### ISSUE TITLE
LDAP Federator Extremely Slow for large numbers of users.

### ISSUE THREAD

**Issue by SomeDeveloper13** [keycloak/keycloak#10005]
### Describe the bug

When the LDAP federator is enabled and a large number of users (100k+) are federated, a significant performance loss to user searches is felt.
Paginated list-all operations no longer work as they timeout, instead.
Even searching by name is extremely slow.

When the federator is disabled, suddenly the searches are nice and quick, but I can't even use this as a temporary solution since it causes the federated users to be disabled.

Note: User search is extremely slow or times out from both the keycloak java client utils & from the keycloak admin console.

### Version

15.0.2

### Expected behavior

Searching for users is expected to be quick from both the java client and the keycloak console.

### Actual behavior

User search is extremely slow or times out from both the keycloak java client utils & from the keycloak admin console when using the ldap federator.

### How to Reproduce?

Create an LDAP Federator with more than 100k users and try to search for all users.
Create an LDAP Federator with more than 100k users and try to search for a user by a common first name.

### Anything else?

Right now the only way we can search is to use the first and last name and the search results still take several seconds to return. Even then they sometimes don't return at all.
Show All Users doesn't return at all.

Not sure if it makes a difference, but:
We have 57 `user-attribute-ldap-mapper`'s and 1 full-name-ldap-mapper.

**Comment by luigimarinucci** [comment]
@

> For me the results are consistent, but extremely slow, or don't return at all with a timeout error (504 and a red error message at the top of the user search page). To get around the issue I had to write an SPI that removes the LDAP calls from the search methods, but leaves it for the sync methods.
> 
> One possible solution is to have a toggle to disable LDAP querying on search operations on the LDAP configuration page. This killed me because it was multiplying the network latency by the number of users returned times two and an additional one to four queries to search for new users. Enabling periodic syncs helped only a little in production, but wasn't enough. My SPI code made the searches nearly instantaneous, but I had to strip out the updates on search to do it.

Hi @SomeDeveloper13,
can you share your workaround? I'm on KeyCloak 16 with 85k users and the performance are very poor.

Thanks
for your support
Luigi

**Comment by ChrissW-R1** [comment]
This issue still exist for us in version 22.0.1.

**Comment by grigoreo-fox** [comment]
I have 16 users in LDAP now and fetching 10 of them takes 5s.
I am on 22.0.1 version.
And why listing is disabled when user federation is enabled?

**Comment by andricDu** [comment]
Still slow in v22.0.1

**Comment by hungry4cheese** [comment]
Still an issue in 22.0.4 as well with postgres as the keycloak database. Noticing sync in the logs for all LDAP providers when searching for users, paginating through users, and displaying users in group memberships. With the number of users above 1000+, the time to display users can take up to 15 seconds.

**Comment by omasseau** [comment]
Hello, same problem here. Tested on Keycloak 15 and Keycloak 22.
Just asking to get the users in a single role (which has 500 ldap users mapped to it) take 12s !
This makes user federation with LDAP almost unusable when we need to make calls the the Keycloak admin API to get user/groupes/roles

**Comment by michelangelo136** [comment]
With the latest Keycloak version 25.0.1 the issue still persists, Netbird tries to fetch the ldap users, even if the realm has 5 users from LDAP it will fail. Is there any way to increase the timeout limit?

**Comment by kbudde** [comment]
Not a fix, just a workaround which may help you:
We created another realm for netbird. This realm allows login using our main realm (with ldap enabled). 
This allows fast login without timeouts.

**Comment by michelangelo136** [comment]
That sounds interesting, is there a guide on how to properly setup Keycloak authentication from one realm to the other?

**Comment by AnthyG-epias** [comment]
Using Keycloak v26.1.3 with a few manually created users and a ldap instance with 10000 users.

Referring to the following Admin REST API call: `GET /admin/realms/{realm}/users`, see https://www.keycloak.org/docs-api/26.1.3/rest-api/index.html#_get_adminrealmsrealmusers

(I'm recalling the numbers from an experiment a colleague and I did last week so take them as approximations rather than exact values)

Using `briefRepresentation=false` caused timeouts when using about `max=2000`.

Using `briefRepresentation=true` didn't cause a timeout when using `max=10000` but it took about 3 minutes.

To make matters worse: using `briefRepresentation=true` and attempting a paginated approach by setting `first=10000` and e.g. `max=1000` actually falls into a timeout again, even tho there's only a few more users on that last page. This means that there's no way to get all users in a paginated manner when ldap is connected.
