### ISSUE TITLE
Issue with PartialImport API - Noticed different behavior between UI and API call

### ISSUE THREAD

**Issue by katariakhyati** [keycloak/keycloak#10008]
### Describe the bug

UI Behavior::

Import the attached test.json file under the keycloak admin UI Partial Import section. 
Resource has been created(user in our case) without any error. Please refer to screenshot-1. No error noticed under UI or Keycloak Server Logs
API Call Behavior::

Trigger PartialImport API from postman as displayed in screenshot-2.
Resource has been created under keycloak, refer to screenshot-3
Received 500 Internal server Error as an API response and following error noticed under Keycloak Server Logs
 

Keycloak Server Log Error(Screenshot-4)::
2021-09-14 04:03:49,455 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-614) Uncaught server error: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: org.keycloak.partialimport.PartialImportResults of media type: application/octet-stream
at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:118)
at org.jboss.resteasy.resteasy-

![Screenshot-1](https://user-images.githubusercontent.com/97315402/152562411-7ea40660-d59e-4daa-a193-7e515d5e0761.png)
![Screenshot-2](https://user-images.githubusercontent.com/97315402/152562416-82c21e9b-7efc-4c8c-8f9c-15d98d2f06ab.png)
![Screenshot-3](https://user-images.githubusercontent.com/97315402/152562418-9ec85581-6023-4083-b448-a2aec7a75ed1.png)
<img width="908" alt="Screenshot-4" src="https://user-images.githubusercontent.com/97315402/152562422-21512082-fa83-450b-b941-0de53e4a95c5.png">

### Version

11.0.3 and 14.0.0

### How to Reproduce?

UI Behavior::

Import the attached test.json file under the keycloak admin UI Partial Import section. 
Resource has been created(user in our case) without any error. Please refer to screenshot-1. No error noticed under UI or Keycloak Server Logs
API Call Behavior::

Trigger PartialImport API from postman as displayed in screenshot-2.
Resource has been created under keycloak, refer to screenshot-3
Received 500 Internal server Error as an API response and following error noticed under Keycloak Server Logs

**Comment by H4pH** [comment]
Just add the "Accept: application/json" HTTP Header in postman
