### ISSUE TITLE
id_token not provided in refresh token response when initial requested scope was openid

### ISSUE THREAD

**Issue by iFrozenPhoenix** [keycloak/keycloak#10013]
### Describe the bug

When a login with scope openid is performed the id_token is returned as part of the response. Before the session expires a refresh is performed with the refresh token. The response only includes an access_token.

### Version

16.1.0

### Expected behavior

The id_token is also provided in refresh responses if the initial request scope included openid.

### Actual behavior

Only the access_token is returned

### How to Reproduce?

Login via API with scope openid. access_token, refresh_token and id_token are included in the response.
When refreshing the token with the provided refresh_token theres just an access token in the response.

**Comment by stianst** [comment]
This is caused by missing oidc scope in refresh request most likely. As we definitely return the id token in refresh requests.

**Comment by iFrozenPhoenix** [comment]
@stianst I performed a device auth request with client_id=*** and scope=oidc. Then the authentication is performed. Then when the authentication was successful I call token auth with client_id=***, grant_type="urn:ietf:params:oauth:grant-type:device_code", scope=openid, device_code=***.
In the response I receive a refresh_token, access_token and id_token, as expected.
Then I use the refresh_token and id_token in kubectl. After the id_token expired kubectl tries to refresh the id_token which leads to the response that the scope openid was either not requested at the initial request or that the provider does not support id_tokens in refreshes.
To verify that it is not a problem with kubectl I manually tried to refresh the token to see the response. The request included grant_type=refresh_token, refresh_token=***, client_id=***, scope=openid. The response was an access_token and scope email, profile.

Am I missing something?

**Comment by stianst** [comment]
Strange. Could you capture the actual request for the authz request and the refresh request?
