### ISSUE TITLE
Keycloak is not capturing proper Signing details(like browser name and version) when logged in from different browsers

### ISSUE THREAD

**Issue by katariakhyati** [keycloak/keycloak#10010]
### Describe the bug

we tried logging to keycloak with chrome , edge and firefox browsers, but we are seeing only chrome details are captured properly. For edge browser it shows as Chrome and for firefox, version its showing incorrect.

All the details must be captured properly
![Device_activity (1)](https://user-images.githubusercontent.com/97315402/152565698-c5a6f189-64b9-42fd-93e0-c1c41d3281f8.png)
![Browser_details (1)](https://user-images.githubusercontent.com/97315402/152565701-48d60e18-cbdf-41b3-8a34-9f0c5895962b.png)

### Version

11.0.2

**Comment by stianst** [comment]
Looks like both Chrome and Firefox are shown properly? Not sure if Edge sends a different user-agent to Chrome and if that even can be differentiated.

**Comment by stianst** [comment]
We're using an old version of UA Parser, updating should resolve these issues
