### ISSUE TITLE
JPA Map Storage: leverage function-based indexes (Postgresql)

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10018]
### Description

Several JPA map stores use a function-based index for the attributes (See the [clients store](https://github.com/keycloak/keycloak/blob/main/model/map-jpa/src/main/resources/META-INF/clients/jpa-clients-changelog-1.xml#L75) for an example). The implementations need to ensure that the queries that would benefit from the index are also using the same function in their WHERE clause. At the moment the function-based indexes are not being leveraged by the stores.

### Motivation

Function-based indexes work if the same function is being used in the query. If we want to leverage the indexes being added to the new JPA map stores we must ensure the searches are using the same function.

### Details

Related to https://github.com/keycloak/keycloak/issues/10017

**Comment by vramik** [comment]
I've investigated query plans with current implementation of postgres database when querying attribute table. Here is how it looks like. I tested it for `kc_client_attribute` table. There is following index: 

```
kc_client_attribute               | client_attr_name_value                                          | CREATE INDEX client_attr_name_value ON public.kc_client_attribute USING btree (name, ((value)::character varying(250)))
```

I have populated the table with some sample data. There is one client with many multi-valued attributes. There are some stats:
```
keycloak=# SELECT count(*) FROM "public".kc_client_attribute;
  count  
---------
 1220052
```
```
keycloak=# SELECT count(*) FROM "public".kc_client_attribute where fk_root = '92b72f07-0c1c-44c8-8ccb-4cdf60007a59';
  count  
---------
 1220012
```
```
keycloak=# SELECT count(*) FROM "public".kc_client_attribute where fk_root = '92b72f07-0c1c-44c8-8ccb-4cdf60007a59' and "name"='test123';
 count  
--------
 400005
```

~200k of the those 400k from above has its value length almost 4k characters

When I run 

```
keycloak=# explain analyze SELECT kc_client.clientid, kc_client_attribute."name" FROM kc_client 
keycloak-# left join kc_client_attribute on kc_client.id = fk_root
keycloak-# WHERE 
keycloak-#     kc_client.realmid = '414d45e5-81af-4417-a12a-4a002e383e3c' 
keycloak-# AND
keycloak-#     kc_client_attribute."name" = 'test123'
keycloak-# AND
keycloak-#     kc_client_attribute."value" = 'VERY_LONG_ATTR_VALUE_SHORTENED_FOR_READABILITY';
```
The query plan looks like:
```
QUERY PLAN
 Nested Loop  (cost=1.30..202.33 rows=1 width=22) (actual time=3.356..3.422 rows=1 loops=1)
   ->  Seq Scan on kc_client  (cost=0.00..59.64 rows=17 width=31) (actual time=0.014..0.050 rows=17 loops=1)
         Filter: ((realmid)::text = '414d45e5-81af-4417-a12a-4a002e383e3c'::text)
         Rows Removed by Filter: 34
   ->  Index Only Scan using kc_client_attribute_fk_root_name_value_key on kc_client_attribute  (cost=1.30..8.38 rows=1 width=23) (actual time=0.198..0.198 rows=0 loops=17)
         Index Cond: ((fk_root = kc_client.id) AND (name = 'test123'::text) AND (value = 'VERY_LONG_ATTR_VALUE_SHORTENED_FOR_READABILITY'::text))
         Heap Fetches: 1
 Planning Time: 9.774 ms
 Execution Time: 3.462 ms
```

So to me it seems that our queries doesn't need any update to work correctly with the index. 

@sguilhen, @ahus1, @hmlnarik could you please take a look and possibly confirm my assumption here?

**Comment by ahus1** [comment]
Hi @vramik - I agree that the query you're using will use an index, and it is sufficiently fast in your example. The index used in the example is `kc_client_attribute_fk_root_name_value_key`, which is for the uniqueness constrint.

At the same time this issue is about function based indexes, and if they are used in query and their query plans. There is an index `client_attr_name_value` which is not used in this query. 

So I suggest to start the investigation with either a function based query, or review the function based indexes where those could be used effectively. 

Side note: When researching for this issue, and how to handle large text columns in indexes, I came across this blog post describing that long texts might have problems to be indexed, and that hashing the text might covercome that potential problem we might have with the unique index on (fk_root, name, value): https://dev.to/rhymes/how-to-build-unique-indexes-in-postgresql-on-large-text-3e6d

**Comment by sguilhen** [comment]
This hashing of texts is really an interesting reading, thanks for sharing @ahus1 !

**Comment by vramik** [comment]
So for I was not able to find a way how to make posgres use the `client_attr_name_value` index. Currently I'm investigating the hashing approach, thanks @ahus1 for pointing this out.

**Comment by vramik** [comment]
As discussed in call, we should create either functional constraint (with hash) on `value` column if possible or create new column with the hash value and create the constraint on that.

**Comment by sguilhen** [comment]
@vramik  and myself tried a few different approaches to add this hashing function. Unfortunately, trying to use an expression in a unique constraint is not possible, so you can't do something like

```
keycloak=# ALTER TABLE public.kc_client_attribute ADD UNIQUE (fk_root, name, (md5(value))) DEFERRABLE INITIALLY DEFERRED;
ERROR:  syntax error at or near "("
LINE 1: ...ic.kc_client_attribute ADD UNIQUE (fk_root, name, (md5(value...
```

Looking around in forums and documentations, it turns out that expressions can be used in unique indexes, but not in the unique constraints. On the other hand, indexes cannot be deferrable or initially deferred. We've even tried to break the constraint creation in two steps: one that creates a unique index, and another one that creates the constraint and makes it use the index:

Step 1:
```
keycloak=# CREATE UNIQUE INDEX abc ON kc_client_attribute (fk_root,name,(sha512(value::bytea)));
CREATE INDEX
```

Works fine. Index is created with the hash function

Step 2:
```
keycloak=# ALTER TABLE kc_client_attribute ADD CONSTRAINT xyz UNIQUE USING INDEX abc DEFERRABLE INITIALLY DEFERRED;
ERROR:  index "abc" contains expressions
LINE 1: ALTER TABLE kc_client_attribute ADD CONSTRAINT xyz UNIQUE US...
                                            ^
DETAIL:  Cannot create a primary key or unique constraint using such an index.
```

Which shows that the constraint creation doesn't allow expressions, detecting the function call in the index.

**Comment by sguilhen** [comment]
The other option we've explored is the usage of another generated column for the hash, and then use the column in the constraint.

```
keycloak=# ALTER TABLE public.kc_client_attribute ADD value_hash VARCHAR(255) GENERATED ALWAYS AS (sha256(value::bytea)) STORED;
ALTER TABLE

keycloak=# ALTER TABLE public.kc_client_attribute ADD UNIQUE (fk_root, name, value_hash) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE
```

Which works fine. Adding some test data:

```
keycloak=# INSERT INTO kc_client_attribute VALUES ('9f0edd00-6e43-4217-8be7-e2d3771c4b16', '9f0edd00-6e43-4217-8be7-e2d3771c4b16', 'anyname', 'along value to test the hashing function');
INSERT 0 1
keycloak=# 
keycloak=# SELECT * FROM kc_client_attribute;
                  id                  |               fk_root                |  name   |                  value                   |                             value_hash                             
--------------------------------------+--------------------------------------+---------+------------------------------------------+--------------------------------------------------------------------
 9f0edd00-6e43-4217-8be7-e2d3771c4b16 | 9f0edd00-6e43-4217-8be7-e2d3771c4b16 | anyname | along value to test the hashing function | \x32ae7edb9530289f0ae992de870e685956da4d25ba7468a9bd3b93548747d0cf
 ```
 
 Checking the constraint:
 ```
 keycloak=# INSERT INTO kc_client_attribute VALUES ('9f0edd00-6e43-4217-8be7-e2d3771c4b18', '9f0edd00-6e43-4217-8be7-e2d3771c4b16', 'anyname', 'along value to test the hashing function');
ERROR:  duplicate key value violates unique constraint "kc_client_attribute_fk_root_name_value_hash_key"
DETAIL:  Key (fk_root, name, value_hash)=(9f0edd00-6e43-4217-8be7-e2d3771c4b16, anyname, \x32ae7edb9530289f0ae992de870e685956da4d25ba7468a9bd3b93548747d0cf) already exists.
```

Which demonstrates it is computing the hashed value and correctly using it in the constraint. It's just unfortunate we can't use the hashing function directly in the constraint, but it is what it is. On the flip side, a new generated column won't affect entity version and thus won't require migration.

**Comment by vramik** [comment]
Created new issue for tackling unique constraints in separate column and closing this one as it was verified we are good with functional based index for attributes.
