### ISSUE TITLE
Keycloak top-level POM uses deprecated configuration value for maven-javadoc-plugin

### ISSUE THREAD

**Issue by jadecristal** [keycloak/keycloak#10019]
### Describe the bug

The top-level POM `keycloak-parent` uses `maven-javadoc-plugin`, which is version-managed by its parent POM at coordinates `org.jboss:jboss-parent:37` and [set to 3.1.1](https://github.com/jboss/jboss-parent-pom/blob/47c355caeeb5160f11d8fc2352d11e35a6ee72b0/pom.xml#L111) at line 111.

The `maven-javadoc-plugin` is used with the configuration value `additionalparam` to disable linting for particular JDK versions, in [current main branch at line 2072](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/pom.xml#L2072); however, the plugin has deprecated/replaced `additionalparam` [since 3.0.0](https://github.com/apache/maven-javadoc-plugin/blob/36b16ca2ad4bc34dcdd222aba79390e03d99bebf/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java#L395) in favor of `additionalOptions`.

The plugin [checks for misuse of the deprecated configuration value](https://github.com/apache/maven-javadoc-plugin/blob/36b16ca2ad4bc34dcdd222aba79390e03d99bebf/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java#L1907) and if it's used [throws an exception](https://github.com/apache/maven-javadoc-plugin/blob/36b16ca2ad4bc34dcdd222aba79390e03d99bebf/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java#L1938).

### Version

16.1.1, or current main

### Anything else?

Suggested fix: replace the `additionalparam` tag with `additionalOptions`—generically, Maven [maps tags to getters](https://maven.apache.org/guides/mini/guide-configuring-plugins.html#generic-configuration) in [an extending class of the Mojo](https://github.com/apache/maven-javadoc-plugin/blob/36b16ca2ad4bc34dcdd222aba79390e03d99bebf/src/main/java/org/apache/maven/plugins/javadoc/JavadocJar.java#L55).

Additionally suggest: requesting parent POM to bump managed version unless there's a conflict, but that's out of scope.

*Additionally*: `maven-javadoc-plugin` is referenced in:
* [distribution/api-docs-dist/pom.xml](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/distribution/api-docs-dist/pom.xml#L41), which is the only place this configuration will be inherited with effect
* [services/pom.xml](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/services/pom.xml#L232) where the plugin version is overridden and the `additionalparam` becomes valid with the [prior version of maven-javadoc-plugin used](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/services/pom.xml#L234); however, if `additionalparam` is intended in that case, for the versions of the JDK used in `<activation>` [for the profile](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/pom.xml#L2062), then the replacement should be handled in that POM and not at the top level where a later version of the plugin is implicitly present from the version-managed parent
* [testsuite/pom.xml](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/testsuite/pom.xml), where the configuration is [completely skipped](https://github.com/keycloak/keycloak/blob/f107f0596ea38b182090bc5cf6f8ca00750132b9/testsuite/pom.xml#L40)

Does this require careful finesse due to build alteration, or would a PR be appropriate?

**Comment by ahus1** [comment]
Hi  @jadecristal - thanks for reporting this. I'm trying to triage this bug and I see that expected behavior and actual behavior are not filled. This makes it difficult for me to understand the impact of the bug you describe. 

Please update the description of the bug.

**Comment by stianst** [comment]
I'm going to close this issue as there is no explanation of when this would be an issue. If you can describe what problem you are facing (i.e. using a specific JVM or Maven version, etc.) please re-open and we will re-avaluate.
