### ISSUE TITLE
GHA Model Tests are still sometimes failing due to timeout

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10016]
### Describe the bug

Model Tests are still failing due to timeouts. I've come across the most recent failure yesterday (Feb 3), when the jpa+cross-dc-infinispan profile timed out. The logs show all tests passed but the build still failed because of the timeout.

### Version

PR/9477

### Expected behavior

Model tests should have finished without any errors.

### Actual behavior

Model tests failed because one of the profiles timed out.

### How to Reproduce?

This failure is intermittent - sometimes after pushing to a PR and re-triggering the GHA tests will lead to the timeout.

### Anything else?

A sample log file showing the failure can be found here:
[8_Run model tests.txt](https://github.com/keycloak/keycloak/files/8005673/8_Run.model.tests.txt)

**Comment by hmlnarik** [comment]
Happened again with #10072 (https://github.com/keycloak/keycloak/actions/runs/1813350082)

**Comment by ahus1** [comment]
The test that fails is CacheExpirationTest. In #10057 I tried to refactor this test a bit for readability. Maybe any further analysis could start after that PR has been merged.

**Comment by ahus1** [comment]
@hmlnarik - the run you linked in your previous comment doesn't contain the commit from #10057 yet.

**Comment by ahus1** [comment]
Assigned this issue to myself and will have a look at those failing on the main branch that already include the change.
