### ISSUE TITLE
IDX_CLIENT_ATT_BY_NAME_VALUE index is missing queries-*.properties variants for postgres and oracle

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10017]
### Describe the bug

https://issues.redhat.com/browse/KEYCLOAK-18617 introduced a fix that uses function-based indexing for postgres and oracle (see [this section](https://github.com/keycloak/keycloak/pull/8341/files#diff-60fd259eebb2db600eac2a6ee5cb0532f269fd6dae8c07e0c6301c11136e5c6cR73-R78) of the associated PR). 

Function based indexes work if the same function is also used in the WHERE clause. This means that we should have postgres/oracle specific properties files in https://github.com/keycloak/keycloak/tree/main/model/jpa/src/main/resources/META-INF with the attribute search queries that leverage the created indexes.

### Version

16.1.0

### Expected behavior

Named queries that perform the attribute search should be leveraging the function-based indexes in postgres and oracle.

### Actual behavior

There are no db-specific queries that leverage the function-based indexes.

**Comment by ahus1** [comment]
Additional information during team discussion: 
* Return parameters for queries might need special handling, see JPA Map store
* Look at table schema support for legacy native queries
