### ISSUE TITLE
Default client scopes of standard clients do not get intialized on realm import causing  'Forbidden' error in the account console

### ISSUE THREAD

**Issue by gunterze** [keycloak/keycloak#10021]
### Describe the bug

When I create a new realm, I only have to enter the name and the standard clients are created automatically and all available Default and Optional Client Scopes are assigned for each client. 

When I export the realm (without group and roles and clients) , delete it and import it again, then the standard clients are created as well, but this time the Assigned Scopes are empty, which causes the 'Forbidden' error in the account console.

s. [KEYCLOAK-16682](https://issues.redhat.com/browse/KEYCLOAK-16682)

Since version 12.0.1

### Version

18.0.0

### Expected behavior

![created-realm](https://user-images.githubusercontent.com/400095/165152749-5162a96c-ccb3-40af-9431-96aa6861399e.png)

### Actual behavior

![imported-realm](https://user-images.githubusercontent.com/400095/165152793-2a3b5699-181b-46da-bdcb-7a98b5d9ad3c.png)

### How to Reproduce?

1. create realm
2. export realm (without group and roles and clients)
3. delete realm
4. import realm

### Anything else?

If I export the realm without group and roles, but with clients, delete it and import it again, then the Assigned Scopes for standard clients get initialized, but now they did not get all of their Roles assigned, e.g.:

Expected Roles:

![created-realm-roles](https://user-images.githubusercontent.com/400095/165154940-2bae4fce-c8cb-488d-a38d-d05284983b5b.png)

Actual Roles:

![imported-realm-roles](https://user-images.githubusercontent.com/400095/165154986-b1cd6115-657f-4aee-a970-8dcddac7e6e9.png)

**Comment by gunterze** [comment]
When I export the realm without group and roles, **but with clients**,  delete it and import it again, then the Assigned Scopes for standard clients get initialized, but now they did not get all of their Roles assigned. Particularly client `Account` only gets Role
- delete-account
- manage-account

**Comment by kami619** [comment]
@hmlnarik 

Apologies on the delay in getting to this issue.

I was able to reproduce part of the issue and can confirm the issue with Roles being truncated from default clients is not reproducible anymore.

Here is the reproduce steps in a video.

Issues resolved: The roles associated with each default client after the export and re-import of the realm are unchanged, which you can also observe in the video.

https://user-images.githubusercontent.com/3415105/201801766-1ed353d9-99e0-4eae-9478-53e980130229.mp4

Partial Issue observed: The number of client scopes associated with each default client seems to be reduced to only one client scope after the export and re-import as shown below.

Before:
![default_client_scopes_realm](https://user-images.githubusercontent.com/3415105/201802049-111154ed-f097-44ac-9457-54aeca2cd71b.png)

After:
![client_scopes_after_partial_import_realm_create](https://user-images.githubusercontent.com/3415105/201802047-b685bdbf-d41d-4544-a913-47706a1512ef.png)

**Comment by ahus1** [comment]
Triage result: The partial export via the UI contains the client scopes. During import those client scopes are re-imported, but this doesn't trigger any logic to assign those scopes to the clients. 

As the export doesn't contain the clients, it the import can't figure out what to do here, as it doesn't know which client should have which client scope assigned. At the same time the import create some essential clients, but doesn't assign them any client roles. 

Similar pattern applies for roles.

To have the clients re-created with the same scopes as in the original realm and with the same roles, create a partial export with roles and clients. 

Another way I found is to create a partial export without clients and roles, then manually delete the `clientScopes`. This will trigger the logic to re-create the client scopes and also assigns them to the clients. In my tests it also setup the client roles as expected. 

@hmlnarik - with the behavior of the partial import and export being complex and not documented, I suggest to remove the two options to skip roles/groups and clients, and to always export them.

**Comment by sahlex** [comment]
This issue still persists in Version 26.2.x as of time reported. Is anybody experiencing this as well?
Could we please reopen this topic?

**Comment by ahus1** [comment]
It didn't get many up-votes, and also no-one contributed a PR. If there are more up-votes, or someone wants to provide a PR, I can re-open the issue.
