### ISSUE TITLE
Admin-API Inconsistent behavior between client and realm scope-mappings

### ISSUE THREAD

**Issue by KreMat** [keycloak/keycloak#10022]
### Describe the bug

When adding (POST /{realm}/clients/{id}/scope-mappings/realm) or removing (DELETE /{realm}/clients/{id}/scope-mappings/realm) realm-level role to a client scope you are experiencing a different behaviour than adding (POST /{realm}/client-scopes/{id}/scope-mappings/clients/{client}) or removing (DELETE /{realm}/client-scopes/{id}/scope-mappings/clients/{client}) a client-level role.

Client-level roles can be added by using the "name" attribute as identifier, whereas for realm-level roles the "id" is needed.

### Version

16.1.1

### Expected behavior

POST /{realm}/clients/{id}/scope-mappings/realm and DELETE /{realm}/clients/{id}/scope-mappings/realm should work with name attribute as identifier.

### Actual behavior

POST /{realm}/clients/{id}/scope-mappings/realm and DELETE /{realm}/clients/{id}/scope-mappings/realm require the role ID to add the client scope.

### How to Reproduce?

Do a POST request against /{realm}/clients/{id}/scope-mappings/realm and provide only the role-name attribute as payload.

### Anything else?

The issue was identified using the keycloak-operator (https://github.com/keycloak/keycloak-operator/issues/436). I am working on a PR to use name attribute as fallback in cases where the role id is not provided in the payload.

**Comment by johgoe** [comment]
@stianst This issue is required to solve https://github.com/keycloak/keycloak-operator/issues/436 which is currently not working.
From my point of view #10026 is a suitable fix.  Can you assign a reviewer from `area/admin/api`-team?
