### ISSUE TITLE
Fix broken CRD descriptions

### ISSUE THREAD

**Issue by fabiobrz** [keycloak/keycloak#10035]
### Description

Looking at e.g.: the [Keycloak CRD](https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml#L84) it looks like the formatting is broken, and it seems it should be fixed by aligning it to have correct new line character, like in https://github.com/keycloak/keycloak-operator/blob/main/deploy/crds/keycloak.org_keycloaks_crd.yaml#L82.

### Motivation

This can improve user experience in integration contexts based on the contract-first approach, where this information can be incorporated in generated Java models. 

### Details

N/A

**Comment by shawkins** [comment]
Resolving as out of date.
