### ISSUE TITLE
Can not set a jgroups stack other than the defaults from Infinispan

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#10052]
### Describe the bug

It is not possible to configure a custom JGroups stack to the cache container but use only those provided OOTB.

Because of that, it is not possible to configure a JGroups stack with additional protocols such as ASYM_ENCRYPT.

The issue does not happen in `16.1.1` but is in upstream/main. It is related to the ISPN upgrade from 13.0.0 to 13.0.5. 

### Version

17.0.0-SNAPSHOT

### Expected behavior

The server must allow user-defined jgroups stacks.

### Actual behavior

The `udp` stack is always set as the JGroups stack, ignoring any custom stack configured in the cache configuration file. The reason is that it is set as a default option value.

### How to Reproduce?

Create a custom JGroups stack by creating a `jgroups-asym-enc.xml` with the following content:

```
<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups-4.2.xsd">
   <!-- jgroups.udp.address is deprecated and will be removed, see ISPN-11867 -->
   <UDP bind_addr="${jgroups.bind.address,jgroups.udp.address:SITE_LOCAL}"
        bind_port="${jgroups.bind.port,jgroups.udp.port:0}"
        mcast_addr="${jgroups.mcast_addr:228.6.7.8}"
        mcast_port="${jgroups.mcast_port:46655}"
        tos="0"
        ucast_send_buf_size="1m"
        mcast_send_buf_size="1m"
        ucast_recv_buf_size="20m"
        mcast_recv_buf_size="25m"
        ip_ttl="${jgroups.ip_ttl:2}"
        thread_naming_pattern="pl"
        enable_diagnostics="false"
        bundler_type="transfer-queue"
        max_bundle_size="8500"

        thread_pool.min_threads="${jgroups.thread_pool.min_threads:0}"
        thread_pool.max_threads="${jgroups.thread_pool.max_threads:200}"
        thread_pool.keep_alive_time="60000"

        thread_dumps_threshold="${jgroups.thread_dumps_threshold:10000}"
   />
   <PING num_discovery_runs="3"/>
   <MERGE3 min_interval="10000"
           max_interval="30000"
   />
   <FD_SOCK/>
   <!-- Suspect node `timeout` to `timeout + timeout_check_interval` millis after the last heartbeat -->
   <FD_ALL timeout="10000"
           interval="2000"
           timeout_check_interval="1000"
   />
   <VERIFY_SUSPECT timeout="1000"/>
   <SSL_KEY_EXCHANGE keystore_name="server.jks"
                        keystore_password="password"/>
<ASYM_ENCRYPT asym_keylength="2048"
                    asym_algorithm="RSA"
                    change_key_on_coord_leave = "false"
                    change_key_on_leave = "false"
                    use_external_key_exchange = "true"
                    />

   <pbcast.NAKACK2 xmit_interval="100"
                   xmit_table_num_rows="50"
                   xmit_table_msgs_per_row="1024"
                   xmit_table_max_compaction_time="30000"
                   resend_last_seqno="true"
   />
   <UNICAST3 xmit_interval="100"
             xmit_table_num_rows="50"
             xmit_table_msgs_per_row="1024"
             xmit_table_max_compaction_time="30000"
   />
   <pbcast.STABLE desired_avg_gossip="5000"
                  max_bytes="1M"
   />
   <pbcast.GMS print_local_addr="false"
               join_timeout="${jgroups.join_timeout:2000}"
   />
   <UFC max_credits="4m"
        min_threshold="0.40"
   />
   <MFC max_credits="4m"
        min_threshold="0.40"
   />
   <FRAG3 frag_size="8000"/>
</config>
```

Create a cache configuration file `conf/cache-ispn-secure.xml`:

```
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

<jgroups>
    <stack name="encrypt-udp" extends="udp">
      <SSL_KEY_EXCHANGE keystore_name="server1.jks"
                        keystore_password="password"
                        stack.combine="INSERT_AFTER"
                        stack.position="VERIFY_SUSPECT"/>
      <ASYM_ENCRYPT asym_keylength="2048"
                    asym_algorithm="RSA"
                    change_key_on_coord_leave = "false"
                    change_key_on_leave = "false"
                    use_external_key_exchange = "true"
                    stack.combine="INSERT_BEFORE"
                    stack.position="pbcast.NAKACK2"/>
    </stack>
  </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="encrypt-udp"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>            
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

Build the server as follows:

```
kc.sh build --cache-config-file cache-ispn-secure.xml
```

Then try to start two server instances where one of them does not have the proper key material to join the cluster.

**Comment by pedroigor** [comment]
Closes https://github.com/keycloak/keycloak/issues/10052.

**Comment by xgp** [comment]
@pedroigor I'm not clear from the above or the commit how to actually use this. For example, I'm working on configuring a stack that uses `JDBC_PING` discovery protocol. I added this to my `conf/cache-ispn.xml` file:
```
...
  <jgroups>
    <stack name="jdbc-ping-tcp" extends="tcp">
      <JDBC_PING connection_driver="org.postgresql.Driver"
                 connection_username="keycloak" connection_password="password"
                 connection_url="jdbc:postgres://postgres/keycloak" level="debug"
                 initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));"
                 info_writer_sleep_time="500"
                 remove_all_data_on_view_change="true"
                 clear_table_on_view_change="true"
                 stack.combine="REPLACE"
                 stack.position="MPING" />
    </stack>
  </jgroups>
...
```
and ran this with:
```
./bin/kc.sh start-dev --cache-config-file=conf/cache-ispn.xml
```
but there is no indication it is actually using this stack. This either isn't fixed, or maybe I'm misunderstanding how to use it?

Thanks!

**Comment by thomasdarimont** [comment]
@xgp I think your JDBC url is wrong. It should be `jdbc:postgresql://...` instead `jdbc:postgres://...`.

The following JDBC_PING stack element worked fine for me with Keycloak 17:
```
    <JDBC_PING connection_driver="org.postgresql.Driver"
               connection_username="keycloak"
               connection_password="keycloak"
               connection_url="jdbc:postgresql://acme-keycloak-db/keycloak"
               initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));"
               info_writer_sleep_time="500"
               remove_all_data_on_view_change="true"
    />
```

**Comment by onepremise** [comment]
I'm encountering issues as well setting up jgroups for infinispan. I've tried both the example here and the previous settings, which i know worked from jboss. I'm not even certain i am doing this right as the online doc seems to lack examples of recommended settings for a migration from jboss to quarkus. I understand the JBOSS setup and it works. However, when we migrated to the new release, all the cluster settings broke and now the cache doesn't stay in sync or seem to sync at all. The following errors(WARN) are encountered when i try to login in clustered mode:

![terminal-capture](https://user-images.githubusercontent.com/1440489/155166226-7eb5b443-3cb3-42ff-b806-b533c8601d14.png)

 When i run the service in standalone mode, everything works fine.

Commands i used to build:

./bin/kc.sh build --cache-config-file conf/cache-ispn.xml
bin/kc.sh --verbose start

conf/cache-ispn.xml:

`
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

  
  <jgroups>
    <stacks>
                <stack name="tcp-ping">
                    
                    <protocol type="org.jgroups.protocols.TCPPING">
                        <property name="initial_hosts">10.1.x.xxx[7600],10.1.x.xxx[7600]</property>
                        <property name="ergonomics">false</property>
                    </protocol>
                    <protocol type="MERGE3"/>
                    <protocol type="FD_ALL"/>
                    <protocol type="VERIFY_SUSPECT"/>
                    <protocol type="pbcast.NAKACK2"/>
                    <protocol type="UNICAST3"/>
                    <protocol type="pbcast.STABLE"/>
                    <protocol type="pbcast.GMS"/>
                    <protocol type="MFC"/>
                    <protocol type="FRAG3"/>
                    <socket-protocol type="FD_SOCK" socket-binding="jgroups-tcp-fd"/>
                </stack>
    <stack name="jdbc-ping" extends="tcp">
      <JDBC_PING connection_driver="org.postgresql.Driver"
                 connection_username="xxxxx" connection_password="xxxxx"
                 connection_url="jdbc:postgresql://hostname:5432/keycloak"
                 initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));"
                 info_writer_sleep_time="500"
                 remove_all_data_on_view_change="true"
                 stack.combine="REPLACE"
                 stack.position="MPING" />
    </stack>
    </stacks>
  </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="jdbc-ping"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
`

**Comment by onepremise** [comment]
Got it working using the following settings, default-jgroups.jdbc:

```
<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups-4.2.xsd">
   <TCP bind_addr="${jgroups.bind.address,jgroups.tcp.address:SITE_LOCAL}"
        bind_port="${jgroups.bind.port,jgroups.tcp.port:7800}"
        enable_diagnostics="false"
        thread_naming_pattern="pl"
        send_buf_size="640k"
        sock_conn_timeout="300"
        bundler_type="no-bundler"

        thread_pool.min_threads="${jgroups.thread_pool.min_threads:0}"
        thread_pool.max_threads="${jgroups.thread_pool.max_threads:200}"
        thread_pool.keep_alive_time="60000"

        thread_dumps_threshold="${jgroups.thread_dumps_threshold:10000}"
   />
   <JDBC_PING connection_url="${jgroups.jdbc.connection_url}"
              connection_username="${jgroups.jdbc.connection_username}"
              connection_password="${jgroups.jdbc.connection_password}"
              connection_driver="${jgroups.jdbc.connection_driver}"
              initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING (
                                  own_addr VARCHAR(200) NOT NULL,
                                  cluster_name VARCHAR(200) NOT NULL,
                                  ping_data bytea DEFAULT NULL,
                                  added timestamp DEFAULT NOW(),
                                  PRIMARY KEY (own_addr, cluster_name)
                                  )"
              remove_all_data_on_view_change="true"
   />
   <MERGE3 min_interval="10000"
           max_interval="30000"
   />
   <FD_SOCK />
   <!-- Suspect node `timeout` to `timeout + timeout_check_interval` millis after the last heartbeat -->
   <FD_ALL timeout="10000"
           interval="2000"
           timeout_check_interval="1000"
   />
   <VERIFY_SUSPECT timeout="1000"/>
   <pbcast.NAKACK2 use_mcast_xmit="false"
                   xmit_interval="100"
                   xmit_table_num_rows="50"
                   xmit_table_msgs_per_row="1024"
                   xmit_table_max_compaction_time="30000"
                   resend_last_seqno="true"
   />
   <UNICAST3 xmit_interval="100"
             xmit_table_num_rows="50"
             xmit_table_msgs_per_row="1024"
             xmit_table_max_compaction_time="30000"
   />
   <pbcast.STABLE stability_delay="500"
                  desired_avg_gossip="5000"
                  max_bytes="1M"
   />
   <pbcast.GMS print_local_addr="false"
               join_timeout="${jgroups.join_timeout:2000}"
   />
   <UFC max_credits="4m"
        min_threshold="0.40"
   />
   <MFC max_credits="4m"
        min_threshold="0.40"
   />
   <FRAG3/>
</config>
```

Then in the default config, cache-ispn.xml, add the following:

```
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

  <!-- custom stack goes into the jgroups element -->
    <jgroups>
        <stack-file name="default-jdbc" path="/opt/keycloak-17.0.0/conf/default-jgroups-jdbc.xml"/>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="default-jdbc"/>
...
```

Use the following command to start:

`sudo su keycloak -c "./bin/kc.sh start --auto-build -Djgroups.jdbc.connection_url=jdbc:postgresql://keycloak-host-name:5432/keycloak -Djgroups.jdbc.connection_username=postgres -Djgroups.jdbc.connection_password=XXX -Djgroups.jdbc.connection_driver=org.postgresql.Driver --cache-config-file=cache-ispn.xml"`

**Comment by dev-e** [comment]
Hi @onepremise ! Cannot get your configuration working with KC 18.0.0. Seems that it just ignored and jgroups do not even try to connect to the database:
```
2022-06-14 00:31:49,881 INFO  [org.infinispan.CONTAINER[] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-06-14 00:31:51,080 INFO  [org.infinispan.CLUSTER[] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `default-jdbc`
2022-06-14 00:31:51,590 DEBUG [org.jgroups.stack.Configurator[] (keycloak-cache-init) set property TCP.diagnostics_addr to default value /IP_ADDRESS_3
2022-06-14 00:31:51,681 DEBUG [org.jgroups.protocols.TCP[] (keycloak-cache-init) thread pool min/max/keep-alive: 0/200/60000 use_fork_join=false, internal pool: 0/4/30000 (1 cores available)
2022-06-14 00:31:51,690 DEBUG [org.jgroups.protocols.MPING[] (keycloak-cache-init) bind_addr=/IP_ADDRESS, mcast_addr=/IP_ADDRESS_2, mcast_port=46655
2022-06-14 00:31:51,770 DEBUG [org.infinispan.remoting.transport.jgroups.JGroupsTransport[] (keycloak-cache-init) JGroups protocol stack: TCP(time_service_interval=500;thread_pool_max_threads=200;ergonomics=true;port_range=10;conn_expire_time=0;recv_buf_size=0;loopback_copy=false;thread_naming_pattern=pl;use_common_fork_join_pool=false;send_buf_size=640000;tcp_nodelay=true;stats=true;buffered_input_stream_size=8192;suppress_time_different_version_warnings=60000;diagnostics_port_range=50;id=57;logical_addr_cache_max_size=2000;suppress_time_different_cluster_warnings=60000;max_length=0;bundler_wait_strategy=park;sock_conn_timeout=300;client_bind_port=0;use_fibers=false;bundler_num_spins=5;use_fork_join_pool=false;enable_diagnostics=false;external_port=0;log_discard_msgs=true;bind_addr=IP_ADDRESS;bundler_capacity=16384;log_discard_msgs_version=true;defer_client_bind_addr=false;use_ip_addrs=false;buffered_output_stream_size=8192;log_accept_error=true;thread_pool_keep_alive_time=60000;thread_dumps_threshold=10000;bind_port=7800;thread_pool_min_threads=0;diag_enable_udp=true;reaper_interval=0;diagnostics_ttl=8;loopback_separate_thread=true;logical_addr_cache_expiration=360000;peer_addr_read_timeout=1000;msg_processing_max_buffer_size=5000;linger=-1;diagnostics_addr=IP_ADDRESS_3;receive_on_all_interfaces=false;diag_enable_tcp=false;max_bundle_size=64000;thread_pool_enabled=true;bundler_type=transfer-queue;logical_addr_cache_reaper_interval=60000;diagnostics_port=7500;who_has_cache_timeout=2000;spawn_thread_on_full_pool=false)
:MPING(send_on_all_interfaces=false;async_discovery_use_separate_thread_per_request=false;ergonomics=true;receive_on_all_interfaces=false;mcast_port=46655;stagger_timeout=0;async_discovery=false;max_rank_to_reply=0;ip_ttl=2;mcast_addr=IP_ADDRESS_2;max_members_in_discovery_request=500;send_cache_on_join=true;num_discovery_runs=3;bind_interface_str=;break_on_coord_rsp=true;stats=true;use_disk_cache=false;bind_addr=IP_ADDRESS;discovery_rsp_expiry_time=60000;id=6;return_entire_cache=false)
:MERGE3(check_interval=48000;stats=true;min_interval=10000;ergonomics=true;id=38;max_participants_in_merge=100;max_interval=30000;only_coords_run_consistency_checker=false)
:FD_SOCK(cache_max_age=10000;get_cache_timeout=1000;sock_conn_timeout=1000;client_bind_port=0;ergonomics=true;start_port=0;port_range=50;suspect_msg_interval=5000;num_tries=3;stats=true;external_port=0;bind_addr=IP_ADDRESS;keep_alive=true;id=2;cache_max_elements=200)
:FD_ALL(use_time_service=true;stats=true;timeout_check_interval=1000;ergonomics=true;interval=2000;id=20;timeout=10000)
:VERIFY_SUSPECT(num_msgs=1;use_mcast_rsps=false;stats=true;ergonomics=true;bind_addr=IP_ADDRESS;id=11;timeout=1000;use_icmp=false)
:pbcast.NAKACK2(resend_last_seqno_max_times=1;use_mcast_xmit=false;ergonomics=true;xmit_table_msgs_per_row=1024;xmit_table_max_compaction_time=30000;become_server_queue_size=50;xmit_interval=200;resend_last_seqno=true;max_xmit_req_size=511600;discard_delivered_msgs=true;suppress_time_non_member_warnings=60000;xmit_table_num_rows=50;stats=true;xmit_from_random_member=false;log_discard_msgs=true;log_not_found_msgs=true;xmit_table_resize_factor=1.2;id=41;max_rebroadcast_timeout=2000;use_mcast_xmit_req=false)
:UNICAST3(ergonomics=true;xmit_table_msgs_per_row=1024;xmit_table_max_compaction_time=30000;ack_threshold=100;sync_min_interval=2000;max_retransmit_time=60000;xmit_interval=200;max_xmit_req_size=511600;conn_close_timeout=5000;conn_expiry_timeout=120000;xmit_table_num_rows=50;stats=true;xmit_table_resize_factor=1.2;log_not_found_msgs=true;id=48)
:pbcast.STABLE(stability_delay=6000;stats=true;ergonomics=true;desired_avg_gossip=5000;max_bytes=1000000;id=13;send_stable_msgs_to_coord_only=true)
:pbcast.GMS(max_join_attempts=10;print_local_addr=false;view_bundling=true;leave_timeout=2000;all_clients_retry_timeout=100;log_view_warnings=true;install_view_locally_first=true;ergonomics=true;use_delta_views=true;use_flush_if_present=true;print_view_details=true;print_physical_addrs=true;join_timeout=2000;max_leave_attempts=10;view_ack_collection_timeout=2000;stats=true;num_prev_views=10;merge_timeout=5000;max_bundling_time=50;num_prev_mbrs=50;id=12;log_collect_msgs=false;membership_change_policy=org.jgroups.protocols.pbcast.GMS$DefaultMembershipPolicy@43f43ef9)
:UFC(min_threshold=0.4;stats=true;ergonomics=true;max_credits=4000000;min_credits=1600000;id=31;max_block_time=500)
:MFC(min_threshold=0.4;stats=true;ergonomics=true;max_credits=4000000;min_credits=1600000;id=30;max_block_time=500)
:FRAG3(frag_size=60000;stats=true;ergonomics=true;id=62)
2022-06-14 00:31:51,793 DEBUG [org.jgroups.protocols.MPING[] (keycloak-cache-init) receiver thread started
2022-06-14 00:31:51,803 DEBUG [org.jgroups.protocols.pbcast.GMS[] (keycloak-cache-init) address=test-keycloak-x-2-37948, cluster=ISPN, physical address=IP_ADDRESS:7800
2022-06-14 00:31:53,870 INFO  [org.jgroups.protocols.pbcast.GMS[] (keycloak-cache-init) test-keycloak-x-2-37948: no members discovered after 2064 ms: creating cluster as coordinator
```
However this line means that the config was loaded correctly:
```
2022-06-14 00:31:51,080 INFO  [org.infinispan.CLUSTER[] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `default-jdbc`
```
What am I doing wrong?

**Comment by hariubc** [comment]
@dev-e  Were the ports opened?

**Comment by hariubc** [comment]
@dev-e  Are ports to be opened (per @onepremise  post)?

**Comment by dev-e** [comment]
Hi @hariubc ! The issue has been resolved with getting rid of the `KC_CACHE_STACK` environment variable. It is not obvious from the docs that this setting has priority over the transport stack specified in the custom infinispan file for the keycloak cache-container. Thanks!

**Comment by pedroigor** [comment]
@dev-e @hariubc Any feedback is welcome around the changes being done to docs. See https://github.com/keycloak/keycloak/pull/13491.

**Comment by jdbrotech1** [comment]
I am running the keycloak 21 gz version on linux and can't for the life of me figure out why infinispan isn't starting correctly. I'm using TCPPING in my xml file and the logs say it's unable to find correct configuration file. I've had this same issue in version 20, too. Why does keycloak make things so hard? Any suggestions?

ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!

xml file:
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">

<jgroups>
<stack name="tcpping" extends="tcp">
<TCP ind_port="7800"/>
<TCPPING initial_hosts="x.x.x.171[7800],x.x.x.172[7800]" max_dynamic_hosts="2" port_range="2" stack.combine="REPLACE" stack.position="MPING"/>
</stack>
</jgroups>
    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>

**Comment by pedroigor** [comment]
@jdbrotech1 Sorry if you have had a bad experience. This configuration is supposed to work and is covered in our tests.

I'll look in more detail at what might be happening.

I've been working on https://github.com/keycloak/keycloak/issues/20397. Does it look similar?

**Comment by jdbrotech1** [comment]
Hi Pedro,

Thank you for replying and reaching out.

Yes, that issue 20397 is exactly what I'm dealing with also.

I have attached some of my files.

I have experienced the issue in version 20 and 21 and have tried jdbc_ping and tcpping. Spent nearly a week on this getting little roi but learning about clustering a little atleast.

Resolved myself to waiting to see if it will be fixed in version 22 until I try again, but if you can help, all the better.
________________________________
