### ISSUE TITLE
Path parameter is missing in the get account endpoint

### ISSUE THREAD

**Issue by razi-ahmad** [keycloak/keycloak#10055]
### Describe the bug

The following path parameter is missing `userProfileMetadata` in the  resource GET: `/account/`

Service Name: `AccountRestService`

### Version

16.1.1

### Expected behavior

Get API of account should not include the profile metadata if false is passed in the path parameter.

### Actual behavior

{"error":"RESTEASY003210: Could not find resource for full path: http://localhost:9000/auth/realms/restaurant/account/false"}

### How to Reproduce?

- Obtain Token
- curl --location --request GET 'http://localhost:9000/auth/realms/restaurant/account/false' --header 'Authorization: Bearer <AccessToken>

**Comment by ahus1** [comment]
I'm triaging this and I see that the path param was added as part of this ticket https://issues.redhat.com/browse/KEYCLOAK-18812 in [AccountRestService.java](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java) in PR #8273

@velias and @pedroigor  - I did a look around and didn't find a test case for "userProfileMetadata" and also no usage in the code for a path parameter "userProfileMetadata". At the same time I wonder if "userProfileMetadata" should be a query parameter and not a path parameter. 

I wonder if you could comment on this. I assigning this to @pedroigor for further actions as it might be related to one of his areas. Please comment if this is not the case.

**Comment by tania2** [comment]
@pedroigor In the version 21.1.2, what is the endpoint for updating the credentials via account? Is there any example on how to call the following endpoint?
I call the following endpoint:
POST realms/{{realm}}/account/password
{
    "currentPassword": "123456",
    "newPassword": "12345",
    "confirmation": "12345"
}

And i get the following response: "error": "RESTEASY003210: Could not find resource for full path: {{host}}/realms/{{realm}}/account/password"

Thank you in advance
