### ISSUE TITLE
White-space separated CLI options are treated as 2 separate options in errorcase

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#10051]
### Describe the bug

As a successor of #9720:

When using e.g. 
`./kc.sh start-dev --db-pasword foo` 

this results in the following output:
`Unknown options: '--db-pasword', 'foo'`

So the key (`--db-pasword`) gets processed, and an `UnmatchedArgumentException` is thrown due to the typo (should be: `--db-password`). In that case, the actual value is treated as a separate options key.

### Version

<=latest

### Expected behavior

output:
`Unknown option: '--db-pasword foo'`

(or even better, just the key, no foo at all, see #10050 for that)

### Actual behavior

output:
`Unknown options: '--db-pasword', 'foo'`

### How to Reproduce?

run e.g. ./kc.sh start-dev --db-pasword foo

### Anything else?

comment from #9720: 
...
"Your comment shows that we also have another issue here, which might be related to our handling of whitespaces, which is not allowed in out of the box picocli as key/var separator. In case of using a whitespace as key/value separator, it seems that the value is handled as another option instead when an exception is thrown, so you get Unknown options: '--nosuch', 'password'."

**Comment by remkop** [comment]
> (...) whitespaces, which is not allowed in out of the box picocli as key/var separator. In case of using a whitespace as key/value separator, it seems that the value is handled as another option instead when an exception is thrown, so you get Unknown options: '--nosuch', 'password'."

I can see how the error message is confusion, so I wanted to clarify:
picocli handles `--option=value` and `--option value` the same way.

When we have user input like `--xxx somevalue`, and there is no option named `--xxx`, then picocli naturally also does not know what to do with the `somevalue` parameter. The error message says "Unknown options", but perhaps this should be refined to:

* only say "Unknown options" when all unmatched arguments [resemble options](https://picocli.info/#_unknown_options_definition)
* say "Unknown arguments" when none of the unmatched arguments resemble an option
* say "Unknown options and arguments" when some but not all of the unmatched arguments resemble an option

I raised https://github.com/remkop/picocli/issues/1567 for this.

The separate issue of suppressing the (potentially sensitive information) option parameter from the error message can probably be dealt with as suggested in https://github.com/remkop/picocli/issues/1565
