### ISSUE TITLE
Custom authentication flows fails when using third party IDP

### ISSUE THREAD

**Issue by marcelomrwin** [keycloak/keycloak#10064]
### Describe the bug

When the browser flow is changed, for example, by removing the user's login from the password if it tries to authenticate with a user that is associated with a third-party IDP, the login responds with error after providing the user name and does not even offer the chance to provide credentials.

### Version

15.0.1

### Expected behavior

Inform the name or email of the user on the screen provided by the **_username form_** and then inform the password on the screen provided by the _**password form**_

### Actual behavior

When informing the user on the _**username form**_ screen, the system responds with an error screen with the text _Cannot Login, credentials setup required_. Internally the exception is:

WARN  [org.keycloak.services] (default task-105) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException: authenticator: auth-password-form

Third party IDP not even triggered

### How to Reproduce?

1. Edit **_browser_** authentication flow by creating a new one
2. Remove _**username password form**_
3. Add a **_username form_** and a **_password form_** (both required)
4. Change the browser's default flow in the bind tab to the new one created in step 1
5. Try to authenticate using a 3rd party IDP user

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by hanzlasarwar366-bit** [comment]
im also getting the same issue, Have you found any solution @marcelomrwin

**Comment by marcelomrwin** [comment]
are you facing this problem in current keycloak version? 26+
