### ISSUE TITLE
Configurable session limits

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#10077]
### Description

- Kill existing sessions is the most common request

- Specify the maximum number of allowable user concurrent sessions. Replace existing session with new one when user logins and the maximum count of sessions per user is already reached. The killed session is the one, which was used last (has oldest lastAccessTime of all user sessions)

- Implementation will use authenticator `user-session-limits`, which can be added to authentication flows. Session limit is the configurable option of the authenticator

- Alternatively, login sends a "maximum sessions" error if the maximum concurrent sessions value exceeds this number. This is an option of the authenticator as well (False by default)

- Last configurable option is "limit of sessions per user and client" . If used, user can have maximum amount of sessions per client.

### Details

See KEYCLOAK-18386

**Comment by danielFesenmeyer** [comment]
Seems to be a great feature. Is there any documentation on it? Did not find anything there about this feature.

**Comment by mposolda** [comment]
@danielFesenmeyer Not yet. It is going to be added soon :-)

**Comment by datacoderid** [comment]
Hi @mposolda,
Is this already available in keycloak 17

**Comment by datacoderid** [comment]
Nvm, I found the feature in Keycloak 17. Thanks guys for releasing this feature 🔥

**Comment by datacoderid** [comment]
Is there a way to send notification if someone login to keycloak when the session already max?

**Comment by mposolda** [comment]
@datacoderid You can try with latest Keycloak main and doublecheck if:
- the event is sent to event SPI when session is already at max
- the events logged with the events SPI contains the necessary event details, which you expect to see.
 
Feel free to propose PR if something does not work as you expect.

**Comment by danielFesenmeyer** [comment]
@kunalgithub: I found that it's documented in the Server Admin Guide, in the step-up-flow section (https://www.keycloak.org/docs/latest/server_admin/index.html#_step-up-flow, see sub-section "User session limits").

@mposolda Because the session limits are not limited to the step-up-flow, it would probably make sense to move this sub-section one level up. WDYT?

**Comment by mposolda** [comment]
@danielFesenmeyer +1, Thanks for catching this. I think it was added by accident as sub-chapter of step-up flow. Would you mind to create GH issue in the keycloak-documentation and send small PR for this?

**Comment by danielFesenmeyer** [comment]
@mposolda Ok, I will provide that PR :)

**Comment by nahidDeve** [comment]
[](url)Hello,

I installed version 18.0.0 of the keycloak for the active session limit option, when I put this option "required" my web application does not work I have an error "invalid username orpassword", and if I put the option to "disabled" the app works correctly.
Can you help me please?
thank you in advance.

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/110980894/183892764-60ca2bf7-3f50-43dd-877c-0b4014c1aebc.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/110980894/183892776-4c184f00-22da-4113-8352-0fa8219c8e6a.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/110980894/183892790-3e95369f-cd8e-4b52-a99e-358dca33a108.png)

**Comment by mposolda** [comment]
@danielFesenmeyer Your PR is merged. Thanks!

@nahidDeve Your configuration is not accurate as you cannot have "alternative" and "required" executions at the same level. In other words, in your new authentication flow, you should add content of the existing "browser" flow as a REQUIRED "subflow" and the "User Session Count Limiter" as the new REQUIRED execution of the top flow. This is not very admin-friendly as the new subflow needs to be created manually (including all authenticators, which you need).

I've created another PR for updating documentation https://github.com/keycloak/keycloak-documentation/pull/1662 with the example. Hope it make it clearer how the flow should be configured with the "User Session Limits".

I also hope that we soon have further improvements in the admin console, which will allow to easily nest the existing flow as a subflow.

**Comment by nahidDeve** [comment]
@mposolda It works now. thank you

**Comment by safvankothawala** [comment]
<img width="699" alt="Capture" src="https://user-images.githubusercontent.com/53424047/193852141-bad24f6f-f945-4c5b-8364-e524dfc255c5.PNG">

Is this the correct configuration. It does not work for me.

**Comment by sschu** [comment]
I would assume the correct structure is something like:
copy of browser - required
-- cookie - alternative
-- username password form - alternative
user session count limiter - required

**Comment by safvankothawala** [comment]
<img width="707" alt="Capture" src="https://user-images.githubusercontent.com/53424047/194999208-ad5bcac1-9992-4482-b8e2-5554f49df093.PNG">
This worked for me !! Thanks.

**Comment by sschu** [comment]
You should probably set username password form to "alternative" otherwise you will get warnings in the logs saying that alternative and required within the same sub flow are not allowed...

**Comment by zaycker** [comment]
could you tell few words please about such solution:
![image](https://user-images.githubusercontent.com/900473/195266389-6415ddc0-960b-4268-9057-8d0db5ab8bd6.png)

**Comment by sschu** [comment]
Indeed. Your approach might work, but you would have to configure the session limit twice if I am not mistaken. I would probably go for:
browser - required
-- cookie - alternative
-- password subflow - alternative
---- username password form - required
user session count limiter - required

You could also add thinks like MFA to the password subflow.

**Comment by geminys** [comment]
> <img alt="Capture" width="699" src="https://user-images.githubusercontent.com/53424047/193852141-bad24f6f-f945-4c5b-8364-e524dfc255c5.PNG">
> 
> Is this the correct configuration. It does not work for me.



> <img alt="Capture" width="707" src="https://user-images.githubusercontent.com/53424047/194999208-ad5bcac1-9992-4482-b8e2-5554f49df093.PNG">
> 
> This worked for me !! Thanks.

I did this configuration and the session limit works, but if I reload the page after login, I am redirected to login page and the I cannot login again as the first session is active.

What am I doing wrong?

Thanks

**Comment by sschu** [comment]
"Required" always wins agains "Alternative". They cannot be on the same level in a flow. Only "Alternative" can be on the same level. That's why I suggested an additional sub flow in my above proposal.

**Comment by geminys** [comment]
Hello

I have changed the configuration, but still not working. I am missing something.

If I reload the page, I get the limit message. 

It is like it does not recognize it as the same session, but it should do it with the cookie, right?

Thank you


![Captura-keycloak](https://user-images.githubusercontent.com/102797446/199463441-78053452-e660-4f49-9dfa-bd982a817e01.JPG)

**Comment by sschu** [comment]
What exactly is happening when you visit the first time without session and what happens if you come with an existing session (if you could create one)?

**Comment by geminys** [comment]
When the limit is set to 1 session per user in the realm, I login in normally and one session is created. 

geminys | 11/3/2022, 8:25:05 AM (started) | 11/3/2022, 8:25:05 AM (last access)

When I reload the page (F5) (one session is already created), the error "too many sessions" shows up, but there is only one session:

geminys | 11/3/2022, 8:25:05 AM (started)  | 11/3/2022, 8:25:54 AM (last access)

If in this moment I change the limit to 2 sessions and reload the page, it works fine and uses the first session created:

geminys | 11/3/2022, 8:25:05 AM (started)  | 11/3/2022, 8:28:04 AM (last access)

Thank you

**Comment by sschu** [comment]
What happens if you start with a limit of two sessions from the beginning?

**Comment by geminys** [comment]
With 2 sessions from the beginning it works fine if I reload in the first browser.
If a login in a second browser, a second session is created.
If I reload in the first borwser now, I get the error of too many sessions.

**Comment by sschu** [comment]
Maybe the limiter always assumes that a new session will be created. Could you try to move the limiter so it only gets executed after the form login when a new session is in fact created?

**Comment by geminys** [comment]
It works!!!!

![image](https://user-images.githubusercontent.com/102797446/199948438-c55010ef-11b1-427e-b03b-df4bddbf35bd.png)

Thank you very much

**Comment by sschu** [comment]
@merikwesterveld The session count limiter from the Login cookie subflow can be removed, since no new session will be created with an existing cookie. Apart from that it looks ok to me. What exactly is the problem?

**Comment by mposolda** [comment]
@merikwesterveld For apply logins also to the IDP logins, it is needed to create new flow called for example `Post Broker Login Flow` and add the `User Session count limiter` as only authenticator to this authentication flow. Then you may need to set this flow as the option `Post Broker Login Flow` to your IDP (or to all your IDPs, which you are using).

This may need to be adjusted if you are already using `Post Broker Login Flow` for your IDPs. For example if you already `Post Broker Login Flow` with 2-factor authentication with OTP, then you may need to add "USer Session Limiter" as additional "required" authenticator to the existing authenticators.

The reason is, that for IDP logins, the "Browser" flow is used just for redirect to the IDP, but the rest of the authentication is done on the IDP side. Then on Keycloak side, there is possibility to use `Post Broker Login Flow` for the authentication steps done after IDP authentication.
This is briefly touched in the docs https://www.keycloak.org/docs/latest/server_admin/index.html#_user_session_limits, but I can see docs surely has some space for improvement. Anyone is welcome to send PR to the docs to improve this.

**Comment by zjesse713** [comment]
Is there an api that allows us to duplicate browser step and add a step for user session limiter?
How would we "move the limiter so it only gets executed after the form login"?

Or this step would require admin to manually handle in the GUI?

**Comment by karolis-mrc** [comment]
Why user session limiter does not work for me? 
![Screenshot 2023-12-06 at 13 29 53](https://github.com/keycloak/keycloak/assets/56818447/86c954e2-d2d6-49da-a45a-6b061ac14721)

**Comment by danielFesenmeyer** [comment]
@karolis-mrc Have you configured your copied flow as Browser flow for your realm or client?

**Comment by karolis-mrc** [comment]
![Screenshot 2023-12-06 at 15 44 43](https://github.com/keycloak/keycloak/assets/56818447/9c9a125a-3ced-4cd8-b97e-8ec80ab73050)
![Screenshot 2023-12-06 at 15 45 15](https://github.com/keycloak/keycloak/assets/56818447/f572c474-d457-41f5-acc2-c19fd2456725)
![Screenshot 2023-12-06 at 15 44 52](https://github.com/keycloak/keycloak/assets/56818447/0549a1b4-ec7e-4c82-8892-96cbc576222c)

**Comment by vaibhavkumbhar1** [comment]
My Usecase is:  For mobile clients, limit should be set to 1 and for other clients: limit per client should be set to 3. 

I had created copy of browser flow and modified it to add session limiter.  It will have default limit of 3
Another flow was created "Browser Flow Mobile" with session limit of 1.
For mobile client I had overridden browser flow.  

This works for keycloak login i.e. with username and password.
But for Social/Idp Login, Currently I can add only post login flow which I cannot override per client.  This causes problems as it  can have only 1 Post Login flow per IDP per realm.

Is there any way that after IDP redirector step and login is completed, I can resume the configured browser flow?
This will solve my problem?
