### ISSUE TITLE
Protocol mapper for "updatedAt" user attribute in "profile" client scope should use number instead of String 

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#10081]
### Describe the bug

- Add some user in the realm . In the tab "Attributes" in the admin console, create the attribute "updatedAt" with the value "1643282255" .

- Generate token for some client for this user. In the token JSON, it can be seen that claim is included as String:
```
  "updated_at": "1643282255",
```
- The expected behaviour is to have this claim included as number instead in the JSON:
```
  "updated_at": 1643282255,
```
As OIDC specification it should be number and not string: https://openid.net/specs/openid-connect-core-1_0-27.html#StandardClaims

This issue is about changing the default type in the protocol mapper for newly created realms. The existing realms does not need to be changed. I consider that when you create new realm and you will see the "updatedAt" in the token as number, we should be fine.

Hint: For testing purposes, it is possible to look how generated token looks in the client evaluatation tab: https://www.keycloak.org/docs/latest/server_admin/index.html#_client_scopes_evaluate

#### Note

This was found during OIDC certification testsuite run. It corresponds to issue 9 from https://docs.google.com/document/d/1yKg_F-pG0NPz3pxLtDc7g288d7jAC8f0leABh50BZn0/edit# .

### Version

16.1.1

**Comment by iingawal** [comment]
@mposolda can you please assign it to me .
