### ISSUE TITLE
Update H2 database

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#10113]
### Description

We should ideally update H2 as it contains a number of CVEs and is very old. However, there's is issues with newer H2, and Quarkus/Hibernate hasn't updated yet:

https://github.com/quarkusio/quarkus/issues/9354

An alternative could be to switch to something else perhaps like Derby? Or, maybe the new file-based map store is ready enough?

**Comment by DGuhr** [comment]
Created a discussion here: https://github.com/keycloak/keycloak/discussions/10295

**Comment by gsmet** [comment]
I created a PR to upgrade H2 in Quarkus here: https://github.com/quarkusio/quarkus/pull/24663 .

The PR shows a couple of examples of issues you might encounter when upgrading.

**Comment by stianst** [comment]
@gsmet can we get that backported to Quarkus 2.7?

**Comment by gsmet** [comment]
Unfortunately, no. It is a breaking change: they added several reserved keywords and this can break applications and extensions.

**Comment by stianst** [comment]
@DGuhr  We could maybe just try to update H2 on our end and see what happes? Or, perhaps we can create a temporary copy of the H2 extension?

**Comment by gsmet** [comment]
Updating H2 won't work in native. The substitutions are very different. What I'm wondering is if we could make the extension in 2.7 support both by having conditional substitutions.
Would you be willing to test a PR if I did this work?

**Comment by stianst** [comment]
We're not using native at the moment, and probably won't for a while, but making 2.7 sounds like a plan and for sure we can test it out.
