### ISSUE TITLE
Specific events for webauthn register

### ISSUE THREAD

**Issue by cbontemps** [keycloak/keycloak#10114]
### Description

Keycloak currently emit specific events for "update password" and "update OTP" but not for "webauthn register" and "webauthnpasswordless register".

The use case is to send the user an email when a new WebAuthn authenticator is registered on his own account. 

What the email template could be : "A WebAuthn authenticator was registered on {0} from {1}. If this was not you, please contact an administrator."

see https://issues.redhat.com/browse/KEYCLOAK-17175

### Motivation

Currently, WebAuthn register events are mixed in type "custom_required_action" which makes them difficult to identify and handle.

**Comment by mposolda** [comment]
@mabartos Sorry for late answer. My vote is to rather have more generic event types like:
`EventType=UPDATE_CREDENTIAL, details { credential_type=password }`
or
`EventType=UPDATE_CREDENTIAL, details { credential_type=webauthn }`
or
`EventType=UPDATE_CREDENTIAL, details { credential_type=webauthn-passwordless }` .

Custom types for each credential doesn't work well with custom 2nd-factor credential types and will require some changes with each type introduced. But it is not a problem if credential has it's own way to add some details (Like EG. "attestation_statement" related details in the case of WebAuthn).

So ideal will be to rather remove types like UPDATE_PASSWORD or UPDATE_TOTP and replace them with something more generic. Same for REMOVE_TOTP for example

**Comment by mposolda** [comment]
For tracking: I've created https://github.com/keycloak/keycloak/issues/32685 for remove the deprecated password/OTP specific events in Keycloak 27
