### ISSUE TITLE
French translation issues for email verification

### ISSUE THREAD

**Issue by SebastianoOlivo** [keycloak/keycloak#10136]
### Describe the bug

Our users receive the following verification email : 

> Quelqu'un vient de créer un compte "App name" avec votre courriel. Si vous êtes à l'origine de cette requête, veuillez cliquer sur le lien ci-dessous afin de vérifier votre adresse de courriel
> 
> https://auth.app.local/auth/realms/app/login-actions/action-token?key=...
> 
> Ce lien expire dans {4}.
> 
> Sinon, veuillez ignorer ce message.

- In french the link caption is replaced by the {0} variable, showing the link instead of the caption you can find in other languages
- The expiration date variable should be {3} and not {4} according to the source code.

### Version

keycloak:16.1.0

### Expected behavior

- Having a caption for the link 
English caption `Link to e-mail address verification`
French proposal : `Lien vers la vérification de l'adresse e-mail`
- For the expiration date the variable should be {3} and not {4}

### How to Reproduce?

- Creating a new account in french will trigger the verification email to be sent

**Comment by ahus1** [comment]
Thanks for reporting this. The translations are community supported, so please consider creating a pull request for this. Thanks!

**Comment by okft** [comment]
Looks like a similar issue was fixed in https://github.com/keycloak/keycloak/pull/8181

Reading [current messages_fr.properties file](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/email/messages/messages_fr.properties), other french translations may need to be fixed.

**Comment by ahus1** [comment]
Thanks @okft - that's exactly the file that needs to be changed. Each PR should address only one issue, therefore, a PR for this issue should only fix emailVerificationBody/emailVerificationBodyHtml. 

If you see other problems, please open a new issue that can then be handled in a separate PR.
