### ISSUE TITLE
Manual SQL migration does not include databasechangeloglock

### ISSUE THREAD

**Issue by JaimySmets** [keycloak/keycloak#10149]
### Describe the bug

When preparing a manual schema migration as described in the [docs](https://www.keycloak.org/docs/latest/server_installation/#database-configuration), the [generated script](https://github.com/keycloak/keycloak/files/8047432/install-schema.txt) does not include the `databasechangeloglock` table.

It includes the `databasechangelog`, but when starting Keycloak afterwards with `initializeEmpty=false` and `migrationStrategy=manual` or `migrationStrategy=validate`, it tries to create the `databasechangeloglock` table.

As I run Keycloak with a user without DDL privileges (script provided to DBA), it fails to boot. There also seems to be no option to tell it to ignore Liquibase in general. Only update/manual/validate is available, which all require the table.

```
09:41:47,382 WARN  [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService] (ServerService Thread Pool -- 64) Failed to create lock table. Maybe other transaction created in the meantime. Retrying...
09:41:47,847 WARN  [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService] (ServerService Thread Pool -- 64) Failed to create lock table. Maybe other transaction created in the meantime. Retrying...
09:41:51,473 WARN  [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService] (ServerService Thread Pool -- 64) Failed to create lock table. Maybe other transaction created in the meantime. Retrying...
09:41:51,477 FATAL [org.keycloak.services] (ServerService Thread Pool -- 64) Error during startup: org.keycloak.connections.jpa.updater.liquibase.lock.LockRetryException: liquibase.exception.DatabaseException: ERROR: permission denied for schema keycloak
  Position: 14 [Failed SQL: CREATE TABLE keycloak.databasechangeloglock (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]
```

### Version

16.1.1

### Expected behavior

Either the `databasechangeloglock` is included in the generated script during manual migration, or Keycloak doesn't require this table during validation. Or an option to ignore Liquibase all around.

### How to Reproduce?

On an empty database (Postgres 13 in my case), run Keycloak with the follow migration settings:

```xml
<provider name="default" enabled="true">
    <properties>
        <property name="dataSource" value="java:jboss/datasources/KeycloakDS"/>
        <property name="initializeEmpty" value="false"/>
        <property name="migrationStrategy" value="manual"/>
        <property name="migrationExport" value="${jboss.server.config.dir}/install-schema.sql"/>
        <property name="schema" value="keycloak"/>
    </properties>
</provider>
```

Inspect the generated SQL file and see it has no `databasechangeloglock` table. It did create the `databasechangeloglock` in the DB, even though it was set to `manual`.

On an empty database, execute the sql file and revoke DDL access of the Keycloak user. Then start Keycloak again with the settings (or remove `migrationStrategy`):

```xml
<provider name="default" enabled="true">
    <properties>
        <property name="dataSource" value="java:jboss/datasources/KeycloakDS"/>
        <property name="initializeEmpty" value="false"/>
        <property name="migrationStrategy" value="validate"/>
        <property name="schema" value="keycloak"/>
    </properties>
</provider>
```

It will fail with the above error.

**Comment by ahus1** [comment]
Hi @JaimySmets - the current status is (as you observed) that even in Manual mode, Keycloak will try to create the databasechangeloglock table. Once it is created (either by Keycloak or by a DBA), it will use this table to lock the schema migration even in manual and validate mode.

I see the point that in manual/validate mode a Keycloak instance might for good reasons not have permissions to create the table. 

To remedy your situation at hand, please forward the SQL statement in the log to your DBA to create the table. 

For the future, I see two options here: 

* Option 1: update the documentation to describe the scenario where Keycloak is not allowed to create a table in the database, and that the table needs to be created first by using the SQL from the log, assuming that this is dependent on the Liquibase version and the database used. Initializing the database would then be a two-step approach: in the first step run Keycloak to get  the lock statement, in a second step run Keycloak to get the migration script.

* Option 2: when in manual mode, don't lock the database, thereby not creating the databasechangeloglock table. Then add it to the SQL created for the manual migration. 

Other things to consider: The database is currently locked for the validate mode, IMHO that would only make sense in a scenario with "validate" is mixed with Keycloak instances that are in "update" mode, as the SQL scripts created from the "manual" mode don't lock schema migration via the databasechangeloglock. Not locking in validate mode could speed up starting up multiple Keycloak instances as they wouldn't synchronize on the lock. 

Please comment on which options you consider as feasible and favorable. // cc: @hmlnarik

**Comment by hmlnarik** [comment]
Table locking takes place upon startup e.g. to [perform initial import](https://github.com/keycloak/keycloak/blob/90d4e586b6ce92c0b4211586ad554a5a07566417/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L134), so the table needs to be created.

I agree that it should be part of the SQL script. For the immediate workaround, please create the table manually according to https://docs.liquibase.com/concepts/basic/databasechangeloglock-table.html.

For dev / testing purposes, you could leverage `none` lock but never do this in production:
```
/subsystem=keycloak-server/spi=dblock:add(default-provider=none)
```

Sidenote: Locking will change in the new storage: #9388.

**Comment by ahus1** [comment]
For Option 1 (improving the docs) we're looking for a community contribution. It should document the current behavior, and how the necessary table databasechangeloglock can be created, either from Keycloak's log or the Liquibase documentation. 

How and if the databasechangeloglock should be created will be discussed in the issue referenced above, and not in this issue.
