### ISSUE TITLE
Support for acr_values_supported in OIDC well-known endpoint

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#10159]
### Description

[OIDC Discovery specification](https://openid.net/specs/openid-connect-discovery-1_0.html) introduced `acr_values_supported` for OIDC server to return supported acr values. Keycloak currently does not return anything in it.

We can add configuration option `ACR-to-LoA` mapping, which is currently at client level, also to the realm level. When request is evaluated with the `acr` sent in claims or acr_values, the "client" mapping has preference, then "realm" mapping and finally fallback to number values.

The `acr_values_supported` in Well-Known endpoint can directly return values specified by the realm mapping.

In case that `Acr-to-Loa` mapping is not filled for the realm, the Well-Known endpoint can just browse through the authentication flow bind to the realm browser and figure if there are any LoA conditions and return the number values specified by these conditions.

### Discussion

#10120

**Comment by tnorimat** [comment]
@mposolda In Description, the link of OIDC Discovery specification is for OIDC Dynamic Client Registration. It should be https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by mposolda** [comment]
@tnorimat Good point! Fixed
