### ISSUE TITLE
Alert: Update of read-only attribute rejected

### ISSUE THREAD

**Issue by 9p4** [keycloak/keycloak#10166]
### Describe the bug

When using the account console, if you change a value (such as first name) to something and press enter, it will work. If you change it again without reloading the page, we get an error: `Alert: Update of read-only attribute rejected`. Refreshing the page will allow the value to be changed again.

### Version

17.0.0

### Expected behavior

The value should change and a success message should be shown.

### Actual behavior

The value remains the same and an error message appears

### How to Reproduce?

Load the user console. Change a value, then change it again.

### Anything else?

Accounts are federated via LDAP

**Comment by ssilvert** [comment]
We aren't working on the old admin console any more so I'm going to close this issue.  If you see a similar issue in the new `admin.v2` console, we can reopen.

**Comment by tania2** [comment]
I am using the keycloak version 21.1.1, and i have created a custom provider using the LegacyUserCredentialManager. For the users i am creating via api HTTPPOST {{host}}/admin/realms/{{realm}}/users, i am getting the error "You can't update your username as it is read-only." when i am trying to update the info via the admin ui. Any recommendations?

Thank you in advance.
