### ISSUE TITLE
JPA map storage: remove dependency on the model-jpa module

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10192]
### Description

Currently, the `model-map-jpa` module has a `mvn` dependency on the legacy `model-jpa` module. Given that the legacy JPA implementation will be eventually deprecated and removed in the future, we need to remove this dependency and ensure that the `model-map-jpa` module can operate on its own.

### Motivation

Allow future removal of the legacy JPA storage without impacting the new storage.

**Comment by hmlnarik** [comment]
See also #8903

**Comment by hmlnarik** [comment]
Resolved in #11597
