### ISSUE TITLE
UserSession is not attached after Consent-Required-Action

### ISSUE THREAD

**Issue by a-pany-rise** [keycloak/keycloak#10199]
### Describe the bug

We have implemented an `Authenticator` which attaches the current authenticationContext to an existing UserSession.
Attaching to the existing session is done by calling `context.attachUserSession(existingUserSession)` in the Authenticators `authenticate(final AuthenticationFlowContext context)` method.
	
This Authenticator is configured in a BrowserLoginFlow for a Client which requires OIDC consent to be given.
	
Authentication with this Flow finally results in 2 UserSessions. The original session we wanted to attach, and new UserSession created during the BrowserLoginFlow.
	
Attaching to an existing UserSession works as expected in the BrowserFlow, as long as the clients consent requirement is disabled.

### Version

12.0.1

### Expected behavior

Client is added to an existing UserSession after authentication and giving oidc-consent during a Browser-Login-Flow.

### Actual behavior

A new UserSession for the Client is created.

### How to Reproduce?

Setup:
		- Configure ClientA 
		- Configure ClientB requiring OIDC Consent
		- Configure BrowserLoginFlow for ClientB with an Authenticator which attaches to an existing UserSession of ClientA.
	
	- Login to ClientA
	  The admin interface shows a single session for the user for ClientA.
	  
	- Login to ClientB
	  Check the admin interface after giving the consent to complete the login flow. It now shows two separate sessions for the  user. 

### Anything else?

- No changes to `AuthenticationProcessor.attachSession(...)` were made in the source code until Version 16, so I assume the problem still persists.  
	
- Not attaching sessions correctly might be caused by executing other RequiredActions as well.
	
- A comment in `AuthenticationProcessor.authenticationComplete(...)` states that "// Session will be attached after requiredActions + consents are finished."
I haven't been able to find any code attaching the session which was provided in the authentication during or after evaluation of consents.
      
- I have implemented a temporary solution to attach the Session for our application:
      1) In AuthenticationProcessor.attachSession(UserSessionModel userSession)
         Add the sessionId to be attached as `authNote` to the authenticationSession
      2) In LoginActionsService.processConsents()
         Find the Session stored in the `authNote`and attach it with `AuthenticationProcessor.attachSession(AuthenticationSessionModel authSession, UserSessionModel userSession, ...)`
     
It will attach the session properly, and as far as I can see there shouldn't be any adverse effects on the rest of the application.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by mposolda** [comment]
This issue is reported against very old release. Also it is possible that this issue in custom authenticator as the built-in `CookieAuthenticator`, which also attach userSession, works as expected with latest Keycloak 24 release.
