### ISSUE TITLE
User search with LDAP federation not consistent

### ISSUE THREAD

**Issue by cedric780** [keycloak/keycloak#10195]
### Describe the bug

When Keycloak is connected to an LDAP federation the user search is inconsitent, either in the GUI or via REST API.

See "How to reproduce".

### Version

15.0.02

### How to Reproduce?

1. Add an LDAP federation toward any LDAP containing a user named "Martin" with the following configuration:
   -  Edit mode : READ_ONLY
   - sync settings" all synchronizations disabled
   - cache settings : Cache Policy=DEFAULT
1. Open the administration console, go to "Users" sections
1. In the search field type "Ma" and click on the magnifier button
   ==> no result
1. In the search field type "Ma*" and click on the magnifier button
  ==> Martin is found and imported in Keycloak
1. click on the magnifier button again
  ==> no more result !!
1. In the search field type "Ma" and click on the magnifier button
  ==> Martin appears !

### Anything else?

I think the issue comes from:
https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L361

The implementation does not match the API that tells :

>  If possible, implementations should treat the parameter values as partial match patterns(i.e. in RDMBS terms use LIKE). 

The implementation passes the search nearly as is.
To be consistent with local database search, LDAPStorageProvider should :
- Trim search expression of already present '*' chars
- Suffix search expression with '*'
- For performance reasons **not** prefix search expression  with '*', see  #10005

**Comment by SomeDeveloper13** [comment]
@cedric780 - Are you getting 504 errors?

**Comment by cedric780** [comment]
@SomeDeveloper13 - No, I always have HTTP 200 .
I just saw Keycloak 17 was released, and it seems search syntax has changed, supporting '*' wildcard chars.
I am using Keycloak 15.0.2 and I am not able to upgrade it for the moment.

**Comment by hmlnarik** [comment]
@cedric780 Would you be able to recheck with the latest Keycloak (20)?

**Comment by mhajas** [comment]
I would say this is a valid issue. We have some differences in searching implementations for JPA and LDAP. If I am not mistaken, for JPA asterisk search is not allowed while for LDAP it is. Then it is causing issues like those mentioned in this report.

Here is a model test I created as a playground to help reproduce. I could not reproduce step 5 but I still think the report is relevant. The test can be put to [`UserSyncTest`](https://github.com/keycloak/keycloak/blob/main/testsuite/model/src/test/java/org/keycloak/testsuite/model/UserSyncTest.java) class and run with profile: `legacy-jpa-federation+ldap+infinispan`

```java
@Test
public void testIssue10195() {
    // Add 5 users to ldap
    IntStream.range(0, 5).parallel().forEach(index -> inComittedTransaction(index, (session, i) -> {
        final RealmModel realm = session.realms().getRealm(realmId);

        ComponentModel ldapModel = LDAPTestUtils.getLdapProviderModel(realm);
        LDAPStorageProvider ldapFedProvider = LDAPTestUtils.getLdapProvider(session, ldapModel);
        LDAPTestUtils.addLDAPUser(ldapFedProvider, realm, "user" + i, "User" + i + "FN", "User" + i + "LN", "user" + i + "@email.org", null, "12" + i);
        return null;
    }));

    // Change ldap setting to match report
    withRealm(realmId, (session, realm) -> {
        UserStorageProviderModel providerModel = new UserStorageProviderModel(realm.getComponent(userFederationId));
        providerModel.getConfig().putSingle(LDAPConstants.EDIT_MODE, UserStorageProvider.EditMode.READ_ONLY.toString());
        providerModel.getConfig().putSingle("cachePolicy", "DEFAULT");

        realm.updateComponent(providerModel);

        return null;
    });

    // Step 3
    withRealm(realmId, (session, realm) -> {
        List<UserModel> collect = session.users().searchForUserStream(realm, Collections.singletonMap(UserModel.SEARCH, "us")).collect(Collectors.toList());
        System.out.println(collect.size());
        return null;
    });

    // Check if users were imported to local storage
    System.out.println("local search " + (int) withRealm(realmId, (session, realm) -> (int) UserStoragePrivateUtil.userLocalStorage(session).searchForUserStream(realm, Collections.singletonMap(UserModel.SEARCH, "us*")).count()));

    // Step 4
    withRealm(realmId, (session, realm) -> {
        List<UserModel> collect = session.users().searchForUserStream(realm, Collections.singletonMap(UserModel.SEARCH, "us*")).collect(Collectors.toList());
        System.out.println(collect.size());
        return null;
    });

    // Step 5
    withRealm(realmId, (session, realm) -> {
        List<UserModel> collect = session.users().searchForUserStream(realm, Collections.singletonMap(UserModel.SEARCH, "us*")).collect(Collectors.toList());
        System.out.println(collect.size());
        return null;
    });

    // Step 6
    withRealm(realmId, (session, realm) -> {
        List<UserModel> collect = session.users().searchForUserStream(realm, Collections.singletonMap(UserModel.SEARCH, "us")).collect(Collectors.toList());
        System.out.println(collect.size());

        return null;
    });
}
```

This prints result:
```
0
local search 0
5
5
5
```
