### ISSUE TITLE
The CodeQL analysis is broken due to the large content of the generated SARIF file

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#10203]
### Describe the bug

The CodeQL analysis is broken due to the large content of the generated SARIF file.

### Version

17.0.0

### Anything else?

Ref: This is a follow up of https://github.com/keycloak/keycloak/pull/10108#issuecomment-1036180254

**Comment by andreaTP** [comment]
Is it an option to temporary disable the codeql analysis until we have a solution?

Currently the CodeQL analysis job in GH Action is keeping busy 1 runner for 40 minutes for each PR (out of 20 total runners available), this is seriously impacting every PR validation performance.

**Comment by abstractj** [comment]
@andreaTP please let's use this issue to discuss the solution. For requests like that, we can use other communication channels.

**Comment by DGuhr** [comment]
I just found https://github.com/github/codeql-action/issues/820, seems to be kind of the same issue. perhaps we should also post a failing workflow run there and see if they provide some sugggestions? Also, there seems to be some suggestions inside (just scanned over it, though)

**Comment by abstractj** [comment]
_Update:_

The GitHub documentation states that [`paths-ignore` is only available in the context of interpreted languages](https://docs.github.com/pt/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan), for compiled languages like Java it's necessary to [change the build steps](https://docs.github.com/pt/code-security/secure-coding/configuring-the-codeql-workflow-for-compiled-languages#adding-build-steps-for-a-compiled-language) to exclude the directories we need like: testsuite, examples, etc.

For that, it's necessary to disable remove the `autobuild` from the CodeQL workflow and provide the custom build steps. The initial attempt was to skip all the tests, and also the adapters, but that did not reduce the size of the SARIF file, nor prevented the compilation of the testsuite:

```
- if: matrix.language == 'java' 
      name: Build Java
      run: |
        cd quarkus && mvn -f ../pom.xml clean install -Dmaven.test.skip -DskipAdapters -DskipTestsuite -DskipExamples -DskipTests
```
You can find the complete file [here](https://gist.github.com/abstractj/d3ad23ba2fef9ae0ae5b97e43d0e93a2). @JoshuaMulliken and may have other ideas. If there's anything that you would like to suggest as a fix, please let us know.
