### ISSUE TITLE
Unable to create users in realm using API when multiple instances are running

### ISSUE THREAD

**Issue by eshipper-ca** [keycloak/keycloak#10212]
### Describe the bug

We set up Keycloak on an AWS EC2 instance. Details of the set up are as follows:

```
OS: Amazon Linux 2
Java: OpenJDK 11.0.10
Keycloak: 12.0.3
```

This instance is behind an Application Load Balancer and is running using the `standalone-ha` configuration. Only one change has been made to the standard configuration file - details for the database to use.

We connect to this instance from a Spring Boot application using the REST API. We are able to create, authenticate and manage users just fine with this single instance. The overall set up can be visualized as shown below.

```
          -----------------
         |      Spring     |
         |       Boot      |
         |   Application   |
          -----------------
                  ^
                  |
                  v
          -----------------
         |   Application   |
         |       Load      |
         |     Balancer    |
          -----------------
                  ^
                  |
                  v
          -----------------
         |     Keycloak    |
          -----------------
```

We set up an identical instance in another availability zone and put the new instance behind the load balancer as well, with sticky sessions and round-robin load balancing. The modified set up can be visualized as shown below.

```
                         -----------------
                        |      Spring     |
                        |       Boot      |
                        |   Application   |
                         -----------------
                                 ^
                                 |
                                 v
                         -----------------
                        |   Application   |
                        |       Load      |
                        |     Balancer    |
                         -----------------
                                 ^
                                 |
                   ----------------------------
                  |              #             |
                  v              #             v
          -----------------      #     -----------------
         |     Keycloak    |     #    |     Keycloak    |
          -----------------      #     -----------------
                                 #
                                 #
         Availability Zone A     #    Availability Zone B
                    Subnet A     #               Subnet B
```

The instances are running across two separate availability zones (data centers), so we are not expecting the instances to form a cluster, which is substantiated by the fact that logs do not contain anything about a cluster.

With this modified set up, the Spring Boot application is able to authenticate users without any problem. Users can remain signed-in for any amount of time.

However, the application is no longer able to create or modify users - it receives HTTP 401 errors from the Keycloak REST API for such requests. Debug logs do not contain anything related to the failing requests to aid us in our investigation.

Running with any one of the instances, regardless of which one is left running, restores the original behaviour.

Need help on how to investigate this further and fix it.

### Version

12.0.3

### Expected behavior

Users can be created, authenticated and modified through the REST API.

### Actual behavior

Users can be authenticated successfully through the REST API, but creation and modification fail with HTTP 401 errors.

**Comment by stianst** [comment]
This is due to the fact that sessions which are stored in caches across the nodes. Having multiple separate clusters like this is deemed to have issues such as these and also caches containing outdated entries.

If you want multiple availability zones you need to setup clustering across them or use Infinispan to bridge the two clusters.

**Comment by eshipper-ca** [comment]
@stianst, thanks for the quick update. Is there any documentation on how to set up clustering for Keycloak in an AWS environment like this?

Appreciate your help on this.
