### ISSUE TITLE
RelayState max length not respected

### ISSUE THREAD

**Issue by evtr** [keycloak/keycloak#10227]
### Describe the bug

According to 3.5.3 in the specification
https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
"RelayState data MAY be included with a SAML protocol message transmitted with this binding. The valueMUST NOT exceed 80 bytes in length and SHOULD be integrity protected by the entity creating themessage independent of any other protections that may or may not exist during message transmission"
Keycloak does not respect this.

### Version

17.0.0

### Expected behavior

Keycloak should respect the length restriction.

### Actual behavior

The relay state length restriction is not enforced

### How to Reproduce?

Test will be provided

**Comment by ahus1** [comment]
There is a community PR #10231 open that requires a review. 

I see two people voted "thumbs up" for this issue: A review would include (but wouldn't be limited to) that the implementation aligns with the specification, and if people think it might break existing implementations. Thanks!
