### ISSUE TITLE
Separate probes toggle from metrics

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10224]
To use the liveness (`/health/live` endpoint) and readiness (`/health/ready` endpoint) probes, you currently need to enable the `kc-metrics-enabled` toggle which effectively enables all metrics (`/metrics` endpoint). This is not a correct approach e.g. for operator deployments as we'd need to have metrics enabled even when not needed.

We should have a separate toggle for probes and for other metrics.

**Comment by DGuhr** [comment]
@pedroigor @stianst I second this, it makes it possible to use the probes, e.g. in the operator, without necessarily exposing the metrics, where we still have the protection problem (at the moment you'd need to not expose them using a reverse proxy or similar, as quarkus doesn't have support for e.g. exposing on different port).

So one could say "I want to use the operator/deploy to k8s in a reliable manner, but i don't nessecarily need metrics, and definitely not exposed metrics which i have to disable in my reverse-proxy".

Idea:
Provide a 
`--probes-enabled=true/false` option and remove the coupling from the `metrics-enabled`.

 or e.g. `health-enabled=true/false`, `healthchecks-enabled=true/false`
