### ISSUE TITLE
Map storage: components are unable to use the same storage with different configurations

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10226]
### Describe the bug

Consider the following configuration:

```
    "mapStorage": {
            ...     
            "jpa-map-storage": {
                # some db configuration - e.g. a postgres running on hostA
            }
    },
    
    "role": {
        "provider": "map",
        "map": {
            "storage": {
                "provider": "jpa-map-storage"
                # ends up using the root jpa-map-storage as configured above
            }
        }
    },

    "client": {
        "provider": "map",
        "map": {
            "storage": {
                "provider": "jpa-map-storage",
                "jpa-map-storage": {
                        # different configuration - e.g. this would retrieve the clients from a cockroachDB  or another postgres running on hostB
                }
            }
        }
    }
```

The new storage has been designed to support this kind of configuration, where we can have different components using the same storage implementation but with different configurations. So it should be possible to, for example, use the JPA implementation to load users from a particular DB instance and load everything else from a different DB.

However, this is currently not possible. In the example above, the `role` and the `client` components are both mapped to the same `componentId` (`mapStorage-f:ROOT:jpa-map-storage`) [here](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/models/utils/KeycloakModelUtils.java#L329) and this is problematic because the `DefaultComponentFactoryProviderFactory` caches the loaded factories by the `componentId` (see code [here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultComponentFactoryProviderFactory.java#L89)).

This means that the first component that is loaded (in the example above, `role`) gets to instantiate the storage factory with its configuration and the subsequent components that resolve to the same `componentId` (in our example, `client`) end up using the same cached factory, regardless of configuration. In our example, both components end up using the same DB as opposed to us having the roles and clients in separate DBs.

### Version

17.0.0

### Expected behavior

The configuration should be taken into consideration when loading the storage factory for a component and different configuration of the same provider should lead to separate storage factories being loaded for each component.

### Actual behavior

The first component that gets processed ends up initializing and caching the storage factory with its configuration and all other components that resolve to the same `componentId` are using this cached storage factory.

### How to Reproduce?

Simplest way to reproduce is to follow the example shown in the description, where one component (e.g. `role`) is configured to use one DB, and another component (e.g. `client`) is configured to use a different DB. Both will end up in the same database.

**Comment by hmlnarik** [comment]
To add on top of that, sometimes we want to share a configuration across the areas. In that case, we need to be able to reference the same configuration, e.g. by addding a name to it.

**Comment by sguilhen** [comment]
I've started a discussion (https://github.com/keycloak/keycloak/discussions/10324) on the possible ways to fix this.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's codebase. Follow #24111 for the removal steps.
