### ISSUE TITLE
Locale Setting for Update Password Mail

### ISSUE THREAD

**Issue by herrmannkathrin** [keycloak/keycloak#10233]
### Describe the bug

Hi there,

I currently have a problem with the language of the Update password Mail and would be happy, if somebody could help. :)

When a keycloak administrator chooses to send an Update Password mail to a user, who has not set any locale in the user profile, the mail seems to be send in the language derived from the Accept language header of the logged in administrator. 

In our context (the system will be administered by German speaking personnel, but will have international users) this would lead to the undesired effect that for example korean users will get German Update password mails.

According to https://issues.redhat.com/browse/KEYCLOAK-4583 the process to get the best locale for a user is
Locale cookie
User (if authenticated)
"Accept-Language" header
Realm default (if set)
English

I think this works perfectly for login, account, admin themes, but for email themes the order should maybe be 
User (if locale is set in user profile)
Realm default (if set)
English

Best Regards,
Kathrin

### Version

16.1.0

### Expected behavior

If the user attribute "locale" is empty, the user should receive the Update Password mail sent from the keycloak admin console in the realm default language (if existing) or in English.

### Actual behavior

If the user attribute "locale" is empty, the user seems to receive receive the Update Password mail sent from the keycloak admin console in the language that the admin sending the mail is sending in his/her Accept language header.

### How to Reproduce?

Prerequisites: 
- Internationalization is enabled for the realm. 
- Default language for the realm is set to e. g. English.
- Admin is logged into keycloak admin console
- Accept language header of the admin is e. g. German

1) Create user in keycloak without setting a value for the locale.
2) Send Update Password Mail via Credentials tab.

**Comment by KapowraLL** [comment]
Yeah it's clear that `user locale => realm default language => english` would be a much better fallbacking for emails language
