### ISSUE TITLE
Trying to register SPI causes build step error

### ISSUE THREAD

**Issue by CollinAlpert** [keycloak/keycloak#10230]
### Describe the bug

I have written a User Storage Provider and it worked fine in versions before 17. When trying to register it with Keycloak 17, I get the exception message: 
`Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureProviders threw an exception: java.util.ServiceConfigurationError: org.keycloak.provider.Spi: org.keycloak.locale.LocaleSelectorSPI not a subtype`

I have reproduced this issue using Java 11 and 17 on both Windows and Linux.

### Version

17.0.0

### Expected behavior

When I copy the JAR file into the `providers` directory and run `./kc.sh build`, a success message is printed and the provider is registered.

### Actual behavior

The following error is printed:
![image](https://user-images.githubusercontent.com/14217185/154097556-dafd026c-0919-485e-80bd-05fa701ae198.png)

### How to Reproduce?

1. Create an Provider and a ProviderFactory class. No special logic aside from the implementations are required.
2. Register the Factory class in the META-INF/services/org.keycloak.storage.UserStorageProviderFactory file.
3. Create the JAR file using `mvn clean compile assembly:single`
4. Copy the JAR file into Keycloak's `providers` directory.
5. Run `./kc.sh build`

### Anything else?

My folder structure:
![image](https://user-images.githubusercontent.com/14217185/154098410-3d67b008-5842-42d7-897f-3bfe7fd9bdc4.png)

My `pom.xml` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.collinalpert</groupId>
    <artifactId>my-user-provider</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>11</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.release>${java.version}</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <version>17.0.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <finalName>my-user-provider</finalName>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by DamienBoue** [comment]
I got exactly the same error has you you on my SPI with the same build step

i am compiling on java 11

**Comment by CollinAlpert** [comment]
Yeah, very weird, since I even managed to reproduce it with a minimal example. Is this some kind of regression with the SPI handling? I'd really like to know the reason for this.

**Comment by stianst** [comment]
What's the content of your built JAR? At a quick glance it looks like you may be including Keycloak dependencies within the JAR?

**Comment by CollinAlpert** [comment]
@stianst Yes, I definitely am. Should I not be doing that? I remember having problems in earlier versions if I didn't package all dependencies inside the JAR.

**Comment by stianst** [comment]
On Quarkus there's a single classpath, while on WildFly each deployment had its own classpath. This changes things a bit. You should not include dependencies already existing in the dist, and for other things shaded jar should work, but it may be better to deploy those dependencies separately to the provider directory.

**Comment by CollinAlpert** [comment]
Adding `<scope>provided</scope>` to the Keycloak dependencies solved my issue. Thanks!

**Comment by DamienBoue** [comment]
I add it to my pom and it works perfectly now! Thanks!

**Comment by CollinAlpert** [comment]
@pedroigor I'm not sure how that helps in my case. I was copying too many dependencies into the JAR. Am I missing something?

**Comment by dishi-github** [comment]
Thank you so much. I had the same issue with keycloak 18 and this post sort of fixed my issues for once due to the detailed steps provided to reproduce it. Thanks again! Appreciate!

**Comment by jiazanrong610104084** [comment]
感谢，很好用。解决了我的问题

**Comment by YashKakrechaInexture** [comment]
Changing `compile` to `compileOnly` in my build.gradle fixed the issue.
