### ISSUE TITLE
ConfigurationTest can not run on Windows

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#10246]
### Describe the bug

Due to use of paths like `/tmp/` and `~/` the tests can not execute on Windows:

https://github.com/keycloak/keycloak/blob/8938a5be35d952745f052417e0fc0ec64ae1ac7b/quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java#L328

https://github.com/keycloak/keycloak/blob/8938a5be35d952745f052417e0fc0ec64ae1ac7b/quarkus/runtime/src/test/java/org/keycloak/quarkus/runtime/configuration/test/ConfigurationTest.java#L240

### Version

main

**Comment by anantk24** [comment]
I have already raised [PR ](https://github.com/keycloak/keycloak/pull/10240)for this. You can assign this to me . Please review.
