### ISSUE TITLE
Unstable test AuthenticationFlowCallbackProviderTest.errorWithCustomProvider

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#10284]
### Describe the bug

This test failed in a PR that is not making any relevant changes:
https://github.com/keycloak/keycloak/runs/5216281797?check_suite_focus=true

Full log here:
[30.txt](https://github.com/keycloak/keycloak/files/8087270/30.txt)

### Version

main

### Expected behavior

* Tests pass on every run

### Actual behavior

* Unexpected failure in AuthenticationFlowCallbackProviderTest.errorWithCustomProvider

**Comment by mabartos** [comment]
Duplicate of #10225 and related to #10268.
