### ISSUE TITLE
Expose deployment errors in the status field of Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10285]
The operator should propagate any relevant errors to the Keycloak CR. They should be exposed in the `HasErrors` condition in the status field. This includes as many deployment errors reported by the K8s as possible. Leverage [Deployment conditions](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment). E.g.:
* ImagePullBackOff
* Replica failure

**Comment by shawkins** [comment]
The standard deployment conditions are not maintained for statefulsets.  This becomes a little more involved in that we'd have to look directly at the not ready pods with the matching controller-revision-hash then dig into the conditions and containerStatuses from there.  

@vmuzikar let me know if this is still desirable, and I'll follow up with a pr.

**Comment by vmuzikar** [comment]
@shawkins Thanks for looking into this. Yeah, this issue comes from the times when we were using Deployment instead of StatefulSet. I'd say it's still valid and it'd be useful to expose deployment errors in the CR Status regardless of what internal resource we use.

CC @keycloak/cloud-native
