### ISSUE TITLE
Update custom provider examples in source to KC 17.x

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#10293]
### Discussed in https://github.com/keycloak/keycloak/discussions/10258

<div type='discussions-op-text'>

<sup>Originally posted by **thaDude** February 16, 2022</sup>
Hello,

Are there plans to update the custom REST endpoint examples in https://github.com/keycloak/keycloak/tree/17.0.0/examples/providers to Keycloak 17 based on Quarkus?

I have only recently finished the effort of coding my own endpoints and - somewhat painstakingly - scripting Wildfly to deploy these extensions as part of a Docker build.

Best regards,

David</div>

**Comment by pedroigor** [comment]
We need to review these examples because:

* Some of them are already covered by some quickstarts
* We don't support domain extension as now we are doing Quarkus
* Looks redundant to keep these plus quickstarts

**Comment by shawkins** [comment]
Out of date.
