### ISSUE TITLE
Allow adding custom headers in HTTP Requests performed by keycloak-js adapter

### ISSUE THREAD

**Issue by Toilal** [keycloak/keycloak#10312]
### Description

Would you consider a pull request to configure additional headers when performing HTTP Request to Keycloak inside keycloak-js adapter ?

### Motivation

I run an SPA communicating with a REST API and using Keycloak for authentication.

This application is deployed on a staging environment that as restricted access to some people through Cloudflare Access (Zero Trust). 

In this context, I need keycloak-js adapter to add two headers in every HTTP Request (`CF-Access-Client-Id` and `CF-Access-Client-Secret`) for the browser to be allowed to access Keycloak through Cloudflare Access.

**Comment by stianst** [comment]
@jonkoops wdyt?

**Comment by jonkoops** [comment]
See my comment on the PR https://github.com/keycloak/keycloak/pull/10313#issuecomment-1055263174

**Comment by jonkoops** [comment]
Closing this for the reasons specified in the PR

**Comment by Toilal** [comment]
Client is also protected behind cloudflare zero trust, but I understand the use case is not so common.
