### ISSUE TITLE
Introduce Keycloak "feature" for step-up authentication

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#10315]
### Description

We may need to introduce "Feature" inside "Profile" class. The feature will be enabled by default (due it is enabled already in Keycloak 17), but administrator has possibility to disable it.

In case the feature is disabled, the `acr` claim in the ID Token will behave the same as before this feature was introduced (Hence returning 1 for "normal" authentication and 0 for SSO authentication). Otherwise "acr" claim will be filled according to the levels from the authentication flow, which user achieved.

As a follow-up to this, the protocol mapper will be introduced (See #10161) and hence there would be a chance that "acr" claim can be skipped from the token entirely. Or added by some other way by other protocol mapper (EG. userSessionNote as mentioned in #9344)

**Comment by nxadm** [comment]
Hi,

I am still testing the feature (and how it integrates with flows that trigger them). Will this work for oidc clients when Keycloak is brokering for a SAML2 provider? (SAML2 uses authnContextClassRef, what keycloak already implemented on the realm level).

**Comment by mposolda** [comment]
@nxadm By "feature", it was meant the dedicated profile feature as described in the Keycloak documentation https://www.keycloak.org/docs/17.0/server_installation/#profiles .

The scenario you mentioned seems to be non-trivial and there is no plan to add it in the milestone 1 (AKA during implementation of the epic #10153). However hopefully in the future, we will be able to add something like this.
