### ISSUE TITLE
keycloak-js 17.0.0: Can't import the named export 'sha256' from non EcmaScript module 

### ISSUE THREAD

**Issue by klassm** [keycloak/keycloak#10314]
### Describe the bug

Hi,

since Keycloak-js 17.0.0 the import from node_modules is broken.

The build fails with
`
Failed to compile.

./node_modules/keycloak-js/dist/keycloak.mjs
Can't import the named export 'sha256' from non EcmaScript module (only default export is available)
`

Beware - this is not a compile error of the application, but seems to be an issue in the library. Previous versions, like all 16.x.x work fine.

### Version

17.0.0

**Comment by nplaner** [comment]
getting the same error message here. how were you able to resolve this issue?

**Comment by SamHCoco** [comment]
> getting the same error message here. how were you able to resolve this issue?

This worked for me: go the 'keycloak.mjs' under 'node_modules/keycloak-js/keycloak.mjs' and remove the curly braces from the 'sha256' import at the top of the file - not an ideal solution but it should prevent the compilation error.

**Comment by klassm** [comment]
Well I did lots of dependency updates yesterday. What I guess fixed it is upgrading from typescript target es2019 to es2021.

**Comment by Wapax** [comment]
> > getting the same error message here. how were you able to resolve this issue?
> 
> This worked for me: go the 'keycloak.mjs' under 'node_modules/keycloak-js/keycloak.mjs' and remove the curly braces from the 'sha256' import at the top of the file - not an ideal solution but it should prevent the compilation error.

It works for me ! Thanks for this issue

**Comment by parweb** [comment]
still have this error :/

**Comment by eevers-avisi** [comment]
Issue also still occurs for me. Updating node_modules will not fix this, because the next time you'll clean your node_modules or build your application elsewhere, those changes will be gone.

**Comment by nplaner** [comment]
A workaround is reverting back to 16.1.1 as that will resolve this issue.

**Comment by jonkoops** [comment]
Working on a fix for this, in the meantime it is recommended to keep using version 16.0.0. There should be no major differences between the two besides the addition of ES modules.

**Comment by jonkoops** [comment]
I'm inclined to merge #10468 to resolve this issue immediately. I do however want to reproduce the behavior to identify the root cause of this problem as the `js-sha256` library does [advertise this named export](https://github.com/emn178/js-sha256/blob/master/index.d.ts#L148). This leads me to think this might be an issue with the library and a specific build tool.
