### ISSUE TITLE
The hostname-path option is not used for css

### ISSUE THREAD

**Issue by swhitman0** [keycloak/keycloak#10321]
### Describe the bug

When Keycloak is behind a reverse proxy, the hostname-path configuration option sets the context-path configured in the reverse proxy server. This option is not applied to some of the files under /resources. Examples:
- /resources/33yoe/common/keycloak/web_modules/@patternfly/react-core/dist/styles/assets/fonts/overpass-webfont/overpass-regular.woff2
- /resources/33yoe/common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css
- /resources/33yoe/common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css

### Version

17.0.0

### Expected behavior

The hostname-path option is used everywhere it is needed.

### Actual behavior

The hostname-path is not used for some files under /resources.

### How to Reproduce?

- Use a reverse proxy Nginx configuration. Set the location to /auth/. 
- Configure Keycloak with the option hostname-path = /auth/.
- Use a browser to navigate to the URL: https://localhost/auth/realms/myrealm/account/#/
- Notice the page is not formatted correctly.
- View the Nginx logs to see that /auth/ is not prepended to some of the requests.

**Comment by heikkilamarko** [comment]
Faced the same problem today with Traefik as the reverse proxy.

**Comment by cruggieri** [comment]
I have a similiar issue. I have a keycloak installation with docker behind a reverse proxy. I'd like to puth keycloak in /keycloak/ path.
I set ENV KC_HOSTNAME_PATH="keycloak" in my dockerfile, but this variable seems to be ignored.

This is my docker file:



FROM quay.io/keycloak/keycloak:latest as builder

ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
RUN /opt/keycloak/bin/kc.sh build --db postgres

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=[PASSWORD]
# change these values to point to a running postgres instance
ENV KC_PROXY="edge"
ENV KC_DB_URL="jdbc:postgresql://[DB-HOSTNAME]/keycloak"
ENV KC_DB_USERNAME="keycloak"
ENV KC_DB_PASSWORD="[DB PASSWORD]"
ENV KC_HOSTNAME="[MYFQDN]"
ENV KC_HOSTNAME_PATH="keycloak"
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]

**Comment by Morl99** [comment]
> I have a similiar issue. I have a keycloak installation with docker behind a reverse proxy. I'd like to puth keycloak in /keycloak/ path. I set ENV KC_HOSTNAME_PATH="keycloak" in my dockerfile, but this variable seems to be ignored.
> 
> This is my docker file:
> 
> ```
> FROM quay.io/keycloak/keycloak:latest as builder
> 
> ENV KC_METRICS_ENABLED=true
> ENV KC_FEATURES=token-exchange
> ENV KC_DB=postgres
> RUN /opt/keycloak/bin/kc.sh build --db postgres
> 
> FROM quay.io/keycloak/keycloak:latest
> COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
> WORKDIR /opt/keycloak
> # for demonstration purposes only, please make sure to use proper certificates in production instead
> RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
> ENV KEYCLOAK_ADMIN=admin
> ENV KEYCLOAK_ADMIN_PASSWORD=[PASSWORD]
> # change these values to point to a running postgres instance
> ENV KC_PROXY="edge"
> ENV KC_DB_URL="jdbc:postgresql://[DB-HOSTNAME]/keycloak"
> ENV KC_DB_USERNAME="keycloak"
> ENV KC_DB_PASSWORD="[DB PASSWORD]"
> ENV KC_HOSTNAME="[MYFQDN]"
> ENV KC_HOSTNAME_PATH="keycloak"
> ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
> ```

What happens if you start this image and call https://localhost:8443/keycloak (assuming, you bind the docker port 8443 to your local port 8443).?

**Comment by tomcz7** [comment]
To change http uri prefix you can use:
CLI: --http-relative-path
Env: KC_HTTP_RELATIVE_PATH

with value /auth - keycloak 17 would work as previous one on wildfly.

**Comment by pedroigor** [comment]
@tomcz7 You're right ... That is the option to use when you want to change the root-path of the server (other than `/`).

The `hostname-path` is for adding an additional path to what you have set to `http-relative-path`.
