### ISSUE TITLE
Realm localization translations are not available in the Account console

### ISSUE THREAD

**Issue by Alexander72** [keycloak/keycloak#10328]
### Describe the bug

Only translations from the theme properties are available in the Account console. Realm translations created in the Admin Panel (or through the Admin REST API) are not available in the Account console.

There is `msg` and `msgJSON` variables available in the account console theme `.ftl` file, but the content of the variables does not contain translations from the realm.

### Version

17.0.0

### Expected behavior

Realm translations are available in the `msg` and `msgJSON` variables in the account console (`index.ftl` file) and they take precedence over translations from the account theme properties files.

### Actual behavior

Translations from the account them properties file is available in the `msg` and `msgJSON` variables in the account console (`index.ftl` file)

### How to Reproduce?

1. Add translation in the English locale in the Admin Panel -> Realm -> Localization, with the key `testAccountConsoleBug` and the value `Test value`
2. Add ${msg.testAccountConsoleBug} in the `account/index.ftl`
3. Apply theme changes (not required if theme caching is disabled)
4. Open account console page in the browser

**Expected result:** `Test value` is present on the page

**Actual result:** error is being shown because message with such a key does not exist

**Comment by ssilvert** [comment]
We are planning to do some major work on the account UI later this year and addressing localization issues like this one should be part of that effort.

**Comment by ssilvert** [comment]
Oh, I didn't notice that you submitted a PR.  Thanks for that.
