### ISSUE TITLE
Running Keycloak-X 17.0.0 with mssql container causes javax.transaction.xa.XAException

### ISSUE THREAD

**Issue by RaffaelGrob** [keycloak/keycloak#10339]
### Description

I'm trying to run KC using a MSSQL image. Obviously the used images do not support XA Transaction. Question 1 is, whether this scenario has been tested and is there a documentation hint how to get it running? Further I'm testing whether XA Transactions can be disabled on quarkus level using a conf/quarkus.properties file containing quarkus.datasource.jdbc.transactions = disabled. So far that neither worked. Am I facing a bug, a currently open gap or is there a way to configure this I've not found before.

Failed with SQL Images: 
- mcr.microsoft.com/mssql/server:2017-CU14-ubuntu 
- mcr.microsoft.com/mssql/server:2019-latest

Vars:
ENV KC_DB=mssql
ENV KC_DB_URL=jdbc:sqlserver://localhost:1433;databaseName=keycloak

Error:
2022-02-18 07:40:56,213 WARN [com.arjuna.ats.jta] (main) ARJUNA016061: TransactionImple.enlistResource - XAResource.start returned: XAException.XAER_RMERR for < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a580008:a617:620f4d88:0, node_name=quarkus, branch_uid=0:ffff0a580008:a617:620f4d88:3f, subordinatenodename=null, eis_name=0 >: javax.transaction.xa.XAException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to create the XA control connection. Error: "The connection is closed."

### Motivation

The use of MSSQL is/was a requirement from our customers. In demo/dev environments such a SQL Server should be easy to setup and therefore the compatibility with the existing images should imho be made.

**Comment by DGuhr** [comment]
Hey @RaffaelGrob to use non-XA you'd need to chang the transcation type and the driver, as keycloak on quarkus is using XA by default. https://github.com/keycloak/keycloak/issues/10191 you can have a look here how it's done (done for mariadb galera there, but same principle). Basically: set the two system variables using the correct non-xa driver and tx-type, build your image, and it'll work. Expect some future changes around this to make the ux better :)

**Comment by RaffaelGrob** [comment]
This issue is solved for me and works. The following Dockerfile contains everything to reproduce my success:

```
FROM quay.io/keycloak/keycloak:latest as builder

RUN echo "Show-config before build"
RUN /opt/keycloak/bin/kc.sh show-config

ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=authorization,account2,account-api,admin-fine-grained-authz,admin2,impersonation,scripts,token-exchange,upload-scripts,web-authn,client-policies,ciba,map-storage,par,declarative-user-profile,dynamic-scopes
RUN /opt/keycloak/bin/kc.sh \
  -Dkc.db-tx-type=enabled \
  -Dkc.db-driver=com.microsoft.sqlserver.jdbc.SQLServerDriver \
  build \
  --db=mssql

RUN echo "Show-config after build"
RUN /opt/keycloak/bin/kc.sh show-config

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=change_me
ENV KC_DB=mssql
ENV KC_DB_URL=jdbc:sqlserver://localhost:1433;databaseName=keycloak1
ENV KC_DB_USERNAME=keycloak1
ENV KC_DB_PASSWORD=PassW0Rd!
ENV KC_HOSTNAME=localhost:8443

RUN echo "Show-config befor ending"
RUN /opt/keycloak/bin/kc.sh show-config

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]

# Running SQL Server
# podman run -d --rm --network=host -d \
#   -e 'ACCEPT_EULA=Y' -e \
#   'MSSQL_SA_PASSWORD=PassW0Rd!'  \
#   --name sql1 \
#   -p 1433:1433 \
#   -v /var/mssql/data:/var/mssql/data:Z \
#   mcr.microsoft.com/mssql/server:2019-latest 

# Script to create Database using SQL Management Studio
# Use [master]
# CREATE LOGIN keycloak1 WITH PASSWORD = 'PassW0Rd!';
# GO
# CREATE DATABASE keycloak1 COLLATE SQL_Latin1_General_CP1_CI_AS
# GO
# use [keycloak1]
# GO
# CREATE USER [keycloak1] FROM LOGIN [keycloak1];
# exec sp_addrolemember 'db_owner', 'keycloak1';

# podman build . -t prebuilt_keycloak1 -f ./DockerfileMssql
# podman run --rm --network=host --name optimized_keycloak1 -p 8443:8443 prebuilt_keycloak1

# hit: https://localhost:8443
```

**Comment by DGuhr** [comment]
@RaffaelGrob Glad it works for you, and thanks for the dockerfile :)  On a sidenote: for a production deployment i guess you'd want to have your "builder" image created e.g. in your CI and then let the CI upload your optimized image to e.g. quay/dockerhub, and the second stage would be your "runtime image" then where you just invoke start with the env vars. The multi-staged build example in the guide is just to make this separation clear, but you don't want to run the builder everytime.

**Comment by DGuhr** [comment]
@RaffaelGrob fyi, this behaviour will change in the next version / has changed now in latest main, see PR #10378 . you only need to run `kc.sh build --db=mssql --transaction-xa-enabled=false`, no System Properties involved anymore.

**Comment by RaffaelGrob** [comment]
Hereby I've solved this problem and will know what to do in the future. The way you made it seems very straightforward to me. PS: Maybe you wan't to have a look at #10381. This is another problem preventing me stepping ahead.
Thanks anyway!

**Comment by peermaute** [comment]
Hey,
I also ran into this exact same problem.
Although I don't use docker - I just downloaded the Keycloak 17 Quarkus distribution and changed two properties in the `conf/keycloak.conf` file:
```
db=mssql
db-url=jdbc:sqlserver://<url>;DatabaseName=<name>;username=<username>;password=<password>;
```

I tried to use these arguments when building like explained [here](https://gist.github.com/DGuhr/59c17fc6ec461a5ec3421fa4bb8eacd8): 

`./kc.bat -Dkc.db-tx-type=enabled -Dkc.db-driver=com.microsoft.sqlserver.jdbc.SQLServerDriver build --db=mssql`

And I also tried to disable the XA transactions by creating a quarkus.properties file in the /conf directory and setting `quarkus.datasource.jdbc.transactions=enabled` (I also tried disabling this property), as it is stated in the [documentation](https://www.keycloak.org/migration/migrating-to-quarkus), that you can configure the Quarkus part of the Keycloak doing this.

I'm pretty sure it doesn't work, because I don't fully understand what I actually want to do, but I find it hard to find out, what I need to learn or search for, to understand it better.

**Comment by lennartpost** [comment]
@peermaute
I too ran into the problem with `javax.transaction.xa.XAException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to create the XA control connection. Error: "The connection is closed."` when trying to run Keycloak 17 locally from the Windows command line.

The suggested fix by adding the properties `-Dkc.db-tx-type=enabled` and `-Dkc.db-driver=com.microsoft.sqlserver.jdbc.SQLServerDriver` to the build step worked for me.

However, make sure you do not use `kc.bat start-dev` to run the server as that will do an auto-build prior to running Keycloak overriding the two properties in the build step.

If you do want to use `kc.bat start-dev` then make sure you add the properties to conf/keycloak.conf instead:
```
db-tx-type=enabled
db-driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
```

**Comment by DGuhr** [comment]
The changes i mentioned earlier made it into 17.0.1, so it's now just `--db=<mydb> --transaction-xa-enabled=false` to use non-xa db drivers. See https://www.keycloak.org/server/db#_using_database_vendors_without_xa_transaction_support

**Comment by Hollerweger** [comment]
Can this be mentioned in the Guide for Running Keycloak in a container:
https://www.keycloak.org/server/containers

Not sure why `ENV KC_DB=mssql` is not enough and extra parameter are also needed in the RUN command:
`RUN /opt/keycloak/bin/kc.sh build --db=mssql --transaction-xa-enabled=false`

**Comment by radiantmind** [comment]
# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
db=mssql

# The username of the database user.
db-username=keycloak

# The password of the database user.
db-password=<gouda1990>
# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
db-url=jdbc:sqlserver://192.168.100.104;databaseName=keycloak;

# Observability

# If the server should expose metrics and healthcheck endpoints.
metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
hostname=localhost

db-tx-type=enabled
db-driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
transaction-xa-enabled=false


that was my keycloak.conf


keycloak]$ docker run --name=mssql    -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<gouda1990>'    -e 'MSSQL_RPC_PORT=135' -e 'MSSQL_DTC_TCP_PORT=51000'    -p 1433:1433 -p 135:135 -p 51000:51000     -d mcr.microsoft.com/mssql/server:2017-latest

that was database 2017

Use [master]
CREATE LOGIN keycloak WITH PASSWORD = '<gouda1990>';
GO
CREATE DATABASE keycloak COLLATE SQL_Latin1_General_CP1_CI_AS
GO
use [keycloak]
GO
CREATE USER [keycloak] FROM LOGIN [keycloak];
exec sp_addrolemember 'db_owner', 'keycloak';


that was query 

C:\Program Files\keycloak-17.0.1\bin>kc.bat build --db=mssql --transaction-xa-enabled=false

C:\Program Files\keycloak-17.0.1\bin>kc.bat start-dev

that was steps on windows

**Comment by timvdh** [comment]
> @RaffaelGrob fyi, this behaviour will change in the next version / has changed now in latest main, see PR #10378 . you only need to run `kc.sh build --db=mssql --transaction-xa-enabled=false`, no System Properties involved anymore.

If there an environment variable for "transaction-xa-enabled"?

**Comment by my57ic** [comment]
> > @RaffaelGrob fyi, this behaviour will change in the next version / has changed now in latest main, see PR #10378 . you only need to run `kc.sh build --db=mssql --transaction-xa-enabled=false`, no System Properties involved anymore.
> 
> If there an environment variable for "transaction-xa-enabled"?

Yes, `KC_TRANSACTION_XA_ENABLED`, it's a build time variable.
