### ISSUE TITLE
Account data displayed and exposed on screen when navigating back and forth between pages of Account/Personal Info

### ISSUE THREAD

**Issue by uwieske** [keycloak/keycloak#10337]
### Describe the bug

When visiting personal information (Account info webpages) and navigating back and forth with the Back and Forward button, the Json data  (that is a Json string) of an account (user) is displayed on screen (webbrowser) exposing more information about the account than intended. Unexpected and erroneous behaviour.

 

### Version

17.0.0

### Expected behavior

When going back (with the Back) button I should not see the Json data but the pages where I was previously on. 

### Actual behavior

I see a json string on screen.

### How to Reproduce?

1. Navigate to http://loocalhost:8080/realms/myrealm/account
2. Sign in (a user) with username and password
3. Click on card/panel "Personal info"
4. Click immediately on "Applications" in left sidebar
5. Go back to Personal Info by clicking on the Back button of your Chrome browser (experienced this behaviour  in Chrome)
6. Click again on the Back button (thus second time)
7. Click again on the Back button (thus third time at this point)
You should see a blank screen displaying a Json string representing the account information of the signed in user.

### Anything else?

* Tested/experienced in a Docker container deployment of Keycloak
* Host Platform MacOS
* Minimal configurations. I have just downloaded, unpacked and started Keycloak as Docker container.

**Comment by ssilvert** [comment]
@uwieske Thanks for reporting this.

The only way I could make this happen was to open a new tab and go directly to the account UI.  

Usually, the account UI is accessed from another application.  For instance, if you first go to the admin UI, then go to "Manage account" from the upper righthand menu, you can go through steps 3 to 7 and the back button will work as expected.

But this is something we will want to fix when we put more development resources on the account UI later this year.

**Comment by uwieske** [comment]
@ssilvert Stan, thank you. Understood. Indeed, I took a shortcut during development process by using the link above. 
Not a blocking issue, though a phenomenon which should be prevented in the future. Good luck. I will close this issue, as this (partial) anomaly is under your attention and waiting for future resolution.

**Comment by ssilvert** [comment]
Actually, I'd like to keep it open so we remember to take care of this later.  Reopening.

**Comment by uwieske** [comment]
Ok great. 👍

**Comment by edewit** [comment]
no longer an issue in the new version "V3" of the account console

**Comment by uwieske** [comment]
Thanks!
