### ISSUE TITLE
Content-Security-Policy issue with KC_HOSTNAME_ADMIN option set

### ISSUE THREAD

**Issue by vanrar68** [keycloak/keycloak#10340]
### Describe the bug

With Keycloak 17.0.0 when trying to access Keycloak admin console through the hostname set in KC_HOSTNAME_ADMIN I hit the following error in the browser console:

`Refused to frame 'https://console.idp.test.local/realms/master/protocol/openid-connect/3p-cookies/step1.html' because it violates the following Content Security Policy directive: "frame-src https://idp.test.local".`

Keycloak is running inside a container that has the following env vars set:

KC_HOSTNAME: idp.test.local
KC_HOSTNAME_ADMIN: console.idp.test.local
KC_HOSTNAME_STRICT_BACKCHANNEL: "true"

Keycloak starts with the following hostname log:

2022-02-20 17:53:18,279 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: idp.test.local, Strict HTTPS: false, Path: <request>, Strict BackChannel: true, Admin: console.idp.test.local

### Version

17.0.0

### Expected behavior

Display the login screen without errors

### Actual behavior

Throws an error in the browser console and displays an error popup

**Comment by TobiasMende** [comment]
We experience the same issue with Keycloak 17.0.1

Our guess is, it needs to be `frame-src 'self'` for the Keycloak console. – Can we change this somewhere?

**Comment by jesse-savary** [comment]
Still encountering this on 18.0.1

**Comment by hellobiek** [comment]
Is there any resolution?

**Comment by git001** [comment]
Is there any resolution for that issue?

**Comment by vmuzikar** [comment]
@vanrar68 Thanks for the report! Can you please confirm if the issue still persists with the latest Keycloak version for you? If so, feel free to reopen.

**Comment by jakubgs** [comment]
Not sure why this was closed. I'm still seeing this issue on `22.0.1` when using different domains for `KC_HOSTNAME` and `KC_HOSTNAME_ADMIN` environment variables.

**Comment by jakubgs** [comment]
Yes, that issue definitely looks like what I'm seeing, especially https://github.com/keycloak/keycloak/issues/14666#issuecomment-1272272055.
