### ISSUE TITLE
Members are not listed under hardcoded group when users are imported from LDAP 

### ISSUE THREAD

**Issue by ozthemagician** [keycloak/keycloak#10348]
### Describe the bug

Problem:

Created a user federation with AD using **hardcoded-ldap-group-mapper**. 
I saw the group is assigned to the user under user detail page but when I try to get the members of the group. Nothing is listed under.

Expected: All users imported from LDAP is going to be seen under hardcoded group members list.
Actual: Nothing is listed under that group members endpoint.

### Version

17.0.0

### Expected behavior

All users imported from LDAP using **hardcoded-ldap-group-mapper** is going to be seen under group's members list.

### Actual behavior

 Nothing is listed under that group members endpoint.

### How to Reproduce?

Create a use federation. Mine is AD.
create a hardcoded-ldap-group-mapper that assigns a default group to the imported users.
try to get users' list under that group.
No federated user is going to be listed under that group.

### Anything else?

I think the probloem is the implementation of **HardcodedLDAPGroupStorageMapper** It should override the onImportUserFromLDAP method and join that user to the group. 

The code will be something like that.

HardcodedLDAPGroupStorageMapper.java
```java
@Override
    public void onImportUserFromLDAP(LDAPObject ldapUser, UserModel user, RealmModel realm, boolean isCreate) {
        if (isCreate) {
                GroupModel kcGroup = getGroup(realm);
                if (kcGroup != null) {
                    logger.debugf("User '%s' joins group '%s' from hardcoded ldap group", user.getUsername(), kcGroup.getName());
                    user.joinGroup(kcGroup);
                }
            }
    }
```

**Comment by NoCoker** [comment]
I have the same problem with group-ldap-mapper
On the users the group is shown up
if i open the group the member part just say Error !
No users listed as members !

**Comment by hmlnarik** [comment]
Thank you for the bug report. This issue will be addressed in the new store.

For the legacy store, the fix would be more complex than the one suggested e.g. to account for various import modes and the number of affected mappers, since this applies also to several other similar mappers.
Given the team bandwidth and its focus on the new store, I am rejecting this issue for legacy store.

**Comment by fabriceNanni** [comment]
Hello,
Behaviour is still there in v20.0.2, group members tab shows an empty list, but user's detail shows the correct group membership coming from the hardcoded-ldap-group-mapper.
@hmlnarik, What to you call the new store ? the current version 20 ?
Can we have visibility on when this can be treated ?
Thank you very much.

**Comment by unreal-altran** [comment]
Hello,
Behaviour is still there in keycloak:20.0.5, group members tab shows an empty list, but user's detail shows the correct group membership coming from the hardcoded-ldap-group-mapper.

**Comment by CagatayCanK** [comment]
Hey @hmlnarik  
This was happening to me with Version 20.0.3 so I tried upgrading to 21.1.2 version (couldn't upgrade to 22 because of [this ](https://github.com/keycloak/keycloak/issues/21625)) but issue still is there.
Do I need to do something special while upgrading to new store/version?

**Comment by oculos** [comment]
Same here, 22.0.5.

**Comment by drJabber** [comment]
Same here, 23.0.0

**Comment by Chyadmi** [comment]
Same for 22.0.1

**Comment by zufolo441** [comment]
Still there in 24.0.4

**Comment by zufolo441** [comment]
...and in 25.0.1

**Comment by mator** [comment]
still valid issue for 26.2.2

**Comment by patricktzschentkeATform4** [comment]
still there in 26.7.2
