### ISSUE TITLE
KeycloakServletExtension double injecting in a spring boot application 

### ISSUE THREAD

**Issue by buhtr** [keycloak/keycloak#10356]
### Describe the bug

In a spring-boot application which uses undertow web server and keycloak-spring-boot-starter observed double execution for keycloak's auth functionality. The reason for that double registration of a KeycloakServletExtension.

### Version

15

### Expected behavior

Keycloak's auth functionality executed only once 

### Actual behavior

Keycloak's auth functionality executed two times

### How to Reproduce?

Consider spring-boot 2.4.4 application  which uses undertow web server and keycloak-spring-boot-starter. Keycloak-spring-boot-starter brings the following dependencies: 

[INFO] |  \- org.keycloak:keycloak-spring-boot-starter:jar:15.0.2:compile
[INFO] |     +- org.keycloak:keycloak-spring-boot-2-adapter:jar:15.0.2:compile
[INFO] |     |  \- org.keycloak:keycloak-spring-boot-adapter-core:jar:15.0.2:compile
[INFO] |     +- org.keycloak:keycloak-authz-client:jar:15.0.2:compile
[INFO] |     +- org.keycloak:spring-boot-container-bundle:jar:15.0.2:compile
[INFO] |     \- org.keycloak:keycloak-spring-security-adapter:jar:15.0.2:compile
[INFO] |        +- org.keycloak:keycloak-adapter-spi:jar:15.0.2:compile
[INFO] |        \- org.keycloak:keycloak-adapter-core:jar:15.0.2:compile

The org.keycloak:spring-boot-container-bundle:jar does registration of a KeycloakServletExtension with help of META-INF/services/io.undertow.servlet.ServletExtension. 

The class KeycloakAutoConfiguration from  org.keycloak:keycloak-spring-boot-2-adapter add  another KeycloakServletExtension to a undertown web server see method `KeycloakBaseUndertowDeploymentInfoCustomizer::customize` during configuration process.

The log of a starting application 
```
12:49:04.081 [                main] DEBUG o.k.a.u.KeycloakServletExtension - KeycloakServletException initialization
12:49:04.119 [                main] INFO  o.k.a.u.KeycloakServletExtension - Using org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolverWrapper to resolve Keycloak configuration on a per-request basis.
12:49:04.125 [                main] DEBUG o.k.a.u.KeycloakServletExtension - creating ServletKeycloakAuthMech
12:49:04.144 [                main] DEBUG o.k.a.u.KeycloakServletExtension - Setting jsession cookie path to: /
12:49:04.241 [                main] WARN  io.undertow.websockets.jsr - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
12:49:04.249 [                main] DEBUG o.k.a.u.KeycloakServletExtension - KeycloakServletException initialization
12:49:04.250 [                main] INFO  o.k.a.u.KeycloakServletExtension - Using org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolverWrapper to resolve Keycloak configuration on a per-request basis.
12:49:04.250 [                main] DEBUG o.k.a.u.KeycloakServletExtension - creating ServletKeycloakAuthMech
```
   
Moreover in the log message there is a misspelling `DEBUG o.k.a.u.KeycloakServletExtension` - **KeycloakServletException**`

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future as spring boot adapter is not the big priority. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.

**Comment by buhtr** [comment]
> We're facing this issue in one of our production systems. Is there a known workaround to avoid the double execution? We're currently not able to change to a newer version or use anything else than the the deprecated spring keycloak adapter.

I've solved this issue by overriding undertow initialization in a spring. It was a long time ago but if you need I can try to search this workaround.
