### ISSUE TITLE
Javascript adapter: theoretical race condition around token refreshing

### ISSUE THREAD

**Issue by ultinous-dancsa** [keycloak/keycloak#10360]
### Describe the bug

in adapters/oidc/js/src/keycloak.js
setToken() function (from row 982)
If the onTokenExpired callback is set (which must be set before init, but that's not documented [1]), the setTimeout is calculated to be match exactly the token's expiration, which after the the token will be renewed (asyncrounously).
It is possible for the client to get an already expired token

[1] https://github.com/keycloak/keycloak/issues/19144

### Version

16.1.0

### Expected behavior

set lower timeout, to allow the token be updated before expiration or provide callback for updating the token before expiration.

**Comment by jonkoops** [comment]
Re-opening this issue so that we don't lose track of it.

**Comment by jonkoops** [comment]
I am closing this issue as it is purely theoretical, if someone has reproduction steps let me know and I will re-open.

**Comment by Bernhelm** [comment]
It's not theoretical in my case, I have a race condition refreshing token.

I get a token from keycloak, expires in 300 seconds. I use that token to get info from my server, eventually I request updates once per second, as I'm waiting for a process to finish, sending access-token in every request. If I use keycloak.onTokenExpired to refresh my token, I need to wait for it to finish, as in the meantime my token is no longer valid, so if I don't wait for it, my request will be rejected as, I'm using an expired token.

I've set expiration token down to 10 seconds just for testing purposes:

It usually works:

![Image](https://github.com/user-attachments/assets/aaa43f34-2e17-4ce6-b44a-012473169171)

Until it doesn't

![Image](https://github.com/user-attachments/assets/939aaeb1-5bdc-4b37-84e0-c22baf7c0f9c)

**Comment by Bernhelm** [comment]
this code does the trick:

`keycloak.onTokenExpired = async () => {
  await keycloak.updateToken();
};

// Refesh token on auth success
keycloak.onAuthSuccess = () => {
  refreshToken();
};

// Refresh token on refresh success
keycloak.onAuthRefreshSuccess = async () => {
  refreshToken();
};

const refreshToken = () => {
  if (keycloak.tokenParsed && keycloak.tokenParsed.exp) {
    // Schedule the onTokenExpired logic 2 seconds before expiration
    const expirationTime = (keycloak.tokenParsed.exp - 2) * 1000;
    const timeBeforeExpiration = expirationTime - Date.now();

    setTimeout(() => {
      keycloak.onTokenExpired!();
    }, timeBeforeExpiration);
  }
}`

But I'll rather use an option on Keycloak to launch onTokenExpired x seconds before expiration.
