### ISSUE TITLE
Save button on Realms setting themes page  remains enabled even after successful save message

### ISSUE THREAD

**Issue by VeeTheVee** [keycloak/keycloak#10382]
### Describe the bug

Steps to reproduce:
1) Go to Realm Settings-> Themes tab
2) Add custom locale code in supported locale selector.(Screenshot attached "IssueScreenshot1"
![IssueScreenshot1](https://user-images.githubusercontent.com/38424210/155127745-c59541f9-b2c0-454e-97ec-f4345cdc7701.JPG)

3) Select the default locale and click save.
![IssueScreenshot2](https://user-images.githubusercontent.com/38424210/155127753-b0a65f98-dae2-417a-8d5e-fbf43a42c9cd.JPG)

Issue: Setting will be saved and custom language displays in language dropdown page but "Save" button remains enabled. 
On clicking the cancel button the languages in selector comes back.

### Version

15.0.2

### Expected behavior

On clicking the save button the save button should get disabled and selector should show the updated languages.

### Actual behavior

Save button saves the setting but remains in editable mode.

### How to Reproduce?

Steps to reproduce:
1) Go to Realm Settings-> Themes tab
2) Add custom locale code in supported locale selector.(Screenshot attached "IssueScreenshot1"
![IssueScreenshot1](https://user-images.githubusercontent.com/38424210/155127745-c59541f9-b2c0-454e-97ec-f4345cdc7701.JPG)

3) Select the default locale and click save.
![IssueScreenshot2](https://user-images.githubusercontent.com/38424210/155127753-b0a65f98-dae2-417a-8d5e-fbf43a42c9cd.JPG)

Issue: Setting will be saved and custom language displays in language dropdown page but "Save" button remains enabled. 
On clicking the cancel button the languages in selector comes back.

**Comment by ssilvert** [comment]
@VeeTheVee Thanks for reporting, but the old Admin UI will soon be deprecated.  We will only be fixing critical bugs in this UI going forward.
