### ISSUE TITLE
Upgrade migration scripts for more recent versions of WildFly

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#10405]
### Describe the bug

At this moment, it's not possible to execute migration scripts for WildFly as some of the properties were deprecated and it's not possible to use them. It's mainly related to WildFly versions > 25 and the major cause of the inability to execute those scripts is the change of the security layer. To be more specific, deprecating of `security-realm` elements, which were moved to the Elytron subsystem. For more details see the [WildFly 25 Security layer changes](https://www.wildfly.org/news/2021/10/05/WildFly25-Final-Released/#security-layer-changes).

I know WildFly is considered as the legacy distribution for our project, but I think that might be properly working as before.

Pipeline job: https://keycloak-jenkins.com/job/universal-test-pipeline-server/1260/console

cc: @pskopek

### Version

17.0.0

### Expected behavior

Proper execution of migration scripts (for standalone mode) for WildFly distribution

### Actual behavior

After executing migration scripts (for standalone mode), the process exits with an error code and it's not possible to find particular properties included in the script.

### How to Reproduce?

1. Build the WildFly distribution
2. Execute migration script for standalone (especially `migrate-standalone.cli`) - `./jboss-cli.sh --file=migrate-standalone.cli`

**Comment by stianst** [comment]
Although it would be great to have functional migration scripts to upgrade to Keycloak 15+ WildFly distribution, I believe this will be a significant effort, and will bring little value as in the end if we do include this in Keycloak 18 that will be the last release of the WildFly distribution. I'd rather see the effort being put into simplifying/improving the migration to the new Quarkus distribution.

**Comment by mabartos** [comment]
Ok, understand.
