### ISSUE TITLE
state request parameter breaks login-flow

### ISSUE THREAD

**Issue by flaviodonze** [keycloak/keycloak#10408]
### Describe the bug

Having an URL, which requires redirect to Keycloak-Login, containing a `state` parameter breaks the login flow.
e.g. https://demoserver/webapp?state=0

In `org.keycloak.adapters.springsecurity.authentication.KeycloakAuthenticationEntryPoint.commenceLoginRedirect()` the parameters are added to `contextAwareLoginUri` which will result in an URL `/sso/login?state=0`

After entering User+Password the flow will forward to: `https://demoserver/webapp/sso/login?state=0&state=04c97d06-3f89-4647-992b-371c0eac69b0&session_state=....`
which results in a "HTTP ERROR 400 Bad Request".

A possible solution might be, filtering keycloak-relevant parameters in `commenceLoginRedirect()`, e.g. `state`, `session_state`.

The bug was introduced in this issue/commit:
[KEYCLOAK-17665: Spring Boot - Forwarded Query Parameters don't work](https://issues.redhat.com/browse/KEYCLOAK-17665)
[KEYCLOAK-17665 Add query parameter support for Spring](https://github.com/keycloak/keycloak/commit/5d3f80ab5745fb0229459fa47d824ef8ae241d1d)

### Version

17.0.0

**Comment by chvndb** [comment]
I still have this issue with version 18.0.0

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
