### ISSUE TITLE
Kubernetes script error for SSL ingress

### ISSUE THREAD

**Issue by victoriouswarrior** [keycloak/keycloak#10402]
### Describe the bug

This issue causes the page can't be loaded.

In the console page, `/admin/master/console/`, there is a script file path is `http://my_domain/js/keycloak.js?version=42r87`, that causes the error of 

```
Mixed Content: The page at 'https://my_domain/admin/master/console/' was loaded over HTTPS, but requested an insecure script 'http://my_domainjs/keycloak.js?version=42r87'. This request has been blocked; the content must be served over HTTPS.
```

### Version

17.0.0

### Expected behavior

The the page should be loaded instead of a blank page.

### Actual behavior

![image](https://user-images.githubusercontent.com/23412028/155272045-85885ebf-43aa-4078-b3d2-c3f459c574ac.png)

### How to Reproduce?

Host this version in Kubernetes, enable the SSL certificate on ingress.
The service port is 8080.

**Comment by stianst** [comment]
This is probably down to lack of configuring Keycloak to be used with ingress / reverse proxy.

If this is with the new Quarkus version please check out https://www.keycloak.org/server/hostname and 
https://www.keycloak.org/server/reverseproxy guides.

**Comment by mihui** [comment]
Thank you, my problem was solved. @stianst

**Comment by masalinas** [comment]
> Thank you, my problem was solved. @stianst

How do you resolve the problem?

**Comment by darrenloigs** [comment]
I encountered same problem when deployed to EKS with ingress.
I solved by below config:

Ingress
```    
nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $host;
```

Keycloak deployment yaml argument:
```
        args: ["start", "--cache-stack=kubernetes","--proxy-headers=xforwarded"]
```
