### ISSUE TITLE
User Temporary Disabled message is never displayed on the login page

### ISSUE THREAD

**Issue by go-ive** [keycloak/keycloak#10416]
### Describe the bug

If a user in keycloak gets temporarily disabled due to too many login failures, the login screen error message still shows the default "invalid user" message, despite a template for the disabled user message existing.

The error is in the code in AuthenticationProcessor::handleBrowserExceptionList.

The problem is still present in the latest version.

### Version

15.0.2

### Expected behavior

Message with key "accountTemporarilyDisabledMessage" is returned to the frontend and displayed when a user is temporarily locked.

### Actual behavior

Message with key "invalidUsernameMessage" is returned to the frontend and displayed when a user is temporarily locked.

### How to Reproduce?

Have a valid user on keycloak and log in with the wrong password until the user gets temporarily locked.

**Comment by stianst** [comment]
Hi, this is intentional to prevent username enumeration attacks

**Comment by kingjuk** [comment]
it should be an option

**Comment by mouryasuraj** [comment]
"Is there another way? Can you suggest an alternative?"

**Comment by mirageofcode56** [comment]
what if i want to customize this.
