### ISSUE TITLE
Token contains old DB values with "Always Read Value From LDAP" mapper setting 

### ISSUE THREAD

**Issue by g10f** [keycloak/keycloak#10412]
### Describe the bug

Using LDAP User Federation where all mappers have "Always Read Value From LDAP" setting for user-attribute-ldap-mapper, we are still getting old values from keycloak and not the values from the LDAP store.
This happens for edit Mode UNSYNCED and READ_ONLY. 
After Max Lifespan we get once the correct values from the LDAP server, then the next time again the tokens contain wrong old values from the keycloak database. 
Only if the CachePolicy is set to NO_CACHE, we get always the correct values from the LDAP.

### Version

17.0.0

### Expected behavior

After the cache lifetime is expired and keycloak gets new values from the LDAP store, than subsequent keycloak tokens should contain the new values from LDAP and not old values from the database.

### Actual behavior

After the cache lifetime is expired and keycloak delivers once the new values from the LDAP store and in subsequent responses again outdated values.

### How to Reproduce?

1. Configure UNSYNCED  user  federation with ldap and user-attribute-ldap-mapper with "Always read values from LDAP".
2. Set Cache Policy to  "MAX_LIFESPAN=60000"
2. Change user attribute in LDAP
3. Request new tokens from keyclaok
4. After 60000 ms the first token contains the updated values from the LDAP. The next response contains again the old value.

**Comment by mposolda** [comment]
For now, I am adding this to Keycloak 21, but I am not sure if we are able to fix this due the other priority work. Anyone from the community is welcome to investigate this and possibly contribute the PR. Please comment here if you are looking at it.

It seems the issue can be in a fact, that:
- When email is changed in LDAP, then the LDAP user contains email value like `new@email`, but the Keycloak DB still have some old value like `old@email`
- After cache is expired, the Keycloak should always read the user from LDAP (due the "Always Read value from LDAP") and hence it should always see email `new@email`
- However I think that there is something in Keycloak, which direcly reads the user from DB and hence it reads the value `old@email` . Moreover, this functionality probably also cache the user to the Keycloak cache and hence subsequent calls to load the user in Keycloak reads the stale user with email `old@email` from cache.

Just a guess, the real cause can be something different.

**Comment by rmartinc** [comment]
@hmlnarik I have just stolen this from you, I think that I know what is happening here.
