### ISSUE TITLE
Model Tests failing on GitHub Actions

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#10433]
### Describe the bug

The Model Tests have been failing for quite some time. Looking at the test results from https://github.com/keycloak/keycloak/actions/runs/1889073395#artifacts it looks like all tests are passing, so maybe the issue is with https://github.com/keycloak/keycloak/blob/main/testsuite/model/test-all-profiles.sh?

### Version

main

**Comment by ahus1** [comment]
Duplicate to #10016
