### ISSUE TITLE
Error creating new realm

### ISSUE THREAD

**Issue by abstractalchemist** [keycloak/keycloak#10432]
### Describe the bug

When I try to create a new realm, I get the error message popup "Error: Conflict detected".  I just upgrade from 16.1.1 to 17.0.0.  I'm using this on AWS EKS with an AWS Aurora Postgresql backend.  The following error appears in the log:
```
022-02-24 04:11:55,671 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-3) SQL Error: 0, SQLState: 23502
2022-02-24 04:11:55,671 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-3) ERROR: null value in column "social" violates not-null constraint
  Detail: Failing row contains (aws-third-party, 0, 0, 0, null, null, null, f, f, 0, null, aws-third-party, 0, null, f, f, f, null, null, 0, 0, null, f, null, 0, f, null, f, f, f, f, 0, 0, 0, 0, null, null, null, null, null, null, null, 0, f, 0, f, f, null, 0, f, 0, 0, null).
```

### Version

17.0.0

### Expected behavior

Create a new realm

### Actual behavior

Error out with "Conflict Detected"

**Comment by ahus1** [comment]
This looks like the column SOCIAL in the table REALM is about to be set to NULL. The default value for this column is "false". 

Could you please extract the DDL for the table  REALM from your database that shows what all columns with their constraints and defaults as they have been created? Maybe the database schema migration didn't setup the columns correctly. 

Please also provide the log line that prints out the database that Keycloak identified during startup, it would look similar to this line. This could help to identify if Keycloak mis-identified the database:

> 16:50:16,400 INFO  main [org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory] Database info: {databaseUrl=jdbc:mariadb://localhost:3306/keycloak, databaseUser=root, databaseProduct=MariaDB 10.7.1-MariaDB-1:10.7.1+maria~focal, databaseDriver=MariaDB Connector/J 2.7.2}

**Comment by ahus1** [comment]
No additional information has been provided. Without additional information I can't analyze this issue further. Therefore I close this issue. Please open a new issue if the additional information once these are available.

**Comment by unteem** [comment]
I'm facing the same issue. 

I checked the schema and compared with another keycloak instance the defaults are missing. 
Here is the broken schema:
```
--
-- Name: realm; Type: TABLE; Schema: keycloak; Owner: keycloak
--

CREATE TABLE keycloak.realm (
    id character varying(36) NOT NULL,
    access_code_lifespan integer,
    user_action_lifespan integer,
    access_token_lifespan integer,
    account_theme character varying(255),
    admin_theme character varying(255),
    email_theme character varying(255),
    enabled boolean NOT NULL,
    events_enabled boolean NOT NULL,
    events_expiration bigint,
    login_theme character varying(255),
    name character varying(255),
    not_before integer,
    password_policy character varying(2550),
    registration_allowed boolean NOT NULL,
    remember_me boolean NOT NULL,
    reset_password_allowed boolean NOT NULL,
    social boolean NOT NULL,
    ssl_required character varying(255),
    sso_idle_timeout integer,
    sso_max_lifespan integer,
    update_profile_on_soc_login boolean NOT NULL,
    verify_email boolean NOT NULL,
    master_admin_client character varying(36),
    login_lifespan integer,
    internationalization_enabled boolean NOT NULL,
    default_locale character varying(255),
    reg_email_as_username boolean NOT NULL,
    admin_events_enabled boolean NOT NULL,
    admin_events_details_enabled boolean NOT NULL,
    edit_username_allowed boolean NOT NULL,
    otp_policy_counter integer DEFAULT 0,
    otp_policy_window integer DEFAULT 1,
    otp_policy_period integer DEFAULT 30,
    otp_policy_digits integer DEFAULT 6,
    otp_policy_alg character varying(36) DEFAULT 'HmacSHA1'::character varying,
    otp_policy_type character varying(36) DEFAULT 'totp'::character varying,
    browser_flow character varying(36),
    registration_flow character varying(36),
    direct_grant_flow character varying(36),
    reset_credentials_flow character varying(36),
    client_auth_flow character varying(36),
    offline_session_idle_timeout integer DEFAULT 0,
    revoke_refresh_token boolean NOT NULL,
    access_token_life_implicit integer DEFAULT 0,
    login_with_email_allowed boolean NOT NULL,
    duplicate_emails_allowed boolean NOT NULL,
    docker_auth_flow character varying(36),
    refresh_token_max_reuse integer DEFAULT 0,
    allow_user_managed_access boolean NOT NULL,
    sso_max_lifespan_remember_me integer NOT NULL,
    sso_idle_timeout_remember_me integer NOT NULL,
    default_role character varying(255)
);
```
(same issue with all tables)

Not sure what caused this issue. I did two major operations in this keycloak. 
I migrated from mysql to postgres with pgloader and upgraded it from keycloak v12 to v18

Do you have some scripts that could repair the schema ?

Thanks for the help
