### ISSUE TITLE
Keycloak 16.1.1 deployment on docker throws error MIME type ('application/json') is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by gopalkrishnams** [keycloak/keycloak#10434]
### Describe the bug

Deployed an Keycloak version 16.1.1 with spring boot embedded on docker and when tryin to access admin console we get below error 
"Refused to apply style from '<URL>' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled."
Please help us to resolve this.

### Version

16.1.1

### Expected behavior

Admin Keycloak console should load all css and files.

### How to Reproduce?

Deploy keycloak 16.1.1 with spring boot embedded version on docker 
try accessing admin console issue

**Comment by gopalkrishnams** [comment]
HI team please respond to this issue

**Comment by stianst** [comment]
I don't know what you mean by "Spring Boot embedded". Does it work before you do that?

**Comment by stianst** [comment]
Closing this for now as the steps to reproduce suggests this is for a highly modified version of Keycloak as we don't support "with spring boot embedded".
