### ISSUE TITLE
Can't change http-port by Keycloak/Quarkus on Windows

### ISSUE THREAD

**Issue by JPA2015** [keycloak/keycloak#10443]
### Describe the bug

I wanted to install a Keycloak instance on a dev machine where the http-port 8080 is already in use.

The option --http-port is not supported when calling "kc start-dev".

Although the option is supported when calling "kc start", it doesn't really work because it not possible to disable strict https and I get redirected to the https url. This is a dev machine, so that I can't configure https there.

### Version

Keycloak 17.0.0, Quarkus Edition on Windows 10

### Expected behavior

Being able to use --http-port when calling "kc start-dev" and being able to disable strict http when calling "kc start"

**Comment by pedroigor** [comment]
@JPA2015 I tried to reproduce the issue by:

``
kc.sh start-dev --http-port 8180
``

The output is:

```
Updating the configuration and installing your custom providers, if any. Please wait.
2022-02-24 15:14:02,211 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 4171ms
2022-02-24 15:14:04,489 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
2022-02-24 15:14:05,038 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-02-24 15:14:05,120 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-02-24 15:14:05,133 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-02-24 15:14:05,345 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
2022-02-24 15:14:05,766 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_443962, Site name: null
2022-02-24 15:14:06,902 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2022-02-24 15:14:09,200 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2022-02-24 15:14:10,625 INFO  [io.quarkus] (main) Keycloak 17.0.0 on JVM (powered by Quarkus 2.7.0.Final) started in 8.251s. Listening on: http://0.0.0.0:8180
2022-02-24 15:14:10,626 INFO  [io.quarkus] (main) Profile dev activated. 
2022-02-24 15:14:10,626 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, infinispan-client, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
2022-02-24 15:14:10,627 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

As you can see from the output above, port 8180 is active and strict https is disabled.

Could you elaborate more on how to reproduce the issue? The only difference though is that I'm not running on Windows ... But not sure if that should make any difference.

**Comment by tunaranch** [comment]
To add to what the OP has said, I'm seeing something similar when running KC 17 under Minikube on Mac OS with:

```
containers:
        - name: keycloak
          command:
            - /opt/keycloak/bin/kc.sh
            - start
          image: my/keycloak-17.0.0
          env:
            - name: KC_PROXY
              value: none
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KC_DB_PASSWORD
              value: password
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_URL
              value: jdbc:mysql://mysql-keycloak.default.svc.cluster.local:3306/keycloak
            - name: KC_HTTP_RELATIVE_PATH
              value: auth
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: JAVA_OPTS_APPEND
              value: >-
                -Djava.security.properties==/etc/java/security/security.d/java.security
```

KC starts up the http listener, but every request past the welcome page tries to redirect to https. Admin console fails to load because

**Comment by JPA2015** [comment]
I'm on Windows and when I call:
`kc.bat start-dev --http-port 8180`

The output is:
```
Unmatched argument at index 3: '8180'
Try 'kc.bat start-dev --help' for more information on the available options.
```

As the help page for start-dev doesn't list http-port as an option, I imagined that the option wasn't available.

But I've just seen that following command works:
`kc.bat start-dev dummy --http-port 8180`

So I had a look at kc.bat. it calls "shift" twice in following lines. Correct would be to call it only once!
```
if "%KEY%" == "start-dev" (
  set "CONFIG_ARGS=%CONFIG_ARGS% --profile=dev %KEY% --auto-build"
  shift
  shift
  goto READ-ARGS
)
```

**Comment by chriscarpenter12** [comment]
> To add to what the OP has said, I'm seeing something similar when running KC 17 under Minikube on Mac OS with:
> 
> ```
> containers:
>         - name: keycloak
>           command:
>             - /opt/keycloak/bin/kc.sh
>             - start
>           image: my/keycloak-17.0.0
>           env:
>             - name: KC_PROXY
>               value: none
>             - name: KEYCLOAK_ADMIN_PASSWORD
>               value: admin
>             - name: KEYCLOAK_ADMIN
>               value: admin
>             - name: KC_DB_PASSWORD
>               value: password
>             - name: KC_DB_USERNAME
>               value: keycloak
>             - name: KC_DB_URL
>               value: jdbc:mysql://mysql-keycloak.default.svc.cluster.local:3306/keycloak
>             - name: KC_HTTP_RELATIVE_PATH
>               value: auth
>             - name: KC_HOSTNAME_STRICT
>               value: "false"
>             - name: KC_HTTP_ENABLED
>               value: "true"
>             - name: JAVA_OPTS_APPEND
>               value: >-
>                 -Djava.security.properties==/etc/java/security/security.d/java.security
> ```
> 
> KC starts up the http listener, but every request past the welcome page tries to redirect to https. Admin console fails to load because

I had this same issue testing in docker using the latest quarkus 17 image. WIth http enabled the console link always redirected to https. [Based on this config](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/resources/META-INF/keycloak.conf#L22-L23) it seems there's another property that's not in the documentation.

That env var `KC_HOSTNAME_STRICT_HTTPS` is not listed in the all config options docs: https://www.keycloak.org/server/all-config

Adding that to my docker compose I was able to get it started. I have never ran keycloak before. This was just my initial testing.

Docker compose for those that may come across this later...

```yaml
version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: my_local_hostname_here:8080
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    command:
      - start
      - --auto-build
    ports:
      - 8080:8080
    depends_on:
      - postgres
```

**Comment by pedroigor** [comment]
> I'm on Windows and when I call: `kc.bat start-dev --http-port 8180`
> 
> The output is:
> 
> ```
> Unmatched argument at index 3: '8180'
> Try 'kc.bat start-dev --help' for more information on the available options.
> ```
> 
> As the help page for start-dev doesn't list http-port as an option, I imagined that the option wasn't available.
> 
> But I've just seen that following command works: `kc.bat start-dev dummy --http-port 8180`
> 
> So I had a look at kc.bat. it calls "shift" twice in following lines. Correct would be to call it only once!
> 
> ```
> if "%KEY%" == "start-dev" (
>   set "CONFIG_ARGS=%CONFIG_ARGS% --profile=dev %KEY% --auto-build"
>   shift
>   shift
>   goto READ-ARGS
> )
> ```

@JPA2015 Would you be able to contribute with a fix?

**Comment by JPA2015** [comment]
> @JPA2015 Would you be able to contribute with a fix?

I've just tried: https://github.com/keycloak/keycloak/pull/10665

**Comment by febrihasan** [comment]
> @JPA2015 I tried to reproduce the issue by:
> 
> `kc.sh start-dev --http-port 8180`
> 
> The output is:
> 
> ```
> Updating the configuration and installing your custom providers, if any. Please wait.
> 2022-02-24 15:14:02,211 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 4171ms
> 2022-02-24 15:14:04,489 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>
> 2022-02-24 15:14:05,038 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
> 2022-02-24 15:14:05,120 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
> 2022-02-24 15:14:05,133 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
> 2022-02-24 15:14:05,345 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
> 2022-02-24 15:14:05,766 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_443962, Site name: null
> 2022-02-24 15:14:06,902 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
> 2022-02-24 15:14:09,200 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
> 2022-02-24 15:14:10,625 INFO  [io.quarkus] (main) Keycloak 17.0.0 on JVM (powered by Quarkus 2.7.0.Final) started in 8.251s. Listening on: http://0.0.0.0:8180
> 2022-02-24 15:14:10,626 INFO  [io.quarkus] (main) Profile dev activated. 
> 2022-02-24 15:14:10,626 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, infinispan-client, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, vertx]
> 2022-02-24 15:14:10,627 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
> ```
> 
> As you can see from the output above, port 8180 is active and strict https is disabled.
> 
> Could you elaborate more on how to reproduce the issue? The only difference though is that I'm not running on Windows ... But not sure if that should make any difference.

Work for me, Thanks
