### ISSUE TITLE
git tags are not set on production branches

### ISSUE THREAD

**Issue by krichter722** [keycloak/keycloak#10445]
### Description

After checking out https://github.com/keycloak/keycloak and fetching tags, I noticed that the tag are not located on the main branch. They're fetched and the list seems complete when comparing with the list of releases. However I don't see them in `git log main` and they can't be used with `git describe --tags`. I'm not familiar with the details of your pipeline where I assume the tags are set during release builds, but I suspect a possible tweak there.

### Motivation

This is obviously not a high priority task, but it allows to use git features more easily.

**Comment by stianst** [comment]
We don't actually release/tag Keycloak from the main branch. There are a few reasons for this:

1. We don't want main to have non-snapshot versions at any point in time
2. We release from a private fork in order to be able to include CVEs in the release, which are not made publicly available through commits until after the release is ready
3. Branch protection on main branch prevents CI from being able to push changes without requiring human intervention

We are looking at revamping our release process soon, which should eliminate the need to maintain a private fork. However, I don't think due to 1 and 3 I think we will still have this limitation.

**Comment by krichter722** [comment]
@stianst Thanks for you insights. So far, I though that stage is the development branch and main is the production branch, but now looking closer at the state and merges, I think you're not doing [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), am I right? In case you're changing the release workflow you should adapt this very good practice a lot of projects are use for a lot of good reasons :)

**Comment by stianst** [comment]
@krichter722 looks interesting, could you point me to some open source projects that are using this model?

The stage branch is an experiment we have, which is aiming to run complete CI on a batch of PRs and have a bot instead of humans merge PRs.

**Comment by krichter722** [comment]
@stianst I'm surprised that I can't. GitFlow and adaptations like GithubFlow and OneFlow are described as commonly used, however I didn't find a list and looking into some large OSS projects from the top of my head it's hard to tell whether a project uses it or not. In my point of view GitFlow is a collection of good practices that might not all apply to certain projects (I never had a use for a release branch, for example), so the concrete application might differ from project to project.

You probably want to read about the variations (GithubFlow, OneFlow) and the criticisms - I would sum them up as follows:

* It's too complicated -> It's a simple as possible and as complex as necessary. It you gain no value from the complexity, don't use it (keycloak's gain would be correct release tags).
* It's overkill for small projects. Yes, no one ever said differently. However, you don't really develop pipelines for every project, that's just DRY. It's a business process in your organization, team or for yourself. You develop 1 or 2 and you apply them to your projects with no regrets - ideally using a templating system for your CI.
