### ISSUE TITLE
Duplicated attributes in user profile

### ISSUE THREAD

**Issue by delrisu** [keycloak/keycloak#10463]
### Describe the bug

For concurrent or rapidly consecutive requests, the attributes in the user profile duplicate. This is because there is no lock on the database entry in the code that handles setting attributes.

The code can be found in: org.keycloak.storage.jpa.JpaUserFederatedStorageProvider#setAttribute

In my opinion, at least optimistic lock should be used here.

### Version

15.1.1

### Expected behavior

Attributes should not be duplicated, only overwritten by a later transaction.

### Actual behavior

Attributes are duplicated.

### How to Reproduce?

Invoke a concurrent change to the same user attributes by the endpoint used to do so.

For example:
```
for i in {1..2}; do

	curl -s --location --request POST 'https://XXX/account' \
	--header "Authorization: ${BEARER}" \
	--header 'Content-Type: application/json' \
	--data-raw '{
	    "attributes": {
		"X": [
		    "1"
		],
		"Y": [
		    "2"
		],
		"Z": [
		    "3"
		]
	    }
	}' && echo "done${i}" &

done
```

**Comment by pedroigor** [comment]
@hmlnarik Is that something we need to consider in the new store? Is it worth to fix it in legacy?
