### ISSUE TITLE
The `/auth` base path should be adjusted in v17 docs pages

### ISSUE THREAD

**Issue by tkrisztian95** [keycloak/keycloak#10464]
### Describe the bug

In multiple places in the documentation can be found the base path as `/auth` but from v17 with the shift from WildFly to Quarkus this was changed to `/`. 

See the bp in the [Migration to quarkus guide](https://www.keycloak.org/migration/migrating-to-quarkus)
> - /auth removed from the default context path

### Version

17.0.0

### Expected behavior

On the [Admin Rest API docs page](https://www.keycloak.org/docs-api/17.0/rest-api/index.html) for version 17, the base path should be `/` instead of `/auth`

**Visual proof:**

![image](https://user-images.githubusercontent.com/8113120/155166125-dd4a3c12-5ad0-4785-9ae3-6e1fe5a69105.png)

On the [Server installation page](https://www.keycloak.org/docs/latest/server_installation/index.html) in step 8, opening Keycloak via  a localhost URL as for version 17, the path should be adjusted:

**Visual proof:**
![image](https://user-images.githubusercontent.com/8113120/155166380-9ae21561-07a0-49b2-960a-649fb6f1c552.png)

### Actual behavior

When I'm running Keycloak in a container locally using the dev mode the Admin REST APIs returns with `404` when using the `/auth` base path from the docs.

Example response:
```json
// Get an client access token
{
    "error": "RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/master/protocol/openid-connect/token"
}
// List users from the master realm
{
    "error": "RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/admin/realms/master/users"
}
```

**Comment by edwint88** [comment]
besides the `/auth` stuff now other urls don't work, any info on that? 

some examples that used to work
e.g. DELETE {{base-url}}/admin/realms/{{realm}}/attack-detection/brute-force/users
or GET {{base-url}}/admin/realms/{{realm}}/attack-detection/brute-force/users/{{userId}}

now you get:
{
    "error": "unknown_error"
}

**Comment by nelson-lark** [comment]
For folks that need the legacy /auth at the url but want to upgrade keycloak, this is the magic incarnation of env vars:
```      
KC_HTTP_RELATIVE_PATH: /auth
KC_HOSTNAME: keycloak.company.com
```
