### ISSUE TITLE
keycloak js header Access-Control-Allow-Origin sent twice in response

### ISSUE THREAD

**Issue by nicoclau** [keycloak/keycloak#10471]
### Describe the bug

We get twice Access-Control-Allow-Credentials and Access-Control-Allow-Origin with https://sso.xxx.net/auth/realms/yyy/protocol/openid-connect/token

Can you tell us why it can happen ?
Thanks 

`Request URL: https://sso.xxx.net/auth/realms/yyy/protocol/openid-connect/token
Request Method: POST
Status Code: 200 
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: User-Agent,Keep-Alive,Content-Type
Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin: https://zz.hhh.net
Access-Control-Allow-Origin: https://zz.hhh.net
Access-Control-Expose-Headers: Access-Control-Allow-Methods
Cache-Control: no-store
Connection: keep-alive
Content-Length: 4074
Content-Type: application/json
Date: Fri, 25 Feb 2022 11:40:16 GMT
Pragma: no-cache
Server: nginx/1.14.0 (Ubuntu)`

### Version

8.0.1

**Comment by nicoclau** [comment]
I made a test from my machine so from another domain.
I used the same keycloak server which is in the same domain as our QA application

Here my local application works well and Access-Control-Allow-Origin is sent once !

It seems that when we have keycloak and the app on the same domain, they Access-Control-Allow-Origin is sent twice?

Below the difference of request in the headers.
Can you tell me what is going on? Do we need to upgrade keycloak?
Thanks

![image](https://user-images.githubusercontent.com/16133485/155856063-5fd553ab-364d-4771-b309-bdbb19411b76.png)

**Comment by stianst** [comment]
Closing this as it is reported against a very old version of Keycloak. If you still have issues with the latest release feel free to re-open, but please also include steps to reproduce otherwise we're not able to look into it.

**Comment by nicoclau** [comment]
Ok thanks, it seems maybe the headers are added by a reverse proxy HAProxy in front of my application.
So keycloak adds the CORS headers and the reverse proxy HAProxy does the same so we get doubles.

I will check with the infra person.
