### ISSUE TITLE
IPv6 listener support

### ISSUE THREAD

**Issue by candlerb** [keycloak/keycloak#10482]
### Description

Keycloak 17.0.0 defaults to listening on IPv4 addresses only (0.0.0.0).  If I try to listen on IPv6, it says the protocol family is unavailable:

```
# sudo -u keycloak /opt/keycloak/bin/kc.sh start --http-host="[::]"
...
2022-02-25 14:50:38,518 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2022-02-25 14:50:38,519 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.net.SocketException: Protocol family unavailable
2022-02-25 14:50:38,520 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Protocol family unavailable
```

Environment: Ubuntu 20.04, regular (not Wildfly) distribution.

### Motivation

It is 2022, and it should be possible to run servers either in IPv6-only environments, or dual-stack where the service is accessible via both protocols.

**Comment by DGuhr** [comment]
First Analysis results: We set  `-Djava.net.preferIPv4Stack=true` in the kc.sh|bat script. Without it, the command from works, or at least I could open the welcome page and admin console :)  (same error msg also existed in wildfly/eap: https://access.redhat.com/solutions/2801771 ) - so as a workaround, @candlerb you could remove the `-Djava.net.preferIPv4Stack=true` from the kc.sh script. 

@pedroigor @stianst I am not sure about the implications of removing the preferIPv4Stack in general - I guess it's there for a reason? If just "historically", remove? But then we might want to have testsuite runs for ipv6 then?

**Comment by candlerb** [comment]
Confirmed here:
* Setting `JAVA_OPTS="-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"` in the environment (which overrides the default `JAVA_OPTS` set by kc.sh) enables dual stack listening. I don't even need to set `http-host`.
* After changing front-end proxy to use IPv6 to talk to back-end Keycloak instances, admin console appears to work fine.

**Comment by ciphermenial** [comment]
Why is the default no set to listen on both IPv4 and IPv6? I have to modify the kc.sh script to make this work. Simply changing the JAVA_OPTS to `"-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Stack=true -Dfile.encoding=UTF-8"` does the trick.

Why isn't there a setting in the keycloak.conf to change this?

**Comment by pedroigor** [comment]
Docs are being updated here https://github.com/keycloak/keycloak/pull/13577. Thanks @ciphermenial .

**Comment by ciphermenial** [comment]
I updated my keycloak to 20.0.1 and have set ```JAVA_OPTS_APPEND="-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true"```

This does not work and I believe it is because in kc.sh it sets Djava.net.preferIPv4Stack=true by default. Once I remove that from the script, it is now working as expected.

```bash
if [ "x$JAVA_OPTS" = "x" ]; then
   JAVA_OPTS="-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
else
   echo "JAVA_OPTS already set in environment; overriding default settings with values: $JAVA_OPTS"
fi

if [ "x$JAVA_OPTS_APPEND" != "x" ]; then
  echo "Appending additional Java properties to JAVA_OPTS: $JAVA_OPTS_APPEND"
  JAVA_OPTS="$JAVA_OPTS $JAVA_OPTS_APPEND"
fi
```

**Comment by pedroigor** [comment]
@ciphermenial Thanks. We should probably update docs to mention `JAVA_OPTS` instead.

I'm not sure if we can do anything better without adding a bit more complexity for users or the script.

**Comment by ciphermenial** [comment]
> @ciphermenial Thanks. We should probably update docs to mention `JAVA_OPTS` instead.
> 
> I'm not sure if we can do anything better without adding a bit more complexity for users or the script.

No worries. I am happy to edit the script as needed after a reinstall.

**Comment by pedroigor** [comment]
@ciphermenial Not sure why I said we could not fix this :) Created https://github.com/keycloak/keycloak/issues/15925. I'm working on it.

**Comment by pravsjv** [comment]
Hi team,
Did anyone configured dualstack with the latest Keycloak Quarkus deployment? If so, could you share some experiences?

**Comment by pedroigor** [comment]
@pravsjv Could you try setting the `java.net.preferIPv4Stack=false` system property? We can improve our docs to mention this.

**Comment by pravsjv** [comment]
I'm trying to test IPV6 with docker container and when passing -e JAVA_OPTS_APPEND="-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true" as an env variable, the container still runs on ipv4 machine. Does this needs to be a part of Dockerfile?
