### ISSUE TITLE
Spring session persistence in Redis broken for keycloak tokens

### ISSUE THREAD

**Issue by arne-kroeger** [keycloak/keycloak#10483]
### Describe the bug

We're using spring boot keycloak adapter to implement OIDC based on spring session with Redis as the storage. We want to add another component based on Node.js to cover some specialties. Both components share the session ID and therefore we want to access Redis from Node to extract access / refresh token info by session ID. 
As per default Spring is storing the session info with the Java serialization (JdkSerializationRedisSerializer) this needs to be changed to store the data in a more general format. We decided to store it in a JSON format (Jackson2JsonRedisSerializer).

After changing the configuration we got the following error during deserialization:

`Could not read JSON: The class with org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken and name of org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: The class with org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken and name of org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"])
org.springframework.data.redis.serializer.SerializationException: Could not read JSON: The class with org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken and name of org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: The class with org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken and name of org.keycloak.adapters.springsecurity.token.KeycloakAuthenticationToken is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"])
	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:152) ~[spring-data-redis-2.4.15.jar:2.4.15]
	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:130) ~[spring-data-redis-2.4.15.jar:2.4.15]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:355) ~[spring-data-redis-2.4.15.jar:2.4.15]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:299) ~[spring-data-redis-2.4.15.jar:2.4.15]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:247) ~[spring-data-redis-2.4.15.jar:2.4.15]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:183) ~[spring-data-redis-2.4.15.jar:2.4.15]
	at org.springframework.session.data.redis.RedisIndexedSessionRepository.getSession(RedisIndexedSessionRepository.java:440) ~[spring-session-data-redis-2.4.6.jar:2.4.6]
	at org.springframework.session.data.redis.RedisIndexedSessionRepository.findById(RedisIndexedSessionRepository.java:412) ~[spring-session-data-redis-2.4.6.jar:2.4.6]
	at org.springframework.session.data.redis.RedisIndexedSessionRepository.findById(RedisIndexedSessionRepository.java:249) ~[spring-session-data-redis-2.4.6.jar:2.4.6]`

Do we missed anything?

### Version

13.0.1

### Expected behavior

The session should be stored in a json format in Redis and spring boot adapter should be able to serialize / deserialize the data.

### Actual behavior

The session should be stored in a json format in Redis and spring boot adapter is **not** able to serialize / deserialize the data.

### How to Reproduce?

Create a Spring Boot Application with spring-boot application with redis (spring-session-data-redis) as the session storage. Add keycloak to spring boot (keycloak-spring-boot-starter). Change Configuration to use String or JSON as the storage format: https://github.com/spring-projects/spring-session/blob/2.2.2.RELEASE/spring-session-samples/spring-session-sample-boot-redis-simple/src/main/java/sample/config/SessionConfig.java

When launching the application and after authentication there you'll get the error.

**Comment by arne-kroeger** [comment]
I've made some tests and created a working example by adding some mixins to the configuration to add missing JSON hints in Keycloak:

https://github.com/arne-kroeger/test-spring-keycloak-redis-serialize/blob/master/src/main/java/arnekroeger/keycloak/redis/SessionConfig.java

Before providing a PR I want to discuss if this is the correct way for Keycloak:

1. Add @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS) to the following classes:

- AccessToken
- AccessToken.Access
- IDToken
- KeycloakAuthenticationToken
- KeycloakPrincipal
- KeycloakSecurityContext
- SimpleKeycloakAccount

2. Add JsonCreator hint for the constructors for:

- SimpleKeycloakAccount
- KeycloakAuthenticationToken

3. Add JsonIgnore hints for the following functions:

- SimpleKeycloakAccount.getKeycloakSecurityContext
- RefreshableKeycloakSecurityContext.getDeployment
- KeycloakPrincipal.getKeycloakSecurityContext
- KeycloakAuthenticationToken.getCredentials
- KeycloakAuthenticationToken.getAccount

This is also reflected in the test project. If it is easier for discussion I can make the changes and create the PR.

Full project: https://github.com/arne-kroeger/test-spring-keycloak-redis-serialize

**Comment by arne-kroeger** [comment]
What would be your expected behaviour in spring security here? 

My first expectation was that the data stored to the security context in the session is the JWT only. This would be a fully serializable bean which can be easily injected in the keycloak spring boot adapter during unserialization. 

What do you think?

**Comment by Kicey** [comment]
> What would be your expected behaviour in spring security here?
> 
> My first expectation was that the data stored to the security context in the session is the JWT only. This would be a fully serializable bean which can be easily injected in the keycloak spring boot adapter during unserialization.
> 
> What do you think?

Store jwt to session? My expectayion is that different server instance in my inner cluster can share the security context. These instances don;t need to authentication a request is from which user every time, they can just get context from a session in redis. If what you want is share jwt, why not just use a jwt library such as jjwt or auth0's java library then use filter to add to or get from session?

**Comment by Kicey** [comment]
I guess I fint out the problem.
If what we talk is only share and not about session value readability.
It's about session share, zero trust and sso.
First, we are not supposed to share the session between different instance (which from different binary artifact), so it is not supposed to share session between java and node instance. It's problem about session share.
Second, node instance should not trust the java instance if it only take the session id(cookie) without field about the user credentials. It's called zero trust.
Third, so how to solve our problem?
If the java instance and node instance are both accessible from user agent( like a broswer), keycloak sso can help us do a authentication which seems that there is nothing (user can't find it, except they open the dev tools). Else, if your java instance request the node instance, use http hearder Authorization Bearer {access_token}. Sure, you have to use keycloak spring and node  sdk if your don't want to implement these work yourself.
By the way, I still want to make the session readable in redis, it's convinient to debug 🤣.
Hope this help.

**Comment by arne-kroeger** [comment]
Understood but in my case we have mixed frontend approach between Spring Web UI and a nuxt env which should share the session to access the same information stored in session (not only JWT but also application related user data). So keycloak SSO would help only in terms of being authenticated but this does not help in terms of accessing the data stored in session.

If this is not in scope of the keycloak adapter I need to work around this issue. 

So to make the serialization happen without manipulating Keycloak or using Mixins I think the easiest solution is to extend GenericJackson2JsonRedisSerializer and customize serialization / deserialization to make it work together. 

But if you just need to use it for debugging purposes you can also create a bean of type `KeycloakAuthenticationSuccessHandler` to write some debugging / serializable data to redis as a debug value.

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
