### ISSUE TITLE
Support proxy_protocol

### ISSUE THREAD

**Issue by candlerb** [keycloak/keycloak#10492]
### Description

Allow the listener to be configured to accept the HAProxy [proxy_protocol](https://www.haproxy.com/blog/haproxy/proxy-protocol/), which prefixes each TCP stream with information about the source IP address.

### Motivation

The recommended deployment for Keycloak is behind a load-balancer.

The source IP address which Keycloak sees is the IP address of the load-balancer. The standard solution is for the proxy to add an `X-Forwarded-For:` header giving the original source address.  However this means that the load-balancer must be HTTP-aware, *and* it must decrypt HTTPS before proxying, possibly then re-encrypting to a different hostname.

Supporting proxy_protocol would allow layer 4 load balancers such as haproxy or sniproxy to be used.  They can forward TCP connections unmodified, and hence do not need to decrypt TLS or have any certificates of their own.  If necessary, they can inspect SNI (Server Name Indication) information in the stream to select the backend to send to - although in the case of Keycloak with a dedicated proxy and outside IP address, this would not be necessary.

Overall this would be an improvement in security and performance.

### Details

This would require one or more new listener options.

It would be helpful in some scenarios to have both plain and proxy_protocol listeners.  Therefore, maybe something like this:

```
http-enabled=true
http-host=0.0.0.0
http-port=8080
http-proxy-protocol-enabled=true
http-proxy-protocol-host=0.0.0.0
http-proxy-protocol-port=8081
```

**Comment by chrisFrodo** [comment]
Hello,

I'm very interested in this.
When Keycloak was working with WildFly, send-proxy protocol was supported. Since we tried to use Keycloak with Quakus and our HAProxy load balancers with TLS passthrough we cannot get Remote User IP which is very useful to us.
Our migrations are blocked by this.

I hope this issue will be considered for future releases.

Thanks in advance !

**Comment by ibotty** [comment]
This is still pretty important to not compromise between the load balancer being able to sniff traffic and having brute force detection via IP.

**Comment by symplyf** [comment]
Yeah, this is also a wanted enhancement for K8s setups with an API gateway.

**Comment by shawkins** [comment]
Proxy protocol support was added with https://github.com/quarkusio/quarkus/pull/35470 it appears that just a single config option is needed for this. In the example shown in the description presumably the host / port of the proxy would be  specified as a trusted proxy #32346
