### ISSUE TITLE
Revisit Pod-Template in Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10503]
This is a follow-up from #10098.

The current approach has several severe downsides:
* It is done by [explicitly merging every field](https://github.com/keycloak/keycloak/blob/87b4ee41d42966f19e3a248e7d931cb55eccb795/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java#L202-L349) that is very error-prone and hard to validate (a field could be easily missed and/or wrongly merged).
* The test coverage is incomplete, doesn't cover all fields.

To consider this issue resolved:
* Increase test coverage to include every field.
* If possible, merge the fields in a generic way (probably by using reflections).
* Consider removing Pod-Templates completely if not required anymore.

**Comment by shawkins** [comment]
> If possible, merge the fields in a generic way (probably by using reflections).

This is somewhat possible via ObjectMapper.updateValue, but the current logic for list merging is idiosyncratic - there's no notion of a merge key, and at least for containers it assumes positional. 

The other approach is to instead treat the overlay as the base and use builder edit methods when constructing the baseDeployment.  Let me see how that would look.

 > Consider removing Pod-Templates completely if not required anymore.

co-management is applicable here, but at least initially would trigger an additional rolling - and users would need to make sure their changes were stable as to not trigger additional rollings with other updates.

**Comment by vmuzikar** [comment]
@shawkins Do you plan to pick this up? I think it'd be a nice improvement to finally resolve this.

Yes, it's one more downside – that it requires relying on containers position. But maybe it's good enough as we assume KC itself is always the first container.

> co-management is applicable here, but at least initially would trigger an additional rolling - and users would need to make sure their changes were stable as to not trigger additional rollings with other updates.

The problem I see with the approach of replacing pod templates with co-management (hinting users to directly manage defacto internal Operator resources, e.g. StatefulSet) is that those fields would be marked as managed by something else than the Operator. That means if we eventually decided to manage such field via the Operator (i.e. we'd add a field for it to Keycloak CR), there'd be no direct migration path for users but to delete the StatefulSet (either manually or via the Operator). Yes, this approach works (thanks to SSA) but I wouldn't hint users to use. Additionally, I believe the UX would be a bit worse (modifying existing object after Operator creates it) compared to podTemplate directly in the CR. WDYT?

**Comment by shawkins** [comment]
> Do you plan to pick this up? I think it'd be a nice improvement to finally resolve this.

This is a rough draft of using the builder logic to overlay what's in the CR:

https://github.com/keycloak/keycloak/compare/main...shawkins:iss10503?expand=1

> But maybe it's good enough as we assume KC itself is always the first container.

I think that's the same behavior as a strategic merge patch - but it's only applicable here to containers and not the other lists.

> Additionally, I believe the UX would be a bit worse (modifying existing object after Operator creates it) compared to podTemplate directly in the CR. WDYT?

There's no great way of handling this situation currently unfortunately - it keeps coming up for IngressControllers, Ingress, and in a recent thread on operators for runtimes like eap.  As for deleting the statefulset that should only apply to immutable field changes - but yes there will in general be a fight between controllers if they both think they can own a field.  While we can say that the keycloak operator wins, in practice that means users will have to always adapt their secondary operators to whatever we assume control over.

**Comment by vmuzikar** [comment]
Reopening for backport.
