### ISSUE TITLE
Keycloak.x-16.1.1 : it says it is listening on port 8443 but 443 is used after

### ISSUE THREAD

**Issue by nicoclau** [keycloak/keycloak#10501]
### Describe the bug

Hello I did the commands

kc build --db h2-file
kc start --hostname=XXXX --https-key-store-password=YYY

It logs

2022-02-28 15:48:35,337 INFO [org.key.con.inf.DefaultInfinispanConnectionProvid
erFactory] (main) Node name: XXXX-62107, Site name: null
2022-02-28 15:48:36,572 INFO [io.quarkus] (main) Keycloak 16.1.1 on JVM (powere
d by Quarkus 2.5.3.Final) started in 10.364s. Listening on: https://0.0.0.0:8443/

2022-02-28 15:48:36,572 INFO [io.quarkus] (main) Profile prod activated.
2022-02-28 15:48:36,572 INFO [io.quarkus] (main) Installed features: [agroal, c
di, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, j
dbc-postgresql, keycloak, narayana-jta, reactive-routes, resteasy, resteasy-jack
son, smallrye-context-propagation, smallrye-health, smallrye-metrics, vault, ver
tx]

![image](https://user-images.githubusercontent.com/16133485/156011376-0786d5b4-0b7f-49f2-8aa6-472a01ea2c51.png)

it says it listens on

listening on: 0.0.0.0:8443

https://XXXX:8443 works normally but on the administration console it goes on

XXXX/admin/

 which returns

Not Found
HTTP Error 404. The requested resource is not found.

![image](https://user-images.githubusercontent.com/16133485/156011604-31d26dd6-9122-4c72-9574-fdd7aa14ab7f.png)

so I tried : XXXX:8443/admin/master/console/

it returns the page by empty

Can you explain what i did wrong?
Thanks

### Version

Keycloak.x-16.1.1

**Comment by stianst** [comment]
Please check latest release as there has been a few relevant changes. If still an issue please reopen
