### ISSUE TITLE
Impossible to override iss claim in token mapper

### ISSUE THREAD

**Issue by mryangza** [keycloak/keycloak#10504]
### Describe the bug

Since https://github.com/keycloak/keycloak/pull/8680, it is not possible to override the **iss** claim in the access token. See https://github.com/keycloak/keycloak/issues/9344 for a similar issue with the **acr** claim in the ID token. For clients that connect to KC in a k8s cluster through various proxies, the URL included by KC in the **iss** claim is essentially meaningless (and not accessible). We used to use a token mapper to overwrite the **iss** claim with something identifiable for the realm (e.g. 'issuer-<realmname>') but not an URL.

### Version

16.1.1

### Expected behavior

Be able to customize the **iss** claim in the access token.

### Actual behavior

A KC warning is logged indicating that the **iss** claim is non-modifiable and that the mapper is being skipped.

### How to Reproduce?

Define a custom protocol mapper for the **iss* claim:

```
{
   "id": "7ea4c1e3-6c67-4b4c-a271-eea8e1a7f014",
    "name": "Issuer",
    "protocol": "openid-connect",
    "protocolMapper": "oidc-hardcoded-claim-mapper",
    "consentRequired": false,
    "config": {
       "claim.value": "issuer-myrealm",
        "userinfo.token.claim": "true",
        "id.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "iss",
        "jsonType.label": "String",
        "access.tokenResponse.claim": "false"
   }
}
```

**Comment by Rigobertomarro** [comment]
Gracias por asepter

**Comment by Rigobertomarro** [comment]
> ### Describe the bug
> 
> Since https://github.com/keycloak/keycloak/pull/8680, it is not possible to override the **iss** claim in the access token. See https://github.com/keycloak/keycloak/issues/9344 for a similar issue with the **acr** claim in the ID token. For clients that connect to KC in a k8s cluster through various proxies, the URL included by KC in the **iss** claim is essentially meaningless (and not accessible). We used to use a token mapper to overwrite the **iss** claim with something identifiable for the realm (e.g. 'issuer-<realmname>') but not an URL.
> 
> ### Version
> 
> 16.1.1
> 
> ### Expected behavior
> 
> Be able to customize the **iss** claim in the access token.
> 
> ### Actual behavior
> 
> A KC warning is logged indicating that the **iss** claim is non-modifiable and that the mapper is being skipped.
> 
> ### How to Reproduce?
> 
> Define a custom protocol mapper for the **iss* claim:
> 
> ```
> {
>    "id": "7ea4c1e3-6c67-4b4c-a271-eea8e1a7f014",
>     "name": "Issuer",
>     "protocol": "openid-connect",
>     "protocolMapper": "oidc-hardcoded-claim-mapper",
>     "consentRequired": false,
>     "config": {
>        "claim.value": "issuer-myrealm",
>         "userinfo.token.claim": "true",
>         "id.token.claim": "true",
>         "access.token.claim": "true",
>         "claim.name": "iss",
>         "jsonType.label": "String",
>         "accpm grant com.maxmpz.equalizer android.permission.DUMPess.tokenResponse.claim": "false"
>    }
> }
> ```
> 
> ### Anything else?
- [ ] > > 
> _No response_
- - - - - que@Rigobertomarro @Rigobertomarro ****
[]()

**Comment by stianst** [comment]
The correct way of changing the iss field is to set the hostname of Keycloak to the public URL.

Please check https://www.keycloak.org/server/hostname, or if you are using the legacy distribution please check https://www.keycloak.org/docs/latest/server_installation/index.html#_hostname
