### ISSUE TITLE
issue with hostname-admin

### ISSUE THREAD

**Issue by fyaretskiy** [keycloak/keycloak#10505]
### Describe the bug

If I assume correctly that `hostname-admin` should set front end url for master realm, then this isn't working.

### Version

17.0.0

**Comment by stianst** [comment]
hostname-admin doesn't set the front end URL for the master realm. All it does is configure where the admin UI/endpoints are advertised by Keycloak, to allow you to expose it only internally through a proxy/firewall.

**Comment by fyaretskiy** [comment]
So when setting `hostname-admin`, I expect `/admin/master/console/config` to return `..."auth-server-url":"https://ADMIN-HOSTNAME/"...`. Instead, it returns `..."auth-server-url":"https://HOSTNAME/"...`.

**Comment by tejl** [comment]
How can this issue be rejected? If effectively makes if difficult to follow guidelines from usage of reverse proxy (https://www.keycloak.org/server/reverseproxy) 
if the administration application hosted on a different domain, e.g. https://ADMIN-HOSTNAME/ is sending requests to https://HOSTNAME/admin/master/...

**Comment by zachradtka** [comment]
I face this same issue, an explanation of why the `hostname-admin` property does not work according to the guidelines would be nice.
