### ISSUE TITLE
Invalid parameter - redirect

### ISSUE THREAD

**Issue by lgwapnitsky** [keycloak/keycloak#10528]
### Describe the bug

I have an app that was written with the older version of KC in mind. I've migrated to 17, and exposed the /auth path to make it work, but it appears that the redirect to KC is calling this page directly:

`https://auth.mydomain.com/auth/realms/master/protocol/openid-connect/auth?client_id=dashy&redirect_uri=https%3A%2F%2Fdashboard.mydomain.com%2F&state=79b90704-a9b1-403d-acf1-53bb306e42d0&response_mode=fragment&response_type=code&scope=openid&nonce=512057e6-8f60-40db-806d-aa70c83c4010`

but is returning the following:

`Invalid parameter: redirect_uri`

### Version

17.0

### Expected behavior

Redirect should work to open login page for the app and allow for me to login

### Actual behavior

 returning the following:

`Invalid parameter: redirect_uri`

### How to Reproduce?

Using Dashy dashboard app with keycloak authentication. Have followed direction [here](https://dashy.to/docs/authentication#keycloak)

**Comment by stianst** [comment]
`Invalid parameter: redirect_uri` is shown when the redirect-uri sent by the app does not match the permitted redirect uris for the client.

Make sure the client `dashy` has a valid redirect URI 'https://dashboard.mydomain.com/' configured for it.
