### ISSUE TITLE
Error loading account console

### ISSUE THREAD

**Issue by lgwapnitsky** [keycloak/keycloak#10548]
### Describe the bug

When trying to load the account console for my realm, the page spins endlessly. Errors show up in browser console
![keycloak_account_console_error](https://user-images.githubusercontent.com/647444/156440526-6885b2a9-a892-4a3c-9708-f90ba95c40a5.png)

### Version

17

### Expected behavior

Account console should load properly

### Actual behavior

Error thrown, page never loads

**Comment by ssilvert** [comment]
@lgwapnitsky This does work for other users.  Can you figure out what is unique about your environment that might keep keycloak.js from getting loaded?

**Comment by lgwapnitsky** [comment]
Not sure. I even tried it going in as localhost via ssh and received the
same message on multiple browsers.

I tried a fresh installation on a different box and received the same error
message

**Comment by lgwapnitsky** [comment]
Additionally, I'm running the backend in HTTP mode, and have HAPROXY doing
the SSL on the front end

**Comment by lgwapnitsky** [comment]
Just tested using https on the backend, same result.

this is the conf setting i'm using to expose auth (from the older docs)
http-relative-path=/auth

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by ssilvert** [comment]
OK.  I'm going to go ahead and close this because it's not a bug.  If you need further help you can use our discussion boards.
