### ISSUE TITLE
Impossible to configure multiple JPA PersistentUnit

### ISSUE THREAD

**Issue by sebacla** [keycloak/keycloak#10544]
### Describe the bug

I can't add "UserStorageProvider" type extension with JPA.

I am migrating my provider to keycloak 17.0.0.
My provider uses an external SQLServer database.

I configure quarkus according to the multiple persistent units documentation (https://quarkus.io/guides/hibernate-orm#multiple-persistence-units).
Here is the configuration I entered:

```
#datasource config
quarkus.datasource."users".db-kind=mssql
quarkus.datasource."users".username = user
quarkus.datasource."users".password = password
quarkus.datasource."users".jdbc.url=jdbc:sqlserver://xxxx:1433;databaseName=xxx

quarkus.hibernate-orm."users".datasource = "DSYS"
quarkus.hibernate-orm."users".packages=org.acme
quarkus.hibernate-orm."users".dialect = org.hibernate.dialect.SQLServerDialect
```

My EntityManager has the following annotations:

```
@Inject
@PersitentUnit("users")

```
My entities have the following annotation:

`@Entity`

I see my entities when starting quarkus in DEBUG mode but they are systematically attached to the PersistentUnit keycloak-default.

### Version

17.0.0

### Expected behavior

Entities must be attached to the defined PersistentUnit (users)

Add an example to keycloak-quickstart https://github.com/keycloak/keycloak-quickstarts

### Actual behavior

Entities are attached to the default PersistentUnit (keycloak-default)

### How to Reproduce?

Adapt https://github.com/keycloak/keycloak-quickstarts/tree/latest/user-storage-jpa to use with the quarkus distribution.

**Comment by pedroigor** [comment]
@ahus1 Could you please check https://github.com/keycloak/keycloak/pull/10581?

**Comment by pedroigor** [comment]
Fixed by https://github.com/keycloak/keycloak/issues/10579
