### ISSUE TITLE
keycloak health check

### ISSUE THREAD

**Issue by manbobo2002** [keycloak/keycloak#10559]
### Describe the bug

How can I health check keycloak?

```
curl  http://localhost:8080/auth/realms/master/health/check
{"error":"HTTP 404 Not Found"}
```
I just curl like above but return resource not found, how do I ensure keycloak is healthy?

### Version

17.0.0

**Comment by Wolfsrudel** [comment]
At the moment you'll have to enable metrics und use the following link (if your `http-relative-path` is `/auth`):
```
curl  http://localhost:8080/auth/health
```

**Comment by pierreprinetti** [comment]
Didn't seem to work on my machine

```shell
podman run --rm -it -p 8080:8080 -p 8443:8443 quay.io/keycloak/keycloak:17.0.0 start-dev --metrics-enabled=true
```
```shell
$ curl 'localhost:8080/auth/health'
{"error":"RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/health"}
```

**Comment by pierreprinetti** [comment]
This worked:

```shell
podman run --rm -it -p 8080:8080 -p 8443:8443 quay.io/keycloak/keycloak:17.0.0 start-dev --metrics-enabled=true
```

```shell
$ curl -i 'http://localhost:8080/health'
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 159


{
    "status": "UP",
    "checks": [
        {
            "name": "Keycloak database connections health check",
            "status": "UP"
        }
    ]
}
```

Along with its friends [`live` and `ready`](https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/health.adoc).

**Comment by pierreprinetti** [comment]
Interestingly, the `--metrics-enabled` flag does not work with `start`, but only with `start-dev`.

```shell
$ podman run --rm -it -p 8080:8080 -p 8443:8443 quay.io/keycloak/keycloak:17.0.0 start --hostname=localhost:8080 --metrics-enabled=true
Unknown option: '--metrics-enabled=true'
```

And if I remove the flag, no health check to be seen.

```
$ podman run --rm -it -p 8080:8080 -p 8443:8443 quay.io/keycloak/keycloak:17.0.0 start --hostname=localhost:8080 --proxy=edge
```

```
$ curl -i -H 'Host: localhost:8080' 'http://localhost:8080/health'
HTTP/1.1 404 Not Found
content-length: 0

$ curl -i -H 'Host: localhost:8080' 'http://localhost:8080/auth/health'
HTTP/1.1 404 Not Found
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json
content-length: 100

{"error":"RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/health"}
```

**Comment by manbobo2002** [comment]
yes, it worked for me, just closed this ticket.

Please note that curl  http://localhost:8080/auth/health depends on `http-relative-path is /auth`

**Comment by Wolfsrudel** [comment]
> Interestingly, the `--metrics-enabled` flag does not work with `start`, but only with `start-dev`.
> 
> ```shell
> $ podman run --rm -it -p 8080:8080 -p 8443:8443 quay.io/keycloak/keycloak:17.0.0 start --hostname=localhost:8080 --metrics-enabled=true
> Unknown option: '--metrics-enabled=true'
> ```
> 
> And if I remove the flag, no health check to be seen.
> 
> ```
> $ podman run --rm -it -p 8080:8080 -p 8443:8443 quay.io/keycloak/keycloak:17.0.0 start --hostname=localhost:8080 --proxy=edge
> ```
> 
> ```
> $ curl -i -H 'Host: localhost:8080' 'http://localhost:8080/health'
> HTTP/1.1 404 Not Found
> content-length: 0
> 
> $ curl -i -H 'Host: localhost:8080' 'http://localhost:8080/auth/health'
> HTTP/1.1 404 Not Found
> Referrer-Policy: no-referrer
> X-Frame-Options: SAMEORIGIN
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> Content-Type: application/json
> content-length: 100
> 
> {"error":"RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/health"}
> ```

I mentioned that relative path is set to /auth in my example and metrics-enabled is a build option so you first should use build. start-dev has the built option build in so it's working for sure.

**Comment by Wolfsrudel** [comment]
> yes, it worked for me, just closed this ticket.
> 
> Please note that curl http://localhost:8080/auth/health depends on `http-relative-path is /auth`

As I've mentioned.

**Comment by Abdelouahedd** [comment]
if you are using keycloak in docker, just set KC_HEALTH_ENABLED to true and you can check the health trow the URL http://localhost:8080/health/ready

**Comment by gordonhjko** [comment]
The doc https://www.keycloak.org/server/all-config?f=build mentioned nothing about the auth relative path or how to make config work. I got the same error

% curl -i -H 'Host: localhost:8080' 'http://localhost:8080/health'
HTTP/1.1 404 Not Found
content-length: 0

**Comment by devlifealways** [comment]
Had the same issue, I was trying to deploy K.C 24.0.4 using postgres backend, but then the operator started the STS with `--optimized` flag that broke the workload. The workaround here is to build an optimized OCI image beforehand with health checks enabled by default, otherwise Kubernetes' probes will fail

```docker
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
...
```

Hope it helps

**Comment by KostaPo** [comment]
any good solutions?
