### ISSUE TITLE
Keycloak returns Unauthorized 401

### ISSUE THREAD

**Issue by zeynepuyyanik** [keycloak/keycloak#10556]
### Describe the bug

I'm running bitnami's Keycloak image on my local. what I want to do is; use Keycloak REST APIs. but no matter how hard I try, I'm getting 401.

I have done what's written in the doc. so this is a screenshot of the client. access type is confidential, and a service account is enabled. this is testapi client that I created;
![image](https://user-images.githubusercontent.com/75336267/156453917-d98f84cb-c494-4885-8008-05e6b6b48c1d.png)

here you can see the service account roles;
![image](https://user-images.githubusercontent.com/75336267/156453952-4fdd638a-3bca-4e4f-8184-4c12388970f8.png)

to view and manage users, I assigned manage-users and view-user roles.

firstly, to get the `access_token `, I'm using `client_id `and `client_credential`. as you can see from here;
![image](https://user-images.githubusercontent.com/75336267/156454003-291123fb-eaf2-4288-9551-db24fc177a0c.png)

I have no problem getting the access token.

but when I try to get the user list or create a new user, I always get 401. here you can see that I used the SAME access_token that I got from the http://localhost:8092/auth/realms/test/protocol/openid-connect/token

![image](https://user-images.githubusercontent.com/75336267/156454032-772d6beb-54d8-4a30-b54e-f0139402ed08.png)
it doesn't make sense. I started to think about smashing the computer.

any help would be greatly appreciated

### Version

bitnami/keycloak/latest

**Comment by ahus1** [comment]
Looking at this issue you're using a bitnami image, and not one of the original Keycloak images. I can't determine the Keycloak version you're using. Please use an original Keycloak image and provide the version you're using when opening an issue.

A general advice: have a look at the logs of Keycloak to find out why an access token was rejected. There might be permission problem, or they might have been expired. Sites like https://jwt.io/ are usually quite helpful to find out what is stored in the access token in terms of permission and expiry time.

**Comment by abhishekgandhe** [comment]
Hi,

I am facing similar issue, but facing 403: Forbidden. 

Tried to provide the additional roles to clientID - view-users, query-users, query-clients - but none of them is working and still getting 403.

Pls help

Tx

**Comment by MahsaRamezani** [comment]
Hi,
Actually, you should  set the Authorization Header in Headers tab.

**Comment by pike-msonda** [comment]
I know this issue was closed. But just in case anyone is stuck. I was experiencing the same issue simply because I was using **http://127.0.0.1:8080/admin/realms/test/users** instead of  **http://localhost:8080/admin/realms/test/users**

**Comment by gilamarko** [comment]
I'm facing the same exact issue, any tips on how you guys solved this?

**Comment by jonkoops** [comment]
Use the latest version of Keycloak, we will not provide patches for older versions.

**Comment by gilamarko** [comment]
Ok I get that but I still cannot understand what's the issue here... I'm not asking for a patch or something. Normally this should be working.
