### ISSUE TITLE
Incorrect documentation for setting truststore for mTLS

### ISSUE THREAD

**Issue by tanadeau** [keycloak/keycloak#10553]
### Describe the bug

Per https://www.keycloak.org/server/enabletls, I should be able to set a truststore for mTLS using `KC_HTTPS_TRUST_STORE_FILE` and `KC_HTTPS_TRUST_STORE_PASSWORD`; however, this doesn't work and the truststore is null with the following warning among others:
```
2022-03-02 17:50:13,341 WARN  [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (executor-thread-2) Keycloak Truststore is null, but it is required !
2022-03-02 17:50:13,341 WARN  [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (executor-thread-2)   see https://www.keycloak.org/docs/latest/server_installation/index.html#_truststore
```

Instead if I use `KC_SPI_TRUSTSTORE_FILE_FILE` and `KC_SPI_TRUSTSTORE_FILE_PASSWORD`, things work as expected.

Also note that on https://www.keycloak.org/server/enabletls, there is also a typo in several places where `https.` and other dots are used for config keys instead of the `-`.

In the mTLS section of the reverse proxy docs (not yet released), it would also be good to mention that setting the truststore is required when using `x509cert-lookup`.

### Version

17.0.0

### Expected behavior

Configuration keys mentioned in TLS docs work as expected.

### Actual behavior

Need to use other undocumented keys to get truststore to work.

### How to Reproduce?

Entrypoint script:
```shell
#!/bin/bash

set -e

if [[ -n "${MTLS_CA}" ]]; then
    echo "mTLS is enabled"
    mtls_ca_path="/tmp/clientCertCA.pem"
    truststore_path="/tmp/truststore.jks"
    truststore_password="$(</dev/urandom tr -dc '[:alnum:]' | fold -w "${1:-20}" | head -n 1)"

    cat >"${mtls_ca_path}" <<EOF
${MTLS_CA}
EOF

    /usr/bin/keytool \
        -import \
        -noprompt \
        -keystore "${truststore_path}" \
        -file "${mtls_ca_path}" \
        -storetype jks \
        -storepass "${truststore_password}" \
        -alias "mTLS"

    # These don't seem to work, but the group below using SPI does.
    export KC_HTTPS_TRUST_STORE_FILE="${truststore_path}"
    export KC_HTTPS_TRUST_STORE_PASSWORD="${truststore_password}"
    export KC_HTTPS_TRUST_STORE_TYPE=jks

    export KC_SPI_TRUSTSTORE_FILE_FILE="${truststore_path}"
    export KC_SPI_TRUSTSTORE_FILE_PASSWORD="${truststore_password}"
else
    echo "mTLS is disabled"
fi

/opt/keycloak/bin/kc.sh start --auto-build
```

Relevant environment variables:
```shell
KC_HOSTNAME=myHostname
KC_PROXY=edge
KC_HTTP_ENABLED=true
KC_HTTP_RELATIVE_PATH=/auth
KC_SPI_X509CERT_LOOKUP_PROVIDER=nginx
KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT="ssl-client-cert"
MTLS_CA=myCaContents
```

**Comment by oranki** [comment]
Correct `keycloak.conf` options for defining a JKS trust store for outbound SSL connections are `spi-truststore-file-file` and `spi-truststore-file-password`. This was needed to configure LDAPS user federation source.

Documentation at https://www.keycloak.org/server/enabletls is either incorrect or incomplete, and the [server admin guide](https://www.keycloak.org/docs/latest/server_admin/index.html#connecting-to-ldap-over-ssl) links to old WildFly-based distro docs.

**Comment by v1nc3nt27** [comment]
For me it still doesn't work. Neither with the ENVs nor with the start script parameters and it says 

```
2022-03-22 09:40:57,782 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-03-22 09:40:57,783 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
```

Which doesn't really make sense because the trust store is definitely there and using this truststore with keycloak 16 worked. Does anyone have an idea why I could possibly get this error?

**Comment by ipax77** [comment]
I did not manage to make the keystore work neither with 
KC_HTTPS_TRUST_STORE_FILE nor KC_SPI_TRUSTSTORE_FILE_FILE
what worked for me are
```
KC_HTTPS_CERTIFICATE_KEY_FILE
KC_HTTPS_CERTIFICATE_FILE
```
btw Keycloak 17 is still logging "For more details run the same command passing the '--verbose' option." But you have to use `--log-level DEBUG` now.

**Comment by kelimutu** [comment]
Same here: Neither KC_HTTPS_TRUST_STORE_FILE nor KC_SPI_TRUSTSTORE_FILE_FILE

**Comment by fredericoschardong** [comment]
Same here: Neither KC_HTTPS_TRUST_STORE_FILE nor KC_SPI_TRUSTSTORE_FILE_FILE

**Comment by fredericoschardong** [comment]
Same here: Neither KC_HTTPS_TRUST_STORE_FILE nor KC_SPI_TRUSTSTORE_FILE_FILE

**Comment by fredericoschardong** [comment]
Same here: Neither KC_HTTPS_TRUST_STORE_FILE nor KC_SPI_TRUSTSTORE_FILE_FILE

**Comment by grossws** [comment]
`KC_SPI_TRUSTSTORE_FILE_FILE` works for me with JKS store (with custom CA) + `KC_SPI_TRUSTSTORE_FILE_PASSWORD=changeit` (system-global cacerts on RHEL8-like) for LDAP user federation (only `ldaps://`, StartTLS still doesn't work).

**Comment by fredericoschardong** [comment]
This did the trick for me:

```
USER root
RUN chmod 755 /opt/keycloak/conf/tls.key```

**Comment by ykuksenko** [comment]
Neither trust store environment variable worked correctly for me. Updating the OS trust store did. See https://github.com/keycloak/keycloak/issues/9313#issuecomment-1135359416

**Comment by pedroigor** [comment]
@tanadeau Could you please check https://github.com/keycloak/keycloak/pull/12261?

It should solve the issue you reported.

**Comment by pedroigor** [comment]
@grossws W.r.t. to using `ldaps` can we discuss this topic here https://github.com/keycloak/keycloak/issues/11772?

**Comment by tanadeau** [comment]
@pedroigor, I think your PR addresses the documentation comments I had for this ticket. Thanks!

**Comment by pedroigor** [comment]
Thanks.

Superseded by https://github.com/keycloak/keycloak/issues/12260.

**Comment by inad9300** [comment]
@fredericoschardong I'm using Keycloak through Docker too, and indeed the problem was with permissions – thank you! Although the specific permissions you are setting (755) seem a bit too generous.

In my case, I solved it with `COPY --chown=keycloak ./keycloak.crt ./keycloak.key /opt/keycloak/conf` (notice the "chown" part). When the file is owned by "keycloak" (the default user in the official Docker image), you can keep the private key only accessible to the file owner (e.g. 400 to make it read-only).

**Comment by rubendevgo** [comment]
@inad9300 I'm struggling too using Keycloak through Docker, can I know how did you manage this, more specifically in setting the truststore.

**Comment by inad9300** [comment]
It's been a while now, but other than the copy instruction from my previous comment, I defined these two environment variables in my Docker Compose file (among others):
```yaml
environment:
  - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/keycloak.crt
  - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/keycloak.key
```
And that is all, as far as I can remember.

**Comment by MohammedNoureldin** [comment]
Does StartTLS work for anybody? For me, when I try to connect to an LDAP server over LDAPS, both connection and authentication work properly, and removing the certificate causes LDAPS to fail, which proves that the CA in my truststore works well.

However, when I use StartTLS (ldap://..) the connection fails with the following error:

> Error when connecting to LDAP: Could not negotiate TLS: javax.naming.AuthenticationException: Could not negotiate TLS [Root exception is javax.naming.CommunicationException: Connection reset [Root exception is java.net.SocketException: Connection reset]]

I am not sure what is wrong here, because as shown above, the certificate seems to be trusted by my truststore.
