### ISSUE TITLE
Sonarqube Report - Blockers/Major issues noticed

### ISSUE THREAD

**Issue by murugan425** [keycloak/keycloak#10560]
### Describe the bug

Hi Keycloak Team,

Recently, we tried to run a SonarQube check against the Keycloak 15 version, to check about the vulnerability and surprise to notice that there were around 50 blockers & 75 critical issues reported. Please confirm on the quality checks being performed on keycloak. Whether this was expected to happen, and similar case with respect to security checks as well.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/1759522/156496176-497b1093-5c54-4179-bce6-5349f27b0c4c.png">

### Version

15

**Comment by stianst** [comment]
Keycloak 15 was released in July 2021 so not surprised there are CVEs there. Bear in mind that tools like SonarQube also report a significant number of false positives.

Please test with the latest release, and review the output. If you identify any issues please refer to our [security policy](https://github.com/keycloak/keycloak/security/policy) on how to disclose this to us in a responsible way.
