### ISSUE TITLE
external IdP - invalid request error

### ISSUE THREAD

**Issue by dsukhoroslov** [keycloak/keycloak#10566]
### Describe the bug

I'm not sure is it a bug or not, may be just need to add something to my IdP or client app config. I found several mentions of this issue (e.g. https://lists.jboss.org/pipermail/keycloak-user/2018-March/013448.html), but all without clear solution, unfortunately.

My setup is:
- demo-app, protected by keycloak
- keycloak has IdP configured to use my aas-app
- aas-app (built on top of Spring Boot Authorization Server)

The Login flow is:
- user opens protected page in demo-app
- spring security redirects user to keycloak login page with extra IdP button
- user hits extra IdP button
- keycloak redirects user to aas-app /authorize endpoint (authorization code flow)
- aas-app presents custom login page with login button
- user provides his info and hits login button
- aas-app authenticates user and returns authorization code to keycloak
- keycloak requests access and id tokens from /token endpoint providing authz code
- aas-app return tokes requested
- keycloak requests user data to synchronize from /userinfo endpoint providing tokens
- aas-app return claims requested
- keycloak receive user data and stores it in realm
- now keycloak is ready to do redirect back to demo-app and tries to build redirect response
- but it cannot find some required parameters and shows error (Invalid Request)

the relevant part from keycloak log is: 
```
12:31:40,523 DEBUG [org.keycloak.protocol.oidc.OIDCLoginProtocol] (default task-1) redirectAccessCode: state: d2oKa9Zk_YjlAAeQk3NY6Qz7tMxFI4Z6ASQ4n-04sbc=
12:31:40,525 DEBUG [org.keycloak.models.sessions.infinispan.InfinispanSingleUseTokenStoreProviderFactory] (default task-1) Not having remote stores. Using normal cache 'actionTokens' for single-use cache of token
12:31:40,533 DEBUG [org.keycloak.events] (default task-1) type=LOGIN, realmId=gaia-x, clientId=demo-app, userId=aae8a528-d546-4865-81cf-33e7153b1c36, ipAddress=127.0.0.1, identity_provider=ssi-oidc, response_type=code, redirect_uri=http://key-server:8080/auth/realms/gaia-x/broker/ssi-oidc/endpoint, consent=no_consent_required, identity_provider_identity=test@test.com, code_id=af600925-e9d9-4e48-b22e-c50a5042e3a8, username=user, response_mode=query, authSessionParentId=af600925-e9d9-4e48-b22e-c50a5042e3a8, authSessionTabId=PJRZoDOc-z0
12:31:40,545 DEBUG [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-1) authResponse. authCode=04ca6608-1b80-4c60-8b50-58845573eafa.af600925-e9d9-4e48-b22e-c50a5042e3a8.2334e2a3-ed43-4a2e-86cc-443a3d3280bd, state=d2oKa9Zk_YjlAAeQk3NY6Qz7tMxFI4Z6ASQ4n-04sbc=, error=null
12:31:40,546 DEBUG [org.keycloak.services.resources.IdentityBrokerService] (default task-1) getAndVerifyAuthenticationSession. encodedCode=d2oKa9Zk_YjlAAeQk3NY6Qz7tMxFI4Z6ASQ4n-04sbc=, state=org.keycloak.broker.provider.util.IdentityBrokerState@684224c7
12:31:40,548 DEBUG [org.keycloak.services.resources.IdentityBrokerService] (default task-1) Invalid request. Authorization code, clientId or tabId was null. Code=d2oKa9Zk_YjlAAeQk3NY6Qz7tMxFI4Z6ASQ4n-04sbc=, clientId=null, tabID=null

```

### Version

16.1.1

### Expected behavior

keycloak has authenticated user via external IdP. now it has to build response with auth token and redirect user back to demo-app

### Actual behavior

the error raised at https://github.com/keycloak/keycloak/blob/09c39b90f10908ed0e37a15343733ddf54262128/services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java#L1042

it looks like keycloak lost clientId and tabId parameters required in redirect response.. encodedCode used at this place does not have clientId not tabId fields, only the authorizationCode field. 

### How to Reproduce?

try the auth flow I explained above

### Anything else?

[keycloak.log](https://github.com/keycloak/keycloak/files/8176925/keycloak.log)

Please see the keycloak debug log above. I added a bit more debug logs and stack trace around the place where Invalid Request error raised. I can provide aas-app and demo-app logs if they're required.

Thanks, Denis

**Comment by dsukhoroslov** [comment]
as I found, the issue caused by wrong settings in my demo app. after I removed them, the whole flow works as expected.

**Comment by alirizaaribas-ibg** [comment]
> as I found, the issue caused by wrong settings in my demo app. after I removed them, the whole flow works as expected.

Hello @dsukhoroslov, can you share the solution? I need to apply it for temporarily.

**Comment by dsukhoroslov** [comment]
the application.yml is:
```
server:
  port: 8990
spring:
  security:
    oauth2:
      client:
        registration:
          demo-app-oidc:
            provider: keycloak
            client-id: demo-app
            client-secret: secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://my-key-server:8080/realms/my-realm
```
the SecurityConfig is:
```
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
          .authorizeRequests(authorizeRequests ->
              authorizeRequests.anyRequest().authenticated()
          )
          .oauth2Login(oauth2Login ->
              oauth2Login.loginPage("/oauth2/authorization/demo-app-oidc"))
          .oauth2Client(Customizer.withDefaults());
        return http.build();
    }
    
}
```
