### ISSUE TITLE
docs: Getting started with OpenShift

### ISSUE THREAD

**Issue by pierreprinetti** [keycloak/keycloak#10569]
### Describe the bug

The [docs](https://www.keycloak.org/getting-started/getting-started-openshift) and the linked [yaml](https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/openshift-examples/keycloak.yaml) use `KEYCLOAK_USER` and `KEYCLOAK_PASSWORD`. Is it possible that in v17 (Quarkus) the same values need to be set to  `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` respectively?

### Version

17

**Comment by DGuhr** [comment]
Hey hey, sorry for reaching out late. Seems the changes I made before 17 were killed by switching the main branch from latest to main, so I had to reapply them here: https://github.com/keycloak/keycloak-web/pull/288 and here: https://github.com/keycloak/keycloak-quickstarts/pull/304 - will work again :) (as long as noone renames the primary branch again ^^ i was really confused, asked myself if I had only dreamt doing this 😄 )
