### ISSUE TITLE
Wrong spelling in StringKeyConvertor

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#10573]
### Describe the bug

[`StringKeyConvertor`](https://github.com/keycloak/keycloak/blob/92f6c753281079624c08583bd91dba3c474d833f/model/map/src/main/java/org/keycloak/models/map/common/StringKeyConvertor.java) should be spelled as `StringKeyConverter` notice the change from `-or` to `-er`.

### Version

17.0.0

**Comment by ahus1** [comment]
To summarize: it's almost always a converter, unless electricity is involved: 
https://thecontentauthority.com/blog/convertor-vs-converter
