### ISSUE TITLE
Split configuration parameter metrics-enabled into one for metrics and one for healthcheck

### ISSUE THREAD

**Issue by m4rc77** [keycloak/keycloak#10570]
### Description

Currently there is the configuration option `metrics-enabled` in the Keycloak 17 configration, if it is enabled, metrics are available at the `/metrics` endpoint and healthcheck at the `/health` endpoint.

For customers that only want healthcheck but not the metrics this is not ideal.

### Motivation

To have the choice to either have metrics and/or healthcheck endpoint enabled, the current configuration parameter should be split into two parameters.

### Details

The `metrics-enabled` should only enable the  `/metrics` endpoint.

A second configuration parameter `healthcheck-enabled` should be added, in order to individually enable the  `/health` endpoint. This option should be `true` (enabled) by default.

**Comment by hc42** [comment]
Have you tried `health-enabled` (https://github.com/keycloak/keycloak/search?q=health-enabled)? Or is it something different you are looking for?

**Comment by Wolfsrudel** [comment]
> Have you tried `health-enabled` (https://github.com/keycloak/keycloak/search?q=health-enabled)? Or is it something different you are looking for?

This isn't merged to the main branch or a release yet.

**Comment by DGuhr** [comment]
Hey :) we had #10224 and #10395 for this topic and @andreaTP  implemented it in #10396 - so as the others stated, it will be part of the next version of Keycloak.  When you can't wait / want to try it out, feel free to build latest main (e.g. by running `mvn clean install -DskipTests` from the quarkus subdirectory. Zip/tar will be generated in `quarkus/dist/target`. 

I'll close this for now, feel free to re-open when the above is not what you had in mind.

**Comment by m4rc77** [comment]
`health-enabled` is what I was looking for. As far as I can see in #10224 this will be part of **17.1.0**. Thanks!
