### ISSUE TITLE
Third Party Identity Provider adding null attributes breaking search

### ISSUE THREAD

**Issue by HJain01** [keycloak/keycloak#10578]
### Describe the bug

When using a third-party identity provider to create a user and not collecting that user's name, the `fed_user_attribute` table is being populated with attributes that are null instead of not having the attributes in the table.

### Version

16.1.1

### Expected behavior

When certain attributes are not collected, there should not be rows in the `fed_user_attribute` table for those attributes.

### Actual behavior

When certain attributes are not collected, there are rows in the `fed_user_attribute` table for those attributes, but they have null values. This causes the search for that user to throw a null pointer exception.

### How to Reproduce?

Have the ability to sign into Keycloak using a third-party identity provider. Then set the `first login flow` to a flow where you don't `review profile` so that it doesn't collect their name. When the user goes through the registration process with that identity provider, they will not be searchable in the keycloak admin console due to the `FIRST_NAME` and `LAST_NAME` attributes being null.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
