### ISSUE TITLE
Refresh access token only on axios call; disable background refreshing by keycloak-js and @react-keycloak/web

### ISSUE THREAD

**Issue by helenazhang27** [keycloak/keycloak#10584]
### Describe the bug

We want to use “Client Session Idle” so that after the user has been idle for 5 minutes on our website, meaning no action has been performed in 5 miutes, even if the session is still validated, we want to redirect the user to login. 

To achieve this, we try to refresh the access token only when the user triggers a backend call. We call “ontokenExpired()” in our custom axios response interceptor. However, in the background, the library automatically refreshes the token when the token expires even when no axios calls have been made; we want to disable this background refresh. 

We have tried to config keycloak instance on creation following this keycloak.init({"checkLoginIframe" : false}), 
But the login page url indefinitely toggles been our loginpage: http://localhost:3000/login and this page:
http://localhost:3000/login#error=login_required&state=662c92ea-2fb9-410f-94fc-cc86610b501f. We can’t perform any action to our login page to get to our protected pages.

### Version

16.1.0

### Expected behavior

We expected to login into our app and trigger a refresh token call only when an axios call is triggered and if the user hasn't made any calls before the "Client Session Idle" is up, redirect user to login.

### Actual behavior

If we setup our keycloak object with no configurations: 
in the background, the library automatically refreshes the token when the token expires even when no axios calls have been made; we want to disable this background refresh. 

If we configure the keycloak instance, the login page url indefinitely toggles been our loginpage: http://localhost:3000/login and this page:
http://localhost:3000/login#error=login_required&state=662c92ea-2fb9-410f-94fc-cc86610b501f. We can’t perform any action to our login page to get to our protected pages.

### How to Reproduce?

In a react app, our versioning:
 "react": "^17.0.2",
 "react-dom": "^17.0.2",
 "react-router-dom": "^5.2.0",
 "typescript": "^4.3.2"
 
In our App.tsx: 

Import keycloak-js and @react-keycloak/web. Create a keycloak instance to pass to the ReactKeycloakProvider that wraps the BrowserRouter. In the keycloak client advanced settings:

Access token lifespan: 5 min
Client Session Idle: 30 minutes
Client Session Max: 10 hours

**Comment by stianst** [comment]
There isn't any background refresh of the token in keycloak.js, so not sure what is going on here. Perhaps that's something `@react-keycloak/web` is doing, but that is not a library we maintain.

**Comment by MaheshSurepalli** [comment]
I'm also facing the same issue, I want to disable the background token refresh how can I do that? Has anyone found the solution for that?

**Comment by jonkoops** [comment]
As mentioned before Keycloak JS does not 'auto refresh' tokens. This is a problem specific to the library in question, please report the issue there.
