### ISSUE TITLE
Flaky KeycloakServicesE2EIT.testDiscoveryServiceDurability

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#10587]
### Describe the bug

The operator test: `KeycloakServicesE2EIT.testDiscoveryServiceDurability` spuriously failed here:

https://github.com/keycloak/keycloak/runs/5413342790?check_suite_focus=true

### Version

latest

**Comment by andreaTP** [comment]
Update, we have a slight instability in the operator CI tests, since they are mandatory we should address it:

https://github.com/andreaTP/keycloak/actions/runs/1932839938

cc. @vmuzikar

**Comment by mabartos** [comment]
@andreaTP @vmuzikar Yep, as it's a required stage for each PR, it should be resolved ASAP. Is anybody working on that?

**Comment by andreaTP** [comment]
@mabartos I'm on it 👍

**Comment by andreaTP** [comment]
update:
thanks to @csviri we managed to narrow down the issue to a race condition in the [JOSDK](https://github.com/java-operator-sdk/java-operator-sdk), he is working on a fix, and I'm working on a mitigation for the Keycloak CI.
