### ISSUE TITLE
Keycloak 17 Quarkus is not using db-schema parameter properly

### ISSUE THREAD

**Issue by mvk37** [keycloak/keycloak#10582]
### Describe the bug

I am trying to deploy Keycloak 17 Quarkus with MariaDb and schema name different from default 'keycloak'.

I created database with name 'db4keycloak' and trying to start Keycloak. 

```
 bin/kc.sh start-dev \
  --db mariadb \
  --db-url-host localhost \
  --db-username keycloak \
  --db-password mypwd \
  --db-schema db4keycloak
```

And getting error:

`022-03-03 21:17:17,040 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLSyntaxErrorException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=45) Unknown database 'keycloak'
`
Keycloak is still trying to connect to default database 'keycloak' in JdbcEnvironmentInitiator.

### Version

17.0.0

### How to Reproduce?

1. Install MariaDb
2. Create database user 'keycloak' and database 'db4keycloak'

```
create database db4keycloak;
GRANT ALL PRIVILEGES ON db4keycloak.* to keycloak@'%' IDENTIFIED BY 'mypwd'; 
GRANT ALL PRIVILEGES ON db4keycloak.* to keycloak@'localhost' IDENTIFIED BY 'mypwd';
flush privileges;
```
3. Start Keycloak:

```
 bin/kc.sh start-dev \
  --db mariadb \
  --db-url-host localhost \
  --db-username keycloak \
  --db-password mypwd \
  --db-schema db4keycloak
```

You will see error message:

```
[org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLSyntaxErrorException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=50) Unknown database 'keycloak'
```

**Comment by hc42** [comment]
Problem here is that the parameter `db-schema` is only applied to [quarkus.hibernate-orm.database.default-schema](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.database.default-schema) 

(see https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java#L82)

This does however not affect the connection url default schema:
https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/database/Database.java#L129

There the default value `keyloak` is hardcoded.
For an immdiate solution set the parameter `db-url-database`
https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java#L57

The provided merge request fixes the problem by using db-schema as default, if set, and then falls back to `keycloak`if both params are unset.

**Comment by mvk37** [comment]
Thank you. Can we close the issue now?

**Comment by hc42** [comment]
I would wait util the merge request is accepted / merged and then close it.

**Comment by pedroigor** [comment]
@mvk37 Thanks for the contribution but perhaps the meaning of `db-schema` is not so clear.

The `db-schema` is used to set the schema and not really the database name. The option is mainly used by our database-related providers to use a specific schema other than the database default (for instance, in PostgreSQL will be the schema `public`).

Perhaps you are looking for is the `db-url-database` option:

```
kc.sh start --db-url-database db4keycloak
```

**Comment by mvk37** [comment]
Hi Pedro. 'Database' in MySQL/MariaDb is the same as schema in other databases. They have a command 'create database' which is creating database schema. I think my request is still correct.

**Comment by stianst** [comment]
@mvk37 it is equivalent, but not the same. MariaDB/MySQL refers to it as database, and it is specified as part of the connection string, while other databases have schema as something you specify after connecting to the database, and you can also run queries to different schemas in the same connection.

Could you please give `--db-url-database` a go as it should provide you with the results you are looking for.

**Comment by pedroigor** [comment]
@mvk37 Thanks. Based on https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html looks like the format of the JDBC Url is:

```
protocol//[hosts][/database][?properties]
```

And the `db-url-database` is changing the `database` portion of the URL.

That said, I'm still not convinced that using `db-schema` is appropriate.

**Comment by lucrus73** [comment]
> Could you please give `--db-url-database` a go as it should provide you with the results you are looking for.

Having the same problem as @mvk37 I tried this with KC 18, but it seems it is ignoring the `--db-url-database` option, since it still uses the default `keycloak` database. Here is the command I use to run KC 18:

    ./bin/kc.sh -v start --hostname=fqdn.and.hostname --https-certificate-file=/etc/letsencrypt/live/fqdn.and.hostname/cert.pem --https-certificate-key-file=/etc/letsencrypt/live/fqdn.and.hostname/privkey.pem --db-url-host localhost --db-username root --db-password secret --proxy=reencrypt --db-url-database=kc_db

**Comment by lucrus73** [comment]
Never mind, it's not ignoring the `--db-url-database` option at all. My problem was I had not run `kc.sh build --db mariadb` when I upgraded from KC 17, because I assumed it wasn't necessary since I had already run that in KC 17. My fault.

**Comment by DGuhr** [comment]
to wrap up from what I understood `--db-url-database` should be used as mysql/mariadb doesn't have the `schema` concept and this issue and PR could be closed then. Feel free to re-open when I miss something :) 

_note to future me: when we have the ability to show config based on a rule engine ("dependant"), we should remove the db-schema option at runtime when database == mariadb/mysql at buildtime._

**Comment by sheecegardezi** [comment]
KC_DB_SCHEMA still does not work for postgres database. Maybe it would be better to actully have an example of the steps involved in changing the schema. The documentation is misleading.
