### ISSUE TITLE
Plain logs (no color) formatting

### ISSUE THREAD

**Issue by squalou** [keycloak/keycloak#10607]
### Description

Having a way to customize log format is great but incomplete.

Right now we can play with this option : 

`KC_LOG_FORMAT="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"`

But it always outputs color codes. Which is a real pain 
- on some terminals that don't support them, 
- AND mostly when one wants to transfer logs to another system (ELK, you name it)

### Motivation

Keycloak Clusters installed within container-based cloud provider solutions (K8's, AWS ECS for instance),
with external centralized logging system (Elastisearch for instance).

### Details

Toggle feature maybe.

**Comment by DGuhr** [comment]
I just provided an overhaul to logging in #10576 

@stianst @pedroigor It seems we should add the switch for enabling/disabling colors in console logging for the reasons mentioned above. Should be easy to add a `--log-console-color=true/false`, defaulting to true. I'd like to add it to the PR tomorrow, if you don't object. Quarkus property to wrap is `quarkus.log.console.color=true|false`

**Comment by DGuhr** [comment]
added a switch `--log-console-color=true/false` to #10576

**Comment by DGuhr** [comment]
Closed by #10576 :) now no-color logs are the default, see discussion on the pr. the color switch can be used to turn them on if needed.
