### ISSUE TITLE
java.io.FileNotFoundException:  ..../keycloak-17.0.0/model/jpa/target/test-classes/log4j.properties 

### ISSUE THREAD

**Issue by primillet** [keycloak/keycloak#10613]
### Describe the bug

Following the document https://github.com/keycloak/keycloak/blob/main/docs/building.md to build keycloak, the build is failed due to the missing of log4j.properties.

[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ keycloak-model-jpa ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.keycloak.connections.jpa.util.JpaUtilsTest
log4j:ERROR Could not read configuration file from URL [file:<path-ro-keycloak>/keycloak/template/keycloak-17.0.0/model/jpa/target/test-classes/log4j.properties].
java.io.FileNotFoundException:<path-ro-keycloak>/keycloak/template/keycloak-17.0.0/model/jpa/target/test-classes/log4j.properties (No such file or directory)

$ java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

$ mvn -version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
....

I tried to build keycloak so that I can translate the messages to Traditional Chinese later. Please help. Thanks.

### Version

17

### Expected behavior

build successfully?

### Actual behavior

[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ keycloak-model-jpa ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.keycloak.connections.jpa.util.JpaUtilsTest
log4j:ERROR Could not read configuration file from URL [file:<path-ro-keycloak>/keycloak/template/keycloak-17.0.0/model/jpa/target/test-classes/log4j.properties].
java.io.FileNotFoundException:<path-ro-keycloak>/keycloak/template/keycloak-17.0.0/model/jpa/target/test-classes/log4j.properties (No such file or directory)

### How to Reproduce?

$ wget https://github.com/keycloak/keycloak/archive/refs/tags/17.0.0.tar.gz
$ tar xfz 17.0.0.tar.gz 
$ cd keycloak-17.0.0/
$ mvn clean install

**Comment by stianst** [comment]
Did you try building with JDK 11? We don't actually support JDK 11 yet.

**Comment by ahus1** [comment]
@primillet - I tested this locally with OpenJDK 11 locally and it worked for me. It ran well past the module keycloak-model-jpa . To add to @stianst's comment: Keycloak supports JDK 11, but not JDK 17, I suppose a typo slipped into that comment.

When want to test and update the translation, I recommend you build Keycloak running the tests, or maybe just run them at the very end of your development cycle:

```
mvn clean install -DskipTests
```

**Comment by primillet** [comment]
Thank you for your reply.
I rebuilt keycloak with OpenJDK 11 and it worked:
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  02:04 h
    [INFO] Finished at: 2022-03-10T12:38:36+08:00
    [INFO] ------------------------------------------------------------------------
Building the Keycloak Quarkus distribution also succeeded:
$ mvn -f dist/pom.xml clean install
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  19.765 s
    [INFO] Finished at: 2022-03-10T12:50:44+08:00
    [INFO] ------------------------------------------------------------------------

Unpack the newly built distribution and run it. Keycloak server did start successfully and run.

However, at the early stage of building Keycloak with JDK 11, the same error of log4j.properties being not found did appeared but continued to run. (I saw the error flashing up on the monitor.) That is, JDK 17 stopped the building process at the error point but JDK 11 continued with the error.

The file model/jpa/target/test-classes/log4j.properties  doesn't exist. The only difference is the version of JDK. Is it possible to add the correct file or remove the test to see if JDK 17 can finish the build?

**Comment by ahus1** [comment]
I ran the build with JDK 17 and received the following error message at the end: 

``` 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:22 min
[INFO] Finished at: 2022-03-10T09:55:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.hibernate.orm.tooling:hibernate-enhance-maven-plugin:5.3.20.Final:enhance (default) on project keycloak-model-map-jpa: Unable to enhance class: JpaRoleAttributeEntity.class: Failed to enhance class org.keycloak.models.map.storage.jpa.role.entity.JpaRoleAttributeEntity: Unsupported class file major version 61 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :keycloak-model-map-jpa
```

The error message you reported is also there somewhere in the log, but the log you reported is not the reason for the build to fail. If I understand the log correctly, the current hibernate plugin we're using doesn't support JDK 17, yet. There is already an issue for this here #9993

I will use this issue to get rid of the error message in the log about log4j; there'll be PR for this shortly.

**Comment by primillet** [comment]
Thanks. I will use JDK 11.
