### ISSUE TITLE
Incorrect username logged for federated accounts

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#10616]
### Describe the bug

See https://issues.redhat.com/browse/KEYCLOAK-19908

### Version

17.0.0-SNAPSHOT

**Comment by mposolda** [comment]
Adding this to Keycloak 18 for now. It is not major issue, but requested by customer.

**Comment by rmartinc** [comment]
PR submitted: https://github.com/keycloak/keycloak/pull/10662.
Just setting the ATTEMPTED_USERNAME in the broker login (`IdentityBrokerService` class) to emulate what is done in other places like in the authenticators (Form, X509,...).
Thanks!
