### ISSUE TITLE
/auth/realms/{realm}/protocol/openid-connect/token not working on Quarkus 17.0.0

### ISSUE THREAD

**Issue by jesaavedrav** [keycloak/keycloak#10615]
### Describe the bug

I tried to generate a new token in the Quarkus version and it doesn't work.
My realm's name is "demo"
I get the following:
```json
{
    "error": "RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token"
}
```
Then I installed legacy version (Wildfly 17.0.0) and everything works as expected.

### Version

17.0.0

### Expected behavior

I should be able to get a new token when I post to /auth/realms/{realm}/protocol/openid-connect/token

### Actual behavior

Whenever I post to:
http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
client_id:login
username:test
password:pass
grant_type:password

My realm's name is "demo"

I'm getting the following error

{
    "error": "RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token"
}

**Comment by Wolfsrudel** [comment]
Is your Quarkus installation using the `http-relative-path=/auth` build option? If not, could you test your scenario by removing the `/auth` from your path, please?

**Comment by jesaavedrav** [comment]
That was it! Thank you for your quick response.
Tested both removing the `/auth` part of the url and adding `http-relative-path=/auth` to the keycloak.conf file. 
Works as a charm.
Thank you!!

**Comment by ankushx** [comment]
i m getting {
    "error": "invalid_client",
    "error_description": "Invalid client or Invalid client credentials"
} after http://localhost:8080/realms/wp/protocol/openid-connect/token
