### ISSUE TITLE
Keycloak.js not found 404, when accessing Admin Console

### ISSUE THREAD

**Issue by steveytam** [keycloak/keycloak#10619]
### Describe the bug

Deploy a keycloak with development mode behind an nginx reverse proxy as Kubernetes deployment, /realms and /resources are working fine but I encountered 404 (Keycloak.js not found) when accessing /admin. https://keycloakdomain.com/admin 

### Version

17

### Expected behavior

Keycloak Admin login 

### Actual behavior

Only blank white pages, and browser inspection shows that https://keycloakdomain.com/js/keycloak.js not found

### How to Reproduce?

My nginx configuration:

    location / {
      
        root         /usr/share/nginx/kc;  #serving static files
        }

    location /admin {
        proxy_pass http://192.168.0.10:8080/admin;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }

    location /realms {
        proxy_pass http://192.168.0.10:8080/realms;
        proxy_http_version  1.1;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }

    location /resources {
        proxy_pass http://192.168.0.10:8080/resources;
        proxy_http_version  1.1;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/nginx/ssl/xxxbundle.crt;
    ssl_certificate_key /etc/nginx/ssl/xxx.key;
   }

Keycloak kubernetes configuration (configmap):
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-conf
data:
  JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
  KC_PROXY: "edge"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "xxxx"
  KC_DB_URL: "jdbc:mariadb://xxx:3306/keyloak17"
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "keycloak"
  KC_DB: "mariadb"
  KC_HTTP_RELATIVE_PATH: "/"
  KC_HOSTNAME: "xxx.com"
  KC_HTTP_ENABLED: "true"

**Comment by burkesbi** [comment]
Sounds like I've a near identical configuration and the same problem: `https://keycloak.example.com/auth/js/keycloak.js?version=9njk9` 404's even though everything else works. Even tried the KC_HOSTNAME_ADMIN override that seemed to fix it for other people in the other issues, but no lock. `https://localhost:8080/auth/js/keycloak.js?version=9njk9` downloads fine though if I forward the port.

It seems like the javascript is being served in a different manner that's only accessible via localhost? I haven't been able to track down why though. :(

**Comment by ShivanKKP** [comment]
https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/themes/src/main/resources/theme/base/admin/index.ftl

should     
<script src="${authUrl}/js/keycloak.js?version=${resourceVersion}" type="text/javascript"></script>
be changed to
<script src="/js/keycloak.js?version=${resourceVersion}" type="text/javascript"></script>

**Comment by vmuzikar** [comment]
Thanks for the report! Can you please confirm if the issue still persists with the latest Keycloak version for you? If so, feel free to reopen. We believe it should be fixed now.

**Comment by rmdes** [comment]
Issue still persist for me

context, openshift, keycloak deployed with red hat operator or community operator
can't find the keycloak.js file either

**Comment by jonkoops** [comment]
If you are still experiencing this issue, file a new report with details. Comments on closed issues will not be investigated.
