### ISSUE TITLE
Only half the Users are exported

### ISSUE THREAD

**Issue by lhoe** [keycloak/keycloak#10617]
### Describe the bug

When running an export with a huge dataset, only about half of the users seem to be exported.

### Version

15.1.1 - Jboss

### Expected behavior

The User DB has 2038978 entries, so I would expect this many users to be exported. Which should reflect in the log and in the exported files.

### Actual behavior

Only about half of the users are exported:

The User DB has 2038978 entries ( select count(*) from user_entity; -> 2038978 ).

Keycloak finishes the Export after ~5 hours with the lines:
```
14:13:15,620 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (ServerService Thread Pool -- 68) Users 1010000-1019484 exported
14:13:24,453 INFO  [org.keycloak.services] (ServerService Thread Pool -- 68) KC-SERVICES0035: Export finished successfully
```

The produced Export in the File System reflects the log message: ```grep "username" dump/ -R | wc -l ``` -> 1019499

### How to Reproduce?

startup-config.cli:
```
embed-server --server-config=standalone-ha.xml --std-out=echo
echo Changing transaction default timeout
/subsystem=transactions/:write-attribute(name=default-timeout,value=86400)
echo Done
stop-embedded-server
```

```
podman run -d --name keycloak
-p 8443:8443 -p 7600:7600 -p 4098:4098 --network host
-e KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER} -e KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
-e JAVA_OPTS='-Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=dir -Dkeycloak.migration.realmName=myrealm -Dkeycloak.migration.dir=/tmp/dump -Dkeycloak.migration.usersPerFile=10000 -Dorg.hibernate.flushMode=COMMIT -Djboss.as.management.blocking.timeout=2147483'
-e JDBC_PARAMS='connectTimeout=0'
-v /home/runner/application.keystore:/opt/jboss/keycloak/standalone/configuration/application.keystore:Z
-v /home/runner/dump:/tmp/dump:Z
-v /home/runner/startup-config.cli:/opt/jboss/startup-scripts/my-script.cli:Z
-e DB_VENDOR=postgres -e DB_DATABASE=keycloak -e DB_ADDR=${KEYCLOAK_DATABASE_ADDRESS} -e DB_USER=${KEYCLOAK_DATABASE_USER} -e DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD} -e DB_PORT=1433
quay.io/keycloak/keycloak:15.1.1
```

### Anything else?

We are using org.hibernate.flushMode=COMMIT, otherwise 10k Users take about an hour to export. 
https://lists.jboss.org/pipermail/keycloak-user/2016-January/004637.html

All possible timeouts are increased, since we ran in several timeout issues.

**Comment by hmlnarik** [comment]
@ahus1 Could you please try to reproduce it with the latest Keycloak and triage the issue?

**Comment by sschu** [comment]
Are you maybe using lot of service accounts clients? They also create an internal shadow user that might not be part of the export.

**Comment by ahus1** [comment]
I triaged this issue and it wasn't reproducible in the current Keycloak Nightly. Therefore I recommend closing this issue.

cc: @hmlnarik for the final review before closing it.

Used the following setup: 

1. Preparing Keycloak with the latest 0.9-SNAPSHOT dataset provider
2. Run Keycloak against PostgreSQL
    ```
    bin/kc.sh start-dev --db postgres --db-username=keycloak --db-password=pass
    ```
3. Setup 1000 regular users and 100 service account users in realm-0
    ```
    keycloak-benchmark/dataset/dataset-import.sh -a create-realms -l http://localhost:8080/realms/master/dataset -u 1000
    ```
4. Export the users
    ```
    export KC_DB_PASSWORD=pass
    export KC_DB_USERNAME=keycloak
    bin/kc.sh export --realm realm-0 --dir export --users different_files --users-per-file=100 
    ```
    with log messages:
    ```
    2023-02-14 12:51:11,821 INFO  [org.keycloak.services] (main) KC-SERVICES0034: Export of realm 'realm-0' requested.
    2023-02-14 12:51:14,013 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Realm 'realm-0' - data exported
    2023-02-14 12:51:14,648 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Users 0-99 exported
    2023-02-14 12:51:15,378 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Users 100-199 exported
    ...
    2023-02-14 12:51:18,230 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Users 900-999 exported
    2023-02-14 12:51:18,558 INFO  [org.keycloak.exportimport.dir.DirExportProvider] (main) Users 1000-1099 exported
    2023-02-14 12:51:18,559 INFO  [org.keycloak.services] (main) KC-SERVICES0035: Export finished successfully
    ```
5. Exported users in JSON:
    ```
    $ grep '"username"' realm-0-users-* | wc -l 
    1100
    ```

As the number of exported users matches the users in the database and this is the expected result, I recommend closing this issue.

**Comment by hmlnarik** [comment]
I agree, thank you @ahus1.
