### ISSUE TITLE
Internationalized Domain Names in email address

### ISSUE THREAD

**Issue by petermy** [keycloak/keycloak#10620]
### Describe the bug

End-user with Internationalized Domain Name (IDN) can not register their email address. If the user doesn't have knowledge of Punycode and/or the ACE String they are stuck with a message about email not being valid even if it is a valid email address that they use.

### Version

16.1.1

### Expected behavior

Punycode translation from the UTF-8 representation to ACE String should be invisible to the user. If a user provides a email address with IDN this should be accepted and automatically translated using Punycode and stored as ACE String. The reverse should also be true, when reading email from storage it should be translated to UTF-8 before it is displayed to the user.

### Actual behavior

The end-user must be aware of the domain being an IDN and have knowledge about the Punycode algorithm or the ACE String in order to register a working e-mail address.

### How to Reproduce?

1. Create a new user
2. Set required user actions to update profile
3. Click impersonate user
4. Click login
5. Set email address to an address with UTF-8 in domain name

### Anything else?

[Wikipedia about IDN](https://en.wikipedia.org/wiki/Internationalized_domain_name)
[IDN World report](https://idnworldreport.eu/about/introduction/) contains metrics about the number of IDN registrations etc.

**Comment by stianst** [comment]
Hi, thanks for reporting. I'm changing this to an enhancement request as we don't have support for Internationalized Domain Name in email domain names.

**Comment by DerH4NNES** [comment]
Hi,

is there any timeline for implementation?
@stianst

**Comment by stianst** [comment]
Not anytime soon I'm afraid, unless someone wants to contribute it

**Comment by stianst** [comment]
Might just be down to validation needing updating

**Comment by rmartinc** [comment]
At server side https://github.com/keycloak/keycloak/issues/20878 allowed non-ascii characters for emails. I also think that java/jakarta mail supports internationalized addresses since 1.6.0 (https://github.com/javaee/javamail/releases/tag/JAVAMAIL-1_6_0). So I'm closing this, please re-open if needed.
