### ISSUE TITLE
Disable or enable caching with an ENV var

### ISSUE THREAD

**Issue by eldarj** [keycloak/keycloak#10640]
### Description

For Keycloak running in a container, it would be useful to enable or disable userCache in eg. standalone.xml by just passing an env var, similar to other configuration properties.

```
    <spi name="userCache">
        <provider name="default" enabled="true"/>
    </spi>

    <spi name="realmCache">
        <provider name="default" enabled="true"/>
    </spi>
```

**Comment by DGuhr** [comment]
Hey. Are you using the quarkus based 17 dist? If so, could you try setting `KC_SPI_USER_CACHE_DEFAULT_ENABLED=false`? not sure it works tbh, but should. Would also be interesting to know sth around the usecase of this :)

**Comment by eldarj** [comment]
I'm still on wildfly
regarding the usecase, I'm having issues with the session caching in a keycloak cluster - not being synchronized across multiple nodes, so I'd like to disable it at all as I don't have a lot of requirements for speed, but for stability

Is caching required? Because now I'm reading some weird things like sessions not being persisted in the database but only Infinispan?

**Comment by alokrbl** [comment]
Hi eldarj,

Did you find the way? I also have similar requirements for userCache & realmCache to make it env variable driven.

I have tried many ways (using cli/modify standalone.xml) but no luck. Looks like keycloak-server elements are overridden somewhere. 

Thanks

**Comment by eldarj** [comment]
Unfortunately no, I gave up on this as it wasn't easy do this without digging deep into Keycloak, but I believe it should be possible if the changes were to be made within the keycloak-core itself.

**Comment by shawkins** [comment]
Resolving as out of date as it's based upon the Wildfly distribution.
