### ISSUE TITLE
HS256 algorithm is automatically added to active keys.

### ISSUE THREAD

**Issue by BATON35** [keycloak/keycloak#10659]
### Describe the bug

Default signature algorithm is set to RS256 for realm;
![image](https://user-images.githubusercontent.com/28844037/157412873-2d30015c-041e-48fb-aab1-869be9301dd7.png)
Active allgorithm is set to RS256;
![image](https://user-images.githubusercontent.com/28844037/157413555-b3fd369a-be26-422e-9244-4ede3acb8b40.png)
After sending a token request. (http://localhost:8090/auth/realms/core/protocol/openid-connect/token)
HS256 appears in active algorithms:
![image](https://user-images.githubusercontent.com/28844037/157416768-acf2adf0-c980-4530-93ed-134d2f1d44f1.png)

### Version

16.1.1

### Expected behavior

No HS256 algorithm in active keys.

### Actual behavior

HS256 appears in active algorithms:

### How to Reproduce?

Delete HS256 from active keys. 
Send request for token.

**Comment by stianst** [comment]
HS256 is used for "internal" tokens such as refresh tokens, so this is expected behaviour.

**Comment by lukas0krupa** [comment]
@stianst I think it would be better if for internal tokens would be used key from providers set by administrator. 

Also, it seems like HS256 is vulnerable to brute force attack (as mentioned https://github.com/keycloak/keycloak/issues/13080#issuecomment-1518598938)
