### ISSUE TITLE
Review the fail over logic of the controllers and remove workarounds

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#10658]
### Description

The Keycloak CI got affected by a [race condition in JOSDK](https://github.com/java-operator-sdk/java-operator-sdk/issues/1006).

The [follow-up PR](https://github.com/keycloak/keycloak/pull/10653/files) to fix the CI introduces 3 levels of mitigation:

- Disable `generationAwareEventProcessing` to avoid triggering the bug
- Introduce a fail over reconciliation mechanism to reschedule the execution more aggressively
- Increase some timeouts in the tests

After we integrate a fix for the original issue we should review the mitigations to have a more principled and correct approach to reconciliation.

**Comment by andreaTP** [comment]
Update, the upcoming version of JOSDK + Quarkus extension fixes the problem as demonstrated here: https://github.com/andreaTP/keycloak/actions/runs/1981970092

**Comment by shawkins** [comment]
I don't see any current follow-ups on this that aren't covered by other issues.  As far as I can see the rescheduling of reconciliation is required given that watched secrets may not initially exist.  When they come into existence they will lack the watched label, so either we need to keep retrying reconciliation, watch all secrets, or document that users in this scenario need to add the label on their own.

@andreaTP @vmuzikar is there anything that seems actionable here?

**Comment by csviri** [comment]
Yes this seems to be a very old issue, solved long time ago.

**Comment by shawkins** [comment]
Thanks for the feedback, closing.
