### ISSUE TITLE
kc.sh build option "--help-all" not found

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak#10664]
### Describe the bug

Calling `bin/kc.sh build -help` gives back in last output line the hint about `kc.sh build --help-all`
```
Creates a new and optimized server image.

Usage:

kc.sh build [OPTIONS]

[......]

By doing that you have an additional overhead when the server is starting.

Use 'kc.sh build --help-all' to list all available options, including the start options.
```

But calling `bin/kc.sh build --help-all` gives back:

**Unknown option**: '--help-all'
Possible solutions: --help, --health-enabled
Try 'kc.sh build --help' for more information on the available options.

### Version

17.0.0 and 18.0.0-SNAPSHOT from 08. March

### Expected behavior

The option `--help-all` is doing it's job.

### Actual behavior

Unknown option: '--help-all'

### How to Reproduce?

bin/kc.sh build --help-all

**Comment by DGuhr** [comment]
Hey @psytester thanks for catching. That one slipped through when we changed the build behaviour to only consider build options and not both, build- and runtime config. Removed it in #10681 :)
