### ISSUE TITLE
Doc : Security : brute-force defense is not applied if some KC built-in fonctions or code are not called by custom authenticators

### ISSUE THREAD

**Issue by semangard** [keycloak/keycloak#10671]
### Describe the bug

Hello,
We have developped some custom **required** authenticators used into custon auth flows.
We have configured an anti-brute-force defense into KeyCloak admin console.
We have noticed that this anti-brute-force defense is not applied if our custom authenticators do not call some built-in functions.

Our current code calls _AbstractAuthenticationFlowContext.failureChallenge()_
![image](https://user-images.githubusercontent.com/57065741/157471339-b9ba3ac9-3397-4e9a-9a34-c98008c5aa36.png)

Following built-in functions seems to be also called:
_(based on the KC source code : _https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/directgrant/ValidateUsername.java_)_
![image](https://user-images.githubusercontent.com/57065741/157471916-9fe6501c-7b49-46b7-821f-46cccb86a8b4.png)

### Version
11.0.3

### Expected behavior
KeyCloak Developer guide should ABSOLUTELY :
- mention this requirement (what to do to get anti-brute-force applied)
- and give examples

### Actual behavior
Anti-brute-force is not applied.
KeyCloak Developer guide does not say anything regarding this requirement which is quite CRITICAL in terms of SECURITY.

**Comment by arnou** [comment]
We are facing the same issue using [keycloak login attribute SPI](https://github.com/cnieg/keycloak-login-attribute) when apply security defenses : login with attribute and wrong password does not trigger defenses 

[Issue Plugin 203](https://github.com/cnieg/keycloak-login-attribute/issues/203)
