### ISSUE TITLE
Keycloak Multiple js policy Authorization issue spring boot

### ISSUE THREAD

**Issue by suryans1** [keycloak/keycloak#10676]
### Describe the bug

Keycloak is validating all the Java script policies while doing Authorization for a resource even though the policy was not attached to the resource

### Version

16.1.0

### Expected behavior

Only the policies associated with that resource should be validated

### Actual behavior

Validating all the js policies not associated with the permission created for a resource

### How to Reproduce?

Create spring boot application
Create three resources under the Authorization tab of keycloak
create three different javascript policies under Authorization tab
Create 3 permissions for three resources using the above three js policies
Provide claim information point for the js policies in application.properties

**Comment by pedroigor** [comment]
@suryans1 Could not reproduce the issue using the tests we have.

It is not expected that policies (not only JS) are run when not associated with the resources being requested.

Please, make sure the request being made is not for all resources available on the server (this type of request should evaluate every single permission for every single resource) but for one of them or a subset.
