### ISSUE TITLE
Security : Login timeout seems not to work with custom authenticator and custom auth flow

### ISSUE THREAD

**Issue by semangard** [keycloak/keycloak#10670]
### Describe the bug

Hello,
We have developed custon authenticators to use SMS OTP.
We are using them into a custon auth flow.
We have noticed that the login timeout (which is set by default to 30min) does not work : we are still able to get authenticated even if the auth session should be exhausted.

### Version

11.0.3

### Expected behavior

The auth session should be limited by the _login timeout_ configured (even when custom authenticators + custom auth flow are used).

### Actual behavior

The auth session is not limited by _login timeout_ configured when custom authenticators + custon auth flows are used.

### How to Reproduce?

Define a custom authenticator (e.g. SMS OTP) + custom auth flow and try to get authenticated when the login timeout is exhausted.

### Anything else?

Should custom authenticators call some KC built-in functions to let this feature work ?

**Comment by 9228883664** [comment]
Please check code given in below link. https://github.com/9228883664/keycloak-otp-password-authenticator

You can use keycloak for OTP validation as primary login. Many portal want either user can login with username/password or can do login by entering registered mobile number and enter received OTP on portal to login. Valid token needs to be generated by calling keycloak API. This plugin serve the purpose of both user can login with either password or OTP. OOTB keycloak does not provide this feature, instead it provide 2F OTP authenticator with well-known OTP application.
