### ISSUE TITLE
Operator Example with Keycloak 17.0.0 Quarkus Version

### ISSUE THREAD

**Issue by marziman** [keycloak/keycloak#10693]
### Describe the bug

Hello colleagues,

we had difficulties to find a good example for using the KC Operator with the Quarkus v17.0.0.
Is there any example which is more extensive. We want to use 3 instances and activate the clustering.

Can we already use the Operator with v17.0.0 Quarkus edition? Cause we want to use in for Production now.

The operator works fine with the "17.0.0-legacy" which uses Wildfly. I propose to make a good example to use the Operator with v17.0.0 Quarkus, which was crashing due to healthchecks and other issues.

Thanks!
BR Mehmet

### Version

v17.0.0

### Expected behavior

Operator example with more values, which are possible with the Operator to deploy a larger KC setup.

### Actual behavior

Operator examples only have basic values and it is not really helpful as a starting point, if someone wants to start using the Operator.

**Comment by svilenvul** [comment]
@vmuzikar, can you please guide us? We saw that you are active in the development of the new operator for Keycloak X. 
We saw also that in this repository there is a new Quarkus based operator.
Can we use it at this moment? Can you maybe share with us what is the current state of it?

**Comment by vmuzikar** [comment]
@marziman @svilenvul Thank you for your interest in the Keycloak Operator and Quarkus distribution. The [current operator](https://github.com/keycloak/keycloak-operator) supports only Wildfly distribution and will be deprecated in the future together with it. For the Quarkus distribution we're developing a [new operator](https://github.com/keycloak/keycloak/tree/main/operator) as you correctly noticed. You are most welcome to try it (just follow the README) but we plan to properly release it as a tech preview together with more docs very soon. Stay tuned! 🙂
