### ISSUE TITLE
Keycloak 17 http-relative-path not supported in production mode

### ISSUE THREAD

**Issue by spoore1** [keycloak/keycloak#10699]
### Describe the bug

Attempting to start the version 17 container using the http-relative-path option to add /auth back into the path, I see an `unknown options` error.

I'm trying to start the container like this:

```
podman run --name keycloak -d \
    -p 8080:8080 \
    -p 8443:8443 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=Secret123 \
    -e KC_LOG_LEVEL=debug \
    -e KC_HOSTNAME=$(hostname):8443 \
    -e KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt \
    -e KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key \
    -e KC_HTTPS_TRUST_STORE_FILE=/etc/x509/https/truststore.keystore \
    -e KC_HTTPS_TRUST_STORE_PASSWORD=Secret123 \
    -e KC_HTTP_RELATIVE_PATH=/auth \
    -v /tmp/https/tls.crt:/etc/x509/https/tls.crt \
    -v /tmp/https/tls.key:/etc/x509/https/tls.key \
    -v /tmp/https/truststore.keystore:/etc/x509/https/truststore.keystore \
    quay.io/keycloak/keycloak:$KC_VERSION start --http-relative-path /auth
```

And this is what I see from podman logs:

```
# podman logs keycloak
Unknown options: '--http-relative-path', '/auth'
Possible solutions: --https-certificate-file, --https-cipher-suites, --https-port, --http-port, --https-key-store-type, --http-enabled, --https-client-auth, --http-host, --https-protocols, --https-trust-store-file, --https-trust-store-password, --https-trust-store-type, --https-certificate-key-file, --https-key-store-file, --https-key-store-password
Try 'kc.sh start --help' for more information on the available options.
```

I'm unsure if the intention is to not support this option in production mode.    This seems to work when I use start-dev to run in development mode though.

So, can this be fixed to work in production mode as well? 

### Version

17

### Expected behavior

I expected the --http-relative-path option to work in production mode when running the container with start (instead of start-dev).

### Actual behavior

container did not start and provided error message that the option was not supported.

### How to Reproduce?

Prepare TLS certificates and share them when starting the container as shown in the description.  Be sure to start the container in production mode with start (instead of start-dev).

**Comment by Wolfsrudel** [comment]
And again... It's an `build` option, so you'll first need to use `build` and then `start` or use `start --auto-build`.

**Comment by spoore1** [comment]
Adding --auto-build did the trick.   Thanks!

Does start-dev run build first?  Or it just has all options available by default?   

I missed (or misread) the Server Configuration guide/doc that mentioned first running the build command to set build options.  And since the example in the Migration guide didn't mention running build (or auto-build) with start-dev, I thought the option would be available with start for production mode as well.

It may be helpful to others like myself running the new version for the first time to mention this in the Migration guide.

Thanks again for you help

**Comment by DGuhr** [comment]
@spoore1 yes, start-dev is effectively detecting if a build is needed and starts it afterwards. Glad it worked out for you. Closing here :)

**Comment by spoore1** [comment]
@DGuhr Should I open a separate ticket for the doc update request?

I still think there should be something in the Migration guide clarifying that you have to run the build step separately or use --auto-build (at least with the container).  A separate example in the "Default context path changed" or examples in the "Quarkus is not an application server" sections might help.

I'm willing to submit a PR if someone points me to the proper doc repo to use for that.

Thanks

**Comment by harithamc** [comment]
Is this issue still exists in KC21 version?
