### ISSUE TITLE
Mismatch between RESTEasy dependency on Operator and Quarkus distribution

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#10702]
### Description

I noticed that we have a mismatch between the versions used on the Operator and Quarkus. It would be nice if we manage to keep those versions aligned, and also upgrade those versions at the main POM file if possible. Meanwhile, the short-term solution is to update the RESTEasy version in the Operator.

```
operator/pom.xml
23:        <resteasy.version>4.7.4.Final</resteasy.version>

quarkus/pom.xml
40:        <resteasy.version>4.7.5.Final</resteasy.version>

```

### Motivation

Keep dependencies aligned.

**Comment by andreaTP** [comment]
@abstractj we should discuss about this issue, the Quarkus Operator SDK is not released at the same cadence as Quarkus releases.
ATM It's almost by chance (I upgraded versions a few days ago in the operator) that we happen to use almost the same versions, as you noticed.

Cc. @metacosm

**Comment by abstractj** [comment]
@andreaTP interesting (I wasn't aware about that), and thanks for clarifying Andrea. If you would like to, we can close this issue or put it on hold. Whatever works best for the team, I'm happy.
