### ISSUE TITLE
Keycloak quarkus smallrye liveness probe:  already completed error.

### ISSUE THREAD

**Issue by rvanderboom** [keycloak/keycloak#10718]
### Describe the bug

We finally have keycloak 17.0.0 quarkus running with all our customized code (so migrated from wildfly to quarkus)..

We only do see 1 strange issue, the liveness probe sometimes (few times a hour) gives an error, but it doesn't seem to effect the pods running..

Why do we get this error:

<img width="2260" alt="Screenshot 2022-03-11 at 17 03 40" src="https://user-images.githubusercontent.com/28537513/157904077-43a18ea0-14ca-4035-b9ad-7198f975fd64.png">

### Version

17.0.0 (quarkus)

### Expected behavior

The liveness probe shouldn't log above error. We don't now if its only an error that doesn't mean anything or does it indicate a real issue ?
we also have de /ready probe, we never have errors from this one (which actually does more then /live)..

### Actual behavior

We have to keycloak pods running in kubernetes (DNS PING), everyting runs well except above error..
The pods do stay alive..

### How to Reproduce?

Hope it can be reproduced with all basics as is keycloak 17 - quarkus on kubernetes , with min. 2 pods.

### Anything else?

no

**Comment by vmuzikar** [comment]
@rvanderboom Thanks for the report! Can you please confirm if the issue still persists with the latest Keycloak version for you? If so, feel free to reopen.
