### ISSUE TITLE
Rollup.js complains about the use of eval in one of keycloak.js's dependencies

### ISSUE THREAD

**Issue by hornet-9** [keycloak/keycloak#10710]
### Describe the bug

When performing a build with [Rollup](https://github.com/rollup/rollup) of a project containing `keycloak-js`, you get the following message: `Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification`.

eval is used in the library [js-sha256 ](https://github.com/emn178/js-sha256) which is a dependency of keycloak.js. There are numerous issues that have been opened about this, some open (like [this](https://github.com/emn178/js-sha256/issues/18)), some closed without resolution. There have been no updates to the package since 2017.

Is there an alternative that keycloak-js can use instead?

### Version

17.0.0

### Expected behavior

Rollup can do a build without an eval warning.

### How to Reproduce?

I actually use [Vite](https://github.com/vitejs/vite), which uses Rollup.js under the hood for production builds. So either you can install Rollup, import keycloak-js and build, or in a Vite project import keycloak-js and run `npm run build`.

**Comment by jonkoops** [comment]
I'd love to remove this dependency, however we are currently shipping this for maximum backwards compatibility with older browsers such as Internet Explorer. That said, I think it might be time to re-evaluate this position now that this browser is in the grave.

Preferably I'd like to bump the minimum target for JavaScript syntax to ES2015 as well and focus on more evergreen browsers.

**Comment by jonkoops** [comment]
Took a quick look and making this change would be breaking as it would require part of the public API interface to be modified. Since the Web Crypto API is Promise based it would require `createLoginUrl()` to return a Promise as well, breaking existing expectations.

**Comment by juhoha** [comment]
> I'd love to remove this dependency, however we are currently shipping this for maximum backwards compatibility with older browsers such as Internet Explorer. That said, I think it might be time to re-evaluate this position now that this browser is in the grave.

From a glance it looks like there's a polyfill available, might ease the pain! Seems like js-sha256 hasn't been updated in 5 years and this same issue has been around for 4: https://github.com/emn178/js-sha256/issues/18  

Workaround: these don't seem to cause any actual trouble (YMMV), so just suppressed these. Vite conf:

```es6
export default defineConfig({
  build: {
    rollupOptions: {
      onwarn: ({ loc }) => {
        if (loc?.file?.match(/js-sha256\/src\/sha256.js$/))
            return;
      } 
  }
});
```

**Comment by schmidtk** [comment]
@juhoha Have you had success with your workaround in a production build? In a production build I'm getting an actual error:
```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/usr/src/app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at eval (eval at nodeWrap (file:///usr/src/app/server/chunks/index4-520a3e48.js:243:19), <anonymous>:1:1)
    at nodeWrap (file:///usr/src/app/server/chunks/index4-520a3e48.js:243:19)
    ...
```

I can work around this by either ensuring the package isn't included in server code, or by replacing `js-sha256` entirely and using npm workspaces to make sure my local version of it is linked during `npm install`.

Both of these are ugly, and I think an ideal solution would be replacing this package in `keycloak-js` given it's no longer supported and native replacements are present. I understand this is a breaking API change, but long term would be for the best.

**Comment by jonkoops** [comment]
This issue has been resolved by upgrading the `js-sha256` dependency to the latest version, which removes the use of `eval()`.
