### ISSUE TITLE
Oracle database tests failing in server pipeline

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#10721]
### Describe the bug

Run # 1311 of the server pipeline revealed some failures on Oracle when running the `db_tests`. Most them fail with a socket read timeout, so they might be just transient failures. This is the list of tests that failed only on Oracle (succeeded on all other DBs):

```
org.keycloak.testsuite.adapter.servlet.BrokerLinkAndTokenExchangeTest.testAccountLink
org.keycloak.testsuite.adapter.servlet.BrokerLinkAndTokenExchangeTest.testAccountLinkNoTokenStore
org.keycloak.testsuite.adapter.servlet.ClientInitiatedAccountLinkTest.testLinkOnlyProvider
org.keycloak.testsuite.adapter.servlet.ClientInitiatedAccountLinkTest.testAccountLinkingExpired
org.keycloak.testsuite.adapter.servlet.ClientInitiatedAccountLinkTest.testAccountLink
org.keycloak.testsuite.adapter.servlet.ClientInitiatedAccountLinkTest.testErrorConditions
org.keycloak.testsuite.admin.client.ClientScopeTest.testCreateNonDynamicScopeWithFeatureEnabled
org.keycloak.testsuite.broker.AccountLinkTest.testAccountLinkWithUserStorageProvider
org.keycloak.testsuite.broker.KcOidcFirstBrokerLoginTest.testUserExistsFirstBrokerLoginFlowUpdateProfileOff
org.keycloak.testsuite.oauth.BackchannelLogoutTest.postBackchannelLogoutNestedBrokeringRevokeOfflineSessionsWithoutActiveUserSession
org.keycloak.testsuite.oauth.BackchannelLogoutTest.postBackchannelLogoutNestedBrokeringRevokeOfflineSessions
```

It might be good to check these tests on Oracle. Timeout issues are the cause for the majority of the issues but one of them has caught my attention:

```
org.keycloak.testsuite.admin.client.ClientScopeTest.testCreateNonDynamicScopeWithFeatureEnabled
```

Failed with 
```
java.lang.AssertionError: expected:<> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.keycloak.testsuite.admin.client.ClientScopeTest.testCreateNonDynamicScopeWithFeatureEnabled(ClientScopeTest.java:701)
```

This test is setting an empty attribute in the client scope and is then trying to verify that the created scope contains the empty attribute. However, Oracle returns NULL instead of empty strings, so either the test needs to be adjusted to set a non-empty attribute or it has to be marked not to run with Oracle.

### Version

17.0.0

### Expected behavior

All the tests in the list should succeed in Oracle.

**Comment by hmlnarik** [comment]
@sguilhen Is this issue still valid?

**Comment by sguilhen** [comment]
Fixed in https://github.com/keycloak/keycloak/commit/c18a682f500f18fb7586ae63a2fc5a57c83c59b0
