### ISSUE TITLE
Keycloak 17 (Quarkus): no suitable driver found for jdbc:postgresql

### ISSUE THREAD

**Issue by Nokorbis** [keycloak/keycloak#10722]
### Describe the bug

I'm trying to run the container keycloak with a postgresql database but the server doesn't start because the driver is not found.
I've checked previously created tickets but I do have the ENV KC_DB=postgres line and still does not work

### Version

17.0.0

### Expected behavior

Working postgresql driver

### Actual behavior

2022-03-11 20:13:37,395 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://database:5432/keycloak

### How to Reproduce?

Following the "tutorial" to build and launch an optimized container on https://www.keycloak.org/server/containers
I first tried with `docker compose` but, even with the simple `docker build` and `docker run` it fails.
So I copy this in a Dockerfile : 
```
FROM quay.io/keycloak/keycloak-x:latest as builder

ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak-x:latest
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=change_me
# change these values to point to a running postgres instance
ENV KC_DB_URL=jdbc:postgresql://database:5432/keycloak
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=keycloak
ENV KC_HOSTNAME=localhost:8443
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```
Then run `docker build . -t prebuilt-keycloak`
and then `docker run -p 8443:8443 prebuilt_keycloak`

### Anything else?

As of the time of writing, the "latest" is "17.0.0"

I also tried adding --db=postgres after RUN /opt/keycloak/bin/kc.sh build and wasn't more successful

Thank you

**Comment by giacomoa** [comment]
It seems to be an error in documentation you linked: quay.io/keycloak/**keycloak-x**:latest should be quay.io/keycloak/**keycloak**:latest
You can just modify your Dockerfile

**Comment by Nokorbis** [comment]
Good catch ! 
It does work now. Thank you very much ! 
Should I close the issue or wait until the documentation is updated ?

**Comment by DGuhr** [comment]
Hey. The guide is already updated here https://raw.githubusercontent.com/keycloak/keycloak/main/docs/guides/src/main/server/containers.adoc and will be updated on the page as soon as a new version is out. Sadly its tied to a version release atm. Nevertheless glad this is solved. Closing here for now :)

**Comment by jlpettersson** [comment]
I use image `quay.io/keycloak/keycloak:17.0.1`
but I get the same error in the log.

I start keycloak in production mode using the `start` parameter.
When I add the flag `--db=postgres` it prints this errors in the log:

```
Unknown option: '--db=postgres'
```

If I start without the `--db=postgres` flag, I get this error message in the log:

```
2022-04-04 12:53:34,726 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for postgres://keycloak:mypassword@127.0.0.1:5432/keycloak?sslmode=disable&max_conns=20&max_idle_conns=4
2022-04-04 12:53:34,728 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for postgres://keycloak:mypassword@127.0.0.1:5432/keycloak?sslmode=disable&max_conns=20&max_idle_conns=4
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
```

Is there any workarounds? or isn't PostgreSQL supported anymore?

**Comment by sdenovan** [comment]
You can use the upstream image directly by passing these arguments to the container:
start --auto-build --db=postgres

**Comment by mannp** [comment]
> You can use the upstream image directly by passing these arguments to the container: `start --auto-build --db=postgres`

This snippet saved a wasted day, thank you :) now have v16.1.1 migrated to 18.0.0 👍🏻

**Comment by Aeolun** [comment]
Am I the only one that thinks that trying to start Keycloak from just the image is like playing musical chairs with parameters?

**Comment by saisiva249** [comment]
Hi iam having the issue in the configuration i, i tried to use the same configuration that was mentioned.
`FROM quay.io/keycloak/keycloak:latest as builder

ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
# change these values to point to a running postgres instance
ENV KC_DB_URL=jdbc:postgresql://mypostgres:5432/keycloak
ENV KC_DB_USERNAME=admin
ENV KC_DB_PASSWORD=admin
ENV KC_HOSTNAME=localhost:8443
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]`

and my postgre docker looks like this
`FROM postgres:14-alpine3.16
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin
ENV POSTGRES_DB keycloak`

and my docker compose is 
`version: '3.7'

networks:
  mydocker:
    driver: bridge

volumes:
  postgres_data:
      name: pgdata

services:
  mypostgres:
      container_name: mypostgres
      image: mypostgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
      - 5442:5432
      networks:
        - mydocker

  keycloak:
    depends_on:
      - mypostgres
    image: mykeycloak
    container_name: keycloak
    links:
      - mypostgres
    ports:
      - "8443:8443"
    networks:
      - mydocker
`

with this iam getting the following error

`URL format error; must be "jdbc:h2:{ {.|mem:}[name] | [file:]fileName | {tcp|ssl}:[//]server[:port][,server2[:port]]/name }[;key=value...]" but is "jdbc:postgresql://mypostgres:5432/keycloak" [90046-214]`

 if this is already has a solution can you please let me know what mistake iam doing
