### ISSUE TITLE
Keycloak to fire an event upon realm creation/deletion

### ISSUE THREAD

**Issue by waglik** [keycloak/keycloak#10733]
### Description

Currently it seems that Keycloak is not logging realm creation or deletion. Would it be possible to have this feature, either in logs or via event so we can handle it via EventListener? 

I even find a post from 2019 on SO about somebody forking the code to achieve it so perhaps there is more people interested in this feature.

https://stackoverflow.com/questions/54766636/keycloak-event-listener-provider-not-firing-new-realm-creation-event

thanks
Mateusz

### Motivation

It would improve very much improve debugging but also could be used for alerts, SIEM or non repudiation situations.

**Comment by cpesch** [comment]
@waglik @tsaarni  I'd be interested in listening to Realm creation and deletion events  – whats missing to drive this forwards?

**Comment by tsaarni** [comment]
> whats missing to drive this forwards?

@cpesch From my perspective, I'm blocked by not having reviews for PR #10831 but the maintainers are quite busy and might not have time to review all PRs.
