### ISSUE TITLE
Use SchemaSwap instead of shell script for Realm CRD generatio

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10736]
* Remove the [current workaround](https://github.com/keycloak/keycloak/blob/ad865e75c14f048e2de6748bab6af6c3b495de33/operator/patch-sources.sh) and rely purely on Fabric8 generator SchemaSwap.

**Comment by vmuzikar** [comment]
Steps:
* Upgrade to Fabric8 5.12.2
* Remove the current implementation that is using [Maven](https://github.com/keycloak/keycloak/blob/82fbe6c0d55da9fbbe2556907ad1ad40bcffccbb/operator/pom.xml#L213-L247) and a [Bash script](https://github.com/keycloak/keycloak/blob/main/operator/patch-sources.sh) to add annotations.
* Add `keycloak-core` dependency.
* Add [SchemaSwap](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CRD-generator.md#iofabric8crdgeneratorannotationschemaswap) annotations to [`KeycloakRealmImportSpec`](https://github.com/keycloak/keycloak/blob/main/operator/src/main/java/org/keycloak/operator/v2alpha1/crds/KeycloakRealmImportSpec.java).

**Comment by andreaTP** [comment]
Blocked by the fact that `SchemaSwap` happens to not have the `Repeatable` annotation 😞

**Comment by andreaTP** [comment]
Some work in progress in the area: https://github.com/fabric8io/kubernetes-client/pull/4354
