### ISSUE TITLE
[SPIKE] Enhance operator testsuite run times

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10731]
Figure out how to optimize the testsuite as it takes too much time right now.

**Comment by vmuzikar** [comment]
One idea to investigate was to use a custom KC image for majority of the tests. This would allow us to skip the costly re-augmentation.

**Comment by vmuzikar** [comment]
Another possibility to explore is [Testkube](https://testkube.io/). We could leverage the research that QE did in this area (CC: @nehachopra27).

**Comment by vmuzikar** [comment]
@shawkins +1 for using a custom image (when testing the default image, re-augmentation or build time options is not relevant in given test case).

Could you please elaborate a bit how this is related to https://github.com/keycloak/keycloak/discussions/21008?

**Comment by shawkins** [comment]
> Could you please elaborate a bit how this is related to https://github.com/keycloak/keycloak/discussions/21008?

Sorry, wrong link, should be #21111

**Comment by shawkins** [comment]
Updated the timings with a couple more runs.  Also tried the custom image from build-testing-docker-images with probes that had very little delay and got 50s.  So at least on my system that is saving approximately 9 seconds per pod start.  Then using fake deployments saves another 5 seconds per pod start.
