### ISSUE TITLE
the users are not importet to keycloak 17 from keycloak 12

### ISSUE THREAD

**Issue by mazbeh** [keycloak/keycloak#10751]
### Describe the bug

Hello every body,

i have updated keycloak from version 12 to version 17. Every thing works fine except the list of the users under Users in Realm Master. when i click on the users tab every thing hangs !
i hope that you can see the screenshot that i added here.

Could someone please help me, thanks !!!

![Unbenannt](https://user-images.githubusercontent.com/85217428/158362866-3d1149f6-52d6-423f-8602-e8d6bd2697f4.png)

### Version

17

### Expected behavior

to see the list of the users from keycloak 12 in keycloak 17 after updating.

**Comment by ssilvert** [comment]
@stianst This is probably an issue with migration from version 12 to version 17.  Maybe we should add a label for migration so someone can be in charge of that?

**Comment by vramik** [comment]
Hello @mazbeh, thanks you for reporting the issue. Could you please provide more information how did you performed the upgrade? Are you seeing the issue after importing the users from older version? Could you provide a sample json what are you importing, it'd help to reproduce the issue. Thank you.

**Comment by mazbeh** [comment]
Hello @vramik . Thanks for the replying. I found that the problem was not with keycloak but with the browser version( firfox- unfortunatly i dont the version in mind anymore ). I updated the brwoser and it works fine , thanks !

**Comment by vramik** [comment]
Thank you @mazbeh for the update. I'm glad it is working fine for you!
