### ISSUE TITLE
Automatic scan Keycloak docker image for vulnerabilities

### ISSUE THREAD

**Issue by eabykov** [keycloak/keycloak#10764]
### Description

Please use [trivy](https://github.com/aquasecurity/trivy) scaning in the GitHub Actions [example](https://github.com/eabykov/keycloak-compose/blob/main/.github/workflows/trivy.yml)

### Motivation

Automatic generation of a list of known vulnerabilities

### Details

Example of [scanning the Keycloak image 17.0.0](https://github.com/eabykov/keycloak-compose/security/code-scanning) for vulnerabilities.

**Comment by abstractj** [comment]
@eabykov you are welcome to review https://github.com/keycloak/keycloak/pull/10777
