### ISSUE TITLE
TLS config guide

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10789]

**Comment by andreaTP** [comment]
We have integrated a section on how to set up TLS in [here](https://github.com/keycloak/keycloak/pull/11029/files#diff-803e0af91cd24ac7358761e50f8492cdd039d0d77477cabad318540fc35b9d85R81), not sure if we should we still have a separate section for this?

**Comment by vmuzikar** [comment]
We don't. At least not now.
