### ISSUE TITLE
keycloak.js fails to load from the UI when behind a reverse proxy and KC_PROXY = `edge`

### ISSUE THREAD

**Issue by dc-pm** [keycloak/keycloak#10817]
### Describe the bug

In the frontend authUrl and authServerUrl should respect the setting of [KC_PROXY](https://www.keycloak.org/server/reverseproxy) to `edge` mode and should probably use the X-Forwarded-Proto instead of the request protocol to construct the url for frontend requests.

This initial result of this is in the templates the url for the keycloak.js resource is incorrect, although the issues are probably bigger as the url is also used for other js invoked api calls looking at the code.

### Version

17.0.0

### Expected behavior

```html
<script type="text/javascript">
--
  | var authServerUrl = 'https://...';
  | var authUrl = 'https://....';
...
```

### Actual behavior

```html
<script type="text/javascript">
--
  | var authServerUrl = 'http://...';
  | var authUrl = 'http://....';
...
```

Only setting KC_PROXY to `reencrypt` and communicating over https behind the proxy server resolves the issue and correctly sets the frontend Urls.

### How to Reproduce?

Run a proxy server with SSL termination and set the KC_PROXY option to 'edge'.

Load the `/admin/master/console/` html file and you will see the authUrl and authServerUrl set to `http://{hostname}` and not `https://{hostname}`. The browser will then try to connect on this port and fail.

For reference this was the NGINX configuration used:

```
    server {
        listen 443 ssl http2;
        server_name login.test.test;
        server_tokens off;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        ssl_dhparam /etc/nginx/ssl-dhparams.pem;

        location / {
            set $upstream http://keycloak:8080;
            proxy_pass  $upstream;
            proxy_set_header    Host                $http_host;
            proxy_set_header    X-Real-IP           $remote_addr;
            proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto   $http_x_forwarded_proto;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
```

### Anything else?

Setting KC_HOSTNAME_SCRICT_HTTPS: true also didn't help. (not sure if this option is correct or used)

**Comment by pedroigor** [comment]
@dc-pm I've a similar setup using HAProxy. For me, the URLs are built correctly based on the X-Forward-* headers set by the proxy.

Changing the values of these headers in the proxy are reflected on the page too. For instance, changing from `https` to `http` scheme. 

Any idea what I might be missing?

Here is my HAProxy configuration:

```
#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

    # utilize system-wide crypto-policies
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-server-ciphers PROFILE=SYSTEM

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

frontend mykeycloakedge
    # Copy the haproxy.crt.pem file to /etc/haproxy
    bind *:443 ssl crt /etc/haproxy/haproxy.crt.pem
    use_backend mykeycloakedge

backend mykeycloakedge
    mode http
    stats enable
    stats uri /haproxy?status
    option httpchk GET / HTTP/1.1\r\nHost:\ localhost
    option forwardfor
    http-request add-header X-Forwarded-Proto https
    http-request add-header X-Forwarded-Port 443
    http-request redirect scheme https unless { ssl_fc }
    cookie KC_ROUTE insert indirect nocache
    balance roundrobin
    server kc1 127.0.0.1:8080 cookie kc1
```

**Comment by T0mWz** [comment]
Have setup Keycloak 17 in Kubernetes and encounter the same behavior.
Javascript content is not loaded, where it tries to reach it via HTTP, what is blocked due to `mixed-content`.
Have added some environment variable, but that doesn't seem to help.
```
        - name: KC_PROXY
          value: "edge"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: MY_KC_URL
          value: "https://my-keycloak-environment"
```

**Comment by Thirsa** [comment]
> @T0mWz @dc-pm Could you please try the 17.0.1 release?

@pedroigor I've tried that just now, but with the same result...

I'm following the installation guide on https://www.keycloak.org/getting-started/getting-started-kube and am using this file https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes-examples/keycloak.yaml as is. I see that the "start-dev" command is passed. This should not matter right?

The landing page works, but when we try to access the admin console the browser console logs:
Mixed Content: The page at 'https://DOMAIN-REDACTED/admin/master/console/' was loaded over HTTPS, but requested an insecure script 'http://DOMAIN-REDACTED/js/keycloak.js?version=il7n7'. This request has been blocked; the content must be served over HTTPS.

All other script and stylesheet requests at this point give 200 status.
In our setup haproxy does TLS termination and passes HTTP to the k8s ingress controller.
(Loading it over HTTPS works fine for the js file)

Viewing page source does show me that all other resources are loaded from /resources/ except for the keycloak.js:
>
<! -- Libraries not managed by yarn -->
"<script src="/resources/il7n7/common/keycloak/lib/ui-ace/min/ace.js"></script>"
"<script src="/resources/il7n7/common/keycloak/lib/ui-ace/ui-ace.min.js"></script>"
"<script src="http://DOMAIN_REDACTED/js/keycloak.js?version=il7n7" type="text/javascript"></script>"
"<script src="/resources/il7n7/admin/keycloak/js/app.js" type="text/javascript"></script>"

**Comment by gitdode** [comment]
Strange enough, this works fine for me with 17.0.0, while it doesn't with 17.0.1.

Keycloak is running in RKE2 (nginx-ingress-controller) behind an nginx reverse proxy terminating TLS.

With 17.0.1, I get:

    var authServerUrl = 'https://keycloak.domain.tld/auth';
    var authUrl = 'http://keycloak.domain.tld/auth';

and 

    <script src="http://keycloak.domain.tld/auth/js/keycloak.js?version=ggwbl" type="text/javascript"></script>

And really, it works fine with 17.0.0.

**Comment by pedroigor** [comment]
>The landing page works, but when we try to access the admin console the browser console logs:
Mixed Content: The page at 'https://domain-redacted/admin/master/console/' was loaded over HTTPS, but requested an insecure script 'http://domain-redacted/js/keycloak.js?version=il7n7'. This request has been blocked; the content must be served over HTTPS.

Mixed-content is expected if you have `hostname-strict-https=false` and you do not specify the proxy option. The `X-Forward-*` headers are ignored and pages might end-up fetching resources using HTTP.

**Comment by ytrinh** [comment]
Adding this env "PROXY_ADDRESS_FORWARDING" to "true" solved my issue for 15.0.2. 

https://hub.docker.com/r/jboss/keycloak/

**Comment by dc-pm** [comment]
@Thirsa I just tried and with the v17.0.1 release everything seems to be working for me

**Comment by Thirsa** [comment]
> @Thirsa I just tried and with the v17.0.1 release everything seems to be working for me

Cool. You are using these files too? https://github.com/keycloak/keycloak-quickstarts/tree/latest/kubernetes-examples
Did you specify additional ENVs in them? I removed the tls config lines from ingress. You also have a proxy that does tls termination in front of k8s?

I'm happy to try with "hostname-strict-https=true", but I have a hard time understanding where/ how to configure this feedback... 

> 
> Mixed-content is expected if you have `hostname-strict-https=false` and you do not specify the proxy option. The `X-Forward-*` headers are ignored and pages might end up fetching resources using HTTP because the headers are ignored by the server.

**Comment by meronz** [comment]
Problem is not only related to the protocol. Should the url be relative instead of being absolute?
![image](https://user-images.githubusercontent.com/10725286/159902977-483f25e2-bed1-44b1-bdf4-d0c94f5ecec1.png)

**Comment by gitdode** [comment]
Now tried with

        - --hostname
        - keycloak.domain.tld
        - --hostname-strict-https
        - "true"

and of course

        - name: KC_PROXY
          value: edge

with 17.0.1 and always get `authServerUrl = 'https'` but `authUrl = 'http'` and the link to keycloak.js is `http`.

With 17.0.0 it just works.

**Comment by Thirsa** [comment]
@gitdode 
> With 17.0.0 it just works.

I confirm! 
with this configuration in the deployment file it works:
`        image: quay.io/keycloak/keycloak:17.0.0
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "somepass"
        - name: KC_PROXY
          value: "edge"
        - name: KC_HOSTNAME
          value: "keycloak.domain.tld"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "true"`

You just have to know to set those additional ENVs I guess. Though I can't find the KC_HOSTNAME_STRICT_HTTPS here https://www.keycloak.org/server/all-config ...

Thank you! 💪

**Comment by T0mWz** [comment]
This configuration of @Thirsa works! 🎉 
> @gitdode
> 
> > With 17.0.0 it just works.
> 
> I confirm!
> 
> with this configuration in the deployment file it works: image: quay.io/keycloak/keycloak:17.0.0 args: ["start-dev"] env: - name: KEYCLOAK_ADMIN value: "admin" - name: KEYCLOAK_ADMIN_PASSWORD value: "somepass" - name: KC_PROXY value: "edge" - name: KC_HOSTNAME value: "keycloak.domain.tld" - name: KC_HOSTNAME_STRICT_HTTPS value: "true"
> 
> You just have to know to set those additional ENVs I guess. Though I can't find the KC_HOSTNAME_STRICT_HTTPS here https://www.keycloak.org/server/all-config ...
> 
> Thank you! 💪

However, with 17.0.1, I run against the same issue. the keycloak.js is served (hard) via HTTP, where this results in some issues where we have HSTS applied. 

Thanks for all your help!

**Comment by gitdode** [comment]
AFAIK when using "start-dev", some (security relevant) features like strict hostname checking are disabled which are otherwise enabled by default.
[Running Keycloak in a container](https://www.keycloak.org/server/containers) is particularly interesting I think.
Personally I feel more comfortable using "auto-build" for development than "start-dev":

    spec:
      containers:
      - args:
        - start
        - --auto-build
        - --hostname
        - keycloak.domain.tld

**Comment by kenwark** [comment]
I have run into the same problem trying to set up Keycloak behind nginx with TLS terminated in nginx:

I have `proxy=edge` in keycloak.conf.

My nginx settings:

    server {
        listen       80;
        listen       [::]:80;
        server_name  _;

        proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        location / {
            proxy_pass http://127.0.0.1:8080;
        }
     }

With Keycloak 17.0.1, the links in the admin console are `http://<domain>:443/...`.

With Keycloak 17.0.0, the links are correct.

**Comment by eucleciojosias** [comment]
The fix is [here](https://github.com/keycloak/keycloak/pull/11109), but it was not released yet :(
