### ISSUE TITLE
Message properties aren't getting parsed in UTF-8

### ISSUE THREAD

**Issue by eldarj** [keycloak/keycloak#10821]
### Describe the bug

Rendering messages from property files, within Freemarker templates with:
```
${msg('...')}
```

doesn't happen in UTF-8, so for special characters, output will be '??????????????????????'.

How come UTF-8 isn't default?

### Version

15.0.2

### Expected behavior

Привет in message property file, gets shown as Привет in Freemarker template

### Actual behavior

Привет in message property file, gets shown as ???????????????? in Freemarker template

**Comment by stianst** [comment]
If you want to use utf-8 encoding in message bundles just add the header like this:
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/login/messages/messages_lv.properties#L1

**Comment by eldarj** [comment]
This solved it, thank you

**Comment by AlejandroGarciaMaya** [comment]
Sweet, thank you!

**Comment by jonkoops** [comment]
Just FYI,  this behavior will be likely changed soon (see #21755), starting with Keycloak 23 all of these files will be treated as UTF-8 by default.

**Comment by czosel** [comment]
For anyone looking for the fix for Keycloak 22 or before (since the file linked by @stianst has been updated) - 
prepend `# encoding: UTF-8` to your message property file, e.g.:
```
# encoding: UTF-8

yourMessage=...
```

**Comment by dasler-fw** [comment]
Keycloak 23.0.3

`# encoding UTF-8`

setting the header does not work.
