### ISSUE TITLE
Maven builds doesn't recognize JDK 1.7 API violations

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#10842]
### Description

The Maven builds runs with JDK 11, and some modules still claim want to bei JDK 7 compatible. 

By using JDK 11 to build, it misses when Java adds a new API in JDK 8-11: The code still compiles, still it will fail when running on JDK 7. 

To prevent this, Keycloak should apply a tool like https://www.mojohaus.org/animal-sniffer/ in its build process. The build will then fail when an API is used that is too recent.

At the same time: The Keycloak documentation states OpenJDK 8 should be used, and Maven compiles to 1.7. Strange.

### Motivation

Prevent a situation as it happend in #10840.

**Comment by DGuhr** [comment]
Hey,
as an alternative approach that doesn't add another tool we don't necessarily need, I'd say we update https://github.com/keycloak/keycloak/blob/091b1472ceffa1e963d08b4ff1c89072e7b9130b/docs/building.md to state "JDK11+" instead of JDK8+ instead.
Both, wildfly and quarkus can be built using jdk11. Quarkus actually needs at least JDK11, so JDK8+ is not entirely true for every runtime.
As https://www.mojohaus.org/animal-sniffer/ states: "Please note this plugin is now in maintenance level as the exact same feature can be now easily achieved using the --release flag from Javac see http://openjdk.java.net/jeps/247 " we could then take advantage of the --release flag that was introduced from Java9 on.
wdyt?

(crossposted from keycloak-dev)

**Comment by ahus1** [comment]
@DGuhr - yes, that would be possible. I'll give it a try once someone approves the change that "it can only be built with JDK 11".

**Comment by ahus1** [comment]
BTW for anyone watching this issue: There's now a PR #10974 that implements AnimalSniffer and that would still allow the modules except Operator and Quarkus to be built using JDK 8.

**Comment by mhajas** [comment]
FYI: It seems there is another occurrence of this: #11091

**Comment by stianst** [comment]
Doesn't this problem go away when we get rid of JDK 8 support? For the server-side stuff that is already in progress, as the Quarkus distribution doesn't support JDK 8. For adapters it will also go away soon enough. So question is it really worth doing anything about this in the interim as we've lived with this issue for many years without it being a big issue.

**Comment by mhajas** [comment]
@stianst This is more about adapters support for JDK 7. Based on [this](https://www.keycloak.org/2022/02/adapter-deprecation) we still support the SAML adapter. Therefore, the question relevant to this issue is whether we want to have support for the SAML adapter for JDK 7. If not, we can switch all modules that are currently set to JDK 7 to JDK 8 and we can close this.

**Comment by stianst** [comment]
We don't need to support JDK 7 anymore, as that's only for EAP 6.4, which we're planning on removing in the community now. It'll be supported in RH-SSO 7.x only.

**Comment by ahus1** [comment]
@stianst - this PR might be useful for those maintaining 7.x. 

Once the community project targets at least JDK 8 everywhere, this issue and the PR are obsolete.

**Comment by stianst** [comment]
Thanks, we can bump the targeted JDK versions everywhere to 8+ already now. We'll also remove a bunch of adapters, including EAP 6 soon (as this is planned to be excluded from KC 19 release).

**Comment by stianst** [comment]
https://github.com/keycloak/keycloak/pull/11607

**Comment by ahus1** [comment]
Thank you for that PR. Once it is merged, I'll have a look that we don't introduce for example JDK 11 feature when building JDK 11. But that wouldn't require Animal sniffer, as for that we could rely on javac release features AFAIK.

**Comment by ahus1** [comment]
There is now PR #11991 that uses the functionality available in JDK 9+ to prevent error like this. Please review that PR so it can be merged. Thanks!
