### ISSUE TITLE
Kerberos auth fails when access to keytab is via a group with GID != UID

### ISSUE THREAD

**Issue by oranki** [keycloak/keycloak#10852]
### Describe the bug

Keycloak is running as user `uid=1002(keycloak) gid=1002(keycloak) groups=1002(keycloak),1003(krb5)`.

Kerberos keytab `/etc/krb5.keytab` is mode `0640`, aka. group readable. When keytab group owner is `keycloak`, kerberos authentication works. When keytab group owner is `krb5`, authentication fails. Further testing reveals authentication failing whenever access to keytab is provided via a group with a different GID than the UID keycloak process is running as.

### Version

17.0.0

### Expected behavior

Kerberos Negotiate auth succeeds.

### Actual behavior

```
principal is HTTP/my-keycloak.my.domain@MY.DOMAIN
Will use keytab
Commit Succeeded 

Found KeyTab /etc/krb5.keytab for HTTP/my-keycloak.my.domain@MY.DOMAIN
Found KeyTab /etc/krb5.keytab for HTTP/my-keycloak.my.domain@MY.DOMAIN
Found KeyTab /etc/krb5.keytab for HTTP/my-keycloak.my.domain@MY.DOMAIN
Found KeyTab /etc/krb5.keytab for HTTP/my-keycloak.my.domain@MY.DOMAIN
Entered SpNegoContext.acceptSecContext with state=STATE_NEW
SpNegoContext.acceptSecContext: receiving token = a0 82 09 d.... [trimmed]
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.2.840.48018.1.2.2
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.2.840.113554.1.2.2
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.3.6.1.4.1.311.2.2.30
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.3.6.1.4.1.311.2.2.10
SpNegoToken NegTokenInit: reading Mech Token
SpNegoContext.acceptSecContext: received token of type = SPNEGO NegTokenInit
SpNegoContext: negotiated mechanism = 1.2.840.113554.1.2.2
SpNegoContext.acceptSecContext: negotiated mech adjusted to 1.2.840.48018.1.2.2
Entered Krb5Context.acceptSecContext with state=STATE_NEW
Java config name: null
Native config name: /etc/krb5.conf
Loading krb5 profile at /etc/krb5.conf
Loaded from native config
Looking for keys for: HTTP/my-keycloak.my.domain@MY.DOMAIN
Looking for keys for: HTTP/my-keycloak.my.domain@MY.DOMAIN
2022-03-21 21:14:40,962 WARN  [org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator] (executor-thread-5) SPNEGO login failed: java.security.PrivilegedActionException: GSSException: Failure unspecified at GSS-API level (Mechanism level: Invalid argument (400) - Cannot find key of appropriate type to decrypt AP-REQ - AES256 CTS mode with HMAC SHA1-96)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
        [trimmed further backtrace]
```

### How to Reproduce?

- Keycloak running on "bare metal", aka. no containers
- Debian, OpenJDK 11
- AD LDAP as user federation source, with Kerberos auth enabled

Aside from enabling Kerberos debug in Keycloak options, using following in `bin/kc.sh`:

`SERVER_OPTS="${SERVER_OPTS} -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true"`

Let me know if you need to know something more.

**Comment by waltari2001** [comment]
I am also running kc v17 and keycloak user belongs to the root group only

$ id keycloak 
uid=1000(keycloak) gid=0(root) groups=0(root)


The problem I am having is KC doesn't seem to find the keytab , although it's there.

Debug is  true storeKey true useTicketCache false useKeyTab false doNotPrompt false ticketCache is null isInitiator true KeyTab is null refreshKrb5Config is false principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false

**Comment by oranki** [comment]
>I am also running kc v17 and keycloak user belongs to the root group only
>
> $ id keycloak
> uid=1000(keycloak) gid=0(root) groups=0(root)

Service users should **never** have gid=0. That introduces a potential attack vector, basically granting root privileges for anyone who manages to break in as the service user.

As explained in the bug report, if GID != UID, the authentication will always fail.

You can get it working by making your keycloak user gid=1000, changing keytab group ownership to gid 1000 and making the file group readable. I'm not sure if the group names are relevant, but I'd use name keycloak for gid=1000.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.
