### ISSUE TITLE
Add datasource for User Federation

### ISSUE THREAD

**Issue by beus** [keycloak/keycloak#10865]
### Description

200 / 5 000
Résultats de traduction
Before the migration to version 17, we could add an external data source. 
In the documentation (https://www.keycloak.org/docs/latest/server_installation/#_database) we are told the old version to do.
Could we have "the right way" to do it. 

### Discussion

category:Feedback

**Comment by pedroigor** [comment]
@beus We are improving this and making now possible to use an additional datasource and JPA persistence unit. Please, see https://github.com/keycloak/keycloak/issues/10579.

It should be available in the next release, 17.0.1.
