### ISSUE TITLE
Separate configuration from Quarkus server runtime

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10866]
The server configuration logic is currently part of the [`runtime` module](https://github.com/keycloak/keycloak/tree/c0255cbeea608f67ea3d81500fce09ffaa0225af/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration). This approach brings two main issues:
* The operator can't use this shared logic and [needs to re-implement it](https://github.com/keycloak/keycloak/blob/c153252cfb83f1fc641579bf7327f86505e10605/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java#L590-L591) in some cases. The `runtime` module includes too many things, incl. Quarkus configuration which makes it hardly usable as a dependency.
* Separating the configuration logic from Quarkus runtime might make sense in case we needed to use something else then Quarkus.

**Comment by andreaTP** [comment]
In this task we include:
 - separating the configuration into its own module
 - encode one "example" configuration using the new structure
 - have an initial version of a POJO generator in the operator that can be used in the CRD
