### ISSUE TITLE
[KC17] [Docs] Running Keycloak in a container: list all available env vars + mapping with previous ones

### ISSUE THREAD

**Issue by semangard** [keycloak/keycloak#10863]
### Description

Hello,
To ease the customers'migration to KC 17 would it be possible to:
- list all the allowed env vars
- indicate their mapping with previous envs var 

Main previous env vars:
- KEYCLOAK_USER or KEYCLOAK_USER_FILE 
- KEYCLOAK_PASSWORD or KEYCLOAK_PASSWORD_FILE
- KEYCLOAK_IMPORT
- DB_VENDOR
- DB_ADDR
- DB_PORT
- DB_DATABASE
- DB_USER
- DB_PASSWORD
- KEYCLOAK_FRONTEND_URL
- ROOT_LOGLEVEL
- KEYCLOAK_LOGLEVEL
- CACHE_OWNERS_COUNT
- CACHE_OWNERS_AUTH_SESSIONS_COUNT
- JGROUPS_DISCOVERY_PROTOCOL
- JGROUPS_DISCOVERY_PROPERTIES
- KEYCLOAK_STATISTICS
- X509_CA_BUNDLE
- DEBUG
- DEBUG_PORT
- KEYCLOAK_WELCOME_THEME
- KEYCLOAK_DEFAULT_THEME

### Motivation

Ease migration to KC 17.

**Comment by semangard** [comment]
@pedroigor : It would be really appreciated if KC docs could provide examples of:
- docker compose file
- configuration file for JGroups and Caching
The idea is to ease migration as much as possible for companies using KeyCloak as a docker container and who really appreciated to get previously simple env variables without having to customize underlying middleware

**Comment by pedroigor** [comment]
I also agree that we could be providing some options for:

* defaults for theme and welcome-theme. E.g.: `--theme` or `theme-welcome-page`
* the number of owners for distributed caches. E.g.: `--cache-ispn-owners`.

The `JGROUPS_DISCOVERY_PROTOCOL` is similar to the `--cache-stack` option. This option allows you to easily set the default stacks provided by Infinispan such as `kubernetes`. But if you need something else, you can cachange the `cache-ispn.xml` file to define your own JGroups stack:

```
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:13.0 http://www.infinispan.org/schemas/infinispan-config-13.0.xsd"
        xmlns="urn:infinispan:config:13.0">

<jgroups>
    <stack name="encrypt-udp" extends="udp">
      <SSL_KEY_EXCHANGE keystore_name="server.jks"
                        keystore_password="password"
                        stack.combine="INSERT_AFTER"
                        stack.position="VERIFY_SUSPECT"/>
      <ASYM_ENCRYPT asym_keylength="2048"
                    asym_algorithm="RSA"
                    change_key_on_coord_leave = "false"
                    change_key_on_leave = "false"
                    use_external_key_exchange = "true"
                    stack.combine="INSERT_BEFORE"
                    stack.position="pbcast.NAKACK2"/>
    </stack>

    <!-- Cache containers -->
    ...
</jgroups>
</infinispan>
```

We would like to provide OOTB as much configuration (common-use) as possible. If you can share more details about your settings in terms of caching/HA and if it makes sense for most people, we can probably have it OOTB with the possibility to use system properties to change some specific bits.

In the future, we should be able to provide an extensabilty mechanism that allows you to plug different cache configuration (in addition to implementation).

**Comment by semangard** [comment]
@pedroigor : on docker swarm we were using:

```
JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
# https://www.keycloak.org/2019/08/keycloak-jdbc-ping
# When Keycloak crashes, the database is not cleared, turn remove_old_coords_on_view_change property on
# Also, when a cluster is not too large, you may turn the remove_all_data_on_view_change property on
# Sometimes, Keycloak doesn't write its data into the database, you may lower the info_writer_sleep_time and info_writer_max_writes_after_view property values
JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,remove_old_coords_on_view_change=true,remove_all_data_on_view_change=true
CACHE_OWNERS_COUNT: 2
CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
```

So if we could simply get the same it would be very nice :-)

**Comment by semangard** [comment]
@pedroigor : could be great also to streamline to set KC_HTTP_RELATIVE_PATH = "/auth" (in order to avoid too much changes)

**Comment by semangard** [comment]
@pedroigor : how also to disable themes cahing for dev ?

**Comment by semangard** [comment]
@DGuhr : thanks and if we start KC17 in "prod" like mode (with "start" args) how to achieve the same ?
(yes I know that we sould use the "dev" mode, but sometimes we want to test in a "prod" like mode :-))

**Comment by DGuhr** [comment]
@semangard it'd be setting the same parameters as in the internal config, just without "%dev" (thats the internal "profile").

So like this in the conf file, or with underscores as env var, or with `--` prefix as cli.
```
spi-theme-cache-themes=false
spi-theme-cache-templates=false
spi-theme-static-max-age=-1
```

**Comment by DGuhr** [comment]
As we've created follow-ups in #10874 and #10875 i'll close this one here. Feel free to reopen if something is not solved. Afaict it is, and I just want to avoid discussions around multiple topics in one ticket, and have smaller scoped follow-ups instead (or feel free to open a more broad discussion ;) ).
