### ISSUE TITLE
Database schema migration configuration parameters not working as expected

### ISSUE THREAD

**Issue by gelm0** [keycloak/keycloak#10871]
### Describe the bug

Following https://www.keycloak.org/docs/latest/upgrading/index.html it states that you can enable manual schema migration by adding the `--spi-connections-jpa-default-migration-strategy=manual parameter` to the startup command.

However when doing so the expected sql file is not generated and database is migrated automatically.

Steps to reproduce the issue
```version: "3.9"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.0
    environment:
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak-secret
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data
volumes:
  pg-volume:
    driver: local
```

Run docker-compose up and wait for the database to have been setup.
Close the instance and create a new docker-compose file with

```version: "3.9"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    command: ["start", "--auto-build", "--spi-connections-jpa-default-migration-strategy=manual"]
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak-secret
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data
volumes:
  pg-volume:
    driver: local
```

Run docker-compose up again.

### Version

17.0.0 Quarkus

### Expected behavior

A sql file is generated instead of migrating the database automatically

### Actual behavior

The database is migrated automatically

**Comment by pedroigor** [comment]
@gelm0 Could you please try `--spi-connections-jpa-quarkus-migration-strategy=manual`? The provider name is `quarkus`.

We should probably keep the same id as before to avoid confusion.

**Comment by gelm0** [comment]
Ah that seemed to do it. Probably should update the docs. Want me to create a PR for it?

**Comment by DGuhr** [comment]
@gelm0 would be great if you could provide a PR to fix this :)

**Comment by psytester** [comment]
It seems I finally catched this issue in my open discussion #11099. But unfortunately this setting does not work for me:
`--spi-connections-jpa-quarkus-migration-strategy=manual`
😞

**Comment by psytester** [comment]
Ok, I got it working for my case.
In my case for manual inital DB setup, the `initializeEmpty = false` was missing:
`--spi-connections-jpa-quarkus-initialize-empty=false`

But the overall working with docs on spi configuration should be improved 😉

**Comment by lmorocz** [comment]
Hi! According to [PR#11110](https://github.com/keycloak/keycloak/pull/11110) I tried to start v19.0.1 with the manual strategy using parameters:

```
--spi-connections-jpa-quarkus-migration-strategy=manual --spi-connections-jpa-quarkus-initialize-empty=false --spi-connections-jpa-quarkus-migration-export="/tmp/keycloak_migr.sql"
```

but unfortunately it didn't work. The database is migrated automatically and there is no export file in /tmp. 

What is missing here?

**Comment by pedroigor** [comment]
@lmorocz Created https://github.com/keycloak/keycloak-documentation/pull/1647 to update docs.
