### ISSUE TITLE
unknown option: '--hostname-admin=.. '

### ISSUE THREAD

**Issue by g10f** [keycloak/keycloak#10890]
### Describe the bug

--hostname-admin seems to be not working anymore since keycloak 17.0.1 . In 17.0.0 everything was OK.

### Version

17.0.1

### Expected behavior

https://www.keycloak.org/server/all-config?q=hostname-admin

### How to Reproduce?

start keycloak with --hostname-admin

**Comment by RVSO-NC** [comment]
I have also found that suddenly "KC_PROXY: none" results in white screen when trying to reach the admin interface! Didn't happen in 17.0. Funny thing is that if I remove the variable everything works as expected :O

**Comment by RVSO-NC** [comment]
https://github.com/keycloak/keycloak/pull/10820

**Comment by g10f** [comment]
> #10820 here is the explanation!

Thank you, than this in an issue with the documentation https://www.keycloak.org/server/all-config?q=hostname-admin

**Comment by g10f** [comment]
Docu was updated.
