### ISSUE TITLE
[SPIKE] Re-evaluate the realm import implementation in the operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10910]
This is closely related to #9261. When that is implemented, we might be able to get rid of the realm import job. Be aware of performance.

**Comment by shawkins** [comment]
@vmuzikar what is the performance consideration here?  The startup import seems to skip the import if the realm altready exists.  But that also seems to imply it doesn't handle the case of updating an existing realm via startup import.

**Comment by vmuzikar** [comment]
@shawkins I believe this issue is actually out of date. We don't want to invest much time into the Realm Import as we want to replace it with a Realm CR for full Realm management (https://github.com/keycloak/keycloak/issues/13566) instead of just one time import.

This issue was about exploring the idea of mounting the Realm import file to each KC instance pod and perform the import at startup. IIRC, the performance consideration was about performing the import on each pod (potentially multiple times) instead of single time in a job.
