### ISSUE TITLE
Unable to get managed connection

### ISSUE THREAD

**Issue by hani647** [keycloak/keycloak#10925]
### Describe the bug

We're getting the below error intermittently, in return this crashes our AWS service. We've setup connection pool size to be 3000 and in RDS we're seeing connection spikes maximum to 800 so there's still a limit left and keycloak can open the connection too but it aint. Would anyone know the cause of this issue? 

Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS 

### Version

14.0.0

### Expected behavior

It should not crash the AWS.

### Actual behavior

It is crashing the AWS service.

### How to Reproduce?

1. Setup the KC in clustered mode
2. Call Keycloak API like (.update, .create attributes etc).
3. Intermittently this will be re-produced.

**Comment by junaidcassbana** [comment]
Hey guys,

Any update on this?

We are facing the same issue on production.

We are using keycloak 16.1.1


Thanks!

**Comment by hani647** [comment]
Hey @junaidcassbana , 
We got it resolved by upgrading keycloak to 16. Previously we were using 14 and we found there was a fix done by keycloak dev. team in keycloak 16.

It seems you're already on keycloak 16. I would recommend you to try checking the DB connection because "Unable to get managed connections" exception is raised when application is unable to connect to DB. Maybe check if your DB is getting stale or is there any sort of firewall blocking the keycloak to connect to DB and this is could be intermittent too!

**Comment by junaidcassbana** [comment]
Thanks @hani647 for the quick response. Will check our db as you suggested.

**Comment by momyyao** [comment]
@hani647  What was the fix?  We are having similar issue.  But the connection issue happens on our user storage DB instead of KeycloakDS.  I'm trying to figure out whether its related.

**Comment by hani647** [comment]
@momyyao the issue was because of concurrency. In keycloak less than 16 there's a code where it uses concurrency while creating session due to that buggy code the too many connections were getting created. Also, in exception we were seeing ConcurrencyException too. See if you're observing same scenarios?

**Comment by junaidcassbana** [comment]
@hani647  the issue in our case was:
Our database service went down itself.

**Comment by casfe03** [comment]
hi @hani647 do you have the PR os this issue, only to understand what was doing to solve that? Thank you my friend :)

**Comment by tuliofergulha** [comment]
I'm facing the same problem. It would be interesting to take a look at the PR or some release notes that show the problem is fixed. Could you share with us @hani647?
