### ISSUE TITLE
Maven Metadata for keycloak-parent is outdated

### ISSUE THREAD

**Issue by jkroepke** [keycloak/keycloak#10922]
### Describe the bug

Hi,

https://github.com/adorsys/keycloak-config-cli is using dependabout the manage dependency updates.

Since the 17.0.1 release yesterday, I notified there is still no opened pull request to upgrade the keycloak-parent dependency while other dependency update are available.

I looked deeper into it and figure out, that https://repo.maven.apache.org/maven2/org/keycloak/keycloak-parent/maven-metadata.xml still mention 16.1.1 as latest version, while https://repo.maven.apache.org/maven2/org/keycloak/keycloak-parent/17.0.1/ is available.

I have no clue, is its an error on maven central side OR there still some shady sync from RH maven that overrides the [maven-metadata.xml](https://repository.jboss.org/nexus/content/groups/public/org/keycloak/keycloak-parent/maven-metadata.xml) in maven central. Both maven-metadata.xml have the same `lastUpdated` value.

### Version

17.0.1

### Expected behavior

maven-metadata.xml should reference the lastest available version in maven central.

### Actual behavior

maven-metadata.xml referenced and outdated version as lastest available version in maven central.

### How to Reproduce?

Open https://repo.maven.apache.org/maven2/org/keycloak/keycloak-parent/maven-metadata.xml

### Anything else?

This might ne not mission critical on the first view, but it breaks all dependency bots like dependabot or renovate.

**Comment by stianst** [comment]
Not really sure what's going on here, but I've opened a ticket with Sonatype here:

https://issues.sonatype.org/browse/OSSRH-80163

Hopefully they can sort out the issue on their end.

**Comment by jkroepke** [comment]
Hi @stianst 

maybe it helps. For a short time, the maven-metadata.xml was correct, since dependabot was able to detect new version.

https://github.com/adorsys/keycloak-config-cli/pull/712

But for now, it looks now the overwritten again. From my point of view, it feel like the maven-metadata.xml is periodicly overridden (by a sync?). Maybe its worth to check if repository.jboss.org is stop syncing the keycloak repository (which could override the maven-metadata.xml)

**Comment by stianst** [comment]
Yeah, that's probably it. I've updated the ticket with Sonatype as I'm not sure who controls the sync job if there is still one.
