### ISSUE TITLE
Slash character in Authentication Flow Alias

### ISSUE THREAD

**Issue by z3ky** [keycloak/keycloak#10940]
### Describe the bug

If the alias of an authentication flow contains a /-character, die flow can not be opened again.
Keycloak puts the alias into the URL, slashes won't be encoded to %2f.

### Version

17.0.0

### Expected behavior

Slash characters in authentication flow alias should be correctly encoded or Keycloak should point out, that slashes in aliases are not allowed.

### Actual behavior

Slash characters in authentication flow alias won't be encoded and Keycloak shows an error page due to an unknown page.

### How to Reproduce?

- Create a new authentication flow

- Put a / into its alias and save.

- Try to open the authentication flow

**Comment by mposolda** [comment]
@z3ky Thanks for the report. I am adding the label "help wanted" as this is a corner case and low priority issue. I think we should have a validation to make sure that authentication flow alias contains only sensible characters (EG. not slashes, whitespaces or other URL unsafe characters).

**Comment by joeri-jansen** [comment]
Facing the same issue here. A simple validation can fix this.

**Comment by PhilKes** [comment]
Hi, isn't this fixed already?
I tested it, if I enter e.g. `test/flow` as an alias I get a `400 Bad Request` with response: `{error | "Character '/' not allowed."}` 

https://github.com/keycloak/keycloak/blob/f684a70048d3833c9066e938d66b7f7ba41cab40/server-spi-private/src/main/java/org/keycloak/utils/ReservedCharValidator.java#L37
Already validates if a String contains any reserved characters, and is called in
https://github.com/keycloak/keycloak/blob/f684a70048d3833c9066e938d66b7f7ba41cab40/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L241

So can this be closed or is there anything to do still? @mposolda

**Comment by ahus1** [comment]
@mposolda - there is now a PR for this #23301

**Comment by luahan77m** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by jonkoops** [comment]
@luahan77m as you can see from the conversion history there is already a PR open under #23301. Feel free to pick up any other issues marked as 'help wanted' that do not have an assignee.

**Comment by mposolda** [comment]
Closing as this seems to be already fixed in latest KEycloak 24 release. Please re-open just if you still see this.
