### ISSUE TITLE
Getting 404 not found when using templates in custom provider deployed under providers folder

### ISSUE THREAD

**Issue by RManesiya** [keycloak/keycloak#10951]
### Describe the bug

I have two providers I use one from `[GitHub - BenjaminFavre/keycloak-apple-social-identity-provider: Apple Social Identity Provider for Keycloak](https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider)`, and I wrote another custom provider. 

The custom templates are housed under **`myprovider.jar\theme-resources\resources\partials`**, just as they should be packaged.

Bear in mind I do run `kc.bat build` after placing both the jar files in the **`keycloak-17.0.0\providers`** folder.

When editing configured providers using say following links below I get 404 on one of them unless I remove one or the other, or place the template files in **`keycloak-17.0.0\themes\base\admin\resources\partials`** to prevent **404** message

*/admin/master/console/#/realms/idp/identity-provider-settings/provider/apple/apple*

*/admin/master/console/#/realms/idp/identity-provider-settings/provider/myprovider/myprovider*

In Keycloak version 15.0.0 when browsing to **`/admin/master/console/#/server-info/providers`** under section I see

```
themeResource	 apple-social-identity-provider-1.0.2.jar
                                 myprovider.jar
```
In Keycloak version 17.0.0 when browsing to `/admin/master/console/#/server-info/providers` under section I see
```
themeResource	classpath
```

NOTE: This works flawlessly in version 15.0.0, and I able to edit both providers using custom templates bundled in jar files.

### Version

17.0.0

### Expected behavior

It should find the template bundled in the jar file and allow updating custom provider settings.

### Actual behavior

I get 404 when editing/creating one of the provider's settings that were deployed.

### How to Reproduce?

1.  Download and extract Keycloak https://github.com/keycloak/keycloak/releases/download/17.0.0/keycloak-17.0.0.tar.gz
2.  Download custom identity provider for Apple sign in
https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider/releases/download/v1.0.2/apple-social-identity-provider-1.0.2.jar and copy to **`[KEYCLOAK-17.0.0-PATH]\providers`**
3. Create another custom provider similar to  `https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider` build the jar file and drop it in **`[KEYCLOAK-17.0.0]\providers`**
4. Run **`[KEYCLOAK-17.0.0-PATH]\bin\kc.bat build`**
5. Run **`[KEYCLOAK-17.0.0-PATH]\bin\kc.bat start`**
6. Create a new Realm **`idp`**
7. Browse to **`[YOUR-KEYCLOAK-HOST]/admin/master/console/#/realms/idp/identity-provider-settings`**, add your custom identity provider from the drop-down list. You will get a 404 when attempting to add one of the custom providers, and not the other.

**Comment by pedroigor** [comment]
@RManesiya Thanks. Sent https://github.com/keycloak/keycloak/pull/10989. Would you be able to check it out?

**Comment by RManesiya** [comment]
Sure. I'll check it out. Thanks and let you know.

**Comment by pedroigor** [comment]
@RManesiya Btw, you mentioned the two providers shown in the server info when running the legacy distribution.

You should still see a single provider and that is expected. The server class loader is no longer modularized as it was with Wildfly/JBoss Modules and Quarkus has a flat classpath. See https://quarkus.io/guides/class-loading-reference.

**Comment by RManesiya** [comment]
@pedroigor Tested the changes and it is looking good. It works as expected when I deploy providers built on Quarkus distribution based on branch issue-10951. I tested editing both providers and don't 404 anymore :-)

**Comment by RManesiya** [comment]
Thank you!!
