### ISSUE TITLE
start-dev _without_ auto-build 

### ISSUE THREAD

**Issue by MFAshby** [keycloak/keycloak#10956]
### Description

I am using keycloak 17.0.1 official docker image in a suite of system tests. My applications and supporting apps like keycloak are booted in docker containers, and the test runner drives a browser to perform full-system testing.

I would like to start keycloak in development mode in order to boot without requiring SSL and a particular hostname to be configured. I would _not_ like to --auto-build at the same time, because I would like to boot my test environment as fast as possible, and I already have a dockerfile which runs `build` adding the necessary build options.

At the moment I can't see a way to achieve that without replacing the whole boot script in the container image.

Boot script: https://github.com/keycloak/keycloak/blob/6a657e64729f575f4fcf967366f58da714fbed1e/quarkus/dist/src/main/content/bin/kc.sh#L51

My dockerfile: 
```
# keycloak 17.0.1
FROM quay.io/keycloak/keycloak@sha256:9e7e11f0c71e6959c94bb40610f60d1b27d8a71bcfecfe8c7c714837960a6d17
# https://www.keycloak.org/migration/migrating-to-quarkus#_default_context_path_changed
RUN /opt/keycloak/bin/kc.sh build --db=postgres --http-relative-path=/auth 
# Patched boot script removes the auto-build on start-dev.
# I don't want to auto-build, it's slow and I already build here. I _do_ still want to start-dev however.
COPY kc.sh /opt/keycloak/bin/kc.sh
```

small change to kc.sh
```
              #CONFIG_ARGS="$CONFIG_ARGS --profile=dev $1 --auto-build"
              CONFIG_ARGS="$CONFIG_ARGS --profile=dev $1"
```

It would be great if there was some way to achieve this without needing to patch this boot script.

### Motivation

It's an optimization to keycloak boot time for development purposes.

### Details

see description.

**Comment by DGuhr** [comment]
Hi @MFAshby 
When you look [here](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/resources/META-INF/keycloak.conf) in our internal default config, you'll see multiple parameters that are set for the devmode, prefixed with `%dev`. If you really want the same behaviour, but without the auto-build, I suggest you run Keycloak with a pre-built image with that config, but in production mode: 

```
# keycloak 17.0.1
FROM quay.io/keycloak/keycloak@sha256:9e7e11f0c71e6959c94bb40610f60d1b27d8a71bcfecfe8c7c714837960a6d17
# https://www.keycloak.org/migration/migrating-to-quarkus#_default_context_path_changed
RUN /opt/keycloak/bin/kc.sh build --db=postgres --http-relative-path=/auth --spi-theme-cache-themes=false --spi-theme-cache-templates=false --spi-theme-static-max-age=-1 --cache=local
```

and then start it with `start --http-enabled=true --hostname-strict=false --hostname-strict-https=false <other runtime options, e.g. db password etc>` or the appropriate environment variables / config file.

Would that work for you?

**Comment by MFAshby** [comment]
> Would that work for you?

Thanks for the tip! I hadn't found that configuration file. Your suggestion is working fine, I can add those options for boot in development only, and share the same pre-built docker image with production.
