### ISSUE TITLE
Quickstarts Tests consistently broken on main

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#10950]
### Describe the bug

"Quickstarts Tests" are consistently broken on the `main` branch e.g.:

 - https://github.com/keycloak/keycloak/runs/5692285797?check_suite_focus=true#logs

### Version

main

**Comment by abstractj** [comment]
Confirmed and we should fix this.

**Comment by abstractj** [comment]
Now the issue is slightly different from the original report, but we can make use of this issue considering that they are still broken: https://github.com/keycloak/keycloak/runs/5858287136?check_suite_focus=true

**Comment by ahus1** [comment]
Two PRs to work towards a greener build: 
* https://github.com/keycloak/keycloak-quickstarts/pull/328
* https://github.com/keycloak/keycloak-quickstarts/pull/326

Once those are merged, we'll tackle the next ones.

**Comment by abstractj** [comment]
@ahus1 thank you so much for looking into this!

**Comment by ahus1** [comment]
One more PR: 
* https://github.com/keycloak/keycloak-quickstarts/pull/334

**Comment by ahus1** [comment]
Now they are finally green: https://github.com/keycloak/keycloak-quickstarts/pull/336

:tada: :pinata:

**Comment by andreaTP** [comment]
I applaud you @ahus1 fixer of CIs! 🎉  Thanks!
