### ISSUE TITLE
keycloak/quarkus 17.0.1 propagates pod internal tcp port to web page

### ISSUE THREAD

**Issue by Brezensalzer** [keycloak/keycloak#10964]
### Describe the bug

With keycloak 17.0.1 the admin console delivers a white page after login.
Looking at the html code, the pod-internal port 8443 is propagated to the web client in `authServerUrl`:

```
    <script type="text/javascript">
        var authServerUrl = 'https://login-test.ms.bgnet.de:8443/auth';
        var authUrl = 'https://login-test.ms.bgnet.de/auth';
        var consoleBaseUrl = '/auth/admin/master/console/';
        var resourceUrl = '/auth/resources/j048i/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'j048i';
    </script>
```

Rolling back to keycloak 17.0.0, everything works again, no port 8443 in `authServerUrl`:
```
    <script type="text/javascript">
        var authServerUrl = 'https://login-test.ms.bgnet.de/auth';
        var authUrl = 'https://login-test.ms.bgnet.de/auth';
        var consoleBaseUrl = '/auth/admin/master/console/';
        var resourceUrl = '/auth/resources/j048i/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'j048i';
    </script>
```

Platform: OpenShift 4.8

### Version

17.0.1

### Expected behavior

Internal tcp port in the pod is not propagated to the web client

### Actual behavior

see description above

**Comment by Brezensalzer** [comment]
Commit [3da5a8e](https://github.com/keycloak/keycloak/commit/3da5a8ea7349ee306895f0071b883901102fe2fd) is probably the the culprit. 
By "fixing" #10331[](https://github.com/keycloak/keycloak/discussions/10331) this side effect was introduced.

**Comment by pedroigor** [comment]
@Brezensalzer Can you please provide the options you are using to start the server?

**Comment by pedroigor** [comment]
The new options added to set the hostname base URL should help. See https://github.com/keycloak/keycloak/issues/13524.
