### ISSUE TITLE
Data type for timestamp and expiration in Map Storage

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#10960]
### Description

When reviewing #10943 I noticed that one timestamp is handled as an int, and expiration is treated as a long. 
This happens both on the database level (see [jpa-auth-sessions-changelog-1.xml](https://github.com/keycloak/keycloak/pull/10943/files#diff-36cfdca24245b6a1d92f427253eaa32aae5cac2760bbc18157255ac767e57326)) and in the Java code.

Both timestamp and lifespan are stored in seconds.

Both seem to be timestamp, and calculations are based on the two, see SessionExpiration.java: 

```
    public static long getAuthSessionExpiration(RealmModel realm, int timestamp) {
        return (long) timestamp + getAuthSessionLifespan(realm);
    }
```

I wonder why the sum should be a long while timestamp isn't.

Handling timestamps as singed integers is known as the [Year 2038 problem aka the Epochalypse](https://en.wikipedia.org/wiki/Year_2038_problem).

### Motivation

Prevent errors at runtime, clarify usage for development.

### Details

Possible options to solve this (please discuss):
* Treat time as seconds a long in timestamp (thereby affecting org.keycloak.common.util.Time) - this would be done after Keycloak 18?
* Prepare the map storage to handle timestamp and expiration as longs ahead of time already before Keycloak core changes to avoid disruptions later.

**Comment by hmlnarik** [comment]
Thank you for this discussion.

At this moment, we must not change contract of `Model`s in the server-spi module, e.g. that of `RootAuthenticationSessionModel`.

For this reason, we must prepare map storage for `long`s but still keep adapters as `int`s.

Once the RHSSO 8 is there, this would be possible to handle in a separate issue.

**Comment by martin-kanis** [comment]
Return time of the get expiration methods for [auth|user|client] sessions has to be `long` because there is a test for Integer.MAX values set as timestamp. There was an overflow when calculating expiration time as `int`.

**Comment by ahus1** [comment]
Waiting for #10943 to be merged to avoid conflicts.

**Comment by ahus1** [comment]
There is now issue #11053 to handle this in core. This issue will handle this only in the new store to have timestamps always as longs.

**Comment by ahus1** [comment]
The issue in core has been approved for 19, will start working on this one now.
