### ISSUE TITLE
Flaky Operator tests

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#10967]
### Describe the bug

Found this spurious failure:

- https://github.com/andreaTP/keycloak/runs/5719888347?check_suite_focus=true#step:9:3915

The changes in the branch are un-related to the operator.

The test failed with:
```
KeycloakDeploymentE2EIT.testDeploymentDurability:148
```

### Version

latest

**Comment by andreaTP** [comment]
Another flaky test:
https://github.com/keycloak/keycloak/runs/5723663679?check_suite_focus=true

**Comment by andreaTP** [comment]
https://github.com/keycloak/keycloak/runs/5750417505?check_suite_focus=true#step:10:4478

**Comment by DGuhr** [comment]
https://github.com/keycloak/keycloak/runs/5863358705?check_suite_focus=true#step:11:4302
