### ISSUE TITLE
Keycloak "forgets" ui_locales parameter when using Reset Password functionality

### ISSUE THREAD

**Issue by sonOfRa** [keycloak/keycloak#10981]
### Describe the bug

When the user is redirected back to the login page after entering their email in the "Forgot password" dialog, the language resets to the realm's default language, rather than using a previously set ui_locales parameter.

### Version

17.0.1

### Expected behavior

When being sent back to the login page after a reset password flow, the page should still be translated in the language that was requested via the ui_locales parameter.

### Actual behavior

Instead, the language is reset to the default language of the selected realm.

### How to Reproduce?

1. Create a new realm and client with the authorization code flow, in this case, both named "test". Set the client's redirect_uri to "*".
2. Enable "forgot password" on the realm
3. Enable "Localization" on the realm, and select at least 2 languages (in this case, de and en, with the default language being de)
4. Navigate to [http://localhost:8080/auth/realms/test/protocol/openid-connect/auth?client_id=test&response_type=code&redirect_uri=https://google.com&ui_locales=en](http://localhost:8080/auth/realms/test/protocol/openid-connect/auth?client_id=test&response_type=code&redirect_uri=https://google.com&ui_locales=en)
5. Click "Forgot Password?" and enter any email (an actual user is not required to exist)
6. After submitting the email, the language of the form will have switched to German, rather than the requested English

### Anything else?

When using the language switcher in the login form to switch the language to english, keycloak redirects the user and appends the kc_locale parameter. This parameter is correctly remembered, and even after a password reset, when the user gets redirected back to the login page, the page is in the expected language.

As a workaround, we tried appending kc_locale directly to the auth URL, like [http://localhost:8080/auth/realms/test/protocol/openid-connect/auth?client_id=test&response_type=code&redirect_uri=https://google.com&ui_locales=en&kc_locale=en](http://localhost:8080/auth/realms/test/protocol/openid-connect/auth?client_id=test&response_type=code&redirect_uri=https://google.com&ui_locales=en&kc_locale=en), as well as [http://localhost:8080/auth/realms/test/protocol/openid-connect/auth?client_id=test&response_type=code&redirect_uri=https://google.com&kc_locale=en](http://localhost:8080/auth/realms/test/protocol/openid-connect/auth?client_id=test&response_type=code&redirect_uri=https://google.com&kc_locale=en), but both of these seem to be ignored. They are only used when the user manually selects a language using the language selector.

**Comment by InterStelli** [comment]
Can confirm that this also happens in our setup

**Comment by rherlt** [comment]
we have the same issue in keycloak v12.0.4

**Comment by cybermo** [comment]
Same issue in the latest release keycloak v19.0.2.

user local and gui local are in FR when reseting the passwrod the success screen "Your account has been updated." comes in default local of the realm EN.

**Comment by mposolda** [comment]
Usually we add OIDC parameters sent by client (like `ui_locales` in this case) to client notes. But for `ui_locales` we use authNote for some reason (not 100% sure why, maybe just a typo). So one possible solution to it is to use `clientNote` for `LocaleSelectorProvider.CLIENT_REQUEST_LOCALE` instead of authNote. As client notes should survive authentication session "fork" in new browser, which is used in reset-credentials flow AFAIK.

**Comment by arigelni** [comment]
@mposolda what do you want to say? what is the solution? is there a solution?

**Comment by jonkoops** [comment]
@mposolda I see this is attached to the 23 milestone, but considering this is a bug fix, perhaps it should be back-ported to a patch instead?

**Comment by mposolda** [comment]
@jonkoops Added to 22.0.2 in the end as it is customer related :-)

**Comment by c0ntradicti0n** [comment]
I still can reproduce this with the latest version (23.0.6). The cookie rules the language and can only be changed using manually the language switch, but not having a value preselected in the url. Is there anything we can do else than a custom provider to implement a prevalence of the query string setting over the cookie?
