### ISSUE TITLE
Remove redirect_uri support from OIDC logout endpoint

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#10983]
### Description

Keycloak 18 was updated to follow the RP initiated logout specification, deprecating the support for the legacy `redirect_uri` parameter on the logout endpoint. Support for this backwards compatibility mode should be removed at some point.

### Details

Removing this will require:

- Update of the `LogoutEndpoint.logout()` method and remove support for "redirect_uri" parameter of this method
- Removing method `RedirectUtils.verifyRealmRedirectUri(KeycloakSession session, String redirectUri)` (which is already deprecated in Keycloak 18). And remove some other private method in the `RedirectUtils` class, which is used by the removed `verifyRealmRedirectUri` .
- Remove configuration option `OIDCLoginProtocolFactory.CONFIG_LEGACY_LOGOUT_REDIRECT_URI` and `OIDCLoginProtocolFactory.SUPPRESS_LOGOUT_CONFIRMATION_SCREEN` from `OIDCLoginProtocolFactory` and this constant. This also means reverting changes introduced by https://github.com/keycloak/keycloak/pull/13471 . Probably whole class `OIDCProviderConfig` can be removed in this case (unless we have some other configuration option to `OIDCLoginProtocolFactory` added in the meantime)
- Remove LegacyLogoutTest
- Remove system property config option from the keycloak-server.json in the testsuite
- Documentation will need to be updated (Upgrading guide) about the fact that the options, which were deprecated in Keycloak 18 and 19.0.2, are removed now.

Will be good to discuss with @sschu and/or @bs-matil before removing this.

**Comment by mposolda** [comment]
Removing this will require:
- Update of the `LogoutEndpoint.logout()` method and remove support for "redirect_uri" parameter of this method
- Removing method `RedirectUtils.verifyRealmRedirectUri(KeycloakSession session, String redirectUri)` (which is already deprecated in Keycloak 18)
- Remove configuration option `OIDCLoginProtocolFactory.CONFIG_LEGACY_LOGOUT_REDIRECT_URI` from `OIDCLoginProtocolFactory` and this constant. Probably whole class `OIDCProviderConfig` can be removed in this case (unless we have some other configuration option to OIDCLoginProtocolFactory added in the meantime)
- Documentation will need to be updated (Upgrading guide) about the fact that the option, which was deprecated in Keycloak 18, is removed now.

**Comment by mposolda** [comment]
Moving this to Keycloak 26. From what I know, lots of people and customers still rely on the legacy stuff and I don't think we can remove it right now :-/ Will probably need few more releases (with the additional announcement about removing legacy stuff one release before we really do it).

@sschu Do you still need the legacy stuff or not anymore?

**Comment by sschu** [comment]
I will check our access logs...

**Comment by syed-saad-zahidi** [comment]
i am using keycloak for node red.Upon login the keycloak is removing /20036 from my redirect url . on my keycloak setting the redirect url is https://nodered-dev.abc.de/20036/* .On login the keycloak is removing /20036 from my url so i am getting this url  
https://nodered-dev..abc.de/?access_token=shAJC6UmchIgSwQRbsg0rNFpHtkqzsnwFgkMvTa149/u0/YG2SO/OxjZvv058/7Xq6biaV0gz9OAV8zkfUsJuMNFO4nkIuyOwixj8HlneglKnpn6s51/HCEIo/eXDWsktEgbS75P8iGTwrNPJa+/HpFybA613lYpw2CDvwy76kk=
