### ISSUE TITLE
Replace the dependency cache on GitHub Actions

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#10987]
### Description

The setup-java action now also supports [caching Maven dependencies](https://github.com/actions/setup-java#caching-maven-dependencies). This means that in some cases, the cache action can be removed by adding this option.

@jonkoops brought that to my attention on #10972 and more examples can be found here too https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/

**Comment by jonkoops** [comment]
There is an old PR to implement this https://github.com/keycloak/keycloak/pull/8452, but it was abandoned due to lack of reviews. It might be useful for inspiration.

**Comment by abstractj** [comment]
@jonkoops please feel free to reopen and update that. I will be more than happy to review. My apologies if I missed that.
