### ISSUE TITLE
Remove doubled field from HotRod entities

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#10988]
### Description

Currently, for case-insensitive search and order we have some fields doubled, e.g.:
https://github.com/keycloak/keycloak/blob/19e55650a20592e843485cc79dc648ddea24a56c/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/user/HotRodUserEntity.java#L64-L70

The cause is that by using the analyzed index, we achieve case-insensitivity but we lose the possibility to order because the analyzed index doesn't know the original value.

We should be able to replace the doubled field with a doubled index (we should be able to use two annotations on the same field) which should end up with fewer data in the store.

**Comment by martin-kanis** [comment]
Currently doubled annotations on the same field are not possible. We can workaround it by doubling getter for the given field. Each getter can have different annotation and analyzer. See examples https://github.com/infinispan/infinispan/pull/10041.

Also there will be support for lowercase normalizer https://github.com/infinispan/infinispan/pull/10041 so we will be able to get rid off doubled fields.

**Comment by mhajas** [comment]
Might be fixed by: https://github.com/keycloak/keycloak/issues/12493
