### ISSUE TITLE
Allow overriding the host header using X-Forwarded-Host

### ISSUE THREAD

**Issue by franzmathauser** [keycloak/keycloak#10997]
### Describe the bug

I run a httpd server as reverse proxy upfront a keycloak. The TTLs termination is done by the httpd server. In order to pass the incoming requests to keycloak-node we use a secured connection via https with a self signed CA which is setup for the whole internal backend infrastructure. 

The [Proxy-Userguide](https://www.keycloak.org/server/reverseproxy) expects a preserved Host header, which is not possible since this will fail the certificate check during the proxy action.

If i do not preserve the Host to keycloak and navigate to to the admin-console the browser wants to load a resource which is of the same origin of the Host-Header (which is internal keycloak adress) not the X-Forwarded-For value. The admin console cannot be loaded because the browser cannot directly load anything from the internal backend network.

`curl -v  https://somepublic.domain.com/auth/admin/master/console/`
returns a html-response which contains a script resource with url **stage-kc**
`<script src="https://stage-kc/auth/js/keycloak.js?version=dvfah" type="text/javascript"></script>`

Same for authUrl of the master / console => this is an internal address, this should either be not relevant or exposed to public.

```
 <script type="text/javascript">
        var authServerUrl = 'https://somepublic.domain.com/auth';
        var authUrl = 'https://stage-kc/auth';
        var consoleBaseUrl = '/auth/admin/master/console/';
        var resourceUrl = '/auth/resources/dvfah/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'dvfah';
    </script>
```

I also tried with the feature admin2, which also fails loading and even requests calls to

http://127.0.0.1:8080/auth/admin/master/console/whoami
![image](https://user-images.githubusercontent.com/701101/160783145-ca787c0f-f335-46c5-bc4c-9777cfdc9caf.png)

### Version

17.0.1

### Expected behavior

The UI resources urls respect the set X-Forwarded-For header and do not rely on the Host header.

should return a public facing url
`<script src="https://somepublic.domain.com/auth/js/keycloak.js?version=dvfah" type="text/javascript"></script>`

### Actual behavior

Do not rely on the Host-Header for url-path. Rather use the X-Forwarded-* header values.

### How to Reproduce?

**apache httpd config**

 ```
<Location /auth>
                ProxyPass            https://STAGE-KC:8343/auth
                ProxyPassReverse     https://STAGE-KC:8343/auth
                ProxyPassReverseCookieDomain  "STAGE-KC"  "somepublic.domain.com"
                RequestHeader set X-Forwarded-Proto "https"
                RequestHeader set X-Forwarded-Port "443"
                RequestHeader set X-Forwarding-For "somepublic.domain.com"
                RequestHeader set X-Forwarded-For "somepublic.domain.com"
                RequestHeader set X-Forwarded-Host "somepublic.domain.com"
     </Location>
```

**keycloak.conf**
```
proxy=reencrypt
hostname=stage-kc
http-enabled=true
http-host=0.0.0.0
http-port=8383
https-port=8343
http-relative-path=/auth

spi-x509cert-lookup-apache-ssl-client-cert=SSL_CLIENT_CERT
spi-x509cert-lookup-apache-ssl-cert-chain-prefix=CERT_CHAIN
spi-x509cert-lookup-apache-certificate-chain-length=2
```

**keycloak build**
I used `--spi-x509cert-lookup-provider=apache` for the upfront keycloak build.

**Comment by jonathanmmm** [comment]
Having the same issue, tried and tried to know what I have set wrong, 17.0.0 works fine with nginx, my settings:

important settings in `docker-compose.yml`:
```
KC_HOSTNAME: my-domain.com
KC_PROXY: edge
KC_HTTP_ENABLED: 'true'
```

nginx:
```
set $keycloak_docker keycloak:8080;
proxy_set_header X-Forwarded-For $proxy_protocol_addr;
proxy_set_header X-Forwarded-Proto $scheme; 
proxy_set_header Host $host; 

location / {
          proxy_pass http://$keycloak_docker;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
          proxy_set_header   X-Forwarded-Host  $host;
proxy_cache off;
  expires -1;
    }
```

nginx is also in a docker container and the ports are mapped something like this:
```
80:8080
443:8443
```
Sometimes it redirected js files to the internal nginx docker port, not the one from the outside.

At least in the end of trying, I couldn't do anything really. Even login for users didn't work. But still something was broken (could also be me, after trying to fix the admin panel).

Switched back to 17.0.0 and everything works again.

**Comment by franzmathauser** [comment]
@joao-rebelo thanks for mentioning the version 17.0.0. a rollback to this version works.

**Comment by franzmathauser** [comment]
@pedroigor yes indeed. is that something i can do by adding a conf/quarkus.properties next to my conf/keycloak.conf?

if this is the case, this should be part of the the user guide.

When i run keycloak with wildfly i also set the enable-forwarded-host setting in my standalone.xml

**Comment by joao-rebelo** [comment]
@stianst if I correctly understand the hostname changes that entered on 17.0.1 I believe the hostname property no longer works for the Web admin page. (check my example provided above)

**Comment by stianst** [comment]
Forgot about that one. Yeah, so we definitely need to support X-Forwaded-For, which should just be enabled when proxy != none

**Comment by pedroigor** [comment]
@joao-rebelo @franzmathauser These changes should be enough to enable overriding the host using the `X-Forwarded-Host` header and allow using a specific host when calculating the admin URLs. 

However, setting `X-Forwarded-Host` still has no effect on the frontend URLs. Those are calculated based on the `hostname` option.

If you could try https://github.com/keycloak/keycloak/pull/11021, I appreciate.
