### ISSUE TITLE
ciba http auth channel sends client_id and client_secret via delegation request

### ISSUE THREAD

**Issue by wimvanboven** [keycloak/keycloak#10993]
### Describe the bug

when configuring the ciba http auth channel provider, it seems like the authentication delegation request posted to the KC_SPI_CIBA_AUTH_CHANNEL_CIBA_HTTP_AUTH_CHANNEL_HTTP_AUTHENTICATION_CHANNEL_URI endpoint contains additional 'unexpected' parameters like client_id and client_secret of the initiating client. 
this looks unintentional and is not mentioned in the documentation. 

### Version

17.0.0

### Expected behavior

the authentication delegation request body described in documentation mentions login_hint, scope, is_consent_required, binding_message and acr_values as post body parameters.

### Actual behavior

the authentication entity receives:
{"scope":"openid profile roles email","binding_message":"12345","login_hint":"user","is_consent_required":false,"grant_type":"urn:openid:params:grant-type:ciba","client_secret":"xxxxxxxxx","client_id":"client"}'

### How to Reproduce?

setup keycloak 17 with CIBA auth channel uri, in Dockerfile, set:
`ENV KC_SPI_CIBA_AUTH_CHANNEL_CIBA_HTTP_AUTH_CHANNEL_HTTP_AUTHENTICATION_CHANNEL_URI=http://host.docker.internal:5000/auth`

create dummy authentication entity server with /auth endpoint, dump the request payload.
configure test client and initiate a ciba grant.

**Comment by mposolda** [comment]
@wimvanboven Thanks for reporting this. I am adding label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to contribute the PR with fixing this (after it is investigated and confirmed that this is valid issue).

@tnorimat Pinging you just in case you want to take a look at this as it is CIBA related and maybe you know how to quickly investigate/fix this.

**Comment by tnorimat** [comment]
Hello @wimvanboven,
When you sent a backchannel authentication request to keycloak's backchannel authentication endpoint, did you include `client_id` and `client_secret` in the body of the request for client authentication, not using Authorization header?

**Comment by wimvanboven** [comment]
indeed, secret and id via post body.

**Comment by tnorimat** [comment]
@mposolda Could you review the [PR](https://github.com/keycloak/keycloak/pull/12263) for fixing this issue?

**Comment by wimvanboven** [comment]
you guys are awesome, keep it up
