### ISSUE TITLE
Incorrect get the members of a group imported from LDAP

### ISSUE THREAD

**Issue by BlackKerio** [keycloak/keycloak#11008]
### Describe the bug

I have created two user federations with LDAP (AD_1, AD_2). Imports Users is off.  Both of them will import groups using group-ldap-mapper.

When I try to get the members of a group existing in AD_2 and a user exists with the same username in AD_1, only the user AD_1 is displayed; which logically is not in a group existing only in AD_2.

### Version

17.0

### Expected behavior

Only users imported from a specific LDAP group will appear in the list of group members

### Anything else?

The user has the same username but the email is different.

**Comment by sguilhen** [comment]
I was able to reproduce the issue on Keycloak 20.0.1. Steps:

1- run the test LDAP server in testsuite/utils: `mvn exec:java -Pldap`  -> runs the LDAP server in port 10389, pre-loads test users, groups
2- run another LDAP server on a different port: `mvn exec:java -Pldap -Dldap.port=10390`
3- run Keycloak using the old admin console (new console seems to be missing ability to synch the groups): `./kc.sh start-dev --features-disabled=admin2 --features=admin`
4- using a tool like Apache Directory Studio, connect to the second LDAP server make changes to reflect the scenario described by the reporter:
     - edit the entry `jbrown` under `ou=People,dc=keycloak,dc=org`, changing the username to something else (e.g. `Julius` instead of `James`) and change the e-mail as well.
     - remove both group entries (`ldap-admin` and `ldap-user`) under `ou=RealmRoles`
     - add a new group (e.g. `ldap-tester` and add `jbrown` as a member`

At this point, the second LDAP server contains a different group, with a user that has the same username of another user in LDAP server 1, but different user data (e-mail, first name).

5- go to Keycloak admin console, setup both servers in User Federation (follow guidelines in `docs/tetests.md`, adjusting the connection URL of the second server).
- Import Users -> Off, Synch Registrations -> Off, Edit Mode -> READ_ONLY, UUID LDAP attribute -> entryuuid
6- in the `Mapper` tab, add the `group-ldap-mapper`, setting `LDAP Groups DN` to `ou=RealmRoles,dc=keycloak,dc=org`
7- click on `Synch LDAP Groups to Keycloak`

Once this is done for both servers, all the groups should be imported. Navigating to `Groups` in the admin console, one can see both groups from server 1 (`ldap-admin` and `ldap-user`), and also the group from server 2 (`ldap-tester`). 

Now, if we select one of the groups from server 1 and click on `Members`, it will display the wrong `jbrown` user, which was fetched from LDAP server 2.

**Comment by pedroigor** [comment]
@sguilhen Assigning you to review the priority. The reason why it is labeled as important is because the you were able to reproduce the issue and the behavior is not what we expect if the group mapper is properly configured.
