### ISSUE TITLE
Use dist Quarkus version in the operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#11015]
For the operator, we're currently [overriding](https://github.com/keycloak/keycloak/blob/8cd2c97982847b5bf322afb3423e3efbb7fa8fdb/operator/pom.xml#L36) the Quarkus version that is [set at project level](https://github.com/keycloak/keycloak/blob/8cd2c97982847b5bf322afb3423e3efbb7fa8fdb/pom.xml#L44) and used by the Quarkus dist. We should unify it and use a single version without any overrides.

The risk is potential incompatibilities with JOSDK that might bring fast Quarkus version updates.

**Comment by shawkins** [comment]
Initially addressed by #20264 and will be further addressed by #21078
