### ISSUE TITLE
Webauthn tests broke because of RP-Initiated logout changes

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#11030]
### Describe the bug

When `webauthn` profile is enabled, the build fails because of this change https://github.com/keycloak/keycloak/pull/10887/files#diff-d5b685a6252c811b513fe56a14293162007670a73851967b93e94711309dc995L60.

### Version

999-SNAPSHOT

### How to Reproduce?

Build the project using the `webauthn` profile.

**Comment by pedroigor** [comment]
@mposolda Could you please look at this one?

**Comment by mposolda** [comment]
@pedroigor Yes, I will take a look
