### ISSUE TITLE
Account console not functional when running KeyCloak behind a reverse proxy

### ISSUE THREAD

**Issue by FlyveHest** [keycloak/keycloak#11041]
### Describe the bug

I just setup my first install of KeyCloak, following the various guides in the documentation, but I have run into a problem (for which I also have the solution)

The problem is, then I try and access the account console on https://keycloak-server/realms/testrealm/account/ I get the "Account console is loading" going on forever.

If I check the Network tab, I can see that I get a 403 when trying to get keycloak.js, which is understandable, because I set it up that way based on the guide found here, https://www.keycloak.org/server/reverseproxy (I have a few requires in place in my apache conf to limit the paths that should not be exposed publicly)

When I access the page from a privileged IP that is not limited by apache, I can access the account console just fine.

So, my question is, is the guide wrong?  And if it isn't, how am I going to allow users to change their account related settings?

It does seem strange that if I run KeyCloak behind a proxy, I should limit some folders, but if I run it on a dedicated server, everything is fine.

### Version

17.0.1

### Expected behavior

A user accessing the account console from the public side of the reverse proxy can actually access it.

### Actual behavior

User can not access the account console 

### How to Reproduce?

Follow the reverse proxy setup guide, and try and access the account console.

### Anything else?

The fix is pretty clear, allow access to the /js/ folder, but someone wrote that guide for a reason, and I don't want to open up for potential security risks by ignoring it.

**Comment by ShivanKKP** [comment]
#10619 same issue?

**Comment by FlyveHest** [comment]
Looks like it, in that #10619 has not forwarded the /js/ folder as well. (But does have the /admin/ folder)

I think this is more of a documentation issue, than anything else.

**Comment by DGuhr** [comment]
Hey. Thanks for noticing the docs issue. I tried to clarify it in this PR #11122 could you please look if that works for you?

**Comment by FlyveHest** [comment]
Seems like a sound enough, change, but you might also want to revisit the javascript adapter docs https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter, text follows

> A best practice is to load the JavaScript adapter directly from Keycloak Server as it will automatically be updated when you upgrade the server.

The wording about not copying the adapter to your client, and then encouraging using the adapter from a package manager (which in essence is the same as copying the file) is somewhat confusing as well.

To me, a user who is trying to have my setup as secure as possible, having doubts about the best way to handle the adapter makes me feel unsafe.

**Comment by DGuhr** [comment]
@FlyveHest see https://github.com/keycloak/keycloak-documentation/pull/1448 ;)

**Comment by FlyveHest** [comment]
Perfect, that clears it up for me, at least.  Thank you for the fast response and clarification
