### ISSUE TITLE
Outdated documentation on cluster setup for v17.0.0 and 17.0.1

### ISSUE THREAD

**Issue by mimozell** [keycloak/keycloak#11062]
### Describe the bug

When looking at the documentation for setting up high availability clusters, e.g.: https://www.keycloak.org/docs/latest/server_installation/index.html#_standalone-ha-mode and https://www.keycloak.org/docs/latest/server_installation/index.html#_clustering, there are a lot of references to `standalone.xml`, `standalone-ha.xml` and `domain.xml`, under the `standalone` directory. When deploying a container using:
`FROM quay.io/keycloak/keycloak:17.0.1` or
`FROM quay.io/keycloak/keycloak:17.0.0`
there are no such files or directory.
![Screen Shot 2022-04-01 at 14 22 26](https://user-images.githubusercontent.com/40452559/161273238-ca90c22d-48ce-4566-90ef-c0c3680e9a58.png)
I'm wondering if something is missing on our container or if the documentation is out of date for the newer versions of KC. 

### Version

17.0.0 and 17.0.1

**Comment by raul-verdi** [comment]
Hi @mimozell, seems that you are using the Quarkus based Keycloak, but the docs you are reading are for the Widfly based one.

Quick summary, there are two Keycloak "versions" out there, the legacy Widfly based (which was deprecated as of 17), and the new Quarkus based one.
The documentation on this matter still a bit confusing IMO. Specially if you are new into keycloak. 

This guides https://www.keycloak.org/guides are up to date with the quarkus new way of doing things.

**Comment by mimozell** [comment]
Thanks @raul-verdi! I am aware of the differences, we had to do a painful migration from v16 :D I expected though that the documentation would be up to date for v17.0.1 (current latest) since the links point to `/latest/` and that is also highlighted in the screen.
<img width="1151" alt="Screen Shot 2022-04-04 at 10 17 10" src="https://user-images.githubusercontent.com/40452559/161503468-3e72ec4b-2412-4a77-baef-39173d7902ee.png">
Looks like the main relevant documentation for Quarkus-based versions is here: https://www.keycloak.org/server/configuration-production#_run_keycloak_in_a_cluster, which mainly points to this page: https://www.keycloak.org/server/caching.

**Comment by raul-verdi** [comment]
I am migrating from v15 myself. Yes, those are the latest docs. Some parts are shared, but most is not.

The main differences are in the configs, specially if you have custom setup of infinispan. In v16 (or v15 for that matter) the config was embedded in the same keycloak file. While in quarkus they use the config of infinispan.

I found out by navigating github issues, the jira tracker, and the source code. The source code has the guides for quarkus.

**Comment by stianst** [comment]
Check the top of the docs you're looking at:

![image](https://user-images.githubusercontent.com/2271511/164411504-687d6351-73f6-4bca-aabe-2136cdf412ba.png)

The documentation you are looking for is https://www.keycloak.org/guides
