### ISSUE TITLE
Blank admin console page in Keycloak 17.0.1

### ISSUE THREAD

**Issue by soundsessential** [keycloak/keycloak#11083]
### Describe the bug

Having set the port to be 443 using

```
# Use port 443
https-port=443
```

in the config file, the initial Keycloak page loads, then click "Administration Console", log in and then you are presented with a blank admin console page, with just the black header at the top.

This is not the case if port 443 is not specified. The initial page is reachable at keycloak.mydomain.com:8443, click admin console link, log in and admin console is ok.

### Version

17.0.1

### Expected behavior

Expect to see all the contents of the admin console as when using the default 8443 port.

### Actual behavior

Everything below the header is empty. In addition, clicking on the user "Admin" in the top right of the header and attempting to go to Manage Account fails.

### How to Reproduce?

You can pretty much follow these simple instructions and then move on to part 4 where port 443 is enabled:
https://www.soundsessential.com/blog/214-keycloak-17-filemaker-installation-configuration-tutorial-part-3-preparing-keycloak-17

Note, do not add the port number to the hostname for 17.0.1 in the config file in part 3 above.

It's pretty straightforward with MySQL, SSL, install Keycloak, set up config file (NOTE: NO PROXY IS SET UP), start Keycloak to test, shut it down, change port to 443, rebuild, reboot, start Keycloak, log in and error is encountered. 

It's built on Ubuntu 20.

### Anything else?

I have also been seeing some errors generated when initially logging in, such as:

`2022-04-02 14:54:45,722 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: java.lang.RuntimeException: java.io.IOException: Underlying input stream returned zero bytes`

I need to test further to see if these issues are related but adding here in case this means more to someone in the know!

If any additional details or testing is needed, happy to help so feel free to ask.

**Comment by raul-verdi** [comment]
Having port set up port `443`, then why do you use `8443` afterwards?
How are you deploying it? using docker containers?

**Comment by ShivanKKP** [comment]
@soundsessential please test with bowsertools open (press F12 button).

same as #10619  ?

**Comment by talyz** [comment]
I'm seeing the exact same thing trying to package the quarkus version for NixOS. When using port `443`, the admin console is empty except for the top menu bar. Selecting `Manage account` in the menu returns the error
```
Invalid parameter: redirect_uri
```
When switching to port `8443`, everything seems to work as expected.

@ShivanKKP This issue doesn't seem related to that issue. This happens when no reverse proxy is used. Looking at the network analysis in Firefox when loading the admin console, I see no relevant issues. `keycloak.js` is fetched fine. Inspecting the contents of the page just shows it as blank - the server simply returns an empty page and the browser loads it as expected.

**Comment by soundsessential** [comment]
> Having port set up port `443`, then why do you use `8443` afterwards?
> How are you deploying it? using docker containers?

Apologies this was not clear in the original post. The workflow in setting Keycloak up was:

- Install Ubuntu 20 on virtual machine - not docker
- Install MySQL
- Install Lets Encrypt certs
- Install OpenJDK
- Install Keycloak
- Adjust config file to add database, SSL paths and add hostname (no port on the end)
- Set environment variables for admin and start Keycloak
- Runs on port 8443 and all is ok
- Stop Keycloak, adjust config file to add port 443
- Reboot, start Keycloak
- Initial page is ok, login is ok, blank body section after login

I hope that is clearer now. The steps in the tutorial that was linked to in the original post is what was done. That worked with 17.0.0 without issue. I have found this issue when following those steps (however, do not add the port number to the hostname in 17.0.1) and this was reported to me by someone else following the tutorial, so it has been replicated multiple times. Again, there is no proxy involved here.

**Comment by soundsessential** [comment]
> @soundsessential please test with bowsertools open (press F12 button).

So I don't think this is the same as that issue - at least not the same set up. In browser tools, there are no errors in the console and looking under Elements in Chrome, the below is what I see. The body is essentially just not loading. 

@talyz seems to be experiencing the same as I do.

<img width="231" alt="Screen Shot 2022-04-04 at 7 12 53 AM" src="https://user-images.githubusercontent.com/4053754/161532574-01b96141-5ac4-426a-b404-f2a15d366f83.png">

**Comment by olivierlemasle** [comment]
Same issue here. It also works with 17.0.0, not with 17.0.1.
Also using port 443, and no proxy.

**Comment by pedroigor** [comment]
Can you try passing `--proxy edge` or any other value to the `proxy` option?

**Comment by pedroigor** [comment]
Could you also elaborate on why you are running the server without a proxy?

**Comment by soundsessential** [comment]
> Can you try passing `--proxy edge` or any other value to the `proxy` option?

Ok, so in the keycloak.conf file I enabled
```
# The proxy address forwarding mode if the server is behind a reverse proxy.
proxy=edge
```

This worked and the admin console rendered correctly. I then adjusted the value to this
```
# The proxy address forwarding mode if the server is behind a reverse proxy.
proxy=none
```

This also worked and the admin console rendered as expected. Finally, just for testing I adjusted the value to this:
```
# The proxy address forwarding mode if the server is behind a reverse proxy.
proxy=randomtext
```

This failed with a start error of
`2022-04-05 13:13:53,033 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Invalid value [randomtext] for configuration property [proxy].`

This last one is no doubt expected.



> Could you also elaborate on why you are running the server without a proxy?

Mmm... Good question. I guess I could respond with why shouldn't I run it without a proxy as it's set up to and capable of running without a proxy. In my instance I wanted to limit the complexity of the deployment and while setting up Nginx may be a simple thing for most people reading this, having another piece added to the Keycloak puzzle I figured would add another barrier, point of friction or resistance to adoption within our community. The simpler we can make it, the greater the adoption of Keycloak will be. Many of our users are not native Linux, so getting them to spin up a Linux machine and deal with the command line is a win in itself! 

All that said, thanks to everyone on the Keycloak X > 17 project because deployment (read adoption) is way way simpler! I can sell this concept way easier now.

So, back to the issue at hand - adding a proxy value results in Keycloak working correctly when there is no proxy. What to do about this? Is this something we should recommend to do in the installation process, if so what value should we recommend be added, or will there be a quick revision version issued where if the proxy value is commented out then Keycloak works as expected?

Many thanks and happy to test any further options.

**Comment by DGuhr** [comment]
Hi @soundsessential thanks to your steps I was finally able to reproduce this problem. 

It seems to have something to do with internal handling of standard ports and resteasy in the changes we made to the hostname provider. When we provide `443` as https-port value, the port should be set internally to `-1`, which suggests to use the standard port (443 == standard). But it's still set to 443, and this leads to the browser complaining as there's a mismatch between expected and actual URL (with and without 443). I'll provide a PR to fix this shortly, needs just a bit more testing here.

**Comment by wimdeblauwe** [comment]
I see the same issue with a blank admin console with just the black header in my installation using Keycloak 16.1.0. I have set the `KC_PROXY` environment variable to `edge`, but the issue seems to remain. Is there any way I can validate if the docker image has picked up this setting?

**Comment by PePTojr** [comment]
Hi, how many  instances keycloak you run?

https://www.keycloak.org/2019/05/keycloak-cluster-setup.html

may be this help  you





ср, 1 июн. 2022 г. в 14:50, Wim Deblauwe ***@***.***>:

**Comment by wimdeblauwe** [comment]
For others: I am using the legacy (non-quarkus) version of 18. The final fix was adding `X-Forwarded-For`, `X-Forwarded-Proto` and `X-Forwarded-Host` header to the Azure Application Gateway that in in front of the App Service that runs the Keycloak docker image.

**Comment by schrill** [comment]
[](url)Confirming the above, version's above 17.0.0 do not work with our current setup and result with a white admin page.
We are using a similar setup ALB with SSL termination and an ECS container and can confirm that present configuration works for version 17.0.0 without browser errors.
`start --auto-build --proxy=edge --hostname=${local.project_env}.${element(keys(dependency.zone.outputs.zone_id),1)} --http-relative-path=/${local.name_infix} --hostname-strict-https=true --metrics-enabled=true --log-level=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG --cache-config-file=cache-ispn-jdbc-ping.xml`
The above line is how we start the ephemeral containers, the entrypoint...
Both Version 19 error out with following error:
![Screenshot from 2022-08-25 16-04-35](https://user-images.githubusercontent.com/37488482/186686255-ea7b1dea-6d31-4be0-9215-75f2748bfda2.png)
![Screenshot from 2022-08-25 16-01-16](https://user-images.githubusercontent.com/37488482/186685647-eb9decff-3375-4a32-9cd6-ef3d89195e18.png)
Tried with current DB and auto migration and with a blank DB, resulting in the same error.
