### ISSUE TITLE
Can't initial admin user

### ISSUE THREAD

**Issue by AlexeiKlimenko** [keycloak/keycloak#11097]
### Describe the bug

Installed 17.0.1 on Debian 11 and configured with crt/key with hostname=%server%:8443
Start has been successfully worked with "Keycloak 17.0.1 on JVM (powered by Quarkus 2.7.5.Final) started in 11.023s. Listening on: https://0.0.0.0:8443"

At the https:/%server%:8443/  we receive message:
Open http://localhost:8080/auth
or use the add-user-keycloak script. 

But this link is unreachable and such script is absent. Also tried to set up admin/pass with variables (export KEYCLOAK_ADMIN/export KEYCLOAK_ADMIN_PASSWORD) before starting - but it doesn't work.

How to initial admin user ?

### Version

17.0.1

**Comment by LehouxKevin** [comment]
Hi,

if you have access to the server, then you can user this answer :

https://stackoverflow.com/a/71214731

Adapt your port, it worked for me.

**Comment by AlexeiKlimenko** [comment]
> Hi,
> 
> if you have access to the server, then you can use this answer :
> 
> https://stackoverflow.com/a/71214731
> 
> Adapt your port, it worked for me.

Yeah, it really helped.
Just install lynx and visit https:/%server%:8443
The invisible fields with admin account creation will be available via lynx.
