### ISSUE TITLE
Do not empty attributes if they are not provided when user profile is enabled

### ISSUE THREAD

**Issue by Alexander72** [keycloak/keycloak#11096]
### Describe the bug

When the user declarative profile feature is enabled, attributes that are defined in the User Profile are always present in the user attributes even if they are not set (Admin Panel -> Users -> user -> attibutes tab). 

Also, on an attempt to update a user through PUT endpoint attributes are removed from the user.

### Context
We are using ABAC model and make use of the Keycloak user attributes extensively. To prevent users from accessing areas they should not have access to by modifying their attributes we enabled the Declarative User Profile feature and disabled write access to all the important attributes for the users leavin read access only (via Admin Panel -> Realm settings -> User Profile tab -> Attributes subtab ->  attribute -> Permissions section -> Can user edit = FALSE,  Can user view = TRUE).
At the same time, administrators should have read and write access for those attributes (via Admin Panel -> Realm settings -> User Profile tab -> Attributes subtab ->  attribute -> Permissions section -> Can admin edit = TRUE,  Can admin view = TRUE). Attributes are not required in our case.

#### Problem 1
But when this is configured in this way, administrators can see attributes with empty values in the user attributes page (Admin Panel -> Users -> user -> Attributes tab) even if the attribute has not been set for the user. This is confusing for the administrators.

#### Problem 2
We make use of the Admin REST API to make some modifications on the users, for example, update email. But to make it happen it's necessary to send the whole user representation with all the attributes otherwise they will be removed. This makes it necessary to do GET user request first to get full user representation modify it by updating email address and send PUT request to make an update. This introduces unneccessary HTTP call that could be avoided (and can be avoided in case Declarative User Profile feature is disabled)

### Version

16.1.1

### Expected behavior

1. Attributes that are not set for a user are not shown in the Admin Panel -> Users -> user -> Attributes tab
2. On a request to the `PUT /auth/admin/realms/{realm}/users/{id}` endpoint without `attributes` field in the request body all existing user attributes must preserve as it works when User Declarative Profile Feature is disabled.

### Actual behavior

1. For users without attributes from the User Profile configuration fields are still shown on the user attributes tab in the Admin panel with an empty value
2. On a request to the `PUT /auth/admin/realms/{realm}/users/{id}` endpoint without `attributes` field in the request body all existing user attributes are removed when User Declarative Profile Feature is disabled.

### How to Reproduce?

1. Enable Declarative User Profile feature https://www.keycloak.org/docs/latest/server_admin/index.html#enabling-the-user-profile
2. Create a user with username `test`, email `test@test.com`, and **without any attributes**
3. Go to Admin Panel -> Realm settings -> User Profile tab -> Attributes subtab ->  click Create 
4. Create a new attribute with the following parameters and click save:
    a. name: test-attribute
    b. Required: FALSE
    c. Permissions -> Can admin edit: TRUE
    d. Permissions -> Can admin view = TRUE
    e. Permissions -> Can user edit: FALSE
    f. Permissions -> Can user view = TRUE    
5. Go to the user created on the Step 2 Admin Panel -> Users -> user with username `test` (from Step 2) -> Attributes tab
    a. `test-attribute` is shown with empty value even though it's not set for the user. (Actual behavior 1)
6. Set user attribute `test-attribute` value to `Test Value` and save the user
7. Make a PUT request to the `PUT /auth/admin/realms/{realm}/users/{id}` endpoint to update user email for the user created on the step 2. Payload: 
```json
{
    "email": "new-email@test.com"
}
```
8. Check user Admin Panel -> Users -> user with username `test` (from Step 2)
    a. User email has been updated to the `new-email@test.com` (expected), however, 
    b. on the User Attributes tab `test-attribute` value is empty (Actual behavior 2) even though it was not present in the PUT request. And this won't happen in case Declarative User Profile feature is not enabled

**Comment by pedroigor** [comment]
@Alexander72 We miss a `PATCH` method in our endpoints. That should ideally be the case for updating attributes as you are doing.

I agree we should try to align with the legacy user profile. I just need to make sure it won't break some assumptions from the new user profile.

**Comment by Alexander72** [comment]
@pedroigor Yeah, but from what I see, the current PUT endpoint works kind of as a PATCH. I agree, that there should be PATCH endpoint, but it means that the logic of the PUT endpoint needs to be changed, not sure what are the plans to keep backward compatibility for this particular endpoint, can imagine that there are many applications relying on the current PATCH-like logic of the PUT endpoint and it might be hard to change that.

What do you think if for now there will be a consistency for cases with enabled and disabled user profile, so when a request is sent attributes are preserved and not removed as it is currently for the disabled user profile (default)?

Let me know what are your thought and if you are okay with the proposal, I'm willing to contribute :+1:

**Comment by pedroigor** [comment]
@Alexander72 Thanks, we appreciate your contribution.

It should be a matter of checking if attributes should be removed when updating existing attributes. Something like that https://github.com/pedroigor/keycloak/tree/tmp-up.

Does it work for you?

**Comment by Alexander72** [comment]
@pedroigor yes, that would be a nice fix :+1: 

Also, some considerations about the Admin Panel: currently, in the GET user endpoint  (Admin REST API) all the readable attributes defined in the user profile (at the realm level) will be present in the response no matter whether they are set for the user or not. I see that this functionality was added relatively recent (in 2021) as part of this ticket: https://issues.redhat.com/browse/KEYCLOAK-18860

From my point of view, it's a bit confusing to see empty attributes that have not been set. And there might be a lot of them, for example, we use different attribute sets for different user types, but since all the readable attributes are present in the response administrators see attributes that do not belong to the user type. I think that only those attributes that are set for the user and that administrator has access to should be present in the response, not all the readable attributes from the user profile. 

Let me know if it was made on purpose and I miss something or if you agree with the approach. In the latter case I can open a PR to fix this if needed :smile:

**Comment by pedroigor** [comment]
It was kinda on purpose because it helps administrators to look at the attributes available from the user profile.

But yeah, this topic is basically a UX discussion. Ideally, the UI should be built based on the user profile metadata.

Consider the following situation. You add an attribute and mark it as required. You don't show it in the admin console (when empty). Now you try to save the user and you get an error message saying that the attribute is required.

By showing the empty attribute, the admin can just type the value.

We should probably involve @ssilvert in this discussion and see what works best for the new admin console.

**Comment by chehrhar** [comment]
@pedroigor, it's not only an UI issue. 

We enabled the user profile feature and discovered that one client which uses the REST API to read a user attribute got an Exception because the attribute was present but an emptry array, now.

Other clients accidentally deleted user attributes with a PUT-request. They only wanted to set user.enabled and relied on the PATCH-like logic.

**Comment by pedroigor** [comment]
@chehrhar Right now we don't support `PATCH` operations. So you need to push back all attributes to avoid them to be removed.

This is a general problem we have in other APIs too. Something we should definitely improve as per https://github.com/keycloak/keycloak-community/blob/main/design/rest-api-guideline.md.

**Comment by hmlnarik** [comment]
`PATCH`  operation can be implemented in several correct ways (union? override? intersection? for each set of fields / attributes) which are all meaningful for certain contexts; often a values in one attributes imply change in another value.

For that reason, apart from very simple operations, there is always a case when a user expects a semantics of `PATCH` which is different to the one implemented.

The only operation with clear semantics for complex datatypes is `PUT`, and for that reason the endpoint behaves as it should.

Thus I vote against any `PATCH` implementation.

cc/ @stianst

**Comment by pedroigor** [comment]
@hmlnarik I appreciate your feedback. Could you please move the discussion to the REST API Guidelines design document? It would be nice to update it accordingly.

**Comment by ssilvert** [comment]
> It was kinda on purpose because it helps administrators to look at the attributes available from the user profile.
> 
> But yeah, this topic is basically a UX discussion. Ideally, the UI should be built based on the user profile metadata.
> 
> Consider the following situation. You add an attribute and mark it as required. You don't show it in the admin console (when empty). Now you try to save the user and you get an error message saying that the attribute is required.
> 
> By showing the empty attribute, the admin can just type the value.
> 
> We should probably involve @ssilvert in this discussion and see what works best for the new admin console.

Regarding the admin UI portion of this discussion, we are just starting on an advanced design.  @agagancarczyk will do the implementation.

The way we plan to make it work is that any attribute defined as part of the user profile will not be displayed on the Attributes tab at all.   Instead, the field will be rendered on the Details tab.  This way, can use the definition of the attribute to improve the user experience.  For instance, an attribute that only has three valid values will be displayed as a dropdown.

If `Admin can edit` is false, attribute will display as read only.
If `Admin can view` is false, attribute will not be displayed.

For updates, I guess we will need to do the `PATCH` operation if you guys decide to implement it.

Also, I notice that attribute definitions should probably have a field for help text.  And we should think about localization for both help text and display name.

**Comment by pedroigor** [comment]
@ssilvert I need to check, but I think we can have help text by using attribute annotations.

Regarding the `PATCH`, we don't necessarily need it, I think.

**Comment by ssilvert** [comment]
@pedroigor We can definitely do help text using attributes.  But since help text definitely should be there for admin console and account console, it seems like it would make sense to use a pre-defined field.

If it's too painful to add a pre-defined field for it right now, I don't mind using attributes for the time being.

**Comment by ssilvert** [comment]
@pedroigor Let's do it then.  The UI changes are also trivial.  Just let me know when the back end is ready.

@agagancarczyk FYI.  ^^^

**Comment by pedroigor** [comment]
@Alexander72 Sent https://github.com/keycloak/keycloak/pull/13921. For now, keeping user profile consistent with the legacy behavior so that missing attributes do not have their values set to empty.

**Comment by daviddelannoy** [comment]
Hi @pedroigor 

I don't know if I should open another issue, but I also faced an inconsistent behaviour with other fields of UserRepresentation that have nothing to do with user attributes. 
Exemple on a realm in KC 19.0.1 : 

1. First test OK 
**Settings :** 
Email as username
Login with email
User Profile disabled

- Create a simple user 
access_token=$(curl -v http://localhost:8080/realms/master/protocol/openid-connect/token -d client_id=admin-cli -d grant_type=password -d username=admin -d password=admin|jq -r .access_token) 

curl -X POST 'http://localhost:8081/admin/realms/master/users' \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $access_token" --data-raw '{
    "username": "test@email.com",
    "email": "test@email.com",
    "enabled": "true",
    "firstName": "firstName",
    "lastName": "lastName",
    "requiredActions": ["UPDATE_PASSWORD"]
}'        

![image](https://user-images.githubusercontent.com/16318239/186116771-237268f8-17b0-4aa0-96e3-8d5cf454825d.png)

Let's say I want to clear requiredActions. I will use /users REST Admin API endpoint : 

`curl -X PUT "http://localhost:8081/admin/realms/master/users/983cd041-47ef-4bdd-a3ad-3efba01e29e9" --header 'Content-Type: application/json' --header "Authorization: Bearer $access_token" --data '{ "requiredActions":[] }'`

It works perfectly fined, `/users` endpoint acts as a PATCH and only clear required actions : 

![image](https://user-images.githubusercontent.com/16318239/186116998-ffd71e84-da99-4227-9910-562004f1c480.png)

2. Second test KO 
**Settings :** 
Email as username
Login with email
User Profile **enabled**

Then renew exactly the same test as before. After using `PUT` on any `UserRepresentation` field which is not part of user profile, all fields are cleared ! Even username, email ... account is broken.

![image](https://user-images.githubusercontent.com/16318239/186117536-6946f1c9-e773-405d-8232-db0dc5f3b231.png)

Of course it is fine if we use PUT as a PUT and do a GET before to send entire resource Representation. 

But I think that it is quite an inconsistent behaviour, I didn't see any warning on Admin REST API page regarding this difference with only **User Profile Enabled**

What do you think about it ? 

Thanks

**Comment by pedroigor** [comment]
@ioemat The proposed changes should also help with this and they are covered by the new tests. Did you run those steps using the branch from the proposed PR or the behavior is from upstream/main?

**Comment by daviddelannoy** [comment]
@pedroigor the question about tests is for me ? If yes, I made the tests from the upstream/main branch yes, not for the fix in this PR.

**Comment by pedroigor** [comment]
@daviddelannoy Thanks, it should be related to https://github.com/keycloak/keycloak-ui/issues/3180.

**Comment by daviddelannoy** [comment]
> @daviddelannoy Thanks, it should be related to [keycloak/keycloak-ui#3180](https://github.com/keycloak/keycloak-ui/issues/3180).

Hi @pedroigor 

I think that the REST API behavior I noticed is not linked directly with UI issue, only partially.

I can submit a new specific issue but I think current issue must be extended to consider other User attributes that are not part of User profile : 
**With User Profile enabled** 
- a `PUT` to `/users` to disable a user clear all user fields and breaks it :` { "enabled":"false" }`
- a `PUT` to `/users `to clear a user's required actions clear all user fields and breaks it : `{ "requiredActions":[] }`

**Comment by pedroigor** [comment]
For me, it makes more sense to create a separate issue. This one is only about not removing/resetting attributes if the `attributes` field is not set.

**Comment by daviddelannoy** [comment]
You're right, I will make a new one, already prepared it in fact :) thanks
