### ISSUE TITLE
Update to Quarkus 2.8.0

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#11100]
### Description

To stay up to date and catch possible update problems early on, we want the upstream distribution to use the current version quarkus uses. Current Quarkus upstream version is [2.8.0.Final](https://github.com/quarkusio/quarkus/releases/tag/2.8.0.Final) so we have to update Keycloak underlying Quarkus distribution to the new version.

Note: Don't forget to bump the packages used by Quarkus and Keycloak, found [here](https://github.com/keycloak/keycloak/blob/main/quarkus/pom.xml?rgh-link-date=2022-02-24T09%3A39%3A55Z#L40-L49) and [here](https://github.com/keycloak/keycloak/blob/main/pom.xml?rgh-link-date=2022-02-24T09%3A39%3A55Z#L38) for the bom version. The respective Quarkus versions can be found [here](https://github.com/quarkusio/quarkus/blob/2.8.0.Final/bom/application/pom.xml#L16-L212)

Description cloned from: https://github.com/keycloak/keycloak/issues/10437

**Comment by stianst** [comment]
For now we are not upgrading to Quarkus 2.8

**Comment by abstractj** [comment]
@stianst added the label "future", but feel free to close if you would like.

**Comment by stianst** [comment]
Closing as we're unlikely to upgrade to 2.8, but rather some other future version
