### ISSUE TITLE
Warnings when deploying my provider. “This SPI is internal and may change without notice”

### ISSUE THREAD

**Issue by hongquyen196** [keycloak/keycloak#11114]
### Describe the bug

When we implement the custom SPI to listen to events eg: create User. We refer to the official document from Keycloak SPI refer https://www.keycloak.org/docs/latest/server_development/index.html#_events

After we implemented it, the function is working. But I notice the warning in the console "This SPI is internal and may change without notice".

My understanding is either of these options below can be taken:
1. we follow official documentation from Keycloak and we SHOULD NOT receive this warning.
2. Keycloak removes this warning since it's suggested by Keycloak.

In case Keycloak DOES NOT want to fix that then we need to know so we can take further actions in our project.

### Version

17.0.0

### Expected behavior

No warning in the logs as long as we follow documentation of Keycloak [EventListenerProvider](https://www.keycloak.org/docs/latest/server_development/index.html#_events)

### Actual behavior

```
Updating the configuration and installing your custom providers, if any. Please wait.
2022-03-30 06:43:34,311 WARN  [org.keycloak.services] (build-14) KC-SERVICES0047: extension (com.test.KeycloakExtensionConfigurationProviderFactory) is implementing the internal SPI realm-restapi-extension. This SPI is internal and may change without notice
2022-03-30 06:43:35,720 WARN  [org.keycloak.services] (build-14) KC-SERVICES0047: user-management (com.test.KeycloakEventListenerProviderFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
2022-03-30 06:43:45,451 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 16082ms
```

My project is worrying that the keycloak-server-spi-private dependency able to break change API in the future.

### Anything else?

https://keycloak.discourse.group/t/warnings-when-deploying-my-provider-this-spi-is-internal-and-may-change-without-notice/12260

**Comment by DGuhr** [comment]
@stianst i think this issue is related to https://github.com/keycloak/keycloak/issues/9277 where we should clean up and look what should be in the non-private bom and what should be in the private bom, wdyt? If so, I suggest we close this issue and add a link to #9277 instead.

**Comment by pedroigor** [comment]
@hongquyen196 This SPI is marked as internal/private. Although commonly used, these SPIs are still marked as private.

It has been a long time since when they exist and so far they did not change. When it happens, we should involve the community in the discussions and build a migration plan accordingly.

IMO, these SPIs are more likely to not change anytime soon.

@DGuhr Not sure if it is related to #9277. There we are talking about BOMs and not really changing status of SPIs.

**Comment by hongquyen196** [comment]
Thank you for your feedback.
