### ISSUE TITLE
/clients-registrations API doesn't return secret anymore and is not coherent

### ISSUE THREAD

**Issue by Cracky5457** [keycloak/keycloak#11116]
### Describe the bug

Hello,

When when a user create an OIDC Client using endpoint POST `/clients-registrations/default/` a client secret is not generated anymore with keycloak 15. It was with keycloak 11 very same call. No secret provided in the json, if I provide as secret it works but I want to let the API generate one.

If I do a PUT after on `/clients-registrations/default/{clientId}` with still no secret in the json, a secret is generated by the PUT api ! It's not coherent with the POST.

So only way for a user to know their client secret so far is to perform a useless PUT.

### Version

15.1.1

### Expected behavior

POST should generate a Secret

### Actual behavior
POST Doesnt generate a Secret
GET doesnt return the secret after a POST
PUT generate the secret
GET return the secret after a PUT

### How to Reproduce?

```
response = requests.post(
    'https://your_domain.com/auth/realms/your_realm/clients-registrations/default/',
    headers={'Authorization': 'Bearer %s' % your_valid_access_token},
    json={
        "clientId": "test_client",
        "name": "My Service Name",
        "description": "This describes what my app is for end users",
        "rootUrl": "https://root.url.of.my.app",
        "redirectUris": [
            "https://fullLoginPath",
            "/relative/redirect/path",
            "/these/can/use/wildcards/*"
        ],
        "defaultClientScopes":["openid"],
        "optionalClientScopes":["microprofile-jwt"],
        "webOrigins": ["+"],
        "bearerOnly": False,
        "consentRequired": True,
        "standardFlowEnabled": True,
        "implicitFlowEnabled": False,
        "directAccessGrantsEnabled": False,
    })
    ```

**Comment by vgobrecht** [comment]
Looks like we need to use the admin api endpoint to ask keycloak to generate the secret. POST /auth/admin/realms/{realm}/clients/{client_id}/client-secret

**Comment by vgobrecht** [comment]
Look's like the PUT doesn't return the secret in response. You have to execute a GET `/clients-registrations/default/{clientId}` to get the secret.

**Comment by Cracky5457** [comment]
Ha maybe thanks for checking, but the PUT is at least generating the secret.

If you do the post and check in the UI admin panel there is no secret,
If you do the PUT, maybe it's not returned but the secret is generated and present in the UI
Then the GET return the secret generated by the put, but if you GET without doing a PUT first even the GET will return a secret "null"

**Comment by mposolda** [comment]
I confirm that this is a valid issue and ideally it should be fixed. It seems that this is the issue for both default client registration provider and admin REST API.

List of scenarios and how I think it should work:

1. When I am sending request with curl to "default" client registration provider, the secret is not set (note KC_TOKEN must be set to the valid access token) and hence it is also not returned from the response:
```
export KC_REALM=master
curl -L -X POST "http://localhost:8081/auth/realms/$KC_REALM/clients-registrations/default/" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $KC_TOKEN" \
-d '{
        "clientId": "test_client_5",
        "name": "My Service Name",
        "description": "This describes what my app is for end users",
        "rootUrl": "https://root.url.of.my.app",
        "redirectUris": [
            "https://fullLoginPath"
        ],      
        "bearerOnly": false,
        "publicClient": false,
        "consentRequired": true,
        "standardFlowEnabled": true,
        "implicitFlowEnabled": false,
        "directAccessGrantsEnabled": false
    })'
```

Expected output: Secret should be generated and returned in the response for such a request.

2. Similarly admin REST API currently does not generate a secret to the client. (Same request as above with the exception that URL is http://localhost:8081/auth/admin/realms/$KC_REALM/clients/ ) . When the POST request with admin REST API is send and it contains `"publicClient": false` and `"bearerOnly": false`, then it should generate a secret for the client.

3. When the request is sent to the "default" client registration or admin REST API with `publicClient: true`, then it should make sure that secret is NOT generated and returned (this currently works, but will be good to still test that scenario to make sure that fix does not break it)

4. When the PUT request is sent and it updates client, which was public, to the confidential, then the secret should also be generated and returned.

5. When the PUT request is sent and it updates client, which was confidential, to the public, then the secret should NOT be returned

**Comment by mposolda** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/11897 . Will be probably good to fix these 2 together.

**Comment by pedro-hos** [comment]
Hello @mposolda sent the PR https://github.com/keycloak/keycloak/pull/12195, fixing also #11897 and #11248. I was not able to squash, I don't know if I have done something wrong here, but the commits wasn't merged after the rebase/squash
