### ISSUE TITLE
OpenId configuration showing keycloak as host and 8080 as port for token and cert URL

### ISSUE THREAD

**Issue by ashishkumar-07** [keycloak/keycloak#11130]
### Describe the bug

When running as docker image well known open ID configuration is incorrect for certian URLs. Please see below snap shot

{
	"issuer": "https://{valid host URL}/realms/master",
	"authorization_endpoint": "https://{valid host URL}/realms/master/protocol/openid-connect/auth",
	"token_endpoint": "http://**keycloak:8080/**realms/master/protocol/openid-connect/token",
	"introspection_endpoint": "http://keycloak:8080/realms/master/protocol/openid-connect/token/introspect",
	"userinfo_endpoint": "http://**keycloak:8080**/realms/master/protocol/openid-connect/userinfo",
	"end_session_endpoint": "https://{valid host URL}/realms/master/protocol/openid-connect/logout",
	"frontchannel_logout_session_supported": true,
	"frontchannel_logout_supported": true,
	"jwks_uri": "http://**keycloak:8080**/realms/master/protocol/openid-connect/certs",
	"check_session_iframe": "https://{valid host URL}/realms/master/protocol/openid-connect/login-status-iframe.html",
	"grant_types_supported": [

### Version

17.0.0

### Expected behavior

All Open ID URLs should have same host value

### Actual behavior

Some open ID URLs in well know configuration are showing keycloak:8080 as host URL which looks a dummy wrong URL.

**Comment by SagenKoder** [comment]
Hi, I seems to have the same issue and have no idea what I could have done wrong or when this would be useful.

From the file: .well-known/openid-configuration

https://pastebin.com/pifa86kL

Some of the endpoints point to the correct uri (`https://secure.[REDACTED]/realms/[REDACTED]/protocol/openid-connect/token`) and some point to the wrong uri (`https://[REDACTED]/realms/[REDACTED]/protocol/openid-connect/auth`).

**Comment by stianst** [comment]
This is intentional as "internal" clients can communicate directly to Keycloak in some cases, which means backchannel URLs are taken from the request-url.

You can force the backchannel URLs to be the same as frontend URLs by setting `hostname-strict-backchannel`. See https://www.keycloak.org/server/hostname#_relevant_options
