### ISSUE TITLE
The associated policies of a resource returns wrong policies

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#11148]
### Describe the bug

See the bug reported here on the UI: https://github.com/keycloak/keycloak-admin-ui/issues/2386
Import the `temp` client of the attached json and see the error in the screen.

### Version

17.0.0

### Expected behavior

Should only return the policies belonging to the resource

**Comment by pedroigor** [comment]
@edewit Can you please confirm the evaluation is correct and using the permission attached to each resource?

**Comment by hean0224** [comment]
> @edewit Can you please confirm the evaluation is correct and using the permission attached to each resource?

Yes, please do and thank you for looking into the issue.

**Comment by edewit** [comment]
I'm not sure what you are asking, but I think this is really an issue.

**Comment by pedroigor** [comment]
@edewit Yes, I think so too. What I'm asking is if the policy evaluation is considering the expected permissions and working as expected.

The policies used during the evaluation are different than those obtained from the `{resource}/permissions` endpoint.

**Comment by edewit** [comment]
Okay I've tried that and as far as I can tell it seems to be right in the evaluate tab

**Comment by pedroigor** [comment]
Thanks. The fix is ready and waiting to be merged.
