### ISSUE TITLE
Could not create folder for password blacklists

### ISSUE THREAD

**Issue by jaap3** [keycloak/keycloak#11151]
### Describe the bug

I'm trying to move over from Keycloak 16 to Keycloak 17 using the official docker image. I have an existing realm, and get the following error:

```
[org.keycloak.policy.BlacklistPasswordPolicyProviderFactory] (executor-thread-0) Could not create folder for password blacklists: null/password-blacklists/
```

I've seen that I'm not the only one that sees this behaviour:

https://keycloak.discourse.group/t/kc17-providing-password-blacklist/14407

### Version

17.0.1

**Comment by jaap3** [comment]
I was able to work around this by starting Keycloak with the following flag: `-Dkeycloak.password.blacklists.path=/opt/keycloak/config/` and putting the `common-passwords.txt` file in that directory

**Comment by DGuhr** [comment]
Hi @jaap3 glad you found a workaround. FYI: there's a bugfix for this behaviour already in, targeted for Keycloak 18. See https://github.com/keycloak/keycloak/issues/10608 for details. 

I'll close here for now.

Best regards
