### ISSUE TITLE
Regression : GET /groups API with search doesn't return leaf subGroups

### ISSUE THREAD

**Issue by Cracky5457** [keycloak/keycloak#11167]
### Describe the bug

If you use the GET /groups API

https://domain/auth/admin/realms/realm/groups?first=0&max=20&search=all

it will return lets say

- all
  - countries
  
 If you search
 
 https://domain/auth/admin/realms/realm/groups?first=0&max=20
 
 - all
   - countries
       - uk
       - france
       - spain
     
     
 So basically, every `leaf` in the groups tree is not returned in `subGroups` attribute when a search value is specified
 
 It's a regression that was not the case in keycloak 11
 

### Version

15.1.1

### Expected behavior

GET /groups with `search` query params should return a complete json tree including leaf, or at least the searched node with its subGroups

### Actual behavior

GET /groups with `search` query params return a JSON without last subGroups of the tree (without leaf)

### How to Reproduce?

In you keycloak admin panel you can just display your groups with or without search and the result will be different for the leaf

**Comment by ynojima** [comment]
It seems this is an intended behavior change introduced in https://issues.redhat.com/browse/KEYCLOAK-18380.

In the keycloak-dev discussion, the issue reporter states "The current implementation of group search by name pattern yields unexpected results ...
Groups that are contained in intermediary nodes along a group path are returned by the search, even if they don't match the search pattern."
https://groups.google.com/g/keycloak-dev/c/xnpjefeoIkQ/m/YplnKYQABAAJ

In KEYCLOAK-18380 example, 
The group "g4-bubu/g4.1-lala" is excluded from the expected "bubu" search result.

@hmlnarik,  Could you confirm this is an intended behavior change?

**Comment by Cracky5457** [comment]
Even in that case this doesn't works well, for me the current behavior is almost as not accurate that the old one, including the disparition of the leaf, if I search for a group I except child of this group too like it was. If the intended goal is to not include them, maybe so a queryParam `includeChild=true` should be added ?

Anyway this new intended behavior doesn't works either, you can try with a more complex tree it will still return all the results including several level of child, even several groups at the same level, very same results that before just without the leaf.

**Comment by ynojima** [comment]
I understand your point. Thanks.

**Comment by hmlnarik** [comment]
Seems to be caused by #8134. The expected behaviour of https://github.com/keycloak/keycloak/issues/11167#issuecomment-1181569272 would be to return only

* Groups
   *  TestRoots

**Comment by thomasdarimont** [comment]
@hmlnarik thanks for the heads up I'll take a look at this by the end of the day.

**Comment by nicolasfeyer** [comment]
Any update on this one ?

**Comment by pedroigor** [comment]
We had several changes to the Group API. Please, check the latest version.

One of the key changes are about performance improvements and returning sub-groups is now done differently too.

**Comment by Cracky5457** [comment]
Indeed this issue should probably be claused now. The new API is nice and far more efficient.

Just, be careful to add theses API changes in the release note ( maybe I missed them ) because they may be broker changes for a lot of users and even for some library manipulating groups ( ansible etc. )

**Comment by pedroigor** [comment]
@Cracky5457 Yeah, we need to do a better job when updating release notes. But I think we have some references in the release notes. See https://www.keycloak.org/docs/24.0.1/release_notes/#group-scalability.

We can do better :)
