### ISSUE TITLE
Documentation regarding TLS configuration is incomplete

### ISSUE THREAD

**Issue by alt-enio** [keycloak/keycloak#11168]
### Description

The section in the following link deals with setting up Keycloak to use HTTPS:
https://www.keycloak.org/docs/latest/server_installation/#enabling-ssl-https-for-the-keycloak-server

However it only tells the story of getting a new certificate from scratch. What about users that already have an existing certificate, namely in a pfx file? For this case, the user should use a different _keytool_ command to import the pfx file into the keystore. (Or use it directly as a keystore.)

### Motivation

The number of users that are setting up a Keycloak server but already have a key pair to handle HTTPS is probably not negligible.

### Details

The documentation should mention the alternative way to set up a certificate (actually a key pair) to handle HTTPS. This is for the case where the user already has that certificate and just wants to import it into the keystore to be used by Keycloak.
In this case, the command to use with _keytool_ is **-importkeystore**. The **-import** command only allows to import the X.509 certificate. (Also it probably should be updated to **-importcert**, since **-import** seems to be deprecated).

Also it might be worth mentioning that if the user has separate files for the private key and the public certificate (instead of a single pfx file), he has to join them in a pfx (or p12) file before importing into the keystore.

Also the configuration command  `/subsystem=elytron/server-ssl-context=httpsSSC:add(key-manager=httpsKM,protocols=[\"TLSv1.3\"])` shouldn't have quotes around the TLS version. At least for me it only works without quotes.

**Comment by pedroigor** [comment]
@alt-enio I'm not sure if we are going so deep on how to create a keystore. The documentation is more focused on the steps to configure the keystore itself to enable TLS to the server.

However, if you are interested in contributing more information about this in the new [TLS guide](https://www.keycloak.org/server/enabletls). These guides are targeted for the Quarkus distribution.

**Comment by alt-enio** [comment]
I'm aware of the guides for the new version. I found no problem with the TLS guide. It even allows both the use of a either a keystore or separate certificate and key.

I can only argument that the older guide is still the most recent for Keycloak versions prior to 17. People might still want to set up an old version for testing purposes, for example.

**Comment by shawkins** [comment]
Out of date as it's based upon the Wildfly distribution. In addition to the tls guide mentioned above, mutiple pfx files are supported via truststore-paths, and #33278 is adding a tls guide as well.
