### ISSUE TITLE
UserInfo endpoint does not accept access_token as URI query parameter

### ISSUE THREAD

**Issue by jvanhill** [keycloak/keycloak#11177]
### Describe the bug

The UserInfo endpoint does not accept the access_token as a URI query parameter as part of a GET request. It appears to accept the token fine if the access_token is included in a form-encoded body parameter.

### Version

16.1.1

### Expected behavior

The endpoint should accept the access_token from the URI query parameter and return the user info.

### Actual behavior

The endpoint returns a `400 BAD REQUEST` and the following JSON:

```
{"error":"invalid_request","error_description":"Token not provided"}
```

### How to Reproduce?

When passing the access token to the user info endpoint, pass it using the access_token URI query parameter.

### Anything else?

Produced this error in the `jboss/keycloak` image published to Docker Hub (https://hub.docker.com/r/jboss/keycloak/)

**Comment by mposolda** [comment]
@jvanhill We accept access token only in HTTP "Authorization" header right now. This is also for security reasons as sending tokens in the query parameters is not good from security reasons.

Is it an issue to send the token in the "Authorization: Bearer <your-token>" HTTP header as specified in the https://datatracker.ietf.org/doc/html/rfc6750#section-2.1 . That should work for both GET and POST requests.

**Comment by mposolda** [comment]
I am closing as there is a way to send access token in the GET request and I think we are likely not going to add support for accepting as query parameter.
