### ISSUE TITLE
Theme resources are not loaded correctlyusing quarking when having multiple providers

### ISSUE THREAD

**Issue by jmuis** [keycloak/keycloak#11186]
### Describe the bug

When having multiple providers delivering themes resources containing messages only the first 'seen' provider get its messages loaded, all other providers are ignored. This seems to be related to the quarkus build configuration where only a single message bundle gets processed. 

### Version

17.0.1

### Expected behavior

Load message bundles from all providers

### Actual behavior

Only a single message bundle gets loaded (the first provider seen by the quarkus build)

### How to Reproduce?

Create 2 e.g. authentication providers each containing a theme-resources folder
First provider: 
Add template folder and add template-1.ftl
Add message folder and add messages_en.properties
Implement authentication provider and factory running a form challenge rendering template-1
Build and copy jar to keycloak providers  directory

Second provider:
Add template folder and add template-2.ftl 
Add message folder and add messages_en.properties
Implement authentication provider and factory running a form challenge rendering template-2
Build and copy jar to keycloak providers directory 

Start keycloak  (./kc.[bat|sh] start-dev)
Configure the browser flow authentication flow containing an execution on provider 1
Try login
Messages from the message bundle may be shown properly or the message key is visible (issue triggered, stop here)
Change the browser flow authentication removing provider 1 and adding provider 2
Try login
Messages from the message bundle are shown by their message key.

**Comment by pedroigor** [comment]
@jmuis Thanks. It should be fixed by https://github.com/keycloak/keycloak/issues/10951.

**Comment by shawnritchie** [comment]
- We're experiencing the same issue on version 18.0.0, when loading multiple SPIs, only the messages_en.properties from the first SPI is loaded the others are ignores and hence the templates aren't rendered correctly.

File structure of the SPIs
- resources
    - theme-resources
        - messages
            messages_en.properties
        - templates
            - html
                email.ftl
            - text
                email.ftl
            login.ftl

**Comment by pedroigor** [comment]
@jmuis I missed the change here https://github.com/keycloak/keycloak/pull/11711 to make it possible to also load multiple message bundles from the classpath.

If you could try it out, I appreciate it.

Now that we are using a flat classpath, providers should take additional care when choosing a message key so that they don't overlap.

This might be a breaking change for some people if the same key (with different values) is used by different providers. I'm not 100% sure yet how to achieve better isolation. I'm going to start a discussion around this topic.

**Comment by jmuis** [comment]
@pedroigor Unfortunately I can't make a build of Keycloak a.t.m. based on this change, so testing it is a bit difficult over the next couple of days. However, I did review the change you did and that looks ok to me. Yes, agree, there still is a potential issue having key conflicts, but on the other hand, wasn't that always the case as well with WildfFly as you override message keys through a theme, not per provider?

**Comment by pedroigor** [comment]
@jmuis Sorry for the confusion.

Yes, the behavior is expected. It is how it works in legacy.
