### ISSUE TITLE
Translation of administration button "View all groups" is missing

### ISSUE THREAD

**Issue by zeniel** [keycloak/keycloak#11194]
### Describe the bug

When I use locale pt_BR the button "View all groups" is not translated to portuguese, looking at the admin-messages_pt_BR.properties the button identifier is missing, so it needs to create a new line in this file like this:

`view-all-groups=Exibir todos os grupos
`

### Version

17.0.1

### Expected behavior

When the administration opens the groups menu:
http://<keycloak-base-url>/auth/admin/master/console/#/realms/master/groups using locate pt_BR, he must see the button "View all groups" with the translated text: "Exibir todos os grupos".

### Actual behavior

When the administration opens the groups menu:
http://<keycloak-base-url>/auth/admin/master/console/#/realms/master/groups using locate pt_BR, he actually see the button "View all groups" in english.

### How to Reproduce?

Administrator user has to open the groups menu:
http://<keycloak-base-url>/auth/admin/master/console/#/realms/master/groups using locate pt_BR and check the view all groups button.

**Comment by lexcao** [comment]
Hi, I create a PR to fix it.
https://github.com/keycloak/keycloak/pull/12482
