### ISSUE TITLE
Operator CI is broken reporting docker login failures

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#11206]
### Describe the bug

The Operator CI workflow is reporting login failures while running `docker login`. 

### Version

17.0.1

### How to Reproduce?

A few examples: 

- https://github.com/keycloak/keycloak/runs/5890690824?check_suite_focus=true
- https://github.com/keycloak/keycloak/runs/5892142025?check_suite_focus=true
- https://github.com/keycloak/keycloak/runs/5887096987?check_suite_focus=true

**Comment by abstractj** [comment]
FYI @vmuzikar @andreaTP

**Comment by vmuzikar** [comment]
It looks like the Secrets are completely missing from the workflows:
```
Error: Username and password required
```
I believe, this is the root cause:
>Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

Reference: https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by vmuzikar** [comment]
I'm afraid, we'll need to use [Ok-to-test](https://github.com/imjohnbo/ok-to-test).

**Comment by vmuzikar** [comment]
I'd suggest we revert the [breaking change](https://github.com/keycloak/keycloak/pull/10949/commits) and reintroduce it with ok-to-test in a separate PR. Alternative solution would be to run OLM tests only nightly. Or somehow avoid using Quay whatsoever. WDYT, @andreaTP?

**Comment by andreaTP** [comment]
For visibility: I'm working to have a fix on top by EOD.
