### ISSUE TITLE
ConstraintViolationException being thrown from RoleDecorator

### ISSUE THREAD

**Issue by btarhan** [keycloak/keycloak#11222]
### Describe the bug

We recently removed some customizations around our RoleDecorator class, which means we are now using the keycloak version of these classes. After this change, we noticed some ConstraintViolationExceptions popping up in our logs. There are not many of them (maybe a dozen or so per day), but it appears to be caused by a race condition that is related to the Hibernate Flush strategy. When running locally, if we switched the flush policy to Auto, the error was moved to a different class, so this may be a larger issue as well. We feel like after our initial analysis we have exhausted what information we can find, and would like to engage others to help with this investigation.

### Version

7.5.6

### Expected behavior

Adding roles will not result in this ContraintViolationException, and threads will be able to correctly tell which roles have been added to a user already.

### Actual behavior

In rare cases, a race condition is set that causes threads to attempt to add roles that have already been added to a user.

### How to Reproduce?

Hard to reproduce in the wild as we have been unable to determine a cause, however we have integration tests that will trigger this every time if you need a stack trace.

**Comment by hmlnarik** [comment]
There is no `RoleDecorator` class in Keycloak, thus rejecting this issue.
