### ISSUE TITLE
Node.js adapter tests failure in the test pipeline

### ISSUE THREAD

**Issue by leonardobrancalhao** [keycloak/keycloak#11234]
https://keycloak-jenkins/job/universal-test-pipeline-adapters/954/testReport/

Several errors with nodejs 12 and 14

**Comment by mabartos** [comment]
There were some changes in the Node.js adapter repository.
Pipeline MR: https://keycloak-gitlab.com/keycloak/keycloak-pipeline/-/merge_requests/142

**Comment by mabartos** [comment]
It should be resolved with the recent changes in the [keycloak-nodejs-connect](https://github.com/keycloak/keycloak-nodejs-connect) repository. I'll execute one test run in order to verify it.

**Comment by mabartos** [comment]
Not relevant anymore
