### ISSUE TITLE
/users/count endpoint returns non json response

### ISSUE THREAD

**Issue by lejsekt** [keycloak/keycloak#11238]
### Describe the bug

Hi,
I've been playing around with the Keycloak REST API and I've found that the count endpoints return inconsistent responses:

GET /admin/realms/{realm}/groups/count
example response: { "count": 42 }

GET /admin/realms/{realm}/users/count
example response: 42

### Version

17.0.0

### Expected behavior

/users/count should return a JSON response.

### Actual behavior

/users/count just returns a number.

**Comment by rmartinc** [comment]
Number "42" is a valid JSON value, not a valid JSON object, but a valid JSON value you can parse normally. You are right about the inconsistency with the groups endpoint. But modifying this means changing the API that is being used right now. The documentation also states that the response of that endpoint is an integer. I suppose we can create another endpoint, or adding an attribute to produce the same JSON object used in groups to be compatible.

I don't think this is a major issue so if someone wants to work on it any PR would be much appreciated.

**Comment by pedroigor** [comment]
We are not changing the API contract for the reasons mentioned by @rmartinc. It does not pay off the cost of breaking existing deployments.
