### ISSUE TITLE
Usage of multiple providers with default for SPI only possible under certain conditions

### ISSUE THREAD

**Issue by deryoman** [keycloak/keycloak#11239]
### Describe the bug

I added a custom implementation of [EmailTemplateProvider](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/email/EmailTemplateProvider.java) and want to use it explicitly in certain use cases via `session.getProvider(EmailTemplateProvider.class, "my-custom-provider")`

Doing so let all calls of `session.getProvider(EmailTemplateProvider.class)` return `null`, because no default provider for `EmailTemplateProvider` is set.

I want the built-in [FreeMarkerEmailTemplateProvider](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java) to be the default provider, so I set it as the default provider via: `/subsystem=keycloak-server/spi=emailTemplate/:add(default-provider=freemarker)`

Now the custom implementation is not loaded at all and calling `session.getProvider(EmailTemplateProvider.class, "my-custom-provider")` returns `null`

This is due the implementation of the `loadFactories` method in [DefaultKeycloakSessionFactory](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java) which only loads the provider set as default in the config.

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L272-L292

When not defining a default provider the method `checkProvider` in [DefaultKeycloakSessionFactory](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java) tries to identify the default provider:

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L237-L251

But if the name of the provider is not "default" (which is not the case for FreeMarkerEmailTemplateProvider) no default provider will be set.

### Version

17.0.0

### Expected behavior

Being able to set a default provider of a SPI and use other implementations of the same SPI explicitly

### Actual behavior

Its not possible to set a default provider of a SPI and use other implementations when the name of the default provider is != "default"

### How to Reproduce?

Add a custom implementation of [EmailTemplateProvider](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/email/EmailTemplateProvider.java) 

Set [FreeMarkerEmailTemplateProvider](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java) as the default provider

Try to use the custom implementation explicitly: `session.getProvider(EmailTemplateProvider.class, "my-custom-provider")`

**Comment by pedroigor** [comment]
@deryoman What you can try is to set the `order` in your provider to `-1` and see if the default provider is registered as the default.

**Comment by pedroigor** [comment]
Please, let me know if this error is still relevant.
