### ISSUE TITLE
Editing user attributes in admin saves empty strings in storage when user profile is enabled

### ISSUE THREAD

**Issue by regilero** [keycloak/keycloak#11240]
### Describe the bug

If I do NOT enable the user profile for a realm, adding an empty user attribute in user edition makes a PUT request where this field is not pushed.

If I DO enable the user profile, all profile fields are added on the attributes list, and all attributes are pushed in the PUT request, even with empty fields (sending empty strings which are then saved).

This may also be related to behavior fixed in [KEYCLOAK-18916](https://issues.redhat.com/browse/KEYCLOAK-18916) with conflicting empty attributes for attributes that the admin should be able to edit.

In my case I have a lot of attributes, linked to user attribute mappers, and after user profile activation all these attributes are now in the access tokens, with empty strings, which is annoying.

### Version

16

### Expected behavior

Updating the user attribute via the REST API allows for empty arrays which are fine and the fields do not appear in the tokens, but after any edition via the user attributes interface in keycloak ui all attributes are back as arrays with one empty string.
* Enable the User profile special feature
* Create a user profile with at least two attributes 'Foo' and 'Bar', allow edition of attributes
* Create two user attribute mappers to see the attributes (or absence of it) in a token. I use 'example.bar' and 'example.foo' in token claim names and 'multivalued'
* Edit one user (in admin view, user attribute panel) and set a value to only 'Foo' attribute
* In the final OIDC tokens we should only get the example.foo attribute, and example.foo should remain absent.

### Actual behavior

* example.foo and example.bar are both available in the token, with a value `[""]` for example.bar. 

### Anything else?

previoulsy reported on [Jira](https://issues.redhat.com/browse/KEYCLOAK-19810)

**Comment by pedroigor** [comment]
@regilero I was not able to reproduce using `17.0.1`.

I tried to follow the same steps and in the end, I get an access token with the attribute I set only.

Would mind trying it out using the same version?

**Comment by regilero** [comment]
Seems they were a lot of changes in the attributes editor in v17. I'll test it and report back.

**Comment by regilero** [comment]
Cannot reproduce on V17. So closing
