### ISSUE TITLE
register.formData custom attribute multi select issue on validation error

### ISSUE THREAD

**Issue by olivierb2** [keycloak/keycloak#11269]
### Describe the bug

I wish to use multi select custom attribute in my form and despite keycloak saves correctly the multi select value into user attribute (with expected format `value1##value2`), the value returned into `register.formData['user.attributes.myattribute']` only return the first value in case of form validation error.

### Version

7.0.1

### Expected behavior

I'm expecting to have an ArrayList with all values so I can properly use it into my Freemarker in order to give back the previous selected values to user in case of the form is not validated on the first time.

### Actual behavior

It currently returns only the first value into `register.formData['user.attributes.myattribute']`as String.

### How to Reproduce?

Create a custom register.ftl form and use the following component. Fill only this new field with two values and try to register. The value returned into user.attributes.myattribute will only contains the first choice.

~~~
            ${(user.attributes.myattribute)!''}
            
            
            <#assign myAttribute = { "my-value-1": "My Value 1",
                                         "my-value-2": "My Value 2",
                                         "my-value-3": "My Value 3"}>
                                         
                                         
             <div class="${properties.kcFormGroupClass!}">
                <div class="${properties.kcLabelWrapperClass!}">
                    <label for="user.attributes.myattribute" class="${properties.kcLabelClass!}">My Super Nice Attribute</label>
                </div>

                <div class="${properties.kcInputWrapperClass!}">
                    <select id="user.attributes.myattribute" class="${properties.kcSelectClass!}" name="user.attributes.myattribute">
                        <#if !register.formData['user.attributes.myattribute']??>
                            <option value="" disabled selected>Select your option</option>
                        </#if> 
                        <#list myAttribute as key, value>
                            <option ${(register.formData['user.attributes.myattribute']?? && register.formData['user.attributes.myattribute'] == key)?string('selected', '')} value="${key}">${value}</option>
                        </#list>
            

                    </select>
                        <#if messagesPerField.existsError('user.attributes.myattribute')>
                        <span id="input-error-affiliation" class="${properties.kcInputErrorMessageClass!}" aria-live="polite">
                            ${kcSanitize(messagesPerField.get('user.attributes.myattribute'))?no_esc}
                        </span>
                    </#if>
                </div>
            </div>
~~~

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by jonkoops** [comment]
@olivierb2 Am I correct in reading you are using Keycloak version 7.0.1? Could you please test this on the latest version of Keycloak and let us know if it is still actually an issue?

**Comment by mposolda** [comment]
@olivierb2 I am closing this as it is reported against very old version. Also latest Keycloak version (Keycloak 24 release, which is going to be released probably this week) contains user-profile support, which has much better support for multivalued user attributes.

Please open new issue if you are not able to achieve your use-case with latest Keycloak version and with user-profile builtin support.
