### ISSUE TITLE
[KC17] OAuth Flow fails with 400 Bad Request OAuth_Token_Request_State was changed during second PING type request

### ISSUE THREAD

**Issue by franzmathauser** [keycloak/keycloak#11276]
### Describe the bug

Discovered with Chrome

After a user runs into an inactivity timeout he/she and click a link in the still open application. The user is intercepted by the Login flow. Therefor the user gets redirect to the Login page with a query param redirect_uri of the clicked navigation endpoint.

During that process the OAuth_Token_Request_State cookie is updated with a new value, which is the same as the provided state-query-param of the shown url of the Loginpage.

For example:
http://localhost:8383/auth/realms/internal/protocol/openid-connect/auth?response_type=code&client_id=intranet-user&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fintranet%2FrandomPage.xhtml&state=2cf3466b-80f6-4f57-b2a2-3d0a9e0befe9&login=true&scope=openid

Right after the Login-Page is loaded Chrome requests a PING Request, which updates the OAuth_Token_Request_State Cookie value to a new one. 

![image](https://user-images.githubusercontent.com/701101/163173497-47aa58b2-fab6-41cc-bb91-ebc0811b4498.png)

![image](https://user-images.githubusercontent.com/701101/163173639-af7d85d8-0291-4ebd-85db-98f3cb74ebc3.png)

The OAuth_Token_Request_State value is now e95e7d53-bff1-4714-86d8-0d597be2e5b1

After providing the credentials. The redirect flow is executed

http://localhost:8080/intranet/randomPage.xhtml?state=2cf3466b-80f6-4f57-b2a2-3d0a9e0befe9&session_state=0c565b9d-9f11-44b6-810d-9a01dfc8dc26&code=181b7b5b-a9c6-4c3f-8773-8f757de37ab2.0c565b9d-9f11-44b6-810d-9a01dfc8dc26.5462adbe-6e2d-4f59-be7c-5bd19d0d4dad

The expanded Redirect-URL (with state, session_state, code Parameter) is checked by the org.keycloak.adapters.servlet.KeycloakOIDCFilter and fails because state (Queryparam)  does not match the OAuth_Token_Request_State cookie value, which results in a 400 bad request

![image](https://user-images.githubusercontent.com/701101/163174160-137994ff-99b8-4739-abcc-f1407aa284bf.png)

### Version

17.0.0 quarkus

### Expected behavior

There should not be a second request in the OAuth_Token_Request_State.

Provide information how to stop the browser from sending PING-type requests.

### Actual behavior

the OAuth_Token_Request_State cookie value is updated after the redirect_uri was created, which fails during afterwards with 400 Bad Request

### How to Reproduce?

1. Use Google Chrome (100.0.4896.75)
2. Login a KC-integrated Application, wait until the idle session timeout. 
3. Click to a protected resource in your application. 
4. You will be redirected to the Loginpage
5. Check the state-queryparam with your OAuth_Token_Request_State value if they do not match
6. Enter Credentials
7. After Redirect => Result 400 Bad Request

**Comment by franzmathauser** [comment]
I've found the issue. 

We use a JSF Application with the Omnifaces Lib. On each page change a unload-event (Chrome shows them as requests of type ping) is sent to invalidate the ViewScoped-Beans by Omnifaces, which issued a new value for the OAuth_Token_Request_State cookie, since this request was interfered by the KeycloakOIDCFilter. 

If i bypass the KeycloakOIDCFilter for all of the Omnifaces unload-events, the state value will not be updated and it works as expected.

**Comment by BrechtBD** [comment]
@franzmathauser Can you please tell me how you bypassed those events? I'm currently using the wildfly build-in OIDC adapter
