### ISSUE TITLE
Determine Keycloak image tag from Operator version

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#11287]
Currently the operator by default uses `latest` tag for Keycloak images. To avoid hardcoding the tag in every release, the operator can derivate the default matching Keycloak image tag from the operator version.

Proposed solution:
* Remove [`operator.keycloak.image`](https://github.com/keycloak/keycloak/blob/1661a4ecc76fee3ff86d8d8f5d3c91728b333662/operator/src/main/resources/application.properties#L8) config option.
* Add a new config option: `operator.keycloak.image.name=quay.io/keycloak/keycloak`.
* Add a new config option: `operator.keycloak.image.tag` (this will not be defined by default in [`application.properties`](https://github.com/keycloak/keycloak/blob/1661a4ecc76fee3ff86d8d8f5d3c91728b333662/operator/src/main/resources/application.properties).
* Use the following flow when [determining the Keycloak image](https://github.com/keycloak/keycloak/blob/1661a4ecc76fee3ff86d8d8f5d3c91728b333662/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakDeployment.java#L406):
   * If `image` field is defined in the CR, use that.
   * If `operator.keycloak.image.tag` is defined by the user, use `operator.keycloak.image.name:operator.keycloak.image.tag`.
   * Otherwise, use `operator.keycloak.image.name:{calculatedTag}`. Calculate the tag as follows:
```
if (quarkus.application.version == "999-SNAPSHOT") {
   calculatedTag = "nightly"
} else {
   calculatedTag = quarkus.application.version
}
```

**Comment by andreaTP** [comment]
We decided to explicitly set the operand image in the kubernetes resources leveraging env vars.
This will provide better testability and easy debugging.
i.e.:
```yaml
            - name: OPERATOR_KEYCLOAK_IMAGE
              value: quay.io/keycloak/keycloak:999-SNAPSHOT
```

A sample command for releasing with the appropriate version will look like:
```bash
mvn clean package -DskipTests '-Doperator.keycloak.image=quay.io/keycloak/keycloak:${quarkus.application.version}'
```
