### ISSUE TITLE
Failed to list UMA policies when a user who was used in a policy got deleted.

### ISSUE THREAD

**Issue by fredxing** [keycloak/keycloak#11284]
### Describe the bug

The policy endpoint returns error response when a user who was used in a policy got deleted from the realm (see reproduce steps for more details)

This issue is critical as the user management is not under control of a resource server. It's realm administrator's task. Once it happens, the resource server is no longer able to manage policies anymore.  

### Version

17.0.1

### Expected behavior

At minimal, deleting users should not affect the policy endpoint. The list policy endpoint should still work. Ideally, when a user is deleted, all policies should be updated to reflect the changes.

### Actual behavior

When a user used in a policy was deleted from the realm, list all policy endpoint stop working. It returned unknown error response. 

### How to Reproduce?

1) create a test realm
	login to Administration Console, Add realm "Test"
	
2) add test client
	select the "Test" realm, go to "Clients" -> "Create" and select the attached client json file "bug-test" (see Anything else), and "Save".
	
3) add a user "testuser"
	go to "Users", add a user "testuser"
	
4) register a protected resource
	get a client token (replace hostname:port in the curl requests)
	$curl --location --request POST 'http://hostname:port/auth/realms/Test/protocol/openid-connect/token' \
       --header 'Content-Type: application/x-www-form-urlencoded' \
       --data-urlencode 'grant_type=client_credentials' \
       --data-urlencode 'client_id=bug-test' \
       --data-urlencode 'client_secret=KlCEOISCILLXARITyE09zfo9wnOxAlci'
	   
	register a protected resource "test-protected-resource" (replace the <access_token> in the request with the one got above)
	curl --location --request POST 'http://hostname:port/auth/realms/Test/authz/protection/resource_set' \
       --header 'Content-Type: application/json' \
       --header 'Authorization: Bearer <access_token>' \
       --data-raw '{
           "name": "test-protected-resource",
           "ownerManagedAccess": true,
           "scopes": ["read", "write"]
       }'
	   
	write down the resource id (_id property in the response).
	
5) add an UMA policy
	add an UMA policy with the user "testuser" to the resource created above (replace the <resource_id>)
	curl --location --request POST 'http://hostname:port/auth/realms/Test/authz/protection/uma-policy/<resource_id>' \
       --header 'Authorization: Bearer <access token>' \
       --header 'Content-Type: application/json' \
       --data-raw '{
               "name": "test-policy",
               "decisionStrategy": "AFFIRMATIVE",
               "scopes": ["read"],
               "users": ["testuser"]
       }'
	write down the policy id (id property in the response).
	
6) query policy
	search all policies
	curl --location --request GET 'http://hostname:port/auth/realms/Test/authz/protection/uma-policy' \
		--header 'Authorization: Bearer <access token>'
	
	you should see one policy in response.
	
7) reproduce the bug by deleteing the user "testuser" from Administration Console
	login to Administration Console, go to "Users", and delete the user "testuser" in "Test" realm.
	search all policies again,
	
	curl --location --request GET 'http://hostname:port/auth/realms/Test/authz/protection/uma-policy' \
		--header 'Authorization: Bearer <access token>'

	you will get an error response "{"error":"unknown_error"}". keycloak server log shows a NullPointerException thrown.
	

### Anything else?

bug-test.json

```
{
    "clientId": "bug-test",
	"secret": "KlCEOISCILLXARITyE09zfo9wnOxAlci",
    "enabled": true,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [
        "*"
    ],
    "serviceAccountsEnabled": true,
    "authorizationServicesEnabled": true,
	"authorizationSettings": {
      "allowRemoteResourceManagement": true,
      "decisionStrategy": "AFFIRMATIVE"
	},
    "publicClient": false,
    "protocol": "openid-connect"
}
```

A quick fix could be:

```
 .../policy/provider/permission/UMAPolicyProviderFactory.java        | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/UMAPolicyProviderFactory.java b/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/UMAPolicyProviderFactory.java
index 51107ae8a2..db0daec628 100644
--- a/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/UMAPolicyProviderFactory.java
+++ b/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/permission/UMAPolicyProviderFactory.java
@@ -33,6 +33,7 @@ import org.keycloak.models.KeycloakSession;
 import org.keycloak.models.KeycloakSessionFactory;
 import org.keycloak.models.RealmModel;
 import org.keycloak.models.RoleModel;
+import org.keycloak.models.UserModel;
 import org.keycloak.models.utils.KeycloakModelUtils;
 import org.keycloak.models.utils.ModelToRepresentation;
 import org.keycloak.models.utils.RepresentationToModel;
@@ -349,7 +350,10 @@ public class UMAPolicyProviderFactory implements PolicyProviderFactory<UmaPermis
                 UserPolicyRepresentation rep = UserPolicyRepresentation.class.cast(associatedRep);
 
                 for (String user : rep.getUsers()) {
-                    representation.addUser(authorization.getKeycloakSession().users().getUserById(realm, user).getUsername());
+                    UserModel userModel = authorization.getKeycloakSession().users().getUserById(realm, user);
+                    if (userModel != null) {
+                        representation.addUser(userModel.getUsername());
+                    }
                 }
             }
         }
```

**Comment by pedroigor** [comment]
@fredxing Sent a fix. Thanks.

**Comment by fredxing** [comment]
@pedroigor The fix was verified on my end and it fixed the issue. Thanks!

**Comment by pedroigor** [comment]
@fredxing Tks for looking at it.
