### ISSUE TITLE
Keycloak is ignoring custom infinispan config

### ISSUE THREAD

**Issue by kaiJwitt** [keycloak/keycloak#11302]
### Describe the bug

I want to run Keycloak 17 (Quarkus Edition) in HA mode with the provided infinispan. Because we are running Keycloak on serveral stages, I want to specify a infinispan cluster name. As I understood from the documentation I should configure this in the given infinispan config xml ./conf/cache-ispn.xml

I altered
    ` <transport lock-timeout="60000"/>`
to
`     <transport cluster="myClusterName" lock-timeout="60000"/>`

After that I ran .\kc.bat build --cache=ispn --cache-config-file=conf/cache-ispn.xml

and started up the server with .\kc.bat start

Sadly the output logging shows this:

```
[org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
[org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [MyHostName-14281|0] (1) [MyHostName-14281]
```
As seen in the logs, the cluster name still is the default "ISPN".

I already consulted the infinispan docs here: https://infinispan.org/docs/stable/titles/configuring/configuring.html

as well as the Keycloak docs:

https://www.keycloak.org/server/caching

https://www.keycloak.org/server/configuration

I also noticed that other configs like node names are ignored. 

Running .\kc.bat show-config shows that the infinispan config file is set correctly:

```
Current Mode: none
Runtime Configuration:
        kc.cache =  ispn (PropertiesConfigSource[source=file:/C:/tmp/keycloak-17.0.0/bin/../conf/keycloak.conf])
        kc.cache-config-file =  conf/cache-ispn.xml (PropertiesConfigSource[source=file:/C:/tmp/keycloak-17.0.0/bin/../conf/keycloak.conf])
        kc.config.args =  show-config (SysPropConfigSource)
        kc.db =  dev-file (PersistedConfigSource)
        kc.home.dir =  C:\tmp\keycloak-17.0.0\bin\.. (SysPropConfigSource)
        kc.hostname =  loclhost (PropertiesConfigSource[source=file:/C:/tmp/keycloak-17.0.0/bin/../conf/keycloak.conf])
        kc.http-enabled =  false (PropertiesConfigSource[source=jar:file:///C:/tmp/keycloak-17.0.0/lib/lib/main/org.keycloak.keycloak-quarkus-server-17.0.0.jar!/META-INF/keycloak.conf])
        kc.http-relative-path =  / (PersistedConfigSource)
        kc.metrics-enabled =  false (PersistedConfigSource)
        kc.quarkus-properties-enabled =  false (PersistedConfigSource)
        kc.show.config =  none (SysPropConfigSource)
        kc.version =  17.0.0 (SysPropConfigSource)
```

Am I missing something? Is the infinispan config loading broken in KC 17  Quarkus?

### Version

17.0.0

### Expected behavior

Infinispan config is loaded and custom cluster name is set corretly.

### Actual behavior

Infinispan config is ignored and the default cluster name (ISPN) is always set.

### How to Reproduce?

Try to set a custom cluster name in the infinispan config.

**Comment by kaiJwitt** [comment]
I figured it out:

First I copied the cache-ispn.xml to a new file in the same directory and named it cache.xml
I changed the build paramter --cache-config-file=conf/cache-ispn.xml to --cache-config-file=cache.xml
So i just removed the folder specification as Keycloak seems to auto set the config directory to the conf folder.

**Comment by kaiJwitt** [comment]
Created a pull request to clarify the fact in the docs

**Comment by ahus1** [comment]
Reopening the issue, as there is now a PR to improve the docs.

**Comment by sreekesh93** [comment]
> I figured it out:
> 
> First I copied the cache-ispn.xml to a new file in the same directory and named it cache.xml I changed the build paramter --cache-config-file=conf/cache-ispn.xml to --cache-config-file=cache.xml So i just removed the folder specification as Keycloak seems to auto set the config directory to the conf folder.

Facing similar issue that cache config not getting applied created a new issue https://github.com/keycloak/keycloak/issues/11573 did you face something similar?
