### ISSUE TITLE
Keycloak liveness probe behaves as readiness probe

### ISSUE THREAD

**Issue by lejsekt** [keycloak/keycloak#11300]
### Describe the bug

I've observed the following behavior of health check endpoints in Keycloak: /health/ready and /health/live both return 503 if the underlying database is not responding.

### Version

17.0.1

### Expected behavior

/health/live should still return 200 even if the database is not responding.

### Anything else?

From Kuberenetes docs about readiness and liveness probes: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe

**Comment by DGuhr** [comment]
@pedroigor not 100% sure, but this one should also be solved by #11507 where it is not tied to db anymore, right?

**Comment by pedroigor** [comment]
That is correct.

**Comment by DGuhr** [comment]
solved by #11507
