### ISSUE TITLE
Unable to access admin console or account with KC_HOSTNAME_PORT=443

### ISSUE THREAD

**Issue by glandais** [keycloak/keycloak#11327]
### Describe the bug

If Keycloak is accessed through port 443 and KC_HOSTNAME_PORT is set to 443, we can't access admin console or login on /realms/master/account.

### Version

17.0.1

### Expected behavior

KC_HOSTNAME_PORT should be ignored if set to 443

### How to Reproduce?

Build a docker image with certificates :

Dockerfile :

```docker
FROM quay.io/keycloak/keycloak:17.0.1
WORKDIR /opt/keycloak
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=keycloak.localhost" -alias server -ext "SAN:c=DNS:keycloak.localhost" -keystore conf/server.keystore
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
# docker port forwarding
ENV KC_PROXY=edge
# resolvable hostname to localhost
ENV KC_HOSTNAME=keycloak.localhost
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

```bash
docker build -t keycloak-https .
```

Start container binding on 1443 :

```bash
docker run -it --rm -p 127.0.0.1:1443:8443 -e KC_HOSTNAME_PORT=1443 keycloak-https
```

Login on https://keycloak.localhost:1443 : no problem

Start container binding on 443 without KC_HOSTNAME_PORT :

```bash
docker run -it --rm -p 127.0.0.1:443:8443 keycloak-https
```

Login on https://keycloak.localhost : no problem

Start container binding on 443 with KC_HOSTNAME_PORT :

```bash
docker run -it --rm -p 127.0.0.1:443:8443 -e KC_HOSTNAME_PORT=443 keycloak-https
```

Login on https://keycloak.localhost : blank page with header

**Comment by kafeltz** [comment]
I have the exact same issue and removing the 443 (by hacking the browser) it fixes this issue.

**Comment by kafeltz** [comment]
Temporary fix could the:
In the keycloak.js
`return kc.authServerUrl.replace(':443', '') + 'realms/' + encodeURIComponent(kc.realm);`

It's a nice fix for something finding this isse in pre-release production.

**Comment by kafeltz** [comment]
> ### Describe the bug
> If Keycloak is accessed through port 443 and KC_HOSTNAME_PORT is set to 443, we can't access admin console or login on /realms/master/account.
> 
> ### Version
> 17.0.1
> 
> ### Expected behavior
> KC_HOSTNAME_PORT should be ignored if set to 443
> 
> ### Actual behavior
> _No response_
> 
> ### How to Reproduce?
> Build a docker image with certificates :
> 
> Dockerfile :
> 
> ```
> FROM quay.io/keycloak/keycloak:17.0.1
> WORKDIR /opt/keycloak
> RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=keycloak.localhost" -alias server -ext "SAN:c=DNS:keycloak.localhost" -keystore conf/server.keystore
> ENV KEYCLOAK_ADMIN=admin
> ENV KEYCLOAK_ADMIN_PASSWORD=admin
> # docker port forwarding
> ENV KC_PROXY=edge
> # resolvable hostname to localhost
> ENV KC_HOSTNAME=keycloak.localhost
> ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
> ```
> 
> ```shell
> docker build -t keycloak-https .
> ```
> 
> Start container binding on 1443 :
> 
> ```shell
> docker run -it --rm -p 127.0.0.1:1443:8443 -e KC_HOSTNAME_PORT=1443 keycloak-https
> ```
> 
> Login on https://keycloak.localhost:1443 : no problem
> 
> Start container binding on 443 without KC_HOSTNAME_PORT :
> 
> ```shell
> docker run -it --rm -p 127.0.0.1:443:8443 keycloak-https
> ```
> 
> Login on https://keycloak.localhost : no problem
> 
> Start container binding on 443 with KC_HOSTNAME_PORT :
> 
> ```shell
> docker run -it --rm -p 127.0.0.1:443:8443 -e KC_HOSTNAME_PORT=443 keycloak-https
> ```
> 
> Login on https://keycloak.localhost : blank page with header
> 
> ### Anything else?
> _No response_

Try the above temp fix.

**Comment by olekristoffer** [comment]
I had similar issues on a bare metal keycloak 18 quarkus install, where the admin console would fail to load when configured to use proxy, host and port 443. i.e:
```
hostname=<public.host.name>
hostname-port=443
proxy=reencrypt
```
The above temp fix in keycloak.js allowed the admin console to load using the above configuration. On a side-note the admin page would load as long as the configured reverse proxy and hostname-port was different from 443, e.g. hostname-port=9443, but otherwise using the same proxy/host config.

**Comment by DGuhr** [comment]
We re-introduced the `hostname-admin` configuration where you are able to set a complete url for the administration endpoints. Would that solve the issue for you? You could try it out using the latest nightly image :)

**Comment by DGuhr** [comment]
Closing here for now, as no answer was given. When you still experience problems, please re-open or create a new issue. 

For future reference: The standard ports 443 for HTTPS and 80 for HTTP are used when you set `proxy=edge`, so there would be no need to set the `hostname-port`
