### ISSUE TITLE
New Account console tests failures

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#11323]
### Describe the bug

There are a lot of failures in Account tests.

See:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/1400/testReport/junit/

### Version

999

**Comment by ssilvert** [comment]
@mabartos Just to let you know, I expect that we will be rewriting the Account tests in Cypress later this year.  So the Arquilian tests will go away.  At least that's the current plan....

**Comment by mabartos** [comment]
@ssilvert Thanks for your comment. It seems those failures are caused only by some inconsistencies with messages and it requires only some minor changes. We need to keep the testsuite for the New Account console stable until the new tests coverage approaches the old one's.
