### ISSUE TITLE
Theme can auto-select rememberMe even if disabled in a realm

### ISSUE THREAD

**Issue by dstefanMSFT** [keycloak/keycloak#11330]
### Describe the bug

even if "remember Me" is disabled in realm settings, my theme can have a checkbox. If it gets enabled and POSTed to keycloak, remmeberMe cookie gets created and KYECLOAK_IDENTITY  cookie becomes persistent instead of session based

nutshell - theme/client-side code can overwrite Realm-side settings.

### Version

15.1.1

### Expected behavior

If I disable RememberMe in realm settings, selecting rememberMe on the client side should have no effect

### How to Reproduce?

disable Remember Me in the Realm

modify theme or HTML code with dev tools to POST rememberMe: on
`                <div id="kc-form-options">
                    <input style="display:none;" id="rememberMe" name="rememberMe" type="checkbox" checked>
                </div>`

close the browser
re-open and see that session still lives

**Comment by dstefanMSFT** [comment]
This also looks like a security bu. Should I re-file this one through security bug path?

**Comment by rmartinc** [comment]
Hi @dstefanMSFT and sorry for the delay!

Yes, you are right, the KEYCLOAK_REMEMBER_ME cookie is assigned if the form param is there, no matter the config option in the realm. But I don't think this is a security issue, or if it's, it's low impact. It's just the user name in a cookie and the server does not even show it if the login screen is presented again if realm option is disabled.

Nevertheless I'm assigning it to the 22.0.0 version and I'll try to send a PR the next week.

Thanks!
