### ISSUE TITLE
Add option to not import user from brokers

### ISSUE THREAD

**Issue by PragmaChris** [keycloak/keycloak#11334]
### Description

Hello,
We use Keycloak as a bridge to authenticate our service users with some brokers that do not support standard protocols like OpenID or SAML.

The problem is that a few brokers (ex. one provided by the state of France) refuse us because our Keycloak store the data in its own database.
They tell us that it's not conform to the GPDR.

It will be great to add an option to by-pass user creation in Keycloak when using broker authentication. 

Thanks,
Christophe

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-4429

### Motivation

Be conform to the GPDR by not storing information we don't need (the data could be only pass to the service provider)

**Comment by lscorcia** [comment]
Same for the Italian National ID Federation (basically all of Europe is going the same way). Keycloak has some kind of support for Transient Sessions, but I tried enabling via a custom build a while ago and it gave weird errors when using the broker feature.
One way around this could probably be to save only the NameID (which is usually random from the Broker) into Keycloak and put all other info as session attributes, but I have not tried it.

**Comment by cesdperez** [comment]
@PragmaChris have you found a workaround for this?

**Comment by sschu** [comment]
@PragmaChris @cesdperez Are you sure it makes a difference whether data is stored persistently (users) vs. stored in memory (sessions) from a GDPR perspective?
