### ISSUE TITLE
Account page (Login profile) validations are client side

### ISSUE THREAD

**Issue by dstefanMSFT** [keycloak/keycloak#11331]
### Describe the bug

When signing in through external Identity provider (SAML in my case) going to <url>/auth/realms/<realm>/account/ I cannot edit anything and get a message:

> Account information is controlled by your company identity provider and cannot be changed.

I can open dev tools and "un-hide" or enable edit fields. Once I do, I can submit changes to my own user account and overwrite IdP read-only policy
Eg.
![image](https://user-images.githubusercontent.com/26237154/163488239-3767cf1c-5689-43f0-a4b0-4139b7a15e23.png)

Same applies to password change - I can "unhide" password change DIV (if I have no credential in keycloak it is just password set without having to know old one). After that I can use my newly created password to circumvent IdP

BTW - disabling "Reset Password" in "Reset Credentials" Authentication Flow does not prevent user from setting/resetting their password from the account page

looks like all the validation/checks  happen inside browser-side HTML code

### Version

15.1.1

### Expected behavior

If user is provisioned/signed in via external IdP, editing properties of that user should be restricted on server side

### Actual behavior

Today all account edit validation seems to be happening on the browser side. That code can be manipulated. Hiding/disabling is just a convenience feature. Not a security one.

### How to Reproduce?

Go to <url>/auth/realms/<realm>/account/ 
sign-in with SAML SSO
edit HTML to either enable FistName or LastName fields
> for example change `<input type="text" class="domino-form-control" id="lastName" name="lastName" value="OldLastName" disabled="">` to `'<input type="text" class="domino-form-control" id="lastName" name="lastName" value="NewLastName">'`

submit

despite warning that 
> Account information is controlled by your company identity provider and cannot be changed.

change is saved

for password change you need to just un-hide one DIV: 
`<div id="change-password-container" style="display: none;">`
to
`<div id="change-password-container" style="">`

**Comment by ssilvert** [comment]
@dstefanMSFT @pedroigor As I understand it, this is not a bug in the UI.  

I do think it looks like a security issue though.  So yes, please re-file through the security bug path.

**Comment by ssilvert** [comment]
@dstefanMSFT I'm going to go ahead and close this.  If you did file a security bug, please link it to this issue.
