### ISSUE TITLE
authentication checks cause 'Cookie not found' error

### ISSUE THREAD

**Issue by yakyouk** [keycloak/keycloak#11340]
### Describe the bug

When a user doesn't have credentials, my app occasionally checks auth status in case the user authenticated externally. If this check happens while a user has the login page open, the user won't be able to complete authentication in that login page, with error: `Cookie not found. Please make sure cookies are enabled in your browser.`.

I propose that the cookie not be cleared if `response_type=none`.

### Version

17.0.1

### How to Reproduce?

- in tab 1, open auth page: `/auth/realms/my-realm/protocol/openid-connect/auth?response_type=code&client_id=my-client&state=abc1234&scope=profile&code_challenge=def5678&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fexample.com%2Fsignin%3Faction%3Dclose`
- in tab 2, to simulate an authentication check, open the following: `/auth/realms/my-realm/protocol/openid-connect/auth?prompt=none&response_type=none&client_id=my-client&code_challenge=def5678&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fexample.com%2Fsignin%3Faction%3dmessage`. If this redirects to `redirect_uri` with `error=login_required`, this tells us the user isn't authenticated. Note the `prompt=none` and `response_type=none`.
- return to tab 1 and complete authentication, and see error `Cookie not found. Please make sure cookies are enabled in your browser.`

**Comment by ladytaz-rowell** [comment]
Is there an update to this issue? I am seeing the same error, and trying to figure it how to get around it.

**Comment by rmartinc** [comment]
Hi! Yes, I think this is a valid bug. I'm setting it to 22.0.0 as tentative but it could be delayed.

**Comment by Zhark10** [comment]
it's still unresolved

**Comment by rmartinc** [comment]
@Zhark10 You mean after applying the [PR](https://github.com/keycloak/keycloak/pull/17457)? I added a test with the exact reproducer. The PR is still under review and it's expected to be present in 22.0.0 when released.

**Comment by Meet-S0ni** [comment]
i'm facing this issue still in 24
