### ISSUE TITLE
Typo in HostnamePropertyMappers.java

### ISSUE THREAD

**Issue by McLaynV** [keycloak/keycloak#11344]
### Describe the bug

There is `an` instead of `and` in `HostnamePropertyMappers.java` in `to allow internal an external applications`.

https://github.com/keycloak/keycloak/blob/ffa6df5547a5f9b902bc04a349cb964d5229c449/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/HostnamePropertyMappers.java#L30

Here is a PR: #11260

### Version

17.0.1

**Comment by DGuhr** [comment]
Reopening due to test regression (we check the help output in some tests, so you'd need to change the files we check against. Will provide a PR.)
