### ISSUE TITLE
Fix Device Authorization Grant error responses returned as HTML instead of JSON

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#11438]
### Describe the bug

While testing the OAuth 2.0 Device Authorization Grant Key for a client without the device grant enabled, Keycloak returns the following error:

> Client is not allowed to initiate OAuth 2.0 Device Authorization Grant. The flow is disabled for the client.

Returning an error is correct but the error message is returned as an html document, instead of json. The same happens for other errors.

From https://datatracker.ietf.org/doc/html/rfc8628#section-3.2:

> In the event of an error (such as an invalidly configured client),
>  the authorization server responds in the same way as the token
>  endpoint specified in 
>  Section 5.2 of [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2).

From https://datatracker.ietf.org/doc/html/rfc6749#section-5.2:

> The parameters are included in the entity-body of the HTTP response
>  using the "application/json" media type as defined by [RFC4627]. The
>  parameters are serialized into a JSON structure by adding each
>  parameter at the highest structure level. Parameter names and string
>  values are included as JSON strings. Numerical values are included
>  as JSON numbers. The order of parameters does not matter and can
>  vary.

### Version

16.1.0

### Expected behavior

Return json error in the format described in [section 5.2 of OAuth documentation](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2).
Keycloak has ErrorResponseException for this.

### Actual behavior

Return html page.

### How to Reproduce?

F.e. disable OAuth 2.0 Device Authorization Grant for a client and try to execute Device Authorization Grant.

**Comment by mposolda** [comment]
I am adding this with the label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to investigate this further and eventually send PR for this.
