### ISSUE TITLE
Email address/Username whitespaces

### ISSUE THREAD

**Issue by BirknerAlex** [keycloak/keycloak#11452]
### Describe the bug

Whitespaces are not trimmed on email addresses when registering a new user account. This can cause issues on backend systems that are using the email addresses provided from Keycloak.

### Version

17.0.1

### Expected behavior

Whitespaces on the beginning and on the end of the email address should be removed. e.g. using the String.trim() function on registering user accounts.

### Actual behavior

.Whitespaces are being saved on the database.

### How to Reproduce?

- Register an account on Keycloak
- Use an email address with an whitespace on the end of the address
- User gets created and contains the whitespace character on the email address

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by bastianccm** [comment]
Hi @mposolda, this issue still exists in 21.0.2, please find a solution proposal in #19648

**Comment by pedroigor** [comment]
More context about this issue here https://github.com/keycloak/keycloak/pull/19648.

**Comment by bastianccm** [comment]
What can we do to support with this issue? It's a huge UX problem for non-technical users when registering :(
As converters are not further planned and the proposed solution is closed, what can we do to help resolving this?
I'm happy to work on the converters for the declarative user profile, if this is the proposed way forward? I just don't want to waste time on something which is not aligned with the maintainers.

**Comment by pedroigor** [comment]
@bastianccm Thanks for your interest in collaborating (and for closing your PR). 

What do you think about starting from here https://github.com/keycloak/keycloak/issues/23222?

Tried to consolidate some key points and initial ideas. We only know that we need the mechanism but nothing is set in stone yet.

**Comment by pedroigor** [comment]
@bastianccm @BirknerAlex Closing in favor of https://github.com/keycloak/keycloak/issues/23222.
