### ISSUE TITLE
Barcode for QR-Scan not possible is not showing

### ISSUE THREAD

**Issue by Fbain24** [keycloak/keycloak#11538]
### Describe the bug

After the update from 15.0.2 to 16.1.1 we can´t show the manual code of a qr-code anymore.

The issue lies in the keycloak/forms/login/freemarker/model/TotpBean.java.

Here a change to the Method getManualUrl() got commited. (https://github.com/keycloak/keycloak/commit/c9809f015168e890bd45e9891f45b72f8041a530)

After that change we can´t show the code anymore. If we manually remove the execution part from the url the code is shown as expected.

### Version

16.1.1

### Expected behavior

After clicking on the link for "Unable to scan?" the code behind the qr-code appears to get put in the authenticator.

### Actual behavior

A page saying "This page is no longer valid" appears. If you remove the "&execution=..." part from the url the expected page appears.

### How to Reproduce?

Click the "Unable to scan?" link on the qr-code for google authenticator page. 

### Anything else?

It is possible we are missing some kind of configuration and that is the issue. If you could provide me with that information i would gladly take it.

**Comment by rmartinc** [comment]
Hi @Fbain24!

Does the issue still happen in the new 21.0.0 version? I have just assigned the `Configure OTP` action to a user and I can see the QR without issues when the action is shown after login. Please check with the last version and if the issue s still there please give exact reproducer steps.

Thanks in advance!
