### ISSUE TITLE
Non ASCII characters in TOTP secret not supported in 2FA configurations

### ISSUE THREAD

**Issue by kpritam** [keycloak/keycloak#11561]
### Describe the bug

I am trying to migrate 2FA configurations (Google Authenticator) from legacy system to keycloak.
We generate random secrets which includes non ascii characters, porting these to keycloak (in `credentials` table) does not work.

For example, base32 encoded secret key for google authenticator is `CDLYAYRJ73ORTU4PUWWATWSYQCP4H2QL`.
When I decode this key which results into this `◊Äb)˛›”è•¨	⁄XÄü√Í`

Inserting this secret in `credentials` table does not work

### Version

18.0.0

**Comment by DGuhr** [comment]
@kpritam are you using wildfly (legacy) or quarkus? If quarkus, are you running in a container? Asking bc of https://github.com/keycloak/keycloak/discussions/11527 this _could potentially_ cause the behaviour. I provide a fix in #11547 that sadly didnt make it in 18 but will be targeted for the next release. In the meantime it would be nice if you could check if it works for you when applying the fix from the PR.

Cc @jsorah fyi

**Comment by dalbani** [comment]
Yes, it's very much a valid issue, when it comes to supporting importing *existing* TOTP secrets (which were thus *not* generated by Google Authenticator for example).
