### ISSUE TITLE
OIDC clients can't require JAR if auth requests are sent with PAR

### ISSUE THREAD

**Issue by vanrar68** [keycloak/keycloak#11569]
### Describe the bug

When using the OIDC client setting "Request Object Required=Request Only" Keycloak expects a "request" parameter containing a JWT to be set when calling the authorization endpoint. In a Pushed Authorization Request (PAR) scenario the JWT is sent to the PAR endpoint instead of the authorization endpoint. Keycloak will currently reject the auth request because it won't include the "request" parameter. Keycloak doesn't get that the "request" parameter was indeed submitted, only indirectly (through the PAR endpoint).
Currently the only way to submit JAR request through PAR is to set the following client settings:
- Request Object Required=not required
- Pushed Authorization Request Required=Off

This prevent OIDC clients to require simultaneously JAR and PAR.

### Version

17.0.1

### Expected behavior

When JAR is required for an OIDC client Keycloak should accept PAR auth requests if a corresponding JAR request was sent to the PAR endpoint

### Actual behavior

An error message is displayed on screen (invalid request) and the logs contain the following:

```
2022-04-21 08:50:36,083 WARN  [org.keycloak.services] (executor-thread-1304) KC-SERVICES0097: Invalid request: java.lang.RuntimeException: Client is required to use 'request' parameter.
    at org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor.parseRequest(AuthorizationEndpointRequestParserProcessor.java:74)
    at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:132)
    at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
    at jdk.internal.reflect.GeneratedMethodAccessor617.invoke(Unknown Source)
```

### How to Reproduce?

Set the following OIDC client settings:
- Request Object Required=request only
- Pushed Authorization Request Required=On

Send a JAR request to the PAR endpoint
Perform the GET request to the authorization endpoint using the parameter returned by the PAR endpoint

**Comment by mposolda** [comment]
@vanrar68 Thanks for the report, but not sure if this is really bug. Could you please elaborate what you try to achieve and if any of the options below work for you? :

In case that PAR is used, the request to the AuthorizationEndpoint would use `request_uri` parameter. So:
- In case that you require client to use PAR, you can use:
```
Request URI Object Required=request_uri only
Pushed Authorization Request Required=On
```

- In case that you want your client to use either PAR or JAR (through the `request` object), you can use:
```
Request URI Object Required=request or request_uri
Pushed Authorization Request Required=On
```

There is also an option to use the parameter `Valid Request URIs` to further limit how the request URIs can look like. Will any of the options work for you?

**Comment by mposolda** [comment]
I am adding this with the label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to investigate this further and eventually send PR for this.

**Comment by abdulazezms** [comment]
@mposolda Thanks for you response but this issue still exists. I would try to elaborate more on the issue.

I have a client on Keycloak version 23.0.7 with the following configuration:

1. Pushed authorization request required = ON
2. Request object required = Request or Request URI

My expectation now is that I could use PAR as follows:

```
POST /realms/<my-realm>/protocol/openid-connect/ext/par/request HTTP/1.1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded
Content-Length: 114

client_id=myclient&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2F&scope=openid&response_mode=jwt
```

However, the server is unable to process the request, and responds with:

```
{
    "error": "invalid_request_object",
    "error_description": "HTTP 500 Internal Server Error"
}
```
The server's logs:

```
WARN  [org.keycloak.services] (executor-thread-55) KC-SERVICES0097: Invalid request: java.lang.RuntimeException: Client is required to use 'request' or 'request_uri' parameter.
app-keycloak-1    |       at org.keycloak.protocol.oidc.par.endpoints.request.ParEndpointRequestParserProcessor.parseRequest(ParEndpointRequestParserProcessor.java:74)
app-keycloak-1    |       at org.keycloak.protocol.oidc.par.endpoints.ParEndpoint.request(ParEndpoint.java:96)
app-keycloak-1    |       at org.keycloak.protocol.oidc.par.endpoints.ParEndpoint$quarkusrestinvoker$request_af906d5d7425914e86d7ccc25bd818affb15f104.invoke(Unknown Source)
app-keycloak-1    |       at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
app-keycloak-1    |       at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
app-keycloak-1    |       at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
app-keycloak-1    |       at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
app-keycloak-1    |       at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
app-keycloak-1    |       at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
app-keycloak-1    |       at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
app-keycloak-1    |       at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
app-keycloak-1    |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
app-keycloak-1    |       at java.base/java.lang.Thread.run(Thread.java:840)
```

I cannot make sense of why would a PAR endpoint require the existence of a request or request_uri at this point.
