### ISSUE TITLE
Keycloak infinispan cache config changes are getting ignored in keycloak x 

### ISSUE THREAD

**Issue by sreekesh93** [keycloak/keycloak#11573]
### Describe the bug

I want to update the realm and user cache size configuration of inifinispan. To do this as I understood from the documentation I should configure this in the given infinispan config xml ./conf/cache-ispn.xml.

I modified the values and built docker image and started running it. With same config changes in keycloak With 16 & 17 legacy version on updating realm cache size we are able to notice the good performance difference. But with 17.0.1 version the latency is very high.

This could be because of the cache properties are not getting applied when keycloak starts.

Note: there is no log to check is this cache size got applied or not.

[dockerfile.txt](https://github.com/keycloak/keycloak/files/8530515/dockerfile.txt)

in cache-ispn.xml updated realm cache value from 10000 to  memory max-count="100000"

 

### Version

17.0.1

### Expected behavior

Keycloak cache configuration should have applied 

### Actual behavior

keycloack cache config are not getting applied , due to this the realm creation latency got increased

### How to Reproduce?

Update the cache-ispn.xml realm cache from 10000 to 100000 and build docker image docker file is attached above. Run the image and produce load after reaching around 600 realm it will take long time which is not expected when cache size is increased.

**Comment by kaiJwitt** [comment]
Can you post what the output of ./bin/kc.sh show-config is after running bin/kc.sh build?

**Comment by kaiJwitt** [comment]
@sreekesh93 thank you. It seems that keycloak is using the right config file. 

As you asked [here](https://github.com/keycloak/keycloak/issues/11302#issuecomment-1105141413) I don't faced something similar. 

I hope someone else can help you with your problem.

**Comment by sreekesh93** [comment]
Noted from jmx metrics that this config changes for realm local cache got applied. updated from 10000 to 100000. But still the realm creation performance has no improvement in quarkus version.

**Comment by DGuhr** [comment]
Hi @sreekesh93 as you have found out yourself, the actual changes are set for Keycloak, so I will close this issue as there's no problem with setting and applying the actual value. 

That said: Sadly, they don't help much. 
For these and other performance related things, there are ongoing discussions, mainly at #11074 but also e.g. at #12332 - feel free to join the discussion, and expect some improvements in the future. :)
