### ISSUE TITLE
Admin Console not showing under circumstances

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#11579]
### Describe the bug

Using different http/https and proxy configurations is easy enough to end up with the Admin UI not working and staying in a page reload infinite loop.

Me and @vmuzikar narrowed down the issue to an incorrect variable value (namely `authServerUrl`) being injected into an "in-page" javascript block:
```xml
<script type="[text/javascript]()">
        var authServerUrl = 'https://localhost';
        var authUrl = 'http://localhost:8080';
        var consoleBaseUrl = '/admin/master/console/';
        var resourceUrl = '/resources/xa1ud/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'xa1ud';
</script>
```

The problem shows up in various situations:

```bash
export KC_DB=dev-mem
export KC_HOSTNAME=localhost
export KC_HTTP_ENABLED=true

./bin/kc.sh start --auto-build
```

or even:

```bash
./bin/kc.sh start --auto-build --hostname="localhost" --proxy=edge
```

and again:

```bash
./bin/kc.sh start-dev --hostname="localhost" --proxy=edge
```

The problem shows up in three parts, the protocol (HTTP vs. HTTPS), the hostname mangling, and the associated port.

### Version

18.0.0

**Comment by andreaTP** [comment]
cc. @DGuhr @pedroigor

**Comment by pedroigor** [comment]
Is there a proxy in front of the server? Could you give the error in the browser and some hint on aboy any network call failure?

**Comment by andreaTP** [comment]
@pedroigor tested with and without proxy in front (e.g. with plain port-forward and through the ingress).

The failing network call happen to `authServerUrl` that is incosistent/not available

**Comment by DGuhr** [comment]
Let's split this up a bit.

First, for the part without a proxy, so this example: 
> ```shell
> export KC_DB=dev-mem
> export KC_HOSTNAME=localhost
> export KC_HTTP_ENABLED=true
> 
> ./bin/kc.sh start --auto-build
> ```

As of my information, you **should not be able** to start Keycloak without a proxy and using http **at all** in the production mode (`start`). 

That's exactly why there is the property `KC_HOSTNAME_STRICT_HTTPS`, that was _hidden on purpose_ initially, but seems even we forgot about that and it is handed over and over now. When you don't set this property, HTTPS is applied in the Provider @andreaTP mentions as defaultHttpScheme (l 216). Thus, the authServerURL uses https where it shouldn't. 

The UX / expectations are different, so we should do sth about this. When I have `http-enabled=true`, I'd expect to be able to call keycloak using HTTP. Or fail directly. 

So 2 ways to go, as I see it:

1) In the `HttpPropertyMappers`, for `http-enabled=true`, extend the transformer function and check if the context is production mode. If so, set `hostname-strict-https` to false.

2) not set `hostname-strict-https` to false when `http-enabled` and in production mode, but add a startup error instead telling ppl that http is not supported in production mode. 

Thoughts? Do I miss sth?

**Comment by DGuhr** [comment]
For the proxy setup, i guess its based on the same problem.. not tried yet, but see e.g. the proposed solution in #11324 - so we'd also need to check if proxy != false and for sure if http-enabled is true, and if so, set strict-https always to false, right?

Apart from that I want to again propose to create an example repo / module (maybe in quickstarts) that covers running in production mode with hostname applied, different proxy modes, http enabled/disabled, internal and external clients, and some automated container based tests to show ppl how it goes. 

_disclaimer_: I just tested the non-proxy stuff for now, so these are assumptions for now.

**Comment by vmuzikar** [comment]
@andreaTP Since this issue was resolved by just a [docs change](https://github.com/keycloak/keycloak/pull/11872), I believe we need a follow-up for the operator, right?

Created https://github.com/keycloak/keycloak/issues/12020

**Comment by andreaTP** [comment]
@vmuzikar I actually used #11581 to follow up. PR is: #12021

**Comment by vmuzikar** [comment]
@andreaTP Thanks, closed https://github.com/keycloak/keycloak/issues/12020.
