### ISSUE TITLE
Admin-cli Refresh token expire time decreases every time I utilize it for refreshing the token and then expires eventually

### ISSUE THREAD

**Issue by junaidcassbana** [keycloak/keycloak#11594]
### Describe the bug

I am using refresh token to refresh my access token. Its returning new token every time but the expire time for refresh token. 

Please see the attached image:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/99347500/164703184-4a5d038c-e6d1-49ea-ba56-b2aac03bc3ff.png)

In this image, I am logging the token and details generated by a cron job every 10 seconds. If you look at the refresh_expire_time its decreasing as I refresh the access token using refresh token.

Another thing to note, I am generating these tokes for admin using admin-cli client.

### Version

16.1.1

### Expected behavior

Refresh token should also be refreshed with new expire time.

### Actual behavior

Refresh token expire time decreases as I utilize it i.e. refresh my access token.

**Comment by stianst** [comment]
This is expected as the refresh token expiration time will be set according to when the session expires.

**Comment by stianst** [comment]
Regular tokens are linked to the session. If you want some that survives past that for example for a background job you should look at a service account or an offline token.

**Comment by junaidcassbana** [comment]
Sounds good. Thank you so much for your quick help. Really appreciate it. :)
