### ISSUE TITLE
Refactor Ickle query builder to use for loops instead of streams

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#11599]
### Describe the bug

After disabling the legacy cache, HotRod tests turned out to be significantly slower than before. We need to investigate what is the reason for the slowness and fix it if possible. After getting rid of the slowness we need to enable the HotRod tests in GHA as it was disabled [here](https://github.com/keycloak/keycloak/issues/11599#issue-1212285313).

### Version

main

**Comment by mhajas** [comment]
The slowness is mostly caused by #11769. As part of this issue we should enable near-caching and refactor `IckleQueryBuilder` to not use `Stream` for producing queries but `for` loops.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
