### ISSUE TITLE
Realm password policy regex does not work

### ISSUE THREAD

**Issue by gutschet** [keycloak/keycloak#11608]
### Describe the bug

I created a regex password policy in one of my realms. The regex matches, when NO TWO SAME CHARS are following each other and when you use a password with two same following chars (e.g. "1234aa_A" --> the two "a" should be forbidden) it does not match.

My regex is:
`^(?:(.)(?!1))*$`

I tested it with some online tools, for example https://rubular.com/ and https://ingram-braun.net/erga/online-regex-tester-perl-php-javascript/ and it works as expected:

Password: 1234aa_A --> no match
Password: 1234a_aA --> match

But in Keycloak, I can change the password of my user to "1234aa_A". Is there maybe a bug in the regex policy testing?

Kind regards
Timo

### Version

15.1.1

### Expected behavior

When I set my regex as password policy, I want keycloak to reject passwords with two following same characters (in my opinion the regex is correct and my online tests confirm that). So for example password "1234aa_A" should not be possible.

### Actual behavior

I can change my passwort to "1234aa_A". But it has two same following chars (aa) and therefor should be rejected

### How to Reproduce?

Set a regex password policy with regex `^(?:(.)(?!1))*$` and try to change password to "1234aa_A".

**Comment by koh-osug** [comment]
In Java the regex does not work and since Keycloak is based on Java you have to modify the regex to be supported by Java. You have to use a Java online regex tester.  Consult the [Java documentation](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/regex/Pattern.html)

~~~java
class Scratch {
    public static void main(String[] args) {
        System.out.println("1234aa_A".matches("^(?:(.)(?!1))*$"));
    }
}
~~~

**Comment by rmartinc** [comment]
Hi @gutschet! Yes, as @koh-osug comments you have to use regexp as in Java. Searching over the internet for example [this page](https://www.freeformatter.com/java-regex-tester.html) tests java expressions. I think that if you want a regexp to disallow password with repeated chars you need a regex like this one: `((.)(?!\2))+`

Closing this one as it's working as expected.
