### ISSUE TITLE
Using entities for filtering instead of models in Map*Adapter

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#11603]
There are often calls in `Map*Adapter` to model(s) when filtering objects. e.g.
```
if (getRequiredCredentialsStream().anyMatch(credential -> Objects.equals(model.getType(), credential.getType()))) {
    throw new ModelDuplicateException("A Required Credential with given type already exists.");
}
```
to verify there is no required credential already stored. 

In such calls entities are often transformed into models (within `getRequiredCredentialsStream()`) and then filtered.

One option in this particular example would be to add `Optional<MapRequiredCredentialEntity> getRequiredCredentialByType(String type);` to `MapRealmEntity` to avoid the creation of the models.

This issue is about re-visiting those places in all `Map*Adapter`s.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
