### ISSUE TITLE
Inconsistency in username search

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#11602]
### Describe the bug

There is an inconsistency when searching users by `username`. 

Here we use `EQ` operator: 
https://github.com/keycloak/keycloak/blob/75cb29017c68d628c0b9f09236fd67155fdffc52/model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java#L323

However, here we use `ILIKE`:
https://github.com/keycloak/keycloak/blob/75cb29017c68d628c0b9f09236fd67155fdffc52/model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java#L511
https://github.com/keycloak/keycloak/blob/75cb29017c68d628c0b9f09236fd67155fdffc52/model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java#L629
https://github.com/keycloak/keycloak/blob/75cb29017c68d628c0b9f09236fd67155fdffc52/model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java#L856

We should unify these usages so we avoid situation where we, for example, create two different users `Admin` and `admin` but when searching by username we find both.

### Version

main

**Comment by vramik** [comment]
note: It relates to https://github.com/keycloak/keycloak/issues/10245
