### ISSUE TITLE
Multiple consecutive Device Authorization Grant flow passings use the same User Session

### ISSUE THREAD

**Issue by Raidok** [keycloak/keycloak#11600]
### Describe the bug

Let's assume I have two devices (let's call them **A** and **B**) that use the Device Authorization Grant flow and I have an another device (let's call it **M**) that I use to enter the user code and log in.

When going through the Device Authorization flow with device A then everything is fine.
After entering device B's user code on device M, I no longer have to enter my credentials because I have a cookie from the last time, which is also fine.

Also, I have "Revoke Refresh Token" set to ON and "Refresh Token Max Reuse" is set to 0.

The problems occur when device A goes to refresh it's token after the Authorization flow with device B is complete. The response will be:

```
{
  "error": "invalid_grant",
  "error_description": "Stale token"
}
```

I have read the code that ties the ends together (org.keycloak.protocol.oidc.grants.device.DeviceGrantType#oauth2DeviceFlow) and I have a feeling that the userSession from device M is used every time the Device Authorization Grant flow is passed. It would seem logical to me that the session would be forked somehow and device A and B would get a completely separate sessions.

### Version

18.0.0

**Comment by razvan-tufisi** [comment]
Hello. Any update regarding this issue?

**Comment by Raidok** [comment]
I have the same question. I am able to reproduce this with version 21.0.1.

**Comment by mposolda** [comment]
duplicates #14122

So I am closing as a duplicate for now.

I am not sure if there should be separate sessions on devices `A`, `B` and `M`. The solution might be to rather improve our experience with "Revoke Refresh Token" scenario with multiple client sessions of same client (as this is pretty much what happens here with the device flow). We already have the issue opened for this #14122, but the solution might be non-trivial as you can see in the comments in the underlying issue. Also we may wait for the new store before fixing this. Please use the other issue for further comments/questions/concerns regarding this.

The workaround for now is to just avoid using "Revoke Refresh Token"
