### ISSUE TITLE
if a role for a specific client is not mapped to me in Keycloak, SP initiated login should should fail

### ISSUE THREAD

**Issue by rasikmhetre** [keycloak/keycloak#11628]
### Describe the bug

As of now i can login to the application by doing SP initiated login even if that user is not mapped to that client.

### Version

Redhat SSO 7.4.10.GA

### Expected behavior

SP initiated login should should fail if the user is not mapped the that any role of that client.

**Comment by stianst** [comment]
This is expected behaviour as Keycloak does not have any authorization restrictions on what users can authenticate to which applications.
