### ISSUE TITLE
[docs]: wrong documentation link

### ISSUE THREAD

**Issue by CSalih** [keycloak/keycloak#11626]
### Describe the bug

The documentation link of "Using a reverse proxy" found in [Configuring the hostname](https://www.keycloak.org/server/hostname#_administrative_endpoints) redirects to `/{links_server_proxy_name}` instead of `/server/reverseproxy`.

### Version

--

### Expected behavior

``` html
<div class="sect2">
<h3 id="_administrative_endpoints">Administrative Endpoints</h3>
... 
see the <a href="https://www.keycloak.org/server/reverseproxy">Using a reverse proxy</a>
...
```

### Actual behavior

``` html
<div class="sect2">
<h3 id="_administrative_endpoints">Administrative Endpoints</h3>
<div class="paragraph">
<p>To reduce attack surface, the administration endpoints for Keycloak and the Admin Console should not be publicly accessible.
Therefore, you can secure them by using a reverse proxy.
For more information about which paths to expose using a reverse proxy, see the <a href="{links_server_proxy_url}">{links_server_proxy_name}</a>
 Guide.</p>
</div>
</div>
```

### How to Reproduce?

Goto: 
* https://www.keycloak.org/server/hostname#_administrative_endpoints or
* https://www.keycloak.org/server/hostname#_overriding_the_hostname_path

You will see `{links_server_proxy_name}` instead of the url.

**Comment by JonasCir** [comment]
Hey @CSalih,
thanks for taking care of this!

As of today, if you navigate to https://www.keycloak.org/server/hostname , you will still find `{links_server_proxy_name}` under the `Administrative Endpoints` section for example. Will the documentation on the page only be updated with the next release or is this a regression?

**Comment by CSalih** [comment]
Hey @JonasCi good point. 

@stianst when does the documentation page get upadted?
