### ISSUE TITLE
REGISTER event not logged during First Broker Flow

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#11646]
### Describe the bug

Version : RH-SSO 7.5.0 

ISSUE : REGISTER event is not logged for new user during "First Broker Login" flow in RH-SSO 7.5

 

The issue is not observed in RH-SSO 7.4

 

### Steps to Replicate:

- Configure RH-SSO as a broker, by configuring Identity provider in RH-SSO.
- Disable "Update Profile" Default Action, if enabled
- Configure event listener logging level to INFO

```
               <spi name="eventsListener">
                    <default-provider>jboss-logging</default-provider>
                    <provider name="jboss-logging" enabled="true">
                        <properties>
                            <property name="success-level" value="info"/>
                            <property name="error-level" value="warn"/>
                        </properties>
                    </provider>
                </spi>
```

- Login into RH-SSO with identity provider. Use new user which is not already registered in RH-SSO.
- Checking server logs, there are 2 events for LOGIN and no event for REGISTER

```
2022-04-04 21:18:12,155 INFO  [org.keycloak.events] (default task-10) type=LOGIN, realmId=identity-broker-realm, clientId=account-console, userId=1e06fad1-0189-40f8-bf40-655b5fa1abe8, ipAddress=127.0.0.1, identity_provider=oidc, register_method=broker, response_type=code, consent=no_consent_required, identity_provider_identity=rishabh, code_id=42608047-dff5-4148-81de-db66993a4b09, email=rissingh@redhat.com, username=rishabh, response_mode=fragment, authSessionParentId=42608047-dff5-4148-81de-db66993a4b09, authSessionTabId=lqq3jxp7DdM

2022-04-04 21:18:12,155 INFO  [org.keycloak.events] (default task-10) type=LOGIN, realmId=identity-broker-realm, clientId=account-console, userId=1e06fad1-0189-40f8-bf40-655b5fa1abe8, ipAddress=127.0.0.1, identity_provider=oidc, register_method=broker, response_type=code, consent=no_consent_required, identity_provider_identity=rishabh, code_id=42608047-dff5-4148-81de-db66993a4b09, email=rissingh@redhat.com, username=rishabh, response_mode=fragment, authSessionParentId=42608047-dff5-4148-81de-db66993a4b09, authSessionTabId=lqq3jxp7DdM
 ```

### Observations:

EventListenerTransaction is added in RH-SSO 7.5. And it seems the same event object from `IdentityBrokerService#afterFirstBrokerLogin` with EventType REGISTER  is passed into `AuthenticationManager.finishedRequiredActions` . In `AuthenticationManager.finishedRequiredActions` the EventType is set to LOGIN
 
```
 644     private Response afterFirstBrokerLogin(AuthenticationSessionModel authSession) {
 645         try {
 646             this.event.detail(Details.CODE_ID, authSession.getParentSession().getId())
 647                     .removeDetail("auth_method");
.............
 709                 event.event(EventType.REGISTER)
 710                         .detail(Details.REGISTER_METHOD, "broker")
 711                         .detail(Details.EMAIL, federatedUser.getEmail())
 712                         .success();
 
...........

 816     private Response finishBrokerAuthentication(BrokeredIdentityContext context, UserModel federatedUser, AuthenticationSessionModel authSession, String providerId) { 
...........
 843             event.detail(Details.CODE_ID, authSession.getParentSession().getId());
 844             return AuthenticationManager.finishedRequiredActions(session, authSession, null, clientConnection, request, session.getContext().getUri(), event);
845         }
```

### Query:

This seems to be a bug. Need your input on the same.

### Version

17.0.0

### Note

Marek: I did not personally reproduced it, but I think that the observation is correct and this is valid bug.

**Comment by lexcao** [comment]
Hi Keycloak team.

From my invisigation, the `REGISTER ` event will be override in `finishedRequiredActions` .
And it is same cause as @mposolda said.

I am going to fix it. I need your suggestion before I begin to code.

**Proposal A,**
In `finishedRequiredActions`, avoid to override the same event when the event has already sent.
```
// It could be overridden if the event is not sent.
if (event.getEvent().getId() == null) {
    event.event(EventType.LOGIN);
    event.session(userSession);
    event.success();
}
```
There will break some tests in `KcOidcBrokerEventTest`.

**Proposal B**,
In `afterFirstBrokerLogin`, send a copied `REGISTER` event
```
event.clone()
    .event(EventType.REGISTER)
    .detail(Details.REGISTER_METHOD, "broker")
    .detail(Details.EMAIL, federatedUser.getEmail())
    .success();
```
There will be one more event for `REGISTER` in logs.

I would prefer Proposal B, the tests could not break so much.
Adding a new event is safe than updating one.
Or there are some cases I did not cover.
Please feel free to review and comment.

### Anything else?

From the `afterFirstBrokerLogin`, the `FEDERATED_IDENTITY_LINK` event could be overridden as same to `REGISTER` event.
```
.............
 687             if (Boolean.parseBoolean(isRegisteredNewUser)) {
                     } else {
 711                   event.event(EventType.FEDERATED_IDENTITY_LINK)
 712                                .success();
                     }
...........
```

**Comment by rishabhsvats** [comment]
Hi @lexcao , your **Proposal B** seems better approach to me. 

I have drafted a pull request with the change, would it be fine if I raise the pull request.

**Comment by lexcao** [comment]
Thanks for your help, you can make a fix.
I have seen your draft PR, It would be nice if you fix those tests in `KcOidcBrokerEventTest`.

**Comment by rishabhsvats** [comment]
Thank you for the input. I have started working on the failing tests.
