### ISSUE TITLE
 Authentication Flow Overrides is not updating when reverted to default

### ISSUE THREAD

**Issue by anish-dcruz** [keycloak/keycloak#11643]
### Describe the bug

 Authentication Flow Overrides cache not being cleared.

Note: I m running K8s with 2 replicas.

### Version

18.0.0

### Expected behavior

Once the client changes Authentication Flow Overrides the change should be reflected.

### Actual behavior

The cache is not being removed

### How to Reproduce?

I copied the browser's Authentication Flow and changed it to require an OTP.
It worked perfectly once I updated the client to use the new Authentication Flow Overrides.
When I went back to using the default browser Authentication Flow Overrides, it still asked for an OTP token.
I removed the client, Authentication Flow, and replaced it with a new client with the same name, but it still demands an OTP.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
