### ISSUE TITLE
Access Admin Console when using reverse proxy/load balancer

### ISSUE THREAD

**Issue by eucleciojosias** [keycloak/keycloak#11667]
### Describe the bug

I tried so many approaches, but a just can't access the admin console.

I access `https://my.domain.com` then I click in **Administration Console** that goes to `https://my.domain.com/admin/master/console/` with a loading **Loading the admin console**, then show up a js alert with a message `failed to initialize keycloak`.

<img width="900" alt="Screen Shot 2022-04-26 at 10 28 22" src="https://user-images.githubusercontent.com/46788263/165310764-e174bcdc-2963-49b3-b06f-19b6221bfcc4.png">

When I click in `View Page Source` of this screen I find the following script (note the `http` on the `authUrl`):
```html
<script id="environment" type="application/json">
  {
    "loginRealm": "master",
    "authServerUrl": "https://my.domain.com",
    "authUrl": "http://my.domain.com",
    "consoleBaseUrl": "/admin/master/console/",
    "resourceUrl": "/resources/rq7wk/admin/keycloak.v2",
    "masterRealm": "master",
    "resourceVersion": "rq7wk",
    "commitHash": "{}",
    "isRunningAsTheme": true
  }
</script>
```

If I click "Ok" in the js alert, then it's redirected to a error page with the URL: 
`https://my.domain.com/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https://my.domain.dev/admin/master/console/#/&state={}&response_mode=fragment&response_type=code&scope=openid&nonce={}&code_challenge={}&code_challenge_method=S256`

The error shown is `invalid_url` as the image below 
<img width="736" alt="Screen Shot 2022-04-20 at 16 18 18" src="https://user-images.githubusercontent.com/46788263/164307406-e5723961-9642-4f36-a5a7-02dc4d432f9b.png">

Something I tried in this page was replace the `https` for `http` in the query param `&redirect_uri=http://my.domain.dev/admin/master/console/#/&state= ...`, then the login form shows up, but when I fill with valid credentials and submit the same errors happens.

Something I notice was looking at the dev tools Network, the following requests happens:
<img width="951" alt="Screen Shot 2022-04-26 at 10 37 50" src="https://user-images.githubusercontent.com/46788263/165312679-3e342754-0392-4d9c-bbac-60aa6ecc00cc.png">

The requests `serverinfo/`, `realms?briefRepresentation=true` and `whoami`  are pointing to `http://127.0.0.1:8080/auth/admin/`. 

### Version

18.0.0

### Expected behavior

To log into the Admin Console to registrer realms, users and config

### Actual behavior

When I try to log into the Admin Console this errors are shown

### How to Reproduce?

My Dockerfile:
```dockerfile
FROM quay.io/keycloak/keycloak:18.0.0 as builder

ENV KC_FEATURES=authorization,account2,account-api,admin-fine-grained-authz,admin2,docker,impersonation,token-exchange,client-policies,declarative-user-profile,dynamic-scopes,preview
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:18.0.0

COPY --from=builder /opt/keycloak/ /opt/keycloak/

WORKDIR /opt/keycloak

ARG KEYCLOAK_ADMIN
ARG KEYCLOAK_ADMIN_PASSWORD
ARG KC_DB_URL
ARG KC_DB_USERNAME
ARG KC_DB_PASSWORD
ARG KC_LOG_LEVEL

ENV KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
ENV KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
ENV KC_DB_URL=$KC_DB_URL
ENV KC_DB_USERNAME=$KC_DB_USERNAME
ENV KC_DB_PASSWORD=$KC_DB_PASSWORD
ENV KC_LOG_LEVEL=$KC_LOG_LEVEL

ENV KC_PROXY=edge
ENV KC_HOSTNAME=my.domain.com
ENV KC_SPI_HOSTNAME_DEFAULT_ADMIN=my.domain.com

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

**Comment by filipetavares** [comment]
I'm getting a similar behavior on kubernetes with a nginx reverse proxy.

I'm able to solve the redirect_url issue, by setting the **redirectUris**, **baseUrl** and **adminUrl** attributes of the **security-admin-console** client (not ideal to set this up every time I spawn a new instance though).

But once I get to the admin console, I'm getting mixed block error from the realms API calls:
![keycloak_error](https://user-images.githubusercontent.com/3610553/165346951-43607f50-94eb-4152-9a93-d35190fd2b78.png)

I'm also using version 18, which solves the keycloak.js absolute path issue (https://github.com/keycloak/keycloak/issues/10817).

**Comment by eucleciojosias** [comment]
@filipetavares interesting, how and where did you set these attributes?

**Comment by filipetavares** [comment]
I've used the kcadm.sh to change the settings following the doc (https://www.keycloak.org/docs/latest/server_admin/index.html#updating-a-client).

**Comment by DGuhr** [comment]
Should be fixed by https://github.com/keycloak/keycloak/pull/12192 and the corresponding PR in the admin-ui repository. Feel free to re-open if the issue still persists.

**Comment by michaelpearce-gain** [comment]
Issue is still persisting for me on latest release 18.0.2

**Comment by gfnord** [comment]
I config Michael's note, the problem still persists on 18.0.2. Changing from https to http on redirect_uri allows you to login in the admin.

**Comment by tlann** [comment]
I saw this error because I didn't have my reverse proxy  which for this instance, istio ingress gw set up correctly.  I was eithier or I had the headers incorrectly configured  or I was missing one of the headers needed for when using a reverse proxy.  I think it was the X_FORWARDED PROTO one when https isn't set.  https://www.keycloak.org/server/reverseproxy
