### ISSUE TITLE
Declarative User Profile: weird behaviour in Account Management Console

### ISSUE THREAD

**Issue by lus** [keycloak/keycloak#11668]
### Describe the bug

When starting Keycloak (X) with the new Declarative User Profile feature enabled, the Account Management Console still shows (and requires!) the First Name & Last Name fields, even when completely removed from the User Profile structure.
This breaks my whole setup as I do not want to require those fields in any way.

### Version

18.0.0

### Expected behavior

I expect those fields to completely disappear.

### Actual behavior

They do not and are required when updating the user's personal information.

### How to Reproduce?

* set up Keycloak v18.0.0
* enable the Declarative User Profile feature
* remove the First Name & Last Name fields
* open the Account Management Console

**Comment by pedroigor** [comment]
@lus We did not change the account console to leverage UP capabilities.

@ssilvert Do you think we should start looking at this now?

**Comment by ssilvert** [comment]
@pedroigor I guess that's up to you.  The UI team will be rewriting much of the account console and we will probably start in Q3.  But we don't have time to add new features until then. 

So if you want to wait until then, we can just add this to the requirements in Q3.

**Comment by vmichelin-cpage** [comment]
"We did not change the account console to leverage UP capabilities." -> Ok, i understand now white custom attributes added not appears in the user account console.
Still Q3 for this evolution ? Keycloak 20 ?

**Comment by ssilvert** [comment]
@vmichelin-cpage We have started looking at this, but I wouldn't expect anything until Q4.  Admin console will be done first.  Then account console.  Both might still make Keycloak 20.

**Comment by pedroigor** [comment]
@ssilvert Isn't this already solved?

**Comment by ssilvert** [comment]
@pedroigor Yes.  Dynamic rendering of user profile attributes is in admin console V2 and account console V3.  

Account V3 is in tech preview, but we plan for it to become the default in the next major release.

**Comment by ssilvert** [comment]
@pedroigor Oh, if you are referring to the original issue description, it looks like this is not solved.

**Comment by ssilvert** [comment]
This will not be fixed in Account Console V2.  It will be fixed in Account Console V3 via #23600
