### ISSUE TITLE
log-file-enabled is no longer recognized in 18.0.0

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak#11661]
### Describe the bug

In Quarkus based release 17.0.0 & 17.0.1 it was possible to set those logging settings
```
# logging file
log-file-format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c:%L] [%t] %s%e%n
log-file-enabled=true
log-file-level=trace
log-file=/opt/logfiles/keycloak.log
```

Since 18.0.0 I get this inaccurate error output
`2022-04-26 09:59:24,865 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Invalid values in list for key: log Values: true. Possible values are a combination of: console,file
`

At the end it is the flag `log-file-enabled=true`, but the error log says something meaningless

The source code still contains the flag at this place:
https://github.com/keycloak/keycloak/blob/18.0.0/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/LoggingPropertyMappers.java#L111

### Version

18.0.0

### Expected behavior

Usage of flag `log-file-enabled` ist still working as long it's in the LoggingPropertyMappers.java

**Comment by emikolajczak** [comment]
Hi,
It seems that configuration changed in 18.0.0
https://www.keycloak.org/server/logging

For me is working with below parameters
```
log=console,file
log-file=<path_to_file>
```

**Comment by DGuhr** [comment]
As stated, the configuration changed here, sorry for the inconvenience. Will close here for now.

**Comment by psytester** [comment]
Yes, you are right `log=file,console` is doing its job and logging documentation contains this change (now).
