### ISSUE TITLE
parameter `url` unused in function `loadConfig` ? 

### ISSUE THREAD

**Issue by RossRogers** [keycloak/keycloak#11674]
### Describe the bug

Apologies if this isn't a bug, but [`function loadConfig(url) {`](https://github.com/keycloak/keycloak/blob/8d3a4803bbb17f39ee8fd60f8a192a6c47fb2247/adapters/oidc/js/src/keycloak.js#L796) doesn't seem to use parameter `url`.  Is this intended behavior due to backwards compatiblity?  If it is, can the parameter name be changed to `unused` or `_`?   

The reason I'm inspecting this code is that in our environment, keycloak is inexplicably loading `/keycloak.json` on occasion even though we're supplying a different url to the root `Keycloak` object.  Should this section:

```
        if (!config) {
            configUrl = 'keycloak.json';
        } else if (typeof config === 'string') {
            configUrl = config;
        }
```

actually be
```
        if (!config) {
            if (url) { 
                configUrl = url;
            } else {
                configUrl = 'keycloak.json';
            }
        } else if (typeof config === 'string') {
            configUrl = config;
        }
```

_We're using an old version of keycloak, but I see this variable being unused on the tip of the trunk_

### Version

16.1

### Expected behavior

An unused parameter seems to be incorrect by inspection.

**Comment by jonkoops** [comment]
Yes, this variable in unused. The actual variable that is used for the URL is in the same scope. I've since removed this code, so this issue is resolved.
