### ISSUE TITLE
Unexpexted result get list users with multiple query param in Keycloak REST API

### ISSUE THREAD

**Issue by kresnasatya** [keycloak/keycloak#11676]
### Describe the bug

Step to produce:
1. Add two users with different attribute (e.g. `userType`). I put JSON as example.

```json
[
    {
        "id": "281a74a1-836f-4a4c-b2b0-10cf521d97f0",
        "username": "kresnasatya",
        "enabled": true,
        "emailVerified": false,
        "firstName": "112233",
        "lastName": "Putu Satya Kresna Adi Pratama",
        "email": "satyakresna@test.com",
        "attributes": {
            "userType": [
                "3"
            ]
        }
    },
    {
        "id": "4f56c0cd-e383-4491-9ed7-e5eb5efb220f",
        "username": "kresnayogiswara",
        "enabled": true,
        "emailVerified": false,
        "firstName": "11223344",
        "lastName": "Kresna Yogiswara",
        "email": "kresnayogiswara@test.com",
        "attributes": {
            "userType": [
                "1"
            ]
        }
    }
]
```

2. Search user that have name `kresna` and user type is `3` via Keycloak REST API. Here's the example of URL request.

URL Request: `http://localhost:8180/auth/admin/realms/tester/users?search=*kresna*&q=userType:3`

### Version

17.0.1 to 18.0.0

### Expected behavior

Keycloak should show result with name kresna (`search=*kresna*`) and userType 3 (`q=userType:3`) as below.

```json
[
    {
        "id": "281a74a1-836f-4a4c-b2b0-10cf521d97f0",
        "createdTimestamp": 1651027850758,
        "username": "kresnasatya",
        "enabled": true,
        "totp": false,
        "emailVerified": false,
        "firstName": "112233",
        "lastName": "Putu Satya Kresna Adi Pratama",
        "email": "satyakresna@test.com",
        "federationLink": "18951d6c-d444-4538-b0c2-8e137d05665b",
        "attributes": {
            "userType": [
                "3"
            ],
            "LDAP_ENTRY_DN": [
                "uid=kresnasatya,ou=users,dc=example,dc=org"
            ],
            "LDAP_ID": [
                "97adcb2e-5a20-103c-96c7-a12823b6849a"
            ],
            "modifyTimestamp": [
                "20220427025604Z"
            ],
            "createTimestamp": [
                "20220427025050Z"
            ]
        },
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    }
]
```

### Actual behavior

Keycloak show result with name kresna (`search=*kresna*`) and ignore userType 3 (`q=userType:3`) param as below.

```json
[
    {
        "id": "281a74a1-836f-4a4c-b2b0-10cf521d97f0",
        "username": "kresnasatya",
        "enabled": true,
        "emailVerified": false,
        "firstName": "112233",
        "lastName": "Putu Satya Kresna Adi Pratama",
        "email": "satyakresna@test.com",
        "attributes": {
            "userType": [
                "3"
            ]
        }
    },
    {
        "id": "4f56c0cd-e383-4491-9ed7-e5eb5efb220f",
        "username": "kresnayogiswara",
        "enabled": true,
        "emailVerified": false,
        "firstName": "11223344",
        "lastName": "Kresna Yogiswara",
        "email": "kresnayogiswara@test.com",
        "attributes": {
            "userType": [
                "1"
            ]
        }
    }
]
```

### How to Reproduce?

Already describe on bug.

**Comment by rmartinc** [comment]
@kresnasatya You are right, as it's explained in the count endpoint the `search` option is [exclusive to the other options](https://github.com/keycloak/keycloak/blob/20.0.5/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L350-L353). In the `getUsers` was the same and after some changes [the same behavior is there](https://github.com/keycloak/keycloak/blob/20.0.5/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L285-L300). It's just the `search` option, all the other parameters are combined with a logical and for example `email=ricky@lala.com&enabled=false&q=attr1:value`.

As this is a minor issue I'm going to assign the help-wanted and move it to backlog. If someone wants to help here it would be much appreciated.

**Comment by gregawoods** [comment]
Ran into this issue as well. I understand the explanation, however, it _would_ be super useful if an option existed to use both search parameters at once.

**Comment by pedroigor** [comment]
Marking as `normal` due to the number of requests for the same fix. As per https://github.com/keycloak/keycloak/issues/16687.
