### ISSUE TITLE
Remove adapters that are EOL in Keycloak 19

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#11680]
### Description

First round of adapters to be removed are scheduled for Keycloak 19. These include:

* Fuse 6 and 7 (OIDC)
* JBoss AS 7 and EAP 6 (OIDC and SAML)
* Jetty 9.2 and 9.3 (OIDC and SAML)
* Spring Boot 1 (OIDC)
* WildFly legacy (non-Elytron, OIDC and SAML)
* WildFly Galleon Feature pack (OIDC)

### Discussion

https://github.com/keycloak/keycloak/discussions/categories/adapter-deprecation

### Issues

* https://github.com/keycloak/keycloak/issues/11604
* https://github.com/keycloak/keycloak/issues/11677
* https://github.com/keycloak/keycloak/issues/11683
* https://github.com/keycloak/keycloak/issues/11690
* https://github.com/keycloak/keycloak/issues/11791
* https://github.com/keycloak/keycloak-web/issues/308
* https://github.com/keycloak/keycloak-documentation/issues/1510
* https://github.com/keycloak/keycloak-quickstarts/issues/318

**Comment by stianst** [comment]
@hmlnarik @mposolda now that we are removing the legacy WildFly adapter and Fuse adapters, does that also mean we can remove the Undertow adapter already now? Or, is that also used by the Elytron adapter?

**Comment by stianst** [comment]
@hmlnarik @mposolda  since we are removing Fuse adapters, does that also mean we can remove the OSGI adapter (+ Karaf). I don't think that's used outside of Fuse right?

**Comment by vramik** [comment]
> @hmlnarik @mposolda @vramik since we are removing Fuse adapters, does that also mean we can remove the OSGI adapter (+ Karaf). I don't think that's used outside of Fuse right?

AFAIK that's right

**Comment by stianst** [comment]
> > @hmlnarik @mposolda @vramik now that we are removing the legacy WildFly adapter and Fuse adapters, does that also mean we can remove the Undertow adapter already now? Or, is that also used by the Elytron adapter?
> 
> The Elytron adapter does not seem to use `keycloak-undertow-adapter` as it's dependency. So undertow adapter is probably not needed for elytron.
> 
> Another thing is, that undertow adapter is currently used in our testsuite as the "default" adapter for example when running adapter tests from IDE. It is quite convenient to use it for debugging various stuff related to adapter tests as it doesn't need any "special" server to be prepared in the testsuite and debug. So my personal vote is to keep undertow adapter due this (unless we remove all the other adapters and adapter tests right away).
> 
> But that is just my 2 cents and I don't insist on it :-)

I don't see an issue with keeping the undertow adapter around for now, so let's do that
