### ISSUE TITLE
Under heavy load, DefaultBruteForceProtector blocks the whole system

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#11699]
### Describe the bug

I have 2 keycloak nodes running on version 12.0.1 . Each with a postgres max pool size of 40. Brute force protection is enabled on the realm.

When reaching a huge number of users trying to authenticate, the database pool is exhausted.

216 threads end up waiting for a database connection. 39 threads end up waiting for DefaultBruteForceProtector. Each of those 39 threads are certainly holding a database connection. And DefaultBruteForceProtector is itself waiting for a database connection. You can take a look at [jstack](https://issues.redhat.com/secure/attachment/12509439/12509439_jstack)

Maybe DefaultBruteForceProtector should have a dedicated database connection pool (e.g. with a size of 1) to avoid this situation?

![Screenshot from 2021-05-05 16-21-08](https://user-images.githubusercontent.com/2890843/165524457-a85c82dd-109d-439e-bf39-e86f6cf49c4c.png)

[jstack.txt](https://github.com/keycloak/keycloak/files/8572226/jstack.txt)

### Version

12.0.1

### Anything else?

https://issues.redhat.com/browse/KEYCLOAK-17002

**Comment by mposolda** [comment]
Adding to Keycloak 23 for now, but we may postpone.

It is a problem, however fixing this can be non-trivial effort. We may need some discussion for how exactly this should be done and it should be properly planned.

Some more details in the JIRA https://issues.redhat.com/browse/KEYCLOAK-17002

**Comment by douglaspalmer** [comment]
Is Permanent Lockout enabled?

**Comment by reda-alaoui** [comment]
@douglaspalmer , no, as you can see on the screenshot.

**Comment by douglaspalmer** [comment]
Can you please try this with Keycloak 22?

**Comment by reda-alaoui** [comment]
@douglaspalmer , I have no easy way to try, sorry.
