### ISSUE TITLE
Support for ARTIFACT binding in brokering scenario

### ISSUE THREAD

**Issue by maaroen** [keycloak/keycloak#11705]
### Description

Follow up for this item:
https://issues.redhat.com/browse/KEYCLOAK-9993

I think many people would like to be able to use HTTP Artifact binding in the Identity Broker scenario.

**Comment by pedroigor** [comment]
As per https://github.com/keycloak/keycloak/issues/14073, we now support Artifact Binding when running SP-Initiated SSO.

**Comment by maaroen** [comment]
Alright, thanks for the feedback @pedroigor !
