### ISSUE TITLE
Redirect URL from "Reset password" dialog not used correctly within "password-change" dialog

### ISSUE THREAD

**Issue by Robiwahn23** [keycloak/keycloak#11701]
### Describe the bug

We have a website with keycloak authenticatation.
The website is tenant-specific. So an URL looks something like "foobar.com/tenant/". 
From here normal rediect to the KC-login page is happening.
After logging in the redirect to "foobar.com/tenant/" just works fine.

But if i click "Password forgotten", and using the received link to change the password, the redirect after changing the password just points to "foobar.com" ... 
Is there any way to change this behaviour?

### Version

16.1.1

### Expected behavior

The redirect after password change should use the same URL to redirect as the normal login page does.

### Actual behavior

The redirect after password change redirects NOT to the given redirection-url but instead it redirects only to the hosts part of it and ignores the path.

### How to Reproduce?

See descrption.

**Comment by Robiwahn23** [comment]
Anyone an idea how to solve this?

**Comment by Robiwahn23** [comment]
Anyone? :)

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
