### ISSUE TITLE
LDAP user attribute is not updated in local database

### ISSUE THREAD

**Issue by maciej-zabielski** [keycloak/keycloak#11730]
### Describe the bug

LDAP user attribute is not updated in local database even if set to "Always Read Value From LDAP".

1. Create a Realm and connect to LDAP with User Federation
2. In mappers section add mapper for desired attributes, e.g. **lastName**
3. Make sure the attribute has the **"Always Read Value From LDAP"**  option turned on.
5. Import all users by using Synchronize all users option
6. Observe the value for last name for selected user, e.g. "MyLastName1", go into user details panel and see that the Last Name is also correct there. 
7. Go to your LDAP directory (e.g. Active Directory) - edit the user name to e.g "MyLastName2".
8. Go back to users list in Keycloak. Notice that the Last Name is udpated on the user list as expected to "MyLastName2"
9. Open user details panel (click on user GUID), the Last Name is not udpated here, it will still be "MyLastName1"

Attribute in question will remain with it's old value for as long as we run one of the functions:
- Synchronize changed users
- Synchronize all users
- run Periodic Changed Users Sync

If this is not a bug, theh what is the point in reading the attributes from LDAP each time, when they are not used later on (application and other realms will recieve the "old" value)

### Version

17, 18

### Expected behavior

User attribute should be updated in all places when a new value is read from LDAP. 

### Actual behavior

User list seems to be showing a "live data" from LDAP, and user details panel seems to be showing a local value that is not udpated. 

### Anything else?

I have tried both UNSYNCED and READ_ONLY LDAP modes.

**Comment by mhajas** [comment]
@maciej-zabielski Thank you for reporting the bug and sorry for late response. I was not able to reproduce this. Could you please try the latest Keycloak version? Or could you please have a look at the code that follows whether it matches your scenario?

If you want to run the provided test locally you can add this to [`UserSyncTest`](https://github.com/keycloak/keycloak/blob/main/testsuite/model/src/test/java/org/keycloak/testsuite/model/UserSyncTest.java) and run model tests with `legacy-jpa-federation+ldap+infinispan` profile enabled.
```
mvn clean install -f testsuite/model/pom.xml -Plegacy-jpa-federation+ldap+infinispan -Dtest=UserSyncTest#testIssue11730
```

Please let me know if I missed something. Here is the test:
```java
@Test
public void testIssue11730() {
    // create 5 users in LDAP
    IntStream.range(0, 5).parallel().forEach(index -> inComittedTransaction(index, (session, i) -> {
        final RealmModel realm = session.realms().getRealm(realmId);

        ComponentModel ldapModel = LDAPTestUtils.getLdapProviderModel(realm);
        LDAPStorageProvider ldapFedProvider = LDAPTestUtils.getLdapProvider(session, ldapModel);
        LDAPTestUtils.addLDAPUser(ldapFedProvider, realm, "user" + i, "User" + i + "FN", "User" + i + "LN", "user" + i + "@email.org", null, "12" + i);
        return null;
    }));

    // Create mapper from sn to a new user attribute
    withRealm(realmId, (session, realm) -> {
        UserStorageProviderModel providerModel = new UserStorageProviderModel(realm.getComponent(userFederationId));
        // Create mapper
        ComponentModel mapperModel = KeycloakModelUtils.createComponentModel("My-mapper", providerModel.getId(), UserAttributeLDAPStorageMapperFactory.PROVIDER_ID, LDAPStorageMapper.class.getName(),
                UserAttributeLDAPStorageMapper.USER_MODEL_ATTRIBUTE, "myAttr",
                UserAttributeLDAPStorageMapper.LDAP_ATTRIBUTE, "sn",
                UserAttributeLDAPStorageMapper.READ_ONLY, "false",
                UserAttributeLDAPStorageMapper.ALWAYS_READ_VALUE_FROM_LDAP, "true",
                UserAttributeLDAPStorageMapper.IS_MANDATORY_IN_LDAP, "false");
        realm.addComponentModel(mapperModel);

        return null;
    });

    // Read attribute that should be mapped by created mapper
    withRealm(realmId, (session, realm) -> {
        UserModel collect = session.users().getUserByUsername(realm, "user1");
        System.out.println(collect.getFirstAttribute("myAttr"));
        return null;
    });

    // Check local storage contains imported user
    withRealm(realmId, (session, realm) -> {
        int collect = UserStoragePrivateUtil.userLocalStorage(session).getUsersCount(realm);
        System.out.println(collect);
        return null;
    });

    // Change last name to a new value but only in LDAP
    withRealm(realmId, (session, realm) -> {
        ComponentModel ldapModel = LDAPTestUtils.getLdapProviderModel(realm);
        LDAPStorageProvider ldapFedProvider = LDAPTestUtils.getLdapProvider(session, ldapModel);

        UserModel user1 = ldapFedProvider.getUserByUsername(realm, "user1");
        user1.setLastName("NewLastName");
        return null;
    });

    // Check local storage contains the old value
    withRealm(realmId, (session, realm) -> {
        UserModel collect = UserStoragePrivateUtil.userLocalStorage(session).getUserByUsername(realm, "user1");
        System.out.println(collect.getFirstAttribute("myAttr"));

        return null;
    });


    // Read from Keycloak and check the value of myAttr read from LDAP even though local storage contains old value
    withRealm(realmId, (session, realm) -> {
        UserModel collect = session.users().getUserByUsername(realm, "user1");
        System.out.println(collect.getFirstAttribute("myAttr"));
        return null;
    });
}
```

This results in the following output:
```
User1LN
1
User1LN
NewLastName // this should be equal to User1LN based on your report
```

**Comment by maciej-zabielski** [comment]
Hi @mhajas  - I'm not sure if the test relates 1:1 to what happens in KC in this situation, but generally it seems like a similar "flow". I have just tested on KC 19 and KC 20 and the problem is still there. 

The important part is that the main user list gets updated value - but not the "details" page. 

To make sure we are talking about the same thing, below is a picture showing the details:
- top window shows a main users list in KC realm - you can see the last name, that just got updated in AD and it is the same as on the AD screen shot (with X2 at the end)
- when you click on user GUID to see details, the last name is NOT updated there, still having previous value with X1 at the end. 
- when this user is connected to another realm in KC, user there will also not be updated. 
- clearing users cache does not help, only when I use "Synchronize changed users" from User Federation

![kc_attributes](https://user-images.githubusercontent.com/25347055/205321723-a18b91b7-8686-4c1d-ab1c-e8642867990c.jpg)

**Comment by mhajas** [comment]
Hmm, thank you for more details. It seems there is a different result based on the endpoint call `list users` vs `detail of one user` I will try to incorporate it into the test.

**Comment by mhajas** [comment]
Hello @maciej-zabielski, sorry for thelate reply. I was able to reproduce this. The issue is caused by caching. If we find the entry in the cache, we are returning the cached value and not checking whether anything changed in LDAP. 

I updated the reproducer from above to follow your steps:
```java
    @Test
    public void testIssue11730() {
        // create 5 users in LDAP
        IntStream.range(0, 5).parallel().forEach(index -> inComittedTransaction(index, (session, i) -> {
            final RealmModel realm = session.realms().getRealm(realmId);

            ComponentModel ldapModel = LDAPTestUtils.getLdapProviderModel(realm);
            LDAPStorageProvider ldapFedProvider = LDAPTestUtils.getLdapProvider(session, ldapModel);
            LDAPTestUtils.addLDAPUser(ldapFedProvider, realm, "user" + i, "User" + i + "FN", "User" + i + "LN", "user" + i + "@email.org", null, "12" + i);
            return null;
        }));

        // Read attribute that should be mapped by created mapper
        String id = withRealm(realmId, (session, realm) -> {
            UserModel collect = session.users().getUserByUsername(realm, "user1");
            System.out.println("LastName value: " + collect.getLastName());
            return collect.getId();
        });

        // Change last name to a new value but only in LDAP
        withRealm(realmId, (session, realm) -> {
            ComponentModel ldapModel = LDAPTestUtils.getLdapProviderModel(realm);
            LDAPStorageProvider ldapFedProvider = LDAPTestUtils.getLdapProvider(session, ldapModel);

            System.out.println("Updating LastName value in Ldap.");
            updateLastnameInLdap(session, ldapFedProvider, realm, "user1", "testLastName");
            return null;
        });

        // Check local storage contains the old value
        withRealm(realmId, (session, realm) -> {
            UserModel collect = UserStoragePrivateUtil.userLocalStorage(session).getUserById(realm, id);
            System.out.println("Keycloak local storage LastName value: " + collect.getLastName());
            return collect.getId();
        });

        // Read from Keycloak by Id
        withRealm(realmId, (session, realm) -> {
            UserModel collect = session.users().getUserById(realm, id);
            System.out.println("Reading by id LastName value: " + collect.getLastName());
            return null;
        });

        // Read from Keycloak by searching
        withRealm(realmId, (session, realm) -> {
            UserModel collect = session.users().searchForUserStream(realm, Collections.emptyMap()).findFirst().orElse(null);
            System.out.println("Searching LastName value: " + collect.getLastName());
            return null;
        });
    }

    public static void updateLastnameInLdap(KeycloakSession session, LDAPStorageProvider ldapProvider, RealmModel realm, String username, String newLastName) {
        LDAPObject ldapObject = ldapProvider.loadLDAPUserByUsername(realm, username);
        LDAPOperationManager ldapOperationManager = new LDAPOperationManager(session, ldapProvider.getLdapIdentityStore().getConfig());

        BasicAttribute basicAttribute = new BasicAttribute("sn", newLastName);
        ldapOperationManager.modifyAttribute(ldapObject.getDn().toString(), basicAttribute);

    }
```

Output with Infinispan caching enabled:
```
LastName value: User1LN
Updating LastName value in Ldap.
Keycloak local storage LastName value: User1LN
Reading by id LastName value: User1LN
Searching LastName value: testLastName
```
Output without Infinispan:
```
LastName value: User1LN
Updating LastName value in Ldap.
Keycloak local storage LastName value: User1LN
Reading by id LastName value: testLastName
Searching LastName value: testLastName
```

See the difference between `Reading by id LastName value` with/without caching

**Comment by hmlnarik** [comment]
Possibly related: #10412
