### ISSUE TITLE
Remove `session.area().getById(id)` from Map provider methods

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#11744]
### Description

Currently, for some queries, we obtain just ids of entities that fulfil the search and then call `getById` method. This was done so the legacy cache can store the entity which results in less traffic from the database (in other words, we load just ids from DB and ask the cache whether the entity is already present in the caching layer).

After disabling legacy cache in new storage we no longer want that, because the caching is solved differently. 

An example:
https://github.com/keycloak/keycloak/blob/2474ca73f9b9aac3f62180634e9485efcdb75fdf/model/map/src/main/java/org/keycloak/models/map/authorization/MapPolicyStore.java#L156

**Comment by hmlnarik** [comment]
Relates to #10376.
