### ISSUE TITLE
invalid_client response code does not correspond oauth spec

### ISSUE THREAD

**Issue by tchrobocek** [keycloak/keycloak#11741]
### Describe the bug

Hey, I'm looking at invalid_client error response and it returns status code 400 instead of 401.

https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

> If the client attempted to authenticate via the "Authorization" request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code and include the "WWW-Authenticate" response header field matching the authentication scheme used by the client.

### Version

18.0.0

### Expected behavior

Should return status code 401

### Actual behavior

Returns status code 400

### How to Reproduce?

Request token endpoint with bad client id

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
