### ISSUE TITLE
Declarative User Profile: local-date validation and html5-date clash

### ISSUE THREAD

**Issue by ThoreKr** [keycloak/keycloak#11757]
### Describe the bug

When creating a user profile with a birthday attribute which should be displayed with a date picker in the registration dialogue this input will always fail validation when using local-date-validation.

### Version

18.0.0

### Expected behavior

The user is created and has the attribute birthday set as iso 8601 date.

### Actual behavior

The birthday field is flagged as invalid.

![image](https://user-images.githubusercontent.com/5465291/165805491-ea75e524-ca4c-4fff-aa59-fd12e0d00657.png)

Another interesting sidenote: The date format in the date picker didn't change with a localization change.

In the form data I can see it being sent as:
```
birthday: 2022-01-01
```

### How to Reproduce?

In a realm with declarative user profile with the following configuration:

```
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {}
      }
    },
    {
      "name": "email",
      "displayName": "${email}",
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      }
    },
    {
      "selector": {
        "scopes": []
      },
      "permissions": {
        "view": [
          "user",
          "admin"
        ],
        "edit": [
          "user",
          "admin"
        ]
      },
      "name": "birthday",
      "displayName": "Birthday",
      "required": {
        "roles": [],
        "scopes": []
      },
      "validations": {
        "local-date": {}
      },
      "annotations": {
        "inputType": "html5-date"
      }
    }
  ]
}
```

Then try to register a new account.

**Comment by pedroigor** [comment]
This should be fixed by introducing `converters` as per https://github.com/keycloak/keycloak-community/blob/main/design/user-profile.md#converter-optional.

Right now, we can't validate values from `date` input type because they are sent in the wire using the [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) format. The `date` input type is defined to use this specification to format values.

**Comment by MLukman** [comment]
I encountered the same issue in 24.0.2

**Comment by ThoreKr** [comment]
I "solved" this by writing my own isoformat validator, which tries to parse y-m-d.

**Comment by pedroigor** [comment]
@ThoreKr Nice, we really need to have this as a built-in capability instead ...

**Comment by ThoreKr** [comment]
@pedroigor Should I create a pr for it?

**Comment by pedroigor** [comment]
Do you think it will be generic enough so others can use? Also, are you using the validator to actually change the value of the attribute?

**Comment by ThoreKr** [comment]
It is just validating that the input must have been generated by a datepicker (conforming to is 8601 or rfc3339) and for additional flavour allow for upper and lower bound checks. It doesn't do any tranformations as i want it to retain compatibility to the date picker so the user can edit it again later.
