### ISSUE TITLE
Configure Otp with manual url is not generating the url correctly when keycloak is behind a reverse proxy on an url like http://www.host.com/auth

### ISSUE THREAD

**Issue by DamienBoue** [keycloak/keycloak#11774]
### Describe the bug

We have a keycloak that is running on an url like http://www.host.com/auth

There is a reverse proxy that is redirecting every request on http://ip:another_port/auth on a docker that expose keycloak on http://ip:port/

The TotpBean is getting an uriBuilder in its contructor. This UriBuilder corresponds to the UriInfo where the request is arriving, it's not based on the keycloak configuration that is defining the correct host and path

### Version

17.0.0

### Expected behavior

The request generated by the TotpBean for the manual url should be http://www.host.com/auth/manualUrl

### Actual behavior

The request generated by the TotpBean for the manual url is http://host.com/manualUrl

### How to Reproduce?

1 - Use a reverse proxy like apache or nginx
2 - Make Your keycloak run on ip:port/
3 - Reverse proxy the url on ip:another_port/auth on your keycloak that is running ip:port/
4 - Go to the OTP configuration page
5 - Try to switch on manual URL, the url is pointing on /manualUrl and not on /auth/manualUrl

**Comment by GandalfUFR** [comment]
Additionally to the above there is also the port (8443) missing in the URL when behind a proxy. Going directly to the Keycloak server it works as expected.

![image](https://user-images.githubusercontent.com/26733934/177539131-cbf15b53-1285-4b3d-9bd0-e0e917b5fa12.png)

**Comment by RobYed** [comment]
We encountered exactly the same problem when running Keycloak in docker behind a reverse proxy. Would be great to see it fixed :)

**Comment by RobYed** [comment]
Minimal steps to reproduce the bug:

1. Build and start a nginx reverse proxy with Dockerfile: 
```
FROM nginx:latest
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
```
and default.conf:
```
server {
  listen 80;
  listen [::]:80;
  server_name localhost;

  location = /auth {
    return 302 /auth/;
  }
  location /auth/ {
    proxy_pass http://192.168.2.101:8080/;

    proxy_set_header    Host                $http_host;
    proxy_set_header    X-Real-IP           $realip_remote_addr;
    proxy_set_header    X-Forwarded-Proto   $scheme;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
```
2. Start a local Keycloak in dev mode with the following hostname settings:
```
java -jar server/target/lib/quarkus-run.jar start-dev --proxy=passthrough --hostname=localhost --hostname-path=/auth --hostname-admin=localhost/auth --hostname-strict-https=false --hostname-strict=true --hostname-strict-backchannel=true
```
3. Access the account console: http://localhost/auth/realms/master/account/
4. Click "Set up authenticator application" to open totp setup
5. Click "Unable to scan?"

Keycloak will be send you to http://localhost/realms/master/login-actions/required-action[...] which is missing the /auth path.

**Comment by stianst** [comment]
This change shouldn't be needed as uriInfo should already be the front-end url. Have you properly configured the hostname for Keycloak? I.e. take a look at the openid connect well-known endpoints and make sure they have the correct URLs.

**Comment by RobYed** [comment]
Thanks @stianst for your response. We thoroughly configured our Keycloak instance including the host settings. We have a fully-tested production-ready [release of our application](https://github.com/hzi-braunschweig/pia-system), everything is working fine, except that single OTP Link.

As you suggested I checked the well-known endpoints ([on our pre-release stage](https://pia-release.netzlink.com/api/v1/auth/realms/pia-proband-realm/.well-known/openid-configuration)) and they all contain the correct URLs. The URL which is called in the OTP form is not included there at all.
