### ISSUE TITLE
Session fixation fix in keycloak 12.04 version

### ISSUE THREAD

**Issue by Naveenrajelothunkal** [keycloak/keycloak#11788]
### Describe the bug

Once user successfully login to keycloak , it does not reset session id (AUTH_SESSION_ID) to fix session fixation issue. 

Authenticating a user but failing to provision a new session identifier gives an attacker the opportunity to steal authenticated sessions of victim users. This attack breaks the data confidentiality and integrity of victim users.

A typical session fixation attack is composed of three steps:•The attacker acquires a session ID by either directly crafting one or visiting the target web application (without logon)
•The attacker causes the victim to visit the target web application with the session ID from Step 1 and log in. Thus, the session ID becomes associated with the victim. Depending on the location of session ID in the requests (cookie, query, or post parameter) and application context, the attacker can do this through a combination of social engineering techniques (email, IM) and technical attacks including (but not limited to) XSS and cross-subdomain cooking
•The attacker can now use the authenticated session ID from Step 2 to access and manipulate web resources owned by the victim user

### Version

12.04

### Expected behavior

Once user logged in successfully , session id should reset.

The best way to prevent session fixation attacks is to renew the session ID when a user logs in. This fix can be done at the code level or framework level, depending on where the session management functionality is implemented. Example 1: the following PHP code changes the session ID after users log in successfully: 

    If ($authenication_successful) { 
        $_session[“authenticated”] = true;
        Session_regenerate_id();
    }

### Actual behavior

AUTH_SESSION_ID still be saved in browser cookie even after user successfully logged in.

### How to Reproduce?

Login with keycloak and observe session id(AUTH_SESSION_ID) in browser cookie is reseting or not. Use mozila browser please.

**Comment by Naveenrajelothunkal** [comment]
I have not received any input yet. If you have any input, I’d love to hear it. Thanks.

**Comment by chihhaohuang** [comment]
Is there any update/progress on this issue?

**Comment by mposolda** [comment]
@Naveenrajelothunkal @chihhaohuang This is improved in the latest Keycloak 20.0.2 release, which was released yesterday. Hence I suggest to re-test with this latest version. The related commit is: https://github.com/keycloak/keycloak/commit/0f2ca3bfddeeeece06cae4cbd1f7122adb261eed

So I am closing this issue for now. If you still have more feedback to this issue, I suggest to start a thread on keycloak-security ML instead of discussing it here as it is security related. See https://www.keycloak.org/security.html for the details.

For the future, please directly use rather the "security" channels instead of reporting security related issues here in public.

**Comment by chihhaohuang** [comment]
Looks like it is not fixed, AUTH_SESSION_ID remains the same after successfully login.
Also when relogin after login timeout, it still uses the same AUTH_SESSION_ID, so not sure what is the point to timeout.
Tested by using admin console.
I can see AUTH_SESSION_ID in Request Headers in .../openid-connect/auth?... endpoint.
Once I logged in, this AUTH_SESSION_ID remains the same in the Cookie.

**Comment by Zhiyuan-Amos** [comment]
> Looks like it is not fixed, AUTH_SESSION_ID remains the same after successfully login.

After logging in, you can try dropping this cookie and observe that you are still logged in. So, even though the value of this cookie is the same pre-login and post-login, it seems that `AUTH_SESSION_ID` isn't used anymore.

Unless the value of the real identity cookie (either `KEYCLOAK_IDENTITY` or `KEYCLOAK_SESSION`) is a deterministic value generated from `AUTH_SESSION_ID`, I don't think this is a security concern.

From the [documentation](https://github.com/keycloak/keycloak/blob/98dc21e6fc2b5a46b18d8ee5f9f1d271d8bf5ffe/docs/guides/server/reverseproxy.adoc#enable-sticky-sessions), it looks like `AUTH_SESSION_ID` is used for sticky sessions when using a load balancer.

**Comment by eldhoissc** [comment]
> > Looks like it is not fixed, AUTH_SESSION_ID remains the same after successfully login.
> 
> After logging in, you can try dropping this cookie and observe that you are still logged in. So, even though the value of this cookie is the same pre-login and post-login, it seems that `AUTH_SESSION_ID` isn't used anymore.
> 
> Unless the value of the real identity cookie (either `KEYCLOAK_IDENTITY` or `KEYCLOAK_SESSION`) is a deterministic value generated from `AUTH_SESSION_ID`, I don't think this is a security concern.
> 
> From the [documentation](https://github.com/keycloak/keycloak/blob/98dc21e6fc2b5a46b18d8ee5f9f1d271d8bf5ffe/docs/guides/server/reverseproxy.adoc#enable-sticky-sessions), it looks like `AUTH_SESSION_ID` is used for sticky sessions when using a load balancer.

New cookie, “KEYCLOAK_SESSION,” is follows the format {realm}/{userId}/{AUTH_SESSION_ID}.
session ID remains same right?

**Comment by Zhiyuan-Amos** [comment]
> New cookie, “KEYCLOAK_SESSION,” is follows the format {realm}/{userId}/{AUTH_SESSION_ID}.
session ID remains same right?

@eldhoissc you're right.

**Comment by eldhoissc** [comment]
> remains same right?

Its a security issue ?

**Comment by eldhoissc** [comment]
> > New cookie, “KEYCLOAK_SESSION,” is follows the format {realm}/{userId}/{AUTH_SESSION_ID}.
> > session ID remains same right?
> 
> @eldhoissc you're right.

Its a security issue ?

**Comment by Zhiyuan-Amos** [comment]
@eldhoissc I don't think so. I retract one of my earlier edits on https://github.com/keycloak/keycloak/issues/11788#issuecomment-2310203517 - looks like the cookie that grants authenticated access is `KEYCLOAK_IDENTITY`, not `KEYCLOAK_SESSION`. `KEYCLOAK_IDENTITY` isn't a deterministic value generated from `AUTH_SESSION_ID` I think.

**Comment by eldhoissc** [comment]
@Zhiyuan-Amos 
KEYCLOAK_IDENTITY contains a token (JWT) with the user ids. You can view its content using [jwt.io](https://jwt.io/) (for example). This cookie lives with your browser session and can also be refreshed with SSO. (for example, if you change some of your personal data in the "Manage my account")

KEYCLOAK_SESSION your session id associated to the concerned realm.

**Comment by Zhiyuan-Amos** [comment]
@eldhoissc yes I am aware that `KEYCLOAK_IDENTITY` is a JWT. But because it isn't a deterministic value generated from `AUTH_SESSION_ID` (I think), so Session Fixation attack can't occur.

> KEYCLOAK_SESSION your session id associated to the concerned realm.

Yes, but `KEYCLOAK_SESSION` isn't used by Keycloak to grant authenticated access. You can try copying and pasting this cookie into a separate browser and observe that nothing happens.
