### ISSUE TITLE
Support for multiple SAML_REQUEST_ID_BROKER IDs

### ISSUE THREAD

**Issue by rmoqpd5t** [keycloak/keycloak#11787]
### Describe the bug

Only two SAML request IDs (SAML_REQUEST_ID and SAML_REQUEST_ID_BROKER) are currently supported.  Conceptually _n_ SAML_REQUEST_ID_BROKER IDs should be supported.  This change would be required to 'daisy chain' (i.e. connect end-to-end) two or more keycloak instances using SAML.

### Version

18.0.0

### Expected behavior

SAMLIdentityProvider.java and SAMLEndpoint.java should support multiple SAML_REQUEST_ID_BROKER values when keycloak instances are connected end-to-end.

### Actual behavior

SAMLIdentityProvider.java and SAMLEndpoint.java only support a single value of SAML_REQUEST_ID_BROKER

### How to Reproduce?

A multi-division enterprise has three SAML IDPs, one authentication instance of keycloak, and multiple authorization instances of keycloak, deployed like this:

```
 [Relying Party #1] --- [ authorization keycloak #1 ] \                                 / [ IDP#1 ]
 [Relying Party #2] --- [ authorization keycloak #2 ] --- [ authentication keycloak ] --- [ IDP#2 ]
 [Relying Party #3] --- [ authorization keycloak #3 ] /                                 \ [ IDP#3 ]
```

The reason for this configuration is to centralize authentication and to decentralize authorization.  'Authenticate globally, authorize locally' are design goals of many large enterprises. Each division's authorization keycloak admins have the access and ability to add claims that are division-specific. Central IT's authentication keycloak is standardized and only it's admins have access.

This example would require three SAML request IDs (SAML_REQUEST_ID, SAML_REQUEST_ID_BROKER#1, and SAML_REQUEST_ID_BROKER#2)

### Anything else?

This issue came to light in testing https://issues.redhat.com/browse/KEYCLOAK-19143 where InResponseTo was incorrectly populated.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by mposolda** [comment]
@rmoqpd5t I don't consider this a bug, but rather an enhancement. Please open an enhancement issue if you still consider this valid (However not sure if Keycloak team has time to implement this as doesn't look like big priority. It would be welcome to contribute PR if you are interested in this functionality).
