### ISSUE TITLE
Scope restricted by a specific realm role is present in consent screen even if the user hasnt' this role

### ISSUE THREAD

**Issue by ahcamy2021** [keycloak/keycloak#11781]
### Describe the bug

KC displays in the consent screen scopes that are not authorised by the user

### Version

17.0.1

### Expected behavior

After authentication, the consent screen could be displayed but it should not contain the scope restricted by the role which is not assigned to the actual user.

### Actual behavior

After authentication, the consent screen is displayed with the client scope 'B' even if the user does not have the role 'A'.

### How to Reproduce?

1- Create a realm role 'A'
2- Create a client scope 'B', activate for it 'Display On Consent Screen' and restrict it by the role created in step 1
3- Create a new client, activate for it 'Consent Required' and add the client scope created in step 2 as an optinal client scope
4- Create a new user without assigning him the role created in step 1
5- Try to request an access token and specifiy in the scope the one created in step 2

### Anything else?

We need to add some logic in [AuthenticationManager.java](https://github.com/keycloak/keycloak/blob/d93115673599a8a77d335197913847570ba7e7e3/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1190) to remove the client scopes that are restricted by role not assigned to the user present in the current session.

the logic is already present in [DefaultClientSessionContext.java](https://github.com/keycloak/keycloak/blob/d93115673599a8a77d335197913847570ba7e7e3/services/src/main/java/org/keycloak/services/util/DefaultClientSessionContext.java#L249) we need just to duplicate it.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
