### ISSUE TITLE
Custom protocol mapper not 'multivalued'

### ISSUE THREAD

**Issue by wimdeblauwe** [keycloak/keycloak#11798]
### Describe the bug

I have a custom protocol mapper with code similar to this:

```
public class GroupsWithRolesTokenMapper extends AbstractOIDCProtocolMapper
        implements OIDCAccessTokenMapper, OIDCIDTokenMapper, UserInfoTokenMapper {

    public static final String PROVIDER_ID = "groups-with-roles-mapper";

    private static final List<ProviderConfigProperty> configProperties = new ArrayList<>();

    static {
        OIDCAttributeMapperHelper.addTokenClaimNameConfig(configProperties);
        OIDCAttributeMapperHelper.addIncludeInTokensConfig(configProperties, GroupsWithRolesTokenMapper.class);
    }

    @Override
    public String getId() {
        return PROVIDER_ID;
    }

    @Override
    public String getDisplayCategory() {
        return TOKEN_MAPPER_CATEGORY;
    }

    @Override
    public String getDisplayType() {
        return "Groups With Roles";
    }

    @Override
    public String getHelpText() {
        return "Map the groups and roles to a custom claim.";
    }

    @Override
    public List<ProviderConfigProperty> getConfigProperties() {
        return configProperties;
    }

    @Override
    protected void setClaim(IDToken token,
                            ProtocolMapperModel mappingModel,
                            UserSessionModel userSession,
                            KeycloakSession keycloakSession,
                            ClientSessionContext clientSessionCtx) {
        List<GroupWithRoles> groups = userSession.getUser().getGroupsStream()
                                                 .map(this::toGroupWithRoles)
                                                 .collect(Collectors.toList());

        if (groups.isEmpty()) {
            // If groups is empty, then OIDCAttributeMapperHelper.mapClaim() does not add the claim at all
            // With this custom code, we ensure that the groups claim is always present, even if the user is
            // currently not in any group
            token.getOtherClaims().put(mappingModel.getConfig().get(TOKEN_CLAIM_NAME), Collections.emptyList());
        } else {
            OIDCAttributeMapperHelper.mapClaim(token, mappingModel, groups);
        }
    }

    // some private methods omitted here to support the setClaim() method

   public static ProtocolMapperModel create(String name,
                                             boolean accessToken,
                                             boolean idToken,
                                             boolean userInfo) {
        // This static method is called automatically by Keycloak when it is present
        // It allows to set the MULTIVALUED attribute to true so we can return a list of things
        ProtocolMapperModel mapper = new ProtocolMapperModel();
        mapper.setName(name);
        mapper.setProtocolMapper(PROVIDER_ID);
        mapper.setProtocol(OIDCLoginProtocol.LOGIN_PROTOCOL);
        Map<String, String> config = new HashMap<>();
        config.put(ProtocolMapperUtils.MULTIVALUED, Boolean.TRUE.toString());
        if (accessToken) {
            config.put(OIDCAttributeMapperHelper.INCLUDE_IN_ACCESS_TOKEN, "true");
        }
        if (idToken) {
            config.put(OIDCAttributeMapperHelper.INCLUDE_IN_ID_TOKEN, "true");
        }
        if (userInfo) {
            config.put(OIDCAttributeMapperHelper.INCLUDE_IN_USERINFO, "true");
        }
        mapper.setConfig(config);
        return mapper;
    }
}
```

Altough I have `config.put(ProtocolMapperUtils.MULTIVALUED, Boolean.TRUE.toString());` in there, the token is not used as `multivalued`. If I manually edit the Keycloak database to set `multivalued` to `true` for the mapper in the `protocol_mapper_config` tabel and restart Keycloak, then it works.

### Version

16.1

### Expected behavior

The `multivalued` key is set to `true` in `protocol_mapper_config` when creating a new client with such a mapper.

### Actual behavior

There is no `multivalued` entry in the `protocol_mapper_config` table.

### How to Reproduce?

Using Keycloak 16.1 with the custom mapper. Create a new client. Create a new mapper for that client of the type of the custom mapper. Check the `protocol_mapper_config` table.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by wimdeblauwe** [comment]
Problem still happens with 21.0.2

**Comment by rmartinc** [comment]
Hi @wimdeblauwe!

The `create` method you are implementing is just a static method that is not called by anything in keycloak. I think that the lines you are adding about being called automatically are incorrect. The idea is that the mapper is created by an admin (console, kcadm,...) and the config passed at that point is the one stored in the database. The `getConfigProperties` is used to create the console options in the admin console (html page). You are not setting the multivalued attribute there, so it won't be there when sent by the console. One easy thing you can do is always adding the option before using it, for example adding this line in the `setClaim` method before callin the `mapClaim`:

```java
    mappingModel.getConfig().put(ProtocolMapperUtils.MULTIVALUED, "true");
```

This way you can be sure the config always have the multivalued to true. But adding it in a static method will do nothing. Usually those static methods are just helpers (for tests, to create the mapper if needed in other parts,...) but not used in normal operation.

I'm going to close the issue. Please re-open or file a new issue if needed.

Thanks!
