### ISSUE TITLE
Keycloak New Store: /groups/count API fails when its fired for the first time resulting in an Internal Server Error

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#11808]
### Describe the bug

When we load the groups gui from the admin console, for the first time, the below end point fails with an Internal Server Error.

API : http://localhost:8081/auth/admin/realms/realm-0/groups/count?top=true

![groups_gui_failure_first_load](https://user-images.githubusercontent.com/3415105/166436386-cd134dd1-713c-4dd7-a536-8b7f2aaacd86.png)

In the server side logs, we can see the stack trace of a missing kc_group table related issue 

```
15:31:00,715 INFO  XNIO-1 task-4 [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
15:31:02,617 INFO  XNIO-1 task-4 [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] Initializing database schema. Using changelog META-INF/example-changelog.xml
15:32:18,342 ERROR XNIO-1 task-1 [org.keycloak.services.error.KeycloakErrorHandler] Uncaught server error
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
  at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
  at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1575)
  at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1614)
  at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:109)
.
.
.
.
15:31:00,715 INFO  XNIO-1 task-4 [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
15:31:02,617 INFO  XNIO-1 task-4 [org.keycloak.connections.jpa.updater.liquibase.LiquibaseJpaUpdaterProvider] Initializing database schema. Using changelog META-INF/example-changelog.xml
15:32:18,342 ERROR XNIO-1 task-1 [org.keycloak.services.error.KeycloakErrorHandler] Uncaught server error
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
  at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
  at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1575)
  at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1614)
  at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:109)

```

and an immediate log indicating the update around the dbchangelog to add the needed tables around the `group` entity.

```
15:32:18,561 INFO  XNIO-1 task-2 [org.keycloak.models.map.storage.jpa.liquibase.updater.MapJpaLiquibaseUpdaterProvider] Updating database. Using changelog META-INF/jpa-groups-changelog.xml

```

### Version

main branch - SHA - 0efa4afd493de0cb62501301f8a6828e95ea4982

### Expected behavior

the gui load should not result in the failure of the listing the group api endpoint and the lazy loading of the liquibase update to create the necessary db tables should happen in an seamless even for the first time load.

### Actual behavior

causes bad UX and potential cause for confusing on the client side because of an unwarranted internal server to list the groups.

### How to Reproduce?

Bring up the new storage using the instructions from this page : https://github.com/keycloak/keycloak/discussions/9596

Choose the postgres sql option to bring up the undertow server.

Now create a new realm, and proceed to click the Groups sub-navigation menu and observe for a failure in the endpoint using your network proxy tool or dev tools option in your fav. browser.

### Anything else?

full error log trace :
[internal_server_error_groups_GUI_first_time_access.log](https://github.com/keycloak/keycloak/files/8610064/internal_server_error_groups_GUI_first_time_access.log)

**Comment by ahus1** [comment]
This might be related to what we're experienced in #11328

**Comment by ahus1** [comment]
I haven't see this happening on the new store for quite a while, therefore closing it. The related PR probably fixed it.
