### ISSUE TITLE
Update MS SQL DB Driver Version in non-Docker Keycloak

### ISSUE THREAD

**Issue by mattgagliardi** [keycloak/keycloak#11813]
### Description

It appears (I may be wrong) that the non-Docker version of Keycloak 18.0.0 is utilizing the 7.2.2 version of the MS SQL driver. This is fairly outdated and does not support SQL 2019 per this ([link](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver15)) page.

Suggest/desire the JDBC version be updated to the latest (10.2.x) as already done for the Docker version of Keycloak.  See link here ([link](https://github.com/keycloak/keycloak-containers/issues/374)).

### Motivation

The existing driver supports multiple version of SQL that are EOL or nearly EOL but is missing a "current" version of SQL (2019).  It'd be great to see alignment between the "normal" and dockerized versions of Keycloak and support for this newer SQL version.

**Comment by pedroigor** [comment]
@mattgagliardi The driver is a transitive dependency from Quarkus. IIRC, this is also the version we certify.

**Comment by mattgagliardi** [comment]
Thanks for the reply, I’ll go look into the options in Quarkus. Is there something about the dockerized version of Keycloak that changes that transitive aspect?

**Comment by DGuhr** [comment]
FTR: https://github.com/quarkusio/quarkus/issues/24009 quarkus related issue.

**Comment by mattgagliardi** [comment]
Thank you for all the help and information Pedro and Dominik, I really appreciate it.  I'll keep an eye on the tickets mentioned.

**Comment by sschu** [comment]
I guess this is solved by now. Feel free to reopen @mattgagliardi if you disagree.
