### ISSUE TITLE
Invalid parameter: id_token_hint after upgrading keycloak version 16.1.0 to 18.0.0

### ISSUE THREAD

**Issue by emircankilinc-oviva** [keycloak/keycloak#11815]
### Describe the bug

Hi Team,
We are currently trying to upgrade our keycloak version to 18.0.0. But after upgrading this our logout mechanism is broken. And we're getting following error. `Invalid parameter: id_token_hint` . We've checked our js adapters and other things . They are all upgraded already and using same version as 18.0.0. So how can we fix this issue, could you help us about that? We were using adapter logout method with redirectUri. And according to your [ upgrading guide document ](https://www.keycloak.org/docs/latest/upgrading/index.html#:~:text=If%20you%20use%20the,of%20the%20JavaScript%20adapter.), it should work as it is. Looking forward to hear any suggestions about this.

Thanks.

### Version

18.0.0

**Comment by ddurham2** [comment]
@emircankilinc-oviva: Did you discover the issue?  I've got the same thing going in

**Comment by Greegles** [comment]
Any updates?

**Comment by ambuznego** [comment]
@emircankilinc-oviva did you find the culprit?

**Comment by Greegles** [comment]
The problem went away after I removed the attributes `createdAt` & `updatedAt` from the user in keycloak admin.

**Comment by Luccifer** [comment]
> The problem went away after I removed the attributes `createdAt` & `updatedAt` from the user in keycloak admin.

What have u done exactly? I am new here :)
