### ISSUE TITLE
Client fields( Logo URL, Policy URL and Terms of service URL ) have been removed from ApplicationsPage.tsx in AccountConsole

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#11825]
### Describe the bug

Client fields( Logo URL, Policy URL and Terms of service URL ) have been removed from ApplicationsPage.tsx in AccountConsole!

Although Logo URL, Policy URL and Terms of service URL have been configured  and 'Consent Required' is true, fields  Logo URL, Policy URL and Terms of service URL are not shown in ApplicationsPage.tsx in AccountConsole!

The bug ( removal) have been introduced in [Keycloak account console PatternFly design system alignment PR](https://github.com/keycloak/keycloak/pull/10748).

Policy URL and Terms of service URL (if existed) must be shown as before.  I propose Logo URL (if existed) to be shown in the right part of application.

### Version

18.0.0

### Expected behavior

![application_16 1 0](https://user-images.githubusercontent.com/55974447/166658555-58f04dd3-4c3c-4121-9abe-e99dc49f2b83.PNG)

As you can see from attached screenshot until at least Keycloak 16.1.0, client fields( Logo URL, Policy URL and Terms of service URL ) have been shown in ApplicationsPage.tsx in AccountConsole - if they have been set.

### Actual behavior

![application_18 0 0](https://user-images.githubusercontent.com/55974447/166658935-ed6b8290-3c2b-4e59-92f9-e5454df763dc.PNG)

As you can see from attached screenshot until at least Keycloak 16.1.0, client fields( Logo URL, Policy URL and Terms of service URL ) have been removed from ApplicationsPage.tsx in AccountConsole!

![client_configuration18 0 0](https://user-images.githubusercontent.com/55974447/166659026-6d147912-564c-4bd8-b259-10a97375ac17.PNG)
Logo URL, Policy URL and Terms of service URL have been configured to the client.

### How to Reproduce?

Admin must configure Logo URL, Policy URL and Terms of service URL in the client and make 'Consent Required' true.

After accepting consent for this Client, user goes to AppliactionsPage in AccountConsole and fields  Logo URL, Policy URL and Terms of service URL are not shown!

**Comment by ssilvert** [comment]
@tyandor I think this one is for you also.
