### ISSUE TITLE
problem with KC access to Internet via http/s proxy

### ISSUE THREAD

**Issue by phamlankt** [keycloak/keycloak#11834]
### Description

Hello,

I configured my client to use the back channel logout URL which is the Internet URL. There is proxy setup in our enviroment that requires all Internet access via proxy. How can I tell KC (v18) to use this proxy 192.168.1.10:8080 to be able to talk to the back channel logout URL?

A geneal env variable HTTP/s_PROXY setup does not help.

**Comment by pedroigor** [comment]
IIRC, you want the backend URLs using the same base URL from the frontend URL. For that, you can set `KC_HOSTNAME_STRICT_BACKCHANNEL=true`.

**Comment by phamlankt** [comment]
sorry if
