### ISSUE TITLE
Investigate referential integrity for compositeRoles field in LDAP when removing role

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#11836]
### Description

When some role is removed, we need to remove the reference to the removed role from all other roles that have it in `compositeRole` field. 

We need to make this removal efficient in LDAP. For other stores, we use the following for this:
1. Search for all roles that have id of removed role within `compositeRole` field. This is done using COMPOSITE_ROLE searchable field
2. Remove the reference from each role that was returned by the search

However, for LDAP we are not able to simply make such a search. Currently, we use a workaround where we [skip COMPOSITE_ROLE searchable field](https://github.com/keycloak/keycloak/pull/11816/files#diff-29338c9aa45a3ad4eedb5f6f4b98f6c0bf767cac2f5de7e90f44154b9920540eR145) obtain all roles and then filter them in Java, but this is not ideal.

We should investigate how to make the removal more efficient.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
