### ISSUE TITLE
Fix for NullPointerException in DefaultEmailSenderProvider.java

### ISSUE THREAD

**Issue by isaacjensen** [keycloak/keycloak#11839]
### Describe the bug
This exception is being thrown in `DefaultEmailSenderProvider.java`
The logger is defined after the call to getSupportedSslProtocols(). If getSupportedSslProtocols() throws an error, the catch block calls `logger.warn("Failed to get list of supported SSL protocols", e);` which hasent been defined yet. 

The method call and logger definition need to be flipped so that the logger is defined first. Lines 52 and 54 of DefaultEmailSenderProvider.java need to be swapped. 

### Version

18

### Expected behavior

getSupportedSslProtocols() logs the exception

### Actual behavior

NullPointerException is thrown on the logger.warn(..) and the actual exception cannot be seen. 

### How to Reproduce?

Disable security providers which DefaultEmailSenderProvider.java relies on so that getSupportedSslProtocols() errors out, and notice the NullPointer. This shouldnt be there.

**Comment by isaacjensen** [comment]
Should look like this:
    private static final Logger logger = Logger.getLogger(DefaultEmailSenderProvider.class);
    private static final String SUPPORTED_SSL_PROTOCOLS = getSupportedSslProtocols();

Logger needs to be defined before the call to getSupportedSslProtocols()

**Comment by pedroigor** [comment]
Fixed by https://github.com/keycloak/keycloak/issues/14886.
