### ISSUE TITLE
Servlet 5.0 support

### ISSUE THREAD

**Issue by profTwinglings** [keycloak/keycloak#11835]
### Description

I am using keycloak-saml-servlet-filter-adapter.

I would like to run the module with Tomcat 10, that uses Servlet 5.0 and Jakarta EE 9.

### Motivation

Java 17 will drop support for older javax.* namespaced libraries from Jakarta EE 8 and earlier.

### Details

The source code of keycloak dependes on 
jboss-servlet-api_3.0_spec or jboss-servlet-api_4.0_spec which is incompatible with Tomcat.

**Comment by vmuzikar** [comment]
Thanks for the report. With the upcoming Keycloak 22, we've [migrated](https://github.com/keycloak/keycloak/blob/c75bf313981c30c08de0787ae6473a1d58989b4c/docs/documentation/release_notes/topics/22_0_0.adoc?plain=1#L1-L7) to Jakarta EE and Servlet 6. Hence closing this as obsolete.
