### ISSUE TITLE
Way to store and query composite roles

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#11844]
https://github.com/keycloak/keycloak/pull/11816#discussion_r865762577

There has been added new searchable field `COMPOSITE_ROLE` within https://github.com/keycloak/keycloak/pull/11816 

Composite roles should be probably extracted into separate table and index should be added to support the search.

We might want to consider the fact that composite roles number grows significantly with more realms and clients. There could also be transitive relations and parent has as effective roles all its composite roles and also composite roles of the 1st level composites etc.

to explore 
- recursive queries: https://www.postgresql.org/docs/current/queries-with.html
- https://en.wikipedia.org/wiki/Nested_set_model

**Comment by ahus1** [comment]
As discussed in the storage team, the first step should be to extract this as a new table. 

As there could be many composite roles within a role, this should avoid a one-to-many relation as such a relation would load all entries. Instead, a PR should try to model it only with many-to-one relations. 

This is related to the efforts in #11799
