### ISSUE TITLE
Operator - Job needs imagePullSecret support

### ISSUE THREAD

**Issue by jbpin** [keycloak/keycloak#11847]
### Describe the bug

I was able to create the Keycloak deployment instance with imagePullSecret using unsupported podTemplate.
Unfortunately, when the operator create a realm import job it doesn't take the unsupported podTemplate and the image cannot be pulled. 

### Version

18.0.0

### Expected behavior

Use the unsupported podTemplate or provide a way to specify the imagePullSecret to use. 

### Anything else?

I will try to add the imagePullSecret to the serviceaccount as a workaround in waiting for a solution.

**Comment by andreaTP** [comment]
Hi @jbpin , thanks for trying out the operator in preview!

This is indeed a bug as we are taking the `container` from the `Deplyment` but not respecting the rest of the `podTemplate` fields.

One possible workaround is to make sure that the `imagePullPolicy` of the keycloak image is `IfNotPresent` and not `Always`, [here](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) you can find more information about the defaults of this setting.

cc. @vmuzikar

**Comment by andreaTP** [comment]
@jbpin can I ask you to detail your workaround for future users and as a reference? ( I assume you modified/patched [this resource](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L2-L10)).

I agree that this is a bug that should be fixed.

**Comment by jbpin** [comment]
> @jbpin can I ask you to detail your workaround for future users and as a reference? ( I assume you modified/patched [this resource](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L2-L10)).
> 
> I agree that this is a bug that should be fixed.

Actually the job is using the default serviceAccount. So I simply patch the default SA with imagePullSecret on the namespace of the keycloak operator. (I personally have a namespace separated for keycloak)
