### ISSUE TITLE
`getCount` method is ineficient in Hot Rod store transaction

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#11857]
### Describe the bug

This method: https://github.com/keycloak/keycloak/blob/1162952432b61b9f4fce828f518669f771ce8122/model/map/src/main/java/org/keycloak/models/map/storage/chm/ConcurrentHashMapKeycloakTransaction.java#L210-L212

reads all entities from the store and then counts them. This must be rewritten into something that doesn't require collecting all entities into Java. At least for HotRod storage.

### Version

main

**Comment by hmlnarik** [comment]
Putting to Backlog to understand the performance impact of including / not-including it

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
