### ISSUE TITLE
Unable to update Keycloak authorization settings via API

### ISSUE THREAD

**Issue by neuromantik33** [keycloak/keycloak#11862]
### Describe the bug

I'm trying to configure keycloak clients via the ansible modules. We have a particular case where fined grained authorization is required, however the policies reference client roles. With that said, in our playbook we configure the client w/o authorization settings enabled, then we create the roles, and then we apply the fined grained authorization (using in order `community.general.keycloak_client`, `community.general.keycloak_role` and then again `community.general.keycloak_client`).

Well all client updates go through [ClientResource.update](https://github.com/keycloak/keycloak/blob/00ccc78360001e3451dea3e7472babd111d7f904/services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java#L755-L783) and the only thing being updated is the flag which ignores the client representation and just creates the default permissions and policy.

```java
private void updateAuthorizationSettings(ClientRepresentation rep) {
    if (Profile.isFeatureEnabled(Profile.Feature.AUTHORIZATION)) {
        if (TRUE.equals(rep.getAuthorizationServicesEnabled())) {
            authorization().enable(false);
        } else {
            authorization().disable();
        }
    }
}
```

### Version

17.0.0

### Expected behavior

The client representation should be updated as well.

### Actual behavior

The keycloak fined grained authorization resources/policies/views remain the default ones.

### How to Reproduce?

- Create the client via the REST API **without** authorization enabled.
- Create any client roles
- Update the client via the REST API with the appropriate authorization settings configured.

**Comment by pedroigor** [comment]
@neuromantik33 The endpoint to update authorization settings is a different one. When updating a client you can only enable/disable authorization service, as per the code snippet you mentioned.

To update authorization services for a given client, you need to send a `PUT` request to this endpoint:

```
curl 'http://localhost:8080/admin/realms/myrealm/clients/${client_id}/authz/resource-server/import' -X POST \ 
    -H 'Content-Type: application/json;charset=utf-8' \ 
    -H 'Authorization: Bearer ${access_token}' \
    --data-raw '<JSON>'
```

I know we lack a better documentation but we are still working in providing a better API documentation. For now, I also suggest you to look at the request trace from your browser when updating a client using the administration console.
