### ISSUE TITLE
Linked account - paged listing of IdPs

### ISSUE THREAD

**Issue by laskasn** [keycloak/keycloak#11867]
### Description

``**Motivation:**

On keycloak’s account management console, if a realm has a lot of identity providers, the user is presented with a huge list which he has to scroll in order to find the desired identity provider to link his account with, since there is no search/filtering in the UI. Moreover, a lot of information is fetched, making the webpage quite resource demanding in terms of memory and network bandwidth.

**Design proposal:**

We propose to perform minimal changes on the current design and add a paging and filtering on both {Linked Login Providers, Unlinked Login Providers} lists.
Our enhancement is done by making as few as possible changes on both the react and java sides. 

So, with the following minimal changes: 
- on the backend side (java), we enabled LinkedAccountRepresentation items to be fetched in pages in LinkedAccountsResource.java 
- on the frontend side (react/patternfly), we added a patternfly Pagination element to drive the requests of the pages from the backend and also added a filter, to filter out (server-side) the response 

 
The loading times are hugely improved:
We have ~4300 IdPs in our keycloak and we measured the loading times and the idp-related data fetching.

|  | Before | After |
| ------------- | ------------- | ------------- |
| Data needed to fetch from /auth/realms/master/account/linked-accounts  | 1,1 mb  | 3,5 kb  |
| Total time to load webpage  | 7,49 sec  | 0,834 sec  |

I also attach a screenshot to showcase the UI changes:
![LinkedAccounts](https://user-images.githubusercontent.com/11722418/167010939-4d41c2fc-459a-4c0e-94d2-353c1173fba5.png)

### Discussion

https://github.com/keycloak/keycloak/discussions/8609

### Details

You can find the pull request [here](https://github.com/keycloak/keycloak/pull/8022)

**Comment by pedroigor** [comment]
@laskasn We are resuming the work to improve the scalability of identity providers.

For this particular issue, could you elaborate more about your use case and why you have so many brokers in a realm? Is it related somehow to multi-tenancy?

**Comment by cgeorgilakis** [comment]
> @laskasn We are resuming the work to improve the scalability of identity providers.
> 
> For this particular issue, could you elaborate more about your use case and why you have so many brokers in a realm? Is it related somehow to multi-tenancy?

@pedroigor : @laskasn was a member of GRNET AAI team when he created the issue and related PR. See details in [my comment](https://github.com/keycloak/keycloak/issues/30084#issuecomment-2230539364).

**Comment by pedroigor** [comment]
Closing this one in favor of https://github.com/keycloak/keycloak/issues/21261.
