### ISSUE TITLE
Keycloak v18.0.0 fails to import realm when directories are present in data/import location

### ISSUE THREAD

**Issue by fbladilo** [keycloak/keycloak#11861]
### Describe the bug

Keycloak fails to startup when it finds a directory in the data/import location, we triggered this by mounting the realm json definition from a configmap in OpenShift/Kubernetes at data/import dir, kubernetes adds directories and symlinks in addition to the file contents and we are unable to use the kc.sh start-up realm import (--import-realm) feature because of this. 

### Version

18.0.0

### Expected behavior

Keycloak startup data import should actually ignore (perhaps report) but continue processing files in data/import , should never fail because there are symlinks or other directories present.

### Actual behavior

Keycloak/kc.sh fails to startup with --import-realm because it finds directories in the data/import location

### How to Reproduce?

Drop some sample realms to import in data/import , also create directories , try to startup with kc.sh start --import-realm , watch it fail.

**Comment by andreaTP** [comment]
Possibly related to #11700
cc. @pedroigor @DGuhr
