### ISSUE TITLE
Jakarta EE 9 support

### ISSUE THREAD

**Issue by Szugro2** [keycloak/keycloak#11895]
### Describe the bug

Its a bit weird since no one is writing about this, anyone else having troubles with Jakarta EE 9?

The keycloak-saml-servlet-filter-adapter does not work with Servlet 5.0 since the javax.servlet namespace is deprecated.

I would like to run the module with Jetty 11 or Tomcat 10, that uses Servlet 5.0 and Jakarta EE 9.

Java 17 will drop support for older javax.* namespaced libraries from Jakarta EE 8 and earlier.

The source code of keycloak dependes on
jboss-servlet-api_3.0_spec or jboss-servlet-api_4.0_spec which is incompatible with Tomcat.

### Version

18.0.0

**Comment by fred-hartman** [comment]
Is there an ETA on EE9 support?

**Comment by ahus1** [comment]
With the upcoming Keycloak 22 release, Keycloak will have some jakarta variants of some adapters. The nightly releases are already available, please give them a try: https://s01.oss.sonatype.org/content/repositories/snapshots/org/keycloak/

You'll find among others a keycloak-saml-jakarta-servlet-filter-adapter there.
