### ISSUE TITLE
Frontend url from wrong realm used in password update mails from admin panel

### ISSUE THREAD

**Issue by chris-crunchr** [keycloak/keycloak#11894]
### Describe the bug

After upgrading our keycloak version to `17.0.0`, we couldn't send out correct `Update Password` mails from the admin panel. The reset URL in the mail pointed to an internal domain instead of our client facing domain.

After a long debug session we found that the `frontendUrl` realm setting in our master realm was used instead of the the `frontendUrl` for the specific realm. We believe it doesn't necessarily picks the master realm URL, but rather the `frontendUrl` from the realm where the admin is logged in to. We hot-fixed the problem by unsetting the `frontendUrl` in the master realm, but we expected it to work as it did before.

### Version

17.0.0/18.0.0

### Expected behavior

When an admin user resets a password for a user in another realm, we expect the `frontendUrl` for that specific realm to be used in the password reset mail, so the user will land on the correct realm when resetting his/her password.

### Actual behavior

The master realm `frontendUrl` is used instead for the password reset mail, when resetting a password from the master realm.

### How to Reproduce?

* Setup a clean keycloak instance (we used the `quay.io/keycloak/keycloak:18.0.0` image in a docker-compose setup, with postgres as DB) 
* Configure the `frontendUrl` of the master realm to the actual URL of the master (i.e. the URL from the address bar) in realm settings
* Add a new realm
  * Configure some arbitrary URL for `frontendUrl` under realm settings (e.g. `https://some.random.domain`)
  * Configure realm mail settings to point to your development mail server
  * Create a new user with a usable email address
* Go to the `Credentials` tab under the user
  * At the bottom of the page, set `Reset Actions` to `Update Password (UPDATE_PASSWORD)`
  * Hit `Send email`
* Check  your mailbox, there should be a reset link pointing to the master realm `frontendUrl` instead of the new realm's `frontendUrl`

### Anything else?

The problem occurred for us in both keycloak 17.0.0 and 18.0.0 (the quarkus version of both versions), but we only tried to reproduce for version 18.0.0.

**Comment by pedroigor** [comment]
@chris-crunchr The key used to cache the frontendUrl (to avoid unnecessary processing when resolving realm frontendUrl) is not considering the case where an admin client is authenticating using the `master` realm so that the frontendUrl set to this realm is always used to resolve frontendUrls even though you are managing a specific realm.

Should be fixed by https://github.com/keycloak/keycloak/pull/12321.
