### ISSUE TITLE
Implementation of OAuth2 authentication with HTTP Basic authentication scheme not RFC6749 compliant

### ISSUE THREAD

**Issue by dev-jelinek** [keycloak/keycloak#11908]
### Describe the bug

When authenticating to the keycloak oauth2 server with ` grant_type: "client_credentials"` and the HTTP Basic authentication scheme as described in [RFC6749 section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) with url encoded special characters, keycloak rejects the authentication request with an 401 error response: `{
    "error": "unauthorized_client",
    "error_description": "Invalid client secret"
}`

### Version

16.1.1

### Expected behavior

Keycloak should decode provided credentials in a basic authentication header before validating their correctness as specified in RFC6749 standard.

### Actual behavior

Keycloak does not url decode the client credentials according to specification in basic authentication headers when authenticating an oauth2 client. Therefore requests of compliant clients with secrets containing special characters are not authenticated. 

### How to Reproduce?

When authenticating a client with `client_id = "user"` and `client_secret = "secret/with=special?character"`, a compliant authentication request with basic auth header would look like this:

`
POST /user-service/auth/realms/generic/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Authorization: Basic dXNlcjpzZWNyZXQlMkZ3aXRoJTNEc3BlY2lhbCUzRmNoYXJhY3Rlcg==
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Cache-Control: no-cache
Host: keycloak-test.testdomain.de
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
 
grant_type=client_credentials`

but gets denied with:
`
HTTP/1.1 401 Unauthorized
Cache-Control: no-store
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Referrer-Policy: no-referrer
Date: Mon, 09 May 2022 13:13:54 GMT
X-Content-Type-Options: nosniff
Content-Length: 75
Content-Type: application/json
Strict-Transport-Security: max-age=31536000;includeSubDomains
 
{"error":"unauthorized_client","error_description":"Invalid client secret"}`

### Anything else?

This issue has been brouht to our attantion through an update to the spring oauth2 client impementation: https://github.com/spring-projects/spring-security/issues/9610

**Comment by GauthierV** [comment]
I have the same issue. Why do we have to make complicated workaround? We sould be able to use password with special characters.

**Comment by frankjkelly** [comment]
Is this related to https://issues.redhat.com/browse/KEYCLOAK-18704 or is that similar but separate?

**Comment by mposolda** [comment]
Thanks for reporting this. I am adding label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to contribute the PR with fixing this.

And yes, it is same issue as KEYCLOAK-18704

**Comment by frankjkelly** [comment]
@mposolda it looks like @lexcao provided a PR - how can we get some 👀 on it?  Thanks!

**Comment by frankjkelly** [comment]
@mposolda @lexcao thanks for the fix and the attention - do you have any sense what release this will come out in? Thanks again. Looks like `19.0.0` any chance we can backport to a release that may come out sooner?

**Comment by frankjkelly** [comment]
Hmmm we just tried updating to Spring 2.7 and Keycloak `19.0.1` but still see this issue - any advice? Is this perhaps because "old" client secrets were not encoded and when we upgrade it fails? Do we need to re-created client secrets?

**Comment by lexcao** [comment]
Hi @frankjkelly 
I found https://github.com/spring-projects/spring-security/issues/9610 fixed at their end.
And I found this https://github.com/spring-projects/spring-security/issues/10665

> this change was intentionally introduced in 5.6, per https://github.com/spring-projects/spring-security/issues/9610 (and noted in [5.6.0-M1](https://github.com/spring-projects/spring-security/releases/tag/5.6.0-M1)), which aligns us with [RFC 6749, Section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1). We're aware that this spec unfortunately conflicts with [RFC 2617](https://datatracker.ietf.org/doc/html/rfc2617).

**Comment by sschu** [comment]
@lexcao Still using base64url encoding is not mentioned anywhere in those two specs.

**Comment by mposolda** [comment]
@sschu @lexcao @frankjkelly It seems that @sschu is right. Anyone is welcome to create follow-up issue and send follow-up PR for this. @frankjkelly If you can add the example of client secret, which fails for you (not the actual client secret you are using in the production, but just some example with the "bad" characters, which is causing the issues for you), it would be welcome.

**Comment by lexcao** [comment]
Hi @mposolda @sschu 
Thanks for your confirmation.
I am willing to follow up on this.
I will create the issue and PR later.

**Comment by frankjkelly** [comment]
@mposolda thanks for helping here's a sample from our dev env
Raw output
```
$ kubectl get secrets/keycloak-client-secret-signal  -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{$v}}{{"\n"}}{{end}}' 
CLIENT_ID: c2lnbmFs
CLIENT_SECRET: d0FqbTZtbkVYYngxaDVmclJWejlDX3FEak1FPQ==
```

Now with Base64 decode
```
$ kubectl get secrets/keycloak-client-secret-signal  -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
CLIENT_ID: signal
CLIENT_SECRET: wAjm6mnEXbx1h5frRVz9C_qDjME=
```

**Comment by mposolda** [comment]
@frankjkelly Thanks for the info
@lexcao Thanks for looking at this!

**Comment by frankjkelly** [comment]
@lexcao @mposolda Any update on 👆 . Thanks in advance.

**Comment by lexcao** [comment]
Hi, @frankjkelly @mposolda 
A PR filed.

**Comment by frankjkelly** [comment]
@lexcao Thanks so much - just so I understand when the K8S secret containing the client credentials is created by Keycloak - that's from the Keycloak server - is that correct? So it's not something where I can just update the Keycloak client I presume.
