### ISSUE TITLE
the param id_token_hint in OpenID Connect Logout

### ISSUE THREAD

**Issue by ahcamy2021** [keycloak/keycloak#11915]
### Describe the bug

In the release note of the migration to KC 17, you said that we could omit the confirmation of  the logout by the user if we pass in the logout request the param 'id_token_hint' with a valid id token, it's not the case, because, I noticed that the confirmation in my case is always displayed. I checked the [code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L233) and the logic said that if the client is configured with consent required we will display this confirmation screen.

### Version

18.0

### Expected behavior

We need to have some logic between the code and the documentation, and we need that you confirm if it's a bug and you will remove the chceck of the configuration of consent or it's a miss in documentation.

### Actual behavior

Even if we pass a a valid id token in the logout request, the screen confirmation of logout will be displayed.

### How to Reproduce?

Create a new client and activate 'consent required, config, instantiate a session from your service securized by KC, and try o call the logout endpoint with a valid id token.

### Anything else?

Documentation of behaviour: https://www.keycloak.org/2022/04/keycloak-1800-released section: OpenID Connect Logout
Code checking the config of consent: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L233

**Comment by mposolda** [comment]
@ahcamy2021 Thanks.

As you pointed, the confirmation is always displayed for clients with "Consent Required" . Will it work for you if we just update the documentation about this fact? Or is it required for you to have the ability to skip the confirmation even if your client has "Consent Required" ?

**Comment by aidachami-qc** [comment]
@mposolda Thanks for your reply.

As I saw the power of Keycloak is that he is very cusotmizable, so, I think it's best if you give the ability to config this confirmation instead of link it with an existing one that it's used for another aspect of the solution.

**Comment by mposolda** [comment]
@aidachami-qc True, however clients already have bunch of configuration options and we're trying to limit amount of config options unless necessary. I've created discussion with the alternative option of using parameter `client_id`, which was introduced in latest specification draft. Feel free to comment on that: https://github.com/keycloak/keycloak/discussions/12183

**Comment by mposolda** [comment]
Fixed by #12002 . In Keycloak 19 the behaviour will be that confirmation page is displayed just if `id_token_hint` is not provided. The "Consent Required" switch of the client won't be taken into consideration.

**Comment by aidachami-qc** [comment]
@mposolda 
Thank you for the follow-up and the fix 👍

**Comment by alwa** [comment]
Since `id_token_hint` is optional according to spec, and if the client instead passes "client_id" only, then the consent is needed for logout in KeyCloak 19. Should I open a new issue for that?
