### ISSUE TITLE
Unexpected error when authenticating with identity provider

### ISSUE THREAD

**Issue by bxc2739** [keycloak/keycloak#11917]
### Describe the bug

Getting error of ::
We're Sorry...
Unexpected error when authenticating with identity provider

When trying to login to Keycloak via the OIDC after integrating with PingIdentity
![pingerr](https://user-images.githubusercontent.com/101810221/167491036-261cdfc3-e837-4e54-bf05-a54c1e0711cb.png)
![2022-05-09 15_15_48-Log in to realmz — Firefox Nightly](https://user-images.githubusercontent.com/101810221/167491068-f77ca388-13f0-4fba-b049-7d660e49b650.png)
![2022-05-09 15_16_01-Log in to realmz — Firefox Nightly](https://user-images.githubusercontent.com/101810221/167491071-dbbb461a-90f7-417b-a748-5d2748d452eb.png)

### Version

7.5.2

**Comment by mposolda** [comment]
@bxc2739 Thanks for the report, but I am closing as this seems to be a setup/configuration issue rather than a bug in Keycloak. Please ask for help on Keycloak user forums about help for the integration with Ping Identity.
