### ISSUE TITLE
Admin console does not work with reverse proxy

### ISSUE THREAD

**Issue by JonasCir** [keycloak/keycloak#11922]
### Describe the bug

With a past Keycloak version (16.1.1), I was able to proxy everything Keycloak related (`/admin`, `/auth`) under the path `/keycloak` on my host. I currently struggle to achieve the same with 18.0.

### Version

18.0

### Expected behavior

I expect that `/admin` can be proxied under a path (e.g., `/keycloak`) on my host as before.

#### Attempt 1: Use `--hostname-path`

I start Keycloak with `kc.sh start proxy=edge --hostname-path=keycloak --http-enabled=true` and set the hostname via 
`ENV KC_HOSTNAME`. My reverse proxy config is `/keycloak -> http://local-keycloak:8080`. Navigating to `/keycloak` shows the landing page and e.g., resources are correctly loaded from `/keycloak/resources` as expected. However, the `href` emitted for the admin console link does not honer the provided `hostname-path` and points to `/admin` on my host. Navigating manually to `/keycloak/admin/master/console/` yields a broken page as the resources are now loaded from `/resources` on my host, what is quite strange as on the login page the `--hostname-path` was honored.

#### Attempt 2: Use `--http-relative-path`

I build Keycloak with `--http-relative-path=keycloak` and start Keycloak with `kc.sh start proxy=edge --http-enabled=true` and set the hostname via 
`ENV KC_HOSTNAME`. Reverse proxy setting is now `/keycloak http://local-keycloak:8080/keycloak`. Again, navigating to `/keycloak` shows the landing page and e.g., resources are correctly loaded from `/keycloak/resources` as expected. Clikcing on the admin console redirects me to `/keycloak/admin/master/console/`, but now the page is white and starts refreshing every couple of seconds.

### How to Reproduce?

Please refer to this [repo](https://github.com/JonasCir/keycloak-repro) I created to reproduce the problem.

### Anything else?

While searching around, a couple of people suggested to use `--hostname-admin` but this gives me an unknown option error.

I see two ways to work around this: 
1. I go with attempt 1. and proxy `/admin` etc on my host to the container , however, this would make using the `/keycloak` path in the first place kind of useless.
2. I move the keycloak to a dedicated subdomain e.g., `auth.example.org` and do not rely on proxied paths altogether, but this would require a couple of changes in production what I would really like to avoid.

**Comment by JonasCir** [comment]
But anyways: I really like the general new approach that you guys are taking here. Migrating stuff will of course take time but things look far more concise and stable now :)

**Comment by omasseau** [comment]
Well even when using https the admin console does not work correctly.

I now have this configuration:
- KC_HTTP_ENABLED=true
- KC_PROXY=passthrough
- KC_HOSTNAME=localhost
- KC_HOSTNAME_PORT=443
- KC_HOSTNAME_STRICT=false
- KC_HOSTNAME_STRICT_HTTPS=false
- KC_HTTP_RELATIVE_PATH=/auth

Navigating to https://localhost:443/auth now correctly shows the login page after clicking on "Administration console".
But after I sign in I get a blank page again, but with the black header shown : 

![image](https://user-images.githubusercontent.com/11772429/170966957-3bf922b0-558b-446b-8d9e-1f6c383d719f.png)

I see no error in the network tab of the browser.
But I can see this in the console tab. I don't know if it is related : 

![image](https://user-images.githubusercontent.com/11772429/170967253-2b6feb52-df4d-48fc-a926-a432a6615dd5.png)

**Comment by omasseau** [comment]
Problem resolved for me after removing the KC_HOSTNAME_PORT=443 variable from the config : 

    KC_HTTP_ENABLED=true
    KC_PROXY=passthrough
    KC_HOSTNAME=localhost
    KC_HOSTNAME_STRICT=false
    KC_HOSTNAME_STRICT_HTTPS=false
    KC_HTTP_RELATIVE_PATH=/auth

It now works both in http and https.

This is weird as when calling https://localhost/auth the port is by default 443, which clearly matches the value of KC_HOSTNAME_PORT. So I don't understand why setting explicitely KC_HOSTNAME_PORT=443 is a problem.

**Comment by kekru** [comment]
For me it was important to set the following variables **before** the `kc.sh build`

```
KC_HOSTNAME_PATH="/auth"
KC_HTTP_RELATIVE_PATH="/auth"
KC_PROXY="passthrough" 
```

So first set these environment variables, then run `kc.sh build`

**Comment by kekru** [comment]
I didn't see the radio buttons "All | Build options | Configuration" on https://www.keycloak.org/server/all-config at first.  
So it was quite difficult to know which configs should be used at build time and which should be used at run time.  

I think it would help, if every config has a column, which says, whether it is a config for build time or for run time :)

**Comment by tlann** [comment]
> We also had some improvements in this area that should be available in the next release:
> 
> * Possibility to set a hostname other than the one used to set `hostname` if you are exposing the administration console in a different URL
> * Fixes to the new administration console
> 
> What do you guys think we make more clear in docs?

Define what passthrough, edge, and others do in the documentation.

**Comment by pedroigor** [comment]
> I think it would help, if every config has a column, which says, whether it is a config for build time or for run time :)

The options with a "tool" in the last column are supposed to indicate they are a build option.

**Comment by pedroigor** [comment]
@tlann Isn't enough the information available from this guide https://www.keycloak.org/server/reverseproxy?

**Comment by tlann** [comment]
I wish it would explain what it expects and what it does compared to the others.

**Comment by JonasCir** [comment]
Hey thank you for all the feedback! I cannot follow up on the hints given here right now, but I try to do so next week :)

**Comment by pedroigor** [comment]
@tlann We can certainly improve docs and provide more info about the different proxy modes such as:

* Edge: Enables communication through HTTP between the proxy and Keycloak. This mode is suitable for deployments with a highly secure internal network where the reverse proxy keeps a secure connection (HTTP over TLS) with clients while communicating with Keycloak using HTTP. `When using this mode you should make sure your proxy is properly forwarding the `X-Forwarded-Proto` header with the protocol (e.g.: https) in use. Otherwise, the administration console might fail to load because URLs returned by the server are going to be generated based on the protocol used by the proxy to communicate with the backends (e.g.: http).`

However, let me understand the status of this issue first. @JonasCir Looking at your example, it seems your proxy is listening is using HTTP and the same goes between the proxy and backends (`edge`).

The approach you took using `http-relative-path` should work if you follow the instructions here https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/hostname.adoc#accessing-keycloak-in-production-mode-using-http. This guide should be updated in the next release.

The `http-relative-path` should be used when you want to change the context root (`/` to `/auth`|`/keycloak`) for both non-admin and admin URLs.

**Comment by tlann** [comment]
Thanks @pedroigor That is exactly what I'm looking for.  I realize some of that info was vaguely further up in the document.  Wasn't sure which header was necessary out of the ones listed.
On a lighter note,  I got Keycloak-x working behind Spring-Cloud Gateway with the addition of another path to make up for the bugfix you put in regarding the authUrl and AuthServerUrl

**Comment by pedroigor** [comment]
Thanks, @tlann. Created https://github.com/keycloak/keycloak/pull/12451.

**Comment by JonasCir** [comment]
@pedroigor Thanks for your comment and updating the docs!
I can confirm that adding `--hostname-strict-https=false` as start parameter works! :tada:

**Comment by JonasCir** [comment]
Although I can now work around this issue, I still feel that Attempt 1 as described above should work and `--hostname-path` should be applied consistently in the application.

**Comment by JonasCir** [comment]
Thank you so much @pedroigor, if there is anything else just ping me :+1:

**Comment by l3roken** [comment]
I got the admin protal working behind webpacks reverse proxy.  I found this documentation:

https://www.keycloak.org/server/reverseproxy

You have to forward lots of resources in order for the admin portal to serve.

Here is my KC ENV vars:

`      
    KC_LOG_LEVEL: DEBUG
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    KC_HOSTNAME_STRICT: false
    KC_HOSTNAME_PATH: /auth
    KC_HOSTNAME: localhost.ozarkvolleyball.org
    KC_HOSTNAME_ADMIN_URL: https://localhost.ozarkvolleyball.org/auth
    KC_PROXY_HEADERS: forwarded
    KC_HOSTNAME_DEBUG: true
    KC_HTTPS_CERTIFICATE_FILE: /tmp/cert.pem
    KC_HTTPS_CERTIFICATE_KEY_FILE: /tmp/cert.key
      `
      
      Here is my webpack 4 config:
      
      `
           proxy: {
        "/api": {
          target: "https://localhost.foo.com:8081",
          changeOrigin: true,
          pathRewrite: { "^/api": "/api" }, // Rewrite the path if necessary
          secure: false,
        },
        "/auth": {
          target: "https://localhost.foo.com:8443", // Your Keycloak server URL
          changeOrigin: false,
          pathRewrite: { "^/auth": "" }, // Rewrite the path if necessary
          secure: false,
        },
        "/auth/resources/": {
          target: "https://localhost.foo.com:8443", // URL of your Keycloak server
          changeOrigin: false,
          pathRewrite: { "^/auth/resources": "" }, // Rewrite the path to /resources on Keycloak server
          secure: false, // If you are using self-signed SSL certificates
        },
        "/auth/realms/": {
          target: "https://localhost.foo.com:8443", // URL of your Keycloak server
          changeOrigin: false,
          pathRewrite: { "^/auth/realms": "" }, // Rewrite the path to /resources on Keycloak server
          secure: false, // If you are using self-signed SSL certificates
        },
        "/auth/admin/": {
          target: "https://localhost.foo.com:8443", // URL of your Keycloak server
          changeOrigin: false,
          pathRewrite: { "^/auth/admin": "" }, // Rewrite the path to /resources on Keycloak server
          secure: false, // If you are using self-signed SSL certificates
        },
        "/auth/js/": {
          target: "https://localhost.foo.com:8443", // URL of your Keycloak server
          changeOrigin: false,
          pathRewrite: { "^/auth/js": "" }, // Rewrite the path to /resources on Keycloak server
          secure: false, // If you are using self-signed SSL certificates
        },
      },
      
      `
