### ISSUE TITLE
Browser Navigate Back button does not work after click "Sign in" button

### ISSUE THREAD

**Issue by viknesh-j** [keycloak/keycloak#11932]
### Describe the bug

Click the “Sign In“ button, the sign-in page shall be seen

then, click the “Navigate Back“ button, 

Expected: back to the landing page

Actual: still show Sign in page

Please note: if I click any other options, e. g. Personal Info, Signing In, .. I can go back to “Keycloak Account Management“ page after click “Navigate Back“ button 

![Screen Shot 2022-05-10 at 1 14 57 PM](https://user-images.githubusercontent.com/105246040/167717066-655ef39b-079d-43e9-9f37-0c4d3253f6b0.jpg)

### Version

16.1.1

**Comment by ssilvert** [comment]
Only fix if broken in V3.  Check back button behavior.

**Comment by ssilvert** [comment]
I'm going to go ahead and close this as we won't be fixing it in V2.  [This issue](https://github.com/keycloak/keycloak/issues/20817) should take care of it for V3.
