### ISSUE TITLE
Configuration documentation is incorrect (health and http-relative-path)

### ISSUE THREAD

**Issue by VMM-Mtech** [keycloak/keycloak#11939]
### Describe the bug

[Server / All Configuration](https://www.keycloak.org/server/all-config) states that KC_HTTP_RELATIVE_PATH and KC_HEALTH_ENABLED are build options. Same thing is indicated in [this container sample](https://www.keycloak.org/server/containers#_building_your_optimized_keycloak_docker_image).

If I use them as ENV variables for the runner (not build) image, they seem to work as expected.

This might relate to other build options as well, but these two are the ones I needed for my setup.

### Version

18.0.0

### Expected behavior

The server should response to for example /auth and /auth/health endpoints

### Actual behavior

The server responds with HTTP 404 Not Found

### How to Reproduce?

Dockerfile used to reproduce:

```
FROM quay.io/keycloak/keycloak:18.0.0 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_DB=dev-mem
# Build image
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:18.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
ENV KC_HOSTNAME=localhost
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

### Anything else?

This version seems to create working image:

```
FROM quay.io/keycloak/keycloak:18.0.0 as builder

ENV KC_DB=dev-mem
# Build image
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:18.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
ENV KC_HOSTNAME=localhost
ENV KC_HEALTH_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=/auth
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

**Comment by andreaTP** [comment]
Hi @VMM-Mtech , thanks for reaching out,
the `start-dev` command you are using is always re-running the build step, that's the reason why the properties are picked up only in the "runner" image.

Can you please confirm that you have the expected behavior if you use the `start` command instead?

**Comment by VMM-Mtech** [comment]
Thanks for a quick reply.

I'll try the `start` version once we get all the necessary migration steps done in our "real" environments where we have the certificates etc. in place. Hopefully during this week.

But you're saying that as long as we use the `start-dev` in our development environments, we don't need the build step at all?

**Comment by andreaTP** [comment]
Correct, if you use `start-dev` the build command is completely redundant.

**Comment by VMM-Mtech** [comment]
Hi,

I'm confirming that when running with "start" instead of "start-dev", the build options are effective and not needed in runner image.
