### ISSUE TITLE
user first name not refreshed in Keycloak V2 theme 

### ISSUE THREAD

**Issue by viknesh-j** [keycloak/keycloak#11931]
### Describe the bug

User's first name was updated and saved. But on the top-right corner, the new info is not updated. It still shows “test“
<img width="1318" alt="Screen Shot 2022-05-10 at 1 04 04 PM" src="https://user-images.githubusercontent.com/105246040/167713047-7b00cec7-12db-4a97-9270-39278a04c19c.png">

### Version

16.1.1

### Expected behavior

Profile info near sign out button to be updated

### Actual behavior

Profile info near sign out button is not updated

### How to Reproduce?

Edit user's first name and click save.

**Comment by ssilvert** [comment]
Only fix in V3.

**Comment by ssilvert** [comment]
@agagancarczyk Have you tried to reproduce this with V3?
