### ISSUE TITLE
Update French translations

### ISSUE THREAD

**Issue by FranckKe** [keycloak/keycloak#11949]
### Describe the bug

Logout and idp login pages are missing French translations

### Version

18.0.0

### Expected behavior

Logout and IDP login option text translated in Frrench

### Actual behavior

Logout and idp login pages completely or partially in English when selected locale is French

### How to Reproduce?

Add French locale to realm supported locales

For the login IDP text
- Add an IDP to the realm
- Go to the realm login page
- Select French locale
- Text "Or sign in with" below the login/password fields is in English

For the logout page
- Login to a administration realm
- Sign out
- The logout confirmation page is completely in English

### Anything else?

PR incoming

**Comment by Crow-EH** [comment]
Hi @FranckKe , I'll contribute our i18n too a link it to this issue. We didn't translate everything since we do not use every features, but that's still something

**Comment by ssilvert** [comment]
@Crow-EH and @FranckKe,

If you guys can review each other's PR's for correctness and also verify that there will be no conflicts I can merge both of them.
https://github.com/keycloak/keycloak/pull/11950
https://github.com/keycloak/keycloak/pull/12054

**Comment by ssilvert** [comment]
@FranckKe If you can review https://github.com/keycloak/keycloak/pull/12056 as well that would be very helpful.  I don't speak French.

**Comment by Crow-EH** [comment]
@ssilvert no issue with https://github.com/keycloak/keycloak/pull/11950

You can merge it, then I'll rebase mine to make sure there's no conflicts

**Comment by FranckKe** [comment]
#11950, #12054 and #12056 are ready to merge, @ssilvert should I create a separate issue for #11950 and #12054?

**Comment by ssilvert** [comment]
> #11950, #12054 and #12056 are ready to merge, @ssilvert should I create a separate issue for #11950 and #12054?

We can link them all to this one.

**Comment by ssilvert** [comment]
@Crow-EH I just merged https://github.com/keycloak/keycloak/pull/11950.  Now yours have conflicts.

**Comment by Crow-EH** [comment]
I'm on it

**Comment by Crow-EH** [comment]
@ssilvert  I just rebased my branch, it should be ok now
