### ISSUE TITLE
`kc.sh import`  does not have a `verbose` option

### ISSUE THREAD

**Issue by kdvalin** [keycloak/keycloak#11948]
### Describe the bug

When running kc.sh import, providing the verbose flag returns an "Unknown option" error and fails to continue to the import job.

### Version

v18.0

### Expected behavior

The verbose flag would provide detailed information, probably about what database is being used, connection information, etc. for debugging purposes

### Actual behavior

When running `kc.sh import` it responds with the following
```
sh-4.4$ ./kc.sh import
ERROR: Failed to run 'import' command.
ERROR: Must specify either --dir or --file options.
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

Actually passing the `--verbose` option to the script returns the following
```
sh-4.4$ ./kc.sh import --verbose
Unknown option: '--verbose'
Try 'kc.sh import --help' for more information on the available options.
```

This occurs even when trying to import something
```
sh-4.4$ kc.sh import --dir=/opt/keycloak/data/import/ --verbose
Unknown option: '--verbose'
Try 'kc.sh import --help' for more information on the available options.
```

### How to Reproduce?

Run `kc.sh import --dir=/opt/keycloak/data/import --verbose`

### Anything else?

Providing the verbose flag before the import command works, but does nothing. 
```
/opt/keycloak/bin/kc.sh --verbose import --dir=/opt/keycloak/data/import/
```

**Comment by pedroigor** [comment]
The verbose option should be a `kc.sh` level option.

**Comment by epicbugs** [comment]
In case somebody stumbles on this in future - one reason can be that social login providers (Facebook, Google) don't store username but when Keycloak imports then it expects username to existfor every federated identity ("federatedIdentities" --> "userName"). One solution is to process the export files with a small script/program and generate those where missing.
