### ISSUE TITLE
Set email of initial admin user through env variables

### ISSUE THREAD

**Issue by XiangRongLin** [keycloak/keycloak#11940]
### Description

Currently one can set the username and password of the initial admin user through environment variables, see https://www.keycloak.org/server/configuration#_setup_of_the_initial_admin_user

I would to also be able to set the email

### Discussion

Kind of related but not directly, because I'm not using the X version [Keycloak.X Boostrapping Admin Access](https://github.com/keycloak/keycloak/discussions/8549)

### Motivation

I'm currently developing a process to create temporary containerized environments which are using keycloak.  
In order to use the keycloak [execute-actions-email](https://www.keycloak.org/docs-api/12.0/rest-api/#_executeactionsemail) function, it requires that the admin user has it's email adress set. But currently I can only set the username and password
Meaning that I would have to do it afterwards through the UI or create a script and call the API

From the Web UI it also seems like the email (and first and last name) are mandatory values, so currently one can create an invalid state through this.

**Comment by the-night-wing** [comment]
still no solution?

**Comment by jonkoops** [comment]
The initial admin is intended to be used only to then create a proper administrative user with all the correct credentials. It doesn't make sense to have a feature that further enhances the initial administrative user, as it should serve it's purpose only for a very limited time, you are actively warned about this when singing in to the administrative console.

**Comment by daviddecentage** [comment]
> The initial admin is intended to be used only to then create a proper administrative user with all the correct credentials. It doesn't make sense to have a feature that further enhances the initial administrative user, as it should serve it's purpose only for a very limited time, you are actively warned about this when singing in to the administrative console.

This makes sense. However, we frequently redeploy our apps for testing purposes, and having the set that every time is still a big pain imo

**Comment by jonkoops** [comment]
In that case I would recommend doing some scripting to set up the new user using the API, it will also give you much more control over any other fields or settings you might want to set up.

**Comment by daviddecentage** [comment]
We set up proper users when initializing our backend. As far as I remember the promt to fill out the default Admin info still appears, but let me double check if that really is the case.
