### ISSUE TITLE
Unable to override realm session TTLs per client

### ISSUE THREAD

**Issue by konradwudkowski** [keycloak/keycloak#11959]
### Describe the bug

Keycloak offers different **realm** session ttl settings, e.g. `SSO Session Idle`, `SSO Session Max` etc. There are also corresponding **client** settings, e.g. `Client Session Idle` or `Client Session Max`. 

Reading the documentation it seems that I should be able to specify different values per client, e.g. I would like to limit max session length for a particular client but allow for a different longer session for other clients.

This doesn't seem to work and it seems that realm settings always win.

Am I misunderstanding these settings? My ultimate goal is to reduce max session length in the `security-admin-console` but for other clients it also doesn't work

### Version

16.1.1

### Expected behavior

setting Session Max to 3 min in realm, and 6 min for a client (e.g. `security-admin-console`) should result in:
- client being logged out after 6 min

setting Session Max to 6 min in realm and 3 min for a client should result in:
- client being logged out after 3 min

Alternatively if there are some specific rules, e.g. client can't reduce realm session values etc it should be documented but within the rules it should still be possible to override

### Actual behavior

setting Session TTL to 3 min in realm, and 6 min for a client (e.g. `security-admin-console`) results in:
- client being logged out after 3 min
- expire field in the token being set to 3 min (min of realm/client ttl)

setting Session TTL to 6 min in realm and 3 min for a client results in:
- client being logged out after 6 min
- expire field in the token being set to 3 min (min of realm/client ttl)
- client will attempt to refresh token and will succeed once

### How to Reproduce?

Set realm and client session TTLs and observe that client values don't override realm settings

**Comment by mposolda** [comment]
@konradwudkowski Thanks for reporting this. I am adding label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to contribute the PR with fixing this (after it is investigated and confirmed that this is valid issue).

**Comment by jhelsethbushel** [comment]
If you still want help with this issue, I have some code in a branch I have been working on that can fix this issue. I have not submitted a PR yet, and I am not sure if there should be some discussion here or in the discussion area before I submit my code.

**Comment by y-tabata** [comment]
`Client Session Idle` or `Client Session Max` in client settings are able to overwrite `Client Session Idle` or `Client Session Max` in realm settings only, not be able to overwrite `SSO Session Idle` or `SSO Session Max`.

The below ticket shows details.
https://issues.redhat.com/browse/KEYCLOAK-12406

**Comment by stianst** [comment]
I'm going to close this issue as it's not valid.

The SSO session is just that, single sign-on, and as such is shared across many clients, not a single client. Hence, a single client should not affect its lifespan.

The client session duration should not have an impact on the SSO realm session duration, but rather just be valid for the same or shorter lifespan as the SSO session.

> My ultimate goal is to reduce max session length in the security-admin-console but for other clients it also doesn't work

Having a shorter client session will require the client to go back to Keycloak to get new refresh tokens. However, it should not affect the SSO session duration (remember that is shared between many clients) as mentioned above. The use-cases you are trying to achieve is perfectly valid though, but it needs to be tackled in a slightly different way. Having shorter client session lifespan for security-admin-console will impact lifespan of refresh tokens, and how frequently the client needs to do a authz code request, combine that with a max_age policy on the client the user to re-authenticate after a certain time. This allows the SSO session to remain, while individual clients can control the frequency a user has to re-authenticate.
