### ISSUE TITLE
SAML identity provider Username Template Importer mapper containing : is not restored correctly on Keycloak import

### ISSUE THREAD

**Issue by vpmuli** [keycloak/keycloak#11955]
### Describe the bug

I have a SAML identity provider Username Template Importer mapper with a template value like `${ALIAS}.${ATTRIBUTE.urn:oid:1.2.3}`. I have exported my configuration and when the configuration is imported on Keycloak startup the template value is changed to `${ALIAS}.oid:1.2.3`.

### Version

18.0.0 , 21.0.2

### Expected behavior

The imported template value should match the exported value `${ALIAS}.${ATTRIBUTE.urn:oid:1.2.3}`.

### Actual behavior

Imported template value is `${ALIAS}.oid:1.2.3`.

### How to Reproduce?

Create a SAML identity provider Username Template Importer mapper with a template value like `${ALIAS}.${ATTRIBUTE.urn:oid:1.2.3}`. Export the configuration and then import it.

**Comment by vpmuli** [comment]
"When importing a realm, you are able to use placeholders to resolve values from environment variables for any realm configuration." Maybe related to this?

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by vpmuli** [comment]
Reproduced on 21.0.2.
