### ISSUE TITLE
Keycloak does not support POST method mentioned in latest OIDC RP-Initiated Logout specs draft

### ISSUE THREAD

**Issue by arthur25000** [keycloak/keycloak#11958]
### Describe the bug

OpenID Connect RP-Initiated Logout specifies that "OpenID Providers MUST support the use of the HTTP **GET and POST** methods defined in [RFC 7231](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RFC7231) [RFC7231] at the Logout Endpoint." : https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

But Keycloak only supports GET method for the official OIDC Logout enpoint specification. 

The POST method of the logout endpoint requires client authentication and a refresh token which is not compliant with the OIDC specification.

### Version

Keycloak 18.0.0

### Expected behavior

The Logout Endpoint complies with OIDC RP-Initiated Logout specification when using POST method

### Actual behavior

The Logout Endpoint doe not comply with OIDC RP-Initiated Logout specification when using POST method

### How to Reproduce?

1) Authenticate on Keycloak to get a valid ID Token
2) POST the following request : 
curl -X POST --location "http://127.0.0.1:8080/realms/master/protocol/openid-connect/logout" \
    -d "id_token_hint=<your_id_token>"

You get a response : 

HTTP/1.1 400 Bad Request
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json
content-length: 75

{
  "error": "invalid_client",
  "error_description": "Invalid client credentials"
}

**Comment by mabartos** [comment]
@mposolda Could you please take a look at it? Thanks

**Comment by mposolda** [comment]
@arthur25000 +1 that this worth to be fixed. Thanks for the reporting! I see that recently there is an update to the specification https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout (it is still a draft) and it is possible that POST method was not mentioned as supported in the previous draft. But anyway, we are going to support POST method.

I guess we should make sure to differentiate between the old behaviour for backwards compatibility ( current `LogoutEndpoint.logoutToken()` ) and at the same time support POST method. I guess we can check if parameter `refresh_token` was passed to differentiate between the legacy endpoint and the POST method LogoutEndpoint as per the specs (pseudocode):

````
String refreshToken = form.getFirst(OAuth2Constants.REFRESH_TOKEN);
if (refreshToken == null) {
     // consider this as an endpoint based on the OIDC specification. So just call the same endpoint as when
    // GET method is invoked and pass the FORM parameters as arguments to the method
     logout(form.getFirst(OIDCLoginProtocol.REDIRECT_URI_PARAM),
              form.getFirst(OIDCLoginProtocol.ID_TOKEN_HINT),
               ... other params here
            )
     else {
         // This is the legacy logout endpoint with refresh token provided as parameter. So just call "logoutToken"
         logoutToken();
     }
````
