### ISSUE TITLE
java.net.UnknownHostException in database connection when using IPv6 only hostname

### ISSUE THREAD

**Issue by acuteaura** [keycloak/keycloak#11979]
### Describe the bug

When using a hostname that has no `A` record, but `AAAA` records, Keycloak will fail to boot with `org.postgresql.util.PSQLException`, caused by `java.net.UnknownHostException`.

Workaround is to set `JAVA_OPTS` to exclude `-Djava.net.preferIPv4Stack=true`, see #10482

### Version

18.0.0

### How to Reproduce?

fly.io provides a PaaS experience with managed postgres where the internal network is entirely IPv6 based - very easy to reproduce there without needing to set up a proper IPv6 stack

**Comment by andreaTP** [comment]
Hi @acuteaura , thanks for rising this issue!

I tested ipv6 support in the Quarkus Distribution tests ( https://github.com/keycloak/keycloak/commit/bf53e21808609f1a452efa303465595ef434613e ) and it looks safe to remove the option.
Given the positive feedback from #10482 I am optimistic about removing this option.

One note to setting `preferIPv4Stack` I can find is in this PR by @stianst :
https://github.com/keycloak/keycloak/pull/5884/files#diff-a24c7f89a12564e75ee5c8ea09a90ff9c37ea8848c830e34f81976b04cf59531R544

But there are no details about the possible underlying issues with Infinispan.
I'm looking for more historical context cc. @stianst @pedroigor @hmlnarik @mposolda

**Comment by pedroigor** [comment]
@andreaTP Good point. It should be better to keep this setting as is and add/update guides to tell people how to enable ipv6 support.

Something similar to this https://docs.wildfly.org/26/Admin_Guide.html#ipv4-versus-ipv6.

As you pointed out, changing that now could potentially break people. So it should be solved by docs.

**Comment by andreaTP** [comment]
I do see a couple of options:
 - we remove `-Djava.net.preferIPv4Stack=true` marking it as a breaking change and we document the option (e.g. referring to https://access.redhat.com/documentation/en-us/red_hat_jboss_web_server/5.3/html/installation_guide/java_ipv4_ipv6_properties ) and how to restore the previous default (e.g. using `JAVA_OPTS_APPEND`)
 - we keep the current opinionated option toward `ipv4` and we need detailed instructions on patching Keycloak standard options for `ipv6` users
 
Improving documentation won't give users a good UX and I would try to avoid it if we don't have a technical justification for sticking with the IPv4 option.
More and more services are (finally) starting to use IPv6 and I would be happy to see the Keycloak project adapting accordingly to the trend removing a "limitation" if not justified.

**Comment by pedroigor** [comment]
For now, I would keep ipv4 and improve docs. The "trend" is there for quite a long time but it does not justify changing it now because it might impact a lot of deployments out there. We should have a lot of apps and envs assuming ipv4 addresses.

We should also take into account how it would work in dual-stack systems and probably run some tests for KC acting as both server and a client.

Before removing it, I would open a discussion about the plans and give a chance to people to react and prepare for the change.

**Comment by andreaTP** [comment]
Sounds like a reasonable approach for now.

**Comment by ThoreKr** [comment]
Another curious observation here is that in a dualstack scenario for the database host IPv4 is still preferred even when setting `-Djava.net.preferIPv4Stack=false`.

**Comment by pedroigor** [comment]
@ThoreKr Yeah, please see https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html.

**Comment by pedroigor** [comment]
Created https://github.com/keycloak/keycloak/pull/13577.
