### ISSUE TITLE
Tomcat 10?

### ISSUE THREAD

**Issue by nielss76** [keycloak/keycloak#11972]
### Describe the bug

Tomcat 10 uses servlet 5.0 and  keycloak-saml-servlet-filter-adapter does not support it. Are there any plans for making Tomcat 10 or Jetty 11 to work with  keycloak-saml-servlet-filter-adapter.?

### Version

18.0.0

**Comment by stianst** [comment]
As we are deprecating all Java OIDC adapters there are no plans to support Tomcat 10 or Jetty 11
