### ISSUE TITLE
Authorization services endpoints are unusable using a specific LDAP user federation configuration (readonly, unsynched and none imported users)

### ISSUE THREAD

**Issue by Sebastien-HCL** [keycloak/keycloak#11980]
### Describe the bug

When using an LDAP user federation configuration (readonly, unsynched and none imported users), multiple REST Authorization services endpoints return an Internal Server Error (500) after deleting a user (who owns some resources - User Managed Resources) directly from the LDAP Server.

Endpoints identified (probably more to discover):
- GET /auth/realms/testserver/authz/protection/resource_set?deep=true
- GET /auth/realms/testserver/authz/protection/permission/ticket?returnNames=true

### Version

17.0.0

### How to Reproduce?

Reported against version 9.0.2, and still present in version 17.0.0

Original defect: https://issues.redhat.com/browse/KEYCLOAK-13822 and related issue is https://issues.redhat.com/browse/KEYCLOAK-17904
 
Steps to Reproduce:

- Launch a Keycloak container (quay.io/keycloak/keycloak:17.0.0-legacy for example) and configure a client (confidential, standard and implicit flow enabled, service account enable, **authorization enabled**)
- Configure an external LDAP server and create 1 user (using ApacheDS for example)
- In the Keycloak admin console, configure a user federation provider for that LDAP server
     - **Import Users is turned off**
     - Edit mode is is read_only
     - Sync registration is off
- Create a **user managed** resource with the user created on the LDAP server
     - curl --location --request POST 'http://localhost:9080/auth/realms/testserver/authz/protection/resource_set'  --header 'Content-Type: application/json'  --header 'Authorization: Bearer TOKEN' --data-raw '{
                                                                                                                        "name":"1234",
                                                                                                                        "owner": "replace with the ldap user",
                                                                                                                        "ownerManagedAccess": "true"
}'
- **Directly on the LDAP server**, delete that user (At this point, Authorization services endpoints are still working)
- In the Keycloak admin console, update the LDAP provider config (for example just change the "priority")
- Save the changes
- At this point, multiple (probably more to discover) Authorization services endpoints are not working anymore and throw a runtime exception (see stack track below)
     - GET /auth/realms/testserver/authz/protection/resource_set?deep=true
     - GET /auth/realms/testserver/authz/protection/permission/ticket?returnNames=true
     - GET /auth/realms/testserver/authz/protection/permission/ticket?resourceId=ReplaceWithAResourceId&requester=ReplaceWithARequesterId&granted=true&returnNames=true&first=0&max=50
- Even the Keycloak admin console contains error (http://server/auth/admin/master/console/#/realms/REALM/clients/CLIENTID/authz/resource-server/resource) and is not able to display any resources (even for users still present in LDAP)

**Comment by Sebastien-HCL** [comment]
Adding stack trace found in the Keycloak container
[KeycloakStack-11980.txt](https://github.com/keycloak/keycloak/files/8688239/KeycloakStack-11980.txt)

**Comment by mposolda** [comment]
Set to Backlog for now as doesn't look critical for Keycloak 22. We can possibly triage this later...
