### ISSUE TITLE
Publish container images on Docker Hub

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#11986]
### Description

The images provided on https://hub.docker.com/r/jboss/keycloak/tags are out of date, and it is not unusual to [receive requests](https://github.com/keycloak/keycloak/discussions/11235) from the community about publishing those images on Docker Hub.

Considering that, it should be simple to automate with GHA. I believe it is doable to have it.

### Motivation

Provide more alternatives to our community

### Details

Considering that we don't have any control over https://hub.docker.com/r/jboss/keycloak, images can be published at https://hub.docker.com/r/keycloak/keycloak/tags

#### Follows up on
- https://github.com/keycloak/keycloak-containers/issues/399

**Comment by abstractj** [comment]
cc @keycloak/kc-maintainers @keycloak/kc-developers

**Comment by abstractj** [comment]
@pedroigor that's an eventual request from the Keycloak community, I also got the chance to speak with Stian about it several weeks ago. 
The maintenance cost would be low, if we automate with GHA. What you suggest is valid for sure, but that means imposing a single solution to the community, plus not having any other alternatives in case of outages.

**Comment by daniel-shuy** [comment]
The latest images (`18.0.1`, `18.0.2`, `19.0.0`, `19.0.1`) are not published to Docker Hub, seems like the GitHub Action is not working?
