### ISSUE TITLE
New Referrer-policy breaks cross-origin SP<->IdP (KC)

### ISSUE THREAD

**Issue by RaphC** [keycloak/keycloak#12008]
### Describe the bug

Sometimes some Service Providers (SAML) hosted on a specific domain implements CORS policy directive to prevent illegal cross-domain acess. When Keycloak is used as an Identity Provider (SAML) to secure access of these Service Providers with **POST-binding** profile it fails because of default Referrer-Policy set to 'no-referrer' from 11.0.1 Keycloak Version.

Here is a sample

User-Agent -> Service Provider A (a.com) : User wants to access Service Provider A
User-Agent <- Service Provider A (a.com)  : Service Provider returns an html resource with form containing SAMLRequest and the action pointing to the Identity Provider B (b.com)
User-Agent -> Identity Provider B (b.com) : User-Agent POSTs (when page is loaded) SAMLRequest form
User-Agent <- Identity Provider B (b.com) : ... After user authentication ... Identity Provider B returns an html with form containing SAMLResponse and the action pointing to the Service Provider A (a.com) + an http header 'Referrer-Policy' with no-referrer' policy set.
User-Agent -> User-Agent : As Identity Provider B tells to the User-Agent it doesn't want the Referer header (and moreover Origin) be valued (no-referrer policy definition), User-Agent remove http header Referer and set Origin http header to null before POSTing SAMLResponse form
User-Agent -> Service Provider A (a.com) : User agent POSTs (when page is loaded) SAMLResponse form. Origin is at this time null.
Service Provider A (a.com) -> Service Provider A (a.com) : The Service Provider A detects a cross-origin invocation (coming from b.com) and check Origin (which is null). null being not permitted, the Service Provider stops the request and returns to the User-Agent an 'invalid CORS request' error response.

### Version

11.0.1

### Expected behavior

Referrer-Policy shoud be computed considering the different use case : If the SP has a cross-origin (can be obtain through the ACS URL) we should override the default policy when returning saml-post-form resource to accept cross-origin invocation.  

### Actual behavior

Due to Referrer-Policy set to no-referrer, the User-Agent send html form without Referer header nor Origin (which is set to null).

### How to Reproduce?

Create a SP with a domain (a.com) and an IdP with a domain (b.com)
Implements CORS Policy on SP domain
Register SP on IdP
Triggers a 'login' flow.

### Anything else?
Default policy strict-origin-when-cross-origin should be more appropriate.

**Comment by naveenbharadwaj-nc** [comment]
Interested in this problem. I agree that Keycloak must set strict-origin-when-cross-origin as default instead of no-referrer. Our application depend on referer header for many actions. After redirect from Keycloak, this header is swallowed.

**Comment by anuragpathak21** [comment]
I am facing the same problem in Keycloak version 20.0.5

**Comment by mposolda** [comment]
duplicates #17288
I am closing as a duplicate. Please continue in the other issue for the further discussions/questions/suggestions around this.

**Comment by pedroigor** [comment]
@RaphC @anuragpathak21 Please, see https://github.com/keycloak/keycloak/pull/19917.
