### ISSUE TITLE
Add support for client_id parameter in OIDC RP-Initiated logout endpoint

### ISSUE THREAD

**Issue by ross211** [keycloak/keycloak#12002]
### Describe the bug

This is in relation to the changes introduced by https://github.com/keycloak/keycloak/pull/10887.

As of Keycloak 18 if you hit the logout URL (`/auth/realms/$realm/protocol/openid-connect/logout`) when you don't have a session you get a logout confirmation, prompting for confirmation when it's going to be a no-op seems unnecessary?

Secondly if you don't provide the `id_token_hint` parameter to the logout endpoint then it can't look at your token to determine the issuing client and seems to fallback to the 'account' client. This causes the user to be redirected to the Keycloak account UI (`/auth/realms/$realm/account`) instead of the URL of the appropriate client if they follow the prompts to log back in after logout.
 - The logout button on the confirmation page sends the user to /auth/realms/$realm/protocol/openid-connect/logout/logout-confirm?client_id=**account**&amp;tab_id=X.
 - This scenario could occur if you had 2 tabs open and logged out on the first tab, then switched to the second tab and logged out on that and followed the Keycloak prompts to log back in.

My questions:
1. Should the logout confirmation prompt be bypassed when there is no session?
2. Is there (or should there be) a way to hint which fallback client Keycloak should use if there is no session/`id_token_hint` to read?
   - The [RFC](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) lists `client_id` as an optional parameter for the logout endpoint (for example `/auth/realms/$realm/protocol/openid-connect/logout?client_id=$client`), if this is provided then Keycloak would have a hint for selecting the appropriate client when determining the URL to send the user to when `id_token_hint` isn't provided.
   - Before Keycloak 18 this didn't matter as you could provide the logout endpoint with `?redirect_uri=x` and Keycloak would redirect the user to the given URL as long as it was listed as a valid redirect URI under one of the clients. It didn't matter if there was a session or not, now you can only use `post_logout_redirect_uri` if there is a known session (`id_token_hint` is provided).
   - If `client_id` is added as an optional parameter on the logout endpoint then `post_logout_redirect_uri` can optionally also be set even if `id_token_hint` isn't provided, Keycloak will then be able to validate that `post_logout_redirect_uri` is an acceptable destination for the given client and prompt the user for logout confirmation. Right now if you use `post_logout_redirect_uri` you must provide `id_token_hint` which then automatically bypasses confirmation even if you don't need/want to bypass confirmation.

### Version

18.0.0

**Comment by mabartos** [comment]
@mposolda Could you please take a look at it? Thanks
