### ISSUE TITLE
Keycloak does not honour scope parameter in the refresh flow

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#12009]
### Description

Keycloak must take into account scope parameter - if it exists -  in the request flow.

The scope parameter MUST NOT include any scope not supported by client as in other oauth flows.
New access token scope will contain assigned default client scopes plus the section of scope parameter ( if exists), scope of refresh flow and assigned client scopes.

Moreover, according to [Section 6 in OAuth2 RFC](https://www.ietf.org/rfc/rfc6749.txt):
>If a new refresh token is issued, the refresh token scope MUST be
>identical to that of the refresh token included by the client in the
>request.

### Motivation

Although request flow is implemented in Keycloak, Keycloak does not take into account scope parameter.

According to [Section 6 in OAuth2 RFC](https://www.ietf.org/rfc/rfc6749.txt):

> scope
> OPTIONAL. The scope of the access request as described by
> Section 3.3. The requested scope MUST NOT include any scope
> not originally granted by the resource owner, and if omitted is
> treated as equal to the scope originally granted by the
> resource owner.

**Comment by cgeorgilakis** [comment]
Moreover, UserInfo must be restricted based on Access Token scopes. For example access token produced by refresh flow with scope parameter.
I have implemented it by filtering default Client scopes based on access token scope. If you have another idea , we could discuss it.

**Comment by jitbasemartin** [comment]
Hi ! Any news ?

**Comment by cgeorgilakis** [comment]
I would like to mention that based on documentation only access token scopes are filtering based on scope parameter. Refresh token scope - if must be returned - are not changed.

@jitbasemartin no one have rewiew the PR yet.
