### ISSUE TITLE
Introduce reindexCaches:all option

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#12014]
There are two options how to specify what caches should be re-indexed:

1. reindexAllCaches : true|false
2. reindexCaches: "Comma separated list of cache names that should be re-indexed"

The first option `reindexAllCaches` can be removed and replaced by `all` option used with `reindexCaches`.

**Comment by mhajas** [comment]
I fixed this here: https://github.com/keycloak/keycloak/pull/12015 let me know if we want to have it in separate PRs
