### ISSUE TITLE
Implementing WriterInterceptor breaks keycloak admin console

### ISSUE THREAD

**Issue by Sobakaa** [keycloak/keycloak#12019]
### Describe the bug

When trying to introduce OpenTracing into my quarkus keycloak installation i faced an issue which i believe is a bug - endpoints returning Stream close that stream earlier than it should, resulting in sql exceptions and a random amount of data being returned.
While debugging the issue i simplified the problem to an instance of `WriterInterceptor` simply existing somewhere in one of your providers to be breaking any vanilla keycloak endpoint returning an open stream, even ones explicitly wrapped in `ClosingStream`.

### Version

18.0.0

### Expected behavior

All 10 realms are shown when opening Admin Console, no errors in logs

### Actual behavior

Only 5 realms are shown in admin console, and the following error in log:

```
2022-05-16 18:20:42,372 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-7) SQL Error: 0, SQLState: null

2022-05-16 18:20:42,374 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-7) ResultSet is closed
```

### How to Reproduce?

1. Register a new simple filter:

```
@Provider
@Priority(Interceptor.Priority.PLATFORM_BEFORE)
public class QuarkusSmallRyeTracingStandaloneContainerResponseFilter implements WriterInterceptor {
    @Override
    public void aroundWriteTo(WriterInterceptorContext wic) throws IOException {
        System.out.println("Test");
        wic.proceed();
    }
}
```

2. Start keycloak
3. Create 10 realms
4. Open Admin UI

### Anything else?

I suspect that `org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter` is somehow messing with the flow, but unfortunately don't have a solution yet. Dropping that filter from `quarkus-smallrye-opentracing` implementation allows for both keycloak and tracing to work but it is not ideal, obviously.
If you were to close the stream with something like `collect(toList())` and then return `list.stream()` the issue goes away, as hibernate has nothing to do with that stream any more, which makes `org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter#close` doubly suspicious.

**Comment by shawkins** [comment]
Resolving as out of date. A WriterInterceptor is not a supported extension, open telemetry now has first class support, and there have been several refinements to session / Stream closure in the meantime.
