### ISSUE TITLE
Account console doesn't show the currently logged in user

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#12039]
### Describe the bug

When you access the profile info page in the account console, there was a name of the currently logged-in user in the toolbar. After recent changes in the account console, the username is missing. I'm not sure if it's intentional, but I'd say it'd be great to have it included there.

See those changes here[1].

[1] https://github.com/keycloak/keycloak/commit/caebe50d7e82aba9a55d9b09cb52066a88a218f8#diff-23aee035905f7829df075270dc6aa0b735b33d8221a040a9b1c67c8e19eab9efL67-R69

### Version

999

### Expected behavior

The toolbar in the account console contains a user name.

### Actual behavior

The user name is missing in the toolbar.

### How to Reproduce?

Access the personal info page.

**Comment by mabartos** [comment]
@tyandor Could you please take a look at it? Thanks

**Comment by ssilvert** [comment]
@tyandor I just downloaded the latest nightly, and I see the user name in the toolbar on the main page, but not after you click on "Personal info" or something else.

I think you are the only one who has touched account console in awhile.  Can you take a look?

**Comment by tyandor** [comment]
Yeah, I’ll take a look.

**Comment by tyandor** [comment]
@mabartos @ssilvert here's a PR to fix this: https://github.com/keycloak/keycloak/pull/12962
