### ISSUE TITLE
HELP! Jetty 11 does not work

### ISSUE THREAD

**Issue by anna89382** [keycloak/keycloak#12031]
### Describe the bug

Jetty 11 uses servlet 5.0 and the module keycloak-saml-servlet-filter-adapter does not support Servlet 5.0. We need it to make the jump to Java 17, but this is the only dependency without Jakarta EE 9 plans.

Do you, the developers have any plans for Jakarta EE 9 support?? I have not found any documentation or talks about this so far, is the interest of using Java 17 so low?

### Version

18.0.0

**Comment by abstractj** [comment]
@anna89382 please see the announcement here https://github.com/keycloak/keycloak/discussions/9817. We don't have any plans to provide support for Jetty, or enhancements.
