### ISSUE TITLE
Items in dropdown menu for sharing resources are not visible

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#12048]
### Describe the bug

When you try to select permissions for shared resources, the current dropdown list doesn't show all items and the user is not able to choose the required one. It's not even possible to scroll there. 

![shareResourcePermissionsBug](https://user-images.githubusercontent.com/38039883/168801647-ea4de2b2-70e5-46f3-9120-a2d7c9370359.png)

### Version

999

### Expected behavior

All items from the dropdown list should be visible.

### Actual behavior

Only a few last items are shown.

**Comment by ymbcxb** [comment]
The problem also occurs in release 19.0.2
