### ISSUE TITLE
[SAML Broker] BadPaddingException because Keycloak uses signing key pair for decryption

### ISSUE THREAD

**Issue by Iceforgedmvp** [keycloak/keycloak#12053]
### Describe the bug

When my SAML identity broker processes a SAML response (from an external identity provider), the process fails with a BadPaddingException (either with "Message is larger than modulus" or "Decryption error").

### Version

17.0.0 & master branch

### Expected behavior

The SAML identity broker should use the encryption key pair ("ENC") for decrypting the encrypted key and the assertion of the SAML response.

### Actual behavior

It turned out that Keycloak uses the signing key pair ("SIG") for decryption which leads to the BadPaddingException.

### How to Reproduce?

1. Set up a SAML identity broker in Keycloak
2. Use Keycloak's account application (/realms/{yourRealm}/account/) to send a SAML request
3. Authenticate at the external identity provider
4. When Keycloak shows "An internal server error has occurred": Search for the the error in the logs

### Anything else?

**Code locations:**
org.keycloak.broker.saml.SAMLEndpoint.Binding.handleLoginResponse(..) calls session.keys().getActiveRsaKey(realm) which returns the signing key which is in turn passed on to AssertionUtil.decryptAssertion(holder, responseType, keys.getPrivateKey());

**Suggested Change:**
In the method org.keycloak.broker.saml.SAMLEndpoint.Binding.handleLoginResponse(..):

```
KeyManager.ActiveRsaKey keys = session.keys().getActiveRsaKey(realm) 
//...should be replaced with:
KeyWrapper keys = session.keys().getActiveKey(realm, KeyUse.ENC, Algorithm.RS256);
```

**Comment by dpulrichth** [comment]
This problem has been around for a while: https://github.com/eosc-kc/keycloak/issues/110

There is a pull request that adresses this but it might take some time for it to get merged: https://github.com/keycloak/keycloak/pull/8330

**Comment by Iceforgedmvp** [comment]
Awesome, thanks for the pointer :)

**Comment by rmartinc** [comment]
PR #15985 was already merged last week and it should be fixed in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).
