### ISSUE TITLE
keycloak adding stale userId in the uuid field of the access token

### ISSUE THREAD

**Issue by reachtoamrita** [keycloak/keycloak#12052]
When application generates an access token on behalf of one user X, the access token contains the wrong userId in the uuid field of token and the token validation fails.

The userId of user X is 39c8da6d-5d53-4693-a14f-7f230814ce13 but the access token contains "userUUID": "273aabd6-8dd8-4e78-b8bf-7c9896df8b5c".

It looks like this is happening due to the keycloak cache.
https://www.keycloak.org/docs/11.0/server_admin/#_clear-cache

Have you seen this issue earlier?

### Version

11.0.2

### Expected behavior

The token should contain the correct userId.

### Actual behavior

The token validation is failing and the API call is failing due to this.

### How to Reproduce?

Not able to reproduce

**Comment by abstractj** [comment]
@reachtoamrita please upgrade to the latest version. We no longer support Keycloak 11.0.2.
