### ISSUE TITLE
Disable Identity Provider on export/import

### ISSUE THREAD

**Issue by simse07** [keycloak/keycloak#12063]
### Describe the bug

I noticed some issues while migrating realms from one environment (dev, qa, prod) to another, using the realm partial export/import from the admin console.
If there is an identity provider configured, the `bindCredential` will be stripped.
Unfortunately the identity provider is still enabled, so an user import or any login will cause an authentication failure.
This could lead to the issue, that the client will be blocked by the identity provider.

### Version

17.0.1

### Expected behavior

An identity provider is disabled after exporting or importing a realm via admin console.

### Actual behavior

An identity provider is enabled after exporting or importing a realm via admin console.

### How to Reproduce?

1. add an identity provider, e.g. ldap
2. configure it correctly with `bindCredential`
3. export the realm
4. import the realm
5. identity provider is enabled, but `bindCredential` is invalid

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
