### ISSUE TITLE
Leverage Infinispan lifespan for ExpirableEntities in HotRod storage

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12068]
### Description

Currently, we have the expiration field, that says when the entity expires. We use this field to filter entities that are expired so that they are not loaded into Keycloak. This can be avoided for HotRod store where we can leverage entity lifespan. This way we could completely disregard the expiration field from queries because we will be sure expired entities are not present in the store.

### Discussion

https://github.com/keycloak/keycloak/discussions/11166

**Comment by martin-kanis** [comment]
Parked here https://github.com/martin-kanis/keycloak/commit/01c79e7adc5e7f9d21a584450ca9b734d1983488 until #12494 is resolved. Still requires some minor adjustments.
