### ISSUE TITLE
Environment variable substitution does not work in realm configs

### ISSUE THREAD

**Issue by Robespierre19** [keycloak/keycloak#12069]
### Describe the bug

I`m using Quarkus distribution.

Following the guide [Using Environment Variables within the Realm Configuration Files](https://www.keycloak.org/server/importExport#_using_environment_variables_within_the_realm_configuration_files), I tried to set the realm name from `REALM_NAME` environment variable.

Dev-realm.json:
```
{
    "id": "Dev",
    "realm": "${REALM_NAME}",
    ...
}
```

Running either `kc.sh import --file ./realm/Dev-realm.json` or `kc.sh import --dir ./realm` produces the following error:
```
ERROR: Character '$' not allowed.
```

### Version

18.0.0

### Expected behavior

Realm import should finish without errors.

### Actual behavior

The following log message appeares:
```
2022-05-17 15:26:33,013 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2022-05-17 15:26:33,014 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Character '$' not allowed.
```

### How to Reproduce?

* Use Keycloak 18.0.0, Quarkus distribution
* Export a realm from a working instance
* Replace realm value in config json file to `${REALM_NAME}`
* Set REALM_NAME environment variable
* Import realm with `kc.sh import` into a clean Keycloak environment.

**Comment by pedroigor** [comment]
@Robespierre19 This is a documentation issue. The capability stated in the documentation is related to importing realms at start-up. 

Running `import` command should not work. We recently added this capability to make it easier to provision the server targeting importing realms at startup.

I'm going to update the docs.

**Comment by Robespierre19** [comment]
Thank you for the clarification!
