### ISSUE TITLE
'Next page' button in admin console must be disabled when entity.length = query max

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#12073]
### Describe the bug

 In admin console  when entity.length = query max, admin user can select 'Next page' button and Keycloak will redirect him to empty pager.
This bug exists in many pagers in admin console like clients, roles, events.

 In admin console  when entity.length = query max,  'Next page' button must be disabled.

### Version

18.0.0

### Expected behavior

 In admin console  when entity.length = query max,  'Next page' button must be disabled.

### Actual behavior

 In admin console when entity.length = query max, admin user can select 'Next page' button and Keycloak will redirect him to empty pager.

### How to Reproduce?

Fe introduce 20 clients and select 'Next page' button in clients pager.

![clietnPager1](https://user-images.githubusercontent.com/55974447/169025780-63d4801e-4b73-46a6-8fd9-d33d56d7fcea.png)
![clietnPager2](https://user-images.githubusercontent.com/55974447/169025785-d2f58288-b232-4d7a-be7c-fc2b6ef08cae.png)

**Comment by ssilvert** [comment]
Hi @cgeorgilakis.

Thanks for reporting this.  I see you closed your PR.  We won't be doing a lot of bug fixes to the old console unless it something major.  So I'm going to go ahead and close this issue.

I have verified that this works in the new admin console.
