### ISSUE TITLE
[Documentation] Upgrade guide incomplete for installations with H2 databases

### ISSUE THREAD

**Issue by Iceforgedmvp** [keycloak/keycloak#12079]
### Description

Section "Upgrading the Keycloak server", Step 4 states:
"Copy conf/, providers/ and themes/ from the previous installation to the new installation."
Source: https://www.keycloak.org/docs/latest/upgrading/index.html#_install_new_version

This is not enough when you use an H2 database as the database file lies beneath `data/h2/keycloakdb.mv.db`.

### Motivation

 It took me hours to figure out the problem.

### Details

The documentation should mention what to do when a H2 database is in use or at least point out the H2 database case.

**Comment by hmlnarik** [comment]
H2 is a development database not supported for production use, thus there is no support planned in the documentation either.
