### ISSUE TITLE
Refactor the Distribution configuration to be shared across modules

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#12088]
### Description

Refactor the Configuration of the Quarkus distribution to be shared across other modules.
More specifically it will:
  - create the CLI options
  - create the docs
  - generate the `serverConfiguration` of the Keycloak CRD
 

### Discussion

11848

### Issues

- [ ] #10866 Create the maven structure and integrate it
- [x] #12084
- [ ] ~~#12085~~
- [ ] ~~#12086~~
- [ ] ~~#12087~~
- [ ] #12767

### Motivation

We want to have a single source of truth when talking about the configuration of the distribution (Quarkus)

**Comment by andreaTP** [comment]
We are deciding that the API for Kubernetes is very likely going to have different needs and evolve independently from the CLI options.

Here we decide to drop those changes and revert back some of the separations of the modules to increase the developer's productivity.

**Comment by vmuzikar** [comment]
Superseded by #13456.
