### ISSUE TITLE
Map storage: pagination enhancements

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12095]
### Description

See https://issues.redhat.com/browse/KEYCLOAK-18803 for more details.

There are a few enhancements that could be done for pagination in MapStorage:

# Set default [limit](https://github.com/keycloak/keycloak/pull/8227/files#diff-85233971501238bc4ef1954e3e3e1b184cb1fd96e73bbb81b7b3b920e01c1d7cR20) in QueryParameters to 100?
This change requires careful investigation across all Map*Providers.
- We need to consider [the usage of the pagination](https://github.com/keycloak/keycloak/pull/8227/files#diff-0682b783abef89c6c6b2966e3c3780870c38a635e61ff736a9cdbaad6fa96ef1R105) for BulkDelete operation, we will probably need to remove it as we usually want to remove all entities not only 100
- We need to replace reading entities and then removing one by one with bulk deletes. [An example and a discussion](https://github.com/keycloak/keycloak/pull/8227#discussion_r668247240).

# Add pagination to queries with .findFirst() stream terminal operation
[An example](https://github.com/keycloak/keycloak/blob/main/model/map/src/main/java/org/keycloak/models/map/client/MapClientProvider.java#L249).

# Using of Long type instead of Integer for offset parameter
This may be necessary in case of a huge deployment with billions of objects in the storage. I tried to change it but I ended up with an error in the legacy storage. This probably needs a little bit more refactoring than it looks like.

**Comment by mhajas** [comment]
@hmlnarik Could you please triage? I am not sure whether we still want these and if yes what priority it has.

**Comment by martin-kanis** [comment]
Revert https://github.com/keycloak/keycloak/issues/12993 once this issue is done.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
