### ISSUE TITLE
HotRod user session store doesn't remove client sessions on user session removal

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12096]
### Describe the bug

When a user session is removed we want to have all client sessions for this user removed. This is done using [UserSessionConcurrentHashMapStorage](https://github.com/keycloak/keycloak/blob/main/model/map/src/main/java/org/keycloak/models/map/storage/chm/UserSessionConcurrentHashMapStorage.java)  for CHM, however, we don't have anything like this for HotRod storage.

NOTE: this could be solved by invalidate method, however, this is probably not suitable because we want to allow each storage to implement this cascade removal on its own.  

### Version

18.0.0

### Expected behavior

Client sessions are removed on user session removal

### Actual behavior

Client sessions are not removed

### How to Reproduce?

1. create a user session
2. create a client session for ^
3. remove user session
4. client session should be removed but it is not for HotRod storage

**Comment by mhajas** [comment]
@vramik This would work and it would simplify things quite a lot, however, I see two problems with that.
1. Stores will not be able to provide their own solution for this and using invalidate may be inefficient. On the other hand, the main reason for doing it this way was having the possibility to leverage JPA cascade removal and If we are not able to do this it may be ok to just use invalidate.
2. Using invalidate method may be a little bit complicated since we also have bulk removals. So we would need to either read all by MCB and then call invalidate on each one or we would need to somehow add a possibility to include MCB in the invalidation message. 

WDYT @hmlnarik?

**Comment by vramik** [comment]
Looking at the code... we might be able to leverage `MaUserSessionProvider` user session removal methods.

* `removeUserSession(RealmModel, UserSessionModel)`
```
DefaultModelCriteria<AuthenticatedClientSessionModel> clientMcb = criteria(); 
clientMcb.compare(AuthenticatedClientSessionModel.SearchableFields.REALM_ID, Operator.EQ, realm.getId())
         .compare(AuthenticatedClientSessionModel.SearchableFields.USER_SESSION_ID, Operator.EQ, session.getId());

clientSessionTx.delete(withCriteria(clientMcb));
```

* `removeUserSessions(RealmModel)`
```
DefaultModelCriteria<AuthenticatedClientSessionModel> clientMcb = criteria(); 
clientMcb.compare(AuthenticatedClientSessionModel.SearchableFields.REALM_ID, Operator.EQ, realm.getId());

clientSessionTx.delete(withCriteria(clientMcb));
```

BUT, when removing UserSessions by user (`removeUserSessions(RealmModel, UserModel)`) we have no information about user within client session so this approach cannot be used here
