### ISSUE TITLE
Assign roles to <userName> account filter is not working

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#12093]
### Describe the bug

When you want to assign a Role on an User, and use the Filter, it seems to not work as expected.

### Version

18.0.0

### Expected behavior

The filter in the Role assignment for User to work as expected.

### Actual behavior

When you click on the Role assignment for an user, and you try to filter them (for example for all account client roles), the filter is not working at all (the query itself is working)

### How to Reproduce?

1. Go to **Users**
2. Open an user
3. Go to the **Role mapping** tab
4. Click on **Assign role**
5. Click on **Filter by Origin**
6. Select **account** for example

![AssignRoleOnUser](https://user-images.githubusercontent.com/33352511/169219616-e1513337-9f5a-4fe6-b9b6-ecb55043ac95.gif)

**Comment by ssilvert** [comment]
Thanks for the feedback, @mpalavrov.

This one is already fixed in the latest build.

**Comment by mpalavrov** [comment]
Thanks @ssilvert.
