### ISSUE TITLE
Remove update* methods for nested entities in map storages

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12097]
### Description

Migrated from: https://issues.redhat.com/browse/KEYCLOAK-17626

Currently, for nested entities like [these](https://github.com/keycloak/keycloak/blob/cb433cd2ea9b3563443e58812b20900534c393e8/model/map/src/main/java/org/keycloak/models/map/user/AbstractUserEntity.java#L58-L61) we are using following process for updating:
1. Obtain from storage
2. Change model
3. Call update method on corresponding adapter/provider

Using the updated flag introduced with the map storage, it is possible to get rid of the last step. This approach has many advantages including removal of update* methods or updating storage only in case an entity was meaningfully updated.

**Comment by mhajas** [comment]
Current state:
This issue is not relevant for Map physical layer (entities don't need to call update, they use `updated` flag and are updated only with meaningful changes). However, this can be improved in logical layer and usage of nested entities. 


For example, this method:

https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/model/map/src/main/java/org/keycloak/models/map/user/MapUserProvider.java#L182-L192

can be removed from the provider and replaced by doing changes in the corresponding entity. This would require following changes:
- Remove method from the provider (for example `ComponentModel` have [the method](https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/server-spi/src/main/java/org/keycloak/models/RealmModel.java#L529) in the RealmModel so we should be consistent )
- Change adapter implementation to keep the reference to the entity and update the entity with each setter call
- Change all usages of this method to adapt to the new approach for updating `FederatedIdentityModel`
- Repeat for all nested entities that are updated similarly (for example, `UserConsentModel`, `ComponentModel`, etc.)

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
