### ISSUE TITLE
Update trivy actions

### ISSUE THREAD

**Issue by eabykov** [keycloak/keycloak#12101]
### Description

- Update base image of Ubuntu `ubuntu-18.04` to `ubuntu-20.04`
- Use master tag for trivy scan `aquasecurity/trivy-action@4b9b6fb4ef28b31450391a93ade098bb00de584e` to `aquasecurity/trivy-action@master`
- Use upload-sarif v2 `github/codeql-action/upload-sarif@v2.1.10` to `github/codeql-action/upload-sarif@v2`

### Details

[.github/workflows/trivy-analysis.yml](https://github.com/keycloak/keycloak/blob/main/.github/workflows/trivy-analysis.yml)

**Comment by abstractj** [comment]
> * Update base image of Ubuntu `ubuntu-18.04` to `ubuntu-20.04`

@eabykov could you please elaborate more about the motivation on upgrading this?

> * Use master tag for trivy scan `aquasecurity/trivy-action@4b9b6fb4ef28b31450391a93ade098bb00de584e` to `aquasecurity/trivy-action@master`

Pinning to the SHA commit from 3rd party actions is a security best practice. Please check https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

> * Use upload-sarif v2 `github/codeql-action/upload-sarif@v2.1.10` to `github/codeql-action/upload-sarif@v2`

We are already using `upload-sarif@v2.1.10`. Could you please elaborate more on why switch to v2?

All the updates for GH actions were automated with [dependabot](https://github.com/keycloak/keycloak/blob/main/.github/dependabot.yml), and we have been constantly upgrading those actions. If there's a strong motivation for this enhancement, I'd appreciate your time elaboring more on this.
