### ISSUE TITLE
demo-template no longer available

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#12104]
### Describe the bug

The demo-template which very useful example (customer-portal, product-portal and database service) has disappeared since keycloak 9.0.3

The example is at URL
https://github.com/keycloak/keycloak/tree/9.0.3/examples/demo-template

This example was very useful, as it illustrates a concrete usage of

- client Id/client secret (customer-portal)
- client Id with signed jwt (product-portal)
- bearer mode (database service)

it would great if this example coudl be added back to teh keycloak distribution.

### Version

18

### Expected behavior

NA

### Actual behavior

NA

### How to Reproduce?

NA

### Anything else?

NA

**Comment by abstractj** [comment]
@orivat thanks for reporting this, but we don't have any plans of adding it back to the repository. If you would like to check out some of our examples, please take a look at the [quickstarts](https://github.com/keycloak/keycloak-quickstarts).
