### ISSUE TITLE
AAD IDP mapper of type "attribute importer" not importing claims

### ISSUE THREAD

**Issue by FZilli** [keycloak/keycloak#12129]
### Describe the bug

Good morning,
I've configured the identity brokering for AAD using openid connect v1 and I'm able to correctly login with linked user accounts.

When creating an IDP mapper of type "attribute mapping" I'm unable to import AAD claims and map them to linked accounts attributes.
As an example:
![image](https://user-images.githubusercontent.com/50174433/169565699-ea63caba-9d12-41fd-a481-6cef066ff40f.png)

I've tried also enabling in the logger section the profile dump to check whether the correct claims is being referenced
`
<logger category="org.keycloak.social.user_profile_dump">
  <level name="DEBUG"/>
</logger>
`

### Version

12.0.4

### Expected behavior

Linked user receives the attribute based on AAD claims

### Actual behavior

No attribute is available

### How to Reproduce?

Configure AAD as IDP and configure a mapper of type IDP referencing any incoming claim

**Comment by vmuzikar** [comment]
@FZilli Thank you for reporting this! I noticed you are using quite old Keycloak version (12.y). I'm going to close this for now. Feel free to reopen if you are able to reproduce it with the latest version (18.0.0).
