### ISSUE TITLE
Problem while using KeycloakRealmImport resource with custom image and Docker registry which requires authorization

### ISSUE THREAD

**Issue by tramiaczek** [keycloak/keycloak#12124]
### Describe the bug

I have a Keycloak deployment (kind: Keycloak) which uses custom image which is pushed in Docker registry which requires authorization. As the CRD does not support imagePullSecret directly I had to use "unsupported" section. Unfortunatelly there is no such option for KeycloakRealmImport and when I specify previously deployed Keycloak in keycloakCRName field realm import job is trying to pull custom image from registry, but no imagePullSecret is used, so the authorization fails.

### Version

18.0

### Expected behavior

Possibility to import realm using: KeycloakRealmImport for deployment created from custom image deployed in Docker registry that requires authorization. Simply speaking: possibility to use imagePullSecret not in Keycloak and KeycloakRealmImport CRD's.

### Actual behavior

Impossible to import realm when custom image from authorized Docker registry is used.

### How to Reproduce?

Try to import realm to Keycloak deployed from custom image deployed in Docker registry with authorized access.

**Comment by vmuzikar** [comment]
@tramiaczek Thank you for reporting this! It is already fixed in https://github.com/keycloak/keycloak/pull/11864.

**Comment by vmuzikar** [comment]
Please see also https://github.com/keycloak/keycloak/discussions/11999
