### ISSUE TITLE
kc.sh fails on cygwin

### ISSUE THREAD

**Issue by elkman** [keycloak/keycloak#12130]
### Describe the bug

Hello,

since there is explicit support for cygwin in kc.sh, it would be nice if it also works.

If this issue is accepted, I can also provide a PR to fix the two issues described below (and replace the backticks):

https://github.com/keycloak/keycloak/compare/main...elkman:feature/fix_kc.sh_cygwin

Perhaps someone could test the change for Darwin and FreeBSD, to which I currently have no easy access.

cheers

### Version

18.0.0

### Expected behavior

1. no bash syntax error
2. pass path parameters in windows style to JVM process

### Actual behavior

1. bash syntax error
2. path parameters are passed in cygwin style to JVM process

### How to Reproduce?

1. call kc.sh inside cygwin environment -> syntax error `bin/kc.sh: line 5: CFILE: command not found`

2. fix 1. and call kc.sh -> entry point io.quarkus.bootstrap.runner.QuarkusEntryPoint not found due to wrong path to quarkus-run.jar

**Comment by vmuzikar** [comment]
@elkman Thank you for reporting this! Since you have a proposal for a fix, could you please open a PR? We can discuss details in there.

**Comment by elkman** [comment]
@vmuzikar I submitted PR #12147 a while ago, but the initial build tests had some issues that I couldn't bring into relationship with the changes of the PR. Can someone with more insight please re-trigger the workflow and also have a look at the results if they fail again.
