### ISSUE TITLE
enable to setup the initial admin user by command line tool 

### ISSUE THREAD

**Issue by gunterze** [keycloak/keycloak#12132]
### Description

Currently the initial admin user can be added manually using the web frontend when accessed from localhost or automatically using environment variables.
Running Keycloak in a container, you can't access the frontend from localhost, so you have to use environment variables KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD.
I would like to have a command line tool - like `add-user-keycloak.sh` in the Wildfly based Keycloak version - which can be executed in the container as an alternative possibility to setup the initial admin user.

### Motivation

Passing predefined default user name and password by environment variables can become a security issue.

**Comment by andre-nascimento-rh** [comment]
I believe this RFE is in the same context of what is being requested [here](https://github.com/keycloak/keycloak/issues/19913) and discussed [here](https://github.com/keycloak/keycloak/discussions/8549).

Therefore, I believe we could close this issue as "Duplicated". 

WDYT, @vmuzikar ?

**Comment by vmuzikar** [comment]
@andre-nascimento-rh Yes, correct, we can consider it a duplicate.

**Comment by andre-nascimento-rh** [comment]
Closed as Duplicated: 

- https://github.com/keycloak/keycloak/issues/19913
- https://github.com/keycloak/keycloak/discussions/8549
