### ISSUE TITLE
IdP backchannel logout does not work with session id in logout

### ISSUE THREAD

**Issue by DmitriyKonenkow** [keycloak/keycloak#12142]
### Describe the bug

Keycloak has external Identity provider. 
User successfuly authorize and keycloak recieved token from IdP 
authentication response
`
{
    "access_token": "eyJraWQiOi...",
    "refresh_token": "iB_P_wJGtU...",
    "scope": "email firstName lastName phone openid",
    "id_token": "eyJraWQiOiIx...",
    "token_type": "Bearer",
    "expires_in": 1800
}
`

id_token
`
{
  "iss": "https://passport...",
  "sub": "180f024c-0325-405c-bb5e-8bb0646487df",
  "aud": [
    "j11pv8lg61kMGV4oj6dcvWHhcVka"
  ],
  "exp": 1653298807,
  "iat": 1653297007,
  "auth_time": 1653297007,
  "amr": [
    "pwd"
  ],
  "azp": "j11pv8lg61kMGV4oj6dcvWHhcVka",
  "nonce": "1v6zFa2Sh9_2NnebaOLT6Q",
  "sid": "a84db92e-3be5-4c3d-bc3f-cb4f3ca4b018",
  "at_hash": "8i-rGWZRbH1xp2-Didkq0sJ3WRXh2bgPv-w9L6FN_Jc"
}
`
Then user move to another application and logout from it.
After that keycloak recieved logout token from IdP
`
{
  "sid": "a84db92e-3be5-4c3d-bc3f-cb4f3ca4b018",
  "iss": "https://passport...",
  "sub": "180f024c-0325-405c-bb5e-8bb0646487df",
  "aud": "j11pv8lg61kMGV4oj6dcvWHhcVka",
  "iat": 1653297201,
  "jti": "a0aeec65-3928-4565-902b-adeb61348283",
  "events": {
    "http://schemas.openid.net/event/backchannel-logout": {}
  },
  "exp": 1653299001
}
`
User session does not closed.

### Version

18.0.0

### Expected behavior

Keycloak should close user session from backchannel logout request of Identity Provider.

### Actual behavior

User session stile active in keycloak.

### Anything else?

As I understand keycloak expecting session id in field session_state from authentification token response. But IdP does not use it, as  it is not specified in https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse.
But sid specified in logout token (https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken) and IdP return it.
In this case keycloak tries close defined session, but can not find it.
So user session does not closed.

**Comment by mposolda** [comment]
@DmitriyKonenkow Thanks for the report. Do you have any logs or other debugging info or are the things, which you described in the "Anything else" section just your assumptions?

I believe the cause of the bugs is not `session_state` VS `sid` problem, but rather the fact that Keycloak does not have support for react on backchannel or frontchannel logout requests sent to it from 3rd party IDP.

**Comment by DmitriyKonenkow** [comment]
I checked situation on keycloak.
logout token and condition to close session
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/8981992/170963603-770f58ca-bac4-45b1-a279-08f0fe8dca8d.png">

user session state
<img width="863" alt="image" src="https://user-images.githubusercontent.com/8981992/170963650-cde30c70-7b14-4725-8fd5-1c8e56e65e7c.png">

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now.

@DmitriyKonenkow Thanks for your investigation and details on this! If you (or anyone else) is interested in sending the PR to fix this, it will be helpful!

It looks that Keycloak should prefer to use the ID from the LogoutToken. At the same time, it can check that if `brokerSessionId` is not null and it is different that the one from LogoutToken, then some WARNING can be possibly printed to server log.

**Comment by colmbrady** [comment]
I think the bug in the code is here: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L516

Pretty sure it should be looking in the ID Token for the SID, and then fallback to the Access Token if it cant find it there. Ive noticed that the IDP I am integrating with (https://www.ory.sh/docs/oauth2-oidc/oidc-logout) will only have the users SID in ID Token.

**Comment by jonkoops** [comment]
@colmbrady If you feel you have a fix that might work, feel free to open a PR so we can evaluate it.

**Comment by colmbrady** [comment]
https://github.com/colmbrady/keycloak/commit/30a89140e7573d99dd0bf0fa697e28bf84c0b11e

I defer to others to guide on the correctness of this change regards the OIDC spec, however, it does seem like it will make my integration work when Identity Brokering against the ORY hydra IDP. (https://github.com/ory/hydra)

**Comment by kherock** [comment]
Hi, I just found this today while trying to enable Auth0's recent support for backchannel logouts.

@mposolda I'd say that Keycloak is incorrectly implementing the OIDC Session Management spec here
 
https://openid.net/specs/openid-connect-backchannel-1_0.html#rfc.section.2.1

> The sid (session ID) Claim **used in ID Tokens and as a Logout Token parameter** has the following definition (which is identical to the corresponding definition in [OpenID Connect Front-Channel Logout 1.0](https://openid.net/specs/openid-connect-backchannel-1_0.html#OpenID.FrontChannel) [OpenID.FrontChannel]):

As far as I can tell, the `session_state` parameter from the OIDC Session Management spec being used instead here has no direct relation to the `sid` claim. I think it is an error to be depending on this value at all.

**Comment by colmbrady** [comment]
We have been stuck on an old version of Keycloak, so I never tried to make a P.R for this issue on master. However, I did implement a custom authenticator which we inserted into our post login flow for identity brokering, and it appears to work.

Would be better to implement the fix in the core product, but as a work around, this should work.
```
import org.jboss.logging.Logger;

import org.keycloak.authentication.AuthenticationFlowContext;
import org.keycloak.authentication.AuthenticationFlowError;
import org.keycloak.authentication.Authenticator;
import org.keycloak.authentication.authenticators.broker.util.PostBrokerLoginConstants;
import org.keycloak.authentication.authenticators.broker.util.SerializedBrokeredIdentityContext;

import org.keycloak.jose.jws.JWSInput;
import org.keycloak.models.*;
import org.keycloak.representations.IDToken;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.keycloak.services.managers.AuthenticationManager;

/**
 * This is a very specific fix up for a Back Channel Logout issue with Keycloak. Basically we need to correctly
 * update the users session with the External IDP Session State, so that Back Channel Logout can work.
 *
 * Currently, Keycloak does not pull this state from the ID Token, therefore it fails to work.
 */
public class BackChannelLogoutAuthenticator implements Authenticator {

    private static final Logger LOGGER = Logger.getLogger(BackChannelLogoutAuthenticator.class);

    private static final String IDP_CONTEXT = PostBrokerLoginConstants.PBL_BROKERED_IDENTITY_CONTEXT;

    @Override
    public void authenticate(final AuthenticationFlowContext context) {
        if (context.getUser() == null) {
            LOGGER.debugf("No user in context. This authenticator cant run without a user.", context.getUser().getId());
            context.failure(AuthenticationFlowError.UNKNOWN_USER);
            return;
        } else {
            LOGGER.debugf("Found user '%s' in context", context.getUser().getId());
        }
        try {
            LOGGER.debugf("Attempting to deserialize the broker identity session context", context.getUser().getId());
            // de-serialise the identity from the login flow.
            final SerializedBrokeredIdentityContext sbic = SerializedBrokeredIdentityContext.readFromAuthenticationSession(context.getAuthenticationSession(), IDP_CONTEXT);
            if (sbic == null) {
                throw new IllegalStateException("Brokered identity context is null. This is not expected, unable to store remote session id from External IDP.");
            }
            if (sbic.getToken() == null) {
                throw new IllegalStateException("Access Token Payload is null from External IDP - Have you marked enable 'Store Tokens' in the Identity Provider config for this IDP?");
            }
            // extract the access token payload json which should be saved when authentication happens.
            final IDToken parsedToken = getIDTokenFromAccessTokenPayload(sbic.getToken());

            // Generate the broker session id correctly from the ID Token SID claim. Keycloak does this incorrectly which triggers this bug.
            final String brokerSessionId = sbic.getIdentityProviderId() + "." + parsedToken.getSessionId();

            LOGGER.debugf("Generated new broker Session State ID '%s' for user '%s'.", brokerSessionId, context.getUser().getId());

            // Update the serialised broker context with correct session id.
            sbic.setBrokerSessionId(brokerSessionId);
            try {
                sbic.saveToAuthenticationSession(context.getAuthenticationSession(), IDP_CONTEXT);
            } catch (Exception e) {
                // TODO: not sure if this would actually be serious enough to stop the auth flow from continuing so
                // going to swallow the error
                LOGGER.error("Swallowing exception", e);
            }
            LOGGER.debugf("Attempting to save the newly generated session id to as a persisted user session  with parent ID '%s'.", context.getAuthenticationSession().getParentSession().getId());

            // Finally, create the user session - which won't already exist and ensure we save the
            // updated broker session id with the correct session state from the external IDP so back channel logout works
            final UserSessionModel.SessionPersistenceState persistenceState = UserSessionModel.SessionPersistenceState.fromString(context.getAuthenticationSession().getClientNote(AuthenticationManager.USER_SESSION_PERSISTENT_STATE));
            context.getSession().sessions().createUserSession(
                    context.getAuthenticationSession().getParentSession().getId(),
                    context.getRealm(),
                    context.getAuthenticationSession().getAuthenticatedUser(),
                    context.getAuthenticationSession().getAuthenticatedUser().getUsername(),
                    context.getConnection().getRemoteAddr(),
                    context.getAuthenticationSession().getProtocol(),
                    false, // Unsure where this value could come from!
                    brokerSessionId,
                    sbic.getBrokerUserId(), // This broker user id appears to be correct so use the existing one
                    persistenceState); // persistenceState will default to PERSISTENT when not provided.

            LOGGER.debugf("Updated session state correctly for user '%s'. Authenticator has succeeded, about to call success.", context.getUser().getId());

            context.success();

            LOGGER.debugf("SUCCESS called.");
        } catch (Exception e) {
            LOGGER.error("Error generating a brokered session id.", e);
            context.failure(AuthenticationFlowError.INTERNAL_ERROR);
        }
    }

    private static IDToken extractIdToken(String idToken) {
        try {
            JWSInput input = new JWSInput(idToken);
            return input.readJsonContent(IDToken.class);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static IDToken getIDTokenFromAccessTokenPayload(String accessTokenPayloadJson) {
        try {
            final JSONParser parser = new JSONParser();
            // Get the Access Token Payload Response
            final JSONObject tokenAsObj = (JSONObject) parser.parse(accessTokenPayloadJson);
            // Get the ID Token from that response
            final String idToken = (String) tokenAsObj.get("id_token");
            final IDToken parsedToken = extractIdToken(idToken);
            LOGGER.debugf("Found ID Token from stored External IDP token payload issued by %s.", parsedToken.getIssuer());
            return parsedToken;
        }
        catch (RuntimeException e) {
            throw e;
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public boolean configuredFor(final KeycloakSession session, final RealmModel realm, final UserModel user) {
        // Always returns true as no additional configuration is required for a user to use this authenticator
        return true;
    }

    @Override
    public boolean requiresUser() {
        // User must have logged in and be in session prior to doing this step
        return true;
    }

    @Override
    public void action(final AuthenticationFlowContext context) {
        // Not invoked as authenticate() does not submit a form
    }

    @Override
    public void setRequiredActions(final KeycloakSession session, final RealmModel realm, final UserModel user) {
        // Not invoked as users are always configured for this authenticator, i.e. configuredFor() always returns true
    }

    @Override
    public void close() {
        // No resources to close
    }

}```

**Comment by colmbrady** [comment]
I noticed my link to the bug in the code is now outdated too.. but I think the fix should be in that area of the code. Basically, setting the broker session id should fix issue.

**Comment by thomasdarimont** [comment]
I just stumbled upon this issue myself. I just tested this with Keycloak 25.0.2. 

I created two Keycloak realms (`target`, `source`) and used `source` as an OIDC IdP `customidp` in the `target` realm.

I now login to `target` via the `source` IdP see two user sessions created in the admin UIs- one in the `source` and one in `target` realm. 

To test the backchannel logout, I use a custom endpoint to generate a `LogoutToken` with the `sid` claim set to the `source` user session id.  

When I send the `LogoutToken` in a POST request to the `$ISSUER/protocol/openid-connect/logout/backchannel_logout` endpoint in the `target` realm then the `target` user session is correctly inferred with a userSession lookup by brokerUserSessionId `customidp.$sid`. After that the user session is terminated in the `target` realm.

Is that what you wanted to do?

**Comment by colmbrady** [comment]
@thomasdarimont I think your scenario works as Keycloak assumes that the Token Payload has the session ID, where as most other IDPs have the session ID in the ID Token, not token payload. So when you test this with Keycloak to Keycloak, it will work.

**Comment by kfaseela** [comment]
@DmitriyKonenkow @mposolda : Can we reopen this issue? I have pushed a fix for the same as per the suggestions in the issue, and the fix works. https://github.com/keycloak/keycloak/pull/48674

**Comment by mabartos** [comment]
Seems that it is active again and will be fixed. Reopening.

cc: @mposolda
