### ISSUE TITLE
IDP with PKCE: Token-Request body contains non-standard parameter

### ISSUE THREAD

**Issue by MarkusTStecher** [keycloak/keycloak#12141]
### Describe the bug

We are configuring a IdentityProvider in Keycloak with PKCE enabled and PKCE method "SH256". In the token request Keycloak sends the parameter "code_challenge_method" although it's non-standard.  The Identity-Provider we configure cancels the request because the request body contains a non-standard parameter. For security reasons all requests with non-standard parameters are blocked.

Specs: 
- https://openid.net/specs/openid-connect-core-1_0.html#TokenRequest
- https://datatracker.ietf.org/doc/html/rfc7636#section-6.1

Can the parameter "code_challenge_method" be removed in one of the next keycloak versions?

### Version

18.0.0

### Expected behavior

Token Request should not contain parameter "code_challenge_method"

 ```
 POST /token HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

grant_type=authorization_code
&code=SplxlOBeZQQYbYS6WxSbIA
&redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
&code_verifier=random_code_verifier
```

### Actual behavior

Token Request contains parameter "code_challenge_method"

 ```
 POST /token HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

grant_type=authorization_code
&code=SplxlOBeZQQYbYS6WxSbIA
&redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
&code_verifier=random_code_verifier
&code_challenge_method=S256
```

**Comment by mposolda** [comment]
@MarkusTStecher Thanks for the report. I agree that the "code_challenge_method" should not be sent in the token request according to https://datatracker.ietf.org/doc/html/rfc7636#section-4.5 .

I am marking as "Help wanted" . Anyone is welcome to contribute the PR with the fix. The related automated test is `KcOidcBrokerPkceTest` .

**Comment by lexcao** [comment]
Hi, @mposolda I just created a PR to fix it.
Please help to review.
https://github.com/keycloak/keycloak/pull/12473
