### ISSUE TITLE
Investigate enabling `X509DirectGrantTest#loginCertificateExpired` for the new store

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12151]
### Describe the bug

In the PR: https://github.com/keycloak/keycloak/pull/12066 we needed to ignore `loginCertificateExpired`. See https://github.com/keycloak/keycloak/pull/12066#discussion_r875831243 for more details.

We need to investigate whether it is possible to re-enable this test without the need for having 
https://github.com/keycloak/keycloak/issues/11053 closed first.

A possible solution is to move in time before the year 2038 when the integer timestamp overflows.

### Version

main

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
