### ISSUE TITLE
Initial admin account not being recreated when other admin accounts are already present

### ISSUE THREAD

**Issue by cedricguindon** [keycloak/keycloak#12169]
### Describe the bug

When the keycloak docker container restarts, it attempts to create the initial admin account based on the "KEYCLOAK_ADMIN" and "KEYCLOAK_ADMIN_PASSWORD" environment variable.

If the initial admin account was previously deleted and there is at least 1 user already in the master realm, the admin account will not be recreated and give the following error:

ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'user' to realm 'master': user with username exists

### Version

18.0.0

### Expected behavior

I would expect the same behavior as keycloak 16 and before where the admin user would simply be recreated if it was previously deleted.

### Actual behavior

The admin acocunt which is supposed to be created with the environment variable does not get created.

### How to Reproduce?

1. Proceed with a regular launch of a keycloak docker container instance.
2. Log in the master realm and create 1 user with realm admin role.
3. Delete the admin account that was created at deployment using the "KEYCLOAK_ADMIN" environment variable.
4. stop-start the container without wiping the DB.
5. The error will be in the logs, the admin user will not be created.

### Anything else?

We have a case figure where the initial admin account needs to be deleted and we are creating individual admin accounts in the master realm, this way each dev has an account in the master realm with an OTP.

Our security guidelines can't leave an admin account active without an OTP therefore the initial admin accounts needs to be delete once the deployement is over, recreated at a stop-start to execute start-up scripts then redeleted once the scripts are completed.

**Comment by cedricguindon** [comment]
Here's some more info i could find.

[keycloak github page](https://github.com/keycloak/keycloak/blob/45b203d74c267de60706d8dbfee0ef06a6e37336/services/src/main/java/org/keycloak/services/managers/ApplianceBootstrap.java)

The above seems to be the reason why the problem is occuring.
The method createMasterRealmUser is checking if there's already users present in the master realm instead of checking if the user passed in the environmenet variable is already present

`if (session.users().getUsersCount(realm) > 0) {
            throw new IllegalStateException("Can't create initial user as users already exists");
        }`

**Comment by cedricguindon** [comment]
@pedroigor 
We have a use case where we're not allowed to have an admin account that can be used to connect to any realm without the use of an OTP mechanism. We are allowed personal admin accounts with OTP and each have our own password our personal admin accounts are located in the master realm so that we have access to everything.

We however need an admin account that can execute scripts once the application is started without using our our personal admin accounts and sharing our password.

Our use case used to work prior to keycloak 17, our script was executing kcadm.sh commands then was deleting itself once the job was completed, on subsequent deployment, the keycloak deployment script was then recreating the admin account, script executed again and then redeleted itself.

We noticed that the admin user creation changed from keycloak 17 onward, it no longers get's recreated if there are other admin accounts present.

I have a workaround at this time, which is to keep the initial admin account active but to prevent it to connect to the security-admin-console by the use of a custom browser flow but this is not perfect since we could have other browser flow that will not have the deny access execution based on realm role.

**Comment by pedroigor** [comment]
Glad to hear that service accounts work.

Not the best thing to do, but perhaps you can check if you see in logs an entry like `Initializing database schema`. If the entry is there is because you are starting the server for the very first time.

In any case, I would close this issue and keep discussions [here](https://github.com/keycloak/keycloak/discussions/8549) if it works for you.

**Comment by senyahnoj** [comment]
Please see duplicate issue #19913
