### ISSUE TITLE
Jpa map storage: failure to process changelogs when using CockroachDB

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#12176]
### Describe the bug

After the addition of new unique constraints for the attributes tables, the changelogs can't be processed anymore when using `CockroachDB` because of lack of support for `DEFERRABLE` and `INITIALLY DEFERRED` options.

The new constraint looks like this:

```
        <addUniqueConstraint tableName="kc_client_scope_attribute" columnNames="fk_root, name, value" deferrable="true" initiallyDeferred="true" />
```

When Keycloak attempts to create the DB schemas using `CockroachDB`, it fails with:

```
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/client-scopes/jpa-client-scopes-changelog-1.xml::client-scopes-1::keycloak:
     Reason: liquibase.exception.DatabaseException: ERROR: at or near "EOF": syntax error: unimplemented: this syntax
  Detail: source SQL:
ALTER TABLE public.kc_client_scope_attribute ADD UNIQUE (fk_root, name, value) DEFERRABLE INITIALLY DEFERRED
                                                                                                           ^
  Hint: You have attempted to use a feature that is not yet implemented. See: https://go.crdb.dev/issue-v/31632/v21.2 
```

After reading the issue linked in the error description, I saw that there's no indication that support for these options will be added in the near future, so we might need to split these constraints into a separate changeset targeting `PostgreSQL` only, leaving the constraint out in case `CockroachDB` is used.

### Version

main

### Expected behavior

The changesets should be processed successfully when using both `PostgreSQL` and `CockroachDB`.

### Actual behavior

Changesets can't be processed when using `CockroachDB` due to unsupported options in the unique constraint found in the attributes tables.

### How to Reproduce?

Follow the instructions at https://github.com/keycloak/keycloak/discussions/9596 to start Keycloak with `CockroachDB` - just attempt to start the server with a clean database.

**Comment by ahus1** [comment]
@sguilhen - sorry to hear that my change broke the CockroachDB support. I'll also investigate if I can teach Hibernate to first delete and then insert, I remember I saw a knob somewhere. Then we wouldn't need to defer them, although Hibernate might have that order of first inserting for a reason. I'll give it a look and report back here with some insights.

**Comment by sguilhen** [comment]
Thank you @ahus1 !
