### ISSUE TITLE
Better message when a build options is passed to a runtime command like `start`

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#12187]
### Description

Currently, if you use a build options when running `start` you get a message as following:

```
./kc.sh start --proxy edge --hostname mykeycloak --health-enabled true                                                                                                
Unknown option: '--health-enabled' 
```

Looks like we can improve here and provide a better message indicating that the options is a build option and need to be used with the `build` command or using the `--auto-build` option. Something like:

```
Unknown option: '--health-enabled'. This is a build option and should be set using the `--auto-build` option.
```

### Motivation

Improve CLI messages and configuration.

**Comment by shawkins** [comment]
This has been addressed in the last couple of releases.
