### ISSUE TITLE
Allow setting the admin hostname

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#12190]
### Description

See https://github.com/keycloak/keycloak/discussions/12186.

### Discussion

https://github.com/keycloak/keycloak/discussions/12186

### Motivation

Improve usability when deploying the server and exposing the administration console using a hostname other than what is set to the frontend URLs.

**Comment by thomasdarimont** [comment]
Currently users can set a dedicated admin hostname via the hostname spi configuration, e.g. `KC_SPI_HOSTNAME_DEFAULT_ADMIN=admin.acme.test`
