### ISSUE TITLE
Add `RealmModel` to remove methods for all areas

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#12206]
When removing objects we want to make sure we are removing objects belonging to correct realm.

E.g.  for user sessions it is already implemented this way. https://github.com/keycloak/keycloak/blob/main/model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java#L365-L374

But for some it's missing, e.g. roles: https://github.com/keycloak/keycloak/blob/main/model/map/src/main/java/org/keycloak/models/map/role/MapRoleProvider.java#L158-L170

This issue is about adding the realm for all areas when removing objects.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
