### ISSUE TITLE
data/import missing in Keycloak 18 Docker Image

### ISSUE THREAD

**Issue by Manu10744** [keycloak/keycloak#12224]
### Description

I was glad to see that the realm import feature that supports importing a realm during startup of keycloak is coming back in Version 18, so I pulled the image `quay.io/keycloak/keycloak:18.0`. Unfortunately, you state that

> When you set the --import-realm option, the server is going to try to import any realm configuration file from the data/import directory. Each file in this directory should contain a single realm configuration.

### Motivation

But this directory does not exist in the Docker Image, which makes using this feature imo unneccesarily uncomfortable because 
a) I don't want to create an own keycloak docker image where this dir is created in the dockerfile only because I need to create one directory 
b) I don't see why you should hardcore the directory anyway. Why did you not reimplement it the same way like it was back in the day where you only had to specify a path via an environment variable? 

### Details

Please return to the old way of configuration or at least update your Docker Image accordingly.

**Comment by pedroigor** [comment]
Yes, it does not exist but you can just run:

```
docker run --name keycloak_test -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
        --mount type=bind,source=/tmp/import,target=/opt/keycloak/data/import \
        quay.io/keycloak/keycloak:latest \
        start-dev --import-realm
```

Why do you need to pass a directory if you can just copy/mount the file to that dir? When doing containers is one less thing you should do because and less error-prone because you don't need to specify the file location twice (when setting the option and when mounting the file).

**Comment by abstractj** [comment]
@Manu10744 we really appreciate you taking the time-sharing your feedback. Although, it is possible to achieve the same outcome based on @pedroigor suggestions. I tried the same with Podman and Kubernetes, and I could not find any reason to use the old way.


```
podman run -v /tmp/import:/opt/keycloak/data/import:z -p 8180:8180/tcp -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -it quay.io/keycloak/keycloak:nightly start-dev --http-port 8180 --import-realm
```
