### ISSUE TITLE
Keycloak 18.0.0 on ECS Fargate doesn't work behind ALB with rules based on URL

### ISSUE THREAD

**Issue by sergeyanover** [keycloak/keycloak#12237]
### Description

I tried to implement Keycloak 18.0.0 on ECS Fargate behind ALB with rules based on URL and it didn't work with many combinations of options. I used Keycloak in HTTP mode on port 8080 and my task is to run it behind ALB with rule like https://www.domain.com/keycloak/ -> Internal IP of Task ECS. In version 16.0.0 this feature worked well (web-context in standalone-ha.xml). 
Please, check the ability to do the same in 18.0.0 and give a feedback, maybe I missed something or it really doesn't work with options like --hostname, --hostname-path, --proxy=passthrough, --hostname-strict-backchannel
Besides, in documentation we can find Error 404 - https://www.keycloak.org/server/hostname and link [{links_server_proxy_name}](https://www.keycloak.org/server/%7Blinks_server_proxy_url%7D) Guide.

**Comment by JayAhn2** [comment]
@sergeyanover I have the same issue now.. Have you got a chance to get through it?

**Comment by sergeyanover** [comment]
I am still using 18.0.0 with regular LB, not that old one ALB with rules. We should try 18.0.2.

**Comment by shawkins** [comment]
Closing as out of date. If this can be reproduced on KC 25+ with hostname v2 settings, then please reopen.
