### ISSUE TITLE
EventType.UPDATE_TOTP_ERROR is unused

### ISSUE THREAD

**Issue by MariuszCwikla** [keycloak/keycloak#12258]
### Describe the bug

It looks like `UPDATE_TOTP_ERROR` enum literal in `EventType` is defined but unused throughout the code.

Effectively it means that successful TOTP setup results with `UPDATE_TOTP` event, but if user provides invalid otp during setup then event is not published.
It would be reasonable to add support for unsuccessful scenario.

I have already prepared a PR for this.

### Version

18.0.0

**Comment by pedroigor** [comment]
See
