### ISSUE TITLE
Cleanup expiration handling for `ClientInitialAccesses`

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12268]
Currently, we have the following condition in `MapRealmEntity`. 
https://github.com/keycloak/keycloak/blob/d083b6c4849c5d8bde9762d410a76b0aedf8f4b1/model/map/src/main/java/org/keycloak/models/map/realm/MapRealmEntity.java#L239-L242

This condition should not be there in the physical layer, it should be moved to the logical layer. Maybe even removed completely as it is checked here already:
https://github.com/keycloak/keycloak/blob/d083b6c4849c5d8bde9762d410a76b0aedf8f4b1/services/src/main/java/org/keycloak/services/clientregistration/ClientRegistrationAuth.java#L145-L153

Also, in current Map store implementations, we [changed](https://github.com/keycloak/keycloak/pull/12066) expiration from lifespan to point in the time when the entity expires. It is possible, that after this change the timestamp field is not needed anymore. If this is the case, we should remove it. Since we cannot remove the field from `ClientInitialAccessModel` a possible solution would be to set the model timestamp to 0. When this is set the formula above should give correct results because `timestampCreated + lifespan` == `0 + timestampExpiration`

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
