### ISSUE TITLE
Investigate cache config update on existing cache

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12265]
It seems that the [current solution](https://github.com/keycloak/keycloak/blob/main/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/connections/DefaultHotRodConnectionProviderFactory.java#L158) doesn't update cache configuration when a cache already exists.

**Comment by martin-kanis** [comment]
The following attributes of a cache can be updated in Infinispan 14.0.0.CR1 using CLI:
```
clustering.remote-timeout
expiration.lifespan
expiration.max-idle
expiration.interval
jmx-statistics.statistics             
memory.max-count
memory.max-size
transaction.single-phase-auto-commit  
transaction.stop-timeout
locking.acquire-timeout                                      
```
