### ISSUE TITLE
Ingress creation loop

### ISSUE THREAD

**Issue by derverzweifler** [keycloak/keycloak#12274]
### Describe the bug

The nightly operator stucks in an ingress creation loop, even when ingress creation is disabled.

First, the operator removes the Ingress when `disableDefaultIngress: true` and existing ingress is found. Then a new ingress is created again. And so on...
https://github.com/keycloak/keycloak/blob/8f54f03f17cbe985e763fb4ce101c569d2842740/operator/app/src/main/java/org/keycloak/operator/v2alpha1/KeycloakIngress.java#L46-L51

### Version

nightly

### Expected behavior

Ingress should not be created when `disableDefaultIngress: true`

### Actual behavior

Ingress is created, then removed, then created again in a loop manner.

### How to Reproduce?

Deploy nightly operator and apply a Keycloak CRD with `disableDefaultIngress: true`

**Comment by andreaTP** [comment]
Thanks for taking the time to file this issue @derverzweifler
I just submitted a fix for it!

**Comment by abstractj** [comment]
@stianst added this to the queue, so we don't miss it. @andreaTP would like to include it in the next release.

@andreaTP please submit the backport to our repository. If you have any troubles doing it, please let me know or ping @DGuhr

**Comment by andreaTP** [comment]
Done: https://github.com/keycloak/keycloak-prod/pull/484
