### ISSUE TITLE
Identity provider decoding issue in ID token

### ISSUE THREAD

**Issue by WillemNoort** [keycloak/keycloak#12275]
### Describe the bug

When configuring a Keycloak realm as Identity provider in another realm, I have trouble importing first and last names with special characters. It looks like a decoding issue.

### Version

18.0.0

### How to Reproduce?

For example, I have configured two realms, 'RealmA' and 'RealmB', where RealmA is configured as Identity provider in RealmB. When a user from RealmB log in to RealmA using the identity provider, I get the following:

User in RealmA:
![Screenshot 2022-05-31 at 14 51 18](https://user-images.githubusercontent.com/103425897/171177497-4bf64724-7064-4b2b-b4b6-745deb3876bf.png)

User imported in RealmB:
![Screenshot 2022-05-31 at 14 53 35](https://user-images.githubusercontent.com/103425897/171177936-784c0e0e-b2d3-4aee-953b-2522b5388c76.png)

### Anything else?

I tried debugging the issue, but could couldn't find an obvious bug. 

ID token decodes correctly:
![Screenshot 2022-05-31 at 15 07 19](https://user-images.githubusercontent.com/103425897/171180509-3e7fd659-053f-4b4e-8d3e-b2b453f9aa36.png)

Name is stored in database incorrectly:
![Screenshot 2022-05-31 at 15 02 59](https://user-images.githubusercontent.com/103425897/171179688-b9fc84ef-55a7-444c-b8c7-05fa85a104c3.png)

**Comment by WillemNoort** [comment]
This seems to be fixed in the 18.0.1 release, with https://github.com/keycloak/keycloak-prod/pull/472

**Comment by mabartos** [comment]
@WillemNoort Could you please verify, that the issue is already resolved with the 18.0.1 release? Thank you.

**Comment by WillemNoort** [comment]
I can confirm that the issue is indeed fixed
