### ISSUE TITLE
Review Profile doesn't update data on First Broker Login

### ISSUE THREAD

**Issue by aleluc13** [keycloak/keycloak#12284]
### Describe the bug

Update Account data in Review Profile page won't work after first broker login of an existing account.

### Version

17.0.0-1
18.0.0
19.0.1

### Expected behavior

Changed fields (email, first name and last name) in Review Profile page should be saved.

### Actual behavior

Profile changes doesn't persist.

### How to Reproduce?

1. Realm Settings > Login > **Email as username**: `ON`
3. Configure any IdP, like Github
4. Authentication > Flows > First Broker Login > Review Profile > Actions > Config > **Update Profile on First Login**: `on`
5. Create an account via registration form, complete it, and sign out
6. Sign in with your IdP (account with the same email as created before)
7. In Update Account Information form modify any field like first name, then Submit
8. In Confirm Link Existing Account page > **Add to existing account**
9. Confirm Linking account via email

### Anything else?

Note: I can update account data from Account Console.

**Comment by aleluc13** [comment]
It also happens with version 18.0.0

**Comment by aleluc13** [comment]
Still happening with version 19.0.1

**Comment by daniel-ITC** [comment]
I'm using a SAML IDP but the problem is the same. Also I have the User Profile feature enabled. I also set the sync mode to force and then try to update some fields on the Review idp profile (not during the first login flow) but without success.

**Comment by mposolda** [comment]
@aleluc13 Question:
- Do you have "User Profile" feature enabled?
- What exactly are your sync settings? It means sync settings for your IDP and also sync settings for IDP-mapper for the target attribute, which is not updated by review profile (like firstName for example)

**Comment by aleluc13** [comment]
Hi @mposolda ,

- Do you mean `declarative-user-profile` feature?
- About sync settings, we have **sync mode**: `import`. 

We also , tried sync mode `force` and it works for default fields like first name, but not for custom fields, even with IDP-mappers I can't make it work for custom user attributes like _phone_. Our IDP-**Mapper type** is `Attribute importer`. Any suggestion?

Thanks in advance

**Comment by mposolda** [comment]
@aleluc13 Yes, I meant `declarative-user-profile` feature. Is it enabled or disabled in your environment? If you did not change anything and did not enabled "preview" profile, it is disabled by default (as it is preview feature).

**Comment by mposolda** [comment]
@aleluc13 There is no response to my previous question, so I am closing. Feel free to re-open if still applicable for you, but then please add the response to my last question (whether `declarative-user-profile` is enabled or not).

**Comment by it-luke** [comment]
Can we please reopen this? I confirm that this problem occurs in the latest version `26.2.4`. After adding the required custom user attribute along with the mapper, it's even worse—user is asked to fill this value twice! The first time at step 6 described in the original submission, after which the value is lost, then after step 8, when the user is shown the same screen with a blank non-standard field and the `firstName` and `lastName` attributes, whose values are taken from the data in the profile. This creates a terrible experience for the user.

> please add the response to my last question (whether declarative-user-profile is enabled or not).

`declarative-user-profile` is obviously enabled.
