### ISSUE TITLE
Managing User Profile

### ISSUE THREAD

**Issue by alirf81** [keycloak/keycloak#12289]
### Describe the bug

1. I configured the firstname required for admin only but it is reset to default (user) on restart.
![image](https://user-images.githubusercontent.com/92157864/171388064-6bd19c30-9a59-4746-a97f-d4d3a6dc211e.png)
As I checked the db, when I restart my docker-compose project, the configuration entries for user profile are removed in `component_config` table. I guess while initializing the Keycloak, it reset user profile setting to default.

2. Export/Import for User profile setting doesn't work. I use `kc.sh import/export` to backup/restore my configuration.
`    "org.keycloak.userprofile.UserProfileProvider" : [ {
      "id" : "fed2ebb4-81eb-40b6-a501-c0fdd44d9b50",
      "providerId" : "declarative-user-profile",
      "subComponents" : { },
      "config" : {
        "config-piece-0" : [ "{\"attributes\":[{\"name\":\"username\",\"displayName\":\"${username}\",\"validations\":{\"length\":{\"min\":3,\"max\":255},\"username-prohibited-characters\":{}}},{\"name\":\"email\",\"displayName\":\"${email}\",\"validations\":{\"email\":{},\"length\":{\"max\":255}}},{\"name\":\"firstName\",\"displayName\":\"${firstName}\",\"required\":{\"roles\":[\"admin\"],\"scopes\":[]},\"permissions\":{\"view\":[\"user\",\"admin\"],\"edit\":[\"user\",\"admin\"]},\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}},\"selector\":{\"scopes\":[]}},{\"name\":\"lastName\",\"displayName\":\"${lastName}\",\"required\":{\"roles\":[\"admin\"],\"scopes\":[]},\"permissions\":{\"view\":[\"user\",\"admin\"],\"edit\":[\"user\",\"admin\"]},\"validations\":{\"length\":{\"max\":255},\"person-name-prohibited-characters\":{}},\"selector\":{\"scopes\":[]}}]}" ],
        "config-pieces-count" : [ "1" ]
      }
    } ],`
And user profile setting is exported properly but not imported at all.

### Version

18.0.0

**Comment by gdhameeja** [comment]
I'd like to work on this. Although, I've used keycloak for work (at beginner level), this is my first time contributing to keycloak. Can someone please guide me on how I can get started on fixing this?

**Comment by pedroigor** [comment]
@gdhameeja Thanks for your interest. Are you still available for contributing a patch for this one?

**Comment by pedroigor** [comment]
@alirf81 I was able to import the settings after exporting using the `import` and `export` commands, respectively.

I'm basically doing this:

```
# Start the server, then create a realm, enable UP, and change the UP config like adding a new attribute, etc
./kc.sh start-dev --features declarative-user-profile

# Export
./kc.sh export --dir /tmp/export --realm test

# Start the server again and remove the test realm

# Import
./kc.sh import --dir /tmp/export
```

Could you please check if I'm missing something and how to reproduce it?

**Comment by alirf81** [comment]
@pedroigor thanks for checking
Can you please try the following?
- configure firstname and lastname not required.
- export realm setting and re-import (please make sure it replaces existing realm setting or please clean db before importing)
- check if firstname and lastname are still configured not to be required

**Comment by alirf81** [comment]
@pedroigor are there any updates on this issue?
I tried your instruction but the issue still remains.
The user profile is enabled after I import JSON but the configuration of firstname or lastname are not imported but just have the default configuration.

**Comment by pedroigor** [comment]
@alirf81 Sorry for the late reply. I exported a `test` realm to this [file](https://github.com/keycloak/keycloak/files/9419566/realm-export.zip).

This file marks the `firstName` as required and `lastName` as not required.

After importing, the configuration for both attributes is set as expected.

Perhaps something changed during this time so if you can try it again, I appreciate it.

Sorry again for the time taken to reply to your last comment.
