### ISSUE TITLE
Client Policies: pkce-enforcer executor with client-access-type condition is not applied on client change via Admin API

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak#12295]
### Describe the bug

I like to make sure that public and confidential clients can only be created with PKCE configured appropriately (PKCE challenge method should be S256).
For this purpose, I created a Client Policy with a pkce-enforcer executor. Because I don't want to require this pkce-config for bearer-only clients, I used a client-access-type condition. But the pkce-executor is not triggered when creating or updating a (public or confidential) client via the Admin API.

### Version

18.0.0

### Expected behavior

When creating or updating a client via the Admin API, it should be checked whether PKCE is appropriately configured.

### Actual behavior

Clients can be created or updated without or inappropriate PKCE configuration (code challenge method "plain").

### How to Reproduce?

I created a Client Profile named pkce-policy with the following steps:

1. Creating a pkce-profile:
```
curl --request PUT 'https://<host>/auth/admin/realms/<realm_name>/client-policies/profiles' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "profiles": [
        {
            "name": "pkce-profile",
            "executors": [
                {
                    "executor": "pkce-enforcer",
                    "configuration": {
                        "auto-configure": false
                    }
                }
            ]
        }
    ]
}'
```

2. Creating the pkce-policy based on the profile, with client-access-type restricted to "confidential" and "public":
```
curl --request PUT 'https://<host>/auth/admin/realms/<realm_name>/client-policies/policies' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "policies": [
        {
            "name": "pkce-policy",
            "enabled": true,
            "conditions": [
                {
                    "condition": "client-access-type",
                    "configuration": {
                        "is-negative-logic": false,
                        "type": [
                            "confidential",
                            "public"
                        ]
                    }
                }
            ],
            "profiles": [
                "pkce-profile"
            ]
        }
    ]
}'
```

Now, when creating a new public client without pkce config, I would expect an error, but the client is successfully created (status 201):
```
curl --request POST 'https://<host>/auth/admin/realms/<realm_name>/clients' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "clientId": "test-public",
    "rootUrl": "https://localhost:8443",
    "adminUrl": "https://localhost:8443",
    "enabled": true,
    "redirectUris": [
        "https://localhost:8443/*"
    ],
    "webOrigins": [
        "https://localhost:8443"
    ],
    "standardFlowEnabled": true,
    "protocol": "openid-connect"
}'
```

When updating a client without pkce config, it also succeeds (status 204). I would also expect an error in this case.
```
curl --request PUT 'https://<host>/auth/admin/realms/<realm_name>/clients/<clientUuid>' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "clientId": "test-public",
    "rootUrl": "https://localhost:8443",
    "adminUrl": "https://localhost:8443",
    "enabled": true,
    "redirectUris": [
        "https://localhost:8443/*"
    ],
    "webOrigins": [
        "https://localhost:8443"
    ],
    "standardFlowEnabled": true,
    "protocol": "openid-connect"
}'
```

Is this a bug, or am I missing something in my configuration?

### Anything else?

It seems like the scenario would work as expected, if:

- either ClientAccessTypeCondition#applyPolicy would actually handle UPDATE and REGISTER (not to confuse with UPDATED and REGISTERED) events - see https://github.com/keycloak/keycloak/blob/7335abaf08915d364f16667733237aa8ac8a3b0f/services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientAccessTypeCondition.java#L68
- or PKCEEnforcerExecutor#executeOnEvent would actually handle UPDATED and REGISTERED (not to confuse with UPDATE and REGISTER) events - see https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/services/clientpolicy/executor/PKCEEnforcerExecutor.java#L93
- or both

Not sure what's the best solution in this case - I'm using Client Policies for the first time.

**Comment by tnorimat** [comment]
@danielFesenmeyer IMO, the 1st option seems to be appropriate. If applying the 2nd option, a client with not allowed PKCE setting (code_challenge_method) is registered before `PKCEEnforcerExecutor` checks an updating client request.
I would like to fix the issue as follows:
1. Add `REGISTER` as a event that `ClientAccessTypeCondition` handles. On the event, `ClientAccessTypeCondition` chekcs a content of a proposed client registration request because the client is not yet registerd at this time.
2. Add `UPDATE` as a event that `ClientAccessTypeCondition` handles. On the event, `ClientAccessTypeCondition` chekcs a content of a registered client, not a content of a proposed client updating request.

**Comment by danielFesenmeyer** [comment]
@tnorimat, @mposolda: Thanks for your prompt response and the fix 👍

**Comment by huberts90** [comment]
[danielFesenmeyer](https://github.com/danielFesenmeyer) [tnorimat](https://github.com/tnorimat):
could you indicate where I can find the documentation of the options which could be used to enforce policy (e.g. PKCE), I would like to exclude the client by its name or attribute assigned to it, similarly to the configuration below:
```
            "conditions": [
                {
                    "condition": "client-name",
                    "configuration": {
                        "is-negative-logic": false,
                        "name": "excluded-client",
                    }
                }
            ],
```

**Comment by tnorimat** [comment]
@huberts90 Hello,
Unfortunately, the current keycloak does not have a `condition` of client policies that can exclude the client by its name.
However, you can implement by yourself such the `condition`. https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientAccessTypeCondition.java might be helpful.

**Comment by huberts90** [comment]
Thank you @tnorimat . Is it possible then to somehow "mark" client and use this attribute in the condition? Any kind of client attribute?

**Comment by tnorimat** [comment]
IMO, we can write a `condition` to apply a client that has a specifc client attribute's value. BYW, how about using `ClientRoleCondition` ?

**Comment by huberts90** [comment]
Yes, I could use `ClientRoleCondition`. Is any link to the documentation describing this specific condition or better analyse the code?

**Comment by tnorimat** [comment]
AFAIK, https://www.keycloak.org/docs/latest/server_admin/index.html#_client_policies is describing client policies.

**Comment by huberts90** [comment]
Thank you!
