### ISSUE TITLE
Inconsistent `BrokeredIdentityContext` properties

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#12307]
### Describe the bug

Refactoring for user profile (#7080) has transformed the user model properties first name, last name, email, and username into attributes. This change was not propagated to `BrokeredIdentityContext` class where these attributes are still maintained as fields: https://github.com/keycloak/keycloak/blob/0a8e132c7cdac5cff487a2adc39dacc73f45faf3/server-spi-private/src/main/java/org/keycloak/broker/provider/BrokeredIdentityContext.java#L42-L44

This leads to an inconsistent behaviour in mappers where these attributes are treated differently to the properties regardless they should be just the same.

### Version

18.0.0

### Expected behavior

`BrokeredIdentityContext` needs to treat the now-attributes first name, last name, username, and email as attributes.

### Actual behavior

It is now possible by wrong broker mapper configuration to override a  (irrespective of protocol) accidentally override one of the special four attributes. 

### Anything else?

This has been encountered while reviewing #10650.

Example of such a piece of code is here:
https://github.com/keycloak/keycloak/blob/7e925bfbff5410d27675f10d596b752fa794a4ab/services/src/main/java/org/keycloak/broker/saml/mappers/UserAttributeMapper.java#L145-L155

**Comment by pedroigor** [comment]
Could you please provide the steps to reproduce the problem?

**Comment by mposolda** [comment]
Adding to Backlog for now with the label for `area/user-profile`. We may consider looking into this again once we need to add supported user profile feature.

**Comment by pedroigor** [comment]
I'm closing this one as it is lacking more details on how to set a `wrong broker mapper configuration`.
