### ISSUE TITLE
HotRodMapStorage return null instead of empty delegate

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#12304]
`HotRodMapStorage#read()` and `HotRodMapStorage#update()` should not return `HotRodSingleUseObjectEntityDelegate` when there is nothing found in the storage. 
Also fix the condition in `SingleUseObjectHotRodMapStorage#read`.

**Comment by mhajas** [comment]
We should also add a null check to delegates so we are sure this never happens.
