### ISSUE TITLE
blank page when adding role under client

### ISSUE THREAD

**Issue by phamlankt** [keycloak/keycloak#12302]
### Description

Hello,

I have this strange error when trying to add Role under a client page, it just display a blank white page. I could not find any error in the log.
I am using KC v18.
https://mykeycloak_hostname/admin/master/console/#/create/role/test/clients/9d3a627e-26a7-492d-8e1d-04f449de0a6a
![grafik](https://user-images.githubusercontent.com/45233442/171556167-db268081-6215-4e82-a928-4d3efa16caad.png)

![grafik](https://user-images.githubusercontent.com/45233442/171556011-2686359c-801d-479e-8ff9-4a7cc5773d6a.png)

**Comment by phamlankt** [comment]
I did so many tests and my conclusion is this problem has something to do with the external DNS setup on the loadbalancer. When I use another DNS name, this "Add role" works perfectly. As long as I switched back to the old DNS Name, the "Add role" is not working. @pedroigor is there any restriction on the FQDN Name that might make KC react differently?

**Comment by pedroigor** [comment]
@phamlankt AFAIK, it shouldn't have any restriction. Any chance to easily reproduce this issue?
