### ISSUE TITLE
access token claims are not updated when calling /protocol/openid-connect/token

### ISSUE THREAD

**Issue by mitzen** [keycloak/keycloak#12319]
### Describe the bug

Noticed that access_token claims are not updated when we are trying to update token by calling auth/realms/myrealm/protocol/openid-connect/token endpoint with grant_type: refresh_token or grant_type: authorization_code.

### Version

17

### Expected behavior

Please review How to Reproduce step.

I would have thought steps 8 and 9, would update the refresh_token. Is the the same expectation as well?

### Actual behavior

access token claims does not update customerid, shopperid for days until sessions logout is called. 

### How to Reproduce?

1. Create a new oidc provider, OIDC_Provider. Sync mode is set to '**force**'.
2. Setup 'Attribute Importer' mappers, e.g. customerid, shopperid 
3. Create a client for demosp - (**confidential client**)
4. Request authentication from demospa
5. Complete authentication, receive access token and refresh token in demoapp
6. Observe that the claims is good - we haven't populated the customerid, shopperid claims.
7. Proceed to update claims on OIDC_Provider and update customerid and shopperid.   
8, Request a new access token using grant_type=refresh_token and observe that the claim does not have customerid, shopperid from the new access token.
9. Request a new access token using grant_type=authorization_code and observe that the claim does not have customerid, shopperid from the new access token.
10. Log out from the session.
11. Request authentication from demospa
12. Observe the claim customerid, shopperid appears in the access_token.

**Comment by mposolda** [comment]
I am adding this with the label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to investigate this further and eventually send PR for this.
