### ISSUE TITLE
Set quarkus.datasource.jdbc.max-lifetime or any quarkus property

### ISSUE THREAD

**Issue by vdahlberg** [keycloak/keycloak#12316]
### Describe the bug

Using keycloak with AWS Aurora Serverless, which will discard database connections after 24h, we need to configure the max lifetime of a connection.

I've tried with setting`-Dquarkus.datasource.jdbc.max-lifetime=12H` in `JAVA_OPTS` and/or `quarkus.datasource.jdbc.max-lifetime=12H` in `conf/quarkus.properties` but I can't find any trace of it actually being set in the logs or anything.

I realize this config might not be valid to add as a keycloak configuration but how can I verify that the configuration is actually used?

### Version

18

**Comment by stianst** [comment]
To use unsupported Quarkus configuration you need to specify these in `conf/quarkus.properties`, see https://www.keycloak.org/server/configuration#_unsupported_server_options for more details
