### ISSUE TITLE
AccessTokens generated from RefreshTokens without scope

### ISSUE THREAD

**Issue by SrMouraSilva** [keycloak/keycloak#12326]
### Describe the bug

In my scenario, I want to make the scope `roles` Optional for a specific client A.
As consequence, if the client A wants this information, it's necessary inform it in the list of the scopes when you're requesting the `access_token`.

I notices that when you request a new `access_token` from `refresh_token`, the information related to `roles` scope doesn't appears anymore into `access_token`.

I notice this only when 

### Version

15

### Expected behavior

`roles` information appears in the `access_token` when this information is requested even if it was defined as Optional Token.

### How to Reproduce?

Part 1:

1. Create a Client;
2. Go to `Client Scopes`;
3. Remove `roles` from "Assigned Default Client Scopes";
4. Include `roles` from into "Assigned Optional Client Scopes".

Part 2:

1. Request a `access_token` without informing `roles`, notice that information related to it will not appears;
1. Request a new `access_token` informing `roles`, notice that information related to it will appears;
1. Request a new `access_token` using from `refresh_token` from the previous request, notice that information related to it will not appears.

### Possible solution

I think it might be good that refresh-token always contains all optional scopes (even those with `Include in access token` is false). This is probably better than using the scope from clientSession as that may not work 100% accurately in case of more browser tabs (that is the limitation of having single authenticatedClientSession per client attached to userSession). See my comment https://github.com/keycloak/keycloak/pull/12860#issuecomment-1184694501

**Comment by mposolda** [comment]
I am adding this with the label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to investigate this further and eventually send PR for this.

**Comment by thomasdarimont** [comment]
@mposolda I think I found the problem. See: https://github.com/keycloak/keycloak/pull/12860

**Comment by mposolda** [comment]
@thomasdarimont Not sure if it works to use the scope from clientSession... Added section `Possible solution` to the description of this issue with more details.
