### ISSUE TITLE
Regression for application list in new account console

### ISSUE THREAD

**Issue by gdelbos** [keycloak/keycloak#12324]
### Describe the bug

In the old account console, when viewing the application list, every application was available and for each application we could view the roles. 

This is not the case in the new account console. To my understanding, the new account console only display the current active session instead of the applications and the available roles.

See the following screenshot:
**Old console:**

> ![image](https://user-images.githubusercontent.com/104490436/171832309-b1f37729-2c03-4cb8-b4c4-b83a9defa4da.png)

**New console:**

> ![image](https://user-images.githubusercontent.com/104490436/171834257-bd5f6bac-68d2-47f0-9ce7-848c1cfd0fc1.png)

### Version

16.1.1

### Expected behavior

Both feature should be identical or at least we should be able to have a similar feature.

### Actual behavior

The new console does only display applications on which I have an active session.

### How to Reproduce?

Initialization: 
- Create a realm "myrealm" 

Old behaviour:
- Set the realm "Account Theme" to "keycloak"
- Open the application page on the account console (ie. https://localhost:8443/auth/realms/myrealm/account/applications)

New behaviour:
- Set the realm "Account Theme" to "keycloak.v2"
- Open the application page on the account console (ie. https://localhost:8443/auth/realms/myrealm/account/#/applications)

**Comment by ssilvert** [comment]
We did change this in a newer version.  If you want an application to always show up in the account console, you need to go to the client and set `Always display in UI`.
