### ISSUE TITLE
Consider adding `jq` to the container image

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#12331]
### Description

When one needs to run commands against keycloak, it is easy to use the existing container image, as it includes the `kc` and `kcadm` commands.

However, working with JSON is tricky, as there is no JSON tooling in the container image.

Adding `jq` would definitely help with that.

### Motivation

Make it easier to work with the command line tooling in a containerized world.

### Details

`jq` is a well know tools and pretty lightweight. It doesn't add much, but brings a lot of value.

**Comment by abstractj** [comment]
@ctron thanks for suggesting this enhancement. It should be possible for developers to extend the Keycloak image and introduce jq.

The reason why we avoid introducing more tools into those images, is related with the size. Thinking about production environments, often `jq` is not even used.

I hope it brings some clarity.

**Comment by ctron** [comment]
> @ctron thanks for suggesting this enhancement. It should be possible for developers to extend the Keycloak image and introduce jq.

Sure it is. However, that means you need to re-build keycloak images yourself, with every update. It would be way nicer to have some "tooling" out of the box.

> The reason why we avoid introducing more tools into those images, is related with the size. Thinking about production environments, often jq is not even used.

The keycloak image currently is `558 MiB`, `jq` has `32 KiB`. I would say the increased size doesn't make a big difference, but provides a real benefit, when working with keycloak.

Besides, it you think that adding a simple tool like `jq` causes some major issues, I would suggest to create a "tools" container, which contains all the necessary tools to work in a reasonable way with keycloak. Including `kc`, `kcadm`, and `jq`. Not adding the server side components might even make the image much smaller.

**Comment by abstractj** [comment]
Thanks for your suggestion @ctron. Unfortunately, we don't have enough bandwidth to maintain more images, but if this is something that you would like, I'd suggest starting a GH discussion about it and perhaps create build a custom image. 

For now, I'm closing this issue, considering that we don't have any plans for doing it, but would love to see the outcome of a GH discussion around this topic.
