### ISSUE TITLE
Unable to set ES256 key for client in Keycloak 18

### ISSUE THREAD

**Issue by carlosli888** [keycloak/keycloak#12342]
### Describe the bug

I am not able to import an ECC public key to use to authenticate confidential clients via the client credentials flow and private_key_jwt method.  

### Version

18

### Expected behavior

I am able to import the public key successfully.  When a client attempts to authenticate using the client credentials flow and private_key_jwt method, it is able to authenticate successfully using the matching ES256 private key.

### Actual behavior

I encountered `Error! An unexpected server error has occurred` when I tried to import a public key PEM file.
When I checked the Keycloak console, I saw...
```
java.lang.RuntimeException: org.keycloak.common.util.PemException: java.security.spec.InvalidKeySpecException: encoded key spec not recognized: algorithm identifier 1.2.840.10045.2.1 in key not recognised
        at org.keycloak.models.utils.KeycloakModelUtils.getPublicKey(KeycloakModelUtils.java:94)
        at org.keycloak.services.resources.admin.ClientAttributeCertificateResource.getCertFromRequest(ClientAttributeCertificateResource.java:200)
        at org.keycloak.services.resources.admin.ClientAttributeCertificateResource.uploadJksCertificate(ClientAttributeCertificateResource.java:167)
        at jdk.internal.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
...
```

When I tried to workaround the issue and have Keycloak generate the PKCS12 file for ES256, the resulting archive shows a RSA certificate instead.
![image](https://user-images.githubusercontent.com/47931389/171962751-e98ad8f6-20de-46e2-a328-dff24a8af321.png)

### How to Reproduce?

1.  I created a private/public ES key pair.
```
openssl ecparam -genkey -name prime256v1 -noout -out .\key-test-client.es256.privatekey.pem
openssl ec -in .\key-test-client.es256.privatekey.pem -pubout -out .\key-test-client.es256.publickey.pem -outform pem
```
2. Logged in to Keycloak (running as a container) using admin account.
3. Created a client called "key-test-client".
4. Enabled services account and disabled other flows (see excerpt from export):
```json
    {
      "id": "40839760-6269-4d12-b876-ba83c6f937be",
      "clientId": "key-test-client",
      "surrogateAuthRequired": false,
      "enabled": true,
      "alwaysDisplayInConsole": false,
      "clientAuthenticatorType": "client-jwt",
      "secret": "**********",
      "redirectUris": [],
      "webOrigins": [],
      "notBefore": 0,
      "bearerOnly": false,
      "consentRequired": false,
      "standardFlowEnabled": false,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": false,
      "serviceAccountsEnabled": true,
      "publicClient": false,
      "frontchannelLogout": false,
      "protocol": "openid-connect",
      "attributes": {
        "saml.force.post.binding": "false",
        "saml.multivalued.roles": "false",
        "token.endpoint.auth.signing.alg": "ES256",
        "frontchannel.logout.session.required": "false",
        "oauth2.device.authorization.grant.enabled": "false",
        "backchannel.logout.revoke.offline.tokens": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "use.refresh.tokens": "true",
        "oidc.ciba.grant.enabled": "false",
        "backchannel.logout.session.required": "true",
        "client_credentials.use_refresh_token": "false",
        "require.pushed.authorization.requests": "false",
        "saml.client.signature": "false",
        "saml.allow.ecp.flow": "false",
        "id.token.as.detached.signature": "false",
        "saml.assertion.signature": "false",
        "client.secret.creation.time": "1654294326",
        "saml.encrypt": "false",
        "saml.server.signature": "false",
        "exclude.session.state.from.auth.response": "false",
        "saml.artifact.binding": "false",
        "saml_force_name_id_format": "false",
        "acr.loa.map": "{}",
        "tls.client.certificate.bound.access.tokens": "false",
        "saml.authnstatement": "false",
        "display.on.consent.screen": "false",
        "token.response.type.bearer.lower-case": "false",
        "saml.onetimeuse.condition": "false"
      }
```
6. Saved the changes.
7. Once credential tab became available, changed the settings to be "Signed Jwt" and selected "ES256" as the signing algorithm.
8. In the Keys tab, selected to import a "Public Key PEM".
9. Selected attached file.
[key-test-client.es256.publickey.pem.txt](https://github.com/keycloak/keycloak/files/8835995/key-test-client.es256.publickey.pem.txt)
10. Click on "Import".

### Anything else?

Keycloak is running on a container.  The container was based on the latest tag of Keycloak.

The following is the version information shown at startup in the console:
![image](https://user-images.githubusercontent.com/47931389/171963054-4e052a6d-741b-442c-8a7b-c833623c0d6b.png)

**Comment by rmartinc** [comment]
This sounds very similar to #9194. Until that bug is fixed in 19 and the new version released you can only set the key using jwks (real url or direct string) and specifying the alg there to ES256 (or the one you want to use). The `ClientPublicKeyLoader` only allows RSA until #9194.

**Comment by carlosli888** [comment]
Hello @rmartinc, 
Thank you for your suggestion.  Unfortunately, I have also tried using JWKS, and that feature was not working, not even for simple RS256.  See https://github.com/keycloak/keycloak/issues/12344

**Comment by tnorimat** [comment]
@carlosli888 Hello,
Is this issue related to https://github.com/keycloak/keycloak/issues/12152 ?
Does this issue happen if you use wildfly based keycloak 18 (legacy)?

**Comment by rmartinc** [comment]
@carlosli888 I have also answered in the https://github.com/keycloak/keycloak/issues/12344 issue. I have uploaded to github a little tool I previously had developed to configure jwks. At least I have checked that keycloak 18 on quarkus can do a client-credentials login OK using signed jwt using ES512.

**Comment by carlosli888** [comment]
I am able to set ES key for clients using Keycloak 18 now by using JWKS (see https://github.com/keycloak/keycloak/issues/12344).  The key is adding the "use" attribute, which is optional in the JWK specs but required for Keycloak.
