### ISSUE TITLE
Align Operator config naming with Quarkus distribution

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#12352]
This is a follow-up from https://github.com/keycloak/keycloak/issues/10738#issuecomment-1142189716.

Change `Config` to be more aligned with Quarkus distribution (e.g. similar to `kc-operator.operand.image`, `kc-operator.operand.image-pull-policy` etc. etc.)

**Comment by shawkins** [comment]
No longer relevant.

**Comment by shawkins** [comment]
Reopening as our operator prefix conflicts with the property prefix used by olm.
