### ISSUE TITLE
KC_HOSTNAME_PATH does not seem to be working

### ISSUE THREAD

**Issue by ddurham2** [keycloak/keycloak#12367]
### Describe the bug

I'm attempting to make v18 have /auth as the prefix path for all traffic into keycloak.  I'm running into trouble, and v17 seems to have the same problem.

And, as I understand it, the context-path setting is only for the realm requests, but not the admin interface.

I've got a kubernetes cluster, with ingress-nginx in front with all traffic beginning with /auth directed to the keycloak workload.

I'm using bitnami's keycloak helm chart v9.2.2 which uses keycloak v18.0.0 and following [these docs](https://www.keycloak.org/server/hostname), I have, I think, managed to configure the KC_HOSTNAME, KC_HOSTNAME_PORT and KC_HOSTNAME_PATH such that keycloak should respond with /auth as the prefix

e.g.
```extraEnvVars:
  ...
  - name: KC_HOSTNAME
    value: "example.com"
  - name: KC_HOSTNAME_PORT
    value: "443"
  - name: KC_HOSTNAME_PATH
    value: "auth"
  ...
```
Confirmed by the following log output from keycloak
>2022-06-07 05:05:24,340 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: example.com, Strict HTTPS: false, **Path: auth**, Strict BackChannel: false, Admin: &lt;request&gt;, Port: 443, Proxied: true

Yet, when I fetch the main page:
```curl https://example.com/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=rnusb```
It returns
```{"error":"RESTEASY003210: Could not find resource for full path: https://example.com/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=rnusb"}```

And wireshark (from the keycloak pod) shows the following:
```
GET /auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=rnusb HTTP/1.1
Host: example.com
X-Request-ID: c27e6d84b4016e273c8933d2dbc2ff3f
X-Real-IP: 104.131.37.82
X-Forwarded-For: 104.131.37.82
X-Forwarded-Host: example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Scheme: https
user-agent: curl/7.68.0
accept: */*

HTTP/1.1 404 Not Found
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Type: application/json
content-length: 170

{"error":"RESTEASY003210: Could not find resource for full path: https://example.com/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=rnusb"}
```

I've also tried with KC_PROXY of "edge" and "passthrough" and neither seems to make a difference

I wouldn't be able to upgrade from v16 (where /auth was the default) to anything newer without being able to successfully configure a path which distinguishes kc traffic from other service's traffic.

### Version

18.0.0 and 17.x

### Expected behavior

Respond to requests on the configured context-path

### Actual behavior

Receiving 404

### How to Reproduce?

Described above

**Comment by ddurham2** [comment]
I've now come to believe that the KC_HOSTNAME_PATH does not change the URL on which it responds to API requests, but rather only affects the where any returned HTML will request css, js, images, etc.
So it's up to the load-balancer to accept it on /auth, and trim that off before forwarding the request.

That is not at all evident from the docs e.g. https://www.keycloak.org/server/hostname#_overriding_the_hostname_path

**Comment by vmuzikar** [comment]
@ddurham2 Thank you for reporting this! I believe it is already tracked in #12506. I'm going to close this one, feel free to reopen if you think otherwise. See also #11922 as I believe it might help solving your issue.

**Comment by LakshmiPhani7680** [comment]
Hi @vmuzikar ,
Can you please let me know how to add HTTP Response headers for this path: /auth/realms/master/protocol/openid-connect/3p-cookies/step1.html, using keycloak 21 version. Please respond ASAP. Thank you.
