### ISSUE TITLE
Provide a Galleon feature pack to install the Keycloak Elytron SAML adapter

### ISSUE THREAD

**Issue by fjuma** [keycloak/keycloak#12363]
### Description

A new Gallon feature pack should be added that contains a single layer, `keycloak-client-saml`.

This relates to [WFLY-16306](https://issues.redhat.com/browse/WFLY-16306).

I will work on this.

### Motivation

This will make it easier to secure applications deployed to WildFly with SAML without needing to manually install the Keycloak Elytron SAML adapter using the zip file. 

### Details

A similar feature pack to install the Keycloak Elytron OIDC adapter was added a little while ago before WildFly
added native support for OpenID Connect (see [WFLY-13706](https://issues.jboss.org/browse/WFLY-13706) / [KEYCLOAK-14953](https://issues.jboss.org/browse/KEYCLOAK-14953)).

For more details, see https://github.com/wildfly/wildfly-proposals/pull/486.

**Comment by pskopek** [comment]
@fjuma this PR can be closed. See https://github.com/keycloak/keycloak/pull/19710
