### ISSUE TITLE
Admin console never loads

### ISSUE THREAD

**Issue by ethindp** [keycloak/keycloak#12365]
### Describe the bug

I've just deployed keycloak and set it up behind my reverse proxy. However, the admin console refuses to load, just getting stuck saying "Loading...".

### Version

18.0.0

### Expected behavior

The admin console should load fine

### Actual behavior

The console remains stuck on "Loading...".

### How to Reproduce?

These may not work for anyone else, but:

1. Deploy keycloak
2. For your nginx config, add the following for location "/":

```nginx
    proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address 
    proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
    proxy_set_header Host $host; # to forward the original host requested by the client
proxy_hide_header X-Content-Type-Options;
add_header X-Content-Type-Options "" always;
# Pass other proxy headers and pass as normal
```

(I removed the `X-Content-Type-Options` header due to [this bug](https://issues.redhat.com/browse/KEYCLOAK-17076), and I don't know if that's fixed.)
3. Try logging into the admin console.

### Anything else?

My full nginx configuration is quite lengthy, but if you guys want me to upload that here I can do that.

**Comment by pleic** [comment]
I was facing a similar issue, using the new Quarkus based operator. How are you deploying Keycloak ?

**Comment by ethindp** [comment]
@pleic I'm just manually deploying it via `kc.sh`, not through Keycloak Operator/Kubernetes.

**Comment by pleic** [comment]
@ethindp Okay, I discovered now that in my case it was just wrong value for the [proxy mode](https://www.keycloak.org/server/reverseproxy), but I am not quite sure if that will help you

**Comment by pleic** [comment]
@ethindp I just set it to passthrough since in my case Keycloak handles the encryption, but it also should handle http and https connections, so could be worth a try

**Comment by pedroigor** [comment]
@ethindp Could you please provide the options you are using to start the server? Or did you manage to get it working?

**Comment by pckhoi** [comment]
I am having the same problem running `kc.sh start --proxy=edge --http-enabled=true`. It works well when I replace `start` with `start-dev` though, so I think this is a bug where Keycloak doesn't work fully with HTTP traffic even in edge proxy mode. This is how I find out:

1. **When visiting the admin console, the page is stuck at `Loading the admin console` forever**

<img width="590" alt="Screen Shot 2022-08-07 at 18 05 25" src="https://user-images.githubusercontent.com/370820/183287664-263c92f6-03ee-44e0-9ef8-368c612f3066.png">

There is one single failed request, it appears to try to load the path `/realms/master/protocol/openid-connect/3p-cookies/step1.html` with HTTPS scheme, which of course doesn't work.

If one somehow manage to reach the login page at `/realms/master/protocol/openid-connect/auth` path, the page loads fine. However...

2. **after logging-in, the page redirect to `/realms/master/login-actions/authenticate` under HTTPS scheme**

I think this is one or multiple bugs, not completely sure though. Happy to open a separate bug issue.

**Comment by pckhoi** [comment]
Just out of curiosity, what was the scheme you were using? I think Keycloak only work under HTTPS scheme if you run `kc.sh start`.

**Comment by tacerus** [comment]
I encounter the same issue with Keycloak 19.0.1 with **no** reverse proxy between my browser and Keycloak.

![image](https://user-images.githubusercontent.com/5121046/183292933-f30cba26-420c-4d83-8782-e14e1ccf310c.png)

My issue was the `hostname=` field in `keycloak.conf` was not set to the same address I used to access the built-in webserver.

Is this expected behavior? If for some reason the `hostname=` field does need to match (albeit me seeing use cases where one wants to access the server from different hostnames), should the program not inform the user about this, instead of showing a spinning circle? :-)

**Comment by ethindp** [comment]
@pedroigor Sorry I didn't respond to this promptly... I got majorly sidetracked. I'm just starting the server normally in production mode. My proxy setting is set to `passthrough`.

**Comment by pckhoi** [comment]
@tacerus don't quote me on this but I think it's a security feature. Same with requiring HTTPS on production, some security features would be compromised if the host name wasn't locked down.

**Comment by ethindp** [comment]
@pedroigor Can you clarify what you mean? Do you want my keycloak.conf file?

**Comment by ethindp** [comment]
@pedroigor

> When you set a proxy the server also makes an assumption that the server URLs should created using standard ports like 443 and 80. If that is not the case, you should be able to set the hostname-port option to match the port you are using to expose the server in your reverse proxy.

I have the proxy listening on ports 80 and 443. The actual Keycloak instance listens on an internal port that my reverse proxy connects to. I've changed only the `http-port` and `https-port` options... Should I also set the `hostname-port` option to `https-port`?

**Comment by pedroigor** [comment]
Yes, your `keycloak.conf` (if it is the source of configuration) should help.

You don't need to set `hostname-port` if you are exposing the server through your proxy using the default ports.

**Comment by ethindp** [comment]
@pedroigor I mean, my config is pretty standard:

```
db=postgres
db-username=<omitted for security>
db-password=<omitted for security>
db-url=jdbc:postgresql://localhost/kcdb
health-enabled=true
metrics-enabled=true
https-certificate-file=${kc.home.dir}conf/server.crt
https-certificate-key-file=${kc.home.dir}conf/server.key
proxy=passthrough
hostname=iam.the-gdn.net
https-port=9001
http-port=9000
http-enabled=true
http-host=0.0.0.0
log=file
```

**Comment by pedroigor** [comment]
@ethindp Thanks. Are you accessing the server using a URL using `iam.the-gdn.net` as the host?

**Comment by pedroigor** [comment]
Please, let me know if the issue is still happening.

Based on the config you provided, you should be able to access the administration console using `https://iam.the-gdn.net/admin`. But if you trying to access the administration console using another URL, I would suggest you to also set the `hostname-admin` option to set the hostname you want the administration console exposed to.

**Comment by ethindp** [comment]
@pedroigor Its still happening for me. I'm not sure why at all, and I'm not sure what to do to resolve the problem. There are no log entries whatsoever that I can find.

**Comment by ethindp** [comment]
> @ethindp Thanks. Are you accessing the server using a URL using iam.the-gdn.net as the host?

Yes.

**Comment by pedroigor** [comment]
@ethindp Thanks. If you can provide the source code for the loading page, we should be able to check for unexpected URLs being used to reach out the server.

Other than that, it should work fine ...

What proxy are you using?

**Comment by ethindp** [comment]
@pedroigor Doesn't appear to be anything unexpected, the code is below, though. What's odd though is this particular snippet:

```html
<div class="feedback-aligner" data-ng-show="notification.display">
    <div class="alert alert-{{notification.type}} alert-dismissable">
        <button type="button" class="close" data-ng-click="notification.remove()" id="notification-close">
            <span class="pficon pficon-close"/>
        </button>

        <span class="pficon pficon-ok" ng-show="notification.type == 'success'"></span>
        <span class="pficon pficon-info" ng-show="notification.type == 'info'"></span>
        <span class="pficon pficon-warning-triangle-o" ng-show="notification.type == 'warning'"></span>
        <span class="pficon pficon-error-circle-o" ng-show="notification.type == 'danger'"></span>
        <strong>{{notification.header}}</strong> {{notification.message}}
    </div>
</div>
```

That's that unknown notification that's showing. If it displayed properly, perhaps it would provide an idea as to what's happening, but it isn't for some reason.

The full code is:

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="/resources/na3pi/admin/keycloak/img/favicon.ico">
    <link href="/resources/na3pi/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css" rel="stylesheet" />
    <link href="/resources/na3pi/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css" rel="stylesheet" />
    <link href="/resources/na3pi/common/keycloak/node_modules/select2/select2.css" rel="stylesheet" />
    <link href="/resources/na3pi/common/keycloak/lib/angular/treeview/css/angular.treeview.css" rel="stylesheet" />
    <link href="/resources/na3pi/common/keycloak/node_modules/text-security/text-security.css" rel="stylesheet" />
    <link href="/resources/na3pi/admin/keycloak/css/styles.css" rel="stylesheet" />

    <script type="text/javascript">
        var authServerUrl = 'https://iam.the-gdn.net';
        var authUrl = 'https://iam.the-gdn.net';
        var consoleBaseUrl = '/admin/master/console/';
        var resourceUrl = '/resources/na3pi/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'na3pi';
    </script>

    <!-- Minimized versions (for those that have one) -->
    <script src="/resources/na3pi/common/keycloak/node_modules/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/select2/select2.js" type="text/javascript"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular/angular.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-resource/angular-resource.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-route/angular-route.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-cookies/angular-cookies.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-translate/dist/angular-translate.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-translate-loader-url/angular-translate-loader-url.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/angular-ui-select2/src/select2.js" type="text/javascript"></script>
    <script src="/resources/na3pi/common/keycloak/node_modules/autofill-event/autofill-event.js"></script>

    <!-- Libraries not managed by yarn -->
    <script src="/resources/na3pi/common/keycloak/lib/angular/ui-bootstrap-tpls-0.11.0.js"></script>
    <script src="/resources/na3pi/common/keycloak/lib/angular/treeview/angular.treeview.js"></script>
    <script src="/resources/na3pi/common/keycloak/lib/fileupload/angular-file-upload.min.js"></script>
    <script src="/resources/na3pi/common/keycloak/lib/filesaver/FileSaver.js"></script>

    <script src="/js/keycloak.js?version=na3pi" type="text/javascript"></script>

    <script src="/resources/na3pi/admin/keycloak/js/app.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/controllers/realm.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/controllers/clients.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/controllers/users.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/controllers/groups.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/controllers/roles.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/loaders.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/services.js" type="text/javascript"></script>

    <!-- Authorization -->
    <script src="/resources/na3pi/admin/keycloak/js/authz/authz-app.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/authz/authz-controller.js" type="text/javascript"></script>
    <script src="/resources/na3pi/admin/keycloak/js/authz/authz-services.js" type="text/javascript"></script>

</head>
<body data-ng-controller="GlobalCtrl" data-ng-cloak data-ng-show="auth.user">

<nav class="navbar navbar-default navbar-pf" role="navigation" data-ng-include data-src="resourceUrl + '/partials/menu.html'">
</nav>

<div class="container-fluid">
<div class="row">
    <div data-ng-view id="view"></div>
</div>
</div>

<div class="feedback-aligner" data-ng-show="notification.display">
    <div class="alert alert-{{notification.type}} alert-dismissable">
        <button type="button" class="close" data-ng-click="notification.remove()" id="notification-close">
            <span class="pficon pficon-close"/>
        </button>

        <span class="pficon pficon-ok" ng-show="notification.type == 'success'"></span>
        <span class="pficon pficon-info" ng-show="notification.type == 'info'"></span>
        <span class="pficon pficon-warning-triangle-o" ng-show="notification.type == 'warning'"></span>
        <span class="pficon pficon-error-circle-o" ng-show="notification.type == 'danger'"></span>
        <strong>{{notification.header}}</strong> {{notification.message}}
    </div>
</div>

<div id="loading" class="loading">Loading...</div>

</body>
</html>
```

**Comment by aruehl** [comment]
Some behavior on my side. The console never stops loading. The browser communicates directly with the keycloak docker container (no proxy).

My keycloak.conf 
```
db-url=jdbc:postgresql://kc-db/keycloak
db-username=keycloak
# db-password=<using ENV>

hostname=idp.knusel.me
hostname-port=443
hostname-path=/auth
```
I'm requesting the console over https://idp.knusel.me/auth/admin/master/console/

Here is the source of the console page
```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><link id="favicon" rel="icon" href="/auth/resources/delki/admin/keycloak.v2/favicon.ico"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Web site to manage keycloak"><title>Keycloak Administration Console</title><style>.container,
    .container-fluid,
    #load-container {
      padding: 0;
      margin: 0;
    }

    .container,
    .container-fluid,
    #load-container {
      width: 100vw;
    }

    .keycloak__loading-container {
      height: 100vh;
      width: 100%;
      background-color: #f0f0f0;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      margin: 0;
    }

    #loading-text {
      z-index: 1000;
      font-size: 20px;
      font-weight: 600;
      padding-top: 32px;
    }</style><link rel="stylesheet" href="/auth/resources/delki/admin/keycloak.v2/styles.1653b4622917b89da7e4.css"></head>

<body style="height: 100%;">
  <script id="environment" type="application/json">
    {
      "loginRealm": "master",
      "authServerUrl": "https://idp.knusel.me:443/auth",
      "authUrl": "https://idp.knusel.me/auth",
      "consoleBaseUrl": "/auth/admin/master/console/",
      "resourceUrl": "/auth/resources/delki/admin/keycloak.v2",
      "masterRealm": "master",
      "resourceVersion": "delki",
      "commitHash": "04237c0eb32bf838e866b879b3637d1eca326151",
      "isRunningAsTheme": true
    }
  </script>

<div id="app" style="height: 100%"><div class="container container-fluid" id="load-container"><div class="keycloak__loading-container"><span class="pf-c-spinner pf-m-xl" role="progressbar" aria-valuetext="Loading..."><span class="pf-c-spinner__clipper"></span> <span class="pf-c-spinner__lead-ball"></span> <span class="pf-c-spinner__tail-ball"></span></span><div><p id="loading-text">Loading the admin console</p></div></div></div></div><noscript>You need to enable JavaScript to run this app.</noscript><script src="/auth/resources/delki/admin/keycloak.v2/webpack-runtime.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/lib-index-916de6ed.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/lib-EmptyState-25333d4a.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/lib-react-core.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/4359.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/index.js"></script></body></html>
```
All resources and subpages are responded with http status 200 or 204. So everything seems to be adressed correct.

**Comment by carlosli888** [comment]
Although this ticket is closed, I thought I shared some of my findings in case it helps people.

I also encountered this issue while running Keycloak v19.0.1 in a container.  After considerable troubleshooting, I finally fixed it and got the login prompt to show by doing three things:
* The Keycloak HTTPS port must match the one used by the host  (e.g., `docker run -p 8443:8443 ...` or `docker run -p:443:443` ...)
* I moved KC_HTTPS_PORT to be after KC_HOSTNAME in my list of environment variables (i.e., order matters)
* I made sure that my KC_HOSTNAME value was lower-case (i.e., hostname is case-sensitive)

### Details:
My dockerfile: 
```dockerfile
FROM quay.io/keycloak/keycloak:19.0.1
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build
ENV KC_LOG_CONSOLE_OUTPUT=json
ENV KC_DB_URL_DATABASE=keycloak
ENV KC_DB_URL_HOST=postgres
ENV KC_DB_USERNAME=<DBUSERNAME>
ENV KC_DB_PASSWORD=<DBPASSWORD>
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start"]
```
*Part* of my compose file:
```yaml
services:
  keycloak:
    build: 
      context: ./src/keycloak
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KC_DB_URL_HOST=postgres
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HTTPS_CERTIFICATE_FILE=/run/secrets/host.cer
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/run/secrets/host.insecure.key
      - KC_HOSTNAME=${AUTHN_HOSTNAME:-authn}.${DOMAIN}
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HTTPS_PORT=443           ## IMPORTANT: this must be after KC_HOSTNAME settings for admin portal to show
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    secrets:
      - host.cer
      - host.insecure.key
    depends_on:
      - postgres

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432  # other apps would want to connect to Postgres via default port, not proxy
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-storage: 
```
> Note: the full compose file includes a reverse-proxy.  However, I was able to discover the issues described above by using `docker run`.

**Comment by ethindp** [comment]
@carlosli888 I'm not using a docker container, though. Using keycloak 18.0.0 still, unsure how to upgrade.

**Comment by aruehl** [comment]
@carlosli888 
>  The Keycloak HTTPS port must match the one used by the host (e.g., docker run -p 8443:8443 ... or docker run -p:443:443 ...)

I have already tried this, but because of the need to expose on port 443, I have set https_port to 443. With this setting quarkus failed to start, because of using a low port (<= 1024).
```ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.net.SocketException: Permission denied```

**Comment by carlosli888** [comment]
@ethindp,
I wonder if this page would help: https://www.keycloak.org/docs/latest/upgrading/index.html.  Unfortunately, I am not that familiar with Keycloak.  I more or less started with Keycloak 18 then moved to 19, both times using containers.  Given that I was just starting, I was able to easily throw away data from Keycloak 18 and start from scratch for v19.

**Comment by carlosli888** [comment]
@aruehl,
My observations have been through docker, which in my environment has been running as root.  I wonder if that is why I have not seen the same errors.
Please also note that I have given up trying to proxy through a path prefix.  I find that it works fine for the public and confidential clients, but not the admin page.  The admin page gets redirected to "https://<server>.<domain>/admin, even though I set KC_HOSTNAME_PATH.  I decided it was easier to get another domain name and map it to the same server.

**Comment by ethindp** [comment]
I can't use a low port like 443 for the HTTPS port because I'm reverse-proxying it. If it indeed is rerouting connections to `https://./admin`, that needs to be undone somehow, because it shouldn't assume that the admin console is only accessible via localhost. I mean, I haven't even gotten the setup wizard process/created my admin user, because the admin console refuses to load and gets stuck at 50 percent. I'm definitely getting irritated; the documentation never indicated that this kind of behavior was expected, or that it would even happen. I've upgraded to Keycloak 19, though most of the process I could skip (e.g. upgrading themes/providers) because I haven't touched those. I just want this to work. Sigh.

**Comment by pedroigor** [comment]
@ethindp I understand your frustration and we have been working on several issues around the hostname during this time. One of our last changes to bring the same behavior as legacy (Wildfly) is this PR https://github.com/keycloak/keycloak/pull/13681. Basically, allow you to set both frontend and admin URLs directly.

However, I think we are missing something here to make it work with the latest release. Thanks for sending this snippet:

```
<script type="text/javascript">
        var authServerUrl = 'https://iam.the-gdn.net';
        var authUrl = 'https://iam.the-gdn.net';
        var consoleBaseUrl = '/admin/master/console/';
        var resourceUrl = '/resources/na3pi/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'na3pi';
    </script>
```

For me, it looks correct so that requests from the browser are going through the `https://iam.the-gdn.net`. So I would expect all the static resources being loaded from the server.

The next question from me is if you can spot, by looking at the network activity in the browser, which requests are failing.

**Comment by ethindp** [comment]
@pedroigor From what I can tell, here's the chain of events:

1. When I click "Administration Console", I get a 302, because the link is `/admin/` but is redirected to the actual admin console.
2. The HTTP status 200 is received and that initial page is loaded.
3. All other requests the system makes get 404s.

The HAR is available [here](https://pastebin.com/Bx3Zmsht). It may lend insight that I have not been able to see. Perhaps there is a configuration setting I am missing, or I didn't set up my reverse proxy correctly. I do not believe the HAR contains any sensitive information, since I didn't log into anything nor did I send any authentication headers or anything like that.

**Comment by pedroigor** [comment]
The pastebin was removed after trying to access it again :)

But at first glance, the requests failing with `404` looks OK. Perhaps we can check how it will behave if you disable the new admin console and try to load the old console instead. You should be able to change the admin theme in your realm settings or use `--features-disabled=admin2`.

**Comment by ethindp** [comment]
@pedroigor Yeah, I turned on "burn on first read". Oops? :)

I just started it using the old admin console. Still no load, but [here's the resulting HAR](https://pastebin.com/h7ZEs1Dx). Its considerably larger, and I think there isn't anything sensitive in it, but still, you definitely might want to import this into Brave/Chromium/FF.

**Comment by pedroigor** [comment]
@ethindp Thanks. Take this request as an example:

```
"request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://mykeycloak/resources/8k4f2/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "mykeycloak"
            },
            ...
}

And compare it with yours:

```
"request": {
          "method": "GET",
          "url": "https://iam.the-gdn.net/resources/bh975/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css",
          "httpVersion": "http/2.0",
          "headers": [
            {
              "name": ":authority",
              "value": "iam.the-gdn.net"
            },
            {
              "name": ":method",
              "value": "GET"
            },
            {
              "name": ":path",
              "value": "/resources/bh975/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css"
            },
            {
              "name": ":scheme",
              "value": "https"
            },
            ...
}
```

Despite the host and the resource version in the path, they are pretty much the same. It does not make much sense the `404` you are getting.

Can you make sure the `404` is from the server itself and not from your proxy? 

I usually run proxy tests locally using HAProxy but I also have the configuration for NGINX and Apache. They all work fine.

**Comment by ethindp** [comment]
@pedroigor I can confirm that this is not the fault of the proxy but is most likely from keycloak. No log is printed for the 404s in the logs though; presumably, the logger does not consider this an error condition. If I set the log level to `DEBUG` I get too much output to be useful, and I can't seem to figure out the log categories for the HTTP stuff in particular. So I'm guessing that its most likely keycloaks fault, not my proxys.

**Comment by pedroigor** [comment]
@ethindp You mentioned the docker-compose example is only part of your configuration. Would you be able to provide me a full reproducer using docker?

**Comment by ethindp** [comment]
@pedroigor I don't use the docker configuration. I've deployed this without docker, and I'm unsure how I'd go about reproducing it within Docker.

**Comment by miguel-rn** [comment]
Sorry to revive an old thread but if anyone else is having similar issue while using a reverse proxy, I'll share my solution. To fix I set `hostname-url` and `hostname-admin-url` to equal values in the keycloak.conf for Quarkus (e.g. `hostname-url=https://sso.example.com`  `hostname-admin-url=https://sso.example.com`).

**Comment by yahyaguzide** [comment]
> Sorry to revive an old thread but if anyone else is having similar issue while using a reverse proxy, I'll share my solution. To fix I set `hostname-url` and `hostname-admin-url` to equal values in the keycloak.conf for Quarkus (e.g. `hostname-url=https://sso.example.com` `hostname-admin-url=https://sso.example.com`).

This worked for me thank you @miguel-rn 😄

**Comment by HendrikHuebner** [comment]
I'm having the same issue. Today, without me changing anything suddenly the admin UI isnt loading any more. It just worked yesterday and I'm 100% sure I didnt change anything about the env file or my docker file... Really strange. None of these solutions have worked so far.
