### ISSUE TITLE
Remove "You are already logged-in" during authentication

### ISSUE THREAD

**Issue by acolombier** [keycloak/keycloak#12406]
### Description

*This request is a long time request, which can be found on [Jira](https://issues.redhat.com/browse/KEYCLOAK-5179?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true)*

## Expected behavior

```
Given a logged user 
When they get prompted to login
Or follow a validation link (e.g email)
Then their authentication flow complete successfully back into the app, with the request login data
```

## Current behavior

```
Given a logged user 
When they get prompted to login
Or follow a validation link (e.g email)
Then they see an error-like page telling them they are already logged in 
And a cancel-like button to get back to the application, if there is a base URL set
```

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-5179?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

### Motivation

The current logic currently gives a poor user experience and doesn't bring any value as such - since the user is already authenticated anyway, there is no fundamental issue to complete their authentication flow.

### Details

Worth to mention that this has been a requested feature for almost 5 years, perhaps it would be nice to provide a temporary workaround (someone in the documentation mentioned they've managed to achieve a hack, but sadly haven't shared much) or provide a vision and design on how to start implementing this solution (there was a suggested approach, but it appears that it wasn't well received by the community)

**Comment by eldarj** [comment]
Any updates on this? 
@lexcao until a proper fix, PR, etc. is created, can this be implemented as an extension?

**Comment by lexcao** [comment]
Still waiting for Keycloak team to check.
I am sorry that it is not recommended to be implemented as an extension for the changes need to be in `SessionCodeChecks` which is from  `org-keycloak-keycloak-services` module.

**Comment by eldarj** [comment]
@lexcao thanks, let's see what the Keycloak team has to say. 

Regarding your proposal, here are my two cents - The adjustments proposed above would possibly cause the user to end up in a loop. Imo, the _**Already logged in page**_ is the expected behavior, as I can't think of a reason when this would not be appropriate to show.

If the user is logged in but lands on the login page again for whatever reason, the best thing is to show this page. **_Why_**  this happens needs more troubleshooting, and it depends on the specific use case.

Redirecting back to the `redirect_uri` and defaulting to `base_url` would be nice to have as a configurable option. Additionally besides this, when this occurs, it would be nice to have a `auto_force_logout` as well as an option.

This way we can choose how to handle this, we show the _**Already logged in page**_ by default, but you can enable one of the above options if it fits your use case.

And yes, obviously improve this page to provide better UX. I suggest providing a more sophisticated UI, with two buttons - one for navigating to the app, and one to navigate to login (logout the user and allow new login)

Definitely, this needs to be worked on in any case. This is something that was being asked to improve for years now.

**Comment by eldarj** [comment]
Five cents, what I did is the following

_Whenever a user ends up on the login page, check for existing cookies and if present remove them._

This can be done within a custom login authenticator SPI, and it solved all the _"You are already logged in."_ issues for me.

**Comment by souravs17031999** [comment]
@lexcao @eldarj is there any update on this from Keycloak team to be fixed/enhanced in future ?

Currently, baseUrl also seems fine to me which can be shown on the page, but I also checked info.tpl which can be overriden and redirected directly to baseUrl , will that help or open any loophole ?

**Comment by mposolda** [comment]
No immediate update unfortunately... 
@souravs17031999 Just a note that automatic redirect to "baseUrl" have some negative side-effects:

- the issue, which we recently talked about in the other thread. In other words, when user already finished login in tab1 and then he went to tab2 and he fills incorrect username/password, he will be automatically authenticated (due the fact that he was automatically redirected from "You are already logged-in" info page to the "BaseUrl", which in next turn automatically authenticated him due the SSO)

- For some clients, "baseUrl" points to the public page. In this case, after filling username/password in tab2, user will be redirected to the "baseUrl", but he won't be authenticated here. This is very confusing from the UXD perspective IMO.

**Comment by bocekm** [comment]
When I have multiple Jira tickets opened in a browser and the tabs are re-loaded without me being logged in I'm asked to log in in all the tabs. After logging in in one tab I get redirected to the Jira ticket. But all the other Jira tabs then tell me that "you are already logged in" and no redirection follows! With that I'm literally losing all the other Jira ticket tabs - I have no way to get to the original Jira ticket URLs anymore.

Why does the redirect happen only for the one tab but not for the others? This is a very annoying bug. Especially when I have the Jira tickets open as a reminder to update them or comment on them.

Thousands of redhatters have recently moved from Bugzilla to Jira. I've asked my colleagues and they are losing their opened Jira tabs the same way.

![Screenshot from 2023-08-07 13-52-57](https://github.com/keycloak/keycloak/assets/9884110/4e878d6a-7ef5-42b1-afbc-695dd0bd4a22)
![Screenshot from 2023-08-07 13-54-02](https://github.com/keycloak/keycloak/assets/9884110/d5109679-f74a-469b-84fd-5201aa83e3cd)

**Comment by netchild** [comment]
Best of both worlds: make it configurable.  If the admin decides to accept an auto-redirect,do the redirect. If the switch is on "You are laready logged in - message", provide the message instead.

Additional suggestion: provide the redirect link in the error message.

**Comment by mposolda** [comment]
Issue is fixed in latest Keycloak main and will be fixed in Keycloak 23. See https://github.com/keycloak/keycloak/pull/23517 description of what was done.

There are some follow-up issues addressed https://github.com/keycloak/keycloak/issues/23879
