### ISSUE TITLE
Review if BouncyCastle FIPS can be included in the distribution

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12417]

**Comment by mposolda** [comment]
This was already done. BCFIPS cannot be included in the distribution and people will need to add it to the distribution. This is same approach used by EAP as well https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/how_to_configure_server_security/index#configure_ssl_fips_bouncycastle
