### ISSUE TITLE
Add config option for switching between regular and FIPS mode

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12418]
On RHEL and Fedora hosts when FIPS is enabled Keycloak should automatically use FIPS compliance, on other hosts it should be possible to explicitly enable FIPS compliance with a config option.

It should be available to KC providers if it is running in regular or FIPS mode.

We may want to add the option for "FIPS 140-2" rather than just "FIPS" to make room for enabling "FIPS 140-3" later.

If we keep BouncyCastle should we then have an option to run FIPS in approved and non-approved mode. See https://www.bouncycastle.org/fips/BCFipsDescription.pdf for more details. I think there is some BC non-FIPS jars, some FIPS jars, and some BC jars that can be used with either, needs to be reviewed.

Initial discussion:
https://github.com/keycloak/keycloak/discussions/12250

**Comment by mposolda** [comment]
Update:
Current Keycloak main already has the option `--fips-mode`.Possible values are:
- `disabled` : Default value. Keycloak uses `keycloak-crypto-default` with BC libraries (FIPS disabled)
- `enabled` : Keycloak uses `keycloak-crypto-fips1402` with BCFIPS non-approved mode
- `strict`: Same like `enabled`, but with BCFIPS approved mode
The option is not yet officially supported (it is not documented in startup options when running something like `./kc.sh help`

Remaining items for this task are:
- Should we keep the option name (and values), or should we add something to be able to differentiate between "Fips 140-2" and "Fips 140-3"? For example something like `enabled-140-2` and `strict-140-2`?
- Should the option be officially supported and available at startup options? Or should we have `FIPS-140-2` preview feature and have this option available just when the feature explicitly enabled?
- Should we have some auto-detection available? For example enable FIPS by default when running on RHEL 8.6 host with FIPS enabled? Not sure about this as it is hard to reliably detect and also hard to consider if to use `enabled` or `strict` mode (To be discussed...)

**Comment by pedroigor** [comment]
IMO, we could close this one because I remember we decided:

* Right now we are `FIPS-140-2` and we are going to support it initially. Based on what we discussed, BC also does not provide yet a GA release for `FIPS-140-3`. In order to support additional levels we can discuss adding a new option or just using `fips=140-2|3`. The `fips-mode` option is only about disabling completely or enabling/disabling approved mode, right?
* The options should be supported if our FIPS support is feature complete.
* IMO, it is nice to have and we can always improve this in the future. I personally prefer to have FIPS explicitly enabled by the user.

**Comment by mposolda** [comment]
@pedroigor +1 in having the option and config values in it's current format. However one remaining thing is to make this option "officially visible". Right now, it is some kind of "experimental" option, which is not shown for example when you call `./kc.sh --help` etc.

So I see the remaining task might be to have this option "officially advertised" and supported. Feel free to assign to you and send PR for this.

However I would wait with merging it until we have also the other things. IMO it won't be very great to release Keycloak 21 with this option "officially advertised", but without official FIPS documentation.

**Comment by pedroigor** [comment]
@mposolda Thanks. 

FTR, the config option to `switch between regular and FIPS mode" is implemented. The next step is to make it supported once we finish FIPS work.

**Comment by mposolda** [comment]
@pedroigor yes, exactly. So I prefer to leave this open just for "make the option supported". You can already send PR for this if you want, and we can mark it "Hold on" and not merging it until other things completed. Or we can just wait with this to later... whatever you prefer.

**Comment by mposolda** [comment]
We will make FIPS 140-2 as preview feature in Keycloak 21. So we need to make sure that this switch is addressed *after* 21 release (once we want to have FIPS 140-2 feature to be officially announced).

**Comment by mposolda** [comment]
Closing this as there is other follow-up task for promote FIPS from "preview" to "fully supported" https://github.com/keycloak/keycloak/issues/17234 . This involves this one and additional work.
