### ISSUE TITLE
keycloak-js: keycloak.init({ onLoad: 'check-sso' }) fails with #error=login_required in the url

### ISSUE THREAD

**Issue by danielmoessner** [keycloak/keycloak#12410]
### Describe the bug

Let's say a user is on a page in my Vue3 App and wants to login in. 

He presses a button and `keycloak.login()` is called.

This works fine if the url is like this: www.example.com/start/
However this does not work if the url is like this: www.example.com/start/#error=login_required

Btw the url is only changed by keycloak-js if `{ onLoad: 'check-sso' }` is set. Changed meaning #error and #state stuff is added.

Not working means that the catch block of the following code is hit after the user filled out the login form. The error looks like this: `{error: 'login_required', error_description: undefined}`

```js
keycloak
  .init({ onLoad: "check-sso" })
  .then(async (auth) => {
    if (auth) {
      store.dispatch("login", keycloak);
    } else {
      store.dispatch("logout");
    }
    store.dispatch("setLoaded");
  })
  .then(() => {
    app.use(router);

    app.mount("#app");
  })
  .catch((error) => {
    console.error("Keyclok init failed.", error); // this is where we end up with #error=login_required in the url and calling keycloak.login()

    alert("Login Error.");
  });

```

### Version

keycloak-js 17.0.1

### Expected behavior

Maybe I'm doing something wrong or I've got a mistake in my head, but it seems to me that the init function should always complete successfully.

### Actual behavior

The init method fails.

### How to Reproduce?

It's kinda difficult for me to provide an example, because I don't have keycloak running locally. But this problem should occur on every keycloak-js version 17.0.1. As a side note this problem occurs always in Safari and in Chrome. But in chrome it does not occur under usual circumstances as #error=login_required is not added to the url.

**Comment by mariuszbeltowski** [comment]
@danielmoessner did you manage to fix it?

**Comment by danielmoessner** [comment]
Actually not. Tried a lot of stuff, but the error is still producable.

**Comment by joelsonrochamk** [comment]
I have the same error here.

**Comment by shaikshoaib92** [comment]
When I am using onLoad:"login-required" .then is not working.

**Comment by birenjack** [comment]
I have same problem

**Comment by birenjack** [comment]
> ### Describe the bug
> Let's say a user is on a page in my Vue3 App and wants to login in.
> 
> He presses a button and `keycloak.login()` is called.
> 
> This works fine if the url is like this: [www.example.com/start/](http://www.example.com/start/) However this does not work if the url is like this: [www.example.com/start/#error=login_required](http://www.example.com/start/#error=login_required)
> 
> Btw the url is only changed by keycloak-js if `{ onLoad: 'check-sso' }` is set. Changed meaning #error and #state stuff is added.
> 
> Not working means that the catch block of the following code is hit after the user filled out the login form. The error looks like this: `{error: 'login_required', error_description: undefined}`
> 
> ```
> keycloak.init({ onLoad: "check-sso" }).then(async (auth) => {
>     if (auth) {
>       store.dispatch("login", keycloak);
>     } else {
>       store.dispatch("logout");
>     }
>     store.dispatch("setLoaded");
>   }).then(() => {
>     app.use(router);
> 
>     app.mount("#app");
>   })
>   .catch((error) => {
>     console.error("Keyclok init failed.", error);  <-- this is where we end up with #error=login_required in the url and calling keycloak.login()
> 
>     alert("Login Error.");
>   });
> ```
> 
> ### Version
> keycloak-js 17.0.1
> 
> ### Expected behavior
> Maybe I'm doing something wrong or I've got a mistake in my head, but it seems to me that the init function should always complete successfully.
> 
> ### Actual behavior
> The init method fails.
> 
> ### How to Reproduce?
> It's kinda difficult for me to provide an example, because I don't have keycloak running locally. But this problem should occur on every keycloak-js version 17.0.1. As a side note this problem occurs always in Safari and in Chrome. But in chrome it does not occur under usual circumstances as #error=login_required is not added to the url.
> 
> ### Anything else?
> _No response_

first, you shoild add the initial option "checkLoginIframe": true  .
second, you shold use the init function in a .vue file, like  nav.vue

**Comment by birenjack** [comment]
> When I am using onLoad:"login-required" .then is not working. how do I fix it ??
use .init  function in the vue files like nav bar

**Comment by jonkoops** [comment]
I am unable to [reproduce this issue](https://github.com/jonkoops/kjs-playground/tree/issue-12410), but I am not using Vue. If anyone can reproduce this in a [Minimal, Reproducible Example ](https://stackoverflow.com/help/minimal-reproducible-example) (which means without Vue), it would help resolve this issue.

I've created the aforementioned repo specifically to test Keycloak JS integration, so the best option would be to [fork this repository](https://github.com/jonkoops/kjs-playground), and try to reproduce the issue there.

For now, I am closing this issue as there is not enough information to go on to reproduce the problem. I'll re-open it if steps to reproduce the issue are provided.

**Comment by mrdahbi** [comment]
I'm also using Nuxt and Vue with keycloak 22.0.5 with `check-sso` on load.
The same error `login_required` occured after calling `keycloak.login()`.

The issue was resolved after setting a redirectUri:
```js
keycloak.login({
  redirectUri: window.origin
})
```

**Comment by yukimasaki** [comment]
@mrdahbi 
Thank you.
It works, although `error=login_required` is added to the URL.

**Comment by yguenneugues** [comment]
@mrdahbi Thx a lot !
it works also for me with your solution !

**Comment by vincentgong7** [comment]
I encountered the same problem. After exploring for a while, I solve it with the following options in keycloak.init:

```
  onLoad: 'check-sso',
  redirectUri: redirect_url,
  pkceMethod: 'S256',
  checkLoginIframe: true
```

The key point is to enable the "checkLoginIframe".

**Comment by Fahad-ishfaq** [comment]
I am getting same error even with all these options,

Keycloak version : "22.0.3"
on frontend using Nuxt 2

```javascript

data() {
   return {
         keycloak: null
    }
},
mounted() {
         this.keycloak = new window.Keycloak({
            "realm": "user",
            "url": 'https://<keycloak-domain>',
            "clientId": '<client-Id>',
          });
        this.checkLogin();
},
methods: {
      async checkLogin() {
        const authenticated = await this.keycloak.init({ 
          onLoad: 'check-sso',
          checkLoginIframe: true,
          silentCheckSsoRedirectUri: window.origin
        });
        console.debug("authenticated: ", authenticated);
      },
}
```

whenever page refreshes it returns `#error=login_required&state=<state-value>"` in the url and page gets reloaded.

**Comment by temkarus0070** [comment]
https://www.keycloak.org/securing-apps/javascript-adapter#_modern_browsers
 docs says that it is can be unsupported by some browsers 
**The adapter relies on third-party cookies for Session Status iframe, silent check-sso and partially also for regular (non-silent) check-sso. Those features have limited functionality or are completely disabled based on how restrictive the browser is regarding cookies. The adapter tries to detect this setting and reacts accordingly.**
