### ISSUE TITLE
Review if we can remove BouncyCastle

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12416]

**Comment by david-rh** [comment]
Notes from my investigation into the option of decoupling KC from BC. There are some areas where that can be achieved. I will create tasks+prs for those areas as I continue to identify and resolve them. However, when looking into alternative standardized options for implementing the functionality in org.keycloak.common.util.CertificateUtils.generateV1SelfSignedCertificate(), I was unable to find any standard apis that would provide the needed behavior. This code would need to be abstracted out where the implementation can be provided using either BC or BC-FIPS.

**Comment by david-rh** [comment]
Continued investigation into wildfly elytron. It does appear that this would be a valid option for replacing the dependancy on BC for certificate creation.  I tested this with the RSAVerifierTest.

import org.wildfly.security.x500.cert.X509CertificateBuilder;
