### ISSUE TITLE
Run testsuite on FIPS enabled RHEL host

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12422]
The testsuite should have an option to run in FIPS mode and we need CI to run this. It may be just in the internal Jenkins pipelines, or also in GitHub Actions.

**Comment by mposolda** [comment]
@rmartinc Assigning to you as it is related to #15069

**Comment by mposolda** [comment]
@rmartinc I guess this can be considered resolved (based on your work on #15069, which is sufficient IMO). However I am not 100% sure if we need to test on ubi8 or ubi9. I've started thread on keycloak team ML with title "Do we target ubi8 or ubi9 for RHBK 22?"

So until now, we can keep this open as placeholder to eventually update our testsuite to ubi9 if needed.

**Comment by rmartinc** [comment]
Yes, I think this one is for the moment not needed if nobody says the contrary. The current github-actions use the ubi8 image but I suppose we can use ubi9 if necessary (although not checked).

**Comment by mposolda** [comment]
@rmartinc Official Keycloak container was updated to ubi9. See discussion on keycloak team mentioned above and also the related PR https://github.com/keycloak/keycloak/pull/17058 . So looks like we can also update fips tests to use ubi9 in GH actions?

**Comment by rmartinc** [comment]
Yes, we can do it. Do you want to use this issue for the PR?

**Comment by mposolda** [comment]
> Yes, we can do it. Do you want to use this issue for the PR?

@rmartinc +1
