### ISSUE TITLE
Investigate Apache Santuario security provider if it is FIPS 140-2 compliant

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12425]
We need to verify that Apache Santuario doesn't introduce any non-FIPS compliant algorithms. It may be needed that Santuario is actually FIPS verified or something for us to say KC is.

We should also review if it is even needed and can be removed altogether.

If we keep Santuario we should review [ProvidersUtil](https://github.com/keycloak/keycloak/blob/main/saml-core/src/main/java/org/keycloak/saml/processing/core/util/ProvidersUtil.java#L34) and how it adds it as a security provider.

**Comment by mposolda** [comment]
Did some investigation and sent draft PR for this. Details: https://github.com/keycloak/keycloak/pull/12786#issuecomment-1171285334
