### ISSUE TITLE
Update realm keys used in testsuite for FIPS 140-2 compliance

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12420]

**Comment by mposolda** [comment]
There is possibility that this was already (partially) solved in the branch https://github.com/sudeepd/keycloak/commits/saml-fixes . So maybe it is possible to use just keys from this branch?

However one point is, that keycloak testsuite should still work for both non-fips mode and fips mode

**Comment by jharmison-redhat** [comment]
@mposolda I've got some simple work done statically setting the certificates in the test suite to match the [Trellix branch commit](https://github.com/sudeepd/keycloak/commit/68cb0358000b33751e87649b222de03da2901aaa). I've also been poking around the way that the various tests set up these keys to prepare them to see if auto-generation by Keycloak matches the algorithms we would expect it to generate, but I'm having difficulty finessing the test suite to get it to run specific tests with the fips140-2 build.

Are you able to provide me some pointers on how you expect me to run these tests with a specific build? I think my ignorance of Maven is getting the best of me as I try to confirm that my changes are doing what I expect.

I'll be on PTO next week but will have my laptop with me and I'm sure I'll be interested in tinkering in some of my free time.

**Comment by mposolda** [comment]
@jharmison-redhat Thanks for the update!
Regarding the tests, there are 2 things:
- Unit tests, which directly test the code (for example those inside the modules `keycloak-common` or `keycloak-core`)
- Integration tests from the arquillian testsuite, which tests the whole server (those are mostly in the `testsuite/integration-arquillian` directory)

Regarding the unit tests, we can move them to the modules related to `crypto`, which will allow us to test for example with BC, or with BC-FIPS or with Elytron etc. I've started some of this in my PR https://github.com/keycloak/keycloak/pull/12692

Regarding the integration tests, you first need to build the server with the FIPS mode (and with BC-FIPS dependencies) as described here: https://github.com/keycloak/keycloak/blob/main/docs/fips.md . Then when you have KC server on Quarkus, you can run some specific test with quarkus like for example this way:
```
cd testsuite/integration-arquillian
mvn clean install -Pauth-server-quarkus -Dtest=LoginTest
```

**Comment by mposolda** [comment]
I am re-assigning to myself. Geting rid of hardcoded keys would be needed especially for BCFIPS approved mode support as there are lot of the keys hardcoded in integration testsuite, which use RSA with 1024 bits and that is not allowed in BCFIPS approved mode (minimum is 2048).

**Comment by jharmison-redhat** [comment]
Apologies - I forgot to ping your team when I was reassigned. I'm not part of the team that was working on this any longer.

**Comment by mposolda** [comment]
@jharmison-redhat np, that is fine
