### ISSUE TITLE
Verify what is needed in Quarkus to enable FIPS

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12428]
There may not be anything needed after the underlying OpenJDK security providers are configured, but we need to review and probably get in touch with someone from the Quarkus side

* * TLS

**Comment by mposolda** [comment]
@pedroigor I am assigning to you as you're most familiar with Quarkus. Also you may know who is Quarkus expert on security and who to contact to doublecheck this?


I think that we don't need to do anything special for this issue as the fact that we're running on FIPS enabled OpenJDK on FIPS enabled RHEL and with usage of BCFIPS library, which itself is FIPS compliant, should be sufficient as the non-FIPS compliant algorithms are unavailable. This applies to SSL/TLS layer, which relies on Java security and hence should allow only Java approved algorithms. But still, we can possibly doublecheck if there are some places in Quarkus, which use some non-FIPS compliant cryptography somehow (EG. implementing some cryptography in some module of their own? Or something like that?)

So this is just to doublecheck with them or if you are aware of something suspicious in Quarkus, which may not be FIPS compliant.

**Comment by pedroigor** [comment]
@mposolda My main concern is wherever we rely on PEM and keystore files like when enabling TLS, configuring truststores, etc.

Quarkus has its own FIPS configuration but we are not using it. I think we are basically doing the same thing as Quarkus when preparing the runtime for FIPS but need to double-check.

**Comment by mposolda** [comment]
@pedroigor Yes, Thanks for doublecheck. I think we're good at TLS handled by Quarkus/vert.x as we're using that in our testsuite. But doublecheck would be nice.
