### ISSUE TITLE
Review what algorithms, hash sizes, etc. are available and needs to be disabled in FIPS mode

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12426]
Identify what crypto is available in Keycloak, and create issues to disable options if not suitable for FIPS when running in FIPS mode.

For example it should not be possible to create a 1024k rsa key in FIPS mode, and that option should not be available.

Some things we need to review:

* Keys
* OIDC signing and encryption algorithms
* SAML signing and encryption algorithms
* Kerberos and LDAP
* WebAuthN
* OTP
* Password hashing
* X509 authenticator

Places where non-approved algorithms shouldn't be visible includes:

* Config options
* Admin UI
* OIDC discovery endpoint
* SAML metadata
* Adding initial admin user

We should also figure out how Keycloak should fail when using non-approved algorithms. For example a client trying to use a non-approved algorithm should result in a 4xx status code rather than a 500 with errors in the log.

**Comment by mposolda** [comment]
This is already done during other work. In FIPS mode, some options are hidden in the admin console. There was no need to hide anything in OIDC/SAML metadata in particular. Some things, which were done, are:
- Keystore types are dynamically retrieved from `CryptoProvider` based on which keystore types are available. This is used for example when setup `Java Keystore key provider or keys of OIDC/SAML clients
- RSA 1024 keys are not available with BCFIPS approved mode. The available key lengths are retrieved from `CryptoProvider` and hidden in the admin console
- Feature `KERBEROS` can be hidden in the admin console (and admin REST APIs) in case Kerberos/GSSAPI is not available in java, which is currently in OpenJDK 17 on RHEL with FIPS mode enabled
