### ISSUE TITLE
Investigate if we can have GitHub Actions test FIPS mode

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12434]
We'd need at least to be able to configure the OpenJDK on the GitHub runners

**Comment by stianst** [comment]
This will help collaborating on the FIPS support as we can check easily that a PR works in FIPS and non-FIPS mode

**Comment by mposolda** [comment]
Starting with adding unit tests #14241 . We will follow with integration tests in the follow-up PR

**Comment by mposolda** [comment]
This was already done in #14886 and we now have the initial tests available in GH actions. It is for the package `org.keycloak.testsuite.forms`, but we will add more packages and combinations for:
- BCFIPS non-approved mode (See #14729 and it's subtasks for the details)
- BCFIPS approved mode (See #14972 for the details)
- Hopefully also tests with keycloak-crypto-elytron module
