### ISSUE TITLE
Review if we want migration steps for users moving to FIPS mode

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#12432]
We could just document it, we could have a intermittent mode where non-FIPS compliance is logged rather than resulting in errors, we could also try to automatically migrate some config. This needs to be discussed.

For example if hashed passwords are using non-approved crypto then users password hashes will need to be updated prior to enabling FIPS mode, otherwise they will no longer be able to authenticate. Another example may be clients using non-approved crypto.

**Comment by pedroigor** [comment]
You are referring to approved or non-approved modes? Or both?

If the server is running in non-approved mode (e.g.: `fips-mode=enabled`) existing passwords using non-approved algs should still work?

**Comment by mposolda** [comment]
@pedroigor I used passwords as an example when this GH issue was created. Regarding passwords and pbkdf2:
- BCFIPS non-approved mode does not have any restrictions
- BCFIPS approved mode has restrictions of having passwords of at least 14 characters long. This can be mitigated by the option `--spi-password-hashing-pbkdf2-sha256-max-padding-length=14`

At the time when this GH issue was created, it was not clear if the backwards compatibility will be OK etc. But now, we know that it is OK. In other words when you have scenario like this:
- Non-FIPS environment with created user with short password `password`
- Then you start against same DB in BCFIPS approved mode with `--spi-password-hashing-pbkdf2-sha256-max-padding-length=14`
- User is able to login fine with his password `password` in BCFIPS approved mode. Also users are able to create new short passwords in this case.

Some details in https://github.com/keycloak/keycloak/blob/main/docs/fips.md#run-the-server-with-fips

**Comment by mposolda** [comment]
@pedroigor In general, I am not sure what to do with this task. So far, my vote is to just document the restrictions as already done in https://github.com/keycloak/keycloak/blob/main/docs/fips.md#run-the-server-with-fips .

We can also have this "special mode" where we can throw warnings in case that some settings (EG. keys, client secrets, user passwords) don't match the requirements specified by BCFIPS approved mode. For example when some realm is trying to use RSA key of 1024 bits (which is not allowed in BCFIPS approved mode). However the system cannot run in BCFIPS approved mode when you want this "warning" mode. As BCFIPS approved mode actively enforces restrictions.

Overally, I don't know how to have this "warning mode" running... The tricky thing is, that with BCFIPS approved mode, the restrictions are enforced and administrator see the errors when trying to use unsupported crypto. But with "warning mode", we would need to emulate it ourselves and I don't know how to do it cleanly...

Son in short: My vote is to just document the restrictions.

**Comment by mposolda** [comment]
Done together with https://github.com/keycloak/keycloak/issues/16444
