### ISSUE TITLE
Review and break down into separate tasks API incompatibility for FIPS mode in Keycloak

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12431]
Some code like those working with cerificates are using API from BC that is not compatible with BC FIPS. There may also be some code that doesn't work with OpenJDK in FIPS mode.

Ideal is we have the Keycloak code work in both modes, but worst case scenario we need to introduce something like a CryptoSPI with different providers for FIPS and non-FIPS mode.

**Comment by mposolda** [comment]
This task can be closed. The CryptoSPI was already introduced longer time ago as part of other tasks.
