### ISSUE TITLE
Direct Naked Impersonation - error: access_denied

### ISSUE THREAD

**Issue by motiejuss** [keycloak/keycloak#12438]
### Describe the bug

I have followed directions according to the guide (https://www.keycloak.org/docs/latest/securing_apps/#direct-naked-impersonation), but still cannot get it to work. After researching, seems like others can't get it to work neither (https://keycloak.discourse.group/t/direct-naked-impersonation/6887/3) and unfortunately I wasn't able to find a possible solution. 

Details about my Keycloak installation:

Version: 18
Installed using containers (AWS ECS) and using this guide: https://www.keycloak.org/server/containers
SSL enabled
token-exchange and admin-fine-grained-authz features enabled

Example request:
```
curl --location --request POST 'https://example_domain.com/realms/my-realm/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
--data-urlencode 'client_id=my-client' \
--data-urlencode 'client_secret=iXwJB01N5u0WcTEMMcGA1KvUWm5VA9HN' \
--data-urlencode 'requested_subject=test_user'
```

Example response:
```
403
{
    "error": "access_denied",
    "error_description": "Client not allowed to exchange"
}
```

Has anybody experienced the same or know if there's anything else to configure or may it be a bug?

### Version

18

**Comment by nloke** [comment]
I am facing the same issue and tested on version 16.1.1

**Comment by motiejuss** [comment]
I figured out a way, but I'm not sure this is the right way to do it. Some help from more experienced experts would be very much appreciated. 

When following the Direct Naked Impersonation guide, instead of `user-impersonated` under `Users -> Permissions` I chose `impersonate` to apply the `client-impersonators` policy. 

And then in order to achieve the desired result, there's rather a 2 step call that looks like this:

```
curl --location --request POST 'https://identity.domain.com/realms/my-realm/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=my_client_id' \
--data-urlencode 'client_secret=BZqGENd9LKJTixvJLl860jpCJvMgAY7y'
```

Client `access_token` from the response will then be used in the next call as a `subject_token` parameter. 

```
curl --location --request POST 'https://identity.domain.com/realms/my-realm/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
--data-urlencode 'requested_token_type=urn:ietf:params:oauth:token-type:access_token' \
--data-urlencode 'subject_token=eyJhbGciOiJSUzIU0ODU5NzQsImlhdCI6MTY1NTQ0OTk3NCwianRpIjoiZmFkYTBkODctNzMyYy00ZDY4LWJhYzctMDk2NWU1ZmJjMGFkIiwiaXNzIjoiaHR0cHM6Ly9zdGFnaW5nLWlkZW50aXR5Lm5vaWUuY29tL3JlYWxtcy9teS1yZWFsbSxlcy1teS1yZWFsbSJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsibWFuYWdlLXVzZXJzIiwidmlldy11c2VycyIsInF1ZXJ5LWdCBwcm9maWxlIiwiY2xpZW50SWQiOiJ3ZWJzaXRlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRIb3N0IjoiODIuMTkyLjE3MS4yMzgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtd2Vic2l0ZSIsImNsaWVudEFkZHJlc3MiOiI4Mi4xOTIuMTcxLjIzOCJ9.ZducIG0iqNJ55kWgcN7-EwZvVibwa-RCl2lc3JZRCike4bkhIHBOWe_ypFPb-i_VEVRhKrhv-vANl5xIFbvqez_1PRGrhqHhIaf5xQmMoFu_TKd7EoKIbk_bCKrj3P3OdVqt0N0Uiutc2IDSlhsLGtFHmz1H5vc_2Jddlp_KnjeSjobiamC9_4ut2uGVYJ8ev_639hF54Y67_rH88SPorAM8riWFxsvhi0LDQ5swBpi9rT1K-cAT3PtrM2vKITg4H-GSfKI3z7VA' \
--data-urlencode 'client_secret=BZqGENd9LKJTixvJLl860jpCJvMgAY7y' \
--data-urlencode 'client_id=my_client_id' \
--data-urlencode 'audience=my_client_id' \
--data-urlencode 'requested_subject=username'
```

**Comment by pedroigor** [comment]
@motiejuss We should improve the documentation. We had some changes recently in this area and that perhaps is the confusion. The main change was related to how we handle the `audience` parameter and the conditions that should be met in order to exchange.

If the audience is not set it will take the audience as the client for which the `subject_token` was issued for (`azp` claim). If the client making the request (e.g.: `my_client_id`) is different it will fail as long as you have explicitly set the permissions to grant the `token-exchange` scope that you configure for the client making the request. I think that is why you had the additional step to obtain an AT for `my_client_id`.

But yeah, you should be fine by defining the policies for the `impersonate` scope and optionally define policies for the `user-impersonated` scope.

**Comment by pedroigor** [comment]
@motiejuss Created https://github.com/keycloak/keycloak/issues/12634. PR sent, please let me know if you think we can improve more.

**Comment by nloke** [comment]
The updated Documentation still does not reflect that the whole Direct Naked steps are wrong like what @motiejuss  mentioned. In the documentation it is just a ONE STEP curl with the clientID and secret, not like the example that @motiejuss  provided which is two steps and requires the accesstoken from first doing a client_credential flow.

**Comment by nloke** [comment]
@motiejuss I tried the steps you mentioned but I am still not able to make it to work. That being said I am using 16.1.1, still having trouble to get the 18.0.1 to fully work on EKS due to some admin console redirection issue that I have yet to figure out how to overcome.

**Comment by motiejuss** [comment]
Thanks @pedroigor . @nloke actually now playing a bit more with the token-exchange request I'm now able to make it in one go. I don't know why I haven't tried it before and went to the 2 step flow which is also valid, but if you just remove `subject_token` AND `audience` params from the second request it will return 200 with the `access_token` that is valid to impersonate. I tested and it works.
