### ISSUE TITLE
Flaky map tests in June 2022

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#12445]
### Describe the bug

This collects flaky test runs that should be investigated.

Please mention PR, test suite, action run and failed test.

### Version

999-SNAPSHOT

**Comment by DGuhr** [comment]
PR: #12371 
Run: https://github.com/keycloak/keycloak/runs/6815002365?check_suite_focus=true

Test suite: Base testsuite (undertow-map, group3)

Failed test: RefreshTokenTest.tokenRefreshRequest_ClientES512_RealmRS256:1349->conductTokenRefreshRequest:1393->refreshToken:1446 » Runtime

**Comment by hmlnarik** [comment]
Please introduce a specific issue for each failing test. Do not introduce collective (umbrella) issues as it is hard to keep track of fixing individual bugs.
