### ISSUE TITLE
Map Storage: make single-use object entities realm-specific

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#12462]
### Description

Currently the single-use object entities have no reference to the realm that was used to create them. This has to be changed, so that operations like `get`, `contains` and `remove` in `MapSingleUseObjectProvider` use the `realmId` when operating on these objects.

### Discussion

https://github.com/keycloak/keycloak/discussions/12408

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
