### ISSUE TITLE
prompt=none is not forwarded to IDP when "prompt" configuration option is specified

### ISSUE THREAD

**Issue by kherock** [keycloak/keycloak#12469]
### Describe the bug

When both "Accepts prompt=none forward from client" and "Prompt" are configured on an OIDC provider (or any provider extending `AbstractOAuth2IdentityProvider`) the `IdentityProviderRedirector` won't forward prompt=none requests. This occurs ultimately because there is no special behavior in `AbstractOAuth2IdentityProvider#createAuthorizationUrl()` for preferring the parameter supplied in the request.

### Version

18.0.0

### Expected behavior

Intuitively, I would expect "Accepts prompt=none forward from client" to make an exceptional case to the `prompt` configuration option on IDPs, since otherwise the option has no apparent effect.

Moreover, I actually would expect that any user-supplied `prompt` parameter should override the preference set on the IDP, but perhaps that change might be too disruptive. For example, an application supplying `prompt=login` in the request should override `prompt=select_account` in the IDP.

### Actual behavior

When both options are configured, prompt=none forwarding has no apparent effect.

### How to Reproduce?

1. Configure the prompt config option to `select_account` or `login` and enable prompt=none forwarding
2. Attempt to run an authentication flow, passing `prompt=none` in the URL
3. Keycloak will show the IDP's login screen instead of silently redirecting back to the application with `login_required` error

### Anything else?

I encountered this issue because I am developing applications that single sign-on with Azure AD and would like to always present the account selector with `prompt=select_account`. This way, users can have multiple Azure AD sessions and switch between them freely without needing to implement special behavior on our web clients.

**Comment by mposolda** [comment]
I agree that in case that IdentityProvider Authenticator is configured to `Accepts prompt=none forward from client`, then the `prompt` set on the Idp can be likely overriden and instead `prompt=none` should be sent to the IDP. Hence the `prompt=none` would take the preference.

I am adding this with the label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to send PR for this with the fix.
