### ISSUE TITLE
Add Apple ID to Identity Providers

### ISSUE THREAD

**Issue by humleflue** [keycloak/keycloak#12468]
### Description

Migrated from: https://issues.redhat.com/browse/KEYCLOAK-13171

It would be nice to have Apple ID (Sign in with apple) as an Identity Provider.
https://developer.apple.com/sign-in-with-apple/

Apple requests apps to have "sign in with apple" option if there are any other social login options.

### Discussion

https://keycloak.discourse.group/t/sign-in-with-apple/119/30

### Motivation

From a Keycloak point of view, the following improvements would be very-VERY-nice-to-have:

- First and foremost: Implement response_mode=form_post for identity providers, as the lack of support for it actually negatively impacts the integration of Sign-In With Apple when using Keycloak.
- Add Apple as dedicated identity provider. It will make the configuration easier and will even allow Keycloak to display the apple Icon in the login screen - yay! 
- When using that new Apple identity provider, let admins enter the private key (or upload the p8 file) received from Apple in OpenSSL format (just as they received it from Apple, without the need to generate anything else themselves). And set up a scheduler in Keycloak that periodically renews the client secret using that key. I would then disable the “Client Secret” password input field in the Admin Console so that it is clear that this one is managed by Keycloak.

**Comment by humleflue** [comment]
Duplicate

**Comment by humleflue** [comment]
Duplicate

**Comment by acdha** [comment]
This was closed as a duplicate but there isn't a pointer to where. Is that #7323?
