### ISSUE TITLE
Expiration for Admin Events

### ISSUE THREAD

**Issue by thpeter** [keycloak/keycloak#12476]
### Description

Add an expiration time to admin events. This could be done in the same way the non-admin events are currently cleaned up as a per realm setting. The default setting should be the current behavior (no expiration). This should be a separate setting from the existing eventsExpiration.

### Discussion

https://github.com/keycloak/keycloak/discussions/10646

### Motivation

Admin events, too, should have an expiration time after which they can be cleaned up so the table does not grow in an unlimited way.

**Comment by sschu** [comment]
@stianst FYI.

**Comment by thpeter** [comment]
opened a [PR](https://github.com/keycloak/keycloak/pull/12501)

**Comment by hmlnarik** [comment]
Please hold on with this issue as it collides with #9667

**Comment by JohnPolansky** [comment]
Just registering another customer interest in this feature, our keycloak has 100's of realms and we expect more, having to go through 100's of realms to click a button, even via API seems less than ideal, not sure if it's safe to delete via SQL from DB. But having an auto-expiration like login events seems to make a lot more sense. Thx!

**Comment by ahus1** [comment]
@hmlnarik - it seems to me that this issue has now been implemented: both backend and UI are there.

**Comment by ahus1** [comment]
@hmlnarik - it seems to me that this issue has now been implemented: both backend and UI are there as part of KC 20.0.0. 
Unfortunately it is broken on Oracle, see #15528
