### ISSUE TITLE
I can't log into the keycloak container

### ISSUE THREAD

**Issue by helmutct** [keycloak/keycloak#12487]
### Describe the bug

I'm using docker-compose to create keycloak and postgresql containers. The container uses an external reverse proxy that automatically generates letsencrypt certificates (jwilder/docker-letsencrypt-nginx-proxy-companion), so I don't need to register the certificates in keycloak.

When running the container everything worked (the keycloak container log shows that everything started without error), but when opening the url in the browser by clicking "Administration Console", at login page I type the same username and password as the KEYCLOAK_ADMIN e KEYCLOAK_ADMIN_PASSWORD docker variables, then I get as return the message "Invalid username or password".

When trying to log in to the browser console, no error appears and in the keycloak log this message appears:
> 2022-06-13 20:34:50,957 WARN  [org.keycloak.events] (executor-thread-5) type=LOGIN_ERROR, realmId=0bc98fc6-e5de-41b4-b57c-7fd44635a8d7, clientId=security-admin-console, userId=495ea3f3-2926-4a04-998a-d43ada1aa4e6, ipAddress=[my.ip], error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=https://[mydomain].com/admin/master/console/, code_id=dfe7fcd1-7cf0-4f16-ad31-096109ba890f, username=admin, authSessionParentId=dfe7fcd1-7cf0-4f16-ad31-096109ba890f, authSessionTabId=OXOvQHCkJBc

### Version

18.0.0

### Expected behavior

Successfully login at "Administration Console".

### Actual behavior

Get the message "Invalid username or password" when informing the same credentials from docker container.

### How to Reproduce?

Run the keycloak container with these environment variables:

```
KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
KC_DB_USERNAME=${DB_USER}
KC_DB_PASSWORD=${DB_PASSWORD}
KEYCLOAK_ADMIN='admin'
KEYCLOAK_ADMIN_PASSWORD='ad123456'
KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
HTTP_ADDRESS_FORWARDING='true'
KC_HTTP_PORT=${KEYCLOAK_HTTP_PORT}
KC_HTTP_ENABLED=true
KC_HOSTNAME_STRICT=false
KC_HOSTNAME_STRICT_HTTPS=false
KC_PROXY=edge
```
Remembering that my reverse proxy is external, that's why I have KC_HTTP_ENABLED=true, HTTP_ADDRESS_FORWARDING='true'...

**Comment by helmutct** [comment]
My mistake... There were two keycloak containers on the same server, and the volume being shared.

**Comment by kekersdev** [comment]
Had the same issue
