### ISSUE TITLE
build failed from keycloak source code

### ISSUE THREAD

**Issue by suichangyin** [keycloak/keycloak#12489]
### Describe the bug

i download the keycloak source code at https://github.com/keycloak/keycloak/archive/refs/tags/18.0.0.zip.

build with "mvn -f "pom.xml" -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean package"

but the build is failed, and the error message is:
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:install-node-and-npm (install node and npm) on project keycloak-js-adapter: The plugin com.github.eirslett:frontend-maven-plugin:1.12.0 requires Maven version 3.6.0 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:install-node-and-npm (install node and npm) on project keycloak-js-adapter: The plugin com.github.eirslett:frontend-maven-plugin:1.12.0 requires Maven version 3.6.0

please check is this a bug?

and i am use the maven 3.5.4 and jdk 1.8 on windows 10 paltform.

the building https://github.com/keycloak/keycloak/blob/main/docs/building.md write JDK 8 (or newer), Maven 3.5.4 (or newer) and Git installed, so is maven 3.5.4 not supported?

### Version

18.0.0

### Expected behavior

build complate

### Actual behavior

build failed

### How to Reproduce?

build with 'mvn -f "pom.xml" -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean package'

**Comment by pedroigor** [comment]
As we are constantly running the project from sources, it is working fine. However, improvements are being made to keep it in sync with the current practices.

See https://github.com/keycloak/keycloak/pull/16924.
