### ISSUE TITLE
Dependency conflicts for org.jboss.resteasy packages

### ISSUE THREAD

**Issue by anthowlett** [keycloak/keycloak#12496]
### Describe the bug

Please update the version of the `resteasy` dependencies. We have a project which displays the following error due to conflicting versions of the `org.jboss.resteasy:resteasy-jaxrs` package:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1526080/173527406-de45b6cc-5d15-4267-86db-e05d6134a12c.png">

This is likely because `org.keycloak:keycloak-services:17.0.1` uses `org.jboss.resteasy:resteasy-jaxrs:3.15.1.Final` and `org.keycloak:keycloak-admin-client:17.0.1` uses `org.jboss.resteasy:resteasy-jaxrs:3.13.2.Final`. Removing the latter from the project fixes the error.

### Dependency Trees

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1526080/173528417-b47d7b50-a497-49bf-b458-5910d2d07501.png">

<img width="269" alt="image" src="https://user-images.githubusercontent.com/1526080/173528503-01029a05-7270-44e3-9c6f-c215cca22ee9.png">

This was error occurred while using 17.0.1 but looks to also be present in 18.0.0

### Version

17.0.1

### Expected behavior

Child dependencies are in sync.

### Actual behavior

Child dependencies are out of sync.

### How to Reproduce?

Implement both `org.keycloak:keycloak-services:17.0.1` and `org.keycloak:keycloak-admin-client:17.0.1` in the same project.

**Comment by anthowlett** [comment]
https://github.com/keycloak/keycloak/issues/11832

**Comment by pedroigor** [comment]
@anthowlett There were critical changes to our dependency management including making sure we have an SSoT for the versions we are using.
