### ISSUE TITLE
Remove two ways for setting user fields in physical layer

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12495]
### Description

In this issue, we need to remove two ways of setting fields like firstName, lastName, etc. (all that can be set using the `setAttribute` method). For more details see the linked discussion, especially the following comment: https://github.com/keycloak/keycloak/discussions/10004#discussioncomment-2912063

### Discussion

https://github.com/keycloak/keycloak/discussions/10004

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
