### ISSUE TITLE
error:1408F10B:SSL routines:ssl3_get_record:wrong version number on Keycloak 17.0.0

### ISSUE THREAD

**Issue by kpbasu** [keycloak/keycloak#12490]
### Describe the bug

We are getting below error on Keycloak 17.0.0.

error:1408F10B:SSL routines:ssl3_get_record:wrong version number
While generating Keycloak Token, Receiving SSL3 Error(url)

### Version

17.0.0

### Expected behavior

Token generated successfully. 

### Actual behavior

While generating Keycloak Token, Receiving SSL3 Error
error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by stianst** [comment]
This is not an error in a format that Keycloak would output, so not sure what's going on here. Can you provide some more information please?

**Comment by stianst** [comment]
Closing due to insufficient information, and error message is not an error from Keycloak.
