### ISSUE TITLE
Investigate usage of HotRod enums

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12502]
Currently, we are using `ProtoEnumValue` annotations for all enums in HotRod. This may cause problems for no-downtime upgrades. This can be solved by changing enums to Integer. Some work was already done here: https://github.com/mhajas/keycloak/commits/12277-enums

**Comment by DhirajSardar** [comment]
Can I work on this issue?

**Comment by mhajas** [comment]
Hello @DhirajSardar, thank you for your interest in the new storage for Keycloak. Sure, feel free to provide a PR. This should be a simple one, it should be enough to cherry-pick the changes I linked above and make sure the testsuite is passing.

**Comment by hmlnarik** [comment]
Is this related to #12299?

**Comment by mhajas** [comment]
Yes this is follow up issue on #12299 that implements it for HotRod

**Comment by mhajas** [comment]
@DhirajSardar I hope I do not interrupt you in the middle of work on this issue, however, I needed to provide a PR for this issue myself as this is a high-priority issue. If you still want to work on some issue regarding the new Keycloak storage, feel free to choose anything from https://github.com/orgs/keycloak/projects/9.
