### ISSUE TITLE
Make sure `hostname-path` is considered when redenring admin URLs

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#12506]
### Describe the bug

I start Keycloak with kc.sh start proxy=edge --hostname-path=keycloak --http-enabled=true and set the hostname via
ENV KC_HOSTNAME. My reverse proxy config is /keycloak -> http://local-keycloak:8080. Navigating to /keycloak shows the landing page and e.g., resources are correctly loaded from /keycloak/resources as expected. However, the href emitted for the admin console link does not honer the provided hostname-path and points to /admin on my host. Navigating manually to /keycloak/admin/master/console/ yields a broken page as the resources are now loaded from /resources on my host, what is quite strange as on the login page the --hostname-path was honored.

### Version

18.0.0

### Expected behavior

Honor the value set to `hostname-path` when building admin URLs.

**Comment by pedroigor** [comment]
I think it would be the next issue but that one is related to how the port is resolved.

**Comment by dvallant** [comment]
@stianst Any chance this will be fixed in 19.x? Currently it prevents us from migrating to the new Quarkus distribution, 'cause we are running 3 Keycloak instances on a single host, under a single domain name and the context path is configurable by our OPs, so we cannot hardcode it :-/

**Comment by pedroigor** [comment]
@dvallant This should now be fixed by https://github.com/keycloak/keycloak/pull/13681. Can you please check our nightly image build?

**Comment by dvallant** [comment]
@pedroigor After setting both KC_HOSTNAME_URL and KC_HOSTNAME_ADMIN_URL to the same value, all works fine :-) Thx.
Are there any plans to back port this to version 19?

**Comment by pedroigor** [comment]
@dvallant Yeah, I'm doing it now.

**Comment by dvallant** [comment]
@pedroigor Great! Thx

**Comment by luchsamapparat** [comment]
I can also confirm that it works 👍 Looking forward to the release. Thanks!
