### ISSUE TITLE
Only the Credential Authenticator with the highest priority is added to AuthenticationSelectionOptions

### ISSUE THREAD

**Issue by chh456** [keycloak/keycloak#12519]
### Describe the bug

Hello

I am implementing authentification with multiple second factors as alternatives. My flow looks similar to this:

- First Factor (Required)
- Second Factor Flow (Required)
-- Authenticator A implements CredentialValidator (Alternative)
-- Authenticator B implements CredentialValidator (Alternative)
-- Authenticator C (Alternative)

Authenticator A has priority 3 and Authenticator B has priority 2 in authentication_execution table.

### Version

18.0.0

### Expected behavior

After logging in, all Authenticators implementing CredentialValidator should be added to AuthenticationSelectionOptions, a "try another way" link should be generated and the user should be able to chose between Authenticators A, B, C.

### Actual behavior

When the user successfully logs in with username/password they "see" authenticator B's authenticate method with "try another way" link present in the template. After clicking "try another way" link they can chose between Authenticator B and Authenticator C.

### How to Reproduce?

Create Authentication Flow and log in.

- First Factor (Required)
- Second Factor Flow (Required)
-- Authenticator A implements CredentialValidator (Alternative)
-- Authenticator B implements CredentialValidator (Alternative)
-- Authenticator C (Alternative)

### Anything else?

When the flow looks like this:

- First Factor (Required)
- Second Factor Flow (Required)
-- Authenticator A implements CredentialValidator (Alternative) (higher priority)
-- Authenticator B implements CredentialValidator (Alternative) (lower priority)

The "try another way" link is not generated at all and authenticator A is loaded. The user is only able to authenticate with authenticator B if authenticator A sets context.failure at some point.

I think the problem happens in AuthenticationSelectionResolver line 91:
`.filter(typeAuthExecMap::containsKey)`

With typeAuthExecMap only containing the authenticator (CredentialValidator) with the highest priority.

Any help or advice if I'm overlooking something would be appreciated.

**Comment by pedroigor** [comment]
Please, provide more details given that the reported issue could not be reproduced.
