### ISSUE TITLE
WebSecurityConfigurerAdapter is deprecated since Spring Security 5.7.0

### ISSUE THREAD

**Issue by brunomendola** [keycloak/keycloak#12514]
### Description

The latest release of Spring Boot (2.7.0) upgraded Spring Security to version 5.7.1.

As described in [this post in the Spring Blog](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter), Spring Security 5.7.0 deprecated the `WebSecurityConfigurerAdapter` and moved to a component-based configuration.

The problem is that you can't use the old and the new configuration in the same project: component-based **XOR** `WebSecurityConfigurerAdapter`.

Anyone who would like to use the new configuration of Spring Security (even just to get rid of the deprecation warning) will be blocked by `KeycloakWebSecurityConfigurerAdapter` still extending `WebSecurityConfigurerAdapter`.

By trying to do so, you get the following exception: `java.lang.IllegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.`

For more info about this decision, see [this GitHub issue](https://github.com/spring-projects/spring-security/issues/10822) in the Spring Security project.

**Comment by anthonyraymond** [comment]
I'm ran a test project with spring boot 2.7.1 (security 5.7.1), i've created a custom `AbstractHttpConfigurer` and applied it in a `SecurityFilterChain` it works quite well as long as you don't create  `KeycloakWebSecurityConfigurerAdapter` anotated with `@Configuration`.


But, i share your interest in getting a `Configurer` from the keycloak lib itself.

**Comment by anthonyraymond** [comment]
Actually, the Spring boot adapter itself is to be deprecated.

You can replace the keycloak spring boot adapter with the spring security oauth2 configurer.

This is how i configured my API application (resource-server).

pom.xml
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>

```

SecurityConfig.java
```java
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(
        securedEnabled = true,
        jsr250Enabled = true,
        prePostEnabled = true
)
public class SecurityConfig {

    @Bean
    SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        return http.authorizeRequests()
                    .anyRequest().authenticated()
                .and().sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and().oauth2ResourceServer()
                    .jwt().jwtAuthenticationConverter(new KeycloakJwtAuthenticationConverter()).and()
                .and().cors() // by default uses a Bean by the name of corsConfigurationSource
                .and().csrf().disable()
                .formLogin().disable()
                .httpBasic().disable()
                .build();
    }
}
```
`KeycloakJwtAuthenticationConverter` is a simple implementation of `JwtAuthenticationConverter` that defines wich claims are to be used to build the `Authentication` token.


application.yml
```yml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://xxxxx.xxx/realms/<realm>
```

**Comment by brunomendola** [comment]
Hi! Any plans on resolving this? At least with a decision on what to do...

If the Keycloak adapter is deprecated because Spring has shipped its own generic solution for Oauth2 clients, then I'd expect the Keycloak documentation to reflect this change and suggest the usage of the Spring library, instead of a deprecated one.

This issue wil become blocking when Spring will completely remove the support for WebSecurityConfigurerAdapter (maybe with Spring Boot 3 on november '22?).

**Comment by ChenSino** [comment]
I stuck with the same problem! How did you solve it ?

**Comment by mjeffrey** [comment]
Hi @anthonyraymond. 

Thanks for the info. 
You mentioned `Actually, the Spring boot adapter itself is to be deprecated`
Do you have a link to something official from Keycloak?

**Comment by anthonyraymond** [comment]
Here is the doc : https://www.keycloak.org/2022/02/adapter-deprecation

>What is being deprecated:
> - OpenID Connect Java adapters
> - OpenID Connect Node.js adapters
> - SAML Tomcat and Jetty adapters
>
>What is not being deprecated:
> - OpenID Connect client-side JavaScript adapter
> - SAML WildFly and servlet filter

And reading further you can see "alternative > spring oauth2"

**Comment by dmitry-weirdo** [comment]
Hi guys. 

I am now migrating my app to Spring Boot `3.0.0-RC2` and Spring Security `6.0.0-RC2`. And `WebSecurityConfigurerAdapter` is not anymore there (see also https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter). Therefore the project does not compile anymore.

How to configure Keycloak with the new Spring Security? https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter — does not mention other options as extending the `KeycloakWebSecurityConfigurerAdapter`.

**Comment by anthonyraymond** [comment]
> Hi guys.
> 
> I am now migrating my app to Spring Boot `3.0.0-RC2` and Spring Security `6.0.0-RC2`. And `WebSecurityConfigurerAdapter` is not anymore there (see also https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter). Therefore the project does not compile anymore.
> 
> How to configure Keycloak with the new Spring Security? https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter — does not mention other options other than extending the `KeycloakWebSecurityConfigurerAdapter`.

See: https://github.com/keycloak/keycloak/issues/12514#issuecomment-1209109769

**Comment by OtenMoten** [comment]
> Actually, the Spring boot adapter itself is to be deprecated.
> 
> You can replace the keycloak spring boot adapter with the spring security oauth2 configurer.
> 
> This is how i configured my API application (resource-server).
> 
> pom.xml
> 
> ```
> <dependency>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-security</artifactId>
> </dependency>
> <dependency>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
> </dependency>
> ```
> 
> SecurityConfig.java
> 
> ```java
> @Configuration
> @EnableWebSecurity
> @EnableGlobalMethodSecurity(
>         securedEnabled = true,
>         jsr250Enabled = true,
>         prePostEnabled = true
> )
> public class SecurityConfig {
> 
>     @Bean
>     SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
>         return http.authorizeRequests()
>                     .anyRequest().authenticated()
>                 .and().sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
>                 .and().oauth2ResourceServer()
>                     .jwt().jwtAuthenticationConverter(new KeycloakJwtAuthenticationConverter()).and()
>                 .and().cors() // by default uses a Bean by the name of corsConfigurationSource
>                 .and().csrf().disable()
>                 .formLogin().disable()
>                 .httpBasic().disable()
>                 .build();
>     }
> }
> ```
> 
> `KeycloakJwtAuthenticationConverter` is a simple implementation of `JwtAuthenticationConverter` that defines wich claims are to be used to build the `Authentication` token.
> 
> application.yml
> 
> ```yaml
> spring:
>   security:
>     oauth2:
>       resourceserver:
>         jwt:
>           issuer-uri: https://xxxxx.xxx/realms/<realm>
> ```

What's the dependency for Maven for this class: KeycloakJwtAuthenticationConverter ?

**Comment by anthonyraymond** [comment]
There is none. Its an implementation of my own.

KeycloakJwtAuthenticationConverter is a simple implementation of JwtAuthenticationConverter that defines wich claims are to be used to build the Authentication token.

**Comment by OtenMoten** [comment]
> There is none. Its an implementation of my own.
> 
> KeycloakJwtAuthenticationConverter is a simple implementation of JwtAuthenticationConverter that defines wich claims are to be used to build the Authentication token.

Could you provide an example?

**Comment by anthonyraymond** [comment]
> Could you provide an example?

Here is an example:

```java
package com.cjp.auth.oauth.converters;

import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter;

public class KeycloakJwtAuthenticationConverter extends JwtAuthenticationConverter {
    public static final String PRINCIPAL_CLAIM_NAME = "preferred_username";
    public static final String AUTHORITY_PREFIX = "ROLE_";

    public KeycloakJwtAuthenticationConverter() {
        var grantedAuthoritiesConverter = new KeycloakRealmRolesGrantedAuthoritiesConverter();
        grantedAuthoritiesConverter.setAuthorityPrefix(AUTHORITY_PREFIX);

        setJwtGrantedAuthoritiesConverter(grantedAuthoritiesConverter);
        setPrincipalClaimName(PRINCIPAL_CLAIM_NAME);
    }
}
```

**Comment by rcbandit111** [comment]
What should be the import for `KeycloakRealmRolesGrantedAuthoritiesConverter`?

**Comment by anthonyraymond** [comment]
@rcbandit111 i've updated my comment

**Comment by madukan** [comment]
It it just me or do I see a mixing of the Authorisation Server implementation vs OIDC Client implementation in the discussion forums. Why I say that here? Well, it is because it doesn't make sense to me how a problem in here (OAuth client):

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
```

Can be solved by this (Resource server):

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
```

... in terms of logging out through the back channel. Logging out a single session for a given user, through one client!

**Comment by anthonyraymond** [comment]
@madukan I'm a bit confused here. I think i don't get your point.

I don't understand why you are opening with `Authorisation Server implementation` **vs** `OIDC Client implementation`
and end up linking maven reference to `resource-server` *vs* `oauth2-client`.

And thus i'm a bit lost, what is the question?

**Comment by stianst** [comment]
Closing as we are not planning any further updates to the Keycloak Spring adapter. Please look at Spring Security as an alternative.

For those using Keycloak authorization client, there is a new version of that, which is framework agnostic, and can be used in combination with any OAuth or OIDC libraries like Spring Security.
