### ISSUE TITLE
Viewing the User Consent page has the potential to kill a Keycloak Instance if number of offline sessions is High

### ISSUE THREAD

**Issue by davidfrickert** [keycloak/keycloak#12511]
### Describe the bug

When attempting to view the User Consents page in our PROD env, this causes the Keycloak instance that processes this request to spike to 100% memory usage and 100% cpu.

![imagem](https://user-images.githubusercontent.com/25358815/173590666-fc01e203-f4c1-49f1-b2bc-4ea24c311a96.png)

This button seems to trigger a weird query. It fetches all client sessions between minUserSessionId and maxUserSessionId. This query has the potential to retrieve millions of rows!
https://github.com/keycloak/keycloak/blob/9df0d9a5c49ca178c2832b5bb7596c84398aba36/model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentClientSessionEntity.java#L43

Since '<=' and '>=' are being used, this query will not only return the client sessions associated with the user sessions of the specified user. This was a change introduced in commit 919899b9, which I think should be reverted as the `IN` in the previous query would not have this problem.

In our case, the query returned 9 million rows: 

![imagem](https://user-images.githubusercontent.com/25358815/173592999-ba4bd7d1-ab19-4542-ae0a-77ce3d6c4929.png)

![imagem](https://user-images.githubusercontent.com/25358815/173590118-315f5649-b6d8-4d86-8432-3462ce5a13e1.png)
![imagem](https://user-images.githubusercontent.com/25358815/173590547-ca066de3-d96e-4d17-bbc0-092d821490af.png)

### Version

15.1.1

### Expected behavior

User Consents are loaded and keycloak resumes operation as normal.

### Actual behavior

Webpage freezes. Keycloak memory spikes to 100%. CPU also spikes to 100%. 

### How to Reproduce?

Create a big number of users. (~500k)
Create a few sessions for each user (5-10).
Attempt to view the User Consents page for any User.

**Comment by pedroigor** [comment]
@keycloak/store Could you please triage this one?

**Comment by davidfrickert** [comment]
most likely duplicate of https://github.com/keycloak/keycloak/issues/13340 which was already addressed
