### ISSUE TITLE
build server failed from keycloak source code

### ISSUE THREAD

**Issue by suichangyin** [keycloak/keycloak#12517]
### Describe the bug

i download the keycloak source code at https://github.com/keycloak/keycloak/archive/refs/tags/18.0.0.zip.

build with "mvn -f "pom.xml" -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean package"

but the build is failed, and the error message is:
[ERROR] Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:5.2.7.Final:build-feature-pack (keycloak-server-galleon-pack-build) on project keycloak-server-galleon-pack: Failed to resolve org.keycloak:keycloak-admin-cli:jar:18.0.0: Could not find artifact org.keycloak:keycloak-admin-cli:jar:18.0.0 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:5.2.7.Final:build-feature-pack (keycloak-server-galleon-pack-build) on project keycloak-server-galleon-pack: Failed to resolve org.keycloak:keycloak-admin-cli:jar:18.0.0

please check is this a bug?

and i am use the maven 3.6.0 and jdk 1.8 on windows 10 paltform.

### Version

18.0.0

### Expected behavior

build complate

### Actual behavior

build failed

### How to Reproduce?

build with 'mvn -f "pom.xml" -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean package'

**Comment by mposolda** [comment]
This is probably out-of-date, so I am closing. Please try to build with latest sources with JDK 11 by command:
```
mvn clean install -DskipTests=true -Pdistribution
```
and you will see built server at `quarkus/dist/target`
