### ISSUE TITLE
Check whether Infinispan 14 still requires configuring indexed entities within cache configuration

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12526]
Currently, we need to configure indexed-entities within cache configuration. This means we need to have no downtime upgrades for cache configuration. We should investigate how to make this changes no-downtime upgradable

**Comment by martin-kanis** [comment]
Nested entities are removed from cache's definitions as part of https://github.com/keycloak/keycloak/pull/13910.

Splitting a root entity into more entities that should be defined in a cache's definition for performance reasons is tracked as a feature request here: https://issues.redhat.com/browse/ISPN-14085
