### ISSUE TITLE
Not possible to expose Keycloak on a non-standard-port

### ISSUE THREAD

**Issue by dennismeissel** [keycloak/keycloak#12529]
### Describe the bug

If I start Keycloak in the Production mode behind reverse proxy, which runs on a certain Port (not a standard one) and configure the Port using environment Variable KC_HOSTNAME_PORT, it doesn't completely work. Keycloak  tries to load some resources using the baseUrl without the port.

### Version

18.0.0

### Expected behavior

Proxy with non-standard ports should work the same way as with standard ports

### Actual behavior

1. If I login into admin console, I get an error: "Invalid Parameter Redirect Url", because ${authAdminUrl} variable is filled without the Port number
2. If I change security-admin-console RootUrl to ${authBaseUrl}, I can login, but admin-console is not loading
3. When I open browser console, I see that Keycloak unsuccessfully tries to load many resources from https://localhost/ without the Port number, though the number has been set using KC_HOSTNAME_PORT Variable
4. If I use Proxy with the standard 443 port, everything works

### How to Reproduce?

- Start keycloak in a container (-p 8080:8080)
The container is started with the following environment variables:
```
KC_HOSTNAME=localhost
KC_HOSTNAME_PORT=10443
KEYCLOAK_FRONTEND_URL=https://localhost:10443/
```

- Start reverse proxy on some non-standard port (for example on 10443) and configure it to pass traffic to keycloak container on the exposed port.

**Comment by jhollmannk** [comment]
We had the same problem: An nginx is running in front of keycloak in a docker environment and the nginx container is exposed on a different port.

We also found that setting the KC_HOSTNAME_PORT environment variable is not enough for the admin console.

We had to set the X-Forwarded-Port header in the nginx location for keycloak.

**Comment by dennismeissel** [comment]
@jhollmannk Thank you, your solution has solved my problem
