### ISSUE TITLE
[Javascript Adapter] Logout with id_token_hint undefined when updateToken fails

### ISSUE THREAD

**Issue by hufon** [keycloak/keycloak#12520]
### Describe the bug

WIth the new keycloak 18 implementation the logout function of the javascript adapter don't work :+1: 
 when the session has been expired and when the updateToken function has been called and fails.

The requested url for logout has a '&id_token_hint=null' parameter so keycloak display an error page with id_token_hint parameter is invalid.

### Version

18.0.0

### Expected behavior

We should be able to logout from keycloak with JS, even if the session has expired and even if the updateToken method has failed to refresh the token

### Actual behavior

updateToken calls clearToken() when session is expired. ClearToken cleans idToken -> logout doesn't work
https://github.com/keycloak/keycloak/blob/cf386efa40034ad788c265520316a1c30dfe30da/adapters/oidc/js/src/keycloak.js#L660

**Comment by lexcao** [comment]
Hi, seems there is an issue https://github.com/keycloak/keycloak/issues/12002 recently.
And is fixed by https://github.com/keycloak/keycloak/pull/12202.

**Comment by jonkoops** [comment]
This was fixed under #12202. Closing.
