### ISSUE TITLE
DELETE user api uses inefficient SQL queries while deleting data from OFFLINE_CLIENT_SESSION 

### ISSUE THREAD

**Issue by ashishtchaudhari** [keycloak/keycloak#12523]
### Describe the bug

Environment details.
Keycloak : version 15
Database : MySQL Aurora Serverless v1
USER_ENTITY Size: 30 million + rows
OFFLINE_CLIENT_SESSION Size : 10 million + rows

Problem Statement:
When a DELETE USER api is used to delete a user. It looks like following SQL query is executed to delete offline session details from OFFLINE_CLIENT_SESSION table.

![image](https://user-images.githubusercontent.com/40871388/173823077-eb69a9af-55d7-492b-a660-7ea5e7896616.png)

This query uses IN subquery, due to which MySQL ignores the indexes on the table. 
![image](https://user-images.githubusercontent.com/40871388/173825234-0f690476-682b-4af3-a6fe-18f35fa1453a.png)

It can be seen that the query takes more than 6 minutes to complete. During this duration, this can cause some database table locking, which would result in failure of issuing tokens or updating the refresh time of the session in the table.

The queries when ran independently (without subquery) runs within few milliseconds.
![image](https://user-images.githubusercontent.com/40871388/173825800-8f6d6290-7445-4821-8e75-c0867728711d.png)

Suggested approach:
If instead of using a sub-query, if the two queries are executed separately. i.e.
a. Get the session IDs using the Select query first
b. Run the delete query with result set of  'a'. Then this can speed up the deletions to a very large extent.

I believe this should be a small change and can help to improve the performance to a great extent. 

### Version

15

### Expected behavior

On the call of Delete User, the Delete user should be completed quickly and should not time out or take time like 300+ seconds.

### Actual behavior

The delete user operation times out or take large time for completion.

### How to Reproduce?

Try deleting the user from a Keycloak when Offline sessions are enabled and the table has more than 1 million rows.

**Comment by lexcao** [comment]
Hi, it is fixed by https://github.com/keycloak/keycloak/pull/8415.
But it is not fixed for version 15 you are using.

There is a workaround for you to customize 15 version.
* by just convert sub-query to join-query
```java
// org/keycloak/models/jpa/session/JpaUserSessionPersisterProvider.java
// ...
private final static String DELETE_EXPIRED_CLIENT_SESSIONS = "DELETE `client` " +
    "FROM `OFFLINE_CLIENT_SESSION` `client` " +
    "JOIN `OFFLINE_USER_SESSION` `user` " +
    "WHERE `client`.`USER_SESSION_ID` = `user`.`USER_SESSION_ID` " +
    "      AND `user`.`REALM_ID` = :realmId " +
    "      AND `user`.`OFFLINE_FLAG` = :offline " +
    "      AND `user`.`LAST_SESSION_REFRESH` < :lastSessionRefresh ";
// ...
public void removeExpired(RealmModel realm) {
  // ...
  // - cs = em.createNamedQuery("deleteExpiredClientSessions")
  int cs = em.createNativeQuery(DELETE_EXPIRED_CLIENT_SESSIONS)
  // ...
}
```

**Comment by ashishtchaudhari** [comment]
@lexcao  - can you please confirm the version of Keycloak in which this is fixed ?

**Comment by lexcao** [comment]
Hi, @ashishtchaudhari 
I found it was fixed on `15.1.0` from [KEYCLOAK-18842](https://issues.redhat.com/projects/KEYCLOAK/issues/KEYCLOAK-18842).

**Comment by ashishtchaudhari** [comment]
Thanks @lexcao . I am open to upgrade my Keycloak to version that remediates this probem.

I see that the fix was for deleteExpiredClientSessions. However, my situation seems to be for deleteClientSessionsByUser or deleteClientSessionsByRealm. If I have to update the query for these two Named queries, can you please guide me, what approach should I use, with Keycloak 16, to solve this problem.

**Comment by lexcao** [comment]
Hi, @ashishtchaudhari
You are right, it only solves `deleteExpiredClientSessions`.
I'm glad to help with you.

The Customization has two steps:
1. convert sub-query to join-query
2. replace `createNamedQuery` to `createNativeQuery`

e.g: `deleteClientSessionsByUser`
```java
//  in JpaUserSessionPersisterProvider.java
private final static String DELETE_CLIENT_SESSIONS_BY_USER = "DELETE `client`" +
    "FROM `OFFLINE_CLIENT_SESSION` `client`" +
    "JOIN `OFFLINE_USER_SESSION` `user`" +
    "WHERE `client`.`USER_SESSION_ID` = `user`.`USER_SESSION_ID`" +
    "      AND `user`.`USER_ID` = :userId";
// ..
private void onUserRemoved(RealmModel realm, String userId) {
  em.createNativeQuery(DELETE_CLIENT_SESSIONS_BY_USER)
    .setParameter("userId", userId).executeUpdate();
  // ...
}
```

You can convert `deleteClientSessionsByRealm` from above way as well by yourself.

If you need any help, feel free to ping me.

**Comment by ashishtchaudhari** [comment]
Thank again for the clarity.

I have few points here.
a. Can this be picked up as a defect and fixed in the solution ?
b. Can all the named queries be put into configuration files, like done for deleteExpiredClientSessions ?
c. If I have to temporarily fix this in my setup, what would be the procedure for me to build the code again ? Will it be risky to use the local fix in production ?

Regards,
Ashish Choudhari

**Comment by lexcao** [comment]
Hi, It's hard to say.

Re a:
It could be a defect, I think.

Re b:
Yes, it can be put into configuration file, currently it's in
```
model/jpa/src/main/resources/META-INF/queries-default.properties
// queries-mariadb.properties
// queries-mysql.properties
```

Re c:
It's hard to guide how to build for production by some locally modification in this short comment.
> Will it be risky to use the local fix in production ?
No, I use local fix in my production, it works normal.

---
I am trying to make a PR to convert sub-query to join-query in configuration.

**Comment by ashishtchaudhari** [comment]
@lexcao  -- Your help so far is greatly appreciated. Thanks for taking out your time to guide me.
For point b:
With my version upgraded to Keycloak 16, can I update the queries by just updating queries-mysql.properites (I use MYSQL) or I will also have to update the java file ?
Can I know the name of the jar file that will contain this properties file ?

**Comment by lexcao** [comment]
Hi @ashishtchaudhari , sorry for the late response.
From a test on my local, I found there is no need to comment out the code of `@NamedQuery`.
Just adding SQL to the properties file fits the needs.
(You can try it on your local first, I think)

The properties file is located on
```
model/jpa/src/main/resources/META-INF/queries-mysql.properties
```

**Comment by ashishtchaudhari** [comment]
@lexcao  -- Sorry for asking primitive question. But, can you please tell me which jar file contains this properties file ?

**Comment by ashishtchaudhari** [comment]
Thanks, I will check.

**Comment by sguilhen** [comment]
Looks valid to me given a- the slow performance of sub-query with deletion on MySQL/MariaDB and b- existing similar fix for `deleteExpiredClientSessions`

**Comment by lexcao** [comment]
Hi, @ashishtchaudhari 
The PR(#12611) has merged and this will be fixed in the next release.
