### ISSUE TITLE
The links to install the operator defined in the documentation do not work.

### ISSUE THREAD

**Issue by johnpptz** [keycloak/keycloak#12557]
### Describe the bug

The links to install the operator defined in the documentation do not work.
https://www.keycloak.org/operator/installation

Links for  CRDs return status 404
https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.1/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.1/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml

Link for operator returns status 404
https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.1/kubernetes/kubernetes.yml

### Version

18.0.1

**Comment by andreaTP** [comment]
This PR needs to be merged:
https://github.com/keycloak/keycloak-k8s-resources/pull/5

**Comment by DGuhr** [comment]
PR is merged and links are working again. closing here :)
