### ISSUE TITLE
Review RollingUpdate settings for the Deployment

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#12558]
### Description

Takeaway from the discussion: https://github.com/keycloak/keycloak/discussions/11763

`RollingUpdate` should delete max 1 pod at a time to keep in a consistent state the embedded Infinispan.

**Comment by sschu** [comment]
@andreaTP This is not sufficient to resolve the Infinispan issues scaling up and down, see my remark here https://github.com/keycloak/keycloak/pull/12447#issuecomment-1161317869.
