### ISSUE TITLE
Keycloak accepts a client scope name that violates OAuth2.0 scope-token definition rule

### ISSUE THREAD

**Issue by ynojima** [keycloak/keycloak#12553]
### Describe the bug

Keycloak accepts a client scope name that violates the OAuth2.0 scope-token definition rule.

OAuth2.0 specification defines scope and scope-token format in this way in ABNF notation,
```
     scope       = scope-token *( SP scope-token )
     scope-token = 1*( %x21 / %x23-5B / %x5D-7E )
```
https://datatracker.ietf.org/doc/html/rfc6749#section-3.3

but Keycloak accepts "(double-quote) or multi-bytes characters.
This may break interoperability with other OAuth2 implementations.

### Version

18.0.0

### Expected behavior

client scope name should be validated against the OAuth2.0 specification rule during creation.

### How to Reproduce?

Create a client scope with a name "マルチバイト文字(multi bytes characters)" from the Admin console.

**Comment by lexcao** [comment]
Hi, I have created a PR to fix it.
https://github.com/keycloak/keycloak/pull/12571
