### ISSUE TITLE
SQLGrammarException would occur if a user doesn't belong to any groups

### ISSUE THREAD

**Issue by jichen-amplify** [keycloak/keycloak#12567]
### Describe the bug

In the case where a user does not belong to any groups, the following two places would result in `org.hibernate.exception.SQLGrammarException`.

* https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L468
* https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L482

The reason being that when a user doesn't belong to any groups, `ids` would be an empty stream. When that is being used with the IN operator in a named query such as [getGroupIdsFromIdList](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java#L35), it would result in a SQL predicate like this `IN ()`, which is not a valid syntax (at least according to Postgres).

### Version

12.0.4

**Comment by lexcao** [comment]
Hi, I am facing the same issue as well on keycloak 15.0.2.
I think you can make a PR to fix it by just returning `Stream.empty()` when the `ids` is empty.

I am willing to help you if you need. 😃
