### ISSUE TITLE
No secret provided for dynamically registered client using client_secret_jwt method in Keycloak 18

### ISSUE THREAD

**Issue by carlosli888** [keycloak/keycloak#12565]
### Describe the bug

I am trying to register clients dynamically as per https://openid.net/specs/openid-connect-registration-1_0.html, but I noticed that I am not able to get the client secret upon registration when I use `client_secret_jwt` method.  A secret is returned, however, if I use `client_secret_basic`.

### Version

18

### Expected behavior

A successful response message that includes the client secret when I use `client_secret_jwt`.

### Actual behavior

After sending a request to dynamically register a confidential client, I get a successful response message.  However, this message does not include the client secret.

### How to Reproduce?

1. Send a HTTP POST request to the OIDC registration endpoint (e.g., https://localhost:8443/realms/wenco/clients-registrations/openid-connect) using the payload below:
```json
{
  "software_id": "backend.client_secret_jwt",
  "redirect_uris": [],
  "grant_types": [
    "client_credentials"
  ],
  "application_type": "native",
  "client_name": "backend-client-secret-jwt-01",
  "token_endpoint_auth_method": "client_secret_jwt",
  "token_endpoint_auth_signing_alg": "HS384",
  "response_types": []
}
```
2. Analyze the response received (see below) and notice that there is no client secret.
```json
{
  "redirect_uris": [],
  "token_endpoint_auth_method": "client_secret_jwt",
  "token_endpoint_auth_signing_alg": "HS384",
  "grant_types": [
    "authorization_code",
    "client_credentials"
  ],
  "response_types": [
    "code",
    "none"
  ],
  "client_id": "02698813-1c42-44b8-9b70-925e18119a41",
  "client_name": "backend-client-secret-jwt-01",
  "scope": "address phone offline_access microprofile-jwt",
  "subject_type": "public",
  "request_uris": [],
  "tls_client_certificate_bound_access_tokens": false,
  "client_id_issued_at": 1655488614,
  "registration_client_uri": "https://localhost:8443/realms/wenco/clients-registrations/openid-connect/02698813-1c42-44b8-9b70-925e18119a41",
  "registration_access_token": "eyJhbGci[… omitted for brevity …]jkifQ.eyJleHAiOj[… omitted for brevity …]vdXMifQ.0xlRk[… omitted for brevity …]3C7Q",
  "backchannel_logout_session_required": false,
  "require_pushed_authorization_requests": false,
  "frontchannel_logout_session_required": false
}
```

### Anything else?

If I change the request to use `client_secret_basic` instead of `client_secret_jwt`, a secret is returned.

**Request**
```json
{
  "software_id": "backend.client_secret_basic",
  "software_version": "0.1.0",
  "redirect_uris": [],
  "grant_types": [
    "client_credentials"
  ],
  "application_type": "native",
  "client_name": "backend-client-secret-basic-01",
  "token_endpoint_auth_method": "client_secret_basic",
  "response_types": []
}
```

**Response**

```json
{
  "redirect_uris": [],
  "token_endpoint_auth_method": "client_secret_basic",
  "grant_types": [
    "authorization_code",
    "client_credentials"
  ],
  "response_types": [
    "code",
    "none"
  ],
  "client_id": "37853133-8913-4787-b240-7e917bad2d91",
  "client_secret": "lQpR9La6p92JhPrRDMopvnhleWT26uom",
  "client_name": "backend-client-secret-basic-01",
  "scope": "address phone offline_access microprofile-jwt",
  "subject_type": "public",
  "request_uris": [],
  "tls_client_certificate_bound_access_tokens": false,
  "client_id_issued_at": 1655420325,
  "client_secret_expires_at": 0,
  "registration_client_uri": "https://localhost:8443/realms/wenco/clients-registrations/openid-connect/37853133-8913-4787-b240-7e917bad2d91",
  "registration_access_token": "eyJhbG[… omitted for brevity …]iZmIyNjkifQ.eyJleHAiOjAsI[… omitted for brevity …]dXMifQ.kp-KbQDX[… omitted for brevity …]95YXcGny4",
  "backchannel_logout_session_required": false,
  "require_pushed_authorization_requests": false,
  "frontchannel_logout_session_required": false
}
```

**Comment by lexcao** [comment]
Hi team, with [Client Registration Response](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse) from oidc protocol, I found that
>  client_secret, OPTIONAL

There is no restriction for adding `client_secret` in response from the docs.

And there are both `alg` and `client_secret` shown on admin console when using `client_secret_jwt`.

For the consistency, I think it is great to add `client_secret` in response when using `client_secret_jwt`.

Before I start coding, I'd like the team to help me check if this change meets expectations.

org/keycloak/services/clientregistration/oidc/DescriptionConverter.java:329
```
if (client.getClientAuthenticatorType()
    .equals(ClientIdAndSecretAuthenticator.PROVIDER_ID)) {
    // set client secret here
}
```

I am going to add `client_secret_jwt` type for returning client secret here.

**Comment by carlosli888** [comment]
@lexcao,
Thank you for looking into this.  I think that sending a secret back for `client_secret_jwt` makes sense.  I interpret: "It is not needed for Clients selecting a token_endpoint_auth_method of private_key_jwt unless symmetric encryption will be used" (from [Client Registration Response](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse)) to mean that the client_secret is required since client_secret_jwt uses symmetric encryption based on the secret key.

**Comment by mposolda** [comment]
It is possible that this is partially fixed in latest keycloak main due the https://github.com/keycloak/keycloak/pull/12195#issuecomment-1159128446 , however not sure. It seems the issue might be the check in the `DescriptionConverter.toExternalResponse`, which may need to be updated.

I am adding label `help wanted`, so ayone is welcome to look into this and send the PR with the fix.
