### ISSUE TITLE
Pre-selected Client ID is not correctly assigned on creation of user federation mapper 

### ISSUE THREAD

**Issue by vrindanayak** [keycloak/keycloak#12579]
### Describe the bug

On creating a new mapper for LDAP User Federation with _Use Realm Roles Mapping_ as _OFF_, the pre-selected _Client ID_ which defaults to _account_ is not sent in the request payload on saving the configurations. 
User has to select some other value from _Client ID_ dropdown and re-select _account_ again for it to be effective.

### Version

Keycloak 18.0.0

### Expected behavior

Pre-selected _account_ value in _Client ID_ dropdown should be effective by default if _Use Realm Role Mappings_ is set to _OFF_

![account-role-mapper-success](https://user-images.githubusercontent.com/15785031/174493423-a644f030-e7ab-4b76-b23b-29e0076a7f25.png)

Request payload json
````
{"config":{"roles.dn":["ou=account,dc=dcm4che,dc=org"],"role.name.ldap.attribute":["cn"],"role.object.classes":["groupOfNames"],"membership.ldap.attribute":["member"],"membership.attribute.type":["DN"],"membership.user.ldap.attribute":["uid"],"roles.ldap.filter":[],"mode":["LDAP_ONLY"],"user.roles.retrieve.strategy":["LOAD_ROLES_BY_MEMBER_ATTRIBUTE"],"memberof.ldap.attribute":["memberOf"],"use.realm.roles.mapping":["false"],"client.id":["account"]},"name":"account2","providerId":"role-ldap-mapper","providerType":"org.keycloak.storage.ldap.mappers.LDAPStorageMapper","parentId":"4415d8f0-90dd-43ad-bbd2-318b9ed22db7"}
````

### Actual behavior

Pre-selected _account_ value in _Client ID_ dropdown is not effective by default if _Use Realm Role Mappings_ is set to _OFF_

![account-role-mapper_failure](https://user-images.githubusercontent.com/15785031/174493479-c5c901fe-16cf-4b3b-87e5-8475592d61ab.png)

Request payload json

````
{"config":{"roles.dn":["ou=account,dc=dcm4che,dc=org"],"role.name.ldap.attribute":["cn"],"role.object.classes":["groupOfNames"],"membership.ldap.attribute":["member"],"membership.attribute.type":["DN"],"membership.user.ldap.attribute":["uid"],"roles.ldap.filter":[],"mode":["LDAP_ONLY"],"user.roles.retrieve.strategy":["LOAD_ROLES_BY_MEMBER_ATTRIBUTE"],"memberof.ldap.attribute":["memberOf"],"use.realm.roles.mapping":["false"],"client.id":[]},"name":"account2","providerId":"role-ldap-mapper","providerType":"org.keycloak.storage.ldap.mappers.LDAPStorageMapper","parentId":"4415d8f0-90dd-43ad-bbd2-318b9ed22db7"}
````

### How to Reproduce?

- Create ldap User Federation
- Create _role-ldap-mapper_ with _Use Realm Role Mappings_ as _OFF_ and other bind DN details as required.
- _Client ID_ dropdown shows _account_ as pre-selected client. Leave this value as it is and _Save_

**Comment by ssilvert** [comment]
Hi @vrindanayak.  

I just verified that this does work on the new admin console.  Since the new console does not pre-select a client, it will work as expected.

We will not be fixing this in the old console as it is being deprecated.
