### ISSUE TITLE
"Email as username" option shouldn't be visible/hidden dependent on "User registration"

### ISSUE THREAD

**Issue by jblachly** [keycloak/keycloak#12573]
### Describe the bug

The boolean option "email as username" affects several parts of the keycloak experience:
 1. user self-registration
 2. user login
 3. admin interface: adding new users
 4. admin interface: viewing all users (although whether the "username" column is shown here is also dependent on whether any existing users have a username but no email set, so we will disregard this for purpose of this issue report)

This setting is accessible in Realm Settings > Login tab.

However, it's hidden (gated) until "User registration" is set to "on."

Importantly, its effects on (2) user login and (3) the admin interface add new user exist _independent_ of the "user self-registration" setting, and its effects persist even when it is hidden in the admin UI.

### Version

18.0.0

### Expected behavior

The "email as username" option should be always visible in the Realm settings > Login tab

### Actual behavior

The "email as username" slider disappears when "user registration is set to "off" (however, the email as username toggle remembers its value , and exerts its side effects, even when hidden in the UI)

### How to Reproduce?

# Baseline

Create new realm

Go to realm settings (sidebar) > login tab

Observe no "email as username setting".

Go to Users (sidebar) > Add user button

Observe: mandatory username field; optional email field.

Return to realm settings (sidebar) > login tab

Toggle "user registration"

Toggle "email as username"

(Save)

Return to Users (sidebar) > add user button

Note different appearance: no username field; mandatory email field

# Now observe that this setting exerts its side effect even when hidden

Return to realm settings (sidebar) > login tab

Toggle "user registration" ; note "email as username" toggle disappears

(Save)

Return to Users (sidebar) > add user button

Note that there is still no username field and a mandatory email field

**Comment by pedroigor** [comment]
I see. So the issue here is that the value set to `email as username` is not unset when you disable user registration.

In this case, I think we should make sure the option is disabled when registration is disabled.

@ssilvert Do you know if the new administration console behaves differently in this read?

**Comment by jblachly** [comment]
> In this case, I think we should make sure the option is disabled when registration is disabled.

@pedroigor respectfully disagree. I explicitly want self-registration disabled (we have our own user registration/sign-up application so we can pnopulate backend API database, billing information, etc.), but also need email as username.

The simplest fix, IMO, it to just leave "email as username" always visible.  It doesn't even have a logical relation to user self-registration anyway, does it?

**Comment by pedroigor** [comment]
@jblachly Historically, it has and that is why I'm not sure if we can just make it a top-level option. I see your point and I'm fine making it like so if others don't see any implication.

But the way it is now (not saying is correct), it looks like a UX issue. Mainly because you can set the two options separately if using the Admin API directly.

That is why I'm asking UI team feedback on this one.

**Comment by ssilvert** [comment]
We have an issue open for this in the repo for new admin ui: https://github.com/keycloak/keycloak-admin-ui/issues/1242

Erik did put out a request for comment but I don't think he got any response.  We will escalate the issue after Keycloak 19.

Glad to have the feedback above.

**Comment by ssilvert** [comment]
I bumped up the priority on the issue for the new admin console, https://github.com/keycloak/keycloak-ui/issues/1242

However, I'm going to go ahead and close this one because we aren't working on the old console any more.
