### ISSUE TITLE
Keycloak deployment in kubernetes has redirect uri error

### ISSUE THREAD

**Issue by hellobiek** [keycloak/keycloak#12574]
### Describe the bug

I deploy keycloak using 18.0.1 version(newest) using method: https://www.keycloak.org/getting-started/getting-started-kube

succussfully, I open the home page as belows.

![image](https://user-images.githubusercontent.com/2854520/174466813-818cc7e8-ce40-4dad-bb3b-58b8c2953f3a.png)

however, when I click to login to Administration Console. it failed and problem is as follows:

Invalid parameter: redirect_uri
![image](https://user-images.githubusercontent.com/2854520/174466917-56e0ad4a-6235-438a-9e48-77e6a8fd1cb3.png)

my keycloak conifg is as follows:

![image](https://user-images.githubusercontent.com/2854520/174466934-4f342d9c-c0db-42e5-ac02-a04cef4af92e.png)

### Version

18.01

### Expected behavior

using keycloak.

### Actual behavior

as describes.

### How to Reproduce?

re deploy

**Comment by XcrigX** [comment]
I ran into a similar problem with 18.0.0, for me it's working in 18.0.2.  In my case the issue was I was accessing keycloak from an internal hostname, but when logging in to the admin portal it was redirecting to my external/public hostname  with a redirect uri back to the internal causing the error. 

Between setting X_FORWARDED_HOST headers at the reverse proxy, the KC_HOSTNAME_ADMIN variable, and updating to 18.0.2 the problem has resolved. Not certain if your problem is the same, but posting in case it helps.

**Comment by hellobiek** [comment]
@XcrigX @DGuhr thank you all first, I change to 18.0.2 and set KC_HOSTNAME_ADMIN, I don't know how to set X_FORWARDED_HOST，but no use   at all.

But my condtion is not the same as  @XcrigX 

My traffic graph is as follows.
traffic --->  AWS-NLB  (tls termination here)  ---->  K8S Nginx Ingress    ----> keycloak service

My problem is I access keycloak using https://keyclock.XXX.com, and I can login the home page as follows.

![image](https://user-images.githubusercontent.com/2854520/179385533-c0bb67bc-403e-4927-bd80-40d8cf773adb.png)

but when I click the "Administration Console ", I encountered the "Invalid parameter: redirect_uri" error as follows 

![image](https://user-images.githubusercontent.com/2854520/179385573-08b1ea24-3495-4a30-a48c-44f54d6d48a8.png)

However, If I access keycloak using http://keyclock.XXX.com, I can login successed. as follows:
![image](https://user-images.githubusercontent.com/2854520/179385659-ee26c536-8be2-4c6c-ae4c-49188cf3ff1a.png)

**Comment by hellobiek** [comment]
@DGuhr so the key point is when I access the https://keycloak.XXX.com,  is there a method that can change the redirect url from https to http

**Comment by XcrigX** [comment]
What is the redirect URI that is invalid? You can see it either in the URL itself in the browser bar, or in chrome debug mode. That may help point to the problem. 

The reverse proxy and hostname guides may provide some clues/ideas as well : 
https://www.keycloak.org/server/reverseproxy
https://www.keycloak.org/server/hostname

But from my understanding, somewhere between the proxy mode, the various hostname variables, and (perhaps) the X_FORWARDED_XXX headers, Keycloak makes decisions about how to construct navigation and redirect URLs. 
And it seems Keycloak treats the administration endpoints differently than the authorization endpoints - the preference, or at least common configuration being that the admin endpoints are not exposed publicly. 

The X_FORWARDED_HOST and X_FORWARDED_PROTO http headers give a web app running on an private/internal network a way to how traffic actually came in so they can use that to construct correct navigation URIs from the perspective of the client - which is hitting a public endpoint the app is not necessarily aware of. 
You would set these at the gateway where traffic first comes in - whatever is accepting the traffic at https://keycloak.xxx.com. That would be your AWS-NLB if that is exposed to the internet, or your WAF/gateway if you are running one in front of your NLB. These headers would get set with the public hostname "keycloak.xxx.com" and "https". 

I am not certain if the X_FORWARDED_HOST and X_FORWARDED_PROTO headers are actually used by keycloak. It is not well documented, but they are mentioned in the reverse proxy guide - and this is precisely what they are typically used for. But with the addition of the KC_HOSTNAME_ADMIN variable in 18.0.2 (or 18.0.1?), I'm not certain if those headers are considered or not. 

Caveat: I'm not a keycloak expert, I just spent some time recently trying to get it working.

**Comment by pedroigor** [comment]
We introduced two options to set the base URL for frontend and admin URLs. Basically, they do not force you to configure your proxy to forward those headers because the scheme, host, and port, are inferred from the URL you set.

See https://github.com/keycloak/keycloak/issues/13524.
