### ISSUE TITLE
False implementation of SAML element EncryptionMethod

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#12585]
### Describe the bug

Schema Definition of [SAML element EncryptionMethod](https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#sec-EncryptionMethod) is : 

>   <complexType name='EncryptionMethodType' mixed='true'>
    <sequence>
      <element name='KeySize' minOccurs='0' type='xenc:KeySizeType'/>
      <element name='OAEPparams' minOccurs='0' type='base64Binary'/>
      <any namespace='##other' minOccurs='0' maxOccurs='unbounded'/>
    </sequence>
    <attribute name='Algorithm' type='anyURI' use='required'/>
  </complexType>

Keycloak only honors and parses KeySize and OAEPparams. If an EncryptionMethod exists with any other valid xml element, Keycloak throws a RuntimeException. Due to it, valid xml files can not be parsed and inserted as SAML Identity Provider or SAML Client. Examples can be found to https://md.aai.grnet.gr/feeds/edugain-samlmd.xml ( fe SP with entity id 'https://sam.ihsmarkit.com/sso/Ukfed-W228SA1MKb' ).

EncryptionMethod must be enhanced with a List<Object> any and SAMLEncryptionMethodParser must add in this least all xml elements expect from KeySize and OAEPparams.

### Version

16.1

### Expected behavior

Xml element must be parsed as any elemnt

### Actual behavior

A RuntimeExceptio is thrown.

### How to Reproduce?

Try to add entity with entity id 'https://sam.ihsmarkit.com/sso/Ukfed-W228SA1MKb' from https://md.aai.grnet.gr/feeds/edugain-samlmd.xml as SAML Client.

**Comment by avl-team-pandas** [comment]
Hello, I believe the same issue is preventing us from loading a SAML IdP setup via Entity Descriptor. Just to be sure, I'm going to describe the issue here and hope for some feedback.
Keycloak version: 20.0.2

Our SAML EntityDescriptor has EncryptionMethod section as follows in this code block:
```
<KeyDescriptor use="encryption">
  <ds:KeyInfo>
    <ds:X509Data>
      <ds:X509Certificate> ... </ds:X509Certificate>
    </ds:X509Data>
  </ds:KeyInfo>
  <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
  </EncryptionMethod>
  <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc">
    <xenc:KeySize>128</xenc:KeySize>
  </EncryptionMethod>
</KeyDescriptor>
```
Which results in an error with message "Unknown tag:DigestMethod"
The full error stack trace is available in the attached file.
[saml_error.txt](https://github.com/keycloak/keycloak/files/10345174/saml_error.txt)

When adding the SAML IdP manually through admin console, it works fine.

**Comment by cgeorgilakis** [comment]
@avl-team-pandas the solution for such cases is the [related PR](https://github.com/keycloak/keycloak/pull/12588).

Unfortunatelly, Keycloak does not honor [SAML element EncryptionMethod](https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/Overview.html#sec-EncryptionMethod). This cause the exception described by you.

**Comment by tpetillot** [comment]
Any update regarding this issue?
