### ISSUE TITLE
Unavailable Keycloak Backend Blocks Client 

### ISSUE THREAD

**Issue by Sazzels** [keycloak/keycloak#12581]
### Describe the bug

Using vuejs and trying to implement keycloak login. 
*package.json*
```json
"dependencies": {
  "core-js": "^3.22.5",
  "keycloak-js": "^18.0.0",
  "vue": "^3.2.33"
}
```
```javascript
// keycloakInitOptions 
const keycloakInitOptions = {
  onLoad: "login-required",
  checkLoginIframe: false,
};

const keycloak = new Keycloak(keycloakOptions); // *nothing special* URL, REALM, CLIENT_ID

// basic implementation (for testing)
keycloak
    .init(keycloakInitOptions)
    .then((res) => console.log(res))
    .catch((err) => console.error(err));
```

works when backend config is valid and server is reachable. 
As soon as i configure a non responding backend or i shutdown keycloak server the application is blocked and results in a `ERR_CONNECTION_TIMED_OUT`. 
Don't let me start with when i configure a page which has nothing todo with keycloak (like: google.de, reddit.com, example.com) then i get 404 pages from them (makes sense) but some kind of (is the backend a keycloak backend would be highly appriciated)

i got from a long list of issues and PR's which all mention that this is fixed, but unfortunately i'm still experiencing it.
Example: https://github.com/keycloak/keycloak/pull/7901#issuecomment-861592119

### Version

18.0.1

### Expected behavior

Error handling when network errors occur or backend is not a keycloak server.

### Actual behavior

application is blocked by this behavior.
* `ERR_CONNECTION_TIMED_OUT`

### How to Reproduce?

1. shutdown keycloak backend
2. configure non working backend URL in `keycloak-init-options`

**Comment by FabianAhammer** [comment]
Same problem facing this with:

- @angular/*@13.2.6
- keycloak-js@18.0.1
- keycloak-angular@10.0.2

**Comment by Sazzels** [comment]
@jonkoops any updates on this, is this fixed/better in current versions?

**Comment by jonkoops** [comment]
Not at this time, but feel free to submit a PR to fix this if you know how.

**Comment by jonkoops** [comment]
Re-opening this issue so that we don't lose track of it.

**Comment by jonkoops** [comment]
This issue has been fixed as we introduced a timeout on loading the iframe.
