### ISSUE TITLE
Read/write configuration for user profile also for username/email not possible

### ISSUE THREAD

**Issue by ioemat** [keycloak/keycloak#12599]
### Describe the bug

To allow keycloak to run as pure ID broker (no IDP functionality), we must be able to forbid the user from changing attributes coming from an external IDP.

The user profile does allow to configure this on a per-attribute basis, however this does currently not work for username and  email.

### Version

18.0

### Expected behavior

The administrator can configure permissions to all attributes (including username and email) in the user profile configuration UI.
This configuration is handled correctly by the Account API.

### Actual behavior

It's not possible to configure permissions on username and email attributes in the user profile configuration UI.
(The "Permissions" desctions is not available for these attributes.)

### How to Reproduce?

Enable declarative user profile by setting -Dkeycloak.profile.feature.declarative_user_profile=enabled.

* got to "Realm settings" and check "User Profile Enabled"
* switch to the "User Profile" tab and press the "Create" button to create a new attribute
* enter "username" or "email" as attribute name
* the "Permissions" section disappears in the moment the attribute name has been entered completely

### Anything else?

I'll provide a fix for this

**Comment by 0xpr03** [comment]
If anyone else if facing this: I blocked POST to `/realms/REALM/account` for now. As I don't want anything in the userprofile to be editable. (only sign-in stuff)
