### ISSUE TITLE
Policy enforcer does an extra call to keycloak server when evaluating RPT

### ISSUE THREAD

**Issue by GretUp** [keycloak/keycloak#12598]
### Describe the bug

When we add additional claims with a custom policy SPI to the authorization-permissions part of the RPT there is an extra call to keycloak server. My understanding is that if the policy enforcer evaluates a RPT it should be done without an extra call to the keycloak server. Evaluation of RPT should be done client side only.

### Version

18.0.0

### Expected behavior

No extra call to keycloak. At the moment RPT without extra claims works without an extra call to keycloak.

### Actual behavior

Extra call to keycloak.

### How to Reproduce?

Add additional claims to authorization-permissions part of the RPT.
"authorization": {
    "permissions": [
      {
        "scopes": [
          "view"
        ],
        "claims": {
          "country-view": [
            "[Belgium]"
          ],
        },
        "rsid": "1dd9ba94-6a16-487c-9279-4650d2187c8d",
        "rsname": "customers"
      },

**Comment by pedroigor** [comment]
@GretUp Thanks. It is expected in this case because you have claims within the permission and the PEP should make sure they are still valid.

**Comment by GretUp** [comment]
When I follow your logic then with or without claim the RPT should be validated, which does not make sense.
This means also serious performance degradation when each request to an endpoint needs to be validated. 
Can we have a chat on this?
