### ISSUE TITLE
SpringBoot PolicyEnforcer gives access denied on custom claim in RPT

### ISSUE THREAD

**Issue by shankaryadavy9** [keycloak/keycloak#12601]
### Describe the bug

Hi,

Added custom claim using javascript rule to push back extra info to the resource server for filtering. The evaluation API gives the expected success result but the Springboot adapter gives access denied.

{
  "exp": 1655733351,
  "iat": 1655733051,
  "jti": "468bee4c-395f-430b-856d-9ac205917fe0",
  "aud": "dummy",
  "sub": "f:345374dc-dfdf-43c4-8e5b-996075be8412:ET1024",
  "typ": "Bearer",
  "azp": "dummy",
  "session_state": "9905c2c9-aa5c-4722-b025-51418d7a4bf4",
  "allowed-origins": [
    "*"
  ],
  "resource_access": {
    "dummy": {
      "roles": [
              "user"
      ]
    }
  },
  "authorization": {
    "permissions": [
      {
        "scopes": [
          "view"
        ],
        **"claims": {
          "countries": [
            "IN",
            "US"
          ]
        },**
        "rsid": "49c7f215-c2e8-4fab-abce-b23bcd1dfbeb",
        "rsname": "Widgets"
      }
    ]
  },
  "scope": "email profile",
  "sid": "9905c2c9-aa5c-4722-b025-51418d7a4bf4",
  "email_verified": false,
  "name": "Dummy",
  "preferred_username": "ET1024",
  "locale": "en",
  "given_name": "Dummy",
  "family_name": "Dummy",
  "email": "Dummy@Dummy.com"
}

### Version

18.0.1

### Expected behavior

If evaluation API gives success RPT with extra claims, Springboot adapter should also evaluate to granted. 

### Actual behavior

The adapter gives access denied. If I remove the custom claim it gives success RPT.

### How to Reproduce?

Just add custom claim Using Javascript and attach the policy to any permission which gets called using the Springboot Keycloak adapter.

**Comment by shankaryadavy9** [comment]
Has anybody got a chance to look into it..?
Because of this limitation, we are not able to use data filtration using Authorization services.

**Comment by GretUp** [comment]
We are using keycloak as authorization service in a new major project. This is also a feature we need. Would be be nice if we can fix this issue soon.

**Comment by shankaryadavy9** [comment]
Hi @stianst 
 
 I am really not sure how bugs are being taken account.  I did not find any documentation as well regarding this process. 
 
But this particular bug (I suppose) giving me anxiety,  whether  should I go ahead with the adapter approach or not..?

Please put some lights on it.

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by shankaryadavy9** [comment]
Hi @stianst and @mposolda,

I hope you're both doing well. I wanted to highlight this  issue again! I noticed that the class PolicyEnforcer has been moved under the dependency 'keycloak-policy-enforcer', which I assume, will be actively maintained going forward.

My use case i.e.  leveraging dynamic custom claims from Keycloak as 'where clause' in resource servers for data filtration still valid! 

This is a feature I find incredibly powerful and valuable in Keycloak. However, the feature is currently not working as expected due to PEP (Policy Enforcement Point) side validation.

I'd like to understand your perspective on this issue. Is it possible to disable the validation on the PEP side to make this feature work as intended? If so, what are the potential implications or security considerations of doing so? I believe that allowing the dynamic custom claims to be used effectively can greatly enhance the flexibility and usefulness of Keycloak for many use cases.

Looking forward to your valuable insights and guidance on how to proceed. Thank you for your time and attention to this matter. 

![image](https://github.com/keycloak/keycloak/assets/43490933/51b6394e-c6ea-4113-9a2a-68fdbcfe4326)

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.

**Comment by shankaryadavy9** [comment]
Hi @stianst 

Totally understand about deprecation but I guess this below lib still be maintained actively..?

> <dependency>
    <groupId>org.keycloak</groupId>
    <artifactId>keycloak-policy-enforcer</artifactId>
    <version>24.0.2</version>
</dependency>

And this lib also has the same code that I explained above which does not allow me to use custom claims.
