### ISSUE TITLE
Role name containing ";"(semicolon) leads "Resource not found..." error in the admin console

### ISSUE THREAD

**Issue by ynojima** [keycloak/keycloak#12618]
### Describe the bug

When I create a role containing ";"(semicolon) in its name from the admin console, the admin console is redirected to the error page with a following error message:
```
Resource not found...

We could not find the resource you are looking for. Please make sure the URL you entered is correct.
Go to the home page »
```
But when I open the role list page, the role containing ";"(semicolon) in its name is shown there. It seems the role itself is created correctly, but the logic to redirect the page to the role details page after the role creation is broken.

When I open the "Users in Role" tab of the role, the same "Resource not found..." error message is shown.
There is something wrong too.

I found ";"(semicolon) had been prohibited in KEYCLOAK-12768, but the restriction is relaxed in KEYCLOAK-14038 again. 
https://issues.redhat.com/browse/KEYCLOAK-12768
https://issues.redhat.com/browse/KEYCLOAK-14038
So, just prohibiting the special characters in a role name is not an option.

### Version

RH-SSO 7.5.2, Keycloak 18.0.0

### How to Reproduce?

1. Create a role that contains ";" in its name from the admin console
2. the admin console is redirected to the error page with following message:
```
Resource not found...

We could not find the resource you are looking for. Please make sure the URL you entered is correct.
Go to the home page »
```
3. When I open the "Users in Role" tab of the role, the same error message is shown too.

**Comment by lexcao** [comment]
Hi, I test in my local Keycloak 18.  
And the error page is shown.
Seems it is not a safe URL encoded.
```
http://localhost:8080/admin/realms/lex/roles/test;/users?first=0&max=5
```
And if I replace `;` to `%3B`, it works as expected.
```
http://localhost:8080/admin/realms/lex/roles/test%3B/users?first=0&max=5
```

I have two proposals to solve this, which need the Keycloak team to confirm.

**Proposal A**
the role name should not contain special characters with restrictions like the name of client scope .

**Proposal B**
If allow `;`, we should use URL encoded role name for path parameter in the JS request.

I personally prefer proposal A, a valid role name is safe to use anywhere not just fix one place from the path parameter to use it.

**Comment by mposolda** [comment]
Closing as this is not an issue in latest Keycloak and latest admin console and hence should be OK in Keycloak 21. I've tried to create roles like `foo;bar` or `baz;`, but both can be fine to display in the new admin console (including their users).
