### ISSUE TITLE
WebAuthn tests are broken in GHA

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#12621]
### Describe the bug

This is caused by some chromedriver issues, see e.g.: https://github.com/vmuzikar/keycloak/runs/6981239474?check_suite_focus=true

### Version

main

**Comment by mabartos** [comment]
@vmuzikar Thanks for creating this issue. I'm aware that those tests don't pass within the GH actions when there are some changes made to the WebAuthn.
Those tests require Chrome browser and I'm about to fix the interoperability with it, but don't have time for it yet.

Related testing PR: https://github.com/keycloak/keycloak/pull/12201

**Comment by mabartos** [comment]
Should be resolved now.
