### ISSUE TITLE
Container build on Windows not working due to line-endings of .sh files (crlf)

### ISSUE THREAD

**Issue by ghost** [keycloak/keycloak#12629]
### Describe the bug

Building the quarkus-container on a windows maschine, it doesn't work directly due to wrong line-endings on the .sh script.

### Version

18.0.1

### Expected behavior

A fresh checkout and build should work also on windows when git is changing the line-endings. 

I suggest to add `*.sh text eol=lf` to the `.gitattributes` too.

**Comment by vmuzikar** [comment]
@ghost Thanks for reporting this! Unfortunately, we're unable to prioritize this issue. Although, we'd very much welcome a PR (with as minimum changes as possible :))!
