### ISSUE TITLE
Update loading Keycloak 16 to 18

### ISSUE THREAD

**Issue by taihoa** [keycloak/keycloak#12642]
### Describe the bug

I am doing version update for keycloak 16 to 18 on ECS AWS.
But when performing the update, an error arises that cannot successfully start the keycloak 18 container.

I have tested to simulate the update process on a local computer and found that when running 2 Keycloak containers at the same time, only the Keycloak 16 and 18 containers successfully start and the keycloak 18 container fails, generating errors like the log below. If I run 2 Keycloak containers 16 and 16 concurrently, I don't get this error.
This could be the reason why the update on AWS ECS fails.

Can anyone help me with this problem?

Logs:
`keycloak_16  | 04:39:54,283 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 69) WFLYUT0021: Registered web context: '/auth' for server 'default-server'
keycloak_16  | 04:39:54,428 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
keycloak_16  | 04:39:54,512 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
keycloak_16  | 04:39:54,519 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 16.0.0 (WildFly Core 15.0.1.Final) started in 67955ms - Started 692 of 978 services (686 services are lazy, pa
ssive or on-demand)
keycloak_16  | 04:39:54,527 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
keycloak_16  | 04:39:54,527 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
keycloak_18  | Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
keycloak_18  | -b 0.0.0.0
keycloak_18  | =========================================================================
keycloak_18  |
keycloak_18  |   Using MySQL database
keycloak_18  |
keycloak_18  | =========================================================================
keycloak_18  |
keycloak_18  | 04:40:00,014 INFO  [org.jboss.modules] (CLI command executor) JBoss Modules version 2.0.2.Final
keycloak_18  | 04:40:00,156 INFO  [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.13.Final
keycloak_18  | 04:40:00,169 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.4.0.Final
keycloak_18  | 04:40:00,343 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) starting
keycloak_18  | 04:40:00,462 INFO  [org.jboss.vfs] (MSC service thread 1-7) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
keycloak_18  | WARNING: An illegal reflective access operation has occurred
keycloak_18  | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-
integration-18.1.0.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
keycloak_18  | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
keycloak_18  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
keycloak_18  | WARNING: All illegal access operations will be denied in a future release
keycloak_18  | 04:40:01,361 INFO  [org.wildfly.security] (ServerService Thread Pool -- 18) ELY00001: WildFly Elytron version 1.19.0.Final
keycloak_18  | 04:40:02,589 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-5) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Use
d blank.
keycloak_18  | 04:40:02,612 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-8) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto
 generated on first use with a self-signed certificate for host localhost
keycloak_18  | 04:40:02,641 INFO  [org.jboss.as.patching] (MSC service thread 1-3) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
keycloak_18  | 04:40:02,829 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
keycloak_18  | 04:40:02,832 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) started in 2798ms - Started 49 of 72 services (24 services are lazy, passiv
e or on-demand) - Server configuration file in use: standalone.xml
keycloak_18  | The batch executed successfully
keycloak_18  | 04:40:03,064 INFO  [org.jboss.as] (MSC service thread 1-5) WFLYSRV0050: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) stopped in 16ms
keycloak_18  | 04:40:05,165 INFO  [org.jboss.modules] (CLI command executor) JBoss Modules version 2.0.2.Final
keycloak_18  | 04:40:05,277 INFO  [org.jboss.msc] (CLI command executor) JBoss MSC version 1.4.13.Final
keycloak_18  | 04:40:05,291 INFO  [org.jboss.threads] (CLI command executor) JBoss Threads version 2.4.0.Final
keycloak_18  | 04:40:05,488 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) starting
keycloak_18  | 04:40:05,621 INFO  [org.jboss.vfs] (MSC service thread 1-3) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
keycloak_18  | WARNING: An illegal reflective access operation has occurred
keycloak_18  | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-
integration-18.1.0.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
keycloak_18  | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
keycloak_18  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
keycloak_18  | WARNING: All illegal access operations will be denied in a future release
keycloak_18  | 04:40:06,632 INFO  [org.wildfly.security] (ServerService Thread Pool -- 21) ELY00001: WildFly Elytron version 1.19.0.Final
keycloak_18  | 04:40:08,355 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Use
d blank.
keycloak_18  | 04:40:08,366 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-7) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto
 generated on first use with a self-signed certificate for host localhost
keycloak_18  | 04:40:08,418 INFO  [org.jboss.as.patching] (MSC service thread 1-1) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
keycloak_18  | 04:40:08,632 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
keycloak_18  | 04:40:08,637 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) started in 3463ms - Started 49 of 79 services (31 services are lazy, passiv
e or on-demand) - Server configuration file in use: standalone-ha.xml
keycloak_18  | The batch executed successfully
keycloak_18  | 04:40:08,895 INFO  [org.jboss.as] (MSC service thread 1-3) WFLYSRV0050: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) stopped in 33ms
keycloak_18  | Setting JGroups discovery to JDBC_PING with properties {datasource_jndi_name=>java:jboss/datasources/KeycloakDS,info_writer_sleep_time=>500}
keycloak_18  | =========================================================================
keycloak_18  |
keycloak_18  |   JBoss Bootstrap Environment
keycloak_18  |
keycloak_18  |   JBOSS_HOME: /opt/jboss/keycloak
keycloak_18  |
keycloak_18  |   JAVA: java
keycloak_18  |
keycloak_18  |   JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
 --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-o
pens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.
util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED
keycloak_18  |
keycloak_18  | =========================================================================
keycloak_18  |
keycloak_18  | 04:40:16,112 INFO  [org.jboss.modules] (main) JBoss Modules version 2.0.2.Final
keycloak_18  | 04:40:16,905 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.13.Final
keycloak_18  | 04:40:16,917 INFO  [org.jboss.threads] (main) JBoss Threads version 2.4.0.Final
keycloak_18  | 04:40:17,083 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: Keycloak 18.0.0 (WildFly Core 18.1.0.Final) starting
keycloak_18  | 04:40:17,263 INFO  [org.jboss.vfs] (MSC service thread 1-2) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
keycloak_18  | WARNING: An illegal reflective access operation has occurred
keycloak_18  | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-
integration-18.1.0.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
keycloak_18  | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
keycloak_18  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
keycloak_18  | WARNING: All illegal access operations will be denied in a future release
keycloak_18  | 04:40:18,417 INFO  [org.wildfly.security] (ServerService Thread Pool -- 5) ELY00001: WildFly Elytron version 1.19.0.Final
keycloak_18  | 04:40:19,756 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
keycloak_18  | 04:40:19,780 INFO  [org.xnio] (MSC service thread 1-4) XNIO version 3.8.6.Final
keycloak_18  | 04:40:19,803 INFO  [org.xnio.nio] (MSC service thread 1-4) XNIO NIO Implementation Version 3.8.6.Final
keycloak_18  | 04:40:19,879 INFO  [org.jboss.remoting] (MSC service thread 1-2) JBoss Remoting version 5.0.24.Final
keycloak_18  | 04:40:19,893 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 38) WFLYCLINF0001: Activating Infinispan subsystem.
keycloak_18  | 04:40:19,899 INFO  [org.wildfly.extension.health] (ServerService Thread Pool -- 37) WFLYHEALTH0001: Activating Base Health Subsystem
keycloak_18  | 04:40:19,918 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 49) WFLYNAM0001: Activating Naming Subsystem
keycloak_18  | 04:40:19,973 INFO  [org.wildfly.extension.metrics] (ServerService Thread Pool -- 47) WFLYMETRICS0001: Activating Base Metrics Subsystem
keycloak_18  | 04:40:19,896 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 40) WFLYRS0016: RESTEasy version 4.7.4.Final
keycloak_18  | 04:40:19,930 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 32) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
keycloak_18  | 04:40:19,957 INFO  [org.jboss.as.connector] (MSC service thread 1-7) WFLYJCA0009: Starting Jakarta Connectors Subsystem (WildFly/IronJacamar 1.5.3.Final)
keycloak_18  | 04:40:19,973 INFO  [org.jboss.as.naming] (MSC service thread 1-5) WFLYNAM0003: Starting Naming Service
keycloak_18  | 04:40:19,978 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-8) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
keycloak_18  | 04:40:19,966 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 53) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger
for environments running multiple servers. Please make sure the attribute value is unique.
keycloak_18  | 04:40:20,013 INFO  [org.jboss.as.clustering.jgroups] (ServerService Thread Pool -- 42) WFLYCLJG0001: Activating JGroups subsystem. JGroups version 4.2.20
keycloak_18  | 04:40:20,012 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 39) WFLYIO001: Worker 'default' has auto-configured to 8 IO threads with 64 max task threads based on your 4 availa
ble processors
keycloak_18  | 04:40:20,021 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-5) WFLYJCA0018: Started Driver service with driver-name = h2
keycloak_18  | 04:40:20,188 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0003: Undertow 2.2.16.Final starting
keycloak_18  | 04:40:20,228 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 32) WFLYJCA0005: Deploying non-JDBC-compliant driver class com.mysql.cj.jdbc.Driver (version 8
.0)
keycloak_18  | 04:40:20,279 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0018: Started Driver service with driver-name = mysql
keycloak_18  | 04:40:20,308 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Use
d blank.
keycloak_18  | 04:40:20,343 WARN  [org.wildfly.clustering.web.undertow] (ServerService Thread Pool -- 54) WFLYCLWEBUT0007: No routing provider found for default-server; using legacy provider based on static
 configuration
keycloak_18  | 04:40:20,367 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-6) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto
 generated on first use with a self-signed certificate for host localhost
keycloak_18  | 04:40:20,494 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 16 (per class), which is derived from the number o
f CPUs on this host.
keycloak_18  | 04:40:20,498 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 64 (per class), which is derived from thread work
er pool sizing.
keycloak_18  | 04:40:20,503 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 54) WFLYUT0014: Creating file handler for path '/opt/jboss/keycloak/welcome-content' with options [directory-
listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
keycloak_18  | 04:40:20,528 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0012: Started server default-server.
keycloak_18  | 04:40:20,530 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) Queuing requests.
keycloak_18  | 04:40:20,546 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0018: Host default-host starting
keycloak_18  | 04:40:20,728 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0006: Undertow AJP listener ajp listening on 0.0.0.0:8009
keycloak_18  | 04:40:20,733 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080
keycloak_18  | 04:40:20,743 INFO  [org.jboss.modcluster] (ServerService Thread Pool -- 56) MODCLUSTER000001: Initializing mod_cluster version 1.4.4.Final
keycloak_18  | 04:40:20,787 INFO  [org.jboss.modcluster] (ServerService Thread Pool -- 56) MODCLUSTER000032: Listening to proxy advertisements on /224.0.1.105:23364
keycloak_18  | 04:40:20,919 INFO  [org.jboss.as.ejb3] (MSC service thread 1-1) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
keycloak_18  | 04:40:21,036 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0006: Undertow HTTPS listener https listening on 0.0.0.0:8443
keycloak_18  | 04:40:21,090 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
keycloak_18  | 04:40:21,093 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-3) WFLYJCA0001: Bound data source [java:jboss/datasources/KeycloakDS]
keycloak_18  | 04:40:21,268 INFO  [org.jboss.as.patching] (MSC service thread 1-3) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
keycloak_18  | 04:40:21,283 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-5) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
keycloak_18  | 04:40:21,295 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
keycloak_16  | 04:40:22,465 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_16  | 04:40:22,470 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN100000: Node 5ab8044263c2 joined the cluster
keycloak_16  | 04:40:22,473 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_16  | 04:40:22,474 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN100000: Node 5ab8044263c2 joined the cluster
keycloak_16  | 04:40:22,477 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_16  | 04:40:22,482 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN100000: Node 5ab8044263c2 joined the cluster
keycloak_16  | 04:40:22,483 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_16  | 04:40:22,485 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN100000: Node 5ab8044263c2 joined the cluster
keycloak_16  | 04:40:22,487 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_16  | 04:40:22,489 INFO  [org.infinispan.CLUSTER] (thread-5,null,6d715b718af5) ISPN100000: Node 5ab8044263c2 joined the cluster
keycloak_18  | 04:40:23,307 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 58) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
keycloak_18  | 04:40:23,373 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 60) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.spi.marshalling.InfinispanProtoStreamMa
rshaller'
keycloak_18  | 04:40:23,374 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 59) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.spi.marshalling.InfinispanProtoStreamMa
rshaller'
keycloak_18  | 04:40:23,376 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 58) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.marshalling.jboss.JBossMarshaller'
keycloak_18  | 04:40:23,378 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 61) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.spi.marshalling.InfinispanProtoStreamMa
rshaller'
keycloak_18  | 04:40:23,379 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 56) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.marshalling.jboss.JBossMarshaller'
keycloak_18  | 04:40:23,606 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 60) ISPN000078: Starting JGroups channel `ejb`
keycloak_18  | 04:40:23,608 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 56) ISPN000078: Starting JGroups channel `ejb`
keycloak_18  | 04:40:23,606 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 58) ISPN000078: Starting JGroups channel `ejb`
keycloak_18  | 04:40:23,608 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 61) ISPN000078: Starting JGroups channel `ejb`
keycloak_18  | 04:40:23,609 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 59) ISPN000078: Starting JGroups channel `ejb`
keycloak_18  | 04:40:23,617 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 61) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_18  | 04:40:23,617 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 60) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_18  | 04:40:23,618 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 58) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_18  | 04:40:23,617 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 56) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_18  | 04:40:23,621 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 59) ISPN000094: Received new cluster view for channel ejb: [6d715b718af5|1] (2) [6d715b718af5, 5ab8044263c2]
keycloak_18  | 04:40:23,641 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 56) ISPN000079: Channel `ejb` local address is `5ab8044263c2`, physical addresses are `[172.20.0.4:7600]`
keycloak_18  | 04:40:23,642 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 61) ISPN000079: Channel `ejb` local address is `5ab8044263c2`, physical addresses are `[172.20.0.4:7600]`
keycloak_18  | 04:40:23,647 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 60) ISPN000079: Channel `ejb` local address is `5ab8044263c2`, physical addresses are `[172.20.0.4:7600]`
keycloak_18  | 04:40:23,652 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 59) ISPN000079: Channel `ejb` local address is `5ab8044263c2`, physical addresses are `[172.20.0.4:7600]`
keycloak_18  | 04:40:23,656 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 58) ISPN000079: Channel `ejb` local address is `5ab8044263c2`, physical addresses are `[172.20.0.4:7600]`
keycloak_16  | 04:40:24,226 INFO  [org.infinispan.CLUSTER] (thread-12,ejb,6d715b718af5) [Context=org.infinispan.CONFIG] ISPN100002: Starting rebalance with members [6d715b718af5, 5ab8044263c2], phase READ_O
LD_WRITE_ALL, topology id 2
keycloak_18  | 04:40:24,227 ERROR [org.infinispan.CLUSTER] (thread-10,ejb,5ab8044263c2) ISPN000474: Error processing request 0@6d715b718af5: java.lang.ClassCastException: class [I cannot be cast to class ja
va.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:405)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:390)
keycloak_18  |  at org.infinispan.commons@13.0.8.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.commands.topology.TopologyUpdateStableCommand.readFrom(TopologyUpdateStableCommand.java:88)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1449)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1389)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:144)
keycloak_18  |  at org.infinispan@13.0.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1562)
keycloak_18  |  at org.jgroups//org.jgroups.JChannel.up(JChannel.java:780)
keycloak_18  |  at org.jgroups//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
keycloak_18  |  at org.jgroups//org.jgroups.stack.Protocol.up(Protocol.java:309)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.FORK.up(FORK.java:142)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.Discovery.up(Discovery.java:300)
keycloak_18  |  at org.jgroups//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
keycloak_18  |  at org.jgroups//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
keycloak_18  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak_18  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak_18  |  at org.jboss.as.clustering.common@26.1.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
keycloak_18  |  at org.jboss.as.clustering.common@26.1.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
keycloak_18  |  at java.base/java.lang.Thread.run(Thread.java:829)`

### Version

18.0.0

**Comment by stianst** [comment]
It is not possible to run two different versions of Keycloak in the same cluster currently. Nor, is it supported to have two different versions of Keycloak pointing to the same database at the same time. This is planned to be improved in the new store, which will support seamless upgrades without downtime, but in the meantime you either need to stop all old instances before upgrading, or you need to build out a blue/green style deployment, which is quite a lot of work to be able to do.
