### ISSUE TITLE
Smartcard sets Username - can't login with UserName/Password (Other Login Method)

### ISSUE THREAD

**Issue by robson90** [keycloak/keycloak#12646]
### Describe the bug

If the user presents the smartcard when logging in, but then decides to use a different authentication method (username/password via "Other login method"), the login UI automatically no longer offers the option of entering a username. Only the field "Password" appears.

Smartcard is presented and I want to login:
![screenshot_20220603_131620-other-login-method](https://user-images.githubusercontent.com/39960884/174999105-f90420ff-def1-4f41-b21e-b5d0349b07dc.png)

I choose the Login Methods:
![screenshot_20220603_131650-login-options](https://user-images.githubusercontent.com/39960884/174999243-d79679eb-1b38-4bc0-95c1-d577af2a06fa.png)

Username is set by presented smartcard and is not changeable.
![screenshot_20220603_131741-username-is-set-automatically](https://user-images.githubusercontent.com/39960884/174999291-d434bd3f-9d5d-49ba-aba4-075faad92e65.png)

### Version

17.0.1

### Expected behavior

I should be able to change the Username and login via Username and Password, even if the smartcard is presented.

### Actual behavior

Username is not editable, only the Password. Username is set by smartcard.

I have to disconnect the smartcard.

### How to Reproduce?

SetUp Keycloak to work with smartcards. Insert smartcard, go to Keycloak Login Page, and choose "Other login method". Then your Username will be set and is not editable.

### Anything else?

Similar Issues:

https://issues.redhat.com/browse/KEYCLOAK-18905
https://github.com/keycloak/keycloak/pull/9580
https://github.com/keycloak/keycloak/issues/9498

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to investigate this and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .
