### ISSUE TITLE
Logo/Policy/ToS URLs to be added to REST API

### ISSUE THREAD

**Issue by senyahnoj** [keycloak/keycloak#12676]
### Description

On Keycloak 16.1.1 there are 3 new useful URL fields which are added to a client record

![Screenshot from 2022-06-23 10-02-10](https://user-images.githubusercontent.com/5585851/175266170-fd7838bc-5b0d-4d9e-8db8-1f072633bd15.png)

* Logo URL
* Policy URL
* Terms of service URL

However, none of these appear to be present in the REST API https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_clientrepresentation

### Discussion

https://github.com/keycloak/keycloak/discussions/12674

### Motivation

In the interests of automation, it would good if everything one can set via the admin console is available in the REST API

### Details

It would be good to be able to set these 3 URLS in

* POST /{realm}/clients
* PUT /{realm}/clients/{id}

And retrieve these 3 URLS in

* GET /{realm}/clients
* GET /{realm}/clients/{id}

**Comment by rmartinc** [comment]
Hi @senyahnoj!

I think that the new fields are just `attributes` inside the client. So you can modify then just as any other attribute. The values are `logoUri`, `policyUri`and `tosUri`. For example using `kcadm`:

```
./kcadm.sh update clients/dc286802-cf11-4ca4-8286-ebf1aa9bc627 -s 'attributes.logoUri=http://example.com/logo'
./kcadm.sh get clients/dc286802-cf11-4ca4-8286-ebf1aa9bc627 | jq .attributes.logoUri
"http://lala/logo"
```

In general, if you see the console is doing it there is an endpoint that performs the change. You can use the web developer tools to see what he console is calling and the json format used.

Hope that helps!

**Comment by senyahnoj** [comment]
Aha - missed these. Thank you!
