### ISSUE TITLE
SAML Signature Key Name does not set up via GUI or import

### ISSUE THREAD

**Issue by lamenawuer** [keycloak/keycloak#12681]
### Describe the bug

When setting up the flag "SAML Signature Key Name " in a saml client, either in a newly created one or in an imported one, they key does not set up. When retrieving the json descriptor via the admin-cli this flag does not appear, and the SAML connection fails. 

Although when using the terraform provider to create the client (mrparkers/keycloak) this flag does set up and appears in the json export

### Version

18.0.0

### Expected behavior

The "SAML Signature Key Name" flag should be in the json export of the client in question and the saml connection should work

json field

    "saml.server.signature.keyinfo.xmlSigKeyInfoKeyNameTransformer" : "KEY_ID",

### Actual behavior

The key does not set up nor it appears in the json export  in spite of appearing in the GUI with the wanted value. The saml connection fails

### How to Reproduce?

Create a new saml client and export the client json data with the admin cli. The flag "SAML Signature Key Name" does not appear

**Comment by bziraoui** [comment]
Hello, have the same issue for v19.0.3 , did you solve it?

**Comment by jonkoops** [comment]
This issue may have been resolved in the new Admin Console. Could you try testing it with the latest version of Keycloak?

**Comment by rmartinc** [comment]
I have tested this and it's solved in the new admin console. I can export and import `SAML signature key name` without issues (attribute `"saml.server.signature.keyinfo.xmlSigKeyInfoKeyNameTransformer": "KEY_ID"` is in the json file). Closing this as resolved. Please re-open or file a new issue if needed.
