### ISSUE TITLE
Execute DB migration tests for Keycloak on WildFly to Quarkus distribution

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#12687]
### Description

At this moment, it's possible to execute only DB migration tests for Keycloak from WildFly to WildFly or Quarkus to Quarkus, but not from WildFly to Quarkus. As there will be a lot of changes in the new Keycloak store, the DB migration tests will change a little bit as well. Therefore, I'd consider this issue as the one with low impact and can be done as a follow-up task.

**Comment by hmlnarik** [comment]
There is no difference between Quarkus and Wildfly when run on legacy store, this would be effectively testing the same functionality as Wildfly migration.

New store will **not** be automatically migrated from legacy store. There will be an offline migration tool needed for that purpose, which is yet to be created

**Comment by mabartos** [comment]
@hmlnarik Thanks for your comment. You're right, there's no difference between them regarding the legacy store migrations, but there's a difference in the test execution, where those tests are not ready to be executed with 2 different containers. For further, info, see the #12688 issue.

**Comment by mabartos** [comment]
Not relevant anymore
