### ISSUE TITLE
KeycloakAuthenticationEntryPoint loginuri does not support query parameters correctly.

### ISSUE THREAD

**Issue by ianwallen** [keycloak/keycloak#12693]
### Describe the bug

In our environment we wanted to disable the login redirect so we set the loginurl to the following.

/sso/login?prompt=none

The following line appends the this.loginUri to the queryParameters of the supplied request with a "?"

https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/authentication/KeycloakAuthenticationEntryPoint.java#L115

So in our case if the request is for url?lang=en then it will create the following url (notice the double "?")

/sso/login?prompt=none?lang=en

This double "?" breaks the url format and causes issue later in the process.

### Version

18.0

### Expected behavior

Url should not contain double "?" in the scenario described.

### Actual behavior

double "?" in url is causing issues.

### How to Reproduce?

Explained in the but description

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
