### ISSUE TITLE
Keycloak 18.0.1 Fails to start ISPN cache

### ISSUE THREAD

**Issue by biertz** [keycloak/keycloak#12718]
### Describe the bug

Bug is similar to #12630, though that one could be solved by re-creating the containers. My bug persists even in a fresh (docker-compose) testing system without replication.

### Version

quay.io/keycloak/keycloak:18.0.1

### Expected behavior

When starting version 18.0.0, the logs indicate that they cannot find an ISPN cache and initialise a new one. It happens with both our custom image and the version I provided above.

### Actual behavior

Startup of the container comes to a halt: 
```
keycloak_1  | 2022-06-24 11:00:03,131 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-8,33473546fc4e-47667) ISPN000210: Failed to request state of cache authenticationSessions from node 5c31f932c08f-30053, segments {0-255}: org.infinispan.commons.CacheException: ExceptionResponse(java.io.EOFException)
keycloak_1  |   at org.infinispan.statetransfer.InboundTransferTask.lambda$startTransfer$3(InboundTransferTask.java:167)
keycloak_1  |   at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
keycloak_1  |   at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
keycloak_1  |   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
keycloak_1  |   at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
keycloak_1  |   at org.infinispan.remoting.transport.AbstractRequest.complete(AbstractRequest.java:67)
keycloak_1  |   at org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:46)
keycloak_1  |   at org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:51)
keycloak_1  |   at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1495)
keycloak_1  |   at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1397)
keycloak_1  |   at org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:145)
keycloak_1  |   at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1582)
keycloak_1  |   at org.jgroups.JChannel.up(JChannel.java:780)
keycloak_1  |   at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:913)
keycloak_1  |   at org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
keycloak_1  |   at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
keycloak_1  |   at org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
keycloak_1  |   at org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
keycloak_1  |   at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
keycloak_1  |   at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
keycloak_1  |   at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
keycloak_1  |   at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
keycloak_1  |   at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
keycloak_1  |   at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
keycloak_1  |   at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
keycloak_1  |   at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
keycloak_1  |   at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
keycloak_1  |   at org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
keycloak_1  |   at org.jgroups.protocols.Discovery.up(Discovery.java:300)
keycloak_1  |   at org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
keycloak_1  |   at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
keycloak_1  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
keycloak_1  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak_1  |   at java.base/java.lang.Thread.run(Thread.java:829)
```
and eventually timeouts.

### How to Reproduce?

It's a docker-compose setup with a mysql service and a keycloak service. Keycloak runs behind a traefik (KC_PROXY: edge).

**Comment by vmuzikar** [comment]
@biertz Thanks for reporting this! Could you please provide more details on how exactly is your KC instance configured? Without it, we're unfortunately unable to reproduce.

**Comment by DmitryZ-outten** [comment]
Hello! I have a similar issue. It looks like even when you are trying to start a new container with Keycloak it tries to fetch authenticationSessions from a node that is not defined in the cluster configuration and not running anymore. 

@vmuzikar Is there an option for Infinispan to start a fresh cluster, with the new coordinator?

**Comment by DmitryZ-outten** [comment]
@pedroigor 
I am trying to prepare an exact steps to reproduce the issue. 
For me it looks like the issue is related to the message before the exception:
```
INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [node1-55572|201] (2) [node1-55572, node2-27775]
```
In this case, I am starting `node2` but `node1` should not be in the cluster and was removed already. But Infinispan still puts it into the cluster. Is there some option to flush cluster/cache and start from scratch?

**Comment by pedroigor** [comment]
Infinispan should remove nodes accordingly when they shut down, gracefully. Could you tell us how the node is leaving the cluster? If unexpectedly, without a graceful shutdown?

**Comment by DmitryZ-outten** [comment]
It looks like I have found the issue. I had an old container running in the same network.
@biertz I recommend you to check if all Keycloak containers in your network are down, before starting a new cluster. 

@pedroigor Do you know if there is an option to disable the multicast detection for infinispan? And use exact host/port configuration with TCPPING. 
I have tried to override cache-ispn.xml file with the following configuration:
```
    <jgroups>
        <stack name="test" extends="tcp">
          <TCP external_addr="${env.KC_EXTERNAL_ADDR}" bind_addr="${env.KC_BIND_ADDR}" bind_port="${env.KC_BIND_PORT}" />
          <TCPPING initial_hosts="${env.KC_INITIAL_HOSTS}"
                   port_range="0"/>
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="test" />
```

It works, but it looks like infinispan still uses multicast to detect other cluster nodes.

**Comment by vdahlberg** [comment]
We have the same issue upgrading from 18.0.0 -> 18.0.1. We're running on AWS ECS with DNSPING discovery.

It was no issue upgrading from 17.0.0 -> 18.0.0. All of it quarkus.

Just let me know if I should attach our detailed configuration. Haven't been able to reproduce it locally it.

**Comment by biertz** [comment]
Thanks for all your answers, especially @DmitryZ-outten, you pointed me in the right direction. I failed to understand that the issue is not about cache sharing in a replicatin situation, but between *any* instance running in the same network.

Indeed, I have another Keycloak testing instance on the same docker host that is in a shared (traefik) network with the non-persistent testing instance. Shutting down that instance would allow me to update to 18.0.1. This was the first time this happened, although I had more than one Keycloak in a similar setup before, so that got me confused.

> Do you know if there is an option to disable the multicast detection for infinispan?

I'd be interested in this as well. :)

**Comment by pedroigor** [comment]
I see now, that the error makes sense.

By default, the server uses UDP for transport and multicast (e.g.: discovery protocol).

@DmitryZ-outten By default, TCP transport uses MPING which relies on multicast. As you are extending `tcp` I would suggest you to make sure you are replacing MPING with `TCPPING`. 

See:

* https://infinispan.org/docs/stable/titles/server/server.html#default-jgroups-stacks_cluster-transport.
* https://infinispan.org/docs/stable/titles/embedding/embedding.html#customizing-jgroups-stacks_cluster-transport

**Comment by vdahlberg** [comment]
@pedroigor we don't have a setup like that but still have this issue. We're running keycloak in ECS and multicast isn't allowed in AWS by default, so we're using DNSPING. This is how our setup looks like;

```
FROM --platform=linux/amd64 quay.io/keycloak/keycloak:18.0.1 as keycloak-builder

ENV KC_DB=postgres \
    KC_CACHE=ispn \
    KC_CACHE_STACK=kubernetes \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build

FROM --platform=linux/amd64 quay.io/keycloak/keycloak:18.0.1
COPY --from=keycloak-builder /opt/keycloak/providers/* /opt/keycloak/providers/
COPY ./theme/ /opt/keycloak/themes/


ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start --spi-sticky-session-encoder-infinispan-should-attach-route=false"]
```

Then we set `KC_HOSTNAME_STRICT_BACKCHANNEL=true`, `KC_PROXY=edge`, `KC_HTTP_ENABLED=true` and `JAVA_OPTS=-Xms64m -Xmx1536m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djgroups.dns.query=keycloak.service -Dquarkus.datasource.jdbc.max-lifetime=20H`

**Comment by bertbaron** [comment]
We have the same issue with a setup very similar as the one in the previous post. I'm able to reproduce this on a local single-node cluster with the example here: https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx/examples/postgresql

To reproduce I added the following to `keycloak-server-values.yaml`:
```yaml
image:
  repository: quay.io/keycloak/keycloak
  tag: 18.0.0
replicas: 2
affinity:
```

When upgrading to `18.0.2` the new pod gives the error:
```
2022-07-05 09:40:42,106 WARN  [org.infinispan.statetransfer.InboundTransferTask] (jgroups-5,keycloak-keycloakx-1-15267) ISPN000210: Failed to request state of cache authenticationSessions from node keycloak-keycloakx-0-21114, segments {0-255}: org.infinispan.commons.CacheException: ExceptionResponse(java.io.EOFException)
```

Interestingly enough earlier tests seemed to indicate that a rolling update from one 18.0.0 build to another, or of one 18.0.2 build to another (different docker images containing the same keycloak version but minor other changes) did not give any problem. But I didn't verify this locally yet.

**Comment by pedroigor** [comment]
@bertbaron I think the issue you are facing is related to https://github.com/keycloak/keycloak/issues/13479#issuecomment-1202235557.

Upgrade from N-1 version should be supported by the new store.

**Comment by atreyd** [comment]
@vdahlberg I am also trying to run the keycloak 20.0.5 version on AWS ECS and have tried JDBC_PING and other cache configurations but it didn't work. Can you please share your cache-ispn.xml configuration which worked with DNS_PING
