### ISSUE TITLE
Set `resourcesVersionSeed` when using ConcurrentHashMap storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#12710]
## Description

When run with a map storage, the following warning is logged:

`WARN  [org.keycloak.models.DeploymentStateProviderFactory] (main) It is recommended to set 'resourcesVersionSeed' property in the map provider config of deploymentState SPI`

To fix this warning, set the `resourcesVersionSeed` property of `map` provider of `deploymentState` SPI to a random number when using only `concurrenthashmap` storage providers.

**Comment by ahus1** [comment]
Starting to look into this one as it is one of the things waiting for the tech preview.

**Comment by ahus1** [comment]
This change is being re-worked in #13807 as the warning was showing too often. The CLI option is still valid.
