### ISSUE TITLE
Potential improper handling of auth_time in OIDC identity brokering

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#12735]
## Original report

When delegating authentication to an external Identity Provider the auth_time returned to the initiating client should correspond to the auth_time at the external Identity Provider. Otherwise the auth_time returned to the client may not correspond to the time the user actually entered credentials. This also affects if the initiating client includes max_age, where the client wants the max_age since last time the user entered credentials.

We need to review how this is handled.

### Version

- <= 18.0.1

### Reference
- https://issues.redhat.com/browse/KEYCLOAK-12812

**Comment by mposolda** [comment]
@abstractj @vmuzikar Anyone of you willing to triage this? :-) Thanks

**Comment by abstractj** [comment]
@mposolda assigned to @vmuzikar considering that he was the previous assignee. @vmuzikar please feel free to remove yourself as assignee after the triage.

**Comment by abstractj** [comment]
@vmuzikar whenever you have some time, could you please triage? If not possible, we can try to find someone else.

**Comment by mposolda** [comment]
@pedroigor I believe this was recently fixed by you (or at least there was PR opened for this, but not 100% sure if it was merged or not)? Maybe you remember some more details and have the link to the original commit (or GH issue) with the fix?

**Comment by pedroigor** [comment]
@mposolda Yeah, it should be fixed by https://github.com/keycloak/keycloak/pull/14147.

That change respects the auth time sent by the brokered Idp.
