### ISSUE TITLE
[keycloak-js] multiple init call with onload option as check-sso cause redirects

### ISSUE THREAD

**Issue by lfelipevc** [keycloak/keycloak#12745]
### Describe the bug

Calling  `init()` function multiple times  (more than one) with `{onLoad:"check-sso",...}`, the adapter creates multiple iframe and ends up causing fail and redirects (maybe because it follow login-required flow after failing).

When using with React projects created with create-react-app, its inserts   `<React.StrictMode>` tag that renders components twice and ,depending the user implementation,  calls `init()` twice.

### Version

<= 18.0.1

### Expected behavior

Do not redirect or ignore new init() call when there's ongoing one

### Actual behavior

The adapter cause multiple redirects

### How to Reproduce?

Call init twice with check-sso  options enabled

**Comment by mwiede** [comment]
@lfelipevc I don't think, this is an issue with keycloak-js library. It is an issue, how react handles state between unmounting and mounting a component. See my answer in https://github.com/react-keycloak/react-keycloak/issues/182#issuecomment-1175217793 You just have to make sure, that init is only called once.

**Comment by lfelipevc** [comment]
@mwiede thank you for you reply. I saw your post and i still think that's a keycloack-js lib issue. I understand the init() method was not designed to be called more than once, but the main issue is existing: calling the method for the second time leads the object to an undesirable or unpredictable state, not only the object instance but the entire page. So, the implementation of this kind of a method should: 1. Throw an error, 2. Ignores the call or 3. Re-execute de init logic. The pull-request that i made implements the same logic that's partially implemented today at init code to deal this issue. It will do nothing if there's a ongoing init() call or it will execute the init() logic again.
