### ISSUE TITLE
Update resources after creation instead of re-creating them

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#12750]
### Description

Rationale:
https://github.com/java-operator-sdk/java-operator-sdk/blob/6f8d38d73b4a60c35b602994a2cf0f3ee6a70634/docs/documentation/patterns-best-practices.md?plain=1#L67-L74

At the moment resources are always re-created with `createOrReplace`: https://github.com/keycloak/keycloak/blob/c05898365528d19bf62677b97925b21b954365d9/operator/app/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java#L57
But we should instead `update` to avoid erroneously overwriting changes that happened in the cluster.

**Comment by vmuzikar** [comment]
This will be potentially solved by #13453.

**Comment by shawkins** [comment]
Or by #20850.  

To clarify createOrReplace is not recreating the resources fully - it is performing unlocked PUTs.  Some createOrReplace calls in fabric8 used to support deleteExisting, which is similar to the kubectl force option.  That would delete the resource and then create, but that is not being used here.

**Comment by shawkins** [comment]
Closed by #20850
