### ISSUE TITLE
Add the "cty" (content type) Header Parameter in encrypted user info response

### ISSUE THREAD

**Issue by Spyna** [keycloak/keycloak#12752]
### Describe the bug

The JWT header returned in the user info endpoint should contain the parameter `cty` (content type). 
Its value should be JWT.

### Version

18.0.0

### Expected behavior

The expected behavior would be that the `cty` header of the JWT of the (encrypted) user info endpoint response, would be present and valued with `JWT`

### Actual behavior

 the `cty` header of the JWT of the (encrypted) user info endpoint response is missing

### How to Reproduce?

In the client configuration, configure the value of `Fine Grain OpenID Connect Configuration` -> `User Info Response Encryption Key Management Algorithm` to `RSA-OEAP-256`.

Then run a login flow of openid connect, with the obtained access token call the `User info endpoint`. 
Check the header parameters of the returned JWT. the `cty` is missing

### Anything else?

I'll send a PR asap

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

@Spyna Did you had a chance to send PR as you mentioned?

**Comment by Spyna** [comment]
@mposolda here's the PR: https://github.com/keycloak/keycloak/pull/12753

**Comment by pernelkanic** [comment]
Can I work on this issue?

**Comment by Spyna** [comment]
A pr is already ready to be merged for this issue, link in description
