### ISSUE TITLE
Keycloak 18 Docker Container not importing properly

### ISSUE THREAD

**Issue by jbcbezerra** [keycloak/keycloak#12758]
### Describe the bug

Hello there,

I am currently trying to re-import jsons I exported from my Keycloak 18 container using `--dir` and `--users same_file`at startup. But this does not work if there is a **xyz-realm.json** and a **xyz-users-0.json**.

To be precise it seems to be that the **xyz-users-0.json** files are the problem because the whole import process works if you put only the **xyz-realm.json** in the import directory.

### Version

18.0.2  and 18.0.1

### Expected behavior

It is expected that realm and the corresponding user json will be imported without any problems.

### Actual behavior

As soon as a **xyz-users-0.json** is defined for a realm, it is imported before the **xyz-realm.json**. The following attempt to import **xyz-realm.json** fails with the error message "It already exists"
```
2022-06-27 11:34:15,353 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2022-06-27T11:34:16.455857252Z 2022-06-27 11:34:16,455 INFO  [org.keycloak.services] (main) KC-SERVICES0003: Not importing realm master from file /opt/keycloak/bin/../data/import/master-realm.json.  It already exists.
2022-06-27T11:34:16.830262069Z 2022-06-27 11:34:16,830 INFO  [org.keycloak.services] (main) KC-SERVICES0004: Imported realm menti from file /opt/keycloak/bin/../data/import/menti-users-0.json.
2022-06-27T11:34:16.901305462Z 2022-06-27 11:34:16,901 INFO  [org.keycloak.services] (main) KC-SERVICES0003: Not importing realm menti from file /opt/keycloak/bin/../data/import/menti-realm.json.  It already exists.
2022-06-27T11:34:16.903271097Z 2022-06-27 11:34:16,903 INFO  [org.keycloak.services] (main) KC-SERVICES0003: Not importing realm master from file /opt/keycloak/bin/../data/import/master-users-0.json.  It already exists.
```

### How to Reproduce?

1. create and run keycloak 18.0.2 docker container using compose.yml:
```
version: '3.6'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    user: 1000:1000
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8090:8080'
    command: start-dev --import-realm
    volumes:
      - ./realms/import/:/opt/keycloak/data/import/
```

2. create a realm besides master. Lets call it "menti"
3. in that new realm add a simple new user 
4. save/export those Kc Configuration using `docker exec -u 1000:1000 keycloak_keycloak_1 /opt/keycloak/bin/kc.sh export --dir /opt/keycloak/data/import/ --users same_file`
    - this will generate/export 4 jsons **master-realm.json**  ,  **master-users-0.json**  ,  **menti-realm.json**  ,  **menti-users-0.json**
    - copy them to the ./realms/import directory (or your defined volume dir)
5. shut down and restart the container using `docker-compose up/down`
    - since we set the compose.yml to have `--import-realm` set and to use the defined volum, Kc will try to import those four jsons but will fail with the previosly defined Messages.

**Comment by jbcbezerra** [comment]
So it's expected that a freshly created Keycloak container can't import realm.json and its associated user.json at startup ?
This sounds a bit strange, because it worked fine in older versions (i.e. 9.0.0) and these are already years old.

**Comment by jbcbezerra** [comment]
thx for the quick answer btw!

**Comment by pedroigor** [comment]
@jbcbezerra You can do it but realms are not overridden if they already exist in the database.

**Comment by bigred8982** [comment]
So, how do you successfully import both a realm.json and user.json file for the same realm?

**Comment by jbcbezerra** [comment]
You would then have to use the export option "--users realm_file" instead of "--users same_realm". This will export realm and users in a single json, which then eliminates the "Already exists" problem, since the realm is only created/configured by one json.

**Comment by boerngen-schmidt** [comment]
> @jbcbezerra You can do it but realms are not overridden if they already exist in the database.

If I create a new container for development purposes, which does not contain the realm which should be imported, it should fully import all data for that realm from the provided JSON files.

Keycloak by default exports a realm into multiple files, the realm metadata and the realm users, and thus it should import the full realm (metadata + users) before it considers an import complete. Once the import of metadata and users has taken place once, I agree with you, that it should not be done again e.g. when restarting the container.

@pedroigor please reconsider reopening this bug since the behavior does not adhere to keycloaks own convention on export file naming. Or explicitly state in the documentation, that the users must be in the same file as the realms metadata.

I my opinion what keycloak should be doing is
 1. it finds a new realm to import
 2. gathers all files according to convention that should be imported (myrealm-realm.json, myrealm-users-0..*.json)
 3. import all data

**Comment by pedroigor** [comment]
@jbcbezerra @boerngen-schmidt Can you please take a look at https://github.com/keycloak/keycloak/pull/16282?

**Comment by boerngen-schmidt** [comment]
Thank you very much for responding and pointing to the other issue, which I did not find earlier.
