### ISSUE TITLE
RESTEASY002005: Failed executing GET /: org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: org.keycloak.models.KeycloakSession

### ISSUE THREAD

**Issue by tianqing108** [keycloak/keycloak#12777]
### Describe the bug

How to resolve this problem? It's happend at  a request arrive at QuarkusWelcomeResource. KC_HTTP_RELATIVE_PATH is seted to "/auth". Any body know this?

### Version

18.0.2

**Comment by mabartos** [comment]
@tianqing108 Thanks for creating this issue. Unfortunately, I'm unable to reproduce this issue. Could you please try it with the latest Keycloak version?

Feel free to reopen this issue if the problem persists and provide a reproducer.
Thank you
