### ISSUE TITLE
Admin REST API "User" response should have a "webauthn" field

### ISSUE THREAD

**Issue by ynojima** [keycloak/keycloak#12776]
### Description

Admin REST API "User" response should have a `webauthn` field, which indicates the user have webauthn credentials or not like the `totp` field.

~~~
[ynojima@sso1 bin]$ ./kcadm.sh get users
[ {
  "id" : "8048cc01-d52c-47cc-9e44-62c8a722139d",
  "createdTimestamp" : 1655714601942,
  "username" : "ynojima",
  "enabled" : true,
  "totp" : false,     // "webauthn" should have a field like this
  "emailVerified" : false,
  "disableableCredentialTypes" : [ ],
  "requiredActions" : [ ],
  "notBefore" : 0,
  "access" : {
    "manageGroupMembership" : true,
    "view" : true,
    "mapRoles" : true,
    "impersonate" : true,
    "manage" : true
  }
} ]
~~~

### Motivation

Credential existance can be checked by `GET /{realm}/users/{id}/credentials`, but get user list response (`GET /{realm}/users`) should have the data to avoid calling the credentials REST API per users.

**Comment by mabartos** [comment]
@ynojima Thanks for creating this enhancement. 

It'd be nice to have such information about users. However, I'd consider a better approach to have a list or array of available credentials. As a user can use credentials like password, OTP, use WebAuthn authenticator, or different WebAuthn passwordless authenticator. IMHO, it'd be good to have syntax for it similar to the `access` list above. 
Besides that, the `otp` field can be deprecated.

List:
```
"availableCredentials" : {
   "password" : true,
   "otp" : true,
   "webauthn" : true,
   "webauthn-passwordless" : true
}
```
Array:
```
"availableCredentials" : ["password", "otp", "webauthn", "webauthn-passwordless"]
```

Or the name of the list could be only "credentials".

@ynojima @mposolda WDYT?

**Comment by ynojima** [comment]
Thank you for your prompt response. I prefer the "Array" approach.

**Comment by mposolda** [comment]
@ynojima @mabartos TBH I am not sure if it is good to introduce this change at this stage.

For the long-term, there is plan to rewrite admin REST API and align with the OpenAPI. Until that, it will be good to avoid minor changes in the admin REST API unless necessary IMO. And this one is not necessary IMO as it is still possible to retrieve list of credentials the other way. Introducing it will need new field on UserRepresentation, which is not ideal in case we want later to remove it (additional pain regarding backward compatibility etc).

The field "totp" is exactly the thombstone, which was added in early day of Keycloak and is deprecated now. It will be ideal to remove this field, which is not done just due the backwards compatibility.

**Comment by mposolda** [comment]
Closing after discussion with @ynojima
