### ISSUE TITLE
Add Docker Secrets Support

### ISSUE THREAD

**Issue by MichaelKoch11** [keycloak/keycloak#12785]
### Description

There should be an option to pass KEYCLOAK_ADMIN, KEYCLOAK_ADMIN_PASSWORD, KC_DB_USERNAME and KC_DB_PASSWORD with Docker Secrets in the quarkus distribution.
This should be work with env KEYCLOAK_ADMIN_PASSWORD_FILE and KC_DB_PASSWORD_FILE.

### Motivation

One Option is to pass secrets  with .env file, but more secure would be the docker secrets approach.
In the old Wildfly distributions I use (https://hub.docker.com/r/jboss/keycloak/) its also integrated. 

### Details

Add enviroment Variables with _FILE ending to  pass docker secrets path.

**Comment by Zocker1999NET** [comment]
Seems to be a duplicate of #10816

**Comment by MichaelKoch11** [comment]
Thanks for your help, I doesnt find before this Issue by searching.
