### ISSUE TITLE
Move `StorageId` class to one of legacy modules

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12807]
`StorageId` is used for referencing users that are stored outside of Keycloak - from `UserStorageSpi` implementation/provider. This is something that should not be possible in the new storage, therefore we should make sure `StorageId` is not used there by moving it into one of legacy modules.

**Comment by hmlnarik** [comment]
Tree store will need to reference the nodes in the tree similarly - storage node ID (a.k.a. provider ID), and the ID in that storage.

Let's close this for now and revisit once tree store is in.
