### ISSUE TITLE
Deprecate legacy-only-used methods in provider/model interfaces

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#12811]
Logical layer interfaces contain methods that are used only from legacy modules. As an example see: 

[unlinkUsers](https://github.com/keycloak/keycloak/blob/main/server-spi/src/main/java/org/keycloak/models/UserProvider.java#L142)
or 
[removeImportedUsers](https://github.com/keycloak/keycloak/blob/main/server-spi/src/main/java/org/keycloak/models/UserProvider.java#L134)

there may be much more occurrences of this. We should identify such methods and deprecate them. After the decision that the legacy store will not be used together with the new one, we are sure such methods will never be called with the new storage. Therefore, we can remove the implementation of them which can result in removal of some `SearchableField` or entity fields.

**Comment by martin-kanis** [comment]
No longer relevant after removal of map store. Closing
