### ISSUE TITLE
Inconsistent behavior of group attribute caching

### ISSUE THREAD

**Issue by leischt** [keycloak/keycloak#12819]
### Describe the bug

When setting a group attribute and afterwards read this attribute again from the same GroupModel instance some unexpected behavior could be noticed.

### Version

18.0.0

### Expected behavior

In my opinion all getter methods should return the value provided by the setter method.

### Actual behavior

Dependent on the get method called different outputs were given.
Only the getFirstAttribute("key") method returned the previous set value. All others returned the old value, which was stored before the set call.
If the GroupModel is reloaded from the session the new value is returned by all getters as expected.

### How to Reproduce?

```
groupModel.setSingleAttribute("key", "new_value");


List<String> values = groupModel.getAttributes().get("key");
LOG.info(String.valueOf(values)); // old value

String value = groupModel.getFirstAttribute("key");
LOG.info(value); // new value

Optional<String> optionalValue = groupModel.getAttributeStream("key").findFirst();
LOG.info(String.valueOf(optionalValue));  // old value

GroupModel groupModelReloaded = session.groups().getGroupById(session.getContext().getRealm(), groupModel.getId());
List<String> valuesReloaded = groupModelReloaded.getAttributes().get("key");
LOG.info(String.valueOf(valuesReloaded));  // new value

String valueReloaded = groupModelReloaded.getFirstAttribute("key");
LOG.info(valueReloaded); // new value

Optional<String> optionalValueReloaded = groupModelReloaded.getAttributeStream("key").findFirst();
LOG.info(String.valueOf(optionalValueReloaded)); // new value

```

**Comment by mhajas** [comment]
Thank you for the report @leischt. You are right, there is a bug in `GroupAdapter` in the Infinispan cache implementation. It seems the fix is simple, I created a PR: https://github.com/keycloak/keycloak/pull/15350

**Comment by cnwaldron** [comment]
I'm seeing this same issue on the user model's getAttributeStream call. I'm seeing this on version 20.0.1.

**Comment by mhajas** [comment]
@cnwaldron, minor releases do not contain all fixes, mostly security fixes and regressions. For this fix, you will need to wait for Keycloak 21 to be released.
