### ISSUE TITLE
update microsoft active directory password error through keycloak

### ISSUE THREAD

**Issue by qixiangyang** [keycloak/keycloak#12815]
### Describe the bug

![image](https://user-images.githubusercontent.com/9353474/176427709-ad0b7fea-a21d-4e2e-b899-dea03a5b13a1.png)

Background： has add related permissions to admin user to update the users password in AD

error info:
Error! Could not modify attribute for DN [CN=xxxx,CN=Users,DC=xxxx,DC=com]

log info: 

keycloak_1    | Caused by: javax.naming.OperationNotSupportedException: [LDAP: error code 53 - 0000001F: SvcErr: DSID-031A126A, problem 5003 (WILL_NOT_PERFORM), data 0

keycloak_1    | 2022-06-29 11:37:26,522 WARN  [org.keycloak.services.resources.admin.UserResource] (executor-thread-9) Could not update user password.: org.keycloak.models.ModelException: Could not modify attribute for DN [CN=xxx,CN=Users,DC=xx,DC=com]

i also try to set ssl config for keycloak, and change ldap path to ldaps://xxxxxx:636
but still not working, and the error log like this:

Error when authenticating to LDAP: simple bind failed: 172.16.163.200:636: javax.naming.CommunicationException: simple bind failed: xxxxxxxx:636 [Root exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]

### Version
18.02
docker-compose file
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=xx
      - POSTGRESQL_DATABASE=bitnami_keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:18
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=xxx
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=xxx
      - KEYCLOAK_DATABASE_PASSWORD=xxx
      - KEYCLOAK_ENABLE_TLS=true
      - KEYCLOAK_TLS_KEYSTORE_FILE=/opt/bitnami/keycloak/certs/keystore.jks
      - KEYCLOAK_TLS_TRUSTSTORE_FILE=/opt/bitnami/keycloak/certs/truststore.jks
      - KEYCLOAK_TLS_KEYSTORE_PASSWORD=xx
      - KEYCLOAK_TLS_TRUSTSTORE_PASSWORD=xx
    depends_on:
      - postgresql
    ports:
      - "808:8080"
    volumes:
      - 'path/keycloak/keystore.jks:/opt/bitnami/keycloak/certs/keystore.jks'
      - 'path/keycloak/truststore.jks:/opt/bitnami/keycloak/certs/truststore.jks'
volumes:
  postgresql_data:
    driver: local

### How to Reproduce?
set ad path like this:  ldap://xxxxxx:389

_No response_

**Comment by ldesroch** [comment]
Hi,

We had the same exact problem for one of our clients.
In fact it seems to not be related to keycloak, but is a security rule from active directory preventing password modification from an uncyphered connection.

Clue 1:
Testing with ldap tools had the same issue.
```
ldappasswd -H ldap://server_domain_or_IP -x -D "cn=admin,dc=example,dc=com" -W -S "uid=bob,ou=people,dc=example,dc=com"
Protocol error(2)
Additional info: 0000203D: LdapErr: DSID-0C0911AA, comment: Unknown extended request OID, data 0, v3839
````
 
Clue 2:
Ldapwiki has documented the security rule
https://ldapwiki.com/wiki/UnicodePwd#section-UnicodePwd-SectionUnicodePwdEncryptionRequired

I'll let you know our solution or workaround once found and tested.
We will probably recommend to encrypt the connection (ldaps) even if it is on a secured network to workaround the problem.

**Comment by ahus1** [comment]
For MSAD, TLS is required to change passwords. Therefore this error is expected.

**Comment by hmlnarik** [comment]
Closing as explained
