### ISSUE TITLE
Admin-Console isn't loading if KC_HOSTNAME_PORT environment variable is set on 443 port

### ISSUE THREAD

**Issue by dennismeissel** [keycloak/keycloak#12823]
### Describe the bug

I start keycloak behind a reverse proxy, on a particular port.
To make it work I set `KC_HOSTNAME_PORT` by Keycloak and add `X-Forwarded-Port` by nginx.

However, if I start everything on a standard 443 Port and set `KC_HOSTNAME_PORT` to 443, admin-console doesn't work anymore, there is only logo and blanc list.
Account console doesn't work either, there is an invalid redirect_uri error.
In dev-tools nothing is pending and it looks like if the page is loaded correctly.

Workaround is very simple: If I remove `KC_HOSTNAME_PORT` variable completely, everything works.

### Version

18.0.0

### Expected behavior

Admin-Console should work if `KC_HOSTNAME_PORT` is set to 443

**Comment by andybarilla** [comment]
I have the same issue. Removing `KC_HOSTNAME_PORT` causes the Admin screen to fully load but then the clients can't validate tokens.

In my case, the logon screen loads, then it goes to the next page where only the top bar loads. I'm seeing no negative responses and the last request in the network traffic is to `https://<keycloak-hostname>/realms/master/protocol/openid-connect/login-status-iframe.html/init?client_id=security-admin-console&origin=https://keycloak-hostname` which returns a 204.

In our case, we're running in the Google cloud.

**Comment by allahshukur-ahmadzada** [comment]
Hello, I wonder anyone found a workaround? because having same issue. I have haproxy in front of keycloak and keycloak uses 8443 port while haproxy acts as load balancer and uses 443, now keycloak supposed to redirect to 443 but redirects to 8443, setting KC_HOSTNAME_PORT helps with redirect port but this time admin console is blank

**Comment by stianst** [comment]
Did you configure the proxy settings? --proxy?

**Comment by allahshukur-ahmadzada** [comment]
yes, those things configured via env variables and was working on 17.0.0

**Comment by allahshukur-ahmadzada** [comment]
LIke what is the purpose of KC_HOSTNAME_PORT? we supposed to give it port of load balancer?

**Comment by stianst** [comment]
If you are using a reverse proxy on the default ports just use the "--proxy=something" option. The hostname-port option is only needed if KC is exposed via a reverse proxy on non standard ports.
