### ISSUE TITLE
Users cannot access the Account Management page (access dennied)

### ISSUE THREAD

**Issue by TheParanoik** [keycloak/keycloak#12840]
### Describe the bug

When redirecting an user to `/realms/{realm_name}/account/` it returns HTTP 403 Forbidden.

### Version

18.0.1

### Expected behavior

It should show the user the `account` page and let them edit their data/profile.

### Actual behavior

It returns HTTP 403 Forbidden

### How to Reproduce?

I have no clue what went wrong, I've tried even giving the user admin privileges and all the roles. Each try ended up with the same result.

**Comment by Nannymeta** [comment]
Facing same issue

**Comment by sschu** [comment]
Does your user have the account.manage-account role @Nannymeta ?

**Comment by Nannymeta** [comment]
yes,

i've finally solved the issue by clearing caches from front.
![image](https://user-images.githubusercontent.com/103997330/189950409-f3d878c8-28e3-4e5c-a66d-f1954089bd74.png)
