### ISSUE TITLE
Remove dependency of "keycloak-common" on BouncyCastle

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#12855]

**Comment by mposolda** [comment]
Scope of this task is to:
- Remove dependency of `keycloak-common` module on BouncyCastle libraries
- Classes from `keycloak-common`, which use BouncyCastle (EG. CertificateUtils, PemUtils etc) can invoke the CryptoProvider instead and the corresponding code can be implemented in CryptoProvider implementations, which are inside `crypto/default` (for BC) and `crypto/fips1402` (for BCFIPS).
- Unit tests from `keycloak-common`, which use crypto classes, can be also moved to corresponding crypto modules or changed to abstract and make sure that they are tested in both 'default" and "fips1402" environment (For example something already done in 
- This may need also update Wildfly modules to skip directly using `bouncycastle` modules (both server and adapter modules of the WF distribution)

**Comment by mposolda** [comment]
@david-rh Assigning to you

**Comment by david-rh** [comment]
@mposolda please assign to me, thanks.
