### ISSUE TITLE
Custom URL prefix not working for keycloak 18.0.2

### ISSUE THREAD

**Issue by EinavDanielDX** [keycloak/keycloak#12852]
### Describe the bug

We use keycloak in our k8s deployment.
As part of it, we changed the root URL path to https://mydomain/auth, and put nginx controller as a reverse-proxy in front of it.
On version 18.0.1, it worked fine with the following configuration:
```
KC_PROXY_ADDRESS_FORWARDING=true
KC_PROXY=passthrough
KC_HOSTNAME_PATH=/auth
KC_HTTP_RELATIVE_PATH=/auth
```
After upgrading keycloak version from 18.0.1 to 18.0.2, we get 404 page not found response

### Version

18.0.2

**Comment by Jacob-** [comment]
We are having the same issue when setting the relative path during the build of the image.

Setting it again in the start command works but leads to keycloak being "rebuilt".

```
Changes detected in configuration. Updating the server image.  
Updating the configuration and installing your custom providers, if any. Please wait.  
```

**Comment by mehtadev17** [comment]
+1 experiencing the same issue with 20.0.2 when setting `KC_HOSTNAME_PATH=/auth` during the build stage.

**Comment by sschu** [comment]
According to https://www.keycloak.org/server/all-config, `KC_HOSTNAME_PATH=/auth`is not a build option so it should not need a rebuild. `KC_HTTP_RELATIVE_PATH` does need a rebuild.

**Comment by mehtadev17** [comment]
Sorry updated the comment. KC_HTTP_RELATIVE_PATH is the one i'm using and it doesn't work when set during the build stage. 

![Screenshot 2023-01-03 at 1 50 16 PM](https://user-images.githubusercontent.com/6795712/210422295-125eef26-949d-4958-a898-caceb2abdc2d.png)

**Comment by sschu** [comment]
Because it should be set at runtime, it is a configuration option.

**Comment by mehtadev17** [comment]
Where does it suggest that it should be set at runtime? From the screenshot you can clearly see its a build time option.

**Comment by sschu** [comment]
Ah, sorry, I mixed it up. Yes, it's a build time option. But we are using it and it does work at least on Keycloak 19 which is our current version. I haven't checked Keycloak 20.

**Comment by mabartos** [comment]
@EinavDanielDX Sorry for the late response. Could you please try it with the latest version of Keycloak or the latest main branch? Thanks

**Comment by mabartos** [comment]
I couldn't reproduce this issue, and it seems to be inactive. Be aware there were some changes related to proxy modes behavior[1], so please check it. If you reencounter the issue, please reopen this issue. Thanks!

[1] https://github.com/keycloak/keycloak/pull/20072/files

**Comment by EinavDanielDX** [comment]
@mabartos 
Sorry I hadn't had the attention for the subject lately.
Thank you for the response, I'll let you know if there is still a problem or it had been fixed once I get the chance to test it
