### ISSUE TITLE
Partial import feature does not import Identity Provider mappers in Keycloak

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak#12861]
### Describe the bug

The Partial Import using RH-SSO admin console does not import the Identity Provider mappers config, it only import the IdP config.
I was able to recreate the behavior on RH-SSO 7.5.x using the attached idp-mapper.json file.
Is it expected behavior or bug ?
Also is it possible to import complete IdP configuration including mappers using below REST API:
POST /{realm}/identity-provider/import-config

### Version

18.0.0

**Comment by mposolda** [comment]
Closed by https://github.com/keycloak/keycloak/pull/13237
