### ISSUE TITLE
Realm cannot be overridden if it already exists

### ISSUE THREAD

**Issue by exilehanharr** [keycloak/keycloak#12868]
### Describe the bug

Using keycloak in Docker if some realm has already been imported I can't override it.

Path with my realm: `/opt/keycloak/data/import/realm.json`

ENTRYPOINT in Docker: ENTRYPOINT ["/opt/keycloak/bin/kc.sh","start","--import-realm"]

I've tried use follow but it isn't work:
```
ENTRYPOINT ["/opt/keycloak/bin/kc.sh","start"]
CMD ["-Dkeycloak.migration.action=import","-Dkeycloak.migration.provider=singleFile","-Dkeycloak.migration.file=/opt/keycloak/data/import/realm.json","-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
```

### Version

18.0.2

### Expected behavior

Realm will be overridden if exists

### Actual behavior

Realm can't be overridden

### How to Reproduce?

Start Docker container when realm already exists with CMD below:

ENTRYPOINT ["/opt/keycloak/bin/kc.sh","start"]
CMD ["-Dkeycloak.migration.action=import","-Dkeycloak.migration.provider=singleFile",-Dkeycloak.migration.file=/opt/keycloak/data/import/realm.json","-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]

**Comment by lexcao** [comment]
Hi, @exilehanharr 

Currently, the import realm is not supported for the overriding realm.

From the doc [server import&export](https://www.keycloak.org/server/importExport)
> If a realm already exists in the server, the import operation is skipped.

From the doc [operator import&export](https://www.keycloak.org/operator/realm-import)
> If a Realm with the same name already exists in Keycloak it will not be overwritten.

**Comment by vmuzikar** [comment]
@exilehanharr Thanks for the report, however  this is not supported at the moment as pointed out by @lexcao. Feel free to open a feature request.

**Comment by nerumo** [comment]
there's an open issue that would allow this: https://github.com/keycloak/keycloak/issues/14183
