### ISSUE TITLE
[REST API] - User temporarily locked  but "enabled" property return TRUE

### ISSUE THREAD

**Issue by Pi19** [keycloak/keycloak#12872]
### Describe the bug

After a user has failed to log in too many times ( eg . user = A) ,  his account is  temporarily locked

When I try to access a user (A) representation (https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_users_resource) using keycloak REST API : 

   1-  **GET /admin/realms/{realm}/users/{id of user A }**  , enabled= false 
   2- but when I  retrieve all users with  **GET /admin/realms/{realm}/users**  and check the user (A)  , enabled= true 

I think that _"enabled_" property should be equal to **false** for both endpoints
   

### Version

17.0.1

**Comment by lexcao** [comment]
Hi,
From my understanding, the `user-by-id` endpoint is checked by BruteForceProtector for temporary blocker.
https://github.com/keycloak/keycloak/blob/2c0cebea4739a2e2811f0820e0e8f67ac70b3fea/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L281-L283

While the `users-query` endpoint is not.
It might be a trade-off for `users-query` endpoint for there is a single check of user `isTemporarilyDisabled`.
It could result in slow query if query the temporaily disabled users in batch.

I don't know if is a bug or design.
Need Keycloak team to check.

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now.

The question is how to properly handle this, but it is big issue for performance to call `isTemporarilyDisabled` for every user. We may need some API changes to handle this more properly.

**Comment by nitinramvelraj** [comment]
Hey @mposolda thanks for the update, is there some place we can track this?

**Comment by pedroigor** [comment]
We had several improvements to user management, please check latest version.
