### ISSUE TITLE
hostname-strict-frontchannel ? 

### ISSUE THREAD

**Issue by edwint88** [keycloak/keycloak#12889]
### Description

Should this not be called hostname-strict-frontchannel instead?

<html>
<body>
<div class="paragraph" style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 0px;"><i class="options-expander fa fa-chevron-down" style="box-sizing: border-box; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-family: &quot;Font Awesome 5 Free&quot;; font-weight: 900; padding-right: 0.3rem; font-size: 0.7rem;"></i><span class="options-key" style="box-sizing: border-box; display: inline-block; font-weight: bold;">hostname-strict-backchannel</span></p></div><div class="paragraph" style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 0px;"><span class="options-description" style="box-sizing: border-box; color: rgb(108, 117, 125); margin-bottom: 0.8rem; display: block;">By default backchannel URLs are dynamically resolved from request headers to allow internal and external applications.</span></p></div>

If all applications use the public URL this option should be enabled.
--
CLI: --hostname-strict-backchannel
Env: KC_HOSTNAME_STRICT_BACKCHANNEL

</body>
</html>

Currently that is by default `false` and when you activate -> `true` -> it allows only frontchannel communication. So it's a little bit confusing.

### Motivation

To have a clear description of the parameter.

**Comment by shawkins** [comment]
Moot as of KC 26 with the removal of hostname v1.
