### ISSUE TITLE
Jackson De-serialization error when using ROLE_TYPE ProviderConfigProperty in custom LDAP mapper

### ISSUE THREAD

**Issue by tkautenburger** [keycloak/keycloak#12887]
### Describe the bug

When using a ROLE_TYPE ProviderConfigProperty in a custom LDAP storage mapper factory class (child class of AbstractLDAPStorageMapperFactory), deserialization of the 'config' map in the REST POST command fails due to the fact that the value of the map element for config property is rendered in the JSON payload as a single JSON string and not as expected a JSON array of strings (like with the STRING_TYPE ProviderConfigProperty).

Payload of POST request when trying to save the mapper:
`{config: {my-role: "Test-Role-Name"}, name: "test mapper", providerId: "spi-hardcoded-ldap-role-mapper",…}`

### Version

15.0.2 (bug persist also in 18.0.0)

### Expected behavior

It is expected that JSON payload for component POST request is rendered having the config value as JSON array, like:
`{config: {my-role: ["Test-Role-Name"]}, name: "test mapper", providerId: "spi-hardcoded-ldap-role-mapper",…}`

### Actual behavior

When trying to save an LDAP mapper configuration that contains a ROLE_TYPE provider configuration property, saving fails with the following exception:

````
kc15-keycloak  | 07:53:43,585 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-23) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Test-Role-Name')
kc15-keycloak  |  at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 23] (through reference chain: org.keycloak.representations.idm.ComponentRepresentation["config"]->org.keycloak.common.util.MultivaluedHashMap["my-role"])
kc15-keycloak  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
kc15-keycloak  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
kc15-keycloak  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
kc15-keycloak  | 	at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
k
````

### How to Reproduce?

Create a custom LDAP mapper with a ROLE_TYPE configuration property, e.g. copying the original code from the HardcodedLdapRoleStorageMapperFactory and change the PROVIDER_ID to something different. I don't actually know why the original mapper works while a clone of it will fail with the deserialization error.

**Comment by hmlnarik** [comment]
@tkautenburger Could you please check this issue is still valid with Keycloak 20?

**Comment by tkautenburger** [comment]
@hmlnarik I can confirm that with 20.0.1 it works when using the new Keycloak.v2 React Security Console, but not when still using the "old" classic GUI. For the classic GUI, the same deserialisation error still persists. Don't know if you want to fix that hence it is not actively maintained anymore.

**Comment by hmlnarik** [comment]
@tkautenburger Thank you for verification. The legacy console is not maintained / fixed anymore, hence closing this issue.
