### ISSUE TITLE
When internal domain for admin-security-console: 404 on step1.html file

### ISSUE THREAD

**Issue by rvanderboom** [keycloak/keycloak#12892]
### Describe the bug

With the admin console configured on a different domain blow configuration, the step1.html gives 404.
step1.html only available via the main domain name.

ENV KC_HTTP_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_FEATURES=admin2
ENV KC_PROXY=edge
ENV KC_CACHE=ispn
ENV KC_CACHE_STACK=kubernetes
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=false
ENV KC_HOSTNAME=<main.domain>
ENV KC_SPI_HOSTNAME_DEFAULT_ADMIN=<admin.internal.domain>

(when putting frontendUrl for realm master to main.domain, login on admin.internal.domain works but step1.html is working via this public main.domain.

see also:

https://keycloak.discourse.group/t/kc-17-x-x-how-to-access-admin-ui-from-port-forwarded-internal-url-prevent-redirect-from-internal-url-to-kc-hostname/14917

### Version

18.0.0 (quarkus)

### Expected behavior

should be able to login on admin console without getting whitepage.

### Actual behavior

getting whitepage on /auth/admin because of 404 on step1.html .

### How to Reproduce?

run keycloak quarkus (17 or 18) in kube environment with nginx.

2 nginx ingress:
1 internal with <admin.internal.domain>.   (/admin path and /realms/master/ go to this via path rules).
2. main domain <main.domain>.  (all except above admin paths.).

**Comment by pedroigor** [comment]
@rvanderboom The iframe is created based on the frontend URL. That is because it is not an admin URL.

**Comment by rvanderboom** [comment]
aah yes thanks, that helps knowing is discussed, will park it meanwhile and follow up this issue.

Thanks
