### ISSUE TITLE
client credentials with spring security oauth2

### ISSUE THREAD

**Issue by scizeron** [keycloak/keycloak#12906]
### Describe the bug

Context : spring-boot application performing some API requests leveraging client_credentials fow.
When spring-security did like this, no issue.

String **credentialsString = username + ":" + password**;
byte[] encodedBytes = Base64.getEncoder().encode(credentialsString.getBytes(charset));

Now, they do like that : 

String clientId = encodeClientCredential(clientRegistration.getClientId());
String clientSecret = encodeClientCredential(clientRegistration.getClientSecret());
headers.setBasicAuth(clientId, clientSecret);

when clientSecret contains specific characters, URL encode(clientSecret) includes a change and keycloak sends back "invalid credentials" because org.keycloak.util.BasicAuthHelper.parseHeader doesn't url decode client Id and client Secret.
String val = header.substring(6);
try {
  val = new String(Base64.decode(val.getBytes()));
} catch (IOException e) {
  throw new RuntimeException(e);
}
int seperatorIndex = val.indexOf(":");
if(seperatorIndex == -1) return null;
 String user = val.substring(0, seperatorIndex);
 String pw = val.substring(seperatorIndex + 1);

### Version

16.1.1

### Expected behavior

People from spring security say that they are right and it is a provider issue : 
https://github.com/spring-projects/spring-security/issues/11435

**Comment by lexcao** [comment]
Hi, @scizeron 
Seems the special character support is fixed by https://github.com/keycloak/keycloak/issues/11908

**Comment by mposolda** [comment]
@lexcao Thanks!

This is fixed in latest version, so I am closing. Please re-open just if you're still able to reproduce in latest Keycloak 21.0.1 version
