### ISSUE TITLE
#7539 does not fully solve KEYCLOAK-15167

### ISSUE THREAD

**Issue by zak905** [keycloak/keycloak#12912]
### Describe the bug

[KEYCLOAK-15167](https://issues.redhat.com/browse/KEYCLOAK-15167) had as an objective to add the option to include the email in the user info to avoid having  Keycload redirect to the user profile form after redirecting from the twitter login. 

The changes introduced by #7539 fix the issue except when the twitter name has only a single word (e.g name of a company, or even a person that uses just a nickname). In this case, the `identity.setName(twitterUser.getName());` will set the first name only and Keycloak will redirect to the profile form asking the user to enter a last name. 

I think we should move away from using `setName`, which is deprecated anyway, here  https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/social/twitter/TwitterIdentityProvider.java#L221 

Since the twitter name can be also the name of a company or something else than a person, unlike Google or other idps, we can for example set the whole twitter name as a first name, and leave the last name as a blank string. 

I suggest replacing 

```
identity.setName(twitterUser.getName());
```

By 

```
                identity.setFirstName(twitterUser.getName());
                identity.setLastName("");
```

### Version

16.0.0

### Expected behavior

 Keycload should not redirect to the user profile form after redirecting from the twitter login. This is the case only if the twitter name is made of at least two words

### Actual behavior

If the twitter name is for example `keycloak`, keycloak will still redirect to the user profile update form asking the user to fill the last name, which means that the last name was not set up by the idp logic 

### How to Reproduce?

* configure twitter as idp
* try logging in with an account which has only one word as a name

**Comment by mposolda** [comment]
Closing based on the discussion on https://github.com/keycloak/keycloak/pull/12923
