### ISSUE TITLE
SAML setting on  Logout Service Redirect Binding URL ?

### ISSUE THREAD

**Issue by matumot** [keycloak/keycloak#12914]
### Describe the bug

I tried to use keycloak  18.01 for saml with example django program on python3-saml (v1.14, python3.9) https://github.com/onelogin/python3-saml

I could  check login procedure with demo-django example and confirmed it worked as expected.

However, in the case of logout procedure,  
I specified  {key cloak admin url}/realms/{realm name}/protocol/saml  as  single logout  service URL.
But after passing the single logout service URL, 
"Logout service redirect binding URL" settings (in Fine Grain SAML Endoint Configuration of keycloak) seems not to be working.
Is it possible to have bugs on keycloak?

I checked the case for "Logout Service POST Binding URL" setting with keycloak and 
this worked as expeced (though some patch required on python3-saml side, see https://github.com/onelogin/python3-saml/issues/205) 

### Version

18.0.1

### Expected behavior

After passing  {key cloak admin url}/realms/{realm name}/protocol/saml,
it is expected to redirect to  url of "Logout service redirect binding URL"  if this is specified in keycloak settings.

### Actual behavior

redirect url described in expected behavior seems not to be proceeded.

### How to Reproduce?

See the section on "describe the bug". I can provide more information if neccessary.

**Comment by konradwudkowski** [comment]
I've experience the same problem :(

**Comment by PatrykTurczynowski** [comment]
I have meet the similiar problem with my .NET application.
Logout Service POST Binding URL setting seems not working properly.
When I'm logout from my application and session on keycloak server is active it redirect to URL I've specified into settings, but when I'm remove session on keycloak server and then logout from my .NET application kaycloak server is not able to redirect to proper URL and displays error.

![image](https://user-images.githubusercontent.com/25999244/189296692-583ba95c-f479-47d3-9c61-643b5b9410d0.png)
![image](https://user-images.githubusercontent.com/25999244/189310116-ad964100-7d64-4a2b-93eb-62af36b71324.png)
