### ISSUE TITLE
Step-up authentication with existing cookie not working when using `Authentication Flow Overrides` per client

### ISSUE THREAD

**Issue by niek1414** [keycloak/keycloak#12919]
### Describe the bug

When using step-up authentication to in combination with OTP we discovered a bug. The step-up authentication does not consider a client overridden authentication flow and instead takes the default from the Realm.  
It does this when the cookie is still valid and it needs to find all active (not expired) LoA config.

The cookie authenticator executes
https://github.com/keycloak/keycloak/blob/93bba8e338d7c785a4e2968fa54ce312be35ddb4/services/src/main/java/org/keycloak/authentication/authenticators/util/AcrStore.java#L146-L155

While this function should take the current Authentication Flow into account it just takes the realm default using `realm.getBrowserFlow()` :
https://github.com/keycloak/keycloak/blob/93bba8e338d7c785a4e2968fa54ce312be35ddb4/services/src/main/java/org/keycloak/authentication/authenticators/util/LoAUtil.java#L76-L77

### Version

18.0.1

### Expected behavior

A user with a valid cookie with LoA should be able to login into a Keycloak Client with a custom Authentication Flow.

### Actual behavior

After a user logs into the application for the first time everything works fine. 
When the user refreshes the page and the Adapter requests the same LoA as earlier the application logs "No condition found for level '1' in the authentication flow" and the users sees a whitelabel page "Sign-in failed. Invalid username or password"

### How to Reproduce?

NOTE: This is tested with a Browser Flow with OTP Form but should also fail with Direct Flows.

1. Create a new Authentication flow with LoA conditional Executions.
2. Pick a Keycloak Client and override the default flow for this client only. (Make sure that the default client for this realm does NOT contain LoA)
3. Login using this client.
4. Now with the valid session login again. (Just resubmit the token or login request)
5. The user is not automatically signed in and does not get a chance to. A whitelabel page with "Sign-in failed. Invalid username or password" is shown.
6. Keycloak logs two WARN lines:
```
No condition found for level '2' in the authentication flow
```
```
Failed authentication: org.keycloak.authentication.AuthenticationFlowException
   at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1041)
   at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:892)
  ...
```

### Anything else?

The original linked PR https://github.com/keycloak/keycloak/pull/19310 can be hopefully used as is with some minor tweaks like rebase and adding automated tests and some more minor tweaks (See my comment from the linked PR).

### Possible solution

Instead of using `realm.getBrowserFlow()` the current flow should be used. Either by retrieving possible override flows for the client with a fallback to realm. Or by passing through a reference from the Cookie Authenticator Execution of the Authentication Flow.

**Comment by raffaeler** [comment]
We have the same bug.
The workaround (not always applicable) is to set the Browser step-up authentication as the default for the entire realm, by selecting "Action - Bind Flow" in the custom flow.

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.

Fore more details: We do not recommend to use "Authentication flow override" future and it is possible that it will be deprecated/removed in the future. But if someone is still willing to contribute the fix, it is fine.

**Comment by fredericoschardong** [comment]
FYI this bug is still happening on 20.0.2

**Comment by raffaeler** [comment]
As fare as I can see from the sources, the bug is still there in 21.0.1

@mposolda Question: if overriding the flow is not recommended, I assume you suggest to use multiple realms. In this case how can you get users in-sync on multiple realms?

**Comment by jcputney** [comment]
Can we get an update on this issue? Running into this as well, and it looks like there's potential a PR with a fix

**Comment by jcputney** [comment]
@mposolda I see that you closed the original PR with comments left unaddressed. I went ahead and created a new PR addressing your comments. Let me know if you need anything else. The PR is #33747
