### ISSUE TITLE
Jpa Map Storage: standardize the column names format in the schemas

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#12929]
### Description

The JPA map storage schemas use different column name formats when the name is composite. Some columns use the underscore character as a separator (e.g. `user_id` or `fk_root`) while others use no separator at all (e.g. `entityversion`, `lastname`, etc). We should decide on a common format for these columns and change the schemas so they all follow the same name convention.

**Comment by vramik** [comment]
See https://github.com/keycloak/keycloak/pull/13392#issuecomment-1240573369
