### ISSUE TITLE
Add X509 thumbprint to JWT when using private_key_jwt 

### ISSUE THREAD

**Issue by marbindrakon** [keycloak/keycloak#12946]
### Description

Some identity providers, notably Azure AD, will not use JWKS to obtain the public key used for JWT signing and expect the thumbprint of the signing certificate to be included in the JWT header. Since Keycloak only includes `kid` in the JWT header, this means that such providers will fail to map the signing certificate to one that has been provided to the provider out of band (i.e. through the Azure console). 

It would be nice to have the option of including the `x5t` parameter in the JWT header when using JWT signed with a private key in order to use Azure and similar providers as an IdP for authenticating with Keycloak. 

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17609

### Motivation

At least one popular enterprise IdP requires the x5t parameter to be present and many enterprises are switching to the private_key_jwt method as a requirement for authenticating with those IdPs to avoid security concerns with client secret management.

### Details

An inactive PR has been open since March 2021: https://github.com/keycloak/keycloak/pull/7890

**Comment by RaffaelGrob** [comment]
Having AzureAD as upstream IDP is very common. And to avoid the use of client secrets a demand. So using certificates to authenticate is a perfect remedy. 
But why is the pull request providing the x5t headers open for a long time? Is there a concern about using the x5t header?
Or is the recommended way to authenticate to azure using SAML?
