### ISSUE TITLE
keycloak.d.ts is not updated in 18.0.1 release of keycloak-js

### ISSUE THREAD

**Issue by gwin003** [keycloak/keycloak#12945]
### Describe the bug

A fix that was committed to the keycloak-js artifact on May 12th was not included in the 18.0.1 release of keycloak-js, which was published on June 16th.
https://github.com/keycloak/keycloak/commit/cdef39f76c50506681227b627e678bdbf15779a4#diff-f20164fd1393727b823dbd6fefaeb763e07d059275f99d7af42dc68d6866c53a

### Version

18.0.1

### Expected behavior

18.0.1 would contain the fix committed in https://github.com/keycloak/keycloak/commit/cdef39f76c50506681227b627e678bdbf15779a4#diff-f20164fd1393727b823dbd6fefaeb763e07d059275f99d7af42dc68d6866c53a

### Actual behavior

18.0.1 does not contain the above fix.

### How to Reproduce?

Create a new folder on your machine
Open cmd/powershell in that folder, and run `npm install keycloak-js`
Npm will create the package.json file and node_modules folder, with the keycloak-js artifact in it.
Open the keycloak-js folder and check the package.json to verify the 18.0.1 version.
Open the `dist/keycloak.d.ts` file and search for `scope?`.
It only appears in `KeycloakLoginOptions` but is missing from `KeycloakInitOptions`.

### Anything else?

Discussion: https://github.com/keycloak/keycloak/discussions/12281

**Comment by jonkoops** [comment]
Closing this issue as this functionality has been released in Keycloak 19.
