### ISSUE TITLE
Implement "advanced claim to group" mapping for SAML

### ISSUE THREAD

**Issue by GlennButera** [keycloak/keycloak#12950]
### Description

Currently, Keycloak supports mappers for Identity Providers.  Recently the ability to map an "advanced claim to [a] group" [was added](https://github.com/keycloak/keycloak/pull/8467) as a new Mapper Type, but only implemented for "OpenID Connect v1.0" Identity Providers.  Adding the same for SAML Identity Providers would help to keep feature parity between the 2 common standards.

### Motivation

Many identity providers still utilize SAML and would like to map in groups.  It would therefore be helpful to implement the same mapper for SAML that was added for OpenID Connect.

**Comment by d4effij** [comment]
I would REALLY like to see this implemented, for now, I am looking at possibly using an event listener spi, or a modified first login flow

**Comment by paulkilla** [comment]
+1

**Comment by claudiunicolaa** [comment]
+1

**Comment by Joni-Aaltonen** [comment]
+1

**Comment by willbenica** [comment]
This would be great!
Didn't the older versions of keycloak have this? Trying to do exactly this I found step-by-step guides pointing to a `protocol mapper` named `group mapper`.
I don't know which version this was, but I can't find it now.

**Comment by AndreasKneistSIT** [comment]
This would be great!
I have included both different IDPs with SAML and with OIDC. With OIDC I can use "Advanced Claim to Group". With SAML unfortunately not. It is not understandable why there is this difference.

**Comment by IamSuhaz** [comment]
Eagerly waiting for it
