### ISSUE TITLE
Public URL autodetection from request does not work when using reverse proxy on non standard ports

### ISSUE THREAD

**Issue by AndreaVida** [keycloak/keycloak#12970]
### Describe the bug
If deployed behind a reverse proxy accessed trough a port different than 443 which does not set `X-Forwarded-Port` header, after login Keycloak tries to redirect the client to the same request url but without the port.

Example:
request url = https://example.com:31390/auth/admin
redirect url = https://example.com/auth/admin

This seems to be due to Keycloak being unable to autodetect the correct public root URL if `X-Forwarded-Port` header is not properly set (`X-Forwarded-Host` typically contains only the hostname and not the port).

Setting env var `HOSTNAME_PORT=31390` fixes the initial redirect issues but then creates another issue with admin console being inaccessible due to an "invalid redirect_url".  This is likely due to **security-admin-console** client using `https://example.com` as root url, thus making all "Valid Redirect URIs" being relative to that; however, even after editing client config to allow any redirect uri (*), the console still does not load beacuse of a 403 error.

### Version
All Quarkus-based versions (verified on 18.0.2 and 19.0.2).

### Expected behavior
The ideal scenario would be having Keycloak resolving correctly the rootUrl, as it is actually doing correctly in its WildFly version (tested with version 16.1.1). If this is not possible due to libraries used, at least there should be an env var to set a fixed custom port also for admin console access, as done for frontendUrl with HOSTNAME_PORT (either reusing it or splitting `HOSTNAME_ADMIN_URL` into `HOSTNAME_ADMIN_HOST` and `HOSTNAME_ADMIN_PORT`).

### Actual behavior
When calling `DefaultHostnameProvider.getPort(delegate, type);` at [KeycloakUriInfo.java#L48](https://github.com/keycloak/keycloak/blob/5b48d727307e12eed701916b46bf7b817ef474f6/server-spi/src/main/java/org/keycloak/models/KeycloakUriInfo.java#L48) the result returned is -1 instead of the expected result (31390 in our case).

![2022-09-26 16_20_53-KeycloakUriInfo java - keycloak  SSH_ 172 20 52 72  - Visual Studio Code](https://user-images.githubusercontent.com/12733629/194322968-12816042-a86f-451b-8d37-8385f0c8bad1.png)

### How to Reproduce?
Deploy KC behind a reverse proxy (proxy mode "edge") and configure it to be accessed trough a port different than 443 (or 80). Verify the proxy does not set `X-Forwarded-Port` header with such port.

**Comment by AndreaVida** [comment]
Update: issue still present in KC 19

**Comment by AndreaVida** [comment]
After a long investigation we figured out that our reverse proxy (Istio) was correctly setting `X-Forwarded-Proto` and `X-Forwarded-Host` headers but not setting `X-Forwarded-Port`; this made Keycloak unable to determine the original public URL trough Quarkus Vertx libraries. Forcing our proxy to add a (fixed) `X-Forwarded-Port` header solved all our issues.

However, I won't close the bug as I still consider this only as a workaround for following reasons:
- Same proxy configuration was working fine with WildFly Keycloak, despite missing header (tested version 16.1.1)
- I would expect HOSTNAME_PORT env var to have same effect as forcing a fixed port with the header, instead it solves the issue only partially (login on application is fine but admin console not)

**Comment by pedroigor** [comment]
@AndreaVida Could you please try forcing a base URL using the `hostname-url` and `hostname-admin-url` options. For more details, please look at this [guide](https://www.keycloak.org/server/hostname).

By providing a base URL can then force the HTTP scheme, host, port, and path.

**Comment by AndreaVida** [comment]
@pedroigor this would not work for us as we have multiple DNS hosts (Ingresses) which resolves to the same KC instance; only the port is fixed. This is the reason why I am asking to split this in multiple env vars (hostname-host and hostname-port for example).
