### ISSUE TITLE
Javascript adapter not initializing. Keycloak.init() never completes.

### ISSUE THREAD

**Issue by dlmorais-13** [keycloak/keycloak#12973]
### Describe the bug

Using the Javascript adapter of version `18.0.2` is not working anymore. The promise returned by function `keycloak.init()` never resolves nor rejects.

Debugging the code I could see that the promise that loads the adapter configuration (configPromise [1]) never completes, even though the function `setSuccess` on the promise is being called [2].

Debugging further, I found out the problem looks like to be in this minified es6Promise that exists on version `18`, but not on `16`. If I put a breakpoint just after initializing this minified Promise implementation and override it with the browser implementation, everything works normal.
```
# I ran this below with a breakpoint on line 19
es6Promise_min.exports.Promise = Promise
```

This problem does not occur using the adapter provided on version `16.1.1`.

1: https://github.com/keycloak/keycloak/blob/1c598aa13d600b0b20e21f7eec620f139b006669/adapters/oidc/js/src/keycloak.js#L180
2: https://github.com/keycloak/keycloak/blob/1c598aa13d600b0b20e21f7eec620f139b006669/adapters/oidc/js/src/keycloak.js#L919

### Version

18.0.2

### Expected behavior

Screenshots using `keycloak.js` of version `16.1.1`

Keycloak adapter should initialize with success, requesting user token, since I'm already logged in.

The request for user token is made succesfully.
![image](https://user-images.githubusercontent.com/17011099/178011262-11290975-1b34-4b8e-9249-c06898779a09.png)

The promise `configPromise` resolves succesfully.
![image](https://user-images.githubusercontent.com/17011099/178012530-ab27ac91-27ce-45e8-8078-32bab8e2dfed.png)

### Actual behavior

Screenshots using `keycloak.js` of version `18.0.2`

Keycloak adapter is not initializing, the method `keycloak.init()` is not resolving nor rejecting.

The request for user token is not made.
![image](https://user-images.githubusercontent.com/17011099/178011801-3cd3a4e3-99e0-49f7-9a1c-7d0afe0ded07.png)

The promise `configPromise` never resolves.
![image](https://user-images.githubusercontent.com/17011099/178012003-25ea911e-8bc1-4366-a754-31f645a54b3a.png)

### How to Reproduce?

Initialization code for reference, used with both version `16.1.1` and `18.0.2`.
_I omitted parts of the code that are not important for this issue._

```js
const kc = new Keycloak({
  url: "http://localhost:8080/auth",
  realm: "PBH-DSV",
  clientId: "openid-publico",
});

...
async mounted() {
  kc.onReady = () => this.updateAuth();
  kc.onAuthSuccess = () => this.updateAuth();
  kc.onAuthError = () => this.updateAuth();
  kc.onAuthLogout = () => this.updateAuth();
  kc.onAuthRefreshSuccess = () => this.updateAuth();
  kc.onAuthRefreshError = () => this.updateAuth();
  
  await kc.init({ onLoad: "check-sso", enableLogging: true });
},
...
```

**Comment by jonkoops** [comment]
We no longer include a polyfill for promises, so this is fixed. I am no longer able to reproduce the issue. Closing.
