### ISSUE TITLE
Quarkus Keycloak intermittently misconfigures default client scopes when importing realms

### ISSUE THREAD

**Issue by mstruk** [keycloak/keycloak#12989]
### Describe the bug

I've been experiencing intermittent failures when migrating my testsuite from legacy Keycloak to Quarkus based Keycloak. The realm token endpoint would often (but not always) return a token that's missing half of the claims it should contain.

I noticed that when the bad tokens are returned the affected client has empty 'Assigned Default Client Scopes'. If I use Keycloak Admin Console and manually add 'profile' and 'roles' to the 'Assigned Default Client Scopes' I start getting the expected tokens for the affected client.
 
The realms are automatically imported at start time from realm .json files in data/import directory. These files are prepared ahead of time and don't change between runs.

It looks like some kind of intermittent (possibly async / concurrency related) issue during parsing / configuration of realms. There are never any startup errors. 
  
See the reproducer with instruction: https://github.com/mstruk/strimzi-kafka-oauth/tree/keycloak-quarkus-issue/testsuite/keycloak-quarkus-tests

### Version

18.0.2

### Expected behavior

When importing the realm at startup the assigned default client scopes should consistently be applied every time. 

### Actual behavior

When importing the realm at startup the assigned default client scopes are sometimes applied, and sometimes not.

### How to Reproduce?

See https://github.com/mstruk/strimzi-kafka-oauth/tree/keycloak-quarkus-issue/testsuite/keycloak-quarkus-tests

**Comment by mstruk** [comment]
I don't understand the resolution status. Does it mean that you didn't manage to reproduce the issue (1) or do you acknowledge the issue (a bug) but don't think it's a problem (2) or that the issue has been fixed by some PR in the mean time and doesn't seem to be an issue any more (a fixed bug now) (3)?

Which one of the 1, 2, 3 is the verdict here?

**Comment by pedroigor** [comment]
@mstruk Sorry. I wasn't able to reproduce using `22.0.1`. Tried the steps and multiple runs of `mvn test`. Also tried setting the `KEYCLOAK_THREAD_COUNT=10`.

```
docker run --rm --name keycloak_auto_build -p 8080:8080 -p 8443:8443 -v "$PWD/../docker/certificates:/opt/keycloak/certs" -v "$PWD/../docker/keycloak/realms:/opt/keycloak/data/import" -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HOSTNAME=keycloak -e KC_HTTP_ENABLED=true quay.io/keycloak/keycloak:22.0.1 start --auto-build --import-realm --features=token-exchange,authorization,scripts --https-key-store-file=/opt/keycloak/certs/keycloak.server.keystore.p12 --https-key-store-password=changeit
```

If you are still facing the issue, we can re-open it.
