### ISSUE TITLE
quay.io/keycloak/keycloak lacks any kind of documentation

### ISSUE THREAD

**Issue by stlaz** [keycloak/keycloak#12990]
### Describe the bug

The web pages of the container images at https://hub.docker.com/r/jboss/keycloak have beautiful and thorough documentation.

The newer and fresher container images at https://quay.io/repository/keycloak/keycloak have nothing.

### Version

all

### Expected behavior

Properly document the Keycloak image at its newer location.

### Actual behavior

The image repository says:

```
Description
No repository description has been set 
```

### How to Reproduce?

Go to https://quay.io/repository/keycloak/keycloak

**Comment by stianst** [comment]
Docs are here: https://www.keycloak.org/guides

**Comment by stianst** [comment]
Update the description to link to the guides.
