### ISSUE TITLE
IDP link username is not updated

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak#13049]
### Describe the bug

We observed that when a user is linked to an IDP, and the username at the IDP is changed, the IDP link username in Keycloak will never get updated. (Even when the user re-logins and the IDP is configured with sync mode `force`).

The IDP link username seems to be displayed in the following places and it therefore would be great if it would be up-to-date:

- Admin UI: User info, tab Identity Provider Links
- in the Account UI (Account Security -> Linked accounts)

### Version

18.0.2

### Expected behavior

If a user logs in via IDP and the IDP's sync mode is `force`, the IDP link username should be updated, if the username changed at the IDP (i.e. the IDP token contains a username different from the one already stored at Keycloak).

### Actual behavior

The IDP link username is stored once (at first login) and is never updated.

### How to Reproduce?

The issue can be reproduced with two Keycloak realms. One of the realms (let's call it _consumer_) uses the other realm (let's call it _provider_) as IDP.

1. Create realm _provider_. Make sure that the option "Edit username" is enabled for the realm.
2. In realm _provider_, create a user with a name like _test_ with password credentials.
3. In realm _provider_, create a client with a name like _login-client_, with "Standard Flow Enabled" and "Access Type" _confidential_. For the purpose of this test, just allow the whole keycloak instance as redirect uri, by specifying "Root URL" accordingly (e.g. http://localhost:8180/auth).
4. Create realm _consumer_.
5. In realm _consumer_, create an IDP of type _keycloak-oidc_. Specify "Sync Mode" as _force_, and specify the required fields appropriately, e.g.:
   - Authorization URL: http://localhost:8180/auth/realms/provider/protocol/openid-connect/auth
   - Token URL: http://localhost:8180/auth/realms/provider/protocol/openid-connect/token
   - Client Authentication: Client secret as post
   - Client OD: login-client
   - Client Secret: <secret of login-client>

6. Login at the _consumer_ realm, by using the IDP _keycloak-oidc_ (_provider_ realm). For example you can use the account console to login: http://localhost:8180/auth/realms/consumer/account/. Fill out the user profile form with arbitrary values.
7. Check (via Admin UI) that the user has been created in the _consumer_ realm and it contains an IDP Link entry with "Provider Username"  _test_.
8. Logout from both _consumer_ and _provider_ realm (clearing cookies also works).
9. Change the username of user _test_ in the _provider_ realm, e.g. to _test1_.
10. Again login at the _consumer_ realm, using the IDP.
11. When checking the IDP link entry of the _consumer_ realm user (via Admin UI), it still has "Provider Username"  _test_, but it SHOULD BE _test1_.

**Comment by scan0qr** [comment]
This issue still persist for users which are not federated. We are using keycloak : 20.0.2.

**Comment by danielFesenmeyer** [comment]
> This issue still persist for users which are not federated. We are using keycloak : 20.0.2.

What do you mean with "not federated"? LDAP?
