### ISSUE TITLE
 Conditional Flow Loop

### ISSUE THREAD

**Issue by Jess103** [keycloak/keycloak#13044]
### Describe the bug

Hi,

I'm using multiple conditions in Authentication Flow.
The weird thing is that it goes back and check the previous confitions again after the last execution.
(I'm not really sure if this is a bug or an expected behavior; please let me know if it's the latter one.)

---

**[Authentication Flow]**
(I already tested Kerberos; it works fine.)
* Kerberos (Required)
* Flow1 (Conditional)
   * Condition1 (Required) - Check custom parameter if user wants usr-pw-form [SPI]
   * Execution1 (Required) - Username Password Form
* Flow2 (Conditional)
   * Condition2 (Required) - Check if user is not allowed to log in [SPI]
   * Execution2 (Required) - Deny Access
* Flow3 (Conditional)
   * Condition3 (Required) - Check if user needs MFA [SPI]
   * Execution3 (Required) - MFA [SPI]

### Version

18.0.1

### Expected behavior

1. Kerberos works fine
   * Go to Flow1
2. Test account doesn’t meet Condtion1 (=false)
   * Go to Flow2
3. Test account doesn’t meet Condtion2 (=false)
   * Go to Flow3
4. Test account meets Condition2 (=true)
   * Do the execution 3 correctly > (allow acces)

### Actual behavior

1. Kerberos works fine
   * Go to Flow1
2. Test account doesn’t meet Condtion1 (=false)
   * Go to Flow2
3. Test account doesn’t meet Condtion2 (=false)
   * Go to Flow3
4. Test account meets Condition2 (=true)
   * Do the execution 3 correctly
5. Check Condition1 again
   * can't get the custom parameter I sent in the beginning
   * null exception is done in the code > go to the next step
6. Check Condition2 again
   * can't get the custom parameter I sent in the beginning
   * null exception is not done in the code > throw “KC-SERVICES0013: Failed authentication: java.lang.NullPointerException”

### How to Reproduce?

**Authentication Flow**
1. Same as the flow in the beginning
2. Or replace Kerberos > UsernamePasswordForm would also work I think...
(Just make sure it's false for the condition 1)

**SPI**
* Check custom parameter if user wants usr-pw-form
   * "true" if pram1 exists
* Check if user is not allowed to log in
   * "true" if param2=Y
* Check if user needs MFA
   * "true"

**Client(OIDC)**
https://<KEYCLOAK_URL>/realms/<KEYCLOAK_REALM>protocol/openid-connect/auth?client_id=<KEYCLOAK_CLIENT>&redirect_uri=<REDIRECT_URL>&state=<RANDOM_UUID>&response_mode=query&response_type=code&scope=openid&**param2=Y**

---

**[Questions]**

**1. How can I make the Conditional Flow as I expect?**
   * I tried alternative too, but this isn’t the one I want.
   * Why does it check the false conditions again?

**2. How can I use the custom parameters again?**
   * I hard-coded the parameters in the condition SPI for the null case (step4~5 in Actual behavior)
   * Then this goes 1~5, then allows access
   * How can I make the executions to send the custom parameters as well?

**Comment by OleksanderRudenko** [comment]
Same issue here. My flow is organized in the next way:
- Flow_1 (Requirement.Conditional)
- - Conditional_1
- - Execution_1
- - - Flow_2 (Requirement.Conditional)
- - - - Conditional_2
- - - - Execution_2

Chrome Browser. When I am on Execution_2 by pressing refresh page(F5) it starts to check Conditional_1 again. If you press F12 and go to the Network tab you will see some weird requests with status code 302.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
