### ISSUE TITLE
500 error when accessing user role mappings tab

### ISSUE THREAD

**Issue by RManesiya** [keycloak/keycloak#13055]
### Describe the bug

After selecting the user id link in a realm and then clicking on `Role Mappings` tab a pop dialog is displayed with following error in red. If that same id is selected again and then clicking on  `Role Mappings` the error does not occur and the `Available Roles` list box is populated.

"Error! An unexpected server error has occurred."

### Version

18.0.0

### Expected behavior

`Available Roles` list box must populate and should not return an error.

### Actual behavior

Available Roles list box is empty and a pop dialog is displayed "Error! An unexpected server error has occurred."

**Google Chrome Network tab shows**

Request URL: https://idpkcserver/admin/realms/idp/users/[USERGUID]/role-mappings/realm/available
Request Method: GET
Status Code: 500 Internal Server Error

**Google Chrome developer console shows**

{
	"data": {
		"error": "unknown_error"
	},
	"status": 409,
	"config": {
		"method": "GET",
		"transformRequest": [
			null,
			null
		],
		"transformResponse": [
			null
		],
		"jsonpCallbackParam": "callback",
		"url": "https://idpserver/admin/realms/idp/users/[USERGUID]/role-mappings/realm",
		"headers": {
			"Accept": "application/json, text/plain, */*",
			"Authorization": "Bearer eyJhb..."
		}
	},
	"statusText": "Conflict",
	"xhrStatus": "complete",
	"resource": []
}

### How to Reproduce?

1. Select a realm
2. Under Manage click on Users.
3. Select user under ID column by clicking on the hyperlink with GUID.
4.  Click on `Role Mappings` tab.

**Comment by ssilvert** [comment]
I'm going to go ahead and close this.  We aren't working on the old console any more.  If you see the same kind of issue in the new admin console, we can reopen.
