### ISSUE TITLE
Move non-map-storage related classes to new package

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#13081]
### Describe the bug

In #12963, the new implementation `DisabledStickySessionEncoderProvider` was created to enable Keycloak to be run without Infinispan. 

This implementation should move to a different module, as this is not storage related. Possibly move this to `server-spi-private` where the SPI lives, as this is actually a dummy implementation for that SPI. Possible new package: `org.keycloak.sessions` or a sub-package.

### Version

999-SNAPSHOT

### Expected behavior

Only storage related providers should be in the map module.

**Comment by ahus1** [comment]
@hmlnarik - it would be great if you could comment if these classes should be moved as suggested above. I'll then be happy to create a matching PR. 

Thanks!

**Comment by hmlnarik** [comment]
I agree with the suggestion, it should be moved to `server-spi-private` module and `org.keycloak.sessions` package.
