### ISSUE TITLE
ADMIN REST API : /{realm}/groups?search=xxx does not work with briefRepresentation=false

### ISSUE THREAD

**Issue by christopheblin** [keycloak/keycloak#13088]
### Describe the bug

When you call `/myrealm/groups?briefRepresentation=false`, each result contain subGroups

When you call `/myrealm/groups?briefRepresentation=false&search=XXX`, each result DOES NOT contain subGroups anymore

### Version

18

### Expected behavior

Fill the subGroups when briefRepresentation=false independently of the search query param

### Actual behavior

![Capture d’écran 2022-07-13 à 16 01 51](https://user-images.githubusercontent.com/11044877/178752681-5b5bda37-be44-4855-b805-4c4011ce24f2.png)
![Capture d’écran 2022-07-13 à 16 01 23](https://user-images.githubusercontent.com/11044877/178752691-3f81e55c-6234-4511-9a8c-7a3c42b709d8.png)

**Comment by christopheblin** [comment]
@lexcao Thanks for answering

I was using KCK 14 and when I upgrade to KCK 18 it breaks : can you confirm this is an intended breaking change that is documented somewhere (I did not find anything related to this part in the doc) ?

**Comment by christopheblin** [comment]
@lexcao I just tested again from the admin console to be sure, and this is exactly what you said : subgroups are filtered by the `search` parameter

I have groups like these
```
apps
  app-1
  app-2
```

The query I am testing
```
auth = "Bearer ..." //to take from another query in the Networks panel of chrome dev tools
tmp = await fetch("https://auth.svc/auth/admin/realms/master/groups?briefRepresentation=false&search="+search, {
  "headers": {
    "authorization": auth
  },
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
JSON.stringify(await tmp.json())
```

With KCK 14
```
search = apps -> "[{"name":"apps",subgroups:[{"name":"app-1"}, {"name":"app-2"}]}]
search = app-2 -> "[{"name":"apps",subgroups:[{"name":"app-1"}, {"name":"app-2"}]}]
```

With KCK 18
```
search = apps -> "[{"name":"apps",subgroups:[]}] //no children match the search, they are all excluded even if I specify briefRepresentation=false
search = app-2 -> "[{"name":"apps",subgroups:[{"name":"app-2"}]}]
```

-> do you confirm this is intented ?

**Comment by lexcao** [comment]
Hi, @christopheblin 
Thanks for your investigating, and sorry for my less confirmation with KCK 14.

I found [this commit](https://github.com/keycloak/keycloak/commit/17da3ee8d94784bbf201824b813528f51ae1679b) changes the search behavior.

So while searching groups by the search parameter it will apply filtering in the name of all subgroups.

Let's say, we have groups like this:
```
apps
- app-1
- app-2
```
When searching.
```
search = apps -> "[{"name":"apps",subgroups:[{app-1}, {app-2}]}]"
search = app-2 -> "[{"name":"apps",subgroups:[{app-2}]}]"
```

I wonder if is there the same group data from your side testing from KCK 14 to 18 ?

**Comment by christopheblin** [comment]
@lexcao I still do not understand the reason behind what was done to filter subGroups of a MATCHING group

I mean: if my group MATCHES the search, then why the subGroups of this group are also filtered ?

However, I understand that if a subgroup X MATCHES the search, then its parents (for ex, P1 and P2) are included in the result and not its brothers. But then, I expect the subGroups of X to NOT be filtered (subGroups of P1 just contain P2 and subGroups of P2 just contain X)

Anyway, I will adapt to this behavior by just requesting all groups (i.e without search parameter) and performing the search client-side

Thanks for the clarifications

**Comment by pedroigor** [comment]
There were significant changes to the Group API. Please, try using the latest release to make sure the report still makes sense.
