### ISSUE TITLE
'Condition - User Configured' does not work for 'Recovery Authentication Code Form'

### ISSUE THREAD

**Issue by pdt-ayidi** [keycloak/keycloak#13093]
### Describe the bug

Here's the authentication flow:
<img width="840" alt="Screen Shot 2022-07-13 at 10 40 47 AM" src="https://user-images.githubusercontent.com/66796521/178797897-42e7b6b2-a912-46a9-bf65-454f4bf53807.png">

User `test2` does not have recovery codes configured, and the following option still shows up:
<img width="670" alt="Screen Shot 2022-07-13 at 10 40 34 AM" src="https://user-images.githubusercontent.com/66796521/178798103-d2f87b79-9999-45c4-ad9e-9667d40bd073.png">

When clicking on the recovery codes option, the user gets a confusing error:
<img width="610" alt="Screen Shot 2022-07-13 at 10 40 18 AM" src="https://user-images.githubusercontent.com/66796521/178798330-d321f56b-9978-418d-8813-aeb3e1514be9.png">

### Version

18.0.2

### Expected behavior

<img width="670" alt="expected" src="https://user-images.githubusercontent.com/66796521/178798542-e9b00626-8754-45a3-a75a-6785053d6e70.png">

### Actual behavior

<img width="670" alt="Screen Shot 2022-07-13 at 10 40 34 AM" src="https://user-images.githubusercontent.com/66796521/178798103-d2f87b79-9999-45c4-ad9e-9667d40bd073.png">

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.
