### ISSUE TITLE
Session expiration settings

### ISSUE THREAD

**Issue by wangjie-zzz** [keycloak/keycloak#13100]
### Describe the bug

My operation is: 
Created a wj-test realm and admin user.
In "Realm Settings => Tokens", I adjusted the following two parameters：
![7BLKn5RQyT](https://user-images.githubusercontent.com/65529061/178909653-cd685ac1-ff49-4c02-9621-64ee81e8208c.jpg)

Two minute after I log in.
In "users=>sessions", I can still query this session, which is valid.
![BSfuZPNMN5](https://user-images.githubusercontent.com/65529061/178909680-d5f0822c-2c86-4fb6-acff-0f35c3d92d19.jpg)

After waiting for about eight to nine minutes, it disappeared.
![W5GG376Llz](https://user-images.githubusercontent.com/65529061/178909719-d08100cf-ba80-4c02-80dd-22f0da55aec4.jpg)

### Version

16.1.1

### Expected behavior

When I log in for two minutes, it should be invalid

### Actual behavior

After waiting for about eight to nine minutes, it disappeared.

**Comment by wangjie-zzz** [comment]
The client code is as follows:
![hpoa78HNmk](https://user-images.githubusercontent.com/65529061/178910508-b1837dde-aba7-4903-93e3-30aa012bcd42.jpg)

**Comment by stianst** [comment]
The session will be invalid after the expected time, but it is not garbage collected until some later time when the background garbage collection runs.
