### ISSUE TITLE
Sessions not removed when Client Session Idle and Max is set

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#13105]
### Describe the bug

See https://issues.redhat.com/browse/KEYCLOAK-18718

### Version

14.0.0

**Comment by marcelomrwin** [comment]
According to issue https://issues.redhat.com/browse/KEYCLOAK-18718 we tried to reproduce it using Keycloak version 14 but we couldn't reproduce it. We created a client as directed to reproduce the problem but we were not able to observe any of the mentioned behaviors: 

- Negative values for "exp" 
- The invalid session remaining indefinitely

Also in version 18.x we did not observe this behavior

**Comment by mposolda** [comment]
@marcelomrwin Thanks! I am closing based on this. This can be re-opened if there are more accurate steps to reproduce as this may not be trivial to simulate.
