### ISSUE TITLE
Conditionally enable and disable CLI options

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#13113]
### Description

Options might not make sense if some other option is used when running the CLI. This is especially true when using build options that usually enable or disable a specific provider and its configuration.

It might make sense to conditionally enable/disable options depending on the build options set so that the CLI reflects the configuration state of the distribution. This capability can potentially consider the values set to options too.

A use case for this capability is related to the new store integration and the middle/long-term support for the legacy store. The legacy store relies on a cache configuration whereas the new store does not provide any cache settings but its own way to structure different stores in a tree store. 

Another example is to remove the `db` option completely when `storage=jpa|chm`.

Right now is a bit confusing to see:

```
Cluster:

--cache <type>       Defines the cache mechanism for high-availability. By default, a 'ispn' cache
                       is used to create a cluster between multiple server nodes. A 'local' cache 
                       disables clustering and is intended for development and testing purposes.
                       Default: ispn.
--cache-config-file <file>
                     Defines the file from which cache configuration should be loaded from. The 
                       configuration file is relative to the 'conf/' directory.
--cache-stack <stack>
                     Define the default stack to use for cluster communication and node discovery.
                       This option only takes effect if 'cache' is set to 'ispn'. Default: udp. 
                                                                                               
Storage (Experimental):
                                                                                               
--storage <type>     Experimental: Sets a storage mechanism. Possible values are: jpa, chm.
                                                                                               
Database:
                                                                                               
--db <vendor>        The database vendor. Possible values are: dev-file, dev-mem, mariadb, mssql,
                       mysql, oracle, postgres. Default: dev-file.
```

And have the `db` or `cache` options available even though the distribution is configured as follows:

```
kc.sh build --storage chm
```

I would expect to see this instead:

```
Storage (Experimental):
                                                                                               
--storage <type>     Experimental: Sets a storage mechanism. Possible values are: jpa, chm.
```

And potentially unlock more options after choosing a specific `storage`.

At the same time, I'm not sure about the UX when you have a vanilla distribution. If we should show all options and filter them afterwards or if we should impose some flow through the CLI so that options are unlocked only after some initial configuration is done. For instance, suppose you just extracted a distribution and you run:

```
kc.sh build -h
```

It would show the following help because `legacy` storage is enabled by default:

```
Cluster:

--cache <type>       Defines the cache mechanism for high-availability. By default, a 'ispn' cache
                       is used to create a cluster between multiple server nodes. A 'local' cache 
                       disables clustering and is intended for development and testing purposes.
                       Default: ispn.
--cache-config-file <file>
                     Defines the file from which cache configuration should be loaded from. The 
                       configuration file is relative to the 'conf/' directory.
--cache-stack <stack>
                     Define the default stack to use for cluster communication and node discovery.
                       This option only takes effect if 'cache' is set to 'ispn'. Default: udp. 
                                                                                               
Storage (Experimental):
                                                                                               
--storage <type>     Experimental: Sets a storage mechanism. Possible values are: jpa, chm, legacy. Default: legacy.
                                                                                               
Database:
                                                                                               
--db <vendor>        The database vendor. Possible values are: dev-file, dev-mem, mariadb, mssql,
                       mysql, oracle, postgres. Default: dev-file.
```

Note the change to `storage` description:

>--storage <type>     Experimental: Sets a storage mechanism. Possible values are: jpa, chm, legacy. Default: legacy.

Now, after setting `storage=chm` using the `build` command, the result would be just:

```
Storage (Experimental):
                                                                                               
--storage <type>     Experimental: Sets a storage mechanism. Possible values are: jpa, chm, legacy. Default: legacy.
```

I don't know if Picocli supports a construct like that:

```
kc.sh build --storage chm --help
```

Where `help` will show the message with only the options available for the `storage=chm`. The same goes for `start --storage chm --help`.

Also, when running :

```
kc.sh start --storage chm --cache local
```

You should get an error saying the `cache` is unknown because of the `storage` option being set to `chm`.

### Motivation

Improve UX by hiding options that should not be set when other options are set.

### Details

Not sure how much this is feasible (UX and code-wise) or if just complicates more the UX. I have a feeling that it provides a more concise usage and understanding of the available options.
```[tasklist]
### Follow-up Tasks
- [ ] https://github.com/keycloak/keycloak/issues/27025
- [ ] https://github.com/keycloak/keycloak/issues/27026
```

**Comment by vmuzikar** [comment]
While this was mainly focused on providing optimal UX for the new store (which is now being removed), conditional CLI options will be required for https://github.com/keycloak/keycloak/issues/24252.

**Comment by vmuzikar** [comment]
@shawkins Would this be something you would be able to look into. The scope of this would be to do any needed refactoring to disable options as needed.

**Comment by shawkins** [comment]
@vmuzikar yes I can take a look.  

Do we have captured somewhere what all of the exclusive option relationships are?

@pedroigor to clarify you are saying that user would do:

```
kc.sh build --storage chm
kc.sh start --help
```
And expect to see a pruned set of options for start, is that correct?

Later you show this form
```
kc.sh build --storage chm --help
```
With the expectation that there would be a conditional processing of the help based upon existing cli options.  This seems almost like a form of command completion and introduces an ordering or feedback mechanism into picocli that we currently don't have.  Given that we'd persue valiation of conflicting options, I wouldn't attempt this.





-

**Comment by vmuzikar** [comment]
> Do we have captured somewhere what all of the exclusive option relationships are?

I think with the current removal of the new store (and `--storage` option) there are none. But there will be with the new hostname impl. When a profile feature is active, we will add new options and remove old.

**Comment by shawkins** [comment]
> But there will be with the new hostname impl. When a profile feature is active, we will add new options and remove old.

Ok, I see the proposal to control that via --features hostname2.  It seems straight-forward to check for this feature flag in the same spot that the non-cli validation is being done.

The additional validations called out on that issue could be implemented at this level as well. 

I don't think there needs to be any proactive changes to support this, it can be added once the changes are made to support the new options.

**Comment by vmuzikar** [comment]
@shawkins I'm thinking that we might need a bit more than just validations as we also need the `--help` option to properly show only enabled options.

**Comment by shawkins** [comment]
> @shawkins I'm thinking that we might need a bit more than just validations as we also need the --help option to properly show only enabled options.

Rewriting the above examples, that seems straight-forward as:

```
kc.sh build --features hostname2
kc.sh start --help
```
But less so with:
```
kc.sh build --features hostname2 --help
```
Would you expect filtering in both cases?

**Comment by vmuzikar** [comment]
> Would you expect filtering in both cases?

Yes, plus
```
kc.sh start --features hostname2 --help
```

**Comment by vmuzikar** [comment]
> But less so with:
> 
> ```
> kc.sh build --features hostname2 --help
> ```

Actually, we'll be filtering out only runtime options in case of the new hostname impl, so this is not relevant to our use case.

**Comment by shawkins** [comment]
> kc.sh start --features hostname2 --help

I'll see what could make sense here, it kind of goes against typical cli patterns - which would normally let commands / subcommands dictate options, not other options.

**Comment by pedroigor** [comment]
@shawkins What you have discussed with @vmuzikar is exactly what this issue is about.

At that time, the idea was to rely on the configuration categories to enable and disable options. For instance, in the case of the new store, we would remove `database` and `cache` categories when you have set options from the `storage` category.

Not sure if we have a valid use case for this issue anymore as the new store is being removed. It is a nice capability but not sure if still worthy?
