### ISSUE TITLE
keycloak(behind nginx)  .well-known/openid-configuration  path not return correct token or jwt url（custom port loss）

### ISSUE THREAD

**Issue by ly123-liu** [keycloak/keycloak#13148]
### Describe the bug
we use keycloak as an ldp provider,  keycloak is deployed behind nginx proxy with two domains: one public domain( set in fronturl in realms settings) and another domain with custom port (see 172.18.4.33:30733)

in keycloak realm, we set fronturl（public domain） for extranet login（extranet users）, while we have another scenario for intranet use（don't want go public domain call），intranet service first calls xxx/.well-known/openid-configuration url to get token path , the .well-known/openid-configuration returns keycloak auth / token / userinfo / jwt  url ,  we use above return jwt url to verify token ,

when we use 172.18.4.33:30733（nignx proxy） as host to get keycloak .well-known/openid-configuration, we found jwt url is not right , except  jwt url as http://172.18.4.33:30733/auth/realms/<name>/protocol/openid-connect/certs ,  
but get http://172.18.4.33/auth/realms/<name>/protocol/openid-connect/certs

while in keycloak 12.04 every thing is ok, why is that ？

keycloak config:
env:
  KC_HOSTNAME: "xxxx"
  KC_HOSTNAME_STRICT: 'true'
  KC_HOSTNAME_STRICT_HTTPS: 'true'
  KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
  KC_PROXY: edge
  KC_HTTPS_CLIENT_AUTH: none
  KC_LOG_LEVEL: debug
  KC_HTTP_ENABLED: 'true'
  KC_HTTP_PORT: 8080
  KC_HTTP_RELATIVE_PATH: /auth
  KC_CACHE_STACK: kubernetes
  KC_CACHE: ispn
  KC_CACHE_CONFIG_FILE: conf/cache-ispn.xml
  JAVA_OPTS_APPEND: -Xms512m -Xmx1024m -Djgroups.dns.query=keycloak-qiming.qiming-qe2.svc.cluster.local

test results：
with nginx proxy， nginx port is 80， seems ok：

![WeChatWorkScreenshot_fe36a46f-6f96-48f4-811d-cf5daad4a070](https://user-images.githubusercontent.com/57338370/179248657-4fde6d2d-58d5-4ecf-8a09-cedb50a4c600.png)

another nginx with custom port ,see 172.18.4.33:30733, not work
![WeChatWorkScreenshot_5eb98741-5386-4d0b-91ac-da5fc1351b54](https://user-images.githubusercontent.com/57338370/179249840-65bccad2-bbee-4d59-8a9a-bac2c6ec3084.png)

### Version

17.0

### Expected behavior

keycloak /auth/relms/<name>/.well-known/openid-configuration returns with browser domain+port

### Actual behavior

custom port is not added to token or jwt url

**Comment by ly123-liu** [comment]
can someone follow this issue ? thanks ?

**Comment by regilero** [comment]
It seems the KC_HOSTNAME_PORT env variable could fix that, but it open other issues:

* #12970
* #12823

**Comment by andre-nascimento-rh** [comment]
Hello, @ly123-liu ,


It seems this issue could be solved If you apply what @regilero described on his previous comment. Please, try it with Keycloak 18.0.2 or above (the latest version preferrably, If it is possible), and let us know If the attempt worked properly or not.

I'm closing thia issue now, but feel free to reopen it If you the error/problem persists, Ok?

Thanks.
