### ISSUE TITLE
[ RP-Initiated Logout] support of client_id parameter

### ISSUE THREAD

**Issue by etchepar** [keycloak/keycloak#13188]
### Description

Hello,
Currently, KC 18 extracts the client_id from the idToken received via the parameter id_token_hint.

According to the specs [post_logout_redirect_uri, ](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout), the parameter client_id can be used with or without the id_token_hint.

### Motivation

This support will allow to support more use case and allow more uses cases and particularly the one described in the specs : 
"The most common use case for this parameter is to specify the Client Identifier when post_logout_redirect_uri is used but id_token_hint is not"

**Comment by sschu** [comment]
@etchepar If I am not mistaken that's already implemented in main.

**Comment by etchepar** [comment]
> 

thank you... I was only looking in the tag 18.0.2, my bad,

Sorry
