### ISSUE TITLE
keep k8s operators usability

### ISSUE THREAD

**Issue by Stefanqn** [keycloak/keycloak#13204]
### Description

we're currently using k8s operator v18-legacy. 

Comparing the CRDs of v18 and v20 CRDs, the usability has suffered from my perspective. We're using the operator to add service-specific Keycloak clients (`KeycloakClient`) within the Helm charts of our microservices, keeping them together and touching just one repository. 

Is it planned to provide similar usability with the new operator as with the old one?

**Comment by abstractj** [comment]
@Stefanqn it's quite unclear to me how this is an enhancement request. For questions, please use GitHub discussions or the Keycloak user mailing list. If you would like to be more specific about which kind of enhancements in the Operator you suggest, or if you would like to contribute, please reopen adding more details.

cc @vmuzikar

**Comment by vmuzikar** [comment]
@Stefanqn Hello, thank you for your interest in the new Operator. We currently support only [Realm import](https://www.keycloak.org/operator/realm-import.html) (incl. all sub-resources, e.g. Clients), however we do plan to add new CRDs for cloud-native management of Clients etc., leveraging the new Store architecture. Unfortunately, I don't yet have more details to share with you.

**Comment by sathieu** [comment]
https://www.keycloak.org/2022/09/operator-crs
