### ISSUE TITLE
Health Check base path changable

### ISSUE THREAD

**Issue by cgomm** [keycloak/keycloak#13202]
### Description

The current `KC_HOSTNAME_PATH` environment variable will change the entire path for the keycloak application but the health endpoint is still available within the path, ignoring this change. 

### Motivation

By using keycloak in ha-cluster we are using readiness checks for each application running within the cluster. each application has an own base path, in our case `<DNS A record>/keycloak` for example. This will help us to route the traffic through our load balancer. But the health check does not meet these requirements. 
 

### Details

Adding `KC_HOSTNAME_HEALTH_PATH` would allow users to change this if needed.

**Comment by shawkins** [comment]
Resolving as out of date. With the management interface enabled, the health path will be relative to the managment root path, which is now configurable via http-management-relative-path.
