### ISSUE TITLE
keycloak not translating text correctly using selenium under robot framework

### ISSUE THREAD

**Issue by johnmusa1957** [keycloak/keycloak#13218]
### Describe the bug

When going to specific hrefs in keycloak directly as the starting url the page does not translate to english correctly and therefore does not display correctly when screen capturing the page in selenium through robot framework.

Here is an image showing what is being captured.

![Screenshot 2022-07-19 17 02 38](https://user-images.githubusercontent.com/56207392/179848444-de65b8fc-c89c-4812-9ba1-7ae6a59b563b.png)

Internationalization under Themes has been enabled and only en language enable, and as well use of ?ui_locales=en within the url does not resolve.

How should selenium be configured via robot framework to ensure the page displays as in the image below?

![Screenshot 2022-07-19 17 10 98](https://user-images.githubusercontent.com/56207392/179849026-96d4b092-dff8-48d0-b715-db12b8a54eaa.png)

### Version

16

### Expected behavior

Screen displays correctly without the {{:: 'text' | translate}} ... but shows the 'text' in english.

### Actual behavior

The screen shot comparison shows the issue, and keycloak is not testable via automation using robot framework/selenium.

### How to Reproduce?

Issue is reproducible upon running a robot test using selenium.

**Comment by lexcao** [comment]
Hi, 
It seems the `js` is not loaded properly.
Could you please try to check the javascript setting with your robot configuration?

Could you try to view the console logs of the browser from the robot framework?
