### ISSUE TITLE
Exception not handled on Custom EventProvider transaction

### ISSUE THREAD

**Issue by fenos** [keycloak/keycloak#13226]
### Describe the bug

When creating a custom EventListenerProvider and using `enlistPrepare` within the event handler

```
@Override
    public void onEvent(Event event) {
            // ...
            session.getTransactionManager().enlistPrepare(transactionImplementation)
   }
```

if the `commitImpl` throws a RuntimeException I end up receiving an empty 500 response during registration (See Image)

### Version

18.0.2

### Expected behavior

I'm expecting to receive the error page message saying that an error occurred

### Actual behavior

returns empty 500 response during registration submit (see image)

 ![Screenshot 2022-07-20 105153](https://user-images.githubusercontent.com/4754064/179998631-07b84ecc-45bb-44e9-a1d4-c556a6a91841.png)

### How to Reproduce?

throw a RuntimeException in the `commitImpl` of the AbastractKeycloackTransaction` implementation.

Register the implementation within the `enlistPrepare` on the session transaction manager:

```
session.getTransactionManager().enlistPrepare(transactionImplementation)
``` 

### Anything else?

Is there any workaround for now?

**Comment by mposolda** [comment]
Adding to Backlog. Also it is not clear if this is real bug or rather incorrect usage. So may need to be investigated.

It may help if you try with latest Keycloak 21 release and/or also if you add some exception stacktrace displayed in the server log (if any). If not any stacktrace, you can try to enable TRACE logging if something is added to the log.
