### ISSUE TITLE
--verbose option doesn't work in Quarkus distribution

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13250]
### Describe the bug

When there is an error during Keycloak startup there is the following error message:
```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (Quarkus Main Thread) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
However, if I add `--verbose` parameter (for example: `./kc.sh start-dev --verbose`) it fails with:
```
Unknown option: '--verbose'
```

### Version

main

### Expected behavior

`--verbose` parameter works or Keycloak doesn't suggest using it.

### Actual behavior

Keycloak suggests using `--verbose` parameter but it doesn't work.

### How to Reproduce?

`./kc.sh start-dev --verbose`

**Comment by mabartos** [comment]
@mhajas AFAIK, the `--verbose` is considered as an option, and according to the helper guide, options are positioned before commands. Therefore, this command should work as expected: `./kc.sh --verbose start-dev`. 

On the other hand, I'd say it'd be good to have the possibility to define those options regardless of their position.

**Comment by mhajas** [comment]
Thanks for the response @mabartos! You are right, it works this way. Let's leave this open, maybe there is a way to make it also work the other way.

**Comment by mhajas** [comment]
Yes, you are right.

**Comment by iankko** [comment]
@abstractj @mhajas @mabartos Unless you want to close this issue, I would take it. Hit it recently trying to debug (get more reasons about the failure to start) trying to start Keycloak image with random CLI options.

The fix seems to be pretty straightforward, so unless you want to keep this as learning issue for someone else, I would fix it as part of my onboarding.

Let me know

Thanks,
Jan

**Comment by mabartos** [comment]
@iankko Thanks for bringing this up again. Assuming the fact we're facing this issue even inside the team, the community might encounter that for sure as well. 

We should improve UX:
1. at least improve the log message when this case occurs
2. not require a specific order of the property (after that, we'd be able to use it everywhere)

I'd slightly lean toward the 2. option. We'd probably need to move the property to the AbstractCommand in order to be able to use it in all commands. 

WDYT?

**Comment by abstractj** [comment]
@iankko it makes sense to keep it open

@mabartos  +1000 about option 2
