### ISSUE TITLE
KeyCloak User Attribute Save Failed when Claim JSON Type used as JSON

### ISSUE THREAD

**Issue by krishna-kunderu** [keycloak/keycloak#13257]
### Describe the bug

Created a Protocol Mapper UserAttribute with Claim JSON Type as JSON
![image](https://user-images.githubusercontent.com/99324244/180262351-42a4195b-1698-4799-b76b-1901de46c76b.png)

Then Created an UserAttribute same as the name created in Protocol Mapper
The following JSON is added to the spidmapper user attribute and tried saving in UserAttribute screen as below. Giving error from the admin console "User Could not be updated"

JSON value added to the attribute is 
`[{
	"serviceProviderId": "1001",
	"layout": {
		"headerBackground": "linear-gradient(194.89deg, #08c8fd 1.6%, #04647f 90.5%)",
		"headerFontHexCode": "#ffffff",
		"navbarIconHexCode": "#ffffff",
		"spLogoUrl": "../../assets/images/logo.svg",
		"locale": "en-US"
	},
	"navbar": [{
		"title": "Home",
		"icon": "home",
		"className": "active",
		"link": "/home"
	}, {
		"title": "Party",
		"icon": "customer",
		"className": "active",
		"link": "/party"
	}, {
		"title": "Customer",
		"icon": "party",
		"className": "active",
		"link": "/customer"
	}, {
		"title": "Contacts",
		"icon": "contacts",
		"className": "active",
		"link": "/contact"
	}, {
		"title": "Account",
		"icon": "accounts",
		"className": "active",
		"link": "/account"
	}, {
		"title": "Subscriptions",
		"icon": "subscriptions",
		"className": "active",
		"link": "/subscriptions"
	}, {
		"title": "Products",
		"icon": "products",
		"className": "active",
		"link": "/products"
	}, {
		"title": "Cases",
		"icon": "cases",
		"className": "active",
		"link": "/cases"
	}]
}]`

![image](https://user-images.githubusercontent.com/99324244/180262753-c87adcf4-9b78-48d4-9a08-e995644910c9.png)

### Version

1.18

**Comment by ssilvert** [comment]
We aren't working on the old admin console any more so I'm going to close this issue.  I could not create this problem in the new console.  If you see a similar issue in the new `admin.v2` console, we can reopen.
