### ISSUE TITLE
KC_HOSTNAME_STRICT_HTTPS is not documented

### ISSUE THREAD

**Issue by LelouBil** [keycloak/keycloak#13270]
### Description

Hello, I had some troubles with enable http access to a keycloak instance and found mentions of the environment variable 
"KC_HOSTNAME_STRICT_HTTPS" online.

Setting it to false worked for my use case, however I could not find it at https://www.keycloak.org/server/all-config

**Comment by shawkins** [comment]
strict https was removed in KC25
