### ISSUE TITLE
Keycloak can't resolve theme-resources/resources/partials from different classpaths

### ISSUE THREAD

**Issue by gelm0** [keycloak/keycloak#13278]
### Describe the bug

Hi, we have our own developed Getty Social Provider plugin which we have used for a while in our Keycloak project. We now need to integrate with Apple as well. Keycloak does not support this natively so we looked around for some community developed plugins before trying to write our own.

We found two that looked promising.
1. https://github.com/klausbetz/apple-identity-provider-keycloak
2. https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider

Trying both out though we have ran into an issue which. Both plugins are found and loaded by Keycloak, but we are not able to display the page of the Identity provider plugin, we simply get a 404.

Now I have been able to circumvent this in two ways.
1. I disable our Getty plugin and the Apple one works fine. Obviously this is not viable as we need to use them both.
2. I incorporate the code of any of above plugins into our repository and compiling them from the same classpath. This also works for both plugins.

So having read through https://github.com/keycloak/keycloak/issues/10951 this issue as well, I suspect that there is still an issue how Quarkus loads the themes of the different supplied JARs to Keycloak. I am happy to provide more information if you should need it.

### Version

18.0.2

### Expected behavior

Keycloak shows the provider plugin page.

### Actual behavior

A http response with 404 is shown to us, where Keycloak can't find the theme resource.

### How to Reproduce?

Load two separate SocialIdentityProviders by supplying them in different Jars. Whoever is picked up by the classpath loader first works in Keycloak, while the latter throws a 404 while trying to load it's identity provider page.

**Comment by cbaker-s1** [comment]
Noticed (probably) the same on 19.0.0 and was able to work around it by adding a dummy `ThemeResourceProviderFactory` into one of my plugins. I don't even need to configure it, its existence in one plugin alone seems to be enough to fix theme-resources for all plugins.

```java
public class DummyFlatClasspathThemeResourceProviderFactory extends FlatClasspathThemeResourceProviderFactory {
    @Override
    public String getId() {
        return "flat-classpath-dummy";
    }
}
```

`META-INF/services/org.keycloak.theme.ThemeResourceProviderFactory`

```
your.package.DummyFlatClasspathThemeResourceProviderFactory
```

Debugger shows that `configureThemeResourceProviders` is not getting called if there isn't at least one plugin adding a `ThemeResourceProviderFactory`:

https://github.com/keycloak/keycloak/blob/19.0.0/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L315-L317

**Comment by pedroigor** [comment]
@gelm0 There is a bug that should be fixed by https://github.com/keycloak/keycloak/pull/13521.

It is basically the same behavior you get when adding the dummy provider.

Basically, that change makes sure the `FlatClasspathThemeResourceProviderFactory` is always installed.

**Comment by klausbetz** [comment]
In the meantime you can use the latest version of Apple-Identity-Provider, which addresses this issue as suggested by @cbaker-s1 
https://github.com/klausbetz/apple-identity-provider-keycloak/releases/latest
