### ISSUE TITLE
CORS issue with keycloak.js adapter for confidential client

### ISSUE THREAD

**Issue by GretUp** [keycloak/keycloak#13286]
### Describe the bug

I am getting for the confidential client where we need the authorization part:
Access to XMLHttpRequest at '[https://keycloakx.example.com/realms/xxxx/protocol/openid-connect/token'](https://keycloakx.example.com/realms/xxxx/protocol/openid-connect/token%27) from origin 'http://localhost:4200/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
We are using:
"@angular/core": "^12.2.0"
"keycloak-angular": "^8.4.0",
"keycloak-js": "^15.1.1"

### Version

18.0.2

### Expected behavior

No cors issue when requesting a token from the token endpoint.

### Actual behavior

Blocked by CORS policy

### How to Reproduce?

Integrate keycloak.js adapter to angular SPA and request token from confidential client. 

### Anything else?

When we switch to public client it works but then we loose the authorization part which is actually not an option.
For security reasons confidential client should not be allowed for a SPA since there is no secure way to store the secret in a SPA. The solution could be to add an option to "enable" the authorization tab for public clients.

**Comment by phllpmcphrsn** [comment]
Similar issue being seen for me as well. I'm using Isito, oauth2-proxy, and Keycloak with confidential client for oauth2-proxy. The Web Origins are setup; however, CORS does not seem to work. I saw somewhere that enabling PKCE should fix that, but it doesn't, sadly. Istio is performing a TLS pass-through to Keycloak at the gateway level so I can't setup CORS Policy via Virtual Service

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by jonkoops** [comment]
Confidential clients are not allowed for authenticating over the browser for security reasons. You'll have to create a public client if you want to use it with Keycloak JS.
