### ISSUE TITLE
Interchanged property values in warnings in console output

### ISSUE THREAD

**Issue by jflipp** [keycloak/keycloak#13294]
### Describe the bug

I work on Windows.
I download Keycloak 18.0.2 and unpack the archive into d:\keycloak.
So my keycloak base folder is d:\keycloak\keycloak-18.0.2.

I run d:\keycloak\keycloak-18.0.2\bin\kc.bat start --hostname localhost --http-enabled true
and Keycloak starts.
So far so good.

I stop Keycloak and run d:\keycloak\keycloak-18.0.2\bin\kc.bat start --hostname localhost --http-enabled true --https-client-auth **request**
Again, Keycloak starts, but the console output contains this warning:

2022-07-23 22:04:43,838 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.http.ssl.client-auth is set to '**none**' but it is build time fixed to '**request**'. Did you change the property quarkus.http.ssl.client-auth after building the application?

You see, the property values are interchanged.
The text **should be**:
 - quarkus.http.ssl.client-auth is set to '**request**' but it is build time fixed to '**none**'. Did you change the property quarkus.http.ssl.client-auth after building the application?

I stop Keycloak and run d:\keycloak\keycloak-18.0.2\bin\kc.bat start --hostname localhost --http-enabled true --https-client-auth **required**
Again, Keycloak starts, but the console output contains this warning:

2022-07-23 22:06:03,153 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.http.ssl.client-auth is set to '**none**' but it is build time fixed to '**required**'. Did you change the property quarkus.http.ssl.client-auth after building the application?

Again, the property values are interchanged.
The text **should be**:
 - quarkus.http.ssl.client-auth is set to '**required**' but it is build time fixed to '**none**'. Did you change the property quarkus.http.ssl.client-auth after building the application?

I stop Keycloak and create a configuration file d:\conf001.conf which contains the following two lines.
health-enabled=**true**
metrics-enabled=**true**

I run d:\keycloak\keycloak-18.0.2\bin\kc.bat --config-file d:\conf001.conf start --hostname localhost --http-enabled true
Again, Keycloak starts, but the console output contains this warning:

2022-07-23 22:17:53,913 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.datasource.health.enabled is set to '**false**' but it is build time fixed to '**true**'. Did you change the property quarkus.datasource.health.enabled after building the application?
 - quarkus.datasource.metrics.enabled is set to '**false**' but it is build time fixed to '**true**'. Did you change the property quarkus.datasource.metrics.enabled after building the application?

Again, the property values are interchanged.
The text **should be**:
 - quarkus.datasource.health.enabled is set to '**true**' but it is build time fixed to '**false**'. Did you change the property quarkus.datasource.health.enabled after building the application?
 - quarkus.datasource.metrics.enabled is set to '**true**' but it is build time fixed to '**false**'. Did you change the property quarkus.datasource.metrics.enabled after building the application?

It seems to me that in the text
 - SOME_PROPERTY is set to '**THIS_VALUE**' but it is build time fixed to '**THAT_VALUE**'
**THIS_VALUE** and **THAT_VALUE** are always interchanged.

Frankly, I find this rather confusing.
Can you please look into that?
Thank you.

### Version

18.0.2

**Comment by DGuhr** [comment]
@jflipp thanks for noticing. There are multiple threads on quarkus issues around this, last I could find is https://github.com/quarkusio/quarkus/issues/26156 - but there are older ones also. The warning is shown directly from quarkus itself, thus we can't do much about it atm.
@pedroigor we might want to wrap it, as the warning msg references underlying quarkus properties instead of our config layer. I'll add help wanted label for now.

**Comment by pedroigor** [comment]
The improvement makes a lot of sense. It is related to how the underlying stack works and we can not invest time in investigating what it takes to remove those messages from the console.

We appreciate any contribution in this area while we don't have time to work on it.

**Comment by shawkins** [comment]
Closing as out of date. The upstream issue has been addressed.
