### ISSUE TITLE
Refactor Quarkus HotRod test to not use DatabaseContainer

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13329]
### Description

Currently, Quarkus HotRod test use `DatabaseContainer` and `@WithDatabase` annotation for spinning up the Infinispan server. This should be refactored to either use something like `@WithContainer` or `@WithInfinispan`.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
