### ISSUE TITLE
404 when accessing http://localhost:8080/realms/realm_name/protocol/openid-connect/3p-cookies/step1.html

### ISSUE THREAD

**Issue by jcarlosmm** [keycloak/keycloak#13336]
### Describe the bug

I'm adding Keycloak login to an Angular app, but always get 404 Not Found error because Keycloak JavaScript adapter tryes to connect to http://localhost:8080/realms/realm_name/protocol/openid-connect/3p-cookies/step1.html

According to Google this error looks related to Keycloak server and keycloak-js library different versions, but I'm using same exact version (18.0.1) for both.

**keycloakClient** is created in Keycloak with public access type, http://localhost:4200/* as Valid Redirect URIs and with * in Web Origins. Rest of parameters are in default values.

Basically, I'm using the JavaScript adapter code located at https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

```
<!doctype html>
<html lang="es">
<head>
  <script src="http://localhost:8080/auth/js/keycloak.js"></script>
  <script>
    function initKeycloak() {
      const keycloak = new Keycloak({
        url: 'http://localhost:8080',
        realm: 'realm_name',
        clientId: 'keycloakClient'
      });
      keycloak.init().then(function(authenticated) {
        alert(authenticated ? 'authenticated' : 'not authenticated');
      }).catch(function() {
        alert('failed to initialize');
      });
    }
  </script>
  <meta charset="utf-8">
  <title>KeycloakJavascript</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body onload="initKeycloak()">
  <app-root></app-root>
</body>
</html>
```

### Version

18.0.1

### Expected behavior

Show Keycloak user login window for entering credentials

### Actual behavior

Get an 404 because Keycloak JavaScript adapter tryes to connect to http://localhost:8080/realms/realm_name/protocol/openid-connect/3p-cookies/step1.html

### How to Reproduce?

Run the inserted code previously configuring Keycloak client as described

**Comment by lexcao** [comment]
Hi, @jcarlosmm 
From the URL you provided
`http://localhost:8080/realms/realm_name/protocol/openid-connect/3p-cookies/step1.html`
I found the base URL of your Keycloak is set to `/`, while the URL to Keycloak JS is
`http://localhost:8080/auth/js/keycloak.js`

There may be related to the base URL of Keycloak, I think.

### Attempt A
Could you try this, to change the URL of Keycloak JS?
`http://localhost:8080/js/keycloak.js`

### Attempt B
Or, could you try this, visit the HTML directly.
[http://localhost:8080/auth/realms/realm_name/protocol/openid-connect/3p-cookies/step1.html](http://localhost:8080/auth/realms/realm_name/protocol/openid-connect/3p-cookies/step1.html)

If `Attempt B` works(no 404), change your code of initializing Keycloak.
```
const keycloak = new Keycloak({
        url: 'http://localhost:8080/auth', // add /auth for base URL
})
```

**Comment by jcarlosmm** [comment]
Thanks @lexcao for your quick answer

Attempt A produces an 404 error, but Attempt B works!!
