### ISSUE TITLE
Enable Bloom filter on HotRod near-cache

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13332]
#13303 Enabled near-cache with bloom filter set to false due to some errors when bloom filter was enabled. We need to investigate why it fails and enable it once the failures are resolved.

**Comment by mhajas** [comment]
The issue when the bloom filter is enabled is reported here: https://issues.redhat.com/browse/ISPN-14039.

As a workaround to enable bloom filter without the ISPN-14039 resolved it should be possible to: 
> create a JAR file with your objects stored in the cache and put it in server/lib

**Comment by hmlnarik** [comment]
Putting to Backlog to understand the performance impact of including / not-including it

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
