### ISSUE TITLE
Wrong Documentation 

### ISSUE THREAD

**Issue by gmmkmtgk** [keycloak/keycloak#13330]
### Describe the bug

https://www.keycloak.org/docs/latest/server_installation/#_setting_up_ssl

here in the documentation of setting up ssl 
The way written is of version 16.0.0
In which there is standalone which is deprecated now in the latest version 18.0 
<img width="947" alt="image" src="https://user-images.githubusercontent.com/51493190/181003144-bac42d3f-de82-4ce0-9c9c-9f072a7c7009.png">

### Version

18.0.2

**Comment by darius-m** [comment]
Was the standalone configuration deprecated in version 18? The documentation that you mention is for the legacy (Wildfly) Keycloak server, not the default (Quarkus), so it should still be correct. If you go to the [documentation](https://www.keycloak.org/documentation) section, they have replaced the long single-page documents with short guides for Quarkus.

**Comment by DGuhr** [comment]
What @darius-m states is right, thanks. you can find the new guides under https://www.keycloak.org/guides#server and the tls guide here: https://www.keycloak.org/server/enabletls
