### ISSUE TITLE
Cannot save profile on User Management Console while CJK characters in username

### ISSUE THREAD

**Issue by hyperzlib** [keycloak/keycloak#13346]
### Describe the bug

in org.keycloak.services.validation.Validation, I found that allows only Latin characters for username, which causes users with CJK characters in their username to be unable to update their profile on User Management Console.
In order to solve this problem, I hope to add a configuration that allows turn off username-not-idn-homograph, or change the regular expression of username Validation to support CJK characters, or skip the username validation if user is not allowed to change the username.

### Version

18.0.2

### Expected behavior

Supports CJK characters in username.

### Actual behavior

Got **invalidUsernameMessage** error while saving user profile.

### How to Reproduce?

Create a user with CJK characters in username. e.g.: 你好世界
Enter User Management Console and click **Save** button.

**Comment by pedroigor** [comment]
@hyperzlib Thanks. Created https://github.com/keycloak/keycloak/pull/16618.

**Comment by hyperzlib** [comment]
@pedroigor Thanks
