### ISSUE TITLE
Minor inaccuracy in description of config file behavior

### ISSUE THREAD

**Issue by sgrimm** [keycloak/keycloak#13344]
### Describe the bug

https://www.keycloak.org/server/configuration#_configuring_the_server_by_using_configuration_files says:

> Changes to any **build option** defined in the `keycloak.conf` file that is targeted for the `build` command are ignored if the value differs from the value for the last `build` command. In this case, make sure you run the `build` command again so that any build option is updated accordingly.

This seems circular: it is telling you that you can only change the options on a `build` command after you've already run `build` with the new options.

I believe the first sentence should say, "...targeted for the `start` command."

### Version

18.0.2

**Comment by DGuhr** [comment]
Hi @sgrimm and thanks for your contribution. There is an overhauled version of the configuration guide in the merged pr here: https://github.com/keycloak/keycloak/pull/13137 that also takes into account the latest changes to the server startup with the optimized flag (basically, "autobuild by default"). I will close this one and the accompanying pr, as the whole guide changed for v19 (see around line 200 in the overhauled guide pr).
