### ISSUE TITLE
Unable to configure URL scheme for admin console

### ISSUE THREAD

**Issue by robbertbrak** [keycloak/keycloak#13364]
### Describe the bug

I'm trying to setup Keycloak 18.0.2 in a reverse proxy environment where the HTTPS connection is terminated at the proxy. The admin console is also exposed via the proxy. However, after logging in to the admin console, some requests are blocked with a "Mixed content" error from the browser.

The reason for this appears to be that the scheme of the `authUrl` JavaScript variable is set to `http`:

```
var authServerUrl = 'https://MY-URL/auth';
var authUrl = 'http://MY-URL/auth'; // <-- INCORRECT URL SCHEME
...
```

I could not find a way to configure this. Looking through the code, this line seems suspect: https://github.com/keycloak/keycloak/blob/8470a30446cf1a8280353fb96f8e2152d5d186ac/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L67

A recent commit has added the possibility to configure the admin hostname (commit b34f4615, added in https://github.com/keycloak/keycloak/pull/12192). Would it be possible to add a similar configuration option for the admin scheme?

### Version

18.0.2

**Comment by lexcao** [comment]
Hi, have you checked this?
* https://github.com/keycloak/keycloak-admin-ui/pull/2704
* #11667

**Comment by robbertbrak** [comment]
@lexcao: Thank you for giving these references. It looks like my issue might be the same as #11667 (in particular https://github.com/keycloak/keycloak/issues/11667#issuecomment-1109999172). I can see that it was closed, but that - as multiple people have pointed out by now - the issue hasn't been solved yet.

I already came across the potential solution described in https://github.com/keycloak/keycloak/issues/11667#issuecomment-1197575278 (passing on the X-Forward-Proto header from the reverse proxy). Unfortunately I'm in an environment where I do not have control over the proxy, so I'm looking for a way to configure this in Keycloak itself.

**Comment by robbertbrak** [comment]
I should mention that I initially linked to the wrong "suspect" line in DefaultHostnameProvider (line 81 instead of line 67). What I meant to say was: I would expect the method for getting the ADMIN url scheme to be more similar to the method for getting the ADMIN hostname. 

In other words:

https://github.com/keycloak/keycloak/blob/8470a30446cf1a8280353fb96f8e2152d5d186ac/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L67

should be more like

https://github.com/keycloak/keycloak/blob/8470a30446cf1a8280353fb96f8e2152d5d186ac/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L82

**Comment by pedroigor** [comment]
@robbertbrak The problem is that admin URLs are basically built based on the information from the request except for the host when the `hostname-admin` is set.

In your case, the only possible approach is to set the `X-Forwarded-Proto` header to force `https`.

However, I should be working on a fix to this area where it will be possible to set a URL when setting `hostname` and `hostname-admin` options. That should solve lot of problems people are facing with this and keep the same behavior from the legacy distribution.

**Comment by pedroigor** [comment]
Created https://github.com/keycloak/keycloak/issues/13524.

**Comment by pedroigor** [comment]
@robbertbrak Could you check https://github.com/keycloak/keycloak/pull/13681?

**Comment by robbertbrak** [comment]
@pedroigor That looks fantastic, can't wait till this gets merged... Thanks for picking this up so quickly!
