### ISSUE TITLE
Prevent Users from editing their personal Data entirely

### ISSUE THREAD

**Issue by LordRazor** [keycloak/keycloak#13378]
### Description

Add an Option in the Admin Console which, if enabled, prevents Users from changing their own Firstname and Lastname and / or their Email in the Account Management Console

### Motivation

Currently it is impossible to prevent Users from changing their Firstname and Lastname or their Email in the Account Management Console while maintaining the Functionality of the Console.
However, some Applications might rely on the Integrity of this currently editable Data. This is why there should be an Option to prevent Users from changing it by themselves.

### Details

There is already an Option to prevent Users from changing their Username (Realm Settings -> Login -> Edit Username). In this spot, more Switches could be added which copy the Behaviour of the "Edit Username" Switch but they grey out the "First Name" and "Last Name" or "Email" Fields in the Account Management Console instead of the "Username" Field.

**Comment by lexcao** [comment]
Hi, have you tried to remove `account.manage-profile` role from the user?

It may be the default role of a realm.

And, if you want the profile read-only, you need to assign the `account.view-profile` role.

**Comment by LordRazor** [comment]
Thank you for your Advice. I already tried this approach, but sadly, removing `account.manage-account` completely breaks the functionality of the Account Management Console (a 403 is thrown at every page of the Console, including the Account Security Page which should be available for changing Passwords and 2FA).

`account.view-profile` is pre-assigned and does not change that Behaviour.

**Comment by sschu** [comment]
@LordRazor Have you checked the user profile? It is now able to configure read/writability of firstname and last name (see https://github.com/keycloak/keycloak/issues/12109). Only thing missing is username and email (https://github.com/keycloak/keycloak/pull/12620).

**Comment by LordRazor** [comment]
@sschu Thank you very much, this did it for the Firstname and Lastname and is providing the functionality i asked for, even though its providing it in a rather complicated manner. However, it works. Appreciate it.

**Comment by 0xpr03** [comment]
> Firstname and Lastname

Note that you can't disable editing them via the UI, only in the JSON editor.
