### ISSUE TITLE
Enable to specify which message levels will be logged by the GELF logger 

### ISSUE THREAD

**Issue by gunterze** [keycloak/keycloak#13397]
### Description

Enable to specify which message levels will be logged by the GELF logger by

CLI Option | Env | Description | Default
-- | -- | -- | --
`--log-gelf-level` | `KC_LOG_GELF_LEVEL` |  The log level specifying which message levels will be logged by the GELF logger. Message levels lower than this value will be discarded.  | info

Enhancement of #12125

### Motivation

Typically, centralized (long-term) logs are not as verbose as local (short-term) (file) logs.

### Details

Workaround:
`quarkus.properties:`
```
quarkus.log.handler.gelf.level=${KC_LOG_GELF_LEVEL:INFO}
```

**Comment by DGuhr** [comment]
see #13422 👍
