### ISSUE TITLE
Add rememberMe to a user session representation

### ISSUE THREAD

**Issue by hokuda** [keycloak/keycloak#13408]
### Description

Please add rememberMe to a user session representation which is fetched by the rest API `GET /{realm}/clients/{id}/user-sessions`

### Anything else

This is related to support ticket 291

**Comment by lexcao** [comment]
I think it is a straightforward feature I am willing to help with.
@mposolda Could you please check it out?

**Comment by mposolda** [comment]
@lexcao If you have an opportunity to help, it will be warm welcome!

**Comment by lexcao** [comment]
@mposolda Thank you!
I fired a PR #13765
