### ISSUE TITLE
Weaknesses in Keycloak cookies

### ISSUE THREAD

**Issue by fedeneira** [keycloak/keycloak#13404]
### Description

**1. Vulnerability: Cookie Does Not Contain The "secure" Attribute**
-Solution: If the associated risk of a compromised account is high, apply the "secure" attribute to cookies and force all sensitive requests to be sent via HTTPS.
-Details: Cookies: KC_RESTART, AUTH_SESSION_ID_LEGACY

**2. Vulnerability: Cookie Does Not Contain The "HTTPOnly" Attribute**
-Solution: If the associated risk of a compromised account is high, apply the "HTTPOnly" attribute to cookies
-Details: Cookies: KEYCLOAK_3P_COOKIE_SAMESITE, KEYCLOAK_3P_COOKIE

**3. Vulnerability: Session Cookie (Authentication Related) Does Not Contain The "secure" Attribute**
-Solution: If the associated risk of a compromised account is high, apply the "secure" attribute to session cookies and force all sensitive requests to be sent via HTTPS
-Details: Cookies: KEYCLOAK_IDENTITY_LEGACY, KEYCLOAK_SESSION_LEGACY, AUTH_SESSION_ID_LEGACY

**Comment by mhajas** [comment]
Thank you for the report @fedeneira. The `secure` flag should be set based on [SSL realm settings](https://www.keycloak.org/docs/latest/server_admin/index.html#_ssl_modes). If you set the setting to `ALL` all cookies should be secure, if external it depends on from where you access Keycloak. Please let us know if this doesn't work.

Regarding 3p cookies, as you can see in [this discussion](https://github.com/keycloak/keycloak/discussions/10540) these cookies don't hold any sensitive data therefore there is no high risk of compromising any account.

**Comment by fedeneira** [comment]
Thanks for the quick response. We will checl your recommendation on the secure flag based on [SSL realm settings](https://www.keycloak.org/docs/latest/server_admin/index.html#_ssl_modes) in case we have not set it to ALL.

**Comment by fedeneira** [comment]
It has been verified that your recommendation on on the secure flag based on SSL realm settings solves this issue. Thanks for the help.
