### ISSUE TITLE
Group seach does not display matching groups hierarchy anymore in the UI

### ISSUE THREAD

**Issue by xelita** [keycloak/keycloak#13415]
### Describe the bug

I have the following groups in my UI
<pre>
parent1
      |----------> subgroup1
                           |----------> child1
                           |----------> child2
      |----------> subgroup2
                           |----------> child1
                           |----------> child2
</pre>
...

Initially (in version 15.0.2) when I was searching for "subgroup1" the following result was displayed in the UI.
As you can see the entire group hierarchy is displayed:
<pre>
parent1
      |----------> subgroup1
                           |----------> child1
                           |----------> child2
</pre>

Now the result is:
<pre>
parent1
      |----------> subgroup1
</pre>

Children (subgroups of subgroups) do not appear anymore. It is problematic for me because in my case I am assigning permission to my users in this way.

### Version

18.0.2

### Expected behavior

Expected result should be:
<pre>
parent1
      |----------> subgroup1
                           |----------> child1
                           |----------> child2
</pre>

So that I can assign child1 / child2 group to my users

### How to Reproduce?

1. Create the following structure in keycloak groups:
<pre>
parent1
      |----------> subgroup1
                           |----------> child1
                           |----------> child2
      |----------> subgroup2
                           |----------> child1
                           |----------> child2
</pre>

2. Create a test user.

3. Edit the user and in "groups" tab / "available groups" widget, seach for subgroup1

The following result should be displayed and you are not able to add "child1" subgroup to your user.
<pre>
parent1
      |----------> subgroup1
</pre>

**Comment by xelita** [comment]
probably related to the following ticket - https://github.com/keycloak/keycloak/issues/9435

**Comment by rmartinc** [comment]
Yeah @xelita, the new behavior was done intentionally in https://github.com/keycloak/keycloak/pull/8134. With the new console this conversation is out of date. I have filed a new UI issue as I'm not totally happy with the group assignment in the new console: https://github.com/keycloak/keycloak-ui/issues/4526.

Closing this one and moving to the conversation to the new console behavior. You can comment on that issue.
