### ISSUE TITLE
New Admin Console: How to create a new Client with access type "bearer-only" ?

### ISSUE THREAD

**Issue by Yallan** [keycloak/keycloak#13448]
### Describe the bug

On the new admin console, there is no option to choose : Access type  = "bearer-only"
How create a client with this configuration ?

### Version

19.0.0

**Comment by ssilvert** [comment]
Hi @Yallan.

I know it's a little weird, but we have removed bearer-only clients from the new admin console.  If you have a bearer-only client created with the old admin console, it will still show up in the new console, but you will not be able to change its access type.

To create the equivalent of a bearer-only client in the new admin console, just uncheck all the Authentication flows.

You can learn more about the rationale for this here:
https://groups.google.com/g/keycloak-dev/c/dvgDVYn1P2E/m/VjkFF2DUAQAJ?pli=1

**Comment by mohamed-iyed** [comment]
> Hi @Yallan.
> 
> I know it's a little weird, but we have removed bearer-only clients from the new admin console. If you have a bearer-only client created with the old admin console, it will still show up in the new console, but you will not be able to change its access type.
> 
> To create the equivalent of a bearer-only client in the new admin console, just uncheck all the Authentication flows.
> 
> You can learn more about the rationale for this here: https://groups.google.com/g/keycloak-dev/c/dvgDVYn1P2E/m/VjkFF2DUAQAJ?pli=1

i make what you told me, but i keep get this response :
![Screen Shot 2022-08-19 at 10 50 33 AM](https://user-images.githubusercontent.com/74566099/185593338-da8adfa5-738c-4bba-bf32-ada61824ee53.png)

also if i try to access my api using bearer authorization, i always get access denied reponse : 

![Screen Shot 2022-08-19 at 10 51 38 AM](https://user-images.githubusercontent.com/74566099/185593511-78f5c062-8f13-4179-95fc-dec5a13bcb69.png)

I'm using keycloak.protect() middleware in my api endpoint
