### ISSUE TITLE
Failing compile keycloak development on first run

### ISSUE THREAD

**Issue by KenZync** [keycloak/keycloak#13446]
### Describe the bug

running `mvn -f testsuite/utils/pom.xml exec:java -Pkeycloak-server `

[ERROR] Failed to execute goal on project keycloak-testsuite-utils: Could not resolve dependencies for project org.keycloak:keycloak-testsuite-utils:jar:999-SNAPSHOT: The following artifacts could not be resolved: org.keycloak:keycloak-admin-client:jar:999-SNAPSHOT, org.keycloak:keycloak-wildfly-adduser:jar:999-SNAPSHOT, org.keycloak:keycloak-undertow-adapter:jar:999-SNAPSHOT, org.keycloak:keycloak-saml-adapter-api-public:jar:999-SNAPSHOT, org.keycloak:keycloak-saml-adapter-core:jar:999-SNAPSHOT, org.keycloak:keycloak-authz-client:jar:999-SNAPSHOT, org.keycloak:keycloak-saml-servlet-filter-adapter:jar:999-SNAPSHOT, org.keycloak:keycloak-servlet-filter-adapter:jar:999-SNAPSHOT, org.keycloak:keycloak-saml-undertow-adapter:jar:999-SNAPSHOT, org.keycloak:keycloak-jaxrs-oauth-client:jar:999-SNAPSHOT, org.keycloak.testsuite:integration-arquillian-testsuite-providers:jar:999-SNAPSHOT, org.keycloak:keycloak-util-embedded-ldap:jar:999-SNAPSHOT: Could not find artifact org.keycloak:keycloak-admin-client:jar:999-SNAPSHOT

### Version

lastest probably 19.0.1?

### Expected behavior

Clone and run dev successfully

### Actual behavior

error while run dev

### How to Reproduce?

1. download java maven and git
2. clone this project
3. make new file  settings.xml in .m2 folder and put mirror code in it
4. run command mvn -f testsuite/utils/pom.xml exec:java -Pkeycloak-server 

### Anything else?

actually when maven install dependencies there's an error when testing this one 

[INFO] Keycloak Quarkus Server Extension .................. FAILURE [  3.639 s]

**Comment by pedroigor** [comment]
@KenZync Could you please look at this guide https://github.com/keycloak/keycloak/blob/main/quarkus/CONTRIBUTING.md ?

There you should find the details about how to run the server from sources.
