### ISSUE TITLE
Admin console does not work behind traefik proxy

### ISSUE THREAD

**Issue by BonaBeavis** [keycloak/keycloak#13467]
### Describe the bug

When Keycloak is behind a Traefik proxy, the Admin console does not open and only a spinner is shown. It looks like Keycloak does not set session cookies.

### Version

19.0.0

### Expected behavior

Admin console should open. I did the request one time without proxy:
```bash
./opt/keycloak/bin/kc.sh start-dev --hostname localhost --proxy edge --hostname-port 8000 --hostname-strict-https false --hostname-strict false
```
And with a proxy in an otherwise identical setup:
```
./opt/keycloak/bin/kc.sh start-dev --hostname keycloak.localhost --proxy edge --hostname-port 80 --hostname-strict-https false --hostname-strict false
```

I logged the network traffic and did a screenshot where those setups diverge. One the left side, no proxy was used:
![image](https://user-images.githubusercontent.com/3330855/182211802-6b1695ec-cce0-48da-8f25-9974c95b0db1.png)

### Actual behavior

It only shows a spinner. And the request from step1.html does not set a cookie.

### How to Reproduce?

More information about the environment is here: https://github.com/keycloak/keycloak/discussions/13459

### Anything else?

I am not sure if this is a Keycloak or Traefik issue, I start here because I have three other services up and running behind the same reverse proxy, so it is probable the issue lays with Keycloak, also I tried everything...

The issue could also be, that Traefik does not set the x-forwarded-for header correctly, currently it is set to the IP of Trafik's container.

**Comment by BonaBeavis** [comment]
This seems to be a regression, I get to the login page with 18.0.2, bit the I run into https://github.com/keycloak/keycloak/issues/11926#issuecomment-1122530494

**Comment by BonaBeavis** [comment]
Seems to be an issue with the port:
This does not work:
```
http://keycloak.localhost/realms/master/account/?referrer=security-admin-console&referrer_uri=http%3A%2F%2Fkeycloak.localhost%2Fadmin%2Fmaster%2Fconsole%2F%23%2F
```
But this works:
```
http://keycloak.localhost:80/realms/master/account/?referrer=security-admin-console&referrer_uri=http%3A%2F%2Fkeycloak.localhost%2Fadmin%2Fmaster%2Fconsole%2F%23%2F
```

**Comment by BonaBeavis** [comment]
In the source for the admin console `view-source:http://keycloak.localhost/admin/master/console/#/` I found the following snippet: 

```html
    <script type="text/javascript">
        var authServerUrl = 'http://keycloak.localhost:80';
        var authUrl = 'http://keycloak.localhost';
        var consoleBaseUrl = '/admin/master/console/';
        var resourceUrl = '/resources/nyv0e/admin/keycloak';
        var masterRealm = 'master';
        var resourceVersion = 'nyv0e';
    </script>
```

Looks like the `authServerUrl` is built differently from the `authUrl`

**Comment by onlookor** [comment]
I observed [the same behavior](https://github.com/keycloak/keycloak/issues/13454) of the admin console endpoint without a reverse proxy.
My problem seems to be caused by netty, because after a while it reports an uncaught exception from netty: SSLEngine closed already.

**Comment by BonaBeavis** [comment]
@onlooker I do not get this exception, because I have proxy mide edge anabled which disbles ssl.

**Comment by BonaBeavis** [comment]
Underlying issue was actually https://github.com/keycloak/keycloak/issues/13519
