### ISSUE TITLE
Automatically remove roles in Keycloak based on SAML attributes(with  Azure AD integration)

### ISSUE THREAD

**Issue by sumanraovakt** [keycloak/keycloak#13461]
### Describe the bug

I have a SAML IdP set up in Keycloak and it is working fine. We get an attribute from SAML called “Groups” which is a list of group IDs. So I set up some mappers of type “Advanced Attribute to Role”. I mapped GroupA to RoleA, GroupB to RoleB, etc. This works fine at first. If a user’s "Groups" attribute contains "GroupA", then that user is correctly assigned RoleA.

The problem is when a user is re-assigned from GroupA to GroupB. Now when that user logs on, he is correctly assigned RoleB, but he retains RoleA from before. If a user simply loses GroupA, that user retains RoleA.

I want a user to have those roles and ONLY those roles that are mapped in based on his current Groups attribute. And if a user loses a group attribute value, then he should lose the corresponding role.

I set the sync mode to force so that we overwrite all mapped attributes and roles, in the Settings of your IDP . But still facing the same issue 

How can I fix this situation? Can this be done using SAML attribute mappers? What’s the proper way to do this?

### Version

15.1.1

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by autoluminescent** [comment]
I have the same issue but with an OIDC IdP, and mapping app roles (not groups) to realm roles. I understand there is no capacity to pick this up, but could I get some tips on what would be a reasonable approach? It feels like a potentially big vulnerability, and I'm sure others have fixed it. Thanks!
