### ISSUE TITLE
19.0.1 is just a beta version 

### ISSUE THREAD

**Issue by marchalb** [keycloak/keycloak#13499]
### Describe the bug

I am very new to Keycloak and the first impression in matter of quality of release is not great. 

There are many changes apparently with 19.0.1 which break the many tutorial I found on the web. I do not expect Keycloak to update those but at least its own quick starts. 

Just as two examples:   
- one can't even follow the docker getting started: https://www.keycloak.org/getting-started/getting-started-docker (the creation of client is now very different)
- the VueJS getting started is also failing: https://www.keycloak.org/securing-apps/vue    .. can't change the access type,  import/export client fails,  getting error after successful authentication CODE_TO_TOKEN_ERROR

Can you please call 19.0.1  a beta version so that beginner like me do not lose time with it. Which version I should use to match the documentation? (and most examples on the web) 
Many thanks 
B.

### Version

19.0.1

### Expected behavior

Documentation in line with software 

### Actual behavior

many broken differences 

### How to Reproduce?

Just try to follow the Getting Started Guide 

### Anything else?

Nevertheless many thanks for the impressive works .. we need an open source SSO for our NGO project and can't afford expensive alternative

**Comment by darius-m** [comment]
Not sure on the specifics of the issues you face, but the guide seems to still use the original admin interface, while Keycloak 19.0.0 switched to the new Admin2 interface as the default. You can try to disable it by setting the disabled features variable - the change was mentioned in the [Upgrade guide](https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-19-0-0); you can set flags in the config file or through environment variables (see the [All configuration](https://www.keycloak.org/server/all-config) page) - you should be able to set `KC_FEATURES_DISABLED=admin2` if you want to follow the guides that rely on the original interface.

**Comment by pedroigor** [comment]
@darius-m Thanks for the valuable input.

@marchalb First of all, you have a point here and we did not update some docs to keep them aligned with the administration console. In this release (in fact since 18) we have been working and delivering a completely new experience. I understand your frustration and we appreciate the feedback that helps us to keep improving.

@ssilvert Can you please look at it?

**Comment by ssilvert** [comment]
You can also switch to the old admin console from the Realm settings --> Themes tab.  Just change the admin console theme to "keycloak" and refresh your browser.  Then you won't need to pass the KC_FEATURES_DISABLED flag any more.

The main documentation is updated but the quickstarts are not.  @andymunro should know more about when that will be updated.

**Comment by andymunro** [comment]
@ssilvert The Quick Start guides use a new format involving Freemarker that has not been used by CCS, so we don't have ability to update these guides.  I believe Stian created the previous versions.  Unless someone else knows how to update them, it may have to wait till Stian is back on August 15.

**Comment by pedroigor** [comment]
@andymunro The images are here https://github.com/keycloak/keycloak-web/tree/c0af0b09216cac55d432476ad212360c13a842f4/guides/images and the guide is here https://github.com/keycloak/keycloak-web/blob/ea829c94a89976b5fc840f92b41f66ec9f803c81/guides/securing-apps/vue.adoc.

I will send a PR fixing this.

**Comment by andymunro** [comment]
Okay, thanks, @pedroigor.  I am happy to review the PR.

**Comment by marchalb** [comment]
Thanks a lot guys, the reaction is very much appreciated.

**Comment by onlookor** [comment]
> @darius-m Thanks for the valuable input.
> 
> @marchalb First of all, you have a point here and we did not update some docs to keep them aligned with the administration console. In this release (in fact since 18) we have been working and delivering a completely new experience. I understand your frustration and we appreciate the feedback that helps us to keep improving.
> 
> @ssilvert Can you please look at it?

Excuse me, could you contact some guy to have a look at [my issue](https://github.com/keycloak/keycloak/issues/13454)? It's an uncaught exception from netty, I have issued it for 3 days, nobody concerns it! It's a bug, not a requirement!

**Comment by marchalb** [comment]
Dear Guys, Has it been really fixed?  

I look at https://www.keycloak.org/securing-apps/vue.   It still show the screenshot with the possibility to change the Access Type to Public (Something I apparently need to avoid a CORS issue) while I can't get such possibility when I try with the version 19.  Changing the Theme as suggested by Ssilvert does not make any change.. 

Also disabling the admin2 feature does not seem to change anything (no possibility to change Access Type of the Client)  even though the disabling has been taken into effect: 
ben@benoits-macbook-pro keycloak-19.0.1 % bin/kc.sh show-config                     
Changes detected in configuration. Updating the server image.
Current Mode: production
Current Configuration:
	kc.cache =  ispn (PersistedConfigSource)
	kc.config.build-and-exit =  true (SysPropConfigSource)
	kc.db =  dev-file (PersistedConfigSource)
	kc.features-disabled =  admin2 (PersistedConfigSource)
