### ISSUE TITLE
Could not save the execution config: unknown_error

### ISSUE THREAD

**Issue by KCBoys** [keycloak/keycloak#13503]
### Describe the bug

Attempting to save a X509/Validate Username Form config

cause in a "Could not save the execution config: unknown_error"

Server log:
 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-219) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 44] (through reference chain: org.keycloak.representations.idm.AuthenticatorConfigRepresentation["config"]->java.util.LinkedHashMap["x509-cert-auth"])

This issue happens only using the new admin panel
Changing it from the theme options to the old admin panel will give no issue

### Version

19.0.1

**Comment by lexcao** [comment]
Hi, @KCBoys 
It is a duplicated issue and is moved to `keycloak-admin-ui` repo.
Please check this out.
https://github.com/keycloak/keycloak-admin-ui/issues/3022
