### ISSUE TITLE
User Storage Provider settings not visible in new Admin UI

### ISSUE THREAD

**Issue by SebastianLng** [keycloak/keycloak#13535]
### Describe the bug

I am currently trying to migrate my User Storage SPI implementation to keycloak 19. I have a small test project where I tried to port the storage provider according to the migration guides first. This means, as I understand it, using the legacy packages and using the LegacyUserCredentialManager for the user class.  The keycloak 19 storage provider seems to work in in principal, but the configuration properties are not shown in the new admin UI.

### Version

19.0.1

### Expected behavior

The new admin UI in keycloak 19 shows the custom provider properties in the UI.

### Actual behavior

Keycloak 18 shows the properties:
![kc-18-settings](https://user-images.githubusercontent.com/25402641/182810391-a6d9affd-bedc-4832-97e5-e450a51f8f73.png)

Keycloak 19 doesn't show any custom properties:
![kc-19-settings](https://user-images.githubusercontent.com/25402641/182810401-11cc96da-1272-4301-8958-71e7974b1744.png)

### How to Reproduce?

1. Create a user storage SPI with legacy storage and provider config properties.
2. Run Keycloak 19 in dev mode with the custom storage provider

Here're my small keycloak 18 and 19 test projects to reproduce the issue:
[test-storage-provider.zip](https://github.com/keycloak/keycloak/files/9258240/test-storage-provider.zip)

**Comment by lexcao** [comment]
Hi, @SebastianLng 
Seems the issue is related to new admin UI.
Could you please move this issue to https://github.com/keycloak/keycloak-admin-ui repo?

BTW, you can use the legacy admin UI by changing the theme from realm settings.

**Comment by SebastianLng** [comment]
Thanks for the reply, my goal is to use the new UI when upgrading to keycloak 19, so I'd like to see this to work without using the legacy UI. I created a new ticket in the admin ui repo: https://github.com/keycloak/keycloak-admin-ui/issues/3059
