### ISSUE TITLE
Quarkus testsuite should use storage=chm by default where it makes sense

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#13544]
### Description

In order to improve startup times (see draft PR here: https://github.com/keycloak/keycloak/pull/13443 ) and not having to add `--storage=chm` for most tests where it should be used, we want the quarkus testsuite to use `--storage=chm` if not otherwise specified.

Also, it should be possible to use the legacy store "on demand", for example with a method-level annotation like `@WithLegacyStore` or a similar solution that uses dev-file instead of the new chm store when set (e.g. for the import / export tests).

**Comment by DGuhr** [comment]
@pedroigor pls review this, not sure what is the best way to dostinguish, annotation or another way. Its just what came firstto my mind

**Comment by pedroigor** [comment]
I wrote some requirements here https://github.com/keycloak/keycloak/pull/13443#issuecomment-1203066579. Please, let me know if they make sense.

Implementation-wise, I think using an annotation is the best approach.

For which tests we should be marking to use the legacy store, I'm still not sure and need to take a closer look.

One thing we also need to consider is how much we are going to lose in terms of coverage by doing this move. The legacy store is still our default/supported database and we can't lose coverage.

**Comment by abstractj** [comment]
@pedroigor @vmuzikar I just wonder if the issue is more appropriate to be handled by the storage team, rather than your team. Does it make any sense?

**Comment by vmuzikar** [comment]
@abstractj I think it makes both sense, whether it's Storage or CND team. On one hand it touches and enhances the Quarkus testsuite which is owned by our team, on the other hand it leverages Storage to do so. Please notice the main aim here is not to test the CHM Storage, but to speed up the testsuite.

In any case, there's a [draft PR](https://github.com/keycloak/keycloak/pull/14713) already.
