### ISSUE TITLE
Occasional 401 Unauthorized when calling admin client RealmResource with correct credentials

### ISSUE THREAD

**Issue by urieli** [keycloak/keycloak#13551]
### Describe the bug

Occasionally, when calling HTTP resources beneath [org.keycloak.admin.client.Keycloak.realm](https://github.com/keycloak/keycloak/blob/15.1.1/integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java#L113), I get a HTTP 401 Unauthorized response, despite the credentials in the configuration file being correct.

Indeed, if I make the identical call again with the same credentials, I get an HTTP 200 OK response.

This seems to be related to the moment when [a refresh token is required](https://github.com/keycloak/keycloak/blob/15.1.1/integration/admin-client/src/main/java/org/keycloak/admin/client/token/TokenManager.java#L72).

My guess is that the request to refresh the token for some reason returns a NotAuthorizedException (401) instead of a BadRequestException (400), and therefore the [catch clause](https://github.com/keycloak/keycloak/blob/15.1.1/integration/admin-client/src/main/java/org/keycloak/admin/client/token/TokenManager.java#L114) is not triggered (this part of the code seems identical in more recent keycloak versions).

I haven't been able to confirm this, as the error occurs sporadically. I'm not sure what situation would result in this.

The server-side log when this occurs is attached:
[KeycloakServerLog401.log](https://github.com/keycloak/keycloak/files/9260654/KeycloakServerLog401.log)

Specifically, the following line always appears when the 401 error is returned:
```
WARN  [org.keycloak.events] (default task-239) type=REFRESH_TOKEN_ERROR, realmId=pipeline2_dev4us, clientId=pipeline2, userId=null, ipAddress=10.20.0.116, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```
Prior to this line, there is a 401 error reported as well:
```
08:07:27,664 DEBUG [org.keycloak.services.managers.AuthenticationManager] (default task-239) User session not active
08:07:27,664 DEBUG [org.keycloak.services.resources.admin.AdminRoot] (default task-239) Token not valid
08:07:27,665 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (default task-239) Error response 401: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.admin.AdminRoot.authenticateRealmAdminRequest(AdminRoot.java:179)
	at org.keycloak.keycloak-services@15.1.1//org.keycloak.services.resources.admin.AdminRoot.getRealmsAdmin(AdminRoot.java:211)
	at jdk.internal.reflect.GeneratedMethodAccessor428.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

### Version

15.1.1

### Expected behavior

Calls to admin client resources with correct credentials should always result in 200 OK if the request is correct.

### Actual behavior

Occasionally, these calls result in 401 Unauthorized.

### How to Reproduce?

Make many calls to the RealmResource over a period of several hours.

**Comment by lexcao** [comment]
Hi, from the log I can see `User session not active`
From my understanding, when the access token is not valid, it would refresh the token using the refresh token.
While refreshing the token, if the SSO session `idle` or `max` is reached, the refreshing should be an error.

Could you please try to check your SSO session lifespan settings from admin settings?

**Comment by urieli** [comment]
Thanks @lexcao - indeed, on this particular realm the `Access Token Lifespan` was set to be longer than the `SSO Session idle` and `SSO Session Max`. Now that I've reduced the `Access Token Lifespan` to be much less than the other two values, the problem seems to have disappeared. I'll close for now, and re-open if the problem re-appears.
