### ISSUE TITLE
Preview Feature "Update Email" clears first and last name upon email confirmation

### ISSUE THREAD

**Issue by ReneZeidler** [keycloak/keycloak#13550]
### Describe the bug

When the new UPDATE_EMAIL feature is enabled, going through the process of changing your email address clears the first and last name fields of your user profile.

### Version

19.0.1

### Expected behavior

Changing the email address should not affect any other profile fields.

### Actual behavior

After clicking the confirmation link in the email, the email address gets successfully updated (as expected), but at the same time the first and last name are cleared.

### How to Reproduce?

* Enable the UPDATE_EMAIL feature (e.g. KC_FEATURES=update-email)
* Create a realm
  * which has the "Update Email" required action enabled
  * which has email verification enabled
* Create a user with an email address, first and last name
* Log in as that user and go to the account console. Observe the email address, first and last name in the profile information.
* Click "Update email" and enter a new (different) email adress
* Click the confirmation link sent to that email adress
* Go to the account console again. The email address has been updated, but the first and last name are gone.

**Comment by lexcao** [comment]
Hi, 
I found these codes for validating the profile.

https://github.com/keycloak/keycloak/blob/ec808d28bb224fc243edd334aa549a8cf8d94ca7/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L142-L151

It does not need to add `first_name` and `last_name` for validating when `UPDATE_EMAIL`, I think.

I will make a fix.
