### ISSUE TITLE
[PLACEHOLDER] Add realms/users/clients CRDs

### ISSUE THREAD

**Issue by AndriiOmelianenko** [keycloak/keycloak#13566]
### Description

hello, what are the plans to support of realms/users/clients crd, as it was in the previous operator, to make it comply more 'configuration as a code' and gitops approaches?

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31300
```

**Comment by sathieu** [comment]
Hello, what is the status of this issue? Is there any ETA?

**Comment by KarstenSiemer** [comment]
Take a look here https://github.com/keycloak/keycloak/issues/11928
I just commented there, realizing too late that the issue was already closed.

Most of your questions are answered or stated in that issue, I guess

**Comment by vmuzikar** [comment]
Thank you for the interest in this feature. A while ago, we published a [blog post](https://www.keycloak.org/2022/09/operator-crs.html) around our plans for the CRs. It's a few months old but still accurate with the exception of expected Keycloak versions for delivering it. Unfortunately, at the moment I'm unable to share a new schedule but it is still high in our priorities. Thanks for your understanding.

**Comment by crumohr** [comment]
> Unfortunately, at the moment I'm unable to share a new schedule but it is still high in our priorities.

@vmuzikar: Do you have an update for us regarding the new schedule?

**Comment by vmuzikar** [comment]
@crumohr Unfortunately, there's nothing I could share right now. CRDs are still on our radar!

**Comment by Shm013** [comment]
I can offer workaround using Ansible Operator Fraemwork. https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/

It's seems relatively easy to make operator based on Ansibe. I want to wrap Ansible modules like [keycloak_client]( https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_client_module.html#ansible-collections-community-general-keycloak-client-module) or [keycloak_realm](https://docs.ansible.com/ansible/latest/collections/community/general/2_module.html#ansible-collections-community-general-keycloak-realm-module) into CRDs.

**Comment by alexander-bruun** [comment]
I would love to provide my assistance, feel free to reach out (here or on the Keycloak Slack channel) if I can contribute to this in some shape or form.

**Comment by vmuzikar** [comment]
@alexander-bruun That'd be awesome. :) Later, we'll share some initial design proposal and we can then discuss details over it.

**Comment by tomsit-ionos** [comment]
any update on the progress ?

**Comment by phmcder** [comment]
Are there any updates on this yet?

**Comment by calohmn** [comment]
Linking https://github.com/keycloak/keycloak-operator/issues/399 here: 
It would be good if the new `KeycloakClient` CRD is designed in such a way, that there is no `secret` field in there containing the plain text password. Instead, there could be a reference to a Kubernetes secret.

**Comment by vmuzikar** [comment]
Ass only Client CR is considered at the moment, closing this in favor of https://github.com/keycloak/keycloak/issues/31300.
