### ISSUE TITLE
New Update Email flow not working when "User Profile Enabled" enabled from realm.

### ISSUE THREAD

**Issue by sparkmylife** [keycloak/keycloak#13561]
### Describe the bug

When "User Profile Enabled" is disabled and update email is enabled , first name and last name became empty on clicking the email validation link. It clears the user profile attributes which were not sent.

But once we enable the "User Profile Enabled" from Realm General setting, we are getting error while confirming new email id on update.

![image](https://user-images.githubusercontent.com/15565805/183021290-2d365794-4af2-4002-ae8b-102654e77923.png)

### Version

V19.0.1

### Expected behavior

Only email id should be updated. It should work fine with "User Profile Enabled" enabled or disabled.

### Actual behavior

With "User Profile Enabled" disabled, first name and last name became empty.

With "User Profile Enabled" enabled, getting error "Please specify this field"

### How to Reproduce?

From the realm disable "User Profile Enabled" and enable "verify email". Go to user account profile and update email address. On clicking email confirmation link, first name and last name is removed from profile.

From the realm enable "User Profile Enabled" and enable "verify email".  Go to user account profile and update email address, getting error "Please specify this field"

### Anything else?

Only email id should be updated and no other use profile fields should be checked and updated

**Comment by lexcao** [comment]
It seems it is related to #13550.
I made a fix.

**Comment by sparkmylife** [comment]
@lexcao Pl. confirm the fix will cater to all custom attributes  (required/optional) which will be added to the user profile will not be impacted apart from first name and last name known attributes?
