### ISSUE TITLE
Tracking: Improve CLI storage options in quarkus

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#13562]
## Description

With #12615 and #12616, the Postgres and Cockroach DB has been integrated into Quarkus. The command-line options were marked as experimental and they can change in the future.

This issue is a tracking issue for development of stable CLI options that would be able to configure Quarkus with new store and keep good UX.

## Requirements

- It has to be *easy* to set up an in-memory storage and run Keycloak with it
- It has to be easy to pick a parameterizable storage profile together with its parameters
- It has to be possible to provide completely custom configuration

User feedback:

- #13445

**Comment by vramik** [comment]
There is https://github.com/keycloak/keycloak/pull/16549 touching this area. PR is sent into `quarkus3` branch.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
