### ISSUE TITLE
Run map-jpa model tests profile in GHA

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13573]
Currently, `mpa-jpa` profile is disabled because it wasn't possible to run Postgres in Model tests. Now with the changes from this PR: #13488 it should be possible to run Postgres similarly as it is done here: https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java#L107

**Comment by vramik** [comment]
It has been decided to limit the scope of the failing `ConcurrentAuthzTest` to `StoreFactoryCacheSession` provider. An issue for revisiting the test was created: https://github.com/keycloak/keycloak/issues/15071
