### ISSUE TITLE
New Admin console does not show User Storage SPI configuration fields

### ISSUE THREAD

**Issue by joeri-jansen** [keycloak/keycloak#13580]
### Describe the bug

We have a custom User Storage SPI implementation, with several configurable fields, like database URL and credentials. In the old admin interface, these settings show up when we add/edit the provider. However, the admin2 interface does not show the configuration fields.

![admin](https://user-images.githubusercontent.com/90042688/183111631-2479b9f1-6ff1-48c5-bf61-f7491298c8c1.png)
![admin2](https://user-images.githubusercontent.com/90042688/183111632-fa216b51-1cfd-411a-b328-a0213c8be90b.PNG)

To reproduce, follow these steps of the original Keycloak documentation:
https://www.keycloak.org/docs/latest/server_development/index.html#configuring-the-provider-in-the-admin-console

### Version

19.0.1

### Expected behavior

The custom config items are visible / can be modified.

### Actual behavior

Observed: the custom config items are not visible in the 'keycloak.v2' theme.
When the admin console theme is set to 'keycloak' the variables are visible.

### How to Reproduce?

To reproduce, follow these steps:
https://www.keycloak.org/docs/latest/server_development/index.html#configuring-the-provider-in-the-admin-console

**Comment by sbrajchuk** [comment]
Have same issue

**Comment by lexcao** [comment]
Hi, @joeri-jansen 
It seems related to the [#keycloak/keycloak-admin-ui](https://github.com/keycloak/keycloak-admin-ui)

Could you please clone an issue to it?

From my understanding, the new Admin UI currently might not support custom providers.

**Comment by joeri-jansen** [comment]
Duplicates issue https://github.com/keycloak/keycloak-admin-ui/issues/3059
