### ISSUE TITLE
Spelling error in the code

### ISSUE THREAD

**Issue by clayrisser** [keycloak/keycloak#13594]
### Describe the bug

The function `getProviderFactorytById` is spelled wrong. I know, it's nitpicky.

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java#L92
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java#L119
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java#L147
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/IdentityProvidersResource.java#L224

### Version

19.0

### Expected behavior

N/A

### Actual behavior

N/A

### How to Reproduce?

N/A

### Anything else?

N/A

**Comment by pedroigor** [comment]
@clayrisser Thanks.
