### ISSUE TITLE
Keycloak uses incorrect encryption keys as SAML identity brokers in SPSSODescriptor

### ISSUE THREAD

**Issue by Minhception** [keycloak/keycloak#13606]
### Describe the bug

Keycloak should send a SPSSODescriptor with a signature and an encryption key to a SAML identity provider. Instead of using a realm signature key for <md:KeyDescriptor use="signing"> and a realm encryption key for <md:KeyDescriptor use="encryption">, realm signing keys are used for signing AND encryption. Realm encryption keys are not considered at all.
I believe that the error is related to the following code location: 
https://github.com/keycloak/keycloak/blob/17.0.1/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java
```
session.keys().getKeysStream(realm, KeyUse.SIG, Algorithm.RS256)
                    .filter(Objects::nonNull)
                    .filter(key -> key.getCertificate() != null)
                    .sorted(SamlService::compareKeys)
                    .forEach(key -> {
                        try {
                            Element element = SPMetadataDescriptor
                                    .buildKeyInfoElement(key.getKid(), PemUtils.encodeCertificate(key.getCertificate()));
                            signingKeys.add(element);

                            if (key.getStatus() == KeyStatus.ACTIVE) {
                                encryptionKeys.add(element);
                            }
                        } catch (ParserConfigurationException e) {
                            logger.warn("Failed to export SAML SP Metadata!", e);
                            throw new RuntimeException(e);
                        }
                    });
```
Instead of KeyUse.SIG probably KeyUse.ENC should be used.

### Version

19.0.1

### Expected behavior

Realm signing keys are used in the SPSSODescriptor only under KeyDescriptor use="signing" and realm encryption keys under KeyDescriptor use="encryption".

### Actual behavior

Currently in the SPSSODescriptor realm signing keys are used for signing AND encryption while realm encryption keys are not used at all.

### How to Reproduce?

Create an active realm rsa key for signing and another one for encryption. 
Add a SAML identity provider and call the SPSSODescriptor of this identity provider:
<host>/auth/realms/<realm-name>/broker/<identity-provider>/endpoint/descriptor

**Comment by abstractj** [comment]
@mhajas even though I agree with @Minhception that it is a good security practice to use separate keys for signing and encryption, and I understand why it was flagged as a bug. At the same time, there's nothing wrong, about using the same key for both. 

From my perspective, I don't see it as a security flaw, but instead an enhancement. Splitting the keys can spread the risk, in case one of those keys is stolen. We have 2 alternatives, but @hmlnarik has way more experience than me:

1. Keep it as is, but in some way make it explicit into the code that we are using the same key for both, adding a meaningful name for that.
2. Use separate keys for each task, signing and encryption.

**Comment by hmlnarik** [comment]
I agree that this is an enhancement rather than bug. Current SAML key handling deserves refactor to get up to date to at least with #5309 changes, but is correct regardless. This enhancement should use separate keys for signing and encryption.

**Comment by dpulrichth** [comment]
If I'm not entirely mistaken then this is the same problem as discussed here: https://github.com/keycloak/keycloak/pull/8330

That pull request fixes this problem but unfortunately it has been up in the air for over a year now. @hmlnarik any chance you can take another look at the PR to fix this? @pedroigor has previously approved it but is waiting for your opinion.

**Comment by hmlnarik** [comment]
Together with @mhajas, we have reviewed the PR and found that the original PR is a good direction but has a few minor issues to be covered. This will be handled soon, and is going to supersede the original PR.
