### ISSUE TITLE
Modify `RealmsAdminResource.importRealm` to work with `InputStream`

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#13609]
Importing a realm via REST endpoint should not consume JSON realm representation but an `InputStream` instead.

The JSON realm representation is valid for the legacy store. The new store has to deal with either this representation or a native file with (likely) a file-store based structure.

This task is to prepare API so that the endpoint consumes `InputStream` and uses legacy / new store implementation logic to process the stream accordingly. This implies relevant changes in `RealmManager.importRealm` and `RepresentationToModel.importRealm`, pushing the conversion from the stream to representation as much to the storage layer as possible, and returning eventually the imported `RealmModel`.

**Comment by ahus1** [comment]
Hi @hmlnarik - I had a look at the code and the UI and came up with some questions where I'd like to learn more about before working on this issue: 

* The current UI allows the user to choose a file, a realm name and if the realm should be enabled or not. The UI then mangles everything into one JSON of one `RealmRepresentation` and passes that to the backend. I agree this could be just an input stream at the backend, still I see problems with this once there is the new store: I'd assume the format will be opaque to the UI, therefore  the backend would receive a file plus some parameters. So it will be `multipart/form-data`, and couldn't we use that content type to split it between the old and the new API?
* Looking at `RealmManager.importRealm`, the first thing it creates is a realm, and it is then working on that realm. Assuming the data is opaque to the service layer, this would be different IMHO that for example a `RealmManager` would get the file to import it ... or would it only receive the realm part of it? I'd like to learn more about how the data of the different areas would be stored and processed in the process.
