### ISSUE TITLE
Improve error handling when configuration env vars

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#13608]
### Description

This requires a little bit more investigation to properly set the scope of it.

One concrete example of confusing error message:
```
docker run --rm -e KC_DB=postgresdb -e KC_DB_USERNAME=test -e KC_DB_PASSWORD=test quay.io/keycloak/keycloak:19.0.0 start

Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.

...

ERROR: Failed to run 'build' command.
ERROR: java.util.NoSuchElementException: No value present
ERROR: No value present
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

Compare to CLI arguments:
```
docker run --rm quay.io/keycloak/keycloak:19.0.0 start --db postgredb --db-username test --db-password test


Changes detected in configuration. Updating the server image.
Invalid value for option '--db': postgredb. Expected values are: dev-file, dev-mem, mariadb, mssql, mysql, oracle, postgres
Try 'kc.sh build --help' for more information on the available options.
```

We should be consistent with the  error messages regardless if env vars or CLI args are used for configuration.

**Comment by gerethd** [comment]
would love to see this fixed, still an issue in 21.1. entering POSTGRES instead of postgress results in the same output

**Comment by nschipperbrainsmith** [comment]
I would also love to see this fixed, I was unable to find my issue only after digging through github issues. The error is very, very unhelpful and sends the developer down a rabbit hole figuring out what might cause it. 

Honestly, even a simple message like: Don't use KC_DB_URL  and KC_SCHEMA together etc. would make this way easier and less likely to occur.

**Comment by shawkins** [comment]
A related issue from #21816 is when KC_DB is set and --optimized is used, there's no message in the logs that db is an unknown property like there is when --db is used as a cli parameter.

@vmuzikar is also thinking on #https://github.com/keycloak/keycloak/issues/22667#issuecomment-1700477756 that the general message for unknown property could inticate whether it's because --optimized is in use - that would make it very clear in operator related scenarios.

**Comment by vmuzikar** [comment]
> general message for unknown property could inticate whether it's because --optimized is in use - that would make it very clear in operator related scenarios.

+1, instead of generic "unknown property" we could say something like "unavailable when using --optimized"
@mabartos @pedroigor WDYT?

**Comment by mabartos** [comment]
> +1, instead of generic "unknown property" we could say something like "unavailable when using --optimized"

Yep, agree.
