### ISSUE TITLE
Administrator REST API documentation link on the documentation page is broken

### ISSUE THREAD

**Issue by alia5gar** [keycloak/keycloak#13618]
### Describe the bug

Administrator REST API Documentation link which is available on the [documentation](https://www.keycloak.org/documentation.html) website is broken

### Version

19.0.1

**Comment by alias5gar** [comment]
Link redirects us to https://www.keycloak.org/docs-api/19.0/rest-api/index.html
Which is broken instead it should redirect to https://www.keycloak.org/docs-api/19.0.1/rest-api/index.html
