### ISSUE TITLE
Design file map storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#13625]
## Description

Design a file storage with properties described in #13624.

In addition to requirements stated there, the following properties have to be satisfied:

- It must be possible to pin an ID to an object so that renaming an object (say client) must preserve its references from other objects (say client roles or authorization services)
- Changing a single property must be an isolated change which changes at most one line
- The storage may leverage directory structure, e.g. to separate realms into separate directories

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
