### ISSUE TITLE
LDAP Filter not applied on user validation

### ISSUE THREAD

**Issue by cbontemps** [keycloak/keycloak#13628]
### Describe the bug

Hi Keycloak team,

**Summary** :  Custom User LDAP Filter in LDAP federation is not applied at validate user step. If an imported user "comes out" of the configured LDAP filter, it is still deemed valid in Keycloak and can still authenticate.

The case is with an LDAP User Federation in READ_ONLY mode to import users to Keycloak ( I suspect it also happens in UNSYNCED mode. ) The federation uses an LDAP filter to load only valid users from LDAP. For exemple I use a filter to include only members from a group and exclude disabled users based on custom attributes.

If a user is already loaded in Keycloak and then disabled in LDAP, it "comes out" of the LDAD filter. Now it can still authenticate in Keycloak, but I would expect the user to be invalid and deleted in Keycloak, such as described in https://lists.jboss.org/pipermail/keycloak-user/2019-January/016938.html

There is another person with the same issue here : https://keycloak.discourse.group/t/ldap-user-sync-how-to-remove-users-automatically/13764

Regards, 

Colin

### Version

15.0.2

### Expected behavior

If a user "comes out" the LDAP filter,  I would expect this user to be invalid and deleted in Keycloak, such as described in https://lists.jboss.org/pipermail/keycloak-user/2019-January/016938.html

### Actual behavior

The user stays valid in Keycloak.

### How to Reproduce?

1. Create an LDAP User federation in readonly mode.
2. Add filter such as "(sn=Doe)" -> only people with last name "Doe" are loaded to keycloak
3. Create entry "John Doe" in LDAP 
4. Sync the LDAP provider in Keycloak
  - John Doe is created in Keycloak and can authenticate
5. Rename John Doe as John Loe in LDAP
  - John Loe can still authenticate while being out of LDAP filter scope. 
 

### Anything else?

I think this used to work in Keycloak 11.

**Comment by iingawal** [comment]
It does work in Keycloak 18 at my environment, can you please confirm it ?

**Comment by cbontemps** [comment]
> It does work in Keycloak 18 at my environment, can you please confirm it ?

I tried after update to RH SSO 7.6 based on Keycloak 18 and indeed, it does fix this issue for me.

**Comment by pravsjv** [comment]
Does anyone know what piece of code is fixed in 18 to fix this issue?
