### ISSUE TITLE
Export and import in the new format

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#13626]
The map store export and import format will be the same as that of  file-store (#13624), perhaps packaged in a single .zip file.

Investigate way to implement it.

Depends on: #13624

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
