### ISSUE TITLE
File map storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#13624]
## Description

File map storage is a map storage where the contents is stored in a filesystem in a human-readable form.

As such, this storage is best suitable for workflows which require less concurrency or serve mostly static data. It thus also serves well in cases where the realm configuration data are stored in files and realm-dynamic data (like sessions or one-time codes) are stored in a fast data source, e.g. database or Infinispan.

File storage has the following properties
- No-downtime upgradable
- Data are stored exclusively in a filesystem within a single directory (subdirectories are possible there)
- Data have to be easily editable manually by administrators
- File structure must be meaningful in versioning systems (changes are easily trackable)

Subtasks (must have, covers export / import):

- [x] #13632
- [x] #16676
- [ ] #13625
- [ ] #13629
- [ ] #13630
- [ ] #13631
- [ ] #16817
- [ ] #13633
- [ ] #13634
- [ ] #13639

Subtasks (can be postponed):
- [ ] #13635
- [ ] #13636
- [ ] #13637
- [ ] #13638
- [ ] #13640

**Comment by dominikschlosser** [comment]
Is there a chance this will make the 20.0.0 release? We are looking forward to using this for configuration-as-code ;-)

**Comment by hmlnarik** [comment]
> Is there a chance this will make the 20.0.0 release? We are looking forward to using this for configuration-as-code ;-)

File storage will be ready after 20.0.0, and it will be announced in a blog post. 20.0.0 might be released earlier due to other priorities.

**Comment by ahus1** [comment]
The first bits of the file store have arrived in Keycloak 21. Follow this discussion for details: https://github.com/keycloak/keycloak/discussions/16768

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
