### ISSUE TITLE
Wrong feature flag used to decide if admin fine-grained-permissions should be enabled

### ISSUE THREAD

**Issue by sschu** [keycloak/keycloak#13647]
### Describe the bug

In several places, the flag `Profile.Feature.AUTHORIZATION` is used to decide if fine-grained permissions should be used. However, the correct flag is `Profile.Feature.ADMIN_FINE_GRAINED_AUTHZ`.

### Version

19.0.1

### Expected behavior

`Profile.Feature.ADMIN_FINE_GRAINED_AUTHZ` is used to decide whether admin fine-grained permissions checks should be performed.

### Actual behavior

`Profile.Feature.AUTHORIZATION` is used to decide whether admin fine-grained permissions checks should be performed.

### How to Reproduce?

Check source code.

### Anything else?

Also see discussion in https://github.com/keycloak/keycloak/pull/12654

**Comment by sschu** [comment]
PR provided: https://github.com/keycloak/keycloak/pull/13648

**Comment by DelusionalLogic** [comment]
This really ought to have been mentioned in the changelog.

Like the test that was modified in this commit I was running with token-exchange enabled, but without fine-grained-permissions. That obviously broke during the upgrade to 20. A mention in the changelog would have eased that migration significantly.

**Comment by sschu** [comment]
@DelusionalLogic You are right, sorry about that. We are not using token-exchange so I was not aware of the implications.

**Comment by DelusionalLogic** [comment]
@sschu Happens to the best of us. Thank you for your time, both for the response and for the programming :)
