### ISSUE TITLE
Create per-request object caching map storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#13641]
## Description

The JPA / Hot Rod storage implementations suffer from a common pattern where the same object is retrieved multiple times throughout processing a single request from the store, often via `getById` type of method (see #11744).

This task is to create a generic implementation which will serve as per-request cache for any area, and will store all objects per ID.

Additional properties like searching by username / client ID will be implemented separately from this task.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
