### ISSUE TITLE
MapRealmAdapter.getAttributes can result in NPE as value mapper function can result in a null value

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#13658]
### Describe the bug

The `MapRealmAdapter.getAttributes` method uses a map collector to construct a `Map` from the realm entity's attributes. The value mapper function used can result in `null` values, which leads directly to an NPE if, for example, an attribute was stored with a `null` value.

While the code that sets an attribute in the entity should never pass `null` values for attributes, the function in this method does explicitly return `null` in certain circumstances and this should be changed because the value mapper function cannot result in a `null` value.

### Version

main

**Comment by sguilhen** [comment]
The code's value mapper function still explicitly returns null if the value is either null or empty. Even if we guarantee that the no empty/null values are ever stored, I think we should change the method so that it filters out "invalid" attribute values before mapping.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
