### ISSUE TITLE
Health checks fail when using relative paths in 19.0.0-1

### ISSUE THREAD

**Issue by EmpathicKernel** [keycloak/keycloak#13659]
### Describe the bug

When configuring relative paths at build time for both 19.0.0 and 19.0.1, health checks fail to respond even on the container itself. This works as expected on 18.0.2.

### Version

19.0.1

### Expected behavior

Building with a `--http-relative-path` configured along with `--health-enabled` and `--metrics-enabled` set to true should provide a health check responding on `http://localhost:8080/auth/health/live` and  `http://localhost:8080/auth/health/ready` when curling locally from the container.

This is with `--http-relative-path=auth`

### Actual behavior

Building with a `--http-relative-path` configured along with `--health-enabled` and `--metrics-enabled` set to true results in  the following errors when curling the health check paths locally from the container:

```
{"error":"RESTEASY003210: Could not find resource for full path: http://127.0.0.1:8080/auth/health/live"}
{"error":"RESTEASY003210: Could not find resource for full path: http://127.0.0.1:8080/auth/health/ready"}
```

This is with `--http-relative-path=auth`

Note: If `--http-relative-path` is not set during build time, the health checks work as expected from `http://localhost:8080/health/live` and `http://localhost:8080/health/ready`

### How to Reproduce?

Build keycloak container using version 19.0.0 or 19.0.1. Set the HTTP_RELATIVE_PATH during build along with HEALTH_ENABLED and METRICS_ENABLED set to true.

Exec into the container and attempt to curl for the health check against localhost.

### Anything else?

My Dockerfile (I'm electing to build using ENV Vars instead of the CLI Args but I've tested both ways with the same results):

```
FROM quay.io/keycloak/keycloak:19.0.1 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=auth
ENV KC_DB=postgres
ENV KC_CACHE=ispn
ENV KC_CACHE_STACK=kubernetes

# Install custom providers
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build

RUN curl -sL https://github.com/DataDog/dd-trace-java/releases/download/v0.98.1/dd-java-agent-0.98.1.jar -o /opt/keycloak/dd-java-agent.jar

FROM quay.io/keycloak/keycloak:19.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENV KC_LOG_CONSOLE_OUTPUT=json
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY=edge

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

Current setup is Keycloak running in a replica set on Kubernetes and Postgres backed. Tested this locally as a single Docker container and Postgres backed with same results. 18.0.2 currently works as expected with only changes to Dockerfile being container version being pulled from quay.io as well as the removal of `--optimized` from entry point.

**Comment by DGuhr** [comment]
@EmpathicKernel pls set your relative path to start with a `/` - I just created a (currently missing) test for this use case, and it worked with `--http-relative-path=/auth`, but returned a 404 when using `--http-relative-path=auth` as you do in your config. Will provide a PR containing the test and maybe a line in the docs to state that the relative path has to start with a `/`

**Comment by EmpathicKernel** [comment]
Thanks @DGuhr and @pedroigor, we were able to deploy 19.0.1 without any issues after prepending the `/` to our relative path.

We were under the assumption that the health check changes wouldn't affect us as we were never relying on the `/q/` endpoint that we knew of but seems that we were. Thanks for the quick reply on this!
