### ISSUE TITLE
Make compatibility mode for oidc logout endpoint fully compatible to previous keyloak versions

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#13657]
### Description

This is about backport of https://github.com/keycloak/keycloak/issues/13469 to Keycloak 19.0.2.

There is also documentation PR https://github.com/keycloak/keycloak-documentation/pull/1658, which should be backported as well.

**Comment by sschu** [comment]
@mposolda Should we file a PR to the 19.0.0 branch?
@bs-matil FYI

**Comment by mposolda** [comment]
@bs-matil @sschu Yes, that would be welcome. There is "19.0." branch for both codebase and documentation:
https://github.com/keycloak/keycloak/tree/19.0
https://github.com/keycloak/keycloak-documentation/tree/19.0

**Comment by bs-matil** [comment]
@mposolda provided both backports.

**Comment by bs-matil** [comment]
@mposolda  anything do to here?

**Comment by mposolda** [comment]
Backported to branch "19" in the commit https://github.com/keycloak/keycloak/commit/d3aeeb8ea9fabb6119ca542b27f1c07b65324943
