### ISSUE TITLE
Disabling features (impersonation) not working with Dockerfile

### ISSUE THREAD

**Issue by tonial** [keycloak/keycloak#13688]
### Describe the bug

I need to disable the feature for security reasons, so I followed these documentations :
- https://www.keycloak.org/server/features#_disabling_features
- https://www.keycloak.org/server/containers#_building_your_optimized_keycloak_docker_image

I now have the following Dockerfile but when running the dev server, I can still impersonate users.

```
FROM quay.io/keycloak/keycloak:latest
RUN /opt/keycloak/bin/kc.sh build --features-disabled=impersonation
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

Am I missing something ?

### Version

19.0.1

### Expected behavior

User impersonation should not be available in the Administration console. 

### Actual behavior

I can still see (and use) the impersonate action on users.

**Comment by lexcao** [comment]
Hi, Could you please try this?
* Attempt 1
```
RUN /opt/keycloak/bin/kc.sh build --features-disabled=impersonation
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

* Attempt 2
```
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--features-disabled=impersonation"]
```

---
From my understanding. There will build and then run when using `start-dev`, while
there are seperated commands for `build` and `start`.

**Comment by tonial** [comment]
Hi, 

Thank for your answer.

I couldn't make the first attempt work on my laptop.

The second attempt didn't work.

I also tried this other Dockerfile :
```
FROM quay.io/keycloak/keycloak:latest
ENV KC_FEATURES_DISABLED=impersonation
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

In all tested cases (my first Dockerfile, your Attempt2 and my last Dockerfile) I could impersonate a user.
The strage thing is that with both `ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--features-disabled=impersonation"]` and `ENV KC_FEATURES_DISABLED=impersonation` I could see that in the Administration Console : 
![Screenshot from 2022-08-10 21-11-41](https://user-images.githubusercontent.com/7632730/183999746-8da2f062-e013-4613-85af-44eb6746bd32.png)

And with just 
```
FROM quay.io/keycloak/keycloak:latest
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```
or with my first Dockerfile there's no `IMPERSONATION` in `Enabled features`:
![Screenshot from 2022-08-10 21-10-25](https://user-images.githubusercontent.com/7632730/184000175-0711bdf0-71ad-49fb-af80-4def43b28f5c.png)
But I can still impersonate a user

**Comment by lexcao** [comment]
Hi, @tonial 
Sorry for mentioning that attempt 2 was just fixed in #13517, which is not included in `19.0.1`
So, the `start-dev` when passing param is not working before the fix is released.

Could you please try this? 
* use `build` and `start` for production profile
```
FROM quay.io/keycloak/keycloak:latest

ENV KC_FEATURES_DISABLED=impersonation

RUN /opt/keycloak/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
```

**Comment by tonial** [comment]
Hi @lexcao.

This Dockerfile behaves exactly as the second screenshot : `IMPERSONATION` isn"t displayed in either enabled of disabled features, but I can still use it.

**Comment by lexcao** [comment]
Hi, I have reproduced with the Dockerfile. See the screenshot below.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/14901139/184497119-757e2803-d50b-4217-b17b-f58c1ac10fab.png">

---
# Attempt 
I tried to build the image with the latest source code, And it works fine.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/14901139/184498473-7725a8c2-9490-4630-94dc-e6d617928959.png">


I think this PR #13517 may fix this issue.

**Comment by tonial** [comment]
Hi @lexcao 

That's great, I'll wait for the next release.
Thanks a lot for your help !
