### ISSUE TITLE
Realm Email doesn't default to port 25

### ISSUE THREAD

**Issue by chuegel** [keycloak/keycloak#13704]
### Describe the bug

Email configuration of the realm doesen't use the default port:

![image](https://user-images.githubusercontent.com/6955465/183929263-e9eaeda7-7877-433f-bbd9-296b2780557f.png)

### Version

19.0.1

### Expected behavior

Emails should be able to be send with the default port 25 but it needs to be explicitly set 

### Actual behavior

Keycloak tries to send mails without a port:

```bash
2022-08-10 14:33:19,499 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-1095) Failed to send email
 com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.*****.com, 0; timeout 10000;
  nested exception is:
	java.net.SocketTimeoutException: connect timed out
```

### How to Reproduce?

1. configure SMTP settings and leave port to default (no entry)
2. try to send mail and watch the errors in the logs
3. set the port 25 and redo no. 2

**Comment by lexcao** [comment]
Hi @chuegel 
I think it is an issue related to new Admin UI.
Could you please clone this issue to https://github.com/keycloak/keycloak-admin-ui/issues/ ?

**Comment by chuegel** [comment]
Done: https://github.com/keycloak/keycloak-admin-ui/issues/3097
