### ISSUE TITLE
KeycloakQuarkusServerDeployableContainer doesn't configure new storage tests correctly

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13721]
### Describe the bug

There is a bug in configuration of new storage for `auth-server-quarkus`.

https://github.com/keycloak/keycloak/blob/e3af0610e21961c1e8d074a223f9fffee0e56dde/testsuite/integration-arquillian/tests/base/pom.xml#L865

is not equal to:

https://github.com/keycloak/keycloak/blob/e3af0610e21961c1e8d074a223f9fffee0e56dde/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/arquillian/containers/KeycloakQuarkusServerDeployableContainer.java#L57

### Version

main

**Comment by mabartos** [comment]
@mhajas Yes, you're right. I'm just working on it [1]. However, it means, that the GH action, which uses CHM store (map-storage), hasn't been never properly executed. Feel free to create a PR for this particular change, but I spotted some failures in the map-storage GH action when I enabled that. 

[1] https://github.com/keycloak/keycloak/pull/13643
