### ISSUE TITLE
JSON Parse error: Unexpected identifier "undefined"

### ISSUE THREAD

**Issue by q5616417** [keycloak/keycloak#13728]
### Describe the bug

When trying to view the details of an idp-Mapper created with a pre 18 version of keycloak in the admin console, I'm getting "JSON Parse error: Unexpected identifier "undefined"". New mappers show up as expected. Sure, a workaround would be to recreate the old mappers, but thought it would be useful for you to know.

### Version

19.0.1

### Expected behavior

All idp mapper details show up in admin console

### Actual behavior

pre-keycloak-18-created mappers give the error "JSON Parse error: Unexpected identifier "undefined""

### How to Reproduce?

In admin-console click "Identity Provider" -> click your idp -> click "Mappers" -> click one mapper

**Comment by lexcao** [comment]
Hi, are you using the new Admin UI?
If so, please check this https://github.com/keycloak/keycloak-admin-ui/issues/3022
It is a duplicated issue for the new Admin UI.

**Comment by GVincenzo** [comment]
Hi,
I have the same problem.
I'm using the new UI (I just installed the last 19.0.1 keycloak version)
New Identity provider mappers work as expected while the old ones brokes.

Looking in chrome's network, i just see the differences in response:
```
//NEW
{
    "id": "38c968ba-8313-443e-8b86-ddecb8811d96",
    "name": "test",
    "identityProviderAlias": "oidc",
    "identityProviderMapper": "oidc-user-attribute-idp-mapper",
    "config": {
        "are.claim.values.regex": "false",
        "claims": "[{\"key\":\"\",\"value\":\"\"}]",
        "syncMode": "INHERIT",
        "claim": "test",
        "user.attribute": "test",
        "attributes": "[]"
    }
}
//OLD
{
    "id": "b7519842-4c0c-46e1-a9b2-3c0aca73735b",
    "name": "context",
    "identityProviderAlias": "oidc",
    "identityProviderMapper": "oidc-user-attribute-idp-mapper",
    "config": {
        "syncMode": "FORCE",
        "claim": "context",
        "user.attribute": "context"
    }
}
```
the error chrome report in console, is:
```
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at K (4062.js:1:3540)
    at 4062.js:1:3444
    at index.js:2:304683
```

**Comment by lexcao** [comment]
Hi @GVincenzo 
Thanks for reporting.
Yes, it is the duplicated.

**Comment by ttu75** [comment]
Same error with mapper type "Attribute Importer" in idp-mapper, I cannot view any existing mapper which were created at 18. 
I tried to create a new mapper, look like there is new field "ATTRIBUTE_FORMAT_BASIC", which any existing mapper doesn't have it.  Is this same issue as other mapper type?
