### ISSUE TITLE
Broker links are not deleted upon deletion of an identity provider

### ISSUE THREAD

**Issue by arthur25000** [keycloak/keycloak#13731]
### Describe the bug

When an identify provider is deleted, the content of the table BROKER_LINK for this identity provider is not deleted

### Version

19.0.1

### Expected behavior

When an identify provider is deleted, the content of the table BROKER_LINK for this identity provider is deleted

### Actual behavior

When an identify provider is deleted, the content of the table BROKER_LINK for this identity provider is not deleted

### How to Reproduce?

1) Create an identity provider
2) Link with an account
3) Delete the identity provider

### Anything else?

The problem is that the namedquery is not executed (missing .executeUpdate() on the query) in the method org.keycloak.storage.jpa.JpaUserFederatedStorageProvider#preRemove(org.keycloak.models.RealmModel, org.keycloak.models.IdentityProviderModel)

**Comment by lexcao** [comment]
Interesting, I think there may be some tests missing as well.
Would you like to make a PR to fix this?

If not, I am willing to help you. 😃

**Comment by arthur25000** [comment]
Yes, I'll try to submit a PR for it. I actually try last week to compile the source code bu I had some minors compilation issues due to my environment. I'll continue this week and let you know if I need help.

**Comment by lexcao** [comment]
Thank you, I am willing to help.

**Comment by arthur25000** [comment]
@lexcao I managed to compile the Keycloak distribution but not all integration tests would pass on my machine due to some environment issues. I don't have much time to fully investigate. The IdentityProviderTest is passing and it seemed to me it was the one I should add a test into. Let me know if it's not the case.

**Comment by lexcao** [comment]
Hi @arthur25000 
I think it is not required to pass all integration tests locally.
The `IdentityProviderTest` is fine to add to the test.
Could you please check this method as well?
```
org.keycloak.testsuite.broker.AccountLinkTest#testDeleteIdentityOnProviderRemoval
```

**Comment by arthur25000** [comment]
Hi @lexcao 
This test is okay since it tests federation link deletion for a local user and the method org.keycloak.models.jpa.**JpaUserProvider**#preRemove(org.keycloak.models.RealmModel, org.keycloak.models.IdentityProviderModel) does execute the query.

The bug only concerns federated users because in such case, the federation link is created in the BROKER_LINK table and these records should be delete by the method org.keycloak.storage.jpa.**JpaUserFederatedStorageProvider**#preRemove(org.keycloak.models.RealmModel, org.keycloak.models.IdentityProviderModel) which is affected by the bug.

I didn't see this AccountLinkTest class when I wrote the test. Should I move / adapt the test I've added into this class rather than the IdentityProviderTest ?

**Comment by arthur25000** [comment]
Sorry, for the closing/reopening of the issue. The default github behavior is to create a merge commit when syncing repo from the web UI so I've hard reset my repo which had the consequence to close the PR and the bug here.

**Comment by lexcao** [comment]
Hi, @arthur25000 
I think it would be better to write a test `testDeleteFederatedIdentityOnProviderRemoval` in `AccountLinkTest`.

**Comment by arthur25000** [comment]
Hi @lexcao ,
Just a quick update to confirm I'm on it. I moves the test but it didn't work as expected. I need to investigate further but I was quite busy last week. I'll have a look today or tomorrow and hopefully I'll push the fix + test this week.

**Comment by arthur25000** [comment]
Hi @lexcao 
The PR is ready. Let me know if it is okay.
