### ISSUE TITLE
Zip files from adapter config download are broken

### ISSUE THREAD

**Issue by 0xpr03** [keycloak/keycloak#13733]
### Describe the bug

If you create a SAML client and download the keycloak-mod-auth-mellon-sp-config.zip for the Mod Auth Mellon configuration, you get a broken zip file.

### Version

9.0.1

### Expected behavior

Valid zip file

### Actual behavior

Invalid zip file

```
Archive:  keycloak-mod-auth-mellon-sp-config.zip
warning [keycloak-mod-auth-mellon-sp-config.zip]:  3552 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [keycloak-mod-auth-mellon-sp-config.zip]:  start of central directory not found;
  zipfile corrupt.
```

### How to Reproduce?

Basic Setup behind nginx reverse proxy.

Create a SAML client and click on `Download Adapter Config` -> `Mod Auth Melon`

### Anything else?

See also here for another case of broken zip files: https://github.com/keycloak/keycloak/discussions/13723 In that case for a completely different thing. Maybe zipping itself it broken.

**Comment by mhajas** [comment]
I am closing this in favour of #13955
