### ISSUE TITLE
ComponentFactory.getConfigProperties() does not work with keycloak.v2 in UserStorageProvider

### ISSUE THREAD

**Issue by Guy-Incognito** [keycloak/keycloak#13753]
### Describe the bug

It seems that the new admin console theme `keycloak.v2` does not support rendering config properties from  `ComponentFactory.getConfigProperties()` as described in the developers guide:
https://www.keycloak.org/docs/latest/server_development/#configuration-example

We encountered this issue with a custom `UserStorageProvider` [Source Code](https://github.com/daniel-frak/keycloak-user-migration)

When opening the User Federation Provider Config, no config options are displayed:
![184153200-7153c4bc-df65-4a36-bc05-be2ef7d4ddc4](https://user-images.githubusercontent.com/2777794/184328791-fb9105f8-2dcf-48e5-bdf5-43d1e451c838.png)

For now we switched back to the `keycloak` theme, were everything still works fine. But since this will be dropped in v21 we would very much like to fix this.

I know that the User Storage SPI is marked as [deprecated](https://www.keycloak.org/docs/latest/server_development/#_user-storage-spi). If this issue is connected, can you please point me towards a way to migrate?

Thank you!

### Version

19.0.1

### Expected behavior

When providing config options via ComponentFactory.getConfigProperties() they should be displayed on the settings screen of the corresponding  UserStorageProvider.

> 

### Actual behavior

When providing config options via ComponentFactory.getConfigProperties() they are not displayed on the settings screen of the corresponding  UserStorageProvider.

### How to Reproduce?

Include [Custom UserStorageProvider](https://github.com/daniel-frak/keycloak-user-migration) in your keycloak v19 instance.
Go to `User federation`. Add new  `User migration using a REST client`.

**Comment by lexcao** [comment]
Seems it is a duplicated issue from https://github.com/keycloak/keycloak-ui/issues/2989
