### ISSUE TITLE
New Admin Console has only limited support for fine-grained authZ

### ISSUE THREAD

**Issue by tkautenburger** [keycloak/keycloak#13766]
### Description

The new keycloak.v2 admin console has only limited support for fine-grained authorizations, e.g. an administrator with the correct permissions to manage the member of a group cannot see the users in the group without having coarse-grained view-users permission set (which is bad, because the admin should only see the users of that group he is authorized for). Looking into the javascript code for the new admin console, one can see that routing to user detail page is wired fixed to coarse grained "view-users" authorization. 

For when is it planned to fully support fine-grained authZ for the new admin console, that would be extremely helpful. Our solutions build greatly upon the possibilities of using fine-grained permissions on group and role levels. 

### Motivation

It provides high value and also a consistent user experience with the features of the classic admin console.

**Comment by tkautenburger** [comment]
I guess i put this in the wrong project, admin-ui has own repo

**Comment by ssilvert** [comment]
@tkautenburger The new admin console is intended to fully support fine-grained authorization equivalent to the old console.  But this is a bug.  See https://github.com/keycloak/keycloak-ui/issues/3090.

Also see pull request https://github.com/keycloak/keycloak-ui/pull/3111.  I'd like to get your feedback to make sure that resolves your issue.  Thanks.
