### ISSUE TITLE
Up From Version 17.0.1 Console Log from outside does not load

### ISSUE THREAD

**Issue by b1tw0rker** [keycloak/keycloak#13775]
### Describe the bug

First Awful: I do not have local access via https://localhost.
So far only Version 17.0.0 is working fine on a linux system running RockyLinux 9 , connection to keyclock admin with initial-admin

I am using: Let's Encrypt Cert, admin is in my envirnoment like, no firewall.

```
export KEYCLOAK_ADMIN=admin
export KEYCLOAK_ADMIN_PASSWORD=admin
```

my keyclock.conf (which works like charm with version 17.0.0):

```
# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
#db=postgres

# The username of the database user.
#db-username=keycloak

# The password of the database user.
#db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
#db-url=jdbc:postgresql://localhost/keycloak

# Observability

# If the server should expose metrics and healthcheck endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
https-certificate-file=/etc/letsencrypt/live/sso.somehostname.com/cert.pem

# The file path to a private key in PEM format.
https-certificate-key-file=/etc/letsencrypt/live/sso.somehostname.com/privkey.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
hostname=sso.somehostname.com:8443
```

- I runned: 

kc.sh build
kc.sh start-dev or kc.sh start

After Clicking on "Administration Console", which should bring my to the Loginpage,
the screen is just showing: "Loading Admin Console" - That's it. Nothing more is upcoming.
The urlbar shows: https://sso.somehostname.com:8443/admin/master/console

### Version

19

### Expected behavior

Showing Loginpage

### Actual behavior

Does not show login page.

**Comment by lexcao** [comment]
Hi, could you please provide some info to help me debug?
> the screen is just showing: "Loading Admin Console" 

Could you please check the browser tools to see if there is an error on the network or console when loading?
