### ISSUE TITLE
Documentaion for database mssing importned information.

### ISSUE THREAD

**Issue by b1tw0rker** [keycloak/keycloak#13778]
### Describe the bug

In the Documentation on: https://www.keycloak.org/server/db importent information are missing.

Why not saying in one sentence:

Using MySql, the database 'keaycloak' must be created manually **before** running 'kc.sh build --db mysl'

And why not explaing if i have to use the command: 'kc.sh build --db mysl' everytime i make changes on the .conf file or is this a "one timer command" ?!?

### Version

17+

### Expected behavior

Explain more detailed

### Actual behavior

less, poor explanation...

**Comment by lexcao** [comment]
Could you please try these?

Attempt 1
```
# add to env
KC_DB=mysql
```

Attempt 2
```
# at keycloak.conf
db=mysql
```
