### ISSUE TITLE
Disable Keycloak sessions

### ISSUE THREAD

**Issue by eldarj** [keycloak/keycloak#13789]
### Description

There are plenty of reported issues that relate to the Keycloak page rendering **You are already logged in**, or the **You are already logged in with x user**

In order to avoid these issues, how can I disable Keycloak sessions entirely? I'd like Keycloak to not persist any session at all for the login flows, which I use with redirects and integrate with my app.

I didn't find much docs on this, but I've read that supposedly you cannot disable sessions if you want the to use the browser (redirect based) flow, is that right?

Is there any way to achieve this from UI? If not from UI, can I extend a Provider and override this behavior?

Also could we implement this as an enhancement - **allow using browser flows, but without user sessions**, or at least to use them only within the flow, and only until the flows are _ongoing e.g._ Login, 2FA, Verification etc. and once all is done, and user is redirect to target secured application; Keycloak deletes the session. Is this possible? 

### Motivation

There's no way to not use sessions with browser flows, even when sessions aren't needed

**Comment by lexcao** [comment]
Could you please try the `offline` scope, which saves the user session into the database?

Regarding annoying already login, I found there is no response from the Keycloak team (#12406)

**Comment by darius-m** [comment]
I do not believe that it would make sense to remove the sessions on Keycloak's end once the user has finished authenticating, since you usually may need such information for auditing and statistics. However, if you want users to authenticate whenever they click the `Login` button inside a client, you could remove the cookie authentication alternative. After disabling it, Keycloak should functionally ignore all cookies set inside the browser, and require manual authentication on every login.

**Comment by eldarj** [comment]
Yup, that's exactly what I ended up doing, thanks @darius-m 

Within the custom authenticator that I have, I manually check for the cookies and remove them if present - the reasoning at least for my use case is that if a user for whatever reason ends up on the login page - you want to allow them to login, instead of showing the very naive and underwhelming page with the message _"You are already logged in."_

As for whether it makes sense to remove the sessions - that depends on the use case pretty much. It would be nice if there could be an Admin Console setting for this. It feels much more natural to do things in a stateless fashion, especially if you go down that route with your apps.

**Comment by eldarj** [comment]
@daviddelannoy I no longer have the code, but I'll check if I can recall how to implement it

**Comment by ahus1** [comment]
This has been handled in Keycloak 25 (see https://www.keycloak.org/docs/latest/release_notes/#addressed-you-are-already-logged-in-for-expired-authentication-sessions) and Keycloak 23 (see https://www.keycloak.org/docs/latest/release_notes/#you-are-already-logged-in), so this message "You are already logged in" should no longer appear.
