### ISSUE TITLE
Old admin console does not find keycloak.js when url is not set with a tailing /

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#13786]
### Describe the bug

running `./standalone.sh -Dkeycloak.frontendUrl=http://localhost:8080/auth -Dkeycloak.profile.feature.admin2=disabled` without adding a tailing `/` to the frontendUrl leads to a non-working admin console page because the now as per #11109 relative path for the keycloak.js file is then set to `/authjs/keycloak.js` instead of the correct `/auth/js/keycloak.js`

### Version

<=latest

### Expected behavior

js path is correct

### Actual behavior

missing a / in parsed relative js path, which leads to problems when frontendUrl is set to a value without tailing `/`

### How to Reproduce?

download latest keycloak legacy. start using `./standalone.sh -Dkeycloak.frontendUrl=http://localhost:8080/auth -Dkeycloak.profile.feature.admin2=disabled` 

### Anything else?

The new admin console does not use this path anymore, so there it doesn't happen.

**Comment by vmuzikar** [comment]
Reopening as this will get backported to 19.0.2.

CC: @Pepo48
