### ISSUE TITLE
Brute force detection not work

### ISSUE THREAD

**Issue by approached** [keycloak/keycloak#13782]
### Describe the bug

I enabled the **Brute force detection** but it not works.

Settings:
<img width="861" alt="Screenshot 2022-08-15 at 10 49 04" src="https://user-images.githubusercontent.com/3439330/184605420-6ce2ad34-f63d-4237-a546-2d122c7a257e.png">

I have entered my password incorrectly 3 times but nothing happens. 

### Version

19.0.1

### How to Reproduce?

I' am use a reverse proxy (traefik).

**Comment by lexcao** [comment]
Hi, I have tested with the same configuration as yours.
It works as expected from my side.
I attempt 4 times, and the login events are
```
invalid_user_credentials
invalid_user_credentials
invalid_user_credentials
user_temporarily_disabled
```

> entered password incorrectly 3 times

Then the next time should be disabled temporarily.

**Comment by approached** [comment]
@lexcao thank you for your comment. It works as described. I have imagined the function a little differently:

1. you don't see a response in the fronted UI that you are locked 👎 
2. if you enter wrong username then it does not count 👎
