### ISSUE TITLE
Unable to build in IntelliJ after clean install

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#13793]
### Describe the bug

After importing Keycloak into a freshly installed IntelliJ I'm no longer able to build Keycloak.

When doing a build/rebuild I get the following error:

```
/home/st/dev/keycloak/operator/src/main/java/org/keycloak/operator/crds/v2alpha1/realmimport/KeycloakRealmImportSpec.java:20:40
java: package org.keycloak.representations.idm does not exist
```

After getting rid of the operator module (deleted from parent pom.xml) it is still not working and just moving on to the next problem:

```
keycloak/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/common/CommonPrimitivesProtoSchemaInitializer.java:40:63
java: cannot find symbol
  symbol:   class CommonPrimitivesProtoSchemaInitializerImpl
  location: interface org.keycloak.models.map.storage.hotRod.common.CommonPrimitivesProtoSchemaInitializer
```

### Version

main

### Expected behavior

Importing Keycloak into IntelliJ just works, or if some config is required prior it must be documented.

### Actual behavior

Unable to run anything from within IntelliJ due to compilation issues.

### How to Reproduce?

1. Use latest IntelliJ community edition
2. Delete IntelliJ config (this may not be required)
3. Delete IntelliJ files within Keycloak project (.idea and *.iml files)
4. Open Keycloak project and try to run KeycloakServer, or run a build/rebuild of the project

**Comment by vmuzikar** [comment]
As a workaround until we're able to properly triage this, please try to disable the `operator` profile in Maven panel in your IDEA, or build the operator module using plain mvn, e.g. `mvn clean install -DskipTests -f operator`. Please note the operator module is excluded by default and is not built with rest of the project. Not sure why the IDEA is trying to build that module when the `operator` profile was not explicitly enabled.

**Comment by mhajas** [comment]
@stianst regarding the issue with the hot-rod module. I have seen this issue already, mostly when I make some changes in that module. However, I have never seen this when I use `mvn` command, only in Intellij. 

What usually fixes it for me is `right click on that module -> Run Maven -> clean` and then `right click -> Rebuild Module`.

I am not sure what exactly is the problem, but it may be something with Intellij not being able to handle two generators configured for one module.

**Comment by vmuzikar** [comment]
I was able to involuntarily reproduce. :D Created docs for it: https://github.com/keycloak/keycloak/pull/14093
