### ISSUE TITLE
Keycloak sessions do not get removed after the time period set in admin console

### ISSUE THREAD

**Issue by eldarj** [keycloak/keycloak#13790]
### Describe the bug

Whatever values I set for the session lifespans (SSO, Client, etc.) on both Realm and Client level, are just ignored ie. the session I can see under a specific User - Sessions are still there

![image](https://user-images.githubusercontent.com/28787596/184632381-f185a2de-6af6-44a7-83b1-3e926a0fc057.png)

### Version

15.0.2

### Expected behavior

Set session lifespans to 1 minute - session gets removed after 1 minute

### Actual behavior

Set session lifespans to 1 minute - session isn't removed after 1 minute

**Comment by lexcao** [comment]
From my understanding,
Set session lifespans to 1 minute, which means the expiration time of cookie `KEYCLOAK_SESSION` is 1 minute.
And for the backend lifespans, it would run a background task to clean the sessions.

The interval of the task is
```
long interval = Config.scope("scheduled").getLong("interval", 900L) * 1000;
```

Maybe it would be removed after the next task.

**Comment by eldarj** [comment]
Thanks a lot @lexcao unfortunately this didn't work, I'm not sure if this is a bug on KC side or if some other vague behavior is in place.

**Comment by stianst** [comment]
Sessions are purged by default using a background task, but that doesn't mean the sessions would still be valid. They just haven't been garbage collected yet.

Closing this one as firstly it makes no sense to have a 1 min session lifespan, and secondly there's no real bug here.

**Comment by eldarj** [comment]
> Sessions are purged by default using a background task, but that doesn't mean the sessions would still be valid. They just haven't been garbage collected yet.

What do you mean by this? This is confusing, but in either case - the question is why does a session still exist after the specified time has elapsed? 

Whether it's purged, garbage collected or whatever the mechanism - if you set the lifespan to 5 minutes, it shouldn't exist after 5 minutes. And if this doesn't work like so, either it's a bug or the UI needs to be more clear on what is happening. 

I assume the sessions get marked for deletion but are deleted only once a scheduled job runs in the background. If so, then this time should be defined as the minimum when setting lifespans on the UI.

Regarding 1 min session lifespan however - that obviously would be a workaround because as of now, there's no way to disable sessions entirely.

**Comment by sschu** [comment]
Keycloak does check if a session is still valid or if it is expired and won't use it when it is already expired. The background task removing the session just only runs in certain intervals to do the final deletion.

**Comment by eldarj** [comment]
Thanks a lot for clarifying @sschu
