### ISSUE TITLE
Themes keycloak.v2 break custom provider

### ISSUE THREAD

**Issue by nathmo** [keycloak/keycloak#13806]
### Describe the bug

Using the new keycloak.v2 themes don't display the interface correctly of our custom user provider.
![image](https://user-images.githubusercontent.com/15912256/184863479-c6b7ba20-47db-4acb-9dc2-be5e76302752.png)
![image](https://user-images.githubusercontent.com/15912256/184863341-ac55cf80-c857-4b7a-b586-0fac0cc7a5ef.png)

but with the old keycloak themes it works just fine
![image](https://user-images.githubusercontent.com/15912256/184863763-a6a52ce0-d32f-4416-a9e4-7acb5ff9696f.png)
![image](https://user-images.githubusercontent.com/15912256/184863397-372cc2ed-5ba4-4f3a-aefc-74291212c8dd.png)
I couldn't find another user federation plugins to test if the issue is only for our provider or any, But the identity providers plugins seems to work. Maybe it's a bug in our code, but I didn't see any change in the documentation regarding the template.

### Version

19.0.1

### Expected behavior

that both themes would work as expected and display all the field.

### Actual behavior

all the custom field of the custom providers are not rendered with the themes keycloak.v2

### How to Reproduce?

Install the .jar in the providers folder of keycloak.
Under realms settings -> themes, switch between keycloak and keycloak.v2 for the admin UI
(don't forget to clear the cache by opening a new private browser, for instance)
[CustomUserProvider.zip](https://github.com/keycloak/keycloak/files/9350675/CustomUserProvider.zip)

and here is the source code
[keycloak-custom-provider-feature-v18.0.2-src.zip](https://github.com/keycloak/keycloak/files/9350694/keycloak-custom-provider-feature-v18.0.2-src.zip)

**Comment by lexcao** [comment]
Thanks for your reporting.
It seems duplicated to https://github.com/keycloak/keycloak-ui/issues/3059

**Comment by DGuhr** [comment]
Thanks for reporting, and thanks for providing the correct answer @lexcao. Closing this ticket as duplicate, fixed in https://github.com/keycloak/keycloak-ui/issues/3059
