### ISSUE TITLE
Hidden roles editing a policy

### ISSUE THREAD

**Issue by juanjoi-empathy** [keycloak/keycloak#13801]
### Describe the bug

When trying to edit an existing role policy, the roles already assigned are not visible in the interface.

### Version

19.0.1

### Expected behavior

The list of roles assigned to an existing policy should be listed in the edit view, in order to be able to remove them, or just know that those roles are there.

### Actual behavior

In the edit view of an existing policy, you can not see the previous roles assigned, so If you add another role to the policy, you will save a policy with 2 roles assigned but what you see in the interface when you click on save is just the only role you have added.

### How to Reproduce?

Create a role policy with one role assigned.
Go back to the policies list view.
Edit the previous role policy.
In the edit view, the role assigned won't be shown.

**Comment by lexcao** [comment]
It seems it is an issue related to the new admin UI.
Please clone this issue to https://github.com/keycloak/keycloak-ui

**Comment by juanjoi-empathy** [comment]
Ouch! Sorry.
Cloned.
