### ISSUE TITLE
Can't set storage-deployment-state-version-seed for map storage via environment variable

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#13807]
### Describe the bug

When using the map storage for Quarkus, I can successfully set the CLI option `--storage-deployment-state-version-seed`, then no warning is issued in StoragePropertyMappers. 

Once I try to set it via an environment variable `KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED` this doesn't end in the parameterValue passed to `getResourcesVersionSeed()`: 

https://github.com/keycloak/keycloak/blob/8470a30446cf1a8280353fb96f8e2152d5d186ac/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/StoragePropertyMappers.java#L322-L329

I seems to me that I misunderstood how the configuration mechanism works here. 

I tried to double-check the https://www.keycloak.org/server/all-config page, but it seems to be on 19.0.0 and not 19.0.1 as this option was backported.

### Version

19.0.1-SNAPSHOT

### Expected behavior

The option should be configurable with an environment variable, as this is the way the Keycloak operator passes on information to Keycloak.

### Actual behavior

The warning is logged on the CLI

> Version seed for deployment state set with a random number. Caution: This can lead to unstable operations when serving resources from the cluster without a sticky loadbalancer or when restarting nodes. Set the '--storage-deployment-state-version-seed' option with a secret seed to ensure stable operations.

Surprisingly enough when debugging, the environment option still ends in the provider.

**Comment by ahus1** [comment]
@DGuhr - Maybe you can help me out with this one. The attempt to add a mapper that would show a warning works with the CLI option, but not the environment variable. I seems to me I was using it in a way it wasn't supposed to work. Still I have no idea why this is the case. 

The original idea: The `MapDeploymentStateProviderFactory` is already showing a warning. Still, I was aiming for a warning that is more specific about the CLI options that needs to be provided; CLI options are unknown to the MapDeploymentStateProviderFactory. I could now remove the mapper, and AFAIK it would work -- or is there a better way?

Could you please have a look and comment here? Thanks.

**Comment by DGuhr** [comment]
> @DGuhr - Maybe you can help me out with this one. The attempt to add a mapper that would show a warning works with the CLI option, but not the environment variable. I seems to me I was using it in a way it wasn't supposed to work. Still I have no idea why this is the case.
> 
> The original idea: The `MapDeploymentStateProviderFactory` is already showing a warning. Still, I was aiming for a warning that is more specific about the CLI options that needs to be provided; CLI options are unknown to the MapDeploymentStateProviderFactory. I could now remove the mapper, and AFAIK it would work -- or is there a better way?
> 
> Could you please have a look and comment here? Thanks.

Hm, I also thought transformers would apply to all config sources(as in: conf file, ENV), not just for CLI options. @pedroigor do you know if sth has changed in that regard currently?

**Comment by pedroigor** [comment]
@ahus1 Perhaps I missing something, but setting:

```
KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED=1
```

Works for me and the transformer is invoked.

**Comment by pedroigor** [comment]
But in terms of design, the best I think is to show this kind of message from the provider itself and not from our configuration layer. The reason being the provider the single source of truth for validating its options.

However, we can do that today because providers are not aware of our `config-api` module and the options defined there and providers rely on a different mechanism for exposing its options. See https://github.com/keycloak/keycloak/blob/52d205ca916688b7fc6c77d6a319f584b6b3fd6f/services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java#L232.

I think we have some options on the table to achieve what you want. But I need to think more about them.

**Comment by pedroigor** [comment]
@ahus1 There is also a bug with that message from the property mapper:

```
[pedroigor@fedora bin]$ ./kc.sh build
Updating the configuration and installing your custom providers, if any. Please wait.
2022-08-16 16:25:31,870 WARN  [org.keycloak.quarkus.runtime.configuration.mappers.StoragePropertyMappers] (main) Version seed for deployment state set with a random number. Caution: This can lead to unstable operations when serving resources from the cluster without a sticky loadbalancer or when restarting nodes. Set the '--storage-deployment-state-version-seed' option with a secret seed to ensure stable operations.
2022-08-16 16:25:37,428 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 6084ms
Server configuration updated and persisted. Run the following command to review the configuration:

        kc.sh show-config
```

The message should not be there at all. But only when the `storage` is set.

I would vote for removing that code from the mapper from now and open an issue to discuss a better strategy of showing messages from providers that reference configuration options.

**Comment by ahus1** [comment]
Thanks @pedroigor for having a look. There is now a PR that removes the log message and will default to not-helpful-message 

> Set the 'resourcesVersionSeed' property in the map provider config of deploymentState SPI for stable operations

plus a follow-up issue to improve this with a better design.

**Comment by ahus1** [comment]
As discussed in the cloud native distribution/storage team today, there is now the hard-coded CLI option in the provider's warning message as this is more user friendly and actionable advice for the admin involved.
