### ISSUE TITLE
Why pem format of client key is not supported anymore in 19.0.1?

### ISSUE THREAD

**Issue by kingluo** [keycloak/keycloak#13812]
### Describe the bug

In 18.0.2, the pem format is allowed. Now the latest version, 19.0.1 only reserves jks and pkcs12, why? pem format is so convinent in many cases.

### Version

19.0.1

**Comment by DGuhr** [comment]
Hi @kingluo 

I just tested it using this hacked-together Dockerfile:
```
FROM quay.io/keycloak/keycloak:19.0.1
WORKDIR /opt/keycloak
COPY id.keycloak.test-key.pem /opt/keycloak/conf/
COPY id.keycloak.test.pem /opt/keycloak/conf/
USER root
RUN chmod 644 /opt/keycloak/conf/id.keycloak.test-key.pem
RUN chmod 644 /opt/keycloak/conf/id.keycloak.test.pem
USER 1000
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_HOSTNAME=id.keycloak.test
ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/id.keycloak.test.pem
ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/id.keycloak.test-key.pem
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```
works perfectly given you have the certificates in PEM format. Also works when using the cli commands instead and running on-prem. Please provide more information / steps to reproduce, and re-open the ticket when the bug still persists, as I can not reproduce it. Will close here for now.

**Comment by kingluo** [comment]
@DGuhr No, it's not about the https cert of the web. I mean, in the web console, it does not provide the format option for PEM when I need to import the cert for client key of SAML. Just jks and PKCS12.

**Comment by DGuhr** [comment]
Hi @kingluo 

okay, then I assume you are using the new admin console. There's a new repository for that one, https://github.com/keycloak/keycloak-ui/ - I suggest to reopen the issue there. cc @ssilvert @jonkoops maybe you have more information on this?
