### ISSUE TITLE
Cannot resolve symbol 'UserStorageProviderFactory'

### ISSUE THREAD

**Issue by corinz** [keycloak/keycloak#13822]
### Describe the bug

When trying a basic import, I am receiving this error in IDE and with maven.

```
import org.keycloak.storage.UserStorageProviderFactory;
```
Error: "Cannot resolve symbol 'UserStorageProviderFactory'"

### Version

19

### Expected behavior

The import works.

### Actual behavior

The import fails

### Anything else?

pom.xml
```
    <dependencies>
    <dependency>
        <groupId>org.keycloak</groupId>
        <artifactId>keycloak-core</artifactId>
        <version>${keycloak.version}</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.keycloak</groupId>
        <artifactId>keycloak-server-spi</artifactId>
        <version>${keycloak.version}</version>
        <scope>provided</scope>
    </dependency>
    </dependencies>
```

**Comment by corinz** [comment]
Looks like the new versions deprecated/moved storage class. What is the long term plan here? Any docs?

**Comment by nanachimi** [comment]
Facing the same issue after a migration from version 16 to 19 and I cannot find any documentation on this.

**Comment by quangnguyen** [comment]
Same here

**Comment by hmlnarik** [comment]
This class has been moved to legacy module. Please see https://www.keycloak.org/docs/latest/upgrading/index.html#changes-affecting-developers
