### ISSUE TITLE
HS256 ID Token signed with the wrong key (should use client_secret according to OIDC)

### ISSUE THREAD

**Issue by liweitianux** [keycloak/keycloak#13823]
### Describe the bug

I setup Keycloak (19.0.1) as the OP and was testing HS256 tokens with [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc).  However, it failed the signature verification.

Then I queried the `hmac-generated` secret of my realm and set it as the `symmetric_key` in `lua-resty-openidc`. Additionally, I changed the `lua-resty-openidc` code a bit to use the `symmetric_key`, then the ID token verified OK.

I suspect it was a bug/typo in `lua-resty-openidc`, and I submitted a ["patch" there](https://github.com/zmartzone/lua-resty-openidc/pull/447).

However, I was [pointed out](https://github.com/zmartzone/lua-resty-openidc/pull/447#issuecomment-1216666938) the ID token should be verified with **client secret** as the HMAC key, as described in the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation).

I decoded the header of one ID token (see below), and the `kid` is the ID of the `hmac-generated` secret.  So it seems Keycloak was actually use the `hmac-generated` secret to sign the HS256 ID token, which is wrong and should use the **client secret** instead.

```json
{
  "alg": "HS256",
  "typ": "JWT",
  "kid": "5185d9c0-fca4-47d2-897b-e8e638eb9336"
}
```

### Version

19.0.1

### Expected behavior

Token verifies OK and Keycloak works well with lua-resty-openidc.

### Actual behavior

ID Token failed to verify:

```
2022/08/15 18:10:10 [debug] 10360#10360: *497 [lua] openidc.lua:1029: openidc_load_jwt_and_verify_crypto(): jwt: {"reason":"signature mismatch: lHQw7qMe_2TDD4fw_ZS0k1QXnd9mimeq0rVIsiNRJH0","valid":true,...
```

### How to Reproduce?

1. Deploy Keycloak
2. Create Realm
3. In "Realm settings", change "Default Signature Algorithm" to "HS256" in the "Tokens" tab
4. Create Client
5. Create User
6. Configure the client in lua-resty-openidc (in OpenResty)
7. Access OpenResty, redirect to Keycloak, login, redirect back to OpenResty
8. Fail.

**Comment by liweitianux** [comment]
Found a similar issue from: https://github.com/FusionAuth/fusionauth-issues/issues/57#issuecomment-449072506

<blockquote>

> Regarding the client_secret and id_token validation.

Thank you for the clarification, it looks like you are correct. We are not currently using the client_secret to sign the id_token when you are using HS256, HS384 or HS512 signing algorithm.

https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

> 3.1.3.7. ID Token Validation
>
> If the JWT alg Header Parameter uses a MAC based algorithm such as HS256, HS384, or HS512, the octets of the UTF-8 representation of the client_secret corresponding to the client_id contained in the aud (audience) Claim are used as the key to validate the signature. For MAC based algorithms, the behavior is unspecified if the aud is multi-valued or if an azp value is present that is different than the aud value.

</blockquote>

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

As aside-note, it is suggested to use asymmetric keys for signing ID tokens instead of symmetric keys like HS256, HS384 or HS512
