### ISSUE TITLE
Latest Keycloak container images not published on DockerHub

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#13821]
### Describe the bug

Since Keycloak 18.0.0, the GHA we have to publish our container images is not updating DockerHub. 

See for more details:
- https://hub.docker.com/r/keycloak/keycloak/tags
- https://github.com/keycloak/keycloak/actions/workflows/release-container.yml 

### Version

>= 18.0.0

### Expected behavior

Container images published on DockerHub.

### Actual behavior

No updates since Keycloak 18 release.

**Comment by stianst** [comment]
Working on publishing to Docker in the release now

**Comment by stianst** [comment]
Release process has been updated and we will start publishing to Docker again with Keycloak 20 release.
