### ISSUE TITLE
Front-Channel Logout URL not triggered when logging out from SAML SSO

### ISSUE THREAD

**Issue by tgerakitis** [keycloak/keycloak#13832]
### Describe the bug

I have set up a Keycloak (v19.0.0) realm for my web application with an external SAML IDP.
After successfully logging in, the application uses its own cookies (I can't change this since this is an external piece of software) and has a logout endpoint to destroy those cookies when visited through the browser.

In the corresponding client configuration, I set a front-channel logout URI to be called by the browser whenever a logout is triggered from the IDP.
![image](https://user-images.githubusercontent.com/34158395/185085330-3d998675-8ab8-45b1-9949-b56d0d7f4504.png)

### Version

19.0.0

### Expected behavior

That the Front-Channel Logout URL gets triggered and kills my app cookies

### Actual behavior

No URL is triggered, leaving the app in a logged in state.

### How to Reproduce?

Setup a client with a SAML IDP and then trigger the logout from the SAML IDP.

### Anything else?

Temporary workaround is to manually create a hidden `iframe` element within the client theme `themes/<theme-name>/login/saml-post-form.ftl`
```
<#import "template.ftl" as layout>
<@layout.registrationLayout; section>
    <!-- BELOW LINE -->
    <iframe id="iframe1" src="https://my-app.domain.com/_oauth/logout" style="display:none;"></iframe>
    <!-- ABOVE LINE -->
    <#if section = "header">
        ${msg("saml.post-form.title")}
    <#elseif section = "form">
        <!-- BELOW SCRIPT - to make sure that the logout has finished  before triggering the redirect -->
        <script>
            function readystatechange(event) {
                if (document.readyState=='complete') {
                    document.forms[0].submit();
                }
            }
            document.addEventListener('readystatechange', readystatechange);
        </script>
        <!-- ABOVE SCRIPT -->
        <p>${msg("saml.post-form.message")}</p>
        <form name="saml-post-binding" method="post" action="${samlPost.url}">
            <#if samlPost.SAMLRequest??>
                <input type="hidden" name="SAMLRequest" value="${samlPost.SAMLRequest}"/>
            </#if>
            <#if samlPost.SAMLResponse??>
                <input type="hidden" name="SAMLResponse" value="${samlPost.SAMLResponse}"/>
            </#if>
            <#if samlPost.relayState??>
                <input type="hidden" name="RelayState" value="${samlPost.relayState}"/>
            </#if>

            <noscript>
                <p>${msg("saml.post-form.js-disabled")}</p>
                <input type="submit" value="${msg("doContinue")}"/>
            </noscript>
        </form>
    </#if>
</@layout.registrationLayout>
```

**Comment by ririsoft** [comment]
Hello,

I believe I have the same issue with OIDC.
I have setup front-chanel logout url.
I login on RP side.
I go to the KC admin console in another tab and sign out from there.
The front channel logout url is not called (no logs server side). I can see the "consent screen to logout" flickering very quickly but it disappeared before I can click on anything and I am back to the login screen.

I am using Safari on macOS 12.6, I disabled any extensions and cross sites tracking protection.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment]
Duplicated of https://github.com/keycloak/keycloak/issues/25234.
