### ISSUE TITLE
Declarative user profile does not support multiple-value attributes 

### ISSUE THREAD

**Issue by jkrenzer** [keycloak/keycloak#13844]
### Describe the bug

When activating the user profile in the realm, changing attribute fields with multiple values throws an error.

### Version

19.0.1

### Expected behavior

Attribute fields with multiple values should be processed by the user-profile without error. Either by applying constraints and annotations to each sub-value (no change in current interface needed), by dedicated multi-value handling (would be an enhancement) or by simply passing these fields through (dirty hack).

### Actual behavior

Using the new admin theme (keycloak.v2) you run into keycloak/keycloak-ui#3533. User profile does not issue an error, as the value is reduced to one item of the list.

With the old (keycloak) theme, the list notation with "##" as separator is back and, without user profile activated, can be changed. With user profile, editing the list throws an error and the list changes from "##" to "," as separator. Resubmitting the change throws the same error.

Thus editing multi-valued attribute fields (e.g. mail-aliases from ldap) is not possible with the declarative user profile enabled.

### How to Reproduce?

- Switch user profile on in realm
- Switch to old admin theme in master realm (or problem will be hidden by keycloak/keycloak-ui#3533)
- Create multi-valued attribute (import form ldap federation e.g.)
- Create entry for attribute in user profile
- Try to change value list
- Submit change

### Anything else?

- Keep keycloak/keycloak-ui#3533 in mind as conflicts of multi-value-attributes with the new interface might hide problems or produce new ones
- Consider adding dedicated, explicit multi-value handling

**Comment by pedroigor** [comment]
Should be fixed by https://github.com/keycloak/keycloak-ui/issues/3533.
