### ISSUE TITLE
Resultlist of applications in Accout UI is incomplete

### ISSUE THREAD

**Issue by kitenco** [keycloak/keycloak#13858]
### Describe the bug

When I click on "manage account" or impersonate as a different user,
the list of applications I have rights for is incomplete.

Until now I wasn't able to find out, why some clients are not showing up.

### Version

19.0.1

### Expected behavior

the list of applications is complete

### Actual behavior

the list of applications is incomplete

### How to Reproduce?

create a few clients and give a user a role for all of them
go to impersonate / applications and check if all the clients are listed

**Comment by edewit** [comment]
Looking at the endpoint it takes into account different type of clients: [`/services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java`](https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java#L470)
guess it should be the same no matter what though

**Comment by edewit** [comment]
I just tried it and I had the same as the user I see 2 applications and when I switch to the admin I only see one.

**Comment by kitenco** [comment]
Hi,
is there a chance that this issue will be fixed in the near future?

**Comment by edewit** [comment]
Yes

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.
