### ISSUE TITLE
js adapter just sets error to true upon error updateToken

### ISSUE THREAD

**Issue by RiskManagementGroup** [keycloak/keycloak#13852]
### Describe the bug

If an error occurs while refreshing a token, the error returned is just true, instead of the actual error

The problem is in the updateToken function in https://github.com/keycloak/keycloak/blob/18.0.1/adapters/oidc/js/src/keycloak.js line 661

### Version

18

### Expected behavior

Promise is rejected with the reason true no matter what the cause of the error is

### Actual behavior

That the promise is rejected with an error message that relates to the actual error. Perhaps simply the http code (and perhaps response text) when available

The thing is, that if we had the info, we could for example retry refreshing the token in cases where the server is down or internet connectivity is lost.

**Comment by maximilianfixl** [comment]
Is there any update on this? In version 25, the error (object?) still returns `true`. Since the catch was triggered by an attempt to refresh the token, one would expect, if no error object is present, at least a boolean `false` value.

@stianst, could you clarify what exactly happened during the last milestone when it was "removed from the backlog (this milestone has been deleted)"? Will there be any adjustments, or is this issue being left as is?

Thank you for taking the time to look into this!

**Comment by bitkraft-apathak** [comment]
Hello getting the same error `true`, any update on this ?

**Comment by jonkoops** [comment]
Feel free to submit a PR to implement this feature, this is currently not a high priority item for the team and therefore unlikely to be picked up anytime soon.

**Comment by adropofliquid** [comment]
This is my first time contributing to keycloak and I would like to have a go at this, as it is a good first issue. 

I plan to return an object like below:

p.setError({
    status: req.status,
    statusText: req.statusText,
    responseText: req.responseText
});

If this is excessive, I can just return false

**Comment by jonkoops** [comment]
I think it is excessive to add a bunch of information about the request. Instead, let's throw an error with some descriptive text.

**Comment by jonkoops** [comment]
Assigning this to you @adropofliquid. Let me know if you need any help. I have a little [test application](https://github.com/jonkoops/kjs-playground) I use for Keycloak JS that might be useful for you. You can use `pnpm link path/to/keycloak/js/libs/keycloak-js` to link Keycloak JS for development there.
