### ISSUE TITLE
Remove legacy WildFly distribution

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#13855]
### Description

As we are no longer going to release the WildFly distribution with Keycloak 20 we need to get started on the removal process.

This epic serves as an umbrella issue for all related tasks in this repository, and other repositories.

### Discussion

https://www.keycloak.org/2022/03/releases.html

### Issues

* #13856 
* https://github.com/keycloak/keycloak-web/issues/333
* https://github.com/keycloak/keycloak-documentation/issues/1665
* #14307
* https://github.com/keycloak/keycloak-quickstarts/issues/357
* https://github.com/keycloak/keycloak-quickstarts/issues/356

### Motivation

WildFly distribution is no longer supported with Keycloak 20

**Comment by mabartos** [comment]
This task should be included here as well:
#14307
