### ISSUE TITLE
Old keycloak admin theme missing valid postlogout uris client options

### ISSUE THREAD

**Issue by cghislai** [keycloak/keycloak#13859]
### Describe the bug

I was about to report a failing logout bug, but it is merely a missing option in the old keycloak theme. I leave it below for reference

I use a keycloak v19 image which bundles some providers that register 'partials' template for the old keycloak theme. I couldn't find how to augment the new keycloak.v2 theme, so i disabled the 'adminv2' feature altogether to ensure an usable theme would be loaded by default with this image.

After having noticed the symptoms below, and reproducing them on a bare image, i noticed there was a 'valid postback uris' options in the new theme that is not visible in the old one. It maps to a `post.logout.redirect.uris` attribute of the client representation.

I think this missing option makes the old theme unusable and that this should be fixed.

---
Symptoms:

I recently upgraded to keycloak 19.0.1 in one environement, and noticed that the logout did not work anymore.

I am redirected to `https://<keycloak-host>/realms/<realm>/protocol/openid-connect/logout?post_logout_redirect_uri=<client_uri>&id_token_hint=<undefined | token>`

Keycloak is running behind a reverse proxy in edge mode, i also  tried to enable https and use reencrypt mode with the same result.
The client is configured with its uri (the one passed as the post_logout_redirect_uri value) in the 'redirectUris' (appended with a wildcard).

The error page shows a working 'back to the application' link.
I tried adding various http/https variant of the client_uri in the redirectUris list without success.

If i replace 'post_logout_redirect_uri' by the old 'redirect_uri' param, i get a warning in the logs  `Parameter 'redirect_uri' no longer supported. Please use 'post_logout_redirect_uri' with 'id_token_hint' for this endpoint. Alternatively you can enable backwards compatibility option 'legacy-logout-redirect-uri' of oidc login protocol in the server configuration.`. Im not sure the keycloak client Im using (keycloak-js v19) would allow me to switch back by config.

If I remove the post_logout_redirect_uri param from the url, Im allowed to logout without being redirected. Then the 'back to application link' (which is the exact same uri) can be used to get back to the application.

### Version

19.0.1

### Expected behavior

Im able to set teh valid postback uris using any admin theme

### Actual behavior

Im unable to use an image with the admin2 feature disabled because.

### How to Reproduce?

Start keycloak without the admin2 feature, provision a client using the api without setting the `post.logout.redirect.uris` value, try to understand why the url is not valid.

**Comment by lexcao** [comment]
Hi @cghislai 
Seems duplicated to #14246 which is fixed now.

**Comment by cghislai** [comment]
yes it is. closing now
