### ISSUE TITLE
Run an app through keycloak with Japanese lang 

### ISSUE THREAD

**Issue by EtiNec** [keycloak/keycloak#13862]
### Describe the bug

I'm using keycloak when my browser's default lang is set to Japanese. 
In the login I load a few js files, for example, one of these files is database.min.js, this file contains currency chars, like the EURO sign, and when I load it this sign loads as Japanese char. Therefore, loading failed.
I've tried to set UTF-8 as encoding in setting props, with no success, this file still getting with Japanese chars.

### Version

10 and 19

### Expected behavior

When I set encoding files as UTF-8 I expected to see that all java/js files were loaded as UTF-8

### Actual behavior

Files still loaded with Japanese chars (seems that using default browser lang instead UTF-8)

### How to Reproduce?

use keycloak, open an app that load js files with ocLazyLoads, and see that file on the console it contains Japanese chars

**Comment by stianst** [comment]
I've got absolutely no clue what this issue is about. Could you please try to explain this better?

**Comment by stianst** [comment]
Closing this as I'm not quite following what this is about, and it seems more like an issue in the app rather than Keycloak.
