### ISSUE TITLE
Improve Resources support for HTML Email Themes

### ISSUE THREAD

**Issue by schewara** [keycloak/keycloak#13899]
### Description

Currently there is no convenient and documented way to add resources to HTML E-Mail Themes and it would be
super helpful to provide a Variable for the base URI to the Server.

When trying the snipped, mentioned in the Documentation
```
<img src="${url.resourcesPath}/img/image.jpg">
```
The source in the E-Mail only shows the path and is therefore unable to display the resource.

```html
<img src="/resources/ol8k6/email/mytheme/img/logo.png" alt="Logo"/>
```
After searching for quite some time and trying/guessing a lot of variables to get the URI of the Server,
the only solution that seemed to work, without having to hardcode the address into the template is the following
```
<img src="${link?keep_before("/realms")}${url.resourcesPath}/img/logo.png" alt="Logo"/>
```
To make things easier, it would be very practical to have a variable (e.g. baseUri or something) available to get the full external path to the resources.

### Motivation

The default E-Mails do not have any kind of formatting, which raised red flags for some of our users, as they assumed they where Scam mails.

Trying to get a custom HTML E-Mail with our Company Logo set up was (as a non Developer) rather painful and with some better documentation and a variable which holds the base URL would have made a huge difference to get this task completed in a short amount of time.

**Comment by SergeyZubatkin** [comment]
@schewara
Approach with ${url.resourcesPath}/img/logo.png" is a little bit problematic for all emails if they share same template.ftl.
For example I want to have logo on template.ftl, which is most popular case I guess. 
If we look on FreeMarkerEmailTemplateProvider.java we will see that "url" is not defined in context of sendSmtpTestEmail and sendEvent, so those emails building will fail if "url" is used on template.
Currently we think about putting this url to localization texts and output as msg("companyLogoUrl"), it is better than hardcoding url on theme.properties, value could be easily adjusted from admin console.

**Comment by erikdstock** [comment]
I wound up on this issue after following the recommendations [here](https://stackoverflow.com/questions/65342120/how-we-can-use-image-in-email-template-in-keycloak-locally) - but it wound up that my `properties` is not defined. From the [source code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java#L224) it looks like that should be there, but maybe i'm missing something. my `theme.properties` looks like this in development:
```
locales=en,es
basePath=http://localhost:8080
```

**Comment by SergeyZubatkin** [comment]
In 21.0.2 you could use ${url.resourcesUrl}/img/logo.png and it works for all templates.

**Comment by schewara** [comment]
@SergeyZubatkin Thank you for this input.

I just updated to 21.1.1 and changing it to `${url.resourcesUrl}/img/logo.png` worked like a charm.

I think the only thing preventing this issue from closing, would be a updated [Documentation](https://www.keycloak.org/docs/latest/server_development/#adding-an-image-to-a-theme)?

**Comment by jonkoops** [comment]
Feel free to submit a PR for that :+1:

**Comment by KevinMartinsDevUbi** [comment]
Hello @jonkoops , @schewara  I've just had the problem, I've added your solution to the documentation 😄 

https://github.com/keycloak/keycloak/pull/25705
