### ISSUE TITLE
Session established but no "sign out" option offered leaving session vulnerable under certain sign in error conditions

### ISSUE THREAD

**Issue by rmoqpd5t** [keycloak/keycloak#13905]
### Describe the bug

In cases where a login error condition occurs, for example:
- when first-broker-login requires the update of missing account information (i.e. missing username, email, first name, or last name )
- when roles are missing (e.g. logging into the account portal when missing the manage-account roles)

No "sign out" option is shown in the Keycloak theme leaving the session potentially vulnerable.

For example, if the user was on a shared computer and closed the browser tab then another user would be able to look at the browser history, open the session, access the session, link the account from the account portal, etc.

### Version

19.0.1

### Expected behavior

Whenever a session is established, a "sign out" option should be offered to enable the user to terminate the session

### Actual behavior

Under certain error conditions, no "sign out" option is shown in the Keycloak theme leaving the session vulnerable.

### How to Reproduce?

In a new instance of keycloak, log into an IDP missing mappers for username, email, First name, or Last Name.

The first-broker-login's "Update Account Information" screen appears.

Note that no "Sign Out" button appears on the screen.

Close the browser tab.

Notice that the session exists:
```
# select session_id from event_entity;
              session_id
--------------------------------------
 36f7dcb5-61bc-4909-a780-36dc604ecb20
(1 rows)
```
Also, return to the URL and the page will reload.

### Anything else?

The keycloak theme is a reference implementation so it isn't expected to be comprehensive. However, perhaps 'signout' should be added on error pages where a session is established so that this potential vulnerability can be explained.

**Comment by rmoqpd5t** [comment]
@ssilvert, should this be moved to keycloak-ui ?  Now that I'm aware of keycloak-ui, I think it should be moved.  However, I'm not clear on how to move an issue.

**Comment by mposolda** [comment]
I am adding to Keycloak 23 for now to check if we can/should improve usability around this.

If anyone from the community is able to improve this before, it will be welcome! Please comment here that you want to work on this issue. See "Contributors" section under https://www.keycloak.org/community for more details.

@rmoqpd5t I think that this should not be moved to `keycloak-ui` -it is UXD related, but not related to new admin console or new account console.
