### ISSUE TITLE
User profile attributes doesn't display in admin and account ui

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak#13912]
### Describe the bug

I have activate user profile in order to add some attributes dynamically in account, admin and registration ui.
It works perfectly on the registration page.
But in admin and account ui, attributes are not displayed and generate some error when we try to save if the attribute is mandatory (please specify attribute xxx).
Also we can't create user anymore in admin ui because of mandatory attribute.

### Version

19.0.1

### Actual behavior

![image](https://user-images.githubusercontent.com/16814142/185889828-a032fff7-c426-4416-9ed9-8b8d7e6d0198.png)
![image](https://user-images.githubusercontent.com/16814142/185889929-9bc8432b-2b58-4f1a-95ca-101381b0060a.png)

### How to Reproduce?

Enable User Profile in realm settings
In user profile tab, add some attributes that user and admin can view/edit. (you can do what you want here, the result is the same)
You have two choice here :

- Go to account-console and see that our attributes doesn't appear
- Try to add new account and see that our attributes doesn't appear

### Anything else?

You can access to account ui and try to modify mail to see error
https://pp-rnaconnect.nouvelle-aquitaine.pro/realms/testuserprofile/account/#/personal-info
testuser/testUser!123

**Comment by pedroigor** [comment]
@ssilvert This is related to what we discussed around dynamically rendering user attributes in the user details page. In addition to that, we should also make the same to the account console.

**Comment by ssilvert** [comment]
@pedroigor @Ekouyoja  That's correct.  We will be implementing this as an enhancement soon.

I'm closing this as it will be fixed in the keyclaok-ui repo under https://github.com/keycloak/keycloak-ui/issues/3188
