### ISSUE TITLE
Failed to send email: com.sun.mail.smtp.SMTPSendFailedException: STARTTLS is required to send mail 

### ISSUE THREAD

**Issue by vijaykumarv7** [keycloak/keycloak#13916]
### Describe the bug

Recently upgraded our keycloak app version from 12.0.4 (wildfly) to 18.0.2(quarkus).

 During the Keycloak function testing, Observersed that In realm settings the Email tab when tried to do Test connection to send an email with configured SMTP(outlook) server.  it showing **Error! An unexpected server error has occurred** and when checked the Pod logs it showed the below error post this error. it didn't produce any error at all. Have enabled the STARTTLS SMTP configuration. This has been hosted in Azure Kubernetes Services and has vouched for the firewall logs it doesn't block anything.

**Failed to send email: com.sun.mail.smtp.SMTPSendFailedException:  STARTTLS is required to send mail [DBBPR09CA0030.eurprd09.prod.outlook.com]**

Need urgent support.

### Version

18.0.2

### Expected behavior

SMTP Test Connection function should work

### Actual behavior

**Error! An unexpected server error has occurred** on keycloak UI. 

In pod logs, **Caused by: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [DBBPR09CA0030.eurprd09.prod.outlook.com]**

### How to Reproduce?

1. Spin up the new keycloak (18.0.2) instance version pods and create realm.
2. Under that Realm, navigate to Email where you need to fill your SMTP server info and do a Test connection.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
