### ISSUE TITLE
User Profile: Setting E-Mail to required not working

### ISSUE THREAD

**Issue by dominiwe** [keycloak/keycloak#13923]
### Describe the bug

I have enabled Declarative User Profile as explained here [in the documentation](https://www.keycloak.org/docs/latest/server_admin/#user-profile).

After this, the pre-existing `email` attribute seems to no longer be required, regardless of whether I turn on `Required`.

However, when I declare a new attribute `test` and turn on `Required`, I get asked to provide it when logging in.

### Version

19.0

### Expected behavior

The `email` attribute is required and users have to set this when logging in.

### Actual behavior

The `email` attribute is not required and users do not have to set this (e.g. during login).

### How to Reproduce?

1. Start keycloak with `kc.sh start-dev --features=preview`.

**Comment by pedroigor** [comment]
The `email` and `username` attributes have special handling and they have some hard-coded validations. I agree it is a bit inconsistent though because the UI shows you can actually change some properties of the attributes.

**Comment by dominiwe** [comment]
Thank you for explaining, that makes more sense! :)
My main use case was having users which have only their `username` set complete the information of their profile on first login (including custom attributes), so I was surprised when all of a sudden they no longer had to complete their `email` information after turning on this preview feature.
So for now I have turned off the Declarative User Profile feature again and made `Update Profile` a default action. I'll have to handle the custom attributes later.

I do think it would be best if the *special* attributes like `email` and `username` would be marked in some way in the `User Profile` attributes editor.

**Comment by pedroigor** [comment]
I'll work on it and try to come up with a proposal to allow changing e-mail. The `username` is more complicated to achieve without deep discussions about how it should work.
