### ISSUE TITLE
Requesting Party Token missing User Session Notes in Access Token

### ISSUE THREAD

**Issue by a-m-brewer-datapath** [keycloak/keycloak#13938]
### Describe the bug

After upgrading from version 11.0.3 to 18.0.2 User Session Note mapper values are missing in Requesting Party Token claims. However, they do appear when using the Client Credential flow.

### Version

18.0.2

### Expected behavior

User Session Note mapper values appear in both Client Credential tokens and Requesting Party Tokens.

### Actual behavior

User Session Note mapper values only appear in Client Credential Tokens but not in Requesting Party Tokens.

### How to Reproduce?

1. Create a client that can authorize using the Client Credential Flow.
2. Add a mapping from User Session Notes e.g.

![image](https://user-images.githubusercontent.com/109953425/186170514-2a25f6dd-e9ed-4166-9ddf-20b022efe08f.png)

3. Request an access token using client credentials
4. Use that token to get a Requesting Party Token

The token returned is missing User Session Note mapper values

**Comment by lexcao** [comment]
I found Keycloak is not supporting mapper for `Requesting Party Token` currently.

https://github.com/keycloak/keycloak/blob/cbfe9b9a3d7cd636a69980c3793f475dcc687e90/services/src/main/java/org/keycloak/authorization/protection/introspect/RPTIntrospectionProvider.java#L60-L70

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by rmartinc** [comment]
Hi @a-m-brewer-datapath!

I think your problem is that client credentials / service accounts use now [transient sessions](https://www.keycloak.org/docs/23.0.4/server_admin/#_transient-session) by default (no user session is attached to the request). Please set the option `Use refresh tokens for client credentials grant` in the `advanced` tab of the client to ON. This way the user session will be created as before and the mapper will work OK.

Closing this issue. Please reopen if using normal session doesn't work for you.
