### ISSUE TITLE
Email Test Connection uses wrong email address

### ISSUE THREAD

**Issue by jblachly** [keycloak/keycloak#13931]
### Describe the bug

"Test Connection" from Realm Email settings putatively uses the parameters entered there to send a test email.

Many email providers may limit who an email may be "From", including Amazon SES.

The "test connection" button establishes a connection using the connection parameters in the Realm settings, with the EXCEPTION that it sends the mail from the logged-in administrator's on-file email (if any; otherwise it fails completely), instead of the `From` address entered in the Realm email settings.

This causes the test to fail with rejection. For example, with Amazon SES I receive the following error:

```
2022-08-22 22:18:23,869 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-1) Failed to send email
 com.sun.mail.smtp.SMTPSendFailedException: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-2: <mypersonalemail@domain.com>
```

To be clear, I have configured Keycloak to use a `From` address that _is_ verified. As a final positive control experiment, I changed temporarily my admin user account's email to the verified-with-SMTP-provider email and re-tested the "Test Connection" function; it worked as expected.

### Version

19.0.1

### Expected behavior

I expect the test connection to use the connection parameters, including the `From` address, entered in the Realm Email settings.

### Actual behavior

The test connection uses the logged-in administrator's email address as the `From` address. (As a related bug, it also fails completely if the admin has no email)

**Comment by sriharsha-bhasuru** [comment]
I see the same issue for Forgot password aswell. When as an end-user I click on Forgot Password and enter users email address it tries to use the email of the user but not the email address of From that was given in the email settings

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

**Comment by victorfonseca** [comment]
This is a significant issue. Why is it not possible to prioritize it?
