### ISSUE TITLE
pending admin console for 19.0.1,  when using reverse proxy, https, and port is not 443

### ISSUE THREAD

**Issue by matumot** [keycloak/keycloak#13932]
### Describe the bug

I tried to  use keycloak19.0.1, using reverse proxy (reencrypt), https.

When I used [docker-compose-not-good.yml](https://github.com/keycloak/keycloak/files/9398766/docker-compose-not-good.yml.txt),
with port=8443,
At first, I accessed to Web,  https://myhostname.jp:8443/
Then I accessed Administration Console, Then I found pending with "Loading the admin console"
![pending_for_loading_the_admin_console](https://user-images.githubusercontent.com/4617735/186054452-306e10eb-a889-4b5d-bbf4-c330b9280288.PNG)

But If  I set port=443 with [docker-compose-good.yml](https://github.com/keycloak/keycloak/files/9398767/docker-compose-good.yml.txt),
I found the pending problem for "Loading the admin console" was disappeared!

Is this bug?   For the test, I want to use proxy(reencrypt) , https for port other than 443.
I would appreciate your advice.

regards,

### Version

19.0.1

### Expected behavior

Pending with "Loading the admin console" should not be occured for port=8443.

### Actual behavior

Pending with "Loading the admin console" occured for port=8443.

### How to Reproduce?

Please refere docker-compose files above.

**Comment by matumot** [comment]
In the case of Pending with "Loading the admin console" ,  I captured log and found "no-refferer" message. This may help for solve the problem...
![キャプチャ](https://user-images.githubusercontent.com/4617735/186091823-60e327e6-7c4c-42b4-98fd-a4f6b8b8c489.PNG)

**Comment by xsmart** [comment]
same issue.

**Comment by pedroigor** [comment]
@matumot Did you try setting the `hostname-port=8443` option?

**Comment by matumot** [comment]
> @matumot Did you try setting the hostname-port=8443 option?
Thank you for your comment!  I could solve the problem.
I should read detail the manual here, https://www.keycloak.org/server/hostname

**Comment by matumot** [comment]
Since the problem was fixed, I close the issue, Thank you.
