### ISSUE TITLE
`--optimized` is not supported by `kc.sh export`

### ISSUE THREAD

**Issue by famod** [keycloak/keycloak#13940]
### Describe the bug

I have a realm export script that essentially runs:
```
# note: kc.sh export briefly starts the server including binding a http port, which fails because 8080 is already in use. So we give it a random port instead.
KC_HTTP_PORT=0 kc.sh export --file  ${_EXPORT_FILE_TMP} --users same_file
```

With KC 19.0.1 this logs:
> Changes detected in configuration. Updating the server image.

and then goes on to rebuild, which I don't want and which wasn't there with KC 18.0.2.
I also don't see how the runtime config property `KC_HTTP_PORT` is relevant for rebuilding?

Adding `--optimized` doesn't work:
> Unknown option: '--optimized'

### Version

19.0.1

### Expected behavior

A way to prevent auto-build for `export`.

### Actual behavior

Seemingly no way to prevent auto-build for `export`.

### How to Reproduce?

`kc.sh export --help` -> no `--optimized` (or similar)

**Comment by pedroigor** [comment]
@famod The server should not run a `build` when doing `export` or `import`. The behavior is wrong and we should fix it.

The `http-port` option does not trigger a build though.

**Comment by famod** [comment]
> The `http-port` option does not trigger a build though.

Ok, this was just an assumption from my side. Never triggering a build for export sonds plausible.
Thanks for the quick fix! 👍

**Comment by pedroigor** [comment]
Related https://github.com/keycloak/keycloak/issues/13907.
