### ISSUE TITLE
Custom user storage provider factory settings aren't shown with new admin console

### ISSUE THREAD

**Issue by Shryne** [keycloak/keycloak#13949]
### Describe the bug

I have a class similar to this:

```java
public class MyUserStorageProviderFactory implements UserStorageProviderFactory<MyUserStorageProvider> {
    private static final Logger logger = Logger.getLogger(MyUserStorageProviderFactory.class);
    private static final List<ProviderConfigProperty> configMetadata;

    static {
        configMetadata = Collections.unmodifiableList(
            ProviderConfigurationBuilder.create()
                .property()
                .name("oracle")
                .label("JDBC Driver Class")
                .type(ProviderConfigProperty.STRING_TYPE)
                .defaultValue("org.h2.Driver")
                .helpText("Fully qualified class name of the JDBC driver")
                .add()
                .build()
        );
    }

    @Override
    public List<ProviderConfigProperty> getConfigProperties() {
        logger.warn(
            "getConfigProperties called! " +
                String.join(",", configMetadata.stream().map(it -> it.getName()).collect(Collectors.toList())));

        return configMetadata;
    }

    // ....
}
```
My custom property from `getConfigProperties` isn't shown in Keycloak on the GUI. I can only see the default properties (Console display name and Cache policy).

### Version

19.0.0

### Expected behavior

I should be able to see my defined properties.

### Actual behavior

I don't see the properties.

### Anything else?

The logging on `getConfigProperties` shows this when I enter the page of my custom provider:
> getConfigProperties called! oracle

Which means, Keycloak actually knows that there are custom properties. They just don't appear on the new version.

I tried the same code with:
> --features-disabled=admin2

and it works. Additionally, it also works on version 18.0.0.

**Comment by lexcao** [comment]
Hi, it is an fixed issue duplicated to https://github.com/keycloak/keycloak-ui/issues/3059
