### ISSUE TITLE
Remove Infinispan 12.1.7 workarounds from legacy store and model tests

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13962]
### Description

We introduced the following workarounds to make model tests stable:
- https://github.com/keycloak/keycloak/commit/2b81e62b6b62f7ce6f6e3918bf0a237cc52d9b9a
- https://github.com/keycloak/keycloak/commit/64cbbde7cf255c853ba098f2cf3e899413ff4e0a
- https://github.com/keycloak/keycloak/commit/ebfc24d6c105971f00f86d1c96fc0dc2aed45bf9

We should revert this since now we are using ISPN 13 which should have these problems fixed.

**Comment by ahus1** [comment]
Als investigate if the Cross-DC Infinispan version can up upgraded to the same version as the internal Infinispan version.
Depending on how complicated this is, it might be extracted to its own issue.
