### ISSUE TITLE
Allow for groups to be searched by exact name in addition to searching for all matching names

### ISSUE THREAD

**Issue by Redhat-Alice** [keycloak/keycloak#13973]
### Description

The current behavior when searching for groups by name searches all groups with a LIKE operator on pattern "%search%" 

There is currently no behavior to support getting only groups that exactly match the provided search. 

Given a set of groups ```{ apple, apples, fruit, fruitcakes, orange, blood-orange }```

 it is currently impossible to query for and retrieve only apple, fruit, or orange. The wildcard pattern matching will ensure that a query for "orange" always returns ```{ orange, blood-orange }``` in the result set. 
 
 At scale, if looking for only one specific group name, this becomes a burden to iterate through the result set and pick out only the exact groups you were looking for. 

### Motivation

Better support for finding specific groups by name at scale

### Details

The changes for this should be overall relatively minor. A new named query can be added to `GroupEntity` to support the query itself and surrounding interfaces can be updated to accept a boolean that enables or disables exact match.

**Comment by ssilvert** [comment]
@Redhat-Alice I take it we will need a change in the UI to make this work?  If so, please open an issue for it in the UI repo at https://github.com/keycloak/keycloak-ui/issues
