### ISSUE TITLE
Credential reset mail reports Illegal reflective access

### ISSUE THREAD

**Issue by schewara** [keycloak/keycloak#13972]
### Describe the bug

When Sending a `Reset Actions Email`, the logs produce the following WARNING messages.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.mail.util.SocketFetcher (file:/opt/keycloak/lib/lib/main/com.sun.mail.jakarta.mail-1.6.5.jar) to method sun.security.util.HostnameChecker.getInstance(byte)
WARNING: Please consider reporting this to the maintainers of com.sun.mail.util.SocketFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
As I'm not a Developer, I am unsure if this can also be fixed on Keycloak end, or if it really has to be reported upstream.

### Version

19.0.1

### Expected behavior

no warning messages

### How to Reproduce?

Sending a `Reset Actions Email` from `Users` -> `username` -> `Credentials` -> `Credential Reset`

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by bramklg** [comment]
This seems to be a bug in the jakartaee/mail-api implementation: https://github.com/jakartaee/mail-api/issues/391

**Comment by sschu** [comment]
@schewara Can you please check if the issue still persists in the latest version since Keycloak switched to Java 17 in the meantime?

**Comment by schewara** [comment]
@sschu will do, but it could take a bit as I'm currently flooded with work and don't yet know when I will get around it.

**Comment by schewara** [comment]
@sschu Just upgraded to 2.1.1 and no WARNING messages could be observed. :smile:
