### ISSUE TITLE
no matches for kind "Keycloak" in version "k8s.keycloak.org/v2alpha1"

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#13980]
### Describe the bug

Trying to create a new Keycloak like
https://github.com/keycloak/keycloak/blob/19.0/operator/src/main/resources/example-keycloak.yaml

error:
```console
$ kubectl create -f https://raw.githubusercontent.com/keycloak/keycloak/19.0/operator/src/main/resources/example-keycloak.yaml
error: unable to recognize "https://raw.githubusercontent.com/keycloak/keycloak/19.0/operator/src/main/resources/example-keycloak.yaml": no matches for kind "Keycloak" in version "k8s.keycloak.org/v2alpha1"

```

Kubernetes version `1.22.8`

used CRDs https://github.com/keycloak/keycloak/tree/main/kubernetes

### Version

latest

### Expected behavior

To create the resource

**Comment by vmuzikar** [comment]
@droslean Thanks for the report! Could you please try to apply CRDs from the [`19.0` branch](https://github.com/keycloak/keycloak/tree/19.0/kubernetes) that corresponds with the example you are deploying?

**Comment by droslean** [comment]
@vmuzikar Thanks for the response. I will try to create it from scratch since my team couldn't deploy the new version of keycloak. We are still using the old operator because of this problem.
