### ISSUE TITLE
Investigate usage of objectKey in SingleUseObject area in HotRod and CHM

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#13989]
We have this field in entity: 
https://github.com/keycloak/keycloak/blob/5408d25e096c2f764c855aed6574d9fb4cb40ebf/model/map/src/main/java/org/keycloak/models/map/singleUseObject/MapSingleUseObjectEntity.java#L57-L58

It was introduced because JPA can't store `not-UUID-String` as id. However, this is specific for JPA and in other stores, it seems unnecessary. When id is generated, it is never used, because SingleUseObjects are referenced only using `objectKey` from outside. 

The suggestion is to remove `objectKey` completely and solve the problem with non-UUID-String only in JPA. For example, we can add `objectKey` only in JPA and then translate `read(id)` to use `objectKey` field.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's codebase. Follow #24111 for the removal steps.
