### ISSUE TITLE
Cannot change realm settings in Keycloak 19.0.0

### ISSUE THREAD

**Issue by Oidlichtnwoada** [keycloak/keycloak#14001]
### Describe the bug

Upgraded from jboss keycloak 15 to quarkus keycloak 18 to quarkus keycloak 19 ... 

while toggling User registration the following error pops up in the ui:
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/42490916/186681091-20465cf0-de76-45af-ada2-77c4f2a6eae5.png">

all database migrations were made according to the logs:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/42490916/186680557-5f0f7233-a1ed-46c8-a9fe-5d6952e2480d.png">
the logs in keycloak show this error:

2022-08-25T13:17:22.40315185Z stdout F 2022-08-25 13:17:22,402 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (executor-thread-0) HHH000010: On release of batch it still contained JDBC statements
2022-08-25T13:17:22.402378799Z stdout F 2022-08-25 13:17:22,401 WARN  [io.agroal.pool] (executor-thread-0) Datasource '<default>': JDBC resources leaked: 0 ResultSet(s) and 1 Statement(s)

There is no error in the database happending (postgres is used)

### Version

19.0.0

### Expected behavior

Toggling of realm options is possible

### Actual behavior

error pops up

### How to Reproduce?

do not know ...

### Anything else?

no

**Comment by Oidlichtnwoada** [comment]
@stianst Do you know someone who can help me to fix this issue?

**Comment by hmlnarik** [comment]
Thank you for the report. Sadly, this cannot be reproduced with the latest Keycloak / Quarkus on Postgres.

It seems like there are too many requests coming at the same time. Could the connection to Keycloak / Postgres be slow?

**Comment by Oidlichtnwoada** [comment]
Hi @hmlnarik 
This is definitely not the problem, since both are running as docker containers on the same kubernetes cluster, also the load on out keycloak instance is quite low, only 10 users are using it concurrently, would it be helpful to decrease the logging level to see more messages or do you have another suggestion? I am not familiar with the Keycloak architecture to consult the source code ...

**Comment by Oidlichtnwoada** [comment]
... also why is there a delete statement executed when I try to enable a feature, for example "Forgot password"? ... seems a little bit strange

**Comment by Oidlichtnwoada** [comment]
I have access to our DB, so if you can tell me the exact query that gets executed I can check why there are only 0 rows returned ...

**Comment by Oidlichtnwoada** [comment]
@hmlnarik Could you please help me?

**Comment by Oidlichtnwoada** [comment]
Exporting everything and importing everything into a new database solved the issue ... expected kc to be more stable :(

**Comment by Oidlichtnwoada** [comment]
https://www.keycloak.org/server/importExport

**Comment by tu-pm** [comment]
I'm experiencing the exact same problem on our staging environment, and it can also be resolved by dumping all data into a new database.

> Could the connection to Keycloak / Postgres be slow?

This could be the cause for our environment, since it's known to be not very stable and fast. But can you elaborate more on how it is the cause for the optimistic lock error, @hmlnarik ? I'm not very familiar with JDBC and how Keycloak handle Optimistic Lock in this case, but even when updating realm attributes is a heavy operation, it should not raise this error when there is only one client who sends the request at any given moment.
