### ISSUE TITLE
Upgrade to Quarkus 2.12.0.Final

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#14003]
### Description

Upgrade Quarkus to 2.12.0.Final.

Issues that might be closed after the upgrade:

* https://github.com/keycloak/keycloak/issues/10113
* https://github.com/keycloak/keycloak/issues/11292
* https://github.com/keycloak/keycloak/pull/13740
* https://github.com/keycloak/keycloak/issues/13477
* https://github.com/keycloak/keycloak/issues/13735
* https://github.com/keycloak/keycloak/issues/12610

Issues unblocked by the upgrade:

* https://github.com/keycloak/keycloak/issues/10618

**Comment by trixpan** [comment]
@pedroigor I think this one will also be fixed by the version bump

https://github.com/keycloak/keycloak/issues/13735

**Comment by pedroigor** [comment]
@trixpan Thanks :)
