### ISSUE TITLE
CreatedTimestamp on REST import not used

### ISSUE THREAD

**Issue by heddn** [keycloak/keycloak#14009]
### Description

The CreatedTimestamp (if set on the user rest creation call) is always discarded in favor of `Time.currentTimeMillis()`. This shouldn't be the case for scenarios when someone is REST importing from a legacy system.

### Motivation

Handle graceful import of users from legacy systems.

### Details

From `MapUserProvider`.

![image](https://user-images.githubusercontent.com/1581734/186769589-0638e1a5-0c6e-462e-b6bc-2b6c539ac943.png)

**Comment by efesler** [comment]
In `LegacyExportImportManager.createUser`, the createdTimeStamp is set to the timestamp coming from the legacy repository.

```java
// Import users just to user storage. Don't federate
        UserModel user = UserStoragePrivateUtil.userLocalStorage(session).addUser(newRealm, userRep.getId(), userRep.getUsername(), false, false);
        user.setEnabled(userRep.isEnabled() != null && userRep.isEnabled());
        user.setCreatedTimestamp(userRep.getCreatedTimestamp());
```

Is the issue still relevant ?

**Comment by heddn** [comment]
I'm dusting off the user migration again and will confirm.

**Comment by heddn** [comment]
No, the provided value from the REST import is not used. It still uses the time of import instead of the value provided in the import.

**Comment by heddn** [comment]
I'm looking at `org.keycloak.services.resources.admin.UsersResource::createUser`, and there is nothing to set the create timestamp.

**Comment by heddn** [comment]
Just pushed up a PR that should at least start the conversation here.
