### ISSUE TITLE
User/User Profile API inconsistent behaviour : partial PUT clear all user fields when user profile enabled

### ISSUE THREAD

**Issue by daviddelannoy** [keycloak/keycloak#14035]
### Describe the bug

When the user declarative profile feature is enabled, Admin REST API endpoint `PUT` on `/users` behavior is different from when user profile is disabled

# Context 

Updating a user field which is not part of user declarative profile (like Required Actions or user enabled) leads to clear any other user attribute.

### Version

19.0.1

### Expected behavior

With **User declarative profile enabled**, a `PUT` on `/users` should act as `PATCH`, just like when the feature is disabled if behavior must be consistent. 

Or it should be at least documented with a **warning** in REST Admin API Documentation that PUT /users with User declarative profile activated is a PUT and without user profile a PATCH

### Actual behavior

With **User declarative profile enabled**, a `PUT` on `/users` acts like a PUT and delete any missing field on user in the payload
With **User declarative profile disabled**, a `PUT` on `/users` acts like a PATCH and allows partial updates on an user

### How to Reproduce?

1. **First test OK** 
**Realm Settings :** 
Email as username enabled
Login with email enabled
User Profile **disabled**
User Registration enabled

Register a new user : 

![image](https://user-images.githubusercontent.com/16318239/186872768-c3369f4d-915a-4f65-a2b4-354ddb212daf.png) 

Then try to **partially update by API** one of this user native attributes (first name, last name, required actions ...) : 

`curl -s -X PUT "http://localhost:8080/admin/realms/master/users/694a81a6-a55e-4cd7-91a6-71292e9afb09" 
--header 'Content-Type: application/json' 
--header "Authorization: Bearer $access_token" 
--data '{ "firstName":"newFirstNameUserProfileDisabled" }'`

It works perfectly fine, `/users` endpoint acts as a PATCH and only updated firstName in this case : 

![image](https://user-images.githubusercontent.com/16318239/186873915-322c28c6-ec31-4256-8797-de5668263cdf.png)

2. **Second test KO** 
**Settings :** 
Email as username enabled
Login with email enabled
User Profile **enabled**
User Registration enabled

Reproduce exactly the same test as before after switching on User Profile feature, without any configuration in User profile : 
![image](https://user-images.githubusercontent.com/16318239/186874653-73dec6a7-1035-42cb-9e9d-01887e9524d8.png)

After using `PUT` on any `UserRepresentation` field which is not part of user profile, all other fields are cleared, like in a usual PUT. Even username because email as username is enabled in this example, so account is broken and cannot be displayed anymore.

![image](https://user-images.githubusercontent.com/16318239/186874998-bfb4e534-4987-4ef1-90df-361e7e740665.png)

Of course API works as expected by using PUT as a PUT and sending whole resource Representation in payload.

### Anything else?

This issue completes this issue [[Do not empty attributes if they are not provided when user profile is enabled](https://github.com/keycloak/keycloak/issues/11096#top)
#11096](https://github.com/keycloak/keycloak/issues/11096) which is more specific about the user attribute tab

The API behavior which acts as a classic PUT when User profile enabled **is wider than previous issue** : for example required actions field is not a user attribute, it has nothing to do with user profile and when trying to clear required action by sending a payload `{ "requiredActions":[] }`
Same for `User enabled` field.

**Comment by daviddelannoy** [comment]
Hi @Pepo48 
Do you have any new on this issue ? I did not try on KC 19.0.2 (and new coming 20.x) ... 
thanks !

**Comment by ynfle** [comment]
This is a massive blocker for us. Are there any plans to look in to this?

**Comment by sschu** [comment]
@ynfle I agree the semantics is not great, but why is this a blocker for you? You can still first read all current attributes before writing the updated values back?

**Comment by pedroigor** [comment]
@ynfle We had some improvements in this area. Could you evaluate the latest version?

The `PATCH` operation is still not possible but you should not have issues like invalidating an account because you did not provide the username.
