### ISSUE TITLE
Custom provider is not showing up in mapper

### ISSUE THREAD

**Issue by aymns** [keycloak/keycloak#14031]
### Describe the bug

I'm trying to extend Keycloak claims with custom implementation.

I forked my codebase from this project:
https://github.com/dasniko/keycloak-extensions-demo

You can find my code base below in the How to Reproduce section.

### Version

19.0.1

### Expected behavior

Get custom provider in the list of Client Scope - Mappers.

### Actual behavior

Customer provider is not being added to the Client Scope - Mappers.

### How to Reproduce?

1. I added the simple below implementation of `OIDCAAccessTokenMapper`

```


public class TesterClaimMapper extends AbstractOIDCProtocolMapper implements OIDCAccessTokenMapper {

    private static final List<ProviderConfigProperty> configProperties = new ArrayList<ProviderConfigProperty>();


    public static final String PROVIDER_ID = "oidc-test-claim-mapper";


    public List<ProviderConfigProperty> getConfigProperties() {
        return configProperties;
    }

    @Override
    public String getId() {
        return PROVIDER_ID;
    }

    @Override
    public String getDisplayType() {
        return "Custom test claim mapper";
    }

    @Override
    public String getDisplayCategory() {
        return TOKEN_MAPPER_CATEGORY;
    }

    @Override
    public String getHelpText() {
        return "test resource custom mapper";
    }

    @Override
    public int getPriority() {
        return 99999999;
    }

    @Override
    public AccessToken transformAccessToken(AccessToken token, ProtocolMapperModel mappingModel, KeycloakSession session,
                                            UserSessionModel userSession, ClientSessionContext clientSessionCtx) {
        token.getOtherClaims().put("custom claim", "value");
        return token;
    }

    public static ProtocolMapperModel createClaimMapper(String name) {
        ProtocolMapperModel mapper = new ProtocolMapperModel();
        mapper.setName(name);
        mapper.setProtocolMapper(PROVIDER_ID);
        mapper.setConfig(Collections.emptyMap());
        return mapper;
    }
}
```
2. Build and pack the project using `mvn clean package`
3. Copy the output JAR file to **providers** folder.
4. Run `bin/kc.sh build`
5. I get the following response: 
```
Updating the configuration and installing your custom providers, if any. Please wait.
2022-08-26 07:42:54,516 WARN  [org.keycloak.services] (build-27) KC-SERVICES0047: oidc-test-custom-claim-mapper (dasniko.keycloak.tokenmapper.TesterClaimMapper) is implementing the internal SPI protocol-mapper. This SPI is internal and may change without notice
2022-08-26 07:42:59,297 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 8248ms
```
6. I create new `client scope` and couldn't find the `TesterClaimMapper` there.

**Comment by akbar1214** [comment]
@aymns have you added the mapper in  META-INF/services? Seems like you have not performed that step.

**Comment by aymns** [comment]
Yes, The META-INF/Services is included in the project.
I've even tried to deploy the jar package for https://github.com/dasniko/keycloak-extensions-demo/tree/main/tokenmapper

For some reason it was successful to add the provider to Keycloak v.18 but not v.19.

**Comment by aymns** [comment]
My bad! I just needed to restart the docker container.
