### ISSUE TITLE
InResponseTo not included in ACS response

### ISSUE THREAD

**Issue by Mailstorm-ctrl** [keycloak/keycloak#14055]
### Describe the bug

When using SAML authentication, Keycloak will not provide a InReponseTo in ACS responses.

### Version

V19

### Expected behavior

I expect to see InResponseTo in an ACS response.

### Actual behavior

InResponseTo is not included in ACS reponses.

### How to Reproduce?

This can be reproduced with [Bookstack](https://www.bookstackapp.com/).

Setup bookstack according to their guide ro use the [Ubuntu script](https://www.bookstackapp.com/docs/admin/installation/#ubuntu-2004).

Follow [this guide](https://www.bookstackapp.com/docs/admin/saml2-auth/) to implement SAML2 Auth or just copy the following into `/var/www/bookstack/.env` (Update with your values)

```
APP_DEBUG=true
AUTH_METHOD=saml2
AUTH_AUTO_INITIATE=true
SAML2_NAME="Login in Keycloak"
SAML2_EMAIL_ATTRIBUTE=email
SAML2_EXTERNAL_ID_ATTRIBUTE=ID
SAML2_DISPLAY_NAME_ATTRIBUTES=firstName|lastName
SAML2_IDP_ENTITYID=http://example.org:8080/realms/example/protocol/saml/descriptor
SAML2_AUTOLOAD_METADATA=false
SAML2_IDP_SSO=http://example.org:8080/realms/example/protocol/saml/clients/bookstack
SAML2_IDP_x509=<cert from keycloak>
SAML2_IDP_AUTHNCONTEXT=false
```

Then in keycloak, make a new client that uses SAML.
```
Client ID= Whatever
Valid redirect URIs= http://<bookstack instance>
IDP-Initiated SSO URL name= bookstack
Name ID format= email
Assertion Consumer Service POST Binding URL = http://<bookstack instance>/saml2/acs
```

When you go to your bookstack instance and try to login, you will get the following error:
```
No InResponseTo at the Response, but it was provided the requestId related to the AuthNRequest sent by the SP
Invalid ACS Response: invalid_response
```

**Comment by F1Feng** [comment]
How about this issue? I also got the same error message

**Comment by mpuggelli-gucci** [comment]
any news on this?

**Comment by aybhalala** [comment]
Same issue in V20.0.3

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

**Comment by kekeskuya** [comment]
Any update with this issue ?, I got same issue

**Comment by haraldhaas** [comment]
This is preventing us from using Keycloak with JIRA, because JIRA always reports:
`{"key":"badRequest","context":{"message":"Invalid customer saml login callback request","reason":"No In Response To in SAML Response"}}`

**Comment by tosts** [comment]
update!
