### ISSUE TITLE
[keycloak 17 migrate to 19] users import failed

### ISSUE THREAD

**Issue by manbobo2002** [keycloak/keycloak#14065]
### Describe the bug

Not sure why, only users cannot import, but for others seem working fine

### Version

19.0.1

### Anything else?

![image](https://user-images.githubusercontent.com/25196415/187175071-e196f9b6-28f8-4383-8051-45e815d6246e.png)

**Comment by vmuzikar** [comment]
@manbobo2002 Thanks for the report. Can you please provide us with detailed steps to reproduce?

**Comment by manbobo2002** [comment]
@vmuzikar go to keycloak 17 container and export the json
```
bash-4.4$ /opt/keycloak/bin/kc.sh export --file /opt/keycloak/exported.json 
```

Then go to keycloak 19 UI and add realm, it fails
Then go to partial import, only users cannot be imported

**Comment by stianst** [comment]
Closing due to clear steps on how to re-produce and the issue is rather old
