### ISSUE TITLE
A performance cross DC test for CockroachDB

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#14069]
### Description

Deploy and test Keycloak in multi-site CockroachDB deployment.

This is a task to develop multi-site support with CRDB in keycloak-benchmark (deploying multiple CRDB nodes in separate "sites", ensuring they communicate correctly).

It should be possible to run the sites in separate machines, but initially it suffices to have sites represented as separate namespaces in the same K8s environment ran in the same box.

Running any keycloak-benchmark test will do to illustrate that it is possible to run more .

**Comment by hmlnarik** [comment]
Done as part of https://github.com/keycloak/keycloak-benchmark/issues/202

**Comment by PavelVlha** [comment]
[From Grooming] Issue dependent on https://github.com/keycloak/keycloak-benchmark/issues/202 (Already done)

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
