### ISSUE TITLE
Refused to frame ' ... ' beucause it violates Content Security Policy directive: "frame-src 'self'".

### ISSUE THREAD

**Issue by EPanni** [keycloak/keycloak#14078]
### Describe the bug

I am not able to open the admin console and the following error shows up in the console.

Refused to frame ' ... ' because it violates the following Content Security Policy directive: "frame-src 'self'".

### Version

18.0.2 but the same happens with the latests

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by jonkoops** [comment]
Closing this in favor of resolving this under #16277.
