### ISSUE TITLE
Identity Provider Settings:  Sync mode hidden behind panel

### ISSUE THREAD

**Issue by toarm** [keycloak/keycloak#14096]
### Describe the bug

The "Sync mode" can normally be configured on the Identity Provider page.
But with the new UI no Sync mode is visible on the Identity Provider settings page:

![image](https://user-images.githubusercontent.com/4092852/187469669-1f495d0e-0750-4494-9ab8-7963e58182f9.png)

I figured out that the setting is overlayed by the "Save/Revert" bottom bar. Adding manually some padding via the browser dev tools works. See Expected behavior.

### Version

19.0.1

### Expected behavior

See the "Sync mode" setting

![image](https://user-images.githubusercontent.com/4092852/187470064-01b5b563-b513-4450-9503-65a8c2487572.png)

![image](https://user-images.githubusercontent.com/4092852/187469286-c3a76beb-35ff-4d48-96be-01fb3a2c7ef3.png)

### Actual behavior

The Sync mode is not visible to the user.

![image](https://user-images.githubusercontent.com/4092852/187469669-1f495d0e-0750-4494-9ab8-7963e58182f9.png)

### How to Reproduce?

Create an Identity Provider and save it. 
Go to settings page.

**Comment by ssilvert** [comment]
Hi @toarm.  This one is fixed.   See https://github.com/keycloak/keycloak-ui/issues/3196
