### ISSUE TITLE
When firewalld is enabled, the cluster cannot be formed using `--cache stack=tcp` 

### ISSUE THREAD

**Issue by JokerDevops** [keycloak/keycloak#14100]
### Describe the bug

adopt https://www.keycloak.org/server/caching This document shows that `cache stack` supports multiple methods. When I used TCP, it still used 'mping (uses UDP multicast)` Discovery mechanism. This causes my friedwald not to know which port should be allowed to be accessed.

### Version

19.0.1

### Expected behavior

How to open firewall rules here?

### Actual behavior

When I turn off firewalld, it is normal

### How to Reproduce?

cache configfile use default

**Comment by pedroigor** [comment]
I hope this link can help you https://www.redhat.com/sysadmin/secure-linux-network-firewall-cmd.

Note that you can also customize the stack by changing the `cache-ispn.xml` file. See https://infinispan.org/docs/dev/titles/embedding/embedding.html#customizing-jgroups-stacks_cluster-transport.
