### ISSUE TITLE
Valid Redirect URLs: Allow wildcard in hostname

### ISSUE THREAD

**Issue by silviokennecke** [keycloak/keycloak#14113]
### Description

We have a lot of projects, all serving under the same domain *.staging.my-domain.com. Right now, we have to allow all Domains explicitly. This is very annoying. It would help a lot if we could use wildcards, also in the hostname of the valid redirect URLs and not only in the path. In most use-cases it would already help if the wildcard can be at the leftmost part of the hostname (like required in DNS).

### Discussion

Old ticket: https://issues.redhat.com/browse/KEYCLOAK-14071

Related discussions:
* https://github.com/keycloak/keycloak/discussions/9278
* https://github.com/keycloak/keycloak/discussions/12376

### Details

From what it looks like, the relevant implementation affects: [org.keycloak.protocol.oidc.utils.RedirectUtils#matchesRedirects](https://github.com/keycloak/keycloak/blob/ee2c5391bd9d2cfaafb0ddede4c32246de56f7e1/services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java#L178)

First prototyped implementation:
```java
public class RedirectUtils {
    private static boolean matchesRedirects(Set<String> validRedirects, String redirect) {
        for (String validRedirect : validRedirects) {
            // check wildcard hostname + replace hostname
            if (!validRedirect.startsWith("/")) {
                int vrHostnamePosStart = validRedirect.indexOf("//") + 2;
                String vrScheme = validRedirect.substring(0, vrHostnamePosStart);
                String vrHostname = validRedirect.substring(vrHostnamePosStart);
                
                int vrHostnamePosEnd = vrHostname.indexOf("/");
                String vrPath = vrHostname.substring(vrHostnamePosEnd);
                vrHostname = vrHostname.substring(0, vrHostnamePosEnd);
                
                if (vrHostname.contains("*")) {
                    int vrWildcardPos = vrHostname.indexOf("*");
                    String vrHostnameStart = vrHostname.substring(0, vrWildcardPos);
                    String vrHostnameEnd = vrHostname.substring(vrWildcardPos + 1);
                    
                    int rHostnamePos = redirect.indexOf("//") + 2;
                    String rHostname = redirect.substring(rHostnamePos);
                    
                    int rHostnamePosEnd = rHostname.indexOf("/");
                    rHostname = rHostname.substring(0, rHostnamePosEnd);
                    
                    if (rHostname.startsWith(vrHostnameStart) && rHostname.endsWith(vrHostnameEnd)) {
                        validRedirect = vrScheme + rHostname + vrPath;
                    } else {
                        continue;
                    }
                }
            }
            
            if (validRedirect.endsWith("*") && !validRedirect.contains("?")) {
                // strip off the query component - we don't check them when wildcards are effective
                String r = redirect.contains("?") ? redirect.substring(0, redirect.indexOf("?")) : redirect;
                // strip off *
                int length = validRedirect.length() - 1;
                validRedirect = validRedirect.substring(0, length);
                if (r.startsWith(validRedirect)) return true;
                // strip off trailing '/'
                if (length - 1 > 0 && validRedirect.charAt(length - 1) == '/') length--;
                validRedirect = validRedirect.substring(0, length);
                if (validRedirect.equals(r)) return true;
            } else if (validRedirect.equals(redirect)) return true;
        }
        return false;
    }
}
```

**Comment by stianst** [comment]
Putting this on hold while we keep the discussion going in https://github.com/keycloak/keycloak/discussions/9278

**Comment by subinamathew** [comment]
Please take this into consideration

**Comment by Nefcanto** [comment]
Yeah, we want this too. We use Keycloak for our development. We host one instance of it locally on `https://accounts.company.local` and we want all of our projects to use this instance.

Right now we have to manually add each project's redirect URI and web origin manually in the client. We have to repeat that for each project. This is very annoying.

**Comment by sephentos** [comment]
Any updates here?

**Comment by Nefcanto** [comment]
@sephentos, we used `*` for valid redirect URLs and valid web origins and it worked.

**Comment by sschu** [comment]
@Nefcanto So you are creating an open redirect vulnerability: https://cwe.mitre.org/data/definitions/601.html

**Comment by Nefcanto** [comment]
@sschu we only do it in our development environment. Of course, we don't do it in production. Thank you for mentioning that.

@sephentos just put `*` there instead of `https://*.domain.tld/`

**Comment by Nefcanto** [comment]
@sschu we only do it in our development environment. Of course, we don't do it in production. Thank you for mentioning that.

@sephentos just put `*` there instead of `https://*.domain.tld/`

**Comment by sephentos** [comment]
> @sschu we only do it in our development environment. Of course, we don't do it in production. Thank you for mentioning that.
> 
> @sephentos just put `*` there instead of `https://*.domain.tld/`

This would allow every domain to be valid instead of every subdomain belonging to a subdomain which is not intended from OP and me

**Comment by TzahiFadida** [comment]
> @Nefcanto So you are creating an open redirect vulnerability: https://cwe.mitre.org/data/definitions/601.html

Just to be clear, I think the above fix could be good (perhaps a bit of modification is required, but) because https://*.domain.com/.. cannot suffer from this specific vulnerability if this is a wildcard domain. e.g. the site is used for multi-tenant purposes. This is the application for the site and therefor a malicious party cannot redirect to another domain. Not to mention if this is confidential, then they don't have your client_secret which will not allow redirect without it.

**Comment by mposolda** [comment]
I am closing as this was already addressed by https://github.com/keycloak/keycloak/issues/25637 and should be available in Keycloak 24.
