### ISSUE TITLE
Cannot create  /update or get users realmRoles with java admin client

### ISSUE THREAD

**Issue by MichaelKoch11** [keycloak/keycloak#14116]
### Describe the bug

I want to create /update / get an users over the Java  Keycloak-admin-client,
User generation and fetch work except the Realm Roles cannot directly set or see..

1. When creating a user over client no Realm Roles are set in Keycloak.

2. When I set some Roles manually I have the Failure
this.userResource.get(getKeycloakId()).toRepresentation().getRealmRoles() is always be null.

### Version

18.0.0 and org.keycloak:keycloak-admin-client:18.0.0 /19.0.1 (testet both versions)

### Expected behavior

1. Create /update user
- Want to set and change realm Roles for one User.
- Set userRepresentation.setRealmRoles as an list of role names existing in Keycloak .
- create user
- get user by username/ id from response
- read user roles
2. Get User
- get user by keycloak id
- realm roles shoud by assigned roles

### Actual behavior

realmRoles in UserRepresentation is always be null

### How to Reproduce?

Simple Setup

Connect

``` java
	public KeycloakServiceManager(Environment env) {
		this.kc = KeycloakBuilder.builder()
				.serverUrl(env.getProperty("keycloak.client.url"))
				.grantType(OAuth2Constants.CLIENT_CREDENTIALS)
				.realm(env.getProperty("keycloak.client.realm"))
				.clientId(env.getProperty("keycloak.client.id"))
				.clientSecret(env.getProperty("keycloak.client.secret"))
				.build();
		this.realmResource = this.kc.realm(env.getProperty("keycloak.client.realm"));
		this.userResource = this.realmResource.users();
	}
```
Test User Generation
Realm Role globalAdmin exists in Keycloak
``` java
var userRepresentation1 = new UserRepresentation();
		userRepresentation1.setEnabled(true);
		userRepresentation1.setFirstName("Dum");
		userRepresentation1.setLastName("Dummy");
		userRepresentation1.setEmail("dummy@dummy.com");
		userRepresentation1.setUsername(userRepresentation1.getEmail());
		userRepresentation1.setRealmRoles(List.of("globalAdmin"));
		
		if (!this.userResource.search(userRepresentation1.getUsername()).isEmpty()) {
			this.userResource.delete(this.userResource.search(userRepresentation1.getUsername()).get(0).getId());
		}
		
		this.userResource.create(userRepresentation1);
		userRepresentation1 = this.userResource.search(userRepresentation1.getUsername()).get(0);
		
		CredentialRepresentation credential = new CredentialRepresentation();
		credential.setType(CredentialRepresentation.PASSWORD);
		credential.setValue(env.getProperty("keycloak.local.user.password"));
		credential.setTemporary(false);
		this.userResource.get(userRepresentation1.getId()).resetPassword(credential);
		
		var userRepresentation = this.userResource.search(userRepresentation1.getUsername()).get(0);
```

Client is generated with service accounts enabled and Service Account Roles->Client roles (realm management ) ->all

The next test was to fetch user with
userResource.get(getKeycloakId()).toRepresentation()
where the role list is null

Here are some pictures of my keycloak config.

![serviceroles](https://user-images.githubusercontent.com/100569058/187667431-701ef2d2-45bd-46f4-9c23-2f110bf72d20.png)
<img width="1571" alt="realmroles" src="https://user-images.githubusercontent.com/100569058/187667435-b35b7ea7-571c-4f2c-a6c6-2924ad8c1a55.PNG">
<img width="1150" alt="client" src="https://user-images.githubusercontent.com/100569058/187667436-e6340ec9-bf66-49be-bf80-1c2092833951.PNG">

### Anything else?

Some workarround if found
https://keycloak.discourse.group/t/realm-role-is-not-assigned-while-creating-user/2271
https://stackoverflow.com/questions/65292454/keycloak-can-not-read-users-realm-roles-as-admin-cli-when-calling-the-admin-res
https://stackoverflow.com/questions/69103060/keycloak-add-client-roles-to-service-account-roles-with-java-api-client
Want it work directly

**Comment by pedroigor** [comment]
Roles are never available from the API when returning the user representation. It is mainly targeted when exporting users and their role mappings.
