### ISSUE TITLE
Cannot save X509 config step in flow

### ISSUE THREAD

**Issue by andreibleortu** [keycloak/keycloak#14139]
### Describe the bug

Before I begin: I'm a novice here, I apologize if I miss anything.

Hi! I have a Keycloak deployment running under Ubuntu Server 22.04.1 LTS, in production mode. I have one realm aside from _Master_, which we'll call A***. I've masked its name for my privacy. I have an Active Directory deployment as an ID provider set up.

When I try to save a _X509/Validate Username config_ step in an inactive flow in my Keycloak deployment, I get a _Could not save the execution config: unknown_error_ message. My flow contains a _Cookie_ step and a _WebAuthn Passwordless Authenticator_ step. I have attached screenshots of the flow config below.  I have chosen to mask the OCSP provider's URL within these screenshots for privacy reasons.

<img width="1800" alt="Screenshot 2022-09-01 at 1 45 59 PM" src="https://user-images.githubusercontent.com/46914650/187898731-6eee2a3e-da35-4987-8d57-b00b1a847297.png">
<img width="1800" alt="Screenshot 2022-09-01 at 1 46 11 PM" src="https://user-images.githubusercontent.com/46914650/187898724-ba140715-9e79-4454-9ddb-148f14daf2cf.png">

### Version

19.0.1

### Expected behavior

I would have expected the flow step to save successfully and for it to be usable in my flow.

### Actual behavior

When I try to save a _X509/Validate Username config_ step in an inactive flow in my Keycloak deployment, I get a _Could not save the execution config: unknown_error_ message. I've also attached a log of what `kc.sh start` outputs when running and the error itself within the UI. I have chosen to mask Keycloak's actual domain on the first line for privacy reasons.

<img width="632" alt="Screenshot 2022-09-01 at 2 00 09 PM" src="https://user-images.githubusercontent.com/46914650/187898739-cf284a38-7fa1-402f-97c7-c84a44bfc110.png">

[log.txt](https://github.com/keycloak/keycloak/files/9469265/log.txt)

The error starts at:

> 2022-09-01 10:37:55,063 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 46] (through reference chain: org.keycloak.representations.idm.AuthenticatorConfigRepresentation["config"]->java.util.LinkedHashMap["x509-cert-auth"])

### How to Reproduce?

I think you can try adding a _X509/Validate Username config_ step in any flow. The issue appears to occur regardless of the step's configuration parameters.

**Comment by lexcao** [comment]
Hi, @andreibleortu 
It is a fixed issue duplicated to https://github.com/keycloak/keycloak-ui/issues/3022
