### ISSUE TITLE
Refused to apply style from... because its MIME type ('') is not a supported stylesheet MIME type - 

### ISSUE THREAD

**Issue by TitanRob16** [keycloak/keycloak#14138]
### Describe the bug

The main page of my Keycloak instance hosted in Google's Kubernetes Engine isn't loading as expected; I believe this to be an issue with the image used. 

I've tried both:
_marketplace.gcr.io/google/keycloak:18.0_
and:
_quay.io/keycloak/keycloak:18.0.0_

In the Chrome Developer Console, I see 5 errors like:

`Refused to apply style from 'https://keycloak-test.company.co.uk/resources/fx0e8/common/keycloak/node_modules/patternfly/dist/css/patternfly.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

I'm also getting 404 errors for 'patternfly-additions.css' and patternfly.css:

https://keycloak-test.company.co.uk/resources/fx0e8/common/keycloak/node_modules/patternfly/dist/css/patternfly.css
https://keycloak-test.company.co.uk/resources/fx0e8/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.css

There are then further issues when I browse to _keycloak-test.company.co.uk/admin/master/console_; quite a few files are giving me a 404 error message, e.g.:

`GET https://keycloak-test.company.co.uk/resources/fx0e8/common/keycloak/node_modules/jquery/dist/jquery.min.js net::ERR_ABORTED 404`

```
Uncaught ReferenceError: angular is not defined
    at angular.treeview.js:95:5
(anonymous) @ angular.treeview.js:95
```

`Uncaught TypeError: Cannot read properties of undefined (reading 'controller')
    at clients.js:7:8`

I'm not sure what's going on here; our deployment pipeline hasn't changed, so this should just deploy a working Keycloak instance as expected; we've never needed to modify or change any .js or .css files. 
Where should these files be located on the pod? 

Any help with this would be greatly appreciated!

### Version

18.0

### Expected behavior

We should be able to deploy a working instance of Keycloak from the Google marketplace without any issue regarding .js or .css files. 

### Actual behavior

As described in the above ticket: we can't load the /admin/master/console page due to the 404 and .js, .css error messages.

### How to Reproduce?

Deploy either _marketplace.gcr.io/google/keycloak:18.0_ or _quay.io/keycloak/keycloak:18.0.0_ into GKE with an Ingress and certificate for keycloak-test.company.co.uk.

**Comment by lexcao** [comment]
If Keycloak is deployed behind a proxy, there should be a config for `proxy`.
Could you please refer to this doc https://www.keycloak.org/server/reverseproxy?

**Comment by stianst** [comment]
I'd suggest trying to configure the proxy settings and see if that works. GCP load balancer is basically a smart reverse proxy, so those configurations apply for your case.

**Comment by jmax01** [comment]
We have the same issue.

**Comment by jonkoops** [comment]
Commenting on an issue that it still happens will not get it fixed. If you have a way to reproduce an issue feel free to submit a new issue with minimal steps to reproduce it.
