### ISSUE TITLE
[keycloak 18] cannot import users with correct ID in partial import

### ISSUE THREAD

**Issue by manbobo2002** [keycloak/keycloak#14134]
### Describe the bug

old user:
![image](https://user-images.githubusercontent.com/25196415/187867492-e0f212f5-b03e-4e58-939d-2bc330a9253e.png)

migrated user:
![image](https://user-images.githubusercontent.com/25196415/187867563-5b48e2ba-8003-4b0c-96ab-7d9ef5a4b198.png)

I also try to import through cli, but it seems if I am running it cannot do so.

and I try to import the whole realm as well, but I am not sure may be the file is too large, but if I seperate the files during import it works, then I need to import users afterwards. Here is the related issue: https://github.com/keycloak/keycloak/issues/14065

### Version

18

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now.

**Comment by antikalk** [comment]
> This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now. If anyone is willing to send PR for this, it is welcome as not sure when Keycloak team will have time to look into this. Also it may be "automagically" fixed once Keycloak will start to use new store.

@mposolda I am not sure it will. The user id is already overwritten in the partial import class and not on store level (like e.g. it is done with groups). See [UsersPartialImport](https://github.com/keycloak/keycloak/blob/1049ad8edf703180edb39b79e6477666d9f9245c/services/src/main/java/org/keycloak/partialimport/UsersPartialImport.java#L113). I created a pull request where the id is only generated when no id is provided with the import.

**Comment by simonst** [comment]
Any news on this one, it would be great to have this feature!

**Comment by antikalk** [comment]
@jonkoops I am sorry to bother you, but would it be possible if someone could have a look at this one? It's a rather minor thing that I think would improve the user import via the partial import API by a lot. 

At the moment exporting and reimporting (in an empty realm) would cause all users to have a new ID (even though the old ids are provided in the json). Also if the user is already present in Keycloak and using the OVERWRITE import setting the user will loose his ID and get a new one.

**Comment by jonkoops** [comment]
I usually do not work on the Java-side of things, but I will chase someone for you to get this fixed. The PR itself looks good to me.

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.

**Comment by alolis** [comment]
Is the fix for the importer only? Or will a custom UUID id be supported for when you are creating a user from the REST API as well with these changes?

**Comment by antikalk** [comment]
> Is the fix for the importer only? Or will a custom UUID id be supported for when you are creating a user from the REST API as well with these changes?

@alolis unfortunately only for the partial import API.

**Comment by alolis** [comment]
@antikalk , thanks for the clarification.
