### ISSUE TITLE
Keycloak adds "SameSite=Strict" setCookie on /auth request

### ISSUE THREAD

**Issue by mike-pt** [keycloak/keycloak#14177]
### Describe the bug

DISCLAMER: Not sure if this is a bug or some configuration I'm missing but so far I found nothing.

I've added a new vhost for a web app that uses keycloak, the new vhost is also on a new domain.

old: app.domain1.com
new: app.domain2.com

KC: idm.domain1.com

I've noticed that on refresh of the tab for "app.domain2.com" I was getting prompted from login again

Upon comparing the "set-cookie" headers I noticed this:

```
set-cookie
    AUTH_SESSION_ID=xxxxxxe-keycloak-xxxxx; Version=1; Path=/auth/realms/xxxx/; SameSite=Strict; Secure; HttpOnly
```

This does not happen if I come from app.domain1.com

There is nothing in our standalone/domain xml that enables anything like this

### Version

15.1.1

### Expected behavior

SameSite=Strict should not be added

### Actual behavior

SameSite=Strict is added

### How to Reproduce?

Unsure has this is the first time I see it, and I could only fine old posts referring to "SameOrigin" but apparently the repro comes from using a web app on a different domain?

### Anything else?

Keycloak and the Web app are deployed in GCE K8s using ingress and there is also no ingress annotation/config for set-cookies

**Comment by mike-pt** [comment]
Hum another interesting thing I'm seeing when comparing with a different env, deployed exactly the same way and also using  different domains is that on the stage env where I do not have issues I only see:

```
set-cookie | KC_RESTART
```


But on the failing case I get:
```
AUTH_SESSION_ID_LEGACY
AUTH_SESSION_ID
KC_RESTART
```

And of course on the stage env there is no "SameSite" in the set-cookies header:
```
set-cookie | KC_RESTART=xxxxxx;  Version=1; Path=/auth/realms/xxx/; Secure; HttpOnly
```

vs

```
set-cookie | AUTH_SESSION_ID=x-x-x-x-x.x-xx;  Version=1; Path=/auth/realms/xxx/; SameSite=Strict; Secure; HttpOnly
set-cookie | AUTH_SESSION_ID_LEGACY=x-x-x-x-x.x-xx;  Version=1; Path=/auth/realms/xxx/; Secure; HttpOnly; SameSite=Strict
set-cookie | KC_RESTART=xxxxxx;  Version=1; Path=/auth/realms/xxx/; Secure; HttpOnly; SameSite=Strict
```

To be clear this is not even on a reload its on the first request I make to "webapp.newdomain.com" compared to "webapp.stage.newdomain.com".

So although KC is running the same version on both, and same standalone.xml I now wonder if there is some setting that god changed that only affects the main env.

Stage env is a clone originally but its possible something got changed in the mean time by accident, I've check realm settings and client settings though and don't see anything different. The web app is exactly the same on both sides too.

They also share the same ingress setup only the hostnames/IPs change so I'm really lost as to why it works on on env and not the other, the only difference is the headers and "samesite=strict" but I have no clue where that is coming from

**Comment by patilvamsi** [comment]
Hi, I'm facing the same issue with the KC_RESTART cookie. Getting the Cookie not found error while redirecting from okta with SAML/OIDC. I didn't know where that value is coming from. Using Keycloak 18.0.2. Please help me out with how to deal with cross-domain IDP situations.

**Comment by douglaspalmer** [comment]
Duplicates #19886

**Comment by pedroigor** [comment]
The version reported is quite old and we are not setting `SameSite=none`. Although it does not provide the most secure policy, improvements are being discussed as per the issue above mentioned by Douglas.

**Comment by pedroigor** [comment]
@patilvamsi W.r.t to `KEYCLOAK_RESTART`, please check the linked issue above. We are missing the samesite attribute for this one.

Not sure why we don't set it. We can discuss it there.

**Comment by patilvamsi** [comment]
@pedroigor Thanks for the reply. The issue has been resolved by identifying a custom filter that was adding the cookie. By removing the filter, the cookie is no longer added, and the problem is fixed.

**Comment by joshua-2015** [comment]
> @pedroigor Thanks for the reply. The issue has been resolved by identifying a custom filter that was adding the cookie. By removing the filter, the cookie is no longer added, and the problem is fixed.

Can you elaborate on the specific steps to solve it? Thanks!

**Comment by patilvamsi** [comment]
Hi @joshua-2015 ,

We use a custom filter in our gateway to add cookies to URLs. When the filter identifies a URL as belonging to Keycloak, it adds the attribute "SameSite=Strict" to it. However, I've exempted a specific URL from having this attribute added.

Thanks!
