### ISSUE TITLE
Keycloak-Operator 19.0.1: make "--override" configurable in the KeycloakRealmImportJob.java

### ISSUE THREAD

**Issue by husira** [keycloak/keycloak#14183]
### Description

Regarding the Keycloak Import/Export documentation (https://www.keycloak.org/server/importExport), the `--override` option is set to `true` by default, so that realms are always overridden with the new configuration.

Regarding the Keycloak-Operator Realm Import documentation (https://www.keycloak.org/operator/realm-import.html), already existing Realms with the same name will not be overwritten.

Is it possible to make the [KeycloakRealmImportJob](https://github.com/keycloak/keycloak/blob/19.0.1/operator/src/main/java/org/keycloak/operator/controllers/KeycloakRealmImportJob.java#L164
) configurable, so that the `--override` flag can be set either true or false?

### Motivation

It may happen that someone makes manual changes in the Keycloak configuration of a specific realm (e.g. via GUI).
With the possibility to set `--override=true`, the KeycloakRealmImport CR will always override the existing Realm.
We also do not store users in Keycloak, as we query them via external providers. So the only thing we need is the configuration of Keycloak, which should always be identical with the configuration set in the KeycloakRealmImport custom resource.

In addition, I would have another enhancement about this topic:
In our company, we follow the GitOps approach. As far as possible, all configuration should be stored as code in Git. Via continuous deployment tools (we use argo-cd), changes on resources will be detected and re-synced.
As soon as someone pushes some changes in the Git to the KeycloakImportRealm custom resource (which is used for the import), argo-cd detects the changes and a re-sync them. This change has no effect on the existing KeycloakRealmImport-job. A way that automatically trigger the job would be great.

What do you think about these enhancements?

### Details

Keycloak-Version in use:
19.0.1

**Comment by husira** [comment]
hey @vmuzikar 

I'll try my luck and write to you directly, because I never received any feedback from anyone in this issue.

The latest keycloak-operator release (20.0.1) still has the flag override=false hardcoded in the KeycloakRealmImportJob. Are there any plans for the future?

The docs still mention the following (https://www.keycloak.org/operator/realm-import): If a Realm with the same name already exists in Keycloak it will not be overwritten.

But actually an override would be possible according to the Realm-Import / Export docs: https://www.keycloak.org/server/importExport

**Comment by nerumo** [comment]
That limitation came unexpected to me. I thought the operator would provide a way to declaratively define realms. We need this for a proper GitOps flow. The existing alternative https://github.com/adorsys/keycloak-config-cli still works, it's just that tiny override flag that prevents this

**Comment by vmuzikar** [comment]
Thanks for creating this issue. We did not include the `--override` switch simply because it does not align with the current intentended use case of the RealmImport CR – a one time import of a Realm for its initialization. Overriding a Realm might have unintended side effects, like deleting users and settings that were created after the Realm was imported. A possible solution might be some selective "merge" instead of a complete overwrite but this is not something Keycloak supports at the moment.

The plan still is to add new CRs for fully declarative management that would ultimately replace the RealmImport CR. However, I don't have any ETA I could share right now.
