### ISSUE TITLE
"1403 Killed" after starting a fresh build

### ISSUE THREAD

**Issue by Zumpel96** [keycloak/keycloak#14188]
### Describe the bug

After installing a new virtual machine (Ubuntu 22.04) and installing Java (JDK Version 11.0.16) I get the following error message when running `./kc.sh start-dev`

```root@my-server:/opt/keycloak/bin# ./kc.sh start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
./kc.sh: line 100:  1403 Killed                  java -Dkc.config.build-and-exit=true -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Dkc.home.dir='/opt/keycloak/bin'/../ -Djboss.server.config.dir='/opt/keycloak/bin'/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp '/opt/keycloak/bin'/../lib/quarkus-run.jar io.quarkus.bootstrap.runner.QuarkusEntryPoint --profile=dev start-dev
```

Machine specs: 
RAM - 0.5 GiB
Free disk space - ~30GB

### Version

19.0.1

**Comment by Zumpel96** [comment]
It seems, that the [installation prerequisites](https://www.keycloak.org/docs/latest/server_installation/#installation-prerequisites) are not correct. After increasing the memory size of the VM to ~1GiB the build succeeds.

**Comment by vmuzikar** [comment]
@Zumpel96 Thanks for the report. This indeed seems like a documentation issue. Please note that the documentation for the new Quarkus dist of Keycloak is located [here](https://www.keycloak.org/getting-started/getting-started-zip).

**Comment by shawkins** [comment]
@vmuzikar we have docs on memory under the high availablity topic. Are you wanting short / simple in the getting started about a memory requirement for the machine running kc.sh?

**Comment by vmuzikar** [comment]
@shawkins Thinking about it, I would not probably add memory requirements to the getting started guide. It would be another piece of perf related docs to maintain. Maybe we could simply add some note (a recommended read) to the [getting started guide](https://www.keycloak.org/getting-started/getting-started-zip) that would point to the [sizing guide](https://www.keycloak.org/high-availability/concepts-memory-and-cpu-sizing). WDYT?

**Comment by shawkins** [comment]
@vmuzikar it seems like a similar note would be needed in each of the getting started guides and for the operator as well. Or would you want a single getting started topic about hardware / VM requirements pointing to the high availability guide?

**Comment by vmuzikar** [comment]
@shawkins We can put the link (leading to the HA guide) into each getting started guide as a recommended read or something. That seems most explicit. WDYT?
