### ISSUE TITLE
Bug when LoadTest

### ISSUE THREAD

**Issue by hnhai** [keycloak/keycloak#14187]
### Describe the bug

- Run load test by Jmeter with 3000 ccu login to 500 difference accounts
- Using this image: [https://github.com/bitnami/containers/tree/main/bitnami/keycloak](url) runing on K8S

### Version

18.0.2

### Expected behavior

Keycloak working normaly

### Actual behavior

- Uncaught server error: org.infinispan.commons.IllegalLifecycleStateException: ISPN000324: Cache 'realms' is in 'STOPPING' state and this is an invocation not belonging to an on-going transaction, so it does not accept new invocations. Either restart it or recreate the cache container.
- JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)
- SQL Error: 0, SQLState: null
- Enlisted connection used without active transaction
- ARJUNA016029: SynchronizationImple.afterCompletion - failed for org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization@74ad3005 with exception: org.hibernate.exception.GenericJDBCException: Unable to release JDBC Connection

**Comment by hmlnarik** [comment]
This issue contains insufficient amount of information. When reporting the issue, please provide all the details of the use case, REST endpoints, server logs, stack traces etc. Feel free to reopen the issue with the details.
