### ISSUE TITLE
Removing testsuite/performance from main Keycloak repository

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#14192]
### Description

The dataset provider and the Gatling tests are now available in the kecloak-benchmark repository.

This issue is about to remove the folder `testsuite/performance` from the main Keycloak repository, as all new developements will take place in `keycloak-benchmark`.

While not all functionality like for example a cross-dc Infinispan setup, this will eventually be added to the keycloak-benchmark project when needed.

**Comment by ahus1** [comment]
Hi @tkyjovsk - I wonder if it is now time to remove the folder `testsuite/performance` from the old repository, as new development will take place in the repository `keycloak-benchmark`. 

Looking at the commits in the folder, I see that you've been most involved here, so I'm asking you to comment here. We could add a pointer in `keycloak-benchmark` repository to its predecessor.

Also adding @hmlnarik as I see that you've committed here as well and you could take a maintainer's view here. 

Looking forward to your comments!

**Comment by tkyjovsk** [comment]
@ahus1 I think we can go ahead and remove the legacy stuff now.
