### ISSUE TITLE
Keycloak is not genearting token for refresh_token call when run on 2 different instance 

### ISSUE THREAD

**Issue by ddjain** [keycloak/keycloak#14195]
### Describe the bug

- In our setup, we are running keycloak in a cluster (AWS ECS).

- We have a load balancer(AWS ALB), which distributes traffic in a round robin manner to each node of the keycloak server.

- We are using MySQL as a database for keycloak server.

- When a user issues access_token from one of the nodes, it gets success. and we are able to get access_token and refresh_token.

- The issue is when we use refresh_token in order to generate new access_token, and if the request goes to a different node (other then the node from which we generated access_token), we get below error in response.

`{
   "error": "invalid_grant",
   "error_description": "Session not active"
}`

### Version

15.0.0

### Expected behavior

- It must return refresh_token also when we run it on 2 different instances.

### Actual behavior

- When ever we are requesting to get refresh_token for different instance as of access_token

- It start throwing message in DEBUG log that No user session

- Here are attached screenshots of what we get in the terminal while generating refresh token.

![DeepinScreenshot_select-area_20220902201614](https://user-images.githubusercontent.com/17905734/188426716-4f056a18-92cd-40aa-8649-f84a46cb886f.png)

### How to Reproduce?

- Start Keycloak on 2 different ECS instances

- Made call to generate access_token from keycloak

- And again hit request for refresh token  from postman  with using grant_type as refresh token

- Whenever your request hitted the instance i.e is similar to access_token you will get the          refresh_token too 

- Else if you hit on that second instance which is also working fine , you will get a message on postman saying
- And this works in roundrobin

`{
   "error": "invalid_grant",
   "error_description": "Session not active"
}`

**Comment by mabartos** [comment]
@ddjain Thanks for creating this issue. 

@mhajas Could you please check it? I think it's necessary to have also remote Infinispan, right?

**Comment by lexcao** [comment]
I think the distributed cache is needed.
Please refer to this [doc](https://www.keycloak.org/server/caching) to configure your Infinispan distributed cache.

**Comment by ddjain** [comment]
I added below env variable in keycloak docker running on AWS ECS.

```
JGROUPS_DISCOVERY_PROPERTIES  = dns_query=keycloak.local, dns_record_type=SRV
JGROUPS_DISCOVERY_PROTOCOL = dns.DNS_PING
KC_CACHE = ispn
KC_CACHE_STACK = kubernetes
```

- `keycloak.local` is a SRV record used for Node discovery.
- These task are running with `awsvpc` network mode

After adding above env variable, getting below logs in keycloak
`11:08:51,860 WARN  [org.jgroups.protocols.TCP] (Connection.Receiver [10.0.3.173:38507 - 10.0.3.62:8080]-6,ejb,ip-10-0-3-173) JGRP000010: packet from 10.0.3.62:8080 has different version (5.28.49) than ours (4.2.11); packet is discarded
11:08:51,868 WARN  [org.jgroups.protocols.TCP] (Connection.Receiver [10.0.3.173:43751 - 10.0.3.173:8080]-7,ejb,ip-10-0-3-173) JGRP000010: packet from 10.0.3.173:8080 has different version (5.28.49) than ours (4.2.11); packet is discarded
11:08:54,869 INFO  [org.jgroups.protocols.pbcast.GMS] (ServerService Thread Pool -- 58) ip-10-0-3-173: no members discovered after 3042 ms: creating cluster as coordinator
11:08:55,265 INFO  [org.infinispan.CONTAINER] (ServerService Thread Pool -- 59) ISPN000128: Infinispan version: Infinispan 'Corona Extra' 11.0.9.Final
11:08:55,280 INFO  [org.infinispan.PERSISTENCE] (ServerService Thread Pool -- 62) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.marshalling.jboss.JBossMarshaller'`

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by mposolda** [comment]
@ddjain It seems this is setup/environment issue and also it is reported against very old Keycloak version. Please check latest Keycloak documentation (we have HA availability guide and others related to setup with AWS and cluster in general) and check if you are still able to reproduce (with using your environment according to latest docs).
