### ISSUE TITLE
Configurable session limits bug on chrome & edge

### ISSUE THREAD

**Issue by gabisonia** [keycloak/keycloak#14197]
### Describe the bug

I have configured session limit in Keycloak and it works only on firefox. 

### Version

18.0.0

### Expected behavior

When I try to sign in using same user I should be logged out.

### Actual behavior

I'm still signed in and session is active.

### How to Reproduce?

Authentication -> Flows -> New Flow -> Add execution -> User Session Count Limiter

And set Maximum concurrent sessions for each user within this realm to 1. 

Use chrome or edge.

**Comment by lexcao** [comment]
Hi, @gabisonia 
From the [docs](https://www.keycloak.org/docs/latest/server_admin/index.html#_step-up-flow)

> Note that the user session limits should be added to your bound Browser flow, Direct grant flow, Reset credentials and also to any Post broker login flow. Currently, the administrator is responsible for maintaining consistency between the different configurations.

Different from your reproduce steps, could you please try following the docs?

**Comment by gabisonia** [comment]
Hi @lexcao 
Thanks for the answer, is there any other way to implement it in version 18.0.0?

**Comment by lexcao** [comment]
Hi @gabisonia 
Here is the [same docs ](https://www.keycloak.org/docs/18.0/server_admin/index.html#_authentication-flows)of version 18.0

**Comment by mposolda** [comment]
@lexcao Thanks for answering this question. I am closing as this does not look like a valid bug.
