### ISSUE TITLE
Keycloak does not handle absolute-URI http request

### ISSUE THREAD

**Issue by manfuin** [keycloak/keycloak#14211]
### Describe the bug

Hi! We have a client that is sending HTTP requests to Keycloak using absolute-URI instead of absolute-path.
This is allowed by HTTP protocol https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2 
But Keycloak assumes it is always absolute-path and concatenates protocol, Host and Request-URI unconditionally.

E.g. with such a valid HTTP request there is an error:
```
GET https://keycloak.maxiv.lu.se:443/auth/realms/maxiv/.well-known/openid-configuration HTTP/1.1
Host: keycloak.maxiv.lu.se:443

HTTP/1.1 404 Not Found
{"error":"RESTEASY003210: Could not find resource for full path: https://keycloak.maxiv.lu.sehttps://keycloak.maxiv.lu.se/auth/realms/maxiv/.well-known/openid-configuration"}
```

More common absolute-path in Request-URI HTTP request is working as expected:
```
GET /auth/realms/maxiv/.well-known/openid-configuration HTTP/1.1
Host: keycloak.maxiv.lu.se:443

HTTP/1.1 200 OK
{"issuer":"https://keycloak.maxiv.lu.se/auth/realms/maxiv",....
```

### Version

18.0.2

### Expected behavior

Using absolute-URI as Request-URI in the HTTP request works.

### Actual behavior

Keycloak always assumes HTTP request sent with absolute-path in Reqeust-URI and does not handle absolute-URI requests.

### How to Reproduce?

Send HTTP request with absolute-URI, e.g.:

```
openssl s_client -connect keycloak.maxiv.lu.se:443
CONNECTED(00000003)
<output omitted>
GET https://keycloak.maxiv.lu.se:443/auth/realms/maxiv/.well-known/openid-configuration HTTP/1.1
Host: keycloak.maxiv.lu.se:443

HTTP/1.1 404 Not Found
<output omitted>
{"error":"RESTEASY003210: Could not find resource for full path: https://keycloak.maxiv.lu.sehttps://keycloak.maxiv.lu.se/auth/realms/maxiv/.well-known/openid-configuration"}
```

**Comment by stianst** [comment]
New Quarkus dist or legacy WildFly dist?

**Comment by manfuin** [comment]
New Quarkus, images from https://quay.io/repository/keycloak/keycloak

**Comment by ppppfly** [comment]
> ### Describe the bug
> Hi! We have a client that is sending HTTP requests to Keycloak using absolute-URI instead of absolute-path. This is allowed by HTTP protocol https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2 But Keycloak assumes it is always absolute-path and concatenates protocol, Host and Request-URI unconditionally.
> 
> E.g. with such a valid HTTP request there is an error:
> 
> ```
> GET https://keycloak.maxiv.lu.se:443/auth/realms/maxiv/.well-known/openid-configuration HTTP/1.1
> Host: keycloak.maxiv.lu.se:443
> 
> HTTP/1.1 404 Not Found
> {"error":"RESTEASY003210: Could not find resource for full path: https://keycloak.maxiv.lu.sehttps://keycloak.maxiv.lu.se/auth/realms/maxiv/.well-known/openid-configuration"}
> ```
> 
> More common absolute-path in Request-URI HTTP request is working as expected:
> 
> ```
> GET /auth/realms/maxiv/.well-known/openid-configuration HTTP/1.1
> Host: keycloak.maxiv.lu.se:443
> 
> HTTP/1.1 200 OK
> {"issuer":"https://keycloak.maxiv.lu.se/auth/realms/maxiv",....
> ```
> 
> ### Version
> 18.0.2
> 
> ### Expected behavior
> Using absolute-URI as Request-URI in the HTTP request works.
> 
> ### Actual behavior
> Keycloak always assumes HTTP request sent with absolute-path in Reqeust-URI and does not handle absolute-URI requests.
> 
> ### How to Reproduce?
> Send HTTP request with absolute-URI, e.g.:
> 
> ```
> openssl s_client -connect keycloak.maxiv.lu.se:443
> CONNECTED(00000003)
> <output omitted>
> GET https://keycloak.maxiv.lu.se:443/auth/realms/maxiv/.well-known/openid-configuration HTTP/1.1
> Host: keycloak.maxiv.lu.se:443
> 
> HTTP/1.1 404 Not Found
> <output omitted>
> {"error":"RESTEASY003210: Could not find resource for full path: https://keycloak.maxiv.lu.sehttps://keycloak.maxiv.lu.se/auth/realms/maxiv/.well-known/openid-configuration"}
> ```
> 
> ### Anything else?
> _No response_

Same issue, Version 18.0.2

**Comment by ppppfly** [comment]
Same issue, Version 18.0.2

**Comment by mabartos** [comment]
@manfuin Thanks for creating this issue!

However, it's not bug of Keycloak. The same issue was addressed on the Quarkus side with this ticket[1] and one of the best solutions for that is to fix it on the Quarkus side for RestEasy. Currently, we use Quarkus RestEasy Classic extension, and that issue is already solved for Quarkus RestEasy Reactive extension. It's possible to use RestEasy Reactive for Keycloak, but it's a little bit challenging to do it right now. 

[1] https://github.com/quarkusio/quarkus/issues/24898
