### ISSUE TITLE
Sync Registrations switch missing in new admin console

### ISSUE THREAD

**Issue by cybermo** [keycloak/keycloak#14226]
### Describe the bug

Sync Registrations switch is missing in the new admin console.
The switch is used if we want new users created by Keycloak added to LDAP.

### Version

19.0.1

### Expected behavior

Sync Registrations switch has to be visible to be able to toggle it ON/OFF.

### Actual behavior

Sync Registrations switch is not visible in the add LDAP provider page.

### How to Reproduce?

Add/Edit LDAP provider in the new admin console.

**Comment by lexcao** [comment]
It is an fixed issue and duplicated from https://github.com/keycloak/keycloak-ui/issues/2989

**Comment by kikolouro** [comment]
Can we still activate it from other place?

**Comment by lexcao** [comment]
You can change back to using the legacy admin theme.
Go to `master realm > settings > theme > admin`

**Comment by ssilvert** [comment]
Closing as duplicate.
