### ISSUE TITLE
New Operator cannot install multiple instances

### ISSUE THREAD

**Issue by dolfim-ibm** [keycloak/keycloak#14220]
### Describe the bug

The new Kubernetes operator should add the CR name in the `matchLabels`, of the statefulset (and possibly other resources), otherwise we cannot install multiple instances in the same namespace.

### Version

20.0.0-alpha.5

### Expected behavior

We can install multiple "isolated" instances in the same namespace.

### Actual behavior

The Operator creates two statefulset (one per instance), but when getting the details of any, we see both pods listed.

**Comment by jsorah** [comment]
Seems related to #10562

**Comment by vmuzikar** [comment]
Duplicate of https://github.com/keycloak/keycloak/issues/10562
