### ISSUE TITLE
In the latest version of keycloak 18.0.2 Logout functionality is not working.

### ISSUE THREAD

**Issue by sathishkumar3009** [keycloak/keycloak#14238]
### Describe the bug

Keycloak is hosted as containers in kubernetes.

Portal is integrated with keycloak, logout functionality is not working. 

To overcome this issue keycloak has suggested below command to execute during server start up.

How to run this command if keycloak is running in a container.

bin/kc.[sh|bat] --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start 

### Version

18.0.2

**Comment by lexcao** [comment]
There are three ways to configure keycloak. Please refer to [this guide](https://www.keycloak.org/server/configuration).

### command line parameters
```
docker run quay.io/keycloak/keycloak:19.0.1 \
start --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
```

### environment variables
```
docker run -e KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true \
quay.io/keycloak/keycloak:19.0.1 start
```

### configuration file
```
# keycloak.conf
spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
```
then with container
```
docker run -v $(pwd)/keycloak.conf:/opt/keycloak/conf/keycloak.conf \
quay.io/keycloak/keycloak:19.0.1 start
```

**Comment by mposolda** [comment]
@lexcao Thanks for the hints!

I am closing this as "explained". Note that future versions of Keycloak (maybe Keycloak 23) may remove switches for backwards compatibility of logout. See release notes and upgrading guide for the details. So please update your applications to avoid using deprecated `redirect_uri` parameter.
