### ISSUE TITLE
[LDAP federation] Username can be found in the user list although the user creation fails

### ISSUE THREAD

**Issue by Shiva19908** [keycloak/keycloak#14248]
### Describe the bug

When we try to create a user in federated realm with password not complying with the password policy, the user creation will fail. However, the username still can be found in the user list.

I think when Keycloak creates a user in federated realm, it first creates the user, then sets the password. If it fails to set the password it just shows an error saying user creation failed but it doesn't delete the user.

This issue is created for https://issues.redhat.com/browse/KEYCLOAK-14180 

### Version

10.0.1

### Expected behavior

user should not be present in LDAP or user should be deleted!

### Actual behavior

the user is still found in LDAP

### How to Reproduce?

When we try to create a user in federated realm with password not complying with the password policy, the user creation will fail. However, the username still can be found in the user list.

**Comment by mposolda** [comment]
I am adding label "Help wanted" as Keycloak team likely won't have time to look at this in the near future (but maybe I am possibly wrong as this may be handled somehow easily with the new store, but not sure...)

Anyone, who want to contribute this, please look at the comment of the original JIRA: https://issues.redhat.com/browse/KEYCLOAK-14180
