### ISSUE TITLE
Can't access Admin page  "failed to load resource: the server responded with a status of 500()"

### ISSUE THREAD

**Issue by Joshinwood** [keycloak/keycloak#14242]
### Describe the bug

After configuring another client and testing SAML auth to google, our admin page becomes inaccessible, throwing "Failed to Load Resource: server responded with a status of 500. As we have Keycloak installed on a docker container, if we restart the container hosting keycloak, the container starts, stops and then stays in a stopped state and another container boots up  and gets stuck in a loop. When accessing the keycloak landing page during this loop users get a "Bad Gateway" error message.

This is the 500 error we receive
![2022-09-07 14_26_39-Greenshot](https://user-images.githubusercontent.com/113007819/188806160-90cc6507-1442-4a24-91ee-5ec4cab13be9.png)

And this is the Bad Gateway error message
![2022-09-07 14_48_51-Greenshot](https://user-images.githubusercontent.com/113007819/188808830-8a292acb-1305-4e5c-996f-a4d77a07d755.png)

### Version

19.0.1

### Expected behavior

The admin portal works and it should allow us to sign in to the master realm, however it throws up the error here.

### Actual behavior

Throws initial status 500 error, can still access the landing page and sign in, but straight after sign in, all i see is a blank page.
After restarting container, even the landing page is inaccesible and only shows 'Bad Gateway' error with GET 502 error.

### How to Reproduce?

seems after restoring from backup it's only after a login attempt from google redirected to our keycloak login page then causes the issue. If i do not test the login for the client configured in keycloak for google then there is no issue. 

### Anything else?

I have 2 clients under 1 realm both externally hosted services. One web service works fine, google is causing issues, however haven't tested with anything else.

We also have configured keycloak, postgres and traefik all in one docker compose yml file. If need be i can post that here too

**Comment by lexcao** [comment]
Hi, @Joshinwood 
Could you please share more info about:
1. the error response from 500 of the requests to `/admin/master/console/whoami`
2. the error logs from your Keycloak server

**Comment by stianst** [comment]
Got no clue what's happening here, but without server logs or some more information like clear steps to reproduce there's nothing we can do.

**Comment by stianst** [comment]
We believe this is fixed in https://github.com/keycloak/keycloak-ui/pull/3373

Could you please try the nightly release (quay.io/keycloak/keycloak:nightly) and check if that works?

**Comment by stianst** [comment]
Closing this as we don't have sufficient information to be able to figure out what the potential problem is
