### ISSUE TITLE
Add basic auth compliant RFC 6749

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#14247]
### Description

There was something already done in Keycloak 19 by #11908 . However it needed to be improved for the compliance with RFC 6749 (See discussion on #11908 for the details).

**Comment by mposolda** [comment]
PR sent and merged in Keycloak 20: https://github.com/keycloak/keycloak/pull/14179

**Comment by mposolda** [comment]
Reopened for backport to 19.0.2

**Comment by sschu** [comment]
@mposolda  Backport PR: https://github.com/keycloak/keycloak/pull/14347
