### ISSUE TITLE
Keycloak and openldap integration not synchronizing users added in keycloak ui back to ldap

### ISSUE THREAD

**Issue by kikolouro** [keycloak/keycloak#14257]
### Describe the bug

When I add users in keycloak ui it doesn't add them in openldap. I have ldap user federation sync in writable. It does imported newly created users in ldap but not the other way around.

### Version

19.0.1 docker image

### Expected behavior

When we add users in keycloak ui it add the user to ldap

### Actual behavior

Keycloak only add users to local, not sync to ldap

### How to Reproduce?

add ldap user federation as writable and try to add an user in keycloak ui.

**Comment by ataraxus** [comment]
Just Upgraded and stumbled upon this too. Flag "Sync Registratrions" is missing. Was present in KC 16.1.1 
is still documented in current docs: https://www.keycloak.org/docs/latest/server_admin/

**Comment by ataraxus** [comment]
After looking at the code, I found a workaround, you can set this option if you switch the admin console theme to the old one. After switching the theme the option is available again an can be used as expected.

**Comment by kikolouro** [comment]
Sorry for late response, found people complaining about it. I had to switch the admin console to the old theme. Works fine.

**Comment by lepeli** [comment]
Hey, 

Can you reopen the issue, it might help to fix it later.

Thanks
