### ISSUE TITLE
Not able to create custom ClientAuthentication flow

### ISSUE THREAD

**Issue by makettner** [keycloak/keycloak#14259]
### Describe the bug

Since version 19 it's not possible to bind a custom client authentication flow. This behavior is possible in version 17 and/or 18.

### Version

19.0.1

### Expected behavior

To have a 'Bind flow' option in the copy of the clients flow, so that the 'Used by' 'Client authentication flow'  is moved from the 'Clients' flow to the copy of the clients flow.

### Actual behavior

The 'Bind flow'  option is missing from the menu

### How to Reproduce?

Installed a fresh keycloak
Created a test realm
In Authentication menu created a copy of the 'Clients'  build in flow
Try to bind this flow to the 'Client authentication flow', but it's only possible to duplicate or delete the flow.

**Comment by lexcao** [comment]
I could reproduce this from my side.
I think it is related to the new admin UI.
Could you please clone your ticket to https://github.com/keycloak/keycloak-ui/issues for tracking issues?

**Comment by makettner** [comment]
Created issue 3295 on keycloak-ui

**Comment by makettner** [comment]
closing issue here
