### ISSUE TITLE
Google login - add prompt=select_account option

### ISSUE THREAD

**Issue by EvgeniGordeev** [keycloak/keycloak#14258]
### Description

Google configuration page does not let configure `prompt` param to be passed to google login. 

Scenario:
1. Use Google for login
2. User chooses google account
3. User realizes they logged in with the wrong google account and restart the login process.
Issue: user cannot get to google select account any more and is stuck with the first google account. If multiple google sessions are authenticated for given user then google account picker is displayed. 
Expected: even if there is a single authenticated google session client can request an account picker with query param `prompt=select_account`. Thus Google configuration page on Identity Providers must support setting prompt param. 

### Motivation

Make google login more user-friendly on single authenticated google session with `prompt=select_account`. 

### Details

Workaround: 

add `CustomGoogleIdentityProviderFactory` to META-INF/services/org.keycloak.broker.social.SocialIdentityProviderFactory file

```java

public class CustomGoogleIdentityProviderFactory extends GoogleIdentityProviderFactory {
    @Override
    public GoogleIdentityProvider create(KeycloakSession session, IdentityProviderModel model) {
        return new CustomGoogleIdentityProvider(session, new GoogleIdentityProviderConfig(model));
    }
}

...
public class CustomGoogleIdentityProvider extends GoogleIdentityProvider {
    public CustomGoogleIdentityProvider(KeycloakSession session, GoogleIdentityProviderConfig config) {
        super(session, config);
    }

    @Override
    protected UriBuilder createAuthorizationUrl(AuthenticationRequest request) {
        UriBuilder uriBuilder = super.createAuthorizationUrl(request);
        uriBuilder.queryParam("prompt", "select_account");
        return uriBuilder;
    }
}
```

**Comment by lexcao** [comment]
Yes, the standard OIDC configurations are missing in the `Google` identity provider as well as Microsoft.
Like `login_hint` from  https://github.com/keycloak/keycloak/pull/8374, it is better to add these to the new admin UI.

Could you please clone this ticket to https://github.com/keycloak/keycloak-ui

There is another workaround,
create an `OIDC` identity provider instead of a `Google` identity provider.

**Comment by JaleelB** [comment]
> Yes, the standard OIDC configurations are missing in the `Google` identity provider as well as Microsoft. Like `login_hint` from #8374, it is better to add these to the new admin UI.
> 
> Could you please clone this ticket to https://github.com/keycloak/keycloak-ui
> 
> There is another workaround, create an `OIDC` identity provider instead of a `Google` identity provider.

The OIDC solution works! Thank you.

**Comment by EvgeniGordeev** [comment]
Closing as a duplicate of https://github.com/keycloak/keycloak/issues/16750
