### ISSUE TITLE
Exception due to requirement of "client_id" presence within Request Object

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#14255]
### Describe the bug

Issue Description:
===================

A thirdparty OIDC client registered in Keycloak is using the authorisation code grant flow.
The authorization request is build by this OIDC client and the `request_uri` request parameter is provided.

When Keycloak tries to handle the JWE Encrypted Request Object obtained through the "request_uri" request parameter, we can see that Keycloak verifies that the "client_id" claim is present within the decrypted request object and is the same as the "client_id" provided request parameter. Request Object provided by a thirdparty OIDC Client doesn't contain this claim as this is not a mandatory claim in the OIDC specifications.

The OIDC specification states that for the request to be a valid OAuth 2.0 Authorization Request, " values for the response_type and client_id parameters MUST be included using the OAuth 2.0 request syntax, since they are REQUIRED by OAuth 2.0. The values for these parameters MUST match those in the Request Object, if present."
[OIDC Specification](
https://openid.net/specs/openid-connect-core-1_0.html#RequestUriParameter
)

The "response_type" and "client_id" request parameters are indeed provided by this thirdparty OIDC client but are not present in the Request Object because these values are optional within it. So the validation against the "client_id" should be done only if the claim is provided in the Request Object only... and then the presence of this claim shouldn't be mandatory as today within Keycloak

**Auth Request Endpoint**
https://www.foo.com/authorize?response_type=code
&redirect_uri=https%3A%2F%2Frfoo.com&request_uri=https%3A%2F%2Ffoo.com/bar&scope=openid%2Bservices&client_id=aaa&state=bbb&nonce=ccc

**Decrypted Request Object**
```
{
"foo": "bar",
"baz": "some"
}
```

server.log
===========

```
org.keycloak.protocol.oidc.endpoints.request.AuthorizationEndpointRequestParserProcessor.parseRequest(AuthorizationEndpointRequestParserProcessor.java:96)
at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:132)
at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```

Notes:
=====

The change should be done in the following class
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestObjectParser.java
In particular...

```
if (clientId == null) {
throw new RuntimeException("Request object must be set with the client_id");
}

if (!client.getClientId().equals(clientId.asText())) {
throw new RuntimeException("The client_id in the request object is not the same as the authorizing client");
}
```

should be changed into

```
if (clientId != null && !client.getClientId().equals(clientId.asText())) {
throw new RuntimeException("The client_id in the request object is not the same as the authorizing client");
}
```

Workaround
===========
Updated source file of AuthzEndpointRequestObjectParser
Updated source file of AuthzEndpointRequestParser
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java
 
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestObjectParser.java

Queries:
=========
1) Is the "client_id" claim mandatory in the object request (current Keycloak mode) ?

2) Is the overriding of each authorization endpoint request attribute, with the one available from the one in the object request even if it is null, correct (current Keycloak mode) ?

3) Regarding the RFC9101 ("The OAuth 2.0 Authorization Framework: JWT-Secured Authorization Request (JAR)"), the "client_id" claim seems indeed mandatory.
However, it doesn't seem correct to override the authorization endpoint request attributes with null values if not present in the request object.

### Version

19.0.1

**Comment by mposolda** [comment]
@tnorimat This was reported by one of our customers. WDYT? Does it makes sense to you to fix as proposed in the description of this issue?

Answers to the questions as I see it (but please correct me if I am wrong):
1. The `client_id` parameter is not mandatory in the OIDC request object as stated in this description (For example I am not sure about specs like PAR or various FAPI requirements, but at least in the plain OIDC core, it doesn't seem to be required in the JWT `request` object. It is required only in the OAuth2 request and if provided in both the JWT `request` object and in the OAuth2 request, then we must validate that it is the same

2. I think that overriding should be skipped for null values

3. Same answer as to (2)

So it looks that we should:
- Make sure that `client_id` is not mandatory in the `request` object (At least for the plain OIDC)
- Don't override values with null values (At least for the plain OIDC)

**Comment by tnorimat** [comment]
@mposolda Basically, I agree with you.

"client_id" in a request object is mandatory in [FAPI 1.0 Advanced securtity profile](https://openid.net/specs/openid-financial-api-part-2-1_0.html#confidential-client).  The executor for FAPI 1.0 Advanced security profile does not check whether a request object includes "client_id" and "response_type" because `AuthzEndpointRequestObjectParser` does the check.
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRequestObjectExecutor.java#L135
Therefore, your suggesting fix may cause some failures of FAPI 1.0 Advanced/Australia CDR/Open Banking Brazil conformance tests.
To not cause the failures, `SecureRequestObjectExecutor` also need to be modified to check whether "client_id" and "response_type" are included in a request object.

I also think that "client_id" is mandatory in JAR but not in OIDC. If we want to control whether a request object without "client_id" is accepted or not, an executor of a client policy can be used. 

Moreover, how should be treat "response_type"?

**Comment by mposolda** [comment]
@tnorimat Thanks for pointing this. +1 to add the checks to the `SecureRequestObjectExecutor` if we remove them from `AuthzEndpointRequestObjectParser`. So we should be still FAPI Advanced compliant. I think we can do this for both `client_id` and `response_type` and have them both in the `SecureRequestObjectExecutor` ?

Also do you agree that overriding should be skipped for null values?

**Comment by tnorimat** [comment]
@mposolda 
> I think we can do this for both `client_id` and `response_type` and have them both in the `SecureRequestObjectExecutor` ?

Yes, `SecureRequestObjectExecutor` checks both.

> Also do you agree that overriding should be skipped for null values?

Yes, I agree with it.

**Comment by tnorimat** [comment]
@mposolda IMO, there are two options to deal with this issue:

1. Firstly, updating `SecureRequestObjectExecutor` for checking existence of `client_id` and `response_type` as an independent PR. Next, working on this issue.
2.  The PR of this issue also updates `SecureRequestObjectExecutor`. 

Which do you like better? If former, I can send the PR of updating `SecureRequestObjectExecutor` separately.

**Comment by mposolda** [comment]
@tnorimat +1 to do both in the same PR (so your approach 2).

Also do you agree that overriding should be skipped for null values? See points 2 and 3 from the description of this issue from the section "Queries" for more details of what I mean. Should we do something about this or are we fine with keep as it is?

**Comment by tnorimat** [comment]
@mposolda Yes, I agree that overriding should be skipped for null values. I have not encountered such the parameter that its value being null has some valid meaning. However, the current keycloak overrides the parameter whose value is null. Therefore, it might be better to do some documentation.

**Comment by mposolda** [comment]
@tnorimat Good point. So maybe sufficient to not care about overriding for null values, but just fix this as described per your approach 2 in the comment https://github.com/keycloak/keycloak/issues/14255#issuecomment-1244787672 ?

**Comment by tnorimat** [comment]
@mposolda Yes. According to [5.2.3.  Confidential client of FAPI 1.0 Advanced Final](https://openid.net/specs/openid-financial-api-part-2-1_0.html#confidential-client),
> 9. shall additionally send duplicates of the response_type, client_id, and scope parameters/values using the OAuth 2.0 request syntax as required by Section 6.1 of the OpenID Connect specification if not using [PAR](https://tools.ietf.org/html/draft-ietf-oauth-par);

> 16. shall additionally send a duplicate of the client_id parameter/value using the OAuth 2.0 request syntax to the authorization endpoint, as required by Section 5 of [JAR](https://tools.ietf.org/html/draft-ietf-oauth-jwsreq), if using [PAR](https://tools.ietf.org/html/draft-ietf-oauth-par).

To satisfy them, `SecureRequestObjectExecutor` need to be modified.

**Comment by mposolda** [comment]
> To satisfy them, SecureRequestObjectExecutor need to be modified.
> The current SecureRequestObjectExecutor does not check them rigorously. I can take over the task of modifying 
> SecureRequestObjectExecutor WDYT?

+1 for this approach if possible. Thanks for looking at this!

**Comment by tnorimat** [comment]
@mposolda I will create a PR for this modification of `SecureRequestObjectExecutor` for checking a request rigorously for FAPI 1.0 advanced.

**Comment by tnorimat** [comment]
@mposolda If you need to fix this issue as soon as possible, it might be ok to for the PR for resolving the issue to modify `SecureRequestObjectExecutor` to only check the existence of `client_id` and `response_type` in a request object.
