### ISSUE TITLE
Mod Aut Mellon files zip empty

### ISSUE THREAD

**Issue by ewo2022** [keycloak/keycloak#14260]
### Describe the bug

-> Created a new SAML Client in k8s HA cluster
-> Added Redirect URI
-> Click on "Action" -> "Download Adapter Config"
-> Dialog opens -> Choosing "Mod Auth Mellon files" -> Download
-> Downloaded zip Files is empty

### Version

19.0.1

### Expected behavior

Downloaded Zip-File has Mod Auth Mellon files
Hopefully logs on error

### Actual behavior

Downloaded Zip-File is empty
No error/warning logs

### How to Reproduce?

As described above

**Comment by lexcao** [comment]
Hi, @ewo2022 
Are you using the new admin UI in Keycloak?
If so, it is a duplicated issue to https://github.com/keycloak/keycloak-ui/issues/3264

**Comment by ewo2022** [comment]
Thanks!
