### ISSUE TITLE
Old administration console not loading

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#14288]
### Describe the bug

Looks like the old administration console is broken after this change https://github.com/keycloak/keycloak/pull/14271.

By reverting the changes, you should be able to access the old admin console as expected.

### Version

999-SNAPSHOT

**Comment by pedroigor** [comment]
@jonkoops @ssilvert Any idea what might be happening? You get an error in the browser console but it is not clear what is happening. Just pointing to `services.js`.

**Comment by sschu** [comment]
@pedroigor @ssilvert @jonkoops I see syntax errors, something is broken with the nesting and IntelliJ also says it expects a `,`and not closing brackets...

**Comment by lexcao** [comment]
I have reproduced from my local as well.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/14901139/189537014-50c842eb-02bf-40e8-945e-132fd3476081.png">

Attempt to fix from my local, this change would work.
```diff
query.callback({ results: response.map(function (client) {
    return { id: client.id, text: client.clientId }
-});
+})});
```

I am going to make a PR.
