### ISSUE TITLE
Multiple JDBC connection Pools

### ISSUE THREAD

**Issue by anovinger** [keycloak/keycloak#14285]
### Description

Would like to get an Enhancement for Keycloak to support multiple JDBC connections pools.  

### Motivation

This is a need as our SPI adapter is pulling data from another database, that the Keycloak cluster is not using.  This is preventing us from migrating off of Wildfly to Quarkus.

### Details

This is a need as our SPI adapter is pulling data from another database, that the Keycloak cluster is not using.  This is preventing us from migrating off of Wildfly to Quarkus.

**Comment by pedroigor** [comment]
@anovinger You can configure additional data sources by setting some Quarkus properties. See https://github.com/keycloak/keycloak-quickstarts/blob/latest/user-storage-jpa/conf/quarkus.properties.

Perhaps we should document this better?

**Comment by anovinger** [comment]
Thanks @pedroigor yeah I was reading the documentation, but the last statement in this section https://www.keycloak.org/server/configuration#_using_raw_quarkus_properties which is where I was getting confuse.  Since the JDBC was already used in keycloak properties, it sounded like putting another connection in the quarkus.properties file would had no effect.

**Comment by pedroigor** [comment]
@anovinger I see. You are going to set properties to a "named" data source that are different than the properties we use to set the default data source.
