### ISSUE TITLE
Javascript Adapter fires clearToken() if checkloginiframe is not set to false

### ISSUE THREAD

**Issue by Baelx** [keycloak/keycloak#14322]
### Describe the bug

With our app using the Keycloak Javascript adapter, users log in, get redirected back to our app, then use it as normal until the access token expires. When the token is expired, our app is set up to run `updateToken()` automatically. However, the query to the server fails due to no refresh token being sent with the POST request. Upon further inspection, we found that `clearToken()` is being run seconds after log in, removing all tokens from memory.

After looking into the source code and trolling support forums, I found that passing `checkloginiframe: false` into the init options resolves the issue.

I'm still not sure why this option is necessary. In my opinion, the documentation doesn't really make clear that it's needed. I'm not sure if the documentation needs to be updated to place greater emphasis on this option or if this is an anomalous bug occurring only on localhost environments. Either way, I'm hoping someone can lend some insight as to why this behaviour occurs and potentially take steps to resolve it if necessary.

### Version

19.0.1

### Expected behavior

`updateToken()` is called and the refresh token in memory is used to query the Keycloak server for a new access token.

### Actual behavior

`updateToken()` is called but refresh token is not in memory. POST to Keycloak server fails and access token is not refreshed.

### How to Reproduce?

1. In your app, instantiate a new Keycloak object with your Keycloak server's config: `new Keycloak({ client_id: xxxxx, realm: xxxxx, url: xxxxx })`
2. Call the init() function as such: `keycloak.init({ onLoad: 'check-sso', pkceMethod: 'S256' })` when your app loads. This should trigger a redirect and prompt the user to log in.
3. Set up a way to trigger keycloak's `updateToken()` call when the Access Token expires(through an HTTP interceptor, for ex.)
4. Boot up your app on localhost. Log in with Keycloak and get returned back to your app. Wait 5 minutes for the access token to expire(by default).

### Anything else?

**Environment**
- Local development(localhost)
- Angular app(not using any additional Keycloak auth library, just keycloak-js)
- Mac OS Big Sur

**Comment by jonkoops** [comment]
Did some testing on the latest stable version of Keycloak, and it is no longer possible to reproduce this using the procided steps. Considering nobody else has chimed into this issue it seems that also nobody else is affected, so I think this issue may have been fixed over time.

I'll close the issue, but if someone is able to reproduce this on the latest version let me know and I will re-open it.
