### ISSUE TITLE
After deleting all resources, from Authorization under Clients. You lose the create option

### ISSUE THREAD

**Issue by fischer7** [keycloak/keycloak#14320]
### Describe the bug

I was making a new setup to Keycloak, so I've downloaded the last version with docker-compose:
image: bitnami/keycloak

After deleting the sample resource, to create my own, I couldn't proceed:
![image](https://user-images.githubusercontent.com/26326537/189400619-50310474-c12d-498b-8032-008d9f0db217.png)

Anyway, importing from another confg., I was good to go again. But you may get stuck here.
![image](https://user-images.githubusercontent.com/26326537/189400848-fe1375f5-65fa-4366-aa66-6766e62c0248.png)

### Version

19.0.1

### Expected behavior

Be able to create a new resource.

### Actual behavior

Lost of the "Create resource" button

### How to Reproduce?

Delete all resources from a Client > Authorization page.

### Anything else?

![image](https://user-images.githubusercontent.com/26326537/189401824-ccfe7ed5-f170-45a0-8450-6e17a98a9bda.png)

**Comment by lexcao** [comment]
It seems related to the new admin UI.
Could you please clone your ticket to https://github.com/keycloak/keycloak-ui?

**Comment by fischer7** [comment]
Just did it ☺
https://github.com/keycloak/keycloak-ui/issues/3296
