### ISSUE TITLE
Read-only user error message in account console not expanded properly

### ISSUE THREAD

**Issue by darius-m** [keycloak/keycloak#14337]
### Describe the bug

The error message is not properly expanded when attempting to update the personal information of a user imported from a read-only federated storage. The error message that is displayed is `Danger alert:Bad Request: readOnlyUserMessage`.

### Version

19.0.1

### Expected behavior

A localized error message, like the `Federated storage is not writable` text that is displayed when attempting to update the user password should be displayed.

**Comment by edewit** [comment]
this seems to have been fixed I now get: 'Could not create user: User is read only!'
