### ISSUE TITLE
Make attributes read-only in user account console for read-only federated accounts

### ISSUE THREAD

**Issue by darius-m** [keycloak/keycloak#14335]
### Description

When a user is imported from a read-only LDAP federation, some user attributes should be displayed as either disabled text inputs or simple text (e.g., HTML paragraphs), and some elements should be removed altogether. This affects interface elements such as:
  - Personal info
    - username
    - email
    - first name
    - last name
    - save / cancel buttons
  - Account security > Signing in
    - User password (update button)

### Motivation

When users access the account console they see the option to edit their account details, but when attempting to submit some changes, an error message is displayed since the federated storage is not writable. This is confusing for users because the interface displays immutable information as editable.

### Details

User fields should properly be displayed as read-only if they cannot be edited. In this case, the buttons that are used to update data (in the `Personal info` tab) / redirect users to update their information (for passwords) should also be removed.

An additional possible enhancement would be adding an option to disable the editing of user details (e.g. First / Last name) for all users. Company policies may require users to follow an approval / verification procedure when updating some user data, but users should be able to change their passwords when the federated storage is writable.

**Comment by lexcao** [comment]
Hi, you can try `declarative-user-profile` feature to achieve that.
See the [docs](https://www.keycloak.org/docs/latest/server_admin/index.html#defining-a-user-profile)

**Comment by darius-m** [comment]
Thank you for your reply. After a quick look, this does appear to partially address the issue, but requires some manual configuration. I will look further into this to see if we can / should use it in our case (the current approach is to edit the account console and change how fields are displayed, but this requires changes with Keycloak updates).

However, my argument for the issue is that this should be set by default, and users should not see the option to edit fields that cannot be saved (e.g., the user is imported from a read-only LDAP federation). This may be achieved by setting the conditions to `false` if the user federation is set to read-only (e.g. `isEditUserNameAllowed` would either be set to `false` if the field is set to non-editable in `declarative-user-profile` settings, or the user field cannot be edited in the federation).

**Comment by pedroigor** [comment]
The use case makes sense to me too. 

We already have:

* Account dynamically rendering attributes based on the user profile metadata

We are missing:

* Incorporate into the metadata whether an attribute is read-only depending on how user federation is configured.

Does that make sense?

I'm not sure if the metadata should be entirely based on how user federation providers are configured or if we also need some settings in the UI.

**Comment by pedroigor** [comment]
@darius-m Closing in favor of https://github.com/keycloak/keycloak/issues/23878. They are related and this one provides a good source of information.
