### ISSUE TITLE
Missing roles in ID token/userinfo

### ISSUE THREAD

**Issue by yohny** [keycloak/keycloak#14356]
### Describe the bug

I have just created a fresh client in a new realm. This fresh client has `roles` scope configured as a default scope. If I inspect `roles` scope I can see that it has 3 mappers configured out of the box: `audience resolve`, `realm roles` and `client roles`.
The latter two mappers have both turned ON the options to be added in ID token, Access token and Userinfo:
![image](https://user-images.githubusercontent.com/5924185/189756092-7fe18edd-a585-4723-b292-325bc9c25d62.png)

However when the tokens are obtained by the client the realm and client roles are only present in Access token and are missing in ID token and Userinfo. 

### Version

19.0.1

### Expected behavior

the realm/client roles are also present in ID token and Userinfo as indicated by `roles` scope mapper settings (or disable those settings completely to indicate that they can not be added to ID token/Userinfo)

### Actual behavior

`roles` scope mapper settings to include realm/client roles in ID token and Userinfo are ignored

### How to Reproduce?

1. create a fresh client with default roles scope and get the ID and access tokens for it
1. observe that access token contains realm/client roles claims as indicated by mapper settings 
1. observe that ID token does NOT contain realm/client roles claims, even if mapper settings indicate that it should

**Comment by yohny** [comment]
I just happened to try this configuration in old Keycloak (version `8.0.1`) and there it worked as expected - the roles claims are present also in ID token

**Comment by dankots** [comment]
When I open the above GUI page, the GUI fetches the protocol-mapper from keycloak, and the keycloak response does NOT contain id.token.claim
however the GUI shows "add to id token" is ENABLED.
it is NOT enabled on in keycloak

changing that value in the GUI from disabled -> save, enabled -> save, 
then correctly enables it in keycloak.

So maybe only a GUI bug.

**Comment by madbrain** [comment]
It seems to have been corrected in the UI with PR https://github.com/keycloak/keycloak-ui/pull/3822

**Comment by mposolda** [comment]
I am closing as this works as expected in the latest Keycloak 21.

Just a note that roles in the Id-token and user-info are not strictly OIDC specification compliant (regarding access-token it is fine to have roles as access-token structure is not prescribed by OIDC specification).
