### ISSUE TITLE
File vault not working after upgrade to 19.x

### ISSUE THREAD

**Issue by hjannasch** [keycloak/keycloak#14363]
### Describe the bug

After upgrading from 18.x to 19.0.1, it seems that file vault contents are not replaced when using `kcadm.sh` to import a realm.

Related property in keycloak.conf (secret files are mounted to this dir)
`vault-dir=/opt/keycloak/conf/secrets`

Start command (docker compose file)
`- start --spi-vault-file-key-resolvers=KEY_ONLY,REALM_UNDERSCORE_KEY`

Import command
`
kcadm.sh create realms -s realm=zidDevOps -s enabled=true
kcadm.sh create partialImport -r zidDevOps -s ifResourceExists=OVERWRITE -o -f /opt/keycloak/conf/realm.json
`

Content of realm.json
`
  "identityProviders": [
    {
        ...
        "config": {
            ...
            "clientSecret": "${vault.azure-ad-secret}",
            ...
        }
    }
  ]
`

Result: 

### Version

19

### Expected behavior

Actual secret value imported.

### Actual behavior

String ${vault.azure-ad-secret} imported instead of actual secret.

### Anything else?

Same setup is working on keycloak 18.x

**Comment by hjannasch** [comment]
Is there any debug option which shows the vault content?

**Comment by pedroigor** [comment]
@hjannasch You should also set the `vault=file` option. Can you please try it out?

**Comment by hjannasch** [comment]
@pedroigor Many thanks, adding `vault=file` to `keycloak.conf` works.

**Comment by hjannasch** [comment]
Works with settings both

```
vault=file
vault-dir=/opt/keycloak/conf/secrets

```

to keycloak.conf
