### ISSUE TITLE
Update user attribute deletes existed attributes

### ISSUE THREAD

**Issue by serhatko** [keycloak/keycloak#14378]
### Describe the bug

Hello,

Currently I have Keycloak 19.0.1 installed in an App Service on my Azure environment. Everything seems to work fine but when I tried to update user attribute via Admin API, all the existing user attributes are deleted and only the attribute that I wanted to update is left on user. I checked many sources on this issue, I've seen this issue on previous version but I couldn't find any solid or work-around solution for this problem.

Before Update Request:

![image](https://user-images.githubusercontent.com/16943671/189982867-421d61f1-1d4e-4482-9fa0-2e957604077a.png)

Request is made from a Java method:
![image](https://user-images.githubusercontent.com/16943671/189982982-94354609-b641-473c-acc8-816c78daf2ce.png)

After invoking method with attribute name:attribute2 and new value:000000
![image](https://user-images.githubusercontent.com/16943671/189983183-1c358391-e960-436c-83fd-50564e40c10b.png)

### Version

19.0.1

### Expected behavior

When update user attribute API is called, only the requested attribute must be updated. If user has any other attributes beside that the one is updated, these attributes must be unchanged after update.

### Actual behavior

When update user attribute API is called, only the requested attribute left on the user. If there are extra attributes on user, they are deleted after updating an attribute.

### How to Reproduce?

Just create a user with multiple attributes and try to update one of them with admin API.

**Comment by pedroigor** [comment]
@serhatko Thanks. Unfortunately, we don't support PATCH operations so you need to pass all user attributes otherwise they are removed.

It is not a bug but expected behavior.
