### ISSUE TITLE
Support redirect URI client policy executor

### ISSUE THREAD

**Issue by lexcao** [keycloak/keycloak#14381]
### Description

See the entire background from #14380

### Redirect URI Client Policy Executor

Implement a configurable Redirect URI client policy that allows configuring the policy around redirect-uris, maybe options like:

Option | Type | Default | Notes
-- | -- | -- | --
Allow Private-Use URI Scheme Redirection | boolean | false | https://www.rfc-editor.org/rfc/rfc8252#section-7.1
Allow Loopback Interface Redirection | boolean | true | https://www.rfc-editor.org/rfc/rfc8252#section-7.3
Allow HTTP | boolean | false |  
Allow wildcard in context-path | boolean | true | Mainly for compatibility with Keycloak adapters
Permitted domains | List |   | List permitted domains, with support for regex, if enabled will allow wildcard in hostname, and check that configured redirect-uri matches one of the patterns
Allow Open Redirect | boolean | false |  

The client policy would only check the configured redirect-uris for a client when created or updated.

### Design

1. implement `ClientPolicyExecutorProvider` interface for **`RedirectUriClientPolicyExecutor`**
2. execute on event
    1. `REGISTER`
    2. `UPDATE`
3. with configuration options from above

**Comment by lexcao** [comment]
There are 2 open questions:
1. Should `post_logout_redirect_uri` is also validated by the policy while it only validates for `redirect_uri` currently?
    * I think it could not, find the description of `post_logout_redirect_uri` from specs
> These URLs SHOULD use the https scheme and MAY contain port, path, and query parameter components
> -- https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata

2. Should it be possible for `http://localhost:8080` if there allows the loopback interface but disallow HTTP?
-- I think it could

**Comment by mposolda** [comment]
I am closing as this was already addressed by #25637 and should be available in Keycloak 24.
