### ISSUE TITLE
Quarkus Tests in GHA are very slow

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#14389]
### Description

ATM, tests for Quarkus distribution executed in the GHA are very slow.

I don't know the purpose of the step related to building the parent pom with the `distribution` profile again; should be already built and stored in the m2. Also, the individual tests are executed sequentially and I don't see any problem with why they shouldn't be executed in parallel. 

I've found out the average execution time is ~80m.

**Comment by vmuzikar** [comment]
jFTR – there is a related task for improving test run times: https://github.com/keycloak/keycloak/issues/13544

CC: @andre-nascimento-rh

**Comment by mabartos** [comment]
Not relevant anymore.
