### ISSUE TITLE
Tar file broken

### ISSUE THREAD

**Issue by tuxmaster5000** [keycloak/keycloak#14393]
### Describe the bug

The fie name of many jar files are truncated.

### Version

19.0.2

### Expected behavior

That the tar ball contains all files

### Actual behavior

Keycloak don't start, because of missing files.
The files are not missing, but the files names of it are truncated.

### How to Reproduce?

Simple try to start it.

### Anything else?

The zip archive is fine, only the tarball are affected.

**Comment by stianst** [comment]
Which tar files? In what environment?

**Comment by tuxmaster5000** [comment]
This:
https://github.com/keycloak/keycloak/releases/download/19.0.2/keycloak-19.0.2.tar.gz
on CentOS Stream 8

**Comment by stianst** [comment]
U using GNU tar to extract it or something else?

**Comment by tuxmaster5000** [comment]
Very strange, an tar xf will work, but extract the same file using the mc will fails.

**Comment by stianst** [comment]
I know some tar tools don't work well with tars that have long filenames inside them. I see that rather as an issue with the tool than something we can fix though.

**Comment by tuxmaster5000** [comment]
Yes, so I will close it.
