### ISSUE TITLE
Save and Cancel Buttons remain disabled for some Realm level settings updates

### ISSUE THREAD

**Issue by HMNoumanKhan** [keycloak/keycloak#14392]
### Describe the bug

1 - Go to the Realm Settings
2 - Under the Tokens tab
3 - Set **Override User-Initiated Action Lifespan**
4 - Save and Cancel buttons do not enable

However, if you change other settings, these buttons start to appear and changes can be saved. This is a minor front-end issue.

### Version

jboss/keycloak:16.1.0

### Expected behavior

Upon changing the values in Override User-Initiated Action Lifespan drop downs, the Save and Cancel buttons should be enabled.

**Comment by stianst** [comment]
Can you check in the latest release please?
