### ISSUE TITLE
Missing artifact for 19.0.2

### ISSUE THREAD

**Issue by freswa** [keycloak/keycloak#14399]
### Describe the bug

Release 19.0.2 fails to build from source. The artifact `org.keycloak:keycloak-admin-ui:jar:19.0.2` is missing in the public repositories. 
```
[ERROR] Failed to execute goal on project keycloak-dependencies-admin-ui-wrapper: Could not resolve dependencies for project org.keycloak:keycloak-dependencies-admin-ui-wrapper:jar:19.0.2: Could not find artifact org.keycloak:keycloak-admin-ui:jar:19.0.2 in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
```

### Version

19.0.2

### Expected behavior

Artifact available for download.

### Actual behavior

Artifact is missing.

### How to Reproduce?

Try to build the sources.

**Comment by stianst** [comment]
It's there now. It just takes a little bit of time for maven to sync artifacts.
