### ISSUE TITLE
Can't open Authentication flow Identity Provider settings

### ISSUE THREAD

**Issue by wangchengxin** [keycloak/keycloak#14425]
### Describe the bug

![image](https://user-images.githubusercontent.com/15154825/190344310-c429b6fd-c070-455e-b4d1-fc43c8c5d7bd.png)
![image](https://user-images.githubusercontent.com/15154825/190344354-9e8bd861-7f19-4234-bdaa-b6cbdc77fef3.png)

### Version

19.0.2

**Comment by sventorben** [comment]
Same as #14493?

**Comment by edewit** [comment]
fixed: https://github.com/keycloak/keycloak-ui/pull/3268
