### ISSUE TITLE
OAuth getting failed for the keycloak version 19.0.0

### ISSUE THREAD

**Issue by meghanaph** [keycloak/keycloak#14427]
### Describe the bug

I have the same issue when I am using the latest keycloak version(19.0.2) for SSO and for the keyclaok with lower version(15.0.2) there is no such issue login was possible without any error logs

Once I click on sign in with oauth I am redirected with this error

"login.OAuthLogin(missing saved state)"

![grafana](https://user-images.githubusercontent.com/104889038/190323494-fd82ea4c-92d6-4998-b2b6-290dd450c2b3.jpg)

### Version

19.0.2

### Expected behavior

Once the authentication is done with the keycloak it must redirect back to the dashboard page

### Actual behavior

grafana auth by keycloak I am getting the following error

"login.OAuthLogin(get info from generic_oauth)"

**Comment by sschu** [comment]
Can you check the specific error in the server log like error screen suggests?

**Comment by stianst** [comment]
Closing this one as there is no indication it is a bug in Keycloak, but looks more like something happening on the Grafana side. Feel free to re-open if you can provide more information, and something that suggests the issues is on the Keycloak side.
