### ISSUE TITLE
Don’t trust Host header for redirection. Use whitelists of domain/host names for redirection.

### ISSUE THREAD

**Issue by prakash1** [keycloak/keycloak#14422]
### Describe the bug

1. Goto forgot password
2.Change the host to bing.com in the forgot password request and send the request
4.Itis observed that tampered host is reflecting in response

Please provide a solution fix the same.

Thanks,
Prakash

### Version

15.0.1

**Comment by darius-m** [comment]
The same issue was reported in #13966. I'm not sure what settings should be set in your Keycloak version, but you can set up a reverse proxy that overrides the header before sending the request to the backend.

**Comment by stianst** [comment]
Please check the documentation here:
https://www.keycloak.org/server/hostname

**Comment by stianst** [comment]
@pedroigor don't we already require hostname to be set in prod mode? If not we should consider that.

**Comment by pedroigor** [comment]
@stianst I thought I had replied to this one. We do force the `hostname` to be set when running in production mode. But I think this one is related to legacy as the reported version is `15.0.1`.

@prakash1 Could you please provide more details like which client you are using to authenticate the user? If you are using the admin console client, you should for a hostname using `hostname-admin` or set a specific URL to the `root url` of your client.

**Comment by prakash1** [comment]
Hi @pedroigor ,

We are using keycloak admin console client. Please find below screenshots for more infos.

KeyCloak adminconsole portal:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/4908652/192942759-5ddddc49-cc3c-4b38-ad7c-134a2e8362b5.png">

Application login screen forgot password link: 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/4908652/192943504-c03aa6ec-4cd7-48d3-a931-36c7a36a22d5.png">

Host manipulation in request:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/4908652/192944563-59e5e65a-c861-4ae0-8635-d5e5f3410278.png">

<img width="938" alt="Host_Header_manip3" src="https://user-images.githubusercontent.com/4908652/192944940-5ffa7acb-dfa8-4813-9f4a-48a7dc416c3b.png">




Thanks,
Prakash

**Comment by stianst** [comment]
@prakash1 did you check out the hostname guide as I mentioned? Configuring that is a must in production deployments.

**Comment by pedroigor** [comment]
Closing because the `hostname` must be set as per @stianst comments.
