### ISSUE TITLE
User is not getting loggedout in external application if it is disabled in keycloak

### ISSUE THREAD

**Issue by prakash1** [keycloak/keycloak#14420]
### Describe the bug

We are using KeyCloak as an IDM for our application. We are facing some below security issues. Please provide a resolution at earliest possible.

1> After successful login in our application, the user is disabled in KeyCloak

Steps : 

User say 'rahul' loggged into application.
Admin logged into Keycloak and disabled the user 'rahul'.
Check if 'rahul' is able to perform any action on its current logged in session. The user can do all actions. This is a security issue.

2> After successful login in our application, if a role of the user is changed in KeyCloak

Steps :

User say 'rahul' loggged into application.
Admin logged into Keycloak and updated a role of the user 'rahul'.
Check if 'rahul' is able to perform any action related to the updated role on its current logged in session. The user can not do all actions related to the updated role. This is a security issue.

3> After successful login in our application, if all active sessions are logged out in KeyCloak

Steps :

User say 'rahul' loggged into application.
Admin logged into Keycloak and logged out active sessions in KeyCloak.
Check if 'rahul' is able to perform any action on its current logged in session. The user can do all actions. This is a security issue.

Thanks,
Prakash

### Version

15.0.1

### Expected behavior

There should be a way to communicate to the application that user is disabled, deleted or session invalidated, so that application can logout the user.

**Comment by lexcao** [comment]
> Check if 'rahul' is able to perform any action on its current logged in session. The user can do all actions. This is a security issue.

Do you mean the user can do any actions with access token which issued before being disabled?

How do you verify the access token?

**Comment by prakash1** [comment]
We have created one layer called identity service which delegates the credential verification to KeyCloak. Once keycloak validates a give a success response, we generate another JWT token. So, the issued keycloak access token is still valid.

**Comment by lexcao** [comment]
> So, the issued keycloak access token is still valid.

Yes, it is expected.
1. When a user login from Keycloak with issued JWT(let's say `jwt_a`)
2. Identity Service would verify the JWT with the user(with `jwt_a`)
3. When disabling a user from Keycloak admin, the issued JWT would not be revoked
4. The `jwt_a` is still a verified JWT by the Identity Service.

How to resolve this?
There are 2 suggestions, and you can also refer to [this](https://stackoverflow.com/questions/31919067/how-can-i-revoke-a-jwt-token).

Solution 1:
* Make your expiration of the access token as short as possible and then revoke the refresh token.

Solution 2:
* Check with the JWT block list for your Identity Service
* Identity Service should register an Admin URL endpoint to receive revocation policy from Keycloak, see [docs](https://www.keycloak.org/docs/latest/securing_apps/#admin-url-configuration) for detail.
* Mark the associated JWT to the block list
* every time verifying the JWT, it should check with the block list as well

**Comment by mposolda** [comment]
@lexcao Thanks for your analysis!

I am closing as this does not look like Keycloak bug
