### ISSUE TITLE
Require special characters validations in group name, first name and last name field

### ISSUE THREAD

**Issue by prakash1** [keycloak/keycloak#14423]
### Describe the bug

We are able to add a new user with special characters in first name and last name field. Also, able to new group with special characters. This may lead security issue.

Thanks,
Prakash

### Version

15.0.1

**Comment by prakash1** [comment]
Please provide an update.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by jonkoops** [comment]
> This may lead security issue.

Do you have anything to back up this claim?
