### ISSUE TITLE
Null pointer exception ERROR when trying to use custom jgroups stack for infinispan

### ISSUE THREAD

**Issue by Shiva19908** [keycloak/keycloak#14435]
### Describe the bug

Use the below inifinispan cache config file to start Keycloak server without setting _--cache-stack_ option as it would override the custom stack. The cluster formation also succeeds (2 nodes). However, in the logs on both the nodes we can see an ERROR log saying a null pointer exception occurred in JChannels as shown below. However, we do not observer this when using the OOB available stacks i.e., we do not see this error when using _--cache-stack_ option.

`2022-09-15 15:02:14,307 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2022-09-15 15:02:14,330 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-09-15 15:02:14,344 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2022-09-15 15:02:14,607 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
2022-09-15 15:02:14,874 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel 'ADP-IAM' with stack 'encrypt-tcp'
GMS: address=eric-sec-access-mgmt-0-216, cluster=ADP-IAM, physical address=192.168.147.80:7600
2022-09-15 15:02:20,652 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ADP-IAM: [eric-sec-access-mgmt-0-216|0] (1) [eric-sec-access-mgmt-0-216]
**2022-09-15 15:02:20,699 ERROR [org.jgroups.JChannel] (keycloak-cache-init) JGRP000016: exception in channelConnected callback: java.lang.NullPointerException**
2022-09-15 15:02:20,699 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel 'ADP-IAM' local address is 'eric-sec-access-mgmt-0-216', physical addresses are '[192.168.147.80:7600]'
2022-09-15 15:02:21,306 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: eric-sec-access-mgmt-0-216, Site name: null`

`<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:13.0 http://www.infinispan.org/schemas/infinispan-config-13.0.xsd"
        xmlns="urn:infinispan:config:13.0">

    <jgroups>
        <stack name="encrypt-tcp" extends="tcp">
            <TCP bind_port="7600"/>
            <dns.DNS_PING dns_query="eric-sec-access-mgmt.name-headless"
                          stack.combine="REPLACE"
                          stack.position="MPING"/>
            <FD_SOCK start_port="57600"
                     stack.combine="REPLACE"
                     stack.position="FD_SOCK"/>
            <SSL_KEY_EXCHANGE keystore_name="/opt/jboss/rundir-safe/ha.keystore"
                              keystore_password="${env.KEYSTORE_SECRET}"
                              session_verifier_class="org.jgroups.protocols.CertficateCNMatcher"
                              session_verifier_arg="CN=eric-sec-access-mgmt"
                              port="2157"
                              ssl_protocol="TLSv1.2"
                              stack.combine="INSERT_AFTER"
                              stack.position="VERIFY_SUSPECT"/>
            <ASYM_ENCRYPT asym_keylength="2048"
                          change_key_on_leave="true"
                          change_key_on_coord_leave="true"
                          use_external_key_exchange="true"
                          sym_keylength="128"
                          sym_algorithm="AES"
                          asym_algorithm="RSA"
                          stack.combine="INSERT_AFTER"
                          stack.position="SSL_KEY_EXCHANGE"/>
            <pbcast.GMS max_join_attempts="5"
                        join_timeout="30000"
                        stack.combine="REPLACE"
                        stack.position="pbcast.GMS"/>
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport stack="encrypt-tcp"
                   lock-timeout="60000"
                   cluster="ADP-IAM"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <distributed-cache name="sessions" owners="${env.CACHE_OWNERS:2}">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="${env.CACHE_OWNERS:2}">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="${env.CACHE_OWNERS:2}">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="${env.CACHE_OWNERS:2}">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="${env.CACHE_OWNERS:2}">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="${env.CACHE_OWNERS:2}">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="actionTokens" owners="${env.CACHE_OWNERS:2}">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>`

### Version

Keycloak Quarkus 18.0.0

### Expected behavior

We should not see null pointer exception error
**2022-09-15 15:02:20,699 ERROR [org.jgroups.JChannel] (keycloak-cache-init) JGRP000016: exception in channelConnected callback: java.lang.NullPointerException**

### Actual behavior

we see null pointer exception error
**2022-09-15 15:02:20,699 ERROR [org.jgroups.JChannel] (keycloak-cache-init) JGRP000016: exception in channelConnected callback: java.lang.NullPointerException**

### How to Reproduce?

run keycloak quarkus 18.0.0 with the above cache config.

**Comment by Shiva19908** [comment]
This is a bug on Infinispan and was fixed by https://issues.redhat.com/browse/ISPN-13836 in version 13.0.10.Final. So, I believe the fix would be to uplift infinispan version to 13.0.10.Final or latest.
Thanks,
Shiva

**Comment by pedroigor** [comment]
@Shiva19908 Thanks for the information. Saved us some time.

I'm closing this one because the next major should be based on ISPN 13.0.10+.
