### ISSUE TITLE
Missing variable declaration in AuthZ JS

### ISSUE THREAD

**Issue by Mario-Eis** [keycloak/keycloak#14445]
### Describe the bug

As far as I can tell, there are two critical bugs in keycloak-authz.js.

**First:** 
When calling entitlement(), a function is set as the new then() function and init() is called.. init() starts an async request. When the script is used as stated in the docs, an error happens, because the async request is not finished in time. Because its result is used in the set then-function.

This failes:
```
var keycloak = ... // obtain a Keycloak instance from keycloak.js library
var authorization = new KeycloakAuthorization(keycloak);
authorization.entitlement('my-resource-server-id').then(function (rpt) {
    // onGrant callback function.
    // If authorization was successful you'll receive an RPT
    // with the necessary permissions to access the resource server
});
```

This would work. But ohhh boy...
```
var keycloak = ... // obtain a Keycloak instance from keycloak.js library
var authorization = new KeycloakAuthorization(keycloak);
var bla = authorization.entitlement('my-resource-server-id');
setTimeout(() => {
    bla.then(function (rpt) {

    });
}, 300);
```

**Second:** 
There is a syntax error in line 201!
is should be `var j = 0`!

This part of the code iterates the scopes. So when using a permission request like in the docs, the whole script fails.

```
const authorizationRequest = {
   "permissions": [
       {
           "id" : "Some Resource",
           "scopes" : ["view", "edit"]
       }
   ]
}
```

![2022-09-15 23_05_36-DevTools - localhost_2000_home - Opera](https://user-images.githubusercontent.com/17924929/190508675-4fdbd81c-d4b3-4231-a51f-dbfe7e159163.png)

### Version

19.0.2

**Comment by pedroigor** [comment]
@Mario-Eis Are you able to send a fix?

**Comment by jonkoops** [comment]
Yeah, this sounds like a legitimate issue, it probably stems from the fact that [Strict Mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) was enabled at some point. The fix for this should be easy enough by adding a variable declaration.

**Comment by jonkoops** [comment]
@Mario-Eis I split this into two separate issues (see #14562). You might want to subscribe to notifications there as well.
