### ISSUE TITLE
Client-secret with special character (+) for authorization is failing in 19.0.2

### ISSUE THREAD

**Issue by joggeli34** [keycloak/keycloak#14441]
### Describe the bug

Since the upgrade to 19.0.2, the client secret containing a + is rejected. All works fine when recrating a secret without a special caracter.

In 19.0.1 the secret was accepted.

### Version

19.0.2-legacy

**Comment by sschu** [comment]
How do you encode the client secret / are you using some library to pass it?

**Comment by joggeli34** [comment]
We us quarkus with `io.quarkus:quarkus-keycloak-authorization` for all the authorization

**Comment by lexcao** [comment]
Hi, @joggeli34 
How do you pass the client secret, form data or http baisc header?
Could you please provide some example requests?

**Comment by joggeli34** [comment]
Today we noticed that we have also problems with other secrets after we updated the authorization client without changing the existing secret. But we don't know when it happens.
When we update the client and add a new secret, it works afterwards again. 
So I think it has nothing to do with the + sign, rather with the client-secret that can get corrupted somehow after updating the client.

**Comment by joggeli34** [comment]
Successful: 33, 36
Failed: 32, 34

Just for completeness, we currently use keycloak 19.0.3 und for the client application Quarkus 2.12.2

**Comment by mposolda** [comment]
Adding to Keycloak 22 for now as this may deserve some investigation.

**Comment by adrhine** [comment]
Hello @joggeli34 , I have been trying to reproduce this issue but I am not having much luck. I've attempted with the latest version of KC as well as the version you mentioned in your latest comment (19.0.3). 

I've tried including the "+" character in my secret (a single "+", as well as several "+"). I've tried a variety of secret lengths (28-38 chars - this includes the 32 and 34 you had mentioned had broken for you). 

I wasn't sure exactly when you had encountered an error, but I am guessing it is during client authentication? I have been trying with the client_credentials grant.

Any further information would be greatly appreciated (perhaps you could a particular secret that you see the error with? are there any associated logs too?)

**Comment by pedroigor** [comment]
This issue should be related to https://github.com/keycloak/keycloak/issues/11908. The fix is https://github.com/keycloak/keycloak/pull/12486.

Basically, there was a mismatch when using different versions of Keycloak at the server and the client side (`quarkus-keycloak-authorization`).
