### ISSUE TITLE
Identity Broker allows user-creation with invalid username

### ISSUE THREAD

**Issue by matrium0** [keycloak/keycloak#14447]
### Describe the bug

When using Keycloak as an Identity Broker the default behavior is to open the "Update Account Information" page if information (like username or email) was not provided in the openid-connect/saml response.

The problem we are experiencing with this page is that you can use it to create invalid usernames. e.g. "asdf/ölkj" (notice the SLASH) - now you have created an account that can no longer be modified because both are true:
a) you are not allowed to save the account, since the username field is invalid (not even through Admin-UI)
b) you are not allowed to change the username, since it is read only

The problem in our case is that the backing IDP returns the username like this and no email. So if the user just leaves the username as it is he has created a broken account and can't pass the e-mail validation or anything else that requires saving it. Ideally we WOULD want to use the "sub"-claim of the IDP, but just strip invalid characters.

### Version

15

### Expected behavior

The username validation-rules on the "update account information" page should match other account-creation-possibilities. The page should not allow you to create an account with an invalid username.

### Actual behavior

It is possible to create an account with an invalid username through that page.

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.
