### ISSUE TITLE
Code already in used for user session and client error

### ISSUE THREAD

**Issue by edumanish** [keycloak/keycloak#14449]
### Describe the bug

In our application we are supporting Kerberos authentication through keycloak. in browser everything is working fine. when we try to execute same behavior using curl script, we can get the authorization code using _(<server>/auth/realms/kerberos/protocol/openid-connect/auth?reponse_type=code&client_id=<sericeName>&scope=<values>&state=XXXXXXX&redirect_uri=<server>/login/oauth2/code/kerberos&nonce=XXXXXXX_) but while getting access token (_<server>/login/oauth2/code/kerberos?state=XXXXX&session_stated=XXXXX&code=XXXX_) we are getting **Code already in used for user session and client error**. Find the below screenshots for more details.

![KeycloakBUG](https://user-images.githubusercontent.com/113010936/190571299-7ee1fdb9-a865-4352-a13c-6311121ff205.JPG)

### Version

keycloak-11.0.2

**Comment by stianst** [comment]
Not sure what you mean by running the same code through a curl script. Authorization code flow is not designed to be used for a native application, it is intended to be used through a user-agent only. 

Take a look at https://www.rfc-editor.org/rfc/rfc8252#section-4.1 as an example.

**Comment by stianst** [comment]
I'm going to close this one as I can't see a valid bug here. If you are getting the error that the code has been used twice, that is because it's been used twice.

**Comment by edumanish** [comment]
HI Please,
code has not been used twice. Please review the Issue description.
Can you Look into this issue again.?

**Comment by ELISHELL** [comment]
I have the same problem. How did you solve it? Can you help me?
我遇到了同样的问题，你是怎么解决的，能帮帮我吗？
