### ISSUE TITLE
Only "/*" url pattern can be used in web.xml with tomcat adapter 19.0.2

### ISSUE THREAD

**Issue by gaorongfu** [keycloak/keycloak#14456]
### Describe the bug

I tested with tomcat version 8.5.82 and 8.5.78. 
Only "/*" can work and the others due to 403 forbidden, such as :
`
<security-constraint>
        <web-resource-collection>
            <web-resource-name>admin</web-resource-name>
			<url-pattern>/back/*</url-pattern>
		</web-resource-collection>
        <auth-constraint>
            <role-name>super-admin</role-name>
            <role-name>user</role-name>
        </auth-constraint>
    </security-constraint>
`
and I test many times with different patterns , all is 403.
![image](https://user-images.githubusercontent.com/10938991/190636260-4be5cf8d-6568-49cb-8c8f-3ae3c5512c4c.png)

### Version

19.0.2

### Expected behavior

In my web application , only some resources should be access after login . I need protected them with special url patterns.

**Comment by gaorongfu** [comment]
`<security-constraint>
        <web-resource-collection>
            <web-resource-name>admin</web-resource-name>
			<url-pattern>/back/*</url-pattern>
		</web-resource-collection>
        <auth-constraint>
            <role-name>super-admin</role-name>
            <role-name>user</role-name>
        </auth-constraint>
    </security-constraint>`

**Comment by lexcao** [comment]
Have you tried this [doc](https://www.keycloak.org/docs/latest/securing_apps/#_tomcat_adapter)

Could you please provide more details about
* any server logs from your backend
* detailed configuration file your Tomcat server using

**Comment by gaorongfu** [comment]
Sure, I tried as the document of laster version  just you remind of. these is the context segment in my tomcat server.xml:
`<Context path="/sc" docBase="/data/webapps/safecloud" defaultSessionTimeOut="28800" reloadable="false">
        <Valve className="org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve"/>
</Context>
`
And tomcat listener port change to 8180, other settings are all default by tomcat.

In tomcat logs, only these two line is related of keycloak:
16-Sep-2022 20:06:27.213 INFO [http-nio-8180-exec-3] org.keycloak.adapters.authorization.PolicyEnforcer.configurePaths No path provided in configuration.
16-Sep-2022 20:06:27.214 INFO [http-nio-8180-exec-3] org.keycloak.adapters.authorization.PolicyEnforcer.configureAllPathsForResourceServer Querying the server for all resources associated with this application.

I think it is very eary to reproduce: follow the document you remind of , then change url-pattern to any other , like "/back/*". And restart tomcat, you can see the 403 error when access by browser.

My webapp is run from keycloak 9.0.0 for years. And upgrade to keycloak 18.0.0 several months, It's all ok. This error only occured on version 19.

In old version of keycloak(9 or 18), my web.xml config is more free, it is below, but 403 error on version 19 . I tried many hours to found the reason, finally I found it only can work when remove url-pattern items and only left one, and must change to "/*":
`<security-constraint>
        <web-resource-collection>
            <web-resource-name>SafecloudPlatform</web-resource-name>
            <url-pattern>/alipay/index</url-pattern>
            <url-pattern>/back/*</url-pattern>
            <url-pattern>/center/*</url-pattern>
            <url-pattern>/centre/*</url-pattern>
            <url-pattern>/chart/*</url-pattern>
            <url-pattern>/index</url-pattern>
            <url-pattern>/inspection/*</url-pattern>
            <url-pattern>/journal/*</url-pattern>
            <url-pattern>/os/*</url-pattern>
            <url-pattern>/pay/*</url-pattern>
            <url-pattern>/personal/*</url-pattern>
            <url-pattern>/report/*</url-pattern>
            <url-pattern>/svg/*</url-pattern>
            <url-pattern>/wxpay/index</url-pattern>
            <url-pattern>/weixin/relogin</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <role-name>super-admin</role-name>
            <role-name>channel-admin</role-name>
            <role-name>customer-admin</role-name>
            <role-name>user</role-name>
        </auth-constraint>
    </security-constraint>

    <login-config>
        <auth-method>BASIC</auth-method>
        <realm-name>this is ignored currently</realm-name>
    </login-config>

    <security-role>
        <role-name>super-admin</role-name>
    </security-role>
    <security-role>
        <role-name>channel-admin</role-name>
    </security-role>
    <security-role>
        <role-name>customer-admin</role-name>
    </security-role>
    <security-role>
        <role-name>user</role-name>
    </security-role>`

**Comment by mposolda** [comment]
I am closing as adapters are going to be entirely removed soon.
