### ISSUE TITLE
Unable to read id token from OIDC provider

### ISSUE THREAD

**Issue by ChrisMOxon** [keycloak/keycloak#14474]
### Describe the bug

Hi,

I'm having an issue where we are unable to view the id token from an oidc provider as expected here - https://127.0.0.1:8443/realms/master/broker/oidc/token

The error message is -

`2022-09-09 11:00:11,742 ERROR [org.keycloak.services.resources.IdentityBrokerService] (executor-thread-819) Invalid token.
2022-09-09 11:00:11,742 WARN  [org.keycloak.events] (executor-thread-819) type=IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR, realmId=858d1a6f..., clientId=null, userId=null, ipAddress=127.0.0.1, error=Invalid token.`

The token is definitely valid as the user is able to login fine.  The keycloak token has the required permissions to view the OIDC id token -

```
`exp	16627166389/9/2022, 10:43:58 AM

iat	16627165789/9/2022, 10:42:58 AM

auth_time	1662716346

jti	6fcc922...

iss	https://127.0.0.1:8443/realms/master

aud	

0	broker

1	account

sub	b53ce2a2...

typ	Bearer

azp	account-console

nonce	82c93414...

session_state	bd9a7974...

acr	0

resource_access	

broker	

roles	

0	read-token

account	

roles	

0	manage-account

1	manage-account-links

scope	openid broker_read_token email profile

sid	bd9a7974...

email_verified	false`
```

I've tried raising this on the discourse group but got no response -

https://keycloak.discourse.group/t/struggling-to-read-the-id-token-from-azure-errormessage-invalid-token/17319

### Version

19.0.0

### Expected behavior

User is able to view the id token received from the oidc provider

### Actual behavior

User receives {“errorMessage”:“Invalid token.”}

### How to Reproduce?

Clean install of 19.0.0 running in dev mode with the appropriate permission for reading tokens mapped.

**Comment by lexcao** [comment]
Hi, could you please provide the request to the endpoint `https://127.0.0.1:8443/realms/master/broker/oidc/token`?

From my understanding, this token endpoint needs an access token that belonged to the target user.
Maybe the error is an invalid token for the access token.

**Comment by sschu** [comment]
Did you also enable storing tokens readable in the IDP config?

**Comment by jbman** [comment]
On Keycloak 18.0.2 I just observed that the response of [Retrieving external IDP tokens](https://www.keycloak.org/docs/latest/server_development/#retrieving-external-idp-tokens) 
GET /realms/{realm}/broker/{provider_alias}/token is not as expected.

It contains the IdP ID token under JSON key "access_token" and the access token (if any provided) is available under key "id_token". Somewhere the tokens get mixed up.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

**Comment by mihkelpoldoja** [comment]
Has some find a solution/workaround for this? Still happens in version 21.

**Comment by pedroigor** [comment]
Not sure if the issue makes sense because Keycloak stores the whole access token response from the OP. As a result, you'll get the same response.

**Comment by rizkyyogamitrais** [comment]
Hi guys, has some find a solution/workaround for this? Still happens in version 26.

I've got this error `{“errorMessage”:“Invalid token.”}` when requesting token via grant type authorization_code. But when I requesting token via grant type password it works.

I've checked inside the token body and decode it seems identical. and I've checked the keycloak code and it seems something need to be updated in this method related to this issue. Please let me know if you need any detail to debug the issue. Thanks.
