### ISSUE TITLE
Unable to send clientSecret 

### ISSUE THREAD

**Issue by Tung4** [keycloak/keycloak#14479]
### Description

import Keycloak from "keycloak-js";
let kcInstance = new Keycloak({
  url: "your-url-login",
  realm: "master",
  clientId: "web-auth",
});

kcInstance.clientSecret = "";
export default kcInstance;

I have problem integrating clientSecret in project
how to send clientSecret?

**Comment by ZhangWeike2000** [comment]
use Keycloak JavaScript adapter ,Authentication and authorization services,The client secret parameter is not carried why??
const KEYCLOAK_CONFIG = {
  url: 'your-url-login',
  realm: 'master',
  clientId: 'clientId',
  clientSecret: 'xxxxx'
}
const keycloak = new Keycloak(KEYCLOAK_CONFIG)
const authenticated = await keycloak.init({
      onLoad: 'login-required'
})
