### ISSUE TITLE
Need to create 4 caches manually to get it working (clients, groups, roles,realms)

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#14482]
### Describe the bug

Followed doc  HotRod Map Storage: How To and Q&A #12010

Got error 

org.infinispan.HOTROD] (HotRod-client-async-pool-1-1) ISPN004005: Error received from the server: org.infinispan.server.hotrod.CacheNotFoundException: Cache with name 'realms' not found amongst the configured caches

1. Download KC 19.0.2 
wget https://github.com/keycloak/keycloak/archive/refs/tags/19.0.2.zip

2. started infinispan docker
docker run -it -p 11222:11222 -e USER="admin" -e PASS="admin" quay.io/infinispan/server:13.0.10.Final

3. Compile KC 19.0.2
mvn clean install -DskipTests

---> Success

4. Check infinispan docker caches
---> empty

5. Run command 

mvn -pl testsuite/utils \
-Pkeycloak-server,map-storage \
-Dkeycloak.authSession.map.storage.provider=hotrod \
-Dkeycloak.client.map.storage.provider=hotrod \
-Dkeycloak.clientScope.map.storage.provider=hotrod \
-Dkeycloak.role.map.storage.provider=hotrod \
-Dkeycloak.realm.map.storage.provider=hotrod \
-Dkeycloak.group.map.storage.provider=hotrod \
-Dkeycloak.user.map.storage.provider=hotrod \
-Dkeycloak.authorization.map.storage.provider=hotrod \
-Dkeycloak.userSession.map.storage.provider=hotrod \
-Dkeycloak.loginFailure.map.storage.provider=hotrod \
-Dkeycloak.singleUseObject.map.storage.provider=hotrod \
-Dkeycloak.eventStore.map.storage.provider=hotrod \
-Dkeycloak.connectionsHotRod.embedded=false \
-Dkeycloak.connectionsHotRod.configureRemoteCaches=true \
-Dkeycloak.connectionsHotRod.port=11222 \
-Dkeycloak.connectionsHotRod.enableSecurity=true \
-Dkeycloak.connectionsHotRod.reindexCaches=all \
exec:java

mvn -f quarkus/server/pom.xml compile quarkus:dev -Dquarkus.args="start-dev --storage=hotrod --storage-hotrod-host=localhost --storage-hotrod-port=11222 --storage-hotrod-username=admin --storage-hotrod-password=admin" -Dkc.config.args="start-dev;;--storage=hotrod;;" | more
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< org.keycloak:keycloak-quarkus-server-app >--------------
[INFO] Building Keycloak Quarkus Server App 19.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ keycloak-quarkus-server-app ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ keycloak-quarkus-server-app ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ keycloak-quarkus-server-app ---
[INFO] Executing: /bin/sh -c cd '/home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/quarkus/server' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/quarkus/server
[INFO] Storing buildNumber: UNKNOWN at timestamp: 1663578407289
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

[INFO] Executing: /bin/sh -c cd '/home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/quarkus/server' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/quarkus/server
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ keycloak-quarkus-server-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ keycloak-quarkus-server-app ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:2.7.6.Final:dev (default-cli) @ keycloak-quarkus-server-app ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:3.1.0:testResources) @ keycloak-quarkus-server-app
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/quarkus/server/src/test/resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile) @ keycloak-quarkus-server-app
[INFO] No sources to compile
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-quarkus-server:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-services:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-js-adapter:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-common:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-core:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-crypto-default:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-server-spi:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-server-spi-private:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-themes:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-saml-core-public:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-saml-core:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-model-jpa:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-model-infinispan:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-model-legacy:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-model-legacy-private:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-model-legacy-services:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-authz-policy-common:19.0.2 will not be hot-reloadable
[WARNING] [io.quarkus.bootstrap.devmode.DependenciesFilter] Local Quarkus extension dependency org.keycloak:keycloak-kerberos-federation:19.0.2 will not be hot-reloadable
2022-09-19 11:06:49,997 WARN  [org.keycloak.common.Profile] (build-34) Experimental feature enabled: map_storage
2022-09-19 11:06:50,678 WARN  [io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor] (build-15) Hibernate ORM is disabled because no JPA entities were found
2022-09-19 11:06:51,765 WARN  [org.keycloak.common.Profile] (Quarkus Main Thread) Experimental feature enabled: map_storage
2022-09-19 11:06:51,807 WARN  [org.keycloak.models.DeploymentStateProviderFactory] (Quarkus Main Thread) Version seed for deployment state set with a random number. Caution: This can lead to unstable operations when serving resources from the cluster without a sticky loadbalancer or when restarting nodes. Set the 'storage-deployment-state-version-seed' option with a secret seed to ensure stable operations.
2022-09-19 11:06:51,810 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (Quarkus Main Thread) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: false
2022-09-19 11:06:51,929 INFO  [org.keycloak.common.crypto.CryptoIntegration] (Quarkus Main Thread) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
2022-09-19 11:06:52,190 WARN  [org.keycloak.services.DefaultComponentFactoryProviderFactory] (Quarkus Main Thread) No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
2022-09-19 11:06:52,662 INFO  [org.infinispan.HOTROD] (Quarkus Main Thread) ISPN004021: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
2022-09-19 11:06:52,667 WARN  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-1) ISPN004005: Error received from the server: org.infinispan.server.hotrod.CacheNotFoundException: Cache with name 'realms' not found amongst the configured caches
2022-09-19 11:06:52,712 WARN  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-1) ISPN004005: Error received from the server: org.infinispan.commons.CacheConfigurationException: ISPN005053: The supplied configuration for cache 'realms' must contain a single cache configuration for it: 
infinispan>
    <cache-container>
       
        <distributed-cache name="auth-sessions" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodRootAuthenticationSessionEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="clients" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodClientEntity</indexed-entity>
                    <indexed-entity>kc.HotRodAttributeEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="client-scopes" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodClientScopeEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="groups" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodGroupEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="roles" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodRoleEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="users" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodUserEntity</indexed-entity>
                    <indexed-entity>kc.HotRodAttributeEntity</indexed-entity>
                    <indexed-entity>kc.HotRodUserFederatedIdentityEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="user-login-failures" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodUserLoginFailureEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="realms" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodRealmEntity</indexed-entity>
                    <indexed-entity>kc.HotRodComponentEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="user-sessions" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodUserSessionEntity</indexed-entity>
                    <indexed-entity>kc.HotRodAuthenticatedClientSessionEntityReference</indexed-entity>
                    <indexed-entity>kc.HotRodStringPair</indexed-entity>
                    <indexed-entity>kc.HotRodAuthenticatedClientSessionEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="authz" mode="SYNC">
            <encoding media-type="application/x-protostream"/>
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodResourceServerEntity</indexed-entity>
                    <indexed-entity>kc.HotRodResourceEntity</indexed-entity>
                    <indexed-entity>kc.HotRodScopeEntity</indexed-entity>
                    <indexed-entity>kc.HotRodPolicyEntity</indexed-entity>
                    <indexed-entity>kc.HotRodPermissionTicketEntity</indexed-entity>
                    <indexed-entity>kc.HotRodStringPair</indexed-entity>
                </indexed-entities>
            </indexing>
        </distributed-cache>
        <distributed-cache name="auth-events" mode="SYNC">
            <encoding media-type="application/x-protostream"/>
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodAuthEventEntity</indexed-entity>
                </indexed-entities>
            </indexing>
        </distributed-cache>
        <distributed-cache name="admin-events" mode="SYNC">
            <encoding media-type="application/x-protostream"/>
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodAdminEventEntity</indexed-entity>
                </indexed-entities>
            </indexing>
        </distributed-cache>
        <distributed-cache name="single-use-objects" mode="SYNC">
            <indexing>
                <indexed-entities>
                    <indexed-entity>kc.HotRodSingleUseObjectEntity</indexed-entity>
                </indexed-entities>
            </indexing>
            <encoding media-type="application/x-protostream"/>
        </distributed-cache>
    </cache-container>
</infinispan>

 

### Version

19.0.2

### Expected behavior

It should work first shot

### Actual behavior

It is generating error 

org.infinispan.HOTROD] (HotRod-client-async-pool-1-1) ISPN004005: Error received from the server: org.infinispan.server.hotrod.CacheNotFoundException: Cache with name 'realms' not found amongst the configured caches

### How to Reproduce?

Steps provided above

**Comment by orivat** [comment]
Known  work-around:


It is possible to work-around this issue adding the 4 caches manually in infinispan console

1)  podman run -d --network host --name infinispan -e USER="admin" -e PASS="admin" quay.io/infinispan/server:12.1.7.Final
2) open infinispan console

3)  create manually 

clients
grouos
realms
roles

**Comment by mhajas** [comment]
Hello, what version of Infinispan are you using? Keycloak 19 only works with Infinispan 12.1.7. If you want to use Inifinispan 13.0.10 as it is in https://github.com/keycloak/keycloak/discussions/12010 you need to use the current main branch.

**Comment by orivat** [comment]
OK 

It is working fine with 12.1.7

Closing ticket

**Comment by orivat** [comment]
Closed
