### ISSUE TITLE
Indexing was not enabled on cache realms

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#14484]
### Describe the bug

Got error message 

[org.infinispan.HOTROD] ISPN004005: Error received from the server: org.infinispan.commons.CacheException: java.lang.IllegalStateException: Indexing was not enabled on cache realms

1. start docker
podman run -d --network host --name infinispan -e USER="admin" -e PASS="admin" quay.io/infinispan/server:12.1.7.Final

3. create caches on infinispan console 
groups
clients
roles
realms

4. Run command 

 mvn -pl testsuite/utils -Pkeycloak-server,map-storage -Dkeycloak.authSession.map.storage.provider=hotrod -Dkeycloak.client.map.storage.provider=hotrod -Dkeycloak.clientScope.map.storage.provider=hotrod -Dkeycloak.role.map.storage.provider=hotrod -Dkeycloak.realm.map.storage.provider=hotrod -Dkeycloak.group.map.storage.provider=hotrod -Dkeycloak.user.map.storage.provider=hotrod -Dkeycloak.authorization.map.storage.provider=hotrod -Dkeycloak.userSession.map.storage.provider=hotrod -Dkeycloak.loginFailure.map.storage.provider=hotrod -Dkeycloak.singleUseObject.map.storage.provider=hotrod -Dkeycloak.eventStore.map.storage.provider=hotrod -Dkeycloak.connectionsHotRod.embedded=false -Dkeycloak.connectionsHotRod.configureRemoteCaches=true -Dkeycloak.connectionsHotRod.port=11222 -Dkeycloak.connectionsHotRod.enableSecurity=true -Dkeycloak.connectionsHotRod.reindexCaches=all exec:java

### Version

19.0.2

### Actual behavior

 mvn -pl testsuite/utils -Pkeycloak-server,map-storage -Dkeycloak.authSession.map.storage.provider=hotrod -Dkeycloak.client.map.storage.provider=hotrod -Dkeycloak.clientScope.map.storage.provider=hotrod -Dkeycloak.role.map.storage.provider=hotrod -Dkeycloak.realm.map.storage.provider=hotrod -Dkeycloak.group.map.storage.provider=hotrod -Dkeycloak.user.map.storage.provider=hotrod -Dkeycloak.authorization.map.storage.provider=hotrod -Dkeycloak.userSession.map.storage.provider=hotrod -Dkeycloak.loginFailure.map.storage.provider=hotrod -Dkeycloak.singleUseObject.map.storage.provider=hotrod -Dkeycloak.eventStore.map.storage.provider=hotrod -Dkeycloak.connectionsHotRod.embedded=false -Dkeycloak.connectionsHotRod.configureRemoteCaches=true -Dkeycloak.connectionsHotRod.port=11222 -Dkeycloak.connectionsHotRod.enableSecurity=true -Dkeycloak.connectionsHotRod.reindexCaches=all exec:java
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.keycloak:keycloak-quarkus-server:jar:19.0.2
[WARNING] 'dependencies.dependency.scope' for org.keycloak:keycloak-dependencies-admin-ui-wrapper:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ line 665, column 28
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.keycloak:keycloak-testsuite-utils:jar:19.0.2
[WARNING] 'dependencies.dependency.scope' for org.keycloak:keycloak-dependencies-admin-ui-wrapper:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ line 55, column 20
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------< org.keycloak:keycloak-testsuite-utils >----------------
[INFO] Building Keycloak TestSuite Utils 19.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ keycloak-testsuite-utils ---
11:42:57,750 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.testsuite.TestPlatform] Using server tmp directory: /tmp/keycloak-server-11149475379034920872
11:42:57,751 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.testsuite.KeycloakServer] Using jboss.server.data.dir /tmp/keycloak-server-11149475379034920872/data
11:42:57,805 INFO  org.keycloak.testsuite.KeycloakServer.main() [io.undertow] starting server: Undertow - 2.2.14.Final
11:42:57,966 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.jboss.threads] JBoss Threads version 2.3.3.Final
11:42:58,497 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.common.crypto.CryptoIntegration] Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
11:42:58,517 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services] KC-SERVICES0001: Loading config from file:/home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/testsuite/utils/target/classes/META-INF/keycloak-server.json
11:42:58,702 WARN  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.common.Profile] Experimental feature enabled: map_storage
11:42:58,776 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.protocol.oidc.OIDCWellKnownProviderFactory] Overriding default OIDC well-known endpoint configuration with the options from file 'classpath:wellknown/oidc-well-known-config-override.json'
11:42:58,848 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.url.DefaultHostnameProviderFactory] Frontend: <request>, Admin: <frontend>, Backend: <request>
11:42:59,444 WARN  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services.DefaultComponentFactoryProviderFactory] No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
11:43:00,053 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.infinispan.HOTROD] ISPN004021: Infinispan version: Infinispan 'Taedonggang' 12.1.7.Final
11:43:00,066 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,067 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,068 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,157 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,158 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,158 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,213 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,213 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,213 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,269 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,270 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,270 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,325 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,325 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,325 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,383 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,383 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,383 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,437 INFO  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,437 INFO  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,437 INFO  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,486 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,486 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,486 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,536 INFO  HotRod-client-async-pool-1-2 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,537 INFO  HotRod-client-async-pool-1-2 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,537 INFO  HotRod-client-async-pool-1-2 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,586 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,586 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,586 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,636 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,636 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,636 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,688 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,688 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,688 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,739 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,739 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,739 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,789 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:43:00,789 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:43:00,789 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:43:00,829 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.models.map.storage.hotRod.connections.DefaultHotRodConnectionProviderFactory] Reindexing all caches. This can take a long time to complete. While the rebuild operation is in progress, queries might return fewer results.
11:43:00,899 WARN  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004005: Error received from the server: org.infinispan.commons.CacheException: java.lang.IllegalStateException: Indexing was not enabled on cache realms
java.lang.IllegalStateException: Indexing was not enabled on cache realms
11:43:00,904 INFO  org.keycloak.testsuite.KeycloakServer.main() [io.undertow] stopping server: Undertow - 2.2.14.Final
[WARNING] 
java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication()
    at org.jboss.resteasy.core.ConstructorInjectorImpl.constructOutsideRequest (ConstructorInjectorImpl.java:250)
    at org.jboss.resteasy.core.ConstructorInjectorImpl.construct (ConstructorInjectorImpl.java:209)
    at org.jboss.resteasy.core.providerfactory.Utils.createProviderInstance (Utils.java:102)
    at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.createProviderInstance (ResteasyProviderFactoryImpl.java:1385)
    at org.jboss.resteasy.core.ResteasyDeploymentImpl.createApplication (ResteasyDeploymentImpl.java:418)
    at org.jboss.resteasy.core.ResteasyDeploymentImpl.initializeObjects (ResteasyDeploymentImpl.java:265)
    at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal (ResteasyDeploymentImpl.java:137)
    at org.jboss.resteasy.core.ResteasyDeploymentImpl.start (ResteasyDeploymentImpl.java:121)
    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init (ServletContainerDispatcher.java:144)
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init (HttpServletDispatcher.java:42)
    at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed (LifecyleInterceptorInvocation.java:117)
    at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start (ManagedServlet.java:309)
    at io.undertow.servlet.core.ManagedServlet.createServlet (ManagedServlet.java:145)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call (DeploymentManagerImpl.java:588)
    at io.undertow.servlet.core.DeploymentManagerImpl$2.call (DeploymentManagerImpl.java:559)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call (ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call (ContextClassLoaderSetupAction.java:43)
    at io.undertow.servlet.core.DeploymentManagerImpl.start (DeploymentManagerImpl.java:601)
    at org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer.deploy (UndertowJaxrsServer.java:248)
    at org.keycloak.testsuite.KeycloakServer.start (KeycloakServer.java:448)
    at org.keycloak.testsuite.KeycloakServer.bootstrapKeycloakServer (KeycloakServer.java:253)
    at org.keycloak.testsuite.KeycloakServer.main (KeycloakServer.java:156)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.RuntimeException: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=96 returned server error (status=0x85): org.infinispan.commons.CacheException: java.lang.IllegalStateException: Indexing was not enabled on cache realms
java.lang.IllegalStateException: Indexing was not enabled on cache realms
    at org.keycloak.testsuite.TestPlatform.exit (TestPlatform.java:45)

**Comment by orivat** [comment]
There is a work-around.

Drop the option -Dkeycloak.connectionsHotRod.reindexCaches=all exec:java 

mvn -pl testsuite/utils -Pkeycloak-server,map-storage -Dkeycloak.authSession.map.storage.provider=hotrod -Dkeycloak.client.map.storage.provider=hotrod -Dkeycloak.clientScope.mastorage.provider=hotrod -Dkeycloak.role.map.storage.provider=hotrod -Dkeycloak.realm.map.storage.provider=hotrod -Dkeycloak.group.map.storage.provider=hotrod -Dkeycloak.user.map.storage.provider=hotrod -Dkeycloak.authorization.map.storage.provider=hotrod -Dkeycloak.userSession.map.storage.provider=hotrod -Dkeycloak.loginFailure.map.storage.provider=hotrod -Dkeycloak.singleUseObject.map.storage.provider=hotrod -Dkeycloak.eventStore.map.storage.provider=hotrod -Dkeycloak.connectionsHotRod.embedded=false -Dkeycloak.connectionsHotRod.configureRemoteCaches=true -Dkeycloak.connectionsHotRod.port=11222 -Dkeycloak.connectionsHotRod.enableSecurity=true  exec:java
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.keycloak:keycloak-quarkus-server:jar:19.0.2
[WARNING] 'dependencies.dependency.scope' for org.keycloak:keycloak-dependencies-admin-ui-wrapper:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ line 665, column 28
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.keycloak:keycloak-testsuite-utils:jar:19.0.2
[WARNING] 'dependencies.dependency.scope' for org.keycloak:keycloak-dependencies-admin-ui-wrapper:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ line 55, column 20
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------< org.keycloak:keycloak-testsuite-utils >----------------
[INFO] Building Keycloak TestSuite Utils 19.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ keycloak-testsuite-utils ---
11:59:43,554 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.testsuite.TestPlatform] Using server tmp directory: /tmp/keycloak-server-1375614092965538487
11:59:43,555 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.testsuite.KeycloakServer] Using jboss.server.data.dir /tmp/keycloak-server-1375614092965538487/data
11:59:43,617 INFO  org.keycloak.testsuite.KeycloakServer.main() [io.undertow] starting server: Undertow - 2.2.14.Final
11:59:43,782 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.jboss.threads] JBoss Threads version 2.3.3.Final
11:59:44,260 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.common.crypto.CryptoIntegration] Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
11:59:44,280 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services] KC-SERVICES0001: Loading config from file:/home/orivat/dev/keycloak_quarkus/keycloak-19.0.2/testsuite/utils/target/classes/META-INF/keycloak-server.json
11:59:44,557 WARN  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.common.Profile] Experimental feature enabled: map_storage
11:59:45,179 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.protocol.oidc.OIDCWellKnownProviderFactory] Overriding default OIDC well-known endpoint configuration with the options from file 'classpath:wellknown/oidc-well-known-config-override.json'
11:59:45,341 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.url.DefaultHostnameProviderFactory] Frontend: <request>, Admin: <frontend>, Backend: <request>
11:59:45,394 WARN  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.services.DefaultComponentFactoryProviderFactory] No system-wide ClusterProviderFactory found. Cannot send messages across cluster, thus disabling caching of components. Consider setting cachingForced option in single-node deployment.
11:59:45,987 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.infinispan.HOTROD] ISPN004021: Infinispan version: Infinispan 'Taedonggang' 12.1.7.Final
11:59:45,998 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:45,998 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:45,999 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,084 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,084 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,084 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,140 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,140 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,140 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,195 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,195 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,195 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,252 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,252 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,252 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,305 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,305 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,306 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,359 INFO  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,359 INFO  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,359 INFO  HotRod-client-async-pool-1-8 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,409 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,409 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,409 INFO  HotRod-client-async-pool-1-1 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,458 INFO  HotRod-client-async-pool-1-2 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,458 INFO  HotRod-client-async-pool-1-2 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,458 INFO  HotRod-client-async-pool-1-2 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,507 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,507 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,507 INFO  HotRod-client-async-pool-1-3 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,558 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,558 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,558 INFO  HotRod-client-async-pool-1-4 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,611 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,611 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,611 INFO  HotRod-client-async-pool-1-5 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,663 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,663 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,663 INFO  HotRod-client-async-pool-1-6 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,718 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
11:59:46,718 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004014: New server added(127.0.0.1:11222), adding to the pool.
11:59:46,718 INFO  HotRod-client-async-pool-1-7 [org.infinispan.HOTROD] ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
11:59:46,752 INFO  org.keycloak.testsuite.KeycloakServer.main() [org.keycloak.models.map.storage.hotRod.connections.DefaultHotRodConnectionProviderFactory] HotRod client configuration was successful.
Started Keycloak (http://localhost:8081/auth) in 3515 ms

**Comment by mhajas** [comment]
@orivat Have you enabled indexing on created caches? Here you can see XML config for each cache: https://github.com/keycloak/keycloak/tree/main/model/map-hot-rod/src/main/resources/config

I am afraid `-Dkeycloak.connectionsHotRod.reindexCaches=all` will not solve your issue. It seems you disabled indexes completely in your setup which means you will probably get some errors when doing queries later.

Also, to better understand your usecase, why do you create caches yourself?

**Comment by mhajas** [comment]
@orivat I am closing this as I don't think this is an issue in Keycloak, but rather a problem with how the caches are created. Please let me reopen the issue or let me know if my previous suggestion doesn't help.
