### ISSUE TITLE
Ability to add fields in job template for KeycloakRealmImport CR

### ISSUE THREAD

**Issue by aamoyel** [keycloak/keycloak#14504]
### Description

Like "Keycloak" CR, to add custom labels, annotations and other keys/values, we need an "unsupported" field in "KeycloakRealmImport" CR.

### Motivation

I've deployed keycloak operator and instance in a namespace with Istio enabled and everything is working correctly. My problem is when i create a "KeycloakRealmImport", the operator create a job pod with the istio sidecar proxy because of istio auto injection.
The Istio sidecar leads to a stucking running job because of the proxy never ends.
Istio gives the ability to disable injection with this annotation: 'sidecar.istio.io/inject: “false”' but we cannot add metadata in realmImport like "Keycloak" CR.

### Details

Stucking pod:
```
NAME                                     READY   STATUS     RESTARTS   AGE
pod/internal-ftxtl                       1/2     NotReady   0          18m
pod/keycloak-prod-0                      2/2     Running    0          78m
```
![image](https://user-images.githubusercontent.com/73712310/191269518-26f9acfc-14ad-4bf3-9545-a1c9015a2609.png)

Need to have this fields in KeycloakRealmImports :
```yaml
...
spec:
  unsupported:
    jobTemplate:
      metadata:
        annotations:
          sidecar.istio.io/inject: “false”
```

**Comment by husira** [comment]
@aamoyel, Did you find any solution to quit the job when istio injection is enabled?

**Comment by fuero** [comment]
Could anyone please elaborate on how this has been fixed?

My use case is for applying securityContext best practices to the import jobs
