### ISSUE TITLE
Allow to configure firstname and lastname to be optional during registration

### ISSUE THREAD

**Issue by tbdaniel27** [keycloak/keycloak#14503]
### Description

In light of GDPR, data economy (i.e. only collect personal data you really need to conduct your business) is one of the most important principles. For many applications, there is no real reason to gather the real names of users.

At the same time, Keycloak always requires users to enter their first and last name.

To set a good example regarding the collection of personal data, Keycloak should make it optional to register with first and last name (perhaps configurable per realm).

Currently it is very complicated to make these optional and requires developer skills which probably almost no one will be able or willing to do.

**Comment by sventorben** [comment]
Isn't this supported by the declarative user profile?
https://www.keycloak.org/docs/latest/server_admin/#defining-a-user-profile

**Comment by ThoreKr** [comment]
Curious sidenote: The ui refuses to remove these attributes (first/last name) without any indication why.

Removing them in JSON appears to be working,

**Comment by pedroigor** [comment]
@ThoreKr Do you mean after enabling user profile and removing the attribute from the list at the `User profile` tab?

It works for me in `20.0.2`.

**Comment by ThoreKr** [comment]
> @ThoreKr Do you mean after enabling user profile and removing the attribute from the list at the `User profile` tab?

Indeed. I tried to record a network capture but can't reproduce it in my test setup any more. 
Cosmic rays.

**Comment by p-fruck** [comment]
Hey all,

I have a use case where I want to make firstName and lastName optional attributes. When I enable the declarative user profile feature and set both attributes to optional, everything is working fine when the user registers for the first time (names can be specified optionally). However once registered, the user cannot properly modify their name in the account console. If both names are currently unset, a single name cannot be set (e.g. setting first name but leaving last name empty). Instead, both names have to be specified. Furthermore, once the names are set they cannot be removed by the user anymore and behave as if they were required. An admin account is required to remove the names for the user.

Is this intended? Do I need to customize the dynamic forms? I expected the accounts personal info form to adapt to the declarative user profile automatically
