### ISSUE TITLE
Getting failed to initialize js message if consent is rejected by user

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#14501]
### Describe the bug

Having configured Client with Login settings Consent required enabled, after the login on that client, rejecting consent will bring JS error message and stuck on redirection page. 

### Version

Keycloak 16.1.0 (WildFly Core 18.0.0.Final)

### Expected behavior

Once the consent is rejected, should do some redirection or some button which allow to go back.

### Actual behavior

Getting JS browser popup with: 'Getting failed to initialize keycloak'  and it stuck on loading page with no redirection.

### How to Reproduce?

1. **Go to Clients** -> Go to details by ClientId of existent 'account-console' item
2. Enable settings **Login settings** and Save:
- Consent required
- Display client on screen 
3. . **Go to Clients** -> Go to client **Home URL** http://localhost:8180/auth/realms/master/account/ of the item 'account-console' 
4. Sign In.
5. When **Grant Access to Account Console** page is prompted, reject consent by clicking No.
6. JS popup message appears on loading page with no redirection.

**Comment by ssilvert** [comment]
Need to see if we can handle this error properly.  Need better error handling page.

**Comment by jonkoops** [comment]
I can confirm this bug still exists in Account Console version 3.
