### ISSUE TITLE
User Session Event Log  + Filtering

### ISSUE THREAD

**Issue by sunflowerno0b** [keycloak/keycloak#14506]
### Describe the bug

When clicking the "Event" within the admin panel in Keycloak, while it does show login events - its difficult to filter via username and/or user ID. I would like a clearer way to see who has logged into the client.

### Version

15

### Expected behavior

I expect to be able to filter log in events by username, user ID and make it an easier log to view and understand.

### Actual behavior

I attempt to filter, but the user IDs do not show me the users. When I see login events its only user IDs no usernames.

### How to Reproduce?

Unsure.

**Comment by sschu** [comment]
@sunflowerno0b Please report this as an enhancement, not a bug.
