### ISSUE TITLE
Keycloak server partial gziped resources in some cases

### ISSUE THREAD

**Issue by rh-iatanaso** [keycloak/keycloak#14510]
### Describe the bug

We are serving keycloak theme resources behind CDN.  We have observed partial files been cached occationally.
Looks like the current implementation of https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/encoding/GzipResourceEncodingProvider.java#L42 makes it possible to have a race condition. Request close to the one initially creating the gziped resource can serve partial content. In the general case the subsequent requests will use the complete file. In case of CDN it might take a while for the cached resource to expire

### Version

18.0.0

### Expected behavior

Keycloak should serve correct and complete resource files

### Actual behavior

When concurrent requests for gziped resource are being handled, it is possible to serve partial resource 

### How to Reproduce?

Running multiple requests at single resource requesting gzipped content

**Comment by stianst** [comment]
@rh-iatanaso fancy doing a PR for this one? I guess we could just write to a temp file and rename it when done?
