### ISSUE TITLE
Keycloak returns incorrect metadata when the frontend url is set.

### ISSUE THREAD

**Issue by sutr90** [keycloak/keycloak#14512]
### Describe the bug

The OpenID Endpoint Configuration returns mixed metadata when the frontend url for the realm is set. Its not possible to access the Keycloak simultaneously from private and public hostname.

If you set frontend URL for the realm in the web console and access the realm via the backend hostname, you will get back incorrect metadata.

### Version

18.0.2

### Expected behavior

When accessing the metadata endpoint on the private URL it will return the metadata with the private hostname set.

- Access the frontend url endpoint for OpenID metadata [http://127.0.0.1:9090/auth/realms/manta/.well-known/openid-configuration](http://127.0.0.1:9090/auth/realms/manta/.well-known/openid-configuration)
  - all the registered endpoints contain the frontEnd URL in their domain part
- Access the backend url endpoint for OpenID metadata [http://localhost:9090/auth/realms/manta/.well-known/openid-configuration](http://localhost:9090/auth/realms/manta/.well-known/openid-configuration)
  - all the registered endpoints contain the private URL in their domain part

### Actual behavior

Access the backend url endpoint for OpenID metadata [http://localhost:9090/auth/realms/manta/.well-known/openid-configuration](http://localhost:9090/auth/realms/manta/.well-known/openid-configuration)
- some endpoints contain the frontend URL in their domain part
  
```
{
  "issuer": "http://127.0.0.1:9090/auth/realms/manta",
  "authorization_endpoint": "http://127.0.0.1:9090/auth/realms/manta/protocol/openid-connect/auth",
  "token_endpoint": "http://localhost:9090/auth/realms/manta/protocol/openid-connect/token",
  "introspection_endpoint": "http://localhost:9090/auth/realms/manta/protocol/openid-connect/token/introspect",
  "userinfo_endpoint": "http://localhost:9090/auth/realms/manta/protocol/openid-connect/userinfo",
  "end_session_endpoint": "http://127.0.0.1:9090/auth/realms/manta/protocol/openid-connect/logout"
...
}
```
This way its not possible to authenticate a client using OIDC discovery with the backend URL.

### How to Reproduce?

- Install Keycloak with all defaults. Create realm and set its frontend URL in the web console to [http://127.0.0.1:9090/auth/](http://127.0.0.1:9090/auth/)
- Access the frontend url endpoint for OpenID metadata [http://127.0.0.1:9090/auth/realms/manta/.well-known/openid-configuration](http://127.0.0.1:9090/auth/realms/manta/.well-known/openid-configuration)
  - all the registered endpoints contain the frontEnd URL in thei domain part
- Access the backend url endpoint for OpenID metadata [http://localhost:9090/auth/realms/manta/.well-known/openid-configuration](http://localhost:9090/auth/realms/manta/.well-known/openid-configuration)
  - some of the endpoint still contain the frontend URL

**Comment by TyrantFox** [comment]
We have the same issue. In our case with http for the backend and https for the front end.

This is set in `org.keycloak.protocol.oidc.OIDCWellKnownProvider.java:122` based on the FrontendURL.

Then in the java client, the same value is used for a backend connection at `org.keycloak.adapters.ServerRequest:78` (invokeLogout), using a logout URL from `org.keycloak.apadpters.KeycloakDeployment:188`, which reads this from the well-known `end_session_endpoint` property.

**Comment by stianst** [comment]
This is expected behaviour.

A client can communicate to Keycloak through backend URLs for backend endpoints like token requests, but must use the frontend URL for frontend requests like authz/n request.

**Comment by TyrantFox** [comment]
@stianst surely frontend url is to be used for communication _from the browser_, and backend url is to be used for communication (directly) _from the client_.

Picture a wildfly app server and keycloak deployed in a VPC. All communication between wildfly (the client) and keycloak can be http and does not need to go outside the private network to loop back to communicate. This should all be backend url.

Completely agree that the browser will be redirected to the frontend url.

Looking more closely at the OP, agree that not all URLs should be backend. Only URLs that are _intended_ to be invoked directly by the client. I would argue that the `end_session_endpoint` is intended to be directly invoked by the client, and hence should use the backend url. If this is not the case, then there is a bug in the wildfly keycloak client that thinks it is.

If you agree I can create a new report describing this more focused issue.

**Comment by stianst** [comment]
Actually, end_session_endpoint is also a redirect/frontend logout endpoint. See https://openid.net/specs/openid-connect-session-1_0-17.html#OPMetadata

If the WildFly adapter is invoking that with a backend request it is strictly speaking not doing the right thing.

**Comment by TyrantFox** [comment]
Indeed it is. I shall make a report and propose a change for that instead. Thank you.
