### ISSUE TITLE
Escape character in SAML response

### ISSUE THREAD

**Issue by acaselli** [keycloak/keycloak#14529]
### Describe the bug

I am trying to set up Keycloak as IdP and use it for SSO. The first re-direct (from the application login url to keycloak) works fine, but then, after entering the user credentials I get an "invalid signature" error from the application.

I have checked the SAML response (from keycloak to the application) and I can see that keycloak adds a weird escape character (&#13;) in the certificate and signature value.

Here is part of the SAML response

```xml
<dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
    <dsig:SignedInfo>
      <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
      <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
      <dsig:Reference URI="#ID_fde25c3e-6958-4b49-bbe0-e4aeb200de98">
        <dsig:Transforms>
          <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
          <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
        <dsig:DigestValue>p3ldrwhvbO1zoeHlhCx9TdZ01hGnw3f3IqBDIT5e1oU=</dsig:DigestValue>
      </dsig:Reference>
    </dsig:SignedInfo>
    <dsig:SignatureValue>
iGNKaLxr3c9CUPpRxC3xeS0grx2FdcXWcWArlqZHdWIjQF0n9Whh5ue00HEmb+Nr5VO9jBUwRwXl&#13;
VNEARy/4DeAsuXIxej0OYASBMjx+5qfmUIelXKLChTYjrdHyq2ZtD7BWfCrnNLtB7XiZsy8cYm0v&#13;
ynWLlJTyxUpg+FakcxGNDnSUG6Ofslv6byQDsNY56yvqKCWbcqa1/70PD401E/Gf2XcD4paPAvHX&#13;
B+wS25QFytqrxumRtlJiKcPS+IB8umpcHG4mKk3Qg9FxCRQk2Pk693VnEtYyQ5VXUTNFW8SfWpnQ&#13;
      xDNSE6h2cevj4nT7NSQDxoNh1LRBokwjUNJWQg==
    
</dsig:SignatureValue>
```

Is there a way to force keycloak to send the signature value in one line line without adding escape characters?

### Version

19.0.1

### Expected behavior

The xml response should be like
```xml
<SignatureValue>
Ig/yqt/1Vc/5BMxKvFrARvXGv647L4eAF2TSGkfM1Th3eeU2CjaTFHIFZoGXft8q3ALrbSTBIJckXr3ARZJSqzygTgsMwBgiwH5lR4glSPSbilgTVY/nfDiV9c0+ViVSVCh4ASUB5qEVlVBHUwVHX2dxlFMxunJZj+mlOW3PtFL5Ldbc9Primm+lswX8VMMlJOJJ3JwouQ8NsyUKZwyg27bW8GkOwlBgctKVEDl+rLOSoFY4f2YPzSYG9s8H1yz1VJ8dKMSNIGN+OgNdJBOgAREfnyq5GD6qBHRca0i3KDEXi0+5PRd/tcAIcdYIoLUECVkRYvc0SVWk2r3Ys1X0eA==
</SignatureValue>
```

### Actual behavior

Instead you get this signature value response
```xml
<dsig:SignatureValue>
iGNKaLxr3c9CUPpRxC3xeS0grx2FdcXWcWArlqZHdWIjQF0n9Whh5ue00HEmb+Nr5VO9jBUwRwXl&#13;
VNEARy/4DeAsuXIxej0OYASBMjx+5qfmUIelXKLChTYjrdHyq2ZtD7BWfCrnNLtB7XiZsy8cYm0v&#13;
ynWLlJTyxUpg+FakcxGNDnSUG6Ofslv6byQDsNY56yvqKCWbcqa1/70PD401E/Gf2XcD4paPAvHX&#13;
B+wS25QFytqrxumRtlJiKcPS+IB8umpcHG4mKk3Qg9FxCRQk2Pk693VnEtYyQ5VXUTNFW8SfWpnQ&#13;
      xDNSE6h2cevj4nT7NSQDxoNh1LRBokwjUNJWQg==
</dsig:SignatureValue>
```

### How to Reproduce?

SAML authentication with signature required, signed document and assertion

**Comment by bonnm** [comment]
Does anyone know if this also affects legacy wildfly version 19.0.2?

**Comment by acaselli** [comment]
Maybe it's worth mentioning that I am running keycloak in a docker container with nginx as reverse proxy.

I have tested both redirect and post methods and I can confirm that both have that ASCII code 13 character in it.

**Comment by Kevin-Andrew** [comment]
Having XML character entities anywhere in or throughout the document shouldn't be a problem. The canonicalization that is supposed to happen before computing the signature/digest value should handle this correctly. For example, see:
https://www.w3.org/Signature/Drafts/WD-xml-c14n-20000907.html#Example-Chars

The question then becomes, have both ends performed the came canonicalization transforms correctly?

In our environment, after recently upgrading, we essentially ran into the same problem. That is, client applications were unable to validate the SAML signature(s). After a bunch of research and testing, we had the idea of changing the KeyCloak settings so as to only sign the SAML `<Response>`. Prior, it has been configured to always sign both the SAML `<Response>` as well as the `<Assertion>`. So you'd end up with two XML `<Signature>` nodes in the document. Which really isn't necessary for our purposes of using the [SAML2 Web Browser SSO Profile](https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf) (section 4.1).

So, for example, after changing the KeyCloak setting to only sign the `<Response>`, we end up with the following attached file.
[keycloakSingleSignatureResponse.txt](https://github.com/keycloak/keycloak/files/9718628/keycloakSingleSignatureResponse.txt)

Note that it hasn't been canonicalized yet. And you see the `&#13;` character entities.
For a quick picture, here is a partial formatted screen shot:
![image](https://user-images.githubusercontent.com/22459191/194151831-93efcc99-aaa1-4b86-8137-647401efec4e.png)

Given that, the client code that we've had running for 10 years, was still able to successfully validate the signature and digest value.

However, when the latest version of KeyCloak is set to sign both the `<Response>` and the `<Assertion>`, we are now getting failures when the client application tries to validate it. Whereas, in the past, even with signing both, we were able to at least validate the outer signature of the SAML `<Response>`.

**Comment by Mikescops** [comment]
It seems a similar bug as this https://github.com/keycloak/keycloak/pull/5748 has been reintroduced.

Also facing this issue, so far I'm manually removing the `#13;` char in the signature to pass my verification.

**Comment by JonasPed** [comment]
We are also facing this issue after upgrading from version 16 to version 20. After some testing we can see that it is something that was introduced between version 18 and 19. It affects both the legacy and quarkus.

**Comment by mverbert** [comment]
The problem was triggered by the merge of https://github.com/keycloak/keycloak/pull/9355 , and in particular the unification of the Base64 implementations. Unfortunately it breaks the usage of Microsoft 365 which refuses to validate the new format of the signature. As discussed in https://github.com/keycloak/keycloak/discussions/14500 it would be good to have an acceptable workaround (if not a solution) as it prevents users to upgrade.

**Comment by max-stytch** [comment]
I've just started experimenting with keycloak version 20 and I'm experiencing something similar to @Kevin-Andrew - after stripping out the `#13;` char in the signature, I'm able to validate the response signature when the assertion is signed _or_ when the document is signed _but not_ when both are signed. I'm not sure if this is the same issue or a separate one. Has anyone else experienced similar?

**Comment by diegogmanzanares** [comment]
I've the same problem. A service provider don`t work by the #13; characters

**Comment by unbreakabl3** [comment]
We have the same problem with 19.0.1-legacy

**Comment by kherock** [comment]
I also believe I am running into this now. I experimented with integrating Snowflake's SAML connector with Keycloak back on 18.x, but I have been unable to get it working on version 20.0.2.

**Comment by hmlnarik** [comment]
Reopening for backport

**Comment by shankaryadavy9** [comment]
The same issue is there when Keycloak(19.0.3) sends a signed SAML request.  Should I raise another bug or it's covered in this patch..?

![image](https://user-images.githubusercontent.com/43490933/216234640-09e4af70-e35a-4531-8aac-e5b37f0e635d.png)

**Comment by hmlnarik** [comment]
> The same issue is there when Keycloak(19.0.3) sends a signed SAML request. Should I raise another bug or it's covered in this patch..?

It should be covered. Please see https://github.com/keycloak/keycloak/issues/14529#issuecomment-1400379971 for workaround.

**Comment by shankaryadavy9** [comment]
Thanks. It worked.
