### ISSUE TITLE
Spring Security Adapter is sending invalid Authorization header

### ISSUE THREAD

**Issue by westmc** [keycloak/keycloak#14530]
### Describe the bug

We upgraded the client adapter in one of our apps from 18.0.2 to 19.0.2 and we started receiving ```{"error":"unauthorized_client","error_description":"Invalid client secret"}``` Our server was running 19.0.1, so we upgraded to 19.0.2 but the problem still happens. We also tried 19.0.1 of the adapter, but it has the same problem. I turned on logging and found that the only difference between the requests from 18.0.2 and 19.0.X is the Authorization header.

18.0.2

```
"POST /auth/realms/XXX/protocol/openid-connect/token HTTP/1.1[\r][\n]"
"Authorization: Basic bWF2ZW4tcGF0aWVudC1zZXJ2aWNlOmIyNWI3OTg3LWE4ZWYtNDljMy04N2EwLTQyYTZhMzcxMjNlNg==[\r][\n]"
"Content-Length: 29[\r][\n]"
"Content-Type: application/x-www-form-urlencoded; charset=UTF-8[\r][\n]"
"Host: XXX[\r][\n]"
"Connection: Keep-Alive[\r][\n]"
"[\r][\n]"
"grant_type=client_credentials"
```

19.0.X

```
"POST /auth/realms/XXX/protocol/openid-connect/token HTTP/1.1[\r][\n]"
"Authorization: Basic bWF2ZW4tcGF0aWVudC1zZXJ2aWNlOmIyNWI3OTg3LWE4ZWYtNDljMy04N2EwLTQyYTZhMzcxMjNlNg[\r][\n]"
"Content-Length: 29[\r][\n]"
"Content-Type: application/x-www-form-urlencoded; charset=UTF-8[\r][\n]"
"Host: XXX[\r][\n]"
"Connection: Keep-Alive[\r][\n]"
"User-Agent: Apache-HttpClient/4.5.13 (Java/17.0.3)[\r][\n]"
"Accept-Encoding: gzip,deflate[\r][\n]"
"[\r][\n]"
"grant_type=client_credentials"
```

The missing "==" is causing the server to return a 401.

### Version

19.0.2

### Expected behavior

The client adapter should be able to obtain a token with valid client credentials.

### Actual behavior

The client adapter is receiving a 401 with valid credentials

### How to Reproduce?

```
...

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.3</version>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2021.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.keycloak.bom</groupId>
                <artifactId>keycloak-adapter-bom</artifactId>
                <version>19.0.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

...

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-spring-boot-starter</artifactId>
        </dependency>

...

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${project.parent.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by lexcao** [comment]
Hi, @westmc 

For 19, there is an RFC 6749 compliant basic auth header supporting special characters (#11908)

Could you please provide minimal steps to reproduce to help me debug?

**Comment by westmc** [comment]
@lexcao I can no longer seem to reproduce this. It is very odd because it was happening on a test system with an image compiled and created on our build system as well as locally compiled on my computer, so it isn't like a bad jar or version in my maven cache triggered it. I have no idea why the "==" was getting removed from the header, although I did trace through to the specific Keycloak code creating that header (BasicAuthHelper.RFC6749.createHeader). One thing I noticed is that it is passing Base64.DO_BREAK_LINES, which in my case is triggering the header to become ```Basic bWF2ZW4tcGF0aWVudC1zZXJ2aWNlOmIyNWI3OTg3LWE4ZWYtNDljMy04N2EwLTQyYTZhMzcxMjNl\nNg==``` and when httpclient makes the actual request, it is stripping out the new line and replacing it with a space ```Basic bWF2ZW4tcGF0aWVudC1zZXJ2aWNlOmIyNWI3OTg3LWE4ZWYtNDljMy04N2EwLTQyYTZhMzcxMjNl Ng==```. In my previous tests, there was no space being added, so I'm not sure what was going on.

Isn't it a bug that BasicAuthHelper.RFC6749.createHeader is adding a non-standard newline to a http header and then relying on the downstream http client code to correct it?

**Comment by lexcao** [comment]
> One thing I noticed is that it is passing Base64.DO_BREAK_LINES

Yes, it passes `Base64.DO_BREAK_LINES`, but for `BasicAuthHelper.createHeader` method
not `BasicAuthHelper.RFC6749.createHeader`.

**Comment by westmc** [comment]
BasicAuthHelper.RFC6749.createHeader is calling BasicAuthHelper.createHeader

```
    public static abstract class RFC6749 {

        public static String createHeader(String username, String password) {
            try {
                return BasicAuthHelper.createHeader(
                    URLEncoder.encode(username, "UTF-8"),
                    URLEncoder.encode(password, "UTF-8")
                );
            } catch (UnsupportedEncodingException e) {
                return null;
            }
        }
```

**Comment by lexcao** [comment]
Thank you.
Is there any way to reproduce that?
I think it may be an issue introduced by the additional `Base64.DO_BREAK_LINES`.

**Comment by westmc** [comment]
We discovered it by using a client that had authorization enabled and when the Keycloak Spring Security client would load, it would make the call out to get a token to check the authorization. Here is a watered down unit test...

```
        final HttpPost post = new HttpPost("https://XXX/auth/realms/XXX/protocol/openid-connect/token");
        post.setHeader("Authorization",
                BasicAuthHelper.RFC6749.createHeader("xxxxx-xxxxxxx-service", "b25b7987-a8ef-49c3-87a0-42a6a37123e6"));

        final HttpEntity entity = new StringEntity("grant_type=client_credentials", ContentType.APPLICATION_FORM_URLENCODED);
        post.setEntity(entity);

        try (final CloseableHttpClient client = HttpClients.custom().setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE).build())
        {
            try (final CloseableHttpResponse response = client.execute(post))
            {
                Assertions.assertEquals(200, response.getStatusLine().getStatusCode());
                log.info(EntityUtils.toString(response.getEntity()));
            }
        }
```

and if you set logging to debug for org.apache.http then you can see the request/response.

**Comment by westmc** [comment]
or you can just call this directly...

```
log.info(BasicAuthHelper.RFC6749.createHeader("xxxxx-xxxxxxx-service", "b25b7987-a8ef-49c3-87a0-42a6a37123e6"));
```

it will result in...

```
Basic eHh4eHgteHh4eHh4eC1zZXJ2aWNlOmIyNWI3OTg3LWE4ZWYtNDljMy04N2EwLTQyYTZhMzcxMjNl
Ng==
```

instead of 

```
Basic eHh4eHgteHh4eHh4eC1zZXJ2aWNlOmIyNWI3OTg3LWE4ZWYtNDljMy04N2EwLTQyYTZhMzcxMjNlNg==
```

**Comment by mposolda** [comment]
Adding to Backlog as Spring Security adapter has very low priority and Keycloak team likely won't be able to look at this. Investigation and eventually contribution of the fix is welcome!

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
