### ISSUE TITLE
400 for /token endpoint for Multiple Keycloak Servers

### ISSUE THREAD

**Issue by Jess103** [keycloak/keycloak#14537]
### Describe the bug

Here I have vip(xx.xx.xx.xx), Load Balancer(L4) switching to keycloak1(yy.yy.yy.yy) and keycloak2(zz.zz.zz.zz)
When the local PC hosts is set as "xx.xx.xx.xx keycloak.com", it throws 400 error for /token endpoint using authorization code.
But when the hosts is set as "yy.yy.yy.yy keycloak.com", it correctly gets the token.
My config file looks like below:

>**keycloak.conf**
log-level=DEBUG
log=file
log-file=/PATH/keycloak.log
db=postgres
db-username=DB_USER
db-password=DB_PASS
db-url=jdbc:postgresql://DB_PATH
https-certificate-file=/PATH/cert.pem
https-certificate-key-file=/PATH/key.pem
http-port=80
https-port=443
https-protocols=TLSv1.3,TLSv1.2
http-enabled=true
hostname-strict=false
hostname-strict-https=false
http-forwarded-host-enabled=true
hostname=keycloak.com
health-enabled=true
metrics-enabled=true

Do I need to set something extra for two or more keycloak servers?

### Version

18.0.1, 19.0.2 - Quarkus (tested both) on JVM (JDK 11)

### Expected behavior

Correctly receive the token

### Actual behavior

Throws 400 error

### Anything else?

I use the code below to get token.

---

System.setProperty("https.protocols", "TLSv1.2");

URL url = new URL("https://keycloak.com/realms/REALM/protocol/openid-connect/token");
String query = "code=RECEIVED_CODE&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&redirect_uri=https://a.com/redirect&grant_type=authorization_code";

HttpsURLConnection connection_ssl = null;
OutputStreamWriter wr = null;
String inputLine = "-1";
BufferedReader in = null;

byte[] prm = query.getBytes("utf-8");
int prmLength = prm.length;
DataOutputStream dwr = null;

// ~ SSL check ~

connection_ssl = (HttpsURLConnection) url.openConnection();
connection_ssl.setConnectTimeout(10000);
connection_ssl.setReadTimeout(20000);
connection_ssl.setDoInput(true);
connection_ssl.setDoOutput(true);
connection_ssl.setRequestMethod("POST");
connection_ssl.setRequestProperty("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
connection_ssl.setRequestProperty("Content-Length", Integer.toString(prmLength));
/*
 I tried adding User-Agent after reading this :
 https://stackoverflow.com/questions/47089319/server-returned-http-response-code-400-for-keycloak
 But it still behaves the same
*/
connection_ssl.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36");

dwr = new DataOutputStream (connection_ssl.getOutputStream ());
dwr.write(prm);
dwr.close();

String retVal = "";
if("https".equals(url.getProtocol())) {
    in = new BufferedReader(new InputStreamReader(connection_ssl.getInputStream()));
} else {
    in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
}
while ((inputLine = in.readLine()) != null) {
    retVal += inputLine;
}
in.close();

**Comment by Jess103** [comment]
I just checked the versions of the browsers as well
- Edge : 105.0.1343.42
- Chrome : 105.0.5195.127
What else should I look for?

**Comment by Jess103** [comment]
I added "cache=ispn" in the keycloak.conf but still the same

**Comment by Jess103** [comment]
Oh I just added "proxy-address-forwarding=true" and "proxy=edge" in the conf, treating the load balancer as a revers proxy
then I guess... it kinda fixed... the issue...???
I'm going to tested it more throughout the day and close this issue if this has really been turned out as fixed!

**Comment by Jess103** [comment]
Never mind... I was just lucky that I was keep getiing into the same server.
What else should I try?

**Comment by sschu** [comment]
Did you set up your distributed caching properly? See https://www.keycloak.org/server/caching.

**Comment by DoHaengLee** [comment]
Thank you for the comment
I tried "cache=ispn" already, but it still behaves the same.
I'll try adding "cache-stack=tcp" and test again tmr

**Comment by Jess103** [comment]
Thank you for the comment!
I tried "cache=ispn" already, but it still behaves the same.
I'll try adding "cache-stack=tcp" and test again tmr.

**Comment by sschu** [comment]
The thing is the stack has to match your environment. E.g. in Kubernetes, you should use for example DNS_PING but this requires some additional setup in Kubernetes.

**Comment by Jess103** [comment]
https://github.com/keycloak/keycloak/discussions/12022#discussioncomment-2795805
I followed this, but it's throwing me new errors.

>**keycloak.conf**
log-level=DEBUG
log=file
log-file=/PATH/keycloak.log
db=postgres
db-username=DB_USER
db-password=DB_PASS
db-url=jdbc:postgresql://DB_PATH
https-certificate-file=/PATH/cert.pem
https-certificate-key-file=/PATH/key.pem
http-port=80
https-port=443
https-protocols=TLSv1.3,TLSv1.2
http-enabled=true
hostname-strict=false
hostname-strict-https=false
http-forwarded-host-enabled=true
hostname=keycloak.com
health-enabled=true
metrics-enabled=true
proxy-address-forwarding=true
proxy=edge
cache=ispn
cache-config-file=/PATH/keycloak-19.0.2/conf/cache-ispn-tcpping.xml

>**cache-ispn-tcpping.xml**
#Coppied the original cache-ispn.xml and just added+modified the following parts
#I also opened the 11222 ports for both yy.yy.yy.yy and zz.zz.zz.zz
< jgroups>
    < stack name="tcpping" extends="tcp">
        < TCP bind_port="11222"/>
        < TCPPING
            initial_hosts="yy.yy.yy.yy[11222],zz.zz.zz.zz[11222]"
            port_range="0"
            stack.combine="REPLACE"
            stack.position="MPING"
            />
    < /stack>
< /jgroups>
< cache-container name="keycloak">
    < transport lock-timeout="60000" stack="tcpping"/>

**Problems**
1. When "cache" is set, keycloak doesn't show me any log.
2. When "cache-config-file" is set, I get connection refused for https://keycloak.com/health

**Comment by sschu** [comment]
TCP pings means you have to configure static ip addresses upfront. What is your runtime environment?

**Comment by Jess103** [comment]
I have vip(xx.xx.xx.xx), Load Balancer(L4) switching to keycloak1(yy.yy.yy.yy) and keycloak2(zz.zz.zz.zz)
Both server has keycloak-19.0.2 Quarkus on JVM (JDK11)
I set https port for 443 in keycloak.conf
I use kerberos authentication that I uploaded the key tab and set the config in the admin console

I tested everything in dev server, whichi has no load balancer nor other kc instance that I kinda freaked out when I first found this cache setting...
What else should I look for?

**Comment by sschu** [comment]
What I meant is are you running on bare VMs? Kubernetes?

**Comment by Jess103** [comment]
I'm not using k8s.
I'm using cloud servers (CentOS7), which has jdk n kc installed directly.
I'm not sure what you mean 'static ip address'; if you mean if the vip, kc1, kc2 ip addresses never changes, yes, they are static that the ip addresses don't change.

**Comment by sschu** [comment]
Can you provide a log of the startup process, there you can see whether the cluster actually forms successfully or not.

**Comment by hmlnarik** [comment]
@Jess103 Could you please provide the logs? This issue cannot be moved forward without those and could be subject to closing due to insufficient information

**Comment by Jess103** [comment]
As I mentioned above, it stops logging when I turn on the cache settings.
I found a workaroud though that I'll close this issue
