### ISSUE TITLE
Delete Client Roles does not scale

### ISSUE THREAD

**Issue by nmwael** [keycloak/keycloak#14538]
### Describe the bug

Hi we are experiencing performance issues when deleting client roles. It looks to be related to the amount of checks or queries run after the delete are issued from the Client Role resource, so keycloak will check something per role or per permission instead of running these things as a bulk.

Our code that triggers this behavior:
```
RolesResource rolesResource = clientResource.roles();
rolesResource.deleteRole(roleAndPolicyName.getRoleName());

```
Results in many many SQL executions like these:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/767991/191718203-0a17f40e-d80c-49a4-9edb-4f5298ad4ab3.png)

Currently our system has about 400 client roles, and is taking 8s to delete one role.

### Version

19.0.2

### Expected behavior

Deleting a role should scale with system performance wise.

### Actual behavior

Doesnt seem to scale as roles are processed induvidually.

### How to Reproduce?

Add more than 10 client roles fire up a SQL profiler and watch the amount of SQL executions per deletion on role.

### Anything else?

Keep up the good work :)

**Comment by zanettea** [comment]
We too are experiencing similar performance issues
