### ISSUE TITLE
Login blocked for invalid role mapper in openid IDP

### ISSUE THREAD

**Issue by savvyjindal** [keycloak/keycloak#14540]
### Describe the bug

Okta is configured as an OpenID IDentity Provider(IDP). Multiple mappers (claim-> role) are created to map group claims in okta with roles in keycloak. 

If a mapper is found with a role that does not exist in keycloak, all login requests using this IDP are blocked with errors in server. (Screenshots Attached)

**Sample Mapper**

![image](https://user-images.githubusercontent.com/26510530/191734036-0a1d8761-002d-4201-b84b-241cdcd24801.png)

**Login Error**

![image](https://user-images.githubusercontent.com/26510530/191734228-1265d4cf-baa7-40c0-990f-f847d221f5d4.png)

**Server Error**

![image](https://user-images.githubusercontent.com/26510530/191734340-9c7d834d-a812-408d-b5c8-16e1318c6c3b.png)

### Version

Keycloak Version - 11.0.2

### Expected behavior

The expectation is that if an invalid mapper is found then all other mappers are still honored whereas the invalid one is ignored. But the invalid mapper does not cause all authentications to be blocked.

### Actual behavior

All logins are blocked if a mapper is created with a non-existent role. 

### How to Reproduce?

1. Create a new Identity provider type OpenID
2. Add a mapper with a non-existent role
3. Try to log in to the application using the IDP created.
4. You will notice that the logins are blocked and an error is returned saying "Unexpected error when authenticating with identity provider"

**Comment by mposolda** [comment]
This might be already fixed in latest version, so I am closing. Please re-open just if you're still able to reproduce in latest Keycloak 21.0.1 version
