### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by theusman-dev** [keycloak/keycloak#14587]
### Describe the bug

Getting `ReferenceError: document is not defined` error when trying to initialize the `Keycloak` from keycloak-js. I was using 12.0.4 and then upgraded from 18.0.1 through 19.0.2 the issue still persists. Trying to do server-side rendering in react. Serving from node. Issue generating from below code, on creation

```
const keycloak = new Keycloak({
    url: 'http://keycloak-server${kc_base_path}',
    realm: 'myrealm',
    clientId: 'myapp'
});
```
More info about the issue. The issue starts coming from version 17 and after.
```
function Keycloak (config) {
        if (!(this instanceof Keycloak)) {
            return new Keycloak(config);
        }

        var kc = this;
        var adapter;
        var refreshQueue = [];
        var callbackStorage;

        var loginIframe = {
            enable: true,
            callbackList: [],
            interval: 5
        };

        var scripts = document.getElementsByTagName('script');
```
        
In the above code, the document is not defined.
### Version

18.0.1 to 19.0.2

**Comment by lexcao** [comment]
> Trying to do server-side rendering in react. Serving from node

Yes, from server-side rendering, the `document` is undefined as expected.
From my understanding, Keycloak.js is currently available for the client-side because of the usage of `iframe`.

**Comment by theusman-dev** [comment]
Yes, I think that may be the reason, but it works with versions up to 16 and after that, it was causing this error. But I have handled this error in my code with a window check as I am using react-keycloak/ssr for SSR work.

**Comment by randombk** [comment]
Reviving this old issue to flag that the use of the `document` variable also causes problems with ManifestV3 browser extensions, as background scripts are now migrated to Service Worker without access to `document`.
