### ISSUE TITLE
Unable to Logout because of redirect_uri issue (keycloak-js)

### ISSUE THREAD

**Issue by conormcafee** [keycloak/keycloak#14585]
### Describe the bug

This could be an issue with my understanding of the documentation - but currently I am unable to log a user out of the application without explicitly sending them to:  `https://{domain}/auth/realms/eamli/protocol/openid-connect/logout`.  

Reading the following:

> If you use the latest javascript adapter, you are also not affected. However if your application uses an older version of the JavaScript adapter, you are affected as this adapter uses the variant of the logout endpoint with the deprecated redirect_uri parameter. In this case, you may need to upgrade to the latest version of the JavaScript adapter.

from [Keycloak Upgrading Docs](https://www.keycloak.org/docs/latest/upgrading/index.html#openid-connect-logout) my understanding is I am not affected as using the latest version of the adapter?

Would rather not do this as they have to confirm on that screen that they wish to `logout`.

Am I able to call `keycloak.logout()` and get my expected behaviour? 

Currently I have the `Valid Redirect URI` set to my desired URIs (which work for login), and `Post Logout Redirect URI` set to `+` so it should inherit the `Valid Redirect URI` - but I have no joy with not being able to logout without seeing the `Invalid Redirect URI`

Any tips to point me in the right direction would be appreciated.  I am upgrading from version `15.x.x` to `19.0.2`

### Version

19.0.2

**Comment by RyanLefebvre** [comment]
This is similar to our issue here: https://github.com/keycloak/keycloak/issues/14568

**Comment by mposolda** [comment]
It can be same/similar issue as https://github.com/keycloak/keycloak/issues/14568, so I am closing this one as duplicate.

So I am closing this. Everyone seeing this, please reply to that issue for the further discussions/questions/suggestions.

If possible, I suggest to test with latest Keycloak 21 server and latest Keycloak 21 JS adapter to check if upgrade helps. Please reply to the #14568 if it helps. Thanks!
