### ISSUE TITLE
Bad Gateway error

### ISSUE THREAD

**Issue by nidhin077** [keycloak/keycloak#14595]
### Describe the bug

I have updated my keycloak to quarkus and connected the same to traefik. But while accessing the keycloak. I'm getting a bad gateway error. Could you please take a look and let me know how to resolve the same?

### Version

19.2

### Expected behavior

Loading with latest version 

### Actual behavior

Bad Gateway error

### How to Reproduce?

    restart: always
      command: start-dev
      environment:
       - KEYCLOAK_ADMIN=admin
       - KEYCLOAK_ADMIN_PASSWORD=rN&P3hx(*L
       - KC_DB_USERNAME=adminq
       - KC_DB_PASSWORD=6()qTN9)Tuq
       - KC_HOSTNAME=domain.com 
       - KC_PROXY=edge 
       #- KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
       #- KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
     volumes:
       - ./config/cert/keycloak.crt:/etc/x509/https/tls.crt
       - ./config/cert/keycloak.key:/etc/x509/https/tls.key

**Comment by stianst** [comment]
Keycloak doesn't return a "Bad Gateway error" so this will be an issue in your gateway/proxy configuration. If you've recently switched from the JBoss distribution to the Quarkus distribution it can quite likely be due to the default context path has changed from '/auth' to '/'.
