### ISSUE TITLE
Update Kc{Adm,Reg}Test to allow info level log from CryptoIntegration

### ISSUE THREAD

**Issue by david-rh** [keycloak/keycloak#14592]
In #12702, the log message `Detected crypto provider: XXX` was changed to debug. It will be good to change back to info.

**Comment by mposolda** [comment]
Closing as this task probably won't be needed. Administrator can enable debug log if he wants to see the message. Also the Keycloak server does not "detect" the provider by default, but uses the option where provider is specified with `--fips-mode` option.
