### ISSUE TITLE
Default Build Failing Due to Test Failures

### ISSUE THREAD

**Issue by sam-hieken** [keycloak/keycloak#14610]
### Describe the bug

After cloning and building without making any modifications, I get the following error:

`java.security.NoSuchAlgorithmException: NativePRNG SecureRandom not available`

Which appears to occur in

`org.keycloak.crypto.elytron.test.ElytronHmacTest.testHmacSignaturesUsingKeyGen`

### Version

19.0.1

### Expected behavior

Build success.

### Actual behavior

`[ERROR] Errors:`

`[ERROR]   ElytronHmacTest.testHmacSignaturesUsingKeyGen:42 » NoSuchAlgorithm NativePRNG SecureRandom not available`

`[INFO]`

`[ERROR] Tests run: 46, Failures: 0, Errors: 1, Skipped: 2`

`[INFO]`

`[INFO] ------------------------------------------------------------------------`

`[INFO] Reactor Summary for Keycloak 999-SNAPSHOT:`

`[INFO]`

`[INFO] Keycloak BOM Parent ................................ SUCCESS [  1.048 s]`

`[INFO] Keycloak BOM for adapters .......................... SUCCESS [  0.031 s]`

`[INFO] Keycloak BOM for server extensions ................. SUCCESS [  0.028 s]`

`[INFO] Keycloak BOM utilities for the quickstarts ......... SUCCESS [  0.029 s]`

`[INFO] Keycloak ........................................... SUCCESS [  0.054 s]`

`[INFO] Keycloak Common .................................... SUCCESS [ 14.303 s]`

`[INFO] Keycloak Core ...................................... SUCCESS [ 24.565 s]`

`[INFO] Keycloak Server SPI ................................ SUCCESS [  4.574 s]`

`[INFO] Keycloak Server Private SPI ........................ SUCCESS [  7.780 s]`

`[INFO] Keycloak Crypto Parent ............................. SUCCESS [  0.032 s]`

`[INFO] Keycloak Crypto Default ............................ SUCCESS [  7.006 s]`

`[INFO] Keycloak Crypto FIPS 140-2 Integration ............. SUCCESS [  6.586 s]`

`[INFO] Keycloak Crypto Wildfly Elytron Integration ........ FAILURE [  5.754 s]`

### How to Reproduce?

Adding mirror to mvnw's maven-settings.xml [as described in building.md](https://github.com/keycloak/keycloak/blob/main/docs/building.md), and running

`mvnw clean install`

Same issue also occurs when not using Maven wrapper.

### Anything else?

Maven Version (mvnw): 3.8.6

Java Version: 11.0.16

Operating System: Windows 10

**Comment by Vividious** [comment]
I have the same problem on Java 11 & Windows.
The weird thing is that if you execute that single test class -> ElytronSecureRandomTest it works...

**Comment by Vividious** [comment]
I figured this out.
Problematic test testHmacSignaturesUsingKeyGen is using NativePRNG algorithm which is available for unix like systems only.
In case of windows, it's native algorithm is called "Windows-PRNG". I'll create a PR with the solution proposal.
