### ISSUE TITLE
ID token is not including roles

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#14617]
### Describe the bug

The [example application](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications) included with the book in chapter 2 shows the ID token and access tokens.

Previously the ID token included realm_access, while now it does not.

Example ID token:
```
{
  "exp": 1664300152,
  "iat": 1664299852,
  "auth_time": 1664298915,
  "jti": "21bb9f32-98ce-49aa-896d-796cb716be59",
  "iss": "http://localhost:8080/realms/myrealm",
  "aud": "myclient",
  "sub": "eb14ea82-45e2-4413-8997-129fd0fc865b",
  "typ": "ID",
  "azp": "myclient",
  "nonce": "ccf5f374-aa07-4280-b63a-efdba9c355c9",
  "session_state": "22884115-55cb-4285-ba92-26c4bf74f74b",
  "at_hash": "ngdMORpXQcEQJ6d9s3uHvw",
  "acr": "0",
  "sid": "22884115-55cb-4285-ba92-26c4bf74f74b",
  "email_verified": true,
  "name": "Stian Thorgersen",
  "preferred_username": "st",
  "given_name": "Stian",
  "family_name": "Thorgersen",
  "email": "st@localdomain.localhost"
}
```

Example Access Token:
```
{
  "exp": 1664300152,
  "iat": 1664299852,
  "auth_time": 1664298915,
  "jti": "670c961e-9da2-43f6-818a-79ef076d965f",
  "iss": "http://localhost:8080/realms/myrealm",
  "aud": "account",
  "sub": "eb14ea82-45e2-4413-8997-129fd0fc865b",
  "typ": "Bearer",
  "azp": "myclient",
  "nonce": "ccf5f374-aa07-4280-b63a-efdba9c355c9",
  "session_state": "22884115-55cb-4285-ba92-26c4bf74f74b",
  "acr": "0",
  "allowed-origins": [
    "http://localhost:8000"
  ],
  "realm_access": {
    "roles": [
      "default-roles-myrealm",
      "offline_access",
      "uma_authorization",
      "myrole"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "sid": "22884115-55cb-4285-ba92-26c4bf74f74b",
  "email_verified": true,
  "name": "Stian Thorgersen",
  "preferred_username": "st",
  "given_name": "Stian",
  "family_name": "Thorgersen",
  "email": "st@localdomain.localhost"
}
```

### Version

main

### Expected behavior

ID token includes roles, but doesn't

### Actual behavior

No realm_access included in ID token.

_No response_

### How to Reproduce?

Run the example from chapter 2 of the book, or any other application that can view the ID and access tokens easily.

**Comment by stianst** [comment]
Looking at the realm role mapper it should be included:
![image](https://user-images.githubusercontent.com/2271511/192597062-b9404d30-4ad8-443d-a077-dc7d9b990305.png)

**Comment by mposolda** [comment]
@stianst I am almost sure that ID Token never contained roles by default in Keycloak. Claims `realm_access` and `resource_access` are proprietary Keycloak claims (not available in OIDC or any other specs AFAIK). Keycloak java adapters historically used the access token and retrieved the roles from `realm_access` or `resource_access` claims to figure what roles should be used as JEE roles in the web application. But ID Token was not used by the adapters and roles were never needed here.

But it is easily possible to include roles in ID Token just by switching it in the mapper as you pointed.

**Comment by mposolda** [comment]
I am adding to Backlog. Also I think that this is not a real bug and might be closed as ID Token never contained roles (realm_access and resource_access claims) by default and also OIDC specification does not prescribe anything about that. In general, there is not much reason why roles should be needed by default in ID Token.

**Comment by sschu** [comment]
@mposolda One reason would be a UI rendering input elements only when the user has the rights to actually use the functionality behind the input elements.

**Comment by sschu** [comment]
@mposolda Especially if https://github.com/keycloak/keycloak/issues/19650 is coming this might require adapters to look into the ID token instead.
I am fine with adding it to the ID token on demand or by default. I think the OIDC spec does not forbid adding additional claims so it should be fine with the spec. Furthermore, ID token size is less of an issue since it is not passed in the header (with the exception of the id_token_hint passed in the URL). On the other hand, it wasn't added by default so far and nobody really asked for it (except @stianst :) ).

**Comment by jbman** [comment]
@sschu @mposolda, you are discussing if roles should be in the ID token or not.
But independently of this decision: If the mapper tells that roles are put into the ID token then they should be there.
I observed that ID token contains realm roles (`realm_access`) but not client roles (`resource_access`), even though the client role mapper has "Add to ID token" enabled.

**Comment by stianst** [comment]
@mposolda I'm not sure what has changed, but something has changed, as the steps in the book worked in the past with older versions of Keycloak, but now doesn't.

**Comment by sschu** [comment]
I agree with @mposolda:
a) I don't see an issue with OIDC spec as it allows additional claims. But I agree that it would be a change because as far as I remember it has never been in the token by default (in contrast to what @stianst says). So far nobody missed it as a default (except @stianst ;) ) I also checked the book and it explicitely says roles are not added by default (see screenshot).
b) There was indeed a UI glitch there showing "add to ID token" as enabled even if it wasn't. That should be fixed now as @jbman told me.
So I would also vote to leave it as it is and close this issue.
![IMG_5547](https://user-images.githubusercontent.com/3833769/234842581-bf2f38eb-936d-404b-83d3-d6cba95ef070.jpg)

**Comment by mposolda** [comment]
@sschu Thanks! So book mentions that you should explicitly enable `Add to ID Token`. So it looks that this was likely only UI issue with the `Add to ID Token` switch, which was likely fixed in the meantime by some other commit.
@stianst So are we ok to close this?

**Comment by mposolda** [comment]
I am closing this as based on previous comment, it looks that this was just UI issue with the switches on protocol mappers not correctly working in the admin console. Which was fixed in latest version.

@stianst Feel free to re-open if you still see this with latest Keycloak

**Comment by payalb** [comment]
![image](https://github.com/keycloak/keycloak/assets/18390065/b1820c6d-ef4a-4a2e-ba8a-243c6dfdf4a0)
![image](https://github.com/keycloak/keycloak/assets/18390065/ee214cdf-7cb1-4973-84d5-33327c01a822)
![image](https://github.com/keycloak/keycloak/assets/18390065/0c99e28d-d008-435f-abc7-90adbccf0777)
![image](https://github.com/keycloak/keycloak/assets/18390065/e12b6c15-9e45-4d22-8c15-8f7ad01f18d8)
![image](https://github.com/keycloak/keycloak/assets/18390065/018c78f3-c2bf-4618-9c10-0217d7bd4165)

I don't see the user specified client roles added to the id token in the latest version as well.

**Comment by AcquaNet** [comment]
I don't see the user specified client roles added to the id token in the latest version as well too.

![image](https://github.com/keycloak/keycloak/assets/40213402/ec0936be-51c8-458f-b9e5-f106884c3a4f)

![image](https://github.com/keycloak/keycloak/assets/40213402/d2321321-3660-4bc7-8844-83eaa1718808)

![image](https://github.com/keycloak/keycloak/assets/40213402/3bde4fc4-1b09-445a-b54a-3ac5ab248a37)

![image](https://github.com/keycloak/keycloak/assets/40213402/d9f09dec-d6d3-4385-a85a-ddc41ad747d3)
