### ISSUE TITLE
Invalid parameter: redirect_uri shown when client is not found

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#14615]
### Describe the bug

Doing a authz code flow with a non-existing client results in:

![image](https://user-images.githubusercontent.com/2271511/192593146-0c5dd824-aedc-43e0-bfca-33b84a44c577.png)

At the same time the correct error is shown in the logs:

```
2022-09-27 19:15:44,416 WARN  [org.keycloak.events] (executor-thread-27) type=LOGIN_ERROR, realmId=2e32eeed-558c-44a8-a625-a2bc4840e96e, clientId=myclient, userId=null, ipAddress=127.0.0.1, error=client_not_found
```

### Version

main

### Expected behavior

Error page with message `Client not found`

### Actual behavior

Error page with message `Invalid parameter: redirect_uri`

**Comment by sschu** [comment]
Maybe this is on purpose to not allow client id enumeration?

**Comment by mposolda** [comment]
duplicates #19662 
so closing this.

@sschu Yes, client enumeration was initial purpose, however we discussed with @stianst that we don't consider client enumeration as an issue for now and we consider the fact that "client with client_id foo exists" as public information.
