### ISSUE TITLE
Keycloak 19.0.1 can not atrt with mariaDB 10.8.4

### ISSUE THREAD

**Issue by husaljarab** [keycloak/keycloak#14638]
### Describe the bug

I was using MariaDB version 10.6.5 that keycloak ver 19.0.1 integrated with it perfectly, I moved to mariaDB 10.8.4, and I'm trying to connect keycloak with it, but keycloak can not start and five an errors on start command
![DB 10 6 5](https://user-images.githubusercontent.com/114597091/192811492-41f9bc50-a72d-425f-a2a7-49d7251c67a7.png)
![DB 10 8 4](https://user-images.githubusercontent.com/114597091/192811500-db6853b6-8f18-4494-bd2c-809973f71dd2.png)
![Error](https://user-images.githubusercontent.com/114597091/192811505-c4ecf30d-6be7-4828-8ffd-6c80327420be.png)

### Version

19.0.1

**Comment by Pepo48** [comment]
Hi @husaljarab, thanks for the issue report. I tried to reproduce this issue in a dockerized environment with the same versions you mentioned in the description. Here's my setup:
```
docker network create keycloak-network

docker run -p 3306:3306 --name mariadb -d --net keycloak-network -e MYSQL_DATABASE=keycloak \
-e MYSQL_USER=keycloak -e MYSQL_PASSWORD=password -e MYSQL_ROOT_PASSWORD=root_password mariadb:10.8.4

docker run -p 8081:8080 --name keycloak --net keycloak-network -e KEYCLOAK_ADMIN=admin \
-e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_DB=mariadb -e KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak \
-e KC_DB_USERNAME=keycloak -e KC_DB_PASSWORD=password quay.io/keycloak/keycloak:19.0.1 start-dev
```
This worked for me without the issues. Please, check whether you see some obvious differences right away (mainly regarding the parameters).

Just based on the attached screenshots I guess you use the native distributions of both Keycloak and MariaDB installed on a Windows platform, right?

I can try to reproduce it in a similar environment to yours. Just, please, let me know whether your problem still persists and eventually share more details about your specific setup.

Thank you very much!

**Comment by husaljarab** [comment]
Hi @Pepo48,

At first, I want to thank you for your efforts.
Yes dear, I'm using a Windows platform and I solved it by using DB driver org.mariadb.jdbc.Driver and add some configurations to Keycloak config file

db-driver=org.mariadb.jdbc.Driver
tx-type=enabled
transaction-xa-enabled=false

**Comment by Pepo48** [comment]
@husaljarab thanks for sharing the solution. Glad to hear that it works for you.

Thus, I am closing this issue.  Thanks again and have a great day!
