### ISSUE TITLE
Loading the admin console

### ISSUE THREAD

**Issue by alokhom** [keycloak/keycloak#14637]
### Describe the bug
Problem: 
On clicking keycloak adminstrator console, it only shows "Loading the admin console" and nothing more.... goes round and round.. all browsers tried. 

Deployment : 
- minikube v.1.20.0  hosted on a desktop debian box with flux cd 0.34
- Deployed postgres Database (  zallando operator based postgres db )  https://gist.github.com/alokhom/6f1836a48f9defb052f1d6bc775db40c . Alternatively also tried crunchy postgres db but no improvement. 
- Deployed keycloak operator  CRDs of https://github.com/keycloak/keycloak-k8s-resources/tree/19.0.2/kubernetes and using kubernetes,yaml ( minikube.yaml has some manifest issues) 
- Deployed Keycloak 19.0.2 manifest https://gist.github.com/alokhom/713901155a23bb46187ec31c3b9b06be
- kubectl port forwarded keycloak pod to local browser on laptop on port 8080. 
- Also run Ingress nginx deployed for https access of keycloak.  ( on https://accounts.xxx.ext_ip.nip.io ) with a Ingress manifest and tls cert issued by cert-manager ca openssl certs.

Till now: 
- Tried to check  issues  [11926](https://github.com/keycloak/keycloak/issues/11926 )  but no luck and no clear idea about how to use `hostname-strict-https and proxy`. I want to use the `tlsSecret `flag for external https access on `nip.io` but as well as port-forwarding 8080 local laptop should work just like it is mentioned here  [11324](https://github.com/keycloak/keycloak/discussions/11324)

### Version

19.0.2

### Expected behavior

admin console opens properly

### Actual behavior

Loading the admin console

### Anything else?

- Lens/kubectl access with kubeconfig certificates copied out of the box so as to work with ssh tunnel to the box

**Comment by stianst** [comment]
Firefox?

**Comment by stianst** [comment]
Could you try with the old admin console?

Anything interesting in Dev console (cookies/request blocked/failing) or js errors?

**Comment by alokhom** [comment]
i tried with 18.0.2 also same issue. 

Dev console:
on the keykloak admin console url  it gets stuck here... with red.. 404
https://accounts.xxx.ext_ip.nip.io/realms/master/protocol/openid-connect/3p-cookies/step1.html
the .js result is 200 ok

one reason i suspect the url not resolving is, the debian box 30443 external port needs ssh port-forward to minikube-ip:30005 ( ingress ngnix  service NodePort port) .  And then i would do some nginx scripting to proxypass to http://$host:30433$request_uri;

**Comment by stianst** [comment]
We believe this is fixed in https://github.com/keycloak/keycloak-ui/pull/3373

Could you please try the nightly release (quay.io/keycloak/keycloak:nightly) and check if that works?

**Comment by stianst** [comment]
What you're trying to achieve is a bit of an edge-case, which is why we introduced the ability to specify the full URL. The following should work with 19.0.2:
```
--hostname-url=https://accounts.xxx.ext_ip.nip.io
```
