### ISSUE TITLE
Update OpenShift REST client to fix a critical vulnerability on the transitive dependency com.squareup.okhttp3:okhttp

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#14641]
# Overview

[com.squareup.okhttp3:okhttp](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp) is a HTTP & HTTP/2 client for Android and Java applications and a transitive dependency coming from OpenShift REST Client.

Affected versions of this package are vulnerable to Information Exposure. When there's an illegal character in a header value, an `IllegalArgumentException` is thrown whose message includes the full header value.

# Remediation

Upgrade OpenShift REST Client fixed it on 9.0.5.Final release which can be a breaking change for us.

# References

-   [GitHub Commit](https://github.com/square/okhttp/commit/1fd7c0afdc2cee9ba982b07d49662af7f60e1518)
-   [GitHub Issue](https://github.com/square/okhttp/issues/6738)
-   https://github.com/square/okhttp/issues/6738

**Comment by ahrycej** [comment]
I am scanning latest keycloak 20.0.2 with anchore enterprise (grype enginne) and I still find vulnerable okhttp
/opt/keycloak/lib/lib/main/com.squareup.okhttp3.okhttp-3.14.9.jar

it need to be updated to 4.x could you resolve it?

**Comment by abstractj** [comment]
@ahrycej please refer to our nightly builds considering that they contain the latest updates. If the issue persists, please create a new GH issue. 
```
trivy image --ignore-unfixed quay.io/keycloak/keycloak:nightly
```
We don't keep track of comments on closed issues on GH.
