### ISSUE TITLE
(API)Logout: Able to logout using different server refresh token and access token(Login from QA AWS server and logout from Dev AWS server using same Access/Refresh token)

### ISSUE THREAD

**Issue by Afzalkhan644** [keycloak/keycloak#14647]
### Scenario-
When we are using the Access token and Refresh token of different server(Login QA Server) and using it in (DEV-Server) for Logout API.

### Version

16.1.1

### Expected behavior

User should not able to use same refresh token and access token for different server. It should throw unauthorized error

### Actual behavior

User able to logout with invalid refresh token and access token(any value)

### How to Reproduce?

Test Data:
Environment : QA-AWS, Dev-AWS
QA-AWS API URL for Login-  http://[<host>:<port>](http://localhost:8001/auth/realms/demo/.well-known/openid-configuration)/auth/realms/<realm_name>/protocol/openid-connect/token
**Request Body-GRANT_TYPE,CLIENT_ID,CLIENT_SECRET,USERNAME,PASSWORD**
Dev-AWS API URL for Logout- [http://<host>:<port>/auth/realms/demo/protocol/openid-connect/logout]
**Request Body- client id , client secret,access token,refresh token**

### Anything else?

 even using any junk access & refresh tokens  for logout- it is always giving positive response

**Comment by Suhita1234** [comment]
A new ticket has been reported,please find reference https://github.com/keycloak/keycloak/issues/14554 for more details-

**Comment by stianst** [comment]
Please upgrade to the latest Keycloak, and check out https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout. You should pass the ID token, not the access/refresh tokens.
