### ISSUE TITLE
ciba authentication policy not found in keycloak 19

### ISSUE THREAD

**Issue by yamanawad-monty** [keycloak/keycloak#14650]
### Describe the bug

according to the documentation, the ciba policy is still active and still a feature in the lastest keycloak version, but the problem is while im making a post request to http://localhost:8080/realms/XXXXX/protocol/openid-connect/ext/ciba/auth
with all the url-encoded params satisfied and verified, im getting a 503 service unavailable status code;
and the following response is what im getting:
**{
    "error": "server_error",
    "error_description": "Failed to send authentication request"
}**

### Version

19.0.1

### Expected behavior

it should return a authentication request id in the response body

### Actual behavior

**{
    "error": "server_error",
    "error_description": "Failed to send authentication request"
}**

### How to Reproduce?

just use the latest version of keycloak and try to use ciba authentication.

### Anything else?

in addition, the ciba policy is mentioned in the lastest documentation of keycloak and is referenced by :
realm settings-----> policies----> ciba policy
but this is false and it is not found there, thank you

**Comment by mposolda** [comment]
@yamanawad-monty I suggest to try with latest Keycloak 21 and see if it helps.

Other than that, I can just add that some issue happened during parsing your request, but it is not clear which one as the exception is currently not logged anywhere. I've added PR with more logging, which may help to nail this: https://github.com/keycloak/keycloak/pull/17246

In the meantime, I also suggest you to enable TRACE logging for `org.keycloak` and see if something helpful is still logged when your request is being sent

**Comment by mposolda** [comment]
@yamanawad-monty If you still reproduce with latest Keycloak 21 release, then please use the Keycloak nightly build, which will include my PR https://github.com/keycloak/keycloak/pull/17246 . Latest Keycloak nightly release is here: https://github.com/keycloak/keycloak/releases/tag/nightly . If still reproducible, please eventually re-open and reply here with the error from the log (error should in the log should be available due the change in https://github.com/keycloak/keycloak/pull/17246).

Just a note that you will need to retrieve Keycloak nightly not earlier than tomorrow as the PR was merged right now, so obviously is not yet available in the today's Keycloak nightly release.
