### ISSUE TITLE
Ckey 19.0.2 in k8s environment Admin Console keeps spinning

### ISSUE THREAD

**Issue by mtmvivek** [keycloak/keycloak#14662]
### Describe the bug

After deploying keycloak 19.0.2 (Quarkus) in the k8s cluster, When tried to access the admin url, it is keep spinning, page is not getting loaded. We are using ingress and accessing the url through a edge node ip. But, when clicking the admin console link from the main page, the html page url has port 8443 automatically added to the ip, This happens only for the html file, all other image files are having right url (seen through developer console), Hence the page is keep spinning.

 

We use,  KC_HTTP_RELATIVE_PATH to have the custom path /access. We also explored KC_HOSTNAME_URL which is solving the problem as work around but by using this we end up in specifying absolute urls, there are k8s clusters with more than 1 edge ip, so we are not sure how use this. One of consequences of setting KC_HOSTNAME_URL is we need to set KC_HOSTNAME_STRICT to false which is not recommended

 

Also, Getting error message when using this with KC_HOSTNAME_STRICT. Lastly, There is a restriction in using KC_HOSTNAME and KC_HOSTNAME_URL together. So we are struck, how to achieve /access uri to get admin ui loaded

### Version

19.0.2

**Comment by stianst** [comment]
We believe this is fixed in https://github.com/keycloak/keycloak-ui/pull/3373

Could you please try the nightly release (quay.io/keycloak/keycloak:nightly) and check if that works?

**Comment by cen1** [comment]
I can reproduce this with `KC_PROXY=edge` when running in dev environment (so, no actual proxy in front). Setting the hostname, port and strict variables indeed works. 

This is on nightly.

The old `PROXY_ADDRESS_FORWARDING=true` did not have this side effect.

**Comment by stianst** [comment]
> I can reproduce this with `KC_PROXY=edge` when running in dev environment (so, no actual proxy in front). Setting the hostname, port and strict variables indeed works.
> 
> This is on nightly.
> 
> The old `PROXY_ADDRESS_FORWARDING=true` did not have this side effect.

Using `KC_PROXY=edge` without an actual reverse proxy is not going to work, so not sure why you're even trying to do that.

**Comment by stianst** [comment]
@mtmvivek I'm afraid I don't quite understand your description. Could you explain what you are trying to achieve? What you have configured? Also, if you could take a look at the developer console when loading the admin console that should help show what could be the problem.

**Comment by mtmvivek** [comment]
> @mtmvivek I'm afraid I don't quite understand your description. Could you explain what you are trying to achieve? What you have configured? Also, if you could take a look at the developer console when loading the admin console that should help show what could be the problem.

@stianst Let me give you a full picture, We are trying to install keycloak using helm chart in a K8s environment where we have different types of nodes (Controller - where we run helm/kubectl cmds, Worker, Edge & Deployment) . We successfully deployed keycloak connecting to a mariadb database and everything up and running. We have configured ingress to expose the ckey to outside world, So as the design, this is exposed through edge node ip (ngnix). So far everything is fine. 

But we need to expose the service/ui through a relative path /access like https://<edge-ip>:443/access. So, we set KC_HTTP_RELATIVE_PATH env variable and the intial page rendered  https://<edge-ip>:443/access and apis are working fine, But when we tried to click the admin console link, the ui was keep spinning. From the developer console saw that select1.html is adding port 8443 to edge ip to access, So we added KC_HOSTNAME_PORT as 443, after which this html page could get downloaded but still admin page is spinning.

Then we tried to set up KC_HOSTNAME_URL as https://<edge-ip>:443/access, We could able to see the admin screen and everything works fine but the issue is, We cannot hard code 1 edge ip in certain environment where there could be multiple edge nodes are in cluster. So we need a direction how to make this admin screen work without hard coding ips in configuration, Also, we tried KC_HOSTNAME, but saw error it can't set with KC_HOSTNAME_URL. Please advise...

**Comment by mtmvivek** [comment]
@stianst One more thing to mention, We tried the nightly build but the problem still there.

**Comment by mtmvivek** [comment]
@stianst Here are the list of KC environment variables: 
KC_DB=mariadb
KC_DB_POOL_MIN_SIZE=1
KC_DB_URL_PROPERTIES=?autoReconnect=true
KC_HOSTNAME_STRICT=false
KC_DB_URL_PORT=3306
KC_DB_POOL_MAX_SIZE=20
KC_DB_PASSWORD=pwdbuser
KC_DB_USERNAME=dbuser
KC_DB_URL_DATABASE=db4keycloak
KC_HTTPS_CIPHER_SUITES=TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256
KC_HTTP_RELATIVE_PATH=/access
KC_PROXY=edge
KC_HOSTNAME_PORT=443
KC_METRICS_ENABLED=true
KC_TRANSACTION_XA_ENABLED=true
KC_DB_URL_HOST=quarkdb201-cmdb-mysql.muthuvi.svc.cluster.local
KC_HTTPS_KEY_STORE_PASSWORD=keycloak
KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/certs/keycloak.jks
KC_HTTP_ENABLED=false

**Comment by stianst** [comment]
Hostname config in Keycloak is limited to Keycloak being exposed on a single URL, as you are using the edge-ip directly resulting in different "hostnames" you can not use the built-in hostname capabilities in Keycloak.

As you have used KC_HOSTNAME_STRICT=false none of the "hostname" related options should be applicable anymore. However, you do need to have an alternative way of restricting Host headers, as otherwise you leave yourself open to vulnerabilities there. You'd either need a custom hostname provider, or enforce this at the proxy level.

To get this stuff to work it should work with just KC_HOSTNAME_STRICT=false, and make sure the relevant X-Forwarded-* headers are included, such as X-Forwarded-Host, X-Forwarded-Port, etc.. Without this the dynamic hostname resolution which is enabled by setting strict=false is not able to know the correct host/port used when accessing it.

**Comment by stianst** [comment]
@pedroigor this is not really a bug, but I think we can enhance the docs around this stuff. I don't think we clearly mention what to do if default hostname stuff doesn't work, and the proxy guide mentions setting all the X-Forwarded-* headers, but doesn't mention when they are not needed (X-Forwarded-Proto|Host for instance shouldn't be needed, and probably ignored completely, if setting up the hostname provider properly). Maybe also check that `hostname-options` aren't applied when strict is false?

**Comment by stianst** [comment]
I'm going to close this issue and have opened an issue to discuss some enhancements we can make here around the documentation, and perhaps some other things. See https://github.com/keycloak/keycloak/issues/15018 for more details.
