### ISSUE TITLE
Keycloak 19.0.2 - LDAP User Change Password Error

### ISSUE THREAD

**Issue by joeyberkovitz** [keycloak/keycloak#14660]
### Describe the bug

When attempting to perform a password change for an LDAP backed user in Keycloak 19 (Quarkus), an error is thrown despite the password being changed in LDAP.

The error is: `Error saving password: Cannot destructure property 'id' of '(intermediate value).find(...)' as it is undefined.`

It appears that this may occur because the response to `users/USERID/credentials` does not include the LDAP password entry, so either that API would need to be updated to retrieve basic password info from LDAP, or the frontend could be adjusted to tolerate this scenario with the legacy LDAP connection at least until LDAP map storage is supported.

### Version

19.0.2

### Expected behavior

Password change succeeds without error

### Actual behavior

Error is thrown during password change

### How to Reproduce?

Attempt to change the password for an LDAP backed user in Keycloak

**Comment by justintime4tea** [comment]
Also, if I'm experiencing the same issue, the user interface continues to show "no credentials" when it should probably say something about being managed in/by LDAP? I checked LDAP to see a password present and then also was able to log in so I know this message is inaccurate at the least.

![image](https://user-images.githubusercontent.com/4065262/195113073-96b662d3-e3f1-45a1-bb80-6343510d3daa.png)

**Comment by epif4nio** [comment]
I'm also having the issues described by @joeyberkovitz and @justintime4tea in a custom user storage provider.
The error message shows up in the UI but not in the logs.

**Comment by ahus1** [comment]
I triaged this bug, and found the following: 

* I reproduced this problem in KC 19.0.1 with the new admin UI. For this version, I suggest switching to the old admin UI via 
   ```
   bin/kc.sh start-dev --features-disabled=admin2
   ```

* This error is no longer occurring in KC 20.0.5
* For the upcoming KC21 release, there is a UI that shows more details where the user changes the password:
   ![image](https://user-images.githubusercontent.com/3957921/220377251-5449142c-5377-45b7-9fd2-3ad62c5348cb.png)

So the original issue resolved in KC 20.0.5, with further improvement in KC21, therefore closing this issue.
