### ISSUE TITLE
Map-Storage: Clustering doesnt work

### ISSUE THREAD

**Issue by dominikschlosser** [keycloak/keycloak#14683]
### Describe the bug

When using the HotRod-Map-Storage with multiple instances behind a load-balancer, i get 404s in the WebUI when it tries to load resources like JS or CSS.

I noticed that the random-looking part behind /resources/ in the URL (/resources/z6yq4/common/keycloak/web_modules/@patternfly/...) seems to differ in each instance we start in this setup.

### Version

19.0.2

### Expected behavior

Each Keycloak-Instance in the cluster uses the same URLs when using HotRod-Map-Storage.

### Actual behavior

Each instance uses different URLs, differing by a random path-segment behind /resources/.

### How to Reproduce?

Use --storage=hotrod with the same --storage-hotrod-host in multiple keyloak-instances and check the resource-URLs. Just switching back to legacy-storage (by omitting the --storage-option) fixes the issue.

**Comment by mhajas** [comment]
This is not a problem of HotRod store only but in general of the new storage. To make this work at the moment, you need to run all instances with the same `-Dstorage-deployment-state-version-seed`. Please let me know if this doesn't work for you.

Here is CLI option description:
```
--storage-deployment-state-version-seed <type>
                     Experimental: Secret that serves as a seed to mask the version number of
                       Keycloak in URLs. Need to be identical across all servers in the cluster.
                       Will default to a random number generated when starting the server which is
                       secure but will lead to problems when a loadbalancer without sticky sessions
                       is used or nodes are restarted.
```

I created an issue: https://github.com/keycloak/keycloak/issues/14712 to add possibility to avoid this workaround.

**Comment by hmlnarik** [comment]
Thank you for reporting this issue.
As @mhajas mentioned above, this is expected behaviour at this moment which will be addressed in #14712. Closing this one as duplicate.

**Comment by kkcmadhu** [comment]
i tried adding -Dstorage-deployment-state-version-seed to all my keycloak instances, and this does not help.. am i missing something?

**Comment by mhajas** [comment]
@kkcmadhu Can you please share the whole command you used?

**Comment by kkcmadhu** [comment]
> i tried adding -Dstorage-deployment-state-version-seed to all my keycloak pods, and this does not help.. am i missing something?

I had the property in my k8s config file. this worked        
 - name: KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED
    value: "blah"

**Comment by v-kamerdinerov** [comment]
@mhajas Unfortunately doesn't work for me, i'l added env var `KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED` to my deploymet, also trying start with params:

`/opt/keycloak/bin/kc.sh start --import-realm --cache-stack=kubernetes --storage-deployment-state-version-seed "${KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED}"`

**Comment by hmlnarik** [comment]
@v-kamerdinerov Thank you for providing the command.
The `--cache-stack` is for legacy store, while `--storage-...` options are for map storage. The two do not work together.
What is desired setup? Using the legacy storage or trying out the new one?

**Comment by v-kamerdinerov** [comment]
@hmlnarik I want run a 'production ready' keycloak in kubernetes, with several replicas behind reverse proxy (haproxy).

So, i need drop `--cache-stack=kubernetes`, and aslo this variables:
 `KC_CACHE: "ispn"`
?

**Comment by hmlnarik** [comment]
This discussion is about the new (map) storage, and your scenario is different. You certainly need to drop the `storage-deployment-state-version-seed` which is map-storage (new storage) which is not for production.
In order to get a more relevant answer, I suggest you to start a new discussion in Q&A.

**Comment by kkcmadhu** [comment]
storage-deployment-state-version-seed , is not applicable to legacy store..
 
when all the 3 replicas of keycloak points to same db/schema. they will automatically have the same seed version, no explicit setting required there.. 
hope you are not using local h2 db.

**Comment by kkcmadhu** [comment]
> What configuration do I need to run keycloak in kubenetes, with multiple replicas and the **storage-deployment-state-version-seed** parameter set?

torage-deployment-state-version-seed , is not applicable to legacy store..

when all the 3 replicas of keycloak points to same db/schema. they will automatically have the same seed version, no explicit setting required there..
hope you are not using local h2 db.

I Agree with @hmlnarik  ,  better to move this discussion to seperate thread. its not related to new store.

**Comment by v-kamerdinerov** [comment]
@kkcmadhu  @hmlnarik Okay, thanks for you help anyway :)

Let's continue here https://github.com/keycloak/keycloak/discussions/16972
