### ISSUE TITLE
admin user creation fails

### ISSUE THREAD

**Issue by kychandar** [keycloak/keycloak#14698]
### Describe the bug

Using keycloak 19.0.2  (quay.io/keycloak/keycloak:19.0.2) with postgress.
Initial admin user is created.
Lost the credentials for initial admin user.
Trying to create a new user by using docker ENV KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD.

This returns an error that user with username already exist, but actually no such user exist in keycloak.
I tried replicating the issue in a fresh instance, the issue repeated.

Kindly let me know if I'm missing something

### Version

19.0.2

### Expected behavior

User must be created if the username doesn't exist.

### Actual behavior

The user is not getting created even if the username doesn't exist.

### How to Reproduce?

1. Create a running keycloak instance (quay.io/keycloak/keycloak:19.0.2, with postgres) with docker appropriate envs (KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD)
2. Stop the instance
3. Try to create a new user with KEYCLOAK_ADMIN env 

### Anything else?

This would serve as a alternative if we lose the admin creds.

**Comment by abstractj** [comment]
@kychandar could you please share the details of step 3 and how you created the user?

**Comment by kychandar** [comment]
@abstractj 
I use KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD docker environment variables to create a new admin user in existing KC instance.
I get below error,
![image](https://user-images.githubusercontent.com/47603557/194546020-ed182144-7c2d-468e-b673-b6a7c7a8846d.png)

I have made sure that there is no user with username "admin"

**Comment by abstractj** [comment]
@kychandar could you please share step by step the list of commands? I just want to make sure that I'm not missing anything.

**Comment by abstractj** [comment]
Thanks for taking the time to submit this issue. However, we were unable to reproduce the mentioned steps. I'm closing it due to lack of activity.

If you have the time to add more details and check the [latest releases of Keycloak](https://www.keycloak.org/downloads), please reopen this issue, including a reproducer.
