### ISSUE TITLE
Documentation realm import

### ISSUE THREAD

**Issue by suikast42** [keycloak/keycloak#14693]
### Describe the bug

![image](https://user-images.githubusercontent.com/5046525/193473441-dac06c66-9f52-4e3c-961b-91a2a8959929.png)

The documentation is not so clear about the absoulte path of the import directory. 

After one day wasting I found out that the data/import must be in /opt/keycloak/. 

### Version

19.0.2

**Comment by stianst** [comment]
Where else would it be?

**Comment by suikast42** [comment]
> Where else would it be?

From your perspective it's clear. But from my my perspective as an user it is not.

**Comment by stianst** [comment]
That's why I'm asking

**Comment by suikast42** [comment]
I have no issue with that location. That's not clear in the documention :-)

**Comment by stianst** [comment]
I'm asking to understand why you find the documentation unclear, as I can't think of anywhere else it could be.

For the record I didn't write this or implement it, so reading it the first time when looking at this issue.

**Comment by mabartos** [comment]
@suikast42 Thanks for creating this issue!

The documentation for the Realm import was improved in this #13546 PR. I believe it's more clear now. 
Unfortunately, these changes are not propagated to keycloak.org website yet. 

@stianst How often are the changes for guides updated on the website?

**Comment by stianst** [comment]
Docs are updated for new releases, not separately
