### ISSUE TITLE
Email field that is not required still renders with an asterisk in registration form

### ISSUE THREAD

**Issue by skershaw** [keycloak/keycloak#14703]
### Describe the bug

I set
```
registration_allowed = true
registration_without_email = true
```
I can register a user without providing an email, but the email field in the registration form still renders with an asterisk even though it is not required.  The asterisk is outside of the label element, so simply changing the display name of the email field doesn't solve the issue.  

### Version

19.0.2

### Expected behavior

The asterisk which denotes a field as required should not be displayed on the registration form when the field is not required.

### Actual behavior

The email field still displays an asterisk when it is not required for registration.

### How to Reproduce?

Set
```
registration_allowed = true
registration_without_email = true
```
and try to register a user.

**Comment by sschu** [comment]
Where exactly did you configure "registration_without_email = true"?

**Comment by mposolda** [comment]
There is no further response to the question by @sschu . Moreover I am not aware of any "registration_without_email" settings. So rejecting this. Feel free to re-open, but then please answer the question above and add more details to steps to reproduce.
