### ISSUE TITLE
Make sure testsuite passing on FIPS enabled RHEL host with BCFIPS (non-approved mode)

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#14729]
This is about having Keycloak testsuite passing on:
- FIPS enabled RHEL 8.6 host
- FIPS enabled OpenJDK 11
- Keycloak quarkus distribution with BCFIPS configured (non-approved mode for now)
- Ideally OpenJDK security providers to contain only trusted FIPS providers. For example not Sun and SunECP providers - details https://access.redhat.com/documentation/en-us/openjdk/11/html-single/configuring_openjdk_11_on_rhel_with_fips/index#ref_openjdk-default-fips-configuration_openjdk

This will require more changes and hence likely more separate PRs will be needed to achieve this. Individual subtasks are:
- Make possible Keycloak working on HTTPS on the FIPS enabled RHEL 8.6 host. Use keystore working with BCFIPS provider (so ideally PKCS12 or BCFIPS. To be investigated which of those is better. BCFIPS is specific to Bouncycastle, however Pkcs12 keystore not available on BCFIPS approved mode. Ideally to have both keystore types working)

- Make some initial test working with quarkus distribution on the FIPS host (EG. LoginTest)

- Figure the other failing tests and make sure to have them passing. To be investigated what individual subtasks are needed based on the failing tests

- Possibly create GH action build, which will allow to test the same setup as the FIPS enabled host from above

### Subtasks
- #14886
- #14964 
- #14965 
- #14966 
- #14967 
- #14968 
- #14969

**Comment by mposolda** [comment]
All the subtasks are fixed and testsuite should be passing now. So I am closing this. There is no concrete PR associated with this task (it was closed as side-effect of the work done in subtasks).

**Comment by rsvoboda** [comment]
Hi @mposolda. I have question about the GH Actions part. I looked at https://github.com/keycloak/keycloak/pull/14895/files and GH Action is using normal Ubuntu runner without any tweaks of JVM.

Were you able to have FIPS enabled RHEL host GH Actions or you need to rely on Jenkins runners in RH lab?
