### ISSUE TITLE
Client Authentication SPI are not considered

### ISSUE THREAD

**Issue by adaumann** [keycloak/keycloak#14738]
### Describe the bug

I developed a client authentication SPI which should check a customer token (from HTTP Request). Because of the bug #14735 I started to reimplement the client credentials check in the SPI and used just my SPI in the client authorisation flow. This will not work either because the client authenticator type from the "Client" must match the ClientAuthorisationFactory Provider ID. 

### Version

18.0.2

### Expected behavior

The custom SPI should be executed, even if the provider ID and the client authenticator type is different.

### Actual behavior

The authentication fails, but the SPI has a success state

### How to Reproduce?

Use a client with client-credentials (confidental, Service Account)
Write a ClientAuthentication SPI and use it as single execution step in a client authentication flow. (Change the client binding first)

### Anything else?

As you see in the class "ClientAuthenticationFlow":´

````
                String expectedClientAuthType = client.getClientAuthenticatorType();            // returns "client-secret" !!!

                // Fallback to secret just in case (for backwards compatibility). Also for public clients, ignore the "clientAuthenticatorType", which is set to them and stick to the
                // default, which set the client just based on "client_id" parameter
                if (expectedClientAuthType == null || client.isPublicClient()) {
                    if (expectedClientAuthType == null) {
                        ServicesLogger.LOGGER.authMethodFallback(client.getClientId(), expectedClientAuthType);
                    }
                    expectedClientAuthType = KeycloakModelUtils.getDefaultClientAuthenticatorType();
                }

                // Check if client authentication matches
                if (factory.getId().equals(expectedClientAuthType)) {              // is not hit because SPI provider Id must be different !!!
````

**Comment by adaumann** [comment]
I think it works as designed, you have to add the correct client validation in the Keycloak Client.

**Comment by mposolda** [comment]
@adaumann Thanks! I am closing and also your other issue. Please re-open if some of the issues is still valid.
