### ISSUE TITLE
Client Authentication does not recognize execution step

### ISSUE THREAD

**Issue by adaumann** [keycloak/keycloak#14735]
### Describe the bug

I wrote an ClientAuthenticator SPI which should check if a customer token (from the HTTP Request) is valid. Additionally a normal client-secret aus Service Account should handled too according to the client. I changed the authorisation client bindung to the new client flow I copied from "clients" flow.  

![image](https://user-images.githubusercontent.com/94932945/194043868-211411f5-b18c-4130-87a0-2176e0055ed2.png)

My assumption is that the custom token AND the clientId Secret is executed, because both are required. But the token validate is not executed

### Version

18.0.2

### Expected behavior

Both execution steps are executed. 

### Actual behavior

The token validation is not executed. 

### How to Reproduce?

* Create client with clientId+secret (as Service Account)
* Write SPI from type ClientAuthentification and in provider method: "authenticateClient" return context.Success() and deploy
* Change Authrosation binding client* and use new SPI and use "clientId With Secret" client
* 

### Anything else?

In the debug session, the execution steps are not considered all (n=1)

![image](https://user-images.githubusercontent.com/94932945/194045196-2cdd7f6d-0a85-468b-8ab3-1e4bed6f3e03.png)

According to the source code (18.0.2 and 19.0.2) the executions are handled this way:
* If there are required executions, only the first one is taken
* Alternativ executions are taken as list

````
    protected List<AuthenticationExecutionModel> findExecutionsToRun() {
        List<AuthenticationExecutionModel> executionsToRun = new LinkedList<>();
        List<AuthenticationExecutionModel> finalExecutionsToRun = executionsToRun;
        Optional<AuthenticationExecutionModel> first = processor.getRealm().getAuthenticationExecutionsStream(flow.getId())
                .filter(e -> {
                    if (e.isRequired()) {
                        return true;
                    } else if (e.isAlternative()){
                        finalExecutionsToRun.add(e);
                        return false;
                    }
                    return false;
                }).findFirst();

        if (first.isPresent())
            executionsToRun = Arrays.asList(first.get());
        else
            executionsToRun.addAll(finalExecutionsToRun);

        if (logger.isTraceEnabled()) {
            List<String> exIds = new ArrayList<>();
            for (AuthenticationExecutionModel execution : executionsToRun) {
                exIds.add(execution.getId());
            }
            logger.tracef("Using executions for client authentication: %s", exIds.toString());
        }

        return executionsToRun;
    }
````

**Comment by mposolda** [comment]
Closing as per https://github.com/keycloak/keycloak/issues/14738#issuecomment-1451612430
