### ISSUE TITLE
URL fragments are not being removed upon successful login

### ISSUE THREAD

**Issue by cdecinkoKnight** [keycloak/keycloak#14742]
### Describe the bug

With my Vue 2 sample, this does not occur. However with Vue 3 and the 2.1.5-beta we are seeing the fragments left behind on the URL, in the user's address bar. This feels like valuable information is being leaked, or at least made more visible. It can also be confusing to the user and will create broken URLs if they bookmark or share the page link.

### Version

17.0.1

### Expected behavior

After the user logins, they should see a clean URL in the browser address bar.

### Actual behavior

The user sees the entire hash in the browser address bar even when specifying history mode, not hash mode.  According to the RFC, that's a no no and not in compliance: https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2

This is what a user sees:  http://localhost:9000/home/#state=3cedca45-59cc-43e2-aadc-88c07a14dca2&session_state=e577d7df-38bc-49d9-87a8-a638c6393d4b&code=806f06da-84e6-4328-ac98-15c4c59bad42.e577d7df-38bc-49d9-87a8-a638c6393d4b.f2b00725-0b84-4284-a625-23cba3b427f2

### How to Reproduce?

Specify history mode in the router settings and login via Keycloak.

### Anything else?

According to the RFC, that's a no no and not in compliance: https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2

**Comment by stianst** [comment]
Are you using keycloak.js?

**Comment by cdecinkoKnight** [comment]
Yes

Are you using keycloak.js?

-

**Comment by lexcao** [comment]
Could you please provide minimal reproduction steps to help me debug?
If you're using the `keycloak.js` it would consume the fragment and remove it automatically.

**Comment by T0miii** [comment]
I have the same issue with my Vue JS SPA. 
The fragment is an issue cause its messing up the frontend side routing.

**Comment by MarkTallentire** [comment]
We have this issue with a Vue3 app running on vite. Our init contains the following:

`await keycloak.init({
      adapter: 'default',
      responseMode: 'query',
      checkLoginIframe: true,
      onLoad: 'check-sso',
      pkceMethod: 'S256',
    });`

Our URL still contains fragments.  i.e `http://localhost:9000/edi?state=cea3b4f8-3738-4675-818c-0986aed60e84&session_state=b5cd272a-f388-46ab-b96c-a820826797c1&code=081bce02-6f74-49ec-a1ec-f0f1070c2cf8.b5cd272a-f388-46ab-b96c-a820826797c1.75436a41-c0bf-49ed-8a27-3eeb758f105e`

This occurs locally and on production servers.

Any other ideas as to the cause, running the debugger i can see that keycloak replaces the url but then it re-appears.

**Comment by lexcao** [comment]
Hi @MarkTallentire 

I see there is no `#` fragement in the url you provided.
Do you mean the query params?

Could you please try `silentCheckSsoRedirectUri` when using `check-sso`,
which would redirect with params to a silent callback url instead of current url

Here is the [doc](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter) you can refer to.

**Comment by MarkTallentire** [comment]
Hi @lexcao 

Sorry yes, i meant the query params.

I've gone ahead and added the above so my init is now:

` await keycloak.init({
      adapter: 'default',
      responseMode: 'query',
      checkLoginIframe: true,
      onLoad: 'check-sso',
      pkceMethod: 'S256',
      silentCheckSsoRedirectUri: window.location.origin + '/silent-check-sso.html'
    });`

and my silent-check-sso.html is

`
<!DOCTYPE html>
<html>
<body>
<script>
  parent.postMessage(location.href, location.origin)
</script>
</body>
</html>
`

Still seeing the same params in my url though :(
![image](https://user-images.githubusercontent.com/26217534/201132829-07b4d65c-37fe-47ed-8cc9-a782bd2bfc72.png)

I also checked just to make sure the URL was correct and I can navigate to it manually and see the script tags are correct in the console.

![image](https://user-images.githubusercontent.com/26217534/201133133-be36974e-51fb-4e37-990b-328780b28763.png)

**Comment by arcandspark** [comment]
I just ran into this bootstrapping a new project using Vue and Keycloak. Full disclosure: my Javascript knowledge is a decade out of date and I am just starting on catching up, I don't know much about how modules and npm work.

But, I have managed to work around this issue. This smelled like a conflict between the history manipulation by both keycloak-js and vue-router. I found that ensuring that `keycloak.init()` was called before `vue-router` was imported would prevent the authentication fragment from remaining on the URL after page load.

It looks like during the initialization of the vue-router module the function `useHistoryStateNavigation()` is grabbing `window.location` and using that for the path it will evaluate for routing. After it runs guard checks and does other initialization, vue-router pushes this value into the history during `finalizeNavigation()`, which ultimately makes the fragment re-appear in the URL in the browser window.

My workaround so far is to put `keycloak.init()` in its own script tag before loading my app's `main.js`. I store the resultant promise in a var in window, and then await on that promise in `main.js` (first line):

**index.html**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="/kc/js/keycloak.js"></script>
    <script>
        window.keycloak = new Keycloak({
            realm: "[REDACTED]",
            url: "[REDACTED]",
            clientId: "[REDACTED]"
        });

        const kc_options = {
            onLoad: "login-required",
            checkLoginIframe: false,
            flow: "standard"
        }

        window.kc_init = keycloak.init(kc_options);
    </script>
    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite App</title>
</head>
<body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
</body>
</html>
```

**main.js**

```
await window.kc_init;

import { createApp } from 'vue';
import { createPinia } from 'pinia';

import App from './App.vue';
import router from './router';

import './assets/main.css';

const app = createApp(App);

app.use(createPinia());
app.use(router);

app.mount('#app');
```

**Comment by T0miii** [comment]
I think its just the .use(router)

Keycloak init needs to happen before the usage of the router,

**Comment by arcandspark** [comment]
I just confirmed in my project that the vue-router codepath responsible for this race condition executes as a result of vue-router being imported. I re-created the setup where keycloak-js is imported as a module and `keycloak.init()` is executed and waited on before calling `app.use(router)`.

This seems like a vue-router issue and not a keycloak bug. The module init for vue-router is capturing a value from `window.location` and using it later for routing before the caller executes app.use(router), removing the caller's ability to control the flow. I am just getting started with modules so possibly wrong here, but it does not look like there is a deterministic way to order imported module top-level code execution.

The issue for Keycloak to address is the documentation page here: https://www.keycloak.org/securing-apps/vue

This page shows the pattern that will result in the state fragment being re-added to the user visible URL (at least with vue-router 4.1.5). I will dig into this on the vue-router side here and see if there is a way to reset the navigation path it will evaulate when `app.use(router)` is called.

I commented out `app.use(router)` below and, while routing is expectedly broken, the state fragment does not get re-added to the URL. This confirms that the value with the state fragment is captured during module import, but not used until the `app.use(router)` call. So if the value vue-router has grabbed can be fixed before this call, that would probably be the best workaround as it would allow Keycloak init in `main.js`.

**main.js code that has fragment issue:**
```
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import Keycloak from "keycloak-js";
import App from './App.vue';
import router from './router';

import './assets/main.css';

const app = createApp(App);

export const keycloak = new Keycloak({
    realm: "[REDACTED]",
    url: "[REDACTED]",
    clientId: "[REDACTED]"
});

const kc_options = {
    onLoad: "login-required",
    checkLoginIframe: false,
    flow: "standard"
}

await keycloak.init(kc_options);

app.use(createPinia());
app.use(router);

app.mount('#app');
```

**Comment by arcandspark** [comment]
I found a pattern that works when importing `keycloak-js` from `main.js`. Again, fair warning that I am a Javascript dinosaur - I don't know if this is a good way to use dynamic module imports or how compatible this is with across browsers. I gave it a quick test in current versions of Firefox / Edge / Chrome and it worked.

```
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import Keycloak from "keycloak-js";
import App from './App.vue';

import './assets/main.css';

export const keycloak = new Keycloak({
    realm: "[REDACTED]",
    url: "[REDACTED]",
    clientId: "[REDACTED]"
});
const kc_options = {
    onLoad: "login-required",
    checkLoginIframe: false,
    flow: "standard"
}

await keycloak.init(kc_options);

const app = createApp(App);
app.use(createPinia());

let r = await import('./router');
app.use(r.default);

app.mount('#app');
```

**Comment by T0miii** [comment]
If top level await is not supported by any browser this could be  also a solution:

```
  keycloak.init({
    onLoad: 'login-required',
  }).then(async (auth) => {
    if (auth) {
      try {
        let r = await import('./router');
        app.use(r.default);
        await r.default.isReady()
        app.mount('#app');
      }
      catch (e) {
        console.error(e)
      }
    }
  }).catch((e) => {
    useAppStore().user.token = null
    useAppStore().user.username = ''
    console.error(e)
  })
```

**Comment by T0miii** [comment]
Did anyone manage to make this work with nuxt.js? As i am aware of in nuxt we cant controle when the routes are loaded.

**Comment by Kingside88** [comment]
@T0miii I am struggeling to implement keycloakJs in nuxt 3. 
If I implement it as a plugin, I get error 500 - document not found. 
Can you please provide some help?
I created a ready to go project: https://github.com/Kingside88/nuxt3-primevue-starter-auth/tree/keycloakJs

**Comment by cdecinkoKnight** [comment]
We are using Keycloak with a Quasar Vue app, Quasar 2 and Vue 3. I'm not finding a way to specify that Keycloak loads before router. Any ideas?

**Comment by zsebedits** [comment]
The problem seems to be that `createWebHistory` is called when the router is imported in the `main.js` file. The solution we went with is to not call `createWebHistory` directly in the router definition, but export a function that builds the router on demand:

**router/index.js**
```js
import { createRouter, createWebHistory } from 'vue-router'

const routerOptions = {
  routes: [
    {
      path: '/',
      name: 'home',
      component: HomeView
    }
  ]
}

const initializeRouter = () => {
  routerOptions.history = createWebHistory(import.meta.env.BASE_URL)
  return createRouter(routerOptions)
}

export { initializeRouter }
```

**main.js**
```js
import { createApp } from 'vue';
import Keycloak from "keycloak-js";
import App from './App.vue';

// Import initializeRouter function
import { initializeRouter } from './router'

const app = createApp(App);

export const keycloak = new Keycloak({
    realm: "[REDACTED]",
    url: "[REDACTED]",
    clientId: "[REDACTED]"
});

const kc_options = {
    onLoad: "login-required",
    checkLoginIframe: false,
    flow: "standard"
}

await keycloak.init(kc_options);

// Call initializeRouter function after keycloak-js is fully initialized
app.use(initializeRouter());
app.mount('#app');
```

**Comment by nessergio** [comment]
> We are using Keycloak with a Quasar Vue app, Quasar 2 and Vue 3. I'm not finding a way to specify that Keycloak loads before router. Any ideas?

Hi! Hope you managed to fix your problem. I came also into this issue with quasar2. Here how I fixed it (also showing how to add bearer token to axios):
`export default route(async function (/* { store, ssrContext } */) {
  const createHistory = process.env.SERVER
    ? createMemoryHistory
    : (process.env.VUE_ROUTER_MODE === 'history' ? createWebHistory : createWebHashHistory)

  async function createRefreshTokenTimer (keycloak) {
    setInterval(() => {
      keycloak.updateToken(60).then(refreshed => {
        if (refreshed) {
          console.log('Token refreshed ' + refreshed)
          console.log(keycloak.token)
          api.defaults.headers.common.Authorization = `Bearer ${keycloak.token}`
        } else {
          // do not need to refresh, do something...
        }
      }).catch(() => {
        console.error('Failed to refresh token')
        api.defaults.headers.common.Authorization = ''
        window.location.reload()
      })
    }, 60000)
  }

  return new Promise(resolve => {
    const keycloak = new Keycloak({
      url: 'https://...',
      realm: '...',
      clientId: '...'
    })
    keycloak.init({
      onLoad: 'login-required',
      checkLoginIframe: false,
      'public-client': true
    }).then(async (authenticated) => {
      const Router = createRouter({
        scrollBehavior: () => ({ left: 0, top: 0 }),
        routes,
        // Leave this as is and make changes in quasar.conf.js instead!
        // quasar.conf.js -> build -> vueRouterMode
        // quasar.conf.js -> build -> publicPath
        history: createHistory(process.env.MODE === 'ssr' ? void 0 : process.env.VUE_ROUTER_BASE)
      })
      if (authenticated) {
        console.log('Authenticated')
        await createRefreshTokenTimer(keycloak)
        api.defaults.headers.common.Authorization = `Bearer ${keycloak.token}`
        resolve(Router)
      } else {
        console.error('Not authenticated')
        resolve(Router)
        // window.location.reload()
      }
    }).catch((error) => {
      console.error('Authentication failure', error)
      // window.location.reload()
    })
  })
})`

**Comment by jonkoops** [comment]
As mentioned before, this issue is due to a conflict between the router of a web framework (e.g. Vue, Nuxt, etc.) and Keycloak JS. The recommended solution is to always initialize Keycloak JS before initializing the framework, so that all parameters are removed from the URL by Keycloak JS.

I'd also like to point out that it could be worthwhile to configure the [`silentCheckSsoRedirectUri` option](https://www.keycloak.org/docs/latest/securing_apps/#using-the-adapter), which can prevent these parameters from being added to the URL, under certain conditions.

I am closing this issue, as there is nothing we need to fix on the Keycloak side of things.

**Comment by alexandrerbb** [comment]
> @T0miii I am struggeling to implement keycloakJs in nuxt 3. If I implement it as a plugin, I get error 500 - document not found. Can you please provide some help? I created a ready to go project: https://github.com/Kingside88/nuxt3-primevue-starter-auth/tree/keycloakJs

Hi,

Here's my workaround for Nuxt : 
https://github.com/alexandrerbb/nuxt3-keycloak-js

**Comment by cdecinkoKnight** [comment]
@alexandrerbb How would you adapt your solution to use a beforeEach route guard? I had to implement that as only the first page view was being secured or you would see a flash of the intended page before being redirected.

    import Keycloak, { type KeycloakConfig } from 'keycloak-js';

    export default defineNuxtPlugin((nuxtApp: any) => {
      const runtimeConfig = useRuntimeConfig();
      let isKeycloakInitialized = false;

      const initOptions: KeycloakConfig = {
        clientId: runtimeConfig.public.authClientId,
        realm: runtimeConfig.public.authRealm,
        url: runtimeConfig.public.authUrl,
      };

      const keycloak = new Keycloak(initOptions);

      nuxtApp.$keycloak = keycloak;

      // Middleware to check roles on each route navigation
      nuxtApp.$router.beforeEach(
        async (
          to: { path: string },
          _: any,
          next: (arg0: string | undefined) => void,
        ) => {
          if (!isKeycloakInitialized) {
            // Ensure Keycloak is initialized only once
            await keycloak
              .init({
                onLoad: 'login-required',
                checkLoginIframe: false,
                redirectUri: runtimeConfig.public.authRedirect,
              })
              .then(() => {
                console.warn('Keycloak initialized');
                isKeycloakInitialized = true;
              })
              .catch((error) => {
                console.error('Keycloak initialization error', error);
                // next('/error'); // Handle initialization error by redirecting to an error page
              });
          }

          console.warn(runtimeConfig.public.authAccessRole);

          // Check if the user has the required role for each route
          const isLoadboardUser = keycloak.hasRealmRole(
            runtimeConfig.public.authAccessRole,
          );
          // const isLoadboardUser = true;

          if (!isLoadboardUser && to.path !== '/unauthorized') {
            console.warn('does not have required role');
            // Redirect to unauthorized page only if not already on unauthorized page
            next('/unauthorized'); // Update this with your actual unauthorized page route
          } else {
            console.warn('has required role');
            // Continue to the next route if the user has the required role
            next(undefined);
          }
        },
      );
    });

**Comment by alexandrerbb** [comment]
> @alexandrerbb How would you adapt your solution to use a beforeEach route guard? I had to implement that as only the first page view was being secured or you would see a flash of the intended page before being redirected.
> 
> ```
> import Keycloak, { type KeycloakConfig } from 'keycloak-js';
> 
> export default defineNuxtPlugin((nuxtApp: any) => {
>   const runtimeConfig = useRuntimeConfig();
>   let isKeycloakInitialized = false;
> 
>   const initOptions: KeycloakConfig = {
>     clientId: runtimeConfig.public.authClientId,
>     realm: runtimeConfig.public.authRealm,
>     url: runtimeConfig.public.authUrl,
>   };
> 
>   const keycloak = new Keycloak(initOptions);
> 
>   nuxtApp.$keycloak = keycloak;
> 
>   // Middleware to check roles on each route navigation
>   nuxtApp.$router.beforeEach(
>     async (
>       to: { path: string },
>       _: any,
>       next: (arg0: string | undefined) => void,
>     ) => {
>       if (!isKeycloakInitialized) {
>         // Ensure Keycloak is initialized only once
>         await keycloak
>           .init({
>             onLoad: 'login-required',
>             checkLoginIframe: false,
>             redirectUri: runtimeConfig.public.authRedirect,
>           })
>           .then(() => {
>             console.warn('Keycloak initialized');
>             isKeycloakInitialized = true;
>           })
>           .catch((error) => {
>             console.error('Keycloak initialization error', error);
>             // next('/error'); // Handle initialization error by redirecting to an error page
>           });
>       }
> 
>       console.warn(runtimeConfig.public.authAccessRole);
> 
>       // Check if the user has the required role for each route
>       const isLoadboardUser = keycloak.hasRealmRole(
>         runtimeConfig.public.authAccessRole,
>       );
>       // const isLoadboardUser = true;
> 
>       if (!isLoadboardUser && to.path !== '/unauthorized') {
>         console.warn('does not have required role');
>         // Redirect to unauthorized page only if not already on unauthorized page
>         next('/unauthorized'); // Update this with your actual unauthorized page route
>       } else {
>         console.warn('has required role');
>         // Continue to the next route if the user has the required role
>         next(undefined);
>       }
>     },
>   );
> });
> ```

https://github.com/alexandrerbb/nuxt3-keycloak-js/blob/master/plugins/keycloak_init.client.ts

Is your code snippet working ?

I think you can implement your code in the ``setup()`` method. We use the ``"app:created"()`` hook to clean the URL parameters used by keycloak at the right lifecycle step.

**Comment by cdecinkoKnight** [comment]
@alexandrerbb it works, as far as securing the pages. It doesn't secure the server/api endpoints for some reason.

**Comment by alexandrerbb** [comment]
Maybe as we use a client-side keycloak adapter and a client-side nuxt plugin. Server applications should use/verify keycloak (JWT) tokens provided to client by keycloak-js.

**Comment by cdecinkoKnight** [comment]
@alexandrerbb I swapped in your code, leaving off the silent check and it works. Getting a linter warning for "Async method 'app:created' has no 'await' expression."

Now, I wonder if I can add my route guards to check for roles.

**Comment by alexandrerbb** [comment]
> @alexandrerbb I swapped in your code, leaving off the silent check and it works. Getting a linter warning for "Async method 'app:created' has no 'await' expression."
> 
> 
> 
> Now, I wonder if I can add my route guards to check for roles.
> 
> 

I think you can acheive that by creating a nuxt middleware (i.e : https://github.com/alexandrerbb/nuxt3-keycloak-js/blob/master/middleware/require_auth.ts).

**Comment by Ratatinator97** [comment]
> > @T0miii I am struggeling to implement keycloakJs in nuxt 3. If I implement it as a plugin, I get error 500 - document not found. Can you please provide some help? I created a ready to go project: https://github.com/Kingside88/nuxt3-primevue-starter-auth/tree/keycloakJs
> 
> Hi,
> 
> Here's my workaround for Nuxt : https://github.com/alexandrerbb/nuxt3-keycloak-js

Thanks for your code. Unfortunately, I have an error with it in PWA mode (SPA/SSR False) with Workbox caching enabled.
`[nuxt] error caught during app initialization Error: Page not found: /silent-check-sso.html?state=6a36cc7e-0ebe-4fea-865e-93827469e2f6&session_state=1d517115-7d75-440b-8e07-47fd38eda691&code=e9157197-bcf4-425e-9d6c-21f963e85dfb.1d517115-7d75-440b-8e07-47fd38eda691.26a9070a-b97d-4e9c-84c0-d287b09bd68d`

**Comment by Sjoerd82** [comment]
In Quasar it makes sense to load Keycloak-js during "boot". The boot process takes place after pinia and the router are imported. I've not been able to get rid of these "URL fragments", maybe I'm missing or misreading something in this thread thusfar, but it seems that there is no right solution at this point (also, as stated earlier, this is not a Keycloak issue).

FWIW, this is my workaround, maybe it's helpful for anyone. It simply instructs the router to remove the query in the `fnOnInitSuccess `-function. I've not tested this beyond a few basic login/logoffs, there could be undiscovered issues. And if there is an actual working solution for Quasar, I'd be happy to hear it :-)

My keycloak.ts boot file:
```ts
import { boot } from 'quasar/wrappers'
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'
import { VueKeycloakInstance } from '@dsb-norge/vue-keycloak-js/dist/types'

const serverUrl = import.meta.env.VITE_KC_URL
const realmName = import.meta.env.VITE_KC_REALM
const clientId = import.meta.env.VITE_KC_CLIENT_ID

const fnOnReady = (store, keycloak) => {
    store.state.value.app.isAuthReady = true
}
const fnOnInitSuccess = (store, router, authenticated) => {
    store.state.value.app.isAuthenticated = authenticated
    router.replace({ query: null})
}
const fnOnAuthLogout = () => {
    store.state.value.app.isAuthenticated = false
}

export default boot(async ({ app, store, router }) => {
    const config = {
        url      : serverUrl,
        realm    : realmName,
        clientId : clientId,
    }
    const options = {
        config: config,
        init: {
            onLoad: 'check-sso',
            pkceMethod: 'S256',
            flow: 'standard',
            silentCheckSsoRedirectUri: `${location.origin}/silent-check-sso.html`,
            responseMode: 'query',
            checkLoginIframe: true,
        },
        onReady: (keycloak) => fnOnReady(store, keycloak),
        onInitSuccess: (authenticated) => fnOnInitSuccess(store, router, authenticated),
        onAuthLogout: fnOnAuthLogout,
    }
    app.use(VueKeyCloak, options)
    app.provide('keycloak', app.config.globalProperties.$keycloak)
})

// Allow usage of $keycloak in templates
declare module '@vue/runtime-core' {
    interface ComponentCustomProperties  {
        $keycloak: VueKeycloakInstance
    }
}

export { keycloakInstanceRef as keycloak }
```

Note: I use the pinia store to get $keycloak.ready and $keycloak.authenticaed, this way I don't have to block the app from waiting on Keycloak to be ready. I also use '@dsb-norge/vue-keycloak-js', a thin Vue wrapper.

**Comment by Sjoerd82** [comment]
Update: I am now running into situations where this is NOT a solution; not fully sure yet why. Looks like a timing issue related to the "error=login_required" state.

**Comment by JorensM** [comment]
I'm having this issue in a SvelteKit app.

**Comment by TangerineLabsIO** [comment]
Here is my quick fix for nuxt ^3.12.3

File is plugins/keycloak.client.ts

```
import Keycloak, { type KeycloakConfig } from 'keycloak-js';

export default defineNuxtPlugin({
    name: 'KeycloakClient',
    enforce: 'pre',
    hooks: {
        /**
         * Fix router issue, see : https://github.com/keycloak/keycloak/issues/14742
         */
        'app:created'() {
            const router = useRouter();
            router.currentRoute.value.query = {};
        },
    },
    setup: async function () {
        const runtimeConfig = useRuntimeConfig();
        const initOptions: KeycloakConfig = {
            url: runtimeConfig.public.keycloakUrl,
            realm: runtimeConfig.public.keycloakRealm,
            clientId: runtimeConfig.public.keycloakClientId,
        };

        const keycloakClient = new Keycloak(initOptions);

        await keycloakClient.init({
            redirectUri: useRuntimeConfig().public.keycloakRedirectUri,
            responseMode: 'query',
            onLoad: 'check-sso',
        });

        return {
            provide: {
                keycloakClient,
            },
        };
    },

});

```

**Comment by Balthasar42** [comment]
I prefer to work with a router guard. After I use Keycloak init I use the following Navigation Guard:

router.replace('') is working good for my app.

`ts
export const onBeforeEach: NavigationGuard = async (_to) => {
  const systemStore = useSystemStore()
  const authStore = useAuthStore()
  const appStore = useAppStore()

  if (firstLoad) {
    firstLoad = false
    systemStore.hydrating = true
    try {
      await authStore.init()
      router.replace('')
      systemStore.hydrating = false
    }
    catch (error) {
      console.error(error)
    }
  }

  await appStore.hydrate()
}

router.beforeEach(onBeforeEach)
`

**Comment by ksmith97** [comment]
I worked around this issue in Vue Router with an AuthGuard by having the authguard function return a new Location in the call made in the router's beforeEach.

Eg.
```
export default async function authenticated(
    to: RouteLocationNormalized,
    from: RouteLocationNormalized
) {
    const auth = await login(window.location.href);
    return { path: to.path, query: { ...to.query }, hash: window.location.hash }
}
...

router.beforeEach(async (to, from) => {
    // Ensure use authentication
    return await authenticated(to, from)
})

```

**Comment by AntonOvsyannikov** [comment]
> But, I have managed to work around this issue. This smelled like a conflict between the history manipulation by both keycloak-js and vue-router. I found that ensuring that `keycloak.init()` was called before `vue-router` was imported would prevent the authentication fragment from remaining on the URL after page load.

Yep. More precise looks like `createWebHistory` should NOT be called before complete Keycloak initialization. So instead of importing ready to user router object I just wrap it into function and it works fine.

```
// main.js
const app = createApp(App);

initKeycloak(() => {
  app.use(makeRouter());
  app.mount('#app');
});


// router.js
function makeRouter() {
  return createRouter({
    history: createWebHistory(),
    routes: [
      {path: '/', component: HomePage},
    ],
  });
}

export {makeRouter};
```
