### ISSUE TITLE
Addition of Custom User Attribute Filter to Users API Count Endpoint

### ISSUE THREAD

**Issue by wirmler** [keycloak/keycloak#14747]
### Description

Requesting the addition of the Custom User Attribute filter `q` to the `GET /{realm}/users/count` endpoint.

After referencing the codebase and API documentation, it appears that the `GET /{realm}/users/count` endpoint does not support filtering on custom user attributes.

Without it, the only solution is to count all results matching the custom user attribute filters from the `GET /{realm}/users` endpoint, which can be extremely slow depending on the filter criteria and the amount of users that are returned.

**Comment by gilvansfilho** [comment]
I think it is possible do it doing search in a way like search by ID PARAMETER in `UserResource` is done. Could I try that? Someone could point me where can I create test for this?

**Comment by Plunts** [comment]
@gilvansfilho I was doing more or less the same change than you. That way I also found the place to add the test, but for me it didn't succeed (seems like the q parameter isn't evaluated). If you need some inspiration, take a look at: https://github.com/keycloak/keycloak/compare/main...Plunts:keycloak:kc-14747

**Comment by gilvansfilho** [comment]
Hey @Plunts
Here things worked. Once I didn't find a way to add test to this thing I then made a build and then tested by requesting API.

Please see this https://github.com/keycloak/keycloak/pull/14893/
