### ISSUE TITLE
Admin Console does not load

### ISSUE THREAD

**Issue by lsoft-bho** [keycloak/keycloak#14775]
### Describe the bug

I have a keycloak instance running in a kubernetes cluster.
Trying to access the admin console leads to an endless loading screen.

Keycloak is behind a nginx ingress controller. The ingress terminates tls.
There are now errors in the developer console and all network requests from the browser complete successfully

### Version

19.0.1

Edit: I have tried nightly

### Expected behavior

The Admin Console Should load.

### Actual behavior

The loading screen never goes away.

### Anything else?

Environment Variables:
```
KC_HOSTNAME: keycloak.serveral.levels.of.subdomains.com // not actual host
KC_HOSTNAME_PORT: 443
KC_PROXY: edge
PROXY_ADDRESS_FORWARDING: true
```

**Comment by stianst** [comment]
Closing as this has already been reported
