### ISSUE TITLE
Kerberos Login Error

### ISSUE THREAD

**Issue by edumanish** [keycloak/keycloak#14792]
### Describe the bug

In our application we are supporting **Kerberos** authentication through keycloak.
Everything is working perfectly fine in the browser. 
Now we are trying to automate the login process using curl script by making same API calls as browser.
When we load our application in the browser there are in total 4 API calls made to get the access token. We were able to pass through 3 APIs in the curl script as well but while doing 4th API call in the Curl it is giving exception. Can you please help us to resolve the issue?
We are following below steps.
Step 1) We are closing all the existing sessions for the user in the keycloak.
![image](https://user-images.githubusercontent.com/113010936/194484039-5939a52b-4217-4906-9864-6c925a1b8b46.png)

Step 2) **REQUEST**: curl - - negotiate -u : -v -X ‘GET’ ‘**<APPLICATION_URL>**’
**RESPONSE**: Response code = 302
Location = **<APPLICATION_URL>**/oauth2/authorization/Kerberos
cookies = JSESSIONID=XXXX; XSRF_TOKEN=XXXXX

Step 3) **REQUEST**: curl - - negotiate -u : -v -X ‘GET’ ‘**<APPLICATION_URL>**/oauth2/authorization/kerberos’
**RESPONSE**: Response code = 302
Location = ‘**<APPLICATION_URL>**/auth/realms/Kerberos/protocol/openid-connect/auth?reponse_types=code&client_id=*****&scope=openid profile email&state=XXXX&redirect_uri=**<APPLICATION_URL>**/login/oauth2/code/Kerberos&nonce=XXX’

Step 4) **REQUEST**: curl - - negotiate -u: -v -X ‘GET’ ‘**<KEYCLOAK_URL>**/auth/realms/Kerberos/protocol/openid-connect/auth?reponse_types=code&client_id=*****&scope=openid profile email&state=XXXX&redirect_uri=**<APPLICATION_URL>**/login/oauth2/code/Kerberos&nonce=XXX’
**RESPONSE**: Response code = 302
Location = **<APPLICATION_URL>**/login/oauth2/code/Kerberos?state=XXXX&session_state=XXXX&code=XXXX

Step 5) **REQUEST**: curl - - negotiate -u : -v -X ‘GET’ ‘**<APPLICATION_URL>**/login/oauth2/code/Kerberos?state=XXXX&session_state=XXXX&code=XXXX’ -H ‘Cookie: JSESSIONID=XXXXX; XSRF_TOKEN=XXXXX’
**RESPONSE**: Response code = 302
Location = **<APPLICATION_URL>**/login?error

**SINCE  kerberos doesn't require user login and hence user agent is not needed**
![image](https://user-images.githubusercontent.com/113010936/194484239-69e63b45-320c-42d8-b68b-0c6bf54f9d96.png)

### Version

11.0.2

**Comment by stianst** [comment]
Do you mean Keycloak 11.0.2? If so can you please try with the latest release?

**Comment by stianst** [comment]
Authorization code flow is not supported outside of a user-agent
