### ISSUE TITLE
Error when using similar keys with different algorithms in a jwks for identity provider signature validation

### ISSUE THREAD

**Issue by martin-scheelke** [keycloak/keycloak#14794]
### Describe the bug

After upgrade to 19.0.2 from keycloak 18.0.1:

When using a jwks endpoint with similar keys that have the same 'kid', kty" and 'use', but different algorithms, the last key is always chosen for signature validation and the following error occurs:

2022-10-03 08:50:41,547 DEBUG [org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider] (executor-thread-2) Public keys retrieved successfully for model 145bab56-6a3a-4c79-9ae6-8086c07959d1::idp::f5bb6a5e-2a06-49fc-ac0d-40aef190fb3e. New kids: [nrzqxULxLmRsNrpDAe0snB+cr6M=, b+wtPGa0Kda47jXT5uVpiY2kh+k=]
2022-10-03 08:50:41,547 DEBUG [org.keycloak.broker.oidc.OIDCIdentityProvider] (executor-thread-2) Failed to verify token: 	: Key with algorithm RS512 and type RSA is incorrect for provider algorithm RS256
at org.keycloak.crypto.SignatureProvider.checkKeyForVerification(SignatureProvider.java:33)

For example, a key provider with algorithm RS256 is configured, the key with algorithm RS512 (last entry in the jwks) will be chosen from the jwks and a verification exception will be thrown.

### Version

19.0.2

### Expected behavior

This error started occurring after an upgrade from Keycloak 18.0.1 to Keyloak 19.0.2. 
The expected behavior is that for similar keys defined in the openam jwks, the key with the correct algorithm that matches an available Keycloak key provider will be selected. 

### Actual behavior

The last key is always selected for signature verification from a list of keys in a jwks with similar 'use', 'kid' and 'kty' but different 'alg' (algorithm). The other keys are not included in the list fetched from from the jwks.
Bug appears to be in the way org.keycloak.util.JWKSUtils.getKeyWrappersForUse(JSONWebKeySet keySet, JWK.Use requestedUse) creates a map of keys.

### How to Reproduce?

- Setup an identity provider in keycloak configured to use a jwks URL and to validate signatures.
- Create a jwks with list of keys with similar 'kid', 'kty', 'use' but different 'alg' (the other key parts can also be similar across the keys) using for example openam-provider (see end of this 
comment for an example list with dummy keys). Let the last key in the list of similar keys have an algorithm for which there is NO key provider setup in Keycloak.
- When attempting any operation that requires jwt signature validation, the following error occurs:

DEBUG [org.keycloak.broker.oidc.OIDCIdentityProvider] (executor-thread-2) Failed to verify token: 	: Key with algorithm RS512 and type RSA is incorrect for provider algorithm RS256
at org.keycloak.crypto.SignatureProvider.checkKeyForVerification(SignatureProvider.java:33)

{
        kid: '3',
        kty: 'RSA',
        alg: 'PS512',
        use: 'sig',
        e: 'AQAB',
        n: '2s3t1LBJxVpq......',
        d: 'Hv4aWQ0bdf.....',
        p: '9rjHyDLJllALP......',
        q: '4whieZi3S7y......',
        dp: 'i160VG4EHCoZP2.....',
        dq: 'TZ5iPHxPvl79fD.....',
        qi: '5maXjtEVKJGlrQ......',
      },
      {
        kid: '3',
        kty: 'RSA',
        alg: 'RS256',
        use: 'sig',
        e: 'AQAB',
        n: '2s3t1LBJxVpq......',
        d: 'Hv4aWQ0bdf.....',
        p: '9rjHyDLJllALP......',
        q: '4whieZi3S7y......',
        dp: 'i160VG4EHCoZP2.....',
        dq: 'TZ5iPHxPvl79fD.....',
        qi: '5maXjtEVKJGlrQ......',
      },
      {
        kid: '3',
        kty: 'RSA',
        alg: 'RS512',
        use: 'sig',
        e: 'AQAB',
        n: '2s3t1LBJxVpq......',
        d: 'Hv4aWQ0bdf.....',
        p: '9rjHyDLJllALP......',
        q: '4whieZi3S7y......',
        dp: 'i160VG4EHCoZP2.....',
        dq: 'TZ5iPHxPvl79fD.....',
        qi: '5maXjtEVKJGlrQ......',
      }

### Anything else?

The bug appears to be in the way the method:
```
org.keycloak.util.JWKSUtils.getKeyWrappersForUse(JSONWebKeySet keySet, JWK.Use requestedUse)
``` 
creates the map of keys from the jwks - the 'kid' alone is the key to the map so the last key in the jwks with the same 'kid' overwrites the others.

NOTE: It _is_ valid to have a list of keys in a jwks that have the same 'use', 'kid' and 'kty' but different 'alg' (algorithm) see the standard at:
https://www.rfc-editor.org/rfc/rfc7517#:~:text=member%20is%20OPTIONAL.-,4.5.%20%22kid%22%20(key%20id)%20parameter,-The%20%22kid%22%20(key

**Comment by stianst** [comment]
@mposolda can you take a look at this one? If this is valid we should try to get it resolved quickly.
