### ISSUE TITLE
Custom User Attributes not being imported 

### ISSUE THREAD

**Issue by manuschillerdev** [keycloak/keycloak#14829]
### Describe the bug

I try to import users to my realm via 
1) create realm -> from json 
2) partial import in realms.
The users contain custom attributes, that should also be generated via the import:

```json
{
  "realm": "test",
  "users": [
    {
      "username": "user@domain.tld",
      "enabled": true,
      "totp": false,
      "emailVerified": true,
      "firstName": "User",
      "lastName": "Name",
      "email": "user@domain.tld",
      "attributes": [
        {
          "mobilePhone": ["0172123456789"],
          "attr1": ["one"],
          "attr2": ["two"]
        }
      ]
    }
  ]
}
```

### Version

docker.io/bitnami/keycloak:19

### Expected behavior

The users should get created including their attribtues

### Actual behavior

The user and the realm get imported properly, but the attributes are not getting set.

### How to Reproduce?

see description above

**Comment by Vividious** [comment]
Hey!
The solution to this problem is really simple.
You should remove square brackets like this:

```json
{
  "realm": "test",
  "users": [
    {
      "username": "user@domain.tld",
      "enabled": true,
      "totp": false,
      "emailVerified": true,
      "firstName": "User",
      "lastName": "Name",
      "email": "user@domain.tld",
      "attributes": 
        {
          "mobilePhone": ["0172123456789"],
          "attr1": ["one"],
          "attr2": ["two"]
        }
    }
  ]
}
```

**Comment by manuschillerdev** [comment]
@Vividious thanks for your response!
in your Snippet you also have the brackets around the attributes, right?

Besides that, I tried it with and without the brackets but did not have any luck

**Comment by Vividious** [comment]
Hey!
I meant not putting square brackets after "attributes" key, as it's value is not a list.
If it comes for given attributes i.e. items inside "attributes" map, then yes.
I have square brackets there.

**Comment by manuschillerdev** [comment]
That solves my problem - thank you! @Vividious
