### ISSUE TITLE
Calling getTopLevelGroups is slow inside GroupLDAPStorageMapper#getLDAPGroupMappingsConverted

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#14820]
### Description

See https://issues.redhat.com/browse/KEYCLOAK-19230 and the related discussion and comments on that issue.

**Comment by ahus1** [comment]
To those watching this issue: The related PR has been backported to 22.0.5

**Comment by ahus1** [comment]
To those watching this issue: The related PR has been backported to 22.0.5
