### ISSUE TITLE
User password is visible on admin events tab

### ISSUE THREAD

**Issue by mkopeyka** [keycloak/keycloak#14843]
### Describe the bug

This issue exists in keycloak for a very long time.
I may create a user with pre-defined password via REST API.
I will see a request body on admin events tab with clear text password in case `Include Representation` option is activated for admin events.

### Version

19.0.2

### Expected behavior

The `representation` field of `admin_event_entity` table shouldn't contain a clear text password

### Actual behavior

The `representation` field of `admin_event_entity` table contains a clear text password

### How to Reproduce?

1. Turn on `Include Representation` option for admin events
2. Execute this query
```
curl -i -X POST \
   -H "Content-Type:application/json" \
   -d \
'{
  "username": "test.test@gmail.com",
  "enabled": true,
  "email": "test.test@gmail.com",
  "credentials": [
    {
      "type": "password",
      "value": "my strong password"
    }
  ]
}' \
 'http://localhost:8080/auth/admin/realms/test-realm/users'
```
3. check `representation` field of `admin_event_entity` table
4. you will see value `my strong password`

**Comment by lexcao** [comment]
Hi, I just created a fix PR https://github.com/keycloak/keycloak/pull/15355

**Comment by duc12597** [comment]
@lexcao This did not address the `UserResource.updateUser` method. When a password is provided when calling the update user API, the admin events representation still contains the clear text password.

**Comment by lexcao** [comment]
Hi @duc12597 
Could you provide the reproduce process on the latest Keycloak version?

I can see there is handling the UserRepresentation in the AdminEventBuilder.
https://github.com/keycloak/keycloak/blob/0f47071a299c0084ea4247deca06fc06500bf8af/services/src/main/java/org/keycloak/services/resources/admin/AdminEventBuilder.java#L256-L258

Also, I am using the following cURL and not reproduce.
```
PUT /admin/realms/{realm}/users/{id}

{"credentials":[{"type":"password","value":"123456"}]}
```
