### ISSUE TITLE
Client session lifespan doesn't consider user session lifespan

### ISSUE THREAD

**Issue by pjbober** [keycloak/keycloak#14854]
### Describe the bug

We're using rememberMe option set for 180 days in our realm and we noticed a lot of garbage client sessions due to that.
We investigated that method getClientSessionLifespanMs of SessionTimeouts class doesn't consider expiration of user session. So for example, if user session was initiated 170 days ago and client session is being refreshed it will be places into Infinispan with lifespan of another 180 days as client session has always refreshed timestamp that doesn't consider first user session creation. After 10 days, user session is correctly evicted but for next 170 days the client session is there unused.
With ~1.6 millions 'rememberMe' user sessions we end up with ~3 mln garbage client sessions every 2 weeks.

### Version

15.1.1

### Expected behavior

Client session lifespan is not longer than expiration of related user session lifespan.

### Actual behavior

Client session lifespan is always set with lifespan considering current timestamp + rememberMe period.

### How to Reproduce?

Turn on rememberMe option on realm.
Login and create both user & client sessions. 
Then after expiration time, refresh session - user session correctly uses initiated timestamp to compute lifespan but client session uses current timestamp.

### Anything else?

I checked that there are no changes in later Keycloak releases.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Hopefully we're able to review your PR, Thanks for sending it!
