### ISSUE TITLE
SSO authentication impossible (provider microsoft oidc) EXECUTE_ACTION_TOKEN_ERROR,

### ISSUE THREAD

**Issue by drbng** [keycloak/keycloak#14864]
### Describe the bug

I have a client who used Azure AD as Identity provider. All of the users from the domain can access our application in SSO expect one user. We published an application inside Azure App gallery as well all our clients can add the enterprise application to their Azure AD and it will push the OIDC configuration automatically inside their AAD. Everything works nice most of the time but for this case I can't find the root cause. 

When the user try the authentication, I can see some logs from keycloak:

 15:16:57,286 WARN  [org.keycloak.events] (default task-6385) type=EXECUTE_ACTION_TOKEN_ERROR, realmId=xxx, clientId=null, userId=xxx, ipAddress=xxx, error=expired_code, reason='Token is not active', token_id=xxx, action=execute-actions
15:16:59,574 DEBUG [org.keycloak.social.user_profile_dump] (default task-6385) User Profile JSON Data for provider microsoft: 

Version info:
INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.1.Final
Keycloak 7.0.0 (WildFly Core 9.0.2.Final)

### Version

Keycloak 7.0.0

### Expected behavior

SSO authentication in success state without token issue.

### Actual behavior

The user can't be autehnticated through SSO OIDC method 

### How to Reproduce?

Ask the user to try the authentication.

**Comment by stianst** [comment]
User is trying to execute an action like reset password after the action token has expired. This is also a very old version, which hasn't been supported for many years. I suggest you upgrade asap.
