### ISSUE TITLE
Issue with admin console page keep on loading with keycloak 19.0.3 version which deployed in ubuntu server with Nginx

### ISSUE THREAD

**Issue by kattasunil** [keycloak/keycloak#14873]
### Describe the bug

Problem: Not loading the admin page.
Created a new keycloak setup with 19.0.3 in ubuntu server with Nginx.
Able to start the server with "./kc.sh start-dev" and "./kc.sh start".
Nginx Configuration:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/65004880/195545030-93de71fe-3f92-4968-8a3f-78104f27eacc.png">

### Version

19.0.3

### Expected behavior

System should allow to enter the admin username and password

### Actual behavior

The admin console page is keep on loading

<img width="668" alt="image" src="https://user-images.githubusercontent.com/65004880/195545372-7af30030-e9cf-4643-8e00-e923372c5a09.png">

**Comment by kattasunil** [comment]
Requesting help with the above issue. For a couple of days, I stuck with the same. Kindly help.

**Comment by kattasunil** [comment]
Public DNS is added as a hostname.

**Comment by dpoerschke** [comment]
Same problem here, adding the hostname didn't solve it though. 
![image](https://user-images.githubusercontent.com/48479502/198551361-28f49621-00fa-4405-ac0b-d6fe46d31f9e.png)

In my keycloak.conf I have added this (worked with keycloak 17.x):
![image](https://user-images.githubusercontent.com/48479502/198551383-0a3e809f-e2b5-4727-b6a5-1ff05ce3769e.png)

I haven't installed keycloak on a server but on my laptop, having the domain (dev-login....) added to my host file. Worked with Keycloak 15.0.2 and 17.0.0 but unfortunately not with 19.0.3

Any thoughts on this? Any help is appreciated.
