### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by garymach64** [keycloak/keycloak#14870]
### Describe the bug

When looking at my realm, I see the following text:
"If you want to leave this page and mange this realm, please click the corresponding menu items in the left navigation bar."

"mange" -> "manage"

### Version

19.0.2

### Expected behavior

"mange" -> "manage"

### Actual behavior

"mange" -> "manage"

### How to Reproduce?

go into a realm that is not the master

**Comment by ssilvert** [comment]
@garymach64 Thanks for reporting.  This appears to be already fixed.  You can verify in the latest nightly build or release 20.0.0 when it comes out.

https://github.com/keycloak/keycloak/releases/tag/nightly
