### ISSUE TITLE
GELF logging does not resume after send failure

### ISSUE THREAD

**Issue by p-kimberley** [keycloak/keycloak#14894]
### Describe the bug

With GELF logging enabled (`--log=console,gelf`), if the UDP receiver becomes unavailable then recovers, Keycloak does not resume sending logs.

The only way to restore GELF logging at this point is to restart Keycloak.

### Version

19.0.3

### Expected behavior

Keycloak should attempt to log messages regardless of failure, to avoid having to restart the application where connectivity to the logging endpoint is lost.

### Actual behavior

As per description.

### How to Reproduce?

1. Set configuration parameters:
- `log=console,gelf`
- `log-gelf-host=<hostname>`
- `log-gelf-port=12201`

2. Verify log messages are received by the GELF endpoint.
3. Break connection to the GELF receiver.
4. Restore connectivity.
5. Observe that log messages do not resume.

**Comment by mabartos** [comment]
@p-kimberley Thanks for creating this issue. Unfortunately, I wasn't able to reproduce this issue. I disabled the GELF UDP receiver, then enabled it again, and these logs are still received. I also tried to remove the input and also restart the instance of Graylog. Everything works as expected.

Keycloak version: latest main branch (`8573c667a43d8d8d0c3e569bbfddf540953a2ac1` rev) - (Keycloak 21.1.1)
Graylog versions: 4.3.2

Feel free to reopen this issue if the issue persists for the latest main branch and provide a reproducer.
Thanks!
