### ISSUE TITLE
Cleanup setting of Hibernate version twice in root pom and Quarkus pom 

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#14915]
### Description

With #12607's upgrade H2 2.x, this also updated Hibernate to 5.6.x, so it is now the same in the root pom and Keycloak Quarkus Parent pom.

As there is now no difference in the Hibernate version any more, it should be sufficient to set the version once. 

At the same time there is a mechanism `set-quarkus-version.sh` and notice "Do not change the properties bellow." in the Keycloak Quarkus Parent pom.

As part of this issue, this needs to be untangled. The same thing might apply to the RESTEasy version and other versions as well.

**Comment by vramik** [comment]
It might outside of this issue, but I wanted just point out there might be other version than `hibernate`, e.g. `postgresql-jdbc.version`. Would it make sense to include it as well?
