### ISSUE TITLE
Keycloak Admin Console does not start on Safari (MacOS)

### ISSUE THREAD

**Issue by hstm** [keycloak/keycloak#14927]
### Describe the bug

If I click on "Administration Console" in the Keycloak portal, the Keycloak Administration Console does not start. Page load hangs while the browser is trying to access the target URL http://localhost:8080/admin/master/console/#/ .

The error only occurs on Safari (MacOS, Version 16.0 (17614.1.25.9.10, 17614)). **Current Chrome works fine and immediately redirects without issues.**

Same Safari version works fine with Keycloak 18.x, so it must be a Keycloak 19.0.x related issue.

### Version

19.0.3

### Expected behavior

The Administration Console opens without errors.

### Actual behavior

There a lots of possibly CORS related issues ("Fetch API cannot load ... due to access control checks") when I am trying to access the Admin Console from the Keycloak portal using Safari.

<img width="751" alt="Screenshot 2022-10-17 at 12 38 52" src="https://user-images.githubusercontent.com/34376512/196159567-3110ea96-964f-4c1f-bfef-8e4255fe55c2.png">

The errors occur while performing the redirect from http://localhost:8080/admin/ to http://localhost:8080/admin/master/console/#/ . 

Manually interrupting the loading of the website or directly opening the target URL http://localhost:8080/admin/master/console/#/ works without errors.

### How to Reproduce?

- Start Keycloak in dev mode (Docker or bare metal, doesn't make a difference)
- Open localhost:8080 in Safari (MacOS)
- Click on Administration Console in the Keycloak portal

(Tested with 19.0.3 and 19.0.2 with bare metal and Docker installations)

**Comment by hstm** [comment]
Thanks for looking into the issue. 

That's strange. I can reproduce the error reliably (I can provide a screen recording if required):

1. Unzip keycloak-19.0.3.zip and cd into keycloak-19.0.3
2. bin/kc.sh start-dev
3. Open localhost:8080. Keycloak portal opens 
4. Click on "Administration Console". Safari hangs while loading http://localhost:8080/admin/master/console/#/ with the errors mentioned in the bug description.
5. Interrupt the loading of the page by clicking on the "x" in the address bar
6. Keycloak login page appears (URL http://localhost:8080/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadmin%2Fmaster%2Fconsole%2F%23%2F&state...)

Calling http://localhost:8080/admin/master/console/#/ directly also works fine. I also tried disabling all Safari extensions, but that didn't help.

**Comment by stianst** [comment]
Looking at the screenshot you included it is for some reason trying to load admin resources from 9080, not from 8080:

![image](https://user-images.githubusercontent.com/2271511/196353073-eab8a117-dde6-4144-ab48-b49e0eee9249.png)

Got no clue why though.

**Comment by hstm** [comment]
Seems I had some issues with my MacOS installation :-/ 
After a system reboot everything is working as expected now.

So I'm gonna close this issue. Thanks for everyone involved!

**Comment by logopk** [comment]
Please reopen the issue!

I can reliably reproduce this:
- docker image 19.0.3.
- https on port 8883
- click admin-Link on Welcome Page

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/14347357/196462974-6d54d225-6c7c-4737-968e-547396e49405.png">

When I press reload it does work.

**Comment by SylarK** [comment]
> Please reopen the issue!
> 
> I can reliably reproduce this:
> 
> * docker image 19.0.3.
> * https on port 8883
> * click admin-Link on Welcome Page
> 
> <img alt="image" width="1460" src="https://user-images.githubusercontent.com/14347357/196462974-6d54d225-6c7c-4737-968e-547396e49405.png">
> 
> When I press reload it does work. Google Chrome does not show this issue.
> 
> Safari 16.0 on MacOS 12.6

I don't know why but for me it is working when I cancel the request. 
Just click to stop the loading of the page, the page will make an automatic reload.

But I will repeat, I don't know why but is working for me when I use this approach.
I'm using: Keycloak version 19.0.3 and Safari version 16.1.

I hope that works for you!

**Comment by logopk** [comment]
> > Please reopen the issue!
> > I can reliably reproduce this:
> > 
> > * docker image 19.0.3.
> > * https on port 8883
> > * click admin-Link on Welcome Page
> > 
> > <img alt="image" width="1460" src="https://user-images.githubusercontent.com/14347357/196462974-6d54d225-6c7c-4737-968e-547396e49405.png">
> > When I press reload it does work. Google Chrome does not show this issue.
> > Safari 16.0 on MacOS 12.6
> 
> I don't know why but for me it is working when I cancel the request. Just click to stop the loading of the page, the page will make an automatic reload.
> 
> But I will repeat, I don't know why but is working for me when I use this approach. I'm using: Keycloak version 19.0.3 and Safari version 16.1.
> 
> I hope that works for you!

Thats what I meant with:  "When I press reload it does work."

**Comment by livvius** [comment]
I can also reproduce it:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/313040/219813197-87f32238-2d68-453d-8d7d-7391161b64b1.png">

**Comment by helmut72** [comment]
Same for me.

**Comment by logopk** [comment]
Please reopen!

**Comment by helmut72** [comment]
TBH, it was never fixed on my Safari. Because I need it rarely in my homelab after initial setup, I've used Chrome or Firefox. User login works with Safari.

**Comment by helmut72** [comment]
Tested it today. It works now as expected. Never tried it again since months. Therefore I don't know if an update of macOS Ventura or Keycloak fixed it. I guess it was an update of macOS.

**Comment by d996c** [comment]
> Tested it today. It works now as expected. Never tried it again since months. Therefore I don't know if an update of macOS Ventura or Keycloak fixed it. I guess it was an update of macOS.

What version of Keycloak do you have?

**Comment by helmut72** [comment]
> What version of Keycloak do you have?

Every version since I wrote my comment. Now it's 22.0.5. Works great with Safari in macOS 14 Sonoma.

**Comment by potterhe** [comment]
I can reproduce it,  keycloak ver: 25.0.1, macOS Ventura, safari : 16.1 (18614.2.9.1.12)
![Uploading keycloak-safari.jpg…]()

**Comment by logopk** [comment]
Works fine for me now

25.0.1 and macOS Sonoma 14.5 (23F79), Safari 17.5

**Comment by ttww** [comment]
Got the same problem with Safari and following docker installation:

```
docker run -d -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    -e KC_PROXY=edge \
    --name keycloak \
    --restart always \
    -v $HOME/keycloak:/opt/jboss/keycloak/standalone/data \
    quay.io/keycloak/keycloak:26.0 start-dev
```
    
    Safari is on 18.1 (20619.2.5.11.2)
    MacOs is 15.1 Beta (24B5055e)
    
    I have an error on loading the login screen:
    
![image](https://github.com/user-attachments/assets/91659bd7-0330-45a8-9658-5ed62bd3e2e7)

With Firefox I can login....
