### ISSUE TITLE
Default 'first broker login' default first login flow for identity providers ignores realm user registration settings

### ISSUE THREAD

**Issue by PovilasID** [keycloak/keycloak#14932]
### Describe the bug

If I disable registration for the realm but enable identity provider (i.e.) new users can be created using identity provider.

### Version

19.0.3

### Expected behavior

User getting a warning that registrations are not allowed at this time

### Actual behavior

User is created

### How to Reproduce?

Just add any social identity provider to an instance and disable registration in realm settings

**Comment by mposolda** [comment]
@PovilasID Self-registration of users and creation of users by identity brokering are 2 different things. I've created docs PR to clarify this a bit more: https://github.com/keycloak/keycloak-documentation/pull/1792

If you want to disable creation of users by identity brokering, please take a look at the docs here: https://www.keycloak.org/docs/latest/server_admin/index.html#_disabling_automatic_user_creation

**Comment by PovilasID** [comment]
Looked it and tested the configuration suggested in the docs and it looks to work. 
Now it says `Invalid username or password.` If I try to use a new account that has not been created.
However, when using Google it does not prompt to choose what google account to use.

**Comment by mposolda** [comment]
Closing as the docs was clarified to mention that "Realm self-registration" and "Registration by identity brokering" are 2 different things
