### ISSUE TITLE
[keycloak quarkus 18.0.2] admin console is not loaded because of "whoami" request returns http 401 

### ISSUE THREAD

**Issue by rtarasov** [keycloak/keycloak#14955]
### Describe the bug

Hi!
I'm trying to upgrade from 18.0.2-legacy to 18.0.2 quarkus.

Everything went fine except one thing - after I login into the KC admin console the admin console fails to load displaying empty page. From the Network I can see that app.js:33 whoami request fails with 401.

We are behind Azure LB and istio and serving the KC on /auth relative path. 
I have tried with different env vars settings found in the docs and internet:
  - name: KC_HOSTNAME
    value: {{ .Values.kc.hostname }}
  - name: KC_HOSTNAME_URL
    value: "https://{{ .Values.kc.hostname }}/{{ .Values.basepath }}"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
The sticky session and X-Forwarded headers are set on the proxy.
But the problem still stays.

Could you please help? 

### Version

18.0.2-legacy, 18.0.2 quarkus

### Expected behavior

The admin console is loading. whoami is not returning 401

### Actual behavior

whoami returning 401

**Comment by stianst** [comment]
Please try with 19.0.3 and follow the latest version of the hostname guide published on the website

**Comment by rtarasov** [comment]
Thank you Stian @stianst ! This is our next plan. 
Just for those who may be fenced the same problem - you nee to configure environment variable below:
  - name: KC_HOSTNAME_ADMIN_URL
    value: "https://{{ .Values.kc.hostname }}/{{ .Values.basepath }}/admin"

whoami was failing because of cross-origin as admin URL was configured improperly.
