### ISSUE TITLE
Alternative flow with kerberos fails

### ISSUE THREAD

**Issue by Spechey** [keycloak/keycloak#14953]
### Describe the bug

When kerberos authenticator is in alternative sub flow, il doesn't work with an expired page error

### Version

all

### Expected behavior

The kerberos authentication should work in this case

### Actual behavior

The kerberos authentication doesn't work in this case

### How to Reproduce?

At the end of a copy a browser flow, if you create a new alternative flow with required Kerberos authenticator :
![image](https://user-images.githubusercontent.com/13534144/196358213-ec2a7e41-d942-4b1f-97e1-6623d1d97287.png)
We have the possibility to use it :
![image](https://user-images.githubusercontent.com/13534144/196358616-e4cdd62f-5c2d-4bf3-981d-e189818a2b2b.png)
But the authentication fails with an expired page error :
![image](https://user-images.githubusercontent.com/13534144/196359005-40c5ff24-ba2e-4ba9-a399-2aa1eb8fef5d.png)

### Anything else?

From my understanding, this is because when the authentication request is made, the browser replays the request as is and the one-time token is expired as it has already been used up.

**Comment by mposolda** [comment]
@Spechey Thanks for the report. I think this is valid issue, but Keycloak team doesn't have capacity to take a look at this in the near future. Anyone is welcome to come with PR if you find the way how to cleanly fix it.
