### ISSUE TITLE
Broswer Authentication User Role Client Role is undefined

### ISSUE THREAD

**Issue by TafkaMax** [keycloak/keycloak#14971]
### Describe the bug

When using the old admin UI 

1. Authentication
2. Browser flow
3. Condition - User Role
4. Actions
5. Config
6. User role -> Select Role
7. Client role -> Select client > Select client role
8. Apply

Output is as follows.

![image](https://user-images.githubusercontent.com/46354923/196424576-4456c743-81cd-4d35-8305-f6b45362e672.png)

----

Picture of Client Role

![image](https://user-images.githubusercontent.com/46354923/196424674-240681d0-bd0e-483e-8334-fd78a7616c96.png)

### Version

19.0.3

### Expected behavior

Expected behavior is the client not to be undefined.

### Actual behavior

The client is undefined no matter what.

### How to Reproduce?

19.0.3 keycloak, admin2 UI

**Comment by stianst** [comment]
Closing this due to lack of information.
