### ISSUE TITLE
'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [keycloak/keycloak#14980]
## Error:

```text
Access to XMLHttpRequest at 'https://xxx/realms/xxx/protocol/openid-connect/token' from origin 'https://clientorigin.net' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

I have been stuck on the error above for a few days, also researched existing issues and found nothing

### Version

19.0.3

### Expected behavior

I am able to use Keycloak to login to our QA react client

### Actual behavior

Error stated above

### How to Reproduce?

We are able to get the local instance of keycloak running against the local instance of the react client. Using localhost for urls for both.
When we push to production / QA the URLs do not match and we have the CORS error stated above.

KeyCloak configuration in the Client:
![image](https://user-images.githubusercontent.com/6002111/196490746-a5200e5c-4cb3-4106-ab62-2cf4e1fcc633.png)

KeyCloak client settings in QA:
![image](https://user-images.githubusercontent.com/6002111/196495776-632740ad-a250-4b5c-9002-ecd46fe9b9b0.png)

## Background

1. We are using Microsft Azure to host the client and the Keycloak instance within docker containers
    1. Our run command `/opt/keycloak/bin/kc.sh start --proxy edge --hostname-strict-https=false`
2. I have a web client that is using React with the configuration posted above
3. I have a realm created with a client that matches the id in the xxx specified above

**Comment by ZinkNotTheMetal** [comment]
I found an old issue in [RedHat issues](https://issues.redhat.com/browse/KEYCLOAK-5946?jql=text%20~%20%22The%20value%20of%20the%20%27Access-Control-Allow-Origin%27%20header%20in%20the%20response%20must%20not%20be%20the%20wildcard%22)

**Comment by ZinkNotTheMetal** [comment]
Also disabled `--hostname-strict-https=false`

Still getting the CORS error

**Comment by stianst** [comment]
Looking at the code '*' would only be used for Access-Control-Allow-Origin under one of the following conditions:

* Client is trying to invoke Keycloak over http, while SSL required for the realm is configured to require it
* Realm is not enabled
* Client has specifically configured '*' as a valid origin

Sounds like since you've disabled `hostname-strict-https` it is likely the problem that you have a client invoking Keycloak on a non-internal IP address, and have the default SSL required configured for a realm.

I'd suggest configuring HTTPS and making sure the client uses HTTPS. Alternatively, for non-prod environments only, you can relax the SSL required settings for the realm.

**Comment by iyobo** [comment]
None of these worked

**Comment by iyobo** [comment]
I have gotten this to work. In my case, I am hosting keycloak in a kubernetes cluster with an nginx ingress.

Looking at the source, keycloak-js sets withCredentials = true in many client flows. This does not play well with wildcards.
Best to just define the allowed cors origins in the proxy. My proxy was initially set to:

```
metadata: {
          annotations: {
            'nginx.ingress.kubernetes.io/cors-allow-origin': '*'
          }
        }
```

Changing it to this fixed it:

```
metadata: {
          annotations: {
            'nginx.ingress.kubernetes.io/cors-allow-origin': 'https://mydomain.com, http://localhost:3002'
          }
        }
```
