### ISSUE TITLE
With JDK17, AuthzClientTest and Quarkus runtime configuration tests fail with a reflection access error 

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#14997]
### Describe the bug

With JDK17 on Quarkus, AuthzClientTest and Quarkus runtime configuration tests fail with a reflection access error

```
InaccessibleObject Unable to make field private final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module
```

### Version

keycloak 20.0-SNAPSHOT

### Expected behavior

We would want the tests which were passing with the previously supported JDK (JDK11) to also succeed on JDK17 without issue

### Actual behavior

Below tests fail due to a reflection access to map object, from JDK16 on wards, there are deeper restrictions on the ability to use reflection and encounter an Illegal Reflective Access warning, or even a runtime error such as java.lang.reflect.InaccessibleObjectException when trying to manipulate the Map behind the system's environment variables.

```
org.keycloak.testsuite.authz.AuthzClientTest
org.keycloak.quarkus.runtime.configuration.test.ConfigurationTest
```

### How to Reproduce?

Run the below commands with setting your local hosts JDK and JAVA_HOME to jdk17 and observe for test results.

AuthzClientTest
```
mvn clean install  -Dtest=org.keycloak.testsuite.authz.AuthzClientTest -Pauth-server-quarkus
```
ConfigurationTest
```
mvn clean install  -Dtest=org.keycloak.quarkus.runtime.configuration.test.ConfigurationTest -Pauth-server-quarkus
```

### Anything else?

I was able to make the tests work with the below change to the existing jdk9 maven profile inside the root [pom.xml](https://github.com/keycloak/keycloak/blob/main/pom.xml#L1906)

@mposolda If you think this change makes sense to be part of the main branch, I can create a PR for the same, lmk

@nehachopra27 thanks for the help with the investigation and suggestion for the fix

```
        <profile>
            <id>jdk9</id>
            <activation>
                <jdk>[9,)</jdk>
            </activation>
            <properties>
                <surefire.system.args>
                    --add-opens=java.base/java.lang=ALL-UNNAMED
                    --add-opens=java.base/java.util=ALL-UNNAMED
                </surefire.system.args>
            </properties>
        </profile>
```

**Comment by abstractj** [comment]
@kami619 should be fixed by https://github.com/keycloak/keycloak/issues/9971

**Comment by mposolda** [comment]
@kami619 Thanks for this report and for the investigation. So if I understand correctly, the reflection access error with `InaccessibleObject` is thrown from the testsuite, not from the server. So I agree that this is just the test issue and hence it makes sense to me to add the proposed change into main pom.xml. If you can send PR for it, it will be nice.
