### ISSUE TITLE
Configure custom user provider results in RuntimeException: Failed to find provider map for user

### ISSUE THREAD

**Issue by sophievdf** [keycloak/keycloak#15008]
### Describe the bug

I have a custom UserProvider which extends from the JpaUserProvider. It's basically the same, but for my usecase, I had to remove the 'toLowerCase()' calls after the username.

Running on version 18.0.2 , everything worked just fine. But I'm trying to bump to version 19.0.3

I compared my userprovider with the JpaUserProvider of version 19.0.3, but they're still the same - except for those missing 'toLowerCase()'

My Dockerfile - line 6 in particular:

```
FROM quay.io/keycloak/keycloak:19.0.3 as builder
WORKDIR /opt/keycloak
ENV KC_DB=postgres
COPY --chown=keycloak:root themes/ themes/
COPY --chown=keycloak:root providers/ providers/
RUN /opt/keycloak/bin/kc.sh build --spi-locale-selector-provider=custom-locale-selector-provider --spi-user-cache-provider=custom --spi-user-provider=custom_jpa --spi-user-jpa-enabled=false
RUN /opt/keycloak/bin/kc.sh show-config
FROM quay.io/keycloak/keycloak:19.0.3
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
COPY --chown=keycloak:root themes/ themes/
COPY --chown=keycloak:root providers/ providers/
RUN mkdir -p /opt/keycloak/data
RUN chmod -R 775 /opt/keycloak/data
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]

```

Running docker build results in following error:

```
ERROR: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureProviders threw an exception: java.lang.RuntimeException: Failed to find provider map for user
	at org.keycloak.quarkus.deployment.KeycloakProcessor.checkProviders(KeycloakProcessor.java:707)
	at org.keycloak.quarkus.deployment.KeycloakProcessor.configureProviders(KeycloakProcessor.java:308)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
ERROR: Failed to find provider map for user
```

If I replace this line in the Dockerfile:
`RUN /opt/keycloak/bin/kc.sh build --spi-locale-selector-provider=custom-locale-selector-provider --spi-user-cache-provider=custom --spi-user-provider=custom_jpa --spi-user-jpa-enabled=false`

by this:

`RUN /opt/keycloak/bin/kc.sh build --spi-locale-selector-provider=custom-locale-selector-provider --spi-user-cache-provider=custom`

Everything works fine, but I really need my custom provider as the default.

### Version

19.0.3

### Expected behavior

I expected everything to work just like in version 18.0.2.
Being able to register my custom userprovider as the default user provider without any errors.

### Actual behavior

Registering my custom user provider as default user provider results in errors during docker build after bump from 18.0.2 to 19.0.3

### How to Reproduce?

Create your own custom userProvider

```
public class CustomJpaUserProvider extends JpaUserProvider { ... }

public class CustomJpaUserProviderFactory implements UserProviderFactory { ... }

```

Can even be a copy of the original JpaUserProvider. Make sure getId() in the factory returns 'custom_jpa'

Try to build with this config `--spi-user-provider=custom_jpa --spi-user-jpa-enabled=false` 

### Anything else?

https://www.keycloak.org/server/configuration-provider

**Comment by Tristan971** [comment]
Same exact use-case and implementation, same results. With the map provider was ready so we didn't have to do these awkward SPI hacks to keep casing around...

**Comment by pedroigor** [comment]
@hmlnarik It is related to the storage but legacy. Please, let me know if the storage label applies to legacy too.

@Tristan971 @sophievdf Sorry for the delay. Could you please check https://github.com/keycloak/keycloak/pull/16004?

**Comment by Tristan971** [comment]
@pedroigor LGTM

> 2022-12-15 04:34:06,552 WARN  [org.keycloak.services] (build-57) KC-SERVICES0047: case-aware-jpa (org.mangadex.keycloak.models.jpa.UsernameCaseAwareJpaUserProviderFactory) is implementing the internal SPI user. This SPI is internal and may change without notice

A sad note: The SPI route unfortunately still can't be enough to avoid a hard fork, because of the `.toLowerCase()` here :(
https://github.com/keycloak/keycloak/blob/445e953501f3add3b9acf83953890df5139621ac/model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L280

Do you perhaps have an idea whether it's worth thinking of making a PR that way or would it clearly have no chance to go forward...? fwiw the full diff is merely [these few lines](https://github.com/keycloak/keycloak/compare/2003f6fde0e4c9708bd562a0931aa3a60aec8e21...b587722831604ab503a6210e2471479fbb8c2fa2) + a client scope protocol mapper (for our needs anyway)

**Comment by Gayathri2102** [comment]
@sophievdf I am using the same version of keycloak 18.0.2 but not able to extend the JpaUserProvider.java in my code. Is there an example or dependency you can provide?
