### ISSUE TITLE
Keycloak Traefik routing issue 

### ISSUE THREAD

**Issue by nidhin077** [keycloak/keycloak#15002]
### Describe the bug

I have upgraded my keycloak to quarkus latest version. Also, I'm using traefik to route the keycloak. After the upgradation, the keycloak is not routing through the traefik. I have attached my current traefik and keycloak configuration. Please take a look and let me know, how to resolve the same. 

### Version

19.1.1

### Expected behavior

Working 

### Actual behavior

Bad gateway error

### How to Reproduce?

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    restart: always
    command: start  --auto-build 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=rN&P3hx(*L
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=6()qTN9)Tu
      - KC_HOSTNAME=nidhin.com
      - KC_PROXY=edge
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true  
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key

    volumes:
      - ./config/cert/keycloak.crt:/etc/x509/https/tls.crt
      - ./config/cert/keycloak.key:/etc/x509/https/tls.key           
    ports:
        - 8443:8443
    depends_on: 
        - postgres
    networks: 
      - monitoring
    labels:
      - traefik.enable=true
      - traefik.docker.network=monitoring
      - traefik.http.routers.keycloak-https-redirect.entrypoints=https
      - traefik.http.routers.keycloak-https-redirect.tls=true
      - traefik.http.routers.keycloak-https-redirect.rule='HostRegexp(`{any:.*}`)'
      - traefik.http.routers.keycloak-https-redirect.middlewares=keycloak-https-redirect
      - traefik.http.middlewares.keycloak-https-redirect.redirectscheme.scheme=https
      - traefik.http.services.keycloak-https-redirect.loadbalancer.server.port=8443
      - traefik.http.services.keycloak-https-redirect.loadbalancer.server.scheme=https
      - traefik.http.routers.keycloak.entrypoints=https
      - traefik.http.services.keycloak-https-redirect.loadbalancer.sticky.cookie=true
      - traefik.http.routers.keycloak.tls.certresolver=default
      - traefik.http.routers.keycloak.rule=Host(`nidhin.com`)

### Anything else?

No response

**Comment by stianst** [comment]
You're not using the correct proxy setting. `proxy=edge` is used when the load balancer is terminating HTTPS, and forwarding request to Keycloak over HTTP. You should use `proxy=reencrypt` or `proxy=passthrough`, whichever is applicable to you.

**Comment by nidhin077** [comment]
Hi @stianst, I have changed the proxy value to both reencrypt and passthrough. But still, I'm getting the internal server error. Could you please recheck my configuration and let me know if there are any entries that need to remove or add?

**Comment by stianst** [comment]
What error are you getting?
