### ISSUE TITLE
Enable IPv6 dualstack support by default

### ISSUE THREAD

**Issue by bertjwregeer** [keycloak/keycloak#15003]
### Description

In pull request: https://github.com/keycloak/keycloak/pull/13577 documentation was added on how to enable IPv6 in the JVM. I am running an EKS cluster in IPv6 mode and it was surprising to me that in 2022 a project would require additional configuration to support IPv6.

I would expect that Keycloak would work with both IPv4 and IPv6 by default and bind to both IPv4 and IPv6 on all interfaces by default.

### Motivation

IPv6 on hosts where Keycloak is deployed is becoming far more mainstream and Keycloak should support receiving requests over IPv6.

### Details

Please enable IPv6 by default.

**Comment by stianst** [comment]
We should use the default Java settings by default, by removing `-Djava.net.preferIPv4Stack=true` from https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.sh#LL92C80-L92C111 and https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.bat#L81. 

The defaults for Java as specified [here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/doc-files/net-properties.html) would make Keycloak listen both on IPv4 and IPv6, and prefer IPv4 for outgoing connections.

The documentation update in https://github.com/keycloak/keycloak/pull/13577 is somewhat confusing as states setting `java.net.preferIPv6Addresses` to `false` and `java.net.preferIPv6Addresses` to `true` to enable IPv6. However, to enable IPv6, `java.net.preferIPv6Addresses` should be set to `false`. It should only be set to `true` if it is wanted to default to IPv6 addresses, which I'm not sure anyone needs to do.

**Comment by stianst** [comment]
@pedroigor @vmuzikar FIY

**Comment by pedroigor** [comment]
IIRC, the only reason why we did not disable ipv4 for backward compatibility. But if we want to support both and rely on JDK default behavior, I'm fine with it.

W.r.t. documentation, we can move the section to outgoinghttp and also have a section that highlights the outgoinghttp guide. Like we do for others. It is a common production configuration, anyways.

**Comment by vmuzikar** [comment]
I recently manually tested 21.1 on a dualstack cluster and everything worked fine. However, I assume we're talking about IPv6-only environments. We should definitely support that OOTB but I'm a bit concerned about testing that, mainly from the Operator side (AFAIK, minikube that we rely on doesn't support IPv6). Hence, I'd move it to 23 if this should be done properly. WDYT?

**Comment by bertjwregeer** [comment]
I run Keycloak at work on a IPv6 only EKS cluster. I do not use the operator. The biggest issue I ran into is one that I've documented on my work account: 

https://github.com/keycloak/keycloak/issues/12554#issuecomment-1502377881

It requires that we bind to the global address, not the link-local so that Keycloak is able to form a cluster successfully, as otherwise the pods will communicate the wrong IP address to each other even-though PING_DNS is used and the DNS results are the appropriate global addresses.

**Comment by stianst** [comment]
> I recently manually tested 21.1 on a dualstack cluster and everything worked fine. However, I assume we're talking about IPv6-only environments. We should definitely support that OOTB but I'm a bit concerned about testing that, mainly from the Operator side (AFAIK, minikube that we rely on doesn't support IPv6). Hence, I'd move it to 23 if this should be done properly. WDYT?

I'm talking about having both IPv4 and IPv6 enabled by default, not IPv6-only environments. At the moment Keycloak doesn't listen on IPv6 by default due to `java.net.preferIPv4Stack=true`. The proposal here is to remove setting this option, and updating documentation, nothing more than that.

**Comment by stianst** [comment]
Scoping this issue to enabling support for both IPv4 and IPv6, supporting IPv6 only deployments is moved to https://github.com/keycloak/keycloak/issues/21277
