### ISSUE TITLE
Remove support for OpenJDK 11 on the server side

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#15014]
### Description

We are currently supporting OpenJDK 11 on the server-side, and planning to support OpenJDK 17 from 20 onwards.

With new Java releases coming more and more frequently I propose we aim to support only two versions at a given time. Aiming the latest LTS and the latest non-LTS.

This would mean dropping support for OpenJDK 11 shortly after supporting OpenJDK 17, to then be able to add support for OpenJDK 19.

Once Java 21 (the next LTS after 17) is out, we would do the same thing, and quickly remove support for 17 in order to get ready to support Java 22 and onwards.

Tasks:

- [x] Switch CI to 17 as default https://github.com/keycloak/keycloak/pull/16014
- [ ] Release notes
- [ ] Review/update docs to reflect what versions are supported
- [x] https://github.com/keycloak/keycloak/pull/17451
- [ ] Remove JDK 11 testing from GitHub workflows

**Comment by pedroigor** [comment]
As per https://github.com/keycloak/keycloak/issues/13122#issuecomment-1326300240, we should consider improving our docs about the JRE/JDK versions we support.

Do we need an issue for it or we can do it here?

**Comment by pedroigor** [comment]
@stianst Similar but a reviewed version of the documentation we have from RH-SSO?

**Comment by stianst** [comment]
> @stianst Similar but a reviewed version of the documentation we have from RH-SSO?

Something like that

**Comment by vmuzikar** [comment]
@stianst Is this still scheduled for 21?
