### ISSUE TITLE
Remove OpenJDK 8 for adapters

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#15013]
### Description

With the Quarkus distribution we are no longer supporting OpenJDK 8 for the Keycloak server, but we are still supporting OpenJDK 8 for adapters.

We still support OpenJDK 8 for adapters, which means shared modules and adapter modules are limited to Java 8, which is a limitation from a development perspective when we can't take advantage of new features in more recent Java versions.

Even though OpenJDK 8 is strictly speaking supported until 2030 I suggest we drop support for OpenJDK 8 completely from Keycloak in 21.

**Comment by thomasdarimont** [comment]
+1 This certaily helps to remove some old cruft from the codebase.

All of our customers who I regularly interact with are using at least JDK 11 and many are already on JDK 17 anyways.
