### ISSUE TITLE
SAML metadata WantAuthnRequestsSigned not affected by SAML client configration

### ISSUE THREAD

**Issue by OriSchmitz** [keycloak/keycloak#15022]
### Describe the bug

In the exported XML metadata, the value of `WantAuthnRequestsSigned` is always `true`. Even though the client setting for "Client Signature Required" is turned off.

### Version

16.1.1

### Expected behavior

When setting "Client Signature Required" to OFF, the value for `WantAuthnRequestsSigned` should be false.

### Actual behavior

The value for `WantAuthnRequestsSigned` is always true.

### How to Reproduce?

Create a SAML 2.0 client and set "Client Signature Required" as OFF.
Go to the SAML 2.0 Identity Provider Metadata url (#server#/auth/realms/#realm#/protocol/saml/descriptor) and see the value of WantAuthnRequestsSigned which will be true.

### Anything else?

It seems like `SamlService`'s `getDescriptor()` ignores the client and it's settings entirely.

**Comment by bonnm** [comment]
The exported SAML metadata describes Keycloaks behaviour when it is used as an SAML Identity provider. So it is realm-specific, not client-specific. The IDP SSO Descriptor never can contain any client-specific values. Everything in this metadata is autogenerated based on realm-configuration (keys, host name in URLs, etc...)

**Comment by krisleech** [comment]
@OriSchmitz did you figure out how to change `WantAuthnRequestsSigned`?
