### ISSUE TITLE
Enabling hostname verification by default

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#15028]
### Description

By default, Netty 4.1.x certificate hostname validation is disabled. While this is helpful during debugging or developing an application, it can become a security issue if brought in production, making applications susceptible to Man-in-the-Middle attacks.

The issue has been discussed on:

- https://github.com/netty/netty/issues/10806
- https://github.com/netty/netty/issues/8537
- https://github.com/netty/netty/issues/9930
- https://github.com/netty/netty/issues/10362

Until we don't have a Netty 5 release to enable it by default, I believe it is valid to consider enabling it by default ourselves.

### Motivation

- Enhance security

### Details

# References:

- https://codetinkering.com/enable-hostname-verification-netty/
- https://github.com/keycloak/keycloak/issues/12663

**Comment by abstractj** [comment]
@pedroigor @sguilhen does it make any sense?

**Comment by stianst** [comment]
We don't use Netty do we?

**Comment by abstractj** [comment]
@stianst from what I checked, we only make use of the codec on QuarkusRequestFilter:

```
runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java
29:import io.netty.handler.codec.http.HttpHeaderNames;
30:import io.netty.handler.codec.http.HttpHeaderValues;
31:import io.netty.handler.codec.http.HttpResponseStatus;
```

Thinking about it now, we should be able to close this issue and postpone https://github.com/keycloak/keycloak/issues/12663 for the future. Does it make sense?

**Comment by pedroigor** [comment]
Vert.X is based on Netty but I'm unsure if the issue is only related to Netty clients. If so, we are fine.

**Comment by abstractj** [comment]
From my understanding, it's only Netty related. For now I'm closing it and I will update our security scanners to skip those alerts. Thank you.
