### ISSUE TITLE
Declarative user profile should allow to mark the email attribute as non required

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#15026]
### Description

Following #8741, I was expecting "declarative user profile" would allow me to mark the user registration email field as non required.
Looks like it's not the case.

### Motivation

Many of our business users don't have email addresses to provide.

**Comment by reda-alaoui** [comment]
> Right now, changes to the email attribute are applied to all contexts (registration, admin api, idp, etc). Not yet possible to choose where the attribute is required.

This is not an issue for my use-case. I want the email to be optional everywhere.

**Comment by pedroigor** [comment]
@reda-alaoui Could you please check our nightly build? The change should be available from there.

**Comment by reda-alaoui** [comment]
@pedroigor I just tested the change with version 21.0.1 , looks fine to me :)
Thank you !

**Comment by pedroigor** [comment]
@reda-alaoui Glad to hear. Thanks for the feedback.
