### ISSUE TITLE
Unable to create idp role mapper (oidc / saml) with old admin UI

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak#15021]
### Describe the bug

We use Keycloak 19.0.3 with the old admin UI. It works via REST and in the new admin UI. 

### Version

19.0.3

### Expected behavior

Role gets selected properly. 

### Actual behavior

Instead of the client the word "undefined" gets written to the field. 
![image](https://user-images.githubusercontent.com/24498435/196711339-31479646-6958-42c7-b4ae-8be463ce742e.png)

The js-console shows: InternalError: too much recursion
### How to Reproduce?

1. Be sure you have the old admin-UI active
2. Create an IDP (oidc or saml)
3. Create a Role mapper (e.g.g SAML Attribute to Role)
4. Select a role, e.g. in account-client the role "manage-account".

**Comment by ssilvert** [comment]
@foliengriller I don't think we will be able to spend time supporting the old UI.  I'm going to close this.
