### ISSUE TITLE
Custom SPI examples only show the WildFly way

### ISSUE THREAD

**Issue by sonOfRa** [keycloak/keycloak#15033]
### Description

I'm currently implementing a custom SPI for use in our Quarkus based Keycloak installation. For an older project, I used the documentation for the [domain-extension](https://github.com/keycloak/keycloak/tree/main/examples/providers/domain-extension) in order to get started on the development and deployment. The [documentation](https://www.keycloak.org/docs/latest/server_development/#_extensions_spi) also refers to this example.

However, the example only shows how to deploy the custom SPI in a Wildfly setting. I expected the SPI to be automatically registered when it is present in the /opt/keycloak/providers directory. This works for all our custom authenticators and other customizations, however my custom SPI is not picked up, and not listed as a provider in the server info tab.

The documentation or the example should probably show how to deploy a custom SPI in a Quarkus based Keycloak, especially considering the Wildfly distribution is going away soon.

I filed this under enhancement because I did not find a specific "documentation" category for issues, feel free to move it if another type is more appropriate

**Comment by pedroigor** [comment]
@sonOfRa Does this guide work for you https://www.keycloak.org/server/configuration-provider?

**Comment by sonOfRa** [comment]
Yes, that actually works. It actually works out of the box *without* the command line option too, but I had made a mistake in setting up the SPI class. I returned `org.keycloak.provider.ProviderFactory` from `getProviderFactoryClass()` by accident, instead of the actual `MyCustomProviderFactoryClass`. That's why things weren't automatically picked up.
