### ISSUE TITLE
Localization texts are not loaded for default realm locale 

### ISSUE THREAD

**Issue by SergeyZubatkin** [keycloak/keycloak#15059]
### Describe the bug

Login theme (other themes affected as well) does not load localization texts for default realm locale.
Seems the problem is on [this line of code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java#L371). If statement should not contain "!". Search in code by "StringUtil.isNotBlank(realm.getDefaultLocale())" and will see that most of other themes have same code.

### Version

19.0.2

### Expected behavior

Localization texts for default locale is loaded to context

### Actual behavior

Localization texts for default locale is not loaded to context

### How to Reproduce?

1. Create theme base on default one for login:
- create theme folder with login folder inside
- in login folder theme.properties with one line parent=keycloak
- copy login.ftl from default theme to login folder
- open login.ftl, find doLogIn and replace with doLogInSecond
2. Create new realm with name "TestRealm"
3. Change login theme to theme created before
4. Go to realm settings and enable localization
5. Select default locale "en"
6. Go to Localization tab and create texts for "en"
7. Add key doLogInSecond with value doLogInSecondEnglish
8. Open account console e.g. http://localhost:8090/realms/TestRealm/account/
9. Click SignIn
10. Look on login button text, should be doLogInSecondEnglish
11. Change language to Deutsch
A.R. Login button text is changed to doLogInSecond.
E.R. Login button text is changed to doLogInSecondEnglish as "en" is selected as default locale

**Comment by mposolda** [comment]
duplicates #15845
So I am closing this. Everyone seeing this, please reply to that issue for the further discussions/questions/suggestions.
