### ISSUE TITLE
Transaction deadlock with Microsoft SQL if "sendStringParametersAsUnicode=false" not set in db url properties

### ISSUE THREAD

**Issue by JNygard** [keycloak/keycloak#15060]
### Describe the bug

Transaction deadlock error occurs when concurrently creating more than two new users with Keycloak API. Tried with Keycloak versions 18.0.1 and 19.0.3 while using Microsoft SQL Server database.

After setting `sendStringParametersAsUnicode=false` in `KC_DB_URL_PROPERTIES` there were no issues. [Database configuration instructions](https://www.keycloak.org/server/db) for Microsoft SQL Server database however states: 
> No special settings of JDBC driver or database is necessary.

There was issue on Jira backlog for updating Microsoft SQL Server database driver instructions and request in the comments to recreate bug on GitHub.
https://issues.redhat.com/browse/KEYCLOAK-19414

### Version

18.0.1, 19.0.3

**Comment by sschu** [comment]
This should definitely be set to false, otherwise performance is abysmal. Also see e.g. https://sqlwizardblog.wordpress.com/2018/07/29/performance-impact-of-jdbc-connectionstring-property-sendstringparametersasunicode/

**Comment by bonnm** [comment]
Oh man, if I had known a few years ago that this simple but significant parameter existed (e.g. if it had been in the docu...;-)) it would have saved me hundreds of deadlocked account entities and some sleepless nights...
