### ISSUE TITLE
publish keycloak 19 image to dockerhub

### ISSUE THREAD

**Issue by ambition-consulting** [keycloak/keycloak#15079]
### Description

My integration tests require keycloak 19.02 on dockerhub: https://hub.docker.com/r/keycloak/keycloak/tags

Can you please publish this?

**Comment by sschu** [comment]
Why can't you pull the images from quay.io/keycloak/keycloak?

**Comment by ambition-consulting** [comment]
our company only has a mirror for docker hub. :(

if it's the only way to go forward, then I will request the scan + import process.

**Comment by stianst** [comment]
From 20 forward we will publish to docker hub again.

**Comment by ambition-consulting** [comment]
Thank you
