### ISSUE TITLE
Revisit ConcurrentAuthzTest in context of map storage

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#15071]
### Description

Within https://github.com/keycloak/keycloak/pull/12797 there has been added `ConcurrentAuthzTest` to model tests. The test aims to test legacy infinispan caching.

For jpa map storage the test fails with `ModelIllegalStateException: Version of entity changed between two loads` as it modifies (deletes) the object concurrently. Therefore it has been decided to limit the scope of the test to `StoreFactoryCacheSession` provider.

This task is about review of the test. Whether it makes sense to run it with map storage implementations as well.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
