### ISSUE TITLE
Allow setting a help text to an attribute

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#15072]
### Description

Right now, it is only possible to set a hint to an attribute through annotations.

Ideally, we should make help text available as a field in the user profile configuration to make it easier to manage it.

### Details

Add a help text field to the `UPAttribute`.

**Comment by reda-alaoui** [comment]
`attribute.annotations.inputHelperTextBefore` and `attribute.annotations.inputHelperTextAfter` for the record :smile:

**Comment by pedroigor** [comment]
@reda-alaoui Good point :)

I'll close it as it is related to a wider problem where we need to figure out how to provide the best UX when configuring annotations in general. Some of them make sense to be very explicit as a field rather than typing those weird names .

FTR, the new administration console is able to add hints using an image. However, the support from freemarker templates is not so good. The text is basically shown without any icons.
