### ISSUE TITLE
User not added to an LDAP-federated group when created

### ISSUE THREAD

**Issue by trusanen-fluidit** [keycloak/keycloak#15080]
### Describe the bug

We store our users and the groups in LDAP. We have recently also deployed Keycloak and set up synchronization between the two. 

When we create a new user in Keycloak and assign it to some group in the "Add user"-form, the user is created successfully in both Keycloak and LDAP but not added to the assigned group in Keycloak.

However if the user is assigned to the group after creation from the "Groups"-tab in the user UI, he/she is added to the group successfully.

### Version

18.0.2

### Expected behavior

The user is successfully added to the LDAP group when creating a new user.

### Actual behavior

The user is not added to the LDAP group when creating a new user and a `member`-entry with an invalid DN is generated for the group in LDAP.

### How to Reproduce?

Our users have DNs of the form `cn=<full-name>,ou=users,dc=...,dc=...`. Additionally the users have an `uid`-attribute, which we have set to be the "Username LDAP Attribute" in Keycloak. The "RDN LDAP Attribute" is set to `cn`.

The configured mappers related to these attributes are :

user-attribute-ldap-mapper: username <-> `uid`
user-attribute-ldap-mapper: first name <-> `givenName`
user-attribute-ldap-mapper: last name <-> `sn`
full-name-ldap-mapper: full-name -> `cn` (write only)

When a user is created and assigned to some group all the user attributes are synchronised successfully, but the `member`-attribute generated for the LDAP group has a DN of `cn=<username>,ou=users,dc=...,dc=...` whereas it should be `cn=<full-name>,ou=users,dc=...,dc=...`. It seems that Keycloak maps the username to the `cn` value for some reason even though that value should come from the full name.

**Comment by hmlnarik** [comment]
@trusanen-fluidit I am unfortunately unable to reproduce this issue. If this is still an issue, could you please provide more precise steps to reproduce (any minimal reproducer / screenshots would help).

**Comment by trusanen-fluidit** [comment]
Hi @hmlnarik and thanks for the reply.

It seems I can't reproduce this issue either anymore in our current environment. We have made some updates to our LDAP configuration, whereas our Keycloak configuration is the same as before.

Nonetheless I'll close this one as a non-issue and report back, if we encounter the issue again.

**Comment by hmlnarik** [comment]
Thank you @trusanen-fluidit
