### ISSUE TITLE
Old admin console theme still visible for selection even though the corresponding feature is disabled

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#15116]
### Area

admin/ui

### Describe the bug

The old administration console (`keycloak` admin theme) is now disabled by default. However, the theme is still available for selection from the theme settings for a realm. 

Ideally, the `keycloak` theme should be filtered and removed from the list of available thems when the `admin` feature is disabled. Similar to how the `keycloak.v2` theme works.

### Version

20

### Expected behavior

The `keycloak` theme not available for selection if the `admin` feature is disabled.

### Actual behavior

The `keycloak` theme is available for selection even though the `admin` feature is disabled.

### How to Reproduce?

Start the server and check if the `keycloak` theme is available from the theme settings.

**Comment by ssilvert** [comment]
This is now fixed.  Old admin console has been removed.
