### ISSUE TITLE
Add Apple ID to Identity Providers

### ISSUE THREAD

**Issue by jkouris** [keycloak/keycloak#15132]
### Description

Add built in support for Apple ID (Sign in with apple) as an Identity Provider.
https://developer.apple.com/sign-in-with-apple/

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-13171

### Motivation

Apple requires apps to have "sign in with apple" option if there are any other social login options.  

Any mobile app that integrates with keycloak will be rejected unless "sign in with apple" is one of the options in addition to the other social login providers supported by keycloak. 

### Details

Separate extension was developed to provide this functionality but would be appropriate to support it out of the box.
https://tharindunanayakkara.medium.com/how-i-integrated-sign-in-with-apple-to-keycloak-3dae9bc7e46f

**Comment by stianst** [comment]
Due to not being able to automatically test brokering with Apple we are not able to provide this out of the box. I suggest using a community maintained extension instead.
