### ISSUE TITLE
Keycloak 19 crashes when Identity Provider Redirector settings is opened

### ISSUE THREAD

**Issue by milosjovac** [keycloak/keycloak#15137]
### Area

admin/ui

### Describe the bug

Keycloak 19 crashes when Identity Provider Redirector settings is opened

### Version

19.0.3

### Expected behavior

Opening of the Identity Provider Redirector settings

### Actual behavior

Crash with error "Danger alert:Cannot convert undefined or null to object".

### How to Reproduce?

Select a realm -> Authentication -> browser -> Identity Provider Redirector settings --- error with message "Danger alert:Cannot convert undefined or null to object" happens.

**Comment by fungiboletus** [comment]
AFAIK, it's fixed by #3268 but we need to wait for the next release.

**Comment by milosjovac** [comment]
Ah perfect, tnx. Just so I don't spam the channel in the future, how did you find it? It didn't pop-up for me in issue search results.

**Comment by ssilvert** [comment]
@milosjovac Right now, the admin console and its issues live in https://github.com/keycloak/keycloak-ui

We will be moving the code and issues back to the main repo soon though.  I'm going to close this issue now.  Keycloak 20 should be out soon, but if you want to see the fix sooner you can try out the nightly build.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by fungiboletus** [comment]
> Ah perfect, tnx. Just so I don't spam the channel in the future, how did you find it? It didn't pop-up for me in issue search results.

I think I just got a bit more lucky with my searches.
