### ISSUE TITLE
Investigate test failures in GHA after upgrading Quarkus to 2.13.x version

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#15152]
### Description

This task is a follow-up on https://github.com/keycloak/keycloak/issues/15151 to investigate why we are facing test failures on GHA after upgrading to Quarkus 2.13 series.

**Comment by pedroigor** [comment]
Starting from Quarkus 2.13, the default size of the event-loop/io thread pool is reduced to match the number of cores. See https://github.com/quarkusio/quarkus/pull/27025.

However, some tests are running using the same server to perform requests that end up blocking due to the reduced number of io threads available. For instance, brokering tests when linking accounts.

Looks like increasing the number of event loop threads, only for testing, is enough to make tests work again.

**Comment by pedroigor** [comment]
This run https://github.com/pedroigor/keycloak/actions/runs/3341220207/jobs/5532343366 indicates the changes from https://github.com/keycloak/keycloak/issues/15192 are enough to avoid blocking io threads.

**Comment by toddkazakov** [comment]
Just FYI, I saw the same issue in one of our development environments with Keycloak 20.0.1. Definitely not isolated to tests, but I couldn't figure out what triggered it the first time.

**Comment by pedroigor** [comment]
@toddkazakov Are you still facing the issue?

**Comment by toddkazakov** [comment]
@pedroigor I haven't seen it after the first time. I had to restart all pods, because it looked like keycloak was deadlocked, but what's interesting is that liveness probes weren't failing.

**Comment by pedroigor** [comment]
@toddkazakov I'm closing this one as the problem should be fixed. We have some tests to make sure this won't happen.

If you see it again, please let us know because then we need to see what is still missing.
