### ISSUE TITLE
Declarative User Profile: Username permissions

### ISSUE THREAD

**Issue by micbis** [keycloak/keycloak#15159]
### Area

user-profile

### Describe the bug

When the declarative user profile feature is enabled, the User Profile setting under Realm setting activated and the realm setting editUsernameAllowed is enabled the username can be changed by the user or admin.

If an username attribute is configured, the permissions set there are not respected, i.e. user or admin can change the username.

It might be beneficial if the permission can be set for the username as with other attributes, so that an admin can change the username but not the user itself (an example for this is if the username is based on the real-name and the real-name changes due to marriage).

### Version

19.0.3

### Expected behavior

Attribute permissions are respected, i.e. if permissions are set to only allow the admin to write, only the admin can write.

### Actual behavior

See description.

### How to Reproduce?

See description.

**Comment by sschu** [comment]
This has already been implemented in https://github.com/keycloak/keycloak/pull/12620 and will come with KC20.

**Comment by micbis** [comment]
Perfect, thanks.
