### ISSUE TITLE
probably typo in documentation

### ISSUE THREAD

**Issue by garymach64** [keycloak/keycloak#15163]
### Area

translations

### Describe the bug

probably typo in documentation
In documentation https://www.keycloak.org/docs/latest/securing_apps/, there is a reference to the keycloak's json, with a value of "onnection-timeout-millis".  Presume this is missing a leading "c"

### Version

latest documentation

### Expected behavior

probably should be "connection-timeout-millis"

### Actual behavior

is "onnection-timeout-millis"

### How to Reproduce?

not relevant

**Comment by sschu** [comment]
This is already fixed in current master branch.
