### ISSUE TITLE
Declarative User Profile: Email permissions

### ISSUE THREAD

**Issue by micbis** [keycloak/keycloak#15160]
### Area

user-profile

### Describe the bug

When the declarative user profile feature is enabled (and the User Profile setting under Realm setting tab) the email can be changed by the user or admin. If an email attribute is configured, the permissions set there are not respected, i.e. user or admin can change the email.

### Version

19.0.3

### Expected behavior

Attribute permissions are respected, i.e. if permissions are set to only allow the admin to write, only the admin can write.

### Actual behavior

See description.

### How to Reproduce?

See description.

**Comment by Vividious** [comment]
To help other folks with investigation, apart from enabling the feature of declarative user profile, you need to enable User Profile setting under Realm setting tab :)

-----

Not sure if it's intended, in Realm settings/User Profile/Edit attribute (e-mail).
If you check 'Admin' for edit permission, 'User' gets automatically set.

![image](https://user-images.githubusercontent.com/34356490/197988491-4a9c52a9-8699-4208-86fd-e38640845455.png)

**Comment by micbis** [comment]
@Vividious Perfect, thanks for your clarification.

**Comment by sschu** [comment]
This has already been implemented in https://github.com/keycloak/keycloak/pull/12620 and will come with KC20.

**Comment by micbis** [comment]
Perfect, thanks.
