### ISSUE TITLE
Adding Identity Provider SAML2 - Descriptor attribute md:NameIDFormat is not in uri format

### ISSUE THREAD

**Issue by GatoSnake** [keycloak/keycloak#15178]
### Area

saml

### Describe the bug

When I create an identity provider type SAML 2.0 importing a config file, the xml descriptor has an attribute called md:NameIDFormat where this specify the NameID policy format, but this value is not in uri format.

This causes the external Identity Provider site to fail with the following error:

![image](https://user-images.githubusercontent.com/2672846/198117724-5ae1f4f8-aa30-42a5-ab8d-c287703f98ee.png)

### Version

19.0.3

### Expected behavior

When I create a new Identity Provider SAML v2.0, the value of md:NameIDFormat in xml descriptor must be in uri format.

<img width="1678" alt="Captura de pantalla 2022-10-26 a la(s) 16 19 24" src="https://user-images.githubusercontent.com/2672846/198117342-b2d6256e-b869-4724-9869-dd57cacb14cc.png">

### Actual behavior

When I create a new Identity Provider SAML v2.0, the value of md:NameIDFormat in xml descriptor has a value not in uri format.

<img width="1687" alt="Captura de pantalla 2022-10-26 a la(s) 16 03 13" src="https://user-images.githubusercontent.com/2672846/198114639-aa7cdd3a-46b2-4278-90ea-06f1e777f68d.png">

### How to Reproduce?

1. Create a SAML v2 Identity Provider importing a config file.
2. Access to detail identity provider created.
3. Access to "SAML 2.0 Service Provider Metadata" link and check the value format of attribute "md:NameIDFormat".
5. Modify the "NameID policy format" in the detail Identity Provider using the same value "persistent" and save it.
6. Check again the value format of attribute "md:NameIDFormat" in the "SAML 2.0 Service Provider Metadata".

**Comment by GatoSnake** [comment]
Hi, this problem still in the version 20.0.3.

**Comment by rmartinc** [comment]
Hi!

I have tested this in main and the `NameIDFormat` is `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`so I think this is OK and it should be fixed previously. Please note that the option config in the provider is also the full urn (check you don't have something weird there in the provider configuration).

![Screenshot from 2024-01-15 10-42-04](https://github.com/keycloak/keycloak/assets/26901232/515aa9f3-eeaa-4ad6-ba63-6ad8722219f2)

I'm closing this as I think it's resolved now.
