### ISSUE TITLE
Default IDP login flow breaks in case of login timeout

### ISSUE THREAD

**Issue by zanettea** [keycloak/keycloak#15205]
### Area

identity-brokering

### Describe the bug

Hi ,
I've configured a realm A to use another realm B as IDP by default, so that the login flow automatically redirects to the IDP login form.

So if the user takes too much to login in the IDP, the following error message is shown and the user has to redo the login.

![image](https://user-images.githubusercontent.com/95216/198559667-4492096f-71ff-46f2-9203-d8735a52547d.png)

However, if in the meantime also realm A login timeout expired, after authenticating with IDP, the user is also redirect to the login form of A (actually login-actions), which fails with the same error message:

![image](https://user-images.githubusercontent.com/95216/198559537-262df4cb-6f7b-4017-9d8a-ff387b12e28e.png)

This second error screen is really confusing for the user because:
* the same error message about login timeout is shown twice (one for realm A, one for realm B)
* usually the user does not know about the default IDP, because the standard login flow does the redirect automatically (here listed as keycloak-oidc)

Is there a way to avoid this behavior? (now I've put a very high login timeout in realm A but I don't like this workaround)

### Version

19.0.2

### Expected behavior

Since B is configured as default IDP for A, the login screen for A should never appear. Instead any attempt to login to A should redirect to B.

### Actual behavior

The login page of A is shown in case of login timeout expired.

Btw, this behavior appears to have been introduced, since in version 4.8 was working as expected

### How to Reproduce?

1. Create 2 realms, A and B.
3. Configure B as default IDP for A.
5. Set B login timeout to 1 minute.
7. Set A login timeout to 2 minutes.
9. Go to the login page of A (will be redirected to B).
11. Wait >2 minutes.
13. Enter credentials -> first login timeout error screen from B is shown
14. Enter valid credentials -> second login timeout error screen from A is shown

Alternatively:

1. Create 2 realms, A and B.
3. Configure B as default IDP for A.
5. Set B login timeout to 1 hour.
7. Set A login timeout to 1 minutes.
9. Go to the login page of A (will be redirected to B).
11. Wait >1 minutes.
13. Enter credentials -> login timeout error screen from B is shown

**Comment by sschu** [comment]
The problem is that the URL called at A after login at B is not the login URL i.e. it is not an attempt to login. It is an attempt to complete a login process that cannot be completed as the authentication session has expired. I also assume that the state of the first login process got lost .i.e which client requested which kind of token with what redirect URL etc. at A. Therefore, I think configuring a long authentication session duration on realm A seems to be the best solution to the problem.

**Comment by zanettea** [comment]
I understand. Thank you
