### ISSUE TITLE
Make sure the KeycloakSession is not closed more than once

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#15223]
### Description

Currently, the `KeycloakSession` does not have any mechanism to control whether the client code is performing operation after the session has been closed.

We need to make sure a closed session is not used after being closed otherwise it might cause unexpected behavior and indicate its usage is not correct. It should also indicate whether or not we are properly handling the request lifecycle.

### Discussion

https://github.com/keycloak/keycloak/issues/15192

### Motivation

Properly handle closed sessions.

**Comment by ahus1** [comment]
@pedroigor - it would be great to have this issue in KC21 as it would IMHO remove the cast/check introduced in #15193 in TransactionalSessionHandler. Let's hope that no-one uses the a different session implementation here :-(
