### ISSUE TITLE
Search broken on "Users" page (prefix only)

### ISSUE THREAD

**Issue by benzitohhh** [keycloak/keycloak#15232]
### Area

admin/ui

### Describe the bug

`Users` page (i.e. http://localhost:8080/auth/admin/master/console/#/master/users )

In the searchbox at the top...

PREVIOUSLY

Search worked on subset of a user name.

NOW

It seems like only the prefix is searched.

### Version

19.0.3

### Expected behavior

Searching for a subset of a username should return results.

For example, suppose username "ben.immanuel@aistemos.com" exists.

Then searching for the below should all return a match:
* en
* @aistemos.com
* @aistemos

### Actual behavior

For example, suppose username "ben.immanuel@aistemos.com" exists.

Then searching for the below do not return any matches (when actually they should):
* en
* @aistemos.com
* @aistemos

### How to Reproduce?

On the `users` page (http://localhost:8080/auth/admin/master/console/#/master/users)

Search for a subset of a username (i.e. not a prefix).

So for example, suppose username `ben.immanuel@aistemos.com` exists, search for `@aistemos.com`

This should return a match, but it does not.

### Anything else?

We manage thousands of users.

It is really important that we can easily search through them, by typing a fragment of a name.

**Comment by benzitohhh** [comment]
<img width="1271" alt="Screenshot 2022-10-31 at 15 24 00" src="https://user-images.githubusercontent.com/861758/199046542-47bfac62-1b72-4186-9939-ba6411612a27.png">

**Comment by benzitohhh** [comment]
<img width="1271" alt="Screenshot 2022-10-31 at 15 24 00" src="https://user-images.githubusercontent.com/861758/199046976-e78624bc-21e1-409c-b774-89a85e3d80a6.png">

**Comment by benzitohhh** [comment]
<img width="1268" alt="Screenshot 2022-10-31 at 15 24 15" src="https://user-images.githubusercontent.com/861758/199047058-47f0c76e-7401-47c8-9bbf-e638bf0a8160.png">

**Comment by rmartinc** [comment]
Hi @benzitohhh!

I think this was changed in [KEYCLOAK-18727](https://issues.redhat.com/browse/KEYCLOAK-18727). Now by default the search is prefix, but you can do:

- Use quotes to eact search: "username"
- Use prefix search *name (default)
- Use include search *erna*

Try adding an asterisk before and after your search text to use the include syntax.

**Comment by benzitohhh** [comment]
@rmartinc Ah ok thanks for letting us know - much appreciated
