### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by raffaeler** [keycloak/keycloak#15236]
### Area

admin/ui

### Describe the bug

I am using Keycloak 19.0.3. This bug occurs also in 19.0.2 but not in 19.0.1

I am following the steps provided here: https://www.keycloak.org/docs/19.0.1/server_admin/#_step-up-flow
1. Add the `Condition - Level of Authentication`
![image](https://user-images.githubusercontent.com/5183152/199102088-48987a87-fe8c-4c0b-b717-d8e0cd09e9a3.png)

2. Press the gearbox icon. This is what happens:
![image](https://user-images.githubusercontent.com/5183152/199101875-1291e40d-19d5-4ec0-adcf-a30fbde5892d.png)

### Version

19.0.3

### Expected behavior

I should be able to see this dialog (which I can see if I rollback to 19.0.1)
![image](https://user-images.githubusercontent.com/5183152/199102444-2498ce3a-2771-435a-9265-ba88c5e946fa.png)

The dialog is initially empty (no `alias` field, no `loa-condition-level` field).
If I rollback to 19.0.1, fill the dialog and the roll-forward to 19.0.3, I can open the dialog and see the correct value as above. But pressing the `Clear` button cause the problem again.

### Actual behavior

Currently it is not possible to set up a Condition - Level of authentication. The error is the one below.

![image](https://user-images.githubusercontent.com/5183152/199101875-1291e40d-19d5-4ec0-adcf-a30fbde5892d.png)

** Important **
Looking at the old issues, it looks like the same error was found in roles and other authentication blocks. I currently did not test them but it is definitely possible they are affected too.

### How to Reproduce?

Follow the documentation steps in the link I provided above (official documentation).

### Anything else?

Please provide the "database compatibility" among minor versions. I can't find this information and I took the risk to roll-back and roll-forward the container images while sharing the same database.
More info about this would be greatly appreciated.

**Comment by raffaeler** [comment]
I confirm that other flows I created before are now broken in 19.0.3 with exactly the same error

**Comment by ssilvert** [comment]
@raffaeler This is fixed in Keycloak 20.0.0.  I'm going to close this issue but we can reopen if you still see the problem.

**Comment by raffaeler** [comment]
@ssilvert great, but I have 2 questions:
- could you provide a link yo the container image?
- is the db compatible with the 19.x release? (backward and forward)

Thank you

**Comment by ssilvert** [comment]
@raffaeler Not sure what you mean by the first question.  Keycloak 20.0.0 should work just fine with your previous database but there might be a migration step.  Check the release notes.

**Comment by raffaeler** [comment]
@ssilvert yesterday I checked for a new container release but the latest tag was the 19.0.3.
Where can I find the 20? Was it released or is it a beta?

**Comment by ssilvert** [comment]
@raffaeler 20.0.0 was released a couple of days ago.

https://www.keycloak.org/downloads
