### ISSUE TITLE
Switch to micrometer metrics

### ISSUE THREAD

**Issue by sschu** [keycloak/keycloak#15234]
### Description

Quarkus recommends micrometer metrics (see https://quarkus.io/guides/micrometer). To be in line with Quarkus recommendations, it makes sense to switch to micrometer in Keycloak as well.

### Discussion

https://github.com/keycloak/keycloak/discussions/8490

### Motivation

Following Quarkus recommendations.

### Details

I just provide this as a draft together with a draft PR. Just to make any changes as transparent as possible. This is also related to https://github.com/keycloak/keycloak/issues/9036. Draft PR: https://github.com/keycloak/keycloak/pull/15235

**Comment by ahus1** [comment]
PR #15235 has been merged.
