### ISSUE TITLE
Unable to specify default identity provider in 19.0.3

### ISSUE THREAD

**Issue by BrianSiimAndersenEG** [keycloak/keycloak#15270]
### Area

identity-brokering

### Describe the bug

I've added an identity provider and wish to set this as default for the browser flow.
When I try to edit the browser flow and click on the cog icon for the Identity Provider Redirector, to be able to specify the default identity provider, I'm getting this error: Cannot convert undefined or null to object.
I don't see anything in the Keycloak output (running in Docker).

### Version

19.0.3

### Expected behavior

I expected to get to the page where I should be able to specify the default identity provider.

### Actual behavior

Getting this error when clicking on the cog icon: Cannot convert undefined or null to object.

### How to Reproduce?

Go to Authentication and click the browser flow. Click on the settings icon (cog) for Identity Provider Redirector.

**Comment by stianst** [comment]
Please try 20.0.0 as there was a large number of bug fixes in the new admin console.

**Comment by BrianSiimAndersenEG** [comment]
@stianst The error does not occur on 20.0.0. Thank you.
