### ISSUE TITLE
Set redirect_uri on password reset link

### ISSUE THREAD

**Issue by fregge** [keycloak/keycloak#15279]
### Description

There should be a possibility to provide a specific (but valid) redirect_uri for the password reset link.

### Motivation

Right now when you open the password reset link you can provide a "client" URL parameter. If you don't set a client, you will be redirected to the account console after reseting the password. If you set the "client" parameter you will be redirected to the first valid redirect URI of that client.

There are a lot of use cases where you want to be able to redirect to a specific URI after password reset. For example:
- When you have a locale in the redirect URI and want to jump back to the one you came from
- There are several sub sites that have a link to the password reset functionality and you want to jump back to the right one
- ...

I can see no reason, why you shouldn't be able to redirect to a specific uri if it is valid for the client.

### Details

Just add the OIDC redirect_uri URL param to the request, validate and use it, or choose the first one, if none was provided for upwards compatibility.

**Comment by mposolda** [comment]
Closing as this was already addressed by https://github.com/keycloak/keycloak/commit/c94f9f571611461bc8e11f8095d4a78a91a221cf, so I am closing this. Just a note that endpoint is not officially supported and the format of this endpoint might be changed in the future (there is a chance we will change it even for Keycloak 24, but some support for redirect_uri will be probably supported).
