### ISSUE TITLE
kc.bat fails with ClassNotFoundException

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak#15281]
### Area

dist/quarkus

### Describe the bug

In [kc.bat#L127](https://github.com/keycloak/keycloak/blob/9f95b6ec63489f70df98617ece794e1ce2c9f0df/quarkus/dist/src/main/content/bin/kc.bat#L127) `:` is used as path separator instead of `;`, which causes startup to fail with:

```
ClassNotFoundException: io.quarkus.bootstrap.runner.QuarkusEntryPoint
```

### Version

20.0.0

### Expected behavior

Startup success.

### Actual behavior

Startup failure.

### How to Reproduce?

- Download the Server-Distribution from https://www.keycloak.org/downloads
- Unpack on a Windows System
- Run `kc.bat start-dev --db-url="jdbc:h2:file:./data/h2db/kc;NON_KEYWORDS=VALUE"`

**Comment by choma** [comment]
Is there a problem with the path too? this `bootstrap` directory:

```bat
set "CLASSPATH_OPTS=%DIRNAME%..\lib\quarkus-run.jar;%DIRNAME%..\lib\bootstrap\*"
```
does not exist. 

Maybe it should be:

```bat
set "CLASSPATH_OPTS=%DIRNAME%..\lib\quarkus-run.jar;%DIRNAME%..\lib\lib\boot\*"
```

**Comment by krasholo** [comment]
In Keycloak Download homepage is still present the wrong ZIP Quarkus Distribution (kc.bat not fixed)
