### ISSUE TITLE
Remove FreeOTP application 

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#15301]
### Description

The FreeOTP applications are no longer actively maintained, and should no longer be listed in Keycloak.

Last commit to Android version was over 2 years ago. https://github.com/freeotp/freeotp-android/commit/eb2f12f33a38235433fd83e0ad3eb15affae871f

Apple version is more actively maintained, but we should not list an application where only one version is maintained. https://github.com/freeotp/freeotp-ios/commits/master

**Comment by marek-surek** [comment]
Android version has many new commits recently: https://github.com/freeotp/freeotp-android/commits/master

**Comment by stianst** [comment]
@marek-surek thanks, will keep it around for now
