### ISSUE TITLE
Create a helm chart for the new Keycloak Operator

### ISSUE THREAD

**Issue by janaurka** [keycloak/keycloak#15313]
### Description

With the release of Keycloak 20 and the creation of the new quarkus based `operator`, having an official helm chart which implements all the features the operator has (and will get) would be super beneficial. 

Since the operator is designed to run on Kubernetes, it would be great to also have an official recommended way of deploying this operator using helm (or if another method/technology is preferred, then in a way this method/technology works).

### Motivation

There is no official recommended way of deploying the operator to a kubernetes cluster. This should be fixed.

### Details

There are already some resources gathered in https://github.com/keycloak/keycloak-k8s-resources and there are also people who volunteer to create/maintain such a helm chart: https://github.com/keycloak/keycloak/issues/16210

**Comment by janaurka** [comment]
Since there are some volunteers who would create/maintain such a Helm Chart, I guess it would work out if the Keycloak Maintainers would acknowledge, that they are willing to have an official Helm Chart and are happy to get a PullRequest (either in this Repo, since the operator was pulled in here, or in a dedicated repository). Then I guess this can be actively worked on from by the community.

**Comment by janaurka** [comment]
FYI: A colleague of mine, @hairmare, wrote a chart for the keycloak operator. Currently the chart can be found here: https://github.com/adfinis/helm-charts/tree/main/charts/keycloak-operator

**Comment by vmuzikar** [comment]
@janaurka Thanks for the interest in Keycloak Helm charts. Unfortunately, [this statement](https://github.com/keycloak/keycloak/issues/16210#issuecomment-1462203645) is still valid, we don't plan officially supported Helm charts (for Keycloak or the Operator) at the moment.
