### ISSUE TITLE
Keycloak.x duplicate logs are printed 

### ISSUE THREAD

**Issue by sreekesh93** [keycloak/keycloak#15311]
### Area

core

### Describe the bug

able to see same logs printed multiple times (around 6 times)

### Version

18.0.0

### Expected behavior

a log should printed based on the occurrences

### Actual behavior

logs are printed than expected time

### How to Reproduce?

no actual steps to reproduce enabled json logs even for defualt config same behaviour noted

### Anything else?

-

**Comment by stianst** [comment]
Please verify with the latest release, provide steps to reproduce, and an example of the duplicated logs.

**Comment by mposolda** [comment]
I am closing as requested info was not provided. Please re-open just if you are able to reproduce with latest Keycloak 21 release . In that case, please add the details requested in previous comment
