### ISSUE TITLE
Cleanup dependencies and align with Quarkus

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#15325]
* Clean up dependencies overrides in the parent POM. Point is to rely on Quarkus transitive dependencies (where it makes sense).
* Remove remnants of WildFly dist dependencies.
* Unify Hibernate versions: https://github.com/keycloak/keycloak/issues/14915

**Comment by vmuzikar** [comment]
I believe there are two additional points:
* Remove deps overrides from `quarkus` module where possible and use deps from root POM instead.
* Related to that, update the [upgrade script](https://github.com/keycloak/keycloak/blob/28fc5b4574ed5c8cc000ae11d5595d91af7f6a70/quarkus/set-quarkus-version.sh) to reflect these changes.

CC @Pepo48 @pedroigor

**Comment by Pepo48** [comment]
Another follow up: #15870
