### ISSUE TITLE
Wildfly jars that were supposedly removed are still getting pulled in docker image

### ISSUE THREAD

**Issue by nvp152** [keycloak/keycloak#15338]
### Area

dist/wildfly

### Describe the bug

As far as I understand from the release notes wildly has been removed with version 20.0.0. Yet I see that keycloak-20.0.0.tar.gz still seems to include them under directory /opt/keycloak/lib/lib/main/

org.wildfly.security.wildfly-elytron-1.18.3.Final.jar
org.wildfly.security.wildfly-elytron-asn1-1.20.1.Final.jar
org.wildfly.security.wildfly-elytron-audit-1.18.3.Final.jar
....
....

This is an issue since the wildfly jars at version 1.18.3 have some known vulns that are getting flagged by docker image scanners like anchore.

### Version

20.0.0

### Expected behavior

The jars should no longer be pulled anymore since Wildfly support was removed.

### Actual behavior

The jars are getting pulled into the docker image

### How to Reproduce?

Simply fetch artifact at:
https://github.com/keycloak/keycloak/releases/download/20.0.0/keycloak-20.0.0.tar.gz

**Comment by stianst** [comment]
There's a difference between WildFly "the app server" and a dependency with the name "WildFly" in it.
