### ISSUE TITLE
snakeyaml vulnerability GHSA-3mc7-4q67-w48m impacting CLI

### ISSUE THREAD

**Issue by nvp152** [keycloak/keycloak#15339]
### Area

admin/cli

### Describe the bug

The version of snakeyaml should be upgrade to 1.26 to 1.31 in the artifact below to address a "high" vuln

keycloak-admin-cli-20.0.0.jar
keycloak-client-registration-cli-20.0.0.jar

See: https://github.com/advisories/GHSA-3mc7-4q67-w48m

The Anchore docker image scanner (among others) is flagging that vuln.

### Version

20.0.0

### Expected behavior

Neither keycloak-admin-cli, nor keycloak-client-registration-cli should have "high" vulnerabilities.

### Actual behavior

Both keycloak-admin-cli and keycloak-client-registration-cli have "high" vulnerabilities.

### How to Reproduce?

The snakeyaml version of 1.26 being used is known to be vulnerable.

**Comment by abstractj** [comment]
@vmuzikar I'm afraid that this is something that we are unable to fix at the moment. To be honest, I haven't looked into this, but it is possible to find a detailed explanation here https://github.com/keycloak/keycloak/issues/14850

If you have any questions, please let me know.

**Comment by pedroigor** [comment]
I'm closing this one as per last comment from @abstractj.

**Comment by trixpan** [comment]
@abstractj @pedroigor given the usage of ua-parser is largely [cosmetic](https://github.com/keycloak/keycloak/blob/2e5cb103eead82406795461f9c35fe3754e770ba/server-spi-private/src/main/java/org/keycloak/device/DeviceActivityManager.java#L36), wouldn't it be easier to remove/refactor/port to another [library](https://github.com/nielsbasjes/yauaa)
