### ISSUE TITLE
Windows: keycloak-20.0.0 start up error

### ISSUE THREAD

**Issue by echosunstar** [keycloak/keycloak#15362]
### Area

core

### Describe the bug

 keycloak-20.0.0 does not start up under windows

### Version

 keycloak-20.0.0

### Expected behavior

 keycloak-20.0.0 should start up under windows

### Actual behavior

**PS C:\keycloak\keycloak-20.0.0>** java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10-21)
OpenJDK 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
**PS C:\keycloak\keycloak-20.0.0>** .\bin\kc.bat start-dev
Error: Could not find or load main class io.quarkus.bootstrap.runner.QuarkusEntryPoint
Caused by: java.lang.ClassNotFoundException: io.quarkus.bootstrap.runner.QuarkusEntryPoint
PS C:\keycloak\keycloak-20.0.0>

### How to Reproduce?

- install openjdk 19.0.1 2022-10-18
- install keycloak-20.0.0 under windows as recommended by the documentation
- run **.\bin\kc.bat start-dev**

**Comment by Eng-Fouad** [comment]
See #15281

**Comment by stianst** [comment]
Closing as this is a duplicate
