### ISSUE TITLE
searchByFirstName and searchByLastName are taking email as input which is wrong.

### ISSUE THREAD

**Issue by manojjgudi** [keycloak/keycloak#15368]
### Area

admin/api

### Describe the bug

searchByFirstName and searchByLastName are taking email as input which is wrong.

### Version

20.0.0

### Expected behavior

searchByFirstName and searchByLastName should take firstName and lastName respectively as input.

### Actual behavior

searchByFirstName and searchByLastName are showing email as input which is misleading.

### How to Reproduce?

Use function searchByFirstName or searchByLastName.

**Comment by sschu** [comment]
I found that in the admin client the variable name is wrong. I don't think this has consequences on the functionality.
