### ISSUE TITLE
UserSessionNoteMapper cannot be configured to add a claim to the UserInfo Token

### ISSUE THREAD

**Issue by sonOfRa** [keycloak/keycloak#15369]
### Area

oidc

### Describe the bug

When adding a UserSessionNoteMapper, the mapper cannot be configured to add the mapped claim to the UserInfoToken. The other 3 types (Access Token, ID Token, Access Token Response) are available.

### Version

19.0.3

### Expected behavior

Add to UserInfo Token *should* be a configuration option when adding a UserSessionNoteMapper.

### Actual behavior

Add to UserInfo Token *is not* a configuration option when adding a UserSessionNoteMapper.

### How to Reproduce?

Add a UserSessionNoteMapper to any client or scope

### Anything else?

All that should be needed is adding the `UserInfoTokenMapper` interface to `UserSessionNoteMapper`. I'll provide a PR and link it to the issue shortly.

**Comment by mposolda** [comment]
duplicates #15251
I am closing as a duplicate. Please continue in the other issue for the further discussions/questions/suggestions around this.

**Comment by jonkoops** [comment]
Duplicate of #15251
