### ISSUE TITLE
User not added to an LDAP Federated Base

### ISSUE THREAD

**Issue by mateuslima90** [keycloak/keycloak#15360]
### Area

ldap

### Describe the bug

I created a federation with LDAP (edit mode writable) and I can't create user in LDAP by Keycloak.

### Version

19.0.2

### Expected behavior

I want to create an user in keycloak and create in LDAP too. My realms is federate with LDAP Server

### Actual behavior

In my case the user just is created local database.

### How to Reproduce?

I have openldap in docker and I created a ldap federation with edit mode writable in realm in Keycloak. When I try to create an user in Keycloak, He doesnt created in LDAP Server (openldap). 

### Anything else?

I checked in code tha LDAP Federation and I found this:

 
```
public boolean synchronizeRegistrations() {        
       return "true".equalsIgnoreCase(model.getConfig().getFirst(LDAPConstants.SYNC_REGISTRATIONS)) && editMode == UserStorageProvider.EditMode.WRITABLE;
   }
```

When I created the ldap federation I didnt find an option to apply this configuration in this component.

I solve my problem using keycloak Rest API and add this configuration and that works for me.

```
 {
	"parentId": "460d5357-6067-4e70-86b7-354e2977f5ee",
	"providerId": "ldap",
	"providerType": "org.keycloak.storage.UserStorageProvider",
	"config": {
		"syncRegistrations": [ true ]
	}
}
```

**Comment by sguilhen** [comment]
@mateuslima90 Are you able to try Keycloak 21? I'm asking because some functionality from the old console was missing in the new console and AFAIK it was fixed in recent versions.

**Comment by sguilhen** [comment]
I'm closing this for now as it has been probably fixed in most recent versions. @mateuslima90 please re-open if you still have issues with latest Keycloak.
