### ISSUE TITLE
user_info not working after upgrading from 19.0.3 to 20.0.0

### ISSUE THREAD

**Issue by FlyveHest** [keycloak/keycloak#15361]
### Area

oidc

### Describe the bug

I am using a very basic OIDC plugin for a PHP based forum (MyBB with Isango plugin), and am using KeyCloak for authentication.

This has been working as intended, until I upgraded to 20, and now I am getting a 403 error when trying to sign in.

I am getting this in the KeyCloak log

`2022-11-05 19:52:02,996 WARN  [org.keycloak.events] (executor-thread-7) type=USER_INFO_REQUEST_ERROR, realmId=REALM, clientId=null, userId=null, ipAddress=x.x.x.x, error=access_denied, auth_method=validate_access_token`

and this in the apache log for the reverse proxy I run in front of KeyCloak

```
x.x.x.1 - - [05/Nov/2022:21:01:02 +0100] "GET /realms/REALM/protocol/openid-connect/auth?client_id=XXX&redirect_uri=XXX&state=4e0845394e26e1bad069a8b7855620d6f010899bf11b8bc79d7f4cd51133737
x.x.x.249 - - [05/Nov/2022:21:01:02 +0100] "POST /realms/REALM/protocol/openid-connect/token HTTP/1.1" 200 7747 "-" "-"
x.x.x.249 - - [05/Nov/2022:21:01:02 +0100] "GET /realms/REALM/protocol/openid-connect/userinfo HTTP/1.1" 403 5668 "-" "-"
```

Running under KeyCloak 19, I get a 200 http code in the last request.

I can't seem to find anything related to the userinfo endpoint in the upgrade log

### Version

20.0.0

### Expected behavior

Authentication works as intended, and as it always has.

### Actual behavior

KeyCloak denies authentication

### How to Reproduce?

For me, upgrading to v20, but i'm not sure how to reproduce the bug consistently.

The flow "Just Worked" in v19

**Comment by dobrik-ardas** [comment]
Pay attention on "WWW-Authenticate" header in the 403 response.
I had the same issue, I've added the "openid" scope to auth request and it worked.

**Comment by FlyveHest** [comment]
> Pay attention on "WWW-Authenticate" header in the 403 response. I had the same issue, I've added the "openid" scope to auth request and it worked.

That worked, thanks a lot :)

**Comment by kuhhpid** [comment]
> Pay attention on "WWW-Authenticate" header in the 403 response. I had the same issue, I've added the "openid" scope to auth request and it worked.

I had this problem with Portainer OIDC Authentication and this worked, thanks :-)

**Comment by pantherauncia** [comment]
Hi!

I've the same warn/error with this config:

spring:
  application:
    name: "@project.artifactId@"
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 
            redirect-uri:
            # scope: openid
        provider:
          keycloak:
            issuer-uri: 
            user-info-uri: 
            
Client-id, redirect-uri, issuer-uri and user-info-uri all corrected valued.

If enable ' scope: openid ' I obtain this error on browser:
   
"Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
...
There was an unexpected error (type=Not Found, status=404). "

What could it depend on? Thanks
