### ISSUE TITLE
Broken rendering for "loginTotpStep1" in OTP screen for several languages

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#15373]
### Area

authentication

### Describe the bug

In the OTP screen, [login-config-totp.ftl](https://github.com/keycloak/keycloak/blob/600fff4f6f4299d9762df5f104bd75e2d6fe2685/themes/src/main/resources/theme/base/login/login-config-totp.ftl#L9), the loginTotpStep1 is rendered as text, but there are Languages, which are having Anchors for values:

For [EN ](https://github.com/keycloak/keycloak/blob/600fff4f6f4299d9762df5f104bd75e2d6fe2685/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L118)for example (and for DE and all the other languages), it is OK: 
`loginTotpStep1=Install one of the following applications on your mobile:`
But for languages like [ft, lt, sk, sv, zh_CN, no](https://github.com/kurzdigital/keycloak-1/blob/885eec5ef2628e41d59f4017745df44e7b519533/themes/src/main/resources-community/theme/base/login/messages/messages_no.properties#L70) it is:
`loginTotpStep1=Installer <a href="https://freeotp.github.io/" target="_blank">FreeOTP</a> eller Google Authenticator p\u00E5 din mobiltelefon. Begge applikasjoner er tilgjengelige p\u00E5 <a href="https://play.google.com">Google Play</a> og Apple App Store.`
where the Hyperlink is not rendered properly, but is changed with URL encoding

### Version

19.0.3

### Expected behavior

Render the HTML's properly
or
Adjust the **loginTotpStep1** to NOT contain hyperlinks

### Actual behavior

There are some languages containing "hyperlink" for loginTotpStep1 message_key, where they are not rendered properly but rendered as text, like
`Installer <a href="https://freeotp.github.io/" target="_blank">FreeOTP</a> eller Google Authenticator på din mobiltelefon. Begge applikasjoner er tilgjengelige på <a href="https://play.google.com">Google Play</a> og Apple App Store.`

### How to Reproduce?

Open the OTP page with language like Norsk (compare it with English)

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.
