### ISSUE TITLE
kid of refresh token not in jwks

### ISSUE THREAD

**Issue by aruehl** [keycloak/keycloak#15390]
### Area

oidc

### Describe the bug

The kid of refresh tokens are not in jwks.

### Version

20.0.0

### Expected behavior

kid of the refresh tokens is listed in the jwks

### Actual behavior

kid of the refresh tokens is not listed in the jwks

### How to Reproduce?

- get a refresh token
- decode the header
- look for the kid in the jwks of the realm

### Anything else?

access and id tokens are using ES256 algorithm and the kid is listed within the jwks, but the refresh token is using the HS256 algorithm

**Comment by stianst** [comment]
Refresh token is an token that only Keycloak should be able verify and understand, and it's signed with keys not advertised.
