### ISSUE TITLE
Introduce optimistic locking for HotRod storage

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#15402]
After introducing https://github.com/keycloak/keycloak/issues/13273 we should also add possibility for optimistic locking

**Comment by hmlnarik** [comment]
Dependent on #13280

**Comment by mhajas** [comment]
To have a performant version of this, we would need this enhancement to be added first: https://issues.redhat.com/browse/ISPN-14478

Before this is available, we would need to read each object using `remoteCache.getWithMetadata(id)`. We can do this, for example, using an Ickle query just to find all ids that fulfil the search and then read them one by one using `getWithMetadata`.
