### ISSUE TITLE
ConcurrentLoginTest failures on ConcurrentHashMap

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#15410]
### Area

storage

### Describe the bug

After re-enabling the concurrent login tests that are currently disabled (see #12707), failures are seen when the following tests are run with Hotrod and CHM:

* `concurrentLoginSingleUser`
* `concurrentLoginMultipleUsers`

In both tests, the user session can't be found in `OAuth2CodeParser#parseCode`, and we see the following messages in the logs:

```
16:49:37,410 [XNIO-2 task-3] WARN  [o.k.events] type=CODE_TO_TOKEN_ERROR, realmId=test, clientId=client3, userId=null, ipAddress=127.0.0.1, error=user_session_not_found, grant_type=authorization_code, code_id=3b446833-6ab7-4a25-b0b4-18cb9592ff63, client_auth_method=client-secret
```

This event is created in `TokenEndpoint.codeToToken`:

https://github.com/keycloak/keycloak/blob/dc007eab6f53f1b4fdf112ad167a7cd0dd744fd3/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L346-L349

and happens every time the user session can't be found by client in `OAuth2CodeParser`:

https://github.com/keycloak/keycloak/blob/dc007eab6f53f1b4fdf112ad167a7cd0dd744fd3/services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2CodeParser.java#L104

For some reason, when CHM or Hotrod are used the user session is sometimes not found

Both tests pass on JPA with Postgres.

### Version

main

### Expected behavior

Tests should pass with all stores

### Actual behavior

Tests fail on CHM and Hotrod due to user session sometimes not being located

### How to Reproduce?

Re-enable the mentioned tests and run them with CHM or Hotrod

**Comment by mhajas** [comment]
This issue will be probably fixed by https://github.com/keycloak/keycloak/issues/13273 for HotRod

**Comment by mhajas** [comment]
For HotRod the same applies also to tests:
```
ComponentsTest#testConcurrencyWithoutChildren
ComponentsTest#testConcurrencyWithChildren
```

**Comment by mhajas** [comment]
This is done for HotRod as part of https://github.com/keycloak/keycloak/pull/16619. This issue needs to be done only for CHM

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
