### ISSUE TITLE
All configurations documentation lists database vendor as a build configuration

### ISSUE THREAD

**Issue by carlin-q-scott** [keycloak/keycloak#15412]
### Area

docs

### Describe the bug

The database vendor argument is listed as a build configuration, but it's actually a runtime configuration.
<html>
<body>

 
--
CLI: --db
Env: KC_DB

</body>
</html>

### Version

20.0.1

### Expected behavior

database vendor set at build time is used during runtime

### Actual behavior

default file based database vendor is used at runtime

### How to Reproduce?

Build container using --db argument or KC_DB env var

### Anything else?

This was incredibly frustrating because I had everything else set for the db, and made a bunch of changes to my config. And then the container was updated and blew away all of my configuration. I had even checked the log output to make sure there were no errors in there, and there weren't any.

**Comment by carlin-q-scott** [comment]
If I don't supply the optimized argument does it lose the build configuration for the dB provider?

**Comment by lexcao** [comment]
Yes, 
The `build` command would process all the build configurations to create a building output.
The `--optimized` option would use the building output to start the deployment.

If no `--optimized` is present for the `start` command, it would automatically build before starting, so there may be a missing build configuration.

You can refer to this [doc](https://www.keycloak.org/server/configuration), `Optimize the Keycloak startup` section.
