### ISSUE TITLE
Keycloak's API for generating JWT does not support JWK in header

### ISSUE THREAD

**Issue by RuslanTM** [keycloak/keycloak#15419]
### Description

Our API for generating JWT does not support including JWK in header. This feature is extremely important for DPoP mechanism because DPoP Proofs should contain JWK in headers

**Comment by sschu** [comment]
Is this not included here: https://github.com/keycloak/keycloak/pull/8895 ?

**Comment by dteleguin** [comment]
@sschu no this is not included into the main DPoP PR

The purpose of this one is to facilitate DPoP proof generation within Keycloak codebase, while the DPoP PR is more focused on DPoP validation. This will be needed for DPoP tests and brokering to DPoP-enabled 3rd party IAMs. If you feel this should be included into the main PR, please let us know.

**Comment by mposolda** [comment]
duplicates #31681

I am closing this as this was already done by #31681 and is available in Keycloak 26
