### ISSUE TITLE
User Profile Attributes not showing up in Admincp User view and User account management view

### ISSUE THREAD

**Issue by radonthetyrant** [keycloak/keycloak#15431]
### Area

user-profile

### Describe the bug

After adding a custom User Profile Attribute with enabled User Profile preview feature, the Attribute shows up in the registration page (https://keycloak/realms/realm/login-actions/registration?client_id=my-client) but not in the admincp edit user page and not in the users account management page (https://keycloak/realms/realm/account/#/personal-info)

### Version

20.0.1

### Expected behavior

When adding new User Profile attributes and configuring them properly including admin view and edit permissions, they should show up on all places where user data or user attributes are modified, including the admincp.

### Actual behavior

User Profiles enabled in realm.
User profiles preview feature enabled in keycloak version 20.0.1
User Profile attribute configured as such:
![image](https://user-images.githubusercontent.com/4189978/200931488-fa0815d0-0318-424a-b8d6-8fa6f21b6cae.png)

Signup page:
![image](https://user-images.githubusercontent.com/4189978/200932548-ea84fad2-487a-42d6-8e5b-16c0c1bf56fc.png)

User account management page:
![image](https://user-images.githubusercontent.com/4189978/200931867-1cc123d3-ad55-4139-8475-cc51eddd780b.png)
Note that clicking on save causes error "Please specify 'Display Name'." to show up, indicating a required but invisible field.

AdminCP page:
![image](https://user-images.githubusercontent.com/4189978/200932711-004900c3-eec9-4dd7-ad19-6d68d30d5182.png)
Note that First Name and Last Name are visible, altough those attributes have been deleted and when clicking save, a similar error shows up, indicating the field "displayname" must be set

### How to Reproduce?

Boot up 20.0.1 with user profiles enabled,
create user profile attribute as shown above,
try out features as pictured in the screenshots above

### Anything else?

The documentation at (https://www.keycloak.org/docs/latest/server_admin/#using-dynamic-forms) says that the dynamic forms will take these attributes into account, but this does not seem to be the case. additionally the app was restarted in case any cache is holding up the form refreshing.

**Comment by ssilvert** [comment]
@radonthetyrant We are in the middle of implementing User Profile attributes in the User details screen for the new admin console.  So you should see that in a release very soon.

In the mean time, the workaround is to add the key/value pair on the `Attributes` page.
