### ISSUE TITLE
Keycloak tag for 19.0.3 changed manifest ID's

### ISSUE THREAD

**Issue by archoversight** [keycloak/keycloak#15430]
### Area

core

### Describe the bug

Due to security requirements we pin our dependencies using sha256 hashes for the docker containers running in our k8s, and we noticed that the tag for 19.0.3 changed digests from:

`quay.io/keycloak/keycloak:19.0.3@sha256:0b5945042981d393dc252b816eebe4941f72f76bb7f87aa36edbdacdc7a0ce96`

to

`quay.io/keycloak/keycloak:19.0.3@sha256:979743420b63a7c45fcd2cbaf0a0c528473fd28d6f4cd627969e1b4c39f6fcc0`

Is there any documentation on what changes went into that change or why the manifest was updated? Is there also a possibility of leaving the old manifest in place so that pulls don't start failing?

### Version

19.0.3

### Expected behavior

Manifest sha256 stays the same for the same tag.

### Actual behavior

Manifest sha256 was changed for the tag

### How to Reproduce?

`docker pull quay.io/keycloak/keycloak@sha256:0b5945042981d393dc252b816eebe4941f72f76bb7f87aa36edbdacdc7a0ce96`

fails with:

```
Error response from daemon: manifest for quay.io/keycloak/keycloak@sha256:0b5945042981d393dc252b816eebe4941f72f76bb7f87aa36edbdacdc7a0ce96 not found: manifest unknown: manifest unknown
```

**Comment by stianst** [comment]
No longer an issue in Keycloak 20
