### ISSUE TITLE
When implementing SSO using the SecureSecurityConfigurerAdapter, a "failed verification of token: Unknown or unsupported token algorithm" error occurs when using a JWT signed with ES256.

### ISSUE THREAD

**Issue by atsushi0804** [keycloak/keycloak#15433]
### Area

adapter/spring

### Describe the bug

When implementing SSO using the SecureSecurityConfigurerAdapter, a "failed verification of token: Unknown or unsupported token algorithm" error occurs when using a JWT signed with ES256.

The pom.xml is as follows

`

<dependencies>

		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-spring-boot-starter</artifactId>
		</dependency>

	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.keycloak.bom</groupId>
				<artifactId>keycloak-adapter-bom</artifactId>
				<version>20.0.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>`

If the Keycloak server's signature algorithm is RS256, it works fine. However, if the
When the signature algorithm is ES256, "failed verification of token: Unknown or unsupported token algorithm" occuerd

`o.k.adapters.OAuthRequestAuthenticator   : failed verification of token: Unknown or unsupported token algorithm`

I assume it is due to TokenVerifier#verifier being null, is there any way to set this?

### Version

20.0.1

### Expected behavior

TokenVerifier can verify JWT signed with ES256.

### Actual behavior

"failed verification of token: Unknown or unsupported token algorithm" occuerd.
TokenVerifier#verifier is null.

### How to Reproduce?

1. Access the Spring-Boot application with a browser.

2. Enter user information on the Keycloak login screen.

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
