### ISSUE TITLE
Customize log messages for user storage LDAP configuration in KC shown in admin UI

### ISSUE THREAD

**Issue by souravs17031999** [keycloak/keycloak#15434]
### Description

Hi team,

I have setup of LDAP active directory configured with KC and as a end user perspective, I want to make sure whenever this configuration is wrongly configured, I get clear and specific message in admin console UI to help in troubleshooting.

What is currently happening is that Keycloak is throwing generic error messages in UI although application (deployed as docker container) itself shows some logs which are helpful but those are all in backend and doesn't helps end-users who are exposed only to admin UI.

Is it possible somehow to modify those log messages in the UI and get specific messages as per the exact mis-configuration ?

Note: Even the API response is generic message "unknown_error", "LDAP test error" etc... not indicating the exact issue.

I will attach one such scenario for better understanding here.
Ex. below, It would be nice for the end user if it shows the unknown host/wrong host configured issue instead of showing generic messages.

[keycloak LDAP configuration]
![paint](https://user-images.githubusercontent.com/33771969/200897797-47531052-6e5d-4e9f-8907-b6558aaf393c.PNG)

[keycloak container logs]
![keycloak-backend](https://user-images.githubusercontent.com/33771969/200762154-d732e693-f843-4843-8db9-2092c45de7ea.PNG)

[keycloak UI]
![keycloak-admin](https://user-images.githubusercontent.com/33771969/200763266-39e7123e-adea-4230-88ba-3bddfea236c5.PNG)

### Discussion

https://github.com/keycloak/keycloak/discussions/15416

### Motivation

It helps to the end user while troubleshooting the exact issue while doing configuration who are only exposed to keycloak admin UI and doesn't have access to server logs.

**Comment by souravs17031999** [comment]
@mposolda @stianst @pedroigor any suggestions if this can be acheived somehow by extending existing functionality ?

**Comment by souravs17031999** [comment]
Seems like no body is really interested in this kind of feature ?

**Comment by mposolda** [comment]
@souravs17031999 Maybe we have some space for improvement here, however there is one important point: Showing too much details in the UI/API opens potential for various attacks like XSS for example.

For example if `Connection URL` is filled to `foobar` and the UI will display error message like `Invalid connection URL: foobar`, it is not good as in case that if `Connection URL` contains some strange stuff like `foo</div>alert('xss attack')</div>` there is a chance to have this shown in the UI and the JS code to be executed. So whatever improvement is done, it will be still good to stick with "generic" messages (Like `Incorrect connection URL` for example) and never show the values, which were filled by admin.

Security is  more important than UX experience here.

**Comment by souravs17031999** [comment]
@mposolda , I agree security should always be more important and keeping that in mind, some minor improvements could be there such that showing ```Incorrect connection URL``` instead of showing something like ```see server.log for details```.

**Comment by souravs17031999** [comment]
@mposolda is there any capability on admin UI to customize just like templates are there to customize themes ?

**Comment by jonkoops** [comment]
@souravs17031999 No, this is not possible in the new Admin Console. We are working on creating an inventory of this under https://github.com/keycloak/keycloak/issues/19969.

**Comment by jonkoops** [comment]
@mposolda FYI, I am not concerned about XSS from these messages. We do not parse them as HTML in the new Admin Console (default React behaviour).

I think the best approach here would be to improve the messages the API returns so they are more descriptive.

**Comment by souravs17031999** [comment]
@jonkoops I do agree that first step would be definately to improve the API message but still I am not very sure from the user's perspective how much it will help since message is required to be shown to the user so that they can correct the mis-configuration if any.

**Comment by nikumbgo12345** [comment]
@mposolda @abbra @wuwx  could you please assign this to me

**Comment by jonkoops** [comment]
@nikumbgo12345 Done, feel free to open up a PR anytime.

**Comment by dinutine** [comment]
@nikumbgo12345 already did some work to resolve this, maybe check my pull request

**Comment by jonkoops** [comment]
Let's coordinate on @dinutine's PR, feel free to leave a review/suggestions there on the implementation.
