### ISSUE TITLE
Upgrade from 19.0.3-legacy to 20.0.1 with Oracle 11g

### ISSUE THREAD

**Issue by wkruse** [keycloak/keycloak#15465]
### Area

storage

### Describe the bug

We are running Keycloak **19.0.3-legacy** (WildFly) with Oracle **11g** (11.2.0.4) and trying to upgrade to Keycloak **20.0.1** (Quarkus).

The Keycloak **20.0.1** crashes on start with:

```
[org.hibernate.SQL] (main) select migrationm0_.ID as id1_39_, migrationm0_.UPDATE_TIME as update_time2_39_, migrationm0_.VERSION as version3_39_ from MIGRATION_MODEL migrationm0_ order by migrationm0_.UPDATE_TIME DESC fetch first ? rows only
 2022-11-11 11:21:54,728 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) could not extract ResultSet [n/a]: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
...
 Caused by: Error : 933, Position : 191, Sql = select migrationm0_.ID as id1_39_, migrationm0_.UPDATE_TIME as update_time2_39_, migrationm0_.VERSION as version3_39_ from MIGRATION_MODEL migrationm0_ order by migrationm0_.UPDATE_TIME DESC fetch first :1  rows only, OriginalSql = select migrationm0_.ID as id1_39_, migrationm0_.UPDATE_TIME as update_time2_39_, migrationm0_.VERSION as version3_39_ from MIGRATION_MODEL migrationm0_ order by migrationm0_.UPDATE_TIME DESC fetch first ? rows only, Error Msg = ORA-00933: SQL command not properly ended

 	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
 	... 74 more

 2022-11-11 11:21:54,731 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 933, SQLState: 42000
 2022-11-11 11:21:54,731 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ORA-00933: SQL command not properly ended
```

Looks like according to the https://www.keycloak.org/server/db Oracle 11g is **not** supported anymore?

We tried setting the Hibernate ORM dialect to 

```
quarkus.hibernate-orm.dialect=org.hibernate.dialect.Oracle10gDialect
```

without any success.

We also tried adding our `ojdbc.jar` to the custom built Docker container and running `kc.sh build` with `quarkus.properties` similar to

```
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@192.168.1.12:1521/ORCL_SVC
quarkus.datasource.username=scott
quarkus.datasource.password=tiger
```

https://quarkus.io/guides/datasource#other-databases

also without any success.

Is there a way to run Keycloak **20.0.1** with Oracle **11g** or are we stuck on Keycloak **19.0.3-legacy** now? (Upgrading Oracle is sadly not an option for us.)

### Version

20.0.1

### Expected behavior

Keycloak 20.0.1 runs with Oracle 11g

### Actual behavior

Keycloak 20.0.1 crashes

### How to Reproduce?

Run Keycloak 20.0.1 with Oracle 11g.

### Anything else?

Maybe related #10749

**Comment by trailhuntervodafone** [comment]
i had the same issue. Setting the oracle dialect when starting up keycloak helped:
 bin/kc.sh start -Dkc.db-dialect=org.hibernate.dialect.Oracle10gDialect (since 11g dialect is not existent)

If it is a good idea to run Keycloak (quarkus) with an old Oracle Version like this, shpuold be commented by some Keycloak developers, please.

**Comment by vramik** [comment]
@pedroigor could you please provide more information about the decision why there is `Oracle12cDialect` set here: https://github.com/keycloak/keycloak/blob/f8df04b3b8fa6b3a250a87330327e792bbd14955/quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java#L172

@hmlnarik FYI

**Comment by wkruse** [comment]
@trailhuntervodafone Thank you for the hint! I can confirm, that `kc.sh start -Dkc.db-dialect=org.hibernate.dialect.Oracle10gDialect` works.

**Comment by pedroigor** [comment]
@vramik The dialect (ant other values) are the defaults used by Quarkus JDBC extensions.

As @trailhuntervodafone, it should be possible to provide your own values too if you need.

But I think that won't be needed when using the new store as we are going to support postgres only, right?

**Comment by trailhuntervodafone** [comment]
@pedroigor : Thank you for your answer. Here https://www.keycloak.org/2022/02/dbs.html i read: "As such we are not currently planning on offering any second class databases long term, and rather phase out support for MySQL, MariaDB, SQL Server, and Oracle over time."
what does mean long term, how long "second class databases "  will be supported?

**Comment by wkruse** [comment]
Related #15528.

**Comment by pedroigor** [comment]
@trailhuntervodafone The best person to ask is @vmuzikar or @hmlnarik.

**Comment by pedroigor** [comment]
@wkruse Does that issue you linked fix this issue?

**Comment by wkruse** [comment]
@pedroigor The issue I linked is an additional issue, that breaks Keycloak 20.0.1 running with Oracle 11g. It should be fixed with Keycloak 20.0.2. What is still open, would be the [question](https://github.com/keycloak/keycloak/issues/15465#issuecomment-1327659982) by @trailhuntervodafone above. Any comments on that?

**Comment by wkruse** [comment]
@vmuzikar, @hmlnarik any comments regarding how long "second class databases" will be supported?

**Comment by hmlnarik** [comment]
The second class databases are only available with legacy store and their support will decline with the availability of the new store. This is unlikely to happen this year to allow for maturing the new store and a transition period for migrating from legacy to the new store.
