### ISSUE TITLE
Custom theme provider does not work properly

### ISSUE THREAD

**Issue by sakitA** [keycloak/keycloak#15477]
### Area

core

### Describe the bug

Hello.

I followed this https://www.keycloak.org/docs/latest/server_development/#_providers guide and create my custom theme selector. But keycloak does not call my theme selector provider factory 'create' method. It works only if I return 'default' when `ThemeSelectorProviderFactory.getId` method called. So what is the proper way to registering our custom theme provider and use our factory class instead of default one.

### Version

20.0.0

### Expected behavior

it should use custom theme selector provider factory instead of default one.

### Actual behavior

could not detect custom theme provider factory class if id different than 'default'

### How to Reproduce?

follow the https://www.keycloak.org/docs/latest/server_development/#_providers wiki and return any string other than 'default' when getId method called.

**Comment by lexcao** [comment]
Hi, if you want to override the default provider, you could try this [Configuring a default provider](https://www.keycloak.org/server/configuration-provider)

BTW, have you created the correct `META-INF` in your provider jar?

**Comment by sakitA** [comment]
@lexcao no, I don't want to override default one. I want configure my own, but it does not work. only way to use my custom provider I need to return 'default' as provider id which is not correct. for you question, yes I have `META-INF` in my jar otherwise even returning default does not work, am I right?

**Comment by mrpatrickpilch** [comment]
@sakitA You might be experiencing https://github.com/keycloak/keycloak/issues/16626

**Comment by mposolda** [comment]
duplicates #16626
I am closing as a duplicate. Please continue in the other issue for the further discussions/questions/suggestions around this.
