### ISSUE TITLE
12.0.4 - User names fields accept special characters 

### ISSUE THREAD

**Issue by Kalithasan-Periyasamy** [keycloak/keycloak#15485]
### Area

admin/ui

### Describe the bug

User name fields accept special characters in version 12.0.4. 

### Version

12.0.4

### Expected behavior

Need fix or configuration where user fields should not accept special characters.  

### Actual behavior

If entered special characters in firstname and lastname fields while creating users, it is accepting.

### How to Reproduce?

* Go to user creation page in keycloak console. 
* Create new user
* Give some special characters in firstname and lastname fields.
* And save it
* Check the created user.

**Comment by ssilvert** [comment]
Restrictions on special characters for firstname and lastname was not a feature in Keycloak 12.  However, the new user profile feature does allow you to set validators on these fields and others.  You can try it out in newer versions if you set --features=preview.
