### ISSUE TITLE
Update Datastore provider to contain full data model

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#15490]
As highlighted in #15470, the Datastore SPI does not yet cover all storage areas.

Fix that and update the `DefaultKeycloakSession` to target only the datastore API.

**Comment by dominikschlosser** [comment]
I started working on this and realized, that some of the missing providers currently are in _server-spi-private_ (StoreFactory for authorization, SingleUseObjects).
KeycloakSession itself is in _server-spi_ so it has no knowledge of these provider-types.

How do you wish this to be resolved?
