### ISSUE TITLE
LDAP Query failed with openLDAP

### ISSUE THREAD

**Issue by AlexeiKlimenko** [keycloak/keycloak#15491]
### Area

ldap

### Describe the bug

Keycloak - 18.0.0 (bare metal)
We have configured federation with openLDAP (both tests during configuring have been performed successfully). When imported users via full sync.

Periodically we faced with issue during sync changed users:
```
ERROR [org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager] (executor-thread-47417) Could not query server using DN [ou=users,dc=XXX,dc=YYY] and filter [(&(|(createTimestamp>=20221114074444.0Z)(modifyTimestamp>=20221114074444.0Z))(objectclass=inetOrgPerson)(objectclass=organizationalPerson))]: javax.naming.CommunicationException: connection closed [Root exception is java.io.IOException: connection closed]; remaining name 'ou=users,dc=XXX,dc=YYY'
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-47417) Uncaught server error: org.keycloak.models.ModelException: LDAP Query failed
Caused by: org.keycloak.models.ModelException: Querying of LDAP failed org.keycloak.storage.ldap.idm.query.internal.LDAPQuery@2a961670
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore.fetchQueryResults(LDAPIdentityStore.java:289)
	at org.keycloak.storage.ldap.idm.query.internal.LDAPQuery.getResultList(LDAPQuery.java:172)
	... 61 more
Caused by: javax.naming.CommunicationException: connection closed [Root exception is java.io.IOException: connection closed]; remaining name 'ou=users,dc=XXX,dc=YYY'
```
How to troubleshoot such a issues?

### Version

18.0.0

### Expected behavior

Successful sync changed users 

### Actual behavior

Errors are mentioned above

### How to Reproduce?

Configure federation with openLDAP

**Comment by vramik** [comment]
Hello @AlexeiKlimenko, thank you for your report. So far I was not able to reproduce the issue. Could you please provide more specific steps how to reproduce it? 

I was able to successfully configure user federation with openLdap with full sync. Maybe it'd be worth to try to tweak synchronization settings.

**Comment by AlexeiKlimenko** [comment]
Hello.
We have found out that the root cause was value of connection timeout - from both sides for KC and for LDAP. So increasing of this value has resolved this issue.

**Comment by vramik** [comment]
@AlexeiKlimenko thank you for the confirmation.

**Comment by redtomat87** [comment]
@AlexeiKlimenko Hello, could you explain, what specific timeouts have been changed and by what value? I have the same problem.

**Comment by alihoda** [comment]
I have the same error in my keycloak (ver 26.0.0) which connected to a openldap instance. Previous version (ver 24.0.5) did not have any problem with ldap instance. I tried to fix it by increasing `--spi-connections-http-client-default-establish-connection-timeout-millis` but it didn't help.
Can anyone explain why it effects on services' sso that are using keycloak? In my thoughts, it is more rational that the ldap synchronization and sso process should be independent from each other, so if the ldap side went wrong, it won't effect the keycloak and sso process.
