### ISSUE TITLE
Skip OTP for role in Conditional OTP Form doesn't work

### ISSUE THREAD

**Issue by breedjaram32** [keycloak/keycloak#15514]
### Area

authentication

### Describe the bug

I am using Google identity provider with settings

First login flow - **works fine**
<img width="500" alt="image" src="https://user-images.githubusercontent.com/77382127/201922164-28beb3d1-f366-4080-8cc4-af6531bfdf89.png">

**Post login flow with Conditional OTP Form and skipping for specific role _without-otp_**.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/77382127/201922398-4412f3c6-1c00-4614-9d3f-409e0ea3e10f.png">
and config
<img width="357" alt="image" src="https://user-images.githubusercontent.com/77382127/201922436-1e298501-ac8c-443d-b6f7-ca7406c3263d.png">

After upgrade of Keycloak to 20.0.1 this post login flow with`Conditional OTP Form` it stopped working!
**OTP form is is displayed constantly even if the user has an assigned role _without-otp_**
In older version of Keycloak this condition works perfect.

### Version

20.0.1

### Expected behavior

When I set Conditional OTP Form in post login flow so the OTP form will not be displayed for users with the given role for skipping.

### Actual behavior

OTP form is is displayed constantly even if the user has an assigned role _without-otp_

### How to Reproduce?

The whole setting procedure is in Describe the bug

**Comment by breedjaram32** [comment]
Hi,
bug is still in 20.0.3.
Simply `skip OTP for role` in `Conditional OTP Form` doesn't work.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

The alternative approach is to check Conditional flow with the `Conditional role` condition and `OTP Form` authenticator (this might be preferred way as the `Conditional OTP` authenticator was added before we had conditions in the authentication flow).

**Comment by breedjaram32** [comment]
Thank you @mposolda 
I tried use `conditional role` with `OTP forms` like Post login flow and it seem that working it.

_example_
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/77382127/223185510-b9474377-9487-469f-a4c5-0614dd095b24.png">
