### ISSUE TITLE
Keycloak login requires two login attemps to login

### ISSUE THREAD

**Issue by Wetwer** [keycloak/keycloak#15524]
### Area

authentication

### Describe the bug

When login in thru the webinterface on the first attempt the user is not properly authenticated and just put back to the login form.
On the second attempt it allways works.

### Version

jboss/keycloak:10.0.1 or jboss/keycloak:16.1.1 (docker)

### Expected behavior

User should login on the first attempt

### Actual behavior

2 Logins required

### How to Reproduce?

We were unable to reproduce this error. We have multiple instances of this running for diffrent clients on some it works properly on some not...

**Comment by sschu** [comment]
Does the problem still exist in the newest Keycloak version? Fixes will typically only be provided for the latest version.
