### ISSUE TITLE
Custom admin theme not working

### ISSUE THREAD

**Issue by ApoorvSeth** [keycloak/keycloak#15538]
### Area

admin/ui

### Describe the bug

Keycloak customization for admin theme should work after changing logo.
Creating custom theme with resources and theme.properties is working on login page but same changes are not working for admin page. After changing logo for nav bar, UI animation and hamburger menu are changed.

### Version

20.0.1

### Expected behavior

Keycloak customization for admin theme should work after changing logo.

### Actual behavior

UI animation, look and feel changed after changing logo.

### How to Reproduce?

1. Create admin folder under <Custom Theme>
2. Create resources folder with img and css folders taken from theme jar
3. Create theme.properties.
4. Change keycloak logo to another logo under .navbar-title.
5. Refresh changes  and lgo should be changed with all other look and feel to be intact.

### Anything else?

After making changes for logo in navbar. Logo is appearing but below issues are coming:
1. Hamburger logo disappearing.
2. Toggle always on for side menu navigation bar.
3. Toggle button for realm is not working as expected. It should be on click rather it is opening on hover of mouse.
4. Other look and feel also changed.

**Comment by lexcao** [comment]
Are you customizing the old admin console?
If so, the old admin console will end of life from Keycloak 21. 


If not, the new admin UI is not supported customization.

**Comment by ApoorvSeth** [comment]
>

**Comment by lexcao** [comment]
From the 19 version, the default admin UI is the new admin UI.
You can refer to this [doc](https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-19-0-0) to see the difference.

In the new admin UI, it is not supported for admin only. 
Other themes like welcome, login & account would work as before.

**Comment by edewit** [comment]
currently we only support changing the admin ui by either adding a css in the theme.properties and for more / bigger customisation you will need to fork the project.
