### ISSUE TITLE
Quarkus keycloak db-password encryption in keycloak.conf

### ISSUE THREAD

**Issue by senthilkumarsn** [keycloak/keycloak#15548]
### Area

core

### Describe the bug

I am implementing the quarkus keycloak as identity module and one of the requirement is to encryption db-password in the keycloak.conf.

Its security risk to keep the db-password as plaintext.

 is there any custom provider for postgresql db level or quarkus extension available?

I am using windows quarkus keycloak runs as standalone service.

 

Is there any way where we can encrypt in keycloak.conf which decrypts using customer provider? Or built in module supports to do that.

 

Can you help me to understand who initializes the postgresql db connection either by quarkus module or keycloak module?

### Version

19

### Expected behavior

db-password encryption

### Actual behavior

db-password is in plain-text

### How to Reproduce?

refer keycloak db-password

**Comment by senthilkumarsn** [comment]
Quarkus framework provided vault-based encryption and will that work in quarkus?

https://pedrohosilva.wordpress.com/2022/06/23/how-to-encrypt-the-quarkus-file-vault-secret/

**Comment by ajaiswal595** [comment]
> Quarkus framework provided vault-based encryption and will that work in quarkus?
> 
> https://pedrohosilva.wordpress.com/2022/06/23/how-to-encrypt-the-quarkus-file-vault-secret/

@senthilkumarsn 

Is it working for you?

**Comment by vmuzikar** [comment]
Thanks for the report.

Duplicate of https://github.com/keycloak/keycloak/issues/11089

**Comment by pedroigor** [comment]
@ajaiswal595 @senthilkumarsn We should probably leverage https://quarkiverse.github.io/quarkiverse-docs/quarkus-file-vault/dev/index.html.

**Comment by nkuruza** [comment]
Has anyone been able to encrypt the db-password in keycloak.conf?
