### ISSUE TITLE
Issue with PartialImport API - Noticed different behavior between UI and API call #10008

### ISSUE THREAD

**Issue by mtmvivek** [keycloak/keycloak#15554]
### Area

admin/ui

### Describe the bug

I am opening this bug in regards of another bug which was raised by my team mate which I cant re-open, so cloning that issue:
https://github.com/keycloak/keycloak/issues/10008

>> The header mentioned in the resolution is not helping ("Accept: application/json" HTTP Header in postman)

Import the attached test.json file under the keycloak admin UI Partial Import section.
Resource has been created(user in our case) without any error. Please refer to screenshot-1. No error noticed under UI or Keycloak Server Logs
API Call Behavior::

Trigger PartialImport API from postman as displayed in screenshot-2.
Resource has been created under keycloak, refer to screenshot-3
Received 500 Internal server Error as an API response and following error noticed under Keycloak Server Logs

Keycloak Server Log Error(Screenshot-4)::
2021-09-14 04:03:49,455 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-614) Uncaught server error: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: org.keycloak.partialimport.PartialImportResults of media type: application/octet-stream
at [org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final](mailto:org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final)//org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:118)
at org.jboss.resteasy.resteasy-

### Version

11.0.3 and 14.0.0

### Expected behavior

Import successfully

### Actual behavior

Attached error
![152562418-9ec85581-6023-4083-b448-a2aec7a75ed1](https://user-images.githubusercontent.com/1649316/202557384-2b8d8282-d0bf-4fe1-be5e-5122f75422f1.png)
<img width="908" alt="152562422-21512082-fa83-450b-b941-0de53e4a95c5" src="https://user-images.githubusercontent.com/1649316/202557392-2cc0e8f9-c572-4dbe-a13c-bbf49ed3ccae.png">
![152562416-82c21e9b-7efc-4c8c-8f9c-15d98d2f06ab](https://user-images.githubusercontent.com/1649316/202557396-9da8b2ed-3b60-4691-80dd-bf250b433a2f.png)

### How to Reproduce?

UI Behavior::

Import the attached test.json file under the keycloak admin UI Partial Import section.
Resource has been created(user in our case) without any error. Please refer to screenshot-1. No error noticed under UI or Keycloak Server Logs
API Call Behavior::

Trigger PartialImport API from postman as displayed in screenshot-2.
Resource has been created under keycloak, refer to screenshot-3
Received 500 Internal server Error as an API response and following error noticed under Keycloak Server Logs

**Comment by ssilvert** [comment]
It looks like https://github.com/keycloak/keycloak/issues/10008 contained the solution.

Did that solution not work?
And just to be clear, this was a problem using Postman.  It works with the UI, correct?

**Comment by ssilvert** [comment]
I'm going to close this issue.  If you continue to have problems we can reopen.
