### ISSUE TITLE
Windows 11 Could not obtain connection to query metadata in dev mode

### ISSUE THREAD

**Issue by longdog** [keycloak/keycloak#15573]
### Area

core

### Describe the bug

returns error " Could not obtain connection to query metadata: java.sql.SQLException: Acquisition timeout while waiting for new connection" after first run .\bin\kc.bat start-dev 

### Version

20.0.1

### Expected behavior

runs in dev mode without database require

### Actual behavior

crashes with an error 
2022-11-18 18:27:03,246 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2022-11-18 18:27:03,247 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-11-18 18:27:03,247 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Acquisition timeout while waiting for new connection

### How to Reproduce?

download zip and run .\bin\kc.bat start-dev

**Comment by mposolda** [comment]
@longdog Could you please check with latest KEycloak 21 version and confirm if you still see this issue with latest version?

**Comment by longdog** [comment]
same issue with keycloak-21.1.1

**Comment by pdowideit** [comment]
same issue for me

**Comment by ahus1** [comment]
I've tested this with the latest version of Keycloak 22.0.1 on Windows 11.

Using "start-dev" works fine, and I can restart the Keycloak instance OK.

When the database is shut down in development mode unexpectedly, you might need to clean the "data" folder including all subfolders (especially the "h2" folder).

Please let me know if this helps. If the problem persists, provide the full startup log of Keycloak.

**Comment by ahus1** [comment]
Closing this issue as we're missing input from the community
