### ISSUE TITLE
Update QueryParameters

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#15593]
### Description

Redefine `QueryParameters` and related classes so they better fit the future use in services for generic query creation, unblock work in #15345. This work also relates to the tree storage #9742

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
