### ISSUE TITLE
Unable to edit client details on firefox

### ISSUE THREAD

**Issue by jannes-io** [keycloak/keycloak#15594]
### Area

admin/ui

### Describe the bug

When opening any client:

![image](https://user-images.githubusercontent.com/9079379/203032942-820dc933-7bed-4690-9f94-f96f4e13cff5.png)

Console:
![image](https://user-images.githubusercontent.com/9079379/203035949-37771c8e-375a-4735-b563-6b6794446a98.png)

Once the error occurs, a hard refresh must be performed to access any page again (for example, can't navigate back to realms using the menu before doing a full refresh).

### Version

19.0.3

### Expected behavior

Be able to manage clients on firefox

### Actual behavior

Error as seen in the image above

### How to Reproduce?

Open any client details

### Anything else?

Firefox version:
![image](https://user-images.githubusercontent.com/9079379/203033426-9bae2d55-d93f-4546-9264-fceb16e59440.png)

works on other browsers (tested safari).

**Comment by ssilvert** [comment]
@jannes-io I am quite sure this is working on Firefox, so I suspect there is a problem in your environment.  Perhaps upgrade to Keycloak 20 and see what happens?

I'm going to close this now.  If you are still having problems, please open an issue at https://github.com/keycloak/keycloak-ui/issues
