### ISSUE TITLE
Keycloak wrongly assumes that the default datasource is the first one

### ISSUE THREAD

**Issue by mruzicka** [keycloak/keycloak#15608]
### Area

dist/quarkus

### Describe the bug

Keycloak assumes, at least at the following places:
- [org.keycloak.quarkus.deployment.KeycloakProcessor, line 323](/keycloak/keycloak/blob/28fc5b4574ed5c8cc000ae11d5595d91af7f6a70/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L323)
- [org.keycloak.quarkus.deployment.LiquibaseProcessor, line  46](/keycloak/keycloak/blob/28fc5b4574ed5c8cc000ae11d5595d91af7f6a70/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/LiquibaseProcessor.java#L46)

that the first datasource is the _default_ datasource.

While this assumption is correct for the `List<AggregatedDataSourceBuildTimeConfigBuildItem>` as produced by [`io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems()`](/quarkusio/quarkus/blob/a2e7f7e8502b0e730083a301892e5a26251393c7/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L279-L325), it is <ins>wrong</ins> for the `List<JdbcDataSourceBuildItem>` as produced by [`io.quarkus.agroal.deployment.AgroalProcessor.generateDataSourceBeans()`](/quarkusio/quarkus/blob/a2e7f7e8502b0e730083a301892e5a26251393c7/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L229-L277). Notice that this method produces the datasources in the order determined by the iteration order of the `HashMap` returned by [`io.quarkus.agroal.deployment.AgroalProcessor.getDataSourceSupport()`](/quarkusio/quarkus/blob/a2e7f7e8502b0e730083a301892e5a26251393c7/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L179-L193).

This wrong assumption leads to problems, such as those described in issue #14353, under the following circumstances:
- there is an additional datasource defined for Keycloak
- the database kind of the additional datasource is different from the database kind of the default datasource
- the name of the additional datasource happens to come before the name of the default datasource - `<default>` - as determined by the java's `HashMap` iteration order (an example of such a name is `test`; on the other hand, `atest` is OK, as it comes _after_ the `<default>`)

### Version

20.0.1

### Expected behavior

Defining an additional datasource has no negative impact in Keycloak.

### Actual behavior

Keycloak fails to start, reporting errors as described in issue #14353.

### How to Reproduce?

1. define an adittional datasource for Keycloak, for example in `application.properties`, as follows:
    ```properties
    quarkus.datasource.test.db-kind=oracle
    quarkus.datasource.test.jdbc.url=${DB_URL}
    quarkus.datasource.test.username=${DB_USER}
    quarkus.datasource.test.password=${DB_PW}
    ```
2. make sure that:
   * the DB kind of the datasource is different from the DB kind of the Keycloak's default datasrouce
   * the name of the datasource comes before `<default>` as determined by the java's `HashMap` iteration order (`test` does)
3. start Keycloak

### Anything else?

There is a workaround for this problem: Rename the aditional datasource to anything which comes _after_ the `<default>` as determined by the java's `HashMap` (or `HashSet`) iteration order - for example `atest`.

**Comment by pedroigor** [comment]
@mruzicka Thanks for the catch and all the details. The fix is here https://github.com/keycloak/keycloak/pull/15700.

I'm not 100% sure about writing a test as we would need to check for different combinations and spin a test container.

**Comment by mruzicka** [comment]
Hi @pedroigor, thanks for the fix.
And as far as I'm concerned, there is no need for a test for this.
