### ISSUE TITLE
account console ignores hostname-path configuration for some resource files

### ISSUE THREAD

**Issue by Tristan971** [keycloak/keycloak#15600]
### Area

account/ui

### Describe the bug

Some of the /resources-prefixed paths of the account console ignore the hostname-path configuration

### Version

20.0.1

### Expected behavior

I expect the flag `--hostname-path="/auth"` to result in no requests to "/resources/..." and instead only to "/auth/resources/..." when browsing the account console.

I'm aware of the `http-relative-path` parameter, but it's a **build-time** only parameter, which is rather inconvenient, and it being entirely dissociated from `hostname-path` seems like a bug to me.

### Actual behavior

Browsing to `https://$HOSTNAME/auth/realms/$REALM/account/` with --hostname-path="/auth" results in client-side requests to paths like `/resources/hkj3b/common/keycloak/web_modules/@patternfly/patternfly/patternfly-addons.css`

### How to Reproduce?

Using a command-line value like:

```
/opt/keycloak/bin/kc.sh start --optimized [...] --hostname-path="/auth" --hostname-strict=false --proxy="edge"
```

Then browse to the account console of a realm (on your edge proxy domain), for example `https://www.example.com/auth/realms/staff`

**Comment by ssilvert** [comment]
Not a UI bug, so moving to core team.

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .
