### ISSUE TITLE
Display a duplicate user when we use ldap federation

### ISSUE THREAD

**Issue by naitech77** [keycloak/keycloak#15604]
### Area

ldap

### Describe the bug

1 - Configure ldap provider to use federation user (openldap)
    Synchronization settings
       Import users  Off
       Sync Registrations Off
   Batch size 
       Periodic full sync Off
       Periodic changed users sync  Off
2 - When i create the first user in my ldap. the search user in keycloak UI return duplicate user (the same use)  ==> KO
3 - When i create the seconde user in my ldap the search user in keycloak UI return only one (not duplicate) ==> OK

### Version

20.0.1

### Expected behavior

We need get only one result for the first user creation in ldap

### Actual behavior

returned two result for the first user creation in ldap

### How to Reproduce?

1 - Configure ldap provider to use federation user (openldap)
    Synchronization settings
       Import users  Off
       Sync Registrations Off
   Batch size 
       Periodic full sync Off
       Periodic changed users sync  Off
2 - When i create the first user in my ldap. the search user in keycloak UI return duplicate user (the same use)  ==> KO
3 - When i create the seconde user in my ldap the search user in keycloak UI return only one (not duplicate) ==> OK

**Comment by ahus1** [comment]
Triage result: 

I found the situation that `LDAPStorageProvider` will run multiple searches for different keys. When combining the result, it doesn't deduplicate the result, thereby an item that matches the query in multiple ways is returned multiple times.

To reproduce:

* Start Keycloak with LDAP as described above and use the test LDAP setup described in `test.md` 
* Search in the users tab with `*` to return all users -> all users are shown twice

![image](https://user-images.githubusercontent.com/3957921/221830792-b0fd61a9-9287-4ad5-9352-de6500598795.png)
