### ISSUE TITLE
'Verify profile' required action does not continue login flow in SAML

### ISSUE THREAD

**Issue by Heldenkrieger01** [keycloak/keycloak#15629]
### Area

saml

### Describe the bug

When having a User Profile with a required attribute and then activating the VERIFY_USER required action, a user logging in via SAML is correctly presented with the page to update his attribute if it's missing. When clicking on "Update Profile" however, the page reloads and the user cannot login.

### Version

19.0.3

### Expected behavior

The login flow is continued.

### Actual behavior

The user is stuck in an endless reloading loop.

### How to Reproduce?

Activate User Profiles for keycloak and a realm. Add a custom attribute which is required always for users and admins. Do not add the attribute to the user. Activate the required action 'Verify profile'. Login as a user.

**Comment by m1212e** [comment]
How did you fix it?

**Comment by Heldenkrieger01** [comment]
> How did you fix it?

Not at all, chose not to use the feature.
