### ISSUE TITLE
UserInfo: Role name mapper is not respected for user info endpoint

### ISSUE THREAD

**Issue by dweber019** [keycloak/keycloak#15624]
### Area

core

### Describe the bug

When enabling the "Add to userinfo" in the realm roles mapper like this

<img width="371" alt="2022-11-22 14_14_06-RH-SSO Admin Console" src="https://user-images.githubusercontent.com/1021324/203323077-cc0eb5e1-21ec-44ca-a116-1b130d6ada92.png">

The realm roles are added to the user info endpoint as expected.
We then configured a "Role Name Mapper" for certain roles to rename them (we need this for software integration, where certain role names are expected). We did this like this

<img width="340" alt="2022-11-22 14_16_14-RH-SSO Admin Console" src="https://user-images.githubusercontent.com/1021324/203323611-e10d4ae3-a8bd-47e9-b8c6-c4f429af58ca.png">

### Version

9.x.x

### Expected behavior

We should expect that we have a role named "new_role" in the response of the user info endpoint.

### Actual behavior

We have the original role named "old_role".
For access token and id token it works as expected but not for the user info endpoint.

### How to Reproduce?

See description.

### Anything else?

I have tested this bug in version 18.x.x with the same result.
Even when the OIDC spec doesn't define how to represent roles and groups specifically it states that claims have to be returned.
This implies that a claim in a token like (realm_access.roles) should be represented exactly the same in the user info endpoint, I would guess.

https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

**Comment by dweber019** [comment]
The same issue can be found if using the "Hardcoded Role" mapper.

**Comment by dweber019** [comment]
I think as https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/protocol/oidc/mappers/RoleNameMapper.java#L42 only implements `OIDCAccessTokenMapper` but not `UserInfoTokenMapper` this is happening. We have a custom mapper which renames roles based on a regex and when we implement `UserInfoTokenMapper` it works.

**Comment by mposolda** [comment]
Adding to Keycloak 22 for now.

However it is not a blocker and no promise we will be able to fix it. If anyone from the community is willing to send PR for this, it will be welcome. Please reply here in that case that you're looking into this and want to send PR. See https://www.keycloak.org/community for the details.

**Comment by rmartinc** [comment]
@mposolda I checked this in the morning and I took it because it seems to be an easy win. But doing the tests took me some time :smile:. I think it's OK now, I'll send a PR asap.
