### ISSUE TITLE
Allow cookie-based token propagation (single-page application)

### ISSUE THREAD

**Issue by inad9300** [keycloak/keycloak#15622]
The current Keycloak JavaScript adapter returns a token that you have to manually send on the "Authorization" header on every request. To do this, you would typically require remembering that token in a place accessible by JavaScript (e.g. global variables, `sessionStorage`).

Instead, Keycloak could return a `Set-Cookie` header with the token so that the browser would automatically send it in the `Cookie` header in subsequent requests. This would both be more convenient (no manual token propagation needed) and more secure (using HTTP-only cookies would prevent tokens from being accessible by malicious JavaScript, should a cross-site scripting vulnerability occur).

Keycloak already sends a `Set-Cookie` header back with a token. However, it has a `Path=/realms/<realm>/` attribute that prevents the browser from propagating it to other sites, despite being `SameSite=None`. Additionally, the token is different than the one returned by the JavaScript adapter (it uses a different algorithm), which makes it unusable in some (perhaps all) contexts.

In my particular case, I was trying to [configure Eclipse MicroProfile to use cookies](https://download.eclipse.org/microprofile/microprofile-jwt-auth-2.0/microprofile-jwt-auth-spec-2.0.html#_jwt_and_http_headers) (using `mp.jwt.token.header=Cookie` and `mp.jwt.token.cookie=KEYCLOAK_IDENTITY`) when I found the aforementioned Keycloak limitations: the cookie never reached the backend, and when manually changing the cookie's path in the browser so that it does, MicroProfile complained that the token should have been signed with "RS256" instead of "HS256".

**Comment by sschu** [comment]
Is there a standard around this kind of token usage? The current usage is basically OAuth2 standard.

**Comment by inad9300** [comment]
Not that I know of. OAuth2 talks about [three ways to transport bearer tokens](https://www.rfc-editor.org/rfc/rfc6750#section-2), including an insecure, not-recommended one, so it is my interpretation that one should chose the most secure transport method possible, and not just among the three proposed by the standard. These days, everybody seems to lean towards cookies over browser storage (e.g. https://stackoverflow.com/a/65861229/2018219), so at least giving the option so that we can make our own trade-offs seems reasonable.

Additionally, Keycloak is already exposing a token through the `KEYCLOAK_IDENTITY` cookie. I'm not sure which kind of token, though, but if it is a bearer token or equivalent, my intuition is that all that's needed is a couple of configuration options to control the cookie, like its `SameSite`/`Path` attributes, the algorithm used to sign the token, its name...

**Comment by inad9300** [comment]
Being able to authenticate Server-Sent Events end-points is another great reason to switch to cookies, as it is [not possible to add headers to JavaScript's `EventSource()`](https://github.com/whatwg/html/issues/2177), while cookies would work.

**Comment by devlux** [comment]
is perhaps the [CAS protocol](https://unicon.github.io/cas/development/protocol/CAS-Protocol.html) an option for you as there is also a [provider for keycloak](https://github.com/jacekkow/keycloak-protocol-cas)?

I'm currently also considering it but I've no experience yet... ;-)

**Comment by inad9300** [comment]
It's the first time I hear of CAS, but I don't quite see how that would help. I'd much rather stick to a simpler _single_ sign-on solution, which is what Keycloak is supposed to be. I think changing Keycloak in a way that makes it both more secure and usable in ubiquitous web scenarios (like SSE, _and WebSockets_, by the way) is the obvious move here.

**Comment by matthiastz** [comment]
Currently looking into using Keycloak as an Identity/Session Management platform, unfortunately the non-existence of configuring the Cookie Path parameter (SameSite as well?) is completing blocking my use case (Keycloak in Cookie mode). 

@inad9300 the `KEYCLOAK_IDENTITY` is just a simple JWT with `sub` being the userID (I guess) and `session_state` & `sid` both holding the sessionID. You can compare that by decoding that JWT with `KEYCLOAK_SESSION_LEGACY` which just follows <realm>/sub/sid

**Comment by jonkoops** [comment]
I don't think Keycloak JS is the place to solve this. If you want to do something like set a session cookie to protect your endpoints/pages with Keycloak it should be handled with some kind of middleware on the server, such as our [Node.js Adapter](https://github.com/keycloak/keycloak-nodejs-connect) (deprecated but still an example).

On the Java side of things you could use something like [Spring Security](https://www.baeldung.com/spring-boot-keycloak) to protect your routes/APIs.
