### ISSUE TITLE
12.0.4 - Change password required relogin

### ISSUE THREAD

**Issue by Kalithasan-Periyasamy** [keycloak/keycloak#15637]
### Area

account/ui

### Describe the bug

After change password application required relogin

### Version

12.0.4

### Expected behavior

After user changes the password application should logout and redirect to login page

### Actual behavior

Application is not redirecting to login page after change password

### How to Reproduce?

Create user and set temporary password. Login in to application and reset the password.

**Comment by stianst** [comment]
This is expected behaviour, why require user to login again, if you are basically just asking them for the password they entered seconds ago. There's no additional security in doing that, but rather just an annoyance to users.
