### ISSUE TITLE
12.0.4 - Reset password does not require old password

### ISSUE THREAD

**Issue by Kalithasan-Periyasamy** [keycloak/keycloak#15636]
### Area

account/ui

### Describe the bug

When user resetting password while login, it is not asking for old password in password resetting page.

### Version

12.0.4

### Expected behavior

Application should ask for old password and validate while update new password. 

### Actual behavior

Application is not asking old password while user resetting new password while login

### How to Reproduce?

Create a new user and set temporary password. User that user to login into application.

**Comment by stianst** [comment]
This is expected behaviour. User has literally entered the password seconds before.
