### ISSUE TITLE
Logging documentation references non-existing parameter

### ISSUE THREAD

**Issue by sonOfRa** [keycloak/keycloak#15646]
### Description

The documentation for configuring the logging aspects of Keycloak references the non-existing parameter `--log-format`. I used this parameter, expecting it to set the logging format for both the console and the file appenders to the same value.

Instead, Keycloak fails to start because the parameter is invalid.

**Comment by ahus1** [comment]
This has been fixed in the meantime with issue #16179 and PR #16179
