### ISSUE TITLE
Review `set-quarkus-version.sh`

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#15644]
We should review/reconsider the following:
* Use of `mvn versions:revert`.
   * This is sometimes causing issues like e.g. [re-introducing previously removed properties](https://github.com/keycloak/keycloak/pull/15601).
* Updates of dependencies only in `quarkus` module.
   * We should be probably also updating the dependencies in the root POM.

**Comment by pedroigor** [comment]
Yeah, I only created it to remove some steps when preparing for an upgrade/downgrade. But I still need to make sure to look at the Quarkus BOM in their repository to be sure the versions are aligned.
