### ISSUE TITLE
Make Infinispan index data stored in memory to be consistent with cached data

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#15653]
Currently, we store Infinispan index data in storage, while caching data in memory. We should make this consistent, probably by moving index to memory using in cache configuration:
```xml
<indexing storage="local-heap">
```

**Comment by hmlnarik** [comment]
Also add documentation about the need to make store index and data storages consistent (either all data and cache are in memory, or both are configured to be persisted on filesystem).
