### ISSUE TITLE
Can we have FIPS-enabled container image with FIPS-enabled Keycloak?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#15662]
This may be done as follow-up to #16891

**Comment by pedroigor** [comment]
@mposolda Based on what we discussed, a FIPS-enabled container only makes sense when the host also has FIPS enabled.

Looks like whatever we document in terms of server configuration is enough to enable FIPS to a container. In fact, that is one of the main aspects of the distribution: cross-platform experience when configuring the server.

I'm not sure if want to provide an image but just rely on the upcoming  FIPS documentation.

**Comment by mposolda** [comment]
@pedroigor Yes, I think you're right.

Another thing is, that we rely on BCFIPS and we likely cannot provide any container using BCFIPS artifacts. So looks like people will need to have this provided by default. We will just need to document this. So do you agree that we close this?
