### ISSUE TITLE
User Profile: Editing the username attribute adds empty permissions

### ISSUE THREAD

**Issue by chehrhar** [keycloak/keycloak#15668]
### Area

user-profile

### Describe the bug

After editing the username attribute at User Profile > Attributes, the following empty permissions and scopes are added in the JSON-Representation: 

![image](https://user-images.githubusercontent.com/43938163/203771945-e5421652-4d87-400e-8500-6314a39c0dec.png)

With theses permissions the username cannot be updated in the Admin UI, anymore.

### Version

15.0.2

### Expected behavior

Permissions and scopes are not added to the JSON representation, if I only remove the validation.

### Actual behavior

Empty permissions and scopes are added in the JSON-Representation. 
Username cannot be edited in the admin console, anymore.

### How to Reproduce?

- Edit username attribute
- Delete validation username-prohibited-characters
- Save

**Comment by pedroigor** [comment]
Please, try out latest version as this issue can not be reproduced anymore.
