### ISSUE TITLE
Search by group attributes might break on OracleDB 

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#15685]
### Area

storage

### Describe the bug

This is a follow-up on #15639 which fixed this for the Clients. 

The code for Groups looks the same, therefore it is most likely buggy as well. There first needs to be a testcase to reproduce it.

### Version

nightly

### Expected behavior

Test should succeed.

### Actual behavior

Test probably fails, or there is no test for this yet (validation pending).

### How to Reproduce?

Not reproducible with the new Admin UI. Probably only reproducible using the Admin CLI

**Comment by ahus1** [comment]
I found that the tests succeeds, as the column `VALUE` for `GROUP_ATTRIBUTE` is still a NVARCHAR(255). 

Is there a need to change the `VALUE` in `GROUP_ATTRIBUTE` in the legacy datamodel to CLOB? If there is no need to change this to anything longer, this issue can be IMHO closed. 

Pinging @vramik and @sguilhen for their thoughts on this before closing it.

**Comment by vramik** [comment]
@ahus1 I think we there might be a requirement to store longer attribute values than 255 characters. But I'm not sure. Maybe we can get feedback from original contributor of "search groups by attribute" feature. 

@alechenninger could you please comment on this one?

**Comment by alechenninger** [comment]
@vramik I cannot comment on whether Keycloak should support group attributes with greater length than 255 characters. For our use cases, we don't have any attributes of this length, at least for groups. I could see user's potentially having attributes which require longer lengths (e.g. bio).

**Comment by ahus1** [comment]
Thanks for all the feedback.

I decide to close this issue as there is no immediate bug on Oracle due to too long fields. If there would be the need to enlarge them, this code would need to change to handle LOBs on Oracle. Until this is the case, this is fine. :fire:
