### ISSUE TITLE
Spring Boot 3 KeycloakWebSecurityConfigurerAdapter doesn’t work

### ISSUE THREAD

**Issue by SamTV12345** [keycloak/keycloak#15697]
### Area

adapter/spring

### Describe the bug

With yesterday’s update Spring Boot 3 went GA. It removed support for WebsecurityConfigurerAdapter and marked the usage of http.authorizeRequests in configure method as deprecated. Is there already an update on how to use the Spring Boot Keycloak adapter with Spring Boot 3? 

### Version

18.02

### Expected behavior

The application starts. 

### Actual behavior

The application doesn’t start because it cannot find the WebsecurityConfigurerAdapter. 

### How to Reproduce?

Take any Spring Boot project with Keycloak Adapter that extends KeycloakWebSecurityConfigurerAdapter and update spring boot starter parent to version 3.

### Anything else?

[Link to Spring Boot 3 Release](https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0)

**Comment by JamesPeters98** [comment]
I've just tried updating to Spring Boot 3.0.0 and found the same issue too.

Looks like WebSecurityConfigurerAdapter has been removed and replaced with a set of beans to configure security instead:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

**Comment by SamTV12345** [comment]
I created a minimal example [here](https://gitlab.com/samuel1998.schwanzer/minimal-oauth2-client). But it has some limitations:
1. Beans overwrite each other. So when the resource bean is dominating you can only login with postman. When the client is active I get redirected to keycloak but when I access postman I get the keycloak login page as a response.
2. I can't get the client flow to work. So authenticate with loginPage when in browser and authenticate with oauth2 bearer token in postman. 

So examples with keycloak adapter migrating to spring adapter would be very handy.

**Comment by adamzr** [comment]
The other issue is that Keycloak is using `javax` packages and needs to switch to `jakarta`.

**Comment by torsten-liermann** [comment]
> The other issue is that Keycloak is using `javax` packages and needs to switch to `jakarta`.
And other older dependencies like apache http client, rest easy. An update to EE9 and then EE10 is necessary.

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by SamTV12345** [comment]
The question is if you really need Keycloak adapters if the Spring Resource Server/ Spring Client exist. I guess documentation on how to move from the keycloak adapters to the Spring adapters would be better.

**Comment by MHormes** [comment]
I managed to migrate the adapter config to spring boot 3 using this issue:
 https://github.com/keycloak/keycloak/issues/12514#issuecomment-1209109769

**Comment by mhajas** [comment]
Closing as duplicate of #12514
