### ISSUE TITLE
Keycloak authentication brokering cookies blocked on iOS in Canvas iframe

### ISSUE THREAD

**Issue by springroll12** [keycloak/keycloak#15691]
### Area

identity-brokering

### Describe the bug

We have a web application that must be deployed in an iframe (embedded in Salesforce). We use keycloak-js to connect this web application to a keycloak server which performs authentication brokering with an external OIDC IdP. 

This seems to work well in all browsers except on iOS, where Keycloaks' authentication cookies are considered "3rd party" when issued from the iframe domain. We are unsure how to fix this, since there does not seem to be a way to disable Keycloak cookies, even though they are not needed at all for brokering authentication.

See here for details on iOS blocking cookies: https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

This issue seems to imply there is a way to properly disable cookies, but we have not been able to achieve this: https://github.com/keycloak/keycloak/issues/13789

We don't believe the cookies are necessary for brokering applications (minus token refresh), so we are hoping there is a way to do this either through a configuration value or a custom authenticator.

### Version

15.6

### Expected behavior

Keycloak successfully brokers authentication

### Actual behavior

* Authentication fails with "error=cookie_not_found"

We believe this is due to cookies being blocked by iOS.

### How to Reproduce?

Reproduction steps:

1. Create web application using keycloak-js and deploy to domain-x.
3. Embed application in iframe on domain-y.
4. Deploy keycloak server to subdomain of domain-x.
5. Set up keycloak identity brokering to an external Identity Provider
6. Attempt to authenticate in a browser on iOS 13+

### Anything else?

Any help in how to approach this would be greatly appreciated.

**Comment by jonkoops** [comment]
This issue should be resolved in newer versions of Keycloak. If you are still experiencing this issue after upgrading let us know and we will re-open this issue.

**Comment by robwetz** [comment]
> This issue should be resolved in newer versions of Keycloak. If you are still experiencing this issue after upgrading let us know and we will re-open this issue.

Thank you @jonkoops, can you expand on the version info?  I see the issue was reported for version 15.6.  I'm currently running version 16.0.0 and experiencing a similar issue.  Just curious if we need a newer version to resolve the issue.  Thanks!

**Comment by jonkoops** [comment]
I am not sure under which version of Keycloak this was fixed. But it's highly recommended to always use the latest version of Keycloak, as older versions have security vulnerabilities.
