### ISSUE TITLE
Device Flow Login pages' locale change menu doesn't work

### ISSUE THREAD

**Issue by ynojima** [keycloak/keycloak#15717]
### Area

oidc

### Describe the bug

When multiple locales are enabled in Keycloak, locale change menu appears in the each login page.
End users can choose their preferred locale to use, but in the device flow login pages, the menu appears, but it doesn't work.
The menu item issues a request with "kc_locale" query parameter, but not like the LoginActionsService class, the request handlers in the DeviceEndpoint class doens't check the "kc_locale" query parameter.
https://github.com/keycloak/keycloak/blob/20.0.1/services/src/main/java/org/keycloak/protocol/oidc/grants/device/endpoints/DeviceEndpoint.java
https://github.com/keycloak/keycloak/blob/20.0.1/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L277-L279

### Version

Rh-SSO 7.6.0

### Expected behavior

When an end-user clicks the locale change menu item in the Device Flow pages, the locale is changed as specified.

### Actual behavior

When an end-user clicks the locale change menu item in the Device Flow pages, the locale is not changed.

### How to Reproduce?

1. Enable multiple locales from the admin console
2. Set up device flow client from the admin console
3. Initiate the device flow, and navigate your browser to the device flow login page.
4. Change the locale from the menu item in the device flow login page

**Comment by mposolda** [comment]
I am adding to Backlog as I am not sure if Keycloak team will have opportunity to look at this in the near future. Everyone is welcome to investigate and send PR for this. Please take a look at https://www.keycloak.org/community to the "Contributors" section for the details.

I can add that there are more locale related issues like for example https://github.com/keycloak/keycloak/issues/13922, but right now, it seems to me that it is a different cause that this one.
