### ISSUE TITLE
Keycloak won't start due to Unsupported database file version or invalid file header in file "/var/lib/keycloak/data/h2/keycloakdb.mv.db" [90048-214]

### ISSUE THREAD

**Issue by BoBeR182** [keycloak/keycloak#15712]
### Area

core

### Describe the bug

```
2022-11-27 18:25:25,972 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2022-11-27 18:25:25,973 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2022-11-27 18:25:25,973 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unsupported database file version or invalid file header in file "/var/lib/keycloak/data/h2/keycloakdb.mv.db" [90048-214]
2022-11-27 18:25:25,973 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: The write format 1 is smaller than the supported format 2 [2.1.214/5]
2022-11-27 18:25:25,973 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### Version

keycloak 20.0.1-1

### Expected behavior

Keycloak starts

### Actual behavior

Keycloak fails to load the database

### How to Reproduce?

`sudo kc.sh -cf /etc/keycloak/keycloak.conf start`

### Anything else?

Using default Arch Linux config.

**Comment by sschu** [comment]
I cannot reproduce this issue - at least on a fresh Keycloak installation. I assume you have an old H2 DB created with a different Keycloak version and since the H2 version has been updated in between, it does not work anymore with the current version. AFAIK H2 is only for development, not for production use.

**Comment by BoBeR182** [comment]
I fear this might be the case, is there a way to either upgrade the database to be able to start keycloak? or a way to export the data? Looking into migrating to postgreSQL as we speak.

**Comment by BoBeR182** [comment]
Any documentation to best do that without data loss? I can close this issue, unless we need a warning banner, or Keycloak is expected to upgrade the database between versions?

**Comment by sschu** [comment]
I have no experiences with that, but if you google for "export h2 to Postgres" you might find something like https://www.traccar.org/forums/topic/how-i-migrated-h2-database-to-postgresql/.

**Comment by BoBeR182** [comment]
Downgrading and export worked to recover data.

**Comment by lillyqian** [comment]
I see the same error when upgrading from 21.1.1 to 22.0.4. Anyone has a solution to make it work without missing any data?

**Comment by lanmark7** [comment]
Same as lillyqian..  version 23 broke my production environment somehow when it auto upgraded to latest last week.  So I am going back to a dev environment which happens to be on 21.1.4.. when updating it to 22.0 it throws this unsupported database file.

**Comment by sschu** [comment]
H2 really is not meant to be used for production, it can work but there is no guarantee.

**Comment by ashirvadgupta** [comment]
This can be fixed if your h2 database is migrated.

1. First you need to take backup of your db before migration.
_java -cp "../../lib/lib/main/com.h2database.h2-2.1.214.jar" org.h2.tools.Script -url jdbc:h2:./keycloakdb -user sa -password password_
2. Above command will create a file called backup.sql. Copy it somewhere
3. You need to remove keycloakdb.mv.db file from this location.
4. After migration, create a directory data/h2 and place the backup.sql file over there.
5. Run below command to migrate the database to be compatible with new h2 jar.
_java -cp ../../lib/lib/main/com.h2database.h2-2.2.220.jar org.h2.tools.RunScript -url jdbc:h2:./keycloakdb -user sa -password password_
6. Start your Keycloak. It will work fine.
