### ISSUE TITLE
Keycloak 18.0.2 (maybe later versions too) doesn't support importing for LDAP changes

### ISSUE THREAD

**Issue by edwint88** [keycloak/keycloak#15723]
### Area

dist/quarkus

### Describe the bug

Currently we are running the 18.0.2 in docker and give as a flag "--import-realm" that imports the realm for the very first time.
When we try to use "./kc.sh import --file ./realm.json --override true", we see that some changes from the file are applied, but for instance if we have a new IP for our LDAP configuration, that is not changed (override). 
The question is also what else is not updated? 

### Version

18.0.2

### Expected behavior

To override all our changes from the new realm.json file

### Actual behavior

Some of the changes are updated (e.g. new roles, clients, etc.) and some changes are not like the IP from an LDAP user federation.

### How to Reproduce?

1. Install Keycloak
2. Add an LDAP user federation
3. Export Realm
4. Change the settings in the LDAP config
5. Use the import command with the updated json file.

**Comment by pedroigor** [comment]
@edwint88 Could you please try the latest version?

The ldap user federation component is properly created with whatever value you set to `connectionUrl`.
