### ISSUE TITLE
Device Authorization Grant fails with valid S256 code challenge

### ISSUE THREAD

**Issue by asieraguado** [keycloak/keycloak#15739]
### Area

core

### Describe the bug

Device Authorization Grant requests fail under these conditions:

- A public client supports PKCE using S256.
- The URL-safe base64 encoded string contains padding characters `=`, which are optional according to [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648#section-5).

### Version

19.0.3

### Expected behavior

The request works also when the base64 string includes padding characters.

### Actual behavior

The request fails generating this response:

```
{'error': 'invalid_request', 'error_description': 'Invalid parameter: code_challenge'}
```

And the following error message appears in the logs:

```
2022-11-29 11:28:20,660 INFO  [org.keycloak.protocol.oidc.endpoints.AuthorizationEndpointChecker] (executor-thread-2304) PKCE supporting Client with invalid code challenge specified in PKCE, codeChallenge = NVXtCDm7om-TEP8-kZ9qTrghdErwQv7lDJLe89smVZI=
```

### How to Reproduce?

1. Create a public client with OAuth 2.0 Device Authorization Grant Enabled and the default settings.
2. Make a Device Grant request with the `code_challenge` parameter, using the `code_challenge_method` `S256`. The `code_challenge` must be base64-url encoded, and it will fail if it has any `=` characters at the end.

The Python package `base64` includes these padding characters when calling e.g. `base64.urlsafe_b64encode(b"test")`.

Here is a Python script to reproduce this behaviour:

```
import binascii
import os
import base64
import requests
import hashlib

auth_hostname = "test.example.com"
auth_realm = "myrealm"
clientid = "device-code-flow-test"

random_state = binascii.hexlify(os.urandom(8))
# code_verifier: https://www.rfc-editor.org/rfc/rfc7636#section-4.1
# 48*2 = 96 characters, which is within 43-128 limits.
code_verifier = binascii.hexlify(os.urandom(48))

code_challenge = (
    base64.urlsafe_b64encode(hashlib.sha256(code_verifier).digest())
    .decode()
#    .replace('=', '')  # removing equals characters works
)

r = requests.post(
    "https://{}/auth/realms/{}/protocol/openid-connect/auth/device".format(
        auth_hostname, auth_realm
    ),
    data={
        "client_id": clientid,
        "state": random_state,
        "code_challenge_method": "S256",
        "code_challenge": code_challenge
    }
)

if not r.ok:
    print("Device grant request failed!")

print(r.json())
```

### Anything else?

Removing all `=` characters from `code_verifier` works as a temporary workaround.

Adding `=` to [this pattern](https://github.com/keycloak/keycloak/blob/201277b8973d1f6c866e0d6a6604ce2b257894f3/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpointChecker.java#L78) would probably fix the issue.

**Comment by rmartinc** [comment]
@asieraguado I think that PKCE [rfc7636](https://www.rfc-editor.org/rfc/rfc7636) states that the base64 should be without padding. Check [chapter 2 notational conventions](https://www.rfc-editor.org/rfc/rfc7636#section-2):

> BASE64URL-ENCODE(OCTETS) denotes the base64url encoding of OCTETS,
>   per [Appendix A](https://www.rfc-editor.org/rfc/rfc7636#appendix-A), producing a STRING

And in [appendix a](https://www.rfc-editor.org/rfc/rfc7636#appendix-A):

>  This appendix describes how to implement a base64url-encoding
>  function without padding, based upon the standard base64-encoding
>  function that uses padding.

And there in the pseudo-code you see that `=` at the end are removed.

**Comment by asieraguado** [comment]
@rmartinc Thank you for your reply. I think that you are right, the OAuth2 document specifies it's without padding. I will close this issue since Keycloak's behaviour seems to be right.
