### ISSUE TITLE
MULTIVALUED_STRING_TYPE for UserStorageProvider in new Admin UI not visible 

### ISSUE THREAD

**Issue by QuadStingray** [keycloak/keycloak#15743]
### Area

admin/ui

### Describe the bug

I have a individual User Storage Provider implemented with `MULTIVALUED_STRING_TYPE` Settings. In the "old" Admin UI Theme every thing worked fine. In the new UI no values are visible.

### Version

20.0.1

### Expected behavior

In the new UI the values should also be visible.

### Actual behavior

In the new UI no values are visible.

### How to Reproduce?

UserStorageProvider with `MULTIVALUED_STRING_TYPE` Setting

**Comment by QuadStingray** [comment]
<img width="1312" alt="Old UI" src="https://user-images.githubusercontent.com/8616438/204524215-002cf9d0-6ccd-45c4-8fac-5e6da8164190.png">
<img width="1092" alt="New UI" src="https://user-images.githubusercontent.com/8616438/204524226-75faa082-6d8f-49b7-9224-fee5ab2fd3cd.png">

**Comment by QuadStingray** [comment]
btw. what is the right way to define a default value for an `MULTIVALUED_STRING_TYPE` configuration?

My Code:

```
new ProviderConfigProperty(WEBHOOK_URI_HEADER_PROPERTY, "WEBHOOK Header Parameter", "Header Parameter Format 'name::Value'", MULTIVALUED_STRING_TYPE, List.of("hello", "wold"))
```
Produce following bad output:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/8616438/204525369-8e46c43c-1a11-478e-bbc4-f6a4192760ca.png">

**Comment by ssilvert** [comment]
I believe this is fixed in the latest nightly build.  Also see https://github.com/keycloak/keycloak-ui/issues/3743

Can you try the nightly and let us know if it resolves your problem?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
I'm going to close this issue now.  If you still have issues with the latest build we can reopen.
