### ISSUE TITLE
Can't change 'Restart login'

### ISSUE THREAD

**Issue by Xuezenghuigithub** [keycloak/keycloak#15777]
### Area

account/ui

### Describe the bug

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/40421053/204953966-a5e22e8d-5e1c-4f63-ac16-c8ed78290baf.png">

There is no setting for 'Restart login' in the [messages_en.properties](https://github.com/DemocracyOS/keycloak/blob/master/democracyos/login/messages/messages_en.properties).

How to change that text?

### Version

20.0.1

### Expected behavior

Have a property for this text.

### Actual behavior

Don't have this property.

### How to Reproduce?

Use base or keycloak theme.

### Anything else?

nop

**Comment by lexcao** [comment]
Hi, @Xuezenghuigithub 
What version of Keycloak are you using?
I think the link you provided with the message properties might be out of date.

I found there is a key of `restartLoginTooltip` for this in the latest version of Keycloak.

https://github.com/keycloak/keycloak/blob/b7d72687442be3c5ba0f6fcc04b1c2c9e2b13e36/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L115

**Comment by Xuezenghuigithub** [comment]
Thanks a lot!
