### ISSUE TITLE
"Failed to add user 'admin' ..." should not be an ERROR

### ISSUE THREAD

**Issue by ChristianCiach** [keycloak/keycloak#15789]
### Area

dist/quarkus

### Describe the bug

When using the environment variables `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` keycloak logs this on startup:

```
ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
```

In other words: This error always appears except for the very first startup of keycloak. When deploying to kubernetes, there is no way to set these environment variables only for the first deployment.

We forward all `ERROR` logs to our 24/7, so this is annoying. I fail to see why this expected situation should be logged as an "error".

### Version

20.0.1

### Expected behavior

Should be logged as an INFO.

### Actual behavior

Log-Level is ERROR.

### How to Reproduce?

Start a keycloak-container that uses the environment variables `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` while using a persistent data storage. Then stop and restart the container.

**Comment by kkapper** [comment]
Is there any chance we could get these commits merged into a minor version of v21.x? Kubernetes based deployments of Keycloak are guaranteed to restart eventually, and will never stabilize lacking this change.

I can't speak for everyone but I imagine this is holding up every Kubernetes deployment of this application.

**Comment by vmuzikar** [comment]
@kkapper We do not plan backporting this to 21.1.z as it was just a minor improvement (change in a log level). We're backporting only critical bug fixes. This issue should not cause any deployment issues. Could you please elaborate a bit more on the problems with K8s deployment you are facing? Thank you.

**Comment by dalbani** [comment]
I'm in the same situation as OP: the logging being done at the `ERROR` level, it ends up being caught by our monitoring system (Sentry in this case) each team a Keycloak pod is (re)started.
