### ISSUE TITLE
Unexpect user's attribute merge with concurrent invocation of REST API

### ISSUE THREAD

**Issue by sasori-developer** [keycloak/keycloak#15788]
### Area

admin/api

### Describe the bug

Performing concurrent invocation of REST API for user update, leads to unexpected behaviors, the user's attributes will be merged and result in a multivalued attribute.

### Version

15.0.2

### Expected behavior

The last invocation should be the one that is persisted.

### Actual behavior

The user attribute will be duplicated and merged into a multivalued attribute.

### How to Reproduce?

It can be easily reproduced with a command line curl invocation:

```
seq 1 2 | xargs -n1 -P2 curl --location --request PUT 'http://localhost/auth/admin/realms/myapp/users/<user-id>' \
--header 'Authorization: Bearer <bearer_token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "<user-id>",
    "createdTimestamp": 1669818851439,
    "username": "user1",
    "enabled": true,
    "totp": false,
    "emailVerified": false,
    "attributes": {
        "custom_attr": [
            "attr-value"
        ]
    },
    "disableableCredentialTypes": [],
    "requiredActions": [],
    "notBefore": 0,
    "access": {
        "manageGroupMembership": true,
        "view": true,
        "mapRoles": true,
        "impersonate": true,
        "manage": true
    }
}'
```

This will create on Keycloak an attribute identified by key **_custom_attr_** and value **_attr-value##attr-value_**
NOTE: repleace **_\<user-id>_** and **_<bearer_token>_** with valid values

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by sasori-developer** [comment]
Thank you for reaching out regarding the bug I reported earlier. I understand your request to upgrade to the latest version of Keycloak to verify if the issue persists. Unfortunately, due to time constraints, I am unable to perform this upgrade at the moment.

However, I'd like to address the situation at hand. It seems that there has been a prolonged period since the bug was initially reported, and despite requests for verification, there hasn't been much progress. Considering the detailed nature of the initial report and the passage of over a year without resolution, it's evident that the urgency to address the issue has diminished.

Furthermore, our project has transitioned to alternative solutions that do not depend on Keycloak's functionalities. Consequently, although I appreciate the efforts made to address the reported bug, its resolution is no longer critical to the operation of our software.

Thank you for your understanding and assistance throughout this process.

Best regards,
Simone

**Comment by pedroigor** [comment]
@sasori-developer Thanks and sorry for the delay. The issue can not be reproduced using your reproducer and it should be working fine in the latest version.

We had some changes in this area recently with the introduction of the declarative user profile.
