### ISSUE TITLE
Not able to make a user as a realm admin

### ISSUE THREAD

**Issue by RKVodde** [keycloak/keycloak#15795]
### Area

admin/ui

### Describe the bug

created a new realm and a new user and wanted to make that user the realm admin but cannot assign manage-realm role mapping to the user.

### Version

20.0.1

### Expected behavior

should allow to assign manage-realm role to the user

### Actual behavior

except admin & create-realm I am not seeing other roles that can be assigned to user in role mappings

### How to Reproduce?

started a new setup with docker keycloak 20.0.1 and after creating a new user and a new realm trying to assign realm admin using mange-realm role mapping but the said role is not there in the list.

**Comment by sschu** [comment]
This role is a client role and belongs to the realm-management client. It is not a realm role.

**Comment by ssilvert** [comment]
@sschu is correct.  If you need help beyond the documentation, you can ask questions in https://www.keycloak.org/community.

**Comment by RKVodde** [comment]
apologies, figured it out, my mistake.
