### ISSUE TITLE
fix typo in kcWebAuthnKeyIcon

### ISSUE THREAD

**Issue by punkratz312** [keycloak/keycloak#15807]
### Area

account/api

### Describe the bug

plz fix typo in kcWebAuthnKeyIcon

<img width="782" alt="image" src="https://user-images.githubusercontent.com/8830888/205261820-884146ff-5923-4f89-9b48-02c6a84da888.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/8830888/205261792-f7dbb83b-1ea5-4a1b-b79b-9d743cae7b15.png">

### Version

current

### Expected behavior

kcWebAuthKeyIcon

### Actual behavior

kcWebAuthnKeyIcon

### How to Reproduce?

look into file 

https://git.autonomic.zone/ruangrupa/login.lumbung.space/commit/57eeabe1348fe03574005ed213c587966f503408?style=unified&whitespace=show-all

https://cgit.gentoo.org/sites/sso/tyrian-keycloak-theme.git/plain/login/webauthn-register.ftl

### Anything else?

thanks

**Comment by punkratz312** [comment]
Hello thanks for your response @lexcao.
maybe not in your opinion, but in the opinion of the best and most common professional ide IntelliJ and therefore not in the most common opinion, in my humble opinion, so maybe go with the flow instead of trying to invent a new wheel. Thanks for considering. Have a nice beautiful new week.

**Comment by sschu** [comment]
AuthN and AuthZ are equally commonly used terms, see for example https://www.cloudflare.com/en-gb/learning/access-management/authn-vs-authz/
So I would also assume the usage is intended here.
