### ISSUE TITLE
Usage of CookieTokenStore hinders CSRF validation with Spring Security

### ISSUE THREAD

**Issue by OLibutzki** [keycloak/keycloak#15828]
### Area

adapter/spring

### Describe the bug

I develop a Spring Boot application which configures the Keycloak adapter to use a Cookie based token store for storing the token issued by Keycloak. I use Spring Security 5.8.0.

Unfortunately, this leads to the problem that `org.springframework.security.web.session.SessionManagementFilter` detects that the user has been authenticated during the current request. This leads to a call to `org.springframework.security.web.csrf.CsrfAuthenticationStrategy.onAuthentication(Authentication, HttpServletRequest, HttpServletResponse)` resulting in a new csrf token.

As there are csrf tokens generated multiple times they become out of sync. In the end the token sent by the client is not the one the server expects.

Then not using the Cookie token store but saving the token issued by Keycloak in the HTTP session the `SessionManagementFilter` does not detect a new authentication and does not generate a new csrf token.

### Version

20.0.1

### Expected behavior

When the user authenticates using a auth token stores in a cookie, the csrf token should not be regenerated.

In the end the behavious should be the same, regardless of using auth token connected to the HTTP session or sending it via a cookie.

### Actual behavior

The csrf token is regenerated on every request.

### How to Reproduce?

Run a Spring Boot application which uses csrf protection with Spring Security.

Configure the KEycloak adapter to store the token in a cookie:
`keycloak.token-store=cookie`

Login in using Keycloak and try to perform a POST request. The csrf protection kicks in and a 403 ist returned.

### Anything else?

There seems to be a workaroung by setting `NullAuthenticatedSessionStrategy` as the `sessionAuthenticationStrategy` at `org.springframework.security.config.annotation.web.configurers.CsrfConfigurer`.

I am not sure whether this is a Keycloak adapter or a Spring Security adapter.

If you think there should be a Spring Security issue, please let me know.

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
