### ISSUE TITLE
JPA Map Storage: Add transaction retry logic to LoginActionsService.authenticate

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#15849]
### Area

storage

### Describe the bug

Execution of performance tests for the new storage revealed that concurrent invocations of the `LoginActionsService` endpoint to authenticate users (path `/realms/{realm}/login-actions/authenticate`) occasionally leads to `RETRY_SERIALIZABLE` failures on CockroachDB.

We must employ the same logic used in `AuthorizationEndpoint` and `TokenEndpoint` to handle concurrent requests by running the code in a retriable transaction.

### Version

20.0.1

### Expected behavior

Concurrent execution of `LoginActionsService.authenticate` should finish with no transaction retry errors

### Actual behavior

Concurrent invocation of the `LoginActionsService.authenticate` endpoint lead to the `RETRY_SERIALIZABLE` errors on CockroachDB

### How to Reproduce?

Run the login performance tests on CRDB

**Comment by ahus1** [comment]
Adding to "Anything else?": This starts to fail only after ~20.000 entries exist in `kc_single_use_obj`.

**Comment by hmlnarik** [comment]
Dependency for https://github.com/keycloak/keycloak-benchmark/issues/203
