### ISSUE TITLE
Keycloak contains EOL Log4j version

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#15844]
### Area

dependencies

### Describe the bug

Keycloak contains log4j 1.2.17 as reported by one of scan which is EOL. This needs an upgrade in the version in the upcoming releases. This dependency is present in the main pom.xml under keycloak/pom.xml.

### Version

19.0.3

### Expected behavior

Log4j version needs to be upgraded with the latest version.

### Actual behavior

NA

### How to Reproduce?

the dependency is visible in main pom.xml.

**Comment by mvk37** [comment]
Logj4 1.2.17 is still present in Keycloak **21.0.1**. Scanner found it in org.jboss.logmanager.log4j-jboss-logmanager-1.3.0.Final.jar.

Could you upgrade it to log4j2, please?

**Comment by mabartos** [comment]
AFAIK, Log4j 1.2.17 dependency is used only as a test dependency and doesn't impact the functionality of Keycloak. Unfortunately, we don't have the capacity to take care of this, but PR with valid changes is more than welcome :)

**Comment by ahus1** [comment]
I've created a PR #20423 that shows an idea, let's see if that is worth pursuing.
