### ISSUE TITLE
Move `UserSessionCrossDCManager` to legacy module

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#15855]
This class https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java is relevant only for the legacy store, we should move it to the legacy module.

**Comment by martin-kanis** [comment]
Moving `UserSessionCrossDCManager` to legacy module creates a cyclical dependency between `keycloak-services` <--> `keycloak-model-legacy-services` and `keycloak-ldap-federation` <--> `keycloak-model-legacy-services`.
Removing `keycloak-services` and `keycloak-ldap-federation` dependencies from `keycloak-model-legacy-services`  seems to be a large refactoring. 
Another option is to move methods from `UserSessionCrossDCManager` to `UserSessionManager` and remove `UserSessionCrossDCManager`. There are only methods that call `getUserSessionWithPredicate`. Nothing which is strictly related to crossDC. @mhajas WDYT?

**Comment by mhajas** [comment]
@martin-kanis Sure methods unrelated to CrossDC can be moved to `UserSessionManager`.

This was created because of these two lines:
https://github.com/keycloak/keycloak/blob/d1ab921c50ad1ffe3a8d1970fae3abab2668a619/services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java#L87-L89

It was causing some issues with pessimistic locking for HotRod storage because it loads one session twice.

**Comment by martin-kanis** [comment]
No longer relevant after removal of map store. Closing
