### ISSUE TITLE
Incorrect Signature algorithms presented by Client Authenticator

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#15853]
### Area

oidc

## Issue:

Presented signature algorithms for clients using client Client authenticator being "Signed JWT" or "Signed JWT with client Secret" are not correct

### Signed JWT client 

Doc states

```
Signed JWT is "Signed Json Web Token".

When choosing this credential type you will have to also generate a private key and certificate for the client in the tab Keys. The private key will be used to sign the JWT, while the certificate is used by the server to verify the signature.
```

Keycloak behaviour

1. Go to credentials
2. Select client authenticator "Signed Jwt"
3. Go to Signature algorithm

The proposed list of signature algorithm iss:
```
ES256
ES384
ES512
HS256
HS384
HS512
PS256
PS384
PS512
RS256
RS384
RS512
```

Client has his private key registered within a keystore. It means that asymmetric key algorithm are needs to be used.

The value HS256 HS384 HS512 are applying to HMAC which is a a symmetric algorithm. 

The client needs to use a asymmetric algorithm.

It is providing more confusion than anything else, and those values should be removed.

 

The list of proposed algorithms should be 
```
ES256
ES384
ES512
PS384
PS512
RS256
RS384
RS512
```

#### Signed JWT with client secret

The doc states

```
If you select this option, you can use a JWT signed by client secret instead of the private key.

The client secret will be used to sign the JWT by the client.
```

Keycloak behaviour:

1. Go to credentials
2. Select client authenticator "Signed Jwt with client credentials"
3. Go to Signature algorithm

The proposed list of signature algorithm proposes:
```
ES256
ES384
ES512
HS256
HS384
HS512
PS256
PS384
PS512
RS256
RS384
RS512
```

Here we are dealing with symmetric key encryption, where is no Keystore.

Even more, there is reference within the doc, or corresponding client authenticator panel to any JWKS URL.

Also the OIDC specification explicitly mention the HMAC based algorithm in the section for `client_secret_jwt` : https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

Therefore the proposed list should only contains the symmetric algorithm: 
```
HS256
HS384
HS512
```

### Version

20.0.0

**Comment by pedroigor** [comment]
@mposolda Do we want to include this one in 22?

**Comment by mposolda** [comment]
@pedroigor I don't strictly see a blocker, but will be nice and is easy to do. So keeping it in 22. At least for now.
