### ISSUE TITLE
TOTP codes can be submitted multiple times on Chrome

### ISSUE THREAD

**Issue by svenseeberg** [keycloak/keycloak#15854]
### Area

authentication

### Describe the bug

On Chromium based Browsers during login the submit button for the TOTP method can be triggered multiple times. This results in a message that the user is already logged in.

### Version

20.0.1

### Expected behavior

The submit button should be disabled after the first submit on Chrome.

### Actual behavior

The submit button can be triggered multiple times.

### How to Reproduce?

1. Use Chromium
1. Set up an account with authenticator app
1. Log in and use TOTP / authenticator app as 2nd factor
1. Enter the code and hit submit multiple times until the page refreshes

### Anything else?

Works on Firefox.

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now.


Same/similar issue was already fixed for the regular "username/login" page: https://github.com/keycloak/keycloak/pull/4614 . So hopefully something similar can be applied to all other pages? It can be nice if it is doable in some "generic" way (EG. have some "freemarker tag" like `kcSubmitButton` or something, which will do this and then all templates will be able to use this tag).

**Comment by vplemyannik** [comment]
@mposolda it seems to me that easiest way to fix it - add js function to template.ftl

```js
<script>
    function preventDoubleClick(e){
        e.target.disabled = true;
    }
    const submitButtons = document.querySelectorAll('input[type="submit"]');
    for (var i = 0; i < submitButtons.length; i++) {
        const submitButton = submitButtons[i];
        submitButton.addEventListener("click", preventDoubleClick)
    }
</script>
```

this function will prevent from double clicking on each page for each submit button. So there is no need to modify each page.
What do you think ?
