### ISSUE TITLE
Upload Script error

### ISSUE THREAD

**Issue by dpoerschke** [keycloak/keycloak#15869]
### Area

account/api

### Describe the bug

I used the export function on my KeyCloak 17 installation and tried to import the json into KeyCloak 20.0.1 when creating a realm:
![image](https://user-images.githubusercontent.com/48479502/205934227-10716ac5-510f-4243-838f-6566bb4e01be.png)

After clicking an "Create" a error message "unknown server errror" is displayed. On the console the following error is shown:

> [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-4) Uncaught server error: java.lang.RuntimeException: Script upload is disabled

In the past it was possible to use 
> ./kc.sh build --features=upload-scripts

to add this feature, but upload-scripts was already deprecated and is now no longer available. Executing the build command results in:
> ./kc.sh build --features=upload-scripts
Invalid value for option '--features': upload-scripts. Expected values are: authorization, account2, account-api, admin-fine-grained-authz, admin-api, admin, admin2, docker, impersonation, openshift-integration, scripts, token-exchange, web-authn, client-policies, ciba, map-storage, par, declarative-user-profile, dynamic-scopes, client-secret-rotation, step-up-authentication, recovery-codes, update-email, js-adapter, preview
Try 'kc.sh build --help' for more information on the available options.

This is confusing - why is the option "Resource file" displayed when it is not possible to use the import?
If I am not mistaken, the error message should be updated since it is no longer possible to use this feature and the option to import a resource file should not be displayed.

### Version

20.0.1

### Expected behavior

It should be possible to import a realm.

### Actual behavior

Import failes, the error message makes you think, that the feature upload-script is still available.

### How to Reproduce?

In KeyCloak 17.x export a realm. In Keycloak 20.0.1 click on "create realm" and import the previously created exported file.

**Comment by lexcao** [comment]
Yes, the `upload-scripts` feature is removed from Keycloak 18.
You can refer to this [upgrading doc](https://www.keycloak.org/docs/latest/upgrading/#removal-of-the-code-upload-scripts-code-feature)

Could you please check if the realm you want to import contains scripts?
Then try to upload again without these scripts in KC20.

**Comment by dpoerschke** [comment]
Thanks for your help - I have replaced the contained passwords, private Keys and certificates with placeholders and renamed the file extension from json to txt because it is not possible to upload files with json-extension here:
[my-dashboard-export.txt](https://github.com/keycloak/keycloak/files/10174628/my-dashboard-export.txt)

**Comment by lexcao** [comment]
Hi, I just found this `js` policy
```
{
  "id" : "24e5d835-a6c2-415a-9639-f912f36b890c",
  "name" : "Default Policy",
  "description" : "A policy that grants access only for users within this realm",
  "type" : "js",
  "logic" : "POSITIVE",
  "decisionStrategy" : "AFFIRMATIVE",
  "config" : {
    "code" : "// by default, grants any permission associated with this policy\n$evaluation.grant();\n"
  }
}
```

Then I have successfully imported this after remove above JSON.

Be careful, you should remove the usage of `Default Policy` as well.

**Comment by dpoerschke** [comment]
Thanks a lot @lexcao that worked perfectly!
