### ISSUE TITLE
After changing URL, admin console load old URL

### ISSUE THREAD

**Issue by momoirodouhu** [keycloak/keycloak#15886]
### Area

admin/ui

### Describe the bug

I changed "hostname-url" in config and build again.
I can access keycloak via new URL.
But admin page load `/realms/master/protocol/openid-connect/3p-cookies/step1.html` which is old URL

I already trashed cookie and restart nginx proxy.

### Version

keycloak 19.0.2

### Expected behavior

Admin console is opened correctly

### Actual behavior

The page continue loading

### How to Reproduce?

Install Keycloak and setup.
Change the URL to access Keycloak.

**Comment by lexcao** [comment]
Could you please try the latest version of Keycloak?

**Comment by momoirodouhu** [comment]
It was solved by updating to `20.0.1`

Thank you
