### ISSUE TITLE
use kcLocale as users locale once kcLocale is set in UI.

### ISSUE THREAD

**Issue by kanguran** [keycloak/keycloak#15893]
### Area

oidc

### Describe the bug

Switching locales from one to another sometimes does not work out.
LocaleUtil.java is new class added this year to Keycloak
@mposolda could check this bugfix and advice which tests should be added
@vilmosnagy could tell me if he faces similar issues.

```
public class LocaleUtil {

    public static void processLocaleParam(KeycloakSession session, RealmModel realm, AuthenticationSessionModel authSession) {
        if (authSession != null && realm.isInternationalizationEnabled()) {
            String kcLocale = session.getContext().getUri().getQueryParameters().getFirst(LocaleSelectorProvider.KC_LOCALE_PARAM);
            String locale = session.getContext().resolveLocale(null).getLanguage();

            // If KC Locale is set use kc locale as session current locale
            if (kcLocale != null) {
                locale = kcLocale;
            }

            if (locale != null) {
                authSession.setAuthNote(LocaleSelectorProvider.USER_REQUEST_LOCALE, locale);

                LocaleUpdaterProvider localeUpdater = session.getProvider(LocaleUpdaterProvider.class);
                localeUpdater.updateLocaleCookie(locale);
                // update users locale after user locale cookie update aswell.
                localeUpdater.updateUsersLocale(authSession.getAuthenticatedUser(), locale);
            }
        }
    }
}
```

### Version

20.0.1

### Expected behavior

if user changes locale the Page is displayed with in new locale.
If new user uses existing email to identify himself, locale is kept as user selected it.

### Actual behavior

Switching locales from one to another sometimes does not work. Page stays in previous locale.
If new user uses existing email to identify himself, locale is reset to English

### How to Reproduce?

- Start a local KeyCloak instance. Configure at least 2 locale-s in your instance.
- use Keycloak plugin and custom themes.
1) user removes his allowance to service usage or performs other complex operations and changes locale then.  User locale must change to users selected new locale.
2) provide existing email address for new user registration. Registration opens in English language, not in user selected locale.

**Comment by vilmosnagy** [comment]
> @vilmosnagy could tell me if he faces similar issues.

The only thing we've seen around locale & OIDC is that the locale passed in the `ui_locales` query parameter was lost, but that was fixed in #10444.

**Comment by kanguran** [comment]
Yes, that was Great fix, but we need more fixes.

**Comment by mposolda** [comment]
@douglaspalmer Assigning to you to triage as it seems this is related to other issues you are working on?

**Comment by mposolda** [comment]
@kanguran Can you please add some more concrete scenario with exact steps to reproduce? For example see the description of https://issues.redhat.com/browse/KEYCLOAK-18846 of how the scenarios may look like. Is it some of the scenarios, which you have in mind or something different?

**Comment by mposolda** [comment]
Duplicates #13922
It has same cause. So I am closing this. Everyone seeing this, please reply to that issue for the details.
