### ISSUE TITLE
Failed to compile from source code

### ISSUE THREAD

**Issue by cod-soap** [keycloak/keycloak#15906]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

1.clone the latest code from github(20.0.1)

2. try the flowing code build:

mvn clean install -Poperator -DskipTests

mvn clean install -Pdistribution -DskipTests

also I add this in my maven settings:
```
<mirrors>
  <mirror>
    <id>jboss-public-repository-group-https</id>
    <mirrorOf>jboss-public-repository-group</mirrorOf>
    <name>Jboss public https</name>
    <url>https://repository.jboss.org/nexus/content/groups/public/</url>
  </mirror>
</mirrors>
```

### Version

20.0.1

### Expected behavior

build success

### Actual behavior

errors ocurred because there was lack of some classes :

![image](https://user-images.githubusercontent.com/25627194/206407954-5e6dfc60-4299-482e-8a6f-64c0025a919d.png)

### How to Reproduce?

see in Describe

mvn -version：
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: D:\devTools\apache-maven-3.8.6
Java version: 19.0.1, vendor: Oracle Corporation, runtime: *******
Default locale: zh_CN, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by sschu** [comment]
You are using Java 19. The latest supported version is Java 17.

**Comment by cod-soap** [comment]
> You are using Java 19. The latest supported version is Java 17.

@sschu  Thanks for your answer, I changed my java version to java 17,

![image](https://user-images.githubusercontent.com/25627194/206606572-1ed82d67-d437-4931-8624-86a277333a6f.png)

When I build again, the same error occurs:
![image](https://user-images.githubusercontent.com/25627194/206609411-4a8428c3-5b96-4d2c-bf7a-03b688e53aa3.png)

**Comment by cod-soap** [comment]
The error msg such as missing a class :MapResourceEntityImpl

I also not found this class in keycloak git repo.
Is there any other mechanism to load these classes?

**Comment by cod-soap** [comment]
Another try to use jdk in version 11 also failed with the same error occurs:
![image](https://user-images.githubusercontent.com/25627194/206633611-dee7c7fe-e301-4291-bff3-207810c43afc.png)



runtime info:
![image](https://user-images.githubusercontent.com/25627194/206633722-ee418847-0051-41f6-b4b5-269b5302c79c.png)

**Comment by sschu** [comment]
I typically build with `mvn clean install -DskipTestsuite -DskipExamples -DskipTests` and it works without problems. I would assume it is something in your environment. I just cannot try to reproduce it as I am not running Windows.
