### ISSUE TITLE
Hostname debug tool

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#15910]
* Port the [hostname debug tool](https://github.com/stianst/playground/tree/main/kc-ext/hostname-debug) to Keycloak
* Make it disabled by default and enabled via `hostname-debug=true` option
   * This should be added to the Keycloak CR as well
* Add a mention about it to [Hostname Guide](https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/hostname.adoc)

**Comment by Nefcanto** [comment]
My recommendation is that you guys also add **parameter validation** too.

**Comment by buti1021** [comment]
> * Port the [hostname debug tool](https://github.com/stianst/playground/tree/main/kc-ext/hostname-debug) to Keycloak
> * Make it disabled by default and enabled via `hostname-debug=true` option
>   
>   * This should be added to the Keycloak CR as well
> * Add a mention about it to [Hostname Guide](https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/hostname.adoc)

Current URL of the Guide
https://github.com/keycloak/keycloak/blob/main/docs/guides/server/hostname.adoc
