### ISSUE TITLE
Java 17 support not given

### ISSUE THREAD

**Issue by HJK181** [keycloak/keycloak#15916]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Unable to add a custom protocol mapper build with Java 17 event though the [release notes](https://www.keycloak.org/2022/11/keycloak-2000-released.html) clearly states this is possible. Checking the [docker image](https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile#L26) shows the mismatch.

### Version

20.0.1

### Expected behavior

The custom protocol mapper gets loaded.

### Actual behavior

Keycloak crashes on startup with
```
ERROR: Build failure: Build failed due to errors
        [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.lang.UnsupportedClassVersionError: io/searchhub/keycloak/mapper/SearchhubTenantMapper has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

### How to Reproduce?

Create a custom protocol mapper with java 17 and place the jar file in the providers directory.

**Comment by arahlf** [comment]
Sorry if slightly off topic, but any ideas when this fix will be available in a release?

**Comment by pedroigor** [comment]
@arahlf Very soon https://github.com/keycloak/keycloak/pull/16014 :)
