### ISSUE TITLE
Keycloak.X Container should not default to user 1000

### ISSUE THREAD

**Issue by djessich** [keycloak/keycloak#15936]
### Description

When Keycloak.X Container is deployed on Kubernetes, it is required to run the container with user 1000. This is the case because of directive `USER 1000` declared in Dockerfile. Security best practices cannot be fully applied to the running container.

It should be allowed that the user ID is to be specified during deployment on Kubernetes using
```
securityContext:
  runAsUser: 60568
  runAsGroup: 60568
  fsGroup: 60568
```

This ensures, that the container does NOT interfere with users already defined on worker nodes. Therefore the current requirement (running with user 1000) is an implicit security leak (!), in case user 1000 exists on the worker node. Unfortunately user 1000 always exists on most linux systems, as this is the user ID of the user created during installation of most linux OS.

### Motivation

Secure deployment on Kubernetes.
Also relevant for Docker Swarm, Docker Compose and others.

### Details

Remove the user requirement for the Keycloak.X container.

**Comment by awoimbee** [comment]
> it is required to run the container with user 1000.
> [...]
> It should be allowed that the user ID is to be specified during deployment on Kubernetes using [...]

This is false, `USER 1000` is a default value, that can be overwritten by `securityContext`.

So the issue becomes:
- Should keycloakx default to user `XXXX` instead of `1000`:
    Please provide a meaningful suggestion.
- Should keycloak operator allow customizing `securityContext`:
    No idea, I personaly use https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx, which allows me to customize `securityContext`.

The Dockerfile in question:
https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile

**Comment by djessich** [comment]
Ok, then I misunderstood the `USER` directive. I'm very sorry for that.

I gave it a try now, still got a permission denied error. After inspecting the Dockerfile, I would argue that the permission denied error comes from the chown made in the Dockerfile.

Here:
https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile#L23
https://github.com/keycloak/keycloak/blob/main/quarkus/container/Dockerfile#L28

Could that be the problem?

I also use the `keycloakx` Helm chart, with the following security context:
```
securityContext:
  runAsUser: 60568
  runAsGroup: 60568
  fsGroup: 60568
```

**Comment by sschu** [comment]
Yup, user 1000 will be the owner of the Keycloak files, no matter if it actually exists. Other users won't have access (unless they are not in group root). I also don't have a quick idea how to change this, the files must have an owner after all...

**Comment by djessich** [comment]
@sschu Maybe its possible to use the `PUID` environment variable (or similar if available)?

**Comment by sschu** [comment]
The thing is that the file permissions are set at image build time while the security context is set at runtime.

**Comment by sobelfall** [comment]
I'am interest to know what will be the next for this issue

**Comment by sschu** [comment]
I had a quick look at https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids and as I understood it, it should be possible to also run the Keycloak container with a different UID as long as the GID is 0. Openshift is using random UIDs per default and Keycloak does run in Openshift so I assume this should work. AFAIK, GID 0 doesn't have any special privileges at Kernel level so this should already be quite helpful from a security perspective.

**Comment by sschu** [comment]
@djessich In my opinion, it should be fine to always run the container with group ID 0 - this way you can let it run with any user ID. The alternative would be to change file permissions to allow access by any user/group which I would not see as a security improvement. I will go ahead and close this issue - if you still see a problem and have ideas how to solve it, just reopen it.
