### ISSUE TITLE
Add Arabic translations

### ISSUE THREAD

**Issue by Eng-Fouad** [keycloak/keycloak#15933]
### Description

I want to participate in Arabic translations. Which files should be translated?

**Comment by SamTV12345** [comment]
I think these are the most important files:
- themes/src/main/resources/theme/base/admin/messages/messages_en.properties
- themes/src/main/resources/theme/base/email/messages/messages_en.properties
- themes/src/main/resources/theme/base/login/messages/messages_en.properties
- themes/src/main/resources/theme/base/account/messages/messages_en.properties
- themes/src/main/resources/theme/base/admin/messages/admin-messages_en.properties

**Comment by jonkoops** [comment]
Note that if you'd like to provide translations we also have the [Admin UI](https://github.com/keycloak/keycloak-ui/tree/main/apps/admin-ui/public/resources) that would need some.

**Comment by Eng-Fouad** [comment]
The remaining messages to be translated is at keycloak-ui repo: https://github.com/keycloak/keycloak-ui/issues/4397
