### ISSUE TITLE
can not logout from IDP with expired session and the error missing parameter id_token_hint is displayed

### ISSUE THREAD

**Issue by Abdelghani-Ben** [keycloak/keycloak#15945]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

My environment is:

- Keycloak version 20.0.1 as broker 
- Keycloak version 18.0.2 as identity provider
- A react web app as client for my keycloak broker by using keycloak.js adapter

Authenticate successfully to the web app by using a user from IDP and wait for idp session to expire in our case it’s 2 mins after that call broker logout the error missing id_token_hint will be displayed.
   
The id_token_hint is messed because of an error occurred at the preparation for this logout, to be exact it’s refresh_token call made by the broker to idp with the refreshToken returned at the login but never updated after getIDTokenForLogout.

` 
```
 @Override
    public Response keycloakInitiatedBrowserLogout(KeycloakSession session, UserSessionModel userSession, UriInfo uriInfo, RealmModel realm) {
        if (getConfig().getLogoutUrl() == null || getConfig().getLogoutUrl().trim().equals("")) return null;
        String idToken = getIDTokenForLogout(session, userSession);
        if (idToken != null && getConfig().isBackchannelSupported()) {
            backchannelLogout(userSession, idToken);
            return null;
        } else {
            String sessionId = userSession.getId();
            UriBuilder logoutUri = UriBuilder.fromUri(getConfig().getLogoutUrl())
                    .queryParam("state", sessionId);
            if (idToken != null) logoutUri.queryParam("id_token_hint", idToken);
            String redirect = RealmsResource.brokerUrl(uriInfo)
                    .path(IdentityBrokerService.class, "getEndpoint")
                    .path(OIDCEndpoint.class, "logoutResponse")
                    .build(realm.getName(), getConfig().getAlias()).toString();
            logoutUri.queryParam("post_logout_redirect_uri", redirect);
            Response response = Response.status(302).location(logoutUri.build()).build();
            return response;
        }
    }
```
`

### Version

20.0.1

### Expected behavior

When preparing the Idp logout url by the broker if the refreshToken is not possible due to expired session we need to ignore the redirection to keycloak IDP but only end the broker internal session or make sure that the refreshToken has always the same expiration date as the Idp session

### Actual behavior

the missing parameters is displayed instead of the idp logout page:
![image](https://user-images.githubusercontent.com/61970424/206932754-6328bfc9-32ac-4414-b534-d6406813300a.png)

### How to Reproduce?

The web app is a public client to a realm in keycloak broker with a Browser authentication flow modified to use my IDP as default:
![image](https://user-images.githubusercontent.com/61970424/206932614-17f8dfe5-a616-46f6-83a8-16a22b5e5b25.png)
My identity provider configuration:
![image](https://user-images.githubusercontent.com/61970424/206932633-2d2e8ce6-b3c4-4143-b0dd-e4c3587d66c6.png)
the keycloak IDP is configured with my broker as client :
![image](https://user-images.githubusercontent.com/61970424/206932652-eb30f319-29b8-48f5-8b31-63cd9a511c57.png)
![image](https://user-images.githubusercontent.com/61970424/206932656-be731d6f-ed24-47cb-a73f-69f0d32155d6.png)
And the configuration of the realm tokens with 2mins for the SOS session and 1 min for access token to make test faster:
![image](https://user-images.githubusercontent.com/61970424/206932666-c3a1a15f-e73b-46cf-afb4-445c1cf41949.png)

### Anything else?

The same function is used when the refreshToken is still valid to prepare the idp logout url and after that the logout page is displayed as expected but if the user chose to go back to the application without completing the logout an inconsistence situation will be made between the idp session extended by the call “getIDTokenForLogout(session, userSession);” but return result is not stored in the broker completely as you see in the code only the idToken is used as id_token_hint but the new refreshToken with the new expiration time and accessToken are note used at all this situation will be the origin of the same error when the used request the logout again because the getIDTokenForLogout will use the older refreshToken still attached to the session instead of the new one -> invalid token error

**Comment by mposolda** [comment]
duplicates #10164
So closing this. Please use that other issue for further comments/suggestions/questions regarding this.
