### ISSUE TITLE
export client saml key JKS from realm ui admin theme keycloakv2 give invalid JKS

### ISSUE THREAD

**Issue by ttedev** [keycloak/keycloak#15952]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When Export a key client saml JKS  from the admin console with theme keycloakv2 the JKS is invalid. invalid mean keytool can not read JKS. 

### Version

20.0.1

### Expected behavior

The JKS exported should be readable from keytool for instance

### Actual behavior

The JKS exported in realm adim ui theme keycloak v2 could not be read form keytool

### How to Reproduce?

1. lunch a keycloak in local : `podman run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.1 start-dev`
2. create a saml client in master realm => key => export JKS 
3. try to read with keytool : ` keytool.exe -keystore keystore.jks -list` => get `erreur keytool : java.security.KeyStoreException: Unrecognized keystore format. Please load it with a specified type`
4. change admin them in realm configuration to keycloack 
5. export jks and try to read it => ok 

### Anything else?

in admin theme v2 the api call to get the file in not the same that in theme keycloak : 

in v1:
![image](https://user-images.githubusercontent.com/38693787/207025673-4b04d914-93d5-4d21-8b2b-95973955fb25.png)
POST Request /admin/realms/test/clients/<id>/certificates/saml.signing/download
{
  "keyAlias": "dd",
  "realmAlias": "test",
  "realmCertificate": true,
  "format": "JKS",
  "keyPassword": "test",
  "storePassword": "test"
}

in v2:
![image](https://user-images.githubusercontent.com/38693787/207025195-fea1008c-3591-4661-98ee-58ebe309c762.png)
POST Request /admin/realms/test/clients/<id>/certificates/saml.signing/download
{
  "keyAlias": "dd",
  "keyPassword": "test",
  "realmAlias": "test",
  "storePassword": "test",
  "format": "JKS"
}

**Comment by ssilvert** [comment]
@ttedev This may be fixed already.  Can you try it out on the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ttedev** [comment]
@ssilvert I just test on nightly build is it ok thank you !
