### ISSUE TITLE
20.0.2 SSL error with mssql

### ISSUE THREAD

**Issue by keycloakrules420** [keycloak/keycloak#15994]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

With KC 20.0.2 SSL seems to be enabled by default with mssql
(With Keycloak 19 this is not needed)
manually trusting the certificate doesn't work when starting kc with --optimized (without it does)
`KC_DB_URL_PROPERTIES="trustServerCertificate=true;"`

### Version

20.0.2

### Expected behavior

The JDBC URL property works as configured

### Actual behavior

KC throws this error:
keycloak1  | 2022-12-14 10:23:37,950 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:4b2290e5-25ec-4783-80e4-9c2ad0a6590e
keycloak1  | 2022-12-14 10:23:37,952 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:4b2290e5-25ec-4783-80e4-9c2ad0a6590e
keycloak1  |    at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3806)
keycloak1  |    at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1906)
keycloak1  |    at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3329)
keycloak1  |    at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
keycloak1  |    at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
keycloak1  |    at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
keycloak1  |    at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
keycloak1  |    at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
keycloak1  |    at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
keycloak1  |    at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
keycloak1  |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak1  |    at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
keycloak1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
keycloak1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak1  |    at java.base/java.lang.Thread.run(Thread.java:829)
keycloak1  | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
keycloak1  |    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
keycloak1  |    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
keycloak1  |    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
keycloak1  |    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
keycloak1  |    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
keycloak1  |    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
keycloak1  |    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
keycloak1  |    at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
keycloak1  |    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
keycloak1  |    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
keycloak1  |    at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
keycloak1  |    at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
keycloak1  |    at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
keycloak1  |    at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
keycloak1  |    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
keycloak1  |    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
keycloak1  |    at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1795)
keycloak1  |    ... 13 more
keycloak1  | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
keycloak1  |    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
keycloak1  |    at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
keycloak1  |    at java.base/sun.security.validator.Validator.validate(Validator.java:264)
keycloak1  |    at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
keycloak1  |    at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:233)
keycloak1  |    at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110)
keycloak1  |    at com.microsoft.sqlserver.jdbc.HostNameOverrideX509TrustManager.checkServerTrusted(SQLServerTrustManager.java:86)
keycloak1  |    at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1549)
keycloak1  |    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
keycloak1  |    ... 25 more
keycloak1  | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
keycloak1  |    at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
keycloak1  |    at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
keycloak1  |    at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
keycloak1  |    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
keycloak1  |    ... 33 more
keycloak1  | 

### How to Reproduce?

Connect with KC 20.0.2 to an MSSQL db (tested with 2019) without SSL configured
I've attached my compose & dockerfile I used for testing
[kc22.0.2.zip](https://github.com/keycloak/keycloak/files/10226500/kc22.0.2.zip)

**Comment by hmlnarik** [comment]
There seems a change related to quarkus upgrades. Could you please triage accordingly?

**Comment by stefanodemartini** [comment]
Same problem upgrading from 19.0.2

**Comment by martaisty** [comment]
I've experienced the same issue. Having spent some time on the investigation, my assumption of the root of the problem is: new MS SQL JDBC driver, which has some breaking changes - `;encrypted=true` in connection url by default.

**In details:**
- From Keycloak `19.0.2` to `20.0.2` Quarkus version was bumped from `2.7.6` to `2.13.3`
- Quarkus BOM [2.7.6](https://repo1.maven.org/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom) has `7.2.2.jre8` version  of mssql-jdbc driver. And Quarkus BOM [2.13.3](https://repo1.maven.org/maven2/io/quarkus/quarkus-bom/2.13.3.Final/quarkus-bom-2.13.3.Final.pom) has `mssql-jdbc:11.2.0.jre11`
- Breaking change: [mssql-jdbc:10.2](https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?source=recommendations&view=sql-server-ver15#changes-in-102) "Default encrypt to true". More details about encryption support by mssql jdbc [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-ssl-support?view=sql-server-ver15#remarks)

**Possible solutions:**

- Either revert encryption settings by setting `;encrypt=false` property in connection URL
- Or configure certificate on MS SQL Server and add it to keycloak's truststore
- Or use `;trustServerCertificate=true` property in connection URL.
 
P.S.: If you opt for the last option, be aware that unless you configure custom certificate on MS SQL server, encryption makes little to no sense. It will contain `SSL_Self_Signed_Fallback`, which is unsecure.

Hope, my answer helped 😉

**Comment by martaisty** [comment]
> manually trusting the certificate doesn't work when starting kc with --optimized (without it does)
> `KC_DB_URL_PROPERTIES="trustServerCertificate=true;"`

Pay attention that you have specified semicolon after the property but it should go before `KC_DB_URL_PROPERTIES=";trustServerCertificate=true"`

**Comment by keycloakrules420** [comment]
> > manually trusting the certificate doesn't work when starting kc with --optimized (without it does)
> > `KC_DB_URL_PROPERTIES="trustServerCertificate=true;"`
> 
> Pay attention that you have specified semicolon after the property but it should go before `KC_DB_URL_PROPERTIES=";trustServerCertificate=true"`

@martaisty thank you 
it was indeed a problem with the semicolon. 
It is working as expected now
