### ISSUE TITLE
Is there a Changelog?

### ISSUE THREAD

**Issue by mmrvelj** [keycloak/keycloak#16022]
### Description

Currently using version 20.0.1, and I see that 20.0.2 is released. 

I am having problems to find a Changelog or similar document in order to understand what has been changed in 20.0.2 release. 

Release Notes is link to major version documentation, which does say it supports 20.0.2. I do appreciate that you can easily understand difference between major versions of KC, but it is not possible to understand what is the difference between micro releases.  

Is there a way to figure this out somehow?

**Comment by cjohnson-ironiq** [comment]
Are you looking for [this article](https://www.keycloak.org/2022/12/keycloak-2002-released)? (In the [blogs](https://www.keycloak.org/blog) on the main website)

Or something more specific?
