### ISSUE TITLE
Flaky test: Base IT(4) CookiesPathTest.testOldCookieWithWrongPath

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#16026]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

https://github.com/keycloak/keycloak/actions/runs/3707517764/jobs/6284172083

### Version

999-SNAPSHOT

### Expected behavior

Test always pass

### Actual behavior

Test fails randomly

### How to Reproduce?

See test failures for more information:

* https://github.com/keycloak/keycloak/actions/runs/3707517764/jobs/6284172083
* https://github.com/keycloak/keycloak/actions/runs/3707517764/jobs/6284733053

**Comment by stianst** [comment]
This has also failed once in scheduled jobs recently. Haven't seen it before, and the test hasn't changed, so wondering if this could be some regression?

```
From 2022-12-10 to 2022-12-16
============================================================================================================================================
Finding details for CookiesPathTest.testOldCookieWithWrongPath
============================================================================================================================================
https://github.com/keycloak/keycloak/actions/runs/3707534454

Base IT (4)	Run base tests	2022-12-15T20:36:59.3370077Z -- [ERROR]   CookiesPathTest.testOldCookieWithWrongPath:184 
--------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by pedroigor** [comment]
More investigation is needed. Shall we prioritize it?

**Comment by stianst** [comment]
Closing as duplicate of https://github.com/keycloak/keycloak/issues/16132
