### ISSUE TITLE
Migration guide incomplete. New admin

### ISSUE THREAD

**Issue by PJaroslaw** [keycloak/keycloak#16033]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

When reading migration guide I see that one can disable the new console by adding `--features-disabled=admin2` but adding only this setting disables the whole admin console, and not only the admin2 console. After some manual experimentation, I discovered that I have to also add `features=admin`

### Version

20.0.2

### Expected behavior

Be able to access the old admin console

### Actual behavior

Not able to access the admin console at all

### How to Reproduce?

Add `--features-disabled=admin2` to the startup command

### Anything else?

This is a documentation "bug" and not a code bug

**Comment by pniederlag** [comment]
confirmed, ran into this as well

**Comment by jsorah** [comment]
Hi, thanks for the report. 

There won't be any updates to the KC 20 migration guide as we are now on KC 21. Additionally, with the context that you're doing this to enable the old admin console - the only option in KC 21 is the new admin console.

See [this note](https://www.keycloak.org/docs/latest/upgrading/index.html#custom-themes-using-old-admin-console-won-t-work) in the 21.0.0 migration guide for more information.
