### ISSUE TITLE
Core Error? Getting error in new admin when opening tokens

### ISSUE THREAD

**Issue by PJaroslaw** [keycloak/keycloak#16032]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I try to go to tokens tab for any realm I get an error `Danger alert:Cannot read properties of undefined (reading 'options')` and cannot continue further.

### Version

20.0.2

### Expected behavior

Go to the tokens tab and be able to check/edit tokens settings for the realm

### Actual behavior

Getting an error `Danger alert:Cannot read properties of undefined (reading 'options')` and not being able to continue

### How to Reproduce?

Go to any realm e.g. `master` go to `Realm settings` then go to `Tokens` tab

**Comment by ssilvert** [comment]
I'm not seeing this on my end.  Can you try it on the latest build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by PJaroslaw** [comment]
> I'm not seeing this on my end. Can you try it on the latest build?
> 
> https://github.com/keycloak/keycloak/releases/tag/nightly

Lates build of 20.0.2?

**Comment by ssilvert** [comment]
I was referring to the nightly build.  Can you try it out?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by PJaroslaw** [comment]
How can I add this `nightly` build to my maven project?

**Comment by ssilvert** [comment]
@PJaroslaw I'm not sure how to set that up in your environment.

20.0.3 should be out soon.  Maybe you can retry with that version?

**Comment by ssilvert** [comment]
I'm going to close this now.  If you can provide more information on how to reproduce then we can reopen.
