### ISSUE TITLE
NPE while trying to access the list of users in the admin console

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#16047]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

After spinning up a container image with our nightly build from last night, I'm unable to see the list of existing users due to a NPE.

### Version

>= 20.0.2

### Expected behavior

See the list of existing users

### Actual behavior

Error message `v.map is not a function`

![](https://i.ibb.co/M8qJrg3/Screenshot-from-2022-12-16-15-46-39.png)

### How to Reproduce?

- podman run --name keycloak-exp -p 8180:8180/tcp -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -it quay.io/keycloak/keycloak:nightly start-dev --http-port 8180
- Log in to the admin console
- Click in the users' section

### Anything else?

- Bug confirmed on the nightly build from Dec 15.
- Stacktrace: https://gist.github.com/abstractj/c305a18922e722a7bcd9f86f39af9787

**Comment by ssilvert** [comment]
@abstractj Have you tried this with a more recent build?  Have you tried it without podman?

**Comment by abstractj** [comment]
@ssilvert indeed the issues is not happening building the latest version of Quarkus distribution locally.

@keycloak/cloud-native-team, could you please triage this issue, and check if the issue happens when running our container images?

**Comment by pedroigor** [comment]
@abstractj Works for me when executing the steps to reproduce the issue.
