### ISSUE TITLE
External to Internal Token exchange fails with Null pointer Exception if the user is not yet registered (first time token exchange)

### ISSUE THREAD

**Issue by Conosci** [keycloak/keycloak#16059]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

Trying to exchange an External to Internal Token for a user that is not yet registered, a Null Pointer Exception is raised, the REST api returns 'unknown_error'. 
In my case I'm testing it with the Linkedin Identity Provider.
I've already debugged it and the issue is in the class **DefaultTokenExchangeProvider.java** where the business logic tries to define the username and saving it in **context.setModelUsername**:
`            String username = context.getModelUsername();
            if (username == null) {
                if (this.realm.isRegistrationEmailAsUsername() && !Validation.isBlank(context.getEmail())) {
                    username = context.getEmail();
                } else if (context.getUsername() == null) {
                    username = context.getIdpConfig().getAlias() + "." + context.getId();
                } else {
                    username = context.getUsername();
                }
            }
            username = username.trim();
            context.setModelUsername(username);`

after this the user is saved using another property that is **context.getUsername** that is null:

`            federatedIdentityModel = new FederatedIdentityModel(context.getIdpConfig().getAlias(), context.getId(),
                    context.getUsername(), context.getToken());
            session.users().addFederatedIdentity(realm, user, federatedIdentityModel);`

once the logic reached the persistent layer, it throws a null pointer exception in this part (**JpaUserProvider.java**):
`    @Override
    public void addFederatedIdentity(RealmModel realm, UserModel user, FederatedIdentityModel identity) {
        FederatedIdentityEntity entity = new FederatedIdentityEntity();
        entity.setRealmId(realm.getId());
        entity.setIdentityProvider(identity.getIdentityProvider());
        entity.setUserId(identity.getUserId());
        **entity.setUserName(identity.getUserName().toLowerCase());**
        entity.setToken(identity.getToken());
        UserEntity userEntity = em.getReference(UserEntity.class, user.getId());
        entity.setUser(userEntity);
        em.persist(entity);
        em.flush();
    }`

### Version

20.0.2

### Expected behavior

The user is registered and saved into keycloak database.

### Actual behavior

the REST api **/realms/{realm}/protocol/openid-connect/token** returns 'unknown_error'

### How to Reproduce?

Get a token from Linkedin Account for a user that has never logged in.
Try to exchange the External Token to the Internal Token using the api:

POST **/realms/{realm}/protocol/openid-connect/token** with parameters:
client_id
grant_type=urn:ietf:params:oauth:grant-type:token-exchange
subject_token={external token}
subject_issuer=linkedin
subject_token_type=urn:ietf:params:oauth:token-type:access_token

### Anything else?

SUGGESTED FIX
change 576/577 lines of **DefaultTokenExchangeProvider.java** using the evaluated ModelUsername instead of the untouched Username attribute:

`            federatedIdentityModel = new FederatedIdentityModel(context.getIdpConfig().getAlias(), context.getId(),
                    **context.getModelUsername()**, context.getToken());`

**Comment by sschu** [comment]
Not sure token exchange should actually work for a user that is not registered before. The registration process typically ensures things like existence of certain attributes that would not be there without. Also self-registration would have to be enabled in the first place. But surely there shouldn't be a 500.

**Comment by Conosci** [comment]
Dear @sschu, from the implementation I can see the behaviour is to Import the user if it doens't exists. I believe it makes sense, also to allow automatic registration via token exchange once the token has been taken from a keycloak external procedure (IE. mobile native app).
The issue is that, as described, the username (modelUsername attribute) is evaluated with some logic but at the end is not used, it tries to save a property that was never set (username attribute).
Using the keycloak social web flow instead, the logic is a little bit different so the values are properly handled and the new user is correctly imported with full details. I created also another issue  #16061 because the logic of web social login and token exchange should share the same 'user import' behavior in my opinion, both giving the same final result.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
