### ISSUE TITLE
`FieldsGenerator` doesn't generate `getMapKeyClass()` and `getMapValueClass()` for `Map<String, String> config` fields

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16053]
https://github.com/keycloak/keycloak/blob/3c7e5c8440a0f4cede2a341c9edcafb0dbbb6e7c/model/build-processor/src/main/java/org/keycloak/models/map/processor/GenerateEntityImplementationsProcessor.java#L175
```java
FieldAccessorType.getMethod(FieldAccessorType.MAP_ADD, methods, fieldName, types, fieldType).isPresent()
``` 
returns `false` in case the field is e.g. config with type `Map<String, String>` 

https://github.com/keycloak/keycloak/blob/3c7e5c8440a0f4cede2a341c9edcafb0dbbb6e7c/model/build-processor/src/main/java/org/keycloak/models/map/processor/FieldAccessorType.java#L82

here `method.getParameters().get(0).asType()` returns `java.util.Map<java.lang.String,java.lang.String>`

**Comment by amentee** [comment]
Please assign this issue to me
