### ISSUE TITLE
Cannot checkout 18.0.2 tag

### ISSUE THREAD

**Issue by janbols** [keycloak/keycloak#16065]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

I want to checkout tag 18.0.2 from github in order to debug the specific version.

I can go to releases and find the commit related to tag 18.0.2. However, github already warns me that the commit cannot be reached from anywhere in the repo:

`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

See screenshot

![image](https://user-images.githubusercontent.com/1818153/208381813-c9ec0acf-bb4a-46eb-888b-1758810780d9.png)

### Version

18.0.2

### Expected behavior

The commit and tag are part of the github repo and I can checkout the specific version to debug it.

### Actual behavior

The commit and tag are not part of the github repo. As a result I cannot check out this commit.

### How to Reproduce?

Go to the releases pase in github. Select release 18.0.2. Click on the corresponding commit.

**Comment by awoimbee** [comment]
Have you even tried ?
Github is only saying that the commit 'Set version to 18.0.2' is not on a branch, this is not an issue. 

```
➜  work cd /dev/shm
➜  shm gcl https://github.com/keycloak/keycloak.git
Cloning into 'keycloak'...
remote: Enumerating objects: 569183, done.
remote: Total 569183 (delta 0), reused 0 (delta 0), pack-reused 569183
Receiving objects: 100% (569183/569183), 186.06 MiB | 14.64 MiB/s, done.
Resolving deltas: 100% (243239/243239), done.
➜  shm cd keycloak
➜  keycloak git:(main) git checkout 18.0.2
Note: switching to '18.0.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 1c598aa13d Set version to 18.0.2
➜  keycloak git:(18.0.2)
```

**Comment by janbols** [comment]
hmm, yes, thank you for your answer. 

Indeed, I have tried.

```
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
❯ git checkout 18.0.2
error: pathspec '18.0.2' did not match any file(s) known to git
❯ git tag --list | grep 18
```

Kind regards
Jan

**Comment by ahus1** [comment]
The warning you see are technically correct: the tags don't belong to any branch in the repository, as the release branch has been deleted. 

To check out the version, proceed as follows (which I have just tried): 

```
git clone https://github.com/keycloak/keycloak
git checkout 18.0.2
``` 
which responds with: 

> HEAD is now at 1c598aa13d Set version to 18.0.2

If you have an existing repository, it might help to fetch the tags first from the upstream repo, like:

```
git fetch origin  --tags
```

**Comment by janbols** [comment]
Ok, thank you, that was helpful `git fetch origin  --tags` did the trick for me.
