### ISSUE TITLE
Keycloak admin page is not loading

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#16099]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Hey Keycloak Team,
I am trying to install keycloak operator using [keycloak-k8s-resources](https://github.com/keycloak/keycloak-k8s-resources/tree/20.0.2/kubernetes). Keycloak Operator and keycloak installation is successful., but when i tried to access the dashboard am getting this issue
![keycloak20error](https://user-images.githubusercontent.com/48629246/208655458-0cc20f83-b6b9-4703-9e31-a691aab1a98a.jpg)

Using k3d to create cluster.
No errors in wither pod or operator.
No logs related to this error.
 

### Version

20.0.2

### Expected behavior

should able to redirect to the keycloak login page

### Actual behavior

should able to redirect to the keycloak login page

### How to Reproduce?

Fallowed this approach to install the [operator and keycloak](https://www.keycloak.org/operator/installation)

**Comment by pedroigor** [comment]
@rakeshreddyrg09 Please, make sure to access the server using the frontend URL. In your case, it is the URL used to query the `step1.html` page.
