### ISSUE TITLE
Client secret not provided in request

### ISSUE THREAD

**Issue by ukbecemuz1996** [keycloak/keycloak#16124]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

Hi,
I have a problem with JavaScript Adaptor keycloak-js.
When I using the standard flow with these options:
`{
  "realm": "joblinkshub",
  "auth-server-url": "https://idm.openvine.io/auth/",
  "ssl-required": "external",
  "resource": "joblinkshub",
  "credentials": {
    "secret-jwt": {
      "secret": "-----------"
    }
  },
  "confidential-port": 0
}` 

and after a successful redirection is done to my redirect_uri ,the Adaptor doesn\`t send Basic Authorization Header to the token_endpoint, Because of that the token_endpoint return me this error:
`{
    "error": "unauthorized_client",
    "error_description": "Client secret not provided in request"
}`

### Version

20.0.2

### Expected behavior

When Using standard flow and after get a successful code from the authorization server , we should send basic authorization header to the token_endpoint and after that the token_endpoint will return us the access_token and refresh_token .

### Actual behavior

In the actual behavior there is no authorization sent by adaptor

### How to Reproduce?

By send basic authorization header in the request to token_endpoint

**Comment by sschu** [comment]
I think "secret-jwt" is the wrong type of credentials.

**Comment by ukbecemuz1996** [comment]
> I guess "secret-jwt" is the wrong type of credentials. I think it should just be "secret".

it`s the same when credentials is "secret"

**Comment by stianst** [comment]
keycloak.js is designed for client-side applications, which are "public" clients and can not securely store secrets. As such keycloak.js simply doesn't support being used with a non-public client.

You should switch the client to not require authentication, and rely on correct redirect-uris.
