### ISSUE TITLE
Support for reCAPTCHA Enterprise at user registration

### ISSUE THREAD

**Issue by atifc** [keycloak/keycloak#16138]
### Description

This feature would add support for reCAPTCHA Enterprise at user registration.

### Motivation

Current implementation is using outdated reCAPTCHA which Google no longer supports.

**Comment by Roriz** [comment]
up

**Comment by derlin** [comment]
Yes, please!

**Comment by jonkoops** [comment]
When up-voting a topic please use a :+1: on the original post, and refrain from leaving comments that do not add value to the discussion itself.

**Comment by NafeezBaba** [comment]
Hi, I am new to contributing for open source. I would like to work on this issue, if no one is assigned for this. Can someone please assign this issue to me? Thanks

**Comment by derlin** [comment]
Hello! I am currently working on it an have a very good starting point. Still working on the ftl though

**Comment by derlin** [comment]
@jonkoops can you assign it to me?

**Comment by jonkoops** [comment]
Sure, I will assign this to you since you already have some work ready @derlin.
