### ISSUE TITLE
Delegated Administration w/ Fine-Grained-Authz: UI issues/inconsistencies

### ISSUE THREAD

**Issue by dosera** [keycloak/keycloak#16160]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/fine-grained-permissions

### Describe the bug

Hi everyone,

I am trying to realize delegated administration with  keycloak's ADMIN_FINE_GRAINED_AUTHZ feature.
So far so good, yet there are two things that are not working as intended as far as I can tell:

1. The delegated admin is unable to see the "Add User" button in the User list
2. The delegated admin can see groups that he is not member of (or not admin of)

### Version

20.0.2

### Expected behavior

The create user button is visible and only groups that are manageable are shown in the UI.

### Actual behavior

Create User button is *not* shown and all groups *are* shown.

### How to Reproduce?

The setup I used to (re)produce this issue:

    Keycloak 20.0.2, ADMIN_FINE_GRAINED_AUTHZ enabled

#### Groups

    t1
    t1-a

    t2
    t2-a

#### Users

    user1-t1     [member of: t1]
    user2-t1     [member of: t1]
    admin1-t1    [member of: t1-a]

    user1-t2     [member of: t2]
    admin1-t2    [member of: t2-a]

#### Realm Roles:

    t1
    t1-a with [associated roles]
            - t1
            - realm-management: query-groups
            - realm-management: query-users

    (similar for t2-* respectively)

**_Fine Grained Permissions are enabled on the _groups_ t1 and t2 as follows:_**

    Scope

    manage-members - with a group policy containing the t1-a group

    view-members - with a group policy containing the t1-a group

    (similar for t2 group respectively)

For the mentioned issues:

**1.** While the delegated administrator "admin1-t1" is unable to see the "Add user" button it is capable of navigating there via the direct URL:

http://localhost:8080/admin/delegated/console/#/delegated/users/add-user

![kc-no-add-user-button](https://user-images.githubusercontent.com/10059422/209159885-903ffc2a-f621-4afb-87ee-64658db8769e.png)

It can also successfully create a user via this UI - but only iff the user that he creates is EXACTLY assigned to the "t1" group.
Assigning NO GROUP results in a "Could not create user: unknown_error" as does assigning "t1-a" or "t2" or "t2-a" (he should not even see the last two - but see issue #2 for that) or a combination of these.

![kc-create-user-can-see-all-groups](https://user-images.githubusercontent.com/10059422/209160009-28b56371-fe99-401f-9ef4-d21976454495.png)

![kc-add-user-in-other-admin-group-could-not-should-not](https://user-images.githubusercontent.com/10059422/209159967-56e00b87-57ef-4dca-8c52-9e826863c901.png)

**2.** The delegated administrator "admin1-t1" can see *all* groups in the Groups menu on the left hand side, meaning

    t1            [he can administrate this]
    t1-a          [he is member of this]

    t2            [he has no relation to this whatsoever]
    t2-a          [he has no relation to this whatsoever]

![kc-useradmin1-can-see-all-groups](https://user-images.githubusercontent.com/10059422/209160096-e19d9d70-c6d0-4f19-ba69-bf199fa3cf59.png)

### Anything else?

1. I found https://github.com/keycloak/keycloak/pull/7429 which - as far as I can tell - should exactly address the problem with the missing button. The code on the `release/20.0` branch seems to be matching as well:

```
<div class="pull-right" data-ng-show="(access.manageUsers || (serverInfo.featureEnabled('ADMIN_FINE_GRAINED_AUTHZ') && access.queryUsers))">
```

- but one of the conditions must be false for some unclear (to me) reason.

2. I debugged and found `org.keycloak.services.resources.admin.permissions.GroupPermissions.getAccess(GroupModel)` where a map is returned containing exactly what I would have expected, namely

for the group `t1`
```
{view=true, manage=true, manageMembership=true}
```

for the group `t1-a`
```
{view=false, manage=false, manageMembership=false}
```

(same for t2-* respectively)

yet the data is still shown in the UI.

**Comment by dosera** [comment]
I just realized that there is the "old" UI. After switching to this the `Add user` (and `Unlock users`) button appears.

**Comment by dosera** [comment]
> This may be already fixed. We did make a fix to the "Create User" button not showing up.
> 
> Can you give the nightly build a try and let us know what you find? https://github.com/keycloak/keycloak/releases/tag/nightly

After trying with `21.0.2` I can confirm that the `Create user` (as well as the `Delete user`) button are now visible as expected.

Wrt. the topic of groups being visible although a delegated admin is not assigned to them:

> You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue. 
> If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue 
> If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

This issue is still applicable in the latest version (`21.0.2`)

**Comment by jonkoops** [comment]
@dosera is this issue still present in the nightly version as well?

**Comment by dosera** [comment]
> @dosera is this issue still present in the nightly version as well?

yes; I used `999.0.0-SNAPSHOT` via `quay.io/keycloak/keycloak:nightly `aka `46ed4b062b89`

**Comment by daanh432** [comment]
> @dosera So the only problem now is that you can see group names that the user does not have access to?
> 
> If the only problem is that the group name shows up, then that's not a bug. If you can view or manipulate group details without proper rights, then that is a bug.

So it is intended that all the groups are listed even if a user has no rights to view or manipulate that group?
But on selection/opening of that group the user should get an access denied?
Am I correct on that intended behavior?

**Comment by ssilvert** [comment]
That is correct.

For now, it just gives you a message if you try to click on a group you don't have access to.  Then it navigates to the root.  We could do some better behavior, but it gets difficult.  It's still much better than the old UI where you would navigate to a nasty "Forbidden" screen.

**Comment by dosera** [comment]
Dear @ssilvert, thanks for your post - that's exactly what happens (and what I didn't expect/think was a mistake).
Thanks a lot for the help/input - I'll close this issue as resolved. If this on some kind of roadmap maybe it'll come in the future (and for me this isn't a deal breaker - would just be a nice to have).
