### ISSUE TITLE
SSSD User Federation dissapeared in 20.0.1/20.0.2

### ISSUE THREAD

**Issue by s1341** [keycloak/keycloak#16165]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

The SSSD User Federation feature, described here (https://www.keycloak.org/docs/latest/server_admin/index.html#_sssd), seems to have been removed in the latest versions of keycloak.

See https://github.com/keycloak/keycloak/discussions/15587#discussioncomment-4267475.

Was this an accidental removal, or is it intended that this feature be removed. If intentional, I suggest that the documentation be updated.

### Version

20.0.2

### Expected behavior

When sssd is configured on the keycloak server's host machine, SSSD User Federation should be listed as an option in the User Federation admin page, and it should be possible to use the functionality.

### Actual behavior

The SSSD User Federation option never shows up in the admin page.

### How to Reproduce?

Follow the instructions at https://www.keycloak.org/docs/latest/server_admin/index.html#_sssd. The SSSD User Federation never shows up.

### Anything else?

Happy to help debug the issue. I'm on libera in the freeipa channel.

**Comment by gno65** [comment]
It seems that SSSD user federation is broken for keycloak > 17.0.1
After upgrading from keycloak 17.0.1 to 20.0.2 login is not possible anymore for users stored in FreeIPA.
I also tried upgrading to 18.0.2 and 19.0.3 with the same result.

I always get the following error when I try to login
org.keycloak.federation.sssd.impl.PAMAuthenticator.authenticate NullPointerException

Login to the admin console with the local keycloak admin user is possible.

**Comment by Keeper-of-the-Keys** [comment]
Related https://github.com/keycloak/keycloak/issues/11728

**Comment by mposolda** [comment]
This is something, which we need to fix in Keycloak 22.

Keycloak is able to federate (read-only) users from IDM and other LDAP servers through SSSD. This relies on JNI to talk to SSSD installed on the same machine as Keycloak. In the Quarkus distribution this is most likely not working at the moment due to some missing libraries/etc.

For more details refer to the documentation: https://www.keycloak.org/docs/latest/server_admin/index.html#_sssd

**Comment by mposolda** [comment]
As part of this GH issue, the initial SSSD integration was fixed. The overall task for SSSD for make SSSD integration working again (including tests and docs) is #20262
