### ISSUE TITLE
Set OpenShift as a "Social Identity Provider" cannot work

### ISSUE THREAD

**Issue by jackson2213** [keycloak/keycloak#16166]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

identity-brokering

### Describe the bug

[keycloak-2-m9vzx-keycloak.log](https://github.com/keycloak/keycloak/files/10293273/keycloak-2-m9vzx-keycloak.log)
when i set openshift as Identity Provider cannot work. so i use RHSSO do same configuration, RHSSO it's works. below is keycloak errors.
login page
![image](https://user-images.githubusercontent.com/37919544/209291873-c960a296-cffe-4251-bb9c-3181fcb1b824.png)
when i click login with openshift-v4
![image](https://user-images.githubusercontent.com/37919544/209291998-dccf640a-6628-4a9c-8fcb-ae1d621d0522.png)
keycloak pod logs
[keycloak-2-m9vzx-keycloak.log.txt](https://github.com/keycloak/keycloak/files/10293278/keycloak-2-m9vzx-keycloak.log.txt)

### Version

all

### Expected behavior

keycloak can set openshift-v4 as identitype provider

### Actual behavior

errors

### How to Reproduce?

configure openshift as identitype provider

**Comment by mposolda** [comment]
I am adding to Keycloak 22 for now as AFAIK we already have this planned. But it is possible, that we will postpone this task.

**Comment by pedroigor** [comment]
@jackson2213 Did you configure the trust store SPI? 

Looking at the logs, it seems the error is related to faling to validate the API server certificate. Not sure why it is different than RHSSO but based on this error you should install the API server certificate to a truststore and configured it as [here](https://www.keycloak.org/server/keycloak-truststore).
