### ISSUE TITLE
We are not able to set the JWKS URL

### ISSUE THREAD

**Issue by ahcamy2021** [keycloak/keycloak#16163]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the Key's config of client, when we activate the config 'Use JWKS URL' we are note able to set the config 'JWKS URL'. 

We tried to import à client with this config activated with json file and the same thing the client was added but without any value in the config 'JWKS URL'.

### Version

20.0.2

### Expected behavior

Able to edit/view the value of the config 'JWKS URL' in the interface of admin console.

### Actual behavior

Not able to edit/view the value of the config 'JWKS URL' in the interface of admin console.

### How to Reproduce?

Create a new client, activate the flag confidential authentification, in the Kes config activate 'Use JWKS URL'.

**Comment by ssilvert** [comment]
@ahcamy2021 This is working for me.  Can you try it on the latest nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
I'm fairly certain that this is fixed in the latest build.  I'm going to close this issue, but we can reopen if still continue to have problems.
