### ISSUE TITLE
E-mail template and internationalization missing for action "UPDATE_EMAIL"

### ISSUE THREAD

**Issue by OtenMoten** [keycloak/keycloak#16173]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

There is **no e-mail template** for action `UPDATE_EMAIL`. I've downloaded the `.jar` from `/opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-20.0.2.jar` and checked the `\base\email\html` directory.

As you can see on that image https://imgur.com/a/w8IS7Kv there is no e-mail template for the action `UPDATE_EMAIL`.

Also, there is **no internationalization** for the action `UPDATE_EMAIL`. As you can see on this image https://imgur.com/tlFYHt9 I've used "**Deutsch**" as language **but the text is english**.

### Version

20.0.2

### Expected behavior

1. There should be an e-mail template for the action `UPDATE_EMAIL`.
2. Internationalization should work for the action `UPDATE_EMAIL`.

### Actual behavior

1. An e-mail template for the action `UPDATE_EMAIL` is missing.
2. Internationalization is not working the action `UPDATE_EMAIL`.

### How to Reproduce?

Install Keycloak `20.0.2`, create a user and set action `UPDATE_EMAIL`. Then, try to login with and change language. As you can see, regardless of what language you set up, the text is english. 

Also, try to find an e-mail template for action `UPDATE_EMAIL` in the `/opt/keycloak/lib/lib/main/org.keycloak.keycloak-themes-20.0.2.jar` file.

**Comment by OtenMoten** [comment]
Hello @mposolda 

The issue is still present as described above.

**Comment by Saman-jafari** [comment]
@alexted sure :)

Hey @OtenMoten I checked the code and there is all what you need in code from translation key for page till HTML for email update conformation. So if you want, you can move some variables from en to any other language properties to change the stuff you need, and you can do it by yourself. I know some keys are not in the main repo in other languages, but just to make it easier, you can do it till someone put translations in the code for other languages, but for en they are there, so let me just point you to the right direction, so you can fix it yourself in your instance for your own theme but for this to work you need to read theme part of this page and whatever below it carefully https://www.keycloak.org/docs/latest/server_development/#_themes so lets start:

For example, you want to translate this text: `You need to update your email address to activate your account.` you can see that in messages_en.properties in base `theme/base/login/messages/messages_en.properties` there is a key already defined `updateEmailMessage=You need to update your email address to activate your account.` so you just need to add `updateEmailMessage` to messages_de.properties, so it translates to whatever you need, for the email template I checked, it uses the `email-update-confirmation.ftl` `theme/base/email/html/email-update-confirmation.ftl` that again if you check for the keys in en `theme/base/email/messages/messages_en.properties` you just need to change this `emailUpdateConfirmationBodyHtml=<p>To update your {2} account with email address {1}, click the link below</p><p><a href="{0}">{0}</a></p><p>This link will expire within {3}.</p><p>If you don't want to proceed with this modification, just ignore this message.</p>
` or add the key `emailUpdateConfirmationBodyHtml` to the language that you want that and btw AFAIS it is available in `de` `ar` `fr` `en` in the base so just read the themes and how to change messages and go on with it, I went through some cases, and they also work properly.

I hope that this helps you to move forward again these are all need you to read the https://www.keycloak.org/docs/latest/server_development/#_themes and all things below it and more importantly in your specific point this: https://www.keycloak.org/docs/latest/server_development/#messages 
I checked all your cases mentioned in main issue and all of them can be solved with just what I wrote, but please let me know if there is something else missing.

**Comment by OtenMoten** [comment]
Thank you very much @Saman-jafari for your sophisticated answer. 

Problem solved.
