### ISSUE TITLE
Username is not updated if email was changed

### ISSUE THREAD

**Issue by OtenMoten** [keycloak/keycloak#16174]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

If `Email as username` is configured in the realm like on that image https://imgur.com/sWqBnoI and the user was forced to update the email address by the action `UPDATE_EMAIL`, then the username is not updated.

### Version

20.0.2

### Expected behavior

If `Email as username` is configured, then the username should be also updated and replaced by the new email address if the user was forced by action `UPDATE_EMAIL`.

### Actual behavior

The username is not updated if the email address was changed by the action `UPDATE_EMAIL`.

### How to Reproduce?

Configure your realm like on this image https://imgur.com/sWqBnoI and set action on user `UPDATE_EMAIL`. If you did, you can see that the username is not updated.

**Comment by pedroigor** [comment]
I think the behavior is expected and the username does not change. 

@mposolda Looks like we have been working like that for a long time. Is there any reason why we don't update the username when email as username is set?

**Comment by mposolda** [comment]
@pedroigor I am not aware of any reason. I see that you send PR https://github.com/keycloak/keycloak/pull/16264 , but there is also other related PR https://github.com/keycloak/keycloak/pull/15583 . Added you as reviewer to that one.

**Comment by OtenMoten** [comment]
Hello @pedroigor and @mposolda thanks for worry about this issue.

Which version of the Keycloak Docker-image I should use to test it?

**Comment by pedroigor** [comment]
@OtenMoten Yes, nightly from https://quay.io/repository/keycloak/keycloak. Thanks.

**Comment by OtenMoten** [comment]
Works.

Thank you very much for paying attention to this issue.

Keycloak is very nice account management software.
