### ISSUE TITLE
Invalid 'expires' header for AWS load balancer cookie

### ISSUE THREAD

**Issue by acassaignemondeca** [keycloak/keycloak#16180]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/jee

### Describe the bug

KeyCloak adapter uses a HttpClient version that is not compatible with latest RFC date format for cookies. This format is used for example if an AWS load balancer sits in front of KeyCloak server.

It is currently not possible to set the HttpClient in KC adapter like this:
HttpClient httpClient = HttpClients.custom()
         .setDefaultRequestConfig(RequestConfig.custom()
         .setCookieSpec(CookieSpecs.STANDARD).build())
         .build();

### Version

20

### Expected behavior

KC adapter understands correctly the Set-Cookie directive (and its expiration date header).

### Actual behavior

KC adapter requests to KC server generate warnings:

WARN (default task-7) [org.apache.http.client.protocol.ResponseProcessCookies] Invalid cookie header: "Set-Cookie: AWSALB=XXXXXX; Expires=Mon, 26 Dec 2022 13:34:42 GMT; Path=/". Invalid 'expires' attribute: Mon, 26 Dec 2022 13:34:42 GMT

### How to Reproduce?

KC adapter
AWS load balancer in front of KC server

### Anything else?

https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api

https://issues.apache.org/jira/browse/HTTPCLIENT-1763

**Comment by jsorah** [comment]
Hi, thank you for the report - I see that you at least have a workaround for this issue, thank you for sharing that.

Given the [deprecation status](https://www.keycloak.org/2023/03/adapter-deprecation-update) of the Keycloak adapters, there isn't high priority to work on issues related to them and this seems like existing behavior. 

Community contributions are welcome.
