### ISSUE TITLE
Deprecate legacy cookie behaviour behind profile

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#16181]
### Description

Since implementing [KEYCLOAK-12125](https://issues.redhat.com/browse/KEYCLOAK-12125), Keycloak adds two cookies with the same value but different `SameSite` settings when the `SameSite=None` is set to none. 

The was due to old browsers not support `SameSite=None`, see https://www.chromium.org/updates/same-site/incompatible-clients/ for details and how to detect them.

Since then, browsers supporting this are wide-spread: https://caniuse.com/?search=SameSite%3DNone (92+%). 

Adding these extra cookies adds to the HTTP headers sent in a response and request, and a default setup with NGINX which limits responses with 4k headers needs to be tweaked to make it work. 

Therefore, I suggest to remove the `*_LEGACY` cookies. Additionally, we should unify our cookie behaviour so that:
- All cookies are `Secure` by default.
- All cookies are `SameSite=Strict`, unless explicitly specified otherwise.

### Motivation

* Simplify Keycloak's code structure, and support ever-green browers.
* Simplify setup of Keycloak behind a loadbalancer

**Comment by mabartos** [comment]
@ahus1 Thanks for creating this issue! Some time ago, I created a PR[1] related to cookies processing. I'd like to complete it a little bit, even with the removal of Legacy cookies. 

I don't see any backward compatibility implications, as these two versions of cookies should already be present for clients. Moreover, there is not need for any "migration" process related to the cookies, right?


[1] https://github.com/keycloak/keycloak/pull/15408

**Comment by ahus1** [comment]
Hi @mabartos - I had a look at the PR, and I see a lot of refactoring, so I miss the current intentions behind the linked PR. 

About compatibility implications: I would consider the cookies an internal API, and we should be free to change their contents, or remove them. Adding a new cookie name should be in the release notes, as people might have their cookies documented / whitelisted. Still a relevant maintainer might think otherwise.

If we still want to support old browsers, another option that would be to add the "SameSite" depending on the usage agent, so we only send it to those browsers that support it. This would still simplify it for the users of Keycloak (no fiddling with the response header length) while it keeps the complexity of the Keycloak code. So for me it is second best. I'd still go for it if dropping the old browsers would be an issue. 

There should be no migration for the cookies IMHO as we're just dropping the old cookies, and nothing would change for new browsers. 
For old browsers it would either break (I might need to find out/document what would break), or if we implement logic regarding the user agent the old browsers would need to re-login as the old cookies wouldn't be recognized any more.

Do you want to drive this further? As I am not sure about the intentions of the linked PR, and we lack confirmation of a maintainer that this can be dropped, I can't advise if this should be part the linked PR or a second PR.

**Comment by mabartos** [comment]
@ahus1 Thanks for your input!

> Do you want to drive this further? As I am not sure about the intentions of the linked PR, and we lack confirmation of a maintainer that this can be dropped, I can't advise if this should be part the linked PR or a second PR.

I'll try to find more information and, yes, drive this a little bit further :)

**Comment by jonkoops** [comment]
@mabartos @ahus1 see #16734

**Comment by jonkoops** [comment]
I've renamed this issue to e more descriptive of what we want to accomplish. The actual removal of legacy cookies has been placed under #16770.

**Comment by jonkoops** [comment]
If there is anyone available to implement this under #16747 that would be greatly appreciated.

**Comment by jonkoops** [comment]
We've decided to expand the scope of this issue to improve the cookie behaviour of Keycloak as a whole, aiming to improve consistency and security, see #26161 for the background discussion on this.

**Comment by stianst** [comment]
One challenge is that PhantomJS doesn't like secure cookies (or at least doesn't send them over http://localhost, which should be considered a secure context). When removing the legacy cookies that brings a challenge to any tests that are using PhantomJS.

**Comment by jonkoops** [comment]
@stianst perhaps we can make quick work on landing #9979, even replacing it with the existing WebDrivers on Selenium would be fine.

**Comment by stianst** [comment]
@jonkoops a nice and simper place to start would be with https://github.com/keycloak/keycloak-quickstarts, and those are the main blocker for removing legacy cookies as I believe the main testsuite doesn't use PhantomJS very much, and uses https when it does.

**Comment by jonkoops** [comment]
Yeah, added this to my personal backlog. Perhaps I can do a quick upgrade to Selenium 4 there.

**Comment by jonkoops** [comment]
Since this is blocked on the test suite refactor we'll have to bump this down the line for now. I am moving it to the next milestone so we don't forget about it.

**Comment by jonkoops** [comment]
Ok, we've managed to remove PhantomJS from both the main testsuite and the quickstart. This means this is no longer a blocker for this issue.

**Comment by stianst** [comment]
Closing this as we've found a way to safely get rid of the LEGACY cookies completely. See #16770
