### ISSUE TITLE
context.getHttpRequest() not correctly implemented?

### ISSUE THREAD

**Issue by tilothiele** [keycloak/keycloak#16184]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I have a custom Authenticator. Inside the authenticate() method I need to access the http headers (cookies).

variant A
```
  import java.net.http.HttpHeaders;
  import java.net.http.HttpRequest;
  ...

  public class MySapSsoAuthenticator implements Authenticator {

  ...

	@Override
	public void authenticate(AuthenticationFlowContext context) {

		AuthenticatorConfigModel acm = context.getAuthenticatorConfig();
		Map<String, String> config = acm.getConfig();
		String cookieName = config.get(MySapSsoConfig.KEY_COOKIE_NAME);
		
		HttpRequest req = (HttpRequest)context.getHttpRequest(); // crash
		HttpHeaders headers = req.headers();
 	    	String cookie = headers.firstValue(cookieName).orElse(null);
 	    	...
	}
  ...
  }
```

variant B

```
public class MySapSsoAuthenticator implements Authenticator {

...

	@Override
	public void authenticate(AuthenticationFlowContext context) {

		AuthenticatorConfigModel acm = context.getAuthenticatorConfig();
		Map<String, String> config = acm.getConfig();
		String cookieName = config.get(MySapSsoConfig.KEY_COOKIE_NAME);
		
		org.jboss.resteasy.spi.HttpRequest req = context.getHttpRequest();
		jakarta.ws.rs.core.HttpHeaders headers = req.getHttpHeaders(); // crash
		Cookie cookie = headers.getCookies().get(cookieName);
 	    	...
	}
...
}
```

### Version

20.0.2
openJdk 11

### Expected behavior

I expect to retrieve the http headers / cookies from

AuthenticationFlowContext,getHttpRequest().getHttpHeaders().getCookies().get(...)

without exceptions.

### Actual behavior

KC throws on variant A:
`2022-12-27 14:40:12,513 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class com.sun.proxy.$Proxy45 cannot be cast to class java.net.http.HttpRequest (com.sun.proxy.$Proxy45 is in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @136432db; java.net.http.HttpRequest is in module java.net.http of loader 'platform')
`

on variant B:
`2022-12-27 15:04:41,985 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-2) Uncaught server error: java.lang.NoSuchMethodError: 'jakarta.ws.rs.core.HttpHeaders org.jboss.resteasy.spi.HttpRequest.getHttpHeaders()'
`

### How to Reproduce?

```
public class MySapSsoAuthenticator implements Authenticator {

... // rest of class omitted

	@Override
	public void authenticate(AuthenticationFlowContext context) {
		context.getHttpRequest().getHttpHeaders().getCookies().get("test");
		context.getHttpRequest(); // never reached
	}
}
```
install and invoke should do.

### Anything else?

The implementations of Request seems not to be what the interfaces promises.

**Comment by tilothiele** [comment]
I found the root cause.
I used resteasy-client 6.2.2.Final instead of version 4.7.7.Final
It works like a charm now.

**Comment by sandeepubyon** [comment]
Any update on this? I am also facing the same issue.

**Comment by tilothiele** [comment]
> Any update on this? I am also facing the same issue.

This is not an issue. This was due to a wrong project configuration. See my message above.
