### ISSUE TITLE
Keycloak Quarkus Distro is not able to process the log format

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#16189]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Linking one issue related mulitple log handler [https://github.com/keycloak/keycloak/issues/16188](https://github.com/keycloak/keycloak/issues/16188)

In the same line i could start keycloak with single handler only but we can not pass format 

I'm trying to start Keycloak with log format as the document suggests and it's failing in windows but the same works in mac

**C:\Users\Administrator\Downloads\keycloak-20.0.2\keycloak-20.0.2\bin>kc.bat start-dev --log=file --log-file=../data/kc.log --log-file-format="'%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'"**

"JAVA_OPTS already set in environment; overriding default settings with values: -Dprogram.name=kc.bat -Dprogram.name=kc.bat -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
%s%e%n' was unexpected at this time.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/8745632/209788811-d2ffdf4d-ec1a-48ff-ae2b-bb8cec587c5b.png">

Doc reference:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/8745632/209788962-112da9af-44c7-4529-9b4d-c4133bf66d19.png">

### Version

20.0.1

### Expected behavior

It's failing in windows machine if we provide the log format

### Actual behavior

It should log the information in the provided format

### How to Reproduce?

Execute the following command:

kc.bat start-dev --log=file --log-file=../data/kc.log --log-file-format="'%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'"

**Comment by sschu** [comment]
I would assume this is because % denotes variables on DOS/Windows so you need some kind of escaping for it?

**Comment by ajaiswal595** [comment]
But in the wildfly distro, it was working.

And if it is platform-dependent then we should write it in docs also **it should not platform dependent.**

**Comment by sschu** [comment]
It seemed to be an escaping issue and I did not find it fixable by providing the parameters in an escaped way. Instead, I provided a PR changing `kc.bat`. I only focused on making the logging work. Other things might be broken now so we need to see what the CI says. But you can give it a spin by copying the `kc.bat` from my branch: https://github.com/keycloak/keycloak/pull/16229
