### ISSUE TITLE
Keycloak Quarkus Distro is not able to process the log multiple log handler

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#16188]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I'm trying to start Keycloak with multiple log handler as the document suggests and it's failing in windows but the same works in mac 

**kc.bat start-dev --log=console,file --log-file=../data/kc.log
Option '--log' expects a single value (<handler>) Expected values are: console, file, gelf
Try 'kc.bat start-dev --help' for more information on the available options.**

I have tested it with latest also and it's failing 

<img width="981" alt="image" src="https://user-images.githubusercontent.com/8745632/209787369-3c6b3366-7d5d-4e4f-a060-04d993b8eb11.png">

Doc
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/8745632/209786725-570ddbb5-3831-45d6-8a1e-75e340dbd5d7.png">

### Version

20.0.1

### Expected behavior

It should not fail and run.

### Actual behavior

It's failing with multiple log handlere

### How to Reproduce?

Execute this command in windows 

kc.bat start-dev --log=console,file --log-file=../data/kc.log

And it will fail

**Comment by sschu** [comment]
I provided a PR: https://github.com/keycloak/keycloak/pull/16298
