### ISSUE TITLE
Jakarta EE 9 support in Keycloak admin client java library

### ISSUE THREAD

**Issue by marcgemis** [keycloak/keycloak#16207]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

I tried to use Keycloak admin client 20.0.2 in a Spring Boot 3.0 project. This does not work, as the Keycloak library does not support Jakarta EE 9.
There is a similar issue 11895 logged, but that is labeled "saml".

### Version

20.0.2

### Expected behavior

N/A

### Actual behavior

N/A

### How to Reproduce?

N/A

**Comment by stianst** [comment]
Please use the `keycloak-admin-client-jakarta` artifact instead of `keycloak-admin-client`

**Comment by marcgemis** [comment]
Thank you for this information! I'll certainly try it.
