### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by solidDoWant** [keycloak/keycloak#16210]
### Description

I'd be great if there was a versioned Helm chart for the resources in https://github.com/keycloak/keycloak-k8s-resources/blob/main/kubernetes/kubernetes.yml.

### Motivation

There are a number of benefits for end users (such as myself), including:
* Upgrade rollbacks
* Chart versioning separate from application versioning
* Easy for users to change manifest values (i.e. changing deployments to use a pull-through image cache)
* Easier to maintain in the long run
* Integrates much more nicely with other Kubernetes ecosystem tools compared to a large YAML file with lots of resources

### Details

I'd be willing to write one if a PR would be accepted for it.

**Comment by vmuzikar** [comment]
I'm moving this to the main Keycloak repo where we track Operator issues. This will allow us to properly triage and plan for this.

**Comment by abstractj** [comment]
@solidDoWant today I had the chance to speak with @vmuzikar. Thanks, submitting and reporting this issue, but unfortunately, we don't support or have the capacity to provide support HELM charts. I'd suggest creating your HELM chart on your repository, or contributing to already existing projects.

**Comment by tspearconquest** [comment]
Hi, would you accept a pull request for a community maintained chart on the `keycloak/keycloak-community` repo? We could submit it there with the understanding that you don't support it but offer it as a contribution from the community.

**Comment by vmuzikar** [comment]
@tspearconquest Thank you for offering the contribution. However, whatever is hosted under the Keycloak GitHub org is considered supported. The `keycloak/keycloak-community` is meant for storing community relevant information aand is maintained by the Keycloak team.
