### ISSUE TITLE
keycloak cluster happen Code ERROR

### ISSUE THREAD

**Issue by bfyxzls** [keycloak/keycloak#16238]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

keycloak cluster mutiple three node,it occasionally appear "CODE TO TOKEN ERROR"
Code '%s' already used for userSession '%s' and client '%s'
![Uploading 图片.png…]()

### Version

14.0.0

### Expected behavior

keycloak cluster mutiple three node,it occasionally appear "CODE TO TOKEN ERROR"
Code '%s' already used for userSession '%s' and client '%s'
![Uploading 图片.png…]()

### Actual behavior

请求code时，会出现一些日志，说这个code被其它人占用了

### How to Reproduce?

请求code时，会出现一些日志，说这个code被其它人占用了

### Anything else?

请求code时，会出现一些日志，说这个code被其它人占用了

**Comment by sschu** [comment]
Please provide exact steps to reproduce your problem. Furthermore, this message can appear if users actually use a token multiple times (e.g. by reloading a page).

**Comment by mposolda** [comment]
Closing as the steps to reproduce doesn't contain enough info and additional steps to reproduce requested by @sschu were not provided.
