### ISSUE TITLE
Improve validation on build options when `--optimized` is set

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#16243]
### Description

This is a follow-up on https://github.com/keycloak/keycloak/pull/16221.

In order to avoid confusion when using build options to start an optimized server image, we should improve the UX by:

```
Therefore, I'd propose this solution in this scenario:

* the --optimized flag is used

* NO build parameters are specified (but they can be specified via ENV vars or props)
check whether the reaugmentation was already executed:
* if NOT: show some warning message ("Be aware that for proper settings of build parameters, you have to execute the build phase")
* if YES: keep the current approach
```

### Motivation

Improve UX and avoid recurrent issues like https://github.com/keycloak/keycloak/issues/15238.

**Comment by pedroigor** [comment]
@mabartos We should probably keep the same experience as CLI and fail to start when using ENV vars.

I would also add that there is an inconsistency across the different configuration sources in terms of validation. The same problem should be fixed when using a configuration file.

For instance, through CLI you can't set build options when using the `optimized` flag. Not true for others. This also can bring some confusion.

At the same time, the more validation we add the more we sacrifice startup time. That is one of the reasons why we have the "fast start" path as per https://github.com/keycloak/keycloak/blob/f799abd9559fb26cde0b273a25989ccced2f4be7/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java#L73. In this case, we do not start Picocli at all as it has some costs when bootstrapping.

Another reason is that we can't have this level of limitation when using a configuration file. Otherwise, people would need to have two distinct files for the `build` and `start` phases.

That said, I'm not sure how we can solve this without sacrificing a bit the startup time and UX too at some degree. The decision is really a trade-off between UX and performance.

We could probably add this validation only when using env vars ...

**Comment by shawkins** [comment]
Resolving as out of date - there have been several refinements related to this in the last couple of releases. The latest proposal is a hard error when they seem to change #33241
