### ISSUE TITLE
New bootstrapping for Admin and Account consoles

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#16279]
### Description

The current bootstrapping mechanism uses inline javascript and Freemarker to stuff bootstrap info into index.ftl. 

Inline script looks like this for admin console:
```
<script id="environment" type="application/json">
    {
      "loginRealm": "${loginRealm!"master"}",
      "authServerUrl": "${authServerUrl}",
      "authUrl": "${authUrl}",
      "consoleBaseUrl": "${consoleBaseUrl}",
      "resourceUrl": "${resourceUrl}",
      "masterRealm": "${masterRealm}",
      "resourceVersion": "${resourceVersion}",
      "commitHash": "${git.commit.id}",
      "isRunningAsTheme": true
    }
  </script>
```

The values of these global variables are stuffed into Freemarker in the back end java code.

There is a similar but much larger inline script for account console.  See [index.ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/keycloak.v2/account/index.ftl).

One problem is that this is not very easy to configure and you can end up with a lot of global variables you don't really need.  A better solution is something along the lines of what @stianst proposed here: https://github.com/keycloak/keycloak/issues/15874#issuecomment-1371885105

`Another improvement we can make perhaps is how we bootstrap the config, we could potentially make index.ftl a static page, and instead have a dynamic json config file that contains the configuration needed by the admin console. This can be templated in the same way as the index.ftl is done today, and we should be able to expose this on the same URL as index.html, but perhaps just as config.json.`

### Discussion

https://github.com/keycloak/keycloak/issues/15874

**Comment by ssilvert** [comment]
Also see https://github.com/keycloak/keycloak/issues/9553 and its associated PR.

**Comment by edewit** [comment]
Currently the location of the console is based on a resource url that is dynamic something like `/resources/qa1sd/admin/keycloak.v2/assets/index.837288d4.js`. When we can get this in another way, the I see no need for any bootstrapping

**Comment by jonkoops** [comment]
Closing this issue as we should not add additional requests to the bootstrapping proccess of the consoles that would only decrease performance.
