### ISSUE TITLE
Admin Client - Resource/Scope permissions list problem

### ISSUE THREAD

**Issue by MuratKaragozgil** [keycloak/keycloak#16272]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

Hello,

First I'm trying to write my own implementation of the clone function for realms/clients. But there is a bug or missing function on the admin API.

`ClientResource baseClientResource = baseRealmResource.clients().get(baseClientRepresentation.getId());
        List<ScopeRepresentation> scopes = baseClientResource.authorization().scopes().scopes();
        List<ResourceRepresentation> resources = baseClientResource.authorization().resources().resources();
        List<PolicyRepresentation> policies = baseClientResource.authorization().policies().policies();
        List<ResourcePermissionRepresentation> permissions = baseClientResource.authorization().permissions().permissions(); // missing function`
        
        There is no method for getting all permission of the selected clients.

### Version

20.0.2

### Expected behavior

Should be a method like scopre/resource or policies.

### Actual behavior

We should get all Resource and scope permissions or both at the same time

### How to Reproduce?

You can use admin API like this. I described in the detail section.

**Comment by jemaromaster** [comment]
Hello! did you get to obtain the permissions from a specific client with an alternative way?

**Comment by pedroigor** [comment]
@jemaromaster You can use the `org.keycloak.admin.client.resource.AuthorizationResource#policies ` and filter the policies with type `resource` and `scope`.

Permissions are policies but set with one of these types. 

You also have methods from `org.keycloak.admin.client.resource.PermissionsResource` to fetch these two types of permissions.
