### ISSUE TITLE
Read-only user attributes error from Keycloak Admin API

### ISSUE THREAD

**Issue by adl1995** [keycloak/keycloak#16274]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

After upgrading to Keycloak 19 (from version 15) we are seeing a `updateReadOnlyAttributesRejectedMessage` error when updating user properties using the Keycloak Admin API.

### Version

19.0.0

### Expected behavior

We should be able to update the user properties without any error. In this case we are setting a required action for setting the user's MFA credentials.

### Actual behavior

This error gets returned:

```
utils.KeycloakAPIError: {'status_code': 400, 'message': 'updateReadOnlyAttributesRejectedMessage'}
```

### How to Reproduce?

The error can be reproduced by calling this endpoint: `PUT /{realm}/users/{id}`.

### Anything else?

This error appears occasionally. Furthermore, if we edit the user profile manually from the Keycloak admin console, the error disappears, and we are able to call the API endpoint correctly.

**Comment by sschu** [comment]
Have you tested this on the latest release which is 20.0.2?

**Comment by pedroigor** [comment]
Please, feel free to re-open once you have more information about how to reproduce the issue. It would be nice to understand which attribute you are managing.

**Comment by azakrytnoi** [comment]
Same issue updating user attribute. Keycloak version 25.0.1. Issue present only when using REST API, In UI all works perfect.
to reproduce:
- user from federated provider, LDAP
- user does have custom attribute (not imported from LDAP, specific for current realm/client), relevant for my business app (to be used later as JWT access token claim)

## Problem description

When updating custom attribute, `createTimestamp` and `modifyTimestamp` attributes MUST be specified in update request, in addition to custom attribute I want to update. 

 If those attributes are not specified, response is 400
```json
{"errors":[{"field":"modifyTimestamp","errorMessage":"updateReadOnlyAttributesRejectedMessage","params":["modifyTimestamp"]},{"field":"createTimestamp","errorMessage":"updateReadOnlyAttributesRejectedMessage","params":["createTimestamp"]}]}
```
If those attributes are specified, response is 400
```json
{"field":"modifyTimestamp","errorMessage":"updateReadOnlyAttributesRejectedMessage","params":["modifyTimestamp"]}
```
Error message about updated `modifyTimestamp` returned in all cases:
- when `modifyTimestamp` is omitted 
- when `modifyTimestamp` is set to `now()`
- when `modifyTimestamp` is unchanged, i.e. passed through from input

Issue exists only when updating custom attributes for user from LDAP federation provider. Updating user attributes for direct realm users - all fine. Updating custom attribute for user from LDAP federation provider via UI - also fine.

**Comment by zawawi** [comment]
Hi,

I have the same problem on Keycloak 26.4.0 when trying to update an LDAP User custom attribute through the REST API.
I received the following error:
`{
    "errors": [
        {
            "field": "modifyTimestamp",
            "errorMessage": "updateReadOnlyAttributesRejectedMessage",
            "params": [
                "modifyTimestamp"
            ]
        },
        {
            "field": "createTimestamp",
            "errorMessage": "updateReadOnlyAttributesRejectedMessage",
            "params": [
                "createTimestamp"
            ]
        }
    ]
}`

Through the UI, no problem but with the API there's a problem.

Like @azakrytnoi, I tested with modifyTimestamp omitted, setted to null, unchanged and stted to a random date (past and future).

If you input a creationTimeStamp to the same date as recorded on the user infirmation, only the following message is displayed:
`{
    "errors": [
        {
            "field": "modifyTimestamp",
            "errorMessage": "updateReadOnlyAttributesRejectedMessage",
            "params": [
                "modifyTimestamp"
            ]
        }
    ]
}`
