### ISSUE TITLE
Bug on isTokenExpired()

### ISSUE THREAD

**Issue by suchorski** [keycloak/keycloak#16278]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

The isTokenExpired() is returning true after init after updateToken() called and token expired (renewed with updateToken()) 

I guess is on this line:

```ts
if (timeLocal) { // timeLocal is null when initializing after a updateToken() called after token expired
  kc.timeSkew = Math.floor(timeLocal / 1000) - kc.tokenParsed.iat;
}
```

Using timeSkew: 0 on initOptions the problem doesn't occurs.
Perhaps is missing the timeLocal (new Date().getTime()) on line 260
```
setToken(initOptions.token, initOptions.refreshToken, initOptions.idToken); // line 260
```

Thanks

### Version

20.0.2

### Expected behavior

return false on isTokenExpired()

### Actual behavior

return true on isTokenExpired()

### How to Reproduce?

Only init the adapter after calling a updateToken() after the token expires

**Comment by jonkoops** [comment]
I am unable to reproduce this issue on the latest version of Keycloak. It seems that some changes have been made that possibly fixed this issue as a side effect. If someone is still able to reproduce this issue let me know and I will re-open.
