### ISSUE TITLE
Compatibility with Maven4 build cache and parallel builds

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#16308]
### Description

The [Maven Build Cache Extension](https://github.com/apache/maven-build-cache-extension) provides promising results for making the build faster when switching between local branches, and rebuilding Keycloak after local changes. 

### Motivation

This will provide a speedup for local builds already. 

While this will not update the Maven version referenced in the maven wrapper (yet), it will upgrade the maven dependencies used to work with both Maven 3 and Maven 4 as necessary. It also puts the necessary bits in place to allow parallel builds.

**Comment by ahus1** [comment]
After a discussion on the PR it turns out that the maven build cache configuration can't be checked in and be disabled by default yet. So this issue focuses only on the M4 compatibility.

**Comment by pedroigor** [comment]
Is this warning something we need to be concerned with:

```
[INFO] --- quarkus:2.13.7.Final:build (default) @ keycloak-quarkus-server-app ---
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but the project  *
[WARNING] * relies on System properties at build time which could cause   *
[WARNING] * race condition issues thus unpredictable build results.       *
[WARNING] * Please avoid using System properties or avoid enabling        *
[WARNING] * parallel execution                                            *
[WARNING] *****************************************************************
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.6.14.Final
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 4652ms

```
