### ISSUE TITLE
 Client Permissions on Resources not reflecting on Clients

### ISSUE THREAD

**Issue by MohammedAdain** [keycloak/keycloak#16307]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

Hi team,
I am trying to achieve a role based access to clients in Keycloak. For instance the users which are mapped to a role say access-only should only be authenticated to a client(for instance Grafana).

I am following an approach similar to [https://stackoverflow.com/a/54374808/12281085](https://stackoverflow.com/a/54374808/12281085) and [https://medium.com/@harsh.manvar111/keycloak-authorization-service-rbac-1c3204a33a50](https://medium.com/@harsh.manvar111/keycloak-authorization-service-rbac-1c3204a33a50).

I created two users access_user mapped it to a role access-only and no_access_user and left it unmapped.
Here are few snapshots of the configuration I made.
Created a policy access-only under the client grafana
![image](https://user-images.githubusercontent.com/61708483/211257113-1a8a3778-f7b6-437f-b643-85c1be24a96c.png)

![image](https://user-images.githubusercontent.com/61708483/211257154-7879a9d2-5094-49ed-928e-9d557918b513.png)
used that policy in default_permission, applied it to default_resource
![image](https://user-images.githubusercontent.com/61708483/211257247-29302c2b-b4e7-4395-8aa5-c65fd2b16544.png)
When I evaluate the auth flow in keycloak with no_access_user mapped to a role other that access-only, it shows Deny, which is as expected
![image](https://user-images.githubusercontent.com/61708483/211257393-a8212749-8fd2-4791-a730-d540f8a136c3.png)

![image](https://user-images.githubusercontent.com/61708483/211257428-05e577da-d413-4afd-94dc-1f3ca9368959.png)

but when I access the OpenID Connect client which is configured with Keycloak as no_acess_user
![image](https://user-images.githubusercontent.com/61708483/211257465-61317413-db8f-4557-9965-7c39ad51d6e8.png)

I am able to login the client (grafana), ideally no_access_user who is not mapped to access-only role shouldn’t have been able to login to grafana.
![image](https://user-images.githubusercontent.com/61708483/211257507-017b7e4d-f479-4062-b6a0-3e3ced055e06.png)

### Version

19.0.1

### Expected behavior

When I evaluate the auth flow in keycloak with no_access_user mapped to a role other that access-only, it shows Deny, which is as expected
![image](https://user-images.githubusercontent.com/61708483/211257393-a8212749-8fd2-4791-a730-d540f8a136c3.png)

![image](https://user-images.githubusercontent.com/61708483/211257428-05e577da-d413-4afd-94dc-1f3ca9368959.png)

but when I access the OpenID Connect client which is configured with Keycloak as no_acess_user
![image](https://user-images.githubusercontent.com/61708483/211257465-61317413-db8f-4557-9965-7c39ad51d6e8.png)

I am able to login the client (grafana), ideally no_access_user who is not mapped to access-only role shouldn’t have been able to login to grafana.
![image](https://user-images.githubusercontent.com/61708483/211257507-017b7e4d-f479-4062-b6a0-3e3ced055e06.png)

### Actual behavior

When I evaluate the auth flow in keycloak with no_access_user mapped to a role other that access-only, it shows Deny, which is as expected
![image](https://user-images.githubusercontent.com/61708483/211257393-a8212749-8fd2-4791-a730-d540f8a136c3.png)

![image](https://user-images.githubusercontent.com/61708483/211257428-05e577da-d413-4afd-94dc-1f3ca9368959.png)

but when I access the OpenID Connect client which is configured with Keycloak as no_acess_user
![image](https://user-images.githubusercontent.com/61708483/211257465-61317413-db8f-4557-9965-7c39ad51d6e8.png)

I am able to login the client (grafana), ideally no_access_user who is not mapped to access-only role shouldn’t have been able to login to grafana.
![image](https://user-images.githubusercontent.com/61708483/211257507-017b7e4d-f479-4062-b6a0-3e3ced055e06.png)

### How to Reproduce?

When I evaluate the auth flow in keycloak with no_access_user mapped to a role other that access-only, it shows Deny, which is as expected
![image](https://user-images.githubusercontent.com/61708483/211257393-a8212749-8fd2-4791-a730-d540f8a136c3.png)

![image](https://user-images.githubusercontent.com/61708483/211257428-05e577da-d413-4afd-94dc-1f3ca9368959.png)

but when I access the OpenID Connect client which is configured with Keycloak as no_acess_user
![image](https://user-images.githubusercontent.com/61708483/211257465-61317413-db8f-4557-9965-7c39ad51d6e8.png)

I am able to login the client (grafana), ideally no_access_user who is not mapped to access-only role shouldn’t have been able to login to grafana.
![image](https://user-images.githubusercontent.com/61708483/211257507-017b7e4d-f479-4062-b6a0-3e3ced055e06.png)

### Anything else?

I am following an approach similar to [https://stackoverflow.com/a/54374808/12281085](https://stackoverflow.com/a/54374808/12281085) and [https://medium.com/@harsh.manvar111/keycloak-authorization-service-rbac-1c3204a33a50](https://medium.com/@harsh.manvar111/keycloak-authorization-service-rbac-1c3204a33a50).

Again I am trying to achieve

I am trying to achieve a role based access to clients in Keycloak.
I did try another method which only works partially https://keycloak.discourse.group/t/role-group-based-authentication-not-working-for-users-authenticated-by-external-idps-azure-ad-github-etc/19427.

I’d really appreciate help here.

Thanks,
Mohammed Adain

**Comment by edwint88** [comment]
Maybe related to: https://github.com/keycloak/keycloak/issues/16597

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment]
@edwint88 https://github.com/keycloak/keycloak/issues/16597 is a different issue.

Regarding this one, there is no built-in support to restrict accessing clients based on its authorization settings. This is only possible through customizations such as https://github.com/cloudtrust/keycloak-authorization.
