### ISSUE TITLE
Discrepancy between legacy and map stores in storing some fields

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16309]
For some entities there are some fields stored in attributes in legacy store, while in map store it's stored in separate fields. 

See e.g. legacy [`RealmAdapter's getDisplayName()`](https://github.com/keycloak/keycloak/blob/522bf1c0b0490fd9a6a8bf18a6b06aae0fa989c5/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L88) vs [`MapRealmAdapter getDisplayName()`](https://github.com/keycloak/keycloak/blob/522bf1c0b0490fd9a6a8bf18a6b06aae0fa989c5/model/map/src/main/java/org/keycloak/models/map/realm/MapRealmAdapter.java#L110). There are multiple occurrences such as those. 

We need to support import in map store from export made from legacy store.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
