### ISSUE TITLE
Provider properties in keycloak.conf must be lowercase

### ISSUE THREAD

**Issue by ricojansen** [keycloak/keycloak#16328]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

When setting properties for a provider, the property key must be lowercase otherwise the property will be present but null.
For example:
spi-required-action-terms_and_conditions_or_else-apiUrl=https://api.example.com

When read with 

` public void init(Config.Scope config) {
        this.apiUrl = config.get("apiUrl");
    }`

Will set apiUrl to null.

When the key is lowercase eg
spi-required-action-terms_and_conditions_or_else-apiurl=https://api.example.com
and is read through

` public void init(Config.Scope config) {
        this.apiUrl = config.get("apiurl");
    }`

The value is set as expected.

### Version

20.0.2

### Expected behavior

The expected behaviour that the value is present under the key used in the configuration.

### Actual behavior

The value of the property is null.
A debugger reveals the key is present in the configuration but is null when read.

### How to Reproduce?

Create a provider (any kind).
Read a property with uppercase in it.
Set a property for the provider in the configuration.
Check in the debugger if the value is set in the provider.

**Comment by stianst** [comment]
Correct syntax to use is api_url, not apiUrl

**Comment by ricojansen** [comment]
I apparently didn't read the documentation thoroughly enough. However https://www.keycloak.org/server/configuration-provider specifies dashes (-) not underscores (_) as seperator. 

I resolved it by just using lowercase, that works. I was thrown of because of the fact that the ones with uppercase where present in the Config.Scope object as keys, just that the values where missing.
