### ISSUE TITLE
Single client export bug

### ISSUE THREAD

**Issue by vamsikrishna-VK31** [keycloak/keycloak#16321]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

When you export a single client (through the admin interface), the client's roles and their attributes does not appear in the exported JSON and therefore, are not imported back when you need it.

### Version

All Versions

### Expected behavior

The JSON file should contain all the roles 

### Actual behavior

The JSON file does not include the exported client's roles 

### How to Reproduce?

Create a client with some roles and give one or more roles . Export that single client through UI and then try to import the file to another realm or instance.

**Comment by vramik** [comment]
@vamsikrishna-VK31 Thank you fro reporting the issue. This functionality never worked. We've had a note about that export files from admin console are not suitable for backups of data transfer in documentation, but it has been (probably by mistake) removed by https://github.com/keycloak/keycloak-documentation/commit/eafa2bb3cfef86d0f05086f6798d3eaaf858fb5a

@andymunro could you please take a look into it?

**Comment by andymunro** [comment]
@vramik I could reinstate the caution in that file however, it looks like admin-console-export-import file is commented out for Keycloak from topics.adoc as only applying for WildFly and now it's removed from topics.adoc

**Comment by vramik** [comment]
Thanks @andymunro, IMO we need to include an information about limitations of admin console export. 

Could we use this issue for it or would you need another one?

**Comment by andymunro** [comment]
Okay, I will add it to https://www.keycloak.org/server/importExport 
Does that work, @vramik?

**Comment by vramik** [comment]
> Does that work, @vramik?
Yup, thanks.

**Comment by mposolda** [comment]
@andymunro Is this a blocker for Keycloak 22? Or can we add it to Backlog? And/or do you have updated PR for this? If you don't have time to look into this, the backlog is fine in my opinion as I don't see this as a blocker for Keycloak 22.

**Comment by andymunro** [comment]
I  don't have the PR because it was submitted when the Keycloak documentation directory was being moved. However, we reinstated the note about that restriction. It had been in the now-removed import/export chapter of the Server Administration guide.  The note is now at the end of this section under Using the Admin Console. https://www.keycloak.org/docs/latest/server_admin/index.html#using-the-admin-console
