### ISSUE TITLE
Hibernate 6 upgrade: API changes in JpaAutoFlushListener

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#16334]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After upgrading to Hibernate 6, JpaAutoFlushListener fails to compile because `EventSource.getDontFlushFromFind()` doesn't exist anymore. Code in quarkus3 branch has commented out the line that uses this method, but we need to figure out how to properly migrate this API change.

### Version

quarkus3 branch

### Expected behavior

JpaAutoFlushListener should use updated APIs.

### Actual behavior

Current code in quarkus3 branch commented out a line that calls a method that no longer exists.

### How to Reproduce?

Use quarkus3 branch

**Comment by ahus1** [comment]
I had a look with the following result: 

* The JpaAutoFlushListener is still needed, as the problem still exists in Hibernate 6 - see  #11666 and https://hibernate.atlassian.net/browse/HHH-15230
* Commenting out the line is correct, as this is the same change that has been done in the `DefaultAutoFlushEventListener`

When implementing this change, I recommend to copy over the original code from `DefaultAutoFlushEventListener` for all methods, and keep only the changes in `flushIsReallyNeeded()`.

**Comment by ahus1** [comment]
PR merged to the feature branch
