### ISSUE TITLE
Hibernate 6 upgrade: JSON functions need to be registered using new APIs

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#16336]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

In Hibernate 6, custom functions have to be registered using new APIs. There seems to be a hook in the dialects (PostgresDialect and CockroachDialect) via the `initializeFunctionRegistry` method, but the preferred way seems to be via `MetadataBuilderContributor`.

I've attempted to use the contributor as it is already used to register the custom `JsonbType`, and apparently was able to register the `->>` function (test of an actual query that uses this function was not yet done, but hibernate stopped complaining about unrecognized function).

We need to check if this is being done correctly and also register the `->` and `@>` functions. One tricky thing about `->` is that it has a `JsonbType` return type, and we need to check how exactly to map that when registering the function.

### Version

quarkus3 branch

### Expected behavior

All JSON functions used in map storage should be properly registered/tested with Hibernate 6

### Actual behavior

Only `->>` function is registered and we're not sure the approach taken is the correct one for that.

### How to Reproduce?

User quarkus3 branch.

**Comment by vramik** [comment]
According to Hibernate team recommended way to register functions in H6 is implementing `org.hibernate.boot.model.FunctionContributor` spi. 

There is Hibernate Zulip chat with details: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/.E2.9C.94.20H5.20-.3E.20H6.20upgrade.3A.20registerFunction.20replacement

**Comment by vramik** [comment]
https://github.com/keycloak/keycloak/pull/16498
