### ISSUE TITLE
Hibernate 6 upgrade: Entity -> id mapping no longer automatically done

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#16337]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After upgrading to hibernate 6, some queries in the legacy JPA store failed with hibernate complaining about wrong types. For example:

https://github.com/keycloak/keycloak/blob/f11bef3e7f697935adf4c4a29e9225d62e5580d5/model/jpa/src/main/java/org/keycloak/authorization/jpa/entities/ResourceEntity.java#L70

`s.resourceServer` is actually a `ResourceServerEntity`, and the parameter is a `String`. In Hibernate 5, the entity would be mapped to it's id automatically, but Hibernate 6 shows an error saying the types are incompatible. The fix is easy, just replace `s.resourceServer` by `s.resourceServer.id`, but we might be missing some way to perform the mapping automatically.

Another example is in queries done via `CriteriaBuilder`. Such as 

https://github.com/keycloak/keycloak/blob/f11bef3e7f697935adf4c4a29e9225d62e5580d5/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java#L158

The query in this method actually returns the ids of the entities, not the entity type itself. Again, Hibernate 5 seemed to map these things automatically, whereas Hibernate 6 displays an error complaining about incompatible types. Again, fix is easy, just create the query using the `String` type:

```
        CriteriaQuery<String> querybuilder = builder.createQuery(String.class);
```

We need to check if there's anything that must be done now to perform this mapping automatically, or if this is a case of Hibernate 6 being more strict about the types used in the queries.

### Version

quarkus3 branch

### Expected behavior

Migration to Hibernate 6 should probably be accomplished without changes to the queries.

### Actual behavior

Queries are being changed to properly match the expected types in Hibernate 6.

### How to Reproduce?

Use quarkus3 branch.

**Comment by ahus1** [comment]
Trying to reproduce this in a clean environment of H5 that it works without having an ID at the end. As it seems, H5 seems to want to have the ID as well, see: https://github.com/hibernate/hibernate-test-case-templates/compare/main...ahus1:hibernate-test-case-templates:is-HHH-xxxx-id-mapping-no-longer-automatically-done?expand=1

I tried to trigger the functionality above via the UI but failed to find the right fields / data setup. 

For now, I'd too assume to fix the SQLs and add the missing `.id`. 

Asking on the Hibernate chat for more information: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/H6.20vs.2E.20H5.3A.20Compare.20entity.20with.20ID.3F

**Comment by ahus1** [comment]
As answered by the Hibernate team: 

> yes, this change was on purpose
> alternative [to using `.id`] is, that you bind the parameter like `.setParameter( "serverId", entityManager.getReference(ResourceServer.class, serverId) )`

**Comment by ahus1** [comment]
Changes merged to Q3 branch
