### ISSUE TITLE
Hibernate 6 upgrade: valueType in `JsonbType` is no longer set

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#16335]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

After migrating to hibernate 6, usages of the `JsonbType` in entities had to be migrated to `@Type` annotations that use a `UserTypeLegacyBridge` to map the `jsonb` type to the actual type that should be used.

After this change, the `JsonbType.setParameterValues` method is no longer called, despite the type implementing `DynamicParameterizedType`. As a result, we no longer get the `valueType`that is needed when deserializing the JSON string into the proper metadata object.

A workaround that was put in place in quarkus3 branch was to put the metadata's class name in the metadata itself, serializing it along with the rest of the entity's attributes. This allows `JsonbType` to obtain the `valueType` when deserializing the JSON string:

```java
        public Object fromString(CharSequence json) {
            try {
                ObjectNode tree = MAPPER.readValue(json.toString(), ObjectNode.class);
                JsonNode ev = tree.get("entityVersion");
                JsonNode mc = tree.get("metadataClass");
                if (ev == null || ! ev.isInt()) throw new IllegalArgumentException("unable to read entity version from " + json);

                Integer entityVersion = ev.asInt();

                tree = migrate(tree, entityVersion);

                String metadataClass = mc.asText();
                valueType = Class.forName(metadataClass);
                return MAPPER.treeToValue(tree, valueType);
            } catch (IOException e) {
                throw new HibernateException("unable to read", e);
            } catch (ClassNotFoundException e) {
                throw new RuntimeException(e);
            }
        }
```

We need to check what is the right approach for this. Ask hibernate team if there's another way to get a reference to the value type. Another options seems to be migrating our custom type to a `UserType`, but needs some experimentation.

### Version

quarkus3 branch

### Expected behavior

`valueType` should be available to the `JsonbType`.

### Actual behavior

`valueType` is not available and code in quarkus3 branch is using an ugly workaround.

### How to Reproduce?

Use quarkus3 branch.

**Comment by ahus1** [comment]
PR merged to the quarkus3 branch.
