### ISSUE TITLE
Keycloak doesn't redirect to client when specifying relative path as valid redirect URIs

### ISSUE THREAD

**Issue by woprandi** [keycloak/keycloak#16331]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

When configuring a client, we can specify relative path as valid redirect URIs. The tooltip says it's relative to the **client root URL** but it's not the current behavior : it's relative to the Keycloak root URL.

![image](https://user-images.githubusercontent.com/1449422/211341974-bbbf7687-5854-42c8-882b-576135a00ea7.png)

![image](https://user-images.githubusercontent.com/1449422/211341520-2fe6877c-a098-4ff9-b13d-4c9c5e477438.png)

### Version

20.0.2

### Expected behavior

With the example above, I should be redirected to `http://localhost:5000/after_login`

### Actual behavior

I'm currently redirected to `http://<KEYCLOAK_URL>/after_login`

### How to Reproduce?

1. Fresh Keycloak install
2. Register a OIDC client like above
3. Try authentification

**Comment by mposolda** [comment]
@woprandi Are you correctly redirected when you add `redirect_uri` to the initial request sent to Keycloak? For example something like `redirect_uri=http://localhost:5000/after-login`

**Comment by woprandi** [comment]
Yes the issue only happens when I don't specify redirect_uri in the initial request.

**Comment by peterstorm** [comment]
Hmm, I'm experiencing the exact same issue. Is there any way to reopen this issue?

**Comment by adamency** [comment]
Also experiencing the issue and this is very much needed as it is the only to use a single `oauth2-proxy` for authentication of multiple apps (i.e. multiple endpoints). Can you please reopen this @mposolda or @stianst ?
