### ISSUE TITLE
Usage of deprecated AngularJS

### ISSUE THREAD

**Issue by drwetter** [keycloak/keycloak#16369]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Keycloak seems to use the deprecated AngularJS version 1.8.3. It is out of support since more than a year, see https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a.

While there seem to be no security bugs known, it's questionable if such a bug will be discovered it'll be fixed upstream. As a result this poses a security risk to keycloak as well.

See also:
* https://owasp.org/Top10/A05_2021-Security_Misconfiguration/: _The software is out of date or vulnerable_
* https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/ : _Monitor for libraries and components that are unmaintained or do not create security patches for older versions._ 

### Version

any

### Expected behavior

use a supported framework

### Actual behavior

uses an unsupported, deprecated framwork

### How to Reproduce?

-

### Anything else?

You might want to consider the references to AngularJS here as well. 
* In [/blob/main/docs/dependency-license-information.md](https://github.com/keycloak/keycloak/blob/main/docs/dependency-license-information.md) there's version 1.4.4 listed https://raw.githubusercontent.com/angular/angular.js/v1.4.4/LICENSE which should be rather https://raw.githubusercontent.com/angular/angular.js/v1.8.3/LICENSE 
* Similar: https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/keycloak/common/resources/lib/angular/version.json

I hope the testsuites which are still using the ~ [9 year old](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1213-romantic-transclusion-2014-02-14) and vulnerable ([see NIST](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:angularjs:angular.js:1.2.13:*:*:*:*:*:*:*)) AngularJS v1.2.13 / (Snyk lists [even more vulns](https://security.snyk.io/package/npm/angular/1.2.13)), don't pose under any circumstances a security problem?

**Comment by ssilvert** [comment]
@drwetter This is one of the reasons we created our new admin console using React.  Right now, Keycloak ships with both the old and new console, but the old one will be removed in a future version.

**Comment by drwetter** [comment]
I really like how thoughtful and considerate you guys address security questions.

**Comment by stianst** [comment]
> I really like how thoughtful and considerate you guys address security questions. 

Not sure what that's supposed to mean, but the old admin console is deprecated and will be removed very soon. With Angular 1 being deprecated I'm not sure else you suggest we do here.

**Comment by drwetter** [comment]
Oh. I am really surprised that I have to explain my comment. How about

* not closing this ticket immediately and thus insinuate to me you sweep a security problem under the rug?
* why didn't you remove the deprecated angularJS a year back when it was non-maintained anymore?
* how about commenting like "the testsuite is no problem, as it'll never be exposed so there's no vector" or "we'll update the testsuite to the latest version for the time being so that it is not 9 years old and full of security problems as we cannot tell for sure that there's no vector"

Take security responsibility of your product! People still use AngularJS on the admin console and it poses a threat. A comment like "we'll remove it in (a future version|very soon)"is like a reply with little content like when a breach occurred and the company notifies their costumers via e-mail beginning "your data is very important to us...."
