### ISSUE TITLE
Inconsistent handling of parenthesis in auth flow name

### ISSUE THREAD

**Issue by jblachly** [keycloak/keycloak#16379]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

auth flow names may be renamed to include parenthesis.

However, when creating a new flow, the API responds with 400 bad request if the flow name field has a parenthesis:

`{"error":"Character '(' not allowed."}`

(side note; right paren is also forbidden, but only the first rejected character is returned in the JSON error message)

### Version

20.0.2

### Expected behavior

Expect that paranthesis are allowed during creation; or disallowed when renaming existing flow

### Actual behavior

Parenthesis are allowed when renaming existing flow, but disallowed during creation

### How to Reproduce?

see description above

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. This has very low priority and has simple workaround (avoid using parenthesis or any other strange characters in the names of various components).

Community contribution is welcome to further investigate and eventually fix this.

**Comment by kaustubh-rh** [comment]
@mposolda , ack will raise a PR for the same

**Comment by jonkoops** [comment]
@mposolda should this not get backported to a patch release as well?
