### ISSUE TITLE
Lack of validation of access token on client registrations endpoint

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#16388]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Hi,

I tried to revoke the access_token generated for the service-account in one of the realms (this client is used for dynamically registering clients using client registration flows) but even after revokation, the token was used succesfully for client registrations as Bearer token type.

Although the /userinfo and /token/introspect endpoints shows me token is invalidated but still the /clients-registrations/openid-connect was able to consume this token and register a new client.

### Version

20.0.2

### Expected behavior

Client registrations using Bearer type authentication request should not be possible with revoked token.

### Actual behavior

Client registrations using Bearer type token with revoked token works.

### How to Reproduce?

* Generate a token for service-account using client_credentials flow
* Revoke the token using /revoke endpoint passing in the above token.
* Now, invoke /clients-registrations/openid-connect passing in the above generated token for auth
* client is created using the token

**Comment by souravs17031999** [comment]
This is really important security fix I was looking forward to. thanks @pedroigor

**Comment by sschu** [comment]
@stianst @pedroigor I was wondering whether this would also be good to backport to 20.0.4?

**Comment by pedroigor** [comment]
@sschu It is available since 20.0.3, no?

**Comment by sschu** [comment]
@pedroigor You are right. Sorry, I missed this.
