### ISSUE TITLE
Reloading the account updated dialog results in the cookie error dialog

### ISSUE THREAD

**Issue by TeJonsch** [keycloak/keycloak#16399]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

After reloading the account update confirmation dialog...
![account_update_confirmed](https://user-images.githubusercontent.com/35114699/211848201-3401db98-e89c-4757-8a62-5522f8bdcc79.png)

the cookie not found error dialog is displayed:
![cookie_error](https://user-images.githubusercontent.com/35114699/211848202-6ef6c11d-c1f3-4e5d-a735-d5ee609897fc.png)

### Version

20.0.1

### Expected behavior

Expected would still be the account update confirmation dialog instead of the error:
![account_update_confirmed](https://user-images.githubusercontent.com/35114699/211848201-3401db98-e89c-4757-8a62-5522f8bdcc79.png)

### Actual behavior

The cookie not found error dialog is displayed:
![cookie_error](https://user-images.githubusercontent.com/35114699/211848202-6ef6c11d-c1f3-4e5d-a735-d5ee609897fc.png)

### How to Reproduce?

Trigger the account update email by the keycloak-admin-client:
```
  public void run(String... args) {
    try (Keycloak keycloak = createKeycloak()) {
      keycloak
          .realm("my-realm")
          .users()
          .get("d6ec997f-ccad-415b-bf43-b45ef057006a")
          .executeActionsEmail(
              "my-client-id",
              "https://my.domain.com/app",
              12 * 60 * 60,
              List.of("UPDATE_PASSWORD"));
    }
  }

  private Keycloak createKeycloak() {
    return KeycloakBuilder.builder()
        .serverUrl("https://my.domain.com/auth")
        .realm("my-realm")
        .username("my-realm-admin@localhost")
        .password("password")
        .clientId("admin-cli")
        .build();
  }
```

After confirming the password change action...
![confirm_action](https://user-images.githubusercontent.com/35114699/211848192-d8a183cd-fdbb-439f-acd8-fdcb95fdc1cc.png)

...and updating the password...
![update_password](https://user-images.githubusercontent.com/35114699/211848197-b7e24fa6-9682-4bbf-92c3-fa7afa6c43ab.png)

...the account update confirmation dialog is displayed:
![account_update_confirmed](https://user-images.githubusercontent.com/35114699/211848201-3401db98-e89c-4757-8a62-5522f8bdcc79.png)

After reloading this page by e.g. F5 or Ctrl+r, the cookie not found error dialog is displayed:
![cookie_error](https://user-images.githubusercontent.com/35114699/211848202-6ef6c11d-c1f3-4e5d-a735-d5ee609897fc.png)

### Anything else?

Link to account update (from the update your account mail):
https://my.domain.com/auth/realms/my-realm/login-actions/action-token?key=__TOKEN__

I left out the token to avoid making it anonymous, too. Please let me known, if it's nevertheless relevant.

====================================

![confirm_action](https://user-images.githubusercontent.com/35114699/211848192-d8a183cd-fdbb-439f-acd8-fdcb95fdc1cc.png)

https://my.domain.com/auth/realms/my-realm/login-actions/action-token?key=__TOKEN__

====================================

![update_password](https://user-images.githubusercontent.com/35114699/211848197-b7e24fa6-9682-4bbf-92c3-fa7afa6c43ab.png)

https://my.domain.com/auth/realms/my-realm/login-actions/required-action?execution=UPDATE_PASSWORD&client_id=my-client-id&tab_id=vp9bXj7L_u4

====================================

![account_update_confirmed](https://user-images.githubusercontent.com/35114699/211848201-3401db98-e89c-4757-8a62-5522f8bdcc79.png)

https://my.domain.com/auth/realms/my-realm/login-actions/required-action?client_id=my-client-id&tab_id=vp9bXj7L_u4

====================================

![cookie_error](https://user-images.githubusercontent.com/35114699/211848202-6ef6c11d-c1f3-4e5d-a735-d5ee609897fc.png)

https://my.domain.com/auth/realms/my-realm/login-actions/required-action?client_id=my-client-id&tab_id=vp9bXj7L_u4

**Comment by prsanjay** [comment]
Hi, I have also faced the same issue. Is there any plan to fix this in near future?

**Comment by ssilvert** [comment]
Moving this to core team as this concerns the required action rather than the account UI.
