### ISSUE TITLE
What is the licensing model of Keycloak

### ISSUE THREAD

**Issue by ajaiswal595** [keycloak/keycloak#16395]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I see Keycloak License is     

                                   **Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/**
                        
                        
But when I saw in keycloak is shipping Keycloak.20.0.1/lib/lib/main/mysql.mysql-connector-java-8.0.30.jar which is of 
**GNU General Public License Version 2.0, June 1991**

Doesn't this affect Keycloak's License?

### Version

20.0.1

### Expected behavior

I'm not sure that we should ship GPL license jar

### Actual behavior

We are shipping GPL license jar

### How to Reproduce?

Check Mysql driver jar license.

**Comment by sschu** [comment]
The mysql connector uses GPLv2 with FOSS exception so it can be redistributed with Keycloak, see https://github.com/mysql/mysql-connector-j/blob/release/8.0/LICENSE and https://oss.oracle.com/licenses/universal-foss-exception/.

**Comment by sschu** [comment]
And please don't file a bug if you just have a question.

**Comment by ajaiswal595** [comment]
Thanks for the answer and noted the suggestion.

I didn't had Idea about this, so instead of bug

What options will be recommended

![Screenshot_2023-01-12-05-39-41-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/8745632/211944979-578f4846-e6f3-4682-a97f-8869be954926.jpg)

Can we open discussion for this kind of ask?

**Comment by sschu** [comment]
@ajaiswal595 I think opening a discussion in Q&A is the best way to go.
