### ISSUE TITLE
Please update antlr-runtime

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#16393]
### Description

Please update the antlr-runtime dependency to current version 

```xml
<dependency>
    <groupId>org.antlr</groupId>
    <artifactId>antlr4-runtime</artifactId>
    <version>4.11.1</version>
</dependency>
```

I didn't check thoroughly where the antlr-runtime 3 is required in keycloak but I replaced it and I couldn't find any features that were broke afterwards. 

The outdated version is causing problems with my SCIM extension which can be fixed by replacing the antlr-runtime within the libs folder but its still inconvenient.

**Comment by sschu** [comment]
Why not provide a PR with that change?

**Comment by Captain-P-Goldfish** [comment]
There seems to be a problem here.
antlr is coming with `io.quarkus:quarkus-jdbc-mssql:jar:2.13.6.Final:compile`. I then wanted to update the antlr-runtime and run the testsuite which runs perfectly fine, no test-errors. I executed: 

```
docker run -p 1433:1433 --env ACCEPT_EULA=Y --env MSSQL_SA_PASSWORD=${DB_PW} --name sql-server-2019 mcr.microsoft.com/mssql/server:2019-latest 

mvn install -Dkeycloak.connectionsJpa.url=jdbc:sqlserver://localhost:1433;database=keycloak;encrypt=false -Dkeycloak.connectionsJpa.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver -Dkeycloak.connectionsJpa.user=sa -Dkeycloak.connectionsJpa.password=${DB_PW}    
``` 

Then I used the same database once...
1. without the antlr-runtime update
2. with the antlr-runtime update

In both cases it seems that keycloak is no longer compatible with mssql. Which would justify the removal of the mssql-jdbc driver. 
I would like confirm this.

**Comment by sschu** [comment]
So you are saying that it does not work independent of the antlr update? Then I would assume it is rather a configuration issue on your side because it still works for us on MS SQL.

**Comment by Captain-P-Goldfish** [comment]
thx, that is what I wanted to know.
I simply have no idea why. I started a brand new database with the docker command above. Created the keycloak database and set the following configuration properties and I only get errors from keycloak after starting it:

```
1. docker run -p 1433:1433 --env ACCEPT_EULA=Y --env MSSQL_SA_PASSWORD=${DB_PW} --name sql-server-2019 mcr.microsoft.com/mssql/server:2019-latest ;

2. create database keycloak

3. db=mssql
db-username=sa
db-password=${DB_PW}
db-url=jdbc:sqlserver://localhost:1433;database=keycloak;encrypt=false
```

is there really anything I could have done wrong there?

**Comment by sschu** [comment]
Have you tried setting `transaction-xa-enabled`to false? Notice this is a build option, see https://www.keycloak.org/server/all-config?q=transaction-xa-enabled.

**Comment by Captain-P-Goldfish** [comment]
and thanks for your suggestion. Disabling xa-transactions did the trick. :-)
