### ISSUE TITLE
Keycloak - Missing data in the userinfo response

### ISSUE THREAD

**Issue by MohammedAdain** [keycloak/keycloak#16403]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

Even after configuring Client scopes which have `client roles` and `realm roles` mappers mapped to them, ref image:
![image](https://user-images.githubusercontent.com/61708483/211900606-765338e1-ef7e-4668-9e23-1480226715e5.png)
and even after toggling `Add to Userinfo` to ON
![image](https://user-images.githubusercontent.com/61708483/211900877-9e8df903-78cb-4771-b8a1-aa465f8bd5d9.png)
the user info doesn't return realm roles as part of the response.
I did add a `realm roles` mapper to dedicated client scope as well and toggled `Add to Userinfo` to ON here too
![image](https://user-images.githubusercontent.com/61708483/211901560-5a80cf9e-dc5e-443c-8f4a-a25f4d58d8c2.png)
but the userinfo still doesn;t return a full response containing roles. One such response after hitting user info endpoint:
```
{"sub":"ccd1ab6c-0c54-4f27-82a9-092376a66cf4","preferred_username":"access_user","given_name":"","family_name":"","email":"access_user@access.com"}
```

### Version

19.0.1

### Expected behavior

The user info should contain `roles ` claims too.

### Actual behavior

One such response after hitting user info endpoint:
```
{"sub":"ccd1ab6c-0c54-4f27-82a9-092376a66cf4","preferred_username":"access_user","given_name":"","family_name":"","email":"access_user@access.com"}
```

### How to Reproduce?

Described in `Describe the Bug` section

### Anything else?

Refs:
1. [https://stackoverflow.com/questions/58584131/keycloak-missing-data-in-the-userinfo-response](https://stackoverflow.com/questions/58584131/keycloak-missing-data-in-the-userinfo-response)
2. [https://stackoverflow.com/questions/57997377/get-the-user-roles-with-the-keycloak-userinfo-endpoint](https://stackoverflow.com/questions/57997377/get-the-user-roles-with-the-keycloak-userinfo-endpoint)

**Comment by robertbakker1** [comment]
Hello,

I have also encountered this on version 20.

After changing the 'Token Claim Name' to something else like 'roles', save it, and then save it back to 'realm.roles', it works for me. Also changed the 'Add to ID Token' toggle and 'Add to access token' toggle a few times.

In the userinfo endpoint I now get the realm.roles field in the response, like this:

```
{
...
"sub":"b4c85c82-a537-4a39-a8bd-6be67b6fa4d9", 
"name":"...",
"realm":{"roles":["offline_access","default-roles-realm","uma_authorization"],
...
}
```

Maybe it helps for you at the moment as a workaround.

**Comment by MohammedAdain** [comment]
Thanks,

> After changing the 'Token Claim Name' to something else like 'roles', save it, and then save it back to 'realm.roles'

I tried this, but it didn't seem to work.

When I toggled off `Add to ID token` and `Add to access token`, it worked for me
![image](https://user-images.githubusercontent.com/61708483/212017420-1b35babe-6d7f-4524-8473-57154f8ba54e.png)

Thanks,
Mohammed Adain

**Comment by jbman** [comment]
Add least in Keycloak 19.0.3 I observed that the initial configuration of the roles mapper looks like this
```
{
	"id": "aa5c5d18-7289-489b-97ae-c893ec53c662",
	"name": "realm roles",
	"protocol": "openid-connect",
	"protocolMapper": "oidc-usermodel-realm-role-mapper",
	"consentRequired": false,
	"config": {
		"user.attribute": "foo",
		"access.token.claim": "true",
		"claim.name": "realm_access.roles",
		"jsonType.label": "String",
		"multivalued": "true"
	}
}
```

However In the new admin console this is displayd with all toggles On (while in old console it is displayed with only "Add to access token" as On).
When I toggled Userinfo off, saved, toggled it on again and saved, then the realm role were correctly added to the userinfo response.

**Comment by MohammedAdain** [comment]
@rmartinc I did try it already, seems to work for me toggling it off and on a couple of times [https://github.com/keycloak/keycloak/issues/16403#issuecomment-1379978703](https://github.com/keycloak/keycloak/issues/16403#issuecomment-1379978703). As pointed out by @jbman , it might be an issue with the new console.
