### ISSUE TITLE
Token endpoint iss error

### ISSUE THREAD

**Issue by yaoguoh** [keycloak/keycloak#16413]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

![image](https://user-images.githubusercontent.com/18107429/212041809-96aeebed-a6e2-4800-8af9-56b5e0c4b91c.png)

### Version

20.0.2

> image quay.io/keycloak/keycloak:20.0.2

### Expected behavior

https to http

### Actual behavior

```shell
curl --location --request POST 'http://127.0.0.1:8080/auth/realms/pharmbrain/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'scope=openid' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'client_id=custom-login-client' \
--data-urlencode 'client_secret=LItTuKqlXvaE9Nys8m74xxxxxxxhSwT' \
--data-urlencode 'username=demo'
--data-urlencode 'username=password'
```

### How to Reproduce?

```shell
curl --location --request POST 'http://127.0.0.1:8080/auth/realms/pharmbrain/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'scope=openid' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'client_id=custom-login-client' \
--data-urlencode 'client_secret=LItTuKqlXvaE9Nys8m74xxxxxxxhSwT' \
--data-urlencode 'username=demo'
--data-urlencode 'username=password'
```

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

As a side-note, it is highly recommended to use `https` everywhere. That's one of the reasons this one has really low priority IMO.
