### ISSUE TITLE
Apple signin with keycloak v19.0.3

### ISSUE THREAD

**Issue by OlivAnno** [keycloak/keycloak#16416]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Nous devons mettre en place une nouvelle version d'une application ios pour intégrer la connexion/création d’un compte utilisateur avec Apple Signin.

Nous utilisons la solution IAM Keycloak (https://www.keycloak.org/), version 19.0.3, pour la gestion du compte
et avons intégré le SDK openid / AppAuth-iOS (https://github.com/openid/AppAuth-iOS) sur l'application pour le connecter à Keycloak.

Nous voulons savoir Comment intégrer Apple signin à Keycloak ?

### Version

19.0.3

### Expected behavior

After login you must be redirected to app ios

### Actual behavior

After login, redirection is broken !

### How to Reproduce?

After login, redirection is broken !

### Anything else?

Nous avons testé les plugins non officiels suivants sans succès 

Apple-social-identity-provider-1.0.2 (https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider)
Apple-identity-provider-1.2.0 (https://github.com/klausbetz/apple-identity-provider-keycloak)

**Comment by stianst** [comment]
Jeg skjønner ikke hva du skriver her
