### ISSUE TITLE
OfflineSessionPersistenceTest times out with session preloading

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#16427]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

`OfflineSessionPersistenceTest.testPersistenceMultipleNodesClientSessionsAtRandomNode` occassionally times out when run in `legacy-jpa+infinispan-offline-sessions-preloading` profile.

### Version

main

### Expected behavior

No timeout

### Actual behavior

Timeout

### How to Reproduce?

Run the following command multiple times:
`mvn test -nsu -pl testsuite/model/ -Dtest=OfflineSessionPersistenceTest#testPersistenceMultipleNodesClientSessionsAtRandomNode -Plegacy-jpa+infinispan-offline-sessions-preloading`

**Comment by hmlnarik** [comment]
Reopening for backport

**Comment by hmlnarik** [comment]
Duplicate of [#11627](https://github.com/keycloak/keycloak/issues/11627)

**Comment by mhajas** [comment]
Completed in #16471
