### ISSUE TITLE
Jakarta implemented in whole Keycloak

### ISSUE THREAD

**Issue by pemko123** [keycloak/keycloak#16436]
### Description

I have changed from Javax to Jakarta and now I can't use the library:
keycloak-server-spi-private-20.0.2.jar

Because this library still uses javax and I don't find a Jakarta version like with the admin-client

### Motivation

Javax moved to Jakarta and it is needed to continue development

**Comment by mabartos** [comment]
@pemko123 Thanks for creating this issue. 

Keycloak migration from JavaEE to JakartaEE is happening within Quarkus 3 upgrade initiative[1] and will most likely be included in Keycloak 22.

[1] https://github.com/keycloak/keycloak/issues/16246

**Comment by mabartos** [comment]
The latest Keycloak 21.1.1 version contains support for Jakarta EE. 

Not relevant anymore. If you find any other related issue, feel free to reopen this.
