### ISSUE TITLE
Keycloak 19.0.1 search from UI bug

### ISSUE THREAD

**Issue by ZazaKumar** [keycloak/keycloak#16443]
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We have a cluster of 2 keyclock instances. There are about a million users in the database PSQL. When searching through the web interface, one of the servers first slows down, then get infinispan errors and finally crashes. LA increases by 5 times.

Nginx logs looks like GET /auth/admin/realms/my_realm/users?briefRepresentation=true&first=0&max=20&search=123456789

In keycloak logs got timeout in queries and infinispan sync

```
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: 2023-01-13 14:48:36,790 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p4-t1) ISPN000136: Error executing command ReplaceCommand on Cache 'offlineSessions', writing keys [a5ea11d7-d799-4ecd-b846-1c30523e1bd6]: org.infinispan.util.concurrent.TimeoutException: ISPN000427: Timeout after 15 seconds waiting for acks. Id=4475494
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at org.infinispan.util.concurrent.CommandAckCollector.createTimeoutException(CommandAckCollector.java:227)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at org.infinispan.util.concurrent.CommandAckCollector.access$600(CommandAckCollector.java:59)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:280)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at org.infinispan.util.concurrent.CommandAckCollector$BaseCollector.call(CommandAckCollector.java:260)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 13 14:48:36 keycloak-02 keycloak[3544260]: #011at java.base/java.lang.Thread.run(Thread.java:829)
```
![image](https://user-images.githubusercontent.com/4714455/212311244-c4724a2f-bc74-476e-a5cb-b7b4cf8c3c54.png)

### Version

19.0.1

### Expected behavior

keycloak service keep working

### Actual behavior

keycloak service fails

### How to Reproduce?

run 2 servers with tcp infinispan, populate about 1 million user and try to search via UI

**Comment by bastianccm** [comment]
Hi @ZazaKumar,

you stated
> I have reproduced the issue with the latest release

however, the latest release is 20.0.3, not 19.0.1. Does this issue still exist in 20.0.3?

**Comment by ZazaKumar** [comment]
@bastianccm my bad. closed
