### ISSUE TITLE
Unable to run docker if built with JDK 17

### ISSUE THREAD

**Issue by martinvisser** [keycloak/keycloak#16441]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

According to https://www.keycloak.org/2022/11/keycloak-2000-released JDK 17 is now supported, which in my mind would mean I should be able to run the docker image with code compiled as JDK 17, but that seems to fail. According to the docker layers only Java 11 is installed, not 17.

[The layers](https://quay.io/repository/keycloak/keycloak/manifest/sha256:c167807890ff63fd10dacef2ab6fd2242487a940ce290a9417a373da66e862e9) show the following line:
```
RUN /bin/sh -c microdnf update -y && microdnf install -y --nodocs java-11-openjdk-headless glibc-langpack-en && microdnf clean all && rm -rf /var/cache/yum/* && echo "keycloak:x:0:root" >> /etc/group && echo "keycloak:x:1000:0:keycloak user:/opt/keycloak:/sbin/nologin" >> /etc/passwd # buildkit
```

During startup this results in a message like `<some class> has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`.

### Version

20.0.3

### Expected behavior

Be able to compile code as Java 17 and be able to run a docker container with Java 17.

### Actual behavior

Unable to start the docker container that uses `RUN /opt/keycloak/bin/kc.sh build`

### How to Reproduce?

Compile a jar with Java 17 bytecode and build Keycloak:
```Dockerfile
FROM quay.io/keycloak/keycloak:20.0
WORKDIR /opt/keycloak

COPY \
    <some-jar-with-java-17-compiled-code>.jar \
    providers/

RUN /opt/keycloak/bin/kc.sh build
```

**Comment by Carmezim** [comment]
Have the same issue, had to modify my container to manually install and set JDK 17 to have that available but then wasn't able to load console.

**Comment by sschu** [comment]
The Keycloak distribution supports Java 17. However, the image is still built with Java 11 so this is just the default as of now. At some point, the provided image will switch to Java 17. But currently, you have to build your own image if you want to use a different Java version. It is designed this way so I would not consider this a bug.

As an alternative, different images could be provided in parallel - this would be an enhancement to the current process.

**Comment by martinvisser** [comment]
@Carmezim Would you be so kind to share how you modified your container?
