### ISSUE TITLE
Expose ready variable in KeycloakAuthorizationInstance interface

### ISSUE THREAD

**Issue by vmichailidisdev** [keycloak/keycloak#16454]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

`KeycloakAuthorization` function returns a `KeycloakAuthorizationInstance` that we can later call providing a `KeycloakInstance`. When `KeycloakAuthorization` is called, background fetch happens. Then we can call `KeycloakAuthorizationInstance.entitlement(serverId, config)` to obtain all entitlements from the Keycloak server. But, we can only call `KeycloakAuthorizationInstance.entitlement(serverId, config)` when `KeycloakAuthorizationInstance` background fetch is completed. `KeycloakAuthorizationInstance` Interface does not provide a way to check if the background fetch is completed. However, as I saw in the implementation (keycloak-authz.js) a `ready` variable is set with the ongoing promise of the background fetch (IF PROMISES ARE SUPPORTED BY THE BROWSER).

### Version

15.1.1

### Expected behavior

`ready` should be exposed in the `KeycloakAuthorizationInstance`.

### Actual behavior

`ready` is not exposed in the `KeycloakAuthorizationInstance`.

### How to Reproduce?

If `KeycloakAuthorization` behind-the-scenes fetch is completed after the `KeycloakAuthorizationInstance.entitlement(serverId, config)` fetch; the Client never receives the RPT token.

**Comment by jonkoops** [comment]
This has been resolved under #34044. And will be backported in a patch release for version 26 (see #34097). With this change is is no longer necessary to use this property though (see PR).
