### ISSUE TITLE
Documentation - Expand/Clarify Admin REST API User Search Functionality

### ISSUE THREAD

**Issue by mattgagliardi** [keycloak/keycloak#16451]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

The documentation around queries for user information via the Admin REST API is incomplete/misleading.

### Version

20.0.2

### Expected behavior

Clear explanations of the behaviors and options available given how the system is configured.

### Actual behavior

Documentation does not present a whole/accurate picture of behaviors/options.

### How to Reproduce?

When an AD/LDAP federation is configured and the sync option is enabled user information is queried and cached in the Keycloak database.  After this it appears that on every query of the Admin API for users (ex. GET /{realm}/users) the result is Keycloak issuing an LDAP query *per user* for user attributes, etc.  If the system has many thousands of users this is not desirable behavior.
On the other hand when an AD/LDAP federation is configured and the sync option is *disabled* the user information is never pulled down from AD to the Keycloak database.  In this case when the same query is run against the API no results (or only users created locally) are returned. However the addition of "?username=*" results in *one* LDAP query (in my case for sAMAccountName=*) with the appropriate...based on the DNs and other options configured in the federation setup...result set.  However the use of the wildcard/asterisk is not documented *and* it does not seem to work if the sync option is enabled.

### Anything else?

Keycloak documentation states "The advantage of synchronization is that all Keycloak features work efficiently because any required extra per-user data is stored locally." [link](https://www.keycloak.org/docs/latest/server_admin/index.html#storage-mode).  However issuing thousands of queries to an AD/LDAP server does not seem to be an efficient method of querying when the scope of the query is fairly large.  Providing expanded documentation in this space might allow users to better understand the ramifications of their configuration choices and how to leverage the options (like the wildcard search in an system not sync'ing) available to them.

**Comment by mattgagliardi** [comment]
Please note that in the above description the ?username= query has an asterisk after the equals sign...Github apparently stripped that out on submission.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
