### ISSUE TITLE
Keycloak Doc.X: Build Antora docs from generated guides

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#16475]
Make a minimal change to the build to show that the downstream docs for Pantheon/ccutil can generated from the Freemarker templates upstream. 

This will do the minimal changes to the Freemarker where necessary to allow the contents to be processed by Antora in the next build step.

**Comment by ahus1** [comment]
@andymunro - I now have a first prototype which on-the-fly uses the Freemarker server guides / cc: @stianst 

I bundled all server guides in an Antora component, and all of them into one master.adoc for the downstream ccutil. 

This determines for upstream the outline of the navigation, and for downstream the table of contents. 

Please advise if you need this split differently. 

Antora / upstream: 
![image](https://user-images.githubusercontent.com/3957921/213196565-df096a21-46a7-4b74-bf6e-9028bc32f575.png)

Downstream / ccutil: 
![image](https://user-images.githubusercontent.com/3957921/213196800-9712c657-8b16-41e0-97e2-9365869ed399.png)

**Comment by andymunro** [comment]
@ahus1 This looks good although I may suggest some refinement of organization.

 However, do you have a complete proposed outline for downstream?  The version hear omits TLS, enabling and disabling features, logging, and several other chapters.

**Comment by ahus1** [comment]
@andymunro / @stianst - there is now PR #16595 with the minimal set of files to create content for downstream, plus the example output as ZIPed files. Let's continue the discussion on the PR.
