### ISSUE TITLE
Use Java cacerts truststore together with additional truststore provided via spi-truststore-file-file parameter

### ISSUE THREAD

**Issue by steadyk** [keycloak/keycloak#16473]
### Description

Add a way to use the Java cacerts truststore together with an additional truststore provided via spi-truststore-file-file parameter.

### Motivation

We currently face the issue that we need to use a truststore to access our internal LDAP. This works fine with the `spi-truststore-file-file` parameter.

We additionally also need to use another identity provider which uses public certificates. This doesn't work, probably since the standard Java cacerts truststore, which holds those public certificates, is not used if we explicitly specify an own truststore.

### Details

Is it possible to use the standard Java truststore together with the additional one provided via spi-truststore-file-file?
Otherwise we would need to use an own container image which does this on top of Keycloak.

The issue #13300 might be related.

**Comment by Hakky54** [comment]
It this maybe what you are looking for? https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#loading-jdk-and-os-trusted-certificates

You can chain jdk/cacerts, system certificates and additional custom trust stores

**Comment by shawkins** [comment]
This is now built into the the new truststore option support in 24: #23742
