### ISSUE TITLE
Identity Provider Mapper -> Claim to Role type does not display all realm roles

### ISSUE THREAD

**Issue by michielpeeters** [keycloak/keycloak#16485]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I'm unable to find a realm role when adding an Identity Provider mapper when using the mapper type: "Claim To Role". When I press the "Select Role" button it does display realm roles, but they are maxed at 11 roles. Other roles are not displayed.

### Version

20.0.3

### Expected behavior

In version 20.0.2 I was able to see all realm roles for selection when I select the button "Select Role" while adding a new Identity Provider mapper.

### Actual behavior

In version 20.0.3 it displays a maximum of 11 realm roles instead of the 16 realm roles that I have defined.

### How to Reproduce?

Within a realm do the following:
1. Add atleast 15+ realm roles to actually see that not all realm roles are loaded
2. Add an OpenID identity provider
3. Click on the just created OpenID identity provider and select the tab "Mappers"
4. Click on "Add Mapper" to add a new mapper
5. Choose "Claim to Role" in "Mapper Type"
6. Click on the button "Select Role" and there are only 11 realm roles displayed instead of the 15+ added from step 1, now I'm unable to select the role which is not displayed.

**Comment by ssilvert** [comment]
@michielpeeters This is working for me.  I seem to remember something like this being fixed recently.  Can you check the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by michielpeeters** [comment]
@ssilvert Ok, ill check it out if its working on the latest build and ill get back to you :)

**Comment by michielpeeters** [comment]
@ssilvert Sorry for my late response. I was able to check it and it seems to be working in the latest nightly build. When will this build being released?

**Comment by jonkoops** [comment]
Thanks for checking this @michielpeeters. This will be fixed in the next major version of Keycloak (version 21). In the mean time you can switch back to the old theme to do this action. You can configure this under 'Realm settings' and then 'Themes'.
