### ISSUE TITLE
Remove `JsonbPostgreSQL95Dialect` from `DatabasePropertyMappers`

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16496]
### Description

With hibernate 6 there is new way to register custom functions, therefore there is no need to specify custom dialect (``JsonbPostgreSQL95Dialect``). 

There is: 
https://github.com/keycloak/keycloak/blob/dceb2f96b274b83c764c2ba8fd98dab16980f757/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java#L189

It should be removed from `DatabasePropertyMappers` and replaced by detecting correct dialect (`PostgreSQLDialect` or `CockroachDialect`). 

Determining correct dialect is important as there is a need to register slightly different function for postgres and cocroach and dialect'd be used for detection.

Note: It'd probably require adding new config options when starting quarkus with map storage.

**Comment by ahus1** [comment]
@vramik - I see that the PR has been merged. GitHub will not close the issue automatically as the PR hasn't been merged to the main branch. 

So I wonder: can this issue be closed?

**Comment by vramik** [comment]
https://github.com/keycloak/keycloak/pull/16498
https://github.com/keycloak/keycloak/pull/16583

**Comment by vramik** [comment]
Blocked by by unavailability of Hiberante 6 in quarkus3: https://github.com/keycloak/keycloak/pull/16549#issuecomment-1408600119

**Comment by vramik** [comment]
Resolved by https://github.com/keycloak/keycloak/pull/16549
