### ISSUE TITLE
Missing roles in users-view

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#16510]
### Describe the bug

The inherited roles from the `admin`-role of the master realm are not displayed within the ui if I open the `Role mapping`-tab of the `admin`-user of the master realm. Not a single inherited role of the master realm is displayed.

### Version

20.0.2

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by rmartinc** [comment]
Hi @Captain-P-Goldfish!

Trying with last version 23.0.5 I created a test realm and I see the associated roles in the admin user.

![Screenshot from 2024-01-29 12-45-21](https://github.com/keycloak/keycloak/assets/26901232/5816ce06-48de-4f6d-82bc-2db52683ab76)

I'm closing this. If you still have the issue in the 23.0.5 version, re-open or file another issue, but please give the exact steps to reproduce the issue using a fresh keycloak installation.
