### ISSUE TITLE
Flaky test: InternationalizationTest.loginFormTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#16515]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

`InternationalizationTest.loginFormTest:90 » ClassCast class com.sun.proxy.$Proxy63 cannot be cast to class org.openqa.selenium.interactions.internal.Locatable (com.sun.proxy.$Proxy63 and org.openqa.selenium.interactions.internal.Locatable are in unnamed module of loader 'app')`

### Version

latest

### Expected behavior

The tests passes

### Actual behavior

The test is throwing an error

### How to Reproduce?

`mvn test -nsu -Pauth-server-quarkus -Dtest=InternationalizationTest#loginFormTest -Dbrowser=firefox -DfirefoxHeadless=true -f testsuite/integration-arquillian/tests/other/base-ui/pom.xml`

**Comment by ssilvert** [comment]
Can we just disable this test for now?  Soon we will be replacing all the account UI tests with Cypress.  Also, there is really nothing in this test that is not tested elsewhere.  The failing line is line 90, which is the login screen.  So it's not part of the account console and should be covered by login tests.  The two assertions on lines 92 and 93 are covered in the previous test on line 78 and 79.  So if we disable this test, I don't think we lose coverage.

See https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/InternationalizationTest.java#LL90C72-L90C72

**Comment by miquelsi** [comment]
Addressed in https://github.com/keycloak/keycloak/pull/16547
