### ISSUE TITLE
/realms/master/protocol/openid-connect/oauth/oob vulnerable to XSS attack

### ISSUE THREAD

**Issue by camiloking** [keycloak/keycloak#16528]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

`/realms/master/protocol/openid-connect/oauth/oob` is vulnerable to XSS attack

run keycloak: `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.3 start-dev`

Visit the following URL:

http://localhost:8080/realms/master/protocol/openid-connect/oauth/oob?error=%3Ca%20href=%22javascript%26%00colon;alert(document.domain)%22%3EReturn%20to%20application%3C/a%3E

Clicking on `return to application` runs the script. 

### Version

20.0.3

### Expected behavior

Script in url does not run after clicking return to application.

### Actual behavior

Script in url is run after clicking return to application.

### How to Reproduce?

run keycloak: `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.3 start-dev`

Visit the following URL:

http://localhost:8080/realms/master/protocol/openid-connect/oauth/oob?error=%3Ca%20href=%22javascript%26%00colon;alert(document.domain)%22%3EReturn%20to%20application%3C/a%3E

Clicking on `return to application` runs the script.

**Comment by thomasdarimont** [comment]
Problem seems to be here: [OIDCLoginProtocolService.java#L260](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocolService.java#L260)

**Comment by mposolda** [comment]
This should be already fixed in latest Keycloak 21.0.1, so I am closing.

BTV. When you're reporting security issues, please don't report them here in public. Pleae follow the instructions from: https://www.keycloak.org/security.html
