### ISSUE TITLE
Bug Implementing External Authentication Using Action Tokens

### ISSUE THREAD

**Issue by sashokbg** [keycloak/keycloak#16536]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Hello, I am implementing an external authentication SPI following more or less the following example : 

https://github.com/keycloak/keycloak-quickstarts/tree/latest/action-token-authenticator

I also have configured a step-up authentication using ACR / LOA as described in the documentation: 

https://www.keycloak.org/docs/latest/server_admin/#_step-up-flow

### Version

20.0.2

### Expected behavior

The following scenario works fine:

**Given** I have NOT logged in
**When** I initiate a step-up auth using the following URL
http://localhost:9900/realms/my-realm/protocol/openid-connect/auth?client_id=my-client&redirect_uri=http%3A%2F%2Flocalhost%3A8095%2Fconfiguration%2Fmessage-types&scope=openid&response_type=code&response_mode=query&nonce=exg16fxdjcu&acr_values=**sensitive**
**Then** everything works as expected (form auth -> external auth -> redirect to token handler -> redirect to app)

### Actual behavior

My problem is the following:

Given I have already logged in using the classic username password flow
When I initiate a step-up auth using the following URL
http://localhost:9900/realms/my-realm/protocol/openid-connect/auth?client_id=my-client&redirect_uri=http%3A%2F%2Flocalhost%3A8095%2Fconfiguration%2Fmessage-types&scope=openid&response_type=code&response_mode=query&nonce=exg16fxdjcu&acr_values=**sensitive**

Then I get redirected to the "You are already logged in page" instead of my app.
It seems the token handler is not called at all.

### How to Reproduce?

1) Run the following example https://github.com/keycloak/keycloak-quickstarts/tree/latest/action-token-authenticator

2) Configure conditional flow as described here https://www.keycloak.org/docs/latest/server_admin/#_step-up-flow

3) Run a backend app configured with spring boot

4) Try logging in first only with username / password

5) Then request elevated ACR that uses external auth provider (from 1)

6) Error - You are already loggedin 

### Anything else?

Technical details:

Keycloak:

   | Keycloak 20.0.2
   | JVM: 11.0.17 (Red Hat, Inc. OpenJDK 64-Bit Server VM 11.0.17+8-LTS)
   | OS: Linux 6.1.1-arch1-1 amd64

The error comes from this code found in LoginActionsServiceChecks.java, called in LoginActionsService#executeActionToken

```
     if (tokenAuthSessionCompoundId != null) {
                // This can happen if the token contains ID but user opens the link in a new browser
                String sessionId = AuthenticationSessionCompoundId.encoded(tokenAuthSessionCompoundId).getRootSessionId();
                LoginActionsServiceChecks.checkNotLoggedInYet(tokenContext, authSession, sessionId);
            }
```

My auth flow:

![image](https://user-images.githubusercontent.com/10643824/213498129-2988b098-a9b9-4768-9466-654a029857f2.png)

**Comment by sashokbg** [comment]
I found how to circumvent the issue.
It seems some already had this issue using action tokens for managing external "required actions" since in the code I saw an explicit IF statement that checks if the list of required actions is not empty.

https://github.com/keycloak/keycloak/blob/761929d1746c4d8445014a1124c27e9c07ca7725/services/src/main/java/org/keycloak/services/resources/LoginActionsServiceChecks.java#L121

What I did in my code is to add a required action to my user in the **authenticate** method of my SPI implementation. 

        user.addRequiredAction(TEMP_REQUIRED_ACTION_ACR);

And then in my **action** method I remove it:

        user.removeRequiredAction(TEMP_REQUIRED_ACTION_ACR);

This seems hacky though and without diving in the code it is impossible to know why the action token is not working.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue).

**Comment by opdt** [comment]
We have the same issue when using step up authentication with an authenticator redirecting to an external app. Would checking if we are in an "step up context" inside LoginActionsServiceChecks be a sufficient fix for this? If yes, we would be happy to send a PR.
