### ISSUE TITLE
Run a performance test to understand characteristics XA vs non-XA driver

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16532]
### Description

It'd be useful to have some understanding whethere there is a performace impact when running XA vs non-XA driver on quarkus on postgres. 

Currently is is only possible to run server with XA driver when using legacy store (with map store there is hardcoded non-XA driver). 

On legacy store `transaction-xa-enabled` property is set to `true` [1].

https://www.keycloak.org/server/db

**Comment by kami619** [comment]
The tests yielded no difference in the performance between xa and non-xa transactions on legacy store.
