### ISSUE TITLE
event.ipAddress behind reverse proxy is set to private IP

### ISSUE THREAD

**Issue by EvgeniGordeev** [keycloak/keycloak#16543]
### Description

Better handle IP address in LOGIN_ERROR emails sent to end user. When KC is deployed to a Kubernetes cluster `event.ipAddress` is populated with [request.remoteAddress().host()](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java#L113) which returns a private IP from internal k8s network.

LOGIN_ERROR emails should provide actual public IPs of end users trying to log in. 

### Details

Something like 
```java

private static final List<String> IP_HEADERS = Arrays.asList("X-Forwarded-For", "X-Real-IP","HTTP_X_FORWARDED_FOR");

public String getRemoteAddr() {
    return IP_HEADERS.stream()
        .map(request::getHeader)
        .filter(Objects::nonNull)
        .filter(ip -> !ip.isEmpty() && !ip.equalsIgnoreCase("unknown"))
        .findFirst()
        .orElseGet(request::getRemoteAddr::host);
}
```

**Comment by shawkins** [comment]
Resolving as out of date. The QuarkusClientConnection is backed by HttpServerRequestRequest that utilizes the ForwardedParser which will handle X-Forwarded-For if proxy-headers=xforwarded. 

Please open an enhancement if you need support for considering X-Real-IP or HTTP_X_FORWARDED_FOR.

**Comment by shawkins** [comment]
Actually the QuarkusClientConnection is backed by the Vertx ForwardedParser, not the Quarkus one, so it does not report the values based upon the headers.

**Comment by shawkins** [comment]
Please excuse the noise. Double checked the implementation, and the vertx forwarded parser is backed by the quarkus one, so this is working as expected. In the case of https passthrough you may need to enable the PROXY protocol to get the remote address - #33276
