### ISSUE TITLE
Additional authorization request parameters shouldn't be limited to 5 and shouldn't be discarded silently 

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#16545]
### Description

Keycloak allows to process custom URL parameters for an OAuth2 authorization request.

This is implemented in https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java

This class has a hard-coded limit of 5 request parameters. Any more parameters are silently discarded with a debug log entry:
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java#L131

### Expected

- More than 5 custom URL parameters are supported
- Fail fast: Exceeding a limit doesn't silently discard a parameter but fails the request.

### Proposal

- Don't limit number of parameters but total custom parameters size to 5*2.000=10.000 characters. This limit should also include the parameter names which are allowed to have large size, currently.
- Fail request (IllegalArgumentException) if byte size is exceeded: "Additional OIDC URL parameter names and values must exceed the limit of 10.000 characters" 

### Motivation

When more than 5 custom parameters are passed by a client an extension might not receive an important parameter sent by the client. Also a brokered OIDC Identity Provider might not be called with the full set of parameters sent by the client. OIDC providers could easily expect more than 5 custom parameters (e.g. Keycloak also has custom ones like kc_idp_hint).
The extension or target IdP will not behave as expected by the client, if parameters are swallowed. Such an error is hard to track down, as the limit doesn't fail the authorization request.

**Comment by mschallar** [comment]
While I like the idea of a fail-fast response, you should make sure to at least parse the `redirect_uri` to be able to redirect the user back to where he came from. This will enhance the user experience greatly.

But I also think that the OpenID Provider should be able to define the maximum number of additional parameters, as well as the maximal size of parameters. If you take a look at my issue/PR at https://github.com/keycloak/keycloak/issues/25006 you will see that I implemented it.

About your code:

1. The `int[0]` exists just to be able to deal with the `forEach` loop as the variable has to be `final`?
2. https://github.com/bosch-io/keycloak/commit/397067b301bb0adc09b136517425ee42350b9601#diff-4b5c5902048bb9c8042baecafcd09b8800baba90f72f538bb0132208bf7c95e3R56 a space is missing before `ADDITIONAL_REQ_PARAMS_MAX_CHARS`.
3. It would be nice if your code supports a realm-specific configuration of maximum allowed number of characters, and/or a maximum number of parameters number (see https://github.com/keycloak/keycloak/pull/25007).

**Comment by jbman** [comment]
Thanks for the feedback.
1. Yes.
2. Yes, in exception message text, good find!
3. I'm in favor of saving the admin from configuration here. My main issue is that the default of 5 allowed params is much to low. An overall limit on the value size would fix it for all cases where the URL hasn't an unreasonable length. And the default of 12000 here would be on the safe side regarding support of very large URLs.

**Comment by mposolda** [comment]
Closing this as it was already addressed by #25006 . Please create follow-up issue if there are more use-cases not covered by that one.
