### ISSUE TITLE
kc.sh start command is failing if keystore/hostname specified

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#16556]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Description:

The command bin/kc.sh start is failing.

It is expecting to have at hostname/keystore to proceed succesfully.

### Version

20.0.3

### Expected behavior

The default kc.sh start command should work.

In comparison, it has always been possible to RH-SSO/Keycloak (before version 16), where it was possibel; to connect to localhost 8443

 Therefore, it would to populate the conf file with a default keystore and local hostname.

===> This would allows to have the same and consistent bhaviour as before. 

### Actual behavior

bin/kc.sh start
ERROR: Unexpected error when starting the server in (production) mode
ERROR: Failed to start quarkus
ERROR: Strict hostname resolution configured but no hostname setting provided
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

### How to Reproduce?

NA

### Anything else?

Na

**Comment by vmuzikar** [comment]
@orivat Thanks for the report. This is by design actually. With the new distribution we're enforcing secure by default policy, i.e. you need to configure hostname and TLS by default in prod. For dev purposes you can run `start-dev` instead of `start` which has different (more permissive) default settings.
