### ISSUE TITLE
Need to be able to  encrypt keystore as truststore password in config

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#16557]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

The keystore password is provide in clear text in the config

cat cat myprod.conf
cat: cat: No such file or directory
# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
#db=postgres

# The username of the database user.
#db-username=keycloak

# The password of the database user.
#db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
#db-url=jdbc:postgresql://localhost/keycloak

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
hostname=localhost

https-key-store-file=/home/orivat/dev/keycloak-x-investigations/keycloak-20.0.3/conf/keycloak.jks

https-key-store-password=password

### Version

20.0.3

### Expected behavior

Need to provide keystore password being encrypted

### Actual behavior

NA

### How to Reproduce?

NA

### Anything else?

NA

**Comment by vmuzikar** [comment]
@orivat Thanks for the report. We believe it will be fixed by https://github.com/keycloak/keycloak/issues/15831. I'm closing this one. Feel free to reopen if you think otherwise.
