### ISSUE TITLE
Second factor security key redirection upon cancellation, wrongfully indicates error.

### ISSUE THREAD

**Issue by iokasti** [keycloak/keycloak#16550]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

`
![326449487_1220249058570532_280542639065418197_n](https://user-images.githubusercontent.com/20352699/213690736-cd88dfe4-2f35-4d09-9a91-83d2f62d4ae6.jpg)

On second factor authentication when the user is prompted to use their security key, if they click cancel, they are redirected to the error message as indicated in the attached image.

### Version

19

### Expected behavior

A possible option could be to restart the process of second factor or present the other possible authenticating methods.

### Actual behavior

Second factor error for security key.

### How to Reproduce?

While on second factor authentication click on Cancel when asked for security key.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
