### ISSUE TITLE
Quarkus 3: RealmModelTest.testRealmLocalizationTexts fails

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#16551]
BLOCKED: see https://github.com/keycloak/keycloak/issues/16551#issuecomment-1400633351

### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

The `org.keycloak.testsuite.model.RealmModelTest.testRealmLocalizationTexts` test fails in the quarkus3 branch in `legacy-jpa` profile

### Version

quarkus3

### Expected behavior

Test passes

### Actual behavior

Test fails

### How to Reproduce?

Run the test in `legacy-jpa` profile

### Anything else?

https://github.com/keycloak/keycloak/actions/runs/3966487788/jobs/6799050521

**Comment by ahus1** [comment]
Workaround, maybe even the final fix prepared in a draft PR. Will now write a reproducer and raise this to the Hibernate team as I didn't find this in the release notes of H6.

**Comment by ahus1** [comment]
Asking in the Hibernate chat: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user

Reproducer test case: https://github.com/hibernate/hibernate-test-case-templates/compare/main...ahus1:hibernate-test-case-templates:is-HHH-xxxx-attribute-converter-dirty-checking?expand=1

**Comment by ahus1** [comment]
Created Hibernate issue: https://hibernate.atlassian.net/browse/HHH-16081

The first pull request for this issue adds a workaround for Hibernate 6. This issue should stay open to track the progress in the Hibernate project.

**Comment by ahus1** [comment]
This will be available in Hibernate 6.2.0 (not released yet)

**Comment by ahus1** [comment]
This is part of Hibernate 6.2.0.CR3

**Comment by ahus1** [comment]
With the Quarkus 3 branch being now on Hibernate 6.2.0.CR4 which includes this change, the workaround can now be removed. Starting to work on this.

**Comment by ahus1** [comment]
Merged to the Quarkus 3 branch.
