### ISSUE TITLE
Error Message with keycloak auth page request

### ISSUE THREAD

**Issue by sagarguptay2j** [keycloak/keycloak#16567]
### Description

Can we pass error_message along with redirect_url,state,client_id,nonce and response_type in params while requesting to auth url (https://keycloak/realms/{realm-name}/protocol/openid-connect/auth), so in case of any failure we can redirect user to the keycloak login page with the custom error message
Sorry if this feature already exist i am having hard time to figure out how to do this

**Comment by abstractj** [comment]
@sagarguptay2j for questions, please consider using the keycloak-user's mailing list https://groups.google.com/g/keycloak-user.
