### ISSUE TITLE
Setting user password and entering "password confirmation" first leads to blocking of "save"

### ISSUE THREAD

**Issue by zzador** [keycloak/keycloak#16577]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Try setting a password for a user and enter the "password confirmation" field first and then "password" afterwards. Even if both password are exactly the same the app says "Password and confirmation does not match." and won't let you save.

Sure it is not the expected workflow to first fill "password confirmation" but in my case a made a typo in the first password field and I went back to correct it just to see that the app doesn't care for my correction.

Please make sure that BOTH fields get the necessary validation listeners assigned to.

### Version

20.0.3

### Expected behavior

Regardless of the order of input both password fields should be checked for match.

### Actual behavior

Only on inputing into the "password confirmation" field leads to check for match.

### How to Reproduce?

Type in the "password confirmation" first and then in the "password" field.

**Comment by jsorah** [comment]
The initial save of the password appears to be fixed in 21.1.1, however, the issue still exists in the "Reset password" dialog.

![image](https://user-images.githubusercontent.com/4944041/236836313-52333bb4-6c86-4bd4-9d64-97b96fd18cbd.png)

**Comment by ssilvert** [comment]
I tried it and for me, the error message does not go away but at least it let me save.
