### ISSUE TITLE
Can't run multiple instances in the same machine

### ISSUE THREAD

**Issue by inad9300** [keycloak/keycloak#16589]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I have a dockerized application where Keycloak has its own container based on `quay.io/keycloak/keycloak:20.0.3`. When running multiple instances of this application (via Docker Compose), logging in in one of them logs me out of the other one. These are applications deployed in different port ranges in the same physical machine.

### Version

20.0.3

**Comment by sschu** [comment]
Can you provide exact steps to reproduce?

**Comment by inad9300** [comment]
After some investigation, I can say that this is most likely because all instances use the same cookie name, and cookies aren't port specific (see https://stackoverflow.com/a/16328399/2018219). If that were the case, reproducing it should just be a matter of running two Docker Keycloak instances side-to-side in different ports, and using a browser to log in to the first, then the second, and observing how you are no longer logged into the first.

**Comment by jonkoops** [comment]
Not really sure what can be done about this as [RFC 6265](https://www.rfc-editor.org/rfc/rfc6265#section-1) pretty clearly states the following:

> For historical reasons, cookies contain a number of security and privacy infelicities.  For example, a server can indicate that a given cookie is intended for "secure" connections, but the Secure attribute does not provide integrity in the presence of an active network attacker.  Similarly, cookies for a given host are shared across all the ports on that host, even though the usual "same-origin policy" used by web browsers isolates content retrieved via different ports.

Basically this is cookies 'working as intended'.

**Comment by inad9300** [comment]
Well, the usage of cookies itself, and how you make use of them, is Keycloak's decision, isn't it? :smile: The question really is, should Keycloak be able to run alongside Keycloak in the same machine? I'm obviously arguing that it should, and if you agree too, then the appropriate technical means to do so should be found, and if cookies don't cut it, then something else should be used, instead of just falling back to "can't do it, sorry, blame the cookies!"

That said, I think cookies can still be used. A couple ideas: the current cookie(s) could be used to store information about different Keycloak instances, having a structured value able to identify the specific instance each sub-value applies to. Alternatively, the cookie names could be customized at boot time to avoid conflicts (e.g. ask for a custom prefix or assign one at random). Just my two cents.

**Comment by jonkoops** [comment]
I don't see how we can get around using cookies as that is integral to how the integration with OpenID Connect works. If you have a proposal on how to OpenID Connect without cookies feel free to do so.

Right now this is simply not a priority as we have many, many more issues to take care of (see our GitHub backlog). So I doubt we can do anything about this soon. 

Feel free to write up a proposal or submit a PR on how this should be handled.

**Comment by inad9300** [comment]
That I understand. You do indeed have quite a challenge to manage all these issues. The general expectation towards Dockerized applications is that they are independent from one another; I wish making this a reality was more of a priority for you, but oh well.

Perhaps something doable is to document this limitation, at least, together with possible workarounds, if any... With Docker being all over the place these days, I can't imagine that I'm the only one that has tried running two Keycloak-depending applications at the same time (this could be two instances of the same application, like in my case, but also two completely unrelated applications, really).

**Comment by sschu** [comment]
As a workaround, you could use different aliases for localhost in your /etc/hosts. Not ideal but should work.

**Comment by mposolda** [comment]
@sschu @jonkoops Thanks for your comments when investigating this!

This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this. Right now, it seems to me that only thing, which can be done might be to improve the docs as suggested by @inad9300 . If you want to send PR to improve the docs on this, it is welcome!

**Comment by stianst** [comment]
This is not a bug for sure. It's expected behaviour, and has been this way for a long time.

Having multiple KC instances running on different ports that are not related are very much a corner case.

Use different hostnames, different realms, etc. if this is really what you need.

That being said we might be open for a contribution, but only one that finds a nice and clean solution, which I doubt there is.

**Comment by Paul-E** [comment]
I ran into this issue when trying test configuration for getting two instances of keycloak to federate with OIDC. I was able to get both running by adding a line to my etc hosts:

```
127.0.0.1 keycloak.local
```

And then I start one keycloak with 

```
docker run -p 127.0.0.1:8090:8080 --network YYY_MY_NETWORK_NAME_HERE --name keycloak-upstream -e KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true  -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin -e KC_HOSTNAME="http://keycloak.local:8090" quay.io/keycloak/keycloak:26.4.7 start-dev
```

and access it by navigating to http://keycloak.local:8090. `YYY_MY_NETWORK_NAME_HERE` is the name of the docker network
