### ISSUE TITLE
Investigate using HotRod client transaction for locks

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#16601]
While working on using HotRod tx I also tried to use it for locks. However, the `putIfAbsent` did not work the way we need for the GlobaLock provider.

See this test:
```java
@Test
    public void testLocksWithTx() {
        IntStream.range(0, 200).parallel().boxed()
                .map(i -> new TransactionController(getFactory()))
                .peek(TransactionController::begin)
                .peek(tx -> {
                    tx.runStep(session -> {
                        RemoteCache<String, String> locksCache = session.getProvider(HotRodConnectionProvider.class).getRemoteCache("locks");
                        session.getTransactionManager().enlist(new HotRodRemoteTransactionWrapper(locksCache.getTransactionManager()));
                        System.out.println(locksCache.withFlags(Flag.FORCE_RETURN_VALUE).putIfAbsent("k1", "v1"));
                        return null;
                    });
                })
                .peek(TransactionController::commit)
                .forEach((i) -> System.out.print(""));
                ;
    }
```
If we comment line `session.getTransactionManager().enlist.....` it works, however, if we initialize HotRod client transaction it doesn't work anymore.

### The expected output is:
```
null
v1
v1
.... (all following threads get v1)
```

### What we get:
```
null
null
null
null
null
null
v1
v1
... (all following threads get v1)
```

From the above, it seems `putIfAbsent` is not visible to other threads before commit, which is probably correct so we may not be able to use HotRod transaction with locks.

### Something else
With current implementation (before [13280](https://github.com/keycloak/keycloak/issues/13280)), Infinispan server is complaining about this:
```
2023-01-24 17:06:59,496 WARN  (non-blocking-thread--p2-t7) [org.infinispan.server.hotrod.HotRodHeader] ISPN006010: Conditional operation 'PUT_IF_ABSENT' should be used with transactional caches, otherwise data inconsistency issues could arise under failure situations
2023-01-24 17:06:59,497 WARN  (non-blocking-thread--p2-t7) [org.infinispan.server.hotrod.HotRodHeader] ISPN006011: Operation 'PUT_IF_ABSENT' forced to return previous value should be used on transactional caches, otherwise data inconsistency issues could arise under failure situations
```

To make this warning disappear it is enough to make the cache transactional, we do not need to use HotRod transaction.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
