### ISSUE TITLE
Replace DB connection product name with Liquibase-provided databaseShortName

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#16617]
In JpaMapUtils:
https://github.com/keycloak/keycloak/blob/54c34dc75b4bdf9f5dd8de08f7e39e8e475c9aae/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/JpaMapUtils.java#L193-L194

we load the database name from the DB connection. This should be replaced by Liquibase-provided `databaseShortName` similarly as it was done in this PR: https://github.com/keycloak/keycloak/pull/16524.

See https://github.com/keycloak/keycloak/pull/16524#discussion_r1081117159 for more details.

**Comment by hmlnarik** [comment]
Legacy store will not be affected, only map-JPA storage.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
