### ISSUE TITLE
Make lockTimeout better configurable in JpaMapStorageProviderFactory

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#16616]
#15890 Introduced a new config option for `JpaMapStorageProviderFactory` that configures how long the execution should wait for acquiring the pessimistic lock.

However, there was no default value configured so it can result in a deadlock. As part of this issue, we should investigate what is the best way to configure this. We should have some default value, but we also need to have the possibility to disable this as it is possible to configure global timeout on the database level. 

We should add this configuration also to Quarkus config.

In model tests, we set the `lockTimeout` value to 1000ms which may be low for some tests and can result in instabilities. We need to add some way to configure this per test case. We will need something like this:
1. Configure `lockTimeout` to some env property
2. At the beginning of the test store the original property value and replace it with some custom value
3. Reinitialize Keycloak factory
4. Do the test
5. Reset property to the original value
6. Reinitialize again

**Comment by ahus1** [comment]
Looking at the code I have the some more comments:

As there is no default, the message shows on each transaction when JPA map storage is enabled: "Database ... used without lockTimeout option configured. This can result in deadlock where one connection waits for a pessimistic write lock forever."  

TODOs:

* Ensure that the warning log message is create only once per Keycloak startup or per instance of JpaMapStorageProviderFactory?
* Implement "getConfigMetadata()" so the configuration option turns up on https://www.keycloak.org/server/all-provider-config

As there as are lot of warnings, at least that part should raise the priority of this issue. Maybe we could even fix the logging part for KC21. 

@mhajas: I leave it for you  to update the milestone if you agree.

**Comment by mhajas** [comment]
@ahus1, thank you for pointing this out. I think you are right, the warning with each request is not very nice, we should probably tackle this asap. I will assign 21 milestone

**Comment by ahus1** [comment]
@mhajas - if we think it is too big for `21.0.0` to do all of this, we could to at least the minimum to prevent the warning (which could be fore example setting a default).

**Comment by hmlnarik** [comment]
Have a default value of 10 seconds.

**Comment by hmlnarik** [comment]
Should this be rather part of a `Config` (see `ProviderFactory.init(Config)`) than env property
