### ISSUE TITLE
Service Account can't access User Info Endpoint

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#16610]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

This relates to the issue [#16168](https://github.com/keycloak/keycloak/issues/16168)

I have 2 clients, X and Y.
X obtains an access token from Keycloak via "Service accounts roles".
X then sends a request to Y containing the access token as authorization bearer header.
Y tries to validate the received access token.

In the attempt to validate the access token, the oidc-lib used in Y requests the user-info-endpoint from Keycloak (to match the access token sub against the user-info-endpoint sub).
This request fails, because the access token does not contain the required "scope=openid" param.

As I have already described in [my comment](https://github.com/keycloak/keycloak/issues/16168#issuecomment-1403283260) on issue #16168:
The underlaying problem seems to be a mix between the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html) and the plain [oAuth spec](https://www.rfc-editor.org/rfc/rfc6749).

According to OIDC, upon login the scope param is mandatory and must contain 'openid'.
However, the Keycloak "Direct access grants" and "Service accounts roles" are not specified by OIDC.
Those are the oAuth "Resource Owner Password Credentials Grant" and "Client Credentials Grant" respectively.
And according to oAuth, the scope param is optional.

An OIDC login flow always starts with the client sending a request to Keycloaks authorization-endpoint.
At this endpoint, one can make the "scope=oidc" mandatory.

The mentioned oAuth login flows however start with the client sending a request to Keycloaks token-endpoint.
At this endpoint, making the scope param mandatory does not comply with any spec....

### Version

20.0.3

### Expected behavior

Access tokens obtained by Keycloaks "Direct access grants" and "Service accounts roles" should also be usable to request the user-info-endpoint.

I suggest making "openid" the default scope of these two authorization flows, even if the scope is not specified in the client request.

### Actual behavior

Access tokens obtained by Keycloaks "Direct access grants" and "Service accounts roles" are not usable to request the user-info-endpoint.

### How to Reproduce?

1. Use Keycloaks "Direct access grants" or "Service accounts roles" to obtain an access token.
2. Try to request the user-info-endpoint using said access token

**Comment by sschu** [comment]
The user info-endpoint is OIDC, client credentials and username password grant are pure OAuth2. So accessing the user info endpoint with these grants is at least not covered by any spec. So I am not sure this needs to be supported, but it could be. Was this working before?

**Comment by ch-lepp** [comment]
It was working before pull [#14237](https://github.com/keycloak/keycloak/pull/14237).
This pull changed the user-info-endpoint to require the "scope=openid"

**Comment by mposolda** [comment]
Duplicates #16844 

Please use that issue for further discussions/concerns around this. Closing this one
