### ISSUE TITLE
Increase the default iterations for Pbdkdf2-256/512 to match the updated OWASP recommendations

### ISSUE THREAD

**Issue by wvdhaute** [keycloak/keycloak#16629]
### Description

As is mentioned @ https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2 the new recommendations would be to have 600k for sha256 and 210k for sha512.

Right now the defaults is still 27.5k and 30k respectively.

Ignoring the fact that users can specify a custom password policy on their own
It seems to me that it would be advisable to push them to sane recommendations.

### Motivation

In detail it would require to update the DEFAULT_ITERATIONS constant in Pbkdf2Sha256PasswordHashProviderFactory and Pbkdf2Sha512PasswordHashProviderFactory.

Sorry for not finding the time on doing this myself in a pull request

**Comment by solardiz** [comment]
I suggest to at least consider switching the default from `pbkdf2-sha256` to `pbkdf2-sha512` at the same time. The latter is 2x+ slower to crack on GPUs/FPGAs/ASICs at same iteration count, allowing for the lower recommended iteration counts.

On 64-bit CPUs with native code, these are of similar speed per iteration, so it's a 2x improvement for defender vs. attacker when switching to SHA-512 in there. However, I don't know how efficient or not current Java VMs/JITs are at 64-bit code (and I see that Bouncy Castle implements SHA-512 in Java code), so someone involved with the project (which I'm currently not) could want to benchmark this first.

**Comment by wvdhaute** [comment]
Sorry but don't see what your point has anything to do with this issue.
I am concerned about the default hash iterations policy applied to the Pbkdf2 providers.
Which is way off what OWASP nowadays recommend.

To be clear, off course I fully agree to just go for sha512 if you have the choice :)

**Comment by solardiz** [comment]
> Sorry but don't see what your point has anything to do with this issue.

Both would be changes of defaults in the same area, and I think can reasonably be made at once. Also notice how OWASP's recommended iteration count for `pbkdf2-sha512` is much lower than for `pbkdf2-sha256`, so if the changes are made at once then the likely-worse performance impact of `pbkdf2-sha256` at 600k iterations would not affect anyone even temporarily.

I don't mind treating these as separate issues/tasks, though. Moreover, long-term there's a third task anyway - introduce a sequential memory-hard password hashing algorithm, the easiest of which would be scrypt as it's already in Bouncy Castle and previously proposed in #121.

**Comment by wvdhaute** [comment]
Sorry @solardiz I misread your comment completely. Fully agree

**Comment by mposolda** [comment]
Adding to 23 for now.

This is surely not a blocker and we can postpone, but can be nice to at least start some discussion about this (maybe on security mailing list) to doublecheck what we should do.

**Comment by pedroigor** [comment]
I think @solardiz has a good point and changing only the iteration might not be the best default from a security and performance perspective, in case we can save a few CPU usage.

**Comment by thomasdarimont** [comment]
FYI I created https://github.com/keycloak/keycloak/pull/25949 with the suggested changes.

However, one thing to note here is that the new password hashing policies take effect in the following cases:
1) when a password is updated or created
2) when a realm local user performs a password based login (!), see https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/credential/PasswordCredentialProvider.java#L194

I think (2) could lead to unexpected load for Keycloak systems where a lot of users sign in at the same time in bulk, as the hash is takes longer to compute.

**Comment by solardiz** [comment]
> I think (2) could lead to unexpected load for Keycloak systems where a lot of users sign in at the same time in bulk, as the hash takes longer to compute.

I think this is not limited to (2). Either the new settings are affordable or they are not, no matter exactly when they start to be used for users. The rehashing is supposed to be not much more costly than authentication (with the new settings), and only done once per user.

A previously unmentioned (here) concern with such updates on live systems is that it becomes possible for a remote attacker to determine (via timing an invalid password attempt) whether a user's password was recently set/changed/rehashed or not (which given (2) means ability to determine whether the user logged in after the Keycloak update or not). There's no good solution to this, it's a trade-off between these different security properties, which could be worth documenting in release notes.

**Comment by pedroigor** [comment]
@mposolda @stianst What is your take here? There is a PR and it is initially targeted for Keycloak 25+.

**Comment by ahus1** [comment]
The measurements and documentation updates around this for KC24 were unfortunately wrong, and there is now a follow-up issue to update the docs: #27900
I'm really sorry about this mistake. Please track the other issue for the progress to update the docs.
