### ISSUE TITLE
keycloak.v2 admin console doesn't have Federation Link on User page

### ISSUE THREAD

**Issue by EvgeniGordeev** [keycloak/keycloak#16624]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Federation Link field is gone from User page in `keycloak.v2` theme. 

### Version

20.0.3

### Expected behavior

Federation Link is displayed and leads to User federation provider

### Actual behavior

Users created through User federation don't have this link any more in `keycloak.v2` theme.

### How to Reproduce?

* Add User federation provider
* Login with a User from User Federation Provider
* Check User page in admin console using keycloak.v2 admin theme

**Comment by jsorah** [comment]
Hi, thanks for the report. I believe this should be fixed in Keycloak 21 based off of this issue https://github.com/keycloak/keycloak/issues/17919

I tested it in 21.1.1 and was able to see the User Federation link.

![image](https://github.com/keycloak/keycloak/assets/4944041/cf0705c8-98c9-43bd-bfe0-d6d8695b9bc2)

**Comment by EvgeniGordeev** [comment]
@jsorah I can confirm that the link is there but it points to ldap configuration even though in our setup it is a custom user federation: 
<img width="757" alt="Screenshot 2023-05-31 at 2 50 47 PM" src="https://github.com/keycloak/keycloak/asset

<img width="709" alt="Screenshot 2023-05-31 at 2 53 06 PM" src="https://github.com/keycloak/keycloak/assets/3843966/2f933289-3425-45d2-aae1-33389135b392">
s/3843966/1ead66c5-5291-4fc8-a966-5a65111897ea">

The actual link is `http://localhost:9080/auth/admin/master/console/#/realm/user-federation/user-federation-provider-name/44e92f9f-3441-4aa4-903e-aa761b0bb02a`

**Comment by edewit** [comment]
that has been fixed as well with #20211 @EvgeniGordeev could you try with the nightly?
