### ISSUE TITLE
Search on user first or last name with multiple tokens gives no results

### ISSUE THREAD

**Issue by eedzjee** [keycloak/keycloak#16638]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

When searching in the admin console on users, some users I would expect to be found don't show up in the results. This happens for example when the first- or lastname of a user consists of multiple tokens separated by whitespace. For example: "Albert Jan" as first name or "de Bruin" as last name. Searching on the whole name doesn't give result, even though the display name (first- + lastname) is exactly the string you're searching for.

The documentation on the 'search'-paramater states that it is "A String contained in username, first or last name, or email", but when investigating the code, it looks like the search is [tokenized based on whitespace](https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L801), each token is [appended with a '%' ](https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L1070) and [each of the tokens must be found](https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L802) in [one of the fields username, email, firstname or lastnames](https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L1073).

The problem is with appending the tokens with '%'. This way the `LIKE` query won't find the third token in the lastname.

 

### Version

20.0.3

### Expected behavior

I would expect to find all users with last name "de Bruin" by searching for that exact same string.

### Actual behavior

I only find users where the tokens "de" and "Bruin" are **both** found in **values that start with that token** in one of the fields username, email, first name or last name.

### How to Reproduce?

Prerequisites:
Keycloak 20.0.3, JPA database (Postgres)
There is a realm with two users:

User 1:
- Firstname: Kees
- Lastname: de Bruin
- Email: debruin@foo.com

User 2:
- Firstname: Kees
- Lastname: de Bruine
- Email: bruine.kees@foo.com

- Go to the admin console -> users
- Search for 'Kees de Bruin' -> only user 2 shows up in the results
- Search for 'Kees Bruin' -> only user 2 shows up in the results
- Search for 'Kees de' -> both users show up in the results

**Comment by rmartinc** [comment]
@eedzjee Yes, it's exactly as you describe. But note that, if the whole string is passed as the `search` parameter, a search for "John Doe" will find no one. Now a user with firstName "John" and lastName "Doe" is returned. And that's a big change IMHO. So, at least for me, it's not clear what we should do here. Remember that you can change the comparison, passing for example "\*de\* \*bruin\*" in the console, you do a contains comparison that would return your user.

**Comment by KevinMordijck** [comment]
A suggestion to solve this issue, is to not only append with % but als do a prefix for each token with %.

**Comment by eedzjee** [comment]
@rmartinc I would expect the search to work like @KevinMordijck also describes by adding the wildcards on both sides of the search tokens. Of course we can change our api to query with the asterisks as you describe, but I it is strange I can't find the right user when I type the full name out of the box. Now it says that the user is not found when I search for "Kees de Bruin", while that is exactly the name of the user. This leads to administrators searching for users and not being able to find them right away. And thinking they don't exist, for example in the case where a user needs to be removed or disabled in a system.
