### ISSUE TITLE
Failed to load AsciiDoc document - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by brianpark928** [keycloak/keycloak#16631]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

Error when building keycloak.

Thanks for letting us know how to solve it.

=======================================================================

[INFO] Keycloak Guides .................................... FAILURE

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.249 s
[INFO] Finished at: 2023-01-26T18:14:54+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc (server-asciidoc-to-html) on project keycloak-guides: Execution server-asciidoc-to-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc failed: org.jruby.exceptions.RaiseException: (ArgumentError) asciidoctor: FAILED: D:/project/workspace/keycloak/docs/guides/target/generated-guides/server/index.adoc: Failed to load AsciiDoc document - invalid byte sequence in UTF-8 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

### Version

20.0.3

### Expected behavior

BUILD FAILURE

### Actual behavior

An error occurred during build, so it cannot proceed any further.

### How to Reproduce?

mvn -gs D:\project\workspace\keycloak\settings.xml clean install -DskipTests

**Comment by kereis** [comment]
I got this error when building Keycloak from source, too. It looks like a Windows issue. I tried to build the docs after setting the following in the docs `pom.xml`:

```xml
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
```
It's failing regardless.

However, the module `docs` builds sucessfully on WSL 2 with Ubuntu 20.04.1 LTS.

**Comment by jsorah** [comment]
Hi there, thanks for the report. 

I believe setting `set MAVEN_OPTS="-Dfile.encoding=UTF-8"` before trying to build Keycloak on Windows may get you past some of those build errors you noticed, but that may only expose more areas that would need to be addressed.

Since most of the build system and the Keycloak team are using *nix-like OSes, I'm moving this one to the backlog. I think it would be great if someone who primarily develops on Windows could pick this up and contribute a cross-platform fix for it.

**Comment by stianst** [comment]
Closing this as out of date. If you are still having this issue please open a new issue.
