### ISSUE TITLE
Missing implementation for ProtocolMapper.getPriority

### ISSUE THREAD

**Issue by jonnytest1** [keycloak/keycloak#16648]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

slightly similar to https://github.com/keycloak/keycloak/issues/15222

we have a protocolmapper that when a certain attribute is set on the user sets/overwrites an attribute in the token via UserAttributeMapper however it seems that on different installations this behaves differently as the order of the protocolmappers is different

i did some research and found the org.keycloak.protocol.ProtocolMapper interface which is a base class of UserAttributeMapper  which provides the getPriority interface 

however it is never 

### Version

20.0.1

### Expected behavior

provide an api to change the priority of protocol mappers

### Actual behavior

the priority of protocol mappers cannot be changed

### How to Reproduce?

setup a keycloak instance

**Comment by mposolda** [comment]
duplicates #15222
I am closing as a duplicate. Please continue in the other issue for the further discussions/questions/suggestions around this.

I can add that method `getPriority` is currently defined per "implementation", but it is not configurable. The workaround might be to create your own subclass (but note protocolMappers SPI is unsupported and can change anytime) and override the `getPriority` method according your needs.
