### ISSUE TITLE
Label for "Review Profile config" modal is not displayed properly in new admin console

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16658]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

This is issue in the main codebase related to https://github.com/keycloak/keycloak-ui/issues/3707 (as some changes may be needed also in the main codebase)

### Version

20.0.3

**Comment by jonkoops** [comment]
Re-opening this issue for the reasons mentioned in https://github.com/keycloak/keycloak-ui/issues/3707#issuecomment-1409040597

**Comment by mposolda** [comment]
Related discussion: https://github.com/keycloak/keycloak/discussions/16882 .

Based on the discussion so far, we may return already translated labels and helpTexts from the admin REST API, so admin console doesn't need to care about localization.

The translation of the `labels` and `helpTexts` can be done at the level of admin REST API (EG. `ServerInfoEndpoint`). So individual authenticators can still use something like `myOption.setLabel("myOptionLocalizationKey")` for the individual options they use and the endpoint itself is responsible for the translation.

**Comment by pedroigor** [comment]
@mposolda Could you please check if we can close this issue as per comments and linked issues?
