### ISSUE TITLE
Keycloak login with non-admin user - "go to home page" is redundant

### ISSUE THREAD

**Issue by GurjotGrewal123** [keycloak/keycloak#16654]
### Description

Once you login to keycloak with a non-admin user, you will be redirected to the following url: https://xxxx:9090/auth/admin/master/console/ 

This will show the following page which is expected:
![image](https://user-images.githubusercontent.com/83552764/214927500-6e012807-df37-42c6-a50c-413329cd5f87.png)

However, the link "go to home page" redirects back to the SAME page. Instead it should redirect to a more useful page. 

EDIT:

A similar situation still occurs after upgrading. Clicking the link redirects to the same page aswell as clicking the "x" on the right.
![image](https://user-images.githubusercontent.com/83552764/216155964-5ef94da0-375e-4b64-8106-77cc3a15d608.png)

**Comment by mvk37** [comment]
In latest Keycloak 24.0.2 behavior changed. But still it is not user friendly.  When I got to admin console http://localhost:8080/admin/ and trying to login by user who doesn't have admin privileges I see an empty screen and spinning wheel which is spinning forever. 

On background HTTP GET http://localhost:8080/admin/serverinfo call returns '403 - Forbidden', which is correct. But could you look how to show it on the screen in a user readable form?

**Comment by jonkoops** [comment]
Closing this as it's a bug report or an enhancement request filed as a task. If this remains an issue please file a report using the correct template.

**Comment by mvk37** [comment]
Created https://github.com/keycloak/keycloak/issues/28753
