### ISSUE TITLE
User Session Count Limiter bypassed when user has actions

### ISSUE THREAD

**Issue by regilero** [keycloak/keycloak#16663]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

User session count limiter filter is not applied when the user has some required actions on the authentication login form submissions.

### Version

20.0.3

### Expected behavior

When trying to log from two different browser with the same account, a user session count limiter set to 1 should block one of the two logins.

### Actual behavior

If there's a stored action on the user (CGU validation, password reset, etc.) and if you performe the login on two different browsers, you get the action shown on the two sessions. After validation of the action you have two valid SSO session. The user session count limiter filter has not been applied.
Any other attempt would still be blocked, but we ended up with 2 valid sessions when only 1 should be allowed.
If think the limiter should be applied *after* the requested action. Opening two sso session and having to make the requested action twice in that case seems OK. But not having the session limiter is not OK.

### How to Reproduce?

* Create a test realm
* add a test client, maybe confidential
* create an authentication workflow, clone of Browser. Add user session count limiter under User name password form. Double check the alignement, it *must* be on the same level as the password form and conditional OTP.
![Capture d’écran de 2023-01-27 09-36-59](https://user-images.githubusercontent.com/809883/215043714-7b6da647-ca44-4f18-ab04-52dd569a09a8.png)
* set it to required, edit configuration to allow only 1 session
![Capture d’écran de 2023-01-27 09-37-05](https://user-images.githubusercontent.com/809883/215043699-815e7f44-3aa3-4467-afd4-343d7157498b.png)

* edit the client and under advanced settings use this new authentication flow
* menu authentication, tab "required actions", allow "terms and conditions" (note that you can test with password reset actions instead of terms and conditions if you want, but to test terms and condition this step is required)
* create a user, force password.
* connect an application to this realm
* test the login with the user, using two different browsers. The second browser is blocked
* that was expected, this is the **ok** state
![Capture d’écran de 2023-01-27 09-45-02](https://user-images.githubusercontent.com/809883/215047424-72b8a5a2-05e4-41a1-b429-14421c93d051.png)

![Capture d’écran de 2023-01-27 09-44-15](https://user-images.githubusercontent.com/809883/215047037-8517de4b-de4c-4f29-a90e-ce8505377445.png)

* logout the connected session
* get back to the first state, with login form on both windows
* add terms and conditions validation action on the user. Save the user.
![Capture d’écran de 2023-01-27 09-46-02](https://user-images.githubusercontent.com/809883/215047339-ce3f1133-a8f0-46ae-bf68-b4019c76dda2.png)

* login on both windows
* You obtain two parallel required actions
![Capture d’écran de 2023-01-27 09-47-13](https://user-images.githubusercontent.com/809883/215047291-df0d3361-1834-4ed4-a6a2-35573e76df27.png)

* validate on both.
* You obtain two sessions. This is **not ok**.

![Capture d’écran de 2023-01-27 09-47-43](https://user-images.githubusercontent.com/809883/215047586-b3155f81-0201-481d-93e2-255018646dc2.png)

### Anything else?

Tested on 18.02 and 20.0.3.

**Comment by mposolda** [comment]
@regilero Thanks for the report. This is the corner case, but will be nice to fix. On the other hand, not seeing any trivial way to fix this.

We likely have few possibilities for fixing like:

- Query also for authenticationSessions and make sure that (userSessions + authSessions) <= limit . If not, then also kill some existing authSessions (or this one authSessions) in addition to userSessions. Problem is, that we don't have in API the use-case like `getAllAuthenticationSessionOfUser(String userId)` 

- Do something different and make sure that this authenticator is changed to some kind of "interceptor", which would be triggered at the end of the authentication flow (after all required-actions are finished). But this will need to add another type of "entity" to the authentication flows and change the API.

**Comment by vanuj** [comment]
Hi, I am able to get this working by updating these configs, but the error message does not appear incase of Terminating oldest session option selected. It show the error message on screen if I select "Deny new session" option.
<img width="570" alt="image" src="https://github.com/keycloak/keycloak/assets/9960088/77baffe8-e445-4eb8-963a-d5371e2e4be3">

Any help is appreciated.

**Comment by chatchaisi** [comment]
![Screenshot 2567-03-26 at 11 10 31](https://github.com/keycloak/keycloak/assets/1871499/ba200ae7-5e63-46b7-973a-978ab16770c9)
Are you set "Client > Advance > Authentication flow overrides Override realm authentication flow bindings." 

It work on version 21.1.2

**Comment by tiagoolifel** [comment]
Hi, I duplicated the built-in browser flow and added the session limiter, when I set it to required the login fails (invalid username/password), 'maxxxx' is my test custom response, but that also does not show.
![image](https://github.com/keycloak/keycloak/assets/131689968/4e1c7d83-9fab-4ba9-af1c-0cdb3c24cec8)

**Comment by kuckchuck96** [comment]
> Hi, I duplicated the built-in browser flow and added the session limiter, when I set it to required the login fails (invalid username/password), 'maxxxx' is my test custom response, but that also does not show. (Version 24.0.2)
> 
> ![image](https://github.com/keycloak/keycloak/assets/131689968/4e1c7d83-9fab-4ba9-af1c-0cdb3c24cec8)
> 
> 
> 
> 
> 
> 

Even I am facing the same issue. It's not event working in my case.

**Comment by BradNut** [comment]
This should probable not be closed if it is still an issue. Do you still have this issue @regilero?
