### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest#testPersistenceMultipleNodesClientSessionsAtRandomNode

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16671]
## org.keycloak.testsuite.model.session.OfflineSessionPersistenceTest#testPersistenceMultipleNodesClientSessionsAtRandomNode
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/3994036682/jobs/6851401076) / [Pull Request #16478](https://github.com/keycloak/keycloak/pull/16478)

```
java.lang.AssertionError: 
threads didn't terminate in time: [main (TIMED_WAITING): locked on java.util.concurrent.FutureTask@77fc5ab7 waiting for 96147 ms blocked for 0 ms
	at java.base@11.0.17/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.17/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.17/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:444)
...
```

**Comment by mhajas** [comment]
The PR https://github.com/keycloak/keycloak/pull/17504 did not resolve this issue completely. 

It was meant to clean the environment after failure so the consequent attempts have a higher probability of success. Therefore I am reopening this issue so we still see how often is this test repeated.

**Comment by martin-kanis** [comment]
I wasn't able to reproduce this locally nor in [20 GHA runs](https://github.com/martin-kanis/keycloak/actions/runs/5266667685/jobs/9521209385). I'll monitor this for a week or so. if this re-appear.
