### ISSUE TITLE
cannot open admin console after upgrade to 20.0.3

### ISSUE THREAD

**Issue by clockrun** [keycloak/keycloak#16684]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I'm upgrading keycloak from 16 to 20. I noticed that if I manually selected and saved theme to `keycloak` in realm setting, it will be saved in table `realm`. Then after upgrade to version 20, because this theme is not there any more, an error saying `index.ftl cannot be found` will occur and admin console cannot be open from browser.

I have to manually clear theme column in table `realm` where its value is `keycloak` to make it work again. This shall be handled automatically in keycloak upgrade script to reduce such puzzle.

### Version

20.0.3

### Expected behavior

upgrade doesn't require manual work for known configuration migration

### Actual behavior

after upgrade to 20.0.3, keycloak try to load old theme and cannot find them 

### How to Reproduce?

define `keycloak` as theme in table `realm` and run version 20

**Comment by sschu** [comment]
@clockrun Even on latest master, the old theme still exists and can be used. Can you check your feature configuration if you have still enabled this feature (it is deprecated now).

**Comment by jonkoops** [comment]
@ssilvert is this something we need to take action on? Perhaps a database migration is required for v21?

**Comment by sschu** [comment]
If the theme is finally removed, there should be a migration switching to `keycloak.v2` or `keycloak` should effectively point to the v2 theme.

**Comment by jonkoops** [comment]
In that case I am adding this to the release for v21 as a reminder. I do believe we are still on track to remove the old UI.

**Comment by jonkoops** [comment]
(note we should still discuss what the best approach is for this is)

**Comment by ssilvert** [comment]
@jonkoops There is a migration script and we could make it part of that process to forcibly change `keycloak` to `keycloak.v2` in the database.

Whatever we decide, it should be done as part of https://github.com/keycloak/keycloak/issues/15247.   So I'll add a note to that issue and close this one.
