### ISSUE TITLE
Allow to run HTTP only in production

### ISSUE THREAD

**Issue by ondrejsika** [keycloak/keycloak#16688]
### Description

Be able to run Keycloak without TLS in a production configuration, not only in dev.

### Motivation

If you want to run Keycloak in Kubernetes, it's much easier to terminate TLS on ingress or load balancer, there is no need to run Keycloak with TLS.

You don't need to handle any TLS certificate by Keycloak backend and you can manage certificates some standard way (cert-manager, AWS ALB, ...)

Now, I'm using a self-sign dummy cert behind my valid TLS on Kubernetes Ingress, so I think, the Kubernetes setup will be easier and more convenient.

**Comment by raphisuter** [comment]
Hi @ondrejsika 
There is the possibility to do that when you configure a reverse proxy in keycloak.conf file. Maybe de "edge" configuration is what you are looking for. Check out https://www.keycloak.org/server/reverseproxy

**Comment by stianst** [comment]
http has to be explicitly enabled in prod mode, and you can configure this with the proxy mode as mentioned
