### ISSUE TITLE
Hibernate 6 referencing m:n association from both entities with both `joinColumns` and `inverseJoinColumns` causes interference

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16693]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

It seems that associations referenced from both related entities causes interference. According to my tests Hibernate 6 removes the entry from join table in case it is not added to both collections. There are following entities in legacy store. 

```java
public class ScopeEntity {
    ...
    @ManyToMany(fetch = FetchType.LAZY, cascade = {})
    @JoinTable(name = "SCOPE_POLICY", joinColumns = @JoinColumn(name = "SCOPE_ID"), inverseJoinColumns = @JoinColumn(name = "POLICY_ID"))
    private List<PolicyEntity> policies;
    ...
}
```

```java
public class PolicyEntity {
    ...
    @OneToMany(fetch = FetchType.LAZY, cascade = {})
    @JoinTable(name = "SCOPE_POLICY", joinColumns = @JoinColumn(name = "POLICY_ID"), inverseJoinColumns = @JoinColumn(name = "SCOPE_ID"))
    private Set<ScopeEntity> scopes;
    ...
}
```
When there is added an object into one collection and not to both, it seems the object is inserted and then removed during the commit.

### Version

quarkus3

### Expected behavior

org.keycloak.testsuite.admin.FineGrainAdminUnitTest passes.

### Actual behavior

org.keycloak.testsuite.admin.FineGrainAdminUnitTest fails.

### How to Reproduce?

run org.keycloak.testsuite.admin.FineGrainAdminUnitTest with quarkus3 branch

### Anything else?

We actually always use one side of the relationship only.

**Comment by ahus1** [comment]
Closing this issue as PR was merged to Quarkus3
