### ISSUE TITLE
Doublecheck if we need to override properties in java.security

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16702]
So far, we have few properties overriden when running with `kc.java.security` file in our testsuite. But it is possible that we don't need to override almost anything and we can still achieve everything working. This issue is about doublecheck the overriden properties in `kc.java.security` and eventually skip overriding most of the properties in this file and also make sure that people don't need to override most of the properties in their own custom manually `java.security` properties file.

Right now, the `kc.java.security` file from testsuite override those:

1) It adds `XMLDSig` security provider, which is needed for SAML. This needs to be present right now and there is separate task for it #16326 . Due to this, we would still need to have custom `kc.java.security` property files, but possibly with all the other properties removed/commented in this file with the exception of this one (See below).
 
2) The properties:
```
keystore.type=PKCS12
fips.keystore.type=PKCS12

ssl.TrustManagerFactory.algorithm=PKIX
fips.ssl.TrustManagerFactory.algorithm=PKIX
```
already have same values like the default `JAVA_HOME/conf/security/java.security` from OpenJDK17 on FIPS enabled RHEL VM. So hopefully we can just comment those properties in our `kc.java.security` ?

3) The property:
```
ssl.KeyManagerFactory.algorithm=PKIX
fips.ssl.KeyManagerFactory.algorithm=PKIX
```
has different value than default `JAVA_HOME/conf/security/java.security`. When this property is removed from the `kc.java.security` file, then some X.509 tests and authorization-adapter tests are failing (see my comment below).

So this task is mostly down to the investigation of the last property (3).

Can we just manually set this property programatically somewhere in `FIPS1402Provider` initialization with `Security.setProperty("ssl.KeyManagerFactory.algorithm", "PKIX");` ? Or would it have any bad side-effect if we do this? It will be good to doublecheck why the `X.509` tests and authorization-adapter tests are failing when this property is not overriden. Could this be related to the fact that the other party is using older algorithms for it's keys during SSL handshake? Or some completely different reason?

**Comment by mposolda** [comment]
NOTE: When commenting this property in `kc.java.security` :
```
ssl.KeyManagerFactory.algorithm=PKIX
fips.ssl.KeyManagerFactory.algorithm=PKIX
```
Then authorization adapter tests (EG. LifespanAdapterTest) are starting to fail.

Note that LoginTest, AccessToken, DemoServletsAdapterTest are still OK. The property `ssl.KeyManagerFactory.algorithm` is the only security property, which is not default. Actualy:
- Property `keystore.type` is set to `PKCS12` by default in OpenJDK 17 in both FIPS and non-fips environment.
- Property `ssl.TrustManagerFactory.algorithm`  is set to `PKCS12` by default in OpenJDK 17 in both FIPS and non-fips environment.

**Comment by daurrutia** [comment]
Thanks for all your work on this. Really, thank you!

I don't know much about Java, much less BouncyCastle.

I'm seeing this with the same BCFIPS versions as listed in pom.xml AND when creating BCFKS store types for the keystore and truststore:

```
keycloak_1  | 2023-02-06 21:27:13,399 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak_1  | 2023-02-06 21:27:13,400 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.RuntimeException: Unable to start HTTP server
keycloak_1  |   at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:758)
keycloak_1  |   at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:318)
keycloak_1  |   at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1866188241.deploy_0(Unknown Source)
keycloak_1  |   at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket1866188241.deploy(Unknown Source)
keycloak_1  |   at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
keycloak_1  |   at io.quarkus.runtime.Application.start(Application.java:101)
keycloak_1  |   at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
keycloak_1  |   at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
keycloak_1  |   at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
keycloak_1  |   at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
keycloak_1  |   at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
keycloak_1  |   at picocli.CommandLine.access$1300(CommandLine.java:145)
keycloak_1  |   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
keycloak_1  |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
keycloak_1  |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
keycloak_1  |   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
keycloak_1  |   at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
keycloak_1  |   at picocli.CommandLine.execute(CommandLine.java:2078)
keycloak_1  |   at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
keycloak_1  |   at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
keycloak_1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
keycloak_1  |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1  |   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
keycloak_1  |   at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
keycloak_1  |   at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
keycloak_1  | Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'int org.bouncycastle.asn1.ASN1Integer.intValueExact()'
keycloak_1  |   at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
keycloak_1  |   at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
keycloak_1  |   at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:724)
keycloak_1  |   ... 25 more
keycloak_1  | Caused by: java.lang.NoSuchMethodError: 'int org.bouncycastle.asn1.ASN1Integer.intValueExact()'
keycloak_1  |   at org.bouncycastle.asn1.cms.CCMParameters.<init>(Unknown Source)
keycloak_1  |   at org.bouncycastle.asn1.cms.CCMParameters.getInstance(Unknown Source)
keycloak_1  |   at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.decryptData(Unknown Source)
keycloak_1  |   at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
keycloak_1  |   at java.base/java.security.KeyStore.load(KeyStore.java:1479)
keycloak_1  |   at io.vertx.core.net.impl.KeyStoreHelper.loadKeyStore(KeyStoreHelper.java:237)
keycloak_1  |   at io.vertx.core.net.KeyStoreOptionsBase.getHelper(KeyStoreOptionsBase.java:187)
keycloak_1  |   at io.vertx.core.net.KeyStoreOptionsBase.getTrustManagerFactory(KeyStoreOptionsBase.java:217)
keycloak_1  |   at io.vertx.core.net.impl.SSLHelper.getTrustMgrFactory(SSLHelper.java:383)
keycloak_1  |   at io.vertx.core.net.impl.SSLHelper.lambda$init$0(SSLHelper.java:204)
keycloak_1  |   at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
keycloak_1  |   at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
keycloak_1  |   at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
keycloak_1  |   at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
keycloak_1  |   at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
keycloak_1  |   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak_1  |   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
keycloak_1  |   at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak_1  |   at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak_1  |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak_1  |   at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1  | 
keycloak_1 exited with code 1
```
Then I found this [comment](https://stackoverflow.com/a/74340291/7742737) that `ssl.KeyManagerFactory.algorithm=PKIX` needs to be configured.

Then I found this open issue.

I don't see the error when using PKCS12 store types.

Do you think my observed error is related to this issue?

**Comment by mposolda** [comment]
@daurrutia Your issue is likely not directly related to this. I think it is more about the fact that there are both BCFIPS and BC jars on the classpath. I think this is already fixed in latest Keycloak main. Could you please try to check with latest Keycloak main or with latest Keycloak nightly build ZIP archive? It's here: https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by rmartinc** [comment]
@mposolda I tested and you are right, there are only two modifications for default `java.security` file in the RHEL jdk to make the tests pass:

* The `fips.provider.7=XMLDSig` which is just because that provider is still being check for inclusion and it's needed for SAML tests.
* The default KeyManagerFactory property value `ssl.KeyManagerFactory.algorithm=SunX509`. This problem is simple, openjdk implements for KeyManagerFactory the following algs: SunX509, NewSunX509 and PKIX ([here](https://github.com/openjdk/jdk/blob/jdk-17-ga/src/java.base/share/classes/sun/security/ssl/SunJSSE.java#L85-L96), two algs with one alias) and BCJSSE implements X.509, X509 and PKIX (only one impl with two aliases).

And the problem is that if the default `SunX509` in the file is selected there is no corresponding alg from BCJSSE and it triggers issues later on. I think the simplest idea is just forcing the names when teh BCJSEE is loaded if the configured alg is not present in BCJSSE (over [here](https://github.com/keycloak/keycloak/blob/20.0.3/crypto/fips1402/src/main/java/org/keycloak/crypto/fips/FIPS1402Provider.java#L75-L78)). I'm testing right now but I think it will work.

**Comment by mposolda** [comment]
@rmartinc Cool, Thanks!
