### ISSUE TITLE
Failing tests due to outdated X509Certificate request attribute name

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16721]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

There are several tests failing due to `javax.servlet.request.X509Certificate` is used instead of `jakarta.servlet.request.X509Certificate` in quarkus3 branch

### Version

quarkus3

### Expected behavior

Tests passes without error.

### Actual behavior

NPE due to attribute is not found.

### How to Reproduce?

Run e.g. HoKTest in quarkus3.

**Comment by ahus1** [comment]
merged into Q3 branch, closing.
