### ISSUE TITLE
Dependency reviews

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16733]
### Description

Umbrella task for review of 3rd party dependencies in Keycloak. In general:
- Can we remove some of them?
- Can we replace some of them with better alternatives? Ideally ones, which is coming from Quarkus and already productized in RH?
- If not removed or replaced, can we upgrade some of them to newer versions? Is it something needed from the "productization perspective" in such case?

### Issues

- #16729
- #16730 
- #16731 
- #16732
- #11706

**Comment by mposolda** [comment]
@pskopek twitter4j was updated to 4.1.2. Related commit is [f8f112d8d27ef255346a0be366294b2514721b23](https://github.com/keycloak/keycloak/commit/f8f112d8d27ef255346a0be366294b2514721b23)

**Comment by pskopek** [comment]
Thanks @mposolda I will build it internally.
