### ISSUE TITLE
Upgrade twitter4j (WAS: Dependency review: twitter4j)

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16731]
### Description

Twitter4j is used in Keycloak for integration with Twitter IDP. This task is to review if twitter4j dependency can be removed entirely.

The point is, that at the time when we added support for Twitter IDP, Twitter did not have support for OAuth 2/ OIDC. However now Twitter has support for it (at least for OAuth2 AFAIK). So this is to doublecheck if we can make Twitter IDP to inherit directly from `OIDCIdentityProvider` or `AbstractOAuth2IdentityProvider` and leverage the existing OAuth2 / OIDC functionality and get rid of twitter4j.

Migration: If we get rid of twitter4j, is it any "migration" needed for the twitter users? For example do they need to update their "application configuration" on Twitter side? If the Twitter integration stop working for existing deployments (without any action needed for users), then we may likely need some "deprecation period" and "migration strategy". But if any update on user's application is not needed, we can likely update our twitter integration right away and get rid of twitter4j.

**Comment by rmartinc** [comment]
@mposolda Can I work on this? Thanks!

**Comment by mposolda** [comment]
@rmartinc Question: If we update directly Twitter provider from "v1" to "v2", will the Twitter login still work for those migrating from previous Keycloak version? Or do they need to change anything in the application configuration on Twitter side (in "Twitter Application Management") or in Keycloak side? If they don't need to change anything, then I am in favour of directly update our provider to "v2" .

However the fact that email doesn't work in `v2` is not ideal because then we have a regression in functionality. Is it possible to retrieve email somehow by some magic call to some "v1-api-endpoint" even if all the rest stuff will use `v2` API?

So my view is:
If we migrate Twitter IDP and login will just work (without any change needed on the config on both Keycloak and Twitter side) and if we can retrieve email, then we can directly replace current provider with OAuth2 and remove dependency on twitter4j. Otherwise, we may need to keep both providers, but deprecate the `v1` provider (in both documentation and admin console) with the note that we will remove it in some future Keycloak version. So in this case, we will need to keep using twitter4j if I udnerstand correctly. So in this case, we will also need to update twitter4j to latest version.

**Comment by pedroigor** [comment]
@rmartinc Did you see https://next-auth.js.org/providers/twitter#oauth-20?

I also tried to find references as I was curious about some scope we could use when sending authorization requests, but I did not find any. Or even a specific endpoint, I don't know.

I found this https://next-auth.js.org/providers/twitter#oauth-20. Stating that email is not supported by v2? Perhaps there are some privacy concerns behind this and you need something else to allow your client to access the email from accounts.

**Comment by rmartinc** [comment]
> Question: If we update directly Twitter provider from "v1" to "v2", will the Twitter login still work for those migrating from previous Keycloak version?

No, it won't. The v1 is using Api Key and Api Key Secret while the v2 needs the Client ID and the Client Secret, which are different data. Although the same app can use v1 or v2 the configuration should be changed from one data set to the other.

> Is it possible to retrieve email somehow by some magic call to some "v1-api-endpoint" even if all the rest stuff will use v2 API?

The v1 API cannot be used with an OAuth2 header. If you call the `verifyCredentials` endpoint with a bearer token generated using OAuth2 the following error is returned:

```
Using OAuth2 in verifyCredentials endpoint:
Caused by: org.keycloak.broker.provider.IdentityBrokerException: failed URL in twitter: {
  "title": "Forbidden",
  "type": "about:blank",
  "status": 403,
  "detail": "You are not permitted to use OAuth2 on this endpoint"
}
```

@pedroigor The different scopes are listed in [this doc page](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code). Then each v2 API endpoint specifies which scopes are required (for example the `me` endpoint needs `tweet.read` and `users.read`). But I didn't find anyone that returns the email of the authorized account. The `me` endpoint can be called to return more fields but never the email. In v1 `verifyCredential` with email requires a special config option that doesn't even appear in v2. Besides in this [stack-overflow thread](https://stackoverflow.com/questions/74271337/how-to-obtain-users-email-via-twitter-api-v1-or-v2) someone says that is really not provided in v2 and that twitter is (or was) working in providing it using Open ID Connect.

So I suppose that the only option is the third one, providing two providers  (v1 and v2) and deprecate the v1 one. I'll try to also upgrade the twitter4j to the last version in the current v1 prov.

**Comment by mposolda** [comment]
@rmartinc @pedroigor The note about OpenID Connect support is interesting. If they go to add OIDC support relatively soon, then it is maybe best option for us to wait with adding new provider until OIDC based provider (supporting also email address) is released? Otherwise if we add `v2` provider and then they add OIDC provider (which is better than v2) is released soon, we will need another migration and eventually ending up with 3 twitter providers (v1, v2, oidc). Could you please try to dig more when they go to add OIDC provider?

So for v1 provider, I suggest to upgrade twitter4j regardless for `v1` provider

For v2 provider: if they add OIDC relatively soon (EG. within 6 months) I suggest to wait for OIDC and not add new twitter provider to Keycloak and just live with our current v1 provider. Otherwise if it is added later (or not possible to figure this in their roadmap etc), we can add `v2` provider right away. WDYT guys?

**Comment by rmartinc** [comment]
Twitter is now in a convoluted situation but we can ask in the community if there is roadmap to provide a OpenID Connect version in the short / medium term. I can ask and see what happens.

On the other side I'm starting to change the old v1 provider to use the new twitter4j version (API is a little different).

**Comment by pedroigor** [comment]
@mposolda I would say we should wait for community and customer feedback to decide whether we should provide a v2 broker.

**Comment by mposolda** [comment]
@pedroigor @rmartinc Yeah... The fact that "email" does not work is a regression in functionality and I recall some users already had issue with that (when `v1` did not support `email` in the past).

So we can possibly just update the twitter4j in `v1` provider. For `v2/oidc`, we can wait until there is ask from the community and/or until they support "email" as well. WDYT?

@rmartinc Is it ok if you just save your prototype in some branch in your fork? As it is a chance we will use it later...

**Comment by rmartinc** [comment]
Yes, no problem at all. Only updating the current provider then.

**Comment by rmartinc** [comment]
I'm going to change the issue name to upgrade twitter4j after the conversation. Regards!

**Comment by mposolda** [comment]
For the reference, here is the branch with the `v2` prototype (if we want to use it in the future): https://github.com/rmartinc/keycloak/tree/twitter-oauth2https://github.com/rmartinc/keycloak/tree/twitter-oauth2
