### ISSUE TITLE
Operator ignores DB vendor when using custom image. Forces h2 instead of chosen vendor.

### ISSUE THREAD

**Issue by easpeagle** [keycloak/keycloak#16775]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

If I specify a custom image in my keycloak object, despite whatever I have setup as the DB vendor, it always forces H2.  Even if I've hard-coded the KC_DB env var in the image itself.

### Version

20.0.3

### Expected behavior

When I use a custom image, I would expect it to honor the selected DB vendor.

### Actual behavior

2023-02-01 18:48:50,910 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': URL format error; must be "jdbc:h2:{ {.|mem:}[name] | [file:]fileName | {tcp|ssl}:[//]server[:port][,server2[:port]]/name }[;key=value...]" but is "jdbc:postgresql://standard-cluster.stackgres.svc.cluster.local:5432/keycloak" [90046-214]

### How to Reproduce?

Create a custom image from quay.io/keycloak/keycloak:20.0.3 that merely injects some additional CA certs into the java cacerts store.  Use that custom image in your object.

**Comment by vmuzikar** [comment]
@easpeagle Thank you for reporting this. @sschu is correct, when a custom image is used, re-augmentation is not performed and therefore build time properties specified in the CR do not take any effect. This is a [documented behaviour](https://www.keycloak.org/operator/customizing-keycloak).

**Comment by easpeagle** [comment]
> @easpeagle Thank you for reporting this. @sschu is correct, when a custom image is used, re-augmentation is not performed and therefore build time properties specified in the CR do not take any effect. This is a [documented behaviour](https://www.keycloak.org/operator/customizing-keycloak).

Well... that's strange... because I baked in the KC_DB env var into the image that I built... and it still wanted to fail back to h2 ... I worked around this by overriding the args in the unsupported container section of the keycloaks object.

**Comment by sschu** [comment]
And you executed kc.ah build in your image build?

**Comment by vmuzikar** [comment]
@easpeagle Thanks for providing more context. You can find all build options [here](https://www.keycloak.org/server/all-config?f=build).

**Comment by easpeagle** [comment]
And... I sweat I've seen this page 100 times and never noticed the radio button for "build" and "configuration" options.  ::facepalm::

Thanks, folks!

**Comment by vmuzikar** [comment]
@Mezzenine Sorry you are facing issues with deploying Keycloak. I'd suggest opening a new issue as we do not have the resources to reliably monitor old closed issues.

In any case, when `spec.image` is specified, the Operator considers it a custom image which is already optimized. See the relevant [guide](https://www.keycloak.org/operator/customizing-keycloak):
> With custom images, every build time option passed either through a dedicated field or the additionalOptions is ignored.

**Comment by Mezzenine** [comment]
@vmuzikar Thanks for your fast response, and sorry for putting my comment to a closed issue.
I'll try to build a custom image and see if this will solve my issues. But this is not what I really want to do. Because I love to use defaults.
