### ISSUE TITLE
Update the Build from source documentation

### ISSUE THREAD

**Issue by Cracky5457** [keycloak/keycloak#16790]
### Description

Hello,

Since version 20 the build from source documentation is not up-to-date

https://github.com/keycloak/keycloak/blob/main/docs/building.md

For exemple I can't build only the server anymore

The server-dist folder doesn't exist anymore

`mvn -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean install`

What is the new way to achieve the same goal ? Thanks.

**Comment by v-kamerdinerov** [comment]
Faced a similar error, had to roll back to 19.0.3 to build from source.

**Comment by abstractj** [comment]
The issue was solved in the most recent changes of our documentation. Closing it for now.

**Comment by Nefcanto** [comment]
Is it updated and working now? Cause I can't build from the source using https://github.com/keycloak/keycloak/issues/16790 and I get errors in a fresh Ubuntu/Debian installation. I reported them at https://github.com/keycloak/keycloak/issues/26807.
