### ISSUE TITLE
Keycloak providers and theme not dynamicly reloaded with Keycloak X (quarkus) vs Keycloak Jboss/wildfly

### ISSUE THREAD

**Issue by mcarbonneaux** [keycloak/keycloak#16808]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

in wildfly/jboss version you need only to copy the providers and theme in directory, and dynamicly reloaded without service impact.
in quarkus version you need to restart quarkus that impact the service.
event if i miss information in documentation...

### Version

i've tested v19 of quarkus version

### Expected behavior

the ability to reload dynamicly providers and theme.

### Actual behavior

need to restart!

### How to Reproduce?

copy  providers and theme in providers directory and themes.

**Comment by sschu** [comment]
This is by design. Quarkus ist not a full-featured application server with runtime code reload and stuff but a framework that puts as much work as possible into the build process and not runtime.

**Comment by stianst** [comment]
It should be possible to edit themes in the theme directory without restarting the server. If you disable gzip, theme caching, and browser caching (check the docs for info), then you can edit files directly.

This shouldn't really have changed at all unless you're deploying themes as JAR files. Perhaps you used to disable theme caching and such on WF, but are not doing it in the Quarkus dist?

**Comment by mcarbonneaux** [comment]
ok for theme but for provider is not possible.
and very usefull option to avoid client interupt when upgrade provider.

**Comment by stianst** [comment]
That's simply not possible to do, and is one of the downsides of using Quarkus rather than wildfly
