### ISSUE TITLE
Any tests using PhantomJS failing in some newer linux environments

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#16818]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

After setup new laptop, Any test using PhantomJS is failing for me with the error like this:

```
09:01:26,169 INFO [org.keycloak.testsuite.adapter.servlet.DemoServletsAdapterTest] [DemoServletsAdapterTest] testWithoutKeycloakConf() STARTED
Feb 03, 2023 9:01:26 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /home/mposolda/IdeaProjects/keycloak/testsuite/integration-arquillian/tests/base/target/drone/1c947d57fce2f21ce0b43fe2ed7cd361/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
Feb 03, 2023 9:01:26 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 1443
Feb 03, 2023 9:01:26 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--ignore-ssl-errors=true, --web-security=false, --webdriver=1443, --webdriver-logfile=/home/mposolda/IdeaProjects/keycloak/testsuite/integration-arquillian/tests/base/phantomjsdriver.log]
Feb 03, 2023 9:01:26 AM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
Auto configuration failed
139991832651712:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
139991832651712:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139991832651712:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
139991832651712:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers
Feb 03, 2023 9:01:46 AM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
09:01:46,486 ERROR [org.keycloak.testsuite.adapter.servlet.DemoServletsAdapterTest] [DemoServletsAdapterTest] testWithoutKeycloakConf() FAILED 
```

I am seeing this on Ubuntu 22.04 as well as on RHEL 9.1 virtual machine. Java version is OpenJDK11 or OpenJDK17. 

### Solution

It helps to set this environment variable:
```
export OPENSSL_CONF=/dev/null
```
See for example here for more details https://github.com/nodejs/node/issues/43132

Can we eventually set this variable by default to avoid such issues?

### Version

20.0.3

### How to Reproduce?

For example run this test on Ubuntu 22.04 or on RHEL 9.1 (reproduced with RHEL 9.1 virtual machine). Java version is OpenJDK11 or OpenJDK17. 
```
mvn clean install -Dtest=DemoServletsAdapterTest
```

**Comment by jonkoops** [comment]
I'd really like to kill off PhantomJS all together, which would be possible if we were to resolve https://github.com/arquillian/arquillian-extension-drone/issues/359.

**Comment by mposolda** [comment]
@jonkoops +1, but I have some doubts when https://github.com/arquillian/arquillian-extension-drone/issues/359 will be done (unless we contribute to do it ourselves...). Also removing PhantomJS may not be all that trivial (I recall that X.509 tests have hard dependency on it and doesn't work with any other browsers).

For now, I went with my PR as it helped to avoid this particular issue.

**Comment by jonkoops** [comment]
> unless we contribute to do it ourselves

Yep, that is pretty much what I think it will take. We could remove it incrementally by slowly converting the tests over, I think we can always fall back to PhantomJS where needed.
