### ISSUE TITLE
UI: User Federation is disabled, but UI shows enabled on first load

### ISSUE THREAD

**Issue by dankots** [keycloak/keycloak#16843]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

when you open a specific User Federation that is currently disabled, the Browser query network traffic shows it is disabled, but the UI shows it is enabled.

### Version

20.0.3

### Expected behavior

if data from the server indicates the user federation is disabled, it should show the "enabled" slider in the disabled position.

### Actual behavior

the enabled slider is always in the enabled position when you first load a user federation, regardless of the actual enabled status.

### How to Reproduce?

create a user federation
disabled it
reload the UI and open the user federation.

**Comment by jsorah** [comment]
Hi, I'm not seeing this behavior in the latest Keycloak (21.1.1) - are you able to replicate it on the latest version?

**Comment by dankots** [comment]
fixed by:
https://github.com/keycloak/keycloak-ui/pull/3822
