### ISSUE TITLE
Failing ThemeResourceProviderTest due to collision on class path 

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#16856]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

The test fails with NPE when getting "Content-Encoding" header from response which is `null`:
```
java.lang.NullPointerException
	at org.keycloak.testsuite.theme.ThemeResourceProviderTest.assertEncoded(ThemeResourceProviderTest.java:143)
	at org.keycloak.testsuite.theme.ThemeResourceProviderTest.gzipEncoding(ThemeResourceProviderTest.java:107)
```

The reason for this behavior seems to be a fact that it's not possible to instantiate `MimetypesFileTypeMap` here:
https://github.com/keycloak/keycloak/blob/404113b47974dbec9f601e60520223c75c20058e/common/src/main/java/org/keycloak/common/util/MimeTypeUtil.java#L28

It's because here 
https://github.com/jakartaee/jaf-api/blob/6c7dd2d757f6a705048c8b4e074c6f741dee110d/api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java#L151 
`getImplementation()` returns `com.sun.activation.registries.MimeTypeRegistryProviderImpl` from `org.eclipse.angus:angus-activation:jar:1.0.0` which is present on class path via multiple dependencies.

### Version

quarkus3

### Expected behavior

The test passes.

### Actual behavior

The test fails.

### How to Reproduce?

Run the test on quarkus3 branch.

### Anything else?

Possible solution could be adding 

```xml
            <dependency>
                <groupId>org.eclipse.angus</groupId>
                <artifactId>angus-activation</artifactId>
                <version>2.0.0</version>
            </dependency>
```
into `dependencyManagement` of `keycloak/pom.xml`. Can we do that?

**Comment by mabartos** [comment]
Resolved by #17214
