### ISSUE TITLE
Unable to obtain private key from generated keys using "Signed Jwt"

### ISSUE THREAD

**Issue by MuhammadZakwan** [keycloak/keycloak#16852]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I am trying to generate key pairs through Keycloak admin console using “Signed Jwt” in an attempt to sign using client application and verify using Keycloak through client_assertion.

I have successfully generated new keys in PKCS12 format, however, were unable to extract the keys using Openssl and convert to pem format.

### Version

20

### Expected behavior

Able to extract the private keys from the generated keys.

### Actual behavior

Running the Openssl command to the generated keys resulted in error.

Command: openssl pkcs12 -in keystore.p12 -out privateKey.pem -nocerts -nodes
Error: ASN1_get_object:header too long:crypto\asn1\asn1_lib.c:105:

There was no problem using Keycloak prior to Version 19.

### How to Reproduce?

1. Set the client Authenticator to “Signed Jwt” under the "Credentials” tab.
2. Generate new keys with PKCS12 format under the “Keys” tab.
3. Run Openssl command: openssl pkcs12 -in keystore.p12 -out privateKey.pem -nocerts -nodes

**Comment by lmm-git** [comment]
The issue seems to be in the new admin console as with the old console everything works as intended.

In the new admin console, even when grabbing the server base64 response directly and decoding it, the file content is correct. Therefore, I suspect a decoding issue within the new admin console.

**Comment by MuhammadZakwan** [comment]
I'm closing this issue as it has been fixed with the release of Keycloak 21.
