### ISSUE TITLE
No event/email when OTP device is removed via API

### ISSUE THREAD

**Issue by yalpertem** [keycloak/keycloak#16872]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When the OTP device (credential) is removed via the API endpoint `DELETE /account/credentials/{credentialId}` no event type of `REMOVE_TOTP` is created. That leads to not sending the email.

Related code:

1. The method for OTP device credential removal is located here: https://github.com/keycloak/keycloak/blob/71d292ff70368f1085af953d0ec52efc3e418ed7/services/src/main/java/org/keycloak/services/resources/account/AccountCredentialResource.java#L273-L283

2. The email is sent when the `keycloak` theme is used since the old form endpoint creates a `REMOVE_TOTP` event. The related code: https://github.com/keycloak/keycloak/blob/71d292ff70368f1085af953d0ec52efc3e418ed7/services/src/main/java/org/keycloak/services/resources/account/AccountFormService.java#L522-L532

### Version

20.0.2

### Expected behavior

When the OTP device is removed via REST API, the event is expected to be created, and an email will be sent.

### Actual behavior

When the OTP device is removed via REST API, the event is not created, and the email is not sent.

### How to Reproduce?

1. Run the latest version locally
2. Enable OTP setup
3. Remove the OTP device with the `keycloak.v2` account theme or directly call the endpoint.
4. Check out the Events and mail inbox. There's no event or email sent.

**Comment by sventorben** [comment]
Duplicate: https://github.com/keycloak/keycloak/issues/15403

**Comment by jonkoops** [comment]
Duplicate of #15403
