### ISSUE TITLE
authentication subflows are not removed from database if parent flow is removed

### ISSUE THREAD

**Issue by henk-n** [keycloak/keycloak#16871]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

When removing a authentication flow with subflows,  the subflows are not deleted and the name of the subflow can not be reused

### Version

20.0.3

### Expected behavior

When there is a subflow or flow removed where there are subflows involved those subflows should also be removed from the database (with or without extra confirmation) so the name of the subflow can be reused

### Actual behavior

the flow is removed and the subflow is still in the database and therefore can not be used again

### How to Reproduce?

create a authentication flow and add nested flows and then remove the parent flow or one of the steps with a nested flow, the names of the removed flows can not be used again to recreate the flow with the same names

### Anything else?

be gentle. this is my first bug report on github. I hope that I followed the rules. If not please tell me

**Comment by mposolda** [comment]
This will be nice to fix, but I am adding to Backlog as I am not sure if Keycloak team will have opportunity to look at this in the near future. Everyone is welcome to investigate and send PR for this. Please take a look at https://www.keycloak.org/community to the "Contributors" section for the details.
