### ISSUE TITLE
Required actions execution order (session and user required actions)

### ISSUE THREAD

**Issue by rd-mara-hegemann** [keycloak/keycloak#16873]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Hi, when I configured some required actions like so:

- password reset (priority 1)
- verify email (priority 2)
- terms and conditions (priority 3)

When the user triggers a password reset (via forgot password) I expect the following order:

action |context
--------|-------
password reset| session
verify email |user
terms and conditions |user

but instead they execute in the following order:

action        | context
--------|-------
verify email |user
terms and conditions |user
password reset| session

This seems like a bug to me and I looked into the code and it seems to go
wrong  [here](https://github.com/keycloak/keycloak/blob/9b01bf382d69b0eb4f3d0defd27beddbac15ba37/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1160-L1166)

```java
Stream<String> requiredActions = user.getRequiredActionsStream();
// Here all the user required actions are executed, even if there are higher priority actions stored in the session...
Response action = executionActions(session, authSession, request, event, realm, user, requiredActions);
if (action != null) return action;

//... which are executed afterwards
action = executionActions(session, authSession, request, event, realm, user, authSession.getRequiredActions().stream());
if (action != null) return action;

```

One potential way of fixing this would be to concatenate user required actions and session required actions to execute them in one step.

The only obvious difference would be that we can't return early after executing the user actions, but I don't understand when that is actually desired.

### Version

19.0.2

### Expected behavior

When configuring required actions like so:

- password reset (priority 1)
- verify email (priority 2)
- terms and conditions (priority 3)

When the user triggers a password reset (via forgot password) I expect the following order:

action |context
--------|-------
password reset| session
verify email |user
terms and conditions |user

### Actual behavior

but instead they execute in the following order:

action        | context
--------|-------
verify email |user
terms and conditions |user
password reset| session

### How to Reproduce?

This can be reproduced by configuring some required actions like in the example above.

### Anything else?

Previously reported and discussed over here:

- https://groups.google.com/g/keycloak-dev/c/MqpYd7kKa3U
- https://keycloak.discourse.group/t/required-actions-execution-order-session-and-user-required-actions/10689

**Comment by mrpatrickpilch** [comment]
Just recently also had the same struggle. https://github.com/keycloak/keycloak/discussions/16527

**Comment by pedroigor** [comment]
@mrpatrickpilch Run the reproducer using versions:

* `upstream`/`nightly`
* `20.0.3`
* `18.0.0`

I also see performance degradation in both `20.0.3` and `upstream`.

@keycloak/performance Would you be able to give us a chance to confirm the results we are facing?
@keycloak/store Is there anything you can spot that might be causing the degradation?

@stianst @mposolda For now, and based on my results, I think this is something we should consider for 22.

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .

I can add that the approach discussed here combined with the sorting in the related discussion #16527 makes sense to me. We may need also some automated test for this (Maybe `RequiredActionMultipleActionsTest` is the good candidate to add new test-case for this)

**Comment by danielFesenmeyer** [comment]
My code still had a bug regarding the "cancel-AIA" behavior: the latest draft now considers that an application initiated action (AIA) cannot be cancelled.

All tests - except one - are succeeding now without further adjustments. The only test to adjust was WebAuthnRegisterAndLoginTest#webAuthnPasswordlessAlternativeWithWebAuthnAndPassword:
The test uses a flow which sets required actions (`WebAuthnPasswordlessRegisterFactory` and `WebAuthnRegisterFactory`) into the session, in case there is no registration of credentials yet. Additionally, it explicitly sets the required action `WebAuthnPasswordlessRegisterFactory` on user level. With the old behavior, user context required actions were executed before session context required actions --> `WebAuthnPasswordlessRegisterFactory` before `WebAuthnRegisterFactory`. Now the execution is based on priority: `WebAuthnRegisterFactory` (prio 70) is now executed before `WebAuthnPasswordlessRegisterFactory` (prio 80).
Do you think this small behavioral change is ok?
