### ISSUE TITLE
Import a realm on the startup of running a container using --import-realm command

### ISSUE THREAD

**Issue by tonygeorgiev** [keycloak/keycloak#16886]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

Greetings!
I am trying to import a realm on the startup of running a container
Here is my podman/docker command:
`podman run --name keycloak -p 9990:8080 -p 9991:8443 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin  -v realm:/opt/keycloak/data/import quay.io/keycloak/keycloak:latest start-dev --import-realm`

It is using keycloak latest version and the realm.json is located in the same directory as the terminal, but when I open the keycloak admin panel the only realm I have is master?

This is taken from the Official documentation https://www.keycloak.org/server/containers#_importing_a_realm_on_startup.

The realm.json is correct I am able to import it manually.

What could be the issue, I think everything I have written is correct?

### Version

20.0.3

### Expected behavior

The following command should import a realm on startup of the container

`podman|docker run --name keycloak_unoptimized -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
        -v /path/to/realm/data:/opt/keycloak/data/import
        quay.io/keycloak/keycloak:latest \
        start-dev --import-realm`

### Actual behavior

My command is 
`podman run --name keycloak -p 9990:8080 -p 9991:8443 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin  -v realm:/opt/keycloak/data/import quay.io/keycloak/keycloak:latest start-dev --import-realm`

### How to Reproduce?

Run by adding your parameters:
`podman|docker run --name keycloak_unoptimized -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me \
        -v /path/to/realm/data:/opt/keycloak/data/import
        quay.io/keycloak/keycloak:latest \
        start-dev --import-realm`

**Comment by gingters** [comment]
I have the exact same issue.

I followed the docs ( https://www.keycloak.org/server/containers#_importing_a_realm_on_startup ) and have an example realm to import on startup, but the realm is NOT imported.

**Comment by jsorah** [comment]
Hi @tonygeorgiev  - if you specify the volume as `-v realm:/opt/keycloak/data/import` you're actually trying to mount a named volume `realm` into your container.  See [the podman documentation for more](https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options). 

If you want to load your realm.json from the host machine you need to move it to a directory such as `realms` and reference it like `-v ./realms:/opt/keycloak/data/import`.

I am unsure about the second comment by @gingters  - I think we would need more details on that set up to be able to help, but I would suspect there could be similar issues with mounting, especially if the server starts as expected without throwing any errors similar to this run:

```
2023-05-16 20:22:25,391 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2023-05-16 20:22:26,566 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/bin/../data/import
2023-05-16 20:22:26,566 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
2023-05-16 20:22:26,567 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
2023-05-16 20:22:26,794 INFO  [io.quarkus] (main) Keycloak 21.1.1 on JVM (powered by Quarkus 2.13.7.Final) started in 6.864s. Listening on: http://0.0.0.0:8080

```

**Comment by jsorah** [comment]
I'm going to go ahead and close this out since it seems like a config issue (the volume params I mentioned) - please feel free to reopen if you're still facing issues with as much detail as you can reasonably provide about your container set up.
