### ISSUE TITLE
Support to enforce LoA in authentication flow (Step-up)

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#16884]
### Description

Keycloak now supports step-up authentication for a while.
While this is a great feature where clients support it, we still have clients that do not support it, but where we would like to enforce a certain level of authentication (LoA).

To support this, we would like to add two new authenticators:
* `Enforce LoA`: Authenticator to enforce a certain level of authentication
* `Condition - Client Id`: A condition that matches based on the client id

### Motivation

When a login request is sent to Keycloak from a client that does not support step-up authentication without `acr_values` parameter and without a `claims` parameter that has an `acr` claim attached, Keycloak already supports a fallback mechanism with `Default ACR Values` on a per client basis.
However, as [stated in the documentation](https://www.keycloak.org/docs/20.0.3/server_admin/#_mapping-acr-to-loa-client) these default values "cannot be reliably used to enforce login with the particular level".

We have scenarios where we need to have three different levels of authentication (1-3). Most clients do not support step-up authentication yet, but would need to require level 2 (default for most clients). Some other clients only need level 1 and we do not want to bother users with entering a 2nd factor if not needed. In addition, some clients already support step-up authentication but for administration purposes may need to step-up from level 2 to level 3.

In such scenarios, it would be nice if the required LoA could be determined and enforced in an authentication flow on the Keycloak site.

### Details

We would like to add two new authenticators:

* `Enforce LoA`
* `Condition - Client Id` (optional)

### Enforce LoA
This authenticator should be able to enforce a minimum level of authentication.
The authenticator should be configurable with a default value for the minimum LoA. In addition it should consider the default acr value for a client. The LoA to be enforced should be the `max(loa from authenticator config, max(default acr values from client)`.

### Condition - Client Id (optional)
We would like to include/exclude some clients from this logic. Currently there is no way to express a condition in a flow to execute certain authenticators only for a subset of clients. Authentication flow overrides could be a solution for this, but would require an additional flow. This is quite cumbersome to align all the conditions for the LoAs across multiple flows.
Therefore, a condition that matches a set/list of client ids would be neat.

**Comment by sventorben** [comment]
I can add a PR later today to give some implementation ideas.

**Comment by embesozzi** [comment]
This feature was a common requirement or question in the Keycloak community:

https://keycloak.discourse.group/t/enforce-default-acr-values/22732

**Comment by thomasdarimont** [comment]
I just stubled upon this issue. I see that the associated PR choose to add additional authenticators to enforce the LoA via custom authentication flows.

Most customers that I've seen want to associate different but fixed LoAs / ACRs per Client, e.g. for client-1 auth via username+pwd is fine but for client-2 users should must use MFA.
@sventorben Did you also consider to just add an optional "Required LoA" attribute to a client configuration and enhance the built-in authentication flow processing to honor this "Required LoA"? 
I think this would have been easier to implement and would do the job for the majority of users without requiring additional / custom auth flow configurations.

**Comment by sventorben** [comment]
@thomasdarimont No, I didn't mainly because I initially implemented this as an extension for a customer of ours. I was requested to implement it as an extension, so that it works out of the box with a default Keycloak release.

**Comment by thomasdarimont** [comment]
I see thanks for the feedback. I think having the additional authenticators is useful but requires user to configure custom auth flows. 

I think we could provide a leaner approach (in addition to the authenticators) by making [org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint#updateAuthenticationSession](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java) aware of a client specific ACR / LoA information.

However care must be taken that this client based "ACR/LoA" requirement plays well with a custom authenticator flow using your authenticators.

**Comment by sonOfRa** [comment]
We're also currently investigating this use case (and considering cherry-picking the PR to get it into our setup). We use Keycloak to provide Logins for applications which simply don't support checking the ACR value inside the token, all they do is validate the access token received from the server. As a business requirement, we want to enforce login via 2FA (or a trusted IdP) for those clients.

We have working flows for this setup, but if an end user manipulates the auth_url used to log in by the application to include a lower (or invalid) `acr_values` parameter, the requirement is bypassed and the user can log in without providing a second factor.

To me it seems like this is a rather common requirement, and a client attribute, rather than complicated client policies would be the best way forward here

**Comment by sonOfRa** [comment]
I've created https://github.com/keycloak/keycloak/pull/33205 as a possible implementation of this feature via a client attribute. It currently lacks tests, but the @thomasdarimont's suggestion of taking the parameter into account in `AcrUtils` works fine in our local setup:

With `acr.values.forced=otp` as an attribute, the user must still satisfy the correct authentication for the `otp` level, even if they append `&acr_values=password` or any other insufficient parameter to the auth_url.

**Comment by embesozzi** [comment]
One thing to keep in mind is that it is not the responsibility of the IdP to control or enforce a specific value for `acr` or `amr`. This is the responsibility of the app or API.
