### ISSUE TITLE
Refine the set of RPMs included in the keycloak container image

### ISSUE THREAD

**Issue by ASzc** [keycloak/keycloak#16902]
### Description

The `keycloak` container image is based on `ubi8-minimal`, and currently it just updates everything and installs Java. "Minimal" is relative, the minimum for a functioning RHEL is more than the minimum for functioning Keycloak. A more refined approach would identify and remove RPMs that aren't actually required to run the keycloak server.

### Motivation

Being more selective about what RPMs are included in the image should prevent bug reports like these: #16075 or #16816

**Comment by ASzc** [comment]
See pull #16879

**Comment by vmuzikar** [comment]
Reopening as this needs to be reflected in release notes.

**Comment by flyingflo** [comment]
Minimization is good, but removal of dnf/microdnf makes it quite hard to extend the image with some use-case specific dependency. E.g. install libstdc++ which is required by a HSM Java API.

**Comment by flyingflo** [comment]
> @flyingflo Please see the updated documentation [here](https://www.keycloak.org/server/containers#_installing_additional_rpm_packages). Your use case is still supported, just through a different procedure.

@ASzc Nice, that does the trick, and keeps the image minimal, thanks!
