### ISSUE TITLE
Update the REST API and make "name" mandatory on GroupRepresentation

### ISSUE THREAD

**Issue by pedro-hos** [keycloak/keycloak#16912]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

After the [1] fixed the `name` parameter become mandatory, but our REST API [2] still pointing `name` as **optional**, so when we try to call the endpoint without the name we got errorMessage value of  'Group name is missing`, that is pretty clean, but I guess that we should update to avoid any problem.

[1] https://issues.redhat.com/browse/KEYCLOAK-17581
[2] https://www.keycloak.org/docs-api/20.0.3/rest-api/index.html#_grouprepresentation

### Version

Keycloak 20

### Expected behavior

Had the REST API updated

### Actual behavior

Rest API still says that the `name` parameter is optional

### How to Reproduce?

By looking the rest api 

https://www.keycloak.org/docs-api/20.0.3/rest-api/index.html#_grouprepresentation

**Comment by pedro-hos** [comment]
Hello Team, 

I guess that we should only add `@JSONProperty` and make it mandatory, right? If so I can do that!

Thanks

**Comment by jsorah** [comment]
Hi, I am actually unsure of the right toggles for the optional/required flag in the documentation.

However, given this is relatively low priority I am going to send this to the backlog. 

If you (or anyone else) decides to chase this down be aware of #20433 being an impact on the `main` branch.
