### ISSUE TITLE
Keycloak admin client is missing the protection API

### ISSUE THREAD

**Issue by bartmentech** [keycloak/keycloak#16929]
Currently the Node.js admin client does not support the protection API described in the [docs](https://www.keycloak.org/docs/latest/authorization_services/index.html#_service_protection_api). 

This would be very useful for writing applications like a AWS Lambda authorizer. Are there any plans to implement this API?

I have created a starting point to cover my needs (https://github.com/bartmentech/keycloak-nodejs-admin-client/commit/d2512aec8ae7b16dd3c0d503cb6924d175b5611b). If there is interest, I will make a pull request.

**Comment by edewit** [comment]
this has been added to the admin client
