### ISSUE TITLE
KeyCloak 20 error during browser token request: unauthorized_client, Invalid client or Invalid client credentials

### ISSUE THREAD

**Issue by senaev** [keycloak/keycloak#16923]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Cannot get token with `OpenID Connect` after authorization

### Version

20.0.3

### Expected behavior

Ability to receive token from browser after autrorization

### Actual behavior

Trying to request token `http://localhost:8080/realms/realm-name/protocol/openid-connect/token` I got error response `{"error":"unauthorized_client","error_description":"Invalid client or Invalid client credentials"}`

### How to Reproduce?

* HTML file with keycloak-js adapter https://gist.github.com/senaev/e07dd4802b86898d0709c2c142331285
* docker-compose.yml with keycloak image https://gist.github.com/senaev/ec64499692f75b3fc1914fd9f4e96a34
* video of reproducing https://disk.yandex.ru/i/pnpO32pq5gIY2w
* HAR file with all browser requests https://gist.github.com/senaev/2f43a9d079c7c90b4d7458d21ad1ffe6

### Anything else?

I tried the same flow with KeyCloak 16.1.1 and everything was working for me

**Comment by sschu** [comment]
Do your client id or secret contain any special characters? There was a change fixing a wrong decoding of client id an secret (https://github.com/keycloak/keycloak/pull/14179/files). This change might have an impact if special characters are contained. Can you try to use a plain client id and a newly regenerated secret?

**Comment by senaev** [comment]
> Do your client id or secret contain any special characters? 

No, there was no other symbols than dash and Latin alphabet

**Comment by pedroigor** [comment]
@senaev The JS adapter is not meant for confidential clients. SPAs can not securely manage/store secrets as they run in the browser.

Please, try changing your client to a public client. The behavior is expected.

**Comment by senaev** [comment]
@pedroigor what do you mean talking about public mode? How cat I turn it on, or create a client in a public mode? During setup I did not see such option.

**Comment by senaev** [comment]
> Basically, do not enable client authentication and authorization.

Thanks, it is really worked for me
My final settings are on the screen
<img width="1536" alt="Screen Shot 2023-02-28 at 11 07 18 AM" src="https://user-images.githubusercontent.com/7939529/221791685-0477b291-ff16-4afa-b32d-858483c61832.png">

https://gist.github.com/senaev/24e4011360a0e5572930f1b38984516c
https://gist.github.com/senaev/bed92fc06ea354847d9240f7ae1f40aa

**Comment by keul** [comment]
Spent big amount of time of this only because accessing the same keylcoak, with same settings, from localhost was working! Thanks for the fix!
