### ISSUE TITLE
Group resource: setOrCreateChild don't return 'location header'

### ISSUE THREAD

**Issue by gstester** [keycloak/keycloak#16925]
Calling adminClient.groups.setOrCreateChild({ realm: realm, id: id }, group)

causes an exception:
`SystemException: location header is not found in request: https://auth-test.lbb7lk8hq4v71.hms-dev.cloud/auth/admin/realms/qc/groups/4e964d7f-9af6-4a71-81dd-318f3b9f381d/children`

Environment:
- Keycloak Server Version v6.0.1
- AdminClient: v1.12.0
- node: v10.15.3

In keycloak admin console you can find:
https://<myserver>/auth/admin/realms/qc/groups/b60dbd41-14ed-4048-87fa-143135cc859b/children
returns: 
- Status: 204
- Headers: content-type | application/json, date | Tue, 20 Aug 2019 08:51:29 GMT

May be to set 'returnResourceIdInLocationHeader' for this specific call isn't suitable any more.

Remark: Other calls like `adminClient.groups.create` are returning the location header.

**Comment by diazoxide** [comment]
Actual for me too!

**Comment by jonkoops** [comment]
The issue here is likely that the header is sometimes present in the response, based on whether the child has has already been created or not. Therefore, we probably need to expand the functionality so that the `id` is optionally extracted from the header in this case.
