### ISSUE TITLE
An ability to replace axios with other axios variants

### ISSUE THREAD

**Issue by alliedgorn** [keycloak/keycloak#16938]
I'm using keycloak-admin behind an http proxy(non-secure) and get this error while trying to connect to keycloak via https.

> Error negotiating SSL on FD 13: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (1/-1/0)

I found that this is a long running bug on axios and they've not fixed this problem yet. Most people stumbled on this problem move to use other library such as https://www.npmjs.com/package/axios-https-proxy-fix
https://github.com/axios/axios/pull/3159

**Comment by jonkoops** [comment]
Closing this as we opted to drop Axios completely in favor of using a plain Fetch API call.
