### ISSUE TITLE
Add credentials endpoint

### ISSUE THREAD

**Issue by tvrg** [keycloak/keycloak#16935]
See https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_credentials

In 7.0.1 you could remove a `totp` configuration via the users API. In more recent versions you have to use the new credentials API instead. The `removeTotp` test was removed in keycloak/keycloak-nodejs-admin-client#66.
Also see https://github.com/keycloak/keycloak-nodejs-admin-client/pull/66#discussion_r519611271

**Comment by edewit** [comment]
it's still there https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/src/resources/users.ts#L320
