### ISSUE TITLE
BaseUrl isn't getting used

### ISSUE THREAD

**Issue by stevehogdahl** [keycloak/keycloak#16931]
I'm getting the following error when calling the auth function:
`ERROR	Invoke Error	
{
    "errorType": "Error",
    "errorMessage": "connect ECONNREFUSED 127.0.0.1:8080",
    "trace": [
        "Error: connect ECONNREFUSED 127.0.0.1:8080",
        "    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)"
    ]
}`

It looks like it's trying to hit the default baseUrl even though i passed in a new baseUrl. Code is below:

```
const KeycloakAdminClient = require('keycloak-admin').default;

const settings = {
	baseUrl   : config.KeycloakBaseLocation,
	username  : config.KeycloakUsername,
	password  : config.KeycloakPassword,
	grant_type: 'password',
	client_id : 'admin-cli',
	realmName : config.KeycloakRealm
}

const client = new KeycloakAdminClient();
await client.auth(settings);
```

**Comment by edewit** [comment]
closing
