### ISSUE TITLE
is Impersonation Supported?

### ISSUE THREAD

**Issue by PavelJacobo** [keycloak/keycloak#16934]
Hello
I would like to know if impersonation is supported. I tried to find a way to impersonate a user but I couldnt find It.
Thanks in advance

https://www.keycloak.org/docs-api/9.0/rest-api/index.html#_users_resource

POST /{realm}/users/{id}/impersonation

**Comment by codespearhead** [comment]
Only to an extent, as explained in this issue [1]:

> [`2022-02-03T13:44:55Z`] [stianst](https://github.com/stianst): The built-in impersonation feature only works through the admin console. To do impersonation without the admin console look at the preview token exchange feature in the docs [2].

[1] https://github.com/keycloak/keycloak/issues/9907
[2] https://www.keycloak.org/nightly/securing-apps/token-exchange

**Comment by jonkoops** [comment]
Closing this as it is a question, and thus belongs in the forums.
