### ISSUE TITLE
Read the config-object when getting an authorization permission

### ISSUE THREAD

**Issue by krilleAb** [keycloak/keycloak#16933]
**Is your feature request related to a problem? Please describe.**
I want to be able to see which resources, scopes and policies are connected to a authorization permission with the findOnePermission-function and/or findByName-function.
This have only been tested against keycloak 11.0.3.

**Describe the solution you'd like**
I would like to be able to read the objects/properties listed in the config-object, of an authorization permission, to see which resources, scopes and policies are used with that permission.

Example.

From the Keycloak WEB GUI, under Athorization->Export Settings, I will get the following information about my permission.
```
{
  "id": "15a43132-1582-4595-8a21-17ec7090ad69",
  "name": "view.members.permission.group.5eebfcc6-8195-4fd1-8a5d-238f8f304d7d",
  "type": "scope",
  "logic": "POSITIVE",
  "decisionStrategy": "UNANIMOUS",
  "config": {
    "resources": "[\"group.resource.5eebfcc6-8195-4fd1-8a5d-238f8f304d7d\"]",
    "scopes": "[\"view-members\",\"view\"]",
    "applyPolicies": "[\"test-group-policy\"]"
  }
}
```

When using the findByName function I will receive the permission without any objects/properties in the config-object.
```
{
  id: '15a43132-1582-4595-8a21-17ec7090ad69',
  name: 'view.members.permission.group.5eebfcc6-8195-4fd1-8a5d-238f8f304d7d',
  type: 'scope',
  logic: 'POSITIVE',
  decisionStrategy: 'UNANIMOUS',
  config: {}
}
```

This also goes for the findOnePermission function but here the config-object is not even listed.
```
[
  {
    id: '15a43132-1582-4595-8a21-17ec7090ad69',
    name: 'view.members.permission.group.5eebfcc6-8195-4fd1-8a5d-238f8f304d7d',
    type: 'scope',
    logic: 'POSITIVE',
    decisionStrategy: 'UNANIMOUS'
  }
]
```

**Describe alternatives you've considered**
I cant find another way to do it.

**Additional context**
When getting a policy with findOnePolicy-function or findByName-function I will also see objects/properties in the config-object.
```
[
  {
    id: '741e36f1-b571-46e0-88cc-e1d0579b7dd5',
    name: 'test-group-policy',
    description: 'Group member can only see group members',
    type: 'group',
    logic: 'POSITIVE',
    decisionStrategy: 'UNANIMOUS',
    config: {
      groups: '[{"id":"21bea578-eafd-4795-82e8-dfe9e4e6db49","extendChildren":false}]'
    }
  }
]
```

**Comment by edewit** [comment]
done
