### ISSUE TITLE
Return all users with client role

### ISSUE THREAD

**Issue by d-vo** [keycloak/keycloak#16949]
### Description

Hi everyone, 

I want to use `adminClient.clients.findUsersWithRole()` to get all users that have a particular client role. However, I can only get the users to whom the role has been directly attached. I can not get users that inherit the role by being in a specific group that has this client role attached. 

My workaround is to query all groups with the role attached with something like: 

```
public findGroupsWithRole = this.makeRequest<{ id: string; roleName: string; first?: number; max?: number },
    GroupRepresentation[]>({
    method: 'GET',
    path: '/{id}/roles/{roleName}/groups',
    urlParamKeys: ['id', 'roleName'],
});
```

and then list all the members... or am I missing something here to get all the users with a particular client role? 

Best regards and keep up the good work! 
Dominik

**Comment by edewit** [comment]
it's a paginated endpoint and if you don't add the `first` and `max` parameters a default will be used. so to get the other results just use `first` and `max` to get the next "page" ( e.g. first=20, max=10 )

**Comment by DAHAG-ArisNourbakhsh** [comment]
@edewit This issue is not about pagination or partial data but that keycloak lacks the ability to return users who have transitive role assignments through group memberships.
