### ISSUE TITLE
search users by custom attributes

### ISSUE THREAD

**Issue by wjh000123** [keycloak/keycloak#16948]
### Describe the bug

The test case for searching user by custom attributes is wrong [here](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/125a0254d72ce781995f0a983728f75d50bbd52c/test/users.spec.ts#L101). By the documentation of [keycloak rest api](https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_users_resource), the search params should be like `users.find({ q: 'key1:value1 key2:value2' })`, instead of `users.find({key: 'value'})`.

<html>
<body>

Type | Name | Description | Schema
-- | -- | -- | --
Query | q | A query to search for custom attributes, in the format 'key1:value2 key2:value2' | string

</body>
</html>

### Version

16.1.0

### Expected behavior

search user by custom attributes, should only return the matched users.

### Actual behavior

all users are returned by following the test case code.

### How to Reproduce?

`user1` has attribute `phone` = `123`, `user2` has attribute `phone` = `456`, if use code: `users.find({phone: '123'})`, two users will be filtered out.

### Anything else?

Official rest api documentation links [here](https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_users_resource).

**Comment by alexniko44** [comment]
can i run some tests to find bugs?

**Comment by edewit** [comment]
Okay guess some documentation is in order, but in the mean time to search attributes you need to specify it like this:
```js
  const users = await adminClient.users.find({ q: "phone:123" });
  console.log(users);
```
this will find the users that have an attribute called phone with value "123"

**Comment by hossain-sazzad** [comment]
> I'd like to create a fix for this but I am currently occupied with other tasks. We're in the process of mono-repoing our JavaScript code to the main repo. Once that is completed I intend to look over all the open issues again.

May I work on this issue?

**Comment by jonkoops** [comment]
Sure @hossain-sazzad, feel free to pick this up.

**Comment by ddurham2** [comment]
any way to escape spaces in the q parameter in case one is trying to search for values containing a space?

**Comment by jonkoops** [comment]
> any way to escape spaces in the q parameter in case one is trying to search for values containing a space?

@ddurham2 Haven't verified this, but I'd imagine you can encode it like any other URL segment, for example using [`encodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

**Comment by jonkoops** [comment]
@hossain-sazzad Have you started working on this? It's been a while since you were assigned, if you don't intend to open a PR let me know, so this issue can be assigned to someone else.

**Comment by ddurham2** [comment]
> > any way to escape spaces in the q parameter in case one is trying to search for values containing a space?
> 
> @ddurham2 Haven't verified this, but I'd imagine you can encode it like any other URL segment, for example using [`encodeURIComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

I don't think so given @sbystrov 's comment above.  However, I did find a filed issue (#21598) where it explains quotes may be added around values.  I think that's very much worth putting in the API docs.  That'd be a nice addition to any PR filed for this issue, IMO.  Thanks

**Comment by Salman-Abdulqadir** [comment]
> ### Describe the bug
> The test case for searching user by custom attributes is wrong [here](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/125a0254d72ce781995f0a983728f75d50bbd52c/test/users.spec.ts#L101). By the documentation of [keycloak rest api](https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_users_resource), the search params should be like `users.find({ q: 'key1:value1 key2:value2' })`, instead of `users.find({key: 'value'})`.
> 
> Type	Name	Description	Schema
> Query	q	A query to search for custom attributes, in the format 'key1:value2 key2:value2'	string
> ### Version
> 16.1.0
> 
> ### Expected behavior
> search user by custom attributes, should only return the matched users.
> 
> ### Actual behavior
> all users are returned by following the test case code.
> 
> ### How to Reproduce?
> `user1` has attribute `phone` = `123`, `user2` has attribute `phone` = `456`, if use code: `users.find({phone: '123'})`, two users will be filtered out.
> 
> ### Anything else?
> Official rest api documentation links [here](https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_users_resource).

Try using users.find({q: "phone:123"}), i think this is the correct way to search the a custom attribute

**Comment by jesseinit** [comment]
This doesn't seem to work on Keycloak v11. It returns all users, I then have to filter which sucks.

**Comment by edewit** [comment]
@jesseinit yes the `q` parameter has been introduced on the server a bit after v11
