### ISSUE TITLE
PolicyRepresentation missing roles and groups

### ISSUE THREAD

**Issue by d-vo** [keycloak/keycloak#16946]
### Describe the bug

From the current admin console, it is possible to implement role-based policies with the following requests being issued: 

> {type: "role", logic: "POSITIVE", decisionStrategy: "UNANIMOUS", name: "Test policy",…}
decisionStrategy: "UNANIMOUS"
logic: "POSITIVE"
name: "Test policy"
roles: [{id: "dcd91634-b0d2-4656-b68b-a00acc1060fx"}]
0: {id: "dcd91634-b0d2-4656-b68b-a00acc1060fx"}
type: "role"

However, the PolicyRepresentation does not specify the field "roles". Based on this API implementation, I can only create user policies. I think it should be straightforward to add the missing fields there and support group and role-based policies. 

https://github.com/keycloak/keycloak-nodejs-admin-client/blob/main/src/defs/policyRepresentation.ts

### Version

16.0.0

### Expected behavior

I should be able to use API to create group and role-based policies.

### Actual behavior

I can only create user-based policies due to missing "roles" (and probably "groups") field.

**Comment by edewit** [comment]
this has been fixed: https://github.com/keycloak/keycloak/blob/ec8e24c5507ae67681f26bac933c26b09a551e63/js/libs/keycloak-admin-client/src/defs/policyRepresentation.ts
