### ISSUE TITLE
Fingerprint of 20.0.1 release did change after release

### ISSUE THREAD

**Issue by fezi** [keycloak/keycloak#16959]
### Describe the bug

2 Weeks ago, you had this integrity sha-512 hash (snippet from package-lock.json of a project depending on you):

    "node_modules/keycloak-js": {
      "version": "20.0.1",
      "resolved": "https://registry.npmjs.org/keycloak-js/-/keycloak-js-20.0.1.tgz",
      "integrity": "sha512-nd84PGuZZaU32iTvNYkHyw8UvmO6b6k9hCu/7kftwSaYTmOytQG9eK3DyL6idHmZQFHwz8QhJnqzEJYUtgmDIQ==",
      "dependencies": {
        "base64-js": "^1.5.1",
        "js-sha256": "^0.9.0"
      }
    }

Now it looks like you changed the release binary (tgz) after the release. I am getting security warning because of this. Have you been hacked?

    "node_modules/keycloak-js": {
      "version": "20.0.1",
      "resolved": "https://registry.npmjs.org/keycloak-js/-/keycloak-js-20.0.1.tgz",
      "integrity": "sha512-YNj0X0mmdLpqjB9W5DTAVDI14CzZs7RFn9T/t/g8Uq80OjaW2zZUis/g73aWwz04S3B6U6Vrg8h1wAMGbx2NQQ==",
      "dependencies": {
        "base64-js": "^1.5.1",
        "js-sha256": "^0.9.0"
      }
    },

### Version

5.0.1

### Expected behavior

Fingerprint of the npm artifact behind a fixed semver string remains constant over time. Use different version numbers if you need to re-release.

### Actual behavior

Fingerprint changes and causes security warnings and breaking build pipelines on your users' side.

**Comment by jonkoops** [comment]
This must be something that NPM itself has changed because it should not be possible to unpublish the package. Looking at the contents of the published package I am not seeing anything strange, so this must be some kind of fluke. If this does happen again in the future do let us know.
