### ISSUE TITLE
Not getting credentials when calling users find()

### ISSUE THREAD

**Issue by ignaciostellino** [keycloak/keycloak#16955]
### Describe the bug

I am calling the function .users.find() function with a query with the email value but I don't receive the credentials as response.
I am using keycloak/keycloak-admin-client 15.0.2

### Version

keycloak/keycloak-admin-client 15.0.2 / keycloak 18

**Comment by lvian** [comment]
Encountered the same issue.
Tried multiple implementatios of `users.find()` and the credentials are not present in the user representation

**Comment by ignaciostellino** [comment]
Any ETA for this issue?

**Comment by edewit** [comment]
there is a special endpoint to get the user credentials `users.getCredentials`
