### ISSUE TITLE
clients.update - defaultClientScopes or optionalClientScopes

### ISSUE THREAD

**Issue by dibenlloch** [keycloak/keycloak#16952]
### Describe the bug

Hi,
Testing some script for creating and updating clients i notice that clients.update is not working at least for defaultClientScopes or optionalClientScopes fields.

### Version

18

### Expected behavior

Related fields should be updated

### Actual behavior

Currently fields are not being updated (seems like being ignored)

### How to Reproduce?

Some example code.

```
await KcAdminClient.clients.update(
        { id: existing_client.id },
        { "defaultClientScopes": ["myFancyScope"] }
);
```
As result, no updates on Existing client. ("myFancyScope" exist)

By other hand, creation is working as expected.

```
await KcAdminClient.clients.create(
        { "clientId": "new_client" , "defaultClientScopes": ["myFancyScope"] }
);
```
Works without problems, create new client with defined scopes.

Tested update for other Array values from `ClientRepresentation` like "protocolMappers" and works perfect for that case. Only failing for ClientScopes related ones. 

### Anything else?

Tested with keycloak 14 and 18.
May be is related with some not implemented API functionality? Searching at google i see some post from 2019 https://lists.jboss.org/pipermail/keycloak-user/2019-January/016979.html

**Comment by edewit** [comment]
to add a client scope to a client you need to use the `addDefaultClientScope` or `addOptionalClientScope` functions

**Comment by cloudymax** [comment]
> to add a client scope to a client you need to use the `addDefaultClientScope` or `addOptionalClientScope` functions

how would this work with kcadm.sh?

**Comment by vfauth** [comment]
We have the same issue. Is a fix planned?

**Comment by edewit** [comment]
Just use addDefaultClientScope or addOptionalClientScope like the UI does, closing this issue

**Comment by kermakovich** [comment]
Hi @edewit. I've been exploring the Keycloak REST Admin API and saw method for updating client - `PUT /{realm}/clients/{id} `. It's mentioned that we can use the `ClientRepresentation` object, which includes `defaultClientScopes` and `optionalClientScopes`. It makes sense that the `PUT` method updates the entire entity rather than just a few fields.
So, if I'm understanding correctly, if I want to update both the `name` and `defaultClientScopes`, I'd need to use two different endpoints, right? 🤔 Is that the way it's supposed to work? If so, it might be helpful to update the documentation to reflect this. WDYT?

**Comment by JonasGroeger** [comment]
We just ran into the same issue. The API spec says you can send a [`ClientRepresentation`](https://www.keycloak.org/docs-api/latest/rest-api/index.html#ClientRepresentation) which includes

* `optionalClientScopes`
* `defaultClientScopes`

[On client creation, these fields are parsed](https://github.com/keycloak/keycloak/blob/78274ccc5da0c731d8393d77af1dbbabac31db91/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L402). On [client update, they are not](https://github.com/keycloak/keycloak/blob/78274ccc5da0c731d8393d77af1dbbabac31db91/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L419), although its the same ClientRepresentation!

If you update a client with these fields, you get a 2xx but if you check in the UI, they're not updated! You have to then use the `.../default-client-scopes` and `.../optional-client-scopes` APIs to actually finish updating the client.

Very counterintuitive...
