### ISSUE TITLE
await kcAdmin.users.find() does not return all user

### ISSUE THREAD

**Issue by valerii15298** [keycloak/keycloak#16954]
### Describe the bug

`await kcAdmin.users.find();` returns exactly only 100 users, while actually there 112 in my case...
In your docs and readme page is said that this method returns all users.

### Version

"@keycloak/keycloak-admin-client": "^18.0.2",

### Expected behavior

I should get all users!!!

### Actual behavior

I am getting only 100 users.

### How to Reproduce?

Add more than 100 users and run `await kcAdmin.users.find();`

### Anything else?

Please give workaround how to get all users.

**Comment by edewit** [comment]
it says in the endpoint doc that max defaults to a 100 https://www.keycloak.org/docs-api/18.0/rest-api/index.html#_users_resource

**Comment by valerii15298** [comment]
@edewit I meant docs in repo itself in readme: 
![image](https://user-images.githubusercontent.com/44531564/225758302-aba5d65d-c6ea-46ce-a2fb-60ec80d7e074.png)

Attached pull request.
