### ISSUE TITLE
Remove session as the wrong types

### ISSUE THREAD

**Issue by miguel-castro-nearseatech** [keycloak/keycloak#16960]
### Describe the bug

The removeSession method (same for deleteSession) have the wrong types. The URL is defined with the param `{session}`, but the method asks for a `sessionId`:
![image](https://user-images.githubusercontent.com/96583441/215077297-d82f06bf-25e3-40d2-85a3-b029595ceaa5.png)

This is what I had to do to make it work:
![image](https://user-images.githubusercontent.com/96583441/215077348-f0746ae6-cca7-4a10-86f1-839488baea84.png)

### Version

16

### Expected behavior

The method argument has `session` instead of `sessionId`

### Actual behavior

The method argument has `sessionId` instead of `session`

### How to Reproduce?

Just use the method respecting the normal types, it does not work.

**Comment by edewit** [comment]
this has been since been fixed
