### ISSUE TITLE
direct naked impersonation documentation is wrong

### ISSUE THREAD

**Issue by sorin-dragomir** [keycloak/keycloak#16965]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

I tried to implement Keycloak **direct naked impersonation** from documentation, but in the end I got the error:

```
"error": "access_denied",
"error_description": "Client not allowed to exchange"

```
I followed all the steps that are in the [Keycloak Direct Naked Impersonation documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html#direct-naked-impersonation).

The problem is that the documentation contains an image that is wrong, namely:

<img width="677" alt="7lNti" src="https://user-images.githubusercontent.com/46748880/217748762-302cee0f-899a-4933-9739-0b60e0cb646c.png">

It should have been a Client Policy with the client **admin-cli** instead of the user **admin**.

Perform the corect request:

```
curl -X POST \
    -d "client_id=admin-cli" \
    -d "client_secret=the client secret" \
    --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
    -d "requested_subject=wburke" \
    http://0.0.0.0:8080/realms/master/protocol/openid-connect/token
```

not what you have now

```
curl -X POST \
    -d "client_id=starting-client" \
    -d "client_secret=the client secret" \
    --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
    -d "requested_subject=wburke" \
    http://localhost:8080/realms/myrealm/protocol/openid-connect/token
```

In your documentation you started with **admin-cli**, then you used **admin** and in the end you used **starting-client**. These are 3 different variables that you used instead of just one: **admin-cli**

Plus for me to have this working I have to setup, inside keycloak admin, the **user-impersonate** also, to have direct naked impersonation to work.

### Version

20.0.3

### Expected behavior

I explained everything above

### Actual behavior

I explained everything above

### How to Reproduce?

I explained everything above

**Comment by pedroigor** [comment]
@sorin-dragomir Thanks. Should be fixed by https://github.com/keycloak/keycloak-documentation/pull/1774

**Comment by mposolda** [comment]
Docs PR merged, so closing this
