### ISSUE TITLE
Minimize the RPM content of the Operator container

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#16967]
* Investigate the possibility to do something similar to https://github.com/keycloak/keycloak/pull/16879.
* The aim is to reduce the container dependencies to minimum.
* We'd probably need to switch from [Jib](https://quarkus.io/guides/container-image#jib) to Docker.

**Comment by ASzc** [comment]
Product is going to need a Dockerfile to build, due to the separate Java and Container build systems. So, this enhancement seems to align with that?

**Comment by abstractj** [comment]
Hi @ASzc, today I had the opportunity to raise your question with our team. From what I understood from @vmuzikar, this enhancement will align with the plans of having a Dockerfile to build the container image. Is this something that you would like to investigate? If yes, that would be fantastic.
