### ISSUE TITLE
CRDB optimization: Optimize selects targeting the primary key or unique keys

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#16977]
### Description

With concurrent updates to the tables for UserSession and SingleUseObject, there are a lot of rolled back transactions due to failed serialization. 

When using optimistic locking on CRDB, the select statements around UserSession use the ID of the object, and add more conditions around the type of session (offline or not), and if the entity is expired. This might be one of the causes.

```
    select
        jpauserses0_.id as id1_40_,
        jpauserses0_.metadata as metadata7_40_,
        jpauserses0_.version as version11_40_
    from
        kc_user_session jpauserses0_
    where
        jpauserses0_.realmId=?
        and jpauserses0_.offline=?
        and jpauserses0_.id=?
        and (
            jpauserses0_.expiration>1675951377993
            or jpauserses0_.expiration is null
        ) for update
            of jpauserses0_
```

Queries around SingleUseObject don't use the primary key; this might be another cause. This could possibly be refactored to have the objectId as the primary key.See #13989 for a discussion why it is the way it is today (JPA storage can't store a non-UUID as a primary key with the current setup), and how this can be changed.

```
    select
        jpasingleu0_.id as id1_31_,
        jpasingleu0_.metadata as metadata4_31_,
        jpasingleu0_.version as version6_31_
    from
        kc_single_use_obj jpasingleu0_
    where
        jpasingleu0_.objectKey=?
        and (
            jpasingleu0_.expiration>1675951378891
            or jpasingleu0_.expiration is null
        )
```

The details of this issue contain now an experiment to see if by avoiding the suffixes on the select those serializations can be avoided. Issue #16976 should be implemented first so see if this approach unblock the issue. 

Efforts might be futile for features like "maximum number of user sessions per user in a realm", as those will run a broader query. 

Other queries for children like this might still interfere, but this remains to be seen:

```
    select
        clientsess0_.fk_root as fk_root6_21_0_,
        clientsess0_.id as id1_21_0_,
        clientsess0_.id as id1_21_1_,
        clientsess0_.metadata as metadata4_21_1_,
        clientsess0_.fk_root as fk_root6_21_1_,
        clientsess0_.version as version5_21_1_
    from
        kc_client_session clientsess0_
    where
        clientsess0_.fk_root=?
```

```
    select
        notes0_.fk_root as fk_root4_32_0_,
        notes0_.id as id1_32_0_,
        notes0_.id as id1_32_1_,
        notes0_.name as name2_32_1_,
        notes0_.fk_root as fk_root4_32_1_,
        notes0_.value as value3_32_1_
    from
        kc_single_use_obj_note notes0_
    where
        notes0_.fk_root=?
```

At the beginning of the task the list of SQL queries during login for both tables should be recorded to see if it to implement what's suggested here.

### Motivation

Performance is very bad on CRDB as a lot of transactions are retried for https://github.com/keycloak/keycloak-benchmark/issues/203. This is all about avoiding transactions to be rolled back due to problems with serializability.

### Details

Suggested changes to the JpaMapKeycloakTransaction: When the query contains an ID, use the ID to fetch the entity, and post-process the result with the other criteria.

In the case of UserSession, those queries would return for the happy path no value anyway.

A similar approach has been applied here to leverage that pessimistic locking is only available for query-by-ID on HotRot (kudos to @mhajas), see `#pessimisticQueryRead()`: 

https://github.com/keycloak/keycloak/pull/16619/files#diff-2cd58c3c33d4f93a5ff9b8262ffe66ebc3f375e1c7a3d519652a8e293d50bf5dR222-R265

**Comment by mhajas** [comment]
FYI: I needed to change the [`pessimisticQueryRead` method](https://github.com/keycloak/keycloak/pull/16619/files#diff-2cd58c3c33d4f93a5ff9b8262ffe66ebc3f375e1c7a3d519652a8e293d50bf5dR210-R265) to also support queries without a primary key, the reason is we have pessimistic query without id here:
https://github.com/keycloak/keycloak/blob/d768e75be7ff3754ea0cbebc4131e00208a7ac4a/services/src/main/java/org/keycloak/broker/oidc/KeycloakOIDCIdentityProvider.java#LL110C7-L110C103
