### ISSUE TITLE
Trivy Workflow failing with context deadline exceeded

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#16974]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

Trivy jobs are failing consistently with timeout and the message `context deadline exceeded`. The issue started 5 days ago, below it is possible to find the details:

```
2023-02-04T06:02:44.212Z	INFO	Analyzing JAR files takes a while...
2023-02-04T06:07:20.823Z	WARN	Increase --timeout value
2023-02-04T06:07:20.823Z	FATAL	image scan error: scan error: scan failed: failed analysis: analyze error: timeout: context deadline exceeded
```

Ref: https://github.com/keycloak/keycloak/actions/runs/4090263515/jobs/7053549164

### Version

>= 20.0.3

### Expected behavior

- Trivy checks passing

### Actual behavior

- Trivy checks failing

### How to Reproduce?

Review Trivy Jobs: https://github.com/keycloak/keycloak/actions/runs/4090263515/jobs/7053549164

**Comment by bruegth** [comment]
@abstractj FYI: My scan still timed out (even with 30mins), so I decide to use `--offline-scan` as described here:
https://aquasecurity.github.io/trivy/v0.27.1/docs/advanced/air-gap/#run-trivy-with-skip-update-and-offline-scan-option
With this option scan will take 30 sec again (but with with an smaller vuln db)

**Comment by abstractj** [comment]
@bruegth thank you, I will have that in mind if the issue persists.
