### ISSUE TITLE
Empty response with 200 status code when path disabled in policy-enforcer-config

### ISSUE THREAD

**Issue by billwenboli** [keycloak/keycloak#16984]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/spring

### Describe the bug

We have set enforcement mode for actuator related paths, such as `/actuator/health` and `/actuator/prometheus` to be DISABLED.  When we try to access these paths without getting the access token, we get an empty response with return code 200. With access token, we are able to get valid content back. We are just wondering if this is a bug from Keycloak interceptor/filter or we misconfigured the policy-enforcer-config?

### Version

20.0.3

### Expected behavior

`
{
	"status": "UP",
	"groups": [
		"liveness",
		"readiness"
	]
}
`

### Actual behavior

Empty

### How to Reproduce?

With the following configuration in application.properties:
`
  policy-enforcer-config:
    lazy-load-paths: false
    on-deny-redirect-to: /accessDenied
    paths[0]:
      path: /actuator/health
      enforcement-mode: DISABLED
    paths[1]:
      path: /actuator/prometheus
      enforcement-mode: DISABLED
`

**Comment by billwenboli** [comment]
For better readability on the config:

  policy-enforcer-config:
    lazy-load-paths: false
    on-deny-redirect-to: /accessDenied
    paths[0]:
      path: /actuator/health
      enforcement-mode: DISABLED
    paths[1]:
      path: /actuator/prometheus
      enforcement-mode: DISABLED

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
