### ISSUE TITLE
Changing realm id will not update relative URLs in `account-console` client

### ISSUE THREAD

**Issue by zotornit** [keycloak/keycloak#17010]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Tested in 20.03

Maybe this is intended, however:

**BEFORE**
![image](https://user-images.githubusercontent.com/45833403/218307109-59b242ad-557d-4101-944d-f75f1e7b59ef.png)

Now when you change the realm id to `testrealm-changed`
![image](https://user-images.githubusercontent.com/45833403/218307265-0642d317-a756-4a7c-b483-ead4e1a3aa2b.png)

The other default clients like `account` or `security-admin-console` get updated accordingly
![image](https://user-images.githubusercontent.com/45833403/218307286-e4d8c6e8-ea26-4841-83d1-13b4760c6e8f.png)

### Version

20.03

### Expected behavior

The relatives paths of default `account-console` client  for `Home URL`, `Valid redirect URIs` are getting updated accordingly when changing the realm id.

### Actual behavior

The relatives paths of default `account-console` client  for `Home URL`, `Valid redirect URIs` are NOT getting updated accordingly when changing the realm id.

### How to Reproduce?

1. create realm
2. change realm id
3. check relative urls in `account-console` default client

**Comment by ssilvert** [comment]
Yes, this is working as intended.  When you change the realm name, there is no way for keycloak to know if you also intend to change those URLs for account-console.
