### ISSUE TITLE
Allow custom message for brute force temporary lockout

### ISSUE THREAD

**Issue by Nogginboink** [keycloak/keycloak#17014]
### Description

When a user account is temporarily locked out due to too many invalid login attempts, Keycloak returns the standard 'invalid username or password' error message to prevent leaking information.

The realm (or client) administrator should be able to substitute a custom message here.

### Motivation

While the current behavior is the most secure behavior, it doesn't meet all business use cases. For many applications, particularly with consumers, returning a message such as "Your account has been temporarily locked out due to too many invalid logon attempts. Please try again in 15 minutes" may be a more appropriate response from the server.

The application owner should be allowed to make a tradeoff between security and usability based on his or her specific use case. Lowering support costs at the expense of leaking the existence of a user account ID, for example, may be an acceptable tradeoff. The application owner should be able to make this business decision.

**Comment by gilvansfilho** [comment]
I already did that once. Basically somethings should change at authenticators, which will need to check if user is blocked by brute force and, if so, thrown meaningful messaging. So, perhaps I could work on that.

Thinking about something like (1) adding a new option to the brute force interface like "send meaningful message?" so that authenticators will be able to verify this and decide which message to send. Default value of that new option should be `false` so behaviour remains equals as older versions.

Wdyt about?

**Comment by douglaspalmer** [comment]
This would be better handled with separating the messages in the message bundle. Those who wish to distinguish between login failures and lockouts can do so by overriding the message with a custom theme.

**Comment by gilvansfilho** [comment]
Relying on themes gives the admin the flexibility to comfig behaviour based on each client needs but will require a custom theme for that what can be a blocker for some users.

Relying on new realm attribute allow a more easy way to use the feature but would be harder to allow a by client config.

What is preferred?

**Comment by douglaspalmer** [comment]
> Relying on themes gives the admin the flexibility to comfig behaviour based on each client needs but will require a custom theme for that what can be a blocker for some users.
> 
> Relying on new realm attribute allow a more easy way to use the feature but would be harder to allow a by client config.
> 
> What is preferred?

In my opinion requiring a custom theme is definitely preferred as using this behaviour should be discouraged. It gives attackers information about the system allowing them to circumvent the brute force protection and also poses a significant DOS risk.

**Comment by gilvansfilho** [comment]
I agree that from security POV show more meaningful messages is not the best choice but also think should be granted to admin user the option to define the desired behaviour in a more easy way than extendind themes.

Default value could be the suggested one (dont show meaningful messages) and docs could alert about security questions.

Perhaps we need more opinions here.

**Comment by hppzone8** [comment]
There should be an option to display the account lock message, and it should be up to the implementer to decide whether to show it or not.

**Comment by hyutopy** [comment]
There should be an option to display the account lock message, and it should be up to the implementer to decide whether to show it or not.
