### ISSUE TITLE
DB racing condition on installation

### ISSUE THREAD

**Issue by mvk37** [keycloak/keycloak#17017]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

I created a docker with Keycloak 20.0.3 to install in kubernetes. Found that if I install more then one pod only one pod will start. All other are failing with error:
 
`SQL Error: 1062, SQLState: 23000. Duplicate entry 'master' for key 'UK_ORVSDMLA56612EAEFIQ6WL5OI'`

And I reproduced it with two Keycloaks on a bare metal. Database is MariaDb.

I have a docker with WildFly Keycloak and never saw this problem before. Looks like a regression. This issue make several instances of Keycloak more complicated.

Attaching Keycloak's logs from simple test when two Keycloaks starting same time. One of them starting (kc_log2.log)  and another not (kc_log1.log). 
[kc_log1.log](https://github.com/keycloak/keycloak/files/10717550/kc_log1.log)
[kc_log2.log](https://github.com/keycloak/keycloak/files/10717551/kc_log2.log)

### Version

20.0.3

### Expected behavior

When several Keycloak instances deployed same time all of them starting successfully. 

### Actual behavior

See description and logs

### How to Reproduce?

This is my test on Rocky8.

# Install mariaDb
dnf install mariadb-server
systemctl start mariadb

# Create database and user for Keycloak
mysql -u root
create database db4keycloak;
GRANT ALL PRIVILEGES ON db4keycloak.* to keycloak@'%' IDENTIFIED BY 'pw'; 
GRANT ALL PRIVILEGES ON db4keycloak.* to keycloak@'localhost' IDENTIFIED BY 'pw';
flush privileges;
exit   

# Create 2 directories with Keycloaks
wget https://github.com/keycloak/keycloak/releases/download/20.0.3/keycloak-20.0.3.tar.gz
tar xvzf keycloak-20.0.3.tar.gz
cp -r keycloak-20.0.3 keycloak-20.0.3_1
cp -r keycloak-20.0.3 keycloak-20.0.3_2

# Start 2 Keycloak instances same time
./keycloak-20.0.3_1/bin/kc.sh start-dev \
--db=mariadb \
--db-url-host=127.0.0.1 \
--db-username=keycloak \
--db-password=pw \
--db-url-database=db4keycloak \
--log=console,file \
--log-file=/home/test/kc_log1.log &

./keycloak-20.0.3_2/bin/kc.sh start-dev \
--db=mariadb \
--db-url-host=127.0.0.1 \
--db-username=keycloak \
--db-password=pw \
--db-url-database=db4keycloak \
--http-port=8081 \
--log=console,file \
--log-file=/home/test/kc_log2.log &

**Comment by sschu** [comment]
I agree this should not happen. However, you should run Keycloak in Kubernetes as a Stateful Set where pods start up sequentially anyways since Infinispan in the legacy store might have problems initialising caches if nodes start up concurrently. Then you also won't run into your problem.

**Comment by ahus1** [comment]
This is a duplicate to #16642. A fix will part of the upcoming KC21 release.
