### ISSUE TITLE
Allow configuring of redirectUri for the cordova adapter

### ISSUE THREAD

**Issue by nerumo** [keycloak/keycloak#17037]
### Description

Make the redirectUri configurable for the keycloakjs cordova adapter.

### Motivation

We have a cordova app that isn't using `http://localhost` as its base address. Therefore, the return address must be something different (https://whatever.com). We are actually loading a PWA into the cordova container.

But in the code, the `http://localhost` is static. Therefore, a configurable redirectUri for the cordova adapter would solve our issue.

### Details

if configured, use the redirectUri parameter from the config object and fall back to 'http://localhost' if not provided.

**Comment by jonkoops** [comment]
Seems like a valid concern, I'll take a look at your PR :+1:
