### ISSUE TITLE
quarkus-keycloak-admin-client-reactive does not getAuthorizationSettings

### ISSUE THREAD

**Issue by bigglesandginger** [keycloak/keycloak#17042]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

When using a Keycloak client configured with Authorization (there are two Resources, two Scopes, and two Permissions configured, viewable in the Keycloak UI, and work with the `@Authenticated` annotation), the admin-client fails to extract the AuthorizationSettings, simply returning NULL.

```
        List<ClientRepresentation> clients = keycloak.realm("realmname").clients().findByClientId("clientname");
        ClientRepresentation appClient = clients.get(0);
        if (appClient.getAuthorizationServicesEnabled()) {
            ResourceServerRepresentation authz = appClient.getAuthorizationSettings();
            List<ResourceRepresentation> resources = authz.getResources();  // <--- Fails with NPE
            return resources;
        }
```

### Version

20.0.3

### Expected behavior

I am expecting that `ClientRepresentation.getAuthorizationSettings()` returns a usable `ResourceServerRepresentation` object.

### Actual behavior

```
java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.authorization.ResourceServerRepresentation.getResources()" because "authz" is null
	at software.uncharted.RolesResource.getPermissions(RolesResource.java:40)
	at software.uncharted.RolesResource$quarkusrestinvoker$getPermissions_63cdc876fbca54bedb90a9e84f307b6ccb49314b.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

To reproduce I am using the example found here: https://quarkus.io/guides/security-keycloak-admin-client and simply changing the getRoles function to a getPermissions function with the code above.  However, one needs a Keycloak with Authorization permissions set up.

Here is a `testrealm.json` with two permissions: https://gist.github.com/bigglesandginger/78500e9de2ee4298c8640a61dcba6bf1

### Anything else?

I ran the process again with Wireshark sniffing the traffic and the response from the Keycloak server (I assume from the call clients.get(0) is https://gist.github.com/bigglesandginger/912592a7643601b73198bf9af3518813

When I asked the Quarkus team, @sberyozkin says: "ResourceServerRepresentation authz = appClient.getAuthorizationSettings();, ClientRepresentation is a bean, appClient.getAuthorizationSettings() returns whatever related was returned in ClientRepresentation. So Keycloak does not return this info"

If Keycloak does not return this info, then is the `ClientRepresentation` incorrect, or is Keycloak failing to return the `ResourceServerRepresentation` obeject, or is there an additional call (not documented) that needs to be called to populate this information?

**Comment by sberyozkin** [comment]
Thanks @bigglesandginger, Hi @pedroigor please comment, my guess Keycloak has to be configured at startup to return this info

**Comment by pedroigor** [comment]
@bigglesandginger In order to obtain the settings, you should obtain an `AuthorizationResource` instance by calling `ClientResource#authorization`. Then you can call `AuthorizationResource#getSettings` to obtain the settings.

**Comment by bigglesandginger** [comment]
How does one translate a `ClientRepresentation` into a `ClientResource` ?  Create a `new ClientResource()` and then `clientResource.update(clientRepresentation)` ?  The JavaDocs are a bit light on details.

**Comment by pedroigor** [comment]
@bigglesandginger Yeah, docs are not so good for the admin client.

The `ClientResource` is an interface and the JAX-RS Client creates a proxy at runtime to call the target endpoint. To update a client you usually call `clientResource.toRepresentation` to obtain a `ClientRepresentation` and then call `update`.

For authorization settings, you should do the same thing but using the `AuthorizationResource`.

**Comment by bigglesandginger** [comment]
Trying to use the admin client to read from Keycloak is really tough.  Objects get created but have no data, and finding a call that populates the object is an exercise in poking all the bears.  To the point where it might be easier to say, that  cURL interface appears more usable, and calling out to the shell from the Java service is not the hardest thing.  But some Java purists are going to be very annoyed.  I will fight for one more day and then either post some findings, or see if using cURL is more straight forward.

**Comment by bigglesandginger** [comment]
A big problem seems to be that https://www.keycloak.org/docs-api/20.0.3/rest-api/index.html does not detail all the rest-api calls available - specifically all the Permission calls.  There are no `.../clients/<id>/authz/...` calls detailed, so working with permissions from any admin is next to impossible.  Can these be documented?

**Comment by bigglesandginger** [comment]
I will add this code example here for others wondering how to go beyond the features of the quarkus-keycloak-admin-client-reactive

This is a simple example of adding a role to a user

https://gist.github.com/bigglesandginger/abaca7bb43e6eab6e696cff52f3386f8
