### ISSUE TITLE
Search an user with a space character

### ISSUE THREAD

**Issue by KennyMk-stack** [keycloak/keycloak#17041]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

I have an user who has "Kenny Mk" as a login.

If i type "Kenny Mk" in the search field area on the keycloak admin interface in the user section, i do not find him.

If i send an http GET request to my local admin API to retrieve it with a search parameter, with NodeJs and Fetch, i do not find him.
Even if i force encodeURIComponent on the search string, it will yield an url like : `"http://localhost:9090/admin/realms/arkyan/users?search=Kenny%20Mk"` and not working.

While an URL like
`"http://localhost:9090/admin/realms/arkyan/users?search=Kenny%40Mk@github"` will work. 

### Version

18.0.2

### Expected behavior

I expect the aforementionned user to be found either with my get request on in the interface.

### Actual behavior

Users with a space in their login is not found.

### How to Reproduce?

Create a user with a space in his Login and try to retrieve it either with the UI or with an admin API request through the "search" parameter.

**Comment by pedroigor** [comment]
Not sure if we are supposed to allow spaces in user names.

The server will split the value using `\\s+` so that the first value (e.g.: `Kenny`) ends up in a predicate like `%Kenny`.

If you are using user profile, you should be able to set validators to avoid usernames with spaces too.

Closing it as we do not have plans to fix it.

**Comment by KennyMk-stack** [comment]
Ok thanks you for your answer!
In fact i found out the right way to achieve what i want is to use the parameter "username" instead of "search". With exact mode enabled, spaces are correctly factored in.

**Comment by lrozenblyum** [comment]
Thanks for sharing @estin68! In which Keycloak version have you tested this? 
In 22.0.5 unfortunately asterisk also doesn't work.

![изображение](https://github.com/keycloak/keycloak/assets/1285898/110df8cf-590e-43db-a98d-f154994847fd)
![изображение](https://github.com/keycloak/keycloak/assets/1285898/51456ad9-e002-40ef-9782-cb144549f005)

**Comment by estin68** [comment]
Interesting, I tried in both version 21.1.2 and latest 23.0.3., and both works for me. I'll try it version 22 and let you know.
