### ISSUE TITLE
Remove `clientRole` flag from `HotRodRoleEntity`

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#17086]
If we need a no-downtime upgrade (20-21) we need to create an issue with milestone KC 22 for removing [this](https://github.com/keycloak/keycloak/blob/main/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/role/HotRodRoleEntity.java#L106-L108), otherwise, we can remove it in this PR.

_Originally posted by @mhajas in https://github.com/keycloak/keycloak/pull/17083#pullrequestreview-1297650016_

**Comment by mhajas** [comment]
As part of this issue, we should also increase [`HotRodRoleEntity` entity version](https://github.com/keycloak/keycloak/blob/main/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/role/HotRodRoleEntity.java#L48)
