### ISSUE TITLE
`getUsersCount` methods in MapUserProvider are using default ineffective implementations

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#17084]
The default implementations of the following methods are reading all objects from the storage:
https://github.com/keycloak/keycloak/blob/2711606a701a0debaf8221602a337e751c63dfc5/server-spi/src/main/java/org/keycloak/storage/user/UserQueryProvider.java#L63-L135

We should create a new implementation for `MapUserProvider` that leverages [`MapKeycloakTransaction#getCount(QueryParameters<M> queryParameters)`](https://github.com/keycloak/keycloak/blob/2665fb01a639891427481aaf5d323569bfd3e7a6/model/map/src/main/java/org/keycloak/models/map/storage/MapKeycloakTransaction.java#L78)

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
