### ISSUE TITLE
FIPS tests marked in GH actions as passing even if they are failing

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#17106]
For example see this PR https://github.com/keycloak/keycloak/pull/16876 and then click to `FIPS IT (non-strict)` from the list of GH actions tests and then click to `Run base tests` when you have underlying PR opened.

There are 2 issues:
- FIPS tests are marked as passing even if they are failing. This needs to be changed to actually make sure that GH actions are failing when any FIPS test failing. Looks like the issue is, that docker command returns `0` even if testsuite failing? Hopefully we can figure it

- Fix testsuite failures itself. Looks like some of the failures are caused by the `KeycloakFipsSecurityProvider.isSystemFipsEnabled` doesn't properly work in GH actions fips environment. As step1, we can possibly just comment calling of `KeycloakFipsSecurityProvider.isFipsEnabled` ? Then we can try to make it working as a follow-up though?

**Comment by rmartinc** [comment]
yes, I had also detected the same yesterday. The problem is the pipe when executing the maven. I have set `set -o pipefail` in teh script before and podman is return 1 locally.
I fixed this one in this PR https://github.com/keycloak/keycloak/pull/17110
