### ISSUE TITLE
Introduce development guide with no-downtime steps for each scenario

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#17114]
Currently, we have some materials on how to achieve no-downtime upgrades for Keycloak with regard to the removal/addition of fields or indexes. However, none of them is written in a way that can be followed when making actual migration.

We should introduce some kind of development guide where we would capture all steps that one can follow when performing some migration, maybe even with some examples. 

Existing materials:
https://github.com/keycloak/keycloak-community/blob/main/design/keycloak.x/storage-hot-rod.md
https://github.com/infinispan/infinispan/blob/main/client/hotrod-client/src/test/java/org/infinispan/client/hotrod/evolution/IndexSchemaNoDowntimeUpgradeTest.java

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
