### ISSUE TITLE
`Enabled` and `Active` toggles for realm keys are not saved

### ISSUE THREAD

**Issue by moritzschmitz-oviva** [keycloak/keycloak#17123]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I cannot change the status of realm keys after I made them passive: https://www.keycloak.org/docs/latest/server_admin/#making-keys-passive. Clicking `Enabled` and/or `Active` and then `Save` doesn't change the status. Even when the `Active` toggle is set to `Off` the key still shows up under the active keys.

Additional minor annoyance: Clicking `Cancel` in the `Edit Provider` view doesn't do anything.

### Version

20.0.3

### Expected behavior

I expect the status of the toggles for `Enabled` and `Active` to be saved when clicking `Save`. If there is an error with saving, I expect to see an error message.

### Actual behavior

Changing the toggle status for `Enabled` and/or `Active` and then clicking `Save` is not persisted. In fact it seems the toggles have no purpose, since the keys also still show up under active keys.

### How to Reproduce?

Follow steps here: https://www.keycloak.org/docs/latest/server_admin/#adding-a-generated-keypair
Then do this: https://www.keycloak.org/docs/latest/server_admin/#making-keys-passive
Check keys show up as passive keys.
Now again, activate the keys, be editing the provider again and change the `Active` toggle to `On`, then click `Save`.

**Comment by moritzschmitz-oviva** [comment]
I have to add I can also create a state where the same `kid` shows up under both `Disabled keys` and `Active keys`.

**Comment by moritzschmitz-oviva** [comment]
https://user-images.githubusercontent.com/109514955/219027005-1883aaed-9abf-458e-80e7-55408b410571.mov

**Comment by rmartinc** [comment]
@moritzschmitz-oviva I think that this is a problem in the new console with the boolean toggles (issue https://github.com/keycloak/keycloak-ui/issues/3819). Can you please try with [the nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly) and check if the toggles are OK?

**Comment by moritzschmitz-oviva** [comment]
@rmartinc Was able to confirm it works with the nightly. But the nightly has some other problems :-D

Will close this. My problem was indeed only visual. Keys have been working as expected when using the Admin REST API.
