### ISSUE TITLE
Theme & Provider folder empty in KeyCloak 20.0.3

### ISSUE THREAD

**Issue by zzador** [keycloak/keycloak#17130]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

The documentation and nearly all online tutorials advice to take an existing theme in the subfolder "theme" and extend it to specific needs. The theme folder however is empty and there is absolutely NO TEMPLATE to start from. I don't even know where and how to start. Seriously guys: It would be quite more helpful to work on the documentation instead of adding features to keycloak. It has cost my company a week of work alone just to get keycloak running together with an old JSF1.5 App because nothing is documented correctly.

### Version

20.0.3

### Expected behavior

Well documented

### Actual behavior

Very poorly documented

### How to Reproduce?

Try to theme your keycloak login with the help of the keycloak documentation and the current server download (v 20.0.3)

**Comment by sventorben** [comment]
You can find themes [here](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme).

Documentation is maintained at https://github.com/keycloak/keycloak-documentation. Maybe try a contribution or file an issue there if something is wrong.
