### ISSUE TITLE
Referrer-policy should be default value

### ISSUE THREAD

**Issue by naveenbharadwaj-nc** [keycloak/keycloak#17138]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Our application relies on referer header to identify the request is coming from a trusted domain. Keycloak has no-referer as default referrer-policy and swallows the referer header. During authentication, our application sends a request to Keycloak with referer header. When the control returns to our application from Keycloak, there is no referer header. I can see many users are facing similar problems because of this Keycloak change. 
Why shouldn't Keycloak use default `strict-origin-when-cross-origin` policy according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy ?
Why is it not even customizable?

### Version

18.0.2

### Expected behavior

referer header must be present

### Actual behavior

referer header is absent

### How to Reproduce?

During OpenID authentication flow, we create an authenticationRequest and send it to Keycloak according to OAuth2 and OpenID standards. We send referer header to Keycloak as well. Keycloak performs authentication successfully and returns control to relying party. Relying party does not receive referer header

**Comment by pedroigor** [comment]
@naveenbharadwaj-nc Why not use the state parameter to verify if the response can be trusted?

Based on [OAuth 2 Security Best Practices](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-4.2.2), additional care should be taken when using the `Referrer` header. In our case, I think we choose to not send it at all but rely on the `state` parameter sent by the client to allow it to verify if the  response from the server is related to an authorization request previously sent.

**Comment by naveenbharadwaj-nc** [comment]
We do that already on server side. After this, we redirect back to UI page. And problem occurs there, because OpenID is not the only authentication mechanism we support. 
The problem during display of UI page is that we need to show an error message if there was some problem during authentication. For this, we use a URL parameter. Now, if someone opens a page with this URL parameter, we simply show that error message even though actual authentication was not even triggered. It is a content spoofing vulnerability. We need a way to check that the authentication happened and then the UI page was shown. For that we check if referer header is present.

**Comment by pedroigor** [comment]
I see. I'm not sure if we want to handle Referrer like that but I see improvements to the security header filter provider so that you could customize this behavior.

One thing you can though is to set this response header in your proxy if that works for you.

Another option is creating your own https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/headers/DefaultSecurityHeadersProvider.java.
