### ISSUE TITLE
UPDATED_PASSWORD user action shouldn't be triggered when login with linked IdP

### ISSUE THREAD

**Issue by asgarciap** [keycloak/keycloak#17155]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

A user account which have an external Identity Provider linked has an UPDATE_PASSWORD action (because his local password was expired).
When the user logins with an external Identity Provider that is linked to his account, keycloak is asking to update his local password eventhough the user haven't userd his local credentials to login. This behaviour is confusing for the user and I think is incorrect since the action should be trigered only when the user use his local credentials (the expired password) to login.

![image](https://user-images.githubusercontent.com/5125146/219498058-7f1a39e6-4a5e-4514-8011-b3959ba556c1.png)

![image](https://user-images.githubusercontent.com/5125146/219498310-9f9cc492-9c36-45b1-b372-01031c16348a.png)

### Version

20.0.3

### Expected behavior

The UPDATE_PASSWORD action shouldn't be triggered if the user didn't use his password to login. If for example the user uses a linked IdentityProvider to login, keycloak shouldn't ask to update his local password

### Actual behavior

Keycloak is asking the user to update his password eventhough the user didn't use his password to login (the user is using an external linked IdP)

### How to Reproduce?

Having a user with a linked external IdP
Add the UPDATE_PASSWORD required action to the user
Login to the account using the external IdP

**Comment by shwethamittur** [comment]
Hi! Is there any workaround to avoid this issue if we want to avoid the UPDATE_PASSWORD for a external Identity Provider user?

**Comment by graziang** [comment]
A way to detect the authentication method in this case could be to set an auth note during the password verification process. This way should be possible to use this note to assign the required action in the `UpdatePassword.evaluateTriggers` only if a password is used for login.

On the other hand, there might be use cases where the user's password still needs to be updated regardless of the authentication method.
@mposolda WDYT?

**Comment by jcputney** [comment]
@mposolda @graziang am I missing something? The merged PR only seems to bypass password update if the password is expired, not if the user has UPDATE_PASSWORD set as a required action, which was the original issue.

**Comment by graziang** [comment]
Hi @jcputney, yes the PR only bypass password update if the password is expired. 
But this was done to give admins the ability to manually add the UPDATE_PASSWORD action and force the user to update their password in any case. 

Do you think it might be better to bypass the password update in any case when you are not using the password to login?

**Comment by jcputney** [comment]
@graziang that seems to be the expectation from our users, and honestly feels like the right way to handle the situation. If I didn't use a password to login through Keycloak, then my password status shouldn't matter.
