### ISSUE TITLE
User locale in server info has language and country switched around

### ISSUE THREAD

**Issue by dalbani** [keycloak/keycloak#17154]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Under `Server Info` > `System`, the `User Locale` field contains values like `us_EN`.
The correct notation is the other way around, i.e. `en_US`.

### Version

20.0.3

### Expected behavior

The locale should be displayed according to the commonly accepted format (`language_COUNTRY`).

### Actual behavior

The locale is displayed according to this invalid format (`country_LANGUAGE`).

### How to Reproduce?

Go to `Server Info` > `System` and look at the `User Locale` field.

### Anything else?

This can easily be fixed by swapping around the arguments to the `Locale()` constructor at https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/info/SystemInfoRepresentation.java#L65.

**Comment by dalbani** [comment]
And why not simply rely on `Locale.getDefault()` by the way?

**Comment by rmartinc** [comment]
@dalbani Yep, you are right. Both solutions you are proposing looks good to me. Why don't you send a little PR for the change?

**Comment by dalbani** [comment]
Yep, I can pick that up.

Speaking of the format of the locale string, there's apparently even a discussion whether `en_US` (underscore) or `en-US` (dash) is the correct one: https://stackoverflow.com/questions/4904803/en-us-or-en-us-which-one-should-you-use.
