### ISSUE TITLE
build wildfly server-dist from the building doc

### ISSUE THREAD

**Issue by suichangyin** [keycloak/keycloak#17164]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

with the release of 20.0.0, the wildfly server-dist has been removed, but the build doc not up-to-date.

https://github.com/keycloak/keycloak/commit/390c7485c78db6face9509e2f2e03ec118917f06

To build only the server run:
mvn -Pdistribution -pl distribution/server-dist -am -Dmaven.test.skip clean install

please update the build doc to up-to-date.

### Version

20.0.0

### Expected behavior

build success

### Actual behavior

build fails

### How to Reproduce?

build server from source code

**Comment by sschu** [comment]
There is already a PR for this: https://github.com/keycloak/keycloak/pull/16924

**Comment by ahus1** [comment]
@suichangyin - thanks for noting this, and @sschu for pointing to the existing PR. I assume it will be merged shortly.
