### ISSUE TITLE
Got http 502，when restart docker

### ISSUE THREAD

**Issue by pipinet** [keycloak/keycloak#17167]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

i start keycloak use docker compose , when i stop and start docker compose, got 502.

### Version

20.0.3-0

### Expected behavior

Expected refresh successed.

### Actual behavior

got 502 error.

### How to Reproduce?

https://github.com/pipinet/keycloak-issues

1、start keycloak with command: docker compose up -d 
2、login keycloak admin
3、restart keycloak with command: docker compose down && docker compose up -d
4、refresh web
5、got 502

### Anything else?

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/6096680/219652347-c7a74623-745c-4f59-a204-a4d03095a54f.png">

_No response_

**Comment by pipinet** [comment]
https://github.com/pipinet/keycloak-issues

**Comment by pshafer-als** [comment]
Are you using nginx as a reverse proxy to keycloak?  If so, have you already tried [increasing the proxy buffer size](https://github.com/keycloak/keycloak/issues/16850#issuecomment-1419083335) in the nginx configuration?

**Comment by pipinet** [comment]
@pshafer-als tks, got it.

**Comment by mabartos** [comment]
It depends on the configuration of nginx itself. I'm afraid that we're not able to do more in this case related to the nginx configuration. Only probably mention this stuff in the documentation and possibly explicitly increase the proxy buffer size for default Ingress in Keycloak Operator. 

@vmuzikar WDYT?

**Comment by stianst** [comment]
Closing as this is not a Keycloak issue
