### ISSUE TITLE
Admin console theme/template is the old one

### ISSUE THREAD

**Issue by libertosurf** [keycloak/keycloak#17163]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The admin console template/theme from org.keycloak.keycloak-themes-20.0.3.jar is still the legacy one (prior to quarkus) and doesn't provide the same set of functionalities.

### Version

20.0.3

### Expected behavior

Expected behaviour would be to have the new UI theme/template with the same menus, etc available

### Actual behavior

Actual behaviour is that the template is the one from the legacy UI.
Also, some menu items are only specific to this theme (partial import/export, for instance)

### How to Reproduce?

- Extract the admin template from the jar in the theme folder (create a parent folder with the theme name first of course)
- Choose this template in the Admin UI
- The admin console now has the old UI instead of the new one.

**Comment by ssilvert** [comment]
@libertosurf I'm not really sure what to make of this issue.  I'm not sure why you would want to extract anything from the theme jar.  But it doesn't really matter because as of the latest build the legacy admin UI is completely gone.

FWIW, partial import/export is available in both.

I'm going to close this since we no longer ship the bits for the legacy admin console.

**Comment by libertosurf** [comment]
Maybe I misunderstood the doc but I thought this is how you were supposed to create a new theme. See https://www.keycloak.org/docs/latest/server_development/#creating-a-custom-html-template

First item in the procedure is "Copy the template from the base theme to your own theme.". Keycloak ships with an empty theme folder by default, so I got it from the jar mentioned above.

If I'm wrong I would like to know what is the correct procedure.
