### ISSUE TITLE
Ability for users to view credentials without manage user permissions

### ISSUE THREAD

**Issue by eatikrh** [keycloak/keycloak#17174]
### Description

There is a need for Customer Service to view OTP status of the users. This is done through the Admin Console.  Currently "manage-users" permission is necessary to view the "credentials" tab. This is enforced in both Java code and in the templates. We are proposing that a read-only version of the "credentials" tab under "user management" displays for the users that have "view-users" permission.

### Motivation

Customer Service cannot analyze the customers' OTP setup and other authentication setup related problems without "manage-users" permission. Manage-users privilege is a powerful one and it is not normally given to Customer Service representatives. This results in such problems quickly escalating to CIAM developers and it is slowing down customer issue resolution. 

### Details

Is it possible to have "requireManageOrView" method in UserPermissions and not transmit secrets if the user only has  view permissions?

In //keycloak/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java we have:
```java
    @GET
    @Path("credentials")
    @NoCache
    @Produces(MediaType.APPLICATION_JSON)
   public Stream<CredentialRepresentation> credentials(){
        auth.users().requireManage(user);
        return user.credentialManager().getStoredCredentialsStream()
                .map(ModelToRepresentation::toRepresentation)
                .peek(credentialRepresentation -> credentialRepresentation.setSecretData(null));
    }
```

This is also enforced at the UI templates:/themes/src/main/resources/theme/base/admin/resources/templates/kc-tabs-user.html
```html
<li ng-class="{active: path[4] == 'user-credentials'}" data-ng-show="user.access.manage"><a href="#/realms/realm.realm/users/user.id/user-credentials">:: 'credentials' | translate</a></li>
```

We would also need to make sure that the form in /themes/src/main/resources/theme/base/admin/resources/partials/user-credentials.html is read only.

**Comment by alechenninger** [comment]
Another possible alternative, which accomplishes the same end goal, is a separate role for viewing credentials (e.g. "view-credentials").

**Comment by eatikrh** [comment]
Adding a separate role (e.g. view-credentials") is probably the better way. We would not be changing the exiting behavior.  If we get a "green light" to go ahead with the implementation  tenant 'admin + access' is willing to take on the development.

**Comment by pedroigor** [comment]
Yeah, if we want to support the use case herein described we should probably support a separate role. Credentials are too sensitive to be accessed with `view-users` role.

Another point for a separate role is that users are already relying on the existing access controls and allowing `view-users` to access credentials is probably something they don't want.

**Comment by alechenninger** [comment]
`view-users` already does not reveal secrets, right, since those should never be returned via API?

```
                .peek(credentialRepresentation -> credentialRepresentation.setSecretData(null));
```

As such perhaps it is fine to extend viewing non-secret credential information to any admins which already can view users and their attributes.

**Comment by eatikrh** [comment]
I created a bug ticket about this functionality (https://github.com/keycloak/keycloak/issues/20783) users with "view-users" permission should be able to invoke /auth/admin/realms/<realm>/users/<userid>/configured-user-storage-credential-types endpoint (https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L682) Can we comment on https://github.com/keycloak/keycloak/issues/20783? It also has security implications.
