### ISSUE TITLE
org.keycloak.Config.Scope provided for method "init(Config.Scope scope)" in interface org.keycloak.events.EventListenerProviderFactory, always returns an empty set when calling "scope.getPropertyNames()"

### ISSUE THREAD

**Issue by LuxTheDude** [keycloak/keycloak#17175]
### Before reporting an issue

- [x] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

As the title states.

I am implementing an EventListener SPI, and need to pass arguments to it via Config.Scope.

Calling scope.get("someproperty") correctly returns the corresponding value, but regardless scope.getPropertyNames() always returns an empty set. 

### Version

20.0.3

### Expected behavior

When Config.Scope contains properties, I would expect scope.getPropertyNames() to return a set containing all property keys.

### Actual behavior

When Config.Scope contains properties, scope.getPropertyNames() to returns an empty set.

### How to Reproduce?

1. Build a jar containing an event listener spi.
2. Run keycloak with this spi in providers folder, and provide configurations for the SPI via command line, environment variables or .conf file.
3. Notice that calling scope.get on provided properties yields those properties values, but scope.getPropertyNames() yields an empty set.

Refer to keycloak documentation for instructions on how to do step 1 and 2.

**Comment by mposolda** [comment]
Can be nice to fix, but I don't see this as big priority as developer should know what are property names, which he is trying to see.

I am adding to Backlog as I am not sure if Keycloak team will have opportunity to look at this in the near future. Everyone is welcome to investigate and send PR for this. Please take a look at https://www.keycloak.org/community to the "Contributors" section for the details.

**Comment by LuxTheDude** [comment]
I see how it might not be a big priority for the Keycloak team.

But the argument that the developer should know the property names is invalid. I need my EventListener to take a dynamic amount of properties. Being able to programmatically see which properties are available, would benefit me greatly, as it removes the need for me to keep a list of possible values, that I have to update each time a new property is added, which also forces me to recompile and rebuild my containers.

Hopefully I can find time to make this fix myself and send PR.

Thanks for the reply.
