### ISSUE TITLE
LDAP Filter with increasing number of groups it becomes difficult for keycloak to filter out groups from LDAP

### ISSUE THREAD

**Issue by demonappolyon** [keycloak/keycloak#17183]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Added an AD server with keycloak and created mappers to pull group from AD
in LDAP filter field added filter : (cn=group1) , (cn=group2) and synced LDAP groups to keycloak
which  works without issues 
The moment we try to add more number of filters i.e. (cn=group1) , (cn=group2) ... (cn=group10) and tried to sync groups
keycloak was able to pull 1st to 3 groups and after multiple synchronization group with keycloak  calls it was able to sync 7 groups
where as with no filter it was able to pull in all the groups.

### Version

19.0.1

### Expected behavior

with multiple filters as well we should be able to synchronize LDAP groups without any issues

### Actual behavior

not able to synchronize groups on the basis of multiple filters. 

### How to Reproduce?

Add LDAP details to keycloak which has multiple groups 
in Group mapper filter add multiple filtering values and try to synchronize LDAP groups with keycloak

**Comment by hmlnarik** [comment]
Please beware `(cn=group1) , (cn=group2)` is not a valid LDAP filter. The filter needs to respect LDAP syntax which apparently looks to be `(|(cn=group1)(cn=group2)(cn=group3))` (update the groups accordingly).

Then I was unable to see any performance implications on Keycloak side.

Coould you please update your filter and check if it helps?

**Comment by ahus1** [comment]
Closing this issue as there wasn't a reply for several weeks and we need more information to triage this. Please comment/reopen this issue, or open a new issue.
