### ISSUE TITLE
It stop to print users on Membership tab

### ISSUE THREAD

**Issue by MariiaAlekseichuk** [keycloak/keycloak#17193]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Not all users on Membership tab for Group are printed in case if there are users which are in current Group but not fit the Custom User LDAP Filter. It just stops print other users.

### Version

17.0.0

### Expected behavior

All users which in current Group and fit Custom User LDAP Filter are printed.

### Actual behavior

Printed only those users which were before user in current Group, but doesn't fit Custom User LDAP Filter. Even if there are users after this one in the list.

### How to Reproduce?

1. Create 2 Groups in AD: A and B
2. Add more than 5 users for group A
3. Add them in group B also
4. Add few other users for group B
5. Set filter for LDAP federation (Custom User LDAP Filter) to import users from group A
6. Set group-ldap-mapper for this LDAP federation to import users from group B
7. Sync users and groups
8. Check Membership tab for group B - it will print users for group B which also in group A until it will meet user that in group B but not in group A. Than it stops to print users at all, even if there are more users in B and A groups in the list.

### Anything else?

reproduced for 20.0.3 also

**Comment by ssilvert** [comment]
@MariiaAlekseichuk Since you have tried this on both Keycloak 17 and 20, I assume you see the same problem on both the old Angular-based UI and the new React-based UI?

If that is the case then it is almost certainly a problem with the admin REST API and I will need a different team to look at this.

**Comment by MariiaAlekseichuk** [comment]
> @MariiaAlekseichuk Since you have tried this on both Keycloak 17 and 20, I assume you see the same problem on both the old Angular-based UI and the new React-based UI?
> 
> If that is the case then it is almost certainly a problem with the admin REST API and I will need a different team to look at this.

Yes, it was reproduced for both old Angular-based UI and the new React-based UI.
This described logic is in org.keycloak.storage.ldap.mappers.membership.MembershipType::getGroupMembers.

**Comment by ssilvert** [comment]
Thanks @MariiaAlekseichuk.  Moving this to the core team.
