### ISSUE TITLE
Database tables are not named correctly.

### ISSUE THREAD

**Issue by ma-scha** [keycloak/keycloak#17190]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

If Keycloak is started with an external database, then new tables are created by Keycloak, which should have a prefix according to this [issue](https://github.com/keycloak/keycloak/issues/10101). However, if you look at the database, you will see that the tables have been created without the required "kc_".

### Version

20.0.3

### Expected behavior

I would expect all table names to be created with the prefix "kc_".

### Actual behavior

Currently the tables are created without prefix, the behavior can be reproduced on external databases (Postgres v15.2 and Oracle v19.3.0.0).
![postgres](https://user-images.githubusercontent.com/125563001/220070774-addaed2b-77e2-4f4b-b830-a5e713285c93.png)

### How to Reproduce?

For Postgres, this can be reproduced with this [docker-compose.yml](https://github.com/keycloak/keycloak/files/10782887/docker-compose.yml.zip).

**Comment by dalbani** [comment]
Isn't this `kc_` prefix supposed to be a "map storage" [1] thing only?
My understanding is that the "legacy" storage still uses Liquibase [2] and table names like `CLIENT_ATTRIBUTES`.

[1] https://www.keycloak.org/2022/07/storage-map.html
[2] https://github.com/keycloak/keycloak/tree/main/model/jpa/src/main/resources/META-INF
