### ISSUE TITLE
Discovery document is missing mandatory fields

### ISSUE THREAD

**Issue by kaol** [keycloak/keycloak#17197]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

OpenID Connect Discovery [spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) lists the fields `subject_types_supported` and `id_token_signing_alg_values_supported` as REQUIRED.

When I created a realm and downloaded the discovery document those two are missing from it.

### Version

20.0.3

### Expected behavior

The specified fields to be present.

### Actual behavior

The specified fields are missing.

### How to Reproduce?

Extract Keycloak. Start with `bin/kc.sh start-dev`.

```
curl http://localhost:8080/realms/master/.well-known/uma2-configuration -H 'Accept: application/json' | jq . -|less
```

### Anything else?

The OpenID Connect library I'm using refuses to recognize the discovery document since it's missing mandatory fields. If anyone knows a reason for omitting them from Discovery then I can go tell them that but right now all I know is that the spec says REQUIRED and they'd likely tell me the same if I'd ask them to patch the fields as optional.

**Comment by sschu** [comment]
@kaol You are using the wrong endpoint, the correct endpoint is `http://localhost:8080/realms/master/.well-known/openid-configuration`.

**Comment by kaol** [comment]
I guess this is invalid bug then. Sorry for the noise.

Unless it's an issue that the uma2-configuration should satisfy the same spec, but I'll leave that for someone else.
