### ISSUE TITLE
Phantom release 20.0.4

### ISSUE THREAD

**Issue by jacekkow** [keycloak/keycloak#17206]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

There are some artifacts of Keycloak 20.0.4 in Maven:
https://repo.maven.apache.org/maven2/org/keycloak/keycloak-core/maven-metadata.xml
https://repo.maven.apache.org/maven2/org/keycloak/keycloak-core/20.0.4/
and even in this repository:
https://github.com/keycloak/keycloak/tree/20.0.4
but there is no article on the site of the release nor there is a Docker container in Quay.

What happened to Keycloak 20.0.4?

### Version

20.0.4

### Expected behavior

Release 20.0.4 is available.

### Actual behavior

Some artifacts of release 20.0.4 are available, others are not.

### How to Reproduce?

docker pull quay.io/keycloak/keycloak:20.0.4

**Comment by jacekkow** [comment]
Any word of explanation?

**Comment by stianst** [comment]
There was an outage on Maven Central while we where publishing 20.0.4, even though it shouldn't be possible, that resulted in a partial release. Rather than spending a lot of time investigating we bumped the release to 20.0.5, as Maven basically blocks releasing over something that's already there.
