### ISSUE TITLE
Add possibility for multi-tenancy in HotRod storage

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#17209]
### Discussed in https://github.com/keycloak/keycloak/discussions/15007

<div type='discussions-op-text'>

<sup>Originally posted by **kkcmadhu** October 19, 2022</sup>
Key cloak presently uses well defined cache names linke realms, clients, users, users-sessions, client-scopes etc. while this is ok, but when using external cache infinispan server/hotrod, i might want to have a single infinispan cluster to server multiple deployments of keycloak,  instead of having one infispan cluster per keycloak deployment. if the cache name can be made configureable or if there is a possiblity to add a prefix to all cache names through -D arg, it might  be very very useful.

</div>

We should support not only sharing one ISPN between more Keycloak deployments, but also we should be able to configure cache names per one configuration. 

For example, we should be able to configure per-realm HotRod caches.

**Comment by mhajas** [comment]
This may be necessary for the tree store. We need to triage based on the tree store work

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
