### ISSUE TITLE
Polish fips-mode switch

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#17208]
We discussed following:
Change `fips-mode=enabled` to `fips-mode=non-strict`. So instead of values `disabled|enabled|strict`, we will have `disabled|non-strict|strict`

**Comment by stianst** [comment]
We shouldn't add the `disabled` mode, as FIPS should be disabled by default, and enabled with `--features=fips`.

Basically it just doesn't make any sense to do `kc.sh start --features=fips --fips-mode=disabled`
