### ISSUE TITLE
Creating a Javascript Policy

### ISSUE THREAD

**Issue by OKELLOMARVIN** [keycloak/keycloak#17247]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

I am trying to create a javascript policy for Attribute Bases Access Control in keycloak to control horizontal access in a mongo collection for a springboot application. I have followed the official documentation under **Authorization services>Managing Policies> JavaScript-based policy**
![JAVASCRIPT policy documentation](https://user-images.githubusercontent.com/34127022/220909972-ea708309-d136-46a3-b9e1-cbf592483701.png)
I have highted the instruction to follow, but in the UI, I am not able to add the Javacript Policy
![policy dashboard](https://user-images.githubusercontent.com/34127022/220910444-d50bca56-3908-4c65-9e9d-cf0b26f47ad8.png)
To add to that, theres no option of javascript policy among the policy types as well as User attribute policy type.
![available policies](https://user-images.githubusercontent.com/34127022/220910924-2288f1c7-cf8f-49a7-a07d-278eae66461c.png)
I have checked the different versions of keycloak namely 20.0.2 and 21.0.0 and they both have the same issue. Theres no provision to create the Javascript policy.

### Version

20.0.2

### Expected behavior

I expect to see the option to create a new JavaScript-based policy by selecting JavaScript in the item list in the upper right corner of the policy listings

### Actual behavior

Theres no provision in the User Interface to create a Javascript policy

### How to Reproduce?

1. Open keycloak and create a client or open one of the existing clients 
2. Head to the Authorization tab and then click on the Policies tab
3. There's no provision see the item list, in order to select the javascript policy
4. Click on create policy and Javascript policy is not among the available policy types

### Anything else?

This is the link to the documentation I have been following
https://www.keycloak.org/docs/latest/authorization_services/#_policy_js

**Comment by rmartinc** [comment]
Hi @OKELLOMARVIN!

The javascript providers now should be used through the [javascript providers](https://www.keycloak.org/docs/latest/server_development/#_script_providers). I think the `upload_scripts` feature was totally disabled in keycloak 18 ([release notes](https://www.keycloak.org/2022/04/keycloak-1800-released)). I suppose the documentation should be updated now. Adding documentation tag and moving to backlog.

For the moment just provide a script provider following the documentation and your provider will appear in the list of policies to add.

**Comment by abstractj** [comment]
@rmartinc is correct about `upload_scripts` and please check his comments about JavaScript providers. For now, I'm closing this issue, but please reopen if the answer is not sufficient.
