### ISSUE TITLE
DefaultKeycloakSessionFactory.isEnabled doesn't propagate config scope to provider factory

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#17250]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Param `Config.Scope scope` isn't propagated to `EnvironmentDependentProviderFactory.isSupported`.
This looks like a potential bug, depending on implementations of the interface.

```
protected boolean isEnabled(ProviderFactory factory, Config.Scope scope) {
        if (!scope.getBoolean("enabled", true)) {
            return false;
        }
        if (factory instanceof EnvironmentDependentProviderFactory) {
            return ((EnvironmentDependentProviderFactory) factory).isSupported();
        }
        return true;
    }
```
The interface `EnvironmentDependentProviderFactory` provides method `isSupported(Config.Scope config) ` which could be overwritten by implementations.

### Version

master / 20.0.5

### Expected behavior

Line [316](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L316)
should probably be:

`return ((EnvironmentDependentProviderFactory) factory).isSupported(scope);`

### Actual behavior

Param scope not propagated.

### How to Reproduce?

Nothing to reproduce. This is a potential bug.

**Comment by sschu** [comment]
@mposolda You are right, but not in: https://github.com/keycloak/keycloak/blob/071fc03f413d85fb9ace132932dea492b64a941b/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L311-L319. ;)

**Comment by jbman** [comment]
I didn't link to master, indeed. Corrected now in original description above.
Line [316](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L316) of DefaultKeycloakSessionFactory still seems to be wrong.

**Comment by mposolda** [comment]
@jbman Thanks!

Yes, you're right that code in `DefaultKeycloakSessionFactory` is likely not correct. This code is not used in quarkus distribution (just in keycloak on embedded undertow in the testsuite) hence this issue is quite minor though. But PR would be welcome with the suggestion to fix this.
