### ISSUE TITLE
Keycloak account page referral_uri not working after login

### ISSUE THREAD

**Issue by tonial** [keycloak/keycloak#17257]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/spring

### Describe the bug

When accessing the account page with a referrer and a referrer_uri :
```http://localhost:8080/auth/realms/my_realm/account/?referrer=my_client_id&referrer_uri=http://127.0.0.1:8000/xxx```

If there's no active session, the user is redirected to the login page :
```http://0.0.0.0:8080/realms/my_realm/protocol/openid-connect/auth?client_id=account&redirect_uri=http%3A%2F%2F0.0.0.0%3A8080%2Frealms%2Fmy_realm%2Faccount%2Flogin-redirect?referrer%3Dmy_client_id%26referrer_uri%3Dhttp%3A%2F%2F127.0.0.1%3A8000%2Fxxx&state=0%2F280a43f9-cede-4e49-a097-3db2cac7e7f1&response_type=code&scope=openid```
I can see that both the referrer and referrer_uri are still in the query params

After login I am redirected to
```http://0.0.0.0:8080/realms/my_realm/login-actions/authenticate?session_code=3cfvNdzt67_U2DQBZ1woDoyI-IrKQbp06_9VAFbMeIQ&execution=2979e1f6-c935-4308-bdc1-c44b8e86bfb0&client_id=account&tab_id=1FN28mygpQ0```
that redirects to 
```http://0.0.0.0:8080/realms/my_realm/account/login-redirect?referrer=my_client_id&referrer_uri=http://127.0.0.1:8000/xxx&state=0%2F280a43f9-cede-4e49-a097-3db2cac7e7f1&session_state=2eb68fdc-8580-47a3-8b70-5e1d3170e2e2&code=855189b2-c9f3-4172-9a88-d5478e11390f.2eb68fdc-8580-47a3-8b70-5e1d3170e2e2.94ba5e84-7967-4b1b-ab5c-365ff005848a```
Here I can see again both referrer and referrer_uri in the query params. And I'm redirect again to
```http://0.0.0.0:8080/realms/my_realm/account/?referrer=my_client_id```
No referrer_uri here.

I cannot bypass this issue by setting a home URL on the client, because some clients have several possible return urls (some query params depends on the user kind).

Am I missing something ?

### Version

21.0.0

### Expected behavior

Both `referrer` and `referrer_uri` should be transmitted after login

### Actual behavior

Only `referrer` is transmitter, not `referrer_uri`

### How to Reproduce?

The urls given in the description should be enough

**Comment by mposolda** [comment]
I am closing as I think this one is fixed in latest Keycloak main. The fix would be available in the Keycloak 21.1.0 release (probably after Easter). Eventually you can try build latest Keycloak from sources and/or latest Keycloak nigthtly release. Please re-open if still applicable with that latest stuff.
