### ISSUE TITLE
Client resource displayName not showing value

### ISSUE THREAD

**Issue by point67** [keycloak/keycloak#17278]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

While in the admin gui, the Display Name field of any client resource stays empty.

When I look inside the json received from : 
{keycloak_url}/auth/admin/realms/{realm}/clients/{client}/authz/resource-server/resource/{resource_id}

The displayName is correct.

Thanks

### Version

19.0.3

### Expected behavior

The Display name saved should be shown in the gui.

### Actual behavior

No Display name shown, field remains empty

### How to Reproduce?

Create a resource with a Display Name, quit the screen and go back to the resource screen. The display name is not shown.

**Comment by ssilvert** [comment]
@point67 I'm not seeing this problem.  Can you take a look at the nightly build and tell me if it is fixed on your end?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
I'm going to close this now.  If you are still seeing a problem in the nightly build then we can reopen.
