### ISSUE TITLE
Intermittent build failures (stalls) with Docker on M1 Mac, no error output

### ISSUE THREAD

**Issue by bryson** [keycloak/keycloak#17283]
### Before reporting an issue

- [x] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ci

### Describe the bug

When building a Docker container image on an M1 Mac I get seemingly-random build stalls at the `/opt/keycloak/bin/kc.sh build` step. I have not been able to find a way to enable the `DEBUG` log-level during `build`, or if it was enabled `build` does not generate any log output. I have not been able to troubleshoot this issue outside of single-change elimination over the last couple days and have not had any success. Builds via Jenkins Pipeline in our datacenter have a 100% success rate. Builds on Intel-based Macs with my same system/software configuration also have a 100% success rate.

I started out using [this Keycloak `Dockerfile`](https://repo1.dso.mil/dsop/opensource/keycloak/keycloak/-/blob/development/Dockerfile) from the US Gov's Iron Bank repo of hardened containers. My goal is a FIPS-enabled build using BC FIPS crypto modules.

My sources of reference while putting this together, in addition to the first-party and Iron Bank `Dockerfile`s:
<https://github.com/keycloak/keycloak/blob/main/docs/fips.md>
<https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/fips.adoc>
<https://github.com/mposolda/keycloak-fips-image> 

Given this build phase from my `Dockerfile`:

```
...

FROM quay.io/keycloak/keycloak:21.0 as upstream

# SOURCE: https://repo1.dso.mil/dsop/redhat/openjdk/openjdk17-slim
FROM openjdk17-slim:latest as build

ENV KEYCLOAK_HOME="/opt/keycloak"
ENV PROVIDERS_HOME="$KEYCLOAK_HOME/providers"
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV LANG="C.UTF-8"

USER 0
RUN microdnf update -y && \
    microdnf clean all && \
    rm -rf /var/cache/dnf && \
    update-crypto-policies --set FIPS
COPY --from=upstream $KEYCLOAK_HOME $KEYCLOAK_HOME
# https://downloads.bouncycastle.org/fips-java/bc-fips-1.0.2.3.jar
# https://downloads.bouncycastle.org/fips-java/bcpkix-fips-1.0.7.jar
# https://downloads.bouncycastle.org/fips-java/bctls-fips-1.0.14.jar
COPY *.jar $PROVIDERS_HOME/

# SOURCE: https://repo1.dso.mil/dsop/opensource/keycloak/keycloak
# Prevent CCE-84038-9 and CCE-85888-6
RUN chmod -R 0750 $KEYCLOAK_HOME

# Config for build
# SOURCE: https://www.keycloak.org/server/all-config?f=build
#         https://www.keycloak.org/server/features
ENV KC_CACHE_STACK="kubernetes"
ENV KC_DB="postgres"
ENV KC_FEATURES="fips,token-exchange"
ENV KC_FIPS_MODE="strict"
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
RUN $KEYCLOAK_HOME/bin/kc.sh build

# SOURCE: https://repo1.dso.mil/dsop/redhat/openjdk/openjdk17-slim
FROM openjdk17-slim:latest as final

...
```

I can successfully create a container image with `20.0.3`, `20.0.5`, and `21.0.0` (the output below is a `21.0.0` image) that starts up as I expect:

```
$ docker build -t keycloak-fips:latest .
...

Step 22/34 : RUN $KEYCLOAK_HOME/bin/kc.sh build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 3b394390138d
Updating the configuration and installing your custom providers, if any. Please wait.
2023-02-25 22:24:25,765 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: fips, token-exchange
2023-02-25 22:24:26,025 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: fips, token-exchange
2023-02-25 22:24:29,894 INFO  [org.keycloak.common.Profile] (build-21) Preview features enabled: fips, token-exchange
2023-02-25 22:24:29,943 INFO  [org.keycloak.common.Profile] (build-26) Preview features enabled: fips, token-exchange
2023-02-25 22:25:03,145 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 39468ms
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Removing intermediate container 3b394390138d
 ---> 10343b477d24
...

Successfully built 9d852613f760
Successfully tagged keycloak-fips:latest

$ docker run -ti -v $(pwd)/keystore:/tmp/keystore keycloak-fips:latest \
    start --optimized \
    --hostname=localhost \
    --https-key-store-file=/tmp/keystore/server.keystore \
    --https-key-store-password=$PASSWORD \
    --log-level=DEBUG,org.keycloak.common.crypto:TRACE,org.keycloak.crypto:TRACE

2023-02-21 21:37:39,269 DEBUG [org.keycloak.crypto.fips.FIPS1402Provider] (main) Inserted security providers: [BCFIPS, BCJSSE]
2023-02-21 21:37:39,271 DEBUG [org.keycloak.common.crypto.CryptoIntegration] (main) Using the crypto provider: org.keycloak.crypto.fips.Fips1402StrictCryptoProvider
2023-02-21 21:37:40,044 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: token_exchange
...
2023-02-21 21:37:45,210 TRACE [org.keycloak.common.crypto.CryptoIntegration] (main) Java security providers: [
 KC(BCFIPS version 1.000203 Approved Mode) version 1.0 - class org.keycloak.crypto.fips.KeycloakFipsSecurityProvider,
 BCFIPS version 1.000203 - class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider,
 BCJSSE version 1.0014 - class org.bouncycastle.jsse.provider.BouncyCastleJsseProvider,
 SUN version 17 - class sun.security.provider.Sun,
 ...
]
...
```

Successful build are extremely predictable. Referencing the next 2 code blocks below, once `Step 22/34` begins on my Mac it is 1–2 seconds until "Updating the configuration..." appears, ~25 seconds until "...enabled: fips,token-exchange", and then ~25 seconds to `build` completion including my final phase that copies `/opt/keycloak` from the above build phase. (On my M1 Mac in the above example, `build` took 39468ms which is repeatable _if_ it succeeds at all; in Jenkins on amd64 hardware `build` completes in sub-4000ms and succeeds 100% of the time.)

If I don't see output on that timeline, I know right away the build will not finish. Failure is not consistent, and I only have a successful build maybe 1 in 20 attempts. Sometimes I will get 3 successes back to back. Sometimes no successes over multiple hours, or after waiting overnight between `build`s. Letting the build run — I gave it more than 48 hours from end-of-day Friday to Monday morning — also produces no output and does not finish.

On some `build`s (20.x) it reaches a point where `token_exchange` is enabled then stalls with no further progress or output:

```
Step 22/34 : RUN $KEYCLOAK_HOME/bin/kc.sh build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 97d5bf71c242
Updating the configuration and installing your custom providers, if any. Please wait.
2023-02-23 01:48:17,915 INFO  [org.keycloak.common.Profile] (build-36) Preview feature enabled: token_exchange
^C
```

Approximately the same output/result is generated with 21.x, which I saw was released while I was putting together this bug report. During my first `kc.sh build` with `21.0.0` I got an enormous amount of red error output right away about needing to enable the FIPS feature if I wanted to set FIPS strict mode. With that change (`ENV KC_FEATURES="fips,token-exchange"`), I get the same result except the output now double-doubles:

```
Step 22/34 : RUN $KEYCLOAK_HOME/bin/kc.sh build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 3b394390138d
Updating the configuration and installing your custom providers, if any. Please wait.
2023-02-25 22:24:25,765 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: fips, token-exchange
2023-02-25 22:24:26,025 INFO  [org.keycloak.common.Profile] (main) Preview features enabled: fips, token-exchange
2023-02-25 22:24:29,894 INFO  [org.keycloak.common.Profile] (build-21) Preview features enabled: fips, token-exchange
2023-02-25 22:24:29,943 INFO  [org.keycloak.common.Profile] (build-26) Preview features enabled: fips, token-exchange
^C
```

Despite getting significant error output regarding the missing FIPS `KC_FEATURES` flag from `21.0.0`, there is still no output related to the stalled/failed build. On the next run, it may not even get as far as feature enablement before the stall:

```
Step 22/34 : RUN $KEYCLOAK_HOME/bin/kc.sh build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 7c732f5cec33
Updating the configuration and installing your custom providers, if any. Please wait.
^C
```

And after that, the next `build` may generate no output at all:

```
Step 22/34 : RUN $KEYCLOAK_HOME/bin/kc.sh build
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 8a120cbccd6b
^C
```

I tried `build --log-level=DEBUG` but `build` complained that `--log-level` was not supported. The things that I have changed trying to narrow this down (all with no effect):

- 2 different M1 Macs
- OpenJDK 17, OpenJDK 11
- `-slim` and standard base images (all RHEL 8.7-based)
- RHEL 9-based base images
- KeyCloak 20.0.3, 20.0.5, 21.0.0
- Disabling the `ENV KC_*` configs one at a time
- Disabling all of the `ENV KC_*` configs
- Waiting 48+ hours for the build to finish

I wish I had more info for this bug report. If not a solution to this problem, at least some insight on how to get any debug output at all from the `build` command would be greatly appreciated.

### Version

21.0, 20.0.5, 20.0.3
macOS 13.2.1 (22D68)
Rancher Desktop 1.7 (provides `docker [build, ...]` support via Docker's [moby](https://github.com/moby/moby))

### Expected behavior

`/opt/keycloak/bin/build.sh` completes in a predictable way every time.

### Actual behavior

`/opt/keycloak/bin/build.sh` rarely completes on M1 Macs and failure point is unpredictable; failure mode and/or errors are hidden.

### How to Reproduce?

A `Dockerfile` is included in the bug report, as well as sources for my changes and my base images.

**Comment by bryson** [comment]
Apologies for missing the "Area" dropdown, I've updated the section in the report to "ci" but it looks like the bot isn't watching.

**Comment by sschu** [comment]
@Bryson I cannot help you with your original problem, I can just tell you that running `RUN chmod -R 0750 $KEYCLOAK_HOME` pretty much doubles your image size as it creates copies of all files with different permissions. You should rather use `COPY --chown`.

**Comment by bryson** [comment]
Thanks for the response. The size of the layers in the main build stage above don't matter. In my final stage there is a `COPY --chown` so a non-root user runs the process in the container, but skips `--chmod` which I assume was your intent because the permissions are already correct from the earlier build stage. Approximately:

```lang-docker
FROM openjdk17-slim:latest as final
...
USER 0
RUN echo "keycloak:x:0:root" >> /etc/group && \
    echo "keycloak:x:1000:0:keycloak user:$KEYCLOAK_HOME:/sbin/nologin" >> /etc/passwd

# If I needed chmod here I'd do this:
# COPY --from=build --chown=1000:0 --chmod=0750 $KEYCLOAK_HOME $KEYCLOAK_HOME

# But since I only need chown I actually do this:
COPY --from=build --chown=1000:0 $KEYCLOAK_HOME $KEYCLOAK_HOME

WORKDIR $KEYCLOAK_HOME
USER 1000
ENTRYPOINT [ "/opt/keycloak/bin/kc.sh" ]
```

**Comment by sschu** [comment]
Ah, ok. Seeing `RUN chmod` just triggers some kind of alarm in my head...

**Comment by bryson** [comment]
Since initially creating this bug report I've also set up Jenkins Pipelines to build these images in our datacenter. On Intel-based hardware in Jenkins `build` has a 100% success rate. I have updated the bug report with relevant new details related to Intel-based `build`s and added 21.0 tests and output.

**Comment by bryson** [comment]
@sschu If you could update the tag from `area/account/api` to the appropriate tag for me I would greatly appreciate it. I guessed CI but defer to you on the appropriate tag if CI is wrong.

**Comment by sschu** [comment]
@Bryson I can't but @stianst already did.

**Comment by vmuzikar** [comment]
@bryson Sorry for the very late response. Can you please confirm this is still happening for you with Keycloak 23? I can see a lot's of `The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)` messages in the logs. Docker previously had some issues with emulation if you need that instead of a native arm image. Might be relevant.

**Comment by vmuzikar** [comment]
@Shegl Feel free to open an issue for it but I couldn't reproduce on a Mac with M1 Pro.

Also manifest inspect confirm it:
```
docker manifest inspect quay.io/keycloak/keycloak:latest

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1056,
         "digest": "sha256:050b5430f5a2f417ef41dd5ccdda70f900761bb757d08a17dd6957796e61acc9",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1056,
         "digest": "sha256:be4ff90d66bd1cdfe79610a90eae2b187dff9926e5c1a99200eaf62b41433600",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:6752bf0b235f4138059d8b7f4b9f915b74d5f51da5beff7025b1780b8313da32",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:eacf8552573197cba194feaf6fc013f97498e5ac1763809f00fac537d2f9898e",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```
