### ISSUE TITLE
Avoid recording raw UUIDs  URIs in metrics like http_server_requests_seconds collected via micrometer

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#17281]
### Description
Ensure  metric tags containing URIs with UUIDs are templated properly to avoid high memory usage.

### Discussion

https://github.com/keycloak/keycloak/discussions/8490#discussioncomment-5102496

### Motivation

The switch from smallrye-metrics to micrometer metrics in Keycloak 21 seems to come with a few unpractial defaults.

When metrics is enabled via `--metrics-enabled=true` new metrics are being generated as described in the [Keycloak 21 release announcement](https://www.keycloak.org/2023/02/keycloak-2100-released.html#_keycloak_uses_micrometer_for_metrics).
Appart from renamed metrics, a new metric for incoming requests `http_server_requests_seconds` might cause problems in large deployments.
By default the `http_server_requests_seconds` metric records full URIs without replacing UUIDs with template parameters. 
This can be lead to memory exhaustion on heavily used systems with high object cardinalities.

### Details

It seems that the quakrus micrometer support allows to define patterns to [create templated URIs from concrete URIs in metrics](https://quarkus.io/guides/micrometer#review-automatically-generated-metrics).

However, configuring patterns for every Keycloak Resource URI seems quite elaborate. Perhaps it is possible to configure micrometer to treat the UUIDs as templates by default.
If this is not feasible, I'd recommend to disable the default http-server-metrics via quarkus.properties in Keycloak for now:
```
quarkus.micrometer.binder.http-server.enabled=false
```

How to reproduce:

0) Start Keycloak 21.0.0
```
docker run --rm -it \
    -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    quay.io/keycloak/keycloak:21.0.0 \
    start-dev \
   --metrics-enabled=true
```

1) Sign-in to the admin-console with admin/admin
2) click on `users` then click àdmin`.
3) Browse to http://localhost:8080/metrics

Now http_server_requests metrics like the following are generated:
```
...
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/master/attack-detection/brute-force/users/b9ab0974-15a2-4102-b2d3-10719a01cd13",} 1.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/admin/realms/master/attack-detection/brute-force/users/b9ab0974-15a2-4102-b2d3-10719a01cd13",} 0.008205889
...

**Comment by ahus1** [comment]
Thanks for reporting this. Promoting this to a bug. 

IDs in URLs during the login show with placeholder. URLs in the admin console show the IDs of the entities.

**Comment by thomasdarimont** [comment]
@ahus1 `io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor` populates the `UrlPathTemplate` which is then used by `io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric#applyTemplateMatching` to replace concrete parameters with the templated path. 

The `QuarkusRestPathTemplateInterceptor` is applied for /resource requests, but not for /admin API requests.

**Comment by ahus1** [comment]
PR #17326 created to disable the `http_server` metrics. A follow-up issue can then try to re-enable them in a future release.

**Comment by thomasdarimont** [comment]
@ahus1  FYI I created this issue in the quarkus repo as an enhancement proposal: https://github.com/quarkusio/quarkus/issues/31497

**Comment by ahus1** [comment]
Backport created: #17373

**Comment by ahus1** [comment]
With the upstream issue being open and Quarkus not supporting sub-resources, I decide to not open a follow-up issue for this, as it is unknown when and if this will be supported. 

If someone sees this differently, please go ahead and create such an issue and link it to this issue.
