### ISSUE TITLE
Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by tricsusz** [keycloak/keycloak#17290]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I'm trying to build my docker container based on keycloak:21.0, but it fails on build.sh, and says:
``Fatal glibc error: CPU does not support x86-64-v2``

![Screenshot from 2023-02-26 12-22-17](https://user-images.githubusercontent.com/16030732/221407553-8703d05e-7f08-4a1f-8152-62cea033d9da.png)

I haven't had any problem with the previous releases.

I'm on a VPS, based on Ubuntu Server 22.04, with all the latest packages.

### Version

21.0

### Expected behavior

build the docker container

### Actual behavior

build fails

### How to Reproduce?

build docker container with latest 21.0 version

### Anything else?

nothing special in my config, i use everything according to best practices

**Comment by GissilyWork** [comment]
I have a same issue on PVE vm, I change the vm cpu type to fix it. Some virtualization systems like PVE, the default cpu type is 'kvm64', that dose not contain SSE4.2.

keycloak 21.0 is base on ubi9, and rhel9 requires the CPU to support SSE4.2. 
I think you need to contact your vps, is it possible to change your vm cpu type, if not maybe you have to customized the image from other base image.

**Comment by mabartos** [comment]
@tricsusz Thanks for creating this issue! 

As @GissilyWork mentioned, Keycloak 21 is based on UBI9 (#17057), where is set a new x86_64 baseline. I wouldn't consider this issue as a bug of Keycloak, but rather an issue regarding requirements for starting the server instance. Depends on the used CPU type. For virtual environments, it's also possible that a hypervisor masks CPU features, so it'd be necessary to set up the environment properly. 

Closed this issue as not planned. Feel free to provide more info for consideration.

**Comment by thmo** [comment]
Would it be possible to rebuild 21 on ubi8, or are there hard dependencies on components only present for ubi9?

**Comment by Daniel-Marynicz** [comment]
@tricsusz @GissilyWork  @thmo   I created alternative docker image  using amazoncorretto as base. And this not require x86-64-v2.
https://github.com/Daniel-Marynicz/keycloak

**Comment by tricsusz** [comment]
> @tricsusz @GissilyWork @thmo I created alternative docker image using amazoncorretto as base. And this not require x86-64-v2. https://github.com/Daniel-Marynicz/keycloak

@Daniel-Marynicz thank you! Your link goes to 404

**Comment by Daniel-Marynicz** [comment]
@tricsusz   I changed visibility

**Comment by borland502** [comment]
Necro update to this thread in case someone comes across it.  If you know the host supports the required standard set the CPU type to max (if using proxmox).  That did the trick in silencing UBI's complaints

**Comment by bryonbaker** [comment]
I had the same issue with running some RHEL 9 images in Podman on a Fedora Linux under Proxmox. RHEL 9 is checking this now for some reason.
The problem is caused by the underlying CPU architecture that Proxmox was telling Fedora that it had.
The problem was resolved very simply. When configuring the VM (or when the VM is in a stopped state) set the CPU architecture value to "host."
In Proxmox, if the machine is already provisioned you stop the server, open the Hardware setting, click Processors. Set the Type value to "host."

**Comment by williank** [comment]
> Tive o mesmo problema ao executar algumas imagens RHEL 9 no Podman em um Fedora Linux no Proxmox. RHEL 9 está verificando isso agora por algum motivo. O problema é causado pela arquitetura subjacente da CPU que o Proxmox disse ao Fedora que possuía. O problema foi resolvido de forma muito simples. Ao configurar uma VM (ou quando a VM estiver parada), defina o valor da arquitetura da CPU como "host". No Proxmox, se a máquina já estiver provisionada para o servidor, abra Configuração de Hardware, clique em Processadores. Defina o valor Tipo como “host”.

Isso não causaria nenhum problema de performance?

**Comment by bryonbaker** [comment]
@williank - no performance issues. You are just telling the VM that it is running on the same cpu architecture as the hypervisor. So when linux asks about the underlying host architecture it is reporting correctly. 
Of course sometimes you want to abstract that away, but it is nothing to do with performance.

**Comment by gardo984** [comment]
> I had the same issue with running some RHEL 9 images in Podman on a Fedora Linux under Proxmox. RHEL 9 is checking this now for some reason. The problem is caused by the underlying CPU architecture that Proxmox was telling Fedora that it had. The problem was resolved very simply. When configuring the VM (or when the VM is in a stopped state) set the CPU architecture value to "host." In Proxmox, if the machine is already provisioned you stop the server, open the Hardware setting, click Processors. Set the Type value to "host."

Thanks a lot, I was working with kvm and virtualizing a Rocky Linux host, I just proceeded to set the following and it worked (this required a restart):

![image](https://github.com/keycloak/keycloak/assets/4959732/aedb09d8-c576-4b9a-bed6-01c97b62eef6)

**Comment by escummy** [comment]
> I had the same issue with running some RHEL 9 images in Podman on a Fedora Linux under Proxmox. RHEL 9 is checking this now for some reason. The problem is caused by the underlying CPU architecture that Proxmox was telling Fedora that it had. The problem was resolved very simply. When configuring the VM (or when the VM is in a stopped state) set the CPU architecture value to "host." In Proxmox, if the machine is already provisioned you stop the server, open the Hardware setting, click Processors. Set the Type value to "host."

Thanks so much, after try a lot of ways, finally [host] is the solution to my Proxmox CPU processor type value.

![cpu-processor-value](https://github.com/keycloak/keycloak/assets/90976678/e57e04ce-3230-4bed-bcc3-afc1214f44b6)

**Comment by zizhufanqing** [comment]
<img width="717" alt="企业微信截图_725121cd-f38e-47ab-8036-88caa97eabca" src="https://github.com/keycloak/keycloak/assets/53900290/3dc1f4b6-c655-434e-b370-2cacd68576a5">
I created a virtual machine using PVE and the operating system is Centos7.9. However, I found that keycloakx could not be started and reported an error as shown in the figure

**Comment by zizhufanqing** [comment]
<img width="1379" alt="image" src="https://github.com/keycloak/keycloak/assets/53900290/c2b116b4-84e5-4bf1-910a-6ce599f62476">

**Comment by zizhufanqing** [comment]
I created a virtual machine using PVE and the operating system is Centos7.9. However, I found that keycloakx could not be started and reported an error as shown in the figure
<img width="648" alt="image" src="https://github.com/keycloak/keycloak/assets/53900290/6e0e019e-aee7-41c5-b06a-43f0fee91bc3">
<img width="1272" alt="image" src="https://github.com/keycloak/keycloak/assets/53900290/5088396a-9c3d-4338-9fc3-3de220f33dcf">

**Comment by Windywind** [comment]
I am not seeing this requirement in any official documents. Please kindly add.

**Comment by botanyhelp** [comment]
I am learning quarkus from Manning's Quarkus In Action, running Ubuntu24.04LTS on amd64 bare metal, everything latest version, java21.0.6, docker 27.5.  I am at chapter "3.4.1 Securing the Quarkus application using OpenID Connect and Dev Services" 

In one terminal, I have quarkus running like this, where it starts my super-simple app:

quarkus dev

..which allows me to see logs, errors, etc.  In another terminal, I run this command which should give me this logging output in the "quarkus dev" terminal:

Services for Keycloak started.

..but, sadly, instead, "quarkus dev" dies, with a ton of output.  The interesting logging, which is how I got on this thread today, is this snippet of output, given in the "quarkus dev" terminal:

```
2025-03-18 17:27:42,939 ERROR [tc.qua.io/.1.3] (build-38) Log output from the failed container:
Fatal glibc error: CPU does not support x86-64-v2
```

**Comment by danielkucera** [comment]
And what if one really has an older CPU?
```
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 8
model name	: AMD Opteron(tm) Processor 4176 HE
stepping	: 1
microcode	: 0x10000d9
cpu MHz		: 2400.143
cache size	: 512 KB
physical id	: 0
siblings	: 6
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc art rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate retpoline_amd ibp_disable vmmcall npt lbrv svm_lock nrip_save pausefilter
bogomips	: 4800.28
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
```

**Comment by botanyhelp** [comment]
@danielkucera ..I am not expert enough to help much here, just reporting what I see.  I thought x86_64 is the only thing required, for nearly all modern development, but here we have a situation where CPU features are being used that are not in older CPUs.  I have never seen such a thing.  The thing I am using, Quarkus, is in the "cloud-native" space.  I think of Quarkus as an easier, and maybe better, alternative to Spring Boot. 

This problem did mean a show-stopper for me, on that older CPU/machine.  Moving through the book, Quarkus In Action, is not so easy, and this is a problem not expected by the authors, and so I will need to get another machine.
