### ISSUE TITLE
Forms in Authentication Flow getting removed automatically

### ISSUE THREAD

**Issue by Sabari22shankar** [keycloak/keycloak#17297]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Adding custom authentication forms using a custom flow.

Forms added in the flow is automatically removed after a certain time.

### Version

19.0.3

### Expected behavior

Form should not be removed from the flow.

### Actual behavior

-

### How to Reproduce?

Create a custom flow taking a copy of browser auth, and add a custom form other than username/password form.

**Comment by Sabari22shankar** [comment]
Hi, please provide support for the issue

**Comment by Sabari22shankar** [comment]
Hello

**Comment by mposolda** [comment]
Adding to Backlog for now. Keycloak team won't have time to take a look at this in the near future.

Moreover, it seems to be that this is rather an issue in your environment. Isn't it some "background" process or something, which automatically updates your realm somehow during some certain times? To track this, I suggest to enabled admin-events in the admin console (and eventually also some logging at DB level) to check what is changing your configuration.

**Comment by rmartinc** [comment]
Please re-test this in the last version of keycloak and file a new issue if the problem persists. The issue should have clear reproducer steps because probably the problem was something environmental. As @mposolda commented you can try to see what is deleting the flows. Regards!
