### ISSUE TITLE
Can only generate RSA keystore?

### ISSUE THREAD

**Issue by MuhammadZakwan** [keycloak/keycloak#17321]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I am trying to generate the keystore through the Admin Console. 
To generate the keystore I first set the “Client Authenticator” to “Signed Jwt” located at a client’s “Credential” tab and choose a preferred algorithm such as ES256. Then the keystore can be generated over the “Keys” tab. 
However the generated keystore are always in RSA even after changing the algorithm.

### Version

20

### Expected behavior

Generate keystore for the selected algorithm.

### Actual behavior

Only generate RSA keystore.

### How to Reproduce?

1.	Go to Client and click on the “Credential” tab
2.	Set the “Client Authenticator” to “Signed Jwt”
3.	Select preferred algorithm beside RSA
4.	Go to Client and click on the “Keys” tab
5.	Click on “Generate new keys” to generate the keystore
6.	Extract the keys within the keystore and obtain its algorithm

**Comment by mposolda** [comment]
This will be nice to fix, but Keycloak team likely don't have capacity for this in the near future. Community contribution is welcome.

IMO at least we should hide option "Generate keystore" when the ESXXX algorithm is chosen as it is just confusing to have the ability to generate RSA keystore when the algorithm chosen is not RSA-compatible. So this may turn to be just UI (admin console) issue.

**Comment by mposolda** [comment]
I am closing as this should be already available since Keycloak 24 (see release notes for more details).
