### ISSUE TITLE
Minimize the Keycloak image by using "scratch" as a base image

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#17328]
### Description

As part of #16902 the Keycloak image has been minimized. 

The first layer still contains "ubi9-micro", and then everything in the root folder is copied over: 

```
FROM scratch
ENV LANG en_US.UTF-8

COPY --from=ubi-micro-build /tmp/null/rootfs/ /
```

### Motivation

Safe approx 8 MB image size and an additional layer (a local test showed that not all of the 24 MB of the base image are saved, as possibly some of the copied over files already existed in the base image)

### Details

The suggested change would be to use `FROM scratch`.

At the same time it would loose all meta information from the old base image, which are (as the root has been overwritten) possibly misleading anyway?

**Comment by ahus1** [comment]
@ASzc / cc: @vmuzikar: I came across this idea of using `FROM scratch` and it might safe some few MB on the image. There might be a trade-off as we loose some metadata/labels from the original base image - not sure if those would be needed.

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the suggestion! Did you compare it with the latest changes in the image? See https://github.com/keycloak/keycloak/pull/17317

**Comment by ahus1** [comment]
@vmuzikar - the linked PR is only about docs. And yes, I looked at the latest changes in main which changed things towards ubi9.

**Comment by vmuzikar** [comment]
@ahus1 Sorry, yes, wrong PR. ;)
https://github.com/keycloak/keycloak/pull/16879

**Comment by ahus1** [comment]
@vmuzikar - yes, this suggested change builds on top of that PR #16879 and reduces the image size as described above (approx 8 MB).

**Comment by ASzc** [comment]
I don't see `FROM scratch` causing any issues for Keycloak. On the product end, I'm less certain, as this isn't a documented way to do ubi-micro. I'm probably going to need a separate dockerfile for product anyway, but a different parent image might cause subtle issues.

The main difference is [some labels](https://catalog.redhat.com/software/containers/ubi9-micro/61832b36dd607bfc82e66399?container-tabs=dockerfile), and obviously a lack of a parent image link to UBI.

**Comment by ahus1** [comment]
@ASzc - thanks for triaging this. Feel free to close this issue if you think it wouldn't have a positive overall impact by making things more complex.
