### ISSUE TITLE
Extract `attachDevice` call to some layer outside of storage

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#17336]
Logical changes to entities should not be part of the storage layer. This is currently the case with calling method:
https://github.com/keycloak/keycloak/blob/2429d18d78cc48a79658baa6e89e540fe12659c9/model/map/src/main/java/org/keycloak/models/map/userSession/MapUserSessionProvider.java#L182

We should move it to some layer above. Maybe we can create some utility function to group similar changes.

**Comment by mposolda** [comment]
+1 for this change. I was already thinking about this some time ago. There are various places around, which calls `userSessionProvider.createUserSession`, which might be affected, but hopefully this refactoring is doable.
