### ISSUE TITLE
Features guide does not work on Windows

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#17376]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

The Features guide [instructs](https://github.com/keycloak/keycloak/blob/7899c6c80adebebc651688c9e2b7741b18f99d82/docs/guides/src/main/server/features.adoc?plain=1#L15) the users to use `-features=<name>[,<name>]` pattern which doesn't work on Windows as `,` is taken as a [parameters delimiter](https://github.com/keycloak/keycloak/issues/16188#issuecomment-1372477471).

This issue is closely similar to https://github.com/keycloak/keycloak/issues/16188 and fix should be similar to https://github.com/keycloak/keycloak/pull/16298.

### Version

main

### Expected behavior

Guide works on Win

### Actual behavior

Guide doesn't work on Win

### How to Reproduce?

Follow the steps on Win

**Comment by sschu** [comment]
@vmuzikar I'll handle that.

**Comment by vmuzikar** [comment]
@sschu Thanks!

**Comment by sschu** [comment]
PR: https://github.com/keycloak/keycloak/pull/17408
