### ISSUE TITLE
Cannot curl inside dockerfile in 21.x. Works in 20.x.

### ISSUE THREAD

**Issue by terahertz5k** [keycloak/keycloak#17384]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Downloading a provider jar as described in the docs: https://www.keycloak.org/server/containers

When on any 21.x release, building a custom docker image fails with:
```
ERROR [stage-1 11/12] RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3  0.3s

 > [stage-1 11/12] RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar:
#14 0.233 /bin/sh: line 1: curl: command not found
```

Works fine on previous 20.x releases.

### Version

21.0.1

### Expected behavior

curl works when building dockerfile with curl in it

### Actual behavior

curl command not found

### How to Reproduce?

build docker image with curl in it using any 21.x image

**Comment by terahertz5k** [comment]
Looking through recent commits, this one seems like it may have affected this.
https://github.com/keycloak/keycloak/commit/610e3044adea39003fdb256585a74d9adea2cd12

**Comment by terahertz5k** [comment]
Took a stab at a PR https://github.com/keycloak/keycloak/pull/17385

**Comment by terahertz5k** [comment]
Built the keycloak docker image from my fork, then built my custom docker image using the newly built image as the base image. curl no longer fails.

**Comment by mposolda** [comment]
Adding to `area/operator` as we don't have something like `area/container`

**Comment by vmuzikar** [comment]
@terahertz5k Thanks for reporting this.
Removing `curl` was intentional, please see a [PR with updated docs](https://github.com/keycloak/keycloak/pull/17317/files) with possible  mitigation solutions.

**Comment by terahertz5k** [comment]
@vmuzikar , do you have suggested way to do ADD with a URL? The docs don't seem to mention that ADD downloads the file with permissions as 600 and the keycloak user cannot read it. Doing ADD --chmod=644 does not work. Any idea why this doesn't work?

I have to USER root, chmod 644, USER keycloak and these additional layers are causing the gitlab runner to run out of memory.

**Comment by vmuzikar** [comment]
@terahertz5k I think you might be able to do something like `RUN chmod ...`.

**Comment by terahertz5k** [comment]
@vmuzikar , yes I did RUN chmod, but it has the effect of increasing the image size significantly compared to RUN curl. chown does as well. Just letting you know. I'm working on getting a larger gitlab runner to build it, but it does work with either.

Thinking these details should be included in the docs.

**Comment by vmuzikar** [comment]
@terahertz5k Good point, I addressed it here: https://github.com/keycloak/keycloak/pull/17546
