### ISSUE TITLE
Update documentation on user storage provider in Quarkus

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#17394]
Update documentation in https://github.com/keycloak/keycloak-documentation/tree/release/21.0/server_development/topics/user-storage to match Quarkus development for legacy store.

Determine correct target guide, either in https://github.com/keycloak/keycloak-documentation/tree/main/server_development or https://github.com/keycloak/keycloak/tree/main/docs/guides

**Comment by ahus1** [comment]
Latest rendered version: https://www.keycloak.org/docs/latest/server_development/index.html#_user-storage-spi

**Comment by ahus1** [comment]
As a starting point, look at the recent changes to the quickstart. If unsure and touching Quarkus parts, get in touch with CND team.
