### ISSUE TITLE
Active Directory ldap vendor first name field wrong

### ISSUE THREAD

**Issue by tuxmaster5000** [keycloak/keycloak#17409]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

The field "First Name" is  not the givenName from the LDAP system, instant it is an mix of givenName and sn.
Example with this ldap attributes:
CN= Foo, Jon Doe
givenName=Jon
sn=Foo

### Version

21.0.1

### Expected behavior

The user is imported as:
Last name: Foo
First name: Jon Doe
or
First name: Jon 

### Actual behavior

Last name: Foo
First name: Foo, Jon

### How to Reproduce?

Add an User federation service with active directory as the provider.

**Comment by tuxmaster5000** [comment]
It was very vexing, because today I tried the  same on 3 systems, and using the active directory type will create the needed  first name mapper.

**Comment by martin-kanis** [comment]
@tuxmaster5000 So can we close this issue?

**Comment by tuxmaster5000** [comment]
Yes I will do it. When it happens again, I will open an new one.
