### ISSUE TITLE
Gradle dependency resolving issue when using keycloak-admin-client-jakarta

### ISSUE THREAD

**Issue by aosipenko-sc** [keycloak/keycloak#17405]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

I use _**keycloak-admin-client-jakarta**_ in my spring boot 3 project:
``` 
implementation ('org.keycloak:keycloak-admin-client-jakarta:21.0.1')
```
When I try to resolve dependencies I get an exception
```
Could not find jackson-jaxrs-base-2.14.1-jakarta.jar (com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.14.1).
Searched in the following locations:
    https://repo1.maven.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.14.1/jackson-jaxrs-base-2.14.1-jakarta.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Version

21.0.1

### Expected behavior

All dependencies resolve correctly.
Possible we should download `jackson-jaxrs-base-2.14.1.jar`

### Actual behavior

Exception
```
Could not find jackson-jaxrs-base-2.14.1-jakarta.jar (com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.14.1).
Searched in the following locations:
    https://repo1.maven.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.14.1/jackson-jaxrs-base-2.14.1-jakarta.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### How to Reproduce?

1. Create gradle project
2. Add `implementation ('org.keycloak:keycloak-admin-client-jakarta:21.0.1')` dependency
3. Sync dependnecies

### Anything else?

Problem reproduce only in Gradle projects. In Maven all dependencies resolved correctly

**Comment by awallat** [comment]
I've got the same problem. Any workaround for this?

**Comment by tgeens** [comment]
Looks like this breaking change in Jackson 2.13: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13#jakarta-variants-to-replace-javax-modules

> To allow working around the Oracle-created "Javax vs Jakarta" problem, Jackson 2.13 introduces hard forks of 3 kinds of existing modules (see below). You (or your platform/framework) will need to change dependencies appropriately, to get the module needed for your Jakarta-or-Javax APIs (hooray for interoperability).
>
> Note that these modules will obsolete Jackson 2.12 use of "-jakarta" classifier for JAXB and JAX-RS provider modules.
