### ISSUE TITLE
keycloak 21.0.1 authentication flow error: Could not update flow: New flow alias name already exist

### ISSUE THREAD

**Issue by ghorchem** [keycloak/keycloak#17422]
### Describe the bug

Hello when i made a mistake in setting up a browser Authentication Flow I deleted it and tried to recreate in using the same information. when I did I got the error: Could not update flow: New flow alias name already exist.

### Version

21.0.1

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .
