### ISSUE TITLE
Configured OTPs are not valid anymore, and cannot configure new ones

### ISSUE THREAD

**Issue by Mangatome** [keycloak/keycloak#17420]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I am having a very strange issue with a Keycloak docker deployment, originally of version 20.0.1 but I reproduce it with 21.0.1. I followed the documentations and set up a realm and users. First OTP configuration went fine, and for a few weeks OTP auth worked well. But at some point, OTP auth stopped working for my users: all codes started being rejected (error "Invalid authenticator code.").

I thought something was wrong with the authenticator apps, so I tried to reconfigure OTP, and in the configuration screen, I'm still getting "Invalid authenticator code" errors and am left unable to setup OTP for the user.

I tried with FreeOTP and Microsoft Authenticator on Android, same results. Updating the Keycloak docker deployment to 21.0.1 did not help either.

I'm not sure how to debug things further, as I see nothing relevant in the logs.

### Version

21.0.1

### Expected behavior

Entering an OTP at configuration-time or at auth-time should work.

### Actual behavior

OTPs are systematically rejected.

### How to Reproduce?

Very unsure how to reproduce, since the issue appeared several weeks into a working deployment. As far as I can tell, nothing changed in the deployment environment (no container restart, no VM reboot, etc).

**Comment by douglaspalmer** [comment]
Can you export your realm settings and attach them to help reproduce the issue?

**Comment by Mangatome** [comment]
[realm-export.zip](https://github.com/keycloak/keycloak/files/10880579/realm-export.zip)

Thank you for your message. Here you go. I redacted the sensitive stuff by replacing it with bogus values.

However, something caught my eye in the configuration. You will see several different names for this realm, and it is not a redaction typo. At first I named the realm "myrealm" and then renamed it "my_realm", but somehow some paths in the configuration are still mentioning "myrealm". I'm not sure if it's linked but I thought I'd mention it.

**Comment by mposolda** [comment]
@Mangatome Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future.

Moreover, it will help if you can figure how to reproduce it. It will be good to confirm if renaming realm is related to this or completely unrelated. If you figure some details how to reproduce, it can be helpful, but until that, we need to put this "on hold" .

**Comment by Mangatome** [comment]
Hi @mposolda, thanks for this. Weirdly, I'm now reproducing this issue with every fresh install of Keycloak, even if I completely delete container and images and rebuild containers from scratch. So I must be doing something wrong in the container setup...

**Comment by Mangatome** [comment]
After further investigation, I managed to fix my issue. I'm still very unclear what happened and it's bugging me. Since completely clearing and rebuilding containers did not fix it, my next guess is that I had some faulty service in the OS. Anyway, here are the steps I took. I don't know if they really fixed it or if something else happened, but well: 

- full package upgrade in the OS + reboot
- in my keycloak deployment folder: `docker compose down` then `docker system prune --all` to remove images containers and build cache for keycloak.
- deleted keycloak deployment folder (including my keycloak data, not a big deal in my case)
- recreated keycloak deployment folder
- rebuilt and started containers: `docker compose up --build -d`

And now I'm good to go. Closing this issue for now as the problem was most likely host OS-related.

**Comment by Mangatome** [comment]
Reopening this issue. I spoke too soon when I closed it; the issue resurfaced a few weeks later. This still occurs on 22.0.5. In the current state, users are unable to set-up or enter OTPs, as one-time codes are rejected with error message "Invalid authenticator code."

**Comment by Mangatome** [comment]
Update: I'm now fairly confident that the issue begins on the first calendar month change after the host reboots. Will try to create a repro.

**Comment by Mangatome** [comment]
Finally cracked this case. It turns out, for some reason, that the software clock on my host drifts from the hardware clock. After two weeks of uptime, the difference was already 2 minutes. This explains why the OTPs couldn't be validated after some time, but not immediately after reboot (which, on my host, synchronizes the clocks). Running `hwclock --hctosys` on the host, I could synchronize the clocks, and thankfully OTP validation worked again, without needing to reboot.
I know now that the host clock is to blame for this issue, so I will close this and try to investigate the reasons of the skew.
