### ISSUE TITLE
[User Profile Enabled] Email/Password fields disappear from registration when Email as Username is on

### ISSUE THREAD

**Issue by emanueleperuffo** [keycloak/keycloak#17439]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

When Email as Username is on, Email/Password registration fields disappear from the registration form.

I started seeing this issue after upgrading to keycloak 21.0.1.
I'm using the declarative profile.

### Version

21.0.1

### Expected behavior

Email/Password fields should be visible in the registration form.

### Actual behavior

Email/Password fields disappear from the registration form, and it's not possible to register.

### How to Reproduce?

Start Keycloak with the declarative user profile.

Create a new realm, set email as username to true and enable user registration.

Enter the registration form to create a user.

At this point, Email, Password and Password Confirmation fields are not present.

### Anything else?

The issue happens just with enabled "user profile" feature and enabled "user profile" switch for the realm.

Realm export:

```json
{
  "registrationAllowed": true,
  "registrationEmailAsUsername": true,
  "rememberMe": false,
  "verifyEmail": true,
  "loginWithEmailAllowed": true,
  "resetPasswordAllowed": true,
  "internationalizationEnabled": true,
  "supportedLocales": ["en", "it"],
  "defaultLocale": "en",
  "attributes": {
    "userProfileEnabled": "true"
  }
}

```

![Screenshot from 2023-03-03 14-43-25](https://user-images.githubusercontent.com/5085029/222737092-2cf39364-65b5-46d4-86c9-4834ec1965d4.png)

**Comment by mposolda** [comment]
I confirm the issue and also confirm that "Registration" form is missing email and password fields and contains just "First Name" and "Last name" field. To reproduce it is needed both of:
- Enable "Email as Username"
- Enable Declarative User Profile feature and enable user profile for the realm (without user profile enabled, Registration form works as expected).

@pedroigor WDYT? It is a regression, but on the other hand, it is specific just for the "User Profile", which is preview feature. To me, doesn't look like a blocker for Keycloak 22, but leaving to you to decide.

**Comment by pedroigor** [comment]
By dynamically creating the user profile the feature relies heavily on the realm settings.

If the `Edit username allowed` setting is disabled you won't be able to change the email (as it is set as registration as email).

It is a backward compatibility issue and it seems to be an overlap with the user profile permission (read/write model). Perhaps that option should not be shown at all if the user profile is enabled as permissions should be set via attributes.

I'll provide a fix for the problem and we can discuss the point above.

**Comment by mposolda** [comment]
@pedroigor +1 that `Edit username allowed` doesn't makes sense to be shown when user profile is enabled. Does it makes sense sense to hide this option and also ignore it's settings entirely when user profile is enabled for the realm?

Do you prefer to do that in separate PR or still in this one?
