### ISSUE TITLE
robots.txt causes indexing

### ISSUE THREAD

**Issue by wirk** [keycloak/keycloak#17433]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication/webauthn

### Describe the bug

The keycloak subdomain of one of our projects was recently found in the google search results (while searching for the project name, not the url directly). The search result does not contain any page excerpt (not even the title), only the subdomain is displayed. 

The issue here is that the robots.txt disallows robots from crawling the contents, and then the templates contain `noindex, nofollow` to prevent indexing. However, to my understanding the `noindex, nofollow` never comes into effect because robots are forbidden from crawling the documents in the first place. It does not prevent indexing. 
```
User-agent: *
Disallow: /
```

```html
<meta name="robots" content="noindex, nofollow">
```

We would like to remove the robots.txt altogether. However, this is not a static resource but generated by [RobotsResource.java](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/RobotsResource.java). 

### Version

17

### Expected behavior

There is no robots.txt or the contents is customizable

### Actual behavior

There is a robots.txt which prevents crawling but not indexing and it is not customizable

### How to Reproduce?

Access /robots.txt on the keycloak host

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now.

**Comment by MDziurakh** [comment]
@wirk, hi! Did you find a solution?

**Comment by wirk** [comment]
@MDziurakh as a workaround we bypassed keycloak for the robots.txt url and returned our own file from a different location

**Comment by stianst** [comment]
That's some curious behaviour for sure. Seems like we could safely delete robots.txt completely. If anyone wants to drop a PR for that please go ahead.

**Comment by jonkoops** [comment]
Re-opening this as @andy-clapson is offering a PR.
