### ISSUE TITLE
quay.io/keycloak/keycloak:21.0.1 no curl

### ISSUE THREAD

**Issue by marcin-kasinski** [keycloak/keycloak#17438]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When using keycloak on docker there is no curl 

FROM quay.io/keycloak/keycloak:21.0.1

How can I install curl using this release.
There is no package manager

### Version

21.0.1

### Expected behavior

curl installed

### Actual behavior

no curl

### How to Reproduce?

execute curl command inside docker container

**Comment by sirux88** [comment]
I stumbled on this aswell.

In my eyes the key problem is that there's been a switch to  [UBI micro images](https://access.redhat.com/documentation/de-de/red_hat_enterprise_linux/9/html-single/building_running_and_managing_containers/index#con_understanding-the-ubi-micro-images_assembly_types-of-container-images) for keycloak's docker images.
Micro images purpose is having a minimized attack surface.

As a consequence curl is missing on V21.0X images. 
Aswell there's no package manager on micro images to simply reinstall it.

Please switch back to at least ubi minimal images or add curl to the keycloak base image

**Comment by ASzc** [comment]
The short answer is: try to avoid curl if you can, but if you need to install it:

```dockerfile
FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y; dnf --installroot /mnt/rootfs clean all

FROM quay.io/keycloak/keycloak
COPY --from=ubi-micro-build /mnt/rootfs /
```

The docs are being updated with a full explanation

**Comment by Wohlraj** [comment]
Also, if you just need to download a plugin, you can use multi-stage builds like so:
```dockerfile
FROM alpine:latest as downloader
RUN apk add curl
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/${METRICS_SPI_VERSION}/keycloak-metrics-spi-${METRICS_SPI_VERSION}.jar -o /tmp/keycloak-metrics-spi-${METRICS_SPI_VERSION}.jar

FROM quay.io/keycloak/keycloak
COPY --from=downloader /tmp/keycloak-metrics-spi-${METRICS_SPI_VERSION}.jar /opt/keycloak/providers/keycloak-metrics-spi-${METRICS_SPI_VERSION}.jar
```

**Comment by ASzc** [comment]
@Wohlraj A better way to do that is with `ADD`:

```dockerfile
FROM quay.io/keycloak/keycloak
ADD https://github.com/aerogear/keycloak-metrics-spi/releases/download/${METRICS_SPI_VERSION}/keycloak-metrics-spi-${METRICS_SPI_VERSION}.jar /tmp/keycloak-metrics-spi-${METRICS_SPI_VERSION}.jar
```

That instruction [supports URLs](https://docs.docker.com/engine/reference/builder/#add) as the source parameter

**Comment by HerrDerb** [comment]
I needed curl as container healthcheck, to see, if keycloak is ready. I kinda don't want to tinker around with foreign repositories such as aerogear. Is there a file on the filesystem which indicates that keycloak has started and is ready?

**Comment by ASzc** [comment]
@HerrDerb Historically (Wildfly) no, it was always annoying. I don't see any evidence of that in the current quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakMain.java however it seems like it could be easily added, if all one wanted was a marker file that "the server started at some point in the past". However, I could see people not wanting to add this because it's not as accurate as a health endpoint.

Maybe start a discussion for it?

**Comment by ASzc** [comment]
This issue was fixed in #17317

**Comment by HerrDerb** [comment]
The comment from https://github.com/keycloak/keycloak/issues/17273#issuecomment-1456572972 did the trick for me
```
#!/bin/bash
exec 3<>/dev/tcp/localhost/8080

echo -e "GET /auth/health/ready HTTP/1.1\nhost: localhost:8080\n" >&3

timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP
ERROR=$?

exec 3<&-
exec 3>&-

exit $ERROR
```

**Comment by Jameru** [comment]
> The short answer is: try to avoid curl if you can, but if you need to install it:
> 
> ```dockerfile
> FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
> RUN mkdir -p /mnt/rootfs
> RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y; dnf --installroot /mnt/rootfs clean all
> 
> FROM quay.io/keycloak/keycloak
> COPY --from=ubi-micro-build /mnt/rootfs /
> ```
> 
> The docs are being updated with a full explanation

For anyone who might run into the same issue as I did while trying this. That last `COPY` probably overwrite some important stuff, including users.

```dockerfile
FROM quay.io/keycloak/keycloak:21.0.1
RUN id -u keycloak                        # <-- runs ok
COPY --from=ubi-micro-build /mnt/rootfs /
RUN id -u keycloak                        # <-- id: ‘keycloak’: no such user
```

**Comment by Jameru** [comment]
> The short answer is: try to avoid curl if you can, but if you need to install it:
> 
> ```dockerfile
> FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
> RUN mkdir -p /mnt/rootfs
> RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y; dnf --installroot /mnt/rootfs clean all
> 
> FROM quay.io/keycloak/keycloak
> COPY --from=ubi-micro-build /mnt/rootfs /
> ```
> 
> The docs are being updated with a full explanation

For anyone who might run into the same issue as I did while trying this. That last `COPY` probably overwrite some important stuff, including users.

```dockerfile
FROM quay.io/keycloak/keycloak:21.0.1
RUN id -u keycloak                        # <-- runs ok
COPY --from=ubi-micro-build /mnt/rootfs /
RUN id -u keycloak                        # <-- id: ‘keycloak’: no such user
```

**Comment by charafsalmi** [comment]
Hi,
Can anyone suggest a finale version of this Dockerfile using the latest keycloak ?
Thanks.

**Comment by ASzc** [comment]
@charafsalmi Please refer to the documentation https://www.keycloak.org/server/containers#_installing_additional_rpm_packages
