### ISSUE TITLE
Removing the Realm ID and saving causes the realm to be vanished from the list of the realms

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#17449]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Create a relam.
Then select it.
Then go to its general settings.
Remove the field content for the `Realm ID` field.
Then save.
The form is saved (which should not, because `Realm ID` is a required field), and the relam gets vanished from the realm list.

I don't know if it's removed from the database or not.

### Version

20.0.2

### Expected behavior

These are expected:

- Required field should become red as soon as it gets invalid
- Form should not submit while it has an invalid field
- Or if it submits, backend code should not accept that form
- A realm that has no id should be shown in the realms list, with an **Undefined ID** tag for example

### Actual behavior

- Required field does not show any UI/UX feedback when it becomes invalid (when it's empty and dirty)
- Form submits even when it has invalid fields
- Backend code does not check the validity of the form
- A realm without ID would be not shown in the relams list

### How to Reproduce?

- Create a relam.
- Then select it.
- Then go to its general settings.
- Remove the field content for the `Realm ID` field.
- Then save.
- The form is saved (which should not, because `Realm ID` is a required field), and the relam gets vanished from the realm list.

**Comment by antikalk** [comment]
It is also possible to create a realm without realm id via the API:
![image](https://user-images.githubusercontent.com/1793007/223750082-e35bd66c-f2fe-4276-accf-27c36649fea9.png)

![image](https://user-images.githubusercontent.com/1793007/223750130-f8fda4a0-1c02-4aeb-94d2-c8c2efe83bc0.png)

This also shouldn't be possible. In the UI the realm-id is required. Once the realm without realm-id is created you can neither select nor remove it anymore. It seems like the realm-id is not checked/validated on Backend side.

**Comment by ssilvert** [comment]
I'm not seeing this behavior in the UI.  When I remove the Realm ID field and try to save, it properly reports an error as `Required field`.

You could try this on the [latest nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly) and see what happens.  

I am going to move this over to the core team to verify that the API is rejecting a realm settings update with an empty realm id.

**Comment by antikalk** [comment]
@ssilvert Just tested it with the nightly: 
![image](https://user-images.githubusercontent.com/1793007/224794839-0b19605e-5c0a-4fc4-a107-873e83e8031d.png)
The UI now validates that the Realm ID is not empty.

Via the API the creation of a realm with an empty realm id is still possible:
![image](https://user-images.githubusercontent.com/1793007/224795859-cfd72bc6-dfe4-46f1-bcf9-b3954a5a2937.png)

And so is the update:
![image](https://user-images.githubusercontent.com/1793007/224796541-75fa8df8-1e1b-4126-91c3-66983bfd7bd5.png)

**Comment by ssilvert** [comment]
Thanks for the extra info @antikalk.  Definitely an API issue.

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted` as this is a corner case, which affects just with direct use of API (no issue when used with admin console). Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .

**Comment by vplemyannik** [comment]
I would like to fix this issue

**Comment by ahus1** [comment]
Marking this as "help wanted" again as the original PR got stale.

**Comment by SamvWinsen** [comment]
By mistake I did made a realm without an name through the API, we are using keycloak version 22.0.1. It's not accessible through the UI. I did investigate to delete that specific realm, but I'm terrified I delete other realms because everything through the API is based on the name of the realm.
Is there a work a round to delete the realm?

**Comment by antikalk** [comment]
> By mistake I did made a realm without an name through the API, we are using keycloak version 22.0.1. It's not accessible through the UI. I did investigate to delete that specific realm, but I'm terrified I delete other realms because everything through the API is based on the name of the realm. Is there a work a round to delete the realm?

If I remember correctly I had to manually delete that realm from the database directly. Deleting the realm with the API won't work in the case of a realm with an empty Realm ID.
