### ISSUE TITLE
cannot remove custom user attribute

### ISSUE THREAD

**Issue by ComradeSlice** [keycloak/keycloak#17454]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

I am unable to remove a custom user attribute via the frontend in 21.0.1.

### Version

21.0.1

### Expected behavior

attribute should be removed

### Actual behavior

attribute is still present

### How to Reproduce?

1. Navigate to user profile in Admin UI
2. Navigate to Attributes tab
3. Click the "Remove attribute" button next to an attribute
4. Note the attribute will be removed from the DOM
5. Click "Save"
6. Note the attribute has returned

### Anything else?

I have noted the payload of the PUT /{realm}/users/{id} request still contains the attribute I am attempting to remove.

I have also noted I am able to remove the attribute if I invoke the PUT /{realm}/users/{id} endpoint myself, outside of the frontend.

My environment has preview features turned on.

**Comment by zemadz** [comment]
We're experiencing the same issue, attribute cannot be removed from the UI. Keycloak version is 21.0.1.

**Comment by douglaspalmer** [comment]
Seems to be fixed in HEAD.
