### ISSUE TITLE
The performance issue when keycloak admin logs into the web console

### ISSUE THREAD

**Issue by hqch0708** [keycloak/keycloak#17455]
### Description
If we have more than 1000 realms in keycloak, when the keycloak admin logs into the web console, the whoami api is very slow, even may get a 5XX response.

I have created a PR for this enhancement, please take a look at https://github.com/keycloak/keycloak/pull/17402

**Comment by scoopex** [comment]
I wrote a hacky script for reproduction and reproduced that with the latest release.
See: https://github.com/scoopex/keycloak-mass-realm

**Comment by jonkoops** [comment]
Duplicate of #20453
