### ISSUE TITLE
Bug in SAML Redirect Binding with 2 validating certificates

### ISSUE THREAD

**Issue by commander81** [keycloak/keycloak#17456]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

If I configure a SAML-IdentityProvider under Menu -> IdentityProvider and use 2 "Validating X509 Certificates" separated with comma (",") and use Redirect-Binding for IDP Responses I get an error:
Caused by: org.keycloak.common.VerificationException: Invalid key locator for signature verification
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:183)

So we have two certificates with MIIH1DCCBbygAwIBAgITbQASIUmhHRspDof1LAACABI...,MIIHxjCCBa6gAwIBAgITbQAU15owiFXb0lHXUgACABTXmj... 
Note the comma in the middle. This is possible to support signing certificate change of the IDP.
So the assumption is that both certificates are checked for signature validation. This works in the case of POST-Binding, but not in the case of REDIRECT-Binding.
I inspected the code in this area and I found the bug in this case. The verify signature method is a different implementation in case of POST-Binding and Redirect-Binding.
Redirect-Binding uses this Method:
org/keycloak/protocol/saml/SamlProtocolUtils.java:178
There is org.keycloak.rotation.HardcodedKeyLocator#getKey Method used, which implements this method:

public Key getKey(String kid) {
    if (this.keys.size() == 1) {
        return this.keys.iterator().next();
    } else {
        return null;
    }
}

So only in the case we have only one key the implementation works. In the case we have two separated keys it won't work.
The correct implementation is to iterate over the HardcodedKeyLocator like it does the POST-Binding Implementation in this area:
org/keycloak/saml/processing/core/util/XMLSignatureUtil.java:498

### Version

21.0.1

### Expected behavior

No Exception when using 2 certifiactes

### Actual behavior

If I configure a SAML-IdentityProvider under Menu -> IdentityProvider and use 2 "Validating X509 Certificates" separated with comma (",") and use Redirect-Binding for IDP Responses I get an error:
Caused by: org.keycloak.common.VerificationException: Invalid key locator for signature verification
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:183)

### How to Reproduce?

If I configure a SAML-IdentityProvider under Menu -> IdentityProvider and use 2 "Validating X509 Certificates" separated with comma (",") and use Redirect-Binding for IDP Responses I get an error:
Caused by: org.keycloak.common.VerificationException: Invalid key locator for signature verification
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:183)

**Comment by rmartinc** [comment]
Thanks @commander81! You are right, the POST verification uses all keys but the REDIRECT only one. Adding it to keycloak 22 for now but possibly this will be delayed to 23 or later.

**Comment by commander81** [comment]
Thank you @rmartinc for solving it.
