### ISSUE TITLE
Unable to acquire JDBC Connection - Kubernetes Bitnami Chart, PostgreSQL HA, Node Down

### ISSUE THREAD

**Issue by todortanevski** [keycloak/keycloak#17460]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Hello Team,

Kubernetes cluster, these apps installed:

* bitnami chart - keycloak
* bitnami chart - postgresql-ha

Everything works until we test with shutting down one kubernetes worker node (on which keycloak and/or postgresql pods are running).

Then we get an error which seems related to inability to create new JDBC connections, it only reuses existing ones, so actually keycloak works sporadically.

Current workaround is to start the node and delete active keycloak pods.

Is this fixable with manipulating these (or similar) Quarkus values?

```
quarkus.datasource.jdbc.min-size=4
quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.max-lifetime=150
quarkus.datasource.jdbc.idle-removal-interval=50
```

Logs are like this:

```
2023-02-28 12:36:02,282 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) SQL Error: 0, SQLState: null
2023-02-28 12:36:02,282 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (Timer-0) Acquisition timeout while waiting for new connection
2023-02-28 12:36:02,283 ERROR [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-0) Failed to run scheduled task ClearExpiredUserSessions: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
...

```

Have you noticed these issues and is this something that has been worked upon?

Thanks!

### Version

20.0.5

### Expected behavior

Shutting down the kubernetes worker node should not affect Keycloak functioning.

### Actual behavior

Keycloak malfunctions as described in 'Describe the bug' text.

### How to Reproduce?

Create kubernetes cluster using latest bitnami helm chart (keycloak-13.1.1) containing Keycloak 20.0.5, shutdown worker node and use:

`kubectl logs keycloak-0[1|2]`

### Anything else?

No.

**Comment by sschu** [comment]
Just to understand your issue, you run both your database and Keycloak inside your Kubernetes cluster? Then you shut down a worker node? Could it be this actually kills your database pod? Keycloak then just reacts to the DB being unreachable with an exception.

**Comment by todortanevski** [comment]
Correct, that is what is happening - this is a HA test that is being conducted - replicating real live scenario of losing a node.

However, postgresql-ha deployment is resilient, it uses pgpool as entry point, and redistributes primary to other existing standby postgresql node, this is tested and works correctly with latest bitnami helm chart.

It seems, from what is going on, that Keycloak deployment cannot fully recover from this change: during the missing worker node we get aforementioned error, and even after starting the stopped node the pods need to be recreated.

It is worth mentioning that this is reproducible, it is happening all the time in two different test clusters.

**Comment by sschu** [comment]
I don't know how this pgpool implementation works. The error behaviour sounds a bit like Keycloak is still trying to connect to the same stopped node and not to some failover endpoint that would be switched to the working node. At least that's how it works with Azure SQL (and this works fine). Maybe somebody with more knowledge of pgpool can provide more insights how this is expected to work.

**Comment by todortanevski** [comment]
@sschu hmm. i agree...
we set the keycloak connection to the database such that we do use `postgresql-ha-pgpool` as connection string's endpoint. 
what that means is that even if db connection falters for a brief moment it can be re-established after that.
probably keycloak's mechanism doesn't allow that to happen properly. 
we are expecting that to work. if we use a psql cli tool connection can be broken buy is quickly re-established with consequent `SELECT` or `INSERT` statements.
have you tested this kind of behavior? it should be pretty common in dynamic environments like kubernetes.

![image](https://user-images.githubusercontent.com/43077767/223350962-d8416cc5-7019-41c0-8416-60155a2adb27.png)

**Comment by sschu** [comment]
We tested it with Azure SQL failover groups which are DNS-based - if a SQL node fails the failover endpoint is switched to the working node. In you setup, where does "postgresql-ha-pgpool" point to? Directly to the failed node?

**Comment by todortanevski** [comment]
using bitnami's postgresql-ha chart enables following behavior (tested with failovers):
* [Pgpool-II](https://pgpool.net/mediawiki/index.php/Main_Page) act as proxy for PostgreSQL backend. It helps to reduce connection overhead, acts as a load balancer for PostgreSQL, and ensures database node failover
* [bitnami/postgresql-repmgr](https://repmgr.org/) ensures standby nodes assume the primary role when the primary node is unhealthy

**Comment by sschu** [comment]
The thing is, Keycloak itself is not really doing anything fancy here. It uses Quarkus's connection pool implementation agroal. When Keycloak needs a connection, agroal looks into its pool if it already has a working connection and returns it. It could theoretically happen, if you have no background validation enabled on your pool, that the pool returns connections that are actually broken and Keycloak runs into an error. However, this should only last until the point when all connections are discovered to be broken and the pool falls below its minsize limit - then it will definitely try to establish new connections. To get more info on what's going on, you would probably need to activate more detailed logging for the lower layers, especially agroal. But I don't know how to do that.

**Comment by todortanevski** [comment]
It seams active jdbc connections in Keylcoak jdbc pool (Agroal) become invalid/broken after a node failure, and Keycloak cannot recover without deleting a pod, which trigers completely new connections pool creation.

quarkus.datasource.db-kind is postgresql, but it is postgresql-ha cluster, as described above. 

You wrote you tested it with Azure SQL, but it is not working with postgresql-ha cluster (connections become invalid), are there differences in tests (Azure SQL failover behaving differently)?

It looks like Keycloak (or Agroal) issue.

**Comment by todortanevski** [comment]
thanks @abstractj !
bitnami ticket is opened and actively worked upon.

**Comment by todortanevski** [comment]
Hi @abstractj !
We opened a ticket on bitnami forums (https://github.com/bitnami/charts/issues/15335) where we got useful instructions, which helped us a lot.
However, we still hit an issue on keycloak side, descirbed as follows.
