### ISSUE TITLE
Client secret 'Error copying to clipboard'

### ISSUE THREAD

**Issue by ttony-kim** [keycloak/keycloak#17481]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

![image](https://user-images.githubusercontent.com/69332203/223294932-771681cd-fb7a-4b7b-9593-612846587430.png)

Copying is not possible.

### Version

20.0.3

### Expected behavior

Realm > Client > Credentials > Client Secret > Copy to clipboard > copy success

### Actual behavior

Relam > Client > Credentials > Client Secret > Copy to clipboard > 'Error copying to clipboard'

### How to Reproduce?

After installing for the first time and creating a client, I pressed copy right away, but it didn't work.

**Comment by ssilvert** [comment]
@ttony-kim I am not seeing this problem.  

Which browser are you using?
Do you see errors in the [inspector console](https://www.tonegym.co/help/item?id=how-to-open-your-browser-s-inspector-console&f=0)?

**Comment by ttony-kim** [comment]
@ssilvert I am using chrome browser.
Nothing is displayed in the inspector console.

**Comment by edewit** [comment]
are you using http and something other then localhost?

**Comment by ttony-kim** [comment]
@edewit I am using http.
However, when I tested on localhost, the same error did not come out.

**Comment by ssilvert** [comment]
This is sort of sounding like https://github.com/keycloak/keycloak/issues/17817, which is fixed in the nightly build.

Can you try it out?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ttony-kim** [comment]
@ssilvert I don't understand this way

**Comment by ssilvert** [comment]
@ttony-kim Have you been able to try out the nightly build to see if your problem goes away?

**Comment by ttony-kim** [comment]
@ssilvert Trying a nightly build also gives the same error.

**Comment by edewit** [comment]
@ttony-kim the use of the clipboard is protected and will only work when using http and localhost or https

**Comment by ttony-kim** [comment]
@ssilvert 
I was curious because it was used on localhost.
I understand now. thank you
