### ISSUE TITLE
MultiVersionClusterTest not working for Quarkus based distribution

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#17483]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Since Keycloak was migrated to a Quarkus-based distribution, the MultiVersionClusterTest has been failing. According to the storage team members, this requires a big refactor of the test.

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

`mvn -f testsuite/integration-arquillian/pom.xml clean install -Pauth-server-quarkus,auth-server-cluster,db-mysql,jpa -Dsession.cache.owners=2 -Dbackends.console.output=true -Dauth.server.log.check=false -Dfrontend.console.output=true -Dauth.server.legacy.version=19.0.0 -Dtest=MultiVersionClusterTest`

**Comment by vmuzikar** [comment]
This was meant for zero-downtime, no longer relevant. The test will be removed
