### ISSUE TITLE
Test connection in realm Email settings hangs

### ISSUE THREAD

**Issue by pantovad** [keycloak/keycloak#17489]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Test connection in realm e-mail settings hangs. In the Chrome (Version 110.0.5481.177) dev console the error is reported:
```
Alerts.tsx:51 Uncaught (in promise) TypeError: crypto.randomUUID is not a function
    at Alerts.tsx:51:20
    at Alerts.tsx:64:5
    at w (EmailTab.tsx:111:7)
(anonymous) @ Alerts.tsx:51
(anonymous) @ Alerts.tsx:64
w @ EmailTab.tsx:111
await in w (async)
onClick @ EmailTab.tsx:386
Nb @ react-dom.production.min.js:54
Tb @ react-dom.production.min.js:54
Ub @ react-dom.production.min.js:55
nf @ react-dom.production.min.js:105
se @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
Rk @ react-dom.production.min.js:274
Jb @ react-dom.production.min.js:52
hd @ react-dom.production.min.js:109
fd @ react-dom.production.min.js:74
ed @ react-dom.production.min.js:73
```
### Version

21.0.1

### Expected behavior

The test should complete with notification success/failure.

### Actual behavior

The test hangs having activity circle in 'Test connection' button rounding.

### How to Reproduce?

- Configure the settings in Email tab of realm settings page
- Press the Test connection button

**Comment by pantovad** [comment]
Apparently many operations in admin UI  using generateId() in Alerts.tsx are misbehaving and reporting:

`Alerts.tsx:51 Uncaught (in promise) TypeError: crypto.randomUUID is not a function`

**Comment by ssilvert** [comment]
This should be fixed by https://github.com/keycloak/keycloak-ui/issues/4442

I'm going to close the issue, but if you want to verify the fix you can check the nightly build at
https://github.com/keycloak/keycloak/releases/tag/nightly

If the problem persists we can reopen this.
