### ISSUE TITLE
File storage: introduce locking mechanism to prevent concurrency issues when reading/writing files

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#17492]
### Description

Reading and writing files in a concurrent environment can lead to unpredictable results if steps to protect these operations are not taken.

As such, a locking mechanism for the file store needs to be implemented. This mechanism must ensure only a single thread has access to the file in the following circumstances:

- When reading the file, a thread should have exclusive access until it has acquired an input stream it can use to read the entity from. After that the lock can be released and the stream consumed normally.
- When moving the temporary file produced by `create` or `update` into the actual file that represents the entity. Writing the entity into the temp file doesn't need to be locked as each thread will produce a different temp file, but the `move` operation that is performed on `commit` must be protected until it is completed.

As the file storage can be used in read-only mode, a no-op implementation of the locking mechanism should be available too. The actual locking strategy must be configurable.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
