### ISSUE TITLE
kc.sh show-config prints the config twice

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#17498]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

After building with `build` and then showing with `show-config`, the configuration is printed twice. 

There's also a misleading output: 

> Changes detected in configuration. Updating the server image.

### Version

nightly

### Expected behavior

Configuration is printed once, no message about "changes detected". 

### Actual behavior

Actual output: 

```
$ bin/kc.sh show-config 
Changes detected in configuration. Updating the server image.
Current Mode: production
Current Configuration:
        kc.cache =  ispn (PersistedConfigSource)
        kc.config.build-and-exit =  true (SysPropConfigSource)

...
Next time you run the server, just run:

        kc.sh start --optimized 

Current Mode: production
Current Configuration:
        kc.cache =  ispn (PersistedConfigSource)
        kc.config.built =  true (SysPropConfigSource)
        kc.db =  dev-file (PersistedConfigSource)
        kc.health-enabled =  false (PersistedConfigSource)
```

### How to Reproduce?

1. unzip the distribution
2. call `bin/kc.sh build --storage=jpa --storage-area-realm=chm`
3. call `bin/kc.sh show-config` 

### Anything else?

I searched the guides for `show-config` on how it should be used, but didn't find an entry. Maybe there's also some missing docs on how to use it / what to expect.

**Comment by pedro-hos** [comment]
I was able to reproduce the same scenario on Keycloak 21.0.1

**Comment by pedro-hos** [comment]
Show config is here https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/cli/command/ShowConfig.java but I can't find where the print is done
