### ISSUE TITLE
kcadm running partialImport doesn't behave like APIs or GUI for duplicate emails

### ISSUE THREAD

**Issue by joao-rebelo** [keycloak/keycloak#17501]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

I'm trying to run an user partial import with Keycloak 20, with a realm where the option for Duplicate Emails is ON (and Login with email is OFF)
This partial import has users with duplicated emails, and is set to policy: SKIP .

Although I can import from the Web Admin console, and by calling the API by curl:

curl --location --request POST 'https://{myHost}:{myPort}/auth/admin/realms/{realm}/partialImport' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ..' \
--data-binary "@data.json"

it doesn't work when importing from the kcadm:

/opt/keycloak/bin/kcadm.sh create partialImport -r {realm} -o -f data.json

When calling by kcadm at keycloak log I can then see

{"timestamp":"2023-03-07T18:42:09.203+01:00","sequence":8479,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.hibernate.engine.jdbc.spi.Sq
lExceptionHelper","level":"ERROR","message":"ERROR: duplicate key value violates unique constraint \"uk_dykn684sl8up1crfei6eckhd7\"\n  Detail: Key (realm_id, email_con
straint)=(465c4869-45b5-402d-ba91-cef64de5e9e6, {private email}) already exists.","threadName":"executor-thread-204","threadId":246,"mdc":{},"ndc":"
","hostName":"keycloak","processName":"QuarkusEntryPoint","processId":1}

Note: I'm hiding confidential information with the {}.. actual commands and logs have real info

### Version

20.0.3

### Expected behavior

Import should run, similar as from the GUI or API importing users with duplicated emails

### Actual behavior

kcadm returns an error where the API and GUI works fine importing the users with duplicated emails

### How to Reproduce?

setup a partial import file where 2 or more users share the same email.
At the realm definition activate the Duplicate Emails to ON

run the import with kcadm and then through GUI / API to see the different behavior

**Comment by hmlnarik** [comment]
This is a difference in the behaviour of `kcadm` command as compared with API / GUI call, and not store-related. Thus removing the import-export area
