### ISSUE TITLE
Keycloak CRD incompatible with `kpt` since does not set `status.observedGeneration` 

### ISSUE THREAD

**Issue by kriswuollett** [keycloak/keycloak#17515]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

If a `Keycloak` CRD is added to the cluster, initially has errors, but then is updated, tools like `kpt` do not recognize the status conditions change since it does not set `status.observedGeneration`, see 

### Version

21.0.1

### Expected behavior

The `status.observedGeneration` field is set on `Keycloak` resources.

### Actual behavior

Including a `Keycloak` inside a `kpt` package may cause `kpt live apply` to fail to see `Keycloak` being reconcilied.

### How to Reproduce?

See description above, e.g., initially use an invalid secret name during initial `kpt live apply`.

### Anything else?

https://kpt.dev/reference/schema/crd-status-convention/
https://github.com/GoogleContainerTools/kpt/issues/1312

**Comment by Pepo48** [comment]
Hi @kriswuollett,

first of all, thanks for the report. We currently don't support the `kpt` tool. If you feel like wider community could benefit from adding the support, feel free to open [ adiscussion](https://github.com/keycloak/keycloak/discussions) or add the implementation. Contributions are always welcomed.

I'm closing the issue for now but you can always reopen it in case of relevant updates in the future.

Thanks!

**Comment by kriswuollett** [comment]
@Pepo48 RedHat OpenShift also uses this `observedGeneration` convention, see https://docs.openshift.com/container-platform/4.12/service_mesh/v2x/ossm-reference-smcp.html#ossm-cr-status_ossm-reference for example. 

<img width="1019" alt="CleanShot 2023-03-09 at 11 37 29@2x" src="https://user-images.githubusercontent.com/1834192/224109973-2508ebce-7a71-4c41-8000-9cd700e8dab8.png">
