### ISSUE TITLE
SAML2 Client Signing Keys Config does not accept PEM import

### ISSUE THREAD

**Issue by hmolsen** [keycloak/keycloak#17514]
### Before reporting an issue

- [x] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I want to create a new SAML2 client in Keycloak and I want to require client signatures, I can click `Regenerate` and receive a private key. The conceptual problem is that
a) keycloak should never know the private key
b) I don't want to transfer the private key to my client. 
Private keys are private. They should be generated on the client and remain on the client. What I actually want to do is to import the client's public certificate as trusted.
This behaviour is broken since the Admin-UI redesign.
![image](https://user-images.githubusercontent.com/5484682/223795230-3951c066-dbfb-40a1-85f8-d33fced14aa3.png)

When I click on `Import Key` the dropdown seems to be broken:
![image](https://user-images.githubusercontent.com/5484682/223795473-7ea9c6b5-4775-4e8c-af1f-4f3b05565cbe.png)
I want either .crt or .pem import, but the only options available are JKS and PKCS12.

I can create a PKCS12 file on my client without a private key:
````
└─$ openssl pkcs12 -export -nokeys -in public.crt -name foo -out foo.p12                                         1 ⨯
Enter Export Password:
Verifying - Enter Export Password:
````
But if I import this in keycloak I get the following error:
![image](https://user-images.githubusercontent.com/5484682/223802167-66323e79-058a-434c-b599-612ccba47011.png)

What am I missing here? Keycloak does not need the client's private key, so why is this new dialog forcing me to give it one?

### Version

21.0.1

### Expected behavior

I can import a trusted cert from the client

### Actual behavior

I have to provide a private key or use the private key which keycloak generates, which does not make sense from a security perspective

### How to Reproduce?

1. Start fresh keycloak (e.g. use the getting-started-docker guide)
2. Create new Realm
3. Create new SAML2 client
4. Go to `Keys` Tab of the client configuration
5. Try to import a .pem or .crt public certificate from the client

**Comment by ssilvert** [comment]
@hmolsen Thanks for reporting.  We will fix this ASAP.

As for generating private keys from the admin console, this is the way the old console worked as well.  The private key is only generated by the UI and never stored on the server.
