### ISSUE TITLE
Custom roles influence whether GET /users succeeds for a client service account

### ISSUE THREAD

**Issue by blagae** [keycloak/keycloak#17567]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

When using a service account and the client secret to authenticate directly for a specific GET request (/users), I need to add custom roles to the service account for the request to succeed. This is presumably because the JWT token doesn't include the roles of the account if there is no custom information.

### Version

19.0.1

### Expected behavior

When the client has all service account roles including the custom ones, the request succeeds:

![bug-all-roles-assigned](https://user-images.githubusercontent.com/8480167/224295533-5544f199-e1fd-4c56-b4db-5f0ab1044bdb.png)
![bug-users-request-succeeds](https://user-images.githubusercontent.com/8480167/224295526-3e9d1025-9319-4afa-b11b-c1be9af5e11b.png)

This should also occur if there are no custom roles

### Actual behavior

When the client has all service account roles except the custom ones, the request fails with a HTTP 403 response:

![bug-custom-roles-unassigned](https://user-images.githubusercontent.com/8480167/224295534-cbbd8501-971a-425e-8e1d-b77c8bbbf8b4.png)
![bug-users-request-fails](https://user-images.githubusercontent.com/8480167/224295536-ac52066e-bf3c-41e2-abb2-d4ea07eff4fe.png)

### How to Reproduce?

* Setup a basic realm
* Create a few custom roles 
* Setup a client with client auth, authorization, authentication flow "standard flow" and "direct access grants"
* Grant the client all realm & management roles except the custom ones
* Use Postman or a similar tool to request a token, then use that token to make a GET request to `{{server}}/admin/realms/{{realm}}/users`

### Anything else?

I dug a little deeper and I found that the JWT token generated for the authentication request is a lot smaller if there are no custom roles, because the scope defined in the token does not contain the `roles` entry:

Without custom roles:

```json
{
  "exp": 1678445000,
  "iat": 1678444700,
  "jti": "5da58127-34c2-4231-9c32-348812c0e718",
  "iss": "https://<domain>/realms/<realm>",
  "sub": "d32466ab-507a-455f-9812-c1e3b8609532",
  "typ": "Bearer",
  "azp": "<client-name>",
  "acr": "1",
  "scope": "profile email",
  "email_verified": false,
  "clientId": "<client-name>",
  "clientHost": "<IP>",
  "preferred_username": "service-account-<client-name>",
  "clientAddress": "<IP>"
}
```

With custom roles:

```json
{
  "exp": 1678445020,
  "iat": 1678444720,
  "jti": "3c32e33b-55df-4d10-ae39-82f216f3ffb9",
  "iss": "https://<domain>/realms/<realm>",
  "aud": [
    "realm-management",
    "broker",
    "<other-client-name>",
    "account"
  ],
  "sub": "d32466ab-507a-455f-9812-c1e3b8609532",
  "typ": "Bearer",
  "azp": "<client-name>",
  "acr": "1",
  "realm_access": {
    "roles": [
      "<prefix>-admin",
      "<prefix>-edit-data",
      "<prefix>-read-access",
      "offline_access",
      "default-roles-<realm>",
      "uma_authorization",
      "<prefix>-superadmin"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "view-realm",
        "view-identity-providers",
        "manage-identity-providers",
        "impersonation",
        "realm-admin",
        "create-client",
        "manage-users",
        "query-realms",
        "view-authorization",
        "query-clients",
        "query-users",
        "manage-events",
        "manage-realm",
        "view-events",
        "view-users",
        "view-clients",
        "manage-authorization",
        "manage-clients",
        "query-groups"
      ]
    },
    "broker": {
      "roles": [
        "read-token"
      ]
    },
    "<other-client>": {
      "roles": [
        "uma_protection"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "view-applications",
        "view-consent",
        "manage-account-links",
        "manage-consent",
        "delete-account",
        "view-profile"
      ]
    },
    "<client-name>": {
      "roles": [
        "uma_protection"
      ]
    }
  },
  "scope": "profile email roles",
  "email_verified": false,
  "clientId": "<client-name>",
  "clientHost": "<IP>",
  "preferred_username": "service-account-<client-name>",
  "clientAddress": "<IP>"
}
```

**Comment by mposolda** [comment]
@blagae Looks like a setup issue.

I think you need to have:
- The scope `roles` defined as default client scope for your client
- In the tab `Scope`, make sure that all "Roles scopes" are available. You can try to temporarily switch "Full Scope Allowed" to ON and see if it helps and your service-account client will contain the roles.
