### ISSUE TITLE
group don't have any clickable link even though it have the access right permission on UI

### ISSUE THREAD

**Issue by FasterLeaner** [keycloak/keycloak#17561]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

In Fine Grain Admin Permissions, we would like to grant permission on specific users in the specific group. The bug is that we can't click on the group even though we have the access right permission on that group. We don't have that issue in the version 20. We realized that the older version of UI has been removed and new UI version has been replaced. It seems that version 21 introduced the permission ofthe clickable link on the group but never think about the permission. 

Please check following code in the UI
i) In GroupsSection.tsx (line 69), there is a canViewDetails variable which will be assigned by checking the access right of either view-users or manage-users. By right , it should be checking also to have the access right of permission on that group.  
ii) In GroupTable.tsx (line 91) , that canViewDetails variable will be decided to have the link or just group name (non-clickable) 

### Version

version 21.0.1

### Expected behavior

Should have the clickable on the group name instead of group name only. 

### Actual behavior

Don't have the clickable link on the group name even though we have the proper access right permission on the group name. 

### How to Reproduce?

1) login to the admin console with the admin account
2) Create the new realm and give proper name as (Trial) 
3) Switch to the Trial (realm) from the master realm in the master
4) create the Trial_admin user 
    4_1) Switch to the user menu, create the Trial_admin (user). 
    4_2) To the Trial_admin user, add the credential with your password.
    4_3) To the Trial_admin user, add the realm-admin role. How to add the role
           a) go to the Role mapping in the Users Menu
           b) click on Assign role button, Assign roles pop up will appear
           c) go to the Filter by realm roles, click on Filter by clients
           d) search realm-admin and then add it
5) create group1_adminuser
    5_1) click add user button to add group1_admin (user). 
    5_2) To the group1_admin user, add the credential with your password.
    5_3) To the group1_admin user, add the query-clients, query-users and query-group roles. How to add the role
           a) go to the Role mapping in the Users Menu
           b) click on Assign role button, Assign roles pop up will appear
           c) go to the Filter by realm roles, click on Filter by clients
           d) search query-clients, query-users and query-group and then add it
6) create group2_adminuser
    5_1) click add user button to add group2_admin (user). 
    5_2) To the group2_admin user, add the credential with your password.
    5_3) To the group2_admin user, add the query-clients, query-users and query-group roles. How to add the role
           a) go to the Role mapping in the Users Menu
           b) click on Assign role button, Assign roles pop up will appear
           c) go to the Filter by realm roles, click on Filter by clients
           d) search query-clients, query-users and query-group and then add it

7) create group 1 under Groups menu
     7_1) add the group1_admin into group 1
8) create group 2 under Groups menu
     8_1)add the group2_admin into group 1 
9) enable the fine grain permission in any group (permission enable) 
10) To create the policy for group
      10_1) go to the Clients menu
       10_2) click on real-management and then go to the Authorization tab
       10_3) go to the Policies tab under Authorization tab
       10_4) Click on Create policy button to add group1_admin_policy
       10_5) select Group in the pop up for policy type
       10_6) in the group policy pop up, give the name (group1_admin_policy) 
       10_7) join the group to the group1 and then save
       10_8) Click on the create policy button to add group2_admin_policy
        10_9) repeat the step for group 2 admin policy from 10_5 to 10_7

11) apply those policy in the group 1 and group 2 in the permission tab, go to permission and select manage_members and view permission and then add the proper permission
12) logout form the admin console and switch to the Trial Realm 
13) then login with group1_admin to the Trial Realm
14) by right, group1_admin should have the access right to click on group1 under the groups menu. 
       

### Anything else?

N.A

**Comment by antikalk** [comment]
Yep, that is a regression from the 21 release, see my comment here: https://github.com/keycloak/keycloak/issues/17589#issuecomment-1465002176

**Comment by FasterLeaner** [comment]
Thank you for your comment. I hope someone is looking to it.

**Comment by ssilvert** [comment]
I believe this is fixed now, at least for the navigation tree.  There are still instances where a group in the "Child groups" tab will not be clickable when a user has fine-grained permissions.  Right now, there is no way to get a reference to the access object from the table.  But at least you will always be able to get to the group from the tree view on the left side.

Can you verify this in the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly
