### ISSUE TITLE
Admin console refresh makes a 401 access denied

### ISSUE THREAD

**Issue by JakKowalCzyk** [keycloak/keycloak#17563]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I am logged in into the admin console with an admin role and when I decide to refresh the page I receive the 401 access denied error after the page was reloaded.
Not sure if this is connected to any Authentication/ flow settings or login methods.

### Version

Keycloak 21.0.1 on JVM (powered by Quarkus 2.13.7.Final)

### Expected behavior

The page should be reloaded and the current view should be maintained. No 401 error should be thrown

### Actual behavior

An 401 access denied error appears

### How to Reproduce?

Refresh a page when logged in into admin console

**Comment by darius-m** [comment]
I have encountered this issue when the Infinispan caches failed to synchronize, making some Keycloak nodes unable to fetch the admin user session information properly. As such, whenever the requests went to the original node that performed the authentication, they would succeed, but would otherwise fail on other nodes. Please add some details about your deployment.

As a debugging step, you could look into the Keycloak / Infinispan log to confirm whether there have been any cache-related errors.

**Comment by ssilvert** [comment]
@JakKowalCzyk Did the suggestion from @darius-m help you?

We would need a reliable way to reproduce the problem in order to address this.

**Comment by JakKowalCzyk** [comment]
@darius-m @ssilvert sorry, it seems that it's something different. 
I've discovered that it's due to one of my authentication flows, which are set to admin client.
I am not sure if I am having something wrong set in the flow or there is some issue on the Keycloak site.
Are you able to give me some hints? If the problem is on my site, sorry for reporting in the wrong place.

The flow is supposed to decline users which wants to login to admin console, and they should the denied access message.
![image](https://user-images.githubusercontent.com/12873002/225233224-a5e4e4b5-b122-46e2-919f-0961cad5fc63.png)

In the role condition, it is checked if a user has an admin role assignment.

**Comment by ssilvert** [comment]
@JakKowalCzyk I'm wondering about your use case.  A user that doesn't have access to the admin console will already be denied access.  Why use a flow for this?

**Comment by JakKowalCzyk** [comment]
@ssilvert the case is to completely hide keycloak from the end-user. So if someone will guess our keycloak admin url he won't see access denied on keycloak admin page but he will see our custom error access denied page - because when a user without admin role will login to admin console he sees the admin console but with the access denied as I remember.
I suppose it's an easier option than IP restriction etc.

**Comment by ssilvert** [comment]
I'm pretty certain this is not a bug in the admin console.  I'm not sure if the role step is meant to work like you want on browser refresh.

**Comment by JakKowalCzyk** [comment]
@ssilvert I see, we can close the issue then, thanks for the help
