### ISSUE TITLE
admin-ui: authz unable to access child group when using fine grained auth

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#17588]
### Describe the bug

When trying to access a childgroup when using fine grained permissions I am getting the following error in the UI:
![image](https://user-images.githubusercontent.com/1793007/220681386-28e768b9-8580-4353-8127-afcffbd83d23.png)

### Version

20.0.3

### Expected behavior

I should be able to open the child group

### Actual behavior

I get an error
![image](https://user-images.githubusercontent.com/1793007/220681378-3eccc65a-d762-439a-b5a9-8c3c0dc7a910.png)

### How to Reproduce?

1. Create a realm testrealm
2. Create a user testuser with query-groups role
3. Add credentials for that user
4. Create a group A and enable fine grained permissions for that group
5. Create a subgroup of group A called B
6. Enable fine grained permissions for group B (this is necessary as permissions of groups are at the moment not inherited, see discussion: https://github.com/keycloak/keycloak/discussions/16915)
7. In clients -> realm-management -> authorization -> policies create a user policy for the testuser
8. Assign that policy to the view and view-members permission of group A and group B.
9. Log in to the admin console of the testrealm with the created testuser
10. Open Groups
11. Click on group A -> should work
12. Click on group B -> should crash

### Anything else?

I also noticed that when you do not have permissions on a group to view or manage it, it is still displayed in the groups overview. It would be a nice to have if I would only see the groups I have permissions for (and their children, depending on this discussion: https://github.com/keycloak/keycloak/discussions/16915).

**Comment by ssilvert** [comment]
This should be fixed now from https://github.com/keycloak/keycloak/pull/19423.  Please check the nightly.

I responded to your discussion.  It's a nice idea, but I don't think it will ever get done unless we re-implement the whole fine-grained authorization mechanism.

**Comment by antikalk** [comment]
Thanks @ssilvert. I checked the nightly and the issue is solved :)

**Comment by jonkoops** [comment]
Awesome, thanks for checking this @antikalk.

**Comment by rkdutta** [comment]
Hello @antikalk @ssilvert 

I am evaluating the fine-grain-admin-authz feature. My Keycloak version is 26.1.4. 
I still find it challenging to extend parent group permission to child group. For each child group, I need to explicitly create a permission. Is this already possible to inherit permission from parent to child group? Could you please guide?
