### ISSUE TITLE
User with "view-clients" role cannot view credentials in Admin Console, but can still use the API to fetch them.

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#17587]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Scenario:
A normal admin of the admin-ui, can view client credentials for all clients and access the admin UI as below:

![image](https://user-images.githubusercontent.com/4944041/222171413-d728eb7a-e666-4353-8b59-5c7b95a41250.png)

A user can provided the "view-clients" role on a realm. This user can access the admin UI and view most client information. 

The "credentials" tab for confidential clients is not displayed for this user. However, the user can simply call the REST endpoint to retrieve the credentials any way as it is only predicated on the "view-clients" role itself.

![image](https://user-images.githubusercontent.com/4944041/222171109-cc552288-e6f8-4a5d-8655-929db11146b6.png)

This is misleading to users of this role as they may erroneously attribute "view-clients" as _not_ providing access to the client credentials by hiding the tab, but the REST endpoint definition shows otherwise.

[REST Endpoint Permission](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/ClientResource.java#L318)

```bash
curl 'http://localhost:8080/admin/realms/master/clients/54666dd8-3472-493e-a61b-80750e889316/client-secret' \
>   -H 'Accept: application/json, text/plain, */*' \
>   -H 'Accept-Language: en-US,en;q=0.9' \
>   -H 'Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJNZjVXbXJCdjRSdGhSZnd1N2ZmczBxRGFjYXNoVnFBNm5QMkdsa0V6dTlrIn0.eyJleHAiOjE2NzYwNzQ3OTcsImlhdCI6MTY3NjA3NDczNywiYXV0aF90aW1lIjoxNjc2MDc0NjEzLCJqdGkiOiIxMGVlMmQ3NC0wMDhmLTQ5N2UtYTFhMy1mMzhlZDVlOWYxYmEiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsInN1YiI6IjlkN2UxNTE1LTE2YzYtNGIxYi05ODhiLWEzZTM4MWFlZDM0OCIsInR5cCI6IkJlYXJlciIsImF6cCI6InNlY3VyaXR5LWFkbWluLWNvbnNvbGUiLCJub25jZSI6IjkwYThkZDg0LWM3MmQtNGZlNy04Mzk1LTI5MmE1NDFjOGFkYyIsInNlc3Npb25fc3RhdGUiOiJiZjIwNzFkMS1kN2NlLTQ0MGUtODMzYy0yNGM5ZWJmOTE1NjciLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCJdLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiYmYyMDcxZDEtZDdjZS00NDBlLTgzM2MtMjRjOWViZjkxNTY3IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ2aWV3b25seSIsImdpdmVuX25hbWUiOiIiLCJmYW1pbHlfbmFtZSI6IiJ9.XdkSkaqwYlGOR_zWGwndLb6allCcTQ6IsOy0XCYo0XvQ-icT8_4P8x0IXM0JTZpLmejEFNtqXzbeDHtt4XGjcd2Yiu5AVqRvVHLvjmvX4VDx8KBbgQiFfu6AIij2kQl94sGZDFMvD4o1F5gZJy9UgBDA1x_ApVHdq9_hTiBEyapErWl2Vo9g8fZKLxbSuhHwn75vLx2w9K34-KSlSh89wz3TtRaFPnPqsm46J78zq69HCUX4--wZMHKPqaoh-kXXY9dxE4AE4_hRZin6gmt4gahM66phnjYPv9beMhq3TKezyK1WQ5raSgUlZHTYIZvG8acDOlSyXS0I_jhw6iBRzQ' \
>   -H 'Cache-Control: no-cache' \
>   -H 'Connection: keep-alive' \
>   -H 'Pragma: no-cache' \
>   -H 'Sec-Fetch-Dest: empty' \
>   -H 'Sec-Fetch-Mode: cors' \
>   -H 'Sec-Fetch-Site: same-origin' \
>   -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[109.0.0.0](http://109.0.0.0/) Safari/537.36' \
>   -H 'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'sec-ch-ua-platform: "Linux"' \
>   --compressed
{"type":"secret","value":"2gHwb4iIIZp0XLkxx1iUbAOVHHeoenG2"}
```

### Version

20.0.3

### Expected behavior

UI reflects the actual access the user has (Credentials tab is shown to users with view-clients).

### Actual behavior

Credentials tab is not shown to users with view-clients.

### How to Reproduce?

1. Spin up a local Keycloak instance using docker
2. Authenticate as the admin user
3. Add a non-admin user - `viewonly`
4. Grant this non-admin user the `view-clients` role
5. Set a password for the non-admin user
6. Create a confidential client with a secret - observe the tab is displayed
7. Authenticate as the non-admin user and view the client that was created - observe the tab is not displayed.

### Anything else?

This appears to be the logic that predicates whether or not a user can view this tab - maybe there needs to be an change for a "read-only" view of the secret based on the `view-clients` role?

https://github.com/keycloak/keycloak-ui/blob/main/apps/admin-ui/src/clients/ClientDetails.tsx#L450

**Comment by ssilvert** [comment]
This should be fixed from https://github.com/keycloak/keycloak/issues/19134

Please check the nightly build.  We can reopen if you still see a problem.

https://github.com/keycloak/keycloak/releases/tag/nightly
