### ISSUE TITLE
admin-ui: authz viewing of a group requires also view-members permission

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#17589]
### Describe the bug

When using fine-grained permissions on a group and only having the view permission, I am unable to open a group in the admin ui.

![image](https://user-images.githubusercontent.com/1793007/220675748-71f1ac93-a518-4e25-b968-2f9534b307f9.png)

### Version

20.0.3

### Expected behavior

The group is opened and the members tab is hidden, as the user has no permissions do view or manage the members of the group.

### Actual behavior

![image](https://user-images.githubusercontent.com/1793007/220675748-71f1ac93-a518-4e25-b968-2f9534b307f9.png)

Request failed with status code 403

### How to Reproduce?

1. Create a realm `testrealm`
2. Create a user `testuser` with `query-groups` role
3. Add credentials for that user
4. Create a group `A` and enable fine grained permissions for that group
5. In `clients` -> `realm-management` -> `authorization` -> `policies` create a user policy for the `testuser`
6. Assign that policy to the view permission of the group.
7. Log in to the admin console of the `testrealm` with the created `testuser`
8. Open `Groups`
9. Click on group `A`

### Anything else?

Debugging the network traffic reveals that the group details are returned, but then the UI proceeds to request the members of the group which then returns a `403` error. The members should not be requested if the user does not have the permissions to do so (view-/manage-members).

**Comment by FasterLeaner** [comment]
@ssilvert , May I know will you follow up the issue #17561 as well? Thanks.

**Comment by ssilvert** [comment]
> @ssilvert , May I know will you follow up the issue #17561 as well? Thanks.

Yes.  Hopefully, this coming week.

**Comment by ssilvert** [comment]
Since this is new functionality, changed this issue from bug to enhancement.

**Comment by antikalk** [comment]
Thanks @ssilvert ! :) I assume my PR https://github.com/keycloak/keycloak/pull/17349 can than be closed?
