### ISSUE TITLE
logged in users name encoded twice in account panel header

### ISSUE THREAD

**Issue by Guite** [keycloak/keycloak#17595]
### Area

account/ui

### Describe the bug

When a logged in user opens the account panel his first and last name are printed at the upper right corner. As soon as any action is done this string is output-encoded again so HTML entities are shown.

### Version

19.0.2

### Expected behavior

The name is shown in a human-friendly way.

### Actual behavior

The name is shown with HTML entities.

### How to Reproduce?

1. Create a user with first name "A&B" and last name "Test".
2. Log in with this user.
3. Open the account panel.
4. Note you see `A&B Test` in the upper right corner (correct).
  ![image](https://user-images.githubusercontent.com/277531/201294038-eec3f370-b8b9-48a8-8c6b-cd40bef2fc58.png)
5. Move to any sub page of the account UI.
6. Note you see `A&amp;B Test` in the upper right corner now (incorrect).
  ![image](https://user-images.githubusercontent.com/277531/201294183-c8b5c9ea-349f-4d31-ba1b-bc1d33ec5f85.png)

**Comment by jonkoops** [comment]
Closing this as we have now shipped the new version of the Account Console in Keycloak 24. If this bug persists in the new version then please let us know.
