### ISSUE TITLE
Keycloak js adapter login method problem

### ISSUE THREAD

**Issue by SetoKaiba** [keycloak/keycloak#17600]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

For `keycloak.init({onLoad: 'login-required'})`, it will replaceState with callback newUrl.
For `keycloack.login()`, it won't.
https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-js/src/keycloak.js#L246-L250

### Version

20.0.3

### Expected behavior

`keycloak.login()` should replaceState with callback url as well.
The redirect login should be success.

### Actual behavior

`keycloak.login()` won't replaceState with callback url as well.
The redirect login is failed without refresh.

### How to Reproduce?

Call `keycloak.init({onLoad: 'login-required'})` and `keycloack.login()` to see the difference.

**Comment by SetoKaiba** [comment]
Discussion here.
https://github.com/keycloak/keycloak/discussions/17599

**Comment by SetoKaiba** [comment]
Hi. Can anyone review the PR?

**Comment by jonkoops** [comment]
Closing this for the reasons mentioned in https://github.com/keycloak/keycloak/pull/17601#issuecomment-1497402593.
