### ISSUE TITLE
Port in frontendUrl ignored in OIDC .well-known

### ISSUE THREAD

**Issue by moongladestorm** [keycloak/keycloak#17608]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

I am running keycloak in a docker compose setup behind traefik as reverse proxy with a public available URL. Additionally I want to have the admin interface reachable on localhost only, which is done in traefik with a seperate entrypoint on localhost:7081. Also the login to the master realm should only happen on localhost. Therefore the following configuration options are set:

KC_HOSTNAME: something.tld
KC_HOSTNAME_ADMIN_URL: https://localhost:7081/keycloak/
KC_HOSTNAME_PATH: /keycloak
KC_HTTP_RELATIVE_PATH: /keycloak
KC_PROXY: edge

With this, keycloak is reachable publicly and the admin interface only on localhost, but the login to the admin frontend (via the master realm) still goes over the public url. I expected to be able to change this by setting the frontendUrl in the master realm to the admin url also:

frontendUrl = https://localhost:7081/keycloak

Unfortunately this redirects in the login process always to https://localhost/keycloak without the port specified. Also the port is missing in the generated .well-known/openid-configuration.

### Version

21.0

### Expected behavior

frontend urls in /realms/master/.well-known/openid-configuration contain port set via frontendUrl realm parameter, e.g. for authorziation_endpoint:

"authorization_endpoint":"https://localhost:7081/keycloak/realms/master/protocol/openid-connect/auth"

### Actual behavior

port is missing, e.g.:

"authorization_endpoint":"https://localhost/keycloak/realms/master/protocol/openid-connect/auth"

### How to Reproduce?

Keycloak setup with docker-compose:

~~~
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: something.tld
      KC_HOSTNAME_ADMIN_URL: https://localhost:7081/keycloak/
      KC_HOSTNAME_PATH: /keycloak
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
~~~
Set frontend URL for master realm (either in the admin frontend or via cli in the docker container of the frontend is not working):
`kcadm.sh update realms/master --server http://localhost:8080/keycloak --realm master --user admin --password '${KEYCLOAK_ADMIN_PASSWORD}' -s attributes.frontendUrl="https://localhost:7081/keylcoak"`

Fetch well-known: https://localhost:7081/realms/master/.well-known/openid-configuration

### Anything else?

This bug might be triggered here (special case hostname set and proxy enabled):

https://github.com/keycloak/keycloak/blob/340025b412d7d14673d55932b87506bc468fabfd/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L120

**Comment by lexcao** [comment]
Hi @moongladestorm 
What is your proxy server `traefik` setting for the `x-forwarded-` header?

Have you setup this up?
```
x-forwarded-proto: https
x-forwarded-port: 7081
```

**Comment by moongladestorm** [comment]
Hi @lexcao ,

traefik is adding those headers automatically per default (see https://doc.traefik.io/traefik/getting-started/faq/#what-are-the-forwarded-headers-when-proxying-http-requests).

Here is the traefik configuration I am using:

traefik/keycloak.yml
~~~
http:
  routers:
    keycloak:
      entryPoints:
        - web
      rule: "PathPrefix(`/keycloak/`)"
      service: keycloak
    keycloak_admin:
      entryPoints:
        - admin
      rule: "PathPrefix(`/keycloak/`)"
      service: keycloak

  services:
    keycloak:
      loadBalancer:
        servers:
          - url: http://keycloak:8080/
~~~

docker-compose.yml
~~~
  traefik:
    image: traefik:v2.9
    command:
      - --providers.file.directory=/config
      - --entryPoints.admin.address=:7081
      - --entryPoints.admin.http.tls=true
      - --entryPoints.web.address=:7082
      - --entryPoints.web.http.tls=true
    volumes:
      - ./traefik:/config
    ports:
      # "admin" entrypoint available on port 7081
      - "7081:7081"
      # default web entrypoint available on port 443
      - "443:7082"
~~~

**Comment by mposolda** [comment]
Adding to Backlog as Keycloak likely won't have capacity to improve this before Keycloak 22 (and it is not clear if this can be classified as Keycloak bug, or is rather an issue in the setup/environment).

**Comment by cdavernas** [comment]
I'm facing the same issue with a solution running on Docker-Compose.

My protected app is retrieving metadata using the Docker DNS for keycloak, at: `http://keycloak:8080`. When trying to access a protected resource using the implicit flow, it would redirect me to that address, which is obviously not available from outside. I therefore set the `KEYCLOAK_HOSTNAME` to `keycloak.localhost` (served by Traefik). Now my user gets redirected to `https://keycloak.localhost:8080`. Setting `KEYCLOAK_FRONTEND_URL` does not address that issue, nor do any of my other attempts.

Anyone has any clue on how to proceed, without having to change the ports on which keycloak listens? As far as I understand it, it's just a matter of metadata configuration.
