### ISSUE TITLE
KeyCloak on Azure to PostgreSQL "Certificates do not conform to algorithm constraints"

### ISSUE THREAD

**Issue by Zumpel96** [keycloak/keycloak#17606]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I am running KeyCloak in an Azure App Service (Docker Container) with the following image "quay.io/keycloak/keycloak:21.0.1" - just, as it is stated in the [documentation][1]

My environment variables look like this:
![image](https://user-images.githubusercontent.com/17179371/224627454-f2225ad0-4744-43ee-9fae-8e1d491080d3.png)

Everything works fine. I can access KeyCloak with my custom domain and the login to the admin console works too. BUT! One thing does not work: The database.

I am using a PostgreSQL database, which is hosted on Azure as well. I can connect to it with the same credentials as I have entered in the environment variables, with the help of DBeaver (that's where I copied the DB URL from btw).

The logs state the following:
```
2023-03-10T13:54:44.250741391Z 2023-03-10 13:54:44,192 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2023-03-10T13:54:44.253996869Z 2023-03-10 13:54:44,192 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: SSL error: Certificates do not conform to algorithm constraints
2023-03-10T13:54:44.254005969Z 2023-03-10 13:54:44,192 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
2023-03-10T13:54:44.254020670Z 2023-03-10 13:54:44,193 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
2023-03-10T13:54:44.254027270Z 2023-03-10 13:54:44,194 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Algorithm constraints check failed on signature algorithm: SHA1withRSA
``` 

Just to clarify it: Just to make sure, that the Web App can access the DB I opened it fully (0.0.0.0 - 255.255.255.255). Also, I manually added the "keycloak" schema (which should be the default according to the docs).

  [1]: https://www.keycloak.org/getting-started/getting-started-docker

### Version

21.0.1

### Expected behavior

Server starts successfully

### Actual behavior

Server does not start and throws the above mentioned error messages.

### How to Reproduce?

Create a new Azure App Service and a Azure PostgreSQL database. Set the shown environment variables and start the Web App. Additionally, create the "keycloak" schema manually on the DB.

**Comment by brecht-vermeersch** [comment]
https://github.com/keycloak/keycloak/issues/17320

**Comment by vishnuprakash92** [comment]
> For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`

I couldnt get this working by using the below command to dockerfile
ADD certs/DigiCertGlobalRootCA.crt.pem /opt/keycloak/.postgresql/root.crt

**Comment by mxdrenthe** [comment]
> > For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`
> 
> I couldnt get this working by using the below command to dockerfile ADD certs/DigiCertGlobalRootCA.crt.pem /opt/keycloak/.postgresql/root.crt

What kind of error do you get?

**Comment by vishnuprakash92** [comment]
> > > For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`
> > 
> > 
> > I couldnt get this working by using the below command to dockerfile ADD certs/DigiCertGlobalRootCA.crt.pem /opt/keycloak/.postgresql/root.crt
> 
> What kind of error do you get?

Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA

**Comment by mxdrenthe** [comment]
> > > > For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`
> > > 
> > > 
> > > I couldnt get this working by using the below command to dockerfile ADD certs/DigiCertGlobalRootCA.crt.pem /opt/keycloak/.postgresql/root.crt
> > 
> > 
> > What kind of error do you get?
> 
> Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA

I would guess your PEM file now has windows line endings messing up the Algorithm

**Comment by ingokuba** [comment]
> For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`

Thank you very much. :pray:  For anyone who would like to see a working Dockerfile:
```
FROM alpine/curl:8.1.2 as digicert

WORKDIR /app
RUN curl https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem -o DigiCertGlobalRootCA.crt.pem

FROM quay.io/keycloak/keycloak:21.1
COPY --from=digicert /app/DigiCertGlobalRootCA.crt.pem /opt/keycloak/.postgresql/root.crt
...
```

**Comment by MattiasAng** [comment]
For others using the Keycloak Operator or running on Kubernetes in general, we used the following workaround for using Azure MySQL Flexible Server as backend. The same should work for PostgreSQL.

Create a ConfigMap with `java.config` copied from the `keycloak:22.2` image at `/etc/crypto-policies/back-ends/java.config` with the only modification being removing `MD1` from `jdk.certpath.disabledAlgorithms`.

Note that it is important to check for changes in this file in future image version if you use this workaround.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-java-config
data:
  java.config: |
    jdk.certpath.disabledAlgorithms=MD2, MD5, DSA, RSA keySize < 2048
    jdk.tls.disabledAlgorithms=DH keySize < 2048, TLSv1.1, TLSv1, SSLv3, SSLv2, DHE_DSS, RSA_EXPORT, DHE_DSS_EXPORT, DHE_RSA_EXPORT, DH_DSS_EXPORT, DH_RSA_EXPORT, DH_anon, ECDH_anon, DH_RSA, DH_DSS, ECDH, 3DES_EDE_CBC, DES_CBC, RC4_40, RC4_128, DES40_CBC, RC2, HmacMD5
    jdk.tls.legacyAlgorithms=
```

And then mount it to the same location, snippet:
```yaml
- volumeMounts:
    - name: keycloak-java-config
      mountPath: /etc/crypto-policies/back-ends/java.config
      subPath: java.config
volumes:
  - name: keycloak-java-config
     configMap:
       name: keycloak-java-config

```

**Comment by Bharath00** [comment]
> For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`

I'm facing the same issue but with Azure mysql and have downloaded the crt for the same but not sure if there is a path called .mysql ?

`services:
  Keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    working_dir: /opt/keycloak
    command:
      - start
    restart: unless-stopped
    ports:
      - 8080:8443
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=xxx
      - KC_DB_USERNAME=myadmin
      - KC_DB_PASSWORD=Mysql
      - KC_DB=mysql
      - KC_DB_URL_HOST=xxx.mysql.database.azure.com
      - KC_DB_URL_PORT=3306
      - KC_DB_URL=jdbc:mysql://xxx.mysql.database.azure.com/keycloak?sslmode=verify-full
      - KC_PROXY=edge
      - KC_HTTPS_CERTIFICATE_FILE=cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=privkey.pem
      - KC_TRANSACTION_XA_ENABLED=false
      - KC_HOSTNAME_URL=https://xxx.eastus.cloudapp.azure.com
      - KC_HOSTNAME_ADMIN_URL=https://xxx.eastus.cloudapp.azure.com
    volumes:
      - ./themes:/opt/keycloak/providers
      - ./DigiCertGlobalRootCA.crt.pem:/opt/keycloak/.mysql/root.crt`

**Comment by mxdrenthe** [comment]
> /> For those who try to solve this one without tempering with security.config to get this working for Azure Flexible PostgresSQL server. By adding the certificate from: https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-connect-tls-ssl Into `/opt/keycloak/.postgresql/root.crt` and setting `KC_DB_URL_PROPERTIES="?sslmode=verify-full"`
> 
> I'm facing the same issue but with Azure mysql and have downloaded the crt for the same but not sure if there is a path called .mysql ?

Try looking at the JDBC driver itself: https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode (and the option after it)

**Comment by Erikvv** [comment]
Has anyone tried to get contact with Azure to get them to update their CA certificate? (I don't have a support tier)

**Comment by propyless** [comment]
> For others using the Keycloak Operator or running on Kubernetes, we used the following workaround for using Azure MySQL Flexible Server as backend. The same should work for PostgreSQL as they use the same root certificate. This workaround doesn't require building your own image.
> 
> Create a ConfigMap with `java.config` copied from the `keycloak:22.2` image at `/etc/crypto-policies/back-ends/java.config` with the only modification being removing `MD1` from `jdk.certpath.disabledAlgorithms`.
> 
> Note that it is important to check for changes in this file in future image version if you use this workaround.
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: keycloak-java-config
> data:
>   java.config: |
>     jdk.certpath.disabledAlgorithms=MD2, MD5, DSA, RSA keySize < 2048
>     jdk.tls.disabledAlgorithms=DH keySize < 2048, TLSv1.1, TLSv1, SSLv3, SSLv2, DHE_DSS, RSA_EXPORT, DHE_DSS_EXPORT, DHE_RSA_EXPORT, DH_DSS_EXPORT, DH_RSA_EXPORT, DH_anon, ECDH_anon, DH_RSA, DH_DSS, ECDH, 3DES_EDE_CBC, DES_CBC, RC4_40, RC4_128, DES40_CBC, RC2, HmacMD5
>     jdk.tls.legacyAlgorithms=
> ```
> 
> And then mount it to the same location, snippet:
> 
> ```yaml
> - volumeMounts:
>     - name: keycloak-java-config
>       mountPath: /etc/crypto-policies/back-ends/java.config
>       subPath: java.config
> volumes:
>   - name: keycloak-java-config
>      configMap:
>        name: keycloak-java-config
> ```

Out of curiousity, are you still using this workaround or have you found a better way today?
