### ISSUE TITLE
Document the criterion when heap and when filestore should be used for storing Infinispan data

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#17615]
During performance testing, we need to test heap consumption in the Infinispan as by default we store both indexes and cached data in the heap. The output should be some input for documentation. For example, if you plan to have more than a million user sessions in the HotRod store consider switching storage from memory to the filesystem.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
