### ISSUE TITLE
Changes in configuration of authenticator in cloned authentication auth flow also affect original flow

### ISSUE THREAD

**Issue by CorneliaLahnsteiner** [keycloak/keycloak#17618]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Changes in the configuration of authenticators in cloned authentication flows also affect the original flow.

When using Keycloak in production, it is advisable to use a "template" flow that is adapted to changes. Once these changes are complete, create a new version of the flow, which is then bound as a new authentication flow to take effect. This has the advantage that changes in the authentication flow do not take effect immediately, but only when all changes have been made and you want to make them active.

Because of this bug, changes to the template flow take effect immediately, as the cloned flow (the active and bound flow) is also changed.

### Version

21.0.1

### Expected behavior

Changes to the configuration of an authenticator should not affect cloned authentication flows.

### Actual behavior

Changes to the configuration of an authenticator affect cloned authentication flows.

### How to Reproduce?

1. Build an authentication flow (Flow A) with an authenticator, which can be configured (e.g. Condition - user attribute config)
2. Set a configuration for the authenticator and save it
3. Clone the authentication flow (Flow B)
4. Change the configuration of the authenticator in the cloned flow (Flow B)
5. Swap back to the original flow (Flow A) and view the configuration of the authenticator

The change has also taken affect in the original flow (Flow A) although the change was made in the cloned flow (Flow B).

**Comment by mposolda** [comment]
duplicates #12012

@CorneliaLahnsteiner Thanks for the report. But I am closing this as duplicate as this issue already exists and is planned for Keycloak 22. Please use the other issue for further questions/concerns/discussions related to this.
