### ISSUE TITLE
/users/count endpoint with search field has different behavior than /users query endpoint

### ISSUE THREAD

**Issue by 99graciamanel** [keycloak/keycloak#17620]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

/users/count endpoint with search field has different behavior than /users query endpoint because of the JpaUserProvider implementation.

In the method 

`searchForUserStream(RealmModel realm, Map<String, String> attributes, Integer firstResult, Integer maxResults)`

the search key/value attribute is trimmed to treat spaces as different search predicates:

```
                case UserModel.SEARCH:
                    for (String stringToSearch : value.trim().split("\\s+")) {
                        predicates.add(builder.or(getSearchOptionPredicateArray(stringToSearch, builder, root)));
                    }
                    break;
```

In the methods

`getUsersCount(RealmModel realm, String search, Set<String> groupIds)`

and

`getUsersCount(RealmModel realm, String search)`

the search attribute is used as a unique predicate:

```
                predicates.add(builder.or(getSearchOptionPredicateArray(search, builder, root)));
```

### Version

>18.0.0

### Expected behavior

Having the user with representation:

```
    {
        "username": "john.doe",
        "firstName": "John",
        "lastName": "Doe Smith",
        "email": "john.doe@keycloak.org",
    }
```

calling the endpoint: 

`/users/count?search=jo do` 

I expect result to be 1.

### Actual behavior

Result is 0

### How to Reproduce?

Call the endpoint:

```
curl --location --request GET 'https://{mydomain}/auth/admin/realms/{myrealm}/users/?search=jo do' \
--header 'Authorization: Bearer Token'
```

and 

```
curl --location --request GET 'https://{mydomain}/auth/admin/realms/{myrealm}/users/count?search=jo do' \
--header 'Authorization: Bearer Token'
```

**Comment by pedro-hos** [comment]
Same behavior was on 21.0.1.
