### ISSUE TITLE
Username enumeration in the Username Form for the Password-less browser login flow

### ISSUE THREAD

**Issue by infl00p** [keycloak/keycloak#17629]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

When configuring a password-less browser login flow as described in Keycloak's administrator docs, the Username Form is vulnerable against username enumeration.

The default browser flow uses the UsernamePassword Form which does not differentiate against wrong username or wrong password, thus it's protected against enumeration attacks.

### Version

21.0.1

### Expected behavior

The expected behavior is not to respond to an invalid username error when entering a non-existing one and forward the username validation to the next execution/flow.

### Actual behavior

When entering a non-existing username an error is displayed "Invalid username or email." or "Invalid username." depending on the "login with e-mail" realm setting.
![kc21_passwordless_invalid](https://user-images.githubusercontent.com/1328604/224773591-7528bf19-a900-4df6-9413-3f74b81dc949.png)

When entering a valid username the next step is displayed depending on the user authentication settings.

### How to Reproduce?

Create a password-less flow as described in the Administration Documentation at: https://www.keycloak.org/docs/latest/server_admin/index.html#creating-a-password-less-browser-login-flow

![kc21_passwordless](https://user-images.githubusercontent.com/1328604/224773882-068def5e-b064-4336-b195-296ed4c6aedd.png)
Bind it to a client e.g account-console.
Then login with an non-existing user.
When login in with an existing user then the next step is displayed.

### Anything else?

From previous reported issues it is apparent that the keycloak team has added additional logic against username enumeration e.g see issue https://github.com/keycloak/keycloak/issues/11916

A workaround could be to use custom username form and password form providers overriding the authentication process, e.g by changing the validateUser method.
Another workaround is to detect brute-force by using an external tool like fail2ban, but I'm using kubernetes and there is no such mechanism there.

**Comment by mposolda** [comment]
Adding to Backlog. Keycloak team won't have time to look at this in the near future.

Avoiding user enumeration can be nice, but it can be quite complex if we want to do it properly for all various scenarios.

Community contribution is welcome to look at it and eventually fix it. On the other hand, I afraid that attempt to fix it as described can lead to various other issues. IF we do what is proposed in the description, we may need to allow `UsernameForm` to continue even if user is not found. This means that UserModel won't be set in the authentication context and I afraid of various other bugs related to corner case scenarios related to it (especially NPE thrown during various scenarios if we do this). In other words, fixing this properly may not be trivial thing to do.

**Comment by stianst** [comment]
Avoiding username enumeration with a identity first login flow like this is not easy to do. Similarly to enabling user registration you can not avoid anyone from using that to enumerate existing usernames.

This would require setting up a WAF or similar in front of Keycloak that can detect attempts like this by looking across multiple request to identify malicious activity.
