### ISSUE TITLE
Exposing Keycloak over multiple Frontend URLs

### ISSUE THREAD

**Issue by albundy83** [keycloak/keycloak#17634]
### Description

Problem Statement
 
Keycloak introduced concept of frontendUrl to enable different URLs for front-channel and back-channel requests towards Keycloak. Though frontendUrl can be configured per realm, but there is an inherent assumption that a single realm in Keycloak will always be exposed via a single frontendUrl, which may not be correct.
 
Scenario
 
Scenario that we have is we install Keylcloak as a microservice in a Kubernetes cluster. There is a cluster internal service name (say, internal.company.com) and other services communicate with Keycloak via this internal URL.
Apart from that, we have browser based web applications which access Keycloak over different Ingresses with different FQDNs (say, domain1.company.com and domain2.company.com) . Assume these domains are hosted in separated VPNs which are not accessible to each other.
We also have other microservices which expose business APIs to the browser based applications. These microservices use Keycloak spring-boot client adapter and configured as a "bearer-only" client. Browser based applications send access tokens to these microservices, which verify the tokens in client adapter.
 
 
First problem: We can set only one Frontend URL per realm. For example, let's say we set it to domain1.company.com. Now when browser based clients access Keycloak via domain2.company.com , all responses from Keycloak service (like login page submit action) contains frontendUrl (domain1.company.com) and they are not accessible because of different VPNs.
 
Second problem: If we don't set the frontendUrl, then we land into another problem that Issuer verification fails, when tokens sent by the browser based applications to the backend microservices. 
 
Expectation/Feature Request
 
It should be possible to decouple Issuer URL from Keycloak's frontendUrl and provide a possibility to set an issuer separately per realm. When that happens, Keycloak will also get decoupled from network architecture and can be exposed over multiple FQDNs.

### Motivation

Fix the following issue: https://issues.redhat.com/browse/KEYCLOAK-15553
And ticket: https://issues.redhat.com/plugins/servlet/mobile#issue/KEYCLOAK-6984

**Comment by vanakema** [comment]
My situation is very similar to yours. Another scenario is wanting to do live code reloads on our backend and frontend apps, which we achieve by port-forwarding the keycloak container, but this causes issues with ISS validation. Curious to hear solutions anyone has found

**Comment by ibcht** [comment]
Similar situation on my side. Third party application and Keycloak are called on different contexts, with different hostnames (e.g. context 1 : domain1.com/auth for KC and domain1.com/app for the application, context 2 : domain2.com/auth for KC and domain2.com/app for the app). If I manage to let KC work with a dynamic URL by disabling strict hostname verification, then the issuer validation fails on the application as I can only register one issuer value.

I've seen some workarounds based on tweaked reverse-proxy configuration, but this seems quite dirty to me, as it involves a custom site configuration for each hostname.

The fact that the issuer is tighly linked to the way the frontend URL is accessed seems a shortcut to me, even though in most cases it works well.

**Comment by justmike1** [comment]
Same here,
I am also commenting to increase the exposure in hopes that it will catch the attention of Keycloak's team and be addressed.

**Comment by flopydisk** [comment]
+1,
Would like this solved

**Comment by sschu** [comment]
One benefit of the current setup is that from the issuer you can deduct the well-known endpoint from where you get the key endpoint from where you get the keys to validate the token. How would you solve that in the future?

**Comment by Shaeto** [comment]
also want to see solution, use keycloak behind proxy with multiple domains

**Comment by vmuzikar** [comment]
This is actually related to https://github.com/keycloak/keycloak/issues/24252#issuecomment-1822718150

**Comment by hughesadam87** [comment]
Here is another situation:

1. Running a docker-compose application on my laptop.  
2. Keycloak is a service inside the docker network.
3. Accessing from my laptop's browser (so localhost)

This means the issuer for keycloack becomes `http://locahost:8080` but when my application goes to exchange the authorization code for the exchange token, it has to reach out to `http://keycloak:8080`.  The underlying oauth client library (passport) sees that the code's `iss` field is 'localhost' and interrupts the exchange.  

Having an easy way to override the `iss` would be great.  Just make it a dev feature or a "WE DONT RECOMMEND DOING THIS" type thing.

![image](https://github.com/keycloak/keycloak/assets/1972276/576a2d5a-8e03-458c-b716-600b854674fa)

**Comment by cmiles74** [comment]
I think @hughesadam87 has another good example where hard-coding the "iss" attribute in the token causes problems.

Do we know what the rationale is behind preventing people from changing this value? 

For my part, I need to change it to work with Epic's EHR. They require a specific "iss" attribute value (it's different for each client). I've asked them to change and they have made it clear that they think their requirement is both reasonable and _a security requirement._ Truly an impasse. 😢

**Comment by hughesadam87** [comment]
> @hughesadam87 #27660 may be applicable to your situation as well - with the new hostname options if you allow a dynamic backchannel, the issuer for the token will become the frontend url, which will be required:
> 
> https://github.com/keycloak/keycloak/blob/65bdf1a60474aef735c8fd7dda3fc53185758a76/docs/guides/server/hostname.adoc?plain=1#L139

Thanks - I've read this and don't fully comprehend it.  But let's say I change my frontend URL to what the issuer should be.

    http://keycloak:8080

Then I can no longer open the keycloak UI in my browser, as ^^^ is only resolvable within the docker network.

**Comment by shawkins** [comment]
> Then I can no longer open the keycloak UI in my browser, as ^^^ is only resolvable within the docker network. 

Yes the assumption is the frontend is public. 

> Also when I try to sign in from my application's SSO, at some point my browser tries to access this URL and fails

Let me try to map things to the new hostname options:

With just:
hostname-strict=false

- If you attempt to create a token via one backchannel and use it via a different frontend, it will fail to validate. 

With:
hostname=https://keycloak/
hostname-backchannel-dynamic=true

- works as long as the hostname is public

If I'm following correctly you are looking for a mode like hostname-strict=false, but where tokens are issued with an understanding of the intended frontchannel, is that correct?

**Comment by hughesadam87** [comment]
> With: hostname=https://keycloak/ hostname-backchannel-dynamic=true
> 
> * works as long as the hostname is public
> 
> If I'm following correctly you are looking for a mode like hostname-strict=false, but where tokens are issued with an understanding of the intended frontchannel, is that correct?

I appreciate your trying to help - but in truth I have no idea what any of these terms mean honestly (hostname-strict, frontchannel).  

At some point I may followup with a minimal example, but am probably going to shelf it for now.  TLDR; is I'm running a basic web app with Oauth2 standard flow and I want to be able to run the entire stack on docker on my laptop.  Is there a complete hello-world working example of this floating around somewhere?

**Comment by shawkins** [comment]
> Is there a complete hello-world working example of this floating around somewhere?

There's several getting started guides, including https://www.keycloak.org/getting-started/getting-started-docker

What you are bringing into the picture here is the keycloak hostname, which is private to the docker network.

I think it could work on a single machine as you alluded to by adding a DNS entry for the keycloak hostname and starting with "--hostname=keycloak --hostname-strict-backchannel=true". However if you cannot add the DNS entry, then you are indeed stuck. Could you run instead with everything as localhost?

**Comment by hughesadam87** [comment]
@shawkins yes we can run everything as localhost.  To be honest, the use case of running keycloak with docker-compose on a single laptop and not be able to setup DNS is kind of contrived.  In reality, we'd deploy on prod servers without such a constraint, so this was mostly just for demo/exercise purposes.  So I am fine leaving it here.  Thanks for you help; I learned a lot.
