### ISSUE TITLE
User not found in Create Policy (Authorization) Page

### ISSUE THREAD

**Issue by harpreetsingh29** [keycloak/keycloak#17640]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Our team is facing issue in admin console of Keycloak 19.0.3. (We are already using Wildfly one and this is last version having Wildfly as base.)

1. Search "Test8" in Users Page and it is working fine. 
<img width="530" alt="users" src="https://user-images.githubusercontent.com/28382120/224908240-15f2db12-c514-4b29-8088-6ff8ce73e96f.png">
2. When we go to Client -> Click on Client -> Authorization -> Policy
And When we click on CREATE POLICY and select type: "test8"
<img width="443" alt="policy" src="https://user-images.githubusercontent.com/28382120/224908280-8c3f248b-a513-4473-a889-2572755ccb56.png">

Then nothing appears, default list (initial 20 records) comes as output. If we have 20,000 users then we are not able to search all but initial 20.

Any suggestions to fix this issue. Any new UI and version we can use?Anything we can do in existing setup?

**Additional Info**:
We tried to debug using postman and found that when URL has "username or search" as query string then we get output for "test8" but Admin Console UI is currently using "name" in query string.
<img width="482" alt="postman" src="https://user-images.githubusercontent.com/28382120/224908382-e5c782be-db0d-4b9f-96b7-e17f6a5ad3d4.png">

### Version

19.0.3

### Expected behavior

It should search the user in Create Policy Page.

### Actual behavior

Not able to search user. Only first 20 user are getting displayed.  

### How to Reproduce?

Our team is facing issue in admin console of Keycloak 19.0.3. (We are already using Wildfly one and this is last version having Wildfly as base.)

1. Search "Test8" in Users Page and it is working fine. 
<img width="530" alt="users" src="https://user-images.githubusercontent.com/28382120/224908240-15f2db12-c514-4b29-8088-6ff8ce73e96f.png">
2. When we go to Client -> Click on Client -> Authorization -> Policy
And When we click on CREATE POLICY and select type: "test8"
<img width="443" alt="policy" src="https://user-images.githubusercontent.com/28382120/224908280-8c3f248b-a513-4473-a889-2572755ccb56.png">

Then nothing appears, default list (initial 20 records) comes as output. If we have 20,000 users then we are not able to search all but initial 20.

Any suggestions to fix this issue. Any new UI and version we can use?Anything we can do in existing setup?

**Additional Info**:
We tried to debug using postman and found that when URL has "username or search" as query string then we get output for "test8" but Admin Console UI is currently using "name" in query string.
<img width="482" alt="postman" src="https://user-images.githubusercontent.com/28382120/224908382-e5c782be-db0d-4b9f-96b7-e17f6a5ad3d4.png">

### Anything else?

https://groups.google.com/g/keycloak-user/c/Zccj5tUpHjY

**Comment by ssilvert** [comment]
The latest nightly version has better behavior.  With each keystroke, it will search for the first 20 users that meet the search criteria.  So you won't just get the first 20 users.  You will only get matches.

You can try the nightly build at https://github.com/keycloak/keycloak/releases/tag/nightly

Please let me know if this solves your problem.
