### ISSUE TITLE
Add no-downtime upgrade step for the new admin console theme for the new store

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#17641]
There is [the following migration step](https://github.com/keycloak/keycloak/blob/d69c580850bb3338e6411645b1180363db4cb1fc/model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo21_0_0.java) in the legacy store. We should introduce the same also for the new store.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
