### ISSUE TITLE
Disabled user profile field editable in PersonalInfo page

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#17652]
### Describe the bug

When declaring user profile fields not editable for a user, the respective user profile fields are still shown as editable text fields. When a user tries to change the value and click save, then an error message is shown.

### Version

21.0.1

### Expected behavior

Read-only user profile fields should be disabled

### Actual behavior

Read-only user profile html input fields should be disabled (or marked as readonly).

### How to Reproduce?

1) Start Keycloak with user profile enabled (--features=preview), e.g.:
```
docker run --rm -it \
    -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    quay.io/keycloak/keycloak:nightly start-dev \
   --http-enabled=true \
   --http-relative-path=auth --features=preview
```
2) Create a new realm profile-test
3) enable user profile support for that realm
4) edit the default user profile and make firstname read-only for user
![image](https://user-images.githubusercontent.com/314690/225012185-afa74816-b43a-465a-b07c-db211a4b9855.png)

4) create a test user with passord
5) access the account page with the test user
6) look at the personal info page -> the firstname field should be disabled (or readonly).
![image](https://user-images.githubusercontent.com/314690/225012938-0935d0d0-851f-415f-93e6-91087d3efc82.png)

### Anything else?

Personally, I'd prefer using `readonly instead of `disabled` because it retains focus. However, the email field uses `disable`by default. Perhaps this needs to be aligned a bit.

**Comment by ssilvert** [comment]
User profile features are not implemented yet for account console.  But it should be coming soon.  I'll leave this open for now.

**Comment by edewit** [comment]
it's in the v3 of the account console that you can start with a feature flag: `./bin/kc.sh start-dev --features=account3`
