### ISSUE TITLE
In Keycloak 19.0.3, Refresh token got rejected with Invalid_grant and Offline user session not found

### ISSUE THREAD

**Issue by VigneshKannaM** [keycloak/keycloak#17666]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

identity-brokering

### Describe the bug

As i am using Keycloak 19.0.3 version as identity broker,

Refresh token got rejected with "Invalid_grant and Offline user session not found", even within the time out limit configured in the Realm's tokens configuration,

Let's say I have configured timeout for refresh token as 2 days in the ( SSO Session Idle , SSO Session Max Offline Session Idle). 
**But refresh token expires before 2 days.**, 

Note: 

- There are **no manual signing out of session** by the user and the single user session have kept idle for 2 days in browser.
- Here I am using  keycloak as  identity broker also, the keycloak is not in cluster deployment, 

Please clarify below points and also give a possible fix or solution for the above issue.

1. In case of Identity broker + Identity Provider setup, user session will be maintained by whom broker or Provider?
2. Access / refresh token's will be generated by identity broker or by Identity Provider ?
3. Do we need to sync the time out configurations between identity broker and Identity Provider ?
4. Is there any possibility of caching system in Keycloak causing the above issue?

### Version

19.0.3

### Expected behavior

Refresh token should not get invalidated before timeout limit.
Unless user manually signing out 

### Actual behavior

Refresh token is getting invalidated before timeout limit and even without manual account signing out.

### How to Reproduce?

Have a keycloak as identity broker and use it as the Identity broker, connect with IDP with openIdConnect protocol settings.

Keep refresh token time out limit max as 2+ days in keycloak as identity broker's token settings and keep access token expiry as short as 15 mins.

Ask user to keep login in to the session for a while, Application which is using above keycloak broker shall try to get new access token with the refresh token taken and keep on using the same still it got expired.

In between while application is using the refresh token to get new access token (with grand type as refresh_token), and refresh token is getting invalidated before 2 days and keycloak is throwing "Invalid_grant and Offline user session not found".

Note:
- There are **no manual signing out of session** by the user and the single user session have kept idle for 2 days in browser.
- Here I am using  keycloak as  identity broker and not in cluster deployment

**Comment by PhungVanHoa** [comment]
I also have this problem

**Comment by mposolda** [comment]
@VigneshKannaM When you mentioned error `Invalid_grant and Offline user session not found`, does this error occurs when you're trying to refresh-token from your application to Keycloak? As in your report, you mentioned "Identity Provider", but I don't know if this error has any relation to Identity brokering. Can you reproduce this when user is logged to Keycloak by some non-IDP way (for example by standard username/password login)?

**Comment by mposolda** [comment]
Moving to Backlog as we're likely not able to improve something on this for Keycloak 22 (and not really sure if this is KEycloak bug or rather some mis-configuration).

**Comment by VigneshKannaM** [comment]
Hi @mposolda, 

The same issue is not observed on usual way (standard username/password login). 

As in my case, 
I have multiple realms in the keycloak, one of the realm acting as Identity brokering and all other realms are in usual way Issue has been observed only in the realm which has Identity broker setup.

Thanks,
Vignesh Kanna Mohan

**Comment by sschu** [comment]
Does this still happen in the newest KC version? There were some changes around lazy-loading of offline sessions.

**Comment by VigneshKannaM** [comment]
Hi @sschu , 
I have tested with 19.0.3
do you mean 21.1.0 having fix for this?

**Comment by sschu** [comment]
@VigneshKannaM Issues will only be fixed for the latest version, so you should make sure a problem exists in the latest version anyways...
