### ISSUE TITLE
Navigating between routable tabs shows page loader

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#17672]
### Describe the bug

When navigating between routable tabs such as the ones introduced in keycloak/keycloak-ui#1862 causes a page loader to appear. This is due to the fact that some of these tabs are on different routes, which means that the original component gets unmounted and then remounted.

Ideally the routable tabs would ensure that the original route stays mounted, a solution will have to be made for this.

**Comment by ssilvert** [comment]
Haven't seen this in awhile.  Might be fixed by new React router.  Closing.
