### ISSUE TITLE
[UX Review] Optimize the details/creation page of Authorization resource

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#17673]
### Describe the bug

There is some fine-tuning of the Resource details/creation page in the Authorization as shown below.

<img width="1071" alt="Screen Shot 2022-02-09 at 4 17 21 PM" src="https://user-images.githubusercontent.com/53931519/153155622-23be1bf7-3487-4979-b4da-3d817fe1c43b.png">

**1. The type should be a dropdown that allows users to select an existing type or create a new type here.**

<img width="935" alt="Screen Shot 2022-02-09 at 4 19 13 PM" src="https://user-images.githubusercontent.com/53931519/153155463-f456cc14-28e1-4359-9f2f-11a8ffcafd8a.png">

**2. Users have to set both the Keys and value for a pair of attributes. Otherwise, the "Add an attribute" link button should be disabled and users can't save the form.**

**3. After clicking the Save button on the details page, it should be returned to the resource table instead of the Setting page. The same thing happens to the Cancel button**

### Version

New admin UI

**Comment by edewit** [comment]
this has now been fixed
