### ISSUE TITLE
Invalid Frontend URL leads to NullPointerException in OIDC Endpoints

### ISSUE THREAD

**Issue by SoylentBob** [keycloak/keycloak#17686]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

When configuring the "Frontend URL" parameter under `/admin/master/console/#/my-realm/realm-settings` missing the Scheme of the URL leads to a `NullPointerException`, which is hard to pinpoint to an actual cause without looking into the code.

This leads to internal server errors, when requesting resources such as "/realms/my-realm/.well-known/openid-configuration" and also causes errors when authenticating through the realm.

The reason lies in the schema check made by the `RealmsResource`:

https://github.com/keycloak/keycloak/blob/ce1e0a65e7ffdcb3b484aebcadd0456e65cba2fa/services/src/main/java/org/keycloak/services/resources/RealmsResource.java#L275

This line does not place the literal "https" first in the comparison, which then leads to the observed `NullPointerException`.

As the application uses a `java.net.URI` internally the missing schema goes unnoticed and `new URI("example.com").getScheme()` returns `null`.

### Version

20.0.5

### Expected behavior

When I enter "example.com" into the "Frontend URL" field, then the validation of the field should prohibit saving the changes to the realm, because "example.com" is not a valid URL.

When I somehow have already entered an invalid "Frontend URL", then requesting the resources should not fail with a `NullPointerException`.

### Actual behavior

When I enter "example.com" into the "Frontend URL" field, then my mistake is processed without any notice.

When I somehow have already entered an invalid "Frontend URL", then requesting resources, such as "/realms/my-realm/.well-known/openid-configuration" fail with a `500 - Internal server error`.

### How to Reproduce?

1. Select the realm (e.g. "my-realm")
2. Select "Realm Settings"
3. Enter "example.com" into the "Frontend URL" parameter
4. Click the "Save" Button
5. Open "/realms/my-realm/.well-known/openid-configuration"

### Anything else?

This could have been prevented by using static code analysis tools. E.g. https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#literalsfirstincomparisons

Thanks for all the hard work.

**Comment by rmartinc** [comment]
@SoylentBob Yeah, you are right. I think that the `frontendUrl` should also be checked when used in the hostname providers, right now any valid URI can work. If the url is using a weird protocol or empty hostname is useless in the same way. I'll send a quick PR for that.

I know there is some CodeQL analysis for the PRs but I don't really know how it is configured. :smile: 

Thanks!
