### ISSUE TITLE
[UX Review] Add a label to indicate the bind type

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#17697]
### Describe the bug

If the flow is bound to a type, a label should be added to indicate that type. For more details about the label, please refer to the link here. https://marvelapp.com/prototype/bh91013/screen/85125471

<img width="1146" alt="Screen Shot 2022-06-17 at 15 29 35" src="https://user-images.githubusercontent.com/53931519/174249026-9a6ac413-03ce-4fb3-a656-5393ed02888d.png">

### Version

Admin new UI

**Comment by edewit** [comment]
This has been done
