### ISSUE TITLE
Accessibility/Identity Providers: Minor Issues

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak#17718]
### Describe the bug

Minor issues were found as per the [attached](https://docs.google.com/spreadsheets/d/1KtZJbDHKosSJBQm--1iJKQMwGIOtoohXIdfwMH3rPns/edit?usp=sharing).

### Version

21.0.0

### How to Reproduce?

Use Deque Browser Extension.

**Comment by agagancarczyk** [comment]
This is a similar issue to https://github.com/keycloak/keycloak/issues/17719

To fix the issue, we would need to rewrite the ClickableCard component to use a Button component instead (possibly with input from Designers). Assigning the role="button" to the ClickableCard component is not sufficient because the

element, which the ClickableCard component is based on, is not intended to be used as a button or given the ARIA role "button" according to the HTML specification.
Because of the minor severity of this issue and no impact on the user as he/she can still navigate to these elements using the keyboard, and they also work with screen readers such as VoiceOver, I suggest that we don't fix it for now. We can, however, create an enhancement issue and review it in the future to decide if it is worth fixing.

@ssilvert WDYT? Thanks.

**Comment by ssilvert** [comment]
@agagancarczyk Same comment as on #17719 

If it should be fixed by PatternFly, open an issue with them and link here.  Otherwise, let's just close this.
