### ISSUE TITLE
Accessibility/User Federation: Minor Issues

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak#17719]
### Describe the bug

Minor issues were found as per the [attached](https://docs.google.com/spreadsheets/d/1KtZJbDHKosSJBQm--1iJKQMwGIOtoohXIdfwMH3rPns/edit?usp=sharing).

### Version

21.0.0

### How to Reproduce?

Use Deque Browser Extension.

**Comment by agagancarczyk** [comment]
To fix the issue, we would need to rewrite the ClickableCard component to use a Button component instead (possibly with input from Designers). Assigning the role="button" to the ClickableCard component is not sufficient because the <article> element, which the ClickableCard component is based on, is not intended to be used as a button or given the ARIA role "button" according to the HTML specification.

Because of the minor severity of this issue and no impact on the user as he/she can still navigate to these elements using the keyboard, and they also work with screen readers such as VoiceOver, I suggest that we don't fix it for now. We can, however, create an enhancement issue and review it in the future to decide if it is worth fixing.

@ssilvert WDYT? Thanks.

**Comment by ssilvert** [comment]
@agagancarczyk Is this something that should be fixed by PatternFly?  If so, please open an issue with them and link here.

If not, I think it's OK to just close this.
