### ISSUE TITLE
Supporting EdDSA

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#17724]
### Description

This issue is for UI part for supporting EdDSA in keycloak repository whose issues is https://github.com/keycloak/keycloak/issues/15714 .

The issues covers the following points:
- Showing EdDSA keys (TYPE OKP) in UI of Realm settings > Keys > Keys list
- Adding EdDSA keys in UI of Realm settings > Keys > Providers

### Discussion

https://github.com/keycloak/keycloak/discussions/15713

### Motivation

shown in https://github.com/keycloak/keycloak/issues/15714 .

**Comment by edewit** [comment]
now that the ui repo is merged into the main repo we can close this one
