### ISSUE TITLE
User attribute search

### ISSUE THREAD

**Issue by artur-baltabayev** [keycloak/keycloak#17728]
### Description

The suggested user attribute search is a "mode" that you can switch to and that will exist on the same page as the current default search. It would work as follows :

- When switching to the user attribute search you will be presented with a drop down instead of a search field.
- The dropdown will open a new menu that allows you to select multiple attribute key/value pairs and add it to a filter.
- For the attribute key's you will only be able to select the ones that are defined in the user profile (from a dropdown).

### Motivation

Some of our customers require a user attribute search for their support operators. Examples of common attributes that are searched for in such a way are "Postal Code", "Company ID", "User ID" (different from Keycloaks UUID) etc.. .
Since the current Admin UI doesn't support such a feature we want to make a suggestion on how we could implement it.

### Details

We made multiple mokups to explain the feature in greater detail (icons and namings are only suggestions).

This is the new "Options" dropdown which will enable you to switch between the current search and the new attribute search.

![User_Search_Options_Dropdown](https://user-images.githubusercontent.com/68421193/216050625-5f68724a-8061-4192-ae46-0144c3a214e4.PNG)

After switching to the new search mode you will be presented with a "Attribute search" dropdown, which opens the new search interface. As you can see we already added a few key/value pairs to the filter such as "Postal Code" / "1234". The attribute name will be resolved from the user profile display name if possible.

![User_Search_Attribute_Search_Dropdown](https://user-images.githubusercontent.com/68421193/216051044-015bd870-fe24-4bd3-8571-a0ae08346822.PNG)

The "Select attribute key" dropdown presents you with a given set of key's which are the ones that are configured in the user profile.

![User_Search_Options_Dropdown_Key_Dropdown](https://user-images.githubusercontent.com/68421193/216051250-f9fac301-f5cb-4277-9698-8d0c6efb045a.PNG)

**Comment by andreas-blaettlinger** [comment]
Hi @ssilvert, @jonkoops, I created a first version based on the design from @xianli123.
Any feedback very welcome!

**Comment by jonkoops** [comment]
Thanks for that @andreas-blaettlinger!

**Comment by jaceblake** [comment]
If it was implemented, why I don't see this option? I am using keycloak 26.
