### ISSUE TITLE
Add Arabic translations

### ISSUE THREAD

**Issue by Eng-Fouad** [keycloak/keycloak#17726]
### Description

<strike>
The Arabic translation of messages in the main Keycloak repository is [completed](https://github.com/keycloak/keycloak/pull/17090), and we need to add Arabic translations of messages in this repository:
</strike>

Edit: After moving [keycloak-ui](https://github.com/keycloak/keycloak-ui) repo to `js` directory of this repo.

The Arabic translation of messages in `themes/src/main/resources-community/theme` is [completed](https://github.com/keycloak/keycloak/pull/17090), and we need to add Arabic translation of messages in `js/apps`:

```[tasklist]
### Files to be tranlsated
- [x] `js/apps/account-ui/public/locales/ar/translation.json`
- [x] `js/apps/admin-ui/public/resources/ar/authentication-help.json`
- [x] `js/apps/admin-ui/public/resources/ar/authentication.json`
- [x] `js/apps/admin-ui/public/resources/ar/client-scopes-help.json`
- [x] `js/apps/admin-ui/public/resources/ar/client-scopes.json`
- [x] `js/apps/admin-ui/public/resources/ar/clientScopes.json`
- [ ] `js/apps/admin-ui/public/resources/ar/clients-help.json`
- [ ] `js/apps/admin-ui/public/resources/ar/clients.json`
- [ ] `js/apps/admin-ui/public/resources/ar/common-help.json`
- [ ] `js/apps/admin-ui/public/resources/ar/common.json`
- [x] `js/apps/admin-ui/public/resources/ar/dashboard.json`
- [ ] `js/apps/admin-ui/public/resources/ar/dynamic.json`
- [x] `js/apps/admin-ui/public/resources/ar/events.json`
- [ ] `js/apps/admin-ui/public/resources/ar/groups.json`
- [ ] `js/apps/admin-ui/public/resources/ar/identity-providers-help.json`
- [ ] `js/apps/admin-ui/public/resources/ar/identity-providers.json`
- [ ] `js/apps/admin-ui/public/resources/ar/realm-settings-help.json`
- [ ] `js/apps/admin-ui/public/resources/ar/realm-settings.json`
- [x] `js/apps/admin-ui/public/resources/ar/realm.json`
- [ ] `js/apps/admin-ui/public/resources/ar/roles.json`
- [x] `js/apps/admin-ui/public/resources/ar/sessions.json`
- [ ] `js/apps/admin-ui/public/resources/ar/user-federation-help.json`
- [ ] `js/apps/admin-ui/public/resources/ar/user-federation.json`
- [ ] `js/apps/admin-ui/public/resources/ar/users-help.json`
- [ ] `js/apps/admin-ui/public/resources/ar/users.json`
```

Repo: https://github.com/Eng-Fouad/keycloak/tree/ar-locale

**Comment by Eng-Fouad** [comment]
@Mouhand-Kaddo I moved all translations files from https://github.com/Eng-Fouad/keycloak-ui/tree/ar-locale to https://github.com/Eng-Fouad/keycloak/tree/ar-locale

**Comment by ahus1** [comment]
I assume this is now completed as part of PR #17090.

We're currently rolling out Weblate to a web based translation, see https://github.com/keycloak/keycloak/blob/main/docs/translation.md

We plan to add the different langauges to weblate one-by-one. Leave a comment in https://github.com/keycloak/keycloak/discussions/9270 if you are interested in maintaining a specific language.
