### ISSUE TITLE
Restore the Cache tab in Realm Settings

### ISSUE THREAD

**Issue by Luthien-in-edhil** [keycloak/keycloak#17727]
### Description

I noticed that the Cache tab has been removed from the Admin UI since Keycloak v19.
I can still access it in v20 by switching the Admin Console Theme to "Keycloak" but I understand it will be removed in v21.

I'd like to ask to re-enable this tab.

### Discussion

https://github.com/keycloak/keycloak/issues/18313

### Motivation

As mentioned in [the discussion above](https://github.com/keycloak/keycloak/issues/18313) this function is supposedly rarely used. I can imagine that that's the case for server administrators, but for me as a developer of custom SPI's, having the ability to quickly flush the user cache is extremely useful.

Of course I _can_ use the `./kcadm.sh` utility, but in a typical scenario of manually editing timestamps in the DB and executing the custom REST endpoint to debug the code, having a simple button to make KC aware of the DB changes is really convenient. 

I can't judge whether or not that weighs up to the added effort of maintaining that tab, but I felt I should mention it in any case.

Thanks.

**Comment by sschu** [comment]
@edewit There are other use cases for this as well, e.g. we do certain mass changes directly on the database because it would be too slow via API. Then flushing the caches is necessary to make Keycloak pick up the changes.

**Comment by sschu** [comment]
@stianst said the cache tab should be added to the master realm settings. He told me to write this here. ;)

**Comment by bekwam** [comment]
With 18, I could create a Mapper for a Client and flush the user cache and see the effects.  My workaround for the missing button in 21.1.2 is to restart the whole container which affects all Realms.

**Comment by sschu** [comment]
@bekwam The API endpoint to flush the cache is still there, so you could also use curl. Furthermore, the flush cache function already clears the cache for all realms since there is only one cache for all realms. So the fact that it was under the individual realm settings was a bit misleading.

**Comment by darrell-hart** [comment]
What is the endpoint for managing caches?  I need to clear the user cache butI can't seem to get any of the cache endpoints to work.  For example to view cache info I have tried http://localhost:8080/auth/realms/master/cache/sizes and http://localhost:8080/realms/master/cache/sizes but neither work (404) I know I am authenticated ok because http://localhost:8080/admin/realms/master/clients works.

**Comment by sschu** [comment]
For user cache, I see a POST to this endpoint: `http://localhost:8080/admin/realms/master/clear-user-cache`.

**Comment by taufanvps22** [comment]
@sschu  can u help with the complete curl / doc that I can read

Thanks

**Comment by sschu** [comment]
You can apparently use `kcadm.sh` this, see https://www.keycloak.org/docs/latest/server_admin/#flushing-the-caches.

**Comment by yanxch** [comment]
memo:

POST http://localhost:8080/admin/realms/master/clear-user-cache
POST http://localhost:8080/admin/realms/master/clear-realm-cache
POST http://localhost:8080/admin/realms/master/clear-keys-cache
