### ISSUE TITLE
Improve feature (detection) code in the Admin Console

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#17733]
There is already [some code](https://github.com/keycloak/keycloak/blob/aa77f713c48fb2f0678ffd4cc2318c1c4c400b79/js/apps/admin-ui/src/utils/useIsFeatureEnabled.ts) present to detect which features are enabled in the Admin Console. However, due to the way the REST API is designed it cannot properly detect all of the enabled features. Therefore this implementation must be changed.

The proposal is as follows, instead of the [`ProfileInfoRepresentation`](https://www.keycloak.org/docs-api/21.0.1/rest-api/index.html#_profileinforepresentation) containing a bunch of separate fields (`disabledFeatures`, `experimentalFeatures` and `previewFeatures`) it should contain a single `features` field with a more detailed data structure that matches what is known in the model on the Java side.

An example of such a data structure would be:
```js
{
  features: [
    {
      id: "AUTHORIZATION",
      label: "Authorization Service",
      type: "DEFAULT",
      isEnabled: true,
      dependencies: []
    },
    {
      id: "ACCOUNT_API",
      label: "Account Management REST API",
      type: "DEFAULT",
      isEnabled: true,
      dependencies: []
    },
    {
      id: "ACCOUNT3",
      label: "Account Management Console version 3",
      type: "EXPERIMENTAL",
      isEnabled: false,
      dependencies: ["ACCOUNT_API"]
    }
  ]
}
```

Then, once the REST API has been adjusted the data can be retrieved and mapped into something like the following TypeScript:

```ts
enum FeatureType {
  /** This feature is enabled by default. */
  Default = "DEFAULT",
  /** This feature is disabled by default. */
  DisabledByDefault = "DISABLED_BY_DEFAULT",
  /** This feature is in preview, it will be stabilized soon and is enabled by default. */
  Preview = "PREVIEW",
  /** This feature is in preview, it will be stabilized soon but is disabled by default. */
  PreviewDisabledByDefault = "PREVIEW_DISABLED_BY_DEFAULT",
  /** This feature is experimental and disabled by default, it might be promoted to preview in the future. */
  Experimental = "EXPERIMENTAL",
  /** This feature is deprecated and disabled by default, it should not be used and will be removed in the future. */
  Deprecated = "DEPRECATED"
}

type Feature = {
  /** The unique identifier for the feature. */
  id: string;
  /** The type of feature. */
  type: FeatureType;
  /** A human readable label that describes the feature. */
  label: string;
  /** A boolean indicating whether the feature is currently enabled. */
  isEnabled: boolean;
  /** Dependencies of the feature, which need to be enabled in order for it to work. */
  dependencies: Feature[];
}
```

Subsequently we can then refactor the code that previously used the now deprecated `disabledFeatures`, `experimentalFeatures` and `previewFeatures` fields to the new `features` field, which should contain accurate information about whether which features are enabled.

**Comment by edewit** [comment]
we have the `useIsFeatureEnabled` and you can do `isFeatureEnabled(Feature.DeclarativeUserProfile)`

**Comment by jonkoops** [comment]
@edewit according to @ssilvert that implementation is incorrect and needs an API fix.

**Comment by jonkoops** [comment]
@ssilvert @edewit I've re-written the issue so it is more clear what should be implemented WDYT?

**Comment by edewit** [comment]
This would mean building a custom serializer / configure the enums so that they create this json.

**Comment by jonkoops** [comment]
Essentially, yes

**Comment by ruckc** [comment]
It seems it is impossible to determine which features are enabled through the UI.  I just enabled docker, and now it doesn't show up at all.

![image](https://github.com/keycloak/keycloak/assets/1426401/f93f7db6-6d6e-4317-abbd-6507577de666)

**Comment by jonkoops** [comment]
@edewit could you back-port this one for version 22?
