### ISSUE TITLE
[UX Review] Left-align the subtab row and main tab row

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#17731]
### Description

In the latest UI, the subtab row and main tab row are left-aligned on some pages, but not the others. We can left-align the subtab row and main tab row to make the UI consistent.

<img width="785" alt="Screen Shot 2022-12-09 at 15 56 02" src="https://user-images.githubusercontent.com/53931519/206654645-c1caa377-f12a-4641-87b9-2e71ade9c999.png">

<img width="1158" alt="Screen Shot 2022-12-09 at 15 50 17" src="https://user-images.githubusercontent.com/53931519/206654634-3e6ac685-31c0-4735-a0eb-ff4bb5ecff15.png">

**Comment by agagancarczyk** [comment]
This has been fixed and is correct.

On the full-size screens, the tabs are aligned in the same way throughout the UI. This is similar to the small-size screens with the exception that the left arrow is added and the alignment is again consistent throughout the UI e.g. Realm settings and Clients> Client details.
