### ISSUE TITLE
Admin-UI: Show realm display name in realm drop down instead of realm id if available

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#17735]
### Description

At the moment in the realm selector the available realms are displayed by their realm id. It would be nice if instead of the realmId the displayName is shown if available.

**Comment by ssilvert** [comment]
We could use the display name if available and use id if not available.  

Both display name and ID could be quite long.  So in that case we would show `...` at the end and you could hover to see the full name.

**Comment by igprasad36** [comment]
@ssilvert Display Name is not unique. If user creates 2 realms having same Display Name, wouldnt it be confusing ?

**Comment by xianli123** [comment]
@igprasad36 
> Display Name is not unique.

Yes. The display name is not unique. But the Realm ID is unique. So I am curious about why you want to view the display name in the dropdown. Is there any special use case?

**Comment by jonkoops** [comment]
> We could use the display name if available and use id if not available.

Yes, I think that this is likely the best solution. If am not entirely sure, but I believe I have seen cases where folks have put HTML in the display name, not sure if that might cause us trouble (from a UX perspective). Either way, we could strip the HTML is this use-case exists.

>  If user creates 2 realms having same Display Name, wouldn't it be confusing ?

So maybe, don't do that? Users themselves are responsible for making sure that their data is not confusing. We could also choose to show the `id` as part of [the description](https://www.patternfly.org/components/menus/dropdown), which could look a little like this:

![A screenshot showing the description text in various dropdown items.](https://github.com/keycloak/keycloak/assets/695720/309d57b9-2205-4177-9064-a95e4a6c11bc)

>  So I am curious about why you want to view the display name in the dropdown. Is there any special use case?

It is quite logical, as the display name is supposed to be a human readable version of the realm.

**Comment by antikalk** [comment]
> Yes, I think that this is likely the best solution. If am not entirely sure, but I believe I have seen cases where folks have put HTML in the display name, not sure if that might cause us trouble (from a UX perspective). Either way, we could strip the HTML is this use-case exists.

There is also the `HTML Display name`-Property, which should be used for that I guess. 


> So maybe, don't do that? Users themselves are responsible for making sure that their data is not confusing. We could also choose to show the `id` as part of [the description](https://www.patternfly.org/components/menus/dropdown), which could look a little like this:
> 
> ![A screenshot showing the description text in various dropdown items.](https://user-images.githubusercontent.com/695720/262951730-309d57b9-2205-4177-9064-a95e4a6c11bc.png)

I really like that solution!

**Comment by ssilvert** [comment]
> @ssilvert Display Name is not unique. If user creates 2 realms having same Display Name, wouldnt it be confusing ?

That's a good point.  Even though users would be the ones creating the confusion, we shouldn't add to their confusion if they do it.

**Comment by xianli123** [comment]
I think this is a solution to this issue. One thing I suggest is to put the **Realm ID** above the **Display name**, because the Realm ID is unique and required for a realm. Does it make sense?

![image](https://github.com/keycloak/keycloak/assets/53931519/b16cd2ee-b5be-41db-8d64-9f25dcbdac69)

**Comment by jonkoops** [comment]
> One thing I suggest is to put the Realm ID above the Display name, because the Realm ID is unique and required for a realm.

Personally I think whatever is meant to be readable by users should be on top, but we can flip it around if you like. Note that we cannot flip the title and description order, as this is fixed in PatternFly. So this would mean that the realm id would be shown as the tile and the realm name as description.

**Comment by xianli123** [comment]
@jonkoops That makes sense. 

> Personally I think whatever is meant to be readable by users should be on top

I agree. In the console, the Realm ID could be the readable and user-friendly name. It could be shown at the top. 

In addition, the Display name is not required. If there are a lot of realms without display names and the display name at the top, the dropdown menu will show a lot of titles named "no-display-name". It's confused. 

So I think we can put the Realm ID at the top as the title. Realm ID is required and readable.

**Comment by jonkoops** [comment]
> I agree. In the console, the Realm ID could be the readable and user-friendly name. It could be shown at the top.

I'd argue the display name makes more sense, as this is quite literally meant to be a field to be read by users. A kind of 'human readable' name.

> So I think we can put the Realm ID at the top as the title. Realm ID is required and readable.

Don't agree that it's more 'readable', but the fact that it's always there is a good enough reason, let's go with that.

**Comment by jonkoops** [comment]
So I think we have a solid idea of how to implement this, if anyone wants to take it feel free to let me know.

**Comment by xianli123** [comment]
In the current UI, the Realm name equals the Realm ID. When creating a realm, the Realm name is required and readable. The realm name (realm ID) is the identifier of the realm. So I think it'd be better to put the realm name (realm ID) above the display name. Does it make sense?

**Comment by jonkoops** [comment]
> In the current UI, the Realm name equals the Realm ID. 

Yeah, this is wrong. When creating a new realm the field is incorrectly called "Realm name", when it should be "Realm ID". If you create a new realm with the "Realm name" filled, and then view the realm settings, you'll see the same value but labelled "Realm ID".

We should rename this field so that it's consistent.

**Comment by xianli123** [comment]
Yes. It'd be better to keep consistent.

**Comment by igprasad36** [comment]
@jonkoops Can I try this one ?

**Comment by jonkoops** [comment]
Sure, go right ahead. I'll assign this to you 👍

**Comment by eriksunsol** [comment]
@xianli123 
> Yes. The display name is not unique. But the Realm ID is unique. So I am curious about why you want to view the display name in the dropdown. Is there any special use case?

For some Keycloak applications it may not matter, but there's definitely a use case for this. Because Realm IDs are used in URLs, an attacker may enumerate realms by guessing. This can be avoided by using IDs that don't mean anything to an attacker and are hard to guess, for example randomly generated strings, however, currently the admin UI becomes very unfriendly if you do that.

**Comment by jonkoops** [comment]
I am removing the assignee for this one so it can be picked up by someone else.

**Comment by jbpin** [comment]
Is this broken on 23.0.6 ? 

```
GET /admin/realms/master/ui-ext/realms/names? 
```
give a 404 ?

**Comment by jonkoops** [comment]
Not sure what you are talking about @jbpin, but this issue is still open so not implemented. If you feel like you found a bug, please report so as a separate issue.

**Comment by antikalk** [comment]
@jonkoops closing this issue as the PR got merged

**Comment by snevas** [comment]
Display Name is also used for MFA as issuer field which is a generic service name for all realms in my use case. As a consequence of this change all realms show the same value in the realm selector.
