### ISSUE TITLE
Show expiration date of realm keys

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#17743]
### Description

The realm keys are currently listed like this:
```
Algorithm  | Type | Kid                                         | Provider          | Public keys
RSA-OAEP   | RSA  | 7ShgKSatq0nK5fyXxvj-fwrXj28AZ68FzHTK2memURQ | rsa-enc-generated | [Public Key] [Certificate]
RS256      | RSA  | WvCsvncC4MtdlyCmndluWsbaAoK7MBMORiD4Ai25YyU | rsa-generated     | [Public Key] [Certificate]
```

It would be helpful to also provide "valid from" and "valid to" information and the thumbprint value of the certificate.
Valid to should be displayed in the table:
```
Algorithm  | Type | Kid                                         | Provider          | Valid to            | Public keys
RS256      | RSA  | WvCsvncC4MtdlyCmndluWsbaAoK7MBMORiD4Ai25YyU | rsa-generated     | 2030-11-27T17:42:02 | [Public Key] [Certificate]
```
Other details could be shown when clicking on the [Certificate] button.

Current workaround for the missing feature:  

- Click [Certificate] button
- Copy the displayed key into a file `cert.pem`
- Add line -----BEGIN CERTIFICATE----- as first line and -----END CERTIFICATE----- as last line
- Use openssl to parse the certificate: `openssl x509 -in cert.pem -text`

### Discussion

PR which also adds this feature at old admin console as a side effect:
[KEYCLOAK-17609: OIDC broker x5t jws header #7890](https://github.com/keycloak/keycloak/pull/7890)

Realm key related discussions
[Automatic realm key rotation #13776](https://github.com/keycloak/keycloak/discussions/13776)
[Realm key(s) uses - Allowing multivalue fields #8523](https://github.com/keycloak/keycloak/discussions/8523)

### Motivation

It is important to see when a key will expire.

### Details

Keycloak Admin API Backend needs to provide additional data like _from_, _to_, _thumbprint_ with the /keys resource.

**Comment by thomasdarimont** [comment]
I took a quick look at this and adapted the changes from #7890 for the new admin ui

The "Not Before" column is now visible in the table, however since the thumbnail is quite long I added a dedicated thumbprint button
![image](https://github.com/keycloak/keycloak/assets/314690/e83c975b-62b0-4714-b2a9-b601fc264e45)

![image](https://github.com/keycloak/keycloak/assets/314690/25e56a41-27f4-48b6-9334-f94155226ac7)

**Comment by edewit** [comment]
@thomasdarimont why not create a PR with these changes

**Comment by thomasdarimont** [comment]
@edewit just rebased and pushed the PR

**Comment by thomasdarimont** [comment]
@jbman I just updated the PR with your suggested changes for the new admin ui.

I have a question here: Currently I use a sha1 to generate an additional certificate thumbprint (as was suggested in the referenced PR). Is sha1 still okay for the thumbgprint, or should we use rather sha256 instead here?

**Comment by sschu** [comment]
@thomasdarimont  Better use SHA256. Even if it is not necessary here, if somebody sees SHA1 you will always have to argue why it is OK in this case.

**Comment by thomasdarimont** [comment]
Actually I think we might need both, currently the thumbprint is used within the JWS Builder to render the x5t header claim (which must be SHA1) however we could also render the "x5t#S256" thumbprint which is a based on a SHA256 hash.
See: https://datatracker.ietf.org/doc/html/rfc7515#page-12

**Comment by thomasdarimont** [comment]
I think it would make sense to have a button "thumbprints" and show multiple thumbprints in the dialog.

Sha1: xxxxxxx
Sha256: xxxxxxx

Then it's clear what was meant an the standard hashes would be covered (x5t and x5t#S256)

**Comment by thomasdarimont** [comment]
But I have the feeling that this needs a bit more thought, I think I should split up the PR into two:
1) add the expiration date to the keys list  (this issue)
2) add support for various kinds of key thumbprints

What do you think?

**Comment by sschu** [comment]
Sounds good to me.

**Comment by jonkoops** [comment]
I think splitting it up makes sense, let's go with that.

**Comment by thomasdarimont** [comment]
Just managed to create a dedicated PR for showing the expiration date.
