### ISSUE TITLE
Project Masthead

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#17746]
### Description

"Project Masthead" is a meta-project that follows from the need to share UI components between the Keycloak admin console and the account console.   Also, we need for developers to easily customize admin and account console.  According to [PatternFly Masthead documentation](https://www.patternfly.org/v4/components/masthead/), "A masthead contains global properties such as logotype, navigation and settings in an organized fashion and it is accessible from all parts of the application. All pages should share a common masthead."

<img width="953" alt="masthead" src="https://user-images.githubusercontent.com/507202/189887511-d3ca352e-258d-4d09-a52f-2fc510a55ca1.png">

But Project Masthead goes beyond just a masthead for a single application.  Instead of just having all pages to share a common masthead, all applications that participate in Keycloak SSO can share a common masthead along with a common look and feel and access to common tools like the account console and an app switcher.  Project Masthead makes it easy to build out this kind of infrastructure.  Think of it as your own "Google Applications" for the enterprise.

Project Masthead consists of a set of UI components, utilities, and documentation that allow a developer to easily create an application that uses Keycloak SSO and provides authentication, authorization, and account services with a similar look and feel.

Tasks needed to develop Project Masthead include:
- Factor out common components from the new admin console.
- Use these common components to create a new version of the account console.
- Create a sample application using these common components with React
- Create a sample application using these common components with another framework, such as Vue.
- Provide developer documentation
- Create an App Switcher to navigate between applications that participate in Keycloak SSO
- Add the ability to use an avatar from a social provider or an image server
- Make it easy to promote common look and feel between applications (i.e. CSS and logo)
- Research feasibility of slimmed-down PatternFly

### Discussion

Discussed in UI Team Meetings and with management
This discussion is also relevant to providing easier customization: https://github.com/keycloak/keycloak/discussions/13598

**Comment by Scot-Survivor** [comment]
Any updates on this issue?

**Comment by ssilvert** [comment]
@Scot-Survivor It hasn't been publicized that well, but we now support the OIDC `picture` claim in both admin and account console.
https://github.com/keycloak/keycloak-ui/pull/3195

For me, I just used a user attribute called `picture`, set up the URL, and added the mapper.

**Comment by NhProGamer** [comment]
Any news about the account console V3 ?

**Comment by helmut72** [comment]
Isn't it possible to use Keycloak for saving the picture or take it from LDAP jpegPhoto attribute and provide it as an URL?

Keycloak recently advertised [user self-management on Fosdem](https://fosdem.org/2024/schedule/event/fosdem-2024-2065-add-user-self-management-brokerage-and-federation-to-your-infrastructure-with-keycloak/).

Then user self management is in one place and not cluttered to different places.

**Comment by edewit** [comment]
It's been published as part of the [ui-shared library](https://www.npmjs.com/package/@keycloak/keycloak-ui-shared) `KeycloakMasthead`
