### ISSUE TITLE
Implement complex attribute types

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#17740]
Currently we have a basic implementation for attributes that supports string based values (as pictured below).

![A screenshot of the Attributes tab of a user](https://user-images.githubusercontent.com/695720/193823092-84c0c798-07c0-439e-b3b9-32beb892580f.png)

However, the value in this form can be any valid [JSON value](https://www.json.org/json-en.html) data type. The UI should be designed to accommodate these complex values.

For more context see keycloak/keycloak#18028

**Comment by ssilvert** [comment]
This is addressed by User Profile.
