### ISSUE TITLE
Consider styled-components or CSS modules

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#17751]
Right now we override extend patternfly styles for curtain components and initially we thought that this would enable users to change the look and feel of the admin console. Right now this is not so realistic anymore due to how the console is installed. So we should rethink this approach and maybe use [styled components](https://styled-components.com/) or css / sass modules.

**Comment by edewit** [comment]
closing this issue as we use styled components in most cases

**Comment by jonkoops** [comment]
> closing this issue as we use styled components in most cases

We don't `styled-components` is not included anywhere. And the CSS is still inconsistently imported, sometimes it's a CSS module (`.module.css`) and sometimes it is a regular style-sheet, but this issue has not been resolved in the slightest.
