### ISSUE TITLE
Usability of `Use discovery endpoint`

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#17767]
Concerning when you try to add an OpenID Connect provider:

User is presented with a screen that has `Discovery endpoint` as a required field.  But it isn't actually required.  This field is only required if `Use discovery endpoint` is on.  If you turn off `Use discovery endpoint`, the required field goes away and many more fields are revealed.  

While use of the discovery endpoint to fill in the extra fields is a great feature, it is unclear to the user that there are actually three ways to fill in the fields that automatic discovery fetches for you.  You can fill in the fields one of three ways:
1. Fetch the values from the discovery endpoint.
2. Import the values from a file.
3. Fill in the fields manually.

A fourth way, which would be easier still, would be to choose a realm.  This would only work for Keycloak OIDC providers that are available on the same server.  So I don't know how common that configuration would be, but it would be really simple for the user to just pick a realm and be done with it.

I believe that the UI needs to be more explicit about the various ways to fill in these fields and the choices that are available.  Currently, when the user is first presented with the screen to add an OIDC provider, it appears that option number 1 is the only option available.

**Comment by edewit** [comment]
the way it works for the admin client is that you call importFromUrl:
```js
const result = await kcAdminClient.identityProviders.importFromUrl({
      providerId: "oidc",
      fromUrl:
        "http://localhost:8180/realms/master/.well-known/openid-configuration",
    });
```
The result is a json with the settings you then can pass into the create as config

**Comment by flutra-osmani** [comment]
Thanks. That method seems to be deprecated in the latest version of the library but `importFrom(..)` works.
