### ISSUE TITLE
Apply typeahead style to dropdown with more than 10 options

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak#17776]
According to PF's guideline, when we have dropdowns with more than ten options (no matter it is a single or multiple select list), we'll apply the [typeahead style](https://www.patternfly.org/v4/components/select/react#typeahead) to the dropdown.

**Comment by john-gom** [comment]
I would be interested in working on this and maybe combining it with #25131 to sort the list by the localized label. Would this require any kind of feature flag?

Also, if a field has an existing value it is quite frustrating if the existing value is not auto-selected when you click into it. Would adding this behaviour as a default give any concerns?

**Comment by jonkoops** [comment]
Feel free to submit a PR for this @john-gom, we can discuss the implementation details there, it's easier to argue about code. Would you like me to assign this issue to you?

**Comment by john-gom** [comment]
Sure, I'll hopefully get time to look at it today.

**Comment by john-gom** [comment]
Hi @jonkoops . I have raised a couple of PRs (#27737 and #27726) but haven't heard anything back in over a week. Have I missed out anything?

**Comment by jonkoops** [comment]
@john-gom I'll try to get your open PRs reviewed tomorrow, could you like this issue there?
