### ISSUE TITLE
b.map is not a function 

### ISSUE THREAD

**Issue by vplemyannik** [keycloak/keycloak#17784]
### Describe the bug

Error when open users on master realm 
![image](https://user-images.githubusercontent.com/17518385/224958545-17b09782-c4a8-483b-9008-3d66dda7f955.png)

Reproduced with nightly build
![image](https://user-images.githubusercontent.com/17518385/224959189-fea7980f-ed2a-42f7-9e31-544ccbbfd504.png)

### Version

nightly

**Comment by ssilvert** [comment]
Thanks @thomasdarimont.

**Comment by HBrites9** [comment]
Hello guys, im using keycloak/keycloak:21.1.1 from quay.io and i still got the problem. In the source code @thomasdarimont solution is alredy updated. Could be because the amount of groups? I saw one problem related to that
Regards

**Comment by jonkoops** [comment]
This fix has not yet been released. It will be included in future patch release.
