### ISSUE TITLE
Pagination doesn't work after search filter

### ISSUE THREAD

**Issue by giordanodavid** [keycloak/keycloak#17782]
### Describe the bug

Hello,

There is an issue with the pagination in the client scopes and realm roles popups.
If I don't filter the list, the pagination works. With the filter, it doesn't.
![image](https://user-images.githubusercontent.com/127959850/225325420-462edd70-260d-4ecc-9ea2-948ce9bcca9e.png)
![image](https://user-images.githubusercontent.com/127959850/225325487-e5dbbdfc-631b-4b10-b8a5-36fe60012613.png)

### Version

20.0.3

### Environment

Chrome / Edge

### Expected behavior

The pagination works after filtering the list.

### Actual behavior

The pagination doesn't work after filtering the list. Other pages don't appear even if page count increases

### How to Reproduce?

- Assign client scopes or realm roles to a Client or a User. The popup appears.
- Filter the results with the textbox "Search for client scope" / "Search by role name". The list is filtered.
- Try to use the pagination. It fails, others pages don't appear.

**Comment by ssilvert** [comment]
@giordanodavid I'm going to go ahead and close this.  If you think it is still broken in the latest nightly build we can reopen.

https://github.com/keycloak/keycloak/releases/tag/nightly
