### ISSUE TITLE
Realm Events Config not persisted when using `keycloak` admin theme

### ISSUE THREAD

**Issue by Badbond** [keycloak/keycloak#17895]
### Describe the bug

When the Admin Console theme is set to `keycloak` and the user tries to save changes to the Events Config tab, the change is not persisted and upon refresh the same state as before is shown.

### Version

20.0.2

### Environment

Google Chrome version 107.0.5304.110

### Expected behavior

The Events Config changes are persisted.

### Actual behavior

The Events Config changes are not persisted and upon refresh show the old values. 

### How to Reproduce?

1. Run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.2 start-dev`.
2. Navigate to http://localhost:8080/admin/master/console/#/master/realm-settings/themes and log in to the Admin Console.
3. Set Admin console themes to `keycloak`.
4. Click Save.
5. Navigate to http://localhost:8080/admin/master/console/#/realms/master/events-settings 
6. Remove `jboss-logging` event listener and click save.
7. Refresh the page.

### Anything else?

- I am not sure whether this is a bug in the frontend or the backend, but at least there is a difference in behavior between two themes, hence reporting it in this repository.
- From inspecting the network requests in the browser, the requests to the server (PUT `admin/realms/master/events/config` and PUT `admin/realms/master`) return 204s.
- No warnings or errors are logged at the server nor in the web console.
- I could reproduce the issue in Keycloak 20.0.0 to 20.0.2.
- I could not reproduce the issue in Keycloak 19.0.3.
- Setting the Admin console theme to `keycloak.v2` is a workaround for the issue.

**Comment by quinot** [comment]
I still see this problem with 21.0.1 and the `keycloak.v2` admin UI theme.

**Comment by ssilvert** [comment]
@quinot This is working for me.  Have you tried the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?
