### ISSUE TITLE
Fine-grained authorization behavior for management of groups differs between version 18.0.3 and 19.03, 20.0

### ISSUE THREAD

**Issue by ExLeonem** [keycloak/keycloak#17913]
### Area

admin/fine-grained-permissions

## Bug
I am trying to migrate my keycloak setup from version 18.0.3 to a more current version, like 19.0.3 or 20.0.
However, the fine-grained authorization mechanism behaves differently in version 19.0.3 and 20.0, even though the setup is identical.

### What I am trying to achieve
- multiple groups
- One group admin per group 
- A group admin is ably to fully manage the group he is in and its users.  (create, delete and configure users, configure the group)

### Version

18.02, 19.0.3, 20.0

### Expected behavior

When I assign a user to `group-a` and give him the role `group-admin` he should be able to...
- ...create, delete, see and configure users in/for `group-a`
- ...configure `group-a`

### Actual behavior

When I assign a user to `group-a` and give him the role `group-admin` he is able to...
- ...create, delete, see and configure users in/for `group-a`

### Scenario
I have multiple groups. I want to create an admin user per group. Each admin should only be able to manage (create, delete, configure users and configure group) the group he is in.

### Example Setup
- Groups: group-a, group-b
- Admin users: admin_a, admin_b
- Users: dummy_user

#### 1. Setup Roles & Policies
1. Create a composite role `group-admin` with associated roles `query-user`, `query-group` (from realm-management).
2. Create the groups (`group-a`, `group-b`)
3. Create a policy `member-group-a` and `member-group-b` (Group policy, positive, only the specific group)
4. Create a pollicy `is-admin` (Role policy, positive, only the group-admin role)

#### 2. Setup the groups
1. Enable Permissions in each group
2. In `group-a` create a permission that gives policy `group-admin-a` all authorization scopes (manage, manage-members, manage-membership, view, view-members)
3. Repeat Step 2 for `group-b` with policy `group-admin-b`

#### 3. Create users 
5. Create a user `admin_a`, assign him role `group-admin` and let him join `group-a`
6. Create a user `admin_b' assign him role `group-admin` and let him join `group-b`
7. Create a user `dummy_user` let him join `group-a`

#### Version 18.0.2
When I login with `admin_a` I am able to...
1. ...see all groups
2. ...configure `group-a`
3. ...create/add a new user to `group-a`
4. ...see/query all users of `group-a`
5. ...configure any user of `group-a` (password, group, roles, etc.)

#### Version 19.0.3 and 20.0
When I login with `admin_a` I am able to...
1. ...see all groups,
2. ...create/add a new user the `group-a`
3. ....see/query all users of `group-a`
4.  ...configure any user of `group-a` (password, group, roles, etc.)

**Comment by anthonyjacquelin** [comment]
@ExLeonem at which step did you create the `group-admin-a / b` ? Thanks
