### ISSUE TITLE
Error! Failed to send email, and Error 400 API

### ISSUE THREAD

**Issue by AzagraMac** [keycloak/keycloak#17933]
### Area

account/ui

### Describe the bug

Configured the mail in **admin/master/console/#/master/realm-settings/email**, a Gmail account, save the credentials and then click Test Connection, sometimes it gives ok, and other times failed, you save again and it gives ok, until you refresh the page and it gives error again. 

By API also gives a 400 error when making a POST request. 

![image](https://user-images.githubusercontent.com/571796/202239816-78746090-214c-4017-8e75-9625281c7e37.png)
![image](https://user-images.githubusercontent.com/571796/202240029-de19fe57-59f3-4043-82bb-e8ee00fed945.png)

![image](https://user-images.githubusercontent.com/571796/202239736-ef1ac897-3eb0-46b6-b241-66fe57a87fad.png)

### Version

19.0.2

### Expected behavior

Save the email credentials, perform a test run and make sure it does not fail. 

### Actual behavior

save the credentials and then click Test Connection, sometimes it gives ok, and other times failed, you save again and it gives ok, until you refresh the page and it gives error again. 

By API also gives a 400 error when making a POST request. 

### How to Reproduce?

Configured the mail in **admin/master/console/#/master/realm-settings/email**, a Gmail account, save the credentials and then click Test Connection, sometimes it gives ok, and other times failed, you save again and it gives ok, until you refresh the page and it gives error again. 
![image](https://user-images.githubusercontent.com/571796/202239736-ef1ac897-3eb0-46b6-b241-66fe57a87fad.png)

### Anything else?
```
2022-11-16 16:43:28,159 ERROR [org.keycloak.services] (executor-thread-1082) KC-SERVICES0029: Failed to send email: javax.mail.AuthenticationFailedException: failed to connect, no password specified?
        at javax.mail.Service.connect(Service.java:376)
        at javax.mail.Service.connect(Service.java:222)
```
_No response_

**Comment by mzehrer** [comment]
I experience this in 19.0.3. Is this solved in higher versions?

**Comment by raghvendramishra-tz** [comment]
> Closing this issue as I can't reproduce and haven't heard back from the author, if this remains an issue feel free to re-open this

Sometimes I am facing same issue ..some time I able to get email and later on it stopped and then working
Using keycloak:26.0.0

<img width="1486" height="553" alt="Image" src="https://github.com/user-attachments/assets/e48df1ef-d1da-4680-a074-10575c23c4e9" />
