### ISSUE TITLE
Make CSS-links absolute instead of relative to prevent PRSSI attacks

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak#18032]
### Description

We use a security-scanner to automatically detect security-problems. 
The scanner complained about the following:
Relative URLs can be dangerous since browser may not determine the correct directory. If the HTML uses path-relative CSS links, it may be susceptible to path-relative stylesheet import (PRSSI) vulnerabilities. This could allow an attacker to take advantage of CSS imports with relative URLs by overwriting their target file.
References:
[Evil CSS Injection](https://www.theregister.co.uk/2015/02/20/prssi_web_vuln/)
[Relative Path Overwrite Attack](https://latesthackingnews.com/2017/07/16/relative-path-overwrite-attack/)
[Research paper: Large-Scale Analysis of Style Injection by Relative Path Overwrite](https://dl.acm.org/doi/10.1145/3178876.3186090)

**Impact**
An attacker may trick browsers into importing JavaScript or HTML code as a stylesheet. This has been shown to enable a number of different attacks, including cross-site scripting (XSS) and exfiltration of CSRF tokens.

**Solution**
It is recommended to use absolute URLs for CSS imports. Alternately you can add the HTML "base" tag in the document which defines the base URL or target location for all the relative URLs.

**Comment by LakshmiPhani7680** [comment]
Hi @ssilvert or @jonkoops  or @foliengriller  or @abbra or @wuwx -> whomever responds it would be great help, like i have got this Path-relative stylesheet import vulnerability in keycloak 24 version, can you please let me know whether this was resolved in the latest or is there anyway that i can resolve this in this version itself.
Thank you

**Comment by foliengriller** [comment]
@LakshmiPhani7680 - basically this was fixed by adding the `<base href="[./]">` to the templates. This should imho prevent the attack, see links above. But of course, not all scanners are satisfied by this solution...

**Comment by LakshmiPhani7680** [comment]
Hi @foliengriller , Thank you so much for the response, i am using the custom themes which contains the .ftl and css files and also contains .properties files where i have included the path to the css files, so how can i add this <base href="[./]"/> tag or any alternative for this or on which version it was fixed as i said i am using version 24. Kindly respond, Thank you.

**Comment by profpiyush** [comment]
Hi @LakshmiPhani7680, Can you please respond if you find any fix for this vulnerability?
