### ISSUE TITLE
prompt=unspecified causing errors in external Idp

### ISSUE THREAD

**Issue by guilhermearpassos** [keycloak/keycloak#18105]
### Describe the bug

When creating a new Idp within keycloak, using advanced option prompt="unspecified" makes it so external (at least azure) Idp rejects user logons since it doesn't recognize this value for this option. In previous Keycloak versions (we're migrating from v13) keycloak didn't send "&prompt=unspecified" to external Idp. We believe it to be a bug in the UI saving the value "unspecified" to the database somewhere.

### Version

19.0.1

### Expected behavior

expected redirect to external login flow without prompt, when unspecified. therefore external idp can go on with their default configuration

>https://login.microsoftonline.com/<your-tenant-id\>/oauth2/v2.0/authorize?scope=openid&state=<...\>&response_type=code&client_id=<your-client-id\>&redirect_uri=http%3A%2F%2Flocalhost%3A8180%2Frealms%2Fmaster%2Fbroker%2Foidc%2Fendpoint&nonce=<...\>

### Actual behavior

keycloak redirects users signing in with a query parameter "&prompt=unspecified", causing microsoft to reject the request since it doesn't have a "unspecified" prompt

>https://login.microsoftonline.com/<your-tenant-id\>/oauth2/v2.0/authorize?scope=openid&state=<...\>&response_type=code&client_id=<your-client-id\>&redirect_uri=http%3A%2F%2Flocalhost%3A8180%2Frealms%2Fmaster%2Fbroker%2Foidc%2Fendpoint&nonce=<...\>

error code
> AADSTS90023: Unsupported 'prompt' value.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/11140366/187035246-e7577927-123d-43eb-aad2-b3d428de3f7e.png)

### How to Reproduce?

1. set up keycloak external Idp using OIDC and "unspecified" prompt
2. try to sign in using newly created oidc

### Anything else?

we noticed when migrating from v13 that while we didnt click on save on the UI the bug didn't occur. Comparing payloads on "save" button between v13 and 19 we found that v13 didnt send unspecified values to the server
> V13 payload:
![V13 payload](https://user-images.githubusercontent.com/11140366/187035583-138c6274-48b8-4944-9a55-54f2371c2e70.png)

> V19 payload:
![V19.0.1 payload](https://user-images.githubusercontent.com/11140366/187035565-7a3c6368-51c2-47ec-9676-8b25f33d13a7.png)

**Comment by rominator1983** [comment]
I do still have this problem in 19.0.3. When creating an IDP connection everything works (kind of, I get other errors still after getting sent back to keycloak).
When I edit the IDP I do still get the error with the prompt.
Can anyone report this as fixed in a newer version?
Using the "Microsoft" type of IDP does not work either. I suppose one must upgrade keycloak for that?

**Comment by jonkoops** [comment]
@rominator1983 we don't support that version of Keycloak any longer, it doesn't receive any security fixes either, so I would recommend upgrading either way. If you are able to reproduce this issue in the latest version of Keycloak, feel free to open a new issue.
