### ISSUE TITLE
Client specific Mapper configuration missing

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#18297]
### Describe the bug

The old admin console allowed to configure client specific protocol mappers as an alternative to the implicit mapper configuration via Client scopes. Although the later provides a more generic configuration, support for specifying client specific mappers ease testing and fine grained configurations.

It would be useful to have that feature in the new admin console as well.

### Version

18.0.0

### Expected behavior

It should be possible to configure client specific protocol mappers for SAML and OIDC clients.

### Actual behavior

Configuration not possible.

**Comment by HolyMacarony** [comment]
And it seems to be removed by now.
