### ISSUE TITLE
Permission editor shows resource IDs instead of names

### ISSUE THREAD

**Issue by flipp5b** [keycloak/keycloak#18318]
### Describe the bug

We have a bunch of resource-based permissions created programmatically using keycloak-admin-client.

In the new admin UI, a permission editor shows resource IDs instead of names:

![Screenshot from 2022-04-01 13-14-08](https://user-images.githubusercontent.com/5507566/161245309-44789311-0a4d-464f-ad9f-a5b5419e5aa2.png)

Meanwhile, a server sends correct resource names along with IDs:

![Screenshot from 2022-04-01 13-14-19](https://user-images.githubusercontent.com/5507566/161245332-a11aa784-0dcc-44c1-819d-3d1eeab7614d.png)

Also, in the old admin UI, the editor shows resource names as expected. (But the old UI isn't able to show multiple resources, it just shows the first one.)

Manually created permissions have no such issue.

### Version

17.0.1

### How to Reproduce?

Here's a relevant (simplified) part of code (Scala) creating permissions:
```scala
...
val permission = ResourcePermissionRepresentation()
permission.setName(name)
resourceNames
  .map(rn => resourcesResource.findByName(rn).get(0).getId)
  .foreach(permission.addResource)
val policy = policiesResource.findByName(policyName)
permission.addPolicy(policy.getId)

val response = permissionsResource.resource().create(permission)
...
```

**Comment by megazone23** [comment]
This problem seem to have come up again with 26.0.7

**Comment by jonkoops** [comment]
Please report a new issue, we cannot track activity on closed issues.

**Comment by megazone23** [comment]
I created issue #36285
