### ISSUE TITLE
[UX Review] Some fine-tuning of the Password policy in the Authentication policy page

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#18348]
### Describe the bug

There is some fine-tuning of the Password policy page as shown in the screenshot below.

<img width="1053" alt="Screen Shot 2022-03-11 at 10 20 55 AM" src="https://user-images.githubusercontent.com/53931519/157789853-6e36c21d-1cbe-4c1c-83b4-69f2ef901322.png">

1. Each label of the fields should have a tooltip.
2. **Hashing Algorithm** should be a dropdown.

For more details please refer to the design link. https://marvelapp.com/prototype/5ifgiai/screen/75687755

### Version

Admin new UI

**Comment by codespearhead** [comment]
1. Each label of the fields should have a tooltip: fixed in PR #24316
2. Hashing Algorithm should be a dropdown: being tracked in #30310
