### ISSUE TITLE
User Federation LDAP: `Remove imported users` modal has wrong text

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#18617]
When you select action `Remove imported users`, the text in the modal says,
`Do you really want to remove all imported users? The option "Unlink users" makes sense just for the Edit Mode "Unsynced" and there should be a warning that "unlinked" users without the password in the Keycloak database won't be able to authenticate.`

I believe that this text came from the wireframe is intended as instructions for the developer.

@andymunro @yih-wang We need more specific text for the modal(s).

**Comment by jonkoops** [comment]
This issue has been resolved, if you have a bug that is still reproducible in the latest version Keycloak then please log a new issue.
