### ISSUE TITLE
No validations on UI side for the user credentials in the login form

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#19065]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

There is no validation on the UI side for the user credentials in the login form. User can provide an empty password and username and the request gets to the backend. In this way the user might end up locking himself..For e.g you have your browser open, you've provided only username and by accident click the login button without password.. This might result in locking the user

### Version

20.0.5

### Expected behavior

There is validation on the UI for the user's credentials, request should not make it to the backend with empty values

### Actual behavior

No validation on the UI, the user can press the submit button with providing no credentials at all

### How to Reproduce?

1. Click on the "Login" button
2. Submit the form without any credentials

**Comment by mposolda** [comment]
@enastevska I am not sure what you mean by `user might end up locking himself` . Do you have Brute-Force protector enabled with only 1 attempt to login?

In that case, I agree that Brute-Force should not be logged (in case that user provided empty password). Overally, this is corner case with low priority and has the workaround (Using more attempts than 1 for Brute-Force protector).

Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .
