### ISSUE TITLE
Failed to make identity provider oauth callback

### ISSUE THREAD

**Issue by alispustina** [keycloak/keycloak#19077]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Users randomly encounter a 502 status error when being redirected from the IDP upon login.

The error message is:

```
Failed to make identity provider oauth callback
Connection reset

```
Followed up by the warning 
`type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=keycloak-openid, clientId=mefio, userId=null, ipAddress=46.252.47.156, error=identity_provider_login_failure, code_id=00353d1b-233e-4391-b310-e69d87793d17, authSessionParentId=00353d1b-233e-4391-b310-e69d87793d17, authSessionTabId=rLwv43OWfOs`

Even after setting these args in Keycloak's pod startup as advised here https://github.com/keycloak/keycloak/issues/12107 and increasing the **socket-timeout-millis** value, the issue persists. 

There are no defined steps on how to reproduce this one; any suggestions are welcome

### Version

19.0.3

### Expected behavior

After receiving a 302 response from the IDP, Keycloak should successfully redirect to the client

### Actual behavior

After receiving a 302 response from the IDP, Keycloak *randomly* displays an error screen and throws the 502 message.

### How to Reproduce?

No clear steps

### Anything else?

<img width="720" alt="Screenshot 2023-03-16 at 3 33 08 PM" src="https://user-images.githubusercontent.com/80396648/225650340-09d38ab7-1ef1-451d-9c48-71bd6dbd0a9e.png">

**Comment by sschu** [comment]
This error just means Keycloak cannot connect to the external IDP to retrieve a token. It could be the IDP temporarily not accepting connection, it could be you are hitting limits of a NAT gateway in the path to the external IDP (like in Kubernetes) or some other network problems. It is most likely not a Keycloak problem.

**Comment by howan36** [comment]
how about the process

**Comment by alispustina** [comment]
Can you elaborate a bit on that please @howan36, what do you mean by it?

**Comment by howan36** [comment]
> Can you elaborate a bit on that please @howan36, what do you mean by it?

i mean did you resolve this issue? or if it's on the process to deal with it.

**Comment by mposolda** [comment]
@sschu +1 to your pointers.

I am closing as this looks like an environment issue (Firewall/network traffic/proxy problem when sending request between Keycloak and IDP) rather than Keycloak bug. You may need to tune your environment and/or also update network parameters for configuration of apache-http-client used for the Keycloak OOB requests as described in https://www.keycloak.org/server/outgoinghttp

**Comment by howan36** [comment]
> @sschu +1 to your pointers.
> 
> I am closing as this looks like an environment issue (Firewall/network traffic/proxy problem when sending request between Keycloak and IDP) rather than Keycloak bug. You may need to tune your environment and/or also update network parameters for configuration of apache-http-client used for the Keycloak OOB requests as described in https://www.keycloak.org/server/outgoinghttp

hi mposolda, thanks a lot for your reply, so which config option you used ? socket-timeout-millis or others?

**Comment by viniciusczar** [comment]
Look the network if you are using docker. Test the dns resolution to 8.8.8.8 are being achieved
