### ISSUE TITLE
Keycloak wrong response after triggering API with token that has no active user session , 403 instead of 401 StatusCode

### ISSUE THREAD

**Issue by JN93** [keycloak/keycloak#19073]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Keycloak provides "probably" wrong status code after triggering API with a user token that has no active user-session. 
Through debug logs can be seen that keycloak is searching with the sessionId provided in token for an offline and / or active user session and none can be found . 
After that  AuthorizationToken Service is failing with  500 Internal Server Error :
PERMISSION_TOKEN_ERROR: org.keycloak.services.ErrorResponseException: HTTP 500 Internal Server Error
Error while evaluating permissions: org.keycloak.services.CorsErrorResponseException: HTTP 500 Internal Server Error

As a user I am expecting to get as response a 401 error "Unauthorized" in order to ask for a fresh token if possible but instead I am getting a 403 Forbidden .

### Version

15.0.4

### Expected behavior

The expected behavior of this scenario is : 

After triggering the API with a user token where the user-session does not exist anymore , 
the system should find out ( as it does ) that the user has no active or offline session but in this case probably the AuthOutcome should be set to some other status than Authenticated and as a result provide as a response code 401 Unauthorized instead of 403 

### Actual behavior

After triggering the API with a user-token where the session is not active anymore the system if failing my API call with a 403 error Code aka Forbidden coming from keycloak server. 

### How to Reproduce?

Issue a token when the system is up and running fine . 
Use it on triggering some API , it should work as expected (fine) . 
Restart keycloak server . 
Retrigger API with the token previously used , do not take a new one .
As response you will get a 403 status code when expected 401 .

### Anything else?

full log : 

sso-app_1  | 11:58:55,574 DEBUG [org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider] [ Txid : ] (default task-1) Offline user-session not found in UserSessionPersisterProvider for sessionId=d9a314ac-bd85-4f3f-9977-aa917c6437ca
sso-app_1  | 11:58:55,574 DEBUG [org.keycloak.services.managers.AuthenticationManager] [ Txid : ] (default task-1) No offline user session
sso-app_1  | 11:58:55,574 DEBUG [org.keycloak.services.managers.AuthenticationManager] [ Txid : ] (default task-1) User session not active
sso-app_1  | 11:58:55,575 DEBUG [org.keycloak.authorization.authorization.AuthorizationTokenService] [ Txid : ] (default task-1) PERMISSION_TOKEN_ERROR: org.keycloak.services.ErrorResponseException: HTTP 500 Internal Server Error
sso-app_1  |    at org.keycloak.authorization.common.KeycloakIdentity.<init>(KeycloakIdentity.java:71)
sso-app_1  |    at org.keycloak.authorization.common.KeycloakIdentity.<init>(KeycloakIdentity.java:66)
sso-app_1  |    at org.keycloak.authorization.authorization.AuthorizationTokenService.lambda$static$0(AuthorizationTokenService.java:132)
sso-app_1  |    at org.keycloak.authorization.authorization.AuthorizationTokenService.createEvaluationContext(AuthorizationTokenService.java:467)
sso-app_1  |    at org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:206)
sso-app_1  |    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.permissionGrant(TokenEndpoint.java:970)
sso-app_1  |    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:208)
sso-app_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sso-app_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sso-app_1  |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sso-app_1  |    at java.lang.reflect.Method.invoke(Method.java:498)
sso-app_1  |    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
sso-app_1  |    at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
sso-app_1  |    at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
sso-app_1  |    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
sso-app_1  |    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
sso-app_1  |    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
sso-app_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
sso-app_1  |    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
sso-app_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
sso-app_1  |    at org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
sso-app_1  |    at org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
sso-app_1  |    at org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
sso-app_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
sso-app_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
sso-app_1  |    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
sso-app_1  |    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
sso-app_1  |    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
sso-app_1  |    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
sso-app_1  |    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
sso-app_1  |    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
sso-app_1  |    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
sso-app_1  |    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
sso-app_1  |    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
sso-app_1  |    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
sso-app_1  |    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
sso-app_1  |    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
sso-app_1  |    at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
sso-app_1  |    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
sso-app_1  |    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
sso-app_1  |    at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
sso-app_1  |    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
sso-app_1  |    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
sso-app_1  |    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
sso-app_1  |    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
sso-app_1  |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
sso-app_1  |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
sso-app_1  |    at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
sso-app_1  |    at java.lang.Thread.run(Thread.java:748)
sso-app_1  |
sso-app_1  | 11:58:55,575 DEBUG [org.keycloak.authorization.authorization.AuthorizationTokenService] [ Txid : ] (default task-1) Error while evaluating permissions: org.keycloak.services.CorsErrorResponseException: HTTP 500 Internal Server Error
sso-app_1  |    at org.keycloak.authorization.authorization.AuthorizationTokenService.lambda$static$0(AuthorizationTokenService.java:135)
sso-app_1  |    at org.keycloak.authorization.authorization.AuthorizationTokenService.createEvaluationContext(AuthorizationTokenService.java:467)
sso-app_1  |    at org.keycloak.authorization.authorization.AuthorizationTokenService.authorize(AuthorizationTokenService.java:206)
sso-app_1  |    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.permissionGrant(TokenEndpoint.java:970)
sso-app_1  |    at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:208)
sso-app_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sso-app_1  |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sso-app_1  |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sso-app_1  |    at java.lang.reflect.Method.invoke(Method.java:498)
sso-app_1  |    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
sso-app_1  |    at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
sso-app_1  |    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
sso-app_1  |    at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
sso-app_1  |    at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
sso-app_1  |    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
sso-app_1  |    at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
sso-app_1  |    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
sso-app_1  |    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
sso-app_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
sso-app_1  |    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
sso-app_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
sso-app_1  |    at org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
sso-app_1  |    at org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
sso-app_1  |    at org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
sso-app_1  |    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
sso-app_1  |    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
sso-app_1  |    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
sso-app_1  |    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
sso-app_1  |    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
sso-app_1  |    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
sso-app_1  |    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
sso-app_1  |    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
sso-app_1  |    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
sso-app_1  |    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
sso-app_1  |    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
sso-app_1  |    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
sso-app_1  |    at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
sso-app_1  |    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
sso-app_1  |    at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
sso-app_1  |    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
sso-app_1  |    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
sso-app_1  |    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
sso-app_1  |    at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
sso-app_1  |    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
sso-app_1  |    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
sso-app_1  |    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
sso-app_1  |    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
sso-app_1  |    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
sso-app_1  |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
sso-app_1  |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
sso-app_1  |    at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
sso-app_1  |    at java.lang.Thread.run(Thread.java:748)
sso-app_1  |
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) MessageBodyWriter: org.jboss.resteasy.spi.ResteasyProviderFactory$SortedKey
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) Interceptor Context: org.jboss.resteasy.core.interception.ServerWriterInterceptorContext,  Method : proceed
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) WriterInterceptor: org.jboss.resteasy.security.doseta.DigitalSigningInterceptor
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.security.doseta.i18n] [ Txid : ] (default task-1) Interceptor : org.jboss.resteasy.security.doseta.DigitalSigningInterceptor,  Method : aroundWriteTo
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) Interceptor Context: org.jboss.resteasy.core.interception.ServerWriterInterceptorContext,  Method : proceed
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) MessageBodyWriter: org.jboss.resteasy.spi.ResteasyProviderFactory$SortedKey
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) MessageBodyWriter: org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider
sso-app_1  | 11:58:55,579 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] [ Txid : ] (default task-1) Provider : org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider,  Method : writeTo
sso-app_1  | 11:58:55,581 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] [ Txid : ] (default task-1) JtaTransactionWrapper  commit
sso-app_1  | 11:58:55,581 DEBUG [org.hibernate.engine.transaction.internal.TransactionImpl] [ Txid : ] (default task-1) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
sso-app_1  | 11:58:55,593 DEBUG [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] [ Txid : ] (default task-1) KeycloakDS: returnConnection(307b4ce6, false) [0/20]
sso-app_1  | 11:58:55,593 FINE  [org.postgresql.jdbc.PgConnection] [ Txid : ] (default task-1)   setAutoCommit = true
sso-app_1  | 11:58:55,593 DEBUG [org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl] [ Txid : ] (default task-1) Initiating JDBC connection release from afterTransaction
sso-app_1  | 11:58:55,593 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] [ Txid : ] (default task-1) JtaTransactionWrapper end
sso-app_1  | 11:58:55,594 WARN  [org.keycloak.events] [ Txid : ] (default task-1) type=PERMISSION_TOKEN_ERROR, realmId=csr, clientId=ESB, userId=null, ipAddress=10.0.0.11, error=invalid_token, reason='HTTP 500 Internal Server Error', auth_method=oauth_credentials, audience=ESB, grant_type=urn:ietf:params:oauth:grant-type:uma-ticket, permission=12cddfcf-fb9a-4dbc-b045-e8df97638daf#GET, client_auth_method=client-secret

**Comment by mposolda** [comment]
@sschu Thanks for looking at this.

I am closing as this is tested with quite old version. Please re-open just if you reproduce this also with latest version.
