### ISSUE TITLE
[Keycloak 21.0.1] Identity provider JWKS public key is not editable via UI

### ISSUE THREAD

**Issue by MikeKasperlik** [keycloak/keycloak#19083]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We are currently upgrading KC from V15 to 21.0.1. In this process we noticed that the former identity provider setting `Validating Public Key` is no longer accessible from the admin ui. 

V15
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/1431474/225674875-efe1367f-6ad0-4714-952c-11dda1f4b64a.png">

V21
<img width="762" alt="image" src="https://user-images.githubusercontent.com/1431474/225674976-3a0f59c2-487f-4aec-8bbb-7daa5e479515.png">

However it works when importing the key into the database `identity_provider_config -> publicKeySignatureVerifier`.

### Version

21.0.1

### Expected behavior

Being able to add/edit such a key via the UI.

### Actual behavior

No input for the key appears.

### How to Reproduce?

1. Create a new Identity Provider
2. Choose Keycloak OpenID Connect Provider
3. Turn off `Use discovery endpoint`
4. Turn on `Validate Signatures`
5. No input for the key appears.

### Anything else?

The documentation still mentions the key: https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker_oidc

**Comment by edewit** [comment]
This option seems to have been removed, I don't think this is a UI issue

**Comment by edewit** [comment]
this is the last version of the old console it already doesn't have this field
![image](https://user-images.githubusercontent.com/51133/226534680-d0d8fa16-f549-45ea-b33b-c77d9d515d39.png)
but I'll discuss this in the meeting today, to see what is what

**Comment by edewit** [comment]
oh wait found the fields, fixing this now
