### ISSUE TITLE
The create new user page requires the admin user to be given the "Manage-Realm" role in order to see the user profile attributes in the create new user page

### ISSUE THREAD

**Issue by JSCorpo** [keycloak/keycloak#19093]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

The create new user page requires the admin user to be given the "Manage-Realm" role in order to see the user profile attributes in the create new user page

The user profile in realm setting is enabled.
![User Profile Enabled](https://user-images.githubusercontent.com/127390108/225835100-9adb06c7-bcf2-4ec8-8cdf-f61d44dd1e9c.jpg)

A new profile attribute has been created and enabled.
![User Profile attribute created](https://user-images.githubusercontent.com/127390108/225835236-db3bbc17-5d79-49b4-bb8d-79bd2125055f.jpg)

The Create user page does not display the user profile attributes unless the admin user has been assign the "Manage-realm" role
![Create User without User Profile attributes](https://user-images.githubusercontent.com/127390108/225835297-3bd27f1d-902a-4c68-bbdf-443b5cc0b730.jpg)

![Create User with User Profile attributes](https://user-images.githubusercontent.com/127390108/225835319-992697ea-47cd-4ac9-8024-a4ca5fa28699.jpg)

### Version

21.0.1

### Expected behavior

The create new user page should display the user profile attributes once the user profile setting is enabled for the realm without the need to assign "Manage-Realm" role to the admin user.

### Actual behavior

The create new user page requires the admin user to be given the "Manage-Realm" role in order to see the user profile attributes in the create new user page

### How to Reproduce?

1. Start Keycloak with user profile enabled (--features=preview)
2. Create new realm
3. Enable user profile
4. Create new user profile attribute
5. Create new admin user with the following roles (Query-Users, Query-Groups, Manage-Users)
6. Click on Create new user

**Comment by jonkoops** [comment]
This seems a UI issue rather than an API issue. I'll re-label this for now.

**Comment by ssilvert** [comment]
I have verified that this is a UI issue.  The custom attribute is returned from the call to `users/profile`.  But it is not displayed unless you have `manage-realm` role.

**Comment by edewit** [comment]
This is the same issue as #17591 we need to know that user profile is on in order to render it, but you need realm role to read this setting so this is a server side issue. We need to always return the `userProfileEnabled` setting regardless of the role.

**Comment by rmartinc** [comment]
I'm doing more or less the same than @pedroigor did in the previous issue  https://github.com/keycloak/keycloak/issues/17591. Regards!
