### ISSUE TITLE
Add no-downtime upgrade for TermsAndConditions change

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#19099]
This is a follow-up on the following issue: #17277 which was addressed only for the legacy store. We need to do the same also for the new store.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
