### ISSUE TITLE
Unable to use SAML entity descriptor with transient NameIDFormat

### ISSUE THREAD

**Issue by matt-rauch** [keycloak/keycloak#19094]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

It's tedious and error prone to import SAML metadata from a file, since things like certificate rollovers aren't detected automatically.

### Version

20

### Expected behavior

When adding a new SAML provider an admin can enter an url of a SAML entity descriptor to import metadata automatically. When this SAML metadatan contains multiple NameIDFormat-elements, the admin should be able to select the NameID policy format und Principal type in the admin ui

### Actual behavior

The fields `NameID policy format` and `Principal type` are readonly, when `Use entity descriptor` is activated.

This leads to further problems, when the SAML entity descriptor lists `NameIDFormat` = `transient `as first element. When you try to add an identity provider like this you reveive the following error:
`Could not create the identity provider: Can not have Transient NameID Policy Format together with SUBJECT Principal Type`

From there on you cannot resolve the error, because the fields are readonly and the `Principal type` is always initalized with `Subject NameID` per default.

### How to Reproduce?

1. Open Admin UI
2. Add new SAML identity provider
4. Ensure `Use entity descriptor` is set to `On`
5. Enter `https://portal.lfrz.at/stdportal-idp/portalverbund.gv.at` as `SAML entity descriptor` and leave field with TAB
6. Click on `show metadata` and check that `NameID policy format` is set to `Transient` and `Principal type` to `Subject NameID`
7. Save. You should get the vaildation error `Could not create the identity provider: Can not have Transient NameID Policy Format together with SUBJECT Principal Type`

**Comment by ssilvert** [comment]
Verified that this works on the old console, but broken on the new one.

**Comment by edewit** [comment]
seems that is not allowed by [keycloak server](https://github.com/keycloak/keycloak/blob/ac490a666cb3a585c53011e89f9b2a2898779acf/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProviderConfig.java#L407) it's not something that the frontend does wrong

**Comment by edewit** [comment]
okay wait I get what the problem is only now, so you want to change the fields after you imported the descriptor. Well in the new console we thought that it would be necessary. But it's still possible, you can import the descriptor and then set `Use entity descriptor` is set to `Off` afterwards

**Comment by matt-rauch** [comment]
The problem with importing the descriptor is, that you lose the ability to detect certificate rollovers automatically. That means our IdP has to inform us before they roll over their certificates and we need to import the new metadata, exactly when they switch their certificates, which is tedious and error prone.

I would love to sync the metadata from an URL and be able to change the `NameID policy format` nevertheless.

**Comment by edewit** [comment]
right that's what I'm saying @matt-rauch you can still import and then change. The way to do that is import your descriptor and after that change `Use entity descriptor` to `Off` all the fields will still have the values from the import

**Comment by matt-rauch** [comment]
@edewit If I follow your description, I lose the values from the import. Was this fixed in v20+, because I'm still on v19.0.2.

I attached a GIF, so you can check if I do something wrong: https://1drv.ms/i/s!AuAtx3kuEcsogkq70SFW5ARtm6MD?e=sdZAeP

**Comment by edewit** [comment]
yes this works on 21
