### ISSUE TITLE
Unable to change the title of Keycloak Admin Console in 21.0.1

### ISSUE THREAD

**Issue by guptakaran27** [keycloak/keycloak#19116]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the previous releases of Keycloak (Till 18), we could change the Title of the admin console, by overriding the  **consoleTitle** 
tag in  **admin-messages_en.properties** 
But, in 21.0.1, we are unable to do so. 
Even after manually creating the properties file, the title still shows "Keycloak Administration UI" instead of my custom message. 

### Version

21.0.1

### Expected behavior

Admin Console UI should display custom Title

### Actual behavior

Admin Console is displaying "Keycloak Administration UI"

### How to Reproduce?

1. Unzip the Keycloak 21.0.1 tar file 
2. Create a custom admin theme in the form : /keycloak/themes/myTheme/admin/messages/admin-messages.properties
3. Provide custom in the field : **consoleTitle**
4. Run the kc.bat file

**Comment by edewit** [comment]
for now the way to modify the admin console is to modify it

**Comment by ssilvert** [comment]
We do plan to make this much easier, but as @edewit said, for now you need to modify or fork the source.

**Comment by guptakaran27** [comment]
Thanks for the update team !

**Comment by guptakaran27** [comment]
Also, @ssilvert  @edewit 
Can I have an idea, which part of the source code needs to be modified in order to achieve this ? 
Also, any timeline, when this will be fixed in a release?
