### ISSUE TITLE
Password policy  "Not Username" and "Not Email" don't work

### ISSUE THREAD

**Issue by mflorczak** [keycloak/keycloak#19112]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

![image](https://user-images.githubusercontent.com/36895020/226135219-aad999b2-7160-4c0c-945d-90ec9818d2c6.png)
Checkbox is disabled and I can't enable it. 

### Version

21.1

### Expected behavior

Checkbox will be selectable and I can enable those two policies.

### Actual behavior

Checkbox is not selectable and I can not enable those two policies.

### How to Reproduce?

Login to admin console go to Password policy and try to select Not Username or Not Email.

**Comment by edewit** [comment]
it's not off it's always `On` you can't disable it because the only way to do that is to remove it with the `-` button 
![image](https://user-images.githubusercontent.com/51133/226259171-fffe90aa-6a3e-423f-b8d9-8619f08bb0e9.png)
