### ISSUE TITLE
kcadm do not update defaultGroups

### ISSUE THREAD

**Issue by ashestak-sc** [keycloak/keycloak#19125]
### Describe the bug

Two groups were created "DEV" and "DEV1". I want to add them to default groups. Next Command do noting, defaultGroups are not updated:
"${HOME}/bin/kcadm.sh" update realms/bma -s  'defaultGroups=["/DEV","/DEV1"]'

Looks like it is old issue. Similar problem reported here also:
https://lists.jboss.org/pipermail/keycloak-user/2018-September/015432.html

### Version

20.0.1

**Comment by shawkins** [comment]
Can confirm this is still an issue.
