### ISSUE TITLE
Documentation is not up to date for implementing Custom User Provider in version 20.0.1

### ISSUE THREAD

**Issue by olman74** [keycloak/keycloak#19129]
### Describe the bug

In the documentation, in the file _server_development/topics/user-storage/provider-interfaces.adoc_ it says we can implement the interface `UserStorageProviderFactory `. 
It seems that this interface is in a _legacy_ folder in the version 20.0.1 and if I want to implement it, it is not available. 
From what I understood, the new interface to implement is `UserProviderFactory`

### Version

20.0.1

**Comment by hmlnarik** [comment]
Duplicate of #17394

**Comment by hmlnarik** [comment]
Thank you for the report. Closing this in favour of #17394.
