### ISSUE TITLE
Better quality of Admin REST API

### ISSUE THREAD

**Issue by DallasP9124** [keycloak/keycloak#19132]
### Description

The admin REST API is significantly lacking in decent documentation. The request descriptions are either lacking in brevity or proper English. Also most of them have a generic Response object that has no description or body structure. It has been this way for many years now and it's really annoying. 

Are there plans to increase brevity and clean up the documentation for accuracy?

**Comment by jonkoops** [comment]
I am closing this issue because the problem statement is too generic for this to be resolved. I expect this might be improved by moving to an OpenAPI schema in the future (see #10775). If anyone has specific places where improvements can be made, feel free to log an issue for those.
