### ISSUE TITLE
Report an issue link points to Jira instead of GHI

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#19136]
### Describe the bug

Community documentations contains "Report an issue" link within each section that points to a Jira issue tracker, which is no longer used. 

### Version

19.0.0

### Expected behavior

Link should point to GHI.

### How to Reproduce?

for example https://www.keycloak.org/docs/latest/server_admin/index.html

**Comment by mposolda** [comment]
Added to Keycloak 22 to doublecheck and update the links (although it is not strictly a blocker for the Keycloak 22 release).

**Comment by ahus1** [comment]
@vickeybrown - yes, this was thought to be a pre-requisite to enable links with pre-filled content. See the other issue for an example. Feel free to elaborate on that, and/or ping me with questions.

**Comment by ahus1** [comment]
@vickeybrown - updating my previous comment that I just deleted: *no* the other PR doesn't handle this. The other PR was thought to be a pre-requisite to enable links with pre-filled content. See the other issue for an example how the new links could look like?

Do you plan to start working on this?

**Comment by vickeybrown** [comment]
Gotcha, makes sense. I was planning on it, but if you'd like to since you've been working on the pre-requisites for it, you're welcome to!

**Comment by ahus1** [comment]
I've got a performance analysis on my desk that might occupy me for several days, so I'm not sure when I can return to this. I'd be happy if you want to look into it.
