### ISSUE TITLE
Mod auth mellon zip file looks inconsistent

### ISSUE THREAD

**Issue by lmode** [keycloak/keycloak#19133]
### Describe the bug

Hi, 
I try downloading adaptor config for client, mod auth mellon files. The zip file I get cannot be opened but with 7zip and in any case it contains zero-length idp xml file. Installed version of keycloak is 19.0.2.
Client is SAML type.
Any idea why is this going to happen?
Thanks a lot for your support, regards

### Version

19.0.2

### Expected behavior

Expect to get a workable mellon .zip file

### Actual behavior

.zip file not possible to open or zero-size files in it.

### How to Reproduce?

Create a SAML client in keycloak and download adaptor config mellon zip files.

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .

**Comment by edewit** [comment]
is this still a problem? We have fixed some issues regarding this in newer versions of the UI
