### ISSUE TITLE
Cannot produce an access token for the admin console

### ISSUE THREAD

**Issue by bugsbunnyshah** [keycloak/keycloak#19145]
### Describe the bug

Following the instructions outlined here:
https://github.com/keycloak/keycloak-documentation/blob/main/server_development/topics/admin-rest-api.adoc

Always 401. Both steps

keycloak-17.0.1

### Version

keycloak-17.0.1

**Comment by mposolda** [comment]
@bugsbunnyshah The 401 error means that authentication fails, likely because `admin` user with password `password` is not available in your environment. You need to create admin user as mentioned in Getting Started guide.

Will slightly update docs about this.
