### ISSUE TITLE
Problem setting TLS1.2 using Keycloak Servlet Filter Adapter

### ISSUE THREAD

**Issue by pigreco33** [keycloak/keycloak#19140]
### Describe the bug

Hi, I'm using keycloak servlet filter adapter to integrate my test application with my Keycloak installation.
Keycloak installation is exposed in https with TLS1.2 enabled (as default).
Servlet filter, that is built as an estension of KeycloakOIDCFilter class, try to retrieve wellknown file configuration from url configured in keycloak.json file.
The problem is that the connection to the keycloak server is reset because client try to iniziate connection using TLSv1.

The software is deployed in Websphere Application Server test environment correctly setted to call same wellknown file url without any problem.
When I try to call same url by KeycloakFilterAdapter the Exception is thrown.

I tried to reproduce the problem creating a simple servlet that use Apache HttpClient to call the same url.
In absence of custom configuration the exception is thrown even in this case.
Changing way to create the client from

CloseableHttpClient httpclient = HttpClients.createDefault();

to

CloseableHttpClient httpclient = HttpClientBuilder.create()
.setSSLSocketFactory(SSLConnectionSocketFactory.getSystemSocketFactory())
.build();
the problem is solved.

How can I find a similar solution in keycloak adapter? Can you help me to set TLS1.2 by Keycloak Client Adapter properties or to configure keycloak to use the systemsocketfactory?

I'm attaching server log where you can find ssl conversation and ConnectionReset error.

### Version

16.1.0

### Expected behavior

Keycloak adapter should use Default Socket Factory using TLS configuration from the system

### Actual behavior

Keycloak adapter uses its configuration and I cannot find a way to set TLS1.2 support by keycloak.json configuration or by java system properties values 

### How to Reproduce?

Try to configure a simple Web Application using Keycloak Servlet Filter adapter to call a Keycloak installation exposed by a TLS1.2 compliant host
[logs_github.txt](https://github.com/keycloak/keycloak-documentation/files/7880150/logs_github.txt)

**Comment by patrickjennings** [comment]
Moving this to the backlog as adapters are deprecated and there is not as much focus on them at the moment, PRs are certainly welcome to fix this issue.
