### ISSUE TITLE
Priority not sent to server when adding new RSA key provider

### ISSUE THREAD

**Issue by shanloid** [keycloak/keycloak#19155]
### Describe the bug

I am trying to add a new RSA key provider with my own private key and certificate. I would like to set the priority of the new provider to be 101, to ensure that it is prioritized above other providers.

Attempting this via the admin UI:

![Screen Shot 2023-01-29 at 3 18 50 pm](https://user-images.githubusercontent.com/1029384/215306902-bd8d2af1-3475-4ab8-bb83-9f1967c0c788.png)

When I hit save, this is the payload that gets sent to the server:

```json
{
  "config": {
    "privateKey": ["MIIEvwI..."],
    "certificate": ["MIICp..."],
    "priority": ["0"],
    "enabled": ["true"],
    "active": ["true"],
    "algorithm": ["RS256"]
  },
  "name": "rsa",
  "providerId": "rsa",
  "providerType": "org.keycloak.keys.KeyProvider"
}
```

The priority field is being sent to the server as `0`, not `101`.

Additionally, after saving the new provider, the UI shows it as being both disabled and inactive, even though the JSON response from the server lists it as enabled and active:

![Screen Shot 2023-01-29 at 3 35 45 pm](https://user-images.githubusercontent.com/1029384/215307244-0b067efd-f31c-4709-a9ad-030e4fe00e96.png)

Response from API:

```json
{
        "id": "a071c0ad-8d6e-4d54-9a9f-b82b5ed4fdbb",
        "name": "rsa",
        "providerId": "rsa",
        "providerType": "org.keycloak.keys.KeyProvider",
        "parentId": "5959757e-75d4-40be-9154-bdfb0186054b",
        "config": {
            "privateKey": [
                "**********"
            ],
            "certificate": [
                "MIICpD..."
            ],
            "active": [
                "true"
            ],
            "priority": [
                "0"
            ],
            "enabled": [
                "true"
            ],
            "algorithm": [
                "RS256"
            ]
        }
    }
```

### Version

20.0.3

### Expected behavior

I would expect the frontend to send the correct priority of 101 to the REST API, and for the subsequent call to the API to query for all key provider components to return my new RSA provider with a priority of 101. I would also expect the provider to be displayed as both enabled and active.

### Actual behavior

Priority field is not sent correctly to the REST API. UI does not reflect enabled and active state of newly-created provider.

### How to Reproduce?

Under "Realm settings" > "Keys" > "Providers", add a new RSA provider with a non-zero priority, hit save, and then view the network traffic to see the JSON sent to the server. Also observe that the UI does not reflect the enabled or active status of the new provider.

**Comment by edewit** [comment]
This is not a bug but a new feature, the idea is that by changing the order in the list the priority is updated
![Screencast from 2023-03-21 13-45-19](https://user-images.githubusercontent.com/51133/226610420-16d0dd0a-556a-4991-9068-f8e95a9a66f0.gif)

**Comment by edewit** [comment]
we could change the backend because the detail screen is generated by the server

**Comment by mattock** [comment]
> This is not a bug but a new feature, the idea is that by changing the order in the list the priority is updated

So how would I change the priority programmatically? In my use-case clicking in the console is not an option - we'd have to do that once for every realm every time the key is changed, and we have plenty to of realms.
