### ISSUE TITLE
Target IDP initiated SSO URL has admin keycloak_url, not the main login url

### ISSUE THREAD

**Issue by cslovell** [keycloak/keycloak#19153]
### Describe the bug

Our Keycloak is configured to have one subdomain for the admin interface, and another for the main user authentication. 

We are attempting to configure a saml provider, and we are configuring "IDP Initiated SSO URL Name". However, the "Target IDP initiated SSO URL" generated from this contains the admin url, not the login url, and changing "Root URL" and hard-coding "Base URL" doesn't change anything. 

The documentation doesn't make it clear how to override this to ensure the Target IDP initiated SSO URL is correct.

### Version

18.0.2

### Expected behavior

What we want: "https://id.our-domain.com/realms/our-client/protocol/saml/clients/the-client-we-are-configuring"

This value is configured using "KC_HOSTNAME" environment variable.

### Actual behavior

What we see: "https://admin.our-domain.com/realms/our-client/protocol/saml/clients/the-client-we-are-configuring"

This is the value configured in the environment variable "KC_HOSTNAME_ADMIN"

### How to Reproduce?

For reproduction purposes, we are following more or less the guidelines here: https://scandiweb.com/blog/sign-in-to-amazon-aws-using-saml-protocol-and-keycloak-as-identity-provider/

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .
