### ISSUE TITLE
Direct Naked Impersonation section contains misleading image

### ISSUE THREAD

**Issue by dreamcrash** [keycloak/keycloak#19157]
### Description

In the section [6.1. Granting permission for the exchange](https://www.keycloak.org/docs/latest/securing_apps/#granting-permission-for-the-exchange-3) the image 
![Client Policy Creation](https://www.keycloak.org/docs/latest/securing_apps/images/exchange-users-client-policy.png) \

talks about a Client Policy Creation but shows a User Policy.

I would expect something like:

![](https://i.stack.imgur.com/BHohW.png)

**Comment by edewit** [comment]
I'm sorry @dreamcrash but what is the difference between the two images?

**Comment by dreamcrash** [comment]
@edewit It seems that the image location has changed and now it looks like I have update the same image. Either this or I made a mistake and uploaded the same image.
