### ISSUE TITLE
token-exchange does apply clientScopes of the origin client

### ISSUE THREAD

**Issue by JulianMetzger** [keycloak/keycloak#19183]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

The token exchange between an origin-client and a target-client uses the clientScopes of the origin client for token claim mapping, if the dynamic-scope feature is enabled. 
Hence, the custom claims of the tokens are set as defined in the origin-client. All clientScopes and connected protocolMappers/scopes of the target-client are ignored. 

May be connected to #17220

### Version

21.0.1

### Expected behavior

token contains claims from target-client
```
{ 
  "aud":` "target-client",
  "azp": "origin-client",
  "target-client": "target-client"
}
```

### Actual behavior

token contains claims from origin-client
```
{ 
 "aud": "target-client",
  "azp": "origin-client",
  "origin-client": "origin-client" <- claim from dedicated-origin-client clientScope
}
```

### How to Reproduce?

Enabled features to reproduce
- DYNAMIC_SCOPES
- TOKEN_EXCHANGE
- ADMIN_FINE_GRAINED_AUTHZ

Steps
- Two clients with a token exchange policy from origin client to target client (https://www.keycloak.org/docs/latest/securing_apps/#_client_to_client_permission)
- Add different ProtocolMapper for the dedicated clientScope of both realms (hard coded claim as example).
- Retrieve token for origin-client.
- Issue a token-exchange with the accessToken of the origin-client with requested_token_type=urn:ietf:params:oauth:token-type:access_token to the token-api
- only the origin-client claim is present, while the target-client claim is absent

### Anything else?

If one enables the DYNAMIC_SCOPES feature in https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java#L84, the testExchangeFromPublicClient will fail with a mismatch between the clientIds (expected: target, actual: realm-management). 
![Bildschirmfoto 2023-03-20 um 16 19 28](https://user-images.githubusercontent.com/65015434/226387867-992fd085-6240-4b84-8713-0f479f8f669b.png)

In these code snipets the clientModel of the origin client is used during the token exchange. A suggestion for a fix is to use the client of the authenticationSession instead of the client of the session here @dgozalo :
* https://github.com/keycloak/keycloak/blob/9db7c8fb34146a3726a085bd18e25c6c1a731f8a/services/src/main/java/org/keycloak/services/util/AuthorizationContextUtil.java#L68
* https://github.com/keycloak/keycloak/blob/9db7c8fb34146a3726a085bd18e25c6c1a731f8a/services/src/main/java/org/keycloak/protocol/oidc/rar/parsers/ClientScopeAuthorizationRequestParserProviderFactory.java#L35

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by JulianMetzger** [comment]
Thanks for your Response.
I could reproduce the bug with keycloak version 21.0.2. Running the ClientTokenExchangeTest test with enabled dynamic-scope feauture still applies the wrong clientScopes. 
![Bildschirmfoto 2023-04-14 um 16 30 17](https://user-images.githubusercontent.com/65015434/232077578-01dafb68-b6ed-4841-8e13-80aefe815608.png)
The suggested PR only passes the authSession Client to the [ClientScopeAuthorizationRequestParser](services/src/main/java/org/keycloak/protocol/oidc/rar/parsers/ClientScopeAuthorizationRequestParser.java) instead of using the current ClientModel of the session and should therefore be minimal invasive. 
Maybe you could take a look, otherwise thanks for adding the issue to the Backlog.
