### ISSUE TITLE
Upgrade from 20.0.5 to 21.0.1 - throws certificate error

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [keycloak/keycloak#19185]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I upgraded my Keycloak image yesterday from 20.0.5 to 21.0.1 and got the following error

```log
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	... 20 more
Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1573)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1498)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1442)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 32 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA
	at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1569)
	... 35 more

```

### Version

21.0.1

### Expected behavior

Keycloak should be deployed successfully with no errors on 21.0.1

### Actual behavior

See errors below:

```log
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	... 20 more
Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1573)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1498)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1442)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 32 more
Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA
	at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1569)
	... 35 more

```

### How to Reproduce?

Setup - I am currently running Keycloak in Kubernetes with Let's Encrypt as a service

My Let's Encrypt certificate is coming from the standard jetstack/cert-manager with the standard configuration, if I need to go more into that I can.

When I inspect the certificate in OpenSSL

```bash
> $ openssl x509 -in tls.crt -text -noout

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:22:3a:9b:28:db:2d:c4:cb:cc:ab:c4:99:ec:a7:c2:a4:fe
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=R3
        Validity
            Not Before: Mar 15 01:10:26 2023 GMT
            Not After : Jun 13 01:10:25 2023 GMT
        Subject: CN=<custom cn here>
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:a5:b7:db:98:f1:17:9c:69:c7:3a:ba:12:2e:a6:
                    a2:d7:c5:cf:d5:8a:0b:81:9b:c1:f1:d2:26:87:48:
                    b8:45:b2:81:73:ec:b4:62:64:bf:f0:5a:54:f2:8e:
                    17:5a:33:b3:b8:43:3b:b2:7a:56:25:e0:f8:89:a6:
                    a5:62:bb:53:29:7c:5e:62:5c:aa:29:56:a8:bb:ae:
                    02:85:38:d7:8a:33:c7:12:29:b5:f3:f0:94:89:5d:
                    ee:e4:cb:fd:cb:ac:cc:5c:1d:27:fa:bb:33:0d:d3:
                    51:bc:41:59:b4:04:90:27:11:9c:a9:0f:fa:71:8a:
                    30:80:5b:c3:48:ef:99:b6:c2:ae:9c:97:c0:22:e9:
                    86:4a:a6:82:4e:01:a9:df:37:e3:0a:cf:a6:27:33:
                    f9:1d:7a:9d:44:76:45:0f:f6:e8:6b:24:93:39:48:
                    95:fa:f4:8a:19:df:0a:3e:5c:21:f7:f6:32:c2:53:
                    f4:20:89:e4:db:84:69:f6:99:7d:38:3f:18:4d:6e:
                    2d:a5:07:3e:af:4b:86:5b:3c:ef:64:4e:d7:be:68:
                    24:fe:2d:9d:27:18:90:25:43:ee:de:24:f2:4d:6d:
                    6d:a9:3b:cd:ea:e2:7c:14:eb:9b:7e:8a:e9:15:cf:
                    16:bd:8d:8a:68:ae:78:65:97:cd:f7:1e:c1:77:1e:
                    87:7f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                39:61:C7:39:29:D0:C8:5C:2B:04:93:A1:6B:A3:EB:3B:C5:3A:5E:65
            X509v3 Authority Key Identifier:
                keyid:14:2E:B3:17:B7:58:56:CB:AE:50:09:40:E6:1F:AF:9D:8B:14:C2:C6

            Authority Information Access:
                OCSP - URI:http://r3.o.lencr.org
                CA Issuers - URI:http://r3.i.lencr.org/

            X509v3 Subject Alternative Name:
                DNS:<alt cn here>
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            1.3.6.1.4.1.11129.2.4.2:
....M;..H`.x...v45\P.r.....!.....;.c+...........%.o..t....i...w.z2.T..-. .8.R....p2..M;.+.:W.R.R......q%.....H0F.!....FOg.....@G......W@J.).....EV..!..\...elh;0.<T..|...,2@4e..~]MB..
    Signature Algorithm: sha256WithRSAEncryption
         8d:a5:04:65:83:4b:45:e2:f9:33:41:16:1d:f8:20:0c:13:b2:
         a7:c1:59:5f:61:c2:49:66:29:65:2b:20:53:9d:3c:f9:ce:00:
         f5:44:85:30:91:68:60:04:4e:de:16:91:db:98:20:6f:00:89:
         e7:a7:1b:bb:2a:31:c9:f3:29:9c:80:f2:d5:96:0d:f6:96:6d:
         61:c1:f6:eb:80:8a:9f:ec:dd:15:b2:62:34:41:40:36:b5:f6:
         93:5d:d4:96:af:aa:af:7b:64:f0:d8:cb:f1:b4:fc:74:8f:32:
         d9:e1:55:ac:bd:87:53:b1:f2:e0:84:30:89:bf:c3:bb:26:4b:
         43:9b:26:6a:00:d0:69:d6:30:fe:6d:be:fe:d0:f3:39:a6:52:
         4c:dc:fd:81:1e:ec:54:d9:27:9c:3c:88:67:1c:11:9c:2c:fa:
         19:33:21:5f:44:6e:6d:c9:91:4f:80:dc:72:07:ce:3c:f3:d5:
         9b:bf:0d:89:81:f2:8b:02:32:85:91:d7:1b:a0:87:37:ba:5e:
         76:bb:f2:48:ad:93:85:3b:88:04:1e:ea:c3:d9:56:34:73:b3:
         c0:6d:d3:f1:f5:8f:47:91:70:05:da:52:da:af:8f:a1:67:e3:
         69:27:4e:7c:77:fe:8e:86:7c:b4:46:92:ed:a7:57:de:67:c7:
         7d:40:44:db
```

### Anything else?

Customized image for Keycloak
```dockerfile
# Documentation:
#  https://www.keycloak.org/server/containers
ARG KEYCLOAK_VERSION

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION as builder

# Configure postgres database vendor
ENV KC_DB=postgres

ENV KC_FEATURES="token-exchange,scripts,preview"

WORKDIR /opt/keycloak

RUN /opt/keycloak/bin/kc.sh build --cache=ispn --cache-stack=kubernetes --health-enabled=true --metrics-enabled=true

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

**Comment by rmartinc** [comment]
@ZinkNotTheMetal My feeling here is that some certificate in you setup is using SHA1withRSA which is not allowed by the jdk configuration. For the stacktrace it can be the certificate in the postgresql database (or in its chain). Try using plain jdbc connection or relaxing the disabledAlgorithms in the java.security file. But don't know why this is happening with version 21.0.1 and not with 20.0.5.

**Comment by ZinkNotTheMetal** [comment]
I am attaching that same certificate in the container. I can look into relaxing the disabledAlgorithms but as you said. It is very odd that it works in the previous version but not this one. Was there more additional certificate restrictions added in this release?

**Comment by mposolda** [comment]
@ZinkNotTheMetal Can you confirm if the workaround mentioned above (adding SHA1 algorithm to `java.config` file) helps to you?

It's very likely that during upgrade to later version, the `SHA1` was removed intentionally (for security reasons). In that case, Keycloak should adjust to that and not support by default the legacy algorithms, which were intentionally removed. We can possibly improve the documentation around this. But overally, it is recommended to update certificates/keys to newer algorithms (or as a workaround, add algorithms back to `java.config`)).

@rmartinc What is your opinion on this?

**Comment by mposolda** [comment]
Adding to Backlog for now, as this is not a blocker for Keycloak 22

**Comment by nxadm** [comment]
While I applaud the security aspect of the change, it is nevertheless a breaking change. There are (at least) two cases where the new jdk default will break existing Keycloak installations:
- while you don't want to connect to services with sha1 certificates, you may connect to services you don't control (cloud examples in this thread).
- sha1 self-signed certs of SAML clients (self-signed is best practice because the CA is not checked in SAML). We are not talking about connections (handshaking, encryption), but about the **contents** of requests and responses. You can replace them, but you need to coordinate that with the clients.

Although this was not a decision made by the Keycloak devs, but rather a consequence of the jdk version update, it would be idea to provide a switch and/or environment variable to disable the new behaviour, at least temporarily.

**Comment by fouringiz** [comment]
we are experiencing the same issue connecting to Azure Database for MySQL using keycloak in a docker container container.
any advice to fix it?

**Comment by tsaarni** [comment]
SHA1 seems to be deprecated [since JDK9](https://bugs.openjdk.org/browse/JDK-8149555) but RHEL8 enabled it back in the crypto-policies package.  Keycloak 21 container seems to be based on RHEL9, RHEL9 deprecated SHA1 - possibly described [here](https://access.redhat.com/articles/6846411).

**Comment by simeonlin** [comment]
> Adding to Backlog for now, as this is not a blocker for Keycloak 22

Is this really true?
I have the same issue with Keycloak 22 (f.e. Keycloak 22.0.5).

**Comment by simeonlin** [comment]
Workaround also helps in Keycloak 22.0.5. (I had the same Issue while Connecting to a MySQL running on Azure.)

I tested the workaround with the following "Hack" in my Keycloak-Dockerfile:  

```
# Ensure Permission to change /etc/crypto-policies/back-ends/java.config
USER root
# Remove SHA-1 from the disabled-List
RUN   sed -i "s|MD2, SHA1, MD5|MD2, MD5 |g" /etc/crypto-policies/back-ends/java.config
```

**Comment by kkcmadhu** [comment]
i too face this issue after we move our db to flexi server mysql in azure..
if the ssl is disabled thigs works fine. this needs some resolution.
either  add the algoback, or every one agrees upon that keycloak will not support the

**Comment by stianst** [comment]
I don't think there's anything we can or want to do here to be honest.

**Comment by rmartinc** [comment]
Yes, this is probably triggered by [JDK-8269039](https://bugs.openjdk.org/browse/JDK-8269039) which disabled the SHA1 for signed jars and certpath. Check also the jdk 17 [release notes](https://www.oracle.com/java/technologies/javase/17all-relnotes.html#R17_0_5). When the JDK in the image was updated this issue started to happen. As commented the JDK configuration in the image should be relaxed to allow SHA1 again (there are several pages pointing to this, for example [this one](https://www.answeroverflow.com/m/1138576335032291368)). This is really something not relate to keycloak codebase but to a JDK upgrade in the image. My vote is to close this as not planned.

**Comment by shawkins** [comment]
Based upon the comments of @rmartinc and @stianst we don't need to leave this open. Users will need to migrate or use a workaround like was documented in https://github.com/keycloak/keycloak/issues/19185#issuecomment-1795341017

**Comment by Rohi-spark** [comment]
I am getting error as file not found. @aalexiev42 
`cannot stat '/etc/crypto-policies/back-ends/java.config': No such file or directory`
