### ISSUE TITLE
Missing Display Name for Resources and Scopes Pages in Client Authorization

### ISSUE THREAD

**Issue by wojja** [keycloak/keycloak#19200]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The display name of resources and scopes is currently not shown in the "Resources" and "Scopes" tabs of the Client Authorization UI. Instead, the technical name is used. As far as I can see, the display names are not used at all in the UI.

### Version

21.0.1

### Expected behavior

The display name of resources and scopes is shown in the "Resources" and "Scopes" tabs of the Client Authorization UI.

### Actual behavior

The technical name of resources and scopes is shown in the "Resources" and "Scopes" tabs of the Client Authorization UI.

### How to Reproduce?

Create some rescources and scopes in the Client Authorization UI of any client with enabled authorization management. Specify a technical and a display name for those rescources and scopes. Observe that the rescources and scopes are listed by the technical names instead of the display names in the "Resources" and "Scopes" tabs.

### Anything else?

This problem was already reported in 2018 in the mailing list: https://lists.jboss.org/pipermail/keycloak-user/2018-October/015732.html

**Comment by edewit** [comment]
what is the "Client Authorization UI"?

**Comment by wojja** [comment]
It's under Clients/[client]/Authorization/Resources and Clients/[client]/Authorization/Scopes.

![Client Authorization UI](https://user-images.githubusercontent.com/61585821/226562214-bc8cd1d2-bd39-4df6-9a1b-9dfe85bb7e17.png)

**Comment by edewit** [comment]
okay but where do you expect the display name to be shown, I thought it was for something external to the admin UI itself

**Comment by edewit** [comment]
quoting the help on the field: "A user-friendly name for the resource, mainly used when rendering user-facing forms. It supports internationalization so that values can be loaded from message bundles."
