### ISSUE TITLE
Typo "Webauthn" (no capital "A") 

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#19216]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

When looking in the UI for "Authentication" -> "Required Actions", the "WebAuthn" is misspelled.

![image](https://user-images.githubusercontent.com/3957921/226652543-90e18b10-ea24-433e-81d8-701700139fb8.png)

### Version

nightly

### Expected behavior

It should be "WebAuthn"

### Actual behavior

It shows "Webauthn"

### How to Reproduce?

Open the admin UI and choose "Authentication" -> "Required Actions".

### Anything else?

Search the codebase for the following (including quotes): 

```
"Webauthn Register"
"Webauthn Register Passwordless"
=Webauthn Register
```

Matches found in `messages_en.properties`, `DefaultRequiredActions.java`, `WebAuthnRegisterFactory.java`, `WebAuthnPasswordlessRegisterFactory.java`.

There are also occurrences in `webauthn.adoc` and `flows.adoc`. Fix text for `webAuthnPolicyPasswordlessFormHelp` in `authentication-help.json`. 

There is a table `required_action_provider` which contains the name of the providers which might needs to be updated. 
Don't know why the name is there, when it can be read from the factory?

**Comment by mposolda** [comment]
Adding to Backlog for now as it is not a blocker for Keycloak 22. But we may try to fix it...

It sounds like easy effort, but there can be slightly more work than it's looking at the first view (for example WebAuthn related tests may start to fail when labels are changed etc). Also we should likely doublecheck documentation when we do it to make sure it is changed on all places (not sure whether also update screenshots in the docs etc...)

**Comment by christian-2** [comment]
@mposolda I may make a stab at this in order to get more familiar with the code base. Could you please indicate more precisely (or provide a pointer to) what tests you had in mind. (Is this about [`mvn -f testsuite/utils/pom.xml exec:java -Pkeycloak-server`](https://github.com/keycloak/keycloak/blob/main/docs/building.md)?) I would then keep a close eye on those tests as I would introduce changes in a local clone (in preparation for a PR).

**Comment by jonkoops** [comment]
@christian-2 sounds like a good idea, feel free to open up a PR so we can discuss it.

**Comment by christian-2** [comment]
@jonkoops FYI so I have started by running a build and tests on a clean fork. I am facing hurdles there as described in discussion #20376.
