### ISSUE TITLE
Attributes cannot be deleted through admin console anymore

### ISSUE THREAD

**Issue by twwd** [keycloak/keycloak#19243]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

It is no longer possible to remove attributes from users via the admin console since the changeover to admin2. The frontend behaves incorrectly, does not update its model and therefore also sends the actually deleted attributes with the REST call. The behaviour can be reproduced at least with Firefox (111, 112) and Chromium (111). 

[keycloak-admin-ui-attribute-removing.webm](https://user-images.githubusercontent.com/8222565/226918300-0ce14088-4695-4fba-93cc-c1a404ec8d4c.webm)

### Version

21.0.1

### Expected behavior

The attribute that was removed through the minus button is actually removed after pressing _Save_.

### Actual behavior

The attribute is not removed and stays the same.

### How to Reproduce?

- Login to Keycloak admin console
- Go to users
- Go to an arbitrary user or create a new one
- Add an attribute
- Press _Save_
- Remove this attribute
- Press _Save_

**Comment by twwd** [comment]
Sorry, this is a duplicate of https://github.com/keycloak/keycloak/issues/17454

**Comment by RogiervR** [comment]
@twwd This bug still occurs on my keycloak page in version 21.0.1, is this already fixed or still in progress?

**Comment by twwd** [comment]
@RogiervR as mentioned in https://github.com/keycloak/keycloak/issues/17454, it's only fixed in `HEAD` (latest nightly). The fix is not released yet.
