### ISSUE TITLE
Mvnd fails when building Keycloak

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#19247]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Describe the bug

When building Keycloak with mvnd (Apache Maven Daemon) the build fails with error when creating documentation distribution.

### Version

main

### Expected behavior

Parallel builds should succeed.

### Actual behavior

Build fails with following error

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (assemble) on project keycloak-documentation: Failed to create assembly: Error creating assembly archive docs-dist: You must set at least one file. -> [Help 1]
```

### How to Reproduce?

```console
mvnd clean install -DskipTestsuite -DskipExamples -DskipTests
```

or

```console
mvn -T4C clean install -DskipTestsuite -DskipExamples -DskipTests
```

### Anything else?

It seems missing dependencies cause the failures when using parallel build. `docs/documentation` is the first, but not the only one.

For example, Keycloak Documentation dist `<artifactId>keycloak-documentation</artifactId>` fails because documentation was not yet generated to `docs/documentation/target/` at the time of execution.

**Comment by tsaarni** [comment]
Also the new admin ui fails to compile randomly due to dependencies not being registered between the js modules

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm-ci) on project keycloak-js-adapter-jar: Failed to run task: 'npm ci --ignore-scripts' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 239 (Exit value: 239) -> [Help 1]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm-ci) on project keycloak-js-adapter: Failed to run task: 'npm ci --ignore-scripts' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 254 (Exit value: 254) -> [Help 1]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm-build) on project keycloak-admin-ui: Failed to run task: 'npm run build --workspace=admin-ui' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm-ci) on project keycloak-js-admin-client: Failed to run task: 'npm ci --ignore-scripts' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 254 (Exit value: 254) -> [Help 1]
```

**Comment by abstractj** [comment]
Thank you for bringing this to our attention. Please note that we don't provide support for `mvnd`. As for Maven, I've tested with the provided command and couldn't reproduce the issue:

```
mvn -T4C clean install -DskipTestsuite -DskipExamples -DskipTests
```

I suggest fetching the most recent updates from our repository and testing again. If the problem continues, feel free to provide more details and reopen this issue.

**Comment by tsaarni** [comment]
Actually, someone must have fixed those broken dependencies since `mvnd` has been working perfectly as well recently 😄
