### ISSUE TITLE
Admin-UI does not show all custom attributes of Authorization Resource

### ISSUE THREAD

**Issue by pboehm** [keycloak/keycloak#19254]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The Admin UI does not show all assigned custom attributes of an Authorization Resource, especially it only shows empty input fields for the "first" attribute. Please refer to the screenshots below where the resource has attributes `attr-1`, `attr-2` and `attr-3` but only `attr-2` and `attr-1` are displayed correctly, while there are empty input fields for `attr-3`.

![Bildschirm­foto 2023-03-22 um 17 23 50](https://user-images.githubusercontent.com/665684/226973734-3654073b-c68b-4f8e-9694-509f8812090c.png)

### Version

21.0.1

### Expected behavior

All existing resource attributes are shown with their correct value and the empty input field are only shown once for creating new attributes.

### Actual behavior

For one of the existing resource attributes the attribute key and value are not shown correctly, empty input fields are shown instead.

### How to Reproduce?

* create a new realm `test`
* within the realm create a client `test` and enable `Authorization`
* open the detail page for the `Default Resource`
* add 3 attributes `attr-1`, `attr-2` and `attr-3` with any value and click save
* reload the page
* one of the newly created attributes is not shown correctly, empty input fields are shown instead

**Comment by ssilvert** [comment]
I have reproduced this.  We will fix it soon.

**Comment by xianli123** [comment]
Hi @pboehm, thanks for your issue. As for this feature, I wonder if this feature has a case where a key can have multiple values as described in another issue #18028 (https://github.com/keycloak/keycloak/issues/18028).

**Comment by pboehm** [comment]
Hi @xianli123, I currently do not use multi-value attributes for authz resources. But I can confirm that the current UI does not handle multi-value attributes for authz resource correctly:

![image](https://user-images.githubusercontent.com/665684/228820496-9f874787-d360-4a69-9202-bc1340c22a06.png)

The resource has the correct attributes (two values for each attribute) but no attributes are shown the UI.

**Comment by pboehm** [comment]
@jonkoops thanks a lot!
