### ISSUE TITLE
Operator ignores KC_PROXY value resulting in it being duplicated

### ISSUE THREAD

**Issue by beejaygee** [keycloak/keycloak#19266]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

Using Keycloak Operator 21.0.1 ignores KC_PROXY value resulting in it being duplicated. When setting "KC_PROXY" to "reencrypt".

If I use the config:

  additionalOptions:
    - name: KC_PROXY
      value: reencrypt

The Statefulset is created as: 

      KC_PROXY:                        passthrough
      KC_KC_PROXY:                     reencrypt

If I set my manifest to:
  additionalOptions:
    - name: PROXY
      value: reencrypt

then Statefulset is set to:
      KC_PROXY:                        passthrough
      KC_PROXY:                        reencrypt

### Version

21.0.1

### Expected behavior

Using manifest options of:

  additionalOptions:
    - name: KC_PROXY
      value: reencrypt
      
Results in Statefulset being created as:

      KC_PROXY:                        reencrypt

### Actual behavior

  Using manifest options of:
  
  additionalOptions:
    - name: KC_PROXY
      value: reencrypt

The Statefulset is created as: 

      KC_PROXY:                        passthrough
      KC_KC_PROXY:                     reencrypt

### How to Reproduce?

Add to the end of k8s manifest:

  additionalOptions:
    - name: KC_PROXY
      value: reencrypt

**Comment by beejaygee** [comment]
Okay but how do I define that configuration in the Keycloak Operator so that my Keycloak cluster runs with proxy=reencrypt? I don't see any way in the Operator to define commandline start options? The links you've provided only discuss Keycloak and don't mention how I would apply this configuration via the Keycloak Operator.

**Comment by Pepo48** [comment]
Hi @beejaygee,

have you got a chance to go through this guide[1]?

[1] https://www.keycloak.org/operator/customizing-keycloak

**Comment by vmuzikar** [comment]
@beejaygee You should be able to override the proxy value as:
```taml
additionalOptions:
   name: proxy
   value: reencrypt
```

I was also curious about why do you need to override it. We are not exposing the proxy as a first-class citizen field as it currently does not make much difference which value you set in K8s environment (apart from `none`).

**Comment by beejaygee** [comment]
> Hi @beejaygee,
> 
> have you got a chance to go through this guide[1]?
> 
> [1] https://www.keycloak.org/operator/customizing-keycloak
There's not much information on that page. Am I supposed to build a custom Keycloak container image and hardcode the setting directly into the container?

> @beejaygee You should be able to override the proxy value as:
> 
> ```
> additionalOptions:
>    name: proxy
>    value: reencrypt
> ```
> 
> I was also curious about why do you need to override it. We are not exposing the proxy as a first-class citizen field as it currently does not make much difference which value you set in K8s environment (apart from `none`).

Sorry, I'm confused, why wouldn't it make a difference? I'm trying to use a reverse proxy (Traefik) with Keycloak and wish to use end-to-end SSL. Therefore it makes sense to use the reencrypt option rather than the edge option which, as I understand it, does SSL offload. If this is incorrect could you please advise. Thanks.

**Comment by vmuzikar** [comment]
Sorry about the confusion, I agree it might not be clear at the first sight.

The Operator currently [uses `passthrough`](https://github.com/keycloak/keycloak/blob/19ee00ff545d0c6cb68079849b5f18188f38928c/operator/src/main/java/org/keycloak/operator/Constants.java#L46) as the default. For your use-case (end-to-end SSL) it should be ok at the moment as Keycloak does not make currently any difference between `passthrough` and `reencrypt`. That's also the reason why it's not exposed in the Keycloak CR as the Operator knows the current default settings is correct. However, if you still wish to override it, you can:
```yaml
additionalOptions:
   name: proxy
   value: reencrypt
```
