### ISSUE TITLE
Cannot import KC20 realm export with KC21

### ISSUE THREAD

**Issue by ThijsBroersen** [keycloak/keycloak#19269]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

Our realm exports (made with KC20) cannot be imported with KC21. Error shown is 
```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cannot read the array length because "<local8>" is null
```
used command arguments: 
```
command:
      - 'start-dev'
      - '-Dkeycloak.import=/tmp/realms/myrealm.json'
      - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
```

### Version

21.0.1

### Expected behavior

KC20 realm exports should be imported correctly by KC21

### Actual behavior

KC20 realm exports fail to import and container crashes.

### How to Reproduce?

create new realm with KC 20.0.5, export via realm-settings -> partial export -> menu (include groups and roles, include clients)
import the export in the same way as explained in the bug description.

**Comment by kenrickles** [comment]
Hello there! I am also facing the same issue. 
I have tested manually importing the realm via uploading the GUI works just fine. 
However, when I am trying to mount a config map and then importing via cli does not work.

**Comment by jeremy-soh-partior** [comment]
Facing the same issue as well. We are trying to move to 21.0.1 (and onwards) to resolve a major security vulnerability. Due to this functional bug, it leaves us no choice but to stick with vulnerable version of Keycloak at the moment. We appreciate a prompt response to this issue. Thank you!

**Comment by sguilhen** [comment]
Running `kc.sh import --file path_to_exported_file` should work (tested on KC 21.0.2) to import the realm exported in a previous version.

**Comment by pedroigor** [comment]
Is there any reason why you are not using the `import` command or the import at startup? See https://www.keycloak.org/server/importExport.

**Comment by miguoliang** [comment]
Hello there! I am also facing the same issue.
I run keycloak 21 in container, and I have to import a realm when it startups because of automated testing.

**Comment by miguoliang** [comment]
> Hello there! I am also facing the same issue. I run keycloak 21 in container, and I have to import a realm when it startups because of automated testing. But keycloak 20 works.

It is caused by line seperator I guess. Maybe the script file uses CRLF as its line separator.

**Comment by kenrickles** [comment]
Hi @ThijsBroersen @miguoliang,

My colleague found the error and looked through Keycloak's code.  

The parameter -Dkeycloak.import now expects a directory instead of a file. It will loop through all the .jsonfiles in the said directory and import the realms. 

Assign to -Dkeycloak.import the path of the folder containing the realm to be imported instead of a file name and it will work fine.


Thanks @sguilhen @pedroigor for your kind inputs.
