### ISSUE TITLE
required actions update user locale & delete account showing up twice in admin panel after update to 21

### ISSUE THREAD

**Issue by sboetzel-ewc** [keycloak/keycloak#19260]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

After upgrading an older realm to v21, "update user locale" and "delete account" shows up twice in admin panel. It's probably related to issue [17277](https://github.com/keycloak/keycloak/issues/17277).

Like with the terms and conditions I updated the required_action_provider table so everything is in uppercase, both "alias" and "provider_id" column. Restarted keycloak, terms and conditions prob is fixed, but update user locale still shows up twice. Same for delete account

![image](https://user-images.githubusercontent.com/107465441/227038402-877987a2-0113-41e4-b09c-b5b240a801e4.png)

### Version

21

### Expected behavior

It should only show once

### Actual behavior

It shows twice, this also messes up the react ui when you click on on / off.

### How to Reproduce?

import a realm created with keycloak<21 into keycloak 21

**Comment by mposolda** [comment]
@sboetzel-ewc Could you please add what DB you're using (including version and possibly JDBC driver - if you know it)?

@hmlnarik @mhajas I am re-assigning to "store" as it looks like store related issue (Maybe also related to https://github.com/keycloak/keycloak/issues/17277 and https://github.com/keycloak/keycloak/issues/9991)? Let me know if you think otherwise.

**Comment by mhajas** [comment]
@sboetzel-ewc The issue #17277 is only related to T&C required action. Required actions "update user locale" and "delete account" should not be changed to upper-case.

Do I understand correctly you renamed these two to upper-case and after it you are experiencing the issue? Or you experienced some issues with these two even before you changed it? 

I would suggest to revert the changes to required actions other than T&C.

**Comment by hmlnarik** [comment]
I am closing this issue.
@sboetzel-ewc Feel free to reopen with the requested information.
