### ISSUE TITLE
Pagination doesn't work on Client > Authorization tab

### ISSUE THREAD

**Issue by Hdz** [keycloak/keycloak#19271]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If we have more than 10 resources, only the first 10 are shown. The same is true for the other sub-tabs. Navigation arrows are disabled, and a page size chooser doesn't work as well: there is no reaction when we switch to "20 per page" or any other value.
Pagination works when you filter by client, but not when we filter on realm roles.

### Version

21.0.1

### Expected behavior

Load the others roles that goes after 10.

### Actual behavior

Doesn't load the other roles

### How to Reproduce?

Migrating from keycloak 18.0.0 to  21.0.1.
Get more than 10 realm roles. 

![CaptureGITHUB](https://user-images.githubusercontent.com/2638430/227186043-a4a4674a-e444-4813-a7c0-c0613fad13d3.png)

This is the same issue than some people previously had : #18319

**Comment by ssilvert** [comment]
This should be fixed now.  Have you tried it on the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly
