### ISSUE TITLE
Error on starting keycloak when foldername contains ")" using kc.bat. 

### ISSUE THREAD

**Issue by AmsalkhirAli** [keycloak/keycloak#19294]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Starting Keycloak in a folder containing closing bracket:")" generates the following Error:
`\keycloak-999.0.0-SNAPSHOT\bin\.." -Djboss.server.config.dir="C:\Program was unexpected at this time.`

### Discussion
[#19219](https://github.com/keycloak/keycloak/discussions/19219)

### Version

20.0.5

### Expected behavior

Being able to start Keycloak in a folder containing a bracket. The goal is to be able to run from a folder like **\Program Files (x86)\**..

### Actual behavior

Starting Keycloak in a folder containing closing bracket:")" generates the following Error:
`\keycloak-999.0.0-SNAPSHOT\bin\.." -Djboss.server.config.dir="C:\Program was unexpected at this time. 

### How to Reproduce?

add a closing bracket ")" in the folder containing keycloak, and try to start it using kc.bat start

**Comment by shawkins** [comment]
This and #19831 should be related to the issues identified with the .bat handling of special characters in @rmartinc initial pr for #22337
