### ISSUE TITLE
Use Undertow server as default app server for adapter testing and Quarkus 3 

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#19299]
### Description

At this moment, for Quarkus 3, we use `app-server-wildfly` in order to properly execute adapter tests. This approach was preferred due to a fact we need to use two different versions of Undertow for executing tests. One for `auth` server and the other one for `app`. 

As adapters still use JavaEE, we need to provide also support for them in the Undertow, but the more recent versions of Undertow don't use JavaEE anymore, but Jakarta EE.

On the other hand, the rest of the codebase use JakartaEE and it's required to use the mentioned more recent versions of Undertow for `auth` server.

The solution for that would be to use undertow, which would run in a different JVM.

**Comment by vmuzikar** [comment]
Most of the changes to use `app-server-undertow` as default were made here: https://github.com/keycloak/keycloak/pull/19760

**Comment by mabartos** [comment]
As there's an incompatibility between Undertow versions for `app-server` and `auth-server`, the maintainability would be worse even when it's enabled again. The `app-server-wildfly` substituted properly the undertow and as the undertow `app-server` might be completely removed(https://github.com/keycloak/keycloak/issues/30347), the relevance of this issue is not assessed.

Closing now.
