### ISSUE TITLE
Replace `react-error-boundary` with React Router error handling

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#19307]
We're using the [`react-error-boundary`](https://github.com/bvaughn/react-error-boundary) package to render errors when something goes wrong the the Admin UI. We don't need to use this package, as React Router already has the [same functionality](https://reactrouter.com/en/main/route/error-element) to handle errors.

We're already [using this functionality](https://github.com/keycloak/keycloak/blob/cf61a65198ba5f18ceb787c36ad8a33c34bbcdbb/js/apps/account-ui/src/routes.tsx#L59) in the Account UI, so this implementation can be used as an example of how this should be aligned.

Before picking up this issue it would likely make sense to resolve https://github.com/keycloak/keycloak/issues/19308 first.

**Comment by jdockeray** [comment]
@jonkoops could you assign this to me? I want to work on this. Thanks

**Comment by jonkoops** [comment]
Closing this out due to the reasons mentioned in #20043. See #21515 for a follow up.
