### ISSUE TITLE
False-negative when blocklist contains passwords with upper-case characters

### ISSUE THREAD

**Issue by Agh42** [keycloak/keycloak#19305]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

When using a password blocklist, the user should not be able to change his/her password to one that is contained in the blocklist. 

If the blocklist contains passwords with upper-case characters, these are never matched. The user may use this password as if it were not present in the blocklist.

It does not matter if the user enters his/her version of the password with upper- or lower-case letters - it will never be found in the blocklist. Any password with upper-case letters present in the blocklist will never match anything the user enters as a new password.

The root cause of this is that the user's password is converted to lower-case before it is compared, but the passwords from the block-list are not normalized in this fashion. I am not sure if I caught the intention of this function but I have a PR ready that should address the problem: https://github.com/keycloak/keycloak/pull/19306

### Version

21.0.1

### Expected behavior

- The password should be rejected because it is contained in the blacklist.

### Actual behavior

- The new password is accepted.

### How to Reproduce?

1. Go to Admin UI -> Authentication -> Policies -> Password Blacklist
2. Configure a password blocklist that contains passwords with upper-case characters (i.e. https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt)
3. Try to change your password to one that is blacklisted but contains upper-case characters (using the above blacklist this could be: L4JKnsPgVwoff or rV3HJRPy or Ruzik191991 )

### Anything else?

The bug was originally discovered by  @murygin and the probable cause was determined by @oleeander. I'm just trying to provide the fix.

I just now noticed the comment for KEYCLOAK-11700 introduced in https://github.com/keycloak/keycloak/commit/ea248b560183c58f65761053228d343829cf65e2 (" All passwords in the blacklist must be lowercased to facilitate case-insensitive comparison.").

Maybe it would be safer to force the password to lower-case when reading the blocklist instead of relying on the user to ensure this? (see the connected PR)

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by mwasson74** [comment]
@Agh42 in your investigation of this, have you noticed the following? (or even @mposolda)

- `password` is in the blacklist file
- `password1` is accepted as a new password

Maybe this is expected but I can't imagine it is.

**Comment by rmartinc** [comment]
Hi @Agh42!

As you commented the password list file should be in lower case and that is in the [documentation](https://www.keycloak.org/docs/latest/server_admin/#password-policy-types). Besides, common password files are usually provided in lower case (for example [SecLists](https://github.com/danielmiessler/SecLists/tree/master/Passwords/Common-Credentials)). The passwords are compared using a [BloomFilter](https://guava.dev/releases/32.0.0-jre/api/docs/com/google/common/hash/class-use/BloomFilter.html) which is a probabilistic data-structure that allows for fast and memory efficient containment checks (but it can give a false positive with a configurable probability).

I'm closing this. If more people really think we should lower case the passwords in the list we can reconsider it later.

Thanks!

**Comment by Agh42** [comment]
Since the current documentation explains this  ("Keycloak compares passwords in a case-insensitive manner. All passwords in the blacklist must be lowercase.") I'm fine with this decision. Thank your for considering my contribution.

Replying to @mwasson74 : the behaviour you describe is expected - the bloom filter that Keycloak does not match substrings - however it allows to match even huge lists of blocked passwords extremely fast. I'd recommend using a large list to ensure that all possible variations of weak passwords are blocked, i.e.: https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt

**Comment by mwasson74** [comment]
@Agh42 thank you so much for the reply!! So I have to come up with all of the possibilities a user might use that contain a substring? I don't think I'll be able to come up with every possibility; I will surely miss some. Is there a different way that I can just provide the substrings as blacklisted words?

**Comment by Agh42** [comment]
> @Agh42 thank you so much for the reply!! So I have to come up with all of the possibilities a user might use that contain a substring? I don't think I'll be able to come up with every possibility; I will surely miss some. Is there a different way that I can just provide the substrings as blacklisted words?

This is a bit off-topic for this issue but trying to help you out:

Usually you would simple pick a common blacklist like the one I linked to. Keycloak has other policies that you may also activate (i.e. a regexp-based rule) on top of that.

If you want to create your own blocklist (i.e. based on domain- or context-specific vocabulary) you could use a tool like [John](https://www.openwall.com/john/) with word mangling rules to create it:

```
john --wordlist=my-starting-wordlist.txt --rules --stdout > variation-blocklist.txt
```

Then you can use `variation-blocklist.txt` as a blocklist in keycloak.

...just make sure that it is all in lower-case - see above. ;-)
