### ISSUE TITLE
Boolean fields for user-Profile

### ISSUE THREAD

**Issue by c0ntradicti0n** [keycloak/keycloak#19318]
### Description

Since I don't find a working description how to enable Terms and Conditions as a checkbox, I tried with approximately this:

https://stackoverflow.com/a/74381814

But that didn't work. So I made my own checkbox into register.ftl, and surprisingly it's saved in the user-profile automatically.

I had a trial with using the 'declarative-user-profile' feature, that we are all previewing. But there could be boolean validators, a description for the field and checkboxes for controlling boolean fields.

What's best pratice here?

### Motivation

Using terms and conditions as everywhere when registering

**Comment by pedroigor** [comment]
@c0ntradicti0n Terms and conditions is out of the scope of the user profile. It is a dedicated required action that runs after the user is authenticating/registering.

If I understood your use case correctly, do you want to have a checkbox on the registration page to decide whether the terms and conditions page is shown afterward?
