### ISSUE TITLE
Support management port for health and metrics in Quarkus 3

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#19334]
### Description

In the Quarkus distribution the management and health endpoints are served from the standard HTTP endpoint. 

While security best practices require those endpoints not to be accessible from the outside, Keycloak still exposes the HTTP endpoint on OpenShift as a passthrough endpoint, which makes them accessible from the outside, which requires users to either disable those endpoints, use another loadbalancer in front of OpenShift, or configure a custom route. 

Quarkus 3.0.0.Beta1 finally supports a management port which allows service health and metrics from a different port, which is then not accessible from the outside: https://github.com/quarkusio/quarkus/issues/13602

### Motivation

Security best practices and hardening.

### Details

The pull request https://github.com/quarkusio/quarkus/pull/30506 adds the necessary documentation for this.

The Operator needs to pass additional options to Keycloak to make this work, and Keycloak possibly needs to support additional parameters / a different internal handling to make this work.
```[tasklist]
### Follow-up tasks
- [ ] https://github.com/keycloak/keycloak/pull/28213
- [ ] https://github.com/keycloak/keycloak/issues/28404
```

**Comment by ahus1** [comment]
@pedroigor / @vmuzikar - Once the Quarkus 3 migration is done, this would be IMHO a great addition to KC22 as it simplifies a secure configuration in cloud and non-cloud environments. 

I'd be happy if you could prioritize this, and add this to the KC22 milestone.

Thanks!

**Comment by vmuzikar** [comment]
I set the milestone to 22 for now. If time allows, we'll look into it.

**Comment by sventorben** [comment]
@vmuzikar I see that this ticket has been pushed for several versions now. I would really like to see this implemented as it would be very helpful from a security perspective for our Kubernetes clusters.
What are the chances of this being implemented in KC 25?
