### ISSUE TITLE
After update to 21.0.1 multiple ldap server space delimited on "Connection url" in not working

### ISSUE THREAD

**Issue by thundercost** [keycloak/keycloak#19354]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

We had configured two space delimited ldap servers on Connection Url (for failover). This was working fine on keycloak 20.0.1.
After upgrade to 21.0.1 the error is:
KC-SERVICES0055: Error when authenticating to LDAP: URI 'ldaps://dc1.example.com:636 ldaps://dc2.example.com:636' is not valid.: java.lang.IllegalArgumentException: URI 'ldaps://dc1.example.com:636 ldaps://dc2.example.com:636' is not valid.

### Version

21.0.1

### Expected behavior

Authenticate using multiple ldap servers as auth federation.

### Actual behavior

The test connection/test authentication fails from the admin UI logging the following error:
KC-SERVICES0055: Error when authenticating to LDAP: URI 'ldaps://dc1.example.com:636 ldaps://dc2.example.com:636' is not valid.: java.lang.IllegalArgumentException: URI 'ldaps://dc1.example.com:636 ldaps://dc2.example.com:636' is not valid.

### How to Reproduce?

Configure 2 ldap servers on "Connection url" for auth federation and try to test authentication.On version 20.0.1 is working and is failing over the 2 ldap servers (tested).
On version 21.0.1 is complaining about URI format

### Anything else?

If this is not the recommended solution for failing over between ldap servers please consult us with the recommended one.

**Comment by mposolda** [comment]
duplicates #17359

I am closing this as duplicate. Please use the other duplicated issue for further questions/comments/concerns around this.
