### ISSUE TITLE
Add realm-specific storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#19369]
Add capability to define a storage setup for an realm independently.

## Business justification

- Support "hard" multitenancy allowing complete split of the datasources for realm objects
- Support for realm-specific configuration for object federations, e.g. multiple sources for users, groups, clients, or roles

**Comment by souravs17031999** [comment]
@hmlnarik when this is planned to be delivered ?

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.

Might be relevant for the legacy store, still as it is very far in the future if this would ever be implemented, closing it for now. Might be re-opened or re-created as a new issue / differently focused issue later.
