### ISSUE TITLE
Facebook identity provider not working

### ISSUE THREAD

**Issue by robozb** [keycloak/keycloak#19368]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

During the login the button simple disappear

![C4200167-960E-47D0-8262-01E5DD69A031](https://user-images.githubusercontent.com/8656998/228131140-3b4bfbb8-6c50-4851-9fbc-693106b3e83c.png)
![917E9C35-D798-472F-966A-FC1DFAD4B2BB](https://user-images.githubusercontent.com/8656998/228131145-1ec2757b-e4f3-4853-a997-054476d18564.png)

### Version

21.0.1

### Expected behavior

Social login

### Actual behavior

No login

### How to Reproduce?

Click on fb login

### Anything else?

Proper scopes?

**Comment by robozb** [comment]
Thanks, I'll check it out!

**Comment by pedroigor** [comment]
@robozb I'm not able to reproduce the issue. Is the identity provider not available from the login page or are you having issues when authenticating through the identity provider?

Both work for me.
