### ISSUE TITLE
Realm export contains rotated client secret

### ISSUE THREAD

**Issue by rwiskerke** [keycloak/keycloak#19373]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

When creating a partial export of a realm the resulting json contains the "client.secret.rotated" attribute in "attributes" for an exported client (of course only when the feature 'client-secret-rotation' is enabled). This secret is not redacted/stripped.

### Version

20.0.3

### Expected behavior

I expected a redacted rotated client secret (`**********`), just like with the (non-rotated) client secret.

### Actual behavior

The unredacted rotated client secret is in the exported json

### How to Reproduce?

- start keycloak with `--features=client-secret-rotation`
- create a client profile with "executor": "secret-rotation"
- create a client policy
- client client and generate new secret
- partial export of realm setting, check the 'clients' checkbox

### Anything else?

I'll create a PR with the fix

**Comment by martin-kanis** [comment]
@rwiskerke Thank you for reporting the issue and sending the PR. I confirm the issue with 21.0.2.
