### ISSUE TITLE
federatedIdentityRemovingLastProviderMessage translation is missing for new account ui

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#19378]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

federatedIdentityRemovingLastProviderMessage is not translated in account ui

### Version

21.0.1+

### Expected behavior

Message should be translated

### Actual behavior

Message not translated

### How to Reproduce?

1) Create IdP in realm
2) Login via IdP
3) Try to delete idp account link

![image](https://user-images.githubusercontent.com/314690/228204425-a9d60be6-2e0d-45d1-8573-4094a3e208ce.png)

**Comment by thomasdarimont** [comment]
@jonkoops is it enough to call `Msg.localize(response.data['errorMessage'])` in `theme/keycloak.v2/account/src/app/account-service/account.service.ts`?

**Comment by jonkoops** [comment]
Yeah, ideally we would handle this kind of error messages generically, just like in the [new Account UI](https://github.com/keycloak/keycloak/blob/077b0644fefb5f85e62593c912b581a50c887722/js/apps/account-ui/src/api/parse-response.ts#L35-L53). We're planning to promote the new code in a couple of releases, so this bug would be fixed automatically.

However, feel free to create a very minimal fix for the existing code if that helps to get this bug squashed now.
