### ISSUE TITLE
memory leak when using ldap user federations

### ISSUE THREAD

**Issue by ainquel** [keycloak/keycloak#19396]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Hello,

We are running a keycloak cluster in production (using the embedded infinispan cache) using
version 18.0.2.

In 2023, we've experienced multiple outages due to the memory growing fast and crashing
1 node in 2-3 hours.

When these incidents started we had around 20 ldap user federations in our main realm
which were synchronized every 5m to 30m for "changed users sync" and
once a day for "full sync".  
We've also noticed that an internal tool was doing a lot of requests
(100-400 searches per minute) of an unknown user for minutes-hours compared to the normal load
(a few occasional searches throughout the day).

![image](https://user-images.githubusercontent.com/35383047/228295673-37ecb1d9-af43-4e6a-801e-7f149aa0b384.png)

We've analyzed a heap dump and found that 98% of the memory was retained by
the ConcurrentHashMap in `LDAPIdentityStoreRegistry.ldapStores`.  
The number of entries in it was correct compared to the number of ldap providers
we had so it wasn't due to the number of entries growing.

![image](https://user-images.githubusercontent.com/35383047/228300173-ab2d1ab8-68b1-4be2-b3c2-df0a6787adc8.png)

In the meantime, we've also noticed something weird in our logs, we've seen a lot of
`[org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (Timer-0) Creating new LDAP Store for the LDAP storage provider`
logged the same second for a single provider.  
After analysis, these logs came from different threads and the only thing changing was the attribute `lastSync`.

Example:

- `thread-1 Creating new LDAP Store for the LDAP storage provider: provider1: lastSync=2`
- `thread-2 Creating new LDAP Store for the LDAP storage provider: provider1: lastSync=1`
- `thread-3 Creating new LDAP Store for the LDAP storage provider: provider1: lastSync=2`

The `LDAPIdentityStoreRegistry.ldapStores` cache is read (and updated ?) concurrently by multiple
threads when a synchronization happens.

In the example above, one request is updating the cache as the `lastSync`
field [changed](https://github.com/keycloak/keycloak/blob/18.0.2/services/src/main/java/org/keycloak/services/managers/UserStorageSyncManager.java#L149) during the synchronization, but another thread is updating it back to the older entry, etc...
We've seen this happening for 10 times in less than a second when the search load is high.

This race seems to happen in `LDAPIdentityStoreRegistry.getLdapStore` between the [line](https://github.com/keycloak/keycloak/blob/18.0.2/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPIdentityStoreRegistry.java#L41)
where the older context is retrieved from the cache and the check between it and the
config stored (earlier during the handling of a request) in `ldapModel`.

So it showed us that there were a lot of activity around this cache when a provider
is been synchronized. The more ldap synchronizations (wether due to a very low interval between sync or a lot of ldap providers) the more it is visible.  
As the number of entries was relevant in the cache itself, we suspected that older
entries couldn't be garbage collected as even by forcing a full gc
(e.g using `jmap -histo:live ...`), they were still in the heap.

During the heap analysis, we've noticed a lot of instances of `DefaultKeycloakSession`,
`LDAPIdentityStore`, `LDAPOperationManager` and many more of `LDAPStorageProvider`.

Immediate dominators of `DefaultKeycloakSession` was `LDAPIdentityStoreRegistry.ldapStores`
so it confirmed there was a problem with the garbage.

See also the dominator tree of one session:

![image](https://user-images.githubusercontent.com/35383047/228301758-d04bc40c-5fab-4bf5-8db2-260db2668c28.png)

I can't explain it fully, but my theory is:

an `LDAPIdentityStore` needs a `DefaultKeycloakSession` at creation, each time a new one is created [here](https://github.com/keycloak/keycloak/blob/18.0.2/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPIdentityStoreRegistry.java#L56) before being put in the cache, the session passed is the current request session which is created when the request is [handled](https://github.com/keycloak/keycloak/blob/18.0.2/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java#L62) by the web server and is meant to be closed at its end.
It means this session won't be closed until it is removed from the cache.

Now when a request creates a `LDAPStorageProvider` (to talk to an ldap server) using the current
request session, it gets and obtain a reference to the latest `LDAPIdentityStore` from the cache
which uses another session (in our situation, we've seen dozens of LDAPStorageProvider
referencing a session stored in the `LDAPIdentityStoreRegistry`).

Sessions end up referenced by other sessions which seems to keep them to be garbage
collected (or something in their cache maybe).

I could reproduce this issue using the keycloak production server and the dev server on versions
`18.0.2`, `20.0.2` and `21.0.1`.

The simplest solution I could come up with was to create an `LDAPIdentityStore`
instance with a dedicated `DefaultKeycloakSession`.

```diff
--- a/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPIdentityStoreRegistry.java
+++ b/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPIdentityStoreRegistry.java
@@ -84,7 +84,8 @@ public class LDAPIdentityStoreRegistry {
         checkSystemProperty("com.sun.jndi.ldap.connect.pool.protocol", cfg.getConnectionPoolingProtocol(), "plain ssl");
         checkSystemProperty("com.sun.jndi.ldap.connect.pool.debug", cfg.getConnectionPoolingDebug(), "off");
 
-        return new LDAPIdentityStore(session, cfg);
+        KeycloakSession storeSession = session.getKeycloakSessionFactory().create();
+        return new LDAPIdentityStore(storeSession, cfg);
     }
```

We've tried it in our lab using scripts to reproduce the issue, by generating a search load
of 8000 searches / minute + 1 ldap synchronization every second and then in production.

We didn't notice any issues in 10 days, the memory is able to be garbage collected correctly.

A few note on this change:

- First I wanted to close the session explicitly when the context in the cache is changed
but as sessions were garbaged quickly I didn't do it, I don't know if there is an impact doing so.
- The session is used only by ldap related classes,  I didn't see any of them using
  a transaction to the db. If it does, the code above doesn't "close" the transaction
  (either by rollback or commit) like it is done [here](https://github.com/keycloak/keycloak/blob/18.0.2/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/web/QuarkusRequestFilter.java#L121)

### Version

18.0.2, 20.0.2, 21.0.1

### Expected behavior

see above

### Actual behavior

see above

### How to Reproduce?

Here is a [project](https://github.com/ainquel/keycloak-memleak-ldap) to reproduce this issue. It uses `docker` and `docker-compose` (more instructions in the readme).

It creates a few ldap providers, starts lot of searches of an unknown user (to bypass the cache), synchronizes
providers constantly and monitors the heap and number of instances of a few classes. It allows to reproduce in a minute the behavior we've seen happening in hours / days.

**Comment by hmlnarik** [comment]
Thank you for an excellent write-up and a reproducer! I can confirm this bug.

The proposed solution confirms the place of the bug and removes the symptom, still it needs amendment: The assumption that the session is not modified after obtaining the `LDAP is not true, it gets modified e.g. in `LDAPOperationManager.authenticate`, and thus the change will be more complex. I am working on it.
