### ISSUE TITLE
Composite Role not showing all roles

### ISSUE THREAD

**Issue by netdip** [keycloak/keycloak#19416]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Hell Team

I was trying to create a composite role via admin console. Unfortunately I am unable to do. When I am trying to assign roles it is listing only few roles at composite role, not complete list of roles when selecting 100 per page. Where as I can able to create the same using API.

Note: I have more than 100 roles.

Regards
Dipten

### Version

19.0.3

### Expected behavior

It should list down all roles

### Actual behavior

Not listing

### How to Reproduce?

Try to create composite role more than 100

**Comment by netdip** [comment]
Hi Team

Yes actual issue is fixed at 21.0.1 but we noticed few more issue and 21.0.1 as below.

1. whenever any domain/realm is imported, UI is not showing any status message like success/failure but it is imported
2. whenever any role is created, UI is not showing  any status message like success/failure but role has been created.

Regards
Dipten

**Comment by jonkoops** [comment]
@netdip please report those as separate issues, it helps us with the bookkeeping.
