### ISSUE TITLE
Impersonation role not added to service account when creating a realm

### ISSUE THREAD

**Issue by allanks** [keycloak/keycloak#19424]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

When creating a new realm via a service account within the master realm with the create-realm role, the impersonation role on the created realm will not be present on the service account.

### Version

21.0.1

### Expected behavior

The service account should receive the impersonation role

### Actual behavior

The service account does not receive the impersonation role

### How to Reproduce?

1. Create a service account client in the master realm
2. Grant service account create-realm role
3. Use service account to create another realm

### Anything else?

Noticed this when trying to grant impersonate to a service account within the created realm as I wanted to add/restrict the client scopes present on an impersonation token when I received the 403. Meaning the service account didn't have full access over the newly created realm

This is using the java admin client, call order is

1. Build keycloak client (master realm with service account credentials)
2. keycloak.realms().create([new realm])
3. keycloak.realm([new realm id]).clients().create([new service account])
4.   a. keycloak.realm([new realm id]).clients().get([new service account id]).getServiceAccountUser().getId()
      b. keycloak.realm([new realm id]).users().get([4a id]).roles().clientLevel([realm management id]).add([realm management impersonation role]) <-- 403

**Comment by pedroigor** [comment]
The reason is that the newly added realm did not exist when the access token was issued. Therefore, there is no role for the newly created realm.

To get the roles, you would need to refresh the token.

This one is related to https://github.com/keycloak/keycloak/issues/26301.
