### ISSUE TITLE
Add autocomplete="off" for username field in account console

### ISSUE THREAD

**Issue by mvk37** [keycloak/keycloak#19457]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Web scanner reported that field "username" in account console missing flag autocomplete="off". It creates possibility that user name could be cached by browser. It attacker get access to this computer it is possible to dump the browser cache and extract information. Risk of this is high on public computers.
![VirtualBox_Rocky8 4_30_03_2023_19_02_57](https://user-images.githubusercontent.com/43886879/228985136-37414300-8cee-48f3-81e5-ac515300e287.png)

### Version

21.0.2

### Expected behavior

username field has flag autocomplete="off" 

### Actual behavior

username field doesn't have this flag

### How to Reproduce?

Currently it is not

**Comment by jonkoops** [comment]
This field is disabled though, so why would it end up getting autocompleted? Feel free to open up a PR to add this if you like.

**Comment by ssilvert** [comment]
Let's fix this in V3 just to make the scanners happy.

**Comment by jonkoops** [comment]
> Let's fix this in V3 just to make the scanners happy.

Like we discussed before, I don't think that is a valid reason to so. In this case the scanner is giving a false positive, so they should fix the scanner. Either way, fixing this or continuing to discuss it just wastes time, I am closing it.
