### ISSUE TITLE
Latest release of @keycloak/keycloak-admin-client uses axios instead of fetch

### ISSUE THREAD

**Issue by valerii15298** [keycloak/keycloak#19455]
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

As I see from the source code in github and as I am told [here](https://github.com/keycloak/keycloak/issues/16900) keycloak-admin-client should use `fetch` instead of `axios`

### Version

21.0.2

### Expected behavior

@keycloak/keycloak-admin-client  should use `fetch` instead of `axios`

### Actual behavior

@keycloak/keycloak-admin-client  uses `axios` now as we see from npm `package.json` and code: https://www.npmjs.com/package/@keycloak/keycloak-admin-client?activeTab=code

### How to Reproduce?

install `@keycloak/keycloak-admin-client@21.0.2` make request that should throw an error. You will see that error is instance of `AxiosError` !!!

**Comment by jonkoops** [comment]
The last release has been published from the [old repository](https://github.com/keycloak/keycloak-nodejs-admin-client/). This was a mistake in our release process that has since been corrected. The next release should get all the latest changes.
