### ISSUE TITLE
Keycloak adapter redirect url incorrect when tls offloading with sidecar in Kubernetes

### ISSUE THREAD

**Issue by drewgraham** [keycloak/keycloak#19451]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/jee

### Describe the bug

We have a service using keycloak adapter, running in a Kubernetes pod. TLS is offloaded with an NGINX sidecar reverse proxy (running in same pod). As a result of being in the same pod, the request url from proxy to application is `localhost`

With `ssl-required` set to `external` (default value), the redirect uri is not converted to https, because the request url is local (https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/OAuthRequestAuthenticator.java#L146).

With `ssl-required` set to `all`. the redirect is correctly converted to https, however the authentication now fails because the request is not https (https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/PreAuthActionsHandler.java#L196).

Configuring the tomcat connector as secure (but retaining http scheme) causes the redirect url to not be rewritten (because it doesn't meet the `!facade.getRequest().isSecure()`  check here https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/OAuthRequestAuthenticator.java#L146.

Additionally, oauth code resolution does not convert the redirect url to https so subsequently fails keycloak token validation. (https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/OAuthRequestAuthenticator.java#L318).

We can solve locally by:
- Removing `!facade.getRequest().isSecure()` check, rewriting the redirect url if ssl required, regardless of secure status:  (https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/OAuthRequestAuthenticator.java#L146).
- Adding equivalent https scheme rewrite to resolveCode: (https://github.com/keycloak/keycloak/blob/main/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/OAuthRequestAuthenticator.java#L318)

### Version

Main

### Expected behavior

Successful oauth authentication

### Actual behavior

Incorrect redirect uri, or authentication failure, depending on ssl-required and secure request configuration.

### How to Reproduce?

Deploy app with keycloak adapter to tomcat server with:
- `secure="true"` set in tomcat server.xml for http endpoint.
- `ssl-required` set to `external` in keycloak adapter config.

Use a reverse proxy to offload https and forward to http application endpoint.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.
