### ISSUE TITLE
Infinispan throws RollbackException when an entity is removed by Id and by query within one transaction

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#19463]
During the optimistic locking introduction #15402, we encountered `RollbackException` when the same entity is removed by query and also by id. This can happen, for example, during cleanup in tests when we remove realm and its user separately (users are removed by query when realm is removed).

Example of code:
```java
        RealmModel realm = s.realms().getRealm(realmId);
        s.sessions().removeUserSessions(realm);

        UserModel user1 = s.users().getUserByUsername(realm, "user1");
        UserModel user2 = s.users().getUserByUsername(realm, "user2");

        UserManager um = new UserManager(s);
        if (user1 != null) {
            um.removeUser(realm, user1);
        }
        if (user2 != null) {
            um.removeUser(realm, user2);
        }

        s.realms().removeRealm(realmId);
```

We should investigate whether it is a problem and if yes try to fix this either by discussing it with the ISPN team or somehow detecting double removals in Keycloak.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
