### ISSUE TITLE
SignatureProvider not showing up in the Default Signature Algorithm list

### ISSUE THREAD

**Issue by vladimirr9** [keycloak/keycloak#19485]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have added a custom signature provider by implementing the SignatureProvider, and SignatureProviderFactory interfaces as well as extending the AsymmetricSignatureVerifierContext and AsymmetricSignatureSignerContext classes. 

Going Under Realm settings > Tokens I expected the custom signature provider to be under the default signature algorithm list, but it is not.

### Version

21.0.2

### Expected behavior

In the old admin console under Realm settings > Tokens the new signature provider would show up as an option in the default signature algorithm list.

### Actual behavior

After adding it as a custom provider it doesn't show up in the list, but it is recognized by keycloak as it can be set to selected using the Admin REST API. Even then it is still not given as an option in the list.

### How to Reproduce?

Create a new SignatureProvider and add it as a custom provider. Go to Realm Settings > Tokens and see if it's in the Default Signature Algorithms list.

**Comment by edewit** [comment]
This might have been fixed with #19198 could you try the nightly build to verify?

**Comment by jonkoops** [comment]
The nightly build can be found here: https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by vladimirr9** [comment]
I tried with 21.1 and it works.

**Comment by jonkoops** [comment]
Awesome, thanks for verifing that for us @vladimirr9 :+1:
