### ISSUE TITLE
Add support for SQLite 

### ISSUE THREAD

**Issue by nlgtuankiet** [keycloak/keycloak#19482]
### Description

For now, we already have support for `dev-file` (which is H2 database under the hook). 
Is it possible to support SQLite as a database option? If is it not, what is the blocker?

### Motivation

1. Amount of dev ops 
Deploying a client-server database (like PostgreSQL and MySQL) with a proper backup setup is very hard. 
With SQLite you only need an instance of https://litestream.io/ running, it is one command away from point-in-time backup/recovery. 

2. Resource usage
Running database + backup programs eats up a lot of memory and is kind of overkill for small apps.

3. People starting to use SQLite in production and finds a lot of success, for example:
https://tailscale.com/blog/database-for-2022/

### Details

I tried to add support for SQLite, starting by implementing new `org.keycloak.config.database.Database.Vendor` but failed to compile the project to begin with 🤦‍♂️. 
I am not familiar with the persistent layer of [keycloak](https://github.com/keycloak/keycloak) and just want to ask if this is possible. I am happy to contribute.

**Comment by nlgtuankiet** [comment]
Hi @stianst, I figure you might familiar with the codebase, do you have any thoughts about this?

**Comment by hmlnarik** [comment]
Sadly, we do not plan to support SQLite or any additional engines due to the efforts needed keep maintainability anytime soon.

H2 is only available for development in legacy store, and is not intended for production use.
