### ISSUE TITLE
not able to login keycloak

### ISSUE THREAD

**Issue by ashisharya01** [keycloak/keycloak#19480]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Email verification
You need to verify your email address to activate your account.
An email with instructions to verify your email address has been sent to your address ashish.arya14jan@gmail.com.

Haven't received a verification code in your email?
[Click here](http://localhost:8080/realms/master/login-actions/required-action?session_code=Or5rsTdyi2yztbXFRmo8AA71w3Fcq6Pgho6NJSe193I&execution=VERIFY_EMAIL&client_id=security-admin-console&tab_id=W8flMdjE3Es) to re-send the email.

### Version

21.01

### Expected behavior

Email verification
You need to verify your email address to activate your account.
An email with instructions to verify your email address has been sent to your address ashish.arya14jan@gmail.com.

Haven't received a verification code in your email?
[Click here](http://localhost:8080/realms/master/login-actions/required-action?session_code=Or5rsTdyi2yztbXFRmo8AA71w3Fcq6Pgho6NJSe193I&execution=VERIFY_EMAIL&client_id=security-admin-console&tab_id=W8flMdjE3Es) to re-send the email.

### Actual behavior

Email verification
You need to verify your email address to activate your account.
An email with instructions to verify your email address has been sent to your address ashish.arya14jan@gmail.com.

Haven't received a verification code in your email?
[Click here](http://localhost:8080/realms/master/login-actions/required-action?session_code=Or5rsTdyi2yztbXFRmo8AA71w3Fcq6Pgho6NJSe193I&execution=VERIFY_EMAIL&client_id=security-admin-console&tab_id=W8flMdjE3Es) to re-send the email.

### How to Reproduce?

Email verification
You need to verify your email address to activate your account.
An email with instructions to verify your email address has been sent to your address ashish.arya14jan@gmail.com.

Haven't received a verification code in your email?
[Click here](http://localhost:8080/realms/master/login-actions/required-action?session_code=Or5rsTdyi2yztbXFRmo8AA71w3Fcq6Pgho6NJSe193I&execution=VERIFY_EMAIL&client_id=security-admin-console&tab_id=W8flMdjE3Es) to re-send the email.

### Anything else?

Email verification
You need to verify your email address to activate your account.
An email with instructions to verify your email address has been sent to your address ashish.arya14jan@gmail.com.

Haven't received a verification code in your email?
[Click here](http://localhost:8080/realms/master/login-actions/required-action?session_code=Or5rsTdyi2yztbXFRmo8AA71w3Fcq6Pgho6NJSe193I&execution=VERIFY_EMAIL&client_id=security-admin-console&tab_id=W8flMdjE3Es) to re-send the email.

**Comment by jonkoops** [comment]
Sorry, but this issue does not have enough information to understand what is going on. Please provide accurate information about what is going on and provide the means to reproduce it and report a new issue.
