### ISSUE TITLE
Client Policy tab causes 501 if the client policy feature is disabled

### ISSUE THREAD

**Issue by bplotnick-humane** [keycloak/keycloak#19510]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If the client policy feature is disabled, clicking on "Client policies" tab in "Realm settings" in the admin UI, a 501 is triggered and causes the error "Feature not enabled".

### Version

20.0.5

### Expected behavior

The tab shouldn't be there

### Actual behavior

The tab is there

### How to Reproduce?

Disable client policies feature. Go to the admin UI and click on client policies

**Comment by ssilvert** [comment]
I have recreated this.

`kc start-dev --features-disabled=client-policies`

**Comment by ssilvert** [comment]
Fixed by https://github.com/keycloak/keycloak/pull/19558
