### ISSUE TITLE
Remove workaround for locking in HotRodMapStorage

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#19518]
### Description

There are workarounds in `HotRodMapStorage` for optimistic locking because it was not possible to project entity version with an Ickle query. We can remove those workarounds after https://issues.redhat.com/browse/ISPN-14478.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
