### ISSUE TITLE
Remove access not working in new account v2 app

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak#19515]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

This issue is a continuation of #12738. The new account v2 app cannot remove the consents for an app whose clientId needs to be encoded, for example, using a URL type clientId. The account v2 application fails with an error: `Not Found: RESTEASY003210: Could not find resource for full path: http://localhost:8080/realms/master/account/applications/http://localhost:8081/sample-rhsso-saml//consent`.

As you can see the URL is using the `clientId` without any encoding but the URL should be: `http://localhost:8080/admin/realms/master/users/85c9667d-1abe-4320-8008-62cfacd80519/consents/http%3A%2F%2Flocalhost%3A8081%2Fsample-rhsso-saml%2F`. Encoding the ID works at server side level.

### Version

21.0.1

### Expected behavior

The account v2 app should encode the `clientId` before sending the request.

### Actual behavior

The `clientId` is not encoded and the delete fails.

### How to Reproduce?

* Create a OIDC or SAML client with consent required to ON. Use as the client ID a URL type, in my case I created: `http://localhost:8081/sample-rhsso-saml/`.
* Login to the application and accept the consent page.
* Change to the account application: `http://localhost:8080/realms/master/account` Go to the `Applications` menu page. Expand the client with the URL and click `Remove Access`. The error appears.

### Anything else?

I have been checking and IMHO the only needed thing is just encoding the clientId. For example, in the [ApplicationsPage.tsx](https://github.com/keycloak/keycloak/blob/21.0.2/themes/src/main/resources/theme/keycloak.v2/account/src/app/content/applications-page/ApplicationsPage.tsx#L102-L107) something like this:

```diff
   private removeConsent = (clientId: string) => {
-    this.context!.doDelete("/applications/" + clientId + "/consent")
+    this.context!.doDelete("/applications/" + encodeURIComponent(clientId) + "/consent")
       .then(() => {
         this.fetchApplications();
       });
```

But I a bit confused with the account app. Because I see it inside the `js` directory and inside the `themes` folder. So better if the UI team check this. But the summary is that the delete should send the `clientId` encoded.

**Comment by jonkoops** [comment]
I agree with your conclusion @rmartinc. A simple `encodeURIComponent()` should do the trick.

> But I a bit confused with the account app. Because I see it inside the `js` directory and inside the `themes` folder.

The one in the `themes` directory is the current stable version (a.k.a 'Account V2'). The one in the `js` directory is the new one we're working on, that is is yet to be productized (a.k.a. 'Account V3').
