### ISSUE TITLE
Users in role Rest API returns empty when User federation used.

### ISSUE THREAD

**Issue by shankaryadavy9** [keycloak/keycloak#19516]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Hi Team,

I have successfully implemented User Federation using an external REST API. Users are pulled from external services, and their extra information is stored in Keycloak. Everything is working well, except for the **Users In Role** tab, which appears empty when clicked. 

![image](https://user-images.githubusercontent.com/43490933/229723038-e93c2f5d-a2ff-415a-9bcc-8893db2a2607.png)

Upon inspection, I noticed that none of my custom user federation methods were called when clicked on this tab. I even attempted to use the admin API GET `/{realm}/clients/{id}/roles/{role-name}/users`, but received the same result.

I already assigned roles to the user and can see the same when clicking on user's **Role Mapping** tab.

When I don't use user-federation and directly add users in Keycloak then it works.

### Version

20.0.5, 21.0.2

### Expected behavior

It should return filtered users by role.

### Actual behavior

Empty response.

### How to Reproduce?

Create a custom user-storage provider and implement `UserStorageProvider, UserLookupProvider, UserQueryProvider` interfaces.

**Comment by martin-kanis** [comment]
@shankaryadavy9 Thanks for the report. I think we need to see your implementation of `UserStorageProvider` to provide any help.

**Comment by shankaryadavy9** [comment]
Hi @martin-kanis 

Extremely sorry for late response.  But I have tested it again with latest Keycloak version 22.0.1 and issue still persist.

I could not share my implementation because of some restrictions but guess what I tested the same scenario with Keycloak's property file writable example 
https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/user-storage-simple/

  Here are the steps to reproduce issue.

1. Build and install writable property file storage spi using above link.
2. Create dummy realm and activate user spi for user federation and create dummy user using this SPI!
3. Create oidc client and one user role under it
4. map  this role to dummy user .
5. Select client role and go to **user's in role** tab.  
6. Find it empty :)

![image](https://github.com/keycloak/keycloak/assets/43490933/4d0648a2-83a5-404a-b8ef-46e98c5ffd32)
![image](https://github.com/keycloak/keycloak/assets/43490933/acef979c-8342-482e-a3ee-abf76057bc87)
 
Please let me know if you are not able to reproduce it.  

Request to reopen it  please

**Comment by shankaryadavy9** [comment]
Hi @martin-kanis  

Just a friendly reminder.

**Comment by martin-kanis** [comment]
@shankaryadavy9 Did you implemented this method https://github.com/keycloak/keycloak/blob/main/server-spi/src/main/java/org/keycloak/storage/user/UserQueryMethodsProvider.java#L168-L170?
In case of default user storage, it is implemented here https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L503-L507
For your custom provider, you have to override the method and provide an implementation. 
There is also paginated variant of this method.

**Comment by shankaryadavy9** [comment]
Yes, I have implemented both methods for  groups and roles as an empty implementation because i want to use Keycloak itself to store groups and roles (augmentation) .  With below code groups are working fine but not the roles. I hope scenario is clear to you .  
```
    @Override
    public Stream<UserModel> getGroupMembersStream(RealmModel realm, GroupModel group, Integer firstResult, Integer maxResults) {
        // runtime automatically handles querying UserFederatedStorage
    	System.out.println("GroupMembersStream called with pagination");
        return Stream.empty();
    }
    
    @Override
    public Stream<UserModel> getGroupMembersStream(RealmModel realm, GroupModel group) {
        // runtime automatically handles querying UserFederatedStorage
    	System.out.println("GroupMembersStream called without pagination");
        return Stream.empty();
    }

    
    @Override
	public Stream<UserModel> getRoleMembersStream(RealmModel realm, RoleModel role, Integer firstResult,
			Integer maxResults) {
    	System.out.println("RoleMembersStream called with pagination");
		return Stream.empty();
	}
   
    
    @Override
	public Stream<UserModel> getRoleMembersStream(RealmModel realm, RoleModel role) {
    	System.out.println("RoleMembersStream called without pagination");
		return Stream.empty();
	}

```

**Comment by martin-kanis** [comment]
@shankaryadavy9 Thanks for adding more info. Now, I understand. Looking into the code, we have the following query  `fedgroupMembership` in `FederatedUserGroupMembershipEntity` for groups, but there is no corresponding method for roles in `FederatedUserRoleMappingEntity`.
I'm reopening this issue. Also, contributions from the community are welcomed. :)

**Comment by shankaryadavy9** [comment]
Thanks @martin-kanis . I am not the expert in Keycloak though but I will read the docs and send PR!

**Comment by shankaryadavy9** [comment]
Hi @martin-kanis 

I followed the `groupmembership` code and created  new method in `UserRoleMappingsFederatedStorage`

Once made the relevant changes and deployed my custom user provider with empty methods, everything works smoothly. I created  PR  with those changes . Please review.

```
       @Override
	public Stream<UserModel> getRoleMembersStream(RealmModel realm, RoleModel role, Integer firstResult,
			Integer maxResults) {
    	System.out.println("RoleMembersStream called with pagination");
		return Stream.empty();
	}
```
