### ISSUE TITLE
Trusted Hosts configuration in Client Registration Policy not working

### ISSUE THREAD

**Issue by sapo-di** [keycloak/keycloak#19513]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I try to edit the `Trusted Hosts` in the `Clients -> Client Registration -> Anonymous Registration Policies` no entries are shown.

Newly added entries are not correct persisted.

### Version

21.0.2

### Expected behavior

Previously added entries should be displayed and be editable.

New entries should be correct persisted.

### Actual behavior

No entries are shown and new entries have the wrong format.

- I can see in the network tab that the stored configuration is loaded but not displayed. 
- New entries are not send as array of multiple entries. The UI send a single array item with all host names and  `##`  between the entries.

If I configure `entry1.com`, `*.example.org` and `*.local_network` as trusted host this is the request:
```json
{
    "id": "...",
    "name": "Trusted Hosts",
    "providerId": "trusted-hosts",
    "providerType": "org.keycloak.services.clientregistration.policy.ClientRegistrationPolicy",
    "parentId": "master",
    "subType": "anonymous",
    "config": {
        "host-sending-registration-request-must-match": [
            "true"
        ],
        "trusted-hosts": [
            "entry1.com##*.example.org##*.local_network"
        ],
        "client-uris-must-match": [
            "false"
        ]
    }
}
``` 

### How to Reproduce?

1. Open in a realm `Clients -> Client Registration -> Anonymous Registration Policies -> Trusted Hosts` and add new entries.
2. Switch back to the policy list
3. Open the `Trusted Hosts` again

**Comment by ssilvert** [comment]
I have reproduced this.  The trusted hosts are saved, but they don't show up when you go back and try to view them.

**Comment by vijay94** [comment]
Hello people, I am not even seeing any option like  Client Registration in the clients page. Is there anything to be done to enable this?

**Comment by sapo-di** [comment]
Hi,

Which keycloak version are you using? 
It was moved from the realm settings to its own tab in the `Clients` section.

**Comment by vijay94** [comment]
Thanks @sapo-di I am able to see the tab in new version of keycloak
