### ISSUE TITLE
Admin Pagination : Roles doesn't load and stay the same first roles when you're loading the next roles

### ISSUE THREAD

**Issue by Hdz** [keycloak/keycloak#19523]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If we have more than 10 resources, only the first 10 are shown. The same is true for the other sub-tabs. Navigation arrows are disabled, and a page size chooser doesn't work as well: there is no reaction when we switch to "20 per page" or any other value.
Pagination works when you filter by client, but not when we filter on realm roles.

### Version

21.0.2

### Expected behavior

Load the others roles after the next page.

### Actual behavior

Doesn't load the other roles

### How to Reproduce?

Migrating from keycloak 21.0.1 to  21.0.2.

Get another page from the roles to assign :

![CaptureGITHUB](https://user-images.githubusercontent.com/2638430/227186043-a4a4674a-e444-4813-a7c0-c0613fad13d3.png)

### Anything else?

This is the same issue than some people previously had : #18319 , #19271

Works on the nightly version, we thought it'd be released on this new version. Apparently it did not.

**Comment by jonkoops** [comment]
@edewit You've worked on the pagination fairly recently, is this one of those cases were the API is lacking and we should probably disable the pagination on the client side?

**Comment by Hdz** [comment]
Don't get us wrong @jonkoops, we love the pagination "this way", we would just like it to work.

**Comment by edewit** [comment]
I'll have a look @Hdz, like you said, I think it did work at some point

**Comment by edewit** [comment]
@Hdz which assign roles page is this? It's used in 5 places

**Comment by Hdz** [comment]
It is currently happening when you decide to assign roles to a user. 

The URL would be auth/admin/master/console/#/{realm}/users/{id}/role-mapping

basically when you're in ysers, there's a button "assign roles" and that's where the bug happens.

It did work on the nightly before 21.0.2

**Comment by edewit** [comment]
I don't know what happened @Hdz I can confirm it still works on the nightly but not on 21.0.2

**Comment by jonkoops** [comment]
If this works in the nightly it has been fixed and will come along with the next release (likely 21.1.0). Closing this issue.
