### ISSUE TITLE
Update migration guide and release notes for Keycloak 21.1.0 release

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#19526]
### Description

- Upgrading guide file `changes-22_0_0.adoc` already contains some stuff. It seems that some (or all?) of this should be moved to `changes-21_1_0.adoc`. Also we should avoid to include the `changes-22_0_0.adoc` before 21.1.0 release (or delete that file entirely for now)

- Release notes file `22_0_0.adoc` - same like above

**Comment by jonkoops** [comment]
"Keycloak JS adapter must be instanciated with the `new` operator" is supposed to come along with 21.1.0. "Legacy Promise API removed from Keycloak JS adapter" is supposed to come along in 22.0.0. The commit that implemented that should be reverted for the 21.1.0 release.

**Comment by mposolda** [comment]
@jonkoops Thanks for pointing that. BTV. Maybe you're best candidate to handle this one? :-) Was just wondering as it looks that you're most familiar with this.

I've created https://github.com/keycloak/keycloak/issues/19529 to not forget about reverting it (Feel free to update accordingly).

**Comment by jonkoops** [comment]
I can certainly work on getting this done for the 21.1.0 release. Once we branch off I will take a look.

**Comment by stianst** [comment]
Updated this in https://github.com/keycloak/keycloak/pull/19718
