### ISSUE TITLE
JTA transaction handling with two data sources not supported in container

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#19538]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When running the Keycloak container with JTA and two data source, the Quarkus transaction manager will start to write information about the transactions in flight to the local file system. 

In https://github.com/keycloak/keycloak-benchmark/pull/306, we saw the error message: 

> "message": "ARJUNA012225: FileSystemStore::setupStore - cannot access root of object store: ObjectStore/ShadowNoFileLockStore/defaultStore/",

This happend with map store and a mixed JPA + Hot Rod setup. The same can happen with the legacy store once users use a custom store and enable JTA. With Quarkus 3, JTA is the default for the legacy store and this situation can become more frequent.

As a fix/workaround, we set the environment variable `QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY` to `/tmp`. 

### Version

nightly

### Expected behavior

The Keycloak container should be configured to allow JTA with multiple transactions.

### Actual behavior

Transactions fail once there are multiple transactions managed within a single request.

### How to Reproduce?

Run a Keycloak container with JPA map storage configured for both HotRod (sessions) and JPA (other entities). 

This would also occur with the legacy store with a custom user provider.

**Comment by pedroigor** [comment]
See https://github.com/keycloak/keycloak/pull/19384. If related, should be fixed upstream already.

**Comment by ahus1** [comment]
Confirmed that this is a duplicated. Closing this issue. Thanks Pedro!
