### ISSUE TITLE
Breadcrumbs are not correct in the authorization part in the admin console

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#19533]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When I enable "Authorization" for some confidential OIDC client.

Then go to: My client -> Authorization -> Policies -> Default Policy

Now I am editing the existing policy `Default Policy`. However the breadcrumbs (links in the top part of the screen) show:
`Clients` -> `Client Details` -> `Create Policy`. See screenshot (FYI. same screenshot used also for reporting the other related issue #19532 )

![Screenshot from 2023-04-04 17-14-33](https://user-images.githubusercontent.com/1223965/229842568-f5dcc0dd-f52f-409b-93fd-8cbf2b204d2d.png)

Here I am not creating new policy, but I am editing existing policy. So strictly said, it should say something like `Policy Details` to be compatible with some other objects in the admin console (EG. users)? The last part should be `Create Policy` just when I am creating new policy.

Same issue exists for other authorization objects (`resources`, `scopes`, `policies`). It seems it is correct only for `permissions`.

### Version

21.0.2

### Expected behavior

When editing existing `policy`, `resource` or `scope`, the last part of the breadcrumb link should be likely something like `Policy Details` instead of `Create Policy`. The `Create Policy` should be just when I am creating new policy (Similar for Resources, Scopes).

### Actual behavior

Breadcrumb is showing `Create Policy` (or `Resource` or `Scope`) even if I am updating existing policy.

### How to Reproduce?

See above

**Comment by pedro-hos** [comment]
@mposolda I guess that is a simple change. May I work on this?

**Comment by jonkoops** [comment]
Feel free to take it @pedro-hos, assigned it to you :+1:
