### ISSUE TITLE
Reset Password: skip and return success if same as existing password

### ISSUE THREAD

**Issue by daniel-shuy** [keycloak/keycloak#19542]
### Description

Enhance the Reset Password feature to skip and return success if the new password is the same as the existing password.

This includes skipping policy checks, updating the credential, adding a new password history, and removing old password histories .

From the user's point of view, there is no difference.

### Motivation

There are tools like [keycloak-config-cli](https://github.com/adorsys/keycloak-config-cli) that updates the configuration state of a Keycloak instance to match a configuration file. This includes default users (which is extremely useful for testing).

Because the tools cannot check if a user's existing password already matches what is in the configuration file, all it can do is create the user if it doesn't already exist, otherwise update the user's password to what is in the configuration file.

With a **Not Recently Used** (**Password History**) policy, if the user exists and the user's existing password already matches what is in the configuration file, the update fails.

Changing the Reset Password to skip and return success if the new password is same as the existing password will allow such tools to work with a **Not Recently Used** (**Password History**) policy.

**Comment by douglaspalmer** [comment]
Changing reset password as suggested as described would break the Not Recently Used password policy as it would allow the user to reuse the same password.
