### ISSUE TITLE
Infinispan max-count values

### ISSUE THREAD

**Issue by mathieu-pousse** [keycloak/keycloak#19553]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

I have configured a cluster of 2 nodes with this kind of settings regarding the infinispan caches: 

```
        <local-cache name="users" statistics="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory storage="HEAP" max-count="10000"/>
        </local-cache>
```

I have activated the metrics and would have expected `vendor_cache_manager_keycloak_cache_users_cluster_cache_stats_approximate_entries_unique` value on a node to be around 10 000. 

However, I get a value of  20 000.

![image](https://user-images.githubusercontent.com/2642023/230095623-1b0b5293-0be9-43b7-8dd0-570ff2cf5821.png)

I can't get the information if this is a bug where everything is stored twice or if the metric is not reflecting properly the number of items. However, since me moved from 15 to 20, we are having memory consumption issues with the same traffic before / after.

### Version

20.0.5

### Expected behavior

Have a number of item cache that matches the configured limit

### Actual behavior

Have a number of item cache that is twice or N-times the number of nodes multiplied by the limit

### How to Reproduce?

Set a max-count value for a cache configuration

### Anything else?

Please not that I have this issue either with local or distributed caches.

**Comment by martin-kanis** [comment]
@mathieu-pousse Thank you for the report. 
Looking into name of the metrics, I found the following in the RH data grid docs https://access.redhat.com/webassets/avalon/d/red-hat-data-grid/8.3/api/index-all.html
```
CLUSTER_APPROXIMATE_ENTRIES
Approximate current number of entry replicas currently in the cache cluster-wide.
CLUSTER_APPROXIMATE_ENTRIES_UNIQUE
Approximate current number of unique entries in the cache cluster-wide.
```

This suggest the metric aggregates number of entries across the cluster. You have two nodes, where every node has its own local users cache. Could this be the explanation why you see 20k entries?

**Comment by martin-kanis** [comment]
Closing as explained. Feel free to re-open, if you still believe this is a bug.
