### ISSUE TITLE
response_type none is oidc spec but ignored in the current implementation.

### ISSUE THREAD

**Issue by fierg** [keycloak/keycloak#19564]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

If a request to the token endpoint is including the `response_type none` param, it is ignored and a token response is sent.

### Version

20.0.5

### Expected behavior

From the open id connect specs (https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html)

### None Response Type
This section registers the Response Type none, in accordance with the stipulations in the OAuth 2.0 specification, Section 8.4. The intended purpose is to enable use cases where a party requests the Authorization Server to register a grant of access to a Protected Resource on behalf of a Client but requires no access credentials to be returned to the Client at that time. The means by which the Client eventually obtains the access credentials is left unspecified here.

One scenario is where a user wishes to purchase an application from a market, and desires to authorize application installation and grant the application access to Protected Resources in a single step. However, since the user is not presently interacting with the (not yet active) application, it is not appropriate to return access credentials simultaneously in the authorization step.

When supplied as the response_type parameter in an OAuth 2.0 Authorization Request, the Authorization Server SHOULD NOT return an OAuth 2.0 Authorization Code, Access Token, Access Token Type, or ID Token in a successful response to the grant request. If a redirect_uri is supplied, the User Agent SHOULD be redirected there after granting or denying access. The request MAY include a state parameter, and if so, the Authorization Server MUST echo its value as a response parameter when issuing either a successful response or an error response. The default Response Mode for this Response Type is the query encoding. Both successful and error responses SHOULD be returned using the supplied Response Mode, or if none is supplied, using the default Response Mode.
The Response Type none SHOULD NOT be combined with other Response Types.

### Actual behavior

`response_type none` is ignored and a token is returned in the response. 

### How to Reproduce?

NOTE: This section is not correct. See this comment for the details https://github.com/keycloak/keycloak/issues/19564#issuecomment-2095850539

```
POST /auth/realms/<realm-name>/protocol/openid-connect/token HTTP/1.1
Host: <host>
Authorization: Basic XXX
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=<client-id>&password=<password>&
username=<username>&grant_type=password&response_type=none
```

### Anything else?

https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

**Comment by mposolda** [comment]
@kaustubh-rh Yes, this would be welcome!

Just a note: The section `How to Reproduce` is not correct as it tries to add parameter `response_type` to the OAuth2 Token request with the OAuth2 Resource Owner Password Credentials. But the `response_type` parameter is not supported at all in the token request - see https://datatracker.ietf.org/doc/html/rfc6749#section-4.3.2 .

The `response_type` parameter is supposed to be used in the "Authorization Request", not in the "Token request" . The specification https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#none , which is mentioned in the description, also mentions `response_type=none` to be used in the authorization request, which makes sense for the purpose mentioned in the specification . We should NOT add the support for `response_type=none` to the token request as it doesn't makes much sense anyway.

**Comment by mposolda** [comment]
Here some notes how this can be possibly implemented: https://github.com/keycloak/keycloak/pull/29322#pullrequestreview-2043787216

**Comment by graziang** [comment]
It seems that the `none` parameter is already correctly handled in the auth request. I tested and the client is correctly redirected without the `code` and other parameters not allowed by specification. Here you can see that the various claims are never included in the response in the case of `response_type=none`: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/OIDCLoginProtocol.java#L237.

The parameter is also added to `OIDCWellKnownProvider` endpoint in the `response_types_supported` claim 
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java#L78

I haven't found any tests with `response_type=none`, so it might make sense to add one. @kaustubh-rh , @mposolda Am I missing something?

**Comment by Arnaud-FELTZ** [comment]
@mposolda : issue persists in 26.0.7, I may be able to provide code base if necessary.
1/ Create a custom theme 
2/ Create a custom provider and authent flow with i18n activated
3/ Switch languages raises the issue when clicking on the "account" link that redirects to the login page
