### ISSUE TITLE
How to change the title of Admin Console 

### ISSUE THREAD

**Issue by guptakaran27** [keycloak/keycloak#19563]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

As per this bug: https://github.com/keycloak/keycloak/issues/19116
I have to modify the source code, in order to change the display title of the Admin Console screen from "Keycloak Administration UI" to say "Karan's Administration GUI"

(As I m unable to edit the title by overriding  message.properties / admin-messages_en.properties)

But I m unable to find the any occurrence of this string "Keycloak Administration UI" in the code-base apart from a pom-file (/keycloak/rest/pom.xml)

![image](https://user-images.githubusercontent.com/128346079/230278211-78b9acc0-02be-4490-9fcf-2e24889b2438.png)
 
Requesting inputs, on where to modify the source code to achieve this. 

Same issue was observed in 21.0.1 as well. 

### Version

21.0.2

### Expected behavior

Admin Console UI should display custom Title

### Actual behavior

Admin Console is displaying "Keycloak Administration UI"

### How to Reproduce?

1. Unzip the Keycloak 21.0.2 tar file
2. Create a custom admin theme in the form : /keycloak/themes/myTheme/admin/messages/admin-messages.properties
3. Provide custom in the field : consoleTitle
4. Run the kc.bat file

**Comment by guptakaran27** [comment]
Hi Team, any update related to this ticket ?

**Comment by jonkoops** [comment]
Hi @guptakaran27. This is currently assigned to one of our team members, so it will get picked up.

**Comment by jonkoops** [comment]
@agagancarczyk Likely we would like this to work as it did before, see [this entry](https://keycloak.discourse.group/t/how-to-change-keycloak-admin-console-title/5680/3) in the forum.

**Comment by agagancarczyk** [comment]
hi @guptakaran27 this should now work as per https://github.com/keycloak/keycloak-quickstarts/pull/426.
