### ISSUE TITLE
require() of ES Module not supported.

### ISSUE THREAD

**Issue by ErenYeager80** [keycloak/keycloak#19569]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

Hi,
My code is written with type-script and uses commonjs as module in tsconfig. 
I updated keycloak-admin-client from 18.0.2 to 20.0.2 after that I got an error that was explained in the issue title.

### Version

21.0.2

### Expected behavior

Work as before

### Actual behavior

An error occurs

### How to Reproduce?

With upgrading lib to latest version

**Comment by jonkoops** [comment]
This is working as expected, we no longer ship the Admin Client as CommonJS. It is now a pure ESM module, this means all the pros and cons of [using ESM in Node.js](https://nodejs.org/api/esm.html#interoperability-with-commonjs) apply here.
