### ISSUE TITLE
Account Console II doesn't remove TOTP from UserStorage

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#19575]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When using UserStorage, user in the Account Console is not able to delete/remove TOTP authentication stored in UserStorage.

### Version

main

### Expected behavior

In the account console user can delete/remove totp authentication with provided UserStorage.

### Actual behavior

In the account console delete action doesn't work -> it fails on credential not found (credential stored in UserStorage).

### How to Reproduce?

Test: https://github.com/keycloak/keycloak/blob/ad3b264088e46aec927325ee9298509d7645e312/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/storage/BackwardsCompatibilityUserStorageTest.java#L220

Replace this disable line with the call from AccountHelper.deleteTotpAuthentication class:
https://github.com/keycloak/keycloak/blob/ad3b264088e46aec927325ee9298509d7645e312/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/util/AccountHelper.java#L83-L97

Old account console calls POST with Delete action on RestAccountFormService: /account/totp
![Screenshot from 2023-04-06 13-31-49](https://user-images.githubusercontent.com/61745358/230388925-d842012a-ac5d-4064-9977-5b4fccff5680.png)
![Screenshot from 2023-04-06 13-32-13](https://user-images.githubusercontent.com/61745358/230388996-cd2a6705-4d55-4c34-a405-210b8dbb0d7b.png)

New account console calls DELETE on UserResource: /account/credentials/{id}
![Screenshot from 2023-04-06 13-38-51](https://user-images.githubusercontent.com/61745358/230389043-8f6386ef-08b9-45a2-a74d-a632eb895282.png)

### Anything else?
Old Account Console did only disable not remove action when using UserStorage provider: https://github.com/keycloak/keycloak/blob/ad3b264088e46aec927325ee9298509d7645e312/server-spi-private/src/main/java/org/keycloak/utils/CredentialHelper.java#L118-L126
_No response_

**Comment by mposolda** [comment]
@lhanusov Thanks for the detailed report!

This looks like a regression, so seems like something to fix in Keycloak 22.
