### ISSUE TITLE
Maven 3.9 removes plexus-utils

### ISSUE THREAD

**Issue by mwhite-amplify** [keycloak/keycloak#19579]
### Description

According to the [release notes for Maven 3.9](https://maven.apache.org/docs/3.9.0/release-notes.html#potentially-breaking-core-changes-if-migrating-from-3-8-x):
> Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer. See [MNG-6965](https://issues.apache.org/jira/browse/MNG-6965).

This results in a build error when using a newer version of Maven.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/122919972/229623857-fb0cc9b8-98f5-4ea0-b7aa-de2b56ace2a8.png">

The solution is to make the following change to the main `pom.xml`:
```xml
<plugin>
    <groupId>com.samaxes.maven</groupId>
    <artifactId>minify-maven-plugin</artifactId>
    <version>${minify.plugin.version}</version>
    <dependencies>
         <dependency>
             <groupId>org.codehaus.plexus</groupId>
             <artifactId>plexus-utils</artifactId>
             <version>3.2.1</version>
        </dependency>
    </dependencies>
</plugin>
```

The `minify-maven-plugin` does have [a PR to fix this](https://github.com/samaxes/minify-maven-plugin/pull/176), but it's been open since February, and no commits have been made to the repo since 2016.

**Comment by jonkoops** [comment]
Looks like we're actually no longer using the `minify-maven-plugin` dependency anywhere (minification is now done with Rollup), so I've created #19583 to remove it.
