### ISSUE TITLE
Add a Expiration field for Admin Events

### ISSUE THREAD

**Issue by hitk6** [keycloak/keycloak#19584]
### Description

Add a Expiration field for Admin Events

Can we add "Expiration" field for Admin Events that can be set to X amount of days/months to clear the data ?. Similar to "Expiration" filed we have in Login Events.

Currently when the database size grows large there is no option to clean the older data. Only available option is to clean the Entire data which we want to avoid. 

Similar Issues:
https://issues.redhat.com/browse/KEYCLOAK-18295

**Comment by fattylego** [comment]
[Please refer to this. Keycloak admin event retention clean up]
(https://github.com/keycloak/keycloak/pull/12501)

**Comment by jonkoops** [comment]
This functionality already exists, you can configure this under 'Realm Settings' :arrow_right: 'Events' :arrow_right: 'Admin events settings' :arrow_right: 'Expiration':

![A screenshot showing the 'Expiration' setting.](https://github.com/keycloak/keycloak/assets/695720/78068fb3-369b-4e03-acef-d37a3742f381)
