### ISSUE TITLE
@keycloak/keycloak-admin-client doesn't provide an ability to use optional client scope for access token

### ISSUE THREAD

**Issue by NikitaKemarskiyLeia** [keycloak/keycloak#19586]
### Description

I have an optional client scope. I want access token to have this scope. I use the following approach to get token (I also have renewal logic there, but omitting it in the snippet):
```js
const kcAdminClient = new KeycloakAdminClient({
  baseUrl: config.leialogin.serverBaseUrl,
  realmName: config.leialogin.realm,
});
await kcAdminClient.auth(CREDENTIALS);
const accessToken = await kcAdminClient.getAccessToken();
```

The point is there is no interface to require a scope for the token. "/protocol/openid-connect/token" Keycloak endpoint accepts a "scope" parameter, but I can't set it using this library.

As a temporary solution I have come up with the following hack:
```js
const keycloakAdminClient = new KeycloakAdminClient({
  baseUrl: YOUR_URL,
  realmName: YOUR_REALM,
  requestConfig: {
    transformRequest: (data) => {
      try {
        const params = new URLSearchParams(data);

        params.append("scope", YOUR_SCOPE);

        return params.toString();
      } catch {
        return data;
      }
    },
  },
});
```
But obviously it's not the best solution, because currently it transforms all requests, which may cause unexpected issues.

### Motivation

To support Keycloak scopes feature in Admin Client interface.

**Comment by jonkoops** [comment]
I can see how this could be a useful feature, I've marked this as 'help wanted' so it can be picked up if deemed useful enough by the community.
