### ISSUE TITLE
Support custom UI fields for custom identity providers is gone in 21+ version

### ISSUE THREAD

**Issue by EvgeniGordeev** [keycloak/keycloak#19595]
### Description

Support of custom UI fields for custom `SocialIdentityProvider` OR `ClientAuthenticator` implementations in `keycloak.v2` theme. 

### Motivation

Custom Identity Providers need more fields than OIDC default ones 
<img width="1036" alt="Screenshot 2023-04-07 at 2 20 50 PM" src="https://user-images.githubusercontent.com/3843966/230666107-4df5ade2-92b4-4a39-b082-5c77222824b0.png">

For instance see this issue https://github.com/klausbetz/apple-identity-provider-keycloak/issues/13. For admin v1 theme this provider has custom template [realm-identity-provider-apple.html](https://github.com/klausbetz/apple-identity-provider-keycloak/blob/main/src/main/resources/theme-resources/resources/partials/realm-identity-provider-apple.html). 

Given that admin v2 theme is based on reactjs there is no way to extend it in theme resources and add additional fields on UI. See [ExtendedFieldsForm.tsx](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/component/ExtendedFieldsForm.tsx#L13):

```tsx
export const ExtendedFieldsForm = ({ providerId }: ExtendedFieldsFormProps) => {
  switch (providerId) {
    case "facebook":
      return <FacebookFields />;
    case "github":
      return <GithubFields />;
    case "google":
      return <GoogleFields />;
    case "openshift-v3":
    case "openshift-v4":
      return <OpenshiftFields />;
    case "paypal":
      return <PaypalFields />;
    case "stackoverflow":
      return <StackoverflowFields />;
    case "linkedin":
      return <LinkedInFields />;
    default:
      return null;
  }
};
```

### Details

Latest keycloak 21.0.2 does not support this. In the past it was an option.

**Comment by antikalk** [comment]
See https://github.com/keycloak/keycloak/issues/15344

**Comment by EvgeniGordeev** [comment]
Closing as a duplicate of #15344
