### ISSUE TITLE
A way to override internal SPI after KC 21

### ISSUE THREAD

**Issue by EvgeniGordeev** [keycloak/keycloak#19596]
### Description

Before KC 21.0.0 there was a way to override internal SPI and replace it with your own class:

* extend internal SPI class
* add custom META-INF service file
* add a small change instead of creating custom OIDC and duplicate everything from the internal SPI

This approach broke after this commit https://github.com/keycloak/keycloak/commit/a804400c842d9e1198a1c24b520498b1466c877f#diff-eea4abb789496423cf703ca63d968147abef72d694dae64b59b06153e3ca379dR97: 

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/3843966/230669877-f41202f4-d59a-461b-89d6-666bc4ef3586.png">

For instance, in this ticket https://github.com/keycloak/keycloak/issues/14258 I described a way to add a parameter to Google Identity Provider without creating a custom provider, or another example for token-exchange grant type in https://github.com/keycloak/keycloak/issues/17668. 

I see that these workarounds can be considered dirty and hacky but sometimes there is no other clean way especially in admin v2 theme when some of the extension options are not supported anymore - https://github.com/keycloak/keycloak/issues/19595.

### Motivation

Let developers to hotfix their custom implementations before it's fixed in KC.

**Comment by EvgeniGordeev** [comment]
Duplicated by https://github.com/keycloak/keycloak/issues/19867

**Comment by mposolda** [comment]
duplicates #19867

So I am closing this. This is fixed in Keycloak main and hence should be resolved in Keycloak 21.1.1 (will be probably released in next few days). Please re-test with Keycloak 21.1.1 once it is released and re-open if you still see issues.
