### ISSUE TITLE
Adding Persian language

### ISSUE THREAD

**Issue by sharifrezvani** [keycloak/keycloak#19604]
### Description

Hello

I want to create the Persian translations for Keycloak. I'm a novice developer though. I need more guidance and help.

Could you please guide me on how to do it?

I saw https://github.com/keycloak/keycloak/issues/15933 but I think it needs more work than those files only.

### Motivation

Adding Persian language so that more teams can benefit from Keycloak's amazing features.

**Comment by kasir-barati** [comment]
I do not know what you meant exactly, but AFAIC I use keycloakify to customize my login and registration pages. In keycloakify we use i18n lib to translate to as many lang as we want. You can look at the [keycloakify-starter](https://github.com/keycloakify/keycloakify-starter) if you like to know more.

**Comment by sharifrezvani** [comment]
@kasir-barati Thanks for your recommendation. However, I was talking about the built-in translations that one can choose from the Localization menu in Realm Settings in the Keycloak Administration Console. I want to contribute to the keycloak project so that everyone can choose the Persian language without customizing anything.

**Comment by sharifrezvani** [comment]
@jonkoops please guide me more.
[This](https://github.com/sharifrezvani/keycloak/tree/main) is my fork. And I want to add Persian language to front UI. I mean, login and password recovery, etc.

But I don't see other languages in the source code. Where should I add mine?

In the admin UI, I see other languages there. And I know where should I add mine. Yet I'm a little puzzled for the front UI.

Thanks

**Comment by jonkoops** [comment]
@sharifrezvani the strings you see there are only for the Admin Console. If you want to translate other parts of Keycloak you can look for files called `messages_en.properties`, these contain the original source  language (English).

If you duplicate these files and rename them to `messages_fa.properties`  and translate them to Farsi I believe they should be picked up.

**Comment by ahus1** [comment]
I assume this is now completed as part of PR #19747. 

We're currently rolling out Weblate to a web based translation, see https://github.com/keycloak/keycloak/blob/main/docs/translation.md

We plan to add the different langauges to weblate one-by-one. Leave a comment in #9270 if you are interested in maintaining a specific language.
