### ISSUE TITLE
Declarative User Profile attribute Add Validator Modal not responsive

### ISSUE THREAD

**Issue by JSCorpo** [keycloak/keycloak#19608]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Declarative User Profile attribute Add Validator Modal not responsive

When creating/editing user profile attribute, the add validator modal is not responsive to browser size. This causes the description column to be truncated and not scrollable.

![User Profile Add validator Modal](https://user-images.githubusercontent.com/127390108/230817926-9a0a1d1b-ea1b-4737-8c89-6dad87813839.jpg)

### Version

21.0.1

### Expected behavior

The add validator modal should be responsive to browser size or scrollable to see the description of each validator

### Actual behavior

The add validator modal is not browser responsive, causing the description column to be truncated and not scrollable.

### How to Reproduce?

Go to realm settings
Enable user profile
Create new user profile attribute
Add Validator

**Comment by ssilvert** [comment]
This should be fixed by https://github.com/keycloak/keycloak/issues/17795

I'm going to close this, but if you still see problems in the nightly build we can reopen.
https://github.com/keycloak/keycloak/releases/tag/nightly
