### ISSUE TITLE
Declarative user profile attribute options validator is not added correctly

### ISSUE THREAD

**Issue by JSCorpo** [keycloak/keycloak#19609]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Declarative user profile attribute options validator is not added correctly.

The options validator is added incorrectly, and the user profile attribute cannot be saved after the options validator has been added through the UI "Add Validator" modal

![Options validator](https://user-images.githubusercontent.com/127390108/230818828-b945790e-8e1d-4ba8-a111-cd3baedf57eb.jpg)

When trying to save after adding the options validator through the UI "Add Validator" modal, the error below will appear

![Options validator error](https://user-images.githubusercontent.com/127390108/230818955-4077d643-2e67-45b1-9c7e-27eb85675d0a.jpg)

There is a work around to save the options validator correctly into the attribute. That is through the JSON editor method.
![Options validator work around](https://user-images.githubusercontent.com/127390108/230819055-8b4415fd-fa51-44a2-86ef-31407db0ca91.jpg)

### Version

21.0.1

### Expected behavior

The options validator should be saved in these format
![Options validator correct format](https://user-images.githubusercontent.com/127390108/230819098-767606ed-18fd-4791-b150-16066337e6e1.jpg)

### Actual behavior

The options validator is currently being added in this format
![Options validator](https://user-images.githubusercontent.com/127390108/230819123-aa577b22-85b2-48e7-8518-08f6d31ec52b.jpg)

### How to Reproduce?

Go to realm settings
Enable User Profile
Add new user profile attribute
Add Validator
Add Options Validator with multiple options

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by ssilvert** [comment]
Please add test for options validator.

**Comment by jonkoops** [comment]
Not entirely sure how to fix this yet, but the change that regressed this is: https://github.com/keycloak/keycloak-ui/pull/4306
