### ISSUE TITLE
Declarative User Profile options validator dropdown list not displaying for self registration page

### ISSUE THREAD

**Issue by JSCorpo** [keycloak/keycloak#19612]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Declarative User Profile options validator dropdown list not displaying for self registration page

User profile attribute is configured with options validator
![user profile attribute validator options](https://user-images.githubusercontent.com/127390108/230870851-b7256f31-a033-4025-aaae-8826d192bf74.jpg)

The create user page is displaying the dropdown options for the new user profile attribute
![admin console create user options dropdown](https://user-images.githubusercontent.com/127390108/230870875-2a24a320-882c-4c97-b0b8-971057f06ce8.jpg)

But the self registration page is not displaying the dropdown options
![self registration page attribute](https://user-images.githubusercontent.com/127390108/230870946-aeee1ac8-b639-4981-b72a-c248fd8af933.jpg)

### Version

21.0.1

### Expected behavior

The self registration page should display the dropdown options just like the create user page when the user profile attribute is configured with options validator

### Actual behavior

The self registration page is not showing the options dropdown when the options validator is configured for the user profile attribute
![self registration page attribute](https://user-images.githubusercontent.com/127390108/230871183-ae5cd1e8-2486-478a-ab7f-bd755f4a7764.jpg)

### How to Reproduce?

go to realm settings
enable user profile
create new user profile attribute
configure options validator
go to self registration page

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by pedro-hos** [comment]
Hi @ssilvert I was looking into this issue. I notice that the User Profile validation is on:

https://github.com/keycloak/keycloak/blob/4f8d67c9fcbc1a50976128584369d9a1a9077ca2/js/apps/admin-ui/src/user/UserForm.tsx#L236

But I can't find where is the Registration page, to make sure that the https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user/UserProfileFields.tsx is used or not. 

Do you know the path or file used to user registration?

Thanks

**Comment by ssilvert** [comment]
@pedro-hos Registration is done using Freemarker.  Please ask questions like this in one of the community forums unless it relates directly to this issue..

**Comment by edewit** [comment]
what you need to do is add `inputType` = `select` to the annotations of the field

**Comment by pedro-hos** [comment]
> what you need to do is add `inputType` = `select` to the annotations of the field

Hey, @edewit cool. This should be done on https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user/UserProfileFields.tsx or should it be applied on some Java class?  I didn't find the correct file to make the change. 

Thanks

**Comment by edewit** [comment]
atm the admin-ui renders a dropdown based on the validator added, this is wrong because the register page uses the annotations for that, so when you add the `inputType` annotation then these pages will also render a dropdown:
![image](https://github.com/keycloak/keycloak/assets/51133/6cbfa5fc-d6ae-4152-9193-ce631acc0a63)
