### ISSUE TITLE
unexpected behavior, keycloak-js throwing not new Error object rather {error:''...} or undefined

### ISSUE THREAD

**Issue by shimondoodkin** [keycloak/keycloak#19626]
### Description

it expected to had thrown something usual, like a ` new Error('error message') ` 

if it is a  propagation of a previous error, a possible solution could be to modify the message of the existing error and throw it again (or set it to a promise.reject).

it was very strange to receive errors with values of undefined or like {error:'asdfasdf'} regular objects.

behavior like this is unexpected.

**Comment by jonkoops** [comment]
Could you provide examples of cases where no proper error is returned? Please provide a [minimal  reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by ssilvert** [comment]
Since we can't reproduce, I'm going to close this.
