### ISSUE TITLE
Keycloak data mix/switch

### ISSUE THREAD

**Issue by PedroDiasVeloso** [keycloak/keycloak#19633]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

We got two Keycloak instances in different servers, under the same domain but with different sub-domains.
Everything was working fine until we updated the ssl certificate after the old one expired.

After updating the ssl certificate, a specific realm that existed in one server with all its data is now available in the other and vice-versa, so keycloak data 1 is beeing read by server 2 and keycloak data 2 by server one, no config files were changed, just changed the crt files and updated the keystore.

Anyone knows why they got mixed ? Tried reverting the keystore to the old one but didn't work, remade the keystore files also, it seems some routing configuration or something like that has been changed in the background but have no idea why and how it happened, any suggestions ?

### Version

15.0.2

### Expected behavior

Both instances should use their own data without mixing with each other as they were doing before the certificate update.

### Actual behavior

Instances are reading each others data like they have been switched

### How to Reproduce?

The problem happened after changing the certificates in the keystore, can't rollback and reproduce again and couldn't find any other case online

**Comment by hmlnarik** [comment]
@keycloak/cloud-native @keycloak/core Could you please assess this issue?

**Comment by stianst** [comment]
I can't see this happening unless the database configuration was changed, as each separate server will point to its own database. Even if the two servers join the same cluster they would only exchange invalidation messages, and not data.

I'm going to close this one for now as there's not sufficient information to reproduce or investigate. If this is still an issue feel free to re-open, but you will need to provide some more information for us to be able to help.
