### ISSUE TITLE
Hibernate 6: Document use of JTA for Quarkus legacy store

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#19639]
### Description

When implementing the Hibernate 6 upgrade on Quarkus 3, the legacy store switched to JTA instead of resource local transactions. Due to this, the transaction manager is used on all transactions. 

There is a change of behavior for users as the default configuration of the transaction manager will use `quarkus.transaction-manager.default-transaction-timeout` which will time out after 60 seconds. 

If users run longer transactions, they would need to change this value. 

This should be noted in the migration notes. 

This is blocked until Quarkus 3 appears in main, as the documentation is currently prepared in the main branch to be ready for KC22 and we want to avoid conflicts.

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the heads up. How did the transaction timeout use to be configured before Quarkus 3?

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the heads up. How did the transaction timeout use to be configured before Quarkus 3?

**Comment by ahus1** [comment]
@vmuzikar - just had a look that Keycloak already sets this in "application.properties" to 300 overriding the default. So there is probably no need to change any CLI, as people also didn't change them before.

So we'll only have a note in the release notes / migration guide pointing to the default of Keycloak being 300. 

Sorry for the noise.

**Comment by ahus1** [comment]
Further investigations on #20119 showed that JTA was always enabled by default in previous releases, and possibly disabling it with the hidden parameter doesn't work in all cases. With MSSQL, there are tests that disable XA, so this is also still working as expected. So there is not really a change here, and this PR is obsolete. Some of the changes done for Q3 are rolled back in the PR above to restore some of the old behavior, still this is not essential to be included in any migration documentation.
