### ISSUE TITLE
Keycloak 21 using invalid chars for naming metrics

### ISSUE THREAD

**Issue by mfbmina** [keycloak/keycloak#19651]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Hello, I'm using Keycloak and exposing the metrics through an otel agent. Since we've updated to 21.0.5, the agent is complaining about some metric names like the example below:

```
[otel.javaagent 2023-04-11 19:56:57:446 +0000] [keycloak-cache-init] WARN io.opentelemetry.sdk.metrics.internal.InstrumentNameValidator - Instrument name "vendor.memoryPool.CodeHeap 'non-profiled nmethods'.usage.max" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter. Returning noop instrument.
```

A [related issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7448) has been reported to the `otel-agent` team but they understand it should be solved at the root. 

Keycloak version: 21.0.0+
Otel agent: 1.24.0

### Version

21.0.2

### Expected behavior

It should not warn.

### Actual behavior

Raises the following warn:

```
[otel.javaagent 2023-04-11 19:56:57:446 +0000] [keycloak-cache-init] WARN io.opentelemetry.sdk.metrics.internal.InstrumentNameValidator - Instrument name "vendor.memoryPool.CodeHeap 'non-profiled nmethods'.usage.max" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter. Returning noop instrument.
```

### How to Reproduce?

1. Install Keycloak 21.0.0 or higher. 
2. Install otel agent 1.24.0
3. Start keycloak

**Comment by sschu** [comment]
These are not the metrics I see. I get `vendor_memoryPool_CodeHeap__profiled_nmethods__usage_max_bytes` as raw metrics from Keycloak. That's a valid Prometheus metric (see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). It looks like your agent transforms the metric into a different format using dot notation and that goes wrong?

**Comment by trixpan** [comment]
@mabartos I see this as well. But my understanding is that is is otel <-> JVM related, not Keycloak related?
