### ISSUE TITLE
Group list isn't filtered based on permission like user lists

### ISSUE THREAD

**Issue by FasterLeaner** [keycloak/keycloak#19655]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

In Fine Grain Admin Permissions, we would like to grant permission on specific users in the specific group. The bug is that all groups have been retrieved even though some groups don't have the access right to view based on fine grain permission. In users, we don't have that issues. 

### Version

version 21.0.1

### Expected behavior

only retrieved the fine grained access group in the list. 

### Actual behavior

all groups have been retrieved 

### How to Reproduce?

How to Reproduce?
login to the admin console with the admin account

Create the new realm and give proper name as (Trial)

Switch to the Trial (realm) from the master realm in the master

create the Trial_admin user
4_1) Switch to the user menu, create the Trial_admin (user).
4_2) To the Trial_admin user, add the credential with your password.
4_3) To the Trial_admin user, add the realm-admin role. How to add the role
a) go to the Role mapping in the Users Menu
b) click on Assign role button, Assign roles pop up will appear
c) go to the Filter by realm roles, click on Filter by clients
d) search realm-admin and then add it

create group1_adminuser
5_1) click add user button to add group1_admin (user).
5_2) To the group1_admin user, add the credential with your password.
5_3) To the group1_admin user, add the query-clients, query-users and query-group roles. How to add the role
a) go to the Role mapping in the Users Menu
b) click on Assign role button, Assign roles pop up will appear
c) go to the Filter by realm roles, click on Filter by clients
d) search query-clients, query-users and query-group and then add it

create group2_adminuser
5_1) click add user button to add group2_admin (user).
5_2) To the group2_admin user, add the credential with your password.
5_3) To the group2_admin user, add the query-clients, query-users and query-group roles. How to add the role
a) go to the Role mapping in the Users Menu
b) click on Assign role button, Assign roles pop up will appear
c) go to the Filter by realm roles, click on Filter by clients
d) search query-clients, query-users and query-group and then add it

create group 1 under Groups menu
7_1) add the group1_admin into group 1

create group 2 under Groups menu
8_1)add the group2_admin into group 1

enable the fine grain permission in any group (permission enable)

To create the policy for group
10_1) go to the Clients menu
10_2) click on real-management and then go to the Authorization tab
10_3) go to the Policies tab under Authorization tab
10_4) Click on Create policy button to add group1_admin_policy
10_5) select Group in the pop up for policy type
10_6) in the group policy pop up, give the name (group1_admin_policy)
10_7) join the group to the group1 and then save
10_8) Click on the create policy button to add group2_admin_policy
10_9) repeat the step for group 2 admin policy from 10_5 to 10_7

apply those policy in the group 1 and group 2 in the permission tab, go to permission and select manage_members and view permission and then add the proper permission

logout form the admin console and switch to the Trial Realm

then login with group1_admin to the Trial Realm

by right, group1_admin should only see the group 1 in the group and should not see group 2.

**Comment by wernergiam** [comment]
How to Reproduce?
1) login to the admin console with the admin account
2) Create the new realm and give proper name as (Trial)
3) Switch to the Trial (realm) from the master realm in the master

create the Trial_admin user
4.1) Switch to the user menu, create the Trial_admin (user).
4.2) Go to the Trial_admin user, add the credential with your own password.
4.3) Go to the Trial_admin user, add the realm-admin role. 
       How to add the role
      a) go to the Role mapping in the Users Menu
      b) click on Assign role button, Assign roles pop up will appear
      c) go to the Filter by realm roles, click on Filter by clients
      d) search realm-admin and then add it

create group1_admin user
5.1) click add user button to add group1_admin (user).
5.2) go To the group1_admin user, add the credential with your own password.
5.3) go to the group1_admin user, add the query-clients, query-users and query-group roles. 
     How to add the role
    a) go to the Role mapping in the Users Menu
    b) click on Assign role button, Assign roles pop up will appear
    c) go to the Filter by realm roles, click on Filter by clients
    d) search query-clients, query-users and query-group and then add it

create group2_admin user
6.1) click add user button to add group2_admin (user).
6.2) go to the group2_admin user, add the credential with your own password.
6.3) go to the group2_admin user, add the query-clients, query-users and query-group roles. How to add the role
a) go to the Role mapping in the Users Menu
b) click on Assign role button, Assign roles pop up will appear
c) go to the Filter by realm roles, click on Filter by clients
d) search query-clients, query-users and query-group and then add it

create group 1 under Groups menu
7.1) add the group1_admin user into group 1

create group 2 under Groups menu
8.1)add the group2_admin user into group 2

enable the fine grain permission in any group (permission enable)
To create the policy for group
9.1) go to the Clients menu
9.2) click on realm-management and then go to the Authorization tab
9.3) go to the Policies tab under Authorization tab
9.4) Click on Create policy button to add group1_admin_policy
9.5) Select Group in the pop up for policy type
9.6) In the group policy pop up, give the name (group1_admin_policy)
9.7) join the group to the group1 and then save

![how_to_to_create_group1_admin_policy](https://user-images.githubusercontent.com/24427910/231444767-a48afa0e-e957-4c8d-a619-6c2cee2f895a.png)

9.8) Click on the create policy button to add group2_admin_policy
9.9) repeat the step for group 2 admin policy from 9.5 to 9.7

![how_to_to_create_group2_admin_policy](https://user-images.githubusercontent.com/24427910/231444922-995406a9-e9cb-4d8c-90e8-092bd63319c5.png)

apply those policy in the group 1 and group 2 in the permission tab, go to permission and select [manage_members ] and [view] permission and then add the proper permission

![how_to_to_create_group1_permission_admin_policy_managemembers](https://user-images.githubusercontent.com/24427910/231444993-adf8f930-54da-40bb-9dd9-98df5699620c.png)

![how_to_to_create_group1_permission_admin_policy_view](https://user-images.githubusercontent.com/24427910/231445028-161906ea-6386-4414-a400-067730bb5d59.png)


logout form the admin console and switch to the Trial Realm

 

then login with group1_admin to the Trial Realm

 

by right, group1_admin should only see the group 1 in the group and should not see group 2.

**Comment by wernergiam** [comment]
Repeat permission assignment for group 2 which was not shown on the last 2 screen shot.

**Comment by wernergiam** [comment]
Any one from keycloak team is looking into this issue to determine the way forward?

**Comment by wernergiam** [comment]
We have tested on latest version, i.e. keycloak 21.1.1, so this bug still remains.

**Comment by wernergiam** [comment]
Hi @edewit,

I have taken a look at the file modified for the fix, i.e. rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java, and i believe this would be a partial fix. The other place where the fix need to be included is when we create a new user. When creating a new user the **group1_admin** should be able to assign the new user to the groups it can view or manage, i.e. group 1, based on the fine grain access control.

![image](https://github.com/keycloak/keycloak/assets/24427910/19c57b43-a792-4b58-a07c-72b51f25b065)

**Comment by dmartinol** [comment]
@edewit I see the fix is not covering the case of Keycloak Admin REST API, e.g. using the `GET /{realm}/groups` we still list all the groups even if the user has `query-groups` role and the fine grain authorizations were set.
This is inconsistent wrt the `GET /{realm}/users`API that instead properly applies the permission filter.
Do yo want me to track this as a separate issue or can this one be re-opened?
BTW: I saw a possible fix that I can PR soon

**Comment by edewit** [comment]
right maybe create a separate issue for this as this is not an issue for the ui team, as you can see we introduced another endpoint that does take the fine grained settings into account under `ui-ext/groups`.

**Comment by guillestepup** [comment]
Hi @dmartinol, I have the same issue for the version 24.0.4 through REST API. Is there any advance with this issue? 

> @edewit I see the fix is not covering the case of Keycloak Admin REST API, e.g. using the `GET /{realm}/groups` we still list all the groups even if the user has `query-groups` role and the fine grain authorizations were set. This is inconsistent wrt the `GET /{realm}/users`API that instead properly applies the permission filter. Do yo want me to track this as a separate issue or can this one be re-opened? BTW: I saw a possible fix that I can PR soon
