### ISSUE TITLE
Remove profile disabling Account Console 2

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#19668]
### Description

Initial Jira issue is replaced by GH task, which is part of old Account console removal.

Remove profile: @DisableFeature(value = Profile.Feature.ACCOUNT2, skipRestart = true) and fix tests against Account console 2.

- [x] - RequiredActionEmailVerificationTest [PR](https://github.com/keycloak/keycloak/pull/19843)
- [x] - DemoServletsAdapterTest [PR](https://github.com/keycloak/keycloak/pull/19940)
- [x] - CookiesPathTest [PR](https://github.com/keycloak/keycloak/pull/19985)
- [x] - LoginTest.loginDifferentUserAfterDisabledUserThrownOut [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - LoginTest.loginRememberMeExpiredIdle [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - LoginTest.loginRememberMeExpiredMaxLifespan [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - AbstractBaseBrokerTest [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - AbstractCustomAccountManagementTest [PR](https://github.com/keycloak/keycloak/pull/20126)
- [x] - AbstractPhotozAccountResourcesAdapterTest [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - ClientInitiatedAccountLinkTest.testAccountLinkingExpired [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - SessionServletAdapterTest.testAccountManagementSessionsLogout [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - ConsentsTest [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - UserTest.loginShouldFailAfterPasswordDeleted [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - UserTest.resetUserPassword [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - UserTest.updateUserWithHashedCredentials [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - SessionTest [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - LoginEventsTest [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - AccountLinkTest [PR](https://github.com/keycloak/keycloak/pull/20080)
- [x] - ClientRedirectTest.testClientRedirectEndpoint [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - CookieTest [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - LDAPLegacyImportTest.loginLdap [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - LDAPProvidersIntegrationTest.deleteFederationLink [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - LDAPProvidersIntegrationTest.loginLdap [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - UserStorageTest [PR](https://github.com/keycloak/keycloak/pull/20165)
- [x] - PasswordHashingTest.testPasswordNotRehasedUnchangedIterations [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - RegisterTest.registerUserUmlats [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - SSOTest.loginSuccess [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - AccountPageTest [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - OIDCAdvancedRequestParamsTest.promptNoneConsentRequired [PR](https://github.com/keycloak/keycloak/pull/19362)
- [x] - TrustStoreEmailTest [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - BrowserFlowTest.testAlternativeNonInteractiveExecutorInSubflow [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - JavascriptAdapterTest.grantBrowserBasedApp [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - SocialLoginTest [PR](https://github.com/keycloak/keycloak/pull/20023)
- [x] - ResetPasswordTest.resetPasswordLink [PR](https://github.com/keycloak/keycloak/pull/19362)
- [ ] - ResetPasswordTest.resetPasswordLinkNewTabAndProperRedirectAccount
- [ ] - OIDCAdvancedRequestParamsTest
- [ ] - SessionSpringBootTest
- [ ] - RPInitiatedLogoutTest.logoutWithRememberMe
- [ ] - EmailEventListenerTest
- [ ] - AccountLinkSpringBootTest

Remove profile only - tests are passing:
- [x] - AbstractKerberosSingleRealmTest - [PR](https://github.com/keycloak/keycloak/pull/19728)
- [x] - KerberosLdapTest - [PR](https://github.com/keycloak/keycloak/pull/19728)
- [x] - LDAPPasswordModifyExtensionTest.ldapPasswordChangeWithAccountConsole - [PR](https://github.com/keycloak/keycloak/pull/19728)
- [x] - LDAPProvidersIntegrationTest.ldapPasswordChangeWithAccountConsole - [PR](https://github.com/keycloak/keycloak/pull/19728)
- [x] - OIDCScopeTest.testRefreshTokenWithConsentRequired - [PR](https://github.com/keycloak/keycloak/pull/19728)

Cleanup imports:

- [x] - AdminConsoleLandingPageTest - [PR](https://github.com/keycloak/keycloak/pull/19700)
- [x] - LogoutTest - [PR](https://github.com/keycloak/keycloak/pull/19700)
- [x] - CorsExampleAdapterTest - [PR](https://github.com/keycloak/keycloak/pull/19700)

**Comment by mposolda** [comment]
@lhanusov I am accidentally closed this, but now I reopened. Sorry for the confusion :-)
