### ISSUE TITLE
Promote Account Console v3 to 'default'

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#19663]
The new Account Console introduced under #19641 must be promoted to 'default' so that more users will have access to it.

**Comment by Eng-Fouad** [comment]
Are there any new resource bundle messages that need to be translated? I will add it to Arabic locale messages: https://github.com/keycloak/keycloak/pull/17090

**Comment by Eng-Fouad** [comment]
Also, I suggest that you notify locale messages maintainer for any future additions. I just added PR to add missing Arabic locale messages that were added in recent commits:

https://github.com/keycloak/keycloak/pull/19684

**Comment by jonkoops** [comment]
> Are there any new resource bundle messages that need to be translated? I will add it to Arabic locale messages: #17090

This is still an experimental feature at this time, which means a lot of things will change. So we are not looking to localize this at the moment. However this will become a concern in the near future.
