### ISSUE TITLE
Invalid parameter redirect_uri when using an invalid client_id

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#19662]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

When using an invalid client_id the error message states the redirect_uri is invalid. In the past this used to be the case, but for some reason this behaviour has changed.

### Version

main

### Expected behavior

Error screen should show the message:

"Invalid parameter: client_id"

### Actual behavior

![image](https://user-images.githubusercontent.com/2271511/231432074-f53e5642-51b8-4017-8118-259a235b8c44.png)

### How to Reproduce?

* Open the admin console and wait for it to redirect to the login page
* Change the `client_id` in the request to an invalid `client_id`

**Comment by mposolda** [comment]
We discussed with @stianst to revert this. Keycloak will allow client enumeration (we still allow it on some places as it is quite hard to avoid it entirely).
