### ISSUE TITLE
Sessions displayed multiple times

### ISSUE THREAD

**Issue by nblock** [keycloak/keycloak#19673]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The "Sessions" page at `/admin/master/console/#/master/sessions` has multiple entries for the same session when multiple clients have been visited by a user.

### Version

21.0.2

### Expected behavior

The "Sessions" page has a "Clients" column. If a user visits multiple clients, there should be a single row with multiple entries in the "Clients" column. Just like in Users - Sessions:

![image](https://user-images.githubusercontent.com/131119/231503539-882d88ea-d1eb-4d66-9004-881261e5b859.png)

### Actual behavior

For each visited client, a separate row is displayed in the "Sessions" page. All rows list all clients in their "Clients" column:

![image](https://user-images.githubusercontent.com/131119/231504112-1a198d40-13a4-47e5-83ef-98d23adfe098.png)

The above image should only have a single row.

### How to Reproduce?

* Login to Security Admin Console as `admin`
* Visit the account console as `admin`
* Open the "Sessions" page

**Comment by ssilvert** [comment]
I have recreated this.

**Comment by lrozenblyum** [comment]
Hello! Any chance it would be ported to the 21.1.1 bugfix release? Pretty important issue.

**Comment by jonkoops** [comment]
We're working on getting a fix in, so I expect this will be in the patch release. Please do refrain from putting unnecessary comments on threads as we are already quite overwhelmed with notifications.
