### ISSUE TITLE
REST API doesn't allow client creation with device grant despite documentation

### ISSUE THREAD

**Issue by Shryne** [keycloak/keycloak#19688]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

The `ClientRepresentation` model from https://www.keycloak.org/docs-api/21.0.2/rest-api/index.html#_clientrepresentation 
mentions a field named oauth2DeviceAuthorizationGrantEnabled. However, this field is not supported.

### Version

21.0.2

### Expected behavior

I would like to create a client with activated device authorisation grant.

### Actual behavior

A call like this:

POST .../admin/realms/myrealm/clients
header: 
  Authorization: Bearer ey...
body:
```json
{
  "oauth2DeviceAuthorizationGrantEnabled": true
}
```
fails with this error:
```json
{
  "error": "Unrecognized \"oauth2DeviceAuthorizationGrantEnabled\" (class ...)"
}
```

### How to Reproduce?

Call POST .../admin/realms/myrealm/clients as described.

**Comment by Shryne** [comment]
You should ask this question on Stackoverflow.

**Comment by JonSzeto821** [comment]
@Shryne I looked into this issue and it appears that the `oauth2DeviceAuthorizationGrantEnabled` value is not used in any capacity within Keycloak - as you mentioned. However, if device auth is needed, it's recommended to use this attribute (`OAUTH2_DEVICE_AUTHORIZATION_GRANT_ENABLED`) instead: https://github.com/keycloak/keycloak/blob/main/server-spi/src/main/java/org/keycloak/models/OAuth2DeviceConfig.java#L42

Additionally, to check this attribute, this method returns if device auth is enabled: https://github.com/keycloak/keycloak/blob/main/server-spi/src/main/java/org/keycloak/models/OAuth2DeviceConfig.java#L117

Hope this helps

**Comment by jsorah** [comment]
To clarify @JonSzeto821's point one would have to use the client attributes - this is the most minimal client I could create myself that was still functional:

```json
{
    "attributes": {
        "oauth2.device.authorization.grant.enabled": "true"
    },
    "clientId": "device-auth-client-test",
    "publicClient": "true",
    "standardFlowEnabled": "false"
}

```

**Comment by Shryne** [comment]
That works fine. Thanks :)
