### ISSUE TITLE
SAML Encryption: Missing Support for http://www.w3.org/2009/xmlenc11#rsa-oaep

### ISSUE THREAD

**Issue by dpulrichth** [keycloak/keycloak#19689]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

Since Keycloak 21 it is no longer possible to decrypt SAML Assertions encrypted with Algorithm `http://www.w3.org/2009/xmlenc11#rsa-oaep` using MGF1 with SHA256. Only `http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p` is supported. This was previously discussed here https://github.com/keycloak/keycloak/pull/15985#issuecomment-1359756472. However the XMLEnc specification referenced there is outdated and misses a key detail: RSA-OAEP can both be declared using  `http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p` (meaning RSA OAEP with MGF1 with SHA1) AND `http://www.w3.org/2009/xmlenc11#rsa-oaep`. The latter MAY be combined with a MGF declaration, allowing for instance RSA OAEP with MGF1 with SHA256.

We are using an IdP that encrypts SAML Assertions like this:

```xml
     <xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep">
      <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod>
      <xenc11:MGF xmlns:xenc11="http://www.w3.org/2009/xmlenc11#" Algorithm="http://www.w3.org/2009/xmlenc11#mgf1sha256"></xenc11:MGF>
     </xenc:EncryptionMethod>
```

This appears to be perfectly valid according to the current XMLEnc spec: https://www.w3.org/TR/xmlenc-core1/#sec-RSA-OAEP

Up until Keycloak 20 this was supported (kind of at least, seeing as encryption and signature keys were mixed), but the changes introduced through https://github.com/keycloak/keycloak/pull/15985 limit Keycloak to just http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p and http://www.w3.org/2001/04/xmlenc#rsa-1_5. 

This breaks existing functionality and means we cannot update to Keycloak 21.

### Version

21.0.2

### Expected behavior

http://www.w3.org/2009/xmlenc11#rsa-oaep as SAML encryption algorithm is supported, including declaring the MGF to be used as defined in https://www.w3.org/TR/xmlenc-core1/#sec-RSA-OAEP

### Actual behavior

http://www.w3.org/2009/xmlenc11#rsa-oaep is not supported for SAML encryption

### How to Reproduce?

Trying to decrypt a SAML Assertion encrypted like this

```xml
     <xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep">
      <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod>
      <xenc11:MGF xmlns:xenc11="http://www.w3.org/2009/xmlenc11#" Algorithm="http://www.w3.org/2009/xmlenc11#mgf1sha256"></xenc11:MGF>
     </xenc:EncryptionMethod>
```

**Comment by hbitsch** [comment]
+1
This breaks compatibility with the German ELSTER/NEZO IdP.

**Comment by dpulrichth** [comment]
@mhajas @mposolda Could you take a look at this issue? Seems to me this is related to https://github.com/keycloak/keycloak/pull/15985.

**Comment by rmartinc** [comment]
For what I see the previous issue via PR https://github.com/keycloak/keycloak/pull/15985 restricted the SAML algorithms for key wrapping to the ones specified in the class [SAMLEncryptionAlgorithms](https://github.com/keycloak/keycloak/blob/21.1.0/services/src/main/java/org/keycloak/protocol/saml/SAMLEncryptionAlgorithms.java#L33-L34). Therefore only `http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p` and `http://www.w3.org/2001/04/xmlenc#rsa-1_5` are allowed now. I will try to add `http://www.w3.org/2009/xmlenc11#rsa-oaep` (AFAIK `rsa-oaep-mgf1p` is a specific `rsa-oaep`, so the latter is more generic).

**Comment by mhajas** [comment]
@opdt I think we should consider backporting this to 21.1.x. 

@rmartinc @mposolda I am adding this to backport board please remove it if you disagree with it.
