### ISSUE TITLE
Unable to fetch key-store credentials from file vault in quarkus.properties

### ISSUE THREAD

**Issue by Varshaa21** [keycloak/keycloak#19709]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Since I do not want to store the https-key-store-password in the keycloak configuration file in plain text, I am trying to put the credentials in file vault and fetch from there in quarkus.properties file. I have built the quarkus with file vault lib extension (keycloak version 21.0.2)

Configuration in quarkus.properties -

quarkus.http.ssl.certificate.key-store-key-alias=my_alias
quarkus.http.ssl.certificate.key-store-file=C:\test.keystore

quarkus.http.ssl.certificate.credentials-provider=quarkus.file.vault.provider.myprovider
quarkus.file.vault.provider.myprovider.path=C:/pass.p12
quarkus.file.vault.provider.myprovider.secret=providerpass

Error seen in the log while running kc.bat -
2023-04-13 11:45:57,025 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2023-04-13 11:45:57,031 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Unable to start HTTP server
2023-04-13 11:45:57,033 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.io.IOException: Keystore was tampered with, or password was incorrect
2023-04-13 11:45:57,034 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Keystore was tampered with, or password was incorrect
2023-04-13 11:45:57,037 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Password verification failed

The keystore is fine and have double checked the password and alias stored in the keystore. Not sure why I am seeing the above error.

Although, using similar configuration, I am able to get the datasource config working.

Any help on this would be appreciated.

### Version

21.0.2

### Expected behavior

Should be able to fetch the credentials from file vault.

### Actual behavior

Seeing error - Unable to start HTTP server

### How to Reproduce?

1. Add quarkus-file-vault extension to pom.xml
2. Add Configuration in quarkus.properties - 

quarkus.http.ssl.certificate.key-store-key-alias=my_alias
quarkus.http.ssl.certificate.key-store-file=C:\test.keystore

quarkus.http.ssl.certificate.credentials-provider=quarkus.file.vault.provider.myprovider
quarkus.file.vault.provider.myprovider.path=C:/pass.p12
quarkus.file.vault.provider.myprovider.secret=providerpass

**Comment by Pepo48** [comment]
Hey @Varshaa21,

first of all thanks for the report. We don't have support for Quarkus File Vault extension in Keycloak. Instead, you can take a look at the [KeyStore Config Source](https://github.com/keycloak/keycloak/pull/20375) that I worked on recently and actually it got merged to the main just today. I think it could help you to achieve exactly what you need. At the same time, I worked on [Keycloak Keystore Vault](https://github.com/keycloak/keycloak/pull/19644), which is a new implementation of the Vault SPI. This allows you to store and read secrets from a Java keystore and use them within various places of the Administration console (in the same way like with a Plaintext File Vault). You can find more information in the documentation.

I'm closing this issue for now, but feel free to reopen it, if necessary.
Thanks.
