### ISSUE TITLE
Cannot add multiple regular expression password policies

### ISSUE THREAD

**Issue by y-tabata** [keycloak/keycloak#19713]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Related JIRA: https://issues.redhat.com/browse/KEYCLOAK-17853

Password policies other than the regular expression password policy are enough to add only once.
However, regarding the regular expression password policy, it should be possible to add multiple times.

As shown in the code below, it is designed to be added multiple times, but it can only be added once.
https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/policy/RegexPatternsPasswordPolicyProviderFactory.java#L64-L67

### Version

20.0.3

### Expected behavior

Regular expression password policy can be possible to add multiple times.

### Actual behavior

Regular expression password policy cannot be possible to add multiple times.

### How to Reproduce?

Add multiple regular expression password policies.

**Comment by max-petrovich** [comment]
I'm also interested in adding Regex a multiple times!
