### ISSUE TITLE
Page title hard-coded in new admin console.

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#19733]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The page title, "Keycloak Administration UI" is hard-coded in index.ftl/index.html.

At the very least, we should allow the user to change this in theme.properties.  Ideally, it should be localized.

### Version

main

### Expected behavior

Not hard-coded

### Actual behavior

hard-coded

### How to Reproduce?

There is no good way to change the title of the page.  The only way currently is to replace index.ftl.

**Comment by jonkoops** [comment]
@ssilvert I think it's time we introduce a dedicated free-marker template instead of doing a 'find and replace' on the template compiled from Vite.

**Comment by ssilvert** [comment]
@jonkoops The actual problem is that we somehow ended up with two copies of index.html.  That's originally why we did the `find and replace`.  That way, there is only one index.html.   So when index.html changes, we don't have to remember to update both the Vite version and the Freemarker version.

Please open a new issue for that.

**Comment by jonkoops** [comment]
@ssilvert Created https://github.com/keycloak/keycloak/issues/19750 for this.

**Comment by ssilvert** [comment]
Also see https://github.com/keycloak/keycloak/issues/19761 for localization.
