### ISSUE TITLE
Email settings erased after any change on realm settings

### ISSUE THREAD

**Issue by Brundolf** [keycloak/keycloak#19746]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Email settings keep reverting to blank after any other realm settings update. Only way to go around it for now is to setup everything and do email settings at the end. 

### Version

21.0.2

### Expected behavior

Email Settings remain as were saved before other realm changes

### Actual behavior

Email Settings completely wiped after change. 

### How to Reproduce?

Steps to reproduce: 

1. Setup email on admin user
2. Create new realm
3. Setup email for realm
4. Change any other realm settings (in my case disable https requirements for incoming requests) 
5. go back to email settings

**Comment by kaustubh-rh** [comment]
Hi @mposolda @jonkoops able to reproduce the issue , can I work on this ?

**Comment by jonkoops** [comment]
Sure @kaustubh-rh, I'll assign you. Feel free to create a PR.

**Comment by tirth1** [comment]
@kaustubh-rh are you still working on this? I would like to take this one.

**Comment by jonkoops** [comment]
@tirth1 I am assigning this to you, since we haven't heard from @kaustubh-rh for a while. Let me know if more information is needed!
