### ISSUE TITLE
Use a proper FreeMarker template for the new consoles

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#19750]
To make it easier to work on the new Account and Admin Consoles we should have dedicated `index.ftl` template files rather than [replacing the output](https://github.com/keycloak/keycloak/blob/8f4c721a7d39683823e5427d980a17949fb87c97/js/apps/admin-ui/pom.xml#L57-L116) HTML from Vite with FreeMarker bits.

**Comment by ssilvert** [comment]
The bottom line is that we should not maintain two index files.  We should not have both an index.html and an index.ftl.  

In the past, we had one index.html that would work with Vite/Snowpack in development.  When we built for bundling into the Keycloak distro, we would use Maven to modify index.html and output index.ftl.  That way, we don't have to maintain two versions of what is essentially the same file.

**Comment by edewit** [comment]
so we can close this one?

**Comment by jonkoops** [comment]
No, not yet. We are still finding an replacing existing HTML templates that are compiled from Vite.
