### ISSUE TITLE
LDAP vendors missing in User federation configuration

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#19762]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

When trying to configure the LDAP user federation some vendors are missing from the list.
With an existing LDAP federation configuration that had the value `Novell eDirectory` shows empty.

Note: I cannot reproduce this on versoin 21.x, because the old admin console is no longer present. I have larger instances where the new admin console is not rolled out to admins, yet. It is not possible to configure any ldap federations in this scenario.

### Version

20.0.5

### Expected behavior

All previously available vendors should be available and shown when opening the config.

### Actual behavior

Only Active Directoy and Red Hat Directory Server are shown.

### How to Reproduce?

Add a new LDAP user federation and open the vendor drop down list.

### Anything else?

This seems to be caused by changes in [#97ae90de](https://github.com/keycloak/keycloak/commit/97ae90de888362c82f6e87ef699035e573ca70ff). 
The admin console still checks for the value `community` in the ServerInfo profile name: https://github.com/keycloak/keycloak/blob/20.0.5/themes/src/main/resources/theme/base/admin/resources/js/controllers/users.js#L1531

**Comment by jonkoops** [comment]
We're not going to be fixing things in the old Admin Console so this would have to be fixed in the new one. Is the same issue present in new Admin Console as well?

**Comment by sventorben** [comment]
@jonkoops No, the new one works as expected.

**Comment by jonkoops** [comment]
Thanks for verifying that. Since we don't plan on creating fixes for older versions of Keycloak (and by extension the old Admin Console) I am closing this issue.
