### ISSUE TITLE
Group Membership nested token claimnot working

### ISSUE THREAD

**Issue by bogi158** [keycloak/keycloak#19767]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When using the group membership mapper to LDAP groups to a claim that needs to be nested, the claim on the JWT will be actually a string and not a nested object.

### Version

21.0.2

### Expected behavior

Mapper Type: Group Membership
Name: groups
Token Claim Name: https://hasura\.io/jwt/claims.x-hasura-groups

```json
"https://hasura.io/jwt/claims": {
    "x-hasura-groups": [
      "JIRA_User",
      "CONFLUENCE_User",
      "BITBUCKET_USER"
    ],
}
```

### Actual behavior

Mapper Type: Group Membership
Name: groups
Token Claim Name: https://hasura\.io/jwt/claims.x-hasura-groups

```json
"https://hasura\\.io/jwt/claims.x-hasura-groups": [
    "JIRA_User",
    "CONFLUENCE_User",
    "BITBUCKET_USER"
  ],
```

### How to Reproduce?

- Connect to LDAP or create some groups on Keycloak.
- Configure the mapper:

Mapper Type: Group Membership
Name: groups
Token Claim Name: https://hasura\.io/jwt/claims.x-hasura-groups

- Enable the claims to be sent on the JWT
- Retrieve a JWT by logging in
- Decode the JWT

### Anything else?

I tried to not escape the first dot, and the claims is again sent back as a sigle string. Seems like the mapper never creates a nested object.

```json
  "https://hasura.io/jwt/claims.x-hasura-groups": [
    "JIRA_User",
    "CONFLUENCE_User",
    "BITBUCKET_USER"
  ],
```

This is a critical problem for our project as Hasura can only read claims inside `https://hasura.io/jwt/claims`.
The nested objects work with every other mapper, it is just the Groups Membership that is breaking.

**Comment by ssilvert** [comment]
@bogi158 You don't have reason to believe this is a problem in the admin UI.  Is that correct?

**Comment by bogi158** [comment]
> u

no it is not the admin UI, I selected the wrong label

**Comment by BlessedDisco** [comment]
I am encountering exactly the same behavior on Keycloak version 20.0.5.

**Comment by rmartinc** [comment]
Hi @bogi158!

Yes, this is a bug in the group membership OIDC mapper. It's not related to ldap, it doesn't matter if the groups are in ldap or just in the DB. I'll try to provide a PR when I get some time to spend on it.

**Comment by Miggets7** [comment]
Also experiencing this with latest release version 21.1.1. Would be nice if the PR is accepted so it can be released soon
