### ISSUE TITLE
Custom providers are not loaded properly in KC21

### ISSUE THREAD

**Issue by avanlangup** [keycloak/keycloak#19777]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

We encountered side effect on custom providers due to this commit  
 
https://github.com/keycloak/keycloak/commit/a804400c842d9e1198a1c24b520498b1466c877f#diff-eea4abb789496423cf703ca63d968147abef72d694dae64b59b06153e3ca379d

### Version

21.0.2

### Expected behavior

Custom providers with same IDs are loaded with a priority determined by _order_ function 

### Actual behavior

Only default KC providers are loaded

### How to Reproduce?

We define custom account provider

UpFreeMarkerAccountProvider extends FreeMarkerAccountProvider implements AccountProvider {
..........
}

public class UpFreeMarkerAccountProviderFactory extends FreeMarkerAccountProviderFactory {

    @Override
    public AccountProvider create(KeycloakSession session) {
        return new UpFreeMarkerAccountProvider(session);
    }

    @Override
    public String getId() {
        return "freemarker";
    }

    @Override
    public int order() {
        return super.order() + 1;
    }
}

**Comment by stianst** [comment]
Added an umbrella issue for these issues here:
https://github.com/keycloak/keycloak/issues/19867

**Comment by stianst** [comment]
Looking at https://github.com/keycloak/keycloak/issues/19335 it seems like it may now be possible to override a provider by ID again in 21.1.0.

**Comment by gvonroten** [comment]
> Looking at #19335 it seems like it may now be possible to override a provider by ID again in 21.1.0.

I asked in that issue already, but can someone explain what was done to make this work again? Because it does not for me in 21.1.0 and I don't see how it would when looking at the commit referenced in that issue.

**Comment by mposolda** [comment]
duplicates #19867

So I am closing this. This is fixed in Keycloak main and hence should be resolved in Keycloak 21.1.1 (will be probably released in next few days). Please re-test with Keycloak 21.1.1 once it is released and re-open if you still see issues.
