### ISSUE TITLE
Wrong title for federation provider when you click on federation link

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#19774]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The following screenshot shows writeable-property-file fedaration
![Screenshot from 2023-04-18 10-15-17](https://user-images.githubusercontent.com/3359545/232715483-44c2ad0e-1e95-4d1e-a874-a48a548cbbf9.png)
When you click on it, it shows the correct title
![Screenshot from 2023-04-18 10-17-42](https://user-images.githubusercontent.com/3359545/232716079-c9b16ae8-97bd-49c8-81a0-be45183f7e82.png)
The following screenshot shows a user from federated provider
![Screenshot from 2023-04-18 10-13-05](https://user-images.githubusercontent.com/3359545/232715487-17e0bdb3-611e-4dba-93b1-856a2dbba5df.png)
When you click on "Federation link" it show wrong LDAP title
![Screenshot from 2023-04-18 10-14-26](https://user-images.githubusercontent.com/3359545/232715485-2ceafb87-f59a-4dc2-bd70-675d87988a38.png)

### Version

21.0.2

### Expected behavior

Show correct title writeable-property-file

### Actual behavior

Showing wrong LDAP title

### How to Reproduce?

Deploy https://github.com/keycloak/keycloak-quickstarts/tree/main/user-storage-simple and debug org.keycloak.quickstart.ArquillianSimpleStorageTest#testUserWritableFederationStorage test. Then go to admin UI

**Comment by jonkoops** [comment]
Duplicate of #20097
