### ISSUE TITLE
Javascript example not printing errors

### ISSUE THREAD

**Issue by andymunro** [keycloak/keycloak#19792]
### Description

Red Hat developer Stacey Mosier reports that the Javascript example in the Securing Apps guide is not printing errors.  

https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

She suggests it can be updated to use console.error instead of alert:

```js
keycloak.init(options)
  .then(function(authenticated) {
    console.log('rh_keycloak:' + (authenticated ? 'authenticated' : 'not authenticated'));
  }).catch((error) => {
    for (const property in error) {
    console.error(`${property}: ${error[property]}`);
  }
});
```

**Comment by jonkoops** [comment]
I don't see why the original code would not be working, that said I am all for changing this to `console.log`.

**Comment by andymunro** [comment]
Thanks, @jonkoops.   I am not exactly sure about the lines to replace in that example.  Do you know what the correct example would look like?

**Comment by jonkoops** [comment]
@andymunro if this has priority you can assign it to me, if not I have marked the issue as 'help wanted' so that it can be a good first contribution. In essence all instances of `alert` can be replaced pretty much directly with `console.log`.

**Comment by andymunro** [comment]
Thanks, @jonkoops.  I will follow up with Stacey and address it myself.
