### ISSUE TITLE
Custom SignatureProviderFactory is not working as expected after Keycloak 21 upgrade

### ISSUE THREAD

**Issue by arjungrootan** [keycloak/keycloak#19805]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

We recently did a keycloak upgrade from 19.0.3 to 21.0.2. We are extending ES256SignatureProviderFactory with CustomES256SignatureProviderFactory for algorithms such as ES256, ES384, ES512 for the support of additional key providers. Our extended class requires the provider_id to be the same as the internal classes, since the Algorithm name is the same as the provider_id and it is not possible to use a custom provider id. Up until KC 20.0.x we have been able to get our custom Provider to work. In KC 21 our version doesn't get executed even though we get a warning at startup about "This SPI is internal and may change without notice". 
After some analysis, we found out that, this happens due to this change (https://github.com/keycloak/keycloak/commit/a804400c842d9e1198a1c24b520498b1466c877f#diff-eea4abb789496423cf703ca63d968147abef72d694dae64b59b06153e3ca379dR97).

Can this still be done in the new KC 21.0.x version?

Please note: The algorithm in the token should be as per standard, for example "ES256" for tokens signed by ES256 Signature Providers, so we cannot create custom providers with different provider ids like "ES256-custom" to ensure my custom Provider is always picked up for the client. 

We need a mechanism to ensure our custom provider is preferred over default provider in Keycloak or the one-to-one mapping between Algorithm name and the provider id of the Signature Provider should be changed to differentiate between different providers for the same algorithm. 

### Version

21.0.2

### Expected behavior

The custom signature provider factory with the same id as the algorithm should be loaded first as in older Keycloak versions up to 20.0.5

### Actual behavior

The custom signature provider factory with the same id as the algorithm is replaced with default keycloak signature provider factory

### How to Reproduce?

1. Create two custom classes extending AsymmetricSignatureSignerContext and AsymmetricSignatureVerifierContext, then place custom logic for sign and verify.
2. Create another class extending SignatureProvider to refer to custom SignatureSignerContext and SignatureVerifierContext. Create a factory for the same by extending SignatureProviderFactory and have the ID same as ID (algorithm) of the internal class.
Example: Use Algorithm.ES256 to emulate custom ES256SignatureProvider.java
3. Package this as a jar and copy it to the providers folder.
4. Start keycloak - ./kc.sh start-dev
5. Refer the logs: [org.keycloak.services] (build-30) KC-SERVICES0047: openid-connect (org.test.oidc.TestOIDCLoginProtocol) is implementing the internal SPI login-protocol. This SPI is internal and may change without notice
6. Configure the custom key provider under the keys tab.
7. Create an OIDC Based client and configure with proper algorithm for sign and verify.
9. Attempt to authenticate with the client. The signing fails with default keycloak signature factory.

### Anything else?

Similar Issues: 
https://github.com/keycloak/keycloak/issues/19335
https://github.com/keycloak/keycloak/issues/19530
https://github.com/keycloak/keycloak/issues/19777

**Comment by stianst** [comment]
Added an umbrella issue for these issues here:
https://github.com/keycloak/keycloak/issues/19867

**Comment by mposolda** [comment]
duplicates #19867

So I am closing this. This is fixed in Keycloak main and hence should be resolved in Keycloak 21.1.1 (will be probably released in next few days). Please re-test with Keycloak 21.1.1 once it is released and re-open if you still see issues.
