### ISSUE TITLE
User attribute mappers resulting in JSON objects produce invalid tokens

### ISSUE THREAD

**Issue by armfergom** [keycloak/keycloak#19808]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

First of all, I am hoping this is an actual bug. After lots of investigations, googling and reading up on the documentation, I have not been able to figure this out. 

We have a client for which we have created a bunch of User Attribute mappers. 5 of them result in the creation of a nested JSON object in the access and id tokens.

This is how we configured one of those mappers:

![Screenshot 2023-04-19 at 14 39 01](https://user-images.githubusercontent.com/10669883/233077234-bccc8977-a060-43f5-af47-ce4c76d899c9.png)

And as I stated, there are another 4 that are analogous to this one. 

The resulting access and id tokens look like this:

```
{
...
"address": {
    "country": "SWE",
    "postal_code": "11160",
    "is_verified": "true",
    "city": "STOCKOLM",
    "street_name": "Gatan218 19"
  },
  ...
  }
```

When a user authenticates the access token is produced successfully so up until here everything is alright. 

If we then try to operate with these tokens, Keycloak will shout out claiming that the token is invalid. We have been able to reproduce this by calling the `/logout` endpoint and passing the id token in the `id_token_hint` param. As commented, Keycloak says the token is invalid. 

However, if we change our mappers and map the exact same values into separate claims, say:

```
{
...
    "address_country": "SWE",
    "address_postal_code": "11160",
    "address_is_verified": "true",
    "address_city": "STOCKOLM",
    "address_street_name": "Gatan218 19"
  ...
  }
```

Then everything works as expected and we can successfully call the `/logout` endpoint. 

I have not found any other errors in the logs other than the plain "Invalid token" message and I have not been able to find anywhere any reference saying that what we are doing is wrong in any way.

### Version

20.0.2

### Expected behavior

We can use id/access tokens with extra claims that are JSON objects generated by User Attribute Mappers successfully for calls like the `/logout` endpoint.

### Actual behavior

When we use id/access tokens with extra claims that are JSON objects generated by User Attribute Mappers Keycloak considers the tokens invalid when calling endpoints like `/logout`

### How to Reproduce?

Create mappers as described in the issue that result into a JSON object and then try to call the `logout` endpoint with it.

**Comment by jsorah** [comment]
From some local testing, this seems specific to nesting claims under the `address` node - other claims with different named nodes have worked for me (such as `notaddress`, `test`, `nested1`) when they were nested with no issue here. 

I was able to reproduce with the latest code base.

It appears to have something to do with the [AddressClaimSet](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/AddressClaimSet.java) when deserializing the token and it not being happy about fields there that aren't explicitly specified..

**Comment by armfergom** [comment]
Glad to know it wasn't just me. I wonder if I should basically not map a nested `address` note manually, being a special field of sorts.

**Comment by sschu** [comment]
`Address` is a claim specified by OIDC spec, see: https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim So I assume this is not a bug.

**Comment by jsorah** [comment]
This snippet from the spec really solidifies that `address` claims is not meant for extension, at least from whats used in the ID token and the UserInfo response.

>End-User's preferred postal address. The value of the address member is a JSON [[RFC4627]](https://openid.net/specs/openid-connect-core-1_0.html#RFC4627) structure containing some or all of the members defined in [Section 5.1.1](https://openid.net/specs/openid-connect-core-1_0.html#AddressClaim).

Access Tokens however leave some ambiguity, but if we just look at the [JWT claims registry](https://www.iana.org/assignments/jwt/jwt.xhtml) it seems like `address` should still follow the same definition from the OpenID Connect Core specification.

So that being the case, Keycloak doesn't stop someone from creating these mappers that override the standard claim definitions, and this behavior is only discovered after that point in a vague manner. I wonder if Keycloak itself should have more protection around these standard claim definitions so folks don't end up in this situation? I think `address` is unique because it is the only claim with its specification being a JSON object?

**Comment by sschu** [comment]
Fair point. However, I assume there are people actually taking advantages of Keycloak's customisation ability to not follow standards to integrate with other systems not following the standard. So just preventing these kinds of modifications would probably not be a good idea. Maybe users could at least be warned?

**Comment by mposolda** [comment]
@jsorah @sschu Not 100% sure what is the best way to handle this... I can see the advantages of allowing "custom" things to be added to `address`. At the same time, someone can then use `address` in non-standard way by accident...

Maybe the ideal is to allow customizations, but at the same time, throw some warning in case that non-standard claims are found under address? Ideal is that this warning is logged just once per VM? However I don't know if it is possible to log it as warning and even more challenging to log it just once...

Implementation hints: There is for example `@Once` annotation used by jboss-logging - used for example in the `ServicesLogger` Keycloak class. However I think that `ServicesLogger` itself cannot be easily used as the JWTToken/IDToken/AccessToken classes are in the `core` when the `ServicesLogger` is in the `services`...). So maybe the warning can be added as a "best-effort" if possible to implement (which I am not 100% sure) ?

**Comment by sschu** [comment]
I am wondering if a better place to show this warning would be in the UI, as people configuring mappers are different from the ones looking at the logs. In our scenario, we would have to inform our customers that they made a potential mistake if the warning was just in the logs. We could also have warnings in both places.

To only have one warning in the log, it could be shown when the mapper is configured, not when it is actually used.
