### ISSUE TITLE
NPE when updating a subflow in an authentication flow

### ISSUE THREAD

**Issue by CorneliaLahnsteiner** [keycloak/keycloak#19844]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

It is not possible to update an subflow in the authentication flow when the description field is null in the database (NPE): 

`2023-04-20T11:33:13.601+0000 ERROR - org.keycloak.services.error.KeycloakErrorHandler : Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.keycloak.models.AuthenticationFlowModel.getDescription()" is null
	at org.keycloak.services.resources.admin.AuthenticationManagementResource.updateExecutions(AuthenticationManagementResource.java:675)`

### Version

21.0.2

### Expected behavior

Updating the name or description of a subflow, where the description is null in the database, does not lead to an NPE.

### Actual behavior

Update the name or description of a subflow, where the description is null in the database, does lead to an NPE and thus the subflow i not longer editable.

### How to Reproduce?

**Prerequests**: Create a subflow in an authentication flow and set the description of the subflow in the database to null.
Then follow the steps below: 

1. Log in to the admin UI and select an authentication flow
2. Edit the name or the description of the subflow
3. An error occurs instead of updating the subflow

**Comment by ssilvert** [comment]
I could not reproduce this.  @CorneliaLahnsteiner any hints?

I used the old admin console to create a flow with no description.
Then went to new console and did Action -> Edit Info
Changed description and hit `Edit` button.

**Comment by edewit** [comment]
When and with which version of keycloak where these old subflows created?

**Comment by CorneliaLahnsteiner** [comment]
@edewit @ssilvert sorry for the misinformation about the old keycloak versions. I will correct this in the description. 

We deploy our authentication flows with an Ansible module where we do not specify a description for subflows as they are optional. If no description is specified, it is stored as "null" in the database. When trying to edit the subflow in the admin console, an NPE is triggered. Is there a way to fix this problem or do we have to set an empty description when we deploy our authentication flows? Thanks in advance.

**Comment by ssilvert** [comment]
Setting an empty description will probably work around the problem.  

Since this is not a UI bug, but an NPE on the server side, I'm going to move this to the core team for now.

**Comment by pedro-hos** [comment]
I can reproduce this on 21.1.1. I am trying to fix that issue, should to sent the PR sooner

**Comment by pedro-hos** [comment]
Hi @ssilvert and @edewit can you assing someone from core team to review the PR https://github.com/keycloak/keycloak/pull/20014. Thanksss

**Comment by ssilvert** [comment]
@pedro-hos I requested review from the core team.

**Comment by pedro-hos** [comment]
Thank you @ssilvert :-D
