### ISSUE TITLE
Admin UI does not respect default values for custom authenticator configurations

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#19852]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have a [custom extension](https://github.com/sventorben/keycloak-home-idp-discovery) that implements an authenticator. The authenticator is configurable and defines default values for config options. As it can be seen in the screenshot, the default values are correctly send from the backend to the frontend. However, the frontend seems to ignore them and does not show the default values in the configuratoin dialog.

![image](https://user-images.githubusercontent.com/12183470/233485623-e54f9b41-9a46-417e-bd88-de01697b53f4.png)

### Version

20.0.5, 21.1.0

### Expected behavior

New configuration uses default values for all config options.

### Actual behavior

Default values are not used.

### How to Reproduce?

- Checkout the extension at https://github.com/sventorben/keycloak-home-idp-discovery
- build it with `mvn clean install`
- start a docker container with docker-compose: ``docker-compose up`
- navigate to https://localhost:8080 and login to Keycloak with user admin and password admin
- open the realm named `test-realm`
- open the flow named `home-idp-discovery-flow`
- click the gear icon for the `Home IdP Discovery` authenticator

**Comment by sventorben** [comment]
How is that a problem? It's the purpose of a default value, isn't it?
Or have I misunderstood you?

**Comment by edewit** [comment]
because in keycloak booleans have 3 values `undefined`, `false` and `true`. `undefined` should be false. But `undefined` can be 2 things it's either `undefined` because we have a new "item" or it's `undefined` on a existing item. When it' s new we want the default value, but when it's existing we want it to be `false`. On the level of the field we don't know the difference between a new or an existing item, so the saver option is to ignore the default

**Comment by sventorben** [comment]
> `undefined` should be false. 

No. If the value is undefined, the default value should be used. That is what will be done at runtime anyways. That's the whole purpose of default values: if you do not have a value, use the default.

> but when it's existing we want it to be `false`.

Why would you want this to be `false`? In case of an authenticator config as in my example that would imply that the default value used at runtime would be always `false`. But that's not the case. The default is used which may be `true`.

Let's say I have added a new field to an extension config. And let's say the item for the extension config is present, but does not have a value set for the new field (undefined). Let's further assume the extension uses `true` as a default. If you open that config via the UI to change a different config option, you may change the (implicitly used default) value from `true` to `false`. I do not see any benefit in that behavior.

**Comment by edewit** [comment]
> > `undefined` should be false.
> 
> No. If the value is undefined, the default value should be used. That is what will be done at runtime anyways. That's the whole purpose of default values: if you do not have a value, use the default.

In this case maybe, but these components are not only used here, this is the issue https://github.com/keycloak/keycloak/issues/17927 where you see that `undefined` must be either use default or false depending on the state of the item. If it's an existing item that doesn't have an attribute it should be false, but if it's a new item then it should use the default value.

> Let's say I have added a new field to an extension config. And let's say the item for the extension config is present, but does not have a value set for the new field (undefined). Let's further assume the extension uses true as a default. If you open that config via the UI to change a different config option, you may change the (implicitly used default) value from true to false. I do not see any benefit in that behavior.

That is the problem! In this case opening it would show you the field as set to 'true' because that is the default value, but it is not set, it's `undefined` so it is treated as `false`

**Comment by edewit** [comment]
Guess the right way to solve this would be to pass in an attribute to tell the field that it's a new item that we are creating or if we are editing an existing item. And based on that either use the default value or 'false'

**Comment by sventorben** [comment]
What I am requesting here is different from #17927, because mappers (as in #17927) do not have customizable default values as authenticator configurations have. For an authenticator configuration, the default value is specified by the authenticator and should be respected accordingly (see my screenshot). Otherwise it would be meainingless to have this value. 
For this it is completely irrelevant whether the item existed before or is newly created. If a field has no value, the default must be used.

**Comment by edewit** [comment]
mappers have custom default values and they use the same component:
![image](https://user-images.githubusercontent.com/51133/236998476-652bfe69-e8e8-4ed7-b046-63d567f874d7.png)
it's not irrelevant, that's why I add this comment that we don't just add the default value blindly, because it will break it here

**Comment by edewit** [comment]
Have you tried my PR? It will fix your issue, it's not a server side problem.

**Comment by sventorben** [comment]
I am sorry to say I didn't. But too me it looks like this is only fixing the issue for newly created configurations.

Let's disucss this with a concrete example:

I developed the [Home IdP Discovery](https://github.com/sventorben/keycloak-home-idp-discovery/) extensions. With one of the latest features I added a new configuration property named `Forward to first matched IdP`. For backwards compatibility I had to interpret an undefined value as `true` during runtime. So, I also set the default value for this property to `true` to reflect this.
Now when you update an old version of the extension with the new one, the behaviour stays the same and users do not have to update the configuratoin. But when a users opens the configuration dialog, the property is shown as switched off (`false`). The problem is, that this does not reflect the current behaviour at runtime. This confuses users - take [this comment](https://github.com/sventorben/keycloak-home-idp-discovery/issues/171#issuecomment-1515781968) as an example.

That is because the default value is not considered in this case. It's also a useability issue, because user may unintentionally change the configuration, e.g. when they change another property value and save the configuration. The undefined value that was implicitly interpreted as `true` now becomes `false`.

This leads me to the conclusion, that the UI should always use the default value and the backend should be changed to send the correct default values.

Please do not get me wrong. I appreciate your PR and the fix, but I think it's just one part of the issue.
Maybe we simply disagree in this point, which is fine for me.

**Comment by edewit** [comment]
I think it's strange that I fix your issue, you don't try the fix but keep saying that the fix is wrong. Until you have verified that my fix indeed doesn't fix your issue there is no point in restating the same point.

**Comment by cnwaldron** [comment]
@edewit , I'd like to try your PR but I don't have my system setup for building Keycloak. Is it possible to get a docker image with your changes that I can just spin up?

**Comment by cnwaldron** [comment]
@edewit , I've tested on the nightly build and it appears default Map values are ignored.
