### ISSUE TITLE
Can't able to authenticate the user in our backend

### ISSUE THREAD

**Issue by rv-ragul** [keycloak/keycloak#19855]
### Before reporting an issue

- [x] I have reproduced the issue with the latest release
- [X] I have searched existing issues

### Area

authentication

### Describe the bug

We have our **_FastAPI(python)_** as backend server and using keycloak for authentication. Our frontend is **_VueJs_** application and **_python-keycloak_** python package in our FastAPI application. We have hosted the backend and keycloak in the same server. 
They are running in separate ports in the same server. When the user login the VueJs application, accessToken is successfully fetched from keycloak server. Then I sent the accessToken to my backend server. Now I want to introspect the token sent from  the client side. Our FastAPI application sends the introspect request to the keycloak server through the local network not through DNS. The introspect operation results in  **_Unauthorized_**.  I have searched about these issues in [stackoverflow](https://stackoverflow.com/a/53721874/16407852) forums related to this issue. But our server cant make a request to keycloak server through DNS server in the roundtrip manner.

### Version

21.1.0 (latest)

### Expected behavior

We want to introspect the token by making the request to the keycloak server through the local network not through DNS server. This also reduces the roundtrip time and solves this issue.

### Actual behavior

When I run both VueJs, FastAPI and keycloak in our server, request from users comes through DNS server and introspect request reaches the keycloak server through the local network. So the introspect operation results in {"active":"false"}.

### How to Reproduce?

Host the keycloak and backend application in the same server. Login using the keycloak-js login() method. Send the accessToken to your backend python application. Introspect the token in the backend application through the local network.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team doesn't have time to look at this in the near future. Anyone is welcome to send the PR with fixing it. See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

Also it is possible that this is not a valid issue, but just configuration mismatch. Here are some tips on how to configure Keycloak hostname https://www.keycloak.org/server/hostname
