### ISSUE TITLE
Keycloak Quarkus Server dependency broken

### ISSUE THREAD

**Issue by SamTV12345** [keycloak/keycloak#19850]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dependencies

### Describe the bug

The keycloak quarkus server dependency has keycloak account ui/keycloak admin ui as a dependency of it. Because these two don't exist in the latest version 21.0.0 I get errors resolving keycloak. This also bricks the [keycloak custom server](https://github.com/SamTV12345/keycloak-custom-server) installation which is based on [this](https://github.com/thomasdarimont/keycloak-custom-server) example on how to run keycloak in an alpine container. 

### Version

21.1.0

### Expected behavior

Keycloak account ui/admin ui can be resolved from Maven

### Actual behavior

Keycloak account ui/admin ui are not resolvable as they are not present in the version 21.1.0

### How to Reproduce?

Check out the project and main. Try resolving dependencies

### Anything else?

I would love to have these two dependencies still available so I don't have to build them from scratch. They were present up until Keycloak migrated to monorepo

**Comment by SamTV12345** [comment]
Will the missing dependencies be available soon on maven central? Repo1 doesn't list them yet https://repo1.maven.org/maven2/org/keycloak/keycloak-admin-ui/

**Comment by ahus1** [comment]
@SamTV12345 - the dependencies will be available only after KC 21.1.1 has been released.

There are several upcoming changes for KC 22, including the upgrade to Jakarta EE eventually (not available in main yet). To test those and to provide feedback, consider adding a daily or weekly build of your project against the nightly release. Those are available as version `999.0.0-SNAPSHOT` from https://s01.oss.sonatype.org/content/repositories/snapshots/

**Comment by SamTV12345** [comment]
I can’t find the keycloak admin ui on mvnrepository. According to your explanation it should be uploaded as 21.1.1 is released. Other than that good idea I am happy to test the upcoming keycloak major version

**Comment by SamTV12345** [comment]
I added a local profile. So if someone wants to test the latest build just do a `mvn package -P testing' and the docker image is built.
