### ISSUE TITLE
Enabling Dynamic Scope missing in UI

### ISSUE THREAD

**Issue by powermax** [keycloak/keycloak#19865]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

After enabling dynamic scope feature possibility activating dynamic scope is missing in the UI. In previous version (before redesign) this options was under: client scopes -> create -> Dynamic Scope ON/OFF.

### Version

21.1.0

### Expected behavior

After enabling dynamic scope feature the option should be available in the UI.

### Actual behavior

After enabling dynamic scope feature the option is missing in the UI.

### How to Reproduce?

Enable dynamic scope feature and try to activate this feature in the UI.

**Comment by ssilvert** [comment]
I have reproduced this.

Note to developer fixing this bug:  You need to enable the experimental feature, `dynamic-scopes`.
https://www.keycloak.org/server/features
