### ISSUE TITLE
Usability issues with composite role management

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#19873]
### Description

The Admin Console (version 21.1) provides the following view for a newly created client role:
![image](https://user-images.githubusercontent.com/789496/233618635-0158dcfd-72ac-484c-a280-cd0fa76f3d2d.png)

## Adding associated roles hard to find

Issue: Adding associated roles is hidden at the action menu. It would be better to have the "Associated Roles" tab always present (also when no role was added). Should look like is when you add and remove an associated role (except the "Composite" flag):
![image](https://user-images.githubusercontent.com/789496/233613038-44427174-5f08-49f9-ad86-9e24ec664220.png)

Issue: The text from realm roles is reused here, but the context is a client role.

## Searching for client roles a bit cumbersome

When clicking "Assign role", realm roles are always pre-selected.
![image](https://user-images.githubusercontent.com/789496/233615870-cb16e5e1-753d-4b60-8665-6d073c85415c.png)

Issue: Before you can search for a client role you need to switch to "Filter by client roles". It would be more convenient to search at client and realm roles at same time, without enforcing a selection by type.

## Removing all roles at unexpected place
Once one or more roles are assigned, all of the can be removed within the action button.
![image](https://user-images.githubusercontent.com/789496/233613974-cb795ec0-e9dc-4a45-9921-c493d6897a2b.png)

Issue: Removing all associated roles shouldn't be a top level action. It is expected at level of the tab "Associated Roles"

## Selecting all roles adds the roles from this page plus one
When all roles of a page are selected, this number plus one is assigned. 
How to reproduce: Search for "master-realm" client roles and then select all (with default page size 10)
![image](https://user-images.githubusercontent.com/789496/233621352-649e40ba-270a-49ed-a652-2e33bf153188.png)
After assignment 11 roles are assigned:
![image](https://user-images.githubusercontent.com/789496/233621909-eb0c0d72-d311-46af-aa9e-6f97e47637c5.png)

Expected: All roles are assigned (independently of page size) or just the ten visible roles are assigned. 

## Selecting a role and then searching again keeps it selected
When selecting one role and then narrowing down the search, the first selected role is still selected even if not visible any more. It will be assigned to to together with the selected roles which are visible.

Issue: this could be unexpected, as the selection state isn't visible any more.

### Motivation

Make it easier to understand and use Keycloak role configuration.

**Comment by jonkoops** [comment]
@xianli123 as our resident UX expert what is your take on this?

**Comment by xianli123** [comment]
Hi @jonkoops, thanks for involving me. Initially, we didn't want users to abuse this feature. So after discussion, we decided to put this feature in the upper right corner. Does separating the "Associated Roles" as an always-present tab make sense? @stianst

**Comment by xianli123** [comment]
@jonkoops @jbman  As for the issue:

> Searching for client roles a bit cumbersome
When clicking "Assign role", realm roles are always pre-selected.
![image](https://user-images.githubusercontent.com/53931519/233940597-c0149f55-e2c4-443c-a6a0-5d4422b65d9b.png)
> Issue: Before you can search for a client role you need to switch to "Filter by client roles". It would be more convenient to search at client and realm roles at same time, without enforcing a selection by type.

We have tried to update the search function. However, it slows down loading when all available roles are displayed at the same time. I am not sure if the dev team could help solve this problem. What do you think? @jonkoops

**Comment by xianli123** [comment]
@jbman Thanks! If the "Composite role" tab would always be displayed, we can put the "Remove" action in the composite roles table.

> Removing all roles at unexpected place
> Once one or more roles are assigned, all of the can be removed within the action button.
> Issue: Removing all associated roles shouldn't be a top level action. It is expected at level of the tab "Associated Roles"

**Comment by xianli123** [comment]
According to the design and decision, only the visible roles on the current page will be selected.

> Selecting all roles adds the roles from this page plus one
> When all roles of a page are selected, this number plus one is assigned.
> How to reproduce: Search for "master-realm" client roles and then select all (with default page size 10)
> image
> After assignment 11 roles are assigned:
> Expected: All roles are assigned (independently of page size) or just the ten visible roles are assigned.

**Comment by xianli123** [comment]
Hi @jbman , does this mean that there should be a way to display all the selected roles? Thanks!

> Selecting a role and then searching again keeps it selected
> When selecting one role and then narrowing down the search, the first selected role is still selected even if not visible any more. It will be assigned to to together with the selected roles which are visible.

Issue: this could be unexpected, as the selection state isn't visible any more.

**Comment by jbman** [comment]
> Hi @jbman , does this mean that there should be a way to display all the selected roles? Thanks!

Hi @xianli123 no, I think it's not necessary to display all selected roles. 
in my opinion this could be the behavior expected by users:

- When the checkbox is clicked to mark all roles, all which matches the search are selected (also the ones which are on next pages and not visible)
-  If search input is changed and search executed, all selected roles are cleared (No roles are selected internally any more)

**Comment by xianli123** [comment]
@jbman Thanks for the details. I will consider how to reach the goal. 
As for the composite roles tab, I agree that always display it. What do you think? @stianst

**Comment by ssilvert** [comment]
@xianli123 Can we move forward with an improved design if @stianst doesn't have time to respond?

**Comment by xianli123** [comment]
Hi @ssilvert I have been working on the design and will finish it as soon as possible. Thanks 👍

**Comment by ssilvert** [comment]
@xianli123 Thanks. Just let us know when you are done and we will assign to someone for coding.

**Comment by xianli123** [comment]
Hi @jbman @jonkoops @ssilvert I updated the design of the composite role. Here is the design link https://www.figma.com/proto/YkPV0knnrWo7crrGrWGfNc/CompositeRoles?page-id=0%3A1&type=design&node-id=7-170&viewport=790%2C512%2C0.17&scaling=scale-down&starting-point-node-id=7%3A170. If you have any questions or comments, please leave your comments on the wireframe.

There are some explanation below, please take a look.

> **Adding associated roles hard to find.**

In the new design, the "Associate role" tab will always be displayed. If there is no role, there will be an empty state. 
<img width="1706" alt="Frame 1" src="https://github.com/keycloak/keycloak/assets/53931519/8c7d51de-b93c-421a-9ac2-79f0ff303404">

> **Searching for client roles a bit cumbersome**

In the modal, all available roles will be displayed by default. 
<img width="750" alt="Screenshot 2023-05-11 at 15 54 59" src="https://github.com/keycloak/keycloak/assets/53931519/e6be2568-d355-40ec-8643-321bcb611f00">

> **Removing all roles at unexpected place**

Users can select all roles in the table, and click the "Unassign" button in the toolbar.
<img width="687" alt="Screenshot 2023-05-11 at 15 57 32" src="https://github.com/keycloak/keycloak/assets/53931519/9f427dfb-6e04-4179-bb98-c76e147f61c7">

> **Selecting all roles adds the roles from this page plus one**

The component has been updated. Please refer to the PF4 component. Here is the link: https://www.patternfly.org/v4/demos/filters/#checkbox-select. In addition, there is a demo for your reference: https://www.patternfly.org/v4/components/table/react-demos/bulk-select/.

> **Selecting a role and then searching again keeps it selected**

When selecting one role and then narrowing down the search, the first selected role can be canceled. What do you think? @jbman

**Comment by jbman** [comment]
Thank you @xianli123, the design is a big improvement. I like that any role can be searched by default.This will need two requests at the API, but I think that's acceptable.

I'll add further comments in the design.

> When selecting one role and then narrowing down the search, the first selected role can be canceled. What do you think? 
Whenever the filter changes (Select none / all or realm roles client role type or search string) all selected roles should be cleared. 
This way no roles get assigned unexpectedly.

**Comment by xianli123** [comment]
Hi @jbman, Thanks for your suggestions. That would make sense to me. 

> Whenever the filter changes (Select none / all or realm roles client role type or search string) all selected roles should be cleared.
This way no roles get assigned unexpectedly.

**Comment by xianli123** [comment]
@jonkoops Could we start fixing this issue? What do you think?

**Comment by jonkoops** [comment]
Yes, we certainly can. It should be prioritized so we know when to pick it up.

**Comment by xianli123** [comment]
@jonkoops Thanks!

**Comment by agagancarczyk** [comment]
@ssilvert Could you please help me understand if there is anything we need to implement here? I see that the 'Associated roles' tab and related functionality are already implemented. If there is nothing else to do, I suppose we can close this issue. Thanks!

![Screenshot 2024-06-28 at 16 31 41](https://github.com/keycloak/keycloak/assets/4890675/ebe7cdec-7940-4e87-bb65-2bd458782d61)

**Comment by ssilvert** [comment]
@agagancarczyk The `Associated roles` tab is still not displayed until you add some associated roles via the `Action` dropdown.  This makes the functionality awkward and hidden.  That is the main complaint here so we should probably limit the scope to that.

So I propose that the enhancement should consist of:
1. `Associated roles` tab should be always displayed.
2. Get rid of `Add associated roles` option in `Action` dropdown.
3. Get rid of `Remove all associated roles` option in `Action` dropdown.

I believe the other issues mentioned are with the role selection dialog.  It is used in several contexts.  So improvements to that should be proposed and discussed separately.

**Comment by agagancarczyk** [comment]
> @agagancarczyk The `Associated roles` tab is still not displayed until you add some associated roles via the `Action` dropdown. This makes the functionality awkward and hidden. That is the main complaint here so we should probably limit the scope to that.
> 
> So I propose that the enhancement should consist of:
> 
> 1. `Associated roles` tab should be always displayed.
> 2. Get rid of `Add associated roles` option in `Action` dropdown.
> 3. Get rid of `Remove all associated roles` option in `Action` dropdown.
> 
> I believe the other issues mentioned are with the role selection dialog. It is used in several contexts. So improvements to that should be proposed and discussed separately.

Thank you @ssilvert for reviewing this. Your suggestions make sense, I'll add them in. Thanks again!

**Comment by jbman** [comment]
Great, that the associated roles can be more easily found in the admin console, now!

The design by @xianli123 also included an improvement which makes it easier to find roles. 
https://www.figma.com/proto/YkPV0knnrWo7crrGrWGfNc/Keycloak-Issues?page-id=0%3A1&type=design&node-id=1-18&viewport=790%2C512%2C0.17&scaling=scale-down&starting-point-node-id=7%3A170

Admins start to search for roles here, but don't find any client roles as it is hidden in the drop down
![image](https://github.com/keycloak/keycloak/assets/789496/40ff5ac5-c54b-4146-b6f7-25d338bc7414)

As this is rather an issue with general role selection (not only in context of associated roles) I can start a new discussion for this.
