### ISSUE TITLE
Incorrect function is used in 'keycloak-admin-client' library in getToken function

### ISSUE THREAD

**Issue by lexakozakov** [keycloak/keycloak#19879]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

It looks like it's just a simple mistake - 'atob' function is used instead of 'btoa'

### Version

2022.9

### Expected behavior

'btoa' function should be used

### Actual behavior

'atob' function is used

### How to Reproduce?

just run getToken function

**Comment by hmica** [comment]
Hi, I got the same issue while upgrading to admin@21.1.1

it's seems there is an error in auth.ts 

https://github.com/keycloak/keycloak/blob/f7988a6ae335836df910f0b5fbb6f1d4b3b80fee/js/libs/keycloak-admin-client/src/utils/auth.ts#L80-L83

The correct header should be something like this : 
```ts
 headers.set("Authorization","Basic "+btoa(credentials.clientId + ":" + credentials.clientSecret));
 ```

Thank you

**Comment by lexakozakov** [comment]
BTW, authorization does not work properly even the function is changed to btoa. 

clientId and clientSecret should be sent in request body.  


https://github.com/lexakozakov/keycloak/blob/main/js/libs/keycloak-admin-client/src/utils/auth.ts#L66

**Comment by jonkoops** [comment]
Hi @hmica, would you be willing to submit a pull request to fix this? We'll try to backport it to a patch release.

**Comment by jonkoops** [comment]
I see you already did, will take a look at it :+1:

**Comment by guesant** [comment]
Same issue here.

`DOMException [InvalidCharacterError]: Invalid character`
