### ISSUE TITLE
Allow configuration cookies with `SameSite=Strict` for better compliance with strict regulations and standards

### ISSUE THREAD

**Issue by Wimmerke** [keycloak/keycloak#19886]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authorization-services

### Describe the bug

Cookie SameSite configuration missing in the interface

The default setting is also unsecure

The concerned identified cookies are:
- AUTH_SESSION_ID_LEGACY
- AUTH_SESSION_ID
- KC_RESTART

This must be configurable, and defautl to Strict

### Version

21.0.2

### Expected behavior

All cookieflags configurable
Default configuration the secure setting
for SameSite this should be Strict

### Actual behavior

KC_RESTART missing SameSite setting
AUTH_SESSION_ID SameSite=none
AUTH_SESSION_ID_LEGACY missing SameSite setting

### How to Reproduce?

Check in browser the cookie settings with the developer tools
or scan the site with https://www.immuniweb.com/ or other testing tools for the cookie configuration

### Anything else?

Yes as this is a security service which is core for the cyber resilience and the compliance of an organization and its used services, these settings must be up to the industry standards.

**Comment by jonkoops** [comment]
At least for the `_LEGACY` cookies this is intentional, these cookies will be removed in the future (see #16770).

**Comment by Wimmerke** [comment]
Good to see legacy is being removed

But the current cookies must have the secure configuration for all 3 cookie flags

For the SameSite in scope of this report all cookies must support SmaeSite=Strict, and preferably have this as default
If default not possible, it must be configurable

**Comment by jonkoops** [comment]
Agreed, these should have the strictest defaults possible with the user needing to explicitly opt-in to less secure behaviour.

**Comment by Wimmerke** [comment]
Indeen Jon

I'm security officer, so not a coder. But on the level of compliance and resilience these security and privacy by default configurations are essential for market adoption.

**Comment by mposolda** [comment]
Adding to Keycloak 22 for now. We will see if we can handle this or if we need to postpone due the lack of time...

**Comment by jonkoops** [comment]
@mposolda if we could get someone on #16747 I think we could make some progress on this.

**Comment by mposolda** [comment]
Removing from 22 for now.

According to @pedroigor : It should be done carefully and with some baking time. Doing it now might seriously break customers migrating to Keycloak 22

**Comment by alaa-ahmad** [comment]
Dear Mposolda ..if the Missing SameSite attribute issues for below cookies will solved on release 23 and what the expected date for publishing this release, and if you have workaround to solve issues:
AUTH_SESSION_ID
AUTH_SESSION_ID_LEGACY
KC_RESTART



</body>

</html>

**Comment by as950118** [comment]
Hi. It seems that the issue still remains in several cookies (AUTH_SESION_ID, etc.) provided by keycloak, is there a fix measure?

**Comment by pedroigor** [comment]
@Wimmerke I'm not sure if we can't force `Strict` by default because most of the time you are deploying the server in a separate domain from your apps and you need to enable cross-site requests.

By setting the cookie as `SameSite=none; secure` is also a valid approach to securely set cookies while not breaking production deployments.

As for the legacy cookies, we did not yet complete the task to remove them completely. However, perhaps we should enable at least a flag to enable/disable them.

**Comment by Wimmerke** [comment]
Hello

This should be configurable. This will the enable security and not having
the setting just configured. Talking as a security expert and CISO and
business owner.

Default to none is fine but it should be configurable in a strict mode.

This is in line with industry good (none) and best (strict) practices.

Greetings
Wim

Op di 19 dec 2023 om 14:00 schreef Pedro Igor ***@***.***>

**Comment by pedroigor** [comment]
@Wimmerke Thanks. I see that being opinionated and not allowing configuring those policies might be a problem for some people.

We have discussed in the past certain approaches to this problem. See https://github.com/keycloak/keycloak/pull/16747.

I'm changing the title of the issue to make it more explicit that we want some level of configuration about how cookie policies are set. Another one would be removing the legacy cookies. 

Does it work for you?

**Comment by Wimmerke** [comment]
Hello,

Indeed good initiative!

Legacy if not necessary should always be removed.
Not needing to maintain and support, reducing the attack surface.

Cookies should always be configurable if not essential.
Flags always configurable with security by default in mind, certainly for
idp services which are backbone core critical services.

Greetings
Wim

Op di 19 dec 2023 om 15:18 schreef Pedro Igor ***@***.***>

**Comment by 6550554** [comment]
Hi,
any ideas when this will be fixed? planned date?

**Comment by jonkoops** [comment]
We don't have an estimate for this, and we do not give out 'planned dates' for anything in development.

**Comment by Wimmerke** [comment]
Hello

I hope the compliance issue is clear, as well as the resilience risk.

In all transparency , we will need to document it in our report to the
regulatory body. We stated a couple of times work in progress, but cannot
postpone anymore the finding.

Fyi regulatory bodies in scope are ECB and EDPB.

Greetings
Wim

Op ma 22 jan 2024 om 17:08 schreef Jon Koops ***@***.***>

**Comment by stianst** [comment]
Setting `SameSite=Strict` on the sso cookies (KEYCLOAK_IDENTITY, etc) would effectively break any application that is not hosted on the same eTLD+1 as Keycloak. Reason for this is that browser do not send cookies with `SameSite=strict` after a redirect to Keycloak if the original site is on a different eTLD+1.

It may work in some use-cases where all applications are hosted on the same eTLD+1 (for example https://myapp.mycompany.org and https://keycloak.mycompany.org). Both OIDC and SAML have protection against CSRF though, so this really shouldn't be necessary in the first place.

**Comment by Wimmerke** [comment]
Hello

This should be configurable

Greetings
Wim

Op di 23 jan 2024 om 12:14 schreef Stian Thorgersen <
***@***.***>

**Comment by jonkoops** [comment]
You can always put a proxy in front of Keycloak and change all the cookie properties if you really need to. But like @stianst said that will break stuff so do it at your own risk. We're working on new defaults for cookies, which may or may not include `SameSite=Strict`, but they will likely not be set for cookies that are require cross-domain access such as the session.

**Comment by Wimmerke** [comment]
Indeed people could.

But if KeyCloak puts cookies not configurable (and in the default unsecure
state), it should be at least made configurable.

Putting compensating measures in line does impact operational excellence
and distupts the seperation of concerns etc.

A lot of people don’t have a clue about the risks here, this is why it is
key to have the settings out of the box in the secure way, and if needed
let the user downgrade the setting.

If you want we can setup a call for this.

Greetings
Wim

Op di 23 jan 2024 om 13:30 schreef Jon Koops ***@***.***>

**Comment by stianst** [comment]
We will definitively will not set cookies intended for cross-site requests to `SameSite=strict` by default, and I do not really see the point in making it configurable either, as I mentioned above that will break a lot of deployments if you do that. I would bet that if you did it to your deployment it would end up breaking integrations with applications on your end.

`SameSite=strict` main purpose is to prevent CSRF attacks, but as I mentioned before the way this cookie is utilised by Keycloak there are other mechanism in place built-into the OIDC and SAML protocols that are how applications interact with Keycloak.

**Comment by jonkoops** [comment]
> But if KeyCloak puts cookies not configurable (and in the default unsecure state), it should be at least made configurable.

Note this is not in any way a security issue, this is working as intended. We will not make things configurable that will break the user experience. People will run Keycloak trough fundamentally broken security scanners, draw a conclusion that this is 'insecure', then set this option and log issues in Keycloak when it all breaks, creating additional overhead for us, and confusion for users.

> Putting compensating measures in line does impact operational excellence and distupts the seperation of concerns etc.

Sorry, but I have no idea what you are trying to say here.

> A lot of people don’t have a clue about the risks here, this is why it is key to have the settings out of the box in the secure way, and if needed let the user downgrade the setting.

Please provide us with a detailed motivation as to what the risk is here that we don't already know about. These cookies are supposed to operate in a cross-domain setting, they are in fact required to be exposed in a manner that they can be accessed, as this is fundamental to the operation of Keycloak.

**Comment by stianst** [comment]
If anyone is aware of any actual attack surface around cookies used by Keycloak, please send an email to [keycloak-security@googlegroups.com](mailto:keycloak-security@googlegroups.com) and not disclose it here or anywhere else that is public.

**Comment by stianst** [comment]
Closing this as we don't have any valid reason for making SameSite configurable.

**Comment by Wimmerke** [comment]
When the cookie flags are set to `SameSite=None` in Keycloak services, there are several potential security risks, despite the use of CSRF (Cross-Site Request Forgery) tokens. Here's an overview of these risks:

1. - Cross-Site Request Forgery (CSRF): CSRF tokens are designed to prevent CSRF attacks, where an attacker tricks a user into submitting a request to a web application they are authenticated against. While CSRF tokens provide a level of protection, they are not a complete safeguard, especially when `SameSite=None` is used, as this setting allows cookies to be sent in requests initiated by third-party websites.
2. - Cross-Site Scripting (XSS) Attacks: If an attacker can execute a successful XSS attack, they could potentially bypass CSRF protections. Since `SameSite=None` cookies are sent with requests initiated from any site, an XSS attack could leverage these cookies to perform actions on behalf of the user.
3. - Cookie Tossing: This is a type of attack where an attacker sets a cookie from a different domain that the browser sends to the target domain. With `SameSite=None`, these cookies will be sent in cross-site requests, potentially leading to security issues.
4. - Session Hijacking: If the cookies are not set as `Secure` along with `SameSite=None`, the cookies could be transmitted over non-HTTPS connections, increasing the risk of session hijacking where an attacker could intercept these cookies.
5. - Reliance on Browser Implementation: The effectiveness of `SameSite` flags can depend on the user's browser and its implementation of the `SameSite` specification. Some older browsers might not correctly handle `SameSite=None`, leading to inconsistent security behaviors.
6.  -Third-Party Integrations: In environments where Keycloak interacts with third-party applications, `SameSite=None` can make it challenging to enforce strict cross-origin policies, potentially opening up more avenues for attack.

The product team's position that CSRF tokens mitigate the risk sufficiently is valid to a certain extent, as CSRF tokens are an essential part of defending against CSRF attacks. However, they should not be the sole line of defense, especially in scenarios where `SameSite=None` is used. Additional security measures, such as strict content security policies, secure cookie handling (including the use of `HttpOnly` and `Secure` flags), regular security audits, and ensuring up-to-date browser support, are important to mitigate these risks effectively.

**Default Setting: SameSite=Lax**
Reasoning:
Lax allows cookies to be sent in top-level navigations which are GET requests. It offers a balanced approach between security and user experience.
It prevents cookies from being sent in requests initiated by third-party websites, which reduces the risk of CSRF attacks.
This setting is generally compatible with most modern browsers and use cases, making it a practical default.
Options:
- SameSite=None: Only use this if your service needs to support cross-origin usage scenarios, such as embedding in third-party sites. Ensure that cookies are also set as Secure.
- SameSite=Strict: This is the most secure setting, where cookies are only sent in requests originating from the same site. This can hinder some cross-origin functionalities.

Implementing Configurability:
- Provide an option in your Keycloak configuration (perhaps in the admin console or a configuration file) to set the SameSite attribute.
- Document the implications of each setting so administrators can make informed decisions based on their security requirements and the nature of the cross-origin interactions.

Hope this information does provide some insights and motivates our request to enable this cookie to be configurable with a good general usable default setting.

**Comment by jonkoops** [comment]
> SameSite=None: Only use this if your service needs to support cross-origin usage scenarios, such as embedding in third-party sites. Ensure that cookies are also set as Secure.

Yeah, that is what we're doing right now. Keycloak needs to be able to run in cross-origin scenarios, including being embedded in third-party sites to enable Silent Authentication and Session Management as part of OAuth. Not sure where all this advise is coming from, looks like it is copy-pasted from ChatGTP.

**Comment by jonkoops** [comment]
Locking this discussion as I don't feel like we need to waste more time on this. Feel free to submit an issue if there is an actual realistic attack vector or other motivation.
