### ISSUE TITLE
Saving client admin-cli in master realm gives a javascript error

### ISSUE THREAD

**Issue by leodip** [keycloak/keycloak#19883]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I start the latest Keycloak with docker:

`docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:latest start-dev`

Then I visit the admin portal and go to `Clients`. I select the `admin-cli` client, of the master realm. On the Settings tab, I scroll down and change `Client authentication` to "On", uncheck the box `Direct access grants`, and check the box `Service accounts roles`.

I finally click the `Save` button.

Nothing happens. 

When I press F12 to see the Dev tools console log, I can see an error:

```
Uncaught (in promise) TypeError: u is undefined
    validate LogoutPanel.tsx:139
    validateField index.esm.mjs:804
    wt index.esm.mjs:1609
LogoutPanel.tsx:139:22
```

### Version

21.1.0

### Expected behavior

To see a "Saved successfully" confirmation. Or an error message telling me why I couldn't save.

### Actual behavior

Nothing happens when I click Save, and an error is displayed on the javascript console log.

### How to Reproduce?

Steps to reproduce are in the description of the bug.

**Comment by ssilvert** [comment]
I have verified this bug in main, though I get a slightly different error:

```
Uncaught (in  LogoutPanel.tsx:139 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at validate (LogoutPanel.tsx:139:27)
    at validateField (validateField.ts:226:28)
```
