### ISSUE TITLE
File map storage: Environment variable expansion

### ISSUE THREAD

**Issue by dominikschlosser** [keycloak/keycloak#19890]
### Description

In order to make the file store more usable in cloud native configuration scenarios, i propose to add variable expansion.
This can be done with SnakeYaml directly: https://bitbucket.org/snakeyaml/snakeyaml/wiki/Variable%20substitution

### Motivation

File store adds a much needed configuration as code approach to Keycloak. In such a scenario, placeholders are needed to exclude sensitive data like keys from the configuration and add them back at runtime (for example via Kubernetes secrets).

An alternative would be to broaden the scope of [Keycloak Vault](https://www.keycloak.org/server/vault) to be usable in a lot more fields.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
