### ISSUE TITLE
Keycloak: Disable login after forgot password and show custom message

### ISSUE THREAD

**Issue by Aditya-oneadvanced** [keycloak/keycloak#19907]
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

Current behaviour:

Click on Forgot password link -> Enter username or email -> User receives an Email with reset link -> Click on the link -> Reset password, then submit -> User is logged in then The user is logged in.

What I want to acheive is the following

Click on Forgot password link -> Enter username or email -> User receives an Email with reset link -> Click on the link -> Reset password, then submit -> Display a message saying "Your password has been updated." and do not login the user. stay on that page.

### Version

17

### Expected behavior

Click on Forgot password link -> Enter username or email -> User receives an Email with reset link -> Click on the link -> Reset password, then submit -> Display a message saying "Your password has been updated." and do not login the user. stay on that page.

### Actual behavior

Click on Forgot password link -> Enter username or email -> User receives an Email with reset link -> Click on the link -> Reset password, then submit -> User is logged in then The user is logged in.

### How to Reproduce?

Click on Forgot password link -> Enter username or email -> User receives an Email with reset link -> Click on the link -> Reset password, then submit -> User is logged in then The user is logged in.

**Comment by vilmosnagy** [comment]
@Aditya-oneadvanced I don't think it's a bug, and you should be able to implement this with custom authentication flows. I'd start at [this](https://github.com/keycloak/keycloak/tree/main/services/src/main/java/org/keycloak/authentication/authenticators/resetcred) package and [this](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java) class.

**Comment by Aditya-oneadvanced** [comment]
> @Aditya-oneadvanced I don't think it's a bug, and you should be able to implement this with custom authentication flows. I'd start at [this](https://github.com/keycloak/keycloak/tree/main/services/src/main/java/org/keycloak/authentication/authenticators/resetcred) package and [this](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java) class.

Okay Thanks @vilmosnagy
