### ISSUE TITLE
CRL verification with multiple CRL files not working

### ISSUE THREAD

**Issue by baldmageix** [keycloak/keycloak#19918]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When using x509 Certificate Authentication with CRL validation is turned on, and multiple CRL Files are used, it seems like Keycloak is having issues validating against multiple CRL files.

### Version

21.1.0

### Expected behavior

When authenticating with a X509 Certificate, the certificate should be able to be validated against multiple CRL files. The current behavior is that there's a chance the users would be denied access when there's multiple CRL files. 

Authentication should be successful if the CRL file does not contain the matching CA of the client certificate. Since the CRL is essentially a list of denied user, if Keycloak cannot process the list due to mismatched CAs or malformed format of the file, there is no list of denied users to pull from, and the user should be able to authenticate successfully.

### Actual behavior

Users using X509 Certificate for browser flow login are denied login if there are multiple CRLS files and and Keycloak chooses to process the CRL file that does not match with their CA. Keycloak should process all the CRL files specified in the CRL files list. If there is no match, the user should still be able to authenticate.

The error is from Keycloak is:
```{"timestamp":"2023-04-24T15:10:38.251Z","sequence":8713,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.keycloak.services","level":"ERROR","message":"Truststore not available","threadName":"executor-thread-17","threadId":340,"mdc":{},"ndc":"","hostName":"ip-10-38-1-112.us-gov-west-1.compute.internal","processName":"QuarkusEntryPoint","processId":77,"exception":{"refId":1,"exceptionType":"java.security.GeneralSecurityException","message":"Truststore not available","frames":[{"class":"org.keycloak.utils.CRLUtils","method":"findCRLSignatureCertificateInTruststore","line":94},{"class":"org.keycloak.utils.CRLUtils","method":"check","line":75},```

### How to Reproduce?

1. Generate multiple CRL files from three different intermediate CAs (about 3 should be enough)
2. In the X509 Browser flow, enable CRL checking and specify those files as input
3. Authenticate with a client certificate signed by one of those 3 CAs

Client will be denied.

**Comment by psytester** [comment]
If you get the error "Truststore not available", you need to configure the `spi-truststore-file` instead of `https-trust-store-file`.
The documentation is not clear at this point, but this was my last puzzle to overcome `Truststore not available`.

**Comment by Shiva19908** [comment]
Hi Guys,
Do you know how we could configure CRL for outgoing connections? I couldn't find any documentation about configuring CRLs for outgoing connections?
Kind regards,

**Comment by samratdgreat** [comment]
> I can verify that @psytester 's fix worked for me to get past this error. Here are the args I passed
> 
> ```
>   --https-trust-store-file=<truststore>
>   --https-trust-store-type=<type>
>   --spi-truststore-file-file=<same_truststore>
>   --spi-truststore-file-password=<pass>
>   --spi-truststore-file-hostname-verification-policy=<policy>
> ```
> 
> I can also verify multiple CRL's from 2 different issuing CA's worked to properly revoke/allow access to the correct client

Will there be any conflict if we configure both spi-truststore and https-truststore?

**Comment by stianst** [comment]
Keycloak 24 has made improvements on configuring truststores, which should fix this issue, so going to close this. If it's still an issue please create a new issue with a reproducer with the latest release.
