### ISSUE TITLE
Keycloak performance degrades in some areas with growing number of groups

### ISSUE THREAD

**Issue by pboehm** [keycloak/keycloak#19923]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

## Background 
I'm using Keycloak Groups to implement multi-tenancy in a SaaS application, so that each customer has a corresponding top-level group `customer-XXXXXXXX` with a subgroup for admins and optionally even customer-defined subgroups (all groups are used to assigning realm roles or attributes to users of the corresponding customer).

```
customer-12345
   |- admins
   |- customer-defined
       |- Feature A
       |- Feature B
```

## Problem

With a small number of groups everything is fine but starting with a few thousand groups, operations that rely on `org.keycloak.models.RealmModel#getTopLevelGroupsStream()` or `org.keycloak.models.utils.KeycloakModelUtils#findGroupByPath` (which uses `getTopLevelGroupsStream` internally) are getting really slow. This results in the following problems (there are definitely more ...):

* Importing groups through the `/admin/realms/{realm_name}/partialImport`-Endpoint takes longer with each imported chunk (request duration for importing only top-level groups increases from ~1sec for the first chunk of 200 groups to 210sec for the 80th chunk, with a steeper increase after 10k groups)
  * this probably also happens when importing using `kc.sh` 
* some Admin UI features are really slow and produce high load in the backend (especially with subgroups):
  * In the "Groups"-Page of the Admin-UI loading groups for the right panel takes "forever" but works
  * On the User-Detail-Page for some user, within the "Groups"-Tab, the spinner spins forever and there is definitely load in the backend
* When using Keycloak Authorization Services with a Javascript Policy that uses the `isUserInGroup`-Function (`org.keycloak.authorization.policy.evaluation.Realm#isUserInGroup(java.lang.String, java.lang.String, boolean)`), checking Permissions on a single resource takes multiple seconds with high load

Running IntelliJ's "Find Usages" for `getTopLevelGroupsStream` returns 8 results and 19 results for `findGroupByPath` in non-test code. All of them are probably problematic when having many groups in a realm.

### Version

21.1.0

### Expected behavior

Keycloak Performance should not depend on the number of existing groups in a realm!

Group-Access should not happen in the context of "all groups" like via `org.keycloak.models.RealmModel#getTopLevelGroupsStream()` but within a single group or at least a single page (via `first` and `max`). Ideally `getTopLevelGroupsStream` would be removed and callers have to use alternatives. Especially `org.keycloak.models.utils.KeycloakModelUtils#findGroupByPath` should not traverse all existing groups to find a group with matching path and should do a lookup by top-level group name instead.

### Actual behavior

Keycloak performance degrades in certain areas where `org.keycloak.models.RealmModel#getTopLevelGroupsStream()` is used. Group search by path (`org.keycloak.models.utils.KeycloakModelUtils#findGroupByPath`) currently traverses all existing top-level groups linearly in Java.

### How to Reproduce?

I've created a small python script `kc-create-realm-with-groups.py` that creates a realm and imports a specific number of groups https://gist.github.com/pboehm/5504aa60cf21be53332d96c5aa974871 (this requires `aiohttp` which can be installed with `pip3 install aiohttp`).

Run Keycloak in Docker with in-memory DB on port `38080`:

```
docker run -it --rm \
  --name test-keycloak -p 38080:38080 -e KC_HTTP_PORT=38080 -e KC_DB=dev-file \
  -e KEYCLOAK_ADMIN=test-admin -e KEYCLOAK_ADMIN_PASSWORD=test-admin \
  quay.io/keycloak/keycloak:21.1.0 start-dev
```

For having JDK Flight Recordings, I've sometimes also added `-e JAVA_OPTS_APPEND="-XX:StartFlightRecording:filename=/recordings/recording.jfr,dumponexit=true" -v "/Users/user/recordings:/recordings"`.

Then execute the script and import some groups (either with or without subgroups). The progress and the request duration of the chunk import is shown.

```bash
TOPLEVEL_GROUPS=10000 INCLUDE_SUBGROUPS=True python kc-create-realm-with-groups.py

# the following runs in a transaction timeout on chunk 95 on my machine because it takes longer than 300sec
TOPLEVEL_GROUPS=20000 INCLUDE_SUBGROUPS=False python kc-create-realm-with-groups.py
```

### Anything else?

If it it would be helpful, I could provide JDK Flight Recorder Snapshots.

**Comment by mposolda** [comment]
I am adding to "store" area as the performance is likely storage related. Performance /Scalability might be improved once Keycloak will use new store instead of the current (legacy) store implementation.

**Comment by Redhat-Alice** [comment]
I believe a PR that we've been working on should address this issue as well: https://github.com/keycloak/keycloak/pull/22700
