### ISSUE TITLE
Keycloak 21.1.0 is missing Admin-ui and Account-ui libraries in  Maven Central.

### ISSUE THREAD

**Issue by gknapowski** [keycloak/keycloak#19921]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

It appears with the release of 21.1.0 two libraries did not make it to maven central. 

org.keycloak:keycloak-admin-ui:21.1.0  
org.keycloak:keycloak-account-ui:21.1.0

Both are missing (there is an admin-ui:22.19.0 out there BTW).  

A simple work around is to install locally from source.  

I only noticed as I have a custom build to patch underlying dependencies as required by my security team's scans.

Thank You.

### Version

21.1.0

### Expected behavior

When pulling dependencies listed in a parent pom, all dependencies are in mavencentralrepoisitory.

### Actual behavior

The two libraries are not found.  

### How to Reproduce?

mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=https://repo1.maven.org/maven/2/ -Dartifact=org.keycloak:keycloak-admin-ui:jar:21.1.0

mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -DrepoUrl=https://repo1.maven.org/maven/2/ -Dartifact=org.keycloak:keycloak-account-ui:jar:21.1.0

### Anything else?

I am assuming since the rest of Keycloak is out on maven central, this is an oversite and not intentional.

**Comment by jonkoops** [comment]
Duplicate of #19850
