### ISSUE TITLE
Test app is not functioning - https://www.keycloak.org/app/ 

### ISSUE THREAD

**Issue by Johnny1824** [keycloak/keycloak#19932]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

The test app is not functioning - https://www.keycloak.org/app/ 
No matter what configuration you add is stuck on the save page. No login, no clean config

### Version

21.1.0

### Expected behavior

Sign in option after save.

### Actual behavior

Stuck on the Save screen

### How to Reproduce?

Go to https://www.keycloak.org/app/  add you config --> save
Nothing happens

**Comment by jonkoops** [comment]
I can confirm this issue, but I have no idea how this is deployed.

**Comment by jonkoops** [comment]
@vmuzikar could I ask you to review this PR for me? https://github.com/keycloak/keycloak-web/pull/390
