### ISSUE TITLE
Account v3 - account console link redirect to master realm

### ISSUE THREAD

**Issue by Ekouyoja** [keycloak/keycloak#19933]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

When i try to use account v3 on another realm than Master, the account link redirect to master realm.

### Version

21.1.0

### Expected behavior

Stay on the same realm and redirect to login page of this realm.

### Actual behavior

Redirect on realm master login page.

### How to Reproduce?

Use keycloak v21.1.0
Active account3 feature
Create new realm
pick keycloak.v3 on account theme
Try to access to account console.

### Anything else?

https://pp-rnaconnect.nouvelle-aquitaine.pro/realms/tesuserprofile/account/

**Comment by jonkoops** [comment]
I can confirm this issue, looks like we're not reading the variables injected into the Freemarker template correctly. I'll create a fix for it.
