### ISSUE TITLE
Authentication section in admin console is not working

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#19938]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Unable to open the authentication section for a realm in the admin console in latest nightly release. Works fine in 21.1.0.

### Version

nightly

### Expected behavior

Opens authentication settings

### Actual behavior

![image](https://user-images.githubusercontent.com/2271511/234298258-3699ceaa-c5b4-4409-b0d5-b2ef0490d742.png)

### How to Reproduce?

1. Download latest nightly release
2. Login to admin console and click on Authentication section

**Comment by jonkoops** [comment]
@stianst I am unable to reproduce this one both in the nightly as well as a clean build from `main`. Do you have some data or flags that might be causing this behavior?

**Comment by stianst** [comment]
![Uploading image.png…]()

**Comment by stianst** [comment]
There was a bug in the script I use to download nightly, so when I thought I was using the latest nightly the one I was actually using was from 14th March. With the latest nightly I can't reproduce this one either, so looks like it's been broken for a short period in main, but is now fixed.
