### ISSUE TITLE
New Flow created for Post Login Flow IDP not mark "Used by" at Flows

### ISSUE THREAD

**Issue by jorozcof** [keycloak/keycloak#19942]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I created a new flow for Post login flow in Identity Providers but in the Flows does not appear the flow used. 

![image](https://user-images.githubusercontent.com/115189644/234306132-75b80d0c-0f05-4ac4-b9bc-2b6d4fd18dd6.png)

![image](https://user-images.githubusercontent.com/115189644/234306181-e3385c60-759f-460c-b6b3-26576aad497b.png)

In other created flows, if you check the flow in use.

### Version

20.0.3 && 21.1.0

### Expected behavior

Have the flow mark "in use" in the authentication flows.

### Actual behavior

The new flow created for Post Login Flow mark "Not in use" in the authentication flows.

### How to Reproduce?

1) Created a new flow
2) Add the new flow in a flow the IdentityProviders, specify this flow in Post Login Flow

**Comment by jorozcof** [comment]
> 

@ssilvert How can I bind the flow? "Post login flow" is not appear at the kebab menu to the right of the flow. Or which the bind flow?

![image](https://user-images.githubusercontent.com/115189644/234883460-75a95817-cc45-4d16-bafa-cc0029058263.png)

**Comment by ssilvert** [comment]
For the flow to say something other than "Not in use" in the "Used by" column, it must be bound to one of those 5 flows.  

But I don't know if a "Not in use" flow can still be used as a Post Login Flow.  I suspect it can and the UI is just misleading.  Is your PostBrokerLoginCustom working?

**Comment by jorozcof** [comment]
> For the flow to say something other than "Not in use" in the "Used by" column, it must be bound to one of those 5 flows.
> 
> But I don't know if a "Not in use" flow can still be used as a Post Login Flow. I suspect it can and the UI is just misleading. Is your PostBrokerLoginCustom working?

I Understand.! But I set it up "firstbrokerlogin" and not appear in thoose flows, but this flow appear "built-in". 

My PostBrokerLoginCustom works, I set it up in my Identity Provider for deny access if an user logged many times, and too configured "first broker login". Wouldn't it also be nice to add "post broker login" as "incorporated flow"?

**Comment by ssilvert** [comment]
I need to understand what you are wanting.

For this issue, are you merely suggesting that we add a new binding for Post Login Flow as an enhancement?  I agree that it is confusing and maybe we should add an enhancement.

Or do you believe that there is a bug?

**Comment by jorozcof** [comment]
> I need to understand what you are wanting.
> 
> For this issue, are you merely suggesting that we add a new binding for Post Login Flow as an enhancement? I agree that it is confusing and maybe we should add an enhancement.
> 
> Or do you believe that there is a bug?

I don't know if it's a bug, or just even though the flow is used in Identity Provider, it marks the same way in the column "Used by" "Not in use". I take the functionality of "first broker login" as a reference because the flow is used in identity provider and this does mark that it is used by "Specific Providers"

If the current "post broker login" functionality is correct, I suggest we add a new hook for the post-login flow as an improvement, as it can be a bit confusing.

What do you think?

**Comment by ssilvert** [comment]
I think this could be improved as an enhancement.  I will be honest with you though.  For this kind of thing, we probably won't implement it for quite some time.  The fastest way to see this improved is for someone in the community to submit a PR.  Either do one yourself or find someone else who is interested.
