### ISSUE TITLE
Logout redirect URL truncated since v20

### ISSUE THREAD

**Issue by jendib** [keycloak/keycloak#19950]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Since version 20.0 and specifically this commit https://github.com/keycloak/keycloak/commit/1987c942f527b9f3bbf2a86ba71ba8ae0154ac37 my redirect URI passed in the `post_logout_redirect_uri` parameter gets truncated because it contains %23.

For example:
` https://keycloak.example.com/realms/myrealm/protocol/openid-connect/logout?post_logout_redirect_uri=https://my.website.com/user/Jendib%231234/activity&id_token_hint=blabla` gets redirected to `https://my.website.com/user/Jendib`

### Version

21.0.2

### Expected behavior

The redirect URL should not be truncated.

### Actual behavior

The redirect URL gets truncated.

### How to Reproduce?

Pass a redirect URL in the logout endpoint containing `%23` in the `post_logout_redirect_uri` parameter.

**Comment by mposolda** [comment]
@jendib This one should be already fixed in Keycloak 21.1.1. Could you please try with that version and check if you can still see this?

**Comment by jendib** [comment]
@mposolda It works perfectly, thanks!

**Comment by mposolda** [comment]
@jendib Nice, Thanks for the confirm!
