### ISSUE TITLE
Allow changing admin console logo and favicon from theme.properties

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#19968]
### Description

We should allow changing the logo and favicon from theme.properties in admin console just as we do in account console.  This will make it very easy to make this common change.

### Discussion

Discussed in UI Team Meetings

### Details

Sample `theme.properties`
```
# This is the logo in upper lefthand corner.
# It must be a relative path.
# Defaults to Keycloak logo.
logo=/public/retro-keycloak-logo.png

# This is the link followed when clicking on the logo.
# It can be any valid URL, including an external site.
# By default, this will go to the home page of the selected realm.
logoUrl=http://www.keycloak.org

# This is the icon for the admin console.
# It must be a relative path.
favIcon=/public/favicon.ico

# This is the mime type for the favIcon.
# Default value is 'image/svg+xml'
favIconType=image/x-icon
```

**Comment by jonkoops** [comment]
@ssilvert I think we should also do the same for the Account Console under this issue.

**Comment by ssilvert** [comment]
@jonkoops Account console should already have this.  At least V2 did.

**Comment by jonkoops** [comment]
I don't believe we have this in Account V3 at the moment.

**Comment by ssilvert** [comment]
> I don't believe we have this in Account V3 at the moment.

Created https://github.com/keycloak/keycloak/issues/20200
