### ISSUE TITLE
Paginating on the group tree view doesn't work

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#19966]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The pagination on the group tree view is not right

### Version

main

### Expected behavior

It should work

### Actual behavior

it's not right

### How to Reproduce?

have more then 20 groups and try and go to the next page

**Comment by jonkoops** [comment]
@edewit this one still needs to get backported I believe.

**Comment by edewit** [comment]
done https://github.com/keycloak/keycloak/pull/20644
