### ISSUE TITLE
Wrong URL in documentation for CURL example

### ISSUE THREAD

**Issue by joehni** [keycloak/keycloak#19971]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

The [CURL example in the documentation](https://www.keycloak.org/docs/latest/server_development/index.html#examples-of-using-curl) to get an access token uses the URL Path
  `/realms/master/protocol/openid-connect/token`
but it should be 
  `/auth/realms/master/protocol/openid-connect/token`

### Version

latest

### Expected behavior

Executing the curl comman of the example should return the JSON structure with the token

### Actual behavior

The call returns a minimal HTML page with the message "Resource not found"

### How to Reproduce?

Execute the call of the example

**Comment by vickeybrown** [comment]
The legacy distribution used "/auth". However, that was dropped with the Quarkus distribution. You can find more info here - https://www.keycloak.org/migration/migrating-to-quarkus

**Comment by joehni** [comment]
Funny then, since this is 20.0.3 running on Quarkus. So, if it's not the documentation, is it a bug?
![grafik](https://user-images.githubusercontent.com/795149/234784052-49264ebc-f1da-4e26-9449-391f020ed7af.png)

**Comment by joehni** [comment]
Sorry for the noise, the server was explicitly started with /auth as http-relative-path
