### ISSUE TITLE
Invalid username or password.

### ISSUE THREAD

**Issue by 13567436138** [keycloak/keycloak#19979]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

![image](https://user-images.githubusercontent.com/31508490/234795417-b4a45ac8-a55d-4b18-aef5-3740be31e350.png)

password comes from 

```
[root@mycompany keycloak]# kubectl get secret -n keycloak keycloak -o yaml
apiVersion: v1
data:
  admin-password: OFBTWWZITUVibA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: keycloak
    meta.helm.sh/release-namespace: keycloak
  creationTimestamp: "2023-04-27T06:41:30Z"
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-13.1.1
  name: keycloak
  namespace: keycloak
  resourceVersion: "6830628"
  uid: c12fbd0d-4a67-4408-bd25-833e51ec79cd
type: Opaque
[root@mycompany keycloak]# echo OFBTWWZITUVibA==|base64 -d
8PSYfHMEbl[root@mycompany keycloak]#
```

### Version

20.0.5

### Expected behavior

can login

### Actual behavior

invalid username or password

### How to Reproduce?

helm install
login

**Comment by sschu** [comment]
Are you using some third-party helm chart? If yes, you will probably have to ask the helm chart provider for any issues you have with it. If no, you should provide complete steps to reproduce the problem.

**Comment by 13567436138** [comment]
helm pull bitnami/keycloak
tar zvxf keycloak-13.1.1.tgz
helm install keycloak -n keycloak --create-namespace .

**Comment by 13567436138** [comment]
solved by checking values.yaml

**Comment by nickthewitcher** [comment]
> solved by checking values.yaml

How do yoy solve? I have the same problem, thanks in advance for your quick repply.

**Comment by Gusta-Darede** [comment]
Hi

I have the same problem. My solution was to check the values.yaml as mentioned by @13567436138  and i saw that the default user installed by helm bitnami/keycloak is: user

![image](https://github.com/keycloak/keycloak/assets/77642385/50a3fb4e-95c1-4283-b260-dc3e4c1bb1b8)

Normally, the default user is admin, but not in this case.
