### ISSUE TITLE
Default Roles show all roles if "Hide inherited roles" is not checked 

### ISSUE THREAD

**Issue by kheckelmann** [keycloak/keycloak#19982]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the default roles section of the Keycloak Administration Console all roles are shown if the "Hide inherited roles" checkbox is not checked. I don't believe this is intended, it lets the user believe that alle roles are assigned to new users even if that is not the case.

### Version

21.1.1

### Expected behavior

If the "Hide inherited roles" checkbox is not checked in the default roles section, all assigned default roles should be shown as well as all the roles that are inherited from the default roles. Inherited roles can be associated roles if the default role is a composite role.

### Actual behavior

If the "Hide inherited roles" checkbox is not checked in the default roles section, all roles are shown.

### How to Reproduce?

- Go to Realm settings -> User registration -> Default roles
- Deselect the "Hide inherited roles" checkbox

**Comment by ssilvert** [comment]
You are correct.  There is a bug here.

For example, by default, there is no role assigned from `realm-management`.  But if you uncheck `Hide inherited roles`, then all the roles from `realm-management` are shown.

**Comment by edewit** [comment]
That is not wrong @ssilvert these roles have not been assigned to the user directly the user gets them implicit because they are the default roles.

@kheckelmann I think this is not wrong, default roles are not directly assigned and therefor hidden only direct assigned roles are shown.

**Comment by ssilvert** [comment]
@edewit The user does not get them implicitly.  It's showing lots of roles that are not default roles.  Uncheck `Hide inherited roles` and you will see roles such as `master-realm->manage-realm`.  This is not a default role.

When you uncheck `Hide inherited roles`, it should only show those roles assigned directly and any roles inherited from those assigned directly.
