### ISSUE TITLE
Getting  "We are sorry... An internal server error has occurred" when trying to create an initial user

### ISSUE THREAD

**Issue by Reedarh** [keycloak/keycloak#19989]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

When I create an initial user, I get the following error, "We are sorry...
An internal server error has occurred"

### Version

21.1.1

### Expected behavior

I expect to be logged in as an admin

### Actual behavior

I get an error 

### How to Reproduce?

Try creating an initial user for the quarkus  version

**Comment by Reedarh** [comment]
Yes, it was from the welcome screen. I started using ./bin/kc.sh start-dev, and I was able to open the welcome page through localhost:8080, I was then asked to create an initial user, but after filling in the form and submitting, I get the error .

I don't get any issues while using a container

**Comment by Reedarh** [comment]
Sorry, I was able to use env variables, I'm new to keycloak, so I'm just starting to understand it

**Comment by vmuzikar** [comment]
@Reedarh Thanks for the update. I'd still be interested in a reproducer for the welcome screen. :) It might be a bug.
