### ISSUE TITLE
Keycloak 21.1.1: Paging and filtering not working in "Assign roles" popup for Groups

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#19981]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the new Admin UI, in "Role Mapping" tab for a group, when clicking on "Assign roles" button, the popup will display only the first page of role results. Clicking on next, will display the same first page of results, so its not possible to display subsequent pages.

When entering search term in "Search by role name" field, the search term doesn't affect the result, but the same unfiltered first page of results is displayed.

The requests sent to keycloak server:

/groups/b06c2caa-7742-4747-9f96-8fcd78c43cc8/role-mappings/realm/available?first=0&max=11 - result contains all 21 roles (I have 21 in the realm), but the UI displays only first 10
/groups/b06c2caa-7742-4747-9f96-8fcd78c43cc8/role-mappings/realm/available?first=10&max=11 - result contains all 21 roles (I have 21 in the realm), but the UI displays only first 10
/groups/b06c2caa-7742-4747-9f96-8fcd78c43cc8/role-mappings/realm/available?first=0&max=11&search=test - result contains all 21 roles (I have 21 in the realm), but the UI displays only first 10

Theories: it's either a backend issue, or the parameter names sent from the frontend are incorrect.

### Version

21.1.1

### Expected behavior

* Clicking on next should display next page instead of first page only
* Entering search term should display only matching roles

### Actual behavior

* Clicking on next shows first page only
* Entering search term has no effect on search results (non-matching roles are retrieved)

### How to Reproduce?

* Add more then 10 roles to the realm
* See that paging and filtering on "Assign roles" popup don't work

**Comment by ssilvert** [comment]
I have reproduced this bug.  Attaching a partial import file to create 150 roles.

[realm-role-many.zip](https://github.com/keycloak/keycloak/files/11343386/realm-role-many.zip)

**Comment by lrozenblyum** [comment]
Hello Erik, I assume it will be backported to the 21.1 release branch,
right?

**Comment by edewit** [comment]
@lrozenblyum yes that has been done in https://github.com/keycloak/keycloak/pull/20142

**Comment by frankXorFox** [comment]
Hi guys - thanks for working on this. In a bit of a panic this weekend because we just went over 100+ roles in a major installation and can't assign roles via the admin ui due to this issue. I just wanted to comment that the description mentions 'groups', but it happens on 'user' role assignments as well. I understand that this may use the same dialog/popup as groups. But I just thought I'd mention it. Thanks again for working on it.

**Comment by lrozenblyum** [comment]
@frankXorFox 21.1.2 is released and includes the fix for this issue, you may give it a try.
