### ISSUE TITLE
Adding a truststore to Keycloak in openshift seems to be experimental

### ISSUE THREAD

**Issue by tom-youd** [keycloak/keycloak#19987]
### Description

Looking at this [article](https://access.redhat.com/solutions/6623671), the `spec` for adding a truststore to keycloak is experimental? I've looked through the open issues and couldn't spot anything obvious.

### Discussion

What is the current use case for this?

### Motivation

We're trying to add an OIDC IDP in front of KeyCloak and it fails to talk to the IDP because it doesn't trust the endpoint.

### Details

We want a way to trust the endpoints for that IDP. 
Would is be possible to either -
 - Create a global trust store where we can add CA certs to
 - Accept a CA cert just for a given IDP and add it on a connection-by-connection basis for the IDP.

**Comment by Jamstah** [comment]
And, for individual IDP configuration:
- https://github.com/keycloak/keycloak-community/pull/345
- https://github.com/keycloak/keycloak/issues/13300

Neither of those are in a milestone though

**Comment by vmuzikar** [comment]
Thank you for opening this issue. As suggested by @Jamstah, this is a duplicated issue. Unfortunately, it won't most probably make it to 22. Thanks for understanding.
