### ISSUE TITLE
Keycloak 21.1.1: filter on Sessions gets stuck

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#19999]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Sessions filter becomes not working after first change of value.

### Version

21.1.1

### Expected behavior

Filter should switch to the new value clicked.

### Actual behavior

Filter gets stuck, no requests to backend are sent.

### How to Reproduce?

Go to admin console -> Sessions
Select Filter: 'Regular SSO'.
Try to use Filter 'Offline' (or 'All sessions types').

**Comment by ssilvert** [comment]
I have reproduced this.  Workaround is to go out of sessions, then go back in again and choose a different filter.

**Comment by lrozenblyum** [comment]
Not supposed to be backported to 21.1.*?

**Comment by stianst** [comment]
Backport to 21.1: https://github.com/keycloak/keycloak/pull/20712
