### ISSUE TITLE
Group attribute query is missing QueryParams in java admin client

### ISSUE THREAD

**Issue by PapPatrick** [keycloak/keycloak#20016]
### Description

Using the Java admin client library it is currently not possible to query attributes with additional parameters. Thus, the parameter described in the REST API  (first, max, and briefRepresentation) cannot be set when using the admin-client library.

### Motivation

The admin client library should match the REST API documentation.

### Details

#12964 implemented the group attribute search. However the GroupsResource is misssing the additional method with all QueryParams. For reference: [the UsersResource ](https://github.com/keycloak/keycloak/blob/9186327807477f4ca5c36d0adb6fd7b7f62b9721/integration/admin-client/src/main/java/org/keycloak/admin/client/resource/UsersResource.java#L120) implements all parameters.

**Comment by danielFesenmeyer** [comment]
See linked PR for the implementation.
