### ISSUE TITLE
Restrict removing admin realm role in master realm

### ISSUE THREAD

**Issue by Sky-555** [keycloak/keycloak#20015]
### Description

Using one and only admin user account in master realm, I tried removing admin role from Role Mapping, and poof the whole master realm is now gone. I cannot take any action to change the settings anymore.

Please restrict unassigning admin role especially in master realm, by checking whether there is no more than one account having the admin realm role, or provide an alternative way for user to gain back admin access.

**Comment by sschu** [comment]
This is strongly related to https://github.com/keycloak/keycloak/issues/19913.

@Sky-555 are you fine with closing this and tracking the progress in the aforementioned issue? Feel also free to comment there.

**Comment by sschu** [comment]
Closing this because of no feedback.
