### ISSUE TITLE
publicClient is not working

### ISSUE THREAD

**Issue by ghost** [keycloak/keycloak#20024]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

Using Keycloak 21.1.1 and keycloak-admin-client 21.1.1

### Version

21.1.1

### Expected behavior

Setting public client using keycloak-admin-client via `.setPublicClient(true)` allows the creation of a client with Client authentication disabled
![image](https://user-images.githubusercontent.com/93596537/235147443-7721a2b4-9d8f-4af4-9f5f-2bb83712ff4d.png)

### Actual behavior

Setting public client using keycloak-admin-client via `.setPublicClient(true)` breaks client. Cannot authenticate, cannot edit the client neither from UI nor from admin client.

### How to Reproduce?

```
Keycloak kc = KeycloakBuilder.builder()
        .serverUrl("http://10.200.10.1:18080/auth") //legacy auth enabled in Keycloak 21.1
        .realm("master")
        .username("admin")
        .password("admin")
        .clientId("admin-cli")
        .build();

    RealmRepresentation realm = new RealmRepresentation();
    realm.setRealm("tenant1");
    realm.setEnabled(true);

    kc.realm("tenant1").remove();
    kc.realms().create(realm);

    ClientRepresentation newClient = new ClientRepresentation();
    newClient.setName("Test Client");
    newClient.setClientId("test-client");
    newClient.setRedirectUris(List.of("*"));
    newClient.setEnabled(true);
    newClient.setPublicClient(true); // breaks the UI and client setting

    kc.realms().realm("tenant1").clients().create(newClient);
```

**Comment by robson90** [comment]
I can confirm that this is still the case with version 22.0.1. 

I stumbled on this, when I was working with the [Terraform Provider](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs). When publicClient is true, then "Credentials" tab is shown. If publicClient is false, "Credentials" tab is NOT shown.

I searched in the specification for the attribute and I can't find it.
Specification: https://saml.xml.org/saml-specifications
