### ISSUE TITLE
Keycloak-Minio integration not working after upgrading Keycloak from version 13.0.0 to version 19.0.0

### ISSUE THREAD

**Issue by gaurav-16** [keycloak/keycloak#20022]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

We are facing an issue with the integration between Keycloak and Minio after upgrading from version 13.0.0 to version 19.0.0 of Keycloak. Prior to the upgrade, we had successfully integrated Keycloak and Minio, and had set up a forward proxy for Minio. However, after the upgrade, when we log into our platform and try to access Minio, we are prompted to log in again.

We suspect that the issue may be related to changes in the way authentication sessions are managed between Keycloak versions, and that the session cookie used by Keycloak to authenticate requests to Minio is not being passed correctly or is being invalidated prematurely.

We have reviewed the Keycloak and Minio integration documentation to ensure that we have followed the correct configuration steps for version 19.0.0, and have enabled debug logging in both Keycloak and Minio. However, we have been unable to identify the root cause of the issue.

### Version

Keycloak v13.0.0

### Expected behavior

After logging into the platform, users should be able to access Minio without being prompted to log in again.

### Actual behavior

Users are prompted to log in again when trying to access Minio.

### How to Reproduce?

1. Set up Keycloak and Minio integration using the forward proxy for Minio.
2. Upgrade Keycloak from version 13.0.0 to version 19.0.0.
3. Log into the platform and try to access Minio.
4. Observe that you are prompted to log in again.

### Anything else?

- Keycloak server logs and Minio server logs are available upon request.
- Keycloak and Minio integration configuration details are available upon request.

**Comment by vickeybrown** [comment]
Hi! it looks like you haven't upgraded to the latest version of Keycloak. I'd recommend doing that and trying again. I also found this documentation from MinIO that goes through how to configure it with Keycloak 21.0.0, which may be of use to you https://min.io/docs/minio/macos/operations/external-iam/configure-keycloak-identity-management.html

**Comment by abstractj** [comment]
Thank you for reaching out. We understand the difficulties faced with the integration between Keycloak and Minio, although we do not support Minio. Since the issue seems to be specifically related to Minio, I'd suggest reporting the issue to their team.

That being said, if you come across any issues specifically related to Keycloak that are within our scope of support, please feel free to reach out.
