### ISSUE TITLE
Use an original domain name of Kerberos Principal in UserModel attribute instead of configured value of Kerberos realm in User federation

### ISSUE THREAD

**Issue by hokuda** [keycloak/keycloak#20045]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

There are 2 Active Directory domains (EXAMPLE1.COM and EXAMPLE2.COM) which have mutual trust.
Configuring User Federation of kerberos against one of them (EXAMPLE**1**.COM), RH-SSO/Keycloak can authenticate user1@EXAMPLE**2**.COM against the domains.
However, the "KERBEROS_PRINCIPAL" attribute in UserModel is "user1@EXAMPLE**1**.COM". It should be "user1@EXAMPLE**2**.COM".

### Version

21.0.2/upstream

### Expected behavior

It should be "user1@EXAMPLE**2**.COM".

### Actual behavior

"user1@EXAMPLE**1**.COM".

### How to Reproduce?

1. Setup AD domains of EXAMPLE1.COM and EXAMPLE2.COM then make mutual trust between them
2. configure Keycloak User federation so that it authenticates users agaist EXAMPLE1.COM
3. log in Keycloak as user1@EXAMPLE2.COM

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by mposolda** [comment]
Some notes how to possibly address this (But not 100% sure):

- This method SPNEGOAuthenticator.getAuthenticatedUsername() from https://github.com/keycloak/keycloak/blob/21.1.1/federation/kerberos/src/main/java/org/keycloak/federation/kerberos/impl/SPNEGOAuthenticator.java#L115-L119 might be renamed to "getAuthenticatedPrincipal()" and it should return whole Kerberos principal (without cutting realm from it)
- The caller storage providers (KerberosFederationProvider and LDAPStorageProvider) may need some options on them whether to cut Kerberos realm from the principal (So keep something like "john" for the principal "john@FOO.com") or whether to keep the Kerberos realm (so something like "john@FOO.com") when they lookup user based on the principal. Also we will need to configure on LDAP provider what should be the LDAP attribute to look at Kerberos principal (in MSAD it is typically "userPrincipalName" AFAIR, but this attribute may be MSAD specific (not 100% sure)). We can possibly have single option to address both parts of this or introduce more options (at least to LDAP provider). Not 100% sure now what would be best.

- To support LDAP provider fallback (EG. for the case when LDAP-server-1 handles users from kerberos realm "REALM1.ORG" when LDAP-server-2 handles users from kerberos realm "REALM2.ORG"), we may also need some changes in the upper storage layer (UserStorageManager or so) to handle LDAP providers fallback.

The most difficult might be testing part (we have `KerberosLdapCrossRealmTrustTest` and `KerberosStandaloneCrossRealmTrustTest`, but not 100% sure they can be used).

**Comment by flaviodonze** [comment]
After updating from Keycloak 21 to 26 the username of the user contains the Realm. I'm assumig this change here is the cause of it. 
We don't use the LDAP configuration, only a plain User federation > kerberos. But here I have no option to change this behavior, how can I configure keycloak to only use the username without realm?

**Comment by cluck** [comment]
Another issue: in AD, additional user principals are stored in (altSecurityIdentities)[https://learn.microsoft.com/en-us/windows/win32/adschema/a-altsecurityidentities], but with a prefix "Kerberos:".
