### ISSUE TITLE
Update passthrough behavior and docs

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20070]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Update the docs about a `passthrough` proxy. 

### Version

21.1.1

### Expected behavior

A `passthrough` proxy is usually handling TLS and doesn't add headers.

### Anything else?

I will create a PR

**Comment by acuteaura** [comment]
FWIW i'd have rather seen a new value with the old one throwing a deprecation warning. `edge` didn't exist when i built my config and upgrading with `passthrough` lead to a funny semi-working state where the login flows worked, but other things didn't (without clear cause, e.g. the admin console redirect throws an `undefined` as exception)

**Comment by ahus1** [comment]
@acuteaura - sorry to hear that this was difficult for you to find. That `passthough` would parse headers was really a bug, and it should have never done that. I agree that the longer a bug exists, the more people might expect that behavior, and I'll consider it for future cases.

To improve Keycloak's behavior, please create a new issue with the exception you've seen, so it could show a better error message or handling of the situation and reference it here. Thanks!
