### ISSUE TITLE
Add xml schema to Infinispan caches to have style checking and type hinting in IDE

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#20071]
Currently, in the XML cache config file, there is no schema defined, for example,
https://github.com/keycloak/keycloak/blob/81f80a725a80a8e088d5b01cff379c1ea44da630/model/map-hot-rod/src/main/resources/config/realms-cache-config.xml

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
