### ISSUE TITLE
Event-Type: "User info request error" does not work

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#20087]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Hi,

I have added the event type: "User info request error" for my keycloak events to check when a request fails at the user info endpoint.

If the event should now be published and I want to filter for it in the events overview, the following error occurs:

admin ui:

![Screenshot from 2023-05-02 14-38-29](https://user-images.githubusercontent.com/54103655/235668490-a6227bfa-a09a-45dc-bd86-a585694e1b89.png)
![Screenshot from 2023-05-02 14-38-49](https://user-images.githubusercontent.com/54103655/235668499-ed2ed28b-bdf3-46e6-9a57-7f95f6f3cc56.png)

browser admin console:
![Screenshot from 2023-05-02 14-40-11](https://user-images.githubusercontent.com/54103655/235668609-361d117e-900c-4fca-9d2d-fe42d69b8735.png)

The search for the other event types works.
Is there anything to consider with the event type ?

### Version

21.1.1

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by ssilvert** [comment]
I have reproduced this bug.
