### ISSUE TITLE
`searchForUserStream` called twice when navigating between pages in the admin UI for searching users

### ISSUE THREAD

**Issue by cesdperez** [keycloak/keycloak#20086]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When implementing a custom user storage provider, the `searchForUserStream` function (from `UserQueryProvider`) is called twice when navigating between pages in the admin UI for searching users. One call includes the `firstResult` and `maxResults` parameters for pagination, as expected. However, an unexpected additional call is made to searchForUserStream without `firstResult` and `maxResults` parameters.

This is a problem specially if searching for `*`, because it's retrieving all users from my storage in between moving to the next results page.

### Version

21.0

### Expected behavior

`searchForUserStream` should only be called once with the correct `firstResult` and `maxResults` parameters when navigating between pages in the admin UI for searching users.

### Actual behavior

`searchForUserStream` is called twice, once with the correct pagination parameters and once without any pagination parameters

### How to Reproduce?

1 - Implement a custom user storage provider with a searchForUserStream function that logs the parameters it receives.
2 - Deploy the custom user storage provider and configure it for a realm in Keycloak.
3 - Have at least more than 10 users in the storage
4 - Go to the admin UI and navigate to the Users page.
5 - Search for "*".
6 - Move to the next page(s).
7 - Observe the log output, and notice that searchForUserStream is called twice, with and without pagination parameters.

**Comment by ssilvert** [comment]
@cesdperez I've looked through the latest code and I don't see how this would be happening.

Can you check the latest nightly build and let me know if you see the problem?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by cesdperez** [comment]
Thanks for looking into it @ssilvert.

I'm using Docker, I tried with the latest available nightly from quay.io and still can reproduce the issue.
```
quay.io/keycloak/keycloak:nightly@sha256:97d38c6389326c68defe1594256f1861763f2d8438db20829845531ea169d0f4
```

_I'll restate that **I'm using a custom User Storage Provider**. To be more clear, I'm implementing all these interfaces: `UserStorageProvider, UserRegistrationProvider, UserLookupProvider, UserQueryProvider`. The issue in discussion is in `searchForUserStream(...)`, that's defined on `UserQueryProvider`.
I haven't checked if this also happens with Keycloak's default user storage.
The cache setup (when configuring the user storage provider in admin UI) doesn't seem to affect this behavior._

I recorded a video to make it a bit more clear. Sadly there are parts I can't show because there's sensible information.

https://user-images.githubusercontent.com/16674679/236164477-909e8c30-e570-4249-9fb6-4690d871a73b.mov

Notice how loading the first page is faster than loading the subsequent pages.

The calls made by the browser seem to be ok
```
[1] GET http://localhost:8080/admin/realms/master/ui-ext/brute-force-user?briefRepresentation=true&first=0&max=21&search=xxx
[2] GET http://localhost:8080/admin/realms/master/ui-ext/brute-force-user?briefRepresentation=true&first=20&max=21&search=xxx
[3] GET http://localhost:8080/admin/realms/master/ui-ext/brute-force-user?briefRepresentation=true&first=40&max=21&search=xxx
```

But here's what happens under the hood.

[1] performs this call to my user storage provider, which is ok
```
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx, firstResult: 0, maxResults: 21)
```

but [2] performs these calls:
```
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx)
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx, firstResult: null, maxResults: null)
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx, firstResult: 20, maxResults: 21)
```

and the same with [3]:
```
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx)
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx, firstResult: null, maxResults: null)
searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx, firstResult: 40, maxResults: 21)
```

In this case, it's not that bad because there're only 500 users matching the criteria "xxx". If you search for "*" though, this is pretty bad.

Something also worth mentioning, is that these calls `searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx, firstResult: null, maxResults: null)` are triggered by the calls to `searchForUserStream(realm: 8c84d58d-6dd2-456a-824c-2155672cb6c3@65023d20, search: xxx)`. That is what the default implementation of the unbounded `searchForUserStream` does. It's not relevant to the issue tho, the point is that the unbounded (non-paginated) call to `searchForUserStream` shouldn't be performed at all.

**Comment by ssilvert** [comment]
@edewit Can you take a look at this?  I browsed the code and I don't see where that first unbounded call to `searchForUsersStream` is coming from.  But maybe you have an idea.

There is probably a quickstart that implements `UserQueryProvider` we could hack to reproduce the problem.

**Comment by pedroigor** [comment]
@cesdperez The behavior might be happening because you are not implementing the methods from `UserCountMethodsProvider` interface. This interface is a parent of `UserQueryProvider`.

By default the methods at `UserCountMethodsProvider` delegate to `searchForUserStream` methods.

Could you check if the assumption is correct?

**Comment by DavidSonoda** [comment]
> @cesdperez The behavior might be happening because you are not implementing the methods from `UserCountMethodsProvider` interface. This interface is a parent of `UserQueryProvider`.
> 
> By default the methods at `UserCountMethodsProvider` delegate to `searchForUserStream` methods.
> 
> Could you check if the assumption is correct?

I can verify this is true as the same exact thing described by OP happened to me, after implementing the count method everything works like a charm. 

But maybe the documentation is a bit misleading. Specifically, implementing `int getUsersCount(RealmModel realm)` suggested by the [Server Developer Guide](https://www.keycloak.org/docs/26.0.7/server_development/#implementing-userqueryprovider) is not sufficient (not sure if it's necessary) since `getUsersCount(RealmModel realm, Map<String, String> params)` is the count method that I saw getting called, not sure if the documentation is outdated or not.

Also if the specific logic/order of these interface methods are getting called are documented that would be much appreciated.
