### ISSUE TITLE
Custom theme - url.resourcesCommonPath references wrong theme

### ISSUE THREAD

**Issue by dfs-** [keycloak/keycloak#20085]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

In a custom theme with own `template.ftl` it is not possible to reference resources (in this case CSS) in the parent theme it is using. The theme in question references "keycloak in theme.properties:

```
parent=keycloak
```

Since the update from 20.0.2 to 21.1.1 the references inside the ftl are forced to use the active theme

| 20.0.2 | 21.1.1 |
| ------ | ------ |
| ![20 0 2](https://user-images.githubusercontent.com/6563013/235657432-3d528d6f-cdfd-4262-b4b5-6d2e5fa4384d.png) | ![21 1 1](https://user-images.githubusercontent.com/6563013/235657449-dde72423-d5d3-4768-912c-7df6fcee3506.png) |

See how the patternfly css files are correctly retrieved in the "keycloak" theme in 20.0.2, but are retrieved from "nx-swl" in 21.1.1. In the latter they don't exist, as they are simply inherited from the "keycloak" theme.

The `template.ftl` gets those stylesheets using the following code
```
<link rel="icon" href="${url.resourcesPath}/img/favicon.ico" />
<#if properties.stylesCommon?has_content>
	<#list properties.stylesCommon?split(' ') as style>
		<link href="${url.resourcesCommonPath}/${style}" rel="stylesheet" />
	</#list>
</#if>
```

### Version

21.1.1

### Expected behavior

Retrieve those stylesheets the way 20.0.2 did (referencing the theme where they are exist)

### Actual behavior

Force files to be included in the custom theme, rather than using those from the theme they are provided.

### How to Reproduce?

Perform steps from https://www.keycloak.org/docs/latest/server_development/#_themes
The theme used to reproduce this locally is a login theme only if this matters.

**Comment by mposolda** [comment]
@dfs- @gvonroten Thanks for the report.

We will try to look into this as it is a regression...

**Comment by douglaspalmer** [comment]
@dfs- Are you able to share your theme.properties file?

**Comment by dfs-** [comment]
@douglaspalmer sorry for the late reply.

The file contains only the following lines:

```
parent=keycloak
import=common/nx-swl
locales=de,en,es,fr,it,nl,no,pl
author=dfs

kcNxLogo=nx-logo
```

**Comment by sirkrypt0** [comment]
I also use a custom `common` theme. I figured out that you can just use `parent=keycloak` in the `theme.properties` of your `common` theme to include the common resources from the Keycloak theme like the `web_modules` stuff.

Then, the patternfly css files will still be loaded from your `nx-swl` but this time will be found because of the inheritance.
