### ISSUE TITLE
Language couldn't be changed on the /login-actions/action-token page

### ISSUE THREAD

**Issue by s-solianyk-onventis** [keycloak/keycloak#20094]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

It is currently not possible to change the language in the `/login-actions/action-token` page for the `Action expired` case. When the user selects a different language from the drop-down list, the language does not change and a different message is displayed.

### Version

21.1.1

### Expected behavior

The language could be changed correctly in the `/login-actions/action-token` page.

### Actual behavior

The error page is displayed in the user's default language. It is not possible to change the language and see the same error in another language. After changing the language, another error is displayed (`Invalid Request`), but the language does not change.

![image](https://user-images.githubusercontent.com/120454144/235726550-299424f2-81de-45f7-99af-9e35433f31e6.png)

### How to Reproduce?

- Install Keycloak 21.1.1
- Enable `update-email` feature
- Go to realm settings, `Login` tab, enable `Email as username`, `Login with email`, `Verify email`, `Edit username`
- Go to realm settings, `Email` tab, configure smtp
- Go to realm settings, `Email` tab, enable `Internationalization` and add 2+ supported languages
- Create new user with verified email and password
- Login to the account console with a new user and click to the `Update email`

![image](https://user-images.githubusercontent.com/120454144/235724713-96a11668-0501-4d39-8be6-0a62f789c1a8.png)
- Update email to the new one
- Email with link should be sent
- Wait 5 minutes until link is expired
- Click on the link from the email, error page with "Action expired." message is shown

![image](https://user-images.githubusercontent.com/120454144/235725951-bcb294ca-769d-4f2d-ae25-ba8db686efc4.png)

- Change language

**Comment by ssilvert** [comment]
@s-solianyk-onventis I haven't had time to set up email and try to validate this, but I'm going to go ahead and remove from triage status.  

It will probably be quite some time before we can get to this one, so if you need it to be fixed quickly it would be helpful if you could submit a PR for it.

**Comment by s-solianyk-onventis** [comment]
@ssilvert, thanks for looking at the problem.
Checked again after updating the version. This issue is not reproduced in Keycloak version 22.0.5.
