### ISSUE TITLE
Duplicated serverPrincipal property in LDAPStorageProviderFactory

### ISSUE THREAD

**Issue by simse07** [keycloak/keycloak#20101]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Rendering a custom user-federation in the admin-ui fails, because of duplicated children ids "serverPrincipal":
`Encountered two children with the same key, `serverPrincipal`. `

Looking at org.keycloak.storage.ldap.LDAPStorageProviderFactory the property for "serverPrinicipal" is added 2 times:

1. https://github.com/keycloak/keycloak/blob/main/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java#L208
2. https://github.com/keycloak/keycloak/blob/main/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java#L225

### Version

21.1.1

### Expected behavior

Property is only added once, so the page is rendered correctly.

### Actual behavior

There are missing labels and the page is not usable to create a new custom user-federation.

### How to Reproduce?

Add a new LDAPStoreageProvider and try to create an instance via admin-ui.

**Comment by ssilvert** [comment]
Looks like it's not a UI issue.  Moving to the storage team.
