### ISSUE TITLE
Unable to template emails in EventListenerProvider (No realm in provided KeycloakSession)

### ISSUE THREAD

**Issue by ValentinLorand** [keycloak/keycloak#20105]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I have a custom EventListenerProvider which instanciate a FreeMarkerEmailTemplateProvider() to send a email with keycloak.

My implementation works well with the keycloak version 21.0.1. but no longer works in  21.1.x.

When I debug Keycloak, I see that there is no realm in the context of the KeycloakSession given to EventListenerProviderFactory in order to instanciate my EventListenerProvider.

I have this error : 
Cannot invoke "org.keycloak.models.RealmModel.getEmailTheme()" because the return value of "org.keycloak.models.KeycloakContext.getRealm()" is null

Example of my code : 
```
public class BlockLoginEventListenerProviderFactory extends EventListenerProviderFactory {

    @Override
    public BlockLoginEventListenerProvider create(KeycloakSession keycloakSession) {
        return new BlockLoginEventListenerProvider(keycloakSession);
    }

    @Override
    public String getId() {
        return "gzl-block-login";
    }
}
```

```
public class BlockLoginEventListenerProvider extends EventListenerProvider {

   KeycloakSession keycloakSession;

    public BlockLoginEventListenerProvider(KeycloakSession keycloakSession) {
       this.keycloakSession = keycloakSession;
    }

    @Override
    public void onEvent(Event event) {
          MyUserModelAdapter myUserModelAdapter = (MyUserModelAdapter) this.getKeycloakSession().users().getUserById(keycloakSession.getContext().getRealm(), event.getUserId());
          ...
          try {
              // Create email template
              EmailTemplateProvider emailTemplateProvider = new FreeMarkerEmailTemplateProvider(this.keycloakSession)
                      .setRealm(keycloakSession.getContext().getRealm())
                      .setUser(myUserModelAdapter);
              // Send email
              emailTemplateProvider.send("xxx", "email-blocked.ftl", attributes);
         } catch (EmailException e) {
              log.warn("Mail not sent");
         }
    }
}
```

### Version

21.1.0 & 21.1.1

### Expected behavior

When I log in throught account client (https:/xxx/auth/realms/myRealm/account/), i want to send an email to notify the user if it account is disabled. For this I use an specific implementation of EventListenerProvider and EventListenerProviderFactory.

Example of KeycloakSession provided to create an instance of EventListenerProvider when it works : 
![image](https://user-images.githubusercontent.com/47445051/235863696-c515fb3b-7856-42b1-8a87-67652be6dd17.png)

### Actual behavior

Unable to instanciate a FreeMarkerEmailTemplateProvider to send an email in the onEvent() method of my custom EventListenerProvider implementation.

The KeycloakSession provided in the create() method of the factory doesn't contains the RealmModel. A realm is required to retrieve the email templates.

Example of bad KeycloakSession provided to create an instance of EventListenerProvider : 
![image](https://user-images.githubusercontent.com/47445051/235863867-077b3ed0-ec4d-4870-9a8f-6c8e00e3847c.png)

Note that this create() method is called 3 times during the connection attempt. The first two times, the KeycloakSession provided contains the realm but the third time it is no longer the case

### How to Reproduce?

Implement an EventListenerProvider and an EventListenerProviderFactory which instanciate a FreeMarkerEmailTemplateProvider in the onEvent() method. Try to log in to an user account (/realms/myRealm/account). An exception should be thrown.

**Comment by mposolda** [comment]
Just a clarification: In your email provider, you're calling `keycloakSession.realms().getRealmByName("myRealm")` . But I don't see any call to something like `keycloakSession.getContext().getRealm()` . Or am I missing something?

Could you please update the source of your provider in the description to actually have the provider, which worked before and doesn't work now as expected?

**Comment by ValentinLorand** [comment]
Thanks for the reply !

I've just tried it by retrieving the realm via the methods `keycloakSession.getContext().getRealm()`.

Unfortunately, I have the same problem : NullPointerException. It seems that there is no available Realm in the provided KeycloakSession.

The Error trace : 

```
2023-05-19 17:19:11,641 ERROR [org.keycloak.events.EventBuilder] (executor-thread-0) Failed to send type to xxx.events.BlockLoginEventListenerProvider@64b4e589: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getId()" because "realm" is null
        at org.keycloak.models.cache.infinispan.UserCacheSession.isRegisteredForInvalidation(UserCacheSession.java:192)
        at org.keycloak.models.cache.infinispan.UserCacheSession.getUserById(UserCacheSession.java:198)
        at xxx.events.BlockLoginEventListenerProvider.onEvent(BlockLoginEventListenerProvider.java:27)
        at org.keycloak.events.EventBuilder.sendNow(EventBuilder.java:257)
        at org.keycloak.events.EventBuilder.lambda$send$1(EventBuilder.java:241)
        at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:256)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:269)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
        at org.keycloak.events.EventBuilder.send(EventBuilder.java:237)
```

**Comment by mposolda** [comment]
@ValentinLorand Thanks! From the stacktrace, it can be seen that there is a call to `getUserById` for lookup user. However in your example provider source code, which is attached in the description of this GH issue, there is not any call to `getUserById` . So it seems that something is missing from this source. Is it possible that you update your provider source code to reflect of what's going on in your environment?

**Comment by ValentinLorand** [comment]
Sorry I tried to simplify my implementation for time saving. I just updated the source

Indeed, the error of the stacktrace is raised from the line : 
`MyUserModelAdapter myUserModelAdapter = (MyUserModelAdapter) this.getKeycloakSession().users().getUserById(keycloakSession.getContext().getRealm(), event.getUserId());`

The root cause seems to be the same : keycloakSession.getContext().getRealm() -> null

**Comment by mposolda** [comment]
@ValentinLorand Thanks!

This might be a regression, so preliminary adding to Keycloak 22 to doublecheck and eventually fix this.

**Comment by pedroigor** [comment]
@mposolda @ValentinLorand Should be related to this change https://github.com/keycloak/keycloak/pull/19488/files#diff-6c641fd553097eb7d3a340bc4d676ff2c435bac772f3d57e343665c4bf867b6eR237.

A new session is created and the context is not set with the realm.

It should be a trivial fix.

**Comment by xgp** [comment]
Without patching, are you aware of a workaround in KC21 that can be used to get the Realm out of the session/context @pedroigor ?

**Comment by pedroigor** [comment]
@xgp You can try to see if the event holds the realm id or if it holds information about the user so that you can infer the realm.

The latter might require looping through your realms a not so nice implementation.

**Comment by xgp** [comment]
@pedroigor Thanks. I'll try that, but it might require some rework, as I'm trying to get the realm out of the session in the `create` method in the factory, before the event handler methods get called.
