### ISSUE TITLE
Operator: Improve ingress

### ISSUE THREAD

**Issue by DjVinnii** [keycloak/keycloak#20117]
### Description

I tried to deploy Keycloak by using the Kubernetes operator. During this, I noticed there is a lack of configuration for the ingress. The Keycloak operator could be improved by adding more ingress configuration possibilities, such as `ingressClassName` and additional annotations/labels.

### Motivation

A user should be able to configure the ingress if there is no default ingress or there are multiple ingresses available in a Kubernetes cluster.

**Comment by shawkins** [comment]
Marking as resolved based upon additional support and the other existing issues.
