### ISSUE TITLE
Role mapping tab no longer visible when using fine grained permissions after upgrade from 20.0.3 to 21.0.2

### ISSUE THREAD

**Issue by robvdlv** [keycloak/keycloak#20125]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We have been using fine grained permissions with Keycloak [20.0.3](https://github.com/keycloak/keycloak/releases/tag/20.0.3).

A user using fine grained permissions was able to view the `Role mapping` tab when navigating a `Group` found in `Groups` in the admin UI.

![image](https://user-images.githubusercontent.com/171731/235934840-3c20aada-dfa4-4988-b42a-85c370eb6195.png)

The issue: this tab "disappeared" after upgrading Keycloak to version [21.0.2](https://github.com/keycloak/keycloak/releases/tag/21.0.2).

![image](https://user-images.githubusercontent.com/171731/235935150-c816e64f-bc51-457f-951c-80d57f55282c.png)

Note:
* No Keycloak configuration or permissions changes had been made meanwhile
* We also tested to see whether upgrading to version [21.1.1](https://github.com/keycloak/keycloak/releases/tag/21.1.1) would resolve it, which it unfortunately did not

### Version

21.0.2

### Expected behavior

A user using fine grained permissions should be able to view the `Role mapping` tab when navigating a `Group` found in `Groups` in the admin UI.

![image](https://user-images.githubusercontent.com/171731/235934840-3c20aada-dfa4-4988-b42a-85c370eb6195.png)

### Actual behavior

A user using fine grained permissions is unable to view the `Role mapping` tab when navigating a `Group` found in `Groups` in the admin UI.

This tab "disappeared" after upgrading Keycloak to version [21.0.2](https://github.com/keycloak/keycloak/releases/tag/21.0.2).

### How to Reproduce?

- in a Keycloak instance version `20.0.3`
- setup basic fine grained permissions for a specific user with a groups "manage" role linked to a policy granting that specific user these permissions
- verify that the user is able to see for a group in groups, the `Role mapping` tab
- upgrade the Keycloak instance to version `21.0.2`

expected:
- the user is able to see for a group in groups, the `Role mapping` tab 

actual:
- the user does not longer see the `Role mapping` tab

**Comment by ssilvert** [comment]
From looking at the code, I can't find where we have changed the logic for hiding that tab.  Right now it requires that you have the "manage-users" role, which may be too restrictive.

@robvdlv What role mappings and fine-grained authorization does your user have?

**Comment by thesoftwarebrewery** [comment]
Hey @ssilvert,

We did another round of testing where we used a fresh `20.0.3` Keycloak instance and can confirm that indeed the "manage-users" role DOES provide the ability to view the group role mappings.

For some reason we mistakenly we're convinced that it would it work with the finegrained `manage` permission without that role. Sorry for the inconvenience, this does not seem to be a bug.

We do not want to assign manage-users as that is to broad a permission in our eyes.

What is your stance that on providing a fine grained group permission, that enables a user to map roles for a specific group? (as a possible feature request)

**Comment by ssilvert** [comment]
@thesoftwarebrewery I think it's a reasonable request.  I'm going to leave this open but change from bug to enhancement.

**Comment by robvdlv** [comment]
@ssilvert thank you for the open minded attitude, it's appreciated. 

Understood that there's no hard promises on the 'when'; good to hear its on the radar.

**Comment by cheqmate** [comment]
Is there a plan to fix this? I contend it is a bug rather than an enhancement. Users with view access cannot see the role mappings tab in groups nor users 

![Screen Shot 2023-07-20 at 11 07 09 AM](https://github.com/keycloak/keycloak/assets/5148462/c47057ec-db8f-4faf-b684-e2de0f7683d6)

**Comment by sschu** [comment]
I can confirm that the tab is only visible if the the map-role permission for the user is present. I am not sure, this is intended.

**Comment by SalemWafi** [comment]
@sschu
I got a similar issue #25054, for read-only users due to that line of code you linked.

I'm also in favor of changing it to be `isHidden={!user.access?.view}` and having the buttons inside that tab page that are responsible for assigning and unassigning roles to have `isHidden={!user.access?.mapRoles}` (which is linked to the "manage-users" role).

**Comment by ssilvert** [comment]
I would like to get to this soon, but it can't have the `priority/important` label as fine-grained is still tech preview.  So this is a bit lower priority.

**Comment by jonkoops** [comment]
@sschu a PR is always appreciated, I can help you with any tests that might need to be changed/written.

**Comment by SalemWafi** [comment]
@jonkoops and @sschu 
Could you please help with the tests needed for the linked PR? Feel free to commit to it!

**Comment by jonkoops** [comment]
@SalemWafi could you l[ink this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to the PR?

**Comment by SalemWafi** [comment]
@jonkoops Done!

**Comment by robvdlv** [comment]
Much ❤️  for addressing this. Thank you.
