### ISSUE TITLE
Still login with an account removed from postgresql database on security admin console

### ISSUE THREAD

**Issue by bdoublet91** [keycloak/keycloak#20127]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

I wanted to reset the admin password of realm master to test a lost password scenario so I found on differents topics/issues that I have to delete users of realm master in order to restart keycloak with kc.sh which will recreate admin account with admin-user and admin-password args.

So I have deleted all accounts on real master

```
select * from realm where name='master';
2aa8277e-210f-4a30-a2ff-2950b86dd46d |                   60 |                  300 |                    60 |               |             |             | t       | f              |                 0 |             | master  |          0 |                 | f                    | f           | f                      | f      | EXTERNAL     |             1800 |            36000 | f                           | f            | 66617b66-daf5-4e8a-a6de-0d6670160f23 |           1800 | f                            |                | f                     | f                    | f                            | f                     |                  0 |                 1 |                30 |                 6 | HmacSHA1       | totp            | 89e8ae35-0d8f-400c-bdcc-c325e1f27aac | 8f427de6-b289-4b67-81ce-9380803deae9 | 1ada323f-d1a3-46b1-b21a-a462383066a5 | 60897a65-6181-4ae8-8741-278c4228bcff | 092a5494-0eb0-4c35-be16-fae0f1a5dd9b |                      2592000 | f                    |                        900 | t                        | f                        | ee7b8aa7-0be7-4726-8e36-837447d6abb4 |                       0 | f                         |                            0 |                            0 | 6fd69f2c-5089-4cd7-b99e-4524b9c00c91

select * from user_entity where realm_id='2aa8277e-210f-4a30-a2ff-2950b86dd46d';
delete from credential where user_id = '****';
delete from user_role_mapping where user_id = '****';
delete from user_entity where id = '****';

select * from user_entity where realm_id='2aa8277e-210f-4a30-a2ff-2950b86dd46d';
 id | email | email_constraint | email_verified | enabled | federation_link | first_name | last_name | realm_id | username | created_timestamp | service_account_client_link | not_before 
----+-------+------------------+----------------+---------+-----------------+------------+-----------+----------+----------+-------------------+-----------------------------+------------
(0 rows)
```

First, I stay signed in with admin account of realm master in keycloak security console
I decide to logout and login again, it worked...

I need to restart my keycloak cluster (on docker swarm) to apply the change and get disconneted from admin security console.

Also Is there another solution to update or add another admin account if I have lost the admin account ? I try kcadm but I need to be authent to do modification ...

Thanks

### Version

20.0.3

### Expected behavior

When I remove the account from postgresql BDD, keycloak logout all the active session from this account

### Actual behavior

Keep signed in after account removal

### How to Reproduce?

Install keycloak with admin account
Sign in to admin console with admin account
Connect to postgresql database, remove the admin account
Reload keycloak admin console

**Comment by sschu** [comment]
Keycloak uses an in-memory cache to cache data from the database and also all session data is only stored in memory. Therefore, deleting data directly in the database won't be noticed by Keycloak and won't have an effect on active sessions. This is basically by design so I don't consider this a bug.

**Comment by bdoublet91** [comment]
OK and  when you administrate your application's users and you revoke some users accounts, will you have to restart keycloak after each acccount deletion to be sure that there is no cache so the old user couldn't login again ?

**Comment by sschu** [comment]
No, you just have to delete users directly in Keycloak, not in the database.

**Comment by jonkoops** [comment]
This can be accomplished by using the Admin REST API to delete users, since this is working as designed I am closing this issue.
