### ISSUE TITLE
role filter has no effect on roles list

### ISSUE THREAD

**Issue by indiealexh** [keycloak/keycloak#20140]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When in the admin console and trying to add role to a group (functions correctly for a composite role)
![image](https://user-images.githubusercontent.com/1066212/236062731-e1020847-98b6-49e3-b80a-0dc24ade0ccc.png)

If you add a filter at the top of the box and click the -> button, the list reloads but in the same order without being filtered

![image](https://user-images.githubusercontent.com/1066212/236062888-9845ab31-2ef1-4ef1-aad6-c0d0d30ff6f3.png)

### Version

21.1.0

### Expected behavior

The expected behavior is to be filtered and display only the list of matching items (See image of composite role):
![image](https://user-images.githubusercontent.com/1066212/236063005-831a8c1a-c406-4c7a-b4d7-e09cedd69148.png)

### Actual behavior

The list of roles is not filtered in the assign role to a group modal

### How to Reproduce?

Try to filter the list of roles in the assign roles to a group modal

**Comment by tirth1** [comment]
Hello @indiealexh, I am not able to replicate the issue in the latest version. Did you check if the same issue is occurring for the latest version or not?

**Comment by indiealexh** [comment]
> Hello @indiealexh, I am not able to replicate the issue in the latest version. Did you check if the same issue is occurring for the latest version or not?

I checked the latest version available as an openshift operator.

I can try latest locally in addition to verify.

**Comment by ssilvert** [comment]
I do see this in the latest nightly.  Search works fine when filtering by client, but not when filtering by realm roles.

**Comment by edewit** [comment]
fixed by #20142
