### ISSUE TITLE
Can't reach the server (when getting started with JDK). / No files present for Getting Started with JDK.

### ISSUE THREAD

**Issue by sourav234698** [keycloak/keycloak#20168]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

VERSION 21.1.1
I'm unable to connect to the server. The website crashes when I try to open it while following the steps for getting started with JDK. I have successfully created the username, realm, and client, but when I attempt to sign in, the site crashes and I cannot establish a connection to the server.

### Version

VERSION 21.1.1

### Expected behavior

it's expected to run and add credentials of the user realm and the client to go to further process.

### Actual behavior

I'm unable to connect to the server. The website crashes when I try to open it while following the steps for getting started with JDK. I have successfully created the username, realm, and client, but when I attempt to sign in, the site crashes and I cannot establish a connection to the server.

### How to Reproduce?

we can update Admin-User / Java side with the proper code to run it without crashing.
<img width="1107" alt="Screenshot 2023-05-05 at 1 07 21 AM" src="https://user-images.githubusercontent.com/65505067/236311845-7947dcb2-5a80-4349-b019-6b18f9b46e3e.png">

### Anything else?

Here's the link where it's crashing https://www.keycloak.org/getting-started/getting-started-zip
and I have checked the keyCloak files I think there are no files related to getting started with JDK.
I found it with Kube, docker, open shift, podman. but for JDK I didn't find it.

**Comment by abstractj** [comment]
@sourav234698 could you please try the command below?

```
bin/kc.sh start-dev --http-port 8180 --https-port=8443
```

I was able to access the admin console following all the steps, the only difference is the exposure of the HTTP port. Probably this is something that we need to update our docs.

**Comment by sourav234698** [comment]
Nah ! Not working I think files are not present for JDK.

**Comment by abstractj** [comment]
@sourav234698 could you please be more specific? Which files?

**Comment by sourav234698** [comment]
I think not sure but files for getting started with JDK are not present in KeyCloaks.
