### ISSUE TITLE
keycloak.v2 account theme breaks account login with http403 (if using nginx reverse proxy)

### ISSUE THREAD

**Issue by OverlordAkise** [keycloak/keycloak#20178]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Hi,

Im using Keycloak 21.1.1 , deployed on bare metal with Java11, behind an nginx proxy with a relative path of /test (full url for account login would be https://example.com/test/realms/myrealm/account/)

I recently encountered the same bug as referenced in issue #16234 

If I use the keycloak.v2 account theme then the login oidc call will return a 403.  
If I switch back to "keycloak" theme then it works again.  
This happens only on my server behind a proxy, not on my localhost test environment.

A short video about the bug in action:

https://user-images.githubusercontent.com/21167136/236415388-65b2fb40-05a0-453e-8832-cebfe9a52ade.mp4

My nginx config:

```
location /test {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Forwarded $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_pass http://localhost:8008;
}
```

keycloak.conf:

```
proxy=edge
transaction-xa-enabled=false
hostname-strict=true

http-port=8008
http-enabled=false
http-relative-path=/test
hostname-url=https://example.com/test
hostname-admin-url=https://example.com/test


db=mariadb
db-url-port=3306
db-url-host=localhost
db-url-database=<cut>
db-username=<cut>
db-password=<cut>

metrics-enabled=true
```

### Version

21.1.1

### Expected behavior

The keycloak.v2 account theme set in the realm settings should work normally in production for account login.

### Actual behavior

If I set the Account theme in realm settings to keycloak.v2 then the /realm/myrealm/account login doesn't work anymore and instead returns an 403 error.

### How to Reproduce?

Download keycloak 21.1.1, set it up behind an SSL-Terminating nginx reverse proxy and set the account theme for your new realm to keycloak.v2

I tested this on my local test machine and it works correctly if you use localhost without proxy. But if I test it on my server with an nginx reverse proxy infront of it (with a relative path of /test) then it breaks.

**Comment by ssilvert** [comment]
This sounds similar to https://github.com/keycloak/keycloak/issues/14666

Do you agree?

**Comment by OverlordAkise** [comment]
Yes it does, sorry I didn't see it earlier.
I will close mine and follow the one you mentioned.
Thanks & BR
