### ISSUE TITLE
Accessibility/authentication: critical problems

### ISSUE THREAD

**Issue by ethindp** [keycloak/keycloak#20172]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The authentication flow editor is majorly inaccessible.

### Version

21.0.2

### Expected behavior

I should be able to easily understand and modify authentication flows, steps, and sub-flows.

### Actual behavior

The authentication flow editor has significant accessibility problems that make it incredibly difficult to set up an authentication flow and then understand it.

### How to Reproduce?

Use a screen reader, go to authentication and then go to edit or create a new flow. If the flow has steps or sub-flows, try tabbing through the flow -- you won't hear what step or sub-flow your on, nor can you navigate the flow tree. If you arrow through the flow tree, you'll here information about dragging steps around, which only adds unnecessary noise, among all the other information. And you still won't really be able to understand the flow tree. If your in diagram mode, you won't be able to edit the flow tree, nor will you be able to understand it.

### Anything else?

I'm pretty sure I've posted about this before. The help descriptions for flows aren't all that helpful; I created a new flow with the "username form" step as it's first step and it completely broke the entire flow and now, I can't access my Keycloak instance. It was incredibly difficult to actually work with the flow to begin with, and it was also extremely frustrating. Please raise this to a high priority, considering how important authentication flows are to Keycloak itself, and the security of the system as a whole. An alternative option (albeit one that would be significantly more complicated) would be to represent authentication flows as scripts that one could just write and save. As it currently stands, conditions are difficult to understand (do you place them before the alternatives? In the middle? Somewhere else?), on top of the already incredibly frustrating UX for assistive technology.

**Comment by jonkoops** [comment]
Closing this issue due to lack of response, feel free to reply and we will re-open the issue.
