### ISSUE TITLE
The default realm locale is overridden by English

### ISSUE THREAD

**Issue by sharifrezvani** [keycloak/keycloak#20207]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

When I choose the default locale for a realm in the localization menu, It works fine if English is not included in the realm languages at all. However, when English is added among other languages, no matter what language I choose for the default locale (and I make sure that my settings are saved), the UI always shows English as the default language. What can I do to prevent this from happening?

### Version

21.1.1

### Expected behavior

The default locale must be what I choose from the localization menu, no matter which languages the realm is given.

### Actual behavior

The default locale is always set to English if English is included in the realm languages.

### How to Reproduce?

In the realm settings, go to the **Localization** menu and toggle **Internationalization** on. Choose multiple locales as supported locales and among them, make sure to choose English as well. Now set any locale other than English as your default locale and **Save** these settings. Then if you visit one of the clients of that realm, you'll see that English would still be the default locale.

**Comment by ssilvert** [comment]
Off hand, I don't remember the full algorithm for determining locale, but at one time we were using the browser setting as part of it.  So it may be getting English as the default locale from the browser?

What exactly is seeing the incorrect locale?  Is it the login screen?  
Why did you set this as a problem in the account UI?  I don't see that mentioned in the description.

**Comment by ssilvert** [comment]
I have to disagree here.  If the user has declared in his own browser settings that he has a preferred language then he should see that language first and foremost.  The purpose of localization is to get as close as possible to the user's preference.  The purpose of the default locale is to pick some supported language when the user's preference is unknown or unavailable.

**Comment by jonkoops** [comment]
I have to agree with @ssilvert here on this one, the best language to pick is always the one the user has indicated to be their preference.

**Comment by jonkoops** [comment]
Input is always appreciated, thanks for raising this @sharifrezvani.
