### ISSUE TITLE
Can not access realm admin Console UI upon adding frontend URL in realm settings

### ISSUE THREAD

**Issue by pramodsultane** [keycloak/keycloak#20205]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Can not access realm admin Console UI upon adding frontend URL in realm (other than master realm).

Ex. If I add frontend URL like dev-auth.xyz.com/auth in ABC realm, I can't open ABC realm admin console URL like https://xyz.com/auth/admin/ABC/console

### Version

20.0.3

### Expected behavior

After adding frontend URL in a realm, should be able to open respective realm admin console URL

### Actual behavior

Can not access realm admin Console UI upon adding frontend URL in realm.

### How to Reproduce?

Add frontend URL like dev-auth.xyz.com/auth in any realm (lets say ABC realm), then open ABC realm admin console URL like https://xyz.com/auth/admin/ABC/console

**Comment by ssilvert** [comment]
Does it look like a version of this problem?
https://github.com/keycloak/keycloak/issues/14666

**Comment by pramodsultane** [comment]
No, its a different issue while first time login. I am facing this issue
after logging in and configuring realm settings with frontend URL

Regards,
Pramod Sultane,
9823955060.

**Comment by jonkoops** [comment]
@pramodsultane could you test this on the latest version of Keycloak or preferably even the [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly)? Also, please share any logs that might be in the browser console.

**Comment by pramodsultane** [comment]
Hello @jonkoops , using latest version same issue. below is console logs sanp:

![image](https://github.com/keycloak/keycloak/assets/56796651/e31845c9-0817-4d85-85e7-5e2dc605a629)

**Comment by jonkoops** [comment]
@pramodsultane looks like you have configured your own CORS policy, is that correct? The Admin Console needs to embed an iframe into the page so it can check if the user is authenticated in the background.

**Comment by pramodsultane** [comment]
yes @jonkoops , we are using nginx headers in k8s ingress like:

"Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self' {frontend URL}; frame-ancestors 'self' https://{hostname}; object-src 'none' "

**Comment by sschu** [comment]
Wouldn't you have to go to `https://dev-auth.xyz.com/auth/admin/ABC/console` if you set this as a frontend url or am I missing something here?

**Comment by jonkoops** [comment]
I am closing this issue since it has to do with a user-defined CORS policy. We recommend not changing the default CORS headers that Keycloak provides (at least for the UIs like the Admin and Account Console), as they might not be compatible with stricter policies.

**Comment by pramodsultane** [comment]
Hello @jonkoops , I have tried same using local keycloak built on docker. went through same steps and same result - Can not access realm admin Console UI upon adding frontend URL in realm setting

**Comment by jonkoops** [comment]
@pramodsultane if you have a reproducible example for this let us know and I will re-open the issue.

**Comment by pramodsultane** [comment]
Hello again @jonkoops , I have run keycloak on k8s without CORS policy and tried setting frontend URL but no luck !... getting same thing: realm admin console keeps spinning infinitely...

**Comment by jonkoops** [comment]
The exception must be different then, are you seeing anything informative in the browser console?

**Comment by pramodsultane** [comment]
@jonkoops , I got solution.. thanks

**Comment by the-nap** [comment]
@pramodsultane can you share how you got the solution? I am in the same position

**Comment by pramodsultane** [comment]
@the-nap I got no solution on this problem, and indeed there was no blocker for me now as I can make all things from the master relam or with API.

**Comment by the-nap** [comment]
@pramodsultane thanks for replying, I found a solution by accessing keycloak database, as mentioned in #20868
