### ISSUE TITLE
Cannot retrieve initial access token if created with kcadm

### ISSUE THREAD

**Issue by Kibubu** [keycloak/keycloak#20215]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

calling `./kcadm.sh create clients-initial-access -r master -s count=5  -s expiration=60 -o` will create an initial access token but kcamd does not print the token

This issues was also mentioned [here](https://lists.jboss.org/pipermail/keycloak-user/2019-January/016977.html) and curl was suggested as a workaround.

The issue arises because `-o` triggers an additional get, but the token can only be retrieved from the initial json response:

https://github.com/keycloak/keycloak/blob/1d2a98d747372f909e330edc3e85e32de92fbfc9/integration/client-cli/admin-cli/src/main/java/org/keycloak/client/admin/cli/commands/AbstractRequestCmd.java#L385:L400 

### Version

21.1.1

### Expected behavior

return the json object like

`{"id":"4913c63e-6ed4-48cd-b1af-cd9091685494","token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmNmI3ODhmMi0yNDNiLTQ3NGQtYjY3OC00NGFlM2Y5OTExZTkifQ.eyJleHAiOjE2ODM1NTQ3MzMsImlhdCI6MTY4MzU1NDY3MywianRpIjoiNDkxM2M2M2UtNmVkNC00OGNkLWIxYWYtY2Q5MDkxNjg1NDk0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.KOnnjyy1EBa6T2HUOeG_FudrNnr8iXX2WsjKWloBDGo","timestamp":1683554673,"expiration":60,"count":1,"remainingCount":1}`

### Actual behavior

The token id gets returned

`Created new clients-initial-acces with id '4913c63e-6ed4-48cd-b1af-cd9091685494'`

### How to Reproduce?

1. `kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password $PASSWORD`
2. `kcadm.sh create clients-initial-access -r master -s count=5 -s expiration=60 -c -o`

**Comment by abstractj** [comment]
Interesting enough, when running with Keycloak 22.0.3 I get a different output:

```
$ bin/kcadm.sh create clients-initial-access -r master -s count=5 -s expiration=60 -c -o
{"error":"RESTEASY003650: No resource method found for GET, return 405 with Allow header"}
```

@vmuzikar removing the triage label, considering that we definitely have a bug here.
