### ISSUE TITLE
Use env in bash-scripts to start server

### ISSUE THREAD

**Issue by stellanalm** [keycloak/keycloak#20220]
### Description

Today it's better to start shell with discovery of where the sh-command is located by using env.

#!/usr/bin/env bash 

### Motivation

By using env it makes it more flexible to locate the shell in scripts that needs to used during execution of a script.
I use FreeBSD and bash is located in #!/usr/local/bin/bash

The scripts that are used in Keycloak uses #!/usr/bin/bash

By changing the scripts so that they start with #!/usr/bin/env bash 

Everyone should be happy?

**Comment by shawkins** [comment]
This is out of date. We have switched to the posix bin/sh instead.
