### ISSUE TITLE
OTP devices are not shown in the admin UI

### ISSUE THREAD

**Issue by rsvdl** [keycloak/keycloak#20258]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When trying to view a user's OTP devices under `/auth/admin/master/console/#/realm/users/UUID/credentials`

All configured OTP devices are hidden from the UI.

The information is available when inspecting the response of `/auth/admin/realms/realm/users/UUID/credentials`. (you can search for userLabel of the OTP device)

However, when visiting `/auth/realms/realm/account/#/security/signingin` OTP devices are visible.

### Version

Nightly / 1d2a98d

### Expected behavior

Show all configured OTP devices

### Actual behavior

No OTP devices are shown

### How to Reproduce?

To reproduce this scenario, please follow the steps below:

1. Configure a user with at least one OTP device.
2. Log in to the Keycloak Admin Console.
3. Navigate to the "Users" section and select the user that has the configured OTP device.
4. Click on the "Credentials" tab for the selected user.
5. Verify that the OTP device is not visible in the "OTP Devices" section of the UI.

**Comment by ssilvert** [comment]
@rsvdl I just tried this on the latest code in main.  Seems to be working fine.  Any ideas why yours is different?

**Comment by rsvdl** [comment]
I am not sure, but with the same database I get different results.

I have attached some screenshots to clarify the issue, the first screenshot is Keycloak 21.0.2 and the second screenshot is the latest nightly build.

![21 02](https://github.com/keycloak/keycloak/assets/13320994/a572dbf6-976a-4912-98a9-4fe757a60b5c)

![nightly-build](https://github.com/keycloak/keycloak/assets/13320994/bb4ead62-fe11-4681-ad3d-43b648c9c313)

**Comment by nberlee** [comment]
I've been looking into this issue along with my colleague @rsvdl, and I've examined the recent changes at the following link:
https://github.com/keycloak/keycloak/blame/aa77f713c48fb2f0678ffd4cc2318c1c4c400b79/js/apps/admin-ui/src/user/UserCredentials.tsx#L397

It appears that the problem might be related to !hasCredentialTypes, which in case of the screenshot is true. However, I must admit that I am not an experienced TypeScript programmer, so I might be missing something here.

**Comment by ssilvert** [comment]
@rsvdl The screen shots were very helpful.  I've recreated the problem now.

@nberlee Looks like you are exactly right about the problem on line 397.  I'll prepare a fix.

**Comment by ssilvert** [comment]
Note to self.  I was able to recreate this using the `user-password-map-arq` identity provider from quickstarts.

**Comment by rsvdl** [comment]
Thank you for fixing the issue, can you tell me when this fix will be available in the nightly build?
