### ISSUE TITLE
SSSD integration in Quarkus distribution

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#20262]
### Description

The point of this issue is to:
- Make sure that SSSD integration works with RHEL8
- Make sure that docs is up-to-date and there is automated test

### Subtasks

- #16165
- #20263
- #20265
- #20305 
- #20387

### Related issues

Once completed, we can ping people from those tasks and check with them if SSSD integration works for them with latest docs and nightly build

- #16165 
- #11728

**Comment by mposolda** [comment]
Closed as all subtasks are done

**Comment by etfeet** [comment]
Hi,

I just tried running the nightly build against the following os/java combinations:

- Rocky 8 - java-17-openjdk
- Rocky 9 - java-17-openjdk and java-19-openjdk
- Ubuntu  22.04 - openjdk 17/18/19
- Ubuntu 22.04 - Oracle java 17/20. 

With all of them the SSSD doesn't show up as federation option on the federation page. There are no log messages of any kind related to sssd. I followed the instructions from https://github.com/rmartinc/keycloak/blob/08b8f5ef845858cd8467ee191c69d31e90c2b42b/docs/documentation/server_admin/topics/user-federation/sssd.adoc

I also tried building your pr https://github.com/rmartinc/keycloak/tree/issue-16165 with the same result.


keyloak was started via
```
java -jar keycloak/lib/quarkus-run.jar start-dev
```

Using kc.sh produced the same results as well. So did using production mode.

dbus shows sssd lookups are working
```
[root@ipa-dev-r8 keycloak]# dbus-send --print-reply --system --dest=org.freedesktop.sssd.infopipe /org/freedesktop/sssd/infopipe org.freedesktop.sssd.infopipe.GetUserAttr string:test.user array:string:mail,givenname,sn,telephoneNumber
method return time=1688198320.285470 sender=:1.37 -> destination=:1.1856 serial=8 reply_serial=2
   array [
      dict entry(
         string "mail"
         variant             array [
               string "test.user@ipa-dev.localhost"
            ]
      )
      dict entry(
         string "givenname"
         variant             array [
               string "test"
            ]
      )
      dict entry(
         string "sn"
         variant             array [
               string "user"
            ]
      )
   ]
[root@ipa-dev-r8 keycloak]# dbus-send --print-reply --system --dest=org.freedesktop.sssd.infopipe /org/freedesktop/sssd/infopipe org.freedesktop.sssd.infopipe.GetUserGroups string:test.user
method return time=1688198326.833669 sender=:1.37 -> destination=:1.1859 serial=10 reply_serial=2
   array [
      string "ipausers"
      string "ipausers"
      string "admins"
   ]
```

```
[root@ipa-dev-r8 keycloak]# sssctl user-checks test.user -s keycloak
user: test.user
action: acct
service: keycloak

SSSD nss user lookup result:
 - user name: test.user
 - user id: 333600003
 - group id: 333600003
 - gecos: test user
 - home directory: /home/test.user
 - shell: /bin/sh

SSSD InfoPipe user lookup result:
 - name: test.user
 - uidNumber: 333600003
 - gidNumber: 333600003
 - gecos: test user
 - homeDirectory: /home/test.user
 - loginShell: /bin/sh
 - givenname: test
 - mail: test.user@ipa-dev.local
 - sn: user

testing pam_acct_mgmt

pam_acct_mgmt: Success

PAM Environment:
 - no env -
```

**Comment by rmartinc** [comment]
@etfeet I have just checked the nightly build and it is created with jdk-11. So the sssd code is missing. It should be created with jdk-17 to get the classes for sssd. You can compile by yourself if needed (mvn clean install -DskipTests). I will try to check if we need to change to jdk-17 in the nightly build.

For debug, you have to start with log option `--log-level=INFO,org.keycloak.federation.sssd:TRACE` and you will see what the `AvailabilityChecker` debug is saying. In your case it will complain about not being in jdk-17 although you are using it (cos it was compiled with jd-11).

**Comment by etfeet** [comment]
Thanks! That worked.

**Comment by rmartinc** [comment]
@etfeet I commented the issue about the nightly builds and there already was an issue https://github.com/keycloak-rel/keycloak-rel/issues/102 about using java 17 for releasing. It seems that the associated PR is merged now. I checked the last nightly release and it contains the correct classes for SSSD, so I think that everything is fine now.
