### ISSUE TITLE
Danger alert:Network response was not OK.

### ISSUE THREAD

**Issue by VisheshIrasus** [keycloak/keycloak#20279]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

So with the help of postman, I made a post request to

Token link : https://<domain>/realms/{{realm}}/protocol/openid-connect/token

Got the token as :
```json
{
    "access_token": "...some_token...",
    "expires_in": 60,
    "refresh_expires_in": 1800,
    "refresh_token": "...some_token...",
    "token_type": "Bearer",
    "not-before-policy": 0,
    "session_state": "...some_state...",
    "scope": "profile email"
}
```
Using the token I made a post request to:
Create User: https://<domain>/admin/realms/{{realm}}/users)
```json
{"firstName":"Sergey",
"lastName":"Kargopolov", 
"email":"boss@boss.com", 
"enabled":"true", 
"username":"boss",
   "credentials":[{"type":"password","value":"test1234","temporary":true}]
}

```
Good it was so far and got a 201 response

Then tried to login using the username and password.
I think I got log in.
But I saw that error  **Danger alert:Network response was not OK.**

Using chrometools debugger:
Found the error occurs in this function where the NetworkError is hit and the and response is `undefined`:
 
```js
export async function fetchWithError(input, init) {
```

[Link to the function](
https://github.com/keycloak/keycloak/blob/39d24bd04db4348af32391f1b251e4f49f3aa0c3/js/libs/keycloak-admin-client/src/utils/fetchWithError.ts#L14)

the input looks something like this, don't know what ate the data in between.

```
URL {origin: 'https://kk.irasus.com', protocol: 'https:', username: '', password: '', host: 'kk.irasus.com', …}
hash
: 
""
host
: 
"<domain>"
hostname
: 
"<domain>"
href
: 
"https://<domain>/admin/<realm>/console/whoami"
origin
: 
"https://<domain>"
password
: 
""
pathname
: 
"/admin/<realm>/console/whoami"
port
: 
""
protocol
: 
"https:"
search
: 
""
searchParams
: 
URLSearchParams {size: 0}
username
: 
""
[[Prototype]]
: 
URL
```
![Chrome debugger](https://github.com/keycloak/keycloak/assets/130440188/6e7aa3bd-0750-43c6-b0c6-e465bd40f120)

![Error message](https://github.com/keycloak/keycloak/assets/130440188/1fe090a1-ad65-43b0-9ccf-335d39fdfbfc)

### Version

quay.io/keycloak/keycloak:21.0.2

### Expected behavior

Should have seen the dashboard

### Actual behavior

got the error  **Danger alert:Network response was not OK.**

### How to Reproduce?

Don't know .
Probably use my docker compose :
I will share if required
My all services including are behind a reverse https nginx proxy.

**Comment by abstractj** [comment]
Thank you for taking the time to report the issue. However, we were unable to investigate the bug due to the lack of detailed steps to reproduce the problem.

We understand that it can be difficult to provide clear instructions, but without them, our team is unable to identify the issue. 

Please reopen the issue, if you're able to provide the details necessary to identify the issue.

**Comment by Teut2711** [comment]
Well, there were two reasons that I think caused the issue, one was that after you get the access token, the default time for expiry is 1 min. You need to increase it by going to the settings and changing it since it would be used to create the user. Second thing was I used the wrong link.

**Comment by VisheshIrasus** [comment]
https://lively-shadow-351432.postman.co/workspace/New-Team-Workspace~7498e13b-b90c-4868-a68b-7442fba4f527/collection/26877158-1e58e922-5b98-44c2-b181-54b5fdd4f225?action=share&creator=26877158

You need to increase the expiry time of token in keycloak. Also I think I was putting   client-id as grafana which is wrong,  client id has to be admin-cli. 
Read the following https://www.appsdeveloperblog.com/keycloak-rest-api-create-a-new-user/
