### ISSUE TITLE
PersistenceException with ConstraintViolationException in Hibernate: Duplicate Key Violation in Unique Constraint 'constraint_fb'

### ISSUE THREAD

**Issue by Mohamed-Hammada** [keycloak/keycloak#20299]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

Following the upgrade from keycloak-20.0.3 to keycloak-21.1.1, I began receiving this error message randomly on a regular basis.

```
 javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement; org.hibernate.exception.ConstraintViolationException: could not execute statement; could not execute statement; ERROR: duplicate key value violates unique constraint "constraint_fb"
  Detail: Key (id)=(123456) already exists.
```

### Version

21.1.1

### Expected behavior

This occurrence should not have happened.

### Actual behavior

Log in as usual.

### How to Reproduce?

Apologies, as it occurred randomly, I am unable to reproduce it.

**Comment by sschu** [comment]
This constraint is on the user id in the USER_ENTITY table. The ID (123456) looks really suspicious since this is not an ID Keycloak would normally generate. Did you install any custom extension or anything that might change the way IDs are generated?

**Comment by sschu** [comment]
Closing this due to lack of feedback to reproduce this.
