### ISSUE TITLE
Admin REST API - /{realm}/groups?search=xxx - returns unwanted groups

### ISSUE THREAD

**Issue by pboklashov** [keycloak/keycloak#20308]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

When searching for a group with "/{realm}/groups?search=xxx " admin REST API, it returns unwanted groups that don't satisfy search criteria.
If there is a sub-group with name that satisfy search criteria, all sibling groups will be found if those groups have children.

### Version

21.1.1

### Expected behavior

If there are the following groups:
- group1
  - group11
    - group111
  - group12
    - group121
  - group13
    - group131
  - group14
    - group141
- group2
  - group11

search by "group11" should return:
- group1
  - group11
- group2
  - group11

### Actual behavior

If there are the following groups:
- group1
  - group11
    - group111
  - group12
    - group121
  - group13
    - group131
  - group14
    - group141
- group2
  - group11

search by "group11" returns:
- group1
  - group11
    - group111
  - group12
  - group13
  - group14
- group2
  - group11

### How to Reproduce?

Start keycloak with the following command:
```
docker run --rm --name keycloak-21.1.1 -p 8080:8080 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin \
        quay.io/keycloak/keycloak:21.1.1 \
        start-dev
```

Login to keycloak admin ui and create the following group hierarchy:
- group1
  - group11
    - group111
  - group12
    - group121
  - group13
    - group131
  - group14
    - group141
- group2
  - group11

Get access token:
```
curl -s \
  -d "client_id=admin-cli" \
  -d "username=admin" \
  -d "password=admin" \
  -d "grant_type=password" \
  "http://localhost:8080/realms/master/protocol/openid-connect/token" | jq '.access_token'
```

Use access token to execute REST API: http://localhost:8080/admin/realms/master/groups?search=group11

Observe that result has groups "group12", "group13" and "group14" although it don't satisfy search criteria.

**Comment by pedro-hos** [comment]
I can take a look into this.
