### ISSUE TITLE
Require automation team review on pom.xml changes

### ISSUE THREAD

**Issue by ASzc** [keycloak/keycloak#20309]
### Description

Due to its more limited and controlled environment, the product build can easily be broken by non-testsuite POM changes, even when the Keycloak build is unaffected. Automation team oversight on those changes before they hit `main`, might help improve nightly product build reliability.

This can probably be accomplished by adding an appropriate entry to `.github/CODEOWNERS`. Since [negation is not allowed](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) in that file's pattern syntax, we might need multiple entries like:

```
pom.xml
adapters/**/pom.xml
authz/**/pom.xml
boms/**/pom.xml
common/**/pom.xml
core/**/pom.xml
crypto/**/pom.xml
dependencies/**/pom.xml
distribution/**/pom.xml
docs/**/pom.xml
federation/**/pom.xml
integration/**/pom.xml
js/**/pom.xml
misc/**/pom.xml
model/**/pom.xml
operator/**/pom.xml
quarkus/**/pom.xml
rest/**/pom.xml
saml-core/**/pom.xml
saml-core-api/**/pom.xml
server-spi/**/pom.xml
server-spi-private/**/pom.xml
services/**/pom.xml
themes/**/pom.xml
util/**/pom.xml
```

<details>
<summary>Complete list of build pom.xml files</summary>

```
adapters/oidc/adapter-core/pom.xml
adapters/oidc/installed/pom.xml
adapters/oidc/jakarta-servlet-filter/pom.xml
adapters/oidc/jaxrs-oauth-client/pom.xml
adapters/oidc/jetty/jetty9.4/pom.xml
adapters/oidc/jetty/jetty-core/pom.xml
adapters/oidc/jetty/pom.xml
adapters/oidc/js/pom.xml
adapters/oidc/pom.xml
adapters/oidc/servlet-filter/pom.xml
adapters/oidc/spring-boot2/pom.xml
adapters/oidc/spring-boot-adapter-core/pom.xml
adapters/oidc/spring-boot-container-bundle/pom.xml
adapters/oidc/spring-security/pom.xml
adapters/oidc/tomcat/pom.xml
adapters/oidc/tomcat/tomcat-core/pom.xml
adapters/oidc/tomcat/tomcat/pom.xml
adapters/oidc/undertow/pom.xml
adapters/oidc/wildfly-elytron/pom.xml
adapters/oidc/wildfly/pom.xml
adapters/oidc/wildfly/wildfly-subsystem/pom.xml
adapters/pom.xml
adapters/saml/core-public/pom.xml
adapters/saml/core/pom.xml
adapters/saml/jakarta-servlet-filter/pom.xml
adapters/saml/jetty/jetty9.4/pom.xml
adapters/saml/jetty/jetty-core/pom.xml
adapters/saml/jetty/pom.xml
adapters/saml/pom.xml
adapters/saml/servlet-filter/pom.xml
adapters/saml/tomcat/pom.xml
adapters/saml/tomcat/tomcat-core/pom.xml
adapters/saml/tomcat/tomcat/pom.xml
adapters/saml/undertow/pom.xml
adapters/saml/wildfly-elytron-jakarta/pom.xml
adapters/saml/wildfly-elytron/pom.xml
adapters/saml/wildfly/pom.xml
adapters/saml/wildfly/wildfly-jakarta-subsystem/pom.xml
adapters/saml/wildfly/wildfly-subsystem/pom.xml
adapters/spi/adapter-spi/pom.xml
adapters/spi/jakarta-servlet-adapter-spi/pom.xml
adapters/spi/jboss-adapter-core/pom.xml
adapters/spi/jetty-adapter-spi/pom.xml
adapters/spi/pom.xml
adapters/spi/servlet-adapter-spi/pom.xml
adapters/spi/tomcat-adapter-spi/pom.xml
adapters/spi/undertow-adapter-spi/pom.xml
authz/client/pom.xml
authz/policy-enforcer/pom.xml
authz/policy/common/pom.xml
authz/policy/pom.xml
authz/pom.xml
boms/adapter/pom.xml
boms/misc/pom.xml
boms/pom.xml
boms/spi/pom.xml
common/pom.xml
core/pom.xml
crypto/default/pom.xml
crypto/elytron/pom.xml
crypto/fips1402/pom.xml
crypto/pom.xml
dependencies/pom.xml
dependencies/server-all/pom.xml
dependencies/server-min/pom.xml
distribution/adapters/jetty94-adapter-zip/pom.xml
distribution/adapters/pom.xml
distribution/adapters/tomcat-adapter-zip/pom.xml
distribution/adapters/wildfly-adapter/pom.xml
distribution/feature-packs/adapter-feature-pack/pom.xml
distribution/feature-packs/pom.xml
distribution/galleon-feature-packs/pom.xml
distribution/galleon-feature-packs/saml-adapter-galleon-pack/pom.xml
distribution/licenses-common/pom.xml
distribution/maven-plugins/licenses-processor/pom.xml
distribution/maven-plugins/pom.xml
distribution/pom.xml
distribution/saml-adapters/jetty94-adapter-zip/pom.xml
distribution/saml-adapters/pom.xml
distribution/saml-adapters/tomcat-adapter-zip/pom.xml
distribution/saml-adapters/wildfly-adapter/pom.xml
distribution/saml-adapters/wildfly-adapter/wildfly-adapter-zip/pom.xml
distribution/saml-adapters/wildfly-adapter/wildfly-jakarta-modules/pom.xml
distribution/saml-adapters/wildfly-adapter/wildfly-modules/pom.xml
docs/guides/pom.xml
docs/maven-plugin/pom.xml
docs/pom.xml
federation/kerberos/pom.xml
federation/ldap/pom.xml
federation/pom.xml
federation/sssd/pom.xml
integration/admin-client-jee/pom.xml
integration/admin-client/pom.xml
integration/client-cli/admin-cli/pom.xml
integration/client-cli/client-cli-dist/pom.xml
integration/client-cli/client-registration-cli/pom.xml
integration/client-cli/pom.xml
integration/client-registration/pom.xml
integration/pom.xml
js/apps/account-ui/pom.xml
js/apps/admin-ui/pom.xml
js/libs/keycloak-admin-client/pom.xml
js/libs/keycloak-js/pom.xml
js/pom.xml
misc/keycloak-test-helper/pom.xml
misc/pom.xml
misc/spring-boot-starter/keycloak-spring-boot-starter/pom.xml
misc/spring-boot-starter/pom.xml
model/build-processor/pom.xml
model/infinispan/pom.xml
model/jpa/pom.xml
model/legacy-private/pom.xml
model/legacy-services/pom.xml
model/legacy/pom.xml
model/map-file/pom.xml
model/map-hot-rod/pom.xml
model/map-jpa/pom.xml
model/map-ldap/pom.xml
model/map/pom.xml
model/pom.xml
operator/pom.xml
pom.xml
quarkus/config-api/pom.xml
quarkus/deployment/pom.xml
quarkus/dist/pom.xml
quarkus/pom.xml
quarkus/runtime/pom.xml
quarkus/server/pom.xml
quarkus/tests/integration/pom.xml
quarkus/tests/junit5/pom.xml
quarkus/tests/pom.xml
rest/admin-ui-ext/pom.xml
rest/pom.xml
saml-core-api/pom.xml
saml-core/pom.xml
server-spi-private/pom.xml
server-spi/pom.xml
services/pom.xml
themes/pom.xml
util/embedded-ldap/pom.xml
util/pom.xml
```
</details>

**Comment by vmuzikar** [comment]
Do you also need test related POMs covered? E.g.
```
./quarkus/tests/integration/pom.xml
./quarkus/tests/junit5/pom.xml
./quarkus/tests/pom.xml
```

**Comment by vmuzikar** [comment]
@ASzc I can see possibly more non relevant POMs:
```
./docs/documentation/tests/pom.xml
./misc/keycloak-test-helper/pom.xml
```

**Comment by vmuzikar** [comment]
Given the large number of identified POMs, how often they change and the limited capacity of the Automation team (should they really review each and every PR touching those POMs), I was wondering if we might possibly create some guidelines that would help us identify the cases when a review from Automation team is required. WDYT?

**Comment by ASzc** [comment]
@vmuzikar  I started thinking of what is relevant when a build pom is changed, but quickly that became thinking of what is not relevant. Most changes that can be made to a pom can impact the product build. The best guidelines I can express would be "non-trivial changes to a pom that is part of the normal server build", which is basically what CODEOWNERS would do here.

Testsuite poms are not part of the normal build, but regarding the couple you posted in your last comment, `misc/keycloak-test-helper/pom.xml` is part of the build (part of the default `<modules>` tree), and `docs/documentation/tests/pom.xml` is not (only enabled by profile). I also went back and checked `quarkus/tests/junit5/pom.xml`, and it is part of the default build.

Potentially we'd want to clean up these edge cases as part of the PR that enables review for the poms. They might be enabled by default due to an oversight.

**Comment by ASzc** [comment]
I'm working on a more intelligent method of generating the pom list, so we know for sure what's part of the build and isn't.

A thought on workload: I am also concerned about taking on more work than the two of us can handle. The situation as it is now isn't ideal however. For example, this PNPM change, commit 2a18bcb2, if I had reviewed that I could have immediately pointed out it would break the product build. The fix for that is proving moderately difficult, and it could have been the upstream developer's job to figure that out, but now it's my job.

**Comment by ssilvert** [comment]
Even though more required reviewers tends to slow things down, I'm OK with giving this a try.  It might even be helpful for the rest of us to learn more about how the product build works.

If it does start to slow things down for trivial pom changes, I guess that's what maintainer overrides are for.

**Comment by ASzc** [comment]
I'm happy to do any more legwork to make this happen

**Comment by stianst** [comment]
With the automation team being the size it is I don't think requiring review for all POM changes will be feasible. We should rather look at automation as a resolution here, and I doubt we want to do any tests on a PR basis. Rather I'd say we should focus on identifying and quickly resolving any issues with nightly builds.

**Comment by ASzc** [comment]
The nightly build is catching a lot of the problems, as is was at the time this issue was created. The point of this issue here is to avoid unnecessary nightly build failures by making automation team proactively involved in the Keycloak project. Human review also has the benefit of catching some subtle release-time issues that the nightly builds can't.

Some stats to help inform our decision: of 262 commits to main since 2022, 189 of them (72%) touched a relevant pom file in some way. That's honestly higher than I thought, but works out to between 2 and 4 commits per workweek.

```
$ git log --date=iso-strict --format="> %h %ad" --name-only -p '*/pom.xml' | grep -v -e '^testsuite/' -e 'examples/' -e 'quarkus/tests/' | sed ':a;N;/\n> /!s/\n/ /;ta;P;D' | grep -v ' $' | grep -e '2023-' -e '2024-' | wc -l
189
$ git log --date=iso-strict --format="> %h %ad" --name-only -p '*/pom.xml' | grep '^> ' | grep -e '2023-' -e '2024-' | wc -l
262
```

I glanced through the filtered commits, and most of the changes are pretty trivial, and would be approved after looking at them for 10 seconds. The time sink there is someone from the automation team has to load up the page and press the approve button.

While this issue has been open, I have been receiving more requests for review on important POM changes, and that's been beneficial for everyone. However, since it's up to the author to think to contact me, I've also noticed some changes slip in that I'd rather not have landed in main. If this oversight had existed a few years ago, a lot of the really difficult issues that have surfaced for the automation team (e.g. struggling to publish the API docs when they're so thoroughly disabled in maven) could have been avoided.

I thought a compromise might be to have CODEOWNERS set only on the especially important pom files, like the root pom, the operator pom, maybe some of the top-level quarkus poms. However that barely reduces the commit count at all, so the potential lag from the approvals wouldn't be mitigated

**Comment by ssilvert** [comment]
@ASzc Do you have any objections to closing this?

**Comment by ASzc** [comment]
I still think it's a valid request, but if the team doesn't wish to implement it I can't override that

**Comment by stianst** [comment]
There is simple too many updates to `pom.xml` files to require review by two people. This will be a bottleneck for sure.

We'll need to come up with something different to solve this problem. Might just be down to nightly builds/tests, and educating maintainers.

**Comment by ASzc** [comment]
Nightly builds are being utilized to their full extent. Education maybe will make a difference, but I continue to believe this proposal was our best hope for real change in this area.
