### ISSUE TITLE
When choosing resources in scope-based permission, multiple resource can be selected but only one will be visable

### ISSUE THREAD

**Issue by kopecmaciej** [keycloak/keycloak#20304]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

In the Admin-UI in the Authorization panel I've tried to create a scope-base permission with multiple resources, but the dropdown is designed to select only one (although the field is named the same as in the resource-base permission: "Resources"), but if you still click on multiple resources they are added even though only one is visible 

### Version

21.1.0

### Expected behavior

This is example after I've removed the `variant` from `ResourcesPolicySelect` (which default value is `typeaheadMulti`)
`variant={
                    permissionType === "scope"
                      ? SelectVariant.typeahead
                      : SelectVariant.typeaheadMulti
                  }`
from here:
https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/clients/authorization/PermissionDetails.tsx#L314
![Screenshot from 2023-05-11 10-21-16](https://github.com/keycloak/keycloak/assets/88329364/f48a9f38-670e-40c7-82d3-20a6dcf2cdb1)

I don't know if this could be the fix here or the  `SelectVariant.typeahead` should be modified. 

### Actual behavior

As it can be seen below, after adding multiple resources, only one is visible in the UI, but more are saved and it's hard to manage them from the UI.
![Screenshot from 2023-05-11 10-24-05](https://github.com/keycloak/keycloak/assets/88329364/be53981c-9f73-4223-8883-7d8e03c5ce7d)
![Screenshot from 2023-05-11 10-21-57](https://github.com/keycloak/keycloak/assets/88329364/a099026d-2bf3-44b5-9e0e-5db2aa27cd9b)

### How to Reproduce?

Create scope-base permission with multiple resources

**Comment by ssilvert** [comment]
I have reproduced this.  Weird thing for me is that the `Authorization scopes` field is also acting strange.  It becomes blank after saving.

**Comment by GreenEyedAndy** [comment]
I'm using 22.0.1 now and I still can't select more than one resource.
Also I have the same problem as @ssilvert and the Authorization Scope is blank after making a change in the resource.

**Comment by jonkoops** [comment]
If you are still experiencing issues, please open a new issue so we can triage it.

**Comment by ssilvert** [comment]
I'm just going to reopen this.  I have verified that the original problem(s) is not fixed.

**Comment by edewit** [comment]
Yes this is an issue in v2 and in v3, because it uses the firstName and lastName from the token and that doesn't get updated
