### ISSUE TITLE
 message bundles are not  included in the realm export

### ISSUE THREAD

**Issue by tuxmaster5000** [keycloak/keycloak#20343]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

When exporting and importing an realm, the created message bundles are not take one to the new realm.

### Version

21.1.1

### Expected behavior

That the message bundles are also an part of the export/import.

### Actual behavior

After the import the bundles are missing.

### How to Reproduce?

1. create an realm
2. add message bundles
3. export the realm
4. On an second instance import the json file from the export.

**Comment by PavanButke** [comment]
hi @tuxmaster5000  , I'm new to this project. Request if you can assign me this bug.

**Comment by hmlnarik** [comment]
@PavanButke Process-wise, there is no need to assign this bug to you. Feel free to submit a PR, and Keycloak team will be happy to review it.

**Comment by ahus1** [comment]
PR created, notifying the community if someone want to help reviewing it: #21347
