### ISSUE TITLE
Build fails with missing "react-tokens-4.94.6.tgz" 

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20352]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/javascript

### Describe the bug

Recent builds fail, possibly due to a NPM package no longer available in the NPM registry, see https://github.com/keycloak/keycloak/actions/runs/4978897464/jobs/8909804741

ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@patternfly/react-tokens/-/react-tokens-4.94.6.tgz: Not Found - 404

### Version

main

### Expected behavior

Main branch should build

### Actual behavior

Build fails

### How to Reproduce?

run `mvn clean install -DskipTests`

**Comment by llllvvuu** [comment]
npm outage currently:

https://status.npmjs.org/incidents/drj38qn6qm59
https://github.com/search?q=+npm+ERR%21+404&type=issues&s=created&o=desc

**Comment by ahus1** [comment]
Just tried again, it is now working again, apparently at least that part of the problem was resolve. 
Closing the issue.
