### ISSUE TITLE
"Cannot deserialize value of type java.util.ArrayList<java.lang.String> from Object value" in execute-actions-email

### ISSUE THREAD

**Issue by jackprg** [keycloak/keycloak#20367]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

Hi,
when I try to run the execute-actions-email endpoint, passing the json correctly, the following error occurs in the keycloak.

End-point: http://srvkeycloak:8080/admin/realms/xpto/users/d6d0dc4a-d679-4549-b96e-48f168e390a2/execute-actions-email

{
	"id":"d6d0dc4a-d679-4549-b96e-48f168e390a2",
	"realm":"xpto",
	"lifespan":300,
	"client_id": "xpto",
	"client_secret": "DqSLZlW04GJ14LzZhDL0EJcwzpPkBNmV",
	"actions": [
		"VERIFY_EMAIL"
	]
}

![image](https://github.com/keycloak/keycloak/assets/11577916/01cd79bd-1c30-4da9-83ee-31c832e210ed)

### Version

20 ou 21

### Expected behavior

email sending

### Actual behavior

{
	"error": "unknown_error"
}

### How to Reproduce?

try to consume the execute-actions-email endpoint passing any action

**Comment by jsorah** [comment]
Hi there, seems the payload you're sending is a bit off from what is expected - see https://www.keycloak.org/docs-api/21.1.1/rest-api/index.html#_executeactionsemail

You must send a JSON array in the body containing the actions in the form as

```
[
    "VERIFY_EMAIL"
]
```

and the remainder of items should be path or query variables.

Your example URL should be something like

```
http://srvkeycloak:8080/admin/realms/xpto/users/d6d0dc4a-d679-4549-b96e-48f168e390a2/execute-actions-email?client_id=xpto&lifespan=300
```

Assuming of course the following:

realm = xpto
user ID = d6d0dc4a-d679-4549-b96e-48f168e390a2
client_id = xpto
lifespan = 300

**Comment by jsorah** [comment]
Thanks for the report - given the fact that the issue is coming from an improperly formatted request the error you see is expected. Once you correct your request as I mentioned previously it should work without error.
