### ISSUE TITLE
Double form submit in Admin UI possible leading to error mesages

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20371]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When pressing the save button multiple times "double clicking", or if the response takes a longer time, the UI will submit the form contents again. 

This leads to submitting the same information again. When this is a create request, the second create will fail when there is for example as with clients a unique key on the clientId. 

This leads to error like the following: 

![image](https://github.com/keycloak/keycloak/assets/3957921/55af6409-e936-4382-b12e-5f1b81eb5a86)

### Version

999-SNAPSHOT

### Expected behavior

Submitting a form should be possible only once when a second submission would lead to an error. If the submission is processing, the "Save" button might change its color, show a spinner or something similar. 

In general, it might be good to have a feedback on all forms that it is currently processing. Other applications add a "glass pane" and editing form contents is not possible while the submission is in progress. 

### Actual behavior

* The form can be submitted multiple times, and all except the first one lead to an error.
* The form data can be changed after the data has been submitted and before the response is being returned.

### How to Reproduce?

* In the developer tool, switch to "Slow 3G throttling"
* Create a new client. On the "Save" button, click "Save" multiple times before the next page appears
* Watch different toast message appear; one in green, others in red.

**Comment by ahanamallik1** [comment]
@ssilvert @jonkoops @ahus1 
I am trying to fix it. 
Is it needed to assign the ticket to myself ?

**Comment by ahus1** [comment]
Thank you for offering your help. No need to assign the ticket - leaving a comment here is just enough.

**Comment by ahanamallik1** [comment]
Thank you @ahus1
