### ISSUE TITLE
Deleting a client scope in the Admin UI should redirect to the list of ClientScopes

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20370]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When deleting a client scope in the Admin UI from the client scope details view, the browser doesn't return to the list of client scopes. 
Instead, it stays on that page which indicates that the client scope hasn't been deleted as expected. Deleting it again produces an error message as the client scope has already been deleted. 

The behavior works as expected with other entities like for example clients

### Version

999-SNAPSHOT

### Expected behavior

When deleting a client scope in the details view should show the list of remaining client scopes in the browser once the action succeeds.

### Actual behavior

When deleting a client scope in the details view with the action on the upper right corner, the client details remain open. Trying to delete it again produces an error message as the client scope has already been deleted. 

### How to Reproduce?

* Open the admin console
* Choose client scopes
* Create a new client scope. This will open the details of the newly created client scope
* Choose the Action *Delete* in the upper right corner
* Confirm the deletion. Then the browser still shows the client scope details page and the action to delete it can be triggered again

![image](https://github.com/keycloak/keycloak/assets/3957921/aec7f420-420f-4135-9abd-4a23bd40e56d)

**Comment by stianst** [comment]
Backport to 21.1: https://github.com/keycloak/keycloak/pull/20653
