### ISSUE TITLE
Productization issue related to JNA upgrade

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#20387]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dependencies

### Describe the bug

There is some productization issue caused by JNA upgrade (Issue #20305). I am creating this issue for tracking purpose. We can close this when the producization issue is figured.

**Comment by rmartinc** [comment]
The JNA prod version 5.8.0 is empty. The jar contains no classes or native libraries. For the moment it's been decided that we are make the compilation go and wait to see if the 5.8.0 jars (or newer) are created OK later. It seems that this version was created for quarkus, so we can align with it. If we see there is no prod version we can go back to 4.5.1 which is the last JNA version made by RH that is complete.
