### ISSUE TITLE
Spring-Boot removes WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by Bambatera** [keycloak/keycloak#20432]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/spring

### Describe the bug

Since version 2.7.x Spring Security has removed the class WebSecurityConfigurerAdapter, causing compilation errors in the IDE when trying to run the project "...WebSecurityConfigurerAdapter was not found..."

I reproduced this error on Spring-Boot version 3.0.6 with Spring Security version 6.

Spring Security blog have an article about this.
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

### Version

21.1.1

### Expected behavior

No bugs when compiling the project

### Actual behavior

Compilation error stating that the class WebSecurityConfigurerAdapter was not found.

### How to Reproduce?

Implementing the configuration class as shown in the documentation.

https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter

### Anything else?

Spring Security blog: https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

Keycloak documentation: https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter

**Comment by jsorah** [comment]
Thanks for the report - given the deprecation status of many of the adapters and the priority of the Keycloak team this would likely need to be fixed via community contribution.

For more info on the adapter deprecation - https://www.keycloak.org/2023/03/adapter-deprecation-update 
In this case for the Keycloak Spring Adapters the recommended action would be to leverage the native Spring Security OAuth/OIDC functionality.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
