### ISSUE TITLE
Default Client Registration of Service Account Client does not create default mappers

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#20454]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

When creating a service account client in Keycloak ui, default mappers (Client IP Address, Client Host and Client ID) are created.
When create the same service account client( "serviceAccountsEnabled":true ), a scope without any mappers is created.

The same bug exists also for updating a client with Default Client Registration.

### Version

21.1.1

### Expected behavior

When create the same service account client( "serviceAccountsEnabled":true ), a scope with default mappers (Client IP Address, Client Host and Client ID) are created.

### Actual behavior

When create the same service account client( "serviceAccountsEnabled":true ), a scope without any mappers is created.

### How to Reproduce?

Create Service Account Client with default Client Registration

**Comment by cgeorgilakis** [comment]
The problem is due to existence of line 86 in [AbstractClientRegistrationProvide](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/AbstractClientRegistrationProvider.java). If you comment this line, mappers are creating.

**Comment by cgeorgilakis** [comment]
> I don't believe this is a UI problem, rather it seems that this default is provided by the REST API.

You are right. The problem is in default Client registration REST API.

**Comment by pedroigor** [comment]
@cgeorgilakis Not sure if I'm following your instructions to reproduce the problem.

Looking at how clients are *created* during registration, I can see the mappers being created just like when using the Admin API. However, this is not true when updating the client through the client registration API.

Is that what you mean? Is it about making sure https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/AbstractClientRegistrationProvider.java#L86 is also called when you change the `grant_types` claim to contain `client_credentials`?

**Comment by pedroigor** [comment]
@cgeorgilakis Now I see, the problem is that the protocol mappers are removed because of this policy, see https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/policy/impl/ProtocolMappersClientRegistrationPolicy.java#L76.

I'm assuming the behavior is expected as you can see here https://www.keycloak.org/docs/23.0.3/securing_apps/#_client_registration_policies. You should add those mappers to the list of allowed protocol mappers.

I'm not sure if this is an unexpected behavior or if the `oidc-usersessionmodel-note-mapper` is indeed not part of the default set of allowed protocol mappers for some reason.

@mposolda Do you know why `oidc-usersessionmodel-note-mapper` is not among the default protocol mappers allowed by the `ProtocolMappersClientRegistrationPolicy` ?

**Comment by cgeorgilakis** [comment]
> oidc-usersessionmodel-note-mapper

You are right @pedroigor. The problem is that oidc-usersessionmodel-note-mapper is not among the default protocol mappers.
Could we make it default or mentioned it in service account documentation? @mposolda ?

**Comment by cgeorgilakis** [comment]
> @cgeorgilakis Now I see, the problem is that the protocol mappers are removed because of this policy, see https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/policy/impl/ProtocolMappersClientRegistrationPolicy.java#L76.
> 
> I'm assuming the behavior is expected as you can see here https://www.keycloak.org/docs/23.0.3/securing_apps/#_client_registration_policies. You should add those mappers to the list of allowed protocol mappers.
> 
> I'm not sure if this is an unexpected behavior or if the `oidc-usersessionmodel-note-mapper` is indeed not part of the default set of allowed protocol mappers for some reason.
> 
> @mposolda Do you know why `oidc-usersessionmodel-note-mapper` is not among the default protocol mappers allowed by the `ProtocolMappersClientRegistrationPolicy` ?
> 
> For the sake of consistency, we should probably add it here https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/policy/DefaultClientRegistrationPolicies.java#L45 for the sake of consistency with the Admin API.

You are right @pedroigor. The problem is that oidc-usersessionmodel-note-mapper is not among the default protocol mappers.
Could we make it default or mentioned it in service account documentation? @mposolda ?
