### ISSUE TITLE
Changing the email address has no impact at username regardless "Email as username" toggle

### ISSUE THREAD

**Issue by speechkey** [keycloak/keycloak#20459]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

Changing the email address ha no impact at username regardless enabled `Email as username` toggle. The bug was introduces in https://github.com/keycloak/keycloak/commit/53ee95764e4bbfc0a075d7b91c872590fd376e46#diff-45cc3f2945c63a4269281feeea8d34243f7179eb761dba4d8627c34da87c648c which supposed to close https://github.com/keycloak/keycloak/issues/16263 issue.

**Working version:** `20.0.5`
**Bug since:** `21.0.0`

### Version

21.1.1

### Expected behavior

If `Email as username` toggle is enabled changing the email address by a user at `/realms/{realm}/account/#/personal-info` will cause an automatically change of the username to the new email.

### Actual behavior

Changing the email address has no impact at username regardless enabled `Email as username` toggle. After changing the email, it becomes new value, the username stays equal previous email

### How to Reproduce?

1. Start last release: `docker run --rm -p 8888:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:21.1.1 start-dev`
2. Login with `admin:admin` at http://localhost:8888/admin/master/console
3. Create new realm `test`
4. Enable all toggles at http://localhost:8888/admin/master/console/#/test/realm-settings/login and expecially `Email as username`
5. Create new user with verified email address `test@8888.com` at http://localhost:8888/admin/master/console/#/test/users/add-user and set its password.
6. Verify the new user has same email and username at http://localhost:8888/admin/master/console/#/test/users
7. Impersonate the user
8. Go to http://localhost:8888/realms/test/account/#/personal-info and change its email to `new@8888.com`
9. Go to admin console http://localhost:8888/admin/master/console/#/test/users and observe the new email `new@8888.com` but old username `test@8888.com`
10. Login in private browser window to http://localhost:8888/realms/test/account/#/personal-info with `test@8888.com` and verify the `new@8888.com` email
11. Go to admin console http://localhost:8888/admin/master/console/#/test/users and observe the new email `new@8888.com` but old username `test@8888.com`

### Anything else?

Related issue: https://github.com/keycloak/keycloak/issues/17692

**Comment by vickeybrown** [comment]
Looks to be a regression, moving to 22.0.0
