### ISSUE TITLE
Conditional OTP registration during login with LDAP read-only

### ISSUE THREAD

**Issue by mriedmann** [keycloak/keycloak#20464]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

We have tried to enable conditional OTP using a modified browser-flow. During our tries, we encountered the following error:

```
 2023-05-19 17:31:10,867 WARN  [org.keycloak.services] (executor-thread-115) KC-SERVICES0013: Failed authentication: org.keycloak.storage.ReadOnlyException: Not possible to write 'required action CONFIGURE_TOTP' when updating user '****'
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.utils.ReadOnlyUserModelDelegate.readOnlyException(ReadOnlyUserModelDelegate.java:146)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.utils.ReadOnlyUserModelDelegate.addRequiredAction(ReadOnlyUserModelDelegate.java:71)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.utils.UserModelDelegate.addRequiredAction(UserModelDelegate.java:105)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.utils.UserModelDelegate.addRequiredAction(UserModelDelegate.java:105)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.utils.UserModelDelegate.addRequiredAction(UserModelDelegate.java:105)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.utils.UserModelDelegate.addRequiredAction(UserModelDelegate.java:105)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.storage.ldap.mappers.msad.MSADUserAccountControlStorageMapper$MSADUserModelDelegate.addRequiredAction(MSADUserAccountControlStorageMapper.java:292)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.storage.adapter.UpdateOnlyChangeUserModelDelegate.addRequiredAction(UpdateOnlyChangeUserModelDelegate.java:83)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.models.cache.infinispan.UserAdapter.addRequiredAction(UserAdapter.java:240)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.authentication.authenticators.browser.ConditionalOtpFormAuthenticator.setRequiredActions(ConditionalOtpFormAuthenticator.java:328)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:429)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
May 19 19:31:10 kc-1 keycloak[106656]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:380)
...
```

Our users are ldap (read-only) backed, so we tried the same flow for identity provider and local users, and this worked flawlessly. 

### Version

21.1.1

### Expected behavior

The conditional OPT Form throws an error when a user (from read-only LDAP) has no configured OTP.

### Actual behavior

Show the user the "configure OTP" form (as it is for the normal OPT Form step, or non-readonly-ldap users)

### How to Reproduce?

- Setup Keycloak 21.1.1
- Add a read-only ldap
- Clone the browser auth-flow
- Add the conditional OTP Form flow as required step to the flow
- Try to log in using a user without configured OTP

### Anything else?

Our research brought us to the following bug report/commit from 3 year ago:

> https://github.com/keycloak/keycloak/commit/850d3e7fef2ae25719e2e0804b6ace9d774185c8
> When LDAP user federation is configured in read-only mode, it is not possible to set required actions for users from LDAP. Keycloak credential model allows for registering OTP devices when LDAP ist configured with "Import Users" flag enabled. Registering OTP devices needs to be done via the account management console and works as expecetd. However, it fails, if a user has to register aN OTP device during login (i.e. within the authentication flow), because the OTP Form Authenticator tries to enforce OTP registration via setting the corresponding required action for the user. That fails, because the user is read-only. To work around this, the required action is set on the authentication session instead.

This is the relevant, current implementation found in the "normal" OTP Form auth-step.
https://github.com/keycloak/keycloak/blob/0ca0a5fa4459d97c4d769fec15b4ba99c3824314/services/src/main/java/org/keycloak/authentication/authenticators/browser/OTPFormAuthenticator.java#L137-L142

This section is still using the "old" way, utilizing the UserModel instead of the AuthenticationSession. 
https://github.com/keycloak/keycloak/blob/25b7f1e8234577c0d8d8486e3f0272e8eac5bf8f/services/src/main/java/org/keycloak/authentication/authenticators/browser/ConditionalOtpFormAuthenticator.java#L324-L330

We think that simply changing this to the way already implemented in the other auth-steps would solve our problem.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. You are welcome to send PR for fixing this in the ConditionalOtpFormAuthenticator. See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

Just a note that ConditionalOtpFormAuthenticator has very low priority for the Keycloak team as in general, it is recommended to rather use OTPFormAuthenticator together with "Conditions" in the authentication flow instead of having the conditions logic inside the authenticator itself.

**Comment by mriedmann** [comment]
Ok thank you for the answer. As far as I know, the conditions do not support analyzing request headers right? So having conditional OTP for requests that are coming from a special load-balancing endpoint (injecting a x-no-otp header) is only possible with the ConditionalOTPForm execution, right?

(If I find time, I will provide a PR)
