### ISSUE TITLE
Look ahead window setting in OTP policy is not accurate

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#20469]
### Description

The label and description of the `Look ahead window` setting in the OTP policy are not accurate. 

This setting is actually looking *around* given that the valid time window also takes into account the past. See https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/models/utils/TimeBasedOTP.java#L80.

### Motivation

Better label and description of how the `Look ahead window` works. 

### Details

See description.

**Comment by pedroigor** [comment]
@thomasdarimont FYI

**Comment by thomasdarimont** [comment]
@pedroigor thanks for the hint. I'll take a look.

**Comment by thomasdarimont** [comment]
The code does indeed perform a lookaround but the variables and (all) translations weren't adapted.

I could could rename all relevant translation keys and adapt the english and german texts - but then the other texts would be inconsistent, how to deal with that?

**Comment by ssilvert** [comment]
@thomasdarimont The way we deal with untranslated texts is to just leave them out of the message bundle for those locales.  There is really nothing else we can do until someone comes along to provide a good translation.

**Comment by ssilvert** [comment]
@thomasdarimont Can I assign this one to you and remove it from triage?

**Comment by thomasdarimont** [comment]
@ssilvert Thanks for clarification! Should I then also change the variable names to match the actual meaning (`lookAround` vs. `lookAhead`?)

Yes, you can assign this to me.

**Comment by thomasdarimont** [comment]
@ssilvert I just sent a PR for this, I deliberately reduced the impact of this change to just internal changes and admin-ui changes. See PR description.
