### ISSUE TITLE
When user federation is enabled, admin console user search doesn't show search field

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20498]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Once I add a federation provider to the realm, the search field for users is gone in the admin UI.

### Version

nightly (used to work in 21.1.1)

### Expected behavior

When there is a user federation setup with LDAP, the search field for users should be there

![image](https://github.com/keycloak/keycloak/assets/3957921/8d5cecd0-60e5-40ed-a90f-f1e9f6470e5f)

### Actual behavior

The search field is gone: 

![image](https://github.com/keycloak/keycloak/assets/3957921/dbbb48f6-6d3c-481e-ae33-136d98e0da19)

### How to Reproduce?

1. Login to the admin console
2. Choose *User federation*
3. Choose *Add Ldap providers*
4. Choose any values that make the validation pass - like outlined in "docs/test.md" chapter "LDAP server" 
5. Go to tab *Users* -> no search field present

### Anything else?

I'm marking it KC22 milestone, as it is probably a regression which should be fixed before KC22 is released.

**Comment by ssilvert** [comment]
I have reproduced this.
