### ISSUE TITLE
Keycloak supports I18n, but the support to Romanian seems to miss

### ISSUE THREAD

**Issue by apescione** [keycloak/keycloak#20508]
### Description

I cannot see Romanian support in Keycloak, locale ro_RO.
Is there somewhere it can be downloaded?
In case, it doesn't exist, where can I find out all files to translate from English?
In the case of my translation, how can I add my messages?

I'm using the latest Quarkus version.

Thanks in advance.

**Comment by sschu** [comment]
In https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources-community/theme/base there are the 4 themes for Keycloak. In each theme, there is a `messages` folder with translation files for the different languages. You would have to add files for Romanian. You might have to do some more modifications like adding the language to the `theme.properties` files.

**Comment by apescione** [comment]
Thank you very much, I'll request my team to translate and contribute to adding them to your repository.

**Comment by jcucurull** [comment]
Hello, are there any news on that? Did you finally translated the language files to Romanian?
