### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by jojo-schneider** [keycloak/keycloak#20515]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

I am using the Keycloak Admin Client in a Node Express server project. Since updating the client to 21.1.1 the calls no longer work. I get an exception "Headers is not defined" e.g. when calling `await kcAdmientClient.components.find({name: 'rsa-env'})`. Downgrading to version 21.0.2 solves the problem.

### Version

21.1.1

### Expected behavior

no exception as in version 21.0.2 

### Actual behavior

An exception is thrown. Error "Headers is not defined"

### How to Reproduce?

call `await kcAdmientClient.components.find({name: 'rsa-env'})`

**Comment by jonkoops** [comment]
What version of Node.js are you using? If you want to make use of this package the minimum Node.js version supported is 18.

**Comment by jojo-schneider** [comment]
@jonkoops Thanks for pointing this out, I wasn't aware of it. The project is currently using Node 14, upgrading to 18 causes other problems but the keycloak admin client v21.1.1 then works. 
Perhaps you should adjust the engines in the package.json accordingly. Thank you for your great work!

**Comment by jonkoops** [comment]
> The project is currently using Node 14, upgrading to 18 causes other problems but the keycloak admin client v21.1.1 then works.

Yes, I think we can be more clear about this constraint. I will create a PR to resolve this. Be aware that Node.js 14 is [currently EOL](https://nodejs.dev/en/about/releases/), so you might want to move at least version 16 soon.

**Comment by malopez16** [comment]
Having same issue here, I had opened https://github.com/keycloak/keycloak/issues/20587.

But this issue is happening on node 16 too (see steps on https://github.com/keycloak/keycloak/issues/20587 to reproduce).
My node version is 
´´´
node -v          
v16.20.0
´´´

**Comment by jonkoops** [comment]
@malopez16 Yeah, this should probably have been in the release notes. We simply forgot about it when releasing 21.
