### ISSUE TITLE
Ensure proper escaping  for LDAP

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#20510]
From #20396
[...] I used the command line to do some interactive testing using 

```
./kcadm.sh get users -q "search=Wilson"
```

The results are ok. 

Examples:

* `Wil*son` -> finds entries with wildcard in LDAP, but not in JPA, as JPA only replaces asterisks at the beginning and the end, and `*` is a natural wildcard in LDAP.
* `Wil%son` -> finds entries with wildcard in JPA, but not LDAP, as `%` is a natural wildcard in JPA
* `Wil)son` -> returns a 400 error as the LDAP doesn't properly escape braces in this search mode

Possible changes in that follow-up PR: 
* Define which wildcards would be supported in the frontend (possibly only `*`?)
* For JPA, replace all `*` with `%`, and escape all other wildcards like `_`
* For LDAP, keep all `*`, and escape all other characters

_Originally posted by @ahus1 in https://github.com/keycloak/keycloak/pull/20396#pullrequestreview-1436667356_

**Comment by ahus1** [comment]
There is now a PR #20518 which adds the escaping for LDAP when the wildcard search is used.

**Comment by ahus1** [comment]
JPA will be handled in #20610
