### ISSUE TITLE
[Declarative User Profile] Optional attributes become required

### ISSUE THREAD

**Issue by mhanysz** [keycloak/keycloak#20536]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When the declarative user profile is enabled, adding new attributes and leaving the required toggle _off_ causes the attributes to be required, when editing the user or the attribute itself afterwards.

### Version

21.1.1

### Expected behavior

Attributes created with the required toggle set to _off_ have that toggle set to off, when editing them after creation and when editing user profiles, the attributes don't have to be specified.

### Actual behavior

After creating the attribute with the required toggle set to _off_, it must be specified when editing a user and when editing the attribute itself, the setting is set to _on_.

### How to Reproduce?

1. start keycloak 21.1.1 with declarative user profiles enabled `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_FEATURES=declarative-user-profile quay.io/keycloak/keycloak:21.1.1 start-dev`
2. log in to the admin ui
3. create a new realm, go to realm settings and set "User Profile Enabled" to on
4. go to the "User Profile" tab in realm settings and create a new attribute with "Required" set to _off_

When editing the create attribute again, "Required" is set to _on_ now and when editing users, the attribute must be specified.

**Comment by ssilvert** [comment]
I see the problem.  It only happens the first time you create the attribute.  After that, when you change the `Required` setting it will get saved properly.
