### ISSUE TITLE
Hardcoded path in OAuth_Token_Request_State cookie vs. dynamically set once

### ISSUE THREAD

**Issue by mdeknowis** [keycloak/keycloak#20531]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/spring

### Describe the bug

Sometimes the OAuth_Token_Request_State cookies with different paths, so set twice and that leads  to an error respins 400 with this text message in the body "Error 400: SRVE0295E: Error reported: 400" error with the logs

```txt
2023-05-23 09:37:00.790 SessionID="" LogLevel="WARN" ThreadName="Default Executor-thread-300" ClassName="org.keycloak.adapters.OAuthRequestAuthenticator" MethodName="checkStateCookie" LineNumber="254" state parameter invalid
2023-05-23 09:37:00.790 SessionID="" LogLevel="WARN" ThreadName="Default Executor-thread-300" ClassName="org.keycloak.adapters.OAuthRequestAuthenticator" MethodName="checkStateCookie" LineNumber="255" cookie: 9fa8880e-9594-4908-8b8a-6b44e158d91a
2023-05-23 09:37:00.791 SessionID="" LogLevel="WARN" ThreadName="Default Executor-thread-300" ClassName="org.keycloak.adapters.OAuthRequestAuthenticator" MethodName="checkStateCookie" LineNumber="256" queryParam: 42dca916-ab9b-4b45-bd16-f522aae84b7d
```

It's really hard to reproduce but it occurs often enough.

I guess the root cause is, that `org.keycloak.adapters.OAuthRequestAuthenticator` defines the path hardcoded with "/"

```java
// ...
    protected AuthChallenge loginRedirect() {
// ...
                tokenStore.saveRequest();
                log.debug("Sending redirect to login page: " + redirect);
                exchange.getResponse().setStatus(302);
                exchange.getResponse().setCookie(deployment.getStateCookieName(), state, "/", null, -1, deployment.getSslRequired().isRequired(facade.getRequest().getRemoteAddr()), true);
                exchange.getResponse().setHeader("Location", redirect);
//...
```

but `org.keycloak.adapters.CookieTokenStore` defines it dynamically

```
// ...
    public static void setTokenCookie(KeycloakDeployment deployment, HttpFacade facade, RefreshableKeycloakSecurityContext session) {
// ...
        String cookiePath = getCookiePath(deployment, facade);
        facade.getResponse().setCookie(AdapterConstants.KEYCLOAK_ADAPTER_STATE_COOKIE, cookie, cookiePath, null, -1, deployment.getSslRequired().isRequired(facade.getRequest().getRemoteAddr()), true);
    }
// ...
    static String getCookiePath(KeycloakDeployment deployment, HttpFacade facade) {
        String path = deployment.getAdapterStateCookiePath() == null ? "" : deployment.getAdapterStateCookiePath().trim();
        if (path.startsWith("/")) {
            return path;
        }
        String contextPath = getContextPath(facade);
        StringBuilder cookiePath = new StringBuilder(contextPath);
        if (!contextPath.endsWith("/") && !path.isEmpty()) {
            cookiePath.append("/");
        }
        return cookiePath.append(path).toString();
    }
// ...
```

The workaround is to define in the `keycloak.json`

```json
"adapter-state-cookie-path": "/",
```

to align the hardcoded with the dynamically determined path. But I guess also `org.keycloak.adapters.OAuthRequestAuthenticator` should implement the same cookie path determination strategy as it is implemented by `org.keycloak.adapters.CookieTokenStore`

### Version

21.1.1 and 19.0.3

### Expected behavior

The cookie path of OAuth_Token_Request_State is always the same

### Actual behavior

The cookie path is sometimes (hardoced) "/" and sometimes either the keycloak.json value of "adapter-state-cookie-path" or if that configuration is not set, then the current context path

### How to Reproduce?

Hard, I didn't find a relaible way to reproduce it, but found the root cause in the code

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
