### ISSUE TITLE
Mixed http & https URLs in .well-known/openid-configuration response

### ISSUE THREAD

**Issue by franck102** [keycloak/keycloak#20549]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

With the configuration given below the endpoints advertised at `https://some-tenant.acme.io/auth/realms/master/.well-known/openid-configuration` contain a mix of https and http URLs.

token_enpoint in particular advertises an http URLs that javascript clients (oidc-client-ts in an SPA) cannot reach from browsers:

```
{
  "issuer": "https://www.acme.io/auth/realms/master",
  "authorization_endpoint": "https://www.acme.io/auth/realms/master/protocol/openid-connect/auth",
   "token_endpoint": "http://some-tenant.acme.io/auth/realms/master/protocol/openid-connect/token",**
  "introspection_endpoint": "http://some-tenant.acme.io/auth/realms/master/protocol/openid-connect/token/introspect",
  "userinfo_endpoint": "http://some-tenant.acme.io/auth/realms/master/protocol/openid-connect/userinfo",
  "end_session_endpoint": "https://www.acme.io/auth/realms/master/protocol/openid-connect/logout",
  "frontchannel_logout_session_supported": true,
  "frontchannel_logout_supported": true,
  "jwks_uri": "http://some-tenant.acme.io/auth/realms/master/protocol/openid-connect/certs",
  "check_session_iframe": "https://www.acme.io/auth/realms/master/protocol/openid-connect/login-status-iframe.html",
```

The configuration we use is below; we have tried various combinations of KC_HOSTNAME, KC_HOSTNAME_STRICT, HTTP(S)_*  without any success

```
command: ["start", "--import-realm"],
                environment: {
                    KC_PROXY: "edge",
                    KC_HTTP_ENABLED: "true",
                    KC_HOSTNAME: "www.acme.io",
                    KC_HTTP_RELATIVE_PATH: "/auth",
                    // Always use hostname above for frontend endpoints
                    KC_HOSTNAME_STRICT: "false",
                    // Resolve host from incoming request for backend endpoints since they use VPC endpoints
                    KC_HOSTNAME_STRICT_BACKCHANNEL: "false",
                    KC_HTTP_PORT: 8080,

```

### Version

quay.io/keycloak/keycloak:21.1

### Expected behavior

Basically we need Keycloak to generate back the exact HTTP origin it receives in the Forwarded header; or always https with the host from the received Host header; and doing this in proxy mode where SSL is terminated at the load balancer.

The origins for the frontend endpoints in the `.well-known/openid-configuration` response above should all be `https://some-tenant.acme.io`

Is this possible at all in the current version?

### Actual behavior

Keycloak generates a mix of http and https origins for the frontend enpoints.

### How to Reproduce?

Use the configuration above, install Keycloak behind a proxy that terminates SSL and call the configuration endpoint.

### Anything else?

`KC_HOSTNAME_URL` is not an option since we want varying hostnames based on the tenant making the request from their assigned `<tenant>.acme.io` domain.

**Comment by franck102** [comment]
My bad, I was terminating the SSL too early and the X-Forwarded headers received by Keycloak were incorrect.

Everything works as expected (oauth-wise, I didn't try the admin console yet) with those settings behind AWS CloudFront + an ALB that terminates the SSL:

```
                    KC_PROXY: "edge",
                    KC_HTTP_ENABLED: "true",
                    KC_HOSTNAME_STRICT_HTTPS: "false",
                    KC_HTTP_RELATIVE_PATH: "/auth",
                    KC_HOSTNAME_STRICT: "false",
                    // Resolve host from incoming request for backend endpoints since they use VPC endpoints
                    KC_HOSTNAME_STRICT_BACKCHANNEL: "false",
                    KC_HTTP_PORT: 8080,
```

**Comment by jakubgs** [comment]
@franck102 could you maybe elaborate on how exactly your `X-Forwarded-*` headers were wrong?

**Comment by franck102** [comment]
Ouch, this is too old for me to remember the details, but IIRC I have  keycloak behind an AWS load balancer itself behind CloudFront, and the issue had to do with where SSL is terminated.

**Comment by jakubgs** [comment]
Thanks. I believe my issues was specifically wrong `X-Forwarded-Proto: http`. Cheers.
