### ISSUE TITLE
emailVerified user attribute is not sent in SAML response

### ISSUE THREAD

**Issue by rgl** [keycloak/keycloak#20574]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

After configuring a SAML Client User Attribute Mapper for sending the emailVerified attribute, Keycloak does not actually sends it in the SAML response.

### Version

21.1.1

### Expected behavior

I expected to see the emailverified SAML attribute in the SAML response.

### Actual behavior

The SAML response is returned to the SAMP service provider, but now emailverified attribute is sent.

### How to Reproduce?

In terraform, you can create the mapping as:

```hcl
# see https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/saml_user_attribute_protocol_mapper
# see https://www.keycloak.org/docs-api/21.1.1/javadocs/org/keycloak/models/UserModel.html
# TODO https://github.com/mrparkers/terraform-provider-keycloak/issues/844
# TODO why is this not sent by keycloak in the saml response?
resource "keycloak_saml_user_attribute_protocol_mapper" "wso2is_emailverified" {
  realm_id                   = keycloak_saml_client.wso2is.realm_id
  client_id                  = keycloak_saml_client.wso2is.id
  name                       = "emailverified"
  user_attribute             = "emailVerified" # NB isEmailVerified does not work either.
  saml_attribute_name        = "emailverified"
  saml_attribute_name_format = "Basic"
}
```

This modified the following area:

![image](https://github.com/keycloak/keycloak/assets/43356/f78bc42b-7be9-4512-96f4-4444bd4be64e)

![image](https://github.com/keycloak/keycloak/assets/43356/11bbb49b-9874-447a-98f4-0753816b6960)

![image](https://github.com/keycloak/keycloak/assets/43356/90328039-ffab-4a31-823c-d9ab1b894e46)

**Comment by rmartinc** [comment]
@rgl Instead of using a `User Attribute` mapper use a `User Property` one. I think that the `isMailVeirified` is never managed as an attribute in the user. The mapper should be something like the following:

Type: User Property
Name: emailVerified
Property: emailVerified
Friendly Name: emailVerified
SAML Attribute Name: emailVerified
SAML Attribute NameFormat: Basic

That is working for me.

**Comment by rgl** [comment]
That was it! Thank You!

The terraform code was modified to use `keycloak_saml_user_property_protocol_mapper` instead of `keycloak_saml_user_attribute_protocol_mapper`:

```hcl
# see https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/saml_user_property_protocol_mapper
# see https://www.keycloak.org/docs-api/21.1.1/javadocs/org/keycloak/models/UserModel.html
resource "keycloak_saml_user_property_protocol_mapper" "wso2is_emailverified" {
  realm_id                   = keycloak_saml_client.wso2is.realm_id
  client_id                  = keycloak_saml_client.wso2is.id
  name                       = "emailverified"
  user_property              = "emailVerified"
  saml_attribute_name        = "emailverified"
  saml_attribute_name_format = "Basic"
}
```
