### ISSUE TITLE
Add back examples for Kubernetes and Openshift to the quickstarts

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#20635]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

During the refactoring of the quickstart repository, the examples for deploying Keycloak on Kubernetes and OpenShift were removed.

These examples are used by the getting started guides available from Keycloak website.

### Version

999-SNAPSHOT

### Expected behavior

Provide examples of how to deploy on Kubernetes and OpenShift.

### Actual behavior

The examples are no longer available and breaking the website.

### How to Reproduce?

N/A

**Comment by vmuzikar** [comment]
I'd argue that the [OpenShift Guide](https://www.keycloak.org/getting-started/getting-started-openshift) on KC web is superseded by Operator.
