### ISSUE TITLE
Generate Operator OLM as part of the maven build

### ISSUE THREAD

**Issue by ASzc** [keycloak/keycloak#20630]
### Description

The operator OLM YAML files are essential for a functional bundle. Currently they are generated by manually calling a custom script, `operator/scripts/create-olm-bundle.sh`, based on templates in `operator/olm-base/`. Since they are manually generated, they're not accessible to maven and any build process based around that.

Ideally these should be generated through maven, and subsequently deployed as a maven artifact of the keycloak-operator pom, probably a zip or tar archive of the files, perhaps with the classifier of `olm` to distinguish it from the archive of quarkus+operator jars already deployed.

At the same time, it probably makes sense to take advantage of the Java Operator SDK's ability to generate these files, since the SDK is already integrated into the maven build. Integrating the scripts themselves is possible, though far less portable, since CLI tools like `yq` need to be installed.

**Comment by ASzc** [comment]
@vmuzikar further to our discussion

**Comment by vmuzikar** [comment]
I believe this is a duplicate of https://github.com/keycloak/keycloak/issues/10911

**Comment by ASzc** [comment]
Closing, will add a comment over there
