### ISSUE TITLE
"Not username" and "Not email" options when creating/changing a password, should ignore letter case when comparing password to email or to username

### ISSUE THREAD

**Issue by ygoldner1** [keycloak/keycloak#20649]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When enabling the "Not username" and "not email" options for when users create/change their password, there ais a case in which certain passwords are allowed but shouldn't be.
What happens is that email and username are always saved in lower case letters, even if they were inputted in upper case letters.
As a result, if I use a password with even one upper case, it will never match either email or username.

Examples:
1. Password and email both inputted as: A@b.c will be allowed, since password will be saved as "A@b.c" and email will be saved as "a@b.c"
2. Password and username both inputted as Abcd1 will also be allowed, since password will be saved as "Abcd1" and username will be saved as "abcd1"

In my opinion, you should compare password to email and password to username, with ignore case. Meaning, the same text in 2 fields, with the only difference between them being a lower or upper case letter, should be considered as identical values.

### Version

21.1.1

### Expected behavior

"ABC" should be considered equal to "abc", when comparing password to email or username.

### Actual behavior

Currently, "Abc" is not considered equal to "abc".

### How to Reproduce?

There are many flows that can reproduce this issue: change/reset password to match the username, or create a user with email and password identical, except that the password has upper case letters.

**Comment by mposolda** [comment]
I agree that it is valid issue, but not that big priority, so I am adding to Backlog. Anyone is welcome to send the PR with fixing this.

**Comment by pedro-hos** [comment]
I can take a look at this next week.

**Comment by pedro-hos** [comment]
@mposolda just an update, I have finished that fix also. Thank you

**Comment by ygoldner1** [comment]
Hi,
Any idea when this issue is going to be fixed?

**Comment by rmartinc** [comment]
This issue was initially fixed by https://github.com/keycloak/keycloak/issues/37431. But the PR was added for the tests.
