### ISSUE TITLE
Facing issue while testing the keycloak email  

### ISSUE THREAD

**Issue by prasannavemula** [keycloak/keycloak#20650]
### Description

I am testing the email from keycloak application it sends email successfully but its sends file name as output. 
While cheking logs getting errors as 

`Caused by: org.keycloak.email.EmailException: Failed to template plain text email. at org.keycloak.keycloak-services@16.0.0//org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:226) ... 86 more Caused by: org.keycloak.theme.FreeMarkerException: Failed to process template text/executeActions.ftl at org.keycloak.keycloak-services@16.0.0//org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:71) at org.keycloak.keycloak-services@16.0.0//org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:224) ... 86 more`

`org.wildfly.extension.undertow@25.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544) at io.undertow.servlet@2.2.12.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet@2.2.12.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet@2.2.12.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.core@2.2.12.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.core@2.2.12.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990) at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: org.keycloak.email.EmailException: Failed to template plain text email. at org.keycloak.keycloak-services@16.0.0//org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:226) ... 86 more Caused by: org.keycloak.theme.FreeMarkerException: Failed to process template text/executeActions.ftl at org.keycloak.keycloak-services@16.0.0//org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:71) at org.keycloak.keycloak-services@16.0.0//org.keycloak.email.freemarker.FreeMarkerEmailTemplateProvider.processTemplate(FreeMarkerEmailTemplateProvider.java:224) ... 86 more Caused by: freemarker.template.TemplateNotFoundException: Template not found for name "text/executeActions.ftl". The name was interpreted by this TemplateLoader: org.keycloak.theme.FreeMarkerUtil$ThemeTemplateLoader@3ab3f80. at org.freemarker@2.3.31//freemarker.template.Configuration.getTemplate(Configuration.java:2883) at org.freemarker@2.3.31//freemarker.template.Configuration.getTemplate(Configuration.java:2703) at org.keycloak.keycloak-services@16.0.0//org.keycloak.theme.FreeMarkerUtil.getTemplate(FreeMarkerUtil.java:85) at org.keycloak.keycloak-services@16.0.0//org.keycloak.theme.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:58) ... 87 more`

Themes configuration in keycloak application.
![image](https://github.com/keycloak/keycloak/assets/101807264/32e4d797-3aff-4ed8-b514-b737fc399785)

Email configuration:
![image](https://github.com/keycloak/keycloak/assets/101807264/9796d9ef-8efb-4dc8-a5fc-c460e5a11a6e)

Expected output is Message in plaintext, but is returns filename. Can anyone please help on this.

Actual output:
<img width="171" alt="image" src="https://github.com/keycloak/keycloak/assets/101807264/b34f73fc-00a4-4ed5-b228-a0116e9fa4d5">

Expected output:
<img width="304" alt="image" src="https://github.com/keycloak/keycloak/assets/101807264/484830d9-64dd-43d4-a507-574410490c5a">

**Comment by jonkoops** [comment]
We don't provide support on older versions of Keycloak. If this issue is reproducible in the latest version of Keycloak feel free to submit a new issue, or we can re-open this one.
