### ISSUE TITLE
Fix for certificate revalidation 

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#20663]
### Description

When "Revalidate Client Certificate" is active and there's no reverse proxy before Keycloak the certificate won't be revalidated. If this happens and the KC_SPI_TRUSTSTORE_FILE_FILE variable is missing/misconfigured, any trustfile may be accepted with the logging information of "Cannot validate client certificate trust: Truststore not available".

**Comment by stianst** [comment]
Resolved by https://github.com/keycloak/keycloak/pull/20693
