### ISSUE TITLE
SAML IDP integration doesn't redirect to the IDP login page 

### ISSUE THREAD

**Issue by fvitolo** [keycloak/keycloak#20667]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

saml

### Describe the bug

Trying to configure a SAML IDP using the wizard provided by keycloak 'SAML v2.0' (**<keycloak_host>/admin/master/console/#/<tenant_name>/identity-providers/saml/add**) using azure application idp, okta, samltest.id (https://samltest.id/), the login crashes when redirecting to the authorisation page of the relevant external system, on the screen shown below.
![image](https://github.com/keycloak/keycloak/assets/103186799/342018b1-b408-4eea-ad94-96b0c0a95a0c)

There are no errors in the server logs, the only one detected is the client log above which asks for javascript to be enabled (already enabled in the browser, is there any other keycloak-side action needed?).

We are not sure whether this could be a keycloak bug, but we would like some indication as to which areas should be investigated, from a network or configuration point of view.

Below are screenshots with the current configuration of the idp created using samltest.id as provider:

![image](https://github.com/keycloak/keycloak/assets/103186799/b2cc495e-a6d9-4bd3-8b52-6c13b21e9b8a)
![image](https://github.com/keycloak/keycloak/assets/103186799/56fe85ff-69ce-46bd-a271-6a61c6d6a90a)
![image](https://github.com/keycloak/keycloak/assets/103186799/73916d63-63e2-47e1-ae91-6d52eb78b963)

### Version

21.1.1

### Expected behavior

Once you click on the idp in the login screen, you are redirected to the relevant authentication page.

### Actual behavior

Once you click on the idp in the login screen you are stuck on the following keycloak page 
![image](https://github.com/keycloak/keycloak/assets/103186799/71d2193b-2f9f-4a66-84e8-618d124f25b8)

### How to Reproduce?

Configure any idp by following the 'SAML v2.0' wizard

**Comment by rmartinc** [comment]
Hi @fvitolo!

When you configure SAML as an identity provider and click the provider button, keycloak sends a saml AuthnRequest to the IdP configured. By default it uses POST binding, which is a POST automatically submitted via javascript in the html. The page you are seeing is exactly that, and yes, post binding requires javascript, if you have it disabled in your browser please enable it. My feeling is that you are stuck at that point and you cannot reach the IdP to submit the POST. Try to see if you can reach the URL in the form in that page.

I did a little test with samltest.id and I could successfully perform a login. So all the redirections work OK.

As commented try to see if you can reach the URL

**Comment by rmartinc** [comment]
Closing the issue. Please re-open if needed.

**Comment by fvitolo** [comment]
Hey @mcgrawia, I don't know if this can be useful to you, but we solved it by setting the flag `HTTP-POST binding for AuthnRequest`  to false.

![image](https://github.com/keycloak/keycloak/assets/103186799/a4a07dec-23ad-42e4-badd-015d8ce50f72)

**Comment by mcgrawia** [comment]
thanks for the quick response @fvitolo, that fixed it! I'll make a separate issue for the CSP bug, the redirect is working with this new setting. Thanks!
