### ISSUE TITLE
User Group is not working as intended

### ISSUE THREAD

**Issue by lillyqian** [keycloak/keycloak#20666]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If I create a user which is assigned to the user group by default, and remove a user, I am still able to login to the the  application that Keycloak secures.

### Version

21.1.1

### Expected behavior

If I remove a user from the User group, I  should not be able to login to the the  application that Keycloak secures.

### Actual behavior

If I remove a user from the User group, I  am able to login to the the  application that Keycloak secures

### How to Reproduce?

1. Create a user which is assigned to the user group by default
2. Remove a user from the User group
3. I am still able to login to the the  application that Keycloak secures.

**Comment by sschu** [comment]
@lillyqian This is working as designed.  A user can always authenticate to Keycloak and Keycloak will generate a token for the user upon successful authentication. It is up to the application to deny access based on role assignments or group memberships of the user when checking the token content.
