### ISSUE TITLE
Selecting one mapper and switch page select them all

### ISSUE THREAD

**Issue by Andyriod** [keycloak/keycloak#20694]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

If you select a client dedictated scope setting and try to select one new mapper "From predefined mappers" and do a page-click in this mappers-view the result is that all predefined mappers get selected.

### Version

21.1.1

### Expected behavior

Only the selected mapper get's selected after page change

### Actual behavior

All mappers get's selected after page change

### How to Reproduce?

Select a client, go to client scope, the client-dedictated and then add a predefined mapper, do a page-click in the mapper view.
![capture_005_31052023_154554](https://github.com/keycloak/keycloak/assets/1324154/a27c7353-55f3-43fa-856a-d56e13a88496)
![capture_006_31052023_154603](https://github.com/keycloak/keycloak/assets/1324154/4ab88a6d-8441-4ed3-9b6d-5d623c609a78)
![capture_007_31052023_154611](https://github.com/keycloak/keycloak/assets/1324154/22b478c3-3f43-4ec5-b145-e72af5d1c3d5)

**Comment by ssilvert** [comment]
I have reproduced this.
