### ISSUE TITLE
FAPI 2.0 support

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#20708]
### Description

Support the following FAPI 2.0 security profile specifications:

- [FAPI 2.0 Security Profile](https://openid.bitbucket.io/fapi/fapi-2_0-security-profile.html)
- [FAPI 2.0 Message Signing (Draft)](https://openid.bitbucket.io/fapi/fapi-2_0-message-signing.html)

Subtasks ( related tasks):

```[tasklist]
### Tasks
- [ ] #21181
- [ ] #20710
- [ ] #20584
- [ ] #20623 
- [ ] #20622 
- [ ] #8589
- [ ] #8574 
- [ ] #21945
- [ ] https://github.com/keycloak/keycloak/issues/22043
```

**Comment by mposolda** [comment]
Closing as everything for support latest FAPI 2 drafts was delivered
