### ISSUE TITLE
Realm export performance heavily depends on the amount of users per file

### ISSUE THREAD

**Issue by thomasschuerger** [keycloak/keycloak#20703]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

I frequently need to export a realm (including users) and need to import it into another Keycloak server.

I have a realm with currently around 11500 users. Exporting the realm with users is extremely slow if --users=same_file is used. The export then exports just a few users per second and runs into a timeout after 5 minutes. After this time, only around 930 users have been exported, amounting to around 3 users per second.

If --users=different_files is used, the export is fairly fast if a low number of users per file (via the --users-per-file parameter) is used and becomes slow if a larger amount of users per file is used. With 50 users per file (the default), the whole export takes around 80 seconds (over 140 users per second), with 1000 users per file, the export takes 280 seconds (around 40 users per second), with a higher number this runs into a timeout. The amount of users per file (which I assume is also the transaction size) heavily affects the performance during the export.

The relationship between the number of users per file and the export time is not mentioned anywhere in the Keycloak documentation.

### Version

21.1.1

### Expected behavior

The number of users per file during a realm export should not impact the performance. Keycloak should internally always work with some fixed optimal transaction size, regardless of how many users it stores per file in the end. It should not matter whether I use 10 or 5000 users per file (except for some slight overhead for having more files).

I expect the export time to grow linearly with the number of users.

### Actual behavior

The realm export performance depends heavily on the amount of users per file. The worst case is --users=same_file, which is very slow. With --users=different_files, the performance gets better and better the lower the --users-per-file parameter is.

### How to Reproduce?

Create a realm with a large number of users (e.g. 10,000). Measure the time for a realm export using --users=same_file and compare this to using --users=different_files with different values for --users-per-file (50, 500, 5000).

**Comment by chethankumar4046** [comment]
@thomasschuerger Can you help me with some document for how to backup and restore keycloak, 
i am in 18.0.2 version i want to migrate to version 21.1.1 
 i have red this docs but not getting 
 https://www.keycloak.org/docs/latest/upgrading/index.html
 in above doc it saying need to backup config, theme and database but not given example how to backup 
 also is there any flag to show export portion in UI

**Comment by thomasschuerger** [comment]
> @thomasschuerger Can you help me with some document for how to backup and restore keycloak, i am in 18.0.2 version i want to migrate to version 21.1.1 i have red this docs but not getting https://www.keycloak.org/docs/latest/upgrading/index.html in above doc it saying need to backup config, theme and database but not given example how to backup also is there any flag to show export portion in UI

Not sure what this has to do with this bug, but anyway.

What this means is that you should backup your Keycloak database and that you should backup the Keycloak installation folder (and any other Keycloak folders than may contain Keycloak configuration, like /etc/keycloak). There is probably no example, because it heavily depends on the environment you install Keycloak on. For example, different Linux distributions may store Keycloak and its configuration files in different locations.

**Comment by KonradFeher** [comment]
> ### Actual behavior
> The realm export performance depends heavily on the amount of users per file. The worst case is --users=same_file, which is very slow. With --users=different_files, the performance gets better and better the lower the --users-per-file parameter is.

I am running Keycloak v21.1.1 inside a Docker container. It has one realm with ~22k users.  
Running `export` with:  
- `--users different_files --users-per-file 50`, same as no flags, takes ~2min 10sec  
- `--users different_files --users-per-file 1` takes ~9 minutes  
- `--users different_files --users-per-file 1000` takes over 10 minutes (interrupted)   
- `--users same_file` also takes very long

I'm surprised the default is the fastest for me out of these.  
Something really is amiss.

**Comment by ahus1** [comment]
We currently see an exponential slowdown with the number of entities being read from the database. This is caused by the Hibernate's persistence context growing when reading lots of uses from the database.

Reading the previous comment, this is why "50" is a good default. I'll prepare a documentation change around this, but I won't touch the code. If someone wants to improve the export/import behavior, I'd be happy to see an enhancement request accompanied by a discussion how to change this and/or pull request.
