### ISSUE TITLE
IDELauncher not loading providers

### ISSUE THREAD

**Issue by alninoext** [keycloak/keycloak#20705]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

We have been attempting to debug a custom provider that we are building. Our provider extends the registration flow and has already been tested on a Kubernetes-deployed Keycloak. However, we still want to debug certain parts of our code.

We have copied our provider's JAR file into the providers directory and executed the IDELauncher. However, we are unable to see the provider's ID/description in the steps list when configuring a new authentication flow. Additionally, we are not observing any logs related to the loading of providers.

We followed instructions written on keycloak/quarkus/README.md file

### Version

release/21.1

### Expected behavior

Provider loaded log:
2023-**-** **:**:**,*** WARN  [org.keycloak.services] (build-14) KC-SERVICES0047: registration-user-creation-custom (com.***.forms.RegistrationCustomUserCreation) is implementing the internal SPI form-action. This SPI is internal and may change without notice

### Actual behavior

None provider/theme is loaded.

### How to Reproduce?

Run IDELauncher.main method, add a dummy provider/theme and try to configure it on Keycloak.

**Comment by sschu** [comment]
I am not sure the IDELauncher is actually expected to pick up custom providers. Looking at the referenced Readme: 

"To run the server in Quarkus' development mode, invoke the following command:

    mvn -f server/pom.xml compile quarkus:dev -Dquarkus.args="start-dev"

You will be able to attach your debugger to port `5005`.

For debugging the build steps right after start, you can suspend the JVM by running:

    mvn -f server/pom.xml -Dsuspend=true compile quarkus:dev -Dquarkus.args="start-dev"

When running using `quarkus:dev` you are able to do live coding whenever you change / add code in the `server` module, for example when creating a new custom provider."

So I would assume this is how you can debug your extensions and get hot code reload...

**Comment by mabartos** [comment]
@sschu Yes, that's correct. Thanks for the explanation.

The Keycloak submodules are considered to be non-reloadable dependencies for IDELauncher.
