### ISSUE TITLE
Edge and Safari refresh triggers redirect

### ISSUE THREAD

**Issue by mpichler-abc** [keycloak/keycloak#20726]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I am running an angular app with keycloak as authentication service. When I refresh a page or go to an URL in my application directly, I am redirected to the main page of the application. This only happens in Edge and Safari (IPhone, no Mac available). it works fine in Chrome, Firefox and Brave.  Direct links also work when I am already on my sites domain. 

E.g.

- mysite.com/#/home -> enter url mysite.com/#/sales [works]
- mysite.com/#/sales-> enter url mysite.com/#/sales [redirect]
- mysite.com/#/sales-> refresh [redirect]

Edge also shows this warning in the console which leads me to believe it is a problem with my keycloak-js config and how login-checks are handled. 

![image](https://github.com/keycloak/keycloak/assets/112545379/59fa4369-21bc-4a5e-a43b-88921faf31cc)

### Version

20.0.5

### Expected behavior

Stay on the current page on which I hit refresh

### Actual behavior

Refresh and links from other domains trigger a redirect to main page

### How to Reproduce?

Refresh a page in Edge or Safari

### Anything else?

I am running keycloak in a docker container. The interessting thing is, when testing locally, everything works. When deployed on a test server (not production environment). The above warning shows up and the redirects are triggered. 

In the test envrionment the angular app is also running in a docker container, in the local environment it is run directly using "npm start" on port 4200

**Realm Security Settings**

![image](https://github.com/keycloak/keycloak/assets/112545379/57acc894-1a8e-4812-810d-fde0502b1b46)

**Angular keycloak-js initi code**

![image](https://github.com/keycloak/keycloak/assets/112545379/da7252aa-2483-453c-8ec9-9c0211a52e64)

Redirect URI's are correctly configured as far as I can tell. 

I even tried with the keycloak nightly build to see if a recent PR would have fixed it.

**Comment by jonkoops** [comment]
Thanks for testing the nightly @mpichler-abc. We'll be releasing 21.1.2 next week, which will include the aforementioned fix.
