### ISSUE TITLE
uma-ticket returns 403 even though user has access, when User Realm Role isn't present in access Token

### ISSUE THREAD

**Issue by malopez16** [keycloak/keycloak#20736]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/fine-grained-permissions

### Describe the bug

uma-ticket response changes depending on if the `access_token` has `roles` or not. 

Trying to solve an issue where the JWT is getting too big to hold all of the roles. To solve that, I'm following this advice: https://keycloak.discourse.group/t/huge-jwt-token-size/17244/2 but it turns out it is not possible to get a `success` response from `/realms/authorization_poc/protocol/openid-connect/token` when requesting a uma-ticket if the access_token doesn't have roles on it.

Does this mean there is absolutely no way for a user to have many roles? as otherwise the JWT will get too big. 
Seeing https://github.com/keycloak/keycloak/discussions/9713 is not solved, are there no approaches possible using keycloak when the jwt gets too big?

### Version

21.1.1

### Expected behavior

User should be granted access to a resource via `realms/authorization_poc/protocol/openid-connect/token` if it has access to the resource, independent of if the access_token carries the `roles` claims on it or not. 

### Actual behavior

API returns access denied to a resource for a User that has access to the resource, if access token doesn't have `roles` in it.

### How to Reproduce?

Follow https://medium.com/@harsh.manvar111/keycloak-authorization-service-rbac-1c3204a33a50. End up with a that user is allowed to access a resource, as shown by my test in postman to `realms/authorization_poc/protocol/openid-connect/token`:
<img width="2143" alt="image" src="https://github.com/keycloak/keycloak/assets/26126519/d146dc6a-f846-44a3-8905-fa70655caec8">

Next step is to remove all of the role data from the access token, I'm just removing it from here:

<img width="1090" alt="Screenshot 2023-06-01 at 19 28 21" src="https://github.com/keycloak/keycloak/assets/26126519/2e431df6-8e5e-4744-a223-a53fcbd24b14">

BUT when I call the token endpoint once again with this new access token, I **always** get denied/rejected:
<img width="2061" alt="image" src="https://github.com/keycloak/keycloak/assets/26126519/e72f0cba-def2-4fd2-8221-088a7355e6a7">
This is 100% reproducible.

**Comment by shafii-upsilon** [comment]
I have the same problem

**Comment by Romain7495** [comment]
same problem in 22.0.5, working with group policies but not working with role policies

**Comment by Romain7495** [comment]
@stianst @mposolda Sorry to bother you, but, do you think this is a normal behaviour ?

**Comment by pedroigor** [comment]
The problem here is that the role policy provider only takes into account the roles in the token. See https://github.com/keycloak/keycloak/blob/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProvider.java.

As you noticed, the group policy provider behaves differently because groups are fetched from the database.

We can certainly improve this and perhaps provide a setting to decide if roles should also be checked within the user session and not only from what is granted in a subject token.

@Romain7495 @malopez16 Wdyt?

**Comment by malopez16** [comment]
I think that would be the only way to handle a user having a lot of roles -- otherwise the token gets too big and there's no chance of getting them into it.

**Comment by Romain7495** [comment]
Thank you very much for your answer, @pedroigor 

Having this feature would be extremely helpful. 🙌

In my view, using an authorization server aims to streamline our backend by removing complex logic from it. This approach also allows us to maintain minimal JWTs, as the authorization server contains all the necessary information for decision-making.

**Comment by pedroigor** [comment]
@malopez16 Sent https://github.com/keycloak/keycloak/pull/27430. Please, let me know if it works well for you and others participating in this issue.

Not sure about the `Fetch Roles` label. If you guys have a better name, please let me know.

**Comment by Romain7495** [comment]
hello @stianst, what is the reason to postpone this feature ?

**Comment by Romain7495** [comment]
@stianst do you know in which 24.0.x release this change will be backport ?

**Comment by Romain7495** [comment]
any chance to have it backported to 24 release please? @pedroigor

**Comment by matthiasValuecloud** [comment]
Activating the Keycloak Preview TokenExchange starting with Keycloak v.22.01 helps with this issue: An Access Token without roles yields an uma-ticket.
