### ISSUE TITLE
Keycloak erases form data on validation when `login_hint` is present

### ISSUE THREAD

**Issue by bysanches** [keycloak/keycloak#20732]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

When submitting an invalid registration with the `login_hint` search parameter present, the response erases all the fields aside from the email/username.

### Version

21.1.1

### Expected behavior

Keycloak should render the submitted data on postback so that the user doesn't need to fill them all again.

### Actual behavior

Keycloak erases the form data aside from the email/username on postback.

### How to Reproduce?

Open the registration page with a `login_hint` search parameter and submit an invalid form (e.g. missing last name).

**Comment by ssilvert** [comment]
I did reproduce this.  Thanks for the PR.
