### ISSUE TITLE
Spring Boot 3+ Jakarta API support in Spring Security Adapter

### ISSUE THREAD

**Issue by majoferenc** [keycloak/keycloak#20738]
### Description

As our project relies on Keycloak as an authentication provider, we are integrating with it via library called `keycloak-spring-security-adapter`. After migrating all libaries to Spring Boot 3.0, we are encountering several import issues in Keycloak Spring Security Adapter. Mainly imports from package `javax.servlet`, which should be replaced with imports from `jakarta.servlet` package group.

### Motivation

Spring Boot 3.0 support is essential for Keycloak Java community as it's major stable release of Spring Boot library.

**Comment by romanbad** [comment]
Issuing the same problem, we're using keycloak-spring-security-adapter and planning migration to Spring 6. But it doesn't support Jakarta API's.

**Comment by andregmoeller** [comment]
Last year, the Keycloak project announced the deprecation of the Keycloak Java Adapters: https://www.keycloak.org/2022/02/adapter-deprecation.html.

This year, a new blog post was published on the same subject: https://www.keycloak.org/2023/03/adapter-deprecation-update

The blog post states:
_The Keycloak Java adapters will remain for a while though, at least towards the end of the year, but likely not be removed until early 2024. At the same time don’t expect the adapters to be updated in terms of adding new features, enhancements, or supporting newer versions of Tomcat, Jetty, WildFly, or Spring._

Taking these blog posts into consideration, we decided to switch to alternative solutions. 

Regarding the requirement stated in this issue, I would be happy to see it implemented. However, I have reservations about the likelihood of it being fulfilled.

**Comment by romanbad** [comment]
@andregmoeller Thanks for your comment! 
We'll consider altervative solutions.

**Comment by nikolay-petkoff** [comment]
Does anyone knows how is possible Keycloak Client Authorization to be used without adapter? I mean authorization scopes, permissions and policies defined in Keycloak client authorization.

**Comment by Arturbarth** [comment]
And what are these alternative solutions?

**Comment by dtrunk90** [comment]
> And what are these alternative solutions?

Did you read https://www.keycloak.org/2023/03/adapter-deprecation-update ?

**Comment by Arturbarth** [comment]
thanks, sorry

**Comment by Arturbarth** [comment]
Thanks, Sorry

**Comment by stianst** [comment]
Closing this as the Keycloak Spring adapter is deprecated, and will be removed soon. I'd suggest looking at Spring Security as an alternative.
