### ISSUE TITLE
Update wildfly-elytron to 2.2.0.Final

### ISSUE THREAD

**Issue by xieshenzh** [keycloak/keycloak#20749]
### Description

wildfly-elytron 2.2.0.Final was released recently to [fix a high severity vulnerability](https://github.com/wildfly-security/wildfly-elytron/pull/1904): https://issues.redhat.com/browse/ELY-2551
Keycloak should update the wildfly-elytron dependency to address the vulnerability.

**Comment by pskopek** [comment]
The issue is fixed by PR #20632
