### ISSUE TITLE
SEND_RESET_PASSWORD event is not stored

### ISSUE THREAD

**Issue by s-solianyk-onventis** [keycloak/keycloak#20757]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

SEND_RESET_PASSWORD event is not stored

### Version

21.1.1

### Expected behavior

SEND_RESET_PASSWORD event is stored. This event was stored in the 21.0.2 version.

### Actual behavior

SEND_RESET_PASSWORD event is not stored in the database, it is not visible on the admin UI

### How to Reproduce?

- Run Keycloak `21.1.1` locally using docker compose (in my case I have SQL Server database, but it could be any supported database)
![image](https://github.com/keycloak/keycloak/assets/120454144/72dd2f4c-bef8-4e66-b0d0-80072a87b259)
- Create realm `test-realm`
- Configure Login section:
![image](https://github.com/keycloak/keycloak/assets/120454144/3cb68630-1af5-48d2-9e3e-85fcc368b454)
- Configure smtp (please use valid smtp configuration) 
![image](https://github.com/keycloak/keycloak/assets/120454144/05c71624-9a36-4def-a07b-92cebf5e2afd)
- Enable UserEvents, make sure that `SEND_RESET_PASSWORD` is in the list
![image](https://github.com/keycloak/keycloak/assets/120454144/0e354e6f-ebb6-49b8-a4ea-d2df12327e24)
- Create test user
![image](https://github.com/keycloak/keycloak/assets/120454144/85db9b7a-5488-4844-95be-d25adf754b2e)
- Open client and click to Sign In, then click to Forgot password: http://localhost:8091/realms/test-realm/account/
![image](https://github.com/keycloak/keycloak/assets/120454144/aed3f39e-7169-4fc2-9cad-d1ed04f8edc2)
- Use valid test user email address and click Submit
![image](https://github.com/keycloak/keycloak/assets/120454144/f33d3fbc-546b-4436-ba9a-fe8082c5a1a2)
- Open user events, they are empty
![image](https://github.com/keycloak/keycloak/assets/120454144/019dda88-2ed5-40a3-9b12-2d561855b1e6)

### Anything else?

Please see exported realm json file in zip archive below:
[test-realm.zip](https://github.com/keycloak/keycloak/files/11637895/test-realm.zip)

**Comment by rmartinc** [comment]
@s-solianyk-onventis Yes this is a minor regression triggered by https://github.com/keycloak/keycloak/issues/17644. When a user is cloned the store is not copied and it is not saved in it. Added keycloak 22 as it's a regression.
