### ISSUE TITLE
Does KeyCloak share SSO session among micro front end applications inside iframes?

### ISSUE THREAD

**Issue by anatoly-spb** [keycloak/keycloak#20776]
Hello! 

I have two KeyCloak clients app1, app2 in my realm related to my two web applications http://mysite/app1 and http://mysite/app2.  

I want to show app2 inside iframe in app1, but when I login to app1 and redirect to app1 my application app2 does not see SSO session and redirect to KeyCloak login page:

![image](https://github.com/keycloak/keycloak/assets/13556403/1dc057ea-8b1e-4884-b322-ff2b0c415b89)

If I put app2 into anchor and click on it, everything is ok, app2 open without output login prompt. 

What can be wrong?

Thanks in advance,
Anatoly Shirokov

_Originally posted by @anatoly-spb in https://github.com/keycloak/keycloak/discussions/20743_

**Comment by jonkoops** [comment]
Closing this as it's not an issue, but a question. Also one that was already started #20743.
