### ISSUE TITLE
Admin UI keeps on loading

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#20775]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

![image](https://github.com/keycloak/keycloak/assets/135589150/b5fe1ad5-de72-429c-94c0-0b4ce4594927)

Using Bitnami helm charts to deploy Keycloak on aws eks.

Getting these error on console while trying to open admin login page.

Mixed Content: The page at ‘https://auth.keycloak.aws.com/admin/master/console/’ was loaded over HTTPS, but requested an insecure resource ‘http://auth.keycloak.aws.com/realms/master/protocol/openid-connect/3p-cookies/step1.html’. This request has been blocked; the content must be served over HTTPS.

### Version

21.1.1

### Expected behavior

Admin UI login screen should open properly.

### Actual behavior

Admin UI is keeps on showing loading.

### How to Reproduce?

Start the keycloak server using helm charts deployment and then try to open the server in https mode.

**Comment by jonkoops** [comment]
This is already tracked under #14666
