### ISSUE TITLE
Ability for users to view credentials without manage user permissions

### ISSUE THREAD

**Issue by eatikrh** [keycloak/keycloak#20783]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

This is a bug related to https://github.com/keycloak/keycloak/issues/17174 where users with "view" permission need to be able to see the  user management/credentials tab.  We need to allow users with `view-users` permission only to be able to call `/auth/admin/realms/<realm>/users/<userid>/configured-user-storage-credential-types` endpoint.

### Version

22

### Expected behavior

User with view-users permission should be able to see the user management/credentials tab. This is due to not having the permission to call UserResource.credentials()/

### Actual behavior

User with with only view-users permission see and error on when they navigate to the credentials tab. 

### How to Reproduce?

With view-users permission navigate to Admin console/user management/credentials tab.

**Comment by jsorah** [comment]
@eatikrh - If you wouldn't mind getting your PR for this issue updated and linked that would be great, thanks!

**Comment by eatikrh** [comment]
created a new pull request https://github.com/keycloak/keycloak/pull/21165
closed the old pull request https://github.com/keycloak/keycloak/pull/20821
