### ISSUE TITLE
Mappers tab is not reachable on identity provider settings

### ISSUE THREAD

**Issue by onikitin-iqmessenger** [keycloak/keycloak#20782]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

There is no possibility to reach the `Mappers` tab after the creation of the `SAML v2.0` identity provider in case you add spaces in the alias field.

### Version

21.1.1

### Expected behavior

There is validation on the `alias` field on the step of the creation of the identity provider to prevent the incorrect working of that in the future.
OR
The `alias` field value is trimmed before saving.
But preferably there to be validation, to prevent saving with spaces or other forbidden symbols.

### Actual behavior

The form is saved without any constraints about the spaces so it does not allow user to set up any mappers

### How to Reproduce?

1. go to `Identity providers`
2. click `Add provider` → SAML 2.0
3. set up any provider with the space in the `Alias` field
4. save the provider

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by edewit** [comment]
Should we make it invalid to put an space

**Comment by onikitin-iqmessenger** [comment]
hello @edewit!
will this fix be ported to 21.1.x?
