### ISSUE TITLE
Can we simplify TokenManager.getRefreshExpiration() and TokenManager.getOfflineExpiration()?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#20794]
### Description

Follow-up to PR https://github.com/keycloak/keycloak/pull/17525 :

After the #17525, It seems to me that methods `TokenManager.getRefreshExpiration()` and `TokenManager.getOfflineExpiration()` have some duplicated logic for retrieving timeouts. Maybe it's possible to adjust those methods to re-use the logic from `SessionExpiration` class to have unified place where the logic for timeouts is implemented?

This task is possible refactoring, but it's to be investigated if it makes sense. It seems to me that yes, but I am not yet 100% sure if this would simplify things or rather make them more complicated.

**Comment by rmartinc** [comment]
I want to try this one first, just in case the docs and tool-tips are affected.
