### ISSUE TITLE
Upgrade to Infinispan 14.0.10.Final

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20803]
### Description

Upgrade Infinispan to the latest release as it contains fixes like https://github.com/infinispan/infinispan/pull/10886

**Comment by martin-kanis** [comment]
This upgrade should also fix https://github.com/keycloak/keycloak/issues/19739

**Comment by ahus1** [comment]
@martin-kanis - I had a look at that issue. As I wasn't able to reproduce the issue with the old version, I'll not close this issue with the PR connected to this issue. I'd be happy if you could use your knowledge to check if the issue is fixed once the PR #20804 is merged.
