### ISSUE TITLE
Improve start page on the account ui

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#20817]
### Description

currently the account ui start page looks like this:
![image](https://github.com/keycloak/keycloak/assets/51133/1210c20f-e615-45ee-8d0a-1da3969aeaa4)
Either remove this page and make personal info the start or make this page look better

**Comment by ssilvert** [comment]
@edewit Right now, if you are not logged in and you go directly to the account console with a URL like localhost:8180/realms/master/account/ then you will see the "Welcome" page with "Anonymous" as the user name in the upper right.  Then when you click on something you have to log in.

That's a little awkward, so it looks like the best solution would be to go to the default section `/`.  That way, if you are not logged in you would be immediately prompted with the login screen.  This means we don't have a Welcome page.

Usually, `/` would go to Personal Info.  But it doesn't have to.  It might be the case where you don't want the user to see a Personal Info page.  So if it's not already, the default section should be configurable.

**Comment by edewit** [comment]
ATM it's not configurable, so how would we do that?

**Comment by ssilvert** [comment]
> ATM it's not configurable, so how would we do that?

There are many ways to do it, but it depends on the specifics we come up with in the customization project.

**Comment by ssilvert** [comment]
> Instead of making this configurable I think we can go with the sensible default of forcing the user to log in. You can't do anything in the Account Console if you are not signed into an account.
> 
> The redirect should be pretty simple to accomplish, we can modify the index route so it uses a [`<Navigate>` element](https://reactrouter.com/en/main/components/navigate#navigate) to redirect to the 'Personal Info' page.

I don't think we should assume that the initial page requires login.  For example, V2 doesn't require login for the home page.  It depends on how the developer wants to customize the app.  If it hits a section with a protected resource then it will prompt for authentication automatically.

**Comment by ssilvert** [comment]
> > If it hits a section with a protected resource then it will prompt for authentication automatically.
> 
> Which sections in the V3 UI do not require authentication?

I'm thinking of a new section or splash screen that a developer might want to add.

**Comment by jonkoops** [comment]
> I'm thinking of a new section or splash screen that a developer might want to add.

That is fair, but should we not take that as a separate issue in regards to customization? We currently don't even have a way to register custom pages yet.

**Comment by ssilvert** [comment]
> > I'm thinking of a new section or splash screen that a developer might want to add.
> 
> That is fair, but should we not take that as a separate issue in regards to customization? We currently don't even have a way to register custom pages yet.

Why take the time to implement a redirect when we know it's not what we want?  Just make the initial screen be `/`, which points to Personal Info by default.  It will automatically prompt for login.  Simple.

**Comment by jonkoops** [comment]
That is also a fair fix. Let me take care of that real quick :+1:

**Comment by crowmedia** [comment]
Also if you want to sign in on this page from another tenant, you will be redirect to the master and can not really login
