### ISSUE TITLE
account3 console does not load for realms other than master

### ISSUE THREAD

**Issue by kenkeys** [keycloak/keycloak#20829]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

With the account3 feature enabled, the account console does not load for realms other than master.

### Version

21.1.1

### Expected behavior

Visiting /realms/myrealm/account loads an account console.

### Actual behavior

With account3 enabled, attempting to visit /realms/myrealm/account results in "We are sorry... Invalid parameter: redirect_uri".  (Note that it works as expected without account3 enabled, and /realms/master/account works as expected with or without account3 enabled.)

### How to Reproduce?

Enable the account3 feature, and attempt to visit the account console of a realm other than master.

### Anything else?

kc.sh started with `start-dev --features=preview,account3`

**Comment by ssilvert** [comment]
This is working just fine for me.  Can you try the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by kenkeys** [comment]
It works as expected in the nightly build.

**Comment by jonkoops** [comment]
Since this works in the latest development build, this issue will be fixed in Keycloak 22. Closing.

**Comment by aureleoules** [comment]
I have the same issue on Keycloak v21.1.2.

**Comment by jonkoops** [comment]
@aureleoules if it works in the nightly, it will be released with the next major version.
