### ISSUE TITLE
Token-exchange is not working for OpenID Connect v1.0 provider in KC 21.1.1

### ISSUE THREAD

**Issue by michielpeeters** [keycloak/keycloak#20830]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

In our project we make use of the token-exchange feature and heavily rely on this implementation. We are running version 20.0.5 where the token-exchange feature for OpenID Connect v1.0 providers works flawlessly. However when we updated to the latest version the token-exchange feature does not work how we expected it should work.

In version 20.0.5 we see our custom claims map with the token-exchange. Now we get only the default claims (and no custom claims).

I've started from scratch to determine if it is in our data or that it is an actual bug in keycloak. To confirm, it is a possible bug in keycloak because from scratch it didn't work either.

I've also tested the nightly build, the problem exists there as well.

During our security tests we discovered that there was a bug in 20.0.5 and that we should upgrade to version 21.0.0 where the specific security threat was solved. That's the main reason we wanted to upgrade/upgrade to the latest version.

### Version

21.1.1

### Expected behavior

That the custom claims defined in scopes are returned when the token-exchange has occurred (i believe this is called internal-to-internal token-exchange).

### Actual behavior

The custom claims defined are not displayed/mapped in the token-exchange token. For example:

Example (this is token I use to exchange):

`{
  "exp": 1686083423,
  "iat": 1686083123,
  "jti": "158952f9-003a-4263-b837-e74797ea391d",
  "iss": "http://localhost:8080/realms/myrealm",
  "aud": "account",
  "sub": "0251f2b5-948e-40fc-9cd6-e5555542a6a1",
  "typ": "Bearer",
  "azp": "myclient-test",
  "acr": "1",
  "allowed-origins": [
    "/*"
  ],
  "realm_access": {
    "roles": [
      "default-roles-myrealm",
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email custom-customer-realm profile",
  "customer_realm": "myrealm",
  "email_verified": false,
  "clientHost": "172.19.0.1",
  "preferred_username": "service-account-myclient-test",
  "clientAddress": "172.19.0.1",
  "client_id": "myclient-test"
}`

After exchange:

`{
  "exp": 1686083505,
  "iat": 1686083205,
  "jti": "cec6821f-49c2-4e93-b090-ce05cc0bf0ac",
  "iss": "http://localhost:8080/realms/mymainrealm",
  "aud": [
    "account",
    "mymainrealm-api"
  ],
  "sub": "387e9458-f10b-4477-8eca-2e05c9f866d2",
  "typ": "Bearer",
  "azp": "mymainrealm-myclient",
  "session_state": "bc1a090e-3247-47e1-8287-48f6ec472837",
  "acr": "1",
  "allowed-origins": [
    "/*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "default-roles-mymainrealm"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "mymainrealm-customer-realm email profile",
  "sid": "bc1a090e-3247-47e1-8287-48f6ec472837",
  "email_verified": false,
  "preferred_username": "service-account-myclient-test"
}`

As you can see the customer_realm custom claim is not displayed/mapped after the token-exchange. In version 20.0.5 it is mapped.

### How to Reproduce?

Start from scratch in version 21.1.1 (I've tested it in version 21.0.0 and the problem we face was already introduced in this version). The following features are enabled:

- token-exchange
- admin-fine-grained-authz

1. Add two realms: mymainrealm and myrealm
2. Navigate to myrealm
3. Create a client-scope with the following settings:
name: custom-customer-realm
type: Default
protocol: openid connect
display on consent: yes
include in token scope: yes
All other fields, leave them with the default value

4. Create the following mapper in the recently created client-scope (custom-customer-realm) with the following settings:
mapper type: hardcoded claim
name: customer-realm-mapper
token claim name: customer_realm
claim value: myrealm
claim json type: string
id token: yes
access token: yes
userinfo: yes
All other fields, leave them with the default value

5. Create the following client:
client id: myclient-test
client authentication: yes
authentication flow(s): standard flow, service account roles
All other fields, leave them with the default value

6. Enable the permissions for the just created client (myclient-test)
7. Create a token exchange policy for the just created client and attach this token-exchange policy to the just created client
8. Create the following client:
client id: mymainclient
client authentication: yes
authentication flow(s): standard flow, direct access grants
All other fields, leave them with the default value

9. Get the client secret of the just created client (mymainclient), write this down
10. Navigate to the realm settings to the endpoints section. Click on OpenID Endpoint Configuration and write the url down
11. Navigate to mymainrealm
12. Create a client-scope with the following setting:
name: mymainrealm-customer-realm
type: default
protocol: OpenID connect
consent screen: yes
token scope: yes
All other fields, leave them with the default value

13. Create the following mapper in the recently created client-scope (mymainrealm-customer-realm) with the following settings:
mapper type: user attribute
name: mymainrealm-customer-realm
user attribute: customer_realm
token claim name: customer_realm
claim json type: string
id token: yes
access token: yes
userinfo: yes
All other fields, leave them with the default value

14. Create the following client:
client id: mymainrealm-myclient
All other fields, leave them with the default value

15. Create the following client:
client id: mymainrealm-api
client authentication: yes
authentication flow(s): standard flow, direct access grants, service account roles
All other fields, leave them with the default value

16. Enable the permissions for the just created client (mymainrealm-api)
17. Create a token exchange policy pointing to the client (mymainrealm-myclient) and attach this token-exchange policy to the just created client (mymainrealm-api)
18. Create a new OpenID Connect v1.0 Identity provider (you are still in the mymainrealm realm) with the following settings:
alias: somedomain.com
discovery endpoint: the endpoint you have written down in step 10
client id: mymainclient
client secret: the client secret you have written down in step 9
All other fields, leave them with the default value

19. Create the following mapper in the recently created identity provider (somedomain.com) with the following settings:
name: custom-customer-realm-mapper
sync mode: force
mapper type: attribute importer
claim: customer_realm
user attribute: customer_realm
All other fields, leave them with the default value

20. Enable the permissions for the just created identity provider (somedomain.com)
21. Create a token exchange policy pointing to the client (mymainrealm-myclient) and attach this token-exchange policy to the just created identity provider (somedomain.com)

If all these steps are followed correctly, you need to execute the following requests with the help of Postman:

First request:
POST: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
grant_type: client_credentials
client_id: myclient-test
client_secret: the secret which you can get from the myrealm client
scope: openid

If you verify the token which is returned from the request you can see the customer_realm custom claim

Execute the following request with the help of Postman:
POST: http://localhost:8080/realms/mymainrealm/protocol/openid-connect/token
grant_type: urn:ietf:params:oauth:grant-type:token-exchange
client_id: mymainrealm-myclient
subject_token: the access token that is returned from the first request
subject_issuer: http://localhost:8080/realms/myrealm
audiance: mymainrealm-api

If you verify the token which is returned after the token-exchange you can see that the customer_realm custom claim does not exist anymore (and in version 20.0.5 it works).

Sorry for the long list of steps to execute ;-) ...

### Anything else?

What I've seen from the other responses, you guys seems to be busy. Hopefully you get some time to review the bug and confirm if it is a bug or not. Otherwise we need to stay on version 20.0.5 until this is resolved with a potential security risk.

**Comment by mposolda** [comment]
I am adding to Backlog as token exchange is a preview feature and not an immediate priority issue and Keycloak team may not be able to look into it into the near future. Anyone is welcome to investigate this and eventually contribute the fix for this if needed (after verification that it is the valid issue and not misconfiguration etc).

**Comment by Margo-Ermens** [comment]
I am facing the same problem. It was introduced in [this](https://github.com/keycloak/keycloak/commit/7b58783255fb4059c125b168c7ec0bd68cb17778) commit. In the AbstractClaimMapper the null check is removed for the idToken, so without an id token the method `getClaimValue` will return null instead of looking at the userInfo claim. It will probably be resolved by reintroducing the null check.

**Comment by rick-lansink** [comment]
+1, We are also facing this issue regarding the token exchange

**Comment by michielpeeters** [comment]
We did manage to get a workaround this issue, because we are doing a token-exchange from a keycloak tenant to another keycloak tenant we have changed the provider from OpenID connect to a Keycloak OpenID connect provider. I don't know how it would work if you use this type of provider to an external OpenID connect provider.

**Comment by rick-lansink** [comment]
> We did manage to get a workaround this issue, because we are doing a token-exchange from a keycloak tenant to another keycloak tenant so we have changed the provider from OpenID connect to a Keycloak OpenID connect provider. I don't know if it would work if you use this type of provider to an external OpenID connect provider.

As a test I configured aKeycloak OpenID connect provider against an external OpenID connect provider (Amazon Cognito) and it seems to work just fine.

**Comment by ahus1** [comment]
Adressing the community: There is now a pull request by @gitdode in #21878, please review it, and possibly ping @mposolda once there is a successful community review.

**Comment by gitdode** [comment]
It seems the issue applies also to the 'Keycloak OpenID Connect' provider when using the 'Username Template Importer' mapper: the username is missing in the mapped result.

**Comment by belfhi** [comment]
I can confirm that the PR by @gitdode helped fix our Token Exchange with a custom mapper. 👍
