### ISSUE TITLE
Null pointer exception occurs when I use keycloak-admin-client for permission verification

### ISSUE THREAD

**Issue by wangpf09** [keycloak/keycloak#20836]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/java

### Describe the bug

A null pointer exception occurs when I use keycloak-admin-client for permission verification, and I think it has little to do with the parameters in my request. If it is a problem with the way I call it, can you provide a sample code for calling the evaluate method? . Or how to verify permissions in spring-boot-starter-security version 3.1.0

![e78f7b29abbebd2d3b4d98969381b64](https://github.com/keycloak/keycloak/assets/39894166/5ed9ca1a-73cb-459d-9028-5b14ea8d501c)

![image](https://github.com/keycloak/keycloak/assets/39894166/eb2c1175-72e0-4a7e-b83a-0737ec14ae90)

### Version

21.1.1

### Expected behavior

It can respond normally whether the permission verification is passed

### Actual behavior

java.lang.NullPointerException: client

### How to Reproduce?

The test code is as follows

```java
  private ClientResource getClientByClientId(String realm, String clientId) {
        ClientsResource clients = keycloak.realm(realm).clients();
        return clients.get(
                clients.findByClientId(clientId).stream().findFirst()
                        .orElseThrow(() -> new RuntimeException("keycloak client id does not exist"))
                        .getId()
        );
    }

    public void auth(String userid, String realm, String clientId, String uri) {
        UserResource user = keycloak.realm(realm).users().get(userid);
        List<String> roleIds = new ArrayList<>();
        MappingsRepresentation roleMapping = user.roles().getAll();
        roleMapping.getRealmMappings().forEach(roleRepresentation -> roleIds.add(roleRepresentation.getName()));

        PolicyEvaluationRequest policyEvaluationRequest = new PolicyEvaluationRequest();
        policyEvaluationRequest.setClientId(clientId);
        policyEvaluationRequest.setUserId(userid);
        policyEvaluationRequest.setEntitlements(true);
        policyEvaluationRequest.setRoleIds(roleIds);
        policyEvaluationRequest.addResource(uri, "admin:access");

        PolicyEvaluationResponse evaluate = this.getClientByClientId(realm, clientId)
                .authorization().policies().evaluate(policyEvaluationRequest);

        System.err.println(evaluate.getStatus());

    }
```

**Comment by sguilhen** [comment]
I couldn't spot anything wrong in the code you've provided, but we have some policy evaluation tests in the testsuite that are working fine (I've tested in Keycloak 23). For example
https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaRepresentationTest.java
and
https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/PolicyEvaluationCompositeRoleTest.java#L121-L134

**Comment by pedroigor** [comment]
@wangpf09 The proper way to evaluate permissions from applications is using the token endpoint as per https://www.keycloak.org/docs/23.0.7/authorization_services/#_service_obtaining_permissions.
The API you are using is targeted for the administration console when at the `Evaluate` tab in the client's `Authorization` tab.
