### ISSUE TITLE
Convert all properties files to UTF-8

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#20848]
### Description

A lot of our property files are not using UTF-8, which makes some of the translations hard to read. Under the issue the following should happen:

1. All `.properties` files should start with `# encoding: utf-8`
2. All encoded texts should be written in their plain UTF-8 representation.

**Comment by siddharth-sable** [comment]
I would love to work on this!

**Comment by jonkoops** [comment]
@siddharth-sable Thanks! I will assign this to you then 👍

**Comment by siddharth-sable** [comment]
Thank you 🤝

**Comment by siddharth-sable** [comment]
I have added `# encoding: utf-8` to all `.properties` files. Can you elaborate on second point? how can I check if the strings are already in their utf-8 format or not?

**Comment by jonkoops** [comment]
@siddharth-sable for example, [this file](https://github.com/keycloak/keycloak/blob/ed473da22b713d599865b4779445dc843258505b/themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_pt_BR.properties) is fill of unicode escapes. You'll see a string like `\u00e9`, which could just be written out as the character it represents, in this case `é`.

**Comment by jonkoops** [comment]
Side-note, there is probably some command like tool to do this conversion. There are also [online tools](https://r12a.github.io/app-conversion/).

**Comment by siddharth-sable** [comment]
yes

**Comment by siddharth-sable** [comment]
> Side-note, there is probably some command like tool to do this conversion. There are also [online tools](https://r12a.github.io/app-conversion/).

yeah, thank you. bash script worked well there. All escapes are now converted. Is there anything else I need to work on?

**Comment by jonkoops** [comment]
That should be it for this issue, feel free to open up a PR.
