### ISSUE TITLE
[Declarative User Profile] Attributes are created as required by default but switch is set to "not required"

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#20852]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

When declaring a new attribute with "required" switch "off", the attribute is required after saving.

### Version

21.1.1

### Expected behavior

The attribute should be stored as not required

### Actual behavior

The attribute is stored as required, although switch is set to off and isn't toggled.

### How to Reproduce?

Create an attribute with just a name and save.
![image](https://github.com/keycloak/keycloak/assets/789496/1c598101-f856-46fa-8139-12bbb77fc640)

Open the attribute and see that it is required now.
![image](https://github.com/keycloak/keycloak/assets/789496/7f3042a1-252f-4116-9078-17b265b78862)

### Anything else?

Workaround: When you know the bug, you can open the attribute and correct the setting. If not known, it is a surprise that user's can't be created any more without a value for the attribute.

**Comment by jbman** [comment]
Also the fine grained required settings seem to be broken:
"Required when" is set to "Always" but there are scopes listed in the JSON representation.

![image](https://github.com/keycloak/keycloak/assets/789496/a519b4e8-330d-4fd8-9d63-00157003ce5c)

Stored as:
{
	"required": {
		"roles": [
			"admin",
			"user"
		],
		"scopes": [
			"role_list",
			"profile",
			"email",
			"acr",
			"microprofile-jwt",
			"offline_access",
			"phone",
			"address",
			"roles",
			"web-origins"
		]
	}
}

**Comment by mposolda** [comment]
@jbman Thanks for the report. I am adding to Backlog for now. We may need to revisit if we want to make user-profile to be supported feature.

**Comment by pedroigor** [comment]
Thanks. The behavior looks correct and fixed in both the latest release (`22.0.4`) and upstream/main.
