### ISSUE TITLE
Control redirect after password reset

### ISSUE THREAD

**Issue by pxnis** [keycloak/keycloak#20867]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

After a user has reset their password, they are sent to a "random" redirect.
This happens if the user is sent directly to the reset-credentials endpoint (skipping the KC login page).
The "random" redirect is the first "Valid redirect URI", which are sorted by their hash value. Hence the quoted random.

### Version

18 (RH-SSO 7.6)

### Expected behavior

I should be able to control the redirect somewhat.

**Here are several suggested solutions**
1. Redirect to "Base URL". Base is described in the documentation as "Default URL to use when the auth server needs to redirect or link back to the client". This sounds as it should be the fallback if no redirect is found.
2. Being able to change sort order of "Valid Redirect URIs"
3. Sort "Valid Redirect URIs" alphabetically.
4. Support "redirect_uri" query-param for reset-credentials endpoint. Also requested in #15279 

### Actual behavior

The user is redirected to the first "valid redirect uri", which can't be controlled.

When "Valid Redirect URIs" are loaded they are put into a HashSet
See org.keycloak.models.utils.RepresentationToModel line 571
`resource.setRedirectUris(new HashSet<>(redirectUris));`

When loading the redirectUri, the first (with the lowest hash value) is set.
See org.keycloak.services.resources.LoginActionsService line 422
`redirectUri = RedirectUtils.getFirstValidRedirectUri(session, client.getRootUrl(), client.getRedirectUris());`

### How to Reproduce?

1. have a client with multiple "Valid Redirect URIs" and Base URL set
2. Go to {KEYCLOAK}/auth/realms/{REALM}/login-actions/reset-credentials?client_id={CLIENT_ID}
3. Enter email and receive a “reset password”-email with a link
4. Click link
5. Enter new password twice and submit
6. Get redirect to first "Valid Redirect URIs"

### Anything else?

The "Valid Redirect URIs" should only be used for validation and never for fallback.
They can contains wildcards (*) and therefore can be invalid URLs.
"Base URL" is a much better candidate for this.

**Comment by ssilvert** [comment]
I don't think this is a UI issue.  If the solution is to make the redirect URIs sortable then it will have an effect on the admin console, but I think the core team should first decide what action (if any) should be taken.

**Comment by pxnis** [comment]
> Duplicates #15279

Disagree. This issue is about the core problem of using validation strings as redirect URIs. 
#15279 is a feature request, which could be a (partial) solution. It is also linked in this original issue description.

**Comment by pxnis** [comment]
@mposolda thank you for your response. With it we have working solution. Another related bug has appeared though, which I have documented in #21127 

Though I believe that the core problem still persists.
It seems wrong to use unsortable validation strings as a fallback redirect URI. This should be the BaseUrl.

**Comment by mposolda** [comment]
@pxnis Well, the redirection should not happen at all in this case. In case of successful password-reset, there should be page displayed like "You restarted password" with the link to base URL.

**Comment by pxnis** [comment]
@mposolda 
That could be a solution.
It's just wrong to use unsortable validation strings as a fallback redirect.

**Comment by fregge** [comment]
@mposolda 
> This functionality is not documented and I think that the core issue is, that endpoint of LoginActionsService can be triggered directly from the user's application (which it should not be). So perhaps the follow-up issue might be to make sure that endpoint cannot be triggered directly (EG. reject calling the endpoint `{KEYCLOAK}/auth/realms/{REALM}/login-actions/reset-credentials?client_id={CLIENT_ID}` when authenticationSession doesn't exists).

This way you would make it impossible to have a static link for the password reset. Static links are often used in documentation, emails and so on. See also #7146 or Jira [KEYCLOAK-13202](https://issues.redhat.com/browse/KEYCLOAK-13202)

What would be the reason to stop this endpoint from being directly accessible? Is it insecure?
There is even a code comment in that endpoint that sounds as if it is intended to use the request as link in a client application.
https://github.com/keycloak/keycloak/blob/761929d1746c4d8445014a1124c27e9c07ca7725/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L378

**Comment by soulchild** [comment]
We need this as well to send out password reset links to new users by e-mail without having Keycloak "guess" the correct redirect URI.

**Comment by mposolda** [comment]
@fregge I am not sure what you mean by "static link" - is it the static URL like http://something/forget-password , which users are supposed to invoke when they want to reset-password page? If yes, the option is that you create such link for users to redirect to your application and then in your application, you would create redirect URL like I've mentioned here https://github.com/keycloak/keycloak/issues/20867#issuecomment-1589643819 with possibly generated "nonce" and "state" and "code_id" parameters.

The proper way to trigger reset-password is to trigger Keycloak via the endpoint I've mentioned above to make sure that whole OIDC flow is invoked instead of using the URL like `{KEYCLOAK}/auth/realms/{REALM}/login-actions/reset-credentials?client_id={CLIENT_ID}` . Note that trigger "reset password" via this URL is unsupported and can stop working anytime when we do some refactoring.

**Comment by mposolda** [comment]
I am raising the priority of this. I think that what we should do is to:

- Make it clear in the documentation how to directly invoke "forget password" and "registration" endpoint and that it should be done by the OIDC endpoint mentioned in my comment https://github.com/keycloak/keycloak/issues/20867#issuecomment-1589643819 . And make it clear that directly invoking `{KEYCLOAK}/auth/realms/{REALM}/login-actions/reset-credentials?client_id={CLIENT_ID}` is not supported
- Remove the automatic redirect to the first redirect URL and instead possibly show the info page and possibly the link `Back to application` on this info page. We can probably remove both methods `RedirectUtils.getFirstValidRedirectUri` entirely.

**Comment by fregge** [comment]
> @fregge I am not sure what you mean by "static link" - is it the static URL like http://something/forget-password , which users are supposed to invoke when they want to reset-password page? If yes, the option is that you create such link for users to redirect to your application and then in your application, you would create redirect URL like I've mentioned here [#20867 (comment)](https://github.com/keycloak/keycloak/issues/20867#issuecomment-1589643819) with possibly generated "nonce" and "state" and "code_id" parameters.

You can not always implement a custom endpoint in the any client. If you have only standard software without access to the code connected to keycloak and don't use the account console, or want to take the user directly to the password reset form for better user experience, the openid-connect/forgot-credentials endpoint is no option. You would always have to implement an additional micro application that does nothing else than redirecting to that openid-connect/forgot-credentials flow in these cases.

**Comment by soulchild** [comment]
I'm with @fregge here, having had exactly that use-case a couple of weeks ago. We migrated away from another IDP to Keycloak and had to send a mail to every user with a password reset link. Of course, we could have implemented that as a dedicated microservice, but it'd be nice if Keycloak provided this out of the box. Why not just have an additional `redirect_url` query parameter on the `reset-credentials` endpoint, which must match one of the client's allowed redirect URLs?

**Comment by mposolda** [comment]
@fregge @soulchild I see your point, but on the other hand the proper way to use Keycloak for authentication (or forget password, or directly open registration form) is to go through proper OIDC protocol endpoint and make sure that OIDC parameters with proper values are used. Endpoints on `LoginActionsService` are not meant to be directly invocable by users and doing that can have security implications (like you noticed) and can stop working anytime. 

Just a suggestion, that I think you can still create "static" URL as I've mentioned https://github.com/keycloak/keycloak/issues/20867#issuecomment-1589643819 as the "dynamic" parameters like `state` and `nonce` are not strictly required AFAIK per OIDC and OAuth2 specifications (especially if you ommit `scope=openid` but maybe even ommiting that is not needed).

**Comment by mposolda** [comment]
Just a note for the reference, that `redirect_uri` parameter was added to `reset-actions` GET endpoint. If `redirect_uri` parameter is not sent, it displays the info page after the successful password reset with the link `Back to application` for going to the client.

It is still encouraged to use `forget-credentials` endpoint as I've suggested above as I am not sure we continue supporting this `reset-actions` endpoint to be invoked from client applications and it is a chance that it will be deprecated/removed or updated in the future.

**Comment by soulchild** [comment]
Thanks for letting us know, @mposolda!

I tried your suggestion of using the `forget-credentials` endpoint and that somewhat works without the `nonce` and `state` parameters. There's still the `code_challenge` parameter, which must be specified (but can be empty) for this to correctly show the password reset form (without the empty `code_challenge` parameter you get the login form):

http://localhost:8080/realms/master/protocol/openid-connect/forgot-credentials?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadmin%2Fmaster%2Fconsole%2F%23%2Fmaster%2Frealm-settings%2Flogin&response_mode=fragment&response_type=code&scope=openid&code_challenge=

What are the implications of an empty `code_challenge` parameter?

There's still another problem preventing us from using the suggested approach: The link in the resulting password reset e-mail always leads to a "You're already signed in, back to application" dialog. I double-checked this by using `curl` on the command line to ensure there's no active session in my browser. It's not the missing `code_challenge` parameter either…

Any ideas? 🙏

**Comment by dscham** [comment]
Out of curiosity, how would you disable access to that URL @mposolda, other than using forgot-credentials endpoint instead? Is that feasible or wanted at all?

Anyway, I still don't see what's the security implication with using that without OIDC, even if you somehow saw @fregge  or @soulchild notice some ( where? ). 

F.e. in my use case, I need to use Keycloak to only communicate with a user federation to do a forgot password flow. No IDP, OAuth or OIDC functionality used there. No users logged in via Keycloak at all ( other than the occasional admin tasks and the hopefully short period until users reset their password ). Where's the harm in using `reset-actions` there? Other than Keycloak maybe being overkill for that. But that's what I got to do.
