### ISSUE TITLE
[Admin Console Realm Localization] Sort message list alphabetically by key

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#20876]
### Description

In the realm localization tab, the messages (key value pairs) are not sorted.
This makes it more difficult to spot a message key an admin is searching for.

Current state in 21.1.1: List isn't sorted: 

![image](https://github.com/keycloak/keycloak/assets/789496/5cb3925b-f07c-402a-be4f-8f9aea2fe1d2)

### Motivation

If keys are named with a prefix like in the screenshot above ("welcome") they should be displayed below each other.

### Details

Further improvement: "Add message bundle" should be named "Add message" because only one key value pair can be added not multiple ones (adding message bundle is a missing feature in the v2 console).

**Comment by ssilvert** [comment]
I agree with both points.  We should fix this.

**Comment by websterbeyond** [comment]
Sort option for all tables in general would be great. I have the same problem on attributes tab in user details page. If there are several keys with the same prefix, attributes can easily get mixed up.

**Comment by artur-baltabayev** [comment]
I provided a pull request.
