### ISSUE TITLE
KeycloakBuilder produces incomplete copy

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#20872]
### Description

Doing new KeycloakBuilder(keycloak).build() will fail to copy the spec.  I'm not sure of the exact cause - there may be some misconfiguration with the current annotations that have KeycloakSpec as a buildableRef, but it's not actually buildable.  However making KeycloakSpec Buildable didn't help.

This is not currently a problem, but does highlight it could be too easy for users creating the own pojos / CustomResource to get tripped up with the buildable aspect - too often the behavior seems is to silently fail, rather than build time or more proactive errors. 

It's been discussed with https://github.com/fabric8io/kubernetes-client/issues/5135 whether or not it makes sense to rely on builders even more internally in fabric8.  It seems like we may want to wait on that some more.  cc @metacosm

**Comment by metacosm** [comment]
Might be related to https://github.com/fabric8io/kubernetes-client/issues/2807.

**Comment by shawkins** [comment]
@metacosm appears to be the same issue as https://github.com/sundrio/sundrio/issues/393

The generic typing of the spec and status fields from an inherited class seems to confuse the builder logic - it understands that it needs to be there for the build method, but it doesn't for initializing.

I'll see if there is something that can be done in sundrio, but we've also talked in the past about removing the usage of customresource as an abstract class - that would help as well.

**Comment by shawkins** [comment]
Will be fixed when we pull in fabric8 client 6.8+

**Comment by shawkins** [comment]
Resolved with #26150
