### ISSUE TITLE
[Admin Console v2] Policy creation at Permissions screen missing

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#20884]
### Description

Console V1:
1. Policy can be created on the fly
2. User can navigate to the policy

**Console v2 v21.1.1 is missing these features:**
![image](https://github.com/keycloak/keycloak/assets/789496/f0f73bca-793a-4276-89c0-bb6f8db5020a)

**In console V1 they were available:**
![image](https://github.com/keycloak/keycloak/assets/789496/6126cf52-28ef-4512-8075-c2fd38ac73b0)

### Motivation

With console v2 a new policy has to be created beforehand at realm-management client, while it could just be created at the permissions screen before at console v1.

For reviewing a Permission it should be possible to navigate to the Policy which is selected for the Permission.

### Details

Feature proposal: 

- Allow to click on Policy to navigate to it
- Add "Create Policy" button or an option in the Policy selection dropdown
![image](https://github.com/keycloak/keycloak/assets/789496/665646ec-3772-4d78-a6fd-5184d8de697e)

**Comment by ssilvert** [comment]
The new console does leave out the ability to create a policy from the Permissions screen.  We should probably add that back in.

Defining permissions is awkward in both old and new consoles.  For instance, to set up a permission on a Group, you end up navigating away from the group you are working on and onto the `realm-management` client.  Then when you are done, you have no way to navigate back to the Group where you probably want to set another permission.  

Also, while you are setting up the permission in `realm-management` client, you don't see the name of the Group you are working on.  You just see the mysterious group id.

**Comment by jonkoops** [comment]
I quite like using [the footer](https://www.patternfly.org/v4/components/select#footer) of a select to add a link to create a new policy.
![image](https://github.com/keycloak/keycloak/assets/695720/2b77d6c5-8183-458e-8720-83c9066bc302)
