### ISSUE TITLE
Add Maven Build Cache Extension as opt-in feature

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#20882]
### Description

When implementing #16312, the plugin Maven Build Cache Extension couldn't be disabled by default and then re-enabled on the CLI for individual users. 

With version 1.0.1 being available, this is now possible: https://github.com/apache/maven-build-cache-extension/pull/37

Also Quarkus supports no Maven 3.9 https://github.com/quarkusio/quarkus/issues/31011

So this PR will add support for the cache extension.

**Comment by jonkoops** [comment]
@ahus1 is this something we can enable on CI as well?

**Comment by ahus1** [comment]
@jonkoops - Once we find a way to publish the `~/.m2/build-cache` to a static web server that hosts the content, that would be possible. The plugin's docs suggest WebDAV for this, which we don't one at hand AFAIK. There is also no integration with the GitHub actions based caches available except for a generic once which would cache the contents of that folder.

So I'd summarize it as "not simple", and would postpone it until we that the local builds show its value.

**Comment by jonkoops** [comment]
Perhaps we can add the `~/.m2/build-cache` directory to `actions/cache`? But yeah, perhaps we can log this as a separate issue?

**Comment by ahus1** [comment]
@jonkoops - yes, I'll log it as a follow-up issue once there is agreement to proceed with the linked PR. I don't want to open follow-up issues too early to avoid cluttering the backlog.

**Comment by ahus1** [comment]
@pedroigor / @stianst - I'd be happy if one of you could review this PR as you've been involved in the previous attempt #16312. It works good for me locally, and with opt-in I'd like to refine it in small iterations until we might benefit from it during regular CI runs. Thanks!
