### ISSUE TITLE
Keycloak cluster not cominig when i pass `imagePullSecrets` in CR

### ISSUE THREAD

**Issue by chethankumar4046** [keycloak/keycloak#20904]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

* I have create secret 
* And added secret in imagePullSecrets, 
But not working,  
apiVersion: v1
kind: Secret
metadata:
  namespace: keycloak
  name: secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |. acb

### Version

21.1.1

### Expected behavior

Should work without error even it image in private docker  registry with secured 

### Actual behavior

2023-06-10 04:54:40,670 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-104) Found config secrets names: []
2023-06-10 04:54:40,677 INFO  [org.key.ope.con.KeycloakDeployment] (ReconcilerExecutor-keycloakcontroller-104) Existing Deployment found, updating specs
2023-06-10 04:54:40,756 INFO  [org.key.ope.con.KeycloakController] (ReconcilerExecutor-keycloakcontroller-104) --- Reconciliation finished successfully

keycloak-0                          0/1     CrashLoopBackOff   2 (2s ago)    37s

### How to Reproduce?

Add imagePullSecrets in CR
imagePullSecrets:
  - name: myRegistrKeySecretName

### Anything else?

no

**Comment by andre-nascimento-rh** [comment]
@chethankumar4046 ,


Thank you for the report. Could you please add as detailed steps to reproduce as possible, such as: which K8s engine you're deploying and the content of your Keycloak descriptor file? 

That would help us tremendously with efficiently triaging and prioritizing this issue. 

Are you sure the Keycloak custom image is properly reachable?

Which content are you setting here?
`.dockerconfigjson: |. acb`

Thanks.

**Comment by mabartos** [comment]
@chethankumar4046 Can you please confirm if the issue still persists with the latest Keycloak version for you?
