### ISSUE TITLE
Account V3 missing delete account functionality

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#20901]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Delete account functionality missing from Account Console V3

### Version

main

### Expected behavior

See https://www.keycloak.org/docs/latest/server_admin/#proc-allow-user-to-delete-account_server_administration_guide

### Actual behavior

`Delete Account` missing from Personal Info section.

### How to Reproduce?

See https://www.keycloak.org/docs/latest/server_admin/#proc-allow-user-to-delete-account_server_administration_guide

**Comment by ssilvert** [comment]
This depends on #19683

**Comment by ssilvert** [comment]
See `deleteAccountAllowed` feature flag.

**Comment by Sieboldianus** [comment]
> See `deleteAccountAllowed` feature flag.

This feature flag is not listed here:
https://www.keycloak.org/server/features

And I could not start the container with it:

```
RUN /opt/keycloak/bin/kc.sh build --features="deleteAccountAllowed"
```
> ERROR [keycloak builder 4/4] RUN /opt/keycloak/bin/kc.sh build --features="deleteAccountAllowed"
