### ISSUE TITLE
Keycloak not renewing refresh token with scope 'offline_access' and revoke rfresh token enabled 

### ISSUE THREAD

**Issue by meveno** [keycloak/keycloak#20928]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

According to the documentation here ([offline-access](https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-access)), if you enable the Revoke Refresh Token option, you can use each offline token once only.
This behavior doesn't seem to work with the offline token. We want the offline/refresh token to be renewed along with the acess token in the case the user goes offline. We want the offline user to have the refresh token with the maximum validity we defined in the configuration.

Also we can see this log in the log :

```
2023-06-12 14:16:16,253 WARN  [org.keycloak.events] (executor-thread-489) type=REFRESH_TOKEN_ERROR, realmId=63ff9101-b65b-4c85-8248-615deba8fae3, clientId=web-pgc, userId=436f0d8c-fc97-4c3b-b510-f9270444a7b8, ipAddress=95.128.150.249, error=invalid_token, grant_type=refresh_token, refresh_token_type=Offline, refresh_token_id=0e23f09e-6426-4267-a6b1-feee369ceaba, client_auth_method=client-secret
```

### Version

 docker.io/bitnami/keycloak:21.1.1-debian-11-r8

### Expected behavior

The refresh token with scope offline_access is renewed each refresh of the access token

### Actual behavior

The refresh token with scope offline_access is not renewed until it expires

### How to Reproduce?

Auth2 login with keycloak adapter js with scope offline_access

**Comment by meveno** [comment]
After investigating a while, it seems that the refresh token is effectivelly renewed but the expiration date of the refresh token does not change.
Is there a way to have the expiration date of the offline token to be renewed after each refresk of the access_token ?
We want the user to have a offline session duuration of at least and at max of 14 days by using the refresh token.
Is there a way to do this ?

**Comment by rmartinc** [comment]
Hi @meveno !

The refresh token expiration for offline access is defined by the "Offline Session Idle" and "Offline Session Max" (the latter needs "Offline Session Max Limited" enabled). The refresh token will be issued until the idle or max time is reached, whatever comes first. So I think you have to enable max limited, and then set a max of 14 days. You can set the idle you want for your users.

As an example, if you set offline idle to 4m and max to 10m. A client that requests a new refresh token every 3 minutes would be:

0 -> refresh expires in 4m (idle)
3 -> refresh expires in 4m (idle)
6 -> refresh expires in 4m (idle / max)
9 -> refresh expires in 1m (max)

There have been a lot of activity in this area recently (see #14854 or #11990 for example). So please test first the [nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) before filing more issues.

**Comment by mposolda** [comment]
Adding to Backlog. This may not be a bug at all (looks rather like ask for help) and it's possible that this is fixed in latest Keycloak main anyway.

**Comment by meveno** [comment]
Thanks !
