### ISSUE TITLE
Add a validation of the generated crds

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#20936]
To ensure that we aren't experiencing regressions there should be some point (possibly in a downstream module or pipeline) where crd changes are compared to a known good copy.  The crd generator is still undergoing development and it would be best to minimize unanticipated changes.

_Originally posted by @andreaTP in https://github.com/keycloak/keycloak/issues/20866#issuecomment-1584574297_

**Comment by shawkins** [comment]
https://github.com/keycloak/keycloak/pull/20866#issuecomment-1607006386 - there are tags for both to previous releases and the nightly.  

You can check against the cumulative changes against the previous with something like:

git diff tags/21.1.1 tags/nightly kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
git diff tags/21.1.1 tags/nightly kubernetes/keycloaks.k8s.keycloak.org-v1.yml

These look good wrt to the changes that have been recently introduced.  There looks to be a little instability in enum ordering, and there are quite a few changes under the graph of the unsupported - presumably because we're picking up later fabric8 versions that have aligned with later k8 apis.  Since that is unsupported we probably don't need to document those specifics.

@vmuzikar is there anything more formal you want to do here wrt blessing / validating changes of the crd?

**Comment by vmuzikar** [comment]
@shawkins I like the idea, although I'm not sure how to properly tackle this other than comparing a generated CRD to an approved and manually maintained CRD in our testsuite. It's a bit PITA though, as we can see it with our tests for [help messages](https://github.com/keycloak/keycloak/tree/main/quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/dist/approvals/cli/help).

IMHO comparing with previously released CRDs is IMHO not ideal as it doesn't work well with expected changes.

Question is whether we really need to try and compare generated CRDs. What in the end users are concerned about is breaking changes. So maybe an alternative would be adding tests for actually upgrading the Operator/CRDs from the last released version to see if existing CRs are compatible with generated CRDs. This would help us with identifying any truly unwanted changes.

**Comment by shawkins** [comment]
> So maybe an alternative would be adding tests for actually upgrading the Operator/CRDs from the last released version to see if existing CRs are compatible with generated CRDs. This would help us with identifying any truly unwanted changes.

My understanding is that the server will continue to serve the stored version even if the crd is changed.

My main concerns wrt to crd generation are:
- erroneous generated content, such as the enum issue (which still exists to some extent, see the stableIndex values, until the next fabric8 release is picked up).  This could be considered a messy cometic issue - if someone were to try and create a resource with that erroneous content, it would validate, but the operator would then throw an exception on deserialization. 
- missing generated content - if there is a regression or bug with the crd generator, we need to know if something has inappropriately been dropped.  If a change like this were to occur the affected parts of an existing CR would fail to validate once the resource were updated.

More subtle breaking changes are certainly possible via generation, but that would likely require a change in the typing of a particular property.  We'd need the last version's object model or crd and a representative enough CR (we could probably come with a way to auto-fill non-defaults) and modify the mapper used by Serrialization (or in later releases by KubernetesSerialization) to set ALLOW_COERCION_OF_SCALARS, then we could cross check for this.

Related to this is that the crd object model currently does not employ additionalProperties - if there is ever a concern that round tripping a newer cr is possible via an older object model, additionalProperties will preserve content that would otherwise be lost.

**Comment by vmuzikar** [comment]
> My understanding is that the server will continue to serve the stored version even if the crd is changed.

Yes but if I understand correctly, that [does not come for free](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#overview). Existing CRs need to be served at both old and new CRD versions (during the "migration period" when new and old versions co-exist). If there are breaking changes in the schema of the new CRD (and there are no conversion webhooks in place), we have a problem. In such case, OLM even refuses to upgrade the Operator, IIRC. But this concerns introducing a new CRD version.

What we're talking here about is making unintentional breaking changes to an existing CRD version. But similar logic applies here. If there are unintentional breaking changes, the API server will complain when updating the CRD, AFAIK. Correct?

> My main concerns wrt to crd generation are:
> 
> * erroneous generated content, such as the enum issue (which still exists to some extent, see the stableIndex values, until the next fabric8 release is picked up).  This could be considered a messy cometic issue - if someone were to try and create a resource with that erroneous content, it would validate, but the operator would then throw an exception on deserialization.

Shouldn't this be caught by our existing RealmImport CR tests that are using quite an [extensive CR](https://github.com/keycloak/keycloak/blob/bdb4dd807099e6cd6c622cf9c91ce88377d70618/operator/src/main/resources/example-realm.yaml) with more or less all fields used?

> * missing generated content - if there is a regression or bug with the crd generator, we need to know if something has inappropriately been dropped.  If a change like this were to occur the affected parts of an existing CR would fail to validate once the resource were updated.

That's my main concern as well. Since the API server prunes any unknown fields in CRs, this wouldn't be caught by existing tests.

**Comment by shawkins** [comment]
> But this concerns introducing a new CRD version.

No my main concern here is about the situation where you have an existing CRD then update it.  The api server will mostly continue to serve the old stored version of the resource - as I understand it, it won't be revalidate until you try to change the resource.

intra-version crd changes will happen with fabric8 upgrades, object model changes (including changing the crd annotations), or we have now seen a couple of instances of non-deterministic behavior with the crd generator.  For object model changes I've been validating what's generated with every change, but it seems worth discussing if there's something more formal that would help.

> If there are unintentional breaking changes, the API server will complain when updating the CRD, AFAIK. Correct?

The behavior I see locally is that when you drop a field in a crd, it will be omitted from existing resources when you fetch them again.  However if you change the type of the field, it will continue to serve the existing resource - with the mismatched field.

> Shouldn't this be caught by our existing RealmImport CR tests that are using quite an [extensive CR](https://github.com/keycloak/keycloak/blob/bdb4dd807099e6cd6c622cf9c91ce88377d70618/operator/src/main/resources/example-realm.yaml) with more or less all fields used?

That wouldn't catch erroneous CRD content because it won't be part of the reference CR, but like I say that's mostly a cosmetic concern.

> That's my main concern as well. Since the API server prunes any unknown fields in CRs, this wouldn't be caught by existing tests.

If you feel good about how representative the RealmImport CR is then a round-trip test would help.

**Comment by shawkins** [comment]
Based upon our side conversation if we add round-tripping integration tests with CRs that we feel are relatively complete, then we should feel good that we'll find out early if anything has been dropped.  I'll look to add something like that to the test to resolve this issue.

There is already another on actual version migration #11873 and we won't worry about erroneous content just yet.
