### ISSUE TITLE
Cookie issue "state parameter invalid"

### ISSUE THREAD

**Issue by oliveryasuna** [keycloak/keycloak#20938]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

We use Keycloak 17 (also can be reproduced with latest Keycloak 21.1.1), specifically `keycloak-servlet-filter-adaptor:17.0.1`. Periodically, users will log out and log in to a different account and the state cookie is wrong, therefore, returning a 400 response. Relevant code are lines 253-258 in `OAuthRequestAuthenticator`.

I can reproduce the issue with two browser windows/tabs (Chrome). Our flow works such that the user enters their email, clicks a button, and on the next screen enters their password.
1. On window 1, enter an email and click the button.
2. On window 2, enter an email and click the button.
3. On window 1, enter the password and click the button.
4. Response will be a 400, however, the user is still authenticated.

While the reproducible example requires two browser windows, we periodically see this error when users logout/login on the same window. Also, this can be reproduced using the same email.

It seems that the second request changes the state cookie used by the first request.

### Version

17.0.1
21.1.1

### Expected behavior

The filter handles the requests properly.

### Actual behavior

Please see above.

### How to Reproduce?

Please see above.

**Comment by sschu** [comment]
@oliveryasuna Can you please check if the issue also happens in the latest version?

**Comment by sschu** [comment]
Since this issue affects adapter and they are going to be deprecated (see https://www.keycloak.org/2023/03/adapter-deprecation-update), I don't think this will have a high priority. So if you can provide a PR, that would be welcome.

**Comment by mposolda** [comment]
+1 to what @sschu mentioned.

**Comment by jonkoops** [comment]
Closing this issue since it affects only soon to be removed and deprecated areas of Keycloak. Still feel free to submit a fix if you are so inclined.
