### ISSUE TITLE
Partial Import is not working for resource Type in keycloak 21.1.1

### ISSUE THREAD

**Issue by Roma110** [keycloak/keycloak#20947]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

In keycloak (21.1.1), when we are trying to do Partial import of sample json then we are getting resource type null/blank .
[sample.txt](https://github.com/keycloak/keycloak/files/11731492/sample.txt)

Please find the below image:
![sceenshot](https://github.com/keycloak/keycloak/assets/28138074/79fc4ffb-2c67-4981-a6d8-6ce3f29517cb)

And in old keycloak (19.0.3) , resource type is coming properly.
![oldkeycloak](https://github.com/keycloak/keycloak/assets/28138074/073e448e-c2e5-4213-95ff-ec13c97352da)

### Version

21.1.1

### Expected behavior

![oldkeycloak](https://github.com/keycloak/keycloak/assets/28138074/073e448e-c2e5-4213-95ff-ec13c97352da)

As seen in above picture, resource type should come in latest version of keycloak when we execute partial import.

### Actual behavior

![sceenshot](https://github.com/keycloak/keycloak/assets/28138074/79fc4ffb-2c67-4981-a6d8-6ce3f29517cb)

Resource type is coming null in latest keycloak 21.1.1.

### How to Reproduce?

In latest keycloak, Go to realm setting ---> Action -----> Partial import 
Give some sample json of some set of users. 
Go to Events ----> Admin Events and check the resource type.

**Comment by vramik** [comment]
Thanks @Roma110 for the report, could you please check whether is was working in previous version? AKA, is this issue a regression or should it be considered as enhancement?

**Comment by Roma110** [comment]
We have check keycloak 19.0.3 wildfly distribution , while doing partial import we are able to see resource type in admin event but in keycloak 21.1.1 while doing partial import we are not able to see resource type and its coming as null.
