### ISSUE TITLE
Account V3 missing Internationalization functionality

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#20941]
### Description

Need to add features associated with feature flag `isInternationalizatioinEnabled`.

For details, see how this flag is used in Account V2.

**Comment by ssilvert** [comment]
This depends on https://github.com/keycloak/keycloak/issues/19683

**Comment by jonkoops** [comment]
@edewit We can also inject it into the environment variables of the FreeMarker template instead.

**Comment by ssilvert** [comment]
@edewit @jonkoops I just noticed that we have a bigger problem.  The locale attribute doesn't work in admin console with User Profile enabled.  And we will need to figure out a way to fix that, plus get it working with User Profile in account console.

If User Profile is disabled for the realm, you can see the user's locale setting in admin console at Users --> _username_ --> Attributes.

But if User Profile is enabled, you can't see the user's locale at all in admin console.

I think the question is, do we consider the user's locale to be a regular attribute that appears with username/email/firstname/etc. ?  Or, do we treat it differently, perhaps putting a locale selector in the masthead?

**Comment by pedroigor** [comment]
@ssilvert @edewit Sent https://github.com/keycloak/keycloak/pull/21164.
