### ISSUE TITLE
Hostname is not processed correctly when accepting HTTP/2 requests in KC_PROXY=edge mode

### ISSUE THREAD

**Issue by wadahiro** [keycloak/keycloak#20959]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

As commented in discussion https://github.com/keycloak/keycloak/discussions/12028#discussioncomment-6158423, there is a case where hostname is not processed correctly when using HTTP/2 requests in `KC_PROXY=edge` mode.

This problem occurs when AWS Application Load Balancer (ALB) is deployed as a load balancer in front of Keycloak and HTTP/2 is used from ALB to the keycloak.

The cause is that the ALB and Keycloak (Quarkus) sides have the following behaviour.

- ALB: Even if it is an HTTP/2 request, the `host` header is given and the `:authority` header is **not** given (Also `X-Forwarded-Host` is not given, whether HTTP/2 or HTTP/1.1 is used).
- Keycloak (Quarkus): if an HTTP/2 request is accepted, it will resolve to `0.0.0.0` even if the `:authority` header is not present but the `host` header is.

As a result, the value of the OIDC Configuration Endpoint's issuer, for example, will be `https://0.0.0.0/realms/master`, and Keycloak does not work correctly.

Note: The `:authority` header is mentioned in the [HTTP/2 specification](https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2.3) as:

> Clients that generate HTTP/2 requests directly SHOULD use the :authority pseudo-header field instead of the Host header field.

As it is not mandatory with `SHOULD`, it would be desirable if Keycloak (Quarkus) side implemented a fallback process for case where the `:authority` header is not present but the `host` header is.

### Version

21.1.1

### Expected behavior

If `:authority` header is not present in an HTTP/2 request and `host` header is present, the hostname is resolved with the value of the `host` header. For example, accessing the OIDC Configuration Endpoint with the header `hostname: keycloak.example.com` returns the following issuer:

```
"issuer":"https://keycloak.example.com/realms/master"
```

### Actual behavior

The `host` header is not referenced and the hostname is resolved with `0.0.0.0` as follows:

```
"issuer":"https://0.0.0.0/realms/master"
```

### How to Reproduce?

It is difficult to send an HTTP/2 request without `:authority` header; using libraries such as Java standard HttpClient, Jetty or Vert.x will always automatically add the `:authority` header.
To simplify reproduction, I have wrote reproduction code that sends the binary data of an HTTP/2 request without `:authority` header. This can be used to reproduce the following steps:

1. Start keycloak with `KC_PROXY=edge` mode:

```
docker run -it --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_PROXY=edge -e "JAVA_OPTS_APPEND=-Dquarkus.http.access-log.enabled=true -Dquarkus.http.access-log.pattern=long" quay.io/keycloak/keycloak:21.1.1 start-dev
```

2. Run the following Java program to send an HTTP/2 request without the `:authority` header to localhost:8080

```
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.net.SocketTimeoutException;

public class HTTP2Request {

    public static void main(String[] args) throws IOException {
        String host = "127.0.0.1";
        int port = 8080;

        Socket socket = new Socket(host, port);
        socket.setSoTimeout(1000);

        OutputStream outputStream = socket.getOutputStream();
        InputStream inputStream = socket.getInputStream();

        // HyperText Transfer Protocol 2
        //    Stream: Magic
        //        Magic: PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n
        //    Stream: SETTINGS, Stream ID: 0, Length 18
        //        Length: 18
        //        Type: SETTINGS (4)
        //        Flags: 0x00
        //        0... .... .... .... .... .... .... .... = Reserved: 0x0
        //        .000 0000 0000 0000 0000 0000 0000 0000 = Stream Identifier: 0
        //        Settings - Header table size : 0
        //        Settings - Enable PUSH : 0
        //        Settings - Initial Windows size : 2147483647
        //    Stream: WINDOW_UPDATE, Stream ID: 0, Length 4
        //        Length: 4
        //        Type: WINDOW_UPDATE (8)
        //        Flags: 0x00
        //        0... .... .... .... .... .... .... .... = Reserved: 0x0
        //        .000 0000 0000 0000 0000 0000 0000 0000 = Stream Identifier: 0
        //        0... .... .... .... .... .... .... .... = Reserved: 0x0
        //        .111 1111 1111 1111 0000 0000 0000 0000 = Window Size Increment: 2147418112
        //    Stream: HEADERS, Stream ID: 3, Length 115, GET /realms/master/.well-known/openid-configuration
        //        Length: 115
        //        Type: HEADERS (1)
        //        Flags: 0x05, End Headers, End Stream
        //        0... .... .... .... .... .... .... .... = Reserved: 0x0
        //        .000 0000 0000 0000 0000 0000 0000 0011 = Stream Identifier: 3
        //        [Pad Length: 0]
        //        Header Block Fragment: 208204a262c28e8a50c523424b630bf82d142dd6a3f8a983d65a8d22c43d529a6b6c1a4c…
        //        [Header Length: 227]
        //        [Header Count: 8]
        //        Header table size update
        //        Header: :method: GET
        //        Header: :path: /realms/master/.well-known/openid-configuration
        //        Header: :scheme: http
        //        Header: host: keycloak.example.com
        //        Header: x-forwarded-port: 443
        //        Header: x-forwarded-proto: https
        //        Header: user-agent: Java-http-client/17.0.3
        String magicSettingsWindowUpdateFrame = "505249202a20485454502f322e300d0a0d0a534d0d0a0d0a00001204000000000000010000000000020000000000047fffffff0000040800000000007fff0000";
        String headersFrame = "000073010500000003208204a262c28e8a50c523424b630bf82d142dd6a3f8a983d65a8d22c43d529a6b6c1a4c7abf860f178fea5f44a0e3eab97c8e9ae82ae43d3f008cf2b4a7b3c0ec90b22d59ec4f03343433008df2b4a7b3c0ec90b22d5d8749ff849d29ad1f0f2b91ca3ee35a74a6b589418b52580bab81767f";

        byte[] data = hexStringToByteArray(magicSettingsWindowUpdateFrame + headersFrame);

        // Send HTTP/2 request
        outputStream.write(data);
        outputStream.flush();

        // Dump response
        byte[] buffer = new byte[1024];

        try {
            while (true) {
                int bytesRead = inputStream.read(buffer);
                System.out.print(new String(buffer, 0, bytesRead));
            }
        } catch (SocketTimeoutException e) {
        }

        socket.close();
    }

    private static byte[] hexStringToByteArray(String hexString) {
        int length = hexString.length();
        byte[] data = new byte[length / 2];
        for (int i = 0; i < length; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hexString.charAt(i), 16) << 4)
                    + Character.digit(hexString.charAt(i + 1), 16));
        }
        return data;
    }
}
```

This program accesses the OIDC Configuration Endpoint. It dumps the response result to stdout so that `"issuer": "https://0.0.0.0/realms/master"` is output and reproduction can be checked.

Also, in the logs on the Keycloak side, it can be confirmed that the wrong host name resolution is made with `host: 0.0.0.0` as shown below, as the Quarkus access log is enabled in this reproduction procedure.

```
2023-06-13 09:07:02,463 INFO  [io.quarkus.http.access-log] (executor-thread-0)
GET /realms/master/.well-known/openid-configuration HTTP/2
x-forwarded-port: 443
x-forwarded-proto: https
user-agent: Java-http-client/17.0.3
host: 0.0.0.0
```

**Comment by andre-nascimento-rh** [comment]
Hello, @wadahiro ,


Thanks for your efforts and well detailed investigation.

- Do you know If this issue only happens when setting "proxy=edge"? Does it also happen when setting "proxy=passthrough" or "proxy=reencrypt"?

- Does this issue happen If you start the server like this `kc.sh start --hostname=...`, setting the `hostname` options?

- Would it be also possible to reproduce the error with a simple local Ngnix with `HTTP/2` enabled?


Thanks.

**Comment by mabartos** [comment]
@wadahiro Can you please confirm if the issue still persists with the latest Keycloak version for you?

**Comment by fh-yuxiao-zeng** [comment]
Hi @mabartos, I can confirm this is an issue for version 22.0.3. I specified the `hostname` option (via environment variable `KC_HOSTNAME`).

**Comment by shawkins** [comment]
I can confirm what @fh-yuxiao-zeng is reporting, this also occurs with hostname set, and when using passthrough.  

However looking at the more spec link is https://www.rfc-editor.org/rfc/rfc9113.html#section-8.3.1-1 the language has changed from SHOULD to MUST.  So direct http/2 requests are expected to have authority set.

The only case where is seems possible for this to happen is if there is an incoming http/1.1 request, such that there is no authority, that is turned into a http/2 request by the proxy - which doesn't seem to match this scenario.

**Comment by shawkins** [comment]
@mabartos @andre-nascimento6791 @wadahiro @cescoffier @vietj given the update in the http/2 spec this seems like an issue for AWS ALB.  Should this issue be resolved or converted to an enhancement request to support non-compliant http/2 requests?

**Comment by vmuzikar** [comment]
@shawkins Not much we can do on Keycloak's end anyway. I'd say let's close this and open an issue in Vert.x for them to decide if they want to support nonstandard requests.

**Comment by vietj** [comment]
nothing is said in the spec when authority is missing but host header is present as far as I understand
