### ISSUE TITLE
Update user via rest-api updates it even the same data is requested

### ISSUE THREAD

**Issue by cuberinooo** [keycloak/keycloak#20988]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

We are using keycloak-config-cli to add some configs and standard user to the keycloak. At the beginning of each deployment the keycloak-config-cli starts as job and adds the standard user. It makes an put request to the following uri: "../auth/admin/realms/<realm>/users/<userId>". Whenever we make a change to the keycloak chart or lets say whenever we deploy a new version of keycloak the keycloak-config-cli run its config files to add the called users. This means on each deployment a put request is called even when the user already exists. What keycloak does is, it updates the user even when the same data is requested. So far so good, but this logic makes hard to add the password policy "passwordhistory" on keycloak. On the put request of keycloak-config-cli we also provide the credentials of the users. Updating the user with the same password twice while the "passwordhistory" password-policy is active won`t work. A message "could not update user" will be received. 

### Version

20.0.5

### Expected behavior

Im not 100% certain of what the behavior in general should look like but updating the user with the same data should not update it. Normally it should only update the diffs. 

### Actual behavior

Updating a user via rest-api updates the user even when the same data is requested

### How to Reproduce?

In keycloak: activate password-policy "passwordhistory"
put request to "../auth/admin/realms/<realm>/users/<userId>" with credentials and call it twice. The second call will response with "could not update" due to passwordhistory that you can not update the same password twice.

**Comment by douglaspalmer** [comment]
This sounds like correct behaviour to me. The reason to maintain a password history is to prevent users from reusing a password. When password history isn't enabled then users are free to reuse passwords.

**Comment by cuberinooo** [comment]
@douglaspalmer the passwordhistory works fine and the logic behind that makes sense. What Im issueing here is that the rest api for updating a user does not do what you would normally expect. A user should not be updated when the exact same data is requested. As far as I know the correct behaviour for this would be to update only the difference between what is persisted and what is passed.

**Comment by Guite** [comment]
The issue appears if you automate user imports (e.g. using keycloak-config-cli). Unless you just rotated your secrets, existing users will always be re-imported / updated using the old existing credentials. This would be a use case where it is considered valid reusing the old password. This won't work together with the password history of course. We are open for any suggestions about how to approach this issue.
