### ISSUE TITLE
Performance degradation after Quarkus 3 upgrade related issues

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#20980]
### Description

This is serving as an umbrella issue to collect all the reported issues regarding the performance degradation after the recent Quarkus 3 upgrade.

List of the reported issues:

- [ ] https://github.com/keycloak/keycloak/issues/20448
- [x] https://github.com/keycloak/keycloak/issues/20954

**Comment by abstractj** [comment]
@keycloak/cloud-native do we know if this happened after the upgrade to 3.1.1.Final?

**Comment by abstractj** [comment]
@mabartos this may, or may not be related to the issues you've been investigating https://github.com/keycloak/keycloak/issues/21132. Adding it here for awareness.

**Comment by stianst** [comment]
Closing as we don't need a combined epic for the two linked issues, as they are completely independent issues.
