### ISSUE TITLE
User attributes are not updated when a user performs an account linking

### ISSUE THREAD

**Issue by lme-atolcd** [keycloak/keycloak#20998]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

identity-brokering

### Describe the bug

We added an OIDC Identity Provider with `syncMode=force`.
Each time a user authenticates with this Identity Provider, user attributes are updated with informations provided by the Identity Provider (as expected with `syncMode=force`).
But if a user attempts to link his account to this Identity Provider from the account console, user attributes are **not** updates, even if syncMode is set to "force".

### Version

21.1.1

### Expected behavior

User attributes **are** updated when a user links is account to an Identity Provider with `syncMode=force`.

### Actual behavior

User attributes are **not** updated when a user links is account to an Identity Provider with `syncMode=force`.

### How to Reproduce?

1. create an OIDC Identity Provider with `syncMode=force`
2. log in the account console with a local Keycloak user
3. go to the "Account security > Linked accounts" page
4. use the "Ling account" link to link the user account to the created Identity Provider
5. back to Keycloak, the account is linked but user attributes are **not** updated

**Comment by pedroigor** [comment]
Should be fixed by https://github.com/keycloak/keycloak/pull/20965.
