### ISSUE TITLE
admin-cli Capability config section has not responding to Save

### ISSUE THREAD

**Issue by a-forghani-y79** [keycloak/keycloak#21000]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

hi ever body.
at first thanks for your efforts.
i found problem in admin ui. 
in the clients' page, when i try to change Capability config of admin-cli client, if i change Capabilities and save changes, i couldn't see any response or messages. 
for successful saving, i should revert changes then save again. 

### Version

21.1.1

### Expected behavior

save Capability configs for admin-cli at the first try.

### Actual behavior

no responding and no messages will be shown at first try, until you revert chnages and save it again.

### How to Reproduce?

just run keyCloak in development mode.

**Comment by edewit** [comment]
it's because there are validation errors the `Backchannel logout URL is not a valid URL`

**Comment by rhinoman** [comment]
I was able to workaround this by clicking the 'revert' button followed by 'save' once.  I then could save my changes to admin-cli normally.
