### ISSUE TITLE
When i make update password as default action, I am getting an issue while registration

### ISSUE THREAD

**Issue by syama-aot** [keycloak/keycloak#21003]
### Description

 I am getting update password page again. How can i avoid that. Thanks in advance for your help

**Comment by jonkoops** [comment]
I am sorry, but this is not an issue. If you have a question, I recommend you start [a discussion](https://github.com/keycloak/keycloak/discussions/categories/q-a) instead.

I would also recommend reading ["How do I ask a good question?"](https://stackoverflow.com/help/how-to-ask), as the better you formulate your question, the more likely you are to get an answer.
