### ISSUE TITLE
client auth by jwt

### ISSUE THREAD

**Issue by kfox1111** [keycloak/keycloak#21011]
### Description

I'd like to be able to authenticate a client by jwt rather then client secret. The client config would have a discovery endpoint specified along with a valid subject and audience that would be allowed to be that client.

### Motivation

For some systems like Kubernetes, workloads can be given projected jwt's signed by the Kubernetes cluster and kept up to date automatically. If this token could be used as the client secret, then no manual secret handling would have to be done, making the overall system much more secure.

Other systems that could do similar things include gitlab, github and spire.

**Comment by sschu** [comment]
There is a standard around client authentication via JWT and Keycloak supports this, see https://www.keycloak.org/docs/latest/securing_apps/#client-authentication-with-signed-jwt including dynamic lookup of the client public key.
Does that work for you?

**Comment by kfox1111** [comment]
I think that is exactly what I was looking for. Thanks! :)

**Comment by kfox1111** [comment]
Actually, there is one thing I'm not sure how to handle with this. Anyone on the kubernetes cluster (or gitlab, spire, etc) can request projected tokens. So there needs to be a list of subjects that are allowed to become the client. Is there any way to do that currently?

**Comment by sschu** [comment]
The spec says that the `sub` claim must be the client_id of the client, see https://datatracker.ietf.org/doc/html/rfc7523#section-3. So I hope your issuer puts a value in the `sub` claim according to who requested the token and then you just have to create clients with according IDs in Keycloak.

**Comment by kfox1111** [comment]
In Kubernetes, the subject is the <namespace>:<serviceaccountname> of the workload and its not configurable. :/ Other systems making jwts have similar restrictions on the name being generated automatically. 

I see that the RFC requires it to be what is expected, but maybe it would be ok to make that configurable anyway due to the changing nature of how jwt's are generated?

**Comment by sschu** [comment]
What is the : of the workload? And if you want to make something configurable, I think it should be made configurable in K8s so it conforms to a spec and not to make Keycloak support something that is outside the spec.

**Comment by kfox1111** [comment]
For security reasons, the subject of the jwt is always the namespace:serviceaccount of the pod thats requesting the jwt. This guarantees no pod is asking for a subject that isn't them. This isn't something easily changed in Kubernetes.

gitlab works similarly but in the case of gitlab, the sub related to the project and branch the job is running on: https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html#token-payload
Its also not configurable.

Github seems to be a little more configurable, allowing you to specify some of the properties of which to build your sub. but not fully configurable either:
https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-subject-claims-for-an-organization-or-repository

So, being able to set up a list in Keycloak would be much easier to deal with then try and make all the sources of oidc clients configurable and deal with all the rbac stuff that would be needed to get there. github is also not open source, so no idea if they would even consider it.

**Comment by sschu** [comment]
Why don't you create your client so they follow the naming scheme of namespace:serviceaccount?

**Comment by kfox1111** [comment]
Thats crazy enough that it might just work. :)

Will give it a try and let you know if it doesn't work.

Thanks! :)

Kevin
