### ISSUE TITLE
Cannot delete user custom attribute

### ISSUE THREAD

**Issue by quanguyenka** [keycloak/keycloak#21017]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

S1: Click User
S2: Select existed User
S3: Click on Tab "Attribute"
S4: Enter key and value
S4: Click Button "Save"
S5: Click Button "-" 
S6: Click Button "Save"
Result: Show message "The user has been saved" but the attribute not be deleted

Using CLI: ./kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin
./kcadm.sh update users/{id} -r {realm} -s attributes.myAttribute=value

Result: Not show any error but the attribute still exist

### Version

21.0.1

### Expected behavior

Custom attribute have to delete

### Actual behavior

Custom attribute has not been deleted

### How to Reproduce?

Have not

### Anything else?

á

**Comment by edewit** [comment]
This is already fixed, can you try the nightly to confirm that?

**Comment by jonkoops** [comment]
Thanks for verifying this, I am gonna go ahead an close this issue.
