### ISSUE TITLE
Fail to build due to arquillian test suite

### ISSUE THREAD

**Issue by kamalhusEphesoftGit** [keycloak/keycloak#21014]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

The bug occurs when running an install build of the latest keycloak code base.  All items compile up to the following point:

[INFO] Keycloak Arquillian Integration TestSuite - Cache Server SUCCESS [  0.035 s]
[INFO] Keycloak Arquillian Integration TestSuite - Cache Server - Infinispan SUCCESS [  0.043 s]
[INFO] Keycloak Arquillian Integration TestSuite - Cache Server - Legacy SUCCESS [  0.072 s]
[INFO] Tests .............................................. SUCCESS [  1.163 s]
[INFO] Base TestSuite ..................................... FAILURE [  2.701 s]

The message at the end of the failed build is:

[ERROR] Failed to execute goal on project integration-arquillian-tests-base: Could not resolve dependencies for project org.keycloak.testsuite:integration-arquillian-tests-base:jar:999.0.0-SNAPSHOT: The following artifacts could not be resolved: org.keycloak.testsuite:in
tegration-arquillian-servers-app-server-wildfly:jar:999.0.0-SNAPSHOT (absent): org.keycloak.testsuite:integration-arquillian-servers-app-server-wildfly:jar:999.0.0-SNAPSHOT was not found in https://s01.oss.sonatype.org/content/repositories/snapshots/ during a previous at
tempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :integration-arquillian-tests-base

I have built the testsuite as documented in the instructions and did not have an issue.  

### Version

Latest Git Clone as of 6/13/2023

### Expected behavior

Expected behavior is a successful compile, test and creation of a distribution zip.

### Actual behavior

Error Message on Build:

[ERROR] Failed to execute goal on project integration-arquillian-tests-base: Could not resolve dependencies for project org.keycloak.testsuite:integration-arquillian-tests-base:jar:999.0.0-SNAPSHOT: The following artifacts could not be resolved: org.keycloak.testsuite:in
tegration-arquillian-servers-app-server-wildfly:jar:999.0.0-SNAPSHOT (absent): org.keycloak.testsuite:integration-arquillian-servers-app-server-wildfly:jar:999.0.0-SNAPSHOT was not found in https://s01.oss.sonatype.org/content/repositories/snapshots/ during a previous at
tempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :integration-arquillian-tests-base

### How to Reproduce?

All instructions were followed:

git clone https://github.com/keycloak/keycloak.git
cd keycloak

mvn clean install  --> This produced an error on the Quartas test

Followed it following command to try to bypass all tests to get a clean build
[KeyCloak_BuildError_06142023.docx](https://github.com/keycloak/keycloak/files/11749853/KeyCloak_BuildError_06142023.docx)

mvn clean install  -DskipTestSuite=true -DskipTests=true -DskipITs=true -Pdistribution

The following was also run prior to the command above:

    cd $KEYCLOAK_SOURCES
    mvn clean install -DskipTests=true
    cd distribution
    mvn clean install -Dskip

$KEYCLOAK_SOURCES was empty prior to running - not sure what this should be set to so left alone.

### Anything else?

I was able to test the server locally where I built it using the following which seemed to be work implying that the build was successful. 

mvn -f testsuite/utils/pom.xml exec:java -Pkeycloak-server

 I just need to package this up for deployment to other servers.

Thank you for the support

**Comment by ahus1** [comment]
This no longer fails as those artifacts exist on the Sonatype repository now. 

To avoid download the artifacts from the Sonatype repository, add the profile `distribution` my calling `mvn clean install -DskipTests=true -Pdistribution`. 

I created a follow-up task #25892 to look deeper into this. 

To just build the Quarkus distribution, consider building it using `./mvnw clean install -DskipTests -am -pl quarkus/dist`
