### ISSUE TITLE
Change Slovak message (time format) when user is requested to change password

### ISSUE THREAD

**Issue by Azarchaniel** [keycloak/keycloak#21035]
### Description

Hey.

When user is requested to change password and the realm language is Slovak, he gets following email:
![image](https://github.com/keycloak/keycloak/assets/20816011/d8b6d89c-fc01-457b-a1eb-e5335c7f779e)

As you can see in highlighted area, he gets the time window in minutes, instead of 7 days, which is very unfriendly. But when he gets the same message in Czech lang., it is formatted correctly.

![image](https://github.com/keycloak/keycloak/assets/20816011/4bfcf4c7-c539-4331-80e1-4baaf25be62a)

### Motivation

We wants this time information looks more friendly and easier. 7 days is clear time, 10080 minutes looks weird and almost like an error.

### Details

We took the Czech translation as an example and changed the message bundles in Slovak lang.
`executeActionsBody=Váš administrátor práve požiadal o aktualizáciu vášho účtu {2} vykonaním nasledujúcich akcií: {3}. Kliknutím na odkaz uvedený nižšie spustíte tento proces.\n\n{0}\n\nTento odkaz vyprší za {4}.\n\nAk si nie ste vedomý, že váš adminstrátor o toto požiadal, ignorujte túto správu a nič bude zmenené.`
`executeActionsBodyHtml=<p>Váš správca práve požiadal o aktualizáciu vášho účtu {2} vykonaním nasledujúcich akcií: {3}. Kliknutím na odkaz uvedený nižšie spustíte tento proces.</p><p><a href="{0}&theme_config_url=https://skin.app.test.ydealcloud.cz/api"> Odkaz na aktualizáciu účtu </a></p><p> Platnosť tohto odkazu uplynie do {4}.</p><p> Ak si nie ste vedomí, že váš adminstrátor o toto požiadal, ignorujte túto správu a nič sa nezmení.</p>`

[Here is current Slovak translation.](https://github.com/keycloak/keycloak/blob/808988fe20103a7a625f141ec67698345b4b8277/themes/src/main/resources-community/theme/base/email/messages/messages_sk.properties#L16)

We changed `Platnosť tohto odkazu uplynie do {1} minúty.` to `Platnosť tohto odkazu uplynie do {4}.` as it is in [Czech translation](https://github.com/keycloak/keycloak/blob/808988fe20103a7a625f141ec67698345b4b8277/themes/src/main/resources-community/theme/base/email/messages/messages_cs.properties#LL16C237-L16C281).

If you are OK with this change, I can create PR later.

**Comment by jonkoops** [comment]
@Azarchaniel thanks for the bug report. We always appreciate a pull request, so feel free to create a fix!

**Comment by drichtarik** [comment]
Should not this one be closed? @Azarchaniel was it fixed by https://github.com/keycloak/keycloak/pull/21037 ?

**Comment by drichtarik** [comment]
@Azarchaniel Can you please have a look maybe this got forgotten to be closed after your PR was merged?

**Comment by donarus** [comment]
Hi, I’ll look at it instead of @Azarchaniel tommorow afternoon (CET) and let you know.

**Comment by donarus** [comment]
@drichtarik we can close it
