### ISSUE TITLE
Group membership protocol timeout in JGroups slows down the startup

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#21033]
### Description

During the performance analysis, I noticed that Keycloak waits 2 seconds to join the ISPN cluster, and the CPU utilization is 0%; no tasks are executed. The cluster is analyzed for 2000ms, and if there's no coordinator (cluster empty), the node will become the new coordinator. It slows down the whole Keycloak startup by about the mentioned 2000ms.

It seems to me it's not a proper solution for it. For the minor part, the timeout seems to me really high, and I'm wondering whether exists some solution with a synchronized way to become the coordinator immediately when the cluster is empty. 

I've noticed that we use a JGroups configuration file[1] for the UDP and only for the embedded clustered mode for ISPN. In that file, the default value for the PBCast GMS `join_timeout` is set to `500`. But that file is not used for the default Keycloak start execution, and the default value for that timeout is 2000.

At least, we could decrease the timeout as customers have the ability to change the configs for particular stacks via Keycloak config props.

![ispn-wait](https://github.com/keycloak/keycloak/assets/38039883/f0789fbb-f710-41be-9c20-9043d2537e80)

@mhajas @martin-kanis @pedroigor @pruivo Do you have any thoughts or ideas about this? Thanks for the reply.

[1] https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java#L211

**Comment by mabartos** [comment]
Added milestone 22.0.0 as it can bring significant improvement to the Keycloak performance.

**Comment by pruivo** [comment]
The timeout is the default set by JGroups: https://github.com/belaban/JGroups/blob/b5070eefb5e4da036ccc84f40ad414db76403bb2/src/org/jgroups/protocols/pbcast/GMS.java#L53

There is no automated way to know if the node is the first one to start or not. But, for our test suite, we set `-Djgroups.join_timeout=0` when the first node starts to avoid any waiting. You can document this alternative if you want to save those 2 seconds.

If the timeout is too low, it can lead to a scenario where multiple coordinators are present in a single cluster. That case is detected by `MERGE3` and they need to reconcile and elect a single coordinator. 

I'll let @belaban correct me if I'm wrong and probably suggest a better default value for `GMS.join_timeout`.

**Comment by mabartos** [comment]
@pruivo Thanks for the quick response and valuable info!

**Comment by belaban** [comment]
I guess 2 seconds is a bit on the conservative side, but you're free to override this in the config. If you do a staggered startup, you can set this value to a very low number, e.g. 10 (ms).
As Pedro mentioned, to avoid partitioning at startup, I would not set this value to 0.

**Comment by mabartos** [comment]
Not valid for the milestone 22.0.0. Not planned to change the timeout; closing.
