### ISSUE TITLE
Custom User Storage Provider gets disabled when saved

### ISSUE THREAD

**Issue by RiskManagementGroup** [keycloak/keycloak#21045]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

We have implemented 2 custom user storage providers that implements the ImportSyncronization interface: https://github.com/RiskManagementGroup/keycloak-msg-api-user-federation and https://github.com/RiskManagementGroup/keycloak-itcn-api-user-federation

They have been working fine in previous versions, but currently we are updating them to work with Keycloak 21 and have run into some issues.

One of them is that when you update and save the configuration, the user storage provider is disabled:

![image](https://github.com/keycloak/keycloak/assets/30862022/10752082-b7eb-42c5-9e08-086a246cd3fb)

If you refresh the page the toggle goes back to enabled.

We had never noticed this before, but it turned out that the UI behaved in the same way in version 20.

In version 20 this was not a biggie, since it was only a UI thing and we can live with that.

The problem is, than in version 21, it is not only the UI that changes, but all users previously synced are actually disabled.

Also if you have setup periodic sync this will no longer work. Even if you toggle Enabled back and forth it will not start periodic sync again.

We found out, that the "enabled" attribute of the config gets set to "t" somewhere along the way and we have managed to make a workaround by adding the following code to the `validateConfiguration` function in the factory:

```java
    String enabled = config.getConfig().getFirst("enabled");

    if ("t".equals(enabled)) {
      logger.debug("enabled is set to 't'. Will change it to 'true' as a workaround");
      config.getConfig().put("enabled", Arrays.asList("true"));
    }
```

This does not fix the UI, but it will ensure that the users are not disabled and the periodic sync will work.

### Version

21.1.1

### Expected behavior

Saving the configuration of a custom user storage provider should not disable it

### Actual behavior

Saving the configuration of a custom user storage provider should not disable it

### How to Reproduce?

You can try to add either https://github.com/RiskManagementGroup/keycloak-msg-api-user-federation or https://github.com/RiskManagementGroup/keycloak-itcn-api-user-federation to your keycloak server and you will easily be able to reproduce.

**Comment by vplemyannik** [comment]
Agree, have the same issue

**Comment by vplemyannik** [comment]
@RiskManagementGroup thank you for the workaround

**Comment by vplemyannik** [comment]
i noticed that `t` comes from UI request

![image](https://github.com/keycloak/keycloak/assets/17518385/164df904-d93c-4fb9-b3e6-945c2f54f0b2)

**Comment by edewit** [comment]
fixed with https://github.com/keycloak/keycloak/pull/20964

**Comment by Fryie** [comment]
@edewit Would it be possible to backport the fix to 21.x.x? This is currently an issue for us, but we don't currently have the resources for a major upgrade.

@RiskManagementGroup your workaround seems to work fine (except it still looks broken in the UI), but it still suffers from the reverse issue: if you update a deactivated provider, it will be automatically reactivated. This can be fixed by adding an additional equivalent condition for `if ("f".equals(enabled))` and then setting it to `"false"`.

**Comment by stianst** [comment]
I'm afraid we don't have the capacity to release bespoke fixes to no longer maintained releases. 21 is based on a Quarkus release that is no longer available, and as such even if we did have resources to maintain it longer we wouldn't be able to as we would be unable to obtain CVE or bug fixes to the underlying Quarkus dependencies.

**Comment by jonkoops** [comment]
Thanks for clearing that up :+1:
