### ISSUE TITLE
KEYCLOAK_IDENTITY not set when using device code flow

### ISSUE THREAD

**Issue by Acanthostega** [keycloak/keycloak#21049]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Hello,

I don't know if this is a bug or if this is in the specification of openid (I didn't found something related to this) or I'm missing something, but when trying to perform a device code flow authentication, I can successfully retrieve the access_token, but it seems that the cookies necessary to enable the SSO are not sent with the response to the call of the token endpoint with the device_code.

### Version

16.1.1 (checked also with 13.0.1 currently in use at my office)

### Expected behavior

KEYCLOAK_IDENTITY cookie present in the headers in the response of the token endpoint for the device code flow.

### Actual behavior

KEYCLOAK_IDENTITY cookie **not** present in the headers in the response of the token endpoint for the device code flow.

### How to Reproduce?

- Initiate a login with device code flow on the dedicated endpoint
- start polling the token endpoint with the provided device_code
- validate with verification_url_complete the user code
- check the headers of the response to the token endpoint once user_code validated for the presence of Set-Cookie with KEYCLOAK_IDENTITY

### Anything else?

This useful in case where on a TV or Set-Top box we need to retrieve a auth code (for an already authenticated user with device code flow) to transmit it to another service to make calls on behalf of the user (Alexa skills for example, taking auth code as argument)

**Comment by rmartinc** [comment]
Hi @Acanthostega!

I have tested withe last keycloa endpoint 21.1.1 and I think the behavior is the expected one.

1. From the command line emulating the device I request to the token endpoint the URL:

```bash
curl -s -X POST -d "client_id=test-oidc" -d "client_secret=hVosin8Vxtmv1lblwBtO4YgwD2esFM5t" -d "scope=openid" "http://localhost:8080/realms/master/protocol/openid-connect/auth/device" | jq
{
  "device_code": "v34UgtrM6AjgBHJLmhGmqksxiBRtfZ_N1m8hI3NWA-Q",
  "user_code": "VHEY-VDRJ",
  "verification_uri": "http://localhost:8080/realms/master/device",
  "verification_uri_complete": "http://localhost:8080/realms/master/device?user_code=VHEY-VDRJ",
  "expires_in": 600,
  "interval": 5
}
```

2. With the URL returned I open a browser and login. Here the `KEYCLOAK_IDENTITY` is set as expected. If I use the same browser for a second request the password is not requested again.

3. From the command line again I request the tokens emulating the device. Now the device can start using tokens and refreshing them as usual.

```bash
curl -s -X POST -d "grant_type=urn:ietf:params:oauth:grant-type:device_code" -d "client_id=test-oidc" -d "client_secret=hVosin8Vxtmv1lblwBtO4YgwD2esFM5t" -d "device_code=v34UgtrM6AjgBHJLmhGmqksxiBRtfZ_N1m8hI3NWA-Q" "http://localhost:8080/realms/master/protocol/openid-connect/token" | jq
{
  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMbWR5MVZQT08zNnY3eFNXaDZFMHNTS0lrSGc0dVpmZ3lEVjZ3RnNmNTB3In0.eyJleHAiOjE2ODcxNjU1MDAsImlhdCI6MTY4NzE2NTQ0MCwiYXV0aF90aW1lIjoxNjg3MTY1NDM4LCJqdGkiOiIyYmQ5NzU5YS1iNGM4LTQxMWMtYTUzOC03ZWVjODNjNzYzOGMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIxZWY4NmVkOC0yNjAwLTRiZWItODQ0OC0wNDYyOTE5NGMyMjAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ0ZXN0LW9pZGMiLCJzZXNzaW9uX3N0YXRlIjoiMjMzZDNkMTAtMDEzMS00YTMzLWFhOTctNWNmMWIwZWQ4MGJjIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODEiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiIyMzNkM2QxMC0wMTMxLTRhMzMtYWE5Ny01Y2YxYjBlZDgwYmMiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6InJpY2t5IHJpY2t5IiwicHJlZmVycmVkX3VzZXJuYW1lIjoicmlja3kiLCJnaXZlbl9uYW1lIjoicmlja3kiLCJmYW1pbHlfbmFtZSI6InJpY2t5IiwiZW1haWwiOiJyaWNreUBsYWxhLmNvbSJ9.LY2qn0sg9REKmq-s1x5sOssHqQBlz2pfWiWgbQZ9K26R1H_SIVNJZh-SYrhHZ7CW0oRQj3MYbejjLwzPbThyia7WAwm8HhfAtEAU8wKFb4kdfFbQaS07qcyHsCTZ1p7SbXYbigyeY_cNH1SUutOSgHsz0Kc9xTnWdjoYy4866vO_V3Yzpsezge-vdqGlc4AZIc4SIgHPMawvwMWD0d2RVfdOzc8Rz8Q2MTYWFnHQLmXbJulQONySEAwwzFh2n3cgFXrIgCGLT4GB6i8Az_IA5trc4gtBTPatIyFbqcehN6rtIJhvWkPYAkMyFyh3HGYo_NkQ2hWOhwYBIsqo1H-JoQ",
  "expires_in": 60,
  "refresh_expires_in": 1800,
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5YmRlYjVlMi1iMjViLTRjZWItYTZiMi0xMzZhZGFjZTc3YTEifQ.eyJleHAiOjE2ODcxNjcyNDAsImlhdCI6MTY4NzE2NTQ0MCwianRpIjoiMDQxYTczMzktNTFmYy00MjM1LWE3MmMtNTRkMzUyMTUzNTMwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsInN1YiI6IjFlZjg2ZWQ4LTI2MDAtNGJlYi04NDQ4LTA0NjI5MTk0YzIyMCIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJ0ZXN0LW9pZGMiLCJzZXNzaW9uX3N0YXRlIjoiMjMzZDNkMTAtMDEzMS00YTMzLWFhOTctNWNmMWIwZWQ4MGJjIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjIzM2QzZDEwLTAxMzEtNGEzMy1hYTk3LTVjZjFiMGVkODBiYyJ9.iK0QouA1KKV6lYJs274izdMxJyjxo35jlmoUA_AKqE8",
  "token_type": "Bearer",
  "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMbWR5MVZQT08zNnY3eFNXaDZFMHNTS0lrSGc0dVpmZ3lEVjZ3RnNmNTB3In0.eyJleHAiOjE2ODcxNjU1MDAsImlhdCI6MTY4NzE2NTQ0MCwiYXV0aF90aW1lIjoxNjg3MTY1NDM4LCJqdGkiOiI1M2EzNjUyOS0zODNkLTRlOGYtOTJkNC02NzNlNDFmMDk2NzkiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL21hc3RlciIsImF1ZCI6InRlc3Qtb2lkYyIsInN1YiI6IjFlZjg2ZWQ4LTI2MDAtNGJlYi04NDQ4LTA0NjI5MTk0YzIyMCIsInR5cCI6IklEIiwiYXpwIjoidGVzdC1vaWRjIiwic2Vzc2lvbl9zdGF0ZSI6IjIzM2QzZDEwLTAxMzEtNGEzMy1hYTk3LTVjZjFiMGVkODBiYyIsImF0X2hhc2giOiJxNVdlSGNndnFWQjhINWIzelMyZ3BnIiwiYWNyIjoiMSIsInNpZCI6IjIzM2QzZDEwLTAxMzEtNGEzMy1hYTk3LTVjZjFiMGVkODBiYyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoicmlja3kgcmlja3kiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyaWNreSIsImdpdmVuX25hbWUiOiJyaWNreSIsImZhbWlseV9uYW1lIjoicmlja3kiLCJlbWFpbCI6InJpY2t5QGxhbGEuY29tIn0.IQ6j6vz3tpVtbVAY_er90wbEwb66qJGeWbaI14h1l6LiJ-DZxzSnnPLiuSBgIDS4IZdb1ak_qvVtm-vqFfLtmae4Brbwbwv1CjBrVZ9mF_Z6XCLGFhGRgHUWO15J_pj3Z8nioDT8dhVVNbM1anL2M5uw3BwnyMZ3gUh8gSPKsSlqMYxImQguWywH6OLV6_6m48rzqi5Lg4KBt3IGxSfNq4KGngN554QYxTvWvyOOpbaC8eTF9UBpJ9_AbBeePQcPnLOLqDrMlu5XZK-68y15L9-oOOF4V_kun4qGyRtGaHLBtnQRJWTwm6sp846CZ19tfj3xQr5LDz1OOS2CWqQI7A",
  "not-before-policy": 0,
  "session_state": "233d3d10-0131-4a33-aa97-5cf1b0ed80bc",
  "scope": "openid profile email"
}
```

I don't understand why you are mentioning the `KEYCLOAK_IDENTITY` in the token endpoint. That cookie is never used in that endpoint. It's used in the authentication flow not in the token. The device can use the access token to call to other endpoints and refresh it via the refresh token.

**Comment by Acanthostega** [comment]
Ok. For which endpoint the KEYCLOAK_IDENTITY, maybe I have checked too quickly :smile: 

But if I understand correctly, in the device code flow, I have retrieved the access token, and if I want to request an authorization code from this device for another client_id, I should simply call the authorization code endpoint, providing the access token in the `Authorization` header and the SSO should work?

I tried this but the redirect_uri is called with the `login_required` error. I thought that it was due to the missing headers for SSO but maybe this is not possible to do something like this?

**Comment by rmartinc** [comment]
> But if I understand correctly, in the device code flow, I have retrieved the access token, and if I want to request an authorization code from this device for another client_id

I don't know what you are trying to do here. If you need to start a new flow for another client (device or common code2token), it's the other client the one that should start the flow. If the same browser is used, there will be no re-login using cookies. Probably the token exchange feature is something similar to what you are trying to do, but that's something different.

Once the device completes the device flow, it has the tokens (access/refresh) issued for that client  (`azp` claim in the token). The token can be configured to be used for other bearer only clients (`aud` claim).

**Comment by sschu** [comment]
As long as you use the same browser on the same device, SSO works. It does not matter whether it is device code flow or authcode flow, as long as it is the same browser. I am not sure this works on all mobile devices as it depends which browser is used by the mobile app that open it for authentication and whether they persist cookie state.

**Comment by rmartinc** [comment]
@sschu Yes, exactly, but I think that @Acanthostega wants the same in the device (not the browser) and that's why he's trying to use the token inside the device. I think that's a weird use-case and I don't know if it fits completely in what the spec considers. But in my tests the cookies are set OK using the device flow.

**Comment by sschu** [comment]
@rmartinc But then this is not a bug, right?

**Comment by rmartinc** [comment]
@sschu Yep, AFAIU this is not a bug and working as expected. My idea is closing it in a few days. :smile:

**Comment by Acanthostega** [comment]
In fact on the TV the browser is the same, so the SSO should work. If I understand correctly, inside a same browser (whatever it is), if I do a device code flow for a client id and a second one device code flow for another client id, the second should be able to resolve the call to the token endpoint without waiting for the user entering user_code?

I will try to make a table of the different use cases possible to see what can be done for now with SSO and the different flows.

**Comment by rmartinc** [comment]
@Acanthostega Not in the step 3 of my first comment, so no in the call from the device to the token endpoint. The KEYCLOAK_IDENTITY is expected to work and avoid the login in the step 2 (browser). Steps 1 and 3 are calls done by the device/app and no browser is involved.

**Comment by Acanthostega** [comment]
Ok. I checked all use cases and think more now that it is intrinsic to the behavior of the oauth device code flow as you said.

If I take the example of a company creating several apps of a smartwatch for example, what I wanted is to have the possibility to login inside an app via device code and that other apps be able to use SSO to not ask again a user code to be provided by the user.

But by design of the call sequence of the device code flow, it would require that the device_code endpoint provides directly the token when requesting the user_code, if the user is already logged in via SSO, which is not in the oauth standard.

So I think that the device code flow provides "access rights" to the device, but do not allow to identify it. Last question: do you agree with this vision or it is better to see it as a limitation of oauth? Since when calling the token endpoint with the user_code, I can retrieve the id_token also, I think that it is the second one. But maybe it is not expected to have the id_token in the device in this case. I ask it to better understand and remember it more easily later when I will be wondering why in few months :smile:

**Comment by Acanthostega** [comment]
Yes I agree. I wanted to show with my example my mistake. Allowing SSO on device side using cookies as with other flows would resolve the problem of identifying the user in your previous answer. But this will require modification of the device code flow standard of Oauth to make it works. So this is not something related to Keycloak. I will close the issue.

Thank you for your time and your help.
