### ISSUE TITLE
admin api: search users misses email domain part

### ISSUE THREAD

**Issue by muradm** [keycloak/keycloak#21053]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

Admin API says:
```
GET /{realm}/users
...
Query - search - A String contained in username, first or last name, or email
```

Searching for `test` is ok, but `a`, `ac`, `acm`, `acme`, `c`, `co`, `com` etc. does not match any result.

### Version

21.1.1

### Expected behavior

Search should provide results matching domain part of email too.

### Actual behavior

No results when search matches domain part of email.

### How to Reproduce?

Create a user with email and username `test@acme.com`.

Try to search for acme.

### Anything else?

Using MariaDB as database.

Admin Console also has same problem.

**Comment by rmartinc** [comment]
Since #8346 the `search` parameter uses prefix comparison, so when you set search for `acme.com` you are doing the prefix search `acme.com*` and returns nothing for emails. You can use the `search` with `*acme.com*` to return a contains search.

**Comment by douglaspalmer** [comment]
@rmartinc I guess this just needs a docs update to reflect the changes in #8346?

**Comment by rmartinc** [comment]
@douglaspalmer Yep! it would be a good thing! :smile:
