### ISSUE TITLE
Allow any JGroups stack with --cache-stack

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#21064]
### Description

In OpenShift/Kubernetes it is not possible to set a custom JGroups stack (for example, tunning the JGroups threads or the credits limit, adding/removing protocols) because `--cache-stack` is set by the operator and it cannot be removed.

The change proposed to allow `--cache-stack` to point to any stack shipped with Inifinispan or defined in any custom Infinispan XML configuration file.

**Comment by abstractj** [comment]
@stianst added 22 milestone here because this is important for us to include in the upcoming release.
