### ISSUE TITLE
Support using the SessionFixationProtectionStrategy in the Spring Security adapter

### ISSUE THREAD

**Issue by thomasschuerger** [keycloak/keycloak#21061]
### Description

Our Spring Boot 2.7.x application integrates with Keycloak using the standard Keycloak's Spring Security adapter with OIDC. The usual flow is that the user accesses a page in the application which requires authentication. This request (or any other request before that doesn't require authentication) creates an anonymous session with a specific session ID, then the user is redirected to Keycloak to log in and then comes back to the application. The successful login does not change the session ID, therefore the application is prone to session fixation attacks (see https://en.wikipedia.org/wiki/Session_fixation and https://owasp.org/www-community/attacks/Session_fixation). Spring Security has support for changing the session ID at login time via using one of the provided implementations of SessionFixationProtectionStrategy; however, this is not used/supported by the adapter.

Keycloak's documentation explicitly mentions this problem in https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter:

> Spring Security’s SessionFixationProtectionStrategy is currently not supported because it changes the session identifier after login via Keycloak. If the session identifier changes, universal log out will not work because Keycloak is unaware of the new session identifier.

We don't even use the universal logout. We would rather have the session fixation issue solved instead.

It would be great if

- the Keycloak adapter would allow calling the SessionFixationProtectionStrategy (regardless of the side effects on universal logout) via configuration or if there would be a Keycloak documentation regarding how this can be customized accordingly
- a proper solution regarding the session ID change would be offered (by sending the changed session ID back to Keycloak so that the universal log out would still work)

### Motivation

Session fixation attacks are dangerous and can be prevented easily. Keycloak should offer some kind of option to prevent session fixation attacks when Keycloak is used in conjunction with Spring Security.

**Comment by pedroigor** [comment]
@thomasschuerger Sorry for the delay. As you might know, we are removing support for our adapters including Spring. See https://www.keycloak.org/docs/latest/upgrading/index.html#deprecation-of-keycloak-openid-connect-adapters.

I'm closing the issue for this reason.
