### ISSUE TITLE
Keycloak being able to handle 1000+ identity providers in a realm

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#21071]
### Description

This includes various tasks needed for Keycloak to be able to handle 1000+ identity providers in a realm (might be even 10k or more).

### Discussion

https://github.com/keycloak/keycloak/discussions/21076

Report from the community users about the issues with 4000 identity providers in a realm: https://issues.redhat.com/browse/KEYCLOAK-17860

### Issues

```[tasklist]
### Tasks
- [ ] #14888
- [ ] https://github.com/keycloak/keycloak-benchmark/issues/382
- [ ] #21072
- [ ] #27053
- [ ] #21073
- [ ] #21954
- [ ] #21074
- [ ] #21261
- [ ] #21075
```

### Relevant Open PRs

- #8022
- #7960

**Comment by bonnm** [comment]
Hi,
Just a comment to the area of handling thousands of IdPs: Automated import/processing of IdPs from a SAML federation would also be a nice feature. There already was a discussion about this: https://github.com/keycloak/keycloak/discussions/8608, and there is a fork https://github.com/eosc-kc/keycloak which works with 1000+ federated SAML-IdPs. Maybe it is worth to have a look at it.

**Comment by cgeorgilakis** [comment]
I believe also [account console with many IdPs issue](https://github.com/keycloak/keycloak/issues/11867) must be added to this epic.
Without fixing it, linked-accounts page will be unresponsible and user can not link his IdPs (accounts).

There is [a PR](https://github.com/keycloak/keycloak/pull/8022) for resolving this issue. Could you review it?

**Comment by cgeorgilakis** [comment]
> Hi, Just a comment to the area of handling thousands of IdPs: Automated import/processing of IdPs from a SAML federation would also be a nice feature. There already was a discussion about this: #8608, and there is a fork https://github.com/eosc-kc/keycloak which works with 1000+ federated SAML-IdPs. Maybe it is worth to have a look at it.

We have implemented  the SAML Federation and we could discuss in a github discussion/ github issue. SAML federation is based in supporting section 2.3.1 of [Metadata for the OASIS Security Assertion Markup Language (SAML) V2.0](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) and it gives a way to manage 1000+ SAML IdPs - like in our use case. SAML federation support needs all that mentioned in this epic.

I propose add SAML federation as an issue in this epic and discuss details in github discussion.

**Comment by rmartinc** [comment]
Starting looking at this one. I think that the steps to make this happen are more or less the following:

* Create a new API to manage the providers. API should contain basic CRUD and a search/list with pagination enabled.
* Change the UIs (admin, login page,...) to manage the new endpoints and not the list in the realm. This step will probably be translated into different issues.
* Remove/deprecate the list in the realm (avoid loading all of them in the realm representation).
* Subsequent enhancements (like import, sync or other things that are commented in the different discussions...). Those can be managed as separated issues as we have the base to cover thousands of providers.

The first step is always having the new endpoints to manage the providers. I think that #21072 is the one to cover that point and the starting point. So I'm starting thinking about this. I will present a skeleton to see what everybody thinks about it.

**Comment by jonkoops** [comment]
@rmartinc if we're building new APIs I'd really like to get started on a proper `v2` endpoint with proper Open API annotations.

**Comment by jonkoops** [comment]
Hahah, sounds fair! Let me know when I can pitch in.

**Comment by rmartinc** [comment]
@jonkoops and anyone interested, I updated https://github.com/keycloak/keycloak/issues/21072 with a the API changes (as expected they are minimal).

**Comment by pedroigor** [comment]
We are resuming this work here https://github.com/keycloak/keycloak/issues/30084. Wen can move discussions to this issue.
