### ISSUE TITLE
Make sure identity providers are not send in realm GET requests and PUT requests used in "Realm settings"

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#21072]
### Description

The issue is that when some generic realm page is displayed in the admin console (for instance page http://localhost:8081/auth/admin/master/console/#/test/realm-settings with the basic settings for the `test` realm), then the admin console uses realm GET endpoint under the covers to download the data about realm. For instance it will send GET request to endpoint http://localhost:8081/auth/admin/realms/test, which will return JSON with the `test` realm. The issue is, that realm JSON contains the field `identityProviders` with all the realm identity providers. This doesn't scale in case that realm has many identity providers.

This issue applies for many pages through the admin console (pretty much all the subtabs under left admin console tab `Realm Settings`). However most of the pages don't need identity providers at all.

Another issue with this is, that when some realm settings page is updated by admin console, the subsequent realm PUT REST call includes the realm JSON including identityProviders (pretty much same JSON which was returned by GET endpoint). This caused the error when realm has many identity providers due the event was too long and particular DB column was overflowed, but it is possible that there are multiple issues (especially when count of identity providers would be very big).

### Possible solution

We can handle this by creating "admin console specific" REST endpoint where we can trim identityProviders as well as other possibly redundant stuff. This can be done under https://github.com/keycloak/keycloak/tree/main/rest/admin-ui-ext . Admin console can consume this on most of the places (subtabs of "Realm Settings" and other pages not directly dealing with "Identity providers").

One alternative approach is to directly update realm GET endpoint to not return `identityProviders` (or has some option/flag to control this). However this approach might be problematic as due the backwards compatibility, we cannot change the default behaviour of admin REST API endpoint http://localhost:8081/auth/admin/realms/test and skip returning identity-providers. Introducing another flag just for the purpose of our admin console is also not that pretty. So ATM my vote is to go with separate endpoint under https://github.com/keycloak/keycloak/tree/main/rest/admin-ui-ext .

Note that pagination in "Identity providers" settings can be handled as separate follow-up tasks to this task...

### Discussion

https://github.com/keycloak/keycloak/discussions/21076

**Comment by cgeorgilakis** [comment]
We could create a PR for this. The logic will be that ModelToRepresentation.toRepresentation(KeycloakSession session, RealmModel realm, boolean internal) will not add IdentityProviders and IdentityProviderMappers.
 IdentityProviders and IdentityProviderMappers are only needed during realm export.

I believe [this PR](https://github.com/keycloak/keycloak/pull/20169) is wrong. Realm admin console need all other realm information for showing and saving with PUT.

**Comment by rmartinc** [comment]
I checked the current API and we have endpoints to do almost everything:

* Create: POST /admin/realms/{realm}/identity-provider/instances
* Read: GET /admin/realms/{realm}/identity-provider/instances/{alias}
* Update: PUT /admin/realms/{realm}/identity-provider/instances/{alias}
* Delete: DELETE /admin/realms/{realm}/identity-provider/instances/{alias}
* List providers (no paging, return all): GET /admin/realms/{realm}/identity-provider/instances

And the same for the mappers, we have endpoints for everything.

* Create: POST /admin/realms/{realm}/identity-provider/instances/{alias}/mappers
* Read: GET /admin/realms/{realm}/identity-provider/instances/{alias}/mappers/{id}
* Update: PUT /admin/realms/{realm}/identity-provider/instances/{alias}/mappers/{id}
* Delete: DELETE /admin/realms/{realm}/identity-provider/instances/{alias}/mappers/{id}
* Get all provider mappers: GET /admin/realms/{realm}/identity-provider/instances/{alias}/mappers

The console is also using many of them (except list providers, I think it is using all the rest to administer providers right now). So I think the only missing piece is adding pagination to the providers list endpoint. I have created a simple proposal in this [branch](https://github.com/rmartinc/keycloak/tree/identity-providers) (last commit).

The list endpoint allows passing a search (filter by name), first and max for paging. A count endpoint is also added to return the number of providers that are in the realm (it also allows the search filter). The search filter allows prefix (name\*), contains (\*name\*) and exact ("name") filtering (default prefix), just the same than in users. The implementation is just using the current list in the realm, so no benefit for now. That's the real work to do now.

@jonkoops Take a look to it although the changes are minimal. One important point is that I realized that the openapi plugin doesn't understand the `Stream<IdentityProviderModel>` response type. I needed to upgrade to 3.3.x to make it understand is a array/list result. maybe we can file a separate issue for upgrading the plugin only.

**Comment by jonkoops** [comment]
> I needed to upgrade to 3.3.x to make it understand is a array/list result. maybe we can file a separate issue for upgrading the plugin only.

Yes, I think we can handle that separately. The most important part right now is to ensure performance improves. In the long term, we'd like to be able to generate a client from the OpenAPI schema, rather than maintain one ourselves.

**Comment by jonkoops** [comment]
@rmartinc Those changes look okay, perhaps we can create a draft PR so we can review if it works there? Ideally we'd fix the API, Admin Client and the Admin Console in the same PR to verify this.

**Comment by rmartinc** [comment]
Here it is: https://github.com/keycloak/keycloak/pull/21487

I removed the `pom.xml` modification as it's just for the swagger json generation. Then I will start with the work at db level (and other storages) to not retrieve the full list of providers.

**Comment by mposolda** [comment]
@rmartinc @jonkoops It seems to me that what you guys discussed in last comments and what is done in the draft PR https://github.com/keycloak/keycloak/pull/21487 is related to pagination of identity-providers. However this particular GH issue is not about the pagination of identity providers. There are separate issues for that: https://github.com/keycloak/keycloak/issues/21073 and https://github.com/keycloak/keycloak/issues/21074.

This one is more about the issue when realm GET endpoint is called, the realm contains big JSON due the identity-providers are returned. However the "realm generic" admin console pages don't need identity providers at all.

I've updated the description of this issue to be more clear. I am sorry if the description may not be that clear before. For the details, you can also see the original (long) discussion when this issue first arise https://github.com/keycloak/keycloak/discussions/21076
