### ISSUE TITLE
Identity providers: pagination in admin REST API

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#21073]
### Description

This is pagination for identity providers. Probably might be done in same/similar way like for other entities (clients, users etc).

**Comment by cgeorgilakis** [comment]
We have made [this PR](https://github.com/keycloak/keycloak/pull/7960) long time ago for support old admin console with IdP pagging.
If you are interested, we can delete changes related to old admin console, rebase and review it after.

Except from paging, we sent only brief Identity Provider Representation for Identity Provider admin pager.
