### ISSUE TITLE
Group list isn't filtered based on permission like user lists

### ISSUE THREAD

**Issue by dmartinol** [keycloak/keycloak#21095]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Same as #19655 but with respect to the Keycloak Admin REST API
When invoking the `GET /groups` service and groups have fine-grained authorization enabled, the returned list of groups is not affected by the configured permissions.

### Version

21.1.1

### Expected behavior

`GET /groups` service returns only the groups for which the current user has permissions to query.

### Actual behavior

`org.keycloak.services.resources.admin.GroupsResource` does not implement any permission filter, while `org.keycloak.services.resources.admin.UsersResource` implements it in this method:

`private Stream<UserRepresentation> toRepresentation(RealmModel realm, UserPermissionEvaluator usersEvaluator, Boolean briefRepresentation, Stream<UserModel> userModels) {`

### How to Reproduce?

Setup:
- Create policy P1 based on realm role R1 and P2 based on role R2
- Create user U with realm role R1 and permissions of `realm-management/query-groups`
- Configure groups G1 and G2 and enable fine-grained permissions on both. Associate all the permission scopes of G1 to the policy P1 and all the permission scopes of G2 to the policy P2 and

Test execution:
- Get an access token for user U and then invoke the /groups API
- It returns both G1 and G2

Expected:
- Only G1 is returned

**Comment by ahus1** [comment]
@mposolda - there is now PR #21289 for this by the community.
