### ISSUE TITLE
Use parallel pod management policy for Keycloak StatefulSet 

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#21108]
### Description

During the instance scaling in k8s env, I've noticed we use the default `podManagementPolicy=OrderedReady`, pods are created sequentially, and during scale-down dropped in reverse order. I'm wondering if we need to use this default behavior for Keycloak, which is represented as StatefulSet only because of the ISPN cache state; and might behave more like Deployment. 

AFAIK, it should affect only the scaling and not any migrations. I don't see any implications related to the DB connections, or ISPN and JGroups. 

When we switch to the `parallel`, pods are instantiated in parallel and we could scale and react to the required state more quickly.

@keycloak/cloud-native However, I'd like to hear your opinion on that.
cc: @Pepo48 @shawkins

**Comment by shawkins** [comment]
Looks like a good optimization.

**Comment by andre-nascimento-rh** [comment]
@mabartos , it looks awesome. Have you run some load tests to verify If any User Authenticated Session is missed when scaling in parallel?

**Comment by sschu** [comment]
There was some longer discussion on the question stateful set vs. deployment (see https://github.com/keycloak/keycloak/discussions/11763, also see https://github.com/keycloak/keycloak/pull/12447#issuecomment-1161317869) and the bottom line was that embedded Infinispan does not handle parallel joins/leaves very well and thus using a stateful set with orderedready podmanagement policy was the way to go.

**Comment by vmuzikar** [comment]
@mabartos Thanks for creating the issue. As @sschu suggested, there was a technical requirement for ordered creation and mainly termination of the pods. This is for ISPN to give it the time to rebalance not to lose any sessions when scaling KC cluster. This was also discussed with the ISPN team back then, IIRC.

I'd suggest closing this if that makes sense to you.

**Comment by mabartos** [comment]
Due to the technical requirements mentioned above, I'm closing it for the present non-validity of this issue :)
