### ISSUE TITLE
Migrate example themes to quickstarts

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#21100]
### Description

We have some old and no longer maintained examples for themes (https://github.com/keycloak/keycloak/tree/main/examples/themes), these should be updated and moved to QuickStarts.

The account and admin themes need to be updated to the more recent versions of the consoles. 

We should also check the documentation around themes to make sure it's not referring to the old examples.

**Comment by ssilvert** [comment]
FYI.  We are working on a new quickstart that demonstrates theming admin console V2 and (soon) account console V3.
https://github.com/keycloak/keycloak-quickstarts/tree/latest/extend-admin-console-quick-start

**Comment by agagancarczyk** [comment]
hi @ssilvert can we assign this to somebody else who has done some work with the quick starts recently and may be more knowledgeable about this area?

**Comment by ssilvert** [comment]
Examples no longer exist in keycloak/keycloak.  Closing..
