### ISSUE TITLE
Integrate Startup probe to the deployment

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#21111]
### Description

When the Keycloak application is started inside the StatefulSet, probes for checking the state of the initialization are delayed as we use the liveness and readiness probe with the initial delay set to 20s. It causes major delays. 

We could also leverage the Quarkus Startup probe and integrate it with the Keycloak StatefulSet.

**Comment by shawkins** [comment]
> probes for checking the state of the initialization are delayed as we use the liveness and readiness probe with the initial delay set to 20s

@mabartos @vmuzikar the current FailureThreshold's are 250 and 150 for readiness and liveness respectively.  This allows for over 8 minutes until a pods is not ready or 5 minutes until it is seen as not live - given this is any initial delay even needed?

**Comment by vmuzikar** [comment]
@shawkins I agree. I was thinking about this more and I don't see much benefit in using startup probes in KC. The way I understand it, startup probes have the purpose to delay execution of liveness probes. That might be from two reasons: either you want different liveness timeouts on startup and after startup, or you don't want to interfere with the liveness probes during startup (you want to use a different endpoints for startup and liveness probes). AFAICT, neither is our case.

@mabartos WDYT?

**Comment by mabartos** [comment]
I don't see any implications for not providing the startup probes, as we can leverage the endpoint provided by Quarkus. As was mentioned, we could delay the execution of readiness/liveness probes, and we could optimize the whole startup procedure in k8s env. 

We can eliminate the initial delays completely and set up a proper period of checks and thresholds. The idea behind that would be to check every 1 second the startup probe in order to react on the startup ASAP and then check the liveness/readiness probes not so frequently. We could improve the overall performance of the whole cluster by restricting the execution of health checks inside nodes managed by the present kubelet. 

The `failureThreshold` seems to me very high as we're not able to react to container failures in a more reactive fashion. We could lower the number by default and for particular deployments, it's possible to override these probes.

**Comment by shawkins** [comment]
> The failureThreshold seems to me very high as we're not able to react to container failures in a more reactive fashion. 

Until that is lowered to the point where the probes may fail during normal startup, there's little need for a startup probe.

> We could lower the number by default and for particular deployments, it's possible to override these probes.

Do you mean via the podtemplate?  You have to override them wholely there - there's no option to just tune the existing probes.

**Comment by mabartos** [comment]
> Until that is lowered to the point where the probes may fail during normal startup, there's little need for a startup probe.

I got your point. We can achieve similar behavior only with the readiness/liveness probes without the `initialDelay` with such a big threshold as by providing the startup probe. 

> Do you mean via the podtemplate? You have to override them wholely there - there's no option to just tune the existing probes.

Yes, users would need to completely override them, so it'd need to be documented. However, it might bring some controversial decisions what to prefer. It'd be possible to react more rapidly to failures, but there would be a higher probability that customers would have to "make more workarounds" for their deployments. 

I was also thinking about providing the ability to change these properties for probes via some properties provided in Keycloak, but there's probably no such a big benefit it'd bring to us despite the maintainability,...

I'm ok removing the initial delays from the existing probes and not providing the startup probe for now. We can discuss stuff around probes further in team discussions and make further analyses around that.
