### ISSUE TITLE
Allow existing mappers for Custom Identity Providers 

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak#21154]
### Description

Currently, for each IDP Mapper, the list of supported mappers is defined by the method IdentityProviderMapper#getCompatibleProviders():

For example, for `UserAttributeMapper`, the compatible providers are the Keycloak OIDC Provider and the standard OIDC Provider.
https://github.com/keycloak/keycloak/blob/41e253c054d7db1682a0865603bdf20d0893ba6f/services/src/main/java/org/keycloak/broker/oidc/mappers/UserAttributeMapper.java#LL48C1-L48C1

We have implemented our own Azure OIDC Provider, based on the standard OIDC Provider, and our customers would like to use (probably) all of the mappers which are compatible to the standard OIDC Provider.
Currently this is not easily possible. One of those mappers is `UserAttributeMapper`.

### Motivation

We have built a kind of patch, which supports all mappers for our custom provider, which are supported by the standard provider.
It would be helpful if we could do this without patching Keycloak.

**Comment by mposolda** [comment]
@danielFesenmeyer It would be ideal:
1) When someone implements custom `IdentityProviderMapper`, he can easily specify which `IdentityProvider` implementations it supports.
2) When someone implements custom `IdentityProvider`, he can easily specify which `IdentityProviderMapper` are compatible with it

Currently Keycloak is optimized for (1), but doesn't allow (2).

### How to improve that?

I am thinking about something like this method on IdentityPRovider:
```
boolean default isSupported(IdentityProviderMapper mapper) {
    List<String> compatibleIdps = mapper.getCompatibleProviders();
    return compatibleIdps.contains(IdentityProviderMapper.ANY_PROVIDER) || compatibleIdps.contains(this.getConfig().getProviderId());
}
```
And update accordingly `IdentityProviderMapper.getMapperTypes()` to be able to consume that method.

I think this approach will allow both (1) and (2) if I don't miss anything?

Contribution welcome :-)

**Comment by danielFesenmeyer** [comment]
@mposolda I think it will work that why. I'll provide a PR.

**Comment by danielFesenmeyer** [comment]
Hi @mposolda,

I've implemented a PR based on your suggestion: https://github.com/keycloak/keycloak/pull/22848
