### ISSUE TITLE
User administration: It is not possible to assign a user to a subgroup of an assigned parent group in order to obtain more rights

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#21173]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have the following group structure:

![groupStructure](https://github.com/keycloak/keycloak/assets/54103655/98b70e76-0e5e-4513-9b19-e16e3703b1bb)

The following roles are now in the respective groups:
IT: it-role
![itRole](https://github.com/keycloak/keycloak/assets/54103655/f91a4fb0-b598-4ca6-9974-ed3ed0f1fb38)

IT/Department: department-role
![departmentRole](https://github.com/keycloak/keycloak/assets/54103655/878b500c-6085-44c7-a36c-c31d19a976d3)

IT/Department/Backend: backend-role
![backendRole](https://github.com/keycloak/keycloak/assets/54103655/559b84d0-355a-4b3e-ba87-665d322c3583)

IT/Department/Frontend: frontend-role
![frontendRole](https://github.com/keycloak/keycloak/assets/54103655/b255f76f-47ef-422c-b9d8-785aaeb83d45)

The principle of group hierarchy when assigning roles is as follows: If a user is in the group IT/Department. He gets the roles from the group IT and the subgroup: Department. 
So: it-role & department-role

In this example, I have created a user who I have assigned to the group: IT/Department. As described in the picture, he is in the groups IT and Department, and has the following rights from the groups.
![userGroup](https://github.com/keycloak/keycloak/assets/54103655/017ff440-4e1e-4447-9bff-1d4b57e66ce4)

So far so good, now to the problem:

If I now want to give my user more rights by assigning him to the subgroup "Frontend" of IT/Department via the user administration, this is not possible because the item is greyed out.
![joinSubGroup](https://github.com/keycloak/keycloak/assets/54103655/2e0bd36e-34bd-47fc-abd0-de6009f74da5)

In my opinion, in this case it should be possible to go deeper into the group structure. Because this way you understand that you cannot go deeper because it has the same properties from the subgroups, which is not true.

Furthermore, it would be clearer for the group assignment in the user administration if the general group tree structure could be displayed there. So that you can see directly which parent groups and subgroups there are.
So this view:
![groupStructure](https://github.com/keycloak/keycloak/assets/54103655/98b70e76-0e5e-4513-9b19-e16e3703b1bb)

If you add the user to the subgroup via the group administration, this is possible. But it should also be possible via the user administration.
![Screenshot from 2023-06-23 14-33-48](https://github.com/keycloak/keycloak/assets/54103655/514e453b-5c19-4c57-a02b-59766f27e955)

### Version

21.1.1

### Expected behavior

That you can also assign a user to a subgroup via the user administration if the user is already in the parent group.
Furthermore, it would be helpful to have the tree structure of the groups in the user administration.

### Actual behavior

-

### How to Reproduce?

By explaining the problem, it should be possible to recreate the problem.

**Comment by ssilvert** [comment]
I agree this is a bug.  It's fine for it to be greyed out, but you should still be able to navigate deeper.

As for adding the tree view to the "join" dialog, that's a feature request.  Please create a feature request for it and link to this issue.

**Comment by ssilvert** [comment]
Set to medium impact because there is a workaround.

**Comment by grazius** [comment]
in version 22.0.3 the issue is not fixed when you browse to Users / User detail / Groups / Join Group... top level groups are not browsable so you can't select a subgroup.

Best regards

**Comment by jonkoops** [comment]
@grazius if you are still experiencing problems, please log a new issue, it will make it easier for us to track.
