### ISSUE TITLE
Supporting a reference/lightweight access token

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#21186]
### Description

The original issue is #19650 .

By incorporating [the discussion](https://github.com/keycloak/keycloak/discussions/19649), I will follow the milestones of the discussion comments by @mposolda instead of [the original PR](https://github.com/keycloak/keycloak/pull/19824).

Milestones ( related subtasks):

- M0: #21182
- M1: #21183
- M2: #23724 
- M2: #23725 
- M3(optional): #23727

### Related tasks

```[tasklist]
### Tasks
- [ ] #24344
- [ ] #27243
- [ ] #27238
```

**Comment by mposolda** [comment]
I am closing this epic as this was mostly done for Keycloak 24 (all tasks from milestone 1 and milestone 2). Remaining milestone 3 is in separate epic https://github.com/keycloak/keycloak/issues/21186 .
