### ISSUE TITLE
More flexibility for Introspection endpoint

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#21183]
### Description

The issue is for selecting claims that put onto Token Introspection response for like an access token, ID token, and UserInfo endpoint's response.

### Discussion

https://github.com/keycloak/keycloak/discussions/19649

### Motivation

It is needed to realize reference/lightweight token that is disucussed in https://github.com/keycloak/keycloak/discussions/19649 and https://github.com/keycloak/keycloak/discussions/9713

### Details

The section "More flexibility for Introspection endpoint" of the following comment of the discussion:

https://github.com/keycloak/keycloak/discussions/19649#discussioncomment-6251316

The following features are needed:
- Create protocol mapper that enable keycloak to select claims that put onto Token Introspection response for like an access token, ID token, and UserInfo endpoint's response.
- Add logic for protocol mapper to Token Introspection Endpooint code.

**Comment by cgeorgilakis** [comment]
Thank you all for your work.
After accepting this PR, we have opened a [PR](https://github.com/keycloak/keycloak/pull/24346) for enhancing error logs and error events during UserInfo endpoint and Token Introspection failure.
