### ISSUE TITLE
Client policy executor which will switch Add to Access Token OFF for this request and will manually remove sub claim

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#21184]
### Description

The issue is for removing claims that are added by protocol mappers to an access token and sub claim that may indicate personal identifiable information (PII).

### Discussion

https://github.com/keycloak/keycloak/discussions/19649

### Motivation

It is needed to realize reference/lightweight token that is disucussed in https://github.com/keycloak/keycloak/discussions/19649 and https://github.com/keycloak/keycloak/discussions/9713

### Details

The section "Client policy executor" of the following comment of the discussion:

https://github.com/keycloak/keycloak/discussions/19649

The following features are needed:
- remove all claims that are added by protocol mappers to an access token by setting such mappers' switch for Access Token OFF before the access token is initialized, or remove the claims from the access token after the access token is initialized.
- remove manually sub claim after the access token is initialized.

In order to realize the features above, enchanced client policies by https://github.com/keycloak/keycloak/issues/21182 can be used.

**Comment by mposolda** [comment]
Closing this for now as it might be replaced by #23724
