### ISSUE TITLE
The implementation or documentation of keycloak.import is wrong

### ISSUE THREAD

**Issue by primeos-work** [keycloak/keycloak#21222]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

import-export

### Describe the bug

Realms could be imported like this: `-Dkeycloak.import=/realm/keycloak-realm-test.json` (via the `keycloak.import` system property). I noticed that this is not possible anymore while upgrading an existing Helm Chart deployment (uses the `bitnami/keycloak` chart and provides the setting via `extraEnvVars.KEYCLOAK_EXTRA_ARGS`).

The documentation states the following:

https://github.com/keycloak/keycloak/blob/46fa7d2e6cf913c0bd6e7541d31a3fbcdc942e77/docs/documentation/server_admin/topics/export-import.adoc?plain=1#L85-L90

But the implementation now treats the parameter as a directory (vs. a file):

https://github.com/keycloak/keycloak/blob/46fa7d2e6cf913c0bd6e7541d31a3fbcdc942e77/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L257-L261

Unfortunately the error handling is very suboptimal so this results in a super generic `directory not found` error message:

https://github.com/keycloak/keycloak/blob/46fa7d2e6cf913c0bd6e7541d31a3fbcdc942e77/services/src/main/java/org/keycloak/exportimport/ExportImportManager.java#L124-L125

As a result, this regression took me quite a while to figure out based on this output:
```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: directory not found
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command. 
```

The error message should definitely output the directory name as well.

### Version

21.1.1

### Expected behavior

The provided JSON file gets imported successfully. And if it fails the error message should contain all relevant details to determine the cause (without having to look into the source code).

### Actual behavior

The Keycloak container crashes with an error message that lacks both the file/directory name and the information that the import failed.

### How to Reproduce?

By importing files as described in the documentation:

https://github.com/keycloak/keycloak/blob/46fa7d2e6cf913c0bd6e7541d31a3fbcdc942e77/docs/documentation/server_admin/topics/export-import.adoc?plain=1#L85-L90

### Anything else?

This regression probably isn't that new as the Helm Chart was quite outdated.
Looking at the code it seems to come from 522bf1c0b0490fd9a6a8bf18a6b06aae0fa989c5 (cc @pedroigor, @mabartos, and @vmuzikar).
The `directory not found` error message was introduced in 251f6151e86b55efdfe2a688989ac15795481e59 (cc @ahus1 and @pedroigor).

**Comment by sguilhen** [comment]
`export-import.adoc` is an old guide targeting the WildFly based distributions of Keycloak. It has been removed in recent releases, starting with KC 22.0.0. 

The [new guide](https://github.com/keycloak/keycloak/blob/main/docs/guides/server/importExport.adoc), which targets the current quarkus distribution, should be used for importing and exporting realms. Let us know if you find any issues with that guide.
