### ISSUE TITLE
Conditional OTP Configuration has interference with other/deleted flows that also use Conditional OTP

### ISSUE THREAD

**Issue by nfode** [keycloak/keycloak#21229]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

When you create an authentication flow with "Conditional OTP" as subflow and then delete it, the "Conditional OTP" configuration is not deleted. 

Then when you create another authentication flow with "Conditional OTP" the flow might not work because the configuration of another flow is validated first. This also happens when you have another flow that uses "Conditional OTP".

Here you can see the different configurations that are used for checking despite being deleted or from another flow:
![image](https://github.com/keycloak/keycloak/assets/3685923/4b432e4a-07a2-4fea-82c7-b043abb27293)

### Version

20.0

### Expected behavior

Keycloak checks if the user needs to use the OTP,  only with the configuration that is relevant for the client the user is trying to log in with.

### Actual behavior

Keycloak checks if the user needs to use the OTP either by using deleted configuration or configuration from another client.

### How to Reproduce?

1. Create an authentication flow with a "Conditional OTP" subflow. Example: 
![image](https://github.com/keycloak/keycloak/assets/3685923/527ce81e-bbba-492f-8817-82ee3a9634b5)
Conditional OTP Config:
![image](https://github.com/keycloak/keycloak/assets/3685923/c4ba6ac1-af7d-4e11-8a32-cfdbd282d86c)
2. Delete the flow and create another flow also with "Conditional OTP" but use another value for "User control attribute" (Note: I only changed the control attribute from the previous image for the purpose of the screenshot. I ofc tested this properly with a new client.) 
![image](https://github.com/keycloak/keycloak/assets/3685923/c04bf910-a2ab-4983-81da-4e72d1e68032)
3. Try to log in with a user with the given control attribute and observe that he still needs to configure/enter an OTP. The debugger show that this happens because the control attribute from the previous client is used. This might not directly reproducible because the sorting of configurations  is important. Maybe some clients need to be created until the correct configuration is not the first one.

**Comment by nfode** [comment]
I think there went something wrong with the labels. It meant to be authentication.

**Comment by mposolda** [comment]
I am adding to Backlog as I think that Keycloak team won't have time to look at this in the near future. Anyone is welcome to contribute the fix for this if it is confirmed that this is valid issue. The ConditionalOtpFormAuthenticator does not have much priority as in general, we have conditions now in the authenticationFlow and it might be better to use individual conditions together with OTPFormAuthenticator instead of tweaking ConditionalOtpFormAuthenticator.
