### ISSUE TITLE
Keycloak Event clientId is null when ever a logout event is fired.

### ISSUE THREAD

**Issue by elloumiii** [keycloak/keycloak#21236]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

We are implementing the `EventListenerProvider` interface in order to catch some Keycloak events, we are using the event.clientId to get the clientId which is related to this event.

For the events of type `LOGIN`, we are able to see the correct clientId on which the user or admin is using to authenticate using `event.clientId` , however for `LOGOUT` event, the `event.clientId` is null. (we are using Kotlin)

I tested this with both 20.0.5 and 21.1.1.

### Version

21.1.1

### Expected behavior

I expect that the `event.clientId` should return the correct clientId instead of null, same behaviour as the login event.

### Actual behavior

`event.clientId` is null for the `LOGOUT` event.

### How to Reproduce?

```
class MyEventListenerClass : EventListenerProvider {

  override fun onEvent(event: Event) {

    when (event.type) {
      EventType.LOGIN -> {
             printtln(event.clientId). <----- correct
      }
      EventType.LOGOUT -> {
             printtln(event.clientId) <----- null
      }
}
}}
```

### Anything else?

I am not sure if it is a problem just for the `LOGOUT` event.

**Comment by mposolda** [comment]
Adding to Backlog as I am not sure if Keycloak team would have time to look at this in the near future. Anyone is welcome to send PR with improving this.

Also it may need to be verified if this is valid issue. The clientId should be likely the client, which initiated logout. However in case of opening the logout request itself without any client reference (EG. Opening OIDC RP-Initiated logout without `client_id` and `id_token_hint` parameter), there is no "initiating client" and hence it is correct behaviour that client is not set.

We can also consider to add separate value for list of clients in this browser SSO session, which was logged-out (if not already provided).

**Comment by Delawen** [comment]
Hi @elloumiii I am trying to verify and fix this. What kind of login/logout did you try that returned a null client? An authentication via the form browser?

**Comment by elloumiii** [comment]
> Hi @elloumiii I am trying to verify and fix this. What kind of login/logout did you try that returned a null client? An authentication via the form browser and then the logout via the browser too?

@Delawen yes I logged in using the form browser and logged out from the browser also... As I do remember I reproduced this even using the already existing `master` realm (logged in with the admin user and then logging out from the browser)

**Comment by Delawen** [comment]
Created a drafted PR for this: https://github.com/keycloak/keycloak/pull/23369

Still running tests to make sure I didn't break anything else with the fix.
