### ISSUE TITLE
New Admin UI: Sort User attributes alphabetically

### ISSUE THREAD

**Issue by wdw-jst** [keycloak/keycloak#21239]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

The old admin UI had a feature to show an users attributes sorted by attribute key.

This feature is missing in new admin UI. Attributes are shown in seemingly random order:

![grafik](https://github.com/keycloak/keycloak/assets/83639109/d94371c4-b331-4cdb-b4be-3f88491b8c3e)

Our customers solution relies on adding / removing user attributes for permissioning. Operations have a hard time maintaining these permissions because they are no longer displayed in order. 

### Version

20.0.1

### Expected behavior

User attributes may be sorted alphabetically by `key`-column by clicking on the column header. In the example screenshot the order should be
1. attr_0
1. attr_7
1. attr_9
1. bttr_0

### Actual behavior

User attributes are presented in seemingly random order

### How to Reproduce?

* Create user in Keycloak.
* Create multiple attributes for this user like `attr_0`, `attr_7`, `bttr_0`
* Attributes are shown in no particular order

**Comment by jonkoops** [comment]
I am not quite sure we'd want to (re)implement this. It would break the expectations of pressing the 'Add an attribute' inserting a row at the very bottom.

> Our customers solution relies on adding / removing user attributes for permissioning.

Could you elaborate on what you mean by 'permissioning' is here?

**Comment by wdw-jst** [comment]
> Could you elaborate on what you mean by 'permissioning' is here?

We have users federated via LDAP, so they get some LDAP related attributes. Roles/Permissions within the application are controlled by attributes `r6.tenantAccessMappings_`+ Number and `r6.channels_`+ Number. The numbers must be unique for the application to work.

Here is a (partial, redacted) real world example:
![kc-attributes-unsorted](https://github.com/keycloak/keycloak/assets/83639109/5d2677c8-24f8-4c88-8b27-92f9bd5799ef)

As you can see the attributes are unsorted. Our operations team must make sure that there are no duplicate attribute keys. They report that the attribtues are unsorted even if entered in order (r6.channels_0, r6.channels_1, ...)

Adding new attributes at the bottom is fine. We do not expect a new attribute to jump to another spot in the list. After searching/loading the user again, the attributes should be sorted by key, either by default or by clicking on the column header, as it used to be in the old admin UI.

**Comment by jonkoops** [comment]
@ssilvert @xianli123 how do you feel about this? We want to replace user attributes with User Profile in the future right? I am not sure this feature is worth it for this specific use-case either.

As far as the permission mapping goes, there must be some way to map those LDAP attributes to actual user groups. Although I am not familiar with how that should be done.

**Comment by xianli123** [comment]
Hi @jonkoops @wdw-jst The display order is based on the key pair creation time. I am not sure if it's a common way to control permission mappings. Wait for @ssilvert 's opinion.

**Comment by ssilvert** [comment]
It's true that the Attributes tab is going away in favor of User Profile.  But I don't know how soon that is going to happen.

It's easy enough to just sort it for now.  Let's go ahead and do it.

**Comment by ssilvert** [comment]
And I think @wdw-jst has the right idea.  We should only sort on initial load.  You wouldn't want to add an attribute only to have it "disappear" to the top of the page.

FWIW, the old console just sorts the keys alphabetically with no ability to click the column header to change sort order.

**Comment by xianli123** [comment]
> It's easy enough to just sort it for now. Let's go ahead and do it.
Is it necessary to provide a design wireframe? @jonkoops

**Comment by ssilvert** [comment]
@xianli123 This will not involve a UI design change.  Just need to sort whatever is returned from the server.

**Comment by xianli123** [comment]
@ssilvert Ok. Feel free to let me know if you need anything.

**Comment by jonkoops** [comment]
I guess we can sort the attibutes on load only. That should be enough to cover this use-case.

**Comment by jonkoops** [comment]
@ssilvert I think we should consider this low impact though, as it seems to be a very specific use-case. I'd also re-classify this as an enhancement, as this doesn't really break anything.

Feel free to change it if you disagree.
