### ISSUE TITLE
Link to custom user federation redirects to LDAP provider configuration

### ISSUE THREAD

**Issue by rgrosjean** [keycloak/keycloak#21259]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When importing users from a user federation, it is possible to click the federation link from the user's details page to open the provider configuration.
If a custom user store provider is used, the link will take the Admin to the configuration page of a LDAP provider instead of the custom provider configuration page.

![grafik](https://github.com/keycloak/keycloak/assets/39985706/c3d2a152-1a3b-4dc4-900e-520d76ef1c56)
![grafik](https://github.com/keycloak/keycloak/assets/39985706/6e0a45f4-bae3-421a-ad3c-fe1797f8c36e)

### Version

21.1.1

### Expected behavior

Clicking on the 'federation link' from the user details page should take you to the configuration page of the provider from which the user came.

### Actual behavior

Clicking on the "federation link" from the user details page redirects to the configuration of a LDAP provider

### How to Reproduce?

* Add a customer user-storage provider,
* import a user from this storage
* open its details page
* click on the federation link

**Comment by ssilvert** [comment]
@rgrosjean I believe we fixed this [here](https://github.com/keycloak/keycloak/issues/20097).  Can you give it a try in the latest nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by rgrosjean** [comment]
@ssilvert yes, it's fixed in the nightly version.  Thanks for your feedback.

Is it scheduled for KC22 or a 21.1.3? (The UI changed a bit, probably 22 😃 )

**Comment by rgrosjean** [comment]
@ssilvert yes, it's fixed in the nightly version. Thanks for your feedback.

Is it scheduled for KC22 or a 21.1.3? (The UI changed a bit, probably 22 smiley )
