### ISSUE TITLE
OpenID Connect provider does not support encrypted ID tokens

### ISSUE THREAD

**Issue by PetkoNosal** [keycloak/keycloak#21254]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

identity-brokering

### Describe the bug

We have an external OpenID provider that uses encrypted tokens, in Keycloak we configured this identity provider from /.well-known/openid-configuration and everything seems to be working except that keycloak failing to recognize that token is encrypted when doing validation and straight up fails with invalid token...

I know that Keycloak itself can encrypt its own tokens, so why it fails to recognize JWE and why cannot decrypt it?

### Version

21.1.1

### Expected behavior

When other identity provider is using JWE and encrypting token, Keycloak should recognize it and decrypt it (or at least validate token as JWE), not fail to validate token because it cannot parse JWE into JWT

### Actual behavior

Keycloak is failing to construct JWSInput because input is encrypted token, altho in header there is "enc" and encryption specified

### How to Reproduce?

Add any external Identity OpenID provider that uses encrypted tokens, can be done even Keycloak to Keycloak if brokered keycloak is encrypting tokens

**Comment by mposolda** [comment]
@PetkoNosal You are right. We don't support the case when Keycloak is configured with OIDC Identity provider, which uses encrypted IDTokens (and AFAIK also encrypted UserInfo would be an issue as well).

I am changing this to "Feature".

**Comment by PetkoNosal** [comment]
Shouldn't be hard to implement, there is already a org.keycloak.jose.JOSEParser that can recognize JWT or JWE from header so that can be used in OIDCIdentityProvider.validateToken method instead of using JWSInput directly... from there, just validate, decode and construct org.keycloak.representations.JsonWebToken response

**Comment by ma-lar** [comment]
Does anybody know when it might be include in an official release?

**Comment by gscokart** [comment]
Thanks, this fix the integration with ItsMe that is using JWE tokens.

**Comment by navyademo1** [comment]
Hi ,
By using this endpoint
http://localhost:8080/realms/External/protocol/openid-connect/token

am getting a token if I put this token into the jwt.io I can see the user data but this should not happen it should be encrypted in my case .

I came across JWE , how can I configure this in keycloak UI ( 23.0.0)

Thanks in advance!
