### ISSUE TITLE
Defining an audience in token-exchange messes up other endpoints (introspect, userinfo)

### ISSUE THREAD

**Issue by frelibert** [keycloak/keycloak#21276]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

token-exchange

### Describe the bug

Adding the parameter audience with a registered client_id makes the token (exchange) endpoint generate an accessToken with scopes and mappers as defined for that given client. It also makes keycloak create an authenticationSession for that client (and given user). That works fine. However: before returning the token, the azp claim (issuedFor) is overwritten to the client_id of the client making the token exchange request and that may cause following issues afterwards if the requesting client is not the token holder:
- when the returned token is sent to the introspect endpoint (for validation), the endpoint returns "active":"false"
- when the returned token is sent to the userinfo endpointn the endpoint returns "error":"invalid_request","error_description":"User session not found or doesn't have client attached on it"

The reason for this is, that both endpoints search for active authenticationsessions, linked to the client_id set in the azp claim and that doesn't give the expected result because there is no authenticationSession created for the requesting client. It was created for the client set as audience but that is not the client_id set in azp claim as it was overwritten before the token was returned to the requesting client.

### Version

RHSSO 7.6.3 (keycloak 18.0.7)

### Expected behavior

- introspect endpoint should return active:true
- userinfo endpoint should return the info of the user as expected for the audience for which the token was meant.

### Actual behavior

- introspect endpoint returns active:false
- userinfo endpoint returns an error that no user session was found for the client.

### How to Reproduce?

1. Authenticate and request a token for some registered client (aka sourceClient).
2. request a token exchange from some other registered client (aka targetClient) in the audience of the sourceClient and add a third registered client's id (aka audienceClient) as audience param. Make sure the targetClient has permission to use audienceClient as audience.
3. send the exchanged token to the introspect endpoint. It should return active=false
4. send the exchanged token to the userinfo endpoint. it should return error=invalid request, error_description=user session not found ...

### Anything else?

The solution is quite simple: don't overwrite the azp claim (issuedFor) with the id of the requesting client. The token was requested for the audience client, a session was created for that client and a token was generated with scopes and mappers of that client. If you don't overwrite the issuedfor claim, the introspect and userinfo endpoint work as expected as they will find and map the correct client/user/session when the token is analyzed.

I found other issues in this project repository, requesting to not overwrite the azp claim. I sincerely request the same. Don't overwrite it as it causes issues that can be easily prevented. If you do insist on overwriting it, behaviour in userinfo and introspect endpoint needs to be adapted to get the expected result which will be a lot more difficult if you ask me as the info on the audience client for which the session was created and the token mapped is lost since the azp claim got overwritten.

I've read in other issues here, as reason to set the azp claim to the requesting client, that the oidc spec says that azp is "the party to which the ID Token was issued". Certainly but we are talking about token exchange here and in that spec (https://www.rfc-editor.org/rfc/rfc8693.html) 2 other interesting elements are mentioned (and neglected for now in keycloak's implementation).
- claim "act":  provides a means within a JWT to express that delegation has occurred and identify the acting party to whom authority has been delegated
- claim "client_id": carries the client identifier of the client that requested the token

My suggestion is therefore this:
- Leave the azp claim as set when the token is generated (will be the audienceClient id)
- add client_id claim, set to the id of the requesting client
- add act claim to express delegation has occurred.

the latest claim is optional as it won't change the outcome of introspect or userinfo endpoint but it shows by itself that a token got exchanged and that is valuable info.

`
{
    "aud": "audience_client",
    "azp": "audience_client",
    "client_id": "target_client",
    "act": {
        "azp": "target_client",
        "act": {
            "azp": "source_client"
        }        
    }
}
`

Audience and azp claim are now the same but that is perfectly acceptable by the OIDC spec as it says about the azp claim (which is optional):
"It MAY be included even when the authorized party is the same as the sole audience."

I've implemented myself a fix by overriding the built-in DefaultTokenExchangeProvider and it works as expected. If you are ok with my suggestions, I am willing to write a pull request for this.

**Comment by mposolda** [comment]
Adding to Backlog as Keycloak team may not have time to look at this in the near future. We may revisit if supported token-exchange will turn into a priority.

**Comment by BeardInASuit** [comment]
@frelibert Can you share your fix? 

refresh_token returned from token-exchange are not usable by the target client (audience) because the AZP is not the target client.  The token endpoint that was used for token-exchange returns `"Invalid refresh token. Token client and authorized client don't match"` when using refresh_token.
