### ISSUE TITLE
Profile activation for WF app server doesn't properly work for Windows

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#21284]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

testsuite

### Describe the bug

As the documentation for the `activeByDefault` activation element states:
'This profile will automatically be active for all builds unless another profile in the same POM is activated using one of the previously described methods. All profiles that are active by default are automatically deactivated when a profile in the POM is activated on the command line or through its activation config.'

In the `testsuite/integration-arquillian/servers/app-server/jboss/pom.xml`, profile `windows-properties-cli` is implicitly enabled and the `activeByDefault` for WF app server is ignored same as the whole module.

You can see the WildFly app server module will not be built:
 
![image](https://github.com/keycloak/keycloak/assets/38039883/a6882c94-7255-4057-ab7b-7e1f9b176aea)

### Version

999

### Expected behavior

The module is built on Windows

### Actual behavior

The module is not built on Windows

### How to Reproduce?

`mvn clean install -Dtest=UserTest -f testsuite/integration-arquillian/pom.xml`

**Comment by ahus1** [comment]
Suggested workaround while this is being fixed: 
On Windows, add two profiles (Windows and the usual default profile) on the command line like this:

```
mvnw clean install -Pwindows-properties-cli,app-server-wildfly 
```

**Comment by Pepo48** [comment]
@mabartos (cc: @pedroigor) I think that this is also related to the changes introduced in #20976 - please, see my comment [here](https://github.com/keycloak/keycloak/issues/21716#issuecomment-1646987208).
