### ISSUE TITLE
EventListenerProvider hooked to transaction is causing ConcurrentModificationException

### ISSUE THREAD

**Issue by pawelgoc** [keycloak/keycloak#21297]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

We have custom implementation of **EventListenerProvider** where we are using **EventListenerTransaction** 

According to [documentation](https://www.keycloak.org/docs-api/21.1.1/javadocs/org/keycloak/events/EventListenerProvider.html) it suggesting to hook to transaction manager after complication.

Here is example 

```
    private final EventListenerTransaction transaction = new EventListenerTransaction(
            this::handleAdminEvent,
            this::handleClientEvent
    );
```

then in constructor we have

```
        this.keycloakSession
                .getTransactionManager()
                .enlistAfterCompletion(this.transaction);
  
```

Introduced changes in this [commit](https://github.com/keycloak/keycloak/commit/0d5363d0d5d9e503d101e17542ca768ded2bdc49#diff-6c641fd553097eb7d3a340bc4d676ff2c435bac772f3d57e343665c4bf867b6eR236) cause that `EventBuilder.error` send event immediately which cause ConcurrentModificationException.

```
Uncaught server error: java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
	at org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:144)
	at org.keycloak.services.DefaultKeycloakSession.closeTransactionManager(DefaultKeycloakSession.java:502)
	at org.keycloak.services.DefaultKeycloakSession.close(DefaultKeycloakSession.java:469)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:274)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:255)
	at org.keycloak.events.EventBuilder.send(EventBuilder.java:237)
	at org.keycloak.events.EventBuilder.error(EventBuilder.java:224)
``` 

On the other hand `EventBuilder.success` works fine.

Currently workaround is to check if event is triggered as successful or error action 

```
    @Override
    public void onEvent(Event event) {
        if (event.getError() != null) {
            handleClientEvent(event);
        } else {
            transaction.addEvent(event);
        }
    }
```

### Version

21.1.1

### Expected behavior

Event listener should works in transactional mode regardless of how event has been dispatched.

### Actual behavior

Event listener in transactional mode crash app when triggered type of event is kind of error e.g. providing invalid credentials will trigger event LOGIN_ERORR.

### How to Reproduce?

Make event listener to run in transaction and trigger any error event e.g. LOGIN_ERROR

Below simplified custom event listener that is crashing 

```
public class CustomEventListenerProvider implements EventListenerProvider {
    private final KeycloakSession keycloakSession;

    private final EventListenerTransaction transaction = new EventListenerTransaction(
            this::handleAdminEvent,
            this::handleClientEvent
    );

    public CustomEventListenerProvider(
            KeycloakSession keycloakSession
    ) {
        this.keycloakSession = keycloakSession;

        this.keycloakSession
                .getTransactionManager()
                .enlistAfterCompletion(this.transaction);
    }

    @Override
    public void onEvent(Event event) {
            transaction.addEvent(event);
       
    }

    @Override
    public void onEvent(AdminEvent event, boolean includeRepresentation) {
            transaction.addAdminEvent(event, includeRepresentation);
    }

    @Override
    public void close() {
    }

    private void handleClientEvent(Event event) {
      // http request
    }
    
    private void handleAdminEvent(AdminEvent event, boolean includeRepresentation) {
      // http request
    }
```

**Comment by pedroigor** [comment]
We had a similar fix https://github.com/keycloak/keycloak/pull/20793. Caused by the same change set you linked in the description. They are probably related.

**Comment by pedroigor** [comment]
@pawelgoc Would you be able to check the nightly build/container-image? We have a test that should cover this scenario and it is running fine in upstream.

**Comment by pawelgoc** [comment]
@pedroigor 
thanks for reply to reported issue.

Yes now both success and error kind of events are handled in transactional mode.

**Comment by pedroigor** [comment]
@pawelgoc Thanks for the update.

**Comment by kvnlin** [comment]
Is this issue confirmed to be fixed? I've been getting the same `java.util.ConcurrentModificationException` on 22.0.1 on `LOGIN_ERROR` events
