### ISSUE TITLE
Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by gjain-sag** [keycloak/keycloak#21293]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Hi Team,

After upgrading to 21.1.1 we are seeing "Lock wait timeout exceeded; try restarting transaction" issue in our Keycloack nodes due to which some of the realm creation is failing. I am attaching stack trace [error.json] for more  information.

While running our automation test which comprise of multiple realm creation we have experienced this error.
Our setup is running in clustered mode on Aurora-Mysql 8.x 

### Version

21.1.1

### Expected behavior

Realm Creation should be successful

### Actual behavior
```
Lock wait timeout exceeded; try restarting, Uncaught server error
"threadName": "executor-thread-0",
    "threadId": 18,
    "mdc": {},
    "ndc": "",
    "hostName": "kc-13-prospectfarm1-aw-us-0",
    "processName": "QuarkusEntryPoint",
    "processId": 1,
    "exception": {
        "refId": 1,
        "exceptionType": "org.keycloak.models.ModelException",
        "message": "javax.persistence.PessimisticLockException: could not execute statement",
        "frames": [
            {
                "class": "org.keycloak.connections.jpa.PersistenceExceptionConverter",
                "method": "convert",
                "line": 84
            },
            {
                "class": "org.keycloak.connections.jpa.PersistenceExceptionConverter",
                "method": "invoke",
                "line": 62
            },
            {
                "class": "jdk.proxy2.$Proxy71",
                "method": "flush"
            },
            {
                "class": "org.keycloak.models.jpa.RealmAdapter",
                "method": "setMasterAdminClient",
                "line": 1181
            },
            {
                "class": "org.keycloak.services.managers.RealmManager",
                "method": "createMasterAdminManagement",
                "line": 337
            },
            {
                "class": "org.keycloak.services.managers.RealmManager",
                "method": "setupMasterAdminManagement",
                "line": 310
            },
            {
                "class": "org.keycloak.services.managers.RealmManager",
                "method": "importRealm",
                "line": 539
            },
            {
                "class": "org.keycloak.services.managers.RealmManager",
                "method": "importRealm",
                "line": 504
            },
            {
                "class": "org.keycloak.services.managers.RealmManagerProviderFactory",
                "method": "lambda$postInit$0",
                "line": 54
            },
            {
                "class": "org.keycloak.services.DefaultKeycloakSessionFactory",
                "method": "publish",
                "line": 91
            },
            {
                "class": "org.keycloak.storage.ImportRealmFromRepresentationEvent",
                "method": "fire",
                "line": 50
            },
            {
                "class": "org.keycloak.storage.datastore.LegacyExportImportManager",
                "method": "importRealm",
                "line": 159
            },
            {
                "class": "org.keycloak.services.resources.admin.RealmsAdminResource",
                "method": "importRealm",
                "line": 133
            },
            {
                "class": "jdk.internal.reflect.NativeMethodAccessorImpl",
                "method": "invoke0"
            },
            {
                "class": "jdk.internal.reflect.NativeMethodAccessorImpl",
                "method": "invoke",
                "line": 77
            },
            {
                "class": "jdk.internal.reflect.DelegatingMethodAccessorImpl",
                "method": "invoke",
                "line": 43
            },
            {
                "class": "java.lang.reflect.Method",
                "method": "invoke",
                "line": 568
            },
            {
                "class": "org.jboss.resteasy.core.MethodInjectorImpl",
                "method": "invoke",
                "line": 170
            },
            {
                "class": "org.jboss.resteasy.core.MethodInjectorImpl",
                "method": "invoke",
                "line": 130
            },
            {
                "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
                "method": "internalInvokeOnTarget",
                "line": 660
            },
            {
                "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
                "method": "invokeOnTargetAfterFilter",
                "line": 524
            },
            {
                "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
                "method": "lambda$invokeOnTarget$2",
                "line": 474
            },
            {
                "class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
                "method": "filter",
                "line": 364
            },
            {
                "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
                "method": "invokeOnTarget",
                "line": 476
            },
            {
                "class": "org.jboss.resteasy.core.ResourceMethodInvoker",
                "method": "invoke",
                "line": 434
            },
            {
                "class": "org.jboss.resteasy.core.ResourceLocatorInvoker",
                "method": "invokeOnTargetObject",
                "line": 192
            },
            {
                "class": "org.jboss.resteasy.core.ResourceLocatorInvoker",
                "method": "invoke",
                "line": 141
            },
            {
                "class": "org.jboss.resteasy.core.ResourceLocatorInvoker",
                "method": "invoke",
                "line": 32
            },
            {
                "class": "org.jboss.resteasy.core.SynchronousDispatcher",
                "method": "invoke",
                "line": 492
            },
            {
                "class": "org.jboss.resteasy.core.SynchronousDispatcher",
                "method": "lambda$invoke$4",
                "line": 261
            },
            {
                "class": "org.jboss.resteasy.core.SynchronousDispatcher",
                "method": "lambda$preprocess$0",
                "line": 161
            },
            {
                "class": "org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext",
                "method": "filter",
                "line": 364
            },
            {
                "class": "org.jboss.resteasy.core.SynchronousDispatcher",
                "method": "preprocess",
                "line": 164
            },
            {
                "class": "org.jboss.resteasy.core.SynchronousDispatcher",
                "method": "invoke",
                "line": 247
            },
            {
                "class": "io.quarkus.resteasy.runtime.standalone.RequestDispatcher",
                "method": "service",
                "line": 73
            },
            {
                "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
                "method": "dispatch",
                "line": 151
            },
            {
                "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
                "method": "handle",
                "line": 82
            },
            {
                "class": "io.quarkus.resteasy.runtime.standalone.VertxRequestHandler",
                "method": "handle",
                "line": 42
            },
            {
                "class": "io.vertx.ext.web.impl.RouteState",
                "method": "handleContext",
                "line": 1284
            },
            {
                "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
                "method": "iterateNext",
                "line": 173
            },
            {
                "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
                "method": "next",
                "line": 200
            },
            {
                "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
                "method": "handle",
                "line": 84
            },
            {
                "class": "io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2",
                "method": "handle",
                "line": 71
            },
            {
                "class": "io.vertx.ext.web.impl.RouteState",
                "method": "handleContext",
                "line": 1284
            },
            {
                "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
                "method": "iterateNext",
                "line": 173
            },
            {
                "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
                "method": "next",
                "line": 200
            },
            {
                "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$6",
                "method": "handle",
                "line": 430
            },
            {
                "class": "io.quarkus.vertx.http.runtime.VertxHttpRecorder$6",
                "method": "handle",
                "line": 408
            },
            {
                "class": "io.vertx.ext.web.impl.RouteState",
                "method": "handleContext",
                "line": 1284
            },
            {
                "class": "io.vertx.ext.web.impl.RoutingContextImplBase",
                "method": "iterateNext",
                "line": 173
            },
            {
                "class": "io.vertx.ext.web.impl.RoutingContextWrapper",
                "method": "next",
                "line": 200
            },
            {
                "class": "org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter",
                "method": "lambda$createBlockingHandler$0",
                "line": 82
            },
            {
                "class": "io.quarkus.vertx.core.runtime.VertxCoreRecorder$14",
                "method": "runWith",
                "line": 576
            },
            {
                "class": "org.jboss.threads.EnhancedQueueExecutor$Task",
                "method": "run",
                "line": 2449
            },
            {
                "class": "org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
                "method": "run",
                "line": 1478
            },
            {
                "class": "org.jboss.threads.DelegatingRunnable",
                "method": "run",
                "line": 29
            },
            {
                "class": "org.jboss.threads.ThreadLocalResettingRunnable",
                "method": "run",
                "line": 29
            },
            {
                "class": "io.netty.util.concurrent.FastThreadLocalRunnable",
                "method": "run",
                "line": 30
            },
            {
                "class": "java.lang.Thread",
                "method": "run",
                "line": 833
            }
        ],
        "causedBy": {
            "exception": {
                "refId": 2,
                "exceptionType": "javax.persistence.PessimisticLockException",
                "message": "could not execute statement",
                "frames": [
                    {
                        "class": "org.hibernate.internal.ExceptionConverterImpl",
                        "method": "wrapLockException",
                        "line": 273
                    },
                    {
                        "class": "org.hibernate.internal.ExceptionConverterImpl",
                        "method": "convert",
                        "line": 108
                    },
                    {
                        "class": "org.hibernate.internal.ExceptionConverterImpl",
                        "method": "convert",
                        "line": 181
                    },
                    {
                        "class": "org.hibernate.internal.ExceptionConverterImpl",
                        "method": "convert",
                        "line": 188
                    },
                    {
                        "class": "org.hibernate.internal.SessionImpl",
                        "method": "doFlush",
                        "line": 1411
                    },
                    {
                        "class": "org.hibernate.internal.SessionImpl",
                        "method": "flush",
                        "line": 1394
                    },
                    {
                        "class": "jdk.internal.reflect.NativeMethodAccessorImpl",
                        "method": "invoke0"
                    },
                    {
                        "class": "jdk.internal.reflect.NativeMethodAccessorImpl",
                        "method": "invoke",
                        "line": 77
                    },
                    {
                        "class": "jdk.internal.refle"
                    }
```
### How to Reproduce?

Create multiple realms in loop to reproduce this. We are able to reproduce this is very regular manner

### Anything else?

N/A

**Comment by kkcmadhu** [comment]
i too see this in my application, and this  mostly happens when 2 or  more realm creation is in progress or in deletion..
this issue is killing us actually..

**Comment by kkcmadhu** [comment]
`
------------------------
LATEST DETECTED DEADLOCK
------------------------
2023-07-03 10:24:24 0x40022fe05ef0
** (1) TRANSACTION:
TRANSACTION 41137865, ACTIVE 18 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 1182 lock struct(s), heap size 139472, 3393 row lock(s), undo log entries 1152
MySQL thread id 5076, OS thread handle 70369163140848, query id 3508607 10.0.140.38 user1 updating
delete from REALM where ID='devps0112'

** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 891 page no 419 n bits 272 index IDX_COMPOSITE_CHILD of table `kc_2_1_1`.`COMPOSITE_ROLE` trx id 41137865 lock_mode X locks gap before rec
Record lock, heap no 62 PHYSICAL RECORD: n_fields 2; compact format; info bits 32
 0: len 30; hex 62653635373665612d386138642d343432662d396537332d356339373334; asc be6576ea-8a8d-442f-9e73-5c9734; (total 36 bytes);
 1: len 30; hex 38653563313961642d316237362d346233392d386561662d343464386135; asc 8e5c19ad-1b76-4b39-8eaf-44d8a5; (total 36 bytes);

Record lock, heap no 95 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 30; hex 62653639663761312d326436632d346638362d613838652d333134373263; asc be69f7a1-2d6c-4f86-a88e-31472c; (total 36 bytes);
 1: len 30; hex 64313039643132332d653634302d343133362d393461342d303930343535; asc d109d123-e640-4136-94a4-090455; (total 36 bytes);

Record lock, heap no 161 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 30; hex 62663839623761372d333631392d346666362d383131612d333332303934; asc bf89b7a7-3619-4ff6-811a-332094; (total 36 bytes);
 1: len 30; hex 64313039643132332d653634302d343133362d393461342d303930343535; asc d109d123-e640-4136-94a4-090455; (total 36 bytes);


** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 967 page no 5 n bits 480 index UK_ORVSDMLA56612EAEFIQ6WL5OI of table `kc_2_1_1`.`REALM` trx id 41137865 lock_mode X locks rec but not gap waiting
Record lock, heap no 413 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 9; hex 646576707330313132; asc devps0112;;
 1: len 9; hex 646576707330313132; asc devps0112;;


** (2) TRANSACTION:
TRANSACTION 41137813, ACTIVE 39 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 44 lock struct(s), heap size 8400, 40 row lock(s), undo log entries 46
MySQL thread id 5188, OS thread handle 70369163411184, query id 3512767 10.0.142.148 sciadmin update
insert into COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) values ('d109d123-e640-4136-94a4-09045559dc68', 'be68ebcf-b14f-4524-881e-8f94c4e7ab9a')

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 967 page no 5 n bits 480 index UK_ORVSDMLA56612EAEFIQ6WL5OI of table `kc_2_1_1`.`REALM` trx id 41137813 lock mode S
Record lock, heap no 413 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 9; hex 646576707330313132; asc devps0112;;
 1: len 9; hex 646576707330313132; asc devps0112;;


** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 891 page no 419 n bits 272 index IDX_COMPOSITE_CHILD of table `kc_2_1_1`.`COMPOSITE_ROLE` trx id 41137813 lock_mode X locks gap before rec insert intention w
aiting
Record lock, heap no 95 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 30; hex 62653639663761312d326436632d346638362d613838652d333134373263; asc be69f7a1-2d6c-4f86-a88e-31472c; (total 36 bytes);
 1: len 30; hex 64313039643132332d653634302d343133362d393461342d303930343535; asc d109d123-e640-4136-94a4-090455; (total 36 bytes);

** WE ROLL BACK TRANSACTION (2)
------------
TRANSACTIONS
------------
Trx id counter 41140517
Purge done for trx's n:o < 41140517 undo n:o < 0 state: running but idle
History list length 2275
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 351844119358088, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119352664, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119368936, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119369840, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119368032, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119366224, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119364416, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119356280, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119354472, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119365320, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119353568, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119359896, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119355376, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119357184, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119377072, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119362608, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119351760, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119373456, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119350856, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119358992, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119349952, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 351844119349048, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
--------
FILE I/O
--------
I/O thread 0 state: waiting for i/o request (insert buffer thread)
I/O thread 1 state: waiting for i/o request (log thread)
I/O thread 2 state: waiting for i/o request (read thread)
I/O thread 3 state: waiting for i/o request (write thread)
I/O thread 4 state: waiting for i/o request (write thread)
I/O thread 5 state: waiting for i/o request (write thread)
I/O thread 6 state: waiting for i/o request (write thread)
Pending normal aio reads:, aio writes: [0, 0, 0, 0] ,
 ibuf aio reads:, log i/o's:, sync i/o's:
Pending flushes (fsync) log: 0; buffer pool: 0
0 OS file reads, 0 OS file writes, 0 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 0.00 writes/s, 0.00 fsyncs/s
`

**Comment by kkcmadhu** [comment]
--TRANSACTION 41142037, ACTIVE 19 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 10 lock struct(s), heap size 1136, 5 row lock(s), undo log entries 27
MySQL thread id 5084, OS thread handle 70377987325680, query id 3974828 10.0.140.38 sciadmin updating
update KEYCLOAK_ROLE set CLIENT=null, CLIENT_REALM_CONSTRAINT='master', CLIENT_ROLE=0, DESCRIPTION='${role_admin}', NAME='admin', REALM_ID='master' where ID='d109d123-e640-4136-94a4-09
045559dc68'
Trx read view will not see trx with id >= 41142038, sees < 41141921
------- TRX HAS BEEN WAITING 18 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 983 page no 734 n bits 152 index PRIMARY of table `kc_21_1`.`KEYCLOAK_ROLE` trx id 41142037 lock_mode X locks rec but not gap waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 10; compact format; info bits 0
 0: len 30; hex 64313039643132332d653634302d343133362d393461342d303930343535; asc d109d123-e640-4136-94a4-090455; (total 36 bytes);
 1: len 6; hex 00000273c6a1; asc    s  ;;
 2: len 7; hex 020000008f0675; asc       u;;
 3: len 9; hex 7363696d6173746572; asc master;;
 4: len 1; hex 00; asc  ;;
 5: len 13; hex 247b726f6c655f61646d696e7d; asc ${role_admin};;
 6: len 5; hex 61646d696e; asc admin;;
 7: len 9; hex 7363696d6173746572; asc master;;
 8: SQL NULL;
 9: SQL NULL;

------------------
---TRANSACTION 41142003, ACTIVE 38 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 10 lock struct(s), heap size 1136, 5 row lock(s), undo log entries 27
MySQL thread id 5076, OS thread handle 70377987596016, query id 3969393 10.0.140.38 sciadmin updating
update KEYCLOAK_ROLE set CLIENT=null, CLIENT_REALM_CONSTRAINT='master', CLIENT_ROLE=0, DESCRIPTION='${role_admin}', NAME='admin', REALM_ID='master' where ID='d109d123-e640-4136-94a4-09
045559dc68'
Trx read view will not see trx with id >= 41142004, sees < 41141907
------- TRX HAS BEEN WAITING 38 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 983 page no 734 n bits 152 index PRIMARY of table `kc_21_1`.`KEYCLOAK_ROLE` trx id 41142003 lock_mode X locks rec but not gap waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 10; compact format; info bits 0
 0: len 30; hex 64313039643132332d653634302d343133362d393461342d303930343535; asc d109d123-e640-4136-94a4-090455; (total 36 bytes);
 1: len 6; hex 00000273c6a1; asc    s  ;;
 2: len 7; hex 020000008f0675; asc       u;;
 3: len 9; hex 7363696d6173746572; asc master;;
 4: len 1; hex 00; asc  ;;
 5: len 13; hex 247b726f6c655f61646d696e7d; asc ${role_admin};;
 6: len 5; hex 61646d696e; asc admin;;
 7: len 9; hex 7363696d6173746572; asc master;;
 8: SQL NULL;
 9: SQL NULL;


--TRANSACTION 41141921, ACTIVE 70 sec
258 lock struct(s), heap size 41168, 359 row lock(s), undo log entries 1579
MySQL thread id 5367, OS thread handle 70369162600176, query id 3976734 10.0.137.10 user1
Trx read view will not see trx with id >= 41141922, sees < 41141801

**Comment by kkcmadhu** [comment]
clearly update KEYCLOAK_ROLE set CLIENT=null, CLIENT_REALM_CONSTRAINT='master', CLIENT_ROLE=0, DESCRIPTION='${role_admin}', NAME='admin', REALM_ID='master' where ID='d109d123-e640-4136-94a4-09
045559dc68' is the biggest bottle neck.. 
 i guess, updating the master realm every time a realm is created/deleted..

**Comment by mhajas** [comment]
thanks for the report @gjain-sag and @kkcmadhu. I am not able to reproduce. Can you please try the latest Keycloak release? 

For the record how I tried to reproduce: 
```
@Test
public void testRealmCreation() throws InterruptedException {
    AtomicInteger integer = new AtomicInteger(0);
    ExecutorService service = Executors.newFixedThreadPool(10);
    CountDownLatch latch = new CountDownLatch(100);

    for (int i = 0; i < 100; i++) {
        service.submit(() -> {
            try {
                RealmRepresentation realm = new RealmRepresentation();
                realm.setRealm("realm-" + integer.incrementAndGet());
                System.out.println("creating realm " + realm.getRealm());
                adminClient.realms().create(realm);
                latch.countDown();
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
    }

    latch.await();

    System.out.println("realm: " + adminClient.realms().findAll().size());

    service.shutdown();
}
```

How to run the test in the test suite:
1. Copy the test to some test class in the testsuite I used [`LoginTest`](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/LoginTest.java#L161)
2. Run the test with the following command: `mvn test -f testsuite/integration-arquillian/tests/base/pom.xml -Dtest=LoginTest#testRealmCreation -Pauth-server-quarkus,db-mysql` (don't forget to build integration-arquillian with the given profiles first)
3. The test passes
