### ISSUE TITLE
integration-arquillian-servers-app-server-wildfly

### ISSUE THREAD

**Issue by jian-111** [keycloak/keycloak#21305]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dependencies

### Describe the bug

org.keycloak.testsuite:integration-arquillian-servers-app-server-wildfly:jar:999.0.0-SNAPSHOT was not found in https://s01.oss.sonatype.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced

### Version

20.0/21.1

### Expected behavior

.

### Actual behavior

.

### How to Reproduce?

.

### Anything else?

no

**Comment by Redhat-Alice** [comment]
I am also consistently running into this issue with no solution. Has there been any progress in this area?
