### ISSUE TITLE
3rd party check in iframe not working anymore in safari and keycloak 21.1.2

### ISSUE THREAD

**Issue by joggeli34** [keycloak/keycloak#21307]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

We are using oidc to login from a angular spa. After the ugpgrade to 21.1.2, the safari login does not work anymore throwing the exception "Timeout when waiting for 3rd party check iframe message."

So this has probably to do with the changes added in #19835

### Version

21.1.2

### Expected behavior

Login should work also in safari

### Actual behavior

It hangs in the "step1.html" for the third party check.

### How to Reproduce?

Try to login to a SPA with OIDC in Safari (16.5 17615.2.9.11.6) with 'check-sso' enabled

**Comment by jonkoops** [comment]
Thanks for the report @joggeli34, I'll see if I can reproduce this problem as well.

**Comment by gjherbiet** [comment]
I can confirm the bug is present in 21.1.2.
Before upgrade no issues

**Comment by marviobezerra** [comment]
I'm facing the same issue. 

I tried the versions 21.1.2, 21.1.1, and 21.0.1 with no luck.
iPhone users are not able to login regardless the browser (tested on Safari, Chrome, Firefox, and Brave).
The same is happening on Safari and Firefox on Mac. Chrome is the only browser working.

Firefox throws two errors:

First:

```
Uncaught TypeError: 'storage-access' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    hasStorageAccess https://auth.testerpals.com/realms/development/protocol/openid-connect/3p-cookies/step1.html:32
    async* https://auth.testerpals.com/realms/development/protocol/openid-connect/3p-cookies/step1.html:9
```

Second:

```
Timeout when waiting for 3rd party check iframe message.
```

**Comment by jonkoops** [comment]
Created a fix for this issue under #21325. It seems the Permission API can sometimes throw an exception, presumably Safari expects the user to explicitly confirm access to certain permissions, which is not possible in an iframe.

Handling the exception and falling back to our redirect flow to detect 3rd-party cookie support seems to resolve this issue.

**Comment by marviobezerra** [comment]
Hey @jonkoops. Thanks for the fast response.

**Comment by jonkoops** [comment]
The PR has been merged, if you'd like to try out and verify this fix you can use the [nightly version] of Keycloak. We're expecting a release for 22.0.0 relatively soon (can't give an exact timeline), and this fix will come along with that version.

**Comment by marviobezerra** [comment]
Due to the severity, does it deserve a release?I mean for the JS client and not the whole suite. 

I have clients unable to login and installing the nightly release will bring other changes that I’m not aware of.

**Comment by marviobezerra** [comment]
Just to be clear, all iPhone and iPad users are unable to login. Mac and Windows users only can login using Chrome.

**Comment by scspijker** [comment]
Same problem in our applications. Only work-around client side is to turn off "Prevent cross-site tracking" in Safari.

**Comment by jonkoops** [comment]
> Just to be clear, all iPhone and iPad users are unable to login. Mac and Windows users only can login using Chrome.

From my testing what is in the current stable also works in Firefox, just not on older versions.

**Comment by hlavki** [comment]
I have same issue with latest Firefox 114.02 on linux and keycloak 21.1.2.

**Comment by jonkoops** [comment]
I am running Firefox 114.0.2 right now, and I am unable to reproduce this issue. Either way, this should be fixed in the next release.

**Comment by hlavki** [comment]
It's probably caused by usage of `http:localhost`. When I try it with `https` and valid certificate, it works!

**Comment by jonkoops** [comment]
That could be the reason, I've been testing things locally on a secure domain.

**Comment by valentindruon** [comment]
Downgrade to 21.1.1 solved it for us.
We couldn't upgrade to 22.0 to solve the problem as we are waiting Bitnami Helm chart for this version

Thanks for the info !

**Comment by jonkoops** [comment]
Yeah, this should be fixed in the 22 release. So please try it out and let us know if there are any issues in this regard.

**Comment by marviobezerra** [comment]
22 fixed the issue for me. I updated the js client and the server too (I’m not sure if need both to fix it)

**Comment by jonkoops** [comment]
>  I updated the js client and the server too (I’m not sure if need both to fix it)

Updating the server should be enough, but it's always a good idea to update both. Thanks for verifying this!

**Comment by lazka** [comment]
I'm getting this with an older Firefox which we used in CI (Safari 14 should also be affected https://caniuse.com/mdn-javascript_operators_await_top_level)

```
Uncaught SyntaxError: top level await is not currently supported step1.html:9:10
```

the code is still here: https://github.com/keycloak/keycloak/blob/2b04008b097770a6a5a20587beabc299dabaf8b6/services/src/main/resources/org/keycloak/protocol/oidc/endpoints/3p-cookies-step1.html#L9

Is this something which should be addressed and should I open a new bug report for this?

**Comment by jonkoops** [comment]
We no longer support the aforementioned browsers, so I don't think it makes sense to log an issue for them. I'd recommend to upgrade your CI to a supported version of Firefox.

**Comment by lazka** [comment]
I see, fair enough, thanks.

(the CI version I don't care about, but I still have a few Safari 14 users it seems, oh well 😅)

**Comment by jonkoops** [comment]
Sorry to hear that is causing issues. Can I ask what share of these users are?

**Comment by lazka** [comment]
> Sorry to hear that is causing issues. Can I ask what share of these users are?

I've just re-checked, it's only ~0.5% this month, so not that much, and no one has complained yet, so maybe it's time we drop support too (This is in a university context, where we don't have control over user devices, and students don't have the newest hardware)

**Comment by jonkoops** [comment]
Thanks for letting us know. I am always willing to re-consider this stance if a large amount of users are experiencing issues, but it looks like this only affects a small group of users. Perhaps the right thing here would be indeed to drop support for said users.

**Comment by jonkoops** [comment]
@ozkank feel free to log an issue if you can reproduce this with Keycloak JS in a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Do note that the library you are using [is deprecated](https://github.com/react-keycloak/react-keycloak#warning-deprecated-and-unmaintained).

**Comment by bekwam** [comment]
I'm getting this error on 21.1.2 with Firefox 11.6 (latest) on both Windows and Linux.

The adapter works for Chrome (both platforms) and Edge.

**Comment by bekwam** [comment]
I'm getting this with Firefox 11.6.0 (latest) on both Windows and Linux.  

The app is using the following NPM packages

-     "keycloak-angular": "^14.0.0",
-     "keycloak-js": "^21.1.2",

The server is 21.1.2.  It's working with Chrome (both platforms) and Edge.

**Comment by jonkoops** [comment]
@bekwam I'd recommend you open up a new issue with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), so that we can verify the problem.

**Comment by kabilJbeli** [comment]
Hello I'm getting this error with chrome v116.0.5845.96

**Comment by akhi-ninja** [comment]
@jonkoops  I am facing same issue in Safari . The hidden iframe is causing this issue i think, safari did not  support cookie in browser as default 

`function check3pCookiesSupported() {
            var promise = createPromise();
            if (loginIframe.enable || kc.silentCheckSsoRedirectUri) {
                var iframe = document.createElement('iframe');
                iframe.setAttribute('src', kc.endpoints.thirdPartyCookiesIframe());
                iframe.setAttribute('title', 'keycloak-3p-check-iframe' );
                iframe.style.display = 'none';
                document.body.appendChild(iframe);
                var messageCallback = function(event) {
                    if (iframe.contentWindow !== event.source) {
                        return;
                    }
                    if (event.data !== "supported" && event.data !== "unsupported") {
                        return;
                    } else if (event.data === "unsupported") {
                        loginIframe.enable = false;
                        if (kc.silentCheckSsoFallback) {
                            kc.silentCheckSsoRedirectUri = false;
                        }
                        logWarn("[KEYCLOAK] 3rd party cookies aren't supported by this browser. checkLoginIframe and " +
                            "silent check-sso are not available.");
                    }
                    document.body.removeChild(iframe);
                    window.removeEventListener("message", messageCallback);
                    promise.setSuccess();
                };
                window.addEventListener('message', messageCallback, false);
            } else {
                promise.setSuccess();
            }
            return applyTimeoutToPromise(promise.promise, kc.messageReceiveTimeout, "Timeout when waiting for 3rd party check iframe message.");
        }`

i this above function casing issue 

hope this will help

**Comment by jonkoops** [comment]
@akhi-ninja this issue was fixed, you are likely not on the right version of Keycloak. If the issue does still occur on the latest version of Keycloak (and Keycloak JS) then feel free to submit an issue with steps to reproduce.
