### ISSUE TITLE
Declarative User Profile attribute that is only editable by admin can be set by user

### ISSUE THREAD

**Issue by carlin-q-scott** [keycloak/keycloak#21304]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

The admin permissions for a user profile attribute seem to apply to a non-admin with manage-users role. As a user with manage-users role, I can add the attribute from the attributes tab but not see it. However I can then see that my update was successful when viewing the user profile as an admin. 

If I remove the ability of the admin to edit the attribute, then the same action fails stating:
> Error updating group Attribute Host is read only.

If I make it so only the user can edit the attribute, then they cannot edit it. So I think the permission check for the user is always using the admin permission.

### Version

21.1.1

### Expected behavior

User should not be able to edit an attribute that they do not have permission to.

### Actual behavior

User cannot see the attribute, but they can edit it as long as the admin can edit it.

### How to Reproduce?

1. Enable Declarative User Profile.
2. Log in to Keycloak admin console.
3. Go to Realm Settings > User Profile.
4. Add a new attribute and only allow admin to edit the attribute.
5. Log in as a normal user with roles: query-users, manager-users and manage-account.
    These roles seem to be required for a user to be able to manager their own account beyond what's available from the account manager.
7. View your own profile.
8. Open the attributes tab.
9. Add the custom attribute defined earlier.
10. View the same user account as an admin.
11. The attribute should not have been set.

### Anything else?

related to #16054

**Comment by pedroigor** [comment]
@carlin-q-scott Can you confirm you are managing attributes through the admin console (or API)? If so, the behavior is correct because the administrator user (some of the roles you are granting indicate the user is a realm administrator with limited access) has access to the User API.

The permission model is based on the context of a request. In this case, the request is coming via Admin/User API and as such you should be able to manage the attribute.

**Comment by carlin-q-scott** [comment]
@pedroigor I'm using the admin console. 

There's a realm admin role that is not assigned to the user. I expected that to be the determining factor as to whether the user is an considered an admin or not. But it makes sense that the manage-users role could also be considered an admin. My use case is that I want to grant admins from other organizations the ability to manage their own users but not allow them to set certain group/user attributes that should only be set by my company's admins.

Do the user permissions apply to the account-console client, and admin permissions apply to the security-admin-console client? That would explain why the user permissions don't allow an admin to view/edit using the admin-console.

**Comment by sschu** [comment]
AFAIK, the admin permissions refer to the admin api (used by the security-admin-console) and the user permissions refer to the account api (used by the account-console).

**Comment by pedroigor** [comment]
@sschu +1.

@carlin-q-scott Unfortunately, we don't have yet a permission model for attributes that allows you to grant view/edit based on roles.

For Keycloak, and admin is any user allowed to operate on the Admin API. When you set that "only the admin can view/edit" you are basically enabling/disabling that attribute from the Admin API (and console).
