### ISSUE TITLE
Determine if the keycloak service should provide both ports keycloak service should provide both ports if http is enabled

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#21318]
### Description

Currently the keycloak service is opionated - if tls is enabled, then only the https port will be exposed.  The question is whether this is intentional - or should http be offered by the service as well if httpEnabled=true.

cc @vmuzikar

**Comment by tamis-laan** [comment]
"if tls is enabled, then only the https port will be exposed" 

I don't even see any option in the keycloak CRDs to disable tls.

**Comment by shawkins** [comment]
@tamis-laan if the tlsSecret is not populated, then http should be assumed.

**Comment by shawkins** [comment]
Marking this as a duplicate of #22131
