### ISSUE TITLE
Declarative User Profile blocks spaces in attribute name but they're allowed elsewhere

### ISSUE THREAD

**Issue by carlin-q-scott** [keycloak/keycloak#21328]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

User attributes can have spaces in them, but the Declarative User Profile feature blocks them with a regex.

### Version

21.1.1

### Expected behavior

I can have spaces in my user attributes

### Actual behavior

I cannot have spaces in my user attributes

### How to Reproduce?

Put spaces in a user attribute

### Anything else?

Spaces. In. User. Attributes.

**Comment by pedroigor** [comment]
@carlin-q-scott Could you elaborate more about the use case and why you need empty attribute values?

**Comment by carlin-q-scott** [comment]
@pedroigor I'm not asking for empty attribute values. The attribute name is not allowing spaces, but spaces are in fact allowed in attribute names.

**Comment by pedroigor** [comment]
I see. Could you please elaborate on how to reproduce the behavior?

**Comment by carlin-q-scott** [comment]
Sure.

1. Open admin console
2. Go to realm settings
3. User Profile tab
4. Create attribute button
5. Enter "Partner Name" in the name field
6. Click create

Expected Result: created
Actual Result: "Invalid attribute name (only letters, numbers and '.' '_' '-' special characters allowed): Partner Name']."

**Comment by pedroigor** [comment]
I see now. That is why we have the `Display Name` field so that you set a user-friendly name for your attribute.

The name itself is mainly for internal usage and is constrained by those characters.

Thanks for the report. I'm closing the issue.

**Comment by carlin-q-scott** [comment]
> The name itself is mainly for internal usage and is constrained by those characters.

That seems to be the case for the Declarative User Profile, but not the group or user attribute names. I expected them to have the same constraints.
