### ISSUE TITLE
when I try to get the list of users using API from postman, i am getting 403 {     "error": "unknown_error" }

### ISSUE THREAD

**Issue by premnkl** [keycloak/keycloak#21337]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I have downloaded 21.1.1 version and created a user using keycloak console. But when I try to get the list of user using API from postman, i am getting below error

with 18.0.2 we are able to get the list of users with the same request. 

Kindly let me know, if there is anything missed

![image](https://github.com/keycloak/keycloak/assets/108449384/84d6d028-f09f-4068-af2c-2337bccc9e69)

### Version

21.1.1

### Expected behavior

Using postman, we are trying to get the list of users

### Actual behavior

Using postman, when we try to get the list of users, it is throwing 
Status code: 403
{
    "error": "unknown_error"
}

### How to Reproduce?

try to get the list of users from postman with keycloak 21.1.1

**Comment by akbar1214** [comment]
@premnkl  how did you generate the token. The token length seems too small.

**Comment by premnkl** [comment]
Hello @akbar1214 
Thanks for your interest on the above question. I generated as below. Token is 1086 characters length

![image](https://github.com/keycloak/keycloak/assets/108449384/aab9c8d5-cb0c-400e-943a-80b9f1fe5c0e)

**Comment by sschu** [comment]
Have you tried removing the optional headers like Accept, Accept-Encoding, User-Agent and so on? Just to strip down the request to the bare minimum?

**Comment by akbar1214** [comment]
@premnkl I think this has to do with permission rather than keycloak bug. I think admin-cli is a public client and it does not have a service account role.

**Comment by sschu** [comment]
But he did not use service accounts/client credentials grant but direct access/username password grant and he seemed to receive a token. The token content would be interesting, though.

**Comment by premnkl** [comment]
@sschu @akbar1214 thanks for your responses. 

After mapping the realm-management role to the user, we are able to retrieve the data
