### ISSUE TITLE
Upgrade login theme to PatternFly 5

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#21342]
The login theme will have to be upgraded to the latest version of PatternFly.
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/29009
```

**Comment by ssilvert** [comment]
This is completed as we now have the `keycloak.v2` theme, which is PF5.  We just didn't get rid of the old PatternFly because we needed to keep Login V1 in the release.
