### ISSUE TITLE
session.invalidate(InvalidationHandler.ObjectType.USER, user) do not propagate information to infinispan caches

### ISSUE THREAD

**Issue by bamandine** [keycloak/keycloak#21346]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

I'm currently working on an issue with my Keycloak platform and could use some help. The platform is based on multiple Keycloak nodes with cross-site replication enabled. However, I'm experiencing a problem when it comes to replicating modifications across nodes using the Keycloak internal Infinispan.

I've created a custom provider that modifies user data. At the end of the function, I call `session.invalidate(InvalidationHandler.ObjectType.USER, user)` to invalidate the user data in the caches. The issue is that these modifications aren't getting replicated in the caches. I can only see the changes on one node, not on the others.

After some experimentation, I found that the following code block successfully propagates the modifications into the caches:

```java 
UserCache userCache = session.getProvider(UserCache.class);
if (userCache != null) {
   userCache.evict(realm, user);
}
```

However, I'm a bit concerned about using the `UserCache` class from the `keycloak-model-legacy` package. Shouldn't `session.invalidate()` be enough to handle this?

### Version

21.1.2

### Expected behavior

`session.invalidate(InvalidationHandler.ObjectType.USER, user)`  should invalidate user and propagate the information on all caches nodes.

### Actual behavior

`session.invalidate(InvalidationHandler.ObjectType.USER, user)` does not propagate the information on all caches nodes

### How to Reproduce?

1. Create a custom provider
2. In the provider, use those lines : 

```java
user.setEnabled(false);
session.invalidate(InvalidationHandler.ObjectType.USER, user);
```

3. Execute the provider on a plateform with multiple caches nodes
4. See that the user is disabled on one node, not on the others

### Anything else?

I have exposed this problem on slack and @ahus1 gave this response :
> I agree with your thoughts. Please the culprit is possibly InfinispanUserCacheProviderFactory#invalidate which should handle this by sending an invalidation to the caches in all Keycloak instances.
Looking at the code,  "InvalidationHandler.ObjectType.USER" is not used really anywhere, so it seems you are the first to use this one. For now, use the workaround you described above - at first sight, I assume this or similar code would need to be called there when using the session.invalidate()

**Comment by pedroigor** [comment]
Closing as not a bug because it is a non-supported usage of our SPIs.
