### ISSUE TITLE
Update bcpkix and bcprov dependencies

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#21360]
### Description

In Keycloak we currently use `bcpkix-jdk15on` and `bcprov-jdk15on` [dependencies](https://github.com/keycloak/keycloak/blob/main/pom.xml#L377-L386). [The Quarkus Platform BOM](https://github.com/quarkusio/quarkus-platform/blob/3.2.0.CR1/generated-platform-project/quarkus-operator-sdk/bom/pom.xml) provides us with `bcpkix-jdk18on` and `bcprov-jdk18on`.

The difference is about APIs compatibility for JDK - 1.5 and up vs. 1.8 and up.

@mposolda @pedroigor are there any concerns when it comes to upgrading these two?

This task serves as an follow-up of https://github.com/keycloak/keycloak/pull/21078.

**Comment by sschu** [comment]
Just as a note, there is also a current version for jdk15to18 but that's apparently not what Quarkus is using.

**Comment by pedroigor** [comment]
@Pepo48 I don't think there is. See https://www.bouncycastle.org/latest_releases.html.

Now we are based on JDK 17 we should be able to support multi-release JARs.

**Comment by vmuzikar** [comment]
This turned out to be a bigger change after all, so moving the milestone.

I found out that adapters are using BC `jdk15on` dependencies through `wildfly-feature-pack`. AFAIK, they might clash with the `jdk18on` dependencies. At the same time, I'm not sure we can simply exclude the `jdk15on` alternatives. I tried it in https://github.com/keycloak/keycloak/pull/21543 but we'll need to run the full test pipelines with it.

I set the milestone to a micro release for now. One thing to consider is if we can just remove the `jdk15on` deps in a micro release. We might need to wait for 23.

@pedroigor @sschu WDYT?

**Comment by pedroigor** [comment]
@vmuzikar I think we can go with your changes in https://github.com/keycloak/keycloak/pull/21543. The adapters should be JDK 1.8+ compliant anyways even though not what is coming from the feature pack.

**Comment by sschu** [comment]
@vmuzikar +1 to what Pedro said. I am also wondering whether we should do the same with the bc-fips dependencies, they are also in Quarkus?

**Comment by vmuzikar** [comment]
> I am also wondering whether we should do the same with the bc-fips dependencies, they are also in Quarkus?

@sschu I think we're not including the `bc-fips` deps any way as we [instruct](https://www.keycloak.org/server/fips#_bouncycastle_library) users to "sideload" them.

**Comment by sschu** [comment]
I found them as regular dependencies next to the normal bouncycastle stuff, see https://github.com/keycloak/keycloak/blob/99774b3f7a776476e7f04e472e13e3915971a6fb/pom.xml#L392-L406. But maybe I am missing something here?

**Comment by pedroigor** [comment]
We do not distribute those. See https://www.keycloak.org/server/fips#_bouncycastle_fips_bits.

But I agree with you and those should be resolved from Quarkus, right?

**Comment by pedroigor** [comment]
Isn't that a documentation issue? I mean, we are already referencing the BC version they should use.

But I'm not hard on resolving from Quarkus. I can see as beneficial to manage this one in our side too.

**Comment by vmuzikar** [comment]
Since we'd need to (manually) monitor the version changes to give users a heads-up in docs and migration guide, aligning with Quarkus BOM doesn't give us too much benefit, IMHO.

**Comment by sschu** [comment]
Fine for me, I wasn't aware they are not actually shipped.
