### ISSUE TITLE
Align Infinispan dependencies with the Quarkus Platform BOM

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#21363]
### Description

In Keycloak we currently use a newer version than the one provided in the platform BOM (ver. 3.2.0) - 14.0.9 compared to 14.0.10.

So, in order to align the Infinispan version right now, it would require a downgrade.
Any particular concerns when in comes to that?

This task serves as an follow-up of https://github.com/keycloak/keycloak/pull/21078.

**Comment by vmuzikar** [comment]
@Pepo48 I'd open a separate issue for guava

**Comment by Pepo48** [comment]
> @Pepo48 I'd open a separate issue for guava

done.

**Comment by vmuzikar** [comment]
@ahus1 @mhajas Are there any concerns around aligning (and in this case downgrading) ISPN with Quarkus BOM?

**Comment by ahus1** [comment]
@vmuzikar - version 14.0.10.Final contains fixes for example around ISPN-13053, therefore I'd like to keep it. There are some pending issues we might soon-ish upgrade to 14.0.11.Final once it is available, so I assume we'll stay ahead of Quarkus for a while.

This could be removed once Quarkus catches up, but for now I'd keep it.

**Comment by vmuzikar** [comment]
@ahus1 Then the question is whether we should even consider the alignment with Quarkus.
