### ISSUE TITLE
Align guava dependency with the Quarkus Platform BOM

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#21364]
### Description

In Keycloak we currently use a newer version of guava than the one provided in the platform BOM (ver. 3.2.0) - 32.0.1 vs. 32.0.0.

So, in order to align the guava version right now, it would require a downgrade.
Any particular concerns when in comes to that?

This task serves as an follow-up of https://github.com/keycloak/keycloak/pull/21078.

**Comment by vmuzikar** [comment]
Quarkus is using Guava 32 since Quarkus 3.2.0 release: https://github.com/quarkusio/quarkus-platform/blob/3.2.0.Final/generated-platform-project/quarkus/bom/pom.xml#L568
