### ISSUE TITLE
Extending the keycloak login theme results in 404 for common CSS files

### ISSUE THREAD

**Issue by darius-m** [keycloak/keycloak#21386]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

Extending the `keycloak/login` theme results in a badly rendered login page, as the files mentioned in the [stylesCommon](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/keycloak/login/theme.properties#L5) variable are not properly included in the generated theme. Requests to fetch the common CSS files result in 404 errors for all files in the list.

A workaround is to use the `styles` variable to explicitly mention all CSS files, while keeping the theme's files at the end, and resetting the `stylesCommon` variable to an empty value. A different workaround, that I have tested later seems to be to explicitly import the keycloak common. Both approaches make extending themes a lot harder and non-intuitive, as you need to dig into the parent theme's properties.

### Version

21.1.2

### Expected behavior

The CSS files mentioned in the `stylesCommon` variable in the keycloak login theme are accessible.

### Actual behavior

Requests to common CSS files result in 404 error messages.

### How to Reproduce?

Derive a theme (newtheme) from the Keycloak login that overrides some basic parameters (e.g. background image and font) and use the following as the theme's properties file.

```
parent=keycloak
import=common/newtheme

styles=css/login.css css/newtheme.css
```

After building and starting the Keycloak server, set the login theme to the new theme and access the login page. CSS files fail to load properly.

**Comment by ssilvert** [comment]
I think this might be fixed now by https://github.com/keycloak/keycloak/pull/20873

Can you give it a try in the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
@darius-m I'm going to close this now.  If you can try it in a recent build and still find issues then we can reopen.
