### ISSUE TITLE
Align h2 and mysql-connector-java dependencies with the Quarkus Platform BOM

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#21393]
### Description

We use the same dependency versions as the Quarkus Platform BOM provides. The dependency management is a bit more complex in this case though.

Thus, this should be discussed with the Store/QE teams first in order to approach it the best possible way.

This task serves as an follow-up of https://github.com/keycloak/keycloak/pull/21078.

**Comment by vmuzikar** [comment]
@ahus1 Any thoughts on this one?

**Comment by ahus1** [comment]
I'd be OK to sync those. The only reason I might see to have an earlier version on those would be to if one of them has a CVE which is not uncommon to both of them IMHO

**Comment by shawkins** [comment]
Marking as resolved. We do align to the quarkus version for our actual usage of the dependency. We still need to have a version in our pom for the way our database tests function.
