### ISSUE TITLE
Error message on user creation is not translated

### ISSUE THREAD

**Issue by gediminasre** [keycloak/keycloak#21424]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

On user registration form, select other than English language and enter invalid email. Error message is not translated to selected language. Message returned: `Invalid email address.` 
![image](https://github.com/keycloak/keycloak/assets/118281897/6799afc0-e154-4127-97f2-6e2ed6681154)
However, if you do not enter email, or enter already existing email, message gets translated successfully.
![image](https://github.com/keycloak/keycloak/assets/118281897/9cd7dc8e-71e8-49cc-a87a-4a2f2ebc970b)
![image](https://github.com/keycloak/keycloak/assets/118281897/37108552-3aa4-4e54-a2bb-75b13206d29f)

### Version

21.1.2

### Expected behavior

On user registration, error message is translated when provided email is invalid

### Actual behavior

On user registration, error message is not translated when provided email is invalid

### How to Reproduce?

Enable Internationalization, add additional languages (Deutsch, espanol). Set default locale Deutsch.
![image](https://github.com/keycloak/keycloak/assets/118281897/2dd33cab-b4d8-43ed-bc44-846d1f2d1a94)
Enable user registration
![image](https://github.com/keycloak/keycloak/assets/118281897/cb03e9fe-0516-4ea6-94b8-881991ce6a87)
Open login screen http://localhost:8080/realms/master/account/
Select language other than English
Click Register
Enter invalid email address
Click Register

**Comment by mposolda** [comment]
This applies to some other languages besides Spain. For instance it applies for German as well.

**Comment by thecooldrop** [comment]
I could take care of German if that helps anything.

**Comment by ch-lepp** [comment]
I opened a PR to add the missing German translations: https://github.com/keycloak/keycloak/pull/28962
