### ISSUE TITLE
{realm}/users endpoint requests failed with client timeout

### ISSUE THREAD

**Issue by antonnaumov** [keycloak/keycloak#21429]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

The Keycloak server is deployed in the k8s cluster with GCloud. The cluster contains two StatefulState nodes using the PostgreSQL database, and ISPN distributed cache.

In the same k8s cluster, the Golang service proxying the Keycloak Admin REST API is deployed in a different namespace.

The LinkerD service mech deployed into the k8s cluster and watched after all the services deployment and activities.

The Keycloak REST API works most of the time correctly until the HTTP client fails with client timeout. The timeouts do not lead to constant requests or server failure. It does seem like a single incident happening because of unclear reasons.
The Keycloak logs do not indicate any problems or unusual behavior during the incident.
It is a proven fact the request is not blocked by the network infrastructure, as well as latency is close to 0.

The following countermeasures were applied without success
 - implement graceful retry to the Keycloak API request in the case of the failure
 - increase client timeout
 - tune the HTTP client connection pool to make sure the client has enough connections to work in a high-load concurrent environment
 - tune HTTP client logic to make sure there is no connection leak in the course of retry processing

### Version

21.0.1

### Expected behavior

No HTTP client timeouts against up and running Keycloak server without trace in the logs

### Actual behavior

The Keycloak REST API works most of the time correctly until the HTTP client fails with client timeout

### How to Reproduce?

There is no clear why to reproduce such behavior

### Anything else?

It might be a correlation between Keycloak cluster reconciliation and how Keycloak web server handles requests, but there is no clear proof this is the cause of the problem. At least one time, the timeout happen without the cluster reconciliation.

**Comment by mposolda** [comment]
I am adding to Backlog as this is hard to reproduce and I have doubts if Keycloak team has time to look at this in the near future until we know more detais.

@antonnaumov It would be useful if you post here the exception stacktrace in case you see the issue again. When you mentioned countermeasures, did you changed the configuration of the HTTP client as mentioned here https://www.keycloak.org/server/outgoinghttp ?
