### ISSUE TITLE
Fine-grained authorization behavior for management of groups not working as expected

### ISSUE THREAD

**Issue by Chandan7944** [keycloak/keycloak#21420]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I am trying to manage permissions on group level for adding/removing members to group as described here [https://github.com/keycloak/keycloak/issues/17913](url) but getting 403 forbidden when adding user through 'Add User' button while removing existing users from the group works.

### Version

21.0.2

### Expected behavior

Upon assigning the role query-users as mentioned in the link [https://github.com/keycloak/keycloak/issues/17913](url) the certain users with right permissions should be able to add/remove users from the group.

### Actual behavior

By assigning query-users role I am able to view 'Add User' button in the UI but the functionality fails with forbidden error (validated this behavior with admin api as well).
Upon assigning manage-users role to the user, the 'Add User' functionality is working but user will have permission to manage all the groups instead of the group to which the user is owner.

### How to Reproduce?

Above behavior can be replicated by following the same steps as mentioned in the issue [https://github.com/keycloak/keycloak/issues/17913](url) the functionality fails with forbidden error upon assigning manager-users role the user will have ability to add/remove users from all groups.

### Anything else?
Is this the expected behavior and how to restrict access to groups only to certain users
_No response_

**Comment by jonkoops** [comment]
@Chandan7944 I see that you have checked the "I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)", but your reported version is 21.0.2. Did you test this against the latest nightly?

**Comment by sschu** [comment]
@Chandan7944 If I understand your scenario correctly, you are trying to add a user to a group you can manage. The thing is, in order to do that you already need to be able to manage the user. Therefore, you need to create the user already with the group membership of the group you can manage. Once the user is in the group, you can manage him and also remove him again. But if you lose the ability to manage him by removing him from the group, you cannot add him again. This is just how it is designed.

**Comment by Chandan7944** [comment]
> @Chandan7944 I see that you have checked the "I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)", but your reported version is 21.0.2. Did you test this against the latest nightly?

@jonkoops in my local env I did try it out with latest release and I was facing the same issue, since we are using 21.0.2 in prod I added the same version above

**Comment by Chandan7944** [comment]
> @Chandan7944 If I understand your scenario correctly, you are trying to add a user to a group you can manage. The thing is, in order to do that you already need to be able to manage the user. Therefore, you need to create the user already with the group membership of the group you can manage. Once the user is in the group, you can manage him and also remove him again. But if you lose the ability to manage him by removing him from the group, you cannot add him again. This is just how it is designed.

@sschu Just to make sure I understood properly keycloak provides ability for a user to add members to group only on assigning manager-users role but it doesn't restrict this to certain groups
Is there any way to enforce this in such a way that we can restrict user to add members to certain groups only. 
And also is there a plan to have a concept of owner or admin to groups? This seems like a standard feature and would be really helpful to manage groups.

**Comment by sschu** [comment]
The trick is to put a user in a group while creating it. Every admin can only create users in the groups he can manage. Then, he can add this user to another group if he can manage that group. However, you cannot add a user that already exists but is not in a group to another group unless you can manage all users.

**Comment by Chandan7944** [comment]
> The trick is to put a user in a group while creating it. Every admin can only create users in the groups he can manage. Then, he can add this user to another group if he can manage that group. However, you cannot add a user that already exists but is not in a group to another group unless you can manage all users.

I tested this out locally and this works great we can probably reorganize the way we create groups and implement this solution.
Just for my understanding can you please explain why this doesn't work in case when I try to add users from parent group to sub group.
@jonkoops  @sschu Is there any plan on introducing a concept of group owner or admin anytime soon?

**Comment by sschu** [comment]
I don't know of any plans to do this. However, you can have a kind of group owner using fine-grained permissions.
It should also work to add users from parent group to sub group, you just need to have manage-members on the parent group and manage-membership on the subgroup. You need to assign these permissions explicitely, there is no inheritance of fine-grained permissions from parent group to sub group.

**Comment by Chandan7944** [comment]
> I don't know of any plans to do this. However, you can have a kind of group owner using fine-grained permissions. It should also work to add users from parent group to sub group, you just need to have manage-members on the parent group and manage-membership on the subgroup. You need to assign these permissions explicitely, there is no inheritance of fine-grained permissions from parent group to sub group.

@sschu Got it and this works fine. Thank you so much!

**Comment by sschu** [comment]
You are welcome. I will go ahead and close this issue then.
