### ISSUE TITLE
Allow options to support any value in addition to a list of pre-defined values.

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#21439]
### Description

The use case is based on https://github.com/keycloak/keycloak/pull/21065.

There we have a `cache-stack` option backed by a well-defined list of values. Any value other than those defined as `expected` values are going to fail validation when using the CLI.

However, to make it easier to switch to different stacks without necessarily updating the cache configuration file (see https://www.keycloak.org/server/caching#_custom_transport_stacks), one might want to create a single cache configuration file with multiple custom stacks and switch to a specific stack configuration by setting the `cache-stack` option. Therefore, removing the need for updating the configuration and re-building a container image.

The proposal is to create a distinction between `expected` and `possible` option values where:

* `expected` values (as of today) represent a closed list of option values. Any other value is invalid.
* `possible` values represent an open list of option values. Any other value is possible and valid. We could still add some hints about the values we support but also enable users to set their own values, when needed.

This separation should help to properly manage the option values we support or provide OOTB and allow documenting the behavior when custom values are supported.

### Motivation

Make sure we have the same experience when using different configuration sources, mainly in terms of documentation and behavior.

* https://github.com/keycloak/keycloak/issues/21092#issuecomment-1623628953

**Comment by shawkins** [comment]
Validation can be customized once #24811 is merged.
