### ISSUE TITLE
Cookie error on second browser tab

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#21451]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I open the client URL in my browser and get redirected to the keycloak login page.
I enter my credentials, successfully authenticate and afterwards get redirected to the webpage of my client.

I open a second tab in my browser and in there again open the same client URL.
I get redirected to keycloak, keycloak notices me beeing loged in already and so I get redirected to the webpage of my client.

So far, so good.

Now I log out on that second tab.
My client redirects me to the Keycloak login screen where I can enter my credentials.
What I mean by that is:

- I get redirected to Domain/auth/realms/Realm/protocol/openid-connect/logout
- then I get redirected to the client_url
- then (cause I am not authenticated) I get redirected to Domain/auth/realms/Realm/protocol/openid-connect/auth

After entering my username and password, Keycloak presents me with the error "Cookie not found. Please make sure cookies are enabled in your browser.".
No exception is logged in the keycloak backend.
In the browser an AUTH_SESSION_ID and an AUTH_SESSION_ID_LEGACY cookie are available (the KC_RESTART cookie is missing, but that does not explain the error).

### Version

21.0.2

### Expected behavior

I should be able to properly log out from every browsertab.

### Actual behavior

When logged out from second browser tab, a cookie error is thrown.

### How to Reproduce?

1. Open browser tab 1 and log into keycloak client
2. Open browser tab 2 and navigate to keycloak client (be logged in cause of SSO)
3. Log out on tab 2
4. Relogin on tab 2
--> Cookie error

**Comment by pedroigor** [comment]
We had similar issues before after changing how we resolve sessions on the server-side from cookies. It might be related to https://github.com/keycloak/keycloak/commit/a1ab33778df468d5b9c1828918eedfe7faca1722.

**Comment by pedroigor** [comment]
@ch-lepp Did you try using the latest versions or even nightly? It might be fixed already.

**Comment by jonkoops** [comment]
I'll close this issue since this issue seems to be resolved in more recent versions. If the behavior persists let us know.

**Comment by ignatovladislav** [comment]
Hello there! I'm facing the same issue in the 22nd version of the keycloack within two tabs! Does anybody know how we could fix it? I've found the same issues for another version, such as 24, for instance:

The problem remains unanswered here
https://github.com/keycloak/keycloak/issues/11340#issuecomment-2258982427

Thanks for advance!

**Comment by jonkoops** [comment]
Those versions of Keycloak are no longer supported. If the problem still exists in the latest version please report a new issue.
