### ISSUE TITLE
Upgrade `react-error-boundary` to latest version

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#21515]
We're using the [`react-error-boundary`](https://github.com/bvaughn/react-error-boundary) package to render errors when something goes wrong the the Admin UI. We are however not using the latest version at this time, and the package should be upgraded.

**Comment by jonkoops** [comment]
@tirth1 If you want to take this one, I can assign you.

**Comment by tirth1** [comment]
@jonkoops sure, I'll work on this.

**Comment by jonkoops** [comment]
It's been a while since this issue was assigned, so I will clear the assignee so someone else can pick this up if they want.

**Comment by SaxenaAnushka102** [comment]
Hello @jonkoops! I'm a beginner & would love to know more on how can I contribute to this issue, thanks!

**Comment by jonkoops** [comment]
Hi @SaxenaAnushka102, we need someone to update the dependency and apply the necessary migrations for the [v4.0 version](https://github.com/bvaughn/react-error-boundary/releases/tag/4.0.0). Let me know if you are interested in taking this on.

**Comment by fdeguibert** [comment]
Hi @jonkoops I'm interested in taking this one if no one else does
I already have a first fix, just need to run some tests and check with you if everything is functionaly ok

**Comment by jonkoops** [comment]
Sure, I will assign this to you then @fdeguibert :+1:

**Comment by fdeguibert** [comment]
thanks (sorry I didn't see the notification earlier)

**Comment by fdeguibert** [comment]
@jonkoops this is pushed. Don't hesitate to tell me if I did anything wrong, this is my first PR on Keycloak, and basically my first PR on an open source project (It was about time to contribute to the open source community... ;) )

**Comment by jonkoops** [comment]
Thanks @fdeguibert, I'll take a look :)
