### ISSUE TITLE
Can create a user without the registration flow finished properly (reopened #17644)

### ISSUE THREAD

**Issue by vilmosnagy** [keycloak/keycloak#21514]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

Reopening #17644 as suggested on [Slack here](https://cloud-native.slack.com/archives/C056XU905S6/p1688643055350429?thread_ts=1688559314.400539&cid=C056XU905S6)

There was a PR (#19488) that stated to solve the issue, but it did not. It can be reproduced with the latest nightly at the moment.

I can create a User entity with the registration flow throwing an Exception. Not all elements are run in the registration flow in such cases, but the user still exists. Neither a REGISTER event is saved for the user.

### Version

latest nightly (but present since at least 19.x)

### Expected behavior

If the user entity is created then the registration flow should execute until the end successfully. Probably the whole flow should run in a single transaction.

### Actual behavior

The user entity is created, but an error page is shown to the user. The registration flow is not executed until the end.

### How to Reproduce?

A realm is required where the following is set:
 - registration enabled
 - forgot password enabled

To reproduce:
 - Open the login page
 - Click on the _register_ link
 - Click on the _back to the login_ link
 - Click on the _forgot password_ link
 - Enter a valid, existing e-mail address to the form. Click on the Submit button
 - Press the back button in the browser until you get back to the registration form (~3 times?)
   - a _page is expired_ error will be shown somewhere. Don't care about it, just press the back button until you get back to the login page
 - Fill out the registration form & submit your registration

An error page is shown, but the user is created in the database. From now on the freshly created user can ask for a reset password link, and log in after that with their newly created password.

### Anything else?

This is a reopen of #17644 as suggested on [Slack here](https://cloud-native.slack.com/archives/C056XU905S6/p1688643055350429?thread_ts=1688559314.400539&cid=C056XU905S6)

There was a PR (#19488) that stated to solve the issue, but it didoes not. It can be reproduced with the latest nightly at the moment.

I have a PR in #19556 which solves the issue, opened months ago.

**Comment by abstractj** [comment]
@keycloak/store could you please triage?

**Comment by vilmosnagy** [comment]
@ahus1 the PR #19556 contains 2 commits:
 - the first one contains only a failing test with the current upstream keycloak
 - the second one is my fix - but I'm not sure about this one.

If that helps I'm happy to have a quick call to demonstrate the bug on a nightly keycloak next week - as far as I see we work in the same timezone :slightly_smiling_face:

**Comment by vilmosnagy** [comment]
@sguilhen  the PR #19556 contains 2 commits:
 - the first one contains only a failing test with the current upstream keycloak
 - the second one is my fix - but I'm not sure about this one.

If that helps I'm happy to have a quick call to demonstrate the bug on a nightly keycloak next week. I work in CEST (Central European Summer Time), but I'm flexible &  happy to help outside my working hours. Feel free to contact me at `vilmos.nagy@realcity.io` :slightly_smiling_face:

**Comment by vilmosnagy** [comment]
Can I help you all anyhow with this issue&PR being merged? :slightly_smiling_face:  @sguilhen @ahus1 ?

**Comment by ralfhecktor** [comment]
@sguilhen @ahus1 This is an important bugfix preventing invalid state of registered users. It would be very much appreciated if this could be merged. Thanks.

**Comment by sguilhen** [comment]
I was able to reproduce the issue locally. @ahus1 we should probably prioritize reviewing the associated PR for this one.

**Comment by ralfhecktor** [comment]
@sguilhen Thank you very much for picking this up.
