### ISSUE TITLE
KC21 : LockAcquiringTimeoutException for HotRodCrudOperations

### ISSUE THREAD

**Issue by avanlangup** [keycloak/keycloak#21538]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

We perform load tests with KC benchmark (500 gatling active users). We extend AuthorizationCode scenario with random number of refresh tokens. After 2 minutes, the refresh token requests started to fail because of the external cache timeout
[Gatling Stats - Global Information.pdf](https://github.com/keycloak/keycloak/files/11997427/Gatling.Stats.-.Global.Information.pdf)

### Version

21.1.1

### Expected behavior

User session is properly updated in external ISPN cache

### Actual behavior
```
org.keycloak.models.locking.LockAcquiringTimeoutException: Lock [org.keycloak.models.UserSessionModel_16df630a-c916-441a-b03a-7c0a18138edf] already acquired by keycloak instance [executor-thread-113#7@btxidp-apps-keycloak-df95d9575-ffwws] at the time [2023-07-10T02:29:21.233Z]
    at org.keycloak.models.map.storage.hotRod.locking.HotRodLocksUtils.repeatPutIfAbsent(HotRodLocksUtils.java:83)
    at org.keycloak.models.map.storage.hotRod.HotRodCrudOperations.read(HotRodCrudOperations.java:131)
    at org.keycloak.models.map.storage.hotRod.HotRodCrudOperations.read(HotRodCrudOperations.java:217)
    at org.keycloak.models.map.storage.chm.ConcurrentHashMapStorage.read(ConcurrentHashMapStorage.java:208)
    at org.keycloak.models.map.storage.hotRod.userSession.HotRodUserSessionMapStorage.read(HotRodUserSessionMapStorage.java:140)
    at org.keycloak.models.map.userSession.MapUserSessionProvider.getUserSession(MapUserSessionProvider.java:189)
    at org.keycloak.protocol.oidc.TokenManager.lambda$validateToken$0(TokenManager.java:151)
    at org.keycloak.utils.LockObjectsForModification.lockObjectsForModification(LockObjectsForModification.java:80)
    at org.keycloak.utils.LockObjectsForModification.lockUserSessionsForModification(LockObjectsForModification.java:66)
    at org.keycloak.protocol.oidc.TokenManager.validateToken(TokenManager.java:151)
    at org.keycloak.protocol.oidc.TokenManager.refreshAccessToken(TokenManager.java:374)
```
### How to Reproduce?

https://www.keycloak.org/keycloak-benchmark/  

We created a realm with 10 000 users

./kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode --server-url=xxx --realm-name=realm-0 --users-per-realm=10000 --concurrent-users=500 --sla-mean-response-time=10000 --ramp-up=60 --measurement=180 --logout-percentage=0

### Anything else?

We run on GCP with AlloyDB and external ISPN cluster (3 pods).  KC is autoscaled based on active DB connections

**Comment by ahus1** [comment]
The hot rod store is currently in tech preview. If you want to provide a pull request to solve your issue, please do so. For now, we assign this to out backlog and can't name a date when we might analyze this further. 

Once we analyze it, it might be helpful to know about the full storage configuration you're using (which entity types you store in Infinispan, which data you store in AlloyDB).

**Comment by avanlangup** [comment]
We use the following configuration: 

        - name: KC_STORAGE_AREA_AUTH_SESSION
          value: hotrod
        - name: KC_STORAGE_AREA_LOGIN_FAILURE
          value: hotrod
        - name: KC_STORAGE_AREA_SINGLE_USE_OBJECT
          value: hotrod
        - name: KC_STORAGE_AREA_USER_SESSION
          value: hotrod

**Comment by mhajas** [comment]
@avanlangup The locking is used to make sure only one thread/node is touching one user session.

There may be two reasons for the exception you are seeing:
1. A lock was not cleaned by some thread that failed and it is now blocking all other threads. To identify that option you can compare time within the exception message `at the time [2023-07-10T02:29:21.233Z]` with the time the exception was thrown. If the time difference is too big, it probably means the lock is not cleaned correctly and the thread that was supposed to clean it was killed/failed. Also, if you see more exceptions for one lock, try to compare the instance name and time, if it doesn't change, it probably means some locks are hanging. 
2. There are too many threads trying to change the same user session therefore the waiting time is too big and threads give up waiting for the lock to be released. This timeout defaults to 5 seconds and can be increased within this [factory](https://github.com/keycloak/keycloak/blob/d015fa392ce1ead2a17c3aa8da0d607b2304da36/model/map-hot-rod/src/main/java/org/keycloak/models/map/storage/hotRod/locking/HotRodGlobalLockProviderFactory.java#L55). Unfortunately, we don't have Quarkus option, but it should be possible to change it via environment variable. You can try adding the following:
```
              - name: KC_SPI_GLOBAL_LOCK_HOTROD_DEFAULT_TIMEOUT_MILLISECONDS
                value: "10000"
```
This ^^ sets the value to 10 seconds.


Anyway, I really like to see you are experimenting with HotRod store :+1: I have a few questions:
1. Does it fail after 2 minutes all the time? Or it is happening randomly?
2. What are you using for storing the other areas (mainly users and realms)? Do you use the new map storage? Or legacy store?
3. How many Keycloak pods were approximately active with this load?

**Comment by avanlangup** [comment]
1. I would say randomly. I cannot reproduce anymore when I run with fixed number of pods (8 KC and 3 ISPN). 
2. We use map storage
3.It was failing when we ran with 2 initial pods and auto-scaling based on active connections.
![image](https://github.com/keycloak/keycloak/assets/131152984/a7ec69bf-d0de-46e5-8455-dafb6c381cff)

**Comment by avanlangup** [comment]
We use the benchmark tool : https://www.keycloak.org/keycloak-benchmark/    
We dont have much exception with fixed number of replicas but average response time is still around 5-6 seconds.
We run with OTEL agent but the Jaeger trace is incomplete. We see only spans related to map storage.
So we dont know the cause of response latency. Any suggestion to investigate ?

**Comment by mhajas** [comment]
Traces would be really useful. It is hard to say what is causing the slowness. If responses are longer than 5 seconds this can explain the failures from HotRod because the lock is acquired for the whole response time which can cause the timeouts. In that case, increasing the timeout should avoid this exception. 

One option for the slowness may be that map storage does not use caching for JPA areas, maybe the JDBC connection pool or database connection pool is exhausted.

If you have Grafana dashboards installed from `keycloak-benchmark` project can you check `keycloak-perf-tests` and `Keycloak - JDBC Connection Pool Stats`? This should give us some details about the utilization of JDBC connections within Keycloak.

**Comment by mhajas** [comment]
Also, @avanlangup out of curiosity, can you share how you configure `storage-hotrod-*` Keycloak options? Feel free to remove any URLs specific to your deployment, I am just curious.

**Comment by avanlangup** [comment]
At the beginning we had acquisition timeout but there is no awaiting connection anymore (pool size 400 per pod)
![image](https://github.com/keycloak/keycloak/assets/131152984/a8a86669-defe-4060-b98b-e21d6626d24a)

**Comment by avanlangup** [comment]
> Also, @avanlangup out of curiosity, can you share how you configure `storage-hotrod-*` Keycloak options? Feel free to remove any URLs specific to your deployment, I am just curious.

          - name: KC_STORAGE
            value: jpa
          - name: KC_STORAGE_AREA_AUTH_SESSION
            value: hotrod
          - name: KC_STORAGE_AREA_LOGIN_FAILURE
            value: hotrod
          - name: KC_STORAGE_AREA_SINGLE_USE_OBJECT
            value: hotrod
          - name: KC_STORAGE_AREA_USER_SESSION
            value: hotrod
          - name: KC_CACHE
            value: ispn
          - name: KC_CACHE_STACK
            value: kubernetes
          - name: KC_STORAGE_HOTROD_HOST
            value: btxidp-apps-infinispan.ns.svc.cluster.local
          - name: KC_STORAGE_HOTROD_PORT
            value: "11222"
          - name: KC_STORAGE_HOTROD_USERNAME
            value: infinispan
          - name: KC_STORAGE_HOTROD_PASSWORD
            key: kc_storage_hotrod_password
          - name: KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED
            key: kc_storage_deployment_state_version_seed

**Comment by mhajas** [comment]
> At the beginning we had acquisition timeout but there is no awaiting connection anymore (pool size 400 per pod) ![image](https://user-images.githubusercontent.com/131152984/253900615-a8a86669-defe-4060-b98b-e21d6626d24a.png)

Thank you for sharing this. Can you change the graph to display data only from one pod (ideally the one that acquired the lock, from the exception above `btxidp-apps-keycloak-df95d9575-ffwws`). If you don't have data from that run, just pick one random pod. It should be possible to click the lines in the legend and then `ctrl + click` to add more lines to the resulting graph. We are interested in `awaiting connection` number.

**Comment by mhajas** [comment]
> > Also, @avanlangup out of curiosity, can you share how you configure `storage-hotrod-*` Keycloak options? Feel free to remove any URLs specific to your deployment, I am just curious.
> 
> ```
>       - name: KC_STORAGE
>         value: jpa
>       - name: KC_STORAGE_AREA_AUTH_SESSION
>         value: hotrod
>       - name: KC_STORAGE_AREA_LOGIN_FAILURE
>         value: hotrod
>       - name: KC_STORAGE_AREA_SINGLE_USE_OBJECT
>         value: hotrod
>       - name: KC_STORAGE_AREA_USER_SESSION
>         value: hotrod
>       - name: KC_CACHE
>         value: ispn
>       - name: KC_CACHE_STACK
>         value: kubernetes
>       - name: KC_STORAGE_HOTROD_HOST
>         value: btxidp-apps-infinispan.ns.svc.cluster.local
>       - name: KC_STORAGE_HOTROD_PORT
>         value: "11222"
>       - name: KC_STORAGE_HOTROD_USERNAME
>         value: infinispan
>       - name: KC_STORAGE_HOTROD_PASSWORD
>         key: kc_storage_hotrod_password
>       - name: KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED
>         key: kc_storage_deployment_state_version_seed
> ```

Have you experienced some errors with XA transactions with this setting? When I configured it in a similar way, I have seen an error where it seemed the HotRod client is trying to talk to different ISPN nodes within one transaction (which resulted in an error because not all nodes know about the transaction started in one node)

**Comment by avanlangup** [comment]
> > At the beginning we had acquisition timeout but there is no awaiting connection anymore (pool size 400 per pod) ![image](https://user-images.githubusercontent.com/131152984/253900615-a8a86669-defe-4060-b98b-e21d6626d24a.png)
> 
> Thank you for sharing this. Can you change the graph to display data only from one pod (ideally the one that acquired the lock, from the exception above `btxidp-apps-keycloak-df95d9575-ffwws`). If you don't have data from that run, just pick one random pod. It should be possible to click the lines in the legend and then `ctrl + click` to add more lines to the resulting graph. We are interested in `awaiting connection` number.

number of awaiting connections is always zero since we start with same values for init/min/max pool size. I will try to check once we try to autoscale pods  later

**Comment by avanlangup** [comment]
> > > Also, @avanlangup out of curiosity, can you share how you configure `storage-hotrod-*` Keycloak options? Feel free to remove any URLs specific to your deployment, I am just curious.
> > 
> > 
> > ```
> >       - name: KC_STORAGE
> >         value: jpa
> >       - name: KC_STORAGE_AREA_AUTH_SESSION
> >         value: hotrod
> >       - name: KC_STORAGE_AREA_LOGIN_FAILURE
> >         value: hotrod
> >       - name: KC_STORAGE_AREA_SINGLE_USE_OBJECT
> >         value: hotrod
> >       - name: KC_STORAGE_AREA_USER_SESSION
> >         value: hotrod
> >       - name: KC_CACHE
> >         value: ispn
> >       - name: KC_CACHE_STACK
> >         value: kubernetes
> >       - name: KC_STORAGE_HOTROD_HOST
> >         value: btxidp-apps-infinispan.ns.svc.cluster.local
> >       - name: KC_STORAGE_HOTROD_PORT
> >         value: "11222"
> >       - name: KC_STORAGE_HOTROD_USERNAME
> >         value: infinispan
> >       - name: KC_STORAGE_HOTROD_PASSWORD
> >         key: kc_storage_hotrod_password
> >       - name: KC_STORAGE_DEPLOYMENT_STATE_VERSION_SEED
> >         key: kc_storage_deployment_state_version_seed
> > ```
> 
> Have you experienced some errors with XA transactions with this setting? When I configured it in a similar way, I have seen an error where it seemed the HotRod client is trying to talk to different ISPN nodes within one transaction (which resulted in an error because not all nodes know about the transaction started in one node)

Sometimes we see errors related to XA transactions like HeuristicMixedException but cannot identify the root cause

**Comment by avanlangup** [comment]
[2023-07-18 02:19:58.438 +0000] [/] WARN   [c.a.a.jta:1018] (Periodic Recovery) ARJUNA016037: Could not find new XAResource to use for recovering non-serializable XAResource XAResourceRecord < resource:null, txid:< formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff64400599:ad85:64b5172b:1f7c, node_name=quarkus, branch_uid=0:ffff64400599:ad85:64b5172b:1f82, subordinatenodename=null, eis_name=0 >, heuristic: TwoPhaseOutcome.HEURISTIC_ROLLBACK com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord@415a8d2f >
