### ISSUE TITLE
Login page doesn't show the supported locales which are configured in login theme but the supported locales set in realm setting

### ISSUE THREAD

**Issue by irishuenm** [keycloak/keycloak#21541]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

The bug happened with kc 21.1.2, the supported locales in theme.properties of login theme are not shown properly

### Version

21.1.2

### Expected behavior

The login page should show the supported locales in the theme.properites of login themes.

### Actual behavior

The login page should show the supported locales which are set in realm setting/localization

### How to Reproduce?

- Download and run keycloak 21.1.2 locally
- In realm setting, enable the internationalization, set the supported locales: English, Deutsch, Espanol
- Create a login theme in the themes folder 
![image](https://github.com/keycloak/keycloak/assets/139108329/a73dddb6-5fe1-47ca-a0ea-415d3e9ec153)
In theme.properties, I set the different supported locales : (only German and English)
parent=keycloak
import=common/keycloak
locales=de,en
Created file message_de.properties in messages folder in the "iristheme" folder.
- Select the created theme in the realm setting theme
![image](https://github.com/keycloak/keycloak/assets/139108329/b65bb675-34c0-4743-a034-d4680ee13347)

- restart keycloak
- start the application which use the keycloak for authentication, in the redirected keycloak login page, the supported languages are still "English, Deutsch, Espanol" not "English, German"

![image](https://github.com/keycloak/keycloak/assets/139108329/83fb26cb-d839-4a89-9400-a7c7fa1fb465)
- I got the same issue if I set the created theme as the login theme of a client

**Comment by douglaspalmer** [comment]
@irishuenm Do you know which version this last worked for in?

**Comment by irishuenm** [comment]
> @irishuenm Do you know which version this last worked in?

No, I don't know.

**Comment by stianst** [comment]
Displayed locales are based on what is configured for the realm, and not the theme, so this is expected behaviour.
