### ISSUE TITLE
Context path missing in URL on OTP page to switch between QR code and manual code

### ISSUE THREAD

**Issue by sebastianhoe** [keycloak/keycloak#21542]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

When Keycloak is publicly exposed on a different path, the link generated for the OTP setup page to switch between QR code and manual code entry does not reflect the public path. Debugging showed that the contextPath provided by the hostname provider is not considered when building the URLs.

Setup:
There is a reverse proxy that is redirecting every request on http://hostname:port/foo/auth on a docker that exposes keycloak on http://ip:port/auth, so public path deviates from http-relative-path of Keycloak, all other functionality works.

### Version

21.1.1

### Expected behavior

The contextPath of hostname provider is respected when generating the URL to switch between QR code and manual code entry for OTP setup.

### Actual behavior

The contextPath of the hostname provider is ignored.

### How to Reproduce?

1 - Use a reverse proxy like apache or nginx
2 - Make your Keycloak run on ip:port/auth (using http-relative-path and set env var KC_HOSTNAME_URL and KC_HOSTNAME_ADMIN_URL to ip:port/foo/auth
3 - Reverse proxy the URL ip:port/foo/auth to your Keycloak that is running ip:port/auth
4 - Go to the OTP configuration page
5 - Try to switch to manual, the url is pointing on /auth and not to /foo/auth

### Anything else?

This is related to https://github.com/keycloak/keycloak/issues/11774 which focues on the ip/hostname and port, but was not using a different path.

**Comment by ssilvert** [comment]
Since this is actually inside an AIA, it doesn't fall under UI.  Changing to core team.
