### ISSUE TITLE
Provide raw OpenAPI specification alongside Keycloak Admin REST API html documentation

### ISSUE THREAD

**Issue by DAHAG-ArisNourbakhsh** [keycloak/keycloak#21559]
### Description

It would be nice for the Admin REST API html documentation to link to the raw OpenAPI specification that it was generated from so the community can have a reliable OpenApi specification source.

### Motivation

With the merge of #20669 it should be trivial to also provide access to the raw specification for the purpose of generating clients in different programming languages. 

Currently there are only third party community projects that attempt to create a spec through best effort parsing of either the html documentation or the source code. They are not 100% reliable, lag behind keycloak releases and are a waste of effort if the HTML documentation generation step just needs an additional write to disk of the raw json/yml spec
https://github.com/ccouzens/keycloak-openapi
https://github.com/dahag-ag/keycloak-openapi

**Comment by SimonScholz** [comment]
Then I am wondering if @ccouzens or @dahag-ag could provide a PR for this purpose?
