### ISSUE TITLE
Make sure admin events are not referencing sensitive data from their representation

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#21562]
### Description

It is a follow-up on https://github.com/keycloak/keycloak/issues/17470.

In addition to removing credentials from user representations when persisting admin events, we should also make sure other representation types are not exposing any sensitive data.

The representation types we should start looking at are:

* `RealmRepresentation`
* `UserRepresentation`
* `ClientRepresentation`
* `IdentityProviderRepresentation`
* `ComponentRepresentation`

Ideally, we should enhance how we are using `StripSecretsUtils` to encapsulate how sensitive data are removed from representations for the different representation types. Therefore, helping to administer how sensitive data, such as secrets, are returned from Admin API and set to event representations.

### Discussion

https://github.com/keycloak/keycloak/issues/17470

### Motivation

Avoid exposing sensitive data when returning representations from Admin API or when creating/persisting events.

**Comment by stianst** [comment]
I kinda like the approach in:
https://github.com/keycloak/keycloak/pull/21561/files#diff-1b0f8871254a6c817c81a0aa7ba763e06f170dc78f4ce107011a2bfb0519842eR256

Perhaps we can add a `StripSecretsUtils#strip(Object value)` method that figures out what type of representation it is and strips relevant secrets, then call this in `AdminEventBuilder.representation` for all representations, and remove the boiler-plate. One thing I'm wondering is do we need to clone the representations in case `AdminEventBuilder.representation` is invoked prior to using the representation?

**Comment by pedroigor** [comment]
I've sent https://github.com/keycloak/keycloak/pull/21563.

Ideally, we should clone it but I'm not sure how to properly do it without complicating things and more boilerplate code.

**Comment by ioemat** [comment]
Hi @pedroigor, what is the status of this?

We'd like to get rid of the issue and I could support here if you like.

One solution approach I'm thinking of is to implemented decorators for the affected representations. (Yes, sounds like some effort, but this way we could ensure that the passed objects are not changed while we can control what is exported.)

So e.g. change the code in `AdminEventBuilder` to sth. like

```
    public AdminEventBuilder representation(Object value) {
    
         ...
        Object decoratedValue = value;
        
        // similar for all the other representations that are affected
        if (value instanceof UserRepresentation) {
            decoratedValue = new hideSecretsUserRepresentationDecorator(((UserRepresentation) value);
        }

        try {
            adminEvent.setRepresentation(JsonSerialization.writeValueAsString(decoratedValue));
        } catch (IOException e) {
        ...
    }
```

I'm also open the implement other ideas of course.

**Comment by pedroigor** [comment]
@ioemat Hey. I just closed my PR because of the lack of feedback and priority. If you want to resume discussions, let's go for it.

Regarding your proposal, one thing to consider is that it is not only related to events (as I figured out in that PR) but also some JAX-RS resources returning representations (e.g.: `IdentityProviderResource`).

Looks like your decorator is doing this https://github.com/keycloak/keycloak/pull/21563/files#diff-a7ec31bc0a1a91dc2f2b9a9379c2ce9f4de440274cb2558043b888e7639ce981R49. And the idea behind that is to have a single source of truth for stripping out secrets from representation regardless of their type. As well as in a way we can perform the operator whenever a representation is being exposed (e.g.: JAX-RS responses).

So yeah, ideally we should have a code that:

* Makes it easier to add new representations that need stripping out secrets
* Makes it easier to track how secrets are stripped from representations
* Strip secrets from a single place, regardless of the representation

My changes do not comply with #2 but it does with #1 and #2 above, I think.

If you have a better solution, please send a PR and we can look at it together.

**Comment by ioemat** [comment]
I rebased you branch into main and currently trying out different ideas. 
I think I will come up with some ideas later this week.

**Comment by ioemat** [comment]
Sorry, it took a bit longer than I expected.

Actually I tried different things and came to the conclusion, that your approach @pedroigor, seems to be the best.

So I just rebased your PR to main and refactored it mainly in order to be able to add unit tests. Looking forward to your opinion on that.
