### ISSUE TITLE
KC21.1.1 : Unable to acquire JDBC Connection (timeout)

### ISSUE THREAD

**Issue by avanlangup** [keycloak/keycloak#21580]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

We run 8 pods for performance tests on our GCP cluster with AlloyDB (max 4000 db connections)

Settings as suggested : https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/customizing-deployment#KC_DB_POOL_INITIAL_SIZE

- KC_DB_POOL_INITIAL_SIZE 200
- KC_DB_POOL_MAX_SIZE 200
- KC_DB_POOL_MIN_SIZE 200

But we still got the timeout pretty fast when running Authorization scenario with 1000 active Gatling users

### Version

21.1.1

### Expected behavior

Connection is returned from the initial pool

### Actual behavior

```
Caused by: java.sql.SQLException: Sorry, acquisition timeout!
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:294)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:249)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at io.quarkus.hibernate.orm.runtime.customized.QuarkusConnectionProvider.getConnection(QuarkusConnectionProvider.java:23)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
```
### How to Reproduce?

Login with 1000 concurrent users (eg. using benchmark tool)

https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/scenario-overview

### Anything else?

We see awaiting connections in AGROAL stats

![image](https://github.com/keycloak/keycloak/assets/131152984/6980d553-fe0e-416e-bdc6-9bc2708d1651)

https://issues.redhat.com/browse/AG-201   this is fixed in version 1.17 used by KC21

https://github.com/agroal/agroal/blob/4c4da6419652f772542e648581d0d8939c411b5e/agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java

**Comment by avanlangup** [comment]
I cant reproduce with legacy storage

**Comment by ahus1** [comment]
I assume that you're using JPA map storage. With JPA map storage, there is currently no caching. Due to that, all requests touch the database. When all DB connections are busy, and requests queue up, the error you see is expected. 

Either reduce the load, or allow more concurrent database connections per Keycloak Pod. 

There is currently no work planned to add caching to the map store. We might add it later when work around the map store progresses, and we run more load tests on our own on this. At the moment, we might not even have the time to review community contributions for adding caching except if they are very simple/small.

**Comment by vksaamy** [comment]
Added QUARKUS_DATASOURCE_JDBC_ACQUISTION_TIMEOUT as 10s as an environment variable in my Kubernetes deployment though I have been trying various fixes for long time. In my case it was Keycloak version 25.0.6 and using Quarkus framework.

The earlier versions were using Jboss and this fix will not be applicable if the issue exists in older versions.
