### ISSUE TITLE
OPTIONS requests causing java.lang.ClassCastException on 21.1.2

### ISSUE THREAD

**Issue by Stono** [keycloak/keycloak#21586]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Hello, 
We've recently upgraded from `21.0.2` to `21.1.2` and noticed an increase in `500` errors in our logs.
Digging into it, we see this exception:

```
{"timestamp":"2023-07-11T09:56:53.528Z","sequence":8573,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.services.error.KeycloakErrorHandler","level":"ERROR","message":"Uncaught server error","threadName":"executor-thread-5","threadId":151,"mdc":{},"ndc":"","hostName":"keycloak-1","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"java.lang.ClassCastException","message":"class org.jboss.resteasy.core.registry.ConstantResourceInvoker cannot be cast to class org.jboss.resteasy.core.ResourceMethodInvoker (org.jboss.resteasy.core.registry.ConstantResourceInvoker and org.jboss.resteasy.core.ResourceMethodInvoker are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @22fcf7ab)","frames":[{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invokeOnTargetObject","line":191},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":152},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invokeOnTargetObject","line":183},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":141},{"class":"org.jboss.resteasy.core.ResourceLocatorInvoker","method":"invoke","line":32},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":492},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$invoke$4","line":261},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"lambda$preprocess$0","line":161},{"class":"org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext","method":"filter","line":364},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"preprocess","line":164},{"class":"org.jboss.resteasy.core.SynchronousDispatcher","method":"invoke","line":247},{"class":"io.quarkus.resteasy.runtime.standalone.RequestDispatcher","method":"service","line":73},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"dispatch","line":151},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":82},{"class":"io.quarkus.resteasy.runtime.standalone.VertxRequestHandler","method":"handle","line":42},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":84},{"class":"io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2","method":"handle","line":71},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":430},{"class":"io.quarkus.vertx.http.runtime.VertxHttpRecorder$6","method":"handle","line":408},{"class":"io.vertx.ext.web.impl.RouteState","method":"handleContext","line":1284},{"class":"io.vertx.ext.web.impl.RoutingContextImplBase","method":"iterateNext","line":173},{"class":"io.vertx.ext.web.impl.RoutingContextImpl","method":"next","line":140},{"class":"org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter","method":"lambda$createBlockingHandler$0","line":82},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":576}]}}
```

These correlate with `OPTIONS` requests to the following: `https://our-domain/realms/realm/protocol/openid-connect/auth?client_id=client-id&scope=openid%20profile-minimal%20employee&response_type=code&redirect_uri=...&kc_idp_hint=azure&response_mode=form_post&code_challenge=...&code_challenge_method=S256&nonce=...&state=...`

Digging back into our request logs, these `OPTIONS` requests are not new, but on `20.0.2` they returned a `200`.

### Version

20.1.2

### Expected behavior

The request to not throw an internal server error, either OPTIONS requests are allowed to that URL (like in 20.0.2) or they should be rejected with a 405 or similar?

### Actual behavior

As above

### How to Reproduce?

I'm still digging into the specifics of the applications that send options requests, if i get more information that aids reproducibility i'll let you know.   But right now sending the request with curl -XOPTIONS should reproduce it.

### Anything else?

Unfortunately I cannot try the latest nightly release as I'm unable to recreate this issue in our testing environment, likely due to the cardinality of requests/browsers/users we have in production.

**Comment by Stono** [comment]
Ahh that's good.  By 22 I presume you mean nightly?  I can't push that build to our effected environments unfortunately.

Is there an ETA release date?

**Comment by abstractj** [comment]
@Stono Keycloak 22 was already release, please refer to https://www.keycloak.org/downloads

**Comment by Stono** [comment]
@abstractj please to say i rolled out 22 this morning and the errors have gone away, so this is certainly a 21.1.2.  Assume it'll fall into the "wont fix" seeing as its an old release, and we should close the issue off?

**Comment by Stono** [comment]
I agree! Thanks for helping

**Comment by acp9191** [comment]
Wanted to note that I ran into this issue as well after upgrading to `21.1.2`, and I'm not able to upgrade to 22 yet because of the removed support for Java 11. If possible, I think it would be worthwhile to create patch version under 21 fixing this issue.
