### ISSUE TITLE
Use "create option" on the annotations and evaluate tab

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#21594]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/api

### Describe the bug

atm two solutions are used to have dropdown that have also custom values, we should move this to use `onCreate` of the typeahead

### Version

main

### Expected behavior

consistent working ui

### Actual behavior

not

### How to Reproduce?

see the ui

**Comment by mposolda** [comment]
@edewit Not 100% sure, but I guess the correct component should be `area/admin/ui` or `area/account/ui`. So updated the component to reflect this.

**Comment by edewit** [comment]
yes, sorry thanks
