### ISSUE TITLE
Having issue with user query seach when value having space

### ISSUE THREAD

**Issue by nmanthena18** [keycloak/keycloak#21598]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

I am trying to get the users from which are imported from LDAP & I have custom attributes for to filter the data with query search from users API.

`http://localhost:8080/admin/realms/relame/users?q=emailid:<email> position:<Deputy Manager>`

### Version

21.1.2

### Expected behavior

I was expecting the user who has  match with emailid:<email> & position:<Deputy Manager>`

### Actual behavior

when the position attributes value having space, response given as empty result. I tried with <Deputy+Manager> & <Deputy%20Manager> no luck.

### How to Reproduce?

`http://localhost:8080/admin/realms/relame/users?q=emailid:username@email.com position:Deputy Manager`

ex: searching for below user: 
`[
    {
        "username": "username",
        "firstName": "firstName",
        "lastName": "lastName",
        "email": "username@email.com",
        "attributes": {
            "emailid": [
                "username@email.com"
            ],
            "title": [
                "Deputy Manager"
            ],
            "position": [
                "Deputy Manager"
            ],
        },
    }
]`

**Comment by rmartinc** [comment]
Hi @nmanthena18!

You can use quotes in the name or value. Try something like `q=emailid:username@email.com position:"Deputy Manager"` (correctly url encoded `q=emailid%3Ausername%40email.com%20position%3A%22Deputy%20Manager%22`). If the value has a quote you need to escape it `q=position:"Deputy\"Manager"` (url encoded again).

Check if using quotes works for for you.

**Comment by rmartinc** [comment]
The `q` parameter just uses equals comparison and all attributes are joined via `and`.

**Comment by nmanthena18** [comment]
@rmartinc  thanks!
