### ISSUE TITLE
Can't sign out a user from the admin console "Sessions" section

### ISSUE THREAD

**Issue by maxime-bc** [keycloak/keycloak#21599]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

When I visit my app, I can log-in and see in the "Sessions" section in the Keycloak admin console that my user is logged in : 

![Capture d’écran 2023-07-10 153443](https://github.com/keycloak/keycloak/assets/49453941/8c9b5a46-d5fc-4a44-83b7-41a3a2b11aa5)

My issue is that when I click on the three dots at the end of the line displaying session info, then on "Sign out", the table is emptied but the Keycloak server print the following warning : ``WARN  [org.keycloak.services.managers.AuthenticationManager] (executor-thread-0) Some clients have been not been logged out for user johndoe in dummy realm: dummyclient``. I can confirm that the user was not logged out as I can still navigate to the "Profile" page on the sample app. The same thing happens when I click on the user name and then click on the button "Logout all  sessions". 

If I try to log out of the app after this, the Keycloak server will print a new warning : ``[org.keycloak.events] (executor-thread-9) type=LOGOUT_ERROR, realmId=[...], clientId=null, userId=null, ipAddress=[...], error=session_expired, authSessionParentId=[...], authSessionTabId=[...]``, but according to the previous warning, the user was not logged out so the session should not be expired.

### Version

21.1.2 and nightly

### Expected behavior

Clicking on "Sign out" and "Logout all  sessions" buttons should end the session of the user on the app.

### Actual behavior

Clicking on "Sign out" and "Logout all  sessions" buttons does not end the session of the user on the app and the Keycloak server prints warnings.

### How to Reproduce?

**Keycloak**

In Keycloak, I have set up a realm named `dummy`, and inside this realm, I have created a client named `dummyclient` and a user named ``johndoe`` with a password. I kept the client configuration bare minimum and only followed the "Create client" form with the only exception of setting the "Client authentication" switch to "On" and then set all the app URLs.

**App**

I used the  ``01-Login`` Node.js sample from the [auth0-express-webapp-sample](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) repository (which uses the [express-openid-connect](https://github.com/auth0/express-openid-connect) library).

In `server.js`, i just updated the [config object](https://github.com/auth0-samples/auth0-express-webapp-sample/blob/master/01-Login/server.js#L20) so that the sample works with Keycloak, as follows : 
```javascript
const config = {
  authRequired: false,
  idpLogout: true,
  authorizationParams: {
    response_type: "code",
  },
  clientSecret: "abcde...",
};
```

My ``.env`` file:
```
CLIENT_ID=dummy
ISSUER_BASE_URL=http://localhost:8080/realms/dummy/
SECRET=123456789
PORT=5000
```

### Anything else?

Discussion about this issue: https://github.com/keycloak/keycloak/discussions/19585

**Comment by pedroigor** [comment]
@maxime-bc The first message is related to Keycloak trying to perform a backchannel logout. See https://openid.net/specs/openid-connect-backchannel-1_0.html and https://www.keycloak.org/docs/latest/server_admin/#_oidc-logout.

When expiring sessions like that, Keycloak you try to send a logout token to your application to indicate that local sessions should be destroyed. The session is no longer valid on the server-side.

**Comment by maxime-bc** [comment]
Ok, I've got it working, thanks for the help @pedroigor.

**Keycloak**

For people having the same issue as me, I updated my Keycloak server "Logout settings" to enable backchannel logout as follows:

![Capture d’écran 2023-07-17 103822](https://github.com/keycloak/keycloak/assets/49453941/33c8ba63-02bd-494f-976d-4ab32c14cc63)

**Node.js server**

Backchannel logout is currently an ``express-openid-connect`` beta feature (see https://github.com/auth0/express-openid-connect/issues/383#issuecomment-1330339698).

To setup backchannel logout on the [auth0-express-webapp-sample](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login), I followed the [setup guide](https://github.com/auth0/express-openid-connect/blob/back-channel-logout/BACK_CHANNEL_LOGOUT.md):

- Step 1: uninstall the ``express-openid-connect`` package and install the beta branch:
```
npm uninstall express-openid-connect
npm install "auth0/express-openid-connect#back-channel-logout"
```

- Step 2: install a store

To be less verbose, I'm using ``memorystore`` as a store instead of ``redis`` in the guide.
```
npm install memorystore
npm install express-session
```

- Step 3: add backchannel logout to the config;

```javascript
// Add new imports
const session = require('express-session');
const MemoryStore = require('memorystore')(session);

// ...

// Create a store instance
const store = new MemoryStore({
  checkPeriod: 86400000,
});

// Update the config object
const config = {
  authRequired: false,
  idpLogout: true,
  authorizationParams: {
    response_type: "code",
  },
  clientSecret: "abcde...",
  backchannelLogout: true, // add this
  backchannelLogoutStore: store // and this
};

// ...
```

Done, now sessions can be terminated from the administration console.
