### ISSUE TITLE
Since upgrade to 22.0.0 user will be created differently than before

### ISSUE THREAD

**Issue by Paul6552** [keycloak/keycloak#21609]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

Before 22.0.0 users were created with attribute 
![image](https://github.com/keycloak/keycloak/assets/25934591/7dd292fd-d195-4407-8abb-b07edb76f3a8)

After Upgrade to 22.0.0 users dont have the default attribute locale anymore.
![image](https://github.com/keycloak/keycloak/assets/25934591/0e746ce7-3758-4eea-ab22-480e75df074d)

This information is nowhere in the migration guide:
[Migration / Release notes](https://www.keycloak.org/2023/07/keycloak-2200-released.html)

Not sure if it is a bug but it should be noted because reading `attributes` from users and pretending to have a `locale` is now dangerous.

This is the java code I used since version 16.1.1:
```
        UserRepresentation newUserRepresentation = keycloakUserMapper.mapUser( user, email, password );
        keycloak.realm( "myRealm" ).users().create( newUserRepresentation );
```

mapUser-Function:
```
public UserRepresentation mapUser( User user, String email, String password ) {
        UserRepresentation newKeycloakUser = new UserRepresentation();
        newKeycloakUser.setEmailVerified( Boolean.FALSE );
        newKeycloakUser.setEnabled( true );
        newKeycloakUser.setFirstName( user.getVorname() );
        newKeycloakUser.setLastName( user.getNachname() );
        newKeycloakUser.setEmail( normalizeEmail( email ) );
        newKeycloakUser.setUsername( String.format( String.format( "%09d", user.getId() ) ) );
        newKeycloakUser.singleAttribute( "locale", "en" );

        if ( password != null ) {
            CredentialRepresentation passwordCredential = new CredentialRepresentation();
            passwordCredential.setTemporary( false );
            passwordCredential.setType( CredentialRepresentation.PASSWORD );
            passwordCredential.setValue( password );
            newKeycloakUser.setCredentials( Collections.singletonList( passwordCredential ) );
        }
        return newKeycloakUser;
    }
```

PS: Sry, I havent checked it with the latest nightly release althoug I checked it x)

### Version

22.0.0

### Expected behavior

Should create the user like before with attribute

### Actual behavior

Does not create user with attribute

### How to Reproduce?

Upgrade to version 22.0.0

**Comment by pedroigor** [comment]
@Paul6552 Would you mind enabling localization to your realm if you have done already?

**Comment by Paul6552** [comment]
@pedroigor 

Localization is disabled.
When I enable it, the user will be created with localization.

I checked with the current production build 21.1.1 -> there localization is also disabled, but user will created with localization.

So I would assume it's not a bug in 22.0.0 but was actually incorrect behavior prior to 22?

I would only include this information with the migration guide as it would have caused inconveniences, at least for us in the production environment.

Thank you.

**Comment by pedroigor** [comment]
@Paul6552 TBH, we do not have coverage for locale attributes being used when internationalization is not enabled to a realm.

If this is a common use case, we can certainly relax. But I would like to understand better why the `locale` attribute is using when internationalization is not enabled.

**Comment by Paul6552** [comment]
@pedroigor 

We have ancient systems that assume there is at least one attribute. The attributes are fetched from each user (some have more than just localization).

The problem now was that users could have no attributes and after we received users in our legacy systems we did not check if `attributes` could be `NULL`.

**Comment by pedroigor** [comment]
I see. Depending on how many integrations you have, upgrading will involve additional changes to your ecosystem ...

So there isn't a specific reason to not enable internationalization if I understand correctly. And the attribute is not used for anything specific but make sure the attribute list is never empty.

Does it sounds right?

**Comment by Paul6552** [comment]
Yes, exactly

**Comment by pedroigor** [comment]
Do we really want to allow managing locale even though localization is not enabled to a realm?

**Comment by Paul6552** [comment]
> 

I would normaly say "no". 
I think it would only have been necessary to inform the Migration Guide that the behavior would change here.

**Comment by pedroigor** [comment]
@Paul6552 Thanks. I'm sending a PR to update the migration guide.
