### ISSUE TITLE
`keycloakCRName` and `realm` are no longer marked as required in KeycloakRealmImport CRD

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#21607]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

`keycloakCRName` and `realm` fields are no longer marked as required.

### Version

22.0.0

### Expected behavior

[Marked as required](https://github.com/keycloak/keycloak-k8s-resources/blob/21.1.2/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml#L2226-L2228)

### Actual behavior

[Not marked as required](https://github.com/keycloak/keycloak-k8s-resources/blob/22.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml)

### How to Reproduce?

Diff the CRD for 21.1.2 and 22.0.0.

**Comment by vmuzikar** [comment]
CC @shawkins

**Comment by vmuzikar** [comment]
Mitigated this at least for OLM by manually fixing the CRD:
https://github.com/k8s-operatorhub/community-operators/pull/2978
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2933

**Comment by shawkins** [comment]
@vmuzikar this is coming from https://github.com/fabric8io/kubernetes-client/pull/4597 via https://github.com/fabric8io/kubernetes-client/pull/4348

**Comment by vmuzikar** [comment]
Reopening for backport
