### ISSUE TITLE
Permission Evaluation Issue on custom attribute evaluation on RPT token generation

### ISSUE THREAD

**Issue by sridhar1495** [keycloak/keycloak#21624]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

> This is already created bug https://github.com/keycloak/keycloak/issues/20436, But it is not fixed and story is marked as Close. Since I can't reopen it I am creating the bug again as new.

I am trying to create regex-based policy in client authorization with the attribute that is created in the group. And mapped the policy to the scope-based-permission and evaluated in the Keycloak itself and it is working fine and getting the scope properly. But when I get the RPT token in the authorization's permissions that scope is not found. When we checked in the current version(21.1.1) also the same issue is present.

On analyzed the issue we found that it is because the claim structure we are trying to evaluate is having the structure 'claimname.value'. If I configure to get the value to be present is 'claimname' itself and configured the policy to evaluate it is working as expected. So, we assume that the Evaluation engine is not given support for that kind structure during the RPT generation.

### Version

21.1.2

### Expected behavior

The Evaluation must behave properly as per the Regex configured in the policy based on the claim structure.

### Actual behavior

If the claim structure is represented as Object1.Object2=value is failing for the regex written for the structure Object1.Object2 even with the exact match.

### How to Reproduce?

The behavior is as follows:

Created Attribute in the group called 'ADMIN' as follows
![image](https://github.com/keycloak/keycloak/assets/75622411/6ea05004-28f6-4437-ae66-e590f55a7115)

Added 'admin; user to the above group
![image](https://github.com/keycloak/keycloak/assets/75622411/6ebeb21f-7d2f-476d-829a-521fd9749d62)

Created 'Client Scopes' and mapper to get the group attribute in the JWT token at realm level and marked as default
![image](https://github.com/keycloak/keycloak/assets/75622411/f3fc6a25-9a3c-4f3e-b60d-3fbdbfeb3e51)
![image](https://github.com/keycloak/keycloak/assets/75622411/009def6e-5627-4f37-be00-47c9b10e389f)
![image](https://github.com/keycloak/keycloak/assets/75622411/1fcfab7c-00a7-4385-a133-6cb6cf50b18e)

Created Regex-policy inside the client and checked for the exact value
![image](https://github.com/keycloak/keycloak/assets/75622411/20ea2848-847f-4bf3-9ae7-561342ad2a9e)
![image](https://github.com/keycloak/keycloak/assets/75622411/6e4604f7-a776-4731-82c2-49377fb69271)

Mapper this in the scope-based permission to get the 'read' scope
![image](https://github.com/keycloak/keycloak/assets/75622411/4c6f4dde-2025-43cb-ae3a-1255a453facd)
![image](https://github.com/keycloak/keycloak/assets/75622411/027378d1-272a-415e-8520-c14ec087e05d)

When I use the evaluation option in the keycloak it is giving the permission for that scope
![image](https://github.com/keycloak/keycloak/assets/75622411/fa5e42f0-1a79-4d69-a6e7-8bccd3bae497)
![image](https://github.com/keycloak/keycloak/assets/75622411/61360064-d5c4-441d-b3f3-690cc50d0fc2)

when I am the RPT token using the token API POST: http://localhost:8080/realms/dev/protocol/openid-connect/token by passing the authentication token with the following 2 values grant_type = urn:ietf:params:oauth:grant-type:uma-ticket, audience = service-client in the token the 'read' scope is missing for the same user. Even the token is having the mapper value
image

This is behavior is working fine when I change the 'Token Claim Name' in the Mapper to 'attributes' from 'attributes.values' and changed the policy accordingly.

**Comment by pedroigor** [comment]
@sridhar1495 The issue you linked should be fixed by https://github.com/keycloak/keycloak/pull/20798.

The 22 is now released and you can try it out.

**Comment by sridhar1495** [comment]
@pedroigor Thank you for the information. I have tested my scenario in the 22.0.0version and it is working now. We are moving to that version. And closing this.
