### ISSUE TITLE
Need option to automatic redirect probably to Base URL during password reset 

### ISSUE THREAD

**Issue by iingawal** [keycloak/keycloak#21633]
### Description

If the user closes their browser after requesting a reset-credential email, the redirect_uri is forgotten when the user clicks the link in the email.
Hence need a option to automatic redirect probably to Base URL .

### Discussion

https://github.com/keycloak/keycloak/issues/21127

**Comment by mposolda** [comment]
duplicates #21127

I am closing as duplicate, so we don't have more GH issues for the same thing.
