### ISSUE TITLE
docs/building.md outdated

### ISSUE THREAD

**Issue by vaceksimon** [keycloak/keycloak#21643]
### Description

The [docs/building.md](https://github.com/keycloak/keycloak/blob/main/docs/building.md) file is a bit outdated. Specifically the NOTE about editing the `~/.m2/settings.xml` in the [Building from source section](https://github.com/keycloak/keycloak/blob/main/docs/building.md#building-from-source) is no longer applicable.

Then also in the section [Starting Keycloak](https://github.com/keycloak/keycloak/blob/main/docs/building.md#starting-keycloak), the guide suggests building and then running the server from `distribution/server-dist/` which is no longer right.

**Comment by jonkoops** [comment]
Thanks for reporting this @vaceksimon! If you would be interested in fixing this issue, let me know and I will assign you.

**Comment by lhanusov** [comment]
@jonkoops thanks Jon, I will assign it to Simon and together fix it.

**Comment by christian-2** [comment]
related #20494
