### ISSUE TITLE
Account V3 Missing translate Refresh

### ISSUE THREAD

**Issue by dima-bzz** [keycloak/keycloak#21657]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Missing translate Refresh button on the active devices page.

### Version

21.1.2, 22.0.0

### Expected behavior

Support translate Refresh button

### Actual behavior

Missing translate 

### How to Reproduce?

Translation is not applied

**Comment by ssilvert** [comment]
I have verified this issue.

**Comment by jonkoops** [comment]
This has been fixed under #21676
