### ISSUE TITLE
Account v3 broken url for device session termination but success notification is shown despite 404

### ISSUE THREAD

**Issue by sebastianhoe** [keycloak/keycloak#21656]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

The URL to terminate a device session in the Account v3 console contains a " (double quote) in src/api/methods.ts method deleteSession:
`return request(`**"**/sessions${id ? `/${id}` : ""}`, {`
Despite a 404 error due to that additional " character a success notification is shown to the user.

### Version

21.1.1

### Expected behavior

The session is actually termianted as the correct URL is shown.
In case of an error, an error is shown to the user instead of a success notification.

### Actual behavior

Session not terminated due to 404 when calling API endpoint, and success notification is shown to user anyways.

### How to Reproduce?

Go to account v3 > Devices > terminate a session of a device (user needs to be logged in in more than one device / window).

**Comment by ssilvert** [comment]
I don't see a failure here.

I did notice that the button labels on the "Sign out" confirmation modal are not finding their localization keys, but that's a different issue.

Can you be a bit more specific about the steps to reproduce?  Also, did you try this on the nightly build?

**Comment by dima-bzz** [comment]
This problem has already been solved #21466
