### ISSUE TITLE
Update keycloak operator issue

### ISSUE THREAD

**Issue by igor-sidorov** [keycloak/keycloak#21651]
### Description

While updating keycloak operator via helm chart getting error:

`cannot patch "keycloak-operator" with kind Deployment: Deployment.apps "keycloak-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"keycloak-operator", "app.kubernetes.io/version":"22.0.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

Is any documentation or practice how update keycloak operator in  kubernetes without downtime?

**Comment by shawkins** [comment]
> Is any documentation or practice how update keycloak operator in kubernetes without downtime?

No, for #20906 this was discussed, but the decission was to allow the the operator to delete the statefulset as a one time operation.

**Comment by abstractj** [comment]
@igor-sidorov as @shawkins mentioned, the downtime is the expected behavior, and a trade-off that we jointly agreed. About HELM charts, we do not support them, so please report issues related with HELM charts to the respective repository.

Closing it for now, but if you disagree, please reopen.
