### ISSUE TITLE
Keycloak as Docker Container unable to start when FIPS is enabled

### ISSUE THREAD

**Issue by cprocak95** [keycloak/keycloak#21663]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

When setting the docker container for keyclock to have FIPS enabled, it will run the container but keycloak does not come up and the UI is not responding in the browser. In addition, no logs are displayed when the container is running to help with debugging the issue.
The flag that, when set causes the issue is: 
-Dcom.redhat.fips=true

### Version

latest

### Expected behavior

When running in FIPS enabled mode on a FIPS enabled system, the keycloak UI should appear and respond to user input

### Actual behavior

The UI does not respond unless FIPS is disabled on the container and no logs are generated to address the problem

### How to Reproduce?

Use the following Dockerfile where the lines for COPY have the corresponding jars and files local to the Dockerfile. Build this as the Keycloak image with the necessary FIPS jars. This file was created by following the following documentation:
https://www.keycloak.org/server/fips#_keycloak_server_in_fips_mode_in_the_container

```
FROM quay.io/keycloak/keycloak:latest as builder

WORKDIR /opt/keycloak

COPY bc-fips-1.0.2.3.jar /opt/keycloak/conf/
COPY bcpkix-fips-1.0.7.jar /opt/keycloak/conf/
COPY bctls-fips-1.0.16.jar /opt/keycloak/conf/
COPY kc.java.security /opt/keycloak/conf/
COPY realm.json /opt/keycloak/data/import/realm.json

RUN keytool -keystore /opt/keycloak/conf/server.keystore \
-storetype bcfks \
-providername BCFIPS \
-providerclass org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
-provider org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
-providerpath /opt/keycloak/conf/bc-fips-*.jar \
-alias localhost \
-genkeypair -sigalg SHA512withRSA -keyalg RSA -storepass passwordpassword \
-dname CN=localhost -keypass passwordpassword \
-J-Djava.security.properties=/opt/keycloak/conf/kc.java.security

RUN /opt/keycloak/bin/kc.sh build --features=fips --fips-mode=strict

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

CMD ["start-dev", "--import-realm"]

```
This container uses mysql as the backend and will not work when the following flag is set:
JAVA_OPTS_APPEND: "-Dcom.redhat.fips=true"
When it is set to false, it will start up and the UI can be reached

### Anything else?

https://www.keycloak.org/server/fips#_keycloak_server_in_fips_mode_in_the_container

**Comment by pedroigor** [comment]
@cprocak95 Looks like you are copying the `bc` JARs to the `conf` directory. They should be at the `providers` directory. 

The documentation looks correct.

**Comment by cprocak95** [comment]
Thanks for the reploy @pedroigor. I changed the Dockerfile to put the jars in providers but the behavior from the image is the same. No logs are displaying when it is run as a container and the UI is not responding. I looked at the packages coming in with Wireshark but that doesn't give any useful information.
