### ISSUE TITLE
Could not obtain connection to query metadataerror while using Keycloak 21.1.2 and JDK17 on Windows 11  

### ISSUE THREAD

**Issue by hitechie17** [keycloak/keycloak#21669]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

After going through the entire thread https://github.com/keycloak/keycloak/issues/16448,
 Agree with Sebdul. I too have HyperV in my machine with JDK17 and Windows 11.
The issue still persists, and I require both Hyper V and Keycloak on my machine, so this needs a permanent fix.
Raising new issue here with logs as the earlier one seems to be closed but issue persists in keycloak-21.1.2
[issue.txt](https://github.com/keycloak/keycloak/files/12036020/issue.txt)

Initial setup and startup worked fine, however subsequent startup-dev errored out, despite clearing data folder, in vain.

### Version

21.1.2

### Expected behavior

Keycloak to start correctly with the following environment - Jdk 17, Windows 11 and Hyper V enabled with WSL2.

### Actual behavior

First startup post installation was fine, any subsequent startup errors  out due to connection errors

### How to Reproduce?

1. Download install keycloak-21.1.2 on Windows 11 with WSL2 and Hyper V enabled
2. Run kc.bat using start-dev
3. Let it be idle for hours
4. Reboot
5. Try running start-dev again next day post reboot
6. Tada- Error replicated

### Anything else?

I need to test this on my local machine which is Windows, if this gets fixed, need to test my Keycloak integration on production API's which is on  kubernates cluster, would the idle time or cluster environment be stable if we integrate keycloak with our production API's using WSO2?

**Comment by ahus1** [comment]
I've tested this with the latest version of Keycloak 22.0.1 on Windows 11. 

Using "start-dev" works fine, and I can restart the Keycloak instance OK. 

How did you shutdown Keycloak in the "start-dev" mode? Note that for a production setup, an external database is required (PostgreSQL, etc.) - see https://www.keycloak.org/server/db

When the database is shut down in development mode unexpectedly, you might need to clean the "data" folder including all subfolders (especially the "h2" folder). 

Please let me know if this helps.

**Comment by ahus1** [comment]
Closing this issue as we're missing input from the community.
