### ISSUE TITLE
Long-running tasks need wait cursor.

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#21678]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

We have two tasks that need a wait cursor:

- Large partial import of subgroups
- Delete realm that has these subgroups

I'm not sure if this is only related to subgroups, but I can see the issue when I import a group with 1000 subgroups.  After that is done, I will also see the issue when I try to delete the realm.  In both cases, there is no wait cursor and no indication that there is a long-running operation.

### Version

keycloak-999.0.0-SNAPSHOT

### Expected behavior

For large partial import, the dialog should disappear and show a wait cursor until the process is done and the "finished" dialog is shown.

For deleting the realm, the wait cursor should be shown until the process is done.

### Actual behavior

For large partial import, you click import and nothing seems to happen.  There is no indication that a process is running.

For deleting the realm, everything looks normal except that there is no "success" message.  The message will come about 30 seconds later.

### How to Reproduce?

You can use this json file to do the partial import and re-create the problem.

[groups-10000-in-subgroup.zip](https://github.com/keycloak/keycloak/files/12040025/groups-10000-in-subgroup.zip)

**Comment by jonkoops** [comment]
I think this is working to much on a solution in terms of UX. I'd rather see the loading state on the button itself. Also would be more easy to implement as PatternFly [already has](https://www.patternfly.org/v4/components/button/) progress indicators for buttons.

**Comment by ahus1** [comment]
When deleting a realm with a lot of groups, this is currently very slow. The time to delete a realm is prolonged probably exponentially with the number of groups present in the realm - see the other issue.

**Comment by jonkoops** [comment]
In that case, I think we should show a message to the user after X amount of seconds, with something like "This process can take a while, please wait.".

**Comment by edewit** [comment]
This issue can be closed we since optimised the groups fetch queries quite a bit
