### ISSUE TITLE
Reopen: Keycloak docker image corrupts itself after a few hours of use

### ISSUE THREAD

**Issue by NicoloLazzaroni** [keycloak/keycloak#21697]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Hello,

This issue is a continue of #20041 which has been closed but still persists.

I have a problem with keycloak latest docker image.

I run multiple keycloak instances over docker and had this issue 4 times in a week.

The images run perfectly until a day or so passes and then, when restarted after this yime passes, produce this error:

```
keycloak-public-1 | 2023-07-14 11:23:57,727 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-kerberos-federation / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,727 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-sssd-federation / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,728 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-ldap-federation / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,728 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-config-api / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,730 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-account-ui / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | ERROR: Failed to run 'build' command.
keycloak-public-1 | ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar
keycloak-public-1 | For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

As I use docker-compose I tried to delete the container and re-compose it but the error still occurs.

The only way to solve it is to delete keycloak's docker image and redownload it with docker-compose.

PS. This corruption seems to happen randomly and is not related to the restarts themselves, as I could restart docker and/or the keycloak containers with no problems before a day or so passed.

This is one of my docker-compose files (the one related to the logs):

**Update:** Even tho it says it is due to admin-ui jar the error occurs both with admin features enabled and disabled.

```
version: '3'

services:
  keycloak:
      container_name: keycloak-public-1
      image: quay.io/keycloak/keycloak:latest
      networks:
        - keycloak
      command: start \
        --db=mariadb --features=token-exchange \
        --db-url=jdbc:mariadb://CENSORED:CENSORED/CENSORED --db-username=CENSORED --db-password='CENSORED' \
        --proxy=edge --features-disabled="admin-api,admin2" \
        --hostname-strict=false --spi-sticky-session-encoder-infinispanshould-attach-route=false \
        --spi-theme-welcome-theme=custom
      volumes:
       - /etc/keycloak/themes:/opt/keycloak/themes
      ports:
       - "127.0.0.1:CENSORED:8080"
networks:
  keycloak:

```

### Version

22.0.0

### Expected behavior

Keycloak should start normally.

### Actual behavior

I get the error:

```
keycloak-public-1 | 2023-07-14 11:23:57,727 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-kerberos-federation / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,727 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-sssd-federation / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,728 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-ldap-federation / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,728 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-config-api / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | 2023-07-14 11:23:57,730 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-account-ui / runtime=true resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak-public-1 | 
keycloak-public-1 | ERROR: Failed to run 'build' command.
keycloak-public-1 | ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar does not exist
keycloak-public-1 | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar
keycloak-public-1 | For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

### How to Reproduce?

Run keycloak dockerized for a day or so and restart it.

### Anything else?

I am using docker-compose to run my containers.

These are the versions:

```
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by pedroigor** [comment]
Could you check if the file `/opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar` is actually there? It shouldn't be removed by any means.

**Comment by NicoloLazzaroni** [comment]
> Could you check if the file `/opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.0.jar` is actually there? It shouldn't be removed by any means.

Sorry for the late reply. The image is now broken permanently, even by reinstalling it, it doesn't work. As the container shutdowns right away I am not able to check for the missing file, but I remember from the tests made for my previous issue, that the file was, indeed, missing.

**Comment by vmuzikar** [comment]
> even by reinstalling it

@NicoloLazzaroni Sorry you are still facing issues. Can you please clarify what do you mean by "reinstalling"? Deleting the container and creating a new one?

**Comment by NicoloLazzaroni** [comment]
> > even by reinstalling it
> 
> 
> 
> @NicoloLazzaroni Sorry you are still facing issues. Can you please clarify what do you mean by "reinstalling"? Deleting the container and creating a new one?

Deleting the container, the volume and the image.

**Comment by vmuzikar** [comment]
@NicoloLazzaroni Are you able to reproduce on a different machine/host? Sounds like an issue with your docker instance.

**Comment by NicoloLazzaroni** [comment]
> 

While I have no other machines to try this issue on I tried cleaning up mine and resetting docker. Now the containers start. I'll keep you all update to check if the issue stated in #20041 persists and the containers stop working after a few days.

**Comment by NicoloLazzaroni** [comment]
Okay, this is pretty weird.

The issue reappeard restarting the docker-compose service after 24 hours with the same error:

```
Aug 26 15:38:00 node2 docker-compose[1460749]: keycloak-account | ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.jar does not exist
Aug 26 15:38:00 node2 docker-compose[1460749]: keycloak-account | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.jar does not exist
Aug 26 15:38:00 node2 docker-compose[1460749]: keycloak-account | ERROR: /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.jar
```

Now, the weird part is inside the container that I did not restart and, therefore, is still running.
By runing `ls /opt/keycloak/lib/lib/main/` I see all org.keycloak... libraries except for admin-ui, but when I run `cat /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.jar` it produces a result, unreadable as it is java but it means that it exists.

I tried running  `mv /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.jar /opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.ja` to see if the new file would appear in the list but I got the error:

`mv: cannot move '/opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.jar' to '/opt/keycloak/lib/lib/main/org.keycloak.keycloak-admin-ui-22.0.1.ja': Stale file handle`

**Comment by vmuzikar** [comment]
@NicoloLazzaroni Can you please try and reproduce on another physical machine (if you haven't already)? Really looks like an issue with your docker instance. AFAICT, there's not much we can do from Keycloak side to affect this.

**Comment by shawkins** [comment]
Closing for lack of feedback.

**Comment by NicoloLazzaroni** [comment]
Hello,

I thought it was an issue on my side, but now I bought a new VPS and moved there the docker compose, same exact issue.

docker-compose.yml:
`version: '3'

services:
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:latest
      networks:
        - keycloak
      command: start --db=mariadb --features=token-exchange --db-url=jdbc:mariadb://CENSORED/keycloak --db-username=keycloak --db-password='CENSORED' --proxy=edge --hostname-strict=false --spi-sticky-session-encoder-infinispan-should-attach-route=false --spi-theme-welcome-theme='custom'
      volumes:
       - /etc/keycloak/themes:/opt/keycloak/themes
       - /etc/keycloak/META-INF:/opt/keycloak/META-INF
      ports:
       - "127.0.0.1:8989:8080"
networks:
  keycloak:`
  
  Docker version: 
  `Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Thu May 18 08:38:34 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       5d6db84
  Built:            Thu May 18 08:38:34 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:     `
  
  docker-compose version:
  `docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.2
OpenSSL version: OpenSSL 3.0.11 19 Sep 2023`

Latest version of Keycloak with auto-update via Watchtower.
