### ISSUE TITLE
Disable admin console of keycloak public endpoint

### ISSUE THREAD

**Issue by pravinjec** [keycloak/keycloak#21694]
### Description

Hi Team,

keycloak operator deployed in kubernetes environment.
Due to security reason i want to hide admin console from the keycloak public endpoint.
In place of admin console I want a user login page should open .
Once I will create a new user having admin rights through admin console login , i want to hide it.

Can anyone please help me as i have tried multiple blogs but this questions is not answered

**Comment by akbar1214** [comment]
@pravinjec can you try using different hostname for admin panel and then have that url accessible only using vpn or other approaches https://www.keycloak.org/server/hostname

**Comment by vmuzikar** [comment]
Duplicate of https://github.com/keycloak/keycloak/issues/12394

**Comment by vmuzikar** [comment]
Related discussion https://github.com/keycloak/keycloak/discussions/12481
