### ISSUE TITLE
New Admin UI: Group Attribute UI does not refresh, shows stale values

### ISSUE THREAD

**Issue by ice09** [keycloak/keycloak#21693]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I want to change an attribute value on a group:
1. I click on "Groups" in the left main menu
2. I choose the group I want to change in the "search groups" panel
3. I click on tab "Attributes", change the value of the attribute and click on Save
4. I click on the group again in the "search groups" panel
5. The old values are shown
6. Same happens if I click on other tabs in the group UI and switch back to attributes
7. I have to reload the whole page or click on "Groups" in the breadcrumps to load the changed value

![image](https://github.com/keycloak/keycloak/assets/2828581/3c1c6e87-27e6-4efa-86fc-df6d0aa5dd4e)

### Version

21.0.1/21.1.1

### Expected behavior

I want to change an attribute value on a group:
1. I click on "Groups" in the left main menu
2. I choose the group I want to change in the "search groups" panel
3. I click on tab "Attributes", change the value of the attribute and click on Save
4. A HTTP GET is called to updated the cached values and the new value is always shown.

### Actual behavior

see Bug Description.

### How to Reproduce?

1. Start nightly with "kc.sh start-dev"
2. Follow the steps above

**Comment by ssilvert** [comment]
I have verified this bug.
