### ISSUE TITLE
AccountV3/User Profile: Attributes annotations not used

### ISSUE THREAD

**Issue by YannickFi** [keycloak/keycloak#21699]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Annotations defined on an attribute are ignored/not used in the account3 theme
![image](https://github.com/keycloak/keycloak/assets/31122955/e8971564-bbcb-48e4-8dce-39665a8e7c49)
![image](https://github.com/keycloak/keycloak/assets/31122955/5a0c985f-a2e9-442f-99c9-36817b0e7a01)

### Version

22.0.0

### Expected behavior

Input fields should be rendered like in the dynamics forms e.g.`base/login/update-user-profile.ftl`
<img width="779" alt="image" src="https://github.com/keycloak/keycloak/assets/31122955/2806aee6-eed8-448c-9214-3fc7b2bfaf9a">

### Actual behavior

Annotations are ignored 

### How to Reproduce?

* Activate account3 and declarative-user-profile feature
* Add new attribute with annotations ![image](https://github.com/keycloak/keycloak/assets/31122955/e8971564-bbcb-48e4-8dce-39665a8e7c49)
* Check account page 

### Anything else?

Account3: 
https://github.com/keycloak/keycloak/blob/6541cd56e0dc6ff0615570a20a444524debbe316/js/apps/account-ui/src/personal-info/FormField.tsx#L84-L91

**Comment by ssilvert** [comment]
I think this is just a case of something that is not implemented yet.  But it needs to be done before Account V3 goes from Preview to final.  Assigning to @edewit so he can comment or just implement under this issue.
