### ISSUE TITLE
‘termsText’ community provided values make it hard to customize terms.ftl without replacing it

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#21705]
### Description

`termsText` base message is `Terms and conditions to be defined`.

Community provided message bundles translate this message in each language.

Suppose english is the default language. If one overrides the english message in its own theme, only the english message will be changed. Each language alternative will keep presenting a message meaning `Terms and conditions to be defined`.

Because of that, one that wants to customize the message must absolutely do it in in the properties of each realm’s enabled language.

### Motivation

Default language’s custom terms and conditions should be used as a fallback for alternative language missing dedicated terms and conditions.

E.g. if my default language is english and I defined custom terms and conditions in english and I didn’t define custom terms and conditions in spanish, when using spanish I should see my english terms and conditions.

**Comment by reda-alaoui** [comment]
@jonkoops 

For example, I want to be able to enable the spanish language without having to immedialty provide spanish terms and conditions.
Terms and conditions are provided by the legal department, often it takes time to get them. In between, I want spanish speakers to see the english terms and conditions.

Currently, if I enable spanish langage without providing my terms and conditions, spanish speakers see `<p>T\u00E9rmines y condiciones a definir</p>`.

**Comment by jonkoops** [comment]
In that case, why not place the English terms and conditions in your own locale for Spanish?

**Comment by jonkoops** [comment]
I understand your point of view, but we have to weigh feature requests against maintainability and also usefulness to others. This would be an exception to how our localization works for only a single key, which we'd have to document, and might arguably be unwanted behavior for other users, so we'd also have to make it configurable (as per [your PR](https://github.com/keycloak/keycloak/pull/21706)).

I don't see the value add here, and I think it's not worth the cost or confusion. I'll close this issue for now, because I see it having very little chance of getting implemented. We can of course re-consider this, or the approach in the future if other users are experiencing similar issues.

**Comment by reda-alaoui** [comment]
> Theme implementors are expected to override customTermsTitle and customTermsText messages.

Maybe this quoted sentence from https://github.com/keycloak/keycloak/pull/21706 caused confusion. 
What I meant was that following #21706 merge, we should **recommend** implementors to override `customTermsText` instead of `termsText`. There is no obligation here.

**Comment by reda-alaoui** [comment]
People can enable 20 langages (I did) on their realm. Are they expected to copy/paste english terms and conditions for each language? If yes, please realize they will have to repeat the same operation each time they make a single modification to their english terms and conditions.

I hope you will reconsider.

**Comment by jonkoops** [comment]
> People can enable 20 langages (I did) on their realm. Are they expected to copy/paste english terms and conditions for each language? If yes, please realize they will have to repeat the same operation each time they make a single modification to their english terms and conditions.

Yes, when you are localizing for specific locales you should take the time to do so properly. How can someone accept your terms an conditions if they cannot understand them? Also, depending on the market you are serving, these might even be different for the same language (the law in Mexico can be different than in Spain).

**Comment by reda-alaoui** [comment]
> I guess it's not technically an exception to the localization itself, but it does run the localization conditionally, which is an exception that was not there before.

Yes indeed.

> I can understand your code perfectly fine

Ok great, I was afraid of some confusion caused by one of my sentence in the description.

> And we don't want to if it's just something for your application, it also needs to provide enough value to the rest of the project and it's users

I think it does if they have many langages enabled.

> How can someone accept your terms an conditions if they cannot understand them?

Look at the "french" https://www.redhat.com/fr/about/terms-use . Terms of use are in english, the rest is in french:

![image](https://github.com/keycloak/keycloak/assets/2890843/8a10f19b-2044-45a7-b2f9-3d4f1190b42b)

Moreover, that's beyond the point IMO. Neither of us is a law expert, isn't it?

**Comment by jonkoops** [comment]
> Look at the "french" https://www.redhat.com/fr/about/terms-use . Terms of use are in english, the rest is in french:

Yeah, this is obviously an issue that should be fixed. But this is the Keycloak project, not the Red Hat.com team.

**Comment by reda-alaoui** [comment]
> Yeah, this is obviously an issue that should be fixed. But this is the Keycloak project, not the Red Hat.com team.

This is just an example of a huge company that didn't translate in french its terms of use.

Sorry, I don't see anything obvious on this since I am not a law expert. Our legal department thinks it's perfectly fine.

**Comment by jonkoops** [comment]
Then I would recommend extending the theme and hard-coding these policies.
