### ISSUE TITLE
Liquibase CustomChange are executed twice because of a Liquibase bug fixed in 4.21.0

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#21710]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

Plugins (even Keyloack core ?) relying on Liquibase are hit by https://github.com/liquibase/liquibase/issues/3945 because Keycloak pulls version 4.20.0 .

### Version

22.0.0

### Expected behavior

Liquibase CustomChange should be executed once.

### Actual behavior

Liquibase CustomChange always executes twice.

### How to Reproduce?

Declare a Liquibase CustomChange and see it be executed twice by Liquibase

### Anything else?

Seems to be fixed by https://github.com/liquibase/liquibase/commit/a4d52e1d26e18be194a043f6be4bb6d11db5c379

But be aware of https://github.com/quarkusio/quarkus/issues/34012

**Comment by vramik** [comment]
Thanks @reda-alaoui for the report. Currently we use https://github.com/keycloak/keycloak/blob/c462bbb241288ac31c30cb00f4aa42e89b8f81c6/pom.xml#L129

We may want to keep an eye on it when the liquibase version will be updated.
