### ISSUE TITLE
New Admin UI: User attributes UI does not refresh, shows stale values

### ISSUE THREAD

**Issue by ice09** [keycloak/keycloak#21719]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

Related to https://github.com/keycloak/keycloak/issues/21693

I want to change an attribute value on a user:

1. I click on "Users" in the left main menu
2. I choose the user I want to change in the "search users" panel
3. I click on tab "Attributes", change the value of the attribute and click on Save
4. I click switch to the "Details" tab of the same user and click Save again
5. If I switch back to the "Attributes" tab, the new values are shown
6. If I reload the user by clicking on "Users" and choosing the user in the search panel, the old values are shown in the attributes tab (these old values are also stored in the database)

This does not happen if I do not execute step 4 (ie. save of the details tab after save on the attributes tab) - then the new values are stored correctly.

### Version

21.1.2

### Expected behavior

After saving the values in the attributes tab, the values will not be overwritten with the old values when saving the values again in the details tab.

### Actual behavior

Clicking save on the details tab overwrites the new values which have been saved in the attributes tab with the old values before saving.

### How to Reproduce?

Follow the steps above, can be reproduced in nightly.

**Comment by rmartinc** [comment]
I think this is an UI issue as I see the saving of the details sets back the old values in attributes in step 4. In my tests I see the new value in step 5  but, if the user is reloaded again (go back to users and select the same user again) the old value is present in the attributes.

**Comment by ice09** [comment]
That's correct, I have the same behaviour, I changed the description.

**Comment by ssilvert** [comment]
@ice09 Is this not the same as the issue you opened a couple of days ago?
https://github.com/keycloak/keycloak/issues/21693

**Comment by ice09** [comment]
No, it's probably related (as state in the description), but 21693 is about *group* attributes and this one is about *user* attributes. Also, the errors are a little different, but I assume very much UI/caching related.
