### ISSUE TITLE
An error occurred in accessing keycloak,has been blocked by CORS policy

### ISSUE THREAD

**Issue by baochengjie** [keycloak/keycloak#21713]
### Description

Access to XMLHttpRequest at 'http://xxx:8080/bi/auth/get/user/menu' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by akbar1214** [comment]
@baochengjie can you share a reproducible demo. Looking from the description most probably you are integrating sso in angular. Did you add the valid redirect uri's for the required client ?
