### ISSUE TITLE
Fixing broken JSON translation files

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#21733]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When trying to import the existing translations to Weblate, I found some translations are not valid JSON, as the miss a comma, or other JSON syntax. 

Due to that, the import to Weblate fails.

### Version

main

### Expected behavior

All Admin UI translations are valid JSON

### Actual behavior

Some JSON is wrong

### How to Reproduce?

-

### Anything else?

I'll prepare a PR

**Comment by jonkoops** [comment]
@ahus1 let's also make sure to back-port this fix. I've added it to the 22.0.2 milestone, which is slated for release tomorrow.
