### ISSUE TITLE
Credentials page in Admin UI should show credential creation date

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#21746]
### Description

The credential list on the page in the Admin UI should also show the datetime information when a credential was created, or changed.

Currently the credentials page in the Admin UI does not show the creation date of a credentails.
Therefore an admin must look into the database to determine if the user has recently generated a new password.

![image](https://github.com/keycloak/keycloak/assets/314690/bf515d0e-b867-4b94-b191-86f40ea00e73)

### Motivation

Sometimes during (or as a followup to) support processes it is helpful to see if a user has changed a password or not.

### Details

Currently Keycloak does not differentiate whether a credential is created or changed, it is always deleted an recreated, whereas recreation keeps the original credential id). However, the creation timestamp is updated when a credential is replaced.

**Comment by thomasdarimont** [comment]
We could show the "Created at" info on credentials level like this:
![image](https://github.com/keycloak/keycloak/assets/314690/5e7de827-0c3e-4d38-b276-0e0d266d72a4)

**Comment by jonkoops** [comment]
@xianli123 could you let me know if this makes sense to you? Thomas already created an implementation under #21831. His work looks good to me, so of you agree we can merge this in.

**Comment by xianli123** [comment]
Hi @jonkoops @thomasdarimont Thanks for your work on this. I think this is a good idea to help users get that kind of info. But I'm not sure there are any concerns on the back end. Could you please take a look at this one? @stianst What do you think?

**Comment by thomasdarimont** [comment]
Thanks for having a look! The information was already available in the frontend I just show the creation timestamp.

This helps administrators to see whether a user successfully changed their passwords, e.g. after an account recovery process.

**Comment by xianli123** [comment]
@thomasdarimont Thanks. That's cool. I think we can do that.
