### ISSUE TITLE
Re-instate authenticator alias in authentication flow GUI

### ISSUE THREAD

**Issue by ChrisBrandhorst** [keycloak/keycloak#21745]
### Description

Add the alias of an authenticator below the authenticator name in de authentication flow GUI, similar to the description of a subflow.

### Motivation

In the older GUI, the alias of an authenticator was visible in the GUI when editing an authentication flow. In the new one, these are omitted. Since we have multiple authenticators (5+) of the same type in a certain flow, not showing the alias makes knowing which authenticator to edit difficult to see.

**Comment by ssilvert** [comment]
Changed this to a bug because it is missing functionality compared to the old UI.

**Comment by ssilvert** [comment]
Decided this should be high impact.  The workaround is really hard for a user to deal with.  And this should be easy enough to fix.
