### ISSUE TITLE
Have Route created on OCP even when no Keycloak CR hostname specified

### ISSUE THREAD

**Issue by pgodowski** [keycloak/keycloak#21741]
### Description

I want to use Keycloak on OpenShift (OCP) and want to make sure there is `Route` created for Keycloak, even if I had not specified upfront the hostname value for Keycloak to use.

Seems that Keycloak operator assumes that `Route` for Keycloak is auto-generated by OpenShift based on the `Ingress` resource creates, granted one specifies `className: openshift-default` in the `Keycloak` CR. And then, when if there is `Keycloak.spec.hostname` specified, [adds](https://github.com/keycloak/keycloak/blob/main/operator/src/main/java/org/keycloak/operator/controllers/KeycloakIngress.java#L111) the `host` into `Ingress` resource created.

However, on OCP 4.12+, [`route-controller-manager`](https://github.com/openshift/route-controller-manager) creates `Route` based on the `Ingress` resource, [ONLY if the `Ingress` resource has `.spec.rules.host` specified](https://github.com/openshift/route-controller-manager/blob/main/pkg/route/ingress/ingress.go#L416), otherwise no `Route` is created.

It is perfectly valid to create `Route` on OpenShift, without `host` being specified - in such case, OCP auto-generated the host in the `*.apps.<cluster-dns-name>` subdomain.

So, my key questions are:
- Is the assumption that `hostname` is specified in `Keycloak` CR correct - i.e. is this parameter absolutely required for Keycloak application to work correctly?
  - what breaks when `hostname` is not specified in `Keycloak` CR?
- If `hostname` parameter is not required, should we have the updated Keycloak operator logic in the appropriate way, so that `Route` is created on OpenShift (perhaps a strict tie to Ingres->Route autogeneration could be revised?)

A bit related discussion: https://github.com/keycloak/keycloak/issues/20128 , since eventually we'd like to use the re-encrypt Routes, with the certifies being rotated and replaced with customer's certificates.

### Motivation

Using Keyclok on OpenShift requires `Route` to be exposed outside of the cluster, for external applications / processes interactions.

**Comment by shawkins** [comment]
> Seems that Keycloak operator assumes that Route for Keycloak is auto-generated by OpenShift based on the Ingress resource creates, granted one specifies className: openshift-default in the Keycloak CR

That isn't a strict assumption - there are other ingress controllers which could be used.

> However, on OCP 4.12+, [route-controller-manager](https://github.com/openshift/route-controller-manager) creates Route based on the Ingress resource, [ONLY if the Ingress resource has .spec.rules.host specified](https://github.com/openshift/route-controller-manager/blob/main/pkg/route/ingress/ingress.go#L416), otherwise no Route is created.

Have you raised an issue on the openshift side of things to support this?

> Is the assumption that hostname is specified in Keycloak CR correct - i.e. is this parameter absolutely required for Keycloak application to work correctly? what breaks when hostname is not specified in Keycloak CR?

It's optional - as you see nothing breaks from the operator perspective if it isn't specified.  

> If hostname parameter is not required, should we have the updated Keycloak operator logic in the appropriate way, so that Route is created on OpenShift (perhaps a strict tie to Ingres->Route autogeneration could be revised?)

The operator does not have a strict assumption about autogeneration.

Have you considered disabling ingress in the spec and simply creating the route that you want?

**Comment by pgodowski** [comment]
Thank you for your responses,

> > Seems that Keycloak operator assumes that Route for Keycloak is auto-generated by OpenShift based on the Ingress resource creates, granted one specifies className: openshift-default in the Keycloak CR
> 
> That isn't a strict assumption - there are other ingress controllers which could be used.

That's correct - point taken.


> > However, on OCP 4.12+, [route-controller-manager](https://github.com/openshift/route-controller-manager) creates Route based on the Ingress resource, [ONLY if the Ingress resource has .spec.rules.host specified](https://github.com/openshift/route-controller-manager/blob/main/pkg/route/ingress/ingress.go#L416), otherwise no Route is created.
> 
> Have you raised an issue on the openshift side of things to support this?

No, I haven't, perhaps makes sense doing so, need to read more thru the OpenShift code to understand the motivation there, before doing so.

> > Is the assumption that hostname is specified in Keycloak CR correct - i.e. is this parameter absolutely required for Keycloak application to work correctly? what breaks when hostname is not specified in Keycloak CR?
> 
> It's optional - as you see nothing breaks from the operator perspective if it isn't specified.

Thanks - can you please confirm Keycloak operand works perfectly fine too without `hostname` ? Like are they callback urls which Keycloak would generate to some external entities?

Other way of asking is: why one would even specify the `hostname` for Keycloak?


> > If hostname parameter is not required, should we have the updated Keycloak operator logic in the appropriate way, so that Route is created on OpenShift (perhaps a strict tie to Ingres->Route autogeneration could be revised?)
> 
> The operator does not have a strict assumption about autogeneration.
> 
> Have you considered disabling ingress in the spec and simply creating the route that you want?

I have considered this, but I would expect that Keycloak operator would provide the first-class OpenShift support, with `Route` being generated, when running on OpenShift. There is a risk that custom code would get out of sync with any potential future changes how Keycloak `Service` is defined.

Additionally, got an impression based on https://github.com/keycloak/keycloak/issues/20128 that the support for Routes is something being actually considered in the Keycloak operator.

**Comment by shawkins** [comment]
> Thanks - can you please confirm Keycloak operand works perfectly fine too without hostname ? Like are they callback urls which Keycloak would generate to some external entities?

The hostname is only used for the ingress rule and nothing else.

> Other way of asking is: why one would even specify the hostname for Keycloak?

Presumably in situations where you already have an external hostname for your keycloak.

> Additionally, got an impression based on https://github.com/keycloak/keycloak/issues/20128 that the support for Routes is something being actually considered in the Keycloak operator.

I'd have to differ to others on that - @vmuzikar ?

To rephase - your expection here is that when the operator is deployed on openshift there would be an option to not create the Ingress, but instead directly create the Route, is that correct?

**Comment by Jamstah** [comment]
> The hostname is only used for the ingress rule and nothing else.

I thought the hostname could also be used for verifying the host on http requests in strict mode:
https://www.keycloak.org/operator/advanced-configuration#_server_configuration_details

**Comment by pgodowski** [comment]
> >   Other way of asking is: why one would even specify the hostname for Keycloak?
>   Presumably in situations where you already have an external hostname for your keycloak.

So again - if I had external hostname, how Keycload would make use of this value (where exactly?).
Reason I am asking this question is whether Route (even if created separately) needs to factor in the specified hostname for some reason.

> To rephrase - your expectation here is that when the operator is deployed on openshift there would be an option to not create the Ingress, but instead directly create the Route, is that correct?

Correct - I would expect that on OpenShift, Keycloak operator would create `Route` directly.

**Comment by shawkins** [comment]
> I thought the hostname could also be used for verifying the host on http requests in strict mode:
https://www.keycloak.org/operator/advanced-configuration#_server_configuration_details

I'm referring strictly to spec.hostname.hostname

> If I had external hostname, how Keycloak would make use of this value (where exactly?).

On openshift if you have an external hostname, and point the DNS for it to the load balancer associated with the ingresscontroller, then that traffic will reach the appropriate Route.

**Comment by vmuzikar** [comment]
Keycloak is now designed with secure by default principles. This also includes the requirement for specifying [hostname](https://www.keycloak.org/server/hostname) (which affects redirect URIs etc.). `spec.hostname.hostname` is used both for setting this on Keycloak, and for the Ingress as well. It is possible to [disable](https://www.keycloak.org/operator/advanced-configuration#_disabling_required_options) the strict mode on Keycloak which makes the hostname field optional. To support this scenario, we made the CR field optional too. However, this setting is strictly not recommended in prod.

However, it is a good point we could leverage the OCP's generated hostnames on Route. We could read it and set in on the Keycloak instance (if not specified).

**Comment by shawkins** [comment]
> spec.hostname.hostname is used both for setting this on Keycloak, and for the Ingress as well

Ah, I had missed it was being passed in via a dist property.

>  To support this scenario, we made the CR field optional too.

Should there be a warning when strict != false and the hostname is not set?  Without strict=false it looks like the keycloak will fail to start with just a crashloop and nothing in the logs to indicate why.

**Comment by pgodowski** [comment]
> However, it is a good point we could leverage the OCP's generated hostnames on Route. We could read it and set in on the Keycloak instance (if not specified).

So I am thining along the same line - i.e. on OCP to have the Route being created and then pick the `hostname` from Route and pass it into Keycloak instance, if `spec.hostname.hostname` is not already specified.

Would it be acceptable behavior?

**Comment by vmuzikar** [comment]
@pgodowski Yes, makes sense to me. We'd probably need to make sure the statefulset is created after we have the generated hostname from route to avoid startup failures and rolling update of the statefulset. [Reconcile precondition](https://github.com/keycloak/keycloak/blob/fa1f1ebc701a14a0d8e51bcc298ae7f67891b55a/operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java#L54) might be useful.

**Comment by pgodowski** [comment]
Fair point - we'll take a look at the dependent resources concept in the SDK first. In general we need to wait not only to wait for Route created, but also OCP to generate hostname and update Route spec with the generated hostname, which I guess is handled by the 'enabled condition checking' as part of this framework.

**Comment by shawkins** [comment]
> Yes, makes sense to me. We'd probably need to make sure the statefulset is created after we have the generated hostname from route to avoid startup failures and rolling update of the statefulset. [Reconcile precondition](https://github.com/keycloak/keycloak/blob/fa1f1ebc701a14a0d8e51bcc298ae7f67891b55a/operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java#L54) might be useful.

To circle back to some earlier discussion, are we assuming that the Ingress on openshift is always backed by the openshift-default ingress to route implementation?  The ability to set the ingress classname implies we are not, but the discussion here and the usage of openshift specific annotation route.openshift.io/termination implies that we are.  If we are not, and the user has some other default, or sets the classname to something else, then we can't assume that the route will be created (not just because of the missing host name) nor associated to the ingress / managed by openshift should we create one.  We may need to consider an additional cr field, or operator config, that explicitly directs the operator to directly use routes instead of ingress.

**Comment by pgodowski** [comment]
> We may need to consider an additional cr field, or operator config, that explicitly directs the operator to directly use routes instead of ingress.

I imagine customers on OCP who would still want only `Ingress` to be created, while some of them would like re-encrypt Route created instead. So to me I think we're speaking about some field which configured whether Ingress or Route shall be created.
