### ISSUE TITLE
Preserve the username/sub case-sensitive from the identity provider when Keycloak is acting as the identity broker

### ISSUE THREAD

**Issue by shiup** [keycloak/keycloak#21757]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Keycloak is used as identity broker for SAML/OIDC providers, SAML username is case sensitive, and other OIDC provider's username/sub/preferred-username can be case sensitive

OIDC spec marks sub as case sensitive string.  Without the case being preserved, this is a security risk.

As 3 different users with different sub, 'Alice', 'ALICE', 'alice' are all mapped to the same user's sub (as they are being lowercase(username) === alice)

<img width="1133" alt="image" src="https://github.com/keycloak/keycloak/assets/24717424/a9f30756-cc43-40b3-b28f-69d8e1f4e853">

A similar, but various form of this is https://github.com/keycloak/keycloak/issues/9405

It is highly desirable if Keycloak will allow customers to configure this

### Version

Latest

### Expected behavior

Prefer the case from the source on the case for sub/username

### Actual behavior

Keycloak lowercase(sub|username)

### How to Reproduce?

na

### Anything else?

If the case is not preserved from the source identity provider, this will introduce security vul for the RP which uses Keycloak as idP

Keycloak is used as an identity broker for SAML/OIDC providers, SAML username is case sensitive, and other OIDC provider's username/sub/preferred-username can be case sensitive

OIDC spec marks sub as case sensitive string.  Without the case being preserved, this is a security risk.

As 3 different users with different sub, 'Alice', 'ALICE', 'alice' are all mapped to the same user's sub (as they are being lowercase(username) === alice)

<img width="1133" alt="image" src="https://github.com/keycloak/keycloak/assets/24717424/a9f30756-cc43-40b3-b28f-69d8e1f4e853">

A similar, but various form of this is https://github.com/keycloak/keycloak/issues/9405

It is highly desirable if Keycloak will allow customers to configure this

**Comment by DominicDetta** [comment]
Hi, I think this is already achievable thanks to the Username Template Processor Importer mapper which you can configure after selecting you identity provider in Mappers tab. The field Template let you decide if you want lowercase/uppercacse or none to the substitued value.

**Comment by pedroigor** [comment]
Case-sensitive usernames have been the subject of different discussions and requests from the community. This is not only specific for brokering but also other federation providers such as LDAP.

They all ended up with the same conclusion where lowercase is there by design.

As mentioned by @shiup, you can still pass over the original username from the IdP by using a user session note mapper, if that is your intention.
