### ISSUE TITLE
admin-console 22.0.0 unusable

### ISSUE THREAD

**Issue by burner-account** [keycloak/keycloak#21758]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

To my surprise i was not able to get 22.0.0 to run. Symptoms:

Whilte trying to access the admin console, the login-process fails.

- non-operator k8s: admin credential input results in login loop (fetch on whoami, serverinfo fail) 401
or
- operator k8s: cannot reach login form, 403 while fetching https://public-domain.xy/auth/realms/master/protocol/openid-connect/login-status-iframe.html/init?client_id=security-admin-console&origin=https://internal-admin-domain.xy 

OS: ubuntu 23.04 lunar
Browser: firefox 116.0b5

keycloak on k8s: 1.27.1

### Version

22.0.0

### Expected behavior

Login to the admin console should be possible.

### Actual behavior

see description

### How to Reproduce?

I would have to guess. What i did try:
("started with" can be read as: clean DB, fresh install)

- startet with a custom 21.1.1 image, without operator -> everything is fine
- started with a custom 21.1.2 image, without operator -> everything is fine

- switched javax to jakarta in extensions
- started with a custom 22.0.0 image, without operator -> login loop
- started with a clean 22.0.0 image, without operator -> login loop
- read about host debug page:  all OK

- read about operator
- startet with clean 21.1.1 image & operator -> everything is fine
- startet with clean 21.1.2 image & operator -> everything is fine
- startet with custom 21.1.2 image & operator -> everything is fine

- startet with custom 22.0.0 image & operator -> not even login form reached
- startet with clean 22.0.0 image & operator -> not even login form reached

- read about firefox cookie partitioning -> tweaked setting with no positive result

### Anything else?

As there are no errors on the pod logs (keycloak & operator)  i cannot provide those.

Am i alone having such trouble?

Although i did check the related checkbox, i did not use a nightly build.

**Comment by toabi** [comment]
You're not alone with your troubles. I just updated my operator-setup to a 22.0.0 image and can't use the admin-domain anymore. The normal login seems to still work, but I configured operator to use a different domain for the admin console and that only loops now.

In v21 it actually also did that in Safari, but it worked in Firefox. I blamed Safari.
In v22 it now also breaks in Firefox.

**Comment by toabi** [comment]
I added the following thing to my Keycloak CR:

```
additionalOptions = [
  {
    name  = "proxy"
    value = "edge"
  }
]
```

and now admin even works in Safari…

**Comment by burner-account** [comment]
> I added the following thing to my Keycloak CR:
> 
> ```
> additionalOptions = [
>   {
>     name  = "proxy"
>     value = "edge"
>   }
> ]
> ```
> 
> and now admin even works in Safari…

PSA: The CR options seems to overwrite environment variables baked into a custom image.
I mistakenly assumed that my custom image "had all it needed". Don't fall for it.

Thank you toabi!

**Comment by jonkoops** [comment]
Closing this as it seems to be a configuration error as mentioned above.
