### ISSUE TITLE
v 22.0.0 rest-api, cleans user email when updating attributes (with user-profile enabled)

### ISSUE THREAD

**Issue by guilhermebferreira** [keycloak/keycloak#21751]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When using `PUT` against `/admin/realms/<realm>/users/<user_id>`
To update user's attributes
It has the side-effect of deleting user email

`{'attributes': {'phoneNumber': 'XXXXX'}}`

I use the same endpoint to update user name and to set required actions

But this issue is only observed when adding an attribute

Not happening when using keycloak:21

Happening when using:

- quay.io/keycloak/keycloak:nightly
- quay.io/keycloak/keycloak:22.0

### Version

22.0

### Expected behavior

Using put to set/update user's attributes, only changes attributes

### Actual behavior

Using put to set/update user's attributes, is also deleting user email

### How to Reproduce?

`PUT`: `/admin/realms/<realm>/users/<user_id>`

payload:
`{'attributes': {'phoneNumber': '9999999'}}`

**Comment by mposolda** [comment]
@pedroigor Assigning to you to doublecheck as it is related to user profile.

It looks like a regression, but at the same time it is related only to preview user-profile feature...

**Comment by cuongpham2110** [comment]
I meet same issue

**Comment by angusjfw** [comment]
We are also finding this issue and we do not have any preview features enabled

**Comment by erdebee** [comment]
A bug corrupting user data is very disturbing! Can this issue be given highest priority?

**Comment by guilhermebferreira** [comment]
@erdebee  my workaround for that, was to give the email as well when updating something else
not great, but I'm not facing the issue for now

**Comment by robvdlv** [comment]
Would also love to see this prioritised.
Thanks @guilhermebferreira for sharing your workaround.

**Comment by mpontoizeau** [comment]
+1

**Comment by restray** [comment]
+1

**Comment by pedroigor** [comment]
Working on it ...

**Comment by robvdlv** [comment]
@pedroigor see this branch I created for a failing test that proofs the bug: https://github.com/keycloak/keycloak/compare/main...robvdlv:keycloak:fix-update-user-attributes-leaves-user-email-unaffected-21751

**Comment by romrom21** [comment]
The bug is back on Keycloak 24.0.1
When you update an attribute user email, first name and last name are cleared

**Comment by fjf2002** [comment]
> The bug is back on Keycloak 24.0.1
> When you update an attribute user email, first name and last name are cleared

Yeah, I can confirm firstname and lastname get removed

**Comment by cahidaydin** [comment]
I can also confirm that this issue is still active on 24.0.1

**Comment by ivankravets** [comment]
@pedroigor , could you reopen this issue?

**Comment by lukas1505** [comment]
I tested it with Version 24.0.5. This also happens to me. I am getting following result with the api before changing some attributes:
```
    {
        "id": "1ac60157-84ce-4a9b-948f-8d2ce1eb72a5",
        "username": "test3",
        "firstName": "hans",
        "lastName": "peter",
        "email": "test@localhost",
        "emailVerified": false,
        "createdTimestamp": 1719424671532,
        "enabled": true,
        "totp": false,
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    }
```  
After changing some attributes the User looks like that:
```
{
        "id": "1ac60157-84ce-4a9b-948f-8d2ce1eb72a5",
        "username": "test3",
        "emailVerified": false,
        "attributes": {
            "software": [
                " openssh",
                "linux_kernel"
            ]
        },
        "createdTimestamp": 1719424671532,
        "enabled": true,
        "totp": false,
        "disableableCredentialTypes": [],
        "requiredActions": [],
        "notBefore": 0,
        "access": {
            "manageGroupMembership": true,
            "view": true,
            "mapRoles": true,
            "impersonate": true,
            "manage": true
        }
    }
```

**Comment by ramin-n** [comment]
> Working on it ...

The issue exists on 26.3.3
In #39411, the bot has replayed: "This is not considered a valid issue"!
and you mentioned that: "Keycloak does not support PATCH operations"!
Would you agree that this situation is at least somewhat abnormal?
It’s reasonable to expect that setting a simple user attribute shouldn’t involve so much friction. Many developers, myself included, feel the same.

**Comment by lmignon** [comment]
The issue still exists on 26.4.7 😢
