### ISSUE TITLE
Cannot use namespace 'Keycloak' as a type

### ISSUE THREAD

**Issue by ramseyfeng** [keycloak/keycloak#21767]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/api

### Describe the bug

We are using vue2 + typescript(4.4.4),
and we are running into the below issue:

_**Cannot use namespace 'Keycloak' as a type**_

If we change the import to use the deprecated one:
`import {KeycloakInstance} from 'keycloak-js';`
everything works fine, but there is a deprecated warning

If we change to the suggested import way:
`import Keycloak from 'keycloak-js'`

There will be typescript error, how can we handle this issue?

<img width="895" alt="image" src="https://github.com/keycloak/keycloak/assets/2835062/714af6e0-e6cb-44d6-9c2b-19c36cc29898">

### Version

21.1.1

### Expected behavior

We can import the Keycloak will no error and warning

### Actual behavior

We import the Keycloak with TS error, or import KeycloakInstance with deprecated warning

### How to Reproduce?

see uploaded picture

**Comment by edewit** [comment]
we use it like this:
https://github.com/keycloak/keycloak/blob/228da0e29a70f60ecf44ccfe762382f7fdda977d/js/apps/admin-ui/src/keycloak.ts#L1

**Comment by jonkoops** [comment]
There must be something wrong with your setup, I am unable to [reproduce this](https://stackblitz.com/edit/typescript-xdqrzt?file=index.ts&view=editor).  I'd recommend clearing out your `node_modules` and ensure you have the latest version of Keycloak JS listed in your package file.

**Comment by ramseyfeng** [comment]
Yes, you are right! something wrong in other setup caused the issue. Thanks!
