### ISSUE TITLE
List reload button for admin panel

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#21771]
### Description

Right now to reload the list of users we have two ways:

- Either reload the entire application, which destroys the notion of SPA
- Or change between menu items from the left and come back to the list of users

A good UX could be to have a **reload** button, with a refresh icon for example.

**Comment by jonkoops** [comment]
> Either reload the entire application, which destroys the notion of SPA

It does not, a SPA is still a web page, web pages can always be refreshed by the user.

> A good UX could be to have a reload button, with a refresh icon for example.

This is something we could add, but please provide some motivation (as outlined in the issue template), as to why this would be useful. Is this based on an actual use-case you have, or do you just 'feel' is should be that way?

**Comment by Nefcanto** [comment]
@jonkoops Thank you for the quick response. A SPA is a bunch of HTML templates, and the data is fetched via an API. The HTML won't change, but the data would. So, now consider this scenario from our real experience.

I tell a friend of mine to go and register, and then I want to give him a role. I already have the user list open, and he registers. Data is changed and I want to see the new list. What should I do? I should reload the entire page. But it makes sense to just reload the current list of users.

While this need might seem trivial, there are tons of other examples that I can give you outside Keycloak.

Consider a help desk technician who needs to refresh the data constantly (I know push also works, but many applications do not have push). They need to refresh almost every minute to see if new issues are raised or not. In a SPA, this defies the very first goal of the SPA, which is speed and partial page reload. They can have a simple refresh icon on the top of their issue list, and only click that.

Other real-world examples are: List of comments for public affairs employee, list of orders for the sales department, etc.

Also I can refer you to one example of refresh/reload button from [React Admin](https://marmelab.com/react-admin-helpdesk/#/tickets).

**Comment by jonkoops** [comment]
If anything this applies for most if not all of the views we have in the Admin Console. I think this feature does make sense, but let's do it everywhere, properly and consistently.

@xianli123 as our residential UX expert, can you weigh in on this discussion?

**Comment by xianli123** [comment]
Thanks @jonkoops @Nefcanto, Refreshing data is a good point, especially for a complex admin console.

> If anything this applies for most if not all of the views we have in the Admin Console. 

Yes, I agree. I will research the console and see what data view should have the refreshing function. The users' list is definitely the first to need that. I will consider a uniform way to add a refresh function for all the views that should have that function. Keep in touch.

**Comment by Nefcanto** [comment]
@xianli123 thank you so much. I'm sure the community would benefit from it.

**Comment by xianli123** [comment]
My pleasure! @jonkoops @Nefcanto . I will make some screens. Keep in touch.

**Comment by xianli123** [comment]
Hi @Nefcanto , I have a question about your use case. Generally speaking, how long it will take to refresh the user list? 

I came up with a design for this issue as shown below. I added a refresh button in the toolbar.

> <img width="968" alt="Screenshot 2023-07-21 at 16 04 38" src="https://github.com/keycloak/keycloak/assets/53931519/81b09e04-862d-4835-91ee-6ccbf48f39f6">

In my opinion, the response is quick when users hit the refresh button in most cases. It's very good for users. But sometimes, it may take a relatively long time to get the latest data. Based on this situation, I added an alert under the toolbar, as shown in the screenshot below. In addition, if users don't want to wait for a long time, they can stop the refresh process. This is why I have a question about the refresh time. If response times are always fast, maybe we don't need to add this alert. What do you think? Thanks. Looking forward to your reply.

> <img width="958" alt="Screenshot 2023-07-21 at 16 12 37" src="https://github.com/keycloak/keycloak/assets/53931519/07a1d1e0-51c6-4edf-bc06-245553f552da">

**Comment by ahus1** [comment]
> If response times are always fast, maybe we don't need to add this alert. 

I've seen application which would show this message only when the response is taking longer than than an instant (say, after 500ms), which would prevent flickering if the response is really fast. What are UX thoughts on that, xianli123?

**Comment by xianli123** [comment]
@ahus1 Thanks. It is a good idea. We could set up a max response time. Only when the refresh time is longer than the response time, this kind of alert occurs. In addition, I think all Redhat products should have the same interactions related to the refresh function, so let me check other products or teams. And then I will make a design ASAP.

**Comment by Nefcanto** [comment]
@xianli123 Thank you for that design. It's a good design. The refresh button is fantastic. Yet I have not seen or experienced the alert. I've seen it in critical use cases. For example:

- Sending an email should be done, or if it's taking long, the provider would usually show a message
- When I'm trying to do an online payment transaction, then it should be ACIDic, and if it takes long, it shows a message
- ...

Yet for a list, and the read operation it doesn't add value. It's not necessary. It will be a pessimistic UI update. We internally change the UI of that refresh button to progress as soon as the user clicks it, and we return it to normal when the data is loaded. And if for any reason it takes long to load data, then the user showing an alert to stop the task won't add any value. The user wants to see the latest updated data, so he should wait. We have no other way for it.

**Comment by jonkoops** [comment]
@xianli123 I think we can put the loading state in the button itself, PatternFly already offers a [progress indicator](https://www.patternfly.org/v4/components/button/) for that.

**Comment by xianli123** [comment]
Thanks @Nefcanto  @ahus1 @jonkoops .

> I think we can put the loading state in the button itself, PatternFly already offers a [progress indicator](https://www.patternfly.org/v4/components/button/) for that.

It looks great. It's good to have the [progress indicator](https://www.patternfly.org/v4/components/button/). 


Based on the discussion above, we can keep the refresh button in the toolbar as shown below. 

><img width="967" alt="Screenshot 2023-07-24 at 14 10 25" src="https://github.com/keycloak/keycloak/assets/53931519/159e97c8-41fa-4974-8e1e-8cfc908799ec">


After clicking the "Reload" button, the button will change to the "in progress" status. Users can stop reloading by clicking the button.

> <img width="967" alt="Screenshot 2023-07-24 at 14 12 12" src="https://github.com/keycloak/keycloak/assets/53931519/2a2fed29-6441-4aa3-addb-31bbbdf5ed51">


When the latest data is refreshed successfully, the notice will appear at the top.

> <img width="969" alt="Screenshot 2023-07-24 at 14 13 31" src="https://github.com/keycloak/keycloak/assets/53931519/32e98077-5ad4-44d1-bd43-4f85f007c795">

What do you think?

**Comment by ahus1** [comment]
Nice, I like it. This would be my preferred solution with the button changing. Not sure about the green notification - this might be a bit too much as I would expect it only after I have changed something.

**Comment by Nefcanto** [comment]
@xianli123 good UX thanks. I agree with @ahus1 the green box is not necessary as the change in data would be good feedback to the user that it's loaded. However, in case it's failed, I suggest showing an error.

**Comment by xianli123** [comment]
@Nefcanto @ahus1 Thanks. Good idea. We can remove the green box and add an error alert if it loads fail. If it fails, the process terminates and the button will return to the original status. It will look like the screenshot below. 
<img width="956" alt="Screenshot 2023-07-24 at 16 49 30" src="https://github.com/keycloak/keycloak/assets/53931519/15585e80-f85e-4e84-b7f4-65b9fcb18b3f">

**Comment by Nefcanto** [comment]
@xianli123 I guess it's a perfect solution now.

**Comment by jonkoops** [comment]
I think that the success message is probably not necessary, it should be pretty self explanatory when it completes, but we can certainly add it.

Agree that we should have an error message when something fails, but it might fall back to our default error handler instead.

**Comment by xianli123** [comment]
Hi @jonkoops, That makes sense to use Keycloak default error handler. Could we start developing this feature?

**Comment by xianli123** [comment]
@jonkoops Ok! I will provide a detailed design and leave it in the comments here.

**Comment by jonkoops** [comment]
Just to clarify, which screens should have this 'Reload' button?

**Comment by xianli123** [comment]
Hi @jonkoops I reviewed the console. In addition to the user list, I think the Client list and Sessions list could have this "Reload" button. The Event list already has a "refresh" button, so we can make the "Refresh" button consistent with the list of users. What do you think?

**Comment by xianli123** [comment]
Here is the [design](https://www.figma.com/proto/YkPV0knnrWo7crrGrWGfNc/Keycloak-Issues?page-id=209%3A173&type=design&node-id=209-174&viewport=338%2C195%2C0.08&t=mTMDu8NNCs5ISfSs-1&scaling=scale-down&mode=design), please take a look and feel free to let me know if there any new requirments.

**Comment by jonkoops** [comment]
Problem is that we don't have the header and the table in the same component, so it will require a lot of refactoring to do it as such. Because of that I want to start small, we can always decide to add more views as we go.

@xianli123 can you tell me which views should have this button?

**Comment by xianli123** [comment]
Hi @jonkoops Client list, User list and Session list preferably have this reload button. 

- As for client list, some users may use the "Initial access token" to create clients. This kind of clients is created outside of the Keycloak console. Adding a reload button helps users get to such clients.
- Session records the interactions between users and clients. When admin focus on the session page, the interaction between users and clients may be constantly changing. So it makes sense to add a reload button.
- With regard to the User list, we have discussed above.

What do you think? Thanks!

**Comment by jonkoops** [comment]
Thanks, that should be enough information to go on. I'll try to get to this issue soon, once I have my backlog cleared out.

**Comment by xianli123** [comment]
My pleasure. Please feel free to contact me if there are any questions.

**Comment by nsgeeta12** [comment]
@xianli123 : Hi, May I know the approach used to implement the refresh button on toolbar.

**Comment by jonkoops** [comment]
I am removing my assignment as I realistically don't have time to work on this right now. I've added the appropriate labels so that anyone from the community who wants to can volunteer.

**Comment by xianli123** [comment]
Hi @nsgeeta12 As for the design, please refer to [the design link](https://www.figma.com/proto/YkPV0knnrWo7crrGrWGfNc/Keycloak-Issues?page-id=209%3A173&type=design&node-id=209-174&viewport=338%2C195%2C0.08&t=mTMDu8NNCs5ISfSs-1&scaling=scale-down). The refresh button is a standard PatternFly's component. Here is [the component link](https://www.patternfly.org/components/button#progress-indicators) FYI. Are these what you are looking for?

**Comment by nsgeeta12** [comment]
Hi All, Hi @xianli123, 

I am newbie to React and Keycloak v21 admin-ui code base.
With older version of Keycloak, we had the customization implemented with angularJs and html, javascript.
I need help with how the custom theme structure should look like. 
how can we extend the admin ui to include the button on the Users Section component i.e. beside Add User button on UI. Upon click on Export button the list of users should be saved to file.

Thanks!

**Comment by jonkoops** [comment]
@nsgeeta12 this issue is not the place to ask for this kind of support, please keep things on topic. If you are looking for help I would recommend [starting a discussion](https://github.com/keycloak/keycloak/discussions).

**Comment by thecooldrop** [comment]
Hello @jonkoops  I would like to give this a stab, but note that it may take a while as I am a just getting accustomed to front-end work and Keycloak codebase. If that is acceptable, I would be grateful to be assigned to this issue.

**Comment by jonkoops** [comment]
Perfect, I'll assign this this you @thecooldrop :+1: We're in no rush, so take your time.

**Comment by jonkoops** [comment]
@thecooldrop are you still interested in landing this? If not I will remove your assignment so we can get someone on it.

**Comment by thecooldrop** [comment]
I apologize. It has been quite a busy period for me, and both React and Quarkus are new technologies for me. I will not be able to complete this in any reasonable time as far as I see. Feel free to assign this task to someone else. If at later time when I learn React this task is still available I will pick it up.

**Comment by jonkoops** [comment]
No problem @thecooldrop, thanks for getting back to me. I'll open up the assignment so folks can pick up this issue.
