### ISSUE TITLE
Missing transition from javax.* to jakarta.* in keycloak-undertow-adapter in 21.1 and above

### ISSUE THREAD

**Issue by akley** [keycloak/keycloak#21786]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/jee

### Describe the bug

The transition from Java EE to Jakarta EE has apparently not been done for keycloak-undertow-adapter lib.
In class KeycloakServletExtension are still imports to javax.servlet.ServletContext.

This leads to runtime problems with e.g. resteasy-undertow lib and its dependencies since version 6.1 and later.

### Version

22

### Expected behavior

Right imports for the own dependencies as in Release announcement described: https://www.keycloak.org/2023/07/keycloak-2200-released

### Actual behavior

The imports are wrong

### How to Reproduce?

check the code base

### Anything else?

I don't know if this is related, but I get an error when I start my resteasy application in this context:
RestEasy 6.2.0 Final
Keycloak-undertow-adapter 22.0.1

It seems to be not fixed with kc and related libs in 22.0.1

Exception in thread "main" java.lang.AbstractMethodError: 
Receiver class org.keycloak.adapters.undertow.KeycloakServletExtension does not define or inherit an implementation of the resolved method 'abstract void handleDeployment(io.undertow.servlet.api.DeploymentInfo, jakarta.servlet.ServletContext)' of interface io.undertow.servlet.ServletExtension.
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:282)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:156)
....

**Comment by vmuzikar** [comment]
@akley Thanks for the report. The adapter was not migrated in order to remain backwards compatible. AFAIK, Jakarta EE version is not planned.

CC @keycloak/core

**Comment by ahus1** [comment]
@akley - the release announcement states that Keycloak has been migrated to Jakarta EE. Some of the client adapters have been migrated as well to the extent that they were necessary to run our internal test suites. 

There have been several other announcements that Keycloak is deprecating its own adapters, and recommends to use the OIDC adapters present in the different frameworks. See https://www.keycloak.org/2023/03/adapter-deprecation-update.html for the post and a list of possible alternatives. If there are enough people interested, there could be a community-maintained adapter as a self-contained project in https://github.com/keycloak-extensions, but it would require someone (better a group of people) to step up for this task. If a PR for the main repository to upgrade the adapter will be accepted I cannot say, this is for the core team to decide.

Please let us know if one of the alternatives in the blog post work for you, and any obstacles you might be facing.
