### ISSUE TITLE
Warnings about quarkus.http.ssl.certificate.file and quarkus.http.ssl.certificate.key-file on startup

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#21801]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

When starting Quarkus with a TLS certificate, there are two warnings logged at the console: 

> The 'quarkus.http.ssl.certificate.key-file' config property is deprecated and should not be used anymore
The 'quarkus.http.ssl.certificate.file' config property is deprecated and should not be used anymore

Looking at the issue that change this, this is was part of Quarkus 2, so it is quite old.

### Version

main

### Expected behavior

There should be no warning during startup. Possibly Keycloak should handle multiple server names as Quarkus does, see https://github.com/quarkusio/quarkus/pull/17036

### Actual behavior

There are warnings at the start up that confuse/distract/unsettle the user. A user can specify only one server certificate.

### How to Reproduce?

Start Keycloak with a TLS certificate

### Anything else?

There could be multiple steps here, which could be split: 

1. Get rid of the warning by using the new property
2. Support multiple TLS certificates (which might require code and documentation updates)

At least the first part (getting rid of the warning) might be something to backport to KC22

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the repo, sounds really like something we should fix in a 22 micro.

@mabartos Could you please look into it when you get a chance?

**Comment by mabartos** [comment]
@vmuzikar @ahus1 Totally agree to backport the removal of these warnings and create a separate issue for multiple certs. I'll look at it.

**Comment by mabartos** [comment]
Created follow-up task for handling multiple certificates: https://github.com/keycloak/keycloak/issues/21871
