### ISSUE TITLE
Allow "--verbose" option when running Keycloak via the Operator

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#21802]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

Keycloak might fail with an exception. It then prints the following text:

> For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

AFAIK there is no way to pass that option via the Operator. Due to the lack of that option, I don't see the stack trace in the log.

### Version

main

### Expected behavior

I wonder if "--verbose" it should be the default when starting Keycloak via the Operator. Which leads to the question why not enabling it by default from the CLI.

### Actual behavior

Missing information to debug an issue.

### How to Reproduce?

Inject any exception that prevents Keycloak from starting.

**Comment by vmuzikar** [comment]
A question is, should we perhaps set `--verbose` by default in Operator deployments? It doesn't increase the log level, it just prints full stack trace. Which is what you expect when looking into pod logs.

Related #21816 

CC @keycloak/cloud-native

**Comment by mabartos** [comment]
@vmuzikar @ahus1 +1 to set `--verbose` by default for Operator; I don't see any severe implications or restrictions which could bring it.

**Comment by pgodowski** [comment]
> @vmuzikar @ahus1 +1 to set `--verbose` by default for Operator; I don't see any severe implications or restrictions which could bring it.

Would this increase the number of logs emitted? If so, would the ephemeral storage be potentially exhausted?

**Comment by vmuzikar** [comment]
@pgodowski This affects only possible exceptions, doesn't affect log level.

**Comment by docholiday** [comment]
Not sure if this was fixed for some time or not, but I'm now on keycloak 22.0.5 and still have the same problem.
Keycloak runs into an error at startup and prints
` ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
`

But when you try to start it with --verbose
bin/kc.sh start --verbose

you get the error

`Unknown option: '--verbose'
Try 'kc.sh start --help' for more information on the available options.
`

**Comment by shawkins** [comment]
@docholiday automatically adding --verbose was done for release 23.  

> Unknown option: '--verbose' Try 'kc.sh start --help' for more information on the available options.

The verbose option is not specific to the command, it's a general option.  So the expectation is for those parameters to be reversed: --verbose start

#13250 covers making --verbose more user friendly.

**Comment by docholiday** [comment]
@shawkins Thanks a lot for the quick reply!
--verbose start worked :-)
