### ISSUE TITLE
ConditionalOtpFormAuthenticator unsafe setup OTP flow

### ISSUE THREAD

**Issue by KlausNie** [keycloak/keycloak#21837]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Using the `ConditionalOtpFormAuthenticator` to conditionally "require the OTP on authentication", also makes the "setup of the OTP" conditional.

While I understand that some might use this a way to handily "skip" OTP because it is a nuisance, setting up the OTP should always be required (if OTP is required for your use-case) by default.

Consider this scenario:
1. user does not want to provide OTP, while in certain IP range
2. Keycloak is set up to not require OTP while in certain IP range
3. The user will not ever set up OTP, because he's always in the IP range
4. 3rd party gets access to the credentials
5. Logs into the account: surprise! The attacker even gets to set up a fresh OTP

The whole point of an OTP is circumvented with this flow.

While I'm not going to argue that someone still might want this, I disagree, that this should be the default solution.

The default should always be:
1. Set up OTP once
2. Skip it whenever your use-case desires

### Version

21.1.1

### Expected behavior

The setup of the OTP is, by default, always required on first login.

### Actual behavior

If the conditions to "skip" the OTP are met on the first login, the "setup of the OTP" is also not required.

### How to Reproduce?

With any Keycloak version after 2016.

1. Set up an authentication flow that includes the `ConditionalOtpFormAuthenticator`
2. Configure it to "skip" the OTP, does not matter which setting
3. Create a new user
4. (optional) Set "Configure OTP" for the "Required user actions" (won't do you any good)
5. Log in as that user

Result: you won't have to set up OTP

### Anything else?

The `ConditionalOtpFormAuthenticator` is not used in any default authentication flow of keycloak.

There seems to be a strange bug, where deleting an authentication flow, does not delete all of its sub-flows and/or configurations. I could not yet nail down the reason for that. I noticed that for some `ConditionalOtpFormAuthenticator` configurations.

**Comment by mposolda** [comment]
I am adding to Backlog as I think that Keycloak team won't have time to look at this in the near future. Anyone is welcome to contribute the fix for this if it is confirmed that this is valid issue. The `ConditionalOtpFormAuthenticator` does not have much priority as in general, we have conditions now in the authenticationFlow and it might be better to use individual conditions together with `OTPFormAuthenticator` instead of tweaking `ConditionalOtpFormAuthenticator`.
