### ISSUE TITLE
How to set hibernate.dialect in persistence.xml per environment?

### ISSUE THREAD

**Issue by dominiktopp** [keycloak/keycloak#21843]
### Description

We are currently migrating our user storage provider to Keycloak 22.0.0. The provider uses two additional persistence units.
The database settings are added to quarkus.properties:
```
quarkus.datasource.users-a.db-kind=h2
quarkus.datasource.users-a.jdbc.url=jdbc:h2:tcp://localhost:6114/mem:testdb
quarkus.datasource.users-a.username=dbusername
quarkus.datasource.users-a.password=dbpassword
```
(and the same for user-b with another port in the url)

The persistence units are defined in persistence.xml. The keycloak-quickstart user-storage-jpa and @nicolabeghin (https://github.com/nicolabeghin/keycloak-multiple-ds-user-storage) are also using this approach.
The problem is the hibernate.dialect property in presistence.xml: we use h2 for local development and in the first two test environments but Azure SQL Server in other environments. Since persistence.xml is packaged into our jar we cannot change persistence.xml by environment.

Omitting the dialect in persistence.xml leads to the error during quarkus build

> ERROR: Unexpected error when starting the server in (development) mode
ERROR: Failed to start quarkus
ERROR: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'javax.persistence.jdbc.url', 'hibernate.connection.url', or 'hibernate.dialect')
ERROR: Unable to determine Dialect without JDBC metadata (please set 'javax.persistence.jdbc.url', 'hibernate.connection.url', or 'hibernate.dialect')

How can we set the dialect in each environment or how can we help Hibernate to detect the dialect by itself?

**Comment by vmuzikar** [comment]
@dominiktopp Hello, could you please open a [discussion](https://github.com/keycloak/keycloak/discussions) about it? If I understand correctly, this is neither an RFE nor a bug report, hence a discussion is the right place to get enough visibility. Thank you.

**Comment by dominiktopp** [comment]
https://github.com/keycloak/keycloak/discussions/21876
