### ISSUE TITLE
Redirect Uri after reauthentication ends with double slash

### ISSUE THREAD

**Issue by codemasterover9000** [keycloak/keycloak#21873]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

After my applications session times out it tries to reauthenticate me, which succeeds, but it then redirects me to an url ending with '//' instead of '/' (which gives a 404 page). This incorrect redirect does not occur when logging in. A workaround is to append `?redirectTo=/` to the Master SAML Processing URL in keycloak.

### Version

22.0.1

### Expected behavior

Get redirected to http://localhost:8080/ after reauthentication

### Actual behavior

I get redirected to http://localhost:8080//

### How to Reproduce?

Testcode to reproduce the issue
```
public static void main(String[] args)
{
    MockHttpServletRequest request = new MockHttpServletRequest();
    request.setServerName("localhost:8080");
    request.setRequestURI("/saml");
    request.getSession(true);
    MockHttpServletResponse response = new MockHttpServletResponse();
    FilterSamlSessionStore filterSamlSessionStore =
            new FilterSamlSessionStore(request, new ServletHttpFacade(request, response), 0, null, null);

    System.out.println(filterSamlSessionStore.getRedirectUri()); // http://localhost:8080//
}
```

### Anything else?

The original code (re)authenticates via an AbstractAuthenticationProcessingFilter:
```
 org.keycloak.adapters.saml.SamlUtil.getRedirectTo(SamlUtil.java:86)
 org.keycloak.adapters.saml.servlet.FilterSamlSessionStore.getRedirectUri(FilterSamlSessionStore.java:171)
 org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.handleLoginResponse(AbstractSamlAuthenticationHandler.java:491)
 org.keycloak.adapters.saml.profile.AbstractSamlAuthenticationHandler.handleSamlResponse(AbstractSamlAuthenticationHandler.java:252)
 org.keycloak.adapters.saml.profile.webbrowsersso.SamlEndpoint.handle(SamlEndpoint.java:44)
 org.keycloak.adapters.saml.SamlAuthenticator.authenticate(SamlAuthenticator.java:48)
 org.keycloak.adapters.saml.servlet.SamlFilter.doFilter(SamlFilter.java:167)
 xx.xxx.xxxx.filters.saml.xxxSAMLFilter.attemptAuthentication(xxxSAMLFilter.java:47)
```

**Comment by mposolda** [comment]
I am adding to Backlog as SAML Java adapters are not a priority and Keycloak team won't look at this in the near future. Anyone is welcome to improve/fix on this if needed, but note that Keycloak adapters are not maintained, so the option might be to use different SAML client adapter.

**Comment by mposolda** [comment]
Yes, the SAML filter adapter is not being deprecated in Keycloak, but at the same time, it is not a priority for the Keycloak team to further improve it or fix the issues in it. If you figure this issue and send the PR with the fix, we will be happy to accept your PR with the fix. But it's likely not a priority for Keycloak team in the near future to work on it directly.
