### ISSUE TITLE
OIDC: loosing query parameter when utilizing redirect URI rewrite 

### ISSUE THREAD

**Issue by ChristianAnke** [keycloak/keycloak#21880]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

When using the spring configurations `keycloak.redirect-rewrite-rules`  option, then the redirect_uri parameter value looses the query parameter which the original URL had.

It seems that `org.keycloak.adapters.OAuthRequestAuthenticator.rewrittenRedirectUri()` is not adding the query portion from the `originalUri` to the rewritten URI. Something like 

```
if (Objects.nonNull(url.getQuery())) {
	redirectUriBuilder.append("?").append(url.getQuery());
}
```
could help there.

### Version

20.0.5

### Expected behavior

Any query parameters attached to the original requested URI is preseved when rewriting it and using it as the value of the redirect_uri parameter. 

### Actual behavior

The value of the redirect_uri parameter does not contain the query parameters of the originally requested URI.

### How to Reproduce?

Configure the `keycloak.redirect-rewrite-rules` in a spring boot project which is utilizing the Keycloak client library to authenticate requests.

Access the authentication entry point with an attached query parameter so that the login process will use this as the redirect_uri parameters value.

### Anything else?

There seems to be a path which was supposed to fix the issue: https://github.com/keycloak/keycloak/pull/7797

**Comment by mposolda** [comment]
I am adding to Backlog as Spring/Java adapters are deprecated and Keycloak team won't look at this in the near future. Anyone is welcome to improve/fix on this if needed, but note that Keycloak adapters are not maintained, so the option might be to use different OIDC provider.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
