### ISSUE TITLE
Eliminate the layout shift on forms related to the Login

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#21901]
### Description

Right now when the user goes to the login page, especially if he uses a password manager (like Dashlane or LastPass) which is set to auto-login, in case of a wrong username or password the layout shifts.

It's because error messages are inserted into the UI, pushing elements below them.

This is not a good UX, especially when auto-login is configured. Or even when the user has multiple logins and clicks the **Login** button with the default filled form which might not be correct.

### Motivation

Layout shift is not a good UX as described by [web.dev](https://web.dev/cls/). And since Keycloak is a good product, fixing this UX can help it become even better.

**Comment by Nefcanto** [comment]
https://github.com/keycloak/keycloak/assets/12782347/a8e54683-c94e-4920-819c-4556be6539e1


Our solution for this in our own products is to keep the error space in place. This means fields would be farther apart, but our tests show that it's acceptable by users (at least for us it was so).

**Comment by jonkoops** [comment]
I don't think that there is much we can do about this, as we are using [PatternFly](https://www.patternfly.org/) as our component library. It would likely have to be fixed there, and eventually trickle down to us. I'd recommend opening up an issue on [their repository](https://github.com/patternfly/patternfly), and link back here.

**Comment by ssilvert** [comment]
@Nefcanto thanks for pinging the PatterFly team.  I'm going to close this issue for now.  

Also FYI, we will be upgrading everything to PatternFly 5 when it comes out.
