### ISSUE TITLE
Custom provider is not configured in version 22.0.1

### ISSUE THREAD

**Issue by tania2** [keycloak/keycloak#21905]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I have implemented a custom provider using keycloak version 21.1.2 and i am trying to upgrade to the latest version 22.0.1, but the custom provider that was successfully working in 21.1.2 is no longer started. The custom provider is using LegacyUserCredentialManager, since it is a custom provider for an existing database. Custom provider is placed in /providers folder and dependency libraries are placed in the jar with shadowJar. 
Dependency libraries depends on javax.*. Should the dependency libraries depend only on jakarta.*?

### Version

22.0.1

### Expected behavior

Custom provider should be configured properly, as it was in 21.1.2

### Actual behavior

Custom provider is not configured due to null dataSource. Datasource is a MysqlXADataSource.

### How to Reproduce?

A custom provider configuring a MysqlXADataSource and try to create a user. datasource won't be configured, it will be null

**Comment by mposolda** [comment]
Yes, you should update your providers to use `jakarta` instead of `javax`. See migration guide for the details: https://www.keycloak.org/docs/latest/upgrading/index.html#transition-from-java-ee-to-jakarta-ee . I am closing as this is expected behaviour

**Comment by tania2** [comment]
@mposolda Thank you very much for your response!!!
