### ISSUE TITLE
Using DPoP token type in the access-token and as token_type in introspection response

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#21919]
### Description

This is follow-up on https://github.com/keycloak/keycloak/issues/21200

Currently accessToken with DPoP thumbprint still have type `Bearer` in the initial DPoP Keycloak PR. IMO it will makes more sense if the token type is `DPoP`. This is not explicitly mentioned in the specification, however it is mentioned that:
- Whole AccessTokenResponse should have token-type `DPoP`, which we do.
- The requests to resource-server also use `Authorization: DPoP ...` instead of `Authorization: Bearer ...` 
In general, the `DPoP` specification prescribes to use type `DPoP` in those places, so it would makes sense to me to use the same type in the access-token itself.

There is also one related point in the specification related to introspection endpoint https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-11#section-6.2 :
```
If the token_type member is included in the introspection response, it MUST contain the value DPoP
```
It seems that we're currently not doing it and not adding `token_type` to the response. Maybe with the change above, we can start adding `token_type` (maybe in `AccessTokenIntrospectionProvider`, which would be used for both `Bearer` and `DPoP` tokens) and add `token_type` to the response, which would be retrieved simply from `token.getType()` (and hence would be `DPoP` for the `DPoP` based tokens).

**Comment by tnorimat** [comment]
@mposolda The current keycloak does not return `token_type` parameter in token introspection response. I looked up `TokenMetadataRepresentation` and `AccessToken`, but they does not include `token_type` claim.

`"access_token"` in test methods of `DPoPTest` is used for Token Introspection's request parameter `token_type_hint`. According to [RFC 7662](https://datatracker.ietf.org/doc/html/rfc7662#section-2.1) and [RFC 7009](https://datatracker.ietf.org/doc/html/rfc7009#section-2.1), `access_token` or `refresh_token` can be used for the `token_type_hint`.

Could you check that point?

**Comment by mposolda** [comment]
@tnorimat This is good point. Maybe now when we're adding `DPoP`, it is also good time to start adding `token_type` claim from the introspection response to be able to differentiate between `Bearer` and `DPoP` tokens? I've slightly updated the last paragraph of the description. Does it makes sense to you?

**Comment by tnorimat** [comment]
@mposolda I see. Coud we do the followings?
- Adding a `token_type` parameter to a response of Token Introspect
- If a token is DPoP bound, the `token_type` parameter's value is `"DPoP"`
- If a token is non-DPoP bound, the `token_type` parameter's value is `"Bearer"`
If these are OK, I would like to work on them.

**Comment by mposolda** [comment]
@tnorimat Sounds good! Thanks

**Comment by tnorimat** [comment]
@mposolda Thank you. I will work on this issue.
