### ISSUE TITLE
Adjustements to the behaviour of dpop_bound_access_tokens switch

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#21920]
### Description

This is follow-up on https://github.com/keycloak/keycloak/issues/21200

. The specification mentions:
```
dpop_bound_access_tokens
    Boolean value specifying whether the client always uses DPoP for token requests. If omitted, the default value is false.

If true, the authorization server MUST reject token requests from this client that do not contain the DPoP header.
```
My understanding is that:
- If `dpop_bound_access_tokens` is true, then DPoP is mandatory and Keycloak should reject token-request without `DPoP` header. It seems we're already doing that correctly in the initial DPoP PR

- If `dpop_bound_access_tokens` is false, then DPoP is not mandatory per the specification. However my understanding is, that `DPoP` request should be still possible for this client. IMO it is just not mandatory for this client, but in case that `DPoP` header is still included in the token-request, Keycloak may still verify `DPoP` header if present and attach to token thumbprint. Do you see it same way?

**Comment by tnorimat** [comment]
@mposolda Yes, I will modify keycloak to do as follows:
- Regardless of a value of `dpop_bound_access_tokens`, endpoints (token endpoint for token request and refresh request, logout endpoint for logout request) of keycloak verifies a DPoP proof if it is appended in a http request header.
- Regardless of a value of `dpop_bound_access_tokens`, endpoint (token endpoint for token request and refresh request) keycloak binds an access token and refresh token with the public part of a clients key pair for DPoP proof if it is appended in a http request header
