### ISSUE TITLE
Bring back the p11-kit package in the docker image

### ISSUE THREAD

**Issue by Daryes** [keycloak/keycloak#21936]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dependencies

### Describe the bug

Package p11-kit has been removed with v21, it is required by the update-ca-trust command to regenerate the ca-bundle and the java cacerts files
Which can allow to generate a custom cacert containing both default and custom certificates using only the KC docker image, without the need to install java on looking for a server or image with java installed.

Commit ref : https://github.com/keycloak/keycloak/blame/0ddef5dda884aa5d56f13ee8d1f573e935c33dcc/quarkus/container/ubi-null.sh#L33

### Version

21

### Expected behavior

No error.

### Actual behavior

```
$ /usr/bin/update-ca-trust
/usr/bin/update-ca-trust: line 17: /usr/bin/p11-kit: No such file or directory
/usr/bin/update-ca-trust: line 18: /usr/bin/p11-kit: No such file or directory
/usr/bin/update-ca-trust: line 19: /usr/bin/p11-kit: No such file or directory
/usr/bin/update-ca-trust: line 20: /usr/bin/p11-kit: No such file or directory
/usr/bin/update-ca-trust: line 21: /usr/bin/p11-kit: No such file or directory
/usr/bin/update-ca-trust: line 22: /usr/bin/p11-kit: No such file or directory
```

### How to Reproduce?

Add custom certificates into /usr/share/pki/ca-trust-source/anchors/
then run these commands from the container or using `docker exec/run`  : 
```
update-ca-trust
/usr/bin/p11-kit extract --format=java-cacerts --filter=certificates --overwrite --purpose server-auth /usr/share/pki/ca-trust-source/anchors/cacerts.jks
```

### Anything else?

Practical usage with docker-compose : #21935

**Comment by DAHAG-ArisNourbakhsh** [comment]
The steps [here](https://www.keycloak.org/server/containers#_installing_additional_rpm_packages) are the now intended way to achieve this 
#16879 did that mostly to reduce the attack surface and you can read #17273 for a bit more of the reasoning behind this

**Comment by vmuzikar** [comment]
@Daryes Thanks for the report.

As @DAHAG-ArisNourbakhsh correctly pointed out, you can use any dependencies that you require during the build process of your custom image.
