### ISSUE TITLE
Unable to perform health checks with docker/podman

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#21941]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dependencies

### Describe the bug

There is no out of the box way to perform docker health checks.

Keycloak itself asks to use `curl`, but it is not available in the container. Adding it does make sense, also for other tasks.

But if it is considered "insecure" to add `curl`, `kc` or `kcadm` could easily offer a `ping` command, which does the same.

In any case, the situation is messy, as one can't just add curl through a docker compose right, when using podman, because podman-compose build is somewhat broken.

### Version

22.0.0

### Expected behavior

There should be an "out of the box" way to perform health checks.

### Actual behavior

There is not.

### How to Reproduce?

Try creating a health check.

**Comment by bodograumann** [comment]
Previously discussed here: https://github.com/keycloak/keycloak/issues/17438
The current suggestion is to add curl I guess:

```
FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y; dnf --installroot /mnt/rootfs clean all

FROM quay.io/keycloak/keycloak:22.0.1
COPY --from=ubi-micro-build /mnt/rootfs /
```

This just took **10 Minutes** to build!?! And it also seems to break something about database auth...

https://github.com/keycloak/keycloak/issues/17273#issuecomment-1456572972 gives an approach of doing a health-check without curl.
For this to work you also have to enable the `http-enabled` configuration, so keycloak listens for health checks on port 8080.
