### ISSUE TITLE
Pagination of groups works incorrectly

### ISSUE THREAD

**Issue by transducer** [keycloak/keycloak#21949]
### Before reporting an issue

- [X] I have searched existing issues
- [x] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

The pagination on the Groups tab in the Keycloak tab works incorrectly. Fewer groups than available are listed. For example,. when there are eight groups, the pagination only shows two:

![pagination](https://github.com/keycloak/keycloak/assets/5002921/b7d50d56-1e2e-4f3f-a908-5b9d6bf23468)

Also when clicking through the paginated list of 500 groups paginated by 50, you can visit much more than 10 paginated pages. Thus groups are shown double on every page.

### Version

22.0.1

### Expected behavior

- When there are eight groups and there is a 1-8 pagination I expect all eight groups.
- When there are 500 groups and I paginate by 50 I expect to be able to visit 10 pages, not more.

### Actual behavior

- Two groups are visible on a 1-8 pagination.
- I can visit roughly 25 pages of 50 groups when there are only 500 groups total.

### How to Reproduce?

1. Create eight top level groups
1. Give every top level group 50 subgroups
1. View pagination on main page (it will show fewer than eight groups)
1. Scroll through all groups of a subgroup (it will paginate wrongly, showing double entries on every page)

**Comment by ssilvert** [comment]
This PR probably fixes your problem.  
https://github.com/keycloak/keycloak/pull/21520

The author is out this week so it probably won't merged until he returns.  After that you can give it a try with the nightly build and see if it fixes your problem.  @transducer Will you be able to do that?

**Comment by transducer** [comment]
@ssilvert thanks for reply. I will check later then.

**Comment by transducer** [comment]
Thanks @edewit!
