### ISSUE TITLE
Case insensitive search for groups

### ISSUE THREAD

**Issue by transducer** [keycloak/keycloak#21950]
### Description

Searching for groups is case sensitive, even when "Exact search" is not toggled on. Would be great if this search was case insensitive.

<img width="464" alt="Screenshot 2023-07-25 at 12 49 08" src="https://github.com/keycloak/keycloak/assets/5002921/9d18bc6a-94b5-4ebe-b4c7-144dc05a700d">

### Motivation

Admin users usually don't know the chosen capitalization of group names, since searching is case sensitive this makes it difficult to find. 

As a workaround in the past they just used their browser's CTRL-f (which is not case sensitive) instead of the Keycloak search. But since Quarkus this is no longer possible. Groups are no longer all visible on one page due to the pagination of the groups. Users are forced to use the Keycloak search. It would be great if this had the same case insensitive behaviour as the browser's CTRL-f.

**Comment by MartaGolabek** [comment]
+1 for @transducer request

Our admin users would also love to have this feature!

**Comment by edewit** [comment]
Closing as this now seems to be the case
