### ISSUE TITLE
Configuring id providers is actually only "add"

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#21953]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

In the keycloak documentation is mentions the "configuration" of identity providers: https://www.keycloak.org/docs/latest/server_admin/#identity-provider-operations#configuring-a-keycloak-openid-connect-identity-provider

Like: 

> ## Configuring a GitHub identity provider
>  […]
> ```
> kcadm.sh create identity-provider/instances -r demorealm -s alias=github -s providerId=github -s enabled=true  -s 'config.useJwksUrl="true"' -s config.clientId=GITHUB_CLIENT_ID -s config.clientSecret=GITHUB_CLIENT_SECRET
> ```

However, trying to "configure" an existing provider results in an error.

### Version

22.0.0

### Expected behavior

It should **configure** the provider.

### Actual behavior

It throws an error:

```
Identity Provider github already exists
```

### How to Reproduce?

Run the same create command twice, to:

* create an id provider
* configure an id provider

### Anything else?

If "configuring" means "create" then that's ok. But it should be describes as such. Also the documentation should then have a section on how to "configure" ("update"?) and ID provider.

**Comment by shawkins** [comment]
Removed the triage label, the complaint is valid. However most will be able to discern that we're dealing with a create from the command and this seems to be repeated throughout the guide - it's more than just is providers that only a create is shown.
