### ISSUE TITLE
Configuration of flow execution is wiped after using admin UI drag and drop

### ISSUE THREAD

**Issue by vladimirr9** [keycloak/keycloak#21960]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Context:
Custom top level flow is created with two executions - one authenticator execution and one subflow execution with its own executions.
Scenario:
Upon drag and dropping the authenticator execution to be under the subflow execution - it joins the list of executions under the subflow, however the authenticator's config is cleared.

### Version

21.1.0, 22.0.1, nightly

### Expected behavior

The authenticator execution retains its configuration. Especially if this is done accidentally and we want to drag and drop the execution to be back on the same hierarchical level as the subflow instead of under it.

### Actual behavior

The configuration of the execution is cleared, I'm not sure if it still exists in the DB, but it's no longer displayed in the browser and if refreshed it's still cleared - the connection is severed regardless.

### How to Reproduce?

I think what I've written so far should be enough for the problem to be reproduced, I have nothing else to add to this.

**Comment by ssilvert** [comment]
I have verified this bug.

**Comment by ChrisBrandhorst** [comment]
We have also experienced this bug and wanted to create in issue for it. Should be high-impact if you ask us, since accidental production config removal is possible.

**Comment by ChrisBrandhorst** [comment]
Thanks for a fix. We do feel the solution is not really great, since dragging and dropping is not an atomic operation. The now added request submitting the configuration may still fail after the move operation completed, again resulting in data loss. Also, when moving around blocks with nested elements or nested blocks, data loss is still easily possible.

**Comment by jonkoops** [comment]
@ChrisBrandhorst could you report additional problems as separate issues? It will help us triage and fix them.
