### ISSUE TITLE
Allow to provider password to kcadm (keycloak-admin-cli) via environment variable

### ISSUE THREAD

**Issue by jirutka** [keycloak/keycloak#21961]
### Description

Please allow us to provide the user password for `kcadm` also via the environment variable, not just `--password` option or interactively.

### Motivation

Simplify using `kcadm` in scripts in a more secure way.

**Comment by EricLee423** [comment]
that's a good suggestion. 
In these days, due to the require from security standard, the chance is pretty high that special characters would be added into the password (such as " ),  passing such value via command line would break the functionality completely.

**Comment by jesperronn** [comment]
Very good idea. Although it seems little has happened for the last month, perhaps someone reading this would try to make a suggestion?

**Comment by shawkins** [comment]
To be addressed after #28329 - it would be a good idea if this were an option for all passwords, if not all options.
