### ISSUE TITLE
Improved UX for tweaking JVM memory settings

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#21996]
### Description

Currently, it's not very user friendly to tweak the JVM settings. Only way is to do it is to override the defaults using env vars. We should consider exposing some memory settings in particular (`-Xms`, `-Xmx`, `-XX:MetaspaceSize`, `-XX:MaxMetaspaceSize`) in a more user friendly way. This mainly concerns the Operator but we might also want to consider exposing these via CLI options as well to have a seamless experience between Operator and bare metal deployments.

### Discussion

https://github.com/keycloak/keycloak/pull/21884#issuecomment-1651806055

**Comment by ahus1** [comment]
Another way for this could be calculating JVMs memory settings from the container limits and requests. I know it is tricky, still it would simplify things for user to have only one setting to worry about. 

The downside: If we get it wrong, the JVM will be OOM killed by Kubernetes.

**Comment by shawkins** [comment]
@ahus1 this was mentioned briefly on https://github.com/keycloak/keycloak/issues/23182#issuecomment-1716818464 - that is certianly what I would like for the default behavior once #20107 is addressed.

**Comment by sschu** [comment]
@ahus1 For a bare Keycloak without extensions, this might be possible. But if people add their own extensions, Setting heap and metaspace max will still be necessary since you have no idea what happens in the extensions.

**Comment by wallagib** [comment]
Just more notes on the jvm memory settings

> `-XX:InitialRAMPercentage`, `-XX:MaxRAMPercentage`, and `-XX:MinRAMPercentage`.
> Setting these percentage options when the application runs in a container is preferable to setting maximum and minimum heap size for your application via `-Xmx` and `-Xms`, respectively. The `-XX` options set the heap size relative to the container memory limits and get updated automatically on redeployment should those limits change in the deployment configuration. When both types of settings are in place, `-Xmx` and `-Xms` take precedence.

https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#recent_changes_in_openjdk_s_container_awareness_code

**Comment by sschu** [comment]
In my experience, these settings are not very helpful. What get's our applications OOM-Killed is typically off-heap memory, especially stack space if too many threads are spawned. I would rather like to have a setting to reserve a fixed amount of memory off-heap and use the rest for heap. With a percentage, the space for off-heap memory is dynamic when it really depends on the code you are running (metaspace etc.) and the number of threads you spawn and stack space per thread (which roughly depends on the load you get). Therefore, I rather configure heap directly knowing my pod memory therefore being able to specify off-heap memory in absolute terms.

**Comment by shawkins** [comment]
Marking as out-of-date based upon the containerized memory setting work #26661
