### ISSUE TITLE
Infinite Recursive Loop Causing Application Freeze

### ISSUE THREAD

**Issue by alidandach** [keycloak/keycloak#22010]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/jee

### Describe the bug

The 'getInputStream()' method in the 'org.keycloak.adapters.servlet.FilterSessionStore' class is experiencing an infinite recursive loop, leading to the application freezing under certain conditions.

### Version

22.0.1

### Expected behavior

The 'getInputStream()' method should return the appropriate 'ServletInputStream' as expected without causing an infinite recursive loop.

### Actual behavior

Instead of returning the 'ServletInputStream', the method enters an infinite recursive loop and freezes the application.

```
                public ServletInputStream getInputStream() throws IOException {

                    if (needRequestRestore && body != null) {
                        final ByteArrayInputStream is = new ByteArrayInputStream(body);
                        return new ServletInputStream() {
                            @Override
                            public int read() throws IOException {
                                return is.read();
                            }
                            @Override
                            public boolean isFinished() {
                                return isFinished();
                            }
                            @Override
                            public boolean isReady() {
                                return isReady();
                            }
                            public void setReadListener(ReadListener readListener) {
                                throw new UnsupportedOperationException();
                            }
                        };
                    }
                    return super.getInputStream();
                }
```

### How to Reproduce?

Steps to Reproduce:
1. Set 'needRequestRestore' to true.
2. Provide a non-null 'body' to the 'Servlet' class.
3. Call the 'getInputStream()' method.

**Comment by mposolda** [comment]
This is related to adapters and hence is not very big priority. So moving to Backlog.
