### ISSUE TITLE
The field username is overridden with the user's email 

### ISSUE THREAD

**Issue by onikitin-iqmessenger** [keycloak/keycloak#22036]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

The field username is overridden with the user's email in case there are enabled settings `Email as username` and `Edit username`

### Version

21.1.2, 22.0.1

### Expected behavior

The username for the chosen user was updated
This user is allowed to log in via their email **and** username

### Actual behavior

The username was changed to its email ignoring the updated field for it, so the field `Username` on the page `Update Profile` seems to be useless

### How to Reproduce?

1. Log in as an admin into Keycloak admin
2. Go to Realm settings → Login
3. Enable `Email as username` and `Edit username`
![image](https://github.com/keycloak/keycloak/assets/85672364/cbd56f18-e53c-4fb8-b49b-c98549dd094e)
5. Go to `Users` and edit "user1" chosen for testing
6. `Details` tab → `Required user actions` field → Enable `Update Profile`
![image](https://github.com/keycloak/keycloak/assets/85672364/961d1960-fa14-4f1d-b277-e2171e52989a)
7. Log out or go to another browser to the Login page
8. Log in with the "user1"
9. Fill all the needed fields → in the field `Username` set "user1_updated"
![image](https://github.com/keycloak/keycloak/assets/85672364/04fb39c1-9df0-4123-a76a-0267ecfc5e9f)

**Comment by pedroigor** [comment]
@onikitin-iqmessenger The behavior is expected. If you want to allow users to authenticate with their username and e-mail, you should enable the `Login with email` at your realm settings.

**Comment by lrozenblyum** [comment]
@pedroigor well maybe the problem is that in this combination of settings we do allow changing the field via the screen `Update profile` but the changes are ignored. It's confusing. Maybe the ``username` field should be read-only for this combination of settings.

**Comment by pedroigor** [comment]
But if the `Email as username` setting is enabled the `username` field should be disabled or not shown t all. But the `username`  value will still be updated accordingly to the `email` you set.
