### ISSUE TITLE
Store Model Tests timeout

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#22057]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

Store Model Test seems to usually take around 45 min, but has lately started to randomly take more than 75 min and being killed:

https://stianst.github.io/keycloak-dashboard/tests#failed-job-store-model-tests
https://stianst.github.io/keycloak-dashboard/workflows

Examples for cancelled runs: 
* https://github.com/keycloak/keycloak/actions/runs/5686686701/job/15414167537
* https://github.com/keycloak/keycloak/actions/runs/5681799870/job/15399452674
* https://github.com/keycloak/keycloak/actions/runs/5668657298/job/15360618483

### Version

main

### Expected behavior

Tests are not cancelled

### Actual behavior

Tests are cancelled after 75 min

### How to Reproduce?

Review logs from GitHub Actions

**Comment by ahus1** [comment]
All the three runs listed above failed in the cross-dc section of the model tests. I'm suspecting that the new Infinispan patch release didn't resolve this one, so I'm about to revert #21862 and re-open the issue connected to that.
