### ISSUE TITLE
[Login UI] Toggle Password Visibility

### ISSUE THREAD

**Issue by andreas-blaettlinger** [keycloak/keycloak#22067]
### Description

We would like to improve the look and feel of the login-ftl-based pages by allowing to toggle the visibility of all password input fields.

![grafik](https://github.com/keycloak/keycloak/assets/69153350/bc97c058-1db4-420b-bdfb-203f3761e540)

**Comment by dasniko** [comment]
I just came across this form the latest release notes (23).
Generally a good thing, which I appreciate.

But is there a reason, why there are hard-coded patternfly classnames in the template files of the `base` theme? Now, when I have my custom theme, inheriting the base theme and customizing it only with css classes, I don't have a chance to use my custom classes for the icon and the surrounding button classes.

I would vote for using properties-placeholders as for all the other classnames and adding them to the default keycloak theme with the pf-values. WDYT, @pedroigor @jonkoops ?
If yes, I can create an issue and prepare a PR for this.

**Comment by jonkoops** [comment]
Can you log this as a new issue @dasniko, it will make it easier to triage and discuss.
