### ISSUE TITLE
Enable WebAuthn tests for Firefox

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#22075]
### Description

Once the https://github.com/keycloak/keycloak/issues/22074 is resolved, we can enable WebAuthn tests executed in our GHA CI again. 

These tests are disabled in https://github.com/keycloak/keycloak/pull/22071.

**Comment by mabartos** [comment]
@miquelsi As the #22074 is resolved, we should enable the WebAuthn tests for Firefox again. WDYT? Moving to the milestone 26

**Comment by miquelsi** [comment]
> @miquelsi As the #22074 is resolved, we should enable the WebAuthn tests for Firefox again. WDYT? Moving to the milestone 26

Thanks for the reminder, we will take care of it.

**Comment by mabartos** [comment]
I already sent a draft PR: https://github.com/keycloak/keycloak/pull/30374

However, I see how many tests are ignored for Firefox due to the inability to leverage virtual authenticators, I'm on top of a fence whether to enable them or not (at all). The thing is that when WebAuthn tests are executed with Firefox, only flows that do not work with WebAuthn directly can be executed - which is basically testing only some login screens and account console.

On the other hand, at least we have some test coverage for these login screens related to WebAuthn. The check of available passkeys in the account console should be covered by the JS tests - I guess so, right?

Related issue: https://github.com/keycloak/keycloak/issues/10368

**Comment by miquelsi** [comment]
I'd say enabling them, even if it's only a few tests. As you say, at least we have some coverage there. Thanks @mabartos!
