### ISSUE TITLE
In assign role dialog, the filter dropdown is missing when having only manage-user role

### ISSUE THREAD

**Issue by joggeli34** [keycloak/keycloak#22079]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When having a user with "realm-management / manage-users" role and open the assign role dialog for a user or a group then the filter dropdown is not visible:

![image](https://github.com/keycloak/keycloak/assets/34470368/321acb9f-e0c8-4ea1-bdd1-5470ca488c14)

This leads to the problem, that only client-roles and no realm roles can be applied.

### Version

22.0.1

### Expected behavior

The filter dropdown should be visible always, when the dialog can be open:
![image](https://github.com/keycloak/keycloak/assets/34470368/d098842c-1bf2-4a7c-a4b8-ee27007c2f3c)

### Actual behavior

Missing filter:

![image](https://github.com/keycloak/keycloak/assets/34470368/321acb9f-e0c8-4ea1-bdd1-5470ca488c14)

### How to Reproduce?

Create a user for the realm with "realm-management / manage-users" role and try to apply a role to an existing user

**Comment by ssilvert** [comment]
We did just recently change the UI for this, but it is working as designed.  In order to assign realm roles, you must have at least "view-realm" access.   So the UI now reflects that.

**Comment by ssilvert** [comment]
Hmm.  I took another look and you should also be allowed to assign realm roles if you have "query-users" access.  

However, "manage-users" alone isn't enough.  Strangely, "manage-users" does not include "query-users".

I'm going to make the change so that you can assign realm roles with "query-users" access.  Hope that fixes your problem.

**Comment by joggeli34** [comment]
Yes this will fix our problem, as we indeed also have the "view-users" role which includes "query-users" and "query-groups".
thanx
