### ISSUE TITLE
Client create with "authorizationServicesEnabled" crashes

### ISSUE THREAD

**Issue by wopl** [keycloak/keycloak#22072]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

creating a new client with API works well, if "authorizationServicesEnabled" is not specified.
Specified and set to "true" will result in error below. Here my request (Ansible):

`
- name: Create Keycloak Client 
  ignore_errors: yes
  uri:
    url: "{{ KeycloakConfig.KEYCLOAK_URL }}/admin/realms/{{ KeycloakConfig.REALM }}/clients"
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    body_format: json
    status_code:
      - 201
    body:
      "name": "{{ client_name }}"
      "authorizationServicesEnabled": "true"

`

### Version

21.1. Docker Container

### Expected behavior

Creation of Client. Switch "Authorization" turned on.

### Actual behavior

`
ok: [m1] => {
    "msg": {
        "changed": false,
        "connection": "close",
        "content_length": "25",
        "content_type": "application/json",
        "date": "Fri, 28 Jul 2023 10:29:49 GMT",
        "elapsed": 0,
        "failed": true,
        "json": {
            "error": "unknown_error"
        },
        "msg": "Status code was 500 and not [201]: HTTP Error 500: Internal Server Error",
        "redirected": false,
        "referrer_policy": "no-referrer",
        "status": 500,
        "strict_transport_security": "max-age=31536000; includeSubDomains",
        "url": "https://mydomain.com/admin/realms/myrealm/clients",
        "x_content_type_options": "nosniff",
        "x_frame_options": "SAMEORIGIN",
        "x_xss_protection": "1; mode=block"
    }
}

`

### How to Reproduce?

running Ansible script above with and without parameter

**Comment by rmartinc** [comment]
Hi @wopl!

In order to setup the authorization you also need the the service credentials enabled and the update client is a PUT not a POST. Can you try doing the following?

```bash
curl -X PUT -v "http://${URL}/admin/realms/${REALM}/clients/${CLIENT_ID}" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json;charset=utf-8" \
 -H "Authorization: Bearer $TKN" \
 -d '{"name": "test-oidc", "authorizationServicesEnabled": true, "serviceAccountsEnabled": true}'
```

Check also the log in the server to see if you get a more proper cause of the errors.

Thanks!

**Comment by wopl** [comment]
Hi @rmartinc,
it is ok with the POST, as I am itentionally creating the client.
From Ansible docs I read: Are authorization services enabled for this client or not (OpenID connect). This is ‘authorizationServicesEnabled’ in the Keycloak REST API.
"authorizationServicesEnabled" and "serviceAccountsEnabled" cannot be set TRUE both.
And trying it, did not work.

Further investigation needed.
Thanks anyway.

**Comment by rmartinc** [comment]
@wopl I can create the client with this simple curl bash script:

```bash
#!/bin/bash

URL="http://localhost:8080"
USER="admin"
USER_PWD="admin"
REALM="master"

export TKN=$(curl -sX POST "${URL}/realms/${REALM}/protocol/openid-connect/token" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -d "username=${USER}" \
 -d "password=${USER_PWD}" \
 -d 'grant_type=password' \
 -d 'client_id=admin-cli' | jq -r '.access_token')

curl -X POST -v "${URL}/admin/realms/${REALM}/clients" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json;charset=utf-8" \
 -H "Authorization: Bearer $TKN" \
 -d '{"clientId": "to-delete", "authorizationServicesEnabled": true, "serviceAccountsEnabled": true}'
```

Using keycloak 22.0.1 it returns a 201 creted and I see in the console that the client has the `Authorization` set to ON. Can you please try with it and last version of keycloak?

**Comment by wopl** [comment]
Yes, I updated to 22.0.1 today. 201 is normal for insert, I am aware. Usualy I am using the Ansible community.general.keycloak_client module as a wrapper. But also on native Ansible URI (similar to your proposal) I ran into the crash. 
As said, creation and doing a PUT afterwards now works for me. All is fine. 

hmmm, you are using "client_id"... I was using "name" (see top of my thread). That could be the reason.

**Comment by rmartinc** [comment]
Check the server log, it usually dumps the exception stacktrace. In my case when the `serviceAccountsEnabled` was not present it showed the following:

```
2023-07-31 14:54:18,800 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-24) Uncaught server error: java.lang.RuntimeException: Client does not have a service account.
	at org.keycloak.authorization.admin.ResourceServerService.create(ResourceServerService.java:81)
	at org.keycloak.authorization.admin.AuthorizationService.enable(AuthorizationService.java:64)
	at org.keycloak.services.resources.admin.ClientsResource.createClient(ClientsResource.java:202)
        ...
```

**Comment by wopl** [comment]
Hi @rmartinc , I can fully confirm your answer. I got the same message and adding "ServiceAccountsEnabled" did completely solve the issue.
Many thanks !!!
Wolfram
