### ISSUE TITLE
Operator logs full Secret

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22080]
### Description

Related to https://github.com/operator-framework/java-operator-sdk/discussions/1983 the operator will log Secrets it creates: 

https://github.com/keycloak/keycloak/blob/a33b76e6f733baa4303cc0c1663ea421596fa295/operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java#L81

And in the case of a failure:

https://github.com/keycloak/keycloak/blob/a33b76e6f733baa4303cc0c1663ea421596fa295/operator/src/main/java/org/keycloak/operator/controllers/OperatorManagedResource.java#L85

cc @vmuzikar

**Comment by vmuzikar** [comment]
@shawkins Could you please also create a PR to main just to be on the safe side?

We might remain on Quarkus LTS and JOSDK 4 for KC 23. That means that we'd either need a backport of https://github.com/operator-framework/java-operator-sdk/pull/1985, or a fix to our main.

**Comment by csviri** [comment]
I don't think we need a backport, although this is mainly question on quarkus side, I want to make a patch release soon for JOSDK, the QOSDK LTS might use just that. cc @metacosm
