### ISSUE TITLE
Add non-blocking liveness and readiness checks to Keycloak

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#22109]
### Description

When testing failover between Keycloak pods under load in Keycloak Benchmark, we saw that requests in Keycloak queue up for 5-10 seconds while Infinispan suspects a leaving node, and rebalances. 

The requests are eventually served successfully, but the delayed processing also affects liveness and readiness probes, which would time out. 

This is due to the probes in Quarkus 3.2.2 being blocking I've raised an issue in Quarkus upstream to make them non-blocking, see https://github.com/quarkusio/quarkus/pull/35100
Once they are non-blocking, the will not be enqueue in the blocking thread pool.
The liveness probe will then be always non-blocking as it doesn't contain any checks (as intended). The readiness probe should only block when it needs to connect to the database.

I'll prepare a PR to update the readiness probe, and also add a workaround until the upstream change is available in a release consumable by Keycloak.

This would allow Keycloak to have a liveness probe with a timeout of 1 second again, and avoids a pod restart if the request queue is filled.

### Motivation

A full blocking request queue of Keycloak shouldn't lead to a restart of the Keycloak pod.

**Comment by vmuzikar** [comment]
As discussed offline, we'll address this in 23.

**Comment by stianst** [comment]
Whether or not this is a fix in Quarkus or a workaround in Keycloak it should be backported to 22 as this has quite a bad impact on how well deployments behave due to the probes.

**Comment by vmuzikar** [comment]
@stianst I agree the impact of the bug is relatively high. However, given how uncertain Quarkus was around the potential risks with the fix, it seemed it might not be something we want to do in a micro.

**Comment by cjabrantes** [comment]
@ahus1
I was about to open an issue when i found this issue.

I deployed KC with the operator with 2 instances running, my test was simulating a network partition around one instance of KC.

I expected that readiness probe would fail and with that the pod would be removed from the available service endpoints, but it didn't happen.

At the end even with one healthy instance i endup having impact.

Can you please confirm if your PR will address this situation? Or should i open a new issue?

Thanks,

**Comment by ahus1** [comment]
@cjabrantes - this PR will not address the issue as there is no probe checking for a network partition in the liveness probe.

**Comment by cjabrantes** [comment]
Hi @ahus1,

Just to be sure that we are in sync and sorry if i m lacking some KC knowledge.
KC needs to reach DB to be able to work (excluding cache lookups probably), correct? And i guess other KC instances if cluster (but here i guess the topic may be more complex and require more thoughts and decisions). 

If the readiness probe could check the DB reachability (by simulating some flow or explicit DB connect/query), this would allow to solve the issue (or at least strongly mitigate it) as the readiness probe is enough, meaning that if readiness probe fails the endpoint will be removed from services.

At this moment (22.0.3) the readiness probe continues to be ok until the container crashes.

Thanks for your time.

**Comment by ahus1** [comment]
@cjabrantes - this issue not related to the problem you describe. Please open a new issue for that.

**Comment by sschu** [comment]
@cjabrantes AFAIK the current readyness probe already contains a check for reachability of the database. So if in your partition test you cut off one pod from the database, that pod should become unready.

**Comment by cjabrantes** [comment]
@sschu to avoid spam this issue with non related topic i open the https://github.com/keycloak/keycloak/issues/23798.
But from what i saw the probe dont fail.

**Comment by ahus1** [comment]
There is a follow-up issue to track the progress in Quarkus, and to revert any workaround added here #23854

**Comment by ahus1** [comment]
Backport created: #23855
