### ISSUE TITLE
Invalid redirect uri error from account client logout 

### ISSUE THREAD

**Issue by dsaju** [keycloak/keycloak#22110]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

On a k8s setup for keycloak (20.0.5) configured with edge reverse proxy setting I am seeing a problem on logout from the client (account) on the company realm . The GET request always sets the post_logout_redirect_uri to http instead of https even though the KC_HOSTNAME_URL is set with https schema. This throws the error 'Invalid redirect uri'
because http link is unreachable. On enabling the debug option on keycloak I see some entries from Quarkus that looks something like below .

_2023-07-27 11:14:54,255 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-1) Recalculated absoluteURI to http://<KC_HOSTNAME_URL>

In the above log entry , I see absoluteURI set to http instead of https://<KC_HOSTNAME_URL>. Does anyone has an idea on what configuration might be causing this ?

Note : This issue is not seen on logout from Admin console where the post_logout_redirect_uri is set to https link for the ${authAdminUrl} in the master realm and logout works correctly

Thanks a lot for the help .

### Version

20.0.5

### Expected behavior

post_logout_redirect_uri is set to http://<KC_HOSTNAME_URL> and logout is successful

### Actual behavior

post_logout_redirect_uri is set to https://<KC_HOSTNAME_URL> 

![image](https://github.com/keycloak/keycloak/assets/7468421/59400d92-551c-48dc-a69d-257deac2c327)

### How to Reproduce?

1. Configure keycloak on eks
2. Access the account client url  to login using a client
3. Login successful 
4. Click on logout

### Anything else?

Following message is seen on keycloak logs which does not look right 

_2023-07-27 11:14:54,255 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-1) Recalculated absoluteURI to http://<KC_HOSTNAME_URL>

**Comment by ssilvert** [comment]
This looks more like a core issue than a UI issue.  Switching to core team.

**Comment by mposolda** [comment]
Adding to Backlog as I don't know if Keycloak team will have time to look to this.

Moreover, it seems to me rather a configuration issue related to the reverse proxy setup or something like that. Please make sure that you use `https` everywhere (on all parties and configuration options also on the reverse-proxy site).

**Comment by dsaju** [comment]
Thanks for the reply @mposolda 
All my host references are using https schema apart from ingress which refers to http port on the pod 

I noticed that that the admin account logout uses redirect_uri and that refers to the https link to KC_HOSTNAME_URL  and logout works well . 

Another strange observation is that post_logout_redirect_uri is using the **ingress** hostname instead of the hostname used in the environment i.e KC_HOSTNAME_URL but with the http schema .
The  KC_HOSTNAME_STRICT_BACKCHANNEL is set to true. 

Looking forward to some hints

**Comment by sschu** [comment]
@dsaju The function you mentioned recalculates the uri based on (X-)Forwarded-* headers it received. Can you maybe log all request headers to see if there are any Forwarded headers that might influence the calculation? You can check how to do this here: https://quarkus.io/guides/http-reference#configuring-http-access-logs

**Comment by dsaju** [comment]
@sschu From the logging header I see set of X-Forwarded * values referring to http schema . But this is expected because we are using edge proxy mode . I  did not expect this to influence the re-calculation of absoluteURI or post_logout_redirect_uri  because all other access works well on https mode . 

Below are the set of values seen in the logs : 

X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Scheme: http
X-Scheme: http

**Comment by sschu** [comment]
But this seems to be the issue. The headers should indicate how the original request looked like, so that should all be https and port 443.

**Comment by dsaju** [comment]
@sschu  We are using nginx ingress on eks as the reverse proxy,    The ingress resource on keycloak uses http to connect to the pod but HOST url is configured on https. Do you have any ideas to solve it so that post_logout_redirect_uri  is calculated with https ? 

BTW , the redirect_uri is calculated correctly when I logout from admin console. 

Thanks for the help.

**Comment by sschu** [comment]
Your ingress needs to set X-Forwarded-* headers correctly to https. Normally, I would assume nginx does this correctly automatically, I don't know why this does not work in your case.

**Comment by dsaju** [comment]
The issue was resolved by added the X-Forwarded-* on the loadbalancer (f5) to be forwarded to the proxy . The issue can be closed. Thanks a lot for the hints .
