### ISSUE TITLE
[operator] - deployement failure when using custom image on operator 22.0.0 and 22.0.1

### ISSUE THREAD

**Issue by grimlokason** [keycloak/keycloak#22119]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

Hello,

We have built our on keycloak images because we need to add internal root CA.
On operator 21.1.2, we are able to start it, on operator 22.x, it's not possible anymore.

Here seems to be the culprit : https://github.com/keycloak/keycloak/blob/main/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java#L229

I don't understand why custom images need to be considered as already optimized when they can be used with different settings after.
For us for exemple, we are using different DB, i don't want to build a specific docker images for each of my env.

Best regards

### Version

22.0.1

### Expected behavior

The container doesn't start with the "--optimized" by default

### Actual behavior

the container start with "--optimized" and the application is not able to boot

### How to Reproduce?

use a custom image and try to start it with the 22.0.x operator 
here is my dockerfile : 

```FROM quay.io/keycloak/keycloak:CITAGVERSION as builder
WORKDIR /opt/keycloak
ENV KC_DB=postgres

RUN /opt/keycloak/bin/kc.sh build

FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
COPY rootca.cer /etc/pki/ca-trust/source/anchors/rootca.cer
RUN update-ca-trust

FROM quay.io/keycloak/keycloak:CITAGVERSION
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --from=ubi-micro-build /etc/pki /etc/pki
ENV KC_DB=postgres
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start"]
```

**Comment by vmuzikar** [comment]
@grimlokason Thank you for the report.

This is not considered a bug but rather a design decision to follow the [best practices that custom images are optimized](https://www.keycloak.org/server/containers#_creating_a_customized_and_optimized_container_image). Feel free to open an RFE.

You might also consider [overwriting](https://github.com/keycloak/keycloak-k8s-resources/blob/22.0.1/kubernetes/kubernetes.yml#L211-L212) the default KC image that is used by the Operator. Such image is then considered as unoptimized.
