### ISSUE TITLE
Removing single role from user will remove all roles

### ISSUE THREAD

**Issue by matthiasballreich** [keycloak/keycloak#22115]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

The issue is that when trying to remove a single role (doesn't matter if it's a composite role or default roles) from a user, keycloak automatically removes all roles from the user.

It only appears when a special realm configuration was imported. When creating a new realm or trying this on the master realm this issue also appears, but only after importing the configuration of our special realm.

This issue happened with version 16, then we upgraded to Version 19.0.3 but it didn't help.

If needed we could provide the realm json-export.

### Version

19.0.3

### Expected behavior

Expected behavior is that wenn removing a single role from a user, all the other associated rules will not be removed from that user.

### Actual behavior

At the moment, when removing a single role (doesn't matter if it's a composite role or default roles) from a user, keycloak automatically removes all roles from the user.

### How to Reproduce?

1. Choose a user or create a new one
2. Try to remove a single role from this user
3. All roles will be removed

On our new Environment we did as step 1: Importing our special realm that causes the issue and then did the steps 1 to 3 from above.

**Comment by pedroigor** [comment]
@matthiasballreich Tried to reproduce without success. Would you be able to check latest release or nightly container image?

**Comment by pedroigor** [comment]
Not able to reproduce.

**Comment by matthiasballreich** [comment]
@pedroigor Can i send oyu our json-configuration, so that you can try to reproduce it with these data?
The problem only occurs, if we use this configuration (on a new installation, too).

**Comment by nikolamus** [comment]
I'm currently experiencing this issue on version 26.2.5.
It seems to depend on some aspect of configuration. We have 2 instances of Keycloak - nonprod and prod. Identical version and deployment params. The issue only appears on one (prod).

Same as mentioned in the ticket description, the realm was configured by importing a json-export file from another instance.
