### ISSUE TITLE
jwks is getting keycloak kid 

### ISSUE THREAD

**Issue by eassa** [keycloak/keycloak#22146]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

i am trying to use jwks , and when i check the kid in the token , i get the kid of keycloak not auth0

![image](https://github.com/keycloak/keycloak/assets/14801394/e89a084b-6593-4771-b5b6-ea205b12c85b)
![image](https://github.com/keycloak/keycloak/assets/14801394/9e919614-5707-44e0-962c-f5a9bcca9884)
![image](https://github.com/keycloak/keycloak/assets/14801394/98e5bbb9-91ee-4d48-86e8-c2bab4023c38)
![image](https://github.com/keycloak/keycloak/assets/14801394/bd1af9f4-3184-42dd-a08f-ef14d8881370)
jwks url : 
https://login-uat.isioc.net/.well-known/jwks.json

token : eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxeVVFQkJCODZKZFJfazFsV2JpV2VNd3BRYUNfNzNQMGpqVEdYUDFKaFQ0In0.eyJleHAiOjE2OTA4ODE4NzAsImlhdCI6MTY5MDg4MTU3MCwianRpIjoiYWZkYWY5OGItYTFmOS00ZmU2LWE3NWMtMDg5ZjgxYWIyZTI2IiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6ODA4Mi9yZWFsbXMvb2x5bXB1cyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJiN2FmYzA5OC0zMGNlLTQzYzctYWJmYS0wNDNhYjQ4NGE3NzkiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwcml2YXRlX3Rlc3QiLCJzZXNzaW9uX3N0YXRlIjoiZGVkMDRkZWMtNGJjMi00ODJlLTljZDItYzg3NTM2NTYzOWRkIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImFkbWluIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLW9seW1wdXMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJkZWQwNGRlYy00YmMyLTQ4MmUtOWNkMi1jODc1MzY1NjM5ZGQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJlYXNzYSBuYXNzYXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJlYXNzYSIsImdpdmVuX25hbWUiOiJlYXNzYSIsImZhbWlseV9uYW1lIjoibmFzc2FyIn0.elpQkbMsnhfBxkzHt76pcy1gzip3dYhNLFxI_fPzD2T20J7aYQ42Pv7U24SzBP_H8qsYZWuGXn_HrEix6aOMwGIIo12orZ4T0Yufa6fOfTh4V5GBU5_kUTB4jjM12qJNc65RazSdMmrPO3rrsHJNMvV8M98WrUQDvFqyFjQSDi3f_LQBvvLi5tRoD--U717WUJhVk4L0wApm5DDG3dNAd5KohSwBa0514OTnSSwmb5_l88WpEaPnAQ4OiRA3S1JlU8qHCp37ii21ZpzCa3YGimSEMzjXxMLAOiMJxvVY0gPtqpShOEw6hQKgBgRIeJYPKOmKYFRw4dxeEs39xT_8Lg

http://localhost:8080/realms/olympus/protocol/openid-connect/certs: 
{
  "keys": [
    {
      "kid": "1yUEBBB86JdR_k1lWbiWeMwpQaC_73P0jjTGXP1JhT4",
      "kty": "RSA",
      "alg": "RS256",
      "use": "sig",
      "n": "n224N2N2639u8r1GHEcTjQ1mIsUQlEakhztLqEwIgmSurG4xyjWSmID_hXOulfhQa0bJMXWxiVnMuXKRKs14FcHd17TJhJi5yfS4ZlbqLMWbPdazdwL-re2Y7n09RZt_hBuJi0njxwD9BeEtkkQU-N8JhypiBNcejdCri_Gat8ZxImqCldZX8VQMGu_-JOoJthduqXUT3GLeiQO5g76Nyc8Ve2CNQLX2mFSJyzKdBhgOE1JPRdBBNdZSxXg_yY7a_eAt8FDeeJXCJHfltQDjHPptYt4TRk8LWWJHPLgq0eKDQWUd24gTYTk80cHs5Ks1wKCAHPYoFXou8lfMgPoHmQ",
      "e": "AQAB",
      "x5c": [
        "MIICnTCCAYUCBgGJsD/U3jANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdvbHltcHVzMB4XDTIzMDgwMTA4MzcwMFoXDTMzMDgwMTA4Mzg0MFowEjEQMA4GA1UEAwwHb2x5bXB1czCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ9tuDdjdut/bvK9RhxHE40NZiLFEJRGpIc7S6hMCIJkrqxuMco1kpiA/4VzrpX4UGtGyTF1sYlZzLlykSrNeBXB3de0yYSYucn0uGZW6izFmz3Ws3cC/q3tmO59PUWbf4QbiYtJ48cA/QXhLZJEFPjfCYcqYgTXHo3Qq4vxmrfGcSJqgpXWV/FUDBrv/iTqCbYXbql1E9xi3okDuYO+jcnPFXtgjUC19phUicsynQYYDhNST0XQQTXWUsV4P8mO2v3gLfBQ3niVwiR35bUA4xz6bWLeE0ZPC1liRzy4KtHig0FlHduIE2E5PNHB7OSrNcCggBz2KBV6LvJXzID6B5kCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAelqOfgyOmWgBDk4vhr8+wbVkN0Y7BdafwjeOHtDh2eF60kyc0HG4zBn9wwaMoidgGfn+Dj4vWt6oDJqbr8bf/VjIziNp9luVbKDucERGT6MSQa4Ex6K8dfyUfCOT3S/sR1m1iMDRjJxy1hCZC+CA+hiTsk1IfbURukqBQIGJEWmqxco3sHxiGqGpzQ9vHHOJUznfYxsT7fv2qQWAcxGtKg6Nung4QYicUcqrCpQubuw11byoPPq/GYFQAjdkIjNCCtBbyhoGH4/frdCL2s0uSu04TPEyb0UxcUgmw5RqSSaG5vYgONs6p2ryosPYYbmz04xPRQkpF+/XleId8+SBHw=="
      ],
      "x5t": "wAlDmcFzioEqubCY7Ix62G6uGOE",
      "x5t#S256": "6BdjvkYx5qePre-dmkcNYdNDv3xOWSeL1etJApUVono"
    },
    {
      "kid": "YPjF8I4E4_o0zZ96XjpAiQJyLacSBl0hWEjtYIEpIAs",
      "kty": "RSA",
      "alg": "RSA-OAEP",
      "use": "enc",
      "n": "vIiRYTodbbM-YawaN7rj1wGyCvaYGIggE7Rzteilbr8GbN-c6KrOoY-Y2PR9-4lNjBMMPgwIA1qlVskJk5PtgTEPDtAriyFs0iQEhHOnrH9l07oajaTDvKZXO7NSPOlICQmdJUFuPNSBMgZRiNbqFGiMO3tVvPHAMrkhUgaAxhX0QHxWwEOHDXxH2ICfd29TKGgrYrrU59DTAwhtMv5lhqdd9ABehrE6YRmy5T-MzCZ912OekuPP5oHSO_m1tJqVjPEDvF5EbzpIAVXVwixCOqXESDwh2oUU3Y0SLUC4tqYZkNqobr14lQn0NFb7XqH_tc2uQ5ga1IFTMj_9pNvUcw",
      "e": "AQAB",
      "x5c": [
        "MIICnTCCAYUCBgGJsD/VbjANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDDAdvbHltcHVzMB4XDTIzMDgwMTA4MzcwMFoXDTMzMDgwMTA4Mzg0MFowEjEQMA4GA1UEAwwHb2x5bXB1czCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALyIkWE6HW2zPmGsGje649cBsgr2mBiIIBO0c7XopW6/BmzfnOiqzqGPmNj0ffuJTYwTDD4MCANapVbJCZOT7YExDw7QK4shbNIkBIRzp6x/ZdO6Go2kw7ymVzuzUjzpSAkJnSVBbjzUgTIGUYjW6hRojDt7VbzxwDK5IVIGgMYV9EB8VsBDhw18R9iAn3dvUyhoK2K61OfQ0wMIbTL+ZYanXfQAXoaxOmEZsuU/jMwmfddjnpLjz+aB0jv5tbSalYzxA7xeRG86SAFV1cIsQjqlxEg8IdqFFN2NEi1AuLamGZDaqG69eJUJ9DRW+16h/7XNrkOYGtSBUzI//aTb1HMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAhTt7GGj1YoHUYLzDe9Ei9zL7SyYH3dHvgqfaXIH8R/9RfLAmPhF3FtyzGo2QisaBYsrmTZqPqRzRderpNSdV/ChkPGAU0IwtyhvvkNreVWdjGtTteDG2ppjt5c1AgSQbSiKEjGuAF+mz2QLNAnGKGNm+uvsAVxFIcRlDdSldSQxJqKqjLNvgVtDBGNE75X9WOwLaQ8eEITGnxw81QMU39tO3+mA7flsPQjFVfko3tSTsodhjaf06ULaRTx7zouaxl31QUPsj1JfAt0wxFD0Hd3iAmO77BjAMaWVpC8li3RCxF5Wqp4jhItoP9C2cgzONqZ/jqBHzXPvULQxBtKnCxg=="
      ],
      "x5t": "50ovVdLwMimaKwl125Aop6d2Leo",
      "x5t#S256": "wmYqtP_W7gAbEMerPj81DJvSK_FEwJ4URvX8AGHmAxs"
    }
  ]
}

### Version

21.1.1

### Expected behavior

kid should be the same as jwks url

### Actual behavior

if jwks on or off the same result, takes kid from keycloak not the jwks url

### How to Reproduce?

new realm  
new user name and password 
new private client and authorization
go to keys tab  and fill jwks url https://login-uat.isioc.net/.well-known/jwks.json
save
login ( using api : https://localhost:8082/realms/olympus/protocol/openid-connect/token) 
decode token ( in jwt.io)
kid is different than the jwks url , and it is the same as the keycloak keys

**Comment by rmartinc** [comment]
Hi @eassa!

The keys used in the client tab are different for the keys used in the realm. They are not the same keys and they have different usage. The keys in the client tab are used when, for example, the token should be encrypted (the server needs the encryption PubKey of the client to encrypt) or when the client uses a JWT to authenticate to the server (the server needs the signature PubKey to validate). The realm keys are used in the opposite use-cases, for example, when the server needs to sign the tokens to the client. So you don't have to see the same keys used by the client (https://login-uat.isioc.net/.well-known/jwks.json) and by the the realm (http://localhost:8080/realms/olympus/protocol/openid-connect/certs). They are different.

**Comment by sheremet** [comment]
> Hi @eassa!
> 
> The keys used in the client tab are different for the keys used in the realm. They are not the same keys and they have different usage. The keys in the client tab are used when, for example, the token should be encrypted (the server needs the encryption PubKey of the client to encrypt) or when the client uses a JWT to authenticate to the server (the server needs the signature PubKey to validate). The realm keys are used in the opposite use-cases, for example, when the server needs to sign the tokens to the client. So you don't have to see the same keys used by the client (https://login-uat.isioc.net/.well-known/jwks.json) and by the the realm (http://localhost:8080/realms/olympus/protocol/openid-connect/certs). They are different.

I have experienced with similar issue with `kid` when import RSA private key to realm using `rsa` and `rsa-enc` Key providers. `kid` generated by Keycloak is different with response from jose `calculateJwkThumbprint(publicJWK, 'sha256')` function (https://github.com/panva/jose/blob/HEAD/docs/functions/jwk_thumbprint.calculateJwkThumbprint.md), that implemented according to https://www.rfc-editor.org/rfc/rfc7638 standard
I think Keycloak should met this standard too.
