### ISSUE TITLE
WatchedSecretsTest.testSecretChangesArePropagated error in OCP

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#22143]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

This test is throwing an error when running in an OCP cluster.

### Version

latest

### Expected behavior

The test passes successfully

### Actual behavior

`2023-07-31 16:42:11  [ERROR]   WatchedSecretsTest.testSecretChangesArePropagated:113 » ConditionTimeout Condition with org.keycloak.operator.testsuite.integration.WatchedSecretsTest was not fulfilled within 1 minutes.`

### How to Reproduce?

`mvn install -Poperator -pl :keycloak-operator -am -Dquarkus.kubernetes.image-pull-policy=Always -Doperator.keycloak.image=quay.io/keycloak/keycloak:nightly -Dquarkus.container-image.image=quay.io/keycloak/keycloak-operator:nightly -Dquarkus.jib.jvm-arguments=-Djava.util.logging.manager=org.jboss.logmanager.LogManager -Doperator.keycloak.image-pull-policy=Always -Dtest.operator.deployment=remote`

### Anything else?

Full execution log: https://keycloak-jenkins/view/OpenShift/job/rhbk-operator-test-pipeline/27/execution/node/40/log/?consoleFull

**Comment by vmuzikar** [comment]
Does not affect 22.
