### ISSUE TITLE
Update OCP4 Social IdP example setup in the latest docs

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#22159]
### Description

Among prerequisites of the [OCP4 Social IdP example setup](https://www.keycloak.org/docs/latest/server_admin/index.html#openshift-4), the `X509_CA_BUNDLE` variable In the latest version docs.
This is probably a leftover from the WF dist docs, as the variable isn't supported in the Quarkus based container image [1][2].

[1] https://www.keycloak.org/server/containers
[2] https://github.com/keycloak/keycloak/tree/main/quarkus/container

**Comment by vmuzikar** [comment]
@Pepo48 Can you please create a backport PR?
