### ISSUE TITLE
Built-in Authentication flows with whitespaces on the flow name producing errors 

### ISSUE THREAD

**Issue by Mokhles-scp** [keycloak/keycloak#22150]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

The built-in authentication flows on which the flow name have whitespace are non accessible/editable and they  present an error like in the following screenshot if i click on any of them:
![Screenshot 2023-08-01 at 12 50 18](https://github.com/keycloak/keycloak/assets/141139235/b06aa9b1-2809-4208-aec8-bc0a7f75e4d5)
While the Built-in authentication flows on which the flow name is only one word (no whitespace) are working just fine, like the `browser` flow  : 
![Screenshot 2023-08-01 at 12 49 14](https://github.com/keycloak/keycloak/assets/141139235/6d03f17f-8a7c-4dd6-a96c-d879f23af88a)
![Screenshot 2023-08-01 at 12 49 41](https://github.com/keycloak/keycloak/assets/141139235/2ef5fe62-ebc6-47c6-8213-b059e3a606c5)

The same problem happens if we manually create new flows, the new created flow with whitespace in the name presents the same issue and same error. However if the new created flow does not have any whitespace (one word or many words separated with underscore/lowline, dot, or dash, for exp: direct_grant , direct-grant or ditrect.grant ) it will work fine and it will be accessible and editable.

### Version

21.1.1, 22.0.0 and 22.0.1

### Expected behavior

All Built-in authentication flows should be accessible/editable without errors.
Like the built-in `browser` or `clients` flow : 
![Screenshot 2023-08-01 at 12 49 14](https://github.com/keycloak/keycloak/assets/141139235/dc20f078-bb91-46a3-898b-2ff4f33fd66b)
![Screenshot 2023-08-01 at 12 49 41](https://github.com/keycloak/keycloak/assets/141139235/faf0dd55-46c7-4e1e-8f8f-64cb1814ffb1)

### Actual behavior

Any built-in authentication flow or a manually built authentication flow on which the flow name contains a whitespace will be not accessible/editable and will present the following error : 

![Screenshot 2023-08-01 at 13 44 30](https://github.com/keycloak/keycloak/assets/141139235/e5ad28d7-948c-47a7-852e-9de914f8f51d)

### How to Reproduce?

Install a keycloak and access it as admin then go to authentication.
Click on any of the authentication flows where the name contains whitespaces (exp: `direct grant`).

**Comment by Mokhles-scp** [comment]
@mposolda I just redeployed the nightly after updating the open-jdk but still having the same error.
Could you maybe try to create one authentication flow manually  and give it a name with spaces

**Comment by Mokhles-scp** [comment]
@mposolda any updates ?  im still able to reproduce the issue with the new release 22.0.3

**Comment by rmartinc** [comment]
@Mokhles-scp I have tried to reproduce it and it works with default flows and with a created flow with name "flow with spaces". If this was so easy to reproduce we would have tons of issues about this problem. We are missing something here. Do you have any special setup (proxy, browser,...)?

**Comment by Mokhles-scp** [comment]
@rmartinc i have tried with different browsers besides i have no special setup/config.
Just to know, im deploying keycloak as a docker container. 
I got the following error from developer tool maybe it helps : 
![image](https://github.com/keycloak/keycloak/assets/141139235/d251717c-96f9-4810-a49c-85483deb0ed2)

**Comment by rmartinc** [comment]
@Mokhles-scp I have just doen this:

```
podman run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak start-dev
```
And I can use the 8080 port without issues creating a flow with spaces. No issues at all. I see that the URL to obtain is correctly using %20: http://localhost:8080/admin/realms/master/authentication/flows/flow%20with%20space/executions

As I commented before we are missing something here. Any exception or weird log at the docker execution?

**Comment by Mokhles-scp** [comment]
@rmartinc 
You are right, the command you shared with `podman`is working fine and the issue is not there anymore. However, if you try the same command with docker like the following:
```shell
docker run -itd  -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak start-dev 
```  
you will not be able to access the admin interface :
![image](https://github.com/keycloak/keycloak/assets/141139235/e7fc78bb-9948-4f7b-8fa1-bb08664ece95)

If i configure my web server to be able to access the admin interface using TLS, i will get the error mentioned with this issue (not being able to access flows with spaces).
So far i don't really understand if it is  either a docker problem or web server problem and both do not make any sense.
do you have any hints ??

Thanks

**Comment by rmartinc** [comment]
> If i configure my web server to be able to access the admin interface using TLS, i will get the error mentioned with this issue (not being able to access flows with spaces).

Do you have a reverse proxy before the keycloak server? If that is true, then you probably have the problem there. You have to check what it's really receiving the keycloak in that request.

**Comment by pedroigor** [comment]
I'm also not able to reproduce the issue. Please, feel free to re-open if you managed to provide better steps to reproduce the error.

Perhaps you can try with the latest version or even nightly.
