### ISSUE TITLE
Occasional operator test failures

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22160]
### Description

Recent prs seem to be related to some failed startup / migration https://github.com/keycloak/keycloak/actions/runs/5726457904/job/15517348959?pr=22152#step:8:2561 and https://github.com/keycloak/keycloak/actions/runs/5726457904/job/15517348959?pr=22152#step:8:2699 - this does not happen consistently, but once it does it seems to inhibit that keycloak instance from coming up.  Presumably this has to do with sharing the database instance for all tests in a test class.

The root exception message is 
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "user_setup_allowed" of relation "authentication_execution" does not exist
```

This may have become more prevelent by changes to speed up the tests - the immediate termination of pods and not waiting for instances to become ready could cause a prior test to corrupt some expection of the database state.  However I'm not familar enough to know why it should even be entering migration logic.

cc @vmuzikar

**Comment by vmuzikar** [comment]
If a Keycloak starts with an empty DB, the DB is populated through migration process (through liquibase), i.e. first changes from version 1 are applied, then changes from version 2 etc. I assume we sometimes kill the pods before this finishes. I recon we have to re-add the probes to all tests.

**Comment by shawkins** [comment]
> I recon we have to re-add the probes to all tests.

I'll try to see if this is attributable to the graceful termination or not having the probes - I hope it's the former, if it's the latter it seems like that's an issue.  Someone could quickly create, then delete a keycloak, and that could leave the database in a bad state.
