### ISSUE TITLE
NPE when using Pairwise Subject Mapper with localhost redirect

### ISSUE THREAD

**Issue by bonnm** [keycloak/keycloak#22188]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

When doing login with an OIDC client that has a pairwise subject identifier mapper configured and a localhost redirect, a NPE occurrs:

`
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-165) Uncaught server error: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "sectorIdentifier" is null
        at org.keycloak.protocol.oidc.mappers.SHA256PairwiseSubMapper.generateSub(SHA256PairwiseSubMapper.java:92)
        at org.keycloak.protocol.oidc.mappers.SHA256PairwiseSubMapper.generateSub(SHA256PairwiseSubMapper.java:80)
        at org.keycloak.protocol.oidc.mappers.AbstractPairwiseSubMapper.transformAccessToken(AbstractPairwiseSubMapper.java:74)
        at org.keycloak.protocol.oidc.TokenManager.lambda$transformAccessToken$8(TokenManager.java:748)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
...
`

### Version

21.1.2

### Expected behavior

Token/userinfo is created without error, containing pairwise sub claim.

### Actual behavior

NPE in quarkus console/logs, see bug description.

### How to Reproduce?

Create a client with redirect uri `http://localhost:*`, add a dedicated scope mapper "Pairwise subject identifier", empty sector identifier field, empty salt field. Do a login with the client or use the evaluate function. See the NPE in the logs. 

### Anything else?

I run Keycloak 21.1.2 on vmware ESX, Ubuntu 20, OpenJDK 17, proxy edge mode behind apache, no docker, MS SQL 2019.

**Comment by rmartinc** [comment]
@bonnm I'm not very familiarized with the pairwise mappers but it seems that the [getSectorIdentifier](https://github.com/keycloak/keycloak/blob/22.0.3/services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractPairwiseSubMapper.java#L104-L110) is returning null. For what I see the method returns the hostname of the configured `Sector Identifier URI` in the mapper ([code](https://github.com/keycloak/keycloak/blob/22.0.3/services/src/main/java/org/keycloak/protocol/oidc/utils/PairwiseSubMapperUtils.java#L54)) or the hostname of the valid redirect uris ([code](https://github.com/keycloak/keycloak/blob/22.0.3/services/src/main/java/org/keycloak/protocol/oidc/utils/PairwiseSubMapperUtils.java#L88)).

What have configured in the mapper `Sector Identifier URI` option?
What do you have as `Valid redirect URIs` in the client?

Also probably setting debug `-log-level=INFO,org.keycloak.protocol.oidc:TRACE` you would get some interesting message. Paste if you see something relevant.

**Comment by bonnm** [comment]
I hava an empty `Sector Identifier URI` and a https://FQDN as `Valid redirect URIs`. That works, paiwise sub is generated. But if I change the valid redirects to http://localhost:* or add localhost to have multiple valid redirects (for client dev purposes...) I have the NPE. I think the Port Wildcard `:*` causes the null return value ([code](https://github.com/keycloak/keycloak/blob/074e85b4b6b200d0554c07aba8ea1221ba79aab6/services/src/main/java/org/keycloak/protocol/oidc/utils/PairwiseSubMapperUtils.java#L95))...
That's not a big thing and it is fully ok to close this issue, but maybe it's an option to add some help in the Admin UI or in the documentation that makes clear that when using an empty sector identifier URI, one single FQDN redirect URI is needed.
(When looking to the code, it is clear for me what is happening, but in production, you normally don't have debug logs or a look to the source code....)
