### ISSUE TITLE
Convert the operator admin secret handling to a dependent resource

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22183]
### Description

Convert the operator admin secret to a dependent resource with the current assumptions - that it's create only and we don't expect to handle any modifications.

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the report and sorry for causing trouble for the benchmark project! Since it was never documented it should work that way, I don't think it needs to be highlighted in the release notes. @shawkins WDYT?

> This change in behavior might be worth a note in the migration guide. It would also be nice to describe how to provide the initial user and password externally - via the supported CR parts preferred.

This will be most probably covered together with #19913.

**Comment by ahus1** [comment]
> I don't think it needs to be highlighted in the release notes.

No need to be sorry. Just some feedback from a frequent user of the nightly builds :-) I leave it up to you on how you want to handle this in regards to release notes.

**Comment by shawkins** [comment]
@ahus1 The related discussion from the PR https://github.com/keycloak/keycloak/pull/22044#issuecomment-1662293898

You could still supply an admin secret, you just need to set the owner reference to the keycloak cr as well.

> Since it was never documented it should work that way, I don't think it needs to be highlighted in the release notes. @shawkins WDYT?

That seems sensible.

**Comment by ahus1** [comment]
> You could still supply an admin secret, you just need to set the owner reference to the keycloak cr as well. In practial terms you would need to scale the operator down before creating the keycloak cr otherwise you'd just be racing against the operator to update the secret. We may eventually support a mechanism to pause reconciliation for a keycloak cr that would make this a little more straight-forward.

As we're deploying the secret and the CR with a helm chart, this wouldn't be straight forward for us (at least I wouldn't know how). Thank your for the alternative. I'll then go with commit this commit for now https://github.com/keycloak/keycloak-benchmark/commit/d0de303ef630656397fe33e4b8b70f3cda0f4c5c

Consider this resolved from my point of view. Thanks!
