### ISSUE TITLE
Avoid warnings "Use <sql> or <modifySql> to re-specify all configuration" when starting Keycloak on MySQL

### ISSUE THREAD

**Issue by jean-christophe-manciot** [keycloak/keycloak#22190]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

The warning message is followed by numerous "Got an error reading communication packets" on the external MySQL server. 
I have no idea how to ```Use <sql> or <modifySql> to re-specify all configuration```.

### Version

nightly

### Expected behavior

No lost communication packets with MySQL server

### Actual behavior

Multiple identical warning messages appear in the debug log:
```
2023-08-02 13:21:30,189 WARN  [liquibase.changelog.DatabaseChangeLog] (main) Due to mysql SQL limitations, modifyDataType will lose primary key/autoincrement/not null/comment settings explicitly redefined in the change. Use <sql> or <modifySql> to re-specify all configuration if this is the case
```
Then the communication with the external MySQL server suffers numerous FIN/RST sent from the keycloak server triggering the same error messages on the MySQL server like:
```
{ "prio" : 3, "err_code" : 10914, "subsystem" : "Server", "source_file" : "sql_connect.cc", "function" : "end_connection", "msg" : "Aborted connection 2123 to db: 'keycloak' user: 'keycloak' host: 'host.example.com' (Got an error reading communication packets).", "time" : "2023-08-02T13:25:46.130882Z", "ts" : 1690982746130, "thread" : 2123, "err_symbol" : "ER_ABORTING_USER_CONNECTION", "SQL_state" : "HY000", "label" : "Note" }
```
What is the workaround?

### How to Reproduce?

On keycloak server 999.0.0:
1. Setting up:
- conf/keycloak.conf
- conf/cache-ispn-tcpping.xml
2. Dropping ```mysql.mysql-connector-java-8.0.33.jar``` (from oracle) into providers
3. Building with:
```
bin/kc.sh build --cache-config-file="cache-ispn-tcpping.xml"
```
4. Starting with:
```
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD='my-password' 
KC_EXTERNAL_ADDR=192.168.122.21 
KC_BIND_ADDR=192.168.122.21 
KC_BIND_PORT=7800 
KC_INITIAL_HOSTS='"192.168.122.21[7800],192.168.122.22[7800]"'

bin/kc.sh start --optimized &
```

### Anything else?

1. The external server is:
mysql-server 8.0.33-0ubuntu0.23.04.4
2. Full first [keycloak.log](https://github.com/keycloak/keycloak/files/12240759/keycloak.log)

**Comment by jean-christophe-manciot** [comment]
There is also a strange message in the log:
```
META-INF/jpa-changelog-master.xml : DBMS Precondition failed: expected db2, got mysql
```

**Comment by jean-christophe-manciot** [comment]
Same issue with ```22.0.1```.

**Comment by ahus1** [comment]
@jean-christophe-manciot - the warnings `Use <sql> or <modifySql>...` you see are intended to the Keycloak developers who add functionality to Keycloak. This is nothing you would configure in any of Keycloak's configuration files.

These warnings have been probably added by Liquibase at some intermediate version. While we're checking with automatic tests that this is not an issue, those are still shown to you as a user. 

Those warnings appear when Keycloak initializes the database for the first time. I hope we'll have time to look into that in a future release. Still they have been reviewed and tested and are not expected to affect Keycloak's functionality. 

I'm adding a "help wanted" flag so the community might pick up this issue before the store team finds the time for this issue. As those database change sets have been written sometimes years ago, and are supposed to be immutable, there is no elegant solution at hand for this.

The log entry "DBMS precondition failed" is a debug message which is intended to analyze the steps Liquibase takes to upgrade the database. As it is a debug message, this is fine, and doesn't affect users.

Related to the MySQL errors you see: Keycloak ships with a MySQL driver which we test. There is no need to provide your own driver. There is actually no officially supported way to exchange a database driver version. Please open a separate issue if those errors persist with the integrated driver. Those message would be expected if you don't shut down Keycloak cleanly.

**Comment by jean-christophe-manciot** [comment]
> There is no need to provide your own driver. There is actually no officially supported way to exchange a database driver version. 

There is a discrepancy between the version of the shipped MySQL driver and the version of the MySQL server:
**8.0.30 vs 8.0.33**

> Please open a separate issue if those errors persist with the integrated driver.

They do, that's why I first tried to insert a suitable driver version in the providers folder.

Cf. https://github.com/keycloak/keycloak/issues/22252
