### ISSUE TITLE
Verification of iss at refresh token request

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#22191]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

Token endpoint doesn't verify the `iss` claims of refresh token while handling a token refresh request.
(Off cause the token endpoint token refresh handler verifies the refresh token is issued from itself or not, so this behavior can be problem only when the domain of Keycloak server is changed.)
It should be noted that the issued access token and refresh token inherits the `iss` claim value from the request's refresh token with invalid `iss` claim value.
Contrary to token refresh, the token introspection endpoint verifies the `iss` claim value.
This will put the client a endless loop of token refresh when Keycloak server domain is changed:
1. After the domain of Keycloak server is changed, when the client request a token refresh with a refresh token with a old `iss` claim value, the Keycloak server issues an access token and refresh token with old `iss` claim value.
2. The client try to use the access token with old `iss` claim, but the introspection endpoint rejects the request.
3. Then, the client try to refresh the tokens with the refresh token, but the issued tokens have old `iss` claim value again.
4. Retry from the step 2 as long as the client doesn't detect the endless loop.

### Version

22.0.1

### Expected behavior

We should verify `iss` at refresh-token request. Will be good to doublecheck if we verify `iss` at other endpoints as well

### Actual behavior

It's possible we're not verifying `iss` at refresh-token request, but we're verifying at introspection-endpoint, which can cause some inconsistencies as described above

### How to Reproduce?

See above

**Comment by rmartinc** [comment]
Better steps of how to reproduce. With an OIDC client with direct access grants enabled:

1. Perform a login using localhost domain:

```bash
curl -vX POST http://localhost:8080/realms/master/protocol/openid-connect/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d username=username -d password=XXXX -d grant_type=password \
  -d scope=openid -d client_secret=YYYYY -d client_id=test-oidc
```
2. You get the refresh token and refresh it using IP 127.0.0.1:

```bash
curl -vX POST http://127.0.0.1:8080/realms/master/protocol/openid-connect/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d client_secret=YYYYY -d grant_type=refresh_token -d client_id=test-oidc \
  -d refresh_token=ZZZZZ
```

This works which is not expected. It should fail as the `iss` claim is different.

3. Call the introspect endpoint with the access token returned in 2 using IP again:

```bash
curl -vX POST http://127.0.0.1:8080/realms/master/protocol/openid-connect/token/introspect \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d client_secret=Z2vKCZGtCiXZbGwUsAGGL20JZSvnrAv3 -d client_id=test-oidc \
  -d token=ZZZZZ
```

This one returns `{"active":false}` and is because `JWT check failed: Invalid token issuer. Expected 'http://127.0.0.1:8080/realms/master', but was 'http://localhost:8080/realms/master'`. We should check `iss`claim in refresh token too and don't allow the refresh.
