### ISSUE TITLE
Browser target for Account Console V3

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#22211]
### Description

Before Account Console V3 becomes the default, make sure Account Console V3 runs on the same browsers as V2.

**Comment by jonkoops** [comment]
I think we should change this issue to a more generic one, which is to determine a minimal browser target for the code we ship, not just the Account Console.

**Comment by ssilvert** [comment]
> I think we should change this issue to a more generic one, which is to determine a minimal browser target for the code we ship, not just the Account Console.

Feel free to open a new issue for that.  I want this issue as-is just to make sure we are ready for Account Console V3 to become the default in Keycloak 23.

**Comment by jonkoops** [comment]
@ssilvert see #22266
