### ISSUE TITLE
Convert RealmImport logic to dependent resources

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22223]
### Description

The realm import secret and job should be converted to dependent resources.

**Comment by shawkins** [comment]
There appears to be a performance regression with running the local tests: https://github.com/keycloak/keycloak/actions/runs/5927179684/job/16070891213?pr=22299

It may be related to the additional overhead of logging the full realm secret into the console - as the remote tests do not seem to have the same issue.  If this does turn out to be the problem, it has already been addressed by upstream changes in the operator sdk.

**Comment by vmuzikar** [comment]
@shawkins Can you please open a separate issue for the perf regression rather than reopening this one? That'd help us track it more easily. Thanks.
