### ISSUE TITLE
Unable to update realm settings after adding an identity provider

### ISSUE THREAD

**Issue by mehle** [keycloak/keycloak#22234]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I am unable to update realm settings after configuring a SAML identity provider in that realm. This is reproducible on v21, v22, and the latest nightly. 

When observing the API call, I see a 403. However, this does not appear to be a role or permissions issue, as every other real admin page works using the same set of roles and I am able to view and navigate the main realm settings. This issue also disappears if I remove the identity provider configuration.

Things I have tried:

- Updating a different realm without a configured IDP (works)
- Removing the SAML identity provider (works)
- Update any other settings within the realm (works)
- Tried both local and LDAP federated admin (does not work)
- Adding the SAML identity provider back (does not work)
- Checked roles (looks correct)
- Enabled debug logs (nothing relevant appears)
![tempsnip](https://github.com/keycloak/keycloak/assets/1180889/5b8dd775-813b-49e1-a65e-b5087d747829)

### Version

22.0.1

### Expected behavior

I should be able to update the main realm settings when an identity provider is configured in that realm.

### Actual behavior

I get a message saying the the realm could not be updated. Network trace shows a 403 response on the respective API call.

### How to Reproduce?

On a KC installation, create a new realm and add a SAML IDP. Then try to update the realm settings.

### Anything else?

This is a fairly vanilla KC installation. We have configured LDAP federation and a single realm with a couple of clients and a single SAML IDP. All administrators are defined by roles in the master realm.

The issue seems similar to https://github.com/keycloak/keycloak/issues/14851, except that we have only configured a single identity provider.

**Comment by sschu** [comment]
@mehle And you don't have a firewall in front that for example filters traffic according to OWASP rules or something like that?

**Comment by mehle** [comment]
No, but I forgot to mention that we do have a proxy. Very simple AWS ALB setup that round robins between two KC servers. Another troubleshooting step was to take one out of the rotation in case it was a persistence issue.

**Comment by mehle** [comment]
On a hunch based on your last comment, I decided to try this while bypassing ALB, and it worked!

The proxy settings are pretty straightforward, and this is the first real issue I have seen from it. I'll do a little more digging and see if I can refine this issue further.

**Comment by mehle** [comment]
Upon further investigation, a WAF was enabled on the ALB without my awareness, and disabling it resolved the issue. Very interesting that it only applied the block when an external SAML IDP was configured in the realm. It must add something in the realm settings PUT request that the WAF didn't like.

I'll go ahead and close this since it isn't a valid KC issue. Hopefully this will be useful to anyone else who runs into the same problem. Thank you for your suggestion and help.
