### ISSUE TITLE
context.getSession().users().getUserById(context.getRealm(), userid) not found user ...

### ISSUE THREAD

**Issue by mcarbonneaux** [keycloak/keycloak#22232]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

i've made a user storage provider base on quickstart jpa user storage.
it's work in admin interface i can navigate in user interface and it's work with username password form...
i've made an authenticator that take the userid by header (reverseproxy infrastructure set the header), and i try to search the user by id in the authenticator.
i've found in many authenticator this syntax to search a user by id in authenticate method...
```
UserModel existingUser = context.getSession().users().getUserById(context.getRealm(), actionTokenUserId);
```

when i try my authenticator... he execute the search for the user but not on my user storage, only in the postgresql storage (i've activated the jpa sql debug)...

### Version

21.1.2

### Expected behavior

```
UserModel existingUser = context.getSession().users().getUserById(context.getRealm(), actionTokenUserId);
```

execute my user storage for searching the user...

### Actual behavior

user not found because is not in the postgresql keycloak storage...
```
UserModel existingUser = context.getSession().users().getUserById(context.getRealm(), actionTokenUserId);
```

### How to Reproduce?

use the quickstart jpa storage plus an authenticator that search the userbyid with ....
```
UserModel existingUser = context.getSession().users().getUserById(context.getRealm(), actionTokenUserId);
```
 in authenticate method...

### Anything else?

i canot reproduce with main/22 because of the impact of introducing jakarta and new quarkus....

**Comment by mcarbonneaux** [comment]
i found why... the user id that i pass to getUserById is the externalid not keycloak storage id...
and he dont call the user storage provider...

there a way to get the user storage provider id from Authenticator ?

for the moment i've modified my authenticator to usegetUserByUsername and i've modifier my getUserByUsername to work with id and username....

**Comment by rmartinc** [comment]
@mcarbonneaux The [getUserById](https://github.com/keycloak/keycloak/blob/22.0.4/model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L362-L373) does not iterate over the different storages. The idea is that the user retrieved from the external storage is using a special id `f:<storage-id>:<user-id>` and that method goes directly to the storage to retrieve the UserModel. Other methods like [getUserByUsername](https://github.com/keycloak/keycloak/blob/22.0.4/model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L382-L383) does the iteration.

The authenticator more or less locates the user via username, email or whatever, then sets the user in the authentication context. So if you have the id somehow you can directly search in your storage creating a [StorageId](https://github.com/keycloak/keycloak/blob/22.0.4/server-spi/src/main/java/org/keycloak/storage/StorageId.java#L46). But then the ID is search directly over the provider Id passed, it never iterates.

**Comment by pedroigor** [comment]
Closed as explained. @mcarbonneaux The instructions from @rmartinc should be enough to properly fetch federated users by id.
