### ISSUE TITLE
Docs do not state explictly that H2 should not be used in production

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#22231]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

docs

### Describe the bug

Keycloak's embedded H2 database shouldn't be used for production setups. 

The new docs don't state this explicitly, but only implicitly: 

https://www.keycloak.org/server/configuration-production: "For details on how to configure a supported database, see Configuring the database."

https://www.keycloak.org/server/db: Lists supported databases, but doesn't explicitly name hat H2 is not supported. 

The Wildfly distribution had the following text as part of the server installation guide, which is more explicit (but only little): 

> Keycloak comes with its own embedded Java-based relational database called H2. This is the default database that Keycloak will use to persist data and really only exists so that you can run the authentication server out of the box. We highly recommend that you replace it with a more production ready external database. The H2 database is not very viable in high concurrency situations and should not be used in a cluster either. The purpose of this chapter is to show you how to connect Keycloak to a more mature database.

### Version

main

### Expected behavior

Add a similar hint about H2 to the new docs.

### Actual behavior

There is no hint about H2 in the docs.

### How to Reproduce?

See links above

### Anything else?

This needs to be backported to KC22

**Comment by ahus1** [comment]
@andymunro - could you please advise where would be good place to add this information from a documentation point of view? Thanks!

**Comment by andymunro** [comment]
I think this should be in the Supported Database section of this topic:  https://www.keycloak.org/server/db
It lists what is supported, but we also mention that H2 is NOT supported, but you can use it for testing.

**Comment by stianst** [comment]
`H2` is intentionally not mentioned in the guide, as we don't support `H2` directly, but rather as an implementation detail of `db=dev-file`. The idea here is that we could change `dev-file` to use something else in the future (real files, or a different embedded db) without it being a breaking change.

From my perspective I don't think we should explicitly mention `H2` at all in the docs, and it's fine as it stands.

**Comment by ahus1** [comment]
Ok, then let's close it.
