### ISSUE TITLE
Add Identity Provider page not show the import button as previous. 

### ISSUE THREAD

**Issue by xdinko** [keycloak/keycloak#22249]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the Identity providers -> Add Provider Pages (Like SAML or custom) the import button and custom field not are present in the new keycloak.v2 theme, if you use the base theme all exists and work fine.
Please fix on the theme for getting use the 22.0.x version of keycloak

### Version

22.0.1

### Expected behavior

The import button and the custom field are visible.

### Actual behavior

The import button and the custom field are not present.

### How to Reproduce?

Go to Identity providers -> Add SAML provider

**Comment by edewit** [comment]
You mean this button?
![image](https://github.com/keycloak/keycloak/assets/51133/5635fc08-a196-4391-9a4a-add8fb03e6f2)

**Comment by edewit** [comment]
When you switch the `Use entity descriptor` switch you get these fields
![image](https://github.com/keycloak/keycloak/assets/51133/24c50abe-eb70-496e-a727-0669b2729224)
