### ISSUE TITLE
HEAD http request gives protocol error when http/2 protocol is used

### ISSUE THREAD

**Issue by sujaykulkarn** [keycloak/keycloak#22246]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

Hi Keycloak team, 

Observing one strange behavior with keycloak when we pass HEAD request with http/2 network protocol. In the response, we are getting protocol errors. 
Issue is seen only with HEAD request not with GET request.

`
~$ curl -vk -I  https://localhost:8443
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=initcert
*  start date: Dec 23 17:38:21 2022 GMT
*  expire date: Dec 20 17:38:21 2032 GMT
*  issuer: C=AA; ST=AA; L=AA; O=AA; OU=AA; CN=BCMT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x7fffcdbc6550)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> **HEAD / HTTP/2**
> Host: localhost:8443
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* **HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)**
* stopped the pause stream!
* Connection #0 to host localhost left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

The same request works fine with http/1.1 network protocol.

`
~$ curl -vk -I --http1.1 https://localhost:8443
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=initcert
*  start date: Dec 23 17:38:21 2022 GMT
*  expire date: Dec 20 17:38:21 2032 GMT
*  issuer: C=AA; ST=AA; L=AA; O=AA; OU=AA; CN=BCMT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> **HEAD / HTTP/1.1**
> Host: localhost:8443
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Referrer-Policy: no-referrer
Referrer-Policy: no-referrer
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000; includeSubDomains
Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Robots-Tag: none
X-Robots-Tag: none
< Cache-Control: no-cache, must-revalidate, no-transform, no-store
Cache-Control: no-cache, must-revalidate, no-transform, no-store
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< Content-Security-Policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
Content-Security-Policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
< Set-Cookie: WELCOME_STATE_CHECKER=dV0wBEHrC2vVmGkfzXHHz_FhclMUGXNv_hVcpyZrv0A; Version=1; Expires=Fri, 04-Aug-2023 09:03:18 GMT; Max-Age=300; Path=/; Secure; HttpOnly
Set-Cookie: WELCOME_STATE_CHECKER=dV0wBEHrC2vVmGkfzXHHz_FhclMUGXNv_hVcpyZrv0A; Version=1; Expires=Fri, 04-Aug-2023 09:03:18 GMT; Max-Age=300; Path=/; Secure; HttpOnly
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< Content-Type: text/html;charset=utf-8
Content-Type: text/html;charset=utf-8
< connection: keep-alive
connection: keep-alive

<
* Connection #0 to host localhost left intact
`

Our guess is in http/1.1 response we see "connection: keep-alive" in this header as the response to the HEAD request. Is this header causing the http/2 request to fail, Because in http/2 connection headers are not allowed. Refer - https://httpwg.org/specs/rfc7540.html#n-connection-specific-header-fields 

### Version

22.0.1

### Expected behavior

HEAD http requests should pass with http/2 protocol similar to the http/1.1 

As mentioned in this link - https://httpwg.org/specs/rfc7540.html#n-connection-specific-header-fields

"HTTP/2 does not use the Connection header field to indicate connection-specific header fields; in this protocol, connection-specific metadata is conveyed by other means. An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields; any message containing connection-specific header fields MUST be treated as malformed" 

### Actual behavior

HEAD http requests are failing with http/2 protocol. 

`
~$ curl -vk -I  https://localhost:8443
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=initcert
*  start date: Dec 23 17:38:21 2022 GMT
*  expire date: Dec 20 17:38:21 2032 GMT
*  issuer: C=AA; ST=AA; L=AA; O=AA; OU=AA; CN=BCMT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x7fffcdbc6550)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> **HEAD / HTTP/2**
> Host: localhost:8443
> user-agent: curl/7.81.0
> accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* **HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)**
* stopped the pause stream!
* Connection #0 to host localhost left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
`
As mentioned in this link if some connection header comes in the response of a HEAD request for http/2 protocol. Then it will consider it as Malformed Request or Response and throw a PROTOCOL_ERROR. 

References - https://httpwg.org/specs/rfc7540.html#n-connection-specific-header-fields
https://httpwg.org/specs/rfc7540.html#malformed

### How to Reproduce?

Steps to Reproduce: 

1. Take any latest curl request where the default protocol it takes as http/2. We are using 7.81.0 (curl 7.81.0 (x86_64-pc-linux-gnu)) 
2. Install latest Keycloak in secure mode.
3. Send HEAD request - "curl -vk -I  https://localhost:8443" - Here -I send a HEAD request. 
In response, you will see PROTOCOL_ERROR

### Anything else?

https://httpwg.org/specs/rfc7540.html#n-connection-specific-header-fields
https://httpwg.org/specs/rfc7540.html#malformed

**Comment by pedroigor** [comment]
@sujaykulkarn Could you please try latest? Could not reproduce using a nightly build, probably due to upgrades to Quarkus and how it is handling HTTP/2.

```
pedroigor@fedora:/tmp/keycloak-999.0.0-SNAPSHOT/bin$ curl -vk -I https://localhost:8543
* processing: https://localhost:8543                    
*   Trying [::1]:8543...                        
* Connected to localhost (::1) port 8543        
* ALPN: offers h2,http/1.1                   
* TLSv1.3 (OUT), TLS handshake, Client hello (1):                                                                      
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):                                                                                                                                                                                                 
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1): 
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384                                                                
* ALPN: server accepted h2                                                                                             
* Server certificate:
*  subject: C=BR; ST=DF; L=Brasilia; O=MuneraSoft.io; OU=Operations; CN=keycloak.apps.munerasoft.com; emailAddress=contact@munerasoft.com
*  start date: Jul 21 12:18:39 2018 GMT
*  expire date: Jul 31 12:18:39 2019 GMT
*  issuer: C=BR; ST=DF; O=MuneraSoft.io; CN=MuneraSoft.io Intermediate CA; emailAddress=contact@munerasoft.com
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/2    
* h2 [:method: HEAD]
* h2 [:scheme: https]
* h2 [:authority: localhost:8543]
* h2 [:path: /]         
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1                                 
> HEAD / HTTP/2
> Host: localhost:8543
> User-Agent: curl/8.2.1                                                                                               
> Accept: */*                                                                                                          
>                                                                                                                      
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):                                                                  
< HTTP/2 200                           
HTTP/2 200                           
< cache-control: no-cache, must-revalidate, no-transform, no-store
cache-control: no-cache, must-revalidate, no-transform, no-store
< content-security-policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
content-security-policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
< content-type: text/html;charset=utf-8
content-type: text/html;charset=utf-8
< referrer-policy: no-referrer
referrer-policy: no-referrer
< strict-transport-security: max-age=31536000; includeSubDomains
strict-transport-security: max-age=31536000; includeSubDomains
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< x-robots-tag: none                         
x-robots-tag: none
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block

< 
* Connection #0 to host localhost left intact
```

**Comment by pedroigor** [comment]
Feel free to re-open if you have more steps to reproduce the issue.

**Comment by sujaykulkarn** [comment]
Hi @pedroigor, 
Thanks, it's working with the latest release. 
Need your suggestion for one more request, I am trying to restrict a few HTTP method(OPTION/HEAD) requests against certain admin API's endpoints, is there a way I can achieve this? Or any Quarkus configuration you are aware of that does the job. Appreciate your help here. 

Thanks.
