### ISSUE TITLE
Oder of Stylesheets undermines patternfly

### ISSUE THREAD

**Issue by triick17** [keycloak/keycloak#22250]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

The order in which the stylesheets are imported is messed up In the default login-template.

Patternfly 4 styles are not correctly applied, since the old styles from patternfly.min.css (I think this is patternfly 3), styles are applied. I.e. it is not possible to make proper use of the CSS Variables, since there are not applied. I didn't check all implications this wrong import has. There might be some other issues caused by this. 

See the rule having a too high specificity (due to import order) here:

<img width="1311" alt="Screenshot 2023-08-04 at 12 26 01" src="https://github.com/keycloak/keycloak/assets/25704193/1f1d9315-d0b7-4fd1-8ab6-bf8751ab1d61">

### Version

22.0.1

### Expected behavior

It is possible to e.g. change the font with the supplied patternfly CSS-variable. Add a custom theme and define a font e.g. --pf-global--FontFamily--sans-serif: Barlow. The login page is now displays in "Barlow" font.

### Actual behavior

The changes are not applied. The Font does not change.

### How to Reproduce?

Define --pf-global--FontFamily--sans-serif: <yourfont> somewhere in an additional stylesheet.

**Comment by ssilvert** [comment]
I'm of the opinion that we should not fix this because we will soon be using PatternFly 5 throughout.

@jonkoops Do you agree?

**Comment by jonkoops** [comment]
Yes, this should be resolved once we move everything over to PatternFly 5. We will be removing all older PatternFly styling in the process. See #21321 to track the progress on this.
