### ISSUE TITLE
Usage of ProviderConfigProperty.MAP_TYPE in custom protocol mapper: Not filled with items on admin UI after reload

### ISSUE THREAD

**Issue by thletze** [keycloak/keycloak#22286]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Usind a propery configuration for a map in a custom protocol mapper provider (OIDC) like this:

`configProperties.add(new ProviderConfigProperty("teams-uuid-mappings", "Teams UUID mapping", "Mapping table for team names from IDP (Key) to Team UUID (Value).", ProviderConfigProperty.MAP_TYPE, null));`

The mapping values can be entered when the config page is rendered, they are stored and can be retrieved by the protocol mapper at runtime. But when the config page is reloaded the current mapping rows are not shown in the map component.

The actual data ia available in the API response when accessing the config page.

### Version

22.0.1 (latest Docker image)

### Expected behavior

For MAP_TYPE properties current values of map rows should be shown when accessing the config page for a custom protocol mapper in admin UI.

### Actual behavior

Entering new map rows is possible, they are stored and available in the protocoll mapper.

Changing of a single map rows not possible since no data is displayed in the map component after reloading the page. To change something one have to enter the complete mapping over again.

### How to Reproduce?

- Create a custom OIDC protocol mapper provider using a map as a custom property like this one:
  `configProperties.add(new ProviderConfigProperty("teams-uuid-mappings", "Teams UUID mapping", "Mapping table for team names from IDP (Key) to Team UUID (Value).", ProviderConfigProperty.MAP_TYPE, null));`
- Add custom OIDC protocol mapper provider to Keycloak.
- Add custom OIDC protocol mapper to a client scope
- Access configuration page for created OIDC protocol mapper
- Enter 1-n mapping rows and save configration
- Leave configuration page
- Access configuration page again, no rows are dispayed in map component

### Anything else?

The actual data is available and send to the browser during the API call when the config page is loaded:

```
{
    "id": "73f1eba3-3c78-4f4b-8604-075b3e8a0fa1",
...
    "config": {
...
        "teams-uuid-mappings": "[{\"key\":\"foo1\",\"value\":\"bar1\"},{\"key\":\"foo2\",\"value\":\"bar2\"},{\"key\":\"foo3\",\"value\":\"bar3\"}]",
...
    }
}
```
During further debugging in theJavaScript code of Admin-UI I got the impression that all UI componets incl. the MapComponent are rendered before the properties are actually set in the form.

It occures to me that all other UI components are updating itself after a new value is set but the MapComponent doesn't.

But that's just a wild guess. :-)

**Comment by ssilvert** [comment]
@thletze I apologize that we have not followed up on this sooner.  

Do you still want us to look into it?  If so, can you provide the custom OIDC protocol mapper provider to help us reproduce the issue?

**Comment by thletze** [comment]
@ssilvert Thanks for coming back on this.

Yes it would be very kind if you can look into this. The issue still exists in Keycloak 22.0.4. To reproduce this I created a sample OIDC protocol mapper provider here: https://github.com/thletze/oidc-mapper

Steps to reproduce:

1. Add custom protocol mapper to any OIDC client and open the configuration page in admin UI.
2. Add some mapping value rows, e.g. key1 -> value1; key2 -> value2;...
3. Specify token claim name
4. Tick some "Add to .... token" switches to "On"
5. Hit save to store configuration
6. Check configuration with "Client scopes/Evaluate" for any user and the choosed token type, ther should be some claim added containing the JSON representation of the entered mapping values like: "test": "[{\"key\":\"key1\",\"value\":\"value1\"},{\"key\":\"key2\",\"value\":\"value2\"}]"
7. Open mapper configuration UI again, the current mapping table would not show the entered values anymore.

Hope this helps to fix this.

**Comment by ssilvert** [comment]
@thletze I tried your custom mapper on the latest UI code and it seems to be working as expected.  I added your "MapType config Mapper Example" to the dedicated scope then added two attributes for "Mapping Example".  I go to "Evaluate" and pick a user.  Then I look at Generated ID token and see the claim.  Then I went back to the mapper configuration and all the values I entered were still there.

**Comment by thletze** [comment]
Hi @ssilvert, thanks for trying. I checked the the custom mapper against the latest nightly docker image too and it worked as expected. The issue can be closed.

Thx again for your support.
