### ISSUE TITLE
Attributes disappear in UI after renaming group

### ISSUE THREAD

**Issue by transducer** [keycloak/keycloak#22284]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Reopened from [21438](https://github.com/keycloak/keycloak/issues/21438).

After the action "Rename group" on the Group Details page, the attributes of that group are no longer visible in the UI. They reappear after a refresh.

![attributes disappear](https://github.com/keycloak/keycloak/assets/5002921/f66f541e-d807-4ad0-ac5c-df688ac1aa11)

### Version

22.0.1

### Expected behavior

Attributes are still visible in the UI after renaming a group.

### Actual behavior

The attributes are no longer visible in the UI after renaming a group.

### How to Reproduce?

1. Create a group
1. Add an attribute to that group in the UI
1. Click on action "Rename group"
1. Give the group a new name
1. Press "Rename"
1. View attributes in UI, they are gone
1. Refresh page, attributes are visible again

### Anything else?

Same issue as https://github.com/keycloak/keycloak/issues/21438, but I can not reopen. The fix did not solve it.

**Comment by ssilvert** [comment]
@transducer I can't reproduce this in the latest [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).  I trust you are saving the attribute before you rename?

Can you give the [nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) a try?

**Comment by jonkoops** [comment]
Closing this due to lack of response, if the issue persists let us know.

**Comment by transducer** [comment]
> I trust you are saving the attribute before you rename?

Yes. I save the attribute than rename the group, as shown in the attached gif.

> Closing this due to lack of response, if the issue persists let us know.

I have not checked with recent nightly release (other tickets with higher priority for us at the moment). Will let you know when I get to it and if issue persists. Thank for the efforts.

**Comment by transducer** [comment]
@jonkoops the issue is fixed! thanks a lot!

**Comment by jonkoops** [comment]
Great! Thanks for verifying this.
