### ISSUE TITLE
URLs with custom protocols fail "Trusted Hosts" validation

### ISSUE THREAD

**Issue by t0xicCode** [keycloak/keycloak#22309]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

When anonymous client-registration is enabled with verification of client URIs, The verification fails with a "URL is malformed" error (`MalformedUrlException`).

In my case, the thing trying to do client registration is a phone application with a "custom"/non-standard protocol handler.

Because `TrustedHostClientRegistrationPolicy` tries to parse the client's redirect URI as an URL, any scheme that doesn't have a matching handler in Java will cause a `MalformedUrlException`.

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java#L217
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicy.java#L223

### Version

22.0.0

### Expected behavior

The validation passes and the new client is added.

### Actual behavior

The client registration is denied with an error message:

```json
{"error":"insufficient_scope","error_description":"Policy 'Trusted Hosts' rejected request to client-registration service. Details: URL is malformed"
```

### How to Reproduce?

1. Disable `Host Sending Client Registration Request Must Match` and enable `Client URIs Must Match` in the _Trusted Hosts_ client registration policy.
2. Add a `Trusted Host` entries with "custom" protocols and save the policy.
    e.g. `ios.owncloud.com`
4. Issue a POST request to `/realms/<realm-id>/clients_registration/openid-connect` with a valid payload:
    ```json
   {"application_type":"native","token_endpoint_auth_method":"client_secret_basic","redirect_uris":["oc://ios.owncloud.com"],"client_name":"ownCloud/iOS 12.0.2"}
    ```

### Anything else?

Seems like the issue would be fixed with switching to the URI class (at least for the `redirect_uri`s).

**Comment by rmartinc** [comment]
@t0xicCode Yes, I think that you are right, the policy doesn't allow custom protocols because it's using a URL to check their validity. I have investigated the file history and this is coded this way since the beginning. I'm adding it to the backlog and adding help wanted to the issue. If someone wants to work on this it would be much appreciated.

**Comment by t0xicCode** [comment]
I’ve created a PR that fixes the behaviour by using URI where custom
schemes are permitted.
