### ISSUE TITLE
wrong chinese translation

### ISSUE THREAD

**Issue by techzhou** [keycloak/keycloak#22313]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Wrong Chinese translation
https://github.com/keycloak/keycloak/blob/490016569164086a8c2040faac51ef060bf7b277/js/apps/admin-ui/public/locales/zh-CN/users.json#L38

lastName & firstName misplace 

see  https://github.com/keycloak/keycloak/blob/490016569164086a8c2040faac51ef060bf7b277/js/apps/admin-ui/public/locales/zh-CN/roles.json#L65

### Version

22.0.1

### Expected behavior

"lastName": "姓",
"firstName": "名",

### Actual behavior

"lastName": "名",
"firstName": "姓",

### How to Reproduce?

in user management

**Comment by xianli123** [comment]
@techzhou @edewit  thanks for your correction. I found @edewit has changed them. It looks good.
