### ISSUE TITLE
Keycloak v22: Custom Identity Provider configuration page 

### ISSUE THREAD

**Issue by Slixe** [keycloak/keycloak#22325]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Hey there,
Thanks to Keycloak v22 now we can have access to custom config provided by the plugin (even if Client Secret & Client ID are still mandatory yet but if I remember correctly, should be fix in coming updates)

![image](https://github.com/keycloak/keycloak/assets/22432874/aa620fc6-a0f7-4fd3-8a9e-abcb0c0b9879)

The bug come from the fact that when we created our Custom Identity Provider, we are not able to configure it again, as config properties provided by the Custom Identity Provider aren't applied for the configuration page of a Identity Provider (and Client Secret & Client ID are still present).

![image](https://github.com/keycloak/keycloak/assets/22432874/ff22d0e7-d9d6-4306-b872-5294049bf3b5)

### Version

22.0.1

### Expected behavior

That the config properties provided by the plugin are also shown in the configuration page of a existing Identity Provider.

### Actual behavior

Default configuration is available

### How to Reproduce?

Create a custom IdP, implements `ConfiguredProvider` interface and provide a custom config properties.
It will be shown in "Add a new Provider" but not available anymore when trying to configure an existing one.

You can also try using this plugin CAS: https://github.com/RoboJackets/keycloak-cas

**Comment by kberzinch** [comment]
I believe this was fixed in #21776, just not released yet.

**Comment by Slixe** [comment]
Client ID and Client Secret now, and by rebuilding my nightly image its now appearing.

I close it as well as I see it in nightly now.

Thanks
