### ISSUE TITLE
Selecting resource on resource based permission gives error

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#22332]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When selecting a resource from the dropdown when creating a "resource based permission gives an error:
![image](https://github.com/keycloak/keycloak/assets/51133/c95f3cb7-6bf3-40a9-9fcb-9ccf6ee04847)

### Version

main

### Expected behavior

It should select the resource instead

### Actual behavior

error shown

### How to Reproduce?

Go to client details -> Authorisation -> Permissions -> Create resource based permission and select an resource from the dropdown.

**Comment by jonkoops** [comment]
This fixes a bug that was present in `main`, but is not part of the v22 release. I will go ahead and remove this from the patch release.
