### ISSUE TITLE
Keycloak 15.11 image issue. (*** JBossAS process (334) received TERM signal ***)

### ISSUE THREAD

**Issue by VikasCarscan** [keycloak/keycloak#22338]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/wildfly

### Describe the bug

We have deployed keycloak 15.11 docker image with mariadb backend to our production. The image is deployed on a kubernetes pod. Recently we are observing that we are getting the following exception post which the instance is shutting down and getting restarted again. Attaching the entire stacktrace for reference
*** JBossAS process (334) received TERM signal ***
08:42:58,954 INFO  [org.jboss.as.server] (Thread-1) WFLYSRV0272: Suspending server
08:42:58,956 INFO  [org.jboss.as.ejb3] (Thread-1) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
08:42:58,959 INFO  [org.jboss.as.server] (Thread-1) WFLYSRV0220: Server shutdown has been requested via an OS signal
08:42:59,018 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0010: Unbound data source [java:jboss/datasources/KeycloakDS]
08:42:59,038 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 62) Stopping cache manager null on keycloak-75f869645c-llqb8
08:42:59,040 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 62) ISPN000080: Disconnecting JGroups channel ejb
08:42:59,060 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-2) WFLYMAIL0002: Unbound mail session [java:jboss/mail/Default]
08:42:59,062 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 62) Stopping cache manager null on keycloak-75f869645c-llqb8
08:42:59,061 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 68) Stopping cache manager null on keycloak-75f869645c-llqb8
08:42:59,069 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0008: Undertow HTTPS listener https suspending
08:42:59,070 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 62) ISPN000080: Disconnecting JGroups channel ejb
08:42:59,071 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 0.0.0.0:8443
08:42:59,075 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 68) ISPN000080: Disconnecting JGroups channel ejb
08:42:59,088 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 71) WFLYUT0022: Unregistered web context: '/auth' from server 'default-server'
08:42:59,089 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0019: Stopped Driver service with driver-name = mariadb
08:42:59,120 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
08:42:59,121 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0019: Host default-host stopping
08:42:59,125 INFO  [org.jboss.modcluster] (ServerService Thread Pool -- 71) MODCLUSTER000002: Initiating mod_cluster shutdown
08:42:59,114 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0008: Undertow AJP listener ajp suspending
08:42:59,141 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0007: Undertow AJP listener ajp stopped, was bound to 0.0.0.0:8009
08:42:59,144 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0019: Stopped Driver service with driver-name = h2
08:42:59,176 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 70) WFLYCLINF0003: Stopped clientSessions cache from keycloak container
08:42:59,177 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 70) WFLYCLINF0003: Stopped actionTokens cache from keycloak container
08:42:59,201 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 68) WFLYCLINF0003: Stopped authorization cache from keycloak container
08:42:59,203 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 68) WFLYCLINF0003: Stopped offlineSessions cache from keycloak container
08:42:59,205 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 62) WFLYCLINF0003: Stopped work cache from keycloak container
08:42:59,206 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 68) WFLYCLINF0003: Stopped authenticationSessions cache from keycloak container
08:42:59,211 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 71) WFLYCLINF0003: Stopped offlineClientSessions cache from keycloak container
08:42:59,214 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 72) WFLYCLINF0003: Stopped sessions cache from keycloak container
08:42:59,215 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 68) WFLYCLINF0003: Stopped keys cache from keycloak container
08:42:59,223 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0008: Undertow HTTP listener default suspending
08:42:59,223 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 69) WFLYCLINF0003: Stopped users cache from keycloak container
08:42:59,223 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 0.0.0.0:8080
08:42:59,238 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0028: Stopped deployment keycloak-server.war (runtime-name: keycloak-server.war) in 277ms
08:42:59,248 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 62) WFLYCLINF0003: Stopped http-remoting-connector cache from ejb container
08:42:59,252 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 73) WFLYCLINF0003: Stopped loginFailures cache from keycloak container
08:42:59,254 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0004: Undertow 2.2.5.Final stopping
08:42:59,258 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 62) Stopping cache manager null on keycloak-75f869645c-llqb8
08:42:59,259 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 62) ISPN000080: Disconnecting JGroups channel ejb
08:42:59,299 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 70) WFLYCLINF0003: Stopped realms cache from keycloak container
08:42:59,301 INFO  [org.infinispan.manager.DefaultCacheManager] (ServerService Thread Pool -- 70) Stopping cache manager null on keycloak-75f869645c-llqb8
08:42:59,346 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 70) ISPN000080: Disconnecting JGroups channel ejb
08:42:59,391 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: Keycloak 15.1.1 (WildFly Core 15.0.1.Final) stopped in 428ms
*** JBossAS process (334) received TERM signal ***

### Version

15.11

### Expected behavior

The pod should not restart periodically.

### Actual behavior

The pod is getting restarted every 30 minutes

### How to Reproduce?

The service automatically reboots every 30 minutes when it receives a TERM signal interrupt to stop its service

**Comment by sschu** [comment]
This just means that the pod gets stopped by Kubernetes. There could be multiple reasons for that but one common cause could be that it is OOMkilled because the pods. What is your memory configuration for Keycloak? Also you can read https://medium.com/codex/how-to-diagnose-oomkilled-error-in-kubernetes-application-201a9966be0d to find out if OOMKill is your issue.

**Comment by VikasCarscan** [comment]
Thanks for the reply. The following is our helm config for kubernetes
```
resources:
  requests:
    cpu: "500m"
    memory: "2000Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"
```

On logging into keycloak the server info shows that it has 86% free space. What is the ideal configuration that you would recommend

**Comment by VikasCarscan** [comment]
Can you let me know how can I confirm if it is OOMkill, what commands to run on the cluster ?.

**Comment by sschu** [comment]
Just check the link I posted in my previous reply.

**Comment by VikasCarscan** [comment]
I see these events logs in my kubernetes :

16m         Normal    Pulling                   pod/keycloak-75f869645c-h9nfg                     Pulling image "jboss/keycloak:15.1.1"
16m         Normal    Pulled                    pod/keycloak-75f869645c-h9nfg                     Successfully pulled image "jboss/keycloak:15.1.1" in 2.511134765s
16m         Normal    Created                   pod/keycloak-75f869645c-h9nfg                     Created container keycloak
16m         Normal    Started                   pod/keycloak-75f869645c-h9nfg                     Started container keycloak
10m         Normal    ScaleDown                 pod/keycloak-75f869645c-h9nfg                     deleting pod for node scale down
10m         Normal    Killing                   pod/keycloak-75f869645c-h9nfg                     Stopping container keycloak
57m         Normal    ScaleDown                 pod/keycloak-75f869645c-hh2nm                     deleting pod for node scale down
57m         Normal    Killing                   pod/keycloak-75f869645c-hh2nm                     Stopping container keycloak
57m         Warning   FailedKillPod             pod/keycloak-75f869645c-hh2nm                     error killing pod: failed to "KillContainer" for "keycloak" with KillContainerError: "rpc error: code = Unknown desc = Error response from daemon: No such container: 8c16ecead2bb52b7eee7d3991ca1b2fcf15016ade91810cb2bcc1215629ea5e9"

**Comment by sschu** [comment]
For me it looks like you are using the cluster-autocaler which removed a node from your cluster thus stopping the Keycloak pod on the node. That is pretty normal behaviour when you are running with the autoscaler.

**Comment by vmuzikar** [comment]
@VikasCarscan Thanks for reporting this and sorry you are facing issues. I noticed you are using quite old Keycloak version which we don't support anymore. Please consider upgrading and feel free to reopen the issue if it's still valid with the latest version.
