### ISSUE TITLE
kc.sh errors if using characters like semicolon inside the arguments

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak#22337]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

There are errors when using the `kc.sh` script if the parameters contain problematic characters like semicolon `;`. One easy example is the mssql `db-url`:

```bash
./kc.sh start --db=mssql --hostname=localhost --db-username=keycloak "--db-url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=keycloak;integratedSecurity=false;trustServerCertificate=true;encrypt=No;sendStringParametersAsUnicode=false" "--db-password=Keycloak01!" --transaction-xa-enabled=false
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2023-08-09 10:47:01,142 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 2988ms
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Next time you run the server, just run:

	kc.sh start --optimized --hostname=localhost --db-username=keycloak --db-url=jdbc:sqlserver://127.0.0.1:1433

./kc.sh: line 128: --db-password=Keycloak01!: command not found
```

If you see the semicolon is breaking the line and the rest of parameters are not taken into account. I think we need to quote `${VAR@Q}` the arguments in the script. I suppose there can be other errors with passwords and so on if they contain problematic chars like `$"` or similar.

As a workaround you can use the `keycloak.conf` of env variables to pass the options.

### Version

22.0.1

### Expected behavior

The `kc.sh` should work OK and the chars should be escaped/quoted.

### Actual behavior

Errors in `kc.sh`.

### How to Reproduce?

See the example execution in the description.

**Comment by rmartinc** [comment]
I have been investigating and this issue is complicated, fixing it means possibly issues with current used boot commands. The main problem is that the parameters are really interpreted twice. Each parameter is checked and then re-added to the [CONFIG_ARGS variable](https://github.com/keycloak/keycloak/blob/22.0.1/quarkus/dist/src/main/content/bin/kc.sh#L70) and interpreted again via [eval](https://github.com/keycloak/keycloak/blob/22.0.1/quarkus/dist/src/main/content/bin/kc.sh#L140). This means that normal escaping of the parameters doesn't work, because you need to consider it is going to happen twice. For example, imagine the mssql `db-url` parameter is `jdbc:sqlserver://127.0.0.1:1433;DatabaseName=keycloak;a=b`. Using double quotes should be enough for the shell:

```bash
"--db-url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=keycloak;a=b"
```

But as the parameter is interpreted twice, the first time quotes are OK, but the second time the semicolon is not escaped. The issue described in this issue happens in this case. That's the reason why people are using weird things like:

```bash
'--db-url="jdbc:sqlserver://127.0.0.1:1433;DatabaseName=keycloak;a=b"'
or
"--db-url=\"jdbc:sqlserver://127.0.0.1:1433;DatabaseName=keycloak;a=b\""
```

This works currently because the parameter is interpreted twice, first the outer quote is doing the escape and then the inner quote escapes the semicolons. Same issue can happen for `db-password` or any other parameter that contains special chars.

IMHO the correct way is using escaped variables `${1@Q}` or using `sed` or similar if the shell doesn't support escaping (like default system shell in ubuntu which is `ash` and does not escape). In windows there are other issues (the script gives errors with special chars too), but I don't see this double interpretation that happens in Unix.

I worked in a fix you can see in this [branch](https://github.com/rmartinc/keycloak/tree/issue-22337) but I think that maybe it's better to maintain current (IMO strange) behavior. The remedy may be worse than the disease. Note there are several tests that needs modifications because they were using the current double interpretation. So just asking here. Do I continue with this or just close the issue and maintain current behavior? @pedroigor @mposolda @vmuzikar

**Comment by vmuzikar** [comment]
@rmartinc Thank you for looking into this!

Given the complexity and breaking nature of the fix, IMHO we should just document it. WDYT?

**Comment by rmartinc** [comment]
@vmuzikar Whatever you decide it's OK to me, but explaining this is going to be tricky. :smile:

**Comment by vmuzikar** [comment]
@rmartinc I think maybe an example in docs would do the trick. :)

**Comment by jonkoops** [comment]
Added this to the patch release project since it was assigned to the 22.0.4 milestone. @abstractj if this doesn't need to come along with that specific release please put it into the next.
