### ISSUE TITLE
JSON log formatting enhancements.

### ISSUE THREAD

**Issue by lesaux** [keycloak/keycloak#22348]
### Description

The message portion of this json log line could be enhanced.
I would rather not have to build a parser for this in my logging infrastructure.

`{"timestamp":"2023-08-09T16:33:09.666Z","sequence":27663,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.hibernate.internal.util.EntityPrinter","level":"DEBUG","message":"org.keycloak.models.jpa.entities.UserEntity{lastName=Le Saux, federatedIdentities=<uninitialized>, realmId=f7d50437-f8c9-4e95-8a3b-0ab36bf10ee0, credentials=<uninitialized>, createdTimestamp=1682696312148, serviceAccountClientLink=null, enabled=true, notBefore=0, emailConstraint=pierig.lesaux@xyzcom, emailVerified=false, firstName=Pierig, requiredActions=<uninitialized>, federationLink=null, attributes=<uninitialized>, id=94a12336-cfbf-4d48-ba21-929e83eed178, email=pierig.lesaux@xyz.com, username=pierig.lesaux@xyz.com}","threadName":"executor-thread-1","threadId":17,"mdc":{},"ndc":"","hostName":"keycloak-keycloakx-0","processName":"QuarkusEntryPoint","processId":1}`

### Motivation

Operational visibility dashboards to show last users logged in etc...

**Comment by trixpan** [comment]
@lesaux the JSON data model above is machine readable so what exactly do you mean by creating a parser?

**Comment by lesaux** [comment]
yes indeed, I would benefit from being able to extract data from the message itself
```"message":"org.keycloak.models.jpa.entities.UserEntity{lastName=Le Saux, federatedIdentities=<uninitialized>, realmId=f7d50437-f8c9-4e95-8a3b-0ab36bf10ee0, credentials=<uninitialized>, createdTimestamp=1682696312148, serviceAccountClientLink=null, enabled=true, notBefore=0, emailConstraint=pierig.lesaux@xyzcom, emailVerified=false, firstName=Pierig, requiredActions=<uninitialized>, federationLink=null, attributes=<uninitialized>, id=94a12336-cfbf-4d48-ba21-929e83eed178, email=pierig.lesaux@xyz.com, username=pierig.lesaux@xyz.com}"```

this could be a nice json too.
