### ISSUE TITLE
An internal server error has occurred using azure enterprise app

### ISSUE THREAD

**Issue by bfontainha** [keycloak/keycloak#22365]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

Hi,

currently I have an azure enterprise app which is responsible for authenticate the users using SAML.
On keycloak  a new SAML v2.0 identity provider  was added using the metadata xml from azure enterprise application.
Once uploaded the identity provider configurations, the endpoints descriptor xml file was downloaded to be uploaded to clients (http://localhost:8080/realms/SAML/broker/microsoft/endpoint/descriptor).
Using this file, the client has been created and defined test as IDP-Initiated SSO URL name to access directly the login page.
Accessing http://localhost:8080/realms/SAML/protocol/saml/clients/test, the login and user registration on keycloak works, although the following error pops up at the end.
![image](https://github.com/keycloak/keycloak/assets/55750549/666e32db-4bb6-4209-85b9-761ffc4d1fea)

Keycloak container logs are:

![image](https://github.com/keycloak/keycloak/assets/55750549/ab07c58d-a900-470c-b074-dbf1b7f4866f)

What could be the root cause for this?

Thank you

Regards

Bruno Fontainha

### Version

22.0.0

### Expected behavior

Login successfully and user redirected to proper page

### Actual behavior

An internal server error has occurred on url http://localhost:8080/realms/SAML/broker/microsoft/endpoint

### How to Reproduce?

Create azure enterprise application
Download metadata xml
Upload metadata xml as SAML v2.0 identity provider 
Download endpoints xml from SAML v2.0 identity provider 
Upload the endpoints xml as client 
Set IDP-Initiated SSO URL name 
Access the url generated underneath the  IDP-Initiated SSO URL name
Login using SAML 

```[tasklist]
### Tasks
```

**Comment by rmartinc** [comment]
Hi @bfontainha!

For what I see you are using post binding and the `relayState` parameter is not returned by the IdP (it's null and hence the NullPointerException). Keycloak uses the relayState information to locate the auth session that started the login. By spec the IdP should return the same `relayState` that it received in the request. For more information see https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf (chapter 3.5.3 RelayState in the POST binding).

You can confirm if the `relayState` is not returned by the IdP with the browser web developer tools. In the POST page from the IdP to Keycloak you need to see two hidden inputs, `SAMLResponse` with the base 64 and `RelayState` with the information sent previously by Keycloak. If `relayState` is not present we cannot do much except avoiding the NPE and logging a proper error message.

Regards!

**Comment by bfontainha** [comment]
Hi @rmartinc ,

i've defined on azure enterprise application the relay state http://localhost:8080/realms/SAML/protocol/saml/clients/test and keycloak still gives me the same error.

![image](https://github.com/keycloak/keycloak/assets/55750549/ac5bbb8b-02f8-4681-a0ec-76ea58717e80)


![image](https://github.com/keycloak/keycloak/assets/55750549/f7db092c-4ca6-4eb4-94ab-0ccb772806b1)

**Comment by rmartinc** [comment]
@bfontainha What I'm saying is that it seems that the identity provider you are using (azure enterprise application) does not follow the SAML standard and it doesn't return back the `relayState`. Keycloak cannot work without that parameter because it's used internally to locate the authentication session. Can you please check with the browser web developer tools if the `relayState` is (or isn't) in the POST sent by the IdP?

**Comment by bfontainha** [comment]
Hi @rmartinc 

i've added to IDP Initiated SSO Relay State the url from azure enterprise app and now the error message is that you are already logged in.


![image](https://github.com/keycloak/keycloak/assets/55750549/cd7037d1-7078-4eaf-b6eb-2fa0ed2e3571)


Once accessing http://localhost:8080/realms/SAML/protocol/saml/clients/test, i get redirected to http://localhost:8080/realms/SAML/broker/microsoft/endpoint and Keycloak shows up the message that you are already logged in and doesn't get redirected anywhere.

![image](https://github.com/keycloak/keycloak/assets/55750549/510ed0b5-01f4-4aec-8886-3d3ef573d3dc)


How could I get over and get redirected to an application?

Thank you

Regards

Bruno Fontainha

**Comment by bfontainha** [comment]
> @bfontainha What I'm saying is that it seems that the identity provider you are using (azure enterprise application) does not follow the SAML standard and it doesn't return back the `relayState`. Keycloak cannot work without that parameter because it's used internally to locate the authentication session. Can you please check with the browser web developer tools if the `relayState` is (or isn't) in the POST sent by the IdP?

Regarding the relayState is not being attached in the POST, I have already opened a case with Microsoft regarding that.

**Comment by bfontainha** [comment]
Hi @rmartinc ,

relay state is coming up on post response, although on keycloack it gets stuck at You are already logged in.

![image](https://github.com/keycloak/keycloak/assets/55750549/afb95e69-0bd2-4ef9-948d-1a650bede0bc)

At logs level i get the following message:

`2023-08-17 14:40:45,306 WARN  [org.keycloak.events] (executor-thread-379) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=630e0f6d-df12-483e-973e-0393e4bf9e47, clientId=null, userId=null, ipAddress=172.17.0.1, error=cookie_not_found
`
How can I get the cookie set or overpassed and move the user to the proper application page?

Thanks

Regards

Bruno Fontainha

**Comment by rmartinc** [comment]
Hi @bfontainha !

I'm not following you right now. I though you were configuring a SAML IdP (azure) using an identity  provider in Keycloak. For that you don't need to configure any client in the Keycloak side. With the SP metadata given by Keycloak (/realms/master/broker/{saml-idp-name}/endpoint/descriptor) you need to configure the IdP, in your case azure. You don't need to create any client in Keycloak, those client won't work.

To test if your provider is working you need a user in the IdP side and do for example the following:

1. Go to a Keycloak app page, for example the account page: /realms/{realm}/account. Click on Personal Info to start the login in Keycloak.
2. In the login page select your IdP to login (I think you have called it microsoft).
3. This starts the SAML login producing a AuthnRequest using POST to the IdP. It's in this point where Keycloak generates the SAML request and the relayState (with some specific info needed by Keycloak).
4. Here the login page in the IdP (azure) should be presented. (I don't know about this part.)
5. Do a login in the IdP side with a test user.
6. At this point the external IdP should return with a SAML Response and the relayState back to Keycloak using another POST.
7. The user is logged in keycloak and the account page shown (maybe some data is requested if there is no mappers to collect all the needed information from the SAML response).

I think you are doing something weird creating the clients in Keycloak.

Hope that helps!

**Comment by bfontainha** [comment]
Hi @rmartinc 

following your idea on post above, what would be the reason for keycloak SAML client in general?

Thanks

Regards

Bruno Fontainha

**Comment by rmartinc** [comment]
Keycloak can act as a SAML IdP (Identity Provider, normal use) and as SP (Service Provider, when using an identity provider). SAML clients are the SP apps that use Keycloak as the IdP to login, that's what the [securing apps doc](https://www.keycloak.org/docs/latest/securing_apps/index.html#using-saml-to-secure-applications-and-services) covers. The doc focuses on the adapters but any SAML capable SP can be configured as a client for the realm. Keycloak shows its own IDP SSO descriptor (/realms/{realm}/protocol/saml/descriptor) for the SAML SPs/clients. So, in general, you need a SAML client defined in the realm for each SP app that wants to login (SSO) via SAML.

But Keycloak can also act as an SP for an external IdP using an identity provider. In that case Keycloak leverages the login to the external IdP via the provider. That's why the provider endpoint (/realms/{realm}/broker/{provider}/endpoint/descriptor) shows a SP SSO descriptor. In the provider Keycloak role is SP.

So clients and identity-providers are different things. Depending the role (SP/IdP), you need a client or an identity-provider.. Clients are SPs for Keycloak (or Keycloak is IdP for clients). When you configure an identity-provider, Keycloak is the SP for the external IdP.

**Comment by bfontainha** [comment]
Hi @rmartinc 

Thank you for the clarification.
If understood you well, as i'm using microsoft as IDP, keycloak itself is already the SP, so there is no need to have a SAML client.
Going on that direction, how can I authenticate with SAML using microsoft as IDP and get redirected to the application once the login is successfully? 

Thank you

Regards

Bruno Fontainha

**Comment by bfontainha** [comment]
Hi @rmartinc 

using the account login page it works, although i would be interested to have a login page with proper redirects per client. 
How can i achieve it?

Thanks

Regards

Bruno Fontainha

**Comment by rmartinc** [comment]
If the identity provider works with the account app then I'm going to close the issue, as it's not a code bug. It was a misconfiguration.

> using the account login page it works, although i would be interested to have a web login page having SAML identity provider with proper redirects per client.
> How can i achieve it?

There are two types of client in general (OIDC and SAML). Both perform SP initiated login, that means the browser goes to the app initial page, there it is redirected to the Keycloak login page, the user logs in (it can be automatically  performed if already logged in, no password input is done) and then it's redirected back to the app (exactly as in the account app, which is a OIDC app). In SAML there is also an IdP initiated login, there Keycloak sends the configured SAML response and relayState are sent to the  app SAML endpoint.

Please use the [keycloak-user](https://groups.google.com/g/keycloak-user) mailing list for questions. This is the bug reporting system for issues in the code.
