### ISSUE TITLE
Keycloak 22.0.1 use # in url and the first try log in fail with  Invalid "parameter: redirect_uri"

### ISSUE THREAD

**Issue by SPGGPS** [keycloak/keycloak#22364]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Hi Team,

When I access to "sso.abc.es" I was redirected to "sso.abc.es/#/" (a hash is add by keycloack)

I can see the login page without a problem but I have to try to log in by pushing on the "Singing in" link I have an error "Invalid parameter: redirect_uri". I can push on the link "Back to application" and if I try to push on "Singing in" everything works fine
 
Thanks

### Version

22.0.1

### Expected behavior

Keycloack has to be able to manage # simbol on the URL 

### Actual behavior

Due to # simbol the first time that I try the log in a get an error Invalid "parameter: redirect_uri"

### How to Reproduce?

Install 22.0.1 version 

Apply this config

**Conf**

http-enabled=true
https-enable=false
http-port=8080
http-host=127.0.0.1
proxy=edge
http-relative-path=auth
features=upload-scripts
log=file,console
log-console-color=true
log-file=/opt/keycloak_app/keycloak/data/log/keycloak.log
https-trust-store-file=/etc/pki/ca-trust/extracted/java/cacerts
https-trust-store-password=xxxxxx
hostname=sso.abc.es

Insall apache and apply this config 

**Apache conf**
<VirtualHost *:443>

#DocumentRoot /var/www/html
ServerName sso.abc.es

ProxyPreserveHost On
ProxyRequests Off
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
<Proxy *>
Require all granted
</Proxy>

ProxyPass "/login" "http://127.0.0.1:8080/auth/realms/ems/account/"
ProxyPassReverse "/login" "http://127.0.0.1:8080/auth/realms/ems/account/"

ProxyPassMatch "^/auth/(.*)" "http://127.0.0.1:8080/auth/$1"
ProxyPassReverse "/auth/(.*)" "http://127.0.0.1:8080/auth/$1"

ProxyPass "/admin" "http://127.0.0.1:8080/auth/admin"
ProxyPassReverse "/admin" "http://127.0.0.1:8080/auth/admin"

ProxyPass / http://127.0.0.1:8080/auth/realms/ems/account/
ProxyPass / http://127.0.0.1:8080/auth/realms/ems/account/

SSLEngine on
SSLCertificateFile      /etc/httpd/conf.d/ssl/abc.es.crt
SSLCertificateKeyFile   /etc/httpd/conf.d/ssl/abc.es.key
SSLProtocol -all +TLSv1.2 +TLSv1.3SSLProtocol -all +TLSv1.2 +TLSv1.3
#SSLProtocol TLSv1.3
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-
RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-A
ES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES
128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!3DES

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
CustomLog "logs/ssl_keycloak-access_log" combined env=!forwarded
CustomLog "logs/ssl_keycloak-access_logg" proxy env=forwarded

ErrorLog logs/ssl_keycloak-error_log

ErrorLog logs/ssl_error_log
TransferLog logs/ssl_access_log
LogLevel warn

<FilesMatch "\.(cgi|shtml|phtml|php)$">
SSLOptions +StdEnvVars
</FilesMatch>
<Directory /usr/lib/cgi-bin>
SSLOptions +StdEnvVars
</Directory>
</VirtualHost>

access to sso.abc.es you will be redirect to sso.abc.es/#/ try to log in.

### Anything else?

I don't know if I have a mistake on my proxy pass config, but It was working perfectly for the previous versions. I'll do a lot of tests but I can't do it work

**Comment by ssilvert** [comment]
What is the previous version of Keycloak you are coming from?  Were you using the React-based `keycloak.v2` theme before?

I don't think Keycloak is actually doing a redirect to `sso.abc.es/#/`.  The hash is added on the client side by the React hash router.

To fix this you will need to tweak your proxy or maybe tweak the valid redirect URIs for the `account` client.

Incidentally, we are switching to path routing in the next major version so the hash will go away completely.

I'll keep this open awhile longer so you can investigate further on your end.  Please let me know how things turn out and if you do find that this is a Keycloak bug then we will address it.

**Comment by SPGGPS** [comment]
Hi Ssilvert,

It was working on 20.0.2 version. On this version, I wasn't using keycloak.v2 as the parent of the account theme. With the update to 22.0.1 I have changed to keycloak.v2, because base is deprecated. The proxy configuration didn't change, I'll try to delete # with the proxy module.  Do you think that by changing to keycloak as the parent of the account theme the behavior will be different?

Thanks

**Comment by ssilvert** [comment]
I wouldn't try to use `keycloak` with 22.0.1.  It is no longer there for account theme.

**Comment by SPGGPS** [comment]
Hi,

I added these lines in Apache configuration to avoid the problem.

    LoadModule rewrite_module modules/mod_rewrite.so
    RewriteEngine on
    RewriteCond %{REQUEST_URI} ^/$
    Rewriterule ^/$ https://sso.abc/auth/realms/ems/account [L,R=301]
    
    RewriteCond %{THE_REQUEST} "GET /auth/ HTTP/1.1"
    Rewriterule ^/auth/$ https://sso.abc/auth/realms/ems/account [L,R=301]

Thanks
