### ISSUE TITLE
Account V2 broken in main

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#22369]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

In the latest nightly build, Account V2 appears to be broken.  

You get a `Page not Found` error looking for the page `/personal-info&iss=http%3A%2F%2Flocalhost%3A8180%2Frealms%2Fmaster`, which is not a valid route.

### Version

main

### Expected behavior

Account V2 running

### Actual behavior

Error above

### How to Reproduce?

See description

**Comment by edewit** [comment]
if it was a `?` instead of a `&` then it would have been fine

**Comment by edewit** [comment]
Tested it again on windows can't reproduce it their either...

**Comment by ssilvert** [comment]
Duplicate of https://github.com/keycloak/keycloak/issues/22486
