### ISSUE TITLE
wrong terms in English/French OTP registration form

### ISSUE THREAD

**Issue by Paul-Van-Uytvinck** [keycloak/keycloak#22370]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

The code is a QR-Code, not a Barcode.

![image](https://github.com/keycloak/keycloak/assets/47578994/882c10f1-801e-4fd0-b838-fd91b79d815c)

### Version

20.0.5

### Expected behavior

"Open the application and scan the QR-Code"

### Actual behavior

"Open the application and scan the barcode"

### How to Reproduce?

The file is the following https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/messages/messages_en.properties

**Comment by SebastianLopienski** [comment]
Thanks @Paul-Van-Uytvinck! In the expected behaviour, you mentioned
`Open the application and scan the QR-Code`

I'd propose a slight rephrase:
`Open the application and scan the QR code below:`
or 
`Open the application and scan this QR code:`

**Comment by ssilvert** [comment]
@Paul-Van-Uytvinck Did you send a PR for this?  I didn't find it.
