### ISSUE TITLE
Linkedin Profile projection configuration missing in admin-ui

### ISSUE THREAD

**Issue by jwesselink** [keycloak/keycloak#22384]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

The configuration option "Profile projection" is missing in the LinkedIn Identity provider configuration.

When creating a new linkIn identity provider, I see the following error in the console log of the browser:
```
There is no editor registered for undefined
```

I think something went wrong in refactoring to support custom configuration properties in the identity providers:

I looks like the type configuration `.type(ProviderConfigProperty.STRING_TYPE)` is missing in the `getConfigProperties` method:

https://github.com/keycloak/keycloak/blob/8f38e269700694dc8a34a673038d12ec3f6108cc/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java#L58-L64

For example, compared to the Google Identity provider configuration:
https://github.com/keycloak/keycloak/blob/8f38e269700694dc8a34a673038d12ec3f6108cc/services/src/main/java/org/keycloak/social/google/GoogleIdentityProviderFactory.java#L56-L76

### Version

22.0.1

### Expected behavior

See the Profile projection configuration option when creating or editing a LinkedIn Identity Provider

### Actual behavior

Profile projection is missing

### How to Reproduce?

Create a new LinkedIn Identity Provider, see that the Profile projection is not displayed, as described in the manual: https://www.keycloak.org/docs/latest/server_admin/#_linkedin

**Comment by rmartinc** [comment]
@jwesselink Yes, you are right. It just needs the line you are commenting:

```diff
diff --git a/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java b/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java
index f067ea2de8..55001a3bc3 100755
--- a/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java
+++ b/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProviderFactory.java
@@ -60,6 +60,7 @@ public class LinkedInIdentityProviderFactory extends AbstractIdentityProviderFac
                 .property().name("profileProjection")
                 .label("Profile projection")
                 .helpText("Projection parameter for profile request. Leave empty for default projection.")
+                .type(ProviderConfigProperty.STRING_TYPE)
                 .add().build();
     }
 }
```

But, looking to the issue https://github.com/keycloak/keycloak/issues/22383 it seems that linkedin now it's moving to OpenID Connect provider. I'm not able to configure the old `Sign In with LinkedIn` that the old provider mentions. If you can configure and test it please send a PR just with that lone (no test needed). Maybe this provider is not needed anymore.

**Comment by rmartinc** [comment]
We have created a new LinkedIn OpenID Connect social provider in #22383 as it seems LinkedIn has moved from old OAuth to new OIDC integration. The previous OAuth social provider in keycloak is marked as deprecated now and it will probably be removed in the future. 

So probably any change to it makes no sense from now on. Anyway, as commented before, if you can test the old provider in an existing app that the previous LinkedIn product is still available, please send the PR with the one line change.

**Comment by jonkoops** [comment]
@rmartinc if we are deprecating the old provider, do we have an issue to place it behind a 'deprecated' profile + an issue for removing it eventually? I think we should create these and assign them to a major release milestone, otherwise we are sure to forget about it.

**Comment by rmartinc** [comment]
@jonkoops https://github.com/keycloak/keycloak/issues/23067 was created to move the LinkedIn identity provider to a deprecated profile. I will create a new issue to remove it definitely in 25 for example.

**Comment by rmartinc** [comment]
I'm going to close this issue as the old Linked provider is deprecated now and we have a new one that uses OIDC. I don't think fixing things in the old provider is worthy, I really don't know if the old provider still works for old configurations. Re-open if needed please.
