### ISSUE TITLE
Email sending fails when SPI truststore is configured and hostnameVerification set to 'ANY'

### ISSUE THREAD

**Issue by simonthehero** [keycloak/keycloak#22395]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

With the current Keycloak version, any mail sending fails for us with the below error, indicating that hostname verification is indeed active, even if no verification is wanted:
```
"exception":{"refId":1,"exceptionType":"jakarta.mail.MessagingException",
    "message":"Could not convert socket to TLS","frames":
    [{"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"startTLS","line":2188},
    {"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"protocolConnect","line":765},
...
org.keycloak.services.resources.admin.RealmAdminResource: Failed to send email 
jakarta.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
    java.io.IOException: Can't verify identity of server: our-mail-server.com
```

We have Keycloak set up with the following properties setup in keycloak.conf - especially, no hostname verification :)
```yaml
# Truststore
spi-truststore-file-enabled=true
spi-truststore-file-hostname-verification-policy=ANY
spi-truststore-file-password=very-secret
spi-truststore-file-file=/path/to/keycloak/truststore.jks
```

Emails are sent using StartTLS, the realm configuration is as follows:
```json
"smtpServer": {
    "starttls": "true",
    "port": "25",
    "auth": "",
    "host": "our-mail-server.com",
    "from": "we@domain.com",
    "fromDisplayName": "displayName",
    "ssl": ""
  },
```

Cause of this issue is a change in the underlying `angus-mail` implementation, which was updated in Keycloak 22 to Angus-Mail:2.0.1. 
In jakarta.mail:1.6.5 the default for `mail.smtp.ssl.checkserveridentity` is `false`: 
https://github.com/jakartaee/mail-api/blob/1.6.5/mail/src/main/java/com/sun/mail/util/SocketFetcher.java#L608C46-L608C46
...whereas in angus.mail:2.0.1 the default is `true`: 
https://github.com/eclipse-ee4j/angus-mail/blob/master/core/src/main/java/org/eclipse/angus/mail/util/SocketFetcher.java#L634

However, the `DefaultEmailSenderProvider` was not updated to reflect this change. It would need to set this property explicitly for the case of `ANY` hostname verification
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java#L195

For now, I have worked around the issue by providing my own `EmailSenderProvider` and setting this as the default.

### Version

22.0.1

### Expected behavior

Sending emails without hostname verification is possible. The default EmailSenderProvider instructs angus-mail to bypass the verification if so configured.

```java
private void setupTruststore(Properties props) {
        boolean checkServerIdentity = true;

        JSSETruststoreConfigurator configurator = new JSSETruststoreConfigurator(session);

        SSLSocketFactory factory = configurator.getSSLSocketFactory();
        if (factory != null) {
            props.put("mail.smtp.ssl.socketFactory", factory);
            if (configurator.getProvider().getPolicy() == HostnameVerificationPolicy.ANY) {
                props.setProperty("mail.smtp.ssl.trust", "*");
                props.setProperty("mail.smtp.ssl.checkserveridentity", "false"); // this is needed
                checkServerIdentity = false;
            }
        }

        if (checkServerIdentity) { 
            props.put("mail.smtp.ssl.checkserveridentity", "true"); // obsolete w/ angus-mail:2.0.1, but good to be explicit..?
        }
    }
```

### Actual behavior

Sending emails fails with the following error message:
```
"exception":{"refId":1,"exceptionType":"jakarta.mail.MessagingException",
    "message":"Could not convert socket to TLS","frames":
    [{"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"startTLS","line":2188},
    {"class":"org.eclipse.angus.mail.smtp.SMTPTransport","method":"protocolConnect","line":765},
...
org.keycloak.services.resources.admin.RealmAdminResource: Failed to send email 
jakarta.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
    java.io.IOException: Can't verify identity of server: our-mail-server.com
```

### How to Reproduce?

Set up keycloak with an SPI Truststore configured and try to send emails using StartTLS. Config example below:

Note.
I am unsure what needs to be configured to actually get an SSLFactory here...
```java
        JSSETruststoreConfigurator configurator = new JSSETruststoreConfigurator(session);

        SSLSocketFactory factory = configurator.getSSLSocketFactory();
```

keycloak.conf
```yaml
# Truststore
spi-truststore-file-enabled=true
spi-truststore-file-hostname-verification-policy=ANY
spi-truststore-file-password=very-secret
spi-truststore-file-file=/path/to/keycloak/truststore.jks
```

realm configuration:
```json
"smtpServer": {
    "starttls": "true",
    "port": "25",
    "auth": "",
    "host": "our-mail-server.com",
    "from": "we@domain.com",
    "fromDisplayName": "displayName",
    "ssl": ""
  },
```

### Anything else?

In jakarta.mail:1.6.5 the default for `mail.smtp.ssl.checkserveridentity` is `false`: 
https://github.com/jakartaee/mail-api/blob/1.6.5/mail/src/main/java/com/sun/mail/util/SocketFetcher.java#L608C46-L608C46
...whereas in angus.mail:2.0.1 the default is `true`: 
https://github.com/eclipse-ee4j/angus-mail/blob/master/core/src/main/java/org/eclipse/angus/mail/util/SocketFetcher.java#L634

**Comment by rmartinc** [comment]
Hi @simonthehero!

I suppose this is a small regression but this configuration is quite weird. Besides I suppose setting `mail.smtp.ssl.checkserveridentity` is the recommended option to have security by default. I'll try to provide a fix the next week. But I'm setting also minor.

**Comment by sreeharitummala** [comment]
We are seeing the following error in keycloak 23-
Failed to send email: java.lang.NullPointerException: Cannot invoke "org.keycloak.truststore.TruststoreProviderFactory.create(org.keycloak.models.KeycloakSession)" because "truststoreFactory" is null
Can any of you tell us what configuration are we missing.
thanks in advance!
