### ISSUE TITLE
Common resources in Welcome page didn't resolve correctly

### ISSUE THREAD

**Issue by kamontat** [keycloak/keycloak#22401]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

https://github.com/keycloak/keycloak/blob/8f38e269700694dc8a34a673038d12ec3f6108cc/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/resources/QuarkusWelcomeResource.java#L185-L185

This should use `import` variable in theme.properties instead of hard-coded.

### Version

v22.0.1

### Expected behavior

correct common path

### Actual behavior

404 not found

### How to Reproduce?

use `resourcesCommonPath` in welcome page.

```html
<link href="${resourcesCommonPath}/img/favicon.ico" rel="icon"/>
```

**Comment by kamontat** [comment]
Not sure I tag correct area or not, sorry if not.

**Comment by jonkoops** [comment]
Hi @kamontat, if you have a good idea of what the fix should be feel free to open up a PR.

**Comment by kamontat** [comment]
@jonkoops Created.
