### ISSUE TITLE
Cannot create resource permission with a specific resource

### ISSUE THREAD

**Issue by thuongvo** [keycloak/keycloak#22427]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/fine-grained-permissions

### Describe the bug

I would like to create a resource permission. But I cannot select a resource. 

### Version

20.0.5

### Expected behavior

I expect "test" resource is displayed in the select box then I can create the permission.

### Actual behavior

No resource is displayed. I cannot create any permissions

### How to Reproduce?

1. Create a client which authorization is enable.
2. Create a resource named test.
3. Try to create a resource permission.
4. At reousces field, type "t". You will see the error in console.

```
TypeError: Cannot read properties of undefined (reading 'length')
    at constructor.<anonymous> (select2.js:1800:34)
    at Object.callback (select2.js:681:22)
    at authz-controller.js:986:29
    at I (angular-resource.js:779:15)
    at angular.js:18075:37
```

**Comment by jonkoops** [comment]
This seems to be an issue for the old Angular JS based Administration Console, which have replaced with a new React based one. Since this code no longer exists I am closing this issue.
