### ISSUE TITLE
NPE when fetching sessions for a client in UI

### ISSUE THREAD

**Issue by mkrueger92** [keycloak/keycloak#22428]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

Related to issue #20443, the solution is not complete.
The functions related to pagination of sessions for clients were not touched in the last PR.

Due to offline sessions for non-existing users (see discussion of PR #17577), the UI is not able to display anything.

### Version

22.0.1

### Expected behavior

The UI can show sessions of a client.

### Actual behavior

The UI is not showing sessions of a client when some of the sessions belong to a federated user which has been deleted just on the federated system.

### How to Reproduce?

1. Create an offline session for a federated user.
2. Delete the user from the external system without Keycloak getting informed about it.
3. Open the sessions view from the client details page of the Admin UI.

Then, after some time, the UI fails. In the browser debug window the request it can be observed that the request for offline sessions failed.

### Anything else?

This bug report is related to issue #20443 and PR #17577.

**Comment by ahus1** [comment]
@mposolda - as this referencing #20443, could you please have a look? Thanks!
