### ISSUE TITLE
inputOptionLabels is not used by Admin UI

### ISSUE THREAD

**Issue by taaem** [keycloak/keycloak#22432]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the Admin UI the user profile option `inputOptionLabels`, which can be specified to provide translations to select values are not respected. If I specify them I get correctly translated forms in the login process but the keys are not translated in the admin ui.

### Version

22.0.1

### Expected behavior

With `inputOptionLabels` I should be able to provide translated labels for select options in the admin ui.

### Actual behavior

The `inputOptionLabels` option is ignored by admin ui.

### How to Reproduce?

1. Add a custom attribute in the user profile:
```json
{
      "name": "attr",
      "displayName": "${attr}",
      "selector": {
        "scopes": [
          "microprofile-jwt",
          "phone",
          "profile",
          "email",
          "web-origins",
          "roles",
          "offline_access",
          "role_list",
          "address",
          "acr"
        ]
      },
      "permissions": {
        "edit": [
          "user",
          "admin"
        ],
        "view": [
          "user",
          "admin"
        ]
      },
      "annotations": {
        "inputType": "select",
        "inputOptionLabels": {
          "option1": "${option1Label}",
          "option2": "${option2Label}",
        }
      },
      "validations": {
        "options": {
          "options": [
            "option1",
            "option2"
          ]
        }
      },
      "required": {
        "roles": [
          "user"
        ],
        "scopes": [
          "microprofile-jwt",
          "phone",
          "profile",
          "email",
          "web-origins",
          "roles",
          "offline_access",
          "role_list",
          "address",
          "acr"
        ]
      },
      "group": null
    },
```
2. Check the User detail page of a user
3. It says `option1` and `option2` instead of `option1Label` and `option2Label`

**Comment by taaem** [comment]
As far as I understand the same bug also exists in the new account console. (see https://github.com/keycloak/keycloak/blob/main/js/apps/account-ui/src/personal-info/components/SelectComponent.tsx#L53):
```tsx
<Select
  toggleId={attribute.name}
  onToggle={(b) => setOpen(b)}
  onSelect={(_, value) => {
    const option = value.toString();
    if (Array.isArray(field.value)) {
      if (field.value.includes(option)) {
        field.onChange(
          field.value.filter((item: string) => item !== option),
        );
      } else {
        field.onChange([...field.value, option]);
      }
    } else {
      field.onChange(option);
      setOpen(false);
    }
  }}
  selections={field.value ? field.value : t("choose")}
  variant={Array.isArray(field.value) ? "typeaheadmulti" : "single"}
  aria-label={t("selectOne")}
  isOpen={open}
>
  {options.map((option) => (
    <SelectOption
      selected={field.value === option}
      key={option}
      value={option}
    >
      {option}
    </SelectOption>
  ))}
</Select>
```

**Comment by jonkoops** [comment]
This also ties into the discussion under #16882. We need to find a better way to handle localized content on an API level.

**Comment by jonkoops** [comment]
@edewit could you create a PR to backport this to a patch release for version 22?

**Comment by jonkoops** [comment]
Yes, feel free to log that as a new ticket. It makes it a lot easier for us to track these kinds of things.
