### ISSUE TITLE
Query users by 'LDAP_ID' is not working

### ISSUE THREAD

**Issue by ckoenig95** [keycloak/keycloak#22436]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

Quering for users using their attribute *LDAP_ID* with the endpoint `GET /{realm}/users` results in an empty array response instead of the users data.

### Version

20.0.2

### Expected behavior

The user data of the user with the matching LDAP_ID is returned.

### Actual behavior

An empty array is returned.

### How to Reproduce?

Configure ActiveDirectory as user federation (LDAP) with *Import users* turned off.
Query for a specific user using their LDAP_ID as part of the `q` parameter when calling the `GET /{realm}/users` endpoint.

Example:
`https://keycloak-url/auth/admin/realms/portal/users?q=LDAP_ID:b42670b4-38e9-4e11-8a3f-fb7288937fbb`

Response:
`[]`

![image](https://github.com/keycloak/keycloak/assets/14260016/1de19381-496f-47d6-a5f3-9f5d02cf1980)

**Comment by rmartinc** [comment]
@ckoenig95 IIRC the ldap provider when used without import only searches for a limited set of attributes (see the [javadoc](https://github.com/keycloak/keycloak/blob/22.0.1/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L346-L358)). And this is just in the last versions, probably in version 20 you are using it's not even like this.

Therefore I don't think this is a bug and more an enhancement. But probably the keycloak team will have no time to work on it. I'm just moving it to backlog and adding the help wanted label.

**Comment by rmartinc** [comment]
This issue is being repeated several times, in general searching in LDAP using any attribute, for example https://github.com/keycloak/keycloak/issues/22578. I'm taking this one to submit a PR in the future to search by any attribute defined in the mappers.
