### ISSUE TITLE
Ask admins to install the Oracle Database driver separately

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#22452]
### Description

Due to the Oracle driver being proprietary and not open source, it shouldn't be shipped as part of the Keycloak distribution. 

As [Oracle recommends](https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html), "The best practice is use the latest version of the Oracle JDBC driver that supports the JDK and Database version that you use and is compatible with your support requirements."

Admins will need to download and install the drivers separately, depending among others on the Oracle database version they are using.

### Motivation

Keycloak should ship only open source database drivers.

### Details

I'll prepare a PR for this

**Comment by stianst** [comment]
Wonder if we would need to wrap this in a build profile or something for release/22.0 as it would be a bit of a breaking change to remove in Keycloak 22.0.x. Or, perhaps even wrap it in a profile in main, to make it avail in Keycloak, but not RHBK?
