### ISSUE TITLE
Support Quarkus Dev UI in dev mode

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#22455]
It'd be great to support Quarkus Dev UI in development mode in order to improve UX during the development. We could also enhance our Keycloak extension to include helpful information and statuses. We can also obtain information about DB or caches. Moreover, when we move to the RESTEasy Reactive, we'll also get valuable stats about the endpoints, etc.

Part of this initiative would also require analyzing the dev dependencies and removing them from the distribution.  

https://quarkus.io/guides/dev-ui

**Comment by vmuzikar** [comment]
Thanks for opening this. Dev UI integration might be useful, but probably needs to be discussed in a wider Keycloak team and consider all the implications (incl. productization).

**Comment by jirutka** [comment]
Please make it optional, i.e. easy to disable when building Keycloak (without patching several `pom.xml`), so we can avoid unnecessary bloat in production deployments.

Related to #22399

**Comment by stianst** [comment]
We will definitively not include Dev UI and relevant dependencies in the distribution, and not to actively get rid of all these crazy dev-ui dependencies, including their transitive dependencies.

I could be open to a build profile that let's you build Keycloak to include the Dev UI stuff, but I personally don't think there's much value in that. I'd rather use standard tools like logging, metrics, debuggers, etc to debug KC, and not the Quarkus Dev UI.

**Comment by mabartos** [comment]
Yep, makes sense. Agree, that the potential value, it might bring, is not big. 

Closed as not planned.
