### ISSUE TITLE
Remove org-crac dependency

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22471]
### Description

io.vertx:org-crac has not been productized and should be removed if possible.

It appears to be used by:
- quarkus-vertx-http
- quarkus-bootstrap-runner

**Comment by shawkins** [comment]
@vmuzikar I don't see how this dependency can be removed.  RunnerClassLoader directly uses crac.  That classloader is used for SerializedApplication non-dev / optimized runs via QuarkusEntryPoint.  There are direct references to RunnerClassLoader in keycloak - org.keycloak.quarkus.runtime.cli.command.beforeReaugmentationOnWindows

It also appears to be a tiny dependency without any transitive dependencies - the whole thing is 6 classes only 1 of which really has much logic.

Perhaps the quarkus / productization teams should weigh in here.

**Comment by vmuzikar** [comment]
Will be fixed by https://issues.redhat.com/browse/QUARKUS-3342
