### ISSUE TITLE
Docker tags "latest" and "22.0" point to version "22.0.0-1" instead of "22.0.1-1"

### ISSUE THREAD

**Issue by hjhill** [keycloak/keycloak#22497]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

The tags `latest` and `22.0` on both quay.io and Docker Hub currently points to the image `22.0.0-1`, while a newer version `22.0.1-1` exists. This makes Dependabot determine `22.0.0-1` as the latest available version and refuse to do automatic updates to `22.0.1-1`.

### Version

22

### Expected behavior

The tag `latest` should always point to the latest build of the latest version of Keycloak. 
The tag `22.0` should always point to the latest build of the latest available version of Keycloak with a major version `22`

### Actual behavior

The tags `latest` and `22.0` point to an older version (`22.0.0-1` instead of `22.0.1-1`).

### How to Reproduce?

Look at https://quay.io/repository/keycloak/keycloak?tab=tags - it marks the tags that point to the same image.

**Comment by abstractj** [comment]
@hjhill the issue should be fixed now.

**Comment by mabartos** [comment]
@abstractj Thanks for the confirmation.

**Comment by hjhill** [comment]
@abstractj It is fixed now - thank you!
