### ISSUE TITLE
Wrap issue on 

### ISSUE THREAD

**Issue by gmadhavageek** [keycloak/keycloak#22492]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

Wrap the Permissions within Policies so they are all visible to view on v21-Quarkus 
Right now permissions are not wrapped

![image](https://github.com/keycloak/keycloak/assets/142418359/18c521d3-cc96-4d2d-8a38-7cf22533fe7b)

In older keycloak instance (v18 wildfly) we were able to see them like below
![image](https://github.com/keycloak/keycloak/assets/142418359/8a6c56e2-b711-4ec2-b5ad-b83cd30c16bd)

### Version

v21-Quarkus

### Expected behavior

Permissions need to be wrapped within Policies so they are all visible

### Actual behavior

Permissions are not wrapped within Authorization -> Policies tab

### How to Reproduce?

Keycloak Realm -> Select Clients -> Search and Select a Client -> Select Authorization Tab -> Select Policies tab within Authorization Tab -> Expand any policy

**Comment by gmadhavageek** [comment]
Hi Team - Is there a way this issue can be prioritized?

**Comment by Kikiodazie** [comment]
Hey @gmadhavageek @jonkoops, 

I would like to work on this if no one is working on it. I have good experience with Java and some writing Javascript.

Maybe some guidance to help me get started if possible.

**Comment by jonkoops** [comment]
@Kikiodazie Sure, I will assign this to you.

**Comment by Kikiodazie** [comment]
> @Kikiodazie Sure, I will assign this to you.

Thank you @jonkoops. 

So sorry I haven’t started working on it or gotten back to you. Been swamp with some person stuff. Will work on it this weekend and reach out with questions if i have any. 

Do have great weekend ahead.
