### ISSUE TITLE
Refused to frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

### ISSUE THREAD

**Issue by infacto** [keycloak/keycloak#22491]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/javascript

### Describe the bug

```js
this.keycloak.init({ flow: 'hybrid' })
```

Error: 

```
Refused to frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

### Version

22.0.1

### Expected behavior

Work

### Actual behavior

Does not work.

### How to Reproduce?

See above.

### Anything else?

Trying to migrate from keycloak-js 4 to 22. I want to pass username and password to login. Version 4 works, 22 not. (Angular, Ionic, Cordova but don't want the cordova adapter)

Btw. the typescript type of `keycloak.init` is wrong or required. You always have to pass an empty obejct `{}`.

**Comment by jonkoops** [comment]
Thanks for reporting this issue, but unfortunately I am not able to reproduce this. I've attempted to reproduce the problem on [this branch](https://github.com/jonkoops/kjs-playground/tree/issue-22491), but everything is working as expected.

I have not tried to migrate an older installation of Keycloak to the latest version, but these are the settings I have configured for the security headers:

![A screenshot showing the default values for the security headers.](https://github.com/keycloak/keycloak/assets/695720/627a2266-32de-4531-8efb-276c01f5c324)

Perhaps some of your client settings are no longer accurate, causing this issue. In any case, I would recommend to try to reproduce the issue in a clean environment, with minimal steps to reproduce (such as the repo I linked before).

**Comment by infacto** [comment]
Thank you for testing and replying. I have the same configuration, but fixed that with the following configuration:

```ts
await this.keycloak.init({
  enableLogging: true,
  checkLoginIframe: false,
  flow: 'standard',
  onLoad: 'check-sso',
});
```

It works. But there is a weird behavior. First time I call this code `keycloak.init` the app reloads and is still not authenticated / logged in. The second time the app does not reload and the init method returns true for authenticated. But why is the app reloading the first time?

In my test, I added a button which just executes the code above (the init method). On first click the app reloads and is still not authenticated. 

Some background: 
I work on an Ionic / Cordova app with Angular. But currently I serve this app like a default Angular page. No cordova deps. It should behave like an Angular page.

Later I want this working when I run the app on device using Cordova. I know there a two options `cordova` and `cordova-native`. The native option sound interessting but uses two obsolete plugins which are not yet supported anymore on the latest Cordova version. Therefore it's not a real option. I currently test it with the default option `cordova`  which also feels like pain. Anyway... The init and login should work without reloading (redirecting) the app. Regardless if I'm on cordova or browser.

Server version: 18.0.2

**Comment by infacto** [comment]
I got it running on Cordova now. 🎉 With the default adapter `cordova` (not `cordova-native` due to outdated and unsupported plugins). 

When I run this app in browser (Angular app using `ng serve`), the redirect for check-sso is redirecting (reloading the app). How to prevent this to have the same behavior like on cordova? I suspect this doesn't work since it's done via the inappbrowser plugin. In browser we could use iframe, which is not recommended, right? And it leads to the frame-ancestor issue (initial issue). I know this isn't a forum, but I appreciate any hint. This is very exhausting 😓 and I need to find a solution to prevent page reload. ... The server is updated from time to time. However, it is currently not possible to use the latest version. But feel free to close. Thanks anyway.

**Comment by jonkoops** [comment]
> Maybe I need to change the config to allow all frame-src?

Yeah, you could try to make your configuration more permissive. Perhaps try to allow framing only for your application domain first? I'd recommend reading [the documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) on MDN.

**Comment by infacto** [comment]
Ok, I'll check this out. I'm closing this for now... Just for another refs: #16277

**Comment by srehanhasan** [comment]
I've set up keycloak/keycloak:latest distribution on Azure app service directly. I can see the welcome page but when I try to open the Admin Console, it gives the above-mentioned error. See below for reference:

**Refused to frame 'http://keycloak.azurewebsites.net/' because it violates the following Content Security Policy directive: "frame-src 'self'".**

Can someone please help out on this?

**Comment by jonkoops** [comment]
@srehanhasan please do not bump old issues with comments that are specific to 3rd party services. If you are looking for help I would recommend [starting a discussion](https://github.com/keycloak/keycloak/discussions) instead.

**Comment by srehanhasan** [comment]
@jonkoops Found this issue similar to what I was facing, thought someone might have something useful in case this got fixed.

It wasn't specific to any 3rd party. Got it fixed by providing the following configurations:
- hostname-url
- hostname-admin-url

Still, pardon any inconvenience caused if you feel it was needless.

**Comment by jonkoops** [comment]
> Still, pardon any inconvenience caused if you feel it was needless.

No worries, we value your input so please don't shy away from providing feedback. It's just that existing closed issues are hard for our team to keep track of, so you are less likely to receive an answer.

**Comment by Jquery-knoblenient** [comment]
read this https://stackdev.space/questions/different-ways-to-determine-if-someone-is-currently-using-the-internet-or-not explanation

**Comment by xdanielsb** [comment]
This can happen if your Keycloak init configuration is incorrect, for example, if the specified realm doesn't exist. It also be caused by browser blocking due to a restrictive csp. To fix it, ensure the realm exists and update the CSP Realm Settings -> Security Defenses -> Headers, adding your app’s URL to frame-ancestors. e.g frame-ancestors 'self' http://your-url.com;
