### ISSUE TITLE
Correct Getting Started guide

### ISSUE THREAD

**Issue by andymunro** [keycloak/keycloak#22500]
### Description

QE has reviewed this guide

**Comment by ahus1** [comment]
@andymunro - I assume this change is necessary for RHBK22, so you'd need to backport this change with a pull request against the 22 release.

**Comment by ahus1** [comment]
@andymunro - I merge some minutes ago. You can now prepare the backport.

**Comment by andymunro** [comment]
Okay, great.

**Comment by andymunro** [comment]
Actually, the upstream is the source for the downstream, right?  So it will automatically show in the RHBK Getting Started Guide in a day or so. Is that still the case?

**Comment by andymunro** [comment]
Okay, so what is the snapshot of RHBK content that we know is not going away?  Do you have a date  after which any changes to main are not applied to downstream?

**Comment by ahus1** [comment]
@andymunro - this is probably something we should discuss in the internal chat.
