### ISSUE TITLE
Properly configure operator and statefulsets created by the operator wrt allowPrivilegeEscalation

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22527]
### Description

The keycloak operator and statefulsets created by the operator should follow the guidelines:

https://access.redhat.com/solutions/7002730 

https://docs.openshift.com/container-platform/4.12/operators/operator_sdk/osdk-complying-with-psa.html#osdk-ensuring-operator-workloads-run-restricted-psa_osdk-complying-with-psa

to prevent openshift 4.11+ from issuing warnings - at least for now these are being logged at the debug level and may not be noticable.

**Comment by shawkins** [comment]
@vmuzikar what are the openshift versions supported by RHBK?

**Comment by shawkins** [comment]
@vmuzikar thanks for checking into this.  It looks like we can safely assume that 4.10 is not in the picture, so we can use the solution recommened for 4.11+.

**Comment by shawkins** [comment]
The fix should be applied to the example postgresql as well.

**Comment by vmuzikar** [comment]
> The fix should be applied to the example postgresql as well.

It's just an example for dev and test purposes. IMHO no need to fix that one.

**Comment by shawkins** [comment]
Based upon the investigation of #24060 we'll defer working on this until it comes up again - it's quite possible that openshift 4.13 has somewhat resolved this, and it's unlikely we'll see these logs as the fabric8 client isn't at debug by default.
