### ISSUE TITLE
Adding multiple user attributes with the same key aren't stored (supported?) properly but no error message appears

### ISSUE THREAD

**Issue by yennor** [keycloak/keycloak#22526]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the admin ui, when going to an user account, and adding twice (or more) user attributes with the same key, you can save them, and you get a success message ("the user has been saved"), and all the attributes are shown.
But when you reload the attribute screen, all but one attributes are gone.
![image](https://github.com/keycloak/keycloak/assets/6601243/15d8334c-b904-4419-9613-edbf18581925)

### Version

22.0.1

### Expected behavior

Either shown an error message, that you can't have several attributes with the same key. Or properly store all the keys.

### Actual behavior

Right now, it seems like all the attributes are stored, and only after a reload or returning to the same user later, you notice that at once some attributes are missing.

### How to Reproduce?

- go to user attributes
- add new attribute with key "test"
- add 2nd attribute with key "test"
- click save.

**Comment by edewit** [comment]
I can't reproduce this, can you see the request in the network tab?

**Comment by jonkoops** [comment]
I am also unable the reproduce this issue, but I have found another bug in the process. If you add multiple attributes, save the user, remove all the attributes, and save again, none of the attributes are actually removed.

I've logged #22570, so we can resolve this there.

**Comment by yennor** [comment]
It seems like the problem is the ldap-federation. When I disable it, I can store several attributes with the same key. When the ldap federation is activated, only the first attribute is stored, the other ones are silently removed.
I can't find any error logs neither in keycloak nor the ldap logs.
Edit mode is WRITEABLE and Import Users is activated.
Will try to get more debug log.

**Comment by ssilvert** [comment]
I tried this will a dummy provider and it worked fine.  Looks like it must be specific to the ldap provider.

**Comment by ssilvert** [comment]
I think the core team needs to take a look here.  Unassigning UI team for now.

**Comment by anderermark** [comment]
We just had a debugging session here and in our case we used the `full-name-ldap-mapper` to populate the ldap `cn` field. 

After using this mapper, we only got single values returned for all attributes. After removing the field, everything worked as expected again.

Maybe this helps someone :)

**Comment by rmartinc** [comment]
Hi! I cannot reproduce the issue using an ldap. I have done the following:

* In a realm that I have an ldap user federation provider I changed it from READ_ONLY to WRITABLE and it's importing users. And I created a mapper `user-attribute-ldap-mapper` for `description`.
* In an existing user three description values were added.
* The user is modified successfully in the ldap with the correct values:

```
ldapsearch -LLL -H ldap://localhost:10389 -D "xxxx" -w yyyy -b "dc=example,dc=com" uid=ricky description
dn: uid=ricky,dc=example,dc=com
description: description1
description: description2
description: description3
```

Maybe it's related with your ldap configuration. We are missing something. Is the user an LDAP user or just a internal DB user? Can you share your ldap configuration and what mapper are you using for `mailAlias`? (Export the realm if possible.)

**Comment by anderermark** [comment]
Did you also try to add a `full-name-ldap-mapper` to your ldap user federation? Even though it seems unrelated it somehow broke all attributes in our case.

Maybe this is some kind of side effect in our case, I didn't have the time yet to create a minimal setup.

**Comment by rmartinc** [comment]
@anderermark No, I hadn't tried that as it was not in the reproducer steps. But it's the culprit. The bug is in that mapper, which discards all the values even in other attributes. I'll try to submit a PR the next week.
