### ISSUE TITLE
first login fails and subsequent logins are successful 

### ISSUE THREAD

**Issue by DREGALLA** [keycloak/keycloak#22538]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Hi Team,
We are from avaya. We have observed that there are multi customers who are facing issue with first login. 
subsequent logins are successful. 

We are using keycloak version, 6.0.1. 

Please help us resolve this issue.

### Version

6.0.1

### Expected behavior

first login also should be successful.

### Actual behavior

first login fails.

### How to Reproduce?

we are using keycloak to authenticate users using the client, avaya workplace and using different IDPs

**Comment by jonkoops** [comment]
We do not offer support on older versions of Keycloak than the current stable. I would **highly** recommend that you upgrade your Keycloak server, as the version you are running is vulnerable to multiple critical security vulnerabilities.
