### ISSUE TITLE
Calls Made to https://{url}/auth/admin/realms/{Realm}/clients Result in a 403 Despite Correct Permissions

### ISSUE THREAD

**Issue by MarkTallentire** [keycloak/keycloak#22542]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

We believe that this correctly worked previously in KC21.

Making a call to the API Endpoint https://{url}/auth/admin/realms/{Realm}/clients results in a 403 despite service account having all realm-management permissions (Including View/Query Clients)
![image](https://github.com/keycloak/keycloak/assets/26217534/5bfb9150-cd75-4b60-884a-f08af5abfa7a)

Decoding the JWT also shows that the roles are not being added to the token. (Removing manage-users works, but adding any other permission does not)
![image](https://github.com/keycloak/keycloak/assets/26217534/72e868e9-53df-4fe1-a75e-4c0409a96933)

### Version

22.0.1

### Expected behavior

For service accounts with the view/query clients role to be able to utilise the /clients endpoint on the rest API

### Actual behavior

Endpoint throws a 403

### How to Reproduce?

Create a service account, add permissions to it and decode the jwt via https://jwt.io/ to see that the roles are not being added

Utilise postman to send a request to the clients endpoint resulting in the 403

**Comment by ValentinLorand** [comment]
Hello, I'm experiencing the same problem. I have a specific user in a custom realm who have the rights to "manage-clients". But since I upgraded keycloak in version 22.0.1, my user is unable to create clients like before. I am receiving a 403 (Forbidden) status code.

**Comment by rmartinc** [comment]
Hi @MarkTallentire!

I cannot reproduce this. I used keycloak 22.0.1 created a realm and a test client with a service account. Added the roles "query-clients" and "view_clients" to the account. I can execute the listing. I'm using this script:

```bash
#!/bin/bash

URL="http://localhost:8080"
REALM=demo

TKN=$(curl -sX POST "${URL}/realms/${REALM}/protocol/openid-connect/token" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -d "client_secret=XXXXX" \
 -d 'grant_type=client_credentials' \
 -d 'client_id=test-oidc' | jq -r '.access_token')

curl -vX GET "${URL}/admin/realms/${REALM}/clients?viewableOnly=true" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json;charset=utf-8" \
 -H "Authorization: Bearer $TKN"
```

The output of the second curl is 200/OK and I see the token has the roles in it. 

```
  "resource_access": {
    "realm-management": {
      "roles": [
        "view-clients",
        "query-clients"
      ]
    },
```

Can you please test with the last 22.0.3 using a new realm? If you can reproduce it, please provide the exact steps starting from an empty realm.

**Comment by MarkTallentire** [comment]
Hi @rmartinc 

Can confirm this appears to be working in 22.0.3. 

Mark
