### ISSUE TITLE
Redirect URI not updated when OIDC Identity Provider value for Alias is changed

### ISSUE THREAD

**Issue by borice** [keycloak/keycloak#22549]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

When registering a new OIDC identity provider via `Add OpenID Connect provider`, one of the required form fields is `Alias` whose pop-up documentation reads:
> The alias uniquely identifies an identity provider and it is also used to build the redirect uri. 

In previous versions of Keycloak (can't say exactly which is the last that worked...for sure v16.1.0), when modifying the value for Alias, the autogenerated redirect-url would reflect the change value as it's being changed.  With the latest and nightly versions, it no longer does that.  Here's a screenshot that shows `Alias` being updated, without the redirect uri being updated as well.

<img width="1094" alt="Screenshot 2023-08-18 at 10 00 38 AM" src="https://github.com/keycloak/keycloak/assets/431091/f81937d5-dc57-40df-91c1-c7726270aff2">

The redirect url should've ended with `.../realms/htrc/broker/foobar/endpoint`

### Version

22.0.1

### Expected behavior

The redirect url should be updated to always reflect the value specified in `Alias`

### Actual behavior

The redirect url is not updated when `Alias` is changed.

### How to Reproduce?

1. Start a brand-new Keycloak deployment with either `latest` or `nightly` version
2. Log in as administator
3. Create a new realm, and select it
4. Attempt to register a new OIDCv1.0 identity provider
5. Change the value of `Alias` from the default "oidc" to something else, like "foobar" and observe that the generated redirect uri above it isn't updated to reflect the changed value

**Comment by jonkoops** [comment]
Not quite sure why this broke, it might be something the old Admin Console handled on the front-end, which we then forgot to implement in the new React-based one.

**Comment by jonkoops** [comment]
Yeah, looks like this was updated live [in the old console](https://github.com/keycloak/keycloak/blob/ef47eee2dda29a0f08187ae67970323c28947f11/themes/src/main/resources/theme/base/admin/resources/partials/realm-identity-provider-oidc.html#L16). I don't believe this influences the actual data being sent to configure the provider, so this is a low impact bug. Still, it would be nice to have a fix for this.

**Comment by jonkoops** [comment]
Sure, I will assign this to you, thanks @SoniaisMad!

**Comment by SoniaisMad** [comment]
Thanks a lot :)

**Comment by igprasad36** [comment]
Hello :) 

I have a working code for this. I can create a PR if @SoniaisMad is not working on this. 
![Screenshot from 2023-08-23 15-43-07](https://github.com/keycloak/keycloak/assets/25505198/7ff11b64-acfa-4cc5-aee2-d8191b87dcea)


Thanks

**Comment by SoniaisMad** [comment]
I haven't started yet, so if you already have something working, you can take it @igprasad36 

@jonkoops Can you assign the issue to @igprasad36 since he's got something ?

Thanks
