### ISSUE TITLE
Add more translations for the Italian language

### ISSUE THREAD

**Issue by DeltaFox0018** [keycloak/keycloak#22552]
### Description

In the user account management section, many parts are not translated into Italian and remain in English
![image](https://github.com/keycloak/keycloak/assets/35847603/4d211bc8-422d-4990-8eb8-194268618d44)

**Comment by DeltaFox0018** [comment]
Translation for keycloak.v2
I tried adding the messages_it.properties file in the appropriate section of the theme but some items like "Signing In" is not edited instead "accountManagementWelcomeMessage" is edited correctly

**Comment by DeltaFox0018** [comment]
/Users/alessandrovolpato/Desktop/my-monster-energy-collection/authsystem/mmec_themes/account/messages/messages_it.properties

A possible translation solution to replace the following file

themes/src/main/resources-community/theme/keycloak.v2/account/messages/messages_it.properties

**Comment by jonkoops** [comment]
Hi @DeltaFox0018. Feel free to open a PR to resolve these issues, it will make it easier to discuss the details of the implementation and guide you in the right direction.

**Comment by DeltaFox0018** [comment]
ok thanks
