### ISSUE TITLE
Docs: server_development/topics/custom-attributes.adoc

### ISSUE THREAD

**Issue by espinal1976** [keycloak/keycloak#22557]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

File: server_development/topics/custom-attributes.adoc

this file is mentioned:  themes/base/account/account.ftl 
but it is not included in keycloak package, neither in keycloak-theme.jar.
Please include in documentation where to find this template we users could accomplish their configs.

root@easytest:/opt/keycloak-22.0.1/themes/itksoluciones/login#  find ../../../ -name account.ftl 
root@easytest:/opt/keycloak-22.0.1/themes/itksoluciones/login# 

### Version

22.0.1

### Expected behavior

Identify clearly where to find this file: themes/base/account/account.ftl

**Comment by ssilvert** [comment]
@andymunro @espinal1976 This is documentation left over from the now-removed account console V1 (keycloak theme).

The current way to add new fields and do other customization with account console V2 (keycloak.v2 theme),[ is shown in the quickstart here](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-account-console).

But the very best way is to use the [Declarative User Profile](https://www.keycloak.org/docs/latest/server_admin/#user-profile) feature along with account console V3 (keycloak.v3 theme).   This allows you to define new fields from admin console and they will be automatically added to account console.  These features are considered tech preview right now but should be fully supported soon.

**Comment by pedroigor** [comment]
This issue is out of date because we have removed that specific section of the documentation in https://github.com/keycloak/keycloak/pull/26858. See https://github.com/keycloak/keycloak/issues/26856 for more details.
