### ISSUE TITLE
Unable to remove user attributes

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#22570]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When removing all attributes from a user and then saving the user, the attributes are not removed.

### Version

nighly

### Expected behavior

All of the attributes are removed.

### Actual behavior

None of the attributes are removed.

### How to Reproduce?

1. Go to the 'Attributes' tab of any user.
2. Add an attribute of any kind.
3. Save the user.
4. Remove the previously added attribute.
5. Save the user.

**Comment by jonkoops** [comment]
Marking this as a high impact issue, since as far as I can see there is no workaround for it.

**Comment by ssilvert** [comment]
I verified this too.  Need to fix asap.

**Comment by jonkoops** [comment]
@agagancarczyk could you create a PR to back-port this fix to version 22?
