### ISSUE TITLE
can't deploy source code

### ISSUE THREAD

**Issue by milad-ghasemzadeh** [keycloak/keycloak#22580]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

I have this error when I want to build project with 
mvnw.cmd clean install

but i will get this bug and I don't know how to solve it : 

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm-install) on project keycloak-js-adapter-jar: Failed to run task: 'pnpm install --frozen-lockfile --ignore-scripts' failed. java.io.IOException: Cannot run program "D:\Project\keycloak\js\node\node.exe" (in directory "D:\Project\keycloak\js\libs\keycloak-js"): CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]

### Version

lastest

### Expected behavior

run program without any bug

### Actual behavior

I can't deploy the project.

### How to Reproduce?

Just do what i said. build the project.

**Comment by jonkoops** [comment]
@ssilvert You are building Keycloak on Windows right? Have you ran into this before?

**Comment by milad-ghasemzadeh** [comment]
yes i'm building on windows. and yes this is my first time and i just read document. and try some ways to solve this issue.

**Comment by milad-ghasemzadeh** [comment]
> @ssilvert You are building Keycloak on Windows right? Have you ran into this before?

yes i'm building on windows. and yes this is my first time and i just read document. and try some ways to solve this issue.

**Comment by jonkoops** [comment]
I was referring to my colleague Stan :smile:. He's the only one on our team on Windows as well.

**Comment by milad-ghasemzadeh** [comment]
> I was referring to my colleague Stan 😄. He's the only one on our team on Windows as well.

oh, I'm sorry, I didn't pay attention

**Comment by ssilvert** [comment]
@jonkoops @milad-ghasemzadeh The answer is no, I don't think I've seen that before.

But I'm not using `mvnw.cmd`.  I just run regular `mvn`.  No idea if that's the cause.

**Comment by ssilvert** [comment]
I just ran `mvn install` on the keycloak/js directory and it ran fine.

**Comment by milad-ghasemzadeh** [comment]
> @jonkoops @milad-ghasemzadeh The answer is no, I don't think I've seen that before.
> 
> But I'm not using `mvnw.cmd`. I just run regular `mvn`. No idea if that's the cause.

well I run this one too. but still I have this problem

**Comment by jonkoops** [comment]
Perhaps try to clean your workspace by running `git clean -xdf`?

**Comment by milad-ghasemzadeh** [comment]
Well I succesed to find the problem, after searching a lot about this problem, finaly this issue help me to solve the problem of Node:

https://github.com/eirslett/frontend-maven-plugin/issues/487

But again I got another error message and it was : 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project keycloak-quarkus-server:
[ERROR]
[ERROR] Please refer to D:\Project\keycloak\quarkus\runtime\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :keycloak-quarkus-server


after searching a lot and thinking , finaly this command help me to solve my problem : 

mvn clean install -DskipTests=true -DskipTestsuite  -Dapp.server=wildfly

and now I can deploy the project.

anyway thanks a lot for your attention @jonkoops @ssilvert

**Comment by jonkoops** [comment]
Good to hear you found a solution!
