### ISSUE TITLE
Fine grained permissions not rendering

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#22583]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Opening the fine grained permissions gives an error:

```
TypeError: S is undefined
    te ResourcesPolicySelect.tsx:166
```

### Version

main

### Expected behavior

no error

### Actual behavior

error

### How to Reproduce?

open fine grained permissions

**Comment by jonkoops** [comment]
This fixes a bug that was present in `main`, but is not part of the v22 release. I will go ahead and remove this form the patch release.
