### ISSUE TITLE
Vue Quickstart  for Account UI

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak#22606]
### Description

 A quickstart that just shows using the account API with a view.

**Comment by jonkoops** [comment]
What would this entail? I think we should avoid framework specific implementations, as they tend to end up unmaintained (see the quickstarts).

**Comment by agagancarczyk** [comment]
> What would this entail? I think we should avoid framework specific implementations, as they tend to end up unmaintained (see the quickstarts).

Thanks @jonkoops we discussed this during our team meeting last week. @ssilvert suggested that I look into Vue and create a quickstart example demonstrating the utilization of the account API with Vue. However, we want to discuss how we can use parts of our current account V3 code in a Vue app. It's also possible that, in the future, when we have a way to add new pages, we could simply include a new Vue page. We might need more discussion before deciding on Vue's next steps.

**Comment by jonkoops** [comment]
> However, we want to discuss how we can use parts of our current account V3 code in a Vue app.

I don't quite understand, why would we embed parts of a React application into a a Vue application? Or, is the intention the other way around? Which is to register parts of the page in the Account Console so that a Vue application can be embedded in it?

**Comment by ssilvert** [comment]
> > However, we want to discuss how we can use parts of our current account V3 code in a Vue app.
> 
> I don't quite understand, why would we embed parts of a React application into a a Vue application? Or, is the intention the other way around? Which is to register parts of the page in the Account Console so that a Vue application can be embedded in it?

The latter would be an interesting idea.  

But I was referring to any common code that could be pulled out into its own package and reused.  One example we discussed was to have an account client package like we have for admin.  Even though it would be rather small, such a package would be especially useful if it contained types and such.

Also, there may be other utilities and functions that could be pulled out and reused in any javascript/Typescript application that talks to Keycloak.

Yet another possibility is that we start making heavy use of Web Components, which seems to be PatternFly's answer to multi-framework support.

But the point of this exercise is not so much that we care about Vue.  Rather, we want the pieces of our UI to be loosely coupled and useful in different contexts.

**Comment by jonkoops** [comment]
> But the point of this exercise is not so much that we care about Vue. Rather, we want the pieces of our UI to be loosely coupled and useful in different contexts.

I agree with that, I would just opt to do all of that in plain JavaScript and HTML, without any frameworks on top. If it can be used in the web, it can also be used in any web application framework.

**Comment by agagancarczyk** [comment]
hi @ssilvert , Erik presented an example of account in Vue.js during our Keycloak weekly meeting last week. Perhaps he can easily adapt it for the admin as well. Can I assign this task to him?

**Comment by ssilvert** [comment]
This can be closed as out of date.
