### ISSUE TITLE
Admin-UI: Client-Credentials -> Error copying to clipboard

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#22635]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hi,

when I am in the admin UI and try to copy the credentials in a client via the copy button I get the error message: "Error copying to clipboard".
![Screenshot from 2023-08-23 08-53-17](https://github.com/keycloak/keycloak/assets/54103655/74259090-6949-4d8c-a4ab-5dc3801b7071)

My system information is:
System: Ubuntu 22.04.2 LTS
Browser: Microsoft Edge Version 115.0.1901.188 (Official build) (64-bit)

### Version

22.0.1

### Expected behavior

Copy to clipboard without error

### Actual behavior

-

### How to Reproduce?

-

**Comment by jonkoops** [comment]
Your browser probably is [blocking access to the clipboard](https://learn.microsoft.com/en-us/answers/questions/766718/how-do-i-unblock-the-clipboard-for-a-website), this is a permission that needs to be granted in some scenarios. Still, this can be improved, we should probably hide or disable the button if the permission has not been granted.

**Comment by npriebe** [comment]
@jonkoops 
That will be the problem. I have my Keycloak running under http. This means that it is not possible for me to allow the clipboard in the settings.
![Screenshot from 2023-08-23 13-26-14](https://github.com/keycloak/keycloak/assets/54103655/e402449a-a793-4566-abd7-47d0fda14e35)

It would be helpful to know under what circumstances you cannot use the "Copy to Clipboard" function.
And it would make sense to hide or disable the button afterwards.

**Comment by jonkoops** [comment]
> I have my Keycloak running under http. This means that it is not possible for me to allow the clipboard in the settings.

Hmmm, yes that seems quite a logical security measure.

> It would be helpful to know under what circumstances you cannot use the "Copy to Clipboard" function. And it would make sense to hide or disable the button afterwards.

I agree, perhaps disabling the button and adding a message like "Your browser is blocking access to the clipboard" or something. Or perhaps it's better just to hide the whole button, considering it's a progressive enhancement.

@xianli123 what is your take on this?

**Comment by xianli123** [comment]
Hi @jonkoops 
> perhaps disabling the button and adding a message like "Your browser is blocking access to the clipboard" or something

I agree with you. My concern is whether the Keycloak server can recognize the browser's limitation. If it's okay. We can go ahead with adding a message for the disabled copy icon. Does it make sense?
<img width="662" alt="Screenshot 2023-08-24 at 14 55 19" src="https://github.com/keycloak/keycloak/assets/53931519/7878e0ef-ded2-4f88-bb95-e54a40e32241">

**Comment by jonkoops** [comment]
Yes, I think that makes sense Kun. It's good to inform the user why something is not working. We can probably drop the "Error copying to clipboard" message and just leave "Your browser is blocking access to the clipboard" or something, as the user will no longer be able to click the button.

Perhaps we should also add a help link for sorts that will help the user enable this feature, but that might be a bit too much work.

> My concern is whether the Keycloak server can recognize the browser's limitation.

I think we can probably detect this by using the Permissions API (see [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#security)), but we'd have to test this in all supported browsers.

Since this is not really a bug, I am re-labeling this to an enhancement request. And considering it's a small edge case I don't think we will be getting to it soon. I'll add the help wanted label, perhaps someone would like to help fix this.

**Comment by xianli123** [comment]
> We can probably drop the "Error copying to clipboard" message and just leave "Your browser is blocking access to the clipboard" or something, as the user will no longer be able to click the button.

I agree with you.

> I think we can probably detect this by using the Permissions API (see [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#security)), but we'd have to test this in all supported browsers.

Ok. If there are any needs, please feel free to involve me.
