### ISSUE TITLE
重置密码页面login-update-password.ftl模板，如何显示邮箱email属性？

### ISSUE THREAD

**Issue by huangjy6688** [keycloak/keycloak#22643]
### Description

重置密码页面login-update-password.ftl模板，如何显示邮箱email属性？
源码是只显示username属性： <input type="text" id="username" name="username" value="${username}" autocomplete="username"  readonly="readonly" style="display:none;"/>
如何增加显示email、firstName等其他属性？
尝试使用user，user.email无效

**Comment by jonkoops** [comment]
Hi, thanks for taking the time to report an issue. Unfortunately we cannot accept issue reports in any other language than English, as that is the common language between project members. I am therefore closing this issue, feel free to report a new on in English and we will take a look at it.
