### ISSUE TITLE
Remove responsibility to watch secrets from operator

### ISSUE THREAD

**Issue by Bengreen** [keycloak/keycloak#22647]
### Description

The current implementation of the operator watches the secrets of the deployment (typically db secret and TLS secret).

These secrets are not always present at the point when the keycloak k8s object is created. And may be deployed to the cluster at a later point in time.

The operator plays a role in restarting pods for the stateful set (assuming a rolling update) when the secrets are updated.

There is discussion on moving to mounted configs where potentially the keycloak pod could be updated to observe a change to the mounted secret. That would be dependant upon that feature being added to the keycloak service implementation.

A further alternative is to allow the pod to fail itself if the relevant secrets are updated:
  This could conceptually be feasible for the db creds since changes to these could result in the db connection failing triggering the pod to restart.
  This is not likely to be the case for the TLS secret being updated. (ie there is no logical trigger that would fail in the service to trigger a restart).

### Motivation

When the secrets are updated the operator plays a role in restarting the pods with the new credentials in place.

However, there is currently an issue if the secrets do not exist before the keycloak object is created in k8s api then there is nothing to watch so when the secrets get created at some point in the future there is no trigger to update the reconciliation loop.

Options to ensure the operator is triggered to refresh the reconciliation loop when secrets can be provided late (ie after the keycloak object).

1. Watch all secrets and trigger all reconciliations that are relevant

    a. This would solve the issue at hand allowing late creation of secrets to update the reconcile loop

    b. This might be expensive if there are a lot of secrets

    c. This could be considered intrusive to watch all secrets

3. Remove the secret watching (defer that responsibility of secrets to the StatefulSet)

    a. This would solve the issue of the late creation of secrets as the reconcile loop would already be completed with a valid stahefulset (one that cannot create a pod until the secret becomes available).

    b. Updates to DB creds would automatically trigger a restart of the Keycloak pods since DB connections would be starting to fail. (Might be useful to walk this process through to make it clear).
      - When it is time to update a DB auth the updates are made to the database configuration (either directly to the DB instance, or via some automation process). The Db now has new credentials.
      - The existing services using old creds will now start to fail
      - The new DB creds shoudl be updated in the DB secret
      - As the failing services start to get recycled by k8s they will pickup the new DB creds from the secret and will return to operational state
      NOTE: In production systems it is likely that the keyclaok secretes and DB secretes will be linked together via a secrets management system automating the propagation to k8s from a single source of truth.

    c. Update to the TLS creds would not automatically trigger a restart of Keycloak as there is no relevant trigger or failure to identify.
      - This could be a good exemplar where detecting the change of the TLS secret via a change in the mounted secret woudl be a good solution.
      - If mounted secret triggering is not viable here then this woudl require intervention by the keycloak operator
      - If operator or not triggered by mounted secret change then this action woudl need to be triggered independently. Eg external trigger to apply a rolling update to the statefulset.

**Comment by shawkins** [comment]
> Options to ensure the operator is triggered to refresh the reconciliation loop when secrets can be provided late (ie after the keycloak object).

I would either re-title this discussion, or remove the discussion of watching all secrets.  Watching all secrets to me is simply an implementation detail to make secret detection event driven, rather than based upon polling.  If your goal is to advocate for the removal of watching secrets, it will make that aim clearer.

> However, there is currently an issue if the secrets do not exist before the keycloak object is created in k8s api then there is nothing to watch so when the secrets get created at some point in the future there is no trigger to update the reconciliation loop.

This is fully addressed by https://github.com/keycloak/keycloak/issues/22170 and the associated pr.  This should be linked to, or may not be needed in this discussion if it's focused only the removal of watching secrets.

2.a. is true only for required secrets.

2.b. It shouldn't be phrased as updates triggering restarts.  It's the sub-point below where the existing credentials became invalid which should cause readiness failures that will ultimately trigger the restarts.

2.c. This is the general case, which is likely applicable to other secrets used in the additionalProperties.  The first sub-point requires additional mechanics in keycloak, which I don't believe are yet present.  The second sub-point would mean that the operator is still watching secrets.

**Comment by shawkins** [comment]
Resolving as out of date - we no longer modify the secrets, and you can controll the poll interval.
