### ISSUE TITLE
Flaky test: org.keycloak.testsuite.forms.BrowserFlowTest#testAlternativeNonInteractiveExecutorInSubflow

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#22644]
## org.keycloak.testsuite.forms.BrowserFlowTest#testAlternativeNonInteractiveExecutorInSubflow
[Keycloak CI - Forms IT (firefox)]() / [Pull Request #22639](https://github.com/keycloak/keycloak/pull/22639)

```
org.openqa.selenium.TimeoutException: 
Navigation timed out after 10000 ms
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'fv-az173-551', ip: '10.1.0.25', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1041-azure', java.version: '17.0.8'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
...
```

### Notes

Note by @Aboullos 
```
On the QE team we wanted to check it this was necesary to run it on firefox as it seems to fail only on firefox. As a flaky test it is difficult to reproduce and couldn't check if it really happens for a real user.
```

I suppose we may need to doublecheck if we can reproduce on Firefox locally and see what is going on and why the test fails on Firefox. Based on that, we can check if it is the real issue or if it can be somehow "ignored" this test on Firefox.

**Comment by tkyjovsk** [comment]
https://github.com/keycloak/keycloak/actions/runs/8273367227/job/22637339894

**Comment by ahus1** [comment]
@graziang / cc: @mposolda: I saw a similar test failure in the KC22 branch. Please consider backporting it to KC22 as well. Thanks!

https://github.com/keycloak/keycloak/pull/28632#issuecomment-2050044457

**Comment by graziang** [comment]
@ahus1 Done #28670
