### ISSUE TITLE
Handle the Microsoft "Stay signed in?" dialog

### ISSUE THREAD

**Issue by tondrusk** [keycloak/keycloak#22657]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

There is an additional dialog while logging into Keycloak using Microsoft account.

![image](https://github.com/keycloak/keycloak/assets/67582554/04e26a7b-aeec-4d20-9c88-689d900efee8)

### Version

latest

### Expected behavior

The additional "Stay signed in?" dialog is handled properly.

### Actual behavior

The "Stay signed in?" dialog is not handled.

### How to Reproduce?

1. Set up the Microsoft application according to the documentation 
    https://www.keycloak.org/docs/latest/server_admin/index.html#_microsoft
    The option below must be chosen while registering an application on Azure.

    Who can use this application or access this API?
    **Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)**
3. Prepare `social.properties` file containing the required variables (e.g., Client ID, Client Secret, ...)
4. Run the testsuite with following command with your custom `social.properties` file
```
$ mvn -f testsuite/integration-arquillian/pom.xml clean install \
      -Dtest=SocialLoginTest#microsoftLogin \
      -Dsocial.config=path\to\social.properties \
      -Dbrowser=chrome
```

**Comment by ahus1** [comment]
@tondrusk @wojnarfilip - do you want to backport this to KC22? If so, please create a backport PR for this.

**Comment by wojnarfilip** [comment]
@ahus1 Thank you for the merge. We discussed this with Miquel and as this only affects testsuite, backporting probably won't be necessary.
