### ISSUE TITLE
Implementing custom ClientAuthenticator loses access to Client Secret Input Field in the Admin UI

### ISSUE THREAD

**Issue by useresd** [keycloak/keycloak#22660]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the client credentials tab, the `ClientSecret` input field in the UI is conditionally rendered with a hardcoded names of ClientAuthenticator implementation. [Link to code line](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/js/apps/admin-ui/src/clients/credentials/Credentials.tsx#L208C28-L208C28)

```jsx
{(clientAuthenticatorType === "client-secret" ||
            clientAuthenticatorType === "client-secret-jwt") && (
    <CardBody>
        <ClientSecret
            client={client}
            secret={secret}
            toggle={toggleClientSecretConfirm}
         />
    </CardBody>
)}
```

### Version

21.1.1

### Expected behavior

Client Secret conditional rendering should depend on the value of

```java
boolean supportsSecret() {
        return true;
 }
```

which is defined by the interface [ClientAuthenticatorFactory](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticatorFactory.java#L37)

This value can be brought to frontend using the existing REST endpoint that keycloak Admin UI uses to get a list of client authenticators. `/admin/realms/${realm-name}/authentication/client-authenticator-providers`

The current response of this endpoint is as follows

```json
[
    {
        "displayName": "Signed Jwt",
        "description": "Validates client based on signed JWT issued by client and signed with the Client private key",
        "id": "client-jwt"
    },
    {
        "displayName": "Client Id and Secret with license check.",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header. It also ensures the realm have a valid license.",
        "id": "client-secret-license"
    },
    {
        "displayName": "Client Id and Secret",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header",
        "id": "client-secret"
    },
    {
        "displayName": "X509 Certificate",
        "description": "Validates client based on a X509 Certificate",
        "id": "client-x509"
    },
    {
        "displayName": "Signed Jwt with Client Secret",
        "description": "Validates client based on signed JWT issued by client and signed with the Client Secret",
        "id": "client-secret-jwt"
    }
]
```

The response of this endpoint can be extended to include the the `supportsSecret` attribute as follows:

```json
[
    {
        "displayName": "Signed Jwt",
        "description": "Validates client based on signed JWT issued by client and signed with the Client private key",
        "id": "client-jwt",
        "supportsSecret": false
    },
    {
        "displayName": "Client Id and Secret with license check.",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header. It also ensures the realm have a valid license.",
        "id": "client-secret-license",
        "supportsSecret": true
    },
    {
        "displayName": "Client Id and Secret",
        "description": "Validates client based on 'client_id' and 'client_secret' sent either in request parameters or in 'Authorization: Basic' header",
        "id": "client-secret",
        "supportsSecret": true
    },
    {
        "displayName": "X509 Certificate",
        "description": "Validates client based on a X509 Certificate",
        "id": "client-x509",
        "supportsSecret": false
    },
    {
        "displayName": "Signed Jwt with Client Secret",
        "description": "Validates client based on signed JWT issued by client and signed with the Client Secret",
        "id": "client-secret-jwt",
        "supportsSecret": true
    }
]
```

Which can be done in [AuthenticationManagementResource](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L164) as follows:

```java
public Stream<Map<String, Object>> buildProviderMetadata(Stream<ProviderFactory> factories) {
        return factories.map(factory -> {
            Map<String, Object> data = new HashMap<>();
            data.put("id", factory.getId());
            ClientAuthenticatorFactory configured = (ClientAuthenticatorFactory)factory;
            data.put("description", configured.getHelpText());
            data.put("displayName", configured.getDisplayType());
            data.put("supportsSecret", configured.supportsSecret());
            return data;
       });
}
```

In the Admin UI source code, the conditional rendering of the client secret field can then depends of this value

```jsx
{(clientAuthenticatorType.supportsSecret == true) && (
    <CardBody>
        <ClientSecret
            client={client}
            secret={secret}
            toggle={toggleClientSecretConfirm}
         />
    </CardBody>
)}
```

### Actual behavior

client secret input field, will only be rendered when the PROVIDER_ID is`client-secret` or `client-secret-jwt`.

When attempted to implement ClientAuthenticator, The access to the client secret field is lost, because the provider name cannot be  `client-secret` or `client-secret-jwt`, as they are already in use.

### How to Reproduce?

Implement [ClientAuthenticator](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticator.java#L34C11-L34C11) or extend [AbstractClientAuthenticator](https://github.com/keycloak/keycloak/blob/660d17f8ec113558e520be97007f6b4a72f0fca6/services/src/main/java/org/keycloak/authentication/authenticators/client/AbstractClientAuthenticator.java#L29). Then select your new authenticator in the admin ui, in the credentials tab of the client settings. The client secret field will disappear.

![Screenshot from 2023-08-23 15-10-53](https://github.com/keycloak/keycloak/assets/19995102/ef69bbd0-b4c6-4504-94b8-96e70cace027)
![Screenshot from 2023-08-23 15-48-13](https://github.com/keycloak/keycloak/assets/19995102/1114bc7d-97f7-4e5a-add4-8f0ed7a4225a)

**Comment by jonkoops** [comment]
Thanks for the elaborate bug report @useresd, it's much appreciated! Considering you have a good idea of what the implementation should be, would you also like to create a PR?

**Comment by useresd** [comment]
Yes sure.

**Comment by jonkoops** [comment]
Perfect, then I will assign this to you. Let us know if any assistance is required :smile:

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.

**Comment by jonkoops** [comment]
Moving this to v24, as the related PR hasn't had any activity, and we are doing a release soon.
