### ISSUE TITLE
[Feature request] Manage the deployment of Postgres when creating an instance of keycloak

### ISSUE THREAD

**Issue by giacomoch** [keycloak/keycloak#22686]
### Description

Before, the user didn't have to bring their own Postgres database. Now, the user needs to get:
- Licensing for postgres
- Decide on what operator/vendor to use
- Provision and maintain the database

### Motivation

- Lower the barrier of entry for adopter
- Avoid licensing issues
- Simplified UX for provisioning an instance of keycloak

**Comment by vmuzikar** [comment]
@giacomoch Thanks for the RFE. Keycloak Operator is not a DB Operator and the intention is to keep it narrowly scoped for managing Keycloak only. That way we can fully focus on bringing the best K8s Keycloak experience without dividing our focus between Keycloak and a DB. We suggest to use a dedicated DB Operator like [Crunchy](https://github.com/CrunchyData/postgres-operator).
