### ISSUE TITLE
User attribute mapping not working when external storage provider cache policy set to NO_CACHE

### ISSUE THREAD

**Issue by roliveirad** [keycloak/keycloak#22689]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

When I add a user attribute condition to a flow, the attribute's value is not being evaluated when the UserStorageProvider has a Cache Policy of NO_CACHE.

I found a similar issue here: https://github.com/keycloak/keycloak/issues/10826 it was closed as unable to reproduce.

### Version

22.0.1

### Expected behavior

No matter what Cache Policy I choose, the user's attribute should be taken in consideration in the condition.

### Actual behavior

When choosing  "NO_CACHE" in the UserStorageProvider, the user's attribute is not evaluated in the flow condition.

### How to Reproduce?

Here is a sample with a test https://github.com/roliveirad/keycloak-cache-issue just run UserStorageProviderTest.java

**Comment by martin-kanis** [comment]
@roliveirad Thank you for the report and reproducer. The issue seems to be valid. I'm putting this into the backlog as issue seems to be present for a long time. Community contributions are welcomed.

**Comment by szsascha** [comment]
> This is probably due to how `AbstractUserAdapterFederatedStorage` handles attributes as it delegates to the underlying `UserFederatedStorageProvider`.
> 
> Did you try to override all methods that are related to returning user attributes?

This worked in my case.

I just had `public Map<String, List<String>> getAttributes()` implemented in my `AbstractUserAdapter` and was using the `UserModel.getFirstAttribute("id")` in a `RequiredActionProvider`.

`UserModel.getFirstAttribute("id")` was working with activated cache but always returned null with deactivated cache.

So I implemented the `public String getFirstAttribute(String name)` in addition to the `public Map<String, List<String>> getAttributes()` in my `AbstractUserAdapter` and anything worked fine.

**Comment by pedroigor** [comment]
Glad it worked. I'll close based on your feedback. Thanks.
