### ISSUE TITLE
Incorrect event types in the events overview (eventTypes.Refresh token error.name & eventTypes.User info refresh error.name)

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#22709]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hi,

I noticed that there are incorrect event types in the events overview. It seems that only a certain path is displayed.
I have found the following incorrect event types:
![event-type-userinfo](https://github.com/keycloak/keycloak/assets/54103655/5c9890e1-b3df-4921-ad68-eabca219cbd3)
![event-type-refresh](https://github.com/keycloak/keycloak/assets/54103655/f0e91b30-df19-4eac-8664-06a24f5632d8)

if you then search for it, there is also the error: "Network response was not OK".
![Screenshot from 2023-08-25 09-29-55](https://github.com/keycloak/keycloak/assets/54103655/0f026ee2-25dc-470b-9fb2-a837e2c25967)

### Version

22.0.1

### Expected behavior

That the faulty event types are displayed normally and you can search for them.

### Actual behavior

Incorrect event types and search errors

### How to Reproduce?

Add the event types "eventTypes.Refresh token error.name" & "eventTypes.User info request error.name" under "Realm Settings" -> "Events" -> "User Event Settings" and search for them in the events overview.

**Comment by ssilvert** [comment]
On the nightly build, I don't quite see this.  

What I do see is that in `Realm settings --> Events --> User event settings` I see a couple of events that aren't mapped to their localized names and descriptions.

eventTypes.PUSHED_AUTHORIZATION_REQUEST.name
eventTypes.PUSHED_AUTHORIZATION_REQUEST.description
eventTypes.PUSHED_AUTHORIZATION_REQUEST_ERROR.name
eventTypes.PUSHED_AUTHORIZATION_REQUEST_ERROR.description

So when you go to search for them, the dropdown shows the names above.

Searching seems to work just fine.

Can you try this on the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by agagancarczyk** [comment]
@npriebe I have checked your issue in our nightly and I can't reproduce it, please see attached. 

@ssilvert I don't see what you see in the latest nightly.

![Screenshot 2023-08-29 at 13 30 01](https://github.com/keycloak/keycloak/assets/4890675/481122af-0476-471a-a671-7a7120f2f4ec)
 
![Screenshot 2023-08-29 at 13 32 37](https://github.com/keycloak/keycloak/assets/4890675/e87ccd67-9d4a-425d-aa33-05dff2e75d2c)

**Comment by agagancarczyk** [comment]
Thanks @ssilvert I can see this now. In fact, I've noticed a few unmapped event types in the `Add types` dialog even before adding them. I'll work on addressing this issue.

![Screenshot 2023-08-30 at 09 14 04](https://github.com/keycloak/keycloak/assets/4890675/7b2e4612-d679-465d-8c10-f883935d8c38)
