### ISSUE TITLE
REST API returns different amount of users

### ISSUE THREAD

**Issue by BbIKTOP** [keycloak/keycloak#22719]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/api

### Describe the bug

I use Keycloak 16.1.1 jboss image in docker and have strange problem. I have created some users for testing. Also I have created service client account to use with REST API. It created a user for that, with name service-account-clientname

Problem: via REST API, when I use GET /admin/realms/{realm}/users endpoint, Keycloak returns all users except this service account user. But when I use the same endpoint with empty 'username' query parameter, it returns the same list of users plus this service user as well.

Also, /admin/realms/{realm}/users/count returns count value without service accounts.

### Version

16.1.1

### Expected behavior

The same amount of users returned for any kind of full queries

### Actual behavior

Different amount returned 

### How to Reproduce?

Install new keycloak instance. Add 3-4 users. Add service client. Query users count, users list unfiltered and users list filtered by username="". Observe that filtered query returns service user, as others do not.

**Comment by jonkoops** [comment]
Have you been able to reproduce this issue in the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by BbIKTOP** [comment]
> Have you been able to reproduce this issue in the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)?

Sorry, really have no time for that.

**Comment by jonkoops** [comment]
Then I am closing this issue. We don't provide support on older versions of Keycloak, as we simply do not have the capacity for it. Feel free to report a new issue if the problem persists in the latest version of Keycloak.

**Comment by BbIKTOP** [comment]
Fair enough. Although as a devs you should be also interested in bug fixing. I've downloaded 22.0.1 and it has the same problem. I suppose, devs have dev env installed and it couldn't take more than a few minutes to check. I bet it won't work either.

**Comment by jonkoops** [comment]
Thanks for checking this on the latest version. As mentioned before, we are simply already too busy fixing existing issues to verify new ones on anything but the latest version of Keycoak, and as you mentioned 'it couldn't take more than a few minutes to check', so reporters of issues can help us out as well, so we can spend more time fixing bugs.

**Comment by BbIKTOP** [comment]
Jon, we all are busy, I understand. I had some opensorce projects  back in 90's so i do understand really. Could you merge please?

**Comment by jonkoops** [comment]
Your work will be merged when the team has time to review it.

**Comment by BbIKTOP** [comment]
may i ask what is usual average time for that? need to understand shall i wait or just use my fixed version. this bug is blocking my project a little bit, thats why im asking. thank you!

**Comment by BbIKTOP** [comment]
well, will wait then, thank you
