### ISSUE TITLE
Enable theme caches by default in start-dev

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#22711]
### Description

Currently theme caching is disabled by default in start-dev:

https://github.com/keycloak/keycloak/blob/e9accaf387471d4baf227cb3a138ffdcc4a8474f/quarkus/runtime/src/main/resources/META-INF/keycloak.conf#L9-L11

Disabling theme caching will have a negative impact on loading the UIs, especially admin and account that loads a fairly big amount of resources. In most cases a developer is not using start-dev with the intention of creating/editing themes, and as such by default we should prioritise performance over convenience.

I would consider adding a top-level config option around themes, elevating the SPI options to a higher level. Something like:

```
theme-cache=true|false
theme-cache-themes=true|false
theme-cache-templates=true|false
theme-cache-client-gzip=true|false
theme-cache-client-max-age=<number>
```

Where `theme-cache` is a convenience option that fully disables all caching, so basically a short-hand to:

```
theme-cache-themes=false
theme-cache-templates=false
theme-cache-client-gzip=false
theme-cache-client-max-age=-1
```

Currently the existing options are awkward and isn't documented in the server guides:

```
spi-theme-cache-themes=false
spi-theme-cache-templates=false
spi-theme-static-max-age=-1
```

**Comment by pedroigor** [comment]
I'm not against having a `Theme` category to expose options related to themes. However, I'm more in favor of keeping the cache disabled by default as it makes the experience better during theme|core development. It is one less thing to worry about when setting up an environment.

The performance penalty is a trade-off that I don't see a considerable impact too much on the runtime, for development.

**Comment by vmuzikar** [comment]
+1 for adding top-level theme options
+1 for keeping uncached themes in start-dev
