### ISSUE TITLE
Incorrect authServerUrl preventing access to admin

### ISSUE THREAD

**Issue by clifff** [keycloak/keycloak#22727]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I'm running Keycloak in k8s, with an Nginx ingress. My intent is for the administrative console to be blocked from the public using Nginx, and to use `kubectl port-forward` in order to access it via localhost. My current configuration:

```
KC_HOSTNAME_ADMIN_URL: http://localhost:8080
KC_HOSTNAME_STRICT: "false"
KC_HOSTNAME_STRICT_HTTPS: "false"
KC_HOSTNAME_URL: https://public-website.com
KC_HTTP_ENABLED: "true"
KC_PROXY: "edge"
```

The current configuration works well when accessed from `https://public-website.com`, but when I try to access the admin screens using `kubectl port-forward`, a request to `/realms/master/protocol/openid-connect/3p-cookies/step1.html` fails and prevents the interface from loading. 

A little investigating reveals that it's using `authServerUrl` to load this endpoint. As rendered on the page:

```
{
  "loginRealm": "master",
  "clientId": "security-admin-console",
  "authServerUrl": "http://localhost",
  "authUrl": "http://localhost:8080",
  "consoleBaseUrl": "/admin/master/console/",
  "resourceUrl": "/resources/j35ym/admin/keycloak.v2",
  "masterRealm": "master",
  "resourceVersion": "j35ym",
  "logo": "",
  "logoUrl": ""
}
```

And the output from the hostname debugging tool:

![Screenshot 2023-08-25 at 1 24 09 PM](https://github.com/keycloak/keycloak/assets/51312/08e453a3-b7e2-46e9-a12b-6adb396d8158)

I should note that I'm actually port-forwarding through an Nginx container that is adding the `X-Forwarded-*` headers because I thought it may fix this, but it does not.

### Version

22.0.1

### Expected behavior

The `authUrl` should include port `8080`, since that is where the request is coming from.

### Actual behavior

The `authUrl` does not include any port, which causes out of band access to fail.

### How to Reproduce?

Configure KC with similar settings:

```
KC_HOSTNAME_ADMIN_URL: http://localhost:8080
KC_HOSTNAME_STRICT: "false"
KC_HOSTNAME_STRICT_HTTPS: "false"
KC_HOSTNAME_URL: https://public-website.com
KC_HTTP_ENABLED: "true"
KC_PROXY: "edge"
```

And then use `kubectl port-forward` to try and access the the admin interface.

**Comment by ssilvert** [comment]
@clifff Have you taken a look at this?
https://github.com/keycloak/keycloak/issues/14666

**Comment by clifff** [comment]
@ssilvert I did, but didn't find anything that worked in there

After some more trial and error, it seems that removing `KC_HOSTNAME_URL` and relying on the frontendUrl setting for our public realm (and I think, `KC_PROXY` being configured + forwarding headers being sent) got this working, so going to close this issue
