### ISSUE TITLE
Multiple hostnames on Keyclaoak 22 version

### ISSUE THREAD

**Issue by tajeddin96** [keycloak/keycloak#22734]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Keyclaok in latest version didn't work with multiple hostnames on the same realm, each client has a hostname

### Version

22.0.1

### Expected behavior

in Keycloak version `11.0.2` we used to set a hostname for each client in the same realm

```
a.com
b.com
```

### Actual behavior

when user login to `a.com`, the same session will give the user access to `b.com`

### How to Reproduce?

try to host 2 sites with 2 different domains Ex: a.com / b.com and try to redirect users to login page with these domains a.com/auth ... b.com/auth....
not to the keycloak hostname Ex: x.com

**Comment by pedroigor** [comment]
@tajeddin96 Not sure I'm following the report because it is expected for users to seamlessly authenticate if they are already authenticated at the server (single sign-on).

**Comment by stianst** [comment]
Keycloak has never supported configuring multiple hostnames for a single realm.  What you can do, and this has not changed, is use dynamic resolution of the hostname by disabling hostname-strict. This will allow Keycloak to use either a.com or b.com. However, this opens a vulnerability as the hostname can be manipulated through http headers. You need to either protect against this in the reverse proxy, or you need to implement a custom hostname provider.

This is expected behavior as Keycloak has not supported multiple hostnames.

**Comment by sklroman** [comment]
> Keycloak has never supported configuring multiple hostnames

 in older versions, to access multiple domains you could use:
>subsystem xmlns="urn:jboss:domain:undertow...
>server name="default-server"
>host name="default-host" alias="domain1,domain2,localhost"

(at standalone.xml)

**Comment by ch4mpy** [comment]
> End of the day though there are no real benefits of hosting Keycloak on multiple endpoints

@stianst I don't agree with that: there is a very low limit to the maximum number of realms on a Keycloak instance. So, when running a SaaS, going for a realm per "Business clients" is not an option and one then has to fallback to an OAuth2 client per "Business clients" with all end users (aka "Consumers" in a B2C SaaS) in the same realm.

When branding is important to the "Business clients" subscribing to the SaaS, they want everything to be part of their own domain, including authorization server. In that case, SSO between the different "Business clients" is even undesirable.

Also, when integrating Keycloak forms in iframes, it is much easier to have the authorization server accessed with `SAMEORIGIN` (`https://some.business.com/ui` serving a SPA, `https://some.business.com/auth` as base path for Keycloak and `https://some.business.com/api` for REST resources)
