### ISSUE TITLE
Align MapStorageProvider with the changes in LDAP/Kerberos integration

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#22780]
### Description

There is PR https://github.com/keycloak/keycloak/pull/22531, which contains some changes in the legacy storage in the `UserStorageManager` related to improvements for LDAP/Kerberos integration.

This task is to add those changes also to `MapStorageProvider`. It can be possible to do this together with https://github.com/keycloak/keycloak/pull/10700 (or after that PR is merged).

**Comment by mhajas** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
