### ISSUE TITLE
Display name of attribute groups not shown in admin console

### ISSUE THREAD

**Issue by florianschiller** [keycloak/keycloak#22792]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

In Keycloak 21.1.2 and 22.0.1, admins are able to define a display name for an User Attribute Group. This display name is only used for user-facing forms and is not displayed in the admin console. In comparison, the display name of User Attributes is shown both in the admin as well as the user console.

The help text besides the field Display name on the Edit/Create attributes group page describes that field as:

> A user-friendly name for the group that should be used when rendering a group of attributes in user-facing forms. Supports keys for localized values as well. For example: ${profile.attribute.group.address}.

True to this description, the display name of a attribute group is not shown in the admin console when editing or creating a user. This feels weird, as the display name of user attributes is shown both in the user and admin console.

I can see multiple points, were showing the display name in the admin console could be useful for realm admins:

1. The general group name defined in the Name field is not editable. Changing the name without recreating the group is not possible.
2. An admin could verify the correct localisation without needing to logging in using a test account.
3. In mutlilingual teams, showing a localized text via the display name instead of the not localisable name could be useful.

Is there a specific reason, why the display name isn't shown in admin console for user attribute groups?

### Version

21.1.2

### Expected behavior

The display names of user attribute groups are displayed on the details page of a user in the admin console.

### Actual behavior

The display names of user attribute groups are not displayed on the details page of a user in the admin console.

### How to Reproduce?

- In the admin console, enable user profiles and go to the user profile tab
- Add a new user attribute group with any display name
- Assign a user attribute to this new group
- Go to the details page of any user
- The display name of the group isn't displayed

### Anything else?

This was previously created as an enhancement, but was recreated as a bug because of missing feedback.
See: https://github.com/keycloak/keycloak/issues/21744

**Comment by ssilvert** [comment]
@florianschiller I don't understand.  I'm looking at the nightly build and I see the display name of the user attribute group rendered on the user details page.  Also, it is shown in the `Jump to section` list on the right side of the screen.

I will say that I also checked this in account console with `keycloak.v3` theme and the attribute group is not implemented.

Have you tried the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by edewit** [comment]
It's shown in the admin ui:
![image](https://github.com/keycloak/keycloak/assets/51133/c0c944b3-f43c-4e7b-99a3-d744736df8ff)

**Comment by ssilvert** [comment]
@florianschiller I believe this is working as designed, so I'm closing now.  If you are still having a problem then we can reopen if needed.

FYI, we are planning to implement this in account console.
