### ISSUE TITLE
Since KC 21.1.2, no access to user-panel in Admin-Console: Cannot read properties of undefined

### ISSUE THREAD

**Issue by DaBonse** [keycloak/keycloak#22803]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

since Keycloak 21 we get no access to the user panel in Admin-Console in our realm. The master realm works fine.

We get the message:

Cannot read properties of undefined (reading '0')

Chrome debug toolbar says:

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

and

TypeError: Cannot read properties of undefined (reading '0') at UsersSection.tsx:104:50 at Array.filter (<anonymous>) at UsersSection.tsx:104:26 at AdminClient.tsx:49:11

Refreshing does not change anything. All other panels work as expected.

### Version

21.1.2 Docker

### Expected behavior

User panel should load.

### Actual behavior

User panel does not load and exits with error.

### How to Reproduce?

n/a

**Comment by DaBonse** [comment]
Bug exists since version 21.1.2, in 21.0.1 the ui works fine.

**Comment by ssilvert** [comment]
@DaBonse So to be clear:

- When you go to `Users --> <username> --> Details` you see the error?
- The error only occurs on realms other than master?

It must be something in your environment that's different or I'm sure others on 21.1.2 would have reported this by now.

Have you tried 22.0.1 or the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?  We won't be fixing old community releases.

**Comment by DaBonse** [comment]
The error occurs when I go to the main menu item "Users" - I can not go deeper.

Yes, in master realm, the error is not present.

I have tested Docker version 22.0.1-2, error still exists in same manner.

**Comment by DaBonse** [comment]
Ok, I think I have found the reason on my side.

We use the keycloak-user-migration plugin here: https://github.com/daniel-frak/keycloak-user-migration and configurate it over rest api. The plugin was enabled by default, when we configurate it over rest (UI says plugin is enabled). In the past, everything works fine. The plugin also works fine.

When I do so, we get the error described above. After disable/enable the plugin in the UI, the error was gone.

I can fix my problem, when i explicit enable the plugin over rest api (option: enable = true in config array over rest).

My problem is solved for now. 

**But the behaviour of the UI seems buggy, why the UI crashes? The plugin has worked correctly - we have end-to-end tests for the plugin.**

The plugin has many config options. Not all are necessary. So, we config only the one we need over rest api. The plugin works with this setup, but i suppose the UI crashes when getting not defined config parameters. When disable/enable the plugin over UI, the missing parameters maybe will be filled with default values from the UI.

**Comment by edewit** [comment]
It's the `config.enabled` property that was mandatory for the UI, but this has been fixed now
