### ISSUE TITLE
user search with "q" parameter ignores keys of length 1 and returns all users

### ISSUE THREAD

**Issue by ddurham2** [keycloak/keycloak#22814]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

When issuing a user query with the q parameter, if the length of the attribute is 1, then all users are returned anyway.

### Version

21.1.1 / 22.0.1

### Expected behavior

querying by attributes of any length > 0 should behave consistently

### Actual behavior

querying by attributes of length 1 returns all users

### How to Reproduce?

`GET http://localhost:8080/admin/realms/master/users?q=x:foo`
unexpectedly returns all users in the realm

`GET http://localhost:8080/admin/realms/master/users?q=xx:foo`
expectedly returns no users in the realm (provided that none actually have an attribute named "xx")

### Anything else?

Spent two nights chasing everything else I suspected before something as this (bad openapi client version, bad openapi generator code, newer server version, bad mix of other query parameters, keycloak configuration, bad documentation, how "q" is or isn't uri encoded, etc)  >:-/

Also, I'm a big liar and didn't _actually_ test with the latest nightly, but got as close as I could testing against the latest docker image available to me, v22.0.1

**Comment by kaustubh-rh** [comment]
@ddurham2 yes, able to reproduce the issue also with the latest nightly release. Thanks :)
