### ISSUE TITLE
Keycloak 22.0.1 unable to create user with long email address

### ISSUE THREAD

**Issue by tangtang95** [keycloak/keycloak#22825]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

With the latest nightly release, it is no more possible to create a user with email longer than 75 characters. Moreover in 22.0.1, the limit seems to be at 87 characters. 

Meanwhile in the old version 21.1.2, it is still possible to create a user with an email longer than 87 characters.

This happens both via REST API users and on the admin UI:
![image](https://github.com/keycloak/keycloak/assets/5919707/a9254900-6d9c-43a5-bacc-9e9d71a075e2)

### Version

22.0.1

### Expected behavior

Still able to create user with more than 87 characters in the email like in 21.1.2. Not sure what was the limit before.

### Actual behavior

Unable to create user with more than 87 characters in the email.

### How to Reproduce?

- Run keycloak server
- Login and go to user section
- Try to create user with email address longer than 87 characters in 22.0.1 (or longer than 75 in nightly release)

**Comment by kaustubh-rh** [comment]
Hi @mposolda , the above-mentioned issue is reproducible , do we have to set the limit to 87 characters ?

**Comment by kaustubh-rh** [comment]
@mposolda yes ,will raise a PR for the same. Thanks :)

**Comment by pedro-hos** [comment]
Hi @kaustubh-rh and @mposolda, just a heads up, the following line limiting the character size:

https://github.com/keycloak/keycloak/blob/c92d10c750d522cd1df6f29a62f5320b49b5bafe/server-spi-private/src/main/java/org/keycloak/utils/EmailValidationUtil.java#L10

was added on PR #21131 (issue #20878). I guess that this validation is related to [RFC-3696](https://www.rfc-editor.org/rfc/rfc3696) that limits the local part in 64 characters:

> In addition to restrictions on syntax, there is a length limit on
   email addresses.  That limit is a maximum of 64 characters (octets)
   in the "local part" (before the "@") and a maximum of 255 characters
   (octets) in the domain part (after the "@") for a total length of 320
   characters.  Systems that handle email should be prepared to process
   addresses which are that long, even though they are rarely
   encountered.

So, if we'll accept more than 64 characters, we just need to change the:

https://github.com/keycloak/keycloak/blob/c92d10c750d522cd1df6f29a62f5320b49b5bafe/server-spi-private/src/main/java/org/keycloak/utils/EmailValidationUtil.java#L10

I don't know what is better, keep the limit, or increase the value.

**Comment by mposolda** [comment]
@pedro-hos Thanks for investigation of this! Is it possible to keep 64 characters by default, but allow bigger value in the configuration? Maybe some new option of the user profile provider (See for example here https://www.keycloak.org/docs/latest/server_admin/index.html#_read_only_user_attributes for some other configuration option added to this profile). So maybe something like `--spi-user-profile-declarative-user-profile-max-email-local-part-length=64` . The default value can be 64 when not filled. Not 100% sure if we need the same also for domain? I would say not as the length limit for the domain is well-known.

Will be also good to document this in the migration guide. Can you please add it to the existing `changes-22_0_2.adoc` file?

**Comment by ov-developer** [comment]
I don´t think this is fixed. The validation does also seem to validate the domain-part.
If I try to create a user with the following domain-part it fails saving:
`@this-is-a-domain-part-of-an-email-exceeding-64-characters-and-therefore-fails.com`
If I shorten it to 64 characters before the `.com` it works again.

The previously cited RFC says 255 characters in the domain part should be fine.

**Comment by shimizukawa** [comment]
RFC-3696 said..

> A DNS label may be no more than 63 octets long.  

It would be nice if Keycloak's documentation clearly states this.
