### ISSUE TITLE
Custom Provider disabled on saving a change for the first time

### ISSUE THREAD

**Issue by Saverio82** [keycloak/keycloak#22862]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

On the new Admin UI, when any change is saved for the first time on a user federation custom provider page, the enable/disable toggle is set to automatically **disable**

### Version

21.1.2

### Expected behavior

The original value for enabling/disabling the custom provider should be preserved

### Actual behavior

The original value for enabling/disabling the custom provider
it's changed to disabled even if the provider is enabled

### How to Reproduce?

1. Go to "User Federation"
2. Select the custom provider
3. Change any value
4. After saving the provider is disabled

**Comment by ssilvert** [comment]
I'm not seeing this, but I seem to remember a bug like this that was fixed.  

Please try on the nightly build and let us know what you find.
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by Saverio82** [comment]
Hi @ssilvert 

sorry for the delay in replying.
I confirm the problem on the configuration page of our custom provider for version 21.1.2. The problem does not appear on the LDAP and Kerberos configuration pages
We are trying to verify on version 22.0.2, but the migration is quite expensive given the amount of customizations.

https://github.com/keycloak/keycloak/assets/55389674/ee67e6bd-f9b9-45dc-b8c6-23563b103f18


https://github.com/keycloak/keycloak/assets/55389674/e1f51a35-2a95-4bb1-990d-9d0d1d56b2a9

I attach a video to show you what happens.

Thank you

**Comment by ssilvert** [comment]
Hi @Saverio82.  I can't justify putting more time into this if we can't verify whether or not the bug still exists in the latest version.

I think it's probably fixed, but if you upgrade and find it is still broken then we can reopen this issue again.
