### ISSUE TITLE
Not-working link during adding a SAML Identity provider

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#22892]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

The link 'SAML 2.0 Service Provider Metadata' is opening a not-found page during addition a SAML 2.0 Idp.

Most likely it's useless here.

### Version

22.0.1

### Expected behavior

If the link cannot be opened, it shouldn't exist in the 'Add' mode of 'SAML2.0' Idp addition.

### Actual behavior

The link exists, causes such page to be opened

URL: <host>/auth/realms/\<realm name\>/broker/saml/endpoint/descriptor
![изображение](https://github.com/keycloak/keycloak/assets/1285898/01ec92af-ef11-405f-b6ca-5cb5d95d7100)

### How to Reproduce?

Identity providers -> Add provider -> SAML v2.0.
Click the `SAML 2.0 Service Provider Metadata` link.
![изображение](https://github.com/keycloak/keycloak/assets/1285898/b91d77e5-55c2-444d-98a5-e017309d8550)

**Comment by kaustubh-rh** [comment]
Yes, It looks like in the earlier Keycloak version , the descriptor URL was` /auth/realms/master/broker/saml/endpoint/descriptor` which is not accessible now .

**Comment by lrozenblyum** [comment]
Interesting enough that the original bug was reproduced just in Add mode (after editing an existing identity provider the link loaded proper descriptor). I assume now everything is fine with the Edit mode with this fix? @kaustubh-rh

**Comment by kaustubh-rh** [comment]
Hi @lrozenblyum , in RH-SSO 7.6 , in the  Add mode,  SAML metadata link tab is hidden . It looks like we need to re-implement the same to fix the bug. Thanks

**Comment by jonkoops** [comment]
Marking this for back-porting, @ssilvert since you merged this one can you take care of it?

**Comment by ssilvert** [comment]
> Marking this for back-porting, @ssilvert since you merged this one can you take care of it?

Done.  #23181
