### ISSUE TITLE
Token request is denied when user has the OTP configured (and not requested)

### ISSUE THREAD

**Issue by raffaeler** [keycloak/keycloak#22901]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

I started from a brand new 22.0.1 setting up a new realm and client.

The client is configured as public (no client secret) and "Direct access grants" aka "Resource Owner Password Credentials Grant" or grant_type='password'.
The client makes the request using curl:
```
curl --location --request POST --header "Content-Type: application/x-www-form-urlencoded"
    --data-urlencode "password=xyz"
    --data-urlencode "username=aaa@bbb.com"
    --data-urlencode "client_id=Unattended"
    --data-urlencode "grant_type=password"
    --data-urlencode "scope=openid"
    "https://keycloak.local:8443/realms/Demo/protocol/openid-connect/token"
```

> As a side note, the realm declares the acr: `pwd=1` and `mfa=2`. The default is `pwd`
> Another client (but not this one) can use the OTP thanks by specifying `acr_values='mfa'`. When nothing no `acr_values` is not specified, the user authenticates with the password only.

Lastly, there are two users: 
- user A has the `Password` and `Otp` configured in her `Credentials` tab
- user B has only `Password` and no `Otp`

In this scenario, using the above curl:
1. `User A` request **fails** with `Invalid client credentials`
2. `User B` request **succeeds** in getting the token
3. If `User B` adds an Otp to its credentials, the request **fails** with `Invalid client credentials`.

_Note: I am aware that this grant_type is deprecated from oAuth2 but I am trying to understand this behavior_

Questions:
- Is this a bug / why is this happening?
- Can this happen with others `grant_type`?

### Version

22.0.1

### Expected behavior

I expect any user to be able to log-on regardless her credentials may contain the Otp secret.

### Actual behavior

Any user configuring the Otp cannot use the `grant_type=password` and gets the `Invalid client credentials` error.

### How to Reproduce?

- Create a new realm
- Create a new public client (no client secret) and "Direct access grants" selected
- Add two new users, one without otp, the other with an otp credentials. This should be done separately with the help of another client or by importing the user in the database
- Run the above curl with the correct username, password and client id

### Anything else?

As a side note, I totally agree that the error going to the user / relaying party should never contain details.
Anyway, the events inside keycloak and/or the container logs should definitely provide a better clue about the reason of a login failure.

**Comment by mposolda** [comment]
@raffaeler If your user has OTP, you may also need to use `otp` parameter and provide his OTP. Or to disable this, you can disable "Validate OTP" step in the "Direct Grant" authentication flow and then OTP won't be required. See class `ValidateOTP` from Keycloak codebase for more details.

Anyway, I agree that error "Invalid client credentials" is likely not correct and event handling can be better as well.  However this has low priority (also due the direct grant is deprecated as you pointed) and hence Keycloak team likely won't take a look in the near future. Adding to Backlog for now. Anyone is welcome to send PR with improving this.

**Comment by raffaeler** [comment]
@mposolda 
> If your user has OTP, you may also need to use `otp` parameter and provide his OTP. Or to disable this, you can disable "Validate OTP" step in the "Direct Grant" authentication flow and then OTP won't be required. See class `ValidateOTP` from Keycloak codebase for more details.

I don't believe this is the case because the user can still use username/password to login without providing the OTP even if it is configured. The OTP for this client is optional and only used for step-up authentication (when/where configured in the flows)

The whole point is that if the user uses the client certificate instead of the username and password, Keycloak pretends the OTP and makes the authentication fail.

> Anyway, I agree that error "Invalid client credentials" is likely not correct and event handling can be better as well. However this has low priority (also due the direct grant is deprecated as you pointed) and hence Keycloak team likely won't take a look in the near future. Adding to Backlog for now. Anyone is welcome to send PR with improving this.

Got it, Java is not my primary language, but I will look into it as soon as I can spend some time on it.
