### ISSUE TITLE
Use Infinispan BOM instead of direct Infinispan dependencies

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#22922]
### Description

When updating Infinispan, it needs to be aligned with one other dependency, namely Infinispan protostream.

At the moment the version declared in the Quarkus BOM is used for Infinispan and the Infinispan protostream, which is aligned with the Quarkus version of Infinispan. At the moment we want be able to use newer versions of Infinispan, see #21363.

In order to keep them aligned, attempt to use the Infinispan BOM and get rid of the separate declaration of protostream. 

When doing this, watch out for problems where it might pull properties or dependencies from its parents and grandparents. Align with the cloud native team to discuss if this approach is aligned with their efforts.

### Motivation

A misaligned protostream dependency when upgrading Infinispan causes strange follow-up errors, as seen in September 2023. 

All protostream dependencies need to be listed manually to make sure they are all set to the same version.

### Details

See #22887 for the last version upgrade of Infinispan

**Comment by ahus1** [comment]
@sguilhen  - I know that you needed to list several Infinispan dependencies manually to exclude the non-jakarta dependencies. Even after the BOM change, I assume those will stay in Keycloak's parent BOM. I'd be happy to hear your thoughts on this issue.

**Comment by sguilhen** [comment]
@ahus1 If my  memory is right I had to add `-jakarta` variants for some of the infinispan dependencies because by default they relied on javaee libs. If the bom is bringing the jakarta variants I think it might be worth testing if we can remove the deps from Keycloak's parent bom.

**Comment by ahus1** [comment]
Another mis-alignment happend with #25288 which removed the explicit setting of the protostream dependency. The protostream dependency is still include in the distribution after that change. 

Time to finally move to the bom - I'll prepare a PR for this.

**Comment by martin-kanis** [comment]
> Another mis-alignment happend with #25288 which removed the explicit setting of the protostream dependency. The protostream dependency is still include in the distribution after that change.
> 
> Time to finally move to the bom - I'll prepare a PR for this.

Did you mean by this comment that protostream dependency should not be present in the quarkus dist? Because I tried https://github.com/keycloak/keycloak/pull/26137 and it is still there.

**Comment by ahus1** [comment]
@martin-kanis - it should be present with a version matching Infinispan. In the current nightly build it is included with a path release version contributed by Quarkus, while the Infinispan version we use specifies a different patch version. 
As it is a transitive dependency of one of our infinispan dependencies, we should include it.
