### ISSUE TITLE
Incorrect help Text for the field 'Temporary' while setting password for new user

### ISSUE THREAD

**Issue by casell** [keycloak/keycloak#22924]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When clicking the help text icon message displayed is "temporaryPasswordHelpText".

![2023-09-04-104002_665x371_scrot](https://github.com/keycloak/keycloak/assets/616911/dac9002f-33f3-4b90-860d-9e8f47e24f1f)

### Version

22.0.1

### Expected behavior

Placeholder replaced with help hint

### Actual behavior

Placeholder shown instead of helping text

### How to Reproduce?

1. Create new user
2. Click Set password
3. Click on (?) button near temporary switch

**Comment by jonkoops** [comment]
Hi @casell, thanks for the bug report. I can confirm this issue is reproducible, I will see if I can create a fix for it.
