### ISSUE TITLE
API /send-verify-email not working

### ISSUE THREAD

**Issue by DaBonse** [keycloak/keycloak#22942]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/api

### Describe the bug

API Endpoint /send-verify-email sends an email, but link does not verify the email.

We have upgraded from 15.0.2 to 21+. 

In 15.0.2 we used this workflow:

1. Create user over RestApi
2. Trigger verification email over RestApi in this way:

`PUT /auth/admin/realms//users/send-verify-email`

with payload:

`['VERIFY_EMAIL']`

3. User got an email
4. user click on link in email
5. user email was verified and user was logged in

Since version 21 (we have jumped from 15 to 21) this does not work anymore. Instead, the email was send, but the verification link does nothing. After clicking, user has to log in and than the verification email comes again and only this link verified the email.

Tested with our email theme, base email theme and keycloak email theme. 

### Version

21.1.2 Docker

### Expected behavior

API request should send an email and the link should verify the users email. 

### Actual behavior

Verification link does not verify email.

### How to Reproduce?

API request, described above.

**Comment by mposolda** [comment]
I am not able to reproduce. Moreover, I can add that:
- The URL of `send-verify-email` you pointed is not correct. The correct URL is something like http://localhost:8081/auth/admin/realms/<realm>/users/<user-uuid>/send-verify-email
- There is no need to include `VERIFY_EMAIL` as the payload. When you're sending request to `send-verify-email`, it is automatically assumed that you want to send user link to verify his email. There is other endpoint `execute-actions-email`, which needs to contain all the required actions you want to perform (the endpoint `send-verify-email` is just flexible version of `execute-actions-email` right now).

What I did was:
- I have realm `master` with user `admin` and password `admin` and with user `john` with email `john@something.com` and with ID `8a8d4ef7-27b9-422c-836c-7d4937555168`.

- Then sending the requests like this (please update according to your environment):
```
export ACCESS_TOKEN=`curl -v -X POST -d 'grant_type=password&client_id=admin-cli&username=admin&password=admin' -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json" http://localhost:8081/auth/realms/master/protocol/openid-connect/token | awk -F  "\"" '{print $4}'`

curl -v -X PUT -H "Accept: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" http://localhost:8081/auth/admin/realms/master/users/8a8d4ef7-27b9-422c-836c-7d4937555168/send-verify-email
```

- Mail is sent to john@something.com

- I click on the email link and is opened in my browser. Note that I am not authenticated in this browser

- I need to approve I want to verify email

- I see message "Your account has been updated"

- After login to admin console as `admin`, I can indeed see that email of user `john` is verifed now.

Please add the details where your steps differ from mine or what you expect to behave differently.

**Comment by DaBonse** [comment]
Thanks for investigating and checking the behaviour. I have reinvestigate our API request and can now say, our API request works correct.

After investigating deeper, now I am sure the problem is not the API request, the problem is located in the templating. There were changes between version 15 and 21, and now oure implementation of the templates does not provide the correct action link in the login theme (action token is missing).

**I will close this task, because the problem has nothing to do with the /send-verify-email API.**

Again, thanks a lot for helping and clarification how the API request should be made correctly.



**note:**

I use the same API url like you, in this task I have used angel brackets, which was filtered out from github.

**Comment by tinycoding5** [comment]
When I am using this API, I am getting the executeActions email template in my mailbox.
Can you help me with this issue?
