### ISSUE TITLE
Attributes without a value set are not rendered in the account console

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#22961]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

The personal info page in Account v2 does not show attributes like `E-mail`, `First Name`, and `Last Name` if their values are undefined.

We should always show these attributes regardless of their value not being set

The exception is `Email` which should also respect the conditions around the `update-email` feature and realm settings like `Register email as username` and/or `Edit Username Allowed`. For these conditions, the UI is behaving correctly.

The check for `undefined` values for those attributes was introduced by [#12109](https://github.com/keycloak/keycloak/issues/12109). Although I did not find many issues around that, I think having those attributes always available from UI is the correct behavior.

### Version

22.0.1

### Expected behavior

The personal info page in the account console must show attributes like `E-mail`, `First Name`, and `Last Name` if their values are undefined.

### Actual behavior

The personal info page in the account console does not show attributes like `E-mail`, `First Name`, and `Last Name` if their values are undefined.

### How to Reproduce?

* Create a user and do not provide an e-mail
* The email field is not shown if you access the account console/personal info for the user

The same happens if you force the first and last name fields to null when creating the user (the admin console is passing an empty string).

**Comment by pedroigor** [comment]
@edewit The intriguing part is that we have been working like that since v18. I'm also not sure about the reason for not showing fields with undefined values.

But as you know, you might even end up with an empty form depending on how you configured the realm settings for email as username and edit username allowed.

@ioemat Looks like it will break the UI for https://github.com/keycloak/keycloak/issues/12109. Perhaps we should just accept that Account v2 is not integrated with the user profile and wait for it on Account v3?

**Comment by pedroigor** [comment]
@ioemat Looks like it will break the UI for https://github.com/keycloak/keycloak/issues/12109. Perhaps we should just accept that Account v2 is not integrated with the user profile and wait for it on Account v3?

**Comment by edewit** [comment]
Yes, I think that will be best, we only need to increase the tests for account v3 to become the main account

**Comment by pedroigor** [comment]
@sschu What do you think about this one?

**Comment by sschu** [comment]
I think that in general all attributes that can be read or set according to the user profile and/or the realm settings should be shown - editable when they can be set and as read only if they cannot be set. I think the same should also be true for the admin console, so an admin always sees the whole profile and can fill out missing values without having to add keys.

**Comment by pedroigor** [comment]
The problem is that account v2 does not support user profile and the change to not show `undefined` attributes came from @ioemat. That is why I'm asking if reverting one of the changes from you would break something there.

**Comment by sschu** [comment]
We mostly use our own fork of the account console, so changing this back should not break anything for us.

**Comment by jonkoops** [comment]
@pedroigor perhaps this one could still be backported before 22.0.2 is released?
