### ISSUE TITLE
Do not store empty attributes when updating user profile

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#22960]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When an attribute value is set to an empty string it should not be persisted.

### Version

22.0.1

### Expected behavior

Attribute values set with an empty string should not be persisted.

### Actual behavior

When an attribute value is set to an empty string it should not be persisted.

### How to Reproduce?

* Create a user and do not set any root attribute like first and last names.
* Check the response from the User API and see if these attributes are set with an empty string.

**Comment by sschu** [comment]
@pedroigor I am not sure this is the right direction to go. For us, it was a feature that all attributes we defined in the profile actually exist and we can then check whether they are actually filled. A lot of downstream code would have to be changed to check for existence of attributes first. Today, they just check if values exist. I will check back with our customers, but please hold this change until then.

**Comment by pedroigor** [comment]
@sschu Sure, I noticed it would be a breaking change for you as we are touching the code contributed by you. And I can see the reason behind it.

My main goal here is to make more consistent how attributes are handling empty values. If you look at how it works today, the `Email` field is not set if you have an empty string. However, first and last names behave differently.

This is far from ideal and we should try to make the working/behaving the same when managing their values.

Thanks for checking your side. Just marked the PR with the hold label until we decide what to do with this.
