### ISSUE TITLE
User attributes can't be saved when user profile is enabled

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#22982]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

User attributes can't be saved

### Version

main

### Expected behavior

Attributes are saved

### Actual behavior

not

### How to Reproduce?

Enable the user profile on the realm
Add a custom attribute
Open the user details
Fill the field you just created
Press save
Reload the page and see the field go blank

**Comment by jonkoops** [comment]
@edewit could you create a backport for this one?

**Comment by jonkoops** [comment]
The patch for this one cannot be cleanly applied to the release branch, so it will have to be revised. @edewit I've created #23424 and assigned it to you.
