### ISSUE TITLE
Keycloak 21.0.0 and later doesn't supports LDAPS connections to Active Directory on Windows Server 2012R2 (Connection reset)

### ISSUE THREAD

**Issue by weeix** [keycloak/keycloak#23045]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

Starting from version 21.0.0, Keycloak no longer supports LDAPS connections to Active Directory on Windows Server 2012R2.

**Screen (Keycloak 20.0.5)**:

![keycloak-20-0-5-ldap](https://github.com/keycloak/keycloak/assets/6592791/d66ea200-7cb5-4694-b34f-4196dc064622)

**Screen (Keycloak 21.0.0)**:

![keycloak-21-0-0-ldap](https://github.com/keycloak/keycloak/assets/6592791/71ef9eb4-0762-4c24-a7d8-be348ad001e1)

### Version

21.0.0 and later

### Expected behavior

Successfully connected to LDAPS

### Actual behavior

Error when trying to connect to LDAP: 'SocketReset

Log file: [keycloak-nightly-ldap.log](https://gist.github.com/weeix/5d73cfc7c0a6a0190eb134daa2827d37#file-keycloak-nightly-ldap-log)

### How to Reproduce?

1. Deploy Keycloak normally and mount the truststore file. For example, you can deploy it to a Kubernetes Cluster using [this manifest file](https://gist.github.com/weeix/5d73cfc7c0a6a0190eb134daa2827d37#file-keycloak-yaml).
2. Log in to the Keycloak administrator console.
3. Create a new realm.
4. Click on "User federation".
5. Click on "Add Ldaps providers".
6. In the "Connection URL" field, enter the URL of the AD server.
7. Click on the "Test connection" button. You should see the message "Successfully connected to LDAP".
8. Enter the "Bind DN" and "Bind credentials".
9. Click on the "Test authentication" button. You will see an error message that says "Error when trying to connect to LDAP: 'SocketReset'".

**Comment by bonnm** [comment]
Keycloak 21 images are bundled with Java 17, which is relativley new. Windows Server 2012R2 is relatively old. Your attached log indicates SSL incompatibilities. As  Windows Server 2012R2 goes out of support an October 2023, an upgrade to a newer Windows Server version is recommended and should solve the connection problems.
