### ISSUE TITLE
Quarkus IT that use Oracle DB don't work with `-Dproduct`

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#23058]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

If the Oracle driver is not included in the dist, [`OracleTest`](https://github.com/keycloak/keycloak/blob/2b4f9cf41e33b01766bac1b9123a5c50f8a1736a/quarkus/tests/integration/src/test/java/org/keycloak/it/storage/database/OracleTest.java) fails. We should take similar approach to the [MSSQL driver](https://github.com/keycloak/keycloak/pull/22986/commits/59bdaa15fe0a74f1bcae97e0c4db29515bf050ef#diff-6b0c5824a800a0027bae134fa2edbeb32a6575a5bbe3addd033a9c1a5c48787aR392-R395).

### Version

main,release/22.0.2

### Expected behavior

Test passes

### Actual behavior

Test fails

### How to Reproduce?

Run the test with dist previously built with `-Dproduct`.

**Comment by ahus1** [comment]
It might make sense to install a database driver only when the database is actually used in the test, see comment https://github.com/keycloak/keycloak/pull/22986#discussion_r1318579829 (thank you for @vmuzikar for suggesting it).
