### ISSUE TITLE
Keycloak 22.0.1- Keycloak Admin Page UI and Lables are different when logged in with Non Admin User

### ISSUE THREAD

**Issue by a9ki21023** [keycloak/keycloak#23052]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

**Problems:**
The Lables are named as clientScope instead of Client Scope
The clientScope contains protocol which is protocolTypes.openIdConnect instead of OpenIDConnect
The clientScope Explaination is clientScopeExplain Learn More

**NOTE:** The above problems are noticed only with a Realm User and not the Admin User. If i assign the admin Role Mapping to this user the UI Looks Good. 

**Non Admin User Login:**
![relam-user_screenshot](https://github.com/keycloak/keycloak/assets/139567993/24407e13-8903-4b8c-84a7-0af0a46c1673)

**Admin User Login:**
![Keycloak Admin](https://github.com/keycloak/keycloak/assets/139567993/cf608661-9cbc-41d0-87b2-222db3dc92c7)

### Version

22.0.1

### Expected behavior

Expect the UI Labels and Description to the same when logged in with Admin User or Non Admin User.

### Actual behavior

The UI, Labels for Admin user looks good. But for non Admin User the UI is distorted, The Lables and Text are not properly displayed. 

### How to Reproduce?

**Steps to Repro:**
1. Pull docker container  FROM quay.io/keycloak/keycloak:22.0.1
2. Login to Keycloak Admin Page with admin user
3. Create a new Realm Ex: Test
4. Create a new User is Master Ex: TestUser, Generate Password.
5. Assign the Realm Policies to the TestUser
6. Login with TestUser and Select the Realm Test. Notice the UI is different and Labels are different.

**Comment by ssilvert** [comment]
I'm not seeing this problem.

What is happening in your case is that the message bundles are missing or not applied. But I don't know why it is happening.

I'm not using Docker, but I don't see why that would matter.

**Comment by ssilvert** [comment]
I've reproduced this now.  It is a duplicate issue of https://github.com/keycloak/keycloak/issues/23065.

I'm going to close this one and we will fix under the other issue.
