### ISSUE TITLE
Admin console throwing 403 error when logged in for sub realm using local admin user

### ISSUE THREAD

**Issue by Snehalssg** [keycloak/keycloak#23065]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui admin/console

### Describe the bug

Login into admin console using user which is not having admin role into sub realm, throws {"error":"unknown_error"} with rendering issues on console.

Request URL:
https://<host>/auth/admin/realms/master/localization/en
Request Method:
GET
Status Code:
403

![image](https://github.com/keycloak/keycloak/assets/46847027/09597aea-7db3-4981-8a3e-6b9a4df35afa)

### Version

22.0.1

### Expected behavior

Earlier we were on 18.0.2 version and this issue was not present. After changing to 22.0.1 image resulted this issue.
Even it is replicable on base image provided  from keycloak.
It should not result into any exception after logging into console with non admin roles user.

### Actual behavior

Console is in incorrect format and throwing network error.

![image](https://github.com/keycloak/keycloak/assets/46847027/eb577249-bfd2-4a6c-84ad-48628e9b8b1a)

![image](https://github.com/keycloak/keycloak/assets/46847027/f4601869-998a-45ad-9113-8dc544963856)

### How to Reproduce?

1)Create a realm other than master
2)Add user as testadmin in master realm and in other created realm as well.
3)Assign realm-admin role to testadmin user in other realm.
4)Try to login into console using testadmin.
5)It will show up console with incorrect format
6)Inspect page and you can observe the error mentioned above.

### Anything else?

Have searched for this issue in keycloak community but didn't find any issue related to this. If someone finds it or knows if it is already fixed, please comment here with details.

**Comment by ssilvert** [comment]
I have reproduced this.  

Note to whoever fixes this.  You will not need to log into `test` realm.

Here are my steps:
1) Create `test` realm.
2) Create new user in master realm.  User will be logging into master realm.
3) Assign the `view-realm` role from the `test-realm` client.
4) Log into master realm using the new user.

It fails trying to download the resource bundle.

**Comment by Snehalssg** [comment]
Thanks for fixing this issue. Could you please let me know when it will be released ? will it be released with next 22.0.2 version?

**Comment by jonkoops** [comment]
We don't give out etas for things that still need to get fixed. It will ship when we cut a patch release after the merge.

**Comment by a9ki21023** [comment]
I pulled the latest docker build [22.0.2](https://github.com/keycloak/keycloak/releases/tag/22.0.2) and still the problem on that.

![image](https://github.com/keycloak/keycloak/assets/139567993/d3d17192-53fe-4116-a691-384f844733b9)

**Comment by Snehalssg** [comment]
@a9ki21023 ...It seems that this bug fix is not released as part of 22.0.2. You can check released notes, the bug number is not present in the list.

**Comment by jonkoops** [comment]
Looks like we missed this one, I will add it to the next patch release so it's not forgotten. @edewit can I ask you to back-port the fix for this one?

**Comment by a9ki21023** [comment]
I verified the issue on 22.0.3 bulid this morning and still see the problem. Earlier we were able to access the newly created Realm with non Admin User but now we see a network error the Realm doesn't load.

![image](https://github.com/keycloak/keycloak/assets/139567993/40927628-fb1f-4bab-9804-e0e78d815fb7)

![image](https://github.com/keycloak/keycloak/assets/139567993/ccd14876-4760-426c-aede-a34811e2144e)

**Comment by ahus1** [comment]
While this was planned for 22.0.3, that release was cut before this was backported. We will try again for 22.0.4

**Comment by Snehalssg** [comment]
@ahus1  Any eta for 22.0.4? 
We are waiting for this bug fix to be available asap.

**Comment by a9ki21023** [comment]
Is this issue expected to be fixed on 22.0.4 or 22.0.5 ?
