### ISSUE TITLE
Admin-UI: Change the order of groups with drag and drop

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#23083]
### Description

Hi,
It would be handy to be able to change the order of the groups by dragging and dropping.
For example, if you have a top group with many sub-groups, you might want to sort them in a different way. For example, to sort the groups according to their importance.

### Details

Mockup:
![Screenshot from 2023-09-08 10-45-46](https://github.com/keycloak/keycloak/assets/54103655/6d03cf21-d78c-4533-94e4-cec061a22053)
A burger menu icon lets you drag and drop a group.

**Comment by ssilvert** [comment]
The groups are already sorted in alphabetical order and you can also do searches to narrow the list.

I don't understand what additional use case is served by sorting?  

This would only affect how the group list is displayed in the UI, right?

And are you thinking that the new sorting would affect all users?  That is, you change the sort order and now all administrators will see that sort order?  Or would it only affect the sort order for that one administrator?

**Comment by npriebe** [comment]
Hi @ssilvert, sorry for the late reply.

Yes, the sorting is only for the admin ui.
I would also leave the sorting alphabetical by default. But I think there might be a use case where a custom sorting within a subgroup or something like that would make sense.
For example, to be able to map a group hierarchy within a group collection.

So by default all groups are sorted alphabetically, but there needs to be a way to move them within a group.
It would be good to be able to see when a group collection is custom sorted, so that you can reset it to the default sort with a reset button or similar.

And I think that users would benefit from this, because they would be able to choose the order in which the groups are displayed, making group management much more flexible.

**Comment by ssilvert** [comment]
@npriebe I think this would be really painful to implement if the sort order is persisted.  I'm still not sure I see the great value here.  

Can you give us a specific use case where the user can't accomplish a task almost as easily with searching/filtering?

**Comment by npriebe** [comment]
@ssilvert 
A use case that comes to mind, and that is needed in my case, is to be able to see which group in a subgroup is the most important, based on the group sorting.

Example:
If the groups are named after e.g. activities/teams.
Example structure:

- IT
  - BusinessProcess
  - Infrastructure
  - Support
  - Project

In this example, the support team is the most important, so to be able to see this at first glance, it would make sense to put it at the top.
So:

- IT
  - Support
  - BusinessProcess
  - Infrastructure
  - Project

I am aware that this is a complex feature to implement, but it would be helpful to have something like this in the future.

**Comment by ssilvert** [comment]
I don't think we could free up development resources to work on this.  

Since it is already sorted alphabetically, a workaround would be to prepend the name (maybe with numbers) such that you end up with the sorting you prefer.

01-Support
02-BusinessProcess
03-Infrastructure
04-Project
