### ISSUE TITLE
Paging through subgroups doesn't work

### ISSUE THREAD

**Issue by MartaGolabek** [keycloak/keycloak#23085]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Currently, it isn't possible to page through subgroups. Page indicator is updated, but the displayed subgroups stay the same (see attached video).

[paging-for-subgroups-not-working.webm](https://github.com/keycloak/keycloak/assets/15276644/55d9cc44-b325-4116-b4ed-b58fb6f3b4de)

### Version

21.0.1

### Expected behavior

It should be possible to page through subgroups.

### Actual behavior

Paging through subgroups isn't possible.

### How to Reproduce?

1. Go to a group with many subgroups
2. Try to page through subgroups

**Comment by kaustubh-rh** [comment]
Hi @MartaGolabek  , I tried to reproduce the issue with the exact same steps as in the video on Chrome 116.0.5845.179 and Safari 16.6  , but unfortunately I am unable to . Can you share the browser and the version where it's reproducible ? Thanks :)

**Comment by MartaGolabek** [comment]
@ssilvert after updating keycloak to 22.0.3, it works as expected :) Thanks!
