### ISSUE TITLE
Write announcement for new welcome theme

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#23095]
The new welcome theme that was added under #21343 will need to be announced so that users are made aware of it. We'll need to have a blog post for the next major of Keycloak with:

- A screenshot of the new UI and how it looks.
- A short piece of copy detailing why this upgrade was done, mentioning the PatternFly 5 upgrade (welcome was still stuck on PatternFly 3).

**Comment by jonkoops** [comment]
Revised the description of this issue, as we decided not to feature flag the new welcome page. The new code should remain compatible with existing custom welcome themes, so no additional migration will be required for users that customize this.

**Comment by thomasdarimont** [comment]
Could you perhaps add a screenshot to this issue, such that users without figma access could get a first glance?

**Comment by jonkoops** [comment]
There is currently a PR to implement this new Welcome screen under #25420, which includes screenshots of every possible state in the description.
