### ISSUE TITLE
Custom user provider doesn't work when setting the store to anything other than empty

### ISSUE THREAD

**Issue by sillen102** [keycloak/keycloak#23108]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

I'm running Keycloak 22.0.1 in Docker and have implemented a custom user provider. Everything in it works just fine however when I try to set the KC_STORAGE environment flag the users cannot sync. The only error I get is "Could not sync users: "HTTP 404 Not Found".

I have tried setting the KC_STORAGE to jpa and hotrod and both produce the same result. So the only way I can work with my user provider is by having the KC_STORAGE set to empty but then Keycloak can't persist sessions, realms etc. between runs.

### Version

22.0.1

### Expected behavior

I'm expecting the user provider to sync users properly regardless of storage setting.

### Actual behavior

The user provider refuses to sync users to Keycloak.

### How to Reproduce?

Set the KC_STORAGE flag to jpa or hotrod when running Keycloak in Docker while using a custom user provider.

### Anything else?

![image](https://github.com/keycloak/keycloak/assets/44360609/51ab7543-aba1-4f73-b8c1-f97c42f96892)

**Comment by ahus1** [comment]
@sillen102 - thanks for reaching out. The custom user providers only work with the legacy store. They don't work when setting the new store with KC_STORAGE. 

Closing this as it is not supposed to work that way. The new store is still in development. For now, please use the legacy store.
