### ISSUE TITLE
step1.html not being loaded

### ISSUE THREAD

**Issue by ccpatrut** [keycloak/keycloak#23110]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

Hi, 
Despite multiple isssues being reported and mentioning that the issue is solved I cannot in any ways get the step1.html. 
Have a look on the attached screenshots.

It is like all the mapping under OIDCLoginProtocolService.java don't work.

![image](https://github.com/keycloak/keycloak/assets/44428503/4f50db11-fd2b-4bf8-a7fa-a12d2e2aa8b2)

<img width="959" alt="image" src="https://github.com/keycloak/keycloak/assets/44428503/c80a4bf3-82fa-41e7-8983-7a2c8e7dc333">

### Version

22.0.1

### Expected behavior

The step1.html can be fetched

### Actual behavior

I receive a 401

### How to Reproduce?

just make a call to http://localhost:8080/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html

### Anything else?

couldn't have it ran with the docker image nor with the source code built and running locall.y

**Comment by pedro-hos** [comment]
hi @ccpatrut, give it a try and remove the `auth` from our request: `http://localhost:8080/realms/master/protocol/openid-connect/3p-cookies/step1.html`., The new default path in the Keycloak is `/`, see https://www.keycloak.org/migration/migrating-to-quarkus

**Comment by ccpatrut** [comment]
Hi @pedro-hos ,

Thanks a lot, that helped me and the issue is now fixed.

**Comment by ccpatrut** [comment]
Hi @pedro-hos 
any idea why https://www.npmjs.com/package/keycloak-js?activeTab=versions still include auth in the path?

**Comment by pedro-hos** [comment]
@pedroigor, @mhajas do you know who take care of js adapter?

**Comment by LakshmiPhani7680** [comment]
Hi @pedro-hos , @pedroigor , @mhajas :
We want to add X-Frame-Options and CSP headers for the /auth/realms/master/protocol/openid-connect/3p-cookies/step1.html this path of keycloak how to add them? in master settings we have added already the response headers and they are getting reflected for all other paths except this 3p-cookies one, can you please respond on this?
Thank you

**Comment by mhajas** [comment]
@LakshmiPhani7680 This is not the correct place to ask questions. Could you please use some other channel? 

The best option is probably to start a new GitHub discussion: https://github.com/keycloak/keycloak/discussions or refer to other channels here: https://www.keycloak.org/community

**Comment by LakshmiPhani7680** [comment]
Hi @mhajas,
done created new discussion, Thank you for the response.
