### ISSUE TITLE
Failure in identity_providers_test.spec.ts

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#23118]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

Started failing after [Add old LinkedIn provider to the deprecated profile](https://github.com/keycloak/keycloak/actions/runs/6121795892) was merged

### Version

main

### Expected behavior

Test pass

### Actual behavior

Test failing

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/6142688749/job/16664991726

**Comment by jonkoops** [comment]
Closing this, as it has already been fixed in `main`.
