### ISSUE TITLE
Remove depecrated LinkedIn social identity provider

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak#23127]
### Description

After deprecating the old LinkedIn social identity provider based on OAuth 2.0 in https://github.com/keycloak/keycloak/issues/23067, the old provider should be removed. This is the tracking issue for removing it definitely. I will assign it to keycloak 25 (two versions) when the version is available.

**Comment by jonkoops** [comment]
@rmartinc since this was deprecated in 22.0.2, should we perhaps remove this in Keycloak 24 instead of 25?
