### ISSUE TITLE
Extend the REST API for FedCM

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#23141]
As part of implementing the Federated Credential Management API (see #16834), we will have to extend the REST API with new endpoints and fields to support it.

Ideally we would have a separate 'protocol' specifically for FedCM, for example:

- `https://keycloak.org/realms/master/protocol/fed-cm`

Until the specification and our implementation is considered stable we'll have to put this functionality behind [a profile](https://github.com/keycloak/keycloak/blob/63fc38ca1f0db9d9774ad9a8f50bb9cc8f7a4d13/common/src/main/java/org/keycloak/common/Profile.java#L41) (e.g. `Profile.FEDERATED_CREDENTIAL_MANAGEMENT`).

For this we'll need the following:

### A well-known file

- Can we do this on per realm basis, or does it need to be in the root?

For more information see the developer documentation: https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#well-known-file

### An endpoint for the config file

- For now let's only implement required fields (TODO, create an issue for the optional ones)

For more information see the developer documentation: https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#idp-config-file

### An endpoint for the accounts list

- In Keycloak the e-mail of a user is not required, so we'll likely have to filter those users out.
- For `approved_clients` we can probably return all clients in a realm (TODO find out if this can be restricted).

For more information see the developer documentation: https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#accounts-list-endpoint

### An endpoint for ID assertion

- Let's skip the `nonce` for now (TODO create an issue to do this later)

For more information see the developer documentation: https://developer.chrome.com/docs/privacy-sandbox/fedcm-developer-guide/#id-assertion-endpoint

**Comment by stianst** [comment]
Quick point from me; this really needs to be a new protocol, which also means a new protocol to be supported for clients. This opens a bit of a can of worms as that results in new client attributes, new UI screens, etc.

**Comment by jonkoops** [comment]
> Quick point from me; this really needs to be a new protocol, which also means a new protocol to be supported for clients. This opens a bit of a can of worms as that results in new client attributes, new UI screens, etc.

I can step up to help with any changes we might need to make to the Administration Console. But yeah, seems like it would be more involved than originally expected.

**Comment by jonkoops** [comment]
Agreed, this might also impact proxy configurations, so it's something to look into.

**Comment by vaceksimon** [comment]
> Well-known endpoint is a bit of an issue if that has to be at the root. We can't really have a non-realm specific well-known endpoint

Yes, the well-known file has to be served at root. Specifically at `/.well-known/web-identity`

> , which means we'd probably need to figure out a way for a realm to be served from something like `https://myrealm.company.org` instead of `https://www.mycompany.org/myrealm`

This wouldn't be helpful to us because `https://myrealm.company.org/.well-known/web-identity` still wouldn't be at root. It must be served from [eTLD+1](https://web.dev/articles/same-site-same-origin#same_site_cross_site) of Keycloak.

I was thinking of an approach similar to the `serverinfo` endpoint, but that needs authentication to access. Is it possible to have a global endpoint independent of a realm?

**Comment by stianst** [comment]
Not really sure what we can do then, as the web-identity file will contain links that are realm specific. We could set some sort of default realm for it, but that would limit it so only a single realm can leverage FedCM

**Comment by jonkoops** [comment]
Yeah, let's only list the realms that are configured to use FedCM. Perhaps we can add a 'Enable Identity Federation' toggle in the realm settings to gate this.

**Comment by jonkoops** [comment]
@vaceksimon let me know if you need some help with the implementation, if you have a WIP implementation I can certainly help out with things like the UI and general code review work.
