### ISSUE TITLE
Account merging causes existing username to be deleted 

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#23151]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

saml

### Describe the bug

When an "Attribute Importer" mapper is used with an Identity Provider, if the "User Attribute Name" target is `username`, the account merging process (when the user already exists in Keycloak) causes the Keycloak username to be deleted, which, among other things, renders the Admin UI User screen unusable, as you can no longer click on the user record.

### Version

22.0.2

### Expected behavior

The existing Keycloak user should have its username updated to the value emitted by the Identity Provider Mapper.

### Actual behavior

The account merging process (when the user already exists in Keycloak) causes the Keycloak username to be deleted.

### How to Reproduce?

1. Create a SAML Identity Provider configuration with a "Attribute Importer" mapper for the `username` field. E.g.
![image](https://github.com/keycloak/keycloak/assets/244253/965da72b-5c4b-42c6-8e2d-d72334f664d7)

2. Create a user in the Admin UI with a username that is the same as the username in the Identity Provider you have configured. Create credentials for this user.

3. Log in to the account console using the configured identity provider. When challenged with "Account already exists". Click "Review Profile". Note that the username is correctly populated. Click "Submit" and then "Add to existing account". Note in the account console that the username is now blank.
![image](https://github.com/keycloak/keycloak/assets/244253/d46428e9-dcf5-47ac-a6df-3bc8c38145cb)

5. Go to the user page of the Admin UI and view the user list. Note that there is no longer a username to click on in the list.
![Screenshot from 2023-09-11 20-13-08](https://github.com/keycloak/keycloak/assets/244253/da432d30-e16a-428b-bd13-a941e183bfa8)

**Comment by pedroigor** [comment]
@xgp Perhaps because I'm using an OIDC broker but I can't reproduce the issue using the nightly or the latest version. Could you please confirm the issue is no longer happening?

**Comment by xgp** [comment]
@pedroigor Can no longer reproduce on 23 or nightly. Thanks!
