### ISSUE TITLE
Docs: authorization_services/topics/service-authorization-obtaining-permission.adoc

### ISSUE THREAD

**Issue by vscatarino** [keycloak/keycloak#23153]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

File: authorization_services/topics/service-authorization-obtaining-permission.adoc

### Version

22.0.2

### Expected behavior

I should find a way to grant permission to a user.

### Actual behavior

I'm trying grant permission to an user:

- First, I generate a permission ticket
- Second, I try to associate the ticket with an user 

I'm following the documentation steps but it's not working for me.

### How to Reproduce?

I created two users (luiz and vinicius) and on resource (Alice Resource)
The owner from resource is luiz.

I did this request to create Alice Resource:
```
 curl --location 'http://localhost:8081/auth/realms/globex-corporation/authz/protection/resource_set' \
--header 'Authorization: Bearer <client-token> \
--header 'Content-Type: application/json' \
--data '{
     "name":"Alice Resource",
     "owner": "luiz",
     "ownerManagedAccess": true
  }'
```

Then, I got the luiz's access token with this request: 

```
curl --location 'http://localhost:8081/auth/realms/globex-corporation/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=quarkus-be' \
--data-urlencode 'client_secret=<client_secret>' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=luiz' \
--data-urlencode 'password=password'
```

With luiz's access token in my possession, I made a request to create a permission token: 

```
curl --location 'http://localhost:8081/auth/realms/globex-corporation/authz/protection/permission' \
--header 'Authorization: Bearer <luiz's-access-token> \
--header 'Content-Type: application/json' \
--data '[
  {
    "resource_id": "257a0283-b254-40b3-9961-aa9428379a49",
    "resource_scopes": ["view"],
    "claims": {
        "organizations": ["e16c433b-5d1e-4c53-8ffb-ddd25bc176c0"]
    }
  }
]'
```
So, I obtained vinicius's access token and tried to obtain the RPT.

```
curl --location 'http://localhost:8081/auth/realms/globex-corporation/protocol/openid-connect/token' \
--header 'Authorization: Bearer <vincius'-access-token> \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:uma-ticket' \
--data-urlencode 'ticket=<permission-ticket>'
--data-urlencode 'submit_request=true'
```

I received that response

```
{
    "error": "access_denied",
    "error_description": "request_submitted"
}
```
This is luiz's manage account view 
![image](https://github.com/keycloak/keycloak/assets/20404342/0e45f7ea-40ab-48c0-9f32-ba728c316d33)

There isn't any permission request there.

**Comment by pedroigor** [comment]
@vscatarino The steps look fine to me. Not sure what I'm missing when trying to reproduce the issue using the same steps. We are also extensively testing this in our test suite.

I did manage to see the permission request at the owner's account but I think there are some issues when rendering scopes.
