### ISSUE TITLE
installation stuck at proxy downloading

### ISSUE THREAD

**Issue by crombus** [keycloak/keycloak#23168]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

I am following the steps on master

mvn clean package -Dquarkus.container-image.build=true

[INFO] Installing node version v18.17.1
[INFO] Downloading https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.gz to /root/.m2/repository/com/github/eirslett/node/18.17.1/node-18.17.1-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly

### Version

master

### Expected behavior

it should pass through and give image

### Actual behavior

stuck at 
[INFO] Installing node version v18.17.1
[INFO] Downloading https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.gz to /root/.m2/repository/com/github/eirslett/node/18.17.1/node-18.17.1-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly

### How to Reproduce?

just installation step
mvn clean package -Dquarkus.container-image.build=true

**Comment by jonkoops** [comment]
This doesn't seem like a bug in Keycloak, but rather the frontend plugin. I am unable to reproduce this locally. I would recommend that you clean out your workspace with `git clean -xdf` and try again.

**Comment by crombus** [comment]
@jonkoops ,  I just want the docker image, that project pushes to quay, can you please tell what are the steps to do that.

**Comment by jonkoops** [comment]
@crombus if you are looking for help I would recommend that you start a discussion in the [Keycloak community](https://www.keycloak.org/community). The issue tracker is meant for issues in Keycloak itself.
