### ISSUE TITLE
kcadm should have a command to verify connection

### ISSUE THREAD

**Issue by jesperronn** [keycloak/keycloak#23179]
### Description

currently, you need to "prefix" a command with a login to make sure the connection is up. However, logins are expensive and unnecessary if you are already logged in.

I would love a command to verify that I am logged in. Could be something like:

`kcadm config credentials --status`

```
# not logged in:
$ kcadm config credentials --status
not logged in 

# logged in:
$ kcadm config credentials --server http://127.0.0.1:8080/auth --realm master --user admin --password admin

$ kcadm config credentials --status
logged in (server: http://127.0.0.1:8080/auth, realm: master, expired: false, exp: "2 minutes from now")
```

**Comment by shawkins** [comment]
~priority-normal

**Comment by shawkins** [comment]
Taking out of triage as this appears to be a valid enhancement request, but it may have not enough prioritization to be addressed anytime soon. Added the help wanted label as well.

This kind of thing will get easier now that the aesh replacement has happened. After the further refactoring of the two clients would be a good time to consider this.

**Comment by keshavprashantdeshpande** [comment]
@shawkins Can I pickup this issue now or the refactoring still needs to be done?

**Comment by shawkins** [comment]
@keshavprashantdeshpande no additional refactoring is expected. The kcadm code is stable again.

**Comment by keshavprashantdeshpande** [comment]
@vmuzikar @shawkins Can you please assign this issue to me? I would like to work on this issue.

**Comment by shawkins** [comment]
> @vmuzikar @shawkins Can you please assign this issue to me? I would like to work on this issue.

Sure, thank you for looking into this @keshavprashantdeshpande
