### ISSUE TITLE
crypto/elytron package has several bugs

### ISSUE THREAD

**Issue by david-rh** [keycloak/keycloak#23173]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

The crypto/elytron package was created as a potential option to supporting crypto functions without the need to hardcode dependencies to either BC or BCFIPS. This would allow the user to configure their preferred crypto provider. But, due to limitations (mostly with the OpenJDK FIPS provider) , this package is not ready for use. That said, as the dev of this package, I have done some additional testing and found that a few issues that I need to fix. A key issue is a  failure to provide a complete and thorough implementation parsing DER elements.

### Version

latest

### Expected behavior

DER elements from certs are parsed correctly.

### Actual behavior

The DER element parsing was either wrong, or specific to a given test cert and unable to handle other variations.

### How to Reproduce?

Tested by switching keycloak to use the crytpo/elytron package instead of BC(FIPS). And running unit and integration tests.

**Comment by pedroigor** [comment]
@david-rh @mposolda Do we want tests running on this provider as well?
