### ISSUE TITLE
TypeError in user profile admin-ui

### ISSUE THREAD

**Issue by gwelch-contegix** [keycloak/keycloak#23180]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

There is a JS type exception when viewing a users profile

### Version

22.0.3

### Expected behavior

User profile is shown

### Actual behavior

JS Exception
```
TypeError: Cannot read properties of undefined (reading 'options')
    at P (SelectComponent.tsx:16:63)
    at Xh (react-dom.production.min.js:167:137)
    at Wk (react-dom.production.min.js:290:337)
    at Vk (react-dom.production.min.js:280:389)
    at Uk (react-dom.production.min.js:280:320)
    at Jk (react-dom.production.min.js:280:180)
    at Fk (react-dom.production.min.js:273:245)
    at jg (react-dom.production.min.js:127:105)
    at mh (react-dom.production.min.js:266:390)
    at ri (react-dom.production.min.js:181:441)
```
JS debugger shows that there is no `validations` property only a `validators` property and seems to be part of the issue.
<img width="665" alt="Screenshot 2023-09-12 at 10 30 04" src="https://github.com/keycloak/keycloak/assets/111144057/88f8eeb5-10a3-46d9-a9b6-d6d2adf05ab2">

The nightly no longer crashes but does not provide the options making the input useless
<img width="712" alt="Screenshot 2023-09-12 at 13 06 44" src="https://github.com/keycloak/keycloak/assets/111144057/58051b29-f753-430e-88a0-b621fb1095bc">

### How to Reproduce?

Enable user profile.
Add an attribute with an options validator
Open a user profile.
Page has a TypeError blocking access to the page

### Anything else?

#22803 has a similar error message but this issue only happens on >=22.0.2

**Comment by rene6502** [comment]
For me this is a blocking issue.
I cannot edit any of our users which is an essential function.
Is there any workaround other than rolling back to 22.0.1?

**Comment by jonkoops** [comment]
> Is there any workaround other than rolling back to 22.0.1?

No, you'll have to wait until this is fixed and released.

**Comment by jonkoops** [comment]
@edewit can you create a backport for this?

**Comment by wojmaz** [comment]
This issue was blocking upgrade for us,  I updated to 22.0.4 and unfortunately it still exists. 
It seems that the commit is not in the 22.0.4? 
I can see the change in main, but it's not in 22.0.4 tag, nor in the 22.0.4-release source files

**Comment by jonkoops** [comment]
This commit [was backported](https://github.com/keycloak/keycloak/commits/22.0.4) to 22.0.4, but it was never the whole fix. We are working on a rather large change that will fix a slew of bugs related to user profile under #23537, which should land for 22.0.5.

**Comment by gwelch-contegix** [comment]
The backport missed the reference in SelectComponent.tsx. I look forward to the 22.0.5 release

**Comment by jonkoops** [comment]
@gwelch-contegix not sure what you mean here, can you link to the code that should have been backported?

**Comment by gwelch-contegix** [comment]
@jonkoops 
4 files are listed in #23250 the initial fix. There are 3 files are listed in #23628 the backport
The file missing is `SelectComponent.tsx`. Which is the file causing the error that I opened this ticket for, as shown by the stack trace in my original post:
> JS Exception
> ```
> TypeError: Cannot read properties of undefined (reading 'options')
>     at P (SelectComponent.tsx:16:63)
>     at Xh (react-dom.production.min.js:167:137)
>     at Wk (react-dom.production.min.js:290:337)
>     at Vk (react-dom.production.min.js:280:389)
>     at Uk (react-dom.production.min.js:280:320)
>     at Jk (react-dom.production.min.js:280:180)
>     at Fk (react-dom.production.min.js:273:245)
>     at jg (react-dom.production.min.js:127:105)
>     at mh (react-dom.production.min.js:266:390)
>     at ri (react-dom.production.min.js:181:441)
> ```

**Comment by jonkoops** [comment]
Gotcha. @edewit could you create a PR with the missing parts of the backport?

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
