### ISSUE TITLE
Please put back online the documentations of Keycloak versions < 21

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#23210]
### Description

I don't understand this decision to remove the documentation of all the versions below 21.
Not supporting previous versions should not mean removing their documentation.
At least it would have been nice to warn users some months in advance through the blog.
We have in our own documentation (used by clients who are using Keycloak in production as part of our project) many links to the Keycloak documentation. Now all these links are dead :(

**Comment by DAHAG-ArisNourbakhsh** [comment]
keycloak/keycloak.github.io#22
(the PR that removed them)

**Comment by mach-nf** [comment]
I strongly support this request. It's one thing to quietly remove download links as we still can access github releases, but doing so with documentation and even release notes is simply a no-go for an open source project. Please put it back.

Please be aware that RH SSO 7.6 is based on Keycloak 18 and 7.5 is based on 15 - there are users and environments out there which need to support both variants in equivalent versions.

**Comment by fostermi** [comment]
I agree. Please put this back, ASAP.

**Comment by omasseau** [comment]
Another reason why the old documentation should be put back online :

If you use an H2 database in dev and your Keycloak versuib is <20 and you want to upgrade to version 22, here is what the latest docs says : 

> Upgrade of H2 database files
> 
> H2 database base files created with H2 version 1.x should not be used with version 2.x.
> 
> Purge existing H2 database files to start with an empty database, export and import the realms using Keycloak’s export and import functionality

Without the availability of the old documentation, how I am supposed to know how to export my realms from the old version to be able to import them in the new version ? (The export command has changed in the meantime).

**Comment by mabartos** [comment]
@stianst What's your input on this? Would it be possible to make the old documentation available in some extended archive?

**Comment by stianst** [comment]
The main reason behind removing the documentation published on the website for older and unsupported versions is simply down to GitHub pages being very slow when there are many versions. The docs for each version is over 250MB, and with too many versions this becomes GBs, which causes a long time to make changes to the website, and work with the repository.

We have purged older versions from the website for years, and this is not something new.

For more recent versions the documentation is available in a ZIP format from GitHub releases, we could potentially consider uploading the same for some older versions, but unless someone has a suggestion on how we can work around the issue with slow publishing times on GitHub Pages we won't publish documentation for older versions to the website directly.

**Comment by omasseau** [comment]
> The main reason behind removing the documentation published on the website for older and unsupported versions is simply down to GitHub pages being very slow when there are many versions. The docs for each version is over 250MB, and with too many versions this becomes GBs, which causes a long time to make changes to the website, and work with the repository.
> 
> We have purged older versions from the website for years, and this is not something new.
> 
> For more recent versions the documentation is available in a ZIP format from GitHub releases, we could potentially consider uploading the same for some older versions, but unless someone has a suggestion on how we can work around the issue with slow publishing times on GitHub Pages we won't publish documentation for older versions to the website directly.
> 
> In addition I strongly urge people to not run old and unsupported releases of Keycloak in production. These older versions are completely insecure to run, and you are effectively opening yourself up to attacks by doing so.

Having a zip somewhere to download would indeed be fine and enough I think  ;)

**Comment by cstohr1** [comment]
> slow publishing times on GitHub Pages

@stianst would it be possible to publish documentation for older versions in a separate repo, which then naturally doesnt get updated as often and slow publishing times are not an issue?

**Comment by stianst** [comment]
@cstohr1 not really, as that would be quite a bit of effort + there's also a size limit with GH pages, which is actually the first reason we started purging older docs, so there would be a finite number of versions we could keep that way as well

**Comment by stianst** [comment]
Closing this as we simply don't have capacity for it. For those that really need documentation for older releases:

* RH-SSO - documentation is available through https://access.redhat.com/products/red-hat-single-sign-on/
* Keycloak >= 21 - documentation is available through https://github.com/keycloak/keycloak/releases
* Keycloak <= 20 - documentation can be built from https://github.com/keycloak/keycloak-documentation/tags

**Comment by manologg** [comment]
This was also an inconvenient for me and did this: https://manologg.github.io/keycloak-documentation-18.0.2/

**Comment by omasseau** [comment]
> Closing this as we simply don't have capacity for it. For those that really need documentation for older releases:
> 
>     * RH-SSO - documentation is available through https://access.redhat.com/products/red-hat-single-sign-on/
> 
>     * Keycloak >= 21 - documentation is available through https://github.com/keycloak/keycloak/releases
> 
>     * Keycloak <= 20 - documentation can be built from https://github.com/keycloak/keycloak-documentation/tags

Unfortunately the documentation available through https://github.com/keycloak/keycloak/releases zip is incomplete.
It is missing these essential parts : 'Getting Started', 'Server Installation and Configuration' and 'Server Container Image'.

For example the configuration necessary to work behind a reverse proxy is only available in 'Server Installation and Configuration' part.
Refering to the online documentation for a (recent) previous release (ex: https://www.keycloak.org/archive/documentation-22.0.html) is not possible as the online links for this part of the documentation always points to the the latest release (which may not be revelant anymore for previous release).

See this issue : https://github.com/keycloak/keycloak/issues/30177
