### ISSUE TITLE
kcadm.bat, kcreg.bat do not respect environment variables JAVA, JAVA_HOME to select JVM

### ISSUE THREAD

**Issue by crystalgreen** [keycloak/keycloak#23214]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

This is the same issue as #11336 but this time for the .bat files.

### Version

22.0.3

### Expected behavior

See the related issue #11336, now for Windows.

Keycloak bin/kc.bat supports environment variables JAVA and JAVA_HOME.
So should the other scripts.

### Actual behavior

See the related issue #11336, now for Windows.

### How to Reproduce?

See the related issue #11336, now for Windows.

**Comment by vmuzikar** [comment]
@Pepo48 Can you please look into this when you get a chance?

**Comment by Pepo48** [comment]
I can confirm this issue. I'll try to provide a fix.
