### ISSUE TITLE
Required OTP setting again when doing password reset

### ISSUE THREAD

**Issue by ilu123** [keycloak/keycloak#23227]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/api

### Describe the bug

We use LDAP as the federation provider and enabled the OTP feature for users login.
When I test, I sign in with test account and setup the OTP settings done. Then I logout out to test the "Forgot password?", it sends me the reset password email.
Problem is when I click the email link url, it shows me that to setup the OTP setting again....
It not happened in version 21.1.2, but 22.0.2.
I think that's not a normal process and should be a bug.

### Version

22.0.2

### Expected behavior

Do not provide the OTP settings again after done once when reseting password.

### Actual behavior

It shows the OTP settings again, and have to do 2 times OTP settings. Resulting in 2 OTP devices registered.

### How to Reproduce?

Using 22.0.2

**Comment by mposolda** [comment]
Adding to Backlog as it looks like a mis-configuration rather than Keycloak issue.

@

**Comment by graziang** [comment]
Hi @ilu123
In addition, from version 22 you can configure the "Reset OTP" execution in the "reset credentials" flow with the following options:
- If 'Remove none' is chosen, the user will keep all existing OTP configurations (legacy behavior).
- If 'Remove one' is chosen, the user will be prompted to choose one OTP configuration which will then be removed.
- If 'Remove all' is chosen, all existing OTP configurations of the user will be removed.

The user will always be prompted to configure a new OTP no matter which option is selected, if you want to keep the previously configured OTP without requesting a new OTP configuration, you must disable the "Reset OTP" execution.
