### ISSUE TITLE
Client session timeout has no effect on account console v1 but works in account console v2

### ISSUE THREAD

**Issue by tu-pm** [keycloak/keycloak#23228]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Our Keycloak setup has a single realm that contains multiple clients, with the realm configuration as below:

```
Access Token Lifespan: 3 minutes
SSO Session Idle: 3 hours
SSO Session Max: 10 hours
```

This configuration works with the majority of clients using access tokens that are refreshed every 3 minutes to keep the session length up to 10 hours.

But in the account management page, the session length must be much shorter, as short as the access token lifespan, to reduce the risk of malicious actors trying to update user's important information (such as password, email, etc.).

We achieved that goal by setting client-specific configurations for the account console like this:

```
Access Token Lifespan: 3 minutes
Client Session Idle: 3 minutes
Client Session Max: 3 minutes
```

But this configuration only works for the account console v2 (which uses the `account-console` client) and does not work for the account console v1 (which uses the `account` client): If we set the account theme to value `keycloak`, the account management page is not logged out after 3 minutes, users can still navigate through tabs and update password successfully. But when the theme is set to `keycloak.v2`, users are logged out after 3 minutes as expected.

### Version

19

### Expected behavior

Users are logged out of account management console after the configured client session length for both the v1 and v2 UI.

### Actual behavior

Users are only logged out of account management console v2 and are not logged out of the console v1 after the configured client session length.

### How to Reproduce?

- Step 1: Create a new realm
- Step 2: Configure realm tokens settings like this:

```
Access Token Lifespan: 3 minutes
SSO Session Idle: 3 hours
SSO Session Max: 10 hours
```

- Step 3: Configure the client tokens settings for both `account` and `account-console` client like this:

```
Access Token Lifespan: 3 minutes
Client Session Idle: 3 minutes
Client Session Max: 3 minutes
```

- Step 4: Configure realm's account theme to `keycloak`, log in as normal user and wait > 3 minutes
- Step 5: Try step 4 with realm's account theme is `keycloak.v2`

**Comment by ssilvert** [comment]
@tu-pm Account console V1 no longer exists in the latest version, so we won't be fixing this in older versions.
