### ISSUE TITLE
Realm client update via PUT returns invalid registration_client_uri with duplicated client ID in address

### ISSUE THREAD

**Issue by Roma110** [keycloak/keycloak#23229]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

In keycloak (21.0.1 ) we are doing Realm client update via PUT and it returns invalid registration_client_uri with duplicated client ID in address
Create needed resources to have OIDC discovery endpoint, initial access token, realm
Use OIDC discovery endpoint to get the registration endpoint in order to create a client

### Version

21.0.1

### Expected behavior

Using the modified address by removing extra "/<id>" works - GET returns 200 and shows the client details which have a valid value of registration_client_uri.

Valid registration_client_uri returned from PUT request - no duplicated client ID in the address.

### Actual behavior

Response from PUT request returns invalid registration_client_uri, with duplicated client ID.

GET request using that registration_client_uri and registration_access_token from PUT response fails with 404.

Log with GET response from the test:

![image](https://github.com/keycloak/keycloak/assets/28138074/9e9ccb91-f513-41e8-a8b4-58a8c172382f)

### How to Reproduce?

  We are doing Realm client update via PUT and it returns invalid registration_client_uri with duplicated client ID in address
    Create needed resources to have OIDC discovery endpoint, initial access token, realm
	Use OIDC discovery endpoint to get the registration endpoint in order to create a client
	Send POST request to create a client
	![image1](https://github.com/keycloak/keycloak/assets/28138074/8a603f76-f98f-494e-aa2b-e0ce14970438)
	
	Response to this POST request has registration_client_uri and registration_access_token (among other parameters)
   
	Send GET request to client, using registration client URI and registration access token received from POST response.
        Log with GET request from the test:
	
![image2](https://github.com/keycloak/keycloak/assets/28138074/a95cca3d-7832-4f6f-8ac0-e69d4343ea48)

	
	Send PUT request to update something in this client, using registration client URI and registration access token received from 
         POST response and using request body from POST request with something changed.
        
![image3](https://github.com/keycloak/keycloak/assets/28138074/069aa7d4-faf6-440c-adfe-22c370b6dfe6)

	Send GET request to client, using registration client URI and registration access token received from PUT response.
       
![image4](https://github.com/keycloak/keycloak/assets/28138074/d00fdd6a-bed5-4086-8db5-1b3fa9f2d4ea)
      As shown above Log with PUT response from the test:
	
	**Actual behavior:**
        Response from PUT request returns invalid registration_client_uri, with duplicated client ID.

	GET request using that registration_client_uri and registration_access_token from PUT response fails with 404.
	
	Log with GET response from the test:
	
![image4](https://github.com/keycloak/keycloak/assets/28138074/2794bfee-4ac5-44f1-bdeb-61e4cdaaf53c)

	Using the modified address by removing extra "/<id>" works - GET returns 200 and shows the client details which have a valid value of registration_client_uri.
	
	**Expected behavior:**
	Valid registration_client_uri returned from PUT request - no duplicated client ID in the address

**Comment by pedroigor** [comment]
@mposolda Do we want to backport this one for both 22 and 23?
