### ISSUE TITLE
LDAP bindCredential is stored as clear text in database in COMPONENT_CONFIG table

### ISSUE THREAD

**Issue by Ashwin976** [keycloak/keycloak#23242]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

LDAP bindCredential is stored as clear text in database in COMPONENT_CONFIG table

### Version

20.0.5

### Expected behavior

bindCredential  should not be stored as clear text. It should be encrypted. It should be stored like how password is stored 

### Actual behavior

bindCredential is stored as clear text

### How to Reproduce?

Add userfederation--> Given LDAP details-> bindCredential
All these details are stored in COMPONENT_CONFIG table and bindCredential is stored as clear text

**Comment by ahus1** [comment]
Thank you for raising this issue. The credentials for LDAP are different than user password. User password are hashed one-way. There is no way to decrypt them afterwards. 

Bind-credentials need to be passed in their original form to LDAP. Therefore hashing is not possible. If you want to store the credentials outside of the database, use the Keycloak's vault functionality. See https://www.keycloak.org/server/vault for more information.
