### ISSUE TITLE
Schema generation and data migration is not happening at attached  external postgres database

### ISSUE THREAD

**Issue by adarsh-sw** [keycloak/keycloak#23245]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

I'm using keycloak operator at our AKS cluster which by default installed latest version on keyclock 22.0.3.  The database attached is Azure Database for PostgreSQL flexible server. The issue I am getting is, I'm not able to login with initial admin password provided in secret when the database is connected. Though I'm able to  login when Db is not connected. 
I checked the database for figuring out but as I can see it was empty even after successful connection.

### Version

22.0.3

### Expected behavior

Schema creation, tables and other data migration in external Db so that I can able to login easily and store my keycloak data in Db.

### Actual behavior

No data migration in external database.

### How to Reproduce?

Install the keycloak operator and in custom keycloak resource  attach external Db.. Then on successful start, login with the initial admin password provided in secret.

**Comment by ahus1** [comment]
The initial admin user is only used when an empty database is being initialized with the first admin user. Once that user has been created, the information provided in the secret is no longer used. Admin will need to use the password as it was used to setup the user in the first place or the password to that it was change to afterwards.
