### ISSUE TITLE
Several help text messages missing in saml identity provider

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak#23255]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

There are several help texts missed in the SAML identity provider. It seems that everything that use the `HelpItem` now needs a `Help` suffix. It was detected in this PR: https://github.com/keycloak/keycloak/pull/23203

For example:

![Screenshot from 2023-09-14 15-45-16](https://github.com/keycloak/keycloak/assets/26901232/6f289c8e-ac22-4454-b05a-56d87ca43bf6)

Don't know if this happens in more places.

The problem is only in current main. The 22.0.3 is OK and all the text messages are displayed OK.

### Version

999.0.0-SNAPSHOT

### Expected behavior

The help text should be OK. For example in the property shown in the image is: `Specifies the URI reference corresponding to a name identifier format.`

### Actual behavior

Just shows the same name, no the help.

### How to Reproduce?

Just create a saml identity provider. Check the help texts are not displayed.

**Comment by ssilvert** [comment]
I have reproduced this in the latest nightly.
