### ISSUE TITLE
SAML Encryption Key Export Downloads Signing Key

### ISSUE THREAD

**Issue by monacolulu** [keycloak/keycloak#23251]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When exporting a newly generated SAML encryption key, the /certificates/saml.signing/download api is called instead of /certificates/saml.encryption/download

### Version

21.0.1

### Expected behavior

The encryption certificate should be downloaded

### Actual behavior

the signing certificate is downloaded

### How to Reproduce?

create SAML client
generate encryption and signing keys
exporting either one always downloads the signing-key

### Anything else?

as a workaround the developer tools in chrome can be used to resend the POST Request to the correct endpoint.

**Comment by ssilvert** [comment]
I have reproduced this behavior on the latest nightly.
