### ISSUE TITLE
Invalid redirect after logging in using Twitter (X)

### ISSUE THREAD

**Issue by tondrusk** [keycloak/keycloak#23252]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

The login flow incorrectly redirects after logging in on the Twitter (X) side and redirects to the very same Twitter (X) login page, however, the user is already logged in to Twitter. If the test is forced to navigate to login page and clicking on the Twitter button again, the test requires just to update the profile fields and it passes.

Looking into the Developer tools > Network in the Chrome browser, the redirect after logging in on the Twitter side results in an error request with the redirect included as a URL parameter, and for unknown reason the request's status code is 200.

The GET request URL looks something like this:
```
https://twitter.com/login/error?redirect_after_login=https%3A%2F%2Fapi.twitter.com%2Foauth%2Fauthenticate%3Foauth_token%3DHbd77AAAAAABpSDkAAABipPMEKc
```

After removing the encoded parts like `%3A` from the `redirect_after_login` parameter, replacing them with the corresponding characters, and entering the URL modified like that to the browser, after executing, it correctly proceeds to the Keycloak application.

### Version

latest

### Expected behavior

Login using Twitter and redirect to Keycloak.

### Actual behavior

The redirect after logging in on the Twitter (X) side does not redirect to Keycloak.

### How to Reproduce?

1. Set up the Twitter (X) application according to the documentation 
    https://www.keycloak.org/docs/latest/server_admin/index.html#_twitter
3. Prepare `social.properties` file containing the required variables (e.g., Client ID, Client Secret, ...)
4. Run the testsuite with following command with your custom `social.properties` file
```
$ mvn -f testsuite/integration-arquillian/pom.xml clean install \
      -Dtest=SocialLoginTest#twitterLogin \
      -Dsocial.config=path\to\social.properties \
      -Dbrowser=chrome
```

**Comment by tondrusk** [comment]
The relevant workaround which is working but not truly fixing the issue can be found here: [#23122 | Fixes issue in login flow of SocialLoginTest#twitterLogin](https://github.com/keycloak/keycloak/pull/23122)

**Comment by miquelsi** [comment]
Closing this as it should work even with an eventual fix on Twitter side.
