### ISSUE TITLE
sync all users does not take effect and the database cannot be synchronized with ldap

### ISSUE THREAD

**Issue by MorganReid** [keycloak/keycloak#23275]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

I have deployed a 21.1.1 version of keycloak and integrated it with ldap. The following is the main configuration:
![image](https://github.com/keycloak/keycloak/assets/52235796/9be58256-97a4-41d4-ba0b-e5518b49c265)
![image](https://github.com/keycloak/keycloak/assets/52235796/f3599d3d-af35-406c-af4c-7335fb0156cd)

Background: I logged into keycloak using account `A `in ldap, the authentication was successful, and a record of A was generated in the `USER_ENTITY` table of the database.
Now there are 2 questions:
1: When I add a new account `B`.`User federation` in keycloak and click `sync all users` or `sync changed users`, the newly added account `B` record in ldap is not synchronized. There is no account `B` information in the database and user list, but the interface and logs are no error is reported. How can I synchronize the account B information newly added to ldap?
![image](https://github.com/keycloak/keycloak/assets/52235796/b082a946-6342-48c1-970f-54799c8bf1e2)
![image](https://github.com/keycloak/keycloak/assets/52235796/4c6c6cd4-bebf-432e-9586-208759a8f97a)

2: User `A`, who already exists in ldap, has changed  mail from `a.com `to `a1.com.` When clicks `sync all users` or `sync changed users`, the user list, user details and database display all the old value `a.com`. 
Check the related issue(https://github.com/keycloak/keycloak/issues/10412) and set the email attribute to `Always Read Value From LDAP.` At this time, the user list and user details email displayed on the interface are the latest` a1.com`, but the `USER_ENTITY `table of the database is still the old value `a.com`.
I tried deleting account `A ` from keycloak user list ,and then logging in again. At this time, the user list, user details and database are all shown to be the latest `a1.com`, but all the previously bound `OTP `and other information are gone, which is equivalent to re-creating a new account with keycloak. How can the user list, user details and database be synchronized to the latest ldap attributes without deleting the account?

### Version

21.1.1  22.0.3

### Expected behavior

1: synchronize the new account information  to keycloak
2: user list, user details and database be synchronized to the latest ldap attributes without deleting the account

### Actual behavior

1:There is no new account information in the database and user list, but the interface and logs are no error is reported.
2:Unable to sync to latest values unless account is deleted from keyclaok

### How to Reproduce?

- 21.1.1 version deployment

- ldap is configured as described in the picture

- Add new users to ldap and change the mail information of old users

**Comment by martin-kanis** [comment]
@MorganReid What LDAP do you use? The problems you are describing are covered in the testsuite and should be working.
