### ISSUE TITLE
Test for ldap:// + StartTLS seems not working well

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#23289]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

The PR for #9313 issue introduced an error which caused TLS connection to be established prematurely which led to closing the connection rather than continuing with TLS connection negotiation, reported in #21935.

This bug should have been caught by `LDAPUserLoginTest.loginLDAPUserAuthenticationNoneEncryptionStartTLS` but wasn't. Investigate why.

Also [it seems](https://github.com/keycloak/keycloak/actions/runs/6174628629) that legacy store tests are not run upon change in `federation/` module which would lead to missing this out in the PR checks.

### Version

22

### Expected behavior

Test failure

### Actual behavior

Test passes even with [the missing fix](https://github.com/keycloak/keycloak/pull/23215).

### How to Reproduce?

Remove the [fix](https://github.com/keycloak/keycloak/pull/23215) and run the test.

**Comment by pedroigor** [comment]
@hmlnarik Does it still make sense?

**Comment by hmlnarik** [comment]
I believe it does since it missing already led to a regression and there is a test that should have caught it. I leave the final decision to the core team though.
