### ISSUE TITLE
Keycloak server fails to start with the minimum configuration following the documentation

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#23292]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

```
Changes detected in configuration. Updating the server image.
Updating the configuration and installing your custom providers, if any. Please wait.
2023-09-15 13:40:25,767 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 13719ms
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config

Next time you run the server, just run:

	kc.sh start --optimized 

ERROR: Unexpected error when starting the server in (production) mode
ERROR: Failed to start quarkus
ERROR: Strict hostname resolution configured but no hostname setting provided
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

```

Keycloak:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: test-keycloak
  namespace: keycloak
spec:
  instances: 1
```

### Version

22.0.3

### Expected behavior

To actually start the Keycloak server

### Actual behavior

Failed to start

### How to Reproduce?

Deploy keycloak operator based on https://www.keycloak.org/operator/installation
```
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/22.0.3/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/22.0.3/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml

kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/22.0.3/kubernetes/kubernetes.yml

```

Create the Keycloak resouce.

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: test-keycloak
  namespace: keycloak
spec:
  instances: 1
```

**Comment by vmuzikar** [comment]
@droslean Please refer to the [docs](https://www.keycloak.org/operator/basic-deployment). Production grade Keycloak requires specifying hostname, DB and TLS Secret.

**Comment by droslean** [comment]
> @droslean Please refer to the [docs](https://www.keycloak.org/operator/basic-deployment). Production grade Keycloak requires specifying hostname, DB and TLS Secret.

Thanks @vmuzikar but this is not a solution. If those values are required, then they need to be required in the CRD itself.

**Comment by vmuzikar** [comment]
But we plan to improve the UX around it in #21816.
