### ISSUE TITLE
admin-fine-grained-authz + client authorization settings requires more realm-management roles

### ISSUE THREAD

**Issue by cnwaldron** [keycloak/keycloak#23294]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When using the preview feature admin-fine-grained-authz to allow certain users to manage their clients, some clients are using the Authorization capabilities. In Keycloak <=v19 using the old Admin UI Console, the only realm-management client roles that were needed to these users were: `manage-authorization`, `query-clients`, `query-users`, `query-groups`. In the new Admin UI Console, the role `view-clients` is required to do anything in the Authorization settings for the client. 

This is a problem as `view-clients` role allows users to view other clients and the client secrets of all applications.

### Version

v22.0.1

### Expected behavior

When using admin-fine-grained-authz settings users with manage permissions to a client should be able to configure and create authorization policies for their client without requiring access to ALL clients in the realm. 

### Actual behavior

To manage/view Authorization settings for a client, the user must have `view-clients` realm management client role.

### How to Reproduce?

1)  Follow instructions at [Fine Grain Admin Permissions](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions) to configure a user to manage one specific client.
2) Add realm-management client role of `manage-authorization` to the user as well.
3) Turn on Authorization for the client.
4) Login as user to the security-admin-console for the realm.
5) View the configured managed client and select the Authorization tab.
6) Select any sub-tab of Authorization - Settings, Resources, Scopes, Policies, Permissions, Evaluate, Export
You'll be met with an error message: `Forbidden, permission needed: view-clients`

### Anything else?

![keycloak-authz-resources-tab](https://github.com/keycloak/keycloak/assets/72021941/023673e3-9fd1-4c61-bc9b-20c68a295cbb)

**Comment by ssilvert** [comment]
@cnwaldron This is working fine for me on the latest code.  Did you try it on the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by cnwaldron** [comment]
@ssilvert I'm still seeing this issue on the nightly build

**Comment by ssilvert** [comment]
@cnwaldron I came back to this and I see the problem now.  Before I wasn't looking beyond the `Settings` subtab.

Since you need `manage-authorization` access to see the parent tab, `Authorization`, it does make sense that you should have full permission to all the subtabs.  So my plan is to make the subtabs available to `anyone`.  

The only exception is the `Evaluate` subtab.  I believe that one still needs `view-users` access to actually do the evaluation.  So I'm leaving that one as limited to those with `view-users` access.

Note that a user without `manage-authorization` will be able to see those subtabs if he types in the URL directly.  But in that case, he would not be able to see any data that he doesn't otherwise have access to.

Does this sound like it will fix your problem?

**Comment by cnwaldron** [comment]
@ssilvert Yes, that sounds like it will work. Thanks!

**Comment by ssilvert** [comment]
Actually, forget what I said about using the `anyone` role.  That doesn't make sense for this.

**Comment by jonkoops** [comment]
@ssilvert could you create a PR to backport this issue?

**Comment by jonkoops** [comment]
I've gone ahead and backported this issue, the fix be in the release for 22.0.5.

**Comment by cnwaldron** [comment]
Just fyi. I tested the nightly build and how I can access the Authorization tabs ok but if I attempt to create a new client policy I'm met with the same "Forbidden, permission needed: view-clients" message. I see this also after clickling: Create Resource or Create authorization scope buttons on the other tabs.

**Comment by jonkoops** [comment]
Could you report this as a separate issue for that @cnwaldron?

**Comment by cnwaldron** [comment]
@jonkoops -- Done.
