### ISSUE TITLE
NPE in AuthenticationManager backchannelLogout

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#23306]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

In a customer project we observed UncaughtServerErrors which where caused by NPEs being thrown in [AuthenticationManager#backchannelLogout](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L291). This is caused by accessing the user variable obtained from `userSession.getUser()` without a proper null check.

### Version

22.0.1

### Expected behavior

Should logout `null` for the username instead of throwing a NPE.

### Actual behavior

BackchannelLogout sometimes yields an UncaughtServerError based on an NPE in AuthenticationManager#backchannelLogout.

### How to Reproduce?

Hard to reproduce, as we need to create the sitation where the userSession is still present but the user object is gone.

**Comment by ahus1** [comment]
Thank you for fixing this. If you'd create a backport for KC22, I'd be happy to merge that PR as well.
