### ISSUE TITLE
Keycloak 22.0.3: Create user: select groups to join filter does nothing

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#23341]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Filter 'search for groups' doesn't change the list of visible groups.

### Version

22.0.3

### Expected behavior

After entering something into the search field in the 'Create user -> Select groups to join', and pressing Enter or the button to the right of the filter, the list of groups should be shrinked. 
![изображение](https://github.com/keycloak/keycloak/assets/1285898/78341351-d271-4fd8-af4f-c0be52678f5e)

### Actual behavior

The list of groups remains unchanged.

### How to Reproduce?

Let's have some User groups.
Users -> Create user.
Press Join groups, input some text in the 'Search for groups' input. Press Enter.

### Anything else?

NOTE: the popup itself is blinking and becomes wider, it can be a separate design issue.

**Comment by dazfitzg-1** [comment]
Possibly related to this is that subgroups are not shown in the list and you can't search for them either.
I am trying to setup a Parent Group for a Department and Child Groups for Geographical Location. I can see the Parent Groups but the child groups are not showing and there is no way to expand or search for them.

**Comment by lrozenblyum** [comment]
@dazfitzg-1 maybe, yet we have a flat group structure - no sub-groups, just top level ones.

**Comment by ssilvert** [comment]
I have reproduced this issue on main.
