### ISSUE TITLE
Custom JPA User Federation shows empty User List

### ISSUE THREAD

**Issue by BenjiBoy13** [keycloak/keycloak#23368]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

When implementing a custom user federation storage with JPA taking the [QuickStart](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/user-storage-jpa ) as reference and enabling the federation, no users appear in the Users tab. Yet everything else seems to be working, even the search box.

Going to the Users tab shows:
![image](https://github.com/keycloak/keycloak/assets/35673295/257e9a8f-fb5b-4644-8f33-2908d3bc987d)

Using the search box shows:
![image](https://github.com/keycloak/keycloak/assets/35673295/08ec2083-c396-4ac8-ae8b-0577a217d657)

### Version

22.0.1

### Expected behavior

When going to the Users Tab I should be able to see all the users from my custom DB

### Actual behavior

The user tab shows an empty list, I have to manually use the search box to interact with my DB Users thought Keycloak.

### How to Reproduce?

1. Create a new java (17 LTS) project with gradle (8.1.1) and add the following dependencies to the build.gradle file
```groovy
repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.keycloak', name: 'keycloak-core', version: '22.0.1'
    implementation group: 'org.keycloak', name: 'keycloak-model-jpa', version: '22.0.1'
    implementation group: 'org.jboss.logging', name: 'jboss-logging', version: '3.5.3.Final'

    compileOnly group: 'org.keycloak', name: 'keycloak-server-spi', version: '22.0.1'
}
```
 
2. Create a JPA entity
```java
@Entity
@Table(name = "survivor")
public class SurvivorEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "survivor_id")
    private Integer survivorId;

    @Column(name = "survivor_number")
    private Long survivorNumber;

    @Column(name = "gender", columnDefinition = "ENUM('M', 'F')")
    private String gender;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    // Additional columns ...

    // Getters and setters ....
}
```

3. Create and configure your persistence.xml file under resources/META-INF/
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<persistence
        xmlns="https://jakarta.ee/xml/ns/persistence"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
        version="3.0"
>
    <persistence-unit name="survivors" transaction-type="JTA">
        <class>{YOUR_USER_ENTITY_CLASS}</class>
        <properties>

            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQLDialect" />
            <property name="hibernate.show_sql" value="true" />
            <property name="hibernate.hbm2ddl.auto" value="validate" />

            <property name="hibernate.connection.datasource" value="{DATASOURCE_NAME}" />
            <property name="hibernate.connection.url" value="{YOUR_CONNECTION_URL}" />
            <property name="hibernate.connection.password" value="YOUR_DB_PWD"/>
            <property name="hibernate.connection.username" value="YOUR_DB_USR" />
        </properties>
    </persistence-unit>
</persistence>
```

4. Create a custom user adapter by extending AbstractUserAdapterFederatedStorage
```java
public class SurvivorAdapter extends AbstractUserAdapterFederatedStorage {

    private final SurvivorEntity survivorEntity;

    private String keycloakId;

    public SurvivorAdapter(KeycloakSession session, RealmModel realm, ComponentModel storageProviderModel, SurvivorEntity survivorEntity) {
        super(session, realm, storageProviderModel);
        this.survivorEntity = survivorEntity;
        keycloakId = StorageId.keycloakId(storageProviderModel, survivorEntity.getSurvivorId().toString());
    }

    // Overriding methods such as getUserName; setUserName, etc.
}
```

5. Create a custom provider implementing UserStorageProvider, UserLookupProvider and UserQueryProvider
```java
public class SurvivorUserStorageProvider implements UserLookupProvider, UserStorageProvider, UserQueryProvider {

    private final KeycloakSession keycloakSession;

    private final ComponentModel componentModel;

    private final EntityManager entityManager;

    public SurvivorUserStorageProvider(KeycloakSession keycloakSession, ComponentModel componentModel) {
        this.keycloakSession = keycloakSession;
        this.componentModel = componentModel;
        this.entityManager = keycloakSession.getProvider(JpaConnectionProvider.class, "survivors").getEntityManager();
    }

    @Override
    public UserModel getUserById(RealmModel realm, String id) {
        String persistenceId = StorageId.externalId(id);
        SurvivorEntity survivorEntity = this.entityManager.find(SurvivorEntity.class, persistenceId);
        if (Objects.isNull(survivorEntity)) return null;

        return new SurvivorAdapter(this.keycloakSession, realm, this.componentModel, survivorEntity);
    }

    @Override
    public UserModel getUserByUsername(RealmModel realm, String username) {
        Long survivorNumber = Long.valueOf(username);

        TypedQuery<SurvivorEntity> query = entityManager.createQuery(
                "select s from SurvivorEntity s where s.survivorNumber = :survivorNumber", SurvivorEntity.class
        );

        query.setParameter("survivorNumber", survivorNumber);

        List<SurvivorEntity> survivorEntities = query.getResultList();

        if (survivorEntities.isEmpty()) return null;

        return new SurvivorAdapter(this.keycloakSession, realm, this.componentModel, survivorEntities.get(0));
    }

    @Override
    public UserModel getUserByEmail(RealmModel realm, String email) {
        TypedQuery<SurvivorEntity> query = entityManager.createQuery(
                "select s from SurvivorEntity s where s.eMail = :eMail", SurvivorEntity.class
        );

        query.setParameter("eMail", email);

        List<SurvivorEntity> survivorEntities = query.getResultList();

        if (survivorEntities.isEmpty()) return null;

        return new SurvivorAdapter(this.keycloakSession, realm, this.componentModel, survivorEntities.get(0));
    }
    
    @Override
    public Stream<UserModel> searchForUserStream(RealmModel realm, Map<String, String> params) {
        TypedQuery<SurvivorEntity> query = entityManager.createQuery(
                "select s from SurvivorEntity s", SurvivorEntity.class
        );

        List<SurvivorEntity> survivorEntities = query.getResultList();

        if (survivorEntities.isEmpty()) return Stream.empty();

        List<UserModel> userModelList = survivorEntities.stream().map(s -> new SurvivorAdapter(this.keycloakSession, realm, this.componentModel, s)).collect(Collectors.toList());

        // Logging userModelList

        return userModelList.stream();
    }

    @Override
    public Stream<UserModel> searchForUserStream(RealmModel realm, Map<String, String> params, Integer firstResult, Integer maxResults) {
        String searchKeyword = params.get(UserModel.SEARCH);

        TypedQuery<SurvivorEntity> query;
        if (Objects.nonNull(searchKeyword))
            query = entityManager.createQuery(
                    "select s from SurvivorEntity s where s.firstName like :q or s.lastName like :q",
                    SurvivorEntity.class
            );
        else query = entityManager.createQuery("select s from SurvivorEntity s", SurvivorEntity.class);

        query.setParameter("q", '%' + searchKeyword + '%');

        if (Objects.nonNull(firstResult)) query.setFirstResult(firstResult);
        if (Objects.nonNull(maxResults)) query.setMaxResults(maxResults);

        List<SurvivorEntity> survivorEntities = query.getResultList();

        if (survivorEntities.isEmpty()) return Stream.empty();

        List<UserModel> userModelList = survivorEntities.stream().map(s -> new SurvivorAdapter(this.keycloakSession, realm, this.componentModel, s)).collect(Collectors.toList());

        // Logging userModelList

        return userModelList.stream();
    }
}
```

6. Add the file org.keycloak.storage.UserStorageProviderFactory under resources/META-INF/services
7. Build the project with gradle and put the generated jar file into the providers folder in your Keycloak instance
8. run the kc script with build and then with start-dev
9. Add the custom federation to any of your realms
10. Consult the User page

### Anything else?

I think that the issue might be because I lack the implementation of some interface or method that I am not aware off, but after reading the documentation and reviewing the QuickStart repo, I am pretty sure I am implementing everything that I need.

**Comment by sguilhen** [comment]
In the new console, the users page always displays no users by default. You have to use the search box to load users according to the search criteria.

**Comment by ahus1** [comment]
To search for all users, use `*` in the search.

**Comment by BenjiBoy13** [comment]
@ahus1 Yes, I can see all users even when searching with "%" due to the way my searchForUserStream method was implemented; I did not know that was the way it worked, thank you all.

**Comment by ahus1** [comment]
Thank you for letting me know that this works now. Please note that future versions of Keycloak will improve to only allow for `*` as a wildcard, and will do so across all providers (JPA, LDAP, etc.)

I think showing all users initially has been disabled as it can be quite a performance drain, especially for custom user providers and LDAP. 

Still it is different compared to all other entities, and from a UX perspective this could/should be improved. Especially that `*` shows all entities. Pinging @ssilvert and @jonkoops here.

**Comment by ssilvert** [comment]
> In the new console, the users page always displays no users by default. You have to use the search box to load users according to the search criteria.

Actually, that's the way the old console worked.  You always had to search to see any users at all.  But we did have a "Display all users" button that you could press at your own risk.

We made a change in the new console so that if you haven't configured a federation provider, it will show a paginated list of users by default.

And pagination is the big problem here.  If the UI knew that it could get a nice paginated list of users that wouldn't bring the server to its knees, we could do a lot better.  But right now we have no way of knowing what we are dealing with on the back end.

**Comment by BenjiBoy13** [comment]
I can understand why it is not a good idea to load all users by default; Cause even if you had to override a method on your provider, say, `getAllUserStream `and you pass down an offset and a limit for pagination there is no guarantee that the developer is going to change the query parameters based on those values and nothing is going to stop him/her from returning a massive java stream.

The "Display all users" button does sound like a good approach and it is something that I can certainly be happy with, however I am not able to find this button anywhere on my UI, could I be missing some configuration?

**Comment by ahus1** [comment]
@BenjiBoy13 - @ssilvert is referring to the old admin console which was the predecessor of the current account console and has by now been removed. The new account console doesn't have that button, only the old one did.
