### ISSUE TITLE
Remove Wildfly and EAP OIDC adapters

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23381]
### Description

Those are already deprecated in Keycloak 22 (and before). There is replacement for them by using Elytron OIDC. Hence we can remove them from:
- Keycloak codebase (including testsuite and distribution)
- Documentation
- Web page (downloads etc)
- Will need to add something to release notes and/or migration guide about those being removed

**Comment by douglaspalmer** [comment]
Does this include removing the wildfly-elytron OIDC adapter too?

**Comment by mposolda** [comment]
> @mposolda Does this include removing the wildfly-elytron OIDC adapter too?

@douglaspalmer +1 . Adapter `adapters/oidc/wildfly-elytron` is supposed to be removed as well. WildFly has it's own OIDC adapter in it's own codebase, so we can remove everything on our side.
