### ISSUE TITLE
Allow user to select between `Forwarded` or `X-Forwarded-*` header

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#23431]
### Description

Allow user to explicitly select which header is processed: `Forwarded` or `X-Forwarded-*`. Currently both are processed (in that order).

### Motivation

**Background**

Keycloak 21.0.0 introduced support for [RFC7239](https://datatracker.ietf.org/doc/html/rfc7239) `Forwarded` header with following warning ([link](https://www.keycloak.org/docs/latest/release_notes/index.html#support-for-the-standard-forwarded-header-when-running-behind-a-reverse-proxy)):

> Please, make sure your proxy is also overriding the Forwarded header when making requests to Keycloak nodes.

This warning is repeated in [reverse proxy guide](https://www.keycloak.org/server/reverseproxy)

> Take extra precautions to ensure that the client address is properly set by your reverse proxy via the Forwarded or X-Forwarded-For headers. If this header is incorrectly configured, rogue clients can set this header and trick Keycloak into thinking the client is connected from a different IP address than the actual address. This precaution can be more critical if you do any deny or allow listing of IP addresses.

**Problem**

Most proxies, such as NGINX and Envoy only support `X-Forwarded-*`.

Users who previously deployed Keycloak behind proxy and rely on old behavior, will become vulnerable to header forging by upgrading to Keycloak 21.0.0+ if they miss the importance of the note about reconfiguring their proxy to reset the `Forwarded` header.  As a result, external client can set `Forwarded` with any address, and Keycloak will process that over the real client address in `X-Forwarded-*`.

### Details

**Security hardening proposal** 

Instead of depending only on proxy (re)configuration to secure the deployment,  I would like to propose allowing user to explicitly control following Quarkus properties individually: `quarkus.http.proxy.allow-forwarded` vs `quarkus.http.proxy.allow-x-forwarded` ([link](https://quarkus.io/guides/http-reference#reverse-proxy)).

Today the proxy mode enables both as a combination. As a result, one header is automatically picked over another, which may cause fallback to a header set by untrusted client. More predictable behavior would be to avoid automatic fallback and let user to have control over which header is processed. 

Related issue: https://github.com/quarkusio/quarkus/issues/35751

**Comment by stianst** [comment]
@vmuzikar this one is something we should resolve as it's not ideal we're looking at Forwarded header if it's not been set by the proxy

**Comment by vmuzikar** [comment]
@stianst Yeah, definitely something we want to make configurable. But I see it as an enhancement/security hardening rather than a bug. And rather than randomly adding yet another hostname/proxy config option, I'd like to fix it as part of our broader effort around improving and revisiting our hostname/proxy options. This is something we're already actively investigating. Stay tuned for details soon. :)

Moving milestone to 23. Does it work for you?

**Comment by tsaarni** [comment]
Here is an idea how to solve this in Quarkus https://github.com/quarkusio/quarkus/issues/35751#issuecomment-1764803832

**Comment by vmuzikar** [comment]
This will be resolved as part of https://github.com/keycloak/keycloak/issues/24252. Keeping this open but removing the milestone.

**Comment by torsorensen** [comment]
As a quickfix, we can ask nginx (e.g. powering k8s community ingress) to remove the Forwarded header - then it doesn't matter if it has been tampered with.
But the trade-off is that it requires that we're willing to use a snippet, which is also something that should be avoided
```
  nginx.ingress.kubernetes.io/configuration-snippet: |
   proxy_set_header Forwarded "";
```
