### ISSUE TITLE
Cannot update email address when "Email as username" is enabled

### ISSUE THREAD

**Issue by SilentGert** [keycloak/keycloak#23438]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

Updating a users email address does not work anymore when _Email as username_ is enabled  and _Edit username_ is disabled for the realm. It does not change when I update it via API or Keycloak admin UI. 
It works when I disable the realm setting _Email as username_  or enable _Edit username_.

It used to work in the previous version we use (21.0.1).

Could this issue be related to the recent work on keeping the username in sync when _Email as username_ is enabled?
https://github.com/keycloak/keycloak/issues/20459

### Version

22.0.3

### Expected behavior

The user has the new email address and the username is derived from the email address.

### Actual behavior

The user still has the old email address and username.

### How to Reproduce?

1. Create a realm that has _Email as username_ enabled and _Edit username_ disabled
2. Add a user
3. Change the users email address attribute (either via Keycloak admin UI or API)

**Comment by SilentGert** [comment]
I can see there is a test that covers this exact scenario: [updateUserWithEmailAsUsernameEditUsernameDisabled](https://github.com/keycloak/keycloak/blob/bb8b80e8dde13327663dd350b369b478023eb970/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java#L2364)
Introduced with this [commit](https://github.com/keycloak/keycloak/commit/ea3225a6e1926716734b45d3f5cd9df8e8e66370)

It does not expect the email address to change when _Edit username_ is disabled. So in that sense the "bug" I encounter is not a bug but desired behavior.

Was the behavior here changed on purpose in comparison to earlier versions?

**Comment by pedroigor** [comment]
@SilentGert Yeah, that is the expected behavior. It is actually the same behavior when you have a user profile disabled. Ultimately we want to make both dynamic and legacy user profile behaving the same (e.g.: check KC 18).

This has been confusing for a long time where the `edit username allowed` is also used to set rules at the Admin API. I also agree we can change that because it does not make much sense to allow changing that flag and not being able to change user email, if you are an admin.

**Comment by SilentGert** [comment]
@pedroigor Thanks for looking into this topic. So that means in a future version I can change the email address again via admin API without having _Edit username_ enabled on the realm. 

Is this topic worthy of a patch update or would this rather go into 23.0.0? I'm currently in the middle of the upgrade in our infrastructure and trying to figure out if I have to temporarily enable that flag on all realms or wait for a patch.

**Comment by pedroigor** [comment]
@SilentGert That switch was added by https://issues.redhat.com/browse/KEYCLOAK-1305. However, it did not cover the case where the email is the username, as you can see from the tests. The previous behavior was hidden from us and that is why you noticed it now.

The assumption for the new behavior is that the `edit username allowed` field should also influence how the `email` attribute is set when the `email as username` is enabled.

I can't think of a reason to not support the previous behavior and allow managing the `email` attribute through the Admin API.
