### ISSUE TITLE
Keycloak 22.0.3: editing OIDC client shows Backchannel logout URL as mandatory

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#23437]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

First attempt to save an OIDC client which has empty 'Backchannel logout URL' fails

### Version

22.0.3

### Expected behavior

Just changes should be saved.

### Actual behavior

A not-mandatory field `Backchannel logout URL` blocks saving
![изображение](https://github.com/keycloak/keycloak/assets/1285898/9ca5a9fe-3d25-4356-805e-f43b229827ed)

### How to Reproduce?

Edit an OIDC client with Standard flow enabled (e.g. try add web origins).
Press Save.

### Anything else?

1) It worked in 22.0.2
2) The next 'Save' attempt seems to succeed.

**Comment by ssilvert** [comment]
I tried this and it works fine.  Can you try it with the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by lrozenblyum** [comment]
@ssilvert I confirm that in the nightly build the problem is **not** reproduced, just in 22.0.3.

**Comment by jonkoops** [comment]
This might have been fixed and back-ported already (not released yet), but I can't find an issue for this that was previously reported.

**Comment by lrozenblyum** [comment]
@jonkoops I may re-test this when 22.0.4 is released.

**Comment by jonkoops** [comment]
Just tried to reproduce this on the release branch for 22.0.4 and I could not. I believe this issue has already been fixed and will come along with the next release. If it still doesn't work after that we can re-open this issue.
