### ISSUE TITLE
After the recent switch to resteasy-reactive we are unable to use resteasy-classic or jersey jax-rs clients.

### ISSUE THREAD

**Issue by rh-iatanaso** [keycloak/keycloak#23444]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dependencies

### Describe the bug

We have a number of custom SPI's which are using jax-rs client and more specifically currently Resteasy "classic". 
After the switch to resteasy-reactive we are unable to start Quarkus build due to various initialization issues and collisions.
* We tried to find and use resteasy-reactive but looks like the only one provided is in Quarkus which is and extensions and currently not enabled in Keycloak.
* We tried to switch the Jersey, but we still failed to build Quarkus image because of issues on the classloader. Looks like Jersey is not implementing some things but also we are getting same ServiceLoader issues ` Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
     [exec]     [error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.util.ServiceConfigurationError: jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
     [exec]     at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
     [exec]     at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
     [exec]     at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
     [exec]     at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
     [exec]     at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)`

The options we have left is switch find completely standalone client or maybe keycloak can enable the resteasy-reactive extension. 

### Version

23.0.0

### Expected behavior

We expect to be able to use resteasy "classic" or reactive client in our extensions. 

### Actual behavior

Seem we can't find a way to augment Quarkus once we add our SPI's 

### How to Reproduce?

Currently, we do not have small example, but we can try to provide one if needed.

### Anything else?

We understand it might not be a good idea for Keycloak to enable a particular Quarkus extensions. We are looking for other ideas or suggestions as well.

**Comment by vmuzikar** [comment]
As discussed offline, this will be documented. We should mention it in the [release notes](https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/23_0_0.adoc) as well as in [upgrading guide](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc) with more details.

**Comment by vmuzikar** [comment]
@rh-iatanaso Just wanted to ask if this is something you'll be able to look into before 23.

**Comment by rh-iatanaso** [comment]
We will try to do that.

**Comment by mabartos** [comment]
@rh-iatanaso Certain changes were made in handling REST providers for RESTEasy Reactive in terms of service loading vs indexing at build time[1]. 

What JAX-RS provider did you use with RESTEasy Classic? How did you instantiate it? 

It'd be good if you'd have a chance to use Jandex index inside of your extension in order to discover the inner beans and potentially even the JAX-RS provider. Could you please create an empty `beans.xml` file in the `src/main/resources/META-INF/` of your extension? 

[1] https://quarkus.io/guides/resteasy-reactive-migration#jakarta-rest-providers

**Comment by rh-iatanaso** [comment]
> What JAX-RS provider did you use with RESTEasy Classic? How did you instantiate it?
> 
> It'd be good if you'd have a chance to use Jandex index inside of your extension in order to discover the inner beans and potentially even the JAX-RS provider. Could you please create an empty `beans.xml` file in the `src/main/resources/META-INF/` of your extension?

we moved away from Classic, this PR is mostly to mention that the RESTEasy migration happened, which is more than what there is currently in the doc. We are  excluding the beans.xml because it was breaking the build at some point . We workeds with @pedroigor to try to remedy our issuse without success.
