### ISSUE TITLE
Docs: authorization_services/topics/service-authorization-obtaining-permission.adoc

### ISSUE THREAD

**Issue by remtu-barco** [keycloak/keycloak#23470]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

File: authorization_services/topics/service-authorization-obtaining-permission.adoc

In the "Obtaining permissions" chapter, there is an optional field name "claim_token", according to the document it is "A string representing additional claims that should be considered by the server when evaluating permissions for the resource(s) and scope(s) being requested"

So basically, by using a regex policy, I would have expected to been able to check the string provided in the claim_token matche with the regex. But unfortunately, it seems that regex policy only look at user attribute.

This stackoverflow post is related to the problem we're facing:
https://stackoverflow.com/questions/75855902/pushing-claims-to-regex-based-policy-in-keycloak

### Version

22.0.3

### Expected behavior

How to use a "claim_token" in a regex policy ?

### Actual behavior

regex policy is only using user attribute

### How to Reproduce?

- create a regex policy with he following params:
  name: destination
  target claim: destination
  regex pattern: ^desk.+$

- Send to the request to KC, with the following params:
  "claim_token_format": "urn:ietf:params:oauth:token-type:jwt" 
  "claim_token": '{"destination":["deskA"]}' // encoded in base64

permission using the "destination" policy is always denied (unless we add a "destination" attribute to the user). In any case, the value from "claim_token" is not used to evaluate the regex

### Anything else?

- Is there a setting to do in KC to use the claim_token value in regexp policy ?

- Do we have to create a custom "regex policy" looking at the `Attributes attributes = evaluation.getContext().getAttributes();` (claim_token value) ?

- any other suggestion ?

**Comment by pedroigor** [comment]
@remtu-barco The regex policy doesn't support what you want. It can only operate on attributes from the identity and not from attributes set available from the context.

It should be possible though if we also take contextual attributes when obtaining the claim value. See https://github.com/keycloak/keycloak/tree/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/clientscope.

If you have time to work on it, please send a PR.

**Comment by remituveri** [comment]
Hello @pedroigor ,

- Which aspect of this clientScope do you refer to ?https://github.com/keycloak/keycloak/tree/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/clientscope ?

- Why not creating a "custom regex policy" looking at the Attributes attributes = evaluation.getContext().getAttributes(); (claim_token value) ? This wont modify the existing regex policy and will provide a solution to our need, no ?

BR

**Comment by pedroigor** [comment]
Sorry, @remituveri. I sent you the link to a unrelated policy provider. 

The provider code is https://github.com/keycloak/keycloak/blob/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/regex/RegexPolicyProvider.java#L73. If you look at this line you'll see we are only resolving attributes from the identity.

I'm not sure if we need a custom policy only for that. We can just improve that one. 

Wdyt?

**Comment by jlsjonas** [comment]
Hi @pedroigor, we also believe that improving the current provider makes most sense.

We'd like to improve the existing policy by adding a checkbox to the policy allowing the user to toggle between identity & context attributes.
Is this in line with what you had in mind, or do you have an alternative proposal?

Thanks!

**Comment by pedroigor** [comment]
@jlsjonas For me it makes sense to have this toggle if we really need to differentiate the two but it adds a bit more complexity.

If it works for you to resolve from both sources, better I would say.
