### ISSUE TITLE
Rename "Realm name" field to "Realm ID" field in realm creation screen

### ISSUE THREAD

**Issue by Anil-Shanker** [keycloak/keycloak#23496]
### Description

Issue based on [this discussion post](https://github.com/keycloak/keycloak/issues/17735#issuecomment-1697830183).

When creating a new Realm, the field "Realm name" is a misnomer because it in fact refers to "Realm ID":

![image](https://github.com/keycloak/keycloak/assets/98241053/194f466b-18a9-44e3-b3e5-5c3c9c6ae06c)

![image](https://github.com/keycloak/keycloak/assets/98241053/ead31820-84b0-4d30-9231-f7df12f10332)

**Comment by etiksouma** [comment]
@jonkoops  jupt opened a PR for this issue.

**Comment by sschu** [comment]
Looking at the documentation, the term "realm name" seems to be the most commonly used. It would probably make sense to decide which term is correct and then adapt this consistently.

**Comment by mposolda** [comment]
**In shortcut:** IMO the "realm creation page" is correct, but the "realm details" page is incorrect as it refers "Realm ID" to something, which is rather "Realm name". Will be good to update the "Realm details" page and rename the field "Realm ID" to "Realm name" .

**More details:** It makes sense that there is field "Realm name" on realm creation page where administrator has a way to specify "Realm name" . When this is done, the name specified is really the "name" when the ID of the realm is generated. For instance, when I create realm with name `foo`, I see this content in the DB:
```
ID: 38f25878-91e1-479d-942d-8cf49651432a
NAME: foo
```

This is good behaviour IMO (Also see this comment for more context: https://github.com/keycloak/keycloak/issues/27506#issuecomment-2010049778 )

But IMO it can be useful to rename the field "Realm ID" on the "realm details" page to "Realm name" as it actually refers to the name, not ID.

**Comment by etiksouma** [comment]
If the realm ID here is not to be understood as an "easy-to-remember" unique identifier then you definitely are right.
I will adapt the PR.

**Comment by etiksouma** [comment]
@jonkoops FYI the PR is updated
