### ISSUE TITLE
User cannot be created via Admin UI if custom user attribute is required

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#23507]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When having the user-profile feature enabled and having a custom user attribute marked as required, admin cannot create user via the Admin UI because the attribute is not displayed in the user creation screen, therefore cannot be provided. The field is only shown when editing user and can be set there (have to make the attribute optional)...

### Version

nightly

### Expected behavior

Admin is able to create user via Admin UI when having custom user attributes marked as required.

### Actual behavior

Admin is not able to create user via Admin UI when having custom user attributes marked as required.

### How to Reproduce?

- Enable the user-profile and add new custom user attribute (for e.g locale) and mark it as required
- Try to create user as an admin

### Anything else?

For implementing this a new endpoint for accessing the user profile metadata would become necessary, as the user details API can not be used. It would make sense to afterwards also use that API on the user details screen and decommission the old way.

On the create user screen no inputs for user profile attributes are rendered - if one is required the user can not be created of course. The issue seems to be that for the UserForm to render the UserProfileFields also a user has to be present at the moment:
https://github.com/keycloak/keycloak/blob/d8ff73e34f4cbaae18b9926a42d22a0aeda74854/js/apps/admin-ui/src/user/UserForm.tsx#L226-L228
The user is undefined in case of create user.

imho this is a general flaw of the user screens gathering the user profile metadata through the user details api. Instead maybe a dedicated endpoint in the ui-ext extension should be added, allowing for users with view-users or manage-users permissions to gather the user profile metadata for admin ui (create and edit user - no user entity necessary). When this would be refactored, it could also be addressed, that there is a [discrepancy between what the frontend thinks it gets and what the backend actually returns](https://github.com/keycloak/keycloak/issues/23443) for user profile metadata, resulting in user profile attribute validators to not work in the admin ui.

Afterwards the additional parameter and response data can be removed from the users api ...

**Comment by jonkoops** [comment]
> imho this is a general flaw of the user screens gathering the user profile metadata through the user details api.

Yeah, I totally agree with this. 

> Instead maybe a dedicated endpoint in the ui-ext extension should be added, allowing for users with view-users or manage-users permissions to gather the user profile metadata for admin ui (create and edit user - no user entity necessary). 

I am not sure this is the correct solution, but I agree this data should probably come from a specific endpoint, rather than being present on the user itself.

**Comment by sertal70** [comment]
This is happening to me using Keycloak v22.0.3. 
But if I use Keycloak v22.0.1 I can manage user profile attributes without errors both in create and edit user pages of Admin UI. 

![image](https://github.com/keycloak/keycloak/assets/25665841/6da07b30-9671-4c9d-a2df-f402dfcec70c)

**Comment by jonkoops** [comment]
> Maybe it should in a follow up be checked, whether having the metadata in the user details endpoint is still necessary.

Yeah, I don't quite understand the need for that either. @keycloak/core why was this decision made?

**Comment by pedroigor** [comment]
Do you mean using the `/users/profile` endpoint?

**Comment by antikalk** [comment]
> Do you mean using the `/users/profile` endpoint?

No it is `/users/{userId}` - why does it need to contain the user profile metadata (conditionally on a query parameter)?

**Comment by antikalk** [comment]
> The only reason was to avoid publishing another endpoint and an additional call from clients. But I see the problem when the user is being created.
> 
> It make sense to me to provide one, perhaps under `/users/profile/metadata` ?

Actually I think that `/users/profile` already returns all the informations necessary. At least that is the endpoint being used in the PR :)

**Comment by pedroigor** [comment]
The problem with that endpoint is that it returns the raw configuration and not the actual metadata. For instance, you won't get whether a field is read-only and without any filtering on how permissions are set.

**Comment by antikalk** [comment]
> The problem with that endpoint is that it returns the raw configuration and not the actual metadata. For instance, you won't get whether a field is read-only, and without any filtering on how permissions are set.

Okay. But doesn't the raw configuration contain all information? It would have to be validated whether read-only, validators, etc. properties work with the implementation done in the PR. If not, maybe this additional endpoint `/users/profile/metadata` would become necessary and should be used on a user create and update.

**Comment by pedroigor** [comment]
@antikalk Yeah, I'm adding this endpoint so that we can have metadata without a user. I'm preparing a PR.
