### ISSUE TITLE
Creating a Protocol Mapper with custom ID leads to UI issues

### ISSUE THREAD

**Issue by vfauth** [keycloak/keycloak#23516]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

With Keycloak 21.x or 22.x, if I use the REST admin API to create a client-scope with protocol mappers with custom IDs, it works, but if I go to the web UI and try to open this mapper details, I get a "Could not find the resource that you are looking for" error. The API seems to work fine.

Setting an ID works if I use an ID generated by Keycloak when creating another resource, so it seems to be an issue with formatting. Setting a custom id of the correct length doe snot fix the issue.

### Version

22.0.3

### Expected behavior

I can use the API to create a client-scope with protocol mappers with custom IDs.

### Actual behavior

It works but the web UI can't display the mapper.

### How to Reproduce?

Crate a `client-scope.json` file:

```json
{
  "id" : "test",
  "name" : "Test",
  "protocol" : "openid-connect",
  "attributes" : {
    "include.in.token.scope" : "true",
    "display.on.consent.screen" : "true",
    "gui.order" : "",
    "consent.screen.text" : ""
  },
  "protocolMappers" : [ {
    "id" : "my-custom-id",
    "name" : "audience resolve",
    "protocol" : "openid-connect",
    "protocolMapper" : "oidc-audience-resolve-mapper",
    "consentRequired" : false,
    "config" : { }
  } ]
}
```

Then run `kcadm.sh create -r master client-scopes -f client-scope.json`

Go to Keycloak web UI, open the `test` client-scope, go to the `Mappers` tab then click on `audience resolve`. You will get an error.

**Comment by mposolda** [comment]
Thanks for the report. I am adding to Backlog as not sure if Keycloak team has a time to look at this in the near future. Anyone is welcome to investigate this and send PR for fixing this.

**Comment by peps14** [comment]
Just analyzed the problem, it seems more like a bug on the ui (if you want to maintain the possibility of creating a mapper with custom ID).
The path parameter mapperId is used on the same path to distinguish both the protocol mapper id during creation and the mapper id during modification of a client-scope mapper. The distinction is made by reading the GUID format, which causes the ui bug in the case of a custom format for mapper id.

**Comment by edewit** [comment]
The problem is that `my-custom-id` is not in the list of `serverInfo.protocolMapperTypes`
