### ISSUE TITLE
Better usability when disabling user profile and loosing the previous cofiguration

### ISSUE THREAD

**Issue by paulwer** [keycloak/keycloak#23527]
### Description

Hey folks,
today we discovered, that when we (for us it seems temporary) disable the userProfile functionality, all data regarding the extra defined fields is gone.

Is there any chance, to save them, until this feature is activated again or to display a warning, within the admin-console.
So this cannot happen within prod.

### Details

keycloak 21.1.2
occurs, when userProfiles were enabled and fields defined, 
then disable userProfiles, save and enable it again

**Comment by EraKin575** [comment]
I would like to work on this

**Comment by EraKin575** [comment]
I would like to work on this issue

**Comment by paulwer** [comment]
do you need any additional informations?

**Comment by EraKin575** [comment]
@paulwer  yes, please

**Comment by paulwer** [comment]
what do you need?

**Comment by jonkoops** [comment]
This is not an enhancement, but rather a bug. Please read the issue template before filing an issue.

**Comment by jonkoops** [comment]
@pedroigor this seems to be your domain, can you take a look at this and determine the impact?

**Comment by pedroigor** [comment]
@jonkoops It is an expected behavior. Disabling the user profile reverts to the default settings.

If you want to save it, you can save the JSON configuration. That is one of the reasons why we have it there.

**Comment by paulwer** [comment]
for me it would be ok, if all data gets deleted, but without any message this can happen quite easily and all data would be lost, which can be dramatic with a large userbase. am I right?

**Comment by pedroigor** [comment]
Makes sense to me. I'm adding this one to the project we are using to make the feature supported. We will evaluate what we can deliver in Keycloak 23 or 24 when the feature is supposed to be delivered.

**Comment by pedroigor** [comment]
It depends on https://github.com/keycloak/keycloak/issues/20970.
