### ISSUE TITLE
NullPointerException in SAML IdP Logout request with SessionIndex and without NameID 

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#23528]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

Based on Section 3.7.1 of [Assertions and Protocols for the OASIS
Security Assertion Markup Language
(SAML) V2.0 – Errata Composite](https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf), BaseID or NameID or EncryptedID must be present in the LogoutRequest. SessionIndex is optional.
Keycloak now assumes that NameID always exists.

This throw a NullPointerException for SAML IdP Logout request with SessionIndex and without NameID (BaseID  or EncryptedID) exists. Keycloak must check that at least one of BaseID, NameID and EncryptedID exists and after that if SessionIndex exists, logout request will be handled based on SessionIndex.
As mentioned in the document: 

> If no <SessionIndex> elements are supplied, then all sessions associated with the principal MUST be
invalidated

### Version

22.0.3

### Expected behavior

SAML IdP Logout request with SessionIndex and without NameID (BaseID  or EncryptedID) will succeed to logout User.

### Actual behavior

NullPointerException

### How to Reproduce?

Send Logout Request from a SAML IdP that support it and send SessionIndex together with BaseID  or EncryptedID (fe https://idp.admin.grnet.gr/idp/shibboleth)

**Comment by mposolda** [comment]
@cgeorgilakis Thanks for the report. I am adding to Backlog as not sure if Keycloak team has a time to look at this in the near future. Anyone is welcome to investigate this and send PR for fixing this.

**Comment by cgeorgilakis** [comment]
@mposolda I have opened a [PR](https://github.com/keycloak/keycloak/pull/23529) for this. Could you review it whenever possible.

@bonnm you are right. It still exists. I have updated affected version.
