### ISSUE TITLE
User profile fields in admin console should render input based on annotations

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#23538]
When rendering user profile fields in the registration flow and account console the fields are rendered based on their type. In the administration console this is not always the case. In this task we need to find out which fields are different from their counterparts in other UIs.

**Comment by pedroigor** [comment]
@ssilvert @jonkoops @edewit Looks like we have already this fixed and supported in the administration and account console. IIRC, @edewit did a refactoring to share code between the two UIs and a sanity check from my side shows that we can set annotations like type, help text, etc, and see the fields being rendered accordingly.

I would say that if there are more improvements to be made we can do as a follow-up in a separate task and perhaps close this one.

Does it make sense for you?

**Comment by jonkoops** [comment]
Yeah, now that the implementations have been unified I think we can go ahead and close this issue :+1:

**Comment by edewit** [comment]
Yes, all good
