### ISSUE TITLE
Debug log contain sensitive data

### ISSUE THREAD

**Issue by doufum** [keycloak/keycloak#23548]
### Description

We are doing a security scan and in the debug log of keycloak, it contains the user's encrypted password.
I know this is a hibernate feature, but as an IAM system, I wonder if keycloak desensitizes or does not output sensitive data when it outputs the logs.

Also session-id is directly output in the debug log, is it possible to desensitize the output of these.
Just like:
```
DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-16) org.keycloak.models.jpa.entities.CredentialEntity{userLabel=null, createdDate=1692674980343, salt=null, id=2a5fba7a-538c-4e56-8025-8d9db380edaf, credentialData={\"hashIterations\":27500,\"algorithm\":\"pbkdf2-sha256\",\"additionalParameters\":{}}, priority=10, type=password, user=org.keycloak.models.jpa.entities.UserEntity#3a680963-8bfd-4a7a-8f62-9d4a0ce00957, secretData={\"value\":\"z2K11tFHFaW/6Cr9Z/s1vz3YwQ81bZ/69uUJ56da/7I=\",\"salt\":\"zGfFi4ipCYCWt37ybwA0Nw==\",\"additionalParameters\":{}}}\n","stream":"stdout","time":""
DEBUG [org.hibernate.internal.util.EntityPrinter] (executor-thread-16) org.keycloak.events.jpa.EventEntity{clientId=rightcloud-management, realmId=0b919202-d8da-4dfb-8adc-51c615474f7f, ipAddress=10.112.34.67, id=9487c689-983f-46eb-836e-55d65343db72, sessionId=edca0843-f4ef-4ea5-a51e-97c066a8805d, time=1695222574192, error=null, type=LOGIN, userId=3a680963-8bfd-4a7a-8f62-9d4a0ce00957, detailsJson={\"auth_method\":\"openid-connect\",\"auth_type\":\"code\",\"redirect_uri\":\"https://management.xxxxxxxxx.com:8443/#/\",\"consent\":\"no_consent_required\",\"code_id\":\"edca0843-f4ef-4ea5-a51e-97c066a8805d\",\"username\":\"liangcheng\"}}
```

We also know that we can control the log level of a package by using the `KC_LOG_LEVEL`(`--log-level`) parameter, but once this configuration item is changed, the debug logs will be exposed.

Now our solution is to add the specified package log to the configuration as a fixed info level output, but there is still a risk of sensitive information being exposed by modifying the configuration.
```yaml
- name: KC_LOG_LEVEL
  value: "debug,org.keycloak.models.cache:info,org.hibernate:info,org.keycloak.events:info"
```

**Comment by kaustubh-rh** [comment]
@doufum , thanks for sharing , can you share the exact steps to reproduce the issue ?

**Comment by mposolda** [comment]
I am not 100% sure if this is bug. The debug log for hibernate is disabled by default and must be explicitly enabled and the debug stuff is shown just when explicitly enabled. Also the data in the log should be protected somehow, so only system administrators can view them (which is same guy, who can usually also view DB and hence can see the data in the DB directly).

We can possibly check if there is some hibernate annotation to signal that logging of the specified field should be hidden, but otherwise I am not seeing much possibility to address this at the Keycloak level.

Leaving for the "Store" team to triage this.

**Comment by stianst** [comment]
Ideally we would sanitize this, but don't think that is possible. You should really never enable debug logging for org.hibernate for a production deployment in either case as it produces way more information that you will ever need. I'd suggest taking a look at https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/logging/Logging.html and enable specific categories, and not the whole of org.hibernate.
