### ISSUE TITLE
Cross Site Scripting (XSS) – Reflected via redirect_back_uri Parameter

### ISSUE THREAD

**Issue by Alwardani** [keycloak/keycloak#23556]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Description of problem:

When i search for a bug in the at&t platform i found a security vulnerability related to Keycloak application and it is reflected cross-site scripting (XSS) occur when an attacker injects browser executable code within a single HTTP response in the parameter redirect_back_uri .
When a web application is vulnerable to this type of attack, it will pass unvalidated input sent through requests back to the client.

### Version

version 15

### Expected behavior

1- Filter input on arrival.
2- Encode data on output. 
3- Content Security Policy. 

### Actual behavior

Cookie Stealing: A malicious user can steal cookies and use them to gain access to the application.
Arbitrary requests: An attacker can use XSS to send requests that appear to be from the victim to the web server.
Malware download: XSS can prompt the user to download malware. Since the prompt looks like a legitimate request from the site, the user may be more likely to trust the request and actually install the malware.

### How to Reproduce?

Steps to Reproduce:
1. Setup the application on your system.
1. Login to the application 
2. Open the following URL: 

https://localhost/iam/realms/cdm-us-mng/account/password?redirect_back_uri=javascript:confirm(1)

https://localhost/iam/realms/{your_application_realms}/account/password?redirect_back_uri=javascript:confirm(1)

4. Click on ```Back to the application```

5. The xss will trigger directly as shown in the screenshot.

https://drive.google.com/file/d/1YNJjMIlieXBzjJL4gGVE-WM97p5Gw9r9/view?usp=sharing

**Comment by ssilvert** [comment]
Keycloak 15 is very old.  We have rewritten the entire account console since then.  Can you reproduce this on the latest version?

Also, I don't remember a param called `redirect_back_uri`.  Do you mean `referrer_uri`?

**Comment by Alwardani** [comment]
- I'm sorry the **Keycloak** was **17.0.1**

- The URL was: https://localhost/iam/realms/cdm-us-mng/account/password?redirect_back_uri=javascript:confirm(document.domain) so the parameter was **redirect_back_uri**

- Please check the screenshot.

https://drive.google.com/file/d/1YNJjMIlieXBzjJL4gGVE-WM97p5Gw9r9/view?usp=sharing

**Comment by ssilvert** [comment]
Keycloak 17 is also very old.  We have rewritten the entire account console since then. Can you reproduce this on the latest version?

**Comment by ssilvert** [comment]
Closing as out of date.
