### ISSUE TITLE
Admin REST API using a service account is super slow (> 0.5s) when using MAP_STORAGE

### ISSUE THREAD

**Issue by ghilainm** [keycloak/keycloak#23575]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

When searching for data using a service account using the admin API the queries are super slow.

It seems to be linked to the fact that the query is done on a metadata `fServiceAccountClientLink` in the kc_user table.

This is done on a test database with 

This value is null for all the users except the service accounts.

Here is an example of the problematic query:

select j1_0.id,j1_0.version,j1_0.entityVersion,j1_0.realmId,j1_0.username,j1_0.usernameWithCase,j1_0.firstName,j1_0.lastName,j1_0.email,j1_0.emailConstraint,j1_0.federationLink,j1_0.enabled,j1_0.emailVerified,j1_0.timestamp from public.kc_user j1_0 where j1_0.realmId='5a661de5-1694-4d57-bcd7-a237f65b04a8' and j1_0.metadata->>'fServiceAccountClientLink'='215b62f5-5f1f-4c41-9e1a-e02343cbeda2'

Example of trace using admin API to get a user by id.

![image](https://github.com/keycloak/keycloak/assets/661772/3851b31b-a750-4254-8d99-87ef9b9c8aef)

### Version

22.0.1

### Expected behavior

Must be fast.

### Actual behavior

Slow

### How to Reproduce?

Use any admin API operation

**Comment by ghilainm** [comment]
By the way, I solved it by adding an index on the column, but I don't like modifying Keycloak schema. So I guess it should be supported out of the box.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
