### ISSUE TITLE
Investigate the impact of content-type response change

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#23580]
### Description

With #23459 it was noticed that the server was responding with a content-type that included the charset, but the admin cli client was written to only expect the mime type.  Another commit was added to that pr to address this, but a concern would be that other places in the code base could be making a similar assumption, and/or have their handling of the content-type improved by using the apache ContentType class.

cc @vmuzikar @keycloak/core

**Comment by vmuzikar** [comment]
+1 for updating the Admin CLI client to handle full content type and not just mime type. It'd be more robust and IMHO should've been done from the beginning.

**Comment by shawkins** [comment]
Since I couldn't find much else this would affect, I put an additional commit onto the open PR to consolidate the content-type handling.
