### ISSUE TITLE
It is not possible to apply required actions to a user if LDAP federation is enabled.

### ISSUE THREAD

**Issue by cesarcoruna** [keycloak/keycloak#23594]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

The problem occurs if user federation to an LDAP is enabled. When trying to add a required user action to the save an error occurs. In the log you get this trace

> 2023-09-29 09:05:16,511 WARN  [org.keycloak.services.resources.admin.UserResource] (executor-thread-1491) Could not update user!: org.keycloak.models.ModelException: Not possible to write 'required action UPDATE_PASSWORD' when updating user 'XXXXX'	at org.keycloak.models.utils.ReadOnlyUserModelDelegate.readOnlyException(ReadOnlyUserModelDelegate.java:146)	at org.keycloak.models.utils.ReadOnlyUserModelDelegate.addRequiredAction(ReadOnlyUserModelDelegate.java:71)	
at org.keycloak.models.utils.UserModelDelegate.addRequiredAction(UserModelDelegate.java:105)	
at org.keycloak.storage.ldap.LDAPWritesOnlyUserModelDelegate.addRequiredAction(LDAPWritesOnlyUserModelDelegate.java:86)	
at org.keycloak.models.utils.UserModelDelegate.addRequiredAction(UserModelDelegate.java:105)

### Version

22.0.3

### Expected behavior

That it records correctly and the action remains active.

### Actual behavior

The action is not recorded

### How to Reproduce?

The federation of users to an LDAP must be activated. Without federation it works correctly.

**Comment by ssilvert** [comment]
This doesn't look likely to be a UI bug.  Transferring to core.

**Comment by mposolda** [comment]
This is LDAP, so it falls under "store" team IMO. However this might not be a bug at all as it seems that you have "Edit mode" on your LDAP provider configured to "Read only" . And also that you have disabled import. Is it correct?

If you enable "Import" and/or switch edit mode to something else (unsynced or writable), required actions should be possible to add.

Still, the usability around this can be improved though. TBH the "import" switch on LDAP provider looks confusing to me and wonder if we can remove it entirely. However that is for wider discussion and likely not the focus on this particular bug.

**Comment by cesarbtt** [comment]
i have edit mode to "WRITABLE", import users to "OFF", sync registrations to "ON" and cache policy in "NO_CACHE".

**Comment by cesarcoruna** [comment]
The problem is effectively solved if you enable the "Import users" option in the LDAP federation configuration in conjunction with a "Writable" mode.

**Comment by pedroigor** [comment]
Glad you sorted it out. By enabling importing users they are now managed by Keycloak itself as they are persisted in its internal database. As such, you can now leverage all the capabilities supported by Keycloak like managing required actions for your users.
