### ISSUE TITLE
Docs: hardware requirements

### ISSUE THREAD

**Issue by lonix1** [keycloak/keycloak#23593]
### Description

The docs are comprehensive and of a high quality.

But they are missing details of the app's "minimum hardware requirements": *cpu, memory, disk space, etc.*

It would be very helpful for new users if that could be added to the "getting started" docs.

**Comment by ahus1** [comment]
Some docs for this are now available here: https://www.keycloak.org/high-availability/concepts-memory-and-cpu-sizing (since Keycloak 24).
