### ISSUE TITLE
Support generated ECDH realm keys

### ISSUE THREAD

**Issue by justin-tay** [keycloak/keycloak#23596]
### Description

Add key provider that can generate ECDH keys that can support the ECDH-ES, ECDH-ES+A128KW, ECDH-ES+A192KW and ECDH-ES+A256KW JWE algorithms.

### Motivation

To support the ECDH-ES, ECDH-ES+A128KW, ECDH-ES+A192KW and ECDH-ES+A256KW JWE algorithms.

**Comment by ronimhd** [comment]
hi @justin-tay , do you know when this issue will be closed and released in Keycloak distribution?

Thank you

**Comment by rindishkrishna** [comment]
we would also let to get this code merged. 
Thanks

**Comment by justin-tay** [comment]
Hi @rindishkrishna , @ronimhd this really depends on the availability of a maintainer to review and merge the pull request which really depends on the level of community interest in this feature. You can help to improve the visibility of this issue by upvoting the related issues and the pull requests.

**Comment by Manisha1995vash** [comment]
@justin-tay if this code is not merged yet, did you try another approach to get this functionality working in your project?
if yes, could you please share what steps did you follow?

**Comment by justin-tay** [comment]
You will need to write your own `org.keycloak.broker.oidc.OIDCIdentityProvider` implementation if you need to perform encryption using ECDH-ES, ECDH-ES+A128KW, ECDH-ES+A192KW and ECDH-ES+A256KW JWE algorithms.
