### ISSUE TITLE
invalid tag in .ftl file

### ISSUE THREAD

**Issue by paulwer** [keycloak/keycloak#23616]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

the mentioned file contails an invalid </select>, which is ignored by browsers, but not valid in the context, where its used.
https://github.com/keycloak/keycloak/blob/1f44474aac75ffc5fa5f0a3a476a1c9c330f2f5b/themes/src/main/resources/theme/base/login/user-profile-commons.ftl#L172

### Version

21.0.2

### Expected behavior

removal invalid closing select tag

### Actual behavior

browsers ignore this tag

### How to Reproduce?

create a variable in userProfile and open a page like register to display it (look at source not dev-tools)

**Comment by rmartinc** [comment]
@paulwer Isn't it the close tag for the [select](https://github.com/keycloak/keycloak/blob/22.0.3/themes/src/main/resources/theme/base/login/user-profile-commons.ftl#L117-L122) just a bit above?

**Comment by paulwer** [comment]
from my pov this is an opening tag within macro selectTag, but not at the mentioned macro inputTagSelects, which is a different one.

macro inputTagSelects just has a closing tag and within the macro it is just not required. am I right?

**Comment by rmartinc** [comment]
Ah! Yes, I jumped to the previous macro, sorry. Please send a PR just deleting that line.
