### ISSUE TITLE
DELETE User returns 404 on Success

### ISSUE THREAD

**Issue by MorgeMoensch** [keycloak/keycloak#23624]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

When deleting a User, it returns 404 with Body "Error: Not found" even though the user exists and gets deleted.

### Version

22.0.1

### Expected behavior

Upon successful deletion, the API returns 200 or 204.

### Actual behavior

Even with successful deletion, the API returns 404

### How to Reproduce?

1. Create Realm User
2. Delete User via UI
3. Look at the Network Tab, the corresponding DELETE-Call returns a 404
4. Check in the DB: the User is actually deleted

**Comment by rmartinc** [comment]
Hi @MorgeMoensch! I cannot reproduce this, the delete always returns a 204 for me. Tested in last main branch and 22.0.1. Maybe it's because you have a more complicated setup. Can you test in a new realm, create and delete a user in a fresh realm?

**Comment by MorgeMoensch** [comment]
Hello @rmartinc 

Interestingly, it works in a different realm. I tried on my original realm again, and it works for other users as well. I was able to reproduce it reliably before opening the issue by re-adding the row of the user directly in the DB.

But seems like this is a false alarm. Sorry for that and thanks for the prompt response.
