### ISSUE TITLE
Keycloak fails to start in MySQL Group Replication

### ISSUE THREAD

**Issue by cjabrantes** [keycloak/keycloak#23644]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Keycloak fails to start with MySQL GroupReplication:

2023-10-02 17:25:08,692 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.DatabaseException: The table does not comply with the requirements by an external plugin. [Failed SQL: (3098) INSERT INTO keycloak.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1.0.0.Final-KEYCLOAK-5461', 'sthorger@redhat.com', 'META-INF/jpa-changelog-1.0.0.Final.xml', NOW(), 1, '8:bda77d94bf90182a1e30c24f1c155ec7', 'createTable tableName=APPLICATION_DEFAULT_ROLES; createTable tableName=CLIENT; createTable tableName=CLIENT_SESSION; createTable tableName=CLIENT_SESSION_ROLE; createTable tableName=COMPOSITE_ROLE; createTable tableName=CREDENTIAL; createTable tab...', '', 'EXECUTED', NULL, NULL, '4.20.0', '6267483099')]

The table does not comply with the requirements by an external plugin.

Checking the table DATABASECHANGELOG, it does not have any column being a  key or non-null unique which is mandatory in MySQL innodb cluster that uses GroupReplication

Note: I didn't understood well the nightly release part also Area may be incorrect.

### Version

22.0.3

### Expected behavior

KeyCloak must start.

### Actual behavior

KeyCloak fails to start

### How to Reproduce?

deploy keycloak with MySQL innodb cluster that uses GroupReplication

**Comment by rmartinc** [comment]
@cjabrantes I think this is more or less the same than [KEYCLOAK-13145](https://issues.redhat.com/browse/KEYCLOAK-13145). We test Oracle RAC and MariaDB galera, not MySQL replication. I think that there is a limitation in Liquibase that can be solved adding manually a PK index in the liquibase table. Adding store team to confirm.

**Comment by cjabrantes** [comment]
Hi @rmartinc,
I was also checking further:
https://docs.liquibase.com/concepts/tracking-tables/databasechangelog-table.html#:~:text=The%20table%20tracks%20each%20changeset,all%20rows%20of%20the%20table.

I think you are absolutely correct, but not sure what is the best way to do it, meaning that if KC dont finish the first start seems that the next ones it complains about some already existing tables, we made it work by:
 Connecting KC to a standalone MySQL
 Make the dump
 Add PK 
 Restore it in MySQL cluster


As i m new to KC, is this a good way to do? i mean now that i have a working DB schema, can i use upfront and then to deploy KC? could we have problem if upgrade KC later?

Many Thanks,

**Comment by rmartinc** [comment]
You can manually setup the database. So you can start doing something similar to:

```
./kc.sh start-dev --db mysql --db-username keycloak --db-password XXXX --db-url XXXX --spi-connections-jpa-legacy-migration-strategy manual --spi-connections-jpa-legacy-initialize-empty false
```

That creates a `keycloak-database-update.sql` you can modify (adding the index on DATABASECHANGELOG table, for example in ORDEREXECUTED field). Then Execute to the database. More in info in the [db guide](https://www.keycloak.org/server/db#_setting_jpa_provider_configuration_option_for_migrationstrategy).

**Comment by cjabrantes** [comment]
Thanks for all the tips.
