### ISSUE TITLE
Passkeys: investigate and check it works with Keycloak

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23658]
### Description

This is about investigation how to make Keycloak working with passkeys. Some notes from @stianst :
```
Passkeys are also super cool. I tried out https://passkeys.io/ and was easily able to login on my laptop through my phone. I suggest giving it a go yourself.

Also, check out https://passkeys.dev/ for more info on the dev side of things.

Problem is we're not taking advantage of it at all. Keycloak doesn't even support Passkeys right now, but I assume that it would be relatively trivial to do so, as the complex parts of WebAuthn we already support.
```

Some other points (with links to existing community prototypes, extensions etc) are linked from the discussion https://github.com/keycloak/keycloak/discussions/16201. Maybe it is possible to re-use prototypes referenced from discussion and just "fork" them directly to Keycloak? Is it possible to re-use our WebAuthn authenticators?

**Comment by twaijn** [comment]
AFAIK Passkeys do work already in Keycloak 22. We've tested with iOS and Android on Mac, Windows and Linux with modern browsers, and production use is starting.

**Comment by tnorimat** [comment]
I and @thomasdarimont tested features of passkeys on the current keycloak (22.0.4) as follows.
Accoding the result of the test, It might be OK to say that the current keycloak already supported parts of passkeys features.

1. Windows Environment

- Windows PC
  - OS: Windows 11 Pro 22H2
  - Browser: Google Chrome 118.0.5993.89
- Android Smartphone
  - OS: Android 11
- Keycloak
  - version: 22.0.4

- Created passkeys
  - synced passkey created by Android Smartphone
  - synced passkey created by Google account management on Chrome of Windows PC
  - device-bound passkey created by Windows PC

- Cross-Device Authentication
  - Client: Windows PC
  - Authenticator: Android Smartphone
  - Passkey registration / Authentication by passkey
    - synced passkey created by Android Smartphone -> **OK**
    - synced passkey created by Google account management on Chrome of Windows PC -> **NG** (*)

- Same-Device Authentication
  - Client: Windows PC
  - Authenticator: Windows PC
  - Passkey registration / Authentication by passkey
    - device-bound passkey created by Windows PC -> **OK**
    - synced passkey created by Google account management on Chrome of Windows PC -> **NG** (*)

*: the pattern does not work on the environment, according to https://passkeys.dev/device-support/
- Synced Passkeys
   - Android: OK
   - Windows: NG
- Cross-Device Authentication Authenticator
   - Android: OK
   - Windows: NG
- Cross-Device Authentication Client
   - Android: NG
   - Windows: OK

2. Mac Environment

- MacBook Pro
   - OS: macOS 13.6 (Ventura)
   - Browser: Google Chrome 118.0.5993.88
- iOS Smartphone
   - OS: iOS 16.7
- Keycloak
   - version: 22.0.4
 
- Created passkeys
  - synced passkey created by iOS Smartphone
  - synced passkey created by Google account management on Chrome of MacBook Pro
  - device-bound passkey created by macOS
 
- Cross-Device Authentication
  - Client: macOS
  - Authenticator: iOS Smartphone
  - Passkey registration / Authentication by passkey
    - synced passkey created by iOS Smartphone -> **OK**
    - synced passkey created by Google account management on Chrome of macOS -> **OK**
 
- Same-Device Authentication
  - Client: macOS
  - Authenticator: macOS
  - Passkey registration / Authentication by passkey
    - device-bound passkey created by macOS -> **OK**
    - synced passkey created by Google account management on Chrome of macOS -> **OK**
 
The pattern does not work on the environment, according to https://passkeys.dev/device-support/
- Synced Passkeys
   - iOS: OK
   - macOS: OK
- Cross-Device Authentication Authenticator
   - iOS: OK
   - macOS: OK
- Cross-Device Authentication Client
   - iOS: OK
   - macOS: OK

**Comment by tnorimat** [comment]
@mposolda Could you check the investigation described above?

**Comment by mposolda** [comment]
Closing this issue based on your suggestion. Thanks for the investigation!
