### ISSUE TITLE
Scope Is not getting retrieved in the RPT token in the scope-based permission

### ISSUE THREAD

**Issue by sridhar1495** [keycloak/keycloak#23655]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

I am working on the authorization configuration for my client. The configuration is as follows

1. I created my resource_A with type as 'urn:myservice:resourceA', and I haven't mapped the scopes in the resource.
![image](https://user-images.githubusercontent.com/75622411/271187495-74a351c9-d187-4552-97a1-ca227272778b.png)
2. I have resources as GET, POST, PUT and DELETE.
![image](https://user-images.githubusercontent.com/75622411/271187623-efe120f4-8b9d-4d3b-a8fe-8e54eb8a87b5.png)
3. Then created RBAC policy 'resourceA_get_policy'.
![image](https://user-images.githubusercontent.com/75622411/271187911-7bf36acc-f0a6-4403-8da5-c809be9db943.png)
4. I am creating scope-based-permission. where I gave the resource type as 'urn:myservice:resourceA', and selected the scope as GET and selected the 'resourceA_get_policy'.
![image](https://user-images.githubusercontent.com/75622411/271188102-1cc5e9da-64c9-4882-8e61-d69602205436.png)
5. On getting the RPT token. The evaluation is getting passed and I am getting the RPT token. But the issue is, in the RPT token I am getting the resourceId(rsid) and resource name(rname) but not getting the scope that is passed there.
![image](https://user-images.githubusercontent.com/75622411/271188381-dc68a363-eca1-4778-98aa-b6b81ef21a01.png)

6. I am getting the scope only if the scopes are associated with the resource in the resource tab.
![image](https://user-images.githubusercontent.com/75622411/271188596-abb36622-3990-4167-96fd-e12875ba26c9.png)
![image](https://user-images.githubusercontent.com/75622411/271188523-c8c5c3c6-cabe-4e11-a72d-0fba3c522632.png)

### Version

22.0.3

### Expected behavior

As explained in the bug description It is only getting the scope if that is found in the 'Authorization scopes' of the resources. But it needs to be fetched from the scopes tab after the evaluation is completed. 

### Actual behavior

The scope is not added in the RPT token after the evaluation is completed.

### How to Reproduce?

1. Create resource 'resource_A' with type as 'urn:myservice:resourceA', and don't map any scopes to the resource.
2. Create resources as GET, POST, PUT and DELETE.
3. Create Role Based policy 'resourceA_get_policy'.
4. Create scope-based-permission. and give the resource type as 'urn:myservice:resourceA', and selected the scope as GET and selected the 'resourceA_get_policy'.
5. Get the RPT token and check the permissions that for the resource the scope is present.

### Anything else?

If there is not a bug and the expected behavior can be achieved from any configuration (Other than adding the Scopes to the resource) please let us know.

**Comment by pedroigor** [comment]
@sridhar1495 The behavior is expected and only the scopes associated with a resource are granted.
