### ISSUE TITLE
Attributes tab fields are not changing when a different group is selected 

### ISSUE THREAD

**Issue by kitaniboy** [keycloak/keycloak#23654]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I am using Docker and Google Chrome. In the Groups section, when I select the attributes tab and change the group selected, the fields do not change. Meaning if I select Group 1 and see the attributes of Group 1, then change the selected Group to Group 2 while the attributes tab is still selected, the attributes appearing are Grpup1's attribute not Group 2's.

### Version

22.0.3

### Expected behavior

The attributes shown is changed whenever the group selected is changed.

### Actual behavior

The attributes shown to do not change when the attributes tab is selected and the group is changed.

### How to Reproduce?

Select the Groups section, select a group, select the attributes tab, change the selected group, notice that the attributes haven't changed.

**Comment by transducer** [comment]
This happens only on attributes of parent groups, it does work for subgroups

## Reproduction scenario

### Switching between parent groups
- Create parent group add attribute "foo" with value "bar"
- Create parent group add attribute "foo2" with value "bar2"
- Click on first parent group, then click on the other => attributes of first clicked parent group are only visible
- Refresh parent group attributes by clicking on Members and back on Attributes => Attributes of last clicked group are visible

### Switching between subgroup and parent group
- Create parent group add attribute "foo" with value "bar"
- Create subgroup add attribute "baz" with value "qux"
- Create subgroup add attribute "quz" with value "quux" 
- Click on subgroup
- Click on parent group => attributes of subgroup are still visible
- Refresh parent group attributes by clicking on Members and back on Attributes => Attributes of parent group are visible

## Example parent groups
![example parent groups](https://github.com/keycloak/keycloak/assets/5002921/40f7469b-4ba3-4b58-a087-3d0eaa5afd37)


## Example subgroup to parent group
![keycloak group attributes](https://github.com/keycloak/keycloak/assets/5002921/46ef788f-529a-4cf1-ac50-c3a1b2a0f201)

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by jonkoops** [comment]
This has been backported and will be included in the 20.0.5 release.
