### ISSUE TITLE
Behavior of default value override with protocol mapper dependent on mapper name

### ISSUE THREAD

**Issue by lc-guy** [keycloak/keycloak#23662]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Setting a protocol mapper on a client that overrides the "preferred_username" token claim field only works if the mapper name is ALSO "preferred_username", whether as a dedicated client scope or a separate one.

![image](https://github.com/keycloak/keycloak/assets/5222114/a912ced8-8620-494c-ab73-060aeb32d702)

This one, for example, will not work.

### Version

20.0.3

### Expected behavior

The `preferred_username` field in the access token returned by the client should contain the hardcoded value.

### Actual behavior

The generated access token does not contain the replaced value.

![Screenshot from 2023-10-03 12-49-22](https://github.com/keycloak/keycloak/assets/5222114/3a7eca43-b7cd-4e6e-b0a3-154b4f202e84)

If the mapper is modified to have as "Name" the exact name of the field:

![image](https://github.com/keycloak/keycloak/assets/5222114/e57ce7b3-e9e6-448d-8555-b4c2802440e0)

Then the replaced value is actually taken into account:

![Screenshot from 2023-10-03 12-55-47](https://github.com/keycloak/keycloak/assets/5222114/93401321-5986-447a-ba28-d4008f0108cd)

### How to Reproduce?

See above.

**Comment by rmartinc** [comment]
@lc-guy if I'm not wrong the priority of both mappers (hardcoded and user-attribute) is 0. So you really don't know which one is going to be executed first.

If you really want to make sure your username is there, you better remove the username in that client managing its scopes.

**Comment by lc-guy** [comment]
@rmartinc Thanks for the info. As an aside, I am rather confused by the behavior of protocol mapper priorities. It seems that there is no way to set them for individual mapper instances; only the underlying implementation has a priority set, which makes it impossible to override an existing scope mapper (or set a running order) without writing your own protocol mapper implementation... that seems awfully impractical.

My tests concerning the mapper name being prioritized seem to be wrong, as after deleting and recreating it to test the impact of lexicographical order on name priority, it has stopped working again. Setting the "profile" scope to "optional" fixes the issue.

However, I would still consider it a bug that this type of configuration is completely random and unpredictable, without being able to configure the priority of the mappers, and without any indication in the documentation as to this behavior...

**Comment by rmartinc** [comment]
Yep, I think the order is just the priority ([here](https://github.com/keycloak/keycloak/blob/22.0.3/services/src/main/java/org/keycloak/protocol/ProtocolMapperUtils.java#L124-L136)) and, as you say, it's defined in the mapper implementation. Maybe we can change this but it has been like that since the client scopes were introduced.

It also makes sense IMHO, because I would not waste any time processing mappers that are going to be overwritten. In your case I would remove the "profile" client scope from the client, or the "username" mapper from the profile, maybe you want to add the rest of mappers, so you have to create another scope or similar with the mappers you want and assign it to the client. So, in summary, I would just execute one mapper that assigns the "preferred_username" playing with the client scopes used in the client.

If you want to continue with this, the issue will be probably moved to backlog.

**Comment by lc-guy** [comment]
@rmartinc I come to you with another question regarding this matter.

I've been attempting to introduce optional default claims within keycloak. Basically, I want the following behavior:

- if the user has an existing "preferred_username" attribute, add that value to the token (using an `User Attribute` mapper);
- if the user has no such attribute defined, then use a default value specified in a `Hardcoded claim` mapper.

Obviously, this solution hits the same issue as before (both token mappers, defined on the client, have priority 0, and thus random behavior as to when they overwrite each other e.g. the hardcoded claim might run after the user attribute one, rather than before).

Is there any way to introduce such default claims in a token?

Thanks in advance for your help.

**Comment by pedroigor** [comment]
@lc-guy @rmartinc One thing we can do is to set a priority to the mapper configuration with higher precedence over any built-in (greater than 0) mapper. With that we can perhaps override the built-in mappers (without sacrificing usability and forcing people to use JS mappers or remove/duplicate built-in mappers in the built-in client scopes).

For now, I'm closing this issue as it is not an issue but perhaps an enhancement.

**Comment by lc-guy** [comment]
> @lc-guy @rmartinc One thing we can do is to set a priority to the mapper configuration with higher precedence over any built-in (greater than 0) mapper. For instance, we can perhaps override the built-in mappers without sacrificing usability and forcing people to use JS mappers or remove/duplicate built-in mappers in the built-in client scopes. Mappers created by users will have a default priority set to `1`. Or just allow setting a priority when managing mappers through the Admin API.
> 
> For now, I'm closing this issue as it is not an issue but perhaps an enhancement. If you think it makes sense, I can create an issue about enabling overriding built-in mappers.

Yes, please, that would be a welcome improvement!

creating your own JS mapper is a _big_ hurdle in packaging and figuring out keycloak docs, compared to just adding an override through the GUI. It would avoid having people fall into the same pitfalls I did as well.

**Comment by ahamid** [comment]
I arrived here with the same issue: I assumed there was a deterministic way for one hardcoded claim (for example one assigned to a client scope qualified by role) to override another hardcoded claim of the same name (for example a hardcoded claim with a default value assigned to an unqualified scope). I could find no reliable ordering of the claims, either by context, or name, or creation/update timestamp (no such database column). It appears all mappers of the same type have the same hardcoded priority so there is no way to establish a usable precedence.

I would also vote for some form of deterministic application of identically named claims.

**Comment by lc-guy** [comment]
@rmartinc @pedroigor Are there any plans to implement this at the moment (or provide an alternative idiom to run it in a nocode way)?
