### ISSUE TITLE
passkeys: documentation

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23660]
### Description

Documentation for passkeys. Maybe also blog post can be good (not sure if after Keycloak 23 release or before).

**Comment by tnorimat** [comment]
@mposolda 
As the result of investigation written in https://github.com/keycloak/keycloak/issues/23658#issuecomment-1776248772,  I would like to add such the explanation to a manual (the server administration guide) and release note that the current keycloak can support Passkeys in some extent by using WebAuthn feature.
