### ISSUE TITLE
Default-Value in UI for krbPrincipalAttribute is error prone

### ISSUE THREAD

**Issue by pellmont** [keycloak/keycloak#23683]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Keycloak Admin-UI has a default-Value for krbPrincipalAttribute:
https://github.com/keycloak/keycloak/blob/57e51e9dd425d5a9da0064d6380b31ac497f9537/js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx#L209

In case your LDAP does not have an Attribute containing the Kerberos Principal-Name this field has to be empty to use the alternative way to lookup the ldap entry (just with the username without domain).

But in this case if you edit the storage provider in the UI,  the UI will autmatically fill in "userPrincipalName", despite the field should be empty. So this does not reflect the actual setting.
Even worse if you edit another attribute in the UI and save without removing it again. Then the user is altering the krbPrincipalAttribute (setting userPrincipalName) without even noticing the change.

Therefore I suggest to remove the default in this line.

### Version

22.0.3

### Expected behavior

Ldap UI reflects the actual setting as configured and no attribute will be altered without noticing.

### Actual behavior

UI does not show the actual configuration (in case of empty...) and overwrites the empty value with a (most likely wrong) default in case of saving.

### How to Reproduce?

1. Add an LDAP  User Federation with Kerberos integration.
2. Clear the field of krbPrincipalAttribute.
3. Save
4. Close the Input mask (e.g. Click in the lefthand menu to User Federation
5. Monitor network traffic in browser
6. Go back to the previously added User Federation
7. now you can see "userPrincipalName" (but in reality the value is not set - seen for example in HTTP response)
8. save
9. Close the input mask
10. Go back to the previously added User Federation again
11. now you can see "userPrincipalName" (and this time it is also set to "userPrincipalName" in the HTTP response)

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by agagancarczyk** [comment]
Thanks @pellmont for reporting this issue. I have investigated it further. It seems that it's an API issue. When an empty value is provided for `Kerberos Principal Attribute` field, the provider is created with an empty value, but when we retrieve the data from the server on viewing that created provider, the `Kerberos Principal Attribute` field comes with `userPrincipalName`. 

@mposolda could you please advise if this is an intended behaviour from the API perspective?

**Comment by rmartinc** [comment]
I think that this problem is the UI, the attribute [krbPrincipalAttribute](https://github.com/keycloak/keycloak/blob/23.0.3/js/apps/admin-ui/src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx#L203) has a default value with `userPrincipalName`. Just removing that line the value is saved empty. The backend does not add any value by default.

**Comment by edewit** [comment]
@agagancarczyk is right in case of active directory and rhds the sever sets a default https://github.com/keycloak/keycloak/blob/d10ccc72450e3bc8ae71cb0944ecd54f28261bd5/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPUtils.java#L388

**Comment by rmartinc** [comment]
@edewit Yes, the server adds this attribute on creation depending the ldap type. But it's just at creation time. IMHO it makes some sense because usually if you are using a AD it's going to be the `userPrincipalName`, but this issue is when you delete the value, that the UI always sets it again and to a fixed value. We can also remove the addition in the `onCreate` method if wanted, but I think it's less important.

**Comment by pellmont** [comment]
Thanks a lot!

**Comment by mtn88** [comment]
Thank you!
