### ISSUE TITLE
22.0.4 not included in release notes

### ISSUE THREAD

**Issue by promasu** [keycloak/keycloak#23698]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

docs

### Describe the bug

22.0.4 not included in release notes

### Version

22.0.4

### Expected behavior

22.0.4 is included in release notes

### Actual behavior

22.0.4 not included in release notes

### How to Reproduce?

Access https://www.keycloak.org/docs/latest/release_notes/index.html

**Comment by jonkoops** [comment]
This is not the first time this has happened. @stianst I think we should make an effort to make this kind of stuff automated in the release process to eliminate the human factor.

**Comment by mposolda** [comment]
@jonkoops One thing is, that there are not any changes explicitly added in the release notes for Keycloak 22.0.4. So looks that this is expected. There is missing file for 22.0.4 in https://github.com/keycloak/keycloak/tree/main/docs/documentation/release_notes/topics . Same case was with 22.0.1 as well. Those are micro releases containing just bugfixes and minor enhancements and in some cases, nothing, which worth to be explicitly documented. Hence I guess we can close this issue?

@promasu See here for the list of issues resolved in 22.0.4 https://www.keycloak.org/2023/10/keycloak-2204-released

**Comment by jonkoops** [comment]
Yeah you are right @mposolda, we don't add release notes for these. Just released 22.0.5 and it also doesn't include any release notes.

**Comment by mposolda** [comment]
@jonkoops Thanks, closing this as it is expected behaviour.
