### ISSUE TITLE
Join group screen does not respect or allow pagination with a filter

### ISSUE THREAD

**Issue by martinmeneval** [keycloak/keycloak#23709]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

We've noticed this happening since our upgrade to Keycloak 22(.0.3), but it could be older.
When clicking on "Join Groups" in the Admin UI, either within the user creation page or on the Groups tab of a user's page, and searching for a group, the results screen doesn't show the proper amount of results per page, doesn't report the proper amount of results, and pagination is greyed out. 

<img width="300" alt="Screenshot 2023-09-28 at 14 44 55" src="https://github.com/keycloak/keycloak/assets/34133448/ade3574c-5a73-4d9f-b8a9-09891d3f3def">
<img width="300" alt="Screenshot 2023-09-28 at 14 48 39" src="https://github.com/keycloak/keycloak/assets/34133448/d254f3f9-099a-40a0-b6e6-2ad975cbd2cf">  

Location of the two Join Groups buttons we're talking about.  

### Version

22.0.3, but tested on last night's nightly

### Expected behavior

When clicking Join groups and search for `child`, we see the first 10 matching results. We can go to the next page to see the next 10, and the next page to see the remaining 5.

### Actual behavior

When clicking Join groups and search for `Child`, we see the first 18 results, 15 of which are matching and the remaining 3 parents of the matching results (but not matching themselves). The page arrow buttons are greyed out and cannot be used. The page also reports 5 results being returned.
<img width="853" alt="image" src="https://github.com/keycloak/keycloak/assets/34133448/4c86cec7-9f24-4218-b523-10ab47234699">

Results shown when asking for 10 items. Note the page buttons being greyed out.

### How to Reproduce?

1. Spin-up an instance of Keycloak nightly
2. Create a new realm
3. Create the following group structure:
    - A
      - 'Child of A-`x`' for x=1 through 5 (5 subgroups in total)
    - B
      - 'Child of B-`x`' for x=1 through 5 (5 subgroups in total)
    - C ... E with 5 child subgroups each
    - F ... I with no subgroups
4. Create a user
5. Click Join groups on either the user creation page or the user's page - Groups tab.

### Anything else?

This is loosely related to https://github.com/keycloak/keycloak/issues/23582 and https://github.com/keycloak/keycloak/issues/23707, but I believe is its own issue. If necessary, I can also split this one into multiple issues like:
 - Join group screen does not respect pagination settings with a filter
 - Join group screen does not allow pagination with a filter
 - Join group screen shows non-matching results with a filter
 - Join group screen reports wrong number of results with a filter

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.

**Comment by jonkoops** [comment]
@MaxWinterstein if you can reproduce this issue under the latest version of Keycloak (25.x) then please file a new issue.
