### ISSUE TITLE
Attribute search does not work with federated users with ldap.

### ISSUE THREAD

**Issue by cesarbtt** [keycloak/keycloak#23701]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

If user federation is used in ldap the search for users by attributes does not work. It seems that the query is not even executed when you press the "Search" button after adding the search criteria.

If the federation is not configured, the results are displayed when the "Search" button is pressed.

### Version

22.0.4

### Expected behavior

The search should run and return results that match the search criteria. 

### Actual behavior

It seems that the query is not even executed when you press the "Search" button after adding the search criteria.

### How to Reproduce?

Activate user federation and try to search for specific attributes.

**Comment by cesarbtt** [comment]
What I observe is that, having enabled the trace level log of the org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager class, a search is executed every time I search by text using the "Default search" option. 

However, if I use the "Attribute search" option, no log output is produced when I press the "Search" button in the dialog where you enter the Attribute-Value pairs. The search filter is indeed activated under the "Attribute search" drop-down but the lack of log indicates that no search was executed when clicking on "Search".

**Comment by ssilvert** [comment]
@cesarbtt Can you tell if a request is sent to the server?  Please go to the developer tools in your browser and look at the Network tab.  If you see a request, please tell me what is the request and response?

I'm trying to determine if the problem is in the UI or on the server.

**Comment by cesarbtt** [comment]
Looking at the browser console it does not appear that any calls are being made when I click on "Search" for attributes. If I use the default search I can see a request to "https://id.coruna.gal/admin/realms/coruna/ui-ext/brute-force-user?briefRepresentation=true&first=0&max=101&q=&search=cesar" when I click on the arrow to the right of the search box.

**Comment by ssilvert** [comment]
@cesarbtt I just came back to this and realized how to reproduce.  I suspect that you have user profile disabled, right?

So the problem only occurs if there is user federation and user profile is disabled.

**Comment by cesarcoruna** [comment]
When you talk about "user profile" are you talking about the "--features=declarative-user-profile" option? If so, I don't use this option to start keycloak.

**Comment by MariiaAlekseichuk** [comment]
Hi, I can reproduce it too. 
In my case "--features=declarative-user-profile" is enabled. When User Federation is disabled search by attribute works perfectly fine. If User Federation is enabled search doesn't work and there are really no any requests in browser console.

**Comment by xsuchy09** [comment]
Same problem here. Enabled User Federation (extra plugin, User Federation from database). No request to the server is sent when filter by user attribute is used.

**Comment by g-tom** [comment]
>  no request is sent to the keycloak server

although, if you craft the request (e.g. through browser developer tools), it will give the expected result:

- Create realm "test" and enable User Profile
- Create attribute "test" in User Profile
- Add user "test" with attribute "test" set to "foo"
-  Add user "test2" with attribute "test" set to "bar"
- Run attribute search for test=foo

=> Finds user "test" and not "test2" as expected by requesting `/admin/realms/test/ui-ext/brute-force-user?briefRepresentation=true&first=0&max=11&q=test:foo`

Now add an LDAP-Provider and send the same request (e.g. do a default search for "*" and then edit the request in the developer tools and send again)
=> Search result again as expected

Tested with Keycloak 23.0.4.
