### ISSUE TITLE
Join group screen does not respect pagination settings without filters

### ISSUE THREAD

**Issue by martinmeneval** [keycloak/keycloak#23707]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

We've noticed this happening since our upgrade to Keycloak 22(.0.3), but it could be older.
When clicking on "Join Groups" in the Admin UI, either within the user creation page or on the Groups tab of a user's page, an incorrect number of items is returned. 

<img width="300" alt="Screenshot 2023-09-28 at 14 44 55" src="https://github.com/keycloak/keycloak/assets/34133448/ade3574c-5a73-4d9f-b8a9-09891d3f3def">
<img width="300" alt="Screenshot 2023-09-28 at 14 48 39" src="https://github.com/keycloak/keycloak/assets/34133448/d254f3f9-099a-40a0-b6e6-2ad975cbd2cf">  

Location of the two Join Groups buttons we're talking about.  

### Version

22.0.3, but tested on last night's nightly

### Expected behavior

When clicking Join groups, we see the first 10 groups

<img width="397" alt="image" src="https://github.com/keycloak/keycloak/assets/34133448/0c9b9e25-a33c-41f9-96ea-ebf59c6ebf4d">

Expected list of groups

### Actual behavior

When clicking Join groups, we see the first 3 groups
<img width="425" alt="image" src="https://github.com/keycloak/keycloak/assets/34133448/c82cd5db-a0a8-4195-b4f0-854c0711668b">

Actual list of groups shown, even though
<img width="425" alt="image" src="https://github.com/keycloak/keycloak/assets/34133448/4843479e-392d-4b34-be01-0f8dd9eb475c">

a 10-long page was requested

### How to Reproduce?

1. Spin-up an instance of Keycloak nightly
2. Create a new realm
3. Create the following group structure:
    - A
      - 'Child of A-`x`' for x=1 through 5 (5 subgroups in total)
    - B
      - 'Child of B-`x`' for x=1 through 5 (5 subgroups in total)
    - C ... E with 5 child subgroups each
    - F ... I with no subgroups
4. Create a user
5. Click Join groups on either the user creation page or the user's page - Groups tab.

### Anything else?

This is loosely related to https://github.com/keycloak/keycloak/issues/23582. I believe the reason why only three groups show instead of the existing 5 is that the request to `/groups` takes subgroups into account even though they're not shown in the UI. This is why to us, this is its own issue separate from the first one.

**Comment by ssilvert** [comment]
I've seen something similar that I reported in https://github.com/keycloak/keycloak/issues/23582

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
