### ISSUE TITLE
PKCE Workflow for getting RPT token requires clientSecret value

### ISSUE THREAD

**Issue by sridhar1495** [keycloak/keycloak#23703]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

For web application development using Angular Framework. For authentication we are using the PKCE workflow using the [angular-oauth2-oidc library](https://github.com/manfredsteyer/angular-oauth2-oidc). And we are having no issues until we work authentication only for the FrontEnd.
In the Fine-Grained Authorization Implementation in our application we want to configure the authorization in our front-end client that we created in the KeyCloak. For that which we tried to enable the Authorization option for that client, The option cannot be enabled directly. This requires us to enable the 'Client Authentication' first as follows,
![image](https://github.com/keycloak/keycloak/assets/75622411/7feb8364-c9af-4488-a3ef-fc96a7550b8f)

If we enable the 'Client Authentication' the access type is changed from 'public' to 'confidential', because of this change on the PKCE workflow on getting the token it is looking for 'clientSecret' which is not recommended for the web applications as part of security policy constraint.
This has been initiated as discussion as follows by June still there is no solution found. 
[Keycloak Authorisation with PKCE](https://github.com/keycloak/keycloak/discussions/21103) https://github.com/keycloak/keycloak/discussions/21103

The authorization we are looking for in our application is as per our application requirement. So, we are looking for Authorization as independent to Client Authentication option during the PKCE workflow. Since it is tightly coupled in the latest versions of KeyCloak, we are not able to achieve the mentioned functionality. 

### Version

22.0.3

### Expected behavior

The 'Authorization' option can be enabled separately regardless of 'Client Authentication'. 

### Actual behavior

The 'Authorization' option cannot be enabled without enabling the 'Client Authentication' option.

### How to Reproduce?

Try to enable the 'Authorization' option under the 'Capability Config' section in client without enbling the 'Client Authentication'.

1. Register the angular application as client in the KeyCloak with public access type.
2. In angular application using the angular-oauth2-oidc library get the access token using the PKCE workflow.
3. Enable the Authorization to get the permissions configured for the web application client, without giving the client secret.

**Comment by pedroigor** [comment]
@sridhar1495 Authorization services is mainly targeted to confidential clients and not SPAs (public client) so you can protect resources using a centralized authorization service.

For that to work, you will need to use a Backend for Frontend (BFF) pattern as per https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#name-backend-for-frontend-bff.
