### ISSUE TITLE
When using edge termination the operator should set the proxy-headers option

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#23716]
### Description

Currently when tlsSecret is not set if the operator creates an Ingress it is annotated as edge, but the proxy mode is left unset.  Moving this into the operator should remove the need to do it in our tests https://github.com/keycloak/keycloak/blob/e6e724d585ae6162aaf24aff1be72507c55f7871/operator/src/test/java/org/keycloak/operator/testsuite/integration/KeycloakIngressTest.java#L62

**Comment by shawkins** [comment]
Another related issue is that if you are using non-standard ports for keycloak and the operator creates an Ingress, it is not setting the hostname-port.

**Comment by vmuzikar** [comment]
> @vmuzikar the docs state "Set this option if the proxy uses a port other than the default HTTP and HTTPS ports." - does that refer to the keycloak server ports, or 80 and 443?

Yes.

**Comment by shawkins** [comment]
Yes meaning 80 and 443?

To clarify then when KC_PROXY is set, the requests are expected to use 80 and 443.  If not, they are expected to use the keycloak ports.  

In the operator's case we are defaulting KC_PROXY to passthrough - does that imply a proxy is always required, even if ingress is disabled - that there's no need to support a scenario where access to keycloak is via the Service and local to the namespace / kubernetes cluster?

**Comment by vmuzikar** [comment]
I'm starting to think if we should maybe postpone this until after we've made some final decision around revisiting the hostname config UX. :) Current behaviour is way too confusing as we can see here.

**Comment by shawkins** [comment]
> I'm starting to think if we should maybe postpone this 

It's simply covering what was already in the integration tests, but it can be postponed if you want.  My thought on this and the other explicit proxy support issue #14400 has been to avoid putting anything first-class around the proxy, especially until we have an agreement on the next state.  What I would expect regardless is that the primary cases of passthrough, edge, and reencrypt when using OpenShift default ingress should all work with a minimal amount of first-class CR fields.

> Current behaviour is way too confusing as we can see here.

For the most part I'm just trying to understand what the operator's current assumptions are - and whether those need to be made more explicit, updated, or even carried forward.

**Comment by shawkins** [comment]
Updated to the proxy-headers option.

**Comment by vmuzikar** [comment]
Not sure the Operator should be setting `proxy-headers` option automatically. Can we make any assumptions which of the X-Forwarded or Forwarded headers are accepted?

**Comment by shawkins** [comment]
> Can we make any assumptions which of the X-Forwarded or Forwarded headers are accepted?

I was thinking that this would be another case that checks for the ingress class - for openshift default it will nearly always (in append, the default, or replace mode) set fowarded and x-fowarded together - https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/networking/configuring-ingress#nw-using-ingress-forwarded_configuring-ingress https://github.com/openshift/router/blob/00f1690d49de86206bee1a54c9153747565b4186/images/router/haproxy/conf/haproxy-config.template#L614

However the behavior is more nuanced if never or ifnone modes are used. Since we'd have to check the ingress controller, and the per route annotation that could be set on the ingress, it would get messy pretty quickly trying to infer what the user wants.

**Comment by vmuzikar** [comment]
> it would get messy pretty quickly trying to infer what the user wants

+1

Are you then ok with closing this issue?

In any case, we need to add the `proxy-headers` option to the CR in #25179.

**Comment by shawkins** [comment]
> Are you then ok with closing this issue?

Sounds good.
