### ISSUE TITLE
Flag 'add to lightweight access token' on protocol mappers. Clients being able to decide if use lightweight access token or normal token

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23724]
### Description

Some of the use-cases, which we need to support is:
1) Some clients in the realm want lightweight access tokens
2) Some other clients in the same realm want "full" access token
3) Different deployments can have different requirements for lightweight access tokens. For instance some may want "email" claim in them when some others not etc.

Initially we discussed about having client policy executor, which will mark the "Add to access tokens" as OFF for the particular client, which is triggered for client policy (in https://github.com/keycloak/keycloak/issues/21184). Possible issue with this approach is, that it would allow to easily support both (1) and (2), but not (3). Some deployments may want some claims available even in "Lightweight access tokens". For instance "email". However that client policy executor described in https://github.com/keycloak/keycloak/issues/21184 doesn't possibly have enough flexibility (as it will just remove most of the claims from access token). So there is maybe not enough granularity to specify what exactly should be added to "Lightweight access token". Hence we discussed about alternative approach within Keycloak team like this:
- Add the flag "Add to lightweight access token" to the protocol mappers. This flag will be OFF by default for all existing protocol mappers (hence no migration needed, which will make it easier).
- Use client policy executor to define if particular client matching client policy condition will use lightweight access tokens. Alternative is to add the flag to client like "Use lightweight access tokens", but IMO client policy executor might have more flexibility than simple client switch as it will allow to use lightweight access token when requested by some "scope" parameter (as we have client policy condition) and hence it will allow same client to either use lightweight tokens or not according to some context (like for instance this "scope" parameter or other).

This means that at the time when access token is going to be issued, it will detect if it should use lightweight access token or "normal" access token. And based on that, it will check the flag for protocol mapper. I can think something like this in `AbstractOIDCProtocolMapper.transformAccessToken` (and possibly some other methods, which decide whether to add specific claim to access token):

```

public AccessToken transformAccessToken(AccessToken token, ProtocolMapperModel mappingModel, KeycloakSession session,
                                        UserSessionModel userSession, ClientSessionContext clientSessionCtx) {

    boolean shouldUseLightweightToken = ... // Detect somehow from client attribute or from KeycloakSession (in case we use client policies, we can possibly add some attribute to KeycloakSession by client policy executor?)

    boolean includeInAccessToken = shouldUseLightweightToken ?  OIDCAttributeMapperHelper.includeInLightweightAccessToken(mappingModel) : OIDCAttributeMapperHelper.includeInAccessToken(mappingModel);  

    if (!includeInAccessToken){
        return token;
    }

    setClaim(token, mappingModel, userSession, session, clientSessionCtx);
    return token;
}

```

**Comment by skabano** [comment]
@mposolda 
When "Add to lightweight access token" was marked as ON, I thought it would be better to get the claim with the IntrospectionTokenEndpoint.
The implementation of transformIntrospectionToken is as follows.
How about this?
```
public AccessToken transformIntrospectionToken(AccessToken token, ProtocolMapperModel mappingModel, KeycloakSession session,
                                            UserSessionModel userSession, ClientSessionContext clientSessionCtx) {
    boolean shouldUseLightweightToken = ... 

    boolean includeInIntrospectionToken = shouldUseLightweightToken ?  OIDCAttributeMapperHelper.includeInLightweightAccessToken(mappingModel) : OIDCAttributeMapperHelper.includeInIntrospection(mappingModel);

    if (!shouldUseLightweightToken){
        return token;
    }

    setClaim(token, mappingModel, userSession, session, clientSessionCtx);
    return token;
}
```
