### ISSUE TITLE
Client assertion used to broker has invalid ES256, ES384, ES512 signatures

### ISSUE THREAD

**Issue by justin-tay** [keycloak/keycloak#23721]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

When the identity provider is configured to use the ES256, ES384 or ES512 client assertion signature algorithm the assertion will be rejected due to an invalid signature.

Due to the use of a hardcoded `AsymmetricSignatureProvider` the signature being generated is DER encoded instead of the concatenated R and S values.

### Version

22.0.4

### Expected behavior

The signature for ES256, ES384 or ES512 should be the concatenated R and S values to be accepted by other compliant implementations.

### Actual behavior

The signature for ES256, ES384 or ES512 is DER encoded is and rejected by compliant implementations.

### How to Reproduce?

Configure the identity provider to use the ES256, ES384 or ES512 client assertion signature algorithm for authentication and attempt to authenticate.

**Comment by rmartinc** [comment]
Thanks @justin-tay! You are right. As explained in the PR this was not detected because the verifier has a workaround to explicitly allow it. There is a class already testing ES256 but because the workaround it works. :smile:
