### ISSUE TITLE
Access to v14 documentation

### ISSUE THREAD

**Issue by jdm-hexagon** [keycloak/keycloak#23728]
### Description

We are using v14 of Keycloak and need to access the documentation for that version.
How can that be accessed? All traces of it seems to have been removed.

**Comment by Wapax** [comment]
Hi @jdm-hexagon ,
You can take a look at the archive of the doc (https://github.com/keycloak/keycloak-documentation/tree/14.0.0], clone the project an run it on your own computer. Go to the chosen version tag.
I don't know if there are another way to get it but this can be an issue.
