### ISSUE TITLE
Admin Console doesn't show user when user attribute has annotation inputType

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#23740]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When user profile is activated and an attribute has annotation with key "inputType" (e.g. inputType=select) then the user view just shows error message "undefined has no properties".

![image](https://github.com/keycloak/keycloak/assets/789496/eaa924d1-d396-47c2-9367-e215e6a35f0d)

### Version

22.0.4

### Expected behavior

User view is rendered

### Actual behavior

Error is shown
Browser console shows at [react-dom.production.min.js:189:29](http://localhost:8080/resources/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.production.min.js)

`TypeError: undefined has no properties
    D SelectComponent.tsx:16
    React 9
    Ot EditUser.tsx:121
    useFetch useFetch.ts:33
    promise callback*useFetch/< useFetch.ts:31
    React 6
    Xr EditUser.tsx:81
    useFetch useFetch.ts:33
    promise callback*useFetch/< useFetch.ts:31
    React 3
    ct scheduler.production.min.js:13
    At scheduler.production.min.js:14
    EventHandlerNonNull* scheduler.production.min.js:14
    <anonymous> scheduler.production.min.js:19
react-dom.production.min.js:189:29
    React 12
    Ot EditUser.tsx:121
    useFetch useFetch.ts:33
    (Async: promise callback)
    useFetch useFetch.ts:31
    React 6
    Xr EditUser.tsx:81
    useFetch useFetch.ts:33
    (Async: promise callback)
    useFetch useFetch.ts:31
    React 3
    ct scheduler.production.min.js:13
    At scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.production.min.js:14
    <anonymous> scheduler.production.min.js:19
`

### How to Reproduce?

- Activate user profile
- Create a new attribute and set it as viewable and writable for Admin
- Add annotation inputType=select
- Open a user (e.g. admin)

### Anything else?

Could reproduce with 22.0.4 but not with latest nightly release.

**Comment by sschu** [comment]
@jonkoops @ssilvert I would rate this as critical (it is at least for us) and schedule to be fixed for 22.0.5. Do you agree?

**Comment by jbman** [comment]
In addition to this bug, we discovered that attributes are not send or retrieved by the Admin console user view in 22.0.4.
This occurs when an admin readable and writable attribute is defined without any annotation.

Also on nightly it wasn't possible to store a value without error in JS console. Do we need to report this as own bug? (Did not search if it already is.)

**Comment by antikalk** [comment]
I guess this is related to https://github.com/keycloak/keycloak/issues/23180 which is closed. I guess it is merged, but not part as 22.0.4.

**Comment by ssilvert** [comment]
#23180 should have been in 22.0.4. 

We are making some fixes in this area right now.  I'll give everyone a heads up to make sure the bugs reported here are addressed.

**Comment by jonkoops** [comment]
> #23180 should have been in 22.0.4.

This was back-ported, see https://github.com/keycloak/keycloak/issues/23180#issuecomment-1750221561. But it was never the whole fix.

**Comment by jonkoops** [comment]
> I would rate this as critical (it is at least for us) and schedule to be fixed for 22.0.5. Do you agree?

Yes, it most certainly is. And it will be fixed by #23537.
