### ISSUE TITLE
Expand truststore support

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#23742]
### Description

The keycloak cr should handle directly specifying truststores. A corresponding server feature will use those truststores for all scenarios - mTLS, LDAP, etc.

For users of keycloak via the operator this will simply management of truststores.

Points of discussion:
* This will largely by-pass the need for setting individual truststores under the assumption that there is no need to differentiate by usage.  Is this ok for an MVP, or does the trust need to be limited to the purpose (https vs spi vs java).
* It does not seem necessary to offer the ability to opt of of trusting the kubernetes ca certs
* MVP support for storeType could be fixed as PEM, meaning the password field would not be needed.
* What changes, if any, should be made in the server to accomodate this?
  * If the server is responsible for creating the merged keystore, how does this relate to the optimization process?
* How does this relate to keys (symetric and asymetric) needed for mutual auth?
  * The initial thought is to treat them separately.

Issues anticipated in this epic:
- Add any desired new functionality in server
- Update the CR and operator to the MVP state
- Capture follow-up work, which can include supporting other truststore types.

Also relates to 
- #16473 (should obviate)
- #9784 (should obviate) 
- #13300

### Discussion

https://github.com/keycloak/keycloak-community/pull/345

The discussion on the pr has more emphasis on:
- hot reload / #10654
- creating an spi - which would need to be easily usable by the operator
- trust at the realm level, which was not in the scope of the initial issues identified here

### Issues

- #24798
- #24148
- #10794 
- #9301
- #10654 - if in scope could influence what is responsible for creating the merged truststore
- #23729 (may not be in scope)

### Motivation

To provide users with the flexibility to address the known issues around truststores from both the keycloak CR and direct usage of the server.

**Comment by vmuzikar** [comment]
CC @keycloak/cloud-native

**Comment by vmuzikar** [comment]
@shawkins Thanks for the write-up.

From my perspective, it definitely makes sense to have a config option to specify a list of "global" truststores. Especially for the Operator which could leverage it for trusting K8s CA. But IMHO it also makes sense for other distributions, even bare metal. I.e. have it as a standard config option, i.e. CLI `--truststores list,of,truststores`, env vars, ... other config sources. Hence I think the merging function should be done on the server level.

I can see a couple of potential issues though.
* How to handle truststores that require some sort of credentials? How would the config options work for this with multiple truststores? And how to then the final merged truststore would be protected? I think we could be perhaps a little bit opinionated and support perhaps only PEM format to also avoid another config option for format.
* If we wanted to have it as standard config option (through smallrye) to align with other config options UX, we'd probably have to make it a build time option. We'd generate the final truststore during the build phase and if kc.sh|bat then detects its presence, it'd set the `-Djavax.net.ssl.trustStore` property. An issue might be with truststore rotation but I don't think we need to care too much about it as e.g. in K8s rolling restart is required in any case on Secret change. However, build time option wouldn't work at all with custom images and K8s CA...

**Comment by tsaarni** [comment]
Hi @vmuzikar!  
> in K8s rolling restart is required in any case on Secret change

Not sure if I understood this right, but I wanted to highlight that when using Secret volume mount for the pod, the files are updated automatically when Secrets are updated ([link](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod)). There is a small update delay, but rolling restart is not required from Kubernetes perspective.

**Comment by vmuzikar** [comment]
@tsaarni Good point! I confused it with env vars.

**Comment by shawkins** [comment]
Marking as completed as all outstanding tasks have been completed.
