### ISSUE TITLE
Automatically hot reload TLS certificates when https-certificate-file or https-certificate-key-file changes on disk

### ISSUE THREAD

**Issue by ecerulm** [keycloak/keycloak#23771]
### Description

The use case is Let's Encrypt certificates for the HTTPS url in a non-Kubernetes deployment.

The canonical way of generating the Let's Encrypt certficates  is to use "certbot" cli utility (official let's encrypt tool), to generate/renew the certificate and private key. 

When using `certbot`,  the  `https-certificate-file` and `https-certificate-key-file` configuration parameters of Keycloak will be set to the  paths to the certbot-generated files. Those files will be overwritten when the certificate is renewed during a `certbot renew` operation, but **keycloak will NOT reload them**. 

Since keycloak does not hot-reload  the TLS/SSL/HTTPS , then the current alternatives solution is to 

* restart keycloak entirely after a certificate renewal. The `certbot renew` allows for **deploy hooks**. In the deploy hook you can restart keycloak but that introduces some downtime every 60 days (which is the Let's Encrypt default renewal rate). 
* use a reverse proxy that does the Let's encrypt renewal (ACME)  like Caddy which will handle the HTTP termination itself and it's capable of performing the Let's Encrypt HTTP-01 and DNS-01 challenges itself (without certbot). This introduces yet another component.  

### Discussion

https://cloud-native.slack.com/archives/C056HC17KK9/p1696504180004809
https://github.com/keycloak/keycloak/discussions/10654

### Motivation

* I would simplify HTTPS deployment of keycloak specially for "short lived  certificates" like the ones issued by Let's encrypt (90 days expire time, certificates renewed usually every 60 days). 
* **Avoids downtime during the certification renewal process**. As it is today, there is downtime every 60 days , since keycloak needs to be restarted not requiring to restart keycloak to load the new certificate/ private key). 
* Avoids having to introduce a let's encrypt enabled reverse proxy like Caddy . 

### Details

Apparently is possible in quarkus to do hot reloading of TLS / SSL certificates with `HttpServerOptionsCustomizer` and some non trivial use of `javax.net.ssl.TrustManager`

https://github.com/Hakky54/java-tutorials/blob/9a7a5532610fc383a892e2eb6c6ed5a559aec451/instant-server-ssl-reloading-with-quarkus/src/main/java/nl/altindag/server/config/ServerConfig.java#L33-L75

My proposal  is to look into the above example:
* Use   Quarkus own `HttpServerOptionsCustomizer` and `HttpServerOptions` to set keycertoptions and trustoptions
* Get an implementation of  [`javax.net.ssl.KeyManager`](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/KeyManager.html?is-external=true) and [`java.net.ssl.TrustManager`](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/TrustManager.html?is-external=true)  that is updatables
* Start a periodic check for the files modification time, on change load appropriate data into the `KeyManager` and `TrustManager` instances that were passed to Quarkus's  `HttpServerOptions`

**Comment by vmuzikar** [comment]
Possibly, this is rather an RFE for Quarkus more than for Keycloak.

**Comment by Hakky54** [comment]
Hi 👋🏼  I am the author which posted an example of making hot reloadable certificate for quarkus on my java-tutorials page. I noticed this issue and it is not rocket science and I just wanted to share my knowledge here how I got it working as it might be useful if it is going to be implemented here. Quarkus uses vertx and vertx has some reloading mechanism introduced recently here: https://github.com/eclipse-vertx/vert.x/pull/4568

I am not sure how that works, so it might be also good to investigate that. However I have built a different solution to get it working which works for all java/scala/kotlin server and clients if they are configurable with a sslcontext, keymanager or trustmanager. I use a thread safe custom TrustManager and KeyManager which is basically a wrapper around the actual trustmanager/keymanager. See here for the custom TrustManager and KeyManager:

- [HotSwappableX509ExtendedTrustManager](https://github.com/Hakky54/sslcontext-kickstart/blob/517c6330c87b88bd1fc0bb755714229742d3b0e9/sslcontext-kickstart/src/main/java/nl/altindag/ssl/trustmanager/HotSwappableX509ExtendedTrustManager.java#L39)
- [HotSwappableX509ExtendedKeyManager](https://github.com/Hakky54/sslcontext-kickstart/blob/517c6330c87b88bd1fc0bb755714229742d3b0e9/sslcontext-kickstart/src/main/java/nl/altindag/ssl/keymanager/HotSwappableX509ExtendedKeyManager.java#L40)

The most basic and easiest usage would be:
```java
SSLFactory baseSslFactory = SSLFactory.builder()
          .withDummyIdentityMaterial()
          .withDummyTrustMaterial()
          .withSwappableIdentityMaterial()
          .withSwappableTrustMaterial()
          .build();

Runnable sslUpdater = () -> {
    SSLFactory updatedSslFactory = SSLFactory.builder()
          .withIdentityMaterial(Paths.get("/path/to/your/identity.jks"), "password".toCharArray())
          .withTrustMaterial(Paths.get("/path/to/your/truststore.jks"), "password".toCharArray())
          .build();
    
    SSLFactoryUtils.reload(baseSslFactory, updatedSslFactory);
};

// initial update of ssl material to replace the dummies
sslUpdater.run();
   
// update ssl material every hour    
Executors.newSingleThreadScheduledExecutor().scheduleAtFixedRate(sslUpdater, 1, 1, TimeUnit.HOURS);

options.setSsl(true)
          .setPort(8443)
          .setKeyCertOptions(KeyCertOptions.wrap(sslFactory.getKeyManager().orElseThrow()))
          .setTrustOptions(TrustOptions.wrap(sslFactory.getTrustManager().orElseThrow()));
```

The above snippet will create the hot swappable trustmanager and keymanager and therefor the underlying actual manager can be replaced at any given time. The link to the exact documentation for this server configuration can be found here: https://github.com/Hakky54/java-tutorials/blob/9a7a5532610fc383a892e2eb6c6ed5a559aec451/instant-server-ssl-reloading-with-quarkus/src/main/java/nl/altindag/server/config/ServerConfig.java#L34

I have made this reloading mechanism and other simplifications available in a separate maven library which can be found here: [sslcontext-kickstart](https://github.com/Hakky54/sslcontext-kickstart/) I hope this is a bit helpful.

**Comment by ahus1** [comment]
As discussed in #26524, when using Keycloak with the Keycloak Operator, the lastest version of the Operator will watch the secrets listed in the Keycloak CR, and will trigger a rolling restart. 

From https://www.keycloak.org/operator/advanced-configuration: 
> When a referenced Secret is modified, the Operator performs a rolling restart of the Keycloak Deployment to pick up the changes.

While the restart might induce some latencies in the requests, it might already solve most of the issue you see here. Please comment here if you see other trade offs.

**Comment by ecerulm** [comment]
> As discussed in https://github.com/keycloak/keycloak/issues/26524, when using Keycloak with the Keycloak Operator, the latest version of the Operator will watch the secrets listed in the Keycloak CR, and will trigger a rolling restart.

@ahus1 , I guess that's great if using Kubernetes, but supposed that this is a "regular" deployment on a regular Linux using certbot locally to generate the cert and private key.

**Comment by ecerulm** [comment]
Or do you mean that I just should restart keycloak  after a successful renewal? I mean , that is certainly possible with the certbot deploy hooks. That's what I meant when I said 

> Avoids downtime during the certification renewal process (not requiring to restart keycloak to load the new certificate/ private key).

So yes, that is possible and that's what I do now with certbot deploy hooks. But I was looking after having zero downtime.

**Comment by ecerulm** [comment]
I guess for the sake of newcomers reading this issue I should explain the usage of certbot+keycloak at  high level:
* certbot is the official cli to generate let's encrypt certificates
* certbot will generate new certificates and renew existing one, handling the HTTP-01 and/or DNS-01 challenges required to prove to Let's Encrypt that you own if fact own the domain name
* it generates a cert and private key (or overwrites the existing cert in the case of a renewal)
* It allows you to run scripts for each successful renewal, and from that script you could restart Keycloak.  


If you want to close this issue in favor of #26524 I'm fine with it, it seems that solving the HTTPS part alone is maybe not a complete solution

I guess, it depends if the HTTPS certificate renewal rate of 60 days (let's encrypt default)  is going to be different from the other certificates,key material, etc. In that case maybe it pays off to solve the HTTPS hot reloading , and restarting only when the other stuff changes (hopefully at a slower rate than every 60 days).

**Comment by ahus1** [comment]
With the upgrade to Quarkus 3.12+ in #31676 which is scheduled for KC26, Keycloak will upgrade to a version of Quarkus which supports the reloading of certificates for the HTTP server, see https://quarkus.io/guides/http-reference#reloading-the-certificates

Even if the previous comment suggests to close this issue in favor of a more general solution in the related issue, IMHO it would be great to pick up some low-hanging fruits from Quaruks by making it work for the http and management ports. 

If possible, I'd suggest to make reloading of certificates the default with an interval of say 1h, plus an option to change the interval or disable it. The docs say it is a no-op when the certs didn't change, so checking it every hour shouldn't have much of an impact on the performance.

@vmuzikar - may I ask you to add a KC26 milestone to this issue, at least tentatively?

**Comment by vmuzikar** [comment]
@ahus1 While the Cloud Native's backlog for 26 is a bit packed already, it seems really like a low-hanging fruit – basically just a single new config option. I put it to 26 milestone for now as optional.

CC @keycloak/cloud-native

**Comment by shawkins** [comment]
The scope here would be limited to the quarkus.http.ssl.certificate.files.reload-period, which we can utilize after the quarkus upgrade to 3.13. The only caveat will be that trust store certs configured via the new truststore support will not be reloaded as quarkus.http.ssl.certificate.files.reload-period is specific to the quarkus http configuration. 

A follow-on issue could try to bridge the support and add a repeated task for rebuilding the system truststore. We would also want to consider, like what is proposed in #26524 for broader support. At least for what can be configured via quarkus there is also now support for a TLS Registry, which can be configured for reloading, and referenced via places where trust / keys are needed. 

However not all of our usage of certs / truststores are via quarkus so we'd also have to look into / request TLS Registry support to programatically plug into LDAP, mail, etc.

**Comment by ahus1** [comment]
> The only caveat will be that trust store certs configured via the new truststore support will not be reloaded as quarkus.http.ssl.certificate.files.reload-period is specific to the quarkus http configuration.

Understood. I think it still adds value to those running letsencrypt, while others that run SPIRE need to wait a bit longer for a full solution.
