### ISSUE TITLE
22.0.4 Operator installed via OLM deploys Keycloak nightly version

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#23773]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

The Operator's CSV is [misconfigured](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/keycloak-operator/22.0.4/manifests/keycloak-operator.clusterserviceversion.yaml#L91) to deploy `quay.io/keycloak/keycloak:nightly`.

This affects only OLM installations.

Deployments with a custom Keycloak image are not affected.

### Version

22.0.4

### Expected behavior

Operator deploys `quay.io/keycloak/keycloak:22.0.4`.

### Actual behavior

Operator deploys `quay.io/keycloak/keycloak:nightly`.

### How to Reproduce?

Install Operator using OLM and deploy Keycloak without specifying a custom image.

### Anything else?

Originally reported by @dorianm in https://github.com/k8s-operatorhub/community-operators/issues/3323.

**Comment by vmuzikar** [comment]
This will be fixed with an Operator bundle re-release:
- https://github.com/k8s-operatorhub/community-operators/pull/3326
- https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3391

**Comment by vmuzikar** [comment]
Both PRs were merged, closing this.

**Comment by bo0ts** [comment]
@vmuzikar I've just updated on OpenShift via OLM thinking it would be fixed (because it was listed in the list of fixed bugs in the release), but this isn't the case.

```
kg pod keycloak-0 -o yaml | grep image:
    image: quay.io/keycloak/keycloak:nightly
    image: quay.io/keycloak/keycloak:nightly
```

**Comment by vmuzikar** [comment]
@bo0ts It probably takes some time for OLM to pickup the changes from the catalog.

**Comment by bo0ts** [comment]
@vmuzikar But there isn't a new version of the operator? How is this supposed to trigger an update on the consumer site?

I also tried to fix the image manually through the Keycloak custom resource but the `22.0.4` image could not start with an old error message that only `h2` databases are accepted:

`Datasource '<default>': URL format error; must be "jdbc:h2:{ {.|mem:}[name] | [file:]fileName | {tcp|ssl}:[//]server[:port][,server2[:port]]/name }[;key=value...]" but is "jdbc:...://..../keycloak" `

**Comment by vmuzikar** [comment]
This was not fixed through a new release but rather by patching existing CSV which is allowed and should be picked by OLM. However, there will be the 22.0.5 release soon.

The DB error seems to be because you are probably using the `image` field in the Keycloak CR which is [assumed](https://www.keycloak.org/operator/customizing-keycloak) to be an optimized image. DB option is build time that means building.

**Comment by dorianm** [comment]
@bo0ts 

> I also tried to fix the image manually through the Keycloak custom resource but the 22.0.4 image could not start with an old error message that only h2 databases are accepted:

I had the same problem when I tried to change the deployed image using `spec.image` on `Keycloak` CRD. I don't use Openshift, it may be a little bit different, but with in my case (AWS EKS), the workaround was to specify the `OPERATOR_KEYCLOAK_IMAGE` in the operator. This configuration works well :

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
   # [...]
spec:
  # [...]
  config:
    env:
    - name: OPERATOR_KEYCLOAK_IMAGE
      value: quay.io/keycloak/keycloak:22.0.4
```

**Comment by bo0ts** [comment]
@dorianm Yeah, I fixed that by overwriting the CSV (which contains the operator deployment definition when using OLM).

I'm still not sure the @vmuzikar change is actually ever going to be picked up by the catalog and it is surely not working for installations that are already upgraded to 22.0.4.
