### ISSUE TITLE
User can't be updated in admin console when user profile is used

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#23774]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When user profile is enabled and an attribute defined which is visible for the Admin, isn't updated when save is clicked.

### Version

22.0.4 and nightly

### Expected behavior

The user can be updated e.g. name, firstname or the value of the declared attribute can be changed and saved.

### Actual behavior

Error in browser JS console
`
Uncaught (in promise) TypeError: e.responseData is undefined
    ea UserProfileFields.tsx:29
    z EditUser.tsx:132
    re index.esm.mjs:2147
    React 16
    <anonymous> main.tsx:20
`

### How to Reproduce?

- Activate user profile
- Create a new attribute and set it as viewable for Admin
- Open a user (e.g. admin)
- Enter a Last Name.
- Click Save

<img src="https://github.com/keycloak/keycloak/assets/789496/96793b52-7310-47db-832d-6570015ca976" width=60%>

**Comment by antikalk** [comment]
Related to https://github.com/keycloak/keycloak/issues/23434
