### ISSUE TITLE
'Show version information' is not working

### ISSUE THREAD

**Issue by mamccorm** [keycloak/keycloak#23783]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/cli

### Describe the bug

The CLI does not appear to be returning the version, when the associated arg is invoked. Quoting supported args:

```
docker run quay.io/keycloak/keycloak:latest --help
Options:
-V, --version        Show version information
```

Whenever running `docker run quay.io/keycloak/keycloak:latest --version` or 'docker run quay.io/keycloak/keycloak:latest -V` an exception is thrown.

Details below.

### Version

22.0.4

### Expected behavior

Container should output version information and exit gracefully

### Actual behavior

```bash
docker run quay.io/keycloak/keycloak:latest --version
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2023-10-06 11:09:42,128 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NullPointerException: Cannot invoke "picocli.CommandLine.getCommand()" because "cmdCommand" is null
	at org.keycloak.quarkus.runtime.cli.Picocli.hasConfigChanges(Picocli.java:260)
	at org.keycloak.quarkus.runtime.cli.Picocli.requiresReAugmentation(Picocli.java:141)
	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:126)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:95)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
	... 6 more
```

### How to Reproduce?

docker run quay.io/keycloak/keycloak:latest --version

**Comment by toficzak** [comment]
Can I try to solve this?

**Comment by shawkins** [comment]
This null check will be needed - https://github.com/keycloak/keycloak/pull/23797/files#diff-5e7526010bd1f3d3c2735d6b5d600aaf3457a83eb1699ef7e10c91e2257ae6d2R145 but I haven't tested if it fully addresses this issue.  That can be pulled out of the other pr as a separate one if needed.

**Comment by shawkins** [comment]
Confirmed that the null check was all that was needed.  Opened as separate pr.

**Comment by utilisateuryou** [comment]
i need your help please
keycloak-22.0.4/bin# ./kc.sh start-server
![image](https://github.com/keycloak/keycloak/assets/152034555/8c8edc95-4098-492b-bf89-bd0c2020fb90)

**Comment by utilisateuryou** [comment]
> ### Before reporting an issue
> * [x]  I have searched existing issues
> * [x]  I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)
> 
> ### Area
> admin/cli
> 
> ### Describe the bug
> The CLI does not appear to be returning the version, when the associated arg is invoked. Quoting supported args:
> 
> ```
> docker run quay.io/keycloak/keycloak:latest --help
> Options:
> -V, --version        Show version information
> ```
> 
> Whenever running `docker run quay.io/keycloak/keycloak:latest --version` or 'docker run quay.io/keycloak/keycloak:latest -V` an exception is thrown.
> 
> Details below.
> 
> ### Version
> 22.0.4
> 
> ### Expected behavior
> Container should output version information and exit gracefully
> 
> ### Actual behavior
> ```shell
> docker run quay.io/keycloak/keycloak:latest --version
> The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
> 2023-10-06 11:09:42,128 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider
> 
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
> 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
> Caused by: java.lang.NullPointerException: Cannot invoke "picocli.CommandLine.getCommand()" because "cmdCommand" is null
> 	at org.keycloak.quarkus.runtime.cli.Picocli.hasConfigChanges(Picocli.java:260)
> 	at org.keycloak.quarkus.runtime.cli.Picocli.requiresReAugmentation(Picocli.java:141)
> 	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:126)
> 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:95)
> 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
> 	... 6 more
> ```
> 
> ### How to Reproduce?
> docker run quay.io/keycloak/keycloak:latest --version
> 
> ### Anything else?
> _No response_

hi, do you have a solution ? 
I have same issue
