### ISSUE TITLE
Can not create attribute group before setting/removing an annotation

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#23789]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When creating an attribute group, there is a single empty annotation in the `Annotations` section.

If you don't remove this "default" empty annotation you can create a group.

Annotations should not be mandatory when creating groups, similar to when you are creating attributes.

### Version

22.0.4

### Expected behavior

Create a group without being forced to add an annotation but just the group name.

### Actual behavior

Forced to delete the empty annotation or set values to it.

### How to Reproduce?

* Create a attribute group
* Set a name
* Save

**Comment by jonkoops** [comment]
@pedroigor does this deserve a backport?

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
