### ISSUE TITLE
Made adapters compatible with KC23 "iss" parameter change

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#23794]
Part of the changes for #20621 will need to be backported.The purpose of this backport is to allow the adapters to recognize the "iss" parameter so clients can better prepare for the official change in KC23.

_Issue created from #23583_

**Comment by mposolda** [comment]
Closing as this change is already in Keycloak main (Related PR is https://github.com/keycloak/keycloak/pull/20621 ). And needs to be addressed just in `release/22.0` branch where it was already merged in the PR https://github.com/keycloak/keycloak/pull/23583
