### ISSUE TITLE
H2 Database should be opt-in and well-documented

### ISSUE THREAD

**Issue by danetrata** [keycloak/keycloak#23805]
### Description

Keycloak includes an H2 in-memory database for development purposes. The Keycloak image with either no configurations or improperly configured will default to the H2 database. There is little documentation on the behavior of Keycloak on H2, aside from the cryptic warning not to use the default configuration in production.

This becomes problematic as a scan of open ports on the Keycloak image image will reveal constantly opened ports in the 30000+ range. This behavior exists in version `quay.io/keycloak/keycloak:18.0.2` and `quay.io/keycloak/keycloak:22.0.1`.  

The following is naive scan from a security pipeline:
```
73[✓] Discovered port 41801: open
74[•] Service: unknown (confidence level 3/10)
75[•] Server type: unknown (version unknown)
76[✓] 0 web service(s) identified for scanning
77[!] 1 warning(s) for port 41801
78 ‣  Port is NOT exposed by Dockerfile but has state: open
```
As you can imagine, this raised major red flags, and it was with a lot of effort that we were able to track down the source. Searching the usual channels and asking in Slack leads to nowhere about this behavior. 

In the end, the documentation about using H2 in Keycloak is all over the place. The main takeaway we've gotten is that H2 is unsupported and is only meant for dev purposes. It is not clear this the default unless the container is restarted and the in-memory database is wiped, and it is correctly deduced that H2 was in use.

So as a part of docs, there is an need for detailed and consolidated documentation that outlines the behavior of Keycloak when employing the H2 in-memory database. This should include specifics on port usage, potential security implications, and the consequences of using H2 in a production environment. If H2 is truly intended solely for development and unsupported in production, it should not be the default behavior. Users should be explicitly informed about this default setting and the risks associated with it, ensuring they are not inadvertently deploying insecure configurations.

**Comment by vmuzikar** [comment]
@danetrata Thanks for the report.

I see this rather as a config enhancement than docs enhancement. If we're going with the "secure by default" principles, we should not probably default to H2. We might want to make the `--db` config option mandatory (with no default) in prod profile (`start`) while keeping H2 in dev profile (`start-dev`). WDYT @keycloak/store @keycloak/cloud-native?

**Comment by sguilhen** [comment]
Sounds reasonable to me, @vmuzikar

**Comment by stianst** [comment]
@vmuzikar +1 to requiring `--db` in prod profile, I would also consider logging a warning when `h2` is used in prod profile.

**Comment by shawkins** [comment]
This will be more straight-forward after #32725 because we use mapFrom profile with a specific transformer.

**Comment by ahus1** [comment]
Since #26042 and KC 25.0.2, Keycloak will no longer open the extra port for H2. Still, all the thoughts about having H2 opt-in especially in production still apply.

**Comment by giner** [comment]
@danetrata H2 in Keycloak is not listening on all interfaces since 25.0.2, here is the relevant commit https://github.com/keycloak/keycloak/commit/3b3ca601bb759b31f88e96c22388318df071e27a
