### ISSUE TITLE
PolicyEnforcerConfig is loaded for each request

### ISSUE THREAD

**Issue by xvdb** [keycloak/keycloak#23827]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

The synchronizedMap is useless in org.keycloak.adapters.authorization.integration.jakarta.ServletPolicyEnforcerFilter 

the PolicyEnforcerConfig is loaded for each request... for nothing

### Version

22

### Expected behavior

performance

### Actual behavior

this causes more than 5 requests on keycloack authorization services per request !

### How to Reproduce?

you can reproduce the issue with the official quickstart projet and a simple gatling load test
https://github.com/keycloak/keycloak-quickstarts/tree/latest/spring/rest-authz-resource-server

**Comment by rmartinc** [comment]
@xvdb What happens if you modify the quickstart and the same config is always resolved?

Something like:

```diff
diff --git a/spring/rest-authz-resource-server/src/main/java/org/keycloak/quickstart/OAuth2ResourceServerSecurityConfiguration.java b/spring/rest-authz-resource-server/src/main/java/org/keycloak/quickstart/OAuth2ResourceServerSecurityConfiguration.java
index 8e3f0d1b..538e006f 100644
--- a/spring/rest-authz-resource-server/src/main/java/org/keycloak/quickstart/OAuth2ResourceServerSecurityConfiguration.java
+++ b/spring/rest-authz-resource-server/src/main/java/org/keycloak/quickstart/OAuth2ResourceServerSecurityConfiguration.java
@@ -57,17 +57,19 @@ public class OAuth2ResourceServerSecurityConfiguration {
        }
 
        private ServletPolicyEnforcerFilter createPolicyEnforcerFilter() {
+                try {
+                        PolicyEnforcerConfig cfg = JsonSerialization.readValue(getClass().getResourceAsStream("/policy-enforcer.json"), PolicyEnforcerConfig.class);
                        return new ServletPolicyEnforcerFilter(new ConfigurationResolver() {
                                @Override
                                public PolicyEnforcerConfig resolve(HttpRequest request) {
-                               try {
-                                       return JsonSerialization.readValue(getClass().getResourceAsStream("/policy-enforcer.json"), PolicyEnforcerConfig.class);
+                                        return cfg;
+                                }
+                        });
                } catch (IOException e) {
                        throw new RuntimeException(e);
                }
        }
-               });
-       }
 
        @Bean
        JwtDecoder jwtDecoder() {
```

Maybe the problem is more in the quickstart than in the server.

**Comment by xvdb** [comment]
I solved the problem, I proposed a PR.
it's neither in the quickstart nor in the server, it's at the client level

**Comment by rmartinc** [comment]
I saw your commit, but my feeling is that the `resolve` method is used to allow to load different configurations depending the http request. With your change passing `null` we are modifying that behavior (the same configuration is always used, no matter the request). I think the problem here is that the quickstart is always loading a different config, and therefore a new enforcer is always created. With my change in the quickstart I think that issue is resolved.

**Comment by xvdb** [comment]
you must resolve the client lib before the quickstart.
If you don't like null, you need to review the other classes that extend this one

**Comment by rmartinc** [comment]
But is there a problem doing the change in the quickstart? Doesn't it solve the issue?

**Comment by pedroigor** [comment]
@xvdb I agree with @rmartinc and we should actually change https://github.com/keycloak/keycloak-quickstarts/blob/latest/spring/rest-authz-resource-server/src/main/java/org/keycloak/quickstart/OAuth2ResourceServerSecurityConfiguration.java#L64 to avoid parsing the config every time.

The code works like that because of multi-tenancy and the possibility of enabling different resource servers from a single application (as we used to do when embedded into our adapters).

**Comment by pedroigor** [comment]
Created https://github.com/keycloak/keycloak-quickstarts/issues/497.

**Comment by xvdb** [comment]
closed ?
ServletPolicyEnforcerFilter is not in the quickstart ...
people who will use this class without knowing the quickstart will hit a wall :(

**Comment by rmartinc** [comment]
@xvdb Any app can do what we are going to do in the quickstart, if you return always the same config you always get the same enforcer. It's the correct way of using the filter. As commented in the PR we can protect the `ServletPolicyEnforcerFilter` to limit the map size. You can file an issue and send PR for that.

**Comment by xvdb** [comment]
ha I thought that the configuration file loading method was the same in fremework. I understand better
I carried out a load test and I confirm that the quickstart fix resolves the performance problem
