### ISSUE TITLE
Account console v2 doesn't support automatic logout

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23833]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Scenario like:

- Login to account console https://localhost:8443/admin/master/console/ in tab1. I did not enabled any preview features etc, so assume it is account console V2.
- Open account console also in another browser tab (tab2). I should be logged automatically due the SSO and it works this way.
- Click "Sign out" in tab2. I am logged-out, which is OK
- Go to tab1. I am still logged-in here, which is not OK. When I click to some link (For instance tab "Personal info" on the left), I am redirected to login screen as SSO session was already removed, which is OK

### Version

22.0.4 (or latest Keycloak main)

### Expected behavior

Automatic logout in tab1 due the session iframe after user logged-out in tab2.

### Actual behavior

Not being logged-out automatically in tab1 until I click on some link

### How to Reproduce?

See above

### Anything else?

Not 100% sure if this can be strictly considered a bug or missing functionality (feature). Also it is not a regression since old account console (Account console V1) was not based on javascript and automatic logout did not work here. So feel free to convert to "Feature" or "Enhancement".

**Comment by mposolda** [comment]
For the reference: The same issue for new admin console https://github.com/keycloak/keycloak/issues/23832

**Comment by ssilvert** [comment]
@jonkoops I think we should only fix this for V3.

**Comment by edewit** [comment]
fixed with #28723

**Comment by ssilvert** [comment]
@edewit Assigned to you for backport since you were the one who actually fixed it.
