### ISSUE TITLE
Users page with LDAP User Storage Provider Cannot read properties of undefined 

### ISSUE THREAD

**Issue by slominskir** [keycloak/keycloak#23841]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

If you configure an LDAP User Storage Provider (User Federation) and then navigate to the Admin UI Users tab you'll get a JavaScript error: `Cannot read properties of undefined `.

### Version

22.0.4

### Expected behavior

The Users page should load without error.

### Actual behavior

The page has an error as seen in the attached screenshot.

![Screenshot](https://github.com/keycloak/keycloak/assets/2642119/f1abc833-62c1-446b-9532-76bef392e462)

### How to Reproduce?

A reproducer GitHub Docker Compose project can be used to recreate:

```
git clone https://github.com/slominskir/keycloak_ldap
cd keycloak_ldap
docker compose up
```

1. Wait for the LDAP and Keycloak containers to fully start up.  
2. Navigate your web browser to the admin UI at http://localhost:8080
3. Login with username `admin` and password `admin`
4. Select the "test-realm" realm
5. Click the Users tab to view the Users page.
6. Observe the JavaScript error

### Anything else?

See: https://github.com/keycloak/keycloak/discussions/22769#discussioncomment-7231745

**Comment by edewit** [comment]
```bash
Cloning into 'keycloak_ldap'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 44 (delta 14), reused 27 (delta 7), pack-reused 0
Receiving objects: 100% (44/44), 8.18 KiB | 837.00 KiB/s, done.
Resolving deltas: 100% (14/14), done.
>>>> Executing external compose provider "/home/edewit/bin/docker-compose". Please refer to the documentation for details. <<<<

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'keycloak'
Error: executing /home/edewit/bin/docker-compose up: exit status 1

```

**Comment by slominskir** [comment]
I got a notification that Erik Jan de Wit was having issues running the Docker Compose project to recreate this issue.  I'm not seeing the message here so maybe it got deleted?  Anyways,  make sure you use a modern Compose app from Docker (Version 2 series).   I think there are many old versions (Version 1 series) that don't support `extends` and other features of Compose resulting in errors.   The command should be:

`docker compose` (newer)
vs
`docker-compose` (older)

See:
- https://docs.docker.com/compose/history/ 
- https://github.com/docker/compose

**Comment by jonkoops** [comment]
I believe this may have been fixed by #24460, which will be released in Keycloak 23. Please try out the [nightly version] and let us know if this issue persists.

**Comment by jonkoops** [comment]
Closing this issue, as it is likely already resolved. If the issue persists I will re-open it.

**Comment by slominskir** [comment]
This does not appear to be resolved.  I updated the docker-compose.yml to use `keycloak:nightly` and re-ran test case and I still see the error, though the line it fails on is now line 10 not 189:

![image](https://github.com/keycloak/keycloak/assets/2642119/9f231c9e-4883-4017-b319-01e3edc1269f)

**Comment by slominskir** [comment]
Chrome re-formats the minimized js to show the error specifically appears to be:

<img width="254" alt="image" src="https://github.com/keycloak/keycloak/assets/2642119/091deed5-d57e-453a-a12a-09e5a825093e">

**Comment by slominskir** [comment]
@edewit Thanks, I can confirm your workaround works.  Following your lead, a similar one is to add `config.enabled=true` to the `kcadm.sh` command that creates the LDAP config:  https://github.com/slominskir/keycloak_ldap/commit/e7e7c1213b2dbad8cc946f837a80d3dbb93fc3d8

It appears the enabled flag is a tri-state boolean (true, false, and null) with null meaning true apparently.  In JavaScript maybe quad-state if adding `undefined`.   I'm not familiar with the code, but it may be possible to simplify this internally to an actual boolean to avoid problems such as this.   Having to guard against null everywhere is not optimal.   Null is Tony Hoare's Billion Dollar Mistake.

**Comment by edewit** [comment]
Yes, I did a PR already to fix this
