### ISSUE TITLE
Use upstream Quarkus functionality for non-blocking probes

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#23854]
### Description

In #22109 a workaround was added to Keyclaok to support a non-block readiness and liveness probe. 

In upstream Quarkus, issue https://github.com/quarkusio/quarkus/issues/35099 is open to support non-blocking probes natively in Quarkus. This issue tracks the progress there. 

This also tracks https://github.com/eclipse-vertx/vert.x/issues/4900 and https://github.com/quarkusio/quarkus/issues/36419 where workarounds have been created in #23919. 

### Motivation

Non-Blocking probes are essential to prevent the probes to fail under high load when blocking requests are queued.

### Details

See #22109 and #22112 for the discussion.

**Comment by sschu** [comment]
Do you expect the Quarkus guys to work on this after your PR was closed?

**Comment by ahus1** [comment]
@vmuzikar and the Quarkus and SmallRype health team are in contact to get this eventually implemented. At the same time there is no publicly visible progress except the one upstream issue, yet.

**Comment by vmuzikar** [comment]
This was implemented at the Quarkus side and now is waiting for a backport of https://github.com/quarkusio/quarkus/pull/36434 to 3.2.

Moving this to the Keycloak 24 milestone as it is more realistic.

**Comment by ahus1** [comment]
New PR on the way to fix it correctly: https://github.com/quarkusio/quarkus/pull/37352
