### ISSUE TITLE
Make a clear note in upgrading guide to reverse proxy changes required

### ISSUE THREAD

**Issue by Schaka** [keycloak/keycloak#23868]
### Description

As of 22.0.0, as per the upgrade guide, the reverse proxy mode ignores common reverse proxy headers.
While I like the idea of having the available choices, it wasn't quite clear to me from documentation that the default mode when not actively setting one is passthrough.

It took me a long time to find the relevant portion of the docs and to realize what  exactly broke functionality when upgrading.
I think a small note mentioning that the default is passthrough and to retain functionality as per 20.x or 21.x, you should switch to either edge or reencrypt would be very helpful.

Hopefully this can be considered.

**Comment by vmuzikar** [comment]
@Schaka Thanks for the report! Please correct me if I'm wrong but I believe this was covered in the release notes here: https://github.com/keycloak/keycloak/blob/4bcc5df8585257c2b6282d421f142e27b3a38443/docs/documentation/upgrading/topics/keycloak/changes-22_0_0.adoc?plain=1#L175-L181

**Comment by Schaka** [comment]
I had seen this in the release notes:

> Passthrough proxy mode changes
> Installations which use Keycloak’s --proxy configuration setting with mode passthrough should review the documentation as the behavior of this mode has changed.

I did find what you refer to in the upgrading guide. I still wish there was a note like:
"[...] the **default mode**, passthrough, has its behavior changed. If you don't actively set a proxy mode [...]".
Granted, I couldn't think of a way to word things better and make it more clear that someone may be affected by this unknowingly.

I know this happened to me and it took a while to realize that the server was running in passthrough mode, which is why none of the URLs were using https as a result of headers not being interpreted anymore. 

I was hoping maybe a more clear note would help someone else recognize this faster.

**Comment by vmuzikar** [comment]
@Schaka The default for proxy is not `passthrough` but `none`, please see the [docs](https://www.keycloak.org/server/all-config#category-proxy). Only Operator [uses](https://github.com/keycloak/keycloak/blob/4bcc5df8585257c2b6282d421f142e27b3a38443/operator/src/main/java/org/keycloak/operator/Constants.java#L54) `passthrough` by default. Is that your case?

**Comment by Schaka** [comment]
It would appear that the defaults are part of the helm chart and not keycloak itself then.

**Comment by vmuzikar** [comment]
@Schaka Thanks for the clarification. As we do not maintain official Helm charts, I'm going to close this issue. Feel free to reopen/comment if you think otherwise.
