### ISSUE TITLE
[Declarative User Profile] User details page is not shown properly

### ISSUE THREAD

**Issue by burakkoken** [keycloak/keycloak#23864]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

If we enable the feature `declarative-user-profile` and add a custom attribute with the `options` validator, the user details page is not rendered properly. we got an error like this:

![image](https://github.com/keycloak/keycloak/assets/5354910/49fff474-fe60-459d-80d9-28ad324db877)

### Version

22.0.4

### Expected behavior

User details page should be rendered properly

### Actual behavior

User details page is not rendered properly because of the custom attribute with `options` validator.

### How to Reproduce?

1) Create an attribute with `options` validator

![image](https://github.com/keycloak/keycloak/assets/5354910/5cb59aae-a852-402d-8b56-d7d3bfb0252e)

2) Go to User page and create a dummy user
3) After creation of the user, click on the user name for the user details.
![image](https://github.com/keycloak/keycloak/assets/5354910/8ba43de5-61bc-43cd-a97d-bb77912f28f0)

4) You should see an error like this:
![image](https://github.com/keycloak/keycloak/assets/5354910/395158dc-a7d2-4d1d-9ea7-695bf294c47d)

**Comment by jonkoops** [comment]
@burakkoken have you tested this in this in the nightly like the issue template mentions? I am quite sure this has already been fixed.

**Comment by burakkoken** [comment]
Yes, it is fixed with the latest nightly release which was created 6 hours ago

**Comment by jonkoops** [comment]
Thanks for checking! This should be released in the next patch release of Keycloak (22.0.5).
