### ISSUE TITLE
[Declarative User Profile] Custom attributes are not shown on user creation page

### ISSUE THREAD

**Issue by burakkoken** [keycloak/keycloak#23865]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

If we enable the feature `declarative-user-profile` and add a custom attribute, it is not shown on user creation page even if it is required for both user and admin so I'm not able to create an user. It is working properly with release 21.1.2 version. 

![image](https://github.com/keycloak/keycloak/assets/5354910/ac9fb0cb-d7eb-4ca4-979e-ba6584a645ce)

### Version

22.0.4

### Expected behavior

the added attributes should be shown on user creation page so they can be filled.

### Actual behavior

the added attributes are not shown on user creation page so I'm not able to edit them and I got an error saying `Please speficy the attribute`

### How to Reproduce?

1) Create a required attribute for both admin and user

![image](https://github.com/keycloak/keycloak/assets/5354910/8929004f-b085-4bfc-9b06-393633910bff)

2) Go to user page and click on `Add User` button.

3) the added attribute is not shown on user creation page as follows

![image](https://github.com/keycloak/keycloak/assets/5354910/28753d12-faf2-4ec8-a294-30cb4091c8d6)

4) Click on save button and you should see an error saying `Please specify the attribute`
![image](https://github.com/keycloak/keycloak/assets/5354910/ac9fb0cb-d7eb-4ca4-979e-ba6584a645ce)

**Comment by jonkoops** [comment]
@burakkoken did you test this in the nightly version? I am pretty sure that this should have been fixed in #23537.

**Comment by jonkoops** [comment]
Thanks for verifying this! You can expect this fix to land in the next patch release of Keycloak (22.0.5).
