### ISSUE TITLE
User profile configuration scoped to user-federation provider

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#23878]
### Typical use-case

- I have read-only LDAP server in Keycloak
- Users coming from such LDAP server should not be able to update their attributes (firstName, lastName or email or any other)
- It will be ideal if fields are shown to users as read-only when user is updating his profile in Account console or by "Update profile" required action form. Same applies for administrators as they also should not be able to update such users (Admin console, Admin REST API).
- At the same time, my realm may contain users coming from the Keycloak DB and/or from other user storage provider (for instance from some different LDAP server, which is writable by Keycloak)
- So I want attributes (firstName, lastname, email etc) to be read-only coming from the read-only LDAP. But writable for other providers

### Other notes and questions

- Can we have user-profile configuration, which are "scoped" to particular user-storage provider? For instance attribute `firstName` will have configuration scoped to user-storage provider `my-read-only-ldap`, which will mark it as "read only". There would be also configuration for `firstName` attribute in realm level. Users NOT coming from read-only LDAP provider will have different configuration of `firstName` marked as writable.  Example (for illustration purposes):
```

{
  "name": "firstName",
  "displayName": "${firstName}",
  "permissions": {
    "view": ["admin", "user"],
    "edit": ["admin", "user"]
  },
  "validators": ...

  // This specify that for users coming from read-only LDAP, attribute is read-only. Admin or users cannot edit it
  "config-overrides": [
    "type": "user-storage-provider",
    "name": "my-read-only-ldap-provider-name",
    "config":  {
      "permissions": {
        "view": ["admin", "user"],
        "edit": []
      },
    }
  ]
}
```

Type can refer to user-storage-provider, group, identity-provider etc. For instance `group` to specify that users from group `xy` are read-only etc...

- Can we somehow trigger "auto-update" of user profile when some user-storage provider is created and/or updated? For instance when someone creates read-only LDAP provider, it can be nice if user-storage provider attributes are automatically updated to reflect this. This can possibly also take LDAP mappers into consideration (EG. When I create LDAP mapper for attribute "birthdate", user-profile might automatically create user-storage provider configuration for the attribute "birthdate". But this is to be discussed how exactly this should work...

- Do we want to support the use-case when users coming from user-storage provider `abc` should not be managed and validated by user profile at all?

**Comment by pedroigor** [comment]
Yeah, that would be nice.

I think we don't necessarily think of a configuration for that because we could infer the write/read settings based on the instance of the `UserModel` being handled by the provider.

For instance, we could resolve the provider from where a `UserModel` instance is coming from and based on the provider settings, change how we build the user profile metadata (the metadata consumed by the different contexts like account, update profile, admin api, etc).

**Comment by mposolda** [comment]
So do you think that user-storage provider should have some way of "decorate" the user-profile somehow automatically? So for instance the fact that `firstName` attribute should be read-only for users from read-only LDAP will be provided automatically by LDAP provider implementation without being configured in the user-profile configuration?

This might be alternative approach and probably easier to implement. The small disadvantage is that administrator might not see all the user-profile configuration and hence may not be 100% sure what would be the actual behaviour. But maybe that is fine, not sure...

**Comment by pedroigor** [comment]
For the admin, it would be kinda the same. However, we would need the Attribute UI page to also fetch the metadata (already used in other UIs) to properly render the fields.

**Comment by mposolda** [comment]
Pedro's branch with the prototype we discussed: https://github.com/pedroigor/keycloak/tree/issue-23878 . I can continue from here.
