### ISSUE TITLE
How do I automatically import user groups when using Identity Brokering

### ISSUE THREAD

**Issue by edtshuma** [keycloak/keycloak#23870]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

identity-brokering

### Describe the bug

I am making some changes on an existing SAML IDP (ADFS) configuration in Keycloak. For this configuration users are registered into Keycloak using First login flow. Currently First Flow login imports only basic user information and nothing relating to the user's associated AD groups.

I am using the default groups feature which automatically assigns group membership whenever any new user is created or imported throughout identity brokering.

### Version

Helm chart 18.4.3

### Expected behavior

When a user makes a First Flow login his associated ADFS group should also be imported. To quote from the documentation this is similar to what the LDAP Group Mapper does : 

_Group Mapper
This mapper maps LDAP groups from a branch of an LDAP tree into groups within Keycloak. This mapper also propagates user-group mappings from LDAP into user-group mappings in Keycloak._

source: [link](https://www.keycloak.org/docs/latest/server_admin/index.html#_ldap_mappers)

### Actual behavior

The user groups are not imported. Only username, surname and email are automatically imported.

### How to Reproduce?

This workflow might not be complete. I am trying to reconfigure an existing configuration setup by someone else :

1. Register custom Realm via master realm
2. Register ADFS IDP against Realm.
3. Add Default Groups 

### Anything else?

This is how the Grafana client's Client Scopes looks in Keycloak(It has no configured mappers):

<img width="382" alt="gRAFANA" src="https://github.com/keycloak/keycloak/assets/23119187/11988d18-aa82-4ba1-a5f7-79c2d3212b09">

Under Client Scopes I can see a scope with name group was created and it has the following settings :

"Include In Token Scope" - Enabled
"Display On Consent Screen" - Enabled
"Type" - Optional
"Protocol" - OpenID Connect

<img width="723" alt="CLIENT-SCOPES" src="https://github.com/keycloak/keycloak/assets/23119187/2f3ef27e-9e3d-4cbb-a00b-32ad1d61d3fc">

Under user's "Attributes" tab I also don't see anything, suggesting the ADFS groups are not being added for all First Flow logins.

I am also unsure if I will need to map the AD groups to Keycloak roles. If, yes, why is it necessary ?

**Comment by jens-hammel** [comment]
I think you are mixing things up. You write about Identity Brokering so you have created an Identity Broker not a User-federation via LDAP. 
I think that importing Groups is only possible via LDAP but not via IDP unless your IDP provides a claim for that you can map in the IDPs setting.
Correct me if I am wrong...

**Comment by rmartinc** [comment]
I'm closing the issue as I think it was answered. Please reopen if needed. Regards!
