### ISSUE TITLE
Policy providers for user scopes are invoked more often than expected

### ISSUE THREAD

**Issue by nicow-odit** [keycloak/keycloak#23877]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/fine-grained-permissions

### Describe the bug

We're trying to implement [Impersonation](https://www.keycloak.org/docs/latest/securing_apps/#impersonation). In order to make sure only the right users are allowed to impersonate others we'd like to use "Fine Grain Admin Permissions" since we need to do dynamic evaluations during runtime. We've enabled "Fine Grain Admin Permissions" for users and defined two user permissions
- `admin-impersonating.permission.users` for scope `impersonate` with policy `impersonating`
- `user-impersonated.permission.users` for scope `user-impersonated` with policy `impersonated`

There's a policy provider for each of the policies, i.e. two in total, and they're implemented using the Policy Provider SPI
- `org.keycloak.authorization.policy.provider.PolicyProvider`
- `org.keycloak.authorization.policy.provider.PolicyProviderFactory`

When sending an token exchange request as described [here](https://www.keycloak.org/docs/latest/securing_apps/#making-the-request-2), we notice that our policy providers are invoked twice, i.e. two times the one for scope `impersonate` and two times the one for `user-impersonated`. What makes things even worse is that the same policy provider gets different `org.keycloak.authorization.identity.Identity` objects passed.

The reason for this seems to be that whenever a scope for the `Users` resource is evaluated, all (six) scopes of this resource are evaluated (see `UserPermissions#hasPermission(EvaluationContext, String...)`) which means that the respective policy providers are invoked. That is, when looking at `UserPermissions#canImpersonate(UserModel, ClientModel)`, the code path `canImpersonate()` invokes both policy providers and `isImpersonatable(user, requester)` also does invoke both.

Plus, when navigating through the admin console and hitting the _Users_ page, the impersonation policy providers are also called since again all scopes including `impersonate` and `user-impersonated` are evaluated.

In our policy provider we cannot decide whether it's a legitimate call or not.

### Version

22.0.3

### Expected behavior

We'd expect the policy provider to be invoked if and only if its respective scope must be evaluated.

### Actual behavior

Policy providers for the `Users` resource are invoked whenever any scope must be evaluated.

### How to Reproduce?

1. Create a realm 'test' where the following actions take place
2. Create user1
3. Create user2
4. Activate "Fine grained permissions for managing all users in realm." on the _Users_ page
5. Defined two user permissions
`admin-impersonating.permission.users` for scope `impersonate` with policy `impersonating`
`user-impersonated.permission.users` for scope `user-impersonated` with policy `impersonated`
6. Implement a policy provider `ImpersonatingPolicyProvider[Factory]` just logging its invocation for policy `impersonating` implementing the Policy Provider SPI
7. Implement a policy provider `ImpersonatedPolicyProvider[Factory]` just logging its invocation for policy `impersonated` implementing the Policy Provider SPI
8. Deploy the two policy providers
9. Get an access token for user1
10. Send an impersonation request using user1's access token to impersonate user2

Result: Both policy providers will be invoked twice each.

**Comment by pedroigor** [comment]
@nicow-odit This is being fixed by https://github.com/keycloak/keycloak/issues/25510. I'm linking both issues and closing this one.
