### ISSUE TITLE
Error in MyResourcesTest.shouldDenyRequestToShare

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#23889]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ci

### Describe the bug

[Account Console IT (chrome)](https://github.com/keycloak/keycloak/actions/runs/6466892424/job/17556396827)

```
Error: OR] org.keycloak.testsuite.ui.account2.MyResourcesTest.shouldDenyRequestToShare  Time elapsed: 17.12 s  <<< ERROR!
-- org.openqa.selenium.NoSuchElementException: 
-- no such element: Unable to locate element: {"method":"css selector","selector":"#shareRequest\-Resource\-13"}
```

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by ssilvert** [comment]
@miquelsi Are you waiting for the UI team to do something here?  If not, I'd like to remove the `team/ui` label.

**Comment by jonkoops** [comment]
Removing the UI team labels for this one, I am not sure this belongs in our bucket.
