### ISSUE TITLE
Using platform for managing translations

### ISSUE THREAD

**Issue by DimitriDR** [keycloak/keycloak#23890]
### Description

Hi,

With more than 10 languages on Keycloak and to enhance accessibility all around the world, I would suggest to using a platform dedicated to manage translations, you have many choices, Crowdin (free for open source projects), Transifex, and others.

I think it makes it easy both for translators and you, you can automatically grab translations from Crowdin ([like what Paperless does](https://github.com/paperless-ngx/paperless-ngx/pull/4113)). It's also easier to validate a translation, rather than having a comment review on a file.

**Comment by jonkoops** [comment]
There is already an existing discussion around this under #9270.
