### ISSUE TITLE
Kerberos auto login does not work

### ISSUE THREAD

**Issue by BadBossy** [keycloak/keycloak#23895]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

Hello,

I'm trying to setup a keycloak server in docker with  ldap and kerberos authentication. But I'm stuck with getting auto login to work... Normal login via username + password works.

### Version

22.0.1

### Expected behavior

auto login does not work

### Actual behavior

login mask is shown but if I enter username+password, it logs me in

### How to Reproduce?

Compose file
```
version: '1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: -v start-dev -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./keycloak/server.pem:/etc/x509/https/tls.crt
      - ./keycloak/server.key.pem:/etc/x509/https/tls.key
      - ./keycloak/auth.keytab:/etc/x509/https/auth.keytab
      - ./keycloak/krb5.conf:/etc/krb5.conf
    environment:
      KC_DB: mssql
      KC_DB_URL: <connection>
      KC_DB_USERNAME: <username>
      KC_DB_PASSWORD: <password>
      KEYCLOAK_ADMIN: <username>
      KEYCLOAK_ADMIN_PASSWORD: <password>
      KC_TRANSACTION_XA_ENABLED: false
      KC_HOSTNAME_URL: https://auth.example.com
      KC_HOSTNAME_DEBUG: true
      KC_FEATURES: kerberos // this does not even work
      KC_HTTP_ENABLED: false
      KC_HTTPS_PORT: 443
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      TZ: "Europe/Paris"
```

krb5.conf

```
[libdefaults]
    default_realm = EXAMPLE.COM

[realms]
    EXAMPLE.COM = {
        kdc = 192.168.1.29
        admin_server = 192.168.1.29
    }

[domain_realm]
    .example.com = EXAMPLE.COM
    example.com = EXAMPLE.COM
```

### Anything else?

Logs:
```
WARN  [org.keycloak.events] (executor-thread-24) type=LOGIN_ERROR, realmId=6229f032-2218-4400-b990-422578b8cd3e, clientId=account-console, userId=null, ipAddress=192.168.1.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=https://auth.example.com/realms/Test/account/#/, code_id=21f4aa25-32cc-46bd-8120-be3b67b5affa, response_mode=fragment

Found KeyTab /etc/x509/https/auth.keytab for HTTP/auth.example.com@EXAMPLE.COM

WARN  [org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator] (executor-thread-30) SPNEGO login failed: java.security.PrivilegedActionException: GSSException: Defective token detected (Mechanism level: GSSHeader did not find the right tag)

KRBError:
        sTime is Wed Oct 11 11:34:41 CEST 2023 1697016881000
        suSec is 325395
        error code is 25
        error Message is Additional pre-authentication required
        sname is krbtgt/EXAMPLE.COM@EXAMPLE.COM
        eData provided.
        msgType is 30
```

**Comment by rmartinc** [comment]
The defective token detected usually means that the browser is using ending a ntlm token instead of kerberos. There are multiple misconfigurations that finally result in this error.  For example look to this stackoverflow thread for tips: https://stackoverflow.com/questions/47227276/gssexception-defective-token-detected-when-trying-to-authenticate-to-tomcat

Please do not file an issue for this type of questions. Github issues are for code errors with clear reproducers that probably will trigger a PR. Use the keycloak user group for questions: https://groups.google.com/g/keycloak-user

**Comment by mposolda** [comment]
@rmartinc Thanks!

Closing as this is not Keycloak bug, but rather asking for help with the environment setup.
