### ISSUE TITLE
User profile attribute default render should be ordinary input

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#23911]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

If I create a User Profile attribute with no annotations then it should render as an ordinary single input field in admin console and account console.  Right now it is rendering as a multi-select dropdown.

### Version

main

### Expected behavior

See above

### Actual behavior

See above

### How to Reproduce?

See above

**Comment by jonkoops** [comment]
Changing this to be a lower impact, as this intended (although counter-intuitive behavior). The user needs to add a 'input type' annotation in order for the renderer to know which type of field to use, and this needs to be corrected in several places.
