### ISSUE TITLE
Admin console does not allow several special characters for realm name anymore

### ISSUE THREAD

**Issue by ThomasTosik** [keycloak/keycloak#23930]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When i create a new realm and type the realm name "customer.tenant" the validation fails and i can not create a realm. This is because i use the "special" character "."

### Version

21.1.0

### Expected behavior

Before 21.1.0 this was allowed and the realm was created

### Actual behavior

The validation in the ui fails and the realm can not be created

### How to Reproduce?

Create a new realm with the name "customer.tenant" or any other "special" character inside the realm name.

### Anything else?

I was advised to create a new bug for this topic from here #17592.

We are using the realm name in our solutions as "customer.tenant". We use a dot for seperation. It worked for us flawlessly since several years. Inside the Keycloak UI and for the Keycloak backend. I also misread (?) that this combination was never intended to be allowed? Was it somewhere documented (honest question)?

This change does not only disallow "space" but also other characters. But it only effects the Keycloak UI not the Keycloak Http Rest backend. So i still can create realms that do not adhere to the new schema.

It is intended to disallow this also for the HTTP Rest API? How can i migrate my application from my stated (previous legal?) pattern to the new restrictions?

Regards

Thomas

**Comment by ssilvert** [comment]
To be more specific, this issue appears to be in response to this particular comment: https://github.com/keycloak/keycloak/issues/17592#issuecomment-1754762233

@edewit will probably be the best one to answer as he worked this issue before.  He is out until next week.

**Comment by jonkoops** [comment]
The changes done [here](https://github.com/keycloak/keycloak-ui/pull/4259/files#diff-c99eb4d3acbc92ff2343915313c0d87c0c0be1b284a50c6d9f82ace2e8212c09R90-R96) will have to be reverted, but we do not want to accidentally re-introduce #17592, so we have to test this thoroughly. I believe that that changes from #23667 might actually mitigate this potential regression, as all special characters in the URL are encoded there, so a combination of these efforts could squash both bugs.

**Comment by sfitts** [comment]
Based on this discussion it seems that as of `22.0.5` it should be legal to define a realm with a "dot" in the name.  However, I'm still seeing the error in the admin UI in `23.0.3`.  We name our realms using the host + domain of the target site (e.g. "dev.vantiq.com") and now that we're starting to upgrade Keycloak, we're can no longer change anything on the "General" tab of the realm settings.  Doesn't seem to impact anything else and changes via the API are still working.

**Comment by sfitts** [comment]
Checked `22.0.5` and it has the same behavior.  So now I'm guessing that maybe I misinterpreted the resolution here.  I assumed that the change would allow realms with `.` in the name to be updated/edited via the admin UI.  This seems to mostly be true with the exception of the "General" tab of the realm settings (the tab that shows the name).  In that tab, any change to a realm with dots in the name results in a client side error indicating that the realm name "can't contain special characters".

**Comment by patrickdk77** [comment]
How do we migrate? I have a bunch of realms with spaces in them, from my v12 install, that has been upgrading, Attempting to move to a newer version now and I'm having issues cause the spaces are no longer allowed and are erroring the console.
How would I migrate these realms?

**Comment by jonkoops** [comment]
Please direct any new conversation into a forum topic or bug report, it is a general policy not to continue discussion on issues that have been closed because they cannot be tracked.
