### ISSUE TITLE
FederatedUserLink errors when user does not have view-realm role

### ISSUE THREAD

**Issue by jackie-linz** [keycloak/keycloak#23954]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When viewing "Credentials" tab of a federated user in the admin console, if the currently authenticated user does not have `view-realm` role, admin console throws exception.

### Version

22.0.3

### Expected behavior

User credential is displayed

### Actual behavior

Error `Missing ":providerId" param` is displayed

![image](https://github.com/keycloak/keycloak/assets/120340761/e67a9b4a-1a2f-46ef-8529-ba98506d3743)

Browser console shows error:

![image](https://github.com/keycloak/keycloak/assets/120340761/61e869b0-4213-4de5-bbf0-51c2e2a0e3f4)

### How to Reproduce?

1. User is granted only `query-users` and `manage-users` roles of a realm
2. User logs into the realm's admin console UI
3. Search and opened a user in the realm (the user is a federated user)
4. Go to the "Credentials" tab

### Anything else?

`providerId` is a mandatory path parameter for federation route

https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user-federation/routes/CustomUserFederation.tsx#L18

but `providerId` is not returned from `userStorageProvider.name()`

https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user/FederatedUserLink.tsx#L29-L31
https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/src/resources/userStorageProvider.ts#L7-L17

Potential fix - update `FederatedUserLink` to show plain text of provider name instead of link

**Comment by jonkoops** [comment]
> Potential fix - update `FederatedUserLink` to show plain text of provider name instead of link

I think this is a valid way to resolve this, if the user doesn't have permission to view the link we should not be rendering it. Perhaps we can add a utility function next to the component that can check if the user has permissions to see the link?

For example:

```tsx
{canViewFederationLink(user) && (
  <FederatedUserLink user={user} />
)}
```

@jackie-linz would you be willing to implement a fix for this?

**Comment by jackie-linz** [comment]
I think it's still valuable to indicate that the user is a federated one, even if the authenticated user has no access to view the user federation object.

The `FederatedUserLink` component already uses `access.hasAccess("view-realm")` to check for user access, so I'm thinking adding a conditional return, e.g.

```javascript
if(access.hasAccess("view-realm")) {
  return (<Button...);
}

return (<span>{component.name}</span>);
```

Happy to raise a PR.

**Comment by jackie-linz** [comment]
@jonkoops PR raised, let me know if any change required
