### ISSUE TITLE
Group members are displayed incorrectly when using LDAP in READ_ONLY mode

### ISSUE THREAD

**Issue by 999eagle** [keycloak/keycloak#23966]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

When user federation via LDAP is configured and the group mapper is set to READ_ONLY mode, group members are sometimes duplicated in the admin UI. More specifically, the same group members are listed multiple times on different pages in the admin UI. This does not appear to be a UI bug though as the API calls actually return the same users for different pages.

Making a request to the admin API `/admin/realms/{realm}/groups/{id}/members` manually shows the same behaviour when requesting group members page by page (using the `first` and `max` parameters). Requesting group members with `max` set to a higher value than the group has members returns all members correctly without duplicates.

### Version

22.0.1

### Expected behavior

The admin API returns group members correctly without any duplicates.

### Actual behavior

The admin API endpoint `/admin/realms/{realm}/groups/{id}/members` returns the same users multiple times on different pages when using pagination.

### How to Reproduce?

- Setup LDAP user federation with the group mapper set to READ_ONLY mode.
- Create a LDAP group with more than 100 members (the default page size in the admin UI).
- Query the group members in Keycloak.

### Anything else?

The actual pagination happens in https://github.com/keycloak/keycloak/blob/22.0.1/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L87. Multiple sequential requests will not keep some kind of cursor for pagination, so all group members are queried with every request. The order of the returned users is not defined anywhere and as a `Set<LDAPDn>` is used for the query results, the iteration order is not necessarily defined. A fix would be to sort the returned users before getting a sublist as proposed in #23784.

**Comment by rmartinc** [comment]
I cannot reproduce this, at least with apache-ds as the ldap, but I see your argument.

@999eagle Just one question, I'm trying to guess who is changing the order. If you modify this [line](https://github.com/keycloak/keycloak/blob/fc8e7122e3341ac8842c068d747eb848549c8b9a/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L64) to use a `LinkedHashSet` that maintains the order, do you see the repeated users? Or is the ldap the one that is changing the order of the values returned? When you do a direct ldapsearch over the group the member attribute return values in different order?

Probably we need your PR and sort the results but I was trying to understand this better.

**Comment by 999eagle** [comment]
I'm using Active Directory as the LDAP backend. Using `ldapsearch "(distinguishedName=$groupDN)" 'member;range=0-*'` with the same LDAP URI and bind user configured in Keycloak returns all members of the group (without having to increase the range) and in the same order with every query.

I've now tested `LinkedHashSet`, `LinkedHashSet` + `sort` and `sort` and all three patchsets (applied to current main) still show the same issue in the admin API though. Interestingly, paging through the results in the admin UI always shows the exact same page. So page 1, 2, 3 etc. each show different users with some duplicated users, but each page always shows the exact same users. I'm not entirely sure what exactly is happening here to be honest.

**Comment by rmartinc** [comment]
@999eagle The only way I can obtain duplicated users in my env is if I previously imported the groups. So I created the group mapper with IMPORT (users of the group are imported to the BD), then I change to READ_ONLY. Now I get first the imported users in DB, and then the LDAP users again. Each user appears twice. But this is a bit a corner case.

How many times do you see the same user (one, two or more)?

**Comment by 999eagle** [comment]
I've started with a completely fresh database in my test env, added unsynced ldap federation, added a read_only group mapper and that's enough to reproduce the issue for me. No imports happening.
Users can appear on lots of pages, not just twice. I've set the page limit to 10 and see a few users on nearly every page. There's no single page with duplicate users though.

I've been printf-debugging (or rather, log-debugging) Keycloak for a while now. From what I've gathered, the [`LDAPStorageProvider.getGroupMembersStream`](https://github.com/keycloak/keycloak/blob/d0fed02e1d59dfc98c8ecce4b4ab2332705f47ca/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L369) method is called with `firstResult = null` as the actual paging is implemented in [`UserStorageManager.query`](https://github.com/keycloak/keycloak/blob/d0fed02e1d59dfc98c8ecce4b4ab2332705f47ca/model/legacy-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L271). The [`MembershipType.getGroupMembers`](https://github.com/keycloak/keycloak/blob/d0fed02e1d59dfc98c8ecce4b4ab2332705f47ca/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L89) method thus actually calls `subList(0, 11)` for the first page, `subList(0, 21)` for the second page, `subList(0, 31)` for the third page and so on. Maybe there's another `Set` involved somewhere that I haven't found yet?

**Comment by 999eagle** [comment]
@rmartinc I've found the real issue here and the proper solution. Also the mostly likely reason why you couldn't reproduce this is because this issue only occurs when the username attribute is not the same as the RDN attribute. In the case of AD, the RDN attribute is `cn` while the username is `sAMAccountName`, so an additional LDAP query has to be made which changes the order again. I've updated my fix in #23784 now to actually fix this properly.

**Comment by rmartinc** [comment]
@999eagle I think there are more issues in the part you have detected. I have done a test in this branch https://github.com/rmartinc/keycloak/tree/issue-23966. Can you please test in your env with it?

**Comment by 999eagle** [comment]
@rmartinc Your branch seems to fix this issue as well. It does require one LDAP query per user though as far as I can tell instead of one LDAP query for all users.

**Comment by rmartinc** [comment]
> @rmartinc Your branch seems to fix this issue as well. It does require one LDAP query per user though as far as I can tell instead of one LDAP query for all users.

Not exactly, the previous behavior did an OR search and then loaded the users one by one. So it was:

1. Group: (&(cn=groupname)(objectclass=group)) (locate members)
2. OR search: (&(|(cn=user1)(cn=user2)(cn=user3)...)(objectclass=person)(objectclass=organizationalPerson)(objectclass=user)) (the or)
3. N searches via UUID: (&(objectClass=*)(objectGUID=XXXXXXX)) (Here the user was imported if not in internal DB or just validated, this is done in the loadUsersByUsernames call)

With my commit we are doing:

1. Group: (&(cn=groupname)(objectclass=group))
2. N searches user via DN using base scope:  (&(objectclass=person)(objectclass=organizationalPerson)(objectclass=user)) (Here again the user is imported if needed)

So I think we are doing more or less the same number of queries. We can even improve the previous solution and in the OR operation import users directly.

But there is another change in the commit that is more problematic IMO. This is the point I doubt what to do. Now the list of members is reduced before to the requested page ([here](https://github.com/keycloak/keycloak/blob/22.0.4/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L92)). But that is problematic. Because a DN could be excluded from the result for multiple reasons (it's a group, different objectclasses in general, a custom filter is excluding the entry, it's a non-existent DN,...). If that happens the page is returned with less results and, in general, the pagination is somehow broken.

**Comment by 999eagle** [comment]
> So I think we are doing more or less the same number of queries. We can even improve the previous solution and in the OR operation import users directly.

Ah right, I overlooked the queries done in `loadUsersByUsernames`. In that case, I think doing the N searches directly is fine.

> Now the list of members is reduced before to the requested page ([here](https://github.com/keycloak/keycloak/blob/22.0.4/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L92)). But that is problematic. Because a DN could be excluded from the result for multiple reasons (it's a group, different objectclasses in general, a custom filter is excluding the entry, it's a non-existent DN,...). If that happens the page is returned with less results and, in general, the pagination is somehow broken.

Oh you're right. I didn't even think of that before. Your commit filters the stream before limiting, which should fix that issue as well.

**Comment by rmartinc** [comment]
@999eagle Can you please test with the same branch https://github.com/rmartinc/keycloak/tree/issue-23966 when you have time? I added a new commit to read users by chunks (by default the chunk size is 64, we can tune that if needed). It works in my AD and my apacheds (but for sure you have more complicated setup than mine, and more members).

**Comment by sguilhen** [comment]
> But there is another change in the commit that is more problematic IMO. This is the point I doubt what to do. Now the list of members is reduced before to the requested page ([here](https://github.com/keycloak/keycloak/blob/22.0.4/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/MembershipType.java#L92)). But that is problematic. Because a DN could be excluded from the result for multiple reasons (it's a group, different objectclasses in general, a custom filter is excluding the entry, it's a non-existent DN,...). If that happens the page is returned with less results and, in general, the pagination is somehow broken.

This is really a nice catch and indeed under circumstances like the ones you've described, the set of returned entries would be less than the desired size.

> I added a new commit to read users by chunks (by default the chunk size is 64, we can tune that if needed)

Also very interesting, and I wonder about other places in LDAP integration that could benefit from this approach.

**Comment by 999eagle** [comment]
@rmartinc Tested the chunking now, seems to work correctly with page size 100. Thank you!

**Comment by rmartinc** [comment]
I sent a PR yesterday for this. Thanks @sguilhen  and @sguilhen for looking!
