### ISSUE TITLE
The username in account is required and don't change when email as username is enabled

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#23976]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

When a realm has `Email as username` enabled, the `username` attribute is marked as required and won't change when the user updates the e-mail.

### Version

22.0.4

### Expected behavior

The username field is not required and `Email as username` is enabled and must be the same as the e-mail when updating the user.

### Actual behavior

When a realm has `Email as username` enabled, the `username` attribute is marked as required and won't change when the user updates the e-mail.

### How to Reproduce?

* Create a user
* Enable `Email as username`
* In the account console try changing the e-mail to see if the username changes.

If the user profile is enabled, make sure the username field is not marked as required.

**Comment by lrozenblyum** [comment]
Maybe a related/similar issue was also reported https://github.com/keycloak/keycloak/issues/22036
