### ISSUE TITLE
Docs: server_admin/topics/user-federation/ldap.adoc

### ISSUE THREAD

**Issue by simonleecs** [keycloak/keycloak#24013]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

import-export

### Describe the bug

After setup the user federation, the connection is success
When click on "Sync all users" , it prompt "Sync of users finished successfully.0 users added, 6 users updated, 0 users removed, 1 users failed."

But not user input or see in users menu... 

can help ?

### Version

22.0.1/22.0.4

**Comment by martin-kanis** [comment]
@simonleecs I think, you have to search for users from a user provider. Either by username or search for all by "*". Users from a user provider are not shown be default.
