### ISSUE TITLE
Issue re deploying distributed ispn keycloak on k8s

### ISSUE THREAD

**Issue by sortafullstack** [keycloak/keycloak#24026]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

dist/quarkus

### Describe the bug

We have been running  kc 21.1.1  on distributed  ispn on k8s for some time via the bitnami helm chart.  We have ~300k unique sessions.   I'll note that I havent reproduced on latest nightly because I need my loaded stage or prod environment to intermittently reproduce.

When we run a deploy we intermittently get a locking issue that eventually forces us to restart our cluster.  There isnt seemingly any rhyme or pattern as to which pod in the set or in whichever deploy initiates the issue.  

On the server that initiates the problem, our logs show 
`[org.infinispan.stats.impl.ClusterCacheStatsImpl] (executor-thread-11) Could not execute cluster wide cache stats operation `

Then the cache is left in an invalid state. We have a custom keycloak endpoint based on this code https://github.com/thomasdarimont/keycloak-health-checks/blob/master/src/main/java/com/github/thomasdarimont/keycloak/healthchecker/spi/infinispan/InfinispanHealthIndicator.java) which indicates one of the caches is left in an invalid state.

Further attempts to restart the node end with a timeout after log records like 
` ISPN000660: Cache sessions start failed, stopping any running components: org.infinispan.commons.IllegalLifecycleStateException: Cannot wire or start components while the registry is not running`

if there is no load, restarting a nearby node occasionally clears the problem. Typically however, restarting nearby nodes end with that node also being stuck in the same failed pattern. Once more than one node is stuck, there is no escape.  it seems a lock or similar is left to pollute any further attempts at restarting anything.  The only recovery then is to force restart all the nodes with the subsequent loss of all caches thereby forcing users to login.  

### Version

21.1.1

### Expected behavior

We would prefer cache not be left in this invalid state even if pod restarts fails for any reason.

### Actual behavior

One pod in the k8s cluster fails and then we are stuck with a cluster that we cant deploy anything to.

### How to Reproduce?

We have tried to reproduce by adding sessions to the level of our prod servers and then running a deplloy. This has only intermittently reproduced the issue.

We also tried reducing the timeouts in conf/cache-ispn.xml and were able to trigger the timeout for the state-transfer while under load from a test script. We were able to observe the log related to timing out this setting whcih is different than our issue, but then our cluster was left in a similar state as with our actual issue with a pod that wont restart and any neighboring pods also failing restarts.

### Anything else?

We were able to start pods up by setting the cache specific state-transfer config to not wait for state transfer to complete. However we still couldnt get pods to restart without this setting and tehn any further restarting does not move any sessions around and eventually get lost.

**Comment by vmuzikar** [comment]
@sortafullstack Thanks for the report.

This seems like something from the Store team territory, reassigning to them.

That said, please note we no longer support 21. For efficient triage and prioritization, it'd be most helpful if reproducible with latest nightly.

**Comment by mhajas** [comment]
We experienced similar issues and I believe this was addressed in Infinispan by the following issue: https://issues.redhat.com/browse/ISPN-15042

Could you please try with the latest version? If you are able to reproduce with the latest version please reopen.
