### ISSUE TITLE
Admin UI: Group details page is not updated by group list dropdown actions

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#24035]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When deleting a group from the groups list and being on the details view of that group, the ui does not jump back to the groups overview like it does for the Action -> Delete dropdown: 

![image](https://github.com/keycloak/keycloak/assets/1793007/a20f34be-92ad-4666-9c08-c7a5591b43c4)
![image](https://github.com/keycloak/keycloak/assets/1793007/f4b52756-0aee-445c-8d4e-0fbd7a75a42f)

Additionally when renaming the group via the left menu the group name on the details also is not updated automatically.
![image](https://github.com/keycloak/keycloak/assets/1793007/4da4ca2e-39a2-414d-9234-d989a1c31225)
![image](https://github.com/keycloak/keycloak/assets/1793007/21d0c1b2-cc7b-4576-a675-0f4d39368e38)
![image](https://github.com/keycloak/keycloak/assets/1793007/e82f28ab-c472-471e-a13e-4794ef8f63c7)

### Version

22.0.4

### Expected behavior

When deleting a group that is currently opened the UI should always switch to the overview again. 
When renaming a group the name should automatically be updated in the details view of that group.

### Actual behavior

The UI stays at the details view of the deleted group.
The name stays the same.

### How to Reproduce?

Group delete:
1. Create a group
2. Go to the details view of that group
3. Delete the group with the delete dropdown of the group list (NOT Action -> Delete which is working fine)

Group renaming:
1. Create a group
2. Go to the details view of that group
3. Rename the group with the rename dropdown of the group list (NOT Action -> Rename which is working fine)

**Comment by himanshi1099** [comment]
@ssilvert @jonkoops This issue is reproducable. Can i pick it up.

**Comment by edewit** [comment]
@himanshi1099 go for it, I think all it needs is a to trigger a re-render

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
