### ISSUE TITLE
Missing migration step for Keycloak 22 during import

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#24031]
There is migration step for kc22 which updates rh-sso themes (account, login, email) when upgrading Keycloak:
https://github.com/keycloak/keycloak/blob/50916d58b165f1374369beef764a6a4108e82c9e/model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/JpaUpdate22_0_0_RemoveRhssoThemes.java#L34-L61

To support import of older realm JSONs there needs to be also similar change in MigrateTo22_0_0. Currently there is account theme related change present: https://github.com/keycloak/keycloak/blob/50916d58b165f1374369beef764a6a4108e82c9e/model/legacy-private/src/main/java/org/keycloak/migration/migrators/MigrateTo22_0_0.java#L70-L75 but login and email is missing.

**Comment by ahus1** [comment]
@vramik - please choose a backport milestone as you see fit for this.
