### ISSUE TITLE
Group attributes are not saved if there are two attributes with the same key

### ISSUE THREAD

**Issue by samkolchea** [keycloak/keycloak#24032]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

In the below screenshot, I add 2 attributes with the same key which is "scp". Clicking on the save button, I get "Group updated" message which means the group is saved successfully. However, when I click on F5 to refresh the page, the Group attribute is empty. It looks like that the group attribute is not saved. 
On the contrary, the bug does not occur with users.

![image](https://github.com/keycloak/keycloak/assets/116588922/363cf7ee-6144-459b-aa74-f47e598fbef6)

### Version

22.0.4

### Expected behavior

Group attributes should be saved regardless of the key

### Actual behavior

Group attributes are not saved

### How to Reproduce?

Add two attributes to a group with the same key value

**Comment by antikalk** [comment]
Just checked this: I can confirm this issue. However the attributes are actually saved, but once there are multiple values per key the UI does not render the attribute. The GET call to get the group data actually returns the attribute with multiple values. 

![image](https://github.com/keycloak/keycloak/assets/1793007/0969e7e0-ec01-464a-b646-2d3b0328810e)
![image](https://github.com/keycloak/keycloak/assets/1793007/91a2c5c6-698a-4a72-bab6-b183bea783c6)


Additionally, when having an attribute with a different key it seems to be rendered correctly:

![image](https://github.com/keycloak/keycloak/assets/1793007/49be0496-324c-40ce-8485-1fb574a9e51a)
![image](https://github.com/keycloak/keycloak/assets/1793007/632f9531-2ad9-47f3-8939-eacedd3e0379)

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
