### ISSUE TITLE
Expansion tree icon is not shown on the left of a parent group

### ISSUE THREAD

**Issue by samkolchea** [keycloak/keycloak#24030]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

See the attached screenshots. An expansion tree icon is not shown on the left of the ViewOnlyUserGroup. To see the expansion tree icon, we have to click on the ViewOnlyUserGroup

![image](https://github.com/keycloak/keycloak/assets/116588922/6d1c3ea3-617c-4a4f-bc29-0160eb04b3c0)

![image](https://github.com/keycloak/keycloak/assets/116588922/71eca436-46d0-4c0e-a07c-3f0c3c9c942c)

### Version

22.0.4

### Expected behavior

Expect to see the expansion tree icon on the left of the ViewOnlyUserGroup

### Actual behavior

No expansion tree icon on the left of the ViewOnlyUserGroup unless we click on the ViewOnlyUserGroup

### How to Reproduce?

Create a child group under a parent group

**Comment by edewit** [comment]
Unfortunately we can't fix this atm, because the Tree component that we use from patternfly doesn't allow us to do so. I've created an [issue](https://github.com/patternfly/patternfly-react/issues/9520) once we have updated to the latest version we'll be able to fix this as well

**Comment by jonkoops** [comment]
Closing this as it will be automatically be fixed when we upgrade to the next version of PatternFly, which can be tracked under #21345.
