### ISSUE TITLE
Consistent OLM channel taxonomy

### ISSUE THREAD

**Issue by pgodowski** [keycloak/keycloak#24076]
### Description

Not sure it's the proper place to ask the question, let me try anyway.

I have a question about the OLM channel taxonomy used by the community and production version of the Keycloak operator.
Currently I see that the [community operator](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/keycloak-operator/22.0.4) has OLM channels:
- `alpha`
- `candidate`
- `fast` (marked as _default_)

whereas the production Keycloak early driver has OLM channel 
-  `22`

I am wondering for production Keycloak, whether the taxonomy shall / could be aligned as with the other production-grade operators (e.g. RH Cert-manager), which uses the following taxonomy:

- `stable-v1`
- `stable-v1.10`
- `stable-v1.11`
- ..

So, perhaps for production Keycloak it would make sense to have OLM channels like:

- `stable-v22`
- `stable-v23`
- ...

What do you think @vmuzikar @ASzc @shawkins 

### Motivation

Consistent OLM channel taxonomy for the production version of Keycloak, consistent with other production-grade oeprators (like RH Cert Manager)

**Comment by vmuzikar** [comment]
@pgodowski Please send us an email with prod related discussion (or open a JIRA). :) Thanks.
