### ISSUE TITLE
Map Store Removal: Close issues on Github (cleanup)

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#24091]
### Description

With the Map Store being removed, we need to close all currently open issues related to it. Discussions should probably be closed too, and disable the `Keycloak.X - New Store` category.

**Comment by ahus1** [comment]
I'm taking on the closing of issues (first half of this issue)

**Comment by ahus1** [comment]
@stianst - can you please update the discussion form on GitHub with the following: 

* archive the category "Keycloak.X - New store"
* archive (?) existing discussions on that topic

Thanks!

**Comment by ahus1** [comment]
Category removed, discussions moved to archive.
