### ISSUE TITLE
Map Store Removal: Deprecate and remove Getting Started guides in Github

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#24090]
### Description

With the Map Store removal, we no longer need the associated Getting Started guides.

**Comment by ahus1** [comment]
The following guides have been deprecated by changing their title and adding a comment: 

* https://github.com/keycloak/keycloak/discussions/9596
* https://github.com/keycloak/keycloak/discussions/16768
* https://github.com/keycloak/keycloak/discussions/12010
* https://github.com/keycloak/keycloak/discussions/10254
