### ISSUE TITLE
Admin UI doesn't allow to un-select a theme in the realm

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#24119]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When I open the themes tab of a new realm, no themes are selected. I assume Keycloak then uses a default theme. 

Once I've chosen a theme, I can't unselect it any more. I  

### Version

999-SNAPSHOT

### Expected behavior

The open "Select..." or "Choose..." should be available even if I have previously selected a theme.

### Actual behavior

The open "Select..:" or "Choose..." is not available after I've chosen a theme

### How to Reproduce?

* Create a new realm
* Choose the realm's "Themes" tab
* Select a theme
* Save -> The option "Select..." is now gone

### Anything else?

Allowing to select no theme allows users to always use the default theme. If they can't unselect a previously selected theme, there is no way for them to go back to the default.

**Comment by osorionicolas** [comment]
If I'm not wrong the "keycloak" theme is the default for login and email theme and the "keycloak.v2" is the default theme for account and admin ui theme. Maybe it would be better to preselect the default theme instead of leaving the "Select a theme" option. What do you think @jonkoops?

**Comment by ssilvert** [comment]
@osorionicolas is correct.  Of course, you can select the default theme as it is always one of the choices in the dropdown.

I do see this as a minor usability issue as it is not clear which one is the default.

**Comment by ahus1** [comment]
There is also a difference when I choose the login theme of a client: There I can always go back to "blank", there is always the "Choose..." option. Maybe the one who wants to pick up this issue this can serve as an example.

**Comment by jonkoops** [comment]
I think we should add a separate 'Default' option that clears the configured value of the theme.

**Comment by DiamondMyK** [comment]
Hi, I'm new to open source and want to try to solve some simple problems. Can you assign this issue to me? I would appreciate it!

**Comment by ahus1** [comment]
@DiamondMyK - done. Please drop a note in this issue once there is a PR, so that the people watching this issue know it has arrived. Looking forward to the pull request!

**Comment by jonkoops** [comment]
@DiamondMyK thanks for taking this on. If you are looking to get started with contributing to Keycloak, I would recommend to read our [contribution guide](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md), also the [Administration Console documentation](https://github.com/keycloak/keycloak/tree/main/js/apps/admin-ui#keycloak-admin-ui) might be of interest for this particular issue.

If you require any assistance, let us know, and we will try to help you out. Good luck!

**Comment by DiamondMyK** [comment]
Thank you for your assignment, I will try my best to solve this issue!

**Comment by sebhoss** [comment]
Can we re-open this? If the default changed from keycloak.v2 to keycloak.v3 the old value still remains once selected and there is no way to de-select it to let keycloak pick the current default. This can be changed manually but that's highly annoying when you are maintaining multiple keycloak instances.

**Comment by ahus1** [comment]
Re-opening it. We're still waiting for more up-votes from the community and/or someone to pick this up and create a PR.

**Comment by vikasrajputin** [comment]
Hello @ahus1 
Can i pick this up?

**Comment by ahus1** [comment]
@vikasrajputin - sure, please go ahead.

**Comment by hookom** [comment]
Though it does not address the issue of unsetting these themes from the UI, it is possible to unset them by passing empty string as the value for each to the API.  For example, via the `@keycloak/keycloak-admin-client` npm package:

```
client.realms.update(
  {realm: 'master'},
  {
    loginTheme: '',
    accountTheme: '',
    adminTheme: '',
    emailTheme: '',
  }
})
```

**Comment by jonkoops** [comment]
@vikasrajputin are you still interested in landing this? If not let us know so we can assign it to someone else.

**Comment by vikasrajputin** [comment]
Yes, I'm almost done in 1-2 days will be raising the PR.

**Comment by jonkoops** [comment]
Sounds good, let me know if you need any help :+1:

**Comment by vikasrajputin** [comment]
Sure thanks @jonkoops !!

There's one issue I'm stuck with, is there any place where past issues are being discussed? Like any online forum or slack channel, where we can discuss any issues being faced by contributors?

Currently on executing:
`\mvnw clean install`

Facing the below issue (on my Windows machine):
`[ERROR] Errors: 
[ERROR]   TrustedHostClientRegistrationPolicyTest.testLocalhostDomain:67 » ClientRegistrationPolicy Host not trusted.
[INFO]
[ERROR] Tests run: 230, Failures: 0, Errors: 1, Skipped: 2`

**Comment by jonkoops** [comment]
> There's one issue I'm stuck with, is there any place where past issues are being discussed? Like any online forum or slack channel, where we can discuss any issues being faced by contributors?

Yes, we use [GitHub Discussions](https://github.com/keycloak/keycloak/discussions) as a forum, and there are various places where [such discussions can be had](https://www.keycloak.org/community). But for your convenience we can discuss this here as well.

Try skipping the tests by adding `-DskipTests` at the end of the command. Alternatively, you don't need to build the Keycloak server to work on the admin console. You can also run a nightly Keycloak server, and run it in dev mode against the admin console.

To run the development environment of the admin console install the latest version of Node.js, preferably using a package manager as outlined by the [Node.js download page](https://nodejs.org/en/download/package-manager). Then make sure to enable [Corepack](https://nodejs.org/api/corepack.html) by running:

```sh
corepack enable
```

Then, from the project root install the dependencies [using PNPM](https://pnpm.io/) by running:

```sh
pnpm install
```

You can then start a nightly version of the Keycloak server using [our scripts](https://github.com/keycloak/keycloak/tree/main/js/apps/keycloak-server#keycloak-server):

```sh
pnpm --filter keycloak-server start --admin-dev
```

Keep this proccess running in the background and start the [Vite](https://vitejs.dev/) development server for the admin console in a different terminal session by running:

```sh
pnpm --filter @keycloak/keycloak-admin-ui dev
```

Once this is running you can navigate to http://localhost:8080 and start making changes to the code.

**Comment by vikasrajputin** [comment]
Hello @jonkoops 
I'm ready with PR and looking forward to your feedback!

**Comment by jonkoops** [comment]
Currently a bit swamped, but I am sure that someone from @keycloak/ui could review this :)
