### ISSUE TITLE
HTTP/2 - Last parameter of POST form data contains 0x00 byte in some configurations.

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#24160]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

This is a different manifestation of a previous issue with HTTP/2 handling and empty dataframes - https://github.com/keycloak/keycloak/issues/13315

When an HTTP/2 capable client sends POST data to a Keycloak instance running the current nightly codebase and also ends the HTTP/2 stream with an empty dataframe, the last parameter in the POST data will have a `0x00` byte appended to it. 

This current issue will show up in odd ways - such as Keycloak responding that `grant_type=client_credentials` is an invalid grant type when used at the OIDC Token endpoint, or that PKCE values are invalid.

This is ultimately a problem that should be handled by the resteasy-reactive implementation, but logging this bug for tracking purposes within Keycloak itself.

### Version

main / nightly

### Expected behavior

No `0x00` byte is appending to any form parameters.

### Actual behavior

`0x00` byte is appended to last form parameter, breaking various flows and making the deployment unusable.

### How to Reproduce?

Background:
Our deployment makes use of Openshift, and that uses HAProxy configured to reencrypt and send data to the backend (Keycloak) using http/2 - the HAProxy implementation uses an empty dataframe to close the stream.

Actually reproducing it:
Configure Keycloak with HTTPS and an appropriate TLS certificate.
Use the reproducer code from https://github.com/keycloak/keycloak/issues/13315#issuecomment-1238125070
Debug the code in Keycloak and notice that the last form parameter contains an additional `0x00`

Alternatively, without using Keycloak, it can be reproduced using a generic quarkus app + some of the constructs Keycloak uses

See - https://github.com/jsorah/reproducer/tree/null_bytes_appended_to_form_data

### Anything else?

Disabling HTTP/2 will prevent this issue from occurring.

**Comment by pedroigor** [comment]
@jsorah Thanks a lot for looking at this and resurrecting that previous issue fixed when we were using Resteasy Classic.

@geoand Does it make sense to you and we are probably missing the same patch in Resteasy Reactive?

**Comment by geoand** [comment]
Interesting.

Since our HTTP2 support is all provided by Vert.x, this is one for @vietj and @cescoffier to answer

**Comment by cescoffier** [comment]
What was RestEasy classic fix?

**Comment by pedroigor** [comment]
@cescoffier Sorry, not really in classic but when we were using classic. The fix you did is https://github.com/quarkusio/quarkus/pull/27772.

I have a chat with @jsorah and looks like the same patch should be considered here https://github.com/quarkusio/quarkus/blob/3.2.6.Final/independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/VertxInputStream.java#L273?

**Comment by cescoffier** [comment]
Ah ah... I didn't remember fixing this. And yes, that same should be applied to Resteasy reactive. 

Did you try it?

**Comment by pedroigor** [comment]
Not yet, but I'll try to do the same and send a PR to you. Just wanted to make sure the findings from @jsorah make sense.

**Comment by pedroigor** [comment]
@jsorah @cescoffier Sent https://github.com/quarkusio/quarkus/pull/36605.

**Comment by jsorah** [comment]
Looks like this should be fixed in Quarkus 3.2.8.Final based on the release notes, and I see associated issue for upgrading Keycloak code base to that https://github.com/keycloak/keycloak/issues/24638
