### ISSUE TITLE
Run SAML  adapter tests with EAP 8

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#24168]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

When running SAML adapter tests for EAP8 an error is thrown. It might be related to the recent migration from javax to jakarta.

### Version

latest

### Expected behavior

Tests are executed successfully

### Actual behavior

The following error occurs when deploying the test app:

`15:56:57,666 WARN  [org.jboss.modules.define] (MSC service thread 1-1) Failed to define class org.keycloak.adapters.saml.servlet.SamlFilter in Module "deployment.employee2.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link org/keycloak/adapters/saml/servlet/SamlFilter (Module "deployment.employee2.war" from Service Module Loader): javax/servlet/Filter`

### How to Reproduce?

- Build Keycloak
- `mvn -f testsuite/integration-arquillian/servers/pom.xml clean install -DskipTests -s settings-prod.xml -Dinsecure.repositories=WARN -Papp-server-eap`
- `mvn -f testsuite/integration-arquillian/tests/base/pom.xml clean install -s settings-prod.xml -Dinsecure.repositories=WARN -Dbrowser=chrome -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dtest=SAMLFilterLoginResponseHandlingTest#testAttributes -Pauth-server-quarkus -Papp-server-eap`

### Anything else?

WIP branch: https://github.com/miquelsi/keycloak/tree/main_eap8

**Comment by mabartos** [comment]
It is not possible to run the Keycloak OIDC adapter on EAP8 as the adapter only supports Java EE and will NOT be migrated. EAP8 supports only Jakarta EE[1].

[1] https://access.redhat.com/articles/113373

**Comment by mabartos** [comment]
Created PR: https://github.com/keycloak/keycloak/pull/24633
