### ISSUE TITLE
Couple of links broken and invalid redirects in Keycloak Docs, probably due to a change to Docker docs

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#24179]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

docs

### Describe the bug

The Keycloak Documentation CI caught few issues with broken links and invalid redirects from here - https://github.com/keycloak/keycloak/actions/runs/6581652421/job/17881947174#step:5:1007

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExternalLinksTest.checkExternalLinks:41 Broken links (1) in guide 'securing_apps': 
                - https://docs.docker.com/registry/configuration/ (invalid status code 404)
[ERROR]   ExternalLinksTest.checkExternalLinks:41 Broken links (2) in guide 'server_admin': 
                - https://docs.docker.com/registry/spec/auth/ (invalid redirect to /registry/)
                - https://docs.docker.com/registry/spec/auth/token/ (invalid redirect to /registry/)
[INFO] 
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0

```

An update from the Docker about the Registry being donated to CNCF and moved to a different location can be found here.

https://docs.docker.com/registry/ 

```
Registry
Registry, the open source implementation for storing and distributing container images and other content, has been donated to the CNCF. Registry now goes under the name of Distribution, and the documentation has moved to distribution.github.io/distribution.

For reference documentation on the API protocol that Distribution implements, see Registry HTTP API.

For documentation related to authentication, see:

Token authentication specification
OAuth 2.0 token authentication
JWT authentication
Token scope and access
For information about image manifests, see:

Image Manifest Version 2, Schema 2
Image Manifest Version 2, Schema 1 (deprecated)
```

### Version

nightly (10/20/2023)

### Expected behavior

The links are expected to take the user to a valid landing page

### Actual behavior

The links are either broken or having invalid redirects due to a change in the Docker Registry docs location change.

### How to Reproduce?

Run the below command locally

```
MVN_HTTP_CONFIG="-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120"

mvn install -Dtest=ExternalLinksTest -am -pl docs/documentation/tests -nsu -B -e -Pdocumentation $MVN_HTTP_CONFIG
```

**Comment by jsorah** [comment]
Raised a PR for this, should take care of those failures - doc paths on the new host are pretty much the same.
