### ISSUE TITLE
Username now shown when creating a user and edit username is not allowed

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#24183]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

Fixes a regression introduced by #23976 where the username is not shown if `Edit username allowed` is not enabled.

### Version

999-SNAPSHOT

### Expected behavior

Creating a user should always show the username if the `Registration as username` flag is disabled.

### Actual behavior

Creating a user does not show the username if the `Registration as username` flag is disabled.

### How to Reproduce?

* Create realm
* Enable user profile
* Create an user

**Comment by jonkoops** [comment]
@pedroigor perhaps this one might deserve a backport?
