### ISSUE TITLE
Admin UI group view shows attributes of previously viewed group

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#24187]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When a group without attributes is viewed, attributes from last viewed groups are shown.

### Version

22.0.4

### Expected behavior

The attributes view should be empty

### Actual behavior

The attributes view shows the attributes from the previously viewed group.

![image](https://github.com/keycloak/keycloak/assets/789496/af1451ea-608a-4e43-b001-ecafbcdcca1a)

### How to Reproduce?

Create a group a with an atttribute.
Create a second group b without attribute.
Open the attributes tab of first group.
Click second group b.

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by jonkoops** [comment]
Moving this to v23, as we will no longer be doing patch releases for v22.
