### ISSUE TITLE
Logout error when missing id_token_hint leads to a page with no escape/way out for users (22.0.1)

### ISSUE THREAD

**Issue by jbarbadillo** [keycloak/keycloak#24213]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

After migrating Keycloak from version 16 to 22, this new requirement when `post_logout_redirect_url` of sending either `id_token_hint` or `client_id` raises an error (actually it is a warning level if you check logs).

This is OK when using an oidc client for my frontend, but for some users this error is raised when they try to login (probably because they are using a saved url with query params no longer valid). Keycloak redirects them to `https://iam.srv.das-gate.com/auth/realms/myrealm/protocol/openid-connect/logout?post_logout_redirect_uri=https://myrealm.app.com/`.

The problem here is that they don't know how to proceed, as there is no link/button to start again, or go back home. I checked that if they load the **home URL**, then they can login with no problems.

### Version

22.0.1

### Expected behavior

I would expect Keycloak to behave in one of these 2 ways when this logout error is triggered by a wrong login attempt:
*  render the ErrorInfo template, so I have the link to restart login
* or directly go to the home page regenerating the query params for this login session.

Users don't understand this message so it is pointless to show them this screen.

### Actual behavior

When redirecting to /logout path, users end up in a page with no Call To Actions and the message **Missing parameters: id_token_hint**, which for them means nothing usefull.

### How to Reproduce?

1. Configure a client for web, with the standard flow and backchannel logout.
2. Just go to this path, replacing myrealm by a real realm: `https://iam.srv.das-gate.com/auth/realms/myrealm/protocol/openid-connect/logout?post_logout_redirect_uri=https://myrealm.app.com/`
3.  I was not able to reproduce what happened to users themselves, but I saw they ware saving the keycloak login url with query params, and for them Keycloak redirected them to /logout url.
4. See the page saying **Missing parameters: id_token_hint**, where the user has no escape.

![image](https://github.com/keycloak/keycloak/assets/16958961/7faa174b-13bd-4aea-97cb-af63b8da994b)

![image](https://github.com/keycloak/keycloak/assets/16958961/596a44b4-171a-4bd9-9b3c-5c516387f42c)

**Comment by jbarbadillo** [comment]
Ok, I understand. My question then is... how Keycloak ends up redirecting  to a url like `openid-connect/logout?post_logout_redirect_uri=https://myrealm.app.com/` without attaching client_id=web, which is the client for browser login flow?  

I mean, with version 16.0 clients having login errors, were redirected to the start page (login page) when this kind of error happened, but now they end up at this page, without knowing what to do. I suppose this has to do with the new requirement to be OIDC compliant, which is great, but has this UX inconvenience on the other hand.

Is there anything I can do to make the login process more robust, specially from a UX perspective? We are using custom templates extending from base templates, but maybe we are missing some important detail regarding client_id. Any clues on what to pay attention to are welcomed!

**Comment by jbarbadillo** [comment]
Could it be that we are integrating oidc-client-ts logout badly? After reviewing [the code,](https://github.com/authts/oidc-client-ts/blob/main/src/UserManager.ts#L470) I see they automatically add the post_logout_redirect_uri, but not the client_id, which is also in **settings**.

I can see that [they add the id_token_hint](https://github.com/authts/oidc-client-ts/blob/0e88e36b37a70aef5ee8b9eba210c2d320c666e0/src/UserManager.ts#L535), if they can find it in **user**. 

I guess there could be a situation in our web, in which a logout was called but no token_hint found, resulting in this nehavior.  If this is the case, the is no problem with Keycloak, and we could fix it by always passing client_id=web on signoutRedirect().

I will try to reproduce this, and let you know so you can close this issue. Thanks!

**Comment by mposolda** [comment]
I am closing as there is no further response to the comment from October, so I assume that this is the error on your client code as you pointed.

If the parameter `post_logout_redirect_uri` is attached to the logout endpoint, then it is needed to also attach either `id_token_hint` or `client_id` or both of them . If none of them can be added to the URL, then the `post_logout_redirect_uri` parameter must be avoided as well.
