### ISSUE TITLE
admin-fine-grained-authz + client authorization settings requires view-client role

### ISSUE THREAD

**Issue by cnwaldron** [keycloak/keycloak#24219]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When using the preview feature admin-fine-grained-authz to allow certain users to manage their clients, some clients are using the Authorization capabilities. In Keycloak <=v19 using the old Admin UI Console, the only realm-management client roles that were needed to these users were: manage-authorization, query-clients, query-users, query-groups. In the new Admin UI Console, the role view-clients is required to create resources, client policy, or authorization scope in the Authorization settings for the client.

This is a problem as view-clients role allows users to view other clients and the client secrets of all applications.

### Version

nightly

### Expected behavior

When using admin-fine-grained-authz settings users with manage permissions to a client should be able to configure and create authorization policies for their client without requiring access to ALL clients in the realm.

### Actual behavior

To create new Authorization policies, client resources, or authorization scopes the user must have `view-client` realm management client role.

### How to Reproduce?

- Follow instructions at [Fine Grain Admin Permissions](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions) to configure a user to manage one specific client.
- Add realm-management client role of manage-authorization to the user as well.
- Turn on Authorization for the client.
- Login as user to the security-admin-console for the realm.
- View the configured managed client and select the Authorization tab.
- Select one of these sub-tabs of Authorization - Resources, Scopes, Policies
- On the tab, click the `Create (X)` button like `Create resource` button on the Resources sub-tab.
- You'll be met with an error message: Forbidden, permission needed: view-clients

### Anything else?

Related to: https://github.com/keycloak/keycloak/issues/23294

**Comment by cnwaldron** [comment]
Any update? This functionality is keeping my project from being able to upgrade from version 19.

**Comment by ssilvert** [comment]
@cnwaldron I believe the PR I just pushed solves your problem.  What I saw was that it actually created everything fine, but you couldn't view it afterwards so it would show that error.

**Comment by jonkoops** [comment]
Feel free to create a backport @sschu

**Comment by sschu** [comment]
There you go @jonkoops : https://github.com/keycloak/keycloak/pull/26394

**Comment by sschu** [comment]
Should I also backport this to KC22? We don't need it there but if you do, I can also create a PR for that.

**Comment by jonkoops** [comment]
Sure, if you feel like backporting it there is no harm in that.

**Comment by sschu** [comment]
Merge conflict in in three files. :( Since I don't really know what I am doing when touching Javascript, I would rather leave it at that and not backport it. Unless you tell me it's important...

**Comment by jonkoops** [comment]
Sure, no we can leave things as is. We're going to be focusing on 23 and 24 for now.
