### ISSUE TITLE
Optimization of Keycloak Dockerfile for Enhanced Efficiency and Reduced Image Size

### ISSUE THREAD

**Issue by LeFalse** [keycloak/keycloak#24222]
### Description:
This Pull Request introduces a series of optimizations to the Keycloak Dockerfile, aiming to streamline the build process, reduce the number of image layers, and potentially decrease the final image size.

#### Changes Made:
1. **Comments**: 
   - **Before**: The Dockerfile had minimal explanatory comments.
   - **After**: Added descriptive comments to each section, providing clarity on the purpose and functionality of each step.

2. **Command Grouping**: 
   - **Before**: Separate RUN commands for installing packages, adding and unpacking Keycloak, moving directories, and adjusting permissions.
   - **After**: Grouped related commands into a single RUN command to reduce the number of layers, making the build process more efficient.

3. **Cache Cleanup**: 
   - **Before**: No cache cleanup was performed after package installations.
   - **After**: Added `dnf clean all` at the end of the RUN command to clear the cache post package installation, aiming to reduce the image size.

4. **Port Exposure**: 
   - **Before**: Separate EXPOSE commands for ports 8080 and 8443.
   - **After**: Combined the ports into a single EXPOSE command for clarity and layer reduction.

#### Reason for Changes:
The primary motivation behind these changes is to enhance the efficiency of the Docker image build process. By grouping related commands, we not only reduce the number of layers but also make the Dockerfile more readable. The addition of comments aids in understanding the purpose of each step, especially for contributors unfamiliar with the Dockerfile's specifics. Lastly, cleaning up the cache post package installation can lead to a smaller image size, which is beneficial for deployments.

**Comment by vmuzikar** [comment]
Since the [PR](https://github.com/keycloak/keycloak/pull/24196) was closed, closing this issue as well. @LeFalse Feel free to reopen if you plan to work on this. Thanks.
