### ISSUE TITLE
International characters in Email - Invalid email address

### ISSUE THREAD

**Issue by nschipperbrainsmith** [keycloak/keycloak#24242]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

When creating a new user with an email address that contains an umlaut within the section before the `@` I get an error from the API:

Example email: tëst@domain.com

400 - Invalid email address

I believe this should be possible according to the: https://www.rfc-editor.org/rfc/rfc6532 but I am not sure if this is something that is caused by the way I post the email address or because of Keycloak itself. 

### Version

21.1.2

### Expected behavior

Emails with international characters should be allowed and work

### Actual behavior

Emails with international characters cause an error when created through the admin api /users endpoint

### How to Reproduce?

Post an email with an international character like an umlaut to the admin api /users endpoint.

### Anything else?

I haven't tested it with the latest release, as I couldn't find anything about it within the github issue tracker.

**Comment by mposolda** [comment]
@nschipperbrainsmith Do you please have a chance to try with latest version Keycloak 22.0.4? It is possible that this is already fixed in the latest version as we recently did some changes in this area.

**Comment by nschipperbrainsmith** [comment]
@mposolda I'll check later this week as we have an upgrade to Keycloak in the pipeline anyway so that would be something I could combine.

**Comment by mposolda** [comment]
duplicates #20878 

@nschipperbrainsmith Please re-open if you are still able to reproduce with latest Keycloak 22.0.5 release.

**Comment by nschipperbrainsmith** [comment]
I can also confirm this is fixed, my apologies.
