### ISSUE TITLE
Springboot test failing on different code lines when running with jetty94

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak#24255]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/spring

### Describe the bug

The test testErrorConditions is consistently failing but on different lines, so behaving in a flaky way but always failing

AccountLinkSpringBootTest.testErrorConditions:228 » ConditionTimeout Assertion condition defined as a org.keycloak.testsuite.util.URLAssert URL expected to begin with: http://localhost:8180/auth/realms/test/protocol/openid-connect/auth ; actual URL: http://localhost:8280/admin/LinkServlet?response=true within 10 seconds.

### Version

999-SNAPSHOT

### Expected behavior

Pass

### Actual behavior

Fails

### How to Reproduce?

Run springboot adapter test `testErrorConditions` with jetty94

**Comment by miquelsi** [comment]
Closing as Jetty 9.4 will be deprecated in KC 24.
