### ISSUE TITLE
Transient users: UX

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#24279]
### Description

#23977 Introduced transient users for brokering preview feature.

This task is to improve UX for the transient users feature. Currently there are at least the following issues with UX:

- In the admin console:
   - Transient users from brokering should be distinguishable from regular persistent users, e.g. by using a badge or label 
   - Upon logging out transient user from user detail, the admin UI crashes since the user is deleted along the way and user endpoint returns 404

### Discussion

See discussion in https://github.com/keycloak/keycloak/pull/23977

### Motivation

#11334

**Comment by ssilvert** [comment]
I'm reclassifying this as a bug since a crash is involved.  We need to fix it soon.

**Comment by ssilvert** [comment]
@hmlnarik @xianli123 

I think the idea of a badge or other identifier sounds good.  I'm wondering what the identifier would say.  Does "Transient" work or is there some other word that works better here?

**Comment by xianli123** [comment]
@ssilvert @hmlnarik 

As for the wording "Transient", we could ask Andy, our document writer, to help us. As for the label or badge, I think we could use a label and a tooltip. When hovering over the label, the tooltip would show an explanation of the "Transient". Does it make sense?

**Comment by ssilvert** [comment]
Yes.  Sounds good.  

And that's a really good idea about the tooltip.  Even if we can't come up with the perfect name for the badge the tooltip can explain it.

**Comment by xianli123** [comment]
Hi @andymunro please take a look at this issue. Do you think the `Transient` is accurate in this case?

**Comment by andymunro** [comment]
@xianli123 Transient is good.  Temporary would also work.

**Comment by xianli123** [comment]
@andymunro Ok. Thanks!

**Comment by edewit** [comment]
Changing the status as this is an Experimental feature and atm this issue (#24455) prevents me from even seeing the user screen

**Comment by ssilvert** [comment]
Spoke to @hmlnarik.  He is going to take this one.
