### ISSUE TITLE
Transient users: documentation

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#24278]
### Description

#23977 Introduced transient users for brokering preview feature.

This task is to document the transient users feature.

The necessary bits are how to enable, use the feature, how to use / enable offline sessions and the implications to the size and lifespan of supposedly transient data at rest in case of offline sessions.

### Discussion

See discussion in https://github.com/keycloak/keycloak/pull/23977

### Motivation

#11334

See discussion after https://github.com/keycloak/keycloak/pull/23977#issuecomment-1778633414

**Comment by mposolda** [comment]
For the reference: The transient users is considered "experimental" feature in Keycloak 23. The documentation is added only in markdown file https://github.com/keycloak/keycloak/blob/main/docs/transient-users.md
