### ISSUE TITLE
How to pass client secret and in keycloak 

### ISSUE THREAD

**Issue by mohamedikram7** [keycloak/keycloak#24288]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

In electron  , react i need to pass username,password client secret 
electron/renderer/keycloak.js
```
import Keycloak from 'keycloak-js';

const keycloak = new Keycloak({
  url: 'dev-url',
  realm: 'realm',
  clientId: 'id',
});

export default keycloak;
```

electron/renderer/App.tsx
```
import { useCallback, useEffect, useState } from 'react';
import './App.css';
import { KeycloakOnLoad } from 'keycloak-js';
import keycloak from './util/auth/keycloak';
import { Loader } from './components/Loader';
import { User } from '../main/types';
import { Navbar } from './components/Navbar';
import { Welcome } from './features/welcome';

const { storeActions } = window.electron;
const { getUser } = storeActions;
const initializeKeycloak = async (user: User | null) => {
  const { token, refreshToken } = user || {};
  const initOptions =
    token && refreshToken
      ? { token, refreshToken }
      : { onLoad: 'login-required' as KeycloakOnLoad };
  const result = await keycloak.init(initOptions);
  return result;
};

function App() {
  const [initialized, setInitialized] = useState<boolean>();

  const initializeApp = useCallback(async () => {
    try {
      const user = await getUser();
      const initializedKeycloak = await initializeKeycloak(user);
      if (!initializedKeycloak) {
        await keycloak.login();
      }
      setInitialized(true);
    } catch (error) {
      console.log({ error });
      setInitialized(true);
    }
  }, []);
  useEffect(() => {
    initializeApp();
  }, [initializeApp]);
  return initialized ? (
    <div>
      <Navbar />
      <Welcome />
    </div>
  ) : (
    <Loader message="App is initializing" />
  );
}
export default App;

```

### Version

22.0.4

### Expected behavior

i need to https://{base_url}/protocol/openid-connect/token =>
in body i need to pass username,password,client_secret

### Actual behavior

im getting 401:
**PAYLOAD**:
code: ""
grant_type: authorization_code
client_id: electron
redirect_uri: http://localhost:3000/index.html
![Screenshot from 2023-10-25 19-38-01](https://github.com/keycloak/keycloak/assets/95607047/cd5adb99-65f3-4373-87e3-a7f952965dce)

### How to Reproduce?

USE Client secret in pass it in electron app

**Comment by ssilvert** [comment]
@mohamedikram7 "How to" questions are best directed to our forums.  Please try to get some help there before you assume it's a bug in Keycloak.

https://www.keycloak.org/community
