### ISSUE TITLE
KC_HTTP_ENABLED=true does not work if KC_PROXY=none

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#24294]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

If I set KC_HTTP_ENABLED=true and I have KC_PROXY=none then Keycloak is not listening on http port but only on https port.

Here is a test I've made with KC_HTTP_ENABLED=true and  KC_PROXY=edge -> Keycloak is correctly listening on ports 8080 and 8443: 
![image](https://github.com/keycloak/keycloak/assets/11772429/887b9657-8b09-4cfa-9b71-e7be615d5721)

Now if I change KC_PROXY to none -> Keycloak is not listening anymore on port 8080 : 
![image](https://github.com/keycloak/keycloak/assets/11772429/fc432c43-360e-462c-9073-22dc377b6c50)

Note that I've also noticed this, which seems strange to me if KC_PROXY=none : 
![image](https://github.com/keycloak/keycloak/assets/11772429/bfe2d0f2-276c-4b88-b194-7049ecba0e06)

### Version

22.0.4

### Expected behavior

Keycloak is listening on http port

### Actual behavior

Keycloak is not listening on http port

### How to Reproduce?

Start keycloak in production mode with KC_HTTP_ENABLED=true and KC_PROXY=none

**Comment by shawkins** [comment]
I did not see the same behavior locally - with http enabled, and proxy none, both ports were listening.

On the DefaultHostnameProvider log, that appears to be an incomplete fix from https://github.com/keycloak/keycloak/issues/10627 / https://github.com/keycloak/keycloak/pull/10707 - if kc.proxy is not not set, then false is being returned as the value, but if you explicitly set none, then none is being returned and noProxy is set to false.

cc @vmuzikar @pedroigor PropertyMapper.transformValue will return a ConfigValue representing the default where the raw value here is "none", but the mapped value is false.  This makes it inconsistent when explicitly using --proxy=none as the mapped value will be none.  It seems like there may need to be a change with the default handling, or the logic in the DefaultHostnameProvider will need to check the raw value instead.

**Comment by shawkins** [comment]
Could not reproduce the core issue described.  @omasseau can you double check this is happening on latest for you?  If it is, please provide as complete of a reproducer as possible and reopen this issue.
