### ISSUE TITLE
slow loading offline tokens during start up leads to connection timeout

### ISSUE THREAD

**Issue by imashwin-v** [keycloak/keycloak#24295]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Offline tokens takes too much time to load causing transaction timeout during startup.

### Version

22.0.1

### Expected behavior

Loading tokens during startup should be faster

### Actual behavior

Its too slow causing transaction timeout when there are large number of sessions (>500K depends on DB tuning as well)

### How to Reproduce?

Create roughly around 500K offline tokens.
Load the tokens during startup

### Anything else?

The issue seems to be due to a code block in JpaUserSessionPersisterProvider.java

`     UserModel user = userSession.getUser();
        if (user != null) {
            model.setUserId(user.getId());
        }
        else if (userSession instanceof PersistentUserSessionAdapter) {
            model.setUserId(((PersistentUserSessionAdapter) userSession).getUserId());
        }
        `
        
        This block is present in the `private PersistentAuthenticatedClientSessionAdapter toAdapter(RealmModel realm, UserSessionModel userSession, PersistentClientSessionEntity entity) {` method
        
Seems like `userSession.getUser()` is being called unnecessarily here.

Changing the code to below should be optimal
`
if (userSession instanceof PersistentUserSessionAdapter) {
    model.setUserId(((PersistentUserSessionAdapter) userSession).getUserId());
}
else {
    UserModel user = userSession.getUser();
    if (user != null) {
        model.setUserId(user.getId());
    }
}
`

**Comment by rmartinc** [comment]
@imashwin-v You are right about the tuning of that stanza. What is the improvement in loading time with your change? Is it big? It's OK to send a PR if we see it is appreciable.

But take in mind that now keycloak defaults to [lazily load offline sessions](https://www.keycloak.org/docs/22.0.5/server_admin/#offline-sessions-preloading). Why are you forcing to load them on startup?

**Comment by imashwin-v** [comment]
@rmartinc The improvement reduces upto 4x the time taken to load the offline sessions on startup. 
Below is an example

<span><span class="ui-provider bfn bfo bdb bfp bfq bfr bfs bft bfu bfv bfw bfx bfy bfz bga bgb bgc bgd bge bgf bgg bgh bgi bgj bgk bgl bgm bgn bgo bgp bgq bgr bgs bgt bgu" dir="ltr">

  | With improvement | without improvement 
-- | -- | -- 
time taken for session load | 20 seconds | 80 seconds 

But take in mind that now keycloak defaults to [lazily load offline sessions](https://www.keycloak.org/docs/22.0.5/server_admin/#offline-sessions-preloading). Why are you forcing to load them on startup
 `This is a requirement from one of our clients to reduce the load on DB during each token exchange on offline token. Hence we are loading during startup and having it in cache.`

**Comment by rmartinc** [comment]
@imashwin-v OK, understood. Then just send a PR with the change. No new tests needed as they just need to work OK. Thanks for catch!

**Comment by imashwin-v** [comment]
@rmartinc  Here is the PR https://github.com/keycloak/keycloak/pull/24327

**Comment by ahus1** [comment]
@imashwin-v - thank you for this improvement. 

From a long-term perspective, we're looking into changing the Keycloak behavior about loading sessions at startup: loading all offline sessions at startup doesn't scale well: the more sessions there are, the longer it will take. The more sessions there are, the more memory Keycloak will use. 

As we're working on making Keycloak more scalable, we might focus our efforts on incremental loading of sessions on demand. Even if there is no date yet to deprecate loading sessions on startup, we might eventually consider this once we see the on-demand loading working well enough.

If you have ideas on how to improve the on-demand loading of offline sessions, we're all ears and would welcome pull requests.

**Comment by imashwin-v** [comment]
@ahus1  Thanks for the merge. Sure, I shall check on the same and let you know if i come across any potential room for improvement.
@rmartinc @martin-kanis @mposolda Thanks for the review.
