### ISSUE TITLE
Using KC_HOSTNAME_URL and KC_HOSTNAME_ADMIN_URL does not work (cannot access admin console)

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#24292]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hello,
I want to have a dedicated hostname url when login to my realms (external url) but also a different hostname url to access the admin console (internal url). 

I've simulated this on my machine by defining these two parameters  : 
KC_HOSTNAME_URL=http://localtest.com/auth
KC_HOSTNAME_ADMIN_URL=http://localhost/auth

Note that I've also defined : 
KC_HTTP_RELATIVE_PATH=/auth
KC_HTTP_ENABLED=true
KC_HOSTNAME_STRICT=false

Login to a realm (through http://localtest.com/auth....) works perfectly fine but accessing the admin console does not work.

When I try to access the admin console through http://localhost/auth/admin/ it just redirects me to : 

http://localtest.com/auth/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocaltest.com%2Fauth%2Fadmin%2Fmaster%2Fconsole%2F&state=7a666b1d-9390-4902-9c59-5dc1add757ac&response_mode=fragment&response_type=code&scope=openid&nonce=73dad348-eeff-4108-8b5a-6fe7dc198747&code_challenge=5YdXZ6cjx80h1KTfPnNVcy4wqHcdR6tYMMZx53x9zj8&code_challenge_method=S256

and I of course get an 'Invalid parameter: redirect_uri' message.

So that this means that we cannot have a given hostname url for our realms and a different hostname url for the admin console ?
Then what is the point of having two dedicated parameters KC_HOSTNAME_URL and KC_HOSTNAME_ADMIN_URL ?

Here is the results of http://localhost/auth/realms/master/hostname-debug : 

![image](https://github.com/keycloak/keycloak/assets/11772429/2fde0cd1-13a3-447b-8a95-4397fc93dd38)

Here is the results of http://localtest.com/auth/realms/master/hostname-debug : 

![image](https://github.com/keycloak/keycloak/assets/11772429/223a0cbe-5acd-4abb-b757-ef53f801a522)

### Version

22.0.4

### Expected behavior

I can access the admin console through http://localhost/auth/admin/

### Actual behavior

Trying to access the admin console through http://localhost/auth/admin/ just redirects me to the wrong url

### How to Reproduce?

Start keycloak in production mode by setting this env variables : 

KC_HOSTNAME_URL=http://localtest.com/auth
KC_HOSTNAME_ADMIN_URL=http://localhost/auth
KC_HTTP_RELATIVE_PATH=/auth
KC_HTTP_ENABLED=true
KC_HOSTNAME_STRICT=false

Note localtest.com is pointing on 127.0.0.1 in the hosts file.

**Comment by ssilvert** [comment]
Have you tried adding another valid redirect URI to the security-admin-console client?

This doesn't sound like a bug but rather a configuration problem.  I'm fairly certain that others have done what you are trying to do.  Please try getting some help in the [community](https://www.keycloak.org/community) before we continue.  If you do find that there is a bug we can reopen this issue and investigate further.

https://www.keycloak.org/community
