### ISSUE TITLE
User attribute array data gets stored as comma-separated value if no specific input type annotation present

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#24318]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When a user attribute value contains multiple values and no annotation is set to render it as multi-value field, it is rendered as text field with comma-separated string. Editing this string causes the comma separated string value to be stored.
The original array of values is replaced with a single value.

![screen-record](https://github.com/keycloak/keycloak/assets/789496/8f593ffb-a26b-498d-bb46-5e3b1be834ca)

### Version

22.0.5

### Expected behavior

The attribute with multipe-values should not get lost.

### Actual behavior

A comma separated string is stored.

### How to Reproduce?

1) Store multiple values in an attribute of a user, e.g. by 

 - configuring input type 'multiselect'
 - update a user and add two values
 - remove input type annotation

2) Update the user. The input is rendered as simple text field.

![image](https://github.com/keycloak/keycloak/assets/789496/5df5e068-8ddb-4c3f-a294-6d6c77340a21)

3) Add an entry as if you would believe it should be done (",newentry") and save the user

### Anything else?

This bug may cause accidental data corruption by Admins.

Thought that this bug was already reported and fixed in #20837. 
Maybe it was re-introduced with #23911?

**Comment by ssilvert** [comment]
@jbman So what is happening under the covers is that the value of an attribute is always an array.  But if you haven't specified a type, we always assume you just want simple input.  IMO, you should only be seeing the first value and the rest are ignored.

@edewit I'm not sure what we can do about this problem except we should probably only allow the first value to be edited.  So we only display the first value in the array.  When it is edited, only the first value is changed.  Then at least nothing would be corrupted.

Another possibility is that if we see a second value in the array then we assume it is multi-valued.  But I don't like that solution because there is no way to tell if ["foo"] was meant to be single value or multi value.  You really need to specify.

**Comment by jbman** [comment]
Hi @ssilvert, thanks for taking a look. I think there's nothing wrong with the option you mentioned: Multiselect rendering is used as the default, if the array contains more than one value. 

This allows to to view and edit an existing multi-entry array, without the need to specify an annotation upfront. It's just about preserving the multi-value data and preserving the ability to view and edit the data. The feature to add a second value to a non-annotated attribute isn't needed.

**Comment by edewit** [comment]
This is fixed in the nightly when there is no inputType, but a existing array as value it's rendered as:
![image](https://github.com/keycloak/keycloak/assets/51133/6f6fa059-6958-4c94-9f35-5e6482f86c40)

**Comment by ssilvert** [comment]
> Hi @ssilvert, thanks for taking a look. I think there's nothing wrong with the option you mentioned: Multiselect rendering is used as the default, if the array contains more than one value.
> 
> This allows to to view and edit an existing multi-entry array, without the need to specify an annotation upfront. It's just about preserving the multi-value data and preserving the ability to view and edit the data. The feature to add a second value to a non-annotated attribute isn't needed. If admins deletes one value, and save, they could not add it again. It just needs to be ensured that multiselect rendering is kept while editing. They should be able to add an item again before saving.

I guess that's fine.  Either way there is no data corruption.  It's just a little weird that some users will see single value and others will see multi-select.

We really need a way to encourage admins to specify an input type.
