### ISSUE TITLE
Keycloak tables not getting created

### ISSUE THREAD

**Issue by thaza-cast** [keycloak/keycloak#24345]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

When installing keycloak, the tables are not getting created. 

### Version

1.4.0

### Expected behavior

tables should get created

### Actual behavior

tables get created

### How to Reproduce?

install keycloak

### Anything else?

no

**Comment by jonkoops** [comment]
Sorry, but this issue doesn't contain enough information to reproduce your problem. When reporting an issue please try to provide a minimal an reproducible example, and test it on the latest version of Keycloak.

**Comment by thaza-cast** [comment]
I cannot use the latest version of keycloak.. we can only use one version which is - 1.4.0 in our company. 
It just doesnt install any of your tables.

**Comment by thaza-cast** [comment]
![image](https://github.com/keycloak/keycloak/assets/65299573/921da631-c4b9-4fe3-968c-620f29ba54f9)

**Comment by jonkoops** [comment]
> I cannot use the latest version of keycloak.. we can only use one version which is - 1.4.0 in our company.

We do not support this version of Keycloak, it is also at risk of several critical security issues. If you need support, please install the latest version of Keycloak.
