### ISSUE TITLE
deleteRoleMapping in provider is not being called

### ISSUE THREAD

**Issue by juanvaler-gnoss** [keycloak/keycloak#24356]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

adapter/jee

### Describe the bug

We have created a provider for Keycloak (v22.0.3) and we have overwritten the vast majority of the methods of the class AbstractUserAdapter ([AbstractUserAdapter (Keycloak Docs Distribution 21.1.2 API)](https://www.keycloak.org/docs-api/21.1.2/javadocs/org/keycloak/storage/adapter/AbstractUserAdapter.html)). We are federating users and roles. We can get the users, the roles, the role mapping for a user and the list of users in a role through the provider. We can add users, add roles to users, etc. through the provider too.

But when we try to remove a federated role from a federated user, the Keycloak interface throws an error like this: “Could not remove the scope mapping Role not found”. There isn’t any error in the Keycloak logs. We have implemented the method deleteRoleMapping​ of the AbstractUserAdapter class, but nobody is calling our method. This error occurs only in a federated role with federated users. With a Keycloak User it works properly.

Are we missing something? Is it possible that there is a bug on Keycloak?

We have try the same functionality with groups (methods joinGroup and leaveGroup of AbstractUserAdapter class) and it works well.

Thank you very much

### Version

22.0.3

### Expected behavior

We create realm roles dynamically from our custom provider using the method RealmModel.addRole and it works correctly. Then we assign those roles to our federated users calling the implemented method grantRole, and this flow is also working properly.
When we remove a federated role from a federated user, the deleteRoleMapping method of our implementation of the class AbstractUserAdapter from our provider should be called in order to remove the role to the selected federated user in our database, just like the grantRole method. 

### Actual behavior

When we remove a federated role from a federated user, the deleteRoleMapping​ method of our implementation of the class AbstractUserAdapter isn't being called by nobody, and an error message is shown in the keycloak administration page: “Could not remove the scope mapping Role not found”

### How to Reproduce?

1. Create a provider for keycloak and implements the methods for federate users and roles (setAttribute, getClientRoleMappings, getClientRoleMappingsStream, appendDefaultGroups, getGroups, getGroupsStream, getGroupsInternal, isMemberOf,  getUsername, setUsername, getFirstName, setFirstName, getLastName, setLastName, getEmail, setEmail, setEnabled, credentialManager, isEnabled, getCreatedTimestamp, setCreatedTimestamp, getId, setId, setPassword, getPassword, getAttributes, getAttributeStream, removeRequiredAction, appendDefaultRolesToRoleMappings, getRoleMappings, getRoleMappingsStream, grantRole, hasDirectRole, hasRole, deleteRoleMapping, getRoleMappingsInternal). Deploy it in a keycloak instance and add a new provider from the user federation section of the admin area. 
3. Go to Users page and select a federated user
4. Go to Role mapping tab and click in Assign role
5. Check a federated rol and click Assign
6. Uncheck the federated rol
7. The error "Could not remove the scope mapping Role not found" appears

### Anything else?

Every implemented method is working as intented, except deleteRoleMapping, which is never called.

**Comment by sguilhen** [comment]
Hi @juanvaler-gnoss, is it possible that you should be extending from `AbstractUserAdapterFederatedStorage` instead of `UserAdapter`? If you check [the quickstarts](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension), both `user-storage-simple` and `user-storage-jpa` examples extend from this class instead.
