### ISSUE TITLE
Adding scopes via registration_client_uri does not work when using Dynamic Client Registration

### ISSUE THREAD

**Issue by DuncanDoyle** [keycloak/keycloak#24361]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

I'm using Dynamic Client Registration to register new Clients/Service Accounts to access back-end APIs. In my use-cases, I use scopes, that map to different API-Products to grant access to these APIs. This means that I need to be able to add scopes to an existing Client to give them access to new APIs.

When I register a new client using DCR, I can specify the scopes I want this client to have in the request:
```
{
   "application_type": "native",
   "client_name": "My Cool Client",
   "logo_uri": "https://client.example.com/logo.png",
   "contacts": ["duncan.doyle@example.com"],
   "grant_types": ["client_credentials"],
   "scope": "Catstronauts"
}
```
Sending this request to the OIDC registration endpoint correctly creates my Client with the "Catstronauts" scope as its single scope.

When I later try to add the "Petstore" scope using the "registration_client_uri" and "registration_access_token", that were returned in the response when I registered the client, using the following PUT request, the "Petstore" scope does not get added:
```
{
   "client_id": {generated-id-when-I-registered-my-client},
   "client_name": "My new client name",
   "scope": "Catstronauts Petstore"
}
```

However, the `client_name` does get changed, which shows that the request is getting processed.

Also, I get a `200` as the response code and there are no errors in the Keycloak logs.

Note that in the "Client Registration -> Authenticated access policies -> Allowed Client Scopes", I've listed all the scopes I want to configure.

### Version

22.0.5

### Expected behavior

When I add a scope to a client via a `PUT` operation to its `registration_client_uri`, the scope should be added to the client.

### Actual behavior

The scope does not get added to the client.

### How to Reproduce?

Register a new client via the OIDC Registration Endpoint (e.g. http://{keycloak}/realms/master/clients-registrations/openid-connect), for example by sending the following `POST` request:
```
{
   "application_type": "native",
   "client_name": "My Cool Client",
   "logo_uri": "https://client.example.com/logo.png",
   "contacts": ["duncan.doyle@example.com"],
   "grant_types": ["client_credentials"],
   "scope": "Catstronauts"
}
```

From the response, grab the `registation_client_uri` and `registration_access_token`. Send a `PUT` request to the `registration_client_uri`, trying to add a scope:
```
{
   "client_id": {generated-id-when-I-registered-my-client},
   "client_name": "My new client name",
   "scope": "Catstronauts Petstore"
}
```

Scope does not get added.

### Anything else?

I know that there are other Keycloak REST APIs I can use to add a scope to a Client, but I would like to use the DCR standard, as my platform needs to support multiple IdPs, and hence I would like to rely on this standard as much as possible.

**Comment by souravs17031999** [comment]
@DuncanDoyle I was not even able to add the scopes via DCR and I had to first create that scope manually from admin console and then also add it to whitelisted scopes in the client registration policies, then only it was allowing me to add it via DCR.

One more thing, which platform are you using to send scopes as well in DCR ? is it some custom component or standard platform ?

**Comment by graziang** [comment]
Reproduced this, and seems to be a valid issue because scopes are not updated during a client update request. Looking at [RFC](https://datatracker.ietf.org/doc/html/rfc7592#section-2.2), I see no reason to ignore the scope update. We can take this opportunity to better investigate the validation of the client update request. 
@mposolda WDYT? Am I missing something?
