### ISSUE TITLE
keycloak-admin-client isn't backward compatible

### ISSUE THREAD

**Issue by sbergandy** [keycloak/keycloak#24393]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/api

### Describe the bug

- Keycloak Server version: 20.0.3
- Java client version: keyloack-admin-client-22.0.5.jar

When updating a `org.keycloak.representations.idm.UserRepresentation` with `org.keycloak.admin.client.resource.UserResource#update` I receive 400 bad request. The reason for this is additional `userProfileMetadata` field in `UserRepresentation` which isn't not processable for Keycloak Server 20.0.3

### Version

20.0.3

### Expected behavior

Response 204 No Content and ignoring unknown fields.

### Actual behavior

400 bad request.

### How to Reproduce?
PUT below HTTP request to Keycloak Server 20.0.X

```http
PUT https://<keycloak-url>/admin/realms/<realm-name>/users/<user-id>
Content-Type: application/json
Authorization: Bearer <token>
{
  "self": null,
  "id": "<id>",
  "origin": null,
  "createdTimestamp": 1698511475809,
  "username": "<username>",
  "enabled": true,
  "totp": false,
  "emailVerified": true,
  "firstName": "<first name>",
  "lastName": "<last name>",
  "email": null,
  "federationLink": null,
  "serviceAccountClientId": null,
  "attributes": [],
  "credentials": null,
  "disableableCredentialTypes": [],
  "requiredActions": [],
  "federatedIdentities": null,
  "realmRoles": null,
  "clientRoles": null,
  "clientConsents": null,
  "notBefore": 0,
  "applicationRoles": null,
  "socialLinks": null,
  "groups": null,
  "access": {
    "manageGroupMembership": true,
    "view": true,
    "mapRoles": true,
    "impersonate": false,
    "manage": true
  },
  "userProfileMetadata": {
    "attributes": null
  }
}
```

**Comment by vmuzikar** [comment]
jFTR – this is [coming from Quarkus](https://github.com/quarkusio/quarkus/discussions/36766) and it's related to the cyclic dependency that we have with them.

CC @pskopek

**Comment by rmartinc** [comment]
@sbergandy I think this has been always this way (I remember issues about this when keycloak was in version 3 or 4) and I don't think we want to maintain the backwards compatibility. The `keycloak-admin-client` is mainly something we use to test the keycloak server. You have to use same versions.

**Comment by gmuellerinform** [comment]
Hi! This is actually bad news. We need to access multiple Keycloak instances with different versions. Could you either make userProfileMetadata optional on server side, or add a flag to ommit userProfileMetadata in the client? Otherwise we'd need to reimplement the whole client.

Thanks!

**Comment by islglad** [comment]
@gmuellerinform Additionally, they could add `@JsonIgnoreProperties(ignoreUnknown = true)` to their Representation objects. However, I saw the previous comment about them not wanting to maintain backwards compatibility.

**Comment by buianhtai** [comment]
Have you solved this issue @gmuellerinform ? Upgrading to the latest Keycloak server version is not a good choice for us either

**Comment by geromueller** [comment]
Hi! Yes, by not using multiple keycloak versions :-/
