### ISSUE TITLE
UMA 2 not evaluating as expected when using permission tickets

### ISSUE THREAD

**Issue by BlackVoid** [keycloak/keycloak#24422]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

When using permission tickets to grant access to resources with scopes, it does not work as intended if "User-Managed access enabled" is not enabled on the resource.

Example case:
User has access to resource-a [scope-a] and resource-c [scope-b] through [permission ticket API](https://www.keycloak.org/docs/latest/authorization_services/index.html#creating-permission-ticket-2)

Evaluation without resource specified (UMA enabled on resource) - working as intended:
```
"authorization": {
  "permissions": [
    {
      "scopes": [
        "scope-a"
      ],
      "rsid": "ebb2f0cd-cd0b-41e6-83fa-27e90a80b151",
      "rsname": "resource-a"
    },
    {
      "scopes": [
        "scope-b"
      ],
      "rsid": "83b7804b-08c6-48dd-ae30-c621df93933d",
      "rsname": "resource-c"
    }
  ]
},
```

Evaluation without resource specified (UMA disabled on resource-c) - not working as intended:
```
"authorization": {
  "permissions": [
    {
      "scopes": [
        "scope-a"
      ],
      "rsid": "ebb2f0cd-cd0b-41e6-83fa-27e90a80b151",
      "rsname": "resource-a"
    },
    {
      "rsid": "83b7804b-08c6-48dd-ae30-c621df93933d",
      "rsname": "resource-c"
    },
    {
      "scopes": [
        "scope-b"
      ],
      "rsid": "83b7804b-08c6-48dd-ae30-c621df93933d",
      "rsname": "resource-c"
    }
  ]
},
```

Note that resource-c is shown twice in the permissions list.

Evaluation with resource-c specified (UMA enabled on resource) - working as intended:
```
"authorization": {
  "permissions": [
    {
      "scopes": [
        "scope-b"
      ],
      "rsid": "83b7804b-08c6-48dd-ae30-c621df93933d",
      "rsname": "resource-c"
    }
  ]
},
```

Evaluation with resource-c specified (UMA disabled on resource) - not working as intended:
```
"authorization": {
  "permissions": [
    {
      "rsid": "83b7804b-08c6-48dd-ae30-c621df93933d",
      "rsname": "resource-c"
    }
  ]
},
```

Note that resource-c is only shown once and the scope is missing.

This behavior changes to the correct one as soon as UMA is enabled on the resource again, so it does not matter when the access was delegated through the permission ticket request.

### Version

22.0.5 (also present in nightly as of 31 oct)

### Expected behavior

Delegation of access through PT requests should probably be rejected when UMA is disabled on the resource that the request targets.

### Actual behavior

Request is accepted even though the resource does not have UMA enabled and permission evaluation is not working as intended. For evaluation without a resource as target the resource is shown twice, one entry without a scope and one entry with the expected scope. For evaluation with a target resource the scope is missing.

### How to Reproduce?

1. Create a scope ex. scope-a
2. Create a resource ex. resource-a with scope-a and UMA disabled
3. Delegate access to any user using an access token using the client_credentials flow (will succeed even though UMA is disabled)
```
curl -X POST \
     http://${host}:${port}/realms/${realm_name}/authz/protection/permission/ticket \
     -H 'Authorization: Bearer '$access_token \
     -H 'Content-Type: application/json' \
     -d '{
       "resource": "{resource_id}",
       "requester": "{user_id}",
       "granted": true,
       "scopeName": "scope-a"
     }'
```
4. Evaluate the permissions on the user you delegated access to without specifying the resource (the permission part of the response will list resource-a twice, one entry with scope and one without)
5. Evaluate the permissions on the user you delegated access to with resource-a specified (the permission part of the response will list resource-a once but without the scope)
6. Repeat step 4 and 5 with UMA enabled on resource-a and the response will be identical with the expected resource and scope

**Comment by BlackVoid** [comment]
Something simple such as this would at least inform the user of UMA not being enabled on the resource, but does not prevent it from being disabled after the ticket has been created.

I can create a PR for it, however I did not find any tests for this part of the code. If tests are needed for the PR I'll need some guidance since I'm not very familiar with this codebase.

```git
diff --git a/services/src/main/java/org/keycloak/authorization/protection/permission/PermissionTicketService.java b/services/src/main/java/org/keycloak/authorization/protection/permission/PermissionTicketService.java
index 90d094e4b09..b8b6eb72dde 100644
--- a/services/src/main/java/org/keycloak/authorization/protection/permission/PermissionTicketService.java
+++ b/services/src/main/java/org/keycloak/authorization/protection/permission/PermissionTicketService.java
@@ -87,6 +87,9 @@ public class PermissionTicketService {
         
         if (!resource.getOwner().equals(this.identity.getId()))
             throw new ErrorResponseException("not_authorised", "permissions for [" + representation.getResource() + "] can be only created by the owner", Response.Status.FORBIDDEN);
+        if (!resource.isOwnerManagedAccess())
+            throw new ErrorResponseException("invalid_permission", "permission can only be created for resources with user-managed access enabled", Response.Status.BAD_REQUEST);
+
         
         UserModel user = null;
         if(representation.getRequester() != null)
```

**Comment by pedroigor** [comment]
@BlackVoid Thanks for the PR. LGTM.
