### ISSUE TITLE
User profile behaves different in keycloak 22.0.5

### ISSUE THREAD

**Issue by ioemat** [keycloak/keycloak#24420]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

User profiles are having required fields *firstName* and *lastName* even though they are not configured. (Issue starts with 22.0.5, works fine in 22.0.4)

### Version

22.0.5

### Expected behavior

* *Update Account Information* page presents parameters configured in the custom profile (it works likes this in 22.0.4)

![image](https://github.com/keycloak/keycloak/assets/43614225/0c5989ee-0d53-4da1-a2f2-08b6ef278e6a)

### Actual behavior

* *Update Account Information* page presents parameters configured in the custom profile plus requires *firstName* and *lastName* to be entered

![image](https://github.com/keycloak/keycloak/assets/43614225/6dac7188-5296-4db1-bd63-3d2cf6faafbe)

### How to Reproduce?

* Create a realm
* in realm settings enable user profile
* configure user profile using e.g. this json file
```
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {},
        "up-username-not-idn-homograph": {}
      }
    },
    {
      "name": "email",
      "displayName": "${email}",
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      }
    },
    {
      "name": "foo",
      "displayName": "",
      "permissions": {
        "edit": [
          "admin",
          "user"
        ],
        "view": [
          "admin",
          "user"
        ]
      },
      "annotations": {},
      "validations": {},
      "group": null,
      "required": {
        "roles": [
          "admin",
          "user"
        ]
      }
    },
    {
      "name": "bar",
      "displayName": "",
      "permissions": {
        "edit": [
          "admin",
          "user"
        ],
        "view": [
          "user"
        ]
      },
      "annotations": {},
      "validations": {},
      "group": null,
      "required": {
        "roles": [
          "admin",
          "user"
        ]
      }
    }
  ]
}
```
* in *Authentication*/*Required actions* enable *Verify Profile*
* try to register a user in this realm and see the user profile dialog

### Anything else?

Workaround:

* specify *firstName* and *lastName* in your custom user profile configuration and mark it as "not required"

**Comment by ioemat** [comment]
Seems to be related to #23916

**Comment by pedroigor** [comment]
@ioemat @sschu Yeah, it is not intended. I'll provide a fix for it.

**Comment by jonkoops** [comment]
@pedroigor we will no longer be doing patch releases for v22, so this will likely have to come along in v23. I'll change the milestone for now.
