### ISSUE TITLE
User Profile: User create/update screens differ between master or realm specific admin console

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#24421]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When creating/updating a user in the master admin console (`/admin/master/console/`) the user profile fields are respected and rendered. There also is no more attributes tab shown on the user details.

When accessing the realm specific admin console (e.g. `/admin/test/console`) with a user that has the roles `manage-users`, `query-users` and `view-users` it seems like the user profile configuration is not respected in the UI. The attributes tab is rendered and no dedicated inputs are displayed on the screens for creating or updating the user. In the network tab I can see that the calls to `/admin/realms/test/users/profile`, `/admin/realms/test/users/profile/metadata` and `/admin/realms/test/users/xyz...?userProfileMetadata=true` are actually being made and return a valid user profile configuration.

Shouldn't this be respected in the UI?

### Version

22.0.5

### Expected behavior

User Profile configuration should be respected in the realm specific admin console.

### Actual behavior

User Profile configuration is ignored in the realm specific admin console.

### How to Reproduce?

1. Create a new realm
2. Enable user profile and create a custom attribute
3. Create an admin user with at least these roles:  `manage-users`, `query-users` and `view-users` (imo query/view should already be enough) and add credentials
4. Open the realm specific account-console via clients -> security-admin-console (home url)
5. Sign in as the created admin user
6. Press create user and see that the custom attribute input is not rendered. 
7. Create the user and see on the details screen that the custom attribute input is not rendered and the attributes tab is still present.

**Comment by ssilvert** [comment]
@edewit I have reproduced this.  I think the problem is that the call to get the realm info is just returning `{"realm":"test","registrationEmailAsUsername":false}`.  So you have no way to know if User Profile is enabled.  I thought we fixed that already?

**Comment by edewit** [comment]
I can't reproduce this @antikalk can you retest this on the latest nightly

**Comment by antikalk** [comment]
@edewit I just checked it with the nightly and it seems to be fixed there:
<img width="673" alt="image" src="https://github.com/keycloak/keycloak/assets/1793007/48b3a6d8-6dd7-443d-a7ce-940298d36ee9">
