### ISSUE TITLE
StackOverflowError when creating cycles in group hierarchy 

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#24427]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

storage

### Describe the bug

It's possible to have a group hierarchy with cycles (when data would become invalid in external provider). Once it's done keycloak throws 500 with StackOverflowError because there is infinite loop in the code.

### Version

22.0.5

### Expected behavior

Keycloak prevents a creation of cycles in group hierarchy and if StackOverflowError is detected (due to external provider's data becomes invalid) it should react and throw more specific error.

### Actual behavior

see description

### How to Reproduce?

Create group hierarchy g1 -> g2 -> g3 -> g1

**Comment by sschu** [comment]
@vramik How did you create the cycle? When I try to move g1 to a child of g3, I get a 500.
