### ISSUE TITLE
Resources Scopes in clients are appearing as undefined

### ISSUE THREAD

**Issue by yashmjain26** [keycloak/keycloak#24428]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authorization-services

### Describe the bug

![image](https://github.com/keycloak/keycloak/assets/123618103/27406a11-c327-48c1-8196-7defbf3392c1)
)

When utilizing the Client Authorization Service, an issue has been identified wherein the scope variable appears as undefined. 

### Version

20.0.3

### Expected behavior

The scope variable should be defined and accessible for proper functioning.

### Actual behavior

The scope variable is undefined, which can lead to errors, unexpected behavior, or security issues when working with the Client Authorization Service.

### How to Reproduce?

Access the Client Authorization Service.

**Comment by jonkoops** [comment]
Hi @yashmjain26. We no longer support Keycloak 20, feel free to open up a new issue if this is reproducible in the latest or nightly version of Keycloak.
