### ISSUE TITLE
System crash if using multiple CRLs from different CAs that have the same issuer chain

### ISSUE THREAD

**Issue by cstrem** [keycloak/keycloak#24439]
### Before reporting an issue

- [X] I have searched existing issues
- [X] #25999

### Area

core

### Describe the bug

Using X509 authentication flow and using CRL checking. Works when listing a single CRL, however listing multiple CRLs from different CAs that have the same CA chain cause CPU usage to max out and the system to crash. 

### Version

22.0.5

### Expected behavior

Multiple CRLs are checked correctly

### Actual behavior

CPU usage spikes to 100% and the application crashe

### How to Reproduce?

Add multiple CRLs from different CAs that have the same CA chain to the X509 authentication flow. Then try to authenticate with a valid X509 certificate. 

### Anything else?

Extremely similar behavior as observed in #20725, the difference being the CRLs are from different CAs, however the CAs themselves were issued by the same root CAs.

**Comment by pedroigor** [comment]
Might be related to this fix proposal https://github.com/keycloak/keycloak/pull/25863. @stustison Wdyt?

**Comment by stustison** [comment]
> Might be related to this fix proposal #25863. @stustison Wdyt?

@pedroigor My setup for that PR was very similar to what is described here in the bug. I was using 4 CRLs from different CAs that had the same root CA. My best guess is that they are actually hitting an out of memory error from the CRLs being so large, which causes the CPU spike. I'd need to know more about which CRLs they are trying to use, but I'd be happy to try those CRLs against my PR if they can provide that. @cstrem ??

**Comment by pedroigor** [comment]
Yeah, it would be nice to validate your changes using this issue as it might be related. @cstrem If you can provide some material it would be great.

**Comment by mposolda** [comment]
@cstrem Nobody else reported this issue since it was reported. It is possible that it is fixed in latest version. Can you please doublecheck with the latest Keycloak version if the issue still persists?
