### ISSUE TITLE
Email-verified checkbox not visible anymore when user profile is enabled

### ISSUE THREAD

**Issue by pkeuter** [keycloak/keycloak#24453]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When enabling the user profile on the General-tab in Realm settings, the user edit-page doesn't show a "email verified" toggle button anymore. Over [here](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user/UserForm.tsx#L189) I can see that another component is being rendered when the user profile is enabled, but [here](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/user/UserProfileFields.tsx) it's not visible. Maybe because this field should be provided by the database, but I am not sure.

### Version

22.0.5

### Expected behavior

An "email-verified"-checkbox should be available regardless of the "user profile enabled"-switch.

### Actual behavior

The "email-verified"-checkbox is not available

### How to Reproduce?

- Enable the feature `account3`, 
- Enable the "user profile" with the switch in Realm settings,
- Go to a users details tab. 

The checkbox won't be here.

**Comment by humpfhumpf** [comment]
Same as #17870, which fix seems never worked.

**Comment by jonkoops** [comment]
I am able to reproduce this issue in the latest nightly version of Keycloak.

**Comment by jonkoops** [comment]
We're no longer expecting any new releases in the 22.x series to my knowledge, so this will come along in 23.
