### ISSUE TITLE
Tabbing is not working in forms inside dropdown

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak#24464]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Tabbing is not working in the following forms inside dropdown:
1. User attribute search form in Users
2. Effective message bundles search form in Realm-settings/Localization/Effective message bundles tab
3. User & Admin event search forms in Events

### Version

22.0.5

### Expected behavior

Tabbing is working as expected.

### Actual behavior

Tabbing is not working.

### How to Reproduce?

1. Go to users, select attribute search/select attributes, click `enter`, and try to tab to go to the first form field. Observe that tabbing is not possible. 
2. Go to realm settings > localization > effective message bundles tab and use tab to open and navigate through fields. Observe that tabbing is not possible. 
3. Go to events > user events tab to open the user events search form and navigate through fields. Observe that tabbing is not possible. This is also true for the admin events search form.

**Comment by agagancarczyk** [comment]
hi @ssilvert I have investigated this issue thoroughly. It seems to be patternly issue https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Dropdown/Dropdown.tsx#L100C69-L100C69. Would you like me to raise it with them? Thanks!

**Comment by ssilvert** [comment]
@agagancarczyk Yes.  Link to this issue and make sure we follow up.  This is an ugly one that we don't want to leave alone.
