### ISSUE TITLE
Look if checks in IntrospectionEndpoint can be simplified

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#24466]
### Description

This is just a minor task to doublecheck if we can simplify some checks triggered from introspection endpoint and `AccessTokenIntrospectionProvider`. It looks that some checks are done multiple times. For example `AuthenticationManager.isSessionValid()` is called from:
- `TokenManager.checkTokenValidForIntrospection`
- and from `UserSessionUtil.findValidSession`

We can see if we can cleanup this a bit (and maybe remove `TokenManager.checkTokenValidForIntrospection` at all?). 

At the same time, care should be taken as it is always better to do some checks multiple times rather than zero time :-)

**Comment by dmol5E** [comment]
Hello keycloak team. I see you deleted session refresh from introspection.
org.keycloak.protocol.oidc.TokenManager#checkTokenValidForIntrospection(...)
```java
            if (updateTimestamps && valid) {
                int currentTime = Time.currentTime();
                userSession.setLastSessionRefresh(currentTime);
                if (clientSession != null) {
                    clientSession.setTimestamp(currentTime);
                }
            }
```
@mposolda Was it done on purpose or it was deleted accidently?
Our use-cases are based on user session refresh on token introspection and now we get failures here.
Some of our users still uses implicit flow and we refreshed session every time by checking token using introspection and it prolonged session. Now it looks like we are restricted by SSO Session Idle and neve reach SSO Session Max
