### ISSUE TITLE
Remove non-unique `id` attributes from `webauthn-authenticate.ftl`

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#24462]
The `webauthn-authenticate.ftl` template has several `id` attributes that are inside of a loop, these are therefore likely not unique, which is a violation of the HTML standard. The following `id` attributes will have to be made globally unique, or more likely converted to `class` attributes:

- [`kc-webauthn-authenticator`](https://github.com/keycloak/keycloak/blob/e96d6b38a8710366b7b38f8d3a895854f9e4f946/themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl#L33)
- [`kc-webauthn-authenticator-label`](https://github.com/keycloak/keycloak/blob/e96d6b38a8710366b7b38f8d3a895854f9e4f946/themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl#L38C50-L38C81)
- [`kc-webauthn-authenticator-transport`](https://github.com/keycloak/keycloak/blob/e96d6b38a8710366b7b38f8d3a895854f9e4f946/themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl#L44)
- [`kc-webauthn-authenticator-created-label`](https://github.com/keycloak/keycloak/blob/e96d6b38a8710366b7b38f8d3a895854f9e4f946/themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl#L56)
- [`kc-webauthn-authenticator-created`](https://github.com/keycloak/keycloak/blob/e96d6b38a8710366b7b38f8d3a895854f9e4f946/themes/src/main/resources/theme/base/login/webauthn-authenticate.ftl#L59)

**Comment by klfregoso** [comment]
I'll take a stab at this

**Comment by jonkoops** [comment]
Thanks @klfregoso, I will assign this to you.

**Comment by jonkoops** [comment]
I'll remove the assignee so someone else can pick this up :smile:

**Comment by DineshSolanki** [comment]
Hi @jonkoops Could you please review the PR.
