### ISSUE TITLE
TCPPING: Unable to use any JGroups configuration mechanisms provided in properties

### ISSUE THREAD

**Issue by gertjankoorn** [keycloak/keycloak#24469]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

infinispan

### Describe the bug

Custom transport stack tcpping is not picked up, which gives the warning: 
`Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!`
Now the default stack is used, , which uses multicast to find the other nodes, which will not be possible in the production environment. This will be on a Nomad environment with Consul connect, on which each kc instance has a specific upstream port. That's why i need to be able to define the specific IPs + ports of the instances running.
I have seen for example https://github.com/keycloak/keycloak/issues/20397, but that was fixed with the `--optimized` flag, which i already use. 

I have created a custom cache-ispn.xml file in /opt/keycloak/conf/cache-ispn-tcp.xml:
```
    <jgroups>
        <stack name="tcpping" extends="tcp">
          <TCP external_addr="${TCP_BIND_PORT}" bind_addr="${KC_BIND_ADDR}" bind_port="${TCP_BIND_PORT}" />
          <TCPPING initial_hosts="${INITIAL_HOSTS}"
                   max_dynamic_hosts="0"
                   port_range="0"
                   stack.combine="REPLACE"
                   stack.position="MPING"/>
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="tcpping"/>
    ...
```
The `${TCP_BIND_PORT}` and `${INITIAL_HOSTS}` are replaced in a custom-entrypoint script, which translates to the actual ports, addresses in the file at startup. The other contents of the file are taken from the same image version.

My Dockerfile build step:
```
COPY cache-ispn.xml /opt/keycloak/conf/cache-ispn-tcp.xml
ENV KC_CACHE_CONFIG=cache-ispn-tcp.xml
ENV KC_CACHE=ispn
```

In the docker-compose file for both kc instances:
```
      # ENV VARS
      - KC_BIND_ADDR=<IP_OF_KC_INSTANCE_1>
      - INITIAL_HOSTS="<IP_OF_KC_INSTANCE_1>[<PORT_OF_KC_INSTANCE_1>],<IP_OF_KC_INSTANCE_2>[<PORT_OF_KC_INSTANCE_2>]"
      - TCP_BIND_PORT=<PORT_OF_KC_INSTANCE_1>

      # Start command
      - start --optimized
 ```

When i change the tcpping configuration with jbdc_ping, i don't see this message and the instances are indeed put in the database. However, the discovery is of course still using multicast, so i do need tcpping. 
```
  <jgroups>
    <stack name="jdbc-ping-tcp" extends="tcp">
      <JDBC_PING connection_driver="com.mysql.cj.jdbc.Driver"
                 connection_username="username" connection_password="password"
                 connection_url="jdbc:mysql://mysql/keycloak?useSSL=false"
                 initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data blob, PRIMARY KEY (own_addr, cluster_name) )"
                 info_writer_sleep_time="500"
                 remove_all_data_on_view_change="true"
                 stack.combine="REPLACE"
                 stack.position="MPING" />
    </stack>
  </jgroups>
```

I feel like it might be some issue in my configuration, but i fail to see what. 
Also, if anyone has a suggestion on how to solve this easier on Nomad with Consul connect, feel free.

### Version

22.0.3

### Expected behavior

For Keycloak to pickup the custom stack and say in the logs: `Starting JGroups channel ISPN with stack 'tcpping'`.

### Actual behavior

No custom stack is used and default stack is used.

### How to Reproduce?

See above.

**Comment by sschu** [comment]
Did you also tell Keycloak to use your cache configuration like https://www.keycloak.org/server/all-config?q=cache-config-file ?

**Comment by gertjankoorn** [comment]
Right, that was it..! I see that i used that flag for the JBDC config, but not for this one. Thanks!
