### ISSUE TITLE
User status shows as "-" when user is enabled

### ISSUE THREAD

**Issue by alice-wondered** [keycloak/keycloak#24470]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

User status is showing in the user data table as "-" when the user is enabled, leading to some confusion in the actual status of the user

### Version

Nightly

### Expected behavior

User status should show something more informative like "Enabled" 

### Actual behavior

Status shows as "-"

### How to Reproduce?

Navigate to user table in keycloak admin UI

### Anything else?

Appears to be an issue with this section of code in UserDataTable component: 

```
const StatusRow = (user: BruteUser) => {
    return (
      <>
        {!user.enabled && (
          <Label key={user.id} color="red" icon={<InfoCircleIcon />}>
            {t("disabled")}
          </Label>
        )}
        {user.bruteForceStatus?.disabled && (
          <Label key={user.id} color="orange" icon={<WarningTriangleIcon />}>
            {t("temporaryLocked")}
          </Label>
        )}
        {user.enabled && !user.bruteForceStatus?.disabled && "—"}
      </>
    );
  };
```

**Comment by ssilvert** [comment]
@xianli123 Can you look back and see if we covered this in the wireframes?

**Comment by kaustubh-rh** [comment]
@ssilvert I'm able to reproduce this , can I raise a PR for the same ?

**Comment by ssilvert** [comment]
@kaustubh-rh That's fine if you want to do a PR.  

It looks like it was coded this way on purpose, so I want to find out why if I can.  @xianli123 will be back in a few days.  Maybe he knows.

**Comment by xianli123** [comment]
Hi @kaustubh-rh @ssilvert, sorry for the late reply. Initially, the **Status** was not designed for enabled/disabled. The **Status** should indicate some issues or error messages for the user as shown in the screenshot below. So the dash **-** stood for the normal status at that moment. It seems that we can't develop this complex feature so far. As for the current UI, the dash - is a bit confusing. We can optimize it.

> <img width="950" alt="Screenshot 2023-11-10 at 14 39 31" src="https://github.com/keycloak/keycloak/assets/53931519/1fee4052-1c68-4f7b-9a3e-44c77ad253b5">


The first solution is to change the title from **Status** to **Enable**, and use the clickable switch to indicate Enabled/Disabled.

> <img width="936" alt="Screenshot 2023-11-10 at 15 00 34" src="https://github.com/keycloak/keycloak/assets/53931519/72fb7260-c2ce-4604-9b12-cf9eeea9ee03">


Another approach is to directly remove the status column and add a label next to the user name for each user.

> <img width="974" alt="Screenshot 2023-11-10 at 15 14 43" src="https://github.com/keycloak/keycloak/assets/53931519/853351fe-59da-4c32-a7c5-3312b7bac3b3">

Which one do you prefer? Are there any other thoughts?
