### ISSUE TITLE
show/hide password in clear text button visible for hiden field in "forgot password" flow

### ISSUE THREAD

**Issue by BlackVoid** [keycloak/keycloak#24487]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When using the reset password flow the button to toggle between showing and hiding the password is shown for a hidden field as shown in the image below
![image](https://github.com/keycloak/keycloak/assets/673720/02653713-ac65-4cd2-9928-0f7dce4b7bac)

### Version

nightly (2023-10-02)

### Expected behavior

The toggle should not be shown for hidden fields

### Actual behavior

The toggle is visible for a hidden field

### How to Reproduce?

1. Create a user
2. Use the forgot password feature
3. Click on the link to reset password
4. The toggle for a hidden field is shown

**Comment by jonkoops** [comment]
@andreas-blaettlinger I believe you worked on this, could you take a look at this bug?

**Comment by jonkoops** [comment]
I am able to reproduce this issue, I'll work on a fix.

**Comment by jonkoops** [comment]
Fix available under #24489, this will land in v23.

**Comment by BlackVoid** [comment]
That was super fast, thanks you!

**Comment by jonkoops** [comment]
Keeping this issue open, as we need to land this fix first.
