### ISSUE TITLE
Add clientId to successful LOGOUT event

### ISSUE THREAD

**Issue by jsm174** [keycloak/keycloak#24510]
### Description

When logging out of an app the `clientId` is not included in the `LOGOUT` event details:

```jmillard-keycloak-1  | Event Occurred:type=LOGOUT, realmId=6630d323-ee8e-441c-8338-44d632c9de36, clientId=null, userId=7147da01-9310-483e-92b6-4e50f5b1b4ed, ipAddress=172.18.0.1, redirect_uri=http://localhost:9000/admin/master/console/```

I was looking through the source and I believe this is the path of a successful logout:

https://github.com/keycloak/keycloak/blob/7d7880b6f6aae5112d4b67f94bc9f1697d1e0c06/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L467-L484

I'm not sure if the `clientId` is still available at this point, but it would be great to have.

### Motivation

I need it in an application to support collecting metrics.

### Details

```http://localhost:9000/realms/master/protocol/openid-connect/logout?client_id=security-admin-console&post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fadmin%2Fmaster%2Fconsole%2F&id_token_hint=...```

So I know the `client_id` is definitely in the original request.

**Comment by gabrielpadilh4** [comment]
Hello, i opened a PR for that -> https://github.com/keycloak/keycloak/pull/24987

**Comment by jsm174** [comment]
Fantastic. Thank you!!

**Comment by gabrielpadilh4** [comment]
Hey @jsm174 have you tested in Keycloak 23 ? 

I tested and it seems that the client id is being added:
`2023-11-24 21:50:58,989 DEBUG [org.keycloak.events] (executor-thread-3) type=LOGOUT, realmId=2c798753-f25b-4cdf-a9a7-e076ebe713a3, clientId=security-admin-console, userId=fc5ced1a-084b-4693-ab1e-b6f7772a5034, ipAddress=0:0:0:0:0:0:0:1, redirect_uri=http://localhost:8080/admin/master/console/#/master/events, authSessionParentId=71741f12-32c1-4397-8fac-2d32c2b44868, authSessionTabId=2kG0OJy_yuU`

**Comment by jsm174** [comment]
Unfortunately, I did not test in 23. Our Keycloak instance is tightly locked down and on 22.  I will test in a docker container and report back.

**Comment by gabrielpadilh4** [comment]
Nice, thank you @jsm174

**Comment by jsm174** [comment]
Sorry this took me so long, but I did test 23 via a container, and its there. Thank you for adding this!

```
Event Occurred:type=LOGOUT, realmId=6630d323-ee8e-441c-8338-44d632c9de36, clientId=react-keycloak-test, userId=7147da01-9310-483e-92b6-4e50f5b1b4ed, ipAddress=192.168.65.1, redirect_uri=http://localhost:3000
```
