### ISSUE TITLE
Keycloak integration with Google Identity Provider

### ISSUE THREAD

**Issue by amin224** [keycloak/keycloak#24517]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

I am using Postman with the Authorization code type OAuth 2.0 to generate an access token for my APIs. This setup is configured to use Keycloak as the authentication provider. **Everything works as expected when i log in using Keycloak user credentials**. However, when i attempt to log in using Google or Github as identity providers, I encounter an error at the final stage. The error message is as follows:
 
`POST https://{host:port}/realms/{myrealm}/protocol/openid-connect/token` 
 
Response Body: `{"error":"invalid_grant","error_description":"Code not valid"}`

### Version

21.1.1

### Expected behavior

The expected behavior is to receive an access token for accessing my authorized APIs in my web application, which uses JwtBearer authentication with Keycloak.

For reference:

```
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(o =>
{
    o.Authority = "https://{host:port}/realms/{myrealm}";
    o.Audience = "{aud}";
    o.RequireHttpsMetadata = false;
    o.Events = new JwtBearerEvents()
    {
        OnAuthenticationFailed = c =>
        {
            c.NoResult();
 
            c.Response.StatusCode = 500;
            c.Response.ContentType = "text/plain";
            IdentityModelEventSource.ShowPII = true;
            return c.Response.WriteAsync(c.Exception.ToString());
        }
    };
});
```

### Actual behavior

After requesting a new access token, the Keycloak UI opens, and I'm presented with the option to log in using either my Google or GitHub account. After selecting one of them, I'm directed to their respective login pages and sign in with my account credentials. Subsequently, I'm given the option to grant access to my account from Keycloak, which I accept. However, authentication fails at the final stage, and I receive the following error:

`POST https://{host:port}/realms/{myrealm}/protocol/openid-connect/token` 

Response Body: `{"error":"invalid_grant","error_description":"Code not valid"}`

### How to Reproduce?

1. In Keycloak, I create a GitHub Identity Provider within my realm and provide the ClientId and ClientSecret of my GitHub OAuth application. I also enable token storage.
Note: The "First Login flow" is set to "first broker login," and the "Post login flow" is set to "None."

2. On GitHub, I set the homepage URL and the authorization callback URL as the Redirect URI for the Keycloak Identity Provider for GitHub.
3. In Postman, under the Authorization tab, I configure OAuth 2.0 as follows:
    -     Token name: testing
    -     Grant type: Authorization Code
    -     Auth URL: https://{host:port}/realms/{myrealm}/protocol/openid-connect/auth
    -     Access Token URL: https://{host:port}/realms/{myrealm}/protocol/openid-connect/token
    -     ClientId: The ClientId of my client application in Keycloak
    -     ClientSecret: The ClientSecret of my client application in Keycloak
    -     Client Authentication: Send as Basic Auth header

Note: Regarding the clients, I set up a client for my web application, enabled Client Authentication, and configured the following Authorization flows: standard flow, direct access grants, implicit flow, and OAuth 2.0 Device Authorization Grant to ensure the process works smoothly.

### Anything else?
When i try to log in using Github or Google in a browser for a specific realm it works and logs me in successfully, but for some reason it wont work for OAuth 2.0.

**Comment by amin224** [comment]
I resolved this issue by enabling key features during the Keycloak installation, including preview, token_exchange, and admin_fine_grained_authz.

**Comment by mariocozta** [comment]
For anyone having this issue and is using **postman**:
I was also recieving **{"error":"invalid_grant","error_description":"Code not valid"}** and the logs on the keycloak instance said "Code with **invalid format**" or something like this. 

I was/am using **postman** to test the oauth flow and that is why it was failing. Just use the option *Authorize using browser* and it should work.

What got me to this solution:
https://keycloak.discourse.group/t/no-way-for-external-idp-google-and-postman/20077/4
