### ISSUE TITLE
Offline Sessions not shown in users session tab

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#24523]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Offline Sessions are not being displayed under users session tab, but are available under realm sessions and client sessions tab.
![Bildschirmfoto 2023-11-03 um 13 22 06](https://github.com/keycloak/keycloak/assets/2075748/4c750ab2-8399-495d-8c47-5d3b53403df6)
![Bildschirmfoto 2023-11-03 um 13 22 12](https://github.com/keycloak/keycloak/assets/2075748/b7dfb39b-343b-40ca-827c-aa88c8be0317)
![Bildschirmfoto 2023-11-03 um 13 22 21](https://github.com/keycloak/keycloak/assets/2075748/2c18f7b7-8f0f-47c7-87cd-83720ec404f4)

### Version

22.0.5

### Expected behavior

Offline Sessions are also displayed at users sessions tab.

### Actual behavior

Offline Sessions are not displayed at users sessions tab, only regular sessions are shown

### How to Reproduce?

Create an offline session an inspect the sessions at realm, client and user.

### Anything else?

Don't know if this is really a bug in the admin ui, or if it is intended. If intended, then why? I don't see a reason here.

**Comment by ssilvert** [comment]
This is a question of what the REST API should return when you ask for the user's sessions.  Moving this issue to the core team.

**Comment by john2094** [comment]
@kaustubh-rh exist another issue related with same endpoints. When You signout a offline session the endpoint call for delete is /sessions instead /offline-sessions. These cause that the endpoint respond with a 404 and the offline session was not loged out.

**Comment by jonkoops** [comment]
We could add a tab that shows the offline sessions in the same manner the current session overview is implemented. @ssilvert @xianli123 WDYT?

Since a REST API exists for this data, I will re-label this to the UI team.

**Comment by ssilvert** [comment]
> We could add a tab that shows the offline sessions in the same manner the current session overview is implemented. @ssilvert @xianli123 WDYT?
> 
> Since a REST API exists for this data, I will re-label this to the UI team.

I think two tabs might be overkill.  I don't think a user typically has offline sessions.  If the user does have an offline session, you probably want to see it along with the others.  So a single tab would give a better overview of activity.

I don't remember how the old admin console handled it or if it did what the issue author wants.   But I suppose we could implement it with two REST calls.

**Comment by ssilvert** [comment]
> @kaustubh-rh exist another issue related with same endpoints. When You signout a offline session the endpoint call for delete is /sessions instead /offline-sessions. These cause that the endpoint respond with a 404 and the offline session was not loged out.

Created issue for this one.  https://github.com/keycloak/keycloak/issues/24763

**Comment by dasniko** [comment]
> I think two tabs might be overkill. I don't think a user typically has offline sessions. If the user does have an offline session, you probably want to see it along with the others. So a single tab would give a better overview of activity.

I also don't think that we do need two tabs, one combined tab with regular and offline sessions should be sufficient. The same way, as the realm sessions and the client sessions views work.

**Comment by jonkoops** [comment]
> I think two tabs might be overkill. I don't think a user typically has offline sessions. If the user does have an offline session, you probably want to see it along with the others. So a single tab would give a better overview of activity.

Yeah, I am only proposing this as it's the least frictional approach. Having to call two APIs and handle their pagination on the client together is always problematic (see the amount of issues reported around breaking pagination). If this needs to be a single overview, then we need to have a single REST endpoint that handles that for us.

Basically, we either show offline sessions, or online sessions, but never both at the same time. Unless changes to the REST API are made to handle pagination there.

**Comment by ssilvert** [comment]
@dasniko We have looked into this further and, unfortunately, a proper implementation would require a lot of changes to the back end.  So we are unlikely to devote resources to this..

Since Keycloak has never supported this feature and nobody has asked for it until now, it's probably not a high priority feature for the majority of installations.

I'm going to close this issue now, but if you think there is a truly compelling use case, I suggest that you open a discussion and see what the rest of the community thinks.  We can always reconsider.

**Comment by xianli123** [comment]
Hi @jonkoops I also agree with combining the offline sessions and regular sessions. But if we want to consider this feature in the future, it works for me. Whenever we need to update this part, please feel free to count me in.

**Comment by dasniko** [comment]
@ssilvert Thanks for your effort and explanation. It's not a crititcal feature for me and I wasn't aware of the legacy behavior any more. I just thought it was a "bug" because of the inconsistency between realm, client and user tabs.

**Comment by jonkoops** [comment]
Personally, I think we could still land this as a separate overview if it's a useful feature for users :man_shrugging:
