### ISSUE TITLE
Change inline EN text to translation in ApplicationsPage

### ISSUE THREAD

**Issue by jperlak** [keycloak/keycloak#24527]
### Description

In ApplicationsPage (account theme) there is an inline text "Has access to" instead of a translation. The exact line may be found [here](https://github.com/keycloak/keycloak/blob/848e9fe0040aaae9b4c2eeb6a7a080dc1cd244f2/themes/src/main/resources/theme/keycloak.v2/account/src/app/content/applications-page/ApplicationsPage.tsx#L223).

### Motivation

It is not possible to translate the text to a custom value in other language.

### Details

The text should be probably changed to use a translation-key usage like `hasAccessTo`.

**Comment by thecooldrop** [comment]
Hello I would like to support development of Keycloak and this seems like rather small and good first issue to start on. May I please be assigned to work on it?

**Comment by jonkoops** [comment]
Sure @thecooldrop, feel free to open up a PR to fix this, I'll assign you to this issue.
