### ISSUE TITLE
DPoP advertised on OIDC Well Known Endpoint even though DPoP feature is not enabled (preview feature)

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#24547]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

DPoP is advertised on the OIDC Well Known Endpoint even though the DPoP feature is not enabled - it is currently a preview feature.

In [RFC 9449](https://datatracker.ietf.org/doc/html/rfc9449#section-5.1) 'dpop_signing_alg_values_supported' in the OIDC Well Known Endpoint can be used to signal support for DPoP. 

Having this advertised as supported when the DPoP feature is not actually enabled may be misleading to clients that bootstrap their configuration automatically from this endpoint.

### Version

nightly

### Expected behavior

When DPoP feature is not enabled, `dpop_signing_alg_values_supported` in the OIDC Well Known Endpoint is either an empty array or missing entirely.

### Actual behavior

Regardless of DPoP feature status, `dpop_signing_alg_values_supported` in the OIDC Well Known Endpoint has all the supported algorithms mentioned.

### How to Reproduce?

* Start Keycloak without DPoP feature enabled
  * using podman `podman run -it --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:nightly start-dev`
* Browse to http://localhost:8080/realms/master/.well-known/openid-configuration
* See `dpop_signing_alg_values_supported` set in metadata

### Anything else?

This is likely a minor issue. This also looks like it may be relatively simple to resolve and I will submit a PR.

**Comment by ahus1** [comment]
Tagging this KC23 milestone as this will be the first version to include the DPOP changes AFAIK. 

@tnorimat / @mposolda - can you please review the associated PR?
