### ISSUE TITLE
the `./kc.sh tools completion` command cannot be recognized correctly

### ISSUE THREAD

**Issue by bekcpear** [keycloak/keycloak#24551]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

When I want to generate bash/zsh completion script by `./kc.sh tools completion`, an error occurred with the following log:

```
Changes detected in configuration. Updating the server image.
Unknown option: 'completion'
Try 'kc.sh build --help' for more information on the available options.
```

However I can see the help msg of this completion command with `./kc.sh tools --help`, so I think the command I typed is correct.

I tried to use historical versions of binaries and found：

* 21.1.2, this completion command works fine
* 22.0.0, this completion command doesn't work, the same error as above

I tried to find the cause of the problem but couldn't find it. I hope I can get help here.

### Version

22.0.5

### Expected behavior

command `./kc.sh tools completion` works fine

### Actual behavior

command `./kc.sh tools completion` say `Unknown option: 'completion'`

### How to Reproduce?

unpack the binary tar.gz package, run the above command.

**Comment by kaustubh-rh** [comment]
I'm able to reproduce the issue

**Comment by mabartos** [comment]
I was able to reproduce the issue; out of triage.
