### ISSUE TITLE
The created resource is not being displayed.

### ISSUE THREAD

**Issue by r-3110** [keycloak/keycloak#24552]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

If you request to create a resource at the resource registration endpoint without specifying any scopes, the resource may be created, but it may not be displayed in the account's UI.This issue is occurring at least on version 18.0.2 or later.

### Version

18.0.2 =>

### Expected behavior

The created resource should be displayed in the resource owner's account.
I don't believe 'scope' is a required parameter.

### Actual behavior

The created resource is not displayed, and when inspecting Chrome DevTools, it appears that a map function is being executed on 'undefined', resulting in a runtime error. This is likely due to the absence of scopes, causing 'resource.scopes' to be 'undefined'.
![スクリーンショット 2023-11-04 23 12 40](https://github.com/keycloak/keycloak/assets/65270957/c86d581a-e3e8-4aa7-a36e-bbc1e88ebd25)
![スクリーンショット 2023-11-05 11 16 21](https://github.com/keycloak/keycloak/assets/65270957/4f8499df-608f-4131-992d-aa983057348d)
![スクリーンショット 2023-11-04 23 12 14](https://github.com/keycloak/keycloak/assets/65270957/08d49120-9ea9-4da8-8587-afe3fcd2e2da)

### How to Reproduce?

1. Create a realm and enable UMA.
![スクリーンショット 2023-11-05 13 16 23](https://github.com/keycloak/keycloak/assets/65270957/8f34c2af-eeac-4c5b-8562-6a6100b75a3b)

2. Create a client and enable client authorization and authorization.
![スクリーンショット 2023-11-05 13 16 37](https://github.com/keycloak/keycloak/assets/65270957/9e8ed74e-8e97-4246-bb51-c9727a0d4270)

3. Obtain a PAT (Personal Access Token) and use it to make a request to an endpoint to create a resource. For example:
```bash
 curl -v -X POST localhost:8080/realms/uma-test/authz/protection/resource_set \
  -H 'Authorization: Bearer '$PAT \
  -H 'Content-Type: application/json' \
  -d '{"name":"testuser1 Resource", "owner": "testuser1", "ownerManagedAccess": true }'
```

4. You are trying to log in with "testuser1" to the account console to check for the resource, but it is not being displayed.
![スクリーンショット 2023-11-04 23 12 40](https://github.com/keycloak/keycloak/assets/65270957/c86d581a-e3e8-4aa7-a36e-bbc1e88ebd25)

### Anything else?

- [Resource Registration API](https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-federated-authz-2.0.html#reg-api)

**Comment by edewit** [comment]
What use does a resource have without any scopes?

**Comment by jonkoops** [comment]
Closing this since it was reported for an old version of Keycloak. If the issue persists in the latest version of Keycloak let us know.
