### ISSUE TITLE
use Keycloak JavaScript adapter ,Authentication and authorization services,The client secret parameter is not carried why??

### ISSUE THREAD

**Issue by ZhangWeike2000** [keycloak/keycloak#24566]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

const KEYCLOAK_CONFIG = {
url: 'your-url-login',
realm: 'master',
clientId: 'clientId',
clientSecret: 'xxxxx'
}
const keycloak = new Keycloak(KEYCLOAK_CONFIG)
const authenticated = await keycloak.init({
onLoad: 'login-required'
})

### Version

22.0.5

### Expected behavior

The token was obtained successfully

### Actual behavior

Failed to load resource: the server responded with a status of 401 (Unauthorized)

### How to Reproduce?

export const useKeycloakInit = async () => {
  // 检查是否使用Keycloak作为认证平台
  if (import.meta.env.VITE_BASE_OAUTH_TYPE !== 'keycloak') {
    return
  }
  const systemStore = useSystemStore()
  const keycloakStore = useKeycloakStore()
  // 初始化Keycloak实例
  const keycloak = new Keycloak(KEYCLOAK_CONFIG)
  try {
    // 尝试初始化并登录
    const authenticated = await keycloak.init({
      onLoad: 'login-required'
    })
    //将keycloak实例存入全局状态管理库
    keycloakStore.setKeycloak(keycloak)
    // 如果用户已认证，验证令牌并设置
    if (keycloak && authenticated && keycloak.token != null) {
      await keycloakAuthorization(keycloak.token)
      // 存储到 pinia
      systemStore.setItem(SystemStoreEnum.USER_INFO, {
        [SystemStoreUserInfoEnum.USER_TOKEN]: keycloak.token,
        [SystemStoreUserInfoEnum.USER_ID]: keycloak.tokenParsed?.userId,
        [SystemStoreUserInfoEnum.USER_NAME]: keycloak.tokenParsed?.preferred_username,
        [SystemStoreUserInfoEnum.NICK_NAME]: keycloak.tokenParsed?.family_name,
      })
    }
  } catch (error) {
    // 输出错误并登出
    console.error('Failed to initialize adapter:', error)
    await keycloakStore.getKeycloakInstance.logout()
  }
}

**Comment by jonkoops** [comment]
Keycloak JS no longer supports using client secrets as a way to authenticate. This would mean that the secret needs to be saved in the application on the client side, which is considered insecure. If you want to use Keycloak JS you will have to use a public client. I'd recommend reading [the documentation](https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter) of Keycloak JS.
