### ISSUE TITLE
Failed to parse source map from* after updating the keycloak major version

### ISSUE THREAD

**Issue by TemoSulava** [keycloak/keycloak#24570]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I updated the keycloak lib to the major version and now i am getting:
`WARNING in ./node_modules/@react-keycloak/core/lib/context.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/tname/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/context.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/context.ts'

WARNING in ./node_modules/@react-keycloak/core/lib/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/index.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/index.ts'

WARNING in ./node_modules/@react-keycloak/core/lib/provider.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/provider.tsx' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/provider.tsx'

WARNING in ./node_modules/@react-keycloak/core/lib/types.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/types.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/core/lib/@react-keycloak/core/types.ts'

WARNING in ./node_modules/@react-keycloak/web/lib/context.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/context.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/context.ts'

WARNING in ./node_modules/@react-keycloak/web/lib/index.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/index.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/index.ts'

WARNING in ./node_modules/@react-keycloak/web/lib/provider.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/provider.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/provider.ts'

WARNING in ./node_modules/@react-keycloak/web/lib/useKeycloak.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/useKeycloak.ts' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/useKeycloak.ts'

WARNING in ./node_modules/@react-keycloak/web/lib/withKeycloak.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/withKeycloak.tsx' file: Error: ENOENT: no such file or directory, open '/home/name/Desktop/project/projectname/frontend/node_modules/@react-keycloak/web/lib/@react-keycloak/web/withKeycloak.tsx'
`

I couldnt find a working solution, i tried ignorning this warnings, but the app is still stuck at loading in both cases

### Version

"keycloak-js": "^14.0.0",

### Expected behavior

I expect it to not inifnitely load

### Actual behavior

application is stuck at loading screen

### How to Reproduce?

i am at react 17.0.0 and keycloak 		"keycloak-js": "^14.0.0",
happened after updating from older major version of keycloak to the new major version. I tried with react 18 and it is the same issue

**Comment by ssilvert** [comment]
I don't understand what you are trying to do.

You will need to give step-by-step instructions on how to create a bug.  This should include the keycloak version you are using and making sure that you are upgrading to the latest.  If you aren't upgrading to the latest Keycloak version then we can not help you here.

Otherwise, I suggest you ask for help in the keycloak community.  https://www.keycloak.org/community

**Comment by jonkoops** [comment]
We no longer support that version of Keycloak JS, also the React library you are using is no [longer maintained](https://github.com/react-keycloak/react-keycloak#readme).
