### ISSUE TITLE
Read Only Access of a realm clients' Authz is broken for Admin Console 

### ISSUE THREAD

**Issue by SalemWafi** [keycloak/keycloak#24586]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Users in the master realm who have view-authorization role of a sub realm can't see the "Authorization" tab of the clients (that has authorization enabled) of that sub realm.

### Version

22.0.3

### Expected behavior

Users in the master realm who have view-authorization role of a sub realm should be able to see the "Authorization" tab of the clients (that have authorization enabled) of that sub realm.

### Actual behavior

Users in the master realm who have view-authorization role of a sub realm can't see the "Authorization" tab of the clients (that has authorization enabled) of that sub realm.

### How to Reproduce?

1) Create a User in the master realm and assign these roles to that user (Make sure to assign your sub realm view-authorization role to that user).

![KC1](https://github.com/keycloak/keycloak/assets/32916450/72672995-6a3f-4017-97a3-8d913f7ceb04)

2) Login/impersonate that user, then go to your sub realm clients and click on one of the clients in that realm that has Authorization enabled. 
You won't be able to see the "Authorization" tab even tho that you have the role view-authorization of that sub realm:

![KC2](https://github.com/keycloak/keycloak/assets/32916450/341512bc-ed9f-46b6-89f9-ba5a96dfd248)

### Anything else?

If I assign the sub realm manage-authorization role to that user, the "Authorization" tab shows up, but of course, the user will have write access to the Authorizations tab, which is not a desirable solution for read-only users.

![KC3](https://github.com/keycloak/keycloak/assets/32916450/70efd418-50ad-4dd5-a129-75ff196d77b1)

**Comment by ssilvert** [comment]
I have verified this bug.

**Comment by SalemWafi** [comment]
Hi @hmlnarik 

Since you took this issue, this info might be helpful for you:

I think I have already found the cause of this bug.

The check for "view-authorization" is missing in this line of code: [code_line_link](https://github.com/keycloak/keycloak/blob/20f5edc708a344833763586a87a1bde55667d74a/js/apps/admin-ui/src/clients/ClientDetails.tsx#L533C81-L533C81) 
as you see the line "{client!.authorizationServicesEnabled && hasManageAuthorization && ("
should be instead "{client!.authorizationServicesEnabled && (hasManageAuthorization || hasViewAuthorization) && ("
where: "const hasViewAuthoriztion= hasAccess("view-authorization");"

CC: @ssilvert

**Comment by SalemWafi** [comment]
@hmlnarik I found a similar issue, in case you have some spare time to work on it :)
Thanks in advance!!

[link_to_issue](https://github.com/keycloak/keycloak/issues/25054#issuecomment-1828204325)<br>[link_to_code_issue_described_in_comment](https://github.com/keycloak/keycloak/issues/25054#issuecomment-1828204325)
