### ISSUE TITLE
Leaving Single Sign Out page open for too long and then confirming logout leads to error page

### ISSUE THREAD

**Issue by Gornhoth** [keycloak/keycloak#24595]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have a logout page that is responsible for logging the user out of all connected services.
If a user goes to this logout page but leaves that page open for about an hour and only then presses the logout button to confirm the logout, the user is redirected to the error page from which there is no knowing what went wrong or how to recover (except navigating manually to the login page again via URL).
In the attached image the two steps are shown: Above is the logout page with the logout button and below the resulting error is shown.
![keycloak_error_logout](https://github.com/keycloak/keycloak/assets/34295773/13b63968-ab20-42a3-87c0-00148610e915)

### Version

19.0.3, 22.0.4

### Expected behavior

As I suspect this issue to be related to some timeout setting, the expected behaviour should probably be to automatically redirect the user to the login page instead of an error page when the session expires while on the logout screen.

### Actual behavior

The user is redirected to an error page upon confirming the logout with the logout button on the logout page.

### How to Reproduce?

I am not sure if the problem is easily reproducible without our setup, but here are the steps I took to consistently reproduce this error on our system:

- From our application, go to the logout page for a logged in user.
- Leave this page open for about an hour.
- Confirm the logout by pressing the logout button.

### Anything else?

When filtering for logout errors in the keycloak admin console UI, the logout error event that is caused by this issue is shown but without any client or user, which probably indicates the session expired and; therefore, the event can not be matched to a logged in user.
![keycloak_error_log](https://github.com/keycloak/keycloak/assets/34295773/65cac268-6a99-4dd7-b52c-ddb5ed26e99b)

Upgrading from keycloak 19.0.3 to 22.0.4 did not solve this issue for us.

**Comment by rmartinc** [comment]
Yes, probably the session expired in the hour waiting. Normally we put a link `Back to Application` in the error page if the client is there but maybe it is removed because of this [line](https://github.com/keycloak/keycloak/blob/22.0.5/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L368). If it's that we can change the condition to use something like `!= nul and equals`. We would need a test in `RPInitiatedLogoutTest` if someone wants to work on it. Moving to backlog for the moment and adding help wanted in the issue.

**Comment by lexcao** [comment]
Hi @rmartinc 
Thanks for guiding, I have created a fix. 
Please help review, https://github.com/keycloak/keycloak/pull/26559.
