### ISSUE TITLE
InResponseAttribute is not included in the SAML Response

### ISSUE THREAD

**Issue by VarshneyPrince** [keycloak/keycloak#24605]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

The SAML Request contains the ID but the SAML Response is not having InResponseTo attribute.
Using Keycloak Version 15.1.0 . I checked the code found the attribute shall be added unconditionally. But not sure why it's not getting added.

<saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData NotOnOrAfter="2023-11-01T13:12:31.787Z" Recipient="[https://GVB07248.snowflakecomputing.com/fed/login"/></saml:SubjectConfirmation>](https://gvb07248.snowflakecomputing.com/fed/login%22/%3E%3C/saml:SubjectConfirmation%3E%3C/saml:Subject%3E%3Csaml:Conditions)

### Version

15.1.0

### Expected behavior

It shall include the InResponseTo Attribute in the SAML Response 

### Actual behavior

 the InResponseTo Attribute in the SAML Response is not included

### How to Reproduce?

Perform SAML SSO Integration, mainly facing this with Snowflake SAML integration.

**Comment by VarshneyPrince** [comment]
@hmlnarik: Could you please help here!

**Comment by rmartinc** [comment]
@VarshneyPrince Have you tested in last 22.0.5?

**Comment by VarshneyPrince** [comment]
@rmartinc : I would not be able to test it on 22.0.5 as the version we are using in our production is 15.0.1 . I checked the source code for 15.1.0 and I could see the InResponseTo attributed being added unconditionally. but still it's not there in the response. I would need some help here to understand if this version does not support it and we can add it through any composite mapper.? or if it supports the InResponseTo Attribute so am I missing something here. ?

**Comment by rmartinc** [comment]
@VarshneyPrince You can test with 22.0.5 installing a temporary keycloak or similar. You don't need to modify your production setup. Do you have logs with saml debug that you can share?

**Comment by VarshneyPrince** [comment]
@rmartinc : How I can get the same debug logs, I have the SAML Request and response from the browser developers tool.

**Comment by rmartinc** [comment]
You can start keycloak with debug in the SAML category: `--log-level=INFO,org.keycloak.saml:TRACE` option. That dumps the SAML documents received and sent by the server.

**Comment by VarshneyPrince** [comment]
Thanks @rmartinc : this is fixed by changing the SAML Initiated IDP url to use the format /{realm}/protocol/saml instead of /{realm}/protocol/saml/clients/clientname
