### ISSUE TITLE
clearToken fires for no reason in keycloak-js client side lib

### ISSUE THREAD

**Issue by JuozasIzi1** [keycloak/keycloak#24606]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

clearToken fires for no reason in keycloak-js client side lib using paypal together.

```TS
import { usePayPalHostedFields } from "@paypal/react-paypal-js";
...

export const useCardDetailsSubmitButton = () => {
  const [isPaying, setIsPaying] = useState(false);
  const hostedFields = usePayPalHostedFields();
  const handleSubmit = () => {
      hostedFields.cardFields
        .submit({
...
};
```

clearToken is called after paypal submit

### Version

20.0.0

### Expected behavior

clearToken not fired for no reason

### Actual behavior

clearToken fired for unknwon reasons, but after submit hosted fields of Paypal. Paypal uses iframe and etc

### How to Reproduce?

use paypal code above

**Comment by jonkoops** [comment]
Like mentioned in the issue template, we only offer support on the latest version of Keycloak. If it still occurs there then feel free to report this issue again.
