### ISSUE TITLE
MIGRATION_MODEL does not properly support liquibase migrations for main/nightly branch 

### ISSUE THREAD

**Issue by rh-iatanaso** [keycloak/keycloak#24634]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When keycloak performs database migration it writes the version in MIGRATION_MODEL table. This works great for releases. 
The problem is for main branch, because the version is always 999.0.0 migration on main happens only once after that it will never happen again until the the row is removed.
This presents a big challenge when running main on permanent database for testing or other purposes.

### Version

nightly

### Expected behavior

Expected behavior is to be able to run the migration. Because liquibase will do it's own validation. 999.0.0 version should never be written into the MIGRATION_MODEL table.

### Actual behavior

999.0.0 is written to the MIGRATION_MODEL table

### How to Reproduce?

1. Run keycloak 22.0.0
2. Manually insert row into MIGRATION_MODEL table with version 999.0.0
3. Run keyclok nigthly, the database migration will not be performed

**Comment by vmuzikar** [comment]
Not sure if we actually support DB migrations between nightly versions. We'd need to probably version every nightly release with some unique timestamp or something.

Assigning to @keycloak/store as this is their area.

**Comment by rh-iatanaso** [comment]
> Not sure if we actually support DB migrations between nightly versions. We'd need to probably version every nightly release with some unique timestamp or something.
> 
> Assigning to @keycloak/store as this is their area.

I think the solution is simply to stop writing 999.0.0 to the MIGRATION_MODEL.

**Comment by ahus1** [comment]
This is not supported at the moment, as code in classes like `MigrateTo24_0_0` is designed to run only once, and might change from nightly release to nightly release. 

So even if we don't write it (or a different value) to the table, the outcome will be inconsistent. 

Therefore, the best practice for running nightly builds is to rollback/reset/restore the database to the latest stable release first before installing the nightly release, or starting with an empty database  and possibly re-initialize it from a previous export (which might only work on smaller installations). 

Closing this, as we don't plan to support this.

**Comment by stianst** [comment]
Closing this as main simply does not support migration of the database. There are several problems with supporting migrations in nightly/main and this would not be a trivial task, and would have rather big implications on how we do the changes. We have Java based migration, which does not work on individual changes, but rather from version to version. In addition if a particular migration change is broken or needs updating (both for Java and Liquibase) we modify that migration, and not introduce a new migration (of course only changes since the last release).
