### ISSUE TITLE
UserId too long to add Security Key WebauthN

### ISSUE THREAD

**Issue by jacac** [keycloak/keycloak#24645]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

Adding security keys fails if the user id is longer than 64 bytes. 
A federated user has the storage id included which uses already 39 bytes and easily goes over that limit. 

### Version

22.0.4

### Expected behavior

Ability to add security keys for federated users.

### Actual behavior

Error: Security key registration result is invalid. TypeError: User handle exceeds 64 bytes.

### How to Reproduce?

 Add `User federation` ldap should work well if the `username` is set to `userPrincipalName`. 

### Anything else?

I don't think that WebAuthn will change their standards which leaves it to Keycloak to adjust. Here is the link to the specification https://www.w3.org/TR/webauthn-2/#sctn-createCredential. It fails on point 5.

**Comment by missaeldenadai** [comment]
Any update on this?
@jacac did you managed to overcome this limitation somehow?

**Comment by jacac** [comment]
No updates and it is still an issue.

**Comment by missaeldenadai** [comment]
@jacac in order to overcome this we might create a custom WebAuthnRegister and change only the behavior of setting the userId on the form.

**Comment by jacac** [comment]
Same thing happens on version 25.0.1.

**Comment by jacac** [comment]
@missaeldenadai Did you succeed with a custom register?

**Comment by missaeldenadai** [comment]
@jacac sorry for the delay.
Yes, I did.
I remove the federation id before building the webauthn-register form.
But I had to create a WebAuthnAuthenticator as well. When validating the passkey, I have to compare the userIds without the federation id.
