### ISSUE TITLE
Deleting a User or User Group might cause that all users suddenly get the permissions of the deleted user.

### ISSUE THREAD

**Issue by dinutine** [keycloak/keycloak#24651]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When a user is removed from keycloak, also a "User policy" selecting only this user is also removed.

If you have defined a permission which selects this policy and other policies with Decision strategy Unanimous. The user policy is bluntly removed, suddenly giving this permission to all users in the system.

### Version

22

### Expected behavior

User and User group policy is not removed, but after removal of the User or User group the policy always evaluates to false.

### Actual behavior

User policy is deleted from the database when the user is deleted. In permissions using this policy, this policy is removed.

### How to Reproduce?

Create a user "user1"
Create a client with Authorization enabled.
Create in this client a resource "resource1"
Create a user policy "user is user1", add only user1 to the list of users in this policy
Create some other policy, for instance time based "dayshift". Repeat. Hour min 8 max 17.
Create a permission "user1 has access to resource1 during the dayshift"
Add resource1 to the list of resources. Add policies "user is user1" and "dayshift" to the permission
Set decision strategy to Unanimous

Delete user1
Policy "user is user1" is deleted.
The permission only contains 1 policy anymore being "dayshift"
As a result, suddenly all other users are granted access to resource1 during the dayshift.

**Comment by douglaspalmer** [comment]
Clearly we should be removing the dayshift permission too.

**Comment by sschu** [comment]
The decision what else to remove can be quite complex depending on how the policy is set up (there could be an aggregate policy with combined with more policies, different decision modes etc.). I would rather not delete the policy and make it point to an invalid user ID or to a specific user ID representing a deleted user. I can imagine the same problem exists for role-based policies and group-based policies (assuming the policies are also deleted when roles/groups are deleted).

**Comment by douglaspalmer** [comment]
> The decision what else to remove can be quite complex depending on how the policy is set up (there could be an aggregate policy with combined with more policies, different decision modes etc.). I would rather not delete the policy and make it point to an invalid user ID or to a specific user ID representing a deleted user. I can imagine the same problem exists for role-based policies and group-based policies (assuming the policies are also deleted when roles/groups are deleted).

Sounds reasonable.

**Comment by dinutine** [comment]
> The decision what else to remove can be quite complex depending on how the policy is set up (there could be an aggregate policy with combined with more policies, different decision modes etc.). I would rather not delete the policy and make it point to an invalid user ID or to a specific user ID representing a deleted user. I can imagine the same problem exists for role-based policies and group-based policies (assuming the policies are also deleted when roles/groups are deleted).

I agree not to delete the policy as the decision what to remove will indeed be too complex, 
As I described in the expected behaviour:
"User and User group policy is not removed, but after removal of the User or User group the policy always evaluates to false."

**Comment by douglaspalmer** [comment]
I'm thinking it would be best to leave the user policy in place with an empty list of users. This should mean that nobody can access the resource until an administrator assigns a new user to the user policy. I have a test written that reproduces the issue.

**Comment by pedroigor** [comment]
The behavior is expected but we can review it. IIRC, the same is true for other policies that are bound to entities with their own lifecycle such as clients and groups.

@douglaspalmer What you are proposing should be enough to make sure the policy will always be evaluated as false and the permissions (e.g.: unanimous strategy) will be denied. I can't remember why we decided to not remove the policy but just because we did not want to keep "orphan" policies around.

**Comment by pedroigor** [comment]
Perhaps the best experience here would be to keep the policy but also somehow move permissions (and the policy too) to a "stale" state so that administrators could easily figure out the permissions that need manual intervention to have them fixed. Otherwise, it might be quite hard to figure out what is happening when the behavior changes.

However, I'm not sure if want to invest much in authorization services due to the ongoing discussions for a new authorization model.

**Comment by dinutine** [comment]
> 
> However, I'm not sure if want to invest much in authorization services due to the ongoing discussions for a new authorization model.

Can you share more info on these discussions?
Does this mean the current authorization services of keycloak will become deprecated at some point?
