### ISSUE TITLE
'Advanced Claim to Group/Role' UI Mapper Claims Can Incorrectly Save

### ISSUE THREAD

**Issue by plovell** [keycloak/keycloak#24678]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If you open an existing mapper of the type 'Advanced Claim to Group' or 'Advanced Claim to Role' or OIDC or SAML it is possible to save a mapper that can never match.

When a mapper is first created, it is possible to configure it to match for every authenticated user by leaving the list of claims and groups blank.

If a claim is added to the list, but then removed, the UI will add in a claim with a blank key and value pair, which will never match,

This can lead to user confusion when configuring the mapper as it looks the same in both the initial state and in the state where a claim has been added and removed - but the underlying mapper will behave differently.

### Version

22.0.3

### Expected behavior

The UI should not store claims with blank key/value pairs.  I don't think its a valid use case.

### Actual behavior

The UI does store claims with valid key value pairs, effectively disabling the mapper, but without any clue in the user interface that this has happened.

### How to Reproduce?

1. Download the latest docker image (I am using FROM quay.io/keycloak/keycloak:22.0.3)
2. Start in dev mode (for simplicity, I don't think this impacts the issue)
3. Add enough information to create a new IDP such that you can access the mappers screen,
4. Create a new 'Advanced Claim to Group' mapper, adding in at least one claim.
5. Click Save, navigate back to the **Provider details** page.
6. Open the same mapper for editing.
7. Add an attribute to the new mapper, but leave the key and value blank.
8. Delete the claim create in step 4.
9. Notice that it is not possible to clear the final claim as the minus icon is greyed out 
10. Save again, looking at the network tab, the following is saved against the claims: `claims: [{"key":"","value":""}]`
11. This saved mapper will not now match on login.

**Comment by ssilvert** [comment]
I have reproduced this.
