### ISSUE TITLE
Basic auth is not RFC 2617 compliant

### ISSUE THREAD

**Issue by kusumaghoshdastidar** [keycloak/keycloak#24672]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

[RFC 2617](https://datatracker.ietf.org/doc/html/rfc2617#section-2) explicitly says "<base64 encoding of user-pass, except not limited to 76 char/line>". That means that line breaks should not be present. 
This [PR](https://github.com/keycloak/keycloak/pull/14179) appears to have broken RFC 2617 compliance rather than fix it.

### Version

22.0.5

### Expected behavior

[org.keycloak.util.BasicAuthHelper.createHeader(username, password)](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/util/BasicAuthHelper.java#L35) should prepare a base64 encoded string without line breaks.

### Actual behavior

[org.keycloak.util.BasicAuthHelper.createHeader(username, password)](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/util/BasicAuthHelper.java#L35) should prepare a base64 encoded string is adding line breaks.

### How to Reproduce?

JUnit test invoking BasicAuthHelper.createHeader(username, password):
```java 
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import java.nio.charset.StandardCharsets;
import org.keycloak.common.util.Base64;
import org.keycloak.util.BasicAuthHelper;

class BasicAuthHelperTest {

    @Test
    void test() {
        final String username = "admin";
        final String password = "adminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadmin";

        // Current
        final String hasLineBreak = BasicAuthHelper.createHeader(username, password);

        // Earlier
        final String hasNoLineBreaks = createBasicAuthHeader(username, password);

        assertTrue(hasNewLine(hasLineBreak));
        assertFalse(hasNewLine(hasNoLineBreaks));
    }

    /**
     * Introduced this function to avoid the https://github.com/keycloak/keycloak/pull/14179 change to
     * {@code BasicAuthHelper#createHeader()}.
     */
    private static String createBasicAuthHeader(final String username, final String password)
    {
        return "Basic " + Base64.encodeBytes((username + ':' + password).getBytes(StandardCharsets.UTF_8));
    }

    private static boolean hasNewLine(final String str)
    {
        return str.chars().anyMatch(c -> '\n' == c);
    }

}
```

**Comment by dermot-hardy** [comment]
Fair point.  Base64 adds about 33% so the actual cutoff is around 56 characters.  I noticed it breaking an automated test which was using guids for both the username and the password.

**Comment by sschu** [comment]
That would be my understanding. I can prepare a PR for that.

**Comment by rmartinc** [comment]
Thanks @sschu! Assigning it to you, just assign it to me if you have any issue.

**Comment by sschu** [comment]
@rmartinc Fix is there: https://github.com/keycloak/keycloak/pull/24837
