### ISSUE TITLE
'Advanced Claim to Group/Role' UI Mapper Errors

### ISSUE THREAD

**Issue by plovell** [keycloak/keycloak#24677]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When first creating a new mapper of the type 'Advanced Claim to Group' or 'Advanced Claim to Role' or OIDC or SAML it is possible to make edits after the first time saving the mapper.

If you then try to save those changes, you get an unexpected error and the following exception in the log.

`2023-11-10 11:53:44,357 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-11) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.jpa.entities.IdentityProviderMapperEntity.setIdentityProviderAlias(String)" because "entity" is null
        at org.keycloak.models.jpa.RealmAdapter.updateIdentityProviderMapper(RealmAdapter.java:1417)
        at org.keycloak.models.cache.infinispan.RealmAdapter.updateIdentityProviderMapper(RealmAdapter.java:1152)
        at org.keycloak.services.resources.admin.IdentityProviderResource.update(IdentityProviderResource.java:418)
`

### Version

22.0.3

### Expected behavior

Either I expect the save button to take me back to the mapper screen or for saving changes after having first created the mapper to work and save my new changes

### Actual behavior

An error in the UI and an exception in the log (see description)

### How to Reproduce?

1. Download the latest docker image (I am using FROM quay.io/keycloak/keycloak:22.0.3)
2. Start in dev mode (for simplicity, I don't think this impacts the issue)
3. Add enough information to create a new IDP such that you can access the mappers screen,
4. Create a new 'Advanced Claim to Group' mapper, adding in at least one claim.
5. Click Save, do not navigate away
6. Delete a claim on that page.
7. Save again - the error will show on second Save

**Comment by ssilvert** [comment]
@plovell I have been unable to reproduce this.  Can you give it a try on the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by plovell** [comment]
@ssilvert Thanks for your response.  I have tried this on the nightly build and on the released docker image 23.0.0 and can confirm that this has already been fixed.
