### ISSUE TITLE
Docs: server_admin/topics/realms/proc-using-admin-console.adoc Script that is mentioned is not available

### ISSUE THREAD

**Issue by bloodydragonprincess** [keycloak/keycloak#24681]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

In the File: server_admin/topics/realms/proc-using-admin-console.adoc
The text is

> Enter the username and password you created on the Welcome Page or the add-user-keycloak script in the bin directory. This action displays the Admin Console.

But there is no add-user-keycloak  in the bin directory anymore

### Version

22.0.5

### Expected behavior

Delete the part "or the add-user-keycloak script in the bin directory" or describe another way to add a user over the command line

### Actual behavior

> Enter the username and password you created on the Welcome Page or the add-user-keycloak script in the bin directory. This action displays the Admin Console.

there is no add-user-keycloak  in the bin directory anymore

### How to Reproduce?

Looking into the bin Folder

**Comment by stianst** [comment]
Fixed already
