### ISSUE TITLE
Mapper Option "Add to access token" Toggled Off Despite Claim Added to Token

### ISSUE THREAD

**Issue by patrickjennings** [keycloak/keycloak#24718]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

There was a change where the option "Add to access token" is being exposed in the admin UI, for at least the Audience Resolve mapper. Prior versions of Keycloak, this option was not available through the UI.

Since this change, there is some confusion because the option will display as toggled off in the admin UI, yet the claim will actually be added to the access token. The mappers are missing the "config" attribute for the option since they were created prior to this change. The backend services that process the mapper are handling this missing attribute differently despite what is being displayed in the UI.

This might be an issue with the "Add to token introspection" option as well.

### Version

nightly

### Expected behavior

The behavior of the "Add to access token" option displayed by the admin UI should be the same as what happens when processed by the backend services.

### Actual behavior

Option is displayed as toggled off. Yet claim is added to the token.

### How to Reproduce?

We are upgrading from Keycloak 18 -> snapshots of nightly.

Create a Audience Resolve mapper on a client or client scope in a prior version of Keycloak.
Notice there are no options for "Add to access token" / "Add to token introspection".
Upgrade to the latest nightly version.
Notice that the options  "Add to access token" / "Add to token introspection" are now visible on the mapper. These options are showing toggled off in the UI, indicating that the claim will not be added to the token.
Go through the auth flow and notice that the claim is added to the token.

### Anything else?

Related changes: https://github.com/keycloak/keycloak/pull/22148

**Comment by jsorah** [comment]
@pedroigor @mposolda 

I'm wondering if the client scope config `access.token.claim` for the audience resolve mapper should be backfilled with its "legacy" value during a DB migration for this KC version?

**Comment by pedroigor** [comment]
If you are not yet working on it, please assign to me and I'll also evaluate the problem based on your input. It will be better if we don't need to run any migration.

**Comment by mposolda** [comment]
+1 that it will be good if we can make it working without migration running. So we can make sure that we return `effective configuration values` from the mapper endpoint.

**Comment by hmlnarik** [comment]
I agree that having it fixed without migration is a better way forward. I am removing the UI team label and unassigning myself but if there is anything UI can help with, feel free to reach out.
