### ISSUE TITLE
Message bundles for Custom Locales containing "_" and "-" are not working

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#24735]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have cases, where we need to have custom locales, like:
- us_en (Region: US, Language: English)
- us_de (Region: US, Language: German)
- de_de (Region: German, Language: German)
- de_en (Region: German, Language: English)

The issue is that after adding the custom locales (using the REST API, as it is not possible via the UI, described in https://github.com/keycloak/keycloak/issues/24380), the custom locales cannot have any **Message Bundles added**. There is similar issue with locales, having "-", like:
de-us, de-de
For the Locales, having "_", it always renders them as "und", and the only locale, which works, is the locale "und" (example below).
For locales having "-", it always fallback to the main locale (for de-us, fallback to de).

### Version

22.0.5

### Expected behavior

The custom Locales to be rendered properly and the Message bundle to be used as defined for the Login and other pages.
For locales like "de-de", first to use the Message Bundles for "de-de" if any, then fallback to "de", then to the Default Language.
For locales like "de_de", to use the Custom Locale, then fallback to the Default Language if not defined.

### Actual behavior

1. For locales, having "_"
Example for locale "de_de".
- It does not render as per the Message Bundle created for "de_de"
- In the Login screen dropdown, it renders "und" when the language is selected instead of "de_de" or the added "locale_de_de"
- In the Message Bundles we can add "und" Locale, and some key/values, for example "locale_und", then when select "de_de", it will use the locale_und translation

----

The same behaviour is observed, when
- locale with just 1 char is used ("a" for example)
- locale with more than 8 chars is used ("asdfghjkl" for example)

2. For locales having "-"
Example for locale "de-us"
- It does not render as per the Message Bundle created for "de-us"
- It fallback to the "de" locale translations (default or with message bundle)
- In the Login screen dropdown, it renders "de-US" when the language is selected instead of "de-us" or the added "locale_de_us"

----

Similar behaviour is observed when capital letters used ("usDe" or "usDe") for example

### How to Reproduce?
1. Add custom **supportedLocales** using the Keycloak REST API
```
"supportedLocales": [
        "en", "de", "de_us", "de-us", "und"
    ],
```
2. Add Message Bundles for **loginTitleHtml** for example.
3. Go to the Login Page
4. Change the Languages/Locales to de_us or de-us

![2023-11-14_09h08_07](https://github.com/keycloak/keycloak/assets/33352511/180136b7-6096-408e-8f62-ec7f4aa1f8d5)

### Anything else?

It might be good to fix this directly when working on https://github.com/keycloak/keycloak/issues/24380
This behaviour is not new, as in KC 19 it is the same.

**Comment by danielFesenmeyer** [comment]
It's basically the same problem as described in [this comment (point 5)](https://github.com/keycloak/keycloak/issues/24380#issuecomment-1811001699). Locales like us_en are interpreted by the Java Locale class as undefined, which leads to the strange behavior.

**Comment by edewit** [comment]
These screens where not intended to add new languages, only to add overrides to existing ones

**Comment by mpalavrov** [comment]
Hi @edewit,
Even if this was the intention, it is very real use-case, where customers want to have custom locale (different than the pre-defined ones), which can be achieved currently only via the REST API, but the Message Bundles are not working for some of the custom locales. Currently a work-around is to use locale like **deus** instead of **de_us** for example.

**Comment by edewit** [comment]
@mpalavrov The way locales work are per "theme" so when you add them in "admin" they are not there in "login" that's why your test with `locale_de-us` doesn't work for the "login". In the admin ui we don't use this `local_` prefix instead we us the name of the language.

The way to add a locale is by extending the theme this can be done by creating a folder in the `themes` directory. In there you add a `theme.properties`  with the following:

```properties
parent=keycloak.v2
locales=de-CH,de-us
```
Extend the existing admin console and add these locales
Also then add the message bundles, then your directory looks like this:
```
.
└── test
    └── admin
        ├── messages
        │   └── messages_de_CH.properties
        └── theme.properties
```
Select that theme in the admin-ui:
![image](https://github.com/keycloak/keycloak/assets/51133/f7e8d4b0-daf5-467c-98da-cc63d39e63ec)

Then on the localisation tab you can select these languages:
![image](https://github.com/keycloak/keycloak/assets/51133/c617dd76-6008-46c7-9b83-dc3d9a05c505)

If you want to have these labels for login, you'll have to create a login folder within this `themes/test` folder add a theme.properties there as well with:

```properties
parent=keycloak
import=common/keycloak
```

and your message bundle:

```
.
└── test
    ├── admin
    │   ├── messages
    │   │   └── messages_de_CH.properties
    │   └── theme.properties
    └── login
        ├── messages
        │   ├── messages_de_CH.properties
        │   └── messages_de_US.properties
        └── theme.properties
```
In my messages_de_CH.properties I put:
```
locale_de-CH=Super German
locale_de-us=American German
```
then select it again in the "Themes" tab and then when I select Swiss German as language I see the translated locale:
![image](https://github.com/keycloak/keycloak/assets/51133/5dc49303-2ff6-4deb-837d-83cf4775c53c)

We are planning to make it more clear where translations are coming from in the future though, hope this helps

**Comment by mpalavrov** [comment]
Hello @edewit,
Thank you for the explanation provided. Anyway, I don't agree with it, as it is not completely true.
For example, for locales, that does not contain any "-", "_", "one character locale", "more than 8 chars locale", it works.
If I use only "usde", "usen", or similar, it is OK
![image](https://github.com/keycloak/keycloak/assets/33352511/efe93f57-daa3-474f-828e-7137564fb07e)
![image](https://github.com/keycloak/keycloak/assets/33352511/daf222c4-ff22-4279-a8e0-cb493e313590)
![image](https://github.com/keycloak/keycloak/assets/33352511/558921ca-b353-46e8-8fe5-9629ad460c70)

and here you can see, when the "usde" locale is selected, this time it is not "und", but is the **locale_usde** key value specified:
![image](https://github.com/keycloak/keycloak/assets/33352511/58dd58f9-b6aa-41e7-8b87-c3ce10c4bab5)

It might be true that it will work if I add the locale directly in the theme, but it is not very convenient and in my opinion, not correct. It is clearly a bug, as it works for some, but does not work for others. In addition, the

**Comment by edewit** [comment]
I'm just saying how it should work, but there is no issue here it also works for when you do it your way, but when you create the locale `de-nl` you should name the locale key for the login page `locale_de-nl` and then it will work just fine. But like I said before it's not meant to be used this way it's just for adding overrides to existing bundles that are created the way I described.

We are going to change how this works, but atm this is how it's supposed to be done

**Comment by edewit** [comment]
Feel free to reopen this when you still have problems
