### ISSUE TITLE
SAML ECP does not work on the latest WF/EAP8 

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#24746]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/jee-saml

### Describe the bug

I've just encountered an issue with the SAML ECP(Enhanced Client or Proxy) profile while testing the SAML Adapter on EAP8. There's an incompatibility between Java EE and Jakarta EE, more specifically, 'javax.xml.soap' and `jakarta.xml.soap`. 

This issue will also be seen on the latest WildFly distribution, where the SAML Adapter will be deployed. 

AFAIK, in order to comply with the SAML 2.0 standard, it needs to be fixed.

### Version

22.0.5

### Expected behavior

SAML ECP works

### Actual behavior

SAML ECP does not work - Cannot read the SOAP envelope

### How to Reproduce?

- Deploy the Jakarta SAML Adapter on top of the latest WildFly, or EAP8
- Execute test `SAMLServletAdapterTest#testInvalidCredentialsEcpFlow` with the mentioned app-server

**Comment by mabartos** [comment]
For Keycloak 22.x, I'd propose creating a new Jakarta module for `saml-core` as we probably don't want to change the behavior in minor releases.

For upstream, we could probably make the `saml-core` Jakarta EE compatible, but we'd need to remove the dependants like Jetty, or Tomcat from the codebase.

**Comment by ahus1** [comment]
Set for milestone 22.0.7
