### ISSUE TITLE
Missing Tenant Attribute in JWT Token on First Request Post Cache Eviction

### ISSUE THREAD

**Issue by Arrayly** [keycloak/keycloak#24741]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

The first request for a JWT token made after our scheduled cache eviction results in a token that lacks the "tenant" attribute. This behaviour is consistent and reproducible; it has been observed and documented over several days. Notably, requests for tokens made before the eviction time include the "tenant" attribute as expected.

### Version

22.0.5

### Expected behavior

The JWT token obtained from Keycloak should consistently contain the "tenant" user attribute on all authentication requests, regardless of the cache eviction schedule.

### Actual behavior

The "tenant" user attribute is missing from the JWT token on the first authentication request made immediately after the daily cache eviction time but reappears in tokens from subsequent requests.

### How to Reproduce?

- Login to the dashboard -> User Federation -> Custom Provider. Set cache policy to EVICT_DAILY with eviction time 11:57 AM (cache eviction schedule).
- Restart the server
- Request a JWT token before eviction time (11:57). The token received includes the "tenant" attribute:

`curl -X POST http://localhost:8080/realms/xxxxxx/protocol/openid-connect/token \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "client_id=xxxxx" \
-d "grant_type=password" \
-d "username=xxxx.xxxx@xxxx.com" \
-d "password=xxxxx"
{"access_token":"eyJhbGciOiJs.....","token_type":"Bearer","not-before-policy":0,"session_state":"c37c790b-0f9d-4414-9556-2110eb745b70","scope":"profile email"} `

JWT Token Value:

`{
  "exp": 1699959657,
  "iat": 1699959357,
  "jti": "93d16250-2435-45d1-8b6a-c65f03fc9660",
  "iss": "http://localhost:8080/realms/xxxxx",
  "aud": "account",
  "sub": "f:750ed672-258e-4fea-bacf-dcbe3c6cf1f1:xxxx.xxxx@xxxxx.com",
  "typ": "Bearer",
  "azp": "xxxxx",
  "session_state": "c37c790b-0f9d-4414-9556-2110eb745b70",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:8080",
    "http://localhost"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "profile email",
  "sid": "c37c790b-0f9d-4414-9556-2110eb745b70",
  "email_verified": true,
  "name": "xxxxx xxxxx",
  "preferred_username": "xxxx.xxx@xxx.com",
  "given_name": "xxxxx",
  "family_name": "xxxxx",
  "tenant": "xxxxx",
  "email": "xxxx.xxxx@xxxx.com"
}`

- Wait for the cache eviction to occur at 11:57 AM.
- At 11:58 AM, post cache eviction, request another JWT token. The token received during this request is missing the "tenant" attribute.
- Any subsequent requests for tokens after the first post-eviction request correctly include the "tenant" attribute, until the next eviction time.

### Anything else?

Traces:
[keycloak.log.zip](https://github.com/keycloak/keycloak/files/13348062/keycloak.log.zip)

<img width="1211" alt="Screenshot 2023-11-14 at 12 20 26" src="https://github.com/keycloak/keycloak/assets/57268763/010eb983-7730-4f20-a391-0096e4b5cc52">
<img width="1506" alt="Screenshot 2023-11-14 at 12 19 38" src="https://github.com/keycloak/keycloak/assets/57268763/6e7afafa-7af2-4d2c-b779-689caa804e7f">

**Comment by Arrayly** [comment]
Hello, can someone please assist me with this?

Thank you!

**Comment by mposolda** [comment]
@Arrayly This looks rather as an issue in your provider implementation. Please re-open if you are able to do more investigation, which would indicate that this issue in Keycloak rather than in your provider (for instance if you are able to reproduce with Keycloak built-in provider like LDAP).
