### ISSUE TITLE
Remove sign out action for offline sessions

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#24763]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

[...] another issue related with same endpoints. When You signout a offline session the endpoint call for delete is /sessions instead /offline-sessions. These cause that the endpoint respond with a 404 and the offline session was not loged out.

_Originally posted by @john2094 in https://github.com/keycloak/keycloak/issues/24523#issuecomment-1806434091_

### Version

nightly

### Expected behavior

Offline session is logged out.

### Actual behavior

404

### How to Reproduce?

See description in this comment: https://github.com/keycloak/keycloak/issues/24523#issuecomment-1806434091

**Comment by hmlnarik** [comment]
@john2094 The offline session cannot be logged out similarly to online sessions for historical reason, for further context check this thread: https://groups.google.com/g/keycloak-dev/c/3eWuGqEdABM/m/0AJiid61CwAJ.

Thus there should be no action for offline session logout, contrary to what is there now. The legacy admin console did not have the ability to destroy offline sessions (revoke offline tokens) either, only the ability to set not-before for a particular user or realm or log out corresponding online session if it existed. This is possible in the current admin console.

![image](https://github.com/keycloak/keycloak/assets/5391360/6ab5e297-c33a-48ad-ac7c-7f356d58d48a)
