### ISSUE TITLE
openid scope specified twice in openid-configuration endpoint response

### ISSUE THREAD

**Issue by patrickjennings** [keycloak/keycloak#24761]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

"openid" will be specified twice in the "scopes_supported" field of the well-known/openid-configuration endpoint response, if there is a custom "openid" client scope created for that realm

### Version

nightly

### Expected behavior

"openid" will be specified once.

### Actual behavior

"openid" will be specified twice.

### How to Reproduce?

Create a client scope named "openid" in the realm.
Query the `/auth/realms/<realm>/.well-known/openid-configuration` endpoint.
See that "openid" is specified twice in the "scoped_supported" field.

### Anything else?

The scope is added to the list here: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/OIDCWellKnownProvider.java#L184C42-L184C42
If an "openid" scope exists on the realm, the scope will be duplicated.
Could make this a Set if we do not care about the "openid" scope being the first position in the list.

**Comment by graziang** [comment]
Closing this cause it was fixed by #26542
