### ISSUE TITLE
Do not use `maven.multiModuleProjectDirectory` in build

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#24781]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Recently use of maven variable `maven.multiModuleProjectDirectory` was introduced in `pom.xml`'s. It is utilized in Javascript build ([link](https://github.com/search?q=repo%3Akeycloak%2Fkeycloak%20maven.multiModuleProjectDirectory&type=code)).

In the code there is warning https://github.com/keycloak/keycloak/blob/07a3def4a27da4a0f6d55feb51db89b6f9c91653/pom.xml#L1895-L1896

The variable is set only during maven build and it is unset if building e.g. in vscode / eclipse. They use different implementation of maven which does not set the variable to project root. 

### Version

main

### Expected behavior

The build should avoid use of maven specific variables that are not supported by IDEs.

### Actual behavior

IDE will run the build with empty install directory, which is interpreted as current directory in each submodule. The files are installed in wrong directories and application cannot be started.

### How to Reproduce?

Open the code in IDE without `maven.multiModuleProjectDirectory` defined. Wait for the project to compile and try to run under debugger.

### Anything else?

Note that it is not possible to work around this problem by executing maven build on command line before build inside IDE, since opening the project in vscode will trigger the `clean` build phase and therefore the previously correctly installed files will be wiped out when opening vscode.

**Comment by tsaarni** [comment]
When running in vscode with [Language support for Java ™ for Visual Studio Code](https://github.com/redhat-developer/vscode-java) this problem can be observed by following errors like this:

```
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'pnpm run build' failed.
...
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: java.io.IOException: Cannot run program "/home/tsaarni/work/keycloak/themes/src/main/resources/theme/keycloak.v2/account/src/node/node" (in directory "/home/tsaarni/work/keycloak/themes/src/main/resources/theme/keycloak.v2/account/src"): error=2, No such file or directory
...
Caused by: java.io.IOException: Cannot run program "/home/tsaarni/work/keycloak/themes/src/main/resources/theme/keycloak/common/resources/node/node" (in directory "/home/tsaarni/work/keycloak/themes/src/main/resources/theme/keycloak/common/resources"): error=2, No such file or directory
...
```

These errors are from`frontend-maven-plugin` when it is executed in various submodules with (effectively) empty `<installDirectory>`.

**Comment by jonkoops** [comment]
I'd be curious how we could work around this issue, I am not aware of an alternative to the `multiModuleProjectDirectory` option, but then again Maven is not my field of expertise.

**Comment by jonkoops** [comment]
Marking this as 'help wanted' and adding it to the backlog. I don't think the team will be fixing this anytime soon, as we have higher priority issues to work on, but we'd be willing to accept a community contribution to clean this up.

**Comment by jonkoops** [comment]
@tsaarni I have created #26461 to resolve this issue, let me know if it's now possible to do stuff in VSCode, which I believe was what you were looking for right?

**Comment by tsaarni** [comment]
@jonkoops Yes exactly. Cool, I will check and comment there!

**Comment by jonkoops** [comment]
Yeah, it's clear we need to get rid of the `maven-replacer-plugin` in general (see #19750). Thanks for testing this!
