### ISSUE TITLE
Not proper remove for nested sub-flows from DB

### ISSUE THREAD

**Issue by savadom13** [keycloak/keycloak#24795]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In Auth flow in UI, when you delete one of the nested levels, the subordinates sub-flow is not removed from DB.
This behavior prevents re-creating sub-flows with the same name.
How we caught it, if you remove sub-flow from UI, you can't restore it with API (from Terraform code).
This is not related to terraform itself, because I can find these records in DB and error `{"errorMessage":"New flow alias name already exists"}` is correct

### Version

20.0.5

### Expected behavior

When you delete sub-flows on any level, all subordinated/underlying should be removed from DB, not only from UI/auth-flow

### Actual behavior

When you delete sub-flows on any level, all subordinated/underlying keeps in DB, but removed from UI

### How to Reproduce?

1 - spin up the smallest dev instance in the docker
[docker-compose.txt](https://github.com/keycloak/keycloak/files/13377646/docker-compose.txt)

2 - login and create an auth flow
3 - create three-level nesting for sub-flow
inspect DB 
`SELECT * FROM public.authentication_flow
where alias like 'flow-a%'`

and can find all 3 sub-flows in the alias field and flow itself.
![2023-11-16_14-18](https://github.com/keycloak/keycloak/assets/20001060/8a4dcfca-f16e-48bd-bca2-bc125266051f)

4a - remove second-level sub-flow
inspect DB 
`SELECT * FROM public.authentication_flow
where alias like 'flow-a%'`
and can find 3rd-level and first-level sub-flows in the alias field.
![2023-11-16_14-12](https://github.com/keycloak/keycloak/assets/20001060/07fdc1c4-76f8-4549-aaa9-aece2a5926de)

(repeat items 1-3)
![image](https://github.com/keycloak/keycloak/assets/20001060/86b9c254-e786-48eb-9fd6-83b6c269dce2)

4b - remove first-level sub-flow
inspect DB 
`SELECT * FROM public.authentication_flow
where alias like 'flow-b%'`
and can find all 3rd-level and 2nd-level sub-flows in the alias field.
![2023-11-16_14-14](https://github.com/keycloak/keycloak/assets/20001060/866e8a2b-d0d7-4d0b-8a25-83ea73bbc4f4)

removing flow itself, also not remove abandoned items
![2023-11-16_14-14_1](https://github.com/keycloak/keycloak/assets/20001060/65c44d4a-cf86-426f-a971-77a3253ff4f7)

**Comment by jonkoops** [comment]
@edewit since you worked on this part of the UI, could you take a look at this?

**Comment by edewit** [comment]
I can confirm this is an issue, even existed in the old console. IMO though this is something that should be solved in the backend

**Comment by mposolda** [comment]
I have some feeling this was recently fixed. Please re-open or comment if the issue is still valid with latest Keycloak nightly or latest Keycloak 24 release (going to be released probably next week).

**Comment by rmartinc** [comment]
@mposolda It's till reproducible.I'll try to send a PR soon and I'll tag it for 25.0.0-

**Comment by rmartinc** [comment]
@mposolda I closed #28428 because it's a duplicate of this one. If we want this backported to 24.x just tag it and I'll prepare the PR.
