### ISSUE TITLE
theme/keycloak.v2 requires 'unsafe-eval' in Content-Security-Policy (CSP)

### ISSUE THREAD

**Issue by m4rc77** [keycloak/keycloak#24802]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

We are running Keycloak with the following **Content-Security-Policy (CSP)** on all our realms including master realm:
 `default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'self'; object-src 'none';`
With the update to **22.0.5** we switched to theme **theme/keycloak.v2** for the **account-console**.

While testing we experienced the problem, that the account console could not be loaded anymore. The Browser-Console showed the following CSP error:

```
14:38:52.601 Uncaught EvalError: call to eval() blocked by CSP. account:340:27
    removeHidden https://keycloak:8544/realms/****/account/?referrer=security-admin-console&referrer_uri=https://keycloak:8544/admin/****/console/#/****/users#state=***&session_state=***&code=***:340
    removeHidden https://keycloak:8544/realms/****/account/?referrer=security-admin-console&referrer_uri=https://keycloak:8544/admin/****/console/#/****/users#state=***&session_state=***&code=***:339
    removeHidden https://keycloak:8544/realms/****/account/?referrer=security-admin-console&referrer_uri=https://keycloak:8544/admin/****/console/#/****/users#state=***&session_state=***&code=***:343
    removeHidden https://keycloak:8544/realms/****/account/?referrer=security-admin-console&referrer_uri=https://keycloak:8544/admin/****/console/#/****/users#state=***&session_state=***&code=***:339
    <anonymous> https://keycloak:8544/realms/****/account/?referrer=security-admin-console&referrer_uri=https://keycloak:8544/admin/****/console/#/****/users#state=***&session_state=***&code=***:346

14:38:52.607 Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). account:340:26

14:38:52.847 Uncaught EvalError: call to eval() blocked by CSP. Main.js:52:24
    removeHidden Main.tsx:70
    removeHidden Main.tsx:74
    <anonymous> Main.tsx:86

14:38:52.849 Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).  2 Main.tsx:70:27
```

### Version

22.0.5

### Expected behavior

Keycloak can be run with a **secure Content-Security-Policy** without any `'unsafe-eval'` in  `script-src`.

### Actual behavior

`script-src 'self' 'unsafe-inline' 'unsafe-eval';` is required in Content-Security-Policy (CSP) when using **theme/keycloak.v2** for account console

The following two lines of theme code that are using javascript `eval(...)` are the source of the problem:

https://github.com/keycloak/keycloak/blob/4be835b9cfa38004f7bf51ed653cf2ce476e4cab/themes/src/main/resources/theme/keycloak.v2/account/index.ftl#L283

https://github.com/keycloak/keycloak/blob/8da7a52969f5dfa1235227646ffb07d6fcee8ef3/themes/src/main/resources/theme/keycloak.v2/account/src/app/Main.tsx#L70

Any use of `eval` in JavaScript or TypeScript should be avoided as it does not allow a secure Content-Security-Policy CSP.

### How to Reproduce?

- **Start Keycloak** as Docker container: `docker run -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -p8080:8080 -ti quay.io/keycloak/keycloak:22.0.5 start-dev`
- Open **Security defenses** on **master realm** (http://localhost:8080/admin/master/console/#/master/realm-settings/security-defenses)
- Configure as **Content-Security-Policy** with the value `default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; form-action 'self'; frame-ancestors 'self'; object-src 'none';`
- Click on the username `admin` on the upper right corner and select **Manage account**
- Account Console **hangs on Account Console loading ...**
- Browser dev-tools do show `Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed  ...`

### Anything else?

The problem can be fixed quickly by replacing

`if (item.hidden && eval(item.hidden))`

with

`if (c.hidden && (c.hidden === 'true' || c.hidden === true)) `

which does the same.

**Comment by jonkoops** [comment]
We do not intent to create a fix for this for V2 of the Account Console. Reason for this being that it will soon be replaced by a newer version, which does not call `eval()` anywhere. If you want to try the new version you can do so by passing `--features=account3` when starting the Keycloak server.
