### ISSUE TITLE
Admin UI Localization not working if fetch of localization fails

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#24803]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The Admin UI is not translated if the call for fetching the localization "/admin/realms/master/localization/en" fails.
One of the scenarios how I got this is users belonging to a group lacking permissions for the master realm experienced a lack of translation in the UI. One workaround for fixing this was adding the "view-realm" permission of the master. 

### Version

22.0.5

### Expected behavior

Admin UI is translated even if the request fails. At least the default translation should be used.

### Actual behavior

![MicrosoftTeams-image (6)](https://github.com/keycloak/keycloak/assets/26387482/54c39445-fb82-4e07-85ee-f01a8020189b)

### How to Reproduce?

1. Block the request URL of the call for localization and refresh the page. Check the screenshot below
![MicrosoftTeams-image (5)](https://github.com/keycloak/keycloak/assets/26387482/85c1733c-9d27-477b-8131-11f8fe3ccb0d)
2. Another way is create a group which don't have master realm permissions, add some users to this group and login with one of the users.

**Comment by jonkoops** [comment]
Hmmm, so if I understand this correctly, if a user does not have the `view-realm` permission it is not possible to get this data? That is certainly a bug. We recently landed some changes around how translations are loaded (see #24316), could you try the [latest nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) and see if the issue persists?

**Comment by antikalk** [comment]
@jonkoops I just checked the nightly and the behaviour is definitly different. I see that the localizations for the admin ui are loaded from the theme resources now and this is of course not requiring any permissions. Blocking the request does lead to the Admin UI not being loaded at all, but I guess that is not a scenerio that would occur. 

Imho I would still like to be able to overwrite the localizations in the admin ui with the `Realm Settings -> Localizations` settings though... these seem not the be applied in the admin ui anymore with the nightly - also meaning that you are not able to provide custom text for User Profile Inputs with this. See my comment here on why I think having the translations only in the theme might bring some disadvantages in this regard: https://github.com/keycloak/keycloak/issues/22431#issuecomment-1807174046 

I think that the message lookup should best work like this:
- Check Theme Resources
- Check Master Realm Translations (these overwrites apply to all realms)
- Check Realm Specific Translations (these overwrites apply only to the realm that you currently have selected in the admin ui e.g. - realm scoped)

... where the theme resources have the lowest and the realm specific translations have the highest priority.

**Comment by jonkoops** [comment]
> Imho I would still like to be able to overwrite the localizations in the admin ui with the `Realm Settings -> Localizations` settings though... these seem not the be applied in the admin ui anymore with the nightly 

That is most certainly a bug. The localization should be loaded **including** the overrides from the realm settings. @edewit do you know why this might not be happening now?

**Comment by antikalk** [comment]
@edewit I just tested it again: I tried translating `titleRoles` and expected the entry in the menu to be translated... My bad, I just used the wrong key! It works fine! :) 

The only thing I am missing for the admin console is, that when you switch to a different realm than master, that the localizations of that realm should again overwrite the once coming from the theme and the master realm.

**Comment by jonkoops** [comment]
> The only thing I am missing for the admin console is, that when you switch to a different realm than master, that the localizations of that realm should again overwrite the once coming from the theme and the master realm.

That sounds like a valid bug, we can add some logic to re-fetch the translations when the realm is switched. Could you log this as a separate issue?

**Comment by antikalk** [comment]
> > The only thing I am missing for the admin console is, that when you switch to a different realm than master, that the localizations of that realm should again overwrite the once coming from the theme and the master realm.
> 
> That sounds like a valid bug, we can add some logic to re-fetch the translations when the realm is switched. Could you log this as a separate issue?

There is already this one: https://github.com/keycloak/keycloak/issues/22431

The issue here can be closed I guess. Thank you! 👍

**Comment by jonkoops** [comment]
Yes, I think we can close this issue. Let us know if this still persists somehow.
