### ISSUE TITLE
Hostname config check on welcome page

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#24815]
### Description

When running Keycloak behind a loadbalancer / reverse proxy, Keycloak needs to know the hostname and schema of the loadbalancer for users to be able to log in for all the redirects. 

A lot of example explain how to set the hostname. Users then fail to log in as the loadbalancer is https, and Keycloak is running without https (which is shouldn't for security reasons). All they see is a blank screen, and only the browser console reveals some details.

It would be good to have a self-check as part of Keycloak's welcome screen which would check that the hostname and schema of the welcome screen match the settings in Keycloak. If they don't match, a descriptive error message should be shown, and logging in to the admin console should be disabled.

### Motivation

Make it simpler for users to spot mis-configurations.

**Comment by ahus1** [comment]
@vmuzikar - please let me know what you think about this idea. I've seen this problem in the community mailing lists / chats several times. Not sure if you have something similar already planned (my GitHub issue search didn't reveal anything). If this makes sense, it would require to pull in the UI team of course to get this started. 

Please let me know what you think about this.

**Comment by vmuzikar** [comment]
@ahus1 Thanks for creating the issue. It is a valid suggestion but it should not be needed once we're done with #24252 which should make the hostname config much clearer.

**Comment by shawkins** [comment]
Based upon recent issues users are still hitting some problems. Not sure if they belong as part of a config check, but it's worth mentioning:

- users continue to set hostname v1 options via env variables
- when setting a full hostname url they may not realize that hostname-strict and proxy-headers are generally ignored. An exception to this is that with a full hostname url the proxy-header setting will still be used in things like the origin check (#31946)

**Comment by vmuzikar** [comment]
> * users continue to set hostname v1 options via env variables

Not sure how this is an issue. For it to work, the user would need to explicitly enable v1, no?

> * when setting a full hostname url they may not realize that hostname-strict and proxy-headers are generally ignored

It'd make sense to at least document this explicitly. We can't probably add validations for it (due to e.g. the aforementioned origin check). @shawkins Could you please open an issue for it as you have more context about it?

**Comment by shawkins** [comment]
> Not sure how this is an issue. For it to work, the user would need to explicitly enable v1, no?

Just to force users to be aware of the transition away from hostname v1. 

In the v25 logs we see:

```
2024-09-23 12:42:29,779 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used run time options are UNAVAILABLE and will be ignored during build time:
 	- hostname-port: Available only when hostname:v1 feature is enabled.
```

In the v26 logs there is no warning.

So someone going straight from 24 to 26, which includes product users, may miss out on seeing a warning related to the continued use of hostname v1 options.

> It'd make sense to at least document this explicitly. We can't probably add validations for it (due to e.g. the aforementioned origin check). @shawkins Could you please open an issue for it as you have more context about it?

Ok, opened #33209 will propose some doc changes for that.

**Comment by vmuzikar** [comment]
> In the v26 logs there is no warning.

Are you suggesting another "support level", something for removed options (in case they are specified via env vars)? That's an interesting idea.

> Ok, opened #33209 will propose some doc changes for that.

Thank you!

**Comment by shawkins** [comment]
> Are you suggesting another "support level", something for removed options (in case they are specified via env vars)? That's an interesting idea.

It could be done as a support level, but really I was just thinking specifically about hostname v1 and those going directly from v24 to v26. If it seems like we'll routinely encounter this, or we want to handle version skipping more generally then a support level seems good.

**Comment by vmuzikar** [comment]
We should not have much more cases like hostname v1 where something's removed without deprecation. So a one-off solution for the v1 env vars would also make sense.

**Comment by shawkins** [comment]
> So a one-off solution for the v1 env vars would also make sense.

Here's a proposal for that: https://github.com/keycloak/keycloak/pull/33261 - it seems straight-forward as a log, rather than something on the welcome page.

The only other thing we could do is add a log about setting proxy-headers. But we could only do that in cases we can detect that proxy use is implied - if the full hostname url scheme or port doesn't match what is configured for the server.
