### ISSUE TITLE
Adding client_id as prefix in client roles mapper

### ISSUE THREAD

**Issue by filipetavares** [keycloak/keycloak#24820]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I'm trying to add `${client_id}` as a prefix in the Client Roles mappers, but its not getting interpolated.
So i'm trying to conver this:
```JSON
{
...
"resource_access": {
    "client_a" : {
       "roles": ["owner", "reader"]
    },
   "client_b" : {
       "roles": ["reader"]
    },
},
...
}
```
To this:
```JSON
{
...
"client_roles": [
  "client_a_owner",
  "client_a_reader",
  "client_b_reader"
 ],
...
}
```
But i'm getting this:
```JSON
{
...
"client_roles": [
  "${client_id}_owner",
  "${client_id}_reader",
  "${client_id}_reader"
 ],
...
}
```
Is this the expected behavior? And if so, is there any other way o adding the client_id as a prefix to the client roles?.

Also, just curiosity, is there any documentation which are the variables that are able to be interpolated across the UI?

Thanks in Advance.

### Version

20.0.5

### Expected behavior

Adding the client_id prefix to the mapper and expecting it to be interpolated

### Actual behavior

The string is not interpolated

### How to Reproduce?

Add ${client_id} the the prefix field on the client_roles builtin mapper

**Comment by jonkoops** [comment]
Hi, like mentioned in the issue template, please test this against the latest Keycloak version. I am closing this issue, but feel free to log a new one if this is still reproducible in the latest version of Keycloak.
