### ISSUE TITLE
Keycloak liveness probe not responding to the postgres database password change

### ISSUE THREAD

**Issue by Dhiraj-Jain** [keycloak/keycloak#24836]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Keycloak is deployed in k8 cluster with postgres database and supplying database credentials through secret. During password rotation, postgres password is getting changed and the secret is updated. When changed, Keycloak is not able to connect to connect to database as database is configured during bootstrap. Startup, Liveness and Readiness probe is set but Keycloak pod is not crashing, and database down is not picked up by Liveness probe. 

### Version

22.0.5

### Expected behavior

Liveness probe should pick up the database down health check so that pod could restart.

### Actual behavior

Liveness probe is not picking up and keycloak pod keeps running and requires manual restarting of the pod.

### How to Reproduce?

1. Deploy Keycloak in a k8 cluster using helm chart.
2. Configure the three probes.
3. Feed the db credentials through secret.
4. Change the password and update the secret.

![image](https://github.com/keycloak/keycloak/assets/64320631/31736564-530a-46a0-9bc1-3370a0e994dd)

Workaround fix:
Put the readiness probe endpoint in liveness to trigger restart
![Untitled](https://github.com/keycloak/keycloak/assets/64320631/12469076-20e9-4a50-804e-af6632b94a23)

**Comment by sschu** [comment]
I would say this works exactly as expected. Liveness probe should indicate if Keycloak is still running (it is), Readyness probe should indicate if it's ready to serve requests (it is not if the DB cannot be connected). If you want to roll your database credentials, you can just trigger a rolling restart when changing the credentials.

However, with only one credential there will be a period where all Keycloak pods cannot connect and need to reboot. I would rather use two different users with different credentials, roll the credentials of the user currently not in use and then switch to that user. This way you won't have a downtime.

**Comment by shawkins** [comment]
Marking as resolved based upon @sschu explanation.
