### ISSUE TITLE
User cannot change email address in "Personal info" form if "Email as username" is enabled

### ISSUE THREAD

**Issue by reimer-atb** [keycloak/keycloak#24859]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When "Email as username" is enabled for a realm, and a user tries to change their email address through the account UI's "Personal info" form (http://localhost:8080/realms/test/account/#/personal-info), the changed email address is not saved. Although the form displays a confirmation message that the change has been saved.

I am not sure if email address should be editable when "Email as username" is enabled. If it is supposed to be editable the change should be saved. If it is not supposed to be editable the account UI should not allow a user to edit it.

### Version

22.0.5

### Expected behavior

User's new email address should be saved.

### Actual behavior

User's email address is not saved, although the UI says that the changes have been saved.

### How to Reproduce?

1. Run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin --rm --name keycloak quay.io/keycloak/keycloak:nightly start-dev`
2. Go to http://localhost:8080/admin/ and login
3. Create a new realm named "test"
4. Go to http://localhost:8080/admin/master/console/#/test/realm-settings/login and enable "Email as username"
5. Go to http://localhost:8080/admin/master/console/#/test/users and click "Add user"
6. Fill the "Email" field with "foo@bar.com" and click "Create"
7. Click "Credentials" and set a permanent password for the new user "foo"
8. In a new browser window go to http://localhost:8080/realms/test/account and click on "Personal info".
9. Log in with user "foo@bar.com"
10. Change the "Email" field to "foo@example.com" and click "Save"
11. The confirmation message "Your account has been updated" is displayed
    ![swappy-20231120_172609](https://github.com/keycloak/keycloak/assets/5737222/d7717a61-b767-443a-8e2b-d5cb908b7590)
13. Click on "Sign out"
14. Click on "Personal info", and try to login with "foo@example.com"
15. "Invalid username or password" is displayed
    ![swappy-20231120_173148](https://github.com/keycloak/keycloak/assets/5737222/0767bf24-c4df-4869-af0f-275de0dde860)
17. Try to login again, this time using the old email "foo@bar.com"
18. Login succeeds and the "Email" field still displays "foo@bar.com"
19. Go to http://localhost:8080/admin/master/console/#/test/users and login as admin.
20. The "User list" displays the old email address "foo@bar.com" in the "Username" and "Email" column.

**Comment by pedroigor** [comment]
This looks like a bug in the account console UI because e-mail should be read-only if the `Edit username` is disabled. If this setting is enabled then you should be able to change the e-mail.

**Comment by Joren-Thijs-KasparSolutions** [comment]
Similar weird behaviour is going on in the Account setup https://github.com/keycloak/keycloak/issues/24854

**Comment by pedroigor** [comment]
It is out dated and the issue should be fixed in Keycloak 24.

**Comment by yassineraddaoui** [comment]
same here 2025 April
