### ISSUE TITLE
Inconsistency in the Admin UI handling of "Email as Username"  and "Edit username" settings.

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [keycloak/keycloak#24854]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

For a while now Keycloak has supported configuring the email as the username. And for a while now it has confused server admins. 

Today I did some testing and found a set of bugs/inconsitencies.

In keycloak 22.x There is support for configuring the Email as the username.

When doing so the Email address and username become linked. When a user changes their email they in turn also update their username. Keycloak also has a setting te restrict the editing of usernames. When these two settings are combined you can get some interesting results.

the first set of qwerks can be observed in the User account console's personal info section.
The other set are in the update profile screen for new users.
The steps and behaviour are documented below.

### Version

22.03 & 22.05

## Scenario 1
Configure keycloak with "Email as username" and "Edit username" Off.

### Account setup email
Invite new user -> User clicks setup account email -> user is asked for First and lastname -> user sets password

### User Account console
User visits account console to change personal info -> Email field is shown but is grayed out since it cannot be changed anyway.

## Scenario 2
Configure keycloak with "Email as username" and "Edit username" On.

### Account setup email
Invite new user -> User clicks setup account email -> user is asked for Email, First and lastname -> user sets password
Editing Email at this stage is allowed although a bit weird. When doing so this is refected internally by also changing the username.

### User Account console
User visits account console to change personal info -> Email field is shown and enabled since it can be changed (The username field is not shown). When changing the users email both the email and username is updated.

## Scenario 1
Configure keycloak with "Email as username" and "Edit username" Off.

### Account setup email
Invite new user -> User clicks setup account email -> user is asked for Email, First and lastname -> user sets password.
When user edits the email the changes to the email are not persisted and thus this field should not be showed.
Changing it also triggers no error or warning in the admin UI.

### User Account console
User visits account console to change personal info -> Email field is shown and enabled. The user can edit the value and click save. Upon save Keycloak reports that changes are saved succesfully. However upon refreshing it is clear no values where changed. To the user it is not clear this is configured this way and appears as a bug.

## Scenario 2
Configure keycloak with "Email as username" and "Edit username" On.

### Account setup email
Invite new user -> User clicks setup account email -> user is asked for Username, Email, First and lastname -> user sets password
Username is shown as a seperate field during account setup. This field is prefilled with the current email but changing it has no affect because the changes are not persisted. If the user edits the Email field those changes are persisted and both the Email and username are updated with the new value

### User Account console
User visits account console to change personal info -> Email field is shown and enabled since it can be changed (The username field is not shown). When changing the users email both the email and username is updated.
**This works as intended**

### How to Reproduce?

- Spin up a local keycloak
- Create a realm
- setup a smtp server
- configure "Email as username" and  and "Edit username" Off.
- create a user with only their email and send them an update account email.
- see problems
- navigate to {host}/realms/{realm}/account and login
- go to personal information
- see problems

- configure "Email as username" and  and "Edit username" On.
- create a user with only their email and send them an update account email.
- see problems
- navigate to {host}/realms/{realm}/account and login
- go to personal information
- see problems

**Comment by jonkoops** [comment]
@Joren-Thijs-KasparSolutions we recently landed a lot of changes for this behavior when the user profile feature is enabled. Could you check this under the nightly version with user profile enabled and see if that solves these inconsistencies for you? It will eventually become the default behaviour in a future Keycloak version.

**Comment by Joren-Thijs-KasparSolutions** [comment]
@jonkoops I did some testing on the nightly build and from what i can conclude the situation has not changed.

I have again included my steps below with screnshots to hopefully better illustrate the problems. Hope it helps!

my docker compose file:
```yaml
version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:nightly
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    restart: unless-stopped
    command: ["start-dev"]
    networks:
      - keycloak_network

  mailserver:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - keycloak_network

networks:
  keycloak_network:
```

steps:
- start docker compose
- go to keycloak on http://localhost:8080
- create "test" realm
- configure realm with username as email and edit username off
- setup smtp settings
![image](https://github.com/keycloak/keycloak/assets/93926934/17e7a1fc-b0dd-4cfc-9709-5e0a33014597)
- Verify email by going to mailserver webpage http://localhost:8025
- Add user with example email john@example.be
- Trigger a credential reset for the user with an update profile action
- go to the mailserver webpage and click on email
- verify behaviour

## Scenario 1
Configure keycloak with "Email as username" and "Edit username" Off.
![image](https://github.com/keycloak/keycloak/assets/93926934/1f8accc5-5bdf-4cc6-872e-fe281608e1a2)


### Account setup email
Invite new user -> User clicks setup account email
![image](https://github.com/keycloak/keycloak/assets/93926934/4b4f9c22-2342-4c30-acee-24610f713b9a)

Johns email is prefilled
![image](https://github.com/keycloak/keycloak/assets/93926934/d6d0cf1a-8699-42b6-a2b2-9d62780804b1)

John attempts to edit his email (and thus username)
![image](https://github.com/keycloak/keycloak/assets/93926934/491b8948-ca14-4630-9985-692c60eb1867)

This is accepted without error.
![image](https://github.com/keycloak/keycloak/assets/93926934/5dd7e4ae-dc84-4bad-9557-46b8b3697acd)

In the user section we can see john's email and usernames are unchanged
![image](https://github.com/keycloak/keycloak/assets/93926934/eb29982e-c2c9-443d-bd16-6f3d34650d6f)

### User Account console
User visits account console to change personal info -> Email field is shown and enabled. 
![image](https://github.com/keycloak/keycloak/assets/93926934/af1501ff-79a7-4e87-a44b-a04b6e7105db)

The user can edit the value and click save. Upon save Keycloak reports that changes are saved succesfully.
![image](https://github.com/keycloak/keycloak/assets/93926934/b2930353-aa5e-4696-a56e-40471f459ecb)

 However upon refreshing it is clear no values where changed. To the user it is not clear this is configured this way and appears as a bug.
![image](https://github.com/keycloak/keycloak/assets/93926934/61c158f9-05ea-4b19-a7b9-2a0cee23e41c)

## Scenario 2
Configure keycloak with "Email as username" and "Edit username" On.
![image](https://github.com/keycloak/keycloak/assets/93926934/a2ea4520-e84d-441f-9e1e-3386c837a301)

### Account setup email
Invite new user -> User clicks setup account email
![image](https://github.com/keycloak/keycloak/assets/93926934/8830c516-c895-4b10-9afc-78c1a75ab3b7)

user is asked for Username, Email, First and lastname
![image](https://github.com/keycloak/keycloak/assets/93926934/b550fcfb-c9ad-4ec1-9616-707f28839a72)

user attempts to change only their username
![image](https://github.com/keycloak/keycloak/assets/93926934/d870226f-e46d-451a-bfe0-6d7e16268d7d)

form is accepted
![image](https://github.com/keycloak/keycloak/assets/93926934/ef2dd695-61b1-46f9-bc00-1259ae95939e)

but username change is not persisted
![image](https://github.com/keycloak/keycloak/assets/93926934/deaf4200-888c-4114-bd46-42f26311dfe6)

lets try again
![image](https://github.com/keycloak/keycloak/assets/93926934/68a226f8-e39f-4732-b2d7-9fdfa99097de)

Invite new user -> User clicks setup account email
![image](https://github.com/keycloak/keycloak/assets/93926934/8830c516-c895-4b10-9afc-78c1a75ab3b7)

user is asked for Username, Email, First and lastname
![image](https://github.com/keycloak/keycloak/assets/93926934/b550fcfb-c9ad-4ec1-9616-707f28839a72)

user attempts to change only their email
![image](https://github.com/keycloak/keycloak/assets/93926934/c530697b-a18b-478f-9c03-e2ea9a6e992e)

form is accepted
![image](https://github.com/keycloak/keycloak/assets/93926934/200ae56b-0a98-4b88-8be6-050027f624bc)

Now the change has actually been persisted and both email and username are updated
![image](https://github.com/keycloak/keycloak/assets/93926934/58068a82-bc5e-4444-aef0-42c59de10d7b)

**Since this is the case there is no reason for the username field to be shown.**

### User Account console
User visits account console to change personal info -> Email field is shown and enabled since it can be changed (The username field is not shown).
![image](https://github.com/keycloak/keycloak/assets/93926934/07438d69-de7a-485b-b270-4bbc71380865)

user updates their email, these changes are persisted
![image](https://github.com/keycloak/keycloak/assets/93926934/646b142b-515c-4e31-85dc-1b509ace2ae6)

 When changing the users email both the email and username are updated.
![image](https://github.com/keycloak/keycloak/assets/93926934/17649e19-7b89-4fde-93f4-fd7377b42fb9)

**This works as intended**

**Comment by jonkoops** [comment]
@Joren-Thijs-KasparSolutions I see you had not enabled the User Profile in your config. Could you [enable](https://www.keycloak.org/server/features) the `declarative-user-profile` feature? Our intention is to make this behaviour the default in a future Keycloak version.

**Comment by edewit** [comment]
@Joren-Thijs-KasparSolutions I think these things are fixed when you enable user profile as suggested by @jonkoops, go to realm settings and enable it:
![image](https://github.com/keycloak/keycloak/assets/51133/3f17f157-c4a9-45a4-8894-f4f5a0bdd5b5)

**Comment by ssilvert** [comment]
@Joren-Thijs-KasparSolutions I agree with @edewit.  The behavior seems to be correct in the nightly build with User Profile and the account console v3.

I'm going to go ahead and close this, but we can reopen if you still see issues on the latest build.
