### ISSUE TITLE
Keycloak 22.x no longer accepts a * as wildcard for redirect_uri

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [keycloak/keycloak#24851]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In Keycloak 21.x and earlier we used a * as redirect uri to be used as a wildcard. This allowed us to use any redirect uri we wanted in development and was especially usefull while experimenting with multitenancy and Android App Links.

After upgrading to Keycloak V22.0.3 this no longer works. Keycloak only accepts a redirect uri upon login if its an exact match or using a partial wildcard eg: https://localhost:3001/*. However keycloak does still allow you to configure it in the admin UI despite it not working.

![image](https://github.com/keycloak/keycloak/assets/93926934/c3dd37e0-84b4-4cb0-b06b-c26a370addd7)

### Version

22.0.3

### Expected behavior

Keycloak accepts * as a redirect_uri wildcard and allows me to not care about the redirect_uri in development environments.

### Actual behavior

Keycloak does not accept * as a redirect_uri anymore making it harder to prototype login flows.

### How to Reproduce?

- Install Keycloak.
- Create realm
- Create Client
- Configure Client with [Client authentication Off], [Authorization Off], ["Authentication flow" "Standard flow"]
- Configure "Valid redirect URIs" and "Valid post logout redirect URIs" as * leaving "Root URL" empty.

try to login with any redirect_uri. Keycloak will return an error saying invalid redirect_uri.

**Comment by Joren-Thijs-KasparSolutions** [comment]
Yes and No I generally want to report the difference in behaviour between v21.x and 22.x. 
But also want to ask, if this is intentional then why does the UI let me configure it this way? If this bug needs to be logged under a different category please let me know.

**Comment by jonkoops** [comment]
> if this is intentional then why does the UI let me configure it this way?

It might be someone made changes to the API without also updating the client-side of things. Sometimes that is forgotten.

> If this bug needs to be logged under a different category please let me know.

No worries, it just helps us get it solved faster if things are assigned to the right team.

**Comment by Joren-Thijs-KasparSolutions** [comment]
> It might be someone made changes to the API...

If this is the case then I hope there is a reason for this API change?
I couldn't find any mention of it in the [server migration guide](https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-22-0-2) or the [release notes](https://www.keycloak.org/2023/07/keycloak-2200-released.html).

I am basically trying to figure out if this is a change in how keycloak works or a bug? Since i do like being able to not worry about the redirect uri when prototyping.

**Comment by jonkoops** [comment]
@keycloak/core can someone provide an answer for this?

**Comment by rmartinc** [comment]
@jonkoops @Joren-Thijs-KasparSolutions This was announced in the [release docs](https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-21-1-2) for 21.1.2. It was a security issue. Now `*` is only valid for `http(s)` schemes, if you are using another custom scheme you need to at least specify the scheme  (for example `custom:*`).

**Comment by jonkoops** [comment]
Perhaps it might be worthwhile to update the help text with some more detailed instructions?

**Comment by slominskir** [comment]
This problem appears to be worse in the latest version of Keycloak (v23.0.3).   In particular even http(s) schemes don't appear to honor wildcards the same way as before: specifically URL parameters (and possibly URL fragments) are not longer allowed even with trailing wildcard (*) .   Should I create a separate issue or just piggy back on this one?

See: https://github.com/keycloak/keycloak/discussions/25684

**Comment by rmartinc** [comment]
I'm closing this as it's working as expected. Any non http(s) scheme needs direct configuration to avoid dangerous schemes like javascript or data. I think that the help texts don't need any clarification because they never comments about adding the open `*`. That open redirect configuration is totally not recommended, so better don't comment about it. As documented in different places the more specific valid redirect configuration the better.
