### ISSUE TITLE
"First name" and "Last name" fields are mandatory in "Personal info" form for no reason

### ISSUE THREAD

**Issue by philipreimer** [keycloak/keycloak#24857]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When a user tries to edit their "Personal info" (like changing their email address) through the account UI (localhost:8080/realms/test/account/#/personal-info, they are forced to provide a "First name" **and** "Last name". Even if the user was originally created without specifying a first or last name.

There is no need to require a first or last name. In fact, to conform to GDPR recommendation of "data minimisation" all user data except the minimum required amount should be optional.

Because the user can be created in the admin UI without specifying a first or last name those are clearly not required, and a user should not be forced to provide them when editing their own data.

### Version

22.0.5

### Expected behavior

User should be allowed to update their personal info without having to provide a first or last name.

### Actual behavior

User is forced to provide first and last name.

![swappy-20231120_135220](https://github.com/keycloak/keycloak/assets/5737222/420eb323-33b1-43e5-b3e1-586fdc56c0eb)

### How to Reproduce?

1. Run `docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin --rm --name keycloak quay.io/keycloak/keycloak:nightly start-dev`
2. Go to http://localhost:8080/admin/ and login
3. Create a new realm named "test"
4. Go to http://localhost:8080/admin/master/console/#/test/users and click "Add user"
5. Fill the "Username" and "Email" fields with "foo" and "foo@bar.com", respectively, and click "Create" - do *not* set a "First name" or "Last name".
6. Click "Credentials" and set a permanent password for the new user "foo"
7. In a new browser window go to localhost:8080/realms/test/account and click on "Personal info".
8. Log in with user "foo"
9. Change the "Email" field
10. Click "Save"

**Comment by pedroigor** [comment]
The first and last names are currently mandatory when on user-facing pages like the account, registration, and update profile pages.

However, that is no longer true once you enable the declarative user profile [1]. When using this feature, administrators can configure, among other things, if/when an attribute is required.

I'm closing this one as we are not going to change the behavior for both fields in the static user profile but deliver a more flexible solution to manage user attributes with the declarative user profile.

[1] https://www.keycloak.org/docs/latest/server_admin/#user-profile
