### ISSUE TITLE
Get role ID by Keycloak REST API

### ISSUE THREAD

**Issue by leoguillaumegouv** [keycloak/keycloak#24853]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

#### Before reporting an issue
- [x] I have searched existing issues
- [ ] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

#### Area
admin/api

### Version

Keycloak Server version (docker image): quay.io/keycloak/keycloak:21.0

#### Description

All call to retrieve Role ID doesn't work, I receive 404 not found error for the following endpoints : 
`/{realm}/clients/{id}/roles` or 
`/{realm}/clients/{id}/roles/{role-name}`

Deal with [documentation](https://www.keycloak.org/docs-api/21.1.1/rest-api/#_roles_resource), I call this endpoints to retrieve role ID (I get the ID of the client with  ` /admin/realms/{realm}/clients ` endpoint, => client "realm-management") : 
`/{realm}/clients/{id}/roles` or
`/{realm}/clients/{id}/roles/{role-name}`  (with role-name "realm-admin")

Both return 404 not found error.

### Expected behavior

Deal with [documentation](https://www.keycloak.org/docs-api/21.1.1/rest-api/#_roles_resource), the expected response is [RoleRepresentation](https://www.keycloak.org/docs-api/21.1.1/rest-api/#_rolerepresentation)<html>

### Actual behavior

Actual response : 

``` {'_content': b'{"error":"RESTEASY003210: Could not find resource for full path: https://xxxxxxxxx/auth/clients/55bda90b-efc3-4b6e-9130-e37120e36bab/roles"}',
 '_content_consumed': True,
 '_next': None,
 'status_code': 404,
 'headers': {'Server': 'nginx/1.24.0', 'Date': 'Mon, 20 Nov 2023 14:51:00 GMT', 'Content-Type': 'application/json', 'Content-Length': '167', 'Connection': 'keep-alive', 'Referrer-Policy': 'no-referrer', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block'},
 'raw': <urllib3.response.HTTPResponse at 0x11782968e80>,
 'url': 'https://xxxxxxxxx/auth/clients/55bda90b-efc3-4b6e-9130-e37120e36bab/roles',
 'encoding': 'utf-8',
 'history': [],
 'reason': 'Not Found',
 'cookies': <RequestsCookieJar[]>,
 'elapsed': datetime.timedelta(microseconds=21878),
 'request': <PreparedRequest [GET]>,
 'connection': <requests.adapters.HTTPAdapter at 0x117828eb160>}
``` 

### How to Reproduce?

realm="my_app"
I retrieve the ID of the client realm-management  with this endpoint : ` /admin/realms/{realm}/clients `: OK
id = XXXXX

Call this endpoints to retrieve role ID : 
`/{realm}/clients/{id}/roles` or 
`/{realm}/clients/{id}/roles/{role-name}`

**Comment by sschu** [comment]
I cannot reproduce this. I can just go to the admin console, go to the realm-management client, select the roles tab. This calls exactly the endpoint you mentioned and it works without problems.

**Comment by rmartinc** [comment]
@leoguillaumegouv I think the endpoint is OK, as @sschu commented you can check with the console, start the browser developer tools and go the console and check the requests and responses. Note that the console uses the admin REST API to work, so, if the console works, the endpoints are working too.
