### ISSUE TITLE
Transaction timeout and rollback when fetching events

### ISSUE THREAD

**Issue by mnad-umboss** [keycloak/keycloak#24884]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Greetings,

We have encountered sporadic database transaction timeouts when our application tries to retrieve events from Keycloak by calling the /admin/realms/{realm}/events GET endpoint:

> 2023-11-21 12:33:58,540 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffffc0a83249:91f5:64f07ccb:2eda8b6 in state  RUN

Setup:
- Keycloak 21.1.1 (Quarkus), single instance
- PostgreSQL 14.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit, single instance

In our environment, this request completes successfully in around 3 seconds most of the time, but fails with the error mentioned above once every few days. The table event_entity in this environment contains approximately 8 million records:

> select count(*) from event_entity;

> 8390220

I have inspected Postgres logs and I can see the query executed by Keycloak when our application calls the /events endpoint with "user", "type", and "dateFrom" query parameters:

```
select evententit0_.ID           as id1_21_,
       evententit0_.CLIENT_ID    as client_i2_21_,
       evententit0_.DETAILS_JSON as details_3_21_,
       evententit0_.ERROR        as error4_21_,
       evententit0_.IP_ADDRESS   as ip_addre5_21_,
       evententit0_.REALM_ID     as realm_id6_21_,
       evententit0_.SESSION_ID   as session_7_21_,
       evententit0_.EVENT_TIME   as event_ti8_21_,
       evententit0_.TYPE         as type9_21_,
       evententit0_.USER_ID      as user_id10_21_
from event_entity evententit0_
where evententit0_.REALM_ID = 'realmname'
  and (evententit0_.TYPE in ('LOGIN_ERROR'))
  and evententit0_.USER_ID = 'f57efd9d-6f64-4a96-ac5b-0be2f13e147a'
  and evententit0_.EVENT_TIME >= 1697925600000
order by evententit0_.EVENT_TIME desc
limit '100';
```

At most times, there are multiple users present that frequently log in to our application using the OAuth2 Authorization Code Grant, so I suspect that there is another query active at the same time as the query mentioned above that causes them both to reach a deadlock. In the logs, it can be seen that TransactionReaper rolls back the transaction after 60 seconds. The logs are attached.

[keycloak-logs.txt](https://github.com/keycloak/keycloak/files/13427246/keycloak-logs.txt)

### Version

21.1.1

### Expected behavior

Fetching events from the API should not sporadically cause Keycloak to encounter database deadlocks and requests to stall and not complete successfully.

### Actual behavior

The GET /admin/realms/{realm}/events invocation periodically stalls for 60 seconds and fails after the transaction that should have retrieved the event records is rolled back.

### How to Reproduce?

I am not entirely sure how to reproduce the problem because it happens rarely, however, it is certainly linked to calling the /admin/realms/{realm}/events endpoint. Most likely, the error occurs when there is another database query that holds a lock on the same tables as the query used on the /admin/realms/{realm}/events endpoint. Possibly, the cause can be deduced by examining the attached logs.

**Comment by stianst** [comment]
Afraid we can't look into this without a reproducer, so closing this one.
