### ISSUE TITLE
Race condition on resources updated by config property synchronizer

### ISSUE THREAD

**Issue by kherock** [keycloak/keycloak#24894]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When an update occurs on resource that requires synchronization with other resources, there seems to be a small window where those changes can be rolled back by the synchronizer or left in an inconsistent state. Given the following events,

<img width="1205" alt="image" src="https://github.com/keycloak/keycloak/assets/4993980/73880a27-81c9-4fb0-b6a0-f301850ace86">

my Keycloak instance ended up in a state where the update applied by the `IDENTITY_PROVIDER_MAPPER` event seemed to have been rolled back entirely. In another instance (our production environment unfortunately), we ended up in an inconsistent state where Keycloak reported server errors since the mapper type changed (oidc-group-idp-mapper -> oidc-advanced-group-idp-mapper), but some of the required fields did not.

### Version

21.1.1

### Expected behavior

I think the code here needs to evaluate in a blocking manner

https://github.com/keycloak/keycloak/blob/59823a301ac028635cb85da91ff1f2c202ce75d8/server-spi-private/src/main/java/org/keycloak/broker/provider/mappersync/AbstractConfigPropertySynchronizer.java#L42-L69

### Actual behavior

Simultaneous updates of both the group and the IDP mapper seem to result in Keycloak ignoring the IDP mapper update.

### How to Reproduce?

I'm currently using the [terraform-provider-keycloak](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs) project to orchestrate these changes. This issue should be reproducible by constructing a configuration that deploys both a group/role and an IDP mapper and then subsequently deploying a change that both renames the group/role and changes a configuration value on the IDP mapper.

**Comment by pedroigor** [comment]
This one needs more investigation but I suspect the description from @kherock makes sense and we need to make sure there is no inconsistency when running those "synchronizers" when updating mappers at the same time.

**Comment by sguilhen** [comment]
This should be resolved by https://github.com/keycloak/keycloak/issues/32233 as the synchronizers each update only the mappers affected by the changes (role, group, etc) independently from one another.
