### ISSUE TITLE
User details tab does not display or update attibutes with dot

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#24918]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When a user profile attribute contains a dot like "with.dot", the user details tab fails to display and update the value of this attribute.

Stored values are not displayed:
![image](https://github.com/keycloak/keycloak/assets/789496/68e33b5b-81a0-4a9e-b04d-0d2e6baf1bd5)

Update does not work:
![screen-record-dot-not-stored](https://github.com/keycloak/keycloak/assets/789496/71621505-9e4b-4f24-b75b-650d597dab60)

### Version

22.0.5 and nightly

### Expected behavior

Attributes which have a dot in the key should work like any others

### Actual behavior

Attributes not displayed. The PUT update request sends the following, when value "Foo" was entered to be stored:

```
	"attributes": {
		"with": {
			"dot": "Foo"
		},
		"with.dot": [
			"Baz"
		],
		"without_dot": [
			"Bar"
		]
	}
    ...
```

### How to Reproduce?

* Enable user profile
* Declare an attribute with dot .
* Try to view or update the value

**Comment by jonkoops** [comment]
This happens because our [form library](https://react-hook-form.com/) considers dots to be a part of the path separator for accessing objects. We'll have to encode the key so that it doesn't trigger this behaviour.

**Comment by jbman** [comment]
Thanks for having a look, I just discovered that it's a react-hook-form issue. Thought it is sth. more simple to fix. Could encoding/decoding be done in form-state.ts? And how to encode without possible conflicts? E.g. replacing dot with underscore could produce a key which is also used.

Currently we can't upgrade customer systems to 22 or 23 as they have attributes with dots which can't be renamed.

**Comment by jonkoops** [comment]
> Thanks for having a look, I just discovered that it's a react-hook-form issue. Thought it is sth. more simple to fix. Could encoding/decoding be done in form-state.ts? And how to encode without possible conflicts? E.g. replacing dot with underscore could produce a key which is also used.

I think that `form-state.ts` would indeed be a good place to do this, it is supposed to be a central place for all the form related state conversion. Allow me to introduce you to our wonderful [`beerify()` function](https://github.com/keycloak/keycloak/blob/90f4fbe4e583573dc67ea9457a5b9640bf39544b/js/apps/admin-ui/src/util.ts#L95-L99), which we use to do do this kind of stuff. It's not a great solution, but to our knowledge there is no way to customize this behaviour in  `react-hook-form`, so we're kinda stuck with it.

**Comment by sschu** [comment]
I am going to print this out and put it on the whiteboard at my desk. ;)

**Comment by jonkoops** [comment]
@sschu we use automation for patch releases through projects, when the `backport/x.x` label is added, GitHub will automatically put the backport in the [project board](https://github.com/orgs/keycloak/projects/12). This board is used to keep track of what needs to be backported.
