### ISSUE TITLE
Updating IDP via Admin API do not conform to documentation (alias and providerId seems required)

### ISSUE THREAD

**Issue by ttben** [keycloak/keycloak#24919]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

I encountered the issue on KC 21.1.2, and reproduced it on 22.0.5 (latest).

When updating an IDP via [the Admin API](https://www.keycloak.org/docs-api/21.1.2/rest-api/index.html#_identity_providers_resource), the doc states that the payload should be a [IdentityProviderRepresentation](https://www.keycloak.org/docs-api/21.1.2/rest-api/index.html#_identityproviderrepresentation), which marks all its attributes as optional, in a 'update-what-you-want' fashion.

However, it seems that both the `alias` and the `providerId` are required as errors 401 or 400 are thrown respectively when each attribute is omitted.

### Version

21.1.2, 22.0.5

### Expected behavior

I don't know if the doc is wrong and all fields are required, providing not a "patch-like" update but a stateful-update or if the code is bugged, so I don't know from a product POV what is the final expected behavior.

### Actual behavior

When updating only an attribute (e.g. `storeToken`) and omitting `alias` a 401 is thrown.
When updating only an attribute (e.g. `storeToken`) and providing `alias` BUT omitting `providerId` a 400 is thrown.
When providing the attribute to update (e.g. `storeToken`) and providing both `alias` and `providerId`, it works.

### How to Reproduce?

Versions 21.1.2 (tested) or 22.0.5 (tested)

----

On the 22.0.5 version import the following realms
[kc_issue_realmIDP.json](https://github.com/keycloak/keycloak/files/13437366/kc_issue_realmIDP.json) ; 'external-idp' that is just an empty realm.
[kc_issue_realm106.json](https://github.com/keycloak/keycloak/files/13437367/kc_issue_realm106.json) ; 106, main realm that has an `admin` client with all roles (just for the demo, don't worry), that has an identity provider configured to point to the realm

----

<details><summary>Initial IDP status: 
</summary>
<p>
<pre>
curl -v -X GET "http://localhost:8080/admin/realms/106/identity-provider/instances/external-idp/"\
    --header "Authorization: Bearer ${access_token}"

{
   "addReadTokenRoleOnCreate": false,
   "alias": "external-idp",
   "authenticateByDefault": false,
   "config": {
      "authorizationUrl": "http://localhost:8080/realms/external-idp/protocol/openid-connect/auth",
      "clientAuthMethod": "client_secret_post",
      "clientId": "client-106",
      "clientSecret": "**********",
      "issuer": "http://localhost:8080/realms/external-idp",
      "jwksUrl": "http://localhost:8080/realms/external-idp/protocol/openid-connect/certs",
      "logoutUrl": "http://localhost:8080/realms/external-idp/protocol/openid-connect/logout",
      "pkceEnabled": "false",
      "tokenUrl": "http://localhost:8080/realms/external-idp/protocol/openid-connect/token",
      "useJwksUrl": "true",
      "userInfoUrl": "http://localhost:8080/realms/external-idp/protocol/openid-connect/userinfo",
      "validateSignature": "true"
   },
   "displayName": "external-idp",
   "enabled": true,
   "firstBrokerLoginFlowAlias": "first broker login",
   "internalId": "3de1cefc-a6f4-49e1-9af2-9832f25e3484",
   "linkOnly": false,
   "providerId": "oidc",
   "storeToken": false,  <<=== I WANT TO UPDATE THIS ONLY
   "trustEmail": false,
   "updateProfileFirstLoginMode": "on"
}
</pre>
</p>
</details> 

----

When updating the `storeToken` attribute only, a 401 is thrown.

<details><summary>Details</summary>
<p>
<pre>
curl -v -X PUT "http://localhost:8080/admin/realms/106/identity-provider/instances/external-idp/" \
    --header "Authorization: Bearer ${access_token}" \
    --header "Content-Type: application/json" \
    --data '{"storeToken":true}'
</pre>
</p>
</details> 

----

When updating the `storeToken` attribute and giving the `alias` too , an error 400 is thrown.

<details><summary>Details</summary>
<p>
<pre>
curl -v -X PUT "http://localhost:8080/admin/realms/106/identity-provider/instances/external-idp/" \
    --header "Authorization: Bearer ${access_token}" \
    --header "Content-Type: application/json" \
    --data '{"alias":"external-idp", "storeToken":true}'

=> {"errorMessage":"Invalid identity provider id [null]"}
</pre>
</p>
</details> 

----

When updating the `storeToken` attribute and giving the `alias` and `providerId` too , an error 204 is returned 🎊 .

<details><summary>Details</summary>
<p>
<pre>
                                                                                                                                                                          
curl -v -X PUT "http://localhost:8080/admin/realms/106/identity-provider/instances/external-idp/" \
    --header "Authorization: Bearer ${access_token}" \
    --header "Content-Type: application/json" \
    --data '{"alias":"external-idp", "storeToken":true, "providerId":"oidc"}'
=> HTTP/1.1 204 No Content
</pre>
</p>
</details> 

### Anything else?

It seems that the providerId is required in the payload, even if given as Path Param, as the given calls trace to this block code

https://github.com/keycloak/keycloak/blob/a5b1eaf699c9bfb894bebd0e97773fa3ff38c012/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L806-L818

**Comment by rmartinc** [comment]
Hi @ttben!

The REST API documentation is just obtained from the code annotations and there is clearly a lot of room for improvement. If you check the other representations (like user or client) are the same, all the fields are optional (event username or clientId). In this case the `alias` and the `providerId` are compulsory for creation and update. But in general the idea for update is always the same for all them. First get the current current provider (all the representation), change the attributes you want to modify, and do the update sending the whole representation again, exactly as the console of kcadm do. Moving this to backlog, if someone wants to work on it please fell free to do it.

**Comment by ttben** [comment]
Hi @rmartinc! And thank you for the quick reply!
I understand now that the payload represent the desired state and not simply the field to be mutated.

However as a side note on  

>  First get the current current provider (all the representation), change the attributes you want to modify, and do the update sending the whole representation again

the alias seems to be read-only and updating it has no effect on the IDP, I dont know if other attributes has such behavior.
Let me know if I can help improving the documentation.

Have a nice day!

**Comment by andibeuge** [comment]
@ttben `providerId` is either `saml` or `oidc` - totally misleading names
