### ISSUE TITLE
client update via REST ignores client-scopes

### ISSUE THREAD

**Issue by ottotouzil** [keycloak/keycloak#24920]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When updating a client via the admin REST API, the clientScopes in the request body are ignored.

We use the REST API to create and update clients. When updating e.g:

```
PUT http://{host}/admin/realms/{realm}/clients/{id}
Authorization: Bearer xxxx
Content-Type: application/json

{
  "id": "{id}",
  "clientId": "xxxxx",
  "defaultClientScopes": [
    "some-default-client-scope"
  ],
  "optionalClientScopes": [
    "some-optional-client-scope",
    "another-optional-client-scope"
  ],
  ...
}
```
The `defaultClientScopes` and `optionalClientScopes` are ignored.

When creating a new client via REST API, the clientScopes are set properly.

We also see this in the code:

Here the line, where the client scopes are set for a newly created client:

[RepresentationToModel.java#L460](https://github.com/keycloak/keycloak/blob/a5b1eaf699c9bfb894bebd0e97773fa3ff38c012/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L460)

This code is missing in the updateClient method starting at line 504 in the same class.

### Version

22.0.5

### Expected behavior

After issuing a `PUT http://{host}/admin/realms/{realm}/clients/{id}` the client's client scopes should be updated according to the `defaultClientScopes` and `optionalClientScopes` in the request body.

### Actual behavior

The `defaultClientScopes` and `optionalClientScopes` in the request body are ignored

### How to Reproduce?

- update an existing client using `PUT http://{host}/admin/realms/{realm}/clients/{id}` with different lists of `defaultClientScopes` and/or `optionalClientScopes`

- check in the admin-ui that the client scopes are not updated

**Comment by hoepfnerj** [comment]
Is this the same as https://github.com/keycloak/keycloak/issues/16952 ?

**Comment by graziang** [comment]
To add a client scope to a client you need to use the `addDefaultClientScope` or `addOptionalClientScope` methods as mentioned in #16952

**Comment by ottotouzil** [comment]
Of course you can do that. However, you need to keep track of what to add and/or remove and also execute this explicitly. Whereas an _update_ simply reflects the current state of the client which makes automated configuration much simpler.

Also the code changes for this to work are rather small, as you can see in my PR.

**Comment by graziang** [comment]
@mposolda WDYT?

**Comment by mposolda** [comment]
Not 100% we want to support this. It certainly has low priority (as there is already existing endpoints for this as mentioned by @graziang ). We can doublecheck, but we can merge the PR just if there is 100% sure that it does not have impact on existing functionality of admin REST API (EG. if people don't provide client-scopes in the client PUT request, the Keycloak should NOT treat it as that all existing client scopes should be deleted from client before previously client-scopes field was not mandatory).
