### ISSUE TITLE
MULTIVALUED_STRING_TYPE and MULTIVALUED_LIST_TYPE not working in UserStorageProviderFactory

### ISSUE THREAD

**Issue by ThomasGaebler** [keycloak/keycloak#24927]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

According to the comments in https://github.com/keycloak/keycloak/issues/17851 i want to describe the bug here.

I have my own implementation of the UserStorageProviderFactory, in whose configuration there is an element of type MULTIVALUED_STRING_TYPE.

I have added a simple example as a Maven project.
[MultiValueStringScribble.zip](https://github.com/keycloak/keycloak/files/13438923/MultiValueStringScribble.zip)

If the JAR built from this is deployed in Keycloak, the behavior can be recreated as follows:
Go to **_User federation_**, and then **_Add TestStorage providers_**.

The default config looks like:
<img width="749" alt="01_start-view" src="https://github.com/keycloak/keycloak/assets/6328826/c87d7582-738d-4f82-9775-8c9eae0b2cd4">

Then add a displayname, change the text field and add some values to the MultivaluedStringField and save the configuration:
<img width="729" alt="02_changedvalues" src="https://github.com/keycloak/keycloak/assets/6328826/7a9b985b-51ee-4d9d-a2ba-5b3c2fc569c0">

If you re-open the config now, the following json-config is loaded from the server (it's correct):
<img width="412" alt="03_retrieved_json_config" src="https://github.com/keycloak/keycloak/assets/6328826/e39ca407-33e3-46b2-a8fb-02bd306409fb">

But the displayed configuration looks like this:
<img width="748" alt="04_broken_config" src="https://github.com/keycloak/keycloak/assets/6328826/d5ef7c9c-a2e6-4447-8692-4ec10b19d1ab">

The simple text field is updated correctly, but the mulitvalued string field contains the default value. In the previous Keycloak versions with the new interface, the first value was still displayed when the configuration was reloaded, the other ones skipped. In version 22.0.5, however, no value (or, if set, the default value) is displayed, but not the configuration value that is loaded as JSON from the server.

I am not a frontend developer myself and am not familiar with the programming language, but I downloaded the current GIT version, built Keycloak and debugged it a bit.

The fact that only the first value of the list is retained is probably due to the implementation in
`js/apps/admin-ui/src/util.ts`

the method

` export function convertToFormValues<T extends FieldValues>(`
and here
` const convertedValues = Object.entries(flattened).map(([key, value]) => Array.isArray(value) ? [key, value[0]] : [key, value], );`
Only the first value of the list is retained.

Ok. This is the behavior with the **MULTIVALUED_STRING_TYPE**. Another problem is the **MULTIVALUED_LIST_TYPE**.

Here is a sample:
Select option-1 and option-3, save the configuration and reload it:
<img width="746" alt="05_multivalued_list_changed" src="https://github.com/keycloak/keycloak/assets/6328826/f7a2e699-6002-4222-bfb0-e7ed036f0817">

the json-config from the server is correct:
<img width="409" alt="06_multivalued_list_json_config" src="https://github.com/keycloak/keycloak/assets/6328826/8b5f17d1-1ffb-4b2a-8c09-273b95c2b4c2">

but the result is: only option-3 is shown (the first from the config-json from server), option-1 is missing.
<img width="743" alt="07_multivalued_list_broken_config" src="https://github.com/keycloak/keycloak/assets/6328826/9a4205f4-c3b9-4b66-be90-c4981567029e">

If now another option is selected, the previously selected value is broken down into individual letters and each letter is displayed as an option:
![08_add_new_option](https://github.com/keycloak/keycloak/assets/6328826/d6686213-337e-4c54-a009-2e9a12743cee)

Saving this and reload from the server results in:
<img width="408" alt="09_multivalued_list_broken_config_2" src="https://github.com/keycloak/keycloak/assets/6328826/3d61100c-4cfc-470f-958f-7cec766d44bf">

I hope this description helps to solve the problem.
Best regards, Thomas

### Version

22.0.5

### Expected behavior

The configuration should display and handle all information correctly.

### Actual behavior

see above

### How to Reproduce?

see above

**Comment by patrick-primesign** [comment]
Hello, 

I will piggyback this issue because my current issue and this older (resolved, thanks!) issue seem kind of related: https://github.com/keycloak/keycloak/issues/19469

The new Admin-UI and the backend handle `MULTIVALUED_STRING_TYPE` differently. 

I have this problem with a custom IdentityProviderMapper which uses a `MULTIVALUED_STRING_TYPE` config property.

The backend in the IdentityProviderMapperModel expects the mapper config to be a `Map<String, String>`, but the frontend sends the data as an array.
```
{
  "id": "42a37eb1-c73f-4131-a7f9-a3aa4d885dc1",
  "name": "super-mapper",
  "identityProviderAlias": "super-idp",
  "identityProviderMapper": "super-idp-multivaluestring",
  "config": {
    "syncMode": "INHERIT",
    "strings": [
      "test123",
      "test456"
    ]
  }
}
```
So saving the mapper is not possible in the UI.
When we configure the mapper via database, the mapper works as intended.
But when editing this mapper in the UI again only the first string is shown.

The backend sends following json to the frontend:
```
{
    "id": "42a37eb1-c73f-4131-a7f9-a3aa4d885dc1",
    "name": "super-mapper",
    "identityProviderAlias": "super-idp",
    "identityProviderMapper": "super-idp-multivaluestring",
    "config": {
        "syncMode": "INHERIT",
        "userSessionNotePrefix": "test123##test456##"
    }
}
```
Of note is, that issue #19469 had the opposite problem, so maybe there is a connection to this issue.

Thanks for the hard work and if I should create my own issue, please tell, but I believe this is all connected.

Kind regards,

Patrick

**Comment by edewit** [comment]
@ThomasGaebler yeah I see you are right this is exactly the problem, thank you for your thorough issue. The reason you ran into this while I didn't is that you where using `.` in your properties names for which we have to do another workaround

**Comment by ThomasGaebler** [comment]
Great, thank you very much. I have tested the fix in a self-built Keycloak version. It solves all the problems I described. I hope the next official version comes soon :)

**Comment by ThomasGaebler** [comment]
Hello @edewit, unfortunately this patch only works if more than one value is set, otherwise we have exactly the same behavior as described above: A single value in the MULTIVALUED_STRING_TYPE field is overwritten by the default value, and if there is a single value in the MULTIVALUED_LIST_TYPE and another one is subsequently added, the existing one is broken down into its individual letters.

**Comment by ThomasGaebler** [comment]
Unfortunately, I cannot understand why this ticket was closed. This problem still occurs in version 23.0.4, especially since the committed fix as described above does not solve the problem.
