### ISSUE TITLE
Promote `update-email` from `preview` to `supported` feature

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#24930]
### Description

`update-email` feature has been existing for a while now without recently reported issues.
We have been using it in production since its inception.

I propose to promote it to the rank of `supported` feature.

**Comment by gjherbiet** [comment]
I have unfortunately just opened #24955.

**Comment by mposolda** [comment]
duplicates #16739 

So closing this. Please follow the other issue for the update regarding this feeature.
