### ISSUE TITLE
partialImport for CLIENTS, import clients not in order they passed

### ISSUE THREAD

**Issue by Ujifman** [keycloak/keycloak#24932]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I'm using partialImport for updating clients. I have two clients `clientA` and `clientB`, both with ClientFlow enabled. `clientA` has a lot of resources/scopes, and policies for realm Roles, and policy for `clientB`. 
When I import realm on empty keycloak, all is ok.
Then I use partial import to update clients (I send `clientA` and `clientB` in one request), but with order [`clientB`, `clientA`], I receive 

```
500: "errorMessage":"Error while updating policy [Client clientB]. Client [clientB] could not be found."
```

Policy `Client clientB` is the policy in `clientA` Authorization.

### Version

20.0.5

### Expected behavior

Create client instances for all clients in partialImport, and after that import their content.

### Actual behavior

Clients are imported fully in unknown order

```
500: "errorMessage":"Error while updating policy [Client clientB]. Client [clientB] could not be found."
```

### How to Reproduce?

- Create two clients `clientA` and `clientB`, both with ClientFlow enabled.
- in `clientA` create clientPolicy with `clientB`. 
- export configuration
- use partialImport 3-5 times with both clients in request

### Anything else?

Note: after first successfull import, sometimes one or two times partialImport works, then it can fail couple times and fix, then fail again

There is a workaround. I adapted my import script to update clients by one in order that I need. 
But anyway there will be problem, if `clientB` will have Authorization policy with `clientA`

Tested version 22.0.5 the same behavior

**Comment by mposolda** [comment]
I am adding to Backlog as not sure when Keycloak team has time to look at this. Anyone is welcome to investigate and eventually send PR with fixing this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details on how to contribute to Keycloak and send PR.
