### ISSUE TITLE
Keycloak not able to handle multiple validating X509 certificates when public key are the same

### ISSUE THREAD

**Issue by JonasPed** [keycloak/keycloak#24961]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

We have a Keycloak setup where we have a SAML IdP configured. The IdP have added another signing certificate because the old one will soon expire. It is just a renewal, so the new certificate have the same public key. 

When adding the new certificate to "Validating X509 certificates" users are no longer able to login and get an "internal server error " message. Attached exception is logged. 

[Explore-logs-2023-11-23 10_30_46.txt](https://github.com/keycloak/keycloak/files/13448012/Explore-logs-2023-11-23.10_30_46.txt)

### Version

22.0.3

### Expected behavior

User still able to login.

### Actual behavior

User gets "internal server error" message and exception logget.

### How to Reproduce?

1. Create SAML IdP. 
2. Add two X509 Validating certificates seperated by comma. The two certificates should use the same public key. 
3. Login through the IdP (fails with an error)

### Anything else?

I am not sure, but it might be related to the changes done in https://github.com/keycloak/keycloak/pull/17609.

**Comment by rmartinc** [comment]
@JonasPed Yes, sorry it's because this change https://github.com/keycloak/keycloak/commit/cab7e50410d4f596a8b8c9b19bfa296a0761d8e2. But try adding only the new certificate as it's the same key I think it will work. I'll try to provide a fix anyway.

**Comment by JonasPed** [comment]
I can confirm that it works with only the new certificate. Thanks for the workaround.
