### ISSUE TITLE
Adress keycloak high-availability guide follow-up items

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#24975]
### Description

In #24913 the intial version of the guide was published. This addresses the follow-up items identified in the review: 

* [x] Load shedding sometimes refers to 500 return code when it should be 503.
* [x] In threading concept, tell readers about congestion and throttling.
* [x] State that passthrough is used in the load test with ROSA
* [x] Reference test doesn't use refresh tokens for client credential grants
* [x] State more explicitly that caches should be enlarged

**Comment by vmuzikar** [comment]
In the follow-up, we should probably also update the load shedding instructions to use the new `http-max-queued-requests` option instead of raw Quarkus one.

**Comment by ahus1** [comment]
> In the follow-up, we should probably also update the load shedding instructions to use the new `http-max-queued-requests` option instead of raw Quarkus one.

@vmuzikar - I've now created issue https://github.com/keycloak/keycloak-benchmark/issues/604 for that. We will first need to use in KCB, and then we'll add it to the guides in the Keycloak main repository.
