### ISSUE TITLE
The `DefaultActionToken` serializes a JSON Object with duplicate keys

### ISSUE THREAD

**Issue by spensk8** [keycloak/keycloak#24980]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Performing actions that require a `DefaultActionToken`, such as reset credentials, verify email, update email, etc, generate a JWT as an `ActionToken` that has duplicate keys in the payload, therefore generating an invalid JSON.

The affected keys are those that have a `@JsonProperty(FIELD_NAME)` annotation in a method that calls `getOtherClaims()`.
I've identified the following fields:

- `DefaultActionToken` -> "asid"
- `ExecuteActionsActionToken` -> "rqac", "reduri"

I believe the reason is because in the `JsonWebToken` class, the method `getOtherClaims()` is annotated with `@JsonAnyGetter` and the JSON serializer will serialize all the `otherClaims` map one time, and then again the specific getter annotated with `@JsonProperty(FIELD_NAME)` which will read the values from the same `otherClaims` map

### Version

22.0.5

### Expected behavior

The encoded JWT in the `key` query param of the `login-actions/action-token` url should have a JSON payload without duplicate keys

### Actual behavior

The encoded JWT in the `key` query param of the `login-actions/action-token` url has a JSON payload with duplicate keys

### How to Reproduce?

Perform an action that generates this token.
For example, use the forgot password functionality in the login page, or use the admin panel to send an email to the user to perform an action in "Users > User details > Credentials > Credential Reset"

In the received email, copy the "key" query param of the link received.
Decode the payload part of the JWT

**Comment by graziang** [comment]
Just reproduced the issue, adding this to the backlog for now.
I agree with you since the `getOtherClaims()` method is annotated with `@JsonAnyGetter` and looking at the "asid" claim in `DefaultActionToken` the `getCompoundAuthenticationSessionId()` method has a `@JsonProperty(JSON_FIELD_AUTHENTICATION_SESSION_ID)` annotation but reads the value from the `otherClaims` map. 
The same is true for other duplicate claims.
