### ISSUE TITLE
Allow more extensive Override of BackchannelAuthenticationCallbackEndpoint

### ISSUE THREAD

**Issue by patrick-primesign** [keycloak/keycloak#24992]
### Description

The methods in the BackchannelAuthenticationCallbackEndpoint should be mostly protected to allow easier or more extensive overriding of the class.
Additionaly add methods before and after approving the device code, for additional actions or more validation.
The default behaviour should not be changed, if no overriding is necessary.

### Motivation

We needed a greatly enhanced BackchannelAuthenticationCallbackEndpoint to do some additional validation, which was not possible with the current implementation.
The described features would be easily enough for this.

**Comment by ahus1** [comment]
@mposolda - this looks like the core team's area, so I'm pinging you about this issue. It already has a PR attached.
