### ISSUE TITLE
Sessions are not cleared after logout all in admin console

### ISSUE THREAD

**Issue by good-engineer** [keycloak/keycloak#24990]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

In some cases, sessions are not cleared after "logout all" in the admin console
steps:
1. login admin console
2. users tab and search for a specific user
3. sessions tab
4. logout all 

Usually, After "logout all" the whole session records are cleared after the logout success pop-up. but In some cases, only the client_id field is cleared.  

before logout all
![Screen Shot 2023-11-23 at 18 54 28 copy](https://github.com/keycloak/keycloak/assets/19164143/5ab14bbf-d6a3-4196-bbc6-887a3d1d10c8)
after logout all
![Screen Shot 2023-11-23 at 18 54 37 copy](https://github.com/keycloak/keycloak/assets/19164143/ca799947-8454-45ab-83b5-f6f4708016f0)

When I attempt to log out of the session without a client_id, followng warning is displayed
```
logged_at: org.keycloak.models.sessions.infinispan.remotestore.RemoteCacheInvoker
message: Not found entity to replace for key '2c9d4ae3-5290-4288-a544-22595edbf9bd'
```
I think this is related to memory usage increase issues.  

### Version

15.0.1

### Expected behavior

all sessions should be cleared

### Actual behavior

only client_id is cleared

### How to Reproduce?

do not know the reason

**Comment by mabartos** [comment]
Thanks for the report! Can you please confirm if the issue still persists with the latest Keycloak version for you?

**Comment by jonkoops** [comment]
As mentioned in the issue template, please check this in the latest version of Keycloak. I'm closing this issue for now, if this behaviour persists in the latest version of Keycloak let us know, and we will re-open the issue.
