### ISSUE TITLE
Group search when creating user

### ISSUE THREAD

**Issue by mik3ydll** [keycloak/keycloak#25008]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Search for groups in "Join Group" does not work when creating new users.

### Version

23.0.0

### Expected behavior

Search filters the Group list according to entered string

### Actual behavior

Error message that breaks admin UI

### How to Reproduce?

Create group with subgroup
![image](https://github.com/keycloak/keycloak/assets/22119077/f8854e4e-c500-443c-93db-36dfa088f0e4)

Go to create user
![image](https://github.com/keycloak/keycloak/assets/22119077/59c4d48c-02e2-4b1a-87b1-6ae838aa0667)

Click join group
![image](https://github.com/keycloak/keycloak/assets/22119077/accbe0cf-ccd3-4b7d-875b-345db1e15ba8)

Enter search String and search
![image](https://github.com/keycloak/keycloak/assets/22119077/b89157c8-2e9b-4cc9-9c76-f5d0d0e0b3f6)

Error message occurs which require page reload 
![image](https://github.com/keycloak/keycloak/assets/22119077/aa7e0807-1b2a-4722-a862-ae43bdfac189)

**Comment by jonkoops** [comment]
I am able to reproduce this issue.
