### ISSUE TITLE
Make password visibility css classes configurable for themes

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#25016]
### Description

With #22067 a password visibility toggle was introduced.

The implemented code in the `base` them has some hardcoded css classes, although the `base` theme doesn't know about any css classes and only provides placeholders in class attributes, so that a theme concrete theme can configure its own class names through the `themes.properties` file.
With these hardcoded classnames and without placeholders, it's not possible in inherited themes to set custom css classnames.

That said, I suggest to change the relevant `base` templates to provide placesholders, which can be set by the `theme.properties` file and add the current hardcoded values to the `keycloak` theme. This way, there's no visible change for the default settings in Keycloak.

### Details

I will also prepare a PR for the suggested changes.

**Comment by jonkoops** [comment]
I think we can consider this a bug since all other functionalities in the login have similar ways of handling classes. I am marking this as a candidate to backport to v23.x.

**Comment by bnf** [comment]
@jonkoops Is the backport to v23.x still planned/considered or has it been overseen as the issue is already closed?
