### ISSUE TITLE
Document version 23 fails to execute when command is provided in quotation marks with Unknown option 

### ISSUE THREAD

**Issue by buti1021** [keycloak/keycloak#25018]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

If the command and potential arguments are enclosed in quotation marks the command fails since version 23.0

### Version

23

### Expected behavior

Command to be found and executed successfully

### Actual behavior

Unknown option error messages

### How to Reproduce?

Run: docker run quay.io/keycloak/keycloak:23.0 "start --help"

### Anything else?

Not using quotation marks work:
docker run quay.io/keycloak/keycloak:23.0 start --help

Version 22 works:
docker run quay.io/keycloak/keycloak:22.0 "start --help"

Just running start works as well:
docker run quay.io/keycloak/keycloak:23.0 "start"

The issue seems to be the same for different commands and different options (e.g., also tried start-dev and --import-realm)

I ran into this issue as my docker-compose file was not working anymore

**Comment by buti1021** [comment]
Thank you for the clarification!
However, I think the error message is not too helpful/misleading, would be nice if that could be improved. Additionally, I would have appreciated if that change of behaviour would have been mentioned in the migration guide!

**Comment by shawkins** [comment]
> However, I think the error message is not too helpful/misleading, would be nice if that could be improved.

Unfortunately there's not much that can / should be done there.  It was never intended for kc.sh to allow for an invocation like kc.sh "start --help" - creating a specific error message for that scenario would add some tech debt that we shouldn't need.

> Additionally, I would have appreciated if that change of behaviour would have been mentioned in the migration guide!

@vmuzikar do you want a migration guide entry to cover this either for docker files or calling kc.sh directly?

**Comment by vmuzikar** [comment]
@shawkins +1 for retrospectively adding that to [23 migration guide](https://github.com/keycloak/keycloak/blob/2c611cb8fc000edd4e4a8429eccc0982572b37fe/docs/documentation/upgrading/topics/keycloak/changes-23_0_0.adoc?plain=1#L91-L103). We could mention both kc.sh and docker explicitly (even though it's technically the same thing).

**Comment by shawkins** [comment]
Re-opening as a doc issue.

**Comment by RaymondMouthaan** [comment]
In my docker-compose / stack the following unfortunately wont work since 23.0.0:

```
        command:
            - "start --optimized --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"
```

please advise.

**Comment by shawkins** [comment]
@RaymondMouthaan those arguments will need to be passed individually.  If I'm inferring the usage correct based upon what you provided this would be:

```
        command:
            - start
            - --optimized 
            - --spi-theme-static-max-age=-1
            ...
```

**Comment by shawkins** [comment]
@RaymondMouthaan that is #25010

**Comment by justinaslelys** [comment]
The example above with overriding entrypoint (`command:`) may be confusing. Keycloak image already has an `ENTRYPOINT` defined so only args need to be passed.

In my case I had receive the same problem as the post author ant my manifest looked like this:

```
containers:                                                                                                                                                                     
  - args:                                                                                                                                                                         
    - start --optimized
```

Changed to:

```
containers:                                                                                                                                                                     
  - args:                                                                                                                                                                         
    - start 
    - --optimized
```
    
Works fine now. Don't know how that happens, no quotes are provided in the manifest, but somehow it is passed quoted to the container. Hope it helps for anyone.

**Comment by omasseau** [comment]
> The example above with overriding entrypoint (`command:`) may be confusing. Keycloak image already has an `ENTRYPOINT` defined so only `args` need to be passed.

`args` is for arguments of a `build` configuration.
`command` is the correct way to pass parameters to the entrypoint.
