### ISSUE TITLE
Prevent defining "read only attributes" in User Profile

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#25047]
When reviewing https://github.com/keycloak/keycloak/pull/24282 I've noticed that it is possible to define (override)  user attribute which should be read only: https://www.keycloak.org/docs/latest/server_admin/index.html#_read_only_user_attributes

IMO it should NOT be possible to do so.

**Comment by mposolda** [comment]
To me, it can still makes sense to being able to define attribute in user-profile even if it is declared as "read-only" in the provider configuration. I can imagine that administrator may want to see attributes like `userCertificate` or `saml.persistent.name.id.for.myClient` and hence it can be good if those can be defined in user-profile. Also some attributes may be even visible for users and being shown for example in account console.

But it makes sense to me, that user profile realm configuration should not have possibility to override read-only provider setting for such attributes.

So for example: System administrator wants to have attribute like `important_id` to be read-only for both users and admins. And hence he starts the server with something like this:
```
./kc.sh start-dev --features=declarative-user-profile,account3 --spi-user-profile-declarative-user-profile-read-only-attributes=important_id --spi-user-profile-declarative-user-profile-admin-read-only-attributes=important_id
```
Now realm admin should be able to define attribute `important_id` in my opinion, so the attribute is visible on users in admin console. But both administrator or user should not be able to update such attributes and hence it should be always read-only, so the provider read-only setting always has the "final decision". Is it what you mean?

@pedroigor WDYT?

**Comment by mposolda** [comment]
@vramik What do you think? It already works in a way specified in my last comment. Are you ok with closing this?

**Comment by mposolda** [comment]
We had some more discussions with @pedroigor and ATM looks that we may rather deprecate/remove provider configuration support entirely https://github.com/keycloak/keycloak/issues/25574 . Due to this, this issue might be out of date, so closing for now.
