### ISSUE TITLE
Incomplete Spanish translations for Admin UI

### ISSUE THREAD

**Issue by daniel-shuy** [keycloak/keycloak#25041]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

There are many i18n keys that remain untranslated for Spanish in the Admin UI:
<img width="1403" alt="image" src="https://github.com/keycloak/keycloak/assets/17351764/3bf2c813-f35f-4f35-979d-bc5ee013aa1a">

Compare the number of keys in:
https://github.com/keycloak/keycloak/blob/1d4ce3d8e9dbc9af996f9248996c78e145902a35/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties#L1-L2920
vs:
https://github.com/keycloak/keycloak/blob/1d4ce3d8e9dbc9af996f9248996c78e145902a35/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_es.properties#L1-L273

### Version

23

### Expected behavior

All Admin UI i18n keys should be translated for Spanish

### Actual behavior

Many keys remain untranslated

### How to Reproduce?

1. Enable **localization** in **Realm Settings**
2. Add `español` to the list of **Supported locales**
3. Logout
4. Login with Locale set to `Español`

**Comment by Stephen1234567** [comment]
Hi @daniel-shuy, I have created a new PR with all translation for spanish language.
https://github.com/keycloak/keycloak/pull/25281
