### ISSUE TITLE
Read Only Access of the realm users' "Role mapping" tab is broken for Admin Console

### ISSUE THREAD

**Issue by SalemWafi** [keycloak/keycloak#25054]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Users in the master realm with "view-users" role of a sub realm can't see the "Role mapping" tab of the users of that sub realm.

### Version

22.0.3

### Expected behavior

Users in the master realm with "view-users" role of a sub realm should be able to see the "Role mapping" tab of the users of that sub realm.

### Actual behavior

Users in the master realm with "view-users" role of a sub realm can't see the "Role mapping" tab of the users of that sub realm.

### How to Reproduce?

1. Create a User in the master realm and assign these roles to that user (Make sure to assign your sub realm view-users role to that user).

![1a](https://github.com/keycloak/keycloak/assets/32916450/0c1048b4-32a2-4bdf-a0c0-fbfc8d88fb8e)

<br><br>
2. Login/impersonate that user, then go to your sub realm users and click on one of the users you have already set up.
You won't be able to see the "Role mapping" tab even tho that you have the role view-users of that sub realm:

![2a](https://github.com/keycloak/keycloak/assets/32916450/d0db75fb-2f31-4e7d-91f8-8293bb74a841)

### Anything else?

If I assign the sub realm manage-users role to that user, the "Role mapping" tab shows up, but of course, the user will have write access to the "Role mapping" tab, which is not a desirable solution for read-only users.

<img width="956" alt="3a" src="https://github.com/keycloak/keycloak/assets/32916450/307cbd0d-0ee3-4b8c-8463-d89557b31cf7">

**Comment by SalemWafi** [comment]
For the developer who gonna work on this issue, I think I found the bug source :)

In this line of code [code_line_link](https://github.com/keycloak/keycloak/blob/1be51ee510a7b10ec2ce34adc4c33827cfb86a01/js/apps/admin-ui/src/user/EditUser.tsx#L281C1-L282C1), it is checking for isHidden={!user.access?.mapRoles}, which seems that links it to the role "manage-users".
instead that line of code should be isHidden={!user.access?.view}
and the buttons inside that tab page that are responsible for assigning and unassigning roles should check for the mapRoles access (which is linked to the "manage-users" role).

**Comment by sschu** [comment]
There is a related problem showing the assigned roles in the role-mappings tab with fine-grained permissions since currently, you can only see assigned roles you could also map. I don't think this is how it should be: once you can see a user you should be able to see the role assignments.

**Comment by ssilvert** [comment]
Looks related to this one? https://github.com/keycloak/keycloak/issues/20125

I'll see if I can do something about it.

**Comment by SalemWafi** [comment]
@ssilvert
Yes, it is; both issues are caused by the same line of code.

**Comment by muneebahmed** [comment]
there is a similar issue with the view-groups role not able to see the role mapping tab in the groups section. I have to assign manage users for that tab to be visible

**Comment by sschu** [comment]
@muneebahmed This issue is already closed. If you found a different bug, please report it separately.
