### ISSUE TITLE
Add `hasWords`, first and max to messages endpoint

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#25068]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

In order to build the new screen that we have planned for Internationalisation, we need a filter for translations that have specific words and a first and max.

**Comment by hmlnarik** [comment]
> [...] filter for translations that have specific words [...]

Should the returned items contain all the specified words or any of them?
