### ISSUE TITLE
Publish information about Infinispan availability in lb-check if MULTI_SITE is enabled

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#25077]
### Description

Introduce a new check available for the load balancer to decide whether this site should receive load or not.

This is Keycloak implementation part of the following issue for Keycloak benchmark:
https://github.com/keycloak/keycloak-benchmark/issues/591

**Comment by ahus1** [comment]
@mhajas - when backporting this to KC22, please change this feature from `PREVIEW` to `DISABLED_BY_DEFAULT`. Possibly in a separate commit in the the backport PR. Thanks!
