### ISSUE TITLE
JpaUserProvider searchForUserStream uses default session UserProvider

### ISSUE THREAD

**Issue by zyrtux** [keycloak/keycloak#25095]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

This line:
https://github.com/keycloak/keycloak/blob/23.0.0/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L754
seems to use the default session UserProvider for some reason (session.users()), as compared to all other methods in JpaUserProvider (e.g. searchForUserByUserAttributeStream)
This causes the returned user objects to go through Cache and any User Storage Providers, which should not be the case for userLocalStorage (UserStoragePrivateUtil.userLocalStorage(session))

instead of:
users.getUserById(realm, userEntity.getId())
why is this not:
new UserAdapter(...)
?

like for all other methods in there?

### Version

22.0.5

### Expected behavior

JpaUserProvider (the searchForUserStream method) returns only objects of type org.keycloak.models.jpa.UserAdapter and never uses cache

### Actual behavior

JpaUserProvider.java (the searchForUserStream method) returns objects of any type that a potential user storage provider will return and also uses cache

### How to Reproduce?

use UserStoragePrivateUtil.userLocalStorage(session).searchForUserStream  and search for users that are from a user storage provider ("imported users")
check the returned object type, it should be org.keycloak.models.jpa.UserAdapter, but instead, it will be the type that you user storage provider returns

**Comment by mhajas** [comment]
@zyrtux Thank you for reporting the issue. This concept is reused in many places in Keycloak. The reason for this call is to cache the result (we take advantage of the presence of the users in the Hibernate persistent context and therefore the `getUserById` call is performed fast and the user data are then stored in the memory of Keycloak).

The idea is that if we list users it is expected that some following requests will be loading the data about one of the users again and we will have a cache hit for such request.

I know this is slightly cumbersome and hard to understand at first sight but we believe this performs better than not caching the result. 

I am closing this as not planned but if anyone would like to work on this either by refactoring this to be more understandable or proving this does not have the performance benefits we think feel free to reopen or continue the discussion here. 

Here are some other occurrences of this concept for the record:
- https://github.com/keycloak/keycloak/blob/1d4ce3d8e9dbc9af996f9248996c78e145902a35/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java#L208
- https://github.com/keycloak/keycloak/blob/1d4ce3d8e9dbc9af996f9248996c78e145902a35/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L327
- https://github.com/keycloak/keycloak/blob/23.0.0/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L554
- https://github.com/keycloak/keycloak/blob/23.0.0/model/jpa/src/main/java/org/keycloak/models/jpa/JpaRealmProvider.java#L887
