### ISSUE TITLE
Docker build fails to download tzdata-2023c-1.el9.noarch.rpm

### ISSUE THREAD

**Issue by micahalgard** [keycloak/keycloak#25092]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

Running:

`docker build --build-arg KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/23.0.0/keycloak-23.0.0.tar.gz . -t keycloak:source-test` 

in `quarkus/container` results in the following error:

```
#15 11.37 [MIRROR] tzdata-2023c-1.el9.noarch.rpm: Interrupted by header callback: Inconsistent server data, reported file Content-Length: 864432, repository metadata states file length: 864888 (please report to repository maintainer)
#15 11.38 (67/82): xz-libs-5.2.5-8.el9_0.x86_64.rpm       2.4 MB/s |  94 kB     00:00
#15 11.41 (68/82): zlib-1.2.11-40.el9.x86_64.rpm          2.4 MB/s |  93 kB     00:00
#15 11.68 [MIRROR] tzdata-2023c-1.el9.noarch.rpm: Interrupted by header callback: Inconsistent server data, reported file Content-Length: 864432, repository metadata states file length: 864888 (please report to repository maintainer)
#15 11.74 (69/82): copy-jdk-configs-4.0-3.el9.noarch.rpm   80 kB/s |  29 kB     00:00
#15 11.81 (70/82): lua-posix-35.0-8.el9.x86_64.rpm        421 kB/s | 155 kB     00:00
#15 11.82 [MIRROR] tzdata-2023c-1.el9.noarch.rpm: Interrupted by header callback: Inconsistent server data, reported file Content-Length: 864432, repository metadata states file length: 864888 (please report to repository maintainer)
#15 11.94 [MIRROR] tzdata-2023c-1.el9.noarch.rpm: Interrupted by header callback: Inconsistent server data, reported file Content-Length: 864432, repository metadata states file length: 864888 (please report to repository maintainer)
#15 11.94 [FAILED] tzdata-2023c-1.el9.noarch.rpm: No more mirrors to try - All mirrors were already tried without success
#15 11.95
#15 11.95 The downloaded packages were saved in cache until the next successful transaction.
#15 11.95 You can remove cached packages by executing 'dnf clean packages'.
#15 11.96 Error: Error downloading packages:
#15 11.96   tzdata-2023c-1.el9.noarch: Cannot download, all mirrors were already tried without success
------
executor failed running [/bin/sh -c bash /tmp/ubi-null.sh java-17-openjdk-headless glibc-langpack-en findutils]: exit code: 123
``` 

### Version

main / 23.0.0

### Expected behavior

Docker image should build successfully. `tzdata-2023c-1.el9.noarch.rpm` should download with no issues.

### Actual behavior

`ubi-null.sh java-17-openjdk-headless glibc-langpack-en findutils` executes and attempts to resolve `tzdata-2023c-1.el9.noarch.rpm` this results in the following error:

```
Interrupted by header callback: Inconsistent server data, reported file Content-Length: 864432, repository metadata states file length: 864888 (please report to repository maintainer)
```

### How to Reproduce?

1. `git checkout main`
2. `cd quarkus/container`
3. `docker build --build-arg KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/23.0.0/keycloak-23.0.0.tar.gz . -t keycloak:source-test`

### Anything else?

This might be an issue with `glibc-langpack-en` or `tzdata-2023c-1.el9.noarch.rpm` that must be resolved on their end.

**Comment by stianst** [comment]
This was an issue with tzdata in UBI repositories, which is now resolved
