### ISSUE TITLE
Meaning of briefRepresentation query parameter is inverted in GroupResource.getSubGroups

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#25096]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

While debugging a regression in keycloak-config-cli I noticed, that the meaning of the `briefRepresentation` parameter in https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L162 has changed internally to mean the opposite. 

This was introduced here: https://github.com/keycloak/keycloak/commit/69497382d8cc6c622e815184d9bc27cb0dc6a400#diff-d233e82db465ac2b1ad22b124ab0bae3714f02d58c108c29afbbb935653d3ceaR162
As you can see the query parameter `briefRepresentation`  is mapped to the method parameter `full` and handled with the "meaning" of full.

I think this was a mistake as the parameter name "briefRepresentation" denotes the opposite of "full".

The current behaviour breaks all applications that rely on getting the full group data if briefRepresentation is set to false, but currently clients must use `briefRepresentation=true` to get the full representation.

### Version

23.0.0

### Expected behavior

Meaning of briefRepresentation should be consistent accross all Keycloak admin endpoints.

### Actual behavior

Meaning of briefRepresentation is inverted for GroupResource.getSubGroups.

### How to Reproduce?

1) Create a group with a subgroup
2) Add attributes and / or role mappings to the subgroup
2) try to obtain roles or attributes for the subgroup from the GroupRepresentation fetched with `briefRepresentation=false`

**Comment by transducer** [comment]
Same issue: [GET /admin/realms/{realm}/groups Endpoint Not Returning subGroups, clientRoles, realmRoles Despite populateHierarchy and briefRepresentation settings" #25053](https://github.com/keycloak/keycloak/issues/25053)

**Comment by alice-wondered** [comment]
My guess is this probably happened when we converged the two separate APIs for groups together to remove the workaround API that was being using on the admin console. Should be completely fine to revert the flag!
