### ISSUE TITLE
Remove product from server info

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#25103]
### Description

A rather long time ago the product in server info was used to show what build (Keycloak or RH-SSO). However, this will now always show default, and should just be removed from the admin console.

![image](https://github.com/keycloak/keycloak/assets/2271511/f6b09322-155c-4f03-a4cc-e030b9987d69)

**Comment by ssilvert** [comment]
@jonkoops Figured you could knock this out as part of the Welcome Screen migration stuff.

**Comment by jonkoops** [comment]
I don't see this as part of the welcome screen, I'll make a separate PR.
