### ISSUE TITLE
User Profile "Input placeholder" and other annotations - Use Localization keys

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#25114]
### Description

I would suggest making Annotations in the User Profile attributes like:
- Input placeholder
- Helper text (under) the input field
- Helper text (above) the input field
to be able to hold values using message keys configured in the Localization, like:
![image](https://github.com/keycloak/keycloak/assets/33352511/671f67d4-959b-489a-b763-d4ae42505ba3)
Currently they can have only direct set values, and not localized ones.
It would be great (I think also a must) to accept HTML, not only plain text

### Motivation

Improve the User Profile experience.

**Comment by john-gom** [comment]
I think this should be classed as a bug / regression as the login > user registration screen localizes these fields as expected.

@jonkoops , @edewit this is affecting us too, Shall I start work on it or is it already in hand?

**Comment by jonkoops** [comment]
Feel free to submit a PR @john-gom, shall I assign this to you?

**Comment by john-gom** [comment]
@jonkoops yes please. I also raised a new PR for #17776. Did you get that one?

**Comment by jonkoops** [comment]
@john-gom I'll try to get my review backlog cleared tomorrow, stay tuned.

**Comment by mpalavrov** [comment]
Just one comment, today I noticed that with KC v23, using localization for the Helper Text is working, but for us at least, there is one issue, that an anchor cannot hold **target="_blank"** parameter (Keycloak is trimming it)

**Comment by jonkoops** [comment]
@mpalavrov you should upgrade to v24, we no longer support v23. Feel free to log a new issue for any problems you are experiencing if they are reproducible in the latest version.
