### ISSUE TITLE
Keycloak Authz: Policy Enforcer maven bundle requires Java 8, what about newer versions?

### ISSUE THREAD

**Issue by col-panic** [keycloak/keycloak#25118]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

The keycloak [policy-enforcer](https://mvnrepository.com/artifact/org.keycloak/keycloak-policy-enforcer), required by the keycloak-adapter-core has the following line in MANIFEST.MF `Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"` which seems to bind it to Java 8.

When trying to integrate keycloak-adapter-core into my Java 17 osgi environment, the package dependency `org.keycloak.adapters.authorization;version="22.0.5"` cannot be resolved, as keycloak-policy-enforcer can not be loaded.

### Version

trying 22.0.5

### Expected behavior

I want to integrate it into my Java 17 environment, it worked with keycloak 19.0.2 now trying to update to 22.0.5 fails. 

### Actual behavior

As the dependency is not resolvable, I can not integrate keycloak

### How to Reproduce?

Check the dependencies, try to integrate using Java 17

**Comment by pedroigor** [comment]
@col-panic Not sure how you get that MANIFEST file but it should actually be:

```
Manifest-Version: 1.0
Created-By: Maven Archiver 3.4.0
Build-Jdk-Spec: 17
Specification-Title: Keycloak Authz: Policy Enforcer
Specification-Version: 22.0
Specification-Vendor: JBoss by Red Hat
Implementation-Title: Keycloak Authz: Policy Enforcer
Implementation-Version: 22.0.5
Implementation-Vendor: JBoss by Red Hat
Implementation-URL: http://keycloak.org/keycloak-authz-parent/keycloak-p
 olicy-enforcer
Java-Vendor: Eclipse Adoptium
Java-Version: 17.0.8.1
Os-Arch: amd64
Os-Name: Linux
Os-Version: 6.2.0-1014-azure
Scm-Connection: scm:git:git://github.com/keycloak/keycloak.git/keycloak-
 authz-parent/keycloak-policy-enforcer
Scm-Revision: 8da7a52969f5dfa1235227646ffb07d6fcee8ef3
Scm-Url: https://github.com/keycloak/keycloak/tree/master/keycloak-authz
 -parent/keycloak-policy-enforcer/
```

I'm closing this one because the library is built on JDK 17.
