### ISSUE TITLE
User Profile attribute with "Options" shows options of another attribute if none set on it

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#25110]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

If you create one attribute in the User Profile, which has inputType which uses options, and some options are added, and then you create another attribute, of similar inputType (which uses options), but you do NOT add any options, it is showing the options from the first attribute
![image](https://github.com/keycloak/keycloak/assets/33352511/0d87a1e5-ee78-4ae2-b57b-93ed5f5592b9)

### Version

22.0.5

### Expected behavior

The attribute with no options is empty (or not shown at all maybe?)

### Actual behavior

The options from the other attribute are shown instead

### How to Reproduce?

1. Create attribute with options in the User Profile
2. Create another attribute, with inputType using options (like select), but do NOT add any options
3. Open the Register page or Update Profile

### Anything else?
In case options are added in the new attribute, it is not showing the options of the other attribute but the specifically added on it.

**Comment by pedroigor** [comment]
@ssilvert @jonkoops Adding to 24.
