### ISSUE TITLE
CORS issue in 'openid-connect/certs' endpoint

### ISSUE THREAD

**Issue by pierresebastien** [keycloak/keycloak#25120]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

CORS issue in '/realms/{realm}/protocol/openid-connect/certs' endpoint due to change in Cache-Control header value starting in Keycloak 23

### Version

23.0.1

### Expected behavior

No CORS issue during access of '/realms/{realm}/protocol/openid-connect/certs' endpoint when switching from one application to another one configured as separated OpenID Connect clients in a same realm

### Actual behavior

It seems that starting from Keycloak 23.0.0 the Cache-Control header returned by the server when accessing https://{keycloak_domain}/realms/{realm}/protocol/openid-connect/certs endpoint has changed from 'no-cache' to 'max-age=2592000'. When logging in a application A and then accessing the application B on a separate domain (using the same realm but distinct OpenID Connect clients), the header 'Access-Control-Allow-Origin' remains configured to the first domain (of application A) and cause a CORS issue because the domain of application B is not the same.

Example of information captured in firefox : 
Request Headers
```
GET /realms/dummy-realm/protocol/openid-connect/certs HTTP/1.1
Host: accounts.dfakto.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
Accept: application/json, text/plain, */*
Accept-Language: fr,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Origin: https://application1.example.com
Connection: keep-alive
Referer: https://application1.example.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
```

Respons Headers
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 29 Nov 2023 12:36:23 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 2965
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://application2.example.com
Cache-Control: max-age=2592000
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
```

### How to Reproduce?

Create a realm in Keycloak 23+ and then 2 separate OpenID Connect clients using separate domains. Log into the application using the first OpenID Connect client and then try to access the second application

### Anything else?

I'm using NGINX as reverse proxy sot I have a workaround for the moment by adding this block in my configuration :
```
location ~ /realms/.+/protocol/openid-connect/certs {
        # kill cache
        add_header Cache-Control 'no-cache';
        proxy_no_cache 1;
        proxy_cache_bypass 1;

        proxy_pass      http://127.0.0.1:80;
}
```

**Comment by Tazmaniac** [comment]
Thank you for the workaround.

The real bug is that in case of CORS different than '*', a 'Vary: Origin' header must be present along the 'Access-Control-Allow-Origin:' header.

The bug was lurking long ago.

But you could not put a vary header blindly without Access-Control-Allow-Origin one like the 'no-cache' cache control.

**Comment by peacepenguin** [comment]
Seeing this issue in keycloak 23 too. We worked around the issue very similarly by using HAPROXY as our SSL offload reverse proxy:

```
frontend www-https
        bind *:443 ssl crt /etc/ssl/private/certs.pem
        http-request add-header X-Forwarded-Proto https
        http-request set-header cache-control max-age="0"
        http-response set-header cache-control max-age="0"

```

Obviously this disabled caching globally, which we are fine with, but this should be fixed inside of keycloak. Many of the other responses from Keycloak have a 'no-cache' directive, looks like it needs to be added to the 'certs' endpoint.

**Comment by reda-alaoui** [comment]
Seems to be caused by b62e6e2751b1f9e1d46548f157738bacf08e8e30

**Comment by reda-alaoui** [comment]
Not 100% sure yet, but I'd blame 217a09ce46bac48b7492a881e2ca5fbeef9dfd6d for not having replaced `org.jboss.resteasy.annotations.cache.NoCache` by `org.jboss.resteasy.reactive.NoCache`.

**Comment by pedroigor** [comment]
@reda-alaoui Makes sense. IIRC, it was supposed to work with the current annotation when we started the migration.

**Comment by pedroigor** [comment]
Created https://github.com/keycloak/keycloak/issues/25847.

**Comment by github-user-deepanshu** [comment]
I went into keycloak and selected master realm. After that is the admin-cli client. I have added my localhost to my web-origin (http//localhost:3000). Now what happens is that no matter how many POST requests I make, which are working successfully, like I make GET requests, which give CORS error, is there any solution to this. I am currently using keycloak version 24.0.4
