### ISSUE TITLE
Replace the existing themes with the dynamic templates from user profile

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#25149]
We should replace the existing themes for:

* registration
* update profile
* broker login flow

With the dynamic templates from the declarative user profile remove the dynamic template files.

The goal is to make migration easier for those using custom themes so that their changes to templates are properly recognized by the server.

We should also make sure that the very same beans currently available to the existing themes are also available to the dynamic templates.

We should have a test covering a use case where custom themes exist and custom attributes are supposed to be managed.

**Comment by mposolda** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/25221
