### ISSUE TITLE
Enable user profile by default for realms

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#25151]
The declarative user profile will be enabled by default to existing and new realms. By doing that, we should:

* Remove the `declarative-user-profile` feature as it does not make sense to disable it because it is a core feature and realms just can't live without it. User would still be able to customize it though through the corresponding SPI.
* For existing realms, define which unmanaged attribute policy should be set by default. It makes more sense to have them enabled as `Enabled` in order to keep the same behavior and experience as the static/current user profile.
* For new tealms, define the unmanaged attribute policy as `Disabled` because this is the default behavior and what we expect from realms from now on.
* Review import in order to recognized if the server is importing an existing or new realm based on the version from the realm JSON configuration so that the expected unmanaged attribute policy is set.
* Review documentation about references to remove references about the declarative user profile still in tech preview.

NOTE: verify-profile required action to be enabled by default is not part of this issue. There is separate issue for it https://github.com/keycloak/keycloak/issues/25985

**Comment by mposolda** [comment]
Yeah, we can. Was also thinking about something like this. However it raises some additional questions/concerns:

- Do we want to evaluate for both account console (context `ACCOUNT`) and admin console (context `USER_API`) ? IMO evaluate both is fine?

- This would mean that our account console (or admin console) will effectively use only "default" client scopes of clients `account-console` (or `security-admin-console`). As when you login to our account console (or admin console), there is no easy way to add additional optional client scopes. The only option is to manually edit `scope` parameter in the browser URL once the request to OIDC authentication is sent, but that's not very good for UX. But perhaps still ok?

- Do we want to update behaviour for both "enabled scopes" and for "required scopes" ? Currently scopes evaluation is ignored for "enabled scopes" and both admin console and account console always show all attributes even if it doesn't match the `enabled scopes` filter. IMO this behaviour is fine typically you want to see all attributes in account console (or admin console)? So not 100% sure if change the behaviour just for "required scopes" ?

**Comment by pedroigor** [comment]
A discussed with @mposolda, for Keycloak 24, we aim to support declarative-user-profile by default. For migration from previous versions, we added `Unmanaged attributes` switch (available in admin console in `Realm settings`, however it is part of the UserProfile configuration) with the behaviour like:
- New realms created in Keycloak 24 have the `Unmanaged attributes` switch `DISABLED` by default (this is already current behaviour when user-profile is enabled AFAIK)
- Existing realms (before Keycloak 24) should have the `Unmanaged attributes` switch behaviour: 
  - In case that `User profile Enabled` was OFF for particular realm in previous Keycloak version, the `Unmanaged attributes` switch should be `ENABLED` by default to be compatible with the previous behaviour before declarative-user-profile enabled. As such realm did not used declarative-user-profile feature and hence it expects user's details in the admin console `Attributes` tab working
  - When the switch `User Profile Enabled` was ON, we should keep `Unmanaged attributes` switch DISABLED as that is aligned with the behaviour in previous Keycloak versions (Keycloak 22/23 did not show `Attributes` tab in the admin console for users when the `User Profile Enabled` was ON).

**Comment by pedroigor** [comment]
As discussed with @mposolda, once the declarative-user-profile is enabled and we handle all the migration tasks etc, we can also consider removing method UserProfileProvider.isEnabled(RealmModel realm) .

It is already deprecated in Keycloak 22 - https://github.com/keycloak/keycloak/blob/22.0.6/server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileProvider.java#L92-L98 .

This is likely not strictly a blocker for Keycloak 24, but can be still nice to do it though to simplify some user-profile related code.
