### ISSUE TITLE
Review and update the test suite to run tests against realms with user profile enabled

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#25153]
The test suite should run based on the default settings for the user profile in regards to the unmanaged attribute policy. That might cause failures in some tests where custom attributes are being used and new realms are being created. 

We should also remove the tests we currently have for user profile that are basically extending a specific test class based on the static/current user profile because they are no longer needed. For instance, https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterWithUserProfileTest.java.

**Comment by mposolda** [comment]
@pedroigor This was already done during the work on https://github.com/keycloak/keycloak/issues/25151 . So maybe this one can be closed?

Just a note that I did not removed the user-profile specific tests in all the cases, but I made sure that tests are not duplicated. So for example `RegisterWithUserProfileTest` still exists, but it does not extend from `RegisterTest` anymore. I've kept 2 separate classes as `RegisterTest` is already very big and contains huge amount of tests. So `RegisterTest` now tests the basic aspects of the registration page when `RegisterWithUserProfileTest` tests more advanced scenarios of registration with custom user-profile configurations.
