### ISSUE TITLE
config keystore runtime properties are validated during re-augmentation

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#25166]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Picocli.hasConfigChanges triggers the resolution of all properties, so a runtime property like config-keystore gets validation with kc.sh build - but that is not expected.

### Version

23

### Expected behavior

Runtime properties should not be validated until runtime.

### Actual behavior

Validation failure during build time.

### How to Reproduce?

export KC_CONFIG_KEYSTORE=invalid
./kc.sh build

**Comment by shawkins** [comment]
@Pepo48 @pedroigor @vmuzikar this looks specific to KC_CONFIG_KEYSTORE. KcEnvConfigSource introduces the keystore property unconditionally and triggers the load of the KeyStoreConfig.  I think this also implies that if you included build time properties in the config keystore, they would be included at build time - which may not be intended.

Other runtime properties are filtered by the logic in PropertyMapper.getConfigValue, so this isn't a general problem as far as I can tell.

Is it worth the effort to try to restrict KC_CONFIG_KEYSTORE to only being used / validated at runtime?

**Comment by shawkins** [comment]
> Hmmm, I'm thinking if we should rather make config-keystore option build time. The keystore could indeed include build time options as well, it's by design.

Ah, I had just assumed it was supposed to be runtime given the way things are defined.  

So a breaking change is needed here then?

**Comment by vmuzikar** [comment]
Actually, never mind. :) We assume all build time options are not sensitive and we even store them in clear text (which is even [documented](https://www.keycloak.org/server/configuration#_creating_an_optimized_keycloak_build)). So the keystore config source is NOT expected to include build time options (I think we even had this discussion back then with @Pepo48). We should probably document this better and go with your proposed fix of validating `config-keystore` only at runtime.

**Comment by Pepo48** [comment]
I agree with the runtime validation.
