### ISSUE TITLE
[UMA] Access Token is invalid when retrieved via token exchange

### ISSUE THREAD

**Issue by emmanuelmathot** [keycloak/keycloak#25191]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

Access token issued from a Token Exchange is not valid when you try to retrieve a UMA ticket.

An access token is exchanged targeting a public client from a confidential one. The access token seems valid and can be used to authenticate, but then when you use it for issue a UMA ticket, the same response is always returned.

```json
{
    "error": "invalid_grant",
    "error_description": "Invalid bearer token"
}
```

The log is not much motre verbose

```
dev-acme-keycloak-1               | 23:33:27 DEBUG [or.ke.se.ma.AuthenticationManager] (executor-thread-12) No user session
dev-acme-keycloak-1               | 23:33:27 DEBUG [or.ke.se.ma.AuthenticationManager] (executor-thread-12) Client session for client 'biosdev-api' not present in user session '35dc8ba9-c7df-48e5-9dc6-e877ecaa8bee'
dev-acme-keycloak-1               | 23:33:27 WARN  [or.ke.events] (executor-thread-12) type=PERMISSION_TOKEN_ERROR, realmId=b1a19f87-edd1-4930-a4a2-6974ee98b4b1, clientId=biosdev-api, userId=null, ipAddress=172.25.0.1, error=invalid_token, auth_method=oauth_credentials, grant_type=urn:ietf:params:oauth:grant-type:uma-ticket
```

I have double-checked that the host is the same as the issuer and the introspecter, and I have been running tests via Postman with no luck.

The issue seems similar to #9337

### Version

22.0

### Expected behavior

a successful UMA permission ticket as with a token issued with another flow (authorization, password...) and the same client.

### Actual behavior

the UMA ticket request is always returning 401 with the error "Invalid bearer token"

### How to Reproduce?

1. Create 2 clients (1 public, 1 confidential)
2. Activate authorization on the confidential one
3. Enable advanced permission for token exchange on the public one to allow the confidential client to target the public (client policy)
4. Issue a token for a use with public client (e.g. authorization code flow)
5. Exchange that token with the confidential client
6. Use the issued token to issue a UMA ticket.

**Comment by mposolda** [comment]
Thanks for the report, but I am not sure about priority of this due the token-exchange is preview feature and UMA related issues also have low priority.

**Comment by shalphaaslam** [comment]
Hi, I have the same issue while trying to use keycloak authorization services. I use the 24.0.2 version of Keycloak. the authorization request seeking access to any resource protected by a resource server causes error 
`WARN  [org.keycloak.events] (executor-thread-11) type="PERMISSION_TOKEN_ERROR", realmId="3b897f33-1700-4ee8-9de8-2ae13f92d89c", clientId="account", userId="null", ipAddress="172.26.0.1", error="invalid_token", auth_method="oauth_credentials", grant_type="urn:ietf:params:oauth:grant-type:uma-ticket"`

**Comment by pittlm** [comment]
Hi, i have encountered the same Issue right now. Can you please guide me how the official workflow should look like then ? Currently I have a client for a SPA client which uses a public client with the authorization flow + PKCE and also a confidential client for the Backend. I can't transform the SPA client to a confidential one because I would then need to place the secret into the Application which is not feasible at the moment.  Is there any Suggestion from your side how I could still use the Authorization feature in this case ?
