### ISSUE TITLE
Keycloak CI -> Quarkus IT (ubuntu, container) -> multiple errors

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#25214]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Quarkus IT -> ubuntu, container -> multiple errors:

Error: OR] Failures: 
Error: OR]   BuildCommandDistTest.failIfDevProfile:58 The Error Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   BuildCommandDistTest.resetConfig:45 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   BuildCommandDistTest.testFailInvalidOptionInEnv:79 The Error Output:
--  
-- doesn't contains Invalid value for option 'kc.db': invalid. Expected values are: dev-file, dev-mem, mariadb, mssql, mysql, oracle, postgres. From ConfigSource KcEnvVarConfigSource ==> expected: <true> but was: <false>
Error: OR]   BuildCommandDistTest.testFailRuntimeOptions:71 The Error Output:
--  
-- doesn't contains Run time option: '--db-username' not usable with build ==> expected: <true> but was: <false>
Error: OR]   OptionsDistTest.failInvalidOptionValue:40 expected: <true> but was: <false>
Error: OR]   OptionsDistTest.testServerDoesNotStartIfValidationFailDuringReAugStart:52 expected:<1> but was:<0>
Error: OR]   OptionsDistTest.testServerDoesNotStartIfValidationFailDuringReAugStartDev:46 expected:<1> but was:<0>
Error: OR]   StartCommandDistTest.failBuildPropertyNotAvailable:72 The Error Output:
--  
-- doesn't contains Build time option: '--db' not usable with pre-built image and --optimized ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.failIfAutoBuildUsingDevProfile:79 
-- Expected: a string containing "You can not 'start' the server in development mode. Please re-build the server first, using 'kc.sh build' for the default production mode."
--      but: was ""
Error: OR]   StartCommandDistTest.failNoHostnameNotSet:86 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.failNoTls:43 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.failSpiArgMissingValue:50 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.failUsingDevProfile:57 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.testHttpEnabled:65 The standard output:
-- does include "Listening on:" ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.testStartUsingAutoBuild:94 
-- Expected: a string containing "Changes detected in configuration. Updating the server image."
--      but: was ""
Error: OR]   StartCommandDistTest.testStartUsingOptimizedDoesNotAllowBuildOptions:108 The Error Output:
--  
-- doesn't contains Build time option: '--cache' not usable with pre-built image and --optimized ==> expected: <true> but was: <false>
Error: OR]   StartCommandDistTest.testStartUsingOptimizedInvalidEnvOption:116 The Error Output:
--  
-- doesn't contains Invalid value for option 'kc.log': invalid. Expected values are: console, file, gelf. From ConfigSource KcEnvVarConfigSource ==> expected: <true> but was: <false>
Error: OR]   ToolsCommandDistTest.initialCompletionShouldSucceed:34 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR]   VersionDistTest.failNoTls:34 The Output:
-- doesn't contains the expected string. ==> expected: <true> but was: <false>
Error: OR] Errors: 
Error: OR]   HealthDistTest.testBlockingProbes:80 » Connect Connection refused
Error: OR]   HealthDistTest.testHealthEndpoint:55 » Connect Connection refused
Error: OR]   HealthDistTest.testHealthEndpointNotEnabled:38 » Connect Connection refused
Error: OR]   HealthDistTest.testMultipleRequests:123 » Execution java.net.ConnectException: Connection refused
Error: OR]   HealthDistTest.testNonBlockingProbes:69 » Connect Connection refused
Error: OR]   HealthDistTest.testUsingRelativePath:95 » Connect Connection refused
Error: OR]   MetricsDistTest.testMetricsEndpoint:54 » Connect Connection refused
Error: OR]   MetricsDistTest.testMetricsEndpointDoesNotEnableHealth:73 » Connect Connection refused
Error: OR]   MetricsDistTest.testMetricsEndpointNotEnabled:45 » Connect Connection refused
Error: OR]   MetricsDistTest.testMultipleRequests:112 » Execution java.net.ConnectException: Connection refused
Error: OR]   MetricsDistTest.testUsingRelativePath:84 » Connect Connection refused
-- [INFO] 
Error: OR] Tests run: 67, Failures: 19, Errors: 11, Skipped: 28

### Version

999.0.0-SNAPSHOT

### Expected behavior

tests should pass

### Actual behavior

multiple tests are failing 

### How to Reproduce?

please check this link: https://github.com/keycloak/keycloak/actions/runs/7015559474/job/19085304732

**Comment by vmuzikar** [comment]
@lhanusov Thanks for the report.

@shawkins Could you please look into it when you get a chance?

**Comment by shawkins** [comment]
@lhanusov @vmuzikar that run seems to be from several days ago when there was a problem building the images.  Is this still occurring?

**Comment by shawkins** [comment]
I believe this is out of date, marking as resolved.
