### ISSUE TITLE
Restrict the access to 'whoami' endpoint for tokens issued for the admin console client

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#25219]
### Original reporter

@atexela

### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We use Keycloak 18.0.2 as our Org IdP. Its been an year of happy use.
However, recently our security team has reported an IDOR defect in security-admin-console (admin UI OIDC client). Please read about the details in "Actual Behavior" and "How to Reproduce" sections

### Version

18.0.2

### Expected behavior

Please read this after reading "Actual Behavior" that was observed...
One should not be able to see other people's information using stolen tokens
Our suggestion is to  convert this client (security-admin-console) to a "confidential" OIDC client and don't keep the token info on the client. All tokens should be strictly on the server side.

### Actual behavior

Our security team's burp-Suite reported that when anyone logs in to admin console, there is a "whoami" URL that gets called (among many other URLs) as the screen load sequence.. this URL shows the user's token and if you replace it with anyone else's token, you could easily get to see that user's information on whoami. Now, there is no page associated with this URL but hacker's spiders could easily detect these weaknesses and use it to their advantage (he could use a stolen token of a higher privilege and hack in). 

### How to Reproduce?

Please see the reported defect writeup and images from our security team

<img width="1069" alt="idor-1" src="https://github.com/keycloak/keycloak/assets/112276349/4a0a306b-18c8-4807-ba51-99a691544256">

<img width="1062" alt="idor-2" src="https://github.com/keycloak/keycloak/assets/112276349/ff8d0a61-897b-45f2-bb75-26bb7629dd7c">

<img width="1049" alt="idor-3" src="https://github.com/keycloak/keycloak/assets/112276349/3e31ead1-9fcd-45e6-8fd5-c04b1b42939b">

**Comment by atexela** [comment]
I would still recommend to keep token on the server side (associated with user web session) with additional keycloak server implementation change as follows.

Server should associate all user web sessions with IP addresses, so that even if a hacker could steal a session key, he/she would not be able to jack the session because his/her IP address would be different.

Above implementation will prevent session jacking, and also keep the token safe on the server.

**Comment by ssilvert** [comment]
I'm going to take the `team/ui` label off of this one for now and let the core teams decide what to do for triage.  If we go forward with this and it leaves triage, we can put the label back on as we will be glad to help with design or implementation of the UI part.

**Comment by rmartinc** [comment]
This issued was commented inside the team and it was decided to just do two things:

1. The `whoami` endpoint should check the `azp` (issuedFor) claim and just allow tokens issued for the admin console client.
2. The endpoint should return forbidden 403 error if the user is not admin user (no permissions in the realm).

The rest is plain OIDC specification. The access token sent is only valid for a very short period of time (1 minute by default). The transport should be https.

**Comment by atexela** [comment]
thanks for update
