### ISSUE TITLE
Configure User Registration Theme when using the DECLARATIVE_USER_PROFILE

### ISSUE THREAD

**Issue by dancook993** [keycloak/keycloak#25221]
### Description

We want to display the password policy on our Registration page.

When we disable DECLARATIVE_USER_PROFILE we are able to adjust the register.ftl from the base theme to hardcode in our password policy.

When we enable DECLARATIVE_USER_PROFILE the Registration page no longer seems to inherit from register.ftl and our password policy is lost. 

It would be nice that when you use the DECLARATIVE_USER_PROFILE (which as the Keycloak docs say renders the registration page for you), you are still able to edit the registration page yourself as well. Or, if you were able to display the password policy without have to update the theme that would be easy.   

### Motivation

Custom registration page are needed as Keycloak can't display the password policy of your realm. Without password policy, the user experience is bad when registering. A custom theme can be implemented to show this password policy. However, it doesn't seem possible when using the USER PROFILE feature.

**Comment by antikalk** [comment]
@dancook993 did you try overwriting `register-user-profile.ftl`? Once user profile is activated that one is used instead of `register.ftl` afaik.

**Comment by mposolda** [comment]
@dancook993 Could you please try with latest Keycloak nightly release downloadable from here https://github.com/keycloak/keycloak/releases/tag/nightly ? I think this was updated and in latest Keycloak main, you should be able to override FTL files.

If it still doesn't work, then please add the details about the files you're overriding in your theme as asked by @antikalk .

**Comment by mposolda** [comment]
I am closing as we have related/duplicated issue where this is already planned - https://github.com/keycloak/keycloak/issues/25149 . I am sorry for the confusion as this is not yet addressed in latest Keycloak main. You can follow on the 25149 issue to see when this is available.
