### ISSUE TITLE
front channel logout to clients are not called at Identity Proxy when using front channel logout to Identity Provider(

### ISSUE THREAD

**Issue by ted-the-coder** [keycloak/keycloak#25234]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

when setup Keycloak as Identity Proxy to call other Identity Provider( i.e., another Keycloak instance), the clients at Proxy are set to front channel logout,
![client](https://github.com/keycloak/keycloak/assets/84643595/d18305bb-9f21-47de-b05a-bcf9e0eee0f3)

and the Identity Provider at Proxy is set to front channel logout as well( with  "Backchannle logout" turned off)

![IdentityProvider](https://github.com/keycloak/keycloak/assets/84643595/315fd4ad-c972-45e7-a940-816bc65a0a96)

when logout from Keycloak(Identity Proxy), the sessions at Identity Proxy and Identity Provider are terminated as expected, but there is no call to the applications front channel logout URLs. 

### Version

23.0.1( tried old versions as well, 22.0.5, and so on)

### Expected behavior

1. the logout confirm page is showing which has the iframes calling to applications' front channel logout urls.
2. both sessions at Identity Proxy and Identity Provider are terminated.

### Actual behavior

1. no calling to applications' front channel logout urls. even there are logs like shit 
  frontchannel logout to:  xxxx    (xxxx is the client id)
2. both sessions at Identity Proxy and Identity Provider are terminated.

### How to Reproduce?

1. set up two Keycloak at docker-compose, one is Identity Proxy, the other is Identity Provider, make sure the "Backchannel logout' is turned off at the Identity Provider in Identity Proxy
2.  create two clients at Identity Proxy, and set the Front Channel Logout URL
3.  create two application and implement front channel endpoint, make sure adding logging, and configure these applications  to connect to Identity Proxy as OIDC provider
4.  logout from one application or from the logout URL of Identity Proxy, we will see the applications are not called

### Anything else?

I have a potential fix. before creating a PR, I want to double check if it is a bug.

**Comment by pedroigor** [comment]
@ted-the-coder Sorry for the delay. It makes sense to me and we can improve this when executing a logout for sessions bound to a broker. It seems the problem here is that the logout endpoint will stop before actually rendering the "logout page" with the hidden front-channel logout requests to each application. See https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L656.

If you have a fix, please send the PR and let us know.
