### ISSUE TITLE
bitnami/keycloak:22.0.5-debian-11-r2 - Admin UI is not working

### ISSUE THREAD

**Issue by zohebshaik41** [keycloak/keycloak#25293]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have deployed keycloak by using external database postgres in kubernetes v1.28.2.

Keycloak pod is up/running, but however while accessing admin UI. It's not prompting for credentials, like the UI is continuously loading.

Like I am accessing keycloak UI - https://xyz.com/admin/master/console/

![image](https://github.com/keycloak/keycloak/assets/152380397/f9e8a04a-16d9-4656-a1f4-c8a7fb643687)

### Version

bitnami/keycloak:22.0.5-debian-11-r2

### Expected behavior

Admin UI should work.

### Actual behavior

We have deployed keycloak in kubernetes v1.28.2.

Keycloak pod is up/running, but however while accessing admin UI. It's not prompting for credentials, like the UI is continuously loading.

Like I am accessing keycloak UI - https://xyz.com/admin/master/console/

### How to Reproduce?

Deploy the keycloak using bitnami chart and use any external database like postgresql

**Comment by jonkoops** [comment]
We don't offer support on anything but the latest version of Keycloak. If the issue persists in the latest version feel free to submit a new issue.

That said, I highly recommend that you read the contents of #24252 and #14666, as the answer to your problem is likely a configuration issue.

**Comment by zohebshaik41** [comment]
I've used this in statefulset.yaml, but still no luck.

       image: docker.io/bitnami/keycloak:latest
        imagePullPolicy: IfNotPresent

I mean same error, as it's kept on loading without any error or without opening login page.
