### ISSUE TITLE
unable to build quarkus image with custom jax rs endpoint in keycloak 23

### ISSUE THREAD

**Issue by kkcmadhu** [keycloak/keycloak#25291]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I have a  a custom endpoint (shipped as spi/jar) which is a jax rs endpoint, which i am using since keycloak 16.x , after upgrading to  keycloak 23 i am not able to compile  keycloak 23 image with this spi/jar.

The comiplation of jar goes fine, but when i build quarkus image/start quarkus i get this error.

```
#9 3.994 ERROR: Failed to run 'build' command.
#9 3.994 ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#9 3.994        [error]: Build step io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor#handleFieldSecurity threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
#9 3.994        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
#9 3.994        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#9 3.994        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#9 3.994        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#9 3.994        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#9 3.994        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#9 3.994        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#9 3.994        at java.base/java.lang.Thread.run(Thread.java:840)
#9 3.994        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#9 3.994
#9 3.994 ERROR: Build failure: Build failed due to errors
#9 3.994        [error]: Build step io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor#handleFieldSecurity threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
#9 3.994        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
#9 3.994        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#9 3.994        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#9 3.994        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#9 3.994        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#9 3.994        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#9 3.994        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#9 3.994        at java.base/java.lang.Thread.run(Thread.java:840)
#9 3.994        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#9 3.994
#9 3.994 ERROR: Not a parameterized type!
#9 3.994 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
#9 ERROR: process "/bin/sh -c /opt/keycloak/bin/kc.sh build" did not complete successfully: exit code: 1
------
 > [builder 5/6] RUN /opt/keycloak/bin/kc.sh build:
#9 3.994        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#9 3.994        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#9 3.994        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#9 3.994        at java.base/java.lang.Thread.run(Thread.java:840)
#9 3.994        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#9 3.994
#9 3.994 ERROR: Not a parameterized type!
#9 3.994 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.


```

the dependency section of my pom for this module looks like this 

```
   <dependencies>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-core</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-common</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-services</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-server-spi</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-server-spi-private</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-model-jpa</artifactId>
         <scope>provided</scope>
      </dependency>
      
      <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-legacy</artifactId>
             <scope>provided</scope>
      </dependency>
	  <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-legacy-private</artifactId>
             <scope>provided</scope>
      </dependency>
	  <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-legacy-services</artifactId>
             <scope>provided</scope>
      </dependency>
	  
      <dependency>
         <groupId>org.jboss.logging</groupId>
         <artifactId>jboss-logging</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>jakarta.persistence</groupId>
         <artifactId>jakarta.persistence-api</artifactId>
         <scope>provided</scope>
      </dependency>
   </dependencies>
```

### Version

23

### Expected behavior

/bin/sh -c /opt/keycloak/bin/kc.sh build" should not throw error.

### Actual behavior

throws error while building quakus image

```
#9 3.994 ERROR: Failed to run 'build' command.
#9 3.994 ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#9 3.994        [error]: Build step io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor#handleFieldSecurity threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
#9 3.994        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
#9 3.994        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#9 3.994        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#9 3.994        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#9 3.994        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#9 3.994        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#9 3.994        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#9 3.994        at java.base/java.lang.Thread.run(Thread.java:840)
#9 3.994        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#9 3.994
#9 3.994 ERROR: Build failure: Build failed due to errors
#9 3.994        [error]: Build step io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor#handleFieldSecurity threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
#9 3.994        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
#9 3.994        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#9 3.994        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#9 3.994        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#9 3.994        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#9 3.994        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#9 3.994        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#9 3.994        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#9 3.994        at java.base/java.lang.Thread.run(Thread.java:840)
#9 3.994        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#9 3.994
#9 3.994 ERROR: Not a parameterized type!
#9 3.994 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
#9 ERROR: process "/bin/sh -c /opt/keycloak/bin/kc.sh build" did not complete successfully: exit code: 1
------
 > [builder 5/6] RUN /opt/keycloak/bin/kc.sh build:
#9 3.994        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
#9 3.994        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
#9 3.994        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#9 3.994        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#9 3.994        at java.base/java.lang.Thread.run(Thread.java:840)
#9 3.994        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#9 3.994
#9 3.994 ERROR: Not a parameterized type!
#9 3.994 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
------
Dockerfile:27
--------------------
  25 |     WORKDIR /opt/keycloak
  26 |
  27 | >>> RUN /opt/keycloak/bin/kc.sh build
  28 |     RUN /opt/keycloak/bin/kc.sh show-config
  29 |
--------------------
ERROR: failed to solve: process "/bin/sh -c /opt/keycloak/bin/kc.sh build" did not complete successfully: exit code: 1
```

### How to Reproduce?

have a dummy spi with dependency

```
   <dependencies>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-core</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-common</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-services</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-server-spi</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-server-spi-private</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>org.keycloak</groupId>
         <artifactId>keycloak-model-jpa</artifactId>
         <scope>provided</scope>
      </dependency>
      
      <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-legacy</artifactId>
             <scope>provided</scope>
      </dependency>
	  <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-legacy-private</artifactId>
             <scope>provided</scope>
      </dependency>
	  <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-legacy-services</artifactId>
             <scope>provided</scope>
      </dependency>
	  
      <dependency>
         <groupId>org.jboss.logging</groupId>
         <artifactId>jboss-logging</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <groupId>jakarta.persistence</groupId>
         <artifactId>jakarta.persistence-api</artifactId>
         <scope>provided</scope>
      </dependency>
   </dependencies>
```

**Comment by kkcmadhu** [comment]
thanks @sschu  i doubleced checked my code, keycloak rest endpoints and the link you have shared.
i dont see any resteasy related imports in my code aprt from nocache (org.jboss.resteasy.annotations.cache.NoCache) annotation, which has not chnaged i guess.

rest of the code is purely " jakarta.ws.rs.*" just like keyclaok 23 code. i am not sure where is this problem originating from.

besides the packages which are there in the link are quarkus specfic, i dont see any quarkus specific code in out of box keycloak rest endpoints (and mine too do not have any).

**Comment by kkcmadhu** [comment]
my depdency tree for the custom spi looks like this, should i exclude any jar explicitly?

![image](https://github.com/keycloak/keycloak/assets/997582/81821861-4ca8-4a76-8346-bff2b149b50d) 
like resat easy jaxb core ?

**Comment by kkcmadhu** [comment]
thats the strange things, sources and DEBUG logs, since this is happening at time of image building i am not able to debug it or run loggers at trace level, as far as sources are concerned, i am pretty sure this is some thing to do with quarks , since i am not even  bringing any new dependency or changing the jar versions or doing any thing custom, this did look strange to me.
Let me try to figure out if there is another way to get to the source/debug

**Comment by kkcmadhu** [comment]
keycloak 23 release notes says 

"RESTEasy Reactive
Keycloak has switched to RESTEasy Reactive. Applications using quarkus-resteasy-reactive should still benefit from a better startup time, runtime performance, and memory footprint, even though not using reactive style/semantics. **SPI’s that depend directly on JAX-RS API should be compatible with this change**. SPI’s that depend on RESTEasy Classic including ResteasyClientBuilder will not be compatible and will require update, this will also be true for other implementation of the JAX-RS API like Jersey."
but does not seems so.

**Comment by kkcmadhu** [comment]
here is the exact stack trade at debug level logs

> #9 4.680 2023-12-11 17:53:19,811 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.idm.AuthenticationFlowRepresentation
> #9 4.680 2023-12-11 17:53:19,812 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.idm.RequiredActionProviderRepresentation
> #9 4.681 2023-12-11 17:53:19,812 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.idm.ClientInitialAccessPresentation
> #9 4.681 2023-12-11 17:53:19,812 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.broker.provider.IdentityProviderFactory
> #9 4.681 2023-12-11 17:53:19,812 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.idm.CredentialRepresentation
> #9 4.681 2023-12-11 17:53:19,813 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.account.UserRepresentation
> #9 4.682 2023-12-11 17:53:19,813 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.idm.ComponentRepresentation
> #9 4.682 2023-12-11 17:53:19,813 DEBUG [io.quarkus.deployment.steps.CombinedIndexBuildStep] (build-41) Index: org.keycloak.representations.idm.ProtocolMapperRepresentation
> #9 4.729 ERROR: Failed to run 'build' command.
> #9 4.729 Error details:
> #9 4.729 java.lang.reflect.InvocationTargetException
> #9 4.729        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> #9 4.729        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> #9 4.730        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> #9 4.730        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> #9 4.730        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
> #9 4.730        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
> #9 4.730        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
> #9 4.730        at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:83)
> #9 4.730        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
> #9 4.730        at picocli.CommandLine.access$1500(CommandLine.java:148)
> #9 4.730        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
> #9 4.730        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
> #9 4.730        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
> #9 4.730        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
> #9 4.730        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
> #9 4.730        at picocli.CommandLine.execute(CommandLine.java:2170)
> #9 4.730        at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:218)
> #9 4.730        at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:154)
> #9 4.730        at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:105)
> #9 4.730        at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> #9 4.730        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> #9 4.730        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> #9 4.730        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
> #9 4.730        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
> #9 4.730 Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> #9 4.730        [error]: Build step io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor#handleFieldSecurity threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
> #9 4.730        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
> #9 4.730        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> #9 4.730        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> #9 4.730        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> #9 4.730        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
> #9 4.730        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
> #9 4.730        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> #9 4.730        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> #9 4.730        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> #9 4.730        at java.base/java.lang.Thread.run(Thread.java:840)
> #9 4.730        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> #9 4.730
> #9 4.730        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:336)
> #9 4.730        at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
> #9 4.730        at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
> #9 4.730        ... 26 more
> #9 4.730 Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
> #9 4.730        [error]: Build step io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor#handleFieldSecurity threw an exception: java.lang.IllegalArgumentException: Not a parameterized type!
> #9 4.730        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
> #9 4.730        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> #9 4.730        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> #9 4.730        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> #9 4.730        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
> #9 4.730        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
> #9 4.730        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> #9 4.730        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> #9 4.730        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> #9 4.730        at java.base/java.lang.Thread.run(Thread.java:840)
> #9 4.730        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
> #9 4.730
> #9 4.730        at io.quarkus.builder.Execution.run(Execution.java:123)
> #9 4.730        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
> #9 4.730        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
> #9 4.730        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
> #9 4.730        ... 28 more
> #9 4.730 Caused by: java.lang.IllegalArgumentException: Not a parameterized type!
> #9 4.730        at org.jboss.jandex.Type.asParameterizedType(Type.java:272)
> #9 4.730        at io.quarkus.resteasy.reactive.jackson.deployment.processor.ResteasyReactiveJacksonProcessor.handleFieldSecurity(ResteasyReactiveJacksonProcessor.java:343)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> #9 4.730        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> #9 4.730        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> #9 4.730        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> #9 4.730        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
> #9 4.730        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
> #9 4.730        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
> #9 4.730        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> #9 4.730        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> #9 4.730        at java.base/java.lang.Thread.run(Thread.java:840)
> #9 4.730        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
>

**Comment by sschu** [comment]
Best thing you can do in my opinion is set a breakpoint in the method throwing the exception and debug into it.

**Comment by kkcmadhu** [comment]
Yaa.but not sure how to go about it.. it's not at run time.. it's at build/quarkus argumentation time.

Sent from Yahoo Mail on Android 
 
  On Tue, 12 Dec 2023 at 12:15 pm, Sebastian ***@***.***> wrote:   


Best thing you can do in my opinion is set a breakpoint in the method throwing the exception and debug into it.

**Comment by sschu** [comment]
It's still a JVM, you just set it to waiting for a debugger to connect and then connect using a debugger.

**Comment by kkcmadhu** [comment]
not sure if this is related to quakus issue https://github.com/quarkusio/quarkus/issues/13623

**Comment by shawkins** [comment]
@kkcmadhu did you track down your issue here? The problem appears to be happening on a collection: https://github.com/quarkusio/quarkus/blob/d6e52f7775ca99237074e55d87df355980d8b6b5/extensions/resteasy-reactive/quarkus-resteasy-reactive-jackson/deployment/src/main/java/io/quarkus/resteasy/reactive/jackson/deployment/processor/ResteasyReactiveJacksonProcessor.java#L343C100-L344C1 - that and https://github.com/quarkusio/quarkus/issues/13623 seem to point to some unexpected cases not yet correctly handled by jandex / quarkus. 

If possible could you provide a reproducing project like you did with https://github.com/quarkusio/quarkus/issues/13623 - then we can see if this is a distinct issue.
