### ISSUE TITLE
Deprecate offline session preloading

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#25300]
### Description

The new default of Keycloak load offline sessions on demand, and not loading them at startup any more. The old code to preload them at startup should be removed. 

### Discussion

https://github.com/keycloak/keycloak/discussions/25301

### Motivation

The old default of preloading is still available and tested. This makes the code unnecessarily complex and more difficult to test. With a lot of offline token it also doesn't scale. 

We also want eventually use the table structure and lookup functionality to work for all sessions, so this would be a training execerise.

### Details

This issue is about checking that not using preloading works as expected in call cases, and makes preload deprecated for the next release so it can be eventually removed.

One known issue that is not supported without preloading is 

https://github.com/keycloak/keycloak/blob/a45934a762d8726d1cd3ea9c2c0e34e09dd5b849/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L387-L393

**Comment by vramik** [comment]
[The exception](https://github.com/keycloak/keycloak/blob/d411eafc42190b05b4f41fab0a29d51f95a05081/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L390-L392) should not be thrown. `UserSessionProvider.getOfflineUserSessionByBrokerSessionId` is called from single place from the codebase: [`LogoutEndpoint.logoutOfflineUserSession`](https://github.com/keycloak/keycloak/blob/d411eafc42190b05b4f41fab0a29d51f95a05081/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L653-L654) ... this call is guarded by [`offlineSessionsLazyLoadingEnabled`](https://github.com/keycloak/keycloak/blob/d411eafc42190b05b4f41fab0a29d51f95a05081/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L637) flag.

**Comment by ahus1** [comment]
UserSessionprovider#getOfflineUserSessionByBrokerSessionId is a public API, and we would then need to figure out if we want we want to do with this API: deprecate it, or provide an implementation.

As @sguilhen commented: we'll probably deprecated we don't use it as it can be used as shown in the `LogoutEndoint` today. 

We might add back a more optimized method once we see the code base moving forward.

```
    private void logoutOfflineUserSessionByBrokerUserId(String brokerUserId, String brokerSessionId) {
        UserSessionManager userSessionManager = new UserSessionManager(session);
        if (brokerUserId != null && brokerSessionId != null) {
            session.sessions().getOfflineUserSessionByBrokerUserIdStream(realm, brokerUserId)
                    .filter(userSession -> brokerSessionId.equals(userSession.getBrokerSessionId()))
                    .forEach(userSessionManager::revokeOfflineUserSession);
        }
    }
```

**Comment by ahus1** [comment]
As the feedback from the discussion as well as from internal contacts is positive to proceed with this, I'm preparing a PR for this.
