### ISSUE TITLE
Realm composites of client-level roles get directly assigned to realm roles when assigning the client-level role as composite

### ISSUE THREAD

**Issue by Walnussbaer** [keycloak/keycloak#25321]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I have the following keycloak setup:

A realm role called `a_realm_role`. 

A client called `bla-client` with the following roles: `a_client_role`.

The role `a_client_role` contains the realm role `a_realm_role` as composite

I want to create a new role using the Keycloak ADMIN REST API and Resource Owner Password Flow. 

The new role shall contain the `a_client_role` as composite.

This is the request body I send to the Keycloak ADMIN REST API: 

![grafik](https://github.com/keycloak/keycloak/assets/49414693/ecd21a28-315f-468c-8eed-127402ddfcae)

 

### Version

23.0.1

### Expected behavior

The created role `my_role` should contain the following roles as composites: 

![grafik](https://github.com/keycloak/keycloak/assets/49414693/d47e4504-3aec-411a-be2e-e8347e734169)

### Actual behavior

The created role `my_role` contains the `a_realm_role` as composite as well as the other roles. This is wrong in my opinion, `a_realm_role` should only be an inherited role and not be directly assigned to `my_role`

![grafik](https://github.com/keycloak/keycloak/assets/49414693/25805d9a-f63b-4802-bc4b-67829ffad883)

### How to Reproduce?

See section "Describe the bug"

**Comment by graziang** [comment]
Thanks, this seems a valid issue as the `a_realm_role` should be inherited and not directly assigned to `my_role`.

There might be something to fix [here]( 
https://github.com/graziang/keycloak/blob/d1d1d6984099919dea168a215dce64a9c415a76c/services/src/main/java/org/keycloak/services/resources/admin/RoleContainerResource.java#L169-L206).

**Comment by Walnussbaer** [comment]
I don't think that it's a good idea to close this actual bugs as "not planned", because this is still a bug and not a feature. It should at least stay open so people in the future find it and can contribute to it without opening a new issue. Just my 2 cents.
