### ISSUE TITLE
Add a hostname:v1 feature

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#25336]
### Description

To support #24252 the existing hostname options that will become deprecated should be associated with a v1 feature that will initially be enabled by default.  The new options for the hostname will be introduced under hostname:v2.  

Ideally this issue will also address associating options to features, so that validation / cli parsing is conditional on the usage of the feature.  This seems straight-forward with a sequence such as:

./kc.sh build --features=hostname:v1 ...
./kc.sh start ... - expects hostname v1 options

However auto builds may not straight-forward to do directly in picocli - but we can address expectations in the adjunct Picocli.validateConfig method.

cc @mabartos

**Comment by mabartos** [comment]
Currently, I'm working on managing conditional properties, so it'll be easily achievable to ignore properties when the feature is turned on/off. 

I just need to do some polishing and write some tests. 
You can check the progress here: https://github.com/keycloak/keycloak/pull/25333

**Comment by shawkins** [comment]
@mabartos @vmuzikar how do you want to handle --features-disabled=hostname - won't some version always need to be active?

**Comment by mabartos** [comment]
@shawkins In general, the whole feature, regardless of the version, should be disabled. 

However, we're facing some sort of essentiality in features. Especially for the soon provided hostname features as it's necessary to choose one. The other example could be Admin API with a hypothetical API versioning (but I can imagine some cases when even the API could be disabled, right?!).

I'd be more explicit and throw a startup error when the whole hostname is disabled and inform user that the version needs to be specified. @shawkins WDYT?
