### ISSUE TITLE
Remove workaround added due to an issue on Quarkus when processing path parameters

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#25345]
### Description

Remove this change https://github.com/keycloak/keycloak/pull/25296 in favor of the next Quarkus version with the fix from https://github.com/quarkusio/quarkus/pull/37513.

**Comment by ahus1** [comment]
Remote the label "release/24.0.0" as that should IMHO be added only after a code change has been merge. Added Milestone 24.0.0 instead as that one is IMHO used for planning.

**Comment by stianst** [comment]
Removing the backport as this one doesn't really need a backport

**Comment by rmartinc** [comment]
This one was already prformed when working in https://github.com/keycloak/keycloak/issues/25111 (PR https://github.com/keycloak/keycloak/pull/26292). So it's done now.
