### ISSUE TITLE
improve out of the box use

### ISSUE THREAD

**Issue by markixy** [keycloak/keycloak#25350]
### Description

i using docker to start keycloak，command is that：
```sh
docker run -d --name keyclock \
-p 8080:8080  \
-e KEYCLOAK_ADMIN=admin   -e KEYCLOAK_ADMIN_PASSWORD=admin \
keycloak/keycloak:23.0.1 start-dev
```
when i open the http://host:8080 ， page show the tips: “**HTTPS Required**”

i found some answer, using this is work fine.
```
docker exec -it {contaierID} bash
cd /opt/keycloak/bin
./kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin
./kcadm.sh update realms/master -s sslRequired=NONE
```
(https://stackoverflow.com/questions/30622599/https-required-while-logging-in-to-keycloak-as-admin)

### Discussion
The reason for error “**HTTPS Required**” look like that the defaults sslRequired=external on the **master** realm. 
The solution just is simply to set sslRequired=none？it's right? 
In that case, can we provide a configuration to change the default value of sslRequired on  **master** realm？

**Comment by sschu** [comment]
I assume you have mapped `host` to 127.0.0.1? Keycloak recognizes this host name as an external one. If you use `localhost`, it is recognized as internal and http is allowed. The setting is there to be secure-by-default so I don't think the default will change.

**Comment by markixy** [comment]
> I assume you have mapped `host` to 127.0.0.1? Keycloak recognizes this host name as an external one. If you use `localhost`, it is recognized as internal and http is allowed. The setting is there to be secure-by-default so I don't think the default will change.

i use docker to running keycloak, the default hostname is random.  i didn't do anything.
```sh
# docker exec -it keycloak cat /etc/hostname
287e9dae09a8
```

**What i mean is to adding an configuration to change the default value of sslRequired on realm**. such as: --realm-ssl-required=none. whole command like:
```
docker run -d --name keyclock -p 8080:8080  -e KEYCLOAK_ADMIN=admin   -e KEYCLOAK_ADMIN_PASSWORD=admin \
keycloak/keycloak:23.0.1 start-dev --realm-ssl-required=none
```
In this way, when I first start keycloak, i can directly access it.  but now, it can't.
The current situation is that after starting it, I still need to modify **sslRequired** through the command line or Administration Console (only applicable to new realm). It's a little bit troublesome, isn't it?

On the other hand, keyCloak provide two running mode：development（**start-dev**）, production (**start**)
> [Use development mode to try out Keycloak for the first time to get it up and running quickly. This mode offers convenient defaults for developers](https://www.keycloak.org/server/configuration#_starting_keycloak_in_development_mode)

Perhaps sslRequired=none can become defaults on development mode?

**Comment by markixy** [comment]
> I assume you have mapped `host` to 127.0.0.1? Keycloak recognizes this host name as an external one. If you use `localhost`, it is recognized as internal and http is allowed. The setting is there to be secure-by-default so I don't think the default will change.

i use docker to running keycloak, the default hostname is random.  i didn't do anything.
```sh
# docker exec -it keycloak cat /etc/hostname
287e9dae09a8
```

What i mean is to adding an configuration to change the default value of sslRequired on realm. such as: --realm-ssl-required=none. whole command like:
```
docker run -d --name keyclock -p 8080:8080  -e KEYCLOAK_ADMIN=admin   -e KEYCLOAK_ADMIN_PASSWORD=admin \
keycloak/keycloak:23.0.1 start-dev --realm-ssl-required=none
```
In this way, when I first start keycloak, i can directly access it.  but now, it can't.
**The current situation is that after starting it, in order to avoid error “HTTPS Required”, I need to modify **sslRequired=none** through the command line or Administration Console (only applicable to new realm).** It's a little bit troublesome, isn't it?

On the other hand, keycloak provide two running mode：development（**start-dev**）, production (**start**)
> [Use development mode to try out Keycloak for the first time to get it up and running quickly. This mode offers convenient defaults for developers](https://www.keycloak.org/server/configuration#_starting_keycloak_in_development_mode)

Perhaps sslRequired=none can become defaults on development mode?

**Comment by sschu** [comment]
You can access it if you go to http://localhost:8080 by default.

**Comment by markixy** [comment]
> You can access it if you go to http://localhost:8080 by default.

i‘m unable to use http://localhost:8080/, because i start keycloak using docker on remote server. so i need to use http://remoteServerIp:8080 to access it. and then i get the error  “HTTPS Required” when access http://remoteServerIp:8080/admin/master/console/
![image](https://github.com/keycloak/keycloak/assets/83167421/39acdf37-0a90-426a-b2b0-eb4509e940ee)

So, back to the beginning.  I have to use the command line to modify sslRequired=none.(`./kcadm.sh update realms/master -s sslRequired=NONE`)

that is why i want to add an configuration to change the default value of sslRequired on realm. such as：`start-dev --realm-ssl-required=none` this way，it very out of the box

**Comment by sschu** [comment]
You are running it remotely, this explains your issue. However, I don't think this is worth adding another configuration option to Keycloak. It already has a lot of options and adding yet another makes configuration more complicated. I would rather make `sslRequred=NONE` the default for start-dev. However, there might be security implications to this.
Since you have a one-liner to change your realm setting, why don't you just add it to a launch script?

**Comment by markixy** [comment]
keycloak Image `ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]`，execute this script as soon as container start. has good way to add other command line to it?  or rebuild new Image?

**Comment by sschu** [comment]
You can just write a script that first starts Keycloak using your docker command and then calls kcadm either directly from outside the container or inside the container using docker exec.

**Comment by markixy** [comment]
yes, it is one solve way. 
as a keycloak rookie, I still hope to use it directly after startup.

> make sslRequred=NONE the default for start-dev

I'm looking forward to it.

**Comment by markixy** [comment]
`start-dev`  originally designed to provide users with a quick experience. Perhaps “security implications” can tolerate it?

**Comment by markixy** [comment]
get it

**Comment by arab0v** [comment]
fuck me. I spent more than hour debugging keycloak docker file and all i need is to explicitly bind the network to localhost. 
for people who will come here after me make sure you are running your docker with `-p 127.0.0.1:8080:8080`  instead of `8080:8080`
