### ISSUE TITLE
Admin Console: Realm Dropdown should only show the realms the user has access to

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#25392]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Follow up of discussion: https://github.com/keycloak/keycloak/discussions/25342

Basically when accessing a realm specific admin console the user sees all the realms available on the keycloak instance, even though the user does not have access to those. 

This seems to be a regression with version 23, as this was not the case with v22 and prior.

### Version

23.0.1

### Expected behavior

Admin should only see the realms he has access to. For non-master realm admin consoles there might not be a dropdown necessary at all (as only master realm admins can have cross realm permissions afaik).

### Actual behavior

In the realm specific admin console the admin can see all realms available on the keycloak instance. Even the once he does not have access to.

### How to Reproduce?

1. Create multiple realms
2. Create an admin user for a non-master realm
3. Sign in the non-master realm specific admin console as that admin user

### Anything else?

Looks like the newly introduced endpoint for listing the realms for the dropdown does not filter on the user permissions at all: 

https://github.com/keycloak/keycloak/blob/925c5572ad6597e12485402d4d22c1ef15a5b5a6/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/UIRealmsResource.java#L48-L51

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by antikalk** [comment]
Possible duplicate of: https://github.com/keycloak/keycloak/issues/25392

**Comment by jonkoops** [comment]
@hmlnarik this seems like a candidate for a v23 backport, WDYT?

**Comment by hmlnarik** [comment]
@jonkoops Indeed, I updated flags on PR rather than the issue :) PR for 23.0 is here: https://github.com/keycloak/keycloak/pull/25845

**Comment by hardoverflow** [comment]
When will 23.0.5 or the backports be released?

**Comment by Footur** [comment]
Shouldn't a CVE ID be requested for this?
