### ISSUE TITLE
Missing Terms and Conditions step in registration flow

### ISSUE THREAD

**Issue by norbertkriszt** [keycloak/keycloak#25427]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Upgrading Keycloak to version 23.0.1, the Terms and conditions step in the registration flow has disappeared and cannot be added afterwards. It still exists in the master realm, but not in my existing realm and if I try to add a new realm it doesn't exist in that either.

### Version

23.0.1

### Expected behavior

Automatically display the terms and conditions step or add it to the registration flow afterwards.

### Actual behavior

It is not possible to add terms and conditions and by default it does not appear in the registration flow.

### How to Reproduce?

Create a new realm. Click on the Authentication menu left side and on the Flows tab click on the `registration` flow. There is no Terms and conditions step.

**Comment by stelterlab** [comment]
The problem has also been reported for 22.0 - there is a workaround which works at least for 22.0.5.

https://github.com/keycloak/keycloak/issues/21730#issuecomment-1717184106

**Comment by norbertkriszt** [comment]
> +1
> 
> From which version did you upgrade? I tested 21.1.2 + 22.0.4 for a new project and both versions have the same problem. Both fresh installed.

We used the 19.0.3-legacy version.

**Comment by rmartinc** [comment]
Duplicate if #21730.
Yes, it's the same issue, I'll work in the original issue. Closing this as a duplicate.
