### ISSUE TITLE
Failed to find theme resources, using built-in themes when accessing account console

### ISSUE THREAD

**Issue by mandree95** [keycloak/keycloak#25437]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When I call up the Account Console, an error message is written to the log file. This happens both without custom themes and with custom themes. The error message can be seen below:

`keycloak-server-1   | 2023-12-08 16:19:11,664 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-18) Failed to find ACCOUNT theme resources, using built-in themes`

### Version

23.0.1

### Expected behavior

The account console is rendered correctly and there is no error written to the logfile.

### Actual behavior

The account console is rendered correctly and an error is written to the logfile.

### How to Reproduce?

Just open the account console in the browser after starting keycloak (e.g. http://localhost:8080/realms/master/account)

### Anything else?

A similar report has been made at https://github.com/keycloak/keycloak/issues/25087 although not tagged as bug and in relation to custom themes.

**Comment by hmlnarik** [comment]
Confirmed

**Comment by hmlnarik** [comment]
Reason is that some resources are requested with invalid URL, e.g.:
http://localhost:8080/resources/1ljl8/account/**resources**/web_modules/common/plus-icon-e7722410.js
instead of
http://localhost:8080/resources/1ljl8/account/**keycloak.v2**/web_modules/common/plus-icon-e7722410.js

**Comment by hanrx** [comment]
How to solve？
