### ISSUE TITLE
Could not download Node.js for Windows runners

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#25497]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Regular failures in CI testing for Windows:

```
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.14.2:install-node-and-pnpm (default) on project keycloak-js-adapter-jar: Could not download Node.js from: https://nodejs.org/dist/v18.18.2/win-x64/node.exe: Could not download https://nodejs.org/dist/v18.18.2/win-x64/node.exe: Premature end of Content-Length delimited message body (expected: 71,409,304; received: 38,420,172) -> [Help 1]
```

### Version

main

### Expected behavior

Works everytime

### Actual behavior

Fails fairly frequently

### How to Reproduce?

See GH Actions

**Comment by jonkoops** [comment]
Closing this issue, as it is likely resolved by consolidating the front-end build in the project root.
