### ISSUE TITLE
Partial export/import is not mentioned in Keycloak's Server Administration Guide

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#25490]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

There is no section about partial export/import in the docs.

### Version

main

### Expected behavior

A paragraph in the docs explaining how partial export/import works, and when it should be used.

### Actual behavior

No explanations.

### How to Reproduce?

Open https://www.keycloak.org/docs/latest/server_admin/index.html and search for "partial". It provides a CLI options or the Keycloak CLI admin client, but not explanations.

**Comment by mposolda** [comment]
Marking as "important" also because it already has PR and hopefully we can finish this relatively quick.
