### ISSUE TITLE
Docs: server_admin/topics/authentication/password-policies.adoc

### ISSUE THREAD

**Issue by reaperb0t** [keycloak/keycloak#25508]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

File: server_admin/topics/authentication/password-policies.adoc

### Version

23.0.1

### Expected behavior

Please address the necessity of a password policy when a realm is configured with User Federation using LDAP. When LDAP is enabled password policies should not need to be applied, as this is inherited from LDAP.

### Actual behavior

Docs currently do not specify whether a password policy is required when using LDAP.

### How to Reproduce?

Review the password-policies document.

**Comment by ahus1** [comment]
Thank you for raising this. I'm tagging this "help wanted" as we would be happy to receive a community contribution to the documentation to explain the when a password policy makes sense and when not.
