### ISSUE TITLE
Account v3 theme - theme.properties Custom theme scripts not loading

### ISSUE THREAD

**Issue by Fireblade954** [keycloak/keycloak#25502]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Scripts specified in our custom theme.properties are ignored. We used some custom scripts but they are not loaded anymore when updating the keycloak.v3 theme.

### Version

23.0.1

### Expected behavior

scripts defined in theme.properties to get loaded in the theme.

### Actual behavior

Defined script are not loaded

### How to Reproduce?

specify any script in the theme.properties.

ex:

scripts=test.js

where test.js contains

`alert('test alert');`

**Comment by jonkoops** [comment]
@ssilvert does this deserve a backport? We're not officially recommend Account v3 yet, but it might be beneficial.

**Comment by ssilvert** [comment]
@jonkoops Yes, we probably should backport it if we are backporting other V3 fixes.
