### ISSUE TITLE
"rhbk- operator" and "keycloak-edb-cluster" miss resource values

### ISSUE THREAD

**Issue by rgtoronto** [keycloak/keycloak#25513]
### Description

when installing keycloak latest version on openshift cluster

noticed there are 2 containers missing cpu, mem, or ephemeral-storage values:
1. `rhbk- operator` missing entire resource request and limit
<img width="391" alt="image" src="https://media.github.ibm.com/user/16217/files/ce942da4-ba35-4d93-aeb7-183c1da4ef8b">

2. `keycloak-edb-cluster` missing ephemeral storage in `postgres` container, when it has `readOnlyRootFilesystem` disabled

it's suggested to list out `CPU` request/limit, `memory` request/limit, and `ephemeral-storage` request/limit in the resource definition

### Motivation
this is more manageable for Kubernetes to schedule the pods to the nodes with required resources.

**Comment by shawkins** [comment]
Please consider raising RHBK issues through support channels. 

This issue is already captured as #20107 - until it is worked please use the unsupport spec to override the podtemplate however you need.

**Comment by rgtoronto** [comment]
thanks Steven, it's good we already have a ticket to track this. will open a ticket to Redhat support.
