### ISSUE TITLE
Linking IdP Accounts with redirect other than account-console failes

### ISSUE THREAD

**Issue by paulwer** [keycloak/keycloak#25525]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

After calling the endpoint realms/master/account/linked-accounts/google?providerId=google&redirectUri=XXX
and following the link, we get a Invalid Request Website.

When issueing this request from the official account-console it works find.

I have this issue eigher in the account-ui from p2-inc as well as in my own frontend, after calling the endpoint.

I see, that the generated link has property clientId=account-console, which doent match the current client, so i tried to change it/provide it in the initial request, but this has not effect.

### Version

22.0.3

### Expected behavior

Perform oAuth2 connect flow, as like the flow in the account-console.

### Actual behavior

Shows an error page: Invalid Request
the endpoint realms/master/account/linked-accounts/google?providerId=google&redirectUri=XXX returns a proper link and the issue happens, when following it.

### How to Reproduce?

Install p2-inc account-ui or perform a custom request from postman/frontend, with a client other than account-console.

**Comment by pedroigor** [comment]
Thanks. Not really something we support. Could you elaborate why this is a bug?

**Comment by paulwer** [comment]
What do you need for reproduction?
In short we need a way to use the existing link social accounts flow with a client other than the default client (administration-console)


Thanks
Paul

**Comment by paulwer** [comment]
I will test again next week, because I am on vacation.
If I remember correctly i was able to mimic the request completly, but if i wanted to be redirected to a url other than the account console afterwards, i have to change the client. Which results in the issues above.

Can you test with an other client than the default for this flow?

**Comment by paulwer** [comment]
Solved it by putting an additional valid redirect url into the account-console client, containing protocoll (https) and host: 
![image](https://github.com/keycloak/keycloak/assets/52678724/ac7a5989-e2d2-4a6f-8ee8-3ad4b2e00f25)
