### ISSUE TITLE
Published pom should not contain placeholders for dependencies

### ISSUE THREAD

**Issue by arw357** [keycloak/keycloak#25527]
### Description

Published pom https://repo1.maven.org/maven2/org/keycloak/keycloak-adapter-core/23.0.0/keycloak-adapter-core-23.0.0.pom  contains placeholder instead of value  `keycloak-crypto-default` . This should be replaced by the actual value. 
```
<groupId>org.keycloak</groupId>
     <artifactId>${keycloak.crypto.artifactId}</artifactId>
</dependency>  contains 
```

**Comment by shawkins** [comment]
Maven will resolve those values. You can search the parent poms, use maven dependency-tree, or ide tooling such as eclipse's "Effective Pom" to understand what they resolve to.
