### ISSUE TITLE
Workflow failure: FIPS UT/FIPS IT

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#25530]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

FIPS UT and IT tests: 
During startup -> when downloading image from registry.redhat.com using "docker" fails time to time with 502 (bad gateway) or 500 (internal server error) error and causing PR GH actions to fail.

### Version

999.0.0-SNAPSHOT

### Expected behavior

Registry image should be downloaded without any failure.

### Actual behavior

Downloading image from registry.redhat.com using "docker" fails time to time with 502 (bad gateway) or 500 (internal server error) error.

### How to Reproduce?

Failed runs:
- https://github.com/keycloak/keycloak/actions/runs/7182679734/job/19560344268
- https://github.com/keycloak/keycloak/actions/runs/7086203586/job/19284412075
- https://github.com/keycloak/keycloak/actions/runs/7031872487/job/19134728057

**Comment by mposolda** [comment]
@lhanusov Is it still an issue? There was a fix earlier this week related to `FIPS UT` and `FIPS IT` jobs, so maybe this is not valid anymore? Please remove "auto-close" label if you still see this.
