### ISSUE TITLE
Add an option for a custom welcome page to disable bootstrapping of admin account

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#25541]
### Description

https://github.com/keycloak/keycloak/pull/25420 refreshes the welcome page making it simpler and by default redirecting to the admin console. It also introduces the theme property `redirectToAdmin` which a custom theme can set to disable the redirect to for example show a basic page with the company logo.

As an addition to that it would be nice to have a theme property `supportAdminBootstrap` that would allow a custom theme to disable the ability to create the initial admin account through the welcome page.

When a custom theme sets `supportAdminBootstrap=false` and inherits from the Keycloak welcome page it should just display the Keycloak logo, and not allow any form posts. A custom theme can go further of course and replace the `index.html` as well, so in this case it would be just disabling the ability to post the form.

Should be easy to implement with just checking the theme property in the shouldBootstrap method.

**Comment by edewit** [comment]
@stianst how would you set the welcome theme without setting a admin user?

**Comment by edewit** [comment]
not enough information to even work on this
