### ISSUE TITLE
Remove UserProfileProvider.isEnabled

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#25547]
### Description

Once the declarative-user-profile is enabled and we handle all the migration tasks etc, we can also consider removing method `UserProfileProvider.isEnabled(RealmModel realm)` .

It is already deprecated in Keycloak 22  - https://github.com/keycloak/keycloak/blob/22.0.6/server-spi-private/src/main/java/org/keycloak/userprofile/UserProfileProvider.java#L92-L98 . 

This is likely not strictly a blocker for Keycloak 24, but can be still nice to do it though to simplify some user-profile related code.

**Comment by pedroigor** [comment]
It will be solved by https://github.com/keycloak/keycloak/issues/25151
