### ISSUE TITLE
creating group-ldap-mapper iwth bad config make out of memory Java heap space...

### ISSUE THREAD

**Issue by mcarbonneaux** [keycloak/keycloak#25591]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

i've created group-ldap-mapper with ldap user storage. i've used ldap-only with with DN that don't have right to write...
my ldap group liste returned by my group-ldap-mapper are around 2500 groups... in very few seconds my keycloak instance go to 6g of head... and crash....
i've restart my server, and i've juste the time to correct to read-only and save before crash again (i've try multiple restart that crash very rapidly)...
after they worked fine...

### Version

16.1.1

### Expected behavior

eventualy an errror but no out of memory....

### Actual behavior

crash with out of memory Java heap space

### How to Reproduce?

create group-ldap-mapper in ldap-only with readonly dn... and start the sync.... with suffisant number of group on keycloak with good charge....

**Comment by mcarbonneaux** [comment]
i've another environement that are in 21.1.2 i will try to reproduce it on this environement tomorrow...

**Comment by sschu** [comment]
You should actually try with the latest versions since issues that cannot be reproduced on latest version won't be fixed.

**Comment by mcarbonneaux** [comment]
i've not reproducted the problem in 21.1.2, but i've not the same load to be in the same context.

**Comment by sschu** [comment]
If you cannot reproduce the issue on the latest version, I will go ahead and close this issue.

**Comment by mcarbonneaux** [comment]
i dont know if is related with the version or with the load the run on my keycloak...
