### ISSUE TITLE
OpenAPI: POST /admin/realms/{realm}/clients response is 201

### ISSUE THREAD

**Issue by y-tabata** [keycloak/keycloak#25601]
POST /admin/realms/{realm}/clients response is 201 (OpenAPI spec said 200)

**Comment by ahus1** [comment]
When creating new issues from tasks, those need labels so they show up in the release notes later. I'm not sure if you can add them yourself given your permissions. If not, I'll add them, and I'd be happy if you can remind me or another maintainer if those are missing.

**Comment by y-tabata** [comment]
It seems like I cannot add labels so I'll remind maintainers if those are missing.
