### ISSUE TITLE
"What is the function of default groups?" popover shows incorrect text.

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#25618]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

"What is the function of default groups?" popover shows the incorrect text - it appears to be using the translation key for the tab name and not the actual help text.

Expected - KC 22
![image](https://github.com/keycloak/keycloak/assets/4944041/721ee145-e896-4c98-87f2-4cae18a2b3e6)

Actual - KC 23 / nightly
![image](https://github.com/keycloak/keycloak/assets/4944041/d7f64957-be11-463b-8de7-0c5355e6f695)
### 

### Version

23

### Expected behavior

Popover shows the correct, more detailed text.

### Actual behavior

Popover shows the tab name.

### How to Reproduce?

Start Keycloak, navigate to realm settings -> User registration tab -> Default groups subtab -> Click "What is the function of default groups?" text.

**Comment by ssilvert** [comment]
I have verified this bug.
