### ISSUE TITLE
[23.0.3] IFrame check uses wrong protocol (http instead of https)

### ISSUE THREAD

**Issue by luke7479** [keycloak/keycloak#25640]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After upgrading to keycloak 23.0.3, the admin ui can not be opened anymore. The redirects to /admin/master/console are working properly and the loading circle appears, but does not vanish.

Console says: "Timeout when waiting for 3rd party check iframe message." *once*

Chrome mentions a resource blocked by CSP headers (which is totally right), because http is used instead of https: `http://auth.xyz	blocked	frame-src	keycloak.mjs:1277`

### Version

23.0.3

### Expected behavior

Admin UI should open properly, or at least an error should be shown, that iframe check to (url) failed

### Actual behavior

Loading circle is spinning endlessly, due to failed iframe check

### How to Reproduce?

Didn't try a fresh instance, but both servers I am running are showing the exact same behaviour.

### Anything else?

I am happy to provide links, but not public.

**Comment by Victoremepunto** [comment]
@luke7479 perhaps your setup involves putting Keycloak behind a reverse proxy ? ie - Openshift handling TLS secure routes ? if so, make sure to add the —proxy edge option on the initial args (I’ve recently seen that been an issue after an upgrade to Keycloak 23.X)

if not, feel free to disregard.

**Comment by jonkoops** [comment]
This sounds a lot like a configuration error, I don't believe this is a bug in the Admin Console itself.

**Comment by luke7479** [comment]
Good morning,

finally came to check your recommandation.. (Sorry for the delay)

Indeed I forgot to paste the most important part: I am using keycloak behind traefik, ran fine before and I set the KC_PROXY variable in compose file to passthrough:
```yaml
  keycloak:
    image: docker.int.ithassler.de/general/cache/keycloak/keycloak:23.0.2
    restart: unless-stopped
    container_name: keycloak
    command: start-dev
    environment:
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KEYCLOAK_ADMIN: {{ KEYCLOAK_ADMIN_USER }}
      KEYCLOAK_ADMIN_PASSWORD: {{ KEYCLOAK_ADMIN_PASSWORD }}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: {{ KEYCLOAK_DB_USER }}
      KC_DB_PASSWORD: {{ KEYCLOAK_DB_PASSWORD }}
      KC_PROXY: passthrough
      KC_HOSTNAME: "{{ KEYCLOAK_DOMAIN | default('keycloak') ~ '.' ~ DOMAIN }}"
    depends_on:
    - keycloak-db
    networks:
    - {{ KEYCLOAK_NETWORK | default('dev') }}
{% if TRAEFIK_NETWORK_GITLAB is defined and TRAEFIK_NETWORK_GITLAB | length and TRAEFIK_NETWORK_GITLAB != TRAEFIK_NETWORK | default('dev') %}
    - {{ TRAEFIK_NETWORK_GITLAB }}
{% endif %}
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network={{ KEYCLOAK_NETWORK | default('dev') }}"
    - "traefik.http.routers.keycloak.entrypoints=websecure"
    - "traefik.http.routers.keycloak.rule=Host({{ KEYCLOAK_DOMAIN | default('keycloak') ~ '.' ~ DOMAIN }})"
    - "traefik.http.routers.keycloak.tls=true"
    - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
    - "traefik.http.services.keycloak-service.loadBalancer.server.port=8080"
    - "traefik.http.routers.keycloak.service=keycloak-service"```

Even if I didn't set the variable, then I would be wondering, why only one url is set/called wrong. If you have another idea, I would be glad to test it. Thanks :)

**Comment by jonkoops** [comment]
Closing this as a configuration error, I think we'll be improving this under #24252
