### ISSUE TITLE
LDAP synchronization issue with large groups renaming

### ISSUE THREAD

**Issue by YuriKitkevich-OL** [keycloak/keycloak#25641]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

We are experiencing a critical issue with our Keycloak instance that involves LDAP synchronization. Our LDAP directory contains a substantial number of groups, approximately 8,000, which have been initially successfully synced into Keycloak. However, when a significant number of group changes occur in LDAP, specifically a large-scale renaming within one substantial branch, Keycloak fails to handle these changes within a specific timeframe.

```
 | 2023-12-17 13:35:51,408 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffffac160003:a669:657ef7fa:c5 in state  RUN
kc1         | 2023-12-17 13:35:51,409 INFO  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012404: Action id 0:ffffac160003:a669:657ef7fa:c5 - thread executor-thread-3 at time 13:33:51.409 had stackTrace org.hibernate.engine.internal.Cascade.cascade(Cascade.java:184)
kc1         | org.hibernate.event.internal.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:161)
kc1         | org.hibernate.event.internal.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:144)
kc1         | org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:79)
kc1         | org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:48)
kc1         | org.hibernate.internal.SessionImpl$$Lambda$1125/0x0000000800bee000.accept(Unknown Source)
kc1         | org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
kc1         | org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1375)
kc1         | org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.scroll(JdbcSelectExecutorStandardImpl.java:115)
kc1         | org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$1(ConcreteSqmSelectQueryPlan.java:136)
kc1         | org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan$$Lambda$1096/0x0000000800bda650.interpret(Unknown Source)
kc1         | org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:303)
kc1         | org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performScroll(ConcreteSqmSelectQueryPlan.java:252)
kc1         | org.hibernate.query.sqm.internal.QuerySqmImpl.doScroll(QuerySqmImpl.java:629)
kc1         | org.hibernate.query.spi.AbstractSelectionQuery.scroll(AbstractSelectionQuery.java:445)
kc1         | org.hibernate.query.spi.AbstractSelectionQuery.stream(AbstractSelectionQuery.java:457)
kc1         | org.hibernate.query.Query.getResultStream(Query.java:168)
kc1         | org.keycloak.models.jpa.GroupAdapter.getSubGroupsStream(GroupAdapter.java:141)
```

### Version

23.0.3

### Expected behavior

The expected behavior for the described scenario is that Keycloak should seamlessly handle LDAP synchronization, even when confronted with many group changes, such as extensive renames within a specific LDAP branch. 

### Actual behavior

When a substantial number of group changes occur in LDAP, specifically a large-scale renaming within a significant branch, Keycloak experiences failures during the synchronization process. 

### How to Reproduce?

**Create synchronization with LDAP.**

![Pasted Graphic 12](https://github.com/keycloak/keycloak/assets/47206611/bd58b4f0-ef3f-4433-97f2-64065aaa399e)

![Pasted Graphic 13](https://github.com/keycloak/keycloak/assets/47206611/73710740-f149-4d50-9ccf-9dfc978e9f45)

![Pasted Graphic 14](https://github.com/keycloak/keycloak/assets/47206611/1d02533d-b234-458e-a780-97dc7e6d55a8)

![Pasted Graphic 15](https://github.com/keycloak/keycloak/assets/47206611/e4ac837b-23a0-4aab-aacb-56ee76a2d4dd)

**Create and configure Standard LDAP Group Mapper.**

![Pasted Graphic 18](https://github.com/keycloak/keycloak/assets/47206611/16d9c462-fe40-4001-9737-dc6eaaba4930)

![Pasted Graphic 17](https://github.com/keycloak/keycloak/assets/47206611/31706d1a-5e67-485a-adbb-25280950144b)
￼
**Proceed with initial User and Group Synchronization.** 

To reproduce the issue, perform a substantial renaming operation on a significant number of groups within a specific branch of the LDAP directory and observe Keycloak's synchronization behavior. 

After some period of time, Keycloak fails with an exception and no groups are synchronized.

logs attached
[kc_start.log](https://github.com/keycloak/keycloak/files/13696332/kc_start.log)

￼

### Anything else?

Also, in case of performing a substantial renaming operation on a significant number of groups within a specific branch of the LDAP directory it is possible to break Keycloak with one of the following actions.

1. In the KC admin UI try to find any user and check his groups (repeat that step 6 times).
After such actions, KC will be unresponsive. 

![Pasted Graphic 8](https://github.com/keycloak/keycloak/assets/47206611/1cf1282d-1989-4dbb-bfc9-955ed7cd1a90)

2. Go to any group and try to check group members (include sub-group users).

![Access Control Root](https://github.com/keycloak/keycloak/assets/47206611/acd5395f-3a01-44f5-b69e-5141c292933e)

After some time we get error:

![Pasted Graphic 20](https://github.com/keycloak/keycloak/assets/47206611/a29cfd52-ac41-4fcf-9909-90a06d502d5c)
 

On each such action, KC runs a new thread with full LDAP re-sync.
https://github.com/keycloak/keycloak/blob/ae04b954a6cf57a1c2a0ec01fa2d42bba11abb26/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/membership/group/GroupLDAPStorageMapper.java#L380-L390

**Comment by mhajas** [comment]
Thank you for the report @YuriKitkevich-OL. This issue has been present for some time already. I found the following:
- https://github.com/keycloak/keycloak/issues/10242
- https://keycloak.discourse.group/t/keycloak-timeout-issue/2309

We are probably unable to do much better as we need to go through all Keycloak groups and check whether it still exists in LDAP. Synchronization of two different sources is a long taking process because we need to make sure we detect changes in both places. I will leave this issue open so we can have a look later but this won't be a priority for us at the moment due to other work we have on our plate. If anyone is interested in looking into this, they are more than welcome.

What you can try to make it better:
- As suggested in the linked discussion, increase the transaction timeout, this will not decrease the time needed for sync but it will not fail
- if you have some other groups from other sources, you can set a different parent group for this LDAP provider, this will cause Keycloak to check only groups imported from this provider and can speed up the process
- Disable `Drop non-existing groups during sync`

**Comment by yura-kit** [comment]
@mhajas Thank you for your reply!
One question. In case we decide to split one large existing LDAP provider to several smaller providers. 
Is there opportunity to save existing privileges (roles) which already assigned to existing groups?
