### ISSUE TITLE
Search for all groups of a user doesn't show all groups

### ISSUE THREAD

**Issue by kitenco** [keycloak/keycloak#25658]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

A user is a member of a group in active directory.
Go to User -> Groups 
the list of all groups doesn't include the ad group
BUT
search for the group name
then it appears

### Version

21.1.1

### Expected behavior

the ad groups directly appears when you enter the tab and search for all groups

### Actual behavior

the search for groups result doesn't contain the ad group

### How to Reproduce?

maybe just create a identity provider (AD), create a user, create a group, put user in group
make a sync, check the search result of the groups tab

**Comment by ssilvert** [comment]
Moving to the core team as it sounds like the REST API is not returning what @kitenco expects.

**Comment by sguilhen** [comment]
@kitenco Would you be able to try this using the latest Keycloak version? I've tried to reproduce locally but the groups were correctly synched (provided the group mapper was configured, of course) along with the users and readily available in the Groups tab (both top level Groups menu item, and under User -> search for the user -> Groups)
