### ISSUE TITLE
[Admin UI] Allow to customize built-in components administration UI via ConfiguredProvider

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#25666]
### Description

`org.keycloak.provider.ConfiguredProvider` allows to provide a list of `org.keycloak.provider.ProviderConfigProperty`. This list is then interpreted by the admin UI to generate a list of UI inputs. As of today, almost all `ProviderFactory` implement `ConfiguredProvider`.

This nice feature can be used to add custom fields on a third-party `ProviderFactory`, but not on a built-in one.

I'd like to be able to add custom fields to built-in components.

### Motivation

I need to add some config properties to all `org.keycloak.broker.provider.IdentityProviderFactory` and `org.keycloak.broker.social.SocialIdentityProviderFactory` implementations, including the built-in ones. I need them to be seizable via the Admin UI.

### Details

This could take the form of a new SPI allowing to "complete/enrich" the list returned by `org.keycloak.provider.ConfiguredProvider#getConfigProperties`.

**Comment by reda-alaoui** [comment]
#25697 was only a first step for the current issue, I should not have used keyword `Closes` in https://github.com/keycloak/keycloak/pull/25697#issue-2048491480

@hmlnarik could you reopen this issue ?

**Comment by hmlnarik** [comment]
@reda-alaoui Yup, I did, since I saw the PR as a self-contained piece that would suffice for custom identity provider configuration. As for the SPI, I suggest that you open new issue(s). Should it have more tasks, could you please create a tasklist within?
I think though that there will be some discussion needed around whether a new SPI is really desirable.

**Comment by hmlnarik** [comment]
> @hmlnarik, in fact, I didn't use `Closes`, but you did 🙃

Yup, I did :) - for the reasons above
