### ISSUE TITLE
Workflow error: Base IT - RefreshTokenTest#refreshTokenWithDifferentIssuer

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#25675]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Base IT (6)](https://github.com/keycloak/keycloak/actions/runs/7241907163/job/19726798827)

```
Error: OR] Errors: 
Error: OR] org.keycloak.testsuite.oauth.RefreshTokenTest.refreshTokenWithDifferentIssuer
Error: OR]   Run 1: RefreshTokenTest.refreshTokenWithDifferentIssuer:310 » Runtime java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io: Temporary failure in name resolution
Error: OR]   Run 2: RefreshTokenTest.refreshTokenWithDifferentIssuer:310 » Runtime java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io
Error: OR]   Run 3: RefreshTokenTest.refreshTokenWithDifferentIssuer:310 » Runtime java.lang.RuntimeException: java.net.UnknownHostException: proxy.kc.127.0.0.1.nip.io
```

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by miquelsi** [comment]
Happened again: https://github.com/keycloak/keycloak/actions/runs/11592703130/attempts/1

**Comment by rmartinc** [comment]
@miquelsi @mposolda This is a `temporary failure in name resolution`, so it seems that the resolution of the name `proxy.kc.127.0.0.1.nip.io` failed in the GHA environment. It's a glitch in the network as we see sometimes when downloading things in GHA.

Maybe we can use `localhost` instead of `proxy.kc.127.0.0.1.nip.io` as the test would work in the same way as the ports are different and the issuer is diferent.

**Comment by mposolda** [comment]
@rmartinc If you think that test can be updated (without impact on the tested functionality), we can go for it.

But in general, this is workaround just to handle the issue with GH actions networking and it can probably happen also in some other scenarios :-/ But I am not sure if we can have some better approach to handle network errors...
