### ISSUE TITLE
Introduce new CLI config options for Infinispan remote store

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#25676]
There is an XML config file (cache-ispn.xml) with Infinispan configuration. When used in crossdc setup it's needed to specify configuration for remote store to be able to connect to remote Infinispan server: https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispan ... as an example how it could look like: https://github.com/keycloak/keycloak/blob/main/docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml

This issue is to improve and simplify configs for users by allowing to specify following CLI options: "[remote-store-host](https://github.com/keycloak/keycloak/blob/2853136bbbdd6bc34b3e3f9452eb3f74df9b49c7/docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml#L56C36-L56C40)", "[remote-store-port](https://github.com/keycloak/keycloak/blob/2853136bbbdd6bc34b3e3f9452eb3f74df9b49c7/docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml#L57C36-L57C40) ", "[remote-store-username](https://github.com/keycloak/keycloak/blob/2853136bbbdd6bc34b3e3f9452eb3f74df9b49c7/docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml#L62C37-L62C45)", "[remote-store-password](https://github.com/keycloak/keycloak/blob/2853136bbbdd6bc34b3e3f9452eb3f74df9b49c7/docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml#L63C37-L63C45)", “[remote-store-truststore](https://github.com/keycloak/keycloak/blob/2853136bbbdd6bc34b3e3f9452eb3f74df9b49c7/docs/guides/high-availability/examples/src/kcb-infinispan-cache-remote-store-config.xml#L68C30-L68C40)” which would then be used instead of the xml.

There are several different caches which needs to be configured and we'd like to opinionated here and specify same remote Infinispan for all of them.

**Comment by vramik** [comment]
@keycloak/cloud-native FYI, let's discuss it after break

**Comment by vmuzikar** [comment]
@vramik Thanks for creating the issue.

Before implementing this, IMHO we should step back a little bit and think through our longer-term plan for config UX around ISPN. We probably want to get rid of the config XML file especially in K8s env, at least for some simpler use cases that don't require too complex configuration that would get too confusing for CLI. Therefore I'd suggest first creating some design for the ISPN config UX (without implementing it) and align these new "remote" with it. WDYT?

CC @keycloak/cloud-native @keycloak/store

**Comment by vmuzikar** [comment]
`cache-` prefix sounds nice to me. Although, IMHO we should still try and list other expected ISPN config options (that we'll add in the future) to see how the remote options align with it.

**Comment by pruivo** [comment]
Just to be clear, you want to parse the Infinispan XML file and, if `cache-remote-store*` is enabled, modify the cache configuration to inject the `<remote-store>`?

**Comment by ahus1** [comment]
@pruivo - I hope I wouldn't need to do nay manual XML parsing, and that we would get away with similar (minimal) Java code as presented in your PR #25703. But basically yes.

**Comment by pruivo** [comment]
@ahus1 You need to parse the XML file to fetch the `org.infinispan.configuration.cache.PersistenceConfigurationBuilder`. After that, we can manipulate it as we wish. 
I can work on a draft PR if you want.

**Comment by ahus1** [comment]
@pruivo - let's first agree with @vmuzikar how the CLI should like. Once that has been agreed, it might be the turn of someone else so that we spread the knowledge and share the fun.

**Comment by vramik** [comment]
We've discussed and agreed on naming on today's call with @ahus1 and @vmuzikar. There should be following params introduced: `cache-remote-host`, `cache-remote-port`, `cache-remote-username`, `cache-remote-password`
