### ISSUE TITLE
When new tokens are get in Keycloak, previous sessions are not closed

### ISSUE THREAD

**Issue by zoroglu** [keycloak/keycloak#25689]
### Description

A new session is created every time I get tokens from Keycloak. Every time I get a token, I want the previous sessions to be closed. I have not seen such a service on the Keycloak side. What method can be developed for this?

Keycloak version: 19.0.0

i get the token in this way.
**URL:** http://keycloak_url/realms/{realm}/protocol/openid-connect/token
**body**
```
username:{username}
password:{password}
client_id:{client}
grant_type:password
```

![Screenshot from 2023-12-19 20-24-14](https://github.com/keycloak/keycloak/assets/32324184/5fa90d4d-f8bf-4bea-93e3-c468a88daa02)

when i query with client_id, I can see that a session occurs every time I receive a token
http://keycloak_url/admin/realms/{realm}/clients/{client-id}/user-sessions

**Comment by mposolda** [comment]
It will be good if you specify what exactly are you doing. As your description is very vague. How exactly are you getting tokens from Keycloak?

If you use browser-based authentication, there is SSO session and hence there is only single userSession per browser. The subsequent login will use existing SSO session instead of creating new session.

If you use OAuth2 resource-owner-password-credentials grant, then new login will always create new session as you pointed. But in this case, you can use token refresh once you login, so you don't need to always login again, but you can instead rely on token refresh.

**Comment by zoroglu** [comment]
> It will be good if you specify what exactly are you doing. As your description is very vague. How exactly are you getting tokens from Keycloak?
> 
> If you use browser-based authentication, there is SSO session and hence there is only single userSession per browser. The subsequent login will use existing SSO session instead of creating new session.
> 
> If you use OAuth2 resource-owner-password-credentials grant, then new login will always create new session as you pointed. But in this case, you can use token refresh once you login, so you don't need to always login again, but you can instead rely on token refresh.

i get the token in this way.
**URL:** http://keycloak_url/realms/{realm}/protocol/openid-connect/token
**body**
```
username:{username}
password:{password}
client_id:{client}
grant_type:password
```

**Comment by jbman** [comment]
This is the client credentials grant so you can also switch of session creation (not sure if it is already in 19). When in the advanced tab of the client settings, the setting "Use refresh tokens for client credentials grant" is switched off, no sessions should be created. 

![image](https://github.com/keycloak/keycloak/assets/789496/7ccbb371-ab19-4c0b-b82b-2fd5507522a6)

![image](https://github.com/keycloak/keycloak/assets/789496/b29a0bc3-f68e-4e6b-bc61-79a37ed450de)

Or you have it on and use a refresh request for subsequent token request as proposed by @mposolda 

Note: Issue should be closed.

**Comment by zoroglu** [comment]
> This is the client credentials grant so you can also switch of session creation (not sure if it is already in 19). When in the advanced tab of the client settings, the setting "Use refresh tokens for client credentials grant" is switched off, no sessions should be created.
> 
> ![image](https://private-user-images.githubusercontent.com/789496/291649843-7ccbb371-ab19-4c0b-b82b-2fd5507522a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDYyMDEsIm5iZiI6MTcwMzAwNTkwMSwicGF0aCI6Ii83ODk0OTYvMjkxNjQ5ODQzLTdjY2JiMzcxLWFiMTktNGMwYi1iODJiLTJmZDU1MDc1MjJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNzExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzBkNWQ3OTEyNGQ2N2NmMTUwNzNkOGFiNjBkNWM1YThlYzVlZmMyYmU4NTEyZDE5OTlkYzdlZjY2N2IxOWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7EV5fG091sNQmg44w6DBz4tsAwYV2knbMNuSaBnOGFM)
> 
> ![image](https://private-user-images.githubusercontent.com/789496/291649671-b29a0bc3-f68e-4e6b-bc61-79a37ed450de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDYyMDEsIm5iZiI6MTcwMzAwNTkwMSwicGF0aCI6Ii83ODk0OTYvMjkxNjQ5NjcxLWIyOWEwYmMzLWY2OGUtNGU2Yi1iYzYxLTc5YTM3ZWQ0NTBkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNzExNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzgxOWQ1YTllYTJjMjI0MGVlOTUzNDQ4NGJlM2U1YWE3NTk1YTEyYTJlMmVmMzVhMWJlMDZmZjY3ZmQ5MzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nm9Fn87npnPQKVRhkHJDWkB2IrSDcwY7uI7AzcWYREk)
> 
> Or you have it on and use a refresh request for subsequent token request as proposed by @mposolda
> 
> Note: Issue should be closed.

The "Use refresh tokens for client credentials grant" parameter is already closed. however, every time I buy a token, a new session occurs.

![Screenshot from 2023-12-19 20-24-14](https://github.com/keycloak/keycloak/assets/32324184/a49b9e4c-e2c7-4983-a018-dd61727c0add)

when i query with client_id, I can see that a session occurs every time I receive a token
`http://keycloak_url/admin/realms/{realm}/clients/{client-id}/user-sessions`

**Comment by souravs17031999** [comment]
@zoroglu As I see you have enabled use refresh tokens , so you should use refresh token flow to get access tokens which will update the same session instead of everytime trying to get token using password grant flow in which case a new session will be created every time.

Please refer https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.3
