### ISSUE TITLE
User Profile: Allow customization of normalization methods

### ISSUE THREAD

**Issue by adrhine** [keycloak/keycloak#25681]
### Description

The `org.keycloak.userprofile.DefaultAttributes#normalizeAttributeValues` method is currently breaking compatibility for us as our attributes are not always of type `String`. By making this method overridable, we will be able to parse attributes the way we expect them to be.

### Discussion

https://github.com/keycloak/keycloak/pull/25678

### Motivation

Although we want to get rid of a lot of our custom code around UserProfile, there is also a desire to stay up-to-date with the latest Keycloak version. It will take quite some time to fully remove our incompatible code here so having some ability to support what we have today is really valuable.

**Comment by sschu** [comment]
Fixed by https://github.com/keycloak/keycloak/pull/25678.
