### ISSUE TITLE
Keycloak session token expiring even before the defined time

### ISSUE THREAD

**Issue by nikhilchennam** [keycloak/keycloak#25690]
### Description
Hi Team,

We configured below keycloak settings(PFA) as 10 mins and logged into the client application and copied the generated “sessionToken”. When decoded it, the expiry time is “10 Mins” from time of creation(As defined). But it’s not working as expected the application is getting timed out after 5mins exact.

We are able to see the below error in Log:

error="invalid_token", error_description="Token is not active".

If we set the Token Lifespan as 20mins, it’s getting inactive after 10mins. And if we set it as 30mins it’s getting expired after 15mins (Exponentially).

Please help us resolving the same.

![Uploading Keycloak_setting.png…]()

Thanks,
Nikhil

**Comment by jbman** [comment]
Hi, can you please try to reproduce it with the latest release?
You could then file a bug report, if the problem occurs there as well.

**Comment by jonkoops** [comment]
Closing this issue due to lack of response from the author.
