### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by dioni-dev** [keycloak/keycloak#25696]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I am getting this error: Traceback (most recent call last):
  File "/usr/src/app/arbiter/lifecycle.py", line 323, in do_main_program
    proteus.auth.admin.create(
  File "/opt/conda/envs/proteus-arbiter/lib/python3.9/site-packages/proteus/oidc.py", line 359, in create
    self.auth.proteus.api.raise_for_status(response)
  File "/opt/conda/envs/proteus-arbiter/lib/python3.9/site-packages/proteus/api.py", line 361, in raise_for_status
    raise http_error
  File "/opt/conda/envs/proteus-arbiter/lib/python3.9/site-packages/proteus/api.py", line 336, in raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/proteus-arbiter/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://myurl.com/admin/realms/myworker/users. Returned error payload: {
  "error": "HTTP 401 Unauthorized"
}

I am not able to make this authentication works, i did everything i can image.

This is my client ID configuration:

![Screenshot 2023-12-19 122249](https://github.com/keycloak/keycloak/assets/58851263/319446af-b183-4109-956a-2b33c2abe542)
![Screenshot 2023-12-19 122158](https://github.com/keycloak/keycloak/assets/58851263/ff80f9a0-09e4-4586-9feb-ac957b9e7f20)
![Screenshot 2023-12-19 122104](https://github.com/keycloak/keycloak/assets/58851263/8e084a8b-8a4d-4cd3-8edd-9698d0036542)

Anything is missing?

### Version

Keycloak 23.0.2

### Expected behavior

I expecte to login properly

### Actual behavior

you can see on the description

### How to Reproduce?

download Keycloak 23.0.2 and create the client ID on my realm as i put in the screenshots

**Comment by rmartinc** [comment]
@dioni-dev I don't understand what you are trying to achieve here. You talk about authentication but then the failure is sending a request to the admin interface. What are you trying to do?

In order to access the admin interface you need to send a valid access token with the correct roles in it. So you need to authenticate previously to a client and obtain the correct roles in the token. Using plain curl you have examples for example here: https://linuxdatahub.com/keycloak-rest-api-commands-cheat-sheet-with-examples/
