### ISSUE TITLE
UpdatePassword-Flow Not Verifying Old Password, MaxAuthAge can be changed before changing the password

### ISSUE THREAD

**Issue by dinutine** [keycloak/keycloak#25695]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Requesting an enhancement in the Account-Theme to include old password verification before changing a new password.
UpdatePassword-Form does not validate old password before updating the new password.
See: https://github.com/keycloak/keycloak/issues/12943

As a solution the MaxAuthAge password policy was introduced.

The reason that you have to retype your old password is to protect while you accidentally leave some UI opened while leaving your desk, some attacker changes your password.
If the person leaving the UI opened has realm management role, the attacker can first change the MaxAuthAge to a high number, change the password (without the need for the old password) and set the MaxAuthAge back.

The introduction of the MaxAuthAge is certainly an improvement, but the solution is still incomplete.

### Version

22

### Expected behavior

The old password is requested when updating the user's password

### Actual behavior

When the attacker changes the MaxAuthAge to a very high number before updating the password, it is not required to type the current password.

### How to Reproduce?

Create a user with manage-realm role.
Login into the admin console with this user.
Leave the UI opened for 10 minutes.
Go to Authentication, Policies, Add policy Max Auth Age, put value on 100000 seconds,
Go to manage account, Personal info, Account security, Signing in, Update password.
Reauthentication is not needed to change the user's password

**Comment by sschu** [comment]
I don't really think there is an additional vulnerability here compared what administrators can already do. If you can manage users, you can change their password anyways. If you can impersonate them, you can act as them. Assuming you just have the manage-realm permission so you can change the configuration of the MaxAuthAge password policy, there are probably other things as well you can do to get the user privileges like changing authentication flows to not ask for a password in the first place.
@mposolda WDYT?

**Comment by mposolda** [comment]
@sschu Yes, exactly. Keycloak cannot prevent the situation when realm administrator leaves his desk opened and then someone else is able to go to admin console and change anything they want. I am closing this as I don't consider this as a bug.

@dinutine Please consider creating enhancement for adding "old password" to the account console form, but not sure if we ever add support for that as not seeing much reason for that (apart from the corner-cases you mentioned).

**Comment by m-serag-lab** [comment]
Hello everyone, I did a small demo for changing password with validating old password.

You can check it here

https://github.com/m-serag-lab/keycloak-change-password/tree/main
