### ISSUE TITLE
Add Javadoc for searchQuery parameter in UsersResource.count()

### ISSUE THREAD

**Issue by jmax01** [keycloak/keycloak#25708]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client/java

### Describe the bug

The  `UsersResource.count(... @QueryParam(value="q") String searchQuery)` searchQuery is not documented while all the other parameters are.__

### Version

23.0.3

### Expected behavior

searchQuery has a description

### Actual behavior

Javadoc missing searchQuery

### How to Reproduce?

Read the Javadoc

### Anything else?

https://github.com/keycloak/keycloak/blob/eb184a8554a2ed59203f65965df85d1165742359/integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UsersResource.java#L312

**Comment by sguilhen** [comment]
I'm adding a `help-wanted` label for this one so the community can pick it up. It might be good not only to document the missing param but also the other methods that are currently lacking javadocs in this interface.
