### ISSUE TITLE
Custom Validator is never executed when UserProfileContext is UPDATE_EMAIL

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#25704]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

With `DECLARATIVE_USER_PROFILE` and `UPDATE_EMAIL` enabled, I add a `validation` on the `email` attribute as follow:

![image](https://github.com/keycloak/keycloak/assets/2890843/e4508fe8-e48c-465c-9600-baf971281145)

The Validator is never triggered in an `UPDATE_EMAIL` context.

### Version

23.0.3

### Expected behavior

The Validator should be triggered, even within the  `UPDATE_EMAIL` context.

### Actual behavior

The Validator is never triggered in an `UPDATE_EMAIL` context.

### How to Reproduce?

- Enable `DECLARATIVE_USER_PROFILE` and `UPDATE_EMAIL`
- Enable `User Profile` on the realm
- Add a validation on the `email` attribute
- See it ignored when changing the email via the `UPDATE_EMAIL` form

### Anything else?

Seems to be caused by https://github.com/keycloak/keycloak/blob/810ebf4efd452a9f3a31df3847301d1a6deaba72/services/src/main/java/org/keycloak/userprofile/DeclarativeUserProfileProvider.java#L269-L273, introduced in a6137b9b86820e5899652d6ddd483f704f7f6b3c .

**Comment by reda-alaoui** [comment]
@pedroigor Could we "just" remove this exception on `UPDATE_EMAIL` ?

**Comment by pedroigor** [comment]
@reda-alaoui Sure. We should respect any validation you might have for the email attribute regardless of the context.

**Comment by pedroigor** [comment]
@reda-alaoui Would you mind giving it a spin? See https://github.com/keycloak/keycloak/pull/25732.

**Comment by reda-alaoui** [comment]
@pedroigor I am building your PR right now :)
