### ISSUE TITLE
Clarify concerns about UMA Token endpoint performance

### ISSUE THREAD

**Issue by CarloDeSutter** [keycloak/keycloak#25717]
### Description

Hi,

I am not directly creating an issue because we are not yet working on the latest server version.

We are, for now, looking for some clarification of the following situation, as we are wondering if we are doing something that is not Keycloak-idiomatic in terms of calling that API for RPTs, or we need to dive in further at our end. 

We are having some very strange behaviour when it comes to requesting RPT's through the token endpoint, grant type urn:ietf:params:oauth:grant-type:uma-ticket. I am worried this won't be solved by upgrading to later versions.

We have:
- Staging which was upgraded from v12 to v21 without issues but with even less load we are getting even worse performance (from 100ms to over 2000ms for one RPT call)
- Production sitting on v12

Both versions seem to have bad performance when calling the endpoint, the strange thing being that "normally" we get 50-150 ms for one call (RPT for 500+ resources), and then it tends to degrade up until over 20000ms for that same call every subsequent time. Doing a rolling restart, or clearing the realm and user cache seems to help temporarily which had me thinking this would be better on v21, but it is not, although, granted, we might be comparing apples to oranges at this stage. But we're so far not yet convinced to just bump production up to v21 yet.

I've spent some time looking in the Java code and git history, as well trying to find issues here but I would have expected to have found something by now as we are not putting in yet much load in the instances and have been hitting some limit pretty soon in. Perhaps I am missing some major bug but I'd like some details on that so we can find out at what version that would be solved for instance, or if this is something on our end only.

We are using a Helm chart setup, the Pods have sufficient RAM and CPU, the mysql DB sits in AWS. At first sight this seems DB(indirectly via network or directly)-bound, but I would expect that this is some weird caching bug (as we have some means to improve it very shortly) and that this would hopefully be solved by upgrading.

**Comment by CarloDeSutter** [comment]
Friendly bump.

I cannot imagine this doesn't ring a bell to anyone?
Don't hesitate to let me know if I should post this elsewhere or in another form.

**Comment by sschu** [comment]
There is a Q&A section in the discussions, see https://github.com/keycloak/keycloak/discussions/categories/q-a.
If you can give a reproducer for the problem and you have reproduced the problem on the latest Keycloak version, you can also create a bug issue.

**Comment by CarloDeSutter** [comment]
Thanks for your reply @sschu 
I've created https://github.com/keycloak/keycloak/discussions/25821.

**Comment by sschu** [comment]
Thanks @CarloDeSutter. I'll go ahead and close this issue for now.
