### ISSUE TITLE
 Login theme set for client is not reflected when using Device Authorization Grant

### ISSUE THREAD

**Issue by kalpa-sith** [keycloak/keycloak#25725]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When using a Device Authorization Grant, the login theme set in clinet will not be reflected on the screen that is displayed only with the Device Authorization Grant.
![image](https://github.com/keycloak/keycloak/assets/88638288/28f5304f-bc1c-4058-bd42-ea21988fcd48)
![image](https://github.com/keycloak/keycloak/assets/88638288/df374b40-fc16-470f-a483-a107cd443f27)

### Version

23.0.3(nightly)

### Expected behavior

The login theme set on the client will be reflected.

### Actual behavior

The login Theme set on the client will not be reflected, but the login theme set on realm will be reflected.

### How to Reproduce?

Set a login theme on the client that is different from the login theme set on the realm.
The Device Authorization Grant uses the login theme set for the realm in the screen shown below.

- Device login failure screen (/realms/{realm}/device/status)
- Device login success screen (/realms/{realm}/device/status)

**Comment by ssilvert** [comment]
This looks like it would be a bug in server side code.  Moving to core team.

**Comment by mposolda** [comment]
I am adding to Backlog as not sure when Keycloak team has time to look at this. Anyone is welcome to investigate and eventually send PR with fixing this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details on how to contribute to Keycloak and send PR.
