### ISSUE TITLE
HTTP MITM Cookie Hijack

### ISSUE THREAD

**Issue by yhnbgf** [keycloak/keycloak#25723]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

I found a vulnerability in keycloak's login mechanism on HTTP, version 22.0.5. 

Although keycloak recommends HTTPS for deployment, some developers misconfigure HTTP, ,forget to enable HTTP, or are too lazy to get an SSL certificate. They do not understand its security implications and neglect HTTPS. During development, developers on HTTP are especially vulnerable to this attack. This is especially terrible as bad actors can disrupt development work.

### Version

22.0.5

### Expected behavior

Safe and secure login

### Actual behavior

An attacker is able to arp spoof, obtain a victim's cookie credentials, and impersonate victim login.

### How to Reproduce?

https://docs.google.com/presentation/d/1w-Ucfe_EFxU6isjjvOe5hIBKMxyWm0GH/edit?usp=sharing&ouid=107896507330633954059&rtpof=true&sd=true

### Anything else?

i have emailed keycloak security team, but have yet to obtain a reply. 

am extremely furious about the lack of care for security.

**Comment by abstractj** [comment]
@yhnbgf Hi Lucas, you received a response 7 days ago; please check your inbox as it addresses your concerns about security.

![Blurred_Screenshot](https://github.com/keycloak/keycloak/assets/21758/a144f91e-534d-4fa8-88ad-0f49c2b7fe67)

As already answered:

Thanks for your report. This is **not** a security vulnerability. Running Keycloak in development mode for production is not recommended. Developers must ensure that all traffic, uses HTTPS. This can be achieved by redirecting HTTP to HTTPS and implementing HSTS headers to secure against unencrypted communications. Even in development environments, the use of TLS certificates is recommended.

**Comment by mposolda** [comment]
Closing as it is clearly documented that using `HTTP` is not secure and it is intended only for development purposes and never for production.
