### ISSUE TITLE
Update Route53 HA guide to be compatible with ROSA and Openshift 4.14.x

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#25733]
### Description

The current [Deploy an AWS Route 53 loadbalancer](https://www.keycloak.org/high-availability/deploy-aws-route53-loadbalancer) guide was tested with ROSA and Openshift 4.13.x clusers. However, with Openshift 4.14.x clusters, the type of AWS LoadBalancer deployed has changed from a classic ELB, to a Network Load Balancer. Consequently,  the commands in this guide need to be updated to make use of `aws elbv2`.

The changes required have already been added to the keycloak-benchmark scripts, this now needs to be reflected in the documentation: https://github.com/keycloak/keycloak-benchmark/pull/650

**Comment by ahus1** [comment]
@ryanemerson - please create two more PR to backport this to 23 and 22. For this, pick the commit from the main branch. Thanks!
