### ISSUE TITLE
Document OCP version used to verify High availability guide

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#25734]
### Description

The current "High availability" documentation is based upon procedures that were tested with Openshift 4.13.x, however some of the AWS commands are now outdated for Openshift 4.14.x. I have created https://github.com/keycloak/keycloak/issues/25733 to address the need to update the AWS commands, but we should ensure that the tested Openshift version(s) are explicitly stated in the guides Prerequisite sections.

**Comment by ahus1** [comment]
Child issue complete.
