### ISSUE TITLE
Backchannel logout token is missing the "exp" claim

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#25753]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When using backchannel logout, the sent logout token does not contain the required `exp` claim.

I observed this while using a Quarkus-based application with having backchannel configured. Quarkus complains, when receiving the backchannel request:
```
Back channel logout request for the tenant Default received
Verification of the token issued to client shop has failed: No Expiration Time (exp) claim present.
Back channel logout token is invalid
```
So, Quarkus is properly implemented by following [OIDC Backchannel Logout spec, chapter 2.4](https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken), but Keycloak doesn't send the `exp` claim.

### Version

23.0.3

### Expected behavior

The logout token must contain the `exp` claim, as mentioned in the [OIDC Backchannel Logout spec, chapter 2.4](https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken)

### Actual behavior

The logout token does _NOT_ contain the `exp` claim.

Here's a dump of a current logout token payload:
```
{
  "iat": 1703156525,
  "jti": "a2836698-7660-44e8-a9f1-d27d8514b311",
  "iss": "http://localhost:8080/realms/bookshop",
  "aud": "shop",
  "sub": "a6df2d13-8e94-404b-addc-53e248afc95c",
  "typ": "Logout",
  "sid": "2b6eaf9b-990c-4733-a048-b8e8f28612b3",
  "events": {
    "http://schemas.openid.net/event/backchannel-logout": {}
  }
}
```

### How to Reproduce?

Configure any client with a proper backchannel logout url, login/logout with any user from Keycloak and observe/investigate the sent logout token.

**Comment by dasniko** [comment]
To be fair, this seems (only) to be the case since the latest version/iteration of the mentioned OIDC Backchannel Logout spec. of Dec 15th, 2023.
The used Quarkus version 3.6.3 already contains this requirement, thus the behavior was observed.

So, this is more an enhancement than a bug!
Hopefully you will implement it asap, so that we can use Keycloak backchannel logout with current versions of Quarkus.

**Comment by dasniko** [comment]
I also did a test with a Quarkus 3.5.0 based client app, which also fails with the same error as the 3.6.3 version!

**Comment by dasniko** [comment]
If my PR gets merged, I'd also vote for a backport of this fix to the current release branch!

**Comment by ahus1** [comment]
@dasniko - I've marked this issue for backporting to 23 and 22. You can help out with that as well when you create a PR for each of the release branches and cherry-pick the commit from the main branch. Feel free to ping me from the backport PRs and I'll have a look.

**Comment by dasniko** [comment]
Thanks @ahus1 for merging.
Backport PRs created with #25786 and #25787
