### ISSUE TITLE
idea 开发工具怎么debug源码呢

### ISSUE THREAD

**Issue by liuguangjie** [keycloak/keycloak#25768]
### Description

我尝试了几天都没成功，一直在查看源码打转，开发工具也不能debug，头发掉光了

**Comment by liuguangjie** [comment]
我用开发工具内部能正常启动，就是没法debug，打断点没反应 这些参数都试过了就是不生效  mvn quarkus:dev -DdebugHost=0.0.0.0 -Ddebug=5006

**Comment by jonkoops** [comment]
We only accept issue reports in English.

**Comment by liuguangjie** [comment]
> We only accept issue reports in English.
I have been trying for a few days but have not been successful. I have been checking the source code and the development tools cannot be debugged, and my hair has fallen out 
I can start the development tool normally internally, but I can't debug it. The breakpoint doesn't respond. I've tried these parameters, but they don't work. mvn quarks: dev - DdebugHost=0.0.0.0- Ddebug=5006
