### ISSUE TITLE
Keycloak Spring Security adapter with X-Forwarded-* headers

### ISSUE THREAD

**Issue by buiam** [keycloak/keycloak#25772]
### Description

Currently, Keycloak adapter doesn't consider X-Forwarded-* headers when constracting the redirect_uri inside the Location Response header, considering only the requestUrl inside the ServletRequest.

I would like the Keycloak adapter also to handle this kind of headers.

### Motivation

In my project I have an Nginx proxy ("https") between the Jetty application and the Keycloak server ("https"). The request urls reaching the application use the "http" protocol (not "https"), but have also the X-Forwarded-Proto = https.

The Jetty app is an old open-source project that doesn't handle "https" requests and even if a can add the http redirect to Keycloak server admin console, I have issues when other apps embed mine in an iframe (502 Error Code). My collegue thinks this happens due to _keycloak.js_ **checkSSO**.

Sure there could be other ways to handle this scenario. But shouldn't the Keyclaok adapter be taking into account headers, upon redirect generation?

### Details

This is the flow I followed through debug.
The **AbstractAuthenticationProcessingFilter.attemptAuthentication** method is what sets the redirect

![Screenshot from 2023-12-22 10-34-57](https://github.com/keycloak/keycloak/assets/112827875/d560552f-5293-4b1f-80ed-9210c7846276)

The in-depth flow:

![Screenshot from 2023-12-22 10-38-01](https://github.com/keycloak/keycloak/assets/112827875/e7ed5879-1a00-4296-8a52-d52ea5ee7c79)

![Screenshot from 2023-12-22 10-39-01](https://github.com/keycloak/keycloak/assets/112827875/c2dfa95d-22fb-45e9-9e3f-d7b71ed579bc)

The line where the redirect is set:

![Screenshot from 2023-12-22 10-39-43](https://github.com/keycloak/keycloak/assets/112827875/b02b6596-a327-494f-a01d-211b14cdb69f)

And its flow:

![Screenshot from 2023-12-22 10-40-09](https://github.com/keycloak/keycloak/assets/112827875/f7da5752-98ec-4499-a8bd-be1dea68c72b)

![Screenshot from 2023-12-22 10-40-20](https://github.com/keycloak/keycloak/assets/112827875/23e7a9b6-057f-48cb-bd9a-b36b3514129a)

![Screenshot from 2023-12-22 10-40-48](https://github.com/keycloak/keycloak/assets/112827875/e0a93174-30d4-400b-9228-677f1b6333ca)

Here we go inside the facade, constructed using the ServletRequest:

![Screenshot from 2023-12-22 10-41-17](https://github.com/keycloak/keycloak/assets/112827875/d97d6952-0d08-4327-b254-50c050f1a99c)

![Screenshot from 2023-12-22 10-41-48](https://github.com/keycloak/keycloak/assets/112827875/d94ad78b-b650-4cf3-8094-ab11ba62cf30)

Here the logic of HttpFacade.Request.getURI method:

![Screenshot from 2023-12-22 10-42-13](https://github.com/keycloak/keycloak/assets/112827875/327423cb-3282-46e2-9b76-eb8dbeb0ee83)

So you can see how only the requestUrl is taken into account when generating the redirect.

**Comment by stianst** [comment]
The Keycloak Spring adapter is deprecated, and will not receive any further feature or enhancements. I would suggest looking at Spring Security, which has built-in support for OAuth and OIDC.

The Keycloak Jetty adapter only supports Jetty 9.4, which is no longer available to the community since 2022, and for this reason we are no longer going to include the Jetty adapter from Keycloak 24 onwards.

**Comment by buiam** [comment]
I found a workaround, using Jetty _http-forwarded_ module.
If you start Jetty with the following command, it handles X-Forwarded headers regurarily:
`java $JAVA_OPTS -jar /usr/local/jetty/start.jar --add-to-start=http-forwarded`
