### ISSUE TITLE
X509 client certificate login label extends out of form

### ISSUE THREAD

**Issue by magnhas** [keycloak/keycloak#25770]
### Description

X509 client certificate login label extends out of form.

![Screenshot 2023-12-22 at 10 15 17](https://github.com/keycloak/keycloak/assets/60488810/515162d0-09b8-43ae-9118-a9bf6640038a)

### Motivation

Things should look nice.

### Details

Add something like 

```
label.pf-c-form__label.pf-c-form__label-text {
    overflow-wrap: break-word
}
```

to [login.css](themes/src/main/resources/theme/keycloak/login/resources/css/login.css).

**Comment by ahus1** [comment]
Once the PR is merged to main, your change will be included in the next major release of Keycloak which supposed to be Keycloak 24. 

If you want it to be included in the next patch release of KC23, create a PR against the KC23 release branch which cherry-picks this change from the main branch (after the original PR is merged).
