### ISSUE TITLE
User events: labels overlap content

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#25789]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

User events details have different labels overlapping the content, thus making it hard to understand the value.

### Version

22.0.5

### Expected behavior

Labels must not overlap the content

### Actual behavior

Labels are overlapping the content
![изображение](https://github.com/keycloak/keycloak/assets/1285898/7da5842c-a678-4ada-bcc4-58dd16bba4c3)

### How to Reproduce?

Enable saving of some user events, check their content after expanding

**Comment by jonkoops** [comment]
@lrozenblyum is this issue reproducible in the latest version of Keycloak, as mentioned in the issue template?

**Comment by lrozenblyum** [comment]
@jonkoops yes it's reproduced in **23.0.3** Keycloak (the latest at the moment) but less frequently than before.

For me here it's reproduced sometimes for the REFRESH_TOKEN event type
![изображение](https://github.com/keycloak/keycloak/assets/1285898/52eaa890-ed8a-44c8-9d5b-5fbb662f19de)

**Comment by jonkoops** [comment]
Thanks for verifying that, I will triage this issue so we can get back to it in the future.
