### ISSUE TITLE
Space in realm name breaks initial console uris

### ISSUE THREAD

**Issue by PSanetra** [keycloak/keycloak#25807]
### Area

dist/quarkus

### Describe the bug

Realm names can include spaces, but doing so will create a realm with broken console clients.

The console client uris (including the redirect uris) will contain the unencoded realm name, but they need to include the encoded realm name as the redirect uris will break otherwise.

### Version

23.0.3

### Expected behavior

console clients should be created with valid client uris.

### Actual behavior

The generated redirect uris need to be fixed manually to include the encoded realm name.

### How to Reproduce?

1. Create Realm called "Test Realm"
2. The `account` client has the redirect uri `/realms/Test Realm/account/*`
3. The `account-console` client has the redirect uri `/realms/Test Realm/account/*`
4. The `security-admin-console` client has the redirect uri `/admin/Test Realm/console/*`

**Comment by vmuzikar** [comment]
Thanks for the report! I was able to reproduce.

IIRC, we ran into this issue recently with the admin CLI client (CC @shawkins). However, this is related to the admin console. I wonder if we should possibly do some replacements of spaces for `%20` on the REST API level.

Re-assigning to the @keycloak/core for now.
