### ISSUE TITLE
Docs: server_admin/topics/authentication/x509.adoc

### ISSUE THREAD

**Issue by ketchup201** [keycloak/keycloak#25813]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Screen shot and directions don't sync up under "Adding X.509 client certificate authentication to browser flows".

File: server_admin/topics/authentication/x509.adoc

### Version

23.0.3

### Expected behavior

1. I expect the instructions and their accompanying screen shots to match
2. I also expect the screenshot for step 9 to have two screenshots: a 'before' and 'after' set of images that explain what the screen should look like after the user performs a 'Click and drag the 'X509/Validate Username Form' over the "Browser Forms" execution.". Does this mean the 'X509/Validate Username Form' should be **underneath** the 'X509 Browser forms' or should the 'X509/Validate Username Form' be above it, as part of the steps prior to the new step?

### Actual behavior

Under "Adding X.509 client certificate authentication to browser flows", Step 4 says "ENTER A NAME" without specifying what the name should be. This is OK, but:
- Subsequent screenshot shows "Copy of Browser"
- Screenshot after the first screenshot shows "X.509 Browser"
The two screenshots should both match the same name, and that the verbiage in step 4 says something to the effect of "(for example, X.509 Browser)" so that the name matches those in the screenshots.

Also, the instruction for step 9 is unclear what it means by "over" and "browser forms execution", since "browser forms" isn't on said screen, and "over" could mean "above" or "on".

**Comment by mposolda** [comment]
Thanks for the report, Your feedback is appreciated about the fact that Keycloak docs might not be clear enough for some scenarios. But I think Keycloak team won't likely have a time to look at this in the near future. Anyone is welcome to contribute the PR with the fix https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md .
