### ISSUE TITLE
In UserProfileContext.IDP_REVIEW, NPE on UserModel#getEmail because UserModelDelegate#delegate is null

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#25858]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

`IdpReviewProfileAuthenticator` instantiates a `UserModelDelegate` with a null delegate:

https://github.com/keycloak/keycloak/blob/a228b6c7c9ec7a54ee91bb547b42cc4097ae38e2/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java#L115-L115

Because of that, in a `UserProfileContext.IDP_REVIEW`, a `Validator` performing `UserModel#getEmail` will fail with a null pointer exception.

### Version

23.0.3

### Expected behavior

UserModel#getEmail should not fail

### Actual behavior

UserModel#getEmail produces an NPE

### How to Reproduce?

- Add a validator using UserModel#getEmail
- Trigger an IDP review

**Comment by reda-alaoui** [comment]
@pedroigor , I think this releates to `declarative user profile`.

**Comment by pedroigor** [comment]
@reda-alaoui Are you using a custom validator?

**Comment by reda-alaoui** [comment]
@pedroigor yes
