### ISSUE TITLE
Microsoft cert is expired in AADS, however SSO still works. We want to know why it works.

### ISSUE THREAD

**Issue by DREGALLA** [keycloak/keycloak#25889]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

https://faq.miniorange.com/knowledgebase/how-to-renew-upgrade-sp-certificate-in-the-saml-sso-plugin-with-keycloak-as-idp/
The above link suggests to replace the cert only when ‘Encrypt Assertion’ and ‘Client Signature Required’ is set ‘ON’
we don’t have these specific settings above under the SAML config menu in keycloak 6.0. Also the link mentioned where we can import an encryption key and signing key.
But, on Key-cloak version 6.0.0 packaged with AADS, the ‘Keys’ tab is not available under the Client >> AADS Menu
It seems that we are not enabling SAML assertion encryption by default on Key-cloak.
Is this the reason why SAML SSO continues working although the cert has expired?

Is this fixed in the keycloak version 22 ?

### Version

Keycloak 6.0

### Expected behavior

If the certificate expired SSO will not work.

### Actual behavior

Microsoft cert is expired in AADS, however SSO still works.

### How to Reproduce?

Microsoft cert is expired in IDP, however SSO keycloak still works. Is there any reason why it is working.

**Comment by jonkoops** [comment]
> Is this fixed in the keycloak version 22 ?

Please verify yourself if this issue is fixed or not, we simply do not have time time to do so for you, as we have an enormous backlog. If you are running Keycloak 6 you should really be upgrading to the latest version as soon as possible, as it is full of security holes.
