### ISSUE TITLE
起動しない

### ISSUE THREAD

**Issue by site-lab** [keycloak/keycloak#25888]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

仮想マシン：vagrant
OS：AlmaLinux8
Java：openjdk17

[vagrant@localhost keycloak23]$ sudo  bin/kc.sh start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2024-01-04 05:25:18,193 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

ERROR: Failed to run 'build' command.
ERROR: /opt/keycloak23/lib/quarkus/build-system.properties
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

そもそも起動しない。

OSはインストールしてJavaだけインストールをした状態です。

### Version

23

### Expected behavior

何も出来ない

### Actual behavior

[vagrant@localhost keycloak23]$ sudo  bin/kc.sh start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2024-01-04 05:25:18,193 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

ERROR: Failed to run 'build' command.
ERROR: /opt/keycloak23/lib/quarkus/build-system.properties
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

### How to Reproduce?

 sudo  bin/kc.sh start-dev

**Comment by jonkoops** [comment]
This is not enough information to reproduce an issue. If you want to report an issue, please do so in English with detailed steps on how to reproduce it.
