### ISSUE TITLE
external requests to include the well-established private subnet 100.64/10

### ISSUE THREAD

**Issue by korenlev** [keycloak/keycloak#25881]
### Description

external requests:

Keycloak can run out of the box without SSL so long as you stick to private IP addresses like localhost, 127.0.0.1, 10.0.x.x, 192.168.x.x, and 172..16.x.x. If you don’t have SSL/HTTPS configured on the server or you try to access Keycloak over HTTP from a non-private IP adress you will get an error.

on cloud environments like aws, the usage of private range 100.64/10 has been popular since 2018 : 
https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/

it will be good if that range is added to external requests option, treated as private, without the need for ssl.

**Comment by korenlev** [comment]
https://github.com/keycloak/keycloak/discussions/15400

**Comment by stianst** [comment]
I'm going to reject this as TLS should really be used in anything beyond local development.
