### ISSUE TITLE
Optimize handling of terms and conditions during registration

### ISSUE THREAD

**Issue by Guite** [keycloak/keycloak#25891]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After having updated to Keycloak 22 we tried the [newly introduced feature](https://github.com/keycloak/keycloak/pull/25506) for including terms and conditions directly into the registration page. Unfortunately this feature does not integrate well with how required actions work in general and on other places (for details see below).

### Version

22.0.5

### Expected behavior

After a new user accepted TaC on the registration page, the system should:

- Properly persist the user attribute with the timestamp.
- Not display the subsequent second page showing TaC (again).

### Actual behavior

During testing, we detected two possible deficits:

- It seems that the user attribute with the timestamp is not set automatically. See also [this discussion](https://github.com/keycloak/keycloak/discussions/23653) which might be related to that.
- The separate page for terms and conditions is still shown after the user submitted the first page. We even tried adding a hidden form field carrying the attribute, but this workaround did not work out.

### How to Reproduce?

1. Setup registration flow like [described in the manual](https://www.keycloak.org/docs/latest/server_admin/index.html#proc-requiring-tac-agreement-at-registration_server_administration_guide)
2. Also configure TaC as a required action.
3. Click through registration process.

### Anything else?

For the moment, we decided to disable the direct inclusion of TaC again in favour of the separate page.

**Comment by jonkoops** [comment]
Please confirm this issue is still present in the latest version of Keycloak.

**Comment by cuberinooo** [comment]
I tested this on Version 23.0.3 and got the same issue. User Attribute **terms_and_conditions** is not set after user accepts the TaC on the registration page. After sending the registration form I still need to accept the TaC again. 
Also on first login user needs to accept the ToC again.
