### ISSUE TITLE
Admin UI: Show realm display name on welcome page

### ISSUE THREAD

**Issue by Jamstah** [keycloak/keycloak#25897]
The welcome page of the admin console uses the realm id, I think it should use the display name (if available) and fall back to the realm id.

In this example, the id is `cloudpak` and the display name is "Cloud Pak"

The login page does this right and uses the display name where available.

![image](https://github.com/keycloak/keycloak/assets/298807/891c6794-fcb1-4e69-8466-600ff79c13a3)

**Comment by jonkoops** [comment]
Yeah, this seems like a nice enhancement, I will add this to the backlog and mark it as 'help wanted'

**Comment by malavmevada** [comment]
Hii @jonkoops , I have been working on keycloak since 1 month. I think I'm able to solve this issue. If possible please assign this issue to me.

**Comment by jonkoops** [comment]
I'll assign this to you @dipeshsingh253, thanks! @malavmevada if you are looking to pick up an issue there are [others that can be picked up](https://github.com/keycloak/keycloak/labels/help%20wanted).

**Comment by dipeshsingh253** [comment]
Thanks @jonkoops for this opportunity !!!

**Comment by jonkoops** [comment]
No problem, do let me know if you need any assistance :smile:

**Comment by dipeshsingh253** [comment]
Hi @jonkoops , I am following ![this](https://github.com/keycloak/keycloak/blob/main/docs/building.md) guide to set development environment in my local, though it is taking a lot of time(I left it for somewhere around 2-3 hrs and when I came back it was still running) to execute ```./mvnw clean install ```.

**Comment by jonkoops** [comment]
It's likely that you need to pass `-DskipTest`, otherwise the tests will also run, which can take extremely long if you are running everything.

To get started with development on the Administration Console you won't need to build Keycloak per-se, instead you can opt-to use a nightly build of Keycloak and develop against that. You can find information on how to to that [in the README](https://github.com/keycloak/keycloak/tree/main/js/apps/admin-ui#readme) of the Administration Console.

**Comment by dipeshsingh253** [comment]
Hi @jonkoops , thanks for your assistance, now I can run keycloak-server and admin-ui locally. However, I would love to share a minor error I faced while setting up the local environment for Keycloak. First I tried to follow [these instructions](https://github.com/keycloak/keycloak/tree/main/js/apps/admin-ui#readme) in Windows and I faced this error while executing the start script of keycloak-server. 

![image](https://github.com/keycloak/keycloak/assets/84814627/352ec329-d40b-4360-8d80-ff37c2b34d7b)

But it worked smoothly when I followed the same steps on a Linux device. I will raise a PR by the end of this week for this as I currently don't have access to my Linux device. but I have already located the file where I need to make changes so it won't take much time.

**Comment by dipeshsingh253** [comment]
Hi @jonkoops , I have contributed to other projects as well, and there I had to fork it and work on it(it was mentioned in their contributor's guide), but [here](https://github.com/dipeshsingh253/keycloak/blob/main/CONTRIBUTING.md) I can not see those options and instead of ``pull`` it says to use ``rebase``.  Just some doubt so I can start working and raise the PR, 

1. Do we have to work directly on the main branch as there are no mentions for the branch in the guide and create PR for it only?
2. Do I even need to fork the repo to work on issues, or can we directly clone and start working on the original repo as there is no mention of forking and creating a specific branch related to working issues in the guide?
3. Do we have any community on Slack or Discord etc?

Thanks !!!

**Comment by jonkoops** [comment]
Hi @dipeshsingh253, we do assume that you fork our repository. I think the guide simply assumes that the user is familiar with the [GitHub contribution guide](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project). I agree that our documentation is lacking here, perhaps you could open a PR to add this link to the contribution guide?

1. Ideally you create a new branch on your fork under a name that matches the functionality that you are trying to implement (e.g `show-name-welcome`) and contribute that as a PR. Using the `main` branch from your fork will prevent maintainers from editing it, which complicates contribution.
2. Like mentioned before, I recommend forking the repository, you will not be able to push to our repo, as you do not have the rights to push to it.
3. You can find all our communication channels on the [Community page](https://www.keycloak.org/community), but I would recommend targeted communication like this remain in GitHub, where we are most active.

If you feel like anything is missing from the contribution guide, feel free to open a PR to improve it, and I will make sure to get you a review.

**Comment by dipeshsingh253** [comment]
Hi @jonkoops , Sorry for the delay I just got my Linux device yesterday. I noticed that we are using the URL to get realmName to display on the welcome page, here [this file](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/dashboard/Dashboard.tsx), so I am not sure how can I get the displayName on welcome-page, we can see the displayName on login page for realm : 
![image](https://github.com/keycloak/keycloak/assets/84814627/fb8ea273-7218-4f44-b5bf-e721b600c26f)

I could check the file for the login page to get the display name, but I was not able to locate this file yet. If you have the idea can you help me where should I look for it?

**Comment by agagancarczyk** [comment]
hi @dipeshsingh253 We have recently implemented this in the welcome tab. Please take a look at this code https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/dashboard/Dashboard.tsx#L133 . I believe this is what you want to use as well.

**Comment by dipeshsingh253** [comment]
Hi @agagancarczyk , thanks I was exactly looking for this. But there is a bug and I am sure it should not be there somehow I am not able to display the realmName when the displayName for that realm is not available. 

![image](https://github.com/keycloak/keycloak/assets/84814627/e402314a-a5c3-4e42-adc2-082229520c04)
![image](https://github.com/keycloak/keycloak/assets/84814627/e4f5fe80-3b8c-440f-9f38-24597d87d824)

I also verified the same scenario for the default dashboard of MasterRealm by removing the displayName for it. 
![image](https://github.com/keycloak/keycloak/assets/84814627/ddb6be37-8046-45f0-9e2b-626f3591c263)

**Comment by jonkoops** [comment]
Try using `||` instead of `??`, it might be that `displayName` is an empty string. Using the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) means that empty strings are also included.

**Comment by dipeshsingh253** [comment]
Hi @jonkoops, I have created the PR. Please review it whenever you have time and let me know if there are any modifications needed.

Thanks for the opportunity !!!
