### ISSUE TITLE
Keycloak HA Guide uses token for cross-site setup that expires

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#25909]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The [command in the docs](https://www.keycloak.org/high-availability/deploy-infinispan-kubernetes-crossdc) creates a short-lived token which will expire within one hour by default: 

```
kubectl create token -n keycloak xsite-sa
``` 

Once the token expires, the Operator won't be able to set up the xsite connection any more. 

### Version

main

### Expected behavior

The docs should use a token that doesn't expire

### Actual behavior

The token expires.

### How to Reproduce?

Retrieve the token and put it into the site `jwt.io` to analyze it.

### Anything else?

See https://github.com/keycloak/keycloak-benchmark/issues/663

**Comment by ahus1** [comment]
@pruivo - please create two additional PRs that backport this to 23 and 22 with the commit that has now been merged to the main branch. Thanks!

**Comment by pruivo** [comment]
@ahus1 done :+1: Thanks!
