### ISSUE TITLE
Allow increasing wait time on each failure after the max number of failures is reached

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#25917]
The server will only increase the wait time on multiples of the value set to `Max Login Failures`:

`Wait Increment`  | `Failure Count` | `Max Login Failures` | `Effective Wait Time`
-- | -- | -- | --
30 | 1 | 5 | 6
30 | 2 | 5 | 12
30 | 3 | 5 | 18
30 | 4 | 5 | 24
**30** | **5** | 5 | **30**
30 | 6 | 5 | 36
30 | 7 | 5 | 42
30 | 8 | 5 | 48
30 | 9 | 5 | 54
**30** | **10** | 5 | **60**

While this behavior is valid and expected by some use cases, others might want to increase the wait time linearly on each authentication failure attempt (after the user is no longer locked).

`Wait Increment`  | `Failure Count` | `Max Login Failures` | `Effective Wait Time`
-- | -- | -- | --
30 | 1 | 5 | -90
30 | 2 | 5 | -60
30 | 3 | 5 | -30
30 | 4 | 5 | 0
**30** | 5 | 5 | **30**
**30** | **6** | 5 | **60**
30 | 7 | 5 | 90
30 | 8 | 5 | 120
30 | 9 | 5 | 150
30 | 10 | 5 | 180

A WIP is here https://github.com/keycloak/keycloak/pull/25361.

**Comment by pedroigor** [comment]
@gilvansfilho Could you please review and see if it is aligned with your proposal?

**Comment by gilvansfilho** [comment]
That's right. I believe we can provide the option for the user to choose the desired behavior when configuring brute force where the default will be the current one.

**Comment by gilvansfilho** [comment]
I will work on that.

**Comment by gilvansfilho** [comment]
Waiting finish that https://github.com/keycloak/keycloak/pull/26208 to avoid conflicts...
