### ISSUE TITLE
LDAP federation reports "Creating new LDAP Store..." on every login

### ISSUE THREAD

**Issue by darius-m** [keycloak/keycloak#25912]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

After upgrading to version 23.0.3, on every user login Keyecloak logs an entry similar to the following (both are from the same server):
```
INFO  [org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (executor-thread-44) Creating new LDAP Store for the LDAP storage provider: 'ldap', LDAP Configuration: {fullSyncPeriod=[-1], pagination=[false], startTls=[false], connectionPooling=[true], usersDn=[ou=people,dc=test,dc=keycloak,dc=local], cachePolicy=[DEFAULT], useKerberosForPasswordAuthentication=[false], importEnabled=[true], enabled=[true], usernameLDAPAttribute=[uid], changedSyncPeriod=[-1], bindDn=[uid=keycloak,dc=test,dc=keycloak,dc=local], vendor=[rhds], uuidLDAPAttribute=[uid], connectionUrl=[ldap://quarkus-kc-cluster-1-ldap], allowKerberosAuthentication=[false], syncRegistrations=[true], authType=[simple], useTruststoreSpi=[ldapsOnly], usePasswordModifyExtendedOp=[false], trustEmail=[true], userObjectClasses=[inetOrgPerson, organizationalPerson], rdnLDAPAttribute=[uid], editMode=[READ_ONLY], validatePasswordPolicy=[false]}, binaryAttributes: []
INFO  [org.keycloak.storage.ldap.LDAPIdentityStoreRegistry] (executor-thread-44) Creating new LDAP Store for the LDAP storage provider: 'ldap', LDAP Configuration: {fullSyncPeriod=[-1], pagination=[false], startTls=[false], connectionPooling=[true], usersDn=[ou=people,dc=test,dc=keycloak,dc=local], cachePolicy=[DEFAULT], useKerberosForPasswordAuthentication=[false], importEnabled=[true], enabled=[true], usernameLDAPAttribute=[uid], changedSyncPeriod=[-1], bindDn=[uid=keycloak,dc=test,dc=keycloak,dc=local], vendor=[rhds], uuidLDAPAttribute=[uid], connectionUrl=[ldap://quarkus-kc-cluster-1-ldap], allowKerberosAuthentication=[false], syncRegistrations=[true], authType=[simple], useTruststoreSpi=[ldapsOnly], usePasswordModifyExtendedOp=[false], trustEmail=[true], userObjectClasses=[inetOrgPerson, organizationalPerson], rdnLDAPAttribute=[uid], editMode=[READ_ONLY], validatePasswordPolicy=[false]}, binaryAttributes: []
```

As far as I can tell, in previous versions (up to 21), this message was logged only once.

### Version

23.0.3

### Expected behavior

The message is logged only once, when the configuration is set up the first time.

### Actual behavior

The message is generated on every user login, greatly polluting the log output.

### How to Reproduce?

Create a LDAP federation and monitor the log after every user login.

### Anything else?

If other configuration details (e.g., Infinispan configurations) are relevant, I could link them (they are public), but from what I can tell from [the code](https://github.com/keycloak/keycloak/blob/904e688400cbb4470b15d88ef9f65f03ee1e7c71/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPIdentityStoreRegistry.java#L38), the cache used for lookup is local to Keycloak.

**Comment by ehwhw0w** [comment]
Upgraded from 20.0.5 to 22.0.5 last week. I can tell we're observing the same issue.

**Comment by sippnex** [comment]
We were facing the same issue and i think we could solve it by changing the property "Use Truststore SPI" in the config of the LDAP user federation (screenshot). The value was "ldapsOnly", but this value apparently no longer exist in Keycloak 22/23. I think it was removed by commit b8149d6.

So we changed the value to "Always" and the logging was fine after that.

Maybe the equals-Method of the LDAPConfig does not work with the incorrect value "ldapsOnly" and therefore the LDAP Store cache is not working properly.

**Comment by sguilhen** [comment]
I was able to confirm the bug - it was introduced by https://github.com/keycloak/keycloak/commit/c092c76ae86313ae7b16777590a847c19dfb26c2 - the change in `LDAPConfig.getUseTruststoreSpi` is changing the cached LDAPConfig object, so when the config is read from the DB in subsequent calls the objects don't match and Keycloak ends up logging the creation of a new LDAPObject again.

I'm preparing a fix that adds a migration step so that existing `ldapsOnly` config values are migrated to `always`.

**Comment by ahus1** [comment]
@sguilhen - I've added the backport 23 label for this issue as well, as I suppose everything for KC22 should also be backported to KC23 while we keep KC23 alive. Let me know if you think otherwise.

**Comment by sguilhen** [comment]
@ahus1 I agree with backporting it to 23 as well. Will provide the PRs shortly.

**Comment by oculos** [comment]
I am facing this issue after I enabled kerberos on the ldap provider.

**Comment by ahus1** [comment]
@oculos - this issue is considerd fixed stated in released described in the labels of the issue (see for example Keycloak 24.0.0). If you see this problem in a later release, open a new bug issue, describe your version and problem, and then reference this issue.
