### ISSUE TITLE
Client ID Policy Condition

### ISSUE THREAD

**Issue by 1-alex98** [keycloak/keycloak#25954]
### Description

Apply a Client Policy to all clients with in a list of client ids.

### Motivation

More fine granted controll on what client's a policy is applied to.

### Details

There is discussion to this here. https://github.com/keycloak/keycloak/pull/8236#issuecomment-1241700497
@stianst likes the idea and wishes for a seperate PR with that feature.

My aim in general is to realise wildcards for subdomains as described in 
https://github.com/keycloak/keycloak/discussions/9278

But I want to start small.

**Comment by mposolda** [comment]
I am closing as Client-ID condition can be replaced with `Client Role` condition and "marker role" approach. This will be also documented more explicitly in the Keycloak 24 documentation: https://github.com/keycloak/keycloak/pull/27339 . Feel free to re-open if you think that client-id condition still makes sense to you, but TBH it can be nice to avoid additional condition to implement/maintain if we can already achieved the functionality with different approach, which has much better scalability (as client-id condition won't scale well if 1000 client IDs need to be explicitly listed in the configuration).
