### ISSUE TITLE
Native SQL Schema names broken on MySQL

### ISSUE THREAD

**Issue by jcputney** [keycloak/keycloak#25961]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When trying to delete a Role while running on MySQL, an error is thrown complaining about invalid SQL syntax, because the schema name is being wrapped in double quotes.

### Version

23.0.3

### Expected behavior

Should be able to delete realm without throwing a SQL error

### Actual behavior

An error is thrown and the Role is not deleted.

### How to Reproduce?

Run Keycloak on MySQL/MariaDB

### Anything else?

The bug was introduced in this commit: https://github.com/keycloak/keycloak/commit/dc9970f578144557d75e6e1e21f57dcdf6c70f38

**Comment by rmartinc** [comment]
Moving to storage. :smiley:

**Comment by ahus1** [comment]
To reproduce this locally, can you provide the Schema name you're using? Does it contain a dash (`-`)?

**Comment by jcputney** [comment]
@ahus1 I'm just using the schema name `keycloak`, nothing special

**Comment by jcputney** [comment]
@ahus1 looking at the relevant code, I don't think it has anything to do with what the schema name is, it looks like it's just wrapping the schema name in incorrect characters for MySQL. It is specifically happening in `model/jpa/src/main/java/org/keycloak/connections/jpa/util/JpaUtils.java` in the `getTableNameForNativeQuery` method, because you can't wrap the schema name in double quotes in MySQL. I believe it would need to be backticks instead.
