### ISSUE TITLE
Force reauthentication is ignored during identity brokering when mapping between OIDC and SAML protocols

### ISSUE THREAD

**Issue by phamann** [keycloak/keycloak#25980]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Summary
Keycloak doesn't correctly map OIDC `prompt=login` to a SAML `ForceAuthN` during identity brokering.

### Detail
The OIDC specification states that when a server receives a `prompt=login` authentication request parameter the server:

> The Authorization Server SHOULD prompt the End-User for reauthentication.

Therefore, when a client initiates an OIDC authentication request with the protocol `prompt=login` parameter and the request results in a SAML identity broker redirection (for instance, using the Identity Provider Redirector), Keycloak should map the OIDC `prompt=login` to a SAML `ForceAuthN` XML attribute. This ensures that the external SAML provider also prompts the user for reauthentication regardless of session state. 

Currently, the `SAMLIdentityProvider` logic will ignore any dynamic state in the request context, such as the OIDC parameter, and instead reads from the Identity Provider configuration value to build the SAML request using `ForceAuthN`. Therefore, `ForceAuthN` will only be sent if the IdP has been permanently configured to do so, which makes it hard for clients to conditionally opt-in to the behaviour.

This is a common scenario for step-up authentication flows when an OIDC client needs to ensure that the user is reauthenticated regardless of their session state. 

### Fix
Refactor the logic in the `SAMLIdentityProvider#performLogin()` method to conditionally override the IdP `forceAuthN` value based on the authentication session state and whether `prompt=login` was passed.

### More detail
Code flow for the IdentityProviderAuthenticator, If an IdP is found, it does a redirect here:
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java#L86

This creates a URL which is created to send the request to the RealmsResource-> IdentityBrokerService->`performLogin` method:
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/services/Urls.java#L56

That service is responsible for loading the IdentityProvider (e.g. SAMLIdentityProvider) and calling the `performLogin` method to create the redirect:
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java#L363

The SAMLIdentityProvider creates the SAML2 request, specifically the ability to use `ForceAuthn` based on the Config, which is associated with the identity provider, rather than a transient value which can be passed.
https://github.com/keycloak/keycloak/blob/5c86abbc32a7425b7f465e6d51806fa8650a231a/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java#L164

### Note
As this is a simple fix, I am raising this issue purely as a pointer to reference in the commit and PR and I will be submitting a Pr to fix shortly.

### Version

23.0.3

### Expected behavior

When a client sends requests an OIDC authentication request with the protocol `prompt=login` parameter and the request results in a SAML identity broker redirection, Keycloak should map the OIDC `prompt=login` to a SAML `ForceAuthN` attribute.

### Actual behavior

Keycloak ignores the `prompt=login` parameter and generates a SAML request without `ForceAuthN`.

### How to Reproduce?

- Configure a SAML IdP with `ForceAuthN` set to `false` and associate with a user
- Configure an authentication flow with the "Identity Provider Redirector"
- Configure an OIDC client and bind to authentication flow
- Send OIDC auth request with `prompt=login`
- Get redirected to external SAML IdP and note lack of `ForceAuthN` in the SAML request XML

**Comment by sventorben** [comment]
Sorry for being late at the party, but i came across this issue while discussing a PR in for one of my Keycloak extensions: https://github.com/sventorben/keycloak-home-idp-discovery/pull/312#issuecomment-1912243070

I think the same problem exists when mapping the other way around (from SAML to OIDC). The method `createAuthorizationUrl` in `AbstractOAuth2IdentityProvider` does not check if reauthentication is required. It should do so and enforce `prompt=login`. In addition, the `OIDCIdentityProvider` should enforce `max_age=0` in `createAuthorizationUrl` method. It should also set the client note `AUTH_TIME_BROKER` on the authentication session when reauthentication is required.

Any thoughts?
