### ISSUE TITLE
Authenticated users are able to delete their passwords via a DELETE request to a user's credential ID endpoint

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26002]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

Authenticated users are able to delete their passwords via a DELETE request to a user's credential ID endpoint. This is despite the user's password being marked as non-removable by a boolean. Upon this DELETE request being processed, a user will have their password deleted, preventing this user from logging in.

### Version

<= 23.0.4

### Expected behavior

Authenticated users should not be able to delete their passwords via DELETE request.

### Actual behavior

Authenticated users are able to delete their passwords via DELETE request.

### How to Reproduce?

A user must obtain their credentials ID via intercepting a GET request made to the credential endpoint. The password credential is located under userCredentialMetadatas as id. See
A DELETE request can then be sent to the credentials ID endpoint. This request will remove the password from the user account.
A subsequent request to the credential endpoint will verify that the password credential no longer exists.

### Anything else?

== Additional Information

Issue reference: F-11 Users Can Delete Their Password

**Comment by rmartinc** [comment]
@abstractj Is this something different to #25220?
