### ISSUE TITLE
kc.sh: Broken parameter pass-through in kc.sh via docker image

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26001]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

A security weakness exists in the Keycloak Docker image, version 20.0.1-0, related to the handling of special characters. Specifically, the kc.sh entry point script fails to handle ampersand ('&') characters within passwords.

The issue was discovered during the deployment of a standard Keycloak container as per the instructions provided on the official Keycloak server documentation (https://www.keycloak.org/server/containers#_running_a_standard_keycloak_container). It was observed that when executing the command to run the Docker container with a database password containing an ampersand character, the script kc.sh generated an error.

### Version

<= 20.0.1

### Expected behavior

Properly handle ampersands on passwords

### Actual behavior

Not properly handling ampersands on passwords.

### How to Reproduce?

1. Execute the following command:
```
$ docker run --rm quay.io/keycloak/keycloak:20.0.1-0 "start" "--db-password=o_f?SpNJVM]3+&%Z"
```

2. Observe the error output:
```
/opt/keycloak/bin/kc.sh: line 111: fg: no job control
```

**Comment by vmuzikar** [comment]
@abstractj Since this was fixed in Keycloak 23, does it make sense to close this?

**Comment by abstractj** [comment]
> @abstractj Since this was fixed in Keycloak 23, does it make sense to close this?

@vmuzikar before submitting it, I was trying to find the respective issue, but I was unable to find any. Could you please link the issue here, so we can close?

**Comment by vmuzikar** [comment]
@abstractj Please check #22337 (posted by @shawkins above) to see if that's is sufficient. :) Or do you mean an issue specific to this weakness?

**Comment by abstractj** [comment]
@vmuzikar thank you! Closing it.
