### ISSUE TITLE
Keycloak22 JakartaEE upgraded version jars still refers javax package

### ISSUE THREAD

**Issue by purushothgithub** [keycloak/keycloak#26013]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/jee

### Describe the bug

As per Keycloak update, Keycloak 22 is upgraded to JakartaEE. But still keycloak-tomcat-adapter-22-0.0.jar refers javax.servlet.http.HttpServletResponse.Please suggest which version keycloak is completely upgraded to JakarataEE.

### Version

23

### Expected behavior

We are upgrading our project to JakartaEE. So we are upgrading the Keycloak jars also JakartaEE supported version. We have used keycloak-tomcat-adapter-22-0.0.jar, It shouldn't refer javax.

### Actual behavior

We are upgrading our project to JakartaEE. So we are upgrading the Keycloak jars also JakartaEE supported version. We have used keycloak-tomcat-adapter-22-0.0.jar, but it still refers javax package which is not supported in JakarataEE.

### How to Reproduce?

Upgrading your project to JakartaEE. Add keycloak-tomcat-adapter-22-0.0.jar to support JakartaEE, but it still refers javax package which is not supported in JakarataEE. So it is failing to start the project.

**Comment by stianst** [comment]
The Keycloak Tomcat adapter is deprecated and won't be updated for JakartaEE
