### ISSUE TITLE
Duplicate tooltip/label for refresh button on device activity page

### ISSUE THREAD

**Issue by ReneZeidler** [keycloak/keycloak#26032]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

In the account console v3, the refresh button on the `Account security` -> `Device activity` page has an unnecessary tooltip that exactly matches the label of the button.

### Version

nightly

### Expected behavior

The tooltip should either display a more verbose explanation of the button or not be displayed at all.

### Actual behavior

![image](https://github.com/keycloak/keycloak/assets/5558742/e2ad0b8c-cd90-4f37-aa18-1564e0542879)

### How to Reproduce?

Open the account console v3 (enabled by default in nightly), navigate to `Account security` -> `Device activity`, and mouse over or tab to the "Refresh the page" button.

### Anything else?

Account console v2 uses the translation key `refresh` for the label and `refreshPage` for the tooltip:
https://github.com/keycloak/keycloak/blob/55d0a32b09a4e2d32f689c7b8ed0b864ca812854/themes/src/main/resources/theme/keycloak.v2/account/src/app/content/device-activity-page/DeviceActivityPage.tsx#L228-L238

Account console v3 uses `refreshPage` for both:
https://github.com/keycloak/keycloak/blob/55d0a32b09a4e2d32f689c7b8ed0b864ca812854/js/apps/account-ui/src/account-security/DeviceActivity.tsx#L118-L128

Using the shorter "Refresh" for the label probably makes sense, but the translation key would have to be copied from v2 to v3 (including localizations).

**Comment by jonkoops** [comment]
We won't be doing work on the Account Console v2 any longer as it will be deprecated in the next release. Closing this issue.

**Comment by ReneZeidler** [comment]
> We won't be doing work on the Account Console v2 any longer as it will be deprecated in the next release. Closing this issue.

The issue affects the Account Console v3. I included a reference to the Account Console v2 to show that it didn't have this issue.

**Comment by jonkoops** [comment]
Feel free to submit a PR to remove this tooltip :+1:
