### ISSUE TITLE
Configure OTP Form regenerates Secret on reload

### ISSUE THREAD

**Issue by dominiktopp** [keycloak/keycloak#26052]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

OTP secret is regenerated on every reload of configure otp page.

When configuring an otp device the user scans the QR code and enters the code from the app and an optional device label.
If the scan of the QR code is successful but the user enters a wrong code and clicks save, the page reloads, displays an error and shows a new QR code.
So the user has to re-scan the QR code and try again. Just using the code from the app without a re-scan results in an invalid otp error.
This happens on every page reload (F5) and is very unintuitive. That is why I consider it to be a bug instead of a feature request or an enhancement.

### Version

23.0.4

### Expected behavior

The secret is only generated once and does not change between page loads.

### Actual behavior

OTP secret is regenerated on every reload of configure otp page.

### How to Reproduce?

1. Open configure OTP page
2. Scan the QR code
3. enter a wrong code and click save
4. enter the code from the app and click save again

### Anything else?

Maybe we can generate the totpSecret, store it e.g. as an authNote and pass it to the constructor of TotpBean (has to be extended) in https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/forms/login/freemarker/FreeMarkerLoginFormsProvider.java#L236?

**Comment by lexcao** [comment]
What about only generating a new secret if there is not `totpSecret` in the `formData`

```
this.totpSecret = Optional.ofNullable(formData.getFirst("totpSecret")).orElse(HmacOTP.generateSecret(20));
```

**Comment by dominiktopp** [comment]
In this case UpdateTotp would have to copy the fromData from the request to the form.
When using authNote it could be handled just in FreeMarkerLoginFormsProvider and TotpBean.
But it's just an idea. Unfortunately I don't have the time to create a pull request.

**Comment by lexcao** [comment]
@dominiktopp 
Thanks, need Keycloak to check.
Maybe this is by design.

**Comment by dominiktopp** [comment]
If it's by design I would be very interested in the reason for generation new secrets.
We have some users complaining about not being able to setup new otp devices after they made a typo entering the code from their app. But until now we had no case where the scan of the qr code failed and the app generated wrong totps.

**Comment by graziang** [comment]
Hi @dominiktopp, I don't see any security reasons to regenerate the QR code every time.
To improve the user experience I think it's better to avoid regenerating the QR at least after entering a wrong OTP.
