### ISSUE TITLE
Attempting to update settings for realm with "dots" in the name fails due to client side validation

### ISSUE THREAD

**Issue by sfitts** [keycloak/keycloak#26059]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

While it is possible to create a realm with "dots" in the name (e.g. "my.site.com"), attempts to update the settings on the "General" tab of the "realm settings" are rejected with the error "Realm name can't contain special characters".  Editing settings on the other tabs (such as "theme") works just fine, it is only the "General" tab where the name check is being performed by the client.

Since the check was removed from the creation screen in https://github.com/keycloak/keycloak/issues/23930, I assume it should also be removed from this part of the UI (for all of the same reasons).

### Version

23.0.3

### Expected behavior

It is possible to set a value on the "General" tab of the "Realm settings" for a realm with dots in its name.  For example, it should be possible to set the "Display Name" for such a realm.

### Actual behavior

Any attempt to update these values receives an error message from the client as soon as you press "Save" (the client does not submit the update request to the server, it simply rejects it).

### How to Reproduce?

1) Using the Admin UI, create a realm called "my.test.realm".
1) Click on the "Realm Settings" on the right side of the admin UI for this realm.
1) Set the "Display Name" field to "Test" and click "Save"

At this point you will get red text below the name field which says "Realm name can't contain special characters"

**Comment by ssilvert** [comment]
I have verified this bug.

The dot should be allowed, so just need to adjust client-side validation.

**Comment by sfitts** [comment]
I see that this has been tagged for release in `24.x`, is there any chance it could be included in a `23.x` patch release?
