### ISSUE TITLE
Various Localization tab issues

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#26060]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

@agagancarczyk I'm going to describe several problems I found in the new Localization tab.  You can fix them all in one PR or break them out however you choose.  If you break them out, just create new issues so there is one issue per PR.

### Overall
On the `Locales` subtab, the choices for Default locale includes `root`.  There should not be a language selection for `root`.  This also appears in the dropdown in `Realm overrides` subtab and when searching in the `Effective message bundles` subtab.

### Realm overrides subtab
- The help text for the subtab does not tell the user what "realm override" means.  I suggest we get rid of the help icon and add some plain text as a heading above the toolbar.  It should say something like, "Realm overrides allow you to specify translations that will take effect for the entire realm.  These translations will override any translation specified by a theme."
- The button called `Add message bundle` should be called `Add translation`.  This was wrong in the old version as well.  A message bundle is a collection of all key/value pairs for a language.  Here the user is only adding a single translation to the bundle.
- The empty state should say `No translations` and `Add a translation to get started.`
- The text in the search bar should say, "Search for translation".
- The way edit and remove is implemented is inconsistent with the rest of the application.  I actually like the way it is implemented though so I'm not opposed to keeping it.  The only thing is that the kabab menu immediately brings up the confirmation dialog when I was expecting to see a menu.  I suggest changing the kebab menu to a trashcan icon.  If you are going to use the pencil, might as well use the trashcan.

### Effective message bundles subtab
- We need a heading for this tab as well.  It needs to describe what an effective message bundle is.  I suggest text such as, "An effective message bundle is the set of translations for a given language, theme, and theme type.  It also takes into account any realm overrides, which will take precedence."  Suggest we remove the help icon.
- In the search, Theme, Theme Type, and Language should be required fields.  Maybe the simplest way to deal with this is for each of these values to have a reasonable default.  Language would have the default language as the default selection.  The others could just default to the first value in the dropdown.
- In the search, `Theme` and `Theme Type` are backwards.  The dropdown for `Theme` is showing the values for `Theme Type`, and vice versa.
- We are not supporting the `common` theme with respect to message bundles.  So `common` should not show up in the dropdown.
- `Has words` only searches the values.  It would be nice if it were also searching the keys.  That way if I know the key I am looking for I can find it quickly.
- In the search dialog, the tab key closes the dialog.  Instead, I should be able to tab through the fields.
- We need a refresh button.  If I go to the `Realm overrides` tab and create a new override for a translation, I will not see it in the `Effective message bundles` tab.  I should be able to do a refresh so I can view my change in the effective message bundle.
- By default, translations should be sorted by key in alphabetical order.

### Version

main

### Expected behavior

See above.

### Actual behavior

See above.

### How to Reproduce?

See above

**Comment by agagancarczyk** [comment]
Thanks @ssilvert This is great feedback. I like all of it and I will break this issue into 2 and start implementing.

**Comment by agagancarczyk** [comment]
Closing this issue as all changes have been implemented.
