### ISSUE TITLE
Rest custom JAX-RS resource in kc 23: Method not allowed

### ISSUE THREAD

**Issue by cdevienne** [keycloak/keycloak#26088]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Starting with KC 23, our JAX-RS based resource, implemented after 'example/providers/rest', is not working properly.
The resource works fine up to KC 22.

### Version

23.0.4

### Expected behavior

The provider function decorated with "GET" should be called.

### Actual behavior

The 'getResource' function of the provider properly gets called, but the GET-decorated function is never called, and the http client gets a '405 Method Not Allowed' status.

### How to Reproduce?

The "example/providers/rest" should display the same behavior.

### Anything else?

My guess is that it is related to the switch to RESTEasy Reactive. Did I miss something to port our provider?

**Comment by ahus1** [comment]
Thank you for your pull request. Let's keep this issue open until the PR is merged.
