### ISSUE TITLE
Cookie remains stored in the user browser after performing a logout

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26103]
### Description
A weakness was found in Keycloak Core package where the cookie remains stored in the user browser after performing a logout. This could contain sensitive information, although by default it does not have any and the cookie is invalidated.

It was noticed that in the Keycloak cookies, for example KEYCLOAK_SESSION there is an expires attribute used which makes the cookie persistent and the expectation is the cookies should be session

### Version
\>= 23.0.4

### References
- https://issues.redhat.com/browse/RHSSO-2839
- https://cwe.mitre.org/data/definitions/539.html

**Comment by varodrig** [comment]
is this the reason why I user cannot logout from the web browser? only when using an incognito mode?

**Comment by jonkoops** [comment]
@pedroigor @stianst looks like another cookie issue for the cookie jar.

**Comment by stianst** [comment]
Cookies are expired when a user logs out, so I'm not able to reproduce this one. It's not really clear from the description what cookies we're talking about, nor when they are not expired.
