### ISSUE TITLE
Device verification flow does not require consent under certain circumstances

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26100]
### Description

Keycloak does not require consent in the device verification flow if there are no scopes. This could allow an attacker to gain a user's session without the user's knowledge or consent under some circumstances. The OAuth 2.0 Device Authorization Grant spec requires user interaction (i.e., the user has clicked a button to give permission). 

### Version

\>= 23.0.4

### Steps to reproduce

Reproducer:

1. Create a realm, a user, a client.
2. Enable "OAuth 2.0 Device Authorization Grant Enabled"
3. Remove the "Assigned Default Client Scopes"
4. Log in as a user
5. Make a device flow request (With the scope offline_access, but that work also without) [3]
6. Call the `verification_uri_complete` URL (Keycloak say "Device Login Successful")
7. Make a `urn:ietf:params:oauth:grant-type:device_code` flow request, to check that we have the access_token and refresh_token [4]

1. Code Reference: 
```
<https://github.com/keycloak/keycloak/blob/48835576daa158443f69917ac309e1a7c951bc87/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1061-L1065>
```
2. Spec Reference: <https://datatracker.ietf.org/doc/html/rfc8628#section-3.3>
```
    > Authorization servers supporting this specification **MUST** implement a
    > user-interaction sequence that starts with the user navigating to
    > "verification_uri" and continues with them supplying the "user_code"
    > at some stage during the interaction. Other than that, the exact
    > sequence and implementation of the user interaction is up to the
    > authorization server; for example, the authorization server may
    > enable new users to sign up for an account during the authorization
    > flow or add additional security verification steps.
```
3. Device Flow Request:
```
    curl --request POST \
    --url http://localhost:8080/auth/realms/realm/protocol/openid-connect/auth/device \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data client_id=test \
    --data scope=offline_access
```
4. `urn:ietf:params:oauth:grant-type:device_code` flow request:
```
    curl --request POST \
    --url http://localhost:8080/auth/realms/realm/protocol/openid-connect/token \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data client_id=test \
    --data device_code= Y-quHfHLvfUa9cZj-LmLTRmPa6SLgq2FSvhi2_Pb7To \
    --data grant_type=urn:ietf:params:oauth:grant-type:device_code
    
```

### References: 
- https://issues.redhat.com/browse/RHSSO-2682

**Comment by graziang** [comment]
Reproduced this issue, for device flow the consent screen is always displayed when there is at least one default scope or an optional scope requested, but is ignored if there are no scopes in the request.

In according with the specification, consent should always be required for device flow.

As workaround in the client "Login Settings" is possible to force the request for consent by enabling the "Consent required" and "Display client on screen" options.

A solution could be to force always the consent request [here](https://github.com/graziang/keycloak/blob/693aa1710fde993921cecbbc21287f7817974fa0/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1121.)  in case of device flow.
