### ISSUE TITLE
Lack of input validation for parameters used in JWT generation

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26107]
### Description

A weakness in Keycloak was identified where malformed data submitted via its API caused application crashes and potential Denial of Service by disrupting the OpenID-Connect authentication process. 

This issue is related with the validation or sanitization of inputs. Below are more details.

### Version

\>= 23.0.4

### Additional details

> By submitting malformed data over the API [https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_updateuser] we
> identified that Keycloak would accept any input given. As the values were later used for the OpenID-Connect
> authentication via the JWT, it crashed the application and the OIDC implementation. This could result not
> only in a login failure (Denial of Service) but also in more serious security issues, depending on how the 
> applications work and uses those values, taken from the signed RS256 token. We believe that Keycloak should
> only accept (sanitized) values that will not break the OIDC authentication or any other plugin that could be 
> affected by this.

### Reproduction steps:

1. Get an access token for an admin user
2. Submit malformed date to the following endpoint https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_updateuser
3. Attempt to login as the user and recognize that there is a server error

### References
- https://issues.redhat.com/browse/RHSSO-2672

**Comment by ManfredLange** [comment]
Related documentation for version 24.0.2 can be found at https://www.keycloak.org/docs-api/24.0.2/rest-api/index.html#_users

**Comment by rmartinc** [comment]
Hi @ManfredLange!

Is this still reproducible with the user profile enabled? Now the user attributes are defined by a user profile and each attribute can define validators to enforce the format. By default only a few attributes can be modified but the admins can customize the user profile.

What attribute was you modifying to make the user login fail? Is it allowed to do that in version 24.0.3?

**Comment by mposolda** [comment]
I think this is already addressed by declarative-user-profile. By default, attributes come with the restriction for maximum length and it is not possible to add random attributes (unless unmanaged attributes switch is enabled, which can have impact on security, but it is documented). More details in the docs https://www.keycloak.org/docs/latest/server_admin/index.html#user-profile and also in the release notes and upgrading guide for Keycloak 24:
https://www.keycloak.org/docs/24.0.3/release_notes/#supported-user-profile-and-progressive-profiling
https://www.keycloak.org/docs/24.0.3/upgrading/#user-profile-changes
https://www.keycloak.org/docs/24.0.3/upgrading/#user-attribute-value-length-extension
