### ISSUE TITLE
Improper Input Validation and Sanitization Leads to persistent partial Denial of Service

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26109]
### Description

The Keycloak REST API allows an authenticated realm admin to register new and non existent required actions for all users in a realm. This is done by adding the required action values in the body of an HTTP POST request to the /auth/admin/realms/master/authentication/register-required-action endpoint. However, no validation or sanitization is performed on the input values.

The improper validations allow adding any string value in the providerId field which is then stored in the database as the required action alias as well. After adding a non existent action as required, users can no longer log into the realm.

The improper sanitization could also result in a malformed URL affecting the functionality of other actions like the edition or deletion of the newly created required action using the PUT or DELETE HTTP methods through the /auth/admin/realms/[realm]/authentication/required-actions/[alias] endpoint.

### Version
\>= 23.0.4

### Impact

Unexistent required actions providerId (and alias) values leads to a persistent partial Denial of Service (DoS) by not allowing any user to login into the realm using the Keycloak UI. Not allowing a realm admin to delete, edit or perform any other action that requires the required action unsanitized alias in the URL path as a parameter persist this DoS. This issue gets more severe when the non existent required action has been added to the master realm and thus affects the access to it.

Manually deleting the required action from the REQUIRED_ACTION_PROVIDER table in the database and restarting the Keycloak server is the only way to restore the user access to the affected realm.

This issue has been classified as a weakness given that realm admin privileges are required to create the required action.

### Recommendations

* Validation should be performed before registering a new required action to ensure it exists and is properly implemented.
* A unified sanitization and validation strategy should be implemented on all user input values to ensure only valid values are accepted and saved.
* User input controlled values should not be used to unequivocally identify an object. Also, for this particular case, many required actions can share the same alias value at database (DB) level given that it hasn’t been defined as an UNIQUE DB field. Thus editing or deleting an action with a shared or duplicate alias could affect a different action than the initially intended. Using a Primary Key field (ID) or an UNIQUE Alternate Key is recommended as a best practice when deleting or editing objects from a database.

### References
- https://issues.redhat.com/browse/RHSSO-2680
* https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html
* https://gitlab.cee.redhat.com/keycloak/keycloak-prod/-/blob/18.0.x/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L947

**Comment by graziang** [comment]
For this one a simple solution could be to verify the existence of the provider factory using the `providerId` passed in the body of the request to register a required action:

`session.getKeycloakSessionFactory().getProviderFactory(RequiredActionProvider.class, providerId)`

A check to avoid a provider with the same alias is already present in https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/RealmAdapter.java#L1841
