### ISSUE TITLE
Observable Response Discrepancy

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26110]
### Description
A bug in Keycloak allows the enumeration of different clients registered on a particular realm.

### Version
\>= 23.0.4

### How to reproduce

1. Access the following Keycloak URL and change the 'client_id' with a list of different names.
```
https://<Keycloak_Server:port>/auth/realms/master/protocol/openid-connect/auth?scope=openid&response_type=code&redirect_uri=valid&state=cfx&nonce=cfx&client_id=[valid/invalid
client-Id]&request_uri=http://www.google.com <http://www.google.com>
```

2. Observe the response of valid and invalid client-id names provided in step one.
3. If the server responded with "Invalid Request", then its an existing client and if the server respond with "Client not found", then its a non-exiting client.

### Remediation/Mitigation:

Return generic error messages to user for invliad client-ID and block the
requesting IP for a treshold period for bruteforce attempts.

### References
- https://issues.redhat.com/browse/RHSSO-2694

**Comment by rmartinc** [comment]
@abstractj Client enumeration is possible in keycloak in different places and there has been some tries to avoid this in the login page that were finally reverted. One example is https://github.com/keycloak/keycloak/issues/19662 which reverts a change done in https://github.com/keycloak/keycloak/issues/12164. This one is teh same but using `request_uri`. I would say that this was already tried and we decided to not do it.

If nobody says something different I would close this one as not planned.
