### ISSUE TITLE
Migration docs for https://github.com/keycloak/keycloak/issues/15190

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#26146]
### Description

As discussed in the comments in https://github.com/keycloak/keycloak/pull/23303#issuecomment-1888283421 , we may rather add some small migration note about the behaviour change (just to avoid some questions and possible bug reports due the behaviour change as some people can still rely on the old behaviour).

**Comment by lexcao** [comment]
Hi @mposolda 
PR created, please help review
#26204
