### ISSUE TITLE
Remove dependency on `FormContext` for shared UI controls

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#26151]
A number of the [shared UI controls](https://github.com/keycloak/keycloak/tree/main/js/libs/ui-shared/src/controls) for forms make use of `useFormContext()`, these should be re-written to controlled components.

**Comment by edewit** [comment]
Context is a good way to not have to pass things down multiple levels of components as described in the [docs](https://react.dev/reference/react/useContext#passing-data-deeply-into-the-tree) so I say we keep it that way

**Comment by jonkoops** [comment]
Disagree, but this is no longer my responsibility and I am not going to force this on the team.
