### ISSUE TITLE
Optimize query batching and result fetching by tuning Hibernate parameters

### ISSUE THREAD

**Issue by sebastianh6r** [keycloak/keycloak#26162]
### Description

Hibernate offers a few performance tuning option which do not seem to be applied in Keycloak.

I propose to add the following defaults or at least offer an easy way to configure them:
```
<!-- execute multiple insert and update statements in a single call to improve bulk insert / update performance, see https://vladmihalcea.com/hibernate-performance-tuning-tips/ -->
<property name="hibernate.jdbc.batch_size" value="50" />

<!-- (optional) allows for more batching but according to https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/chapters/batch/Batching.html "Comes with a performance hit, so benchmark before and after to see if this actually helps or hurts your application." -->
<property name="hibernate.order_inserts" value="true" />
<property name="hibernate.order_updates" value="true" />

<!-- increase number of elements fetched from Oracle database query result up from 10 (MSSQL returns the whole result at once); see https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/resultset.html -->
<property name="hibernate.jdbc.fetch_size" value="50" />

<!-- (optional) pad in-clause queries to next power of 2 to improve query execution plan caching, see https://thorben-janssen.com/parameter-padding/ -->
<property name="hibernate.query.in_clause_parameter_padding" value="true" />
```

Due to https://github.com/keycloak/keycloak/issues/19427 persistence.xml / Quarkus properties issue the settings cannot be applied easily so I would propose to either offer them as Keycloak configuration options similar to some other Hibernate settings or extend the defaults.

See also https://access.redhat.com/documentation/de-de/jboss_enterprise_application_platform/5/html/performance_tuning_guide/sect-performance_tuning_guide-entity_beans-batching_database_operations

### Motivation

Applying this settings by modifying the persistence.xml in the keycloak-model-jpa-22.0.5.jar tenant creation operations were sped up by about a factor of 2.

**Comment by sebastianh6r** [comment]
@ahus1 do you have some feedback on that topic?

**Comment by ahus1** [comment]
@sebastianh6r - looking at the options, those make sense to test. Please create a PR for these changes, and then we'll see how the tests respond to these settings.
