### ISSUE TITLE
Support dark mode, at least for the login pages

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#26178]
### Description

A lot of apps support dark mode. We also support it. Our users select dark mode both on the website and in their user panel. However, when they are logged out, they are redirected to Keycloak's login page, and it bothers their eyes. Especially in the middle of the night.

### Motivation

We want to deliver a unified UX for our users. We want them to be able to experience a dark theme out of the box for the login page too.

### Details

I know it's possible for us to create a custom theme. But that's a huge overhead. I think a default dark mode should be available out of the box, and it should be activated using a URL parameter like `&dark=true`.

**Comment by jonkoops** [comment]
We will be upgrading the login theme to PatternFly 5 (see #21342), which has [support for dark mode](https://www.patternfly.org/developer-resources/dark-theme-handbook/#enabling-dark-theme), so once that lands this would be trivial to add as a feature.

**Comment by omasseau** [comment]
I've upgraded to Keycloak 26, but it always show the admin console in dark mode.
How can we switch to the light mode ? I see not button or menu for the switch.
