### ISSUE TITLE
LDAP sync broken across the cluster after node shutdown during sync

### ISSUE THREAD

**Issue by dteleguin** [keycloak/keycloak#26183]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

In a clustered Keycloak deployment, if a node is shut down while performing LDAP sync, no other node will be able to do LDAP sync anymore. The following message will be shown:

> Synchronization ignored as it's already in progress

This happens because when LDAP sync is started, a corresponding record is put into the work cache, which is replicated across the cluster nodes. When the node gets shut down, the record won't be removed. The function could be restored only by scaling the cluster down to zero and scaling up again, which is undesirable for production environments.

The issue could be solved either by graceful handling of the work cache record during shutdown, or by periodically checking the work cache and removing the records pertaining to the node(s) that are not alive anymore.

Also, node shutdown during sync should not be considered as something abnormal. In Kubernetes, pod recycling is part of normal operation. Combined with huge LDAP directory (and hence lengthy sync), that could easily lead to the above issue.

### Version

23.0.4

### Expected behavior

LDAP sync should work regardless of the lifecycles of the cluster nodes.

### Actual behavior

LDAP sync is broken for the whole cluster if a node is shut down during LDAP sync.

### How to Reproduce?

* Start Keycloak cluster with 2+ nodes;
* initiate LDAP sync from one of the nodes (via Admin UI) or wait for the scheduled sync to occur;
* shut down the node performing LDAP sync
* try LDAP sync from a different node

**Comment by ahus1** [comment]
Thanks for reporting this. There are already mechanisms in place that should handle this. Let's investigate why they don't work here: 

There is a piece of code here which on a cluster view change removes stale locks from the work cache. This is triggered on a surviving node which is the coordinator. 

https://github.com/keycloak/keycloak/blob/5b1b3ca11be8526482c1cfc3a441c747b107a991/model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java#L217

Maybe you could try to enable the debug logging for this class and see if this is triggered. 

It would also be good if you could enable trace logging for this class, as it would log the node name as it is stored in the lock, and also the node name in the existing lock:

https://github.com/keycloak/keycloak/blob/a8cff72ed0ef3ec698c637c15f621e3ba4405459/model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProvider.java#L144-L155

With those log entries, maybe we can find out what is happening here. Maybe it allows you to even find the cause.

There is another mechanism in place that the lock should not persist longer than the sync period, see https://github.com/keycloak/keycloak/blob/7797f778d1b32fe45922eb170c9a7c1910a964ce/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L103 - this would be our fallback here, although that timeout is quite long.

**Comment by soulchild** [comment]
I may be seeing something similar with a custom UserStorage provider. The main parts are based on the official LDAP UserStorage provider, I basically just replaced all LDAP stuff with calls to an HTTP REST API which delivers the users. The full sync is triggered every day and takes between 4-5 minutes. 

A few weeks ago, I noticed that the full sync hadn't run for a couple of weeks. It worked perfectly fine for about two years now. As the number of users grows constantly, I suspect the time it takes to sync all users has now crossed a threshold causing problems.

Restarting the Keycloak instance always helps for about 3-4 days/full syncs, but then it stops working again. 

Doing a manual full sync from the UI fails with the above mentioned error `Synchronization ignored as it's already in progress`. Some rather strange observations: 

- After 2-3 times of manually triggering the sync from the UI it starts working again. 
- The Keycloak logs always show corresponding messages of "Sync all users started" and "Sync all users finished". I would have expected to see "Sync all users started" without ever seeing a corresponding "finished" message, but that's not the case.
- The "Sync changed users" sync runs every two minutes and is not affected by this.

We are also running two Keycloak instances on a Kubernetes cluster. Our Keycloak version is 26.3.2. Could this be related, @pedroigor?
