### ISSUE TITLE
Keycloak Operator 23.0.4 not available in OpenShift Community Operators catalog

### ISSUE THREAD

**Issue by bo0ts** [keycloak/keycloak#26191]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

The important Keycloak security release is not yet available for users that installed Keycloak through the OpenShift Community Operators.

### Version

23.0.3

### Expected behavior

The Operator is available in the catalog as soon as the new version of the operator has been released.

### Actual behavior

Security update is not available, because the operator hasn't been published to the registry.

### How to Reproduce?

Have a look at https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/keycloak-operator

**Comment by shawkins** [comment]
Unfortunately this is still a manual release process for us, so it doesn't happen automatically on every release yet. Since there were no changes to the operator in that increment a workaround would be to change the operator deployment to reference the later image instead.

See also #10438

**Comment by bo0ts** [comment]
> Unfortunately this is still a manual release process for us, so it doesn't happen automatically on every release yet. Since there were no changes to the operator in that increment a workaround would be to change the operator deployment to reference the later image instead.
> 
> See also #10438

Unfortunately this isn't so easy. I've tried overriding the image before and the way the operator starts the image changes and the default images don't work anymore.

Also, the documentation advises against this here https://www.keycloak.org/operator/customizing-keycloak 

> To ensure full compatibility of Operator and Operand, make sure that the version of Keycloak release used in the custom image is aligned with the version of the operator.

**Comment by vmuzikar** [comment]
@bo0ts Thanks for the report.

Apparently, the CI on the [PR](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3845) got stuck and I haven't noticed. :( I tried to restart it now.

**Comment by shawkins** [comment]
> > Unfortunately this is still a manual release process for us, so it doesn't happen automatically on every release yet. Since there were no changes to the operator in that increment a workaround would be to change the operator deployment to reference the later image instead.
> > See also #10438
> 
> Unfortunately this isn't so easy. I've tried overriding the image before and the way the operator starts the image changes and the default images don't work anymore.
> 
> Also, the documentation advises against this here https://www.keycloak.org/operator/customizing-keycloak
> 
> > To ensure full compatibility of Operator and Operand, make sure that the version of Keycloak release used in the custom image is aligned with the version of the operator.

I can understand the trepedation, but what I'm saying is specific to this release - there were no changes in 23.0.4 in the operator, so there won't be issues like you observed before. It should be moot as @vmuzikar got the pr merged, but should we end up in this state again, you can diff release labels to determine if the image change is fine.

**Comment by vmuzikar** [comment]
Closing this as this has been resolved now. 20.0.4 was released (and recently 20.0.5 as well).
