### ISSUE TITLE
SSH public keys cannot be written as multivalue attributes in LDAP

### ISSUE THREAD

**Issue by preisacm** [keycloak/keycloak#26194]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

- There are multiple SSH keys stored in LDAP as nsSshPublic key
  ![ADS-SSH-keys-before](https://github.com/keycloak/keycloak/assets/16749230/77ec03a7-9c75-4d12-b212-dd622fc39c3f)
- Keycloak is able to show all entries of the LDAP attribute correctly:
  ![Keycloak-SSH-keys-before](https://github.com/keycloak/keycloak/assets/16749230/1a03e967-0719-46d1-bf29-0f9c579528aa)
- You change one of the entries to another value, e.g. change `<sshkey2>` to `<sshkey3>`:
  ![Keycloak-SSH-keys-after](https://github.com/keycloak/keycloak/assets/16749230/29921178-4657-42a9-8de4-7e2dd00c06ea)

### Version

23.0.4

### Expected behavior

- The changed SSH key is set accordingly in LDAP and all others are not touched

### Actual behavior

- All SSH keys are deleted and there is a new single value attribute holding the whole string of the text area:
  ![ADS-SSH-keys-after](https://github.com/keycloak/keycloak/assets/16749230/6f22111f-a121-414e-8ef8-f1667861014c)

### How to Reproduce?

Setup:
- 389DS where SSH public key are stored
- Keycloak is allowed to edit some LDAP attributes, especially SSH public keys as multivalue attributes
  - Enabled Feature: Declarative User Profile
- Apache Directory Studio to edit LDAP entries

Attribute Setup:
- The LDAP Provider has the following mapper setup (which works just fine):
  ![LDAP-provider-SSH-public-key](https://github.com/keycloak/keycloak/assets/16749230/3ab2195d-72e3-45da-8523-7e9a39637b4a)
- The User profile in the Realm settings uses the attribute as text area:
  ![Realm-settings-SSH-public-key](https://github.com/keycloak/keycloak/assets/16749230/64d4976a-9be5-4197-aa06-adb3b3cb65e5)

### Anything else?

- I did not find any setting where I can make Keycloak aware of this multivalue attribute.
- Manually adding the separator `##` does not work either - The content of the text area will be stored unchanged in LDAP
- SSH keys are used as an example here - I assume this is a general problem of multivalue attributes in LDAP except `objectClass`
- The account UI has the same issue (when you make the attribute user-editable)

**Comment by edewit** [comment]
Could you try without the annotation? Keycloak should render a multivalue field when it detects that the value is an array. #26943 will introduce a way to select this from the annotations

**Comment by preisacm** [comment]
Could finally try that and it works as expected. Thanks!
