### ISSUE TITLE
Safari - multiple redirects when blocking 3rd party cookies (setCookie "domain" parameter)

### ISSUE THREAD

**Issue by MGLL** [keycloak/keycloak#26240]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Discussion: https://github.com/keycloak/keycloak/discussions/26219

We have an issue where Safari consider the cookies generated by Keycloak under a sub-domain as 3rd party cookies. As we are looking to block 3rd party cookies on our platform, it cause multiple redirects from our FE to KC.
We don't have this issue on Chrome & Firefox.

While checking the source code of Keycloak, I saw that there is a `domain` parameter on the `setCookie` methods of Keycloak, but it's always set to `null`.

We currently have this kind of setup:
- auth.example.com -> Keycloak
- app.example.com -> Platform (Secured)
- example.com -> Showcase site

On the FE we use React with https://github.com/authts/react-oidc-context and we have check-sso on init (onLoad).

We are currently wondering if allowing a wild card domain (like `.example.com`) or base domain (`example.com`) in `setCookie` could solve this issue.
But as we are using Keycloak in a container and the null value is hardcoded, it seems we have no way to verify this theory.

### Version

20.0.5

### Expected behavior

Make the `domain` in `setCookie` externally configurable so we can specify the base domain (`example.com`).

### Actual behavior

The `domain` parameter in `setCookie` is always set to `null` which let the different browsers deals with the configuration. 

### How to Reproduce?

1. Deploy a Keycloak on a sub-domain like `auth.example.com`
2. Deploy your secured FE application on another sub-domain like `app.example.com`
3. Block 3rd party cookies and use Safari

**Comment by jonkoops** [comment]
@MGLL I see you reported this issue for Keycloak 20, is it also reproducible in the latest stable version? I am not sure if there is a historical reason the domain is not set in the cookie, but I think it should be set in this case.

**Comment by MGLL** [comment]
@jonkoops  I checked the `setCookie` method from both Keycloak 20.* and 23.* and it's identical (`domain` is always `null` in code). So I guess the issue can be reproduced in Safari, as it might still deals with it as a 3rd party cookie (and block it). 

And I just found an issue a bit similar to what we have (in another repo) : https://github.com/akvo/akvo-lumen/issues/694
With Keycloak on a specific sub-domain which have cookies taken as 3rd party.

Also there was this article: https://keycloak.discourse.group/t/configuring-cookie-domain-of-keycloak-cookies/1953 
That I checked before opening the discussion. 

Somehow, the setup we have is similar to what was described (using check-sso onLoad), which works with Chrome and Firefox but not with Safari where we have multiple redirects to Keycloak when we block cookies.  

But let me loop with the team to see if there is a way to test it locally with the latest Keycloak (we are looking to upgrade, but we are a bit blocked with the account UI change).

**Comment by stianst** [comment]
Setting the domain attribute is probably not a great idea, as that will make the cookies available to on all subdomains, which is not what is wanted, and would be a security risk.

Basically if you set domain=example.com, then app.example.com would also have access to the cookies, which it should not have.

Honestly this sounds like stuff is broken in Safari, as it should not consider cookies as third-party if they are in the same eTLD+1.

**Comment by stianst** [comment]
@jonkoops wasn't keycloak.js supposed to not do `check-sso` when the session cookies can't be retrieved?

**Comment by jonkoops** [comment]
> wasn't keycloak.js supposed to not do check-sso when the session cookies can't be retrieved?

It attempts to detect if third-party cookies are supported, if not then it will fall back to the redirect flow instead of doing silent authentication.

**Comment by MGLL** [comment]
Hi @jonkoops,
I can now fully confirm that the issue is reproducible with latest Keycloak version (as expected from my explanations).

As a reminder, our setup is as follow: 
_Development environment_
- auth.domain.com = keycloak IDP
- domain.com/* = Application

_Production environment_
- auth.domain.com = keycloak IDP
- app.domain.com/* = Application
- domain.com = Marketing page

This issue is particularly visible as we use micro-frontend architecture.  
As we navigate in the application, mfes tries to silent check-sso (on _app.domain.com_), but as cookie is then considered "third party" (issued by "another domain" (_auth.domain.com_)), it fallbacks to KC redirect to check session. 

So visually, we can see that multiple page reloads & redirects are happening as you navigate in the application (which impact user experience). 

Is that something expected to happen with chrome regarding Privacy Box ?

Best

**Comment by jonkoops** [comment]
> Is that something expected to happen with chrome regarding Privacy Box ?

Unfortunately, yes. There is not much we can do about this due to the nature of the Privacy Sandbox changes, this is Google's initiative, but the Safari team implements similar protections. We're in the proccess of evaluating new standards such as the Federated Credential Management API (#16834), which will hopefully mitigate these problems to some extend, and hopefully improve UX in the proccess.

**Comment by jonkoops** [comment]
Yeah, that is a valid solution. It's unfortunate that browser vendors decided to roll out these changes without first providing a migration path that works universally. Not saying these privacy protections aren't needed, but it's a mess.

**Comment by jonkoops** [comment]
I am closing this issue, as this is not within the control of the Keycloak project to fix. For further mitigations I recommend following the discussion around the Federated Credential Management API.
