### ISSUE TITLE
Remove need to update Quarkus tests when profile features change

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#26262]
### Description

Due to the way the CLI output is tested in Quarkus tests every time a feature is added/removed/deprecated a manually and error prone update has to be done to several text files to reflect the changes in the CLI output.

This is not sustainable and adds a lot of unnecessary overhead and complexity to any work around features, and features are an important part of Keycloak that we will just use more and more in the future.

As an example look at https://github.com/keycloak/keycloak/pull/26161/files. Half of the changes in the PR is caused by the Quarkus testsuite, and not the actual change itself.

Some suggestions:

* Template the list of features in the text files. This may be tricky to get the indentation correct though, but should be doable
* Stop listing the features in the CLI help, and instead refer to the documentation, or perhaps consider a helper command (`kc.sh help list-features` or something like that) that can output something similar to the features documentation

### Motivation

Allow developers to work with features without having to update the Quarkus testsuite, and especially having to update several text files.

**Comment by jonkoops** [comment]
As per my [previous rant](https://github.com/keycloak/keycloak/pull/26161#issuecomment-1889559305) on this topic, 100% agree.

**Comment by vmuzikar** [comment]
Resolved by #27546
