### ISSUE TITLE
The new Keycloak Operator does not allow for ENV variable substitution in the realm import

### ISSUE THREAD

**Issue by stustison** [keycloak/keycloak#26275]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

In a containerized scenario, it is often necessary to use ENV variables to pass in information via secrets, etc. The Keycloak import command allows for ENV variable substitution using the `keycloak.migration.replace-placeholders` option, however, the Keycloak Operator has hardcoded the import command and has no option in the KeycloakRealmImport CR to allow you to set any additional options. This means only static information can be imported when Keycloak is started.

### Version

23.0.4

### Expected behavior

The KeycloakRealmImport CR should allow for the setting of any additional options to be used with the import command

### Actual behavior

The Keycloak Realm import from the operator always uses the command `/opt/keycloak/bin/kc.sh import --file='/mnt/realm-import/your-realm.json' --override=false` which will never result in ENV variables being substituted into the realm import

### How to Reproduce?

Deploy Keycloak via K8s

**Comment by shawkins** [comment]
See the discussion on https://github.com/keycloak/keycloak/issues/20199#issuecomment-1599329238 and is shown in a full example keycloak cr at https://github.com/keycloak/keycloak/issues/25467#issuecomment-1850408851

@vmuzikar I know we elected to not do anything the last time this came up, but if this is a common scenario we could consider operator documentation, or even a realm import cr enhancement to make this easier.

**Comment by stustison** [comment]
@shawkins I tried adding the `JAVA_OPTS_APPEND` ENV variable to the yaml and the realm import Job still comes up with `-c /opt/keycloak/bin/kc.sh import --file='/mnt/realm-import/your-realm.json' --override=false` as the command being run and ENV variables in the realm import are not resolved. I'm happy to submit a PR to just do this the right way.

**Comment by stustison** [comment]
The job yaml definitely has the env variable set, hopefully that looks correct:
```
- name: JAVA_OPTS_APPEND
          value: >-
            -Dkeycloak.migration.provider=singleFile
            -Dkeycloak.migration.file=/tmp/master-realm.json
            -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
            -Dkeycloak.migration.replace-placeholders=true
```

**Comment by shawkins** [comment]
Yes, can you then check the Pod that created by the Job and see if its command contains the expected values?

**Comment by stustison** [comment]
I got it to work, I just had to move things around a bit. Thank you for the help! I will still try to throw up a PR to drop this into the CR instead to make it a little easier for folks in the future.

**Comment by shawkins** [comment]
> I got it to work, I just had to move things around a bit. Thank you for the help!

Great. No problem.

> I will still try to throw up a PR to drop this into the CR instead to make it a little easier for folks in the future.

Thanks, it does seem like this will keep coming up.

**Comment by shawkins** [comment]
Closing this issue - an enhancement request should be opened to cover any cr changes.

**Comment by asergeant01** [comment]
@stustison Are you able to share how you got it working... I've got the same issue.
