### ISSUE TITLE
Enable to log to the admin UI

### ISSUE THREAD

**Issue by 3Quatorze** [keycloak/keycloak#26271]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I can't log to the admin UI.

### Version

23.0.4

### Expected behavior

I should access the login page of the admin UI

### Actual behavior

After having clicked on the link to the **Administration Console** the message *Loading the Admin UI* is shown and never disappears.

### How to Reproduce?

On a fresh RHEL 8.7 VM where openJDK17 and postgreSQL15 are installed, I downloaded keycloak-23.0.4.tar.gz then ran:
```bash
tar -xvzf keycloak-23.0.4.tar.gz
# Copy conf and certifcates
cp temp/* keycloak-23.0.4/conf/
cd keycloak-23.0.4
KEYCLOAK_ADMIN="kcadmin" KEYCLOAK_ADMIN_PASSWORD="sdfsdf" bin/kc.sh --verbose start --log-level=DEBUG --log="console,file"
```
Connect to https://keycloak.testing.com:8443/
Click on *Administration Console*
more than one ☕ later and a few **Refresh page** tentatives
Stop

### Anything else?

```bash
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)

$ java -version
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.4.1.1-6.el8) (build 17.0.4.1+1-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.4.1.1-6.el8) (build 17.0.4.1+1-LTS, mixed mode, sharing)

$ bin/kc.sh show-config
Current Mode: production
Current Configuration:
        kc.config.built =  true (SysPropConfigSource)
        kc.db =  postgres (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.db-password =  ******* (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.db-url =  jdbc:postgresql://localhost:5432/keycloak (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.db-username =  kcadmin (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.hostname =  keycloak.testing.com (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.https-certificate-file =  ${kc.home.dir}/conf/keycloak.testing.com.pem (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.https-certificate-key-file =  ${kc.home.dir}/conf/keycloak.testing.com.key (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.log-console-output =  default (PropertiesConfigSource[source=jar:file:///deployment/keycloak-23.0.4/lib/lib/main/org.keycloak.keycloak-quarkus-server-23.0.4.jar!/META-INF/k
eycloak.conf])
        kc.log-file =  ${kc.home.dir:default}${file.separator}data${file.separator}log${file.separator}keycloak.log (PropertiesConfigSource[source=jar:file:///deployment/keycloak-23.0
.4/lib/lib/main/org.keycloak.keycloak-quarkus-server-23.0.4.jar!/META-INF/keycloak.conf])
        kc.spi-hostname-default-hostname =  keycloak.testing.com (PropertiesConfigSource[source=file:/deployment/keycloak-23.0.4/bin/../conf/keycloak.conf])
        kc.version =  23.0.4 (SysPropConfigSource)
```

Attached the debug file if necessary
[debug.zip](https://github.com/keycloak/keycloak/files/13964418/debug.zip)

**Comment by jonkoops** [comment]
Are there any failed requests in the network tab of your browser, or errors in the JS console?

**Comment by 3Quatorze** [comment]
I have a failed request for step1.html, NS_ERROR_UNKNOWN_HOST

**Comment by jonkoops** [comment]
This is likely a configuration error then, seems like there is something about your local setup that is giving DNS errors. I'd recommend reading the following parts of the documentation:

- https://www.keycloak.org/server/configuration
- https://www.keycloak.org/server/configuration-production

Closing this, as I don't believe it to be a bug in Keycloak itself.

**Comment by 3Quatorze** [comment]
There was an issue with the domain name in the configuration file.
Thanks for the help.
