### ISSUE TITLE
Override Action Tokens doesn't work

### ISSUE THREAD

**Issue by Piju** [keycloak/keycloak#26274]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client/java

### Describe the bug

When using Override Action Tokens in Keycloak admin, user action links sent by email always use `User-Initiated Action Lifespan` value for link validity.

### Version

23.0.4

### Expected behavior

User initiated action links should use override action tokens values set in admin.

### Actual behavior

User initiated action links always use `User-Initiated Action Lifespan` value set in admin.

### How to Reproduce?

- Set a value for `User-Initiated Action Lifespan` and value(s) for  one or more `Override Action Tokens`
- Use registration action and forgotten password (for example)
- Email link always show the same value for link lifetime

**Comment by graziang** [comment]
Duplicate of #25827

I'm closing this, it has already been fixed. Also verified the fix on the latest version.
