### ISSUE TITLE
Remove deprecated EnvironmentDependentProviderFactory.isSupported method

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#26280]
If this is considered a breaking change, we should wait until another major release with the default impl added by #26003 in place (although developers may still not be aware that the method is deprecated, they will be able to proactively resolve the deprecation).

Alternatively if this is not considered a breaking change, then we can immediately remove the old signature.

_Originally posted by @vmuzikar in https://github.com/keycloak/keycloak/issues/26003#issuecomment-1895919188_

**Comment by shawkins** [comment]
duplicate of #28751

**Comment by pruivo** [comment]
I don't think this is a duplicated @shawkins 
I'm not removing the method from the interface, I'm just changing the code to stop using that method.

**Comment by shawkins** [comment]
@pruivo in practial terms there's little reason to to one without the other. If you want to track it seperately feel free to re-open this issue.

**Comment by pruivo** [comment]
I'm ok either way. I want to make sure that everybody is aware that I'm not removing the deprecated method :+1:

**Comment by pruivo** [comment]
I'm going to drop the method :)

**Comment by vmuzikar** [comment]
@pruivo It's a private SPI, we don't need to worry about making breaking changes. My two cents would be to remove the method when no longer in use. Nothing else is supposed to use it, no external consumers. Keeping it increases the chances someone starts to use it again. :)
