### ISSUE TITLE
Error! Failed to send email

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#26304]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I have configured the smtp server setting. Tying to test the connection, but the UI gives me the error:

`Error! Failed to send email`

but there are 0 logs.

This looks like a BUG.

### Version

22.0.3

### Expected behavior

Generate logs with the actual error

### Actual behavior

The error logs are missing

### How to Reproduce?

Configure the smtp settings. Click `Test Connection` button.

If the smtp setting are wrong, logs will be generated. You need to add the correct smtp configuration.

**Comment by jonkoops** [comment]
Closing this issue as it was reported for an older version of Keycloak, if the issue still persists in the latest version let us know and we will re-open it.
