### ISSUE TITLE
Add API Support for Changing User Federation Link in Keycloak

### ISSUE THREAD

**Issue by Andreavlm** [keycloak/keycloak#26306]
#### Problem
Currently, Keycloak lacks the ability to change a user federation link through API requests.

#### Current Workaround
The current workaround involves manually updating the database and clearing the user cache, which is neither efficient nor recommended for production environments. This process is error-prone and poses potential risks to the integrity of the Keycloak instance.

**Comment by sschu** [comment]
@Andreavlm you can link and unlink an account. Wouldn't that be sufficient for your use case?
