### ISSUE TITLE
Encrypt network communication in JGroups follow-up

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#26311]
### Description

There are some follow-up tasks to #25702 that might be tackled here or in other issues: 

* Create an integration test
* Tune the docs after a review from CCS
* Discuss a follow-up issue how the Operator could create the certificates possibly using cert manager. See https://github.com/keycloak/keycloak-benchmark/pull/685 for the necessary changes without an Operator change 

### Discussion

https://github.com/keycloak/keycloak/pull/25703

### Motivation

Improve the UX for encryption, especially on Kubernetes

**Comment by ahus1** [comment]
Alternative: Keycloak could generate the certificates and store them in the database to share them with other nodes. 

Benefits: Works also in non-operator environments, better UX for people running Keycloak.

**Comment by pruivo** [comment]
Related to https://github.com/keycloak/keycloak/issues/34546
