### ISSUE TITLE
Support Authorization Code Flow for VC Issuance

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#26328]
### Description

By following https://github.com/keycloak/keycloak-community/blob/main/design/OID4VCI.md , the issue proposes VC issuance by Authorization Code Flow. 

### Discussion

Its epic topic is https://github.com/keycloak/keycloak/issues/25936 .

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/29724
- [ ] https://github.com/keycloak/keycloak/issues/29725
```

**Comment by tnorimat** [comment]
@wistefan I would be happy if you add my sub task issue to your epic topic.

**Comment by wistefan** [comment]
> @wistefan I would be happy if you add my sub task issue to your epic topic.

I added it.

**Comment by tnorimat** [comment]
@wistefan Thank you!

**Comment by smandlavdiya** [comment]
Hope we get it with 25.0

**Comment by tnorimat** [comment]
All sub-tasks were resolved.
