### ISSUE TITLE
Apparently incorrect tooltip on "type" field for a "resource" in a client

### ISSUE THREAD

**Issue by tomqwpl** [keycloak/keycloak#26358]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

The tooltip on the "Type" field in the definition of a Resource appears incorrect:
![image](https://github.com/keycloak/keycloak/assets/42344626/4173e9df-54bb-4a41-bb9a-22e7cd09bf81)

This is within a client, under "Authorization", "Resources" within the definition of a new resource

### Version

23.0.4

### Expected behavior

A relevant tooltip

### Actual behavior

A tooltip that appears to be for something else

### How to Reproduce?

In a client, select the Authorization tab, and from there select the Resources tab. Create a new resource. 
![image](https://github.com/keycloak/keycloak/assets/42344626/44068ce8-bbb2-4a16-93bf-e177992a9937)

Click on the question mark next to the "Type" label

**Comment by ssilvert** [comment]
I have verified this bug.  For reference, the help text in V1 said, `They type of this resources.  It can be used to group different resource instances with the same type.`

It is using the key for `clientTypeHelp`, which is wrong.

Also note that we already have a key for `resourceTypeHelp`, which is used elsewhere.  Whoever fixes this will need to come up with a new key name for this field.

**Comment by agagancarczyk** [comment]
@ssilvert I'm going to use `typeHelp=The type of this resource. It can be used to group different resource instances with the same type. ` which already exists in the messages_pt_BR.properties file, but somehow is missing in the messages_en.properties file.

**Comment by ssilvert** [comment]
> @ssilvert I'm going to use `typeHelp=The type of this resource. It can be used to group different resource instances with the same type. ` which already exists in the messages_pt_BR.properties file, but somehow is missing in the messages_en.properties file.

@agagancarczyk I suggest that you rename that key.  It's very generic and might lead to duplicates.  I think that's part of the underlying problem here.

**Comment by agagancarczyk** [comment]
> > @ssilvert I'm going to use `typeHelp=The type of this resource. It can be used to group different resource instances with the same type. ` which already exists in the messages_pt_BR.properties file, but somehow is missing in the messages_en.properties file.
> 
> @agagancarczyk I suggest that you rename that key. `typeHelp` is very generic and might lead to duplicates. I think that's part of the underlying problem here.

No worries, I named it "resourceDetailsTypeHelp"
