### ISSUE TITLE
Users are deleted automatically after changing the new Ldap custom user filter from keycloak 

### ISSUE THREAD

**Issue by manumittal89** [keycloak/keycloak#26361]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have setup the ldap federation . While changing the new custom filter the old imported users is automatically deleted 

### Version

20

### Expected behavior

the users should not be removed 

### Actual behavior

the imported users is removed 

### How to Reproduce?

with keycloak 20

**Comment by ssilvert** [comment]
I don't think this is likely to be a UI bug.  Switching to core.

**Comment by jonkoops** [comment]
Closing this as it was reported for Keycloak 20, as our issue template clearly states we only accept issues that are verified to be reproducible in the latest version of Keycloak. If this issue persists in the latest version, open a new issue and make sure to provide detailed steps to reproduce.
