### ISSUE TITLE
Duplicate emails is On when Email as username and Login with email are On

### ISSUE THREAD

**Issue by 0verEngineer** [keycloak/keycloak#26364]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In the realm settings under login there are the Email settings, i have enabled "Email as username" and "Login with email", when both of these are enabled the "Duplicate emails" switch has the state "On", this does not make any sense to me because "Duplicate emails" cannot be true if a user is able to login with his email....

Previous issues and MRs:
https://github.com/keycloak/keycloak-ui/pull/3721
https://github.com/keycloak/keycloak/issues/17994

### Version

22

### Expected behavior

I don't really know if this issue is only in the UI or if the duplicate emails boolean is really true but should be false.
If this is only an UI issue then the UI should show the correct state of the "Duplicate emails" feature

### Actual behavior

"Duplicate emails" switch is shown as "On"

### How to Reproduce?

Enable "Email as username" and "Login with email"

**Comment by ssilvert** [comment]
I see this as well.   I'm setting the priority to high for now, but we can lower it when/if determined that it's just a UI bug.

**Comment by manasnisar** [comment]
@ssilvert I see the priority was lowered, maybe reconsider? This is impacting users in production. Allows you to sign up using an already registered email, which results in multiple accounts for the same email in Keycloak and then login doesn't work until you manually purge all duplicates

**Comment by glimberg** [comment]
This issue still persists in 24.0.1

**Comment by jonkoops** [comment]
If this needs to have a higher priority you can upvote the issue, which is what we use to determine priority of community features. The best option here would be to provide a PR to fix the issue, as the team currently has too many other issues on their plate.

**Comment by ssilvert** [comment]
I just verified that this is only a visual thing.  Internally, `duplicateEmailsAllowed` is set correctly to `false`.

Would love a PR if someone has the time to fix it.
