### ISSUE TITLE
The role Unassign button enabled in admin console even if no roles are selected

### ISSUE THREAD

**Issue by ntuveri** [keycloak/keycloak#26375]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The role Unassign button is enabled in user Role Mapping tab of the admin console even if no roles are selected.

### Version

22.0.4

### Expected behavior

The Unassign button is disabled in the Role Mapping view

### Actual behavior

The Unassign button is enabled in the Role Mapping view

### How to Reproduce?

1) Select an existing user with roles already assigned
2) Go to Role Mapping
3) Click the three dots (dropdown) menu and select Unassign 
4) In the pop-up Remove role click on Cancel

**Comment by jonkoops** [comment]
Looks like this issue was reported for an older version of Keycloak. Please ensure this issue is reproducible in the latest version of Keycloak and we will re-open it.

**Comment by ntuveri** [comment]
I was able to reproduce the same issue with the current version 23.0.4.
Please let me know if I can provide further information.

**Comment by agagancarczyk** [comment]
hi @ntuveri Thanks for reporting the issue. Unfortunately, I'm not able to reproduce it with the latest nightly. Could you please provide additional info/steps/screenshots so I can investigate this further? Thanks!

**Comment by ntuveri** [comment]
Hi, please check out the recording below. After canceling the "Unassign" on a single role, the "Unassign" at the top intended to act on multiple roles is active even if no roles are selected.

![Recording 2024-02-01 at 10 20 54](https://github.com/keycloak/keycloak/assets/1021837/26e15232-0f9b-4054-9fdd-647ea5b183e5)

**Comment by agagancarczyk** [comment]
Nice one @ntuveri ! Thank you for providing the video. It's a bug indeed. I'll get it fixed soon.
