### ISSUE TITLE
Ugly error loading a authorization "User" policy that references a user that doesn't exist

### ISSUE THREAD

**Issue by tomqwpl** [keycloak/keycloak#26392]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

Attempting to load an authorization policy that references a user that doesn't exist gives an ugly error in keycloak:

![image](https://github.com/keycloak/keycloak/assets/42344626/06ab6ed0-5fc7-47e8-8caa-bfa91fec0646)

### Version

23.0.4

### Expected behavior

Either that the policy loads and displays with an error, or you get a better error

### Actual behavior

Ugly error as described

### How to Reproduce?

Create a client, enable authorization.
Create a user in the realm.
Create a new "client policy" of type "User". Reference the user in this policy.
Save the policy.
Delete the user.
Attempt to display the policy
Ugly error.

**Comment by ssilvert** [comment]
@tomqwpl This worked for me.  Can you try it on the latest nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
@tomqwpl I'm closing this now.  We can reopen if you still see a problem in the nightly build.
