### ISSUE TITLE
Unexpected redirect URI after authenticate

### ISSUE THREAD

**Issue by LeoQuote** [keycloak/keycloak#26405]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Previously I upgraded key cloak from 11.0 to 23.0, and found a redirect error like #8959 

After my investigation, I found it seems not so simple.

### Version

main

### How to Reproduce?

this bug can be easily reproduced with nightly image, steps are following:
1. setup keycloak server 
2. open network tool in browser, enable persist log to see all requests, filter for HTML only
3. navigate to admin console like `http://localhost:8080/admin/master/console/`
4. login normally

### Expected behavior

keycloak would return a 302 response , redirecting user to a redirect uri that is identical to the uri user provided previously

### Actual behavior

the two redirect uri does not match

the login process would be : 
1. admin console redirect user keycloak login page `http://localhost:8080/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadmin%2Fmaster%2Fconsole%2F&state=361ed6b9-afea-44b9-9f16-86ac91f0f153&response_mode=fragment&response_type=code&scope=openid&nonce=a354386d-d08b-4957-92e8-ae8412ce8130&prompt=none&code_challenge=K41x3hNMzRzLiJt1DZcR6aolGopt7vJi1glMdx_LCbg&code_challenge_method=S256` the url decoded parameter redirect_uri is `http://localhost:8080/admin/master/console/` which is normal
2. user login with authenticate api 
3. keycloak return 302 response with headers
```
HTTP/1.1 302 Found
Cache-Control: no-store, must-revalidate, max-age=0
Location: http://localhost:8080/admin/master/console/#state=21f0e380-1941-40c2-8ba0-66dc710bf106&session_state=78b4fb0f-781f-4686-91e8-58ead1f797ff&iss=http%3A%2F%2Flocalhost%3A8080%2Frealms%2Fmaster&code=b2d3f76c-a0fb-41e4-a39c-eb2ffac51630.78b4fb0f-781f-4686-91e8-58ead1f797ff.a9b337bb-03a1-4b3f-8ec9-fb56c093f909
```

please notice that the Location header contains an URI that connect URI path and parameter with `#` instead of `?`

### Anything else?

After upgrade, I found strange redirect like #8959  in many SPA apps, but none of the backend projects are involved

I also tried to request for a auth with url like `http://localhost:8080/realms/master/protocol/openid-connect/auth?client_id=test&redirect_uri=http%3A%2F%2Flocalhost%3A9090%2F%23%2F&response_type=code` 

notice the redirect_uri is `http://localhost:9090/#/` which contains a `#`

So I'm lost now, I don't know how to trigger this bug preciously.

**Comment by LeoQuote** [comment]
Finally found the problem and solution, this is not a keycloak bug( good news) but a feature , keycloak support setting responseMode when initialize the login process the available responseMode are:
1. Fragment , concat redirect uri and codes etc with a sharp ‘#’ , like : http://myapp/callback#code=123&state=xxx
2. query , using a question mark ‘?’ , like: http://myapp/callback?code=123
3. others 


For SPA apps that using hash mode, the fragment mode could be problematic, resulting a uri like http://myapp/#code=123 , the fragment after sharp would be treated as path and finally reached a 404 page.

# solution
when initializing authentication , set responseMode to query instead of fragment(default value)

Consult to the keycloak adaptor for more info:

https://www.keycloak.org/docs/latest/securing_apps/#api-reference

**Comment by Grawl** [comment]
We use `react-router-dom` 6.26.2 using `createBrowserRouter` (not `createHashRouter`) but still have that issue.
