### ISSUE TITLE
Failed to link identity broker to user with a verified email by IdP email verification flow

### ISSUE THREAD

**Issue by lexcao** [keycloak/keycloak#26418]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

When attempting to link a new broker identity to a user with a verified email, an error occurs stating that the email address has already been verified instead of successfully linking them.

### Version

latest main branch

### Expected behavior

Link successfully after opening the link in the email.

### Actual behavior

Show the error with message
> Your email address has been verified already.

<img width="720" alt="image" src="https://github.com/keycloak/keycloak/assets/14901139/b0342821-4666-498f-91c5-0b79527208b4">

### How to Reproduce?

1. New realm, then setup another realm for IdP
2. Use the default `first-broker-login` flow for IdP
3. Create two users with same **verified** email in both realms
4. Login to the realm by IdP login
5. Confirm link the broker and use email to verification
6. Failed to link with above error

### Anything else?

Seems the #25711 introduced the condition to check the email verification in the action token handler.

https://github.com/keycloak/keycloak/blob/84603a936395e9874658e16017f93cf65a3f0a9e/services/src/main/java/org/keycloak/authentication/actiontoken/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java#L84

How to fix:
* We can add a `VERIFY_EMAIL` required action in the `IdpEmailVerificationAuthenticator` after sending the verification email successfully.

I will prepare the fix.

**Comment by Ketec** [comment]
This problem still persists in 25.0.4

The required action does not fix it  - the account is already verified.

Adding the required action breaks SSO linking - it instead just sends the email verify email, but does not do sso linking anymore.

We even have email verify disabled at a realm level.

**Comment by angelomelonas** [comment]
I also encountered this issue today and it seems like a similar situation to what is described in the comments above:
```
[org.keycloak.events] (executor-thread-330) type="IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR", ..., error="email_already_verified", auth_method="openid-connect", ...
```

Keycloak version 24.05

**Comment by yVolkovHacken** [comment]
I've encountered this problem too, Keycloak version 25.0.1

**Comment by antikalk** [comment]
I have just encountered this problem with Keycloak 26.3.3
