### ISSUE TITLE
"Verify Email" remains in "Required user actions" after the email is verified

### ISSUE THREAD

**Issue by Jakov992** [keycloak/keycloak#26426]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

Due to my project requirements since the user registeres, the server needs to trigger login endpoint(`/realms/{{realm}}/protocol/openid-connect/token`) every 10 seconds regardless if the user verified his email or not.

After the user clicks on the email verifications link, sometimes(maybe once in a few times) it happens that the "Verify email" is left inside "Required user action" and because of that, the login endpoint gets the following error:
```
{
    "error": "invalid_grant",
    "error_description": "Account is not fully set up"
}
```
This is the image:
![image](https://github.com/keycloak/keycloak/assets/26843152/ff820f8b-443b-4f1f-b78b-0033d01b0756)

### Version

23.0.0

### Expected behavior

Required user actions should be empty and the user can login normally.

### Actual behavior

Required user action is filled with "Verify email" and user cannot login(gets the "invalid_grant" error).

### How to Reproduce?

1. Register the user and don't click on the email verification link
2. Start the script that calls the `/realms/{{realm}}/protocol/openid-connect/token` every 0.1 seconds(in my case is 10 seconds, but it is easier the reproduce with 0.1 seconds)
3. Click on the email verification link
4. "Verify Email" is still present in the "Required user actions"

**Comment by pedroigor** [comment]
Thanks. I don't see the script/reproducer you mention in the description attached to the issue.

~missing-information

**Comment by pedroigor** [comment]
~missing-info

**Comment by maucodev** [comment]
I had the same issue and I realized that the problem was in the "Required user actions" field, which needs to be empty.

<img width="791" alt="image" src="https://github.com/keycloak/keycloak/assets/9170386/787041eb-3185-4c06-a9d3-8469921d4d3d">

**Comment by ranaahsanansar** [comment]
I was also facing the same issue. But i realised the first and last name of my user is not set,  Keycloak allowed me to login after setting first and last name of the user

![Screenshot from 2024-10-24 12-17-40](https://github.com/user-attachments/assets/4501e89c-17a7-41db-823b-4ab17418e900)

**Comment by giolvani** [comment]
@ranaahsanansar  it worked for me as well! Weirdly, it has no obligation on the form but there is for login.

**Comment by AlexBurdu** [comment]
The missing First and last name was the reason in my case as well. This is very confusing.
