### ISSUE TITLE
Implement stricter controls at token endpoint for PKCE verification

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#26430]
### Description

We have identified a need to improve security measures at the token endpoint. The specific improvement suggested is to introduce stricter controls for handling PKCE (Proof Key for Code Exchange) data. 

It is proposed that an error be generated when a code verifier is provided, but it is not accompanied by the corresponding PKCE data. This measure aims to ensure that each code verifier is properly validated with its associated PKCE data, thereby reinforcing the security at the token endpoint.

Original idea proposed by @pedroigor 

### Motivation

Enhance the security of the token endpoint

**Comment by abstractj** [comment]
@keycloak/core created the following enhancement based on our discussions.

**Comment by jonkoops** [comment]
Adding this to 24 to force a discussion, feel free to bump it to 25, but this looks like it could be a quick win.

**Comment by rmartinc** [comment]
@pedroigor @mposolda I've been looking to his a bit and I think that we already have a client policy that enforces PKCE: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/executor/PKCEEnforcerExecutor.java

For what I see it ensures that the pkce is enabled to S256 in creation/update, that in the authorization request contains the pkce params and are valid,... So I think that is complete and OK. It is already part of some fapi profiles created by default in realms but not policy is created right now for new realms.

Maybe we need to think more what we want to do with this policies. Create one or more policies at realm creation time? Automatically assign some profiles to them?

**Comment by sschu** [comment]
@rmartinc You could of course use a policy to enforce PKCE. The idea here is to improve the situation if PKCE is not mandatory but the client chose to use it: When only the code verifier is passed but the rest is missing, this is an indicator of a downgrade attack. This should be prevented.

**Comment by rmartinc** [comment]
Thanks @sschu! Yes, I had understood it incorrectly. This is about implementing the recommended security practices about [pkce downgrade attack](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-16.html#name-pkce-downgrade-attack). I created a simple test and it's true that the downgrade attack is passing OK. Working to fix it.
