### ISSUE TITLE
Keycloak cannot run on windows machine in dev-mode. Because non-English systems cannot support keycloak's package's.

### ISSUE THREAD

**Issue by tolga-karabudak** [keycloak/keycloak#26438]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

![image](https://github.com/keycloak/keycloak/assets/67536491/ec61c114-f845-41c6-9266-7890e89c8068)

When i change the system language problem solved. But I think that is not a proper solution.

### Version

23.0.4

### Expected behavior

To start a keycloak dev server.

### Actual behavior

ERROR: No enum constant org.keycloak.common.Profile.ProfileValue.COMMUNİTY

COMMUNITY is not the package that keycloak's looking for.

### How to Reproduce?

When i change system language in windows. Command Prompt's language changed and problem solved. But I think that's not a proper way.

### Anything else?

Thank you for support.

**Comment by jonkoops** [comment]
This issue was reported for an older version of Keycloak, as per our policy stated in the issue template we only accept bug reports tested against the latest version. If this problem is reproducible in the latest version, feel free to log a new issue.

**Comment by tolga-karabudak** [comment]
I updated the version same problem accured.
![image](https://github.com/keycloak/keycloak/assets/67536491/3a9574bf-861e-469a-afeb-9d60551fc8b9)

**Comment by tolga-karabudak** [comment]
Also still, when I change system language to en-US it works properly but in Turkey, capital words are problem.

**Comment by jonkoops** [comment]
Thanks for testing that @tolga-karabudak, I'll re-open the issue.

**Comment by tolga-karabudak** [comment]
Thanks for fast response @jonkoops :)

**Comment by mposolda** [comment]
I consider this related to the distribution, so switching to cloud-native team for triage this.

**Comment by stianst** [comment]
We had an enum ProfileValue a long time ago, but that has been removed, so I honestly can't see how this error message can be coming from the latest release.

**Comment by Pepo48** [comment]
@shawkins here's the stack trace:
![image](https://github.com/keycloak/keycloak/assets/12138171/eaf4ca3f-5c21-41fb-a3c4-3e96cbbba2ea)

**Comment by shawkins** [comment]
@Pepo48 oh, so it's not the reading of the values from the filesystem in this case, but the usage of toUpperCase - https://github.com/keycloak/keycloak/blob/b1a6a5a1b0e228e59d85a000240e39f13cd5446d/services/src/main/java/org/keycloak/theme/ClasspathThemeProviderFactory.java#L115 - the toUpperCase javadoc not coincidentally calls out Turkish. 

It seems like we would have a lot places to check for things like upper/lower case, comparison/sorting, and any readers that may be using the system charset and could affect assumptions we're making. I know the profile logic at least does similar upper and lower conversions.

**Comment by Pepo48** [comment]
@shawkins correct, I already tried some quick fixes like `Theme.Type type = Theme.Type.valueOf(t.toUpperCase(Locale.ENGLISH));`, which made me able to surpass the point. But as you mentioned, it failed immediate at another place:
```
Caused by: java.util.concurrent.ExecutionException: org.infinispan.commons.CacheConfigurationException: ISPN000327: Cannot find a parser for element 'cache-container' in namespace 'urn:infinispan:config:14.0' at [25,41]. Check that your configuration is up-to-date for Infinispan '14.0.24.Final' and you have the proper dependency in the classpath
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.keycloak.quarkus.runtime.storage.legacy.infinispan.CacheManagerFactory.getOrCreate(CacheManagerFactory.java:72)
```
I'm debugging it further.

**Comment by vmuzikar** [comment]
I wonder if we should just set `LC_ALL=en_US.UTF-8` in kc.sh|bat. There might be some side effects but I think local can be set on Realm level?

**Comment by Pepo48** [comment]
@vmuzikar I tried it but without the luck. I guess it's because `LC_ALL=en_US.UTF-8` is unix-like notation. The Windows equivalent would the system setting I already tried and mentioned above:
> enable the "Beta: Use Unicode UTF-8 for worldwide language support" feature
![image](https://github.com/keycloak/keycloak/assets/12138171/a7c9f16f-cc0b-42d9-949c-ea0e772100d7)

It changes the representation of the character compared to previous console output, but not in a desired way. 
![image](https://github.com/keycloak/keycloak/assets/12138171/21c5089c-b24a-491c-9034-d54739acc449)

**Comment by Pepo48** [comment]
Guys, I was actually able to workaround it by setting the English locale on a JVM level:
![image](https://github.com/keycloak/keycloak/assets/12138171/9cd332f3-b141-4aae-9db7-1b9f7e96af1d)

I did the following:
```
chcp 65001 # to make sure I work with UTF-8 in an active console window
set "JAVA_OPTS=-Duser.language=en -Duser.country=US # to set the English locale via JVM options
```
(while the worldwide language support feature enabled on the system level)

@tolga-karabudak could you try the above mentioned in your environment?

cc: @shawkins @vmuzikar

**Comment by tolga-karabudak** [comment]
@Pepo48 Thanks for all of that! I'll try and comment my stack tree.

cc: @shawkins @vmuzikar

**Comment by vmuzikar** [comment]
@tolga-karabudak Thanks for the confirmation. Glad it works now.

@Pepo48 Re-opening as we probably want to include this in kc.sh/bat.

**Comment by vmuzikar** [comment]
Given the nature of the fix and a risk of regression, we won't be backporting this for now.
