### ISSUE TITLE
Customer not receiving code for Singlekey

### ISSUE THREAD

**Issue by Chrissibreeee** [keycloak/keycloak#26433]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

robs@nusourcefinancial.com not receiving code to verify email after creating a singlekey account serviceportal.boschsecurity.com

### Version

single key serviceportal.boschsecurity.com

### Expected behavior

 customer is supposed to receive an email with a code

### Actual behavior

 customer is not receiving a code

### How to Reproduce?

not sure

### Anything else?

 no

**Comment by jonkoops** [comment]
This issue report does not have enough information or a minimal reproducible example, so I am closing it. This sounds like a Bosch-specific issue, so I will redirect you to @sschu.
