### ISSUE TITLE
Custom attributes not showing on user personal info page

### ISSUE THREAD

**Issue by michael-82** [keycloak/keycloak#26446]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

I want to use the declarative_user_profile feature to allow users to set an attribute for themselves. Following [this guide](https://www.keycloak.org/docs/latest/server_admin/#user-profile) I enabled the feature and it is correctly showing up. As an admin, I can also correctly modify that value - but it does not show on the user page.

The attribute as configured via realm settings:

![image](https://github.com/keycloak/keycloak/assets/21363657/bd7367f8-5227-43fc-a089-eec6ad54036f)

The userpage as admin:

![image](https://github.com/keycloak/keycloak/assets/21363657/129a31f1-7892-46eb-a004-16ed1b1dd1e6)

The profile page as the user himself:

![image](https://github.com/keycloak/keycloak/assets/21363657/038fb490-4aee-42f5-aeaf-c8428be78683)

### Version

23.0.4

### Expected behavior

When the user logs into the user profile page, the attribute should be there and be modifiable by the user.

### Actual behavior

The attribute is not showing on the user profile page

### How to Reproduce?

1. Start up keycloak via docker from quay.io/keycloak/keycloak:23.0 with "--features=declarative-user-profile"
2. Create a realm and switch "User Profile Enabled" to on
3. Go to "User profile"
4. Click "Create attribute"
5. Enter a name for the attribute and check all boxes under "Permission"
6. Click "Create"
7. Create a user (you should already see the attribute created in the steps before) and assign some credentials to him
8. Logout (or use another browser or incognito mode) and navigate to /realms/your-realm/account
9. Login with the user you created
10. Go to "Personal info" - the attribute is missing

### Anything else?

Modifying the existing attributes (first name, last name, email) is working fine

**Comment by jonkoops** [comment]
This is working as intended, version 2 of the Account Console does not have support for declarative user profile. You will have to enable version 3 of the Account Console to get this working.

**Comment by michael-82** [comment]
I enabled all preview features now - the problem is still the same

![image](https://github.com/keycloak/keycloak/assets/21363657/c134c7ee-a157-4fc8-978c-16e012beb930)

**Comment by jonkoops** [comment]
@edewit are these features not in 23? Are we only pushing them in 24?
