### ISSUE TITLE
Full DB config provided from k8s secret in Keycloak CRD

### ISSUE THREAD

**Issue by dejwsz** [keycloak/keycloak#26449]
### Description

Already added here: https://github.com/keycloak/keycloak-k8s-resources/issues/19, in the Keycloak CRD in "db" section we can add only user and password for db from a secret, the rest values must be hardcoded. It would be good to have an option to provide full config from a secret as a whole or for every individual config key as it is now for username or password.

### Motivation

Make the deployment more dynamic in regard to DB settings.

### Details

Like there is now in Keycloak's CRD "db" section "usernameSecret" it can be also "externalDbSecret" with only the name where operator can expect strictly defined keys. Other way would be adding the option to give all values for "db" section as references to secrets or configmaps.

**Comment by dejwsz** [comment]
By the way, any ENV "KC_DB_..." variables set in "unsupported" -> "podTemplate" do not help here. Keycloak CRD assumes values only from "db" section and if they are missing, dummy ones or wrong then Keycloak instance does not start.

**Comment by danielloader** [comment]
Yeah this is actually quite the blocker when trying to deal with Aiven Operator or Crossplane RDS compositions or anything where the host name comes dynamically from the managed cloud resource at deployment time.

Would be good to be able to source any/all the fields from a secret:
- URI (full connection string)
- port
- host
- username
- password
- database name

You would also need to retain the key mapping options for each as every operator/secret layout has different key names evidently.

**Comment by danielloader** [comment]
A small work around but your mileage may vary...

You could deploy an external dns service pointer in the namespace so you have a reliable CNAME to resolve in the config... but it doesn't change the port being unknown at deployment time.

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.database.example.com
```

**Comment by shawkins** [comment]
> By the way, any ENV "KC_DB_..." variables set in "unsupported" -> "podTemplate" do not help here. Keycloak CRD assumes values only from "db" section and if they are missing, dummy ones or wrong then Keycloak instance does not start.

@dejwsz on main / 23 the priority order for env values is unsupported, first class (from the proper fields of the cr), then additionalOptions. If you think that you are seeing a different resolution order for the env, please open another issue.

So on this issue it is expected that you can use the unsupported for this. It is also possible to leave the fixed spec.db fields blank and use additionalOptions instead.

**Comment by greyarch** [comment]
+1

**Comment by vmuzikar** [comment]
Thanks for opening this RFE. We support referencing Secrets in the CR for fields we consider security sensitive, like credentials. We do not support referencing Secrets for all fields. This would introduce additional complexity, and even other K8s resources do not support this.

I'm going to reject this. @shawkins Feel free to reopen if you think otherwise.

**Comment by shawkins** [comment]
@vmuzikar It seems like users have a couple of unsupported options to achieve this, so this is probably a low priority regardless.

Quarkus does support the concept of a kubernetes secret or configmap configsource, which we could try to accomodate in the server / operator - but that seems like more work than we'd want to do as we'd want to just map to one of the existing configuration options instead.
