### ISSUE TITLE
Remove support for multiple AUTH_SESSION_ID cookies

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#26457]
### Description

Before Keycloak 4 paths for cookies didn't have a trailing '/', this lead to an issue in IE11 (and earlier) browsers that would send 

### Motivation

Simplify and improve code quality

**Comment by Swasthik-S-Nettar** [comment]
Hi @stianst 
The description of this is not giving a proper insight on why this change was required. Could you please let us know, the reason for this change in a detailed format.

Thank You!
