### ISSUE TITLE
"Test connection" on LDAPS URI does not test TLS handshake

### ISSUE THREAD

**Issue by breakwaterlabs** [keycloak/keycloak#26464]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When creating an LDAP federation in the web interface, there is a `Test Connection` button. However, this button only checks for a TCP handshake and tests neither the transport layer (TLS) nor the application layer. This can be seen when watching a packet capture on the backend LDAP server; whether using LDAP, LDAP with StartTLS, or LDAPS, keycloak only initiates a TCP handshake and then ends with a FIN ACK.

As a result, `Test Connection` will incorrectly report a functioning connection over URIs that would obviously fail at the transport level, such `ldaps://localhost:8080` (the keycloak HTTP interface).

Further, the `Test Authentication` button operates inconsistently. When a valid user is provided, it attempts to perform a handshake on TCP, security layer, and LDAP-- unless the settings are StartTLS with Truststore SPI set to Always, in which case it only performs a TCP handshake and disconnects.

### Version

22.0.5

### Expected behavior

1. `Test Connection` should validate TLS and StartTLS settings as part of the connection.
	- To confirm connectivity up to the application level, an anonymous LDAP bind should be attempted. Any LDAP response should be considered a success.
2. `Test Authentication` with bind type `none` should attempt an anonymous bind
3. `Test Authentication` should always attempt an LDAP bind and should always respect TLS / StartTLS settings

### Actual behavior

1. `Test Connection` only performs a TCP handshake and ignores TLS and startTLS settings
2. `Test Authentication` with bind type `none` only attempts a TCP connect, disregarding TLS settings
3. `Test Authentication` with bind type `simple`, StartTLS on and Truststore SPI set to Always only attempts a TCP connect and does not respect StartTLS settings or attempt a bind

### How to Reproduce?

In my testing, I did not set up trust for the LDAP TLS CA. This is not necessary as the incorrect behavior occurs before TLS verification would occur, and the lack of trust makes it easier to see in the Web UI what is actually happening.

| Environment | . |
| ---- | ---- |
| Keycloak Version | 22.05 (docker) |
| Keycloak Database | Postgres15 (docker) |
| LDAP Hostname | ldap.lab.local |
| Keycloak Hostname | keycloak.lab.local |
| Other | Keycloak does NOT trust LDAPS CA |

 1. Install and run a live packet capture on the LDAP server with filter 'host keycloak.domain.local'
 2. Verify normal packet patterns for ldap connection:

| Test | Command | Packet Capture |
| ---- | ---- | ---- |
| Plain LDAP | `ldapsearch -H ldap://ldap.lab.local:389 -s oneLevel "(cn=conn_test)"` | TCP handshake, LDAP response |
| LDAPS wrong port | `ldapsearch -H ldaps://ldap.lab.local:389 -s oneLevel "(cn=conn_test)"` | TCP Handshake, TLS handshake failure |
| LDAP StartTLS | `ldapsearch -Z -H ldap://ldap.lab.local:389 -s oneLevel "(cn=conn_test)"` | TCP Handshake, StartTLS issued |
| LDAPS correct port | `ldapsearch -H ldaps://ldap.lab.local:636 -s oneLevel "(cn=conn_test)"` | TCP Handshake, TLS handshake |

3. Create a new realm, and begin creating a new LDAP federation. Set Bind Type to 'none' and run both `Test Connection` and `Test Authentication`:

| Test               | URL | StartTLS                                                                  | Keycloak UI result    | Packet Capture                          |
| ------------------ | --- | ------------------------------------------------------------------------- | --- | ------------------------------- |
| Plain LDAP         | ldap://ldap.lab.local:389    | false                                                                          | Successfully connected to LDAP    | TCP handshake    |
| LDAPS wrong port   | ldaps://ldap.lab.local:389    | false   | Successfully connected to LDAP    | TCP handshake      |
| LDAP StartTLS      | ldap://ldap.lab.local:389    | True | Error when trying to connect to LDAP: 'UnknownError'    | TCP handshake |
| LDAPS correct port | ldaps://ldap.lab.local:636    | False   | Successfully connected to LDAP    | TCP handshake    |

4. Change Authentication type to 'simple' and provide a valid LDAP user. Test the `Test Authentication` button.

| Test | URL | StartTLS | Trust SPI | Keycloak UI result | Packet Capture |
| ---- | ---- | ---- | ---- | ---- | ---- |
| Plain LDAP | ldap://ldap.lab.local:389 | false | Any | Successfully connected to LDAP | TCP handshake, LDAP query |
| LDAPS wrong port | ldaps://ldap.lab.local:389 | false | Any | 'Socket Reset' | TCP handshake, TLS Handshake |
| LDAP StartTLS SPI Always | ldap://ldap.lab.local:389 | True | Always | 'UnknownError' | TCP handshake |
| LDAP StartTLS SPI Never | ldap://ldap.lab.local:389 | True | Never | 'SSL Handshake Failed' | TCP handshake, StartTLS |
| LDAPS correct port | ldaps://ldap.lab.local:636 | False | Any | 'SSL Handshake Failed' | TCP handshake, TLS handshake |

### Anything else?

The positioning of the `Test Connection` button is problematic because it's position below the StartTLS and TrustStore settings imply that it will test those settings as well, but it does not.

The fact that these buttons exist but perform inconsistently makes troubleshooting exceptionally difficult because there is no single way to validate only the lower layers and then validate only the authentication settings.

EDITED to add numbering on expected / actuals to simplify referencing the pieces of this issue.

**Comment by jonkoops** [comment]
I see this issue was reported for an older version of Keycloak than the current stable version. Please verify that this issue is reproducible in the latest version of Keycloak.

Re-labeling this to a core issue, as the UI does not control what the API does.

**Comment by breakwaterlabs** [comment]
This is reproducible in 23.0.3, which is the current latest container image on quay.io.

**Comment by jonkoops** [comment]
Thanks for confirming that @breakwaterlabs 👍

**Comment by breakwaterlabs** [comment]
@rmartinc posting this here and on PR for visibility. I updated the original posting to number the expected / actuals to simplify discussion.

Your PR appears to address case 2: using `Test Authentication` with authentication set to none only performing a TCP connect.

This would still leave cases 1 (`Test Connection` needs to check TLS etc) and case 3 (`Test Authentication` with simple, startTLS, and SPI Truststores = always only performs TCP connect), however I think it is a good start as it would certainly provide better feedback than what exists now.

**Comment by rmartinc** [comment]
Hi @breakwaterlabs!

> So part of this would involve fixing the following:
>    Testing with LDAPS should attempt TCP connect + TLS handshake (Current: TCP Connect only)
>   Testing with LDAP + StartTLS should attempt TCP connect + LDAP extendedReq LDAP_START_TLS_OID + TLS handshake (Current: TCP Connect only)

I think that is what we are doing now. Test connection now with my ldap:

URL: ldaps://localhost:10636
StartTLS: false
Use Truststore SPI: Never
Result: Error when trying to connect to LDAP: 'SSLHandshakeFailed'

URL: ldap://localhost:10389
StartTLS: true
Use Truststore SPI: Never
Result: Error when trying to connect to LDAP: 'SSLHandshakeFailed'

So TLS is always tested in test connection. If StartTLS is ON, it sends the extended operation. The line that sends the extended op is [here](https://github.com/keycloak/keycloak/blob/23.0.5/federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/store/ldap/LDAPContextManager.java#L88-L90).

> I would additionally suggest that plain LDAP should also be validated on L1-7 by doing a TCP handshake followed by an LDAP searchRequest "<ROOT>" baseObject. I would use as a model what occurs when issuing ldapsearch -H ldap://my_dc.lab.local :389 -s oneLevel "(cn=connection_test)".

As I commented in the previous comment, LDAP can be configured to not allow anonymous access. And the base root can also be protected. For example with apache-ds:

```
ldapsearch -x -H ldap://localhost:10389 -b "" -s base objectclass=*
ldap_bind: Invalid credentials (49)
	additional info: INVALID_CREDENTIALS: Bind failed: ERR_229 Cannot authenticate user
```

So, I think we cannot test ldap in test connection. We test ldap once the authentication is setup in test authentication.

Regarding the error we are returning the error depending the exception ([here](https://github.com/keycloak/keycloak/blob/23.0.5/federation/ldap/src/main/java/org/keycloak/services/managers/LDAPServerCapabilitiesManager.java#L80-L113)). We can create another message for each exception but we need to rely on the exception thrown by java.

**Comment by breakwaterlabs** [comment]
There may be a disconnect here, because in my container instance (latest from quay.io=23.0.3), I configure ldap URI = `ldaps://myDC.lab.local:88` (the kerberos port, TLS on) and I get "Successfully connected to LDAP".

Likewise, with `ldap://myDC.lab.local:88` with startTLS, I again get "successfully connected....", and with LDAPS... and startTLS on, I get "authenticationFailure".

I would refer you to the packet captures from above-- those were run just a few days ago on fresh instances. Is it possible you are using a modified or nightly instance? I cannot induce "Test Connection" to produce a "SSLHandshakeFailed" -- or even a TLS handshake at all, according to wireshark.

As for the discussion on base root-- getting an "INVALID_CREDENTIALS" back would, in my view, validate the entire L1-L7 connection, which I have always understood was the point of a Test Connection. We can count any LDAP response at all-- as a success, because it demonstrates that there is an LDAP server on the other end and that we can connect to it. And in fact you cannot get away from attempting some form of LDAP conversation, because testing a startTLS setting requires it.

Consider if we were dealing with SMTP software. Typically an SMTP connection test would involve testing
 - Can we get a TCP handshake
 - Can we establish TLS, if indicated
 - Can we issue and receive a HELO

This would not attempt an AUTH, but a success message here would indicate that any problems sending mail were problems further up the application stack, and not related to protocol-, transport-, or network- level problems.

**Comment by breakwaterlabs** [comment]
Apologies for the double comment, but this is to consolidate discussion from #26662.

I believe there was some confusion / disagreement about whether Test Connection initiated TLS connections, so I did some testing in an entirely disconnected environment from where I initially filed this bug-- different container engine, different host OS, different network.

`docker run --name=keycloak -p 8082:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=<password> quay.io/keycloak/keycloak:23.0.5 start-dev`

Logged in, and configured LDAP, changing only these settings:

| Key | Value |
| ---- | ---- |
| Connection URL | `ldaps://1.1.1.1:80` |
| Bind type | none |
| Edit mode | READ_ONLY |
| Users DN | CN=None,DC=lab,DC=local |

Launch Wireshark, monitoring the Docker0 interface, and press "Test Connection".

Results:
![image](https://github.com/keycloak/keycloak/assets/9223149/f388c39d-e45c-4257-b4ab-fc7b8947b7fa)

![image](https://github.com/keycloak/keycloak/assets/9223149/a1c0b491-c5b3-41c9-bffe-6fb0ee851a00)

The Cloudflare page at http://1.1.1.1:80 does not have a TLS certificate, and cannot do a TLS handshake, so `test connection` should never succeed against it. The packet capture also shows that it is not doing a TLS handshake; compare to what is sent when using openssl `openssl s_client 1.1.1.1:80`:

![image](https://github.com/keycloak/keycloak/assets/9223149/06fbce12-b387-4f93-9bf2-0447dc6d121b)

The openssl performs the TCP Handshake, attempts TLS (`PSH ACK`), and finally fails and issues its `FIN, ACK`. Keycloak does not do that, and simply proceeds from a TCP handshake straight into a `FIN, ACK`.

**Comment by rmartinc** [comment]
Hi @breakwaterlabs!

I don't know what to say here. I'm doing your cases with 23.0.5 (last version).

In case 1 my result is the message: Error when trying to connect to LDAP: 'CommunicationError'.

![Screenshot from 2024-02-01 09-05-46](https://github.com/keycloak/keycloak/assets/26901232/d3e2a9f9-0c98-4ddc-8936-abea4644f6fa)

The wireshark if I change decode as TLS shows the hello:

![Screenshot from 2024-02-01 09-07-54](https://github.com/keycloak/keycloak/assets/26901232/b73d64ab-64c6-4a16-9b3d-a0d41c45de61)

And there is an exception showing the lines in which the test is performing a connection and a TLS handshake:

```
2024-02-01 09:03:32,553 DEBUG [org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager] (executor-thread-3) Creating LdapContext using properties: [{java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.provider.url=ldaps://1.1.1.1:80, com.sun.jndi.ldap.connect.timeout=20000, java.naming.security.authentication=none, java.naming.ldap.factory.socket=org.keycloak.truststore.SSLSocketFactory}]
2024-02-01 09:03:32,570 ERROR [org.keycloak.services] (executor-thread-3) KC-SERVICES0055: Error when connecting to LDAP: 1.1.1.1:80: javax.naming.CommunicationException: 1.1.1.1:80 [Root exception is javax.net.ssl.SSLException: Unsupported or unrecognized SSL message]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:253)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
	at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
	at org.keycloak.services.managers.LDAPServerCapabilitiesManager.testLDAP(LDAPServerCapabilitiesManager.java:139)
	at org.keycloak.services.resources.admin.TestLdapConnectionResource.testLDAPConnection(TestLdapConnectionResource.java:93)
	at org.keycloak.services.resources.admin.TestLdapConnectionResource$quarkusrestinvoker$testLDAPConnection_53600405a1d6ba020ad8536bd54994b827f01e74.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:365)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:232)
	... 28 more
```

Your case 3 is a bit misleading because StartTLS just makes sense with ldap (not ldaps). So your case 3 is doing exactly the same that case 1. It connects to a non TLS port, in my env it returns the same CommunicationError and it does not reach the point when the connection is established, so no sending the extended op (which probably would fail because it was already using TLS). So in my env this case 3 is exactly the same than case 1 (same images).

I don't know what's the difference, maybe the environments. But I'm also testing a direct connection against my localhost with an ldap server installed locally. I would suggest to test locally too with keycloak 23.0.5.

**Comment by rmartinc** [comment]
@breakwaterlabs Wait! I think the difference is the connection timeout parameter. If I don't set any value I see your behavior. Let me check what java is doing here.

**Comment by rmartinc** [comment]
Yes, it was the connection timeout. I always configure the provider with timeouts and the timeout make the connection to be established. If there is no timeout, it waits til the first interaction, and, as in the test connection no request is sent, it does nothing. Sorry, but I always had the timeout set.

So I'm going to close the previous PR and send a new one with two changes:

1. Force an anonymous bind when none. The previous change.
2. In the tests always set a connection/read timeout. This is useful for several reasons, it does not wait forever, it forces the connection to be established,... For this point we can also change to force timeouts by default. I prefer to always sets timeouts and, if the admins want, they can put -1 to put infinite timeout. But this a change in current configurations so I prefer to maintain this (and this can be discussed in the PR with other folks and reviewers).

I think with this all issues are fixed. Thanks @breakwaterlabs for testing this so deep.

**Comment by breakwaterlabs** [comment]
Thanks for chasing this down-- thats one truly devious bug, and I'm glad we're getting this documented / addressed. I can imagine this making someone question their sanity.
