### ISSUE TITLE
SPI-truststore-file-type option appears to be invalid

### ISSUE THREAD

**Issue by breakwaterlabs** [keycloak/keycloak#26468]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The documentation ([Keycloak](https://www.keycloak.org/server/keycloak-truststore), [Red Hat](https://access.redhat.com/documentation/en-us/red_hat_build_of_keycloak/22.0/html/server_guide/keycloak-truststore-)) references a `spi-truststore-file-type` option:

```
spi-truststore-file-type
The type of truststore, such as jks, pkcs12 or bcfks. If not provided, the type would be detected based on the truststore file extension or platform default type.
```
However, none of the examples use this option, and a [repository code search](https://github.com/search?q=repo%3Akeycloak%2Fkeycloak%20spi-truststore-file&type=code) for `spi-truststore-file` shows that the only options referenced by code are:

 - spi-truststore-file-file
 - spi-truststore-file-password
 - spi-truststore-file-hostname-verification-policy

### Version

N/A

### Expected behavior

The documentation should only reference valid options. If the type option is valid, an example should be provided showing it in use. If only jks keystores are supported, that should be made clear.

Additionally, the documentation does not indicate whether these SPI options are supported by environmental variables in container deployments (e.g. `KC_SPI_TRUSTSTORE_FILE_FILE`).

### Actual behavior

The documentation apparently does not match the implementation.

### How to Reproduce?

See https://github.com/search?q=repo%3Akeycloak%2Fkeycloak%20spi-truststore-file&type=code.

### Anything else?

The SPI truststore options are [apparently being deprecated in 24.x](https://github.com/keycloak/keycloak/blob/d23383e79ccf0604e72d627cd6a03893b1bfcc77/docs/documentation/upgrading/topics/keycloak/changes-24_0_0.adoc#truststore-changes), however this is still relevant as it affects the current version.

Additionally, that change note references the documentation link above, which as of [current main](https://github.com/keycloak/keycloak/blob/main/docs/guides/server/keycloak-truststore.adoc) does not indicate whether a type option is necessary or exists.

**Comment by shawkins** [comment]
> However, none of the examples use this option, and a [repository code search](https://github.com/search?q=repo%3Akeycloak%2Fkeycloak%20spi-truststore-file&type=code) for spi-truststore-file shows that the only options referenced by code are:

The spi code eventually uses a a relative name to reference the options that it is using. This is where type is referenced: https://github.com/keycloak/keycloak/blob/efa6ddc41ea58b6f7a78265ae614ea852b64fe43/services/src/main/java/org/keycloak/truststore/FileTruststoreProviderFactory.java#L78

> The documentation should only reference valid options. If the type option is valid, an example should be provided showing it in use. If only jks keystores are supported, that should be made clear.

Not only jks keystores are supported. If type is provided, it will be used. If it is not provided the logic can detect one of jks, p12, bcfks, or the system default.

> Additionally, the documentation does not indicate whether these SPI options are supported by environmental variables in container deployments (e.g. KC_SPI_TRUSTSTORE_FILE_FILE).

That is expected to work. At runtime the spi config is backed by the microprofile config which can resolve these env variables. You could submit a pr to have that called out specifically on https://www.keycloak.org/server/configuration-provider or https://www.keycloak.org/server/configuration

> Additionally, that change note references the documentation link above, which as of [current main](https://github.com/keycloak/keycloak/blob/main/docs/guides/server/keycloak-truststore.adoc) does not indicate whether a type option is necessary or exists.

The doc is clear "If not provided, the type ..."  that the type option is optional.

**Comment by vmuzikar** [comment]
@shawkins Yeah, might be a good idea to add a short note around SPI config using env vars [here](https://www.keycloak.org/server/configuration-provider). At the same time, we should not duplicate too much the [generic config guide](https://www.keycloak.org/server/configuration) that describes formats for individual config sources already.

**Comment by shawkins** [comment]
> At the same time, we should not duplicate too much the [generic config guide](https://www.keycloak.org/server/configuration) that describes formats for individual config sources already.

I think part of the complaint is that it doesn't explcitily mention spi options there either.

**Comment by shawkins** [comment]
Perhaps #26648 is sufficient to resolve this.
