### ISSUE TITLE
When Enabling 'Offline Session Max Limited', Token Expires Prematurely

### ISSUE THREAD

**Issue by codyharris-h2o-ai** [keycloak/keycloak#26477]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Within 'Realm settings', 'Sessions', 'Offline session settings':

When 'Offline Session Max Limited' is enabled, the behaviour appears to have changed somewhere between version 11 and 22/23.  Issued tokens how have an `exp` claim in them, and expire at the configured "Offline Session Idle" regardless of usage.  ie, setting "Offline Session Idle" to 7 days, and "Offline Session Max" to 30 days, and using the token daily, would mean that the token is valid until day 30, after which it is no longer valid.

I woul

### Version

23.0.4

### Expected behavior

* When "Offline Session Max Limited" is set, issued offline refresh tokens have an `exp` claim calculated based on "Offline Session Max" not "Offline Session Idle"
* When "Offline Session Max Limited" is set, and token is used within the "Offline Session Idle", the lifespan of the token is reset, and is accepted until the "Offline Session Max" is reached.

### Actual behavior

* When offline token is issued, and "Offline Session Max Limited" is set, issued token contains an `exp` claim seemingly calculated based on "Offline Session Idle"

### How to Reproduce?

1. Set "Offline Session Idle" to 5 minutes
2. Set "Offline Session Max Limited" to Enabled
3. Set "Offline Session Max" to 30 minutes
4. Use Postman or similar to acquire an offline token
5. Perform token exchanges every minute using the original offline token
6. Observe that after minute 5, the token is rejected with:

```
{
    "error": "invalid_grant",
    "error_description": "Token is not active"
}
```

Also manually inspect the original issued offline token, taking note of the expiration time, I have included a sample in this report.

### Anything else?

A sample decoded token, note the delta between `exp` and `iat`

```
{
  "exp": 1706133555,
  "iat": 1706133255,
  "jti": "13300fe5-56e9-42d4-b7e8-16a8e3272e91",
  "iss": "http://example.com/auth/realms/example",
  "aud": "http://example.com/auth/realms/example",
  "sub": "4b5a2a28-190c-4ac3-9ab3-327283af9c28",
  "typ": "Offline",
  "azp": "example-client",
  "session_state": "e6d922b0-92e9-4236-83bf-f1a44d6c1c09",
  "scope": "offline_access email profile",
  "sid": "e6d922b0-92e9-4236-83bf-f1a44d6c1c09"
}
```

**Comment by y-tabata** [comment]
According to the above expected behavior, offline tokens have an exp claim calculated based on "Offline Session Max," but expired before their exp claims due to "Offline Session Idle," right?
This behavior is complicated, so IMO the exp claim value of an offline token and the actual expiration of the offline token should be the same (it is current behavior).

**Comment by sschu** [comment]
I think this works exactly as designed. When exchanging an offline token, you get a new one that again has exp=currenttime+offline session idle (or session creation time+offline session max, if this is smaller). This basically works the same as for normal refresh tokens. Their expiry is also bound to the session idle times. You need to use your refresh token to get a new one within the idle times, otherwise the session will expire.

**Comment by zoido** [comment]
> I think this works exactly as designed. When exchanging an offline token, you get a new one that again has exp=currenttime+offline session idle (or session creation time+offline session max, if this is smaller). 

Documentation does not seem to mention it https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-access. 

> You must use the offline token for a refresh token action at least once per thirty days or for the value of the [Offline Session Idle](https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-session-idle).

How I read is that the session idle is bound to the session not the token. 

And AFAIK this behavior we observe changed between somewhere v15 an v22.

**Comment by sschu** [comment]
@zoido It works like I mentioned for normal tokens so the behaviour is just the same with offline tokens. The reason it works like that is also that you know before which time you have to do another refresh. This information is returned when getting the offline token in the response and in sync with the offline token exp claim. Otherwise you would have to store state to keep this information.
What is stopping you from just using the new refresh token that you retrieve?

**Comment by zoido** [comment]
> What is stopping you from just using the new refresh token that you retrieve?

Usually inability to alter the original offline token. Like workloads having read-only access to the secret. I can use the refresh tokens I get from the initial exchange but I cannot "put back" the refresh token I got from exchange.

> The reason it works like that is also that you know before which time you have to do another refresh. This information is returned when getting the offline token in the response and in sync with the offline token exp claim. Otherwise you would have to store state to keep this information.

When the `Offline Session Max Limited` is disabled then the refresh tokens do not have `exp` but the session expires.

----

Additional observation:

`#1`
 - Offline Session Idle: 2 minutes
 - Offline Session Max Limited: Enabled
 - Offline Session Max: 5 minutes

Offline token has `exp` "in 5m".
After 5 minutes we get `(error='invalid_grant', error_description='Token is not active')` error when we attempt to exchange offline token for new set of tokens. 

`#2`
 - flipped: Offline Session Max Limited: Disabled

Offline token does not have `exp`.

We are able to exchange offline token for the new set of tokens even after `Offline Session Idle` (2 minutes from `#1`) as well as after 3 and 4. But somewhere after 5 minutes mark we get `(error='invalid_grant', error_description='Offline user session not found')` error.

----

I'd expect behavior (presence of the exp claim) and the error returned to be inverted to what we expect.

If there's Offline Session Max Limited the the offline token has exp as it cannot be used beyond the particular point in time. It would become inactive then.

**Comment by sschu** [comment]
Your observations `#1` does not seem to match what was originally reported in the issue which says the expiration is based on the idle time. Do you have any overrides on a per-client-basis? What is the value of `refresh_expires_in` that Keycloak returns with the refresh token?

**Comment by codyharris-h2o-ai** [comment]
> I think this works exactly as designed. When exchanging an offline token, you get a new one that again has exp=currenttime+offline session idle (or session creation time+offline session max, if this is smaller). This basically works the same as for normal refresh tokens. Their expiry is also bound to the session idle times. You need to use your refresh token to get a new one within the idle times, otherwise the session will expire.

The original behaviour was that as long as the offline token was used once every $IDLE_TIME, the token was valid until $ISSUED + $IDLE_MAX had elapsed.

These tokens are used both internally and by customers in CI pipelines, performing a token exchange and saving the new token back is not possible.  When 'Offline Session Max Limited' is not set, the same token may be used indefinitely as long as it's used within $IDLE_TIME of the last usage.  The expectation is that the behaviour would be the same, except the token is bound by $IDLE_MAX.

Given an idle timeout of 5 minutes, and an idle max of 60 days, the original issued offline token expires in 5 minutes regardless of usage.  This makes sense for a regular refresh token, but not an offline token in my opinion.

**Comment by sschu** [comment]
@codyharris-h2o-ai And why do you not set idle time=max session to get your desired behaviour?

**Comment by codyharris-h2o-ai** [comment]
The desired behaviour was to have an unused, idle token to expire quickly (eg 48 hours), but if it's being used, remain active for 28 days before rotation is required

**Comment by sschu** [comment]
So I just tested this with Keycloak 11.0.3 and the behaviour is exactly the same as today: when Offline Session Max Limited is set the refresh token expires after Offline Session Idle (see screenshot).
<img width="1373" alt="Screenshot 2024-01-25 at 19 37 42" src="https://github.com/keycloak/keycloak/assets/3833769/1bc42481-edc0-423c-b450-a0b38521b40a">

**Comment by zoido** [comment]
> What is the value of `refresh_expires_in` that Keycloak returns with the refresh token?

For `#1`

For the initial exchange (code for offline token) there's no `refresh_expires_in`. For the first exchange (offline token for new set of tokens) it's 120.

For `#2`

For the initial exchange (code for offline token) there's no `refresh_expires_in`. For the first exchange (offline token for new set of tokens) it's `"refresh_expires_in": 0`. And the refresh token does not have `exp`.

**Comment by sschu** [comment]
@zoido I also get a `refresh_expires_in` for the the authcode request which is equal to `offline session idle` and in sync with the `exp` claim in the refresh token for `#1`.
@codyharris-h2o-ai I checked again with KC11.0.3 and I don't see a difference in behavior when `Offline Session Max Limited`is enabled compared to KC23.0.4. Can you give exact steps to reproduce a different behavior in KC11.0.3? If the behavior is the same, I would just close this issue as not a bug since this works as designed. Feel free to open a discussion or an issue on how the design should be changed.

**Comment by codyharris-h2o-ai** [comment]
Thanks @sschu, we'll go back to our internal team for some further discussion.

**Comment by codyharris-h2o-ai** [comment]
Ok thanks - after double checking it is indeed not a regression, apologies for that.  

I do disagree with the current behaviour, at least in that it does not to us match the description within the docs at https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-access.  

> If you enable [Offline Session Max Limited](https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-session-max-limited), offline tokens expire after 60 days even if you use **_the_** offline token for a refresh token action. You can change this value, [Offline Session Max](https://www.keycloak.org/docs/latest/server_admin/index.html#_offline-session-max), in the Admin Console.

(Emphasis mine)

Do you have a preference wrt issue or discussion?

**Comment by sschu** [comment]
It might be better to start a discussion on offline tokens in general and how you expect them to behave. A lot of people use offline tokens for long-lived sessions in mobile apps so users don't have to relogin. They don't really do anything when the user is not present. It might be an idea to allow normal sessions to be persisted for that use case and then use offline tokens as originally intended. I understood your use case as one that actually uses offline tokens for backend processing without user presence.

**Comment by codyharris-h2o-ai** [comment]
Thank you!  I opened a discussion thread here: https://github.com/keycloak/keycloak/discussions/26841
