### ISSUE TITLE
Update Keycloak sizing guide after change of default hashing configuration

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#26490]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The issue #16629 changed the default hashing configuration in Keycloak which results in a higher CPU usage. 

Due to this, https://www.keycloak.org/high-availability/concepts-memory-and-cpu-sizing needs to be updated as well as https://www.keycloak.org/keycloak-benchmark/benchmark-guide/latest/report/rosa-benchmark-key-results

### Version

999-SNAPSHOT

### Expected behavior

Guide in both places should match KC24 behavior.

### Actual behavior

This describes KC22/KC23 behavior

### How to Reproduce?

The nightly runs in KCB will show the results.

**Comment by kami619** [comment]
Logging this comment for future use, after the hashing iteration change is merged to Keycloak, we observed a 25% drop in `userLoginsPerSecPer1vCpuPerPod` metric (in a 3-pod Keycloak cluster) in our Continuous performance tests running from [here](https://github.com/keycloak/keycloak-benchmark/blob/main/.github/workflows/rosa-scaling-benchmark.yml).

```
Jan 24th benchmark run data:
"cpu-usage-for-logins-test": {
    "user-logins-per-sec-per-1vCpu-per-pod": 38
  }

Jan 26th benchmark run data:
"cpuUsageForLoginsTest": {
    "userLoginsPerSecPer1vCpuPerPod": 29
}
```

Benchmark results before hashing change: [Jan24th2024.zip](https://github.com/keycloak/keycloak/files/14094748/Jan24th2024.zip)
Benchmark results after hashing change:  [Jan26th2024.zip](https://github.com/keycloak/keycloak/files/14094739/Jan26th2024.zip)

**Comment by kami619** [comment]
> We are currently testing with requested vCPUs per Pod of 6. As we're testing 200 logins per second, our setup should go up to 7 vCPUs, better 8 vCPUs (200/29=6.9, 200/28=7.1).

@ahus1 I agree that having 8 vCPUs will be more realistic, do you want me to update the cpu limit first, take a new baseline and then update the docs ?

**Comment by ahus1** [comment]
@kami619 - I've seen that the pods were getting enough CPU, so we should be fine with the the numbers we got. Having not enough CPU available should in theory only affect the response time, not the CPU spent per request.
