### ISSUE TITLE
Active Directory federated logins don't allow users to have the @ symbol in their passwords

### ISSUE THREAD

**Issue by mcattle** [keycloak/keycloak#26511]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When logging in with an account federated through an ldap (Active Directory) server, the login fails if the password has an @ symbol in it.

### Version

20.0.2

### Expected behavior

The user should be able to log in with the correct password, no matter what characters it contains.

### Actual behavior

The login attempt is marked as unsuccessful, informing the user that their username or password is invalid.

### How to Reproduce?

1. Set up a Keycloak domain with users that are federated from an Active Directory server with ldap.
2. Set up a user in AD that has a password containing an @ symbol.
3. Sync all users with Keycloak
4. Try to authenticate to an application with Keycloak using that account.

**Comment by jonkoops** [comment]
Closing this issue as it was reported for an older version of Keycloak. As our issue templates states, we only accept issue reports tested against the latest version of Keycloak.
