### ISSUE TITLE
Workflow failure: Quarkus IT - FipsDistTest#testUnsupportedHttpsPkcs12KeyStoreInStrictMode

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#26529]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Quarkus IT](https://github.com/keycloak/keycloak/actions/runs/7662097125/job/20883036123)

```
2024-01-26T00:46:36.4258162Z -- [ERROR] org.keycloak.it.cli.dist.FipsDistTest.testUnsupportedHttpsPkcs12KeyStoreInStrictMode(KeycloakDistribution)  Time elapsed: 300.712 s  <<< FAILURE!
2024-01-26T00:46:36.4258328Z -- java.lang.AssertionError: 
2024-01-26T00:46:36.4258429Z -- 
2024-01-26T00:46:36.4258852Z -- Expected: a string containing "ERROR: java.lang.IllegalArgumentException: malformed sequence"
```

### Version

latest

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment]
I thought this was distinct from the transaction timeout / shutdown hang, but I don't believe that it is after trying to reproduce things more. This is still possible to see this when the transaction reaper is stuck as it's the main thread, which is ultimately what's needed for the callback on the quarkus exception handler. We'll end up having to wait the full 5 minutes prior to expecting malformed sequence output in the log.

**Comment by shawkins** [comment]
Still re-occurred after https://github.com/keycloak/keycloak/actions/runs/7714902209/job/21028638681 - so the initial thinking was correct, which is that we can't guarentee that we'll see the malformed sequence log output in this case, no matter how long we wait. The most likely cause is that the transaction reaper is not functioning correctly - there seem to be cases were it could miss awakening the main thread, and so the main thread is simply stuck until there is a spurious wakeup. At this point the best we can do is just not assert the log contains malformed sequence.
