### ISSUE TITLE
calling Revoke token on an offline refresh token is invalidating all offline sessions

### ISSUE THREAD

**Issue by vikram919** [keycloak/keycloak#26532]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have two clients (1 and 2) who wants to use offline sessions.
By using scope "offline_access" i can get the refresh tokens with type offline in it. If I call the revoke token endpoint with client 1 refresh token requests executes with 200 error code but the client 2 can no longer refresh the tokens and server returns 

{
    "error": "invalid_grant",
    "error_description": "Offline user session not found"
}

### Version

21.1.1

### Expected behavior

When i call revoke on a specific offline token only this token needs to be revoked and other offline refresh tokens are not revoked

### Actual behavior

When i call revoke on a specific offline token all other offline refresh tokens are also revoked

### How to Reproduce?

1. Try to get two offline token for specific user of a client
2. Invoke revoke token for one of the offline tokens
3. both offline tokens are revoked

**Comment by jonkoops** [comment]
Closing this issue as it was reported for an older version of Keycloak, as outlined in our issue template, we only accept issues tested against the latest version of Keycloak.

**Comment by vikram919** [comment]
this might be helpful for others, instead of using revoke tokens use logout endpoint with request query string params `id_toke_hint`: `id_token` and `post_redirect_uri`: `your app redirect uri` to invalidate a user session/logging an user out, this way keycloak server wont invalidate all offline tokens procured by an user account

**Comment by theodore86** [comment]
Seems like when the path "realms/{realm-name}/protocol/openid-connect/logout" is being triggered offline tokens are revoked and the server responds with: "Offline user session not found" - using Direct Access Grant
