### ISSUE TITLE
Keycloak/Keycloak-containers repo continues to mislead users

### ISSUE THREAD

**Issue by breakwaterlabs** [keycloak/keycloak#26537]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The `keycloak/keycloak-containers/` repository is archived and read-only, but is the top result when searching for how to implement keycloak on a container platform.

Unfortunately, many of its examples are wrong, and wrong in ways that make it difficult to identify and fix. All of the example parameters for e.g. database integration ([e.g. postgres](https://github.com/keycloak/keycloak-containers/blob/main/docker-compose-examples/keycloak-mysql.yml)) reference deprecated and no longer used variables like `DB_ADDR`.

Because Keycloak does not log invalid environmental variables to stdout nor does it display which are in use at startup, this is a very difficult issue to identify especially as those examples seem at first glance to be official documentation. Thus, you see StackOverflow questions like [this](https://stackoverflow.com/questions/71869421/keycloak-container-ignoring-db-addr-option/77888388#77888388), or keycloak discourse discussions using the old variables like [this ](https://github.com/keycloak/keycloak/issues/24755#issuecomment-1812008203) and [this](https://keycloak.discourse.group/t/keycloak-wiped-all-data-on-docker/24063).

Worse, because keycloak has sensible defaults for those variables (like localhost) it is entirely possible to supply a list of variables, some valid and some not, and end up with a configuration that works for now-- such as if a postgres container is on the same docker network or kubernetes pod, where the default connection string has a good chance of working until you attempt to refacator the database to a different location.

There are several simple fixes that eliminate these foot-guns altogether:
 - The keycloak-containers repository should either remove or clearly label those examples as invalid in current configurations
 - The current version should identify at startup what database options were read in and in use in use in stdout
 - The old environmental variables should either be accepted, or throw an error message, to mitigate incorrect usages

### Version

23.0.4

### Expected behavior

- Legacy options like DB_ADDR should either be accepted or throw startup warnings
- Keycloak startup should clearly stdout what backing DB parameters it is using
- Old incorrect documentation should either carry a warning or be removed

### Actual behavior

 - Legacy options like DB_ADDR are silently ignored

### How to Reproduce?

    docker run -p 8080:8080 -e DB_VENDOR=mysql -e DB_ADDR=<ip_address> -e DB_PORT=3306 -e DB_DATABASE=keycloakdb -e DB_USER=keycloakuser -e DB_PASSWORD=password jboss/keycloak

Database options will be ignored.

**Comment by stianst** [comment]
Deleting the repository would make it hard to build a container for an older version of Keycloak if anyone ever needs to. Instead I've cleared all the content in the repo except the README file.
