### ISSUE TITLE
Post Quarkus 3.7 dependency alignment

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#26535]
A breakdown of dependency issues following the quarkus upgrade:

Versions where we trail quarkus - may need individual issues:
- bc-fips to 1.0.2.4 - exhibited classloading problems
- liquibase to 4.25.1 - even after updating CustomLockService, there is still a test failure 
- osgi to 6.0 - didn't build successfully

Versions where we are ahead of quarkus, and that are used for more than tests:
- jakarata.mail - quarkus is actually still using com.sun.mail, rather than jakarta.mail https://github.com/quarkusio/quarkus/issues/26989

Versions where we are even with quarkus, but have our own property:
- slf4j - used only for an additional test dependency not covered by the quarkus bom
- infinispan - used for more than tests and need the version to import the infinispan bom

Versions where we are trail quarkus, and that are used for more than tests, but seem to upgrade without an issue:
- resteasy
- wildfly-elytron

And a lot of test related dependencies / overlap - mostly drivers, but also awaitility, hamcrest, and testcontainers. Driver versions cannot be removed because we reference them as variables in our tests to switch between databases.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/pull/26203#discussion_r1467792077_

**Comment by shawkins** [comment]
Unfortunately with the exception of a couple of test dependencies it does not look like we can easily remove the versions we are referencing.

**Comment by vmuzikar** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/21356

**Comment by shawkins** [comment]
@vmuzikar should an issue be created for the osgi upgrade? And/or would that fall under the core's responsibility?

**Comment by vmuzikar** [comment]
> should an issue be created for the osgi upgrade? And/or would that fall under the core's responsibility?

I'd say yes and yes. (CC @mposolda)
