### ISSUE TITLE
Mysterious settings changes due to Keycloak cluster changes

### ISSUE THREAD

**Issue by havarnov** [keycloak/keycloak#26549]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The other day we had an issue with our Keycloak cluster. We're running 3 nodes hosted in Azure App Service. At one point one of the nodes was recycled and a new node was started to replace it. During the shutdown/startup we can see from the logs that there were some issues with the Infinispan cache (`java.lang.IllegalStateException: Read commands must ignore leavers` and timeouts).

But, as it seems the nodes were back in normal operation soon after, as expected. What follows is not as expected though. Suddenly we're seeing an increased number of expired refresh tokens and consequently 401s.

By more or less coincidence we saw that the `Offline Session Idle` setting was configured to 42 minutes and not 42 days as we had configured it. Changing this value back to days (not minutes) immediately resolved the expired refresh token issue.

So to us it seems like this setting was changed somehow due to the recycling of the node and/or the Infinispan issues. 

### Version

22.0.1

### Expected behavior

The `Offline Session Idle` setting (and all other settings) should not be affected by changes to the Keycloak cluster.

### Actual behavior

Seems like the the `Offline Session Idle` setting was changed due changes in the Keycloak cluster.

### How to Reproduce?

N/A.

**Comment by mposolda** [comment]
I am assigning to UI team to triage and doublecheck if something can be done with the timeouts settings to be more UXD friendly (See video from the comment above), so it doesn't randomly change from "days" to "minutes" (See video from the comment above).

**Comment by ssilvert** [comment]
I have verified this bug on the latest nightly.

**Comment by havarnov** [comment]
Just wanted to mention that the issue we're seeing is most likely: https://github.com/keycloak/keycloak/issues/14040.

The issue fixed in: https://github.com/keycloak/keycloak/pull/26743 was just something we noticed during our investigation.
