### ISSUE TITLE
Invalid_token_response An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 404 not found

### ISSUE THREAD

**Issue by ser789654** [keycloak/keycloak#26554]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

When I try to authenticate to my Spring Boot app running on /myclient with keycloak, this message is shown to me:

`[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: 404 not found`

I have keycloak running on context **/keycloakt1.**

Request from postman to get token is successful on url `https://somedomain.com/keycloakt1/realms/myclient/protocol/openid-connect/token`

I provided this configuration to my application.yaml

```
 spring.security.oauth2.client.provider.keycloak.issuer-uri: 'https://somedomain.com/keycloakt1/realms/myrealm'
 spring.security.oauth2.client.registration.keycloak.client-id: myclient
 spring.security.oauth2.resourceserver.jwt.issuer-uri: 'https://somedomain.com/keycloakt1/realms/myrealm'
```

But when I list the well known endpoints from /.well-known/openid-configuration

I see some endpoints is missing the /keycloakt1/ in the uri especially the token_endpoint which probably causing the error. Can anybody know how to resolve this?

```
"issuer": "https://somedomain/keycloakt1/realms/myclient",
"authorization_endpoint": "https://somedomain/keycloakt1/realms/myclient/protocol/openid-connect/auth",
-----> THERE IS MISSING /keycloakt1/ "token_endpoint": "https://somedomain/realms/myclient/protocol/openid-connect/token",
-----> THERE IS MISSING /keycloakt1/ "introspection_endpoint": "https://somedomain/realms/myclient/protocol/openid-connect/token/introspect",
-----> THERE IS MISSING /keycloakt1/ "userinfo_endpoint": "https://somedomain/realms/myclient/protocol/openid-connect/userinfo",
"end_session_endpoint": "https://somedomain/keycloakt1/realms/myclient/protocol/openid-connect/logout",
"frontchannel_logout_session_supported": true,
"frontchannel_logout_supported": true,
-----> THERE IS MISSING /keycloakt1/ "jwks_uri": "https://somedomain/realms/myclient/protocol/openid-connect/certs",
```

In my ConfigMap I have this env variables:

```
  HOSTNAME_STRICT: 'false'
  HOSTNAME_STRICT_HTTPS: 'false'
  KC_DB: mssql
  KC_DB_URL: >-
    ***********
  KC_DB_URL_DATABASE: ********
  KC_DB_URL_HOST: ***********
  KC_DB_URL_PORT: '1433'
  KC_HEALTH_ENABLED: 'true'
  KC_HOSTNAME: somedomain.com/keycloakt1
  KC_HOSTNAME_ADMIN_URL: 'https://somedomain.com/keycloakt1/'
  KC_HOSTNAME_STRICT: 'false'
  KC_HOSTNAME_STRICT_HTTPS: 'false'
  KC_HTTP_ENABLED: 'true'
  KC_HTTP_PORT: '8080'
  KC_HTTP_RELATIVE_PATH: /auth
  KC_METRICS_ENABLED: 'true'
  KC_PROXY: edge
  KC_TRANSACTION_XA_ENABLED: 'false'
  KEYCLOAK_ADMIN_URL: 'https://somedomain.com/keycloakt1/realms/master/admin/'
  KEYCLOAK_FRONTEND_URL: 'https://somedomain.com/keycloakt1/auth/'
  KEYCLOAK_URL: 'https://somedomain.com/keycloakt1/'
  PORT: '8080'
  PROXY_ADDRESS_FORWARDING: 'true'
  WEBSITES_PORT: '8080'
  jgroups.dns.query: keycloakt1
```

### Version

22.0.3

### Expected behavior

The endoints from /.well-known/openid-configuration should return correct endopints and authentication should end with 200 OK.

### Actual behavior

Login ends in 404 Not Found

### How to Reproduce?

Deploy Keycloak with same configMap as provided in the question.

**Comment by mposolda** [comment]
Thanks for the report, but I am moving to backlog as Keycloak team likely won't have a change to look at this soon. It might be prioritized when token-exchange become a priority (currently it is still a preview feature).

In the meantime, anyone is welcome to investigate this and eventually send PR with the fix.
