### ISSUE TITLE
Upgrade to bc-fips 1.0.2.4

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#26568]
### Description

Relates to #26535 - quakus 3.7 moved up to bc-fips 1.0.2.4. However our tests do not run cleanly with that version due to classloading issues.

```
2024-01-18T21:51:37.6895717Z [ERROR] org.keycloak.crypto.fips.test.FIPS1402HmacTest.testHmacSignaturesWithRandomSecretKey  Time elapsed: 0.001 s  <<< ERROR!
2024-01-18T21:51:37.6897446Z java.lang.NoClassDefFoundError: Could not initialize class java.util.UUID$Holder
2024-01-18T21:51:37.6898506Z 	at java.base/java.util.UUID.randomUUID(UUID.java:148)
2024-01-18T21:51:37.6899702Z 	at org.keycloak.jose.HmacTest.testHmacSignaturesWithRandomSecretKey(HmacTest.java:49)
```

This has been seen with bc before - https://github.com/bcgit/bc-java/issues/1149#issuecomment-1790457576- that specifically mentions trying 1.0.2.4 with keycloak.

**Comment by vmuzikar** [comment]
CC @keycloak/core Similarly to #26570, this also causes misalignment with Quarkus and potential prod issues as discussed offline today.

**Comment by trixpan** [comment]
We use version 1.0.2.5 in production without issues.

**Comment by trixpan** [comment]
My guess is that the code is calling SecureRandom and the test unit is trying to get an instance of secure Random and getting stuck here on the same bug @mposolda found a while back when working on FIPS on RHEL JDK.

https://issues.redhat.com/browse/RHEL-3478

Given the UUID is just  a random value, seems to me, a better choice would be to use a separate UUID generation mechanism that 

![image](https://github.com/keycloak/keycloak/assets/3108527/bf9a8b48-940e-40e8-8550-0b4a34cfd1b7)

**Comment by trixpan** [comment]
@vmuzikar I am not sure how would this cause production issues tbh.

The BCFIP libraries cannot b shipped with Quarkus nor Keycloak, meaning customers are expected to add the libraries to the classpath.

Yes we specify versions in the documentation and I am sure RH may want to lock them on its supported build of KC but, for all intents and purposes, **it seems those minor increments of bc-fips are the best example of what not to control?**

**Comment by codespearhead** [comment]
This might be superseded by #29670 .
