### ISSUE TITLE
Update for the change log

### ISSUE THREAD

**Issue by bakgaard** [keycloak/keycloak#26579]
### Description

The [current documentation](https://www.keycloak.org/docs/latest/release_notes/index.html) contains no info on the latest releases. Can we have that? 

### Motivation

Even though they might just contain updates to dependencies, translations, and test enhancements, could we at least have a mention that the updates are just minor enhancements to the system. Not having anything on the release is not satisfying.

**Comment by stianst** [comment]
https://www.keycloak.org/2024/01/keycloak-2305-released.html
https://github.com/keycloak/keycloak/releases/tag/23.0.5
