### ISSUE TITLE
Upgrade liquibase to 4.25.1

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#26570]
### Description

Relates to #26535 - quarkus 3.7 has moved ahead to liquibase 4.25.1, which at the very least requires a code change to CustomLockService. However even after that change there were test failures, so this needs evaluated by the @keycloak/store team.

**Comment by ahus1** [comment]
@shawkins - we'll have someone looking into this. To help me understand: 

* This is not blocking the current PR #26203 to upgrade to the latest CR of Quarkus? 
* You plan to merge the that PR later this week, so you we could plan our changes on top of it?

**Comment by shawkins** [comment]
> @shawkins - we'll have someone looking into this. To help me understand:
> 
> * This is not blocking the current PR [task: upgrade to quarkus 3.7.x #26203](https://github.com/keycloak/keycloak/pull/26203) to upgrade to the latest CR of Quarkus?

Correct, it is not blocking the 3.7 upgrade. It is related to the post upgrade task and can be done in parallel with the other post upgrade changes.

> * You plan to merge the that PR later this week, so you we could plan our changes on top of it?

Yes I believe #26150 will be merged this week.
