### ISSUE TITLE
Allow Case-Insensitive Search on Provider Info Page in Admin UI

### ISSUE THREAD

**Issue by stefangries** [keycloak/keycloak#26589]
### Description

Currently provider search for SPI-names is case sensitive on the Provider Info search. This makes it hard for users to find the matching providers. 

### Motivation

Searching for "jpa" doesn't find "connectionsJpa".

### Details

A fix is simple: just compare lower case values of SPI name and search value.

**Comment by ssilvert** [comment]
@edewit I assigned this to you because you are already assigned to the PR.
