### ISSUE TITLE
org.keycloak.models.ModelException: invalidPasswordMinDigitsMessage stacktrace logged when a user tries to update its password without having at least 1 digit

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#26601]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When a user tries to create/update it's password without having at least 1 numerical digit this error is displayed : 
![image](https://github.com/keycloak/keycloak/assets/11772429/0afdd352-a3b3-41d3-ab6f-48ae98a3c351)

This is fine.
But it also logs a whole big stacktrace in the logs with the WARN level : 

_

> gateway-bdoc-gateway-keycloak-1  | 2024-01-30 14:35:05,673 WARN  [org.keycloak.services.resources.admin.UserResource] (executor-thread-6) Could not update user password.: org.keycloak.models.ModelException: invalidPasswordMinDigitsMessage
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.credential.PasswordCredentialProvider.createCredential(PasswordCredentialProvider.java:61)
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.credential.PasswordCredentialProvider.updateCredential(PasswordCredentialProvider.java:142)
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.credential.LegacyUserCredentialManager.lambda$updateCredential$2(LegacyUserCredentialManager.java:98)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.credential.LegacyUserCredentialManager.updateCredential(LegacyUserCredentialManager.java:98)
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.models.cache.infinispan.SubjectCredentialManagerCacheAdapter.updateCredential(SubjectCredentialManagerCacheAdapter.java:41)
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.services.resources.admin.UserResource.resetPassword(UserResource.java:691)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
> gateway-bdoc-gateway-keycloak-1  |      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
> gateway-bdoc-gateway-keycloak-1  |      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
> gateway-bdoc-gateway-keycloak-1  |      at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
> gateway-bdoc-gateway-keycloak-1  |      at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
> gateway-bdoc-gateway-keycloak-1  |      at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
> gateway-bdoc-gateway-keycloak-1  |      at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
> gateway-bdoc-gateway-keycloak-1  |      at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
> gateway-bdoc-gateway-keycloak-1  |      at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
> gateway-bdoc-gateway-keycloak-1  |      at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
> gateway-bdoc-gateway-keycloak-1  |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> gateway-bdoc-gateway-keycloak-1  |      at java.base/java.lang.Thread.run(Thread.java:840)
> gateway-bdoc-gateway-keycloak-1  |

_

I don't really see the point of having this stacktrace logged each time for a functionnal error.
It is more annoying than anything else as when searching for real technical errors or warnings it is a distraction.

### Version

22.0.5

### Expected behavior

Do not log a stacktrace for a functionnal error.
At most simply log the message (but I still don't see the point) and not the full stacktrace.
If a message is logged in WARN it should then at least contain the username so the admin can know who tried to update the password.

### Actual behavior

A full stacktrace is logged

### How to Reproduce?

Try to update a user password without having at least 1 digit.

**Comment by mposolda** [comment]
Looks like a valid issue and fully agree that it can be good to log just the WARN instead of the full stacktrace.

I am adding to Backlog with label "Help wanted" as I am not sure if Keycloak team has time to look at this. Anyone is welcome to send PR for this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details on how to contribute.
