### ISSUE TITLE
CLIENT_ATTRIBUTES index idx_client_att_by_name_value no longer exists since KC 20 (postgres)

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#26618]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Since KC 20, on the CLIENT_ATTRIBUTES table the idx_client_att_by_name_value no longer exists when creating or migrating an existing KC installation using a postgres database.

The index was introduced in jpa-changelog-14.0.0.xml

We noticed this after upgrading from an RHSSO installation to Keycloak 23

### Version

main / latest

### Expected behavior

Table CLIENT_ATTRIBUTES has an index idx_client_att_by_name_value that exists and can be used for queries

### Actual behavior

CLIENT_ATTRIBUTES index idx_client_att_by_name_value does not exist

### How to Reproduce?

- Create empty Postgres DB for KC
- Start any KC version from 20 -> nightly and point it at this db
- Inspect the indexes available on CLIENT_ATTRIBUTES
- Note that idx_client_att_by_name_value no longer exists

### Anything else?

It seems related to this [datatype change](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/resources/META-INF/jpa-changelog-20.0.0.xml#L58) in KC 20

**Comment by vramik** [comment]
Thank you @jsorah for the report. I can confirm your findings as well as that the culprit seems to be https://github.com/keycloak/keycloak/issues/14013

**Comment by rmartinc** [comment]
I think that the issue is clear, previously there was an index on name,value (up to 250 chars) but, when the value was changed from varchar to clob it was removed (the column was removed and the new added without reconstructing the index). We can re-add the index as before (name, value up to 250 chars) or do a similar thing @vramik is doing in users #9758 (recent PR for 24 #26196). I'm going to ask him what he thinks about this.

**Comment by rmartinc** [comment]
I have been implementing a similar solution to #9758 in this branch: https://github.com/rmartinc/keycloak/tree/issue-26618. But maybe it's too complicated. I'm now more inclined to just re-create the [old indexes](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/resources/META-INF/jpa-changelog-14.0.0.xml#L63-L85) (but mssql cannot index using a substring).

@vramik @ahus1 WDYT? Do I continue with the idea in the branch or just re-set the indexes?

**Comment by ahus1** [comment]
@rmartinc - in a first step, I'd be +1 for creating the old index for all databases where it works (and not of mssql when it doesn't work there). Before applying the attributes indexing to other tables, I'd like that implementation to settle a bit first.

**Comment by rmartinc** [comment]
@ahus1 @vramik Okis, perfect, then I will prepare the changes for re-adding the previous index.
