### ISSUE TITLE
iss not returned as query param in redirect url

### ISSUE THREAD

**Issue by Rupacerupesh** [keycloak/keycloak#26611]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Everything was working fine. Something went wrong and I have no idea what. The `iss` query parameter in redirect_url is no longer present.

My keycloak login url is
`https://localhost:8081/realms/square/protocol/openid-connect/auth?client_id=customer-portal&scope=openid email profile&response_type=code&redirect_uri=http://localhost:3000/auth/api/auth/callback/keycloak&state=v-3mFqqnK5BZce7wQwpZUdzBM-Wbo4Eo0Rph_t0ei5g
`

    
After successful login, my redirect url is
`http://localhost:3000/auth/api/auth/callback/keycloak?state=v-3mFqqnK5BZce7wQwpZUdzBM-Wbo4Eo0Rph_t0ei5g&session_state=841252b7-4332-45d9-b36e-ca3a54417c0c&code=7baf3f41-f2cd-40ef-bb77-9d9dc7cded2f.841252b7-4332-45d9-b36e-ca3a54417c0c.ef8b3eab-1fc5-41d0-8020-dc16e0e98d15`.        
 which is missing the iss query parameter

### Version

4.22.1

### Expected behavior

Redirect url with iss query param
`http://localhost:3000/auth/api/auth/callback/keycloak?state=v-3mFqqnK5BZce7wQwpZUdzBM-Wbo4Eo0Rph_t0ei5g&session_state=841252b7-4332-45d9-b36e-ca3a54417c0c&code=7baf3f41-f2cd-40ef-bb77-9d9dc7cded2f.841252b7-4332-45d9-b36e-ca3a54417c0c.ef8b3eab-1fc5-41d0-8020-dc16e0e98d15&iss=https://localhost:8081/realms/square`

### Actual behavior

Redirect url with iss query param
`http://localhost:3000/auth/api/auth/callback/keycloak?state=v-3mFqqnK5BZce7wQwpZUdzBM-Wbo4Eo0Rph_t0ei5g&session_state=841252b7-4332-45d9-b36e-ca3a54417c0c&code=7baf3f41-f2cd-40ef-bb77-9d9dc7cded2f.841252b7-4332-45d9-b36e-ca3a54417c0c.ef8b3eab-1fc5-41d0-8020-dc16e0e98d15`

### How to Reproduce?

Steps logging in via keycloak oidc

**Comment by jonkoops** [comment]
Closing this issue as it is reported for an older version of Keycloak. If you can reproduce this in the latest stable version of Keycloak feel free to submit a new issue.
