### ISSUE TITLE
Can't install Keycloak on fresh DB - timeout?

### ISSUE THREAD

**Issue by OliverCole** [keycloak/keycloak#26619]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Unable to install Keycloak on a fresh database.

My underlying database (Planetscale) has a max transaction time of 20s - is this the issue? Surely it should be able to setup some tables in 20 seconds?

### Version

23.0.5

### Expected behavior

Keycloak installs DB and starts up.

### Actual behavior

CustomLockService is timing out during server start/DB install on a fresh database.

```
2024-01-30T22:38:11Z app[32873eea3dd698] lhr [info]2024-01-30 22:38:11,388 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-1.3.0.xml::1.3.0::bburke@redhat.com encountered an exception.
2024-01-30T22:38:11Z app[32873eea3dd698] lhr [info]2024-01-30 22:38:11,594 ERROR [org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService] (main) Database error during release lock: liquibase.exception.DatabaseException: java.sql.SQLException: target: keycloak.-.primary: vttablet: rpc error: code = Aborted desc = transaction 1706651072330528342: ended at 2024-01-30 22:37:16.348 UTC (exceeded timeout: 20s) (CallerID: 63jlcs9lryspyembcvdw)
2024-01-30T22:38:11Z app[32873eea3dd698] lhr [info]     at liquibase.database.jvm.JdbcConnection.commit(JdbcConnection.java:275)
2024-01-30T22:38:11Z app[32873eea3dd698] lhr [info]     at liquibase.database.AbstractJdbcDatabase.commit(AbstractJdbcDatabase.java:1184)
2024-01-30T22:38:11Z app[32873eea3dd698] lhr [info]     at org.keycloak.connections.jpa.updater.liquibase.lock.CustomLockService.releaseLock(CustomLockService.java:271)
```

Keycloak exits, on restart, depending on where the install got to, it complains about columns in tables, or tables already existing, eg:

```
2024-01-30T22:38:12Z app[32873eea3dd698] lhr [info]2024-01-30 22:38:12,025 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.3.0.xml::1.3.0::bburke@redhat.com:
2024-01-30T22:38:12Z app[32873eea3dd698] lhr [info]     Reason: liquibase.exception.DatabaseException: column 'UPDATE_PROFILE_FIRST_LGN_MD' not found in table 'keycloak.IDENTITY_PROVIDER' [Failed SQL: (1105) UPDATE keycloak.IDENTITY_PROVIDER SET UPDATE_PROFILE_FIRST_LGN_MD = 'off' WHERE UPDATE_PROFILE_FIRST_LOGIN = 0]
```

### How to Reproduce?

Started Keycloak on fresh Planetscale mysql DB. 
Added `JAVA_OPTS_APPEND = "-Djboss.as.management.blocking.timeout=72000"` but no effect.

### Anything else?

Ideally I would get this to install all in one go, but if I can make it pick up the install from where it stopped, that works too.

**Comment by shawkins** [comment]
Presumably each changeset is being applied in its own transaction - on the 20s being a long time, you could try a different database to see what the timings typically are.

Seeing the incomplete application of a changeset results in a corrupted state, rather than being able to resume definitely seems like a bug. We've hit a timing issue that presents similarly: #24550

Looping in the store team to weigh in further.

**Comment by OliverCole** [comment]
I will definitely try that. But what would be the lifecycle going forward - will I be able to do that workaround for future incremental upgrades?

**Comment by sguilhen** [comment]
Hi @OliverCole , yes you will. Once you have the DB initialize and upgrade Keycloak to a newer version, the above procedure will only produce the SQL statements needed to perform the migration. Depending on the amount of changes, you might be successful with automatic migration (If the overall change fits within the 20s tx timeout), but you could risk a failure leaving the DB in an inconsistent state, so I would stick to manual migration.

**Comment by OliverCole** [comment]
No joy - manual migration on a fresh DB outputs a `DELETE FROM keycloak.CLIENT_SESSION_ROLE` before a `CREATE`.
[kc.23.0.6.sql.txt](https://github.com/keycloak/keycloak/files/14186369/kc.23.0.6.sql.txt)

(It also outputs a `UPDATE keycloak.DATABASECHANGELOG` without creating it, but I worked around that by grabbing a table definition from a failed migration...)

I could continue editing, but feels like I'm way off the piste here.

**Comment by OliverCole** [comment]
Hmm, OK. I've tried again. Now it seems to try to install, fails on timeout, and never actually outputs the SQL.
If I run again, it now outputs SQL from that point, but that's not what we need.

So the log is effectively back to square one. Here's the full thing: 
[kc.log](https://github.com/keycloak/keycloak/files/14314245/kc.log)

**Comment by sguilhen** [comment]
I've run the following (using the [nightly](https://github.com/keycloak/keycloak/releases/tag/nightly) release as the migration option names changed for the upcoming Keycloak 24):

`./kc.sh start-dev --spi-connections-jpa-quarkus-migration-strategy=manual --spi-connections-jpa-quarkus-initialize-empty=false`

Logs show

`Database not initialized, please initialize database with /home/sguilhen/Workspace/test/keycloak-999.0.0-SNAPSHOT/bin/keycloak-database-update.sql`

If you are running a Keycloak up to version 23.x, the options are `--spi-connections-jpa-legacy-migration-strategy` and `--spi-connections-jpa-legacy-initialize-empty`

It gave the attached file, which contains all SQL statements that have to be run:

[keycloak-database-update.sql.txt](https://github.com/keycloak/keycloak/files/14314573/keycloak-database-update.sql.txt)

**Comment by OliverCole** [comment]
Right, I was using `start` instead of `start-dev`. Thanks.

My output is immediately invalid because it contains two `CREATE TABLE PUBLIC.DATABASECHANGELOG`. So is yours.

I know this is hard to believe, but from the point it seems to get non-deterministic. For example, it once output:

`CREATE TABLE keycloak.CREDENTIAL (ID VARCHAR(36) NOT NULL, DEVICE VARCHAR(255) NULL, HASH_ITERATIONS INT NULL, SALT TINYBLOB NULL, TYPE VARCHAR(255) NULL, "VALUE" VARCHAR(255) NULL, USER_ID VARCHAR(36) NULL);`

Which didn't work as it needs backticks, then another time it output:

`CREATE TABLE keycloak.CREDENTIAL (ID VARCHAR(36) NOT NULL, DEVICE VARCHAR(255) NULL, HASH_ITERATIONS INT NULL, SALT TINYBLOB NULL, TYPE VARCHAR(255) NULL, VALUE VARCHAR(255) NULL, USER_ID VARCHAR(36) NULL);`

Which does seem to work.

**Comment by sguilhen** [comment]
@OliverCole Ignore the duplicate `CREATE TABLE PUBLIC.DATABASECHANGELOG` in the output file. The first one is produced by Keycloak [here](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/legacy/liquibase/QuarkusJpaUpdaterProvider.java#L217), before running liquibase to generate the statements. Liquibase then ends up generating it again. Not sure why Keycloak is doing it (perhaps previous versions of Liquibase didn't output the table creation), but you can ignore it.

Now, regarding the quotes in the SQL statements, Liquibase uses the DB that is being run to produce the right "flavor" of statements, as some details around quoting, etc, vary from DB to DB. So when we run the command to produce the manual migration file, by default H2 is selected and Liquibase will produce statements compatible with H2.

Seeing that Planetscale is compatible with MySQL, I would suggest running the command in keycloak using a MySQL DB (spin a mysql container just for that, for example), like this:

```
./kc.sh start-dev --db=mysql --db-username=mysql_user --db-password=mysql_pass --spi-connections-jpa-quarkus-migration-strategy=manual --spi-connections-jpa-quarkus-initialize-empty=false
```

This way Liquibase will produce the migration statements using syntax compatible with MySQL. It will be visible in the output file as Liquibase logs info about the DB that was used to generate the statements.
