### ISSUE TITLE
keycloak-js: missing clientSecret option inside config

### ISSUE THREAD

**Issue by frolovsky** [keycloak/keycloak#26623]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Hello! 
I think I noticed a problem with the lack of ability to specify a `client_secret` in the request. I mean the first POST request for a token `{server_url}/realms/{realm}/protocol/openid-connect/token`.
This option must be passed in the body of the request if we enable the “Client authentication” and "Authorization" checkboxes inside the client settings. 

401 Answer from keycloak after login:
```
{
  "error": "unauthorized_client",
  "error_description": "Client secret not provided in request"
}
```

### Version

23.0.4

### Expected behavior

200 status code, client_secret passed inside keycloak config or init options.

### Actual behavior

No possibility to pass `client_secret` to client created with `keycloak-js`.
401 Answer from keycloak after login:
```
{
  "error": "unauthorized_client",
  "error_description": "Client secret not provided in request"
}
```

### How to Reproduce?

**Preconditions:**
- Keycloak server version: `19.0.3`
- Frontend with installed `keycloak-js` version `23.0.4`

**Setting up**
First you need to set up authorization inside admin UI:
1. Select client
2. Settings
3. Scroll down to "Capability config"
4. Turn on “Client authentication” and "Authorization".

**Try to login with code examples**
<details>
<summary>Part of frontend code</summary>

```ts
import Keycloak from "keycloak-js";

const keycloak = new Keycloak({
  url, 
  realm, 
  clientId,
});

keycloak.init({
  checkLoginIframe: false,
  onLoad: "login-required",
});
```
</details>

Next step: Start FE application, login and got 401

```
{
  "error": "unauthorized_client",
  "error_description": "Client secret not provided in request"
}
```

### Anything else?

I fixed it locally inside node_modules. Issue live inside `processCallback` 
```js
params += '&client_id=' + encodeURIComponent(kc.clientId);
params += '&redirect_uri=' + oauth.redirectUri;
params += '&client_secret=' + encodeURIComponent(kc.clientSecret); // this needs to be added
```

**Comment by jonkoops** [comment]
This is intentional, storing a client secret in the browser is insecure as it can be stolen and used to authenticate other clients. For these reasons Keycloak JS only supports public clients.

**Comment by jonkoops** [comment]
I am not to familiar with this part of the Admin Console. I think the best thing would be to start a discussion and ask your question there.
