### ISSUE TITLE
Brute force detection should issue event for temporary lockout

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#26626]
### Description

Brute force detection should send an event when user account is temporarily locked due to brute force attack.

### Motivation

Currently event is sent for permanent lockout (implemented in PR https://github.com/keycloak/keycloak/pull/8679) but not when user account is temporarily locked. Having event also for temporary lockout can improve visibility of ongoing brute force attack.

### Details

Besides the lack of event for temporary lockout, currently brute force protector prints a free-text warning to the logs:

```
2024-01-31 10:51:41,466 WARN  [org.keycloak.services] (Brute Force Protector) KC-SERVICES0053: login failure for user 69563c18-7215-471c-b344-c7a0a8d49296 from ip 127.0.0.1
```

It could be better if lowered from `WARN` to `DEBUG` for not to be visible with default log level, or completely removed. Reasoning: unconditionally printing user id and IP address in free-text logs for every invalid login may be seen as unnecessary logging of personally identifiable information. This could be also better served by event for permanent and temporary lockout, where presence of PII is justified and due to the structured format of events, is easier to process appropriately.

**Comment by ahus1** [comment]
I support removing the log about the login failure, as the same information is present in the event `LOGIN_ERROR` which is (by default) already logged as a warning. 

cc: @mposolda as this connects to the core team. I already looked at the connected PR and it points in the right direction.
