### ISSUE TITLE
Immediately reflect flow binding status on flow definition page in Admin UI when binding an auth flow

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#26636]
### Description

Currently when binding a custom flow from within the flow definition page the flow binding status is not reflected directly.

Users have to leave the flow definition page and return to see the effect.

<img width="1209" alt="image" src="https://github.com/keycloak/keycloak/assets/314690/8f6fa785-e65d-445d-86fe-8a2362830a71">

<img width="1218" alt="image" src="https://github.com/keycloak/keycloak/assets/314690/17c22c38-a3f8-4fe0-ac27-8c693774b020">

### Details

Binding the flow should update the flow status immediately.

**Comment by ssilvert** [comment]
I have recreated this.  I agree with @jonkoops that it's a bug.  Low priority, but we should fix it.
