### ISSUE TITLE
Account UI ships too much Beer in user attributes

### ISSUE THREAD

**Issue by nej1imb** [keycloak/keycloak#26635]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

User attributes (defined in User Profile) with a "." dot in it's keys are not processed in Account UI properly.
GET (/realms/{realm}/account) request from backend provides proper key:value pairs but UI show only keys with empty values.
POST (/realms/{realm}/account) request sends back the proper key:value pairs (unmodified) plus additional attributes with Beer symbols in keys.
![image](https://github.com/keycloak/keycloak/assets/158275485/be70867c-696c-417e-8226-0f18e03d0f51)

### Version

23.0.5

### Expected behavior

Account UI shall process user attributes as defined in configuration "realm settings : user profile"

### Actual behavior

Attributes with key expression holding "." (e.g. "my.attribute.key") cannot be modified in Account UI (V2 and V3)

### How to Reproduce?

Define a user profile attribute "my.attribute.key" in configuration "realm settings: user profile".
In Account UI try to update such attribute.

**Comment by ssilvert** [comment]
The behavior I see is that if you save the attribute from admin console then you won't see the updated value in account console.  And vice versa.

It appears that escaping of the dot is not consistent between admin and account console.  So they are saved as two different key/value pairs.

I didn't try this on registration, but we need to make sure all three are updating the same attribute when the attribute key has a dot in it.

**Comment by edewit** [comment]
Registration doesn't use react forms
