### ISSUE TITLE
Replace "message bundle" text to "translation" in realm overrides

### ISSUE THREAD

**Issue by agagancarczyk** [keycloak/keycloak#26643]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Replace "message bundle" text to "translation" in realm overrides

### Version

23.0.5

### Expected behavior

Messages are replaced

### Actual behavior

Messages are wrong

### How to Reproduce?

Go to localization -> Realm Overrides and run through the  modals

**Comment by weltonrodrigo** [comment]
I'd like to add that it would be nice to see all translatable messages and provide a customization to the relevant ones.

**Comment by agagancarczyk** [comment]
hi @weltonrodrigo thanks for your suggestion. Could you please open a new GH issue so that this can be dealt with separately? Thanks!
