### ISSUE TITLE
Endpoints in keycloak extension with media type multipart/form-data no longer work in keycloak 23.0.x 

### ISSUE THREAD

**Issue by sostrich** [keycloak/keycloak#26642]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

starting with keycloak 23.0.x, having a rest endpoint with the type multipart/form-data no longer works in an extensions. Instead, status code 415 is returned even for requests with the correct media type:

wireshark screenshot:
![image](https://github.com/keycloak/keycloak/assets/82578679/20b31691-12c3-492a-a001-337bfedee897)

A reproducer can be found [here](https://github.com/sostrich/keycloak-23-bug-reproducers).

### Version

23.0.5

### Expected behavior

The request with the correct media type is accepted and processed.

### Actual behavior

status code 415 is returned even for requests with the correct media type:

### How to Reproduce?

follow instructions at  [here](https://github.com/sostrich/keycloak-23-bug-reproducers).

**Comment by sostrich** [comment]
I used area "core" since I did not find a good area for extensions.

**Comment by shawkins** [comment]
From @pedroigor this should be resolved by #24986 - but this issue is logged against 23.0.5, which should have already included that fix.

**Comment by sostrich** [comment]
I think that's a slightly different error - here I'm getting a 415 response status code, whereas in #24986 the media type is accepted, but no content is returned, if I understand correctly.

I recommend the reproducer linked above, I think it's very easy to reproduce the bug with it.

**Comment by shawkins** [comment]
@pedroigor @sostrich @vmuzikar I have reproduced this in our HttpDistTest. It will work as expected if I switch to org.jboss.resteasy.reactive.server.multipart.MultipartFormDataInput rather than the classic version. What should be the path forward here:
- make the resteasy classic version still work
- document this under this issue or as part of #27057

**Comment by vmuzikar** [comment]
@shawkins Thanks for looking into this!

> make the resteasy classic version still work

I would not do that. We want to get rid of RestEasy Classic completely in the long run.

**Comment by shawkins** [comment]
This would also be addressed somewhat by #27032 as the resteasy classic multipart dependency would no longer be available leading to a clearer error.

**Comment by shawkins** [comment]
Resolving as covered by the existing migration note about not using resteasy classic classes.

**Comment by sostrich** [comment]
ah, I did not realize this was too a class I needed to change. Thank you!
