### ISSUE TITLE
Help message for custom password policy is not translated

### ISSUE THREAD

**Issue by jerrycooper** [keycloak/keycloak#26641]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

**Help message on custom password policy is not shown in GUI.** Only key for message is shown.

Place: Authentication->Policies tab. Icon with question mark in password policy row.

Problem:
![obrazek](https://github.com/keycloak/keycloak/assets/6493262/b6d8d09a-f5c1-430e-9b2f-e5a8448a63fb)

Our custom password policy provider has id "passwordPrefix".
We have our custom theme with the same key in .properties file as on the image and it is activated for the realm.

![obrazek](https://github.com/keycloak/keycloak/assets/6493262/0ed163b3-8738-455b-9e4c-38b8c5adeccb)

 I tried localization in realm too, but it doesn't function either.
 
![obrazek](https://github.com/keycloak/keycloak/assets/6493262/dca26641-70ac-47ba-a3b9-f623ea9d1048)

### Version

22.0.5, 23.0.5

### Expected behavior

Message from .properties file or translation is shown.

### Actual behavior

Only key is shown.

### How to Reproduce?

Deploy new password policy.
Add custom theme inherited from admin V2 with key for help message.
Deploy, see problem in gui.

**Comment by ssilvert** [comment]
@jerrycooper This is the code that renders the help text:
     
```
      labelIcon={
        <HelpItem
          helpText={t(`passwordPoliciesHelp.${id}`)}
          fieldLabelId={id!}
        />
```
 So your help text key should be `passwordPoliciesHelp.` plus the `id` of your password policy.  Are you sure that the `id` is `passwordPrefix`.?

Password policies are downloaded in the call to `serverinfo` when you first start the console.  If you go to the inspector in the browser and look at the response to `serverinfo` then you can search for `passwordPolicies`.  You should be able to find your custom policy and find the `id`.

**Comment by edewit** [comment]
2 things I have noticed, you added it to the message bundles, but I think in order for that to work you need to enable "Internationalisation" and if you put the messages in a theme, did you activate that theme in the realm settings?

**Comment by jerrycooper** [comment]
@ssilvert  The response looks fine with the same `id` I used.

![obrazek](https://github.com/keycloak/keycloak/assets/6493262/431d1df6-aea6-48ff-bb41-be0fe0b79857)

@edewit  The custom theme is activated for the realm (not master). 

![obrazek](https://github.com/keycloak/keycloak/assets/6493262/07358c7a-a29d-4026-ae96-cedbdd2dfc45)

I activated internationalisation too but it doesn't help either.

**Comment by jerrycooper** [comment]
@ssilvert  How are messages from .properties files loaded? Through some REST endpoint as password policies?

**Comment by jerrycooper** [comment]
I found the problem,
the endpoint that is called for resources is always the same resources/master/admin/en even though I log into a different realm.
When I have more realms, resources should be loaded for each realm separately.

**Comment by edewit** [comment]
I just tried this on the nightly version and it seems to work, can you see if that fixes it?

**Comment by jerrycooper** [comment]
Yes. In nightly build it is ok. Thank you
