### ISSUE TITLE
Text overflow in "edit message bundles" widget.

### ISSUE THREAD

**Issue by weltonrodrigo** [keycloak/keycloak#26655]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Long values for a key in the dialog don't get wrapped as expected. 
![Captura de Tela 2024-01-31 às 11 38 49](https://github.com/keycloak/keycloak/assets/1644644/6a367197-f284-4a6c-952d-4477321d2eb2)

### Version

23.0.2

### Expected behavior

Long values should have wrap correctly.

### Actual behavior

When using values for a key that are wider that the value text input they overflow to the right passing the limits of the widget.

### How to Reproduce?

In the edit message bundles dialog, add a long phrase with any key value.

**Comment by ssilvert** [comment]
@weltonrodrigo The latest version does wrap.  Can you give the nightly build a try?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by weltonrodrigo** [comment]
fixed in the nightly!
