### ISSUE TITLE
`LogoutEvent` is not fired on required UpdatePassword action 

### ISSUE THREAD

**Issue by mvoronov** [keycloak/keycloak#26658]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

`LogoutEvent` is not fired on `required UpdatePassword` action when `Sign out from other devices` is checked on UI.

### Version

23.0.5

### Expected behavior

`LogoutEvent` is fired after back-channel logout is done, in the same way as in `org.keycloak.services.resources.admin.RealmAdminResource#deleteSession`

### Actual behavior

Only back-channel logout is done, without firing `LogoutEvent`.

### Configure events to save
1. Go to `Realm settings` screen
2. Open `Events` tab
3. Under `Admin events settings` set `Save events` to `On`, click `Save events`

### Configure user's required actions
1. Edit existing user 
2. Go to `Details` tab
3. Add `Update Password` action to the `Required user actions` field
4. Save user

### Login
1. Login as a user configured with `Update Password` required action
2. Set values for `new password` and `confirm password` fields 
3. Check `Sign out from other devices` option, click `Submit` button
4. Go to `Events` open `Admin events` tab
5. No record is listed with `USER_SESSION` Resource type and	`DELETE` operation type

**Comment by lrozenblyum** [comment]
We also are affected by this issue, we subscribe to the LOGOUT events in our custom extension but don't receive them in case of the checkbox `Sign out from other devices` is ON on the Update password screen.

**Comment by lexcao** [comment]
I am glad to help this.
Before to fix it, I want to confirm the expect behavior.

The required action is triggered by the admin, but the checkbox `Sign out from other devices` is confirmed by the user, what event should we fire?
* Admin event for `delete` session
* Account event for `LOGOUT`

I think it more accurate as account event of `LOGOUT`.
@mposolda Wdyt?

--
By the way, I think we should handle all the cases that has `Sign out from other devices` checkbox not only `UPDATE_PASSWORD`, such as update_email, update_totp.

**Comment by mposolda** [comment]
@lexcao Sorry for late response. +1 for your suggestion. It is the user, who confirmed `Sign out from other devices`, so makes sense if the "user" event is triggered.

Also +1 to handle other events like `update_email` or `update_totp` if they have something like `Sign out from other devices` as well.

It can be nice if the logout event contains some detail with a note that logout was triggered by required action. For instance something like:
```
event.detail(Details.LOGOUT_TRIGGERED_BY_ACTION, RequiredAction.UPDATE_PASSWORD.name().toLowerCase());
```
But not a blocker.
