### ISSUE TITLE
Disallow removing required filters when searching for effective message bundle.

### ISSUE THREAD

**Issue by weltonrodrigo** [keycloak/keycloak#26653]
### Description

The current behavior is to list and search through the customized messages.
![image](https://github.com/keycloak/keycloak/assets/1644644/74e7d3f6-f262-48be-b227-dadd55142941)

The isn't any indication of how to find the message keys to override.

I believe a better approach would be to show all message bundle entries in the list and let the user override those she is interested in.

**Comment by ssilvert** [comment]
Hi @weltonrodrigo 

We have made some significant enhancements to the Localization tab.  I'd love to get your feedback and also make sure that the new functionality addresses your concerns.  Can you give the nightly build a try?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by weltonrodrigo** [comment]
> Hi @weltonrodrigo
> 
> We have made some significant enhancements to the Localization tab. I'd love to get your feedback and also make sure that the new functionality addresses your concerns. Can you give the nightly build a try? https://github.com/keycloak/keycloak/releases/tag/nightly

The new interface is great!

A nitpick: I must select all filters in the Effective message bundles' search for message bundle, but then I can close the filters  and get a broader selection.

In the image bellow, I filtered for pt_BR messages for keycloak.v3 login theme and then just closed the filters (via the x).

![image](https://github.com/keycloak/keycloak/assets/1644644/778bc725-f4ca-472e-b9ca-50eed1e30678)

**Comment by ssilvert** [comment]
This was originally an enhancement request, but the enhancement is already complete.  However, we consider the nitpick from  @weltonrodrigo to be a bug. So we will fix it under this issue.
