### ISSUE TITLE
Can't access hidden tabs on the left in admin UI

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#26667]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I use the tabs in the admin UI to navigate to the tabs on the right and some UI elements hide on the left, I can't go back to them until I reload the page

### Version

nightly, using Google Chrome

### Expected behavior

I can access all tabs in a UI

### Actual behavior

Tabs that are hidden on the left are inaccessible

### How to Reproduce?

* login as admin
* open realm settings
* size the browser window that doesn't show all tabs at a time
* use arrow to the right to go the "User registration" tab
* Click on the left arrow. Although it is enabled, nothing happens. I can't go to the "General" tab

![image](https://github.com/keycloak/keycloak/assets/3957921/5bbde022-cf57-4cf4-8a99-5d19c3776109)

### Anything else?

It is only broken when the menu on the left is visible. If I resize the window to be smaller and the menu on the left disappears, the arrow to the left starts to work again.

**Comment by edewit** [comment]
It's a patternfly issue that never got fixed, sometimes it does work though when you refresh the page. https://github.com/patternfly/patternfly-react/issues/8769

**Comment by ahus1** [comment]
I saw it happen pretty consistently, and I assume it is quite annoying to users. So I'd like this not to be closed this time.

I dared to add a milestone and a "priority/important" label, please change if you think otherwise.

**Comment by ssilvert** [comment]
@ahus1 I looked at the underlying PatternFly issue, and it was closed due to inactivity.  But hopefully, when we upgrade to PatternFly 5 this problem will go away.

I'm going to keep this open so we can revisit when that is done.  It definitely won't make it into Keycloak 24 so I removed the milestone.

I'm also going to link it to our PatternFly 5 epic so we know to check it out when the time comes.

**Comment by ahus1** [comment]
@ssilvert - thank you for the update. When I first opened it, I looked to me as if it might be a regression that would be good to fix before KC24.

With the explanation Erik and you provided, I understand that it isn't. While there doesn't seem to be an alternative, it is still sad that this would require at least an upgrade to PF5.

**Comment by edewit** [comment]
Stan had this issue as well, but I've never seem to be able to reproduce it. That's probably why it also got closed. So it might be fixed in PF5, but IDK, it's a weird issue

**Comment by ahus1** [comment]
As I forgot to add it when opening the issue: I'm using Fedora 39 with Chrome 121.0.6167.184

**Comment by ahus1** [comment]
I retested it today and found that this now working after the PF5 upgrade.
