### ISSUE TITLE
It is not possible to save the setting "Kerberos principal attribute" safely empty

### ISSUE THREAD

**Issue by cyberrranger** [keycloak/keycloak#26691]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If i remove the default value "userPrincipalName" from the Field "Kerberos principal attribute", i can save an empty value

![image](https://github.com/keycloak/keycloak/assets/21671762/15d1c83a-e4fd-4f71-8b3f-de1f4d9763e7)

check with CLI

kcadm.bat get components/UUID -r realm

i can't find config.krbPrincipalAttribute

but if i reload the admin ui, the default value is back

![image](https://github.com/keycloak/keycloak/assets/21671762/25feb320-7478-48b9-9aa4-1f674f7c3621)

and if i change now a other setting and save, this default value is saved

check with CLI
![image](https://github.com/keycloak/keycloak/assets/21671762/9579c2e4-5f19-4f14-9280-ed242ca20763)

### Version

23.0.5

### Expected behavior

the field should remain empty, it must not be overwritten with the default value again

### Actual behavior

The Kerberos principal attribute field is always filled even though it is saved empty

### How to Reproduce?

Create a new user-federation
activate Kerberos integration
clear Kerberos principal attribute
save
reload
Kerberos principal attribute is not empty

**Comment by cyberrranger** [comment]
I'm not entirely sure, but the default value seems to have been added with commit 57e51e9dd425d5a9da0064d6380b31ac497f9537 about 6 months ago

**Comment by pottah** [comment]
This is indeed very dangerous if you actually change something else because most likely you won't check that specific option before saving.

**Comment by cyberrranger** [comment]
That's exactly what happened to us, hence this issue. The troubleshooting was confusing.

**Comment by cyberrranger** [comment]
@rmartinc yes is an duplicate, Sorry, I hadn't found the issue, thanks for the update
