### ISSUE TITLE
Keycloak and MSAD: enabling account in MSAD does not propagate to Keycloak

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#26695]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Original report

If User Federation's "Edit Mode" is "WRITABLE", 
when an admin makes an Keycloak account disabled, the corresponding AD account becomes disabled.
Then, the admin make the AD account enabled again from AD side, the Keycloak account left disabled even when the "Synchronize all users" is executed.

Customers expects "Edit Mode"=WRITABLE syncs Keycloak user storage and LDAP server, but this behavior is annoying.

### Additional notes

When looking at `MSADUserAccountControlStorageMapper.isEnabled()` , it is clear that in case the account disabled in Keycloak DB, it will always takes precedence - https://github.com/keycloak/keycloak/blob/23.0.5/federation/ldap/src/main/java/org/keycloak/storage/ldap/mappers/msad/MSADUserAccountControlStorageMapper.java#L238-L248 . We may need to check whether to revisit this behaviour for the use-case mentioned by customer above.

Not sure if we need some "compatibility switch" on the MSAD mapper to achieve the backwards compatibility or if we can just switch to the behaviour above? There is possible option that we will have switch to always rely just on the "enabled" state from MSAD (so never call `super.setEnabled` or `super.isEnabled` ), which will make it easier to support backwards compatibility if needed...

### Version

23.0.5

### Expected behavior

See above

### Actual behavior

See above

### How to Reproduce?

See above

**Comment by mposolda** [comment]
Adding to Keycloak 25 for now. We can possibly postpone if we don't have time, but will be nice to give some priority as it is reported by customer.

**Comment by devsyw** [comment]
Is there any first aid for this problem?

**Comment by pedroigor** [comment]
@devsyw It is initially planned to Keycloak 25 and if fixed in time, backported to a 24 patch release. No concrete date yet.
