### ISSUE TITLE
When creating a user federation mapper changing the type doesn't change User Roles Retrieve Strategy

### ISSUE THREAD

**Issue by petjaniva** [keycloak/keycloak#26697]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

User Roles Retrieve Strategy doesn't change when mapper type is changed in user federation mapper creation screen.

### Version

At least versions 19, 22, 23 and nightly

### Expected behavior

When user switches from group-ldap-mapper to role-ldap-mapper User Roles Retrieve Strategy is changed to an appropriate value for that type.

### Actual behavior

Creating a new user federation mapper and first choosing group-ldap-mapper as the mapper type, then changing the mapper type to role-ldap-mapper doesn't change the value of User Roles Retrieve Strategy. If the value when changing the mapper type was the default LOAD_GROUPS_BY_MEMBER_ATTRIBUTE it stays as the value even when it isn't an choice in the dropdown menu for role-ldap-mapper.

### How to Reproduce?

Create a new user federation mapper, choose group-ldap-mapper as the type and switch to role-ldap-mapper.

**Comment by ssilvert** [comment]
I have verified this bug.
