### ISSUE TITLE
Invalid JSON response from sessions endpoint

### ISSUE THREAD

**Issue by saurabhnemade** [keycloak/keycloak#26707]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When you search for a session it gives wrong json response which is obviously not parsed by JSON.parse on UI and we get error on UI.

<img width="1797" alt="Screenshot 2024-02-01 at 4 10 45 PM" src="https://github.com/keycloak/keycloak/assets/17445338/3c7bb9a8-db8f-4151-a257-a79829c47294">

### Version

22

### Expected behavior

Json from `sessions` api should be correct.

### Actual behavior

Invalid json is being returned from api

### How to Reproduce?

just search for any valid session on admin console.

**Comment by sguilhen** [comment]
I've tried to reproduce in using latest nightly and the searched session was returned correctly - no invalid json response. (Basically logged into admin console and searched for the logged in user, or even client, and the session was always correctly returned).

I'm closing as not reproducible in the latest nightly release. If the issue still persists, please re-open and provide precise steps to reproduce it.
