### ISSUE TITLE
s3.bucket_prefix is not used using S3_PING

### ISSUE THREAD

**Issue by gregoryb** [keycloak/keycloak#26703]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

I run keycloak with following JAVA_OPTS:
`-Djgroups.s3.region_name=eu-west-1 -Djgroups.s3.bucket_name=mybucket -Djgroups.s3.bucket_prefix=keycloak/`

The ISPN directory is created at the root of the bucket.

I'm using jgroups-aws-2.0.1.Final.jar

### Version

23.0.3

### Expected behavior

ISPN directory should be created in s3://mybucket/keycloak/

### Actual behavior

ISPN directory is created in s3://mybucket/

`INFO  [org.jgroups.protocols.aws.S3_PING] (keycloak-cache-init) using Amazon S3 ping in region eu-west-1 with bucket 'mybucket' and prefix ''`

### How to Reproduce?

Add dependencies to the provider directory.

Use the following ENV

```
KC_CACHE=ispn
KC_CACHE_STACK=ec2
JAVA_OPTS_APPEND=-Djgroups.s3.region_name=eu-west-1 -Djgroups.s3.bucket_prefix=keycloak/ -Djgroups.s3.bucket_name=mybucket
```

**Comment by shawkins** [comment]
Based upon https://github.com/jgroups-extras/jgroups-aws/issues/318#issuecomment-1921567866 from a keycloak perspective you'd have to also provide a custom ispn config file with a stack referencing your env variable. If ispn implements the generalized environment variable handling, then this will no longer be required.
