### ISSUE TITLE
The page "Security Policy" contains a minor typo

### ISSUE THREAD

**Issue by EmmanuelHK** [keycloak/keycloak#26741]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The page with URL https://github.com/keycloak/keycloak/security/policy#supported-versions has a minor type.
At the bottom of the page it is written:
"... we encourage you to consider [Red Hat Buld of Keycloak](https://access.redhat.com/products/red-hat-build-of-keycloak/)..."
![2024-02-02 15_31_41-Security Policy_keycloak_GitHub](https://github.com/keycloak/keycloak/assets/105355722/05a32ca7-8684-41d8-8a9f-80582fb935b3)

### Version

23.0.5

### Expected behavior

We should read:
"... we encourage you to consider [Red Hat Build of Keycloak](https://access.redhat.com/products/red-hat-build-of-keycloak/)..."
(the "i" in "Build" is missing) 

### Actual behavior

The link to the BUILD page of RedHat works just fine, but there is a typo.

### How to Reproduce?

Access the following web-page:
https://github.com/keycloak/keycloak/security/policy#supported-versions

### Anything else?

Thanks for the great job delivering such a powerful tool!

**Comment by casdal** [comment]
Hi there @jonkoops ,

It's my first time here. I really like to contribute, if that is ok with @EmmanuelHK .

**Comment by jonkoops** [comment]
Sure, feel free to take this one 👍

**Comment by casdal** [comment]
Thank you very much. I learn a lot
