### ISSUE TITLE
String date attribute trying to parse as a Number

### ISSUE THREAD

**Issue by abdurrahmanekr** [keycloak/keycloak#26744]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have an user who have following attributes: 
<img width="882" alt="image" src="https://github.com/keycloak/keycloak/assets/15075759/d4fb17f2-7d1a-4f28-8600-c0dacfb42636">

I get this error when user trying to login:

```
keycloak-keycloak-1  | 2024-02-02 14:37:05,903 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-15) Uncaught server error: java.lang.NumberFormatException: For input string: "2023-10-02T07:46:34.000Z"
keycloak-keycloak-1  | 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
keycloak-keycloak-1  | 	at java.base/java.lang.Long.parseLong(Long.java:711)
keycloak-keycloak-1  | 	at java.base/java.lang.Long.valueOf(Long.java:1163)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.OIDCAttributeMapperHelper.getLong(OIDCAttributeMapperHelper.java:218)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.OIDCAttributeMapperHelper.convertToType(OIDCAttributeMapperHelper.java:186)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.OIDCAttributeMapperHelper.mapAttributeValue(OIDCAttributeMapperHelper.java:158)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.OIDCAttributeMapperHelper.mapClaim(OIDCAttributeMapperHelper.java:263)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.OIDCAttributeMapperHelper.mapClaim(OIDCAttributeMapperHelper.java:254)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.UserAttributeMapper.setClaim(UserAttributeMapper.java:103)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.setClaim(AbstractOIDCProtocolMapper.java:132)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.mappers.AbstractOIDCProtocolMapper.transformAccessToken(AbstractOIDCProtocolMapper.java:82)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.TokenManager$1.applyMapper(TokenManager.java:756)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.TokenManager$1.applyMapper(TokenManager.java:753)
keycloak-keycloak-1  | 	at org.keycloak.protocol.oidc.TokenManager$TokenCollector.lambda$accumulator$3(TokenManager.java:905)
keycloak-keycloak-1  | 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
keycloak-keycloak-1  | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

### Version

22.0.5

### Expected behavior

User should login without any interruption

### Actual behavior

User get 500 token error

### How to Reproduce?

Reproduce:
1. create an user with password
2. give updatedAt attribute that user as "2023-10-02T07:46:34.000Z"
3. open browser in incognito mode
4. try to login as this user
5. You get this error token:
6. 
<img width="993" alt="image" src="https://github.com/keycloak/keycloak/assets/15075759/ca952a9a-b4b2-4bf9-8bb2-c4c7fcc782f4">

**Comment by pedroigor** [comment]
@abdurrahmanekr We are missing more details how you are configuring the mapper. It is more likely that you are not setting the proper type in your mapper. If you set to `string` it should not fail to parse the value.

**Comment by abdurrahmanekr** [comment]
@pedroigor What is the mapper? Actually I used basicaly dockerized keycloak and ran it. This is docker-compose.yml:

```
version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --log-level="ALL"
```

You can see that the error occurs when you do something like in the "How to Reproduce?" section I mentioned in the issue without doing anything. I just add a string called updatedAt from the attributes field. Aren't key and value the only things I see in the Attributes field? There is no place to specify their types. Do I need to access mapper that I don't know about?

**Comment by pedroigor** [comment]
@abdurrahmanekr Thanks. Now I see what is going on.

The `updateAt` is a built-in attribute used by Keycloak and there is a built-in mapper to include that attribute into ID Tokens as per https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims.

The server expects that attribute to be set as the "number of seconds from 1970-01-01T00:00:00Z as measured in UTC until the date/time" therefore it must be a long.

I'm closing this issue as not an issue.

Thanks for the additional input.
