### ISSUE TITLE
Sessions list panel should have a refresh button

### ISSUE THREAD

**Issue by weltonrodrigo** [keycloak/keycloak#26755]
### Description

The sessions panel won't it now live and won't show new sessions created after the panel is loaded. It offers no way of refreshing the list other than reloading the panel (by navigating to another panel and back) or the application.

### Motivation

When doing tests, is quite frustrating having to click out of the sessions panel (to the groups or events or anything) and then back to sessions to force a reload of the sessions list.
![image](https://github.com/keycloak/keycloak/assets/1644644/649b438e-b1aa-4fbe-8343-f61f31ec82e9)

**Comment by jonkoops** [comment]
Could you [try the nightly](https://github.com/keycloak/keycloak/releases/tag/nightly)? I believe this has already been fixed for 24.

**Comment by weltonrodrigo** [comment]
tried nightly image quay.io/keycloak/keycloak@sha256:4cdc877eadf8a380cf5dd3325237323302adce6d288b4508d446de063ba416de and the behavior is the same (no refresh button, have to somehow update the view to fetch new sessions).

**Comment by jonkoops** [comment]
Looks like this might be fixed by #26599, I mistakenly thought this work was already merged.

**Comment by ssilvert** [comment]
#26599 is merged now and I've looked at it in the nightly build.  All set.  Closing the issue.
