### ISSUE TITLE
Maximum 100 resources with same URI checked when requesting permissions by URI

### ISSUE THREAD

**Issue by harterSe** [keycloak/keycloak#26780]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When requesting resource permissions via the token endpoint  with `permission_resource_format=uri` only a maximum of 100 resources with the same URI are evaluated and returned. This is a fix value and not effected when setting the `response_permissions_limit`  because  AuthorizationTokenService.getResourceListByUri uses Constants.DEFAULT_MAX_RESULTS for searching in the resource store.

https://github.com/keycloak/keycloak/blob/3f07a9522e28a746515c1fe8bdce9634e5d00763/services/src/main/java/org/keycloak/authorization/authorization/AuthorizationTokenService.java#L893-L894

### Version

23.0.5

### Expected behavior

`AuthorizationTokenService.getResourceListByUri` should use a customizable limit for searching in the resource store. For example `response_permissions_limit` when called via the token endpoint.  

### Actual behavior

At the moment `AuthorizationTokenService.getResourceListByUri` uses always `Constants.DEFAULT_MAX_RESULTS`

### How to Reproduce?

Here is a short example how we constructed our resource URIs and ran into the issue.
In this example there are multiple tenants that have resources ( Documents ) and users that have access to some of the documents of a tenant. We want to use URIs to check permission for a single resources and to obtain a list of all resources a user has access to.

We added two URIs to every resource.
```
"/tenant-1/documents/UUID"  ( to check the single resource)
"/tenant-1/documents" ( to get a list of all resources a user of tenant-1 has access )
```

Now if there are more than 100 resources with URI `/tenant-1/documents`. It is not possible to check permissions for the resources 101-xxx when requesting permissions with following curl request.

```
curl -X POST \
https://$KEYCLOAK/realms/$REALM/protocol/openid-connect/token \
-H "Authorization: Bearer $TOKEN" \
--data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
--data "audience=$CLIENT" \
--data "permission_resource_format=uri" \
--data "permission=/tenant-1/documents" \
--data "response_permissions_limit=1000" \
--data "response_mode=permissions"
```

### Anything else?

Regardless of the limitation of the same URI to a maximum of 100 occurrences.
I don't think we are the only ones who want to retrieve a list of all permissions for a particular resource type or URI such as "/tenant-1/documents".  So if there is an obvious problem with our approach of using URIs to achieve this functionality, we would be grateful for a hint on how to improve this.

**Comment by pedro-nicolau-carvalho** [comment]
My team is also using this approach to retrieve all authorized resources in a list endpoint. An alternative approach is welcome!

**Comment by BrunoSampaioDTx** [comment]
I've opened a discussion regarding a potential solution for this issue. The discussion includes a detailed description of the proposed implementation.

You can find the discussion here: #27119

**Comment by pedroigor** [comment]
@BrunoSampaioDTx @pedro-nicolau-carvalho Thanks. If you guys are willing to contribute with the solution you are proposing, I'm open to reviewing the changes and having this one included.

**Comment by tiago-alves139** [comment]
@pedroigor - maybe you can review this PR (https://github.com/keycloak/keycloak/pull/27240)
We would appreciate it a lot because our team really needs this improvement.
