### ISSUE TITLE
java.lang.IndexOutOfBoundsException when using relative path

### ISSUE THREAD

**Issue by mfisch04** [keycloak/keycloak#26799]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Request to /auth throws java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### Version

23.0.6

### Expected behavior

No exception

### Actual behavior

I use the bitnami helm chart with `httpRelativePath: "/auth/"` which causes an exception when making requests to https://url/auth but no exception to https://url/auth/

### How to Reproduce?

Deploy keycloak with `httpRelativePath: "/auth/"` and make a request to url/auth

### Anything else?

Also documented here:  https://github.com/aerogear/keycloak-metrics-spi/issues/190

**Comment by shawkins** [comment]
@vmuzikar do we generally leave these types of issue open on our side until we pick up the version of quarkus with a fix, or should I just go ahead and close this out?

**Comment by shawkins** [comment]
Sure. It looks like this in part is due to the intersection of resteasy classic and reactive - that is if you just use resteacy classic, there's no exception. I'll see if we can still get a fix to resteasy reactive.

**Comment by shawkins** [comment]
Will be addressed once we pick up https://github.com/quarkusio/quarkus/pull/38709 - which is currently slated for 3.9, so that may be a while unless we push for a backport that will make it into the 3.8 release.

**Comment by GenesisAtMac** [comment]
Until this is fixed, I added the following rule to our NGINX ingress controller:

```
rewrite /our_keycloak_path$ /our_keycloak_path/ redirect;
```

**Comment by michbeck100** [comment]
Will the fix be backported to 23.x?

**Comment by farcop** [comment]
@michbeck100 https://github.com/keycloak/keycloak/pull/27037#issuecomment-1954046494

**Comment by michbeck100** [comment]
@farcop https://github.com/quarkusio/quarkus/pull/38981
