### ISSUE TITLE
User profile 'uri' validator not working

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#26792]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When adding a new file in the user profile configuration of a realm, I can add a `uri` validator. This validator rejects all URIs.

### Version

nightly

### Expected behavior

When adding the `uri` validator, valid URIs should accepts, and everything else rejected

### Actual behavior

No values are accepted

### How to Reproduce?

1. add a new field `blog` 
2. add a validation `uri` for the field
3. in the admin view, enter `https://example.com` as a URI -> failure

### Anything else?

When calling the validators, it seems they are always called with a collection, while the current implementation of `UriValidator` doesn't extend `AbstractSimpleValidator` which supplies this behavior.

**Comment by ahus1** [comment]
@mposolda / @pedroigor - added this new bug to the user profile board and the 24.0.0 release milestone for now so that it is not missed in triaging for the upcoming release. Feel free to change during triaging if this is not the case.

**Comment by pedroigor** [comment]
@ahus1 Thanks. i'll work on it.
