### ISSUE TITLE
Upgrade to 23.0.5 gives 403 after SSO redirect

### ISSUE THREAD

**Issue by karlheld** [keycloak/keycloak#26809]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We are using Keycloak for an auth on a single page application. That is: reaching out to the page -> redirect to Keycloak login Page -> Redirect back after login to origin Page with Token.
This used to work fine with version 22.0.5 but after Upgrade to 23.0.3 we are getting redirected correctly but seeing a 403 Page.

### Version

23.0.3

### Expected behavior

No 403 after redirect

### Actual behavior

403 with 23.0.3

### How to Reproduce?

reaching out to the page -> redirect to Keycloak login Page -> Redirect back after login to origin Page that is now 403

**Comment by jonkoops** [comment]
Did you try the latest version of Keycloak as well? There have been several patch releases since 23.0.3.

**Comment by rmartinc** [comment]
Can you please add more details? Error log or something that can help us?

**Comment by karlheld** [comment]
@jonkoops We checked now version 23.0.6. We are seeing the same issue as before.
@rmartinc There is not much what we see in our Server logs. This is what we get when we successfully logged in and redirected:
`o.k.adapters.OAuthRequestAuthenticator   :    {"error":"invalid_grant","error_description":"Code not valid"}
o.k.adapters.OAuthRequestAuthenticator   : failed to turn code into token`

**Comment by rmartinc** [comment]
I would try to set the logger for `org.keycloak.protocol.oidc` to TRACE and try to guess why the code is detected as invalid by the server. As commented with this information we cannot do anything.

**Comment by mposolda** [comment]
I am closing as the requested information was not added.

@karlheld Please re-open if still seeing this issue, but in that case, please add the details on what is added to the server.log of your Keycloak server once you enable the logging as requested by @rmartinc in previous comment. No need to send the whole server.log here, but at least the snippet, which is logged during unsuccessful authentication to your server. See for more details for how to enable logging: https://www.keycloak.org/server/logging

**Comment by lupmit** [comment]
Hi @karlheld how did you fix that? I got the same issue when upgrading to v26
