### ISSUE TITLE
Freemarker erroneously escapes/sanitizes URL in template.ftl (&amp;)

### ISSUE THREAD

**Issue by dominiktopp** [keycloak/keycloak#26826]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Keycloak 23.0.x introduced a script in template.ftl
```html
<script type="module">
    import { checkCookiesAndSetTimer } from "${url.resourcesPath}/js/authChecker.js";

    checkCookiesAndSetTimer(
        "${authenticationSession.authSessionId}",
        "${authenticationSession.tabId}",
         "${url.ssoLoginInOtherTabsUrl}"
    );
</script>
```
What the browser sees when triggering login
```html
<script type="module">
    import { checkCookiesAndSetTimer } from "/auth/resources/pss9g/login/keycloak/js/authChecker.js";

    checkCookiesAndSetTimer(
        "173d8521-afb5-421c-b0ca-5bb2e4ebc22e",
        "lFfEnCIB5EQ",
        "/auth/realms/testRealm/login-actions/restart?client_id=gui&amp;tab_id=lFfEnCIB5EQ&amp;skip_logout=true"
    );
</script>
```

In some cases checkCookiesAndSetTimer does `location.href = "/auth/realms/testRealm/login-actions/restart?client_id=gui&amp;tab_id=lFfEnCIB5EQ&amp;skip_logout=true" which leads to broken requests because of the escaped/sanitized &s (ampersands).

### Version

23.0.4

### Expected behavior

The rendered template.ftl should contain the url with & instead of &amp;amp;

### Actual behavior

The rendered template.ftl contains the url with &amp;amp; instead of &

### How to Reproduce?

- Go to login page
- open DevTools
- search for "checkCookiesAndSetTimer" in HTML

### Anything else?

Escaping happens in `freemarker.core.DollarVaiable#accept(Environment)` in line 68: `markupOutputFormat.output(s, out);`

**Comment by rmartinc** [comment]
Hi @dominiktopp!

You are right, but I have checked and it seems (at least with chrome and firefox) that the URL arrives OK, so browsers are lenient and will accept wrongly HTML-encoded strings in the `location.href`. That's why the tests are working correctly. If you want just send a PR adding this

```diff
diff --git a/themes/src/main/resources/theme/base/login/template.ftl b/themes/src/main/resources/theme/base/login/template.ftl
index 188cea5960..d28cf40eb4 100644
--- a/themes/src/main/resources/theme/base/login/template.ftl
+++ b/themes/src/main/resources/theme/base/login/template.ftl
@@ -41,7 +41,7 @@
             checkCookiesAndSetTimer(
               "${authenticationSession.authSessionId}",
               "${authenticationSession.tabId}",
-              "${url.ssoLoginInOtherTabsUrl}"
+              "${url.ssoLoginInOtherTabsUrl?no_esc}"
             );
         </script>
     </#if>
```
I don't think we need tests for this. Just check manually that URL is OK with the ampersands and we'll check that tests are still working OK.

**Comment by dominiktopp** [comment]
Hi @rmartinc,

PR created :)

Yes, Browsers accept the URL but they interpret is as
path: /auth/realms/testRealm/login-actions/restart
query params:
- client_id=gui
- amp;tab_id=lFfEnCIB5EQ&
- amp;skip_logout=true
where `amp;` is part of the query param name.

**Comment by rmartinc** [comment]
@dominiktopp I just tested it, and the server endpoint receives OK the parameters client_id, tab_id and skip_logout (but probably because it's just used in location.href). Thanks for the PR!

**Comment by rmartinc** [comment]
I have checked again and the parameters are interpreted OK, but the query string arrives incorrectly. The query map using local env is `{skip_logout=[true], tab_id=[CRD7xqZFerg], amp=[, ], client_id=[security-admin-console]}`. The `amp` is there and it's not strange that your WAF is avoiding that request. I'll approve your PR when you sign it. Thanks again!
