### ISSUE TITLE
Keycloak development server doesn't work on Windows

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#26832]
See https://github.com/keycloak/keycloak/pull/26025 for details.

**Comment by dipeshsingh253** [comment]
@jonkoops , Do you have any idea where is the code related to starting the server on port `8180`? is it part of `start-server.js` or some other script that is called internally from `start-server.js`, the issue according to me is that `start-server.js` is trying to `authenticateAdminClient()` from the server:8180, but it's not accessible. it is accessible in Linux.

https://github.com/keycloak/keycloak/blob/516bfbe8968c1e3c7caca9daef9be1511639b120/js/apps/keycloak-server/scripts/start-server.js#L105C1-L108C6

**Comment by jonkoops** [comment]
The script that starts the server is contained within `start-server.js`. The server itself is the nightly build of Keycloak.

**Comment by dipeshsingh253** [comment]
@jonkoops , do you think it can be a problem with the node's spawn on windows? I tried this but there was neither output nor error in the console. I have defined this method in start-server.js and tried to call it randomly just to verify whether this spawn is working or not.

```js
function verifyChild() {
  // const keycloakExecutablePath =
  //   "D:\\dipesh-temp\\keycloak\\js\\apps\\keycloak-server\\server\\bin\\kc.bat";
  const child = spawn("dir", { shell: true });

  child.stdout.on("data", (data) => {
    console.log(`stdout: ${data}`);
  });

  child.stderr.on("data", (data) => {
    console.error(`stderr: ${data}`);
  });

  child.on("error", (error) => {
    console.error("Error executing command:", error);
  });

  child.on("close", (code) => {
    console.log(`Child process exited with code ${code}`);
  });
}
```

**Comment by jonkoops** [comment]
It could be, but I really have no way of validating it.

**Comment by dipeshsingh253** [comment]
Okay. Let me try if I get any leads I will update here !!!

**Comment by dipeshsingh253** [comment]
@jonkoops , I have raised PR, Now I can execute the script on Windows, can you verify whether it works on Linux or not? I don't have access to any Linux device currently.

**Comment by jonkoops** [comment]
Yes, that all still seems to work for me on both Linux and macOS. Nice catch on the `shell` option, totally missed that!

**Comment by dipeshsingh253** [comment]
Thanks @jonkoops, I have signed-off the commit, and now you can move ahead with merging.
