### ISSUE TITLE
Vulnerability: IN1-JAVA-IOVERTX-6209366 - io.vertx:vertx-core

### ISSUE THREAD

**Issue by vsun757** [keycloak/keycloak#26837]
### Description

Dear Keycloak Security Team,

I would like to bring to your attention IN1-JAVA-IOVERTX-6209366 - io.vertx:vertx-core, which affects Keycloak version 23.0.4. The package is located at opt/keycloak/lib/lib/main/io.vertx.vertx-core-4.4.6.jar, and the installed version is 4.4.6.

**Comment by vsun757** [comment]
I would also like to add IN1-JAVA-IOVERTX-6231834 - io.vertx:vertx-core to this report as well

**Comment by abstractj** [comment]
> Dear Keycloak Security Team,
> 
> I would like to bring to your attention IN1-JAVA-IOVERTX-6209366 - io.vertx:vertx-core, which affects Keycloak version 23.0.4. The package is located at opt/keycloak/lib/lib/main/io.vertx.vertx-core-4.4.6.jar, and the installed version is 4.4.6.

@vsun757 Could you please be more specific about which CVE we are discussing?

**Comment by vsun757** [comment]
Unfortunately there isn't a CVE available for this vulnerability

**Comment by vsun757** [comment]
Do you need a CVE in order to fix the vulnerability @abstractj ?

**Comment by abstractj** [comment]
> Do you need a CVE in order to fix the vulnerability @abstractj ?

How we are supposed to know if the project is vulnerable or affected without knowing the details of the issue? The ID IN1-JAVA-IOVERTX-6209366 was not found anywhere.

**Comment by vsun757** [comment]
@abstractj I looked and realized the Snyk report is indeed nowhere to be found. You were right.

I was able to find them another way, here: https://security.snyk.io/package/maven/io.vertx:vertx-core

The two vulnerabilities on this page that are applicable to keycloak are the resource exhaustion and denial of service vulnerabilities

**Comment by jhonis** [comment]
@abstractj This seems to be the same CVE you mentioned in the issue #26791. It comes from quarkus dependencies so, we might need to either wait for them or force the update in keycloak pom.xml.

**Comment by abstractj** [comment]
Thanks for bringing this to my attention @jhonis and you are correct. @vsun757 I'm closing this issue as superseded by https://github.com/keycloak/keycloak/issues/26791
