### ISSUE TITLE
User needs `view_realm` role to see the new user profile

### ISSUE THREAD

**Issue by pkeuter** [keycloak/keycloak#26866]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

A user that does not have `view_realm`-access does not have access to the `new` user profile page in the admin ui. I think this is because with the `view-realm` rights, the call to `admin/realms/<realm>` will show a lot more information, including the `attributes.userProfileEnabled`-field.

Maybe it's necessary to expose this field even without rights?

### Version

23.0.4

### Expected behavior

A user that does not have access to view all realm-settings should be able to modify users in the new user-profile.

### Actual behavior

The user sees the "old" user profile.

### How to Reproduce?

1. Enable user-profile in realm settings
2. Create a user with `query-groups` and `query-users` role.
3. Create another user and go to that user as admin, and as normal user. You will see different pages:

Without rights:
![image](https://github.com/keycloak/keycloak/assets/433441/91fcd8a0-cd3f-41d4-a003-452ca99c7c3d)

With rights:
![image](https://github.com/keycloak/keycloak/assets/433441/27030bbf-e0e7-475e-b3f8-2ff695197351)

4. Enable `view-realm` for the specific user. It now sees the same page (but also a lot more which that user should not be able to see)

**Comment by edewit** [comment]
This is fixed in the nightly version

**Comment by pkeuter** [comment]
Got it, thanks! I believe this will then be in version 24.0.0? Is there any sight on when this version will be released?

**Comment by jonkoops** [comment]
No definitive date, but likely in a couple of weeks.

**Comment by pkeuter** [comment]
Confirmed that this works in nightly.
