### ISSUE TITLE
Admin console keeps loading

### ISSUE THREAD

**Issue by robertoneto-senior** [keycloak/keycloak#26865]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

My keycloak is configurated with:

```
  CACHE_OWNERS_AUTH_SESSIONS_COUNT: "2"
  CACHE_OWNERS_COUNT: "2"
  JAVA_OPTS_APPEND: -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
  JGROUPS_DISCOVERY_PROTOCOL: kubernetes.KUBE_PING
  KC_CACHE_STACK: kubernetes
  KC_DB: postgres
  KC_DB_SCHEMA: keycloak
  KC_DB_URL: jdbc:postgresql://xxxxxxxx:5432/keycloak
  KC_DB_USERNAME: senior
  KC_HOSTNAME_ADMIN_URL: https://xxxxx
  KC_HOSTNAME_DEBUG: "true"
  KC_HOSTNAME_URL: https://xxxx
  KC_PROXY: edge
  KEYCLOAK_ADMIN: admin
  KUBERNETES_NAMESPACE: keycloak
  PROXY_ADDRESS_FORWARDING: "true"
```

But when I access the admin console page a Javascript console error shows:

```
Uncaught TypeError: Erro ao resolver o especificador de módulo “react/jsx-runtime”. Especificadores de módulo relativos devem começar com  “./”, “../” ou “/”.
```

And the admin console keeps in "loading state".

![image](https://github.com/keycloak/keycloak/assets/104595368/34fe2b22-fc33-404e-8ecb-63cbcbd6804d)

In latest versions of Chrome and Edge works!
In Firefox 102.15.0esr isn't working! (I already tried to clean data/cookies, and continues to not working)

### Version

23.0.6

### Expected behavior

To see the user/password to enter in admin console

### Actual behavior

Admin console freezes in loading state

### How to Reproduce?

Put keycloak behind a nginx proxy (upstream http), public https access

**Comment by DeltaFox0018** [comment]
Hi, I tried and with version 23.0.6 on Firefox 122.01 I don't have any kind of problem

From the keycloak logs do you have any particular messages?

Have you tried updating firefox?

**Comment by robertoneto-senior** [comment]
Updated Firefox to 122.0.1 and the problem was solved.

**Comment by robertoneto-senior** [comment]
Updated Firefox to 122.0.1 and the problem was solved.
