### ISSUE TITLE
Session not found for introspect and revoke token for a single client id in a realm

### ISSUE THREAD

**Issue by ratls-shashank** [keycloak/keycloak#26890]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Hello,

I have keycloak setup on Kubernetes with KUBE_PING as cache stack, the issue I'm facing is the token created for client_credentials grant for a specific client only is not getting validated or revoked. I receive the session state key in response, but while introspection or revoking, I get the error "Session not found". This is happening only for one client ID, for other client IDs in the same realm, and user authentication, everything is working fine. Keycloak is deployed in openshift with KUBE_PING. Keycloak version is v21.1.1. Please if someone could help me with this

### Version

21.1.1

### Expected behavior

The token should get introspected and revoked

### Actual behavior

The token does not get introspected or revoked with "Session not found" error in logs

### How to Reproduce?

Unfortunately I haven't been able to reproduce this, with a different client, also imported the same client JSON to another environment and was not able to reproduce this

**Comment by stianst** [comment]
`client_credentials` does not by default get a refresh token, which means it doesn't get a session. Currently we don't support revoking individual tokens, and can only revoke tokens that are associated with a session. The recommendation here is to use a short expiration on access tokens, and have service accounts retrieved new tokens as needed.

You can configure a service account (`client_credentials`) to use refresh tokens, under advanced options for the client (`Use refresh tokens` option). However, I would not recommend doing that as it's not normal for service accounts to leverage refresh tokens and instead just fetch new tokens with its credentials.

It is very curious that you say it works in some environments though, could you check if the client has the use refresh tokens option enabled?

**Comment by ratls-shashank** [comment]
@stianst @rmartinc ,
Thanks for replying

@stianst yes I have explicitly enabled use refresh tokens, the confusing part is,  I have exported and imported the same client configuration on the same environment (Just changed the client id) and even that works, I have tried everything possible but the client_credentials grant only for one specific client id does not work. I do get a successful response, but introspection and revoke don't work. 
@rmartinc even I'm not able to reproduce the scenario with any other client id albeit being on the same environment

Its worth noting that single client id has majority of the sessions, could it be a caching issue? If it is could you help me with clearing the cache. We are using kube_ping as cache mechanism

**Comment by ratls-shashank** [comment]
Hi, please help us with this issue, since we have not been able to make any inroads for this issue, we're not able to figure out why only one single client is giving this issue

**Comment by sschu** [comment]
@ratls-shashank Without a way to reproduce this on our site, it is hard to help you. I think you need to experiment and find out what is special about this specific client. You could for example take a client that currently works and gradually transform it into the client that doesn't work (take over the configuration, even rename it as a last step).

**Comment by ratls-shashank** [comment]
Hi @sschu so I've already tried to export and import the client inside the same realm, just a different client id, and with the new client, all seems to be working fine. So I'm not really sure how can I reproduce this issue

**Comment by ratls-shashank** [comment]
So we have tried to rename the client and add a new client with the same name, the renamed client worked, but the new client with the same name didn't work. We did a restart of the entire cluster and for the first few minutes introspect and revoke were working, and after that it stopped, can it be a load issue?

**Comment by ratls-shashank** [comment]
So we have found out the root cause of the issue, it had nothing to do with the client, but, it was revoke of the refresh token that was causing the issue, it was clearing all the sessions. Thanks for all the help here.
