### ISSUE TITLE
Access tokens includes nonce claim

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#26893]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The `nonce` claim is not relevant to Access Tokens, only ID Tokens.

### Version

main

### Expected behavior

When client is passing the nonce parameter it should only be added to the ID Token

### Actual behavior

When client is passing the nonce parameter it is added to the ID Token as expected, but also added to the Access Token, which is not expected.

### How to Reproduce?

See https://github.com/keycloak/keycloak/blob/cd1e4831340dc195ba43af97412a9a6f41dcdb4b/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L987

**Comment by pedroigor** [comment]
Being an OIDC-specific param/claim/mechanism, I agree it does not make sense in access tokens. Perhaps @mposolda has more details if there is a reason for it.
