### ISSUE TITLE
UPDATE_EMAIL action token handling should allow the user to resume its navigation to the redirect uri

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#26900]
### Description

Let be a Keycloak client (a web application) without home url configured.

A user is given a link to the client (web application). This link contains additional informations. Let's name it the rich link.
1. By clicking on the rich link, the user lands on the application
2. The user being unauthenticated, the application redirects the user to Keycloak with a redirect uri containing the famous rich link
3. The user authenticates successfully
4. Keycloak redirects the user to the rich link

So far so good.
Now if an admin takes this user's account and adds `UPDATE_EMAIL` as a required user action on a realm where `Verify email` is enabled, the process is as follow:
1. By clicking on the rich link, the user lands on the application
2. The user being unauthenticated, the application redirects the user to Keycloak with a redirect uri containing the famous rich link
3. The user authenticates successfully
4. The user is asked to enter its email address:
![2024-02-08_10-19_1](https://github.com/keycloak/keycloak/assets/2890843/e6fdb8a4-ac6a-4e18-bb43-38e41485dfb2)
5. A new screen tells the user the confirmation email has been sent:
![2024-02-08_11-11](https://github.com/keycloak/keycloak/assets/2890843/4fe5f949-782d-437c-a85b-bfc8f400cd40)
6. User finds the confirmation link in its mailbox:
![2024-02-08_10-20_1](https://github.com/keycloak/keycloak/assets/2890843/e502b51e-436d-4e77-a4bf-14fd06398026)
7. User triggers the confirmation link and is shown the following screen:
![2024-02-08_11-11_1](https://github.com/keycloak/keycloak/assets/2890843/8df96e21-be5d-415b-9194-a7631862e896)

There is no action allowing the user to resume its navigation. The rich link is lost.

As a user having verified my email via the UPDATE_EMAIL required action, I want Keycloak to allow me to resume my navigation to the rich link.

### Details

It looks like something similar has been done in https://github.com/keycloak/keycloak/pull/23303 for `VerifyEmailActionTokenHandler`:

https://github.com/keycloak/keycloak/blob/ed96b13312198569b7e68647eefe44d5ee24c739/services/src/main/java/org/keycloak/authentication/actiontoken/verifyemail/VerifyEmailActionTokenHandler.java#L112-L117

**Comment by SergeyZubatkin** [comment]
Hi @reda-alaoui 
Recently we have migrated to the latest Keycloak and faced interesting behavior related to your changes.
Not sure that approach you introduced is correct in terms of auth flow, redirect_uri purpose is not in redirecting user back to original url (rich link in your example), I assume you use PKCE flow with some ui interceptor which handles any redirect_uri (exchange code for access token) and everything works fine, no matter where Keycloak redirects back after login.

We use implicit flow with form_post where redirect_uri = https://SITE/auth-callback
Before your change "Back to application" button on Email confirmation page led to client home page -> browser just started login flow again.
Right now in 25.0.6 "Back to application" leads to "auth-callback" which is not correct, auth-callback purpose is handling auth postbacks with code/tokens.

As far as I understand as a storage for user's origin url devs usually use cookie, local/session storage or state parameter.
