### ISSUE TITLE
Signed JWT authentication EDSA ( ES256 ) algorithm publickey.pem import error.

### ISSUE THREAD

**Issue by mritunjay-kum** [keycloak/keycloak#26918]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

The device will be authenticated using a signed JWT. The device will only share its public key to match the sig i.e. EDSA algo ( es256). I am using keycloak 22v, using admin console when I try to import a .pem file having a public key I get the above error. I have tried generating es256 keystore.jks which works perfectly fine. Any guidance will be helpful. Thankyou @everyone
ERROR [org.keycloak.services.error.KeycloakErrorHandler] 
(executor-thread-73) Uncaught server error: 
java.lang.RuntimeException: 
org.keycloak.common.util.PemException: 
java.security.spec.InvalidKeySpecException: encoded key spec not 
recognized: algorithm identifier 1.2.840.10045.2.1 in key not 
recognised

### Version

22

### Expected behavior

Public-key.pem Import should happen and Keycloak stores it, when a request comes with client assertion it matches the signature with it and returns access token

### Actual behavior

Import of publickey for ES256 algorithm is not working. It is throwing an error, whereas we try to import keystore.jks are able to generate the access token, but the keystore generated from Keyclaok always having RS# algorithm. Which again throws error.

### How to Reproduce?

trying to import publickey.pem file in client key tabs for ES256 it gives error while import , while rest other algo key is getting imported. Use openSSL commond to generate keys.

**Comment by jonkoops** [comment]
As outlined in the issue template we only accept bug reports tested against the latest version of Keycloak. If the issue is reproducible in the latest version, let us know.

**Comment by mritunjay-kum** [comment]
> As outlined in the issue template we only accept bug reports tested against the latest version of Keycloak. If the issue is reproducible in the latest version, let us know.

Yes its happening in latest version

**Comment by jonkoops** [comment]
Thanks for confirming that, I will re-open the issue so it can be triaged.

**Comment by tnorimat** [comment]
@mritunjay-kum Hello, this issue is the same as [the other issue](https://github.com/keycloak/keycloak/issues/26936).
IMO, current Keycloak only supports RSA key import from external keystore (.jks, .pem).

**Comment by rmartinc** [comment]
@mritunjay-kum when importing a PEM file is always managed as a RSA key. Covert that key in a jwks file and import that file with format JSON Web Key Set. For more information check this other issue: https://github.com/keycloak/keycloak/issues/12344.
