### ISSUE TITLE
Deleting sub-realm roles throw errors (even tho it succeeded)

### ISSUE THREAD

**Issue by SalemWafi** [keycloak/keycloak#26915]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

I know that when you send a request to delete a sub-realm role, Keycloak takes some time to go over all its resources (such as users/role_policies/etc) and makes sure to delete that sub-realm role reference from all of them which takes a while if you have a lot of clients, resources, and data in your sub-realm, however, that is another issue for another day as sometimes takes like 1-2 minutes to delete one sub-realm role.
My main issue now for this ticket is that the sub-realm role delete request usually returns an error even when the sub-realm role is deleted correctly.

For example, once it returned `404 {"error":"Could not find role with id"}` I assume that is because it deleted the sub-realm role and it retried again for whatever reason which caused that error, and that is what it got returned to me.
Another time, it gave me `500 {"error":"unknown_error"}`.
Currently, I'm using Keycloak v23.0.6

These pictures are for one of these errors (again keep in mind that the sub-realm role got deleted successfully but the request returned an error)
 
 
<img width="948" alt="image" src="https://github.com/keycloak/keycloak/assets/32916450/1b488e58-9482-48f7-b652-f313d5492151">

<img width="787" alt="image" src="https://github.com/keycloak/keycloak/assets/32916450/33bae3fc-c391-492d-abb1-37fb21c318ba">

<img width="692" alt="fffffr" src="https://github.com/keycloak/keycloak/assets/32916450/c8513d51-bf61-45de-92b2-5613338498ce">

<br><br>
Side rant 🗣️: Deleting sub-realm roles has been not a fun experience since I have been using Keycloak (which was since v18)

### Version

23.0.6

### Expected behavior

Deleting a sub-realm role should return success 200

### Actual behavior

Deleting sub-realm role returns an error even when it is successfully deleted 

### How to Reproduce?

Create a sub-realm that has 200 users and 7 clients and each client should have 1000 role_policies,
then create a sub-realm role and delete it.

**Comment by sschu** [comment]
You are talking about normal realm roles, aren't you? Is this specific to realm roles or the same with client roles?

**Comment by SalemWafi** [comment]
yes, I'm talking about normal realm roles.
Idk about the client roles if the issue happens with them as well or not.

**Comment by SalemWafi** [comment]
@sschu actually I just tested the case for the client role deletion and it worked fine.
I have this client that has 1700 role policies and the request took 27s and returned success no-content 204


<img width="837" alt="image" src="https://github.com/keycloak/keycloak/assets/32916450/9edc1c05-6d4e-431d-8335-e8ef52be6e7b">

**Comment by sschu** [comment]
And for realm roles, the same process always causes an error or just occasionally?

**Comment by SalemWafi** [comment]
The error happens always with the Keycloak server that has 200 users, 7 clients, and 7000 role_policies in total. Also, note that the request takes about 1.1 ~ 2min before it returns an error message (I assume because there are a lot of role policies to check against).
A year ago, it used to happen occasionally like 1 out of 4 times.

Also, I just tested it with another Keycloak server that has 50 users, 5 clients, and 500 role policies in total and it didn't fail at all, and the requests took only 5 ~ 8s and returned 204 success.

**Comment by sschu** [comment]
Do you have some kind of tracing agent that you could use to find out which kind of DB queries are executed during a deletion?

**Comment by SalemWafi** [comment]
currently working on implementing tracing and will get back to you when we have it ready.

**Comment by ssilvert** [comment]
Removing UI labels as this doesn't appear to be a problem with the UI itself.

**Comment by EnneS** [comment]
Hello,

I encounter the exact same issue, currently on Keycloak v23.0.7. I have ~300 users and ~1500 realm roles for 3 keycloak instances. When deleting a role, the request "time outs" after 1 minute responding with sometimes a 401 or 404, 500 error.
What's funny is that after force-killing 2 out of the 3 keycloak instances and directly sending a delete role request we successfully get a 200 response (although after a couple dozens seconds, but still!).
I traced the DB requests, which seem to execute rather quickly :
![image](https://github.com/keycloak/keycloak/assets/23013153/f5aa2dad-59bf-46c6-a811-8f91d698228c)

I then thought of the infinispan cache being the culprit, got this capture of the JVM profiling for a delete role request (executed when a single keycloak instance was running) :
![image](https://github.com/keycloak/keycloak/assets/23013153/436431cf-07d4-40d5-97a2-851325058879)

Clearly, it seems like the infinispan operations are taking quite a rather big chunk of the execution time. Which would make sense since I am observing a slower request the more keycloak instances are running.


When deleting a role on an other fresh empty realm, the role deletion is almost instant.

**Comment by SalemWafi** [comment]
@sschu 
Not sure how helpful is this, but we did delete action for a sub-realm role and got 401 (however, the realm role is deleted successfully):<br>
<img width="757" alt="image" src="https://github.com/keycloak/keycloak/assets/32916450/7ce3b59c-0b71-43cb-b128-4cb585f34679">

And we got the Keycloak DB logs thro "Azure Database for PostgreSQL flexible server" which were as follows:

```
"3/5/2024, 9:52:14.960 PM","2024-03-05 21:52:14.876 UTC-65e78fda.4020LOG:  AUDIT: SESSION,46,1,WRITE,INSERT,,,""insert into ADMIN_EVENT_ENTITY (AUTH_CLIENT_ID,IP_ADDRESS,AUTH_REALM_ID,AUTH_USER_ID,ERROR,OPERATION_TYPE,REALM_ID,REPRESENTATION,RESOURCE_PATH,RESOURCE_TYPE,ADMIN_EVENT_TIME,ID) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)"",<not logged>"
"3/5/2024, 9:52:14.876 PM","2024-03-05 21:52:14.867 UTC-65e78fda.4020LOG:  AUDIT: SESSION,45,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.867 PM","2024-03-05 21:52:14.855 UTC-65e78fda.4020LOG:  AUDIT: SESSION,44,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.855 PM","2024-03-05 21:52:14.853 UTC-65e78fda.4020LOG:  AUDIT: SESSION,43,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.853 PM","2024-03-05 21:52:14.846 UTC-65e78fda.4020LOG:  AUDIT: SESSION,42,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.847 PM","2024-03-05 21:52:14.839 UTC-65e78fda.4020LOG:  AUDIT: SESSION,41,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.839 PM","2024-03-05 21:52:14.837 UTC-65e78fda.4020LOG:  AUDIT: SESSION,40,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.837 PM","2024-03-05 21:52:14.823 UTC-65e78fda.4020LOG:  AUDIT: SESSION,39,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:52:14.823 PM","2024-03-05 21:51:07.077 UTC-65e78fda.4020LOG:  AUDIT: SESSION,38,1,WRITE,UPDATE,,,update POLICY_CONFIG set VALUE=$1 where POLICY_ID=$2 and NAME=$3,<not logged>"
"3/5/2024, 9:51:07.077 PM","2024-03-05 21:51:07.076 UTC-65e78fda.4020LOG:  AUDIT: SESSION,37,1,WRITE,DELETE,,,delete from SCOPE_MAPPING where ROLE_ID = $1,<not logged>"
"3/5/2024, 9:51:07.076 PM","2024-03-05 21:51:07.074 UTC-65e78fda.4020LOG:  AUDIT: SESSION,36,1,WRITE,DELETE,,,delete from KEYCLOAK_ROLE where ID=$1,<not logged>"
"3/5/2024, 9:51:07.074 PM","2024-03-05 21:51:07.065 UTC-65e78fda.4020LOG:  AUDIT: SESSION,35,1,WRITE,DELETE,,,delete from GROUP_ROLE_MAPPING where ROLE_ID=$1,<not logged>"
"3/5/2024, 9:51:07.065 PM","2024-03-05 21:51:07.064 UTC-65e78fda.4020LOG:  AUDIT: SESSION,34,1,WRITE,DELETE,,,delete from CLIENT_SCOPE_ROLE_MAPPING where ROLE_ID=$1,<not logged>"
"3/5/2024, 9:51:07.064 PM","2024-03-05 21:51:07.062 UTC-65e78fda.4020LOG:  AUDIT: SESSION,33,1,WRITE,DELETE,,,delete from COMPOSITE_ROLE where CHILD_ROLE = $1,<not logged>"
"3/5/2024, 9:51:07.063 PM","2024-03-05 21:51:07.061 UTC-65e78fda.4020LOG:  AUDIT: SESSION,32,1,WRITE,DELETE,,,delete from FED_USER_ROLE_MAPPING where ROLE_ID=$1,<not logged>"
"3/5/2024, 9:51:07.061 PM","2024-03-05 21:38:18.528 UTC-65e78fda.4020LOG:  AUDIT: SESSION,31,1,WRITE,DELETE,,,delete from USER_ROLE_MAPPING where ROLE_ID=$1,<not logged>"
```

p.s.
The query used to get these logs:

```sql
AzureDiagnostics
| where Category == "PostgreSQLLogs"
| where TimeGenerated > datetime(2024-03-05T21:48:41.699Z)
| where Message has "AUDIT:" and Message !has "insert into public.lsnmover"
| project TimeGenerated, Message
| order by TimeGenerated desc

**Comment by sschu** [comment]
I think this does not really matter. If you have lots of role mappings in your table and a full table scan is done, this takes time, even in no assignment for that role is found. Can you count the number of entries in that table?

**Comment by EnneS** [comment]
In my case, here is some statistics for that query :
![image](https://github.com/keycloak/keycloak/assets/23013153/bc923421-bbf8-4fad-b7d1-f415edd2ba62)

**Comment by sschu** [comment]
There is an index on the user_id but not on the role_id. Deleting a role searches for role_id, not user_id.

**Comment by EnneS** [comment]
My bad, got the wrong query. Here:
![image](https://github.com/keycloak/keycloak/assets/23013153/8eafebce-44a0-4ece-a0ba-72f1010c72a8)
![image](https://github.com/keycloak/keycloak/assets/23013153/875bc191-9987-43ba-a0fd-4193064b5eca)

I had already added an index on role_id it seems.

**Comment by sschu** [comment]
But you still see the slow overall processing? Do you have an idea where the time is spent, if not deleting the user_role_mappings?

**Comment by EnneS** [comment]
Yes, the more keycloak instances are up the slower. I am really not sure, my intuition would be the infinispan cache invalidation/propagation but I really can't tell.

**Comment by SalemWafi** [comment]
The issue might be in the policy_config table, role association to the authorization policy is handled in code, as the values are stored as a json array inside a "TEXT" type column called "value" in that table. Currently, we have 15000 role policies in the policy_configs table, which are being checked one by one in the code, probably in the functions `findByType()` and `findById()`

**Comment by pedroigor** [comment]
@SalemWafi Yeah, see https://github.com/keycloak/keycloak/blob/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/role/RolePolicyProviderFactory.java#L224.

To avoid that, we could change how the role policy (e.g.: and possibly others that rely on a JSON config referencing other domain objects) handles roles from the configuration so that in case a role does not exist during evaluation, we force an update to the policy configuration to remove the nonexistent role.

Another solution could be filtering out nonexistent roles from the representation. The role policy provider already ignores nonexistent roles so it should not be a problem during evaluation. We could then expect the policy configuration being updated to remove nonexistent roles when you update the policy.

Both solutions should help to avoid iterating over all the policies when removing a role.
