### ISSUE TITLE
Ignore unrecognized truststore formats if `--truststore-paths` is a directory

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#26929]
### Description

When the system truststore is specified as a directory, we should ignore any files that are not recognized as a valid truststore. It is a valid use case (e.g. for K8s deployments) that a directory could include more than just truststores.

### Motivation

https://github.com/keycloak/keycloak/pull/26912#pullrequestreview-1872080857

**Comment by shawkins** [comment]
@vmuzikar to clarify the errors in loading the files are treated as info logs: https://github.com/keycloak/keycloak/blob/8c3df19722514a9d30ca816852735e4bd67f4b5b/services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java#L203

This simplistic handling is based upon that there's no definitive list of extensions for pem format files - you see .crt, .pem, no extension, etc.

Further refinement would include:
- tweak the info log so that things which do not look at all like pem files are just logged at a debug level (if loadedAny==false and possibly some other checks for pem like content)
- support glob patterns to specify exactly the files that are of interest

**Comment by vmuzikar** [comment]
> the errors in loading what could be non pem files are treated as info logs

Oh right, I first saw:
https://github.com/keycloak/keycloak/blob/8c3df19722514a9d30ca816852735e4bd67f4b5b/services/src/main/java/org/keycloak/truststore/TruststoreBuilder.java#L216-L217
But that's specific to failed reading of the file, not parsing it as a PEM truststore.

I think we should tweak it to debug level, but at the same time throw a hard exception if the file was specified directly and it's not just a result of scanning the directory.

**Comment by vmuzikar** [comment]
Right. So it's just a question whether we want to change it to debug or keep info.  Probably we can keep as is then. Sorry for the confusion. :) I [remembered](https://github.com/keycloak/keycloak/pull/26912#pullrequestreview-1872080857) correctly we already support this then.

**Comment by shawkins** [comment]
> I https://github.com/keycloak/keycloak/pull/26912#pullrequestreview-1872080857 correctly we already support this then.

Yes, it's supported, but will generate info logs that users may not be expecting. I'm fine with refining further to debug when we can definitely tell it's not a pem file. A grey area is a file doesn't have at least a single valid cert, but the contents "look like" one - it would be nice to see an info or even a warning in that case.

For #26912 another reason to have a list known to the operator is that we may want that for implementing #25671 - until quakus supports reloading the system truststore, and we have server side logic for rebuilding the truststore, the user or the operator will have to trigger roll outs.

And to confirm - you don't want to go down the path of supporting glob expressions correct?

**Comment by vmuzikar** [comment]
> I'm fine with refining further to debug when we can definitely tell it's not a pem file.

+1

> A grey area is a file doesn't have at least a single valid cert, but the contents "look like" one - it would be nice to see an info or even a warning in that case.

+1 for warning in this case

> For #26912 another reason to have a list known to the operator is that we may want that for implementing #25671 - until quakus supports reloading the system truststore, and we have server side logic for rebuilding the truststore, the user or the operator will have to trigger roll outs.

Right. It seems we might have support for reloadable certs/keys/truststores [relatively soon](https://github.com/quarkusio/quarkus/pull/38608) but that's concerning the HTTP server. With the system truststore it's a bit more complicated as it's used by different component (Keycloak Truststore SPI, DB drivers, mTLS, ...). I don't think we'll be ever able to fully support reloading there.

> And to confirm - you don't want to go down the path of supporting glob expressions correct?

IMHO that adds additional complexity that might not be really needed.

**Comment by vmuzikar** [comment]
> I'm fine with refining further to debug when we can definitely tell it's not a pem file.

Actually, we might do it the other way around. Print an info log what cert files we loaded when truststore is specified as a dir.

**Comment by shawkins** [comment]
> > I'm fine with refining further to debug when we can definitely tell it's not a pem file.
> 
> Actually, we might do it the other way around. Print an info log what cert files we loaded when truststore is specified as a dir.

Ok, opened a pr that reports the discovered files at info and puts the non-pem files as debug. The only other thing I can think of is to just go ahead an assume some extension convention, and say that if you have a file that does not end with one of those extentions (or no extension) then you have to specify the full path.
