### ISSUE TITLE
Once all default client scopes are deleted from the realm we can't create a new custom role.

### ISSUE THREAD

**Issue by r-dimitrov** [keycloak/keycloak#26937]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I've deleted all default roles from the 'Client Scopes' and i'm not able to create a new one.
The button **Create a client scope** is missing.
<img width="1438" alt="image" src="https://github.com/keycloak/keycloak/assets/19496422/79a1610f-6a71-4601-8420-c59c3f3c9114">

### Version

23.0.6

### Expected behavior

To have the ability to create a custom client scopes.

### Actual behavior

The button for creating client scopes is missing.

### How to Reproduce?

Delete all client scopes.

**Comment by ssilvert** [comment]
I have verified this bug.

**Comment by kaustubh-rh** [comment]
I'm able to reproduce the issue, will raise a PR for the same.

**Comment by edewit** [comment]
The problem is that you shouldn't be allowed to remove build in scopes as removing all scopes makes the realm no longer work
