### ISSUE TITLE
Password reset also expires password in FreeIPA

### ISSUE THREAD

**Issue by ProjectPatatoe** [keycloak/keycloak#26945]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Going through the password reset process in Keycloak leaves me unable to get into the account. After resetting, I will be unable to login in Keycloak. Using the updated credentials in FreeIPA works but prompts me to set my password again because it expired.

I have user federation done via ldap/kerberos

```
# ipa --version
VERSION: 4.10.2, API_VERSION: 2.252
```

### Version

23.0.6

### Expected behavior

Password reset resets password and does not set expiration status

### Actual behavior

Password reset set new password in FreeIPA but also sets expiration

### How to Reproduce?

1. use LDAP/Kerberos user federation with a FreeIPA instance.
2. use forgot password prompts for an account
3. set new password
4. check account status / attempt to login

**Comment by mposolda** [comment]
Thanks for the report, but I am adding to backlog as Keycloak team likely won't be able to fix this in the near future. Anyone is welcome to investigate this and possibly send PR with fixing this. See here for more details: https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md

Regarding this, I am not sure if there is even any way for how to update password in FreeIPA from Keycloak without automatically consider FreeIPA password being expired. Is not there any settings on the FreeIPA side, which allows to specify that newly updated password is not automatically considered expired? It can be also an option to have some mapper (similar to `MSADUserAccountControlStorageMapper`, which we have for MSAD), which will allow to remove "expired" flag from MSAD after updating password...

**Comment by ProjectPatatoe** [comment]
I'm new to both Keycloak and FreeIPA. Someone else will have to chime in. However, here is some references I found that might have a solution:
* https://www.freeipa.org/page/New_Passwords_Expired - mentions "The only exception is for password synchronization agents."
* https://listman.redhat.com/archives/freeipa-users/2012-June/msg00360.html - seems to get around it by never having an expiration altogether if i understand it correctly.
* https://access.redhat.com/solutions/6020481 - paywalled

This got me thinking, If the password is expired in a normal way... is there no way for Keycloak to know and prompt for a change password?

**Comment by ProjectPatatoe** [comment]
Another thing I forgot to mention. Keycloak thinks that the access is OK and doesn't realize it wasn't really a complete process. if you log out after resetting your password, you won't be able to login because the password is expired.

Also, turning on the `LDAPv3 Password Modify Extended Operation` doesn't seem to change anything

**Comment by cybertschunk** [comment]
This issue still exists and should not be closed as stall.

**Comment by echthesia** [comment]
> This issue still exists and should not be closed as stall.

This isn't an issue with Keycloak - FreeIPA enforces immediate expiration when passwords are administratively reset and provides [a way to exempt individual administrators (or service accounts) from this](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/managing_idm_users_groups_hosts_and_access_control_rules/managing-user-passwords-in-idm_managing-users-groups-hosts#enabling-password-reset-in-idm-without-prompting-the-user-for-a-password-change-at-the-next-login_managing-user-passwords-in-idm).
