### ISSUE TITLE
Roles admin REST API for creating roles: Composite roles are expanded

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak#26951]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When using the `roles` admin REST API for creating a composite role that contains other composite roles then the contained roles are expanded. This is different from the behaviour when adding composite roles in the Admin UI and the behaviour of `POST {role-name}/composites`. This is unexpected, makes managing roles harder and is probably not intended.

### Version

23.0.6

### Expected behavior

Composite roles added to a composite role are not expanded.

### Actual behavior

Composite roles added to a composite role are expanded.

### How to Reproduce?

Create some roles with composites: `role3 contains (role2 contains role1)`

```
POST /auth/admin/realms/master/roles
 
{
    "name": "role1"
}
 
POST /auth/admin/realms/master/roles
 
{
    "composite": true,
    "name": "role2",
    "composites": {
        "realm": ["role1"]
    }
}
 
POST /auth/admin/realms/master/roles
 
{
    "composite": true,
    "name": "role3",
    "composites": {
        "realm": ["role2"]
    }
}
```

`role1` was added because `role2` was expanded. (It is not expected to have `role1` added explicitly to `role3` as it is already a inherited role from `role2`.)

``` 
GET /auth/admin/realms/master/roles/role3/composites
 
[
    {
        "id": "981a8351-b895-47ad-8923-b94639a47148",
        "name": "role1",
        "composite": false,
        "clientRole": false,
        "containerId": "5f3e9387-7494-44ba-8699-758122ee07b3"
    },
    {
        "id": "fdd4f720-7016-49c8-aa8d-a9371e7472b6",
        "name": "role2",
        "composite": true,
        "clientRole": false,
        "containerId": "5f3e9387-7494-44ba-8699-758122ee07b3"
    }
]
```

**Comment by synth3** [comment]
I added a pull request but I am not yet sure how to get rid of the DCO error...

**Comment by synth3** [comment]
> I added a pull request but I am not yet sure how to get rid of the DCO error...

Ok, now I managed to make GitHub happy which fixed the DCO error in the merge request.

**Comment by thomasdarimont** [comment]
@pedroigor I currently don't see a reason why this endpoints should behave differently.

**Comment by pedroigor** [comment]
@synth3 Planning it to 25 as we are not introducing more potential breaking changes to 24.
