### ISSUE TITLE
Look into alternatives to paid Cypress products

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#26956]
### Description
We need to research alternatives and see if we can still run our Cypress tests with acceptable performance without the need for Cypress dashboard/cloud.

See:
Run Cypress tests in parallel using cypress-split: https://github.com/keycloak/keycloak/pull/20685
Run Cypress tests in parallel using cypress-parallel: https://github.com/keycloak/keycloak/pull/20683

### Discussion

Discussed in UI Team Meetings

**Comment by jonkoops** [comment]
Closing as #20685 was merged.
