### ISSUE TITLE
Editing realms with special characters in realm ID triggers validation error

### ISSUE THREAD

**Issue by Nithe14** [keycloak/keycloak#26966]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Editing realms with special characters in the realm ID is not possible, preventing admin user from updating existing realms with such IDs. While it is possible to create a new realm with special characters, attempting to edit it results in an error: "Realm name can't contain special characters."

### Version

23.0.6

### Expected behavior

Admin user should be able to edit realms with special characters in the realm ID without encountering errors.

### Actual behavior

Attempting to edit a realm with special characters in the realm ID triggers an error message stating, "Realm name can't contain special characters."

### How to Reproduce?

1. Create a realm with a special character in the realm ID.
2. Attempt to edit the created realm without changing the original realm ID.

### Anything else?

Users dealing with multiple realms containing special characters in their IDs face a notable problem. The difficulty arises when attempting to edit these realms after updating to the latest version, presenting a potential challenge. The process of migrating numerous realms with unique identifiers with special chars becomes challenging.
May be related #10181

**Comment by ssilvert** [comment]
I'm changing this to the core team for now.  Once there is resolution on the back end, please let the UI team know.  Then I suspect we can just relax our validation on the front end and just let the back end do all the work.

**Comment by mposolda** [comment]
duplicates #26108 

So I am closing this. Please use that other issue to further watch / comment anything related to this issue.
