### ISSUE TITLE
NginxProxySslClientCertificateLookupFactory unable to work with custom trust stores

### ISSUE THREAD

**Issue by stavsap** [keycloak/keycloak#26972]
👍

### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

[NginxProxySslClientCertificateLookupFactory](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookupFactory.java) is unable to work with trust store providers that are not overwriting the "file" ID trust store provider.

### Version

23.0.6

### Expected behavior

setting the default trust store provider that is not with ID "file" should work properly and provide trust store for the NginxProxySslClientCertificateLookupFactory.

### Actual behavior

NginxProxySslClientCertificateLookupFactory is able to work only with "file" trust store provider.
 

### How to Reproduce?

set mTLS for direct grant.
set Nginx as proxy.
enable NginxProxySslClient to consume x509 from nginx header.
provide custom trust store provider via SPI with ID different then "file"
set the custom trust store provider as default on to use.
try to perform login with mTLS direct grant through Nginx.

### Anything else?

the issue seems to be caused because of hard coded fetch of trust store provider with ID "file".

https://github.com/keycloak/keycloak/blob/750bc2c09c63a81aba02ebb6574b2b69fc6386de/services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookupFactory.java#L83

**Comment by mposolda** [comment]
Thanks for the report, but I am adding to backlog as Keycloak team likely won't be able to fix this in the near future. Anyone is welcome to investigate this and possibly send PR with fixing this. See here for more details: https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md

**Comment by stavsap** [comment]
@mposolda hi,

i opened PR for it, https://github.com/keycloak/keycloak/pull/27001

who is the "maintainer" that need to approve the checks?

**Comment by stavsap** [comment]
👍 ,i am affected by this. i did made a fix. i opened PR for it, https://github.com/keycloak/keycloak/pull/27001
