### ISSUE TITLE
"Unexpected Application Error!" when access to admin console by URL /admin/master/console/#/realms/MYREALM after upgrade to 23

### ISSUE THREAD

**Issue by bamandineDoca** [keycloak/keycloak#26991]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I am reporting an issue related to URL pattern "/admin/master/console/#/realms/MYREALM" after upgrading from version 21.1.1 to 23.0.6. As you can see in the attached screenshot, an error is displayed instead of the expected content, after logging in.

![image](https://github.com/keycloak/keycloak/assets/150713506/b1ad38fd-2323-40f3-9af2-871bb97d11c0)

This problem is particularly concerning because many of our project users have bookmarks using this URL pattern, and they are now encountering errors after the migration.

I was wondering if it would be possible to implement a gentle redirection to "/admin/master/console/#/MYREALM" instead of showing an error message, as this would greatly improve the user experience.

Thank you for your attention to this matter, and please let me know if you need any further information from me.

### Version

23.0.6

### Expected behavior

URL with pattern "/admin/master/console/#/realms/MYREALM" redirect to "/admin/master/console/#/MYREALM" instead of showing an error message

### Actual behavior

Getting an error message and no way to go on a valid URL :

![image](https://github.com/keycloak/keycloak/assets/150713506/b1ad38fd-2323-40f3-9af2-871bb97d11c0)

### How to Reproduce?

On Keycloak 23.0.6, go to "/admin/master/console/#/realms/MYREALM" and log in. The error occurs after logging in.

**Comment by edewit** [comment]
The error is not nice we could improve that, but I think that the realm is not there?

**Comment by bamandineDoca** [comment]
> The error is not nice we could improve that, but I think that the realm is not there?
The realm exists and is available through the URL "/admin/master/console/#/MYREALM".

It would be highly beneficial for the URL with the pattern "/admin/master/console/#/realms/MYREALM" to be redirected to "/admin/master/console/#/MYREALM" in order to prevent the occurrence of error messages. This redirection would greatly enhance the user experience.

**Comment by ssilvert** [comment]
@bamandineDoca I understand your concern, but I don't think this is a rabbit hole we want to go down to support every changed URL, past and future.

Have you thought about just setting up a proxy?

**Comment by bamandineDoca** [comment]
> @bamandineDoca I understand your concern, but I don't think this is a rabbit hole we want to go down to support every changed URL, past and future.
> 
> Have you thought about just setting up a proxy?

Thank you for your reply. I understand your point of view. 
We have found a solution by overloading the dashboard routes of the "admin-console" theme. 
It would still be helpful to have information on URL changes (maybe into the migration guide or release notes ?) to ensure smooth updates.
