### ISSUE TITLE
Having read-only attributes stored at a user leads to validation warning on every login 

### ISSUE THREAD

**Issue by sschu** [keycloak/keycloak#27031]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When a user has stored a read-only attribute and logs in and the `verify-profile` required action is enabled for a realm, the log contains a warning `2024-02-14 12:48:00,513 WARN  [org.keycloak.userprofile.validator.ReadOnlyAttributeUnchangedValidator] (executor-thread-8) Attempt to edit denied for attribute 'saml.persistent.name.id.for.foo' with pattern '(?i:^\QKERBEROS_PRINCIPAL\E$|^\QLDAP_ID\E$|^\QLDAP_ENTRY_DN\E$|^\QCREATED_TIMESTAMP\E$|^\QcreateTimestamp\E$|^\QmodifyTimestamp\E$|^\QuserCertificate\E$|^\Qsaml.persistent.name.id.for.\E.*$|^\QENABLED\E$|^\QEMAIL_VERIFIED\E$|^\QdisabledReason\E$)' of user 'admin'` for every auth request.

### Version

23.0.6

### Expected behavior

No warnings in the log.

### Actual behavior

Warning `2024-02-14 12:48:00,513 WARN  [org.keycloak.userprofile.validator.ReadOnlyAttributeUnchangedValidator] (executor-thread-8) Attempt to edit denied for attribute 'saml.persistent.name.id.for.foo' with pattern '(?i:^\QKERBEROS_PRINCIPAL\E$|^\QLDAP_ID\E$|^\QLDAP_ENTRY_DN\E$|^\QCREATED_TIMESTAMP\E$|^\QcreateTimestamp\E$|^\QmodifyTimestamp\E$|^\QuserCertificate\E$|^\Qsaml.persistent.name.id.for.\E.*$|^\QENABLED\E$|^\QEMAIL_VERIFIED\E$|^\QdisabledReason\E$)' of user 'admin'`appears on every auth request.

### How to Reproduce?

1. ` docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_FEATURES=declarative-user-profile quay.io/keycloak/keycloak:23.0.6 start-dev`
2. Navigate to `admin` user in admin console on master realm.
3. Add a read-only attribute e.g. `saml.persistent.name.id.for.foo` with value `foo`.
4. Enable `Verify profile` required action on master realm.
5. Reload the page

### Anything else?

While debugging I can see that the `ReadOnlyAttributeUnchangedValidator` runs with the list of new values being empty (see https://github.com/keycloak/keycloak/blob/883e83e62540168593046e34292849e16c009760/services/src/main/java/org/keycloak/userprofile/validator/ReadOnlyAttributeUnchangedValidator.java#L70). 

This makes some sense since normally, when doing an auth request there should not be updates to the user (unless there is an authenticator or a mapper doing this, but this is not the case here). The validator then concludes that there is an intended update because the existing value is `foo` and it should be deleted since the new value is `null`. 

I am not 100% sure this is a bug or if it is intended but I definitely find it strange this validator runs with an empty set of updated attributes in an auth request.

**Comment by sschu** [comment]
@pedroigor But does it make sense to run this validator when there is actually no update to the user? He ist just doing an authcode browser flow authenticated by cookie, no mappers are run, no user profile update by the user.

**Comment by pedroigor** [comment]
It does not but that is the only way we have now to decide whether an attribute is a read-only internal attribute. That is the only reason why that validator is being run. Other validators are not running at all.

I propose to change the log message for now and have a follow-up to improve how we are checking for read-only attributes.

What we need is this check https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/userprofile/validator/ReadOnlyAttributeUnchangedValidator.java#L65 rather than running the whole validator. However, this whole "read-only internal" attribute capability should be removed and replaced by capabilities from UP itself.

That is why I'm proposing fixing only the log level for now.

**Comment by sschu** [comment]
OK, thats fine for me. I can also provide a PR.
