### ISSUE TITLE
Verify the performance impact of the changes done to increase internal algorithm's security with HS512 and 128 byte hmac keys

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#27043]
### Description

Verify the performance impact of the changes done to increase internal algorithm's security using HS512 and 128 byte hmac keys with the change introduced here - https://github.com/keycloak/keycloak/pull/26957

**Comment by kami619** [comment]
Verified that there wasn't any performance hit because of the change in the internal algorithm and the details are below.

Made sure the Cookie is signed by the HS512 algorithm and the Keys admin configuration area has the mention of the HS512 algorithm as well.

Results from the performance benchmark on 02-15-2024 (before the algorithm change):

```
"cpuUsageForLoginsTest": {
    "userLoginsPerSecPer1vCpuPerPod": 27
    }
"cpuUsageForCredentialGrantsTest": {
    "credentialGrantsPerSecPer1vCpu": 351
    }
```

Results from the performance benchmark on 02-16-2024 (after the algorithm change):

```
"cpuUsageForLoginsTest": {
    "userLoginsPerSecPer1vCpuPerPod": 27
    }
"cpuUsageForCredentialGrantsTest": {
    "credentialGrantsPerSecPer1vCpu": 360
    }
```

**Comment by kami619** [comment]
@ahus1 if this data looks good to you as well, I shall close this task as completed.

**Comment by ahus1** [comment]
Thank you for reviewing the results. I agree this looks good, and that there is no visible impact to those key metrics.
