### ISSUE TITLE
Document transition issues from resteasy classic to reactive

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#27057]
### Description

On our path away from reasteasy classic, there are things that may need to be documented - at the very least to set expectations about what is, and isn't supported, moving forward.

Possible existing migration issues:
- #26642
- #25291
- #25038 - there's a potential fix from the keycloak side for this to work. When migrating to resteasy reactive specific logic, there's a different in KeycloakSession availablity.
- https://github.com/keycloak/keycloak/discussions/17423#discussioncomment-8493835 - there isn't necessarily a 1-1 mapping between how things were done with classic and reactive. We may want to point users to appropriate help channels when this situation arrises.

Additional migration work, which may also impact extensions:
- #25847
- #26315
- #27242

cc @vmuzikar @pedroigor

**Comment by pedroigor** [comment]
@shawkins Issue #26642 should be fixed by https://github.com/keycloak/keycloak/issues/24986.

**Comment by pedroigor** [comment]
Looking at the other two issues we don't have (until so far) documentation about how to use Resteasy APIs to create extensions or even JAX-RS API.

**Comment by vmuzikar** [comment]
Another one: https://github.com/keycloak/keycloak/discussions/17423#discussioncomment-8493835

**Comment by shawkins** [comment]
@vmuzikar I know we talked about creating a separate doc task for expanding migration note - if we do that, what will this issue represent, or would you just close it?

**Comment by vmuzikar** [comment]
We'd probably retrospectively update the 23 migration guide, which would be then part of RHBK 24 migration guide.

**Comment by vmuzikar** [comment]
@shawkins From my perspective, for docs we should backport the following:
* https://github.com/keycloak/keycloak/pull/27214/files#diff-a1d64743e80c7a36ee4b9f8b76a32b503377c1347aafcd2c54dfd6803107081a
* https://github.com/keycloak/keycloak/pull/27789/files#diff-a1d64743e80c7a36ee4b9f8b76a32b503377c1347aafcd2c54dfd6803107081a
* https://github.com/keycloak/keycloak/pull/27906/files#diff-a1d64743e80c7a36ee4b9f8b76a32b503377c1347aafcd2c54dfd6803107081a
* https://github.com/keycloak/keycloak/pull/27678/files#diff-5487f0a5a94653ecac6ce929e957d7b8674f3bd9d52f43e06ea7cd57f1e3249f

(We could possibly do it as a single PR.)

> Just the comment you mentioned and possibly something about class not found errors when using resteasy classic classes?

+1

As for the resteasy removal concerning the following PR:
* https://github.com/keycloak/keycloak/pull/27032
* https://github.com/keycloak/keycloak/pull/27387

After thinking about it more and considering possible regressions, I'd probably would not backport it.

WDYT?

**Comment by shawkins** [comment]
> (We could possibly do it as a single PR.)

Only https://github.com/keycloak/keycloak/pull/27678/files#diff-5487f0a5a94653ecac6ce929e957d7b8674f3bd9d52f43e06ea7cd57f1e3249f is not covered by an existing issue / backport. I can certianly separate it off.

> After thinking about it more and considering possible regressions, I'd probably would not backport it.

The resteasy-core removal is already part of 24. And we removed the backport label from the resteasy-core-spi issue. 

So other than the doc note about the JAX-RS stuff not being supported it looks like we're good.

**Comment by vmuzikar** [comment]
> The resteasy-core removal is already part of 24.

Oh, right. I was looking for a backport but we made it to merge to main before 24 release. That's good then.

**Comment by vmuzikar** [comment]
@shawkins Can you please create a backport for https://github.com/keycloak/keycloak/pull/28048?

**Comment by shawkins** [comment]
@vmuzikar https://github.com/keycloak/keycloak/pull/28149
