### ISSUE TITLE
Keycloak failed to start in Production mode.!

### ISSUE THREAD

**Issue by Krishna-PriyaV** [keycloak/keycloak#27073]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

Production

### Describe the bug

I am trying to upgrade Keycloak from version 20.0.0 to 23.0.4.
Whenever I try to start it in production mode (start), I get 503 page.. But I tried with dev mode (start-dev), it is working fine.
I am using Docker image and ec2 container for 23.0.4.:

**Logs:**

ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport,instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@36d864e7, status=FAILED} failed to start	

ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000659: Component ComponentWrapper{name=org.infinispan.remoting.transport.Transport,instance=org.infinispan.remoting.transport.jgroups.JGroupsTransport@36d864e7, status=FAILED} failed to start	

ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: bootstrap method initialization exception

ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Invalid receiver type class 
org.jgroups.protocols.relay.RELAY2; not a subtype of implementation type class org.jgroups.protocols.relay.RELAY	

Caused by: java.lang.BootstrapMethodError: bootstrap method initialization exception	
java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188)	
java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)	
java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)

**Docker File:**

FROM public.ecr.aws/docker/library/maven:3.8.4-openjdk-17-slim as maven-builder

COPY native-s3-pom.xml ./
RUN mvn package -f native-s3-pom.xml
FROM quay.io/keycloak/keycloak:23.0.4 as keycloak-builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_DB=mysql
ENV KC_FEATURES=preview,token-exchange,admin-fine-grained-authz
ENV KC_CACHE_STACK=ec2
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_PROXY=edge
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=true

COPY --from=maven-builder --chown=keycloak target/s3-native-ping-bundle-*-jar-with-dependencies.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:23.0.4
COPY --from=keycloak-builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=keycloak-builder /opt/keycloak/providers/* /opt/keycloak/providers/
COPY themes /opt/keycloak/themes
COPY keycloak.conf /opt/keycloak/conf/

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh show-config

ENV KC_DB=mysql
ENV KC_DB_URL=db
ENV KC_DB_USERNAME=dbuser
ENV KC_DB_PASSWORD=dbpass
ENV KC_HOSTNAME=myurl.com
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_HOSTNAME_PATH=/auth

ENTRYPOINT ["/opt/keycloak/bin/kc.sh" , "start" ]

### Version

23.0.4

### Regression

- [ ] The issue is a regressions

### Expected behavior

Keycloak will be start and user can login.

### Actual behavior

Getting 503 page when hitting the redirect url 

### How to Reproduce?

- Use the above Dockerfile to build an image and run the keycloak.

### Anything else?

When I use "start-dev" instead of "start", it's working.

**Comment by shawkins** [comment]
Based upon

```
ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Invalid receiver type class
org.jgroups.protocols.relay.RELAY2; not a subtype of implementation type class org.jgroups.protocols.relay.RELAY
```

and the naming of s3-native-ping-bundle-*-jar-with-dependencies.jar - you are likely including infinispan classes in your provider jar, which is causing the classloading exception above. Do you see a warning at startup about split packages? See also https://github.com/keycloak/keycloak/pull/27214/files - we're adding an explicit note about the classloading behavior around providers.
