### ISSUE TITLE
Can’t get Keycloak to deny access if user not in group/role policy though the evaluate option is showing deny option

### ISSUE THREAD

**Issue by vasudevbannaravuri** [keycloak/keycloak#27103]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Can’t get Keycloak to deny access if user not in group/role policy though the evaluate option is showing deny option

### Version

23.0.0

### Regression

- [ ] The issue is a regressions

### Expected behavior

ideally the user should not access when the evaluate option is set to deny

### Actual behavior

user is accessing the keycloak though the evaluate option is set to deny

### How to Reproduce?

created resource, and added resource based with permission set using group policy

**Comment by pedroigor** [comment]
@vasudevbannaravuri Could you elaborate more on what you mean by the `evaluate` option? Is it the `Evaluate` tab?

Please, also provide more details about the steps and the configuration you are using.

**Comment by vasudevbannaravuri** [comment]
Yes, it is related to the evaluate tab.

Below are the detailed steps and configuration I am using.
- I have a single client with around 15 valid redirect url's in that, and I have close to 30 users in my keycloak realm.
- Now, my requirement is to differentiate those 30 users by tagging those users under different groups and only allowing certain groups to access few url's but not all the list.
- There was already a default resource with default permission with the default policy set to allow all the users in the realm to access the resource.
- I have created a new policy with group type and changed the associated policy of default permission from default policy to the new policy which was created by me.
- So I have tried the evaluate tab option which was there under authorization, tried with the user who is not part of the group and result shows deny option under the evaluate tab but still the user able to access the url's which were present in the client.
- Ideally when deny result comes, the user should not access the resource but here that is not the case.

**Comment by pedroigor** [comment]
@vasudevbannaravuri Thanks. If I understand correctly, you want to restrict the URIs set to the client based on group membership. However, the permission is bound to the resource (default resource) and not the client itself. So the user will have access to the client regardless of the permission you set.

The permissions/policies do not enforce access to the client itself even though they are defined within the client context. Please, look at https://www.keycloak.org/docs/23.0.7/authorization_services/#_service_obtaining_permissions for more details about how to actually evaluate permissions.

I'm closing this as it does not seem like a bug. We also have quite a few tests checking group policies.

**Comment by vasudevbannaravuri** [comment]
Thanks for your response, but could you please tell me how I can achieve to set this and allow only users in group to access certain url's in the client but not all.
