### ISSUE TITLE
Loading spinner keep on running after clicking on cancel button on "Create user" page

### ISSUE THREAD

**Issue by ChetRam** [keycloak/keycloak#27116]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Loading spinner keep on running after clicking on cancel button on "Create user" page.
![User-page-on-loading-error-state](https://github.com/keycloak/keycloak/assets/6292813/540752a9-41f2-4635-8c5b-9f4e48585433)

 

### Version

22.0.5

### Regression

- [X] The issue is a regressions

### Expected behavior

Loading spinner should be hide after loading actual user-list. Users should be listed down. 

### Actual behavior

Loading spinner keep on running after clicking on cancel button on "Create user" page.

### How to Reproduce?

1. login in keycloak admin UI (User will navigate to dashboard page)
2. Click on "Users" link on left-side bar. (User will navigate to user list page)
3. Click on "Add user" button. (User will navigate to create user page)
4. Just click on "Cancel" button.  (User will navigate back to user list page)

Loading spinner will keep on running and actual user-list will not be shown.

**Comment by edewit** [comment]
I can't reproduce this, do you have `User federation` enabled as well? Could you share what there is in the "Browser console"? And have a look at the server logs

**Comment by ChetRam** [comment]
User federation is not enabled. Please find the console log and keycloak logs in attachment.

[keycloak-log.txt](https://github.com/keycloak/keycloak/files/14340205/keycloak-log.txt)
[localhost-1708409737071.log](https://github.com/keycloak/keycloak/files/14340217/localhost-1708409737071.log)

**Comment by edewit** [comment]
So it seems that it fails because the realm is not found?

**Comment by ChetRam** [comment]
I have captured screenshot of dashboard and after-click-on-cancel-button. Please have a look
![dashboard](https://github.com/keycloak/keycloak/assets/6292813/3c7716b7-fbe3-4c2a-a450-821c808ec2dc)
![user-list-after-click-on-cancel-button](https://github.com/keycloak/keycloak/assets/6292813/8f8f5cd0-5172-4115-afac-03ee284b06ca)

**Comment by jonkoops** [comment]
@ChetRam it looks like you reported this issue for an older version of Keycloak. We don't actively support any version of Keycloak other than the latest stable version, can you confirm the issue exists there as well?
