### ISSUE TITLE
When upgrading the database, keycloak seems to target a default database

### ISSUE THREAD

**Issue by bjdijk** [keycloak/keycloak#27130]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I'm upgrading from release 15.0.2 to 23.0.6. When I run the kc.bat with a postgres user for a new schema (keycloak_clone_2), the upgrade errors out on the below

2024-02-19 13:37:06.511 CET [18966] ERROR:  relation "idx_user_service_account" already exists
2024-02-19 13:37:06.511 CET [18966] STATEMENT:  CREATE INDEX IDX_USER_SERVICE_ACCOUNT ON public.USER_ENTITY(REALM_ID, SERVICE_ACCOUNT_CLIENT_LINK)

However, in the schema, that relation does not exist. I also have an already upgraded schema (keycloak) in the same database, it looks like the script is conflicting with that.

### Version

23.0.6

### Regression

- [ ] The issue is a regressions

### Expected behavior

Upgrade without database errors

### Actual behavior

Database errors are reported.

### How to Reproduce?

Maybe as follows:
create default keycloak schema
create cloned schema
upgrade cloned schema

**Comment by vramik** [comment]
Hello @bjdijk, thank you for the report. To properly triage the issue I need answers to few questions. How exactly do you clone the db schema? What is the command you use to start the server? 

Could you please provide detailed steps (commands included) how you hit the issue? Thanks a lot.

~missing-info

**Comment by bjdijk** [comment]
Upon rechecking I think I did not specify the database, causing it to fall
back to keycloak.

Op do 29 feb. 2024 09:54 schreef keycloak-github-bot[bot] <
***@***.***>:
