### ISSUE TITLE
Replace "Security Key" with "Passkey" in WebAuthn UIs and their documents

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#27147]
### Description

WebAuthn UIs (authentication, policy) and documentation about WebAuthn use the word "Security Key".
Recently, "Passkey" becomes used commonly instead of "Security Key".
Therefore, the issue is for replacing the word "Security Key" with "Passkey".

**Comment by jeetparte** [comment]
@tnorimat @mposolda  I believe the dialog for labelling a registered passkey needs to be renamed as well —

<img width="590" alt="Screenshot 2024-03-09 at 1 05 32 AM" src="https://github.com/keycloak/keycloak/assets/17269750/06ed8d0b-9942-4b97-a425-465c1445660b">

Perhaps "Please label your registered passkey" with the default label simply being "Passkey"?

**Another point to note:** I noticed that pressing the Cancel button on the dialog still creates the passkey with the default label (one might expect it cancels the passkey creation but that's already taken place). I believe the Cancel button is simply not needed here. Just one button suffices. Also, "Done" or "Save" is a better choice for the button's name than "OK".

**Comment by tnorimat** [comment]
@jeetparte Hello,
https://github.com/keycloak/keycloak/pull/27239 will resolve the point you mentioned about the dialog for labelling.
