### ISSUE TITLE
Newly created authentication subflow is always disabled

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#27173]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

- Login to admin console
- Go to tab `Authentication` and create some new authentication flow of pre-selected type `Basic` 
- Click `Add sub-flow`
- Add subflow of some random name and click `Save`
- Now the subflow is disabled by default and I cannot enable it -> KO

See screenshot below (Note that there is workaround as I filled below):
![Screenshot from 2024-02-20 18-07-02](https://github.com/keycloak/keycloak/assets/1223965/a21f025a-96a9-4748-ab7f-47753a882137)

### Version

nightly

### Regression

- [X] The issue is a regressions

### Expected behavior

When I create subflow, I can select any requirement from it

### Actual behavior

Newly created subflow is disabled and I cannot enable it

### How to Reproduce?

See above

### Anything else?

There is a workaround: When creating subflow, I first switch `Flow type` to `Form`, but then I immediatelly switch it back to `Generic` . After this, the new subflow look OK and I can change the states.

**Comment by edewit** [comment]
this is because the `requirementChoices` is `[]`
