### ISSUE TITLE
Editing built-in client policy profiles are silently reverted

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#27184]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When editing client policy profiles through the `JSON editor` the built-in profiles are included in the JSON document:

![image](https://github.com/keycloak/keycloak/assets/2271511/11ffa5d2-28f7-46df-919f-8530923c6883)

If any of the built-in profiles are edited the changes are silently dropped when saving. The same happens if you try to rename one of the built-in profiles.

In the `Form view` on the other hand the built-in profiles are marked as read-only and it's not possible to edit them.

### Version

23.0.6

### Regression

- [ ] The issue is a regressions

### Expected behavior

An error is thrown when trying to update the built-in profiles, or probably better the built-in profiles are not included in the `JSON editor` view and it will only show the custom profiles.

### Actual behavior

Built-in profiles are shown in the `JSON editor` and it's possible to edit them, but when saving the changes are silently reverted.

### How to Reproduce?

1. Realm settings
2. Client policies
3. Profiles
4. JSON editor
5. Change for example the description for `fapi-1-baseline` and click `Save`
6. Observe there is no error, and the changes you made are silently reverted

**Comment by mposolda** [comment]
Yes, this can be good.

Regarding first point, we should update also server-side to throw appropriate error.

Regarding second point, we already have the flag available on REST endpoint (See `ClientPoliciesProfilesResource.getProfiles`), so we may need to just update UI and add the toggle and call the REST endpoint accordingly.

I can add that showing globals in the JSON is currently useful for the case when administrator want to copy some global client profile and use it as a "template". Copying in the JSON editor is the only way to do it, but it is not very user-friendly as administrator needs to change the name and change `global` to false when he copy some profile. If we can have something more friendly in the UI (for instance something like the button `Copy profile` like we have for authentication flows), it can be also nice.

**Comment by mposolda** [comment]
Adding to 25 for now. We may need to postpone according to priorities. I've added this to the epic of default client policies #27188 , so we can possibly look at those related things together.

**Comment by edewit** [comment]
maybe we could add this plugin to show and disable editing of these blocks https://constrained-editor-plugin.vercel.app/playground

**Comment by edewit** [comment]
> maybe we could add this plugin to show and disable editing of these blocks https://constrained-editor-plugin.vercel.app/playground

Actually we can't use this as we are not using the monaco editor directly we could ask Patternfly to consider adding this to their component

**Comment by ssilvert** [comment]
Removing `team/ui` label as this requires server-side changes.  If there are any UI changes required, please let me know.
