### ISSUE TITLE
Workflow failure Admin UI E2E - matrix E2E

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#27194]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Whole matrix has failed and E2E testsuite was not executed due to this issue:
```
Run cypress-io/github-action@v6
Skipping install because install parameter is false
waiting on "http://localhost:8080" with timeout of 60 seconds
It looks like this is your first time using Cypress: 13.6.0

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...

DevTools listening on ws://127.0.0.1:36413/devtools/browser/cd5875bf-62b7-4d13-9fdf-3d67c8ae3768
[2437:02[20](https://github.com/keycloak/keycloak/actions/runs/7972202907/job/21763825076#step:11:21)/105511.494183:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: unknown error type: 
Your Record Key b8f1d...fc0eb is not valid with this projectId: j4yhox

It may have been recently revoked by you or another user.

Please log into Cypress Cloud to see the valid Record Keys.

https://on.cypress.io/dashboard/projects/j4yhox
Error: The operation was canceled.
``` 
https://github.com/keycloak/keycloak/actions/runs/7972202907/job/21763825340

### Version

release/22.0 & 23.0

### Regression

- [ ] The issue is a regressions

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by miquelsi** [comment]
@ikhomyn @jonkoops I guess this can be closed now, right?

**Comment by jonkoops** [comment]
Yes, this has been resolved.
