### ISSUE TITLE
Issue with kafka integration for authentication and authorization using Strimzi library 

### ISSUE THREAD

**Issue by gouravsrkr** [keycloak/keycloak#27202]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

We have recently upgraded our keycloak servers from 19.0.3 to 21.1.2. But since then we are seeing an issue with our kafka integrations. We have kafka brokers in 3 nodes, they are unable to make any communications internally. That is failing kafka communications with keycloak 21.1.2. Kafka is using [Strimzi library](https://repo.maven.apache.org/maven2/io/strimzi/kafka-oauth-common/0.10.0/) for communications with keycloak.  There were no changes made on the Kafka side, and this issue started occurring towards the end of the upgrade work. 

### Version

21.1.2

### Regression

- [X] The issue is a regression

### Expected behavior

kafka brokers should be able to communicate with keycloak

### Actual behavior

Initial Connection is not established, Whereas this is working for version 19.0.3

### How to Reproduce?

We successfully upgraded Keycloak from v19.0.3 to V21.1.2, and all functionalities are working fine post-upgrade.
However, we are facing an issue with Kafka integration for authentication and authorization using the Strimzi library.
It seems that communication is not working.
The SDE Keycloak upgrade was completed earlier, and since then, Secure Kafka (using the Infra-Kafka realm) is unable to function. Internally, all three Kafka brokers are unable to connect or communicate with each other.
There were no changes made on the Kafka side, and this issue started occurring towards the end of the upgrade work

**Comment by pedroigor** [comment]
@gouravsrkr Thanks for the report. It seems more related to how you are integrating Keycloak with Kafka than something at our end.

We don't have (yet) tools and tests to make sure the library you are using can work well with the latest releases.

Please, provide more details about the problems you are facing like logs that indicate errors when starting and using a Keycloak server. Otherwise, there is not much we can do.
