### ISSUE TITLE
[DOCS] [Server Guide] [THEMES] Instructions unclear

### ISSUE THREAD

**Issue by tspearconquest** [keycloak/keycloak#27216]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

The instructions for creating a theme in the server guide are a bit unclear. In the section titled Deploying Themes, the instructions state:

> To deploy the archive to Keycloak, add it to the providers/ directory of Keycloak and restart the server if it is already running.

However this doesn't seem to work if you've already run `kc.sh build`. 

The below simple dockerfile should be valid to reproduce this but let me know if not:
```
FROM keycloak/keycloak:23.0.0
RUN /opt/keycloak/bin/kc.sh build
COPY mytheme.jar /opt/keycloak/providers/mytheme.jar

ENTRYPOINT [ "/opt/keycloak/bin/kc.sh", "start", "--optimized", "--spi-theme-welcome-theme=mytheme" ]
```

When running the image, the welcome page for the master realm is still the default keycloak themed page, and I don't see "mytheme" in the theme selector in the realm settings in the admin console.

I'm testing now to see if putting the file in place before the build, and providing the welcome theme flag on the build command line gets it working but the docs should be more clear about this.

### Version

20.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The docs should just simply indicate that you need to run `kc.sh build` again after updating the theme if your command line to start the server normally starts it in optimized production mode.

### Actual behavior

The docs simply say to restart the server

### How to Reproduce?

The reproducer is above

**Comment by tspearconquest** [comment]
Thanks, I will try, however I question if the welcome theme changes would impact whether the theme appears in the theme selector dropdown (noted in the OP that it does not)

**Comment by ssilvert** [comment]
There is no theme selector for the welcome theme.  It is set from the command line.

**Comment by tspearconquest** [comment]
Apologies, let me clarify.

The question was 2 parts.
1. If I do this in my Dockerfile, why doesn't ANY of my theme work/appear in the theme selector?
    ```
    FROM keycloak/keycloak:23.0.0
    RUN /opt/keycloak/bin/kc.sh build
    COPY mytheme.jar /opt/keycloak/providers/mytheme.jar

    ENTRYPOINT [ "/opt/keycloak/bin/kc.sh", "start", "--optimized", "--spi-theme-welcome-theme=mytheme" ]
    ```
2. Regarding to the welcome theme in specific, why did I still get the default theme instead of the welcome theme despite specifying the welcome theme flag in the entrypoint?

After some testing, I was able to solve both of these.

1. Don't do `RUN /opt/keycloak/bin/kc.sh build` until **after** you copy anything you need into `/opt/keycloak/providers`
2. After solving 1 above and getting the theme working everywhere but the welcome screen, I started looking at the browser developer tools to identify the error, and noticed an undeclared variable was in the index.ftl for our theme. After changing the undeclared variable to one that was declared properly in the base keycloak theme, then rebuilding the image, I was able to get the welcome screen to work as well.

This issue remains open to request clarification in the documentation that copying in the theme jar file must be done before running `/opt/keycloak/bin/kc.sh build`
