### ISSUE TITLE
Lowercased "terms_and_conditions" is not migrated in fed_user_required_action table

### ISSUE THREAD

**Issue by nfode** [keycloak/keycloak#27228]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After rolling out Keycloak 21.1.2 we realized that the previously lowercased "terms_and_conditions" is now uppercased in the table `user_required_action`. In the table `fed_user_required_action` it is still lowercased. 

When creating users via the Admin REST API we need to pass it in uppercase for the feature to work and it stored like that in the `fed_user_required_action` table.

I checked the migration guide regarding it here: https://www.keycloak.org/docs/latest/upgrading/index.html#terms-and-conditions-user-attribute-migration

Now, I am confused. Should "terms_and_conditions" now be stored in upper or lowercase? 

### Version

21.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

"terms_and_conditions" is either upper or lowercased and can be used consistently.

### Actual behavior

It can be used in uppercase and is stored like that in the `user_required_action` and `fed_user_required_action` table. But the `fed_user_required_action` table was not migrated to uppercase.

### How to Reproduce?

Create users with the Terms and Conditions required action with a federated storage in a Keycloak version below 21.0.0. Upgrade to 21.1.2 and check the `fed_user_required_action` table.

**Comment by thomasdarimont** [comment]
This is similar to this issue https://github.com/keycloak/keycloak/issues/17277

**Comment by sguilhen** [comment]
I was able to reproduce the issue - after migrating a system that has the "terms and conditions" action set for federated users, the value remains in lower case. When logging in with one of these users, the action is skipped altogether, and a message is seen in the logs:

` WARN  [org.keycloak.services.managers.AuthenticationManager] (executor-thread-11) Could not find configuration for Required Action terms_and_conditions, did you forget to register it?`

We need to add a migration for the federated required actions to avoid this situation.
