### ISSUE TITLE
Cannot disable freemarker email template anymore in v23 (from v21) in production

### ISSUE THREAD

**Issue by JimVanEeden** [keycloak/keycloak#27233]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I've implemented a custom email provider, which used to work absolutely fine in v21. Already then, I found out that this only works when you disable the default `freemarker` provider. If this is not done, I get the following error when trying to send any email:

```
Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.email.EmailTemplateProvider.setRealm(org.keycloak.models.RealmModel)" because the return value of "org.keycloak.models.KeycloakSession.getProvider(java.lang.Class)" is null
```

Disabling freemarker email template is done in the build and run steps as follows:

```
kc.sh build --spi-email-template-freemarker-enabled=false
kc.sh start --optimized --spi-email-template-freemarker-enabled=false
```

Resulting in it being disabled:

<img width="603" alt="image" src="https://github.com/keycloak/keycloak/assets/5991446/ca78caef-5690-4b6a-9c44-fce5f91cda26">

As said, this used to work in v21. Now in v23 it still works in dev mode, but not in prod mode:

<img width="709" alt="image" src="https://github.com/keycloak/keycloak/assets/5991446/bd231109-27a5-4aa6-9131-d5c7d6304087">

Is there some change in the way this is done, or is there a bug? Or alternatively, can I set up my email template provider in such a way that I don't have to disable the freemarker template?

### Version

23.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

Freemarker email template provider is removed

### Actual behavior

Freemarker email template provider is not removed

### How to Reproduce?

Add `--spi-email-template-freemarker-enabled=false` to `build` and `start` commands in Keycloak v23

**Comment by JimVanEeden** [comment]
Ok I actually found a solution for my problem, but I think the bug is still relevant. I've now added `spi-email-template-freemarker-enabled=false` to `conf/keycloak.conf` before the build step. So it just seems that the `--spi-email-template-freemarker-enabled=false` flag is not working anymore.

**Comment by shawkins** [comment]
> Ok I actually found a solution for my problem, but I think the bug is still relevant.

I can't reproduce this as a regression. On 21.1.2 or 23 if the image is built with a given enablement, that carries over to start --optimized. This means that the spi enabled properties are effectively build time properties - they will be ignored when used on start --optimized.

Unlike other cli options we do not make this distinction clear. cc @mabartos @vmuzikar 

>  Or alternatively, can I set up my email template provider in such a way that I don't have to disable the freemarker template?

ProviderFactory does have an order method which may be applicable here.

**Comment by vmuzikar** [comment]
@shawkins Might be a docs bug. We truly load providers at [build time](https://github.com/keycloak/keycloak/blob/6d7a99dc6f166f32c2405941769bb321d265aef9/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L694).

**Comment by shawkins** [comment]
> @shawkins Might be a docs bug. We truly load providers at [build time]

https://www.keycloak.org/server/configuration-provider is pretty clear -enabled is a build time property. 

What I mean is that for the non-spi options on the cli we will error out when they are used unexpectedly, or warn if found in another config source. 

An enhancement could be considered here to have similar handling for spi options.

**Comment by vmuzikar** [comment]
@shawkins Right, missed it's already documented.

You mean add name validations to CLI options? If you mistype you get an error etc? We might use the config metadata some of the more significant options have (we don't probably care about those that don't have it).

**Comment by shawkins** [comment]
> You mean add name validations to CLI options? 

I mean for at least cli optoins related to spi we can add build / runtime validations. The setting of spi-...-enabled could easily be recognized as build-time only.

Full validation of course would be nice, but seems like a lot more work.

**Comment by vmuzikar** [comment]
AFAIK, all spi options should be runtime – except for -enabled and choosing the default provider. Our SPIs don't integrate with the build process.

**Comment by shawkins** [comment]
> AFAIK, all spi options should be runtime – except for -enabled and choosing the default provider.

Agreed. In this case the user here was trying to do "kc.sh start --optimized --spi-email-template-freemarker-enabled=false" - if that were a regular build time option, an error would have resulted indicating that it wasn't allowed.

**Comment by vmuzikar** [comment]
Ok, so it'd make sense to add some validations to spi -enabled and -provider options to treat them as build time.

**Comment by shawkins** [comment]
I'll mark this issue as closed then and open an enhancement on validating spi options wrt build / runtime.

**Comment by vmuzikar** [comment]
@shawkins Makes sense, thanks.
