### ISSUE TITLE
Remove usage of resteasy-core-spi

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#27242]
### Description

As a follow-up to #26315 we should remove the usage of resteasy-core-spi as continued usage is likely to not be valid, and complete removal will help make migration issues manifest as class not found rather than subtle situations where something appears not to work.

**Comment by shawkins** [comment]
I think this roughly looks like: https://github.com/shawkins/keycloak/compare/iss26315...shawkins:keycloak:iss27242?expand=1 - the DefaultXXX classes become abstract and we add Resteasy implementation. For now that was done in the test source of services.

**Comment by vmuzikar** [comment]
There's a risk of regression so I would not backport it. @shawkins Does it make sense to you?

**Comment by shawkins** [comment]
> There's a risk of regression so I would not backport it. @shawkins Does it make sense to you?

We can do that as well. I had thought in our weekly we had discussed that since the resteasy-core removal had already gone into 24, that this should go also. I'm fine if it doesn't.
