### ISSUE TITLE
Server Info not directly available via the "Realm Info" button from realm, different than "master" realm

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#27262]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The Server Info is not available, when "Realm Info" is clicked on realms, different than the master realm

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

As in the Old UI, when the "Server Info" link is clicked, even from realm, different than the "master" realm, to show the "Server Info"
![image](https://github.com/keycloak/keycloak/assets/33352511/3546da8a-3bcc-4ee8-89c2-67955d08e5f3)

### Actual behavior

Page similar to the below is shown, without the Server Info:
![image](https://github.com/keycloak/keycloak/assets/33352511/921fbd0c-a975-4ab7-a823-69bcf599ea45)

In case the same is done from the "master" realm, the Server Info is there:
![image](https://github.com/keycloak/keycloak/assets/33352511/e59b83d5-4b45-4f6f-b314-ccc489ffe18e)

### How to Reproduce?

- Open realm, different than the "master" realm
- Click on the User Name on the Top Right
- Click "Realm Info"

### Anything else?

This might be correct behaviour, but it is working much differently, than how it worked in the previouse Admin UI, where it was redirecting always to the Master realm, showing the Server Info (but there the menu was also called Server Info, not Realm Info).

**Comment by jbman** [comment]
Similar issue: https://github.com/keycloak/keycloak/issues/17970

**Comment by ssilvert** [comment]
@mpalavrov I think this probably is correct behavior.  Can you think of a use case where an administrator without access to master would need to see the Server info?

That being said, if the Server info is not reachable then we shouldn't show the menu item for it.
