### ISSUE TITLE
Invalidating offline token is not working from client sessions tab  

### ISSUE THREAD

**Issue by ravthiru** [keycloak/keycloak#27275]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have configured an user and public client with direct access grant. 
Then used offline token scope to retrieve access_token and refresh_token through "*/protocol/openid-connect/token" endpoint.
Now i want to invalidate/revoke offline_token using Keycloak ui , 
I tried to logout the offline session from Client details --> Sessions tab. 
![Screenshot 2024-02-26 at 11 11 20 am](https://github.com/keycloak/keycloak/assets/15014026/3a093f1e-8681-4886-bf2c-11b344721a7b)

But Offline token is not invalidated, iam able to get new access_token using the offline token received earlier.

### Version

keycloak-23.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Offline token should be invalidated and should not allow to retrieve access token using the offline token

### Actual behavior

 Able to get new access_token using the offline token  which was logged out through UI

### How to Reproduce?

1. Configured an user and public client with direct access grant. 
2. Get access_token and refresh_token through "*/protocol/openid-connect/token" endpoint , using offline token scope 
3.  Logout the offline session from Keycloak UI by going to Client details --> Sessions tab. 
4.  Now  get new access token using the offline token "*/protocol/openid-connect/token" endpoint
     Able to retrieve access token using the offline token

**Comment by pedroigor** [comment]
When deleting sessions from a client the endpoint does not take into account offline sessions but only online sessions. That is the main reason why it is not working as expected.

**Comment by martin-kanis** [comment]
@pedroigor @ravthiru With the current `main`, I don't even see 3 dots for an offline session where the `sign out` should be hidden. Which seems to me that this is an expected behavior and this issue should be handled as enhancement. 
![Screenshot from 2024-03-08 11-26-04](https://github.com/keycloak/keycloak/assets/3359545/7164c92d-ba40-44b3-a0aa-1964ec7f737a)
