### ISSUE TITLE
User id issue

### ISSUE THREAD

**Issue by PrabhaRavi14** [keycloak/keycloak#27282]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

If I am creating a new user in keycloak, After creating an id it does not give back the id from the keycloak.

### Version

20.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

If I am creating a new user in keycloak, After creating an id It will give back the id from the keycloak to DB

### Actual behavior

If I am creating a new user in keycloak, After creating an id it does not give back the id from the keycloak.

### How to Reproduce?

Nil

**Comment by jonkoops** [comment]
Closing this issue as it was reported for an older version of Keycloak. As outlined in the issue template, we only accept issues validated against the latest stable version of Keycloak.
