### ISSUE TITLE
FolderTheme does not support Locales with extensions

### ISSUE THREAD

**Issue by aschei** [keycloak/keycloak#27284]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

FolderTheme does not support Locales with extensions, such as  de-x-informal.

This is a regression, and was introduced with 748c53df7f9fb438277ce2542912004fd663ef97. The regexp `LEGAL_LOCALE` does not contain a hash, but Locale.toString produces hashes for extensions.

### Version

23.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak should support all Locales for bundles.

### Actual behavior

Login page shows an error when called with locales with extensions.

### How to Reproduce?

1. Add de-x-informal to realm
2. Access the login page for this realm and switch language to de-x-informal
3. Login page shows as error and the backend logs an exception:

Exception:
```
    "loggerName": "org.keycloak.services.error.KeycloakErrorHandler",
    "exception": {
      "refId": 1,
      "message": "Found illegal characters in locale or bundle name: messages_de__#x-informal",
      "exceptionType": "java.lang.RuntimeException",
      "frames": [
        {
          "line": 123,
          "method": "getMessages",
          "class": "org.keycloak.theme.FolderTheme"
        },
        {
          "class": "org.keycloak.theme.DefaultThemeManager$ExtendingTheme",
          "method": "getMessagesByLocale",
          "line": 263
        },
```

### Anything else?

I will follow up with a PR, adding the hash to `LEGAL_LOCALE` and a test case.

**Comment by aschei** [comment]
PR: https://github.com/keycloak/keycloak/pull/27285

**Comment by aschei** [comment]
The endpoint `/auth/admin/realms/{realm}``alllows to set `supportedLocales` with a set of strings that will be processed using `Locale.forLanguageTag()` which is documented as "Returns a locale for the specified IETF BCP 47 language tag string".

This worked for us up to the mentioned commit to distinguish between informal and non-informal languages as well as other extensions we use in our application.

**Comment by jonkoops** [comment]
I wonder how the key ends up being `messages_de__#x-informal`, where is the hash sign coming from exactly? Why is it re-formatted in this manner?

**Comment by aschei** [comment]
[FolderTheme.java#L120](https://github.com/keycloak/keycloak/blob/03f6cda85a4f3c12c71788362b4b1b8b81a20f61/services/src/main/java/org/keycloak/theme/FolderTheme.java#L120)  uses Locale.toString implicitly, and Locale.toString uses '#' to separate the extension.

A different approach to fix this would be to not rely on Locale.toString but on the ISO language tag instead, but I was not sure what this would cause/break.

**Comment by jonkoops** [comment]
It seems that the expectation in the code is that we conform to BCP47 (at least in format), so I think we can call `toLanguageTag()` instead of `toString()` to get the result we'd want.

I also believe we can replace the `LEGAL_LOCALE` regex with  `Locale.Builder().setLanguageTag()` to validate the locale, as this will throw an `IllformedLocaleException` if something invalid is passed to it.

WDYT?

**Comment by aschei** [comment]
Let me sort this:
a) BCP47 conformance is currently used to restrict locales during definition (which is fine)
b) If the locale is successfully defined, the mechanism that looks up message property files in FolderTheme uses Locale.toString which is a bit cumbersome, but it's there for ages in KC.

If we change b) to use BCP47 (`toLanguageTag`), existing Keycloak deployments need a sort of migration when they use additional messages-resources.

For this, a migration can be sort of a documentation plus - optional - a fallback to continue support for the established naming scheme.

The need for a migration sounds for me like something for a new KC version.

If we go this route, I would be stuck on this issue (and I'm pretty sure it's not just me).

I suggest to accept the PR as a bugfix for the current stable release, and maybe add another issue (feature) for the next release to switch to language tags for the file names.

WDYT?

Thanks for your effort!

**Comment by jonkoops** [comment]
> If we change b) to use BCP47 (toLanguageTag), existing Keycloak deployments need a sort of migration when they use additional messages-resources.

This would only apply for those that had configured a locale with a script/extension, which is currently already broken in v23 if I understand your issue report and changes under #27285 correctly. I think it's clear from the changes made under #21755 that this was never considered a supported use-case, any support that was there was accidental.

Since this is a rather fringe functionality that is only used by a sub-set of users, and this was already broken in v23, I'd rather not restore the original behaviour. This of course doesn't mean the use-case is not valid, it just needs a better implementation with accompanying documentation.

I understand that a possible implementation of this would be more involved, but I'd much rather see this resolved properly, which would mean:

- Using BCP47 everywhere as a means of indicating the language (so `toLanguageTag()` over `toString()`).
- Replacing the custom regular expression with the Builder API and catching exceptions there.
- Providing updated documentation, that explicitly references BCP47 with examples of 'extended' languages.

**Comment by aschei** [comment]
https://www.keycloak.org/docs/23.0.7/server_development/#adding-a-language-to-a-realm currently does not clearly state what locales are supported. All I can say is, it used to work with the full range of locales, and it went away with #21755 for those locales with an extension. The reason being a reg-exp that does not comply with what Locale.toString returns. Tbh, I don't understand what is so bad about fixing the regexp.

(For the time being I am forced to use a fork then, because I need a fix from v23 (LinkedIn Social IdP) *and* I need full locale support. But that's off topic)

**Comment by simonhype** [comment]
> > If we change b) to use BCP47 (toLanguageTag), existing Keycloak deployments need a sort of migration when they use additional messages-resources.
> 
> This would only apply for those that had configured a locale with a script/extension, which is currently already broken in v23 if I understand your issue report and changes under #27285 correctly. I think it's clear from the changes made under #21755 that this was never considered a supported use-case, any support that was there was accidental.

Not really. Switching from Locale.toString() to BCP47 would break any message resources file that uses a country code as well, since one uses an underscore as a separator and the other uses a dash:

`Locale.forLanguageTag("en-US").toString()` results in `"en_US"`

**Comment by jonkoops** [comment]
> `Locale.forLanguageTag("en-US").toString()` results in `"en_US"`

Ahh, yes. I hadn't considered this. It seems that we'll have to re-evaluate this approach then. Since this is being upvoted a lot I think the impact is higher than we originally expected, so I will revive @aschei's PR so we can restore the behaviour as it was before.

**Comment by aschei** [comment]
@jonkoops Thanks for moving this forward, really appreciated!
As a follow up: @stianst  removed the backport/23.0 label, so my guess is we will have to wait for 24.0 to get a stable release with the fix.
Are there any resources that reveal the timeline for new releases?
Is there a chance to get this backported anyway to 23.x?

**Comment by jonkoops** [comment]
> Is there a chance to get this backported anyway to 23.x?

I'll leave that to @stianst, as he's our project lead. But it looks like this will have to carry over to version 24. We expect a release of 24 in a span of a couple of weeks tops.

**Comment by bjoernhype** [comment]
Yeah, 24.0 has been published, and contains this here. But don't use 24.0, but 24.1

https://www.keycloak.org/2024/03/keycloak-2400-released
https://www.keycloak.org/2024/03/keycloak-2401-released
