### ISSUE TITLE
Validate spi options wrt build / run time

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#27298]
### Description

Unlike regular options, spi options do not provide guidance when they are applicable. See #27233

### Motivation

To ensure users are aware of build vs run time applicability of spi options.

### Details

This will likely only affect cli options. Creating a similar warning for other config sources, as is done for regular options, would require much more work.

**Comment by shawkins** [comment]
This will wait for #31448

There are two options:
- weak validation. Just look over the command line for options in the form of --spi... -enabled, -provider, -provider-default and validate based upon whether we're allowing runtime or buildtime options
- strong validation. Load the Spi classes and use those names to look over the Config for all spi options and validate just like the other Picocli.validateConfig logic. It looks like we load the Spi classes in two places already. This would add a third. Not sure if this is desirable. 

@mabartos @vmuzikar any thoughts?

**Comment by mabartos** [comment]
@shawkins IMHO, the most reasonable approach would be only the weak validation you're proposing. Could you please briefly investigate how much effort would be required to check the other config sources to print these warnings? It'd also be a nice improvement, but probably not a big deal.
