### ISSUE TITLE
CSP issues

### ISSUE THREAD

**Issue by srinivasmummareddy** [keycloak/keycloak#27303]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Refused to frame 'http://scaas-dev.kognif.ai/' because it violates the following Content Security Policy directive: "frame-src 'self'".

Welcome page is loading as expected but facing issues while clicking on admin console page--> api is giving 200 but issue is with csp which is resulting in blockage from browser side for rendering

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin console page(/admin/master/console/) should be rendered as api is returning 200

### Actual behavior

CSP issues 

### How to Reproduce?

I'm trying to run keycloak on aks using bitnami  helmchart behind nginx ingress(aks ingress is behind azure app gateway)

Helm chart config:

auth:
  adminUser: admin
  adminPassword: test@1
postgresql:
  enabled: false
externalDatabase:
  host: "sqlserver.database.windows.net"
  port: 1433
  user: kdi-sql-admin
  database: keycloak
  existingSecret: my-mssql-secret
resources:
  limits:
    memory: 900Mi
  requests:
    cpu: 50m
    memory: 600Mi
ingress:
  enabled: true
  ingressClassName: "nginx"
  pathType: Prefix
  hostname: test.ops.env.ai
  path: /keycloak
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
extraEnvVars:
  - name: KC_DB # override values from the conf file
    value: 'mssql'
  - name: KC_DB_URL
    value: 'jdbc:sqlserver://n08493-sqlserver.database.windows.net:1433;databaseName=keycloak;'
  - name: KC_TRANSACTION_XA_ENABLED
    value: 'false'
  - name: KC_HOSTNAME
    value: test-dev-ops.env.ai
  - name: KC_HOSTNAME_ADMIN
    value: test-dev-ops.env.ai
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
    
httpRelativePath: "/keycloak/"

logging:
  output: json
  level: INFO
# production: True

test-dev-ops.env.ai--> Host which is pointing from app gateway
test.ops.env.ai--> Internal ingress host

**Comment by ssilvert** [comment]
We have made some significant changes to the Welcome page.  Please try latest release.
