### ISSUE TITLE
v22.0.4 kcadm.sh add-roles -r <realm> ...  fails w/ Unknown command: -r or --target-realm

### ISSUE THREAD

**Issue by alaricljs** [keycloak/keycloak#27322]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

kcadm.sh add-roles fails as it doesn't understand the target realm options.

```bash
realm=test
rvgid=$(kcadm.sh get groups -r $realm | jq --raw-output '.[] | select(.name=="Realm Local") | .subGroups[] | select(.name=="Realm View") | .id')
kcadm.sh add-roles -r $realm --gid $rvgid --clientid realm-management --rolename view-users --rolename view-clients --rolename view-events --rolename view-authorization
Unknown command: -r

kcadm.sh add-roles --target-realm $realm --gid $rvgid --clientid realm-management --rolename view-users --rolename view-clients --rolename view-events --rolename view-authorization
Unknown command: --target-realm
```

### Version

22.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The command accepts the target realm option and adds the roles to the group.

### Actual behavior

The command doesn't understand the target realm option(s)  -r  or --target-realm

### How to Reproduce?

Run the above command on 22.0.4

**Comment by shawkins** [comment]
Probably related to #16260 - in this case it looks like cclientid rather than clientid should be used, but the exception message produced is not helpful.

**Comment by alaricljs** [comment]
You are right about the `--cclientId`, thanks ... one tiny letter and a rabbit hole of searching for answers.

**Comment by shawkins** [comment]
Marking this as resolved, and we'll give greater priority to getting #16260 fixed.
