### ISSUE TITLE
Created Date field for user in keycloak console shows invalid date

### ISSUE THREAD

**Issue by valerii15298** [keycloak/keycloak#27321]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Created Date field for user in keycloak console shows invalid date

### Version

22.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

There should be created date for the user

### Actual behavior

<img width="1077" alt="Screenshot 2024-02-27 at 19 52 41" src="https://github.com/keycloak/keycloak/assets/44531564/89eb9b7d-8b13-426f-9282-bfe74a682a81">
Field in UI shows invalid date text.
Also api returns null for createdDate for that user

### How to Reproduce?

Have no idea...

**Comment by jonkoops** [comment]
~old-release
