### ISSUE TITLE
Workflow failure: Admin UI E2E - realm_settings_user_profile_enabled

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#27337]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Some realm_settings_user_profile_enabled test failed during the run
https://github.com/keycloak/keycloak/actions/runs/8073144290/job/22056636796#step:11:156

`User profile tabs
       Check attributes are displayed and editable on user create/edit
         Checks that not required attribute is not present when user is created/edited with email as username enabled:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `.pf-c-alert__title`, but never found it. Queried from:`

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by tkyjovsk** [comment]
@jonkoops Looks like the test is still flaky. Should we reopen?

**Comment by jonkoops** [comment]
Looks to be failing on another part of the test now, feel free to open a new issue.

**Comment by tkyjovsk** [comment]
@jonkoops The test case reported in this issue doesn't seem to be fixed though. Should I create a new issue anyway?

`Checks that not required attribute is not present when user is created/edited with email as username enabled`
- originally reported

`Checks that attribute group is visible when user with a new attribute is created`
- new

`Checks that attribute with select-annotation is displayed and editable when user is created/edited`
- originally reported, fixed, now failing in different spot

**Comment by jonkoops** [comment]
Yes, please log a new issue :+1:

**Comment by hmlnarik** [comment]
Original fix was fixing a potential race condition and was insufficient, see e.g. jobs below. Reopening.
- https://github.com/keycloak/keycloak/actions/runs/8328702336/job/22790669785
- https://github.com/keycloak/keycloak/actions/runs/8328664494/job/22790498415
- https://github.com/keycloak/keycloak/actions/runs/8328662288/job/22790429386
