### ISSUE TITLE
Google Authenticator now supports SHA256 and SHA512

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#27349]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Google Authenticator provider is not included in the list of supported authenticators if algorithm is not SHA1 and if number of digits is not 6

https://github.com/keycloak/keycloak/blob/e2ed9791efb3039692e18133151d473a69c0ef32/services/src/main/java/org/keycloak/authentication/otp/GoogleAuthenticatorProvider.java#L25-L31

This information seems outdated since the app now works with other hash algorithms too and can generate 8 digit numbers.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Google Authenticator should be listed in supported authenticator apps even if 
* OTP policy sets hash algorithm to SHA256 or SHA512.
* OTP policy sets number of digits to 8.

### Actual behavior

Google Authenticator is not included in list of supported OTP authenticators if OTP policy sets hash algorithm SHA256 or  SHA512  or if digits is set to 8.

### How to Reproduce?

Configure SHA256 or SHA512 or number of digits 8 and see that Google Authenticator disappears from the list of supported authenticators. The list is displayed when user is setting up an authenticator app in the account console or when administrator configures OTP policy.

To validate that Google Authenticator still works even if it is not in the list:

1. Download latest Google Authenticator (Android app, updated in Play Store on 2023-05-18). 
2. Change Keycloak's OTP policy to SHA256 and SHA512, and number of digits to 8.
3. Setup authenticator app for user in account console, double check that hash algorithm was changed (click "Unable to scan?" to see parameters)
5. Check that OTP code can be validated successfully even when SHA256 or SHA512 is set as hash algorithm.
6. Check that OTP code can be validated successfully even when number of digits is set to 8.

**Comment by rmartinc** [comment]
@tsaarni I have added some comments in the PR, IIRC the google authenticator also supports `hotp` now with all the algorithms. Give it a try and update the PR if it works. Thanks!

I'm assigning this to you as you have sent a PR. Just comment me if you don't want to work on it to unassign it from you.
