### ISSUE TITLE
index-46ucf2q6.js:formatted:48 Uncaught SyntaxError: Unexpected token '(' error loading admin console

### ISSUE THREAD

**Issue by andynugent** [keycloak/keycloak#27358]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I browse to the main page for Keycloak and everything works as normal:
![image](https://github.com/keycloak/keycloak/assets/6598396/e9d3aa34-b33a-4170-86bb-16b8961614f3)

Click "Administration Console" and get the "Loading the Admin UI" spinner forever
![image](https://github.com/keycloak/keycloak/assets/6598396/7d12fe9f-bb2d-4919-9035-a95a8db0e4bb)

### Version

23.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The admin console to load

### Actual behavior

the "Loading the Admin UI" spinner forever and the error appears in the Chrome console window

### How to Reproduce?

Occurs 

### Anything else?

It happens all the time. Keycloak is configured to use mssql, but there's no ERROR or WARN output. It just seems to be a problem with the frontend JavaScript missing a ")"

**Comment by andynugent** [comment]
Updating to 23.0.7 resolves the issue

**Comment by jonkoops** [comment]
Closing this issue, as it is fixed in the latest stable.
