### ISSUE TITLE
Deprecate GELF

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#27364]
### Description

Keycloak uses the [logstash-gelf](https://github.com/mp911de/logstash-gelf) dependency which has reached EOL. As we don't see much community adoption of this feature (based on the bug reports), we should deprecate the GELF log handler.

**Comment by nxadm** [comment]
See https://github.com/keycloak/keycloak/issues/27365#issuecomment-1977327000

**Comment by DrHackschnitzel** [comment]
Well, gelf is very useful for high level remote logging, especially when keycloak does not support syslog.
What will be the alternative? remote logging ( with custom fields and json format) is mandatory when using keycloak in container orchestration systems like openshift or kubernetes.

**Comment by col-panic** [comment]
I want to log keycloak to OpenSearch - my first approach involved GELF, but now as I see, that 
it is removed - what approach do you recommend?

**Comment by DGuhr** [comment]
Note to self: add more bugs to implementation qhen doing this. Right? 🤪

* just kidding, do as you please, not my beer anymore. Just saying "Number of open bugs" is not even remotely a good metric for adoption. But as you know: What do I know 🤗 Just stumbled upon the kc26 release notes and was irritated.
