### ISSUE TITLE
Remove GELF

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#27365]
### Description

This is a follow-up on https://github.com/keycloak/keycloak/issues/27364

This included:
* Dependencies
* Options
* Tests
* Docs
* Maven profile

**Comment by nxadm** [comment]
> Keycloak uses the [logstash-gelf](https://github.com/mp911de/logstash-gelf) dependency which has reached EOL. As we don't see much community adoption of this feature (based on the bug reports), we should deprecate the GELF log handler.
#27364

Maybe you don't see much bug reports regarding GELF because it works really well? Since there is no syslog support on Keycloak, GELF is *incredible* useful for high-level logging. It was very easy to setup and it hasn't failed once.

Can this decision be reconsidered?

**Comment by vmuzikar** [comment]
@nxadm I understand the concerns and that GELF is useful for some use cases. However, as stated in the issue, the main reason is that the library we've been relying on was deprecated and there doesn't seem to be a maintained replacement that would be suitable for a security product like Keycloak. However, it should be possible to integrate with GELF in a different way using e.g. log parsing.

**Comment by nxadm** [comment]
There are certainly workarounds, but they are clunky if the volume is high enough. Wouldn't exposing quarkys syslog functionality be the the ideal solution, i.e. without extra dependencies?

https://quarkus.io/guides/logging#quarkus-logging-json_quarkus-log-syslog-json-syslog-logging

**Comment by vmuzikar** [comment]
@nxadm Feel free to open an RFE for the syslog. :)

**Comment by nxadm** [comment]
Now that the Red Hat issue tracker closed, would that be an issue here or a Github discussion entry?

**Comment by vmuzikar** [comment]
I'd suggest opening an issue here.

**Comment by hlavki** [comment]
> @nxadm I understand the concerns and that GELF is useful for some use cases. However, as stated in the issue, the main reason is that the library we've been relying on was deprecated and there doesn't seem to be a maintained replacement that would be suitable for a security product like Keycloak. However, it should be possible to integrate with GELF in a different way using e.g. log parsing.

It wasn't deprecated, it was marked as feature-full and that is a completely different story. Quarkus gelf extension uses the same library and it does not look like they will deprecate this extension.

**Comment by vmuzikar** [comment]
@hlavki The way we understand is that the repository was archived and is no longer maintained, while being feature complete. If there was a CVE for example, it's unsure if it would be fixed. And that's a big problem for a security project like Keycloak – possibly less for other projects. We talked with Quarkus folks and it's basically a community extension, they can't fully support it (in product/RHBQ at least) for the same reasons.

**Comment by hlavki** [comment]
Thanks @vmuzikar for the explanation. I assume there will be an option to add this extension to the classpath and configure it using quarkus env variables?

**Comment by vmuzikar** [comment]
@hlavki Unfortunately, that’s not possible. However, in Keycloak 25 we're adding [syslog](https://github.com/keycloak/keycloak/issues/27544) as an alternative.

**Comment by vmuzikar** [comment]
Moving to 26 as syslog will be included in 25. This will allow a ~3 months migration period.

**Comment by mabartos** [comment]
You can leverage this [keycloak-quarkus-extensions](https://github.com/mabartos/keycloak-quarkus-extensions) tool to enhance your Keycloak deployment and add your Quarkus/Quarkiverse extension.

It is possible to support GELF in Keycloak by enhancing your Keycloak distribution.

Please check the [Logging GELF](https://github.com/mabartos/keycloak-quarkus-extensions/blob/main/examples/logging-gelf.md) guide.
