### ISSUE TITLE
Social login - test failures with unexpected status code

### ISSUE THREAD

**Issue by tondrusk** [keycloak/keycloak#27366]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

7 social login test cases

- bitbucketLogin
- facebookLogin
- facebookLoginWithEnhancedScope
- githubLogin
- googleLogin
- openshift4Login
- openshiftLogin

are failing with `expected:<501> but was:<400>`

Related pipeline run: https://master-jenkins.redhat.com/view/RH-SSO/job/universal-test-pipeline-server/3497/testReport/org.keycloak.testsuite.broker/SocialLoginTest/

### Version

latest

### Regression

- [X] The issue is a regression

### Expected behavior

Passing tests

### Actual behavior

 Receiving status codes of `400` instead of `501`

### How to Reproduce?

Set up the relevant social IdPs following the [Server Administration Guide | Social Identity Providers](https://www.keycloak.org/docs/latest/server_admin/index.html#social-identity-providers) and execute the affected tests.

### Anything else?

The failures might be related to the recent changes for the feature below

- #26250

**Comment by tondrusk** [comment]
Looks like the changes related to the #26250 issue changed the behaviour a bit and the social login tests require similar changes as in [Fix disabled feature tests].(https://github.com/keycloak/keycloak/commit/6a576145541815fee9e4298b6bebc9a8db9b6a9f)

**Comment by ahus1** [comment]
Reverted from KC22, will be excluded from 22.0.11
