### ISSUE TITLE
Running kc.bat in folder with parenthesis throws error

### ISSUE THREAD

**Issue by hborchardt** [keycloak/keycloak#27375]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When installing keycloak in a path with parenthesis, like "C:\Program Files (x86)\keycloak", `kc.bat start` gives an error.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

kc.bat runs no matter where keycloak is installed

### Actual behavior

```
"\keycloak\bin\" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
```
which loosely translates to `Syntax error at "\keycloak\bin\"`. 

### How to Reproduce?
Install keycloak into a folder named `Program Files (x86)/keycloak/` and try to run kc.bat

### Anything else?

With some trial and error, the offending line is this
https://github.com/keycloak/keycloak/blob/326d63ce7462cbcd94f2efde2eb9070c1a724220/quarkus/dist/src/main/content/bin/kc.bat#L16-L20
where the parentheses from the `if` clause interfere with parentheses in the unquoted script path in `%~dp0%`.
I tried quoting the `set DIRNAME="%~dp0%"` but this leads to problems due to doublequoting later. So I would solve it like this, which works for me:
```bat
if "%OS%" == "Windows_NT" set DIRNAME=%~dp0%
if "%OS%" neq "Windows_NT" set DIRNAME=.\
```

**Comment by Pepo48** [comment]
Hi @hborchardt, thanks for the report. Coincidentally, just couple hours ago a PR https://github.com/keycloak/keycloak/pull/27363 that should fixed it was merged. 
In the description you mentioned the Keycloak version 23.0.7, which was released a week ago. If so, then such version doesn't contain the fresh fix. You either need to build the distribution on your own or wait for the Keycloak nightly build. Alternatively, you can also apply the fix manually to an older version.

Just to be completely sure I tried it with the latest upstream distribution build, which I then moved and ran from the same location you mentioned. Everything worked as expected, see:
![image](https://github.com/keycloak/keycloak/assets/12138171/e05b9f0f-111c-4840-bf86-96a0982080fa)

In any case, let me know if my assumption is correct and if it works for you the same way.
Thanks again.

**Comment by hborchardt** [comment]
Hi @Pepo48, that is truly a coincidence! I fear when I started the investigation and git blame'd the file, the fix was not merged yet, and I did not find the old ticket.

I can confirm that with the latest kc.bat it works for my use case. And I would have never guessed that quoting like you did in the fix works.

Thanks for the fix and sorry for the duplicate ticket.
