### ISSUE TITLE
[invalid_grant] Session doesn't have required client

### ISSUE THREAD

**Issue by ditogam** [keycloak/keycloak#27384]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Hello team,
I'm facing problem with key refresh token.

We deployed docker image keycloak:22.0.5 , SSO Session Idle & SSO Session Max are configured 30 days, Access Token Lifespan for 10 minutes.

We do not use Infinitspan, docker command is :

start-dev --http-enabled=true --hostname-strict=false --proxy reencrypt --http-relative-path=/auth

when Spring Gateway invokes grant_type "refresh_token" with refresh token, keycloak returns http 500 with message [invalid_grant] Session doesn't have required client

in docker we see only events like this

> 
> 2024-02-28 17:12:55,773 WARN  [org.keycloak.events] (executor-thread-192) type=REFRESH_TOKEN_ERROR, realmId=transguard, clientId=tg-bls, userId=ea131e0f-2570-4e92-a52f-a13427d629f7, ipAddress=10.116.225.8, error=invalid_token, grant_type=refresh_token, refresh_token_type=Offline, refresh_token_id=5e68c56e-0b1d-44e8-846e-bf24c2584eed, client_auth_method=client-secret
This happenes nearly every 30 min, if we refresh browser, everything works normally

As I know this docker was updated from keycloak version 13, but postgresql DB stayes the same

I have exactly the same image installed on other server and with the same config (also image was upgraded from v13), but there is no such issue.

Thanks for advices in advance.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Refresh token for active session

### Actual behavior

Failes to refresh token with error  
`[invalid_grant] Session doesn't have required client`

### How to Reproduce?

Couldnot reproduce on other

**Comment by ditogam** [comment]
Hi, I upgraded docker to 23.0.7 version, same problem

**Comment by ditogam** [comment]
![image](https://github.com/keycloak/keycloak/assets/13191168/91dab7e4-d1de-4abb-9053-4a5e55aa4112)
![image](https://github.com/keycloak/keycloak/assets/13191168/f18b99a7-fee8-4e5a-8f9f-94e64de86407)
In Spring Gateway app we recieve ` [invalid_grant] Session doesn't have required client`
keycloak          logs
`| 2024-03-11 13:09:14,865 WARN  [org.keycloak.events] (executor-thread-589) type="REFRESH_TOKEN_ERROR", realmId="transguard", clientId="tg-bls", userId="01dd0461-6e72-4705-872e-2b802df1eb60", ipAddress="10.115.224.11", error="invalid_token", grant_type="refresh_token", refresh_token_type="Offline", refresh_token_id="940c87ef-e9e4-42d3-b8d0-bdb904b0eab8", client_auth_method="client-secret"
`

In about 5 minutes app (web client) recieves 500 Internal Server Error, then 302 Found with redirection and then CORS error	.
![image](https://github.com/keycloak/keycloak/assets/13191168/fda024c8-e25a-4fcd-80a2-d1be9d7e3e17)


I tried changing all params in Session and Token tabs, but cannot guess the logic which param changes the behave.

After refresh browser (we use cookies), it starts working again

**Comment by sschu** [comment]
The CORS errors indicate there is something wrong with you configuration. You say that you don't have this problem on a different server. Can you try to find out what exactly is configured differently between these two servers. It's really hard to help without a way to reproduce the problem.
