### ISSUE TITLE
KC 23.0.4 - environment variables do not get resolved when configured inside JAVA_OPTS in statefulset.yaml

### ISSUE THREAD

**Issue by satsrini** [keycloak/keycloak#27392]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

**Issue**: KC 23.0.4 - environment variables do not get resolved when configured inside JAVA_OPTS in statefulset.yaml
Openshift 4.12 Kubernetes Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9"

**Issue in Detail:**
In our product, we deploy keycloak server using bitnami helm chart - [Keycloak 23.0.4](https://github.com/bitnami/charts/tree/6b632870dcf2138fbf87a9eab5b73d80a3d3b0ed/bitnami/keycloak)

In the statefulset.yaml, we add an env variable JAVA_OPTS as following

```
 - name: JAVA_OPTS
    value: "-Djavax.net.ssl.trustStore=$KEYCLOAK_HTTPS_TRUST_STORE_FILE -Djavax.net.ssl.trustStorePassword=$KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD"
```

After deploying the Keycloak server, inside the keycloak pod, we see that the above env variables, viz., $KEYCLOAK_HTTPS_TRUST_STORE_FILE and  $KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD do not get resolved 

and hence java process gets deployed as below.

```
root@09ad7bac88d1:/# kubectl exec -it keycloak-2 -n nautilus-system -- bash
Defaulted container "keycloak" out of: keycloak, init-certs (init)
keycloak@keycloak-2:/$ ps -ef | grep kc
keycloak       1       0 22 13:14 ?        00:00:29 /opt/bitnami/java/bin/java -Dkc.config.built=true -Djavax.net.ssl.trustStore=$KEYCLOAK_HTTPS_TRUST_STORE_FILE -Djavax.net.ssl.trustStorePassword=$KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED -Djgroups.dns.query=keycloak-headless -Dkc.home.dir=/opt/bitnami/keycloak/bin/.. -Djboss.server.config.dir=/opt/bitnami/keycloak/bin/../conf -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp /opt/bitnami/keycloak/bin/../lib/quarkus-run.jar io.quarkus.bootstrap.runner.QuarkusEntryPoint -cf /opt/bitnami/keycloak/conf/keycloak.conf start
keycloak     402     394  0 13:16 pts/0    00:00:00 grep kc
keycloak@keycloak-2:/$
```
 As we can see above, $KEYCLOAK_HTTPS_TRUST_STORE_FILE and $KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD are not resolved to their actual values.

**Confirmations:**
confirmed that individually, the env variables $KEYCLOAK_HTTPS_TRUST_STORE_FILE and $KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD resolve to their actual values when tried with 'echo' command in the same pod.

**Note:** we did not face this face when we earlier used [Keycloak v21.1.2](https://github.com/bitnami/charts/tree/df638697464307b86eaea802a0721b5678ec6553/bitnami/keycloak)

Only when we upgrade to [Keycloak v23.0.4](https://github.com/bitnami/charts/tree/6b632870dcf2138fbf87a9eab5b73d80a3d3b0ed/bitnami/keycloak) , we have this issue.

### Version

23.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

JAVA_OPTS  should resolve fully/correctly along with the env variables($KEYCLOAK_HTTPS_TRUST_STORE_FILE and $KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD) that reside in it.

### Actual behavior

JAVA_OPTS  does not resolve fully/correctly along with the env variables($KEYCLOAK_HTTPS_TRUST_STORE_FILE and $KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD) that reside in it.

It does not resolve and hence it remains as below at runtime JVM inside keycloak pod.

` -Djavax.net.ssl.trustStore=$KEYCLOAK_HTTPS_TRUST_STORE_FILE -Djavax.net.ssl.trustStorePassword=$KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD`

### How to Reproduce?

**Steps to reproduce:**

a. helm chart [Keycloak 23.0.4](https://github.com/bitnami/charts/tree/6b632870dcf2138fbf87a9eab5b73d80a3d3b0ed/bitnami/keycloak)
b. Openshift 4.12 Kubernetes Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9"
c. set JAVA_OPTS as an env variable in statefulset.yaml with it's as 
`"-Djavax.net.ssl.trustStore=$KEYCLOAK_HTTPS_TRUST_STORE_FILE -Djavax.net.ssl.trustStorePassword=$KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD"`

where $KEYCLOAK_HTTPS_TRUST_STORE_FILE and $KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD are valid env variables.

**Comment by jonkoops** [comment]
@shawkins should we close this then? Since this is expected behaviour.

**Comment by satsrini** [comment]
@shawkins ,

Thank you.
env variables got resolved after using them as $(KEYCLOAK_HTTPS_TRUST_STORE_FILE) and $(KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD)  in kubernetes resources as per https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

I am closing this.
