### ISSUE TITLE
UX: Account console subpages allow anonymous access

### ISSUE THREAD

**Issue by claytonvaughan** [keycloak/keycloak#27401]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When viewing the account console without being logged in, there's a sign-in button at the top right along with a bunch of links to "Personal info", "Signing in", "Device activity," etc. You can click on any of these links and be taken to a page as though you were actually logged in, under an account named "Anonymous." A short time after loading the page, you will be redirected to a login page but you can press your browser's Back button to return to the Anonymous user's page and will not be redirected again until you click on another link.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Unless I'm mistaken, there is nothing valid that anyone can do on the account console without being logged in other than to click on the "sign in" button. If the only valid action that can be taken is to sign in, then the page should simply render a login prompt directly rather than this strange anonymous-user-details page. This seems to be the goal, but the use of a delayed redirect means that the user will see the anonymous user's details page before being redirected, and can press the back button to return to it.

### Actual behavior

The page is rendered as though you are allowed to make modifications for an Anonymous account (which as far as I can tell does not really exist)
![image](https://github.com/keycloak/keycloak/assets/161776592/568db51c-cdd2-4069-881f-d9f24bd63799)
Note also that the "Sign in" button has now become a "Sign **out**" button
Similar unpopulated pages will be shown for other links from the main console as well as along the menu bar.

### How to Reproduce?

1. Visit the account console at https://{url base}/auth/realms/{realm}/account/
2. Click "Personal info"
3. Wait for the page to redirect to the login screen
4. Press the browser's back button

**Comment by claytonvaughan** [comment]
I re-tested against 23.0.7 and the same issue is present.

**Comment by edewit** [comment]
I can't reproduce this

**Comment by hmlnarik** [comment]
It is reproducible in 24 as well (Firefox). Steps to reproduce:
1. Login to **admin** console
2. Go to some page e.g. Applications
3. Log out
4. Click the back button

**Comment by edewit** [comment]
@hmlnarik I still can't reproduce it with these steps
