### ISSUE TITLE
Document how to specify CPU and memory limits/requests for the Operator

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#27432]
### Description

The Operator subscriptions allows specifying memory and CPU for an Operator. Doing so (especially requesting memory), would prevent a node to come into memory pressure, or an Operator Pod to be evicted from a node.

### Motivation

Allow stable operations of a Keycloak Operator. Be a good Kubernetes citizen. 

The page https://www.keycloak.org/operator/installation currently doesn't provide information how to specify resource information for the Operator, and also doesn't provide values which are proven to be good values. 

It would be nice if some defaults could be provided for the Keycloak Operator.

### Details

See https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/subscription-operators-coreos-com-v1alpha1.html#spec-config-resources on details on how to specify resource for Operators.

Kudos to @vmuzikar for providing this information.

**Comment by Pepo48** [comment]
@ahus1 is your suggestion related to [Resource requirements](https://github.com/keycloak/keycloak/blob/main/docs/guides/operator/advanced-configuration.adoc#resource-requirements) section in the operator's Advanced configuration guide? If so, should it be moved to the Installation guide to make it more visible (and avoid the duplicity)? Or did I overlook something?

**Comment by ahus1** [comment]
@Pepo48 - documenting it in one place is definitely preferred. Back at the time I thought documenting it is the preferred way. Alternatively the Operator could come with a default configuration for the resource settings that we don't expect people to change, so there would be no need to document it in the first place. 

* I'd put it into the Operator installation guide if we expect most people or almost everyone to configure it. 
* It could be part of the advanced configuration guide when think only few people would do it. 
* Again, having some good defaults would be best.

**Comment by vmuzikar** [comment]
@Pepo48 @ahus1 +1 for having some defaults, AFAIK it's actually considered a best practice (OLM PR pipeline actually [logs warnings](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4651#issuecomment-2158254057) about it).

Docs should not be really needed. I assume not many users would need to change the defaults, and if they do, it's already documented in the OpenShift docs.

**Comment by ahus1** [comment]
Good to hear it is possible. It makes sense to take a step back from my proposed solution of adding docs and do something better.

**Comment by Pepo48** [comment]
Thanks guys for the input. I tried to come up with the [PR](https://github.com/keycloak/keycloak/pull/30601), but the actual numbers are rather very wild placeholders. I ran the deployment with the currently proposed defaults though and everything seemed to work. Regardless, do we have data, based on which we could determine the numbers more precisely?

**Comment by vmuzikar** [comment]
> Regardless, do we have data, based on which we could determine the numbers more precisely?

That's a good question what are the reasonable defaults.

@shawkins WDYT?

**Comment by shawkins** [comment]
> @shawkins WDYT?

Given that we are typically managing a low number of keycloaks and everything we're watching is labeled, they should be pretty low. I would deploy just a single keycloak to get a baseline, then deploy another keycloak to validate the typical incremental difference (it may not be perceptible - almost no cpu and maybe several 100 KB). Then set our defaults manage up to something like 10 keycloaks +30% margin.

**Comment by FabriceEll** [comment]
i would be really interested in this, currently i am using limit ranges to "inject" resource definitions into my kc operator pod running on openshift, when i do so (even when using huge sizing for such a simple management pod) the startup times of the keycloak instance pods are slow and users have reported substantial slowness with the managed keycloak instances as well even though the instance pods all have their own constant resources that are not affected by this change. 
Are there any synchronous dependencies between the instance pod serving keycloak and the management operator pod that explain application slowness in a case like this?
