### ISSUE TITLE
keycloaksession access with PreMatching request filters

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#27446]
keycloaksession creation happens here: https://github.com/keycloak/keycloak/blob/77c4cee4d0ea84b17f9ef46fa70638fa16a46c87/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/CreateSessionHandler.java#L42

Which is controlled by https://github.com/keycloak/keycloak/blob/77c4cee4d0ea84b17f9ef46fa70638fa16a46c87/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/KeycloakHandlerChainCustomizer.java#L62

When a request filter is annotated with PreMatching, what we see is that it the filter will get invoked before the CreateSessionHandler runs.

The user indicates that in prior releases of Keycloak, using just the resteasy classic stack, that a PreMatching filter still had access to the session. 

In the prior releases the keycloaksession creation was handled by QuarkusRequestFilter https://github.com/keycloak/keycloak/commit/217a09ce46bac48b7492a881e2ca5fbeef9dfd6d#diff-80ef3a628be94a94774a6f6e71af1c5d29cfb9dedf6c1e88c39ceb5664662239L134 which was installed via https://github.com/keycloak/keycloak/commit/217a09ce46bac48b7492a881e2ca5fbeef9dfd6d#diff-6ebe7f8db3e4dea9dbefd50eed883b8aac997e6c01127e283631e92e9d022835L614 - which at first glance does appear like it would have priority to run before anything else.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/pull/27368#discussion_r1508939704_

**Comment by shawkins** [comment]
This will at least be documented via #27057

**Comment by vmuzikar** [comment]
Added a comment [here](https://github.com/keycloak/keycloak/pull/27368#discussion_r1510935966). From my perspective I don't see a reason why the KeycloakSession should not be available at PreMatching phase.

**Comment by shawkins** [comment]
From what I can see on the KeycloakHandlerChainCustomizer there are phases missing in the handlers method - those include BEFORE_PRE_MATCH. So we are probably being too specific in the with just before / after method.

cc @geoand @pedroigor

**Comment by shawkins** [comment]
Given that we are not supporting general jax-rs components, this is being closed.
