### ISSUE TITLE
Regression in "Groups" label / title localization

### ISSUE THREAD

**Issue by khord** [keycloak/keycloak#27472]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

Previously on version `22.0.3`, the translation for the label "Groups" in Japanese correctly appeared. After upgrading to `23.0.6`, I experienced the description for Groups getting translated in the place where its label should be.

### Version

23.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

The translation for Groups label appears
<img width="1209" alt="Screenshot 2024-03-04 at 4 28 36 PM" src="https://github.com/keycloak/keycloak/assets/21085666/e9fb7cf8-2030-49b1-b41c-c97b4062bdd9">

### Actual behavior

The translation for the Groups description appears
<img width="1213" alt="Screenshot 2024-03-04 at 4 31 02 PM" src="https://github.com/keycloak/keycloak/assets/21085666/ff2f4abf-c469-45e1-94ed-4b23f299a7ed">

### How to Reproduce?

In [Realm settings > Localization], enable Internationalization and add 日本語 as a supported locale. Log out and back in with the language switched.

### Anything else?

I realize this is not the latest 23.0.7 per the rules, but I don't have the ability to test that in this environment at the moment, and I don't see any bugs listed on that version addressing this.

**Comment by jonkoops** [comment]
The key of the translation here is likely mismatched. If anyone is willing to submit a PR to fix this we'll gladly take it.

**Comment by khord** [comment]
@ahanamallik1 That looks to be the correct repro steps, so that leads me to believe that someone already corrected this in a newer version. I'll try to confirm on my end as well tomorrow

**Comment by agagancarczyk** [comment]
hi @khord Has this issue been resolved? If so, could you please close it? Thanks!
