### ISSUE TITLE
Reset password email shows raw link instead of hypertextual text

### ISSUE THREAD

**Issue by remarcoble** [keycloak/keycloak#27480]
### Description

Except for English, all the other languages show the raw link in the email of reset password.

English:
```html
<p><a href="{0}">Link to reset credentials</a></p>
```

Italian (and all other languages):
```html
<p><a href="{0}">{0}</a></p>
```

**Comment by jonkoops** [comment]
This doesn't seem like an enhancement, but rather a bug. I am closing this one, but please log a new issue as a bug, and make sure to fill in all the information required.
