### ISSUE TITLE
`org.keycloak.adapters.KeycloakDeployment.resolveUrls()` is thread-unsafe

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#27489]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/spring

### Describe the bug

`org.keycloak.adapters.KeycloakDeployment.resolveUrls()` can return before `KeycloakDeployment` is fully constructed leading to NPE on access to fields like `org.keycloak.adapters.KeycloakDeployment.logoutUrl`

### Version

22.0.5, 24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

`KeycloakDeployment.getLogoutUrl()` should never be null given the target server is up&running.

### Actual behavior

`KeycloakDeployment.getLogoutUrl()` can be null under heavy load

### How to Reproduce?

![изображение](https://github.com/keycloak/keycloak/assets/1285898/f1d803ce-f93d-49ff-9527-13a55a311822)

Let's have 2 threads (Thread1, Thread2)

1) Thread1: calls `KeycloakDeployment.getLogoutUrl()`
2) Thread1: Code goes inside the `if` and fills in the field `realmInfoUrl` (but not the other fields yet)
3) Thread2: calls `KeycloakDeployment.getLogoutUrl()`
4) Thread2: Code doesn't go inside the `if` (because `realmInfoUrl` is already not null)
5) Thread2: gets KeycloakDeployment.getLogoutUrl = null

### Anything else?

As a fix we may consider initializing `realmInfoUrl` as the last step of the method (unless there are no cross dependencies on its value from other statements).

**Comment by lrozenblyum** [comment]
Same on the latest release.

**Comment by rmartinc** [comment]
@lrozenblyum OIDC adapters are being deprecated and they will disappear in [the next release](https://www.keycloak.org/docs/latest/release_notes/index.html#java-adapter-deprecation-and-removal). If you think this is important and should be fixed in a point release you can send a PR. The idea would be moving the assignment to the end of the synchronization section and add volatile to the property. Please add some test inside `KeycloakDeploymentTest` that initializes it with some threads several times.

**Comment by lrozenblyum** [comment]
@rmartinc is the class `KeycloakDeployment` going to be completely removed or it will be kept for sake of the client adapters that still are going to be kept after the release 24?

(in the latter case it's worth contributing the fix since the issue is general for all adapters depending on this class I believe).

**Comment by rmartinc** [comment]
@lrozenblyum Probably the class will continue although the OIDC adapters will be all gone from download (this is not sure, just my opinion), only the SAML adapters will continue normally. You can send the fix/PR to upstream, but if it is accepted I will mark the issue to be back-ported to 24.x to be useful.

**Comment by lrozenblyum** [comment]
Here it is: https://github.com/keycloak/keycloak/pull/27557
Please let me know @rmartinc if I can do anything to fix a couple of failing CI checks. I see no correlation of failures with the changes in the PR though (https://github.com/keycloak/keycloak/actions/runs/8157745104/job/22298789297?pr=27557, https://github.com/keycloak/keycloak/actions/runs/8157745104/job/22300318438?pr=27557)

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.

**Comment by lrozenblyum** [comment]
It affects not only Spring adapters - `KeycloakDeployment` is a generic class used in adapters that are not supposed to be removed in KC25 I guess @stianst.

**Comment by rmartinc** [comment]
The class is general to all OIDC java adapters, not only Spring, but all of them are going to be removed in 25 as it's in the link we both shared. IMHO @lrozenblyum has done all the work in the PR, so we can proceed with it and backport to 24.x. But it's up to you @stianst. This issue won't affect 25 (maybe for tests or similar but never for a distributed package) so it only makes sense for 24.x.
