### ISSUE TITLE
Process latency increase in Keycloak 22

### ISSUE THREAD

**Issue by shellrausch** [keycloak/keycloak#27490]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

We are planning to update our Keycloak installation from 21.1.1 to 22.0.4 right now (and afterwards to 23). To verify if our setup introduces some bottlenecks, we have done multiple loadtests with 21 und 22. Everytime we do a loadtest with 22 we see increased latencies:

- Median: 36ms to 70ms
- 95th percentile: 225ms to 275ms
- 99th percentile: 316ms to 433ms

The loadtest consists of multiple test-cases like: login, logout, token-exchange, device-login, registration, refresh, revoke, ...
Every test-case has an increased latency.

Current setup

- TLS is terminated by an K8S ingress in front of the Keycloak
- Multi pod keycloak cluster
- External multi pod infinispan cluster (14.0.21.Final) with ~50 million sessions

Is there anything that was changed between 21.1.1 and 22.0.4, that could explain this latency increase?

![latency_keycloak21_22_](https://github.com/keycloak/keycloak/assets/43110475/33d22a7f-d7e5-462e-911f-b627849a4223)
![latency_keycloak21_22](https://github.com/keycloak/keycloak/assets/43110475/24b6141f-a821-4218-a0e1-fd93053da0c0)

### Version

22.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

Similiar latencies as in 21.1.1

### Actual behavior

Median: Increase by 95%
95th percentile: Increase by 22%
99th percentile: Increase by 37%

### How to Reproduce?

We use a cloud service. This is just an example:

```
#!/bin/sh

URL=http://localhost:8080
REALM=master
# Direct access grant needed
USER=admin
PASSWORD=admin
CLIENT=account-console

for i in `seq 1 10000`;
do
  curl -o /dev/null -s -w "%{time_total}\n" -X POST \
      -d "username=$USER" \
      -d "password=$PASSWORD" \
      -d "client_id=$CLIENT" \
      -d "grant_type=password" \
      -d "scope=openid profile" \
      "$URL/auth/realms/$REALM/protocol/openid-connect/token" &
done
```

**Comment by ahus1** [comment]
Thank you for reaching out. You're reporting an issue against a version that is no longer supported as a community release by the Keycloak team. Please test the latest 23.0.x release of Keycloak and let us know if the problem persists. 

In 21.1->22 there have been multiple library changes, but no problem is currently known to cause the regression. There have been fixes to increase the performance of an external Infinispan setup in KC 23, for example #25388. 

If you can reproduce the problem in KC23, we would need additional information from your environment like configuration files, tracing and possibly profiling information.

**Comment by ahus1** [comment]
KC24 has been out, please give this release a try as I heard from other that response times are better.
