### ISSUE TITLE
Operator version 24.0.0 deploys nightly Keycloak

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#27500]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Upgrade to 24.0.0 using the Operator will install nightly Keycloak version which might break DB migration.

This concerns both OLM installations and [raw resources installation](https://github.com/keycloak/keycloak-k8s-resources/blob/24.0.0/kubernetes/kubernetes.yml#L324).

### Version

24.0.0

### Regression

- [x] The issue is a regression

### Expected behavior

Operator uses corresponding Keycloak image

### Actual behavior

Operator uses nightly image

### How to Reproduce?

Install 24.0.0 using Operator

**Comment by stianst** [comment]
Nightly tags are now pointing to 24.0.0, and I've stopped the nightly release to prevent a new release overnight.

Anyone that has upgraded to 24.0.0 before this time will have to manually edit the current migrated version in the DB, otherwise it'll never upgrade the DB again since it'll be pointing to 999.0.0 :/

**Comment by ibotty** [comment]
Should this be done after installing 24.0.1?  If so with the following query?
```sql
UPDATE migration_model SET version = 24.0.0;
```

**Comment by ibotty** [comment]
It would be so great to have an Atom/RSS feed, so one might notice these blog posts...

Thank you for the link!

**Comment by lenzch** [comment]
> It would be so great to have an Atom/RSS feed, so one might notice these blog posts...
> 
> Thank you for the link!

Are you looking for https://www.keycloak.org/rss.xml

**Comment by ibotty** [comment]
Yes, I am.  It's not in the `<head>` of the HTML page.  How did you find it?

**Comment by vmuzikar** [comment]
Operator version 24.0.1 should be now fully released even on OperatorHub.
