### ISSUE TITLE
Use new remote-store options in HA guides

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#27508]
### Description

Since #26756 there are new CLI options for the remote store, which will allow configuring remote Infinispan without a separate XML file.

### Motivation

Simplify the installation.

### Details

A draft PR for KCB already exists in https://github.com/keycloak/keycloak-benchmark/pull/711

**Comment by ahus1** [comment]
There is bug #28638 and as a remedy/workaround I want to have this issue backported to KC24 as the options exist already in KC24. 

@pruivo - please create a backport for this.

The only reason we didn't backport it in the docs was that the change landed in KC24 only in the last minute before the release. Backporting the docs change to 24 would allow us to release the HA guide for RHBK with the current code. 

With the testing over the last weeks, we can be IMHO confident that the options work as expected, and there it is safe to backport this docs change. Let me know if you think otherwise.

**Comment by pruivo** [comment]
@ahus1 backport is here: https://github.com/keycloak/keycloak/pull/28715
