### ISSUE TITLE
Review the Group API

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#27511]
### Description

This epic is about tracking the most important issues related to the Group API so that we can have those issues in a single place.

We should be reviewing those issues and planning how they are going to be delivered.

### Discussion

N/A

### Issues

- https://github.com/keycloak/keycloak/issues/22261
- https://github.com/keycloak/keycloak/issues/20445
- https://github.com/keycloak/keycloak/issues/20308
- https://github.com/keycloak/keycloak/issues/19923
- https://github.com/keycloak/keycloak/issues/17645

### Motivation

Review the current status of the Group API and improve it.

**Comment by marekbnn** [comment]
@pedroigor I believe this ticket can now be closed?
