### ISSUE TITLE
Getting subgroups does pagination before filtering

### ISSUE THREAD

**Issue by pkeuter** [keycloak/keycloak#27512]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When a user with limited rights tries to retrieve subgroups that it has rights on, it will not show them when they are within the limit of the query.

I think this is because this code does pagination first and filters after that: https://github.com/keycloak/keycloak/blob/b066c59a83c99d757d501d8f5e6061372706d24d/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L165

Therefore, rendering no results.

### Version

24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

All available groups should be shown

### Actual behavior

No groups are shown

### How to Reproduce?

* Create 11 groups A to K. 
* Enable fine grained permissions
* Add a user that only has access to group K
* Let the user add a user and select group K, group K will not be visible

**Comment by sguilhen** [comment]
I'm removing the expiration label since the issue already has a PR that potentially fixes it.
