### ISSUE TITLE
Default locale will be override when English is used

### ISSUE THREAD

**Issue by Lexachoc** [keycloak/keycloak#27520]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

This bug exists from Keycloak 22.0.0~24.0.0

![image](https://github.com/keycloak/keycloak/assets/20377719/e909ecd2-6a2c-4db9-9019-9c93d9a615ce)
But I got:
![image](https://github.com/keycloak/keycloak/assets/20377719/39dcd8fe-69af-46e6-83e2-7ea8564d5b49)

If **English** is added as **Supported locales**, the default locale will be override and not displayed!!!

### Version

24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The selected language in **Default locale** should show instead of **English**

### Actual behavior

The selected language in **Default locale** is not displayed, **English** is displayed instead

### How to Reproduce?

Add at least two languages (including **English**) in **Supported locales**
Set **German**(any language except **English**) in **Default locale**

**Comment by rmartinc** [comment]
Hi @Lexachoc!

The default locale logic is a bit more complex and it's explained in the [documentation](https://www.keycloak.org/docs/latest/server_admin/#_user_locale_selection). So probably your browser is sending an `Accept-Language` header which prefers English and that language is selected by default. Try to check if that's the case with your browser. The default locale in the realm is selectde after the header preference.

**Comment by Lexachoc** [comment]
@rmartinc Many thanks for your quick reply!

You're right! I can see it has:
`Accept-Language: en-US,en;q=0.9`

But after I added a another preferred language (not in the list of locale):
`Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7` it still displayes English

until I add German as preferred language (my default locale in Keycloak):
`Accept-Language: de-DE,de;q=0.9,zh-TW;q=0.8,zh;q=0.7,en-US;q=0.6,en;q=0.5`

German is displayed.

I think this is something the administrator should have control over and not the logic of the locale.
For example, a checkbox to specify whether this default locale can be overridden by the `Accept-Language` header:

![image](https://github.com/keycloak/keycloak/assets/20377719/6899adbb-b890-4d9e-aa36-2481f5fe4e8f)

**Comment by jonkoops** [comment]
I don't think we want to make this further configurable. If a user has languages configured that are preferential they should be used at all times.

**Comment by Lexachoc** [comment]
@jonkoops Got it! Then I'll close this issue.
I'm just confused when I see that the default locale is overridden by English.

**Comment by jonkoops** [comment]
> I'm just confused when I see that the default locale is overridden by English.

That is fair, perhaps the help text should be updated here. I think it should be more considered a 'hint', if nothing better is available.
