### ISSUE TITLE
LegacyUserCredentialManager class not found

### ISSUE THREAD

**Issue by nosnilmot** [keycloak/keycloak#27529]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

`LegacyUserCredentialManager`, which is provided by the `keycloak-model-legacy` module, is not available at runtime in Keycloak 24.
This module is documented as [deprecated in Keycloak 24 to be removed later](https://www.keycloak.org/docs/24.0.0/upgrading/#renaming-model-modules), but is effectively removed already.

### Version

24.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Custom code implementing a `UserStorageProvider`, using `LegacyUserCredentialManager` for `UserModel.credentialManager()` implementation (as described in [Keycloak 19 upgrade notes](https://www.keycloak.org/docs/24.0.0/upgrading/#credential-management-for-users)) should continue to run in Keycloak 24.

### Actual behavior

```
2024-03-04 22:06:59,850 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-7) Uncaught server error: java.lang.NoClassDefFoundError: org/keycloak/credential/LegacyUserCredentialManager
```

### How to Reproduce?

Implement a `UserStorageProvider` that works on Keycloak 19-23 using `LegacyUserCredentialManager`. The `user-storage-simple` from Keycloak Quickstarts *before* commit 4af949c8b4d21191486c2c6a32f795fa21a13ea2 should work.

**Comment by ahus1** [comment]
Thank you for reporting this, and sorry for this change to cause you troubles. 

While you have already provided a fix for this in a PR, could you please try if there is a possible workaround: Please add the missing dependency to the providers folder and let me know if this is a suitable workaround for this issue. 

Thanks!

**Comment by nosnilmot** [comment]
Yes, this workaround works as a temporary solution, thanks.
