### ISSUE TITLE
Operator broken as version 24.0.0 is latest in hub

### ISSUE THREAD

**Issue by AndreasBillmann** [keycloak/keycloak#27537]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

In operator hub the 24.0.0 is the latest version, but this version is not available any more in the repository. Currently the usage of keycloak operator without explizit version, does not run as the 24.0.0 could not be loaded from repository. 

### Version

24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The operator hub should reflect the available operator versions in the repository.

### Actual behavior

Failed to pull image "quay.io/keycloak/keycloak-operator:24.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/keycloak/keycloak-operator:24.0.0": failed to resolve reference "quay.io/keycloak/keycloak-operator:24.0.0": quay.io/keycloak/keycloak-operator:24.0.0: not found

### How to Reproduce?

Try to deploy an operator without explizit version number.

### Anything else?

https://operatorhub.io/operator/keycloak-operator
https://quay.io/repository/keycloak/keycloak-operator?tab=history

**Comment by vmuzikar** [comment]
Hello, the 24.0.0 was removed as we've hit a [critical issue](https://github.com/keycloak/keycloak/issues/27500) with it. It was replaced with 24.0.1 as soon as the [OperatorHub PR](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4131) is merged.
