### ISSUE TITLE
Expose quarkus syslog logging now GELF is being deprecated from Keycloak

### ISSUE THREAD

**Issue by nxadm** [keycloak/keycloak#27544]
### Description

GELF logging will be removed from Keycloak because the upstream library has been deprecated: 
https://github.com/keycloak/keycloak/issues/27365

This leaves Keycloak with zero built-in mechanism for remote logging. Is it possible to expose the built-in syslog logging mechanism of Quarkus to Keycloak? This does not add extra dependencies because Keycloak is nowadays built on top of Quarkus.

Pre-quarkus builds of Keycloak could log to syslog, so people that still needed a remote logger that could handle volume moved to the newly GELF logging. Restoring syslog functionality with easy the transition for these kind of setups.

Thank you.

Edit: Quarkus documentation syslog logging: https://quarkus.io/guides/logging#quarkus-logging-json_quarkus-log-syslog-json-syslog-logging

### Motivation

- Keycloak supported Syslog logging.
- While moving to Quarkus, Keycloak lost this functionality while introducing GELF logging as an alternative.
- Keycloak will remove GELF and will break the logging setup of people that needs remote logging for high volumes.

**Comment by ahus1** [comment]
pinging @vmuzikar for this

**Comment by DrHackschnitzel** [comment]
Well, gelf is very useful for high level remote logging, especially when keycloak does not support syslog.
What will be the alternative? remote logging ( with custom fields and json format) is mandatory when using keycloak in container orchestration systems like openshift or kubernetes.
I didnt find any removal plans on the quarkus framework itsself about gelf.

**Comment by nitram22** [comment]
I fully support @DrHackschnitzel statement ! If gelf is removed at least an alternative for remote logging is required

**Comment by djeikyb** [comment]
Will quarkus syslog logging emit multi-line log events as a single log event? I want structured events, not apache style http log lines that I then have to parse. If this is essentially just dumping unstructured lines to a console, it's a big step backwards

**Comment by djeikyb** [comment]
Will quarkus syslog logging emit multi-line log events as a single log event? I want structured events, not apache style http log lines that I then have to parse. If this is essentially just dumping unstructured lines to a console, it's a big step backwards

**Comment by mabartos** [comment]
> Will quarkus syslog logging emit multi-line log events as a single log event? I want structured events, not apache style http log lines that I then have to parse. If this is essentially just dumping unstructured lines to a console, it's a big step backwards

@djeikyb Unfortunately, AFAIK, syslog protocol RFC5424 does not support multi-line logs as a single event as described in this [guide](https://quarkus.io/version/main/guides/centralized-log-management#gelf-alternative-use-syslog).
@loicmathieu Is there anything we can do about it? I guess not, as it's related more to the syslog manners/handling. 

It might be good to try to experiment with the syslog JSON output, verify the behavior, and possibly play with different [delimiters](https://quarkus.io/version/main/guides/logging#quarkus-logging-json_quarkus-log-syslog-json-record-delimiter) for log records. AFAIK, it should be also possible to leverage the UDP Multiline Syslog protocol, which should be interoperable. 

From the long-term Quarkus perspective, OpenTelemetry Logging should be the preferred way to achieve proper centralized log management and will be part of the next Quarkus release - a timeline needs to be determined.

If the Syslog alternative to GELF does not fit your needs, I try to find out our possibilities for improving our centralized logging story. 

_JFYI - I started working on a tool that provides the ability to include arbitrary Quarkus/Quarkiverse extensions to your deployment. It's in the initial phase of development, but the results seem fine. You can follow it here: https://github.com/mabartos/keycloak-quarkus-extensions_

**Comment by nxadm** [comment]
Besides something very custom on the receiving side, JSON output is the way to go in this scenario. Or at least, that's what I do.

**Comment by loicmathieu** [comment]
At Quarkus side, we didn't decied yet to deprecate the existing logging-gelf extension, the underlying library (logstash-gelf) is no longer maintained but is a very mature library so there is no urgency.

However we have two other solutions for centralized log management, both new in Quarkus 3.16 which is around the corder:
- TCP socket appender
- OpenTelemetry log signal

We still need to test how it can be used with various existing system and provide accurate documentation as we have today for logging-gelf (see https://quarkus.io/guides/centralized-log-management).

**Comment by djeikyb** [comment]
@mabartos OTEL would be a great thing replacement for logstash-gelf!
