### ISSUE TITLE
Make general `cache` options runtime

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#27549]
As we've marked the `cache-config-file` as a build time option, we parse it in a runtime anyway. IMHO, it makes sense to provide the capability to specify the config file for cache in runtime. In addition, AFAIK, it could help many deployments. The `cache` and the `cache-stack` are closely tied to the config file. 

I'm not aware of any use cases where the general `cache` options are required to be handled in build time.

More improvements around the `cache` options management will come with the outcome of the discussion https://github.com/keycloak/keycloak/discussions/24055.

**Comment by mabartos** [comment]
@keycloak/cloud-native Does it make sense to you?

**Comment by vmuzikar** [comment]
The only reason we might consider the `cache-config-file` option build time is to provide some built time optimizations – parsing of the config file. But that might bring its own issues (how do we detect changes to that file to retrigger the parsing?). So +1 from my side to make it runtime.

**Comment by mabartos** [comment]
@vmuzikar Yep, ok.

I'd do it iteratively as we could first make these options `runtime`, and then follow the process discussed in https://github.com/keycloak/keycloak/discussions/24055.

This is low-hanging fruit and IMHO, it'd bring quite high value to users. 
WDYT?

**Comment by vmuzikar** [comment]
Yeah, I'm not aware of any risks of making it runtime and the effort to do that is really low. So again, +1 from my perspective.
