### ISSUE TITLE
Not rendered images in https://www.keycloak.org/2024/03/keycloak-2400-released

### ISSUE THREAD

**Issue by lrozenblyum** [keycloak/keycloak#27563]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The article https://www.keycloak.org/2024/03/keycloak-2400-released refers to not existing images which are thus not rendered

### Version

24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

All images should render

### Actual behavior

![изображение](https://github.com/keycloak/keycloak/assets/1285898/5ca08275-0eef-4e09-9a08-e7428bbd5637)

### How to Reproduce?

Open https://www.keycloak.org/2024/03/keycloak-2400-released

**Comment by jonkoops** [comment]
Thanks for reporting this @lrozenblyum, we've published a new version of the post that removes the images.

**Comment by lrozenblyum** [comment]
Thanks @jonkoops
