### ISSUE TITLE
[24.0.1] unable to enable features

### ISSUE THREAD

**Issue by tgurr** [keycloak/keycloak#27561]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

In previous versions like 23.0.7 I was able to enable and use the scripts feature, in 24.0.1 I'm no longer able to do so.

### Version

24.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

Being able to enable and use the scripts feature.

### Actual behavior

Not being able to enable and use the scripts feature.

### How to Reproduce?

In previous versions like 23.0.7 I have `/opt/keycloak/conf/profile.properties` with `feature.scripts enabled` and issuing `su -c "/opt/keycloak/bin/kc.sh build" -s /bin/bash keycloak` & `systemctl restart keycloak.service` enabled the scripts feature:

![23 0 7](https://github.com/keycloak/keycloak/assets/414984/8fd8d60d-5b98-4b2a-9968-d4eb1522b20f)
Even through it doesn't appear to be listed in the logs - probably installed features is not the same as enabled features?:
```
Mär 05 15:16:53 hnkeycloak kc.sh[834]: 2024-03-05 15:16:53,219 INFO  [io.quarkus] (main) Keycloak 23.0.7 on JVM (powered by Quarkus 3.2.10.Final) started in 7.353s. Listening on: http://127.0.0.1:8080
Mär 05 15:16:53 hnkeycloak kc.sh[834]: 2024-03-05 15:16:53,219 INFO  [io.quarkus] (main) Profile prod activated.
Mär 05 15:16:53 hnkeycloak kc.sh[834]: 2024-03-05 15:16:53,219 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
```

Doing the same on 24.0.1 I'm unable to activate the scripts feature and I get:

![25 0 1_scripts](https://github.com/keycloak/keycloak/assets/414984/d9e76871-c4dd-4d75-adee-e621c1fe1b73)
```
Mär 05 14:53:06 hnkeycloak kc.sh[321]: 2024-03-05 14:53:06,143 INFO  [io.quarkus] (main) Keycloak 24.0.1 on JVM (powered by Quarkus 3.8.1) started in 6.495s. Listening on: http://127.0.0.1:8080
Mär 05 14:53:06 hnkeycloak kc.sh[321]: 2024-03-05 14:53:06,144 INFO  [io.quarkus] (main) Profile prod activated.
Mär 05 14:53:06 hnkeycloak kc.sh[321]: 2024-03-05 14:53:06,144 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
```

Also manually trying to enable the feature doesn't do any difference despite it telling me the feature got enabled, here's what I additionally tried for 24.0.1:

```
# su -c "/opt/keycloak/bin/kc.sh build --features=scripts" -s /bin/bash keycloak
Updating the configuration and installing your custom providers, if any. Please wait.
2024-03-05 14:47:00,783 WARN  [org.key.qua.run.cli.Picocli] (main) The following run time non-cli options were found, but will be ignored during build time: kc.db-url, kc.db-username, kc.db-password, kc.hostname, kc.http-enabled, kc.http-host, kc.proxy

2024-03-05 14:47:00,795 INFO  [org.key.com.Profile] (main) Preview features enabled: scripts:v1
2024-03-05 14:47:02,282 INFO  [org.key.com.Profile] (main) Preview features enabled: scripts:v1
2024-03-05 14:47:08,579 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 6717ms
Server configuration updated and persisted. Run the following command to review the configuration:

        kc.sh show-config
```
But after a `systemctl restart keycloak.service` the outcome is still the same, the feature stays disabled.

**Comment by shawkins** [comment]
profile.properties was not a supported mechanism for specifying features. To cut down on the number of formats for features keys, it now uses keycloak.profile.feature.name - where name has _ instead of - where applicable. That format is accepted via the quarkus config, so it's best not to rely on profile.properties.

> But after a systemctl restart keycloak.service the outcome is still the same, the feature stays disabled.

Does that do a --optimized start? If not you should see a warning along the lines of 

```
The previous optimized build will be overridden with the following build options:
        - features=scripts > features=<unset>
To avoid that, run the 'build' command again and then start the optimized server instance using the '--optimized' flag.
```

letting you know that you could be loosing a setting due to an auto-build.

**Comment by tgurr** [comment]
> profile.properties was not a supported mechanism for specifying features.
Thanks I didn't know that and it worked well in the past.

To cut down on the number of formats for features keys, it now uses keycloak.profile.feature.name - where name has _ instead of - where applicable. That format is accepted via the quarkus config, so it's best not to rely on profile.properties.

Could you please elaborate on that or point me to the documentation for this? I don't get where and how exactly I need to create/edit a "quarkus config" and what exactly to put into for the scripts feature like I previously did with profile.properties. I hope it still works via something in conf/ that doesn't get overriden on every distribution package update.

> > But after a systemctl restart keycloak.service the outcome is still the same, the feature stays disabled.
> Does that do a --optimized start? If not you should see a warning along the lines of
> 
> ```
> The previous optimized build will be overridden with the following build options:
>         - features=scripts > features=<unset>
> To avoid that, run the 'build' command again and then start the optimized server instance using the '--optimized' flag.
> ```

Hm can't find anything in that regards so if it doesn't do it by default I suppose no? Here's our current systemd keycloak.service: https://gitlab.exherbo.org/exherbo/net/-/blob/master/packages/net/keycloak/files/systemd/keycloak.service

Having a way like you initially suggested via a config file would be preferrable of course. Thanks in advance!

**Comment by shawkins** [comment]
> Could you please elaborate on that or point me to the documentation for this?

I just mean that the existing configuration options (via the keycloak.conf, system properties, and env https://www.keycloak.org/server/configuration) will work for options of the form keycloak.profile.feature.name - however the only place keys of that form are referenced in the documentation are like https://github.com/keycloak/keycloak/blob/d12711e858ab502ea3428f9af0e59d1470832733/docs/documentation/authorization_services/topics/service-protection-policy-api.adoc?plain=1#L81 - so I'm not sure that they are considered supported either.

The features and features-disabled options are of course fully supported https://www.keycloak.org/server/features

Without --optimized, this start https://gitlab.exherbo.org/exherbo/net/-/blob/master/packages/net/keycloak/files/systemd/keycloak.service#L9 will perform an auto-build if one seems necessary. If the features aren't specified in a way for that auto-build to pick them up, then anything that you passed in to the cli of you build command will be lost.

**Comment by tgurr** [comment]
> > Could you please elaborate on that or point me to the documentation for this?
> 
> I just mean that the existing configuration options (via the keycloak.conf, system properties, and env https://www.keycloak.org/server/configuration) will work for options of the form keycloak.profile.feature.name - however the only place keys of that form are referenced in the documentation are like

* `keycloak.profile.feature.scripts=enabled` in `keycloak.conf` doesn't seem to work.
* `keycloak.profile.feature.scripts=enabled` in `profile.properties` results in a failure to rebuild

```
Updating the configuration and installing your custom providers, if any. Please wait.
ERROR: Failed to run 'build' command.
ERROR: Invalid config value 'enabled ' for feature key keycloak.profile.feature.scripts
```

* adding `EnvironmentFile=/etc/default/keycloak` under `[Service]` in `keycloak.service` and creating a file `/etc/default/keycloak` with `keycloak.profile.feature.scripts=enabled` also doesn't work.

The only thing that does work is manually issue `su -c "/opt/keycloak/bin/kc.sh build --features=scripts" -s /bin/bash keycloak` and adding the `--optimized` to the systemd service `ExecStart=/opt/keycloak/bin/kc.sh start --optimized`

But that involves manual steps and `--optimized` isn't the right thing to have for e.g. upgrades e.g. when just moving from keycloak version x to y and restart the service.

> Without --optimized, this start https://gitlab.exherbo.org/exherbo/net/-/blob/master/packages/net/keycloak/files/systemd/keycloak.service#L9 will perform an auto-build if one seems necessary. If the features aren't specified in a way for that auto-build to pick them up, then anything that you passed in to the cli of you build command will be lost.

Still need to have a way to do exactly that "way for that auto-build".

**Comment by shawkins** [comment]
> keycloak.profile.feature.scripts=enabled in keycloak.conf doesn't seem to work.

I need to qualify my suggestion - keycloak.conf will only work for the features options. 

keycloak.profile.feature.name - doesn't seem to be picked up by keycloak.conf nor quarkus.properties. I would have expected that to work based upon how the logic looks, but the Configuration at that point must not be defined to pick up values from the file locations.

> ERROR: Invalid config value 'enabled ' for feature key keycloak.profile.feature.scripts

Note that there appears to be an extra space at the end of enabled.

> adding EnvironmentFile=/etc/default/keycloak under [Service] in keycloak.service and creating a file /etc/default/keycloak with keycloak.profile.feature.scripts=enabled also doesn't work.

I'm not sure about that mechanism, but the following will work

* as options:
```
./kc.sh build|start --features=scripts
```
* as an env variables
```
KEYCLOAK_PROFILE_FEATURE_SCRIPTS=enabled ./kc.sh build|start
KC_FEATURES=scripts ./kc.sh build|start
```
* as system properties:
```
./kc.sh build|start -Dkc.features=scripts
./kc.sh build|start -Dkeycloak.profile.feature.scripts=enabled
```

Again at this point keycloak.profile.feature.name is essentially undocumented, so using the features option is probably the best path.

> Still need to have a way to do exactly that "way for that auto-build".

You are showing both using a build command, and an non-optimized start. If you don't want to use an optimized start, and want to stick with a non-optimized start, that's fine - it just means your startup time will be a little longer. If you are doing non-optimized starts, then make sure your feature/features configuration is provided to the command in one of the ways discussed above.

**Comment by tgurr** [comment]
> Again at this point keycloak.profile.feature.name is essentially undocumented, so using the features option is probably the best path.

Thanks for the detailed information and listing all available options, that helped me a lot! Just to be sure what you mean with that quoted sentence, `KC_FEATURES` is there to stay where `KEYCLOAK_PROFILE_FEATURE_SCRIPT` might go away? I've now updated our package incorporating being able to set the features via env flag `KC_FEATURES` according to your suggestion:
https://gitlab.exherbo.org/exherbo/net/-/commit/78dc82fc1fc3fe762a4051ff3438369ef0f44497
Works fine that way, I can make changes to the file, restart keycloak and things get picked up like they were before when using the `profile.properties`. Again thanks for you help and patience!

**Comment by shawkins** [comment]
> KC_FEATURES is there to stay where KEYCLOAK_PROFILE_FEATURE_SCRIPT might go away?

Correct, features / KC_FEATURES is fully supported.

> Again thanks for you help and patience!

No problem. There's quite a few nuances to the configuration and there's an added wrinkle here unsupported stuff like profile.properties.

**Comment by shawkins** [comment]
> keycloak.profile.feature.name - doesn't seem to be picked up by keycloak.conf nor quarkus.properties. I would have expected that to work based upon how the logic looks, but the Configuration at that point must not be defined to pick up values from the file locations.

To follow up on this - that's because both of those property sources are filtered. keycloak.conf can only have properties matching the built-in options or prefixed as spi. And the quarkus.properties can have only quarkus prefixed properties.

Closing as not planned since using the features option works for you.
