### ISSUE TITLE
SAML POST AuthnRequest binding fails with Content Security Policy Error

### ISSUE THREAD

**Issue by mcgrawia** [keycloak/keycloak#27572]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

Hi Keycloak team,

I just set up a SAML Identity Provider (Okta) in my Keycloak instance running locally at `http://localhost:8080`. When I set `HTTP-POST binding for AuthnRequest = OFF`, the login flow with Okta works as expected. Unfortunately, when I set `HTTP-POST binding for AuthnRequest = ON`, the login flows fails with the following error in the browser console. It looks like the inline script that submits the Authn POST to Okta is not being allowed to run in the browser.

![Screenshot 2024-03-05 at 1 20 57 PM](https://github.com/keycloak/keycloak/assets/6445305/331659de-8c8e-4214-a0d1-feb58c708ade)

I am not that familiar with CSPs, but it seems like the redirection page in Keycloak needs to be updated to whitelist the hash of the script or add a nonce?

Thanks for the help!

### Version

22.0.5, 24.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect to be able to use HTTP-POST binding for SAML AuthnRequests.

### Actual behavior

Using the HTTP-POST binding for SAML AuthnRequest doesn't redirect me to the IdP to log in.

### How to Reproduce?

1. Set up a SAML Identity Provider
2. set the SAML identity provider as the default provider for the realm
3. Set up a client to sign in users
4. attempt to sign in a user and observe the redirect to the IDP never occurs

**Comment by rmartinc** [comment]
Hi @mcgrawia!

I think that you have modified the `Content-Security-Policy` option in the `Security defenses` of the realm adding `script-src 'self'`, right?

Sadly there are parts that uses unsafe-inline in keycloak. I think there is a general issue about the same already filed. SAML is just one of those parts that are using inline script code.

I found the issue: #9553

Please check if that's the case and, in that case, this is just a duplicate of the unsafe-inline issue.

**Comment by mcgrawia** [comment]
thanks @rmartinc for the reply! Apologies for confusion, I wasn't aware our team had modified those settings or that those settings existed (still a bit new to KC). Adding the SHA to the CSP settings fixed the issue. I'll close this and follow along on #9553. Thank you for the help!
