### ISSUE TITLE
How to add customizations to /par request in Keycloak

### ISSUE THREAD

**Issue by pulkit10251** [keycloak/keycloak#27587]
### Description

My requirement is that in the /par/request, I want to fetch data from my custom endpoint and set this data and continue the usual /par/request flow. I was looking if I can create some SPI to achieve it. But till now i don't find anything.

please let me know if some solution exist for my usecase. One more thing is I know it can be easily achievable by creating my own custom endpoint using SPI and then call the /par/request from inside. But i wanted to see if I can achieve it from here only. Thanks

**Comment by stianst** [comment]
Hi, creating a task issue is not the best place to ask for help, please see https://www.keycloak.org/community
