### ISSUE TITLE
Mixed use of javax and jakarta in org.keycloak.admin.client

### ISSUE THREAD

**Issue by Yc-Chen** [keycloak/keycloak#27609]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/jee

### Describe the bug

Hi, we recently upgraded our java application from using Keycloak 21 to 22 and we started to have runtime exceptions related to jakarta. The package we use is `org.keycloak:keycloak-admin-client:22.0.5`

After some searching, I eventually came to this [file](https://github.com/keycloak/keycloak/blob/release/22.0/integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/UserProfileResource.java), where there is inconsistent reference of `APPLICATION_JSON`:

In L42

```@Consumes(jakarta.ws.rs.core.MediaType.APPLICATION_JSON)```

But in L46, simply
```@Produces(MediaType.APPLICATION_JSON)```

And there is no import of jakarta in the admin-client.

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

No build issues or runtime issues when having `import org.keycloak.admin.client.Keycloak;`  

### Actual behavior

We see build error: `class file for jakarta.ws.rs.core.Response not found`.

### How to Reproduce?

(I'm not able to provide the code as it is private. But I hope I already found the root cause.)

**Comment by mposolda** [comment]
This is low priority, but at the same time, it should be easy to fix. Hopefully we can fix this for Keycloak 25 (or even 24.0.X)

**Comment by jonkoops** [comment]
@mposolda shall we mark this to be backported for 24?
