### ISSUE TITLE
Remove sid or session_state from tokens

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#27624]
Claim `sid` and `session_state` is currently duplicated in the access token (and also in ID Tokens and Refresh token). We can maybe have protocol mappers to make sure that this claim is added only once (not two times). This might apply also for ID Token and Refresh token and others.

We can check the specifications to see which of those claims should be added by default and which of them should be ommitted by default. We will still need some way to add the claim by protocol mapper (maybe "client note protocol mapper")

**Comment by graziang** [comment]
After some investigation:

- `session_state` claim according with [OpenID Connect Session Management](https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions) is REQUIRED if session management is supported.

- `sid` claim instead according with [OpenID Connect Front-Channel Logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html#OPLogout) and [OpenID Connect Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html#BCSupport) is OPTIONAL and represents a session of a User Agent or device for a logged-in End-User at an RP.


In Keycloak `session_state` and `sid` have always the same value, and are present both in access token and id token. The `sid` claim is never used instead there is a large use of the `IDToken.getSessionState()`. Interesting fact is that `session_state` is marked as deprecated in favor of the `sid`.

https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/IDToken.java#L69-L72

`sid` claim is also used for logout token during backchannel logout.

**Comment by Sp4m4** [comment]
Hello,

Sorry, but I'm not sure I understand the decision. 
You indicate that KC considers the values of the Session_state and SID parameters to be identical. 
You also indicate that the OIDC standard sets the session_state attribute as mandatory for session management. 
You note that SID is rarely used, whereas session state is widely used.

If this is the case, why did you decide to delete session_state instead of SID? 
Perhaps i am wrong in my understanding. 
Thank you very much for your explanations, which will help me to understand better. 

Translated with DeepL.com (free version)

**Comment by minusdavid** [comment]
It looks like this change broke Drupal's Keycloak OpenID Connect module. I reckon it would be good to revert this change.

However, as noted on PR https://github.com/keycloak/keycloak/pull/28354 and https://www.keycloak.org/docs/latest/release_notes/index.html#lightweight-access-token-to-be-even-more-lightweight, it is possible to re-add the "session_state" claim using a protocol mapper.

In Keycloak 26.2.4, I note that the "Session State (session_state)" mapper is included in the "By configuration" list when adding a mapper to a scope.
