### ISSUE TITLE
Keycloak issues action tokens with the --hostname-url even if the "Frontend URL" is set for realm. Then expects tokens to be issued from "Frontend URL" .

### ISSUE THREAD

**Issue by redabourial** [keycloak/keycloak#27627]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When generating tokens with this method https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/actiontoken/DefaultActionToken.java#L157 the issuer and audience's domain are the same value as --hostname-url even if the frontendUrl of realm is set.

This is problematic since this causes generated tokens to be invalid :
```
2024-03-06 17:05:31,438 WARN  [org.keycloak.events] (executor-thread-2) type="EXECUTE_ACTION_TOKEN_ERROR", realmId="07b72171-29b7-44f8-b1b9-855c2d6e9f65", clientId="null", userId="7c612117-8e5c-41b0-a1f0-4388668a1c14", ipAddress="172.18.0.8", error="invalid_request", reason="Invalid token issuer. Expected 'https://test23.localhost/realms/test23'", token_id="a0679d83-6b7b-4079-9fc9-7703a9399cf6", action="ext-magic-link"
```

Keycloak expects the tokens for a realm to be issued by frontendUrl while generating them from --hostname-url
![Screenshot from 2024-03-06 18-08-37](https://github.com/keycloak/keycloak/assets/17471331/33e959ab-4c6d-46c2-bbc2-a7bc677acfd1)

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Generated tokens should be issued and have an audience equal to "frontendUrl" if it is set.

### Actual behavior

Generated tokens are issued and have audience equal to --hostname-url

### How to Reproduce?

set the frontendurl value and generate a token with an extension such as https://github.com/p2-inc/keycloak-magic-link/issues/72 . 
the token will be invalid.

### Anything else?
[realm issuer](https://github.com/keycloak/keycloak/blob/f0f8a88489ac4509a0a0d79ea4ae871f28ee8e1b/services/src/main/java/org/keycloak/services/Urls.java#L153C26-L153C37) should take frontendurl into account so that  [token serialization](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/actiontoken/DefaultActionToken.java) issues the tokens with frontendUrl. Otherwise extensions that use token are broken when frontendUrl is set.

**Comment by mposolda** [comment]
@vmuzikar Is it ok to re-assign this to cloud-native team as I suppose this is something, which might be improved with the hostname work cloud-native team has in the backlog? Feel free to re-assign back to core-clients if this is unrelated.

**Comment by shawkins** [comment]
@redabourial I think this issue is happending because of switching the realm https://github.com/p2-inc/keycloak-magic-link/blob/c6723a1f9f496d00c4931b75680276517f1748a5/src/main/java/io/phasetwo/keycloak/magic/MagicLink.java#L223 

The UriInfo https://github.com/p2-inc/keycloak-magic-link/blob/c6723a1f9f496d00c4931b75680276517f1748a5/src/main/java/io/phasetwo/keycloak/magic/MagicLink.java#L208C44-L208C50 is correct for the frontend of the initial realm.

I think you need to then need to create a different UriInfo to match that realm you are setting.

**Comment by shawkins** [comment]
~priority-low
