### ISSUE TITLE
Only allow a known refferer URI for the Account Console

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#27628]
It is possible to specify a referrer for the Account Console through a query parameter (`referrer_uri`) , this will show a link to the user to return to the referrer location:

![image](https://github.com/keycloak/keycloak/assets/695720/ef0a4e6a-2000-448c-b76e-458609e8fa3e)

This link should only be shown if the URL is known for the client specified in the `referrer` parameter.

**Comment by ssilvert** [comment]
@jonkoops Are you sure this is a regression?  I don't remember any check for this that we ever had?  Maybe it should be an enhancement?
