### ISSUE TITLE
In the account console, the link "Back to security-admin-console" disappears after the first navigation

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#27622]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When I change from the admin UI to latest account UI, I see the message "Back to security-admin-console" in the upper right corner which I can click on. 

Once I start navigating, this link disappears. 

With the previous account console, this link stayed.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

The link "Back to security-admin-console" should stay in the upper right corner, even when navigating between different menu items in the account console.

### Actual behavior

The link disappears when clicking for example on "Applications". 

### How to Reproduce?

* Login to Keycloak as an admin
* In the upper right corner next to the avatar, choose "Manage account" -> account console opens, link "Back to security-admin-console" is present 
* Lick on "Applications" in the account console -> link "Back to security-admin-console" is gone

**Comment by hmlnarik** [comment]
This is consequence of #27442 since the URI query parameters are not preserved upon navigation.

**Comment by ahus1** [comment]
Thank you for the fix, @hmlnarik!
