### ISSUE TITLE
customising 'Invalid Username/password' error message

### ISSUE THREAD

**Issue by sharanu116** [keycloak/keycloak#27644]
### Description

is there any option in the keycloak to customise the error messgae "Invalid Username/password"

**Comment by sharanu116** [comment]
In Addition to above raised request, we wanted to configure different error message(like Account locked) instead of showing "Invalid username or password" in case of Account locked due to too many wrong login attempts.
Please suggest me on this.

**Comment by stianst** [comment]
This is not the correct avenue to ask for help. Please see https://www.keycloak.org/community
