### ISSUE TITLE
Password policy for not having username in the password

### ISSUE THREAD

**Issue by sharanu116** [keycloak/keycloak#27643]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have applied password policy of ‘Not Username’. But that policy checks for username exactly same as password, however requirement is to not allow any part of username not present in the password
For example lets say username is 'root'. and password is 'root123',In this case keycloak should not allow the login.

### Version

22.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

login should not happen when the password contains prefix of username or part of username

### Actual behavior

login should not happen when the password contains prefix of username or part of username

### How to Reproduce?

create a username as  'root' and password as 'root123' and apply password policy not having username

**Comment by gilvansfilho** [comment]
I checked the source code of main branch and the behavior remains in latest release so I did a PR do introduce a new policy which check if password contains username.

**Comment by gilvansfilho** [comment]
There are a PR open to this...
