### ISSUE TITLE
resource_access and roles dublication 

### ISSUE THREAD

**Issue by lnwara** [keycloak/keycloak#27648]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I have integrated with Keycloak REST API to manage users and groups through my portal app witch reflect custom client,
 I also have created a custom role (let's call it portal-admin) intended to include several built-in roles (e.g., view-users, manage-users). I used the composite role feature to achieve this. 

However, when tokens are issued, all roles, including the built-in ones, are listed individually in the token. I'm looking for a way to only display the portal-admin role in the token, without exposing the individual built-in roles it comprises. Is there a recommended approach within Keycloak to achieve this kind of role abstraction in the access token?

Also, I removed the resource_access mapper, aiming to streamline the token content. However, this led to all Keycloak REST APIs related to user and group management returning an "Unauthorized" 401 status. It seems that these APIs expect specific roles to be present under the resource_access claim. Is there a way to customize tokens without impacting the authorization for Keycloak's built-in administrative functions?

### Version

23.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

{
  "exp": [expiration timestamp],
  "iat": [issued at timestamp],
  "jti": "[token identifier]",
  "iss": "[issuer URL]",
  "aud": [
    "realm-management",
    "service1",
    "service2",
    "account",
    "service3"
  ],
  "sub": "[subject identifier]",
  "typ": "Bearer",
  "azp": "[client id]",
  "session_state": "[session identifier]",
  "acr": "1",
  "allowed-origins": [
    "[allowed origin1]",
    "[allowed origin2]"
  ],
  "scope": "scope1 scope2 scope3",
  "sid": "[session identifier]",
  "email_verified": false,
  "roles": [
    "portal-admin"
  ],
  "name": "[Full Name]",
  "preferred_username": "[username]",
  "OrganizationId": "[Organization ID]",
  "given_name": "[First Name]",
  "family_name": "[Last Name]",
  "email": "[email]"
}

### Actual behavior

{
  "exp": [expiration timestamp],
  "iat": [issued at timestamp],
  "jti": "[token identifier]",
  "iss": "[issuer URL]",
  "aud": [
    "realm-management",
    "service1",
    "service2",
    "account",
    "service3"
  ],
  "sub": "[subject identifier]",
  "typ": "Bearer",
  "azp": "[client id]",
  "session_state": "[session identifier]",
  "acr": "1",
  "allowed-origins": [
    "[allowed origin1]",
    "[allowed origin2]"
  ],
  "realm_access": {
    "roles": [
      "role1",
      "role2",
      "role3",
      "custom-role"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
       "view-realm",
        "manage-users",
        "view-users",
        "view-clients",
        "query-clients",
        "query-groups",
        "query-users"
      ]
    },
    "service1": {
      "roles": [
        "service1-role"
      ]
    },
    "account": {
      "roles": [
       "manage-account",
        "view-groups",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "scope1 scope2 scope3",
  "sid": "[session identifier]",
  "email_verified": false,
  "roles": [
   "view-realm",
    "manage-users",
    "view-users",
    "view-clients",
    "query-clients",
    "query-groups",
    "query-users",
    "manage-account",
    "view-groups",
    "manage-account-links",
    "view-profile",
    "offline_access",
    "uma_authorization",
    "default-roles-deplyment",
    "portal-admin"
  ],
  "name": "[Full Name]",
  "preferred_username": "[username]",
  "OrganizationId": "[Organization ID]",
  "given_name": "[First Name]",
  "family_name": "[Last Name]",
  "email": "[email]"
}

### How to Reproduce?

1. Creating custom role with composite built-in roles, then add the custom role mapper , this led to list all roles.
2. remove the resource access mapper, this will return unauthorized response.

**Comment by lnwara** [comment]
Unfortunately, the issue remains unresolved in the latest version 24.0.1.

**Comment by pedroigor** [comment]
AFAIK, there is no way to achieve what you want. Roles are going to be expanded and Keycloak expect roles from either the `realm_access` or `resource_access` claims when making RBAC decisions based on a bearer token.

That is why you have 401 when accessing the Admin API.

We don't have plans to change that.
