### ISSUE TITLE
Admin tests: Flaky realm_settings_user_profile_enabled test

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#27653]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Workflow failure: Admin UI E2E - realm_settings_user_profile_enabled fails

https://github.com/keycloak/keycloak/actions/runs/8185384876#summary-22381904792
https://github.com/keycloak/keycloak/actions/runs/8181117762#summary-22370558874

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

tests pass

### Actual behavior

tests fail

### How to Reproduce?

run the test several times

### Anything else?

This is post fixing #27337

**Comment by hmlnarik** [comment]
https://github.com/keycloak/keycloak/actions/runs/8203236778/job/22435867196

**Comment by tkyjovsk** [comment]
https://github.com/keycloak/keycloak/actions/runs/8248665365/job/22561781327

**Comment by hmlnarik** [comment]
Original fix was fixing a potential race condition and was insufficient, see e.g. jobs below. Reopening.
- https://github.com/keycloak/keycloak/actions/runs/8328702336/job/22790669785
- https://github.com/keycloak/keycloak/actions/runs/8328664494/job/22790498415
- https://github.com/keycloak/keycloak/actions/runs/8328662288/job/22790429386
