### ISSUE TITLE
Keycloak 24 very slow compared to 23

### ISSUE THREAD

**Issue by gjvoosten** [keycloak/keycloak#27654]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have a suite of server-side tests (Java) that test our GraphQL API using authenticated requests, with a Keycloak Docker container as the authentication back-end. Running the tests against Keycloak 23.0.7 takes 11 minutes, whereas running the tests against Keycloak 24.0.1 takes 19 minutes, so almost double. The only difference between the two is the version of Keycloak running.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

I would expect the performance to be similar.

### Actual behavior

Keycloak is a _lot_ slower.

### How to Reproduce?

Running the server-side tests in our repo.

### Anything else?

We first noticed this when the GitHub Actions builds for the Renovate PRin our repo that updates Keycloak from 23.0.7 to 24.0.1 took twice as long.

**Comment by stianst** [comment]
You may want to read the release notes, specifically:
```
Changes to Password Hashing
In this release, we adapted the password hashing defaults to match the [OWASP recommendations for Password Storage](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2).

As part of this change, the default password hashing provider has changed from pbkdf2-sha256 to pbkdf2-sha512. Also, the number of default hash iterations for pbkdf2 based password hashing algorithms changed. This change means better security aligned with latest recommendations, but it has impact on performance. It is possible to stick to the old behaviour by adding password policies hashAlgorithm and hashIterations to your realm. For more details, see the [Upgrading Guide](https://www.keycloak.org/docs/24.0.0/upgrading/).
```

If your benchmarking is doing user logins it is expected that those are more expensive as the hashing intervals have been updated to match best practices.

**Comment by gjvoosten** [comment]
@stianst Ah, that makes sense; I'll see if I can experiment with that and if indeed that change is causing the slow down. I'll report back here, okay?

**Comment by gjvoosten** [comment]
And indeed that was the cause of the slow down. We seed Keycloak with a realm that had all passwords hashed as pbkdf2-sha256/27500, but without any explicit password policy. So at first authentication, each user's password would be re-hashed as pbkdf2-sha512/210000. Simply adding:
```json
  "passwordPolicy" : "hashAlgorithm(pbkdf2-sha256) and hashIterations(27500)",
```
to the realm restored performance with Keycloak 24 to what it was before with Keycloak 23.
So thank you, @stianst! :bow: 

[Maybe you should upgrade the AI behind the **keycloak-github-bot**, because I believe I provided _sufficient information_ for you to give me the correct hints. :wink: ]
