### ISSUE TITLE
Unauthorized access and manipulation of admin user privileges

### ISSUE THREAD

**Issue by martinlolek** [keycloak/keycloak#27669]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have roles set in keycloak. Technical user support has the right to view all users, edit passwords and other data + login/impersonate as regular users so they can solve problems from their point of view. The problem is that the technical support can do the same with the admin user of the given realm and thus gain permissions that do not belong to them, or change the admin's password. In most cases, everyone from technical support knows who the admin of the given realm is, so it is not a problem to know or guess the username or email. I think this should be banned or this behavior should be consciously allowed.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should not gain higher rights this way, should not change the account of a user who has higher rights

### Actual behavior

The user easily obtains rights that do not belong to him

### How to Reproduce?

1. Login as user with role realm-management: view-users and impersonation
2. Find a user with realm-admin role and impersonate him
3. Congratulations you are realm admin now

**Comment by hmlnarik** [comment]
@martinlolek Thank you for reporting the issue. Please see https://github.com/keycloak/keycloak/security/policy for the right way of reporting suspected security issues next time.

**Comment by hmlnarik** [comment]
Given the affected area, I am reassigning this issue to the core teams.
@keycloak/core-iam Could you please review this issue?

**Comment by pedroigor** [comment]
@martinlolek For reporting security issues, consider reading https://www.keycloak.org/security.html. We are happy to discuss this report in mode details in the proper channel.
