### ISSUE TITLE
Account console does not work with `--http-relative-path`

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#27709]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The router defined in account console assumes fixed pathname /realms/_realm_/account, however when using `--http-relative-path`, this changes significantly. For example, the testsuite uses `/auth` prefix, and the account console only displays error when navigating to `/auth/realms/master/account/`.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Account console is displayed

### Actual behavior

Account console is not loaded

### How to Reproduce?

Run keycloak with `--http-relative-path=/auth` and navigate to http://localhost:8080/auth/realms/master/account/

### Anything else?

Caused by #22192, the fix #27604 was assuming only default locations.

**Comment by jonkoops** [comment]
@hmlnarik should this be backported to 24?

**Comment by hmlnarik** [comment]
No, since this stopped working due to usage of browser instead of hash router, and is thus only relevant for branches after #22192.

**Comment by jonkoops** [comment]
Ok, thanks, just checking up :+1:
