### ISSUE TITLE
Warning about global state on start

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#27718]
On a simple start or start-dev the logs will show:

> 2024-02-27 11:47:21,993 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled

Neither of our built-in cache configs have global-state defined, but the ClusterPermissionMapper and the ClusterRoleMapper create internal caches that expect persistence. For dev mode there doesn't seem to be a great way to ignore this, and it doesn't like we should be configuing a global-store in that case. @mhajas @mabartos @vmuzikar is there any benefit to users configuring a global-state when not in dev mode? If not, then it seems like we'd want the upstream to switch this to a debug message instead.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/issues/27308#issuecomment-1966640972_

**Comment by shawkins** [comment]
@tristantarrant can you weigh in on if there is any benefit for keycloak to configure a global state, or if we should look to omit this warning in some way?

**Comment by tristantarrant** [comment]
Are you enabling authorization ?

**Comment by shawkins** [comment]
@tristantarrant No. We by default provide configuration for infinispan in local and clustered mode https://github.com/keycloak/keycloak/tree/main/quarkus/runtime/src/main/resources - neither have explicit configuration for authorization.

**Comment by shawkins** [comment]
@tristantarrant can you confirm that if we aren't using authorization, then this warning isn't meaningful? If that's the case, should there be an upstream change to detect this and lessen the warning, or should we look to do log filtering on the keycloak side?

**Comment by tristantarrant** [comment]
https://github.com/infinispan/infinispan/pull/12171

**Comment by shawkins** [comment]
Thank you @tristantarrant 

We'll close this issue when we pick up that fix.
