### ISSUE TITLE
Refactor `getRootPath()` 

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#27716]
I think this is the only place `getRootPath()` was used in the actual code that gets bundled. So perhaps we should move this utility out of `src`? Or perhaps even better, we could re-write `getRootPath()` to return `new URL(environment.baseUrl).pathname`.

_Originally posted by @jonkoops in https://github.com/keycloak/keycloak/pull/27713#discussion_r1517665495_

**Comment by jonkoops** [comment]
If we resolve #19750 this will likely be even easier to resolve, as the dev and prod servers would be running in the same place.

**Comment by edewit** [comment]
outdated when https://github.com/keycloak/keycloak/issues/19750 was merged
