### ISSUE TITLE
Release notes and Migration guide for Hostname v2

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#27730]
### Description

Add a chapter to the [upgrading guide](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/keycloak/changes-25_0_0.adoc) covering migration for Hostname v2. It should show some examples of old vs. new config (a table?) both for server and the operator.

This should be also linked to from the release notes.

**Comment by vmuzikar** [comment]
@mabartos Could you please look into this one?

**Comment by mabartos** [comment]
@vmuzikar Yes, sure.
