### ISSUE TITLE
Remove Hostname v1

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#27731]
### Description

This concerns:
* Code
* Options, incl. the `--proxy` option
* Docs
* Tests
* Fields in the Keycloak CR
* Profile features `hostname:v1` and `hostname:v2`

**Comment by vmuzikar** [comment]
@shawkins We might need a new CRDs version for this since `adminUrl` and `strictBackchannel` are no longer relevant for hostname v2. :/ We can't do this earlier than KC 27 so this should give us enough time to figure it out.

**Comment by shawkins** [comment]
@vmuzikar it would be ideal to have a new crd version, but we can always just add validation in the operator if those fields are in use.

**Comment by vmuzikar** [comment]
@keycloak/cloud-native jFYI – after discussion with @stianst, moved to 26.
