### ISSUE TITLE
KeycloakContext is not set in session when executing `DefaultBruteForceProtector.sendEvent`

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#27740]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The `session.getContext()` is null when executing `DefaultBruteForceProtector.sendEvent`. We discovered this when upgrading our EventListenerProvider extension that uses `session.getContext().getRealm()` in the factory.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

`session.getContext()` should be set.

### Actual behavior

`session.getContext()` is not set.

Here is the stack where it fails.
```
    at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:195)
    at org.keycloak.events.EventBuilder.lambda$getEventListeners$0(EventBuilder.java:84)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at org.keycloak.events.EventBuilder.getEventListeners(EventBuilder.java:93)
    at org.keycloak.events.EventBuilder.<init>(EventBuilder.java:68)
    at org.keycloak.services.managers.DefaultBruteForceProtector.sendEvent(DefaultBruteForceProtector.java:240)
    at org.keycloak.services.managers.DefaultBruteForceProtector.failure(DefaultBruteForceProtector.java:203)
    at org.keycloak.services.managers.DefaultBruteForceProtector.run(DefaultBruteForceProtector.java:291)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to Reproduce?

Create an `EventListenerProviderFactory` implementation that calls `session.getContext().getRealm()` in the `create()` method. It will throw an NPE

**Comment by mposolda** [comment]
@xgp You pointed that this is a regression. Regression means that some functionality, which was previously working, is broken now in Keycloak 24.0.1. Could you please specify what is the Keycloak version where this scenario was working for you?

**Comment by xgp** [comment]
Sorry for the lack of definition @mposolda

It worked <`24`. Most recently tested in `23.0.7` the context is not null.

**Comment by xgp** [comment]
For additional information, this was the bug reported to one of our extensions that caused us to find the issue: https://github.com/p2-inc/keycloak-events/issues/52

**Comment by mposolda** [comment]
@xgp Ok, Thanks for the info!

**Comment by douglaspalmer** [comment]
I'm confused. DefaultBruteForceProtector.sendEvent() is new code that was only introduced in Keycloak 24. You must have been using something different in 23.

**Comment by xgp** [comment]
@douglaspalmer You are correct. I wasn't clear about **how** the behavior was different in previous versions, and **why** I was pointing to `DefaultBruteForceProtector.sendEvent()`.

Let me restate the case.

When an event related to brute force attack detection (e.g. `EventType.USER_DISABLED_BY_PERMANENT_LOCKOUT`) is emitted, and subsequently consumed by an `EventListenerProvider`, the `KeycloakContext` is null (in KC 24), whereas previously in KC <23) it was set correctly.

I was pointing to `DefaultBruteForceProtector.sendEvent()` because that was in the stack trace, and I looked in that code and found that it was not being set there. I thought that would be helpful in debugging. I was not suggesting that was **how** it used to work, or that the same code used to exist. My apologies for the unclear bug.

**Comment by douglaspalmer** [comment]
@xgp No problem. Are you able to build from source to verify that the pull request fixes the issue for you?

**Comment by douglaspalmer** [comment]
@xgp Can you please provide some code that reproduces this issue? My PR can't have helped this problem. Moreover, the KeycloakContext is created by the constructor for the DefaultKeycloakSession so it can never be null. Something else is going on here.

**Comment by xgp** [comment]
@douglaspalmer It looks like it is the Realm in the `KeycloakContext` that is null. 

To reproduce:

1. Create an `EventListenerProviderFactory` implementation with the following code:
```java

  public EventListenerProvider create(KeycloakSession session) {
    RealmModel realm = getRealm(KeycloakSession session);
    // realm is null
   return null;
  }

  static RealmModel getRealm(KeycloakSession session) {
    if (session.getContext() == null) {
      return null;
    }
    if (session.getContext().getRealm() != null) {
      return session.getContext().getRealm();
    }
    if (session.getContext().getAuthenticationSession() != null
        && session.getContext().getAuthenticationSession().getRealm() != null) {
      return session.getContext().getAuthenticationSession().getRealm();
    }
    if (session.getContext().getClient() != null
        && session.getContext().getClient().getRealm() != null) {
      return session.getContext().getClient().getRealm();
    }
    return null;
  }
```
2. Cause an event to be emitted of type `USER_DISABLED_BY_PERMANENT_LOCKOUT` or `USER_DISABLED_BY_PERMANENT_LOCKOUT`.
3. `realm` is null
 

FYI we originally created that messy `getRealm(session)` method because of https://github.com/keycloak/keycloak/issues/20105

**Comment by mposolda** [comment]
Lowering the priority of this as it might be a corner case and the issue related to custom provider only. It can be still good if we're able to fix, but not a blocker for Keycloak 24.0.2 release.

**Comment by douglaspalmer** [comment]
@xgp I'm pretty sure this is the same behaviour that existed in 23 when the permanent lockout was introduced. It's not a regression. The problem is that brute force protection does not operate within an existing session. It's a separate thread that iterates over the event log. It creates it's own session that isn't tied to a specific realm.

**Comment by douglaspalmer** [comment]
@xgp the realm id should be set in the event though. You can access it with Event.getRealmId().

**Comment by xgp** [comment]
Thanks for all your help with this @douglaspalmer 

The problem is that we need the realm in the factory `create` method, and there doesn't seem to be any indication that it will only be conditionally available. This has been a problem in the past where extensions are handed a `KeycloakSession`, but the context is not hydrated with realm, client, etc. 

Is there no way to set the realm value? Make a new session and do a runintransaction? If there is an expectation that some of the time it will not be a full `KeycloakSession` that is representative of the realm it is operating on, should the factory `create` be given another kind of object? 

Regarding whether or not it is a regression, my test was to log in to an existing user with a wrong password 2+ times with `23.0.7` and `24.0.1`. With `23.0.7` the `session.getContext().getRealm()` was not null when the event was emitted. I just tried it again to verify, and it's the same.

**Comment by douglaspalmer** [comment]
@xgp what exactly are you testing with 23.0.7? Do you have permanent lockout enabled or temporary lockout?

**Comment by douglaspalmer** [comment]
@xgp I just stepped through 23.0.7 with a debugger. session.getContext().getRealm() on the Permanent Lockout event is null. I also looked more at other EventListenerProvider implementations. Why are you trying to deal with the realm so early in the process? Realm is usually handled during onEvent().

**Comment by xgp** [comment]
@douglaspalmer Thanks for all the work on this.

FWIW, I the `EventListenerProvider` I create in the `create()` method is loaded, configured and customized based on the Realm provided in the context.

However, it sounds like it is more important to convince me that I'm doing something wrong by assuming the session context should be properly hydrated with the realm than actually providing a consistent behavior. I'll close this and find a workaround.
