### ISSUE TITLE
Public OpenPGP key missing to verify download .asc file.

### ISSUE THREAD

**Issue by bernhardreiter** [keycloak/keycloak#27773]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Release assets have OpenPGP signatures in `.asc`. To verify this a public OpenPGP key is needed. Where can it be found?

 https://github.com/keycloak/keycloak/releases/tag/24.0.1
has 

```
 LANG=C gpg --verify keycloak-24.0.1.tar.gz.asc
gpg: assuming signed data in 'keycloak-24.0.1.tar.gz'
gpg: Signature made Tue Mar  5 08:21:46 2024 UTC
gpg:                using EDDSA key 861AB50E8CC6611FB6BC01A6B8F12EA26FD6EEBA
gpg: Can't check signature: No public key
```
https://groups.google.com/g/keycloak-user/c/mUnWFNwYm7c/m/s0cX9IFoBAAJ
 says this is the right fingerprint, but where does someone get the public OpenPGP key?
It cannot be found. 

Expected behaviour: 

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The documentation has a link to the pubkey, it is also uploaded to the new OpenPGP keyserver network (https://spider.pgpkeys.eu/).

### Actual behavior

Search on the keyserver, documentation and github does not reveal the public key file to verify the signature.

### How to Reproduce?

Download an .asc file and try to verify it. Try to find the corresponding public OpenPGP key there or on a new keyserver.

### Anything else?

(This seems to be the best category to report this.)

**Comment by stianst** [comment]
At the moment the keys are only published to https://keyserver.ubuntu.com/

~question

**Comment by bernhardreiter** [comment]
@stianst thanks for the hint.

I've got the pubkey with 
```
gpg --keyserver keyserver.ubuntu.com --recv-keys 861AB50E8CC6611FB6BC01A6B8F12EA26FD6EEBA
```
and send it to the one of the replicating keyserver.

>  but this looks like a request for help and not a bug.

The defect is that the documentation is missing the information where the pubkey will be published to. The hint that you can get the pubkey from https://keyserver.ubuntu.com/pks/lookup?search=861AB50E8CC6611FB6BC01A6B8F12EA26FD6EEBA&fingerprint=on&op=index is needed.

**Comment by tobast** [comment]
Hello,

Sorry for digging up this topic, but I back @bernhardreiter on this point -- while trying to verify the GPG signature for the release, I could find no trace anywhere of this public key. A GPG signature is only meaningful if I can trust that the corresponding key is owned by the maintainers, and it is not really the case here.

Would you maybe consider publishing your signing GPG public key somewhere on your website (ideally on the download page)?

Thank you!

**Comment by srhoulam** [comment]
Hi,

Also sorry to resurrect this topic, but the difficulty in finding the signing key is the reason I'm here as well. The fact that this GH issue has become the de facto resource on this topic might be evidence that this is a genuine problem.

Thank you,
SR
