### ISSUE TITLE
Keycloak v23 does not support keycloak.v2/account theme extension

### ISSUE THREAD

**Issue by Luka-Krsmanovic** [keycloak/keycloak#27771]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Our team upgraded **from v18 to v23**.

We were using **custom account themes** for editing user profile data and for changing a password. Those themes were built as _.ftl_ files. You can see the structure of our extended theme in the image below.

<img width="1303" alt="Screenshot 2024-03-11 at 14 40 51" src="https://github.com/keycloak/keycloak/assets/163004286/a4cec041-998f-4854-8619-6db9bc343f86">

These themes are not working with the v23: When visiting `${config.KC_AUTH_URL}/realms/${config.KC_AUTH_REALM}/account/` we are getting **500 Internal Server Error**.

From what we read in the various threads, account console v1 has been deprecated, and we have to start using React-based themes. Now, we are facing an issue similar to [26329](https://github.com/keycloak/keycloak/discussions/26329)

Based on the keycloak-man example for the v23, here is the structure of our custom theme:

<img width="1284" alt="Screenshot 2024-03-11 at 14 54 45" src="https://github.com/keycloak/keycloak/assets/163004286/7dcf09b2-44e9-48e4-9e60-91ebe2a1dec0">

In the theme.properties, we are setting `parent=keycloak.v2`.
Both AccountPage.js and PasswordPage.js files export a class that extends the React component.
`import * as React from "../../../../common/keycloak/web_modules/react.js";`
`export class AccountPage extends React.Component { ... }`

Now, when accessing a `${config.KC_AUTH_URL}/realms/${config.KC_AUTH_REALM}/account/` we are getting **404 Not Found Error**. **The react.js file cannot be found**. A default loading spinner is displayed.

Similar to [19508](https://github.com/keycloak/keycloak/discussions/19508), we also tried to copy the content of keycloak.v2/account from the keycloak repo **inside our custom-theme folder** and to adjust what we have to. That approach also failed.

Can you please tell us if is it possible to customize keycloak.v2/account console in the keycloak v23? If so, can you please provide us with an example or docs on how to achieve that? From what we can see, you are suggesting using account console v3, but in an ideal world, we would prefer to stick to the keycloak.v2/account.

Thanks in advance.

### Version

23

### Regression

- [X] The issue is a regression

### Expected behavior

Custom keycloak.v2 account theme should be visible.

### Actual behavior

We are getting **404 Not Found Error**. **The react.js file cannot be found**.

### How to Reproduce?

Please see the 'Describe the bug' section.

**Comment by jonkoops** [comment]
> but in an ideal world, we would prefer to stick to the keycloak.v2/account.

We will not be supporting this, and Account v2 has been deprecated in Keycloak 23, and will be removed in version 25 of Keycloak. You can however copy the source code for Account v2 from the Keycloak repository and use that as your own custom theme if you like.

If you want to customize the Account v3 theme (which was stabilized in Keycloak 24) you can follow the [upgrade guide](https://www.keycloak.org/docs/24.0.1/upgrading/#changes-to-the-account-console-theme-customization), or check out [the updated quick-start](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/extend-account-console).

Some other Keycloak users have been having success with [Keycloakify](https://www.keycloakify.dev/) to customize their themes, so that might be something to check out as well.

**Comment by KhalilDiasDev** [comment]
@jonkoops where can i get the v2 account source code and use it as a default thema, just like login or admin , currently i have a keycloak v2 file but the thema applied to the account keeps loading endlessly returning a 404

![Image](https://github.com/user-attachments/assets/c02a4de5-1fe6-4f68-873b-3bc2022bd666)
