### ISSUE TITLE
Liquibase Migration for v13 failing in v24.0.1 

### ISSUE THREAD

**Issue by kschroeder-of** [keycloak/keycloak#27794]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

As far as I can tell I am reporting an issue that was resolved before but seems to be back.
The past tickets are: [#23220](https://github.com/keycloak/keycloak/issues/23220) and [#9886](https://github.com/keycloak/keycloak/issues/9886).
It seems to be caused by a specific liquibase changeset: `jpa-changelog-13.0.0.xml::default-roles` 

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Successful migration for all change sets.

### Actual behavior

```
keycloak-test  | 2024-03-11 10:38:18,085 DEBUG [io.quarkus.runtime.Application] (main) Stopping application
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak:
keycloak-test  |      Reason: liquibase.exception.DatabaseException: Duplicate entry 'default-roles-test-portal-test-Portal' for key 'KEYCLOAK_ROLE.UK_J3RWUVD56ONTGSUHOGM184WW2-2' [Failed SQL: (1062) INSERT INTO keycloak.KEYCLOAK_ROLE (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, `DESCRIPTION`, NAME, REALM_ID, REALM) VALUES ('9f628d00-18a2-435c-bf41-eef9042112c7', 'test-Portal', 0, '${role_default-roles-test-portal}', 'default-roles-test-portal', 'test-Portal', 'test-Portal')]
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak:
keycloak-test  |      Reason: liquibase.exception.DatabaseException: Duplicate entry 'default-roles-test-portal-test-Portal' for key 'KEYCLOAK_ROLE.UK_J3RWUVD56ONTGSUHOGM184WW2-2' [Failed SQL: (1062) INSERT INTO keycloak.KEYCLOAK_ROLE (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, `DESCRIPTION`, NAME, REALM_ID, REALM) VALUES ('9f628d00-18a2-435c-bf41-eef9042112c7', 'test-Portal', 0, '${role_default-roles-test-portal}', 'default-roles-test-portal', 'test-Portal', 'test-Portal')]
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak:
keycloak-test  |      Reason: liquibase.exception.DatabaseException: Duplicate entry 'default-roles-test-portal-test-Portal' for key 'KEYCLOAK_ROLE.UK_J3RWUVD56ONTGSUHOGM184WW2-2' [Failed SQL: (1062) INSERT INTO keycloak.KEYCLOAK_ROLE (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, `DESCRIPTION`, NAME, REALM_ID, REALM) VALUES ('9f628d00-18a2-435c-bf41-eef9042112c7', 'test-Portal', 0, '${role_default-roles-test-portal}', 'default-roles-test-portal', 'test-Portal', 'test-Portal')]
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Duplicate entry 'default-roles-test-portal-test-Portal' for key 'KEYCLOAK_ROLE.UK_J3RWUVD56ONTGSUHOGM184WW2-2' [Failed SQL: (1062) INSERT INTO keycloak.KEYCLOAK_ROLE (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, `DESCRIPTION`, NAME, REALM_ID, REALM) VALUES ('9f628d00-18a2-435c-bf41-eef9042112c7', 'test-Portal', 0, '${role_default-roles-test-portal}', 'default-roles-test-portal', 'test-Portal', 'test-Portal')]
keycloak-test  | 2024-03-11 10:38:18,085 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Duplicate entry 'default-roles-test-portal-test-Portal' for key 'KEYCLOAK_ROLE.UK_J3RWUVD56ONTGSUHOGM184WW2-2'
```

### How to Reproduce?

1. Setup a Keycloak instance with a given DB (persisted DB of course) without the given changeset applied (any version before 13)
3. Stop the Keycloak server
4. Start a new instance with v24.0.1 and connect it to the same DB

**Comment by anthony-harris** [comment]
Experienced the same and I get this is not the way to handle it but I replaced org.liquibase.liquibase-core-4.25.1.jar with 4.26.0, renamed it to match org.liquibase.liquibase-core-4.25.1.jar and the issue went away

**Comment by mcg1969** [comment]
> Experienced the same and I get this is not the way to handle it but I replaced org.liquibase.liquibase-core-4.25.1.jar with 4.26.0, renamed it to match org.liquibase.liquibase-core-4.25.1.jar and the issue went away

I can confirm this resolved the issue for me as well.

**Comment by pedroigor** [comment]
Glad to see that the workaround is working to migrate from an old and unsupported release. This issue should not be fixed by us as you are not going to experience the same once you migrate to the latest versions.

Fixing this would force us to introduce a fix for migrating for old versions and we don't want to do this now.

**Comment by mcg1969** [comment]
I understand the need to triage, but given that the workaround is simply to update the liquibase jar, I'm a bit disappointed in this outcome. Successful migration is essential for encouraging people to stay up to date. I would encourage you to reconsider, and schedule an update to liquibase.

**Comment by pedroigor** [comment]
I understand that but it is really hard for us to support migrating from such old releases. I can re-open this issue and mark it as a `low` priority so that others can give a thumbs up and force the issue to be prioritized.

But still, it will eventually expire and be closed if we don't have enough interest from the community.

**Comment by mcg1969** [comment]
Hmm, I was migrating from KC 22; I don't think that ought to be considered "really old".

**Comment by mcg1969** [comment]
Honestly I understand your position better now! But let me be on record saying that I experienced the same issue migrating from 22.0.x to 24.0.x, and the same workaround solved it for me too.

**Comment by pedroigor** [comment]
@mcg1969 Are you getting the same exception when migrating from 22?

**Comment by mcg1969** [comment]
It was a liquibase migration error, yes.

We have downgraded to 23.0.7 in production for now due to an unrelated issue, but I should be able to reproduce it in test.

**Comment by mcg1969** [comment]
Give me a couple of hours to spin up a new test instance and I'll get you a reproduction.

**Comment by mcg1969** [comment]
Sorry @pedroigor I got pulled away on another QA issue but I _will_ do this

**Comment by mcg1969** [comment]
@pedroigor OK, I'm afraid I must apologize for a false alarm. I reviewed the reproduction logs, and determined that indeed it _was_ a case where the migration was from a much older version of Keycloak. It was _not_ a migration from 22. I'm grateful for your willingness to work with me here but I do not think there is a near-version Keycloak migration.

**Comment by amir4895** [comment]
@pedroigor I get the same result when upgrading from 18 to 25. it's seems to me the migration shouldn't be broken like that in such versions...it not that i'm upgrading from version 5 or something very old

**Comment by minusdavid** [comment]
I'm seeing this one pop up for a 4.8.3->24.0.5 migration.

With the same DB I can do 4.8.3->16.1.1->17.0.1->26.2.5 without this DB migration issue. (Can't use 26.2.5 due to issue 40171 so going to try to get to the latest version I can.)

I'll re-try 4.8.3 to 24.0.5 using the 16.1.1 and 17.0.1 steps.

**Comment by minusdavid** [comment]
Note that migrating 4.8.3->16.1.1->17.0.1->24.0.5 succeeded.

The build step for 24.0.5 throws some warnings but things seem to be working...
