### ISSUE TITLE
Unable to enable trace while the keycloak server is running 

### ISSUE THREAD

**Issue by psathyavathy** [keycloak/keycloak#27819]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I'm trying to update the log level when server is running, but unable to find a way to do that.

### Version

23.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

log level should be able to be changed at runtime.

### Actual behavior

docker compose file configured as below for default logging,
- KC_LOG=file,console
- KC_LOG_LEVEL=INFO

This is only way we can change the log level at deployment time.

### How to Reproduce?

we could not find a way to change a log level at runtime.

**Comment by shawkins** [comment]
Opened as a discussion initially: https://github.com/keycloak/keycloak/discussions/27693

The short answer is that there's nothing built-in to do this currently.

**Comment by shawkins** [comment]
reopened as an enhancement #27903
