### ISSUE TITLE
ExternalLinksTest `.../keycloak-DEV.zip` (invalid status code 404)

### ISSUE THREAD

**Issue by tkyjovsk** [keycloak/keycloak#27818]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Unreachable external link `https://github.com/keycloak/keycloak/releases/download/DEV/keycloak-DEV.zip`

- failed test in main https://github.com/keycloak/keycloak/actions/runs/8241482953
- failed test in release/24.0 https://github.com/keycloak/keycloak/actions/runs/8236464712

Probably introduced by: https://github.com/keycloak/keycloak/commit/269e9616ff29f24b40851a59822b9d9d4135a4be

### Version

999.0.0-SNAPSHOT

### Regression

- [X] The issue is a regression

### Expected behavior

`org.keycloak.documentation.test.ExternalLinksTest` passing

### Actual behavior

```
[INFO] Running org.keycloak.documentation.test.ExternalLinksTest
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 96.749 s <<< FAILURE! - in org.keycloak.documentation.test.ExternalLinksTest
Error:  checkExternalLinks{String}[6]  Time elapsed: 7.526 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Broken links (1) in guide 'upgrading': 
		- https://github.com/keycloak/keycloak/releases/download/DEV/keycloak-DEV.zip (invalid status code 404)
```

### How to Reproduce?

`org.keycloak.documentation.test.ExternalLinksTest`

**Comment by ahus1** [comment]
Already fixed by #27796
