### ISSUE TITLE
"Unmanaged Attributes"-Option on Realm can not be set with kcadm.sh

### ISSUE THREAD

**Issue by buehlera** [keycloak/keycloak#27823]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

With the update to keycloak 24.X we can no longer provide userattributes with our automated build.

I understand the concept of the unmanaged attributes, but please provide an option to" kcadm.sh" to set the desired option.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

kcadm.sh should be able to set  -s unmanagedAttributePolicy=ENABLED 

### Actual behavior

This option is giving an exception, since it can not be set.

### How to Reproduce?

Upgrade to 24.X and the user-attributes are not listed per default

**Comment by shawkins** [comment]
You can do this via:

```
./kcadm.sh update users/profile -r realm -s unmanagedAttributePolicy=ENABLED
```

@vmuzikar does this need specifically called out in the docs?

**Comment by PhilippKolmann** [comment]
Thanks @shawkins for this hint. Works like a charm.

If anyone needs to do this via API as I do:

- GET KEYCLOAK_SERVER + "/admin/realms/" + realm + "/users/profile"
- add "unmanagedAttributePolicy --> ENABLED" to the JSON
- PUT it to the same URL.

**Comment by shawkins** [comment]
Removed the triage label. We just need to decide if this warrents additional documentation.

**Comment by vmuzikar** [comment]
I think this is generic enough, not really needed to explicitly document it. It's not even relevant just to Admin CLI but rather to how the REST API behave, correct?

@shawkins Setting priority normal for now but feel free to change it.

~action/priority-normal

**Comment by shawkins** [comment]
> I think this is generic enough, not really needed to explicitly document it. It's not even relevant just to Admin CLI but rather to how the REST API behave, correct?

It was initially asked about in the context of kcadm.sh. It seems good enough for users to work backwards from https://www.keycloak.org/docs-api/24.0.1/rest-api/index.html to figure out the request for either the cli or the api.

**Comment by bienblue** [comment]
I have tried with API to enable unmanagedAttributePolicy
But I got the issue **UserProfile configuration without 'attributes' section is not allowed**
Could you please help?

**Comment by sschu** [comment]
@bienblue Just use the admin console to enable unmanaged attributes and use your browsers network tab to see how a valid request looks like.

**Comment by bienblue** [comment]
Dear @sschu ,
Thanks for your suggestion.
It seems while enable in admin console, the attributes was enabled by /admin/realms/{realmName} endpoint with upConfig.
But I would like to use the API endpoint /users/profile to enable only unmanagedAttributePolicy.

**Comment by sschu** [comment]
I see a request to `https://<host>/admin/realms/<realm>/users/profile` with the following content:
`{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {},
        "up-username-not-idn-homograph": {}
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "email",
      "displayName": "${email}",
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "firstName",
      "displayName": "${firstName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "annotations": {},
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "lastName",
      "displayName": "${lastName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "annotations": {},
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    }
  ],
  "groups": [],
  "unmanagedAttributePolicy": "ENABLED"
}`
And this is how you need to do it, you can probably leave out firstName and lastName and maybe email but the unmanaged attribute setting is part of the user profile configuration.

**Comment by bienblue** [comment]
Dear @sschu,
I have tried your approach and it works(GET the json content of current profile, then append the "unmanagedAttributePolicy": "ENABLED" to current profile with PUT request),
But, Is that possible to only define "unmanagedAttributePolicy": "ENABLED" in the body, just like simple ./kcadm.sh command above?
