### ISSUE TITLE
Can't register webauthn passwordless key when RS1 signature algorithm is configured in policies

### ISSUE THREAD

**Issue by bamandineDoca** [keycloak/keycloak#27824]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

While using the "RS1" signature algorithm in webauthn passwordless policies, I can't register a new webauthn Key. 

I received an error message in the browser console when loading the page : "Uncaught SyntaxError: Unexpected number". Additionally, when attempting to register the key, I received the following error message: "Uncaught ReferenceError: registerSecurityKey is not defined at HTMLInputElement.onclick (required-action?execution=webauthn-register-passwordless&client_id=...)".

Upon reviewing the HTML file loaded by "/login-actions/required-action?execution=webauthn-register-passwordless&client_id=...", I noticed an error on line "let signatureAlgorithms =[-36,-257,-7,-35,-258,-259,-65 535,]".

### Version

23.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

I can register a webauthn passwordless key when signature algorithm "RS1" is configured in webauthn passwordless policies

### Actual behavior

I can't register a webauth passwordless key when signature algorithm "RS1" is configured in webauthn passwordless policies

### How to Reproduce?

1. Add "RS1" in "signature algorithm" field in "webauthn passwordless policies" authentication configuration.
2. Add "Webauthn Register Passwordless" required action on a user
3. Connect with this user and try to add a new webauthn key

### Anything else?

I suspect the issue was introduced by the "https://github.com/keycloak/keycloak/commit/1af4a7a5325c248da2275759379ec00e495045df" commit.

**Comment by bamandineDoca** [comment]
In 24.0.2, I have no longer the  "Uncaught SyntaxError: Unexpected number" but I don't know how to test to register with a RS1 Webauthn device. Can someone valid it's ok now using a RS1 algorithm ?

**Comment by rmartinc** [comment]
Using main branch I think the number is printed in the ftl template using locale settings, for example in my case if I have ES256 (-7) and RS1 (-65535) I obtain:

```javascript
signatureAlgorithms : [-65,535,-7,],
```

when I think it should be:

```javascript
signatureAlgorithms : [-65535,-7,],
```

So we just need a little PR with the following (the number should be printed in c_format in the ftl):

```diff
diff --git a/themes/src/main/resources/theme/base/login/webauthn-register.ftl b/themes/src/main/resources/theme/base/login/webauthn-register.ftl
index 14ce7a87c9..48c958911a 100644
--- a/themes/src/main/resources/theme/base/login/webauthn-register.ftl
+++ b/themes/src/main/resources/theme/base/login/webauthn-register.ftl
@@ -29,7 +29,7 @@
                     challenge : '${challenge}',
                     userid : '${userid}',
                     username : '${username}',
-                    signatureAlgorithms : [<#list signatureAlgorithms as sigAlg>${sigAlg},</#list>],
+                    signatureAlgorithms : [<#list signatureAlgorithms as sigAlg>${sigAlg?c},</#list>],
                     rpEntityName : '${rpEntityName}',
                     rpId : '${rpId}',
                     attestationConveyancePreference : '${attestationConveyancePreference}',
```

But I'm in the same situation. I cannot test RS1. @bamandineDoca You can send that a PR with that little change if you want. I don't think we need a test for this. So that little diff is enough. I'll try to send the PR tomorrow if you don't want to do it.

**Comment by rmartinc** [comment]
For more info: https://freemarker.apache.org/docs/ref_builtins_number.html

**Comment by ahus1** [comment]
@rmartinc - I see this is marked for a KC24 backport, and I didn't see a PR backporting this. Could you please create one, or decide not to do it?

**Comment by rmartinc** [comment]
@ahus1 I just forgot it, done now in: https://github.com/keycloak/keycloak/pull/30238 (executing tests now).
