### ISSUE TITLE
Missing Attribute Information in Error Message

### ISSUE THREAD

**Issue by martinlolek** [keycloak/keycloak#27836]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

When creating a user in through the command line, with a mandatory 'phone' attribute set for the specified realm, the attribute must contain between 13 and 20 characters. Executing the following command:
kcadm.sh create users -r myrealm -s username=Someone -s email=someone@example.com -s enabled=true -s emailVerified=true -s attributes.firstName=Foo -s attributes.lastName=Bar -s attributes.phone='0123456789012'
Results in the following error:
error-invalid-length

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

for example: 
attributes.phone: error-invalid-length
attributes.phone: error-invalid-length (from 13 to 20)

### Actual behavior

The error message lacks information regarding which attribute triggered the error, making it challenging to identify the specific problem.

### How to Reproduce?

1. Set a validator for the user profile (e.g. from 13 to 20 characters long)
2. Run a command above which fulfills the attribute and at the same time does not fulfill its condition (e.g. 2 characters)

**Comment by shawkins** [comment]
The error message originates on the server side, so adding core-shared as well.

**Comment by pedroigor** [comment]
@martinlolek Is this the full response body? I thought we were returning the information we were looking for too because we have the same messages indicating the problematic field in UIs (e.g.: admin and account console).
