### ISSUE TITLE
Incorrect Length Validation for Attribute

### ISSUE THREAD

**Issue by martinlolek** [keycloak/keycloak#27839]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

The 'phone' attribute is configured to require arbitrary validation conditions, specifically a length between 13 and 20 characters  (regardless of trim-disabled). However, executing the provided command with a 13-character phone attribute :
kcadm.sh create users -r myrealm -s username=Someone -s email=someone@example.com -s enabled=true -s emailVerified=true -s attributes.firstName=Foo -s attributes.lastName=Bar -s attributes.phone='0123456789012'
Results in the error mentioned down. The condition should be satisfied with 13 characters, and the command should succeed.

If an extra character is added to the 'phone' attribute, making it 14 characters, the command passes successfully. This behavior contradicts the specified length requirement and suggests a counting error in the tool. Notably, through the admin UI, a 13-character text passes validation successfully.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

successful user creation: Created new user with id 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'
with output to stdout, not to stderror and maybe formated as JSON or GUID only. 

### Actual behavior

Results with the following error: 
error-invalid-length

### How to Reproduce?

1. Configure a realm with a mandatory 'phone' attribute requiring arbitrary validation conditions, specifically a length between 13 and 20 characters.
2. Execute the provided command with a 13-character 'phone' attribute.
3. (Optional Step) Execute the provided command with a 14-character 'phone' attribute.

**Comment by shawkins** [comment]
This is an error in the kcadm client. The logic for building up the content of the request makes an assumption that if a value looks numeric, then it can be put into the json as a numeric value. This causes the leading 0 to be dropped. The workaround of course it have any other content in the phone string that would cause to not look like a numeric value.

I don't think that the client should be making these kind of type assumptions without knowing the actual schema involved. I'll see if this can largely be removed.

**Comment by shawkins** [comment]
Actually the logic already contains handling for quoted values, which requires some nesting in this case to preserve them in the shell. @martinlolek try instead:

```
-s attributes.phone="'0123456789012'"
```

@vmuzikar this does not seem to be documented clearly in the admin-cli.adoc. Would you simply document that or is it worth persuing just sending everything as strings and letting the server do any type conversions - jackson is more than capable of doing that as long as we are allowing implicit conversions.

**Comment by shawkins** [comment]
Due to the possible corruption of data, marking as important.

~priority-important
