### ISSUE TITLE
Error when executing refresh grant, with scope param, without offline_access scope specified

### ISSUE THREAD

**Issue by patrickjennings** [keycloak/keycloak#27878]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When executing an OIDC refresh grant request to the token endpoint, providing a valid offline token, and specifying scope via the scope parameter but without the offline_access scope included, the refresh request fails with error.

### Version

24.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

Refresh request should succeed.

### Actual behavior

The following error is produced:
```json
{
    "error": "not_allowed",
    "error_description": "Offline tokens not allowed for the user or client"
}
```

### How to Reproduce?

1. Create a client with offline_access scope available:
* standard flow enabled
* full scope allowed should be toggled off
* offline_access scope set as optional

2. Execute standard auth flow, with offline_access scope provided.
3. Copy refresh (offline) token provided by token endpoint.
4. Execute refresh token request providing offline token and scope in the form data. The scope should not specify offline_access.
```bash
curl --location 'http://localhost:8080/realms/master/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'refresh_token={refresh_token}' \
--data-urlencode 'client_id=std-auth-client' \
--data-urlencode 'scope=openid'
```

Observe error is produced.

### Anything else?

Error thrown here:
* https://github.com/keycloak/keycloak/blob/1788cf2b092130adcc478e34f2d60f5447152369/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L1154

in isOfflineTokenAllowed, seems the offline_access role may not be available on the client session context here:
* https://github.com/keycloak/keycloak/blob/1788cf2b092130adcc478e34f2d60f5447152369/services/src/main/java/org/keycloak/services/managers/UserSessionManager.java#L131

**Comment by mposolda** [comment]
@patrickjennings Thanks for the investigation and nailing it down.

I am marking as a regression as I think that in previous version, using `scope` parameter in refresh-token request was ignored and hence the error was not thrown for the scenario you mentioned. But please correct me if I am wrong.

**Comment by patrickjennings** [comment]
That is a good point @sschu.

Is it then not correct logic currently where one can get an offline token by supplying offline_access scope without the client having the offline_access role mapped on the clients dedicated scope? It seems like that logic in Keycloak is not sound regarding the interaction of the role and scope but maybe I am missing something.

**Comment by sschu** [comment]
It agree, it is not completely sound. I think it is probably best if the scope assignment to the client does not play a role at all for offline access and it is solely controlled via the client scope offline_access.

**Comment by graziang** [comment]
In according with OAuth2 specification for the refresh access token request the requested scope must not include additional scopes that were not issued in the original access token. 
Typically scope parameter will not be included in the request, and if omitted, the service should issue an access token with the same scope as was previously issued.


So the new token should maintain at least the same scope, unless the requesting application explicitly asks for a reduced scope.

So if the scope claim is omitted we should grant all previous scopes.
if the scope claim is present but for instance without `offline_access` ideally the refresh token should be downgraded to traditional refresh token?
I know that this can be crazy to implement so i agree with just assuming that `offline_access` scope is present for the refresh request.

**Comment by graziang** [comment]
In according with OAuth2 specification for the refresh access token request the requested scope must not include additional scopes that were not issued in the original access token.
Typically scope parameter will not be included in the request, and if omitted, the service should issue an access token with the same scope as was previously issued.

So the new token should maintain at least the same scope, unless the requesting application explicitly asks for a reduced scope.

So if the scope claim is omitted we should grant all previous scopes.
if the scope claim is present but for instance without `offline_access` ideally the refresh token should be downgraded to traditional refresh token?
I know that this can be crazy to implement so i agree with just assuming that `offline_access` scope is present for the refresh request.

**Comment by mposolda** [comment]
@graziang Yes, it would be crazy to implement.

But moreover, the specification also mentions that `scope` parameter sent to refresh-token endpoint should not affect `scope` of the refresh-token itself. So it is supposed to affect only `scope` of other tokens like access-token or ID token per my understanding. The refresh-token (and hence the session) should still have the original scope.

That is per https://datatracker.ietf.org/doc/html/rfc6749#section-6 and the section:
```
If a new refresh token is issued, the refresh token scope MUST be identical to that of the refresh token included by the client in the request.
```

**Comment by cgeorgilakis** [comment]
Although the error was existing, the solution with accepted PR was bad and against  [Section 6 in OAuth2 RFC](https://www.ietf.org/rfc/rfc6749.txt).
I have created [a bug issue](https://github.com/keycloak/keycloak/issues/28463) and [a PR](https://github.com/keycloak/keycloak/pull/28503) that solves this issue based on  [Section 6 in OAuth2 RFC](https://www.ietf.org/rfc/rfc6749.txt). 
@mposolda could you review it?
