### ISSUE TITLE
SAML IssueInstant not honoring provided timezone

### ISSUE THREAD

**Issue by nicolabeghin** [keycloak/keycloak#27898]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

When starting a Keycloak server with provided timezone

    TZ=Europe/Rome

or even when building a customized Docker image with

    FROM keycloak:24.0.1
    USER root
    COPY --from=ubi-micro-build /usr/share/zoneinfo/Europe/Rome /etc/localtime

such timezone is not honored and GMT is always used.

This is because when generating the SAML `issueInstant`

https://github.com/keycloak/keycloak/blob/be29be67412eec27576392fff2ece2a29c165e6f/saml-core/src/main/java/org/keycloak/saml/SAML2AuthnRequestBuilder.java#L65

`XMLTimeUtil.getIssueInstant()` relies on `getCurrentTimeZoneID()`

https://github.com/keycloak/keycloak/blob/be29be67412eec27576392fff2ece2a29c165e6f/saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/XMLTimeUtil.java#L114

that in turns refers to environment variable `GeneralConstants.TIMEZONE`

https://github.com/keycloak/keycloak/blob/be29be67412eec27576392fff2ece2a29c165e6f/saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/XMLTimeUtil.java#L118

https://github.com/keycloak/keycloak/blob/be29be67412eec27576392fff2ece2a29c165e6f/saml-core-api/src/main/java/org/keycloak/saml/common/constants/GeneralConstants.java#L112

This doesn't seem to be documented anywhere, but it means that starting the container with

      - JAVA_OPTS_APPEND=-Dpicketlink.timezone=Europe/Rome

makes the server honor the required timezone.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Honor the provided timezone so that SAML IssueInstant are generated with given timezone  or update documentation with references to `picketlink.timezone`

### Actual behavior

Provided timezone `TZ` is not honored therefore SAML `IssueInstant` is generated with fallback `GMT` timezone

### How to Reproduce?

Start a keycloak server with a given timezone and see that it's using GMT in place of the provided one. As a counter-proof, start with 

      - JAVA_OPTS_APPEND=-Dpicketlink.timezone=Europe/Rome

to see it's actually picked up

**Comment by rmartinc** [comment]
@nicolabeghin I think that SAML specifies that issue instant should be in UTC form with no time zone component (check https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf section 1.3.3 - Time values). The initial code for keycloak came from picketlink and I suppose that the system property was added to allow override the spec. You can use `-Dpicketlink.timezone=TIMEZONE_DEFAULT` to use the default timezone in java too.

If you don't say something different I will close the issue as I think we are just following the standard here.

**Comment by rmartinc** [comment]
I'm closing this for the moment. As I commented the format is specified by the SAML standard (UTC form with no time zone), so modifying it is against the specification and not something recommended to do. The system property is just a way (inherited by picketlink) to override the specification, so I don't even think it should be documented. It is more a technical detail for someone that really knows what is doing, and this issue is a perfect place to have the information.

**Comment by nicolabeghin** [comment]
@rmartinc thanks for the detailed followup! I had some doubts about it but couldn't find a definitive answer scouring the internet, but the OASIS spec surely is one therefore sorry for the hiccup. Issue came from a custom SAML validator that's misbehaving and led me to believe the timezone could be the root cause while it isn't. Sorry again!
