### ISSUE TITLE
Keycloak 22.0.4 Version: UI access issue

### ISSUE THREAD

**Issue by Vishnu-Priya05** [keycloak/keycloak#27893]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have deployed Keycloak 22.0.4 version through helm deployment.
Tried browsing the Keycloak URL through the hostname, but getting 404 error.
But with the same hostname followed by /auth I'm able to browse the Keycloak URL.
Wanted to clarify whether is this the expected behavior or how does it works?

### Version

Chart version: 17.0.3  App version: 22.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

Need to browse the Keycloak URL with the mentioned hostname.

### Actual behavior

When trying to hit the keycloak URL with the hostname, getting 404 error.
But provided with /auth in the hostname, I'm able to access the URL.

Attaching  the deployed helm values file for your reference.

```USER-SUPPLIED VALUES:
auth:
  adminPassword: xxx
  adminUser: xxx
  managementPassword: xxx
  managementUser: xxx
externalDatabase:
  database: xxx
  host: xxx
  password: xxx
  user: xxx
extraEnv: "- name: JGROUPS_DISCOVERY_PROTOCOL\n  value: kubernetes.KUBE_PING\n- name:
  KUBERNETES_NAMESPACE\n  valueFrom:\n    fieldRef:\n      apiVersion: v1\n      fieldPath:
  metadata.namespace\n- name: CACHE_OWNERS_COUNT\n  value: \"2\"\n- name: CACHE_OWNERS_AUTH_SESSIONS_COUNT\n
  \ value: \"2\"            "
httpRelativePath: /auth/
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  extraTls:
  - hosts:
    - xxx-yyy-zzz.aaa.bbb.ccc
    secretName: xxx-yyy-zzz
  hostname: xxx-yyy-zzz.aaa.bbb.ccc
  rules:
  - host: xxx-yyy-zzz.aaa.bbb.ccc
    paths:
    - path: /
      pathType: ImplementationSpecific
  servicePort: http
postgresql:
  enabled: false
proxy: edge
proxyAddressForwarding: true
rbac:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
replicaCount: 3
service:
  type: ClusterIP
serviceAccount:
  automountServiceAccountToken: true
serviceDiscovery:
  enabled: true
```

### How to Reproduce?

Need to know what is the expected behavior in the deployed version.

**Comment by ssilvert** [comment]
I don't know anything about helm.  This doesn't sound like a UI issue so moving to core team.

It might help if you told us exactly what you are trying to do.  Are you trying to get to the welcome page where you set up the initial user?  Are you trying to get to the admin console?

**Comment by Vishnu-Priya05** [comment]
I have currently upgraded the Keycloak version to Chart Version: keycloak-17.0.3 App Version: 22.0.4

Upgradation was successful, and keycloak is deployed through helm.

While accessing the UI with the hostname, I'm getting 404 Not Found error. Attaching the screenshot below.

Whereas, while accessing the same URL with the hostname followed with /auth, I'm able to get the login screen. Attaching that screenshot as well.

**Comment by stianst** [comment]
In the linked config above you're using httpRelativePath: /auth/, which will expose KC on /auth and not the root. So, this is working as expected. Just remove that line from your config if you want it on /
