### ISSUE TITLE
Multi datasource configuration does not work in Keycloak 24.0.1

### ISSUE THREAD

**Issue by taka2021** [keycloak/keycloak#27894]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The following configation of quarkus.properties does not work:
```
quarkus.datasource.passport.db-kind=postgresql 
quarkus.datasource.passport.username=<someone>
quarkus.datasource.passport.password=<password>

quarkus.datasource.passport.jdbc.url=jdbc:postgresql://<DB HOST>/<DB_NAME>${env.JDBC_PARAMS:}
quarkus.datasource.passport.jdbc.max-size=16
```
 It was worked in keycloak-23.0.6.

### Version

24.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

Keycloak docker image coud be created successfully.

### Actual behavior

Failed with following errors:
```
#14 5.817 ERROR: Failed to run 'build' command.
#14 5.817 ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#14 5.817 	[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the datasource 'passport' (available: 'h2'). Check if it's a typo, otherwise provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource."passport".jdbc=false' to your configuration if you don't need it.
#14 5.817 	at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:371)
#14 5.817 	at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:345)
#14 5.817 	at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:102)
#14 5.817 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#14 5.817 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#14 5.817 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#14 5.817 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#14 5.817 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
#14 5.817 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
#14 5.817 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#14 5.817 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
#14 5.817 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
#14 5.817 	at java.base/java.lang.Thread.run(Thread.java:840)
#14 5.817 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

### How to Reproduce?

Docker compose: (conf/quarkus.propertis contains the multi datasource configuration)
```
FROM quay.io/keycloak/keycloak:24.0.1 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV PRINT_ENV=true

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
COPY conf/quarkus.propertis conf/
RUN /opt/keycloak/bin/kc.sh build --http-relative-path=auth
```

**Comment by shawkins** [comment]
@taka2021 what is your keycloak / unnamed datasource kind? Is it something other than postgresql? My guess is that newer logic in keycloak that removes unused datasource jars from the application classpath is removing postgresql.

cc @mabartos does the logic look usage of other named datasources, or is the user required to provide their own jar as a workaround?

**Comment by okamoto-ryo24** [comment]
@shawkins
I am from the same team as @taka2021 . I will answer instead. Our datasource kind is postgresql. Were there any change in the logic related to JDBC during the update from Keycloak 23.0.6 to 24.0.1?

**Comment by mabartos** [comment]
> Our datasource kind is postgresql

@okamoto-ryo24 @taka2021 Do you have explicitly set the `quarkus.datasource.db-kind=postgresql` (without specifying the datasource name)? Or set Keycloak env property `KC_DB=postgresql` during the build phase? 

As it seems the JAR for the PostgreSQL is ignored to classloaders as the default DB is set to H2, which is expected behavior. However, when the default datasource db-kind is set to PostgreSQL, the JAR should be present.
I'd see an issue when the db-kind is different for the default and named datasource.

We could make some improvements around it, but it shouldn't be the cause of this issue.

Out of curiosity:
Is the Dockerfile only an example of the behavior, or is it actually a copied set of steps? As I see, there's this line:
```
COPY conf/quarkus.propertis conf/
```
I'd rather recommend storing these config options in `application.properties` file, as it should be the supported default file for the custom Quarkus properties.

> Were there any change in the logic related to JDBC during the update from Keycloak 23.0.6 to 24.0.1?

I'm not aware of any major ones.

**Comment by taka2021** [comment]
I am sorry that the following configuration is only an example.

```
COPY conf/quarkus.propertis conf
```

It should be

```
COPY conf/quarkus.properties conf/
```

**Comment by shawkins** [comment]
> Is there any way to install additional quarkus extensions, while optimizing it with the build-step / using start-dev?

Unfortunately the built-in jars for anything other than the main keycloak / unnamed datasource will get ignored. This issue will need to be worked by updating the logic to scan for additional datasources in the config before performing the exclusions.

I think the workaround for now would be to include your own jdbc jar file for the affected datasources in the providers directory.
