### ISSUE TITLE
Webauthn token stops working on migration to 24

### ISSUE THREAD

**Issue by SpiderD555** [keycloak/keycloak#27890]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

Webauthn hardware tokens stop working after migration from 23 to 24.
I have been using webauthn tokens since around version 18 or 19, and now suddenly it stopped working after migration.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

I can login with webauthn token previously allocated to the account

### Actual behavior

I can't login with webauthn token previously allocated to the account
See attached error from web browser console
![keycloak_webauthn_error](https://github.com/keycloak/keycloak/assets/105607728/01c50feb-bf90-4710-a101-20d7ca5af326)

### How to Reproduce?

1. Install keycloak 23
2. setup authentication flow with webauthn passwordless step (that is right after username step)
3. Migrate to keycloak 24
4. Try to authenticate the user with the same webauthn token

### Anything else?

If I delete the said token and add it again in 24, then it starts to work again

**Comment by mposolda** [comment]
Thanks, preliminary marking as regression until we investigate this.

@SpiderD555 Could you please add the WebAuthn key you're using and the browser version you're using and also the OS (including version) you're using.

**Comment by SpiderD555** [comment]
@mposolda 
OS: Linux Mint 21.3 (latest)
Web browser: Vivaldi 6.6.3271.50 (Stable channel) stable (64-bit)
I have also tried with Firefox 123.0.1
Keys: 2x Solokey Somu, 1x Solokey 2

After re-adding a single key it all started to work again. I can send some files if needed to help with troubleshooting - I have a backup of the whole realm from 23 (in json)

**Comment by mposolda** [comment]
@SpiderD555 Thanks for the info. So just to doublecheck I understand the issue: 
- When user adds his security key in Keycloak 24 to his account, then everything works and user is able to authenticate with his WebAuthn key.
- But for the case when user had his WebAuthn security key configured already in Keycloak 23, then after migration to Keycloak 24, this user is not able to authenticate. Is it correct?

**Comment by SpiderD555** [comment]
@mposolda 
You got it correct.

I still could authenticate using a normal password when token didn't work, but WebAuthn keys are the preferred way for me.

**Comment by rmartinc** [comment]
I did a little test with the chrome virtual authenticator and I could register a key in 23, do the migration and login in 24. So possibly there is something more needed to reproduce this. I don't see anything in the migration that affects the webauthn either. I'm lowering to important as I think we need more time to guess what it's happening here.

@SpiderD555 When it's failing for you the error seems to point to the `webAuthnAuthenticate` JS method is not defined. That method is defined in the same webauthn page in a inline script. Do you see any other error in the page when the `Sign in with Passkey` page is displayed? Can you copy the full page from the web tools source and attach to the issue?

**Comment by jonkoops** [comment]
Let me know if some assistance is required with the JavaScript in this issue, I am not familiar with this code, but it is the area of expertise.

**Comment by SpiderD555** [comment]
I have reverted back to the backup from when I had 23.0.6 version, then upgraded to 24.0.1. Apparently I can't reproduce the issue anymore.

I am attaching the source code of the web page as rmartinc suggests to get and I do see some errors, however I am not sure that has any meaning as now I can't reproduce the error anymore.
[KC_webauthn.txt](https://github.com/keycloak/keycloak/files/14662949/KC_webauthn.txt)
![KC_webconsole](https://github.com/keycloak/keycloak/assets/105607728/6f04d69d-6847-42f1-9f39-0eda517057f5)

Anyway I do have yet another problem with slow loading times of some Keycloak pages (that I haven't got time to raise an issue for). This could be potentially related, so for example when I try to use webauthn and try to login then I still miss some files which are still loading (and have important JavaScript functions inside). Anyway feel free to close the issue, since I can't reproduce it.

**Comment by rmartinc** [comment]
@SpiderD555 The page you attach is the login page with the password input, not the webauthn login page with the `Sign in with Passkey` button.

But anyway, if you upgraded again and it's working now we don't have clear reproducer steps. I tried to reproduce with chrome and virtual env and @pedroigor with real dongles in chrome and firefox, and upgrade to 24.1 worked for both. We will maintain the issue a bit more time but if nobody else complains the issue will be closed as not reproducible.

**Comment by rmartinc** [comment]
I'm closing this for the moment. We have no more issues about webauthn not working after the upgrade. The related issue #28113 was more about registration and it was triggered by the changes in the trust-store done in 24. Just re-open the issue or file a new one if clear reproducer steps are found to make webauthn fail after the upgrade.
