### ISSUE TITLE
User search field loses focus after first input in realms with user federation

### ISSUE THREAD

**Issue by Foobartender** [keycloak/keycloak#27917]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In realms with user federation (LDAP in my case), the user view doesn't immediately list users, but displays the following message instead: "This realm may have a federated provider. Viewing all users may cause the system to slow down,..."

As soon as the user search field is not empty, the message changes to "No search results" and the refresh button appears. This change causes the search field to lose focus, which is very annoying.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Search field should keep focus when beginning to type.

### Actual behavior

It loses focus.

### How to Reproduce?

1. Select a realm with user federation.
2. Go to the users view.
3. Click the search field.
4. Start typing.
5. Note that the search field has lost focus.

### Anything else?

I didn't try 24.0.0. Versions before are not affected.

**Comment by ssilvert** [comment]
Normally, a bug like this would get lowest priority.  But I agree that this is ugly and annoying enough that it warrants a slightly higher priority.  Thanks for reporting it.
