### ISSUE TITLE
Allow managing organizations and authenticate their members

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#27928]
### Description

This epic is about delivering the very basic capabilities that are required to:

- Manage organizations within a realm
- Manage organization members
- Issue tokens for a client acting on behalf of a user so that both ID and access tokens are referencing the organization metadata to which the user belongs to 

### Non-Goal

We are not delivering full organization support and all its capabilities. This is the scope for the first milestone.

### Discussion

NA

### Issues

- [x] #27930
- [x] #27934
- [x] #27993

### Motivation

Introduce the core functionalities that are needed to build the Organization feature.

**Comment by paultempleman** [comment]
@pedroigor is there a design document or discussion for this feature? It would be useful to understand the roadmap for some of the OID4VCI design work. Specifically what other keycloak objects do you envisage linking to an organization.

**Comment by pedroigor** [comment]
@paultempleman The discussion we had that started this initiative is https://github.com/keycloak/keycloak/discussions/23948#discussioncomment-8479924.

At this point,  are expecting a organization to link with:

* Groups
* Identity Provider
* Client
* Authentication Policies (TBD)
* Roles

One of the reasons why we are introducing a specific domain model (the OrganizationModel) is to allow linking more objects as the requirements change.
