### ISSUE TITLE
Entry 999.0.0 in MIGRATION_MODEL prevents future migrations of the database

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#27941]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When the table `MIGRATION_MODEL` contains an entry `999.0.0`, this prevents any future schema changes to the database.

See https://github.com/keycloak/keycloak/issues/23980#issuecomment-1999671099

As the Keycloak Operator 24.0.0 was released with an error that installed the nightly release of Keycloak, this might now happen to other people as well.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak startup should fail if an entry `999.0.0` exists in the migration model, and the current version is a release version, as something is very wrong when this happens.

### Actual behavior

Keycloak starts, but will never run a migration.

### How to Reproduce?

* Start an (old) Keycloak nightly
* Start a released version of Keycloak with a later date -> no migrations will run

### Anything else?

The remedy to such an entry might be tricky: Deleting the `999.0.0` entry might work, but it might actually be better to change it to the latest released version of Keycloak for that nightly build, as some migrations will have been run. 

It would also be an idea to create one entry for each migration run, not only the latest migration run, so it would make a repair simpler, where one would need to delete only the `999.0.0` entry.

**Comment by stianst** [comment]
This is expected behaviour. We do not and can not support migration in main branch / nightly release.

For 24 this is not an issue as we only had this problem for a few hours after the release and included steps to work around it for those if any affected.

The only thing we could do here is throw an error if this happens. I.e. if dB is set to 999 and someone tries to run an actual release we would just throw an exception.

**Comment by mposolda** [comment]
+1 for throwing the error in case that `999` is in the DB and during startup is detected that some current release version is executed.

Actually, I think we can throw error always when `currentVersion < dbVersion` ? For instance when someone is trying to run Keycloak 23 with the DB, which was already migrated to Keycloak 24, strange things can happen as well. Hence would be nice to throw the error right away during startup.

**Comment by ahus1** [comment]
@mposolda - while I agree with the first step, I think implementing the second would make it even harder than today for people to fall back onto a previous release if the new one shows problems. Therefore, in such a case I would rather log an error, message, but not prevent Keycloak from starting.

**Comment by mposolda** [comment]
@ahus1 Ok, let's address only `999` then. I think the description is pretty clear and states exactly this behaviour and looks that we're in agreement also with @rh-iatanaso about this behaviour.

Triaging this as "important" for now.

**Comment by rh-iatanaso** [comment]
> @ahus1 Ok, let's address only `999` then. I think the description of this issue is pretty clear and states exactly this behaviour and looks that we're in agreement also with @rh-iatanaso about this behaviour.
> 
> Triaging this as "important" for now.

This will allow us to have visibility if we have the issue .

**Comment by lauer** [comment]
Just as a note here, our Keycloak Operator (OpenShift) upgraded to Keycloak 25, and for some reason, our installation it had the 999 migration in the database. So I had to manual delete that from the migration model, to start our keycloak instance again. 

https://keycloak.discourse.group/t/keycloak-operator-25-0-0-upgrade-instance-fails-on-db-migration/26427/3

**Comment by ahus1** [comment]
@lauer - there has been a problem with the Keycloak Operator 24.0.0 for a short time that it installed the nightly image instead of a released image until the Operator 24.0.1 version was available - see #27500. If that has been the situation, it would have been ok to change the 999 version to `24.0.0` (but only in that case). I hope this will help others who encounter this.

**Comment by ahus1** [comment]
Once the 25.0.0 entry is there, there is no need to re-add the old one. It would have made sense only before you ran the upgrade to avoid running some 24.0.0 migrations twice. But it seems it worked without issues for you.
