### ISSUE TITLE
Account console upload to NPM public registry

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#27959]
### Description

We need to be able to release account console to the public NPM registry so that it can be used for composable UIs.

Also need to make sure there is adequate documentation and/or a quickstart.

**Comment by edewit** [comment]
shouldn't this issue be moved to https://github.com/keycloak-rel/keycloak-rel/

I have created https://github.com/keycloak-rel/keycloak-rel/pull/114 in attempt to address this, but I know to little from GHA to know if this is right

**Comment by ssilvert** [comment]
> shouldn't this issue be moved to https://github.com/keycloak-rel/keycloak-rel/
> 
> I have created [keycloak-rel/keycloak-rel#114](https://github.com/keycloak-rel/keycloak-rel/pull/114) in attempt to address this, but I know to little from GHA to know if this is right

Not sure if we need an issue in `keycloak-rel` repo for the PR.  I think this issue can stay where it is because it is a task issue and it also includes docs and/or a quickstart.

**Comment by ssilvert** [comment]
@edewit We can close this issue when kc-create-app is done.
