### ISSUE TITLE
Hibernate Dialect detection does not work anymore for Oracle DBs

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak#27954]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Dialect detection for Oracle databases does not work anymore. When no dialect is explicitly configured, it's now defaulting to the (now) non-existent [`org.hibernate.dialect.Oracle12cDialect`](https://github.com/keycloak/keycloak/blob/28afd77917612ffed8090902315eaa6485455645/model/jpa/src/main/java/org/keycloak/connections/jpa/DefaultJpaConnectionProviderFactory.java#L323) dialect.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

When no dialect is configured, the Hibernate dialect selection should be used.

### Actual behavior

An Exception is thrown because `org.hibernate.dialect.Oracle12cDialect` is unknown to the used Hibernate version.

### How to Reproduce?

Configure a Oracle database without specifying a dialect.

**Comment by ahus1** [comment]
@shawkins - as you marked this issue for backporting, can I assume that you'll create the backport?

**Comment by shawkins** [comment]
@ahus1 yes, I'll handle that.

**Comment by shawkins** [comment]
@ahus1 https://github.com/keycloak/keycloak/pull/28147
