### ISSUE TITLE
Groups help message is only "Groups"

### ISSUE THREAD

**Issue by kouki-miura2** [keycloak/keycloak#27965]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In "Create user" page, Groups help message is only "Groups".

![image](https://github.com/keycloak/keycloak/assets/156555495/4f79dbbc-d547-4fa2-8fe4-3f47be40a7d0)

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Display "groupsHelp" of messages_en.properties.

### Actual behavior

Display "groups" of messages_en.properties.

### How to Reproduce?

1. Login admin console
2. Click Users menu
3. Click Add user button
4. Click Groups's help icon

**Comment by jonkoops** [comment]
@kouki-miura2 thanks for reporting this issue. Would you possibly be interested in opening a PR to fix the problem as well?

**Comment by kouki-miura2** [comment]
@jonkoops Yes, I would be happy to open a pull request to address the issue. I will work on a solution as soon as possible.
