### ISSUE TITLE
🍺 instead of dot: Attributes in account UI are not loaded

### ISSUE THREAD

**Issue by KarlKeu00** [keycloak/keycloak#27966]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

I have put my attributes into logical structures with a dot, but no created or predefined attributes are displayed in the account UI. The HTML source code of the fields looks like this:
```<input id="contact.mobile" data-testid="contact.mobile" name="attributes.contact🍺mobile" class="pf-c-form-control" type="text" aria-invalid="false" readonly="" data-ouia-component-type="PF4/TextInput" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-TextInputBase-6" value="">```
Even though I find this very amusing (maybe it's also because I selected German as my language), it prevents me from using this great new feature.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

All values/attributes are loaded correctly

### Actual behavior

As soon as an attribute has a dot in its name, the content is only displayed in the admin area.

### How to Reproduce?

1. Realm settings > User profile: Create attribute with dot in name.
2. Set the value for a user on the admin page.
3. Go to the account UI of this user.

**Comment by KarlKeu00** [comment]
This error also occurs if the languages have been deactivated or set to English for a user.

**Comment by KarlKeu00** [comment]
I think it has something to do with this: https://github.com/keycloak/keycloak/blob/28afd77917612ffed8090902315eaa6485455645/js/libs/ui-shared/src/user-profile/utils.ts#L46-L53
Maybe it's not even the beer. In the code it looks like this is an intentional separator, but in any case the value is not loaded correctly.

**Comment by jonkoops** [comment]
@KarlKeu00 if you need a dev environment I'd recommend reading the [readme of the Admin Console](https://github.com/keycloak/keycloak/tree/main/js/apps/admin-ui#readme), it should help you get started.

The reason we have this rather unfortunate beerification code is that the forms library we use will automatically use `.` notations as object accessors. We haven't found a good way to disable that behaviour, hence all dots in a key are replaced with a character that is unlikely to be used.

**Comment by KarlKeu00** [comment]
Thanks, i'll have a look into this next week.
However, there is a restriction on which characters can be used for attributes anyway (only letters, numbers and '.' '_' '-' special characters allowed). How about an exclamation mark or hashtag? The library would then perhaps be able to handle this a little better.

**Comment by KarlKeu00** [comment]
A quick question of interest: Why is this bug, which appeared with the introduction of KC 24, scheduled for release in KC 25? According to the milestone, a fix will not be released before June.

**Comment by jonkoops** [comment]
@KarlKeu00 you'll see that this issue has a the https://github.com/keycloak/keycloak/labels/backport%2F24.0 label, which means that it's slated to be backported for 24.
