### ISSUE TITLE
Custom ExceptionMapper for custom API endpoint resources

### ISSUE THREAD

**Issue by hlavki** [keycloak/keycloak#27988]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

In version 22.x and earlier we used `jakarta.ws.rs.ext.ExceptionMapper` to define mapper for our custom API endpoint resources. After migration to version 24.x our exception mappers stopped working. According to [quarkus documentation](https://quarkus.io/guides/resteasy-reactive-migration#jakarta-rest-providers) this should work. Keycloak uses their own ExceptionMapper implementations but there is [additional step](https://github.com/keycloak/keycloak/blob/d61b1ddb09c5d1396633504c7dbb0ccdc91b3f8a/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L109)  to register.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

When custom exception is thrown, our ExceptionMapper will handle it and return proper response.

### Actual behavior

generic exception mapper handle all exceptions 

### How to Reproduce?

Write custom ExceptionMapper on custom exception and then throw it

**Comment by shawkins** [comment]
@hlavki more than likely this is resolved by #25038
