### ISSUE TITLE
Username LDAP attribute other than uid is difficult

### ISSUE THREAD

**Issue by Cistoge** [keycloak/keycloak#27984]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I am trying to  create a new User Federation LDAP provider, using firstname.lastname as the user login scheme. So, on my OpenLDAP server, I tried several usually empty LDAP fields where to enter firtsname.lastname for my test user, for example title, employeeNumber, and postOfficeBox. But none of these works as Username LDAP attribute in Keycloak and syncing users fails. The log shows:

ERROR [org.keycloak.storage.ldap.LDAPStorageProviderFactory] (executor-thread-95) Failed during import user from LDAP: org.keycloak.models.ModelException: User returned from LDAP has null username! Check configuration of your LDAP mappings.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak syncs users according to the newly set Username LDAP attribute

### Actual behavior

An error message is shown which says that no user could be imported

### How to Reproduce?

On the OpenLDAP server, set firstname.lastname as employeeNumber, title and postOfficeBox for some test user. Set one of these as User LDAP attribute in Keycloak and then sync all users.

**Comment by sguilhen** [comment]
I've tried to reproduce the problem with OpenLDAP, and setting `cn` to the username attribute worked fine - users were updated and synch succeeded. I've tried even to use `uid` first, import the users, then switch it to `cn` and re-synch. All worked fine.

**Comment by Cistoge** [comment]
Hm, maybe I made mistake on monday and forgot to save my settings after changing from Username LDAP attribute uidNumber to cn, for now it works with cn also for me. But other fields like uidNumber or employeeNumber definitely do not work for me.

**Comment by sguilhen** [comment]
In my setup, I was able to use other attributes as well, such as `employeeNumber`, and import worked fine. If one of the users doesn't have this attribute, it will skip the user during import - in the logs you can see the same message you've posted about the username being `null` (admin console says 1 user failed during synch). So whatever attribute is chosen as the username attribute, all entries in LDAP must have it set or Keycloak won't accept importing the user.

One thing I've noticed, though, is that while synch works and reports some users failed to be imported (those with `null` values retrieved from LDAP for the username), when searching for all users in the Users screen the whole thing fails if an user from LDAP has a `null` username, instead of skipping them. We might need to revisit the `searchForUserStream` in `LDAPStorageProvider` to keep the behavior consistent.

**Comment by Cistoge** [comment]
The OpenLDAP instance I am using for this is not for production use, but only for testing and currently has only one user.  This user has "testuser" as uid OpenLDAP attribute and "test.user" as postOfficeBox OpenLDAP attribute. In Keycloak, the user can be imported with uid as Username LDAP attribute, but not with postOfficeBox ...

**Comment by sguilhen** [comment]
I think I see what's going on. When I create a LDAP federation from scratch, I can set anything to the Username LDAP attribute, and synch users works as expected.

Now, if we go back to the already configured provider, and edit the Username LDAP attribute (for example, switch from uid to postOfficeBox), I start getting the same errors, even after removing all previously imported users. So here's what is happening:

1. When we first create an LDAP storage provider, the configured Username LDAP attribute (let's say uid), is used to create a `username` mapper that fetches the same attribute from LDAP when loading users, and sets it as the username in Keycloak.
2.  When we edit the Username LDAP attribute in the LDAP provider (let's say to `postOfficeBox`), the change **is not** propagated to the `username` mapper, which is still with the old `uid` value. Without any mappers configured to fetch the `postOfficeBox` attribute from LDAP, the value is read as `null` when importing, giving us the errors you've described.

If, after changing the Username LDAP attribute in the main LDAP config you also edit the `username` mapper to the same attribute, synchronizing users work again, and any previously imported user will be updated to the new username.

It would be good if the change was propagated to the correct mapper once the LDAP config changes, but for now this is a workaround you can use.
