### ISSUE TITLE
User Profile: Inconsistent ordering of attributes between account and login themes

### ISSUE THREAD

**Issue by ReneZeidler** [keycloak/keycloak#27981]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

The order of attributes is inconsistend between the account console and login theme (registration page, verify user profile, etc.).

1. Specifically, the account console puts all attributes without a group first and groups them in a section labelled "General".  
The login theme puts all attributes without a group last, visually appearing as part of the last named group.
2. ~~Additionally, attribute groups are sorted by (the translation key of the) display name in the login theme, and are unsorted in the account console (using the order they are returned by the API, which seems to match creation order of the groups).~~  
_Split into separate issue #27994_

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Ordering of attributes should be the same in the account console and login theme forms.

### Actual behavior

<details><summary>1. Attributes without a group</summary>
<p>

User profile configuration:
![image](https://github.com/keycloak/keycloak/assets/5558742/7c0bc0db-f5a3-4747-822f-5eae95e28072)

Account console:  
![image](https://github.com/keycloak/keycloak/assets/5558742/c26994ff-af7d-41a5-9caf-62382448a1f6)

Registration page:  
![image](https://github.com/keycloak/keycloak/assets/5558742/a36b1cad-884c-450c-be52-7b6b07d83601)
</p>
</details> 

<details><summary>2. Manually created "General" group</summary>
<p>

Attribute groups configuration:
![image](https://github.com/keycloak/keycloak/assets/5558742/5cb60dd3-a033-4609-9a36-0972a728ba32)

Account console:  
![image](https://github.com/keycloak/keycloak/assets/5558742/b9b5b5b2-85eb-4d4f-9eb2-e21c41d0fb54)

Registration page:  
![image](https://github.com/keycloak/keycloak/assets/5558742/e4a0ed56-722e-411a-a301-247413aa0282)
</p>
</details> 

### How to Reproduce?

1. Create a new realm and a test account
2. Go to the user profile configuration
3. Add a custom attribute group, create at least one custom attribute and assign it to the new group. Leave the default attributes without a group.
4. Observe the order of the attributes on the registration page and the account console.
5. Create a second attribute group, use `${aaaGeneral}` or similar as the display name (so that it will be sorted first alphabetically). Assign all 4 default attributes to that group.
6. Observe the order of the attributes on the registration page and the account console again.

### Anything else?

**Regarding 1:**
In my opinion, the ordering in the account console makes more sense. General attributes without a group (including the 4 default attributes) are the most important ones and should appear first.

Additionally, I think it would make sense that attributes without a group appear first without a group header in the login theme. In the common case that no custom attributes are defined, it wouldn't make sense to add a "General" heading to the default attributes. And even with custom attributes in their own group, a heading for the common fields like name and email doesn't really add information. You can always add a heading by creating your own attribute group and assigning the default attributes to it.

Manually creating an attribute group for the default attributes seems like a workaround, but has its own issues:
* You run into different inconsitent ordering between groups (see 2).
* You're unable to display attributes without a heading in the login theme, which is the default behavior and commonly a wanted behavior.
* In the account console, the locale attribute will remain in the default "General" section separated from the custom "General" section.

**Regarding 2:**
Sorting attribute groups by the translation key is a bit unexpected, but at least consistent. You can enforce the ordering you want by strategically naming your translation keys. The best solution would be to add an explicit ordering to attribute groups, or use the already existing ordering of the attributes themselves to sort the groups, but that would be an additional feature request.

**Relevant code:**
Ordering in login theme: https://github.com/keycloak/keycloak/blob/28afd77917612ffed8090902315eaa6485455645/services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java#L33-L46

Ordering in account console: https://github.com/keycloak/keycloak/blob/d61b1ddb09c5d1396633504c7dbb0ccdc91b3f8a/js/libs/ui-shared/src/user-profile/UserProfileFields.tsx#L114-L118

**Comment by ReneZeidler** [comment]
As a workaround, I'm using a modified login theme that sorts the attributes in the freemarker template:
```diff
--- a/../../keycloak-src/themes/src/main/resources/theme/base/login/./user-profile-commons.ftl
+++ b/./user-profile-commons.ftl
@@ -1,7 +1,19 @@
 <#macro userProfileFormFields>
 	<#assign currentGroup="">
-	
+
+	<#--
+	[Workaround]: Sort attributes by group, putting attributes without a group first.
+	https://github.com/keycloak/keycloak/issues/27981
+	-->
+	<#assign sortedAttributes=[]>
 	<#list profile.attributes as attribute>
+		<#assign sortElement = { "order": attribute.group!"" + "###" + attribute?index, "attribute": attribute }>
+		<#assign sortedAttributes = sortedAttributes+[sortElement]>
+	</#list>
+
+	<#list sortedAttributes?sort_by("order") as sortElement>
+		<#assign attribute = sortElement.attribute>
+		<#-- [End Workaround] -->
 
 		<#assign group = (attribute.group)!"">
 		<#if group != currentGroup>
```

**Comment by jonkoops** [comment]
> In my opinion, the ordering in the account console makes more sense. General attributes without a group (including the 4 default attributes) are the most important ones and should appear first.

Agreed. Let's change the login so that these are the first to appear.

> Additionally, I think it would make sense that attributes without a group appear first without a group header in the login theme.

Yeah, agreed that makes sense.

>  In the common case that no custom attributes are defined, it wouldn't make sense to add a "General" heading to the default attributes. And even with custom attributes in their own group, a heading for the common fields like name and email doesn't really add information. You can always add a heading by creating your own attribute group and assigning the default attributes to it.

I also agree that the 'General' heading doesn't make sense, at least for the login. For the account and admin we need a label for the navigational elements on the right, do you have a proposal for an alternative there? Perhaps 'Uncategorized' would be more descriptive?

I'd propose we handle the second part of this issue as a separate one, as it will make it easier to discuss without the conversation becoming cluttered. Could you report it as such?

**Comment by jonkoops** [comment]
@pedroigor can I also get your take on this?

**Comment by pedroigor** [comment]
There is no strong reason for having a high priority for attributes with groups. Considering this might be a matter of preference and use-case-specific, does it make sense to have a flag to control this behavior?

**Comment by jonkoops** [comment]
> does it make sense to have a flag to control this behavior?

I'd argue we should not be adding more options. We can have an opinionated default here, and if users ever feel the need that this should be configurable they can let us know so we can determine if we need to take on that additional technical complexity.

**Comment by pedroigor** [comment]
@ReneZeidler @jonkoops +1 to split into two issues so we can prioritize the fix to the order.

**Comment by ReneZeidler** [comment]
> I also agree that the 'General' heading doesn't make sense, at least for the login. For the account and admin we need a label for the navigational elements on the right, do you have a proposal for an alternative there? Perhaps 'Uncategorized' would be more descriptive?

I think "General" is fine, at least I can't think of a better label. I don't think "Uncategorized" should be a default heading in a user-facing application (the account console), it gives the impression that something isn't configured correctly.

You can always override the label with a custom theme/translation.

> I'd propose we handle the second part of this issue as a separate one, as it will make it easier to discuss without the conversation becoming cluttered. Could you report it as such?

I'll create an issue for the feature request of having a well-defined ordering of attribute groups. The most important fix is not having the ungrouped attributes appear at the bottom of login forms where they visually appear as belonging to the last attribute group.

> There is no strong reason for having a high priority for attributes with groups. Considering this might be a matter of preference and use-case-specific, does it make sense to have a flag to control this behavior?

I don't see any use-case where ungrouped attributes should appear anwhere else but the top of the form without a heading. If you put them somewhere else, they need to be visually separated from the preceding attributes, i.e. they need a heading. And if you want to define a heading, you can already create an attribute group for that.

**Comment by jonkoops** [comment]
This all sound good to me, would you perhaps be willing to take this one on @ReneZeidler?

**Comment by ReneZeidler** [comment]
> This all sound good to me, would you perhaps be willing to take this one on @ReneZeidler?

I don't have a dev env set up for Keycloak, and I don't want to blindly make a pull request. To me it seems like simply changing `nullsLast` to `nullsFirst` here should fix the issue:

https://github.com/keycloak/keycloak/blob/28afd77917612ffed8090902315eaa6485455645/services/src/main/java/org/keycloak/forms/login/freemarker/model/AbstractUserProfileBean.java#L45

Somone else could test this change, otherwise I'll try to set up a dev env when I find the time.
