### ISSUE TITLE
Keycloak CR Truststore should not have a name

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#28012]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

There were several design iterations over if/where a truststore should be named. In the final version the name is supposed to be on the map of entries at the spec level, however a name field was also left on the truststore itself.

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

A name should not be required on the truststore stanza.

### Actual behavior

A redundant name is required.

### How to Reproduce?

Add a truststore to a keycloak cr.

**Comment by vmuzikar** [comment]
@shawkins Can you please create a backport for this?

**Comment by shawkins** [comment]
@vmuzikar https://github.com/keycloak/keycloak/pull/28148
