### ISSUE TITLE
scroll bar is missing inn clients view keycloak admin GUI

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#28018]
### Description

Clients/Users page is overflow -> Hidden the info of users/clients and do not display Delete button.

Attached the exact view and improper view.

A scroll bar is missing and not able to view export or delete option menu
![Screen Shot 2024-03-18 at 12 31 12 PM](https://github.com/keycloak/keycloak/assets/20001725/ab4e20c6-410e-41eb-8687-ddf7c52b1939)

Sample Example is a group screeen
![Screen Shot 2024-03-18 at 12 31 29 PM](https://github.com/keycloak/keycloak/assets/20001725/6190277d-ff68-4b9d-9d7f-80f560a5f0bf)

**Comment by jonkoops** [comment]
This is a bug report, not an enhancement, please report it as such.
