### ISSUE TITLE
 Firefox Webauthn Registration "SecurityError: The operation is insecure."

### ISSUE THREAD

**Issue by mcarbonneaux** [keycloak/keycloak#28020]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Describe the bug

on firefox on windows 11 if i try to configure webauthn by following the [documentation](https://www.keycloak.org/docs/21.1.2/server_admin/#webauthn_server_administration_guide) i fail with this error when i go to webauthn registering phase. but on all other website like google, webauthn.io it's work fine...

![image](https://github.com/keycloak/keycloak/assets/8479023/a08e286b-0d67-4f1f-b9f0-f7cc884e15c2)

![image](https://github.com/keycloak/keycloak/assets/8479023/497c4667-cd67-44e3-8544-d86e93a7d266)

after digging on the web find why.... i've not found why...

finaly i've tested on different browser ... and with debugger console...
and on edge finaly i seen this message in the dev console (i've no message on firefox) :
![image](https://github.com/keycloak/keycloak/assets/8479023/396e01a7-6349-4233-9c07-7f41c0fa5133)

the message speek about this link : https://chromium.googlesource.com/chromium/src/+/main/content/browser/webauth/pub_key_cred_params.md

on this page they say that on microsoft windows platform need to have Signature algorithms RS256 in [pubKeyCredParams](https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialparameters)... and keycloak by default not use this Signature algorithms (only ES256)...

after adding it in keycloak admin console: 
![image](https://github.com/keycloak/keycloak/assets/8479023/1ad4e81c-1991-479a-b62e-9ae50a64654d)

we don't have any more the error message in edge, and it's work, and it's work also on firefox...

### Version

21.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Webauthn Registration without error...

### Actual behavior

Webauthn Registration "SecurityError: The operation is insecure."

### How to Reproduce?

install keycloak 21.1.2 from scratch and follow the documentation https://www.keycloak.org/docs/21.1.2/server_admin/#webauthn_server_administration_guide and try to log first time and try to register webauthn key...

### Anything else?

i think you must add RS256 by default in addition of ES256, because of windows platform authenticator that require it... or modify the documentation to inform keycloak admin user to add this Signature algorithms if they have windows user...

**Comment by mposolda** [comment]
@mcarbonneaux Thanks a lot for the investigation!

I am switching to "important" as it will be probably good to prioritize this. We should doublecheck whether we should change the default or update docs. Changing the default can be better unless there are some other side-effects (to be investigated).

@tnorimat Are you aware of any side-effects of changing the default to have both RS256 and ES256?

**Comment by tnorimat** [comment]
@mposolda I think it is OK to have both ES256 and RS256 as default setting.

**Comment by jonkoops** [comment]
Not sure if the others already checked this, but from what I can see this was reported for an older version that is no longer supported. Feel free to bump if this is still reproducible in 24.

**Comment by rmartinc** [comment]
@mposolda @tnorimat I also think that adding RS256 as default should not be an issue.

**Comment by jlrcontegix** [comment]
On Keycloak 24.0.1 we've added RS256, RS384, and RS512, but Firefox still fails to register our Yubikeys.

In our case we are only allowing a specific AAGUID and we see the following error, but this is only happening in Firefox:

![image](https://github.com/keycloak/keycloak/assets/28273315/3a416aee-71f3-4cad-9f82-ccd5a78a9e80)

**Comment by LevN0** [comment]
Do you have attestation conveyance preference set to at "direct" or "indirect"? Any other value won't send an AAGUID.

**Comment by jlrcontegix** [comment]
We have ours set to Direct. We've tried Indirect and Not Specified.

**Comment by jonkoops** [comment]
Looks like the bot has closed this issue, if anyone can reproduce this under 24.0.2 let us know and I will re-open it.

**Comment by mcarbonneaux** [comment]
i've tested on 24.0.2, and the same:
![image](https://github.com/keycloak/keycloak/assets/8479023/b6d0a92d-7717-4400-be1a-1959b7587087)
and on edge is the same:
![image](https://github.com/keycloak/keycloak/assets/8479023/9ee0c2ad-0e79-4f04-a569-184204433247)

and after adding RS256 it's work fine!

**Comment by rmartinc** [comment]
Yep, this issue is not resolved, it was closed automatically by the bot.

**Comment by mcarbonneaux** [comment]
i've try to modify the code to add this additional default algorythm to webauthn policy in https://github.com/keycloak/keycloak/pull/30528
