### ISSUE TITLE
Upgrade Infinispan to 14.0.27.Final

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#28033]
### Description

Infinispan 14.0.27.Final is out and it is the baseline for the product.

Release: https://github.com/infinispan/infinispan/releases/tag/14.0.27.Final

**Comment by ahus1** [comment]
@pruivo - please prepare a backport for KC22. This should only include the changes for the root `pom.xml`. I see that KC22 still has an explicit dependency the `infinispan.protostream.processor.version`, which also needs to be addressed. 

Thanks!

**Comment by ahus1** [comment]
Adding some context why I ask for this: Backporting it to KC22 would align it with the latest productized datagrid version.

**Comment by pruivo** [comment]
PR: https://github.com/keycloak/keycloak/pull/29555
