### ISSUE TITLE
Group search does not work in user view

### ISSUE THREAD

**Issue by MartaGolabek** [keycloak/keycloak#28079]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Group search in user view doesn't work. Results don't match provided search term.

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Search returns results matching provided search term.

### Actual behavior

Search returns results not-matching provided search term.

### How to Reproduce?

1. Go to Users
2. Select a user
3. Go to Groups Tab
4. Click 'Join Group'
5. Type search term
6. Results don't match provided search term

**Comment by bodograumann** [comment]
Unfortunately I can neither reproduce this issue with 23.0.6 nor with 24.0.1. Maybe it only occurs under specific circumstances...
In fact we are using the search as a workaround for #28080.

**Comment by MartaGolabek** [comment]
@bodograumann are your groups also nested or flat ones? Maybe the problem occurs only with nested groups...

**Comment by bodograumann** [comment]
We have one top-level group and lots of subgroups, but not more than these two levels. Do you have deeper nesting?

**Comment by MartaGolabek** [comment]
> We have one top-level group and lots of subgroups, but not more than these two levels. Do you have deeper nesting?

Yes, we have more than one top-level group.

**Comment by bodograumann** [comment]
It would probably be helpful, if you could provide some more information, like:
- Can you see what groups are displayed, if not the ones that match your search term?
- What requests are sent to the backend to retrieve the groups when you submit your search?

**Comment by MartaGolabek** [comment]
@bodograumann it looks like the top-level groups including matching subgroups are displayed.

**Comment by bodograumann** [comment]
Yes, I can confirm that on 24.0.1.
When a subgroup matches, it's parent is also displayed, even if the parent does not match the search term.

**Comment by MartaGolabek** [comment]
> @bodograumann it looks like the top-level groups including matching subgroup are displayed.
> 
> Let's assume that my hierarchy looks like this:
> 
> Top_Group_1 > Top_Group_2 > Matching_Subgroup
> 
> Then results will look like this:
> 
> * Top_Group_1
> * Top_Group_1/Top_Group_2

Unfortunately, I encounter this issue on keycloak version 25.0.1 as well. Can we reopen this issue?

**Comment by bodograumann** [comment]
On 26.0.0 I just tried creating Groups "Parent A", "Parent A > Child A" and "Parent A > Child B".
Searching for "A" showed parent and child, while searching for "B" just showed the child.
Can you try with v26 and maybe give more details how to reproduce, if you encounter the problem again?

**Comment by jonkoops** [comment]
I am going to lock the discussion on this thread as this issue has been resolved. If you are still experiencing issues on the latest version of Keycloak please file a new issue.
