### ISSUE TITLE
Create realm using python script

### ISSUE THREAD

**Issue by shishir84** [keycloak/keycloak#28098]
### Description

I am using keycloak 19 and I am trying to create realm using python3. But it keeps on giving HTTP 500. When I checked the logs I saw that seeing script upload is disabled. I know this is deprecated. Now want to know I can create a realm using Python.

### Motivation

i am looking for an alternative.

### Details

import requests
import json
import subprocess
import re

# Read Keycloak configuration from a file
config_path = "/mydata_ebs_1/tenant-automation/keycloak/keycloak_config"
with open(config_path) as f:
    keycloak_config = dict(line.strip().split('=') for line in f)

# Extract Keycloak configuration details
KEYCLOAK_BASE_URL = keycloak_config["KEYCLOAK_BASE_URL"]
ADMIN_USERNAME = keycloak_config["ADMIN_USERNAME"]
ADMIN_PASSWORD = keycloak_config["ADMIN_PASSWORD"]
REALM_NAME = keycloak_config["REALM_NAME"]

# Get Keycloak admin token
def get_admin_token():
    token_response = requests.post(
        f"{KEYCLOAK_BASE_URL}/realms/master/protocol/openid-connect/token",
        data={
            "username": ADMIN_USERNAME,
            "password": ADMIN_PASSWORD,
            "grant_type": "password",
            "client_id": "admin-cli",
        },
    )

    token_response.raise_for_status()
    return token_response.json()["access_token"]

token = get_admin_token()

print(token)

# Define the path for the new_wingspan.json and the resulting JSON file
resulting_json_path = f"/mydata_ebs_1/tenant-automation/keycloak/files/{REALM_NAME}.json"

# Load the generated realm data
with open(resulting_json_path) as realm_file:
    REALM_DATA = json.load(realm_file)

# Check if the realm exists
realm_response = requests.get(
    f"{KEYCLOAK_BASE_URL}/admin/realms/{REALM_NAME}",
    headers={"Authorization": f"Bearer {token}"},
)

# Create or update the realm based on its existence
if realm_response.status_code == 404:
    create_response = requests.post(
        f"{KEYCLOAK_BASE_URL}/admin/realms",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        json=REALM_DATA,
    )
    print(create_response.json())
    if create_response.status_code == 201:
        print(f"Realm '{REALM_NAME}' created successfully.")
    else:
        print(f"Failed to create realm. Status code: {create_response.status_code}, Error: {create_response.text}")
else:
    update_response = requests.put(
        f"{KEYCLOAK_BASE_URL}/admin/realms/{REALM_NAME}",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        json=REALM_DATA,
    )
    if update_response.status_code == 204:
        print(f"Realm '{REALM_NAME}' updated successfully.")
    else:
        print(f"Failed to update realm. Status code: {update_response.status_code}, Error: {update_response.text}")

**Comment by jonkoops** [comment]
This is not an issue report, please check our [community page](https://www.keycloak.org/community) to find the right place to go.
