### ISSUE TITLE
kc.sh may leak credentials

### ISSUE THREAD

**Issue by trixpan** [keycloak/keycloak#28090]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

while many sensitive properties can (and should) be passed via purpose built environment variables, some sensitive properties must be provided via JAVA_OPTS (e.g. `javax.net.ssl.trustStorePassword` when using BCFIP).

kc.sh dumps the parameters during startup resulting on logs containing the password.

https://github.com/keycloak/keycloak/blob/ceed62213df586cc7fe0d3ef45e7b11057ded3d2/quarkus/dist/src/main/content/bin/kc.sh#L118

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Do not display sensitive data on container logs

### Actual behavior

Sensitive data is added to container logs

### How to Reproduce?

pass a sensitive variable via JAVA_OPTS

**Comment by shawkins** [comment]
This seems to be a valid concern. We have other echos that we consider sanitizing as well. Perhaps we should just omit the values unless PRINT_ENV is set.

cc @aspectj @vmuzikar 

~priority-important

**Comment by vmuzikar** [comment]
@shawkins I don't think we document/support passing any sensitive data via JAVA_OPTS. I would not consider it a secure source for passing any sensitive data. But we could of course as part of hardening tweak the message to just say that JAVA_OPTS is used but without printing the values, as you suggested.

(I think you meant to ping @abstractj.)

**Comment by shawkins** [comment]
> But we could of course as part of hardening tweak

Yes, I would think of this as hardening, not a vulnerability.

> (I think you meant to ping @abstractj.)

Indeed :)

**Comment by abstractj** [comment]
@shawkins @vmuzikar I just wonder if it would be possible to use some sort of variable indirection. That means, instead of placing sensitive data in JAVA_OPTS, use environment variables to reference the sensitive data. For example:

```
export TRUSTSTORE_PASSWORD=mySecretPassword

JAVA_OPTS="-Djavax.net.ssl.trustStorePassword=$TRUSTSTORE_PASSWORD"
```

But if that's not possible, or a good idea, the original proposal from Steve is a good direction.

**Comment by shawkins** [comment]
@abstractj I don't think it's possible anymore because we aren't directly evaling the contents of the env values.

**Comment by abstractj** [comment]
> @abstractj I don't think it's possible anymore because we aren't directly evaling the contents of the env values.

Thanks Steve, so let's stick with your proposal.
