### ISSUE TITLE
Auth status not retrieved in iFrame incognito mode causing looping issue

### ISSUE THREAD

**Issue by rodeaboli** [keycloak/keycloak#28117]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have implement the keycloak based SSO login in our project wherein the login app, keycloak server and one feature app is hosted on same parent domain, this feature app is integrated as an iFrame on a third party application.

Here, we are not able to retrieve the authentication status of the user after completing the login flow in iFrame incognito mode, the authenticated parameter returns undefined and hence user is redirected again to the login flow, causing an endless loop.

please note: this issue is occurring in only strict browser mode when cookies are blocked

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

The authentication status should have been retrieved.

### Actual behavior

The authentication status is not retrieved.

### How to Reproduce?

If a user logs in through our app in browsers like chrome incognito mode, safari private browser, then this issue is reproducible.

### Anything else?

Can you provide an alternative way to fix this issue while using the browser with strict policies or when third party cookies are blocked?

_No response_

**Comment by graziang** [comment]
Keycloak needs cookies to log in with the browser flow, if you try to log in with cookies disabled you should get an error message like: "Cookie not found". Using something like direct grant might work without cookies but I don't know if it's recommended for your use case.

**Comment by rodeaboli** [comment]
I read more on direct grant flow, but here I am using the biometric based authentication login app, hence I cannot use it for my case.

**Comment by rodeaboli** [comment]
I read more on direct grant, but in my login application I use biometric based authentication hence this is not applicable for me. I am hoping to get more solutions based on cookieless implementations as browsers may not be supporting third party cookies in longer run.
