### ISSUE TITLE
Webauthn policies show Platform instread of Cross Platform

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak#28127]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If you go to the `Authentication` tab, select `Policies` and `Webauthn Policy`. In the option `Authenticator Attachment` change to `Cross platform`. You will see `Platform` is set again.

It seems to be just a visual effect because the value `cross-platform` is really save to the realm.

I have fixed the issue with this nitty change:

```diff
diff --git a/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties b/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
index 3cc409047d..67b7a0cc61 100644
--- a/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
+++ b/js/apps/admin-ui/maven-resources/theme/keycloak.v2/admin/messages/messages_en.properties
@@ -1569,7 +1569,7 @@ usersDNHelp=Full DN of LDAP tree where your users are. This DN is the parent of
 addKeycloakOpenIdProvider=Add Keycloak OpenID Connect provider
 clientSessionMax=Client Session Max
 deleteClientPolicy=Delete client policy
-authenticatorAttachment.cross-platform=Cross platform
+authenticatorAttachment.cross\-platform=Cross platform
 whoCanView=Who can view?
 lastAccess=Last access
 emptyClientScopesInstructions=There are currently no client scopes linked to this client. You can add existing client scopes to this client to share protocol mappers and roles.
```

I can send a PR with that change but I really don't know if it's the correct approach.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

It should show `Cross platform`.

### Actual behavior

It shows `Platform`.

### How to Reproduce?

See description.

**Comment by hmlnarik** [comment]
Confirmed for `24.0.1`, works for `main`

**Comment by rmartinc** [comment]
Yep, it works in main so I'm closing it.
