### ISSUE TITLE
Make sure organization-related data can only be managed from the Organization API

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#28133]
As an organization is leveraging the existing functionality from realms to enable its capabilities, we need to make sure that data is only manageable from the Organization API and, under certain circumstances, only internally by the organization provider.

The constraints should apply to the following data:

* **Realms**
* * Any attribute set to groups by the organization provider should be read only for both users and administrators
* **Groups**
* * These groups should not be manageable by the Group API
* * Make sure the group name used and its format are reserved and can not be set to regular groups
* * Any attribute set to groups by the organization provider should be read only for both users and administrators
* **Users**
* * Organization member accounts should not be manageable by the User API
* * Any attribute set to a user by the organization provider should be read only for both users and administrators 
* **Identity Providers**
* * These identity providers should not be manageable by the Identity Provider API
* * Any attribute set to a user by the organization provider should be read only for both users and administrators

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/28734
- [ ] https://github.com/keycloak/keycloak/issues/28833
```

**Comment by pedroigor** [comment]
If we can leverage group-related events and listen for them whenever a CRUD operation is performed on a group, even better. Because it will help to keep the feature self-contained.

**Comment by pedroigor** [comment]
Do we want to have a group attribute to mark a group as an organization too? It would be a 2-way link between the two.

Perhaps it helps a lot to check whether a group is being removed and if it resolves to a organization.

That is why I tried using a 1:1 between the organization and the group.

**Comment by pedroigor** [comment]
Does not make sense anymore.
