### ISSUE TITLE
Review relationships and usage of FK constraints in Keycloak

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#28131]
There has been created `OrganizationEntity` with some foreign keys (Realm, Group). This issue is about reviewing and possibly adding a foreign key constraints. 

EDIT: probably worth reading: https://vladmihalcea.com/the-best-way-to-map-a-onetoone-relationship-with-jpa-and-hibernate/

**Comment by pedroigor** [comment]
Do you know why some key tables like `user` -> `realm` without an FK? Also, why do we see FKs being dropped across different changesets?

**Comment by pedroigor** [comment]
Superseded by https://github.com/keycloak/keycloak/issues/28739
