### ISSUE TITLE
External Infinispan as cache - Part 1

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#28140]
### Description

In the context of multi-site high availability deployment, this issue suggests the removal of the embedded clustered caches and using the required external Infinispan server in cross-site mode only.

This is a requirement for Active-Active deployments.

### Motivation

Keeping the embedded clustered caches in sync with the external Infinispan is not simple. The current solution relies on events streaming to asynchronously update the embedded caches in both sites (sessions mostly) which is costly. Parts of the code also require all sessions to be available in the embedded caches and not fetch any updated value from external Infinispan (search for `SKIP_CACHE_LOAD` flag). 

To simplify the architecture and Keycloak source code, the proposal is to remove those embedded cache. 

The drawback focuses mainly on performance:
* Reads had a `num_owners / number of Keycloak servers` of finding the data locally and avoiding any network call. With the external Infinispan, a remote call is required (except if near-caching is enabled)
* Search and iteration are slower since all dataset is streamed to the Keycloak node. This will be improved in the future by using Infinispan Protostream marshaling and Queries.

There are benefits from this approach too. Besides the simplified source code, write operations would be faster since only the external Infinispan replicates data. Keycloak will be stateless, improving the startup times and, if possible by Keycloak logic, allowing different Keycloak versions to participate. Finally, upgrading Keycloak does not lose the sessions stored in the external Infinispan.

### Details

The implementation will make use of Features to enabled or disable this new mode. At the code level, the Providers will be replaced with new ones that use `RemoteCache`s. This decision is less intrusive and keeps the "current" code untouched and free of problems :crossed_fingers: .

Why "Part 1"?

It is a personal preference to have smaller PRs merged in the main branch. Smaller PRs mean easier to review and earlier feedback about the progress. The current test suite ensures nothing is broken.

This first part adds the experimental feature, testing (new maven profile), code to connect to the external Infinispan and a new implementation of `AuthenticationSessionProvider`. In the future, I'll open a PR for each new provider to keep the code simpler and smaller.

**Comment by Tristan971** [comment]
Seeing as this might also by side-effect solve #14040, this is exciting work.

> if possible by Keycloak logic, allowing different Keycloak versions to participate

That does however sound more like a part 3 than a part 1 or 2, but it would also be a massive improvement indeed.

**Comment by ahus1** [comment]
Merged to feature branch `feature/remote-cache`
