### ISSUE TITLE
Add release/24 branch to GH surefire reports action

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#28166]
### Description

Add new 24 release branch to GH actions: https://github.com/keycloak/keycloak/blob/main/.github/actions/archive-surefire-reports/action.yml#L10

**Comment by ahus1** [comment]
@lhanusov - I removed the `release/24.0.2` label as this is added automatically to the issue only after it has been backported and merged. The only label you set manually is `backport/24.0`.
