### ISSUE TITLE
Recovery code credentials not being listed on AccountCredentialsResources endpoint

### ISSUE THREAD

**Issue by fikrapdso** [keycloak/keycloak#28188]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

User already configured the recovery-authn-codes credential.
It is showing up in admin endpoint `/admin/realms/:realm/users/:id/credentials`
```json
[
    {
        "id": "ab2c5550-b577-409a-9ebd-f6eab0772596",
        "type": "password",
        "userLabel": "My password",
        "createdDate": 1711257326566,
        "credentialData": "{\"hashIterations\":210000,\"algorithm\":\"pbkdf2-sha512\",\"additionalParameters\":{}}"
    },
    {
        "id": "826d1350-d2a5-407c-aa42-fac63c327918",
        "type": "recovery-authn-codes",
        "userLabel": "Recovery codes",
        "createdDate": 1711257927326,
        "credentialData": "{\"hashIterations\":1,\"algorithm\":\"RS512\",\"totalCodes\":12,\"remainingCodes\":12}"
    }
]
```
But recovery auth credential is not present in `account/credentials` endpoint.
```json
[
    {
        "type": "password",
        "category": "basic-authentication",
        "displayName": "password-display-name",
        "helptext": "password-help-text",
        "iconCssClass": "kcAuthenticatorPasswordClass",
        "updateAction": "UPDATE_PASSWORD",
        "removeable": false,
        "userCredentialMetadatas": [
            {
                "credential": {
                    "id": "ab2c5550-b577-409a-9ebd-f6eab0772596",
                    "type": "password",
                    "userLabel": "My password",
                    "createdDate": 1711257326566,
                    "credentialData": "{\"hashIterations\":210000,\"algorithm\":\"pbkdf2-sha512\",\"additionalParameters\":{}}"
                }
            }
        ]
    },
    {
        "type": "otp",
        "category": "two-factor",
        "displayName": "otp-display-name",
        "helptext": "otp-help-text",
        "iconCssClass": "kcAuthenticatorOTPClass",
        "createAction": "CONFIGURE_TOTP",
        "removeable": true,
        "userCredentialMetadatas": []
    }
]
```

Notice the same id on password credentials. That indicating both response is on the same account but using different endpoints.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

All the credentials that assigned to the user are being shown when no filter and hide parameter is not there.

### Actual behavior

it shows credentials except for Recovery authn code

### How to Reproduce?

1. enable recovery feature
2. add user with password credential
3. add Recovery Auth Codes as required action to user
4. open in new tab to login using new user
5. login with password
6. save recovery codes

it will show on admin response, but not on account endpoint response

**Comment by mposolda** [comment]
@fikrapdso Account REST API credential endpoint displays only credentials, which can be used for authentication. Can you try to add recovery-authn-codes credential to some authentication flow of your realm, which is used for authenticate user? Then the recovery-authn-codes credential should be displayed in account console.

**Comment by mposolda** [comment]
I am closing as I think this can be solved as I've mentioned above. Please re-open if you don't see recovery-codes after my previous suggestion is applied.
