### ISSUE TITLE
"Import key" dialog window -> "Archive format" drop-down menu does not display "Certificate PEM" correctly

### ISSUE THREAD

**Issue by fhertzwo** [keycloak/keycloak#28185]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Admin Console UI to import a certificate is broken. 

### Version

21.1.0

### Regression

- [X] The issue is a regression

### Expected behavior

The menu should display the items properly, as before:
![image](https://github.com/keycloak/keycloak/assets/164576983/5e6425c9-aa71-4cd0-b286-6298d8e91675)

### Actual behavior

![image](https://github.com/keycloak/keycloak/assets/164576983/7c356c2f-4c97-4357-9d8b-b24bbe27f938)

### How to Reproduce?

The issue is reproducible in Chrome and in Firefox browsers. I did not try anything else.
Here are the steps to reproduce the issue:
- Login to Keycloak admin console
- Select a realm
- On the sidebar click on "Clients"
- Select an existing client
- Click on "Keys" tab
- In the certificate section click on "Import key"
- In the "Archive format" try to select "Certificate PEM". 

The last step fails because the drop-down menu is broken.

### Anything else?

I saw the terms of submission above, but I am not able to test this bug on the latest keycloak build. Please verify it on your side – it only takes a few minutes and the sequence to reproduce is straightforward. 
If the bug is still there, is there a chance to get a fix in v21.1.0? 
Thank you.

**Comment by hmlnarik** [comment]
On 24.0.1, this cannot be reproduced:

![image](https://github.com/keycloak/keycloak/assets/5391360/0139533c-b740-4f51-a399-a0cec1fc4718)

Unfortunately we do not fix bugs in old releases. Please consider upgrading to the latest version.

**Comment by jonkoops** [comment]
> I am not able to upgrade to the latest Keycloak version

You really should. We only support the latest major version, older versions of Keycloak are very likely vulnerable to several security issues.

**Comment by jonkoops** [comment]
You'll have to go trough the changelogs, I am not quite sure when and how this was fixed. But I do recall this issue being reported some time ago. Perhaps the easiest option is to run a Keycloak server locally and upgrade it until the issue goes away, that way you know which version landed the fix, the release notes should be able to tell you which PR it was that fixed it.

**Comment by fhertzwo** [comment]
@jonkoops Where do I get these changelogs? I looked at the Releases page, but there are only a few releases with the "list of bugs" information.

**Comment by fhertzwo** [comment]
@jonkoops I think, I found it. Could you please confirm that this is the code change I need.
Issue: [#17514](https://github.com/keycloak/keycloak/issues/17514)
Code change: [#19914](https://github.com/keycloak/keycloak/pull/19914)

**Comment by jonkoops** [comment]
Sorry don't have time for that. You'll have to take care of it yourself. If you want support you'll have to use a supported version.
