### ISSUE TITLE
Nightly version 999.0.0 prevents new Migration implementations from running

### ISSUE THREAD

**Issue by cwelch-rh** [keycloak/keycloak#28200]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

In nightly versions, the MIGRATION_MODEL table is updated with a record that contains the version "999.0.0", which prevents new implementations of Migration from being applied.

### Version

Nightly / 999.0.0-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

The version should be updated to the last applied update version so that new implementations of Migration will run correctly.

### Actual behavior

Once the nightly version (999.0.0) is added as the latest entry in MIGRATION_MODEL, no future implementations of Migration will run, causing unexpected behavior.

### How to Reproduce?

Run a previous release version of keycloak with a persistent DB. The latest entry in MIGRATION_MODEL should be the release version. Example: 23.0.0

Checkout commit before MigrateTo24_0_0 was created. Run against same persistent DB. Latest entry in MIGRATION_MODEL should be 999.0.0

Run nightly version of keycloak against same DB. MigrateTo24_0_0 will be skipped.

**Comment by stianst** [comment]
Nightly and builds from main do not support migration
