### ISSUE TITLE
Review how transaction is being handled when creating members due to the commit happening when leveraging UsersResource.createUser

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28210]
In order to leverage the User API to create organization members, we are invoking the `UsersResource.createUser` method.

However, that method does not rely on the usual mechanism to handle transactions and forces a `commit` whenever that method is called.

As a consequence, we are starting a new transaction after calling that method in order to associate the newly created user to an organization.

We need to review this and ideally remove that `commit` call in `UsersResource` so that we can create the user and associate it as a member within a single transaction.

**Comment by vramik** [comment]
relates to https://github.com/keycloak/keycloak/issues/28217
