### ISSUE TITLE
Problem updating attributes with values over 2048 characteres in ldap federated users

### ISSUE THREAD

**Issue by cesarcoruna** [keycloak/keycloak#28233]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We have an attribute with large values over 2048 characteres. In 24.0.x realease we can't update users with this values because it fails when /admin/realms/<realm>/users/ is called. This method returns a 400 http code.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

We can save changes in user attributes

### Actual behavior

It fails

### How to Reproduce?

Put a over 2048 characters value in a field.

**Comment by cesarcoruna** [comment]
I update this case to clarify that this error happens if you use LDAP federation.

**Comment by vramik** [comment]
I believe this is related to this change: https://www.keycloak.org/docs/latest/upgrading/index.html#user-attribute-value-length-extension
