### ISSUE TITLE
Search user field looses focus after first character on first usage after reload

### ISSUE THREAD

**Issue by Loic-des-Rochettes** [keycloak/keycloak#28249]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When typing in the search user field, it looses focus after typing 1 lettre. When an user federation is configured.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Search field keep the focus.

### Actual behavior

Losses the focus after typing first lettre.

### How to Reproduce?

* Create an ldap user federation
* Go to the Users page on admin ui
* F5 to garantie the buggy state
* Start typing in the search field
* The focus is lost and you cant continue typing

**Comment by ssilvert** [comment]
@Loic-des-Rochettes Thanks for reporting.  This should be already fixed in the nightly build under issue #27917.

I'm going to close this, but if you try the nightly build and it's still broken we can reopen.
https://github.com/keycloak/keycloak/releases/tag/nightly
