### ISSUE TITLE
Use a reserved naming space for tables related to organization

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28246]
See https://github.com/keycloak/keycloak/discussions/23948#discussioncomment-8927678.

**Comment by xgp** [comment]
Suggest changing it to `ORG` and using the prefix `ORG_` for related tables. Happy to PR the change if you'd like.

**Comment by xgp** [comment]
Made a PR https://github.com/keycloak/keycloak/pull/28306
