### ISSUE TITLE
Update user makes User ID changes when federationLink and LDAP_ID is not set properly

### ISSUE THREAD

**Issue by Loic-des-Rochettes** [keycloak/keycloak#28248]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

On an existing keycloak 23 with LDAP user federation (Active directory in production, reproduced with LDAP), upgrading to 24 can lead to unexpected behavior.
User managed attributes enabled and LDAP_ID as user managed attribute

Modifiying federated user can lead to user-id modification (user recreation ?)

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Updating user profile whithout id changes or error if something is malformed or missing.
If not defined inside the update request, keep the existing federationlink and user.

### Actual behavior

When updating user profile, if attributes are set but not LDAP_ID the user is recreated.

### How to Reproduce?

* Create an user with a legacy federation link as user attributes
* Update that user through API with "attributes" property and without "LDAP_ID" attribute 
* Check user ID before and after

### Anything else?

Exemple of "buggy" update :
```bash
curl --request PUT "$HOST/admin/realms/$REALM/users/$USERID" \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $(token)" \
--data-raw '{
  "username": "test",
  "firstName": "testpostman",
  "lastName": "test",
  "email": "test@example",
  "emailVerified": true,
  "createdTimestamp": 1711475862870,
  "enabled": false,
  "totp": false,
  "attributes": {
  },
  "federationLink": "5a0e567f-8178-40d4-ac91-5f429467bae4",
  "disableableCredentialTypes": [],
  "requiredActions": [],
  "notBefore": 0,
  "access": {
    "manageGroupMembership": true,
    "view": true,
    "mapRoles": true,
    "impersonate": false,
    "manage": true
  }
}'
```

**Comment by jonkoops** [comment]
@Loic-des-Rochettes is this reproducible in 24.0.2 as well?

**Comment by Loic-des-Rochettes** [comment]
Yes, i updated then instance, same behavior on 24.0.2.
The path to reproduce the problem is still a bit unclear to me i managed to do it once but no more. (still unsure if it was 100% the same thing)

The buggy instance has LDAP_ID and LDAP_ENTRY_DN in the user defined attributes.

"Normal" has it in profile metadata.

Through the API those field are absent from the user representation but can be retrieved through the search API. But i think this is related to them being in users defined attributes and not in metadata.

The endpoint behavior described above is clearly a consequence of what seems to be a migration issue.
(putting some more check wouldn't be a bad idea anyway)

**Comment by Loic-des-Rochettes** [comment]
Update about this bug : 
It does not occur on the highest priority userFederation, and does not occur at all on realm with only one userFed.

Contrary to what I stated previously it does not seem to be a migration issue but it is only related to metadata management having different behavior depending on its priority.

Steps to reproduce : 
* Create an user federation from an LDAP ou with users (or create some users on it with WRITABLE and sync registration)
* Create an other user federation and set it to highest priority (could be on a different OU on the same LDAP server for simpler testing)
* Check an user profile detail from the first created userFederation you'll see that there is no metadata. Check the attributes tab and you'll find them. And then you'll be able to reproduce the API behavior described above.

**Comment by sguilhen** [comment]
I was able to reproduce the issue as described in the last comment. It has to do with how the attribute selector was implemented in `LDAPStorageProvider`.

**Comment by pedroigor** [comment]
The cause is that there is an overlap when multiple user storage providers are enabled in a realm. We are caching the user profile metadata where the selector for an attribute is bound to the provider with the highest priority rather than to the provider the user is associated with.
