### ISSUE TITLE
Keycloak's Memory Consumption Escalates, Leading to Application Crashes

### ISSUE THREAD

**Issue by sweta96** [keycloak/keycloak#28264]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Keycloak exhibits a progressive increase in memory consumption over time under normal operational conditions. This unchecked memory usage escalates to the point where it exceeds the allocated memory limits for the application, leading to performance degradation, unresponsiveness, and eventual application crashes. The issue manifests itself even without a corresponding increase in user load or request rate, indicating a potential memory leak or inefficient memory management within Keycloak.

**Impact:**
This issue affects system stability, performance, and availability, leading to potential service disruptions for users relying on Keycloak for authentication and authorization services.

### Version

24.0.0

### Regression

- [x] The issue is a regression

### Expected behavior

Memory usage should remain stable over time or follow a predictable pattern of growth and garbage collection, ensuring that the application operates within its allocated memory resources without significant leaks or inefficiencies.

### Actual behavior

Memory usage continuously increases over time, without signs of significant garbage collection or memory release, leading to an eventual out-of-memory error or application crash. This behavior suggests a memory leak within the application or related libraries.

### How to Reproduce?

- Deploy Keycloak as a service in AWS ECS. 
- Configure a minimal set of realms, users, and clients to mimic a standard operational setup.
- Execute a series of standard authentication and authorization requests simulating normal user activity.
- Monitor memory usage over time using (service metrics, container metrics, etc.).

**Environment:**
- Keycloak version: (24.0.0 and above)
- Deployment option: (AWS ECS)
- Operating System: (Amazon Linux, 2023)

### Anything else?

![image](https://github.com/keycloak/keycloak/assets/27861304/bb9514e9-b23a-4f27-91dc-af6f1263b351)

**Comment by souravs17031999** [comment]
You can check actual memory usage and if memory increases/decreases over time by observing the metrics provived in admin UI
![image](https://github.com/keycloak/keycloak/assets/33771969/6e02e07a-bb6a-49b5-bdf4-3110e90c8963)

Also, you should monitor keycloak internal metrics at `/metrics` endpoint to know if garbage collection is working or not and use those metrics to compare with what AWS is providing (probably at pod/container level?) .

**Comment by SpiralScout4Share** [comment]
Same issue here. But we're not asking for help, we just rolled back to 23.0.0

**Comment by shawkins** [comment]
@SpiralScout4Share @sweta96 we have observed the increasing heap space growth with KC 24 #28855 but what we've also observed is the actual heap usage is as expected. In this case you are indicated there is associated performance problems and eventual OOM. In that case would it be possible to provide what is actually being retained in your heap via analyzing a heap dump?

**Comment by sweta96** [comment]
Can you provide steps on how to take a heap dump for the keycloak container?

**Comment by shawkins** [comment]
> Can you provide steps on how to take a heap dump for the keycloak container?

If you are experiencing an OOM error, then use HeapDumpOnOutOfMemoryError - https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/clopts001.html with a HeapDumpPath pointed to a volume where you can get the heap dump afterwards.

> memory heap increase in idle state

Presumably that is showing the actual in use heap, not the heap size - but can you compare to what is reported in the app as @souravs17031999 suggested above just to make sure.

**Comment by ryanellis** [comment]
We're experiencing the same issue. We host KC via AWS ECS.
Until we find a resolution for this, we have resorted to restarting the ECS task daily to clear the memory.
Next steps, we'll try increasing the memory of the container to be a little more generous then stated here: https://www.keycloak.org/high-availability/concepts-memory-and-cpu-sizing
