### ISSUE TITLE
Set an internet domain to an organization

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28274]
Organizations need to be associated with one or more internet domains, so that users can mapped to an organization when logging in. As such, we need to be able to:

- specify the organization's internet domains when creating it;
- modify the list of internet domains of the organization when updating it;
- search for the organization by internet domain

The internet domain config can carry additional attributes, such as `verified`, so it might make sense to model it as a separate entity/representation.

Additionally, domains must be unique - i.e. orgs cannot share the same internet domain.

**Comment by sventorben** [comment]
Would be nice to have multiple internet domains for an organization, because I know some large enterprises using different domains for different national companies or for different industries and branches. They have one central ADFS though.

**Comment by pedroigor** [comment]
@sventorben Yeah, I agree. We are considering supporting multiple domains, although the first iteration will focus on a single domain per organization.

I would say we have two driven use cases here. That is why we want to start simple and focus on what we think is the majority of the use cases: an organization bound to a single domain.
