### ISSUE TITLE
Register users as an organization member when authenticating through the identity provider bound to an organization

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28273]
This task is about onboarding organization members by federating their accounts from the identity provider associated with an organization.

The basic flow will be as follows:

* By reaching the authorization endpoint, the server will first ask for the username (no credentials). In other words, executing an identity-first login.
* Once the user provides a username and the value is an e-mail that matches the domain of an organization, the user is automatically redirected to the identity provider associated with the organization
* Once the user is authenticated in the identity provider and redirected back to the organization realm, the regular first browser login flow is executed where, at the end, the federated user is added as a member of an organization.

The following constraints will be enforced when onboarding organization members from an identity provider:

* If the email from the identity provider (e.g.: as a result of calling the user info endpoint) does not match the organization domain, the flow will stop
* Using a broker not associated with an organization that matches the email domain of the user will stop the flow
* The authentication flow defaults to the default steps set to the browser flow. For instance, ask for a username and password
* There is no way to choose identity providers when providing the username on the login page
* Linking accounts (when there is an account already with the same email) should work just like if using a regular identity provider (not bound to an organization)
* Only a single identity provider is supported

**Comment by sventorben** [comment]
How do you plan this to work? In case of Google or M365, there may be multiple organizations using the same IdP, right?

**Comment by pedroigor** [comment]
@sventorben I think each organization having its own broker is better even though they share the same configuration. Organizations should be isolated from each other and you might easily end up in a situation where the way you authenticate through the same broker is different between organizations.

We should also take into account that the persona that will actually manage brokers for an organization is the Organization Administrator and not really the Keycloak Administrator. So the decision on what broker to use and what configuration should be used is organization dependent.

**Comment by sventorben** [comment]
> I think each organization having its own broker is better even though they share the same configuration. Organizations should be isolated from each other ...

How to ensure this isolation and not end up with people getting assigned to the wrong organization? Will there be some matching on the domain or anything similiar?

**Comment by vramik** [comment]
> How to ensure this isolation and not end up with people getting assigned to the wrong organization? Will there be some matching on the domain or anything similiar?

Yeah, the idea for now is to detect the organization based on the domain name and then the login through linked Identity provider bound to the org should automatically add a federated account as a member of the organization. 

Specific details how to detect the domain name are not yet known.

**Comment by pedroigor** [comment]
Yeah, we do know though that Keycloak Organizations will rely on the upcoming authentication policies feature to managed the authentication settings for an organization. The possibility to choose to automatically switch to a identifier-first login being one of these settings.

But yeah, for now users will be forced to manually update their flows or we can come up with some intermediary solution that automates a bit how the authentication flow is customized in an organization-enabled realm.

Another possibility I see in the future is using the `scope` parameter (or leverage resource identifiers or introduce an 'organization` parameter) to indicate whether the authorization request is related to an organization.

**Comment by pedroigor** [comment]
Hi @sventorben, I added a few more details to the description of this issue. There is now a PR open covering the main points described there, including making sure the user matches the domain of an organization during the first broker login and make sure only a broker associated with an organization can add the federated user as an organization member.
