### ISSUE TITLE
LDAP group attributes not showing up in the UI

### ISSUE THREAD

**Issue by fostermi** [keycloak/keycloak#28287]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I've added new attributes to a group in LDAP via an ldif file: "owner" and "description". LDAP now shows these fields correctly no problem.

I've configured the groups mapper in the LDAP user federation such that the mode is "LDAP_ONLY" and the "Mapped Group Attributes" field shows a comma separated list of group attributes I want to display: "owner,description".

I then sync "LDAP groups to Keycloak". 

However, navigating to "Groups" and then selecting my group and clicking the "Attributes" tab, the additional attributes are not there.

### Version

22.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

LDAP group attributes configured in the group mapper show up for each group where those attributes exist.

### Actual behavior

No group attributes from LDAP are showing up in the Attributes tab.

### How to Reproduce?

Create a new realm.
Add an LDAP source as a User Federation
Create a groups mapper
Define the additional group attributes that should display in Keycloak.
Browse the groups and click on the Attributes tab.

**Comment by fostermi** [comment]
Ok, thanks for the clarification. Testing with version 24.0.2, which is the version listed in https://www.keycloak.org/getting-started/getting-started-docker, I'm still not seeing this new attribute under the Attributes tab of the group. Any ideas why this wouldn't be working?

**Comment by ssilvert** [comment]
This is not actually a UI issue as the UI will just display whatever attributes are defined for the group.  Moving to core IAM team.

**Comment by sguilhen** [comment]
I can't reproduce the issue in 24.0.2 - I've added both owner and description to two groups in an OpenLDAP server, configured the group mapper accordingly (set `Mapped Group Attributes`  to `description,owner`), then re-sync'ed the groups. When I select the groups I can see both attributes in the `Attributes` tab.

**Comment by fostermi** [comment]
What mode is your `groups` mapper? Mine is `LDAP_ONLY`. This is definitely a thing on my existing infra on a new realm and 389ds server for testing. Is there any debugging that can be enabled to find out why its not working for me?

**Comment by fostermi** [comment]
I was able to deploy a new container and enabled TRACE on it. Here's the only relevant thing I've seen so far:
```
{"log":"2024-04-03 21:19:02,636 TRACE [org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore] (executor-thread-2) Found ldap object and populated with the attributes. LDAP Object: LDAP Object [ dn: cn=admin,ou=Groups,dc=example,dc=com , uuid: a81ed201-adda11eb-b52a8837-dddc5432, attributes: {uniqueMember=[cn=empty-membership-placeholder, uid=jdoe,ou=People,dc=example,dc=com], cn=[admin]}, readOnly attribute names: [], ranges: {} ]\n","stream":"stdout","time":"2024-04-03T21:19:02.636682029Z"}
```
The `readOnly` attributes list looks empty, which is either a list of attributes returned by LDAP or a list of attributes to look for?

**Comment by sguilhen** [comment]
I was using `READ_ONLY` Mode, but changing it to `LDAP_ONLY` still worked just the same. With trace enabled, here's what I get when synchronizing the groups to Keycloak:

```
LdapOperation: search
 baseDn: ou=RealmRoles,dc=keycloak,dc=org
 filter: (&(objectclass=groupOfNames))
 searchScope: 2
 returningAttrs: [cn, owner, description]
 resultSize: 2
took: 3 ms

2024-04-03 22:56:38,690 TRACE [org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore] (executor-thread-3) Found ldap object and populated with the attributes. LDAP Object: LDAP Object [ dn: cn=ldap-admin,ou=RealmRoles,dc=keycloak,dc=org , uuid: 101516bf-d701-4853-9722-e8690c3cb014, attributes: {owner=[uid=admin,ou=system], description=[LDAP Admins Group], cn=[ldap-admin]}, readOnly attribute names: [], ranges: {} ]
2024-04-03 22:56:38,690 TRACE [org.keycloak.storage.ldap.idm.store.ldap.LDAPIdentityStore] (executor-thread-3) Found ldap object and populated with the attributes. LDAP Object: LDAP Object [ dn: cn=ldap-user,ou=RealmRoles,dc=keycloak,dc=org , uuid: e74156e8-684c-4660-959f-ef8cb4b64df8, attributes: {owner=[uid=admin,ou=system], description=[LDAP Users Group - Updated], cn=[ldap-user]}, readOnly attribute names: [], ranges: {} ]
```

As you can see the LDAP objects that were returned both contain the `owner` and `description` in the list of attributes.

**Comment by fostermi** [comment]
Thanks for looking into this. My apologies, though, I realized I was not connecting to my test LDAP server listening on a different port. After connecting to the correct LDAP server, indeed, the group attributes show up. Sorry to waste your time. :sigh:

**Comment by sguilhen** [comment]
No worries @fostermi , glad you found out what was going on!
