### ISSUE TITLE
scroll bar is missing inn clients view keycloak admin GUI

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#28284]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Clients/Users page is overflow -> Hidden the info of users/clients and do not display Delete button.

Attached the exact view and improper view.

A scroll bar is missing and not able to view export or delete option menu
![Screen Shot 2024-03-18 at 12 31 12 PM](https://github.com/keycloak/keycloak/assets/20001725/42302865-87e7-49d1-81d0-4298a082b607)

Sample Example is a group screen
![Screen Shot 2024-03-18 at 12 31 29 PM](https://github.com/keycloak/keycloak/assets/20001725/4a1936a9-ad63-4712-be40-69d926a5ea81)

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The Clients view screen should include a scroll bar  as described in the bug

### Actual behavior

ScrollBar is missing the clients screen

### How to Reproduce?

Create a client with big name and try to scroll the page to look at the whole client name.

**Comment by ssilvert** [comment]
I'm setting this to `priority/important` because it probably affects other tables as well.  I think the best solution here is not to do scroll bars but rather to limit the column width and use an ellipsis (`...`) for strings that exceed that width.  Then allow mouseover to show the entire string.

**Comment by pravsjv** [comment]
@ssilvert Agree! ellipsis would be a good choice.

**Comment by stianst** [comment]
@edewit moving back to "Ready for backport" as this is still marked to be backported to 22.0 and 24.0. From what I can tell this has only been merged into main.
