### ISSUE TITLE
LDAP user operational attribute lastLoginTime are not propagating to a user's attributes tab

### ISSUE THREAD

**Issue by fostermi** [keycloak/keycloak#28288]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I've configured an LDAP source for User Federation.

I've created an additional mapper "lastLoginTime" and mapped it to the operational attribute "lastLoginTime" in LDAP and selected "Always Read Value From LDAP".

However, navigating to a user and selecting the Attributes tab, this operational attribute "lastLoginTime" does not appear. Other operational attributes such as "creationTime" do appear. Other non-operational attributes, such as "displayName" do appear.

### Version

22.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

LDAP lastLoginTime is added to a users attribute tab along with other operational attriburtes, "creationTimestamp" and "modifyTimestamp".

### Actual behavior

lastLoginTime is not displaying in a user's attribute tab.

### How to Reproduce?

Create a new Realm.
Add an LDAP source as a User Federation, one with 
Create an attribute mappers for "lastLoginTime" mapped to the ldap attribute "lastLoginTime" when that is configured.
Synch the user directory.
The only operational attributes returned are "creationTimestamp" and "modifiedTimestamp".

**Comment by fostermi** [comment]
22.0.3 was released 6 months ago! How can that not be supported?

**Comment by ssilvert** [comment]
> 22.0.3 was released 6 months ago! How can that not be supported?

Free support is given only on the latest community branch.  It's a community effort to answer questions and get bugs fixed.  

If you can reproduce on the nightly build, there is a much greater chance that your problem will be addressed.
https://github.com/keycloak/keycloak/releases/tag/nightly

If you need ongoing paid support on a verified stable release, see Red Hat Build of Keycloak (RHBK).  https://access.redhat.com/products/red-hat-build-of-keycloak

**Comment by fostermi** [comment]
Ok, thanks for the clarification. Testing with version 24.0.2, which is the version listed in https://www.keycloak.org/getting-started/getting-started-docker, I see the new custom attribute label "lastlogintime" in the User's "Details" page. However, the value is not getting populated from LDAP (i.e. Apr 1, 2024, 10:41:11 AM MDT (20240401164111Z)). I would assume that KC would just be able to pull this attribute from LDAP just like any other attribute, including operational ones. Is there something that I'm missing?

**Comment by fostermi** [comment]
The goal here is to use a CoS in LDAP to lock inactive accounts after a certain amount of time. I need to do this in LDAP as we have applications that access authentication directly with LDAP. 

Supplementary question:
When a user authenticates to any configured client, including their account console in KC, shouldn't that register an LDAP bind and log a new lastlogintime stamp? I'm not seeing LDAP update this when a user successfully logs into KC.

**Comment by fostermi** [comment]
Thanks for looking into this. My apologies, though, I realized I was not connecting to my test LDAP server listening on a different port. After connecting to the correct LDAP server, indeed, the group attributes show up. Sorry to waste your time. :sigh:
