### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by fateson** [keycloak/keycloak#28300]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

when i add new user，input Upper username ，save success 。username is Lower，why？？？

### Version

all version

### Regression

- [ ] The issue is a regression

### Expected behavior

input lower username

### Actual behavior

become upper username

### How to Reproduce?

simple operate。simple operate，simple operate

**Comment by shawkins** [comment]
see #28302
