### ISSUE TITLE
Custom Attribute version 24.0.1

### ISSUE THREAD

**Issue by syedshahwar7** [keycloak/keycloak#28315]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Can not find the custom attributes tab in user in keycloak version 24.0.1

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Custom attributes tab in user should be visible

### Actual behavior

Custom attributes tab in user is not be visible

### How to Reproduce?

Move to user and check for available tabs

**Comment by bbaia** [comment]
@syedshahwar7 @stianst @jonkoops 

This is a bug, I have the same problem :
The 'Attributes' tab is not visible in 24.0.1 if you create the link between client et client scope in that version.

If the link has been created in a previous version, and then, you migrate to 24.0.1, you will not have the issue.
