### ISSUE TITLE
org.keycloak.documentation.test.ExternalLinksTest fails with incorrect status code reported back in the results

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#28330]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

In the below run and other scheduled Docs runs

https://github.com/keycloak/keycloak/actions/runs/8507434651/job/23299272388

```
org.keycloak.documentation.test.ExternalLinksTest
Error:  checkExternalLinks{String}[2]  Time elapsed: 65.593 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Broken links (7) in guide 'release_notes': 
		- https://github.com/nngo (invalid status code 429)
		- https://github.com/dasniko (invalid status code 429)
		- https://github.com/rhyamada (invalid status code 429)
		- https://github.com/jonkoops (invalid status code 429)
		- https://github.com/fredbi (invalid status code 429)
		- https://github.com/daniel-ac-martin (invalid status code 429)
		- https://github.com/fiji-flo (invalid status code 429)
```

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

The links listed by the test are returning a valid status code of 200

### Actual behavior

The test fails complaining about the status code was invalid

### How to Reproduce?

watch the Keycloak Docs CI for recent failures in the ExternalLinksTest

https://github.com/keycloak/keycloak/actions/workflows/documentation.yml

### Anything else?

Running this on my local returns a status code of 200

```
> curl -kI https://github.com/nngo
HTTP/2 200
server: GitHub.com
date: Mon, 01 Apr 2024 15:22:55 GMT
```

**Comment by ahus1** [comment]
The code 429 represents "Too Many Requests", which means we're hitting an API limit.

Either we ignore this code, or we might be able to use an the GitHub token from the action get around the API limit.

**Comment by stianst** [comment]
I'd say let's just ignore these links. Perhaps just ignore https://github.com/* in https://github.com/keycloak/keycloak/blob/main/docs/documentation/tests/src/test/resources/ignored-links?
