### ISSUE TITLE
Provide a dedicated way of updating Quarkus classloading indices

### ISSUE THREAD

**Issue by mruzicka** [keycloak/keycloak#28336]
### Description

There are scenarios in which outdated Quarkus classloading indices can result in failures during Keycloak build/start or provided classes being ignored/ineffective. Examples of such scenarios are:
1. #26396
2. providing implementations of `io.smallrye.config.ConfigSourceInterceptor` which need to be discovered early to be effective

For these scenarios a dedicated way of updating of the classloading indices is desirable.
The currently documented way of achieving that is suboptimal as it re-builds the indices twice - see #28320.

IMHO It would be ideal if this wasn't necessary at all - for example if the Keycloak's `build` command did that automatically, but I'm not sure if that's feasible especially in the case 2. mentioned above.

### Motivation

In our setup we provide an implementation of `io.smallrye.config.ConfigSourceInterceptor`. Without first rebuilding the Quarkus class loading indices this interceptor is not used.

**Comment by shawkins** [comment]
> The currently documented way of achieving that is suboptimal as it re-builds the indices twice - see https://github.com/keycloak/keycloak/pull/28320.

> IMHO It would be ideal if this wasn't necessary at all - for example if the Keycloak's build command did that automatically, but I'm not sure if that's feasible especially in the case 2. mentioned above.

We talked this over want to just document adding --help to the workaround so that it runs just a single vm invocation. Adding a new kc.sh/bat option or trying to make the full build command run in a way that cleans the indecies does not seem worth the effort. 

@mruzicka can you update the pr to use --help instead of build?
