### ISSUE TITLE
ConditionalLoaAuthenticator documentation incorrect re: unauthenticated users.

### ISSUE THREAD

**Issue by aph3rson** [keycloak/keycloak#28341]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When using the ConditionalLoaAuthenticator, the documentation in Keycloak is as-follows:

> Flow is executed only if the configured LOA or a higher one has been requested but not yet satisfied.

However, this is not true if the current user has not reached any authentication level. This can be seen by this logging line:

https://github.com/keycloak/keycloak/blob/96672a2a6d9cdbe7cf9d4499c63ad6c7ed07f3b0/services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalLoaAuthenticator.java#L61

Here's an example of me seeing this in my Keycloak stack - the application requires LoA `10`, and the authenticator instead responded `true` (despite being set at `40`).

```txt
# journalctl -xefu keycloak | grep ConditionalLoa
Apr 02 05:14:44 [snip] kc.sh[9575]: TRACE [org.keycloak.authentication.authenticators.conditional.ConditionalLoaAuthenticator] (executor-thread-57) Condition 'MFA_ALWAYS' evaluated to true due the user not yet reached any authentication level in this session, configuredLoa: 40, requestedLoa: 10
```

This appears to have been introduced in https://github.com/keycloak/keycloak/commit/93bba8e338d7c785a4e2968fa54ce312be35ddb4, note that the logic [here](https://github.com/keycloak/keycloak/commit/93bba8e338d7c785a4e2968fa54ce312be35ddb4#diff-335ef41c05942a2949a8949236021b1a8398db8f6eefda5e1bdb75b18ef9bc08L51-L52) is different.

Worse yet, debugging this requires turning on `TRACE`-level logging, which results in a significant amount of logging output.

### Version

23.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

The condition should have returned false - even though the user is not authenticated, the LoA requested is less than the configured LoA.

### Actual behavior

The condition returns `true` always, because the user does not have a session yet.

### How to Reproduce?

This should be reproduceable with any version of Keycloak after 18.0.0.

1. Create an authentication flow, and add a Conditional subflow as the first step.
2. Set the condition to an arbitrary LoA >= 2.
3. Perform the authentication flow requesting LoA 1.
4. Observe that the LoA condition passes as `true`, even though the LoA was lower.

### Anything else?

Conditional LoA could use some additional documentation overall. It's unclear if this is expected or not.
I'm using the documentation in Keycloak directly as a source of truth.

Note that my desire here is to have four LoAs:

- `MFA_ALWAYS` - This application requires MFA (and reauthentication) every time it is used. 
- `MFA_MANDATORY` - This application requires MFA (but not reauthentication) every time.
- `MFA_SELECTIVE` - This application may require MFA depending on external factors (e.g. the client's IP address).
- `1FA` - This application does not require MFA in any fashion.

Tagging some folks that worked on #10205 / #10511 which may have introduced this issue: @mposolda @stianst @mabartos

**Comment by graziang** [comment]
Hi @aph3rson, if I understand correctly, the point here is that the first conditional LoA authenticator always returns `true`, because the user doesn't have a session yet (`currentAuthenticationLoa` is set to `-1`) while the help text of the "`Condition - Level of Authentication`" authenticator text mentions: "_Flow is executed only if the configured LOA or a higher one has been requested but not yet satisfied._"
I think the correct authentication flow configuration for step-up authentication should be with incremental loa value with lower level first. In your example if you have a condition with loa 40 and a condition with loa 10 the condition with loa 40 should not be configured as first. Of course I could be wrong, @mposolda WDYT?

**Comment by mposolda** [comment]
@graziang Agree with what you mentioned.

@aph3rson The 1st configured subflow with "Condition - Level of authentication" is always triggered during 1st authentication of the user (when SSO does not yet exists) as the user does not yet have any level. The subflows are supposed to be ordered from lowest to the higher and the 1st subflow is supposed to contain the authenticators, which you consider as "minimal" authenticators for your deployment.

I've sent PR for the documentation to clarify this.

**Comment by abamuc** [comment]
Hi, I'm not sure if this is just a documentation issue: 

If there are two ways to authenticate users, one is to get an mail )level 1), and the other is to log in by username and password (level 2), there is no way to avoid getting an mail anymore.

Could we make it optional that "no loa reached yet" triggers the condition in any case?

Thanks, Andi
