### ISSUE TITLE
PodTemplateTest assertions are ignored

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#28370]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Assertions in `PodTemplateTest#testAdditionalOptionTruststorePath`[1] and `PodTemplateTest#testImageForceOptimized`[2] are ignored as the `Assertions.assertThat()` require a terminal operation, which is not present. InteliJ IDEA shows it's ignored. 

I tried to put the terminal `isTrue()` op, but these tests failed, so I assume it's gonna be a bigger issue with that.
See logs with these changes: https://github.com/keycloak/keycloak/actions/runs/8525433614/job/23352622664?pr=27629

[1] https://github.com/keycloak/keycloak/blob/95277db4e0883112565c2778862b4a95a8587d3e/operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java#L406
[2] https://github.com/keycloak/keycloak/blob/95277db4e0883112565c2778862b4a95a8587d3e/operator/src/test/java/org/keycloak/operator/testsuite/unit/PodTemplateTest.java#L422

### Version

999

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests are properly executed and passing

### Actual behavior

Assertions are ignored

### How to Reproduce?

Execute `PodTemplateTest#testAdditionalOptionTruststorePath` and `PodTemplateTest#testImageForceOptimized` tests

**Comment by mabartos** [comment]
@shawkins I tried to put the `isTrue()` terminal op, but these tests failed, so I assume it'd need some investigation. 

@shawkins Could you please take a look at it, as you're the author?

**Comment by shawkins** [comment]
@mabartos https://github.com/keycloak/keycloak/pull/28373
