### ISSUE TITLE
Password denylist Doesn't Work As Expected

### ISSUE THREAD

**Issue by cmiles74** [keycloak/keycloak#28381]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I am using a password blacklist from the SecLists project, it can be found here:
- [10-million-password-list-top-1000000.txt](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt)

I have configured my password policy in Keycloak like so:
> "passwordBlacklist(10-million-password-list-top-1000000.txt) and length(8) and lowerCase(1) and upperCase(1) and digits(1) and specialChars(1) and passwordHistory(3) and forceExpiredPasswordChange(90)"

When I test this out by changing my password, the blacklist function seems pretty hit-or-miss. Sometimes a password will be refused, Keycloak will let me know that it's in the blacklist. Other times the password will be changed even though it is present in the blacklist. 

Because my rules include a capital letter, I have been testing with the following passwords:
- Password1!
- 1Password!

Should the passwords "1Password!", "1Password!" and "1PASSword!" all be blacklisted? I've read the documentation over a couple of times, I believe this may be a bug.

### Version

23.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The following passwords should all be blacklisted:
- 1password!
- 1Password!
- 1PASSword!

The blacklist includes the following text:
```
$ ack Password 10-million-password-list-top-1000000.txt|grep !                                                                                 
Password1!                                                                                
1Password!                                                                                
Password!
```

### Actual behavior

These passwords are accepted without producing an error.

### How to Reproduce?

If you use the blacklist and configuration settings detailed above, you will still be able to set these blacklisted passwords.

**Comment by graziang** [comment]
From my test:
- `Password1!` is always blacklisted
- `1Password!` is never blacklisted

Keycloak uses Bloom filter to filter blacklisted passwords, I think the problem may be [here]( https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/policy/BlacklistPasswordPolicyProvider.java#L49), lower case password messing up hashes based check with Bloom filter.

**Comment by rmartinc** [comment]
Hi @cmiles74!

As the [documentation](https://www.keycloak.org/docs/latest/server_admin/#password-blacklist) says the blacklist file should be in lower case. Your grep shows password with the capital `P` and that can make the comparison fail (because initial password is lower-cased to check). Can you please try converting the file to lower case and configuring the blacklist policcy with the new file?

```
sed 's/\([A-Z]\)/\L\1/g' 10-million-password-list-top-1000000.txt |sort -u > 10-million-password-list-top-1000000-lc.txt
```

Also you can decrease the probability if it still fails (`--spi-password-policy-password-blacklist-false-positive-probability=0.00001`).

**Comment by cmiles74** [comment]
Thank you for your quick and clear response. You are right, I am not sure how I managed to misread this. The "case insensitive" managed to register but the "all passwords must be lowercase" flew right past me.
> Keycloak compares passwords in a case-insensitive manner. All passwords in the blacklist must be lowercase.

Changing all the letters to lower case isn't all that difficult. You provided a `sed` example above, I used `tr` to get a similar one-liner
> tr '[:upper:]' '[:lower:]' < 10-million-password-list-top-1000000.txt > 10-million-password-list-top-1000000-lowecase.txt

Even so, this seems likely to trip someone else up in the future. I'm willing to put a PR together if you think it might help. I have three ideas, from most to least disruptive, that I think might help others who also have trouble with reading. 🤦

I took a closer look at how this works this moring, I can see that we lowercase the incoming password before we compare it to the blacklist.
https://github.com/keycloak/keycloak/blob/4ec9fea8f734844f4563bba41b017edfbf4f3a78/server-spi-private/src/main/java/org/keycloak/policy/BlacklistPasswordPolicyProviderFactory.java#L285-L287

It might make sense to leave the password as is, my thinking is that case sensitivity is a part of the password. For instance we have a password policy in Keycloak that requires a certain number of upper or lower case letters. This would be a significant change and would be especially troublesome for people who have lower-cased all of the passwords in the blacklist.

Another approach might be to lowercase the passwords in the file as we read them.
https://github.com/keycloak/keycloak/blob/4ec9fea8f734844f4563bba41b017edfbf4f3a78/server-spi-private/src/main/java/org/keycloak/policy/BlacklistPasswordPolicyProviderFactory.java#L328-L332

I believe we could map over the lines, lowercase them and then put them into the filter.
```java
br.lines().map(String::toLowerCase).forEach(filter::put);
```

Lastly, if retaining the current behavior is important, we could count those strings which have a lowercase letter and then report that as a warning on the console. I was thinking something like a warning that reads "895 lines ignored, includes lowercase letters".

Let me know what you think, thank you again for your help on this. 🙂

**Comment by rmartinc** [comment]
@cmiles74 I remember similar suggestions to what you are proposing. IMHO the first suggestion would mean a very big change and it would need a flag (similar to the positive probability config option or even inside the policy config). The second suggestion is less dramatic and would mean lowering the case before inserting the pasword into the filter as you mention. Both changes are compatible. But that would be an enhancement and not a bug. You can work on it if you want.

**Comment by cmiles74** [comment]
Lower-casing the passwords as they are added to the filter seems like it would deliver the most value and the least disruption. I will get a PR out in the next couple of days.
