### ISSUE TITLE
New username-password policy check is reversed

### ISSUE THREAD

**Issue by csakyzsolt** [keycloak/keycloak#28389]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

The `NotContainsUsernamePasswordPolicyProvider` class that implements the new password policy incorrectly checks whether the password contains the username or not. [This comment](https://github.com/keycloak/keycloak/commit/757c524cc508a662289284b85223a2e3c9a08fa9#r140532594) describes the issue inline.

If not relevant, please ignore this.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

A `PolicyError` should be raised if the user's password contains their username.

### Actual behavior

An error is raised only when the user's username contains their password.

### How to Reproduce?

I did not try reproducing the bug, the error seems clear from the code, although it should be reproducible by enabling the password policy in question, then creating a user named _Bob_ and setting its password to _Bob123_. The error would not be raised.

**Comment by sguilhen** [comment]
Looks like a bug to me, thanks @csakyzsolt .

@pedroigor Do you think we should flag it as important?

**Comment by csakyzsolt** [comment]
I'm glad I could help!
