### ISSUE TITLE
CRD for client scopes

### ISSUE THREAD

**Issue by krasv** [keycloak/keycloak#28405]
### Description

Client scopes are powerful to reduce token to a minimum of content for specific usage target.

The keycloak API supports scope definition and token requests considers scopes also.

Unfortunately k8s management of client scopes is absent.

### Request:
* enhance CRD for client scope specification
* enhance operator handling the resource

**Comment by jonkoops** [comment]
I am sorry, but this request really doesn't have enough information to go on. You'll really have to write a bit more detailed of a proposal if you expect this to land. Feel free to log a new issue with more detailed information.
