### ISSUE TITLE
Unclosed span bracket in register.ftl

### ISSUE THREAD

**Issue by Firelods** [keycloak/keycloak#28409]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Unclosed span bracket in register.ftl

### Version

24.0.2-0

### Regression

- [ ] The issue is a regression

### Expected behavior

Closed span bracket

### Actual behavior

Unclosed span bracket

### How to Reproduce?

Open register.ftl

**Comment by jonkoops** [comment]
@Firelods would you be interested in back-porting this to the 24 release? You can do so by cherry-picking the commit merged into `main` and opening a pull request targeting the `release/24.0` branch.
