### ISSUE TITLE
BackChannel Logout for Update_Password AIA has only one sessionId

### ISSUE THREAD

**Issue by Jayashree-Rajendran** [keycloak/keycloak#28417]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

1)	Establish 4 active sessions of User1 in the same client. Corresponding sessionIds are. 
2)	Change password of User1 from session1 using AIA (below URL) And enabled “Sign Out from other devices”
3)     In Keycloak console, I see other sessions are removed, only one active session present (session where password updated successfully)
4)     But one single backchannel logout request being performed to client, in that I see only one sid present in the Logout_Token. Client will terminate only this sid internally, other 2 sessions info will not be cleaned up.
It is impossible for the client to identify which of the sessions to actively terminate, as seemingly only one of the active sessions in Keycloak will be submitted as a backchannel logout request.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I would have expected one request per session to get all three SID logout requests in the client

### Actual behavior

Keycloak sending only one backchannel logout which has only one of these sid

### How to Reproduce?

Same as mentioned in description

**Comment by graziang** [comment]
Hi @Jayashree-Rajendran, I'm not sure I understand correctly, in step 1 do you mean 4 different sessions (with 4 different session ids) using the same client?
I am not able to reproduce the bug, in my test backchannel logout is called for each remaining session, can you better detail the steps to reproduce it?
