### ISSUE TITLE
Keycloak is not returning proper error message for PUT /users admin API

### ISSUE THREAD

**Issue by Jayashree-Rajendran** [keycloak/keycloak#28416]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Trigger  PUT /users admin API to change user's password
PUT /admin/realms/{realm}/users/{id}
Send password which is same as previous password. As per my password policy, this request will fail, because new password should not be same as past 3 passwords. 

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should send exact error message as follows
 {"error":"invalidPasswordHistoryMessage",
"error_description":"Invalid password: must not be equal to any of last 3 passwords."}

### Actual behavior

Keycloak is responding 400 response code with very generic error message as follows
{"errorMessage":"Could not update user!"}

### How to Reproduce?

Trigger  PUT /users admin API to change user's password
PUT /admin/realms/{realm}/users/{id}
Send password which is same as previous password. As per my password policy, this request will fail, because new password should not be same as past 3 passwords

**Comment by sguilhen** [comment]
Yeah, the `updateUser` method in the `UserResource` endpoint should do something similar to what we find in `resetPassword` in the same enpoint when handling the `ModelException` that is thrown when the password policy is not met.

I'll add this to the backlog, but a PR from would be most welcome as we won't prioritize this for the moment.

**Comment by etiksouma** [comment]
@sguilhen  I can work on this.

**Comment by sguilhen** [comment]
Excellent, @etiksouma , thank you. Let me know when the PR is up and I will prioritize reviewing it!

**Comment by etiksouma** [comment]
@sguilhen done
