### ISSUE TITLE
SSO Session Idle: session is still active after session idle time expired

### ISSUE THREAD

**Issue by Jayashree-Rajendran** [keycloak/keycloak#28418]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I am trying SSO Session Idle scenario
I have:
Token Lifespan: 5 minutes
SSO Session Timeout: 30 minutes
SSO Session Max: 10 hours

If I create session at for example 20:00 then I will have:
access_token expiration to 20:05
refresh_token expiration to 20:30.

Problem is session after 20:30 (user is inactive). It should be invalided but it is not. The session is still valid and I see session valid in administration console too. But the session will invalided next +2 minutes at 20:32.

After doing some research it seems this is standard Keycloak behavior where it keeps 2 min allowance for synchronization between Keycloak cluster and there is no way to change.
https://www.keycloak.org/docs/latest/server_admin/index.html#_idle_timeouts_note

But my environment is not using cluster.  But still it adds 2 mins buffer.
How i can avoid this 2 mins buffer?

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

For non-cluster env, Keycloak should not add 2mins buffer to remove session when session idle time is reached. 
I would suggest that this can be made as a configuration option to set the deployment type.

### Actual behavior

Irrespective of how keycloak is deployed (cluster or non-cluster), 2 mins buffer is added to session idle time

### How to Reproduce?

As mentioned in description

**Comment by mposolda** [comment]
As you pointed, ATM it is not possible to remove the extra-minutes.

I am not sure if we should allow to remove this as don't know about the side-effects of this regarding cluster/cross-dc environment. This might be addressed by the "persistence sessions", but not 100% sure.

@ahus1 Adding also label `team/cross-dc` as this is likely related to your area.

**Comment by ahus1** [comment]
IMHO this 2 minutes are difficult to explain to users, and no longer needed for persistent sessions given the test results and the way we implement it. 

While this is relatively simple to remove from the check, it needs some changes in the test suite where several timeouts are calculated based on those two minutes. 

I'll add it to the epic persistent sessions to have this removed, possibly for KC26, but only when persistent sessions are enabled.

**Comment by Jayashree-Rajendran** [comment]
Any update on this issue?
