### ISSUE TITLE
MIME errors with custom theme following the instructions from the docs

### ISSUE THREAD

**Issue by Sax388** [keycloak/keycloak#28432]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

There are errors in the browser console (tested with Edge and Firefox).
![image](https://github.com/keycloak/keycloak/assets/110223653/04e6a2f4-95b0-420d-953f-379bf65146d9)

```
Refused to apply style from 'http://localhost:8080/resources/qipmp/login/mytheme/css/tile.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
auth:1  Refused to apply style from 'http://localhost:8080/resources/qipmp/login/mytheme/css/styles.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
auth:1  Refused to apply style from 'http://localhost:8080/resources/qipmp/login/mytheme/css/styles.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
auth:1  Refused to apply style from 'http://localhost:8080/resources/qipmp/login/mytheme/css/tile.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

No errors in the console

### Actual behavior

Errors in the console

### How to Reproduce?

- Add [mytheme.zip](https://github.com/keycloak/keycloak/files/14864133/mytheme.zip) to the `themes` folder
- Start keycloak with `.\kc.bat start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false` (from the [docs](https://www.keycloak.org/docs/latest/server_development/index.html#creating-a-theme))
- Create a realm and apply the theme `mytheme` to the login page
- Browse to `http://localhost:8080/admin/<yourRealmName>/console/`, see the theme is applied and there are two errors in the console

### Anything else?

It already happened in version 23.

**Comment by rmartinc** [comment]
Hi @Sax388!

This is because you are adding those css in the theme.properties file but they are not in the zip:

```properties
parent=keycloak
import=common/keycloak

styles=css/login.css css/styles.css css/tile.css css/loginCustom.css
```

As [the documentation says](https://www.keycloak.org/docs/latest/server_development/index.html#_theme_stylesheet) the `styles` is used to add css files to the theme.  But if you don't include those css there is a 404 and the error you mention. The issues dissapear if you just remove them from that prop:

```properties
styles=css/login.css css/loginCustom.css
```

If you don't say anything different I will close the issue as not an issue.

**Comment by Sax388** [comment]
Umm, I'm actually not sure. I thought both `styles.css` and `tile.css` where also files present in the parent theme.
But when I look at https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/keycloak/login/resources/css or even https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources/theme/keycloak.v2/login/resources/css (here at least I see a `styles.css`) I see that there is only one file in the respective css resources folder.

It seems I have to check where I've got these files from and what I wanted with them.

**Comment by rmartinc** [comment]
The file tile.css is not in any theme, and styles.css is in keycloak.v2 but not in the keycloak you are inheriting.  But if you remove them from your theme the error is gone and the aspect seems to be OK.

**Comment by Sax388** [comment]
Yes, you're completely right. Thanks a million!
