### ISSUE TITLE
Declarative User Profile: The use of the "select-radiobuttons" with options validation display is broken

### ISSUE THREAD

**Issue by Nuscly** [keycloak/keycloak#28443]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Starting with Keycloak 24.0.2, when creating a user profile with a "select-radiobuttons" with options validation "on" and "off", in the display the first option is rendered as "n" and the second one is empty.

Here is the display in the keycloak admin, user detail page.
![image](https://github.com/keycloak/keycloak/assets/1038299/3beb19ca-a2aa-44d3-a1d0-8a8b469794cb)

The problem exist too in the account page for the personnal info, with exactly the same bug.

Please note that the problem was not here with Keycloak 24.0.1.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

The user is attribute multi select is displayed with the values of the multiselect, in this example "on" and "off" for instance.

### Actual behavior

The rendering of the HTML is broken:
* the label of the first value is "n" instead of "on".
* the label is missing for the second attribute.
```
<div class="pf-c-form__group-control">
    <div class="pf-c-radio">
        <input id="on" data-testid="on" class="pf-c-radio__input" type="radio" aria-invalid="false"
               data-ouia-component-type="PF4/Radio" data-ouia-safe="true"
               data-ouia-component-id="OUIA-Generated-Radio-1" value="on" data-form-type="other">
        <label class="pf-c-radio__label" for="on">n</label>
    </div>
    <div class="pf-c-radio pf-m-standalone">
        <input id="off" data-testid="off" class="pf-c-radio__input" type="radio" aria-invalid="false"
               data-ouia-component-type="PF4/Radio" data-ouia-safe="true"
               data-ouia-component-id="OUIA-Generated-Radio-2" value="off" checked="">
    </div>
</div>
```

### How to Reproduce?

Create a user attribute of type "select-radiobuttons" with "on" and "off" as valid values.

Here is a configuration of the concerned attribute, here named "optin".
![image](https://github.com/keycloak/keycloak/assets/1038299/da34b85d-65c7-49ab-87c6-a5ed9faa0253)

Here is the complete save of the user profile json config.
```
{
  "attributes": [
    {
      "name": "username",
      "displayName": "${username}",
      "validations": {
        "length": {
          "min": 3,
          "max": 255
        },
        "username-prohibited-characters": {},
        "up-username-not-idn-homograph": {}
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "email",
      "displayName": "${email}",
      "validations": {
        "email": {},
        "length": {
          "max": 255
        }
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "firstName",
      "displayName": "${firstName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "lastName",
      "displayName": "${lastName}",
      "validations": {
        "length": {
          "max": 255
        },
        "person-name-prohibited-characters": {}
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    },
    {
      "name": "optin",
      "displayName": "Product",
      "validations": {
        "options": {
          "options": [
            "on",
            "off"
          ]
        }
      },
      "annotations": {
        "inputHelperTextAfter": "Test text",
        "inputType": "select-radiobuttons"
      },
      "required": {
        "roles": [
          "user"
        ]
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin",
          "user"
        ]
      },
      "multivalued": false
    }
  ],
  "groups": [
    {
      "name": "user-metadata",
      "displayHeader": "User metadata",
      "displayDescription": "Attributes, which refer to user metadata"
    }
  ],
  "unmanagedAttributePolicy": "ENABLED"
}
```

**Comment by pedroigor** [comment]
@jonkoops Can you spot anything strange here in the UI?

**Comment by jonkoops** [comment]
Yeah, the bug is that be default the `option` [will be used](https://github.com/keycloak/keycloak/blob/a0cf09e8991e17ea626b4bd041bde631515e78d8/js/libs/ui-shared/src/user-profile/OptionsComponent.tsx#L36) if no `inputOptionLabels` are configured. Which is then for [some reason truncated](https://github.com/keycloak/keycloak/blob/a0cf09e8991e17ea626b4bd041bde631515e78d8/js/libs/ui-shared/src/user-profile/utils.ts#L28).

Likely:
```tsx
const isBundleKey = (displayName?: string) => displayName?.includes("${");
export const unWrap = (key: string) => key.substring(2, key.length - 1);
```

Should be:

```tsx
const isBundleKey = (displayName?: string) => displayName?.includes("${");
export const unWrap = (key: string) => isBundleKey(key) ? key.substring(2, key.length - 1) : key;
```

@edewit WDYT?

**Comment by edewit** [comment]
@jonkoops this function already exists it's called label that is what should be used + it seems that you can either have an array with options or an array with values, can't really find this back in the docs though

**Comment by pedroigor** [comment]
@jonkoops @edewit Thanks.

**Comment by jonkoops** [comment]
> this function already exists it's called label that is what should be used + it seems that you can either have an array with options or an array with values, can't really find this back in the docs though

Ok, then AFAIK there should be no reason to use `unWrap()` directly anywhere at all right? Perhaps we can replaces all instances of it with `label()` and no longer export  `unWrap()` directly to avoid future mistakes.

**Comment by Nuscly** [comment]
Hello, I checked on nightly, everything is working well, and the translations too. Thanks.
