### ISSUE TITLE
Memory leak when the HTTP connection is force-closed by the client while the request body is being read

### ISSUE THREAD

**Issue by aldiyar04** [keycloak/keycloak#28444]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

1) Send a direct access grant request to _/auth/realms/{{realm}}/protocol/openid-connect/token_.
2) Force-close the HTTP connection (e.g., by sending a TCP Reset (RST) packet to replicate ECONNRESET) before a response is received, while Keycloak is still reading the request body (form parameters).
3) This will result in either _java.nio.channels.ClosedChannelException_ or _io.vertx.core.http.HttpClosedException_ being thrown, depending on the place in the code that is executed at the moment of the connection closure.

Replicating this many times significantly increases the memory usage of a Keycloak instance. If a large number of such exceptions is thrown within a short period, there is a spike in the memory usage at that time. Each time we conduct such a "load test" (replication of ECONNRESET) **with the same load**, the memory usage increases, and in between, when the Keycloak is at rest (not serving any requests), the memory usage remains at the same level and memory is not released back.

The stack traces of the exceptions are attached.

[ClosedChannelException.json](https://github.com/keycloak/keycloak/files/14872628/ClosedChannelException.json)
[HttpClosedException.json](https://github.com/keycloak/keycloak/files/14872637/HttpClosedException.json)

### Version

21.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak releases memory back when HTTP connections are forcibly closed by the client.

### Actual behavior

Keycloak does not release memory back when HTTP connections are forcibly closed by the client.

### How to Reproduce?

[KeycloakMemoryLeakReproducer.zip](https://github.com/keycloak/keycloak/files/14872491/KeycloakMemoryLeakReproducer.zip)

### Anything else?

See this memory usage graph from Grafana.
![image](https://github.com/keycloak/keycloak/assets/73428993/f849f2fb-8cba-44cd-94a1-3deb7390bb0b)
The spikes in CPU/network activity are when we conducted simulations of these exceptions with the reproducer client attached in section "How to Reproduce". It may seem that the memory increases on the left are insignificant but this is because of the graph scale. The most prominent spike was at approximately 16:00 when the number of java.nio.channels.ClosedChannelException exceptions suddenly increased from ~2000 to ~4000. If it has any significance, note that most of the exceptions are of type ClosedChannelException (as opposed to the second type HttpClosedException).

There are other people facing these exceptions as well, see https://keycloak.discourse.group/t/close-channel-exception/21181.

**Comment by abstractj** [comment]
@keycloak/cloud-native could you please review? It sounds like an issue with Quarkus.

**Comment by makekz** [comment]
I have the same problem with keycloak 21.0.3.

**Comment by shawkins** [comment]
Related to #27157 - or at least reproduces similar exceptions in the logs.

**Comment by shawkins** [comment]
@aldiyar04 there appear to be some differences with each keycloak version in how this scenario may be handled. If you move up to keycloak 24 I believe that your situation should be addressed.

For keycloak 21, can you produce a heapdump to see what is taking up the increase in memory? There are three possibilities based upon looking at versions 23, 24, and main - Infinispan cache Data, concurrent requests (look for instances of PoolThreadCache), and queued requests (look for instances of QuarkusResteasyReactiveRequestContext). There are settings that can address these latter two issues. If it's related to the infinispan cache, I think you'll have to upgrade.

@pedroigor @ahus1 for this issue and #27157 is there any concern that exceptions like these - connection reset, closed channel, etc. are being overlogged. It seems like they should be warnings at worst, and/or possibly  the stacktraces omitted by default.

**Comment by shawkins** [comment]
To explain more fully on the memory held by infinispan that is related to the sso session created with a successful login. By default it will take 30 minutes for those to timeout - after which that memory should be reclaimed. The footprint of that memory seems to grow more slowly in KC24 vs KC23 - but ultimately it will be related to the number of successful sso sessions you create in a given amount of time.

**Comment by shawkins** [comment]
Marking as low priority as I don't see anything actionable here for 23+. However if the user can create a new reproducer against a later version, then we can follow-up more.

**Comment by aldiyar04** [comment]
@shawkins Reproduced this on the latest version 24.0.2. Conducted 3 simulations:

1) Start 17:37, 493 MB
End 18:00, 574 MB - **memory spike**
ClosedChannelException count - 1646, HttpClosedException count - 143

2) Start 23:00, 578 MB
End 23:21, 580 MB
ClosedChannelException count - 4308, HttpClosedException count - 405

3) Start 23:58, 578 MB
End 18:00, 676 MB - **memory spike**
ClosedChannelException count - 6537, HttpClosedException count - 651

Here are the graphs:
![image](https://github.com/keycloak/keycloak/assets/73428993/45e39727-1acb-4667-b1bd-25642136c752)

The stack traces of the 2 types of exceptions:
[KC24.0.2_ClosedChannelException.json](https://gith
[KC24.0.2_HttpClosedException.json](https://github.com/keycloak/keycloak/files/14950580/KC24.0.2_HttpClosedException.json)
ub.com/keycloak/keycloak/files/14950578/KC24.0.2_ClosedChannelException.json)

The memory leak seems to be intermittent somehow: the number of the exceptions increased by a large amount during the 2nd simulation but there was not a significant increase in the memory usage. (But the memory usage spikes occur only at the time of simulations and memory is not reclaimed thereafter.)

Note that we are using a custom direct access grant implementation (SPI - Service Provider Interfaces). I didn't mention that initially because according to the stack traces the code execution does not reach our custom code. 
I'm sending requests with such parameters so that a user session is not created upon successful request completion (it is created when a request is sent with other parameters), so it shouldn't be related to user sessions being accumulated in the Infinispan cache.
Tried to reproduce without SPI on the standard direct access grant to make simulations totally "clear", just in case. The number of the exceptions were increasing very slowly and by very small amounts, each simulation only a few (~10-20) new exceptions were thrown (so after like 7-10 simulations there were only ~200 exceptions in total). So, I think the small number of the exceptions is the reason there were not memory usage spikes in this case, apparently it is reproduced only with sufficiently high numbers. In any case, as I said, the code execution does not reach our code when the exceptions are thrown.

**Comment by shawkins** [comment]
> The memory leak seems to be intermittent somehow

It's hard to establish you are seeing a leak with a heapdump confirming what is holding the memory. 

> But the memory usage spikes occur only at the time of simulations and memory is not reclaimed thereafter.

Some of the memory held I saw after held was due to netty PoolThreadCache instances - however that corresponding roughly to maximum number of concurrently processed requests, which currently defaults to 200. 

You seem to be dealing with more memory being consumed than that should involve. Since there is no direct correlation in what you are showing above between the number of exceptions of either type and memory usage it's hard to draw any conclusions.

> so it shouldn't be related to user sessions being accumulated in the Infinispan cache.

Can you capture a heapdump - that will make this very clear. 

Or if there are more reproduction steps that you think will make your situation clearer that would help - it sounds like that without your spi in the picture it wasn't reproducible for you either.

**Comment by aldiyar04** [comment]
> Can you capture a heapdump - that will make this very clear.

[heapdump.zip](https://github.com/keycloak/keycloak/files/14954167/heapdump.zip)

I see there are instances of PoolThreadCache, but they are not taking up that much memory, so not sure. Can you please review? Is it enough to draw any conclusions or point in the right direction?

**Comment by aldiyar04** [comment]
@shawkins I sent you a heap dump a few hours ago. Why my message was deleted?

**Comment by shawkins** [comment]
I deleted the threaddump posting because I wasn't sure if there was anything in there that you wouldn't want exposed.

> This heapdump was taken after those 3 simulations, with approximately the same level of memory usage as it was just after the 3rd simulation.

There's not much in that heapdump - less that 83 million bytes. 

> I see there are instances of PoolThreadCache, but they are not taking up that much memory, so I'm not sure. Can you please review? Is it enough to draw any conclusions or point in the right direction?

This seems to primary be an issue with the memory reported in use by kubernetes. Unless there is some offheap memory leak, I think what you are seeing is the affect of the vm simply adjusting the max heap size, but due to other garbage collection settings it may not be aggressively reclaiming that space. That doesn't mean that keycloak is actually using all of that heap.

**Comment by shawkins** [comment]
Speaking of off heap memory usage - this was just logged #28695 but against an older version. I'll double check it under the context of this issue.

**Comment by aldiyar04** [comment]
We switched our Keycloak from development mode to production mode (/opt/keycloak/bin/kc.sh start-dev -> start) and the base image from openjdk-17 to amazoncorretto-21. This was not an attempt to impact this problem with memory leak in any way. But then I conducted 10 simulations, and the problem wasn't reproduced.

1) Start 16:00, 821 MB
End 16:17, 797 MB
ClosedChannelException count - 349, HttpClosedException count - 35

2) Start 18:08, 816 MB
End 18:25, 815 MB
1091, 92

3) Start 18:32, 815 MB
18:50, 815 MB
1650, 148

4) Start 20:23, 819 MB
20:39, 821 MB
2035, 175

5) Start 20:41, 819 MB
End 20:57, 820 MB
2553, 221

6) Start 21:22, 819 MB
End 21:40, 819 MB
3087, 261

7) Start 23:33, 819 MB
End 23:50, 819 MB
3841, 321

8) Start 09:37, 819 MB
End 09:57, 819 MB
6708, 520

9) Start 10:12, 819 MB
End 10:30, 819 MB
9270, 616

10) Start 10:35, 819 MB
End 10:51, 821 MB
10033, 668

![image](https://github.com/keycloak/keycloak/assets/73428993/cf744613-a39d-4f91-8f82-fcc561904339)

As you can see, the memory usage remained at the same level (~820 MB).

With Keycloak v21.0.1 every simulation there was an increase in memory usage, and during some simulations there were memory usage spikes. With Keycloak v21.0.1 (in development mode based on the Docker image openjdk-17) memory usage wouldn't increase every single time but as I wrote in one of the above postings some simulations caused memory usage spikes as well. Strangely enough, now with Keycloak v24.0.2 (in production mode with amazoncorretto-21) it seems the problem isn't going to be reproduced.

**Comment by aldiyar04** [comment]
If it can help to better understand this, I should also note that this time first we ran a few load tests (marked in the screenshot with red, these are regular load tests, not simulations that are intended to cause the exceptions), which increased memory usage initially. Then after the last load test with time memory usage decreased to some extent. Then went the simulations (marked in the screenshot with blue).

![image](https://github.com/keycloak/keycloak/assets/73428993/005eee6f-148e-4911-9b6e-3c719f3510d7)

**Comment by MartinAndreev** [comment]
Hi, we can see this still as an issue. If a connection is closed (we mostly see it for the realm .well-known url, or a OID client login), keycloak just throws ClosedChannelException and restarts.

```
2025-08-20 07:49:47,432 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-772) Uncaught server error: java.io.IOException: java.nio.channels.ClosedChannelException
... 11 more
at org.jboss.resteasy.reactive.server.handlers.FormBodyHandler.handle(FormBodyHandler.java:92)
at org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.getInputStream(ResteasyReactiveRequestContext.java:736)
at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.createInputStream(VertxResteasyReactiveRequestContext.java:249)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.<init>(VertxInputStream.java:39)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.<init>(VertxInputStream.java:184)
Caused by: java.nio.channels.ClosedChannelException
at java.base/java.lang.Thread.run(Unknown Source)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1699)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:638)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
at org.jboss.resteasy.reactive.server.handlers.FormBodyHandler.handle(FormBodyHandler.java:95)
at org.jboss.resteasy.reactive.server.core.multipart.FormEncodedDataDefinition$FormEncodedDataParser.parseBlocking(FormEncodedDataDefinition.java:235)
at java.base/java.io.InputStream.read(Unknown Source)
at java.base/java.io.InputStream.read(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.FormBodyHandler$CapturingInputStream.read(FormBodyHandler.java:132)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:64)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:73)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.read(VertxInputStream.java:85)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream.readIntoBuffer(VertxInputStream.java:123)
at org.jboss.resteasy.reactive.server.vertx.VertxInputStream$VertxBlockingInput.readBlocking(VertxInputStream.java:256)
```

Our setup for the limits are as follows

```-server -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=90 -XX:InitialRAMPercentage=50 -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
```

We are running 3 keycloak isntances, each having 12 GB of ram
