### ISSUE TITLE
Authentication diagram view initially incorrectly formatted

### ISSUE THREAD

**Issue by adhurjaty** [keycloak/keycloak#28449]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When initially viewing the diagram view in a given authentication flow, the flow diagram is bunched up

![Incorrect state](https://github.com/keycloak/keycloak/assets/4791787/ec9db6c6-2a49-480b-b7d0-fc3fcb07761f)

If I click the table view button, then click back, I get the properly formatted diagram

![Correct state](https://github.com/keycloak/keycloak/assets/4791787/a4707e63-9520-42bf-b23e-44199ab4fc53)

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect to see the diagram formatted in the correct state initially

### Actual behavior

The initial diagram view formatting is bunched up vertically

### How to Reproduce?

Click on the 'browser' default authenticator and click the diagram view button. The initial rendering is off

**Comment by edewit** [comment]
This has been fixed you could download the nightly build to verify
