### ISSUE TITLE
More conventional looking conditional element in authentication diagram

### ISSUE THREAD

**Issue by adhurjaty** [keycloak/keycloak#28453]
### Description

When viewing the authentication diagram, if it includes conditionals, it can be difficult to follow the designed flow.

e.g.

![conditional flow](https://github.com/keycloak/keycloak/assets/4791787/a4707e63-9520-42bf-b23e-44199ab4fc53)

In the above diagram, it is unclear that the OTP Form can be avoided based on the previous condition.

My expectation for [conditional](https://www.zenflowchart.com/guides/if-else-flowchart) cases in a flow chart is for them to branch

<img src="https://assets-global.website-files.com/6184b461a39ff1011f8c0582/620239fdd8763fe2a551f490_If-else%20Flowchart.png" width=400 height=600>

### Motivation

This would make it easier for me to describe our custom authentication flow to users less versed in Keycloak

**Comment by ssilvert** [comment]
This is probably a good suggestion, but I don't see us having time to implement it soon.  If you want to send us a PR that would be great.

Do you find the flowchart helpful?  We haven't received much feedback on it.

**Comment by adhurjaty** [comment]
> This is probably a good suggestion, but I don't see us having time to implement it soon. If you want to send us a PR that would be great.
> 
> Do you find the flowchart helpful? We haven't received much feedback on it.

Working on a PR now with a collaborator. I really like the flowchart. It's helpful to show people new to the auth space what checks are being done before a token is granted
