### ISSUE TITLE
Custom Attributes tab not visible since version 24.0

### ISSUE THREAD

**Issue by bbaia** [keycloak/keycloak#28476]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

The custom attributes tab in user page is not visible anymore since 24.0 (tested on 24.0.1 & 24.0.2).

The 'Attributes' tab is not visible in 24.0.2 if you create the link between client and client scope in that version.
BUT, if the link has been created in a previous version, and then, you migrate to 24.0.2, you will not have the issue.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Custom attributes tab in user page should be visible

### Actual behavior

Custom attributes tab in user page is not visible

### How to Reproduce?

The 'Attributes' tab is not visible in 24.0.2 if you create the link between client and client scope in that version.
BUT, if the link has been created in a previous version, and then, you migrate to 24.0.2, you will not have the issue.

### Anything else?

Same as #28315 that has been closed.

**Comment by smileis2333** [comment]
i find it's normail behavior, the org.keycloak.migration.migrators.MigrateTo24_0_0 process the Migration, and if you want to look the   'Attributes' tab , you could in the
Realm settings -> User profile -> JSON editor, add the property `unmanagedAttributePolicy`
``` json
{
   "unmanagedAttributePolicy": "ENABLED", 
   ....
}
```

**Comment by smileis2333** [comment]
https://github.com/keycloak/keycloak/issues/27823

**Comment by pedroigor** [comment]
@smileis2333 Yeah, Keycloak is now more strict about the attributes you can manage for your users. There are both security and UX concerns involved on that.

As you said, changing the `Unamaned Attribute` policy at the realm settings will get back the attribute tab for you. See https://www.keycloak.org/docs/latest/server_admin/#_understanding-managed-and-unmanaged-attributes.

Ideally, you should avoid using `ENABLED` and prefer using `ADMIN_EDIT` instead in addition to configuring your "user-facing" attributes in the user profile configuration for your realm.
