### ISSUE TITLE
Missing help text on tokens tab

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#28489]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

At the bottom of Realm settings --> Tokens tab there is a section called `Override Action Tokens`.  None of those fields have help text.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

See above

### Actual behavior

See above

### How to Reproduce?

See above

**Comment by edewit** [comment]
@ssilvert we need someone to write the help texts then?

**Comment by ssilvert** [comment]
> @ssilvert we need someone to write the help texts then?

Yeah, we probably need some level of help from someone who knows more about those attributes.

**Comment by agagancarczyk** [comment]
hi @andymunro Could you please advice if we can use the following messages. I found them in the [docs](Specifies independent timeout for email verification.) Thanks!

- Email Verification - Specifies independent timeout for email verification.
- IdP account email verification - Specifies independent timeout for IdP account email verification.
- Forgot password - Specifies independent timeout for forgot password.
- Execute actions - Specifies independent timeout for execute actions.

**Comment by andymunro** [comment]
@agagancarczyk Yes, these look like good definitions and it's good to match what is in the documentation.
