### ISSUE TITLE
IdP Linking: Usernames sometimes lowercase and sometimes uppercase

### ISSUE THREAD

**Issue by alexanderhofstaetter** [keycloak/keycloak#28495]
### Area

identity-brokering

### Describe the bug

When a user adds an external IdP, the username is sometimes stored as lowercase, sometimes stored as original value.

we map the original idp uid to both the BROKER_ID and the BROKER_USERNAME

BROKER_ID: gets always the correct value from idP (case sensitive)
BROKER_USERNAME: sometimes the original value is stored correctly (case sensitive) and sometimes the username value gets changed to all lowercase.

### Version

24.0.2

### Expected behavior

THe username gets correctly set as case-sensitive value coming exactly as from the IDP.

### Actual behavior

The username sometimes gets stored as original value and sometimes as all lowercase value. We dont see any connections to containing special chars.

### How to Reproduce?

Add an external IDP with an idp username prepocessor and provide a case sensitive (including uppercase) username attribute

### Anything else?

username mapper:
![image](https://github.com/keycloak/keycloak/assets/6820505/573a9c75-271e-40ac-aeec-b7837e1f4998)

result in the datbase (all demo IDs and no real world data):
- first red box was translated to all lowercase
- second red example gets stored as original
![image](https://github.com/keycloak/keycloak/assets/6820505/97e900e5-de95-497e-9f70-e5f6caaa1129)

**Comment by pedroigor** [comment]
By default, the username is case-insensitive and set to lower-case when updating a user.

Do you see any correlation to when the user already exists vs running the first broker login flow?

**Comment by alexanderhofstaetter** [comment]
Ok, yes, there seems to be a correlation between new and existing user.

- first idp login -> user gets created based on idp -> federated_username is all lower case
- second idp login -> federated_username of user ALWAYS gets updated with the exakt (mixed upper/lower case) attribute coming fom the idp.

this is reproducable with every test login, only the first login gets transformed to all lowercase,.

both are mapped/imported via username template generator BROKER_USERNAME

**Comment by alexanderhofstaetter** [comment]
in our use case we want to to have the federated_username case-senstive (exakt same value as coming from the idp)

**Comment by pedroigor** [comment]
@alexanderhofstaetter Sorry for the delay and thanks for the confirmation. I think I have something to investigate now.

Creating a user and updating an existing one during the broker flow are probably using a different logic to update the user and its federated identity.

I'll try to reproduce it locally.

**Comment by pedroigor** [comment]
> also it would be nice to have the keycloak username set to the original case-senstive attribute and disable lowercase transformation for bothe the federated_username and the KEYCLOAK USERNAME

We are probably not changing how we store the username in the server local database. That is why we have the username from the IdP (it should be) stored in a different place.

**Comment by NHAS** [comment]
Howdy this might be the wrong place to ask, 
but we're seeing some behavior that might be caused by this.

Effectively we have identities in an external IdP that have mixed case usernames, e.g:
```
Firstname.LastName@email.com
other.account@email.com
```

With all lowercase usernames, the first login flow completes successfully and links the identity with the pre-created account in  keycloak. 
 
However, when a mixed case user attempts to go through the `first login flow`, either the ,"Detect Existing Broker User" or "Automatically Set Existing User" fails with "username or password not found".

**Comment by wronglink** [comment]
Hello @pedroigor,

I'd like to raise a concern regarding the recent changes introduced in PR #29148. Specifically, the removal of the public `BrokeredIdentityContext.setIdpConfig()` method, which was part of the commit bbb83236f5251e3c4718eac63ab0e640a80913f1 (the [specific change](https://github.com/keycloak/keycloak/commit/bbb83236f5251e3c4718eac63ab0e640a80913f1#diff-822407a2ffe29578766f8593a05b8a3001c086b24db66b92c4bcbd9ba07ad298L145)).

Given the importance of backward compatibility, could we consider adding a note about this change in the upgrade notes? Alternatively, marking it as a deprecated method, adding null-check for `idpConfig` field and planning its removal might provide a smoother transition for users relying on the existing method.

Do you think this is relevant?
