### ISSUE TITLE
Missing help text for Brute Force Mode

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#28490]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Realm settings --> Security defenses --> Brute force detection

Help text comes up as `bruteForceModeHelpText`

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Show proper help text.

### Actual behavior

see above

### How to Reproduce?

see above

**Comment by edewit** [comment]
this PR introduced the help text, but not the value https://github.com/keycloak/keycloak/pull/26208
