### ISSUE TITLE
Workflow failure: choco install zstandard

### ISSUE THREAD

**Issue by tondrusk** [keycloak/keycloak#28510]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
Chocolatey v2.2.2
Installing the following packages:
zstandard
By installing, you accept licenses for the packages.
Unable to connect to source 'https://community.chocolatey.org/api/v2/':
 Failed to fetch results from V2 feed at 'https://community.chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'zstandard')%20and%20IsLatestVersion&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 499 ().
zstandard not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - zstandard - zstandard not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
Error: Process completed with exit code 1.
```
https://github.com/keycloak/keycloak/actions/runs/8563925902/attempts/1

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

 -

### Actual behavior

 -

### How to Reproduce?

 -

**Comment by Pepo48** [comment]
@tondrusk does this failure appear frequently? Based on the attached description it looks like a network issue/chocolatey outage.

Especially if you observe that an immediate rerun tends to be successful, we can always try to make the package installation more robust, for example by adding a number of retries:
```
$retryCount = 0
$maxRetries = 5

while ($true) {
    try {
        choco install zstandard -dvfy
        break
    } catch {
        if ($retryCount -ge $maxRetries) {
            Write-Error "Failed to install package after $maxRetries attempts."
            exit 1
        } else {
            $retryCount++
            Start-Sleep -Seconds (5 * $retryCount)
        }
    }
}
```

**Comment by tondrusk** [comment]
@Pepo48, it might be a one-time error since I haven't seen it again in the workflows. I was asked to report it for better tracking as it might occur again in the future.

**Comment by Pepo48** [comment]
It looks like it to me, I have been using Chocolatey for many years and although it happens very sporadically, it's not the first time I've seen such message. Thus, I assume that this one was caused by a temporary service unavailability.

**Comment by tondrusk** [comment]
Closing based on @Pepo48's comment.
