### ISSUE TITLE
Reduce the number of default task threads

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#28516]
200 seems too large of a default based upon testing that has been done for keycloak - see https://github.com/quarkusio/quarkus/blob/9fc4e97d3e35db4ee7584d10c04febf62b48fd90/core/runtime/src/main/java/io/quarkus/runtime/ExecutorRecorder.java#L200

max(50, 4 x available processors) has been proposed as an alternative

_Originally posted by @stianst in https://github.com/keycloak/keycloak/issues/28478#issuecomment-2041971460_

**Comment by pedroigor** [comment]
Changing the default should also align with the recommendations done in https://github.com/keycloak/keycloak/pull/24913#discussion_r1403290580.
