### ISSUE TITLE
v24.0.2 rest-api - User update endpoint requires e-mail only when updating attributes

### ISSUE THREAD

**Issue by FelipeEmerimRandon** [keycloak/keycloak#28527]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

After upgrading keycloak from v23.0.3 to v24.0.2 we started seeing this issue in the user profile. If we call the endpoint like this:

```bash
curl --location --request PUT 'https://kc-endpoint/auth/admin/realms/some-realm/users/some-user' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer token' \
--data '{
    "attributes": {
        "roles": [
            "account.all",
            "loyalty.register"
        ]
    }
}'
```

The server will reply with the following error:
```json
{"field":"email","errorMessage":"error-user-attribute-required","params":["email"]}
```

However, if we try to update a different user field, like `firstName` or `emailVerified` for example, this validation is not triggered and email is not required in the payload, so the user is updated successfully.
```bash
curl --location --request PUT 'https://kc-endpoint/auth/admin/realms/some-realm/users/some-user' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer token' \
--data '{
    "emailVerified": true
}'
```

Previuosly, the email field was not required in both cases. The user would be updated and the e-mail field would just stay the same.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I expected both calls to the rest API to either require or not require the email field. Since the previous behavior was to not require it, I believe that should be favored instead of always requiring the field. Additionally, the email field should not be set to empty as that was the previous behavior.

### Actual behavior

Depending on the payload, the user update request returns a field required error on the `email` field.

### How to Reproduce?

I believe that was already explained in the bug description. Our email attribute is configured as required and editable by both users and admins. Our users have it set on creation and emailVerified is true

### Anything else?

Setting the email field to non-editable make both requests not require the email field. However, new users get created with an empty email.

I haven't found any mentions of this change in the changelog, but feel free to close this issue if this is intended behavior or if this is already tracked.

**Comment by pedroigor** [comment]
@FelipeEmerimRandon Yeah, this is a bit confusing and the reason is that for historical reasons the `email`, `username`, `firstName`, and `lastName` are fields in our user model.

But then, before the user profile, they started to be managed as a regular attribute. So when you set a `email` attribute it will actually set the `email` field in the user model. The same for others.

In theory, we no longer need those fields anymore and all those attributes should be regular user attributes.

Not sure when we are going to fix this but that is how they work for now.
