### ISSUE TITLE
Issue encountered while importing JSON file for Realm Configuration in Keycloak

### ISSUE THREAD

**Issue by Akhmarzhan** [keycloak/keycloak#28524]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Subject: Issue Encountered While Importing JSON File for Realm Configuration in Keycloak

Description:
I'm encountering an issue while attempting to export and import realm settings and authentication configuration in Keycloak. Below are the steps I've followed:

1. Exported the realm to a JSON file using the command:
`docker exec –it containerName /opt/keycloak/bin/kc.sh export --file /tmp/realm-export.json --users skip --realm realmName`

2. Copied the exported JSON file to the local computer using the command:
`docker cp containerName:/tmp/realm-export.json /tmp/realm-export.json`

3. Generated a new database in the JSON file using a Python script.

4. Attempted to import the realm settings and authentication configuration:
   - Logged in to Keycloak as an admin.
   - Created a new realm.
   - Went to Realm settings -> Actions -> Uploaded mynewfile.json (JSON file with new database) -> Selected all resources -> Chose "Overwrite" if a resource already exists -> Clicked "Import".

However, after importing, only users, groups, identity providers, and realm/client roles are present. There are no configuarations such as realm settings, authentification.  
When trying to create a new realm using this JSON file, an error occurs: "Could not create realm Conflict detected. See logs for details".

In the Keycloak logs, the following error is reported:
`Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_orvsdmla56612eaefiq6wl5oi"
  Detail: Key (name)=(kerberos-free-realm) already exists
`
I have ensured to modify the entire database and realm-name, and even adjusted the unique constraint "uk_orvsdmla56612eaefiq6wl5oi" to avoid the aforementioned error.

Despite these modifications, a new error arises: 
`
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-499) Uncaught server error: java.lang.RuntimeException: Resource with id or name [Users] does not exist or is not owned by the resource server.
`

Conclusion:
The objective is to clone any realm for multiple clients without needing to configure each one individually. Assistance in resolving this issue would be greatly appreciated.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The expected outcome of the process is that the realm settings and authentication configurations exported from Keycloak using a JSON file should be successfully imported into a new realm. This includes all the configurations related to users, groups, identity providers, realm/client roles, and any custom database configurations. Upon import, the new realm should reflect the exact configuration as defined in the JSON file, allowing for easy replication of settings across different instances or clients.

### Actual behavior

Despite following the correct steps, the realm settings and authentication configurations are not being applied as expected. Only some components such as users, groups, identity providers, and realm/client roles are imported successfully. 

### How to Reproduce?

1. Export Realm Configuration:
   - Use Keycloak's export functionality or the provided Docker command to export the realm configuration to a JSON file.
   `docker exec –it containerName /opt/keycloak/bin/kc.sh export --file /tmp/realm-export.json --users skip --realm realmName`
2. Modify JSON File:
   - Optionally, modify the JSON file to include changes or a new database configuration using a Python script as described.
3. Import Realm Configuration:
   - Log in to Keycloak as an admin.
   - Navigate to the admin console and create a new realm.
   - Go to Realm settings -> Actions -> Upload the modified JSON file.
   - Select all resources and choose "Overwrite" if prompted.
   - Click "Import" to import the realm configuration from the JSON file.
4. Observe Errors:
   - After the import process, observe the realm to ensure that all configurations, including users, groups, identity providers, and realm/client roles, are imported correctly.
   - Attempt to create a new realm using the imported JSON file.
   - Note any errors encountered during the import process, such as "Conflict detected" or errors related to missing resources like "Users".
5. Review Logs:
   - Check the Keycloak logs for any error messages or exceptions encountered during the import process.
   - Look for specific error messages indicating issues with unique constraints or missing resources.

**Comment by rs0h** [comment]
Same issue. v24.0.2. Tried with full export\import using web GIU.

**Comment by simse07** [comment]
Same issue v24.0.4. Additionally, the user profile configuration is not imported too.
