### ISSUE TITLE
Secondary datasource health-exclude not working on Kubernetes

### ISSUE THREAD

**Issue by noiter** [keycloak/keycloak#28553]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I previously configured a secondary datasource in `quarkus.properties` file, and I want to gradually clean up that datasource. So I specified
```
quarkus.datasource.'secondary-datasource'.health-exclude=true
```
by following [Quarkus datasource configuration guide](https://quarkus.io/guides/datasource#datasource-health-check). After that I tested the config locally with Docker: even though I revoked all permission from the secondary datasource user, the `/auth/health` pages still shows UP status.

But when I deployed the change to development environment, which is set up on Kubernetes, I observed that as long as I revokes the permission from the secondary datasource user, I start seeing error in Keycloak log:
```
2024-04-09T10:50:45.717Z WARN  agroal-21 io.agroal.pool : Datasource 'secondary-datasource': Access denied for user 'user'@'%' to database 'secondary-database'
2024-04-09T10:50:45.718Z INFO  executor-thread-1 io.smallrye.health : SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"Keycloak database connections health check","status":"DOWN","data":{"Failing since":"2024-04-09 10:50:40,812"}}]}
```
.

I looked into the Keycloak source code, and checked the `org.keycloak.quarkus.runtime.services.health.KeycloakReadyHealthCheck`, but it looks fine to me. I have to turn to raising an issue here. 

Any thoughts on it?

### Version

22.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Health check should be excluded for datasource configured with
```
quarkus.datasource.'secondary-datasource'.health-exclude=true
```

### Actual behavior

Health check is still included for datasource configured with
```
quarkus.datasource.'secondary-datasource'.health-exclude=true
```

### How to Reproduce?

Step 1:
Configure a secondary datasource in `quarkus.properties` file, add `quarkus.datasource.'secondary-datasource'.health-exclude=true`

Step 2:
Copy the file under `conf/` folder of Keycloak before build a new custom Keycloak image

Step 3:
Deploy the new custom Keycloak image onto Kubernetes

Step 4:
Revoke all permissions on secondary datasource from the user:
```
revoke <PERMISSIONS> on `secondary_datasource`.* from 'user'@'%';
```

**Comment by shawkins** [comment]
@noiter this is not related to kubernetes. If you are mixing single and double quotes around the datasource name in the quarkus configuration that will be problematic. Quarkus seems to preserve single quotes, whereas double is not part of the datasource name. You likely want to use

quarkus.datasource."secondary-datasource".health-exclude=true

**Comment by shawkins** [comment]
@noiter I have tested on both KC22 and on main, and this works in both places. My only other guess would be that most changes in the quarkus.properties aren't picked up via an auto-build - you may need to issue a build first.

See https://github.com/keycloak/keycloak/blob/aa619f01700df79da69f4314c0f1225c14c6cfa1/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/QuarkusPropertiesConfigSource.java#L53 - only a subset of the build time properties are considered.

cc @vmuzikar @mabartos is it intentional to only look for a subset of build time properties? We may be able to use something like #26175 to find them more dynamically, not sure if this applies to datasource properties - cc @radcortez

**Comment by mabartos** [comment]
@shawkins It seems it was intentional, but I'd say a better approach would be to allow all build-time Quarkus props, not only related to datasources. Perhaps there was not any approach on how to achieve it lately. But I don't have a broader context.

**Comment by noiter** [comment]
@shawkins It should be something else. I don't use `auto-build` at all, and the build has been done via
```
RUN /opt/keycloak/bin/kc.sh build
```
in Dockerfile. 

Do you think the `health-exclude` property wasn't picked up with above way?

**Comment by shawkins** [comment]
> It should be something else. I don't use auto-build at all, and the build has been done via

Ok, so you are using a build and later start --optimized. Is the quarkus.properties part of the image when the build is being run?

**Comment by noiter** [comment]
@shawkins appreciate your hint about the `auto-build` and `build`.

The problem was I was having a placeholder for value of
```
quarkus.datasource.dbsource.health-exclude=$TO_BE_EXCLUDED
```
in `quarkus.properties`, and updating the value at point of time after `/kc.sh build` is run. 

I assume the value update was not picked up by Keycloak because of the `QUARKUS_DATASOURCE_BUILDTIME_REGEX` and `kc.sh start --optimized` does a auto build and simply ignores it?

**Comment by shawkins** [comment]
> I assume the value update was not picked up by Keycloak because of the QUARKUS_DATASOURCE_BUILDTIME_REGEX and kc.sh start --optimized does a auto build and simply ignores it?

start --optimized will only use build time values that are already persisted into the keycloak optimized image / jar. In this case quarkus.datasource.dbsource.health-exclude will already have resolved to a static value and no runtime processing will occur.

auto-builds will occur when you use start without --optimized. The logic will detect is a build time property has changed and automatically rebuild - however as noted in the previous comments that current won't happen with quarkus.datasource.dbsource.health-exclude.

**Comment by noiter** [comment]
Appreciate the clarification.

Then it is clear that this is something I need to fix on my side, sorry for the mis-reporting.

**Comment by shawkins** [comment]
> Then it is clear that this is something I need to fix on my side, sorry for the mis-reporting.

No problem. I'll change the title of the issue to help others if they are in a similar situation.
