### ISSUE TITLE
UserStorageSyncManager int overflow

### ISSUE THREAD

**Issue by tqe1999** [keycloak/keycloak#28564]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Keycloak crashes when sync periods are set to 2147484 or greater due to an integer overflow

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I should be able to set sync periods of greater than 2147484 without Keycloak crashing.

### Actual behavior

When sync periods are set to 2147484 or greater, an integer overflow occurs due to the multiplication, resulting in a negative delay being passed to the timer despite the checks lines [207](https://github.com/tqe1999/keycloak/blob/1bb5e1413416cbe7a83952c6a01e7f75ac7502f3/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L207) and [217](https://github.com/tqe1999/keycloak/blob/1bb5e1413416cbe7a83952c6a01e7f75ac7502f3/model/storage-private/src/main/java/org/keycloak/storage/managers/UserStorageSyncManager.java#L217). As a result Keycloak crashes due to the unhandled exception.

### How to Reproduce?

Set a sync period to 2147484 or greater, then restart Keycloak.

**Comment by sguilhen** [comment]
I was able to reproduce by trying to set the value (which is the same as `Integer.MAX_VALUE/1000 + 1`) in  the LDAP sync settings and then saving the changes. The error is visible right away.

One way to improve things would be to switch the sync values in `UserStorageProviderModel` to long - in line with what the `schedule` method in `TimerProvider` expects. Also, it might be a good idea to check if the configured values * 1000 doesn't overflow the LONG.MAX_VALUE before calling the timer, adjusting it to the MAX_VALUE in case the computed value is negative.

**Comment by sguilhen** [comment]
@martin-kanis if the associated PR looks ok to you and has a chance of being merged in this sprint, please add the issue to the sprint.
