### ISSUE TITLE
Support OpenTelemetry tracing

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#28581]
### Description

For a better observability experience of Keycloak, it'd be great to support a mechanism for obtaining application traces. We'd be able to trace requests with additional information and gather more comprehensive information about the state of the application. We can find performance bottlenecks, determine the cause of application failures in a more agile way, and much more.

The most promising solution for it would be leveraging the open-source OpenTelemetry observability framework, which is also packaged as a Quarkus extension.

https://opentelemetry.io/docs/what-is-opentelemetry/
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31908
```

**Comment by thomasdarimont** [comment]
Yes proper otel support out of the box would be great!

Instrumentation already works quite well with the otel agent. The quarkus otel integration only partially works because the Apache http client that Keycloak uses for outgoing requests is not properly instrumented.

However, the otel-agent instrumentation seems to capture everything.
I already talked with @ahus1 about this.
IIRC he mentioned that the otel-agent doesn't seem to work so well with the reactive components at the moment.

**Comment by ahus1** [comment]
The official recommendation from Quarkus is to use their integrated way and not the agent, see https://quarkus.io/guides/opentelemetry

We will use what they offer out of the box. If there is anything missing, we will talk to the Quarkus team. 

Looking at the docs above, Quarkus supports with OTEL only tracing, which is what we will follow.

**Comment by sschu** [comment]
@ahus1 One thing that is definitely missing for us is to define a fixed rate for sampling so you can keep your costs in check if you use a managed service that bills on the amount of ingested trances. The Azure ApplicationInsights agent (https://github.com/microsoft/ApplicationInsights-Java) supports that (and is based on OTEL AFAIK).

**Comment by mabartos** [comment]
@sschu Good to know. It should not be a problem to provide it. Thanks!

**Comment by ahus1** [comment]
@sschu - let's discuss the "how" and details in the PR.

**Comment by trixpan** [comment]
we also use otel agent. It works fine despite the Quarkus recommendation (which I don't actually understand tbh).

I do have an honest contribution to make:

I think it is important to observe that as soon KC start "supporting" opentelemetry there will be an influx of people asking for specific exporting mechanisms (as it happened with logging / JSON). 

Given [Quarkus a somewhat controversial fit to a composable software offering](https://github.com/keycloak/keycloak/discussions/13181) I think it is worth having that in mind from the start of this journey...

Going one step further, one could say it is a puzzling inconsistency that this change is being done assuming OTLP will be available as a sidecar / endpoint while the logging changes always assume keycloak needs somehow to be able to send logs to another platform (while in reality most places would simply use sidecar injections to solve both scenarios)

Third party libraries continue to be a source of particular concern across the user base (vide the XV fiasco)
