### ISSUE TITLE
Allow onboarding organization members through a registration invitation link

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28608]
### Description

To allow organizations to onboard members when it is not possible or desired to federate their identities from an identity provider linked to the organization, we need to allow an administrator to send a registration invitation link by e-mail so that they can use that link to automatically register to an organization as a new member.

This feature request is about:

* Given an e-mail address, send a registration invitation link via e-mail
* Register a new member to an organization once they follow the registration invitation link

**Comment by alice-wondered** [comment]
Taking a look at this issue :) 

Most likely going to register a new action token handler that works with the invitation behavior

**Comment by xgp** [comment]
So create the new user before the invitation is sent? Anonymous action tokens are not permitted AFAIK.

**Comment by alice-wondered** [comment]
You would be correct! Would have to create the new user first, didn't realize that at the time of my first comment. This is my first foray into this area of keycloak. 

I have a couple of ideas on how to work around that. Am thinking that the login service registration flow / forms can be updated to optionally handle an extra query param that contains the signed action token. Or create a new endpoint/flow/form for an org specifically

**Comment by pedroigor** [comment]
I agree that we should avoid creating the users beforehand.

**Comment by Skittel** [comment]
Hello, I use keycloak for several web-apps.

I create users for these by request by mail.
Currently I create the user, set a temporary password and send the user a mail with link, email and password.

I would love if I can skip setting the temporary password and the mail managed by keycloak as well.

Stefan
