### ISSUE TITLE
First Release of Keycloak Organization

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28609]
### Description

See https://github.com/keycloak/keycloak/issues/30180.

The planned release dates for the first release of Keycloak Organization are:

| Release  | State |
| ------------- | ------------- |
| 25.0.0  | Preview  |
| 26.0.0  | Supported  |

For more details about the release dates, see https://github.com/keycloak/keycloak/milestones.

### Discussion

https://github.com/keycloak/keycloak/discussions/23948

### Issues

- #27928
- #28247
- #28737

### Motivation

Keycloak is a well-known open-source IAM solution and we want to leverage now its capabilities to enable CIAM with a focus on B2B use cases.

**Comment by alice-wondered** [comment]
For the sake of searching the issue threads and googling, I'm just going to mention that this is keycloak's implementation of tenant architecture/multi-tenancy

**Comment by pedroigor** [comment]
> For the sake of searching the issue threads and googling, I'm just going to mention that this is keycloak's implementation of tenant architecture/multi-tenancy

Yeah, but limited to solving B2B as we are not fixing the scalability of realms or making it possible to use Keycloak as a SaaS/IaaS.

**Comment by smandlavdiya** [comment]
> > For the sake of searching the issue threads and googling, I'm just going to mention that this is keycloak's implementation of tenant architecture/multi-tenancy
> 
> Yeah, but limited to solving B2B as we are not fixing the scalability of realms or making it possible to use Keycloak as a SaaS/IaaS.

@pedroigor will it support one user with different realm/client roles on each organisation associated with?

**Comment by xgp** [comment]
> different realm/client roles on each organisation associated with

@smandlavdiya My understanding from their feature choices is that there will only be 1 organization per user, so there will be no such concept as roles per organization membership.

**Comment by pedroigor** [comment]
@smandlavdiya @xgp We do have plans to support roles in a per-organization basis. The same as groups. 

For realm/client roles assigned to organization members, do you mean something like what is proposed here https://github.com/keycloak/keycloak/discussions/23948#discussioncomment-9134249? See the item related to `tiers`.

**Comment by Tayfun74** [comment]
Will this also contain customizability for email templates per organization? 
Or can this be the base for implementing that in the future?

**Comment by pedroigor** [comment]
It is the base for implementing more stuff on top of it, including what you are suggesting. 

I don't think we have any requirements around what you are suggesting (perhaps something more generic around themes). Could I ask you to create an issue with more details about the use case you are trying to solve and how you think it should work?

**Comment by pedroigor** [comment]
Please, see https://github.com/keycloak/keycloak/discussions/23948#discussioncomment-9391003.

**Comment by payam-vahedi** [comment]
The question raised earlier regarding 'email templates per organization' aligns with my concerns. When discussing the multi-tenancy feature, it's crucial to ensure that each organization can fully customize its email communications, especially when sending invitations. Specifically, each organization should have the ability to configure its own SMTP settings to send emails using their unique email domain. Moreover, the content of the invitation emails must be customizable, allowing flexibility in the text, branding, and logos to reflect the individual organization's identity.
