### ISSUE TITLE
Add ui-tab context information into the onCreate

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#28616]
### Description

You can add a tab anywhere in the application, but it would be very helpful to be able to access this context in the onCreate

### Discussion

https://github.com/keycloak/keycloak/discussions/24805#discussioncomment-9067012

### Motivation

Without this what you can do with this feature is limited to only add a tab that is separate from where it's been shown

**Comment by bd-dbconn** [comment]
We tried to use this context in a custom UiTabProvider with the path `/:realm/users/:id/:tab?`
The frontend sends the ID of the selected user (`:id` from the path) in the payload in `config.id`
When we try to get this information in the `UiTabProvider.onUpdate(..., ComponentModel newModel)` under model.config["id"] we get the ID of the loggedin user. `:realm` and `:tab` are correct, just the user id switches. Is this on purpose or a bug? If on purpose, how can we get the id of the user from the path?
