### ISSUE TITLE
Values of Custom claims in Access token are not getting updated to the latest

### ISSUE THREAD

**Issue by atul-epam** [keycloak/keycloak#28631]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

I have included few custom claims in my Access token generated during login using Keycloak custom provider and custom protocol mapper.
Now the value of few of the custom claims are modified in the application database but when the same user tries to login again using keycloak login api, he still see old value for those modified custom claims.

This is happening because **user is cached in Keycloak and using the same adaptor (User model) that was created during first time login for that particular user.** Any kind of change in claims is not considered.

The same issue is happening with the Access token generated using refresh token.

### Version

23.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Access token should contain the modified values of custom claims.

### Actual behavior

The custom claims in the Access token are having old values and not modified values.

### How to Reproduce?

- Login with a user and add few custom claims in the generated access token.
- Modify few user attributes that are present in access token in form of custom claims.
- Login again with the same user.
- Decode the JWT token and see values of the custom claims.

**Comment by atul-epam** [comment]
Hi Team, we have upgraded from v22 to v23.0.4 in Jan 2024 itself. Can you pleas suggest why 23.0.4 became a not supported version so soon?

Also, how frequently do we get new Keycloak versions? and when exactly then become unsupported? How to know exactly when we will be getting the next version of keycloak? This information is required to keep a track and upgrade it in our application.

Can you please also confirm if we should upgrade, when major version is updated like v22, v23, v24, etc or also with minor versions like v24.0.2, v24.0.3, etc ?

**Comment by jonkoops** [comment]
As per Keycloak policy only the latest major is supported at any time.

**Comment by atul-epam** [comment]
Hi Team. Today I tested the same scenario using 24.0.2 version and results are still same on latest build as well. Can you please help me here?

**Comment by pedroigor** [comment]
It is a bit weird that the cache is not invalidated once the attribute is updated to a user. What you mean by a "Keycloak custom provider" is it a custom user storage provider?

**Comment by atul-epam** [comment]
@pedroigor yes, it's custom user storage provide.

**Comment by pedroigor** [comment]
This should be handled automatically. When you update the model (e.g.: call any setter) the entry in the cache is invalidated to force fetching the current state.

I'm not sure how your custom user provider is implemented but you can try to debug when updating the user to see if invalidations are created for force reloading the user state from the database.

**Comment by atul-epam** [comment]
We are using external storage (not keycloak database). How we can invalidate keycloak cache, when there is a change in user's attribute in external database?
Consider the scenario:
- User whose details are present in external database, login into the application via keycloak.
- getUserByUsername is being called, where we are creating UserModel (Adaptor).
- Keycloak's cache stores user's attributes. 
- User's attributes are changed in external database.
- User tries again to login via keycloak. This time getUserByUsername is not getting called. May be because user's details are already present in cache. So old UserModel is being used. This UserModel contains user's old data.
- In custom keycloak code, we are getting latest user's attributes from external API calls. But still keycloak is using cached user's data and not the latest data.

Can you please help me understand, how to invalidate cache and use updated user's data?

**Comment by pedroigor** [comment]
If you are changing data in your identity store, the server won't be able to recognize the change and invalidate the cache automatically. Ideally, you want to manage your users through the Admin REST API, and pass through your custom provider.

You can programmatically invalidate the cache by trying something like: 

```
UserCache userCache = UserStorageUtil.userCache(session);
        if (userCache != null) {
            userCache.evict(realm, user);
        }
```

But you need some notification mechanism around that to only remove the entry from the cache when needed.

But yeah, I don't think we want to fix anything in Keycloak as we don't have plans to provide a more smart mechanism to receive notifications from custom identity stores and invalidate entries automatically.

**Comment by atul-epam** [comment]
Hi @pedroigor thanks for suggesting the following code:

UserCache userCache = UserStorageUtil.userCache(session);
if (userCache != null) {
    userCache.evict(realm, user);
} 

I tried it but after invalidating the cache manually, I am getting the following error on next login with same user and this user is now unable to login via keycloak at all:

[org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext] (executor-thread-5) Restarting handler chain for exception exception: org.keycloak.models.ModelException: java.lang.IllegalStateException: **Session/EntityManager is closed**
2024-04-30 12:18:30     at org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:99)
2024-04-30 12:18:30     at org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:64)
2024-04-30 12:18:30     at jdk.proxy2/jdk.proxy2.$Proxy79.createNamedQuery(Unknown Source)

**Comment by atul-epam** [comment]
@pedroigor can you please provide your suggestion on my latest comment?

**Comment by atul-epam** [comment]
@pedroigor If you can suggest something, that would be a great help.
