### ISSUE TITLE
External Infinispan as cache - Part 2

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#28648]
### Description

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Motivation

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Details

Part 2 of the series `External Infinispan as cache`

This part includes a new implementation for the providers:
* StickySessionEncoderProviderFactory
* LoadBalancerCheckProviderFactory
* SingleUseObjectProviderFactory

And adds a new remote-only cache `actionTokens`.

**Comment by ahus1** [comment]
PR has been merged to the feature branch, closing.
