### ISSUE TITLE
Adjust priority of SubMapper

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28661]
Follow-up on #21185 .

The fact that we now add `sub` claim by protocol mapper by default means that other custom protocol mapper implementations (possibly added by users), which previously allow to override the `sub` claim, can be now potentially executed before the `SubMapper`, which may not be so ideal as the `SubMapper` might override custom value of the `sub` claim.

Possibility is to adjust priority of `SubMapper`, so it is invoked before other protocol mappers, which keep default priority.

**Comment by sschu** [comment]
While we are at the sub mapper again, do we make sure the sub mapper is part of the `oidc` scope (see my late question here: https://github.com/keycloak/keycloak/pull/28622#issuecomment-2051078221)?
