### ISSUE TITLE
Accessing a transient (lightweight) user through client session fails in admin-api/-ui

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#28666]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I've enabled the `transient-users` feature and authenticated a user through an external identity provider. This works fine as expected.
But when I try to access the user in admin-ui through the (client-)sessions tab, it fails. There are several requests being called when trying to access the user and the one to

`GET /admin/realms/{realm}/ui-ext/users/lightweight-{some-uuid}/unmanagedAttributes`

fails with `404`.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

The user details can be accessed through the (client-)sessions tab in admin-ui and no admin-api request fails.

### Actual behavior

see description, the request

`GET /admin/realms/{realm}/ui-ext/users/lightweight-{some-uuid}/unmanagedAttributes`

fails with `404`.

### How to Reproduce?

- enable the `transient-users` feature
- configure an external IdP
- authenticate a user through this IdP
- open the sessions tab in admin-ui
- locate the respective session
- click on the username of the entry to show the user details
- -> error

### Anything else?

I checked "regression", as this worked until 23, but there was no `.../unmanagedAttributes` call then. So, from the recognized behavior it's a regression, technically it's a new request which fails.

**Comment by hmlnarik** [comment]
Moving to UI since this is a `ui-ext` call
