### ISSUE TITLE
Host name must not be empty when accessing admin console on 24.0.2

### ISSUE THREAD

**Issue by gildasleaute** [keycloak/keycloak#28669]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Moving from 23.0.7 to 24.0.2, I fall into hostname issues. Keycloak is behing a proxy that handles the TLS termination

STARTUP OK :

      docker run --name=keycloak \
        --hostname=0.0.0.0 \
        --user=1000 \
        --env=KEYCLOAK_ADMIN=admin \
        --env=KC_DB=postgres \
        --env=KC_DB_URL=jdbc:postgresql://postgres_15/keycloak \
        --env=KC_HOSTNAME_ADMIN_URL=https://mykeycloak.com/auth/ \
        --env=KC_HTTP_RELATIVE_PATH=/auth/ \
        --env=KC_DB_PASSWORD=XXXXXXXXX \
        --env=KC_HTTP_ENABLED=true \
        --env=KC_DB_USERNAME=postgres \
        --env=KEYCLOAK_ADMIN_PASSWORD=YYYYYYYYY \
        --env=PROXY_ADDRESS_FORWARDING=true \
        --env=KC_PROXY_HEADERS=xforwarded \
        --env=KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true \
        --env=KC_HOSTNAME_URL=https://mykeycloak.com/auth/ \
        --env=KC_HOSTNAME_STRICT=true \
        --network=haproxy_keycloak-network -p 8081:8080 --expose=8443 --restart=no --runtime=runc --detach=true quay.io/keycloak/keycloak:23.0.7 start-dev

With same parameters on 24.0.2, when accessing the admin console  https://mykeycloak.com/auth/:

      docker run --name=keycloak \
        --hostname=0.0.0.0 \
        --user=1000 \
        --env=KEYCLOAK_ADMIN=admin \
        --env=KC_DB=postgres \
        --env=KC_DB_URL=jdbc:postgresql://postgres_15/keycloak \
        --env=KC_HOSTNAME_ADMIN_URL=https://mykeycloak.com/auth/ \
        --env=KC_HTTP_RELATIVE_PATH=/auth/ \
        --env=KC_DB_PASSWORD=XXXXXXXXX \
        --env=KC_HTTP_ENABLED=true \
        --env=KC_DB_USERNAME=postgres \
        --env=KEYCLOAK_ADMIN_PASSWORD=YYYYYYYYY \
        --env=PROXY_ADDRESS_FORWARDING=true \
        --env=KC_PROXY_HEADERS=xforwarded \
        --env=KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true \
        --env=KC_HOSTNAME_URL=https://mykeycloak.com/auth/ \
        --env=KC_HOSTNAME_STRICT=true \
        --network=haproxy_keycloak-network -p 8081:8080 --expose=8443 --restart=no --runtime=runc --detach=true quay.io/keycloak/keycloak:24.0.2 start-dev

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.IllegalArgumentException: host name must not be empty
	at io.vertx.core.impl.Arguments.require(Arguments.java:29)
	at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:76)
	at io.quarkus.vertx.http.runtime.ForwardedParser.parseFor(ForwardedParser.java:210)
	at io.quarkus.vertx.http.runtime.ForwardedParser.calculate(ForwardedParser.java:180)
	at io.quarkus.vertx.http.runtime.ForwardedParser.remoteAddress(ForwardedParser.java:108)
	at io.quarkus.vertx.http.runtime.ForwardedServerRequestWrapper.remoteAddress(ForwardedServerRequestWrapper.java:192)
	at io.vertx.ext.web.impl.ForwardedParser.calculate(ForwardedParser.java:112)
	at io.vertx.ext.web.impl.ForwardedParser.absoluteURI(ForwardedParser.java:95)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:158)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.getRequestAbsoluteUri(VertxResteasyReactiveRequestContext.java:184)
```

I cannot manage to setup the hostname-debug endpoint like I previously did on 23.0.7 when I fell into similar problems, as on 24.0.2 I fall into this same hostname issue when trying to access it.

I didn't see any kind of documentation stating that things changed around these options between 23.0.7 and 24.0.2, but maybe I missed something.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak 24.0.2 behind a proxy handling the TLS termination can start with the same parameters as 23.0.7

### Actual behavior

Error when accessing admin console :

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.IllegalArgumentException: host name must not be empty
	at io.vertx.core.impl.Arguments.require(Arguments.java:29)
	at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:76)
	at io.quarkus.vertx.http.runtime.ForwardedParser.parseFor(ForwardedParser.java:210)
	at io.quarkus.vertx.http.runtime.ForwardedParser.calculate(ForwardedParser.java:180)
	at io.quarkus.vertx.http.runtime.ForwardedParser.remoteAddress(ForwardedParser.java:108)
	at io.quarkus.vertx.http.runtime.ForwardedServerRequestWrapper.remoteAddress(ForwardedServerRequestWrapper.java:192)
	at io.vertx.ext.web.impl.ForwardedParser.calculate(ForwardedParser.java:112)
	at io.vertx.ext.web.impl.ForwardedParser.absoluteURI(ForwardedParser.java:95)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:158)
	at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.getRequestAbsoluteUri(VertxResteasyReactiveRequestC

### How to Reproduce?

Use provided docker start commands.

### Anything else?

_No response_

**Comment by sguilhen** [comment]
@vmuzikar  Not sure anything changed in the hostname env options, assigning to the cloud native team to triage.

**Comment by shawkins** [comment]
@gildasleaute the exception should mean that X-Forwarded-For header is either an empty string "" or set to just the port ":port". Can you confirm what header values are being sent?

This may have been working for you before because both the forwarded and x-forwarded headers were considered. Is your proxy setting a Forwarded header as well?

@vmuzikar @cescoffier it does appear that the ForwardedParser is not very robust at handling the X-Forwarded-For based upon online docs that claim it may contain a comma separated list and ipv6 without backets - because it's ip only: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for

**Comment by vmuzikar** [comment]
> it may contain a comma separated list and ipv6 without backets

AFAIK that should be fine, no? The parser is [taking](https://github.com/quarkusio/quarkus/blob/841e65940c6a4e923ea98a626bb3ce3353255d5a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ForwardedParser.java#L213-L216) the first IP (which corresponds to the actual client IP), and in case of IPv6 without brackets it just [returns](https://github.com/quarkusio/quarkus/blob/841e65940c6a4e923ea98a626bb3ce3353255d5a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ForwardedParser.java#L221-L238) it as is.

**Comment by shawkins** [comment]
> The parser is [taking](https://github.com/quarkusio/quarkus/blob/841e65940c6a4e923ea98a626bb3ce3353255d5a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ForwardedParser.java#L213-L216) the first IP

Sorry, I was looking only at the parsing routine and missed that it was passing in only the first. 

> and in case of IPv6 without brackets it just [returns](https://github.com/quarkusio/quarkus/blob/841e65940c6a4e923ea98a626bb3ce3353255d5a/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ForwardedParser.java#L221-L238) it as is.

My confusion remains there - the documentation suggests only ips are supported.

**Comment by vmuzikar** [comment]
> My confusion remains there - the documentation suggests only ips are supported.

You mean that X-Forwarded-For should not contain a port? Yes, I think so as well, looking at a [semi-official docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) too. For port there's a dedicated X-Forwarded-Port. @shawkins Do you want to create an issue in Quarkus (since you've found it :))?

**Comment by shawkins** [comment]
> Do you want to create an issue in Quarkus (since you've found it :))?

Sure, I'll create something.

**Comment by shawkins** [comment]
To follow up - I closed https://github.com/quarkusio/quarkus/issues/40416 because it overly complicated the existing tests to rely upon it being IP only. Also some implementations do provide the port according to the wikipedia entry (no citations though).

@gildasleaute did you get a chance to confirm your headers per https://github.com/keycloak/keycloak/issues/28669#issuecomment-2086331127
