### ISSUE TITLE
Cannot verify dynamic issuer with Entra ID (multi-tenant) when linking Entra ID / Microsoft as OpenID Connect identity provider

### ISSUE THREAD

**Issue by samuli-rukkila** [keycloak/keycloak#28662]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

It doesn't seem to possible make multi-tenant Entra ID work as a identity provider in Keycloak while also verifying Issuer-value. 

We've configured the IDP like this:
![entra id openid connect settings](https://github.com/keycloak/keycloak/assets/105220225/d5fd8046-c292-40a5-92a3-c3850651b182)

When using Entra ID as a multi-tenant broker, Issuer uri varies on the tenant ID provided from the Entra ID but it seems like we can only include a static url in the Issuer-field resulting in error.

Even when filling the discovery endpoint with Entra's well-known location: `https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration` it does paste the value of `https://login.microsoftonline.com/{tenantid}/v2.0` to Issuer-field. 

**I presume** from a security standpoint that it is necessary to verify the Issuer-value? Any way to make it dynamic?

We tried some other Issuer-values:
- https://login.microsoftonline.com/{tenantid}/v2.0 <-- won't work
- https://login.microsoftonline.com/${tenantid}/v2.0 <-- won't work
- https://login.microsoftonline.com/organizations/v2.0 <-- Microsoft doesn't recognize this

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak would be able to read the dynamic Issuer-uri from Microsoft's well-known -documentation and verify it.

### Actual behavior

Keycloak can only read the static URI placed in the Issuer-field, resulting in error:
```
Wrong issuer from token. 
Got: https://login.microsoftonline.com/<customer-tenant-id>/v2.0 
expected: https://login.microsoftonline.com/{tenantid}/v2.0
```

### How to Reproduce?

1. Create new app registration in Microsoft Entra admin center and include necessary configurations to make it multi-tenant 
![azure configuration multi-tenant](https://github.com/keycloak/keycloak/assets/105220225/034590d3-2f79-4c6c-941f-b27a967417c9)
2. Create new OpenID connect identity provider in Keycloak and fill the information so any Azure tenant can use the IDP in Keycloak, for the **Issuer**-field, include `https://login.microsoftonline.com/{tenantid}/v2.0` 
3. Try to login with Microsoft to any client, an error will popup

**Comment by sschu** [comment]
@samuli-rukkila Every tenant in Entra ID is a separate identity provider. This makes a lot of sense because it belongs to a different organization, has different user and administrators, different policies etc. This means you should not just trust Entra ID globally to provide identity information, you should decide that on a tenant level. So you will have to create one identity provider per Entra ID tenant.

**Comment by samuli-rukkila** [comment]
@sschu in our case we don't know the amount of entra ID tenants which will login via Microsoft to our SSO since it's supposed to be available to _all_ Microsoft company/school -accounts. Seems like an impossible task to include every Entra ID manually as our identity providers.

**Comment by sschu** [comment]
I am not an Entra ID expert but I would assume the way this could be supported is by integrating with your tenant and then configure cross-tenant access to your tenant by other tenants (AFAIK this would mean you would have guest users in your tenant coming from other tenants).
In any case, you need to define which tenants you trust. If you just trust any tenant in Entra ID, your whole authentication process is worthless. I can just set up my own tenant in Entra ID and give users there arbitrary email addresses for example.

**Comment by samuli-rukkila** [comment]
Good to know, thank you for the insight. 

Users cannot register to our Keycloak instance and upon the first time user clicks on the Microsoft-button and if an identical email is found, user still needs to verify the linking via an additional email confirmation. 

This does not need to be done if user is already logged in and decides to link the IDP to its user from user-profile.

**Comment by pedroigor** [comment]
I'm not very familiar with Entra ID and I'm not sure if I understand what we could improve.

IIRC, in the past we had https://github.com/keycloak/keycloak/pull/11207 to support single-tenant. Is this issue about supporting the `multitenant` setting in Entra ID?

Or are we talking about some other issue after the suggestion from @sschu here https://github.com/keycloak/keycloak/pull/11207?

**Comment by pedroigor** [comment]
@sschu I see and I agree with you. I'll add this one as a low priority to see if others from the community have similar use case so we can discuss more the details about this improvement on how you setup brokers in Keycloak.

But yeah, even though each one has their own requirements, I don't see it now as a built-in capability in Keycloak, mainly from a security PoV, as you mentioned, where we have a broker for multiple identity sources, each one with potentially different security requirements, flows, etc.

**Comment by carlin-q-scott** [comment]
I was able to use the Entra ID common issuer with Keycloak 21. This is a loss of functionality. It should be up to the Keycloak admin to decide if they are OK with a wildcard in the issuer field.

There's a decent mitigation for this issue, which is to supply a comma separated list in the issuer field for the IdP configuration in Keycloak:
`https://login.microsoftonline.com/a-microsoft-tenant-id/v2.0,https://login.microsoftonline.com/another-microsoft-tenant-id/v2.0`

**Comment by Asamsig** [comment]
@sschu 
> This means you should not just trust Entra ID globally to provide identity information, you should decide that on a tenant level. So you will have to create one identity provider per Entra ID tenant.

The Tenant `organizations` is how you configure it, if you want to leverage Entra ID as a "social" login for business accounts. As far as I know, the user principal name is verified, and is the email of the user, not be be confused with the `email`-property.

So it certainly does have a use-case, in situations where you want tighter restrictions on which Microsoft users can enroll, but still be open by default.

Personally, we've used this approach with our own whitelisting of the TLD, instead of configuring each tenant.

**Comment by tajakobsen** [comment]
I have solved this in another project by doing a replacement of `{tenantid}` with the `tid` from the claim.

```java
public String validate(String token, String issuer) {
    ....
    String tid = decodedJWT.getClaim("tid").asString();

    String iss = issuer.startsWith( "https://login.microsoftonline.com/{tenantid}/" ) && tid != null
                ? issuer.replace("{tenantid}", tid)
                : issuer;
    ...
}
```
