### ISSUE TITLE
Attributes tab missing from user details page

### ISSUE THREAD

**Issue by jmrithyunjaya** [keycloak/keycloak#28687]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Attributes tab is missing from user details page ( Users -> selected a user -> Attributes tab missing).
This is required to create a custom attribute to test my SP application.
<img width="1120" alt="Screenshot 2024-04-12 at 16 09 49" src="https://github.com/keycloak/keycloak/assets/97272697/d20b7503-80a5-4c96-ac47-0b8ee2bfdc61">

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Attributes tab should be available for all users.

### Actual behavior

No Attributes tab for users 

### How to Reproduce?

Login to admin console 
navigate to users tab -> user details

**Comment by malavmevada** [comment]
Hey @stianst, I would like to work on this issue.

**Comment by sschu** [comment]
The attributes tab only appears if you have enabled `Unmanaged Attributes` in the realm settings for your realm. Can you check if this is the case?

**Comment by malavmevada** [comment]
> The attributes tab only appears if you have enabled `Unmanaged Attributes` in the realm settings for your realm. Can you check if this is the case?

Hey @sschu you tell me where can I find Unmanaged attributes in realm settings ?

**Comment by malavmevada** [comment]
@sschu , here is the issue regarding unmanaged attributes.

https://github.com/keycloak/keycloak/issues/25528#issue-2039369384

**Comment by sschu** [comment]
The setting is directly on the `General` tab of the `Realm Settings` menu, 8th line.

**Comment by suneclausen** [comment]
The release note talks about it: https://www.keycloak.org/docs/24.0.0/upgrading/#user-profile-changes 
and it links to the server administration guide which explains why the settings is so: https://www.keycloak.org/docs/24.0.0/server_admin/#user-profile 

I have a follow up question; the documentation notes that one should migrate any custom attributes to the user-profile. Is this just taking any custom attributes and adding them or is there more to it?
I assume that the general goal is to move away from unmanaged attributes as this is not the default setting on keycloak? or am I misunderstanding the intended use of attributes?

**Comment by sschu** [comment]
@suneclausen The idea is to move away from Unmanaged Attributes where this is currently possible. This means you have a well-known set of attributes where you know names and possible values upfront. Then you should go ahead and define your attributes in your user profile.
For cases where the names are dynamically added at runtime, you will still need unmanged attributes as of now.
