### ISSUE TITLE
Keycloak theme Language Dropdown Selector does not work anymore if scripts=js/script.js is used in theme.properties

### ISSUE THREAD

**Issue by Sieboldianus** [keycloak/keycloak#28692]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I apply minor modifications to the Keycloak v2/v3 theme. One of those is adding a custom script and loading it, [according to the docs](https://www.keycloak.org/docs/latest/server_development/#adding-a-script-to-a-theme), with `scripts=js/script.js`. However, when adding this line to `theme.properties`, it is not possible anymore to select the language:

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Lanuage dropdown shows available languages. When I comment out:

```js
##scripts= js/script.js
```

this works as expected:

[selector2.webm](https://github.com/keycloak/keycloak/assets/13646666/a1334b08-ecfb-4fa8-a56c-0cb2cc7a097f)

### Actual behavior

Language dropdown does not appear on click.

[selector.webm](https://github.com/keycloak/keycloak/assets/13646666/f6b19f19-965c-491e-bd86-e52fe5ab6430)

### How to Reproduce?

Follow the docs to add a custom script:

> For example, to add `script.js` to the `mytheme`, create `themes/mytheme/login/resources/js/script.js` with the following content:

```js
alert('Hello');
```

> Then edit `themes/mytheme/login/theme.properties` and add:
```js
scripts=js/script.js
```

### Anything else?

This bug only applies if using `keycloak.v2` in `theme.properties`:
```
parent=keycloak.v2
import=common/keycloak
```

Language dropdown works as expected for theme v1:
```
parent=keycloak
import=common/keycloak
```
```[tasklist]
### Tasks
```

**Comment by rmartinc** [comment]
@Sieboldianus I have tested and I think this is already fixed in the main branch. Can you please test with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?

My feeling is that it was fixed by this [commit](https://github.com/keycloak/keycloak/commit/fe538cbb7210ace955478030089de6a131a8156d) (although not completely sure).

**Comment by Sieboldianus** [comment]
Thank you. I will test asap and edit this post!
