### ISSUE TITLE
Unable to fetch realm names when contains special characters

### ISSUE THREAD

**Issue by jhchong92** [keycloak/keycloak#28702]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After creating a realm with special characters (e.g. %22-239123923), the realm dropdown fails to populate.
The failing API: 
<img width="1258" alt="image" src="https://github.com/keycloak/keycloak/assets/16560316/326f6cfc-fb62-4fa2-959e-328c71c827a6">

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Realm names should load properly

### Actual behavior

Realm dropdown is empty
<img width="310" alt="image" src="https://github.com/keycloak/keycloak/assets/16560316/aefdf598-df8b-4f26-aa16-9153b544d00b">

### How to Reproduce?

1. Start Keycloak server
2. Create realm with special characters
3. Check Realm dropdown after realm created successfully

### Anything else?

This issue also affects Users, Groups and Sessions page.

**Comment by jonkoops** [comment]
Can confirm this issue, since there is already a PR I've gone ahead and assigned this to @jhchong92.
