### ISSUE TITLE
Document Keycloak Organization

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28731]
For the first release of Keycloak Organizations as a technology preview feature, we need to write a documentation covering the core capabilities we are delivering so that people can understand what is it about, how it works, and how to use it.

As a proposal, we could introduce the following sections to the server administration guide:

* Managing Organizations (what is the feature about and what it tries to solve)
* * Creating an Organization (how to create, update, delete, and query organizations)
* * Managing Domains (what is a domain, its role in an organization, and how to manage them)
* * Managing Attributes (how to manage organization attributes. I think a specific section is needed as it will expand later once we support "organization profiles".
* * Managing Members (how to create, update, delete, and query members)
* * Managing Identity Providers (how to create, update, delete, and query the identity providers)
* * Onboarding Members using an Identity Provider (how to self-register members through a broker)
* * Onboarding Members using Invitation Links (how to self-register members through invitation links)
* * Authenticating to an Organization (how members are authenticated to organizations and what is available from tokens issued by the server)

**Comment by zsafder** [comment]
can I know where to find the documentation for "Managing Members (how to create, update, delete, and query members)"
