### ISSUE TITLE
Provide UIs in the amdinistration console for organizations

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28735]
For the first release, we need a set of UIs in the administration console to allow a Keycloak Administrator to manage organizations.

Based on the set of capabilities we are delivering in the first version of Keycloak Organizations, we need the following UIs and behavior:

* A switch at the realm settings to enable and disable organization support to a realm
* A menu item to have access to managing organizations
* Managing Organization
* * A set of UIs to allow listing, searching, creating, updating, and deleting organizations
* Managing Members
* * A set of UIs to allow listing, searching, creating, updating, and deleting organization members
* Manage Organization Attributes
* * A set of UIs to allow managing organization attributes
* Manage Identity Providers
* * A set of UIs to allow managing identity providers for an organization
* Manage Invitation Links
* * A set of UIs to allow sending invitation links and list open invitations

**Comment by ssilvert** [comment]
> * Manage Identity Providers
> * * A set of UIs to allow managing identity providers for an organization

I seem to remember we discussed that the first iteration of this would only allow one identity provider.  Is that correct or should we have full CRUD and searching?

**Comment by xianli123** [comment]
> Manage Invitation Links
A set of UIs to allow sending invitation links and list open invitations

@pedroigor 
IIRC, the Invitation will not be covered in the first round. Right? cc @ssilvert

**Comment by pedroigor** [comment]
> > * Manage Identity Providers
> > * * A set of UIs to allow managing identity providers for an organization
> 
> @pedroigor I seem to remember we discussed that the first iteration of this would only allow one identity provider. Is that correct or should we have full CRUD and searching?

We are changing to support multiple identity providers.

**Comment by pedroigor** [comment]
> @pedroigor IIRC, the Invitation will not be covered in the first round. Right? cc @ssilvert

We are adding support for invitations in this first iteration.

**Comment by xianli123** [comment]
Hi @pedroigor I have a question about the users who are invited to the org. How to show the invited members? Is there a difference between an invited user and a created user?

**Comment by pedroigor** [comment]
> Hi @pedroigor I have a question about the users who are invited to the org. How to show the invited members? Is there a difference between an invited user and a created user?

@xianli123 Sorry, not sure if I understand the question. I'm also adding @alice-wondered.

Can you please elaborate on what you mean by "created user"?

**Comment by xianli123** [comment]
The 'created users' means the members who are created in the organization. @pedroigor 
![image](https://github.com/keycloak/keycloak/assets/53931519/760cde1b-7c5a-4f2f-8080-d900f171ed9b)

**Comment by pedroigor** [comment]
@xianli123 Based on our last discussions, that `Add member` should be able linking an existing realm user to an org rather than creating + linking within the scope of the Organization UI/API.

**Comment by vramik** [comment]
@pedroigor I believe the question is whether we want to show users which are not yet members of the organization but there were invited already? Is that right @xianli123?

**Comment by xianli123** [comment]
@vramik You pointed out the further question that I had. 😄 If the invited users didn't receive or accept the invitation, how to show this kind of user?
