### ISSUE TITLE
External Infinispan as cache - Part 4 / user + client sessions online + offline

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#28755]
### Description

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Motivation

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Details

Final part!
Creates a new provider implementation of `UserSessionProvider` and remote-only caches for the latest 4 caches.

**Comment by ahus1** [comment]
Closing this issue as it has been merged to main.
