### ISSUE TITLE
External Infinispan as cache - Part 3 / login failures cache

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#28754]
### Description

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Motivation

See Part 1: https://github.com/keycloak/keycloak/issues/28140

### Details

Part 3 of the series `External Infinispan as cache`

This part will implement `UserLoginFailureProvider` which provides a remote only `loginFailures` cache.

**Comment by ahus1** [comment]
PR has been merged to the feature branch, closing this issue
