### ISSUE TITLE
Doublecheck Keycloak pipelines

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28777]
This task is about doublecheck with QA team how to handle keycloak-adapters-pipeline and remove the stuff from it when we're removing various OIDC/SAML Java adapters from the Keycloak codebase.

Just noticed that QA team is still using keycloak-adapters-pipeline in latest Keycloak main to test various legacy stuff like for instance Fuse adapter - https://github.com/keycloak/keycloak/pull/27027

Not sure if we (as core-clients) are supposed to update pipelines or if this is going to be done by QA team. This is to be discussed...

**Comment by mposolda** [comment]
Closing this as this was clearified during discussion with @miquelsi and @stianst .

Everything can be removed in testsuite in Keycloak main and in Keycloak 25 release. Old RH-SSO adapters are tested as part of old pipeline. The old pipeline will support using latest Keycloak server with the old adapters.

**Comment by miquelsi** [comment]
Currently the only way of testing legacy Springboot and Fuse adapters with main Keycloak is from main Keycloak itself. These adapter tests need a Keycloak instance running on the same JVM, and it's not possible to run the tests with a remote Keycloak instance (like EAP adapters can do). 

I'm still thinking how to test it, but for now I would keep Springboot and Fuse adapter tests code upstream.

**Comment by mposolda** [comment]
I am closing this as we have tasks created for testing RHSSO 7.6 adapters with latest Keycloak / RHBK.
