### ISSUE TITLE
Remove old-WildFly, EAP 7.4 and 6.4 SAML adapters

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28785]
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

Maybe this was already done in Keycloak 24 or earlier (to be doublechecked as part of this task).

**Comment by douglaspalmer** [comment]
I'm not sure what we can remove here. keycloak-saml-wildfly-subsystem is required by keycloak-saml-wildfly-elytron-adapter. I think we could remove keycloak-saml-wildfly-elytron-jakarta-adapter and keycloak-saml-wildfly-jakarta-subsystem.
