### ISSUE TITLE
Remove servlet filter saml adapters

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28786]
May include codebase, distribution, documentation, testsuite (To be doublechecked what exactly as part of this task...).

**Comment by jellisgwn** [comment]
Will there be any kind of "migration guide" for those of us dependent on the SAML Servlet Filter?

I'm "surprised" that this is being removed right after you went to the effort of upgrading it to Jakarta. Is the maintenance such a burden? it felt like the code never really changed between releases...
