### ISSUE TITLE
Can we remove whole keycloak-adapter-core module?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28791]
This can be done just if all other Keycloak OIDC java adapters can be removed (including undertow adapter etc) and should be done after their removal.

In this case, we can probably remove this whole section https://www.keycloak.org/docs/latest/securing_apps/index.html#keycloak-java-adapters .

**Comment by douglaspalmer** [comment]
Depends upon: https://github.com/keycloak/keycloak/issues/29189
