### ISSUE TITLE
Decide how organizations and related changes to a realm will be enabled/disabled

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#28804]
Keycloak organization introduces changes to authentication flows so that specific flows/steps are executed to authenticate organization members.

We need to decide what is the best UX so that administrators do not need to execute manual steps to enable/configure organization behavior to a realm.

Perhaps this is more a general question on how we should proceed when we have features that need to update the realm configuration in order to fully enabled it to a realm.

**Comment by vramik** [comment]
As discussed, for now there will be a switch to enable/disable organization for a realm in realm settings page.
