### ISSUE TITLE
Available roles search for user is not working as expected

### ISSUE THREAD

**Issue by thilak009** [keycloak/keycloak#28828]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Search functionality in available roles for user API is not working as expected, it is returning all roles
The following API
```cURL
curl 'https://<host>/admin/realms/<realm>/users/<user_id>/role-mappings/realm/available?first=0&max=101&search=thilak' \
  -H 'authority: <host>' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'authorization: bearer <token>' \
  -H 'cookie: <cookie>' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
```

returns all roles available(which are around 14k) instead of returning no roles as there is no role called `thilak` or no role has a sub string called `thilak`

search on the realm roles page works as expected, the corresponding API on `Realm roles` page is
```cURL
curl 'https://<host>/admin/realms/<realm>/roles?first=0&max=101&search=thilak' \
  -H 'authority: <host>' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'authorization: bearer <token>' \
  -H 'cookie: <cookie>' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
```

### Version

20.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

The search should return the appropriate matching roles for users

### Actual behavior

the search on available roles returns all roles instead regardless of what the search string is

### How to Reproduce?

spin up a keycloak container of version `20.0.1` 
- create a realm
- create a user
- create multiple realm roles
- go to `Role mapping` for the created user and click on `Assign role` button
- try searching for a role that does not exist or a role that exists (one from the ones you created)
- the search API returns all available roles that you created instead of either returning matched roles(if a match exists) or no roles (if nothing matched)

**Comment by thilak009** [comment]
ok, i have tested the same thing on version `24.0.3` which is the latest version
here i see that there are 3 problems

1. the API for getting available realm roles for a user is giving more results in response than asked for
```cURL
curl 'http://localhost:8081/admin/realms/dummy/users/bcdb0611-6952-4a41-b7fb-0c98f2ce2b06/role-mappings/realm/available?first=0&max=101' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: sgTheme=light; sgView=normal' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authorization: Bearer <token>' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'
```
the above request returns `387` roles (there are around 10k roles in total), instead of `101`, which is what the `max` query param in the API asks for

2. because the above only returns `387` results in response, when i search for a role which is not in this response, the UI does not call any API to search the role, UI is only relying on roles obtained in the initial API call and is not calling API for search
3. because UI is not calling the API to search, i tried the search myself by calling the API, here is the corresponding cURL
```cURL
curl --location 'http://localhost:8081/admin/realms/dummy/users/bcdb0611-6952-4a41-b7fb-0c98f2ce2b06/role-mappings/realm/available?first=0&max=101&search=role555' \
--header 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'Connection: keep-alive' \
--header 'Cookie: sgTheme=light; sgView=normal' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
--header 'accept: application/json, text/plain, */*' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--header 'Authorization: Bearer <token>'
```
this should return roles which have the prefix `role555` or the role exactly equals that, but instead this API returns response which contain roles like `role_7`, `role4`, `role133` etc.., i am guessing the search is not working here

**Comment by sschu** [comment]
This is definitely not a bug since neither searching nor pagination are currently supported in this API, see the documentation: https://www.keycloak.org/docs-api/24.0.3/rest-api/index.html
This could be an enhancement, though.

**Comment by thilak009** [comment]
hm, thanks for the clarification, i see that the API does not have pagination nor search params, but i think the UI adds the query params cause the UI component is generic?
UI sending in those query params is what made me assume that the API supports it, should have checked the API docs as well, my bad
I am not able to reproduce the search on client side not working on my `20.0.1` version keycloak deployment, works fine when tested with similar amount of roles on local with latest version, so closing the issue

But i think the UI can be made to not send in the query params, also if pagination and search for this API is a good enhancement i can probably take a look at it if i get some time and if i don't feel the codebase is too much for me to grasp :)
