### ISSUE TITLE
Keycloak Operator 24.x - the keycloak custom image tag is being overwritten with nightly pull

### ISSUE THREAD

**Issue by OS-emanuelbrici** [keycloak/keycloak#28825]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Keycloak operator versions [24.0.2, 24.0.3, nightly, latest] are overwriting the keycloak image to nightly.

This might be related to these
https://www.keycloak.org/2024/03/keycloak-2401-released
https://github.com/keycloak/keycloak/issues/27500

![image](https://github.com/keycloak/keycloak/assets/88198289/8b623ac5-db5a-4564-ab95-e3dd135597f4)

I checked the repo and seeing this:
![image](https://github.com/keycloak/keycloak/assets/88198289/00fa7023-87d2-42d0-8c38-d179b1d2f385)

### Version

24.x

### Regression

- [X] The issue is a regression

### Expected behavior

The operator should not overwrite the custom keycloak image.

### Actual behavior

The operator is overwriting the custom keycloak image.

### How to Reproduce?

Deploy the keycloak operator with a custom keycloak image.

### Anything else?

I set the operator version to 23.0.4 and the deployment of my custom keycloak image that is on 24.0.2 deploys successfully.

**Comment by shawkins** [comment]
> Deploy the keycloak operator with a custom keycloak image.

Can you elaborate on what this means - is the custom image being set in the keycloak CR, or via the operator Deployment env variables?

**Comment by OS-emanuelbrici** [comment]
Hi @shawkins,

The custom image is being set in the operator Deployment env variables.

As defined here: https://github.com/keycloak/keycloak-k8s-resources/blob/main/kubernetes/kubernetes.yml#L206

Thanks

**Comment by shawkins** [comment]
Deleted my previous comment - I didn't double check that the kubernetes.yml link shown above is quite out of date. If you are going to deploy directly using the yaml, then you should do so using the corresponding release tag - e.g. https://github.com/keycloak/keycloak-k8s-resources/blob/24.0.3/kubernetes/kubernetes.yml - note that is using the correct env variable.
