### ISSUE TITLE
Inconsistent Group Ordering in Keycloak API Responses For Client Policies Causing Drift Detection Challenges

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [keycloak/keycloak#28824]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

When querying the Keycloak API for fine-grained client policies related to groups and roles, the response does not maintain consistent key-value ordering, as it is not sorted. This inconsistency is evident in subsequent requests, where the order of groups can vary randomly. This random sorting poses a challenge for drift detection when using the Terraform Keycloak provider because each Terraform run encounters a different order.
- https://keycloak.example/auth/admin/realms/spendesk/clients/c0737575-1ded-4d8b-b3f9-0a1df03b5da1/authz/resource-server/policy/group/bc1fa8c0-07f5-4315-af46-ae337e8fc134
```
{
	"groups": [
		{
			"id": "20e378ce-d343-421d-a91e-6de52bebae19",
			"extendChildren": false
		},
		{
			"id": "3544ce6e-5dc1-498e-ba42-9ccb64a1b74d",
			"extendChildren": false
		},
		{
			"id": "e7ad72ec-f146-45be-b89c-180f9d4b8aae",
			"extendChildren": false
		}
	]
}
```
next request:
```
{
	"groups": [
		{
			"id": "3544ce6e-5dc1-498e-ba42-9ccb64a1b74d",
			"extendChildren": false
		},
		{
			"id": "e7ad72ec-f146-45be-b89c-180f9d4b8aae",
			"extendChildren": false
		},
		{
			"id": "20e378ce-d343-421d-a91e-6de52bebae19",
			"extendChildren": false
		}
	]
}
```

While it's possible to configure sorting within the Terraform provider, a more desirable solution would be to have the groups and roles lists consistently sorted,  by their IDs. This would ensure predictability and stability in the Terraform workflow.

In contrast, when querying a client policy for users, the response consistently returns sorted results. For instance, in the provided example, the list of users is always sorted, enabling more reliable integration with Terraform and other automation tools.

- https://keycloak.example/auth/admin/realms/spendesk/clients/c0737575-1ded-4d8b-b3f9-0a1df03b5da1/authz/resource-server/policy/user/26754857-3af8-4640-9c60-5a74ad563e8c

```
{
	"users": [
		"788efe81-9fce-46e2-95b7-091cb0c7db8f",
		"87afd2d3-6ff6-4204-a25e-447db7e09cfd"
	]
}
```

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

I would like that in client policy responses for roles and groups, the items are returned sorted based on id value.

### Actual behavior

Results are randomly sorted

### How to Reproduce?

querying client policy groups and roles endpoints:
- https://keycloak.example/auth/admin/realms/spendesk/clients/c0737575-1ded-4d8b-b3f9-0a1df03b5da1/authz/resource-server/policy/group/bc1fa8c0-07f5-4315-af46-ae337e8fc134

**Comment by pedroigor** [comment]
@marcportabellaclotet-mt Does it work for you https://github.com/keycloak/keycloak/pull/28940?

**Comment by marcportabellaclotet-mt** [comment]
Thanks for looking into this @pedroigor 
Yes, it seems to solve the issue!
