### ISSUE TITLE
SAML clients no longer allow relative Master SAML Processing URLs

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#28832]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

After upgrading to Keycloak 24.0.3 some SAML client configurations could no longer be applied.

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

If a root url is configured for a SAML client it should be possible to configure relative Master SAML Processing URLs.

### Actual behavior

Even with a root URL configured, trying to store a saml client with a relative Master SAML Processing URL will lead to the error:  `Client could not be updated: Master SAML Processing URL is not a valid URL`

![image](https://github.com/keycloak/keycloak/assets/314690/0be41cd4-63d7-48b1-814d-a62d8bc75603)

### How to Reproduce?

- Create a saml client with a root url
- Configure a relative Master SAML Processing URL 
- click save

An error message should appear.

Note that the `Master SAML Processing URL` is stored in the   `adminUrl` attribute.

Here is a client export for testing:
```json
{
  "clientId": "acme-webapp-saml-node-express",
  "name": "Acme Web App SAML Node Express",
  "description": "",
  "rootUrl": "https://apps.acme.test:4723",
  "adminUrl": "/saml",
  "baseUrl": "/app",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "xxxx",
  "redirectUris": [
    "/saml/consume"
  ],
  "webOrigins": [],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": false,
  "serviceAccountsEnabled": false,
  "publicClient": false,
  "frontchannelLogout": true,
  "protocol": "saml",
  "attributes": {
    "saml.assertion.signature": "true",
    "client.secret.creation.time": "1689235223",
    "saml.force.post.binding": "true",
    "saml.multivalued.roles": "false",
    "saml.encrypt": "false",
    "frontchannel.logout.session.required": "false",
    "saml.server.signature": "true",
    "saml.server.signature.keyinfo.ext": "false",
    "saml.signing.certificate": "dummyCert",
    "saml.artifact.binding.identifier": "HC5ftXuLr0FUnJUosZarVSvzZh0=",
    "saml.artifact.binding": "false",
    "backchannel.logout.session.required": "false",
    "saml.signature.algorithm": "RSA_SHA256",
    "saml_force_name_id_format": "false",
    "saml.client.signature": "true",
    "saml.authnstatement": "true",
    "display.on.consent.screen": "false",
    "saml.signing.private.key": "dummyKey",
    "saml_name_id_format": "username",
    "saml.allow.ecp.flow": "false",
    "saml.onetimeuse.condition": "false",
    "saml_signature_canonicalization_method": "http://www.w3.org/2001/10/xml-exc-c14n#",
    "saml.server.signature.keyinfo.xmlSigKeyInfoKeyNameTransformer": "NONE"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": false,
  "nodeReRegistrationTimeout": -1,
  "protocolMappers": [
    {
      "name": "acme-saml-firstname",
      "protocol": "saml",
      "protocolMapper": "saml-user-property-mapper",
      "consentRequired": false,
      "config": {
        "attribute.nameformat": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
        "user.attribute": "firstName",
        "friendly.name": "givenName",
        "attribute.name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
      }
    },
    {
      "name": "acme-saml-lastname",
      "protocol": "saml",
      "protocolMapper": "saml-user-property-mapper",
      "consentRequired": false,
      "config": {
        "attribute.nameformat": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
        "user.attribute": "lastName",
        "friendly.name": "surname",
        "attribute.name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
      }
    },
    {
      "name": "acme-saml-email",
      "protocol": "saml",
      "protocolMapper": "saml-user-property-mapper",
      "consentRequired": false,
      "config": {
        "attribute.nameformat": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
        "user.attribute": "email",
        "friendly.name": "email",
        "attribute.name": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
      }
    }
  ],
  "defaultClientScopes": [],
  "optionalClientScopes": [],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}
```

### Anything else?

Using an absolute URL works:
![image](https://github.com/keycloak/keycloak/assets/314690/3fffe549-6998-4b54-b0f6-b9834dfd763d)

**Comment by rmartinc** [comment]
@thomasdarimont This was done because a security issue and I think that using non absolute URLs is not a valid config. The saml adapters does not use the base url to compute a full URL for the saml processing URL. It just uses what you put there. So, if you are using `/saml` and POST binding, the form is created with:

```html
<form name="saml-post-binding" method="post" action="/saml">
```

Which in my case returns a 404 because it's doing a post against the same keycloak server to `/saml` page that doesn't exist.

Am I missing something?

**Comment by thomasdarimont** [comment]
@rmartinc thanks for taking a look. That' strange. I have a SAML client application that worked fine with `/saml` as a relative URL to the root URL. I just gave it a test and see that the SAML processing endpoint is used during logout, where Keycloak sends a POST request to the `Master SAML Processing URL` after logout. If I leave the `Master SAML Processing URL` empty it produces an error. Now I must specify the absolute URL, in KC 24.0.2 the relative URL worked too.

**Comment by rmartinc** [comment]
In my tests with 24.0.2 I experienced the same error, page not found with the POST sent to the same keycloak server with `/saml`. That's why I said that I think that the master processing URL is not using the root URL to create a full URL.

![Screenshot from 2024-04-17 14-55-33](https://github.com/keycloak/keycloak/assets/26901232/b370b428-a76c-4878-9f96-d0d15b34a8fa)

**Comment by thomasdarimont** [comment]
Okay, thanks for checking. I did a mistake when checking my example, and I cannot recreate the example, but I'm sure that this worked in 23.x.

My example was not using a keycloak SAML Adapter, since it was a nodejs app with node-saml/passport-saml.
See: https://github.com/thomasdarimont/keycloak-project-example/tree/main/apps/acme-webapp-saml-node-express

The [/saml endpoint](https://github.com/thomasdarimont/keycloak-project-example/blob/main/apps/acme-webapp-saml-node-express/src/express.js#L132) in the app was correctly called, even with the "Master SAML processing URL" in the admin ui being set to just `/saml`.

I'm fine with having an absolute URL here, however I assumed that if an root-url is configured for an application, that all other URIs could be relative to the root-uri.

If this isn't the case anymore we should explicitly document that at least.

**Comment by rmartinc** [comment]
I have tested with keycloak 19 and it's the same behavior. My feeling is that (at least with SAML) this has been always worked this way (or for very long time). The security change is only for SAML clients in the SAML processing URLs, because for OIDC there was some checks yet. So I think that nothing has changed with the security change. AFAIK in SAML the only part that uses the root URL are valid redirect URIs and that continue working as expected with 24.0.3.

@thomasdarimont I think that there is nothing to document. The configuration of relative URLs in the SAML processing URLs have never worked, and the security issue just added the test in those URLs. So, if you agree, I will close the issue as this is working as expected IMHO.

**Comment by thomasdarimont** [comment]
@rmartinc thanks for looking into this. I'm fine with closing this issue. It's still suprising to me that the URL configurations for SAML clients work differently than OIDC clients.
