### ISSUE TITLE
keycloak providing incorrect error message when invalid ldap server is present in environment

### ISSUE THREAD

**Issue by inshitaM** [keycloak/keycloak#28834]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When an invalid ldap server is added in the environment, and we try to perform any create, delete or update  operations on users, it fails with unknown error:500. Expected : ldap specific error 

### Version

23.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Invalid ldap server
 or
 any ldap specific error with appropriate error code

### Actual behavior

500 Internal Server Error : unknown_error

### How to Reproduce?

1. Create  invalid ldap server, for example: POST /rest/v2/ldaps
{
  "type": "AD",
  "server_addresses": [
    "INVALID.local"
  ],
  "server_port": 389
} 

2. try to create or update a user, unknown error will be thrown.

**Comment by martin-kanis** [comment]
@inshitaM Thanks for reporting this. Keycloak allows to test connection and authentication to your LDAP server when adding it via UI. I recommend to leverage it to prevent adding invalid config. ATM we don't have explicit validation when adding a new LDAP and I don't see it as priority given the team's capacity.
