### ISSUE TITLE
Advanced Claim to Role Mapper

### ISSUE THREAD

**Issue by brianmori** [keycloak/keycloak#28836]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Hi,

I am using the latest version of Keycloak and I have configured in the "Identity Providers" an OpenID Connect provider integrated with AzureAD.

The SSO is working with AzureAD and I want to assign a certain keycloak role, based on a specific AzureAD Group.

AzureAD does not return groups by default and I followed the guide [here](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-group-claims#add-group-claims-to-tokens-for-saml-applications-using-sso-configuration) to add a groups claim

I created a mapper in the OpenID Connect Provider as "Advanced Claim to Role" with the following parameters:

- Sync Mode Override: force
- Claims with Key "groups" and Value the GroupID defined in Azure
- Role -> the role I created in the Client panel 

Documentation: https://keycloak.discourse.group/t/getting-groups-from-azure-active-directory-idp/590/15

As I see the groups is configured as "optional" in AzureAD, could it be the issue?

https://keycloak.discourse.group/t/keycloak-not-getting-the-optional-claims-from-azure-ad/23690

### Version

24.0.2

### Regression

- [x] The issue is a regression

### Expected behavior

Keycloak role added to the token of the user

### Actual behavior

No keycloak role added in the Access or Identity token 

### How to Reproduce?

- Configure an AzureAD Enterprise Application and obtain in the Single Sign On page the client id and secret
- Add in the AzureAD token configuration the "groups"
- Go to Keycloak and create a Client
- Add in the Client create a role to be mapped later
- Create in Keycloak an OpenID Identity Provider
- Add "Advanced Claim to Role" with the following parameters Sync Mode Override: force / Claims with Key "groups" and Value the GroupID defined in Azure / Role -> the role created in the Client panel
- Retrieve Access and ID Token of the user

**Comment by brianmori** [comment]
Hi again,

something strange happened.

I created in the Client Scopes a client scope for the "client" before. I added the predefined mapper "groups" and I repeated the Authorization Flow to obtain a new access token.

This time my JWT token had the role I created:

```
"resource_access": {
    "myclient": {
      "roles": [
        "myclient-admin-role"
      ]
    }
```

I found this behaviour strange and I removed the client scope, and the relative mapper "groups",  to validate if this was the missing step.

I asked another Access Token and my user had still the good role assigned.

It is unclear why it works now. 
I remember I have done the same configuration, without the client scope part, on another keycloak instance with an older version and I have the same behaviour the resource access is missing

**Comment by sschu** [comment]
The "groups" mapper maps Keycloak groups, it does not map the "resource_access" claim so this is unrelated. The advanced-claim-to-role-mapper only has an effect when you actually login via the external IDP and not when you use an existing session. Are you sure this was the case? You can also check in Keycloak if the role was assigned to your user after login so you can check whether the advanced-claim-to-role-mapper works without having to check for clients/scopes/mappers generating the correct token.
