### ISSUE TITLE
V24.0.3 Upgrade Failing to Load Admin Console: Could it be due to changes in redirect URI verification when using wildcards?

### ISSUE THREAD

**Issue by hariubc** [keycloak/keycloak#28859]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The upgrade from v23.0.6 to v24.0.3 seemed to have failed - The test: attempting to access the admin console (a blank page remains). There are no log entries pointing to potential cause (despite setting log to DEBUG).

Wondering if could be the ‘Valid redirect URI’ setting in screenshot below (containing a wildcard):

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

The admin console to load

### Actual behavior

Blank page

### How to Reproduce?

Upgrade from v23.0.6 to v24.0.3 on bare metal - start as production (i.e. not as 'sstart-dev')

**Comment by hariubc** [comment]
Setting on the ve23.0.6 (i.e. prior to upgrade to v24.0.6)

<img width="1045" alt="image" src="https://github.com/keycloak/keycloak/assets/532775/e9134a7c-516c-4186-b93b-2e7f231a9732">

**Comment by hariubc** [comment]
The above was a red herring. Unrelated to the v24.0.3.

The issue was an SPI had incompatible hibernate library for Oracle (and was missed to log)

**Comment by ssilvert** [comment]
@hariubc OK, I'll close this then.
