### ISSUE TITLE
Default cache-config does not start in Windows without any IPv6 address

### ISSUE THREAD

**Issue by fheck** [keycloak/keycloak#28854]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

On Windows (10 and Server 2022 at least) there seems to be a problem with the default infinispan cache if the system has no IPv6 address. 
I tested with an out of the box configuration regarding caching [1] and I could not get the application to start with cryptic error messages regarding the network: `[...] failed setting interface to name:eth5 [...]`. By comparing to an installation on another system I found a difference regarding IPv6 and started to investigate in this direction. Once the system had any interface where a IPv6 address was assigned (e.g. a link-local address on a virtual switch) the application was able to start, deactivating IPv6 brought back the issue.
I was able to reproduce the issue on another system in another network/domain, so a local problem of the specific windows installation/environment is unlikely.

[1] Note: other configurations regarding https and db were made but as far as I can test are irrelevant to the present issue

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

The server starts without errors.

### Actual behavior

The server does not start, the following, cryptic error message can be found in the log (usually twice): 
```
ERROR [org.jgroups.protocols.UDP] (keycloak-cache-init) failed setting interface to name:eth5 (Intel(R) 82574L Gigabit Network Connection) (/10.50.0.120): java.net.SocketException: Invalid argument: no further information
```

### How to Reproduce?

* download the official Keycloak distribution and unpack it into a local directory. 
* configure https, so an optimized start is possible, database seems to be irrelevant for this issue
* execute a `kc.bat build`
* in the Windows adapter settings for all available network adapters, disable the IPv6 protocol 
![image](https://github.com/keycloak/keycloak/assets/17826649/91d6bc00-3334-4fe4-bbee-5888e8336740)
* run  `kc.bat start --optimized`
* observe the mentioned errors in the log, and that the applications then terminates.

**Comment by Pepo48** [comment]
Hi guys,

thanks for the report. Can you, please, try whether setting the `-Djava.net.preferIPv4Stack=true` property helps to solve the issue on your Windows machines?

**Comment by fheck** [comment]
@Pepo48 
It did on one system, but not on the other. There, it also resolved this specific error, but the cache (and with it the whole application) was not able to start anyways. Unfortunately, the problematic system is a client system, where I cannot conduct more tests nor am I able get logs from this system at the moment due to access restrictions.

But if you need additional logs/tests from the system where `-Djava.net.preferIPv4Stack=true` solved it, I can help with that.

**Comment by Pepo48** [comment]
Do you know by any chance whether this issue is specific for the latest release only? Have you experienced it with the previous releases (within the same environment) as well?

**Comment by fheck** [comment]
I'm not quite sure, which version from the 23 release cycle we were initially using, when we made a test-setup earlier this year, but I would guess, based on some leftover files, that it was 23.0.6.
Since I never configured infinispan, but did not run in the same problem then, I guess it is a new behavior since this version. But I cannot say with certainty, that the client system did not have an IPv6 address then.
Though, I might be able to verify (an) older version(s) on my test system tomorrow, if that helps.

**Comment by omasseau** [comment]
I cannot currently try -Djava.net.preferIPv4Stack=true as I do not have access to the machine.
But what I can already say is that we got the error with a 22.0.5 version.

**Comment by Pepo48** [comment]
I also forgot to mention that we the usage of this property documented, see [Configuring Keycloak for production](https://www.keycloak.org/server/configuration-production) guide.

It's not a newly introduced issue, nor regression. It's up to JVM behaviour within specific environment (operating system and it's networking + JDK version).

Let me know if I can help any further. Thanks.
