### ISSUE TITLE
Default heap space growth is unexpected

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#28855]
We should consider addressing the tendency for our default image to continually consume more heap space - https://github.com/keycloak/keycloak/issues/28671#issuecomment-2051845838

Based upon https://github.com/keycloak/keycloak/issues/28444#issuecomment-2055586726 this behavior is garbage collector specific and does not line up to most users expectations - even if they set a limit. We may want to consider using ShrinkHeapInSteps to see if forces the default vm to give up heap space more rapidly.

Also relates to #20780

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/pull/28812#discussion_r1568686881_

**Comment by aldiyar04** [comment]
Hi @shawkins, do you have any updates on this matter?

**Comment by shawkins** [comment]
@aldiyar04 no, not yet.

**Comment by shawkins** [comment]
@kami619 @mabartos @vmuzikar Kamesh you were proposing to remove MinHeapFreeRatio as part of the adjustments away from parallelgc. It sounds like we could be experiencing a phenomonon that is parallelgc specific with our heap space growth. That is the MinHeapFreeRatio is effectively too low and is triggering frequent old generation space growth and without ShrinkHeapInSteps - https://docs.oracle.com/en/java/javase/11/gctuning/factors-affecting-garbage-collection-performance.html - the reclaimation of space is too conservative. So over time we simply consume up to the max heap space.

It could be that #29033 will address this issue as well - either by switching the garbagage collector or by removing or adjusting the MinHeapFreeRatio

**Comment by shawkins** [comment]
Also relates to #28264

**Comment by makekz** [comment]
Hello!
@shawkins do you have any updatesin this case?

**Comment by shawkins** [comment]
@makekz not yet.

@kami619 based upon the latest GC changes does this issue still exist?

**Comment by kami619** [comment]
@shawkins With the move to better defaults and G1GC, we saw a more steady performance of the JVM heap memory,in our tests. We didn't see an issue with heap space to grow without a reason and it was steady in our continuous performance tests as well.

**Comment by shawkins** [comment]
Thanks @kami619 closing as not planned / out-of-date. Affected users should try again with KC 26 and confirm if things are working as expected.

**Comment by makekz** [comment]
@kami619 can you give us recommendations about optimal JavaOPTS you used? Thank you
