### ISSUE TITLE
Master realm can be deleted

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#28896]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

It's possible to delete the `master` realm via admin-ui/-api.
This was not the case in recent versions and resulted in an error message. Starting with KC 24.x, it's possible again! This is also possible with the nightly build.

### Version

24.0.x, nightly

### Regression

- [X] The issue is a regression

### Expected behavior

When trying to delete the `master` realm, the request should result in an error.

### Actual behavior

The request to delete the `master` realm succeeds and afterwards, it's no more possible to manage Keycloak through the admin-ui.

### How to Reproduce?

- create a new, fresh, clean KC environment
- login as master admin
- go to `master` realm -> realm settings
- select "delete realm" in the upper right action drop-down
- realm is being deleted

**Comment by vramik** [comment]
I can confirm it's possible to delete master realm in kc24. There is missing similar check as we have when updating realm: https://github.com/keycloak/keycloak/blob/3e0a1850708b9f1a07e3292c79ef8c84744f2fc1/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L424-L426

In previous version (tested with KC22) the request fails with NPE: 

```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RealmModel.getId()" because "realm" is null
	at org.keycloak.models.cache.infinispan.RealmCacheSession.getClientById(RealmCacheSession.java:1099)
	at org.keycloak.models.cache.infinispan.RealmCacheSession.removeClient(RealmCacheSession.java:587)
	at org.keycloak.services.managers.RealmManager.removeRealm(RealmManager.java:267)
	at org.keycloak.services.resources.admin.RealmAdminResource.deleteRealm(RealmAdminResource.java:481
```

My assumption is that this behavior was fixed and this bug then occurred.

**Comment by Martin-Office** [comment]
Is there a way to reinstall master realm? I cannot recreate the database... Need some guidance on the process.

**Comment by vramik** [comment]
@Martin-Office I am not aware of any way to recreate master realm. I think you'd need to make a fresh install.

**Comment by vramik** [comment]
@Martin-Office I'd suggest to exactly that, there is link to the util class which we've used for dropping all tables in jboss-based containers: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/helpers/DropAllServlet.java

You may find there some useful info, which may help with it. 

Also I'd suggest to create separate database/schema for Keycloak tables.

**Comment by raff897** [comment]
You can do an export from cli (with kc.sh export), it will export json that you need. Then do a fresh install of keycloak and reimport realm and users(with overwrite policy, in order to keep uuid). In this way you have master and your realm.
