### ISSUE TITLE
OIDC: Backchannel logout token should use "typ":"logout+jwt"

### ISSUE THREAD

**Issue by tbroyer** [keycloak/keycloak#28939]
### Description

OIDC Backchannel Logout uses `"typ":"JWT"` in the logout token, whereas it SHOULD ([per spec](https://openid.net/specs/openid-connect-backchannel-1_0.html#CrossJWT)) uses `"typ":"logout+jwt"`.

### Motivation

Besides SHOULD/RECOMMENDED-level spec compliance, Nimbus OAuth2/OIDC SDK's `LogoutTokenValidator` currently requires that the `"typ"`, if present, be `"logout+jwt"`, and will reject Keycloak's logout tokens. It would actually have been better if Keycloak didn't include a `"typ"` at all, as Nimbus SDK would accept a JWT with an absent `"typ"`, but strictly validates the value if present (https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/465).

**Comment by graziang** [comment]
@tbroyer Thanks! As you mentioned for logout token is recommended to use `"typ":"logout+jwt"` for Logout Token:
https://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken

Feel free to send a PR.
