### ISSUE TITLE
Auto-build shouldn't warn about unavailable runtime options

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#28948]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When running Keycloak in auto-build mode, the Picoli class will show a warning when conditional runtime options are used.   

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

No warnings in auto-build around unavailable runtime options, as the user can't really change what they are doing here, as in auto-build both runtime and non-runtime options are passed to the CLI.

Warnings should indicate something that the user should change (which they  can't in this case)

### Actual behavior

```
 (main) The following used run time options are UNAVAILABLE and will be ignored during build time:
        - cache-remote-tls-enabled: Available only when remote host is set.
```

### How to Reproduce?

Note that first #28950 needs to be merged, then the following will reproduce it. AFAIK this is the first time a runtime option is making something conditional.

```
bin/kc.sh start --cache-remote-host=localhost --cache-remote-tls-enabled=false
```

### Anything else?

This happens only when runtime options are the source of the conditional, as here with the `--cache-remote-host`.

**Comment by shawkins** [comment]
~priority-normal
