### ISSUE TITLE
user attribute locale not 

### ISSUE THREAD

**Issue by DaBonse** [keycloak/keycloak#28954]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

If you query `GET /admin/realms/realmName/users/profile/metadata `over the Admin REST API, you will get a json export of the user profile metadata. Compared to `GET /admin/realms/realmName/users/profile/`  there is the attribute `locale` listed as an user attribute. 

`  "attributes": [
    {
      "displayName": "locale",
      "multivalued": false,
      "name": "locale",
      "readOnly": false,
      "required": false,
      "validators": {}
    }, [...]`

But locale is not managed via GUI or /admin/realms/realmName/users/profile.
So I ask myself why is there a hidden user attribute in there.

I think, locale should be a predefined and managed user attribute as username or email.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

locale should be a predefined and managed user attribute.

### Actual behavior

See description on top.

### How to Reproduce?

Create a new realm and query the REST API GET /admin/realms/realmName/users/profile/metadata

**Comment by pedroigor** [comment]
It works like that by design because the locale is related to the localization feature in Keycloak. Weed it in the metadata to be able to render it accordingly in the UI.

Even tough localization is disabled in a realm, you will always see that attribute in the metadata.

**Comment by DaBonse** [comment]
@pedroigor Thanks for clarification.
