### ISSUE TITLE
Failed to find ADMIN theme keycloak-extended, using built-in themes./  Loading the admin console is spinning

### ISSUE THREAD

**Issue by Krishna-PriyaV** [keycloak/keycloak#28951]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I try to login the admin console page is loading indefinitely. getting error "Failed to find ADMIN theme keycloak-extended, using built-in themes"

Using EC2 stack and docker file.

**Docker File:**

FROM public.ecr.aws/docker/library/maven:3.8.4-openjdk-17-slim as maven-builder

COPY native-s3-pom.xml ./
RUN mvn package -f native-s3-pom.xml
FROM quay.io/keycloak/keycloak:24.0.2 as keycloak-builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_DB=mysql
ENV KC_FEATURES=preview,token-exchange,admin-fine-grained-authz
ENV KC_CACHE_STACK=ec2
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_PROXY=edge
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=false

COPY APM/*.jar /opt/keycloak/providers/
COPY --from=maven-builder --chown=keycloak target/s3-native-ping-bundle-*-jar-with-dependencies.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:24.0.2
COPY --from=keycloak-builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=keycloak-builder /opt/keycloak/providers/* /opt/keycloak/providers/
COPY themes /opt/keycloak/themes/

COPY keycloak.conf /opt/keycloak/conf/

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh show-config

ENV KC_DB=mysql
ENV KC_DB_URL=<url>
ENV KC_DB_USERNAME=ursnm
ENV KC_DB_PASSWORD=pswrd
ENV KC_HOSTNAME=hostname
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_HOSTNAME_PATH=/auth

ENTRYPOINT ["/opt/keycloak/bin/kc.sh" ,"start-dev", "--http-relative-path=/auth" ]

EXPOSE 22 8080 8443 9990 9993 7800

**Error logs:**

Timestamp (UTC+05:30)
	
Message
	
Container

Timestamp (UTC+05:30)
	
Message
	
Container

April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,850 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,756 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,676 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,596 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,508 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,419 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:41,321 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:40,346 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:40,252 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:40,151 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:40,063 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,966 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,881 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,803 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,698 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,598 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,497 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:39,401 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:37,673 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:37,582 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:37,493 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:37,393 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:37,278 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:37,172 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:34,443 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:34,353 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:34,260 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:34,164 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:34,067 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:33,973 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:33,877 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:31,261 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:31,168 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:31,068 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:30,978 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:30,881 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:30,786 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:30,685 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:29,542 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:29,443 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:29,332 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:29,237 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:29,145 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:29,041 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:24,571 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-4) Failed to find ADMIN theme keycloak-extended, using built-in themes	
April 21, 2024 at 22:48 (UTC+5:30)	2024-04-21 17:18:15,301 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-4) Failed to find ADMIN theme keycloak-extended, using built-in themes	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,956 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	KeyCloak-QA
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,857 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,761 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,659 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,552 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,461 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:54,364 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:49,242 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:49,144 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:49,053 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:48,958 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:48,841 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:48,733 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:48,637 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:47,507 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:47,393 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:47,281 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:47,180 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:47,074 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:46,961 WARN [org.keycloak.events] (executor-thread-4) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:47 (UTC+5:30)	2024-04-21 17:17:43,047 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-3) Failed to find ADMIN theme keycloak-extended, using built-in themes	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:25,243 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:25,128 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:25,017 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:24,901 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:24,790 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:24,682 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:24,581 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:23,395 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:23,276 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:23,161 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:23,049 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:22,936 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:22,820 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:22,665 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:45 (UTC+5:30)	2024-04-21 17:15:18,988 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-3) Failed to find ADMIN theme keycloak-extended, using built-in themes	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,791 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,690 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,574 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,463 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,344 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,220 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:46,109 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:19,102 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:18,993 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:18,887 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:18,781 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:18,653 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:18,538 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:42 (UTC+5:30)	2024-04-21 17:12:18,275 WARN [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="master", clientId="null", userId="null", ipAddress="212.64.228.98", error="expired_code", restart_after_timeout="true"	
April 21, 2024 at 22:41 (UTC+5:30)	2024-04-21 17:11:55,851 WARN [org.keycloak.events] (executor-thread-3) type="CODE_TO_TOKEN_ERROR", realmId="master", clientId="security-admin-console", userId="null", ipAddress="212.64.228.98", error="invalid_code", grant_type="authorization_code", code_id="5f2de9b4-02b9-4795-b8b7-2bd0ee8e07dd", client_auth_method="client-secret"	
April 21, 2024 at 22:41 (UTC+5:30)	2024-04-21 17:11:54,996 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-3) Failed to find ADMIN theme keycloak-extended, using built-in themes	
April 21, 2024 at 22:41 (UTC+5:30)	2024-04-21 17:11:28,015 WARN [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.	
April 21, 2024 at 22:41 (UTC+5:30)	2024-04-21 17:11:28,009 INFO [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-mysql, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]	

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

After enter the username and password user can login to keycloak master realm.

### Actual behavior

After entering the username and password from login page it wont directing to admin console page. Admin console page is loading indefinitely.

### How to Reproduce?

Use above docker file and run keycloak 24.0.2

### Anything else?

It also didn't work with the "start" command .

**Comment by Krishna-PriyaV** [comment]
> @Krishna-PriyaV What is the URL you are using to reach the server? This sounds like an issue with the hostname configuration as I can see you setting `KC_HOSTNAME` and proxy-related configuration.

Hi @pedroigor we are using a custom URL for access our keycloak, https://keycloak-qa.com/auth/

**Comment by vmuzikar** [comment]
@Krishna-PriyaV In Keycloak 25, we're introducing a [new Hostname implementation](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc#new-hostname-options) that fixes a numerous issues like this. It's already part of our [nightly builds](https://github.com/keycloak/keycloak/releases/tag/nightly). Can you please confirm this issue is still valid with the latest nightly build?

~missing-info
