### ISSUE TITLE
Grant urn:ietf:params:oauth:grant-type:pre-authorized_code enabled even if oid4vc_vci feature is disabled

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#28968]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

- Start Keycloak with default features (not enabling any preview or experimental features)
- Login to admin console by going at URL like http://localhost:8081/auth/admin/master/console/#/master/providers
- Look at SPI `oauth2-grant-type` . The type `urn:ietf:params:oauth:grant-type:pre-authorized_code` should not be included in available providers as oid4vc feature is disabled. But it is included.

### Version

Keycloak main (from 2024-04-22)

### Regression

- [ ] The issue is a regression

### Expected behavior

Grant type `urn:ietf:params:oauth:grant-type:pre-authorized_code` available only when `OID4VC_VCI` feature is enabled

### Actual behavior

Grant type `urn:ietf:params:oauth:grant-type:pre-authorized_code` is always available

### How to Reproduce?

See steps to reproduce

**Comment by davux** [comment]
Why should pre-authorized code only be available when OID4VCI is enabled?

As an administrator, I might want to use Keycloak for authorization only, and run my own credential issuance endpoint somewhere. Keycloak wouldn't be involved in credential issuance, only in authorization.
