### ISSUE TITLE
Workflow failure: Store IT (aurora-postgres)

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#28998]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

[Store IT (aurora-postgres)](https://github.com/keycloak/keycloak/actions/runs/8792686222/job/24129486471)

Error preparing Aurora DB:

```
Prepare all required actions
Run ./.github/actions/aurora-create-database
Run source ./aurora_create.sh
{
    "AssociationId": "rtbassoc-074dbeda9d369[2](https://github.com/keycloak/keycloak/actions/runs/8792686222/job/24129486471#step:4:2)99f",
    "AssociationState": {
        "State": "associated"
    }
}
{
    "AssociationId": "rtbassoc-0282872e2bdd2dc5d",
    "AssociationState": {
        "State": "associated"
    }
}

An error occurred (DBSubnetGroupQuotaExceeded) when calling the CreateDBSubnetGroup operation: You have already reached your quota of 50 DB subnet groups per customer.
Error: Process completed with exit code [25](https://github.com/keycloak/keycloak/actions/runs/8792686222/job/24129486471#step:4:27)4.
```

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by kami619** [comment]
We are crossing the DB subnet group limit over here, we could request for an increased quota limit while we debug this @ahus1 WDYT ?

**Comment by kami619** [comment]
@ahus1 I have double checked the RDS in `us-east-1` and there weren't any dangling subnet groups left over. I think its safe to close this ticket and revisit if something happens again.
