### ISSUE TITLE
No event for IMPERSONATE in log

### ISSUE THREAD

**Issue by chary1112004** [keycloak/keycloak#28997]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Hi support team,

We have upgraded keycloak to 24.0.3 and we have tested if events appear in log. Once of the case that is event type = IMPERSONATE. We saw event is saved and viewed in admin console however we do not see in the log
![image](https://github.com/keycloak/keycloak/assets/76929085/1a011c97-5ae2-4846-96f6-403588fd3978)

$ kubectl logs keycloak-sandbox-0 -n keycloak-sandbox | grep IMPERSONATE
> return empty

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Event IMPERSONATE is in log

### Actual behavior

Event IMPERSONATE is not in log

### How to Reproduce?

- Deploy keycloak 24.0.3
- Test impersonate

**Comment by sschu** [comment]
AFAIK only error events are normally logged to the console. If you also want success events to be logged, you could for example add spi-events-listener-jboss-logging-success-level=INFO to your keycloak.conf.

**Comment by chary1112004** [comment]
Hi @sschu,

Thank you for the feedback. After enable spi-events-listener-jboss-logging-success-level=INFO then I could see the IMPERSONATE log.
