### ISSUE TITLE
Creating client-scope without protocol causes GUI bug

### ISSUE THREAD

**Issue by traverse1984** [keycloak/keycloak#29027]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

It is possible to create a client-scope via the API which does not have a protocol field. When trying to view this client scope in the admin GUI, the error 'n is not iterable' is shown and the user must refresh the GUI. The API documentation states the field is optional: https://www.keycloak.org/docs-api/21.0.1/rest-api/index.html#_clientscoperepresentation.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

The GUI should show the client scope, or the API should not allow a client scope to be created in an invalid state.

### Actual behavior

The API allows a scope to be created without a protocol field.

### How to Reproduce?

Use the keycloak API to create a client scope without specifying a protocol.

**Comment by prattak86** [comment]
@raff897 @keycloak-bot I have noticed an issue with keycloak and getting this error, but I'm defining the Protocol. It seems I'm probably defining the Protocol incorrectly, but it is creating the client scope anyways and not allowing any later operations on that client to be valid.

**Comment by raff897** [comment]
Sorry @prattak86  i didn't understand. It still create client scope without protocol?
