### ISSUE TITLE
Users groups tab subgroup pagination not working

### ISSUE THREAD

**Issue by raunokulla** [keycloak/keycloak#29034]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Admin UI is not requesting second page of subgroups on users groups tab correctly.

As in my example I have 12 subgroups under root group "institutions".

I am not able to add 12th subgroup to my user as visible from screenrecord:
[screen-capture (1).webm](https://github.com/keycloak/keycloak/assets/11193108/8f98d677-3807-41a5-81e6-935ae32d7b4b)

realm json:
[realm-export.json](https://github.com/keycloak/keycloak/files/15082494/realm-export.8.json)

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

As by default pagination size is 10 items on the second page I should see items of 11-12 out of 12. 

### Actual behavior

Second page of subgroups is requested and rendered incorrectly. Pagination breaks.

### How to Reproduce?

Create new realm by using provided realm json file.

Create new user and try to add "subgroup L" group to your new user using pagination.

**Comment by ssilvert** [comment]
I tried this on the latest nightly build and it worked just fine.  I got an error when I tried to import your realm, but I did create a group with 14 subgroups.  When I tried to add the 14th group to the user, pagination worked and adding it worked.

**Comment by ssilvert** [comment]
Please give the nightly build a try and let me know if it works.
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by raunokulla** [comment]
@ssilvert Thanks, indeed this is working correc
