### ISSUE TITLE
Argon2 password hashing leads to increased Major GC's in Keycloak's JVM during load tests

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#29033]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Argon2 password hashing leads to increased Major GC's in Keycloak's JVM during load tests.

With Argon2 occupying larger amounts of heap memory and with the existing GC(ParallelGC) results in continuous Major GC's leading for higher CPU contention and lower performance across the board.

We looked into the tuning options and did several series of tests. And the findings are below.
But we understand there is an intervention needed due to this password hashing algorithm change and there are couple of recommendations suggested in this ticket based on our tests.

### Version

nightly

### Regression

- [X] The issue is a regression

### Expected behavior

We would want the Keycloak's JVM heap to behave consistently in terms of both throughput and endpoint performance.

### Actual behavior

With the Argon2 hashing change, we find the application to behave abnormally during medium to high load situations with increased JVM GC overhead and CPU utilization.

With the Keycloak current JVM defaults:

High Major GC counts during a load test run and higher JVM GC Overhead.

![screencapture-grafana-apps-rosa-gh-keycloak-a-0u56-p3-openshiftapps-d-basic-keycloak-dashboard-by-namespace-keycloak-perf-tests-2024-04-11-10_18_32](https://github.com/keycloak/keycloak/assets/3415105/6db70e6b-d780-430d-b5bf-665dcbeee0b2)

### How to Reproduce?

Using the keycloak-benchmark and the default Keycloak JVM heap settings, run the below command

```
./kcb.sh --scenario=keycloak.scenario.authentication.AuthorizationCode \
--server-url=<keycloak-url> --users-per-sec=150 --ramp-up=20 \
--logout-percentage=100 --measurement=900 --users-per-realm=20000
```

### Anything else?

We then disabled the `UseAdaptiveSizePolicy` and that stabilized the load test runs. Further more we observed the Adaptive policy is aggressively looking to clear the heap resulting in frequent heap resizing events, but with disabling the adaptive policy, we were able to control that better. But disabling a key attribute is not a longer term solution, now we started to look into the G1GC which suits better to our use case and ran few experiments. Below is the result from those experiments.

<img width="1390" alt="Screenshot 2024-04-23 at 16 04 19" src="https://github.com/keycloak/keycloak/assets/3415105/22e4a5e0-e989-4102-8bec-3063dd006644">

Based on this data, it seems like, G1GC even with current Keycloak JVM defaults works better than ParallelGC and it offers some more tuning bandwidth by adjusting GCTimeRatio and AdaptiveSizePolicyWeight. We would like to hear how the Cloud Native team interprets this data and take appropriate next steps.

**Comment by sschu** [comment]
@kami619 As a side note: we have been using G1C in production since we started using Keycloak without problems.

**Comment by ahus1** [comment]
Re-opened as we need release notes and an updated sizing guide (the sizing guide doesn't reflect Argon2 yet)

**Comment by kami619** [comment]
@ahus1 looks like we dont have a `documentation/upgrading/topics/keycloak/changes-25_0_0.adoc` yet, shall I start an empty one with the performance changes with Argon2 hashing ?
