### ISSUE TITLE
not able to disable declarative_ui feature

### ISSUE THREAD

**Issue by avaraljai** [keycloak/keycloak#29057]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The DECLARATIVE_UI feature extendable admin console could not be turned off.

Referring to this recently added feature:
https://github.com/keycloak/keycloak/pull/23772

I was trying out the introduced feature based on this quickstart:
https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/extend-admin-console-spi

once i have the extend-admin-ui,jar in the providers folder the attempt to disable the extension seems failing.
see the attached screenshots one with enabled one with disabled. ("todo" item is visible on the left regardless of the setting)

Maybe i got  it wrong but i thought that it is possible to switch off this experimental feature.

![2024-04-24_16-10_declarative_ui_enabled](https://github.com/keycloak/keycloak/assets/37251964/1428962f-22bd-46fd-be6e-d06b2e5423b4)
![2024-04-24_16-11_declarative_ui_disabled](https://github.com/keycloak/keycloak/assets/37251964/815f67fd-1efb-4233-9d75-4c1cd189f59d)

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

when i set declarative_ui disabled the UI elements should not be visible

### Actual behavior

when i set declarative_ui disabled the UI elements are visible

### How to Reproduce?

deploy the above mentioned quickstart ( https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/extend-admin-console-spi )

to disable i added the "declarative_ui" to this envvar  KC_FEATURES_DISABLED

then kc.sh build

**Comment by stianst** [comment]
@jonkoops this seems to be a admin ui issue to me, and not a core issue?

**Comment by avaraljai** [comment]
Well i'm not aware of the boundaries of the project, what i could figure maybe the way of applying the feature flag is not ok:
https://github.com/keycloak/keycloak/pull/23772/files#diff-b85fcd54076f5d287313bfb7494f1f0176a61044fbf7fcd6e42480ddaf3063a2R30

https://github.com/keycloak/keycloak/pull/23772/files#diff-04fee0492694816f36c68a468a9ec735283d006b5e6f19502ea8109c4723d646R30

both relying on SPI.isEnabled()

I found 1 occurence of checking spi.isEnabled() in org.keycloak.services.DefaultKeycloakSessionFactory#init
https://github.com/keycloak/keycloak/blob/a3f2ebb1935c544cab0bd101fbba92913c63d7ee/services/src/main/java/org/keycloak/services/DefaultKeycloakSessionFactory.java#L100

and org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory#init 

https://github.com/keycloak/keycloak/blob/168734b817da2138548bacba973204e80f566b2c/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/QuarkusKeycloakSessionFactory.java#L96
overrides this so i believe spi.isEnabled() not being checked when QuarkusKeycloakSessionFactory is being used

But i haven't checked this with debugger.
So maybe SPI.isEnabled() is not the right way to apply the feature gate on this functionality, or the QuarkusKeycloakSessionFactory does not check this SPI.isEnabled()

Or maybe something else - please feel free to validate my assumptions.

**Comment by jonkoops** [comment]
> this seems to be a admin ui issue to me, and not a core issue?

We just get this data from the API, so I think not. Unless it's not possible to disable ANY feature.

**Comment by jonkoops** [comment]
Hmmm, yeah looks like a missing condition somewhere. @edewit could you take a look at this?
