### ISSUE TITLE
UI strings missing in revocation dialogue

### ISSUE THREAD

**Issue by msavy** [keycloak/keycloak#29065]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Sessions -> Action -> Revocation

<img width="661" alt="image" src="https://github.com/keycloak/keycloak/assets/423513/8871866c-0785-401a-acf1-f04a736c379e">

### Version

latest (24.0.3 I think)

### Regression

- [X] The issue is a regression

### Expected behavior

Should have real translated stringss rather than template placeholders

### Actual behavior

<img width="661" alt="image" src="https://github.com/keycloak/keycloak/assets/423513/52d7e6e4-58b9-4ba4-9173-7645df330927">

Has template strings but not real translations

### How to Reproduce?

In the admin UI, visit Sessions -> Action -> Revocation

**Comment by jonkoops** [comment]
Could you confirm this is still an issue in the [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly)? I believe this might have already been fixed there.

**Comment by msavy** [comment]
Thanks @jonkoops – I was using the `latest` docker tag. After trying `nightly`, everything seems fine.

**Comment by jonkoops** [comment]
Awesome, thanks for checking!
