### ISSUE TITLE
Keycloak need to display "Password expired, set new password" kind of message on update_password page, when users password expired. 

### ISSUE THREAD

**Issue by Jayashree-Rajendran** [keycloak/keycloak#29077]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Keycloak need to display "Password expired, set new password" message on update_password page, when users password expired. Because keycloak need to notify the user to reason for password change 

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak need to display "Password expired, set new password" message on update_password page, when users password expired. Because keycloak need to notify the user to reason for password change 

### Actual behavior

![image](https://github.com/keycloak/keycloak/assets/161576805/8fc9aab1-9e5f-470d-b2d5-9b445f4fbbe7)

### How to Reproduce?

As mentioned in description

**Comment by rohangupta231** [comment]
https://github.com/keycloak/keycloak/pull/29119

**Comment by rohangupta231** [comment]
Hi, I have created pull request for the same. #29119

**Comment by mposolda** [comment]
This is valid issue, but Keycloak team likely won't have time to look at this anytime soon. I can just add that there are multiple possible scenarios:

- Case when administrator creates new user in the admin console. Then admin user sets the password of this user with marked flag `Temporary password` (it is ON by default when admin updates password of some user). In this case, it makes perfect sense that during login of this user, there is still the current message displayed `You need to change your password to activate your account`

- Case when there is password policy like "expired password" and password was expired by that policy (not manually by admin by adding `Update password` required action) . In that case, it will makes sense to display slightly different message like `Password expired. Please set new password` .

If it is not possible to reliably differentiate between those cases, we can hopefully use some "universal" message, which will makes better sense for both cases above. Maybe something like `You need to update password to continue login` , which is likely quite universal and IMO it makes sense for both cases when action was manually added by admin or password was expired.

**Comment by Jayashree-Rajendran** [comment]
Any update on this issue?
