### ISSUE TITLE
Prevent to change organization related user attributes for federated users

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#29080]
When a user federated from LDAP or a custom user federation become an organization member, we need a way to detect or prevent to change user attribute(s) related to the organization outside the Keycloak.

**Comment by pedroigor** [comment]
AFAIK, for LDAP that would require creating a mapper for those attributes related to the organization. And if the user is being managed through the user profile provider we are already running validations. Are you considering introducing constraints on which attributes can be mapped from an LDAP mapper?

**Comment by pedroigor** [comment]
@martin-kanis Btw, perhaps related to what you are proposing around LDAP:

* https://github.com/keycloak/keycloak/issues/25726
* https://github.com/keycloak/keycloak/pull/26415

**Comment by pedroigor** [comment]
No longer needed because the `kc.org` user attribute does not exist anymore.
