### ISSUE TITLE
Fix the client name help grammatical error

### ISSUE THREAD

**Issue by biya-bi** [keycloak/keycloak#29094]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hi,
This minor bug is to fix a small grammatical error noticed while creating a client from the admin UI. As can be noticed in the attached screenshot, the word "t**he**" has been omitted before the words "**display name**". I think it might be better if the client name message is:

_Specifies **the** display name of the client. For example 'My Client'. Supports keys for localized values as well. For example\: ${my_client}_

<img width="900" alt="client_name_tooltip_grammatical_error" src="https://github.com/keycloak/keycloak/assets/15185914/6e9d9fc8-ee56-4775-99e5-5f27560365c2">

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The client name help displayed while creating a client should display the below message:

_Specifies **the** display name of the client. For example 'My Client'. Supports keys for localized values as well. For example\: ${my_client}_

### Actual behavior

Currently, the client name help displayed while creating a client displays the below message. We can notice that the word "the" is missing between the word "**Specifies**" and the word "**display**":

_Specifies display name of the client. For example 'My Client'. Supports keys for localized values as well. For example\: ${my_client}_

<img width="900" alt="client_name_tooltip_grammatical_error" src="https://github.com/keycloak/keycloak/assets/15185914/05fc511b-0abf-4c31-9aa1-44fea058fa83">

### How to Reproduce?

On the admin UI, try to create a client. Once on the General settings page, click on the question mark beside the Name label.

**Comment by biya-bi** [comment]
I will submit a pull request for this issue.

**Comment by edewit** [comment]
pr merged closing
