### ISSUE TITLE
Index Exists Precondition: IDX_CLIENT_ATT_BY_NAME_VALUE on CLIENT_ATTRIBUTES : Found multiple catalogs matching XXXXX (PostgreSQL)

### ISSUE THREAD

**Issue by chtyce** [keycloak/keycloak#29123]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I use 23.0.7 version and i want to upgrade to 24.0.2 version. But I get an error when i try to upgrade.

Error message: Index Exists Precondition: IDX_CLIENT_ATT_BY_NAME_VALUE on CLIENT_ATTRIBUTES : Found multiple catalogs matching XXXXX

### Version

23.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

Upgrade version to 24.0.02

### Actual behavior

I get this error.

Error message: Index Exists Precondition: IDX_CLIENT_ATT_BY_NAME_VALUE on CLIENT_ATTRIBUTES : Found multiple catalogs matching XXXXX

### How to Reproduce?

- Create a project that using Keycloak 23.0.7 version and PostgreSQL
- Try to upgrade 24.0.2 version

**Comment by rmartinc** [comment]
@chtyce We test migrations in supported databases from version 19 to current version in any PR. So your reproducer steps are not enough. You have something specific in your env that triggers this error. Looking a bit the error, maybe you have several schemas in postgres with different cases that are producing the error. Check what you have in the DB doing something like:

```sql
select * FROM information_schema.schemata;
```

And check if you have the same catalog with different case or similar.

**Comment by rmartinc** [comment]
Closing this by inactivity. Please re-open or file a new issue if needed.
