### ISSUE TITLE
After I download the source code (24.0.3), local packaging and compilation will report an error

### ISSUE THREAD

**Issue by honestAnt** [keycloak/keycloak#29172]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Currently, through the packaged error log information, you can locate the problem (verifyHost() of TrustedHostClientRegistrationPolicyTest.testGithubDomain). You can solve the problem by commenting it out. I don’t know if it is caused by my region (China)
// policy.verifyHost(InetAddress.getByName("www.github.com").getHostAddress());
// policy.verifyHost(InetAddress.getByName("github.com").getHostAddress());

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

In the source code directory, execute the packaging command (mvn clean install -Pdistribution) to output the corresponding packaging file.

### Actual behavior

![image](https://github.com/keycloak/keycloak/assets/15356873/3b854f36-283d-485a-bed9-507e2e9296bb)

### How to Reproduce?

Download the latest source code, enter the keycloak directory, and execute the packaging command (mvn clean install -Pdistribution) to reproduce (I don’t know if it has something to do with the region)?

### Anything else?

Currently, by annotating the single test code (TrustedHostClientRegistrationPolicyTest.testGithubDomain), you can package it

**Comment by jonkoops** [comment]
Yeah, it's likely because the Chinese government blocks GitHub as far as I am aware.

**Comment by honestAnt** [comment]
thanks

**Comment by jonkoops** [comment]
Closing this issue, as we're really not able to do anything about what a nation state decides their people can or cannot access.
