### ISSUE TITLE
I want the solution for retrieving the user permission using a custom SPI, everytime u close this task and don’t provide the solution i want the solution I am using role based policy permission . I will keep raising it untill I get the solution 

### ISSUE THREAD

**Issue by taru-j-a-i-n** [keycloak/keycloak#29197]
### Description

I want to see the User permission in the user profile of the user but there is no direct method to do so please provide the direct method or the solution to get User permissions . Inwant to get ROLE BASED POLICY PERMISSION
the output must have the Permissions as not null and not empty currently it is coming as an empty list as shown below: {"id":"094073fb-0f5e-419f-a582-d25b8b5b5903","email":"[admin@admin.com](mailto:admin@admin.com)","firstName":"Admin","lastName":"listener","userRoles":["default-roles-portal-realm","create-client","uma_protection","read-token","view-profile","view-groups","view-consent","view-applications","manage-consent","manage-account-links","delete-account"],"userPermissions":[],"claims":null}

**I tried this method but it is not giving the solution: **

public List getPermissions(UserModel user) {

String realmName = System.getenv("realm_name");
RealmModel realm = this.model.getRealmByName(realmName);

ClientModel client = realm.getClientByClientId("demo-client");
log.info("client: " + client);

log.info("getPermissions is triggered...........................");
List<UserPermission> userPermissions = new ArrayList<>();
StoreFactory storeFactory = session.getProvider(StoreFactory.class);
log.info("storeFactory: " + storeFactory);

AuthorizationProvider authorizationProvider = session.getProvider(AuthorizationProvider.class);
 log.info("authorizationProvider: " + authorizationProvider);
 
PermissionTicketStore permissionTicketStore = storeFactory.getPermissionTicketStore();
log.info("permissionTicketStore: " + permissionTicketStore);
ResourceServerStore resourceServerStore = storeFactory.getResourceServerStore();
log.info("resourceServerStore: " + resourceServerStore);
ResourceServer resourceServer = resourceServerStore.findByClient(client);

log.info("resourceServer: " + resourceServer);
if (resourceServer != null) {
    log.info("resourceServer is not null...........................");
    List<PermissionTicket> permissionTickets = permissionTicketStore.findGranted(resourceServer, user.getId());
    log.info("user.getId(): " + user.getId());
    log.info("permissionTickets: " + permissionTickets);
    for (PermissionTicket permissionTicket : permissionTickets) {
        log.info("permissionTicket: loop:  " + permissionTicket);
        UserPermission userPermission = new UserPermission();
        userPermission.setResourceId(permissionTicket.getResource().getId());
        log.info("permissionTicket.getResource().getId(): " + permissionTicket.getResource().getId());
        userPermission.setResourceName(permissionTicket.getResource().getName());
        log.info("permissionTicket.getResource().getName(): " + permissionTicket.getResource().getName());
        userPermission.setActions(getScopeNames(permissionTicket.getResource()));
        log.info("getScopeNames(permissionTicket.getResource()): " + getScopeNames(permissionTicket.getResource()));
        userPermissions.add(userPermission);
    }
}

return userPermissions;
}

**Comment by taru-j-a-i-n** [comment]
please reply ASAP

**Comment by akbar1214** [comment]
This is not the way to ask for help. Wait for reply in discussion created by jonkoops or try asking in [discourse](https://keycloak.discourse.group/).

**Comment by sschu** [comment]
What @akbar1214 said. I will go ahead and close this issue.
