### ISSUE TITLE
Network error attempting to view default realm roles without permissions

### ISSUE THREAD

**Issue by Jamstah** [keycloak/keycloak#29211]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If a user has view-realm permission they can see the realm roles. If they go to realm roles and select the default-roles entry, they get a network error instead of a permissions error. After the error, the console is completely unresponsive and the window must be refreshed.

`Network response was not OK.`

![image](https://github.com/keycloak/keycloak/assets/298807/a4b5241d-4792-4c2e-b830-2cef93ad1975)

### Version

quay.io/keycloak/keycloak:latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Permissions error should be shown

### Actual behavior

Network error shown and admin console unresponsive.

### How to Reproduce?

1. Create a realm
2. Create a user in the realm with `view-realm` permissions
3. Log in as that user
4. Go to Realm Roles
5. Attempt to view the default-roles-<realm> item

### Anything else?

Same thing happens going to *Realm Settings* -> *User registration* with the same permissions.

**Comment by Jamstah** [comment]
This also happens in *Realm Settings* -> *Events* if the user doesn't have event permissions.

LMK If that needs to be a separate bug.

**Comment by himanshi1099** [comment]
@ssilvert Can I raise PR for this issue?

**Comment by jonkoops** [comment]
Feel free to submit a PR if you feel you have a valid solution @himanshi1099

**Comment by ssilvert** [comment]
@himanshi1099 Are you still planning to submit a PR for this?

**Comment by himanshi1099** [comment]
@ssilvert Yes I'm working on this I reproduced the issue and it's reproducable checking for possible solution for fixing the bug.
