### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak#29233]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Documentation tests fail right due to a broken link. Error is:
org.opentest4j.AssertionFailedError: 
Broken links (1) in guide 'server_development': 
		- https://www.liquibase.com/community (invalid redirect to /community/contributors)

### Version

HEAD

### Regression

- [ ] The issue is a regression

### Expected behavior

No test failures

### Actual behavior

ExternalLinksTest fails

### How to Reproduce?

mvn install -Dtest=ExternalLinksTest -am -pl docs/documentation/tests -e -Pdocumentation

**Comment by ahus1** [comment]
Thank you for this fix. Please also backport it to KC22+KC24 when you have the time as those documentation builds also fail. Thanks!
