### ISSUE TITLE
The select for a locale behaves as a multi-select in the admin and account UI when it should be single value

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#29237]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The locale field for a user behaves like a multi-input field while it should be a single-input field only.

This applies to the admin UI and the account console when the managed attributes are enabled. 

This is a regression at it worked with a simple select in the old account console.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

A user should have only one locale set for the local attribute.

### Actual behavior

When using the admin UI or the account UI, when choosing another locale, it is added to the existing locale, so that the user has two locales set. 

### How to Reproduce?

* Start Keycloak in dev mode with a fresh realm
* Enable localization for the realm in the admin UI
* Choose 2-3 languages for localization in the UI
* Select a user in the admin UI
* Select a first locale (English) and save the user and reload the page
* Select a second locale that is listed below the first locale -> the UI will still show the first locale
* Refresh the browser -> the Keycloak log  will show the warning message "KC-SERVICES0046: Multiple values found '[en, ca, nl, da, zh-CN, ar, ca, zh-TW]' for protocol mapper 'locale' but expected just single value" showing that multiple locales have been saved to the user

**Comment by ssilvert** [comment]
I could not reproduce the warning message, but I definitely see how you can't choose a locale that is below the one that is already saved.

**Comment by ahus1** [comment]
I've testing tonight's nightly release, and was still able to reproduce the problem - probably even worse than before, as I can now enter the same locale twice for a user, which is breaking things. 

To reproduce: 

* Fresh installation
* Enable Localization on master realm and add Spanish and German as other languages
* Go to the users tab
* Select the admin user - the locale is empty
* Select "English" and "Save" -> the form appears to have an empty locale. Looking at the JSON returned, the attribute "locale" contains an array with one entry ("en"). 
* Use the drop-down for Locale, and choose "German", then close the dropdown. As the field appears to be empty, do it another time. Hit safe

Looking at the submitted values, and also the retrieved values afterwards, the locale field now contains "en", "de", "de", where it should contain only a single value. It seems that the user can't remove a locale. 


```
{
    "id": "3835905b-4d70-43a5-adfb-f1ece3ef60ab",
    "username": "admin",
    "emailVerified": false,
    "attributes": {
        "locale": [
            "en",
            "de",
            "de"
        ]
    },
    "userProfileMetadata": {
        "attributes": [
            {
                "name": "locale",
                "displayName": "locale",
                "required": false,
                "readOnly": false,
                "validators": {},
                "multivalued": false
            },
...
```

**Comment by ahus1** [comment]
There might already be a duplicate of this opened yesterday: #30218

**Comment by ahus1** [comment]
I tested that PR #30209 connected to it, and it will fix it. So closing this one again.
