### ISSUE TITLE
Backport 3p cookies fix

### ISSUE THREAD

**Issue by ajit2548** [keycloak/keycloak#29255]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-js

### Describe the bug

We need the fix https://github.com/keycloak/keycloak/pull/25055 into keycloak 21.1 version.
Would you be able to do it?

### Version

21.1.2

### Regression

- [ ] The issue is a regression

### Expected behavior

related to 3p cookies in firefox iframe

### Actual behavior

fix need to be backported

### How to Reproduce?

need the backport of fix.

**Comment by ahus1** [comment]
The Keycloak project only provides community releases for the 24.x branch of Keycloak. You'll either need to upgrade to a more recent community release,  build your own version of Keycloak with that backport, or change to commercially supported distribution of Keycloak.
