### ISSUE TITLE
User gets timeout error right after login

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#29254]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

We have around 300 users authenticating with Keycloak.
However, we got reports from three users, two with iPhones and another with an Android, that right after they enter their credentials on a freshly loaded page, they get redirected to the login page with a timeout error saying that they took too long to authenticate.

The thing is that the page is freshly load. This is very difficult to reproduce since we do not always have the user with us. The one time we tried to investigate, there was nothing on the logs.

Sometimes, if there are extra authentication steps, such as 2FA, while the user is still inputing the OTP, he got suddenly redirected to the login page, even without having finished login. 

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should be logged in and/or go to the further authentication steps.

### Actual behavior

1- User enters his credentials on a newly refreshed window
2 - user clicks Log in
3 - user gets immediately sent back to the login window.

The step 3 happens sometimes on the middle of another authentication step, such as 2FA

### How to Reproduce?

We don't manage to reproduce it all the time. But when asked, this user does the above steps and this happens a lot for him.

**Comment by oculos** [comment]
We have seen some errors in our logs, and it seems that some authenticators have problems when calling `context.getUser()`. It is returning `null`.

What is weird is that some of those authenticators call `context.getUser()` twice, and it fails only on the second call. 

We are unsure if this is the main cause of the described bug, or if this is just a symptom.

**Comment by graziang** [comment]
Hi @oculos , with realm default settings user has 30 minutes to complete login, you can check your settings in Realm Setting -> Login Timeout.

From your log i see you are using a custom authenticator `no.uio.keycloak.authenticator.radiusnps.RadiusNPSAuthenticator`, Could the error be related to some custom logic?

**Comment by oculos** [comment]
Thanks a lot Giuseppe.

The thing is that this happens on a freshly loaded webpage. The user tries to login several times and get the same error.

Yes, it could absolutely be related to the authenticator. We are still investigating. But since the problem occurs when the authenticator is still waiting for an input, I assume it isn’t related to it. 

The error the authenticator is presenting is weird. You  see, the authenticator gets the username from `context.getUser().getUsername()`.

It is called once, and there is no error here. Then, the `context` is passed as a parameter to another function, and there the same `getUser()` returns `null`. This happens to a really low number of users, which leads me to believe there is something weird going on. As I said, the function returns a value on a first call, but null on a second call.

Best,

Francis

**Comment by mposolda** [comment]
This might be related to custom authenticator and hence Keycloak team won't prioritize this ATM. Please see if you are able to reproduce similar issue with "out of the box" Keycloak without custom authenticators and/or you can try to isolate the issue and send PR if you find that this is actually bug in Keycloak rather than in your authenticator.
