### ISSUE TITLE
Documentation Enhancements Admin Rest API Group to Client Role Mappings

### ISSUE THREAD

**Issue by sprehn-ero** [keycloak/keycloak#29266]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Documentation on admin rest api
https://www.keycloak.org/docs-api/latest/rest-api/index.html states in section

POST /admin/realms/{realm}/groups/{group-id}/role-mappings/clients/{client}
that body parameter should be of type RoleRepresentation, when it really should be **List of** [RoleRepresentation]

Please also review the description of endpoints group/{group-id}/role-mapping/{client}
The mention that this maps the role to a **user**, when it really is a mapping for a **group**.

I also suggest to rename the palceholder {client} to {**client-id**} and add in the description, which id is expected (the id and not clientId.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

see bug description

### Actual behavior

see bug description

### How to Reproduce?

see bug description

**Comment by sguilhen** [comment]
Verified, documentation needs to be updated in these cases. Contributions are welcome!

**Comment by sprehn-ero** [comment]
Suggested Fix PR #29344

**Comment by sguilhen** [comment]
Thanks, @sprehn-ero !
