### ISSUE TITLE
TrustedHostClientRegistrationPolicyTest#testGithubDomain failing in clean checkout

### ISSUE THREAD

**Issue by Jamstah** [keycloak/keycloak#29271]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

https://github.com/keycloak/keycloak/blob/main/services/src/test/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicyTest.java#L110

This test seems to get the IP of www.github.com, convert it to a string, then attempt to verify that the IP address matches `*.github.com`.

For me, the test fails. This seems to be because reverse DNS lookup of github.com fails.

I think the test is broken (and probably shouldn't rely on external infrastructure anyway)

```
jammy@ibm007470:~$ dig www.github.com

; <<>> DiG 9.18.26 <<>> www.github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30996
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.github.com.			IN	A

;; ANSWER SECTION:
www.github.com.		341	IN	CNAME	github.com.
github.com.		18	IN	A	20.26.156.215

;; AUTHORITY SECTION:
github.com.		341	IN	SOA	ns-1707.awsdns-21.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Fri May 03 15:44:06 BST 2024
;; MSG SIZE  rcvd: 157

jammy@ibm007470:~$ nslookup 20.26.156.215
** server can't find 215.156.26.20.in-addr.arpa: NXDOMAIN
```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests pass on clean checkout

### Actual behavior

Test fails on clean checkout

### How to Reproduce?

Run `./mvnw clean install` on a clean checkout. May get different results in different geos depending on how the github domain is configured.

### Anything else?

I'd be happy to make a PR, but I don't know the importance of the test and what its doing, so would need some direction on how it should be changed.

**Comment by dteleguin** [comment]
Same here. The test is failing, as reverse lookup fails for the GitHub IP (tried with several DNS servers).

**Comment by dbfr3qs** [comment]
It looks like the test relies on the GitHub.com DNS registration supporting reverse DNS lookup, which it does not appear to do and is not a DNS requirement. I'm not fully sure why the test exists - is it to test whether registration works with GitHub, or is it to test the behaviour of the `TrustedHostRegistrationPolicy`?

If the latter I would recommend removing the test entirely. The [testGoogleCrawlBot](https://github.com/keycloak/keycloak/blob/4c2542b91f85a98dcbaeb392934e15620b19b3f0/services/src/test/java/org/keycloak/services/clientregistration/policy/impl/TrustedHostClientRegistrationPolicyTest.java#L91) test appears to cover more or less the same thing.

If the former, does this mean there is something broken that needs to be fixed?

**Comment by sguilhen** [comment]
@rmartinc Could you take a look into this one? It is a test that you've added recently, I think you would be able to handle this much faster than us.

**Comment by rmartinc** [comment]
The test is working for me and in the GHA. I remember that I shose github because I wanted someone that also added the reverse lookup.

```
dig www.github.com +noall +answer
www.github.com.		1102	IN	CNAME	github.com.
github.com.		38	IN	A	140.82.113.3
dig -x 140.82.113.3 +noall +answer
3.113.82.140.in-addr.arpa. 3021	IN	PTR	lb-140-82-113-3-iad.github.com.
```

But yes, these tests are weird because they depend in external DNS infrastructure, but we cannot test this in any other way. IIRC I added this one to have two different names (github.com and www.github.com), but, as someone commented before, this is more or less tested with the googlebot test before just with one hostname/IP. If it's causing issues we can just remove this one.

**Comment by dbfr3qs** [comment]
Yes, I wonder if it's something to do with your geography (as mentioned in the issue) or the DNS server that you are using caching the record. I get a totally different IP address in the initial lookup consistently:

```
dig www.github.com

; <<>> DiG 9.10.6 <<>> www.github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14505
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.github.com.			IN	A

;; ANSWER SECTION:
www.github.com.		1932	IN	CNAME	github.com.
github.com.		52	IN	A	20.248.137.48

;; Query time: 50 msec
;; SERVER: fe80::e246:eeff:fe29:669d%15#53(fe80::e246:eeff:fe29:669d%15)
;; WHEN: Tue Jul 23 14:55:02 NZST 2024
;; MSG SIZE  rcvd: 73

dig @8.8.8.8 -x 20.248.137.48

; <<>> DiG 9.10.6 <<>> @8.8.8.8 -x 20.248.137.48
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 10117
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;48.137.248.20.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
137.248.20.in-addr.arpa. 105	IN	SOA	ns1-01.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300

;; Query time: 48 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jul 23 14:57:
```

What happens if you try running the initial look up using Google DNS? e.g.

`dig @8.8.8.8 www.github.com`

**Comment by rmartinc** [comment]
Yes, using google I get the same resolutions:

```bash
dig @8.8.8.8 www.github.com +noall +answer
www.github.com.		3556	IN	CNAME	github.com.
github.com.		60	IN	A	140.82.121.4
dig @8.8.8.8 -x 140.82.121.4 +noall +answer
4.121.82.140.in-addr.arpa. 839	IN	PTR	lb-140-82-121-4-fra.github.com.
```

For me the difference is that IP you are receiving in direct resolution is different. I don't know if because region or something else. But don't worry, if this is causing issues I'm going to just remove the test. The IP using the google bot at least is documented that it should work.
