### ISSUE TITLE
Group members remain in group members list after removal

### ISSUE THREAD

**Issue by cod3monk** [keycloak/keycloak#29282]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In the admin console, after removing members from a group, they incorrectly remain listed in the members list of the group (Groups -> Group Details -> Members). However, it is correctly reflected everywhere else: the membership column in the list, the information passed to clients and the synced LDAP all do not list the user as a member anymore.

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

After removing a user from a group, I expect them to not show up in the list of members of that group anymore.

### Actual behavior

Old members remain in the list.

### How to Reproduce?

Not clear, because this issue is only observed with members that were added a couple years back using an older Keycloak version (exact timeframe and versions are unknown).

With newly added members the behaviour is not observed and the admin console behaves as expected.

### Anything else?

We use LDAP federation (not sure if this makes a difference).

**Comment by ssilvert** [comment]
This doesn't sound like a UI issue.  Moving to core team.

**Comment by martin-kanis** [comment]
@cod3monk I'm afraid there's not much we can do here without a reproducer.

**Comment by Stijn-K** [comment]
Can this issue be re-opened? We are seeing this in v24.04, including an issue that some groups show the same member twice. Not just in the UI, but also through the API.
We can consistently see this behaviour with several groups and users. We can supply logging if needed. What would you need?

**Comment by Stijn-K** [comment]
Further research suggests this issue is specifically related to the entries in the keycloak database table "user_group_membership". All entries in this table seem to have an issue with which groups they should or should not be a member of.

**Comment by Stijn-K** [comment]
For further reference, deleting the contents of the table "user_group_membership" seems to have solved the problem. We however dont know why, or what caused this in the first place.
This table only contained 11 rows, we have hundreds of users and groups.

**Comment by cod3monk** [comment]
@Stijn-K This seems to be the same for us. In my case the table has 372 entries. When I delte an entrie for an actual member it has no apparent consequence (user stays member of group, through LDAP federation I suppose). When deleteing a spurious member they disappear from the admin interface member list.

@ssilvert has emtying the table any other consequences?

**Comment by cod3monk** [comment]
we are now on v26.7.4 and the problem persists

**Comment by ssilvert** [comment]
@cod3monk Do you have a reliable way to reproduce the problem?

**Comment by cod3monk** [comment]
I investigated further and found the following:

we are using LDAP federation and group sync with `LDAP_ONLY`, yet for some reason the `USER_GROUP_MEMBERSHIP` table has stale entries. Some of those entries are for memberships which have been revoked in the meantime. We have used LDAP sync since the beginning of the realm, thus I am not sure how we got those in the first place.

When looking at the group memberships of a user (User details) these entries do not show up, also they are also ignored in generated tokens.

However, when listing members of a group in the group details, these stale db entries are listed as members of the group.

My fix for now was to delete all records in the `USER_GROUP_MEMBERSHIP` related to the realm with `LDAP_ONLY` group sync enabled.

Using mariadb:
```sql
DELETE ugm
FROM `USER_GROUP_MEMBERSHIP` AS ugm
JOIN `KEYCLOAK_GROUP` AS kg
  ON kg.`ID` = ugm.`GROUP_ID`
JOIN `REALM` AS r
  ON r.`ID` = kg.`REALM_ID`
WHERE r.`NAME` = 'REALM_ID_WITH_LDAP_ONLY_ENABLED';
```
