### ISSUE TITLE
Wrong evaluation after editing/deleting resource

### ISSUE THREAD

**Issue by m1212e** [keycloak/keycloak#29285]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

After deleting, editing or creating certain resources, keycloak returns a deny evaluation result. When running the exact same evaluation a second time, no changes made, it returns the correct permit result.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The eval should run permit every time.

### Actual behavior

It denies first time, then permits every time after that.

### How to Reproduce?

Not sure, but I attatched then network calls in the discussion (https://github.com/keycloak/keycloak/discussions/29008)

**Comment by m1212e** [comment]
https://github.com/keycloak/keycloak/discussions/29008

**Comment by m1212e** [comment]
The cherry on top: This only happens sometimes. Not 100% of the cases

**Comment by m1212e** [comment]
This seems to be somehow related to using types for resources. E.g. after deletion the evaluation fails for the first time for one resource with the SAME type.

**Comment by m1212e** [comment]
Currently it happens at exactly 50% of cases. Every second time. I'm so confused

**Comment by m1212e** [comment]
Unfortunately I cannot reproduce the errors in a different keycloak instance, wether the same or new version is used. It seems like this doesn't even appear in another realm within the same instance. So reproduceability might be a little limited. Just wanted to report this as this might hint to actual race conditions or logic errors in the code. If you have any questions feel free to ask, I'm happy to help!

**Comment by pedroigor** [comment]
@m1212e Yeah, it can be a warning about something not right and probably in caches or, as you said, perhaps when running the evaluation right after removing things the caches were not invalidated already indicating some concurrency issue.

We need some way to reproduce it as we have some tests that are constantly removing things and running evaluations. Perhaps not the same as in your use case.

We'll keep an eye on related issues and I'll close it for now. Feel free to open a new one if you can help us to reproduce the issue.
