### ISSUE TITLE
Unable to have custom Cors implementation

### ISSUE THREAD

**Issue by ravthiru** [keycloak/keycloak#29312]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Want to provide custom Cors implementation for some of the flows.  with current implementation of
DefaultCors, canot extend it as the constructor is not public. 

Tried using the code from DefaultCors and wrote custom Cors ,by following Server Development documentation https://www.keycloak.org/docs/latest/server_development/#_providers.  
We have created
       a) CustomCorsProvider implementing Cors interface 
       b) CustomCorsFactory implementing CorsFactory with unique id and order as 1
but i could not see the my custom provider in the Keycloak  UI Console and Keycloak is still using DefaultCors.
       

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

I should be able to ovideride defaultCors

### Actual behavior

Keycloak always use default Cors implementation , unble extend or overide default Cors implementation

### How to Reproduce?

implement Custom Cors based on CorsSpi

**Comment by graziang** [comment]
You should also have your factory in `META-INF/services/org.keycloak.services.cors.CorsFactory`.
~question
