### ISSUE TITLE
Allow for any admin recovery via a token

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#29325]
The master realm can be configured to use a passwordless auth flow, or to use some sort of 2nd factor authentication. A simple password recreation such as #29324 would not be enough in those cases. A full recovery process overcomes this by introducing a special auth flow.

The cloud native proposes adding a new kc command, such as “kc.sh recover-admin token [--username=value] [--no-prompt]”. That ccommand generates a JWT token:
* Short lived (5 minutes)
* One time use only
* Signed by master realm key
* Issued for an existing admin user; if it doesn’t exist, creates a new one with specified username

An alternative to a JWT token would be a simple random UUID stored in a database (alongside any metadata like expiration).

The user accesses a special login page meant for admin recovery:
* Served on management interface
  * Possibly on the main HTTP(S) interface to allow easier access via Ingress in K8s environment.
* Is disabled by default
* Handled by a special auth flow.
* Accepts 2 inputs: username and the token that user copy-pasted

Drawbacks:

* Would have the same issues as import / export wrt https://github.com/keycloak/keycloak/issues/28384 - https://github.com/keycloak/keycloak/issues/29200
* Not great usability when containerized - probably need a cr driven mechanism for triggering the creation of the token, which would then be available via a Secret.

After log in, the user is redirected to the Admin Console.

**Comment by stianst** [comment]
Not really keen on this option - it is introducing a lot of complexity. Would be better to expand on the approach taken in https://github.com/keycloak/keycloak/issues/29324 to allow resetting credentials through kc.sh commands and directly updating the DB.

**Comment by vmuzikar** [comment]
> Not really keen on this option - it is introducing a lot of complexity. Would be better to expand on the approach taken in #29324 to allow resetting credentials through kc.sh commands and directly updating the DB.

I agree it's a rather complex approach but not sure what options do we. This is rather aiming for master realms that have hardened security and use a modified auth flows that perhaps require 2FA or don't use passwords at all.

**Comment by vmuzikar** [comment]
Based on the recent discussions, we won't be doing this.
