### ISSUE TITLE
Keycloak UI freezes due to unpaginated loading of large number of dependent policies

### ISSUE THREAD

**Issue by tspiechaczek** [keycloak/keycloak#29335]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

We have encountered a significant issue with the Keycloak UI where it freezes upon attempting to access the list of policies. This behavior occurs because the UI attempts to load all dependent permissions without any limits. In our case, this involves loading more than 20,000 entries, which severely impacts performance and usability.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The UI should handle large numbers of policies efficiently, possibly through pagination or limiting the max number of displayed permissions, to ensure that the system remains responsive and usable.

### Actual behavior

The UI becomes unresponsive and freezes when trying to load a large list of dependent policies.
Affected Version

### How to Reproduce?

1. Populate a client with thousands of permissions that depend on a single, general policy
2. Navigate to the UI section where policies are listed.
3. Attempt to access the list of policies for a resource server 

### Anything else?

This issue complicates manual adjustments and workarounds, particularly when applying configurations through scripts, due to the inability to efficiently manage roles and policies via the UI.

The problematic API endpoint is:
`/authz/resource-server/policy/{id}/dependentPolicies`
(where {id} is a placeholder for the actual policy ID, e.g., `c596d38c-5c78-4f16-84bf-9658c017fe5c`)

This endpoint is currently non-paginated and becomes a bottleneck when used in environments with a large number of dependent permissions. In my opinion, this endpoint shouldn't be exposed without any pagination parameters marked as required.

### Suggested Fix

Implement pagination or another form of efficient data loading for the endpoint mentioned above to improve the management of resources in environments with extensive policy lists.

**Comment by sguilhen** [comment]
Verified - this endpoint (and probably other authz endpoints) needs to be enhanced to accept pagination params, and allow fetching authz resources in smaller batches. I'm adding the priority normal for now, but it can be revisited. If community wants to pick this up, the params can be added to the `PolicyResource` interface in the `keycloak-admin-client-javaee` module, and to `PolicyResourceService` , then forward those to the `JpaPolicyStore` where you can use then in the query.
