### ISSUE TITLE
Align startup initial admin creation with new recovery process

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#29355]
### Description

The [proposed admin password recovery process](https://github.com/keycloak/keycloak/issues/29324) introduces some UX changes to the initial admin user.

This issue covers the following changes to align the existing initial admin creation process with the new recovery process:
* Rename the `KEYCLOAK_ADMIN` env var to `KEYCLOAK_ADMIN_USERNAME`.
* The admin user created via env vars (`KEYCLOAK_ADMIN_USERNAME` and `KEYCLOAK_ADMIN_PASSWORD`) during server start-up will need to change the password after first-time login (enforced via Required Actions).
* Introduce a new `KEYCLOAK_ADMIN_EXPIRE` env var. If `KEYCLOAK_ADMIN_EXPIRE=n`, the password will not be expired, i.e. the user will not need to change the password after  first login.

**Comment by stianst** [comment]
`KEYCLOAK_ADMIN_EXPIRE` is confusing, makes me think that the account itself will expire. Should rather be something like `KEYCLOAK_ADMIN_PASSWORD_TEMPORARY`, which matches the admin UI when resetting a password:

![Uploading image.png…]()

**Comment by stianst** [comment]
If we're renaming the env variables perhaps we should make it clear that it's for the initial admin account? So, could be:

`KEYCLOAK_BOOTSTRAP_ADMIN_USER` and `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD`

A bit long, but it was never quite clear to me that those environment variables where only for bootstrapping, and not a way to manage the account in the long term. Perhaps I'm overthinking it though.

**Comment by stianst** [comment]
`KEYCLOAK_ADMIN_EXPIRE` or whatever it is named should be `true` for prod, and `false` for dev.

**Comment by stianst** [comment]
Before we decide on names and mechanism for bootstrapping an initial admin user it would be good to think about how we'd bootstrap a service account instead.

Thinking out-loud here for a bit, what if we had:

* `KEYCLOAK_BOOTSTRAP_PASSWORD` - creates `admin` user with the supplied password
* `KEYCLOAK_BOOTSTRAP_SECRET` - creates `admin` service account with the supplied client secret

Rather than ask the user to reset the password, I think honestly the bootstrap user/secret should be used to create new real user accounts, so the account itself, and not just the password could be temporary

**Comment by stianst** [comment]
Do the environment variables have config file and cli options as well? So, can I do `kc.sh start-dev --admin-user=admin ...` or do they have to be supplied as environment variables?

**Comment by vmuzikar** [comment]
> Should rather be something like `KEYCLOAK_ADMIN_PASSWORD_TEMPORARY`

+1

> So, could be:
> 
> `KEYCLOAK_BOOTSTRAP_ADMIN_USER` and `KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD`

+1

> Do we even need to provide `KEYCLOAK_BOOTSTRAP_ADMIN_USER`?

I would say we do need to provide it. Isn't it considered an improved security if the name is not baked-in as is provided by user?

> `KEYCLOAK_ADMIN_EXPIRE` or whatever it is named should be `true` for prod, and `false` for dev.

-1 I see some challenges here to make it consistent. Let's take the following example. Someone starts the server in dev, creates a non-temporary admin user, then starts the server in prod profile. The admin user stays non-temporary? Or suddenly is required to change the password? What would the user expect? IMHO it's a pretty common scenario to first start the server in dev, make some changes/experiments and then start the same server in prod profile.

> Before we decide on names and mechanism for bootstrapping an initial admin user it would be good to think about how we'd bootstrap a service account instead.

I perceive managing "admin" service accounts through env vars/CLI as a follow-up task, independent of the initial admin user (although I agree it's closely related). I believe it will require a larger effort to get that right and I would not combine it with the admin user effort.

> Do the environment variables have config file and cli options as well?

Not sure if CLI option makes sense for the admin bootstrap during server startup. We don't accept interactive input there, so env var will always need to be provided for at least the password.

---

@shawkins WDYT?

**Comment by shawkins** [comment]
I'm good with env property changes, and agree we don't need general CLI / config file support. Keeping this implicit / isolated to the recovery commands seems best.

Depending on what we want to allow the operator may set both new and old properties to keep compatibility and/or would we want the server to initially deprecate the old, but still check for it if the new is not set?

**Comment by vmuzikar** [comment]
Superseded by #30003.
