### ISSUE TITLE
Authentication session authNotes missing during update password required action

### ISSUE THREAD

**Issue by arahlf** [keycloak/keycloak#29365]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I'm in the process of upgrading from 20.0.1 to 24.0.3 and have a custom UserStorageProvider that relies on AuthenticationSession authNotes to store some state between the initial authentication and required actions such as forcing a password update.

While testing with the updated version, I noticed that when performing an update password required action, and the "Sign out from other devices" option is checked, my CredentialInputUpdater seems to lose the authNotes that had been previously set and the request fails. But if I simply submit the request again, then it works.

I tried digging into this a bit, and it seems as part of logging out the other sessions, the current session context gets replaced but never set back. So it seems to explain why the first request ends up failing w/ missing auth notes, but then when submitted again (and there are no other sessions to actually clear) it keeps the original session context from the request and the auth notes are present.

Here is the rough path where it seems to be happening:

https://github.com/keycloak/keycloak/blob/24.0.3/services/src/main/java/org/keycloak/authentication/requiredactions/UpdatePassword.java#L139
->
https://github.com/keycloak/keycloak/blob/24.0.3/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L298
->
https://github.com/keycloak/keycloak/blob/24.0.3/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L386

I hope this makes sense, it feels kind of hard to explain.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Custom authNotes previously set on the authentication session are still available.

### Actual behavior

Custom authNotes previously set on the authentication session are not visible during an update password required action.

### How to Reproduce?

- During authentication (e.g. from a custom UserStorageProvider) set an authNote on the AuthenticationSession. The UserStorageProvider's CredentialInputUpdater will use that authNote as part of its processing and will throw an error if not present.
- Log in, but don't log out
- Assign the update password required action to the user
- Log in again while leaving the "Sign out from other devices" option checked
- Note that within the UserStorageProvider's CredentialInputUpdater method the authNote will not be visible and it will throw a validation error (as defined in step 1)
- Submit the update request again and this time the authNote will be available (see my original description for why I think this is happening)

**Comment by mposolda** [comment]
This is hard to nail down as the issue is probably related to custom userStorage provider implementation. And it is possible the issue is rather in the provider implementation. Due to this, it is low priority and Keycloak team likely doesn't have a chance to help with this (without further info proving that this is actual issue in Keycloak).
