### ISSUE TITLE
Custom user attributes are not shown for service account users in the Admin UI

### ISSUE THREAD

**Issue by pboehm** [keycloak/keycloak#29362]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

For confidential clients with service account roles enabled, custom user attributes can be added to the corresponding service account users but they are not shown in the Admin UI.

<img width="1719" alt="image" src="https://github.com/keycloak/keycloak/assets/665684/e014fceb-2c1c-4f22-a9d8-bddb3961218c">

In the screenshot, a custom attribute `test` with value `test` has been successfully added to the service account (the attribute is included in the Keycloak backend response), but it is not shown.

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

For a service account all custom user attributes should the shown in the `Attributes` tab of the service account user details in the Keycloak Admin UI.

### Actual behavior

No custom attributes are shown for service account users. This is true for both migrated and newly created realms and for all possible values of the `Unmanaged Attributes` realm setting.

### How to Reproduce?

* Create a realm `test` with the setting `Unmanaged Attributes="only administrators can write"`
* Create a confidential client `test` with service account roles enabled
* Within "Client Details" / "Service Account Roles" Tab: click on the link "service-account-test"
* Within the "Attributes" tab create an attribute `test` with value `test` and click "Save"
* The attribute ist not shown but is included in the Keycloak Backend response

**Comment by edewit** [comment]
this is a server side problem the `unmanagedAttributes` endpoint doesn't return the right information for service accounts. @pedroigor or do we need to disable attributes completely for service accounts?

**Comment by pedroigor** [comment]
We don't need to. I would say that for service accounts we can always enable unmanaged attributes as these accounts are not backed by a person and do not run flows such as account console, update profile, etc.
