### ISSUE TITLE
redirectToAdmin true by default

### ISSUE THREAD

**Issue by Robbilie** [keycloak/keycloak#29364]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

According to recent changes (https://www.keycloak.org/docs/24.0.0/upgrading/#changes-to-the-welcome-theme) the default behaviour should be the old "welcome page".

In the code, the default value is actually set to false (https://github.com/keycloak/keycloak/blob/4b194d00bed51458acb3d125eba9a0ba654c930a/services/src/main/java/org/keycloak/services/resources/WelcomeResource.java#L187).

The default theme has it set to true though (https://github.com/keycloak/keycloak/blob/4b194d00bed51458acb3d125eba9a0ba654c930a/themes/src/main/resources/theme/keycloak/welcome/theme.properties#L7).

In that sense the documentation is quite missleading:

> By default, the property is set to false, unless you are extending the built-in theme, in which case, the property is set to true.

Yes, if you extend the keycloak theme as a base it is true, but it is also true if you use keycloak in a default setup which uses the keycloak theme by default…

Additional sidenote:

This is breaking the legacy keycloak operator in my setup because it tries to ping the welcome page and gets redirected to the admin url on the external domain and that is not publicly accessible…

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

The welcome page should be shown in a standard keycloak setup according to the documentation.

### Actual behavior

A redirect to the admin page is triggered.

### How to Reproduce?

Start keycloak and try to load the welcome page.

**Comment by Robbilie** [comment]
@jonkoops i think this happened during your changes in https://github.com/keycloak/keycloak/pull/23008 as part of https://github.com/keycloak/keycloak/issues/21343

**Comment by ssilvert** [comment]
I agree that the release notes were confusing or possibly just wrong.

We went through our process and decided to change the default welcome theme to only handle creation of the initial administrator.  Otherwise, it does the redirect.  I'm sorry it was a breaking change for you, but we will not be changing back to the old behavior.

I've assigned this to @andymunro, our documentation specialist.  I think @jonkoops wrote the original text.  They may want to update the release notes.

**Comment by Robbilie** [comment]
Ive built a really hacky workaround to Support my Setup and have the old Operator still working.

My keycloak ist Setup to use non strict hostnames, If the admin redirect would behave Like this too and use the referer/origin instead of the Frontend url this wouldnt have been an issue for me either :)

**Comment by jonkoops** [comment]
> I am using the new operator, the old one ist in use alongside it to make use of the CRDs for clients which the new one doesnt support. 

That is a good point, it should probably be evaluated if that should be supported in the new operator. If there is not yet an issue for it in the backlog feel free to submit one.

> Anyways, I appreciate your concern, but calling http://keycloak-service:8080/ and ending Up with a redirect to https://mypublicdomain.com/admin is still weird behaviour, a relative redirect wouldve probanly been simpler.

I am not convinced that a relative redirect would be more appropriate, as I believe should go to the configured URL for the administration console and nowhere else. I understand that it's frustrating if you are in fact using the legacy operator, but under normal usage this is the desired user experience.

> If you decide that the current Implementation is the proper way to solve this then so be IT, the documentation wording should be adjusted nonetheless to something alongside the lines of yours suggestion :)

Yeah, the documentation here is a tad ambiguous, the wording should be changed here.

**Comment by jonkoops** [comment]
Nice, thanks @vmuzikar I wasn't aware we were already tracking this. I'll close this issue, as I don't think there is any other resolution here.

**Comment by Robbilie** [comment]
@vmuzikar I am actually still using this guide of yours:
https://github.com/keycloak/keycloak-k8s-resources/tree/operators-tandem

should probably migrate…

**Comment by jonkoops** [comment]
Is that guide no longer up-to-date? If so feel free to submit an issue for it.

**Comment by vmuzikar** [comment]
The [guide](https://github.com/keycloak/keycloak-k8s-resources/tree/operators-tandem) is describing of use of the old Operator and was superseded by the instructions for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator). We'll look into removing the guide.
