### ISSUE TITLE
Add a scaling guide under the high availability topic

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#29388]
### Description

We don't provide guidance around scale up / down. It would be good to mention that infinispan must do rebalancing as members join / leave. It would also be good to describe in rough terms when scale up / down should be done in response to cpu, memory, or throughput limitations.

**Comment by shawkins** [comment]
@vmuzikar @keycloak/core @ryanemerson I'd like for there to be a topic inbetween the getting start guides and the HA guides around scaling / performance. It would cover at least this issue and #29391. It could be laid out roughly like:

Scaling and Performance

Intro and when is scaling needed...

Vertical scaling:
- link to ha concepts-memory-and-cpu-sizing
- link to ha concepts-threads
- link to ha concepts-database-connections
- could also mention the vertical pod autoscaler

Horizontal Scaling:
- cover how this also improves availability and link to the HA guide
- link to the operator as the prefered solution, could mention what issues it solve wrt discovery, etc.
- mention embedded infinispan single AZ consideration from #29258
- mention node anti-affinity from #29258 (or this could be strictly an HA topic)
- mention scale up / scale down considerations to satisfy this issue, and probably provide a horizontal pod autoscaler example. Could also mention that using external infinispan addresses the rebalancing concern.

Does something like this seem worthwhile and/or is it covered sufficiently by the HA guide?

**Comment by ryanemerson** [comment]
+1. These are all valid considerations for non-ha deployments, so I think it makes sense we document these topics outside of the HA guide.

> * mention node anti-affinity from [Support pod affinity settings in the Keycloak Operator #29258](https://github.com/keycloak/keycloak/issues/29258) (or this could be strictly an HA topic)

My understanding is that HA is related to multi-site deployments. I think anti-affinity is an important consideration for single site deployments, so I would include this in your proposed guides.

**Comment by kami619** [comment]
@shawkins thank you for logging this issue, I myself was contemplating on something like this to be added to our roadmap. We shall definitely bring this to the team and find time to add more data points. I am also interested in using a Horizontal Pod Autoscaler in our provisioning layer within `keycloak-benchmark` @ryanemerson is right about stating this `Scaling` guide(s) applies to beyond the scope of Cross-Site, but falls in the umbrella of Highly Available Keycloak.
