### ISSUE TITLE
Misleading error message for broken user federation

### ISSUE THREAD

**Issue by bjoernhype** [keycloak/keycloak#29381]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Keycloak can be used with a) Identity Providers and b) User Federation. Trying to log in to a realm with b or both, when the required service for b is offline, results in error. This is expected. But the error message is "Unexpected error when handling authentication request to identity provider.". This is misleading, as the problem is not in the (possibly also existing) identity provider, but in the user federation.
Java: `UNEXPECTED_ERROR_HANDLING_REQUEST="unexpectedErrorHandlingRequestMessage"`
Messages: `unexpectedErrorHandlingRequestMessage=Unexpected error when handling authentication request to identity provider.`
So the problem is that this message is used for both problems with identity provider and user federation, but its text seems to handle only the identity provider case

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Either 2 separate messages for these two cases, or a common message which names both reasons.

### Actual behavior

Common message saying there is a problem with identity provider:
`unexpectedErrorHandlingRequestMessage=Unexpected error when handling authentication request to identity provider.`

### How to Reproduce?

Register a user federation, leave it offline, and try to log in using it

### Anything else?

Small prio, but wanted to mention is it can be confusing

**Comment by sguilhen** [comment]
I can see how it can be misleading, and I would even argue that the message should be simply "Unexpected error handling authentication request", with no mention to the provider. However, changing this is not that simple because we would need to change every message catalog to fix it in all supported languages. I'll still add this a low priority issue.
