### ISSUE TITLE
Better default for persistence availability interval

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#29395]
### Description

The default persistence availability interval in Infinspan 15 is 30 seconds. This task periodically checks the connection to the persistence (whether it is an external Infinispan Server or an external database).

The 30-second default may be on the higher side and a better default for Keycloak is needed. There are 2 possible solutions

* Check the XML file and, if not configured, set a more appropriate default (in other words, do not overwrite the value set by the user)
* Add an SPI option to configure. 

The latter has the advantage of not requiring a custom XML file.

**Comment by ahus1** [comment]
We seem to agree on the first part "Check the XML file and, if not configured, set a more appropriate default (in other words, do not overwrite the value set by the user)". 

The second option would be more of a general discussion what people should configure (and then it would need to come with some docs what value to choose and when)
