### ISSUE TITLE
JDBC_PING2 as default discovery protocol

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#29399]
### Description

The default discovery protocol provided by Infinispan uses IP multicast (`MPING`) to find its peers in the network. Although it is perfectly fine for an environment with IP multicast available, `JDBC_PING2` seems a better fit as a default discovery protocol for Keycloak. 

The `JDBC_PING2` protocol uses a database to keep track of the peer's IP addresses (and ports) and, we can use the Keycloak database as a registry.

The following work is required:

* Create a custom stack, replacing `MPING` with `JDBC_PING2`
* Infinispan 15.0.3.Final allows injecting a data source into `JDBC_PING2` for Infinispan Server (see https://issues.redhat.com/browse/ISPN-15961). The same code can be used by Keycloak to inject the Quarkus data source into JGroups.
* (UX improvement) Somehow detect the database dialect to configure the `JDBC_PING2` queries (select, delete, insert). The goal is to achieve zero-config for users.
* Set values for remaining options based on user feedback and/or issues found.

`JDBC_PING2` documentation is available here: http://jgroups.org/manual5/index.html#JDBC_PING2

### Discussion

https://github.com/keycloak/keycloak/discussions/29205

### Motivation

To simplify Keycloak usage and configuration.

**Comment by ryanemerson** [comment]
I have created an Infinispan branch which includes various test scenarios for JDBC_PING and JDBC_PING2 https://github.com/ryanemerson/infinispan/tree/JDBC_PING_tests

During this work, I added a `JdbcPingIT#testZombieProcess` which  tests a scenario described by Bela that JDBC_PING2 was supposed to solve. Unfortunately, this scenario causes both protocols to hang and Infinispan server startup is no longer possible.

I have also created WIP branch, based upon @pruivo's initial work, which makes JDBC_PING the default discovery protocol https://github.com/ryanemerson/keycloak/tree/jdbc_ping. However, this work is on hold until the underlying issues with JDBC_PING(2) have been resolved.

**Comment by gatos-cc** [comment]
So - we've had Keycloak 25.0.1 running with JDBC_PING for quite a while now.  Just tried to upgrade to 26.2.4 and all the cluster discovery broke (JDBC Ping finds the other instances but for some reason can't connect).

Is there a decent summary/how-to/etc on how to get all this working in v26+?  Like I'm not sure what options there are out there to even figure out why a node isn't able to communicate:

```
2025-05-09 19:29:00,308 INFO  [org.jgroups.protocols.FD_SOCK2] (main) server listening on *:57800
2025-05-09 19:29:02,339 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 0
2025-05-09 19:29:04,346 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 1
2025-05-09 19:29:06,353 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 2
2025-05-09 19:29:08,359 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 3
2025-05-09 19:29:10,365 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 4
2025-05-09 19:29:12,372 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 5
2025-05-09 19:29:14,377 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 6
2025-05-09 19:29:16,384 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 7
2025-05-09 19:29:18,390 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 8
2025-05-09 19:29:20,395 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: JOIN(cc5d00201f04-49634) sent to 7768a0cf6a4a-2231 timed out (after 2000 ms), on try 9
2025-05-09 19:29:20,396 WARN  [org.jgroups.protocols.pbcast.GMS] (main) cc5d00201f04-49634: too many JOIN attempts (10): becoming singleton
```

The ports are open - its the same hardware 25.0.1/JDBC_PING was working on before.  But there's no real information on why it couldn't communicate...

Sorry - setting Keycloak up in a clustered configuration has always been one of the biggest headaches to using it for me.

jgroups conf:

```
    <jgroups>
        <stack name="jdbc-ping-tcp" extends="tcp">
            <!-- NOTE - injected by the start script. -->
            <TCP
              external_addr="${env.EC2_PRIVATE_IP}"
              bind_port="7800"
            />
            <JDBC_PING connection_driver="com.mysql.jdbc.Driver"
                       connection_username="${env.KC_DB_USERNAME}" connection_password="${env.KC_DB_PASSWORD}"
                       connection_url="jdbc:mysql://${env.KC_DB_URL_HOST}:${env.KC_DB_URL_PORT:3306}/${env.KC_DB_URL_DATABASE}${env.KC_DB_URL_PROPERTIES:}"
                       initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, bind_addr varchar(200) NOT NULL, updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ping_data varbinary(5000) DEFAULT NULL, PRIMARY KEY (own_addr, cluster_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8"
                       insert_single_sql="INSERT INTO JGROUPSPING (own_addr, cluster_name, bind_addr, updated, ping_data) values (?, ?, '${env.JGROUPS_DISCOVERY_EXTERNAL_IP:127.0.0.1}', NOW(), ?)"
                       delete_single_sql="DELETE FROM JGROUPSPING WHERE own_addr=? AND cluster_name=?"
                       select_all_pingdata_sql="SELECT ping_data, own_addr, cluster_name FROM JGROUPSPING WHERE cluster_name=?"
                       clear_sql="DELETE FROM JGROUPSPING WHERE cluster_name=?"
                       info_writer_sleep_time="500"
                       remove_all_data_on_view_change="true"
                       stack.combine="REPLACE"
                       stack.position="MPING" />
        </stack>
    </jgroups>
```

**Comment by gatos-cc** [comment]
OK - seems this is the new docs: https://www.keycloak.org/server/caching

That makes me feel a little better, though I removed all my old custom config, launched with `--cache=ispn` and I'm still getting the same behavior.  The other instances can be found, but not communicated with.  Something changed in how the cache communication is happening.... maybe how ports are bound or something?

**Comment by ahus1** [comment]
@gatos-cc - sorry to hear this is not working for you. My first thought would have been that the old configuration should still work unless your old stack is named `jdbc-ping` or `jdbc-ping-udp`. I will need to look deeper into that. 

I see that your old configuration is using `external_addr="${env.EC2_PRIVATE_IP}"` ... please check on which address Keycloak should bind to, and which address it should advertise to the other nodes. See [the docs](https://www.keycloak.org/server/caching#network-bind-address) for additional information.

To debug this, please look into the (new) table `jgroups_ping` and the column `ip`: This should be the address and port that is visible to the other nodes. And use `netstat` or a similar tool to verify which address Keycloak is listening on (if that should be different from what is in the database).

**Comment by ahus1** [comment]
On another note: Please share your startup parameters and possibly a modified cache XML file, so we can check why it didn't work with the existing configuration.

**Comment by gatos-cc** [comment]
Thanks a ton @ahus1 - there were a few issues, but really boils down to:
1 - remove all the custom JDBC ping stuff I had to do in the past and just rely on the out of the box settings
2 - mess with the `jgroups.external_addr` setting - guess that changed a little along the way as well

Seems to be working now.  Honestly this is great that it works out of the box now, would've saved me ages a couple years ago.

**Comment by ahus1** [comment]
Thank you for the update. It is good to hear that you consider the new setup simpler than the old one. 

Still we were aiming a little higher here: We wanted the upgrade to the new version to be seamless, and update of any existing Infinispan configuration optional during the initial upgrade, so people you do this as a second step once they are happy with the upgrade. 

Can you please share more information about your setup and the behavior you saw in a bug issue and link it here? 

@pruivo - if you think you have already some ideas with the information provided here, please go ahead an open an issue. 

Thanks!

**Comment by pruivo** [comment]
@ahus1 I can't tell what's the problem 🤣 I'm guessing the external address was set to something wrong.
