### ISSUE TITLE
Realm client unset protocol not preserved

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#29413]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Since #29037, if a realm-type client (e.g. `master-realm` client) is saved, its protocol is overridden to `openid-connect` while it should be preserved empty.

This causes the client not to be recognized as an internal client, and the UI treats it as a normal client, displaying e.g. Keys and Credentials tabs.

Original code:
https://github.com/keycloak/keycloak/blob/65bdf1a60474aef735c8fd7dda3fc53185758a76/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L519

New code:
https://github.com/keycloak/keycloak/blob/2055cf62f246d09ddb0b3747e54b5c8a841c1494/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L522

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Saving the client does not change the protocol.

### Actual behavior

Saving the client changes the protocol.

### How to Reproduce?

1. Create a realm `aa`.
2. Go to `aa-realm` client details
3. Click on Save
4. Reload the client details - two more tabs are now displayed.

### Anything else?

I am not sure if this should be treated as a regression in core or a UI bug. @mposolda, could you please help here?

**Comment by hmlnarik** [comment]
> I wonder if we can have some client attribute like INTERNAL_CLIENT, which would be set to true for Keycloak internal clients and UI can consume to more reliably detect if particular client should be treated as internal client or not? On the other hand, introducing that would be some migration effort...

@mposolda This seems like a way to go. In the ideal case, this could be only a "virtual" flag present in a `ClientRepresentation` computed by the server and not necessarily stored in the database. That way no migration would be needed. WDYT?

**Comment by hmlnarik** [comment]
I am moving this to the core team backlog as per the comment above and putting to triage state so that it can be properly handled by the core team.

**Comment by mposolda** [comment]
For the context, We discussed with @hmlnarik that this may be handled possibly without DB migration needed. The server can have "list of known clients" (like `broker`, `realm-admin` etc) and add the attribute flag `INTERNAL_CLIENT` for all those clients whenever they are returned from admin REST API, so admin console can consume this and handle this properly as internal clients.

**Comment by graziang** [comment]
The admin UI recognizes clients as realm clients by checking if the `client.protocol `is null. There seem to be differences in how the admin UI displays default clients like `broker` and realm clients like `master-realm`, `aa-realm`, etc. 

   https://github.com/keycloak/keycloak/blob/90a88976b632c4dcc9d79c8d514c816d5e44bdb6/js/apps/admin-ui/src/clients/utils.ts#L7

Default clients have the protocol set to `openid-connect`, realm clients have protocol set to null.

Should we set the `INTERNAL_CLEINT` (or `REALM_CLIENT` at this point) attribute only to clients with clientId equal to `{realm}-realm` where `{realm}` is the name of an existing realm?
