### ISSUE TITLE
Authorization tab for master-client shows up in odd ways

### ISSUE THREAD

**Issue by Jamstah** [keycloak/keycloak#29423]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When you first start keycloak, the `master-realm` client has no **Authorization** tab.

If you turn on fine-grained permissions for any client, the `master-realm` then has the **Authorization** tab.

Turning permissions off does not result in the **Authorization** tab going away again.

This is causing test failures in the admin-ui E2E tests, because the number of tabs is tested for this client and will vary depending on which tests have been run before it in that container.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Existence of Authorization tab should be predictable

### Actual behavior

Authorization tab may or may not exist based on previous tests

### How to Reproduce?

1. Create an empty server using `--features=admin-fine-grained-authz`
2. Check the number of tabs in the master-realm client
3. Turn permissions on in a client
4. Check the number of tabs in the master-realm client
5. Turning permissions back off, or deleting the client, does not affect the number of tabs

**Comment by hmlnarik** [comment]
Thank you for reporting this bug. I am closing it in favour of #29443 since the latter targets core functionality where this bug report belongs. Feel free to watch that issue.
