### ISSUE TITLE
realm_settings_general_tab_test.spec fails randomly

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#29468]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After running user_fed_ldap_hardcoded_mapper_test.spec.ts, running realm_settings_general_tab_test.spec.ts fails.

See https://github.com/keycloak/keycloak/actions/runs/9055714397/job/24877310977?pr=29465

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

test passing always

### Actual behavior

test fails

### How to Reproduce?

Run the cypress tests in the order above

**Comment by hmlnarik** [comment]
```
1  cypress/e2e/clients_saml_test.spec.ts              
2  cypress/e2e/realm_settings_general_tab_test.spec.ts
3  cypress/e2e/user_fed_ldap_test.spec.ts             
4  cypress/e2e/realm_test.spec.ts                     
5  cypress/e2e/group_test.spec.ts                     
6  cypress/e2e/partial_import_test.spec.ts            
7  cypress/e2e/identity_providers_oidc_test.spec.ts   
```

https://github.com/keycloak/keycloak/actions/runs/9094710844/job/24996632923?pr=29560

**Comment by hmlnarik** [comment]
https://github.com/keycloak/keycloak/actions/runs/9200617267?pr=29801

```
1  cypress/e2e/partial_import_test.spec.ts            
2  cypress/e2e/realm_settings_general_tab_test.spec.ts
3  cypress/e2e/user_fed_ldap_test.spec.ts             
4  cypress/e2e/user_fed_ldap_mapper_test.spec.ts      
5  cypress/e2e/authentication_policies_ciba.spec.ts   
6  cypress/e2e/realm_user_registration.spec.ts        
7  cypress/e2e/masthead_test.spec.ts
```

[cypress-videos-2-chrome.zip](https://github.com/keycloak/keycloak/files/15413851/cypress-videos-2-chrome.zip)

**Comment by mabartos** [comment]
https://github.com/keycloak/keycloak/actions/runs/9285154296/job/25549341766?pr=28518#step:11:205

```
Realm settings general tab tests
    (Attempt 1 of 4) Test all general tab switches
    (Attempt 2 of 4) Test all general tab switches
    (Attempt 3 of 4) Test all general tab switches
    1) Test all general tab switches
    ✓ Fail to set Realm ID to empty (1778ms)
    ✓ Modify Display name (2189ms)
    ✓ Check Display name value (1504ms)
    ✓ Modify front end URL (1964ms)
    ✓ Select SSL all requests (1863ms)
    ✓ Verify SSL all requests displays (1555ms)
    ✓ Select SSL external requests (1756ms)
    ✓ Verify SSL external requests displays (1494ms)
    ✓ Select SSL None (1759ms)
    ✓ Verify SSL None displays (1543ms)
    ✓ Check Access Endpoints OpenID Endpoint Configuration link (1490ms)
    ✓ Access Endpoints OpenID Endpoint Configuration link (1605ms)
    ✓ Check if Access Endpoints SAML 2.0 Identity Provider Metadata link exists (1534ms)
    ✓ Access Endpoints SAML 2.0 Identity Provider Metadata link (1511ms)
    ✓ Verify 'Revert' button works (1923ms)


  15 passing (3m)
  1 failing

  1) Realm settings general tab tests
       Test all general tab switches:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `.pf-v5-c-alert__title`, but never found it. Queried from:

              > cy.findByTestId(global-alerts)
      at Masthead.checkNotificationMessage (webpack://admin-ui/./cypress/support/pages/admin-ui/Masthead.ts:90:0)
      at Context.eval (webpack://admin-ui/./cypress/e2e/realm_settings_general_tab_test.spec.ts:44:0)
```

https://github.com/keycloak/keycloak/assets/38039883/98f177a7-ab9d-4da9-95d6-28749550495f

**Comment by ahus1** [comment]
It failed again in https://github.com/keycloak/keycloak/actions/runs/9317327504/job/25647652001?pr=30027 and https://github.com/keycloak/keycloak/actions/runs/9317327504/job/25649174962?pr=30027

**Comment by edewit** [comment]
@ahus1 don't link to runs they are only stored temporary

**Comment by ahus1** [comment]
@edewit - I wouldn't know what information you want to grab from those runs, so I would hope you can help out here to capture what the UI team needs.
