### ISSUE TITLE
IDP's always showing even when "Identity provider redirector is removed"

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#29477]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I create a copy of the Browser authentication flow. Then I disable or remove the "Identity provider redirector". Nevertheless, all the configured identity providers show on the login page.
Not a theme issue, this happens across all themes.

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

No IDP is shown if IDP redirector is disabled

### Actual behavior

All IDP's are shown

### How to Reproduce?

Copy browser flow.
Delete Identity provider redirector of the new flow.
IDP's still shown on login for that client.

**Comment by rmartinc** [comment]
Hi @oculos!

The `identity-provider-redirector` authenticator is used to directly redirect the user to an Identity provider using the `kc_idp_hint` parameter. AFAIK this has never removed the links in the login page. Doing that makes no sense IMHO (you can want to remove the redirector but still use links in the login page). You can use the `Hide on login page` option in the IdPs to not show IdPs in the page.

In what version did you see that behavior? Just to test I'm right.

**Comment by rmartinc** [comment]
I think that there is no way to do that via configuration. I would recommend you to just create a new theme with the `login.ftl`, remove or empty the socialProviders part in the page and assign that theme to the clients you don't want IdPs displayed. Note that a user can login to a client using an IdP and then access another client without seeing the login page.

**Comment by oculos** [comment]
Thanks @rmartinc . Yeah, I'm aware that a user could bypass the the login anyway. I think I'll do a combination of what you suggested and see if I can use some rules to prevent certain roles to access the client. Don't know if that's possible without extensions, though.

**Comment by rmartinc** [comment]
Thanks, closing then as not planned.
