### ISSUE TITLE
GET users endpoint is making lots of requests to the database

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#29480]
### Description

In Keycloak, calling this URI /auth/admin/realms/somrealm/roles/something/users result in 142 jdbc query. The total time taken may go up to 25 seconds which is too long. As you can see in the attached screenshot, we have multiple jdbc query.
What can justify the multiple SQL? How can we improve? There are only 147 users in a role. Whenever they tried to access the role users, this is getting called and impacts the performance.

This looks similar to the issue specified in [KEYCLOAK-6134](https://issues.redhat.com/browse/KEYCLOAK-6134).

More info in the original ticket

**Comment by mposolda** [comment]
Adding to Keycloak 25 for now. We may need to postpone if lots of other issues...

**Comment by rmartinc** [comment]
@mposolda Checking this the issue and [KEYCLOAK-6134](https://issues.redhat.com/browse/KEYCLOAK-6134) the problem in the role endpoint is that the user is returned in full. So every user should query the attributes, credential, required actions,... In the [KEYCLOAK-6134](https://issues.redhat.com/browse/KEYCLOAK-6134) the solution was adding the `briefRepresentation` and then just return the basic details of the user and just the first query is needed. If you want we can do the same here.
