### ISSUE TITLE
Default theme logs font related console errors on firefox

### ISSUE THREAD

**Issue by corneliusroemer** [keycloak/keycloak#29486]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

On Firefox only, I get a lot of console errors related to the Open Sans font for the default theme's login page and probably all other pages (or at least all pages that use patternfly). 

This is one console error, there's quite a lot of them, a bit unpleasant.

```
downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:400 stretch:100 src index:3) source: https://authentication-main.loculus.org/resources/gfdpy/login/loculus/resources-common/node_modules/patternfly/dist/fonts/OpenSans-Regular-webfont.woff2
```

<img width="1907" alt="Firefox 2024-05-13 17 32 14" src="https://github.com/keycloak/keycloak/assets/25161793/ed96b22c-218e-4ffd-96fc-19cfb276804a">

 

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

No console errors

### Actual behavior

Console errors

### How to Reproduce?

1. Run
```bash
docker run -e KEYCLOAK_ADMIN_PASSWORD=admin -e KEYCLOAK_ADMIN=admin -p 8080:8080 quay.io/keycloak/keycloak start-dev
```
2. Open dev tools on firefox
3. Load localhost:8080
4. Observe

### Anything else?

See: https://stackoverflow.com/questions/35206815/font-loading-error-downloadable-font-kern-too-large-subtable-table-discarded

First reported at keycloakify/keycloakify#548

This has been an issue for however long patternfly has been used.

**Comment by jonkoops** [comment]
This is likely fixed in the login v2 theme, could you enable that and let us know if the issue persists there?

**Comment by garronej** [comment]
Hello @jonkoops,  

When enabling login v2 does the FreeMarker's `data_model` changes?

**Comment by corneliusroemer** [comment]
Thanks @jonkoops - when I switched away from the base themes (not necessarily called v2, at least in case of login, it's just called keycloak), the console errors no longer appear.

These were the themes I switched to (the only ones available apart from base):
<img width="713" alt="Firefox 2024-05-14 00 08 18" src="https://github.com/keycloak/keycloak/assets/25161793/137974d1-d76d-4283-bab4-be9206c155dd">

Maybe that also answers @garronej's question: it seems like `keycloak/login` _is_ v2, whereas `base` (the default) is v1?

**Comment by garronej** [comment]
> Maybe that also answers @garronej's question: it seems like keycloak/login is v2, whereas base (the default) is v1?  

The question I was asking is more technical. I wanted to know if when strarting Keycloak with the `--features=login2` a different FreeMarker context is used to render the templates.

**Comment by jonkoops** [comment]
> I wanted to know if when strarting Keycloak with the `--features=login2` a different FreeMarker context is used to render the templates.

The environment for the templates should be exactly the same, the class backing it has not changed. The main purpose of the V2 theme is to get rid of old PatternFly versions as the V1 theme includes both PatternFly 3 and 4. The new theme will be using PatternFly 5, which also has different class names and DOM structure, so both CSS and HTML need to be revisited.

**Comment by garronej** [comment]
@jonkoops Thank you very much for claryfing this for me!

**Comment by jonkoops** [comment]
I'll mark this as a low impact bug, if anyone wants to go ahead and fix it be my guest, if it's not important enough this should be resolved once we roll out the new theme version.
