### ISSUE TITLE
Remove Oracle JDBC driver out of the box

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#29491]
### Description

As Keycloak seeks to complete the incubating onboarding items, it must align with the CNCF license policy, which mandates board approval for non-Apache 2.0 dependencies.

To resolve potential license compliance issues, modify future Keycloak community releases to exclude the Oracle driver, requiring it to be installed separately by users. This practice helps address licensing concerns. Note that this change is not applicable to past releases.

### Acceptance Criteria
1. Confirm that excluding the Oracle driver from future releases addresses specific licensing violations.
2. Update installation guides to include instructions for users on how to install the Oracle driver manually.
3. Adjust the build process to exclude the Oracle driver from all future community releases.
4. Communicate this change to the community, highlighting the reasons related to licensing compliance.

**Comment by abstractj** [comment]
cc @keycloak/core-clients @keycloak/core-iam @keycloak/maintainers

**Comment by vmuzikar** [comment]
Yes, this would be done by the Cloud Native team. We'll look into it.

**Comment by vmuzikar** [comment]
Based on an offline discussion with @abstractj, changed the milestone and priority.
