### ISSUE TITLE
Migrate HA guide to use persistent sessions feature

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#29505]
This requires going through whole HA guide and adapt it to the fact the persistent sessions feature is enabled by default:

For example:
- https://www.keycloak.org/high-availability/concepts-active-passive-sync - sessions are no longer lost on upgrades
- https://www.keycloak.org/high-availability/deploy-keycloak-kubernetes 
  - enable the feature
  - set `maxCount` for embedded caches
- https://www.keycloak.org/high-availability/deploy-infinispan-kubernetes-crossdc - set owners to 1?
- https://www.keycloak.org/high-availability/operate-network-partition-recovery - we can simplify this guide to not include sessions in the state transfer?

**Comment by ahus1** [comment]
Please re-use and update, or close it if it no longer necessary. Thanks!

**Comment by mhajas** [comment]
This is no longer relevant as all changes were already updated when migrating to the new multi-site version that is using persistent sessions by default.
