### ISSUE TITLE
Modifying Client Authorization via API Has No Effect

### ISSUE THREAD

**Issue by remithomasn7** [keycloak/keycloak#29533]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

I have an existing confidential client "my-confidential-client". I already defined resources, scopes, policies and permission for "my-confidential-client".
I created this client from a json file (I have a standard client template that I edit when creating a new client), using the following command:

curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${ACCESS_TOKEN}" \
              --data-binary "@/usr/local/etc/my-apps/my-confidential-client.json" \
              "${KEYCLOAK_URL}/${REALM_NAME}/clients"

Where KEYCLOAK_URL is something like "http://KCdnsName/auth/admin/realms

The admin API created my confidential client as expected. That's fine.

Then, I want to add a scope "new-scope" for one of my existing resources in "my-confidential-client". I edited my JSON file to add a scope in the list of scopes, in the scopes of my resources, and updated my scope-base permission.

To apply my changes, I still used the admin API, but using the following command:
curl -X PUT \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${ACCESS_TOKEN}" \
          --data-binary "@/usr/local/etc/my-apps/my-confidential-client.json" \
          "${KEYCLOAK_URL}/${REALM_NAME}/clients/${my_app_clientId}

I receive a valid status code from the admin API. However when I query the authorizations of my client nothing has been updated. As if my api calls have no effect.

I checked that my JSON file is valid by doing the update through the UI. It worked.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that calling the admin API to update confidential client authorizations configuration has effect.

### Actual behavior

The admin API call has no effect (and no error).

### How to Reproduce?

Create a confidential client with resources, scopes, at list a policy, and scope-based permission manually (or using the API admin). Then try to add a scope in a resource and update the new authorization configuration through an admin API call.

**Comment by rmartinc** [comment]
Can you please attach an example of you json file? It would be much easier to test.

**Comment by mposolda** [comment]
@remithomasn7 You are right that when creating/updating client, the "authorization" entities like policies, resources, permissions etc are not automatically updated.

There are separate admin API endpoints for updating authorization entities. When you open admin console and you try to update some authorization objects of some client in admin UI, you can inspect with some tool like for example firebug for firefox what REST requests are updated under-the-covers (as admin console updates everything by using admin REST API).

Because it is possible to update authorization entities by separate admin REST API endpoint, I consider this as very low priority.

**Comment by remithomasn7** [comment]
Ask suggested by @rmartinc, please find an example json configuration file

my-confidential-client.json
{
    "clientId": false,
    "surrogateAuthRequired": false,
    "enabled": true,
    "alwaysDisplayInConsole": false,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [],
    "webOrigins": [],
    "notBefore": 0,
    "bearerOnly": false,
    "consentRequired": false,
    "standardFlowEnabled": false,
    "implicitFlowEnabled": false,
    "directAccessGrantsEnabled": true,
    "serviceAccountsEnabled": true,
    "authorizationServicesEnabled": true,
    "publicClient": false,
    "frontchannelLogout": false,
    "protocol": "openid-connect",
    "attributes": {
      "id.token.as.detached.signature": "false",
      "saml.assertion.signature": "false",
      "saml.force.post.binding": "false",
      "saml.multivalued.roles": "false",
      "saml.encrypt": "false",
      "oauth2.device.authorization.grant.enabled": "false",
      "backchannel.logout.revoke.offline.tokens": "false",
      "saml.server.signature": "false",
      "saml.server.signature.keyinfo.ext": "false",
      "use.refresh.tokens": "true",
      "exclude.session.state.from.auth.response": "false",
      "oidc.ciba.grant.enabled": "false",
      "saml.artifact.binding": "false",
      "backchannel.logout.session.required": "true",
      "client_credentials.use_refresh_token": "false",
      "saml_force_name_id_format": "false",
      "require.pushed.authorization.requests": "false",
      "saml.client.signature": "false",
      "tls.client.certificate.bound.access.tokens": "false",
      "saml.authnstatement": "false",
      "display.on.consent.screen": "false",
      "saml.onetimeuse.condition": "false"
    },
    "authenticationFlowBindingOverrides": {},
    "fullScopeAllowed": true,
    "nodeReRegistrationTimeout": -1,
    "authorizationSettings": {
      "allowRemoteResourceManagement": true,
      "policyEnforcementMode": "PERMISSIVE",
      "decisionStrategy": "AFFIRMATIVE",
      "resources": [
        {
          "name": "apiinventorygrpc.ProductService",
          "ownerManagedAccess": false,
          "displayName": "apiinventorygrpc.ProductService",
          "attributes": {},
          "uris": [],
          "scopes": [
            {
              "name": "Create"
            },
            {
              "name": "Get"
            }
          ]
        }
      ],
      "policies": [
        {
          "name": "any",
          "type": "role",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "config": {
            "roles": "[{\"id\":\"maintainer\",\"required\":false},{\"id\":\"editor\",\"required\":false},{\"id\":\"user\",\"required\":false}]"
          }
        },
        {
          "name": "product",
          "description": "",
          "type": "resource",
          "logic": "POSITIVE",
          "decisionStrategy": "AFFIRMATIVE",
          "config": {
            "resources": "[\"apiinventorygrpc.ProductService\"]",
            "applyPolicies": "[\"any\"]"
          }
        }
        ],
      "scopes": [
        {
          "name": "Create"
        },
        {
          "name": "Get"
        }
      ]
    }
  }
  
When I create a client it works well. But at update, only the list of scopes is updated. 
Maybe should I use the following endpoint to update my client authorizations:

PUT /admin/realms/{realm}/clients/{id}/management/permissions

I would like to mention that I do not think this is a regression. I think I get confused, and that I have never been able to do such an update in v22.0.X

I found a workaround. I get all the data of my existing confidential client, update the JSON file to add scopes/permissions. Then I delete and recreate it (using the previous client secret).

As this workaround is valid on my side, and considering that I misunderstood how the admin API should be use, I sugget to close this issue.
