### ISSUE TITLE
Erro de Login e Senha https://amei.sebrae.com.br/auth/realms

### ISSUE THREAD

**Issue by myeletrik** [keycloak/keycloak#29532]
### Description

O login e Senha ao cadastrar no sistema ele fica em loop infinito.

O mesmo acontece também, em recuperar senha.

### Discussion

https://amei.sebrae.com.br/auth/realms

### Issues

2

### Motivation

 loop infinito.

**Comment by jonkoops** [comment]
We only accept issues reported in English with proper steps to reproduce. Also if you are having an issue please use the proper template for it. For questions please use the forum instead.
