### ISSUE TITLE
When creating a user, Username is not the only required field

### ISSUE THREAD

**Issue by jinqueeny** [keycloak/keycloak#29543]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The note says "Username is the only required field." but on the admin console, Email is the only required field.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The document needs to be consistent with the admin console where Email is the only required field.

### Actual behavior

The note says "Username is the only required field." but on the admin console, Email is the only required field
![Screenshot 2024-05-15 083122](https://github.com/keycloak/keycloak/assets/6220704/e16f3855-f80b-458e-951f-0ed84aaf32dd)

### Anything else?

This might be because of some level of customization.

**Comment by ssilvert** [comment]
This happens when the realm setting "Email as username" is true.  So in this case, the email is the user name and the documentation is correct.

I'll admit that the docs could be a little more clear on this, but
