### ISSUE TITLE
OAuth 2.0 Device Polling Interval - Setting in Realms settings/Token Plus-Minus to change value not working

### ISSUE THREAD

**Issue by xerberde** [keycloak/keycloak#29551]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

OAuth 2.0 Device Polling Interval - Setting in Realms settings/Token Plus-Minus to change value not working

1. Realms Settings
2. Token Tab
3. OAuth 2.0 Device Polling Interval
4. Use + / - to change the value 
5. Not working value did not change. Button for + / - didn't work

### Version

24.04

### Regression

- [ ] The issue is a regression

### Expected behavior

+1 / -1 for the value in Text field

### Actual behavior

 value in Text field not changed

### How to Reproduce?

1. Realms Settings
2. Token Tab
3. OAuth 2.0 Device Polling Interval
4. Use + / - to change the value 
5. Not working value did not change. Button for + / - didn't work

**Comment by ssilvert** [comment]
I have verified this bug.  A PR to fix it would be appreciated.

**Comment by ahanamallik1** [comment]
@ssilvert I have raised the PR #29624
