### ISSUE TITLE
Docs: server_development/topics/admin-rest-api.adoc

### ISSUE THREAD

**Issue by b509** [keycloak/keycloak#29562]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

URLs missing /auth

File: server_development/topics/admin-rest-api.adoc

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

URL for getting the token ("Obtain an access token for the user in the realm master with username admin and password password:") is
"http://localhost:8080/**auth/**realms/master/protocol/openid-connect/token"

URL for trying the access token ("The following example shows how to get the details of the master realm:")
http://localhost:8080/**auth/**admin/realms/master

Probably more examples on this page, haven't checked everything

### Actual behavior

See above

### How to Reproduce?

See above

**Comment by stianst** [comment]
Keycloak doesn't by default include `/auth` since quite a while

@invalid
