### ISSUE TITLE
IdentityProviderAuthenticator: Wrong error message if wrong IDP is chosen in the Identity Provider Redirector step

### ISSUE THREAD

**Issue by NThobae** [keycloak/keycloak#29591]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

In an authentication flow, if the IdentityProviderRedirector is configured with a non-existing IDP name, the user who tries to log in receives the error "InvalidUser" with the message "Invalid username or password". This makes it seem like that it is in error from the user side, but is actually a server configuration error. A more generic error message like "server error" would be a better response.

![grafik](https://github.com/keycloak/keycloak/assets/23555121/aa5f9b14-a031-4c4b-8f67-5428cdd808db)

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Should have a fitting error message, which hints to that it is a server error.

### Actual behavior

The user gets a misleading and wrong error message (InvalidUserMessage). 

### How to Reproduce?

- Go to Authentication
- Duplicate the browser flow
- Bind the duplicated browser flow as "browser flow"
- Add as first step the IdentityProviderRedirector
- Click the settings icon of the IdentityProviderRedirector
- Set the alias to something
- Set the "Default Identity Provider" to a non-existing IdentityProvider (e.g. "test")
- Try to log in from the Account Console
- See Error Message

![grafik](https://github.com/keycloak/keycloak/assets/23555121/40a38d13-accf-4482-ac60-97d81f0038cc)

### Anything else?

Our guess would be that an error in the context should be set here: org.keycloak.authentication.authenticators.browser.IdentityProviderAuthenticator#99

**Comment by rmartinc** [comment]
Hi @NThobae!

The [IdentityProviderAuthenticator](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/IdentityProviderAuthenticator.java#L86) tries to locate the IdP and, if it's missing, it logs a warning `Provider not found or not enabled for realm test` and returns attempted (it tried to redirect but the idp was missing, so let the other authenticators do their job). So it doesn't return any error, the authenticator is just skipped. I suppose you have no other authenticators and it fails with the default error when no one is executed.

I don't think we can return any error, as the authenticator is just skipped to allow other alternative ones to work. You have a warning message in the log that says the IdP is not found.

Closing as not not planned.

**Comment by NThobae** [comment]
Thank you for your detailed answer and explanation.
