### ISSUE TITLE
Quarkus JDBC postgres driver not found

### ISSUE THREAD

**Issue by eestein** [keycloak/keycloak#29605]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

It's already my third day researching and trying many things, but I can't get it to work.
I'm trying to build a keycloak image, but I'm always getting the following error:

Here's the `Dockerfile` (99% from docs):

```sh
FROM quay.io/keycloak/keycloak:latest as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server
RUN /opt/keycloak/bin/kc.sh build --db=postgres

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL="jdbc:postgresql://host.docker.internal/keycloak"
ENV KC_DB_USERNAME=admin
ENV KC_DB_PASSWORD=admin
ENV KC_HOSTNAME=localhost:8443
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

After building, I get this error:

> 2.820 ERROR: Failed to run 'build' command.
2.873 ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist
2.873 ERROR: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist
2.873 ERROR: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar
2.873 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command

After `--verbose`, this is the result:

> 2.868 ERROR: Failed to run 'build' command.
2.868 Error details:
2.868 java.lang.reflect.InvocationTargetException
2.868 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2.869 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2.869 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2.869 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2.869 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:90)
2.869 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:49)
2.869 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
2.869 	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:85)
2.869 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
2.869 	at picocli.CommandLine.access$1500(CommandLine.java:148)
2.869 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
2.869 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
2.869 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
2.869 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
2.869 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
2.869 	at picocli.CommandLine.execute(CommandLine.java:2170)
2.869 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:125)
2.869 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:98)
2.869 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2.869 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2.869 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2.869 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2.869 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
2.869 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
2.870 Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist
2.870 	at io.quarkus.bootstrap.app.CuratedApplication.createAugmentor(CuratedApplication.java:105)
2.870 	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
2.870 	... 24 more
2.870 Caused by: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist
2.870 	at io.quarkus.paths.PathTree.ofDirectoryOrArchive(PathTree.java:53)
2.870 	at io.quarkus.maven.dependency.ResolvedDependency.getContentTree(ResolvedDependency.java:47)
2.870 	at io.quarkus.maven.dependency.ResolvedDependency.getContentTree(ResolvedDependency.java:32)
2.870 	at io.quarkus.maven.dependency.ResolvedArtifactDependency.getContentTree(ResolvedArtifactDependency.java:66)
2.870 	at io.quarkus.bootstrap.app.CuratedApplication.processCpElement(CuratedApplication.java:170)
2.870 	at io.quarkus.bootstrap.app.CuratedApplication.getAugmentClassLoader(CuratedApplication.java:211)
2.871 	at io.quarkus.bootstrap.app.CuratedApplication.createAugmentor(CuratedApplication.java:102)
2.871 	... 25 more
2.871 Caused by: java.nio.file.NoSuchFileException: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar
2.871 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
2.871 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
2.871 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2.871 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
2.871 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
2.871 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
2.871 	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
2.871 	at io.quarkus.paths.PathTree.ofDirectoryOrArchive(PathTree.java:49)
2.871 	... 31 more

### Version

Latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Build to complete without errors

### Actual behavior

ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist

### How to Reproduce?

Run the provided Dockerfile in ubuntu:

`docker build --tag 'keycloak' .`

**Comment by shawkins** [comment]
That jar certainly is in the distribution. This example worked as expected with Podman. What version of docker are you using?

**Comment by eestein** [comment]
Hi, I don't doubt it, that's why I spent 3 days researching and testing everything before posting it here... I'm aware it should be something on my end, just can't say what if that's the case...

Docker version as requested:

![CleanShot 2024-05-17 at 10 54 55@2x](https://github.com/keycloak/keycloak/assets/2049255/5cfa0375-b44b-4f44-b3bc-845943012e52)

Please let me know if you need more info.

**Comment by ahus1** [comment]
IMHO you might have been tricked by an obsolete `:latest` image cached on your machine. Running the current image, it will already break when running `keytool`, as that is no longer included in the image. 

Try running with the `--pull` argument to ensure you are using the latest image:

```
docker build --pull --tag 'keycloak'
```

**Comment by ahus1** [comment]
Update: After I removed a surplus `>` from the Dockerfile, this now completes as expected on my machine.

**Comment by eestein** [comment]
@ahus1 I ran it with the command provided and it passes through the keytool line and throws the exact same error:

![CleanShot 2024-05-17 at 12 17 39@2x](https://github.com/keycloak/keycloak/assets/2049255/79ce05eb-d67c-4394-a440-14de04a08b89)


> 2.790 ERROR: Failed to run 'build' command.
2.793 ERROR: java.lang.IllegalArgumentException: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist
2.794 ERROR: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar does not exist
2.794 ERROR: /opt/keycloak/lib/lib/main/io.quarkus.quarkus-jdbc-postgresql-3.8.4.jar
2.794 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

**Comment by eestein** [comment]
Also, just to provide some extra information that might be helpful, this is a brand new VPS with an updated ubuntu. I've updated everything that was possible before installing docker and postgres. That was about 4 days ago.

**Comment by ahus1** [comment]
I previously ran it with Docker 24, now I tested it again with 26.1.3 (on Fedora 40) which should be very close to your setup. 

Both with the same results that it works. 

I can confirm that the hash `ff02...` is the most current one. You could add `--no-cache` to the parameters to ensure that all commands are re-run, but that shouldn't change the results.

Running out of ideas here, sorry.

**Comment by eestein** [comment]
@ahus1 thanks, I'm gonna try all you've said again after reinstalling the image. I appreciate your time, anyway.

**Comment by eestein** [comment]
I can't choose fedora, would you think any of these images would make a difference?

![CleanShot 2024-05-17 at 12 38 12@2x](https://github.com/keycloak/keycloak/assets/2049255/97671462-57c3-4aee-9786-025a0a3d8806)

**Comment by ahus1** [comment]
Sorry, I can't make any real recommendations here. I see you've been using Ubuntu 22 before, maybe Ubuntu 24 works better.

I've sometimes seen strange file access problems if people are running virus scanners that prevent access to JAR files. Could this be the case in your setup?

**Comment by eestein** [comment]
It should not, at **I** didn't install any software whatsoever. But I'm reinstalling the image now, anyway.

**Comment by eestein** [comment]
Ok, so here's what I did:

Reinstalled the image (using ubuntu 24.04)
![CleanShot 2024-05-17 at 12 59 27@2x](https://github.com/keycloak/keycloak/assets/2049255/608f61bd-0e4c-4858-abc5-39e21bbae392)

Updated all packages (apt-get update/upgrade)

Restarted the server

Created the same Dockerfile from the original message (commenting out the keytool section)
![CleanShot 2024-05-17 at 13 02 30@2x](https://github.com/keycloak/keycloak/assets/2049255/44e411f3-f743-4830-b1ed-0c13acd32eae)

Installed the default docker version in the ubuntu repo (apt-get install docker.io) - **New step**
![CleanShot 2024-05-17 at 13 07 18@2x](https://github.com/keycloak/keycloak/assets/2049255/19b04fc5-17ae-4747-b93c-f590bb56ac87)

Installed the recommended docker buildx (apt-get install docker-buildx) - **New step**

Ran `docker build --pull --tag 'keycloak' .`

And it worked...
I can only assume it was a problem with my docker installation.

@ahus1 thank you for your help, I'm leaving the steps here in case anyone else runs into the same problem.

**Comment by ahus1** [comment]
No worries, I'm happy to hear your got it working.
