### ISSUE TITLE
Disable management port for non-server commands

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#29601]
### Description

import / export and any additional commands that don't start the server, should not start the management port.

**Comment by shawkins** [comment]
This issue may not be needed if we proceed with https://github.com/keycloak/keycloak/issues/29200#issuecomment-2121169444

**Comment by shawkins** [comment]
Closing as not planned. The recommendation is to always shutdown the keycloak instances to run non-server commands - especially if on the same machine where there could be a port conflict.

**Comment by jirutka** [comment]
I’m sorry, but this is a breaking change and it doesn’t make sense to me – why do we have to stop Keycloak to just run `kc export`?
