### ISSUE TITLE
Terms and conditions disappear when changing language

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#29629]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

On the registration form (`register.ftl`), when changing the language after the form is loaded, the terms and conditions disappear. It shows up if you refresh and restart the login. 

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The terms and conditions should be shown as before, with the corresponding locale.

### Actual behavior

The terms and conditions disappear, as if they were not supposed to be displayed.

### How to Reproduce?

On a login page, click on "Register". 
On the registration form where terms and conditions should be displayed, select another language. 
The terms and conditions disappear.

**Comment by rmartinc** [comment]
I cannot reproduce this, in 24.0.4 changing between English and Spanish the terms and conditions remain in the page with no issues. What languages are you using?
