### ISSUE TITLE
Expose Authorization Server Metadata Endpoint under /.well-known/oauth-authorization-server to comply with rfc8414

### ISSUE THREAD

**Issue by francis-pouatcha** [keycloak/keycloak#29627]
### Description

For generic discovery of authorization server metadata as required in [OpenID for Verifiable Credential Issuance](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-11.2.3), expose an additional endpoint to read the auth server metadata.

- Current and only endpoint is: "/.well-known/openid-configuration"
- Additional endpoint shall be: "/.well-known/oauth-authorization-server" 

### Motivation

1. Compliance with [OpenID for Verifiable Credential Issuance](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-11.2.3)
2. Compliance with [RFC8414](https://www.rfc-editor.org/rfc/rfc8414.html#section-3)

### Details

- Add a new class org.keycloak.protocol.oauth2.OAuth2WellKnownProviderFactory as an extension of the class org.keycloak.protocol.oidc.OIDCWellKnownProviderFactory
- Register  org.keycloak.protocol.oauth2.OAuth2WellKnownProviderFactory with META-INF/services/org.keycloak.wellknown.WellKnownProviderFactory

**Comment by tnotheis** [comment]
@francis-pouatcha In your issue description you linked [RFC8414](https://www.rfc-editor.org/rfc/rfc8414.html#section-3), where it says that
> Authorization servers supporting metadata MUST make a JSON document containing metadata [...] available at a path formed by inserting a well-known URI string into the authorization server's issuer identifier **between the host component and the path component**, if any.

Note the part I highlighted in bold. According to this, the full path should look like this:
```
/.well-known/oauth-authorization-server/realms/<keycloak-realm>
```

But with the current implementation (Keycloak 26.0) it looks like this:
```
/realms/<keycloak-realm>/.well-known/oauth-authorization-server
```

Am I misinterpreting the RFC, or is the implementation incorrect?

**Comment by abhimoondra** [comment]
https://datatracker.ietf.org/doc/html/rfc8414#section-3.1

**Comment by heiko-braun** [comment]
@tnotheis I think you are right about this. I read the spec the same way
