### ISSUE TITLE
Bronken link on documentation for building admin-ui

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#29687]
### Description

On this section of the documentation about the admin-ui: https://github.com/keycloak/keycloak/tree/main/js/apps/admin-ui#building-as-a-keycloak-theme

there's link (https://github.com/keycloak/keycloak/blob/main/js/keycloak-theme/README.md) on how to build themes. 

This link is broken. Since building the admin-ui as a theme is not as straightforward as another theme, like login, it would be nice to have this better documented. Maybe the link was outdated anyway?

**Comment by huertin03** [comment]
Is this adressed?

**Comment by jonkoops** [comment]
The issue has not been closed, so I would say not. I'll mark this as a bug, feel free to take a look at it.
