### ISSUE TITLE
Should we restore SAML Servlet filter for Keycloak 25?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#29696]
### Description

This is to doublecheck if we need to restore this for KEycloak 25 and then possibly restore it. We may also try to deprecate this, so that we can remove it in Keycloak 26 release.

We removed it during the work on this https://github.com/keycloak/keycloak/issues/28786

**Comment by mposolda** [comment]
We won't restore SAML servlet filter as it was mentioned in the release notes https://www.keycloak.org/docs/24.0.4/release_notes/#java-adapter-deprecation-and-removal that "The only adapter we will continue to deliver is the SAML adapter for latest releases of WildFly and EAP 8.x."

There's also https://www.keycloak.org/2023/03/adapter-deprecation-update.html that also states only WF/EAP SAML will be kept.

**Comment by jellisgwn** [comment]
Please consider revisiting this decision. The SAML adapter is unable to to support the flexible multi-tenant external configuration that the Servlet Filter provides.

**Comment by mposolda** [comment]
@jellisgwn Thanks for the feedback. Right now, we still prefer to not have SAML Servlet filter as we don't have capacity to properly maintain it. The SAML is still possible to be used with the use of SAML Elytron adapter https://docs.wildfly.org/32/WildFly_Elytron_Security.html#Keycloak_SAML_Integration . If some capabilities (like EG. multitenancy support) are missing, it worth to start a ticket and maybe contribute this to Wildfly Elytron (or also Keycloak if needed as Wildfly elytron is using Keycloak under the covers to have this capability available.

**Comment by jellisgwn** [comment]
@mposolda from the link you provided: 

> To secure applications deployed to WildFly using Keycloak SAML, a Galleon feature pack provided by the Keycloak project needs to be used. 

where is the keycloak project hosted?
