### ISSUE TITLE
The HD parameter in Google IdP can't be a separated coma list

### ISSUE THREAD

**Issue by gillg** [keycloak/keycloak#29712]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

The tooltip of the hd parameters says : 
> Comma ',' separated list of domains is supported. (introduced in https://github.com/keycloak/keycloak/pull/16762)

But even if the logic to validate the claim is correct, the request to Google is wrong.
The hd parameter in query only supports one domain or a wildcard.

Line in error: https://github.com/keycloak/keycloak/blob/b7a2c2a8344fbb7123cdced1a94b9b397473d104/services/src/main/java/org/keycloak/social/google/GoogleIdentityProvider.java#L101
The result is the fact the end user can't reuse its connected accounts and have to fully reconnect to google.

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

In case of comma separated list, I would force * in the hd query parameter. The real security will be done at claim check level, right after.

### Actual behavior

In case of comma separated list, the user is confused and have to reconnect to google.

### How to Reproduce?

Use a google workspace or cloud identity and set a coma separated list in "Hosted Domain" for a google IdP.

**Comment by gillg** [comment]
Example of workaround with expected behaviour
![image](https://github.com/keycloak/keycloak/assets/5639241/a627a797-2108-45b6-a48c-04337b267b3c)

**Comment by jonkoops** [comment]
I am re-opening this issue as a fix for it is up under #32141
