### ISSUE TITLE
The generated token by custom SignatureProvider can not be verified

### ISSUE THREAD

**Issue by yfann** [keycloak/keycloak#29728]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I need to extend the token signature algorithm by creating a custom SignatureProvider.

![image](https://github.com/keycloak/keycloak/assets/1673115/c97acf86-e089-437a-a5da-8dde4321391d)
So far it's good and a new signature algorithm "testAlgorithm" has been created.

And I use the API({{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/token) to get the token.
![image](https://github.com/keycloak/keycloak/assets/1673115/6500153c-2902-4b91-8c08-594f32d947fd)
It still works as expected.

Then I use {{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/token/introspect to verify the token.
Then get the response
`{
    "active": false
}`

The underlying exception is "Cannot deserialize value of type `org.keycloak.jose.jws.Algorithm` from String "testAlgorithm": not one of the values accepted for Enum class: [ES384, HS384, ES256, HS256, HS512, PS384, RS384, PS256, RS256, EdDSA, RS512, none, Ed448, Ed25519, ES512, PS512]"

It seems the custom testAlgorithm is not in the enum list when the token is deserialized to JWSHeader.

Could my custom signature algorithm be added to this enum by extension like SPI? Or I use the provider in the wrong way.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

The generated token by custom signature can be verified by {{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/token/introspect 

### Actual behavior

{{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/token/introspect returns
`{
    "active": false
}`

verify failed

### How to Reproduce?

MySignatureProvider.java
`package mysignature;

import org.keycloak.common.VerificationException;
import org.keycloak.crypto.*;
import org.keycloak.models.KeycloakSession;

public class MySignatureProvider implements SignatureProvider {

    public SignatureSignerContext signer() throws SignatureException {
        return new MySignerContext();
    }

    public SignatureSignerContext signer(KeyWrapper key) throws SignatureException {
        return new MySignerContext();
    }

    public SignatureVerifierContext verifier(String kid) throws VerificationException {
        return new MySignatureVerifierContext();
    }

    public SignatureVerifierContext verifier(KeyWrapper key) throws VerificationException {
        return new MySignatureVerifierContext();
    }

    public boolean isAsymmetricAlgorithm() {
        return true;
    }
}
`

MySignatureProviderFactory.java
`
package mysignature;

import org.keycloak.crypto.SignatureProvider;
import org.keycloak.crypto.SignatureProviderFactory;
import org.keycloak.models.KeycloakSession;

public class MySignatureProviderFactory implements SignatureProviderFactory{
    public static final String ID = "testAlgorithm";

    public String getId() {
        return ID;
    }

    public SignatureProvider create(KeycloakSession session) {
        return new MySignatureProvider();
    }
}
`

MySignatureVerifierContext.java
`package mysignature;

import org.keycloak.common.VerificationException;
import org.keycloak.crypto.SignatureException;
import org.keycloak.crypto.SignatureVerifierContext;

public class MySignatureVerifierContext implements SignatureVerifierContext {

    public String getKid() {
        return "mykey";
    }

    public String getAlgorithm() {
        return "testAlgorithm";
    }

    public boolean verify(byte[] data, byte[] signature) throws VerificationException {
        try {
            System.out.println("Verify data: "+new String(data));
            System.out.println("Verify data: "+new String(signature));
            return true;
        } catch (Exception e) {
            throw new VerificationException("verifiy failed", e);
        }
    }
}
`

MySignerContext.java
`package mysignature;

import org.keycloak.crypto.SignatureException;
import org.keycloak.crypto.SignatureSignerContext;

public class MySignerContext implements SignatureSignerContext {

    public String getKid() {
        return "mykey";
    }

    public String getAlgorithm() {
        return "testAlgorithm";
    }

    public String getHashAlgorithm() {
        return "SHA-256";
    }

    public byte[] sign(byte[] data) throws SignatureException {
        try {
            System.out.println("MySignerContext sign: "+new String(data));
            return data;
        } catch (Exception e) {
            throw new SignatureException("Signing failed", e);
        }
    }
}
`

Here is the source code for my custom signature.

**Comment by rmartinc** [comment]
Hi @yfann!

The `SignatureProvider` is inside the sub-project `server-spi-private` so it's a private class that it's not thought to be extended. What is the complete exception you are getting?

**Comment by yfann** [comment]
Hi @rmartinc 

I try to add a new algorithm for signature so I extend the SignatureProvider. And there is no problem to generate a signed token with the new algorithm. But when to verify the token it throws an exception:

2024-06-11 21:43:04,693 WARN  [org.keycloak.events] (executor-thread-15) type="INTROSPECT_TOKEN_ERROR", realmId="35d9ae74-4f1d-462f-a3af-38f0b4cfd9b1", clientId="myclient_test", userId="null", ipAddress="0:0:0:0:0:0:0:1", error="token_introspection_failed", reason="Access token JWT check failed", client_auth_method="client-secret"

I found the underlying exception is：

Cannot deserialize value of type `org.keycloak.jose.jws.Algorithm` from String "testAlgorithm": not one of the values accepted for Enum class: [ES384, HS384, ES256, HS256, HS512, PS384, RS384, PS256, RS256, EdDSA, RS512, none, Ed448, Ed25519, ES512, PS512]

Is it possible to add a new algorithm for signature using available SPI?

**Comment by mposolda** [comment]
@yfann This is very low priority as adding custom algorithm is kind of private SPI as mentioned by @rmartinc . We can possibly accept PR for make this more easily possible to extend, but Keycloak team itself probably won't prioritize it.

**Comment by Yfannnnnnnnn** [comment]
@mposolda @rmartinc thank you for the clarification. I can overwrite an existing algorithm as a workaround so far. So we can close this issue since it is low priority.

**Comment by yfann** [comment]
@mposolda @rmartinc thank you for the clarification. I can overwrite an existing algorithm as a workaround so far. So we can close this issue since it is low priority.
