### ISSUE TITLE
Admin UI stuck in loading screen when changing proxy settings to forwarded header

### ISSUE THREAD

**Issue by seekermarcel** [keycloak/keycloak#29734]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We are running Keycloak in a Kubernetes Cluster together with an Istio Mesh

In 24.0.0 the proxy option for edge was deprecated. Using the forwarded option the Admin UI is stuck in Loading screen due to a 403 response from the keycloak server.
Setting the proxy option to xforwarded keeps the Admin UI accessable however it breaks the realm-operator:

```
FAILED check if keycloak is available : error performing ping request: Get http://keycloak-service/auth/admin/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
```

The docu mentions to convert all forwarded/xforwarded headers as part of the proxy. However as far as I saw there are no forwarded or xforwarded headers in the admin ui requests.

The problem is somewhere in the headers but I can't find it.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The Admin UI is accessable no matter what proxy option I choose.

### Actual behavior

The Admin UI is only accessable with xforwarded proxy option.
If set to forwarded a 403 response from the server blocks the UI

### How to Reproduce?

Deploy Keycloak 24.0.0 in Kubernetes Cluster with Istio Mesh for communication.
Set Proxy option for keycloak to forwarded/xforwarded.
Try to access the Admin UI.

### Anything else?

https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option

**Comment by shawkins** [comment]
> The docu mentions to convert all forwarded/xforwarded headers as part of the proxy. However as far as I saw there are no forwarded or xforwarded headers in the admin ui requests.

The request from the proxy to keycloak should contain the necessary headers. A quick glance at the istio docs looks like it largely uses the x-forwarded headers. Can you double check how istio is configured to make sure it populates those?

**Comment by seekermarcel** [comment]
I'm sorry I need some time to check on that

**Comment by seekermarcel** [comment]
@shawkins now I'm sure it's not a problem of istio but one of keycloak itself. I looked trough our istio and also tested keycloak without istio in between the connections - same problem.

There is either a bug or a misconfiguration on our side that prohibits the connection to the admin ui when the proxy forwarded option is set

**Comment by shawkins** [comment]
@seekermarcel please provide all of the http(s) and hostname configuration that you are using.
