### ISSUE TITLE
Unable to login to Keycloak Admin Console when Keycloak is behind NGINX proxy which has "session-cookie-name" annotation

### ISSUE THREAD

**Issue by Swasthik-S-Nettar** [keycloak/keycloak#29741]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

We have Keycloak 24 deployed behind NGINX proxy in a K8s Environment. The NGNIX proxy has the following annotation
 1. nginx.ingress.kubernetes.io/affinity: "cookie" 
 2. nginx.ingress.kubernetes.io/session-cookie-name: "AUTH_SESSION_ID".

After Keycloak has come up ,we can see login screen for Admin GUI. But after entering user name and password in browser we see the following error:-
`ERR_TOO_MANY_REDIRECTS`

### Version

24

### Regression

- [X] The issue is a regression

### Expected behavior

After the credentials for user login is entered, it should take me to Keycloak Admin Console.

### Actual behavior

After the credentials for user login is entered, the browser shows the following error message:-
`This page isn’t working <ip-address of edge_node>  redirected you too many times.
[Try deleting your cookies](https://support.google.com/chrome?p=rl_error&hl=en-GB).
ERR_TOO_MANY_REDIRECTS`

### How to Reproduce?

Deploy Keycloak behind an NGINX proxy with the following annotation added in the ingress resource
 1. nginx.ingress.kubernetes.io/affinity: "cookie" 
 2. nginx.ingress.kubernetes.io/session-cookie-name: "AUTH_SESSION_ID".
 
 Once Keycloak is up , and user credentials are entered, the browser would show the `ERR_TOO_MANY_REDIRECT`

**Comment by raff897** [comment]
Have you set --proxy edge?
I thing that your nginx communicate in http with keycloak while use http from external.  In this case you must set as proxy mode edge.
This is the official documentation. 
https://www.keycloak.org/server/reverseproxy

**Comment by Swasthik-S-Nettar** [comment]
@raff897 
The proxy mode that we use is reecnrypt and both our frontend and backend communicate with each other over HTTPS.
Furthermore, according to Keycloak 24, we no more use the --proxy (KC_PROXY environment variable) instead use proxy-headers, "xforwarded" in our case.

As from this configuration https://www.keycloak.org/server/all-config#category-proxy  which indicates that "--proxy-headers" will take precedence over --proxy(which is going to be deprecated). Hence we used the --proxy-headers option
