### ISSUE TITLE
Support AES and HMAC Key-Imports for the JavaKeystoreKeyProvider

### ISSUE THREAD

**Issue by francis-pouatcha** [keycloak/keycloak#29755]
### Description

Current implementation only supports RSA and ECDSA key import.

For the purpose of managing keys externally and across servers, symetric keys shall be imported through the JavaKeystoreKeyProvider.
 

### Motivation

Simplify key management and key rotation, including the sharing and rotation of symmetric keys.

### Details

Identical to the extension of JavaKeystoreKeyProvider with ECDSA import capability.

See: #26936

**Comment by francis-pouatcha** [comment]
Can a code owner please label this as block by state of implementation of java keystores?

**Comment by rmartinc** [comment]
@francis-pouatcha AFAIK the pkcs12 provider can have all the needed secret keys. Example:

```
keytool -genseckey -alias hs512 -keyalg HmacSHA512 -keysize 1024 -keystore test.p12 -storetype pkcs12 -keypass password -storepass password
keytool -genseckey -alias aes -keyalg AES -keysize 128 -keystore test.p12 -storetype pkcs12 -keypass password -storepass password
keytool -genkey -keyalg RSA -alias rs256 -keystore test.p12 -keysize 2048 -dname "CN=demo" -keypass password -storepass password
keytool -genkey -keyalg RSA -alias rsa-oaep -keystore test.p12 -keysize 2048 -dname "CN=demo" -keypass password -storepass password
```

I'm resurrecting this issue as we need to externalize all the keys in a java keystore.
