### ISSUE TITLE
MigrateTo25_0_0 does not complete within default transaction timeout

### ISSUE THREAD

**Issue by cwelch-rh** [keycloak/keycloak#29756]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

The realm migration iterates over each client regardless if it already has a 'basic' scope. It had completed at least once in the past, but won't anymore, which is leaving our clients in an inconsistent state (some have a 'basic' scope, some don't).

### Version

Nightly

### Regression

- [x] The issue is a regression

### Expected behavior

Realm migration completes within the transaction timeout. It might also work if we could skip MigrateTo25_0_0 and do the migration ourselves some other way.

### Actual behavior

Realm migration is attempted, but never completes due to Arjuna transaction reaping, which causes containers to fail to start.

> 2024-04-30 14:30:41,609 DEBUG [org.keycloak.storage.datastore.DefaultMigrationManager] (main) Migrating older model to 24.0.3
> 2024-04-30 14:30:45,035 DEBUG [org.keycloak.storage.datastore.DefaultMigrationManager] (main) Migrating older model to 25.0.0
> 2024-04-30 14:35:41,435 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check processing TX 0:ffffac2800c8:836f:66310089:7 in state  RUN
> 2024-04-30 14:35:41,436 INFO  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012404: Action id 0:ffffac2800c8:836f:66310089:7 - thread main at time 14:33:41.437 had stackTrace

### How to Reproduce?

Run Keycloak 24 against a persistent DB
Create ~2500 clients
Run nightly against same DB

**Comment by nfornaciari97** [comment]
Hi everyone!
I have the same issue upgrading from 22.0.5 to 26.0.7; I get "Migrating older model to 25.0.0" and then after a couple minutes the pod get restarted with the error reported.
I have already read the linked pull request #29823 opened by @mposolda  but I don't get what I have to do to fix the error.
As far as I understand, the migration shouldn't fail ora get stuck as described here even if I may have some client already possesing basic scope.
Am I missing something?

**Comment by ahus1** [comment]
@nfornaciari97 - You are commenting on an issue that is long closed. Please have a look if an existing open issue is a fit (maybe #35261), or open a new issue. 

AFAIK `quarkus.transaction-manager.default-transaction-timeout` should be the setting as described in https://www.n-k.de/2023/09/keycloak-tuning-database-settings-transactions.html - unfortunately there is no official setting.
