### ISSUE TITLE
Require external Infinispan be of version 15 or greater

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#29750]
### Description

There are some differences in the behavior of Infinispan 15 that we depend on to ensure entries in the remote site are removed. We also don't test version 14 of Infinispan any more.

Therefore the migration guide should state that users should upgrade to ISPN 15. This also needs to be part of the [building blocks](https://www.keycloak.org/high-availability/bblocks-active-passive-sync) and [the blueprint](https://www.keycloak.org/high-availability/deploy-infinispan-kubernetes-crossdc). 

### Discussion

https://github.com/keycloak/keycloak-benchmark/pull/823#issuecomment-2122787262

### Motivation

The behavior of Infinispan changed across major versions and we depend on it, plus we want to keep the support matrix small.

**Comment by ahus1** [comment]
It would be nice if keycloak could check at startup if the remote infinispan is compatible and throw an exception if it is 14

**Comment by ryanemerson** [comment]
It's not currently possible to get the server version via the Hot Rod client, but I have created [ISPN-16110](https://issues.redhat.com/browse/ISPN-16110) to address this in 15.0.5.Final
