### ISSUE TITLE
431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by mberbar** [keycloak/keycloak#29770]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

During a migration from Keycloak 9 to Keycloak 24.0.3, I am facing error 431 when calling the route /account. This is because the token and cookies are larger in size. Upon comparing the two versions, I found that the old version had no limit on header size and did not return cookies, whereas the new version has a limit and returns cookies. I tried adding various combinations of these properties to file conf\quarkus.properties, but nothing works:

quarkus.http.limits.max-header-size=100K
quarkus.management.limits.max-header-size=100K
quarkus.http.limits.max-header-list-size=100000
quarkus.management.limits.max-header-list-size=100000
quarkus.http.limits.max-chunk-size=100K
quarkus.management.limits.max-chunk-size=100K
quarkus.http.limits.max-initial-line-length=100000
quarkus.management.limits.max-initial-line-length=100000
quarkus.http.http2=false
quarkus.http.limits.max-header-size=100K
quarkus.http.limits.max-initial-line-length=10240
quarkus.http.limits.max-body-size=10485760

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

I accept either having no limit on the header size or getting the properties I mentioned to work.

### Actual behavior

When I log in, everything works fine, but when I refresh, the /account request returns error 431 because the pre-existing cookies, along with the cookies in the header, make the size of the header too large. I tested the request in Postman and found that if I clear the cookies after each call, I get a response. However, if I leave the cookies after the first successful call, the second call results in error 431.

### How to Reproduce?

For example, calling the route /auth/realms/{realm-id}/account twice in a row with a header size of 9348 B in postman.

**Comment by shawkins** [comment]
@mberbar keycloak is already bumping several values https://github.com/keycloak/keycloak/blob/1cf87407feaf79a5a0081b25d53863d8df83ec58/quarkus/runtime/src/main/resources/META-INF/services/quarkus.properties#L28

Do you get a log about this on the server - it may need debug logging enabled.

**Comment by shawkins** [comment]
@mberbar I cannot reproduce the behavior you are describing. On both main and 24.0.3, I do not hit the 431 response until I exceed the 65535 max header size. Can you provide a more complete reproducer?

**Comment by mberbar** [comment]
> @mberbar I cannot reproduce the behavior you are describing. On both main and 24.0.3, I do not hit the 431 response until I exceed the 65535 max header size. Can you provide a more complete reproducer?

I solved my problem. Thank you for your time. When I attempted to create a reproducer, I discovered that my Angular proxy was causing the 431 error. I hadn't realized that I was using the wrong port.
