### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#29771]
Currently, when some invalid request lands and it results by throwing exception (e.g. `ModelValidationException`), it's returned generic error response without any details:

```
{
    "error": "unknown_error",
    "error_description": "For more on this error consult the server log at the debug level."
}
```

which is then propagated to UI:

![Image](https://github.com/keycloak/keycloak/assets/1897897/e89b949e-7fa2-4ad5-9789-9ab3a7e0e4a4)

**Comment by pedroigor** [comment]
Messages fixed in https://github.com/keycloak/keycloak/pull/29643.
