### ISSUE TITLE
Community keycloak-saml-adapter-galleon-pack shouldn't require to be resolved from channel

### ISSUE THREAD

**Issue by jfdenise** [keycloak/keycloak#29773]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

The WildFly Galleon feature-pack keycloak-saml-adapter-galleon-pack requires to be resolved from channel. That is WildFly specific. This constraint should only be applied when building the feature-pack for EAP.
This configuration item: https://github.com/keycloak/keycloak/blob/main/distribution/galleon-feature-packs/saml-adapter-galleon-pack/pom.xml#L244
Should be moved to https://github.com/keycloak/keycloak/blob/main/distribution/galleon-feature-packs/saml-adapter-galleon-pack/pom.xml#L291

### Version

24.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The feature-pack should not be required to be resolved from the channel.

### Actual behavior

The feature-pack is required to be resolved from the channel.

### How to Reproduce?

Use the WildFly Maven Plugin, configure a WildFly channel, add WildFly feature-pack and the keycloak-saml-adapter-galleon-pack, the plugin execution will fail.

**Comment by mposolda** [comment]
Already resolved by linked PR and will be available in Keycloak 25
