### ISSUE TITLE
Hibernate statistics logging stopped working after upgrade to Quarkus

### ISSUE THREAD

**Issue by cwelch-rh** [keycloak/keycloak#29786]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Java System properties `hibernate.generate_statistics` and `hibernate.session.events.log` are no longer picked up in the Quarkus distribution. 

### Version

Nightly

### Regression

- [X] The issue is a regression

### Expected behavior

Hibernate statistics are collected and logged when those system properties are set to `true`

### Actual behavior

No hibernate statistics are logged.

### How to Reproduce?

Download / build Keycloak Quarkus distribution
export JAVA_OPTS_APPEND="-Dhibernate.generate_statistics=true -Dhibernate.session.events.log=true"
kc.sh start-dev

Should see that no StatisticalLoggingSessionEventListener entries are in the logs. The queries at startup should be enough to cause a few entries to be logged.

### Anything else?

I think https://github.com/keycloak/keycloak/issues/19427 would have provided a way to enable it again, but it looks like it got pushed to 26.

**Comment by shawkins** [comment]
As far as I can tell you can get session stat logging with just: --log-level-org.hibernate.session.metrics=debug

All of the persistence.xml or even the new orm build time options are not needed.
