### ISSUE TITLE
"parentGroup" is null error with LDAP

### ISSUE THREAD

**Issue by jeffgus** [keycloak/keycloak#29797]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Group layout is this:
/applications/testapp/admins
/applications/testapp/users
/customers/acme

A user can be added to any of these groups without issue if the group is not backed by LDAP. If I attached these groups to LDAP, the user can be added to the one group at first, but any additional groups triggers this error:

```
dev-sso-0 keycloak 2024-05-22 23:14:33,367 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-81) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.GroupModel.getName()" because "parentGroup" is null
dev-sso-0 keycloak 	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.getHighestPredecessorNotExistentInLdap(GroupLDAPStorageMapper.java:549)
dev-sso-0 keycloak 	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.getHighestPredecessorNotExistentInLdap(GroupLDAPStorageMapper.java:555)
dev-sso-0 keycloak 	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper.addGroupMappingInLDAP(GroupLDAPStorageMapper.java:588)
dev-sso-0 keycloak 	at org.keycloak.storage.ldap.mappers.membership.group.GroupLDAPStorageMapper$LDAPGroupMappingsUserDelegate.joinGroup(GroupLDAPStorageMapper.java:718)
dev-sso-0 keycloak 	at org.keycloak.models.cache.infinispan.UserAdapter.joinGroup(UserAdapter.java:422)
dev-sso-0 keycloak 	at org.keycloak.services.resources.admin.UserResource.joinGroup(UserResource.java:1026)
dev-sso-0 keycloak 	at org.keycloak.services.resources.admin.UserResource$quarkusrestinvoker$joinGroup_0f1a9c6748fb254fb63d061c5ef823fe7906a7dc.invoke(Unknown Source)
dev-sso-0 keycloak 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
dev-sso-0 keycloak 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
dev-sso-0 keycloak 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
dev-sso-0 keycloak 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
dev-sso-0 keycloak 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
dev-sso-0 keycloak 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
dev-sso-0 keycloak 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
dev-sso-0 keycloak 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
dev-sso-0 keycloak 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
dev-sso-0 keycloak 	at java.base/java.lang.Thread.run(Thread.java:840)
```

I tried tweaking the LDAP group mapper to only point to a subgroup (e.g. /applications/testapp vs /applications) because I first thought there was an issue with nesting groups in LDAP. I deleted all the groups and started over and re-pointed the group mapper to a specific sub-group in LDAP and the subgroup in Keycloak. This didn't fix the issue. The initial group syncs without issue (add/remove users). Group sync (no users) is working.

I created a new realm without any LDAP and was able to build out the groups without an issue. It is only when I try to back the groups to LDAP does Keycloak start to behave badly. 

The LDAP server I'm testing against is 389 Directory Server, running in a pod (for now). I'm using quay.io/389ds/dirsrv:c9s

If I tweak the group mapper, I can get the users sync'd to the first group, but if I click on the other group (/customers/acme), the users will appear, but Keycloak will show the FIRST group (e.g. /applications/testapp/admin) in the Membership column. Very strange!

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The groups should be populated by users in a specific ldap mapper to a specific subgroup in Keycloak. 

### Actual behavior

Keycloak -> LDAP throws an error. LDAP -> Keycloak cause Keycloak to put users in only one group, not matter what groups the user appears in LDAP.

### How to Reproduce?

Create two ou's:
ou=customers
ou=applications

Put groups in the ou's:
cn=testapp,ou=applications
cn=admin,cn=testapp,ou=applications
cn=users,cn=testapp,ou=applications
cn=acme,ou=customers

Add users to groups (either LDAP or via Keycloak). Try to sync.

Create LDAP mappers for each of these groups and point to /applications and /customers in Keycloak. Odd behavior when Keycloak tries to sync users with the groups.

**Comment by sguilhen** [comment]
Yeah, this one also falls under the "issues with group mapper" umbrella. In short, the proxied User that is created by each mapper doesn't check if the group being joined "belongs" to the mapper - i.e. is a subgroup of the mapper's group path - and tries to add the membership anyway. So, when having multiple mappers, the first mapper used by Keycloak (and the order doesn't seem to be deterministic) will always attempt to process the `joinGroup` operation, even when it is not one it should attempt.

Instead, the `joinGroup` implementation should check first if the group being joined belongs to the configured group path, and if not it should delegate to the next proxied user.

**Comment by jeffgus** [comment]
Would the temporary work around be to use only one mapper and put all groups, subgroups there? 

The issue I have with that approach is that it records that one group is a subgroup as an attribute (member, memberOf). That's fine, but it doesn't put it as a branch in the LDAP tree.

**Comment by sguilhen** [comment]
Hi @jeffgus, I believe that it is a valid workaround. The group mapper was initially designed to be a single mapper in the config, but then the concept of group path was introduced, which should in theory enable more than one mapper. However, the implementation of this concept is missing some important bits that causes one mapper to interfere with another. 

We are aware of these problems, and we even started https://github.com/keycloak/keycloak/issues/20966 to keep track of the group mapper issues. We will probably start working on some of these issues soon as the amount of users affected and issues reported in this area is quite significant already.

**Comment by sguilhen** [comment]
Ah, yes, the linked "umbrella" issue is not yet updated with all the relevant issues in this area, it was created some time ago but we still need to update it to include every reported issue.

By the way, I believe your issue is similar to https://github.com/keycloak/keycloak/issues/17593 - the reporter there is using MSAD, but the issue seems to be the same - the wrong mapper is chosen when joining a group. If that is true, would you mind if I close this one as a duplicate and reference it in the other issue?

**Comment by jeffgus** [comment]
It appears that #17593 is what I am seeing, but with 389 Dir. I didn't notice that the AD issue is the same as this issue. I will close this issue.
