### ISSUE TITLE
Fix the keycloak examples inside keycloak pod

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#29807]
### Description

Once I sh into keycloak pod and redirect to the /opt/keycloak/bin to run the kcadm.sh file to get my realm information
I need to do the credentials config. For this when I run the ./kcadm.sh config credentials In the examples its give to use  _--server http://localhost:8080/auth_, but in new keycloak /auth is not there anymore. Can you team change the examples here.

![image](https://github.com/keycloak/keycloak/assets/48629246/fa5a7217-2a1a-4e56-b1c0-a334b96d426a)
when using /auth
![image](https://github.com/keycloak/keycloak/assets/48629246/36af758e-c12e-4e07-bd4c-92e764dc1c05)
without /auth
example section:
![image](https://github.com/keycloak/keycloak/assets/48629246/b2cafd14-3ab0-415a-b87e-9b565b31a002)

**Comment by ahus1** [comment]
This has been fixed in Keycloak 25, possibly by issue #28329

In the future, please open any bug you find as a bug, and it will be handled using our bug handling process in a more timely manner.
