### ISSUE TITLE
Facing issue while exporting realm file in keycloak

### ISSUE THREAD

**Issue by kanchantambe** [keycloak/keycloak#29836]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Trying to export realm file from below link given on keycloak site.

https://www.keycloak.org/server/importExport#:~:text=To%20export%20a%20realm%2C%20you,started%20when%20invoking%20this%20command.&text=To%20export%20a%20realm%20to,%2D%2Ddir%20option.&text=When%20exporting%20realms%20to%20a,for%20each%20realm%20being%20exported

Getting below error,

keycloak@e78:/opt/bitnami/keycloak/bin$ kc.sh export --file D:\checkRealm.json
Appending additional Java properties to JAVA_OPTS: ‘-Djdk.security.allowNonCaAnchor=true’
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:744]

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Realm should export successfully with this command bin/kc.[sh|bat] export --dir <dir>

### Actual behavior

Getting below error,

keycloak@e78:/opt/bitnami/keycloak/bin$ kc.sh export --file D:\checkRealm.json
Appending additional Java properties to JAVA_OPTS: ‘-Djdk.security.allowNonCaAnchor=true’
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:744]

### How to Reproduce?

Exporting a Realm to a Directory:
To export a realm, you can use the export command. Your Keycloak server instance must not be started when invoking this command.

bin/kc.[sh|bat] export --dir <dir>

When exporting realms to a directory, the server is going to create separate files for each realm being exported.

**Comment by shawkins** [comment]
@kanchantambe the DEBUG env variable is likely set and you also have something else running, namely a keycloak server that is also using that port. It is recommended that you shut down the running server before performing an export.

**Comment by shawkins** [comment]
~priority-low
