### ISSUE TITLE
Automating User and Role Management with Keycloak APIs

### ISSUE THREAD

**Issue by goutham1012** [keycloak/keycloak#29900]
### Description

Hi Team,

I have a request to create a user, role, group, group membership, and mapper using Keycloak APIs.

1. Before creating users, we need to obtain a token. Once it is obtained successfully, we can proceed to create users.?
2. Could you please provide any REST API code that would be helpful for this task?

Thanks,
Goutham.K

**Comment by goutham1012** [comment]
Can someone provide an update on above query? Or else guide me is this right platform to ask the query?

**Comment by sschu** [comment]
The Keycloak Admin API is a REST API. You can see the admin API in action by looking at the network tab when using the admin console. The admin api documentation is here https://www.keycloak.org/docs-api/latest/rest-api/index.html. The admin-cli might be useful if you need to script your setup: https://www.keycloak.org/docs-api/latest/rest-api/index.html
