### ISSUE TITLE
browsing and linking subgroups

### ISSUE THREAD

**Issue by truijllo** [keycloak/keycloak#29969]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

Starting with v20 and up (I currently have a docker container running the latest), the admin user interface started to exhibit odd behavior.

I have a group called "labs" in my realm, and it has multiple subgroups.

I have the first-level group list on the Groups page, but when I click on the left of the "labs" label, an arrow opens to reveal the subtree, before that the arrow is hidden.

* Group page, click in this area
![kc_group_0b](https://github.com/keycloak/keycloak/assets/908143/e0203bc8-dead-4b6e-b71b-3dd7897615ab)

* Et voila' ! The arrow appears
![kc_group_1](https://github.com/keycloak/keycloak/assets/908143/f6e5cdb0-c2ad-4ade-8c8c-07667361a73a)
![kc_group_2](https://github.com/keycloak/keycloak/assets/908143/1384eb52-21df-4a54-ae76-fb799e9b8935)

Instead, the arrow next to the "labs" group is not visible when I try to join a user to a subtree on the User page. As a result, I must know the exact name to search. After the search there's an item with the arrow...

* In users, join to groups, no arrows are shown
![bug_keycloak_X_b](https://github.com/keycloak/keycloak/assets/908143/e91ea049-002f-442c-8d1e-1b9f9d0b0150)

* after the search
![bug_keycloak_interface_b](https://github.com/keycloak/keycloak/assets/908143/80e0693c-8597-4f92-915d-bc6c57b5ca1d)

### Version

24.0.4-0

### Regression

- [ ] The issue is a regression

### Expected behavior

there should always be an "arrow" near the subtree labels to make the subtree browsable or to make it clear that the specific label represents a parent of the subtrees

### Actual behavior

In "Groups", near the parent of a subtree the arrows don't appear unless you click in the area
![kc_group_0b](https://github.com/keycloak/keycloak/assets/908143/e0203bc8-dead-4b6e-b71b-3dd7897615ab)
![kc_group_1](https://github.com/keycloak/keycloak/assets/908143/f6e5cdb0-c2ad-4ade-8c8c-07667361a73a)

* In "Users", join to groups, no arrows are shown
![bug_keycloak_X_b](https://github.com/keycloak/keycloak/assets/908143/e91ea049-002f-442c-8d1e-1b9f9d0b0150)

* after the search
![bug_keycloak_interface_b](https://github.com/keycloak/keycloak/assets/908143/80e0693c-8597-4f92-915d-bc6c57b5ca1d)

### How to Reproduce?

A valid structure is needed so:

To test the  behaviour in the "Group" page:
- create a parent group "lab" ( i.e. ), inside this group create children groups ( i.e. lab1, lab2 )

To test the  behaviour in the "Users" page ( after created the group structure ):
- add new user
- join group
- try to add in a subgroup

tested with latest Chrome and Firefox on Linux.

### Anything else?

Up to v19 there wasn't this problem, This is present since v20 with the new interface.

**Comment by edewit** [comment]
You don't have to click the area in front of the group in the tree to have the arrow appear. This is because the subgroups are only fetched once the group is selected this is to make the groups tree more usable when there is a large number of groups 
All the other points have been fixed in the most recent version.

~old-release

**Comment by edewit** [comment]
I made it so that the `>` icon shows up based on whether the group has subgroups instead only on selecting it in #29996
