### ISSUE TITLE
The "update-email" feature updates the email in the user profile, but users can still log in with the old email

### ISSUE THREAD

**Issue by alispustina** [keycloak/keycloak#29962]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When the "update-email" feature is used, the user can successfully change their email address. 
However, the user is still able to log in using the old email address. We are facing this issue with the "Email as Username" option being enabled. Additionally, when searching the user list in the admin-cli, an entry with the old username appears, even though it does not match the username displayed in the full user profile.

We have tried enabling/disabling the "Edit username" option.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should not be able to login with his old email/username. 
We shouldn't get any results when searching the user list with the user's old email address.

### Actual behavior

The user is able to login with his old email/username. 
We are getting a result when searching the user list with the user's old email address.

### How to Reproduce?

1. Start Keycloak with KC_FEATURES=update-email
2. Configure the realm with "Email as Username"
3. Create a user
4. Send the "update email" required action email to the user.
5. Follow the step in the email to update & confirm the user's email address
6. Try to login with the old email address
7. Search in the admin cli user list by the user's old email address

**Comment by alispustina** [comment]
On another note, this behavior was due to the user update we performed through the API.

**Comment by martin-kanis** [comment]
@alispustina Thanks for reporting this. I tried with Keycloak 25, following your instructions, I'm not able to log in with old email after I updated it. If you are able to reproduce it with Keycloak 25, please provide exact steps how to do it. Thanks.

**Comment by alispustina** [comment]
Hello @martin-kanis,

I just tried it out and I'm still able to reproduce with Keycloak V.25.

Steps to reproduce: 

1. Start Keycloak with KC_FEATURES=update-email
2. Configure the realm with "Email as Username" enabled
3. Create a new user
4. Validate his email address (successful login)
5. Trigger a required action email via REST API for this new user with the "UPDATE_EMAIL" action
6. Follow the steps to update the email address to a new one
7. Confirm your new email address
8. Try to log in with your old email address (successful log in when it shouldn't be)
9. See that the user still has his old username set


<img width="1440" alt="Screenshot 2024-06-20 at 12 24 29 PM" src="https://github.com/keycloak/keycloak/assets/80396648/c4ffb466-034c-48a2-972e-ccd7f3e5012d">
<img width="1440" alt="Screenshot 2024-06-20 at 12 24 46 PM" src="https://github.com/keycloak/keycloak/assets/80396648/11bd62fd-0148-4f8c-83f7-0eb51a665b6c">
<img width="943" alt="Screenshot 2024-06-20 at 12 33 17 PM" src="https://github.com/keycloak/keycloak/assets/80396648/a1782e6c-c157-4453-a971-6ec87b6d8119">

**Comment by martin-kanis** [comment]
@alispustina I tried 2 more times with your steps but no luck. I was able to achieve your state with one important tweak. 
Between steps 4 and 5, I switched off "Email as username" settings. After updating the email, only email changed but username stayed set as old email. Now I'm logically able to log in with username (old email) and with email (updated email). Please check you have really "Email as username" switched on when requesting email update.

**Comment by alispustina** [comment]
`Email as username` was switched on during all the steps. I will find a workaround and update the username through the REST API.

Thank you!

**Comment by NiC0x36** [comment]
I also have this issue on my 24.0.4 Keycloak. I do not change anything in the settings between setting / verifying the e-mail or similar.

Interestingly, the username gets correctly updated, if the user saves the personal info form of the account console after Updating the e-mail. Same behaviour, when the admin saves the form of the user in the admin console. Note, that the username and e-mail fields are read-only and the user/admin hasn't made any changes to said forms. Nevertheless, this manual workaround fixes the inceonsistency between username and e-mail.

There has been at least one similar bug in the past: https://github.com/keycloak/keycloak/issues/20459

A fix would be much appreciated.


---

Following parameters:

Env Var:
`KC_FEATURES=update-email`

Realm: 
```
{
  "realm": "myRealm",
   ...
  "editUsernameAllowed": true,
  "registrationEmailAsUsername": true,
   ...
}
```

**Comment by renannprado** [comment]
We're doing an upgrade from 22.0.5 to 26.0.4, and we're pretty sure this was working before, because I could see the username has changed as well and the username == email after the email change.

There was a regression between these versions.

As strange as it seems, while in the database I see the old username, in the admin UI I see the new one.

<img width="743" alt="image" src="https://github.com/user-attachments/assets/be328c56-ccae-4eeb-9196-bc6685022129">

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/54dcad27-97d4-46b1-91cb-60c404167881">

<img width="682" alt="image" src="https://github.com/user-attachments/assets/f9e8eace-5ec4-48bd-b54b-6386db80a980">
