### ISSUE TITLE
Admin UI slow performance loading 600+ realms

### ISSUE THREAD

**Issue by ca5p3r** [keycloak/keycloak#29978]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Whenever I try to open the admin UI and click the realms dropdown, it takes so long to load realms drop list.

After inspecting the dev tool requests, it appears that this request is the root cause:
`auth/admin/realms/master/ui-ext/realms/names?`

The request first takes approximately 3 mins to return with code 200 but the admin UI is still loading
![Screenshot (499)](https://github.com/keycloak/keycloak/assets/39639769/683c82c6-6913-44ca-a3e9-a45a735349f4)

After 3 additional minutes, the response is fully loaded to the UI
![Screenshot (500)](https://github.com/keycloak/keycloak/assets/39639769/e90a74e5-c69c-4479-8f68-9dce8eb98df4)

---------------------------------------------------
I believe this issue was fixed in previous versions of Keycloak. I've searched the currently open bugs to see if there's any similar bugs, but didn't find any.
Possibly a similar bug to this [20453](https://github.com/keycloak/keycloak/issues/20453)
---------------------------------------------------

### Version

24.0.x

### Regression

- [X] The issue is a regression

### Expected behavior

Realms dropdown list loads faster.

### Actual behavior

Realms dropdown takes approximately 6 mins with current setup of 600+ realms.

### How to Reproduce?

- A Keycloak environment with huge number of realms, my case is 600+ realms
- Open admin UI through this link: `https://{host}/auth/admin/master/console/`
- Click on the realms dropdown list

**Comment by AlaaNabil26** [comment]
I am experiencing the same issue with 400+  realms, running version 24.0.4.

**Comment by ssilvert** [comment]
@edewit Looks like the realm dropdown is no longer paginated?

**Comment by edewit** [comment]
@ssilvert it never was

**Comment by ca5p3r** [comment]
@edewit Thank you very much for the follow-up and the quick PR.

Can we expect a release date for that fix? Maybe 24.0.6?
