### ISSUE TITLE
Custom claim not added when federated user

### ISSUE THREAD

**Issue by robertoneto-senior** [keycloak/keycloak#29979]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

I have created a custom UserStorageProvider that queries for users in my legacy database, and insert users in keycloak database. It also validates the password in my legacy rotines, to migrate the password to keycloak management.

The problem is when a user is migrated at first time. The access token obtained doesn't contains my custom claims configured in the default client scope mappers.

Here is an example:

![image](https://github.com/keycloak/keycloak/assets/104595368/46183493-8e84-49ad-91a5-93d4d3e1af8f)

In the left, we can see the access_token with the "username" claim, and at the right we can see the client scope configuration inside the keycloak admin console. Note that the username claim mapper is configured.

If I login again with that username, keycloak will found it inside keycloak realm users (so my user federation provider will not be trigger), and the acccess_token will be generated respecting the client scope mappers configuration and the "username" claim will be present.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the Client Scope Mappers will be applied even the authentication uses the federation logic.

### Actual behavior

When the authentication uses the federation logic, the client scope mappers are not applied.

### How to Reproduce?

1. Create a custom UserStorageProvider,UserLookupProvider and CredentialInputValidator implementation
2. Define a Client Scope Mapper to add a username claim to the token
3. Login with a user that will be processed with your custom federator
4. Assert that the token claims has your custom claims configured in the Client Scope Mappers

**Comment by graziang** [comment]
Hi @robertoneto-senior, 
I'm not able to reproduce this, I get the username correctly using a custom `UserStorageProvider`, make sure your implementation is ok.
[Here](https://www.keycloak.org/docs/latest/server_development/index.html#_user-storage-spi) the link to the documentation for creating custom user storage provider with two sample implementations.

**Comment by robertoneto-senior** [comment]
Hi @graziang 

Yes, that was my mistake. I was extending from `AbstractUserAdapterFederatedStorage`, and that was seemed the source of problem. I made some changes based on that samples and that fixed it!

Thanks.

**Comment by robertoneto-senior** [comment]
Hi @graziang

Yes, that was my mistake. I was extending from AbstractUserAdapterFederatedStorage, and that was seemed the source of problem. I made some changes based on that samples and that fixed it!

Thanks.
