### ISSUE TITLE
Revert editorconfig for properties files as trailing blanks are used

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#29982]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Some message properties files contain blanks, and they shouldn't be automatically removed unless we check why those blanks are there, and if they can be removed safely.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Keep blanks at the end of the line in properties files

### Actual behavior

They are removed due to the `.editorconfig` file

### How to Reproduce?

Try it out in your IDE, for example with file `themes/src/main/resources/theme/base/login/messages/messages_en.properties` key `oauthGrantReview`.

**Comment by jonkoops** [comment]
Should be fine to have en EOL at the end of these files, no?

**Comment by ahus1** [comment]
In theory yes, but I'll have another PR which would add that one and fix the EOLs on those files so we won't see them later.

**Comment by ahus1** [comment]
PR created: #29983
