### ISSUE TITLE
private AuthzClient.createPatSupplier

### ISSUE THREAD

**Issue by sulakm** [keycloak/keycloak#29986]
### Description

Hi,

Could you please change accessibility of method [AuthzClient.createPatSupplier(String userName, String password)](https://github.com/keycloak/keycloak/blob/320f8eb1b403fb6e970a497b4da75e4963b0daa1/authz/client/src/main/java/org/keycloak/authorization/client/AuthzClient.java#L259) to public ?

with best regards,
Martin

### Motivation

It would be very convenient for calling REST services from Java with getting token as simply as this:
one time: `TokenCallable session = AuthzClient().create().createPatSupplier(username, password);`
repeat: `String token = session.call();`

I am not aware of any other official API for automatic token refreshing and it would be convenient for example for calling REST between two servers with single system user.

**Comment by Krishnapro** [comment]
Hi, @jonkoops I came across this issue from the cncf-zero-to-merge session and would like to work on this issue.

Please assign it to me.

**Comment by jonkoops** [comment]
Sure, go right ahead :)

**Comment by Krishnapro** [comment]
Thanks, I'm on it.

**Comment by sirine707** [comment]
Hi @Krishnapro , still working on this issue?

**Comment by Krishnapro** [comment]
Yep, I'm trying to build the project locally but having some issues.

![image](https://github.com/user-attachments/assets/ea1576a7-7b09-4502-b129-d779820c6674)

**Comment by sirine707** [comment]
ensure u have jdk 21 or above
