### ISSUE TITLE
Warnings for temporary admin user and service account

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#30009]
The admin user or service account created through the bootstrapping process as specified in https://github.com/keycloak/keycloak/issues/9829 will be handled as temporary.

This issue covers the UX.
* Temporary users and service accounts are clearly marked as temporary in the lists in Admin Console.
* When logged in as a temporary admin account in the Admin Console, clear warning is visible in the Admin Console when logged in as this user.
    * A bar at the top of all Admin Console pages.
* A warning is emitted in the log any time such a user logs in.
* The warnings include a note when the account will be deleted.

**Comment by vmuzikar** [comment]
Work in progress: https://github.com/keycloak/keycloak/compare/main...vmuzikar:keycloak:temp-admin-warns

What's done:
* A banner at the top of all Admin Console pages.
* Attributes for temp admin user and service account.
What's left:
* A clear label in the tables with users/clients clearly marking a temp admin.
* UI tests.
* Warning in the log if a temp admin user or service account logs in.

Hint - steps to run Admin Console in dev mode:
1. `cd js/apps/keycloak-server && pnpm start --local --admin-dev`.
2. `cd js/apps/admin-ui && pnpm dev`

**Comment by atul-epam** [comment]
@vmuzikar 
So, is that we are only bootstrapping temp admin user and we have completely removed the concept of bootstrapping permanent admin user? Because I am not using KC_BOOTSTRAP_ADMIN_USERNAME and KC_BOOTSTRAP_ADMIN_PASSWORD variables to bootstrap my admin user but still I see warning "You are logged in as a temporary admin user. To harden security, create a permanent admin account and delete the temporary one."

**Comment by vmuzikar** [comment]
The `KC_ADMIN_USER` and `KC_ADMIN_PASSWORD` env var are now deprecated and also create a temporary user same as `KC_BOOTSTRAP_ADMIN_USERNAME` and `KC_BOOTSTRAP_ADMIN_PASSWORD`. The thought behind this is that creating a user this way that is the Master Realm admin is not really secure and such user should be used only temporarily for creating a more secure and permanent admin user (that uses 2FA etc.)

**Comment by ToanTNM** [comment]
> The `KC_ADMIN_USER` and `KC_ADMIN_PASSWORD` env var are now deprecated and also create a temporary user same as `KC_BOOTSTRAP_ADMIN_USERNAME` and `KC_BOOTSTRAP_ADMIN_PASSWORD`. The thought behind this is that creating a user this way that is the Master Realm admin is not really secure and such user should be used only temporarily for creating a more secure and permanent admin user (that uses 2FA etc.)

hi @vmuzikar 
How can we create permanent admin user. The document said that `Keycloak only allows to create the initial admin user from a local network connection`. I tried connecting to keycloak by local IP or domain, but I couldn't find and assign `admin` role to new user.
