### ISSUE TITLE
Multivalue User attribute set via API unexpected/random order with MSSQL 2022 DB

### ISSUE THREAD

**Issue by keycloakrules420** [keycloak/keycloak#30039]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When setting a multi value user attribute via the API Keycloak saves it in an unpredictable order. 
example:
Created 100 users with a multi value attribute 46 have it out of order.
![image](https://github.com/keycloak/keycloak/assets/120559574/ef4257d3-7799-41aa-9b21-2791d3b652cd)

I wasn't able to reproduce this behaviour with the dev database. 
Tested with MSSQL 2022

### Version

23.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Multi-value attributes are stored and returned in order via the API. Using MSSQL

### Actual behavior

Multi-value attributes are stored and returned in out of order via the API. Using MSSQL

### How to Reproduce?

Setup Keycloak 22+ with MSSQL 2022 as Database
Create users with multi value user attributes.

Validate order of attributes

### Anything else?

Tested with Terraform v1.8.4 and mrparkers/keycloak 4.4.0
This behaviour can be reproduced without using terraform

**Comment by sguilhen** [comment]
AFAIK the API doesn't really guarantee value order for the multi-valued attributes. I can see still some value to it, so I'm marking this as a low priority issue that can ideally be handled by the community.
