### ISSUE TITLE
Save button is not activated at first modification on "Client scope details"

### ISSUE THREAD

**Issue by jsorah** [keycloak/keycloak#30048]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Save button is not activated when modifying properties on the "Client scope details" page for the first time. User must modify it again in order to activate it.

### Version

nightly

### Regression

- [X] The issue is a regression

### Expected behavior

Save button activates when properties are modified immediately. Alternatively, the save button could always be activated.

### Actual behavior

Save button does not activate until the user has modified a property twice.

In cases of text boxes this is simply entering another character, but for toggles it means clicking them again and then once more to reach the desired state.

### How to Reproduce?

Created a new Client scope, navigate to modify it after saving it, and simply try to edit the properties of the scope.
[Kooha-2024-05-31-11-19-41.webm](https://github.com/keycloak/keycloak/assets/4944041/25a6782c-3c9f-4516-a530-d5fab05a7586)

### Anything else?

I haven't tested other areas of Admin UI, but this so far is the only place I noticed it.

**Comment by ssilvert** [comment]
I have verified this bug.

**Comment by ahanamallik1** [comment]
@ssilvert @jsorah 

I am fixing this bug.

**Comment by ssilvert** [comment]
> @ssilvert @jsorah
> 
> I am fixing this bug.

Great!  Thank you.
