### ISSUE TITLE
All roles are populated as inherited roles if a single role is added to a dedicated client scope

### ISSUE THREAD

**Issue by rootbeerefloat** [keycloak/keycloak#30049]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In the scope tab of a dedicated client scope, if "Full Scope Allowed" is disabled and a role is added, all the roles in the realm are added as implied roles and are visible once the "Hide inherited roles" box is unchecked.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

  A SAML client is created. Under the *Client Scopes* tab, the dedicated scope is selected. Within the dedicated scope, the *scope* tab is selected. The "Full scope allowed" toggle is set to off, and a role is assigned. When "Hide inherited roles" is unchecked, only the assigned role and default roles should be visible.

### Actual behavior

A SAML client is created. Under the *Client Scopes* tab, the dedicated scope is selected. Within the dedicated scope, the *scope* tab is selected. The "Full scope allowed" toggle is set to off, and a role is assigned. When "Hide inherited roles" is unchecked, every role in the realm is visible.

### How to Reproduce?

Create several roles within a realm. Create a SAML client in the realm. Select the client scopes tab of the SAML client, select the client's dedicated scope, and select the scope tab. Turn off "Full scope allowed" and add a single role to the scope. Uncheck "Hide inherited roles" to see all the realm's roles added.

### Anything else?

This issue appears to be similar to [issue19982](https://github.com/keycloak/keycloak/issues/19982) and may be related.

**Comment by ssilvert** [comment]
I have recreated this bug.
