### ISSUE TITLE
The OID4VC tests break automation

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#30079]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

The [OID4VC UI commit](https://github.com/keycloak/keycloak/pull/29174) introduced "test" which never run anything since it was using property access instead of function calls: Note the missing `();` denoting function calls in [the test](https://github.com/keycloak/keycloak/pull/29174/files#diff-bcc8430b113f420f11c5ec5071ad5c511f8aa632a712c28da62c13c5a2a5a5b3.)

Now the account tests passed because they were never run, see #29976. Once this is fixed, the account tests fail due to the test issues, see https://github.com/keycloak/keycloak/actions/runs/9348103213/job/25726758123?pr=29973#step:8:116.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

The test tests desired behaviour and passes.

### Actual behavior

The test does not test anything, but fails regardless due to missing `oid4vci` control.

This is the place where it fails:

![image](https://github.com/keycloak/keycloak/assets/5391360/c7c7b82c-e2ea-4164-bf03-fcdcb535a436)

### How to Reproduce?

Run account e2e tests.

**Comment by hmlnarik** [comment]
Now that the [oid4vci.spec.ts is removed](https://github.com/keycloak/keycloak/pull/29973/files#diff-bcc8430b113f420f11c5ec5071ad5c511f8aa632a712c28da62c13c5a2a5a5b3), I am lowering the priority of this to important.

**Comment by mposolda** [comment]
@wistefan mentioned that he is already looking into this issue (I am not able to assign this directly, so just commenting).

**Comment by wistefan** [comment]
@mposolda Yes, I'm currently taking a look
