### ISSUE TITLE
Do we need to allow multiple social providers in a realm and organizations linked to multiple instances of a single social provider?

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#30088]
In the context of a realm, most of the time a single instance of a social broker is enough. However, some of these brokers (e.g.: Microsoft) support multi-tenancy and it might be desirable to have specific brokers for each tenant configuration too.

So far, having a single social broker instance in a realm seems to not be a problem for deployments but in the context of organizations, it makes it impossible to use separate social broker instances in different organizations. Therefore, blocking organizations to have their own social providers to authenticate their members.

This issue is about allowing multiple social brokers within a realm so that you can link those instances to different organizations.

**Comment by xgp** [comment]
@pedroigor This will be a great addition!

Question: Does this change also apply to extensions that add a new Identity Provider type? We opened a discussion about allowing multiple instances of a [extension-defined Identity Provider type](https://github.com/keycloak/keycloak/discussions/29666), but didn't get any feedback. We've also been following this issue about [editing alias and display name for custom identity providers](https://github.com/keycloak/keycloak/issues/24710). I would argue that the need this addresses (an organization needs a separate instance of an IdP) doesn't just apply to "social", but all Identity Provider types, including custom.

**Comment by pedroigor** [comment]
@xgp Not sure if I understand the question but if it is about creating multiple instances (using different alias) and assign those instances to different organizations, yes it is possible. This change in particular is allowing that for social providers as it was not possible to create multiple instances of them as their alias was hardcoded with the ID of the provider.

What we don't support is sharing the same broker instance across multiple organizations.

Does it help?

**Comment by pedroigor** [comment]
@xgp I think I see what you mean, see https://github.com/keycloak/keycloak/discussions/29666#discussioncomment-9795005.

**Comment by xgp** [comment]
Yes. That does it @pedroigor. Thanks for verifying. Looking forward to this in `26`!

cc @rtufisi
