### ISSUE TITLE
Admin v2 theme - theme.properties Custom theme scripts not loading

### ISSUE THREAD

**Issue by jamesjose03** [keycloak/keycloak#30115]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Scripts specified in custom theme.properties are not loaded for admin console

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Scripts specified should get attached to the theme and loaded in the admin console UI

### Actual behavior

Custom scripts are ignored

### How to Reproduce?

specify any script in the theme.properties.

ex:

scripts=test.js

where test.js contains

alert('test alert');

### Anything else?

Similar to Issue #25502

**Comment by jonkoops** [comment]
Really going to need more information to test this, please provide a reproducible example, as what you have posted here works fine in my testing on the latest stable. Also please make sure to use the latest version of Keycloak when reporting an issue.

Also what does "Custom scripts are ignored" mean? Is the script tag not added to the HTML? Does it not load? Are you seeing an error?

**Comment by jamesjose03** [comment]
@jonkoops 
For reproducing this issue,
1. Add a custom theme for admin console.
2. In themes/custom-theme/admin/resources/js -> add a simple test.js file with content:
`alert('test alert');`
3. Add `scripts=js/test.js` in theme.properties
4. Run the instance and apply the custom theme.
5. Script does not get attached in the admin console page (no script tag with the src specified in the HTML)

Similiar to the issue reported in #25502

**Comment by ssilvert** [comment]
I have verified this bug.
