### ISSUE TITLE
Partial Import does not work

### ISSUE THREAD

**Issue by ciis0** [keycloak/keycloak#30128]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After using "Partial Export" I cannot import the file using "Partial Import" (the "Import" button stays grayed out).

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

file can be imported (by browse, d'n'd, paste)

### Actual behavior

"Import" button stays grayed out.

### How to Reproduce?

1. create new realm
2. go to realm settings
3. actions --> partial export: keep defaults, save file.
4. actions --> partial import: browser for file

observe the import button stays grayed out.

### Anything else?

tested in Firefox 126 and Edge 125

tested via container: `podman run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:24.0.5 start-dev`, both 24.0.5 (shown) and nightly (not shown, I made sure to pull latest nightly).

**Comment by ssilvert** [comment]
The reason that the `Import` button is not active is because there is nothing to import.

A partial import can import users, clients, identity providers, groups, and roles.  None of those exist in the partial export when you do an export on a new realm with all defaults.

We probably should have a message for this to make it more clear though.

**Comment by ciis0** [comment]
ah, ok, i was trying to import client scopes... :)

**Comment by ciis0** [comment]
(I accidentally deleted the OpenID `profile` scope and wanted to restore it via that... ^^)

**Comment by jaeaxt** [comment]
Hi, I'm trying to do a partial import for organization but it doesn't work. The import button is not active even when I copy and past the exported data. But If use the option import-realm at start with adding the organizations to my realm file it's work.
