### ISSUE TITLE
Specials chars in policy name prevent enabling policy again

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#30141]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When the name of a policy contains a dot "." and I disable the policy, I am not able to enable the policy again via keycloak admin console.
The UI tells me that the enabling has worked and that the policy is active, but if switch to another section of the admin console and than back to client policies, the policy is disabled again.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

I should be able to enable a disabled policy no matter the policy name

### Actual behavior

Policies with a dot in their name can not be enabled after disabling them once.

### How to Reproduce?

Create a policy and name it "ddd.rrr".
Disable the policy.
Try to enable the policy again.
At first it will seem like the enabling worked but if you switch to another tab of the realm-settings section or even switch the section and then come back to the client-policies, the policy is disabled again.

**Comment by raff897** [comment]
Hi, it's a frontend bug.
When you click on enable switch out of policy it pass null value as enabled in client policy rapresentation.


Workaround while someone that is a frontend developer fixes the bug:
- Open policy that has special chars
- Enable it from inside.

![enable-keycloak-policy](https://github.com/keycloak/keycloak/assets/85362193/34fdc8a7-9165-4a8a-8c65-1c585832f1b9)

**Comment by ch-lepp** [comment]
The workaround is also broken but in a different way.

It removes all conditions and client profiles from the client policy...

**Comment by raff897** [comment]
I'm trying to reproduce this but when :
In a policy called 2222.2222 with conditions and client profiles i set enabled with this  workaraund  it works correctly.
Only way to delete all conditions and client profiles is to chage name (another issue) but if you recharge the page they reappear.

**Comment by ch-lepp** [comment]
Nope, that issues definitely existed as described in Keycloak 24.0.4 which we have in production.

Reproduce by creating a policy named "rrr.fff".
Add a Condition and a Client Profile to the policy.
Close the policy and disable it in the policies overview.
Open the policy again and enable it.
It seems now that all conditions and client profiles are still there.
But if you close the policy and reopen it again, all conditions ans client profiles are deleted.

However, I just tested it in the new Keycloak 25.0.0 and here both issues are fixed.
I can deactivate and reactivate the policy in the policies overview.
And when I reactivate a deactivated policy the attached conditions and profiles dont get deleted anymore.
So this ticket can be closed, I guess.
