### ISSUE TITLE
creating a java-keystore provider automatically chooses random algorithm, rendering the keystore useless

### ISSUE THREAD

**Issue by navatweb** [keycloak/keycloak#30151]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Our security team requires us to not save the private key used to generate access tokens in the database.
We have been trying to create a java-keystore provider for this purpose.
KeyCloak saves it successfully but the algorithm shown appears to be randomly selected after the keystore has been configured in KeyCloak. The keystore keys are in RSA256 but KeyCloak shows PS512 etc. At times if we move the entry up or down, the algorithm changes. If we are able to get KeyCloak to recognize that it is RSA256, the provider does work but there is no predictable way to be able to get KeyCloak to do so.
We don't get option to select the correct algorithm.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

When we configure a good java keystore, it should be used by keyCloak to generate tokens.
KeyCloak either should recognize the correct algorithm used to  generate the key or it should allow the user to choose it.

### Actual behavior

We are unable to configure a java keystore because KeyCloak appears to incorrectly choose a key algorithm. 

### How to Reproduce?

create a JKS or PKS12 keystore. Use RSA256 keys. When you configure the java provider using this keystore, KeyCloak shows apparently random algorithms such as PS512 etc, causing KeyCloak to ignore the java provider.

**Comment by rmartinc** [comment]
Can you please explain in more detail what you are trying to do?
Are you trying to configure a key provider of type `java-keystore` in the realm (Realm settings -> Keys -> Add provider)?

**Comment by navatweb** [comment]
Yes. Since we are not comfortable having the private key in clear in the database, we want to use a java provider with a keystore that contains the private key.
I think this is a regression as I am able to get this to work in 21.1.1.
problems are:
- after setting up the java provider the key algorithm shows wrong.
- there is no dropdown to be able to change the algorithm,
- consequently, this java provider is never used to provide the key, essentially making the feature useless.
I'll try and attach a screenshot or a video. But it is easy to reproduce:
- create a keystore
- create a java provider using this keystore
- make this keystore the first one.
- check the java provider's key algorithm: Most of the time it will not be the needed RSA256. And there will be no way to change it in the UI 
- delete and setup the java provider again. You will likely see another algorithm, again probably not RSA256.
- we have also noticed that if we move this provider, up or down,  in the list, the algorithm changes randomly.
-

**Comment by rmartinc** [comment]
Yes, now I understand. Yes, there was an error in keycloak 24.0.4 that mixed default and options in the JavaKeystoreKeyProvider properties. It's this issue: https://github.com/keycloak/keycloak/issues/29426.

It's already fixed in main and waiting to be backported to 24.x. The backport PR was not in time for 24.0.5 but it will be incorporated in the next update. For the moment you can just use 24.0.3 or create the java keystore manually using the kcadm:

```bash
cat /tmp/lala 
{
  "name" : "java-keystore",
  "providerId" : "java-keystore",
  "providerType" : "org.keycloak.keys.KeyProvider",
  "config" : {
    "keystorePassword" : ["password"],
    "keyAlias" : ["server"],
    "keyPassword" : ["password"],
    "keystoreType" : ["PKCS12"],
    "keyUse" : ["sig"],
    "active" : ["true"],
    "keystore" : ["/tmp/server.keystore"],
    "priority" : ["200"],
    "enabled" : ["true"],
    "algorithm" : ["RS256"]
  }
}
./kcadm.sh create components -r backauth -f /tmp/lala -x
Created new component with id '53812a7c-8c66-4dfd-8d11-6145be7391fc'
```

This is duplicate of #29426. I'm closing the issue as it's already fixed and pending backport.
