### ISSUE TITLE
Documentation : Part of the documentation of previous releases points to documentation of the latest release.

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#30177]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

We are using Keycloak 22.0.5 and we need to look at the documentation related to server configuration to check back some settings for the usage of a reverse proxy : https://www.keycloak.org/archive/documentation-22.0.html
The problem is that the link for 'Server Installation and Configuration' links to the latest version of the documentation and not the documentation of the 22.0 version.

I cannot refer to the documentation of the latest version as the settings related to the usage of the reverse proxy have changed a lot.

The links to 'Release Notes', Securing Applications and Services', 'Server Administration', 'Server Developer', 'Authorization Services', 'Upgrading', 'Javadoc' and 'Administration REST API' are correct.

Only 'Getting Started', 'Server Installation and Configuration' and 'Server Container Image' have incorrect links : 

![image](https://github.com/keycloak/keycloak/assets/11772429/950178a9-e5f1-49fb-8f92-4f6abe7ed4f4)

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The documentation of previous releases should point the the documentation of the selected release and not the the latest release

### Actual behavior

Some part of the documentation of previous releases have links to the documentation of the latest release

### How to Reproduce?

Go to https://www.keycloak.org/archive/documentation-22.0.html or https://www.keycloak.org/archive/documentation-23.0.html and click on 'Getting Started', 'Server Installation and Configuration' and 'Server Container Image' -> You will be redirected to the latest documentation.

**Comment by omasseau** [comment]
PS: Documentation zip provided on the release page is not an option at it is incomplete. See : https://github.com/keycloak/keycloak/issues/23210#issuecomment-2150621949

**Comment by stianst** [comment]
This is not a bug as we don't currently publish the guides for older releases. I appreciate that referring to older versions may be useful, but at the moment we don't have time to look into it, but do plan to do so at some point.

@invalid

**Comment by stianst** [comment]
~invalid

**Comment by omasseau** [comment]
> This is not a bug as we don't currently publish the guides for older releases. I appreciate that referring to older versions may be useful, but at the moment we don't have time to look into it, but do plan to do so at some point.
> 
> @invalid

@stianst 
I don't really agree. Misleading links is a bug. Maybe you should completely remove the links so people don't think they are valid for the given version ?
