### ISSUE TITLE
Adding setters to some properties in the OIDCConfigurationRepresentation

### ISSUE THREAD

**Issue by CarlRivard** [keycloak/keycloak#30178]
### Description

We need the well-known values of the open-id-configuration/uma2-configuration **frontChannelLogoutSessionSupported** and **frontChannelLogoutSupported** to be set to false, because even though Keycloak does support these logout options, our solution doesn't.

After exploring the source code, we found out that the values of these OIDCConfigurationRepresentation properties are hardcoded at true in the class, and there are no setters available for us to change their values, making it impossible to update them in the well-known without an enhancement to that class.

We are also wondering if you could add a way to feed a json to update the values in the well-known, instead of relying on the OpenID Connect settings. 

Thank you ! 

Reference :

![image](https://github.com/keycloak/keycloak/assets/93336348/85629563-29f8-4106-8dac-3c356bd9684c)

![image](https://github.com/keycloak/keycloak/assets/93336348/77861c7f-aafb-4412-8e60-684e1540c5bc)

**Comment by mposolda** [comment]
@CarlRivard Feel free to send PR with adding setters.

There is already a way to override the default `oidc` config, but it is not documented as it is not very friendly and officially supported... You can add configuration property `openid-configuration-override` of the provider `OIDCWellKnownProviderFactory` pointing to a file with the overriden JSON properties you want to change from the values set by Keycloak. See `OIDCWellKnownProviderFactory.init` method for more details.

**Comment by keshavprashantdeshpande** [comment]
@mposolda I have created a PR with setters. Please feel free to review it.

**Comment by pedroigor** [comment]
@CarlRivard Did you try using the `spi-well-known-openid-configuration-openid-configuration-override` provider option. See https://www.keycloak.org/server/all-provider-config#_well_known.
