### ISSUE TITLE
Keycloak CI - failure in Store IT (aurora-postgres)

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#30201]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
TASK [Gathering Facts] *********************************************************
fatal: [3.90.144.164]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "failed": true, "module_stderr": "Shared connection to 3.90.144.164 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127, "warnings": ["No python interpreters found for host 3.90.144.164 (tried ['python3.12', 'python3.11', 'python3.10', 'python3.9', 'python3.8', 'python3.7', '/usr/bin/python3', 'python3'])"]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
```

https://github.com/keycloak/keycloak/actions/runs/9392974293/job/25868350613

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by ahus1** [comment]
Thank you for this PR for main, I double-checked that this [worked great](https://github.com/keycloak/keycloak/actions/runs/9409547543) in main last night.

Please provide a backport for KC24 for this as well. Thanks!

**Comment by ryanemerson** [comment]
https://github.com/keycloak/keycloak/pull/30245
