### ISSUE TITLE
Offline sessions org.hibernate.StaleStateException and OptimisticLockException

### ISSUE THREAD

**Issue by iliuta** [keycloak/keycloak#30224]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have a Keycloak 24.0.5 installation in production running with 2 instances.
For some unknown reason, the 2 instances crashed and I learnt on that occasion that sessions were kept in memory. A lot of users were affected.
As regular sessions are not (yet) stored into the database I managed to activate the offline sessions.
On a specific realm, I have an identity provider (Okta) configured. For users of that identity provider, I have regularly this kind of errors:

```
Exception:
org.hibernate.StaleStateException
Message:
Unexpected row count: 0; expected: 1; statement executed: update OFFLINE_CLIENT_SESSION set DATA=?,TIMESTAMP=? where CLIENT_ID=? and CLIENT_STORAGE_PROVIDER=? and EXTERNAL_CLIENT_ID=? and OFFLINE_FLAG=? and USER_SESSION_ID=?


Exception:
org.hibernate.StaleObjectStateException
Message:
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.jpa.session.PersistentClientSessionEntity#org.keycloak.models.jpa.session.PersistentClientSessionEntity$Key@13093958]


Exception:
jakarta.persistence.OptimisticLockException
Message:
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.jpa.session.PersistentClientSessionEntity#org.keycloak.models.jpa.session.PersistentClientSessionEntity$Key@13093958]

```

From my understanding it happens when the client mobile app tries to refresh the access token using the (offline) refresh token, by calling this url:
/auth/realms/<realm>/protocol/openid-connect/token

Any ideas, please? If I migrate to Keycloak 24, it could be a solution?
Thanks.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Token should be refreshed and Keycloak should return 200 instead of 500.

### Actual behavior

Keycloak returns 500 error from time to time when trying to use the offline refresh token for having a new access token.

### How to Reproduce?

Activate offline sessions with expiration, offline session idle 90days and offline session max 365 days.
Configure a identity provider link.
Authenticate a user and try to refresh the tokens.

**Comment by iliuta** [comment]
We'll soon migrate to keycloak 24 and update the ticket accordingly.

**Comment by iliuta** [comment]
I've just upgraded to 24.0.5 and it's the same. I'm still having the Optimistic Lock problems. 
I feel like there are good chances that it's the same with Keycloak 25 ...

POST /auth/realms/<realm>/protocol/openid-connect/token

Here are the queries performed by Keycloak, according to our APM:

```

select puse1_0.OFFLINE_FLAG,puse1_0.USER_SESSION_ID,puse1_0.CREATED_ON,puse1_0.DATA,puse1_0.LAST_SESSION_REFRESH,puse1_0.REALM_ID,puse1_0.USER_ID from OFFLINE_USER_SESSION puse1_0 where puse1_0.OFFLINE_FLAG=? and puse1_0.USER_SESSION_ID=? and puse1_0.REALM_ID=? fetch first ? rows only

select pcse1_0.CLIENT_ID,pcse1_0.CLIENT_STORAGE_PROVIDER,pcse1_0.EXTERNAL_CLIENT_ID,pcse1_0.OFFLINE_FLAG,pcse1_0.USER_SESSION_ID,pcse1_0.DATA,pcse1_0.TIMESTAMP from OFFLINE_CLIENT_SESSION pcse1_0 where pcse1_0.USER_SESSION_ID=? and pcse1_0.OFFLINE_FLAG=?


delete from OFFLINE_CLIENT_SESSION where USER_SESSION_ID=? and OFFLINE_FLAG=?


select OFFLINE_FLAG from OFFLINE_USER_SESSION where OFFLINE_FLAG=? and USER_SESSION_ID=? for update

delete from OFFLINE_USER_SESSION where OFFLINE_FLAG=? and USER_SESSION_ID=?

insert into OFFLINE_USER_SESSION (CREATED_ON,DATA,LAST_SESSION_REFRESH,REALM_ID,USER_ID,OFFLINE_FLAG,USER_SESSION_ID) values (?,?,?,?,?,?,?)

nsert into EVENT_ENTITY (CLIENT_ID,DETAILS_JSON,DETAILS_JSON_LONG_VALUE,ERROR,IP_ADDRESS,REALM_ID,SESSION_ID,EVENT_TIME,TYPE,USER_ID,ID) values (?,?,?,?,?,?,?,?,?,?,?)

update OFFLINE_CLIENT_SESSION set DATA=?,TIMESTAMP=? where CLIENT_ID=? and CLIENT_STORAGE_PROVIDER=? and EXTERNAL_CLIENT_ID=? and OFFLINE_FLAG=? and USER_SESSION_ID=?

SQL Rollback

SQL Commit
```

**Comment by mposolda** [comment]
@iliuta Could you please clarify what is your database vendor including version?

Does this happen just for the users with offline-sessions, which logged by this particular Okta identity provider? Or do you know if it happens sometimes also for the users, who logged some other way? Finally, is it OIDC identity provider or SAML identity provider?

Finally, do you have opportunity to disable storing of the events into your DB? Just wondering if the issue is related to the fact that storing of events is enabled. I understand that this may not be easily possible in your production environment, so asking just in case if this is an option for you...

**Comment by iliuta** [comment]
Hi @mposolda 
Yes, this happens only with offline sessions. 
We disabled for now the offline sessions and everything is back to normal, but we are exposed again to the situation where Keycloak crashes again.
This is an OIDC provider (not SAML). For SAML we don't have the issue.
I'll try to disable event storing.

**Comment by iliuta** [comment]
Ok, I deactivated the events and it hasn't changed. Still having the 500 errors.

The insert into EVENT_ENTITY query however is no longer on the list of executed queries.

Regarding the chain of sql queries, does it sound normal for you? 
I'll try to clone the code and search for this part so I can understand better.

Thank you very much.

**Comment by iliuta** [comment]
@mposolda 
I think I might have found the cause but we need to do further testing to be really sure.
There is a strong possibility that it's because of the library we're using on our iOS app to handle OIDC with Keycloak and federation identity with external identity provider (like Okta). So Keycloak might not even be involved.
