### ISSUE TITLE
Custom attributes are removed during UPDATE PROFILE event

### ISSUE THREAD

**Issue by soulchild** [keycloak/keycloak#30240]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

We have a custom User Storage Provider SPI which syncs users from an external system. We're using a custom attribute to reference the user across both systems. After upgrading from Keycloak v22 to v24 we noticed a very small number of users were suddenly missing their essential attributes. After a lot of debugging I came across these events which were triggered for exactly those few users that are now missing their attributes:

<img width="835" alt="Screenshot 2024-06-07 at 08 48 08" src="https://github.com/keycloak/keycloak/assets/59642/8384a284-e4dc-4901-9e50-99800bedc73d">

After the Keycloak upgrade, the "Unmanaged Attributes" option in the realm was correctly set to "Enabled" to preserve the pre-v24 behaviour.

I'm not sure what even causes the "UPDATE PROFILE" event in the first place because we're not promoting the Account Console to our users (there are only 15 UPDATE PROFILE events in the last few months, so fortunately it's rather rare).

Nonetheless, custom attributes getting deleted on profile updates is quite serious. I suspect it has got something to do with the new User Profile feature that was enabled by default in Keycloak v24, but I think it's supposed to behave exactly like previous versions when doing an upgrade, isn't it?

We have those custom attributes write-protected by listing them in the `KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_READ_ONLY_ATTRIBUTES` and `KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_ADMIN_READ_ONLY_ATTRIBUTES` environment variables and this seems to be the key: Every attribute listed here is getting removed when updating your profile.

Any ideas would be greatly appreciated!

### Version

24.0.3

### Regression

- [X] The issue is a regression

### Expected behavior

Custom attributes should be preserved when profile is updated.

### Actual behavior

Custom attributes are getting removed when profile is updated.

### How to Reproduce?

1. Using the Keycloak UI, set the attribute `MY_CUSTOM_ATTRIBUTE` to some value. 
2. Protect this custom attribute by setting `KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_READ_ONLY_ATTRIBUTES=MY_CUSTOM_ATTRIBUTE` and restart Keycloak. 
3. Go to the account console and update your profile. 
4. `MY_CUSTOM_ATTRIBUTE` will be gone.

**Comment by soulchild** [comment]
I noticed that the custom attributes are kept during profile updates when I set the option "Unmanaged Attributes" to "Only administrators can write". Is that the intended behavior? And more importantly: Will this make my custom attributes be updatable by admins (via UI/Admin API) and my User Storage Provider only and no normal user will be able to modify them?

**Comment by pedroigor** [comment]
> I noticed that the custom attributes are kept during profile updates when I set the option "Unmanaged Attributes" to "Only administrators can write". Is that the intended behavior? And more importantly: Will this make my custom attributes be updatable by admins (via UI/Admin API) and my User Storage Provider only and no normal user will be able to modify them?

Yes. You can also set `Only administrators can view` to make them read-only for admins.

> 
> I find the hint in the "Unmanaged Attributes" tooltip very confusing:
> 
> > By setting `Only administrators can write`, unmanaged attributes can be managed only through the administration console and API, useful if you have already defined any custom attribute that can be managed by users but you are unsure about adding other attributes that should only be managed by administrators
> 
> "Unmanaged attributes can only be managed through the admin console and API" (which only admins can access) but at the same time "custom attributes ... can be managed by users"? The naming of the option suggests that only admins can ever modify custom attributes - never normal users. Is this supposed to mean, that **unmanaged** attributes (not defined in the User Profile) can only be managed by administrators, whereas **managed** attributes (defined in the User Profile) will be honored and can be managed by the users, if the configuration in the "User Profile" allows them to?

Yes, you got it right.

**Comment by pedroigor** [comment]
@soulchild If you have the custom attributes defined in both `KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_READ_ONLY_ATTRIBUTES`  those attributes should not be removed. Is it the case?

But overall, the behavior it is the expected behavior as you have unmanaged attributes `Enabled`. You should change to a more strict policy (e.g.: only admins can write/read) or define the custom attributes in the user profile configuration and configure them accordingly.

**Comment by soulchild** [comment]
Thanks for the clarifications, @pedroigor!

> If you have the custom attributes defined in both KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_READ_ONLY_ATTRIBUTES those attributes should not be removed. Is it the case?

So maybe the behavior I'm seeing really is unintended, because given this environment variable:

```bash
KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_READ_ONLY_ATTRIBUTES=MY_CUSTOM_ATTRIBUTE
```

and the "Unmanaged Attributes" set to "Enabled", the attribute `MY_CUSTOM_ATTRIBUTE` **is deleted** when I update my profile with the account console (in Keycloak v24).

In Keycloak v22 we had the exact same environment variables and an update to a user's profile **did not** remove the custom attribute `myCustomAttribute`. I just started a local Keycloak v22 container to verify this:

```bash
docker run \
  -v $PWD/data:/opt/keycloak/data \
  --rm --name mykeycloak -p 8080:8080 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  -e KC_SPI_USER_PROFILE_DECLARATIVE_USER_PROFILE_READ_ONLY_ATTRIBUTES=MY_CUSTOM_ATTRIBUTE \
  quay.io/keycloak/keycloak:22.0.5 start-dev
```

#### Steps to reproduce

- Add a new user with credentials via the admin console 
- Manually add the "MY_CUSTOM_ATTRIBUTE" attribute in the admin console
- Go to http://localhost:8080/realms/master/console
- Log in as the new user
- Save the profile
- `MY_CUSTOM_ATTRIBUTE` is still there
- Do the same with a `keycloak:24.0.3` image and the attribute is gone after updating the profile

I believe this should be fixed or pointed out in the upgrade guide in capital letters because losing user attributes could potentially wreak all sorts of havoc without anyone noticing right away.

**Comment by pedroigor** [comment]
@soulchild Thanks. Sent a fix https://github.com/keycloak/keycloak/pull/30534.

It was introduced when we added support for unmanaged attribute policies so that they were checked first before looking at the "read-only" internal attributes set via that provider configuration.

Please, let me know if it works for you.
