### ISSUE TITLE
createClientAccessToken method return nullPointerException

### ISSUE THREAD

**Issue by mervealtinbas** [keycloak/keycloak#30242]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Hi,

I try access token using createClientAccessToken method in TokenManager class  but throw null pointer exception after transformAccessToken method. KeycloakSessionFactory create KeycloakSession but client in session is null. When I try version 21.1.2, I didnt got same error. Is it bug for version 24 ? 

### Version

24.0.4/24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

KeycloakSession session = factory.create();
Realm,client should not be null in session because these information are used in the called method.

### Actual behavior

KeycloakSession session = factory.create();
Realm,client are null in session.

### How to Reproduce?

- I write custom user federation  implementing UserStorageProviderFactory and ImportSynchronization.
- I try produce access token in snyc method. I send parameters for createClientAccessToken method. 
- I got null pointer error, because keycloakSession.getContext().getClient() is null.

**Comment by rmartinc** [comment]
With this information it's almost impossible we can help you. At least paste the full NPE you are receiving and give some sample code (it could be a simple playgrund) that shows the issue.

In general when you access the keycloak internal classes the session context should be  initialized with the realm/client/... that is currently being processed. This is done for example [here](https://github.com/keycloak/keycloak/blob/24.0.5/services/src/main/java/org/keycloak/services/resources/RealmsResource.java#L185) for the realm or [here](https://github.com/keycloak/keycloak/blob/24.0.5/services/src/main/java/org/keycloak/protocol/oidc/utils/AuthorizeClientUtil.java#L85) for the client when the TokenManager is used inside the TokenEndpoint. Check if you need to assign that data in the context  before calling the token manager.

**Comment by mervealtinbas** [comment]
You are right it is not clear but I reviewed example links. I set client and realm info to context and works ! :) 
I thought it would be a bug because I did not need this process in previous versions. Thank you for helps..

**Comment by rmartinc** [comment]
Perfect @mervealtinbas! Closing the issue then.
