### ISSUE TITLE
Docs: server_development/topics/admin-rest-api.adoc

### ISSUE THREAD

**Issue by DLewisEE** [keycloak/keycloak#30255]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

The instructions at https://www.keycloak.org/docs/latest/server_development/#example-using-java seem very clear.  When I add the dependency to my pom.xml file and build, no errors or warnings occur.  When I try to run it though, I get a ClassNotFoundExcepetion for org.keycloak.admin.client.Keycloak.

Caused by: java.lang.ClassNotFoundException: org.keycloak.admin.client.Keycloak
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	...

Interestingly, when I look at the Keycloak src, that's not where the admin client lives, rather it lives in keycloak-admin-client-jee and the jee directory isn't mentioned anywhere.  What am I overlooking that will allow this sample to run when it compiles cleanly??

File: server_development/topics/admin-rest-api.adoc

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Actual behavior

I think either the class definition is wrong or the code is wrong, but it would be nice if the docs provided sample code that actually builds AND runs.

### How to Reproduce?

Literally follow the steps on the page to run that code snippet with a maven project.  It will build but not run.

**Comment by rmartinc** [comment]
There are two different clients depending if you are using the new jakarta or the old javax EE integration. So, to use the jakarta flavor you need the `keycloak-admin-client` that is documented. If you want to use the old javax version you need the `admin-client-jee` you are commenting. We are just documenting the new jakarta artifact because we think is the common one that people is going to use.

WDYT? I'm not in favor to document the two libraries as the old javaee one will be removed someday.

**Comment by rmartinc** [comment]
I'm closing this as we think that just commenting the common and new jakarta version is OK. The old javaee/javax version will be removed at some point. If someone disagrees please reopen or file a new issue with the desired changes in the server development documentation.
