### ISSUE TITLE
Protect the disabling of the main keycloak account

### ISSUE THREAD

**Issue by estani** [keycloak/keycloak#30267]
### Description

I unintentionally clicked on the "enable" button of the main keycloak account in the master realm and it automatically turned it off effectively forbidding the management of the server.

### Motivation

One click should never brick an installation. There are multiple options to sort this out:
- Never allow the last admin account to be disabled (before disabling check there are other accounts)
- never allow the account referenced by some environmental variable to be disabled (e.g. KEYCLOAK_ADMIN)
- show a popup to confirm intention.

### Details

It's not terrible, since when you have access to the DB you can flip the flag:
```sql
UPDATE user_entity set enabled = true where username = 'the_admin_user';
```
... and restart the server to invalidate the caches (there might be some other ways I don't know)

But this might be really simple to implement (at least the version of the environmental variable) and save a lot of time in those cases (I doubt I'm the only one working with a laptop which might click before reaching the action button

**Comment by vramik** [comment]
Thank you for creating the issue, I believe it might be related to https://github.com/keycloak/keycloak/issues/9829. Please discuss it there.

**Comment by jonkoops** [comment]
@vramik that issue looks to be more about recovery options, but I think that this issue is more about preventing loss of access in the first place. It should be possible for us to detect the admin user and present a confirmation dialog to the user to warn them they are disabling an admin user. Or we could even have some logic to prevent this entirely.

**Comment by brizaldi** [comment]
Agree, a popup dialog to prevent accidental clicking would be helpful
