### ISSUE TITLE
Token Exchange : promote from preview to supported

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#30262]
### Description

Keycloak supported  [RFC 8693 OAuth 2.0 Token Exchange](https://datatracker.ietf.org/doc/html/rfc8693), but it is preview feature.
Also, as [its documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html#_token-exchange) suggested, Keycloak have extended it a little, ignored some of it, and loosely interpreted other parts of the specification.

This task is about promote Token Exchange to supported. We can wait for the feedback from the community. Also we can consider if we should improve something.).

### Resources
 -  [Token Exchange Gap Analysis](https://docs.google.com/document/d/1plbyw5C1W8q6sYolETfoGqHKIrFWjzYio22o9i6yDOk/edit#heading=h.pdk0qkf0dsl)

### Discussion
 - [Token-Exchange Use-cases](https://github.com/keycloak/keycloak/discussions/26502)

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/26435
- [ ] https://github.com/keycloak/keycloak/issues/30358
- [ ] https://github.com/keycloak/keycloak/issues/33239
```

**Comment by antikalk** [comment]
From our perspective there are two issues that could be considered as additional tasks: https://github.com/keycloak/keycloak/issues/28440 and https://github.com/keycloak/keycloak/issues/29313. For the later I mentioned a Use Case here: https://github.com/keycloak/keycloak/discussions/26502#discussioncomment-9678979

**Comment by mposolda** [comment]
Closing this one for now as there is another epic for token-exchange (maybe we will use dedicated epics for internal-internal and others and also possibly for grouping of internal-internal to dedicated groups, but this is not clear yet).
