### ISSUE TITLE
If docs/building.md is serious about the Java version requirement, set it as `<maven.compiler.*>` to not allow lower ones

### ISSUE THREAD

**Issue by lf-** [keycloak/keycloak#30275]
### Description

Quoth `docs/building.md`:

```
Ensure you have JDK 21 (or newer) and Git installed

    java -version
    git --version
```

If this is true, then the build system should not allow a version of Java less than 21. I'm filing this because it should be tracked as something that needs doing. I do notice that Java 21 support was implemented 5 days ago in 262fc09edc5, but nevertheless.

**Comment by lf-** [comment]
cc @mabartos as author of https://github.com/keycloak/keycloak/pull/28518

**Comment by codespearhead** [comment]
As per Keycloak v25.0.0 release notes, this issue should be added to the 26.0.0 milestone:

https://github.com/keycloak/keycloak/blob/7d05a7a013495a8c59c3bdc71a04f743d3391b34/docs/documentation/release_notes/topics/25_0_0.adoc?plain=1#L5-L11

**Comment by mabartos** [comment]
The issue will be resolved as part of the #29927 PR. However, as the JDK 17 is deprecated (but still supported in some manner), these maven properties will be set to 17 for now. Once we drop JDK 17 completely, it can be moved to the 21.

**Comment by mabartos** [comment]
@jonkoops Are you ok to assign the issue to you? Feel free to unassign or make necessary changes.

**Comment by jonkoops** [comment]
Yes, I will take this one :+1:
