### ISSUE TITLE
Following docs/building.md does not create a quarkus-run.jar

### ISSUE THREAD

**Issue by lf-** [keycloak/keycloak#30274]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Following `docs/building.md`, and trying to not build excessive things, since I just want to [test a client side fix](https://github.com/keycloak/keycloak/pull/30273), I run:

```
./mvnw clean install -DskipTests
```

This doesn't actually install a `quarkus/server/target/lib/quarkus-run.jar` file so the subsequent "starting keycloak" section does not work.

I found out later that this is because you have to build quarkus separately, or something like that? I found that the quarkus/README.md has much much more sensible instructions for "just run it in dev please".

### Version

86101b3d1d8af4080a1e07b91cb64425b1e607cd

### Regression

- [ ] The issue is a regression

### Expected behavior

The first command in the building instructions should work, or at least it should have a qualification on it that says you have to also build Quarkus.

### Actual behavior

The necessary file to run the software should be created by the given build instructions.

### How to Reproduce?

Get a fresh clone of Keycloak and read and follow `building.md`.

### Anything else?

Note also that `./mvnw clean install` as stated in the instructions, *itself*, doesn't work because of tests that hit the internet that are broken: https://github.com/keycloak/keycloak/issues/29271, so you have to skip the tests with `-DskipTests` and potentially `-DskipTestsuite` (which I don't know what it does, I would love docs for that).

Finally, it would be really really good to have instructions that say "ok i want to develop `<x>`, how do I set that up to be pleasant?" For example, for `x = admin ui`, *what server build type do I need* to be able to run the admin UI in dev mode?

**Comment by codespearhead** [comment]
@lf- What commands did you run exactly? Because even with your setup mentioned at #30276 , the documented instructions seem to work as expected:

```dockerfile
# docker build --progress=plain -t keycloak-image-30274 .

FROM archlinux:base-devel-20240101.0.204074 as base_os

FROM base_os as install_os_dependencies
RUN pacman -Sy --noconfirm git jdk21-openjdk
ENV JAVA_HOME /usr/lib/jvm/java-21-openjdk
RUN git --version && java -version

FROM install_os_dependencies as clone_keycloak
RUN git clone --depth 1 https://github.com/keycloak/keycloak.git

FROM install_os_dependencies as checkout_keycloak
COPY --from=clone_keycloak /keycloak /keycloak
RUN cd keycloak && git fetch --depth 1 origin 86101b3d1d8af4080a1e07b91cb64425b1e607cd
RUN cd keycloak && git checkout 86101b3d1d8af4080a1e07b91cb64425b1e607cd

FROM install_os_dependencies as download_keycloak_dependencies
COPY --from=checkout_keycloak /keycloak /keycloak
RUN cd keycloak && ./mvnw dependency:go-offline -B

FROM install_os_dependencies as compile_keycloak
COPY --from=download_keycloak_dependencies /root/.m2 /root/.m2
COPY --from=checkout_keycloak /keycloak /keycloak
RUN cd keycloak && ./mvnw clean install -DskipTests

FROM install_os_dependencies as run_keycloak
COPY --from=compile_keycloak /keycloak /keycloak
CMD ["sh", "-c", "git --version && java -version && cd keycloak && java -jar quarkus/server/target/lib/quarkus-run.jar start-dev"]
```

```bash
# docker run --rm keycloak-image-30274

git version 2.45.2
openjdk version "21.0.3" 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9)
OpenJDK 64-Bit Server VM (build 21.0.3+9, mixed mode, sharing)
2024-06-10 04:16:11,865 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-06-10 04:16:13,381 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_926080, Site name: null
2024-06-10 04:16:16,040 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

UPDATE SUMMARY
Run:                        133
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          133

2024-06-10 04:16:22,062 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-06-10 04:16:22,189 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-06-10 04:16:25,127 INFO  [io.quarkus] (main) Keycloak 999.0.0-SNAPSHOT on JVM (powered by Quarkus 3.8.5) started in 22.097s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
2024-06-10 04:16:25,128 INFO  [io.quarkus] (main) Profile dev activated. 
2024-06-10 04:16:25,128 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mssql, jdbc-mysql, jdbc-oracle, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
2024-06-10 04:16:25,135 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

**Comment by lf-** [comment]
I did the following:

```
git clone https://github.com/keycloak/keycloak keycloak2
cd keycloak2
./mvnw clean install -DskipTests
```

then:

```
co/keycloak2 » java -jar quarkus/server/target/quarkus-run.jar
Error: Unable to access jarfile quarkus/server/target/quarkus-run.jar
```

```
co/keycloak2 » java --version
openjdk 21.0.3 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9)
OpenJDK 64-Bit Server VM (build 21.0.3+9, mixed mode, sharing)
```

**Comment by vmuzikar** [comment]
@lf- Thanks for reporting this. I tried to reproduce.

1. Used a clean project, `quarkus/server/target` dir did not exist.
2. Ran `./mvnw clean install -DskipTests`. In the log, I could see `Keycloak Quarkus Server App` (which corresponds to `quarkus/server`) was built:
```
[INFO] Keycloak Quarkus Server App ........................ SUCCESS [  4.823 s]
```
3. Successfully started server as `java -jar quarkus/server/target/lib/quarkus-run.jar start-dev` as specified in the [docs](https://github.com/keycloak/keycloak/blob/250b986bd7911569ba368b0d26e077bd249c6955/docs/building.md?plain=1#L54).

However, I notice in the previous comment you are using a wrong path: `quarkus/server/target/quarkus-run.jar` instead of `quarkus/server/target/lib/quarkus-run.jar`. I assume that's the root cause.

> Note also that `./mvnw clean install` as stated in the instructions, _itself_, doesn't work because of tests that hit the internet that are broken: #29271, so you have to skip the tests with `-DskipTests` and potentially `-DskipTestsuite` (which I don't know what it does, I would love docs for that).
> 
> Finally, it would be really really good to have instructions that say "ok i want to develop `<x>`, how do I set that up to be pleasant?" For example, for `x = admin ui`, _what server build type do I need_ to be able to run the admin UI in dev mode?

I'd suggest opening a separate issue(s) for those.

~invalid
