### ISSUE TITLE
transient users shouldn't have email required

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#30294]
### Description

In keycloak 23 I could without problems use my custom-login provider with transient-users. Since keycloak 24 the authentication-step `Create User If Unique` seems to have changed in a way that a user cannot be added without an email. This is pretty inconvenient for transient-users that do not have an email.
Our example is based on login with electronic identity cards. The temporary username is the unique identifier generated from the eID's data. We have no email and are now forced to implement our own authentication-flow-provider to fix this problem. It would be great if the previous provider from keycloak 23 could be added additionally or even better if the `Create User If Unique` step would be configurable to use either email or username.

**Comment by sschu** [comment]
@Captain-P-Goldfish  I guess this is because the user profile is always enabled since Keycloak 24. It requires, email, firstname and lastname by default. You can change it so these fields are optional.

**Comment by Captain-P-Goldfish** [comment]
thanks, that did the trick :-)
