### ISSUE TITLE
Facebook IDP , creates user with GUID while username is forced to be email.

### ISSUE THREAD

**Issue by dd-platformcy** [keycloak/keycloak#30290]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

User created with username and email as a GUID
1. We have setup Facebook IDP
2. We have email as username (under Realm Settings -> Login)
3. Username is not editable. (Realm settings -> Login)

We have 4 User accounts that have been created with our Facebook IDP and contain a GUID instead of a valid email.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Expected behavior is the user to pass through Review Profile screen when an email is not being fetched by the IDP. 
Never create a user with not a valid email.

### Actual behavior

We have 4 accounts that they have GUIDs as usernames and emails instead of a valid email.

### How to Reproduce?

We couldn't understand how this happened since all our tests, resolve to the Review Profile Screen.
But we can clearly see 4 Accounts that are created with GUID and not valid emails, hence the problem might not be only in the IDP section.

### Anything else?

We need a guard to avoid creating accounts without valid email

**Comment by vramik** [comment]
Thank you @dd-platformcy for the report. Unfortunately I was not able to reproduce the issue. Would you please try to provide some steps?

~missing-info
