### ISSUE TITLE
Upgrade to Keycloak 25 - Table 'USER_CONSENT' is specified twice on MySQL/MariaDB database

### ISSUE THREAD

**Issue by nicolabeghin** [keycloak/keycloak#30300]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When migrating Keycloak from 24.0.x to 25.0.0 running on database MySQL 8 or MariaDB 10.2 the migration `unique-consentuser` fails due to 

`liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-25.0.0.xml::unique-consentuser::keycloak:
keycloak-1  |      Reason: liquibase.exception.DatabaseException: (conn=2816) Table 'USER_CONSENT' is specified twice, both as a target for 'DELETE' and as a separate source for data [Failed SQL: (1093) DELETE FROM keycloak.USER_CONSENT WHERE ID IN ( SELECT uc.ID FROM keycloak.USER_CONSENT uc INNER JOIN ( SELECT CLIENT_ID, USER_ID, MAX(LAST_UPDATED_DATE) AS MAX_UPDATED_DATE FROM keycloak.USER_CONSENT GROUP BY CLIENT_ID, USER_ID HAVING COUNT(*) > 1 ) max_dates ON uc.CLIENT_ID = max_dates.CLIENT_ID AND uc.USER_ID = max_dates.USER_ID AND uc.LAST_UPDATED_DATE = max_dates.MAX_UPDATED_DATE )]`

The SQL is not ok for MySQL/MariaDB

    DELETE FROM keycloak.USER_CONSENT WHERE ID IN ( SELECT uc.ID FROM keycloak.USER_CONSENT uc INNER JOIN ( SELECT CLIENT_ID, USER_ID, MAX(LAST_UPDATED_DATE) AS MAX_UPDATED_DATE FROM keycloak.USER_CONSENT GROUP BY CLIENT_ID, USER_ID HAVING COUNT(*) > 1 ) max_dates ON uc.CLIENT_ID = max_dates.CLIENT_ID AND uc.USER_ID = max_dates.USER_ID AND uc.LAST_UPDATED_DATE = max_dates.MAX_UPDATED_DATE )

since not allowed as per https://mariadb.com/kb/en/e1093/

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Upgrade to 25.0.0 being completed successfully

### Actual behavior

Upgrade to 25.0.0 fails

### How to Reproduce?

Just start a Keycloak 24.x.x running on MySQL/MariaDB db and upgrade to Keycloak 25.0.0

**Comment by nicolabeghin** [comment]
Idea: issue could origin from commit https://github.com/keycloak/keycloak/commit/4bca804d5aa60308415ea5ef2727d3ddc3f7605a

    <changeSet author="keycloak" id="unique-consentuser-mysql">
        <preConditions onSqlOutput="TEST" onFail="MARK_RAN">
            <dbms type="mysql"/>
        </preConditions>
        <customChange class="org.keycloak.connections.jpa.updater.liquibase.custom.JpaUpdate25_0_0_MySQL_ConsentConstraints"/>
        <dropUniqueConstraint tableName="USER_CONSENT" constraintName="UK_JKUWUVD56ONTGSUHOGM8UEWRT"/>
        <addUniqueConstraint columnNames="CLIENT_ID, USER_ID" constraintName="UK_LOCAL_CONSENT" tableName="USER_CONSENT"/>
        <addUniqueConstraint columnNames="CLIENT_STORAGE_PROVIDER, EXTERNAL_CLIENT_ID, USER_ID" constraintName="UK_EXTERNAL_CONSENT" tableName="USER_CONSENT"/>
    </changeSet>

should be

    <changeSet author="keycloak" id="unique-consentuser-mysql">
        <preConditions onSqlOutput="TEST" onFail="MARK_RAN">
            <or>
                <dbms type="mysql"/>
                <dbms type="postgresql"/>
            </or>
        </preConditions>
        <customChange class="org.keycloak.connections.jpa.updater.liquibase.custom.JpaUpdate25_0_0_MySQL_ConsentConstraints"/>
        <dropUniqueConstraint tableName="USER_CONSENT" constraintName="UK_JKUWUVD56ONTGSUHOGM8UEWRT"/>
        <addUniqueConstraint columnNames="CLIENT_ID, USER_ID" constraintName="UK_LOCAL_CONSENT" tableName="USER_CONSENT"/>
        <addUniqueConstraint columnNames="CLIENT_STORAGE_PROVIDER, EXTERNAL_CLIENT_ID, USER_ID" constraintName="UK_EXTERNAL_CONSENT" tableName="USER_CONSENT"/>
    </changeSet>

**Comment by ahus1** [comment]
Involving @sguilhen as the original change was in #14793. 

There is already a PR, maybe you can help with reviewing the PR created for this. I'm also a bit confused to figure out why this worked in the CI, and now fails in a real environment. Is it due to a table having data (something I've seen with Oracle in the past a lot...)?

**Comment by sguilhen** [comment]
@nicolabeghin It looks like the original PR indeed mixed the DBs (pair should be mariadb/mysql as opposed to postgres/mariadb). When you upgraded, is the changeset mark as ran in the databasechangelog table? Just wondering if fixing the changeset is enough or if we need a new one to properly run the migration.

**Comment by sguilhen** [comment]
@ahus1 @nicolabeghin  Just notice the version used here - per https://www.keycloak.org/server/db Keycloak supports MariaDB 10.11+, and in this version the query runs fine without any errors. I think this is why our CI didn't catch it.

**Comment by sguilhen** [comment]
Also, the RHBK supported configurations (https://access.redhat.com/articles/7033107) mention versions 10.6 and 10.11 for MariaDB - I've tested with both and the query is supported in both, changeset is applied with no errors. On 10.2 it fails as described, but I think this version is not supported.

**Comment by ahus1** [comment]
According to https://endoflife.date/mariadb, MariaDB stopped support for 10.2 on 23 May 2022. 

Due to that it is not a supported version of MariaDB, I'd suggest closing this issue as "won't fix".

**Comment by nicolabeghin** [comment]
> @nicolabeghin It looks like the original PR indeed mixed the DBs (pair should be mariadb/mysql as opposed to postgres/mariadb). When you upgraded, is the changeset mark as ran in the databasechangelog table? Just wondering if fixing the changeset is enough or if we need a new one to properly run the migration.

<img width="930" alt="image" src="https://github.com/keycloak/keycloak/assets/2743637/fbc75680-5694-4cfb-8a07-a912e4f9cade">
