### ISSUE TITLE
Organization resources in keycloak-admin-client-jee have dependencies on jakarta

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#30308]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

The classes in the JEE admin client module `integration/admin-client-jee` should import `javax.*` packages. However organization related resources seem to import  `jakarta.*` packages. For instance see https://github.com/keycloak/keycloak/blob/main/integration/admin-client-jee/src/main/java/org/keycloak/admin/client/resource/OrganizationIdentityProviderResource.java#L22-L24 or any other `Organization*.java` class inside `admin-client-jee` .

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Classes in JEE admin client import `javax.*` packages and  classes in Jakarta admin client import `jakarta.*` packages.

### Actual behavior

Classes in JEE admin client import `jakarta.*` packages

### How to Reproduce?

See above

### Anything else?

We can fix for organizations classes manually, but can we also prevent this from happen in the future?

**Comment by mposolda** [comment]
Just noticed same issue exists for `ClientTypesResource` as well

**Comment by sguilhen** [comment]
Thanks for spotting this @mposolda ! I will work on a fix!
