### ISSUE TITLE
Upgrade to Keycloak 25 - Events bug in UI

### ISSUE THREAD

**Issue by Yuruh** [keycloak/keycloak#30306]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After Upgrading to keycloak 25, accessing events from the UI makes it crash with this error : 
![image](https://github.com/keycloak/keycloak/assets/13162326/f2e7cd64-d761-483f-a016-067c81ab774a).

This occurs even if events are cleared beforehand

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

It should correctly display events

### Actual behavior

The UI crashes and must be reloaded

### How to Reproduce?

1. Run a vanilla quay.io/keycloak/keycloak:24.0.2
2. Setup user and admin events
3. Update image to quay.io/keycloak/keycloak:25.0.0
4. Go to the events page

**Comment by codespearhead** [comment]
What commands did you run to upgrade your Keycloak instance exactly?

**Comment by ssilvert** [comment]
Looks like something associated with upgrade?  Changing to `core-shared` team.

**Comment by scanopm** [comment]
Similar issue while trying to access the events section after upgrading from the latest 24 release to 25.0.0

error message is:
Cannot destructure property 'rowData' of 'undefined' as it is undefined.

**Comment by mdc-webdb** [comment]
Hi I see the same, but "only" on the master realm looks affected. Switching to another realm and open the events for it will work.

**Comment by manderio** [comment]
Have the same issues in all realms, this is after upgrading in k8s with postgres 16.2 as the database version.

**Comment by rmartinc** [comment]
Moving back to UI. This is not related to upgrade but to the application. To reproduce in plain 25.0.0 without upgrade:

* Enable events:  Realm settings -> User events settings -> Sore events to On (put some expiration 1 day or 1 week).
* Logout and login to generate some events.
* Go to the events and check the error: TypeError: Cannot destructure property 'rowData' of 'undefined' as it is undefined.

The last request I see is the user events which is returned OK and with the exact same data that is returned in 24.x. Moved back to UI. I think this is a regression.
