### ISSUE TITLE
Keycloak 24 identity broker ignores custom callback endpoints

### ISSUE THREAD

**Issue by splatch** [keycloak/keycloak#30309]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

I've started porting [keycloak-discourse](https://github.com/Code-House/keycloak-discourse) identity provider and realized that there is a bug. While earlier releases of KC/resteasy honored  @GET/@POST methods in third party callback class, KC 24 and 25.0.0 fail to detect, and call them.
I've narrowed bug down to `org.jboss.resteasy.reactive.server.handlers.ResourceLocatorHandler#findTarget` which yields empty result with these two releases.

### Version

24.0.5, 25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Custom callback endpoint classes should be supported.

### Actual behavior

Neither of  custom endpoint methods is called.

### How to Reproduce?

- Define IDP with extension which ship custom callback endpoint
- Conduct login through this IDP

Any third party class seem to break the flow. I've compared my implementation with keycloak-appleid integration as well as russian providers published at github - all miss any extra annotations, meaning they will break too.

**Comment by pedroigor** [comment]
@splatch Can you please point to one of these extensions?

**Comment by splatch** [comment]
I gonna check if issue remains with twitter integration. Discourse needs several steps to i stall.
