### ISSUE TITLE
KC 24.0.5 - No cache entries evicted after expired time.

### ISSUE THREAD

**Issue by estoT1** [keycloak/keycloak#30303]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

ISSUE: Cache entries not evited after expiry time.
Only evictions occur after the cache is overflowing.

ENVIRONMENT: 
Version: Keycloak 24.0.5
Keycloak config has 2 changes out of the box:

Cache config:
cache-config-file=cache-ispn.xml
metrics-enabled=true

cache-ispn.xml:

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>
        <metrics names-as-tags="true" />
        <local-cache name="realms" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2" statistics="true">
                <expiration lifespan="10000" interval="500"/>
                <memory max-count="2000"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2" statistics="true">
                <expiration lifespan="10000" interval="500"/>
                <memory max-count="2000"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="1111"/>
        </distributed-cache>
    </cache-container>
</infinispan>

Starting KC24.0.5: ./kc.sh start-dev --log-level="DEBUG,org.infinispan:debug" --log="file"
Metrics while hitting the token endpoint via HTTP:

vendor_statistics_evictions{cache="sessions",cache_manager="keycloak",node="keycloak22-41074"} 934.0
vendor_statistics_evictions{cache="clientSessions",cache_manager="keycloak",node="keycloak22-41074"} 934.0

vendor_configuration_eviction_size{cache="sessions",cache_manager="keycloak",node="keycloak22-41074"} 2000.0
vendor_configuration_eviction_size{cache="clientSessions",cache_manager="keycloak",node="keycloak22-41074"} 2000.0

Stopped the script initiating the sessions.
Waited for 1h. vendor_configuration_eviction_size is still 2000 and vendor_statistics_evictions are unchanged.

What am I missing? Should the expired entries not get evicted by the reaper thread?

Thank you in advance.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Cache entries should be evicted after expired. 

### Actual behavior

Cache entries not evited after expiry time.
Only evictions occur after the cache is overflowing.

### How to Reproduce?

Start Keycloak with the cache XML above, create new sessions against the token endpoint using Python script.
# Keycloak server details
keycloak_url = 'http://localhost:8080/'
realm_name = 'master'
client_id = 'myclientID'
client_secret = 'mysecret'
grant_type = 'password'

# Function to authenticate a user
def authenticate_user(username, password):
    token_url = f'{keycloak_url}/realms/{realm_name}/protocol/openid-connect/token'
    payload = {
        'client_id': client_id,
        'client_secret': client_secret,
        'grant_type': grant_type,
        'username': username,
        'password': password
    }

**Comment by douglasawh** [comment]
Is there anything we could provide to help move this along?

**Comment by pruivo** [comment]
Eviction and expiration are two different processes.

Eviction is a local process to the Keycloak server and is only used to make room for a new key. For example, `<memory max-count="1000"/>` only stores 1000 keys in memory, and if you try to insert a new key, an existing key will be removed from memory to make room for the new key. This is eviction and increments the counters tracked by those metrics. 

Expiration is a cluster-wide process, i.e, all Keycloak servers agree the key is no longer required, based on its lifespan and/or max-idle (depending on whatever is reached first). No metrics are exposed for this event and keys are removed on access or periodically by the reaper.

As a warning, eviction is not recommended (or tested) with replicated or distributed caches in Keycloak 24. You will end up with inconsistent sessions and unknown behavior. You have been warned :smile: 

The behavior you are describing is expected and correct. Hope this explanation helps. @estoT1 @douglasawh

**Comment by ahus1** [comment]
Setting livetime and max count for distributed caches is not supported in Keycloak 24. 

The time entries remain in the cache is determined by the session max idle time and max life time which is configured on a per realm basis. Defining a max count will lead to sessions being dropped unexpectedly while users are still within the idle and max lifetime, so this is neither recommended or supported.

If you are looking reduce your memory footprint, have a look at the preview feature "persistent sessions" which is described in the Keycloak 25 release notes and in our blog post https://www.keycloak.org/2024/06/persistent-user-sessions-in-preview.html

With Keycloak 25 and persistent sessions enabled, the size of the caches for sessions/clientSessions and offlineSessions/offlineClientSessions is automatically configured to hold up to 10000 entries, while all other entries are stored in the database.

**Comment by Subhash027** [comment]
Hello @ahus1,

I have a question regarding the configuration of cache-ispn.xml 
```
<distributed-cache name="clientSessions" owners="2" statistics="true">
    <expiration lifespan="3000"/>
    <memory when-full="REMOVE" max-count="2"/>
</distributed-cache>
```
I am using Keycloak 23.0.4 and have a separate cache configuration file where I've specified the lifespan for clientSessions. However, despite setting the lifespan, it doesn't seem to be working as expected.

While researching, I came across your comment:
`The time entries remain in the cache is determined by the session max idle time and max lifetime, which is configured on a per-realm basis.`
Could you clarify why the lifespan setting for cache expiration is not being applied, and why only the session max time is considered?

I also saw `setting lifespan and max count for distributed caches is not supported in Keycloak 24`. Is this limitation also applicable to Keycloak 23.0.4?

**Comment by ahus1** [comment]
@Subhash027 - please don't raise questions on issues which have been closed a long time ago. Also, KC23 is no longer supported for the community.

Setting expiration for this cache is not supported. Instead, use the realm setting as shown below: 

![image](https://github.com/user-attachments/assets/4dd5885e-d835-44f0-af48-de8766541bd8)

Please direct any further questions to the Keycloak user mailing list.
