### ISSUE TITLE
Hashing Algorithm policy field is a text field instead of a select list

### ISSUE THREAD

**Issue by codespearhead** [keycloak/keycloak#30310]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The bug in question (see number 2 only) was initially reported in #18348 , but since two bugs were reported in the same issue, the issue was closed once the other bug was fixed

![Picture of the issue signaled by number 2](https://user-images.githubusercontent.com/53931519/157789853-6e36c21d-1cbe-4c1c-83b4-69f2ef901322.png)

It's still persists in Keycloak 25.0.0 .

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

`Hashing algorithm` field is a select list. 

### Actual behavior

`Hashing algorithm` field is a text field.

### How to Reproduce?

Go to `Authentication > Policy > Password Policy > Add policy: Hashing algorithm`

### Anything else?

[The logic](https://github.com/keycloak/keycloak/blob/51d80a42d58bc89e740962353c51c633b411929b/js/apps/admin-ui/src/authentication/policies/PolicyRow.tsx#L49) for this form item type might need to be reconsidered

[PatternFly has select lists](https://www.patternfly.org/components/forms/form-select), which is already used in many components of the Admin UI.

**Comment by edewit** [comment]
It wasn't fixed in that issue because this would need a server side change. The policies come from the server and have the form: 
```
configType: "String"
defaultValue: "argon2"
displayName: "Hashing Algorithm"
id: "hashAlgorithm"
multipleSupported: false
```
So to make it a dropdown we would need to know what the options are and that would mean changing what is sent from the server and that change has yet to be made

**Comment by ssilvert** [comment]
I'm going to close this as there is very little chance that it will be supported.  I'll note that the dropdown was also not present in the Admin Console V1.

If someone wants to do the work to expose the available algos, we can reconsider.
