### ISSUE TITLE
Test Wildfly 28 adapters (Galleon pack)

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#30324]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Currently the testsuite only supports the Galleon pack adapters for EAP8 (in internal Jenkins, using `app-server-eap8` profile).

A new profile should be added for testing the Galleon pack with Wildfly 28 in GHA.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by mposolda** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/29922
