### ISSUE TITLE
[io.agroal.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL, keycloak 25.0.0, mysql

### ISSUE THREAD

**Issue by peter-lejon-v** [keycloak/keycloak#30344]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Keycloak can't connect to the database after upgrading to keycloak 25.0.0 using quay.io/keycloak/keycloak-operator:25.0.0

Keycloak resource:

![keycloak-cr](https://github.com/keycloak/keycloak/assets/97440384/d86a5b43-7cd3-4766-873a-43d20f18e9d9)

Error log:

![keycloak-error-log](https://github.com/keycloak/keycloak/assets/97440384/51d4b5f2-910f-4908-bd29-8d8f757e386a)

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak can connect to the database using the given Keycloak CustomResourceDefinition

### Actual behavior

We get `java.lang.RuntimeException: Failed to obtain JDBC connection`

### How to Reproduce?

install keycloak using operator

**Comment by mabartos** [comment]
@peter-lejon-v Could you please provide even the full stack trace for the cause exception `SQLException`?

**Comment by peter-lejon-v** [comment]
Sorry for getting back a bit late. Removing the image spec resolved the issue for some reason. On another note. Would it be possible to add versioned channels to the operator subscription on operatorhub? (like the strimzi operator)

**Comment by brunomedeirosdedalus** [comment]
@peter-lejon-v If you remove the image spec, how did you set the custom image

**Comment by brunomedeirosdedalus** [comment]
Okey, the fix on my case was to use the env variable from the operator to add the custom image:

          env:
            - name: RELATED_IMAGE_KEYCLOAK
              value: ...

**Comment by Eng-Fouad** [comment]
I got the same error. I resolved it by creating an optimized build with specifying the DB vendor:

```
kc.sh build --db=mssql
```
