### ISSUE TITLE
Account Console (v3) no longer highlights the current page in the nav bar

### ISSUE THREAD

**Issue by ReneZeidler** [keycloak/keycloak#30383]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

After updating to 25.0.0, the account console v3 no longer highlights the active page in the nav bar. The class `pf-m-current` and attribute `aria-current="page"` are missing. They were correctly set in Keycloak 24.

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

The current page is highlighted in the nav bar:
![image](https://github.com/keycloak/keycloak/assets/5558742/e108708a-9f3f-4899-9c8c-e2edf7ef4903)

### Actual behavior

The current page is not hightlighted in the nav bar:
![image](https://github.com/keycloak/keycloak/assets/5558742/a29503cc-0503-4ade-9f89-0c6393af3a36)

### How to Reproduce?

1. Open the account console in a Keycloak 25.0.0 installation

### Anything else?

This might be related to the URLs within the account console being changed. They previously used fragments, e.g. `/realms/test-realm/account/#/account-security/signing-in`, while now they are part of the path, e.g. `/realms/test-realm/account/account-security/signing-in`.

Additionally, the link to "Personal info" ends in two slashes:
![image](https://github.com/keycloak/keycloak/assets/5558742/1e41eeee-184c-4ea1-b7ca-1470bd2589b9)
This seems like such a minor thing that I don't want to create a separate issue for it, and can probably be fixed together with this issue.

**Comment by ssilvert** [comment]
What I see is that the highlights work as soon as you go to another menu item.  Also, the double slash doesn't seem to cause any problems.

I'm going to set this to low priority, but we can bump it up if you see a more serious issue.

**Comment by ReneZeidler** [comment]
> What I see is that the highlights work as soon as you go to another menu item. Also, the double slash doesn't seem to cause any problems.

That's just the focus styling when you click/focus a nav link. Clicking anywhere else on the page removes that styling again, and it doesn't tell you anything about which page is currently shown.

The issue is in [this function](https://github.com/keycloak/keycloak/blob/8eda167312fa1b54f320b4b99a442c6d3794162f/js/apps/account-ui/src/root/PageNav.tsx#L119-L125), which determines the value for the `isActive` attribute of the `NavItem`.

The double slash in itself isn't an issue, but would probably also mess up this function if it wasn't already broken (because the actual URL of the personal info page only has one slash).

It's only a minor issue, but maybe confusing for users.

**Comment by jonkoops** [comment]
@ReneZeidler sound like you have a pretty good idea of where this issue is happening, if you have the time to create a PR to fix it we would gladly accept it.

**Comment by ReneZeidler** [comment]
I've created a PR #30403

I was unable to get Playwright working on my machine (se error log, I wasn't able to find any useful info on the error). From a cursory look at the tests I don't think any of them should be affected. I'll have to relay on the CI to run the tests.
<details>
<summary>Playwright error log</summary>
```
  1) [chromium] › account-security/device-activity.spec.ts:5:3 › Sign out test › Sign out one device 

    Test was interrupted.

    Error: browserContext.close: Test ended.
    Browser logs:

    <launching> /home/***/.cache/ms-playwright/chromium-1117/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-XXXXXXgKTXzL --remote-debugging-pipe --no-startup-window
    <launched> pid=18383
    [pid=18383][err] [0613/124730.977038:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=18383][err] [0613/124731.025324:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=18383][err] [0613/124731.025488:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=18383][err] [0613/124731.029455:INFO:config_dir_policy_loader.cc(118)] Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
    [pid=18383][err] [0613/124731.029505:INFO:config_dir_policy_loader.cc(118)] Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
    [pid=18383][err] [0613/124731.033482:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
    [pid=18383][err] [0613/124731.085457:WARNING:sandbox_linux.cc(436)] InitializeSandbox() called with multiple threads in process gpu-process.
    [pid=18383] <gracefully close start>

      40 |       await expect(page2.getByTestId("accountSecurity")).toBeVisible();
      41 |     } finally {
    > 42 |       await context1.close();
         |       ^
      43 |       await context2.close();
      44 |     }
      45 |   });
```
</details>
