### ISSUE TITLE
Keycloak SAML Identity provider - internal server error has occurred

### ISSUE THREAD

**Issue by Krishna-PriyaV** [keycloak/keycloak#30410]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

I updated my keycloak version from 20.0.0 to 24.0.2. We have OIDC and SAML identity providers which are used for client login.
When we try to login a client through saml IDP we get below error.

We are sorry...
An internal server error has occurred.

![image](https://github.com/keycloak/keycloak/assets/129741076/abd16965-aef2-47c6-8aa7-4f7dcb5f4239)

Please find below SAML IDP settings in keycloak:
Note: URLs are blurred for confidentiality.

![1](https://github.com/keycloak/keycloak/assets/129741076/dbe17eed-c316-4f64-b4a4-2f63bd5325b1)

![2](https://github.com/keycloak/keycloak/assets/129741076/974cb085-29f2-4e4c-9fa2-61c822c64d38)

![3](https://github.com/keycloak/keycloak/assets/129741076/e4962fe5-1eeb-4eb8-91b1-ec2a14f9e994)

![4](https://github.com/keycloak/keycloak/assets/129741076/b877103d-5234-46e4-b62e-6f3ed54942bf)

![5](https://github.com/keycloak/keycloak/assets/129741076/1b6bd8a7-fd64-4034-94ad-8a22337f35f5)

![6](https://github.com/keycloak/keycloak/assets/129741076/257ca0c7-b43d-4ccd-b4b9-5861acd86d7b)

![7](https://github.com/keycloak/keycloak/assets/129741076/06d5c1b5-9905-4bdd-934d-8cbeaf078a49)

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The user must log in to the client via the SAMl IDP login.

### Actual behavior

User can't login and getting an internal server error.

### How to Reproduce?

Please use my configuration values.

### Anything else?

OIDC login still works fine after this upgrade.

**Comment by graziang** [comment]
@Krishna-PriyaV Could you please share the exception you have in the log?

**Comment by Krishna-PriyaV** [comment]
Hi @graziang We downgraded our Keycloak to version 20.0.0 and the issue no longer exists. If it happens again, will reopen or create a new bug.
Thank You for the quick response!

**Comment by jonkoops** [comment]
I'd recommend going all the way to 25, as we only maintain the latest stable release.

**Comment by bonnm** [comment]
If SAML IdP based login worked with KC 20 and stopped in higher versions of Keycloak, this change introduced in KC 21 could be the reason:
https://www.keycloak.org/docs/25.0.0/upgrading/#saml-sp-metadata-changes
