### ISSUE TITLE
Migration stuck if versions incompatible

### ISSUE THREAD

**Issue by torvitas** [keycloak/keycloak#30449]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

When performing a keycloak upgrade to a version that has an incompatible infinispan version keycloak is stuck with one of three pods running (on the old version) and with another one (on the new version) being unable to get healthy.

### Version

24.05

### Regression

- [ ] The issue is a regression

### Expected behavior

When performing a keycloak upgrade, the operator is supposed to scale down the keycloak statefulset to one pod (on the new version) to make keycloak perform a database migration on just one pod instead of having multiple pods running. After the pod is back up and healthy the statefulset is scaled back up to three pods.

The described process would make all pods go away and start a new pod on the new version, do the possibly needed migration, and then start another one until all three are running again.

### Actual behavior

When performing a keycloak upgrade, the operator scales down the keycloak statefulset to one pod (on the old version) as soon as this is done it updates the version in the statefulset to the new one and scales it back to three pods.

### How to Reproduce?

Do an upgrade from keycloak v23 to v24 using the operator by changing the image in the keycloak resource.

**Comment by shawkins** [comment]
@torvitas the sequence is supposed to be:

- Scale to 1 (old) node
- Update the statefulset to the new image and desired replica count
- The statefulset controller will take down the existing old node as part of a rolling restart before doing a sequential start of the new nodes to satisfy the scaling.

What you are describing seems to indicate that the statefulset controller is performing the scaling operation in tandem or before the rolling restart. Is the old pod stuck terminating, or does the rolling restart simply seem like it is not being performed?

What kubernetes / openshift version are you on?

cc @vmuzikar

**Comment by s-diez** [comment]
Hi @shawkins,

I'm a colleague of @torvitas. The observed behaviour occurs on Kubernetes EKS version v1.29.4-eks with Keycloak Operator quay.io/keycloak/keycloak-operator:24.0.5.

As far as I understand and can reproduce the following statement is false:

>The statefulset controller will take down the existing old node as part of a rolling restart before doing a sequential start of the new nodes to satisfy the scaling.

Here are some experiments:

Keycloak Resource
```yml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  additionalOptions:
  - name: proxy
    value: edge
  - name: log-level
    value: INFO,org.keycloak.events:DEBUG
  - name: hostname-url
    value: https://keycloak.example
  db:
    host: db.example
    passwordSecret:
      key: password
      name: keycloak-database
    usernameSecret:
      key: username
      name: keycloak-database
  hostname:
    adminUrl: https://admin.example
    strict: true
    strictBackchannel: true
  http:
    httpEnabled: true
    httpPort: 8080
  image: registry.example/iam/keycloak:v2.21.0 # Keycloak 23.0.6
  imagePullSecrets:
  - name: docker-config
  ingress:
    enabled: false
  instances: 3
```
Update the image in the Keycloak resource and let the operator handle statefulset changes (image change from Keycloak v23 to v24):

```bash
kubectl -n keycloak get pod -w --output-watch-events --watch-only

EVENT      NAME         READY   STATUS        RESTARTS   AGE
MODIFIED   keycloak-2   1/1     Terminating   0          83m
MODIFIED   keycloak-2   0/1     Terminating   0          83m
MODIFIED   keycloak-2   0/1     Terminating   0          83m
MODIFIED   keycloak-2   0/1     Terminating   0          83m
DELETED    keycloak-2   0/1     Terminating   0          83m
MODIFIED   keycloak-1   1/1     Terminating   0          82m
MODIFIED   keycloak-1   0/1     Terminating   0          82m
MODIFIED   keycloak-1   0/1     Terminating   0          82m
MODIFIED   keycloak-1   0/1     Terminating   0          82m
DELETED    keycloak-1   0/1     Terminating   0          82m
ADDED      keycloak-1   0/1     Pending       0          0s
MODIFIED   keycloak-1   0/1     Pending       0          0s
MODIFIED   keycloak-1   0/1     ContainerCreating   0          0s
MODIFIED   keycloak-1   0/1     Running             0          9s
MODIFIED   keycloak-1   0/1     Error               0          3m22s
MODIFIED   keycloak-1   0/1     Running             1 (1s ago)   3m23s
```

And the same if updating the statefulset manually:
- Prevent operator interaction: `kubectl -n keycloak scale deployment keycloak-operator --replicas=0`
- Scale statefulset to 1: `kubectl -n keycloak scale statefulset.apps/keycloak --replicas=1`
- Patch image and replicas: `kubectl -n keycloak patch statefulsets.apps/keycloak --patch '{"spec": { "replicas": 3, "template": { "spec": {"containers": [{"name": "keycloak", "image": "registry.example/iam/keycloak:v2.22.0"}]}}}}'`

```bash
kubectl -n keycloak get pod -w --output-watch-events

EVENT      NAME         READY   STATUS    RESTARTS   AGE
ADDED      keycloak-0   1/1     Running   0          6m3s
ADDED      keycloak-1   0/1     Pending   0          0s
MODIFIED   keycloak-1   0/1     Pending   0          0s
MODIFIED   keycloak-1   0/1     ContainerCreating   0          0s
MODIFIED   keycloak-1   0/1     Running             0          8s
```

Conclusion, keycloak-0 is not killed and restarted with the new image but instead the rollout of the new image starts with
the missing replicas (keycloak-1, ...) before then finally refreshing keycloak-0. In both cases, manually through the statefulset or through the operator.

And finally the change in the operator as suggested in the PR (scale to 1 and change image first then scale back)
- `kubectl -n keycloak patch statefulsets.apps/keycloak --patch '{"spec": { "replicas": 1, "template": { "spec": {"containers": [{"name": "keycloak", "image": "harbor.breuni.io/iam/keycloak:v2.22.0"}]}}}}'`
- `kubectl -n keycloak scale statefulset.apps/keycloak --replicas=3`

```bash
kubectl -n keycloak get pod -w --output-watch-events

EVENT      NAME         READY   STATUS    RESTARTS   AGE
ADDED      keycloak-0   1/1     Running   0          24m
ADDED      keycloak-1   1/1     Running   0          10m
ADDED      keycloak-2   1/1     Running   0          9m56s
MODIFIED   keycloak-2   1/1     Terminating   0          10m
MODIFIED   keycloak-2   0/1     Terminating   0          10m
MODIFIED   keycloak-2   0/1     Terminating   0          10m
MODIFIED   keycloak-2   0/1     Terminating   0          10m
DELETED    keycloak-2   0/1     Terminating   0          10m
MODIFIED   keycloak-1   1/1     Terminating   0          10m
MODIFIED   keycloak-1   0/1     Terminating   0          10m
MODIFIED   keycloak-1   0/1     Terminating   0          10m
MODIFIED   keycloak-1   0/1     Terminating   0          10m
DELETED    keycloak-1   0/1     Terminating   0          10m
MODIFIED   keycloak-0   1/1     Terminating   0          24m
MODIFIED   keycloak-0   0/1     Terminating   0          24m
MODIFIED   keycloak-0   0/1     Terminating   0          24m
MODIFIED   keycloak-0   0/1     Terminating   0          24m
DELETED    keycloak-0   0/1     Terminating   0          24m
ADDED      keycloak-0   0/1     Pending       0          0s
MODIFIED   keycloak-0   0/1     Pending       0          0s
MODIFIED   keycloak-0   0/1     ContainerCreating   0          0s
MODIFIED   keycloak-0   0/1     Running             0          2s
MODIFIED   keycloak-0   0/1     Running             0          16s
MODIFIED   keycloak-0   1/1     Running             0          16s
ADDED      keycloak-1   0/1     Pending             0          0s
MODIFIED   keycloak-1   0/1     Pending             0          0s
MODIFIED   keycloak-1   0/1     ContainerCreating   0          0s
MODIFIED   keycloak-1   0/1     Running             0          1s
MODIFIED   keycloak-1   0/1     Running             0          17s
MODIFIED   keycloak-1   1/1     Running             0          17s
ADDED      keycloak-2   0/1     Pending             0          0s
MODIFIED   keycloak-2   0/1     Pending             0          0s
MODIFIED   keycloak-2   0/1     ContainerCreating   0          0s
MODIFIED   keycloak-2   0/1     Running             0          11s
MODIFIED   keycloak-2   0/1     Running             0          29s
MODIFIED   keycloak-2   1/1     Running             0          29s
```

**Comment by shawkins** [comment]
Thank you for showing the behavior in detail. We must have assumed, or previously seen, that the sequential start behavior was based upon the updated spec, not a mixed state. The kubernetes docs only speak to the predecessors being live / ready, so regardless there's no guarentee of that behavior. We'll look to move forward with the pr.
