### ISSUE TITLE
UI theme bug in KC 25.0.0

### ISSUE THREAD

**Issue by SebastEnn** [keycloak/keycloak#30440]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The colors of the select input in Realm Settings -> Localization -> Effective message bundles have some issues when in dark theme.

![image](https://github.com/keycloak/keycloak/assets/103125747/6dbae01e-50c1-4a35-9509-f87a138ac75b)

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Text should be visible (in the right color for the currently active theme) and the select box background also should have the right color.

### Actual behavior

They don't.

### How to Reproduce?

Startup a Keycloak 25.0.0 instance, login to the admin console, navigate to Realm Settings -> Localization -> Effective message bundles and open the select input.

**Comment by agagancarczyk** [comment]
This is also is an issue in Users > User list
 ![Screenshot 2024-06-17 at 12 29 30](https://github.com/keycloak/keycloak/assets/4890675/4261f47c-f81b-4cc5-a9ad-137414d629cb)

Also in Admin & User events
