### ISSUE TITLE
Event type not set in reset-credential flow under some conditions resulting in an error page

### ISSUE THREAD

**Issue by etchepar** [keycloak/keycloak#30453]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We customized our reset-credential flow with a customized authenticator for the first step.
This authenticator can fire some **error** event : context.getEvent().error("My Message");

We noticed that some times those error event trigger an error page and a stacktrace in the logs.
"java.lang.IllegalStateException: Attempted to define event error without first setting the event type"

By looking the stacktrace, we narrow the source to the resetCredentialsGET method of the LoginActionServices class (see https://github.com/keycloak/keycloak/blob/edde31a1caf8679f042bc35ca9bda92096c0782c/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L456)

So if :
1 - the user authentication session is expired in the middle of the reset-credential flow 
2 - the user hit the browser refresh button
3 - the resetPAssword is allowed
then the context's event has **no** event type 
(and the processResetCredential method can fail if an error event is fired)

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The event type must always be set in the reset-credential flow. 
Thus, the calls context.getEvent().error("my message") does not fire an exception.

### Actual behavior

the resetCredentialsGET method of the LoginActionServices class (see https://github.com/keycloak/keycloak/blob/edde31a1caf8679f042bc35ca9bda92096c0782c/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L456) does not always set the eventype of the EventBuilder instance.

### How to Reproduce?

1 - fire a context.getEvent().error("myMsg") in the "authenticate" method of the first authenticator in the reset-credential flow (ResetCredentialChooseUser.java for instance)

2 - start a rest credential flow, pass the first step

3 - wait (or use the current url of the browser in a private browser)

3 - an ionternal server error is fired

**Comment by jonkoops** [comment]
Re-opening this one as a PR is attached to it that just needs to be reviewed by the team.
