### ISSUE TITLE
"Failed to replace entity" with external Infinispan cluster when upgrading to `24.0.5`

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#30451]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Upon upgrading from `24.0.2` to `24.0.5` we encountered high latency and many instances of "Failed to replace entity" warnings. This appears to indicate that Keycloak cannot replace a `AuthenticatedClientSessionEntity`, `UserSessionEntity`, etc. within the maximum number of retries.

### Version

24.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

We expect writes/replacements to the client session and user session caches to occur without any warning with 1 attempt.

### Actual behavior

High latency (~4x normal) in any login/token requests, and the logs are full of these:
- For client sessions:
```
InfinispanChangelogBasedTransaction [WARN] Failed to replace entity '11f2e0c6-7f34-4227-9601-5de6d7696f51' in cache 'clientSessions'. Expected: SessionEntityWrapper{version=ee313c41-dcb6-4dd7-93ed-db85317c83cb, entity=AuthenticatedClientSessionEntity [id=11f2e0c6-7f34-4227-9601-5de6d7696f51], localMetadata={lstr=1718205184}}, Current: SessionEntityWrapper{version=ee313c41-dcb6-4dd7-93ed-db85317c83cb, entity=AuthenticatedClientSessionEntity [id=11f2e0c6-7f34-4227-9601-5de6d7696f51], localMetadata={lstr=1718205184}}
```
- For user sessions:
```
InfinispanChangelogBasedTransaction [WARN] Failed to replace entity '6ce9e0e7-671d-4509-b055-3a88126ae49f' in cache 'sessions'. Expected: SessionEntityWrapper{version=992c7084-f62a-48cd-8479-65400b07f61f, entity=UserSessionEntity [id=6ce9e0e7-671d-4509-b055-3a88126ae49f, realm=8e45fe9a-61e5-4840-abb3-b68323aad8f9, lastSessionRefresh=1718206387, clients=[7eb496ec-01c7-4582-9ace-9f85e7423d85]], localMetadata={lsrr=1718206387}}, Current: SessionEntityWrapper{version=992c7084-f62a-48cd-8479-65400b07f61f, entity=UserSessionEntity [id=6ce9e0e7-671d-4509-b055-3a88126ae49f, realm=8e45fe9a-61e5-4840-abb3-b68323aad8f9, lastSessionRefresh=1718206387, clients=[7eb496ec-01c7-4582-9ace-9f85e7423d85]], localMetadata={lsrr=1718206387}}
```

It appears to be looping through `InfinispanUtil.MAXIMUM_REPLACE_RETRIES` for **all** cache writes/replacements.

### How to Reproduce?

1. Create an external Infinispan cluster (`Infinispan 'Flying Saucer' 14.0.21.Final`) using the [helm chart](https://github.com/infinispan/infinispan-helm-charts). Configure caches, e.g.:
```yaml
cacheContainer:
  caches:
    sessions:
      distributedCache:
        encoding:
          key:
            mediaType: application/x-jboss-marshalling
          value:
            mediaType: application/x-jboss-marshalling
        expiration:
          lifespan: "900000000000000000"
        locking:
          acquireTimeout: "5000"
        mode: SYNC
        owners: "2"
        stateTransfer:
          timeout: "60000"
...
```

2. Configure Keycloak `24.0.2` with a cache config file pointing the caches to the external Infinispan cluster, e.g.:
```xml
...
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
            <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0" cache="sessions" raw-values="true" shared="true" segmented="false" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                    <remote-server host="${env.KC_REMOTE_STORE_HOST}" port="${env.KC_REMOTE_STORE_PORT}"/>
                    <connection-pool max-active="16" exhausted-action="CREATE_NEW"/>
                    <security>
                        <authentication server-name="infinispan">
                            <digest username="${env.KC_REMOTE_STORE_USERNAME}" password="${env.KC_REMOTE_STORE_PASSWORD}" realm="default"/>
                        </authentication>
                    </security>
                </remote-store>
            </persistence>
        </distributed-cache>
...
```

3. Create many client and user sessions.

4. Stop Keycloak and upgrade to `24.0.5` with the same cache config as above.

5. **BAM!** the log barfs with the above

### Anything else?

We have validated that this happens when upgrading from `24.0.2` to `24.0.5`, but *not* when upgrading to `24.0.4`. We believe it may be a regression introduced by the fix for https://github.com/keycloak/keycloak/issues/28466 despite it being a change made to fix a similar bug (https://github.com/keycloak/keycloak/issues/14040#issuecomment-2034148155).

By forking `24.0.4` and cherry picking *only* this commit https://github.com/keycloak/keycloak/pull/29378 we are able to reproduce the behavior.

**Comment by pruivo** [comment]
@xgp a couple of questions... 

* How many Keycloak nodes and how many Infinispan nodes? 
* With Keycloak 24.0.5, are you getting the exception during the import or when creating new sessions?
* How many sessions are being created in step 3?

**Comment by xgp** [comment]
@pruivo Thanks for the fast look:

- We have 6 keycloak nodes (3 for auth and 3 for admin) and 3 infinispan nodes.
- We saw the exception on every new session
- Around 1000 sessions were present before the upgrade. We saw that number increase past 2000 after the upgrade.

**Comment by pruivo** [comment]
@xgp I need more info since I'm unable to reproduce it so far. What endpoint are you invoking to create the sessions? Is it for the same user/client or different? How many operations per second?

**Comment by pruivo** [comment]
If you have a dev/stage environment, you can try to reproduce it with more logging: https://github.com/pruivo/keycloak/commit/345eba5838b67e9d971c6735301bcc702674ba1d

I won't advise using that commit in production since it logs every fail in every iteration.

**Comment by xgp** [comment]
> @xgp I need more info since I'm unable to reproduce it so far. What endpoint are you invoking to create the sessions? Is it for the same user/client or different? How many operations per second?

@pruivo these are normal login sessions that go through a browser authentication flow. It's for many users and the same client. The sessions are creates slowly over a period of hours, the same as the normal user load on the system.

> If you have a dev/stage environment, you can try to reproduce it with more logging

Thanks. Will try and report back.

**Comment by richardalberto** [comment]
I can confirm this issue is still present in keycloak `25.0.2` with an external infinispan `15.0.5.Final` 

```
{"timestamp":"2024-08-07T13:48:54.543380076Z","sequence":32930,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction","level":"WARN","message":"Failed to replace entity '879f92d7-cc49-4988-81d7-a023e8b34114' in cache 'sessions'. Expected: SessionEntityWrapper{version=7bff4130-4024-43ff-9710-e6ef1e636874, entity=UserSessionEntity [id=879f92d7-cc49-4988-81d7-a023e8b34114, realm=8e45fe9a-61e5-4840-abb3-b68323aad8f9, lastSessionRefresh=1723038534, clients=[7eb496ec-01c7-4582-9ace-9f85e7423d85, d559a4c9-6c69-4cf2-876c-bfa6281897e7]], localMetadata={lsrr=1723038534}}, Current: SessionEntityWrapper{version=7bff4130-4024-43ff-9710-e6ef1e636874, entity=UserSessionEntity [id=879f92d7-cc49-4988-81d7-a023e8b34114, realm=8e45fe9a-61e5-4840-abb3-b68323aad8f9, lastSessionRefresh=1723038534, clients=[7eb496ec-01c7-4582-9ace-9f85e7423d85, d559a4c9-6c69-4cf2-876c-bfa6281897e7]], localMetadata={lsrr=1723038534}}","threadName":"executor-thread-1375","threadId":1853,"mdc":{"trace_flags":"01","trace_id":"821a1e94cff0efbc4e9d77f810ea7e72","span_id":"8176d81169c85d30"},"ndc":"","hostName":"keycloak-1","processName":"QuarkusEntryPoint","processId":1}
```

**Comment by mohammedalics** [comment]
same here @richardalberto . Did you mange to fix it?
