### ISSUE TITLE
Missing parameter cryptographic_binding_methods_supported in openid-credential-issuer endpoint

### ISSUE THREAD

**Issue by ttu75** [keycloak/keycloak#30458]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

After I add "cryptographic_binding_methods_supported" in new client's attribute, I don't see this parameter in in openid-credential-issuer endpoint
Look like the vaule of CRYPTOGRAPHIC_BINDING_METHODS_SUPPORTED_KEY is incorrect from this line
https://github.com/keycloak/keycloak/blob/5c0dddd8372f3e39f82524d4cf0fdd48b21d3509/services/src/main/java/org/keycloak/protocol/oid4vc/model/SupportedCredentialConfiguration.java#L45

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Display cryptographic_binding_methods_supported in openid-credential-issuer endpoint

### Actual behavior

Missing cryptographic_binding_methods_supported parameter 

### How to Reproduce?

Add "cryptographic_binding_methods_supported" in new client's attribute, and check this new value is in openid-credential-issuer endpoint

**Comment by mposolda** [comment]
@wistefan @francis-pouatcha @tnorimat What do you think about this one?

**Comment by wistefan** [comment]
@mposolda I'll have a look tomorrow.

**Comment by wistefan** [comment]
The issue was already solved by @francis-pouatcha in https://github.com/keycloak/keycloak/commit/d4797e04a29db387a68efc7a25f65e2ab883b84d

**Comment by francis-pouatcha** [comment]
@mposolda | @ttu75 can you please close this ticket?

**Comment by jonkoops** [comment]
Closing
