### ISSUE TITLE
Error dialog title and description shows property name instead of message

### ISSUE THREAD

**Issue by nmathew98** [keycloak/keycloak#30471]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

<img width="627" alt="image" src="https://github.com/keycloak/keycloak/assets/55116576/af7ab59a-3bcf-4cca-b80f-bd10d64b7851">

### Version

25.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Error message title: `Something went wrong`

Error message body: `Sorry, an unexpected error has occurred.`

Try again button: `Try again`

### Actual behavior

Error message title: `somethingWentWrong`

Error message body: `somethingWentWrongDescription`

Try again button: `tryAgain`

### How to Reproduce?

Was just logging in and out on repeat many times until I encountered the error dialog

### Anything else?

Preview features enabled: `persistent-user-sessions`

**Comment by nmathew98** [comment]
here is a video reproduction, literally just spam logged in and out and refresh until the error dialog kinda showed up

keycloak config is as follows:
<img width="1072" alt="image" src="https://github.com/keycloak/keycloak/assets/55116576/92ae44b9-958a-4d7e-a62c-b267d81e034d">

and dockerfile:
<img width="1213" alt="image" src="https://github.com/keycloak/keycloak/assets/55116576/c59d1980-51a8-4bd1-a0ae-0a466353a6a4">

https://hub.docker.com/layers/skulpture/authnz/dev/images/sha256-7723000a92a0b2a5745a312301caf6e68f54435c71d13d3586d43426f5ca0d22?context=repo


https://github.com/keycloak/keycloak/assets/55116576/66664367-5146-4c13-81d8-6db6df3f3568

**Comment by jonkoops** [comment]
Please provide a [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), that does not include any application specific code. Preferably without any operator or Docker configuration, but just a plain Keycloak server start command. Please also do not use screenshots to share any configurations, but share them as text so they can be copied.

**Comment by nmathew98** [comment]
well feel free to close it because the exact reproduction is log in, out and repeat and refresh a few times until something shows haha

I understand it feels like a bit of waste of time but thought that the i18n text should show instead of showing the property names

anyways:
keycloak version: v25.0
server start command: `start --optimized --proxy-headers xforwarded`

<details>
<summary>Dockerfile</summary>

ARG KEYCLOAK_VERSION

FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as builder

ARG KEYCLOAK_CACHE
ARG KEYCLOAK_CACHE_STACK
ARG KEYCLOAK_FEATURES
ARG KEYCLOAK_DB

# Enable health and metrics support
ENV KC_HEALTH_ENABLED true
ENV KC_METRICS_ENABLED true

ENV KC_CACHE $KEYCLOAK_CACHE
ENV KC_CACHE_STACK $KEYCLOAK_CACHE_STACK
ENV KC_FEATURES $KEYCLOAK_FEATURES
ENV KC_DB $KEYCLOAK_DB

WORKDIR /opt/keycloak

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ADD --chown=keycloak:keycloak https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar /tmp/opentelemetry-javaagent.jar

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
</details>

relevant configuration:
- `KC_CACHE`: `ispn`
- `KC_CACHE_STACK`: `kubernetes`
- `KC_HTTP_ENABLED`: `true`

**Comment by jonkoops** [comment]
Perhaps there are some browser logs that you could share? There must be a request failing to retrieve the translations, and I am curious why.

**Comment by nmathew98** [comment]
lol can't get it to reproduce anymore, if it happens again will paste the logs here

**Comment by strybus** [comment]
thank you very much dude for the solution

**Comment by chauhan2000** [comment]
Hello, does any one knows how to fix this problem

Keycloak comes up with one dialog box something went wrong

**Comment by githubcdr** [comment]
Facing the same issue here after upgrade to v26

**Comment by nmathew98** [comment]
hey there I wasn't able to reproduce it when I wanted to check network requests haha

anyways for the admin ui project:
- the repo is available here: https://github.com/edewit/keycloak-admin-ui
- i18n initialised here: https://github.com/edewit/keycloak-admin-ui/blob/main/apps/admin-ui/src/i18n.ts

**Comment by jinnerbichler** [comment]
Facing the same issue here after upgrade to v26

**Comment by jnsn** [comment]
I was seeing the same issue after upgrading to 26.

Mine was related to the deprecation of certain hostname configuration values in version 25, which have been completely removed.

https://www.keycloak.org/docs/latest/upgrading/#new-hostname-options
https://www.keycloak.org/docs/latest/upgrading/#deprecated-proxy-option
