### ISSUE TITLE
Unable to see option of organization in keycloak 25.0.0

### ISSUE THREAD

**Issue by saurabhmaslekar1** [keycloak/keycloak#30489]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

File: server_admin/topics/organizations/managing-organization.adoc

I am not able to see the option of organization toggle in admin UI with keycloak version 25.0.0 .
![image (4)](https://github.com/keycloak/keycloak/assets/124061205/a85afcf3-1427-4997-b7bb-aeae7c904811)
![image (5)](https://github.com/keycloak/keycloak/assets/124061205/09709394-faf3-4444-b9d1-89e37820af19)

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

If not here, could you please tell me where I may find the organisation toggle option?

### Actual behavior

Unable to see orgnization toggle option.

### How to Reproduce?

I have created my keycloak container through docker compose.

**Comment by jonkoops** [comment]
The organization feature is [in preview](https://www.keycloak.org/server/features#_preview_features), you'll have to enable it when staring the Keycloak server.
