### ISSUE TITLE
VERIFY_PROFILE action is required by default

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#30499]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When logging into Keycloak via an external IDP, the VERIFY_PROFILE action is always triggered (meaning the user is shown his profile data to update).
Even when the action is not "set as default action"

The only way to prevent that from happening is to disable the action entirely in the "required actions" tab in the "authentication" menu.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The VERIFY_PROFILE action should only trigger when explicitly given to a user or when "set as default action".

### Actual behavior

The VERIFY_PROFILE action triggers uppon every IDP login.

### How to Reproduce?

Have the VERIFY_PROFILE action enabled but not  "set as default action".
Log into Keycloak with a new user via an external IDP.
The user is asked to update his profile information (enter all required but not yet filled out profile information)...

**Comment by sschu** [comment]
@ch-lepp This is the expected behaviour since the user profile is always active since Keycloak 24. You can configure your profile to be less strict, e.g. by not requiring firstname, lastname or email to be set or by allowing the usage of unmanaged attributes. Then the the update screen won't show. But the validation itself will always run. Does this work for you?

**Comment by ch-lepp** [comment]
> But the validation itself will always run.

Well, that is not true in the sense that it won't run once I disable the "verify profile" action in the "required actions" tab in the authentication menu.........


Let's talk a bit about UI/UX here:

What good is the "set as default action" switch for the "verify profile" action, if said action is set as default anyway?
Does the switch have any additional effects?

What is the difference between the "verify profile" and the "update profile" action? 
Up until now, we have made the "update profile" action "set as default action". That way, every new user had to provide all required attributes. 
With the "verify profile" action being implicitly set as default, new users now are asked to enter their attributes twice.
We could now of course just edit the "update profile" action and switch off the "set as default action".
However, both actions are actually not identical UX-wise.
The "update profile" action presents a clean form and only if the user does not fill out every required filed, the form will have errors.
The "verify profile" action however starts out with errors for every required field. And that is from an enduser perspective just bad UX......



On a more personal note:
I have a certain understanding for a software trying to be smarter than the average end user.
However, I really don't appreciate software trying to be smarter than an admin user (who supposedly knows what he is doing).
If we would want the "verify profile" action to be a default action, we would set it to be a default action...

**Comment by sschu** [comment]
I agree that the different required actions might be a bit confusing. I am also not sure whether setting VERIFY_PROFILE has any effect. Maybe @pedroigor knows more.

However, what is the behaviour you actually want to achieve, e.g. under which cirumstances should the verification run/not run and show/not show validation errors? Maybe we can get the desired behaviour with the current means and separate improving the UX around the configuration.

**Comment by ch-lepp** [comment]
I want new users, that log in for the first time into keycloak via an external IDP to enter their missing user attributes.
The form presented to the users to enter their attributes should be clean (error free) at first.
Only if the user tries to submit the form without filling every required field, errors should be displayed.

I already achieved this by

1. setting the "required" flag for every required user attribute
2. disabling the "validate profile" action entirely
3. turning on the "set as default action" switch for the "update profile" action


So there is currently actually no immediate issue for me to be solved.
It jused seems to me, that my **disabling the "validate profile" action entirely** solution is a bit hacky.
And that you will prevent me from doing so in future Keycloak releases, if your policy is to have that validation active all the time....

**Comment by sschu** [comment]
Your solution probably means there are ways to enter invalid information if VERIFY_PROFILE is disabled. So you cannot rely 100% on user data being valid.

If I get it right your only problem with VERIFY_PROFILE is the fact that validation errors are rendered immediately? We also stumbled across this problem and implemented a custom required action to circumvent this. Sounds like this should actually be changed upstream.

**Comment by ch-lepp** [comment]
> Your solution probably means there are ways to enter invalid information if VERIFY_PROFILE is disabled. So you cannot rely 100% on user data being valid.

Well, the "update profile" action also validates the submitted data, doesn't it?

**Comment by sschu** [comment]
It does verify. But for example an admin could update a user and bypass validation. Or the user could possibly update his profile using the account api.

**Comment by ch-lepp** [comment]
> It does verify. But for example an admin could update a user and bypass validation. Or the user could possibly update his profile using the account api.

Not really.
The deactivated "verify profile" is really just a user action to be performed immediately after login.
Changing the user profile via API still undergoes the usual verification...

So for example users trying to change their attributes via the account-management-client are still prevented from leaving required fileds empty.
And a realm-admin can via keyclaok admin console empty every required field, even if the "verify profile" action is enabled...

**Comment by ch-lepp** [comment]
I've done some digging into the keycloak code to check what was causing the "Verify Profile" action to be implicitly set as default.

The action has an explicit trigger coded that fires upon every login and results in a frontend user form whenever a user profile is not valid: [source](https://github.com/keycloak/keycloak/blob/57139cbefc0327ab8635b7eb36ddafd1583094b0/services/src/main/java/org/keycloak/authentication/requiredactions/VerifyUserProfile.java#L58)

Now my issue seems actually to be more of a matter of the correct sequence of events.
When a user logs in for the first time via my external IDP, his profile is indeed invalid because his first and last name are missing. However, since I have the "Update Profile" action set as default, the user is immediately asked to provide those missing values, which makes his user profile become valid.
The issue was, that the "Verify Profile" action triggered before the "Update Profile" action and therefor before the user had the chance to provider the missing values.


So the actualy solution for me was to simply switch the priorities of the two actions involved in the process.

Thanks @sschu for having this discussion with me and brainstorming ideas.
My issue is resolved.

**Comment by sschu** [comment]
Please not that you might still run into the issue if you add another required field to your profile - you would have to reassign the UPDATE_PROFILE action to every user somehow.
