### ISSUE TITLE
Nextjs: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by stratusceo** [keycloak/keycloak#30496]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

When I try to use keycloak-js, I either have this issue when I enter `new Keycloak()`: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

Or I've this issue if I remove the "new" and try to launch my app: ReferenceError: window is not defined

### Version

^25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

It should work perfectly to login without the credentials of my client.

### Actual behavior

It throws unexpected errors with `new Keycloak` or with its proper usage (same as in the documentation)

### How to Reproduce?

Follow this [tutorial](https://blog.logrocket.com/implement-keycloak-authentication-react/) or even the [official one](https://www.keycloak.org/docs/latest/securing_apps/index.html#installation) in nextjs in typescript.

**Comment by jonkoops** [comment]
I am unable to reproduce this issue, please provide a [minimal and reproducible](https://stackoverflow.com/help/minimal-reproducible-example) example. From what I am seeing here you are likely running Next.JS in a server context, which is not supported by Keycloak JS.

**Comment by stratusceo** [comment]
didn't find a solution to share a mvp in nextjs typescript quickly but it sounds like this (indeed it should be the server of nextjs but all the solutions i see on the internet gives me the errors said above): https://codesandbox.io/p/sandbox/intelligent-platform-2gvvr3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxj0xssi00062e6gui1uw10h%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxj0xssi00022e6g80zk4j3e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxj0xssi00032e6gflr5oblo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxj0xssi00052e6ghbfpvban%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxj0xssi00022e6g80zk4j3e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxj0xssh00012e6g8i29aiej%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxj10tbx00352e6gpeloezd6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxj0xssi00022e6g80zk4j3e%2522%252C%2522activeTabId%2522%253A%2522clxj10tbx00352e6gpeloezd6%2522%257D%252C%2522clxj0xssi00052e6ghbfpvban%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxj0xssi00042e6g1vvoirmz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxj0xssi00052e6ghbfpvban%2522%252C%2522activeTabId%2522%253A%2522clxj0xssi00042e6g1vvoirmz%2522%257D%252C%2522clxj0xssi00032e6gflr5oblo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxj0xssi00032e6gflr5oblo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by stratusceo** [comment]
idk why but i finally worked. the code example wasn't but then after several edits it worked! thanks anyway :)

**Comment by vladimircuriel** [comment]
> idk why but i finally worked. the code example wasn't but then after several edits it worked! thanks anyway :)

How did you solved it ?
