### ISSUE TITLE
partial_import_test fails randomly

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#30492]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

partial_import_test.spec.ts fails randomly

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

test passes always

### Actual behavior

test fails

### How to Reproduce?

Run the test several times

### Anything else?

https://github.com/keycloak/keycloak/actions/runs/9491970781/job/26175392466?pr=30391
https://github.com/keycloak/keycloak/actions/runs/9545039070/job/26305623158?pr=30319

**Comment by hmlnarik** [comment]
https://github.com/keycloak/keycloak/actions/runs/9545039070/job/26305623158?pr=30319

**Comment by ahus1** [comment]
https://github.com/keycloak/keycloak/actions/runs/9544190058/job/26307834098?pr=30464

**Comment by hmlnarik** [comment]
Caused by: #29619

**Comment by hmlnarik** [comment]
Reopening since this has not been fully fixed in #30199

**Comment by agagancarczyk** [comment]
Maybe this PR will fix it -> https://github.com/keycloak/keycloak/pull/30435
