### ISSUE TITLE
Migration From Version 11.0 to 24.0.4 Fails

### ISSUE THREAD

**Issue by ChristianLohmann** [keycloak/keycloak#30497]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

(The list of areas did not really match my issue)

### Describe the bug

I first tried to migrate  Keycloak from version 11.0 to version 22.0.4 and I stumbled upon the issue of duplicate insertions mentioned in this issue #23220. So I tried to update it from 11.0 to 24.0.4 but the very same issue popped up. I then switched to manual migration mode and let me create the migration SQL [file](https://github.com/user-attachments/files/15871062/keycloak-database-update.sql.zip). There, in the `jpa-changelog-13.0.0.xml::default-roles::keycloak` section: 
```sql 
-- Changeset META-INF/jpa-changelog-13.0.0.xml::default-roles::keycloak
SET SEARCH_PATH TO public, "$user","public";

ALTER TABLE public.REALM ADD DEFAULT_ROLE VARCHAR(255);

-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
INSERT INTO public.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('e36e183c-3f9d-4bdd-bef0-483e22548109', 'master', FALSE, '${role_default-roles-master}', 'default-roles-master', 'master', 'master');

UPDATE public.realm SET DEFAULT_ROLE = 'e36e183c-3f9d-4bdd-bef0-483e22548109' WHERE REALM.ID='master';

INSERT INTO public.COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) SELECT 'e36e183c-3f9d-4bdd-bef0-483e22548109', ROLE_ID FROM public.REALM_DEFAULT_ROLES WHERE REALM_ID = 'master';

INSERT INTO public.COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) SELECT 'e36e183c-3f9d-4bdd-bef0-483e22548109', public.CLIENT_DEFAULT_ROLES.ROLE_ID FROM public.CLIENT_DEFAULT_ROLES INNER JOIN public.CLIENT ON public.CLIENT.ID = public.CLIENT_DEFAULT_ROLES.CLIENT_ID AND public.CLIENT.REALM_ID = 'master';

INSERT INTO public.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('f6d46b9c-015a-4468-87f5-e62e0779b4dd', 'master', FALSE, '${role_default-roles-master}', 'default-roles-master', 'master', 'master');

UPDATE public.realm SET DEFAULT_ROLE = 'f6d46b9c-015a-4468-87f5-e62e0779b4dd' WHERE REALM.ID='master';

INSERT INTO public.COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) SELECT 'f6d46b9c-015a-4468-87f5-e62e0779b4dd', ROLE_ID FROM public.REALM_DEFAULT_ROLES WHERE REALM_ID = 'master';

INSERT INTO public.COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) SELECT 'f6d46b9c-015a-4468-87f5-e62e0779b4dd', public.CLIENT_DEFAULT_ROLES.ROLE_ID FROM public.CLIENT_DEFAULT_ROLES INNER JOIN public.CLIENT ON public.CLIENT.ID = public.CLIENT_DEFAULT_ROLES.CLIENT_ID AND public.CLIENT.REALM_ID = 'master';

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('default-roles', 'keycloak', 'META-INF/jpa-changelog-13.0.0.xml', NOW(), 91, '9:fa8a5b5445e3857f4b010bafb5009957', 'addColumn tableName=REALM; customChange', '', 'EXECUTED', NULL, NULL, '4.25.1', '7669297159');

-- Changeset META-INF/jpa-changelog-13.0.0.xml::default-roles-cleanup::keycloak
SET SEARCH_PATH TO public, "$user","public";
```
you can see that it tries to insert 2 times a role called `master` which fails because of a duplicate primary key. So I commented the second one. The migration script ran fine after that but when the server starts up (with `start`) it throws this error: 
```
2024-06-17 12:18:06,711 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-06-17 12:18:06,711 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Error details:: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.RoleModel.getId()" because the return value of "org.keycloak.models.RealmModel.getDefaultRole()" is null
```

Is there anything i can do to mitigate that issue?

### Version

11

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should upgrade without any issues 

### Actual behavior

Running a newer Keycloak server connected to a DB which was formerly connected to a Keycloak 11.0 does not work out as migration fails because of duplicate DB entries.

### How to Reproduce?

run a Keycloak server with version 11.0 and then connect the DB to a Keycloak server version 24.0.4

**Comment by jonkoops** [comment]
If you are having issues upgrading then I would recommend going from one major to another, rather than several majors at once. There is significant migration that needs to be done between some major versions of Keycloak, so it's not realistic to jump from 11 to 24 all at once. I'd also recommend you try to grab the latest patch version of each major, rather than a `.0.0`.

**Comment by ChristianLohmann** [comment]
Hi @jonkoops unfortunately we cannot do that on production because we are limited to only one version of Keycloak as we are not allowed to pull "arbitrary" images from public docker hub. This version has to be approved  by our principals first.

**Comment by shawkins** [comment]
@ChristianLohmann this looks similar to #17312 - could you see about performing a work around at the database level?

**Comment by ChristianLohmann** [comment]
@shawkins thanks a million! That was indeed the issue.
So in my case the query 
```sql
SELECT realm.ID,realm.NAME,realm.DEFAULT_ROLE,role.NAME
from REALM realm LEFT OUTER JOIN KEYCLOAK_ROLE role ON realm.ID = role.REALM_ID
    AND realm.DEFAULT_ROLE = role.ID;
```
returned (next to the master realm and default role) a custom realm which hasn't set a default role yet. In my case that default role didn't even exist yet.
To create the default role i copied the DDL snippet from the version 13 changelog and adapted it to my needs:

```sql
INSERT INTO public.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('f6d46b9c-015a-4468-87f5-e62e0779b4dd', 'master', FALSE, '${role_default-roles-custom-realm}', 'default-roles-custom-realm', 'custom-realm', 'custom-realm');

UPDATE public.realm SET DEFAULT_ROLE = 'f6d46b9c-015a-4468-87f5-e62e0779b4dd' WHERE REALM.ID='custom-realm';

INSERT INTO public.COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) SELECT 'f6d46b9c-015a-4468-87f5-e62e0779b4dd', ROLE_ID FROM public.REALM_DEFAULT_ROLES WHERE REALM_ID = 'custom-realm';

INSERT INTO public.COMPOSITE_ROLE (COMPOSITE, CHILD_ROLE) SELECT 'f6d46b9c-015a-4468-87f5-e62e0779b4dd', public.CLIENT_DEFAULT_ROLES.ROLE_ID FROM public.CLIENT_DEFAULT_ROLES INNER JOIN public.CLIENT ON public.CLIENT.ID = public.CLIENT_DEFAULT_ROLES.CLIENT_ID AND public.CLIENT.REALM_ID = 'custom-realm';
```
