### ISSUE TITLE
Cannot conditionally create user in First login flow

### ISSUE THREAD

**Issue by RichieB2B** [keycloak/keycloak#30503]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

We want to create new users only if they have a certain SAML attribute. We map the attribute using the "Attribute Importer" which works fine. However, in the "First login flow" the step "Condition - user attribute" only tiggers if the user is created first. Since we conditionally want to create the users this is too late.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

In the "First login flow" the step "Condition - user attribute" should also check the mapped attributes of the current user object, even if that user has not yet been created in the Keycloak database.

### Actual behavior

The mapped user attributes are never matches.

### How to Reproduce?

Create the attached "First login flow":
![image](https://github.com/keycloak/keycloak/assets/1461970/a39c7b4e-c59b-4cb3-a2b2-df2f625c6db4)

**Comment by rmartinc** [comment]
@RichieB2B The `Condition - user attribute` is a conditional step that work on the user assigned in the authentication flow context (see [here](https://github.com/keycloak/keycloak/blob/25.0.0/services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalUserAttributeValue.java#L46)). So, as you have commented, this condition needs a created UserModel and it is working as expected.

Probably you need some customization and using the [authentication SPI](https://www.keycloak.org/docs/latest/server_development/#_auth_spi) to perform your use-case (don't know id just using the JS authenticator is enough, you can investigate that). Maybe adding a custom step that simple returns an error if the SerializedBrokeredIdentityContext does not contain the attribute you are interested in is enough. I have not investigated this too much but my feeling is that you need some customization (custom step or at least a JS script one).

**Comment by RichieB2B** [comment]
Thanks for confirming this is working as designed. I think the feature requested in #30573 will help us: introducing a flow conditional that looks at the authentication attributer rather than the UserModel attributes.

**Comment by rmartinc** [comment]
Thanks @RichieB2B! I'm going to close this one then. The other one is an enhancement and better described. Condition user attribute is working as expected.
