### ISSUE TITLE
Flow steps back when changing locale or refreshing page on "Try another way page"

### ISSUE THREAD

**Issue by MariiaAlekseichuk** [keycloak/keycloak#30520]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Authentication flow shows the previous page when user changes locale or refreshes the page on 'try-another-way' (select-authenticator.ftl) page.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

User stays on the same page

### Actual behavior

User is redirected to the previous page

### How to Reproduce?

1. Configure authentication browser flow with 2 alternative authenticators on the same level
2. User starts this flow
3. User selects one of these authenticators (send OTP by one of the possible ways for example)
4. User clicks on the 'Try another way' link
5. User changes locale or refresh page
6. User is redirected to the previoues page instead of stays on the same page
![5](https://github.com/keycloak/keycloak/assets/14878466/9fe6bb6c-bfda-4a82-9e56-f40ad7f60d83)

**Comment by mposolda** [comment]
@MariiaAlekseichuk Thanks for the report. This is not so important issue, but I ended up fixing it when checked this :-)
