### ISSUE TITLE
Use correct scope within maven-plugin

### ISSUE THREAD

**Issue by MichaelWarnecke** [keycloak/keycloak#30542]
### Description

During the build process of docs/maven-plugin (keycloak-guides-maven-plugin), a warning is generated:

```
[INFO] --- plugin:3.11.0:descriptor (default-descriptor) @ keycloak-guides-maven-plugin ---
[WARNING] 

Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.

The following dependencies are in wrong scope:
 * org.apache.maven:maven-model:jar:3.9.6:compile
 * org.apache.maven:maven-artifact:jar:3.9.6:compile
 * org.apache.maven:maven-core:jar:3.9.6:compile
 * org.apache.maven:maven-settings:jar:3.9.6:compile
 * org.apache.maven:maven-settings-builder:jar:3.9.6:compile
 * org.apache.maven:maven-builder-support:jar:3.9.6:compile
 * org.apache.maven:maven-repository-metadata:jar:3.9.6:compile
 * org.apache.maven:maven-model-builder:jar:3.9.6:compile
 * org.apache.maven:maven-resolver-provider:jar:3.9.6:compile
```

This issue can be readily resolved by setting the dependencies to the `provided` scope.

### Motivation

Fewer warnings in the build process

- simplifies error detection due to reduced clutter.
- leads to fewer errors in the future.

**Comment by MichaelWarnecke** [comment]
Funny enough, it is not that simple. I just tried to implement this and broke the build in the process. The issue arises from the plugin’s use of a class from plexus-utils, which has ceased to be injected since the release of Maven 3.9 (see [Maven Release Notes](https://maven.apache.org/docs/3.9.0/release-notes.html#potentially-breaking-core-changes-if-migrating-from-3-8-x)):

> Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer. See [MNG-6965](https://issues.apache.org/jira/browse/MNG-6965).

This issue has already been noted in discussion #19509.

There are 2 possible solutions:

1. declare an explicit dependency on plexus-utils
2. reimplement the required method

The only instance where this is used is here:

https://github.com/keycloak/keycloak/blob/e89b4182b64802c777b435513db9138ee52e05ec/docs/maven-plugin/src/main/java/org/keycloak/guides/maven/GuideMojo.java#L44

Since this is used to copy some files, I am leaning towards reimplementing this without the need for a dependency. If you agree with this approach, I'd like to give it a shot.

**Comment by jonkoops** [comment]
> Since this is used to copy some files, I am leaning towards reimplementing this without the need for a dependency. If you agree with this approach, I'd like to give it a shot.

This sound good to me @MichaelWarnecke, feel free to shoot us a PR.
