### ISSUE TITLE
Keycloak 25.0.0 does not import client secrets on initial startup

### ISSUE THREAD

**Issue by Nosfistis** [keycloak/keycloak#30543]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

I have an exported test realm configuration that I use for CI purposes. During CI, I spin a keycloak importing that realm configuration, which also includes static client secrets.

In the Keycloak 25.0.0 version, the `--import-realm` imports the client but no longer imports the secret. Exporting the realm including its clients, after creating a new secret for that client shows the secret in the exported json. Which means that only the import does not work.

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Using `--import-realm` with a realm json that includes secrets might contain security risks when done in production, but it is useful in other environments. The realm should be imported as-is, including its clients' secrets.

### Actual behavior

The realm is imported but the secrets are empty.

### How to Reproduce?

Export a realm configuration, including its clients.

Create a new clean Keycloak v25.0.0 instance using `--import-realm` with the realm-export.json mounted in `/opt/keycloak/data/import/realm-export.json`.

**Comment by dasniko** [comment]
I was just curious as I need this regularly in my Keycloak trainings. I tested it in my environment, but it works pretty well, like all the time, my realm-json is imported including the client secrets.
Is there perhaps anything special in your environment, which is not obvious on first sight?
Can you provide a minimal reproducable example on which one can see what you are describing?

**Comment by Nosfistis** [comment]
The realm json I use comes from way back (Keycloak v15 as far as I remember). I try to keep it up to date with the latest changes by exporting and comparing changes made from more recent versions to that file.

Indeed when I create a new Keycloak realm with v24, and export it, everything works.

I have tried exporting just one of my v24 client json, which does not contain the secret, append the secret to that json, and import it to v25, but it does not work.

I have the following two client json files. The first is the one generated when creating a new client with "Client Authentication", "Standard flow" and "Direct access grants" enabled, and its import suceeds:

```JSON
{
  "clientId": "api",
  "name": "",
  "description": "",
  "rootUrl": "",
  "adminUrl": "",
  "baseUrl": "",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "8YkyN5H3EOA6kOM9Hd90i7HOxFoOOovS",
  "redirectUris": [
    "/*"
  ],
  "webOrigins": [
    "/*"
  ],
  "notBefore": 0,
  "bearerOnly": false,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": false,
  "publicClient": false,
  "frontchannelLogout": true,
  "protocol": "openid-connect",
  "attributes": {
    "oidc.ciba.grant.enabled": "false",
    "oauth2.device.authorization.grant.enabled": "false",
    "client.secret.creation.time": "1718836252",
    "backchannel.logout.session.required": "true",
    "backchannel.logout.revoke.offline.tokens": "false"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "defaultClientScopes": [
    "web-origins",
    "acr",
    "roles",
    "profile",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}
```

I have also exported my current configuration from a v24 Keycloak client used for token introspection, which does not succeed in importing the secret:
```JSON
{
  "clientId": "api",
  "name": "Public API",
  "description": "External API",
  "adminUrl": "",
  "surrogateAuthRequired": false,
  "enabled": true,
  "alwaysDisplayInConsole": false,
  "clientAuthenticatorType": "client-secret",
  "secret": "8YkyN5H3EOA6kOM9Hd90i7HOxFoOOovS",
  "redirectUris": [],
  "webOrigins": [],
  "notBefore": 0,
  "bearerOnly": true,
  "consentRequired": false,
  "standardFlowEnabled": true,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": true,
  "serviceAccountsEnabled": false,
  "publicClient": false,
  "frontchannelLogout": false,
  "protocol": "openid-connect",
  "attributes": {
    "saml.force.post.binding": "false",
    "saml.multivalued.roles": "false",
    "post.logout.redirect.uris": "+",
    "oauth2.device.authorization.grant.enabled": "false",
    "backchannel.logout.revoke.offline.tokens": "false",
    "saml.server.signature.keyinfo.ext": "false",
    "use.refresh.tokens": "true",
    "oidc.ciba.grant.enabled": "false",
    "backchannel.logout.session.required": "true",
    "client_credentials.use_refresh_token": "false",
    "require.pushed.authorization.requests": "false",
    "saml.client.signature": "false",
    "id.token.as.detached.signature": "false",
    "saml.assertion.signature": "false",
    "client.secret.creation.time": "1718833627",
    "saml.encrypt": "false",
    "saml.server.signature": "false",
    "exclude.session.state.from.auth.response": "false",
    "saml.artifact.binding": "false",
    "saml_force_name_id_format": "false",
    "tls.client.certificate.bound.access.tokens": "false",
    "saml.authnstatement": "false",
    "display.on.consent.screen": "false",
    "saml.onetimeuse.condition": "false"
  },
  "authenticationFlowBindingOverrides": {},
  "fullScopeAllowed": true,
  "nodeReRegistrationTimeout": -1,
  "defaultClientScopes": [
    "web-origins",
    "roles",
    "profile",
    "email"
  ],
  "optionalClientScopes": [
    "address",
    "phone",
    "offline_access",
    "microprofile-jwt"
  ],
  "access": {
    "view": true,
    "configure": true,
    "manage": true
  }
}
```

**Comment by rmartinc** [comment]
Hi @Nosfistis!

At import time the secret is set [here](https://github.com/keycloak/keycloak/blob/25.0.1/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L566-L583). So, if you check the code, the secret is not set if the client is public or bearer-only. In the snippet you have pasted for the non working is `"bearerOnly": true` and therefore the secret is not assigned. Can you please change bearer-only to false and try again?

The bearer-only clients disappeared from keycloak some time ago (the equivalent now is unchecking all authentication flows). But it's clear that a bearer token in the past should not have any secret, because it is not involved in any authentication flow (it only receives tokens).

**Comment by Nosfistis** [comment]
Hi @rmartinc! Thanks for the answer.

Indeed making the client private makes the import work.

What is the recommended client configuration for simply introspecting a token right now? Creating a client with no authentication flows and enabled client authentication? Would the first json listed cover the very same functionality (as a matter of fact it does).

**Comment by rmartinc** [comment]
> What is the recommended client configuration for simply introspecting a token right now? Creating a client with no authentication flows and enabled client authentication? Would the first json listed cover the very same functionality (as a matter of fact it does).

Yes, exactly, I think if you just need to receive tokens and validate using the introspect endpoint, you configure the client with no checks in the Authentication flow section and a credential (it can be anyone, client secret, jwt,...).

Closing this issue because it was solved using bearerOnly to false.
