### ISSUE TITLE
Authentication Flow Condition : evaluate ACR before authentication

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#30572]
### Description

Hi,
we have a custom authentication provider implemented and my objective now is to select the custom provider based on the received `acr_values` parameter. The idea is to support `acr_values=[low, high]`. Low should e.g. initiate Cookie or Username-Password login and high should inititate an eid-card login.

The current `Conditional - Level of Authentication` is not able to do that because it evaluates always to true if the user is not authenticated yet and I want to evaluate the value before the authentication was processed.

We would also be willing to provide a pull-request for this ourselves.

### Details

The idea is simple. Instead of creating a new Conditional AuthenticationExecution we would like to extend the existing one by a configuration parameter that allows to switch between evaluation of the acr_value parameter before and after authentication.

Is this acceptable?

**Comment by Captain-P-Goldfish** [comment]
Can we start with the implementation here?

**Comment by FrankSch1024** [comment]
This topic was also already discussed here:
https://github.com/keycloak/keycloak/issues/28341

**Comment by Captain-P-Goldfish** [comment]
Due to changes in the workflow we do not need this anymore and thus we are going to close this issue for the moment
