### ISSUE TITLE
get username by email returns multiple users with different email

### ISSUE THREAD

**Issue by employwisegit** [keycloak/keycloak#30580]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

The get user by email api returns mulitple results with different email addresses. For example 
/users?email="abc.paudel@xyz.com.np"
for the above get request I'm getting two emails in return
abc.paudel@xyz.com.np2
abc.paudel@xyz.com.np22

### Version

20.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

/users?email="abc.paudel@xyz.com.np" should always return only users who has exact email match

abc.paudel@xyz.com.np2

### Actual behavior

Returning users with different email addresses

### How to Reproduce?

Create two users using create user api (from UI it will not allow to create such users) with following emails
abc.paudel@xyz.com.np2
abc.paudel@xyz.com.np22

then call api /users?email="abc.paudel@xyz.com.np"
with version 20.0.1 it will return both accounts

**Comment by martin-kanis** [comment]
@employwisegit This is expected. According the API docs email parameter: `A String contained in email, or the complete email, if param "exact" is true`. So if you wish to search for a user by email, provide `exact=true` query parameter.
