### ISSUE TITLE
Remove or deprecate old KEYCLOAK admin properties

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#30658]
KEYCLOAK_ADMIN, KEYCLOAK_ADMIN_PASSWORD, and the associated system properties are no longer needed.

**Comment by ahus1** [comment]
@shawkins - when you deprecate items, do you track their eventual removal in a follow-up issue?

**Comment by shawkins** [comment]
> @shawkins - when you deprecate items, do you track their eventual removal in a follow-up issue?

Captured as #31229
