### ISSUE TITLE
Admin console dev mode broken for non-master realms

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#30660]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

With the new integrated Vite in dev mode, only master realm will work.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Should be able to log in to admin console for a test realm during development.

### Actual behavior

Fails with 403 getting serverinfo.

### How to Reproduce?

1. Start admin development server with `pnpm --filter keycloak-server start --admin-dev`
2. Start vite with `pnpm run dev`
3. Log into master realm and create a test realm called `test`
4. Create a user called `test` and set password.
5. Try to log in to admin console with `http://localhost:8080/admin/test/console/`

Login works, but you get a 403 trying to GET serverinfo

**Comment by jonkoops** [comment]
@ssilvert I don't think this is related to the changes to the dev server, as this issue is also reproducible with a plain Keycloak server. The problem is that in order to call the `/serverinfo` endpoint the user needs to have the `admin` role, so this is a duplicate of #30683.

**Comment by jonkoops** [comment]
Duplicate of #30683
