### ISSUE TITLE
"Session not bound to a realm" when updating User in `KeycloakModelUtils.runJobInTransaction`

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#30664]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

In an implementation of `EventListenerProvider`, when a user attribute update is performed inside a `KeycloakModelUtils.runJobInTransaction` block, it throws a `java.lang.IllegalArgumentException: Session not bound to a realm`. 

### Version

25.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

The user lookup and attribute update should succeed.

### Actual behavior

```
Error updating last-login: java.lang.IllegalArgumentException: Session not bound to a realm
 	at org.keycloak.organization.jpa.JpaOrganizationProvider.getRealm(JpaOrganizationProvider.java:491)
 	at org.keycloak.organization.jpa.JpaOrganizationProvider.isEnabled(JpaOrganizationProvider.java:405)
 	at org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:122)
 	at org.keycloak.storage.UserStorageManager.getUserById(UserStorageManager.java:394)
 	at org.keycloak.models.cache.infinispan.UserAdapter.getUserModel(UserAdapter.java:453)
 	at org.keycloak.models.cache.infinispan.UserAdapter.getDelegateForUpdate(UserAdapter.java:103)
 	at org.keycloak.models.cache.infinispan.UserAdapter.setSingleAttribute(UserAdapter.java:176)
```

### How to Reproduce?

Create an implementation of `EventListenerProvider` with the following code
```java
@Override
public void onEvent(final Event event) {
  KeycloakModelUtils.runJobInTransaction(
      session.getKeycloakSessionFactory(),
      s -> {
        try {
          RealmModel realm = s.realms().getRealm(event.getRealmId());
          UserModel u = s.users().getUserById(realm, event.getUserId());
          u.setSingleAttribute("foo", "bar");
        } catch (Exception e) {
          e.printStackTrace();
        }
      });
}
```

### Anything else?

It looks like the code that is throwing the exception is trying to get the `RealmModel` out of the `KeycloakContext`. https://github.com/keycloak/keycloak/blob/25.0.1/model/jpa/src/main/java/org/keycloak/organization/jpa/JpaOrganizationProvider.java#L488-L494

In implementing `EventListenerProvider`s or using `runJobInTransaction`, I've noticed that getting anything out of the `KeycloakContext` (or indeed, making the generous assumption that it would even be populated) is a risky thing. Given that the upstream methods are all taking the `RealmModel` from as a parameter, shouldn't you be using the passed in `RealmModel` rather than trying to get it from the `KeycloakContext`?

As an aside, I have the `organization` feature disabled, so why is it even calling this?

**Comment by xgp** [comment]
If I do this using the same session, it doesn't throw this error (likely because the `KeycloakContext` got set), but it shouldn't matter if you're passing it in.

**Comment by pedroigor** [comment]
This line `org.keycloak.storage.UserStorageManager.importValidation(UserStorageManager.java:122)` in the stackstrace indicates you have the `organization` feature enabled. See https://github.com/keycloak/keycloak/blob/25.0.1/model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L122.

In regards to the `KeycloakContext`, the session usually operates within the context of a realm. It is safe to assume you have the `realm` set there. Some providers other than the `OrganizationProvider` also expect the realm available from the session and user-code should take this into account when running code in a new session/transaction.

As you can see from `KeycloakModelUtils`, there are methods there that support cloning the original context to propagate it to new sessions.

I think this is something we need to document in migration/upgrade guides once we enable the `organization` feature as supported.

**Comment by xgp** [comment]
Thanks @pedroigor 

> indicates you have the organization feature enabled

Thanks. It was failing in both cases. I think I pasted the wrong stack trace.

> As you can see from KeycloakModelUtils, there are methods there that support cloning the original context to propagate it to new sessions.

So, to clarify, I should call one of these methods inside my `runJobInTransaction` method in order to get the `RealmModel`, etc. populated there?

[cloneContextRealmClientSessionToSession](https://www.keycloak.org/docs-api/25.0.1/javadocs/org/keycloak/models/utils/KeycloakModelUtils.html#cloneContextRealmClientSessionToSession(org.keycloak.models.KeycloakContext,org.keycloak.models.KeycloakSession))([KeycloakContext](https://www.keycloak.org/docs-api/25.0.1/javadocs/org/keycloak/models/KeycloakContext.html) origContext, [KeycloakSession](https://www.keycloak.org/docs-api/25.0.1/javadocs/org/keycloak/models/KeycloakSession.html) targetSession)

[cloneContextRealmClientToSession](https://www.keycloak.org/docs-api/25.0.1/javadocs/org/keycloak/models/utils/KeycloakModelUtils.html#cloneContextRealmClientToSession(org.keycloak.models.KeycloakContext,org.keycloak.models.KeycloakSession))([KeycloakContext](https://www.keycloak.org/docs-api/25.0.1/javadocs/org/keycloak/models/KeycloakContext.html) origContext, [KeycloakSession](https://www.keycloak.org/docs-api/25.0.1/javadocs/org/keycloak/models/KeycloakSession.html) targetSession)

**Comment by pedroigor** [comment]
Yeah, or you can try calling a variant of `runJobInTransaction` that already allows you to pass a `KeycloaContext` instance.

**Comment by xgp** [comment]
Thanks for the help. Closing, but I do think it's confusing to have methods that take a realm as a parameter, but then make an assumption about the realm being set in the `KeycloakContext`. Where do you think that should be documented?

**Comment by pedroigor** [comment]
I understand what you are saying. And if you look at some of our SPIs it is a lot confusing to see the realm being passed over and over while at the same time available from the session.

The reason why we are not using `RealmModel` as a parameter of any of the `OrganizationProvider` interfaces is to make it simpler and aligned with the majority of invocations where providers are operating in the context of a realm. Exceptions should be handled as exceptions and not necessarily force you to design SPIs to explicitly pass a realm to methods given it will be most of the time available from the session at runtime.

The confusion is also in the code as we have provider methods defining the realm as a parameter and others that don't do that. We had some internal discussion about this and we preferred to leverage the context from a session and assume a session is always bound with a realm.

The documentation should be in the migration/upgrade notes and developer guide.

**Comment by MartaGolabek** [comment]
I encouter the same problem with scheduled tasks: https://github.com/keycloak/keycloak/issues/34398 The solutions suggested above don't help in my case.

**Comment by shogunassar** [comment]
I fixed it by adding session context like this:
 KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),  **session.getContext(),** s -> {
               
            });

**Comment by EjaYF** [comment]
> I fixed it by adding session context like this:
> 
> ```
>  KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),  **session.getContext()**,  s -> {
>                
>             });
> ```
> 
> Before:
> 
> ```
> KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),s -> {
>               
>            });
> ```
> 
> After (Fix):
> 
> ```
>  KeycloakModelUtils.runJobInTransaction(session.getKeycloakSessionFactory(),  session.getContext(), s -> {
>                
> 
>             });
> ```

This fixed my problem migrating from keycloak 25.x to 26.x with my own SPI.
