### ISSUE TITLE
A theme called `custom` is displayed as `Custom Attribute...` in the admin console

### ISSUE THREAD

**Issue by DerEnderKeks** [keycloak/keycloak#30663]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When a theme is called `custom`, it is displayed as `Custom Attribute...` in the admin console.

![image](https://github.com/keycloak/keycloak/assets/12559640/4f0db3ec-7b27-49de-be12-21a6c71c1591)

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

The theme should be listed as `custom`.

### Actual behavior

The theme is listed as `Custom Attribute...`.

### How to Reproduce?

* Install Keycloak 25.0.1
* Add a theme called `custom`

**Comment by ssilvert** [comment]
Weird but true.  I have verified this bug.
