### ISSUE TITLE
Sending Mail via SMTP fails, because of "Caused by: jakarta.mail.MessagingException: 501 Syntax: HELO <hostname>"

### ISSUE THREAD

**Issue by ThomasOliver545** [keycloak/keycloak#30673]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We want to send Emails with keycloak and therefore we are trying to set it up with smtp. Our keycloak instance itself is running perfectly.
When we try to send a testmail it always fails with: "Caused by: jakarta.mail.MessagingException: 501 Syntax: HELO ".

I also tried to set a hostname for the mailer via ENV JAVA_OPTS_APPEND="-Dmail.smtp.localhost=myapp.local" and so on.

In Keycloak the "KC_HOSTNAME" is set to our domain, so xxx.com

For the connection in keycloak we are using:
Host: email-smtp.eu-central-1.amazonaws.com
Port: 465
SSL & StartTls ENABLED
Authentication with correct username and password

Keycloak itself is running fine in https Mode and has a certificate.
Some words to our environment:

We are using Keycloak: 25
We deploy to AWS ECS via Terraform
We are using AWS SES for sending Mails (the Testmails from SES itself are working)
Our Domain points to a loadbalancer and there the request is forwarded to our target group
Has anyone an idea what i am doing wrong or has a hint? Thanks :)

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

We await that we are able to connect aws ses service correctly and are able to send mails for passwort resetting etc.

### Actual behavior

We are not able to connect successfully to aws ses from our ecs container, it always fails with: "Caused by: jakarta.mail.MessagingException: 501 Syntax: HELO ".

### How to Reproduce?

Have a running keycloak in aws ecs deployed and try to connect to your aws ses endpoint.

**Comment by shawkins** [comment]
> I also tried to set a hostname for the mailer via ENV JAVA_OPTS_APPEND="-Dmail.smtp.localhost=myapp.local" and so on.

From what I can see in the source it looks like that won't get used unless it's in the property set passed to create the Session. 

That does appear to be one way to address this issue, but for now that would require a custom provider to handle an additional option.

Is it possible to make sure that the machine ip resolves to a hostname https://confluence.atlassian.com/confkb/sending-email-fails-due-to-501-syntax-helo-hostname-error-317950662.html

**Comment by ThomasOliver545** [comment]
further see this discussion here:
@shawkins

**Comment by shawkins** [comment]
@ThomasOliver545 does that mean we can close this issue?

**Comment by ThomasOliver545** [comment]
@shawkins 
Yes, thanks for closing.
