### ISSUE TITLE
Group assignment: Display disabled information from user

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#30682]
### Description

Hi,

When a user is disabled, this information is displayed in the user administration but not in the group assignment. This information is missing at this point and should be added.

### Motivation

It would be helpful to have this information at this point so that disabled users are not accidentally assigned to a group.

### Details

![Screenshot from 2024-06-24 10-06-22](https://github.com/keycloak/keycloak/assets/54103655/2aa29b52-c6e2-4988-bd96-3a2887056597)
![Screenshot from 2024-06-24 10-06-45](https://github.com/keycloak/keycloak/assets/54103655/78679347-b64c-4c11-a86e-84ed83d5c71c)

**Comment by ssilvert** [comment]
I agree.  This would be nice to have.  @npriebe would you be willing to submit a PR for it?

**Comment by npriebe** [comment]
> I agree. This would be nice to have. @npriebe would you be willing to submit a PR for it?

Sure. I'll finish it in the next few days.
