### ISSUE TITLE
Commit proto.lock files to release/26.0 branch

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#30684]
### Description

#30243 was added to ensure that changes to the various protobuf schemas used with Infinispan do not break compatibility between release versions. In order for this to work effectively, we need to update the Keycloak release process so that the `proto.lock` files are generated on every release (by setting `-DcommitProtoLockChanges=true`) and committed back to the `main` and release branch(es).

**Comment by ahus1** [comment]
@ryanemerson - Keycloak 26 has been released. Please perform the updated (even if they are intermediate updates) to ensure we don't break backwards compatibility.
