### ISSUE TITLE
Keycloak Helm 21.4.4 not running successfully behind `path: /keycloak` in `values.yaml`

### ISSUE THREAD

**Issue by aceeric** [keycloak/keycloak#30693]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I do not seem to be able to run the Keycloak Admin UI under a `/keycloak` prefix in a K8s cluster. Looking at the Nginx ingress controller logs I see the first GET from the browser has "/keycloak" in the prefix but thereafter - all resource requests drop that prefix:
```
10.112.25.11 - - [24/Jun/2024:10:56:04 +0000] "GET /keycloak HTTP/2.0" 404 1662 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 702 0.880 [keycloak-keycloak-http] [] 10.42.0.91:8080 1662 0.880 404 1d3c5e4a0036a348c0087a20f5169819
10.112.25.11 - - [24/Jun/2024:10:56:04 +0000] "GET /resources/nbjkg/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css HTTP/2.0" 404 548 "https://ip-10-104-22-161.evoforge.org/keycloak" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 85 0.001 [upstream-default-backend] [] 127.0.0.1:8181 548 0.001 404 33e2e783aa17c95b2ee0bb2bffff7dce
```
With other UIs in k8s that run behind ingress resources - I often see the concept of configuring the web app with a `--baseURL` argument which causes it to make all its embedded resource requests relative to that base URL. I don't see that in Keycloak so far.

Helm values working:
```
  adminIngress:
    enabled: true
    hostname: ip-Z-Z-Z-Z.myco.org
    annotations:
      cert-manager.io/issuer: keycloak-selfsigned-issuer
    tls:
    - hosts:
      - ip-Z-Z-Z-Z.myco.org
  keycloakConfigCli:
    enabled: true
    configuration:
      master.json: |
        {
          "realm" : "master",
          "attributes": {
            "frontendUrl": "https://ip-Z-Z-Z-Z.myco.org"
          }
        }
```

Helm values **not** working:
```
keycloak_values:
  adminIngress:
    enabled: true
    hostname: ip-Z-Z-Z-Z.myco.org
    path: /keycloak
    annotations:
      cert-manager.io/issuer: keycloak-selfsigned-issuer
    tls:
    - hosts:
      - ip-Z-Z-Z-Z.myco.org
  keycloakConfigCli:
    enabled: true
    configuration:
      master.json: |
        {
          "realm" : "master",
          "attributes": {
            "frontendUrl": "https://ip-Z-Z-Z-Z.myco.org/keycloak"
          }
        }
```

Is there an established set of values to be able to run the admin UI below a prefix? Thanks.

### Version

Helm chart 21.4.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Ability to access the admin UI under a prefix.

### Actual behavior

Browser says:
```
We are sorry...
Page not found
```

The `ingress-nginx` controller logs show the `/keycloak` prefix dropping off

### How to Reproduce?

Helm install with "not working" values from above.

**Comment by aceeric** [comment]
This is the latest helm chart available: https://artifacthub.io/packages/helm/bitnami/keycloak ... ?

**Comment by aceeric** [comment]
P.S. found this but - it does not resolve the issue:
```
httpRelativePath: /keycloak
```

**Comment by Romain7495** [comment]
@aceeric you mentionned a bitnami charts, you can create an issue there or deploy keycloak with the offical [k8s operator ](https://www.keycloak.org/operator/installation)

**Comment by aceeric** [comment]
fwiw - I was able to successfully access the admin UI behind path prefix `/keycloak` with these values and chart version 21.4.4:
```
  production: true
  proxy: edge
  httpRelativePath: /keycloak/
  auth:
    adminUser: admin
    adminPassword: adminpass
  adminIngress:
    enabled: true
    hostname: ip-1-1-1-1.foo.org
    path: /keycloak
    annotations:
      cert-manager.io/issuer: keycloak-selfsigned-issuer
    tls:
    - hosts:
      - ip-1-1-1-1.foo.org
  extraEnvVars:
  - name: KC_HOSTNAME_ADMIN_URL
    value: https://ip-1-1-1-1.foo.org/keycloak/
  keycloakConfigCli:
    enabled: true
    configuration:
      master.json: |
        {
          "realm" : "master",
          "attributes": {
            "frontendUrl": "https://ip-1-1-1-1.foo.org/keycloak"
          }
        }
```
Though the chart emanates the stateful set manifest this way:
```
            ...
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://ip-1-1-1-1.foo.org"
            - name: KC_HOSTNAME_URL
              value: "https://ip-1-1-1-1.foo.org"
            - name: KC_HOSTNAME_ADMIN_URL
              value: https://ip-1-1-1-1.foo.org/keycloak/
            ...
 ```
And because of how the yaml parser works, fortunately the second `KC_HOSTNAME_ADMIN_URL` prevails so the chart still needs fixing.
