### ISSUE TITLE
Recovery codes missing from account console

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#30703]
When enabling the recovery codes functionality, it no longer shows up under the Account Console. For details on how to reproduce this follow the steps in [this tutorial](https://www.youtube.com/watch?v=fLzrgwAIR7g) by @dasniko.

**Comment by edewit** [comment]
Had an initial look at this issue and it seems that the backend doesn't include the recovery password in the "credentials" call

**Comment by edewit** [comment]
This is not an issue, the tutorial is missing a step, in order to have the section show up you also need to set the recovery codes in the authentication flow

**Comment by jonkoops** [comment]
Re-opening this as a documentation issue.

**Comment by jonkoops** [comment]
Actually, we can handle this under #30702
