### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak#30717]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

https://access.redhat.com now redirects to https://docs.redhat.com. Entries in our docs need to be updated.

### Version

HEAD

### Regression

- [ ] The issue is a regression

### Expected behavior

ExternalLinksTest should pass.

### Actual behavior

ExternalLinksTest should pass

### How to Reproduce?

cd docs
mvn clean install -Pdocumentation -Dtest=ExternalLinksTest

**Comment by ahus1** [comment]
@douglaspalmer - thank you for this fix. Please also create backports for the branches we currently maintain (25, 24, 22). Thanks!

**Comment by douglaspalmer** [comment]
> @douglaspalmer - thank you for this fix. Please also create backports for the branches we currently maintain (25, 24, 22). Thanks!

Sure thing.
