### ISSUE TITLE
If the user is federated before the broker is associated with an organization this user is not a managed user

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#30744]
Currently, if there are existing federated users in a realm and their identity provider is linked with the organization, those users will automatically be considered managed members.

However, this does not make much sense because these users were not really created in the context of an organization but previously when their identity providers were link linked to any organization.

**Comment by vramik** [comment]
As discussed in private chat ... For now, users federated before the broker is associated with an organization won't become members of the organization.
