### ISSUE TITLE
Can not import another template that is outside current directory

### ISSUE THREAD

**Issue by dr0kz** [keycloak/keycloak#30752]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Template that is outside the current directory can not be resolved properly upon starting the keycloak in a docker.

If imported relatively for example: 
`<#import "../test.ftl" as test>`

 it says:

`keycloak  | 2024-06-25 13:54:03,995 SEVERE [freemarker.runtime] (executor-thread-5) Error executing FreeMarker template: freemarker.core._MiscTemplateException: Template importing failed (for parameter value "../test.ftl"):
keycloak  | Template not found for name "../test.ftl".
keycloak  | Reason given: Backing out from the root directory is not allowed.
keycloak  | The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@55d06c6.
`

If imported absolutely:
`<#import "/custom-themes/common/common-theme/test.ftl" as test>`

it says:

`keycloak  | Caused by: freemarker.core._MiscTemplateException: Template importing failed (for parameter value "/custom-themes/common/common-theme/test.ftl"):
keycloak  | Template not found for name "custom-themes/common/common-theme/test.ftl".
keycloak  | The name was interpreted by this TemplateLoader: org.keycloak.theme.freemarker.DefaultFreeMarkerProvider$ThemeTemplateLoader@5fe8ef36.
keycloak  | 
keycloak  | ----
keycloak  | FTL stack trace ("~" means nesting-related):
keycloak  |     - Failed at: #import "/custom-themes/common/common...  [in template "login.ftl" at line 2, column 1]
keycloak  | ----
`

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The templates are resolved fine and macros can be used.

### Actual behavior

Importing templates out of current directory results with error

### How to Reproduce?

Import a template outside of the current directory

**Comment by troyere** [comment]
This subject should be reopened, we are forced to duplicate code because of that
