### ISSUE TITLE
Invalid UMA 2.0 claim_token_format value for ID token in the documentation

### ISSUE THREAD

**Issue by randomstuff** [keycloak/keycloak#30778]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

The User Manual [claims](https://www.keycloak.org/docs/25.0.0/authorization_services/#_policy_evaluation_overview) that `https://openid.net/specs/openid-connect-core-1_0.html#IDToken` should be used for `claim_token_format` for ID tokens. The correct URI is `http://openid.net/specs/openid-connect-core-1_0.html#IDToken`.

Moreover, `urn:ietf:params:oauth:token-type:id_token` should probably be supported as well (and should probably be used in preference of the other value). This value is defined in the [Token Exchange spec](https://datatracker.ietf.org/doc/html/rfc8693).

See for example https://docs.gravitee.io/am/current/am_devguide_protocols_uma2_overview.html

### Version

25.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The documentation should not mention https://openid.net/specs/openid-connect-core-1_0.html#IDToken which is not recognized. Instead, it should mention http://openid.net/specs/openid-connect-core-1_0.html#IDToken.

In addition, Keycloak should probably accept claim_token_format=urn:ietf:params:oauth:token-type:id_token. The documentation should mention this value and mention http://openid.net/specs/openid-connect-core-1_0.html#IDToken as a legacy/compatibility value.

### Actual behavior

Documentation mentions unsupported `https://openid.net/specs/openid-connect-core-1_0.html#IDToken` value. Using this value results in a invalid_request error:

~~~json
{"error":"invalid_request","error_description":"Claim token format [https://openid.net/specs/openid-connect-core-1_0.html#IDToken] not supported"}
~~~

The implementation does not support `urn:ietf:params:oauth:token-type:id_token` which is more standard. Using this value results in an invalid_request error:

~~~json
{"error":"invalid_request","error_description":"Claim token format [urn:ietf:params:oauth:token-type:id_token] not supported"}
~~~

### How to Reproduce?

~~~sh
curl -D- -X POST \
  http://127.0.0.1:8180/realms/test/protocol/openid-connect/token \
  -H "Authorization: Bearer ${access_token}" \
  --data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
  --data "ticket=$ticket" \
  --data "claim_token_format=https://openid.net/specs/openid-connect-core-1_0.html#IDToken" \
  --data "claim_token=${id_token}"

curl -D- -X POST \
  http://127.0.0.1:8180/realms/test/protocol/openid-connect/token \
  -H "Authorization: Bearer ${access_token}" \
  --data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
  --data "ticket=$ticket" \
  --data "claim_token_format=urn:ietf:params:oauth:token-type:id_token" \
  --data "claim_token=${id_token}"
~~~

I have can provide a working lab for reproducing the issue if needed.

**Comment by pedroigor** [comment]
Makes sense. I think we should then:

* Add support for `claim_token_format` `urn:ietf:params:oauth:token-type:id_token`
* Fix docs to reference format `http://openid.net/specs/openid-connect-core-1_0.html#IDToken` and the new format above.

**Comment by randomstuff** [comment]
See https://github.com/randomstuff/keycloak-uma-test (test_rs_resource.py) for some tests around this topic.

**Comment by randomstuff** [comment]
For reference, the usage of `http://openid.net/specs/openid-connect-core-1_0.html#IDToken`as a `claim_token_format` value *is* [mentioned](https://docs.kantarainitiative.org/uma/wg/rec-oauth-uma-grant-2.0.html#rfc.section.3.3.6) in an (non-normative) example in the UMA 2.0 core specification.
