### ISSUE TITLE
Rendering of granted client scopes in User Consents view broken in Admin UI

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#30772]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Granted client scopes rendering is broken in the user consents view in the admin ui

![image](https://github.com/keycloak/keycloak/assets/314690/d2c04daf-10d6-4df8-9367-c3946d76a7ce)

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Granted client scopes should be rendered as a comma separated list.
In Keycloak 24.0.5 it looks like this:
![image](https://github.com/keycloak/keycloak/assets/314690/92ec6e1e-ed16-4deb-bad0-09a064e30b37)

### Actual behavior

Scope strings are just joined together
![image](https://github.com/keycloak/keycloak/assets/314690/54cf97fd-e046-4897-bdc2-cc312876f799)

### How to Reproduce?

1) Create a dummy realm
2) Enable "Consent required for account console"
3) Login as a user with the account-console
4) Go to the consents tab of the user in the admin ui

**Comment by agagancarczyk** [comment]
@thomasdarimont Thank you for reporting this issue. I have reproduced it and will provide a fix shortly.
