### ISSUE TITLE
Testing connection to ldap on the settings page does not work in 25.0.1

### ISSUE THREAD

**Issue by ihard** [keycloak/keycloak#30821]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Testing connection to ldap on the settings page does not work.

### Version

25.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

success ldap test

### Actual behavior

After pressing the button "Test connection" on the ldap settings page , I get an error in the interface:
`Error when trying to connect to LDAP: 'UnknownError'`
 in the logs:
`{"timestamp":"2024-06-26T16:42:01.048130619+03:00","sequence":681143,"loggerClassName":"org.jboss.logging.Logger","loggerName":"WebApplicationException","level":"DEBUG","message":"Restarting handler chain for exception exception","threadName":"executor-thread-21","threadId":113,"mdc":{},"ndc":"","hostName":"iva-keycloak-test-1","processName":"QuarkusEntryPoint","processId":1,"exception":{"refId":1,"exceptionType":"org.keycloak.services.ErrorResponseException","message":"HTTP 500 Internal Server Error","frames":[{"class":"org.keycloak.services.ErrorResponse","method":"error","line":43},{"class":"org.keycloak.services.ErrorResponse","method":"error","line":36},{"class":"org.keycloak.services.resources.admin.TestLdapConnectionResource","method":"testLDAPConnection","line":96},{"class":"org.keycloak.services.resources.admin.TestLdapConnectionResource$quarkusrestinvoker$testLDAPConnection_d65ae9343a71f2736595679e81594225f9de5d6f","method":"invoke"},{"class":"org.jboss.resteasy.reactive.server.handlers.InvocationHandler","method":"handle","line":29},{"class":"io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext","method":"invokeHandler","line":141},{"class":"org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext","method":"run","line":147},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":582},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2513},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1538},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":1583}]}}`
User synchronization continues to work without errors, the Sync all users button also works.

### How to Reproduce?

On the page for setting up a connection to ldap, click the button "Test connection"

**Comment by pedroigor** [comment]
@ihard The stack trace does not help much. Can you check if the same works in a fresh installation using the same LDAP server?

**Comment by ihard** [comment]
run keycloak in develop mode with root ca certificate for ldaps in directory /tmp/ca/test:
`docker run -v /tmp/ca/test:/opt/keycloak/conf/truststores:ro -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.1 start-dev`
add User federation ldap type in interface  - ldaps://ldaps.mydomain.ru:636 with user for bind svcKeycloakTestBind 
buttons "Test connection" and "Test authentication" - work correctly
save configuration with button "Save"
go to settings User federation > ldap again -  buttons "Test connection" and "Test authentication" broken
export realm setting:
[realm-export-3.json](https://github.com/user-attachments/files/16044126/realm-export-3.json)

**Comment by pedroigor** [comment]
@ihard Are you able to reproduce without using `ldaps`? Trying to correlate this issue with https://github.com/keycloak/keycloak/issues/31001.

**Comment by ihard** [comment]
@pedroigor with ldap://ldap.mydomain.ru:389 problem persists

**Comment by pedroigor** [comment]
@ihard Thanks. I have a hard time reproducing the issue. What I'm doing is basically:

* A brand new distribution
* Create a realm
* Create an LDAP provider, test connections (both with and without credentials), and save
* Edit LDAP provider and try testing connections

The last step does not fail.

I do think there is something else I'm missing so please, let me know if the above steps also fail for you.

**Comment by ihard** [comment]
run Keycloak 
```
docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.1 start-dev
Updating the configuration and installing your custom providers, if any. Please wait.
2024-07-04 19:25:21,475 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 3877ms
2024-07-04 19:25:23,652 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-07-04 19:25:24,152 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_642868, Site name: null
2024-07-04 19:25:24,823 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml

UPDATE SUMMARY
Run:                        133
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          133

2024-07-04 19:25:26,219 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-07-04 19:25:26,247 INFO  [org.keycloak.services] (main) KC-SERVICES0050: Initializing master realm
2024-07-04 19:25:27,395 INFO  [org.keycloak.services] (main) KC-SERVICES0009: Added user 'admin' to realm 'master'
2024-07-04 19:25:27,467 INFO  [io.quarkus] (main) Keycloak 25.0.1 on JVM (powered by Quarkus 3.8.5) started in 5.908s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
2024-07-04 19:25:27,467 INFO  [io.quarkus] (main) Profile dev activated.
2024-07-04 19:25:27,467 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, keycloak, logging-gelf, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2024-07-04 19:25:27,471 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.
```

Goto in Firefox 127.0.2 (64-bit) http://127.0.0.1:8080
enter admin/admin
Then I recorded a video of what was happening on the screen, with error "Error when trying to connect to LDAP: 'UnknownError'" at the very end. 
Github limits the size of the file, I had to squeeze it hard, but it seems you can understand what is happening, if not, I can post it on another resource in better quality.
https://github.com/keycloak/keycloak/assets/3078342/34b77762-2f2a-410b-8c95-d1db90045fb7

**Comment by PiRomant** [comment]
Just upgraded from 24.0.5 to 25.0.1, and LDAP has completely stopped working. Even an unprotected ip:389 throws an `Error when trying to connect to LDAP: 'UnknownError'`
