### ISSUE TITLE
Organization API not available from OpenAPI documentation

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#30832]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

https://github.com/keycloak/keycloak/discussions/8899#discussioncomment-9885965

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Organization API exposed available from OpenAPI docs.

### Actual behavior

Organization API exposed not available from OpenAPI docs.

### How to Reproduce?

https://www.keycloak.org/docs-api/latest/rest-api/index.html

**Comment by Persistent13** [comment]
Are there any docs on how to add these in?
I'd be willing to do the work to add these in since I'm dependent on a library that is built with the openapi definitions and it's missing the organization APIs due to this.

**Comment by gtjaboer** [comment]
@pedroigor any idea when this is available?

**Comment by pedroigor** [comment]
We added this one to our backlog and we will be looking at it before eycloak 26. It should be a wider issue as it might also impact other APIs based on JAX-RS resources added through the `AdminRealmResourceSpi` or even the `RealmResourceSPI`.

**Comment by gtjaboer** [comment]
> We added this one to our backlog and we will be looking at it before eycloak 26. It should be a wider issue as it might also impact other APIs based on JAX-RS resources added through the `AdminRealmResourceSpi` or even the `RealmResourceSPI`.

Do you know @pedroigor if this update will be available in Release 26.0.0? We want to use the organization endpoints in our Keycloak environment from november

**Comment by JIStolk** [comment]
@pedroigor Is there an update for this issue in Keycloak 26?

**Comment by vramik** [comment]
Hello @JIStolk, this issue is not part of the released 26.0.0, current plan is to have it included in the next release [26.1.0](https://github.com/keycloak/keycloak/milestone/55), nothing is of course set in stone :)
