### ISSUE TITLE
Support More Complex Expression in `UserResource.searchByAttributes`

### ISSUE THREAD

**Issue by hantsy** [keycloak/keycloak#30849]
Currently from the documentation `userResource.searchByAttributes` accepts a `key:value` series joined with `spaces`, eg `key1:value1 key2:value2`.

How to process the following cases.

1. Matches value by pattern
2. Test the key in a list value
3. Test if the key(is a collection) contains a value
4. etc.

_Originally posted by @hantsy in https://github.com/keycloak/keycloak/discussions/30847_

**Comment by hantsy** [comment]
For example:
1. `key:in(value)` - key in a collection.
2. `key:contains(value)` - key (a collection) contains an item, or string contains substring, etc.
3. `key:gt(value)` - key greater than value, similarly, `lt`, etc.
4. `key:between(value1, value2)`, key is between value1 and value2, etc.
5. `key:regex(value)` - key matches regex pattern
6. `key:not ....` - `!` or `not` to compute the reverse case.
7. support simple logic expression, `or`, `and` and`()`, eg. `(key1:value1 or key2:not value2) and key3:in(value3)`

**Comment by jonkoops** [comment]
@hantsy please use the regular issue submission proccess so we can triage this, creating an issue from a discussion strips all information needed for triage.
