### ISSUE TITLE
Add Group Support Mapper for User Attributes 

### ISSUE THREAD

**Issue by hantsy** [keycloak/keycloak#30851]
I created an `app_metadata` group for the user attributes that are related to our business logic. 

What I want to map in access token like this.

```json
{
  // other data in token
  "app_metadata": {
    "key1": "value1", 
    "key2": "value2"
  }
}
```
But there is no mapper to map the attributes in this group to access token directly, I have to map then one by one like this.

```json
{

  "key1": "value1", 
  "key2": "value2"
}
```

_Originally posted by @hantsy in https://github.com/keycloak/keycloak/discussions/30848_

**Comment by jonkoops** [comment]
@hantsy please use the regular issue submission proccess so we can triage this, creating an issue from a discussion strips all information needed for triage.
