### ISSUE TITLE
Users.searchByEmail result does not include realmRoles

### ISSUE THREAD

**Issue by hantsy** [keycloak/keycloak#30852]
I connected to admin API by administrator username/password with client `admin-cli`. 

When using the following codes to search a user by email.

```kotlin
realmResource.users().searchByEmail(email, true).firstOrNull()?.let {
    log.debug("found users by email: ${it.realmRoles}")
    // ...
}
```

The `realmRoles` always return `null`.

But when I use get users by id like the following.

```kotlin 
val userResource = realmResource.users().get(id)
val roles = userResource.roles().realmLevel().listAll().map { it.name }
val user = userResource.toRepresentation()
```

The roles is filled as expected here.

_Originally posted by @hantsy in https://github.com/keycloak/keycloak/discussions/30782_

**Comment by jonkoops** [comment]
@hantsy please use the regular issue submission proccess so we can triage this, creating an issue from a discussion strips all information needed for triage.
