### ISSUE TITLE
Add Count Users by Role Name

### ISSUE THREAD

**Issue by hantsy** [keycloak/keycloak#30850]
I want to create a pageable users by role result. but there only has an API of listing users by role.

```kotlin 
realmResource.roles().get(roleName).getUserMembers(offset, limit)
```

Is there an API to count the users?

_Originally posted by @hantsy in https://github.com/keycloak/keycloak/discussions/30785_

**Comment by jonkoops** [comment]
@hantsy please use the regular issue submission proccess so we can triage this, creating an issue from a discussion strips all information needed for triage.
