### ISSUE TITLE
DPoP Keycloak JS Adapter

### ISSUE THREAD

**Issue by hillout** [keycloak/keycloak#30874]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Hi, 

Reading [server_admin_23.0](https://www.keycloak.org/docs/23.0.0/server_admin/) and [server_admin_24.0](https://www.keycloak.org/docs/24.0.0/server_admin/)  I've found the mentions: `Currently, Keycloak client adapters do not support DPoP holder-of-key token verification. Keycloak adapters treat access and refresh tokens as bearer tokens.`  But in the [server_admin_25.0](https://www.keycloak.org/docs/25.0.0/server_admin/) this mention has disappeared. So, I made a conclusion that the [adapter](https://www.npmjs.com/package/keycloak-js) started to support DPoP I can use this feature straight away. 

I started to test this out, I've spun up the keycloak with `-features=dpop` enabled, created a public client and activated `Oauth 2.0 DPoP Bound Access Tokens Enabled` toggle and tried it out, but all I could get is: `{"error":"invalid_dpop_proof","error_description":"DPoP proof is missing"}`. 

Maybe I got it wrong that everything will work under the hood such as  - generating pairs of keys (private/public), signing the jwt with private key and sending all needed info to the Authorization Server (Keycloak) but it's not working this way and I couldn't get any info from the updated [server_admin_25.0](https://www.keycloak.org/docs/25.0.0/server_admin/) despite the fact that now the adapter supports it (indirectly). Can you tell what I missed ? How can I implement this feature using Keycloak TS adapter ? 

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

DPoP works with TS Adapter raight away. 

### Actual behavior

Getting `{"error":"invalid_dpop_proof","error_description":"DPoP proof is missing"}` message. 

### How to Reproduce?

Install keycloak 25.0.1, enable dpop feature, try to use TS Adapter Keycloak with it.

**Comment by rmartinc** [comment]
@hillout I think no work was done to add DPoP to `keycloak.js`. I have checked and the paragraph you have mentioned was removed when the removal of the java adapters (issue #28792). So it was removed because a lot of the adapters were removed ubt it is still true for the `keycloak.js`. I'll try to re-add it just mentioning the `keycloak.js`.

**Comment by hillout** [comment]
@rmartinc hi, thanks for reaching out. Are there any plans to add it for a native work with Keycloak and DPoP enabled?

**Comment by rmartinc** [comment]
No @hillout, there is no plan to add it AFAIK.

**Comment by jonkoops** [comment]
Development on Keycloak JS is currently frozen, we are working on a plan to either improve the code quality, build a new library, or recommend a community established solution. The code quality and test coverage of Keycloak JS is too low to confidently add new features or refactor it.

**Comment by hillout** [comment]
@jonkoops I see. Thanks for the info.

**Comment by pranjaldaffodil** [comment]
> Development on Keycloak JS is currently frozen, we are working on a plan to either improve the code quality, build a new library, or recommend a community established solution. The code quality and test coverage of Keycloak JS is too low to confidently add new features or refactor it.

Is this still the case? Cause if it is, it should be mentioned EVERYWHERE on the [keycloak-js NPM page](https://www.npmjs.com/package/keycloak-js) but it's not. It was also updated 2 months ago so it wouldn't feel outdated at a cursory glance. It's at almost 700K downloads weekly so I would hope that Keycloak keeps updating it regularly and the lack of DPoP support has disappointed me since the support was first added to server.

**Comment by jonkoops** [comment]
No, this is no longer the case. Keycloak JS is under active development, although it is now maintained by me, and mostly in my spare time, as I am not longer part of the Keycloak team.
