### ISSUE TITLE
Fail to select a credential configuration in verifiable credentials 

### ISSUE THREAD

**Issue by ttu75** [keycloak/keycloak#30902]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

When I set up a frontend URL in my realm, the dropdown list of "select a credential configuration" is empty.
This only happens when I setup frontend URL

When I look into the browser log, I see the request to the openid-credential-issuer endpoint with two "//" after frontend URL and realm.
https://xxx/iam//realms/tech-demo/.well-known/openid-credential-issuer

The frontend URL I setup is https://xxx/iam , without "/" at the end.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Be able to see the dropdown list of "select a credential configuration" in account UI when I setup a frontend URL.

### Actual behavior

Fail to display the dropdown list of "select a credential configuration"

### How to Reproduce?

1, setup a frontend URL 
2. login user 
3. click verifiable credentials
4. the dropdown list of "select a credential configuration" is empty

**Comment by francis-pouatcha** [comment]
You need to configure signing service for credential configuration to be active. See method [configureTestRealm](https://github.com/keycloak/keycloak/blob/39100edc1281422399b045012acb3cb27062fbf6/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oid4vc/issuance/signing/OID4VCIssuerEndpointTest.java#L304) in OID4VCIssuerEndpointTest.

You can also have a look at this kcadm based deployment configuration at [1.oid4vci_test_deployment.sh](https://github.com/adorsys/keycloak-ssi-deployment/blob/main/1.oid4vci_test_deployment.sh)

Once clients and signing services are well configured, you can see the credential configuration in the .well-kown/openid-credential-issuer endpoint.

**Comment by francis-pouatcha** [comment]
@mposolda this issue can be closed.

**Comment by ttu75** [comment]
@francis-pouatcha , Thank you for your response. We don't see this error in 25.0.1. We also follow your repo to setup oid4vc to test. Thank you for the details of explanation in your repo.

**Comment by francis-pouatcha** [comment]
@mposolda | @ttu75 can you please close this ticket?
