### ISSUE TITLE
Update Email Action by User does not change username

### ISSUE THREAD

**Issue by schuetm** [keycloak/keycloak#30913]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Hello,
I use the update_email preview feature.
If I have the option "Email as username" and "Email as username" active when changing email, it changes the email but not its username. 
Do I miss something?

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

If the login option "Email as username" is active, when I change the email it must also change the username.

### Actual behavior

If the login option "Email as username" is active, when I change the email I have the old email as username.

### How to Reproduce?

1. Activate the update-email feature
2. Have the login option "email as username" activated
3. Then log in with a user
4. Go to "personnal info" /realms/{REALM}/account
5. Modify Email of user
6. The email has been changed but not the username

**Comment by schuetm** [comment]
It could be fixed in UpdateEmailActionTokenHandler like this. Is this a possible fix or is it not correct?

`    @Override
    public Response handleToken(UpdateEmailActionToken token, ActionTokenContext<UpdateEmailActionToken> tokenContext) {
        AuthenticationSessionModel authenticationSession = tokenContext.getAuthenticationSession();
        UserModel user = authenticationSession.getAuthenticatedUser();

        KeycloakSession session = tokenContext.getSession();

        LoginFormsProvider forms = session.getProvider(LoginFormsProvider.class).setAuthenticationSession(authenticationSession)
                .setUser(user);

        String newEmail = token.getNewEmail();

        UserProfile emailUpdateValidationResult;
        try {
            emailUpdateValidationResult = UpdateEmail.validateEmailUpdate(session, user, newEmail);
        } catch (ValidationException pve) {
            List<FormMessage> errors = Validation.getFormErrorsFromValidation(pve.getErrors());
            return forms.setErrors(errors).createErrorPage(Response.Status.BAD_REQUEST);
        }

        UpdateEmail.updateEmailNow(tokenContext.getEvent(), user, emailUpdateValidationResult);

        if (Boolean.TRUE.equals(token.getLogoutSessions())) {
            AuthenticatorUtil.logoutOtherSessions(token, tokenContext);
        }

        tokenContext.getEvent().success();

        // verify user email as we know it is valid as this entry point would never have gotten here.
        user.setEmailVerified(true);
        **user.setUsername(newEmail); // update username to new email**
        user.removeRequiredAction(UserModel.RequiredAction.UPDATE_EMAIL);
        tokenContext.getAuthenticationSession().removeRequiredAction(UserModel.RequiredAction.UPDATE_EMAIL);
        user.removeRequiredAction(UserModel.RequiredAction.VERIFY_EMAIL);
        tokenContext.getAuthenticationSession().removeRequiredAction(UserModel.RequiredAction.VERIFY_EMAIL);

        AuthenticationSessionModel authSession = tokenContext.getAuthenticationSession();
        String redirectUri = RedirectUtils.verifyRedirectUri(tokenContext.getSession(), token.getRedirectUri(), authSession.getClient());

        return forms.setAttribute("messageHeader", forms.getMessage("emailUpdatedTitle"))
                .setAttribute("pageRedirectUri", redirectUri)
                .setSuccess("emailUpdated", newEmail)
                .createInfoPage();
    }`

**Comment by martin-kanis** [comment]
@schuetm Thanks for the issue. I tried with 25.0.1 and I see a different behavior: 

1. when `email as username` enabled there is no option in the account console to initiate change of email/username. Only option is to assign `UPDATE EMAIL` required action to the user in the admin console. Then, on the next login, the user is asked to update the email and both email and username are updated.
2. when `email as username` is disabled, I see `Update email` option in the account console. Then of course, only email is changed

Am I missing something? 

~invalid
