### ISSUE TITLE
Account v3 - missing password.ftl template

### ISSUE THREAD

**Issue by lucas9122** [keycloak/keycloak#30923]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

There is a password.ftl template in account version 1, which allows users to change their passwords (it is available at the URL: ...account/password), but it is missing in version 3 of the account theme

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

There supposed to be a password page allows users to change its passwords

### Actual behavior

There is no such template

### How to Reproduce?

Navigate to the account version 3 environment.
Go to the same URL: localhost:8080/realms/myrealm/account/password
Check if the password.ftl template is present.

**Comment by edewit** [comment]
it's not part of the account console, it's part of the login it's called `login-update-password.ftl` you can update the password by going to the account console and selecting account security and then signing then press the button "update" next to "password":

![image](https://github.com/keycloak/keycloak/assets/51133/510b04d7-c0e4-45bd-a4ae-fe211aa6fe76)

**Comment by lucas9122** [comment]
@edewit So what was the purpose behind account/password.ftl if there was already login-update-password.ftl? These two templates are different, by the way. I'm curious because I am working on a simple custom account theme from scratch with two views: personal-info and password.

**Comment by lucas9122** [comment]
@edewit  but I've been thinking about creating an account theme app in React from scratch, extending only the base for messages. Additionally, I will add a Password.tsx template to the app to achieve the similar results to V1, but I wonder is it a good idea

**Comment by edewit** [comment]
In that case you can also use the account ui as a npm module you can use the locale selector component and the user profile inputs as a component. See the [quickstart](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-admin-console-node) for an example
