### ISSUE TITLE
Drop and merge offline session caches

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#30932]
### Description

Drop the offline session and offline client session caches. 

This data can be stored in the online sessions cache using composite keys.

### Discussion

https://github.com/keycloak/keycloak/discussions/30532

### Acceptance criteria

* In scope is the remote only Infinispan (new style), and embedded caches are out of scope
* Out of scope: docs (as everything is still experimental)
* Test suite should run in KCB and in Keycloak to accept the new compound keys (offline flag + UUID key)

### Motivation

The motivation is to reduce the number of caches to configure and try to reduce the amount of memory (each cache has its overhead).
Use cases like removing realm or users will require fewer network calls due to the number of caches it needs to check.

### Details

Composite key, using tuple `<uuid, offline>`, will help identify if the session is online or offline.

**Comment by ahus1** [comment]
Closed, see comments in the PR. There still seems to be good reasons to keep those two caches apart.
