### ISSUE TITLE
Email as Username for Account creation gives duplicate Errors.

### ISSUE THREAD

**Issue by satyamdafero** [keycloak/keycloak#30933]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Hi,

I have selected the option to use "Email as Username" for user registration.
But if the user does not fill the email/username, i am getting error message for both the fields.
I should be getting the error message for only missing email.

### Version

v24

### Regression

- [ ] The issue is a regression

### Expected behavior

Only one error message should be thrown for missing email. Does not make sense to show error message for both email and username.

### Actual behavior

Both validation messages are returned :
- "Please specify Email"
- "Please specify Username"

### How to Reproduce?

1. Set login option as : "Email as username".
2. Register a new user.
3. Leave the Email field empty
4. Submit

**Comment by raff897** [comment]
Sorry, if i create a new user in admin panel and there is Email as username enabled it throws only one error.
When i do it from the registration panel it highlights only the incorrect fields. 

![Immagine 2024-06-28 202925](https://github.com/keycloak/keycloak/assets/85362193/e0935e98-38d2-4f5f-a639-69b3eff21545)
![rpanel](https://github.com/keycloak/keycloak/assets/85362193/91fafeee-361a-4518-bc5c-587d17c72786)
