### ISSUE TITLE
Keycloak operator adds proxy by default which is depreacted

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak#30945]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

The operator adds by default : 
https://github.com/keycloak/keycloak/blob/287916997e76642bd68e3069f0b0da1884b1daac/operator/src/main/java/org/keycloak/operator/Constants.java#L50
This feature is deprecated and breaks my deployment even though I am using hostname:v2 which in the docs:
https://www.keycloak.org/server/hostname#_using_edge_tls_termination
 doesn't specify that I need to use neither proxy nor proxy-headers. (as the hostname is strict).
 This breaks the config and I am unable to use keycloak. The only fix was adding:
 ```
  additionalOptions:
  - name: proxy
    value: edge
 ```

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Operator not to break config and use deprecated feature.

### Actual behavior

Operator forces me to use KX_PROXY=edge which deprecated.

### How to Reproduce?

1. install the oprator
2. create a keycloak CRD
3. view the logs: 
    > The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
        - proxy: Use proxy-headers.
4. and check that unless you override edge with passthourgh you can not use TLS termination with hostname:v2

**Comment by shawkins** [comment]
This does appear to be an edge case that isn't covered by the operator logic - no pun intended. The operator will remove the proxy option only if the proxy-headers are set, which they won't be in this case.

~priority-important

**Comment by shawkins** [comment]
@vmuzikar I had marked this as important because there isn't a clear workaround other than to keep using hostname v1 options. 

A possible pr was opened, but it requires a url be used for the hostname - which would probably need to be documented. Let me know if you want to do anything here, or just wait until v1 is removed.

**Comment by vmuzikar** [comment]
I would remove rather `--proxy` in 26. It's been deprecated since 24 so should be safe to do even from the RHBK perspective.

**Comment by shawkins** [comment]
@vmuzikar ok, so on main we'll just remove the operator's usage of proxy completely. Do you want to consider the pr for 24/25, or just resolve this issue by relying on the workaround of specifying proxy=edge?

**Comment by yelhouti** [comment]
@shawkins does you PR by any chance remove the proxy even if it is also specified in an env variable. this could be the case if the user is using hostname:v1 with tls termination.

**Comment by shawkins** [comment]
@vmuzikar full hostname v1 removal isn't currently slated until KC 27 - #27731

@yelhouti the change will only remove the proxy setting if the hostname is a url - which is only valid for hostname v2.

**Comment by vmuzikar** [comment]
> Do you want to consider the pr for 24/25, or just resolve this issue by relying on the workaround of specifying proxy=edge?

I would not change 24/25 behaviour. The deprecated message is [documented](https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option).

Thinking about it more, I believe we could just remove the default `proxy=passthrough` value from the Operator, and leave removal of the whole `--proxy` option to later when we remove Hostname v1. The default `proxy=passthrough` was needed for Hostname v1 (it did not accept any proxy headers just slightly changed the hostname behaviour). Now that v2 is the default, I think we don't need it anymore. We'd just document it in the upgrading guide.

**Comment by shawkins** [comment]
> The deprecated message is [documented](https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option).

It's not just that there's a deprecation warning, it's that for this scenario you also need to set proxy=edge.

> Now that v2 is the default, I think we don't need it anymore. We'd just document it in the upgrading guide.

Seems fine for main along with the upgrade note.

**Comment by sathieu** [comment]
@Pepo48 Will this change be backported to v25.x?

**Comment by shawkins** [comment]
@sathieu not the entire change, just a doc note about using proxy=edge if proxy-headers can't be used.
