### ISSUE TITLE
Unrecognized field "organizationsEnabled" using keycloak-adapter-core

### ISSUE THREAD

**Issue by Chrispie** [keycloak/keycloak#30956]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

We are using the `org.keycloak:keycloak-adapter-core:24.0.5`  and `org.keycloak:keycloak-admin-client:24.0.5` library. 

We are trying to upgrade to 25.x  but there is no version 25 of the `keycloak-adapter-core` lib.
So we are running:
- `org.keycloak:keycloak-adapter-core:24.0.5`  
- `org.keycloak:keycloak-admin-client:25.0.1`

When we execute `Keyloak.realms().findAll()` we get an exception: `Unrecognized field "organizationsEnabled"`

This is a similar issue to https://github.com/keycloak/keycloak/issues/30293.

Are there any plans to upgrade the `keycloak-adapter-core`  to be version 25 compatible?

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

`org.keycloak:keycloak-admin-client` be compatible with  `org.keycloak:keycloak-adapter-core:25.x`

### Actual behavior

Cannot upgrade `org.keycloak:keycloak-admin-client` to version 25 and version 24 is not compatible with version 25.

### How to Reproduce?

Gradle project with the following 2 libararies
`org.keycloak:keycloak-adapter-core:24.0.5`  
`org.keycloak:keycloak-admin-client:25.0.1` 

Calling  `Keyloak.realms().findAll()` results in the error.

**Comment by vramik** [comment]
Hello @Chrispie, this behavior is expected, it is not possible to mixup different versions of `keycloak-admin-client` and Keycloak server. 

`keycloak-adapter-core` module was removed within https://github.com/keycloak/keycloak/issues/28791. The adapters was deprecated in Keycloak 19 and now finally removed in Keycloak 25. See https://github.com/keycloak/keycloak/issues/28774 for more details.
