### ISSUE TITLE
metrics endpoint response "Resource not found" on management interface

### ISSUE THREAD

**Issue by potterhe** [keycloak/keycloak#30954]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I read the following documents, but I did not get the Prometheus format metrics at the "/metrics" path of the management port, and the HTTP request responded with `<html><body><h1>Resource not found</h1></body></html>`

- https://www.keycloak.org/server/management-interface
- https://www.keycloak.org/server/configuration-metrics

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

response  prometheus format metrics

### Actual behavior

```
$ curl http://localhost:9000/metrics
<html><body><h1>Resource not found</h1></body></html>
```

### How to Reproduce?

Follow the actions described in the following two documents

- https://www.keycloak.org/server/management-interface
- https://www.keycloak.org/server/configuration-metrics

**Comment by shawkins** [comment]
Please include all of the relevant configuration options you used to start the server.

**Comment by kuon** [comment]
I have the same issue with this configuration:

```
# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
db=postgres

# The username of the database user.
db-username=keycloak

# The password of the database user.
#db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
#db-url=jdbc:postgresql://localhost/keycloak

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
proxy-headers=xforwarded
http-enabled=true

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
hostname=auth.goyman.com
http-port=9040
https-enable=false
http-enable=true
http-management-port=9042
spi-theme-welcome-theme=goyma
```
