### ISSUE TITLE
ProviderConfigProperty.URL_TYPE does not work as expected

### ISSUE THREAD

**Issue by mnlipp** [keycloak/keycloak#30950]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

The SPI offers `ProviderConfigProperty.URL_TYPE`. Though not stated explicitly, it's a reasonable assumption that using this results in an input field for the property that somehow supports the input of an URL

However, when using this, you get the help text as URL instaed.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Allows you to edit the property as URL ("text field" with whatever support for URLs is intended)

### Actual behavior

Hows help text as link.

### How to Reproduce?

Try it.

**Comment by pedroigor** [comment]
Not sure if I'm following the description. Is it related to https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/components/dynamic/UrlComponent.tsx?

Moving to @keycloak/ui-maintainers as it seems related to how that component property is rendered.

**Comment by mnlipp** [comment]
It's related to writing an extension using the SPI (which doesn't exist in the "area" drup-doen). See https://github.com/mnlipp/keycloak-moodle-auth/blob/f260685e38c9470c1cc3a620cfd20e6295a15c6a/org.jdrupes.keycloak.moodleauth/src/org/jdrupes/keycloak/moodleauth/MoodleAuthenticatorFactory.java#L99 for an example.

**Comment by ssilvert** [comment]
@mnlipp Can you post a screen shot?

Also, are you able to use ProviderConfigProperty.STRING_TYPE as a workaround?

**Comment by mnlipp** [comment]
Using URL_TYPE:

![image](https://github.com/keycloak/keycloak/assets/1446020/a1cccc32-755a-454a-90f7-c684574e9132)

Text shown as link is the help text.

Using STRING_TYPE (only change):

![image](https://github.com/keycloak/keycloak/assets/1446020/7bca156d-1046-48e7-b5e4-7a99fd77892b)

Using https://github.com/mnlipp/keycloak-moodle-auth 013e124e0883413f07a541560d6fd2563a42c297

**Comment by ssilvert** [comment]
This appears to be working as designed.  See https://github.com/keycloak/keycloak/issues/27673

**Comment by mnlipp** [comment]
If this is intended to display a URL instead of providing an input field for a URL then this should at least be mentioned in the comment for the constant.

**Comment by ssilvert** [comment]
> If this is intended to display a URL instead of providing an input field for a URL then this should at least be mentioned in the comment for the constant.

You are probably right.  If you want to submit a PR, we can reopen this.
