### ISSUE TITLE
Keycloak is not working in IBM AIX OS.

### ISSUE THREAD

**Issue by ashirvadgupta** [keycloak/keycloak#30967]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

In AIX, If I try to run kc.sh, it's throwing me errors about _cygpath not found_ . I was able to fix it by adding double square brackets wherever we are checking for empty or null values.

For example, 
Changing 
_if [ -z "$JAVA_OPTS" ]; then_ 
to
_if [[ -z "$JAVA_OPTS" ]]; then_ 

I want keycloak should embrace this change and fix it.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Script should work for AIX too.

### Actual behavior

Script isn't working for AIX.

### How to Reproduce?

Just run the _kc.sh start-dev_

**Comment by shawkins** [comment]
@ashirvadgupta the kc.sh script needs to remain posix compliant. Double square brackets are bash specific. What shell are you using on AIX? Let's see if we can come up with something that is portable.

**Comment by ashirvadgupta** [comment]
@shawkins I tried initially with default shell. It didn't work. Then I tried with bash. Same errors both the time.

**Comment by ashirvadgupta** [comment]
> @ashirvadgupta the kc.sh script needs to remain posix compliant. Double square brackets are bash specific. What shell are you using on AIX? Let's see if we can come up with something that is portable.

@shawkins I tried initially with default shell. It didn't work. Then I tried with bash. Same errors both the time.
It will be better if we have something which works in both.

**Comment by ashirvadgupta** [comment]
@shawkins I tried running bash on posix mode, still getting same error.

**Comment by shawkins** [comment]
> It will be better if we have something which works in both.

We won't try to have a script that works on all shells / OS combintations. 

We just need it to run in posix mode. If you are still having an issue in posix mode with bash, then we can see if there is additional portable changes needed - or if something we're doing isn't currently posix compatible.

**Comment by ashirvadgupta** [comment]
> > It will be better if we have something which works in both.
> 
> We won't try to have a script that works on all shells / OS combintations.
> 
> We just need it to run in posix mode. If you are still having an issue in posix mode with bash, then we can see if there is additional portable changes needed - or if something we're doing isn't currently posix compatible.

I am getting same errors with POSIX mode on as well.

**Comment by shawkins** [comment]
> I am getting same errors with POSIX mode on as well.

Ok, so look for a modification to the script that is posix complaint and works for you.

**Comment by ashirvadgupta** [comment]
> > I am getting same errors with POSIX mode on as well.
> 
> Ok, so look for a modification to the script that is posix complaint and works for you.

its only working if if put double brackets in if empty or if null conditions

**Comment by shawkins** [comment]
You can try some of the alternatives mentioned on https://stackoverflow.com/questions/19783948/portable-way-to-check-emptyness-of-a-shell-variable - again it needs to be posix compliant.

**Comment by shawkins** [comment]
> @shawkins Can you add this change in keycloak

Yes - all of those tests should have the variables quoted.

**Comment by ashirvadgupta** [comment]
Thank you @shawkins
