### ISSUE TITLE
FIPS 14.0.3 support (KeyFactor is sunsetting bcfips v1, after 1.0.2.5)

### ISSUE THREAD

**Issue by mamccorm** [keycloak/keycloak#30964]
### Description

Keycloak currently supports FIPS 140-2, by leveraging bcfips (v1.x), and have a published doc on how to configure:
 - https://www.keycloak.org/server/fips

As bcfips v1.x only supports JDK17 as it's most recent, then this does require pinning to JDK17 in KeyCloak. Note this is a separate issue we've already [filed here](https://github.com/keycloak/keycloak/issues/30415), so not going into specifics.

Note that bcfips v1.x is going to sunset soon, the current certified release is 1.0.2.4, and v1.0.2.5 is pending, and will be the last patch release before bcfips v2.x comes.

Is Keycloak working to validate and support bcfips v2.x, and FIPS 140-3, prior to it becoming GA?

### Motivation

Keycloak supports FIPS 140-2 via bcfips, but v1 of bcfips will be sunsetting after the next 1.0.2.5 patch release, meaning Keycloak must support bcfips v2, and FIPS 140-3.

**Comment by mamccorm** [comment]
bcfips 2.0 (FIPS 140-3 support), is now GA. bcfips V1.0 cert expires in a couple of weeks. Any plans to support bcfips 2.0?

**Comment by codespearhead** [comment]
@mamccorm Should this be closed now that https://github.com/keycloak/keycloak/pull/33213 is merged?
