### ISSUE TITLE
Brute force protection: Lockout permanently uses parameters configured under lockout temporarily

### ISSUE THREAD

**Issue by dominiktopp** [keycloak/keycloak#30969]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Configure Brute force protection in a Realm:

1. Choose mixed mode and set wait increment to 0
2. save
3. Choose lockout permanently mode and set e.g. max login failes 10, quick login check millis 0, minimum quick login wait empty
4. save
Result: realm.getMaxTemporaryLockouts() == 0 and realm.getWaitIncrementSeconds() == 0

Now login with wrong password 10 times and observe that the user is NOT disabled.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

User gets locked

### Actual behavior

User does not get locked

### How to Reproduce?

see description

### Anything else?

DefaultBruteForceProtector (hat commit 6a22f31b812ce68735373b1a0b047b75958f0b64 = tag 25.0.1)
- line 119: user gets locked
- line 113: therefore user must have numTemporaryLockouts (=0) > realm.getMaxTemporaryLockouts() (=0)
- line 99: would have incremented numTemporaryLockouts but only if waitSeconds > 0

Why are parameters of temporary lockout relevant for permanent lockout? You can't even configure those when choosing permanent lockout mode.

Workaround: use reproduction steps but set wait increment to at least 1 sec.

**Comment by mposolda** [comment]
@douglaspalmer Do you have a chance to triage this and doublecheck if this is expected behaviour or something can be improved?
