### ISSUE TITLE
OIDC Authentication Flow Fails to Maintain Session Persistence for Custom Authenticator

### ISSUE THREAD

**Issue by alaa60** [keycloak/keycloak#30979]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When implementing a custom authenticator within an OIDC authentication flow, the user session fails to persist across requests, resulting in inconsistent authentication state and repeated challenges.
This issue prevents the implementation of multi-step authentication flows that require session persistence, particularly affecting scenarios like Two-Factor Authentication (2FA) in OIDC flows.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The authentication session should persist throughout the OIDC flow, maintaining the user's authentication state and completed steps.

### Actual behavior

When using OIDC authentication, the session fails to persist across page refreshes or subsequent requests. Each new request results in the creation of a new authentication session, as indicated by changing tab IDs in the Keycloak logs. This causes the authentication flow to restart from the beginning, losing all progress and state information from previous steps. Consequently, users are unable to complete multi-step authentication processes, as they are treated as new, unauthenticated visitors with each request to the OIDC endpoint.

### How to Reproduce?

1. Configure a custom authenticator in the authentication flow for the account console.
2. Attempt to access the Keycloak Account Console (this will automatically initiate the OIDC authentication flow).
3. In the custom authenticator, add code to store a value in the authentication note: context.getAuthenticationSession().setAuthNote("TEST_NOTE", "test_value");
4. Refresh the page in the browser.
5. Observe that testNote is null, indicating the authentication session was not preserved.

### Anything else?

To partially solve this problem in my custom Email OTP SPI, I implemented a solution that transfers the authentication flow from OIDC to a regular authentication flow when an OIDC endpoint is detected.

```
String requestPath = context.getUriInfo().getPath();
String authPath = "/realms/" + context.getRealm().getName() + "/protocol/openid-connect/auth";

if (requestPath.equals(authPath)) {
    logger.debug("User accessing via OIDC authorization endpoint, transferring to regular authentication flow for 2FA.");

    // Construct URL for email OTP challenge
    UriBuilder uriBuilder = context.getUriInfo().getBaseUriBuilder()
        .path("realms").path(context.getRealm().getName())
        .path("login-actions").path(AUTHENTICATE_PATH);

    uriBuilder.queryParam(Constants.EXECUTION, context.getExecution().getId());
    uriBuilder.queryParam(Constants.CLIENT_ID, context.getAuthenticationSession().getClient().getClientId());
    uriBuilder.queryParam(Constants.TAB_ID, context.getAuthenticationSession().getTabId());

    URI redirectUri = uriBuilder.build();

    Response challenge = Response.seeOther(redirectUri).build();
    context.challenge(challenge);
    return;
}

// Regular authentication flow
initiateEmailChallenge(context, null);
```

**Comment by rmartinc** [comment]
Hi @alaa60!

I have done a quick test and I can set an auth note in a custom authenticator. If I refresh the value in the page of the challenge I can get the note.

The auth session is managed in a cookie called AUTH_SESSION_ID (and AUTH_SESSION_ID_LEGACY although the latter will be removed someday). With the value the authentication session is retrieved from the infinispan cache. Which for the case of auth sessions is distributed if in cluster. So you can check if the cookies are sent correctly by the browser and the infinispan cache is working OK.

What is your setup (cluster, lodalhost,...)? Can you test in a fresh 25.0.1?

I'm attaching my simple authenticator. It's just something I did for another thing so it's a bit messy. Just compile it and put in the providers folder.

```bash
mvn clean package
cp target/custom-form-authenticator.jar ${KEYCLOAK_HOME}/providers
````

Then just copy default browser and add the custom authenticator inside the copy of the browser forms at the end (the last step to execute). This way when you login the last step is accepting the Terms and Conditions with the custom auth. If you click decline, the auth note is added to the session. If you click decline again you will see the value=value is printed in the log as set. If you refresh the page, the same, the value is there.

Note that a lot of default authenticators are adding notes, for example the remember me, the level of authentication,... So it's strange that this was not maintained as it's used a lot.

[keycloak-custom-authenticator.zip](https://github.com/user-attachments/files/16111650/keycloak-custom-authenticator.zip)

**Comment by rmartinc** [comment]
Hi @alaa60!

We cannot test exactly your environment as you are using custom extensions. So we cannot know the reason without an exact reproducer. As I commented, keycloak relies on the fact that the session is maintained and it's like this in all the default authenticators in the software. I have also shown to you that a custom authenticator also maintains the session. Please check my first comment (cookies and so on and forth) and try to understand what is happening in your environment.

So the summary of this issue is that we cannot reproduce it.
