### ISSUE TITLE
Localization: Long message key values not editable or deletable

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#30987]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Message texts which exceeds the screen width are not wrapped. It looks broken and they can't be edited or deleted any more at the UI.

<img src="https://github.com/keycloak/keycloak/assets/789496/e30c72b3-9042-45b1-ac63-9dad1a2c91ef" width=600>

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

- Message key is completely displayed
- Edit icon can be used to edit the value
- Context menu can be used to delete the entry

### Actual behavior

- Text is not wrapped but runs out of screen.
- Edit icon not visible
- Context menu barely usable (when not clicked exactly screen ends up unusable without reload):
<img src="https://github.com/keycloak/keycloak/assets/789496/eb913dad-2e0d-4bc6-b7cc-97da38ee36ed" width=400>

### How to Reproduce?

1. Enable realm localization.
2. Add message key with long value.
3. Try to click on context menu (three dots)

### Anything else?

Without "white-space: nowrap" it looks fine.
<img src="https://github.com/keycloak/keycloak/assets/789496/95e340da-67e8-4c5f-a187-182ce0e86fad" width=400>

**Comment by agagancarczyk** [comment]
Thanks @jbman for reporting this issue but I'm not able to reproduce it in 25.0.1. Please see attached 
![Screenshot 2024-07-02 at 10 03 30](https://github.com/keycloak/keycloak/assets/4890675/6d9f7e3f-d3c5-4738-ac7a-725f265f8f4a)

**Comment by jbman** [comment]
Sorry, probably sth,. was cached. Should have tested with a clean browser. Works as expected!
