### ISSUE TITLE
Workflow failure: WebAuthn IT (firefox) - WebAuthnSigningInTest:navigateBeforeTest

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#30994]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

In some cases this test is marked as failed instead of flaky, even though the 2nd time the test is executed it passes.
```
-- [INFO] Results:
-- [INFO] 
Error: OR] Failures: 
Error: OR] org.keycloak.testsuite.webauthn.account.WebAuthnSigningInTest.multipleSecurityKeys
Error: OR]   Run 1: WebAuthnSigningInTest>AbstractWebAuthnAccountTest.navigateBeforeTest:110->AbstractWebAuthnAccountTest.loginToAccount:161 Expected OIDCLogin but was Account Management (https://localhost:8543/auth/realms/test/account/account-security/signing-in)
-- [INFO]   Run 2: PASS
-- [INFO] 
-- [INFO] 
Error: OR] Tests run: 126, Failures: 1, Errors: 0, Skipped: 112
```

https://github.com/keycloak/keycloak/actions/runs/9739775087/job/26875767087

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by mposolda** [comment]
Adding it as low priority for now. We can revisit if this issue is still happening.

**Comment by miquelsi** [comment]
Happening again: https://github.com/keycloak/keycloak/actions/runs/11171716978/job/31057139189

**Comment by rmartinc** [comment]
This error happens sometimes in firefox. It's always in the first test `WebAuthnSigningInTest.multipleSecurityKeys`. I cannot reproduce it in my laptop. Showing the error in the CI the account page shows an error loading a CSS:

![error](https://github.com/user-attachments/assets/6433a799-bf48-416d-ad37-62ff8d0a0999)

So it's like there was a network error loading something (a css style in this example). I tried to reproduce this adding sleeps in serving resources and it never fails locally. Besides I usually use firefox and I have never seen this error accessing the account console. So I'm just to going to re-try loading the account page. I'll send a PR the next week.
