### ISSUE TITLE
Token-Exchange does not trigger/log user update event

### ISSUE THREAD

**Issue by kochen** [keycloak/keycloak#31002]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

When token exchange is used with the `userinfo` endpoint, user profile is being created on the first attempt to access, triggering a TOKEN-EXCHANGE event as well as a `USER.REGISTER` event.

On a second attempt to access with token-exchange, a TOKEN-EXCHANGE event is triggered but there is no `USER.UPDATE` triggered even when the user profile got actually updated.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

A `USER.UPDATE` (even as `admin`) event is expected for every profile update, regardless of the cause.

### Actual behavior

No `USER.UPDATE` event triggered

### How to Reproduce?

Use `token-exchange` with userinfo endpoint

**Comment by rmartinc** [comment]
Hi kochen!

AFAIK the userinfo endpoint does not create a registry or update event. It just generates the user info event which is not enabled by default. Those events you mention are typically created by the user login (for example a login via IdP can create a REGISTRY, or the locale can also create the UPDATE,...). Are you sure the events are created by the user info endpoint? Are they not created by the login performed before that gets the token to do the userinfo request?

**Comment by kochen** [comment]
> Hi kochen!
> 
> AFAIK the userinfo endpoint does not create a registry or update event. It just generates the user info event which is not enabled by default. Those events you mention are typically created by the user login (for example a login via IdP can create a REGISTRY, or the locale can also create the UPDATE,...). Are you sure the events are created by the user info endpoint? Are they not created by the login performed before that gets the token to do the userinfo request?

It might not be the `userinfo` endpoint itself, but for the TOKEN-EXCHANGE process itself, we do see a `USER.REGISTER` event when the user is created, but we do not get any `USER.UPDATE` when the user gets updated - the question is why?

**Comment by kochen** [comment]
> @kochen With the information you provide is very difficult to guess what is creating the events. My feeling is that the update is generated by the user creation itself not by the user-info or the token-exchange. Maybe you can explain a bit more how you are doing the test and how you are creating the users, or even better, send exactly what you are doing in a way we can reproduce the issue.

### Loosely steps to reproduce
Our setup involves several other applications which I can expose/explain here, but the last step is the most relevant:
- Token Exchange is initiated from our backend
```
[
    'grant_type' => 'urn:ietf:params:oauth:grant-type:token-exchange',
    'subject_token_type' => 'urn:ietf:params:oauth:token-type:jwt',
    'subject_issuer' => 'keycloak_idp_alias',
    'subject_token' => ...,
    'redirect_uri' => ...
    'client_id' => ...,
    'client_secret' => ...,
]
```
- in the respective IdP, we have set the `userinfo` endpoint, pointing at the location where the user is originating to validate the user attributes (as you mentioned, might not be relevant to the actual problem).
- this registers the user within `Keycloak`, resulting in a `USER.REGISTER` event
- a session is created for the user within `Keycloak`
- the user gets redirected to the provided `redirect_uri` with a `Keycloak` session/token and is fully authenticated in our platform.
- on a *second* access with the same flow, the token exchange is initiated in the same way
- user details/attributes are (if needed) updated within `Keycloak`
- even if user profile was update no `USER.UPDATE` is logged/triggered!

Hope this clarifies the scenario a little bit.

M.

**Comment by rmartinc** [comment]
@kochen If you think we can imagine all you are describing there with no explanation is that you think we are more than we really are. For what I understand from the last comment, you are using TE to instantiate a user from IdP. The TE can create the user (if the user is missing in keycloak) and it generates the REGISTER event [here](https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java#L636-L642). I think the second time you are using TE the user already exists and no event is generated. Why do you expect an update event? What other process is generating the update and you are trying to compare with it?

Besides there is no update user event. Keycloak has update profile, update email, update password, update totp,... But not just update. What update are you referring to?

**Comment by kochen** [comment]
> @kochen If you think we can imagine all you are describing there with no explanation is that you think we are more than we really are. For what I understand from the last comment, you are using TE to instantiate a user from IdP. The TE can create the user (if the user is missing in keycloak) and it generates the REGISTER event [here](https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java#L636-L642). 

Correct!

> I think the second time you are using TE the user already exists and no event is generated. Why do you expect an update event? What other process is generating the update and you are trying to compare with it?

I'm not sure what is causing the update, but the user profile is updated (i,e attribute values do change) - the change itself is desired (!).
Our problem is with the fact that the profile update does not trigger the update profile event.

> Besides there is no update user event. Keycloak has update profile, update email, update password, update totp,... But not just update. What update are you referring to?

update profile.

**Comment by zluiten** [comment]
Let me add a little as well. What we currently see is that on a _second_ TokenExchange with an _existing_ user, the user details sometimes get updated (f.e. attributes) (probably as a result of the user info call that's being done by Keycloak as part of the token exchange flow). We expect as a result of this a user updated event to be generated, but that does not seem the case.

**Comment by rmartinc** [comment]
Ah! No, the IdP can change the user (if the user attributes returned by the IdP change or the mappers or whatever). It's the same in a login via IdP. But there is no update profile event generated. Neither normal IdP login nor TE generates the update profile. I don't know if this is expected or not but it has been this way since the beginning.

At least we understand the issue now. But it's minor. I'm adding the help wanted and setting to backlog. Changing the title too as this affects also IdP login.

**Comment by kochen** [comment]
> Ah! No, the IdP can change the user (if the user attributes returned by the IdP change or the mappers or whatever). It's the same in a login via IdP. But there is no update profile event generated. Neither normal IdP login nor TE generates the update profile. I don't know if this is expected or not but it has been this way since the beginning.

That does not seem to be correct.
When a user comes from an IdP (i,e SSO) and the user's attribute change (i,e via mappers), there **is** an update profile event triggered!
We have that setup for several realms and actually rely on that functionality for other parts of the platform - that is why we expect (or maybe even need) the update profile event in the case of a TE as well.


> At least we understand the issue now. But it's minor. I'm adding the help wanted and setting to backlog. Changing the title too as this affects also IdP login.

Given the above, is it still `minor`?

**Comment by rmartinc** [comment]
yes, it's minor and I have tested it. I have changed a user firstname and lastname. Logged in via idp normally and only the login event is generated. And I see the user in the provider realm has changed the firstName and lastname. So maybe it's generated but not always (and I would say that is never generated).  A missing event is always minor.

**Comment by kochen** [comment]
> yes, it's minor and I have tested it. I have changed a user firstname and lastname. Logged in via idp normally and only the login event is generated. And I see the user in the provider realm has changed the firstName and lastname. So maybe it's generated but not always (and I would say that is never generated). A missing event is always minor.

Thanks for the help here 🙏 

I'd be really nice if eventually both IdP and TE behave the same and generate the same events. register & update, but also login.

**Comment by rmartinc** [comment]
I have been looking this a bit more. The update profile you are seeing in the normal login is generated by the first login flow. It's the one generated by the [IdpReviewProfileAuthenticator](https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpReviewProfileAuthenticator.java#L113). So it's part of the first login. A second login does not generate any update event even if there are changes in the user (as I commented before).

Probably here the solution is that TE executes the first login flow somehow. But this is something not easy to do. So I think this should be studied in more detail. I don't know if it's even a bug and more an enhancement. I will try to comment about this with the group in teh next weeks.
