### ISSUE TITLE
User Federation settings changing when saving

### ISSUE THREAD

**Issue by puggimer** [keycloak/keycloak#31001]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When saving the configuration for User Federation, the Bind credentials field is getting reset instead of saving.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Save the new property as specified

### Actual behavior

Set the Bind Credentials.  Click Test Authentication, it works.  Click Save button.  Click Test Authentication, it now fails.

### How to Reproduce?

Import realm with user federation where the password is not correct.  Go to User federation tab,  correct the password (bind credentials).  Test authentication.  Save.  Test Authentication.

### Anything else?

I am including screen shots taken quickly as I set the password, tested, saved and tested again.  I circled the bind credentials field - you can see where the mask changes length when saved and no longer works.

![ok](https://github.com/keycloak/keycloak/assets/331213/be271136-91ac-42bd-a7c2-c456c784e14f)
![bad](https://github.com/keycloak/keycloak/assets/331213/2fcb4d89-b36e-4c64-a109-f1182a57627a)
![save](https://github.com/keycloak/keycloak/assets/331213/6bfb7580-12b8-43e8-bbac-0178daee125f)

I am also including the trace log when this happens.  
[kc.log](https://github.com/user-attachments/files/16068866/kc.log)

**Comment by pedroigor** [comment]
@puggimer It seems related to https://github.com/keycloak/keycloak/issues/30821. I tried to reproduced using a realm JSON file where the bind credentials are invalid but when importing back the realm I cannot reproduce the issue.

The difference in the value of the field is because the credential is masked.

I'm wondering if there is something else to reproduce the problem.
