### ISSUE TITLE
Conditionally redirect existing users to a broker based on their credentials

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#31006]
### Description

We might want the following logic when deciding if the user should be shown with the brokers he is linked to vs automatically redirecting if linked to a single broker:

* If the user has credentials set and there is a single broker, we do not redirect automatically to allow him to either authenticate using credentials or the broker he is associated with
* If the user does not have credentials set and there is a single broker, we automatically redirect as we per today.

Today we always redirect an existing user to a broker if there is a single federation link to an organization broker. The idea is to conditionally redirect the user by checking whether or not the user has credentials.

### Motivation

https://github.com/keycloak/keycloak/pull/30972

**Comment by alexanderhofstaetter** [comment]
We would like to see this behaviour also without organizations: When a user logs in and has no credential set but has a linked IdP (e.g. google - then redirect automatically to google)
