### ISSUE TITLE
"Verify Email" may cause other Required Actions to be ignored

### ISSUE THREAD

**Issue by melegiul** [keycloak/keycloak#31014]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When "Verify Email" is top prio Required Action and user has set this and other Required Actions and email is still empty, then on login all Required Actions are ignored.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

All Required Actions set for a user should be processed.

### Actual behavior

Under some circumstances not all Required Actions set for a user are processed.

### How to Reproduce?

1. Set "Verify Email" on top of the list of Required Actions (highest prio)
2. Choose a user with no email set and add "Verify Email" and any other Required Action ("Update Password", "Update Profile", ...)
3. Login with user
4. See that "Verify Email" is ignored correctly because nothing to verify, but any other Required Actions are ignored, too

### Anything else?

Workaround: reduce prio of "Verify Email" Required Action

**Comment by svenseeberg** [comment]
I can reproduce this on multiple Keycloak installations. However, there is one additional piece to the puzzle: the actions are only ignored when the Verify Profile action has a lower priority than the Verify Email action.

Obviously, if no mail is set, it is necessary to first update the profile before the email can be verified.

But this is still critical as the Update Password actions etc are also skipped.

**Comment by graziang** [comment]
Thanks @svenseeberg , the reason is that the verify email action is ignored if the user doesn't have an email set, so all the required actions with lowest priority would be skipped if the user's email is null.

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/requiredactions/VerifyEmail.java#L68-L67

If the email field is not required for the User Profile, this issue can also occur with the default priorities of the required actions.

**Comment by radoslawsyga** [comment]
Issue is not related only to "Verify Email", it occurs also for other required actions:

Issue occurs when required action calls `context.success();` from `requiredActionChallenge(final RequiredActionContext context)`
then next required actions execution is skipped 

Please check if https://github.com/keycloak/keycloak/pull/31060 fixes also other cases than 'Verify Email'

**Comment by rmartinc** [comment]
This is a regression from #16873.
