### ISSUE TITLE
multivalue custom attributs are allways user editable even if configured as read only

### ISSUE THREAD

**Issue by trailhuntervodafone** [keycloak/keycloak#31017]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

multivalue custom attributs are allways user editable even if configured as read only

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

multivalue custom attributs should be readable if configured "who can edit" permission for user is not set

### Actual behavior

multivalue custom attributs are allways user editable even if configured as read only

### How to Reproduce?

define multivalue attribute in realm settings/ UserProfile make it only User van view but not edit; and login with enduser: enduser is able to delete or create new values

**Comment by jbman** [comment]
Could not reproduce in 25.0.1
![image](https://github.com/keycloak/keycloak/assets/789496/52dc5311-42ac-44fa-b9ad-ddcdd53cab76)

```
{
      "name": "multi",
      "displayName": "${profile.attributes.multi}",
      "validations": {
        "options": {
          "options": [
            "A",
            "B",
            "C"
          ]
        }
      },
      "annotations": {
        "inputType": "multiselect"
      },
      "permissions": {
        "view": [
          "admin",
          "user"
        ],
        "edit": [
          "admin"
        ]
      },
      "multivalued": false
    }
```

Could you please check with this newest version? Maybe also provide the attribute config JSON.
