### ISSUE TITLE
Styling of recovery codes seems wrong

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#31021]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

The style of the recovery codes download 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

look good

### Actual behavior

doesn't

### How to Reproduce?

enable recovery codes feature and download the codes from the account console

**Comment by rmartinc** [comment]
@edewit I was playing with this some days ago and the download file was:

```
Keep these recovery codes somewhere safe.

1: PN7I-4T44-72VL
2: J2RE-VVSC-GZT4
3: 7VE4-WVUN-8BJR
4: WI91-NA3E-Y6YT
5: 3N8N-FTXR-T1DR
6: PBWV-VVMD-MNWR
7: ZWLK-YEJ2-ZTIK
8: Q8W7-86JE-76F4
9: 1FZZ-MTTS-TMN6
10: DMLP-ER4P-53U4
11: 3AU4-TDVN-DHHP
12: BAIU-4URI-N98B

Recovery codes are single-use passcodes that allow you to sign in to your account if you do not have access to your authenticator.

These codes were generated on July 4, 2024 at 1:01 PM GMT+2
```

How do you want them? Maybe I'm a bit sloppy, but I don't see them very bad. :smile:

**Comment by rmartinc** [comment]
@edewit How are you seeing this? Is like in my previous comment or do you see something different? I'm trying to understand what you are reporting here.

**Comment by rmartinc** [comment]
Okis! Undertood! Although we'll need the help from @xianli123 to finally manage this. I'll create a PR with my initial proposal that everybody can review.

**Comment by edewit** [comment]
@rmartinc already have something PR coming soon

**Comment by rmartinc** [comment]
Okis, perfect! I have also created this one https://github.com/rmartinc/keycloak/tree/issue-31021 if you want to take a look. When sending the PR add @xianli123 to the review.

**Comment by rmartinc** [comment]
@xianli123 Yep, @edewit already has sent a PR here: https://github.com/keycloak/keycloak/pull/31106

**Comment by xianli123** [comment]
@rmartinc @edewit Thanks. Looks good! A question is about the "Recovery Authentication Codes" page. Is it necessary to have a way to return to the previous page "Select login method"?
A trivial matter is that the cancel button should be a link button to follow PatternFly's guidelines. 
![image](https://github.com/keycloak/keycloak/assets/53931519/f04fd251-6ea3-42f7-acc6-820b12ccd475)

**Comment by edewit** [comment]
right done

**Comment by xianli123** [comment]
Great! Thanks @edewit

**Comment by hmlnarik** [comment]
Reopening due to the original PR was reverted because of #31319
