### ISSUE TITLE
Remove explicit Protostream dependency

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#31032]
### Description

In order to resolve #30761, it was necessary for Keycloak to consume a newer version of the Protostream library than that provided by Infinispan. Once Infinispan starts to adopt Protostream 15.0.6.Final or later, it will be possible for us to remove this explicit dependency.

**Comment by ahus1** [comment]
Adding this for KC26 as a reminder, although it is unlikely that Infinispan 15.0.x has caught up by then, and as it looks today we won't upgrade to 15.1.x for KC26. 

If the preconditions haven't been met, we'll bump the milestone of this issue to KC27.

**Comment by ryanemerson** [comment]
Closing as we now need the explicit Protostream version to be defined in order to use the `proto-schema-compatibility-maven-plugin`.
