### ISSUE TITLE
Home URL for account-console / security-admin-console broken in admin-ui

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#31038]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The current admin ui shows invalid home page URLs for account/account-console and security-admin-console clients
<img width="1512" alt="image" src="https://github.com/keycloak/keycloak/assets/314690/ad27b678-bfd5-43d0-bb54-e8b4bcf348b1">

### Version

26.0.0 (a7ae90cbb6)

### Regression

- [X] The issue is a regression

### Expected behavior

Links to account console should include `/account` path. 
Link to security-admin-console should point to realm scoped admin console.

### Actual behavior

All links for built-in clients point to the auth-server url `http://localhost:8080` in this case.

### How to Reproduce?

1) Start a current nightly build
2) List the clients
3) Check the generated homepage links

**Comment by JessThrysoee** [comment]
This regression was introduced in keycloak 25.0.2, but the fix ffbfb7450f has not been cherry-picked to the release/25.0 branch !

**Comment by jonkoops** [comment]
Thanks for letting us know @JessThrysoee. I'll prepare a backport.

**Comment by jonkoops** [comment]
Backport up under #33237

**Comment by thomasdarimont** [comment]
The security-admin-console link is still broken in 26.0.0 and 25.0.6, see https://github.com/keycloak/keycloak/issues/34015
