### ISSUE TITLE
ClientStorageProviderResource is unused and should be removed

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#31049]
### Description

The class above generated in the RHSSO 7.6 docs an entry which is wrong:

* The resource is never instantiated neither in RHSSO 7.6 or RHBK24, so it is never called
* The description conflicts with UserStorageProviderResource

So I suggest to remove it.

![image](https://github.com/keycloak/keycloak/assets/3957921/4685cd4b-bac3-4f4c-807d-65fac1170bcc)

**Comment by sguilhen** [comment]
Can we remove resources from services without deprecating first? Or is it currently unreachable anyway, so it is safe to remove?

**Comment by ahus1** [comment]
I'd argue it is unreachable, happy to be proven otherwise. For all the other resources, their constructor is called from somewhere. This is one isn't (and hasn't been for quite a while). Still I'd be happy to have a second pair of eyes confirming that.

**Comment by sguilhen** [comment]
@pedroigor  what do you think? It seems safe to me to proceed with @ahus1 's suggestion but would like to confirm.
