### ISSUE TITLE
Cannot reorder custom auth flow executions in admin-ui

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#31040]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Cannot reorder authentication flow executions in custom authentication flow - auth flow execution hangs when dragged.
<img width="1498" alt="image" src="https://github.com/keycloak/keycloak/assets/314690/464b2d5b-584b-43a6-b4f4-c46192bcda75">

### Version

26.0.0 (a7ae90cbb6)

### Regression

- [X] The issue is a regression

### Expected behavior

it should be possible to reorder auth flow executions.

### Actual behavior

Cannot reorder authenticator executions in custom auth flows.

Error in dev tools console:
```
execution-model.ts:127 Uncaught TypeError: Cannot read properties of undefined (reading 'level')
    at Mc.getChange (execution-model.ts:127:60)
    at onDrop (FlowDetails.tsx:430:50)
    at ee (Draggable.js:101:35)
    at HTMLDocument.j (Draggable.js:235:33)
```

### How to Reproduce?

1) Run the latest nightly
2) Duplicate browser flow
3) Try to reorder auth flow executions

**Comment by mrik974** [comment]
Hi. I'm experiencing the exact same issue with Keycloak 26.0.1.
The workaround is to stop moving elements from bottom to top, and move them from top to bottom.

**Comment by jonkoops** [comment]
@mrik974 if you are still experiencing this issue please report a new one so we can triage it, thanks.
