### ISSUE TITLE
Keycloak does not allow two different groups to have the same role

### ISSUE THREAD

**Issue by DREGALLA** [keycloak/keycloak#31058]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have created three groups in keycloak(admin, user, agent). Assigned aads.user role for two groups(user, agent). Users from user group not getting role at the time of login. Keycloak does not accept two mappers with the same role.

### Version

24

### Regression

- [ ] The issue is a regression

### Expected behavior

All users from all group able to get role and authenticate.

### Actual behavior

Keycloak does not allow two different groups to have the same role.

### How to Reproduce?

1. Created a new attribute mapper and map another new group to the same user.
2. Login with xxx.com which is in user group, it can always work for SAML authentication with multiple sign in attempts.
3. Login with xxx.com which is agent group, it can work for first SAML authentication, and failed with the 2nd SAML authentication due to error: No supported roles/No username provided in token even if we received correct user role agent in the SAML token from IDP.

**Comment by rmartinc** [comment]
@DREGALLA Can you please spend more than 1 minute to write the issue? What mapper? What configuration? What role? Is is SAML mapper, OIDC or IdP?

I would expect a reproducer like the following:

1. Create a new realm called demo.
2. Create role user-role.
3. Create a user called user1 and assign user-role to the user.
4. Create a SAML client.
5. In the client configure the mapper of type `whatever` with the following config
6. ....

Do you think we can do something with what you have written here? Maybe I'm stupid but I really don't understand what you are trying to do or what is failing.

**Comment by DREGALLA** [comment]
Hi Team ,

I have created three mappers(aads.admin, aads.user and aads.gslabuser) . Please see attached screenshots.

<img width="893" alt="aads admin" src="https://github.com/keycloak/keycloak/assets/142571886/44768b48-d0e8-449f-adfa-737cec7283be">

<img width="842" alt="aads gslabuser" src="https://github.com/keycloak/keycloak/assets/142571886/d9f4fefb-ad2d-4baf-a1b3-884595a19fe7">

<img width="923" alt="aads_user" src="https://github.com/keycloak/keycloak/assets/142571886/1df886de-05e7-45ba-8b79-4bf1be9ae817">


aads.user and aads.gslabuser assigned same role that is user. And aads.admin mapper assigned admin role. So the issue is because of same role assigned to two group, users from aads.user not able to login. they are not able to get role and authentication is failing.  If I move any user from aads.user to aads.gslabuser group then that user working fine.

**Comment by DREGALLA** [comment]
Hi Team,

I have created three mappers(aads.admin, aads.gslabuser & aads.user). Please check attached screenshots.

<img width="944" alt="aads admin" src="https://github.com/keycloak/keycloak/assets/142571886/10a792a5-10ca-43d7-8b86-eb7b9e52d203">

<img width="959" alt="aads gslabuser" src="https://github.com/keycloak/keycloak/assets/142571886/4e9d64da-3bb4-4ff4-b039-ac99479a1813">

<img width="923" alt="aads_user" src="https://github.com/keycloak/keycloak/assets/142571886/5de4b355-e4d6-40a3-ab1e-d8676866843f">



aads.user and aads.gslabuser assigned same role that is user. And aads.admin mapper assigned admin role. So the issue is because of same role assigned to two group, users from aads.user not able to login. they are not able to get role and authentication is failing. If I move any user from aads.user to aads.gslabuser group then that user working fine.

**Comment by rmartinc** [comment]
@DREGALLA This is expected, note that the role mapper adds the role if the attribute exists but also removes the role if the attribute does not match. So if you define two mappers over the same role and one matches and the other not it just depends in the order of execution if the role is added or removed. If the first mapper removes the role and then it's added, the role is added, but if the first mapper adds the role and the second one removes it, the result is role removed (not added). You can also use the `Advanced Attribute to Role` and use a regex with several values to match the value of the attribute (using several values in an or for example).

**Comment by DREGALLA** [comment]
@rmartinc Can you please put one example for how use can use 'Advanced Attribute to Role" and regex? It will be helpful.

**Comment by rmartinc** [comment]
For example in my environment:

![Screenshot from 2024-07-05 15-04-57](https://github.com/keycloak/keycloak/assets/26901232/e33c18cd-cadf-41a6-b3b4-ce7541003f63)

This configuration adds the `test-oidc->role` if the one value of the saml attribute `Role` matches the regex `manage-account|manage-account-links`. So both values are valid, any one would add the role. Just note the regex should be a java regex and maybe you need to escape some characters in the values. The values in the images you have shared are OK as they don't have especial chars. You can use any web page to test (for example https://regex101.com/ selecting java flavor).

**Comment by DREGALLA** [comment]
@rmartinc Thank you so much for helping. It's working for me.

**Comment by rmartinc** [comment]
Thanks @DREGALLA!

Then I'm going to close the issue as not planned as this is working as expected. Note that the simple attribute to role mapper for IdPs just assigns or unassigns the configured role if the attribute is found or missing respectively. So adding two or more mappers to the same role makes no sense as the addition or removal is not guaranteed. If the different mappers are contradictory (one mapper results in adding the role and the other in removing it, you don't know what it's going to happen because it just depends in the order of execution). The advanced mapper is more configurable as it allows regex to create more complex configuration to assign/unassign the role.

**Comment by DREGALLA** [comment]
@rmartinc I can see the "Advanced Attribute to Role" is not present in Keycloak 6.0. Does it mean Keyaclok 6.0 does not support multiple mappers with the same role?

<img width="766" alt="image" src="https://github.com/keycloak/keycloak/assets/142571886/522ca442-4f48-4697-bf4f-c4337a5e8d5a">

**Comment by realwangjiafa** [comment]
@rmartinc The AADS 10.1.1.3 has keycloak 6.x which is too old and it only has a few mapper types. 

I tried the same regular expression EquinoxUser|GSLABUser in mapper type: “SAML Attribute to Role” in AADS 10.1.1.3 for multiple groups, it did not work. 

The required mapper type “Advanced Attribute to Role” is only available in AADS 10.2 with Keycloak 22.0 release which has lots of additional mapper types. 

I am not sure whether Keycloak can provide a workaround for us to add the new mapper type “Advanced Attribute to Role” in current Keycloak 6.x release in AADS 10.1.1.3, like adding this option from database. 

Is it possible? 

Or the only way to get this new mapper type is to upgrade Keycloak release to 22.0? 

thank you so much!

**Comment by jonkoops** [comment]
Yes, the only way to get it is to upgrade. But if you are running 6.0 in production you should make it your immediate priority to upgrade your Keycloak instance. That version is vulnerable to several critical security issues, and can be compromised by attackers. The only supported version of Keycloak in community is the latest major version.

**Comment by realwangjiafa** [comment]
Got it, thank you @jonkoops

**Comment by realwangjiafa** [comment]
Hi Team,

The same config works for IDP ADFS, but it comes to IDP Azure AD, it does not work.

ADFS: 

Name: aads.user
Mapper Type: Advanced Attribute to Role
Attributes Key: http://schemas.xmlsoap.org/claims/Group
Attributes --> Value: EquinoxUser|GSLABUser

Azure AD:

Name: aads.user
Mapper Type: Advanced Attribute to Role
Attributes Key: http://schemas.microsoft.com/ws/2008/06/identity/claims/groups 
Attributes --> Value: 7a6737ed-a753-4d70-ba5f-7fd20d1eedc5|0de8c507-0d52-4266-8179-dbaa1ce982cc  

Maybe the regular expression does not support  dash "-" in the value?

Please let me know how to make it work with the above 2 Azure group IDs for 2 groups mapped to aads.user role.

Thanks a lot!

Jiafa

**Comment by realwangjiafa** [comment]
Hi Team,

“Regex Attribute Values”  was not enabled, when it was enabled, then it worked. No further questions on this topic.

Thanks again.
