### ISSUE TITLE
Cannot create "multivalue | array" attributes in Admin UI if the value isn't already an array

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#31069]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

An user attribute cannot be made multivalued (array) directly from the Admin UI.
If the user attribute is already an array (passed from an IdP or via the Rest API), it is working as an array, having the button for adding new value for the attribute:
![image](https://github.com/keycloak/keycloak/assets/33352511/ecab38b6-ce03-499a-b9f8-95f6a16a1d96)

For new attribute, even if Validation for "multivalued" is added, there is no option to add multiple values from the Admin UI (tried with ,;|## and others):
![image](https://github.com/keycloak/keycloak/assets/33352511/c2f115ac-d93a-40d1-82cb-f5c991540c99)
![image](https://github.com/keycloak/keycloak/assets/33352511/d1123bb3-dc38-466b-b3b6-aaebaf621623)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

User Attribute can be created as "multivalued" (have such an option in the User Profile) and when it is, it can hold an array as values, possible to be added with Add new button in the Admin UI

### Actual behavior

If the attribute is not pre-created as an array, via IdP mapper or via the REST API, multiple values cannot be added (and the button is not visible if the value is only one)

### How to Reproduce?

- Create new attribute in the User Profile
- Open an user
- Try to add multiple values in the newly created attribute

### Anything else?

Issue https://github.com/keycloak/keycloak/issues/18177 is related to this one, where it seems this behaviour was just not added.

**Comment by pedroigor** [comment]
@mpalavrov It should be fixed by https://github.com/keycloak/keycloak/issues/30712. And the switch should be back in Keycloak 25. Please, check the nightly image if you want to test the fix.
