### ISSUE TITLE
Updating dynamically registered client's metadata drops `preferred_username` from ID token

### ISSUE THREAD

**Issue by sberyozkin** [keycloak/keycloak#31062]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When one registers a client using a standard OIDC Dynamic Client Registration call, and then, sends an update request to the registered client's configuration endpoint, a strange side-effect happens: ID token loses `preferred_username`.
Not a problem if a client metadata is re-read from the registered client's  configuration endpoint.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Authorization code flow involving the dynamically registered client produces correct ID tokens after the registered client's metadata have been updated.

### Actual behavior

ID token loses `preferred_username`

### How to Reproduce?

* Register a client with https://www.keycloak.org/docs/latest/securing_apps/index.html#openid-connect-dynamic-client-registration using one of the documented options (provide a `redirect_uris` array with a single value like `http://localhost:8080/protected`)
* Secure a Quarkus endpoint at `@Path("/protected")`, for example, a Quarkus endpoint with the registered client's id and secret, and `application-type=web-app` to enable an authorization code flow
* Have the endpoint code secured with `@Authenticated`
* Have `@Inject @IdToken JsonWebToken idToken;` and return `idToken.getName()` from a secured endpoint's `@GET` method
* Login, and confirm the user name is returned

Now, repeat, but after registering a client, follow immediately with an update to this client's configuration endpoint, for example, send the same metadata you got after the client has been registered.

Repeat other steps, ID token will have no `preferred_username`.

### Anything else?

I can prepare a test on my branch if the team decides to look at this issue

**Comment by graziang** [comment]
Thanks @sberyozkin, this is a real bug because with the update the default scopes are removed from the client, so the `profile` scope that maps the `preferred_username` is removed, and as a result, the claim is missing in the ID token.

**Comment by sberyozkin** [comment]
Thanks @graziang and @mposolda, just back from PTO, thanks for the fast fix
