### ISSUE TITLE
"Signed JWT" implies "MTLS"

### ISSUE THREAD

**Issue by ch-lepp** [keycloak/keycloak#31067]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

This issue is identical to the discussion I opened [here](https://github.com/keycloak/keycloak/discussions/30985).

I changed the authentication method of one of my clients from "Client ID and Secret" to "Signed JWT".
The GUI then asked me to generate a private key and cert from the "Keys" tab, which I did.

Upon requesting a token, my client now sends a JWT to Keycloak, properly signed using the private key.
But as a response the client gets an error.
**_Client Certification missing for MTLS HoK Token Binding_**

It seems, MTLS got implicitly required for the client as soon as I created a private key and cert for my client.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

I want to be able to use "Signed JWT" without using MTLS

### Actual behavior

"Signed JWT" seems to somehow enforce MTLS.

### How to Reproduce?

Have a client, set the authentication method to "Signed JWT" and generate a private key and cert for the client.
Now try to log in with this client without MTLS.

**Comment by pedroigor** [comment]
Token binding should be controlled by the setting `OAuth 2.0 Mutual TLS Certificate Bound Access Tokens Enabled` in the `Advanced` tab. Perhaps you can check the value of the client attribute `tls.client.certificate.bound.access.tokens` to make sure it is not set or `false`.

AFAIK, you shouldn't have that error if it is disabled. There are quite a few tests running the exact same scenario.

**Comment by ch-lepp** [comment]
@pedroigor you are right, the `OAuth 2.0 Mutual TLS Certificate Bound Access Tokens Enabled` switch was active in my client, but I don't recall activating it.

Anyway, thx for the help.
I turned the switch of and now everything works as expected.
The issue can be closed...
