### ISSUE TITLE
Force / Failure challenge do not abort the flow

### ISSUE THREAD

**Issue by mircea97** [keycloak/keycloak#31072]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

According to documentation, the forceChallenge, failureChallenge methods should abort the flow and return the given challenge (from AbstractAuthenticationFlowContext)
Ex: context.forceChallenge(challenge)
If there is another code after using **context.forceChallenge**, like **context.success()**, the last one is returned.
According to documentation, **context.challenge(challenge)** should be skipped if there is a **context.success()** after it.
What is the difference between these methods? And how can I enforce failure challenge? 
Should I use if / else or 'return' after I call on a challenge method?

### Version

22

### Regression

- [ ] The issue is a regression

### Expected behavior

When using context.failureChallenge or context.forceChallenge, the flow is stoped and the challenge is returned to the client.

### Actual behavior

Context.failureChallenge and context.forceChallenge just set status / challenge variables in **AuthenticationProcessor**.
Later, DefaultAuthenticationFlow.processResult gets triggered and there is a use case for each status. Again, FORCE_CHALLENGE and CHALLENGE have the same behaviour, even if the docs says the contrary.

Actual behaviour: the flow is not aborted and the challenge is not returned immediately.

### How to Reproduce?

Run a code where you have both lines of code, one under one:
context.failureChallenge(...)
context.success()

**Comment by mircea97** [comment]
From [docs](https://www.keycloak.org/docs-api/22.0.2/javadocs/org/keycloak/authentication/AbstractAuthenticationFlowContext.html#failureChallenge(org.keycloak.authentication.AuthenticationFlowError,jakarta.ws.rs.core.Response))

void forceChallenge(jakarta.ws.rs.core.Response challenge)
Sends the challenge back to the HTTP client irregardless of the current execution requirement.

Does this mean that current execution is one of the authenticators and it returns the challenge at the end of it ?
I understood that it should immediately stop the flow and return the challenge, even if there is another challenge in the same **authenticate** method.

**Comment by mircea97** [comment]
Version: latest version
Behaviour: same issue

**Comment by rmartinc** [comment]
@mircea97 The methods to control the status of the wokflow are just a mark in the object that is later consulted by another class (`getStatus` and `getChallenge`). You can check the code [here](https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/authentication/AuthenticationProcessor.java#L391-L446). They do not return anything to the caller, it just marks the context as failed, succeeded, or whatever. Mainly the result is then checked in another class to do the challenge or set the flow as succeeded. The idea is that you just execute one of those methods to mark what you want to do with the response. You have an example in the server development [documentation](https://www.keycloak.org/docs/latest/server_development/index.html#implementing-an-authenticator). And in general you can also check all [the authenticators in the product itself](https://github.com/keycloak/keycloak/tree/25.0.1/services/src/main/java/org/keycloak/authentication/authenticators/browser).

If you think the javadoc is misleading please send a PR with your suggestion but the code follows your code if you execute two methods, success and failure one after the other the last one wins.

**Comment by rmartinc** [comment]
I think there is no difference between `challenge` and `forceChallenge` in the [DefaultAuthenticationFlow](https://github.com/keycloak/keycloak/blob/25.0.1/services/src/main/java/org/keycloak/authentication/DefaultAuthenticationFlow.java#L499-L502). I think they are different in the ClientAuthenticationFlow in which there is no interaction. The idea of alternative in the default flow is a bit different. If a step has alternatives the one that is challenged is the one with the highest priority (see this [issue comment](https://github.com/keycloak/keycloak/issues/12102#issuecomment-1229914623) for more info).

**Comment by mircea97** [comment]
The documentation is still confusing. Still not clear when you can force a challenge to be returned.
