### ISSUE TITLE
Search doesn't  work for nested groups

### ISSUE THREAD

**Issue by keobr** [keycloak/keycloak#31070]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

![Screenshot from 2024-07-05 10-40-33](https://github.com/keycloak/keycloak/assets/47155091/bdacaee3-901d-4d23-bb37-9c9ff9f3ca06)
Search doesn't  for nested groups

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Search should work for all groups

### Actual behavior

Search doesn't  work for nested groups

### How to Reproduce?

Create nested group and find it

**Comment by keobr** [comment]
Is it possible to apply this change to version 25.0.x?

**Comment by jonkoops** [comment]
@keobr backport PR is up under #31658, should come along with the next patch release.
