### ISSUE TITLE
Internal code flow execute insert query twice in the keycloak migration (3.4.3.Final -> 24.0.4) from AuthzResourceUseMoreURIs.java and failed for adding primary key as part of ChangeSet execution "authz-4.2.0.Final-KEYCLOAK-9944"

### ISSUE THREAD

**Issue by SunilVishwakarma** [keycloak/keycloak#31108]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Internal code flow execute insert query twice in the migration (3.4.3.Final -> 24.0.4) from AuthzResourceUseMoreURIs.java and failed for adding primary key as part of ChangeSet "authz-4.2.0.Final-KEYCLOAK-9944"

References:
model/jpa/src/main/java/org/keycloak/connections/jpa/updater/liquibase/custom/AuthzResourceUseMoreURIs.java
model/jpa/src/main/resources/META-INF/jpa-changelog-authz-4.2.0.Final.xml

### Version

24.0.4

### Regression

- [x] The issue is a regression

### Expected behavior

It should migrate without inserting duplicate entries while copying records from RESOURCE_SERVER_RESOURCE table to RESOURCE_URIS table. 

### Actual behavior

It is inserting duplicate entries while copying records from RESOURCE_SERVER_RESOURCE table to RESOURCE_URIS table and later Primary key addition gets failed with the below error.

2024-07-05 13:13:04,227 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com encountered an exception.

UPDATE SUMMARY
Run:                         74
Previously run:              50
Filtered out:                 0
-------------------------------
Total change sets:          124

2024-07-05 13:13:04,760 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
2024-07-05 13:13:04,760 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2024-07-05 13:13:04,760 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-authz-4.2.0.Final.xml::authz-4.2.0.Final-KEYCLOAK-9944::hmlnarik@redhat.com:
     Reason: liquibase.exception.DatabaseException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_F5 ON PUBLIC.RESOURCE_URIS(RESOURCE_ID, ""VALUE"") VALUES ( /* key:4 */ '220580aa-3ac3-485e-bb1e-20e9058754fe', '/test')"; SQL statement:
ALTER TABLE PUBLIC.RESOURCE_URIS ADD CONSTRAINT CONSTRAINT_RESOUR_URIS_PK PRIMARY KEY (RESOURCE_ID, "VALUE") [23505-224] [Failed SQL: (23505) ALTER TABLE PUBLIC.RESOURCE_URIS ADD CONSTRAINT CONSTRAINT_RESOUR_URIS_PK PRIMARY KEY (RESOURCE_ID, "VALUE")] 

### How to Reproduce?

Use the keycloak old version like (3.4.3.Final) with any supported database and try to upgrade to any latest Keycloak versions. In my case used Keycloak version(24.0.4).

While server startup it will execute changelogs and during the execution it will fail with the specified error.

**Comment by sguilhen** [comment]
@SunilVishwakarma Just to ensure I understand the issue - in your original `RESOURCE_SERVER_RESOURCE` table you had more than one entry with the same (ID, URI) value? And then during migration these are moved to a new table where the primary key creation fails? How would that happen if the id is a primary key on the original table?

**Comment by vramik** [comment]
@SunilVishwakarma do you have any update on the @sguilhen's question?

**Comment by chandanachs** [comment]
@SunilVishwakarma: were you able to solve this issue? we are facing the same issue, it would be helpful if you share the procedure you followed.
