### ISSUE TITLE
Open email link sent from IdpEmailVerificationAuthenticator in new browser doesn't work if user have a verified email

### ISSUE THREAD

**Issue by jak837** [keycloak/keycloak#31102]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

When using "Verify existing account by Email" `IdpEmailVerificationAuthenticatorin` in the first-broker-login flow the requried action is added to the auth session:
`authSession.addRequiredAction(UserModel.RequiredAction.VERIFY_EMAIL);`
An email with a verify link is sent to the user.

If a user who already have a verified email opens the link in a new browser (fx the OS standard browser might be different from the browser they tried to login with), then an error messages appear that the users email already is verified from `IdpVerifyAccountLinkActionTokenHandler`. This happens here:
```
if (user.isEmailVerified() && !isVerifyEmailActionSet(user, authSession)) {
    event.user(user).error(Errors.EMAIL_ALREADY_VERIFIED);
    return session.getProvider(LoginFormsProvider.class)
            .setAuthenticationSession(session.getContext().getAuthenticationSession())
            .setInfo(Messages.EMAIL_VERIFIED_ALREADY, user.getEmail())
            .createInfoPage();
}

private boolean isVerifyEmailActionSet(UserModel user, AuthenticationSessionModel authSession) {
    return Stream.concat(user.getRequiredActionsStream(), authSession.getRequiredActions().stream())
            .anyMatch(RequiredAction.VERIFY_EMAIL.name()::equals);
}
```

It checks if email is already verified, but then it checks required actions from the user model and authSession.
The required action wasn't added to the user, only the auth session. But since the link is opened in a new browser the auth session is different.

This is only if the users email is already previously verified, for a user with an unverified link, it works with a different browser.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Its expected that a user with a previously verified email behaves the same doing "Verify existing account by Email"-step in first-broker-login flow as a user with an unverified email. So that all users can open the link in a different browser.

### Actual behavior

A user with a previously verified, gets the error message EMAIL_VERIFIED_ALREADY, when opening the link sent from `IdpEmailVerificationAuthenticator `in a new browser

### How to Reproduce?

1. Create a user with a verified email
2. Go thru first-broker-login flow with the authenticator "Verify existing account by Email" (enable smtp settings).
4. Go to email client
5. Copy verify link and open in a new browser (separate from where the first-broker-login flow happened).
6. Error appears

### Anything else?

The seems to have been introduce with keycloak 24.0.0 and this issue: https://github.com/keycloak/keycloak/issues/14776

There can be two ways of solving it.
1: Add required action to user (and not only auth session) in `IdpEmailVerificationAuthenticator`
```
authSession.addRequiredAction(UserModel.RequiredAction.VERIFY_EMAIL);
existingUser.addRequiredAction(UserModel.RequiredAction.VERIFY_EMAIL);
```
(not sure if authSession line would still be needed).
Disadvantage: If the user doesn't click the link, the required action is still persisted on the user for the next time they might login.

2: Make fix in IdpVerifyAccountLinkActionTokenHandler
In https://github.com/keycloak/keycloak/issues/14776  the check for already verified emails on users was in two token handlers:
- IdpVerifyAccountLinkActionTokenHandler
- VerifyEmailActionTokenHandler

I can see why it was added VerifyEmailActionTokenHandler, but I don't think the behavior is needed for IdpVerifyAccountLinkActionTokenHandler because the IdpEmailVerificationAuthenticator step in first-broker-flow doesn't really look different if its a user with a verified email or not. So my suggestion would be to remove the step check from IdpVerifyAccountLinkActionTokenHandler

**Comment by jak837** [comment]
Opening the link in a different browser because an even bigger issue if you use keycloak in an app that uses an openid client to open an embedded webview. The embedded webview wont get the link openeded, but will fx happened in phones email client webview or the phones browser.

Regarding my first proposal about adding the required action to usermodel in IdpEmailVerificationAuthenticator then IdpVerifyAccountLinkActionTokenHandler would also have to be modified to remove the requried action again (which it doesn't do currently).

I would still go with my second proposal. I still think the check is needless in IdpVerifyAccountLinkActionTokenHandler but does make sense in VerifyEmailActionTokenHandler regarding the original story, since for account linking the behavior should be that if you require email verification, then it doens't matter if you have previously verified your email.

I would be willing to implement something to solve the issue, I would just prefer somebody from keycloak could give advice on what would be preferred to be implemented.

**Comment by martin-kanis** [comment]
@jak837 Hi, thanks for reporting this. I have troubles to reproduce this. In my case, whenever a user has a verified email, verification link is not sent. I guess, I'm missing some config steps. How your authentication flows are configured? Do I have to setup an IDP?

**Comment by jak837** [comment]
> @jak837 Hi, thanks for reporting this. I have troubles to reproduce this. In my case, whenever a user has a verified email, verification link is not sent. I guess, I'm missing some config steps. How your authentication flows are configured? Do I have to setup an IDP?

Hi,
Thanks for having a look at it.
Yes the issue is doing the "first broker login" flow.
I will try detail it more here

1
Setup a realm with smtp settings
2.
create user in realm with username and email the same. It must match something from an identity broker like microsoft.
username and email could be set to: test@hotmail.com
4:
Mark the user as email verified:
![image](https://github.com/user-attachments/assets/18708a94-f14b-4c0a-a62e-9e75c765d250)
3a
Setup "first broker login" - the default will work, it must reach the "Confirm link existing account"
![image](https://github.com/user-attachments/assets/8b96fe51-283f-4e15-b508-417297d8835b)
3b
Alternative smaller first broker login flow:
![image](https://github.com/user-attachments/assets/701975e1-8420-467f-9a1b-15e83d31a102)
4
Setup realm to connect to an identity broker that have the same user as was created in keycloak.
It must use the first broker login flow previously configured
![image](https://github.com/user-attachments/assets/311fc38a-8857-4b36-96be-ac4b9a55ce39)
5
Now try login using the identity broker.
The user should in keycloak now reach what is displayed by: login-idp-link-email.ftl
6
The user will now get an email generated by: identity-provider-link.ftl
7
The link from the email, try an op open it in a new browser. and the user gets this page:
![image](https://github.com/user-attachments/assets/4a593291-de76-431f-b5bf-b577678a1ce2)


Hope that helps reproduce it.
I believe its because "Confirm link existing account" (`IdpEmailVerificationAuthenticator`), adds the required action to authSession.
The action token handler `IdpVerifyAccountLinkActionTokenHandler`, looks for the required action (only in case of the users email is already verified) in the userModel and authSession, but since the authenticator doesn't add the required action to the usermodel and its a new browser. It fails.
I think the check this check:
```
if (user.isEmailVerified() && !isVerifyEmailActionSet(user, authSession)) {
    event.user(user).error(Errors.EMAIL_ALREADY_VERIFIED);
    return session.getProvider(LoginFormsProvider.class)
            .setAuthenticationSession(session.getContext().getAuthenticationSession())
            .setInfo(Messages.EMAIL_VERIFIED_ALREADY, user.getEmail())
            .createInfoPage();
}

private boolean isVerifyEmailActionSet(UserModel user, AuthenticationSessionModel authSession) {
    return Stream.concat(user.getRequiredActionsStream(), authSession.getRequiredActions().stream())
            .anyMatch(RequiredAction.VERIFY_EMAIL.name()::equals);
}
```
can be removed from the `IdpVerifyAccountLinkActionTokenHandler`, it was added in https://github.com/keycloak/keycloak/issues/14776 where it was also added to `VerifyEmailActionTokenHandler`. The check makes sense in `VerifyEmailActionTokenHandler`, but for  `IdpVerifyAccountLinkActionTokenHandler` I think it can be removed. The first broker login flow doesn't take into account if the email is previously verified when linking an account, which I believe is correct. But the ActionTokenHandler that handles linking the account cares if the email was previously verified.

Let me know if you need anything else

**Comment by martin-kanis** [comment]
@jak837 Thanks for the detailed steps. I was able to reproduce it. It seems there is quite a few conditions that needs to be met in order to get this error. Therefore setting priority to normal. 
Maybe @pedroigor has an opinion about proposed fix as he worked on https://github.com/keycloak/keycloak/issues/14776. @pedroigor WDYT?

**Comment by clairtonluz** [comment]
I have the same problem here with Keycloak 25.0.6. Someone found some workaround to resolve this while this bug isn`t fix?

**Comment by jak837** [comment]
> I have the same problem here with Keycloak 25.0.6. Someone found some workaround to resolve this while this bug isn`t fix?

We ended up implementing our own IdpEmailVerificationAuthenticator and respective TokenHandler that removed the if statement to see if the email had previously been verified.

**Comment by clairtonluz** [comment]
> > I have the same problem here with Keycloak 25.0.6. Someone found some workaround to resolve this while this bug isn`t fix?
> 
> We ended up implementing our own IdpEmailVerificationAuthenticator and respective TokenHandler that removed the if statement to see if the email had previously been verified.

Do you hava some example of how to do this?

**Comment by jak837** [comment]
We copied 
* IdpEmailVerificationAuthenticator
* IdpEmailVerificationAuthenticatorFactory
* IdpVerifyAccountLinkActionToken
* IdpVerifyAccountLinkActionTokenHandler

From keycloak into our own project.
### Factory classes
In IdpEmailVerificationAuthenticatorFactory we change the PROVIDER_ID to "-custom" and the display name to distinct between keycloaks own authenticator
```
public static final String PROVIDER_ID = "idp-email-verification-custom";
@Override
public String getDisplayType() {
    return "Verify existing account by Email (Custom)";
}
```
In IdpVerifyAccountLinkActionToken we also used a different TOKEN_TYPE to distinct between keycloaks own:
```
public static final String TOKEN_TYPE = "idp-verify-account-via-email-custom";
```
### Authenticator and TokenHandler
IdpEmailVerificationAuthenticator where it does a `new IdpVerifyAccountLinkActionToken` we make sure that it is our own custom IdpVerifyAccountLinkActionToken it creates a new instance of.

In our own IdpVerifyAccountLinkActionTokenHandler we also removed the following if-statement: 
`if (user.isEmailVerified() && !isVerifyEmailActionSet(user, authSession)) {`

So that it skips the logic of looking at verify email.

### Authentication flow
Then we set it up on our first broker login flow:
![image](https://github.com/user-attachments/assets/e37701b2-e55c-4bfb-8308-9506be66c777)
Then once the "Verify existing account by Email (custom)" is reached, it will use our custom TokenHandler which doesn't have the email verified condition.

Hope it helps.

**Comment by martin-kanis** [comment]
Fixed by https://github.com/keycloak/keycloak/issues/31563 in 26.0.0 and 25.0.7
