### ISSUE TITLE
Not able to remove otp credential of user

### ISSUE THREAD

**Issue by VhvDennis** [keycloak/keycloak#31107]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

Since version 24.0.3 onwards (24.0.2 works fine) users are not able to delete their otp credentials via the account api anymore.

The request looks like the following:
```
Request URL: http://localhost:8380/realms/x/account/credentials/87909a18-79b9-4f4f-b7d1-3f9fef1b526b
Request Method: DELETE
Status Code: 403 Forbidden
Content: {
    "error": "No LoA on the token",
    "error_description": "For more on this error consult the server log at the debug level."
}

```
And in the logs: `WARN  [org.keycloak.services.resources.account.AccountCredentialResource] (executor-thread-7) Not able to remove credential of user 'e@example.com' as no acr claim on the token`

Creating new credentials seems to be working without a problem.
GET-Response from http://localhost:8380/realms/x/account/credentials looks like the following:
```
[
    {
        "type": "password",
        "category": "basic-authentication",
        "displayName": "password-display-name",
        "helptext": "password-help-text",
        "iconCssClass": "kcAuthenticatorPasswordClass",
        "updateAction": "UPDATE_PASSWORD",
        "removeable": false,
        "userCredentialMetadatas": [
            {
                "credential": {
                    "id": "1986f2f1-213a-47db-be09-f79f24ecbd13",
                    "type": "password",
                    "createdDate": 1679072941676,
                    "credentialData": "{\"hashIterations\":210000,\"algorithm\":\"pbkdf2-sha512\",\"additionalParameters\":{}}"
                }
            }
        ]
    },
    {
        "type": "otp",
        "category": "two-factor",
        "displayName": "otp-display-name",
        "helptext": "otp-help-text",
        "iconCssClass": "kcAuthenticatorOTPClass",
        "createAction": "CONFIGURE_TOTP",
        "removeable": true,
        "userCredentialMetadatas": [
            {
                "credential": {
                    "id": "87909a18-79b9-4f4f-b7d1-3f9fef1b526b",
                    "type": "otp",
                    "createdDate": 1720439963400,
                    "credentialData": "{\"subType\":\"totp\",\"digits\":6,\"counter\":0,\"period\":30,\"algorithm\":\"HmacSHA1\"}"
                }
            }
        ]
    }
]
```
Do we need to configure now otp credentials differently? I did not find anything in the change notes for 24.0.3.

### Version

24.0.3+

### Regression

- [X] The issue is a regression

### Expected behavior

User can delete their own otp credentials

### Actual behavior

user cannot

### How to Reproduce?

Setup otp authentication and then try to delete it via account api.

### Anything else?

Error messages originate from new code added with this commit: https://github.com/keycloak/keycloak/commit/c427e65354a208cedbfb828e47e6a631f903b384

**Comment by graziang** [comment]
Hi @VhvDennis, I am not able to reproduce the issue, could you better describe the steps to reproduce it?

**Comment by rmartinc** [comment]
@VhvDennis AFAIK the commit you are commenting resolved a security issue about a user removing OTP or 2FA just authenticated with the password. Are you using levels of authentication in your setup? Have you modified the browser flow to have different levels?

**Comment by ymargulis-infinipoint** [comment]
@VhvDennis, it seems like you migrated from Keycloak without ACR support, right? I had a similar issue and noticed that my account-console client scopes didn’t include the ACR scope. The Bearer JWT generated by this client also didn’t have the acr field. After adding the missing scope, the issue was resolved. Keycloak probably needs to implement some kind of migration process from older versions.

**Comment by VhvDennis** [comment]
@ymargulis-infinipoint hello, thank you, this was indeed the case here. After adding the acr claim to the client scope, the problem vanished.

**Comment by rmartinc** [comment]
So the issue is the `acr` client scope is not assigned as default to the `account-console` client and, therefore, the `acr` claim was not in the token. Probably we need a upgrading task that assigns the client scope to the `account-console` client, and maybe we should also consider to get the `acr` claim using introspect if missing (to support lightweight tokens with the console). @mposolda WDYT?

**Comment by mposolda** [comment]
This was fixed as mentioned in the previous comment https://github.com/keycloak/keycloak/issues/31107#issuecomment-2286134848 by handling migration from older versions than 18 and adding `acr` client scope to all clients.

For migrating from newer version, manual action may be needed (some from those mentioned in the last comment). Also added Warning triggered when Account REST endpoint for removing credential will be triggered as this endpoint is deprecated now.
