### ISSUE TITLE
Inter-Realm Authentication not working

### ISSUE THREAD

**Issue by michelangelo136** [keycloak/keycloak#31112]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have configured keycloak with 2 Realms, Realm A and Realm B, Realm A is the primary realm with all the users and federation with FreeIPA for authentication and user sync, Realm B will be used by a single application due to time out issues when the application tries to fetch the users on Realm A.

Realm B has been configured to user Realm A as an identity Provider with the following configuration.

Realm B Identity Provider Config:
![image](https://github.com/keycloak/keycloak/assets/47090692/9aaf693a-85fa-4425-af03-db6e3d6cb3df)
![image](https://github.com/keycloak/keycloak/assets/47090692/799256a3-4c5d-42ea-ac1e-80497211b93f)

In the Realm A I have configured a client for the Realm B to use.
![image](https://github.com/keycloak/keycloak/assets/47090692/99f021e3-f6ba-4f9d-8760-b20c9b77e842)
![image](https://github.com/keycloak/keycloak/assets/47090692/14c42481-2f43-4973-b364-062408e52da4)

When I try to login to the application with SSO, I get redirected to the Realm-B login screen, from there, I select the Realm-A authentication and I'm successfully authenticated Authenticated, but when the session should be forwarded to the Realm-B I get the following error in the web ui "Unexpected error when authenticating with identity provider"

In the Keycloak logs I see the following 2 errors.

`2024-07-08 14:34:24,966 INFO  [org.keycloak.events] (executor-thread-698) type="LOGIN", realmId="[REDACTED]-de5a-4b2c-912a-[REDACTED]", realmName="[REDACTED]", clientId="keycloak-[REDACTED]-realm", userId="[REDACTED]-d652-46c7-9704-[REDACTED]", sessionId="[REDACTED]-912c-41cd-986b-[REDACTED]", ipAddress="[REDACTED]", credential_type="webauthn-passwordless", web_authn_authenticator_user_verification_checked="true", auth_method="openid-connect", auth_type="code", public_key_credential_id="[REDACTED]-FVGr80", response_type="code", redirect_uri="https://sso.[REDACTED].com/realms/netbird/broker/keycloak-[REDACTED]-realm/endpoint", consent="no_consent_required", code_id="[REDACTED]-912c-41cd-986b-[REDACTED]", username="[REDACTED]", response_mode="query", authSessionParentId="[REDACTED]-912c-41cd-986b-[REDACTED]", authSessionTabId="[REDACTED]"

2024-07-08 14:34:25,130 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-698) Unexpected response from token endpoint https://sso.[REDACTED].com/realms/[REDACTED]/protocol/openid-connect/token. status=464, response=

2024-07-08 14:34:25,135 ERROR [org.keycloak.events] (executor-thread-698) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="[REDACTED]-50f1-4b6b-bd4a-[REDACTED]", realmName="netbird", clientId="netbird-client", userId="null", ipAddress="[REDACTED]", error="identity_provider_login_failure", code_id="[REDACTED]-4a3f-453d-87dc-[REDACTED]"`

The SSO endpoint is behind an ALB in the public internet, the admin endpoint is directly accessible by the internal net only, there are 2 SSO servers and the public SSO endpoint is loadbalanced between the two, but the admin endpoints are different.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The user is authenticated in Realm-B by using his account in Realm-A

### Actual behavior

The user authenticated from the Realm-A should be authenticated to the Realm-B too, but the Realm-A response to the Realm-B is empty and the Realm-B returns the error "identity_provider_login_failure"

### How to Reproduce?

Create an inter-realm authentication on the same Keycloak instance, set Realm-B to use Realm-A as an authentication provider.

**Comment by sschu** [comment]
@michelangelo136 When I integrate two realms locally, everything works as expected. Therefore, there might be an issue in your network setup preventing this from working. To really check if there is an issue in Keycloak, we need a reproducer i.e. ideally a setup with the docker container so we can recreate the issue.

**Comment by michelangelo136** [comment]
@sschu, The Keycloak server runs directly on the host without docker, I have temporarily disabled the secondary Keycloak server in order to make the troubleshooting easier, the network topology is as follows.

SP application and user are in the same network, the Keycloak server has the admin endpoint directly accessible on port 443, and the sso endpoint (different url) is behind a public ALB with access to port 443.

For testing I added the instance IP in the host file of my computer and of the Keycloak instance in order to bypass the ALB but it still didn't worked.

The keycloak logs return the error "identity_provider_login_failure" with the userId="null"

Is the configuration that I have attached in my previous message correct? I may have configured something incorrectly on the Keycloak UI.

**Comment by rmartinc** [comment]
@michelangelo136 As @sschu has commented this is something that is tested in CI and I personally do a lot to test broker issues. As your logs are reporting there is an error when the initial realm is acceding the token endpoint:

```
2024-07-08 14:34:25,130 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-698) Unexpected response from token endpoint [https://sso.[REDACTED].com/realms/[REDACTED]/protocol/openid-connect/token](https://sso.%5BREDACTED%5D.com/realms/%5BREDACTED%5D/protocol/openid-connect/token). status=464, response=
```

There is an HTTP error 464 returned from the load balancer so probably it is only accepting HTTP2 or similar. You have to check if you can access the token endpoint from the keycloak machine doing a normal POST with HTTP/1.1.
