### ISSUE TITLE
Review filtering of session returned from the sessions cache 

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#31115]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

There is some a dubious code path where we continue searching the different caches even if we know it doesn't match the predicate. 

See https://github.com/keycloak/keycloak/pull/30859#discussion_r1668755619 for the original comment

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

* If an entry is returned from the cache, and it doesn't match the predicate, we shouldn't try any other store.

### Actual behavior

* If we don't have a match locally, we try to get it from the remote store

### How to Reproduce?

This is a code analysis.

**Comment by mhajas** [comment]
We already investigated this some time ago. If I remember correctly, this was because when running in A/A mode and we do 2 consecutive requests 1. changing session in DC1 2. querying session with predicate in DC2 it may happen the second request does not find the session in updated state in DC2. 

The code was added here https://github.com/keycloak/keycloak/pull/4357 with the initial CrossDC support.

**Comment by ahus1** [comment]
I've analyzed this, and this is what I found: 

The current code path is necessary as this implicit behavior is used by the following code:

https://github.com/keycloak/keycloak/blob/4672366eb92fef52782c8615683d24e314d12cae/services/src/main/java/org/keycloak/services/managers/UserSessionCrossDCManager.java#L90-L91

In case you are wondering, the condition is always false. 

This issue should IMHO be tackled once we remove the local-caches-have-remote-caches functionality. I suggest to put this issue to the backlog.

**Comment by pruivo** [comment]
@ahus1 it looks worst now. The database is the source of truth when persistence sessions is enabled and we say in our docs that we can limit the entries stored in the external Infinispan:

```
When using persistent sessions, limit the cache size limit for sessions, offlineSessions, clientSessions, and offlineClientSessions
```

I would say we have an high chance of the entry not being present in the remote cache and, when it happens, it will remove the session from the database. We are basically transforming that method into a `removeSession`.

**Comment by ahus1** [comment]
After an analysis with @pruivo, he showed me a scenario where this could lead to a loss of user sessions in the following scenario: 

* Persistent user sessions are enabled
* External Infinispan (old style) is used and the maximum number of remote cache entries are restricted to 10_000 (as suggested by the docs
* A user session is found in the local cache but not the remote cache because it was evicted in the remote cache (would happen if more than 10_000 user sessions exist)

I'll create a PR for this that will also be backported to KC25.
