### ISSUE TITLE
KC.ORG user attribute shown - even if the organizations feature for the realm is disabled

### ISSUE THREAD

**Issue by alexanderhofstaetter** [keycloak/keycloak#31143]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

even though the ORG feature is disabled for the realm, the user attribute "kc.org" is shown for the user in the admin UI:

![image](https://github.com/keycloak/keycloak/assets/6820505/ea93d227-0870-476d-9062-7dd459bf7889)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

when organizations feature is not enabled for the realm, the attribute is not shown for users in the realm.

### Actual behavior

kc.org is always shown

### How to Reproduce?

enable org feature flag on build; and open any user

**Comment by martin-kanis** [comment]
I think this is worth to fix from UX perspective.
@edewit Can we show this field based on whether organizations are enabled for a realm? Or even better show it only when the user is member of an organization?
Also we should not display the field as mandatory as it is a read-only field. 
One thing to mention is that we plan https://github.com/keycloak/keycloak/issues/30747 in which case we need to figure out a way how to display multiple orgs there.

**Comment by pedroigor** [comment]
The UI renders the fields based on what the server returns as metadata so we should actually fix that on the server side, ideally.

**Comment by pedroigor** [comment]
@martin-kanis Forcing  `false` to the read condition should remove that attribute from the UI. In case unmanaged attributes are enabled the admin will see the attribute in the attributes tab but won't be able to remove or change it. Perhaps it is enough to fix this one.

**Comment by ahus1** [comment]
@pedroigor / @martin-kanis - would you consider this for a backport to KC25?
