### ISSUE TITLE
"Can not update organization group" error when trying to create organisation from REST API

### ISSUE THREAD

**Issue by mamatomarco** [keycloak/keycloak#31144]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

When I invoke the POST http://<keycloakurl>/admin/realms/M1/organizations with this payload
"name": "Acme Srl",
    "attributes": {
        "organizationType": [
            "privateCompany"
        ]
    },
    "domains": [
        {
            "name": "acme",
            "verified": false
        }
    ]
    
I receive the error "Can not update organization group"

If I remove the "attributes" prop, everything is ok and I receive a 201.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Receive a 201 response code

### Actual behavior

I receive a 400 response code with
"errorMessage": "Can not update organization group"

### How to Reproduce?

curl --location 'http://<keycloakurl>/admin/realms/M1/organizations' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "name": "Acme Srl",
    "attributes": {
        "organizationType": [
            "privateCompany"
        ]
    },
    "domains": [
        {
            "name": "acme.it",
            "verified": false
        }
    ]
}'

**Comment by martin-kanis** [comment]
Issue is that the organization is not set in the session context https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/organization/utils/Organizations.java#L60 
It was either removed preliminarly or not not set at all.

**Comment by mamatomarco** [comment]
To which kind of session are you referring to? I'm not managing it through the AdminUI but from a client calling KC through the REST API

**Comment by martin-kanis** [comment]
> To which kind of session are you referring to? I'm not managing it through the AdminUI but from a client calling KC through the REST API

To the internal Keycloak session that is bound to any request. My comment was meant as hint to anyone who will be fixing the bug.
