### ISSUE TITLE
IDP SAML Certificate should be text-area not text

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak#31146]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The SAML Certificate field should be a textarea not a text field.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

![image](https://github.com/keycloak/keycloak/assets/24498435/5af2cd97-0d21-4595-9574-69fc5e630c09)
This is the UI in Keycloak 24.0.5

### Actual behavior

This is the UI in 25.0.1
![image](https://github.com/keycloak/keycloak/assets/24498435/ea391e99-f456-49c4-a3e6-a9a461c84aa3)

### How to Reproduce?

Add a new SAML IDP and check "validate signatures".

### Anything else?

This was fixed once with the following commit: https://github.com/edewit/keycloak-admin-ui/commit/03475f985dd6979f2ed3424a8071a1fca5acdbd4

**Comment by ssilvert** [comment]
Hmm.  Looks like the help icon is gone too.
