### ISSUE TITLE
HTTP metrics not exposed

### ISSUE THREAD

**Issue by SimonelDavid** [keycloak/keycloak#31163]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Hi! I am using Prometheus to scrape keycloak metrics endpoint. The system and jvm data works fine, but I can not see HTTP data, so I want to retrieve data about login, and I found out there are some HTTP request data that this endpoint should expose, but I can not see those.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

To see exposed data related to HTTP from the metrics endpoint.

### Actual behavior

There is no data regarding HTTP exposed by the metrics endpoint.

### How to Reproduce?

Have this configuration for keycloak:
# Configuration file for keycloak

KC_PROXY=edge
KC_HTTP_RELATIVE_PATH=/auth
KC_DB=<db>
KC_DB_URL_HOST=<specified_path>
KC_DB_URL_DATABASE=<database_name>
KC_DB_SCHEMA=public
KC_DB_USERNAME=<username>
KC_DB_PASSWORD=<password>
KAFKA_BOOTSTRAP_SERVERS=<server>
KEYCLOAK_JVM_SIZE=-Xms512m -Xmx1024m
JAVA_OPTS=<some_jvm_options>
INITIAL_USERNAME=<username>
ESCAPE_EMAIL_LINKS=false
STORE_APPROVAL_USERNAMES=<username>
JGROUPS_DISCOVERY_EXTERNAL_IP=<IP>
KC_CACHE_CONFIG_FILE=<file>
KC_METRICS_ENABLED=true

**Comment by sschu** [comment]
I just tested this on KC25.0.1 and I see http metrics.
