### ISSUE TITLE
After creating a new authentication flow and returning to the list, the "Used by" column displays "flow.undefined"

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#31167]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Creating a new authentication flow and returning the to the list of flows, shows a "flow.undefined" value in the "Used by" column.
<img width="384" alt="Bildschirmfoto 2024-07-09 um 17 26 57" src="https://github.com/keycloak/keycloak/assets/2075748/e476dc95-2481-4b19-9111-352e6a371ca8">

### Version

25 / nightly

### Regression

- [X] The issue is a regression

### Expected behavior

the proper "used by" value will be displayed

### Actual behavior

"flow.undefined" is displayed.

### How to Reproduce?

see description

### Anything else?

when reloading the complete browser tab, the flow will be displayed correctly

**Comment by agagancarczyk** [comment]
Closed https://github.com/keycloak/keycloak/issues/31167 as completed via https://github.com/keycloak/keycloak/pull/31133
