### ISSUE TITLE
A lot (really!) dropdown/select fields in admin-ui remain open after selecting an action/entry.

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#31166]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Throughout the entire admin-ui, a lot of dropdowns/select fields remain open if a value or action is selected. In previous releases, these dropdowns closed automatically.
I can' t tell you each and every dropdown, for me this seems to be introduced somehow generally... Right now I've experienced it again at the authentication flow action dropdown in the upper right corner. After e.g. editing the flow info, the drop down remains open, instead of closing automatically.

### Version

25.x / nightly

### Regression

- [X] The issue is a regression

### Expected behavior

see description

### Actual behavior

see description

### How to Reproduce?

see description

**Comment by edewit** [comment]
This is due to the patternfly 5 upgrade they changed how dropdowns work by default
