### ISSUE TITLE
Getting 502 after AuthZ

### ISSUE THREAD

**Issue by kioskOG** [keycloak/keycloak#31178]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I have integrated keycloak(25.0.1) with Apicurio(2.5.11.Final) . Both the services are running in k8s. while i'm hitting apicurio endpoint, request getting redirected to keycloak, once i provide the creds, page start running in loop & throws 502 bad gateway. Adding both service files

keycloak Manifest:-
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keyclok-syslog-test
  name: keycloak
  namespace: keycloak-syslog-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyclok-syslog-test
  template:
    metadata:
      labels:
        app: keyclok-syslog-test
    spec:
      containers:
      - args:
        - start-dev
        - --cache-stack=kubernetes
        env:
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HTTP_HOST
          value: 0.0.0.0
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_FEATURES
          value: hostname:v2
        - name: KC_HTTP_MANAGEMENT_PORT
          value: "9000"
        - name: KC_HTTP_RELATIVE_PATH
          value: /
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: keycloak-admin
              name: keycloak-admin
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: /etc/certs/tls.crt
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value: /etc/certs/tls.key
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: http://<serviceLB>:80
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://keycloak-postgres-service.keycloak-syslog-test.svc.cluster.local:5432/keycloak
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_HOSTNAME_DEBUG
          value: "true"
        - name: KC_HOSTNAME_DEBUG
          value: "true"
        - name: KC_HOSTNAME_ADMIN
          value: http://<serviceLB>:80
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: keycloak-postgres-postgresql
        - name: jgroups.dns.query
          value: keycloak
        - name: KC_LOG
          value: console
        - name: KC_PROXY_HEADERS
          value: xforwarded
        image: quay.io/keycloak/keycloak:25.0.1
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 7600
          name: jgroups
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 9090
          name: httpss
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /realms/master
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: keycloak-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: keycloak-certs
        secret:
          defaultMode: 420
          secretName: keycloak-credential
        
        
        Apicurio manifest:-
        
        apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-sql
  namespace: keycloak-syslog-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry-sql
  template:
    metadata:
      labels:
        app: apicurio-registry-sql
    spec:
      containers:
      - env:
        - name: REGISTRY_DATASOURCE_URL
          value: jdbc:postgresql://apicurio-postgres-service.keycloak-syslog-test.svc.cluster.local:5432/apicurio?user=postgres&password=ApiCurio$#3210
        - name: REGISTRY_UI_CONFIG_APIURL
          value: http://<serviceLB>/apis/registry
        - name: REGISTRY_UI_CONFIG_UIURL
          value: http://<serviceLB>/ui/artifacts
        - name: AUTH_ENABLED
          value: "true"
        - name: KEYCLOAK_URL
          value: http://<serviceLB>
        - name: KEYCLOAK_REALM
          value: registry
        - name: KEYCLOAK_UI_CLIENT_ID
          value: apicurio-registry
        - name: ROLE_BASED_AUTHZ_ENABLED
          value: "true"
        - name: REGISTRY_AUTH_ROLES_ADMIN
          value: sr-admin
        - name: REGISTRY_AUTH_ROLES_DEVELOPER
          value: sr-developer
        image: apicurio/apicurio-registry-sql:apicurio/apicurio-registry-sql:2.5.11.Final
        imagePullPolicy: IfNotPresent
        name: apicurio-registry-sql
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      
      
      
      
<img width="1512" alt="image" src="https://github.com/keycloak/keycloak/assets/31181135/ee6c879f-73f7-45a0-a115-e170caa60383">

ALB error throws "Backend 10.100.6.19 returned invalid header"
<img width="616" alt="image" src="https://github.com/keycloak/keycloak/assets/31181135/6a11a70e-6ccd-4856-8724-a252a7bc250b">

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

it shouldn't throw 502

### Actual behavior

Getting 502

### How to Reproduce?

1. Deploy a postgres for both services seperately,
2. use the provided manifest to deploy keycloak & apicurio
3. Create LB/Nodeport service for both the services
4. Don't forget to create secrets mentioned in manifests

**Comment by mposolda** [comment]
Changing this to cloud-native team.

From quickly looking, not really sure if this is a Keycloak bug (looks more like an "ask for help" with make things working in custom environment, but I may be wrong)
