### ISSUE TITLE
Lack of lang Attribute in Keycloak Admin Console HTML Tag

### ISSUE THREAD

**Issue by rayan-sobhanian** [keycloak/keycloak#31174]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The Keycloak Admin Console lacks the lang attribute in its HTML tag, which is essential for specifying the language/locale of the content. Unlike other themes (such as account, login, and welcome), the Admin Console does not include this attribute.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Please take a lang attribute in html tag, like other themes (e.g. Account and Login)

### Actual behavior

When I want to change the direction of an FTL template (which is transferred to HTML) based on locale and language, it is not difficult for other themes. However, for the admin console, it seems impossible. I attempted to use a JavaScript snippet to achieve this, but unfortunately, I couldn’t find any variable that is passed to the client.

### How to Reproduce?

Please take into account that the HTML generated for the admin console lacks any lang attribute in the HTML tag. Furthermore, when examining the JSON data received from the server, there is no variable or object that can be utilized in JavaScript snippets for this purpose.

### Anything else?

Are there any solution for me to make my admin console responsively Right-to-Left or Left-to-Right base on locale and language?

**Comment by rayan-sobhanian** [comment]
there is no lang attribute in htm tag for Admin console UI

**Comment by jonkoops** [comment]
@edewit you had some work queued up for this right?

**Comment by edewit** [comment]
Yes solved with #30965

**Comment by jonkoops** [comment]
Ah, but that doesn't handle the `lang` attribute. So this would be a different issue. It's a valid enhancement I think.

**Comment by jonkoops** [comment]
@rayan-sobhanian the account and login themes already determine the locale, so if you would like to contribute a fix for this feel free to open up a PR based on that.

**Comment by rayan-sobhanian** [comment]
I’m excited about this opportunity and proud to fix this small bug.

**Comment by jonkoops** [comment]
Great, I will assing this issue to you then. Do let me know if you are not able to pick this up, then I will remove the assignment so someone else can.

**Comment by rayan-sobhanian** [comment]
Thanks, I will try to do that as soon as possible. I'm beginning in one
hour. Before all I need to dive in code and get my hands dirty, and
moreover read your standards and something like that. I am trying to do
that today or at most tomorrow.

**Comment by rayan-sobhanian** [comment]
Hi @Jonkoops,

I apologize for the delay in addressing this issue. I’ve been dealing with some personal difficulties.

Regarding the issue, I’ve implemented a solution by introducing a ‘locale’ variable in org.keycloak.services.resources.admin.AdminConsole from the keycloak-service module. Additionally, I’ve set the lang attribute to ${locale} in the HTML tag within index.ftl for the admin theme. You can find this file by navigating to keycloak-js-parent -> keycloak-admin-ui -> maven-resources -> theme -> keycloak.v2 -> admin -> index.ftl.

However, I noticed your comments in AdminConsole.java, and I’m unsure about your preferred approach. so I decided to be patient for Push-Request. Could you please guide me to better understand your mindset so that I can align my solution accordingly?

Thank you!

**Comment by jonkoops** [comment]
Your approach sounds good, feel free to open a PR.
