### ISSUE TITLE
token exchange: exchange-sequence still fails with `Client session for client '..' not present in user session` when starting on public client

### ISSUE THREAD

**Issue by flyinfish** [keycloak/keycloak#31180]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

this is a follow-up for https://github.com/keycloak/keycloak/issues/30614
thank you for checking again @rmartinc @pedroigor @J0F3

see https://github.com/flyinfish/keycloak-examples/tree/main/token-exchange-sequence#readme

> Initially only [S1: token-exchange starting with grant_type=password on service-1-client](https://github.com/flyinfish/keycloak-examples/tree/main/token-exchange-sequence#s1-token-exchange-starting-with-grant_typepassword-on-service-1-client) worked

> Then issue https://github.com/keycloak/keycloak/issues/30614 fixed [S2: token-exchange starting with grant_type=client_credentials on service-1-client](https://github.com/flyinfish/keycloak-examples/tree/main/token-exchange-sequence#s2-token-exchange-starting-with-grant_typeclient_credentials-on-service-1-client)

> [S3: token-exchange starting with grant_type=password on public-spa](https://github.com/flyinfish/keycloak-examples/tree/main/token-exchange-sequence#s3-token-exchange-starting-with-grant_typepassword-on-public-spa) still fails

### Version

main/latest

### Regression

- [ ] The issue is a regression

### Expected behavior

token exchange sequence should work for as many clients/audiences you like

### Actual behavior

the second exchange fails when initial token was received from public-client

### How to Reproduce?

https://github.com/flyinfish/keycloak-examples/blob/main/token-exchange-sequence/README.md
https://github.com/flyinfish/keycloak-examples/tree/main/token-exchange-sequence#s3-token-exchange-starting-with-grant_typepassword-on-public-spa

https://github.com/flyinfish/keycloak/blob/bug/token-exchange-sequence/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oauth/ClientTokenExchangeTest.java#L448

**Comment by betalb** [comment]
I think that we faced this issue loong time ago, when token exchange was first introduced in KC. Currently we have a workaround for this by doing self-exchange. i.e. once client receives token, it does exchange with audience = client_id, so this client_id appears in session and after that it does exchange for target client. It is additional exchange call, but the only way that currently works.

**Comment by flyinfish** [comment]
Hi @rmartinc 
i tested it and it works. be happy if it would be merged. is there anything left besides review and re-run pipeline?

thanks a lot for  update

**Comment by mposolda** [comment]
Adding to sprint 58 as we have already PR for this.
