### ISSUE TITLE
Show Display Name (if available) and Realm Id on Realm Dropdown Button

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#31183]
### Description

Similar to the realm dropdown list, the realm selector button itself should also show both the Display Name and the Realm Id if available, e.g. like this: 

![image](https://github.com/keycloak/keycloak/assets/1793007/9a00f5c5-7f62-4683-9eda-cfaf96fc22f7)

At the moment the button only shows the display name if that one is set for the realm and therefor hides the id:
![image](https://github.com/keycloak/keycloak/assets/1793007/9fe1bd0a-f23b-4442-85de-3a45b0583ffe)

I can see where in some use cases you want the display name to be the same between realms and therefor you cant see which realm you currently have selected if the id (which is unique) is not displayed on the button itself.

Follow up of https://github.com/keycloak/keycloak/issues/17735 

### Motivation

Bring consistency to the realm dropdown by showing the same thing in the button as in the dropdown list.

**Comment by thomasdarimont** [comment]
So does this issue mean to change this:
<img width="292" alt="image" src="https://github.com/user-attachments/assets/1b55ba22-226f-4242-b4ab-f93327645f48">
to this
<img width="564" alt="image" src="https://github.com/user-attachments/assets/b6d32b84-8112-4ddb-8cdf-9bdabb474f67">
?

Realm name: demo
Realm Display Name: Demo Realm
