### ISSUE TITLE
Admin user can be updated with another custom realm's settings

### ISSUE THREAD

**Issue by yoanaenikova** [keycloak/keycloak#31181]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

If you are logged in with the master admin user, you can view master realm users through another custom realm.
The endpoint for getting all users of a newly created realm returns an empty array but if you try to query the users by the master admin user's ID, it will be returned no matter the realm specified in the path.
Example: .../auth/admin/realms/test-realm/users returns []
Example: .../auth/admin/realms/test-realm/users/<master_admin_user_id> returns the master admin user
If you try to update the same master admin user through the custom realm, those realm's settings will be applied and not the user realm's settings. This way a master user can be modified through any of the realms with any kind of configurations, ignoring the user realm's configurations.

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I should not be able to view or modify a master user through another realm.

### Actual behavior

Master users can be viewed or modified by another realm.

### How to Reproduce?

1. Open the Keycloak admin and log in with the master admin user
2. Create a new custom realm in Keycloak
3. Go to Realm Settings -> Login
4. Enable Email as username and Login with email
5. Go to Realm Settings -> Email
6. Click on the link - Configure e-mail address (the admin user you are currently logged in should not have an email address set)
7. You will be redirected to a similar URL .../test-realm/users/<master_admin_user_id>/settings where the master admin user is visible through the test-realm.
8. Set the email to a dummy one e.g. admin@admin.com and save
9. The master admin user now has the same username as the email - admin@admin.com, because the settings from the custom test-realm are applied.

**Comment by yoanaenikova** [comment]
I confirm that the same behaviour is reproducible with the latest release.

**Comment by pedroigor** [comment]
@yoanaenikova The reason why you can do that is because the user you are authenticating is the master admin user. I agree it is a weird situation because you are accessing the master admin account from some random realm.
