### ISSUE TITLE
Email Verification Works in the Same Browser but Fails Across Different Browsers

### ISSUE THREAD

**Issue by tarek0174** [keycloak/keycloak#31185]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

usecase:
- Using Keycloak for user authentication and email verification.
- Email verification works successfully when the verification link is opened in the same browser where the verification email was initiated.
- When attempting to verify the email by opening the verification link in a different browser, the email verification process indicates  success but the email remains unverified when trying to access the website.

### Version

21.0.2 , 25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

i want to be able to verify the account in different browser is that possible ? 

### Actual behavior

 after verifying the account from different browser ->the email remains unverified when trying to access the website.

### How to Reproduce?

create an account in keycloak with  required action to verify the email 
try to verify the account in a new browser 
result : account still not verified 

### Anything else?

i think the cause of the problem is accrued because of the cookies that keycloak creating during registration. AUTH_SESSION_ID and KC_RESTART
Because when I close the browser window these cookies are no more in a browser.
i'm getting the same behavior with the last version **25.0.1**

**Comment by rmartinc** [comment]
I cannot reproduce this. I have added a verify_email action to a user. Processed the login in a private window, when the email is sent I closed that window. I opened a new private window and completed the email verification in this new browser window. The email verification succeeded and the email is marked as verified in the user.

What am I missing? Can you please explain in more detail what is your problem?

**Comment by tarek0174** [comment]
thanks @rmartinc, i appreciate your help, I discovered that when the verification link is opened in a different browser from the one where the login process started, an action is added that needs to be processed to verify the account (the action URI field is filled). Since I am using my own custom theme with Keycloak, I did not handle this case.

**Comment by Anakael** [comment]
Getting the same behavior on keykcloak 26.1.0 even on standard theme.

**Comment by ParvinderjitSF** [comment]
encountered the same issue on my side as well

**Comment by maoudia-via** [comment]
Also encountering this issue. 
Steps to reproduce: 
- Sign up on chrome. 
- Open verification link in Safari. 
- See message : "Restart login cookie not found".
