### ISSUE TITLE
Realm export - duplicated elements in browser flow. Organization user must click login button multiple times.

### ISSUE THREAD

**Issue by osajdapawel** [keycloak/keycloak#31182]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Bug happens during exporting to json previously imported realm from json.
Some elements in export file in authenticationExecutions of authenticationFlows  (**e.g browser flow**) are duplicated each time export is invoked.

For example if you develop app and exports realm to json than imports the realm during deploy, make changes and export again authentication flows elements are redundant. 

In context of organization when identity-first login (only email/username) is enabled duplicating elements makes user unable to login. 
User must press login button as many times as the count of realm exports bcs auth flow steps are redundant.

Left col:    base import file
Right col: exported realm that was previously imported
![image](https://github.com/keycloak/keycloak/assets/50982515/d623c792-433f-4ef6-affe-3fd22f0fb4ce)

Login button must be pressed as many times as export happend

Left col:    after import
Right col: exported realm that was previously imported
![image](https://github.com/keycloak/keycloak/assets/50982515/25ea0056-c8e2-4e8f-bd4d-6ba3cc2ba389)

Browser flow view:
![image](https://github.com/keycloak/keycloak/assets/50982515/ae9426d2-7622-4656-9e57-b1668fd25a0b)

### Version

Nightly (999.0.0-SNAPSHOT)

### Regression

- [X] The issue is a regression

### Expected behavior

Export feature not duplicates autheniticationExecutions steps in authentication flows in export.json file (e.g browser flow).

Organization user doesn't have to press login button as many times as export happend (in _identity-first login_ with organizations enabled)

### Actual behavior

Authentication flows elements/steps are duplicated each time export happens.

When organizations enabled and _identity-first login_ (only email/username) user press button one time to be prompt for password.

### How to Reproduce?

I got webapp that uses keycloak to secure:

1. Create realm

2. Enable organization + add some organization
3. Export realm to json file
4. Import realm with the file (I build new container and then import from admin UI console)

5. Repeat steps 2, 3 and 4 (simulates development process)
6. Add user with password, add organization (organizations aren't preserved while export)

7. Try to log user in to application
8. You have to press login as many times as count of the exports.

**Comment by pedroigor** [comment]
@osajdapawel Sent https://github.com/keycloak/keycloak/pull/31346. Even though we have a check to prevent this it was wrong and not really checking the presence of the authenticator when using sub-flows.
