### ISSUE TITLE
Recaptcha links changed in the Google Docs

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#31187]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The links to the Google docs changed, and the external links check started to report problems: 

https://github.com/keycloak/keycloak/actions/runs/9873514570/job/27266069376

```
Error:    ExternalLinksTest.checkExternalLinks:41 Broken links (2) in guide 'server_admin': 
		- https://cloud.google.com/recaptcha-enterprise/docs/choose-key-type (invalid redirect to /recaptcha/docs/choose-key-type)
		- https://cloud.google.com/recaptcha-enterprise/docs/interpret-assessment-website#interpret_scores (invalid redirect to /recaptcha/docs/interpret-assessment-website)

```

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The links should point to a valid URL

### Actual behavior

The links are redirected by Google to a new location.

### How to Reproduce?

See job above.

**Comment by ahus1** [comment]
@derlin - I know you've been involved in the docs for this feature in the past, and it seems that there has been a change in the docs Google provides.

May I ask you to:

* Review the redirects that Google reports
* Create a PR with updated links pointing to the most appropriate place in the docs?

As it seems to me both links are in the file `proc-enabling-recaptcha.adoc`. 

As we want to fix this also for Keycloak 25, I'd appreciate if you could first create a PR for the `main` branch, and then another one for the `release/25.0` branch.

Thanks,
Alexander

**Comment by derlin** [comment]
@ahus1 on it, you can assign it to me.

**Comment by ahus1** [comment]
Thank you, @derlin, for fixing this!
