### ISSUE TITLE
#kc-form-options div not wrapping its content correctly in login-password.ftl

### ISSUE THREAD

**Issue by DevDuki** [keycloak/keycloak#31216]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

In the `login-password.ftl` starting at line 33, the div element with the id `kc-form-options` is not wrapping its content. The content is placed a sibling element instead on line 35. (see snippet bellow)
```html
<div id="kc-form-options">
</div>
<div class="${properties.kcFormOptionsWrapperClass!}">
    <#if realm.resetPasswordAllowed>
        <span><a tabindex="5"
                 href="${url.loginResetCredentialsUrl}">${msg("doForgotPassword")}</a></span>
    </#if>
</div>
```

### Version

25.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect the content to be inside the `kc-form-options` div, like in other ftls. (See snippet below)
```html
<div id="kc-form-options">
  <div class="${properties.kcFormOptionsWrapperClass!}">
      <#if realm.resetPasswordAllowed>
          <span><a tabindex="5"
                   href="${url.loginResetCredentialsUrl}">${msg("doForgotPassword")}</a></span>
      </#if>
  </div>
</div>
```

### Actual behavior

Wrong rendering in the ui

### How to Reproduce?

checkout branch `release/25.0` go to `src/main/resources/theme/base/login/login-password.ftl`

**Comment by jonkoops** [comment]
Thanks for reporting this @DevDuki. If you are up for it we'd welcome a PR to fix the problem.

**Comment by DevDuki** [comment]
@jonkoops Sure, but for some reason I cannot create a branch directly from this issue

**Comment by jonkoops** [comment]
@DevDuki you'll have to fork the Keycloak repository, I recommend you read GitHub's documentation on [contributing to a project](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project) and our own [contribution guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md).
