### ISSUE TITLE
[Docs] Broken link in Server Admin guide for JWT_Auth wiki

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#31219]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

External links tests in the Keycloak CI fails with the below reported broken links, out of which the JWT_Auth wiki seems to have moved into the [GitHub](https://github.com/eclipse/microprofile/wiki/JWT_Auth) instead as pointed out by @rmartinc 

Failed CI run: https://github.com/keycloak/keycloak/actions/runs/9883280723/job/27297742928
```
Error:  Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 42.95 s <<< FAILURE! - in org.keycloak.documentation.test.ExternalLinksTest
Error:  checkExternalLinks{String}[4]  Time elapsed: 18.33 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Broken links (2) in guide 'server_admin': 
		- https://fedoraproject.org/wiki/Features/SSSD (invalid status code 503)
		- https://wiki.eclipse.org/MicroProfile/JWT_Auth (invalid status code 404)
```

### Version

nightly (7/11/2024)

### Regression

- [ ] The issue is a regression

### Expected behavior

Our docs and server guides should not point to broken links.

### Actual behavior

Seems like one or more of the docs references point to outdated hyperlinks.

### How to Reproduce?

refer to the CI failed run.

**Comment by ahus1** [comment]
Thank you @rmartinc for the fix. Please provide backports to 22, 24, and 25 with this change as well. Thanks!
