### ISSUE TITLE
Realm  - token not found in realm account 

### ISSUE THREAD

**Issue by sdeemer1027** [keycloak/keycloak#31231]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Request Id: 7327aadd-3553-45c2-8b5a-58bffc1c8600
Correlation Id: a8ead046-f35e-4e3e-ba24-b95afd9f9e22
Timestamp: 2024-07-11T21:05:22Z
Message: AADSTS700016: Application with identifier 'f3bdc667-b751-4e10-8783-ab47ba78d2ee' was not found in the directory 'Walkabout'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

SSO is technically working however it is not working 
I am told on Microsoft side technically the SSO is logging in and I can see this and agree 
They said nothing has changed on their end 

I have seen the Billing change a plan then a few days later SSO Stopped log in 
they said we must have changed KeyCloak - We Had NOT changed a thing 

after more info I seen we are on keycloak 23.0.1 --- after planning and testing we went to 25.0.0 
Error is the same as before 

I have seen the REALM needs to be reconfigured in the admin 
looking further I can not see the ADMIN section in keycloak  
This is the Dev Server I play around in but production is the same That Said 

KeyCloak Has an admin but I am not aware how to get it running how to create the admin user to get it running and yet how to get the administration UI to Load as I see only a link then it is LOADING ...... Never even asking me for a user name I am not sure how to yet create 
Any Support in any or All the Areas I am just trying to get SSO to login but it never gets through the REALM just gives deep in the back 502 Gateway error 

### Actual behavior

502 Gateway error if SSO is attempted

### How to Reproduce?

just click Microsoft link on our login page

**Comment by jonkoops** [comment]
Please provide steps to reproduce this issue from a fresh Keycloak installation. We cannot fix bugs that cannot be reproduced.
