### ISSUE TITLE
[Scalability of IDPs] Introduce new SPI / Provider for IDPs

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#31249]
### Description

With the introduction of a new provider for IDPs we will be able to decouple the management of identity providers from the realm model, which will allow us to introduce new methods for better searching IDPs at the DB level (e.g. `searchByAlias`, `searchByAttribute`, pagination, etc).

**Comment by thomasdarimont** [comment]
@sguilhen great to have this new capability to let users plug-in their own storage for identity providers!
Would it be possible to change the name of the SPI classes though? If the intent of the new `IDPProvider` SPI is to manage Identity provider storage, then why not just name that provider `IdentityProviderStorageProvider`?

**Comment by sguilhen** [comment]
@thomasdarimont I have to agree that the name is not ideal - @pedroigor also suggested the change to something very similar to what you're suggesting. I'll update the name.
