### ISSUE TITLE
Some bugs found with PVS-Studio

### ISSUE THREAD

**Issue by feeelin** [keycloak/keycloak#31259]
### Description

Hello!

My name is Valery Filatov, I am DevRel of PVS-Studio company, we are developing a static code analyzer. We have released an article with the check of this project and found some errors:

https://pvs-studio.com/en/blog/posts/java/1142/.

We hope that fixing these errors will help improve the project's code base!

**Comment by jonkoops** [comment]
Thanks, but we're not interested in further automated tooling. If you found specific bugs please report them individually in our bug tracker with accurate information on how to reproduce them.

**Comment by Px-x64** [comment]
@jonkoops am I understand your point correct that "bugs found by automatic tools are not bugs", and code in provided examples is working right?

**Comment by jonkoops** [comment]
Not sure what you mean. But bugs found by automatic tools **without a reproducible example** will be considered invalid.

**Comment by Px-x64** [comment]
@jonkoops 
You didn't read the report, do you? ))

**Comment by jonkoops** [comment]
I did.

**Comment by Px-x64** [comment]
> I did.

Okay, so for this code, for example

`
    StaxUtil.writeAttribute(
      writer, 
      "xsi", 
      JBossSAMLURIConstants.XSI_NSURI.get(), 
      "type", 
      "xs:" + attributeValue.getXMLSchemaType().getLocalPart()   // <=
    ); 

    if (attributeValue == null) {
      StaxUtil.writeAttribute(
        writer, 
        "xsi", 
        JBossSAMLURIConstants.XSI_NSURI.get(), 
        "nil", 
        "true"
      );
    ....`
You expect from the reporter to find out the case, when "attributeValue " is null, see KeyCloak crashing, and only then it would be accepted as valid bug? Before this happened it is okay to utilize value which could be null, and then test it for null? ))

**Comment by jonkoops** [comment]
I would expect a reporter to do some due diligence and explain why something causes a bug. If it can be empirically proven that it is a bug then of course we will fix it. What I am simply saying here is that we don't accept reports with "my code scanner found this, I have not spend any time understanding this code". That just creates more work for the team (we have a backlog of ~1800 issues), and such issues are likely to be closed or be asked for more details and eventually closed out by the bot :man_shrugging:

**Comment by Px-x64** [comment]
So what you saying is this call - `attributeValue.getXMLSchemaType().getLocalPart()` without "due diligence" would not fail with NPE, even if attributeValue is null, and only if "due diligence" would be done, NPE will finally start occurring, right?

**Comment by jonkoops** [comment]
I am not saying anything of the sort. I am not commenting on any specific code here. If you have found a bug please report it as such. This issue is closed, so I will mark it as resolved. If you want to start a discussion I recommend the forums.
