### ISSUE TITLE
multiple ldap url's not working on one realm

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#31267]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have a realm where I connect to one ldap instance. There, I configured to url's for redundancy.
The thing is that whenever I test the connection, it gives me this error on gui:

<img width="665" alt="Screenshot 2024-07-13 at 07 33 56" src="https://github.com/user-attachments/assets/58afa737-36af-496e-aeb4-3974e26ef9cd">

Individually, both url's work fine.
I see nothing at all on the logs.
When I save it, I can still search users. But if the first url is down, it doesn't retrieve users using the second url

In a brand new realm, I can do this normally, and I got no error whatsoever. So something might be broken underneath.

### Version

25.0.1

### Regression

- [x] The issue is a regression

### Expected behavior

Get a successful test connection when using multiple ldap url's.
Getting redundancy by setting up two url's.

### Actual behavior

I get an error when testing two otherwise working ldap urls when configuring ldap user storage to use them.
I don't get the second url to work. When the first url is down, no search is made on the second.

### How to Reproduce?

I don't know. I can't reproduce this on another realm.

**Comment by martin-kanis** [comment]
@oculos  Sorry, we can't work on this if there are no steps to reproduce and a stacktrace with an error.

**Comment by oculos** [comment]
@martin-kanis Here's a trace log I generated. I can't see anything there that looks relatable.
[trace.log](https://github.com/user-attachments/files/16232869/trace.log)

**Comment by thomasdarimont** [comment]
Thanks for reporting that @oculos. I could verify the issue with Keycloak 25.0.1 and created a fix for that. Feel free to give it a try.

**Comment by oculos** [comment]
> Thanks for reporting that @oculos. I could verify the issue with Keycloak 25.0.1 and created a fix for that. Feel free to give it a try.

Thanks a lot @thomasdarimont! I'll give it a try. But what I find odd is that this bug only could be reproduced in one realm. But I'll try the fix.

**Comment by ahus1** [comment]
Looking at the code change done by @thomasdarimont in the linked PR, this seems to be a regression caused by #30434

cc: @rmartinc, @mposolda

**Comment by ahus1** [comment]
@thomasdarimont - please prepare backports for KC 22/24/25 for this change from the commit merged to main. 

Thanks!

**Comment by rmartinc** [comment]
@thomasdarimont We need the backport asap, so I'm prep raring them right now. Please do not spend time on it. I don't want both work on them. Thanks!
