### ISSUE TITLE
Account console won't load when using URL having a path as hostname config

### ISSUE THREAD

**Issue by uliw-tech** [keycloak/keycloak#31276]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When for the "hostname" config an URL is configured that has a path (e.g. "https://auth.remote.net/auth/") (see [docker-compose.yaml.txt](https://github.com/user-attachments/files/16227872/docker-compose.yaml.txt)), then the account console won't load (see 
![Screenshot from 2024-07-14 17-17-47](https://github.com/user-attachments/assets/8bb99dc0-ea3b-4ea2-ab1a-52b1f6b811dd))
The reason is that some resource files cannot be loaded because they have the wrong path in the URL (see 
![wrong-resource-urls](https://github.com/user-attachments/assets/4bc8be89-4ba2-4d79-aaa0-88a0e73a6d33)
).
E.g. a resource file is loaded from "/resources/108fu/common/keycloak/vendor/react/react.production.min.js" but it should actually be loaded from "/auth/resources/108fu/common/keycloak/vendor/react/react.production.min.js"
Other resource files however are loaded from the correct location (e.g. "/auth/resources/108fu/account/keycloak.v3/assets/main-RBOOfBld.js")

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Account console is loaded correctly.

### Actual behavior

Account console is not loaded and hangs (see 
![Screenshot from 2024-07-14 17-17-47](https://github.com/user-attachments/assets/8bb99dc0-ea3b-4ea2-ab1a-52b1f6b811dd))

### How to Reproduce?

1. Configure docker the way I did (see [docker-compose.yaml.txt](https://github.com/user-attachments/files/16227872/docker-compose.yaml.txt))
2. Navigate to "https://keycloak.remote.net/" in the browser
3. Log on to an admin account
4. After logging in, in the drop-down on the top right, select "Manage account"

**Comment by uliw-tech** [comment]
> This is likely a duplicate of #30541, @uliw-tech can you test the latest [nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly) and let us know if the problem persists?
I tested with the nightly release. Indeed, the bug is gone in the nightly release. In the nightly release the account console loads as expected.

**Comment by jonkoops** [comment]
Duplicate of #30541

**Comment by jonkoops** [comment]
Thanks for confirming the issue is fixed @uliw-tech. The fix should arrive in version 25.0.2, which will be released soon.

**Comment by uliw-tech** [comment]
> Thanks for confirming the issue is fixed @uliw-tech. The fix should arrive in version 25.0.2, which will be released soon.

No problem. Thank you for processing the issue and explaining me when it will be fixed.
