### ISSUE TITLE
https://host.example.com/auth/admin/master/console/ returns "somethingWentWrong"

### ISSUE THREAD

**Issue by kvvloten** [keycloak/keycloak#31270]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Keycloak admin console (`https://host.example.com/auth/admin/master/console/`) does not load from browser (Firefox):

![afbeelding](https://github.com/user-attachments/assets/fd1d4a74-a10f-49bc-8f27-bca968b611bf)

This happens after following the advice in `keycloak.log` to remove `proxy=edge`:

```
2024-07-13 23:59:52,657 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
        - proxy: Use proxy-headers.
Consult the Release Notes for details.
```

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Firefox loads admin UI and displays login form

### Actual behavior

Firefox loads admin UI shows blank window with text "somethingWentWrong" (as in the image above)

### How to Reproduce?

Apache is setup as reverse-proxy and ssl terminator.

Fragment of apache's revproxy conf:
```
<Location /auth/>
    AllowMethods GET POST PUT DELETE
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"
    ProxyPass http://127.0.0.1:8080/auth/
    ProxyPassReverse http://127.0.0.1:8080/auth/
</Location>
```

New keycloak.conf fragment that reproduces the failure:
```
http-enabled=true

http-host=127.0.0.1
http-port=8080
hostname-strict=false
http-relative-path=auth
```

Previous keycloak.conf fragment which works as expected:
```
proxy=edge

http-host=127.0.0.1
http-port=8080
hostname-strict=false
http-relative-path=auth
```

Is there something in the configs to improve or is it an issue in the javascript sent to the browser and hence a bug?

I tried 24.0.5 and 25.0.1 and both show the same behavior.

**Comment by jonkoops** [comment]
> proxy: Use proxy-headers.

Did you try using `proxy-headers` as the CLI suggests? See our [reverse proxy](https://www.keycloak.org/server/reverseproxy) documentation.

**Comment by kvvloten** [comment]
Good point, I missed that bit of documentation.

I have just tested with `proxy-headers=xforwarded` and indeed it does the trick.

Thanks for your help, issue solved.

-- Kees.
