### ISSUE TITLE
Recovery code List shows duplicate numeration

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#31287]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

The list of the recovery codes shows duplicated numeration:
![image](https://github.com/user-attachments/assets/3fbb2b8e-8036-4c02-b8a0-27af84ea292b)

```
1. 1: BIS1-M9XQ-QK76
2. 2: 287S-N8JY-B94S
```

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The list should only show a single numeration.
![image](https://github.com/user-attachments/assets/744fe5c3-735d-42fd-9f99-08f667224848)

### Actual behavior

Duplicate numeration is shown in the browser form.

### How to Reproduce?

Generate a new set of recovery codes.

### Anything else?

![image](https://github.com/user-attachments/assets/75c013aa-b346-42f5-aee1-8bf0e3447151)

**Comment by rmartinc** [comment]
@thomasdarimont I think this is duplicate of #31021. @edewit already sent a PR to fix some issues with codes for the login v2.

**Comment by thomasdarimont** [comment]
Oh, I missed that thanks!
