### ISSUE TITLE
NPM library of account-ui is unusable (@keycloak/keycloak-account-ui version 25.0.1)

### ISSUE THREAD

**Issue by gdelbos** [keycloak/keycloak#31299]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The current library is using `main.tsx` to export the object.
The types are correctly handled and we can create the project and import the expected components/functions/etc.

However, when we want to build the project, we are encountering the following issue: 
`"Header" is not exported by "node_modules/.pnpm/@keycloak+keycloak-account-ui@25.0.1/node_modules/@keycloak/keycloak-account-ui/lib/keycloak-account-ui.js"`
 
This has been corrected with the PR #30645.
However, this correction is not present in the release `25.0.1`.

See https://github.com/keycloak/keycloak/blob/25.0.1/js/apps/account-ui/vite.config.ts
You can also directly download the NPM artifact and check its content. 
https://registry.npmjs.org/@keycloak/keycloak-account-ui/-/keycloak-account-ui-25.0.1.tgz

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Being able to build a project using this library

### Actual behavior

Cannot build a project using this library

### How to Reproduce?

- Create a project
- Add the library @keycloak/keycloak-account-ui with the version 25.0.1
- Import one of the component exported by the library
- Build

**Comment by antoine-roux** [comment]
The commit did not make it into version `25.0.2`.
The library hosted on NPM repos is still unusable.

**Comment by edewit** [comment]
as a workaround you can still use 25.0.1

**Comment by gdelbos** [comment]
That's the point @edewit : we can't.
Because the 25.0.1 does not have this correction.

**Comment by edewit** [comment]
Sorry I meant to say 25.0.0

**Comment by edewit** [comment]
fixed in 25.0.2

**Comment by UncleSamSwiss** [comment]
@edewit You meant "fixed in 25.0.3", right? Because that isn't released yet.

**Comment by UncleSamSwiss** [comment]
@gdelbos Were you able to get this working? When I go back to 25.0.0, I get the following error:
```
TS2305: Module '"@keycloak/keycloak-account-ui"' has no exported member 'KeycloakProvider'.
```

**Comment by edewit** [comment]
fixed in the 25.0.3 release

**Comment by edewit** [comment]
oh 25.0.3 got skipped so it's 25.0.4

**Comment by garronej** [comment]
Just to let you guys know, Keycloakify provides a good developer experience to work with this package.  
https://docs.keycloakify.dev/account-theme/single-page
