### ISSUE TITLE
Hide save / update buttons in account console for READ_ONLY federated accounts

### ISSUE THREAD

**Issue by darius-m** [keycloak/keycloak#31304]
### Description

Users retrieved from a READ_ONLY federation are not able to update their account information. As such, the "Save" and "Cancel" buttons in the "Personal info" tab should not be displayed, since they don't do anything (the fields that contain the user's information are already disabled). By the same token, the "Update" button for the password in the "Signing in" tab should also be hidden, since attempting to reset the password results in the error message "Federated storage is not writable".

### Motivation

The user information and password cannot be updated when the user federation is set to READ_ONLY. The buttons are confusing for the users, since they lead them to believe that the data can be updated, when that is not the case.

### Details

The buttons to update the information from the federated storage should be hidden when the user comes from a READ_ONLY federation. Ideally, the fields with the user data would be transformed into span or paragraph elements, but simply hiding the buttons and leaving the inputs as-is would achieve the desired results.

**Comment by ssilvert** [comment]
This sounds more like a bug to me.  We will look into this and try to get it fixed.

**Comment by darius-m** [comment]
Hi! Thanks for the contribution. Commit d9555e4c9fc1b5ae6cb7db0664fa46ef22b98edd only appears to change the behavior in the admin console, not the user account console, is that correct?

In the issue I was asking if it would be possible to hide the buttons entirely in the account console (ideally regular users should not even see the account information page as a form if they cannot edit the data). The same logic applies to the password update button.

**Comment by jonkoops** [comment]
@darius-m could you create a new issue for this linking to the discussion here? This will allow us to follow our regular triage proccess. Thanks!

**Comment by edewit** [comment]
@darius-m right reading is hard created a new PR that does the same thing for the account

**Comment by darius-m** [comment]
Thanks for handling things so quickly! Is there any reason why the buttons are disabled instead of hiding or removing them when the user does not have the option to enable the button? For example, I would expect a disabled button in a form where some required information is missing or a sanity check has failed, but it would become enabled if the error is corrected; in contrast, a "Site administration" button would be hidden / missing entirely when the user does not have the appropriate permissions and there is nothing that they can do to change that. I very rarely handle UI/UX, so there are definitely a lot of things that I fail to consider in UI design.

The password update button also needs to be disabled / hidden, for the reasons mentioned in the issue, but I assume that would be a different PR since it's more complex.

**Comment by edewit** [comment]
right, changed it to remove the buttons
