### ISSUE TITLE
Master Realm Using Wrong Auth Method - can't login as Admin

### ISSUE THREAD

**Issue by ReggieCarey** [keycloak/keycloak#31302]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

# I can no longer login to the Admin User to my Keycloak Master Realm.

I've got a bitnami based helm chart for installing Keycloak.  I've be able to admin using the configured admin account "user" and a custom password.  It no longer works.  I've seen others complain about this but nothing in the way of a solution.  I wanted to point out an observation that may indicate the root failure.

In my case I've got the master realm - was set up for just UN/PW login
Ive got additional realms some of which use OPENID-CONNECT.
For some reason, my master realm thinks it should authenticate users via OIDC.

See the log:
```
2024-07-15T10:38:16-04:00 2024-07-15 14:38:16,171 WARN  [org.keycloak.events] (executor-thread-1) type=LOGIN_ERROR, realmId=<REALM GUID>, clientId=security-admin-console, userId=null, ipAddress=<INTERNAL-IP>, error=user_not_found, auth_method=openid-connect, auth_type=code, redirect_uri=https://keycloak.example.com/auth/admin/master/console/, code_id=<CODE_ID_GUID>, username=user
```

Am I missing something? How can I resolve this?

### Version

Revision 12, Version 17.2.0, App Version 22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the admin "user" and associated configured credentials would work to allow me to admin my Keycloak environment.

### Actual behavior

Access denied - Invalid username or password

### How to Reproduce?

I do not know how it got to this state and I have no idea how to resolve it.  Hence this issue report.

### Anything else?

API authentication with this user also fails.  I would love to be able to upgrade but I'm locked out.

**Comment by sschu** [comment]
Unless you find a way to reproduce the problem, I cannot help you. We also don't support the bitnami helm chart (you could ask there for help) and you are also not using the latest version. Any problem in Keycloak needs to be verified in the latest version. It is also fine that the security admin console used OIDC for authentication, it gets a token from Keycloak to then use it against the admin API.
