### ISSUE TITLE
Convert chapter 1 : Planning for securing applications and services

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31328]

**Comment by graziang** [comment]
Should we remove this chapter?

**Comment by rmartinc** [comment]
@mposolda @graziang I'm using this chapter to send a PR that checks everything again: links, order, possible missing chapters,... My idea is creating the introduction chapter but hidden (there was no box in the securing-apps). It will be created in the document (for RHBK documentation which has no web).

**Comment by rmartinc** [comment]
It was decided in today's meeting that the chapter will be visible as a introduction guide.
