### ISSUE TITLE
Convert chapter 3: Using SAML to secure applications and services

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31330]

**Comment by ahus1** [comment]
@rmartinc - it seems to me that after this change the external links broken as there is an unknown anchor in `https://www.keycloak.org/guides#securing-apps` - see https://github.com/keycloak/keycloak/actions/runs/10075330940/job/27853374728?pr=31303

Can you please create an issue, and resolve it while we wait for this change to be deployed to the production site by adding an entry to the file `ignored-links`? Thanks!

Unfortunately it is unclear to me why the check didn't report this on the original PR.

**Comment by rmartinc** [comment]
Should be working now.

**Comment by ahus1** [comment]
Thanks, confirmed.
