### ISSUE TITLE
Organizations: Default browser flow is modified instead of built-in browser flow

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#31347]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

The scenario is the following:
- Startup of a KC instance with organization feature enabled
- Import a realm during startup that has a custom authentication flow bound as the default browser flow

The organization feature re-configures the default browser flow although it is not the built-in browser flow but a custom flow.

I cannot remove the organization sub-flow, because it is marked as built-in.

![image](https://github.com/user-attachments/assets/37642de3-4033-4b85-9f13-d2a677222160)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The built-in browser flow should be re-configured by the organization feature instead of the bound authentication flow.

### Actual behavior

The organization features reconfigures whatever flow is bound as default browser flow.

### How to Reproduce?

- checkout git tag v25.0.0 from https://github.com/sventorben/keycloak-home-idp-discovery
- build the project with `mvn clean package`
- run docker: `docker compose up -d`
- navigate your browser to http://localhost:8080
- login with username admin and password admin
- open the `test-realm`
- Navigate to authentication
- Check the home-idp-discovery-flow and check the browser flow

### Anything else?

I think the issues arises from this line of code: https://github.com/keycloak/keycloak/pull/29785/files#diff-c38dffa84cef8bdac1a1d97df798583d3b6e86ee5e83ac6746bff5a04775501aR141
It looks up the current default browser flow instead of the built-in one.

The same issue may arise with the first broker login flow a few lines above.

**Comment by sguilhen** [comment]
This is related to another issue (https://github.com/keycloak/keycloak/issues/31182) and I think the solution proposed by @pedroigor  in https://github.com/keycloak/keycloak/pull/31346 will also solve your issue because we're moving the code that manipulates the flows to the `DefaultAuthenticationFlows` where it will be applied only upon new realm creation and will affect only the built-in flow.

**Comment by sventorben** [comment]
Yes, that should fix it. Although, it still would not allow me to remove the organization sub-flow that already was created in the wrong flow.

It does not affect me personally, yet. But if someone activated that feature on an actual running instance and not for testing purpose, this may be an issue now for them.

**Comment by sguilhen** [comment]
As this can only happen when importing a previously exported realm, an easy workaround for anyone who runs into this situation is to remove the realm and re-import with the feature disabled.

**Comment by pedroigor** [comment]
Yeah, it should be fixed by https://github.com/keycloak/keycloak/issues/31182. Just run the steps you provided and the default browser flow is no longer updated with the organization subflow.
