### ISSUE TITLE
Hidden options shown in help all

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#31340]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Options that are marked as hidden and are also conditional enabled can be shown in the help all.

### Version

latest

### Regression

- [X] The issue is a regression

### Expected behavior

Hidden options should always remain hidden.

### Actual behavior

Some of the conditionally enabled options will still be displayed.

### How to Reproduce?

run help all

**Comment by mabartos** [comment]
@shawkins As #31207 has already been merged, this issue has also been fixed, right? As it's considered as regression, the backport should be suitable here.
