### ISSUE TITLE
Infinite loop after login to master realm

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#31377]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

After login to the admin console, the url keeps changing the session state as if on a loop, and we can no longer access the console. 

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should see the console

### Actual behavior

What happened here was this:
This is our test instance, and I wanted to set a required idp redirect on a realm. But I was’t paying attention, and configured this on the master realm instead. 

So what I did was that I used the API to fix this, and we could finally log in again with username and password. But then we got this loop. 

On the log, the only thing we see is this: 

```
2024-07-17 12:04:16,637 WARN  [org.keycloak.events] (executor-thread-6) type="REFRESH_TOKEN_ERROR", realmId="142d7345-b710-4466-a05a-7e6aa4f896834", realmName="master", clientId="security-admin-console", userId="null", ipAddress="[2001:720:100:4055::51]", error="invalid_token", reason="Invalid refresh token", grant_type="refresh_token", client_auth_method="client-secret"
```
We rolled back the database, redeployed the images on OKD, but nothing brings the console back. 

### How to Reproduce?

I don’t really know.

**Comment by oculos** [comment]
it was the load balancing.

**Comment by jaapspiering** [comment]
Turns out this is indeed related to running behind a reverse proxy and not telling Keycloak. 
In 26.1.5 this required me to configure both `KC_HTTP_ENABLED=true` as wel as `KC_PROXY_HEADERS=xforwarded`. The latter was missing, causing this behaviour.
