### ISSUE TITLE
Joining group for user doesn't list correct number of groups

### ISSUE THREAD

**Issue by Aravindpogu** [keycloak/keycloak#31386]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When join groups of one user, enter "one" in filter text, it will list the group name with "one",
In my environment,  filter "one"  with about 14 group records, and it only 10 records in each page by default. And then I click the next page - as below screenshots are the second/last page, it cannot go back to the previous page, the button are grey, and record number is also incorrect. 

![image](https://github.com/user-attachments/assets/dfd4775d-7db2-472e-8523-684d33de1170)

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

It should list correct pagination results on groups. Previous button should also be in "enabled" state.

### Actual behavior

Doesn't list the correct pagination results of group results. And, previous button is disabled on UI as shown in the screenshot

### How to Reproduce?

1. Create more than 10 user groups with "one" as a subtext in it.
2. Try to join a group with subtext "one" for a user
3. Go to next page on the join group popup. You will see incorrect record numbers and previous button is disabled.

### Anything else?

NA

**Comment by ssilvert** [comment]
I have reproduced this.  Thanks for reporting @Aravindpogu
