### ISSUE TITLE
[Organizations] Add a count() method to the OrganizationMembersResource

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#31388]
### Description

In some use cases, knowing the amount of users that are members of an organization without having to query them all is a desired feature. Currently, the `OrganizationMembersResource` endpoint offers no method for this, and adding one should be a simple task given that in Keycloak we already have queries in place to count all users that are members of a group.

### Motivation

Main motivation is to unlock more flexibility for users of the API to be able to get the number of org members without having to query all members.

**Comment by pdormehlerisco** [comment]
Hi Stefan,

Thanks for the update.

**Comment by heruan** [comment]
> in Keycloak we already have queries in place to count all users that are members of a group

Is there really a count method for members in a group? I can't find one, and really need it. With groups with hundreds of users I can't query for all and count manually 😓

**Comment by MiaChan1024** [comment]
> > in Keycloak we already have queries in place to count all users that are members of a group
> 
> Is there really a count method for members in a group? I can't find one, and really need it. With groups with hundreds of users I can't query for all and count manually 😓

Same confusion, cannot find one to get count number for members in a group in documentation.

**Comment by sguilhen** [comment]
IIRC we have internal methods capable of counting group members, but they aren't exposed via the admin API.
