### ISSUE TITLE
TokenVerifier failing on ClassNotFoundException since 25.0.1

### ISSUE THREAD

**Issue by augi** [keycloak/keycloak#31403]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

I'm maintainer of [this gRPC JWT Java library](https://github.com/avast/grpc-java-jwt). Since `keycloak-admin-client:25.0.1` we can see our end-to-end tests are failing: https://github.com/avast/grpc-java-jwt/pull/537

The root cause is `java.lang.ClassNotFoundException: com.fasterxml.jackson.datatype.jdk8.Jdk8Module`. Stack-trace:
```
0 = {StackTraceElement@4428} "java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)"
1 = {StackTraceElement@4429} "java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)"
2 = {StackTraceElement@4430} "java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)"
3 = {StackTraceElement@4431} "org.keycloak.jose.jws.JWSInput.<init>(JWSInput.java:57)"
4 = {StackTraceElement@4432} "org.keycloak.TokenVerifier.parse(TokenVerifier.java:405)"
5 = {StackTraceElement@4433} "org.keycloak.TokenVerifier.getHeader(TokenVerifier.java:428)"
6 = {StackTraceElement@4434} "com.avast.grpc.jwt.keycloak.server.KeycloakJwtTokenParser.createTokenVerifier(KeycloakJwtTokenParser.java:74)"
7 = {StackTraceElement@4435} "com.avast.grpc.jwt.keycloak.server.KeycloakJwtTokenParser.parseToValid(KeycloakJwtTokenParser.java:48)"
8 = {StackTraceElement@4436} "com.avast.grpc.jwt.server.JwtServerInterceptor.interceptCall(JwtServerInterceptor.java:44)"
9 = {StackTraceElement@4437} "io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)"
10 = {StackTraceElement@4438} "io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)"
11 = {StackTraceElement@4439} "io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)"
12 = {StackTraceElement@4440} "io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)"
13 = {StackTraceElement@4441} "io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)"
14 = {StackTraceElement@4442} "io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)"
15 = {StackTraceElement@4443} "io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)"
16 = {StackTraceElement@4444} "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)"
17 = {StackTraceElement@4445} "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)"
18 = {StackTraceElement@4446} "java.base/java.lang.Thread.run(Thread.java:840)"
```
After adding `'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.17.2'` dependency, it works well. So I'm curious if you are aware of this behavior.

The test is failing on [this code](https://github.com/avast/grpc-java-jwt/blob/main/keycloak/src/main/java/com/avast/grpc/jwt/keycloak/server/KeycloakJwtTokenParser.java#L74), so basically `TokenVerifier.getHeader()` method.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The usage of the `TokenVerifier` doesn't require additionally dependency to be added manually.

### Actual behavior

`java.lang.ClassNotFoundException: com.fasterxml.jackson.datatype.jdk8.Jdk8Module` exception is thrown on `TokenVerifier.getHeader()` method.

### How to Reproduce?

Check this pull request: https://github.com/avast/grpc-java-jwt/pull/537

**Comment by rmartinc** [comment]
@mposolda Take a look to this one when you have time.

The reason is that the `admin-client` is incorporating the `keycloak-core` but excluding dependencies. So the `jackson-datatype-jdk8` is not incorporated just adding the `admin-client`. But maybe the `TokenVerifier` is not something that is intended to be used by the `admin-client` (for sure it is not using it), maybe your project needs to directly depend on `keycloak-core` and not only the `admin-client`.

**Comment by augi** [comment]
Thank you! Unfortunately, the code uses also classes from `admin-client`, this is why we have this dependency there. 
I can confirm that after adding `keycloak-core` dependency, the issue is also resolved (https://github.com/avast/grpc-java-jwt/pull/543).

**Comment by mposolda** [comment]
@rmartinc @augi Thanks for figuring this. I can add that in Keycloak 26, there will be more changes in this layer and the requirement of specifically declaring `keycloak-core` as a dependency will still remain if you want to keep using `TokenVerifier` class. As `keycloak-admin-client` probably won't have any dependency at all on `keycloak-core` since Keycloak 26.
