### ISSUE TITLE
Wrong command in exposing metrics from caches section

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#31413]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

https://www.keycloak.org/server/caching 
missing = before `true` in `bin/kc.[sh|bat] start --metrics-enabled true --cache-metrics-histograms-enabled true`

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Correct command is provided

### Actual behavior

Not correct command is provided

### How to Reproduce?

see desc

**Comment by ahus1** [comment]
Hi @martin-kanis - I'm running the `kc.sh` script without the `=` on a Linx CLI and it works for me as expected: The metrics are available.

Are you adding the equal sign the matter of consistency?

**Comment by martin-kanis** [comment]
@ahus1 Hi, I got the following error:
```
Option: '--metrics-enabled true' is not expected to contain whitespace, please remove any unnecessary quoting/escaping
Possible solutions: --metrics-enabled
```
therefore, I thought it must be with `=`

**Comment by ahus1** [comment]
The following CLI command works for me without the error message: 

```
bin/kc.sh --verbose start --http-enabled true --hostname-strict false \
--db postgres \
--cache ispn \
--health-enabled true \
--features=transient-users,persistent-user-sessions \
--db-password pass --db-username keycloak \
--db-url jdbc:postgresql://localhost:5432/keycloak
```

Maybe you are passing this to a container using the CMD option? For that, you'll need to break it down to an array element on every blank if you choose the "exec" form (see https://docs.docker.com/reference/dockerfile/#cmd). 

I see that we use the equal sign across the Keycloak docs, so let's use the equal sign here as well. I'm proceeding to approve your change. Still it might not be necessary to backport it unless you want to.

**Comment by martin-kanis** [comment]
> The following CLI command works for me without the error message:
> 
> ```
> bin/kc.sh --verbose start --http-enabled true --hostname-strict false \
> --db postgres \
> --cache ispn \
> --health-enabled true \
> --features=transient-users,persistent-user-sessions \
> --db-password pass --db-username keycloak \
> --db-url jdbc:postgresql://localhost:5432/keycloak
> ```
> 
> Maybe you are passing this to a container using the CMD option? For that, you'll need to break it down to an array element on every blank if you choose the "exec" form (see https://docs.docker.com/reference/dockerfile/#cmd).
> 
> I see that we use the equal sign across the Keycloak docs, so let's use the equal sign here as well. I'm proceeding to approve your change. Still it might not be necessary to backport it unless you want to.

Yeah, it was in docker compose under `command` section. 

Thanks
