### ISSUE TITLE
call to group-by-path does not return subGroupCount

### ISSUE THREAD

**Issue by TiboGr** [keycloak/keycloak#31410]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When requesting a group by path, response should contain a "subGroupCount" property but is does not

WHEN GET /admin/realms/{realm}/group-by-path/{path}
THEN response contains subGroupCount . example ;

````
{
  "id": "e1e5dffe-9d87-4bca-a796-8f0ebf64a14c",
  "name": "everybody",
  "path": "/everybody",
  "subGroupCount": 2,
  "subGroups": [],
  "attributes": {},
  "realmRoles": [],
  "clientRoles": {}
}
````

### Version

23.0.7 reproduiced with 25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

GET /admin/realms/{realm}/group-by-path/{path}
THEN response contains subGroupCount . example ;

````
{
  "id": "e1e5dffe-9d87-4bca-a796-8f0ebf64a14c",
  "name": "everybody",
  "path": "/everybody",
  "subGroupCount": 2,
  "subGroups": [],
  "attributes": {},
  "realmRoles": [],
  "clientRoles": {}
}
````

### Actual behavior

subGroupCount is missing from response : 

````
{
  "id": "e1e5dffe-9d87-4bca-a796-8f0ebf64a14c",
  "name": "everybody",
  "path": "/everybody",
  "subGroups": [],
  "attributes": {},
  "realmRoles": [],
  "clientRoles": {}
}
````

### How to Reproduce?

Create a group with subgroups and request GET /admin/realms/{realm}/group-by-path/{path}

### Anything else?

When requesting by id or listing groups, subGroundCount is present

GET /admin/realms/{realm}/groups/{id}
GET /admin/realms/{realm}/groups

**Comment by pedroigor** [comment]
Marking as priority/normal as we don't return the count at that endpoint. We can probably use the same logic as `org.keycloak.services.resources.admin.GroupResource#getGroup` to call `GroupUtils.populateSubGroupCount(group, rep)` when returning the representation.
