### ISSUE TITLE
Package Name in Security Advisories

### ISSUE THREAD

**Issue by PiRomant** [keycloak/keycloak#31429]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

In the security recommendations, you did not specify the package name in Maven.

For this reason, vulnerability scanners cannot report the presence of a vulnerable version of Keycloak. Please specify the exact package name from Maven in the line with the field Ecosystem - Maven.

### Regression

- [ ] The issue is a regression

### Expected behavior

Specify the exact package name from Maven in the line with the field Ecosystem - Maven.

### Actual behavior

https://github.com/keycloak/keycloak/security/advisories/GHSA-69fp-7c8p-crjr There is no `org.keycloak.protocol` in maven https://mvnrepository.com/search?q=org.keycloak.protocol
https://github.com/keycloak/keycloak/security/advisories/GHSA-72vp-xfrc-42xm There is no `org.keycloak.protocol.oidc`  in maven https://mvnrepository.com/search?q=+org.keycloak.protocol.oidc

### Anything else?

https://docs.github.com/en/enterprise-cloud@latest/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/best-practices-for-writing-repository-security-advisories#package-name

**Comment by abstractj** [comment]
Should be fixed now, please reopen if not fixed on your end.
