### ISSUE TITLE
Unable to connect to external infinspan from keycloak 

### ISSUE THREAD

**Issue by nit211** [keycloak/keycloak#31423]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

I am trying to connect keycloak with external infinispan. When I run Infinspan I am able to start the server and able to connect to console. The cache required by Keycloak are also created. But when I am starting keycloak I am getting error **"SecurityException: ISPN000287: Unauthorized access: subject 'null' lacks 'LIFECYCLE' permission"

In Security under authorization I have specified the required subject and role but still getting the error.

**Keyclaok version: 25.0.1
Infinispan version: 15.0.1**

Attached are the cache-ispn.xml file which is passed as a config-file to Keycloak
And For Infinspan I am using infinispan-xsite.xml

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Null subject should not be passed as the user is admin

### Actual behavior

Subject passed is null and so this user does not has permission for LIFECYCLE

### How to Reproduce?

Start Infinspan using the command : bin\server.bat -c infinispan-xsite.xml

Start Keyclaok using command: bin\kc.bat start --https-certificate-file=C://Users//Nitiin-O//keycloak.crt --https-certificate-key-file=C://Users//Nitiin-O//keycloak.key --hostname=myapp.com --optimized --cache-config-file=cache-ispn.xml --verbose

### Anything else?

[cache-ispn.zip](https://github.com/user-attachments/files/16303177/cache-ispn.zip)

**Comment by martin-kanis** [comment]
@ahus1 Can cross-dc team check this one please?

**Comment by ahus1** [comment]
@nit211 - can you please check if the modifications to the `cache-ispn.xml` are necessary, as the latest version Keycloak allows you to set a remote Infinispan on the CLI, and also allows you to disable TLS if you choose to not use it: https://www.keycloak.org/server/all-config

Please let me know if the issue persists. 

![image](https://github.com/user-attachments/assets/461e862f-0a51-4f9c-bb95-e0b97a2511ba)
