### ISSUE TITLE
Add Events for Organization Creation and Member Assignment

### ISSUE THREAD

**Issue by Degoya-Studio** [keycloak/keycloak#31421]
### Description

It would be nice to be able to listen for organization related events in a custom spi interface.

### Discussion

#30180

### Motivation

This feature will allow me to call my internal API in order to create that organization in a database and assign users to them

**Comment by Degoya-Studio** [comment]
related to #30180

**Comment by pedroigor** [comment]
@Degoya-Studio It makes a lot of sense to provide such events:

* Create/Update/Delete Organization
* Join/Leave Organization
   * It should also contain the onboarding method when joining an org (e.g.: invitation, admin, broker)

Can you elaborate more on the use case and what you mean by "create that organization in the database and assign users to them"?

**Comment by Degoya-Studio** [comment]
@pedroigor sure. Let's say my users are personnel at medical practices. Each practice should have an Organization in KeyCloak in order for its staff to log in. Internally, that practice has other related Tables inside of my API such as patient, examinations and so on. So my goal is to create and link the initial practice via KeyCloak Organization creation. Invited user will also then be  assigned to the practice in my internal API, in order for them to access the patient information, examination and so on.
