### ISSUE TITLE
Package Name in Security Advisories

### ISSUE THREAD

**Issue by PiRomant** [keycloak/keycloak#31424]
### Description

In the security advisories, you do not specify the package name in Maven.
Ex: 
https://github.com/keycloak/keycloak/security/advisories/GHSA-69fp-7c8p-crjr There is no `org.keycloak.protocol` in maven https://mvnrepository.com/search?q=org.keycloak.protocol
https://github.com/keycloak/keycloak/security/advisories/GHSA-72vp-xfrc-42xm There is no `org.keycloak.protocol.oidc`  in maven https://mvnrepository.com/search?q=+org.keycloak.protocol.oidc

For this reason, vulnerability scanners cannot report the presence of a vulnerable version of Keycloak. Please specify the exact package name from Maven in the line with the field Ecosystem - Maven.

https://docs.github.com/en/enterprise-cloud@latest/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/best-practices-for-writing-repository-security-advisories#package-name

**Comment by jonkoops** [comment]
This is not a task, but a bug report, please use the appropriate form to report issues.
