### ISSUE TITLE
Support for authenticating and issuing tokens in the context of a organization

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#31438]
### Description

When authenticating using organizations, clients and users might want to obtain a token containing only the metadata for a specific target organization.

In the case of clients, they can choose the organization they want to have access on behalf of an user by leveraging the `organization` scope parameter so that they can either ask for access to all organizations that user is a member of or only a subset of the organizations.

In case of users, when a client does not provide the organization it wants to access on behalf of the user, the user should be able to select which organization they want to access by choosing it during the authentication flow.

As a result, the organization feature will provide a mechanism for both clients and users to authenticate in the context of a specific organization(s) and provide the core functionality to build more capabilities in the future around how the authentication flow should be configured and how tokens should be issued.

### Motivation

Make it possible for clients and users to authenticate in the context of an organization.

**Comment by stianst** [comment]
As an example we could have two client scopes; orgs and org, where the org is a dynamic/parameterized scope.

If an application requests `scope=orgs` the token will contain `orgs: [a, b, c]`. However, if the application wants a single org in the token it can use `scope=org:a` in which case the token will only be issued if the user belongs to `org=a`. 

It should also be possible to ask the user to select the org, say application asks for `scope=org` without a specific value. If the user belongs to a single org, that's fine we'll just return that org, but if the user belongs to multiple orgs the user is prompted to select which org to use for the specific authentication request.

**Comment by pedroigor** [comment]
@stianst Do you agree with the following requirements?

* Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for all organizations the user is a member of. This is what we support today.
* Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for a set of one or more organizations the user is a member of.
* Clients can switch contexts and ask users to re-authenticate and obtain tokens for organizations other than those previously granted
*  Users can select the organization they want to access when authenticating. When a member of a single organization, they always authenticate in the context of that organization.
* Users can grant clients consent to access their data at the organizations they are members.

**Comment by stianst** [comment]
> @stianst Do you agree with the following requirements?
> 
> * Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for all organizations the user is a member of. This is what we support today.

So, that means `scope=organization` returns all organizations user is associated with?

> * Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for a set of one or more organizations the user is a member of.

Not quite sure I'm following. Do you mean client can specify one or more orgs to include? How would they send a list in the scope param? Is the return a subset of the requests orgs, or does the user have to be associated with all requested orgs?

> * Clients can switch contexts and ask users to re-authenticate and obtain tokens for organizations other than those previously granted
> * Users can select the organization they want to access when authenticating. When a member of a single organization, they always authenticate in the context of that organization.

How would that work if you have `scope=organization` or `scope=organization:foobar`? When would the user be asked to select the org?

> * Users can grant clients consent to access their data at the organizations they are members.

Not sure I'm following

**Comment by pedroigor** [comment]
> > @stianst Do you agree with the following requirements?
> > 
> > * Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for all organizations the user is a member of. This is what we support today.
> 
> So, that means `scope=organization` returns all organizations user is associated with?

Yes, this is what we have today.

> 
> > * Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for a set of one or more organizations the user is a member of.
> 
> Not quite sure I'm following. Do you mean client can specify one or more orgs to include? How would they send a list in the scope param? Is the return a subset of the requests orgs, or does the user have to be associated with all requested orgs?

Yes, they will send `scope=organization:foo organization:bar`. As you know, the scope parameter is a list of space-delimited, case-sensitive strings. One thing I'm not 100% sure yet though is if we can rely or not on the dynamic scope feature because it is a tech-preview feature.

From the AS perspective, requesting the scope should fail if the scope is unknown, invalid, or malformed. However, I would say that requesting a scope that maps to an organization the user is a member should just be ignored because the scope is valid. As long as we return the scopes actually granted in the access token response, it should be fine.

> 
> > * Clients can switch contexts and ask users to re-authenticate and obtain tokens for organizations other than those previously granted
> > * Users can select the organization they want to access when authenticating. When a member of a single organization, they always authenticate in the context of that organization.
> 
> How would that work if you have `scope=organization` or `scope=organization:foobar`? When would the user be asked to select the org?

They will be asked when users are members of multiple organizations, as a general rule. But if the client requests a scope that maps to only one of the organizations, there is no need to select one. 

> 
> > * Users can grant clients consent to access their data at the organizations they are members.
> 
> Not sure I'm following

You might want to force users to grant consent to the client to act on their behalf when accessing protected resources in the context of an organization. This is basically about enabling consent when using the `organization` scope.

**Comment by stianst** [comment]
> > > @stianst Do you agree with the following requirements?
> > > 
> > > * Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for all organizations the user is a member of. This is what we support today.
> > 
> > 
> > So, that means `scope=organization` returns all organizations user is associated with?
> 
> Yes, this is what we have today.
> 
> > > * Clients can leverage the `organization` scope parameter to authenticate and obtain tokens for a set of one or more organizations the user is a member of.
> > 
> > 
> > Not quite sure I'm following. Do you mean client can specify one or more orgs to include? How would they send a list in the scope param? Is the return a subset of the requests orgs, or does the user have to be associated with all requested orgs?
> 
> Yes, they will send `scope=organization:foo organization:bar`. As you know, the scope parameter is a list of space-delimited, case-sensitive strings. One thing I'm not 100% sure yet though is if we can rely or not on the dynamic scope feature because it is a tech-preview feature.

From memory (and this is a long time ago) the dynamic scopes is experimental because it's not fully implemented; we had some ideas on how we would handle the values, and what protocol mappers would do, but doesn't exist, and there's no way to do something like asking a user to select the value to use. I think also there's some lacks in the persisted consents not understanding them.

> 
> From the AS perspective, requesting the scope should fail if the scope is unknown, invalid, or malformed. However, I would say that requesting a scope that maps to an organization the user is a member should just be ignored because the scope is valid. As long as we return the scopes actually granted in the access token response, it should be fine.
> 
> > > * Clients can switch contexts and ask users to re-authenticate and obtain tokens for organizations other than those previously granted
> > > * Users can select the organization they want to access when authenticating. When a member of a single organization, they always authenticate in the context of that organization.
> > 
> > 
> > How would that work if you have `scope=organization` or `scope=organization:foobar`? When would the user be asked to select the org?
> 
> They will be asked when users are members of multiple organizations, as a general rule. But if the client requests a scope that maps to only one of the organizations, there is no need to select one.

Okay, so `scope=organization` returns a single org, but we can use parameterized values to get a specific org. How would I then get all orgs?

> 
> > > * Users can grant clients consent to access their data at the organizations they are members.
> > 
> > 
> > Not sure I'm following
> 
> You might want to force users to grant consent to the client to act on their behalf when accessing protected resources in the context of an organization. This is basically about enabling consent when using the `organization` scope.

**Comment by pedroigor** [comment]
> From memory (and this is a long time ago) the dynamic scopes is experimental because it's not fully implemented; we had some ideas on how we would handle the values, and what protocol mappers would do, but doesn't exist, and there's no way to do something like asking a user to select the value to use. I think also there's some lacks in the persisted consents not understanding them.

@stianst I see. As we discussed, I'll check how the feature is working today and see how we can leverage it in the context of organizations.

> 
> Okay, so `scope=organization` returns a single org, but we can use parameterized values to get a specific org. How would I then get all orgs?

As we are adding support for multiple organizations, asking for `scope=organization` will map to all organizations the user is a member.

But now I'm not sure how the scope will look like when a client wants only the organization the user is a *managed* member. In this case it will always resolve to a single one. Therefore, `scope=organization` sounds a bit confusing to return all the orgs, as I was thinking.

Perhaps we can have:

* `scope=organization`, authenticate in the scope of the organization the user is a managed member. Tokens will have claims only for a single organization.
* `scope=organizations`, authenticate in the scope of any organization the user is a member. Tokens will have claims for whatever organization the user is a member. Perhaps this scope will also change the login flow to allow the user to select the organization he wants to authenticate?
* `scope=organization:foo`, authenticate in the scope of a specific organization. Tokens will have claims only for a single organization.

Wdyt?

**Comment by stianst** [comment]
I propose something like:

Add a config options what to do when there are multiple orgs? Options would be:
- return the managed org
- prompt user (this provides a form where the user selects which org to continue with)

When using the scope the app sends:

* scope=organization
** returns a single organization
** if user is associated with multiple organizations the user is prompted to select which to use

* scope=organization:*
** returns all organizations

* scope=organization:foobar
** returns foobar org if user is a member, or no org if not

**Comment by pedroigor** [comment]
@stianst Do we want a value to return only to the organization the user is a managed member? Something like `organization:parent` ?

**Comment by Tungsten78** [comment]
@pedroigor, @stianst -  I'm wondering if there was a technical reason the org selection needed to occur before the user authenticates.

Looking at the [authenticator](https://github.com/keycloak/keycloak/blob/d96e01abf829da40b11859a1c91622ba209e44c5/services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java#L300), the linked IDP redirect may terminate the flow (#10250)?

Our concern is that the order poses a privacy concern (#41736) where organization membership could be easily introspected having only an email address.   In our line of business, this translates to customers being able to snoop on competitors.

Looking for ideas on how to resolve this concern
- leverage Post Broker Login flow to address flow truncation -> maybe the same authenticator could be called back?
- For credential login, hook the same authenticator post form login to prompt org selection?
* apologies if these are non-sensical - just recently started getting involved with keycloak.
