### ISSUE TITLE
CWE-327 Use of a Broken or Risky Cryptographic Algorithm

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31437]
### Description

Hi,

SAST scan of keycloak 25.0.1 in Gitlab CI/CD is reporting following high severity vulnerabilities coming in io.quarkus, org.freedesktop, org.jgroups packages.

![image](https://github.com/user-attachments/assets/9bf1a247-7687-462d-934a-5a4236c5d511)
![image](https://github.com/user-attachments/assets/422ad888-6b35-46ef-a8a3-13c71f08ca75)
![image](https://github.com/user-attachments/assets/11845d69-99a8-43d4-a939-fe5f580fc551)
![image](https://github.com/user-attachments/assets/ccf48103-cc56-4786-83c1-5819e11c6275)
![image](https://github.com/user-attachments/assets/cd418845-b62f-458c-a3ea-5c4b723bfbac)
![image](https://github.com/user-attachments/assets/575fc2ac-e7b4-445f-a6e7-55fdb9f8c3f9)
![image](https://github.com/user-attachments/assets/65e20825-6af1-44fd-b9f5-17bb23aaf965)
![image](https://github.com/user-attachments/assets/c0ef64cb-9577-4c88-a6e4-62916052806a)

[CWE-327](https://cwe.mitre.org/data/definitions/327)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
