### ISSUE TITLE
CWE-255 Credentials Management Errors org.jgroups.protocols.JDBC_PING.main()

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31435]
### Description

Hi,

SAST scan of keycloak 25.0.1 in Gitlab CI/CD is reporting following vulnerability coming with org.jgroups.protocols.JDBC_PING.main()

![image](https://github.com/user-attachments/assets/177d7c79-259e-4681-81a6-04534ba41c1e)

![image](https://github.com/user-attachments/assets/efab528e-a1d8-4db5-a1bd-9d84381397be)

[CWE-255](https://cwe.mitre.org/data/definitions/255)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
