### ISSUE TITLE
Users cannot access customized realms even with realm management roles.

### ISSUE THREAD

**Issue by Krishna-PriyaV** [keycloak/keycloak#31440]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

If a user trying to access a customized realm in keycloak and they cannot access the realm, getting the following error pages:

![image](https://github.com/user-attachments/assets/fa7c427c-f931-46f5-8c6f-e6dd2c563efa)

![image](https://github.com/user-attachments/assets/b884de86-ba3b-4f70-b98d-1b75451c4e57)

### Version

23.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

User can access the customized realms.

### Actual behavior

User getting error page while trying to access the customized realms

### How to Reproduce?

Please add below roles to a user and try to login with url  keycloakurl/admin/{realm name}/console
view-clients
view-users
view-events
view-realm
query-clients
query-realms
manage-users
manage-authorization

### Anything else?

This worked into a custom realm for a user with the same roles mentioned above.

**Comment by sguilhen** [comment]
I can't reproduce this on Keycloak 25 - created a realm test, added a user, assigned the roles as described in the `Steps to Reproduce` section. Then I opened the console at KEYCLOAK_URL/admin/test/console, logged with the user just fine, I am able to manage many aspects of the test realm with this user.
