### ISSUE TITLE
Make IdP list reusable across login theme pages

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#31447]
### Description

Make the identity provider list reusable across mutliple login pages and avoid redundant html fragments.

This could be achieved by using a (parameterized?) freemarker macro for the IdP provider list in a file like `login-idp-list.ftl`.

### Motivation

Currently the IdP list is rendered within dedicated pages, e.g. `src/main/resources/theme/base/login/login.ftl` and `login-username.ftl`  and is repeated several times.

In Keycloak customizations some users want just to show the IdP Providers list for login. This is currently difficult to achive. A dedicated `login-idp-list.ftl` macro would make this a bit easier.

### Details

With this change we should also move the IdP list rendering from a `<footer>` element in a `<div>`.
Currently identityProviders are linked like this:
```html
      <footer class="pf-v5-c-login__main-footer">
        <#nested "socialProviders">
      </footer>
```

The `<footer>` element should rather be used for actual footer components, see: https://github.com/keycloak/keycloak/pull/31391

_No response_

**Comment by edewit** [comment]
closing as this is now done:
https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/keycloak.v2/login/login.ftl#L44-L48
