### ISSUE TITLE
Show account page before login

### ISSUE THREAD

**Issue by ehsanr1366** [keycloak/keycloak#31469]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

I intend to describe the bug very briefly and precisely. I am using version 25.0.2. When I try to access the account page, the account page, including menus and header, is displayed for a few moments and then the login page is shown.

This is not very pleasant! Thank you.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Well, it's natural that the login page should be shown to the user immediately and quickly.

### Actual behavior

The point is that the account page is shown first, then it checks whether the user is logged in or not. After realizing that no one is logged in, the user is redirected to the login page.

### How to Reproduce?

You can easily reproduce the bug. Just try to access the account page. That's it.

**Comment by ehsanr1366** [comment]
Thank you for your response. I also observed the issue I reported on version 25.0.2, which is currently the latest version.

**Comment by agagancarczyk** [comment]
Thanks @ehsanr1366 for reporting this issue. I can reproduce it also in `main`.

**Comment by edewit** [comment]
The way it works is that on the first fetch it notices that the user is not logged IMO there isn't a way to find out before that the user isn't logged in. So no data is shown, but we can't get rid of having this initial render

**Comment by jonkoops** [comment]
We should really be implementing a mechanism in the theme bootstrapping to ensure we know if the user has a session, but this would require some more extensive refactoring.

**Comment by edewit** [comment]
we allowed to be not logged in for the account console before, can't we "just" make it so that that is no longer allowed? I don't know exactly how to accomplish that but maybe something like:

```java
if (auth == null)
   throw new ForbiddenException("Bearer")
```
but that doesn't redirect to the login page though

**Comment by mahdisn76** [comment]
I also have this problem and caused lots of problems for me and my customers.

**Comment by edewit** [comment]
@mahdisn76 lots of problems? I mean it's not nice, but it's not a big issue, right?

**Comment by mahdisn76** [comment]
> @mahdisn76 lots of problems? I mean it's not nice, but it's not a big issue, right?

Yeah! Since the account page shown before the login page, the user feels insecure and think it as a security bug.

**Comment by msmosavar** [comment]
Same problem... Any updates?

**Comment by ehsanr1366** [comment]
Please confirm if this issue has entered the development process or not. My next question is whether it will be fixed in the next release or not? If not, could you at least provide a reasonable timeline? Thank you.

**Comment by jonkoops** [comment]
If the issue has not been assigned it is currently not being worked on. The team is currently busy with other important tasks and does not have time to work on it immediately, nor can we provide a timeline on when this will be resolved. The quickest way to get this fixed is to provide a PR to resolve the issue, of which we can prioritize the review.

If you want to increase the priority of the issue please leave a :+1: on the issue description, we use that to [prioritize our backlog](https://github.com/keycloak/keycloak/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thomasdarimont** [comment]
I just gave it a spin and the following patch works for me:
```
Index: services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java b/services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java
--- a/services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java	(revision abb521bedc3ce01d1dc12be2d772383d7a660ffc)
+++ b/services/src/main/java/org/keycloak/services/resources/AbstractSecuredLocalService.java	(date 1725496962938)
@@ -161,7 +161,7 @@
         return oauth.redirect(session.getContext().getUri(), accountUri.toString());
     }
 
-    static class OAuthRedirect extends AbstractOAuthClient {
+    public static class OAuthRedirect extends AbstractOAuthClient {
 
         /**
          * closes client
Index: services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java b/services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java
--- a/services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java	(revision abb521bedc3ce01d1dc12be2d772383d7a660ffc)
+++ b/services/src/main/java/org/keycloak/services/resources/account/AccountConsole.java	(date 1725497358878)
@@ -3,8 +3,9 @@
 import jakarta.ws.rs.GET;
 import jakarta.ws.rs.Path;
 import jakarta.ws.rs.core.Response;
-import jakarta.ws.rs.core.UriInfo;
+import jakarta.ws.rs.core.UriBuilder;
 import org.jboss.resteasy.reactive.NoCache;
+import org.keycloak.OAuth2Constants;
 import org.keycloak.authentication.requiredactions.DeleteAccount;
 import org.keycloak.common.Profile;
 import org.keycloak.common.Version;
@@ -17,12 +18,14 @@
 import org.keycloak.models.RequiredActionProviderModel;
 import org.keycloak.models.RoleModel;
 import org.keycloak.models.UserModel;
+import org.keycloak.protocol.oidc.OIDCLoginProtocolService;
 import org.keycloak.protocol.oidc.utils.RedirectUtils;
 import org.keycloak.services.Urls;
 import org.keycloak.services.managers.AppAuthManager;
 import org.keycloak.services.managers.Auth;
 import org.keycloak.services.managers.AuthenticationManager;
 import org.keycloak.services.resource.AccountResourceProvider;
+import org.keycloak.services.resources.AbstractSecuredLocalService;
 import org.keycloak.services.resources.RealmsResource;
 import org.keycloak.services.util.ResolveRelative;
 import org.keycloak.services.util.ViteManifest;
@@ -92,10 +95,31 @@
     public void close() {
     }
 
+    protected Response login() {
+        AbstractSecuredLocalService.OAuthRedirect oauth = new AbstractSecuredLocalService.OAuthRedirect();
+
+        String authUrl = OIDCLoginProtocolService.authUrl(session.getContext().getUri()).build(realm.getName()).toString();
+        oauth.setAuthUrl(authUrl);
+        oauth.setClientId(client.getClientId());
+        oauth.setSecure(realm.getSslRequired().isRequired(session.getContext().getConnection()));
+
+        UriBuilder uriBuilder = UriBuilder.fromUri(Urls.realmIssuer(session.getContext().getUri().getBaseUri(), realm.getName())).path("account");
+
+        URI accountUri = uriBuilder.build(realm.getName());
+
+        oauth.setStateCookiePath(accountUri.getRawPath());
+        return oauth.redirect(session.getContext().getUri(), accountUri.toString());
+    }
+
     @GET
     @NoCache
     @Path("{any:.*}")
     public Response getMainPage() throws IOException, FreeMarkerException {
+
+        if (auth == null) {
+            return login();
+        }
+
         final var serverUriInfo = session.getContext().getUri(UrlType.FRONTEND);
         final var serverBaseUri = serverUriInfo.getBaseUri();
         // Strip any trailing slashes from the URL.

```

**Comment by thomasdarimont** [comment]
I think we could do the same for the admin-console.

**Comment by jonkoops** [comment]
> I think we could do the same for the admin-console.

That sounds good to me, there is no reason to visit the Admin Console without being signed in. Thanks for the PR!

**Comment by thomasdarimont** [comment]
I think we need to create a separate ticket for the admin-console because it is a bit more work.
Reason: the account-console is served from the realm path (/realms/$realm/account) and hence we can use the existing
cookies (KEYCLOAK_IDENTITY) which are served from /realms/$realm.

However, the admin-console is served from /admin/master/console/ and this request does not have access to the cookies from /realms/$realm.

**Comment by jonkoops** [comment]
Sure, we can handle that separately, can you log an issue @thomasdarimont?

**Comment by edewit** [comment]
@thomasdarimont I think it already works for admin, no?

**Comment by ehsanr1366** [comment]
I hope this message finds you well. I wanted to follow up regarding this issue, as it has been two weeks since the last update. Could you please let us know when we might expect a resolution, and if it will be included in the next release?

Thank you for your attention to this matter!

**Comment by vramik** [comment]
To backport https://github.com/keycloak/keycloak/issues/28328 to 26.0 it's needed backport of this one.
