### ISSUE TITLE
Duplicate Key "validatingX509CertsHelp" in admin-ui messages

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#31466]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The file `theme/keycloak.v2/admin/messages/messages_en.properties` contains the key `validatingX509CertsHelp` twice (line 3218 and 820). 

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Message key `validatingX509CertsHelp` should be defined only once.

### Actual behavior

Message key is defined twice. 

### How to Reproduce?

Looking at the file. This error was reported by Weblate when it checked the syntax of the file. 

cc: @jonkoops 

### Anything else?

This was introduced in PR #31193 when fixing #31146

I assume the new text should be kept. I'm not sure if the old text is used in another place - it seems it never is. 

cc: @agagancarczyk

**Comment by agagancarczyk** [comment]
Right @ahus1 - thanks for reporting this. I can rename the help text I added previously.

**Comment by ahus1** [comment]
> I can rename the help text I added previously.

As I wrote above, it seems the old text is never used (maybe it was forgotten to be added to the frontend). So your text might be the right one.

**Comment by agagancarczyk** [comment]
> > I can rename the help text I added previously.
> 
> As I wrote above, it seems the old text is never used (maybe it was forgotten to be added to the frontend). So your text might be the right one, and it would be about removing the old one.

No problem, I'll check the situation. My text is from our docs so it's the right one. If that's the case I'll just remove the unused one.
