### ISSUE TITLE
Docs: server_admin/topics/realms/keys.adoc

### ISSUE THREAD

**Issue by johanloke** [keycloak/keycloak#31474]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

File: server_admin/topics/realms/keys.adoc

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Under the compromised key section
https://www.keycloak.org/docs/25.0.2/server_admin/#compromised-keys

The following instruction is not valid. I am unable to find the revocation section as in the older version

5. Click the Advanced tab.
6. Click Set to now in the Revocation section.
7. Click Push.

Revocation section is totally missing

### Actual behavior

I am not sure where this section went to

### How to Reproduce?

Just click the url and boot up a 25.0.2 version via docker run

**Comment by mposolda** [comment]
@keycloak/ui I can confirm that "Revocation" section is not available in the admin console. I can see there is still admin REST endpoint available (Corresponding Java method is `ClientResource.pushRevocation()` ). Was the "revocation" section removed from admin console on purpose or by accident?

If on purpose (which is probably fine as this part is specific to Keycloak/Elytron OIDC adapters), we can probably just update the documentation and remove that corresponding section.

**Comment by edewit** [comment]
it was on purpose as stated in this issue https://github.com/keycloak/keycloak/issues/17734
