### ISSUE TITLE
Group roles - Assign role not showing in JWT

### ISSUE THREAD

**Issue by BrunoPapa** [keycloak/keycloak#31479]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

Hi guys, sorry for using this space to create a new discussion, but I couldn't find an answer elsewhere.

In the admin console, we can assign a realm role to a group and associate a user with the group. OK, that's all well and good, but if I create a token for the user (I used a grant_type password and got a token in the admin console), the realm roles won't be displayed in the token. I've searched several sites and haven't found a method for displaying the realm roles associated with a group in the token.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

- Create a user
- Create a group
- Create a realm role

- Assign a realm role to group
- Assign a group to user

- Create a token using a grant_type password or login in admin console using a user and get a token.
- Showing realm role assiged to group in JWT

### Actual behavior

- Not showed realm role in JWT

### How to Reproduce?

- Create a user
- Create a group
- Create a realm role

- Assign a realm role to group
- Assign a group to user

**Comment by BrunoPapa** [comment]
Hi @graziang thanks for your response, but i not want assing a role for client or user, i want assig realm roles for group. In group i assigned some roles and not showing in the token.

**Comment by graziang** [comment]
Hi @BrunoPapa you don't assign the role to the client, you limit the permissions of each individual access token instead of giving the client access to all the users permissions. More details here: https://www.keycloak.org/docs/25.0.2/server_admin/#_role_scope_mappings

**Comment by rmartinc** [comment]
@BrunoPapa As @graziang commented, the roles in the token are the intersection between the user roles and the roles allowed by the client scope. So you can add the roles to the client scope or you can set the client as `Full scope allowed`. Closing the issue.
