### ISSUE TITLE
dynamic MultiValuedListComponent default value not stringified

### ISSUE THREAD

**Issue by simse07** [keycloak/keycloak#31480]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If you define a default value for a provider configuration property of type `MULTIVALUED_LIST_TYPE`, the default value is not stringified in the frontend `MultiValuedListComponent`, when used for an identity provider.

### Version

24.05

### Regression

- [ ] The issue is a regression

### Expected behavior

Default value should be stringified, when property is defined for MultiValuedListComponent

### Actual behavior

Default value should be stringified, when property is defined for MultiValuedListComponent

### How to Reproduce?

Create a identity provider with its own configuration properties:
```java
ProviderConfigurationBuilder
            .create()
            .property()
            .name("custom multi select list")
            .type(ProviderConfigProperty.MULTIVALUED_LIST_TYPE)
            .options("item1", "item2", "item3")
            .defaultValue("item1")
            .add()
            .build();
```
Try to create a new instance of the IDP in the admin console. Default value is selected, but on save, the server will complain, because an array `["item1"]` is send, instead of the stringified version `"item1"`.

### Anything else?

Root cause is located in https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/components/dynamic/MultivaluedListComponent.tsx#L45

There is no check for `stringify`, so a possible solution could look like 
```ts
        defaultValue={
          defaultValue
            ? stringify
              ? toStringValue([defaultValue])
              : [defaultValue]
            : stringify
              ? ""
              : []
        }
```

**Comment by edewit** [comment]
stringify will take all the values and concatenate them into a string like: `item1##item2`. So your problem is not solved by calling stringify

**Comment by simse07** [comment]
@edewit I don't understand. My issue is that the default value is not stringified. The rest works fine.

**Comment by edewit** [comment]
@simse07 that can't be the case, because stringify does what I described. Why don't you tell me what the problem is, then I can see how to fix it

**Comment by simse07** [comment]
I implemented an identity provider for BundID, where you can select multiple authentication methods.
```kotlin
fun ProviderConfigurationBuilder.authnMethods(): ProviderConfigurationBuilder = this.property()
    .name(BundIdSamlIdentityProviderConfig.AUTHN_METHODS)
    .label(BundIdSamlIdentityProviderConfig.AUTHN_METHODS_LABEL)
    .helpText(BundIdSamlIdentityProviderConfig.AUTHN_METHODS_HELP)
    .type(ProviderConfigProperty.MULTIVALUED_LIST_TYPE)
    .options(AuthnMethods.entries.map { it.name })
    .defaultValue(AuthnMethods.USERNAME)
    .add()
```

In the admin ui, I used the same code from [DetailSettings](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx). 
1. fetch the provider infos https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx#L262
2. add the DynamicComponent https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/identity-providers/add/DetailSettings.tsx#L448

Now, the first issue is that the default value is not displayed:
<img width="1037" alt="create-idp-no-authentication-methods-default-value" src="https://github.com/user-attachments/assets/07aa57eb-4b53-40b9-9e5c-554749aadcd9">

When I want to create the idp, an error is thrown, because the configuration for authentication methods is an array:
<img width="874" alt="create-idp-failure" src="https://github.com/user-attachments/assets/d33259c6-8a39-4a7d-92a8-cbc9c564e82d">
This also applies to other config properties of type `MULTIVALUED_LIST_TYPE`, which do not have a default value. There an empty array is transmitted. The config of an idp is of type `Map<String, String>` which is not compatible.

With my propsed fix, the default value is displayed and send as string for empty and non empty values:
<img width="874" alt="create-idp-success" src="https://github.com/user-attachments/assets/78e055c9-6d7c-48f0-acd5-c6d0bf04b4ea">

**Comment by edewit** [comment]
ahh okay, thanks now I get it.... I've created a PR that will fix it, not the same way you suggest, but the effect is the same
