### ISSUE TITLE
Use single client to implement entire OID4VCI process

### ISSUE THREAD

**Issue by francis-pouatcha** [keycloak/keycloak#31496]
### Description

Task is to address the following conversation. With respect with ticket comment: https://github.com/keycloak/keycloak/pull/30692#discussion_r1686012154

> Could you confirm the following?
> 
> A client (1) that sends a token request and receives an access token is the one whose protocol is oidc.

Yes. To obtain a token, i need an oidc client. Or do you think i can use an oid4vci client to obtain a token?

> A client (2) that sends a credential request and receives a VC is the one whose protocol is oid4vci.

Yes. Unless we have a way of issuing a token with an oidc client.

> Both shold be the same, but Keycloak does not do that ( azp in an access token shows the client (1) while a sender of Key binding proof is the client (2)).

This is why i did not check the azp here and left it commented. We need a concept.

> To get around it, the client (1)'s access token includes audiences that includes the client (2), and the method check it.

Ok. I will try this. As client access token can have many audiences. Thank you.

> If those above are right, IMO, it might be preferable to require only one client for OID4VCI.
> 
> For example, [POTENTIAL Interop Event / Track 2 / Full Profile](https://www.authlete.com/developers/oid4vci/#45-potential-interop-event--track-2--full-profile) requires DPoP Proof JWT on Token Endpiont and Credential Endpoint, which means that a sender of a token request should be the sender of a credential request. I am afraid that the current Keycloak's treatment of clients for OID4VCI does not realize such the use-case.

Correct. I will try the approach with many audiences.

> 
> Also, for tracking of VC issuance for audit, it might be preferable that one client go through all phases from getting a credential offer, an access token, and a VC.

Yes.

I will create a separate ticket to implement this.

**Comment by hugoib** [comment]
This ticket:

https://github.com/keycloak/keycloak/issues/32961

Will solve this one. Please close this ticket. @mposolda

**Comment by tnorimat** [comment]
@hugoib I closed the issue on behalf of @mposolda .
