### ISSUE TITLE
Review use of credentialType and scope in the implementation of OID4VCI

### ISSUE THREAD

**Issue by francis-pouatcha** [keycloak/keycloak#31497]
### Description

With respect to review comment: https://github.com/keycloak/keycloak/pull/30692#discussion_r1686033782

**Comment by hugoib** [comment]
According to today's discussion:

https://cloud-native.slack.com/archives/C05KR0TL4P8/p1726656673124189

We will focus on using scope and removing the usage of credentialType.

**Comment by hugoib** [comment]
This ticket:

https://github.com/keycloak/keycloak/issues/32961

Will solve this one. Please close this ticket. @mposolda

**Comment by tnorimat** [comment]
@hugoib I closed the issue on behalf of @mposolda .
