### ISSUE TITLE
Add a deprecation warning when old `KEYCLOAK_ADMIN`, `KEYCLOAK_ADMIN_PASSWORD` env vars are used

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#31491]
### Description

There should be a warning emitted in the log.

This is a follow-up from #30658, and related to #31229.

**Comment by shawkins** [comment]
This will wait until after #31478 is committed.

**Comment by vmuzikar** [comment]
@shawkins I'd suggest doing it separately, IMHO this is not really relevant to that PR.
