### ISSUE TITLE
Misleading docs and functionality around cache-ispn.xml

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#31492]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The [docs](https://www.keycloak.org/server/caching) state: 

> Keycloak provides a cache configuration file with sensible defaults located at conf/cache-ispn.xml.

This could lead to the assumption that if this file is changed, the settings will come into effect (at least when `cache` is set to `ispn`). 

It also states:

>  You are free to change the number of owners accordingly to better fit into your availability requirements. To change the number of owners, open conf/cache-ispn.xml and change the value for owners=<value> for the distributed caches to your desired value.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

When changing the file, those changes should come into effect once I edit the file (at least that's what the docs seem to tell me, and this is what I would assume when I see the file in the conf folder). 

### Actual behavior

The changes wouldn't come into effect unless I add the CLI parameter `--cache-config-file=cache-ispn.xml` as otherwise the file would be taken from the classpath which includes the shipped defaults.

### How to Reproduce?

This happend to me when I tried to enable the metrics in KC24 which need editing the `cache-ispn.xml`. A similar configuration mishap would happen if I change the number of cache entries. 

### Anything else?

While some of this could be fixed by the docs for KC24/KC25 where we don't want to change the functionality, keeping a file in the conf folder which contains the defaults but isn't used is part of the problem. 

Another idea: It might also be good in KC24/25 to print the file path where the ISPN file has been picked up from: 

https://github.com/keycloak/keycloak/blob/d2ae27a1e2ff0cf153f56e89c2dd3979eb6e7704/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/KeycloakRecorder.java#L143

This might have been discussed in the past, so I'm eager to hear the cloud native team's ideas around that.

**Comment by mabartos** [comment]
@vmuzikar It should go out from triage, right?

**Comment by pruivo** [comment]
Hope I'm not stepping in anybody toes :)
