### ISSUE TITLE
[UX Design] Show user's organization info in the Account UI

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#31509]
### Use cases
If I were a user, I'd like to check the organization info in my account console.

### Output
Design prototype

### Related issue/task
https://github.com/keycloak/keycloak/issues/31301
https://github.com/keycloak/keycloak/issues/31507

**Comment by xianli123** [comment]
Stakeholders have reviewed this design. It's all ready for development. Here is [the design prototype](https://www.figma.com/proto/ipJHVANnw4uGat0tPK0y7P/KC---Multi-org?page-id=502%3A49495&node-id=502-49496&viewport=564%2C437%2C0.05&t=VxUF1gMTAmnN8bPE-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=502%3A49496).

**Comment by edewit** [comment]
https://github.com/keycloak/keycloak/pull/32311
