### ISSUE TITLE
[UX Design] Show user's organization info in the Admin and Account UIs

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#31507]
### Description
To make it easier to identify the organizations a user is a member of we might want to update both the Admin and Account UIs to show this information.

Today, the only way to look for the organizations a user is a member of in the Admin UI is by going into each organization and searching for the user. The Account UI does not provide anything.

### Use cases

- If I were an admin, I'd like to check users' organization in the Keycloak Admin console.
- If I were a user, I'd like to check the organization info in my account console.

### Output
Design prototype

### Related issue/task

- https://github.com/keycloak/keycloak/issues/31301
- https://github.com/keycloak/keycloak/pull/29613

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31508
```

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/31509
```

**Comment by edewit** [comment]
closing as all the sub-tasks are done
