### ISSUE TITLE
Allow Embedded Cache sizes to be configured via the CLI

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#31514]
### Description

It should be possible for users to configure the size of Infinispan Embedded caches via the CLI without having to provide
an Infinispan configuration xml.

### Motivation

As Keycloak now supports persistent-user-sessions, a common configuration setting required by users will be to correctly set the size of the various Infinispan caches required in Embedded mode. The current mechanism to configure these settings requires users to provide an Infinispan XML configuration file via the `--cache-config-file` CLI option. This file exposes Infinispan internals to Keycloak users and is overly verbose, as shown by the below example:

```xml
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:15.0 https://www.infinispan.org/schemas/infinispan-config-15.0.xsd"
        xmlns="urn:infinispan:config:15.0">

    <cache-container name="keycloak">
        <distributed-cache name="sessions">
            <memory max-count="10000"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions">
            <memory max-count="10000"/>
        </distributed-cache>
        <distributed-cache name="clientSessions">
            <memory max-count="10000"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions">
            <memory max-count="10000"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

For Kubernetes users, it's all necessary for the above file to be deployed in a ConfigMap and the following added to the
Keycloak CR:

```yaml
spec:
  cache:
    configMapFile:
        name: example
        key: infinispan.xml
```

N.B. It can also be desirable to set a maximum cache size for volatile caches in order to harden Keycloak deployments
against denial-of-service style attacks that could cause OOM exceptions if the cache is unbound.

#### Towards Abtracting Infinispan
In order to simplify Keycloak configuration and user onboarding, we want to reduce the amount of Infinispan knowledge required to operate a deployment as much as possible. Providing high-level Keycloak configuration options for caching semantics helps to achieve this, as users no longer need to become familiar with the Infinispan configuration schema.

### Details

It should be possible for users to configure the max-count of all embedded caches using the following CLI parameter:

`--cache-embedded-<cache-name>-max-count=x`

For example, the persistent-user-sessions configuration used earlier now becomes:

```
--cache-embedded-sessions-max-count=10000 \
--cache-embedded-offline-sessions-max-count=10000 \
--cache-embedded-client-sessions-max-count=10000 \
--cache-embedded-offline-client-sessions-max-count=10000
```

and in the Keycloak CR:

```yaml
spec:
  additionalOptions:
    - name: cache-embedded-sessions-max-count
      value: "10000"
    ...
```

In the future we may want to consider a first class representation in the Keycloak CRD, but I believe the `additionalOptions` option approach is sufficient to begin. Furthermore, the `--cache-embedded-<cache-name>-*` format allows additional per-cache configuration options to be added as required.

#### Activation
The proposed CLI parameters should only be configurable when Embedded caches are required, i.e. not when the `remote-cache` feature is enabled or `cache-remote-*` options specified.

**Comment by ryanemerson** [comment]
@pruivo @keycloak/cloud-native Let me know what you think of the proposal, cheers.

**Comment by ahus1** [comment]
+1 for this. Please note that we'll also need to add the local caches using the same schema, which are `realm`, `users` and `authorization`, as those are the caches people would like to tune most often when it comes to caching more information which would otherwise be fetched from the database.

**Comment by mabartos** [comment]
+1; seems reasonable to me.

**Comment by mhajas** [comment]
I understand using `additionalOptions` is simple and flexible. 

The only problem I can see with this approach is it may be confusing for users as we already have `cache` top-level configuration. Maybe it would be more consistent to design some per-cache configuration within [CacheSpec](https://github.com/keycloak/keycloak/blob/main/operator/src/main/java/org/keycloak/operator/crds/v2alpha1/deployment/spec/CacheSpec.java).

For example:
```yaml
cache:
  sessions:
    max-count: 10000
```
or
```
cache:
  sessions-max-count: 10000
```

the first one may be too loose allowing too many configurations once we add more options per cache (if we add it). With the second we will have more control over what we allow for what cache.

WDYT?

**Comment by ahus1** [comment]
@mhajas - I agree an full support in the CRD would be nice. Still I'd argue to postpone this until we've implemented the CLI options, unless we see an interaction of the two. WDYT?

**Comment by vmuzikar** [comment]
Sorry for the late response. The proposal sounds reasonable to me. I agree let's limit the CR support just to `additionalOptions` field. Adding new fields to CR brings bigger commitment than to CLI as deprecation and removal is quite a complex process. So I'd suggest let's give it some baking time as CLI options and we'll see where that brings us.
