### ISSUE TITLE
Export users throws Disabled option: '--users' in v25

### ISSUE THREAD

**Issue by scurk1415** [keycloak/keycloak#31515]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Since v25 exporting users throws an error:

```
Disabled option: '--users'
Try 'kc.sh export --help' for more information on the available options.
Specify '--help-all' to obtain information on all options and their availability.
```

The command I run:
```kc.sh export --realm <REALM_NAME> --file "/tmp/export-realm.json" --users same_file```

This command was working perfectly until v25 (worked in 24.0.2).

I couldn't find any changelog mentions or issues about this. All I could find was this discussion (https://github.com/keycloak/keycloak/discussions/30462?sort=old), with not real solution (just a workaround).

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The export command not throw the error ```Disabled option: '--users'```

### Actual behavior

Running ```kc.sh export --realm <REALM_NAME> --file "/tmp/export-realm.json" --users same_file```

Throws

```
Disabled option: '--users'
Try 'kc.sh export --help' for more information on the available options.
Specify '--help-all' to obtain information on all options and their availability.
```

### How to Reproduce?

Export a realm with --users in v25

**Comment by shawkins** [comment]
The users option is only valid when exporting to a directory. When exporting to a single file exporting users to the same file is implied.

We can consider either making this validation allow same_file, or the message can be made clearer to indicate why users is not accepted.

~priority-low

**Comment by andre-s-pedrosa-alb** [comment]
What if we want to skip users export? we are forced to use dir export

**Comment by shawkins** [comment]
> What if we want to skip users export? we are forced to use dir export

That is correct. Single flie export never allowed excluding the users.
