### ISSUE TITLE
account-ui lib duplicates React context

### ISSUE THREAD

**Issue by antoine-roux** [keycloak/keycloak#31526]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Hello,

I think you should consider to move PatternFly deps into peer deps and declare it as external.

Currently, the Keycloak's `account-ui` bundle contains all the code of PatternFly.
When I'm creating my own account-theme, the `PageContext` of PatternFly is duplicated: one version from my code, and the one bundled into the Keycloak library. This is problematic as the sidebar is not functional because of that (it does not share the same context)

Before making a PR, I submit my changes here https://github.com/antoine-roux/keycloak/commit/9c181f490c5cfe64fb980a8e9c79405801123069

What do you think?

Antoine

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The React contexts should be unique

### Actual behavior

PatternFly `PageContext` is duplicated in the final bundle

### How to Reproduce?

Based on https://github.com/edewit/account-extend and updated to 25.0.2

**Comment by ssilvert** [comment]
@edewit WDYT?

**Comment by edewit** [comment]
right, @antoine-roux could you make that into a PR?

**Comment by antoine-roux** [comment]
@edewit PR at #31792

**Comment by edewit** [comment]
This is solved in 25.0.4

**Comment by edewit** [comment]
Fixed this with version 25.0.4
