### ISSUE TITLE
refersh token after login failed as #12982

### ISSUE THREAD

**Issue by Ufoton** [keycloak/keycloak#31525]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

After upgrade from 23.0.1 to 25.0.2 errors in consele "Failed to refresh token" like in 12982 but in all browsers. 
And TypeError: Cannot destructure property 'permissions' of '(intermediate value)' as it is undefined.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Client can authenticate 

### Actual behavior

errors 

### How to Reproduce?

No response

**Comment by Ufoton** [comment]
Hello,
Issue resolved after upgrade client lib to 25.0.

**Comment by graziang** [comment]
@Ufoton so can it be closed?
