### ISSUE TITLE
Creating client roles with fine grained permissions is not possible

### ISSUE THREAD

**Issue by Xulunix** [keycloak/keycloak#31537]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

It's currently not possible to delegate the creation of client roles for single clients to a user.
To create clients roles, the realm-wide "realm-management:manage-clients" role is required.
This issue was created as requested in https://github.com/keycloak/keycloak/issues/28633 to handle the creation of roles

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

A client permission is available to allow a user to create roles for a single client via fine grained permissions.
Users with said permission are able to create and manage roles for that client

### Actual behavior

None of the client permissions allow creating client roles.
Creating client roles is only possible with realm-management:manage-clients, allowing much more than just administrating a single client.

### How to Reproduce?

Similar as described in https://github.com/keycloak/keycloak/issues/28633, 
Assigning a user a policy containing the manage permission.
Trying to create a client role results in the error "Forbidden, permission needed: manage-clients"

**Comment by pedroigor** [comment]
@ssilvert This is actually a constraint in the Admin UI. From an API perspective, you should be able to manage client roles as long as you have the `configure` scope properly configured with setting up permissions for your clients.

@edewit Can you confirm that?

**Comment by pedroigor** [comment]
@Xulunix But still, it won't solve the problem of restricting the admin user to only manage roles as they will be able to manage anything in the client.

**Comment by Xulunix** [comment]
> @Xulunix But still, it won't solve the problem of restricting the admin user to only manage roles as they will be able to manage anything in the client.

This is fine, at least in my case, as i want to be able to delegate the management of the entire client to the team responsible for the application.
Currently  they can do that, except creating roles

**Comment by pedroigor** [comment]
@edewit @ssilvert I noticed that the UI is blocking the request to create a client role, even though the user has permissions to `configure` the client. From a backend perspective, we are allowing creating client roles if this permissions is properly set. Can you please confirm my findings?

**Comment by edewit** [comment]
This is something for @ssilvert he knows fine grained permissions the best
