### ISSUE TITLE
Link existing account to SSO by email not linking since v23

### ISSUE THREAD

**Issue by Ketec** [keycloak/keycloak#31563]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Starting from v23 the flow seems to have changed.
When users login and choose link by email they get the email that contains a link to confirm.
This worked fine previously.
Now that link opens another keycloak page where you have to yet again click another link.
That link says (in 23):
_You successfully verified your email. Please go back to your original browser and continue there with the login._

Yet the account was not linked. Going to the kc admin for the user shows no new idp link.
When they attempt to login again, they get sent another email asking them to verify.

In 24/25 that page says "email already verified" - a related bug for that already exists in https://github.com/keycloak/keycloak/issues/31102

Verify email in realm is turned off and IDP has "trust email" enabled.
There should be NO email verification at all. Just confirm to link email.

### Version

23+

### Regression

- [X] The issue is a regression

### Expected behavior

Clicking the link in email should  verify and link SSO

### Actual behavior

Another page opens from email and sso is not linked, even when clicking the link on that page, regardless of successful message.

### How to Reproduce?

Login through an sso with an user that already exists in keycloak and the first login flow contains "verify by email" step.

**Comment by Ketec** [comment]
https://github.com/keycloak/keycloak/commit/142c14138fa6d15afaf58874873b5a4136c5ae05
This seems to be the culprit here. A line that sets  forced email verify step. It does not respect realm settings either.

**Comment by jonkoops** [comment]
@rmartinc does this affect only v25 and up, or should we also be applying downstream patches for v22 and v24?

**Comment by rmartinc** [comment]
I think that 24 is affected but it's not a major issue (it only affects idm email verification when the verification is done in another browser). If someone complains we can backport it to 24.

**Comment by jonkoops** [comment]
No problem, I'll just throw in the backport for good measure since it applies cleanly.

**Comment by jonkoops** [comment]
Upon closer inspection, needs a couple of other commits, so I'll omit it for now.
