### ISSUE TITLE
separated --spi options not picked up by the smallrye config

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#31578]
The previous refinements to the parsing logic were excluding --spi... value options (without an '=') from being picked up by the Config. This was not intentional, just a side effect of the focus on our primary options. So this can be considered / narrowed for backport as well.

_Originally posted by @shawkins in https://github.com/keycloak/keycloak/issues/31448#issuecomment-2243032776_

**Comment by vmuzikar** [comment]
Resolved via https://github.com/keycloak/keycloak/pull/31448
