### ISSUE TITLE
Misconfiguration of login settings causes login to not be possible

### ISSUE THREAD

**Issue by wkbrd** [keycloak/keycloak#31595]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If a user sets Login timeout to 0 as well as Login action timeout to 0, a "Login timeout." timeout appears instead of the login display (username/password/etc.).  This could cause the admin login experience to be locked out and require database manipulation to get back into the Keycloak admin experience.

### Version

latest as of 7/25/2024

### Regression

- [ ] The issue is a regression

### Expected behavior

Login experience is still usable.

Possibly, trying to put in zero values would be blocked by the UI as well.

### Actual behavior

Zero values are accepted and then login experience is replaced by "Login timeout" error message and no username/password prompts.

### How to Reproduce?

In Realm Settings -> Sessions,
Set Login timeout to "0" minutes.
Set Login action timeout to "0" minutes.

Then sign out and attempt to sign back in.

### Anything else?

downloaded using latest tag: docker run quay.io/keycloak/keycloak start-dev

I selected admin/ui as the area since it is where the input entry error took place.

**Comment by wkbrd** [comment]
This is what is seen with a test with the latest docker version:

![image](https://github.com/user-attachments/assets/491a9a43-d89f-4cee-a9a1-ad44ef3afcac)

**Comment by agagancarczyk** [comment]
thanks @wkbrd for reporting this. I can verify that it can be reproduced.

**Comment by ssilvert** [comment]
I'm reassigning this to core-iam team for triage.  It's actually something that should be hardened in the admin REST API instead of doing a brittle "fix" in the UI.
