### ISSUE TITLE
User A's username can equal user B's email address; in that case "I forgot password" works for neither

### ISSUE THREAD

**Issue by corneliusroemer** [keycloak/keycloak#31591]
### Area

Don't know

### Describe the bug

_Caveat: I don't have much experience with keycloak and don't have the time to setup a latest keycloak to check if I can reproduce there, but as I couldn't find this issue fixed in the release notes for 24 or 25, I assume it's still an issue. I have tested on keycloak 23._

I noticed that the "login" and "password-reset" pages accept both username and email. This made me wonder what happens when user A's username is user B's email address. It turns out, that there seems to be a) no validation enforcing uniqueness of the joint set of username/email-address (i.e. I can create a user B with email matching user A's username without keycloak complaining) and that b) password reset does not work in that case for neither A nor B. However, login works: if a string entered into the field "username or password" matches both a username and an email of different users, the user whose username is matched is used. This means that a user whose email address matches another user's username cannot login by providing their email address, they must provide their username (in contrast to the text stating that "username or email address" work.

These are the accounts I created for illustration of what I tested:

<img width="272" alt="Brave Browser 2024-07-24 19 02 55" src="https://github.com/user-attachments/assets/cba675e4-dd57-4c5b-88db-c1b0f5ccfbd7">

<img width="315" alt="Brave Browser 2024-07-24 19 02 48" src="https://github.com/user-attachments/assets/8a7dea11-ddd0-4097-92e1-b4d7cb4f7933">

### Version

23

### Expected behavior

Usernames and email addresses cannot match across users, at account creation, either through validation or by excluding `@` from user names

### Actual behavior

Username of user A can match email address of user B, there is nothing preventing this from happening. This causes issues when either use A or B want to reset their password

### How to Reproduce?

1. Create users with cross-matching usernames and email addresses for example like in the screenshots above (they don't need to cross-match exactly, i.e. only one match must exist of username to password, not two matches, but it doesn't harm to try both)
2. Observe that this is allowed
3. Try to reset password by typing in the matching username/email address
4. Observe that no email is sent to either user

### Anything else?

Workaround: don't allow user names with `@` sign

**Comment by sguilhen** [comment]
This scenario should no longer happen since commit https://github.com/keycloak/keycloak/commit/f9708037383aa98741e4850447de64dc4a0d4b4e was merged, as the validator now checks for users by username as well. This is present since Keycloak 24.

**Comment by corneliusroemer** [comment]
Excellent, what I describe is indeed a dupe of the target you found, thanks @sguilhen!
