### ISSUE TITLE
Can't delete kerberos user

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#31603]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

Contrary to what happens on when attempting to delete an LDAP user, doing so with a user created after a Kerberos log in is not possible. The user is presented with an error "Can't delete user".

I am sending the trace logs. This bug was also confirmed in this issue: https://github.com/keycloak/keycloak/issues/31095

[tracelog.tgz](https://github.com/user-attachments/files/16372154/tracelog.tgz)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

It should either present a human-friendly message saying something like "Kerberos users can't be deleted" or something like that, or, ideally, the user should be removed from the database.

### Actual behavior

An error is displayed.

### How to Reproduce?

Log in with kerberos
Attempt to delete the user

**Comment by vramik** [comment]
In kerberos there is no availability to manage users (search, create, delete,...). Kerberos just logs the user in, so the manageability of users is very limited. That's the reason it does not implement the `UserRegistrationProvider`. Therefore we should improve the error message if possible.

Assigning normal priority for now.

**Comment by pedroigor** [comment]
> In kerberos there is no availability to manage users (search, create, delete,...). Kerberos just logs the user in, so the manageability of users is very limited. That's the reason it does not implement the `UserRegistrationProvider`. Therefore we should improve the error message if possible.
> 
> Assigning normal priority for now.

@vramik Can't we implement the `UserRegistrationProvider` to at least allow removing users created from a Kerberos provider? Otherwise, administrators will be forced to delete the provider and all users federated from Kerberos if they want to remove a single user from Keycloak.
