### ISSUE TITLE
CWE-497 Exposure of Sensitive System Information to an Unauthorized Control Sphere |  Improper Handling of Exceptional Conditions

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31615]
### Description

Hi,

SAST scan of keycloak 24.0.4 in Gitlab CI/CD is reporting following high severity vulnerabilities coming in io.quarkus, io.smallrye, com.arjuna packages.

![image](https://github.com/user-attachments/assets/a2337ad4-22bc-4291-ad41-68c124639931)
![image](https://github.com/user-attachments/assets/c4fe70d0-1c86-444d-bff8-9a963e4d1a73)
![image](https://github.com/user-attachments/assets/e18fc9c0-81bf-4d4a-9e51-823bbefc8f11)
![image](https://github.com/user-attachments/assets/28a55c07-3852-4344-abdd-98f47e060afd)
![image](https://github.com/user-attachments/assets/aa1e3cfb-1877-4042-bcc1-5a8be7062b2c)
![image](https://github.com/user-attachments/assets/5fa4985d-9361-4898-b959-c77c1c354144)
![image](https://github.com/user-attachments/assets/7fcce7b2-645f-4986-95cd-09a7be95d250)
![image](https://github.com/user-attachments/assets/01393d6e-588e-4506-b62c-329ce484ae79)
![image](https://github.com/user-attachments/assets/da8b7779-2a7d-4e03-8361-48b95ce39408)
![image](https://github.com/user-attachments/assets/3a0d5ce5-1634-42dc-b4bd-5b4c94abc1b7)
![image](https://github.com/user-attachments/assets/d15371c6-f0e7-4e1e-8f69-1391aa2767fc)
![image](https://github.com/user-attachments/assets/3eaaebbe-05ea-4298-94df-75e0c04cd0e3)
![image](https://github.com/user-attachments/assets/9c640943-bd53-4b78-bc00-dd1a33636019)
![image](https://github.com/user-attachments/assets/0f56001e-804f-4ccc-bd5d-b21032d0ed20)
![image](https://github.com/user-attachments/assets/9cd4c6d1-40d0-4f02-9fa1-628d8dae28a9)
![image](https://github.com/user-attachments/assets/5b6e604a-d180-4061-8df6-f19715a55ae1)
![image](https://github.com/user-attachments/assets/37c7525e-60c2-444e-a7af-3d199cfc657b)
![image](https://github.com/user-attachments/assets/fcc8b112-6e49-45a2-98d4-6d85a016713c)
![image](https://github.com/user-attachments/assets/ac78536d-c468-4096-b2f7-26e1e4cf3355)
![image](https://github.com/user-attachments/assets/71aeb5d9-d319-454e-8bb2-22d64c065528)
![image](https://github.com/user-attachments/assets/27749d96-20c4-4d0e-ba37-70ac51aa602a)
![image](https://github.com/user-attachments/assets/e74be7d8-9dbe-4115-8159-8c20f4eb3ae3)
![image](https://github.com/user-attachments/assets/f86d2478-e759-4ebb-a9ed-b23bece17fbf)
![image](https://github.com/user-attachments/assets/6a96fb98-622b-4955-b623-4cb4362ce84e)
![image](https://github.com/user-attachments/assets/0886f85b-8191-4d46-944e-004c18c67673)
![image](https://github.com/user-attachments/assets/48067062-3bfb-4981-b74f-aa1193f5bb87)
![image](https://github.com/user-attachments/assets/dad2f185-02ea-4ff4-82f0-f6eb288f623c)
![image](https://github.com/user-attachments/assets/f2df3c36-c350-4521-b6f8-96d8e3fcb3dd)
![image](https://github.com/user-attachments/assets/7fcc4193-2b59-41e7-b05a-1f4ebe90db6e)
![image](https://github.com/user-attachments/assets/b220933a-7c85-43a6-a943-4c6ce7465a69)
![image](https://github.com/user-attachments/assets/76d1cf5d-f6a3-40c1-8da1-36ec153b955e)
![image](https://github.com/user-attachments/assets/4b2fe4c8-087a-4c71-ac12-56128d02e87d)
![image](https://github.com/user-attachments/assets/2d2eeeb6-1fac-42a5-ab77-1e48e1adeb1a)
![image](https://github.com/user-attachments/assets/ae04f232-fe30-4479-aa5c-d9afd1d66955)
![image](https://github.com/user-attachments/assets/24e780ff-fe54-4a30-8488-e07515fbf1cc)
![image](https://github.com/user-attachments/assets/88444567-523a-4c21-a874-5e1adde85846)
![image](https://github.com/user-attachments/assets/d9180bcd-3eba-4cbc-a287-561828880f6e)

![image](https://github.com/user-attachments/assets/e30d4373-c2e7-447d-aaeb-056d7687e7fa)

[CWE-497](https://cwe.mitre.org/data/definitions/497)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
