### ISSUE TITLE
CWE-209 Generation of Error Message Containing Sensitive Information 

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31613]
### Description

Hi,

SAST scan of keycloak 25.0.1 in Gitlab CI/CD is reporting following medium severity vulnerabilities coming in io.quarkus, biz.paluch packages.

![image](https://github.com/user-attachments/assets/9be6c340-3ead-4332-a088-7ed62e3695dd)
![image](https://github.com/user-attachments/assets/d61ec6fc-dc78-4fd4-a829-e3e291c27505)
![image](https://github.com/user-attachments/assets/7b216515-ea18-4621-9eee-a370ff6069bb)

[CWE-209](https://cwe.mitre.org/data/definitions/209)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
