### ISSUE TITLE
import placeholders should be converted to an option

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#31625]
### Description

The [docs](https://www.keycloak.org/server/importExport) mention using placeholders, but that only applies to import on startup.

### Motivation

The operator, and possibly other users, may want to run import with placeholders with a regular import command and should be able to do so without using a system property.

**Comment by shawkins** [comment]
cc @pedroigor @vmuzikar should anyone from core weigh in on this?

**Comment by vmuzikar** [comment]
@shawkins I don't think it's strictly necessary, though @pedroigor's feedback is always welcome. :) Point is, we're not doing any breaking changes to the import provider (I'd keep the sys prop), just adding a dedicated Quarkus dist option for it.

**Comment by shawkins** [comment]
@vmuzikar Thinking about it more I'd rather have placeholders enabled by default at all times rather than introducing another option - that would seemingly line up with the existing documentation as well. 

The only downside is if someone is running kc.sh import currently with values that look like ${...} and don't want them replaced. If this applies to anyone we could suggest the workaround of disabling placeholders via the system property before considering adding another option.

**Comment by vmuzikar** [comment]
@shawkins That sounds reasonable to be opinionated here. Possibly, we could mention the sys property only in the upgrading guide, not in the Import guide to not make too strong implications it's supported.

**Comment by shawkins** [comment]
> @shawkins That sounds reasonable to be opinionated here. Possibly, we could mention the sys property only in the upgrading guide, not in the Import guide to not make too strong implications it's supported.

Ok, that's been added to the upgrade note.
