### ISSUE TITLE
CWE-73 External Control of File Name or Path

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31624]
### Description

Hi,

SAST scan of keycloak 25.0.1 in Gitlab CI/CD is reporting following high severity vulnerabilities coming org.aesh package.

![image](https://github.com/user-attachments/assets/227d6da6-008a-4234-a68e-3b96efa6b605)
![image](https://github.com/user-attachments/assets/4aa5c874-0ce7-4405-8e23-a69771efe8eb)
![image](https://github.com/user-attachments/assets/f61600f2-03ac-43aa-a7d8-a74da150a3db)
![image](https://github.com/user-attachments/assets/de832d22-5ad7-41a1-8af4-c6b09d7b96a6)
![image](https://github.com/user-attachments/assets/22966c30-333d-4cd5-9909-e7923e9aee89)

[CWE-73](https://cwe.mitre.org/data/definitions/73)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
