### ISSUE TITLE
CWE-74 Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection') |  Non-validated write to stream

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31623]
### Description

Hi,

SAST scan of keycloak 25.0.1 in Gitlab CI/CD is reporting following medium severity vulnerability coming org.jgroups package.

![image](https://github.com/user-attachments/assets/66958a93-fbcb-4fd4-9ac5-2d9ca24547ee)
![image](https://github.com/user-attachments/assets/b4e8f8d4-8436-4030-8fc1-d1f1b477dea7)

[CWE-74](https://cwe.mitre.org/data/definitions/74)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
