### ISSUE TITLE
CWE-116 Improper Encoding or Escaping of Output in com.arjuna package

### ISSUE THREAD

**Issue by gurtekOO7** [keycloak/keycloak#31622]
### Description

Hi,

SAST scan of keycloak 25.0.1 in Gitlab CI/CD is reporting following medium severity vulnerability coming in com.arjuna package.

![image](https://github.com/user-attachments/assets/9b83a094-50ae-4641-8d14-81a4ded924aa)
![image](https://github.com/user-attachments/assets/ec0bc1f2-a1ee-4db4-bc96-07778b9e7c0c)
![image](https://github.com/user-attachments/assets/5c2f7bfb-aaec-41be-97f4-ae23c18afd6f)

[CWE-116](https://cwe.mitre.org/data/definitions/116)

**Comment by jonkoops** [comment]
Hi @gurtekOO7, please report security issues with dependencies on the respective repository of said dependency. We cannot fix issues here as we don't maintain these dependencies here. If this is marked as a security issue in the dependency we will upgrade it when a new version is released.
