### ISSUE TITLE
Ldaps UI Issues To be Reported

### ISSUE THREAD

**Issue by althakur** [keycloak/keycloak#31628]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

There are 3 bugs have been identified as part of ldap UI:
1. Two ldaps provider with same display name and details can be added without any warning or error message in UI. Although in database two different ids are created for different ldap provider but in UI , there is no error message displayed while adding multiple ldap provider with same details.
2. Ldaps users are not getting displayed under Member tab of Groups although ldap groups are visible for every ldap users.
3. Ldap groups are not with same count for every ldap users. Example : scp,nrf and admin group is visible under Ben Alex ldap user, but for joe smith user only scp group is visible under groups tab of user details.
[ldap_issues.docx](https://github.com/user-attachments/files/16378847/ldap_issues.docx)

### Version

10.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

1. Two ldaps provider with same display name and details should not be added. Either there should be a error or warning  message displayed in UI
2. Ldaps users should get displayed under Member tab of Groups.
3. Ldap groups should always with the same count for every ldap users. Example : if  scp, nrf and admin groups are visible under Ben Alex ldap user, then same groups should also be visible for joe smith user under groups tab of user details.

### Actual behavior

1. Two ldaps provider with same display name and details can be added without any warning or error message in UI. Although in database two different ids are created for different ldap provider but in UI , there is no error message displayed while adding multiple ldap provider with same details.
2. Ldaps users are not getting displayed under Member tab of Groups although ldap groups are visible for every ldap users.
3. Ldap groups are not with same count for every ldap users. Example : scp,nrf and admin group is visible under Ben Alex ldap user, but for joe smith user only scp group is visible under groups tab of user details.

### How to Reproduce?

[ldap_issues.docx](https://github.com/user-attachments/files/16378975/ldap_issues.docx)

**Comment by althakur** [comment]
Latest keycloak is used for this testing. By mistake I have updated wrong version of keycloak here as 10.0.0. But we have used 24.0.3 version of keyclock.
Please let us know if you have any concern.

**Comment by althakur** [comment]
Hi Team,

Latest keycloak is used for this testing. By mistake I have updated wrong
version of keycloak here as 10.0.0. But we have used 24.0.3 version of
keyclock.
Please let us know if you have any concern.

**Comment by jonkoops** [comment]
24.0.3 is not the latest version of Keycloak, that would be 25.0.2. As outlined in the issue template, we only accept issue reports for the latest version of Keycloak.

**Comment by althakur** [comment]
Sure, Thanks. We will test in latest keycloak of 25.0.2 and get back to you.

**Comment by sguilhen** [comment]
Besides testing in latest keycloak, there's some info missing so we can properly evaluate this report:

For point (2), what is the group mapper configuration, including import mode? It's hard to reproduce anything without this info.
For point (3) I really don't know what those groups are, who are the members and what is the expected result, so this needs to be clarified.

**Comment by althakur** [comment]
[ldap_issues_Indetail.docx](https://github.com/user-attachments/files/16538979/ldap_issues_Indetail.docx)
sguilhen , please refer the detail screenshots with steps and it has also tested with latest version.. Please let me know if you need any additional information or steps.

**Comment by sguilhen** [comment]
@althakur Thanks for the info - on issue 3, those users all have the same group memberships on LDAP? I'm not sure what Keycloak should be showing without knowing the LDAP groups memberships

**Comment by althakur** [comment]
sguilhen , Sure. Let me check and confirm back to you.
