### ISSUE TITLE
localization not work with user attribute display name in users add

### ISSUE THREAD

**Issue by hmz22** [keycloak/keycloak#31633]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I create new realm in admin ui and create new user attribute and set display name and then add localization then when going to users in admin ui and create new user the localization won't work
![Screenshot 2024-07-25 193048](https://github.com/user-attachments/assets/fff743ab-54e4-4d6c-b92b-0f58f3ba65e3)
![Screenshot 2024-07-25 193102](https://github.com/user-attachments/assets/58f6cd8d-db6b-413e-81b6-653408975c78)
![Screenshot 2024-07-25 193112](https://github.com/user-attachments/assets/79b7a282-e94a-4b01-a61b-bade00f38c4a)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

--

### Actual behavior

--

### How to Reproduce?

--

**Comment by agagancarczyk** [comment]
@hmz22 backport PR is up under https://github.com/keycloak/keycloak/pull/31666, should be available in the next patch release 25.0.3.
