### ISSUE TITLE
Admin Console Spins with hostname:v2 using security-admin-console Redirect URIs 

### ISSUE THREAD

**Issue by baparker** [keycloak/keycloak#31640]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The admin console spins when using the security-admin console redirect URIs to access the admin console with hostname:v2 . These redirect URIs do work with hostname:v1 in 25.0.2 and the admin console loads.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Admin console loads using the redirect URIs

### Actual behavior

Admin console spins

### How to Reproduce?

My config file:
hostname= https://kc-fqdn:kc-port/
https-port=kc-port
https-key-store-file=kc-keystore
https-key-store-password=kc-keystorePw

Note: I'm excluding database and log parameters. I have no other parameters set. kc-* are replaced with my actual values.

Steps to reproduce:
kc.bat build --db=kc-db
kc.bat start --optimized
Login, and add redirect URIs to the security-admin-console:
* https://kc-hostname:kc-port/*
* https://kc-ip-address:kc-port/*

Replace kc-fqdn in the brower's URL with kc-hostname or kc-ip-address
Admin console spins (with hostname:v1 configured, the admin console successfully loads)

**Comment by jonkoops** [comment]
Please check the network tab in the browser dev tools to see if any requests are failing.

**Comment by baparker** [comment]
Below is the network tab. I do not see any failures, but only 14 requests are made. Using the FQDN, 70 requests are made - so it seems it is stuck somewhere with hostname:v2 using the hostname or ip address that I entered as the redirect URIs.

![image](https://github.com/user-attachments/assets/8220e438-20dd-4555-85ba-6ed5a10c93ea)

**Comment by shawkins** [comment]
> I have no other parameters set. kc-* are replaced with my actual values.

To confirm, there's no proxy in play here correct?

> These redirect URIs do work with hostname:v1 in 25.0.2

Can you provide the configuration you are using with hostname:v1? Is it just hostname-url instead of using hostname?

**Comment by baparker** [comment]
> To confirm, there's no proxy in play here correct?

Correct, no proxy.

> Can you provide the configuration you are using with hostname:v1? Is it just hostname-url instead of using hostname?

Yes, it's just `hostname-url=https://kc-fqdn:kc-port/`, and of course `features=hostname:v1`.

**Comment by shawkins** [comment]
For a similar setup I can see in the initial response to a console request with hostname:v1 the adminBaseUrl / authUrl use the redirect host, while when using hostname:v2 they do not. From there with hostname:v1 the javascript issues a valid request which sets the redirect url parameter correctly. This does not happen with v2 enabled and you see the spinning behavior.

In v1 the admin host defaults to the host of the incoming request in this situation. In v2 the admin host always resolves to the front end url as long as the admin url is not set. So it seems like you can no longer have a dynamic admin url by using the redirect uris.

cc @vmuzikar @stianst @pedroigor

**Comment by baparker** [comment]
I confirmed `hostname-strict=false` fixes the redirect URI behavior. Based on the docs it seems like that option should only be used when using a proxy. Is that correct?

If so, I cannot utilize that workaround.

**Comment by shawkins** [comment]
> Based on the docs it seems like that option should only be used when using a proxy. Is that correct?

It's generally associated with a proxy because that's where you are likely to allow alternative hostnames based upon the headers. In your situation you want anything that resolves server to be usable without a proxy involved. While that is not called out explicitly, it's still applicable. More than likely this issue will be resolved by additional documentation - both for the hostname-strict option and additional migration notes for hostname v1 to v2.

**Comment by shawkins** [comment]
@vmuzikar can you confirm if you see this as a documentation issue?

**Comment by shawkins** [comment]
> @shawkins IMHO it's not a bug.

Thanks for the confirmation. Is modifying the client redirects a holdover from much older keycloak versions? https://github.com/keycloak/keycloak/discussions/12186 

Since there is a behavioral change between hostname v1 and v2 here it does seem worth mentioning in the docs. We can also change the hostname-strict docs to be more general.

~priority-low

**Comment by vmuzikar** [comment]
> Thanks for the confirmation. Is modifying the client redirects a holdover from much older keycloak versions? #12186

Yes, it's possible the Clients created in older Keycloak versions need some manual migration of the redirect URIs (haven't checked that though). That would either need automatic migration, or a docs mention.

> Since there is a behavioral change between hostname v1 and v2 here it does seem worth mentioning in the docs. We can also change the hostname-strict docs to be more general.

+1 We can update the upgrading guide.

**Comment by baparker** [comment]
> > Login, and add redirect URIs to the security-admin-console:
> 
> @baparker If I understand correctly, you are modifying a redirect URIs of built-in client. I don't think this is really supported, or even needed. The default redirect URI leverages `${authAdminUrl}` variable which expands to `--hostname-admin` (or `--hostname` if `--hostname-admin` is not set). The redirect logic on the welcome page expects this.

@vmuzikar Yes, that's what I'm doing, but I'm also doing it for my realm's security-admin-console. I was allowing the IP address in case something happens to the DNS server so they could still login to the admin console (hence why I set the redirect URIs for the built-in client), and I was following the [hostname documentation](https://www.keycloak.org/server/hostname) for a secure frontend URL (hence why I set the hostname):
> By explicitly setting the hostname option, we avoid a situation where tokens could be issued by a fraudulent issuer.

It also states to configure the acceptable hostnames for my situation in [this documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#mitigating_security_threats):
> By default, the hostname derives from request headers. No validation exists to ensure a hostname is valid. If you are not using a load balancer, or proxy, with Keycloak to prevent invalid host headers, configure the acceptable hostnames.

Thanks for the all the replies - I have more questions as a result, but they really helped me understand the behavior difference better. It seems like with hostname:v1, you could make the frontend URL explicit (not resolved dynamically) and the admin URL could be dynamically resolved; whereas with hostname:v2, the frontend URL and the admin URL must both be explicit (not resolved dynamically) or must both be dynamically resolved. Please correct me if I'm misunderstanding.

My main concern / confusion with the workaround is the security (I'm no expert; just going off the documentation). With my hostname:v1 configuration, I believe I am securing the frontend URL (avoiding a situation where tokens could be issued by a fraudulent issuer - see the same documentation I linked above) while also allowing the admin URL to be dynamically resolved. While the workaround (to set `hostname-strict=false` instead of setting the hostname) does allow the admin URL to be dynamically resolved, doesn't it make the frontend URL vulnerable to the attack described in that documentation?

I didn't realize modifying/adding redirect URIs to the security-admin-console might not be supported. Does [this documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#capability-config) not apply to the security-admin-console client?
> OFF
For client-side clients that perform browser logins. As it is not possible to ensure that secrets can be kept safe with client-side clients, it is important to restrict access by configuring correct redirect URIs.

For my understanding, are the redirect URIs only used/applicable when `hostname-strict=false`?

**Comment by vmuzikar** [comment]
> It seems like with hostname:v1, you could make the frontend URL explicit (not resolved dynamically) and the admin URL could be dynamically resolved; whereas with hostname:v2, the frontend URL and the admin URL must both be explicit (not resolved dynamically) or must both be dynamically resolved. Please correct me if I'm misunderstanding.

Yes, that is correct. Only admin cannot be resolved dynamically as the Admin Console would not know what is the actual correct frontend URL when accessed via the admin URL.

> doesn't it make the frontend URL vulnerable to the attack described in that documentation?

Yes, it does. `hostname-strict=false` is mainly meant for situation when Keycloak is behind a reverse proxy that correctly sets/overrides the headers.

> Does [this documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#capability-config) not apply to the security-admin-console client?

It does but misconfiguring the built-in Clients might lead to unexpected behaviour (as described in this issue).

> For my understanding, are the redirect URIs only used/applicable when `hostname-strict=false`?

No, the redirect URIs are always used. It's just that some of the built-in Clients use variables in the redirect URIs (like `${authAdminUrl}`) which are then resolved by the hostname provider. The provider resolves them dynamically from the incoming request headers if `hostname-strict=false`. This is the potential security issue.

**Comment by shawkins** [comment]
> Yes, it does. hostname-strict=false is mainly meant for situation when Keycloak is behind a reverse proxy that correctly sets/overrides the headers.

My initial thought here and with #32101 initially was that without a proxy hostname-strict=false wasn't as much of a concern, but since that is looking at the host header it's still a problem. 

It sounds like the proper resolution here is that you can only use a single alternative hostname for the admin via the hostname-admin. I've updated #32101 to reflect that.

My understanding of the issue with hostname-strict-false

#32101
