### ISSUE TITLE
Keycloak with nexus OIDC integration 

### ISSUE THREAD

**Issue by vijimgowda** [keycloak/keycloak#31647]
### Description

HI Team @keycloak-bot 

there is no supporting plugin for **OIDC** with nexus and sonar 
is there any plan to enhance with new plugin and previously we **flytreeleft** plugin which is archived now. So confirm once any enhancement for the same.

**Comment by jonkoops** [comment]
We don't strive to maintain any community integrations. Keycloak implements standards-based protocols such as OAuth, OpenID Connect and SAML. As long as the tool you're trying to use supports these, it should just work.
