### ISSUE TITLE
Implement invitation-only self-registration for realm users

### ISSUE THREAD

**Issue by Degoya-Studio** [keycloak/keycloak#31643]
### Description

A good feature would be for an user registration process that allows self-registration only through invitation links, even when self-registration is disabled in the realm settings. This feature will ensure that every new user in a realm is associated with an organization upon registration.

Current behavior:

If self-registration is disabled in realm settings, users cannot register even with an invitation link.

Desired behavior:

- Self-registration is always disabled by default.
- Users can only register using a valid invitation link.
- Each invitation link is associated with a specific organization.

Benefits:

- Increased security by ensuring all users are vetted through invitations
- Guaranteed association between users and organizations from the point of registration
- Flexibility in allowing targeted user registration without opening it up realm-wide

### Discussion

#30180

**Comment by osajdapawel** [comment]
It would also be good if we have pre-filled email in email registration link for organization since we need to specify it to send message (there is also validation that not allows to send form with mail that is different, but pre-fill would be more clear)

**Comment by vramik** [comment]
> It would also be good if we have pre-filled email in registration form from email registration link since we need to specify it to send message (there is also validation that not allows to send form with mail that is different, but pre-fill would be more clear)

+1

> **Define own redirect URI with invitation:** Also would be great if we could specify redirect URI after successful register via invitation. Now it is /account, somebody for example could want to directly redirect user to application ( I see now redirectURL it is stored in token property _reduri_.Token is provided in registration link as query parameter)

I believe this is out of scope of this issue. Please feel free to create new issue for this.

**Comment by duklyro** [comment]
Hi there,

While this feature isn't currently in Keycloak core, there's an actively developed SPI extension that provides invitation-based registration functionality:

**[keycloak-invite-registration](https://github.com/VlastoLabs/keycloak-invite-registration)** by VlastoLabs

This extension works without requiring Keycloak Organizations.

I'm affiliated with this extension as a maintainer.

Hope this helps!
