### ISSUE TITLE
Search for a group never succeed in UI - keep "loading"

### ISSUE THREAD

**Issue by please-openit** [keycloak/keycloak#31667]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When searching for a group by its name, all APIs calls works but the UI shows "Loading".

Loading groups works fine : 
![image](https://github.com/user-attachments/assets/481603c0-8f7c-44d4-8056-26f7f09511ab)

When I search for a group : 

![image](https://github.com/user-attachments/assets/3a283601-d516-480d-b5fa-716584f7f91b)

API works fine.

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

return the group in the tree

### Actual behavior

Keeps "Loading" with the spinner

### How to Reproduce?

Create a group, and a subgroup. Search for the subgroup name.

**Comment by edewit** [comment]
fixed with https://github.com/keycloak/keycloak/pull/31430
