### ISSUE TITLE
Client access settings URLs showing updated values after edit, but token generation happens for initial URL value

### ISSUE THREAD

**Issue by alexejibishvili** [keycloak/keycloak#31686]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Client is created with: Root URL=https://localhost:xxxx, Home URL=https://localhost:xxxx, Admin URL=https://localhost:xxxx.
Flow: Client credentials grant.
Swagger is authorized successfully.
Decompiled bearer token shows it was generated for https://localhost:xxxx.

![kc1](https://github.com/user-attachments/assets/db83f95d-c23a-4424-9e98-9af748c0c1f9)
![kc2](https://github.com/user-attachments/assets/33a5cdff-01d6-46f2-992c-7fe08d7971e6)
![kc3](https://github.com/user-attachments/assets/8a766d2c-0cc1-49b5-92d1-2dab230db910)

Then I want to change my application URL to https://localhost:yyyy.
I change my application configuration to run on a new port: yyyy.
Accordingly I go to Keycloak admin and input a new Root URL, Home URL and Admin URL = https://localhost:yyyy.
These values in the form are updated and saved!
When I run my application on a new URL (https://localhost:yyyy), Swagger can not authenticate and I get an error.

![kc4](https://github.com/user-attachments/assets/ed9de426-5974-410a-b80d-f0f97b4e83e8)

I change my application configuration back to https://localhost:xxxx, at this time Keycloak admin shows URL values with a different URL, which is https://localhost:yyyy.
I run my application and Swagger authenticates successfully again.
My app runs on https://localhost:xxxx, Keycloak shows https://localhost:yyyy, but bearer token is generated for https://localhost:xxxx.

Only when I delete that client record, create new one with an initial value of https://localhost:yyyy, I can achieve my goal to move my application to a new URL.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I change URL of my app.
I go to Keycloak admin and update client URL records.
When authenticating token generation happens for a new URL.

### Actual behavior

I change URL of my app.
I go to Keycloak admin and update client URL records.
When authenticating token generation happens for the value I filled in initially while creating the client record.
Application can't authenticate running on a new URL.
I have to delete the client record.
Create a new client with the same name, but with new URLs.
Then application works on new URL.

### How to Reproduce?

...

**Comment by mposolda** [comment]
Adding it as low priority, not even sure if this is valid bug. Looks like a mis-configuration or environment issue...

@alexejibishvili Please make sure to doublecheck all other URLs for client in the admin console in all tabs of client. Especially for example `Web origins` . Also make sure to update all URLs on the swagger side.
