### ISSUE TITLE
"Use metadata descriptor URL" switch is always set to "On"

### ISSUE THREAD

**Issue by jskeycloakuser** [keycloak/keycloak#31687]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

"Use metadata descriptor URL" switch in the IDP config is always set to "On". If you click the button and save the webform the GUI renders the button as off, the API returns the correct value, but on reload, the button again gets rendered as "On"

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

"Use metadata descriptor URL" should be rendered as "Off"

### Actual behavior

"Use metadata descriptor URL" gets rendered as "On"

### How to Reproduce?

Create a SAML IDP and use the switch. Save the IDP and reload the page. Then check again.

### Anything else?

It worked with the latest 24 release.

**Comment by edewit** [comment]
Do you mean the `Use entity descriptor` switch? That is just used to add values from an endpoint, it's not saved as part of the Identity provider

**Comment by jskeycloakuser** [comment]
I mean a switch labeled "Use metadata descriptor URL".
![image](https://github.com/user-attachments/assets/cf40b582-14d4-47b6-a576-aa519169957b)
The image shows the state of the GUI after save and reload. In the representation of the IDP it states: useMetadataDescriptorUrl : false

If i "disable" it, it changes the value of useMetadataDescriptorUrl from true to false (and back, if clicked again). But in the GUI it stays in the enabled state after reload. Also, if the switch just determines if a URL should be used if present, shouldn't the supplied URL  be enough and the switch would be redundant? Feel free to correct me if I'm missing something :)
