### ISSUE TITLE
Convert chapter Keycloak Node.js adapter from securing apps into guides

### ISSUE THREAD

**Issue by graziang** [keycloak/keycloak#31696]
### Description

Move Keycloak Node.js adapter chapter as done for OIDC chapter
https://www.keycloak.org/docs/latest/securing_apps/index.html#_nodejs_adapter

**Comment by Zysberg** [comment]
Question, in a blog post they said thery are deprecating the NodeJS adapter, so what will replace this?

**Comment by jonkoops** [comment]
A search for a replacement is ongoing, see #9818 for more information.
