### ISSUE TITLE
ID is used as tab name instead of localized string

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#31704]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

![image](https://github.com/user-attachments/assets/a1ba2d72-d62d-4628-85fe-9013abf924ca)

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

nice

### Actual behavior

not nice

### How to Reproduce?

create a custom tab and see it

**Comment by kaustubh-rh** [comment]
Hi @edewit , can I raise a PR for the same ?
