### ISSUE TITLE
The OID4VCI cross-device flow should not require the device to have an access token

### ISSUE THREAD

**Issue by wistefan** [keycloak/keycloak#31712]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oid4vc

### Describe the bug

When a users tries to receive a VerifiableCredential through the OID4VCI pre-authorized flow, by using the account console, the [credential-offer endpoint](https://github.com/keycloak/keycloak/blob/69642f142728b1e3a16887b1022e13d8b5b2ed61/services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java#L200) expects an valid access-token. In a cross-device flow(f.e. when a user scans the QR-code with its mobile wallet) the device has no access-token and should be able to retrieve the offer with just the information from the QR.

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The nonce/code provided as part of the credentials-offer-uri through the [credential-offer-uri endpoint](https://github.com/keycloak/keycloak/blob/69642f142728b1e3a16887b1022e13d8b5b2ed61/services/src/main/java/org/keycloak/protocol/oid4vc/issuance/OID4VCIssuerEndpoint.java#L134) is sufficient for retrieving the credentials-offer.

### Actual behavior

When only the nonce/code provided as part of the credentials-offer-uri is used for retrieving the offer, keycloak fails with a 500, since it expects a valid access-token. 

### How to Reproduce?

- run Keycloak with the OID4VCI feature enabled
- open the account console and select a VerifiableCredentials configuration
- scan the QR with a wallet and use it to retrieve a credential
-> the response to the wallet will be 500

**Comment by wistefan** [comment]
I will work on that issue. I would propose as a solution:
- generate an [OAuth2Code](https://github.com/keycloak/keycloak/blob/69642f142728b1e3a16887b1022e13d8b5b2ed61/services/src/main/java/org/keycloak/protocol/oidc/utils/OAuth2Code.java) to be used instead of the nonce in the credential-offer-uri
  - the code is connected to the active session that generated the QR-Code
  - the full credentials-offer is generated at the same time and stored as part of the active session(including the pre-authorized code)
- the Oauth2Code will be provided the same way as the current nonce as part of the credential-offer-request, e.g. ```credential-offer/<oauth2code>```
- the credential-offer endpoint will parse the code and retrieve the offer from the session to be returned to the wallet for further usage

Rational:
- OAuth2Codes are well supported by Keycloak already and intended to retrieve very short-lived data once -> the offer should be short-lived for security reasons and only be returned once
- if the full offer is created at time of creation of the Oauth2Code, the user of the code will only be able to retrieve exactly what was authorized at that time

**Comment by francis-pouatcha** [comment]
I also do think it is a good idea to proceed with something similar to the OAuth2Code.

If the OAuth2Code class can contain the data we need, we might reuse it. If not, I won't mind defining and new PreAuthCode following the same phylosophy like the OAuth2Code.
