### ISSUE TITLE
KC doesn’t enforce uniqueness of aliases in Authentication flows, but uses them as identifiers (in config export)

### ISSUE THREAD

**Issue by jirutka** [keycloak/keycloak#31727]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

See below.

### Version

24.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should enforce the aliases to be unique per realm.

### Actual behavior

Keycloak allows to define multiple steps with the same alias and uses this non-unique identifier in the flow executions to reference the associated authenticator config.

```jsonc
{
  "authenticationFlows": [
    {
      "authenticationExecutions": [
        {
          "authenticatorConfig": "foo",  // <-- HERE
          "authenticator": "allow-access-authenticator",
          //...
        },
        {
          "authenticatorConfig": "foo",  // <-- HERE
          "authenticator": "deny-access-authenticator",
          //...
        }
      ],
      //...
    }
  ],
  "authenticatorConfig": [
    {
      "id": "946bac8f-1b51-43e2-b110-0a36d996a891",
      "alias": "foo",  // <-- HERE
      "config": {
        "default.reference.value": "bar"
      }
    },
    {
      "id": "549a33b1-4c94-4ba2-82bf-a4eec1854422",
      "alias": "foo",  // <-- HERE
      "config": {
        "default.reference.value": "baz"
      }
    }
  ],
  // ...
}
```

### How to Reproduce?

1. Create a new Authentication flow.
2. Add some step to the flow, set _alias_ (e.g. `foo`) and some attributes (e.g. Authenticator reference).
3. Add another step and set the same _alias_ as before and some attributes.
4. Export configuration to JSON.
5. You can see that there are two `authenticatorConfig` items with the same alias and two `authenticationFlows` referencing the configs by the alias name.

### Anything else?

I'm using version 24.0.6, but I didn’t find any mention of this in the release notes for ≥25.0.0.

Another problem is that when you remove the step, Keycloak does not remove the associated config from the database. This must be fixed as well, otherwise users would not be able to reuse already “removed” aliases…

**Comment by rmartinc** [comment]
I have been checking this today and I see two ways to fix this:

1. Checking the config alias is unique, like we are doing for the flow [here](https://github.com/keycloak/keycloak/blob/26.0.0/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L253-L255), but in the [newExecutionConfig](https://github.com/keycloak/keycloak/blob/26.0.0/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L1021) and other part that create auth configurations.
2. The second option is just not using the alias in the export and use the ID. This way we don't have the limitation of using the same alias. The import needs to fallback to the alias name if the ID is missing to load previous exports.

Point 1 would need changes in the database to ensure the alias is unique, but I wouldn't add the constraint for compatibility reasons. Adding the constraint would fail in current installations with duplicate aliases. It's not there even for the flow alias now. I have to decide what option I prefer, I'm not sure right now, I see pros and cons in each one.

**Comment by jirutka** [comment]
I strongly prefer the first option, UUIDs are quite unusable for configuration management (using e.g. [keycloak-config-cli](https://github.com/adorsys/keycloak-config-cli)).

**Comment by dankots** [comment]
Can you please fix the text in this error message?  Just spend to much time figuring out why this isn't working as before.
thanks!

https://github.com/keycloak/keycloak/commit/20044677499a03edf879660d69ac9ea4ae602481#r156151510
