### ISSUE TITLE
Persist revoke tokens with remote cache feature

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#31760]
Add options to persist the revoked tokens into the database when the feature `remote-cache` is enabled. 
The revoke tokens are preloaded from the database at boot time and stored in the remote cache. 

This is a follow-up to issue #31296

**Comment by ahus1** [comment]
Thank you @pruivo for creating this issue. 

There was a comment from Marek Posolda on the previous PR after it was closed to consider a refactoring for the 900 seconds interval, see https://github.com/keycloak/keycloak/pull/31303#discussion_r1693284470

I'd be happy if you could handle this in this PR as well, as I assume you would also need that interval in your setup. Thanks!
