### ISSUE TITLE
REVOKED_TOKEN table is missing

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#31774]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

The current build cannot be started due to missing table `REVOKED_TOKEN` that was introduced with commit 227c71f7f0457d12f5130e03997b69823f50a5f7.
The table must be added to the liquibase script

### Version

999.0.0-SNAPSHOT before release 26

### Regression

- [ ] The issue is a regression

### Expected behavior

keycloak should be able to start after build

### Actual behavior

keycloak does not start after build due to missing table

### How to Reproduce?

build the keycloak and start the artifact from the zip or the tar-ball

**Comment by ahus1** [comment]
I assume you're running a SNAPSHOT version of Keycloak against a database which was created with an earlier SNAPSHOT version of Keycloak. Upgrading an installation between SNAPSHOT versions is not supported, as migrations can still change before Keycloak is released. 

The usual recommendation is to start each new snapshot/nightly release with an empty database, or with a database created with an earlier regular release. Sometimes it will work if you remove the the row from `MIGRATION_MODEL` which states `999.0.0` as a version.
