### ISSUE TITLE
Keycloak 25 SAML IdP has made Single Logout URL mandatory.

### ISSUE THREAD

**Issue by gknapowski** [keycloak/keycloak#31781]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

The Single Logout Service is an optional field of SAML2. Versions of Keycloak <25.0.0 did not require this value to configure an IdP 

KC versions >=25.0.0 have this marked as required.

![image](https://github.com/user-attachments/assets/df1f1966-c027-4724-9afe-5d24527cf405)

In the past the field was not require (from 24.0.5):
![image](https://github.com/user-attachments/assets/10cdb55e-51da-4414-881d-fc485dece316)

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

a Single Logout URL should not be required. 

### Actual behavior

Without providing a value the looks like URL (https://something), the IdP cannot be created. While this works, it will create issues down the line.

### How to Reproduce?

1. Create a new SAML2 idP
2. Slide **Use entity descriptor** to off
3. Fill out required fields, leaving **Single logout service URL** empty
4. Observe you cannot create the IdP

### Anything else?

I noticed in conjunction with #31780

If this is by design, my apologies.

**Comment by rmartinc** [comment]
I see this was changed in this commit: https://github.com/keycloak/keycloak/pull/27705.

My feeling is that it was not done on purpose. @edewit Can you confirm? If you agree we can just remove the required, I can send the PR if needed.

**Comment by edewit** [comment]
Just dowloaded and ran 24, it's already required there as well

**Comment by rmartinc** [comment]
@edewit The issue is in the [singleLogoutServiceUrl](https://github.com/keycloak/keycloak/blob/24.0.6/js/apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx#L136-L159), it's the one that is required now and it was not before. The `singleSignOnServiceUrl` is required and it's OK.

**Comment by deanmaster** [comment]
hi @agagancarczyk 
With current Keycloak version 25.0.4, we can't use backchannel logout with SAML anymore. The logout only available with frontchannel logout. 

I guess it related to this change ?
