### ISSUE TITLE
Social Login test failures

### ISSUE THREAD

**Issue by lhanusov** [keycloak/keycloak#31791]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Failed tests:
-  org.keycloak.testsuite.broker.SocialLoginTest.openshiftLogin
-  org.keycloak.testsuite.broker.SocialLoginTest.bitbucketLogin
-  org.keycloak.testsuite.broker.SocialLoginTest.openshift4Login
-  org.keycloak.testsuite.broker.SocialLoginTest.googleLogin
-  org.keycloak.testsuite.broker.SocialLoginTest.githubLogin
-  org.keycloak.testsuite.broker.SocialLoginTest.facebookLoginWithEnhancedScope
-  org.keycloak.testsuite.broker.SocialLoginTest.facebookLogin
-  org.keycloak.testsuite.broker.SocialLoginTest.stackoverflowLogin
-  org.keycloak.testsuite.broker.SocialLoginTest.twitterLogin

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

all tests should pass

### Actual behavior

9 social login tests fail

### How to Reproduce?

trigger pipeline job with social login step

**Comment by wojnarfilip** [comment]
Replaced with: https://github.com/keycloak/keycloak/issues/32465
