### ISSUE TITLE
log-syslog-output=json does not provide valid json

### ISSUE THREAD

**Issue by stefan-kalb** [keycloak/keycloak#31795]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

- enable syslog
- set log-syslog-output=json

The log message which is sent to the syslog-server is not a valid json object. The log-message starts with  the loggerName as plain text without proper json formatting.

Log snippet (shortened):
`org.keycloak.events - ﻿{"timestamp":"2024-07-30T15:14:49.0743686+02:00","sequence":10500,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.events","level":"INFO","message":"type=\"LOGIN\", realmId=\"4b939ad4-eaa4-489a-a818-300000000\"}`

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The log message sent to the syslogserver is a valid json object.
`﻿{"timestamp":"2024-07-30T15:14:49.0743686+02:00","sequence":10500,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.events","level":"INFO","message":"type=\"LOGIN\", realmId=\"4b939ad4-eaa4-489a-a818-300000000\"}`

### Actual behavior

The log message sent to the syslogserver is not a valid json object.
`org.keycloak.events - ﻿{"timestamp":"2024-07-30T15:14:49.0743686+02:00","sequence":10500,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.events","level":"INFO","message":"type=\"LOGIN\", realmId=\"4b939ad4-eaa4-489a-a818-300000000\"}`

### How to Reproduce?

- enable syslog
- set log-syslog-output=json

**Comment by shawkins** [comment]
@stefan-kalb I believe what you are seeing is a RFC5424 header, which includes the logger name. However it is not being interpreted as such - https://github.com/jboss-logging/jboss-logmanager/blob/5f444f8cc651c6bb491f7d8275dea46cebb0b65d/src/main/java/org/jboss/logmanager/handlers/SyslogHandler.java#L1311

[quarkus.log.syslog.syslog-type](https://quarkus.io/guides/logging#quarkus-log-logging-log-config_quarkus-log-syslog-syslog-type) could be changed in the quarkus.properties to see if rfc3164 could work for you instead.

cc @mabartos

**Comment by stefan-kalb** [comment]
@shawkins thanks for the quick reply.
That might be intended as header, but it seems to be part of the logmessage. BTW the same happens when I use the log-syslog-format string mentioned in the docs. But it just happens for syslog. Console works fine with the very same configuration.

How do I configure the quarkus.log.syslog.syslog-type setting? 
I neither compile the code nor run docker. And it seems trying to set it in keycloak.conf has no effect, but maybe I am doing it wrong.

**Comment by shawkins** [comment]
> That might be intended as header, but it seems to be part of the logmessage.

It's not clear to me if that's a bug with the jboss logging syslog RFC 5424 header, or if it's an issue with how it's being interpretted. The spec just calls for up to a string https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.7

> Console works fine with the very same configuration.

That uses a different handler.

> I neither compile the code nor run docker. And it seems trying to set it in keycloak.conf has no effect, but maybe I am doing it wrong.

See quarkus.properties in https://www.keycloak.org/server/configuration - it how you would set an arbitrary quakus property.

**Comment by stefan-kalb** [comment]
Sorry, I just don't get it work.
I created a quarkus.properties in the conf directory. But it's ignored. If I use the -cf parameter to enforce loading the quarkus config the keycloak.conf is ignored (as expected).
So I tried to migrate all keycloak.conf setting to the commandline. But quarkus seems not to send any logs to my syslog server, no console messages either. 

`quarkus.log.syslog.enable=true
quarkus.log.syslog.endpoint=adm-logs-10.lab.lan:11514
quarkus.log.syslog.app-name=keycloak
quarkus.log.syslog.syslog-type=rfc3164
quarkus.log.syslog.protocol=udp
quarkus.log.syslog.use-counting-framing=false
quarkus.log.syslog.level=ALL`


If I am supposed to provide better data I need more direct instructions.

I can live without direct syslog logging as I can use the log-file handler as workaround, but I would prefer the syslog handler for various reasons.
From my point of view (log-server admin) keycloak sends invalid formatted json-messages. Other products sending json formatted messages directly to our syslog servers don't include the MSGID at the start of the log message.

**Comment by shawkins** [comment]
> I created a quarkus.properties in the conf directory. But it's ignored.

How can you tell if it's ignored?

> So I tried to migrate all keycloak.conf setting to the commandline. But quarkus seems not to send any logs to my syslog server, no console messages either.

Arbitrary quarkus properties can only be set via the quarkus.properties file. They will be ignored as command line options.

> From my point of view (log-server admin) keycloak sends invalid formatted json-messages.

The issue here is not with the json formatting, but with the syslog header. Or are you saying that syslog logging works as expected if the json format is not used?

> Other products sending json formatted messages directly to our syslog servers don't include the MSGID at the start of the log message.

You'll need to compare the entire message, including the header, to see what might be different. As you can see from the RFC docs it's not clear what the problem is from just what is here.

**Comment by stefan-kalb** [comment]
I think I found a better workaround for my issue.
keycloak syslog -> local rsyslog server -> forward to -> central graylogserver syslog input

Furthermore rsyslogd seems to interpret RFC 5424 the way keycloak does and forwards the json messages to graylog server in a format, which the graylog syslog input is able to interpret correctly.

**I conclude my point of view:**
An unclear standard definition leads to different interpretations of the standard. As it works with rsyslogd, in my point of view it's rather an issue of the syslog input of graylog server than a keycloak issue. Feel free to close the issue.

**Comment by shawkins** [comment]
> An unclear standard definition leads to different interpretations of the standard. As it works with rsyslogd, in my point of view it's rather an issue of the syslog input of graylog server than a keycloak issue. Feel free to close the issue.

Sounds good. Having a workaround with rsyslog may help others.
