### ISSUE TITLE
oidc-usersessionmodel-note-mapper mapps clientId to client_id

### ISSUE THREAD

**Issue by akostenev** [keycloak/keycloak#31806]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

# Bug

In previous versions of keycloak (for example 20.0.5) the default oidc-usersessionmodel-note-mapper would map the "default" fields `clientHost`, `clientId`, `clientAddress`, while never versions use a different mapping to `client_id`.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

The default oidc-usersessionmodel-note-mapper should map Client ID to `clientId` in the JWT token.

### Actual behavior

In previous versions of keycloak (for example 20.0.5) the default oidc-usersessionmodel-note-mapper would map the "default" fields `clientHost`, `clientId`, `clientAddress`, while never versions use a different mapping to `client_id`.

![grafik](https://github.com/user-attachments/assets/6d13b815-4897-49f5-a999-cb86bfcfad6a)

A token therefore contains the fields

```json
{
  "exp": 1722427651,
  "iat": 1722427591,
  "jti": "3839c692-0673-4496-b3af-12f3505edab6",
  "iss": "***",
  "aud": [
    "realm-management",
    "account"
  ],
  "sub": "c18502d5-0a22-4ccf-8674-12ec55b10e0b",
  "typ": "Bearer",
  "azp": "akostenev",
  "acr": "1",
  "allowed-origins": [
    "/*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "someOtherRoles"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "someOtherRoles"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "",
  "clientHost": "10.42.0.1",       <--- default mapped field clientHost
  "clientAddress": "10.42.0.1",  <--- default mapped field clientAddress
  "clientId": "akostenev"           <--- default mapped field clientId
}
```

In newer versions (e.g. latest 25.0.2) the default mapping of  `clientId` has changed, while the other `clientHost`, `clientAddress` stayed the same.

![grafik](https://github.com/user-attachments/assets/07138a26-b722-4523-9c88-5a1757b296fe)

A token therefore contains `client_id` and not `clientId`.

```json
{
  "exp": 1722427651,
  "iat": 1722427591,
  "jti": "3839c692-0673-4496-b3af-12f3505edab6",
  "iss": "***",
  "aud": [
    "realm-management",
    "account"
  ],
  "sub": "c18502d5-0a22-4ccf-8674-12ec55b10e0b",
  "typ": "Bearer",
  "azp": "akostenev",
  "acr": "1",
  "allowed-origins": [
    "/*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization",
      "someOtherRoles"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "someOtherRoles"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "",
  "clientHost": "10.42.0.1",       <--- default mapped field clientHost
  "clientAddress": "10.42.0.1",  <--- default mapped field clientAddress
  "client_id": "akostenev"           <--- default mapped field client_id (which is our Problem)
}
```

### How to Reproduce?

1. Setup a new latest (25.0.2) keycloak
2. Configure a new client for your realm

We use the following client capability config
![grafik](https://github.com/user-attachments/assets/6916478b-24ce-4bb1-b8a4-f2b69f25f73b)

4. Navigate to the details of your client > Client Scopes > "Assigned client scope"

![grafik](https://github.com/user-attachments/assets/f5fbb633-ef70-4e36-8cae-9b08807e9342)

5. There you see the 3 default mappers for `Client Host`, `Client ID`, `Client IP Address`.

![grafik](https://github.com/user-attachments/assets/ef7177b5-4b13-47f9-905c-5783b5e9aa53)

6. Go to `Client ID` which has an incorrect mapping to client_id

![grafik](https://github.com/user-attachments/assets/5ba57edf-ac4a-482a-8752-463e1fd7c403)

### Anything else?

Is this a bug?
If no: is `client_id` a new standard?
If yes: why is only the `client_id` in snake_case?

**Comment by rmartinc** [comment]
@akostenev This was done because of https://github.com/keycloak/keycloak/issues/16329 and it's also documented in the upgrading notes [here](https://www.keycloak.org/docs/latest/upgrading/index.html#change-of-the-default-client-id-mapper-of-service-account-client). If you see the related PR https://github.com/keycloak/keycloak/pull/16359 discussed about this can break things and the final agreement was that another mapper can always be added to the client using `clientId` instead of  `client_id`. So I think that this can be closed as it was already discussed and it was decided to work in the current way. WDYT?

**Comment by akostenev** [comment]
ACK, we were used to clientId, but client_id works too as long as it is stable (i.e. it hopefully does not change again)
