### ISSUE TITLE
"manage-events" inconsistent behaviour when saving Admin Event config

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#31804]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When an user is having all roles, including "manage-realm", but not having "manage-events", and want to update the Admin Events config, an error is shown in the network tab and in the UI, but the config is actually updated

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The Event Config to not be updated, as the "manage-events" role is not assigned to the user (or in case it is expected the user to be able to edit this setting, only by having "manage-realm", no error to be shown).

### Actual behavior

Error is displayed in the UI and in the Network Tab, but the config is updated anyway.

### How to Reproduce?

1. Create realm
2. Create user with password
3. Assign all "realm-management" roles, except "realm-admin" and "manage-events"
4. Open the security-console of the realm with the created user
5. Go to Realm settings - events - Admin events settings
6. Add new value for the "Expiration" for example
7. Save

![2024-07-31_16h03_40](https://github.com/user-attachments/assets/a4e2a6c6-7cd9-4509-a66e-ad78cc53909f)

**Comment by ssilvert** [comment]
@mposolda @stianst WDYT?

If a user has `manage-realm`, but not `manage-events`, should they be able to save the events config?

**Comment by ssilvert** [comment]
@mpalavrov Can you try this with the nightly build?  I'm getting a 403, which I think probably what is intended.  So at least it's no longer allowing the user to save the config if they don't have `manage-events`.
https://github.com/keycloak/keycloak/releases/tag/nightly

Do you agree that this is the correct behavior with the user prohibited from saving?  I suppose we could improve things by making the form read-only in this situation.  WDYT?

**Comment by mpalavrov** [comment]
Hi @ssilvert,
On step 6 (Add new value for the "Expiration" for example), it is still not working as expected. If the Admin Events (Save Events) is enabled, and with the user without "manage-events" role you try to change just the "Expiration", it is returning 403, yes, but the value is actually saved :(
Returning 403 is OK to me, but the question is to really Forbidden, not only to show that it is, but the value for the Expiration to be saved.

Having the fields "read-only" would be great improvement, but it should be for all the menus, where only "view" access is provided to the users, not only in for this in particular.

**Comment by ssilvert** [comment]
@mpalavrov Yes, I see it too now.  This is an interesting issue.

The problem is that we are doing PUT on the entire realm because `adminEventsExpiration` is saved as a realm attribute.  But in this case, the back end should not allow that attribute to be changed because the user does not have the `manage-events` role.

I'm going to switch this to `core-iam` team for a server side fix.
