### ISSUE TITLE
Management Interface is turned on even though nothing is exposed on it

### ISSUE THREAD

**Issue by baparker** [keycloak/keycloak#31818]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I'm not sure if this is a bug or feature suggestion. It seems like a bug based on the [Management Interface Docs](https://www.keycloak.org/server/management-interface).

> The management interface is automatically turned off when nothing is exposed on it. Currently, only health checks and metrics are exposed on the management interface regardless.

When the health and metrics endpoints are disabled (which is the default), then it seems the management interface should be turned off because nothing is exposed on it. However, the management interface is still turned on for me - it is accessible via the base management URI and the log shows `Management interface listening on https://0.0.0.0:9000.`. If the above documentation is the intended behavior, the this is a bug.

If the intended behavior is for the management interface to always be on, even when nothing is exposed on it, then this is a feature suggestion to turn it off when nothing is exposed on it. I do not want to expose another port. Because of this bug/behavior, I'm using `legacy-observability-interface` for now, but it is deprecated.

----
As an alternative solution to using `legacy-observability-interface`, I tried setting the `http-management-port` to the same port as Keycloak, `https-port`, (I also set `http-management-relative-path=/management`), but I'm getting intermittent "Resource not found" errors 6% of the time accessing the admin console and making API calls (130 errors out of 1933 calls). This is causing failures in automation I've done for configuring our realm. Also, I'm aware this is documented as not a security best practice, but since I am not enabling the health and metrics endpoints, I thought this would be a viable solution. If the management interface can be turned off, then I would have no need to set the management port to the same as the Keycloak port.

Examples of the API calls getting "Resource not found":
* GET https://kc-fqdn:kc-port
* GET https://kc-fqdn:kc-port/admin/realms/master
* POST https://kc-fqdn:kc-port/realms/master/protocol/openid-connect/token
* GET https://kc-fqdn:kc-port/admin/realms/<my-realm>/client-scopes
* POST https://kc-fqdn:kc-port/admin/realms/<my-realm>/roles

Below is a screenshot of the error in the admin console and the network tab (again only occurring about 6% of the time):
![image](https://github.com/user-attachments/assets/a30ca12d-a15d-482b-a799-4b1c70e1ea3b)

![image](https://github.com/user-attachments/assets/4298ed2f-1c1a-4193-832e-32b11930e6a6)

![image](https://github.com/user-attachments/assets/6640686e-17c4-497e-a7cb-9de1ceefb013)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The management interface is automatically turned off when nothing is exposed on it.

### Actual behavior

The management interface is still turned on - it is accessible via the base management URI and the log shows `Management interface listening on https://0.0.0.0:9000.`.

### How to Reproduce?

My config file:
hostname= https://kc-fqdn:kc-port/
https-port=kc-port
https-key-store-file=kc-keystore
https-key-store-password=kc-keystorePw

Note: I'm excluding database and log parameters. I have no other parameters set. kc-* are replaced with my actual values.

Steps to reproduce:
kc.bat build --db=kc-db
kc.bat start --optimized
The management interface is still turned on - it is accessible via https://kc-fqdn:9000/ and the log shows `Management interface listening on https://0.0.0.0:9000.`.

----
Just in case, here is the configuration for my alt. solution that is giving me errors:
hostname= https://kc-fqdn:kc-port/
https-port=kc-port
http-management-port=kc-port
http-management-relative-path=/management
https-key-store-file=kc-keystore
https-key-store-password=kc-keystorePw

kc.bat build --db=kc-db
kc.bat start --optimized
Getting "Resource not found" 6% of the time via any admin console UI pages and any API calls. Some API examples getting the error:
* GET https://kc-fqdn:kc-port
* GET https://kc-fqdn:kc-port/admin/realms/master
* POST https://kc-fqdn:kc-port/realms/master/protocol/openid-connect/token
* GET https://kc-fqdn:kc-port/admin/realms/<my-realm>/client-scopes
* POST https://kc-fqdn:kc-port/admin/realms/<my-realm>/roles

**Comment by mabartos** [comment]
@stianst Ahh, didn't notice that you added the `triage` label - can you elaborate?

**Comment by mabartos** [comment]
Out of triage as it is a valid issue.

**Comment by stianst** [comment]
@mabartos it needs a priority set on it before moving out of triage. Ideal way to triage issues is using the action labels as it sorts out the rest for you, see https://github.com/keycloak/keycloak/blob/main/docs/bug-triage.md
