### ISSUE TITLE
KeyCloak Client Keys Page Import Error Messages Worse Than Useless

### ISSUE THREAD

**Issue by EmperorArthur** [keycloak/keycloak#31815]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

Attempting to import a JWKS on the Client -> Keys page fails if the file is does not have a "SIG" use field, or has some other problem.  However, the error message produced is not helpful at all, and it required reading the source code to determine this is required.

The only information is "Certificate or key with given alias not found in the keystore".  Which has nothing to do with the problem.
That error message comes from [this line](https://github.com/keycloak/keycloak/blob/5284641b9df7566261e6693f9cee96a3ba5b3586/services/src/main/java/org/keycloak/services/resources/admin/ClientAttributeCertificateResource.java#L191).

The annoying part is that error was caused by [this line](https://github.com/keycloak/keycloak/blob/5284641b9df7566261e6693f9cee96a3ba5b3586/services/src/main/java/org/keycloak/services/resources/admin/ClientAttributeCertificateResource.java#L228), and is hiding the useful error message!
> IllegalStateException("Certificate not found for use sig")

I actually thought there was a completely different issue until I finally decided to search the source code, and still have not been able to get this working!

Note: The inner exception could also probably use an error message useful for people who have not just browsed the JWKS RFC.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The error message produced helps a user understand why things are not working.

### Actual behavior

Error message misrepresents issue.

### How to Reproduce?

* Create a new client.
* Within the "client details" for that client, go to the "Keys" tab.
* Click the "Import" button.
* 

### Anything else?

I am attempting to use "urn:ietf:params:oauth:client-assertion-type:jwt-bearer" authentication with my own keys, and that has been a nightmare.  Nothing seems to work, and I had to request server and DB access from our IT department to even figure out it was not a configuration issue with the system!

**Comment by EmperorArthur** [comment]
This is the same page referenced by the minor UI task #17762.  The issue is otherwise unrelated to that task.

**Comment by mposolda** [comment]
@EmperorArhur Thanks for the report! It will be nice if you can send the PR with this improvement since you already pointed where the issue is and how the optimal error message can be looked and shown in the UI. As I afraid that we might not be able to prioritize this in the near future...
