### ISSUE TITLE
Class CertificateUtils should support creation of EC certificates

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#31816]
### Description

We require creation of certificates for simple elliptic curve keys. Currently the class `CertificateUtils` is not supporting this because the switch is missing the case for `EC`.

**Comment by mposolda** [comment]
@Captain-P-Goldfish Thanks for the addition. Just a note that `CertificateUtils.generateV3Certificate` is kind of helper method and it can change anytime in future Keycloak upgrades with no guaranteed backwards compatibility (Similarly like you are now breaking a bit backwards compatibility with your PR and replacing `SHA1WithRSAEncryption` with the better alternatives of SHA256).
