### ISSUE TITLE
Ignoring JWK key Missing required field 'use' still happens in keycloak version 25.02

### ISSUE THREAD

**Issue by dongsupkim-onepredict** [keycloak/keycloak#31823]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

The issue reported in #28004 was supposed to be resolved and released in version 25. However, we are still encountering the same problem in version 25.02.

### Version

25.02

### Regression

- [ ] The issue is a regression

### Expected behavior

The JWK key should not be ignored even if the 'use' field is missing.

### Actual behavior

`Ignoring JWK key '***'. Missing required field 'use'. `
makes error

### How to Reproduce?

This issue occurs when connecting via Slack SSO
![스크린샷 2024-08-01 오후 12 19 49](https://github.com/user-attachments/assets/7e8684e7-bd81-4b1e-b2f4-2fc0887351be)

**Comment by justin-tay** [comment]
That issue is with regards to configuring a client in Keycloak with the `private_key_jwt` authentication method which is different from your current issue. This one probably needs a modification to `OIDCIdentityProviderPublicKeyLoader`.

**Comment by dongsupkim-onepredict** [comment]
@justin-tay Is there a way I can fix this by changing the settings?

**Comment by justin-tay** [comment]
No unfortunately I think this will require a fix or you will need to proxy the JWKS url and modify it to add the use.

**Comment by dongsupkim-onepredict** [comment]
@justin-tay Do you have a plan to fix this issue?

**Comment by rmartinc** [comment]
Yep, as @justin-tay this one is more or less the same than #28004 but for brokers instead of clients, I think the `true` is needed [here](https://github.com/keycloak/keycloak/blob/25.0.2/services/src/main/java/org/keycloak/keys/loader/OIDCIdentityProviderPublicKeyLoader.java#L59). This one is one of those issues that the test is more complicated than the fix. @justin-tay if you want to give it a try it would be most than welcomed. :smile:

**Comment by justin-tay** [comment]
@rmartinc I would like to add support for ECDH in Keycloak. If you happen to have the time could you help me review? Would be much appreciated but can understand if it's going to take a while. Thanks!

* https://github.com/keycloak/keycloak/pull/23598
* https://github.com/keycloak/keycloak/pull/23928

**Comment by dongsupkim-onepredict** [comment]
@justin-tay Is this patch planned to be released with version 26, or will it be included as a sub-patch of version 25?
