### ISSUE TITLE
Keycloak is not reading JRE certificates

### ISSUE THREAD

**Issue by PavanKalyan-Gandhapudi** [keycloak/keycloak#31824]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

While configuring Keycloak Identity provider (OIDC) for Azure AD/Entra ID, keycloak doesn't trust the identity provider certificate. But this cacert is present in JRE truststore. I can see keycloak is loading this certificate as i observed in iam.log. Not sure still why keycloak is not trusting the certificate. 
Anyhow i added cacert certificate to keycloak truststore then there is no issue keycloak trusts the certificate. 
Still my question is eventhough this cacert is available in JRE truststore why keycloak not trusting that certificate?
![image](https://github.com/user-attachments/assets/1f47d3b7-6069-40c9-bc04-69016c98a84c)

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should trust the JRE truststore certificates eventhough keycloak have custom truststore.

### Actual behavior

Keycloak is trusting certificates from keycloak truststore only.

### How to Reproduce?

1. Created EntraID application in Azure.
2. In keycloak side, adding endpoint while creating OIDC identity provider. Keycloak is not trusting the microsoft token url.

**Comment by shawkins** [comment]
> Anyhow i added cacert certificate to keycloak truststore then there is no issue keycloak trusts the certificate.

Please clarify how you are configuring a keycloak trustore?

**Comment by sschu** [comment]
Could this be related? https://github.com/keycloak/keycloak/issues/30164

**Comment by PavanKalyan-Gandhapudi** [comment]
> Please clarify how you are configuring a keycloak trustore?
1. We are using _spi-truststore-file-file_ parameter to point to custom truststore.
2. For microsoft identity provider keycloak looking for Microsoft Root CA certificate. But keycloak unable to read the root CA certificate from JRE truststore. I found that if we want to use both custom truststore and JRE truststore then we have to use _--truststore-paths_ parameter and add multiple paths.
3. But here the problem occurs, for our custom truststore it has password. How should we handle this?
4. If we want to use both default JRE truststore and custom truststore by specifying with _truststore-paths_  paths then both has passwords. How should we proceed in this flow?

**Comment by PavanKalyan-Gandhapudi** [comment]
> A workaround could be to import the cacerts certificates into a new truststore file and add your custom certificates there. You can then use a custom password for your new truststore.

1. In this case, i have to use _--spi-truststore-file-file_ parameter right(I can't use `--truststore-paths `parameter)?
2. And you mean to say import all cacerts certificates into new truststore file?

**Comment by shawkins** [comment]
> We are using spi-truststore-file-file parameter to point to custom truststore.

Usage of spi-truststore-file-file does not consult the JRE truststore.

>  I found that if we want to use both custom truststore and JRE truststore then we have to use --truststore-paths parameter and add multiple paths.

You do not need to explicitly list the JRE truststore with --truststore-paths, it is merged into the resulting truststore by default.

> But here the problem occurs, for our custom truststore it has password. How should we handle this?

It is not expected that you'll use a truststore with a password with --truststore-paths. It works best with just pem files, but you can also use password-less stores. This has been talked about in a couple of issues / discussions, including #28007

> If we want to use both default JRE truststore and custom truststore by specifying with truststore-paths paths then both has passwords. How should we proceed in this flow?

The logic will use the JRE truststore password if one is set to extract the certs. Can you use a pem file instead of a password based truststore for your custom certs. Is there a reason why you require a password for public certs?

**Comment by shawkins** [comment]
Closing as not planned as everything is working as expected. We'll convert to a discussion if there are continued comments.
