### ISSUE TITLE
HA Guide missing from Keycloak archives

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#31838]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

It's currently not possible for a user to view an archived version of the Keycloak HA guide.

Keycloak 26 will introduce a significant change to the existing HA guide #31029 which changes the recommended cloud stack significantly. Upon Keycloak 26 release, existing 24/25 users may want to consult the old HA guide to help with maintenance tasks, it should be possible for them to retrieve this via https://www.keycloak.org/archive

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

It should be possible to view archived versions of the HA guide for older Keycloak versions.

### Actual behavior

There's no corresponding entry in the table provided at https://www.keycloak.org/archive/documentation-24.0.html for the HA guide. Several of the links in this table also forward users to the most recent version of their respective documents, not the archived version.

### How to Reproduce?

 Go to https://www.keycloak.org/archive/documentation-24.0.html

**Comment by ahus1** [comment]
The new style of guides doesn't support any versioning, so only the latest version of the docs are presented to the community. So this is out-of-scope until something like #16474 or similar is in place. 

But as this is unlikely to happen for KC26 unless we make this our own priority, we won't be able to do this. Today, this is only something we offer as part of RHBK.
