### ISSUE TITLE
Redirect old HA guide URLs to the new guide

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#31837]
### Description

#31029 introduces significant changes to the HA guide structure, which will result in previously valid URLs returning 404 responses when we release Keycloak 26. To improve the user experience, we should add redirects back to the main multi-site guide for the previously valid URLs.

URLs to redirect:

- https://www.keycloak.org/high-availability/deploy-aws-route53-loadbalancer
- https://www.keycloak.org/high-availability/deploy-aws-route53-failover-lambda
- https://www.keycloak.org/high-availability/operate-failover
- https://www.keycloak.org/high-availability/operate-network-partition-recovery
- https://www.keycloak.org/high-availability/operate-switch-over
- https://www.keycloak.org/high-availability/operate-switch-back

**Comment by ahus1** [comment]
Draft PR available in keycloak-web repository. Will only be merged once KC26 is out. Closing this issue as resolved.
