### ISSUE TITLE
Unlocking temporarily locked user clears all their details

### ISSUE THREAD

**Issue by mruzicka** [keycloak/keycloak#31847]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Clicking the _Temporarily locked_ toggle on the user details page of a temporarily locked user clears all details of the user (_First Name_, _Last Name_, ...) except _Username_.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

the user is enabled and all user details are preserved

### Actual behavior

the user is enabled but all user details (except _Username_ ) are gone

### How to Reproduce?

1. have a temporarily locked user, make sure the user has at least some details defined - a non empty _First Name_ or _Last Name_ for example
2. login to the admin console
3. navigate to _Users_, search for the locked user, open the user's details
4. on the _User details_ page (on the _Details_ tab) click the _Temporarily locked_  toggle (which should be on)
5. reload the page

### Anything else?

When the  _Temporarily locked_ toggle is clicked, the following API request is sent:
* HTTP method:
  `PUT`
* API endpoint:
  `<Keycloak base URL>/admin/realms/<realm ID>/users/<user ID>`
* payload:
  ```json
  {"enabled":true,"attributes":{}}
  ```
This apparently clears the user's details.

**Comment by shawkins** [comment]
Related to #28220

**Comment by ssilvert** [comment]
@mruzicka I'm not seeing this.  Can you check the nightly build?

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by mruzicka** [comment]
@ssilvert, I can confirm the nightly build works fine. It's likely down to the fact that the suspect API request's payload has changed slightly:
```json
{"enabled":true}
```
Closing this.
Thanks!

**Comment by mruzicka** [comment]
@shawkins, @ssilvert, or should I reopen this, given 25.0.2 is affected?

**Comment by ssilvert** [comment]
> @shawkins, @ssilvert, or should I reopen this, given 25.0.2 is affected?

The fix should have been backported to 25.0.x.  No need to reopen.

**Comment by mruzicka** [comment]
OK, thanks.

**Comment by rokf** [comment]
@ssilvert @mruzicka Hi, I'm sorry for bothering you, but the commit (https://github.com/keycloak/keycloak/pull/31203/commits/c6296d3d04cdce36797a3512d3155641b389ffc9) that's supposed to fix this didn't yet go into the `release/25.0` branch - I've just checked.

The changes aren't there.

**Comment by jonkoops** [comment]
Backport for this is pending, see https://github.com/keycloak/keycloak/issues/31165#issuecomment-2353300331

**Comment by ahus1** [comment]
Has been backported to 25.0.6 as part of #31165
