### ISSUE TITLE
Keycloak Operator Installation documentation point to fork of Keycloak

### ISSUE THREAD

**Issue by KenVanGrinsven** [keycloak/keycloak#31861]
### Description

In step 2 under the heading _"Installing by using kubectl without Operator Lifecycle Manager"_ on [this page](https://www.keycloak.org/operator/installation#_installing_by_using_kubectl_without_operator_lifecycle_manager) in the Keycloak documentation, installing the Keycloak Operator points to [this yaml file](https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.2/kubernetes/kubernetes.yml).

I noticed that this file contains a reference to a fork of Keycloak, see the **"/metadata/annotations/app.quarkus.io/vcs-uri"**.

This is not the case for v25.0.1 and earlier versions of the operator, and this feels like this shouldn't be pointing to a fork.

**Comment by shawkins** [comment]
@stianst it is pointing to your fork. Was something different about the 25.0.2 operator release process?

cc @Pepo48 @vmuzikar

**Comment by KenVanGrinsven** [comment]
Additional question: what is the `app.quarkus.io/vcs-uri` used for exactly? Could this be a security issue _if_ malicious code would be present on this fork, or is it just some metadata?

**Comment by shawkins** [comment]
> Additional question: what is the `app.quarkus.io/vcs-uri` used for exactly? Could this be a security issue _if_ malicious code would be present on this fork, or is it just some metadata?

It's just some additional metadata caputured by the quarkus build logic. I'm not aware of any usage.

**Comment by stianst** [comment]
> @stianst it is pointing to your fork. Was something different about the 25.0.2 operator release process?
> 
> cc @Pepo48 @vmuzikar

When doing the release this step failed and I had to do it manually. I thought I did change the URLs, but apparently not properly. Should just be a matter of manually updating the files for the 25.0.2 release

**Comment by vmuzikar** [comment]
Fixed in https://github.com/keycloak/keycloak-k8s-resources/commit/36aaf4b295665a9b6c8a960993e675918229c04e
