### ISSUE TITLE
Add more tests for admin-client

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31869]
After #31867 , we can consider how to add more tests for the admin-client and make them available in keycloak client repository. Some possibilities:

- Re-use directly some admin client tests from the keycloak arquillian testsuite from [this package](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin) . However I am not sure if it is possible to re-use those tests reliably (considering that we don't plan to use arquillian in the keycloak-client testsuite and the arquillian testsuite is anyway going to be migrated soon to the new testsuite in `keycloak` repository, which is currently WiP).

- Copy some admin client tests from the main repository from the [admin package of the testsuite](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin) . Right now, this option seems to be more feasible to me, but not sure... May be investigated. I assume we won't copy whole admin testsuite, but just subset of it just to make sure that most important admin endpoints are covered by the tests in the `keycloak-client` repository.

**Comment by graziang** [comment]
In recent days, I have investigated and started working on this issue by following the second approach of copying the tests from the main repository, This is my branch https://github.com/graziang/keycloak-client/tree/issue-31869.

- To migrate a significant portion of the tests, it is necessary to copy many classes from the Keycloak repository.

- Some tests use the server to perform internal operations, so these need to be modified in some way to be executed in the client side.

- Removed also all the events checks. 

- Some tests do not work on Keycloak 24, for instance the test to check that the master realm cannot be deleted, which was introduced in Keycloak 25.

- So far, I have copied the tests from AdminClientTest and part of RealmTest. The tests that use WebDriver for the OauthClient are still missing. How should we handle these tests?

@mposolda What do you think? Should we continue with this approach?

**Comment by mposolda** [comment]
@graziang Thanks for this investigation! I agree that second approach is likely OK. At least for now.

I've added few comments to your commit here: https://github.com/graziang/keycloak-client/commit/5a83fbdc20fab91b405d8748638a7ffe0bd6f8ef .

Replying to some of your notes:



>    To migrate a significant portion of the tests, it is necessary to copy many classes from the Keycloak repository.

Yeah, I see. But I don't know better way for now... :( Hopefully we can copy just to the testsuite instead of having the classes available directly in the admin-client module. Maybe for some cases, we can do some slight updates to the tests to not require the classes, but that is likely not always possible...

>    Some tests use the server to perform internal operations, so these need to be modified in some way to be executed in the client side.

Yeah, I see. Hopefully most of the admin-client tests can live without direct modifications of the server. Some server modifications can be replaced with the admin-client calls to the server. For some other problematic tests, which really need to modify the server, we can hopefully  not testing them for now (I think it is OK if the tests in the keycloak-client, we test just some subset of the admin-client tests from the main repo). WDYT?

> Removed also all the events checks.

+1. At least for now.

> Some tests do not work on Keycloak 24, for instance the test to check that the master realm cannot be deleted, which was introduced in Keycloak 25.

Yeah, I was thinking that this will be the case. If some tests does not makes sense on the older Keycloak server versions, we can hopefully figure that with the `Assume` checks in particular methods (For example something similar to used here https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/ContainerAssume.java#L27 ) or figure some annotations on the test methods to handle that.

At the same time, sometimes things do not work because of some issues in the admin-client itself. So if we can fix them, it is always better than ignore the tests for 24. For example I saw those in the past:
https://github.com/keycloak/keycloak/issues/32025
https://github.com/keycloak/keycloak/issues/32117

> So far, I have copied the tests from AdminClientTest and part of RealmTest. The tests that use WebDriver for the OauthClient are still missing. How should we handle these tests?

Not yet sure. I was hoping that we can test admin-client without webDriver. It is the workaround, but hopefully OK for now.

For the policy-enforcer tests, I've just replaced the "proper OIDC logins" done here https://github.com/keycloak/keycloak/blob/25.0.4/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/admin/PolicyEnforcerTest.java#L127-L133 with the directGrant logins (OAuth2 resource owner password credentials grant) https://github.com/keycloak/keycloak-client/blob/main/testsuite/authz-tests/src/test/java/org/keycloak/client/testsuite/policyenforcer/PolicyEnforcerTest.java#L119 . Do you think it is sufficient?

If not and we really need webDriver, we will probably need to figure how to do webDriver with the junit5 (maybe the guys working on the new testsuite in keycloak repository already figured it, so we can just copy from them in that case :-) )
