### ISSUE TITLE
Move some documentation to keycloak-client repository

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#31870]
Some section of current Keycloak documentation will be "owned" by keycloak-client repository. This applies to those sections:

-- keycloak-admin-client: Small section here https://www.keycloak.org/docs/25.0.2/server_development/#example-using-java
-- authorization client: https://www.keycloak.org/docs/25.0.2/authorization_services/#_service_client_api
-- policy-enforcer: https://www.keycloak.org/docs/25.0.2/authorization_services/#_enforcer_overview  (With the exception of the section with javascript integration, which should be still in the original place)

Hence will be good to:
- Move those documentations to the `keycloak-client` repository and delete from `keycloak` repository
- Possibly have dedicated section on keycloak webpage and/or add into existing section of "Securing applications" guide https://www.keycloak.org/guides .
- Make sure that keycloak webpage with the documentation is updated during the release of keycloak-client (will require some changes in the release process).

**Comment by rmartinc** [comment]
This issue has three PRs right now:

* https://github.com/keycloak/keycloak-client/pull/28 (keycloak client adding the docs part in client).
* https://github.com/keycloak/keycloak/pull/32187 (PR in keycloak removing the documentation, maybe we need a follow-up to re-add some links after huides for clients are ready).
* https://github.com/keycloak/keycloak-web/pull/482 (keycloak-web, this one needs a release of the keycloak-client with the guides).

**Comment by mposolda** [comment]
Update: This task is done and PRs to [keycloak-client](https://github.com/keycloak/keycloak-client/pull/28) and [keycloak](https://github.com/keycloak/keycloak/pull/32187) were merged.

The remaining is still to merge the PR to keycloak-web: https://github.com/keycloak/keycloak-web/pull/482

There is follow-up created for Keycloak 26.0.1 to fix the links (Cannot be yet done as the keycloak-client documentation does not yet exists online): https://github.com/keycloak/keycloak/issues/32644
