### ISSUE TITLE
Client secret is visable in Admin event representation when Credentials Reset action performed for the Client.

### ISSUE THREAD

**Issue by ravthiru** [keycloak/keycloak#31892]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

After implementing following  https://github.com/keycloak/keycloak/issues/21562 , 
With AdminEvent representation, client secret is masked when client is create and updated. 
In the case where client secret is reset using UI console "Regenerate" button , client secret is still shown as part of representation.

![Screenshot 2024-08-05 at 12 03 44 PM](https://github.com/user-attachments/assets/2c8cd597-6767-4eba-8783-78948d70a941)
@

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Client secret should be masked in the admin event representation when secret is reset using UI console "Regenerate" button .

### Actual behavior

Client secret is shown in the admin event representation.

### How to Reproduce?

1. For realm, Realm settings / Events ,  Enable Save events including representation
2.  Now Create Client with Client authentication enabled
3.  Try reseting client credentials using "Regenerate" button under credentials
4. Go to admin events  and you can see client secret under representation

**Comment by kaustubh-rh** [comment]
Hi @mposolda , can I raise a PR for the same ?
