### ISSUE TITLE
Outdated Latest Documentation

### ISSUE THREAD

**Issue by statist32** [keycloak/keycloak#31901]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The latest section shows version 24 instead of 25 [https://www.keycloak.org/docs-api/latest/javadocs/index.html](https://www.keycloak.org/docs-api/latest/javadocs/index.html)

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

If I visit the website I expect the newest version of the documentation

### Actual behavior

At least the title states version number 24.x instead of the 25.x one.

### How to Reproduce?

Visit the provided link

**Comment by mposolda** [comment]
@pskopek Assigning to you in case you have any idea why the API documentation is not up-to-date?
