### ISSUE TITLE
ReponseBuilder is unused

### ISSUE THREAD

**Issue by statist32** [keycloak/keycloak#31928]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The `DefaultCors` `build` method takes an `ResponseBuilder` object as an argument. 
This `ResponseBuilder` is never used and I assume that this is a bug and should be used in the `add` method, such that the cors header are integrated into the response. 

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The private `ResponseBuilder` should be used in the class implementation or be markes as a NOOP.

### Actual behavior

The `ResponseBuilder` is not used except from the assignment.

### How to Reproduce?

Can be observed when looking at the [code](https://github.com/keycloak/keycloak/blob/d85fa0982392d850486c95f23bf8322c8b8e65e8/services/src/main/java/org/keycloak/services/cors/DefaultCors.java#L39)

**Comment by martin-kanis** [comment]
This default cors builder seems to be never used in our code therefore I'm marking this issue as a low priority.
