### ISSUE TITLE
Upgrade to next Quarkus LTS

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#31932]
### Description

Keycloak 26 will use a new Quarkus LTS which is [currently assumed to be 3.15](https://github.com/quarkusio/quarkus/wiki/Release-Planning).

**Comment by ahrycej** [comment]
Is there any rough estimate on availability of 26.0.0? Will it happen before November 2024 or rather next year?
thank you!
asking due to this ticket : 
https://github.com/keycloak/keycloak/issues/31896

**Comment by vmuzikar** [comment]
@ahrycej Current estimate is that 26.0 should be released around September.
