### ISSUE TITLE
Account Console not working after upgrade

### ISSUE THREAD

**Issue by karthikappy** [keycloak/keycloak#31946]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The account console page at ```https://<server>/realms/<realm>/account``` does not load correctly. It displays a white screen with a loading spinner.

This is a fresh upgrade of Keycloak upgraded from 23.0.4 to 25.0.2 (the latest version at this time)
The account console worked in the previous version

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Visiting the page at ```https://<server>/realms/<realm>/account``` should allow the currently logged in user to manage their account.

### Actual behavior

Visiting the page displays a white screen with a loading spinner on the top left.
Developer Tools in Google Chrome displays:
```GET https://<server>/realms/<realm>/protocol/openid-connect/login-status-iframe.html/init?client_id=account-console&origin=https%3A%2F%2F<server> net::ERR_ABORTED 403 (Forbidden)```

### How to Reproduce?

OPTION 1:
- Login to the admin console
- Select Manage > Users from the left sidebar
- Click on an existing user
- From the action menu on the top-right select "impersonate user"

OPTION 2:
- Visit the page at ```https://<server>/realms/<realm>/account```

### Anything else?

- I am using the default keycloak distribution (powered by Quarkus)
- The keycloak server is running behind a reverse proxy using ```proxy-headers=forwarded``` (this used to be ```proxy=edge```)

**Comment by shawkins** [comment]
> The keycloak server is running behind a reverse proxy using proxy-headers=forwarded (this used to be proxy=edge)

Can you provide the full hostname configuration and hostname debug output from the 23 and 25 installs?

**Comment by shawkins** [comment]
Also seems similar to #31640

**Comment by karthikappy** [comment]
Here are config files and logs
# 23 keycloak.conf
```
proxy=edge
hostname-url=https://kc-fqcdn/auth/
hostname-admin-url=https://kc-fqcdn/auth/
hostname-path=auth/
```
# 25 keycloak.conf
```
proxy-headers=forwarded
hostname=https://kc-fqcdn/auth/
```
# Apache httpd.conf
```
ProxyPass /auth/ http://localhost:kc-port/
ProxyPassReverse /auth/ http://localhost:kc-port/
```
# Apache Access log (v25)
Here are the relevant entries from my access log
```

128.235.90.109 - - [06/Aug/2024:10:54:49 -0400] "GET /auth/resources/itsrc/account/en HTTP/1.1" 200 33301
128.235.90.109 - - [06/Aug/2024:10:54:49 -0400] "GET /auth/resources/iszq9/account/keycloak.v3/favicon.svg HTTP/1.1" 200 6718
128.235.90.109 - - [06/Aug/2024:10:54:49 -0400] "GET /auth/realms/myrealm/protocol/openid-connect/3p-cookies/step1.html HTTP/1.1" 200 2318
128.235.90.109 - - [06/Aug/2024:10:54:49 -0400] "GET /auth/realms/myrealm/protocol/openid-connect/3p-cookies/step2.html HTTP/1.1" 200 686
128.235.90.109 - - [06/Aug/2024:10:54:49 -0400] "GET /auth/realms/myrealm/protocol/openid-connect/login-status-iframe.html HTTP/1.1" 200 4330
128.235.90.109 - - [06/Aug/2024:10:54:49 -0400] "GET /auth/realms/myrealm/protocol/openid-connect/login-status-iframe.html/init?client_id=account-console&origin=https%3A%2F%2Ftransprod10.njit.edu HTTP/1.1" 403 -
```

**Comment by shawkins** [comment]
Just to confirm, your proxy is running on the default ports correct? 

Based upon your configuration of a full hostname url, the proxy-headers are effectively ignored. Are there any values that you need picked up from the headers?

**Comment by karthikappy** [comment]
The proxy (Apache web server) is running on the default ports.

I don't think I need to pick up any values from the headers.

**Comment by shawkins** [comment]
@karthikappy the forbidden response should be coming from here https://github.com/keycloak/keycloak/blob/cf8905efe87276a672dabea249bdd797c6243e9d/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java#L70 - which means that origin=https%3A%2F%2Ftransprod10.njit.edu is not allowed. Is transprod10.njit.edu the kc-fqcdn?

**Comment by karthikappy** [comment]
Yes, that is the kc-fqcdn

**Comment by shawkins** [comment]
@karthikappy I tried to reproduce this using nginx, but it worked as expected. The only way I could reproduce similar behavior is to set an invalid Forwarded header, such as host=https://kc-fqcdn - without the port. At that point the origin check will fail because the parsing logic expects both the host and the port and will create a mangled host.

If this is indeed the case for you, you should either correct how the Forwarded header is being set, or remove the usage of the proxy-headers=forwarded option (since you are using the full hostname url and don't need the values from the headers). If you can confirm that the Forwarded header is indeed the issue, then we can probably resolve this with additional documentation - and possibly a debug log in the LoginStatusIframeEndpoint to make it clear why the request was forbidden.

cc @vmuzikar

**Comment by 0314R** [comment]
@karthikappy Have you managed to find the cause or a solution by now? We are having the exact same problem at the moment.

**Comment by karthikappy** [comment]
@0314R Setting the origin parameter to "*" as described in https://github.com/keycloak/keycloak/issues/33109 resolved the issue for me ... but I'm unsure about the security implications of such a change ...
