### ISSUE TITLE
Update HA guide performance numbers to reflect the latest architecture

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#31940]
### Description

The reference architecture and performance numbers in concepts-memory-and-cpu-sizing.adoc needs to be updated to reflect the new multi-site architecture.

**Comment by mhajas** [comment]
Here are some facts we need to reflect:
- Persistent sessions are enabled by default
- Sessions are no longer stored/cached in Keycloak and Infinispan

**Comment by ahus1** [comment]
I've accidentially created a new issue which already has a PR. Closing this one as a duplicate.
