### ISSUE TITLE
Admin console not usable when instance has a 1000 realms

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak#31956]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When trying to access the admin UI, the endpoint to retrieve all realms is called: `/admin/realms/master/ui-ext/realms/names` which loads all realms from DB (one at a time) then checks if the user can access them (again loading from DB one at a time) which again loads the client of the realm (one at a time) to check if the user has the required role to manage/view the realm. Doing this a 1000 times take more than 60 seconds causing the TransactionReaper to intervene an close the connection.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Be able to use the Admin GUI

### Actual behavior

Unable to list Realms

### How to Reproduce?

Create a 1000 realms and open the admin console.

**Comment by ssilvert** [comment]
@yelhouti This should be fixed in Keycloak 26 under https://github.com/keycloak/keycloak/issues/29978

Please check out the nightly build to test:
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by yelhouti** [comment]
@ssilvert This only reduces the computation by half. As explained before half of the time is spent  on retrieving all realms.
```
query.getResultStream().map(session.realms()::getRealm).filter(Objects::nonNull)
```
getRealm is very expensive. 

There are two ways to fix this:
1. make getRealm less expensive
2. make getRealmsStream() take a string param to search by name.
Change getAllRealmIds in this code and use something like getAllRealmIdsAndNames and filter on that before calling getRealm
```
@Override
    public Stream<RealmModel> getRealmsStream() {
        TypedQuery<String> query = em.createNamedQuery("getAllRealmIds", String.class);
        return getRealms(query);
    }
```

**Comment by ssilvert** [comment]
Looks like this one needs to be looked at by core-iam team.

**Comment by pedroigor** [comment]
@yelhouti Thanks for the issue. It is a known issue and Keycloak does not support a large number of realms. We have several open issues and discussions  around this topic. One of the last ones is https://github.com/keycloak/keycloak/discussions/11074.

However, we are about to introduce the Keycloak Organizations Feature which will help to address B2B and multi-tenancy use cases. The feature is under development and the first release of it, narrowed to the core capabilities, is targeted to  Keycloak 26. For more details, please see https://github.com/keycloak/keycloak/issues/30180.

**Comment by yelhouti** [comment]
@pedroigor while I understand that keycloak project has limited bandwidth and cannot focus on all issues at once. I would like to point the following:
1. It is not always possible to group multiple realms into one in a transparent way to the end user (users with same login on different realms...). Maybe the constraint should be updated to prevent the same username in the same organisation, this also doesn't seem to go along the road-map of allowing shared login between multiple organisations.
2. The solution I proposed would allow apps that have been using realms for multi-tenancy to keep using then without a problem. This specially true, when there is no clear migration path for all of us.
3. The current login flow for organisations doesn't facilitate the migration, specifically since roles per organization are not et implemented. Plus, I feels that moving all the roles I have now per realm to organization roles while just make the problem worse, as checking if a user has a specific role would require recursively loading all roles for all tenants (now organization, previously realms) and doing recursive computation on them.

The fact that realms offer today full separation with little risk of bad configuration and cross login is a major asset that should not be dropped in favor of organisation. 

Would it be ok for you, If I implement a fix that improves the performance for multiple realms ?

**Comment by ahus1** [comment]
Re-opening as a community PR has been opened.

**Comment by sguilhen** [comment]
Assigning myself to ensure the linked PR is reviewed/merged

**Comment by yelhouti** [comment]
@pedroigor Thanks for taking the time to responde.

I totally agree with your point that organisations will offer new possibilities and I am all here for it.

I am hoping to have tens of thousands of realms if all goes well, and If it starts to misbehave I will try to catch to understand where the next bottleneck is and remove it.

I am also glad to see that small PRs that fix specific performance bottlenecks are easy to have merged so I will do my best to help whenever I encounter one.

It might be a good time reopen the benchmark issue, I am pretty sure It have a much better performance now, which will keep improving like you mentioned when other improvements like the one for identity mappers... are added.

I ma following closely https://github.com/keycloak/keycloak/discussions/11074 and if it become a priority for our business, I will pick the relevant parts and create small PRs for them.

Thanks again for the great project and good luck.

I didn't not answer all your point as to not waste your time for stuff not urgent for now,
