### ISSUE TITLE
Duplicate Key error for Kerberos user attribute

### ISSUE THREAD

**Issue by sebastianBoehringer** [keycloak/keycloak#31957]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After upgrading from Keycloak 23.0.7 to 25.0.1 we get exceptions for users in the console and cannot access their detail page. Not all users are affected only those that are federated via Microsoft AD where Kerberos authentication is also enabled.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

I can look at the user details of a user federated via LDAP with Kerberos enabled

### Actual behavior

The request made fails with the following stacktrace. The console displays an error message making it impossible to e.g. impersonate affected users.

`
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]: 2024-08-07 06:59:08,538 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-6706) Uncaught server error: java.lang.IllegalStateException: Duplicate key KERBEROS_PRINCIPAL (attempted merging values org.keycloak.userprofile.AttributeMetadata@8ddf702a and org.keycloak.userprofile.AttributeMetadata@8ddf702a)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.userprofile.DefaultAttributes.getUserStorageProviderMetadata(DefaultAttributes.java:347)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.userprofile.DefaultAttributes.configureMetadata(DefaultAttributes.java:324)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.userprofile.DefaultAttributes.<init>(DefaultAttributes.java:90)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.userprofile.DeclarativeUserProfileProvider.createAttributes(DeclarativeUserProfileProvider.java:111)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.userprofile.DeclarativeUserProfileProvider.createUserProfile(DeclarativeUserProfileProvider.java:138)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.userprofile.DeclarativeUserProfileProvider.create(DeclarativeUserProfileProvider.java:116)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.services.resources.admin.UserResource.getUser(UserResource.java:328)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.keycloak.services.resources.admin.UserResource$quarkusrestinvoker$getUser_7e789726117d7cfd3ef1d9ddd01596d8e6add5b0.invoke(Unknown Source)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Aug 07 06:59:08 keycloak.my-domain.de keycloak[929]:         at java.base/java.lang.Thread.run(Thread.java:840)
`

### How to Reproduce?

Try to access the user details of a user that is federated via AD and has kerberos enabled

**Comment by pedroigor** [comment]
We have a similar setup in our test suite but using ApacheDS. I'm trying to understand how the `KERBEROS_PRINCIPAL` key is duplicated if the attribute should come from the provider linked with the user. It should be a single one.

Can you please provide:

* The `Federation link` for the user you get the error. I would like to know to which provider the user is linked to
* The configuration of your LDAP provider with Kerberos enabled

Other than that, we can probably fix the issue by ignoring duplicated. But ideally we should understand why it is happening in the first place.

**Comment by pedroigor** [comment]
It might be related to https://github.com/keycloak/keycloak/issues/30476. The fix to this issue makes sure the metadata cached does not change. In your case, it might happen that metadata for a specific attribute is added twice because the `KERBEROS_PRINCIPAL` attribute was previous added.

Can you check nightly to see if the issue still persists?

**Comment by sebastianBoehringer** [comment]
Thanks for taking the time. After reexamining the configuration for the affected user federation I found a mapper that was writing KERBEROS_PRINCIPAL. After removing said mapper I can view the profile of the linked users again. I might have created (and forgotten) that mapper after our kerberos integration stopped working at one point.

Anyhow thank you again. I'll close this issue
