### ISSUE TITLE
Customized storge provider password validation

### ISSUE THREAD

**Issue by Theoshen** [keycloak/keycloak#31976]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have implemented a customized UserStorageProvider and the isValid() method from the CredentialInputValidator interface, but I encountered a situation that made me wonder.

I have a user stored in our federation database, whose old credential too.
![微信截图_20240807193550](https://github.com/user-attachments/assets/e9e83e5e-bcd6-4e7a-bdfb-982a4a7ac4c3)

In our business flow, this user's new credential will migrate into Keycloak. 
![image](https://github.com/user-attachments/assets/856e151c-7278-4102-a6ca-6bc0fe3e9a5f)

In our flow, this user may be inactive, and then this user cannot log in, however, in this situation, I use the correct credential, and it's still logging in.

I debugged the login flow, it seems like the isValid() method which is ineffective. I even tried to force the isValid() method to return false.
```
@Override
    public boolean isValid(RealmModel realm, UserModel user, CredentialInput credentialInput) {
       return false;
    }
```
But the same case for a user whose password has not yet been migrated to Keycloak does not encounter this error behaviour.

So I'm confused as to how this works and I'm hoping someone can help me out with this.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The user cannot log in when isValid() returns false

### Actual behavior

The user can log in when isValid() returns false

### How to Reproduce?

Mock a user stored in the federation database, and then set a keycloak password for him.
Use this user login, and in the code, force the isValid() method returns false.

**Comment by rmartinc** [comment]
Can you please attach the mock project to review?
