### ISSUE TITLE
Docs: api_documentation:Admin Rest API:get group members

### ISSUE THREAD

**Issue by gattobriz** [keycloak/keycloak#32012]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

The documentation for query parameter ```max ``` of ```GET /admin/realms/{realm}/groups/{group-id}/members``` API seems to be incomplete. I checked the latest documentation found under https://www.keycloak.org/docs-api/latest/rest-api/index.html#_groups,but it's not mentioned how to disable the maximum result size to get all members of the group. This is done by setting ```max=-1```.  I hope this is a feature and not a bug, because in my application I want to download all members of a group without pagination.
 
In our project we prefer to use documented interfaces and if this is a feature, please add it to the documentation.
Thanks Gerald

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

GET /admin/realms/{realm}/groups/{group-id}/members
Query Parameters

|Name|Description|Default|Pattern|
|--|----|----|-----|
|max (optional) | Maximum results size; set to -1 to return all members|100||

### Actual behavior

|Name|Description|Default|Pattern|
|--|----|----|-----|
|max (optional) | Maximum results size (defaults to 100)|null||

### How to Reproduce?

Go to https://www.keycloak.org/docs-api/latest/rest-api/index.html#_groups and scroll down to

GET /admin/realms/{realm}/groups/{group-id}/members

**Comment by martin-kanis** [comment]
@gattobriz You are right, a this could be improved on multiple places.

**Comment by martin-kanis** [comment]
@Ashleycodesseo sure, that would be great. Feel free to open a PR and ask questions if needed. Thanks!

**Comment by Ashleycodesseo** [comment]
@martin-kanis you got it. Once I get started I will update you. Thanks alot
