### ISSUE TITLE
SAML Responses with error="invalid_signature"

### ISSUE THREAD

**Issue by krishnakekan619** [keycloak/keycloak#32013]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

Keycloak generates SAML responses with invalid signatures. 

### Version

quay.io/keycloak/keycloak:25.0

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak should generate SAML responses with valid signatures.

### Actual behavior

Keycloak generates SAML responses with invalid signatures

### How to Reproduce?

I wanted to integrate keycloak IDP with gitlab-CE (V17.2.0)
1. you can install gitlab on ubuntu VM by following below URL: https://about.gitlab.com/install/

2. To install and Start Keycloak

$ docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0 start #add certs to run in prod mode or either use below compose file

---
#version: '3.8'
services:
  mykeycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    ports:
      - 8443:8443
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HEALTH_ENABLED=true
      - KC_LOG_LEVEL=info
    volumes:
      - /home/keycloak/kc.crt:/opt/keycloak/conf/server.crt.pem
      - /home/keycloak/kc.crt.key:/opt/keycloak/conf/server.key.pem
      - /home/keycloak/kcCA.pem:/opt/keycloak/conf/rootCA.pem
      - keycloak_data:/opt/keycloak/standalone/data
    command:
      - start
      - --db=postgres
      - --features=token-exchange
      - --db-url=jdbc:postgresql://keycloak-postgres:5432/keycloak_db
      - --db-username=keycloak_user
      - --db-password=password
      - --https-certificate-file=/opt/keycloak/conf/server.crt.pem
      - --https-certificate-key-file=/opt/keycloak/conf/server.key.pem
      - --hostname=sso.kc.local
      - --verbose
    depends_on:
      - keycloak-postgres
      
 ----
3. configure keycloak client
 Visit https://sso.kc.local:8443/

Sign into the Administration Console with admin/admin.

Create Realm: myrealm.

Create user & credentials: Users > Add user / Credentials > Set password (Set Temporary to off).

Create SAML client: Clients > Create client

Client type: SAML
Client ID: repo.kc.local
Valid redirect URIs: https://repo.kc.local/users/auth/saml/callback

4. edit /etc/gitlab/gitlab.rb file
---

#SAML 2.0#######
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
gitlab_rails['omniauth_block_auto_created_users'] = false
gitlab_rails['omniauth_auto_link_saml_user'] = true
gitlab_rails['omniauth_providers'] = [
  {
    name: "saml",
    label: "SAML Keycloak", # optional label for login button, defaults to "Saml"
    groups_attribute: 'Role',
    external_groups: ['repo.kc.local:external'],
    required_groups: ['developer', 'freelancer', 'admin', 'auditor'],
    args: {
      assertion_consumer_service_url: "https://repo.kc.local/users/auth/saml/callback",
      idp_sso_target_url: "https://sso.kc.local:8443/realms/myrealm/protocol/saml",
      idp_cert: "-----BEGIN CERTIFICATE-----\n<certificate>\n-----END CERTIFICATE-----\n", 
      idp_cert_fingerprint: "43:51:43:a1:b5:fc:8b:b7:0a:3a:a9:b1:0f:66:73:a8", #either one of the thing we can use here
      issuer: "repo.kc.local",
      attribute_statements: {
        first_name: ['first_name'],
        last_name: ['last_name'],
        name: ['name'],
        username: ['name'],
        email: ['email'] },
      name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
    }
  }
]

I am using self signed certs for installing gitlab and keycloak 
everything is smoothly working as expected with other applications and i face issue only with keycloak and gitlab

### Anything else?

I am using self signed certs for installing gitlab and keycloak 
everything is smoothly working as expected with other applications and i face issue only with keycloak and gitlab

error is as below:
2024-08-08 11:33:38,592 ERROR [org.keycloak.protocol.saml.SamlService] (executor-thread-84) request validation failed: org.keycloak.common.VerificationException: SigAlg was null
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:154)
        at org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:144)
        at org.keycloak.protocol.saml.SamlService$RedirectBindingProtocol.verifySignature(SamlService.java:836)
        at org.keycloak.protocol.saml.SamlService$BindingProtocol.handleSamlRequest(SamlService.java:314)
        at org.keycloak.protocol.saml.SamlService$BindingProtocol.execute(SamlService.java:720)
        at org.keycloak.protocol.saml.SamlService.redirectBinding(SamlService.java:888)
        at org.keycloak.protocol.saml.SamlService$quarkusrestinvoker$redirectBinding_f029009a8f864880d0a24aa96e434ce2f5c9e801.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-08-08 11:33:38,595 WARN  [org.keycloak.events] (executor-thread-84) type="LOGIN_ERROR", realmId="xx-xx-xx-xx-xx", realmName="myrealm", clientId="null", userId="null", ipAddress="xx.xx.xx.xx", error="invalid_signature"

assistance on this issue much appreciated 
@rmartinc @abbra @wuwx @eppsilon @AlekSi @stianst @patriot1burk

**Comment by rmartinc** [comment]
@krishnakekan619 It seems that the request generated by gitlab is not passing the `SigAlg` parameter. In SAML when the REDIRECT binding is used the signature is placed out of the SAML document in some query parameters (`sigAlg` and `Signature`). Those are specified in the [saml bindings spec](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) in the chapter 3.4.4.1 DEFLATE Encoding.

So it seems that gitlab is not signing the request. You have to remove the `Client signature required` in the client `keys` tab or configure gitlab to sign the request correctly (and I have no idea about how to do that). Check also if gitlab is placing the signatures inside the SAML document (I saw this issue several times) which would be a bug in gitlab (in this case you should try to use POST binding in gitlab).

**Comment by krishnakekan619** [comment]
As expected @rmartinc, Thanks for looking into this!
Based on my knowledge, I have attempted the following configurations:

In the gitlab.rb file:

name_identifier_format: urn:oasis:names:tc:SAML:2.0:bindings:URL-Encoding:DEFLATE
On the Keycloak side:

IDP-Initiated SSO URL Name: https://repo.kc.local
Assertion Consumer Service POST Binding URL: https://repo.kc.local
Could you please guide me on where I should make changes or if there are any other areas I need to check?

error is still the same

**Comment by rmartinc** [comment]
@krishnakekan619 I personally have no idea how to configure gitlab with SAML (I have never done that). But if the problem is the `SigAlg` parameter is not sent in the request, the client is simply not signing the requests. So you have two different options:

1. Configure keycloak to accept non-signed request for the client. For that you need to configure the option `Client signature required` to OFF in the client `Keys` tab.
2. Configure gitlab to send the authn request signed. That should be done in gitlab and please ask to the proper forum, not here (this is keycloak issues, code issues in the keycloak repository).

I would try 1 first (just to test) and then I would try to do 2. Reading a bit the gitlab documentation, in order to sign the request you need to configure a certificate and private key as explained [here](https://docs.gitlab.com/ee/integration/saml.html#sign-saml-authentication-requests-optional). The same certificate you have to configure in keycloak in the commented keys tab. But, as I commented, I have never configured gitlab with SAML so maybe I'm not pointing to the proper documentation, so ask in the gitlab forums.
