### ISSUE TITLE
`My password` string in `Signing in` page not getting translated in `keycloak.v3 account` theme

### ISSUE THREAD

**Issue by ArunjithPK** [keycloak/keycloak#32016]
### Before reporting an issue

- [ ] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

`My password` string in `Signing in` page not getting translated to other languages. 

I update account UI language(locale) as Portuguese
add added in `messages_pt_BR.properties` file as  `password=Minha senha` but not reflecting in Account UI.  

<img width="737" alt="keycloak" src="https://github.com/user-attachments/assets/d5ea2ee7-5c92-45a9-b53c-54dd7aa72128">

This issue I faced in all languages.

### Version

v25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Need to convert selected language.

### Actual behavior

Not converting selected language.

### How to Reproduce?

Change `Select a locale` other than English
go to Signing in page and check `Basic authentication` lists

**Comment by kaustubh-rh** [comment]
Raising a PR for the same
