### ISSUE TITLE
Keycloak - Administration Console is not working

### ISSUE THREAD

**Issue by AyeTinHla** [keycloak/keycloak#32024]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Administration Console is not working in Keycloak url. https://hq-ydnec-ap01:8443/auth/
In Keycloak url, https://hq-ydnec-ap01:8443/auth/, click on Administration Console , only the "Loading the Admin UI" message is displayed with loading image.

### Version

Keycloak 25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Browse Keycloak url, https://hq-ydnec-ap01:8443/auth/, click on Administration Console menu on home page, Keycloak administration page will display properly.

### Actual behavior

In Keycloak url, https://hq-ydnec-ap01:8443/auth/, click on Administration Console, only the "Loading the Admin UI" message is displayed with loading image.
![KeyCloak](https://github.com/user-attachments/assets/ec23f08b-aec1-48b6-95ef-8cb47b736e09)

### How to Reproduce?

browse "https://hq-ydnec-ap01:8443/auth/" url, click on Administration Console menu on home page.

### Anything else?

This issue is already opened in Quorum Software service desk page.
![KeyCloak](https://github.com/user-attachments/assets/13fc2f1c-e128-4447-84d0-f2a9e9aea0d1)

**Comment by sschu** [comment]
This is most likely not a bug in Keycloak but lack of correct configuration. Please check out the configuration guide to set things up properly (e.g. https://www.keycloak.org/server/hostname).
