### ISSUE TITLE
fetch user by ui-ext/brute-force-user endpoint in admin-console is very slow 

### ISSUE THREAD

**Issue by amiramirifar2** [keycloak/keycloak#32041]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

I have created a realm with following specs:
- 5000 nested group with 3 level
- 20000 users (each user has only one group)
- activate (view, view-members, manage-membership, manage-member) for each group
- define 100 policy that assign those policy to groups

when I go to users page in admin console it take more than 20s to get response from the  ui-ext/brute-force-user endpoint

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

response  ui-ext/brute-force-user endpoint in proper duration (less than 1s)

### Actual behavior

for user which can see limited number of group and user base on defined policies it take more than 20s to get response from the  ui-ext/brute-force-user endpoint

### How to Reproduce?

1. create user1 as a middle admin of group1 with 
2. define user base policy  as a middle-admin-of-group-1 and select user1 for this policy
3. assign defined policy  to view, view-members, manage-membership, manage-member permissions for group1 and all its subgroups 
4. login as a user1 and go to users in admin console

### Anything else?

I have checked your source code and noticed that last commit for the [BruteForceUsersResource.java](https://github.com/keycloak/keycloak/blob/main/rest/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java) file is for last year

**Comment by ahus1** [comment]
This seems to be a duplicate if #31519. Please join that discussion to confirm that the fix provided in Keycloak's nightly build.

**Comment by ahus1** [comment]
You confirmed in the other issue that this still happens in the nightly build, and even after the fixes for #31519 are present. 

For the setup you describe with the groups, users and policies: Can you please provide a scripted setup for those, so we can reproduce it locally? 

Keycloak ships with a default of 10000 entries in the `realms` cache which is also used for groups and other entries of the realm. As an intermediate measure, I'd recommend to increase this to 100000 entries. For that, copy the `cache-ispn.xml` to a new file, edit it, and pass the configuration file via the `cache-config-file` option. Even if the first call might be slow, the second call should be faster. With Keycloak 25, there is also a simpler way to get cache metrics enabled than in KC23 - those metrics will give you information how many entries are in the cache.

Best,
Alexander
