### ISSUE TITLE
OIDC Form Post Response Inline Script

### ISSUE THREAD

**Issue by jamesshuriff** [keycloak/keycloak#32055]
### Description

The OIDC Form Post Response contains an inline script that's used to submit the form.

`builder.append("  <BODY Onload=\"document.forms[0].submit()\">");`

I am proposing to move this into a dedicated endpoint, like so:

`builder.append("    <script src=\"" + HtmlUtils.escapeAttribute(params.get("iss")) + "/protocol/openid-connect/redirect.js\" defer></script>");`

I am preparing a PR to accomplish this.

### Discussion

https://github.com/keycloak/keycloak/discussions/32054

### Motivation

Requiring inline scripts for OIDC functionality prevents the defining of strong Content Security Policies.

**Comment by jonkoops** [comment]
Closing this for the reasons mentioned under https://github.com/keycloak/keycloak/pull/32057#issuecomment-2284341128
