### ISSUE TITLE
JS adapter cannot pass client_secret parameter when request token

### ISSUE THREAD

**Issue by cn2156** [keycloak/keycloak#32064]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Use JavaScript adapter in /js/libs/keycloak-js, with initial Keycloak：
```
const keycloak = Keycloak({
    url: 'https://my_kc_server_url',
    realm: 'test',
    clientId: 'test',
    redirectUri: 'http://localhost/',
    credentials: {
        secret: 'my_secret'
    }
})
```

then use `const auth = await keycloak.init({onLoad: 'login-required'})`

after login success, redirect to the redirect url,  run `const auth = await keycloak.init({onLoad: 'login-required'})`, will request https://my_kc_server_url/realm/test/protocol/openid-connect/token, the request payload not pass client_secret parameter.

to fix the issue: in keycloak.js line 786, processCallback function, add:
```
if (config.credenticals && config.credenticals.secret) {
    params += '&client_secret=' + config.credenticals.secret
}
```

### Version

25.02

### Regression

- [ ] The issue is a regression

### Expected behavior

request token api, must pass client_secret parameter when setted in initial

### Actual behavior

not pass client_secret parameter when setting in initial

### How to Reproduce?

1. initial keycloak
```
const keycloak = Keycloak({
    url: 'https://my_kc_server_url',
    realm: 'test',
    clientId: 'test',
    redirectUri: 'http://localhost/',
    credentials: {
        secret: 'my_secret'
    }
})


async function load(
    const auth = await keycloak.init({onLoad: 'login-required'})
}

load()
```

2. run, login keycloak

3. redirect to redirectUri,will request token api, the 401 error occured with not pass client_secret parameter.

**Comment by cn2156** [comment]
the version is 25.0.2

**Comment by mposolda** [comment]
Thanks for the report. This is low priority IMO as javascript clients are usually public clients and using client-secret on them is quite uncommon. In case you needed, feel free to send PR for this.

**Comment by jonkoops** [comment]
We explicitly removed support for passing in a client secret to Keycloak JS in the past, as it is not possibly to securely store secrets on the client-side. You should use a public client instead.
