### ISSUE TITLE
Remove keycloak-admin-client-jee

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#32099]
It was decision to remove keycloak-admin-client-jee. This task is to remove it from both `keycloak` and `keycloak-client` repository.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak/issues/32181
- [ ] https://github.com/keycloak/keycloak-client/issues/27
```

**Comment by rmartinc** [comment]
I'm closing this as completed once the two related tasks are merged.
