### ISSUE TITLE
Reset Credentials - "Chooser User" selecting null user and returning invalid user or password

### ISSUE THREAD

**Issue by rntjr** [keycloak/keycloak#32103]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When creating a conditional within Reset Credentials with Chooser User, if the user does not exist, it is returning an invalid user or password.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

We expect that if the user doesn't exist, it won't meet the condition (just like an existing user created manually) and would execute the email.

### Actual behavior

When Chooser User can't find the user, it doesn't answer the conditional and doesn't execute the send email either.

### How to Reproduce?

The user attribute condition is shown in the image below.
![image](https://github.com/user-attachments/assets/e368b16f-bfd7-400e-80f1-3c2159085375)
![image](https://github.com/user-attachments/assets/6fdbd926-f456-4cae-92c8-0987321c68db)

**Comment by rntjr** [comment]
I understand the lack of security regarding access denied to some users. But we're having problems with federated users changing their password via Forgot Password, diverging from Active Directory.

**Comment by rmartinc** [comment]
@rntjr I don't understand what you mean with "We expect that if the user doesn't exist...", I suppose you mean if the attribute doesn't exist (not the user).

But, in general, I don't think the `federationLink` can be used as an attribute, it's an internal property (like enabled which is not retrieved as an attribute). So the the condition is always going to fail. If it's an AD attribute ldap users should have the special LDAP_ENTRY_DN (dn) or LDAP_ID (uuid) attributes. So try with the following configuration for the condition:

Attribute name: LDAP_ENTRY_DN (or LDAP_ID)
Expected attribute value: .* (anything)
Include group attributes: OFF
Negate output: OFF
regex: ON

This will deny to any user that has the attribute LDAP_ENTRY_DN in it with any value (so it's an LDAP user). I tested it with 25.0.2 and it works for me. You can also create a JS (or Java) step if you want something fancier.

**Comment by rntjr** [comment]
In fact, it works for users who are registered in keycloak, but for users who are not registered (users who do not exist in the database), it is returning “Invalid user or password”.

If you run the test with a user with these attributes, it will return “Deny” according to the flow. If you test a user without these attributes, it will send the email normally. But if you test a user who doesn't exist in the database, it will return an “Invalid user or password”. What I want is for it to return the message that the email was sent successfully, but it's not doing that.
