### ISSUE TITLE
Offline session bug on 25.0.2

### ISSUE THREAD

**Issue by truediogo** [keycloak/keycloak#32127]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

There's a problem in "version" column of above entities, that results in error when user tries to login in a offline session.

**- PersistentUserSessionEntity.java**
https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentUserSessionEntity.java

**- PersistentClientSessionEntity.java**
https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/session/PersistentClientSessionEntity.java

Keycloak tries to query version in lowercase, but in database the version column is UPPERCASE

```
select top ? puse1_0.OFFLINE_FLAG,puse1_0.USER_SESSION_ID,puse1_0.BROKER_SESSION_ID,puse1_0.CREATED_ON,puse1_0.DATA,puse1_0.LAST_SESSION_REFRESH,puse1_0.REALM_ID,puse1_0.USER_ID,puse1_0.version from OFFLINE_USER_SESSION puse1_0 where puse1_0.OFFLINE_FLAG=? and puse1_0.USER_SESSION_ID=? and puse1_0.REALM_ID=?

select pcse1_0.CLIENT_ID,pcse1_0.CLIENT_STORAGE_PROVIDER,pcse1_0.EXTERNAL_CLIENT_ID,pcse1_0.OFFLINE_FLAG,pcse1_0.USER_SESSION_ID,pcse1_0.DATA,pcse1_0.TIMESTAMP,pcse1_0.version from OFFLINE_CLIENT_SESSION pcse1_0 where ((pcse1_0.CLIENT_ID=? and pcse1_0.CLIENT_STORAGE_PROVIDER=? and pcse1_0.EXTERNAL_CLIENT_ID=? and pcse1_0.OFFLINE_FLAG=? and pcse1_0.USER_SESSION_ID=?))

```

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Entities with version field with correct casing for successful login on offline sessions

### Actual behavior

Throws "For mode on this error consult the server log at the debug level"

But i forget to save the errors

### How to Reproduce?

In my case i was on version 24.0.1 and updated to 24.0.2, using Microsoft SQL Server

**Comment by ahus1** [comment]
Sorry to hear this is happening to you. I research it and it seems that the behavior of MSSQL depends on the operating system and the collation settings if it treats column names case-sensitive. 

We'll try to fix this in the next patch release.

**Comment by ahus1** [comment]
Release 25.0.4 is now available which fixes this issue. Please let us know if this now works for you as expected.

**Comment by truediogo** [comment]
> Release 25.0.4 is now available which fixes this issue. Please let us know if this now works for you as expected.

Fixed, ty

**Comment by mixman68** [comment]
Seems to be back in 26, it is a regression ?

```
2024-10-05 12:49:19,334 INFO  [org.hibernate.event.internal.DefaultLoadEventListener] (org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker) HHH000327: Error performing load command: org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [select pcse1_0.CLIENT_ID,pcse1_0.CLIENT_STORAGE_PROVIDER,pcse1_0.EXTERNAL_CLIENT_ID,pcse1_0.OFFLINE_FLAG,pcse1_0.USER_SESSION_ID,pcse1_0.DATA,pcse1_0.TIMESTAMP,pcse1_0.VERSION from public.OFFLINE_CLIENT_SESSION pcse1_0 where (pcse1_0.CLIENT_ID,pcse1_0.CLIENT_STORAGE_PROVIDER,pcse1_0.EXTERNAL_CLIENT_ID,pcse1_0.OFFLINE_FLAG,pcse1_0.USER_SESSION_ID) in ((?,?,?,?,?))] [ERROR: column pcse1_0.version does not exist
```

**Comment by ahus1** [comment]
@mixman68 - thank you for opening a new issue, this is the way to analyze this. I'll have a look at that issue.
