### ISSUE TITLE
ReadOnlyException in Authenticator / RequiredAction occured on setAttribute

### ISSUE THREAD

**Issue by deincodeverbesserer93** [keycloak/keycloak#32132]
### Description

Hello,
i don`t know is this a bug or is this the normal behaviour.

When i set a custom attribute in keycloak  to an user in an ldap directory. 
The exception org.keycloak.storage.ReadOnlyException occured. When i use this in read-only mode.
It only works in a LdapMapper here can i set a keycloak attribute in read-only mode ldap directory.
When i set writeable mode than all works. But our service user in ldap-connection has to many rights and it could be a security problem.

Or is there any trick how this could work in readonly mode.

**Steps to reproduce**
- Keycloak: 24.0.5, 25.0.2
- add a microsoft ldap directory in read-only mode
- create a **RequiredAction** or **Authenticator**
- set or activate **RequiredAction** or **Authenticator**

Code
 
```
 @Override
    public void authenticate(AuthenticationFlowContext context) {
        log.info("authenticate called...");

        UserModel user = context.getUser();
      
        user.setSingleAttribute("test","Test1")
```

**Expected Behavior**

- add user attribute in keycloak
- add no user attribute to the ldap directory

**Comment by mposolda** [comment]
I think this works as expected. When you set `Edit mode` of LDAP provider to read-only, the whole user instance is read-only (the `ReadonlyLDAPUserModelDelegate` ) and hence it is not possible to edit any attributes of the user.

Maybe there are few possibilities how to setup what you want (Depends exactly on your requirements, deployment etc).

If you prefer to be able to set some attributes to the LDAP user and those attributes are not mapped to the LDAP, they will be saved to the Keycloak DB (like the attributes `test` for your case). So maybe the option is to set `Edit mode` to `WRITABLE` or `UNSYNCED` for LDAP provider, but then setup the LDAP mappers appropriately for the attributes, which you don't want your users to edit. For example, you can set LDAP mapper for attribute `email` to be read-only and then users won't be able to update their email from Keycloak. Similarly for the other attributes, which you don't want users to be able to edit.

Note that with `UNSYNCED` mode, nothing is written back to LDAP. Users are still able to edit their attributes in Keycloak by default, but those attributes are written to Keycloak DB in that case and then they are also read from Keycloak DB if they exist here. So you can doublecheck if this is what you need...

Anyway, I don't think that this is a bug.
