### ISSUE TITLE
Loading the proxied admin loads assets of non-admin, resulting in 404

### ISSUE THREAD

**Issue by wiebeytec** [keycloak/keycloak#32159]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I try to use the `hostname-admin` feature, opening Keycloak on that domain, it still tries to load various assets over the `hostname` url, resulting in 404s with the message: 

```
{"error":"Unable to find matching target resource method",
"error_description":"For more on this error consult the server log at the debug level."}
```

The browser inspector shows:

![keycloak_assets_404](https://github.com/user-attachments/assets/7fe73579-bb6c-4aee-b36d-ab6be3bce6ff)

The first document contains this script tag:

```
<script id="environment" type="application/json">
      {
        "serverBaseUrl": "https://login.example.com",
        "adminBaseUrl": "https://sso.example.com",
        "authUrl": "https://sso.example.com",
        "authServerUrl": "https://login.example.com",
        "realm": "master",
        "clientId": "security-admin-console",
        "resourceUrl": "/resources/ggw81/admin/keycloak.v2",
        "logo": "",
        "logoUrl": "",
        "consoleBaseUrl": "/admin/master/console/",
        "masterRealm": "master",
        "resourceVersion": "ggw81"
      }
    </script>
```

The result for the user is a hanging spinner.

The `keycloak.conf` is:

```
hostname=https://login.example.com/
hostname-admin=https://sso.example.com/
hostname-debug=true

proxy-headers=xforwarded
http-enabled=true
hostname-strict=false
```

Nginx is:

```
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name sso.example.com;

  location / {
    proxy_pass        http://127.0.0.1:8080/;

    # This one doesn't make a difference.
    proxy_set_header  Host                 $host;

    proxy_set_header  X-Forwarded-Host     $host;
    proxy_set_header  X-Forwarded-For      $proxy_protocol_addr;
    proxy_set_header  X-Forwarded-Proto    $scheme;
  }

  access_log /var/log/nginx/sso.example.com/access.log combined_plus;
  error_log  /var/log/nginx/sso.example.com/error.log;

  ssl_certificate     /etc/letsencrypt/live/sso.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/sso.example.com/privkey.pem;

  include letsencrypt.inc;
}

server {
  listen         80;
  listen         [::]:80;
  server_name    sso.example.com;
  include        letsencrypt.inc;
  return         301 https://$server_name$request_uri;
}

```

It also happens when I set the `hostname-admin` to `http://localhost:8080` and use an SSH tunnel to the server to access it. Even when starting with `start-dev`.

Versions:

* keycloak-999.0.0-SNAPSHOT
* keycloak-25.0.2

### Version

keycloak-999.0.0-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

When opening Keycloak on the admin URL, it should know that's loading the admin, using only the admin URLs.

### Actual behavior

Keycloak is accessible on the admin URL, but it also uses the non-admin URL for asset loading, which fails.

### How to Reproduce?

See above.

### Anything else?

![hostname_debug_Screenshot_20240815_134206](https://github.com/user-attachments/assets/97036de3-ae7e-430c-a5f4-10707da96278)

**Comment by shawkins** [comment]
This seems to be the currently expected behavior - the front-end url is expected to always be publically accessible, so it should work for common assets even when using a different admin hostname. Does your nginx configuration purposely not expose login.example.com?

**Comment by wiebeytec** [comment]
Loading assets from the public one indeed seems like something that maybe should be possible. However, my login.example.com is available in the same manner. It works when I open it.

Also, the content returned with the 404 was `Unable to find matching target resource method`, which is not an Nginx error. That's a keycloak message.

I can do some more experiments later to hopefully find out more.

**Comment by shawkins** [comment]
> However, my login.example.com is available in the same manner. It works when I open it.

Do you mean that nginx is configured to have server_name login.example.com (or similar configuration) such that it is proxying login.example.com as well? And that if you try to access https://login.example.com (https at the default port) that it seems usable in your browser?

I must not quite be understanding your setup because I'm not yet able to reproduce this behavior - the public front-end urls are usable for me.

> Also, the content returned with the 404 was Unable to find matching target resource method, which is not an Nginx error. That's a keycloak message.

The conclusion would be that you are hitting keycloak, but the path is wrong. What is the full request url that is failing with a 404? And can you check the proxy error / access log for exactly what request is being sent to the keycloak server based upon that?

**Comment by wiebeytec** [comment]
:scream: :scream:  :scream: 

I decided to restart with my proxy config from scratch to confirm everything, and realized where the PEBKAC was... 

Nginx requires `location /resources/ { ... }` to be proxied to `http://localhost:8080/resources/`, not `http://localhost:8080/` ...
