### ISSUE TITLE
Healthcheck on the main http server

### ISSUE THREAD

**Issue by kozlek** [keycloak/keycloak#32166]
### Description

I would like to monitor Keycloak availability through the main http server.

It is already possible using `legacy-observability-interface` and `/health/*` endpoints but that setting is marked at both deprecated and not recommended, so I'm looking for a more sustainable way.

### Motivation

My orchestrator monitors Keycloak through the management interface and it works well.
However, I had an outage related to a network configuration (unrelated to Keycloak) and while the management interface worked well, the main interface was unreachable by my users. 

I would like to add a way of monitoring Keycloak availability from the outside to get a full user perspective.

### Details

Documentions pages used:
- https://www.keycloak.org/server/health#_using_the_health_checks
- https://www.keycloak.org/server/management-interface

**Comment by sschu** [comment]
@kozlek You can just set some monitoring that for example sends simple GET request to the well-known endpoint of Keycloak or you could do more complex things like create a web test that performs an automated login to Keycloak. What exactly are you missing here?

**Comment by kozlek** [comment]
@sschu You're right, `https://<domain>/realms/<realm>` does the trick.

Thanks !
