### ISSUE TITLE
FIPS documentation update

### ISSUE THREAD

**Issue by james-erickson** [keycloak/keycloak#32163]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Going through the FIPS documentation here https://www.keycloak.org/server/fips and I ran into a issue where the docs are outdated. The Bouncy Castle libs need to have bcutil-fips-*.jar added to the list of required otherwise you get this error
`java.lang.NoClassDefFoundError: org/bouncycastle/asn1/eac/EACObjectIdentifiers`

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

NA

### Actual behavior

NA

### How to Reproduce?

NA

**Comment by rmartinc** [comment]
Hi @james-erickson!

I have done the following steps:

* Download and unzip 25.0.4.
* In the providers folder I downloaded the jars as specified in the guide.
```bash
wget https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/1.0.2.3/bc-fips-1.0.2.3.jar
wget https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-fips/1.0.7/bcpkix-fips-1.0.7.jar
wget https://repo1.maven.org/maven2/org/bouncycastle/bctls-fips/1.0.18/bctls-fips-1.0.18.jar
```
* Created the certificate located in the `bin` folder:
```bash
keytool -genkeypair -sigalg SHA512withRSA -keyalg RSA -storepass passwordpassword   -keystore ../conf/server.keystore   -alias localhost   -dname CN=localhost -keypass passwordpassword
```
* And the server was started:
```bash
./kc.sh start --features=fips --hostname=localhost --https-key-store-password=passwordpassword --log-level=INFO,org.keycloak.common.crypto:TRACE,org.keycloak.crypto:TRACE
```

And it's working for me without issues. Besides the missing class I see it's in the bc-fips-1.0.2.3.jar file:

```bash
jar tvf bc-fips-1.0.2.3.jar | grep org/bouncycastle/asn1/eac/EACObjectIdentifiers
  1604 Thu Nov 11 13:58:58 CET 2021 org/bouncycastle/asn1/eac/EACObjectIdentifiers.class
```

So I cannot reproduce the issue. Besides I have checked and I don't see any dependency in none of the three jars to the bcutil-fips jar. Note that in the bc download page the bcutil-fips is only displayed in the version 2.0.0 which we are not integrating/testing yet.

**Comment by isaacjensen** [comment]
I am running into this exact same issue with latest v2 BCFIPS .jars and KC 26.0.0
