### ISSUE TITLE
Keycloak reuses AUTH_SESSION_ID of logged out sessions

### ISSUE THREAD

**Issue by robertoneto-senior** [keycloak/keycloak#32197]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

On discussion #31265 I reported this bug.

The scenario:
- I login using the authorization_code flow via keycloak login page 
- My application issues a new token
- Via keycloak administrative console, I force that user session logout
- At this moment the backchannel logout triggers, and my app stores the SID claim of the logout_token  in a blacklist to guarantee that all tokens issued with that SID will be denied.
- When I navigate again to the keycloak login page, the browser session uses the same SID via AUTH_SESSION_ID from the previous login (the cookie was restored/reused).
- After enter with my credentials, another token will be issued (by my app) with that same SID, and my app will deny this new token because that SID was already logged out

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

In my opinion, Keycloak should not accepting SIDs (via AUTH_SESSION_ID cookie) that were already logged out.

Sessions "reborn" that was already dead (logged out) is a strange behavior, in my opinion.

This turns in a complex token management, my application will need to also to keep the "iat" claim of the logout_token, to be possible to accept or deny tokens with a specific SID.

For example, with the current behavior, my application will need to validate access tokens in this way:
- the SID of the token were logged out in some moment?
- the "iat" claim of the access token is after the SID logout moment? If so, I will accept it. Otherwise, I will deny it.

### Actual behavior

As mentioned in the scenario in description.

### How to Reproduce?

As mentioned in the scenario in description.

**Comment by robertoneto-senior** [comment]
Dear folks!

Any status of this issue @graziang and @jonkoops ?

Any workaround instead of my one?

**Comment by jonkoops** [comment]
We're still in the process of triaging this issue. Due to the pending Keycloak 26 release and other triaging work this can take some time.

**Comment by betonetotbo** [comment]
Same bug here +1

**Comment by jonkoops** [comment]
Please do not leave comments unless there is something to add to the conversation. If you are experiencing the same issue you can upvote it by leaving a :+1: on the PR description.

**Comment by robertoneto-senior** [comment]
Hi again.

@jonkoops ... I have a question about the [authorization code request parameters](https://openid.net/specs/openid-connect-basic-1_0.html#RequestParameters).

As described in the OIDC documentation, the request parameters `state` and `nonce` are subsequently "recommended" and "optional".

At my case, I'm not using/defining them.

But, I tried them in a insolated scenario I they solved the issue (each time the auth redirect occurs, a new SID is issued by keycloak login page). 

So, on this way, I think this issue can be closed.

As a workaround, can I assume that is a impicit requirement of this parameters to prevent this behavior?

**Comment by jonkoops** [comment]
@graziang do you have an answer to the above questions?

**Comment by graziang** [comment]
Hi @robertoneto-senior sorry for the late response, I managed to reproduce this issue.
The reason is that when multiple tabs exist for an auth session, it is not deleted when logging out via backchannel logout or admin console. As a result, after a new login, the `AUTH_SESSION_ID` cookie remains valid, and a new user session with the same session ID is created. I'm on it, and I hope to fix it soon.

**Comment by ppetrovt** [comment]
When do we expect to release `25.0.7` patch version? @graziang @mposolda
