### ISSUE TITLE
KeyCloak with Azure MySQL throws "Certificates do not conform to algorithm constraints"

### ISSUE THREAD

**Issue by Pilleo** [keycloak/keycloak#32248]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

The description is similar to https://github.com/keycloak/keycloak/issues/17606, just for MySQL.
We are running KeyCloak and MySQL db in  Azure. It is running with current setup, but we have to migrate to Azure Flexible MySQL server, which is also working fine for every app except KeyCloak, it gives us:

> 2024-08-19 13:27:14,153 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> 2024-08-19 13:27:14,219 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
> 2024-08-19 13:27:14,271 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
> 2024-08-19 13:27:14,272 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
> 2024-08-19 13:27:14,273 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> 2024-08-19 13:27:14,275 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Communications link failure
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
> 2024-08-19 13:27:14,276 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
> 2024-08-19 13:27:14,276 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
> 2024-08-19 13:27:14,277 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Algorithm constraints check failed on signature algorithm: SHA1withRSA

 It works with [this "fix" ](https://github.com/keycloak/keycloak/issues/30164#issuecomment-2268885498). But obviously we want it better than that, so we have tried to apply smth similar to [this ](https://github.com/keycloak/keycloak/issues/17606#issuecomment-1631115584) by copying DigiCertGlobalRootCA.crt.pem into /opt/keycloak/conf/truststores/DigiCertGlobalRootCA.crt.pem which did not change anything. 

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Server starts successfully

### Actual behavior

Server does not start and throws the above mentioned error messages.

### How to Reproduce?

Run keycloak against a Azure MySQL database.

**Comment by Pilleo** [comment]
Hi @Bharath00, have you managed to solve this issue?

**Comment by shawkins** [comment]
This does not seem distinct from the #30164 - as mentioned there and linked above support for SHA1 is disabled by default. Without re-enabling it, these certs will not work.

I vote for closing this issue as to not split the discussion on this topic.

> But obviously we want it better than that

Please follow up on the other issue what else you think keycloak should be doing - it's the JDK that has SHA1 support disabled by default. This seems to be a sensible default for most users, and you can create a custom image to workaround it.

**Comment by Pilleo** [comment]
@shawkins , as you can see here https://github.com/keycloak/keycloak/issues/17606#issuecomment-1631115584 there is a better way at least for Postgres users, I would like to do the similar for MySQL

**Comment by shawkins** [comment]
> @shawkins , as you can see here https://github.com/keycloak/keycloak/issues/17606#issuecomment-1631115584 there is a better way at least for Postgres users, I would like to do the similar for MySQL

I am not sure how that would address the algorithm constraint issue. Adding trust of a cert with a disabled algorithm shouldn't make it work. In #30164 a user has logged an upstream issue https://github.com/Azure/azure-postgresql/issues/112 - a similar one should be created for mysql.
