### ISSUE TITLE
[Keycloak CI] - AuroraDB IT fails to start on EC2 due to lack of entropy regression

### ISSUE THREAD

**Issue by wojnarfilip** [keycloak/keycloak#32259]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Seems MigrationTest fail with Timeout due to some IllegalState. 
Reference GHA run: https://github.com/keycloak/keycloak/actions/runs/10462937028/job/28974098600

```org.keycloak.testsuite.migration.MigrationTest output end  ---------", "[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 398.569 s <<< FAILURE! - in org.keycloak.testsuite.migration.MigrationTest", "-- [ERROR] org.keycloak.testsuite.migration.MigrationTest  Time elapsed: 398.532 s  <<< ERROR!", "-- java.lang.RuntimeException: java.lang.IllegalStateException: Timeout [300000] while waiting for Quarkus server", "-- \tat org.keycloak.testsuite.arquillian.containers.KeycloakQuarkusServerDeployableContainer.start(KeycloakQuarkusServerDeployableContainer.java:56)", "-- \tat org.jboss.arquillian.container.impl.ContainerImpl.start(ContainerImpl.java:179)", "-- \tat org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:137)", "-- \tat org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$8.perform(ContainerLifecycleController.java:133)", "-- \tat org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:208)", "-- \tat org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.startContainer(ContainerLifecycleController.java:133)", "-- \tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)", "-- \tat java.base/java.lang.reflect.Method.invoke(Method.java:580)", "-- \tat org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)", "-- \tat org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:54)", "-- \tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)", "-- \tat java.base/java.lang.reflect.Method.invoke(Method.java:580)", "-- \tat org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)", "-- \tat org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)", "-- \tat org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)", "-- \tat org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)", "-- \tat org.keycloak.testsuite.arquillian.AuthServerTestEnricher.startAuthContainer(AuthServerTestEnricher.java:387)", "-- \tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)", "-- \tat java.base/java.lang.reflect.Method.invoke(Method.java:580)", "-- \tat org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)", "-- \tat org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)", "-- \tat org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)", "-- \tat org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)", "-- \tat org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:83)", "-- \tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)", "-- \tat java.base/java.lang.reflect.Method.invoke(Method.java:580)", "-- \tat org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)", "-- \tat org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)", "-- \tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)", "-- \tat java.base/java.lang.reflect.Method.invoke(Method.java:580)", "-- \tat org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)", "-- \tat org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)", "-- \tat org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)", "-- \tat org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)", "-- \tat org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:71)", "-- \tat org.jboss.arquillian.junit.AdaptorManager.initializeAdaptor(AdaptorManager.java:23)", "-- \tat org.jboss.arquillian.junit.AdaptorManagerWithNotifier.initializeAdaptor(AdaptorManagerWithNotifier.java:19)", "-- \tat org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:103)", "-- \tat org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)", "-- \tat org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)", "-- \tat org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)", "-- \tat org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)", "-- \tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)", "-- \tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)", "-- \tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)", "-- \tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)", "-- Caused by: java.lang.IllegalStateException: Timeout [300000] while waiting for Quarkus server", "-- \tat org.keycloak.testsuite.arquillian.containers.AbstractQuarkusDeployableContainer.waitForReadiness(AbstractQuarkusDeployableContainer.java:310)", "-- \tat ```

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Tests pass

### Actual behavior

Tests fail

### How to Reproduce?

Maybe reproducible in GHA

**Comment by ahus1** [comment]
I traced this down to Liquibase in Quarkus waiting for a secure random due to a change in commons-lang3 which was introduced in the latest Quarkus upgrade: https://issues.apache.org/jira/browse/LANG-1748
On the EC2 instances, there is not enough entropy to do this, so this happens only there. The usual `-Djava.security.egd=file:/dev/urandom` isn't working here.

Quarkus rolled back the update here: https://github.com/quarkusio/quarkus/pull/42597

An upgrade to Quarkus 3.13.3 should fix this. 

@keycloak/cloud-native - could you please update to the latest Quarkus patch release?

**Comment by vmuzikar** [comment]
@kami619 @ahus1 With the [Quarkus upgrade](https://github.com/keycloak/keycloak/pull/32390) now merged, can this be resolved?

**Comment by kami619** [comment]
@vmuzikar looks like https://github.com/keycloak/keycloak/actions/runs/10558331252/job/29247579070 this was skipped, so I ran the Keycloak CI on my fork, I shall report back once this is successful.

**Comment by ahus1** [comment]
It should. I started a build in the main branch: https://github.com/keycloak/keycloak/actions/runs/10564125064

(oops, @kami619 is also looking into this)

**Comment by ahus1** [comment]
Kamesh's build skipped Aurora DB (possibly an AWS key was missing in his fork?) and it also the re-run failed for a reason yet unknown to me (maybe a parallel setup interfering?)

Still, the build succeeded tonight: https://github.com/keycloak/keycloak/actions/runs/10569327101

So I'm closing this one as it seems to have been fixed. Thank you for everyone involved in this!
