### ISSUE TITLE
Scope of "scripts" preview feature

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#32272]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Currently https://www.keycloak.org/server/features#_preview_features documents `scripts` preview feature as 

* Write custom authenticators using JavaScript. 

but https://www.keycloak.org/docs/25.0.0/server_development/#_script_providers says that `scripts` covers

* Authenticator
* JavaScript Policy
* OpenID Connect Protocol Mapper
* SAML Protocol Mapper

In the code it seems that `scripts` feature flag is checked in 

* authenticator ([link](https://github.com/keycloak/keycloak/blob/aee9390812b884072c5cac03c96eaf6794e2e682/services/src/main/java/org/keycloak/authentication/authenticators/browser/ScriptBasedAuthenticatorFactory.java#L145))
* OIDC mapper ([link](https://github.com/keycloak/keycloak/blob/aee9390812b884072c5cac03c96eaf6794e2e682/services/src/main/java/org/keycloak/protocol/oidc/mappers/ScriptBasedOIDCProtocolMapper.java#L124)) 
* SAML mapper  ([link](https://github.com/keycloak/keycloak/blob/aee9390812b884072c5cac03c96eaf6794e2e682/services/src/main/java/org/keycloak/protocol/saml/mappers/ScriptBasedMapper.java#L104))  

However authz policy provider is not guarded by feature flag check ([link](https://github.com/keycloak/keycloak/tree/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js))

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The documentation linked above should be consistent with each other. It should be clarified if JavaScript authz policies is intended to be also behind the feature flag.

### Actual behavior

n/a

### How to Reproduce?

n/a

### Anything else?

JavaScript authenticator provider seems to be the first one implemented, so maybe the description of the flag reflects that history https://github.com/keycloak/keycloak/blob/fed804160befe60b283b6d9c9ae26218902a79dc/common/src/main/java/org/keycloak/common/Profile.java#L70

**Comment by pedroigor** [comment]
The main reason why JS policies are not guarded is that for historical reasons we use a JS policy as a default policy when you enable authorization settings for a client. This policy is internal and not a script deployed to the server.

Even though the JS policy is enabled you can't deploy scripts to the server if you don't enable the `scripts` feature.

I hope it clarifies why it works like that. Closing as a question.
