### ISSUE TITLE
The UPDATE_EMAIL required action never gets loaded by Keycloak

### ISSUE THREAD

**Issue by stustison** [keycloak/keycloak#32287]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I tried to enable the Update Email required action by setting KC_FEATURES with "update-email" and then including this required action as part of the realm import. Trying to navigate to https://keycloak:8443/admin/master/console/#/myrealm/authentication
results in an error. Digging into the error response, I can see that the required action is never added to the list of required action providers that the system knows about and a null pointer exception is thrown in `AuthenticationManagementResource.toRepresentation()` when `factory.isConfigurable()` is called

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

I expected to be able to turn on this feature via the flag and then utilize the required action provider.

### Actual behavior

A null pointer exception is thrown.

### How to Reproduce?

Enable the "update-email" feature
Add the required action as part of a realm import
Attempt to navigate to the realm Authentication tab

**Comment by martin-kanis** [comment]
@stustison Thanks for the report. However, I'm not able to reproduce it with the current `main`. 

My steps: 

1. start the server with `update-email` feature enable
2. create a user and assign UPDATE_EMAIL required action to the user
3. export the realm (I see `"requiredActions" : [ "UPDATE_EMAIL" ],` in the export file for the user)
4. import the file on a different server instance
5. navigate to Authentication tab, nothing happens. The user is imported, the required action is set for the user
