### ISSUE TITLE
Client-based permission not evaluated correctly

### ISSUE THREAD

**Issue by mpicanyol** [keycloak/keycloak#32300]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

We have a Keycloak client that acts a a resource server. A resource has been defined. Two client-based policies have also been defined: one policy for client A and another for client B. We have created two permissions: one that allows access to the resource for client A and another that allows access to the resource for client B. Access is not authorized even though the Decision strategy is set to Affirmative in the general client settings.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect to allow access to client A or B when the Decision strategy is set to Affirmative, because at least on of the permissions is positive.

### Actual behavior

Resource is not authorized for client A or client B.

### How to Reproduce?

- Create a confidential client A.
- Create a confidential client B.
- Create a resource server. New client with Client authentication and Authorization options enabled.
  - Authorization tab, Settings -> Decision Strategy: Affirmative
  - Authorization tab, Resources -> Create resource
  - Authorization tab, Policies -> Create client-based policy for Client A
  - Authorization tab, Policies -> Create client-based policy for Client B
  - Authorization tab, Permissions -> Create resource-based permission that allows access to the resource for Client A.
  - Authorization tab, Permissions -> Create resource-based permission that allows access to the resource for Client B.

When trying to access the resource URL with Client A or Client B credentials, access is denied.

**Comment by pedroigor** [comment]
Thanks. Duplicate https://github.com/keycloak/keycloak/issues/10086#issuecomment-1210776998.

**Comment by christophenoel** [comment]
I have understood from the old related issue that Decision Strategy only works if you assigned a scope to the resource (even a dummy scope). It is not clear why ? Thank you for your guidance.
