### ISSUE TITLE
Temporary admin account notice logged to org.keycloak.events

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#32305]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

`org.keycloak.events` is a special category that should only be used for events, and not general log statements.

In addition using `JBossLoggingEventListenerProvider` for this purpose is not good. It's an optional thing that is only enabled for some realms, and this just isn't the correct place for this statement.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

`org.keycloak.events` only logs login events or admin events, and not general log statements.

### Actual behavior

Invalid event logged using `org.keycloak.events`:

```
2024-08-21 11:11:43,933 WARN  [org.keycloak.events] (executor-thread-1) admin is a temporary admin service account. To harden security, create a permanent account and delete the temporary one.
```

### How to Reproduce?

Login with a temporary user account

**Comment by stianst** [comment]
Introduced in https://github.com/keycloak/keycloak/commit/1b5fe5437a69d5bbf3faed9371d901ebbe8b7ad1, please remove these log outputs, or find a different place and category to do it.

**Comment by vmuzikar** [comment]
> It's a lot of extra code, for a very special case. Where we do actually have plans for adding the concept of expiring user accounts in a generic way.

I would not say it's lot of code for a special use case. For now perhaps. But when we have the generic way, I reckon the UI changes will be re-used (evolved). So I see it as a baseline for the future generic expiration.
