### ISSUE TITLE
`/admin/realms` endpoint for 200 realms loads 2MB of json

### ISSUE THREAD

**Issue by indera** [keycloak/keycloak#32310]
### Description

For 200 realms I see repeated blocks of data 

```
        "browserSecurityHeaders": {
            "contentSecurityPolicyReportOnly": "...",
            "xContentTypeOptions": "...",
            "xRobotsTag": "...",
            "xFrameOptions": "...",
            "contentSecurityPolicy": "...",
            "xXSSProtection": "...",
            "strictTransportSecurity": "..."
        },

smtpServer {
   replyToDisplayName
   starttls
   ...
}

enabledEventTypes {
   SEND_RESET_PASSWORD
   ...
}
```

Would it be possible to load these only when needed instead of all the time?

### Details

It is possible this was fixed in the latest version of keycloak but I don't have access to it.

**Comment by jonkoops** [comment]
Please report issues only against the latest version of Keycloak. If you want less details it should be possible to add `briefRepresentation=true` to the API call.
