### ISSUE TITLE
Legacy `KEYCLOAK_ADMIN` environment variable is not working

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#32333]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Using legacy bootstrapping for admin account creates user with the wrong username, as it seems `KEYCLOAK_ADMIN` environment variable is ignored.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Admin user should be created based on username from `KEYCLOAK_ADMIN` and password from `KEYCLOAK_ADMIN_PASSWORD`.

### Actual behavior

Admin user has username `temp-admin`, and password from `KEYCLOAK_ADMIN_PASSWORD`

### How to Reproduce?

Start Keycloak with:
```
KEYCLOAK_ADMIN=myadmin KEYCLOAK_ADMIN_PASSWORD=mypassword kc/bin/kc.sh start-dev
```

Now you can login to the admin console with `temp-admin` / `mypassword` instead of `myadmin` / `mypassword` as expected.

**Comment by vmuzikar** [comment]
Most probably caused by:
https://github.com/keycloak/keycloak/commit/d9a92f5de30d5af642db65ea00f2ab9510e6713a#diff-cd7ce849e7c544b92297f6998dc545e10e2280cc6e87b4ca7b22476bb0511160R19

**Comment by shawkins** [comment]
> Most probably caused by: [d9a92f5#diff-cd7ce849e7c544b92297f6998dc545e10e2280cc6e87b4ca7b22476bb0511160R19](https://github.com/keycloak/keycloak/commit/d9a92f5de30d5af642db65ea00f2ab9510e6713a#diff-cd7ce849e7c544b92297f6998dc545e10e2280cc6e87b4ca7b22476bb0511160R19)

The issue is with the recent change to expose the cli options - there is now a default associated with the username, so the env variable is no longer consulted.
