### ISSUE TITLE
none of the enabled features are shown as such in the admin console

### ISSUE THREAD

**Issue by jean-christophe-manciot** [keycloak/keycloak#32348]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Despite building the server with a list of ```Preview``` features, none of those appear in the ```Enabled features``` area but rather below the ```Disabled features```.
Are they not used or is this just a UI issue?

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

All enabled features, including ```Preview``` and ```Experimental``` ones should be listed as enabled when keycloak has been built/started with those as enabled.

### Actual behavior

When enabling the following features at build time:
- client-secret-rotation,
- passkeys,
- persistent-user-sessions,
- recovery-codes

I get:
![Screenshot from 2024-08-22 15-49-02](https://github.com/user-attachments/assets/51552bc1-699d-4e69-b9a9-6b1325ff46e8)

### How to Reproduce?

1. download 25.0.4 and extract
2. install ojdbc11-23.5.0.24.07.jar into providers
3. install orai18n-23.5.0.24.07.jar into providers
4. set keycloak.conf and quarkus.properties into conf 
5. bin/kc.sh build --features="client-secret-rotation,passkeys,persistent-user-sessions,recovery-codes"
6. bin/kc.sh start --proxy-headers=xforwarded &

**Comment by jean-christophe-manciot** [comment]
Same issue with keycloak 25.0.1.

**Comment by shawkins** [comment]
> bin/kc.sh start --proxy-headers=xforwarded 

If you do not include --optimized, then the start command is assumed to be independent of the build. Since the features aren't specified again, they revert back to the defaults.

You should see a warning in the console when start runs like:

```
The previous optimized build will be overridden with the following build options:
	- features=client-secret-rotation,passkeys,persistent-user-sessions,recovery-codes > features=<unset>
To avoid that, run the 'build' command again and then start the optimized server instance using the '--optimized' flag.
```

If you feel that there is more to this, please reopen.

**Comment by jean-christophe-manciot** [comment]
@shawkins 

I'm confused. According to "[Configuring a database](https://www.keycloak.org/server/db)":
> Do NOT use the --optimized flag for the start command if you want to use a particular DB (except the H2). 

Since I'm using MySQL, I thought that the ```--optimized``` flag was not to be used.

Am I missing something here?

**Comment by shawkins** [comment]
@jean-christophe-manciot that note may need some tweaking - it means that if you haven't already run a bulid, then the database will remain the default of h2.

**Comment by jean-christophe-manciot** [comment]
> @jean-christophe-manciot that note may need some tweaking - it means that if you haven't already run a bulid, then the database will remain the default of h2.

I see. Except that stoppping and restarting AWX with ```bin/kc.sh start --optimized --proxy-headers=xforwarded &``` does not change anything:
![Screenshot from 2024-08-27 17-59-29](https://github.com/user-attachments/assets/fdddd6ed-0b1c-4671-a3e7-a1c32251689c)

Do I need to run a build again?

**Comment by jean-christophe-manciot** [comment]
Yes, if I perform another build, all the enabled features are shown as such in the admin console.

**Comment by shawkins** [comment]
> Yes, if I perform another build, all the enabled features are shown as such in the admin console.

start without --optimized, start-dev, and the non-server commands (import, export, bootstrap-admin) will all perform implicit builds if there their given options don't match what is in the existing optimized image. So yes, once something has modified the image, you need to run build again to restore it to what you want.

**Comment by shawkins** [comment]
@jean-christophe-manciot would https://github.com/keycloak/keycloak/pull/32433 make this situation clearer?

**Comment by jean-christophe-manciot** [comment]
> @jean-christophe-manciot would #32433 make this situation clearer?

To be honest, no. I would remind the administrator in a warning block that the database settings can be defined during the build phase followed by a ```start --optimized```, or during the start command as shown in the example ```1. Start the server and set the basic options to configure a database``` without using the ```--optimized``` option.

**Comment by shawkins** [comment]
I'm not in favor of a warning because this is standard behavior wrt build-time options, and without careful wording could make it seem like we're warning against using --optimized (as you initially inferred). 

That is not the case as we recommend using --optimized for nearly all production usage. Initially showing start without --optimized and setting the database type is mostly a development time paradigm.

cc @mabartos

**Comment by jean-christophe-manciot** [comment]
Another way is to use a different layout below [Configuring a database](https://www.keycloak.org/server/db):


> For each supported database, the server provides some opinionated defaults to simplify database configuration. You complete the configuration by providing some key settings such as the database host and credentials.

The configuration can be set during the **build phase** OR the **start phase**:
1. During the build phase:
_to be completed_
2. During the start phase: 
Start the server and set the basic options to configure a database
```
bin/kc.[sh|bat] start --db postgres --db-url-host mypostgres --db-username myuser --db-password change_me
```
This command includes the minimum settings needed to connect to the database.

The default schema is keycloak, but you can change it by using the db-schema configuration option.

**Comment by shawkins** [comment]
Do you want to submit that in a pr? The only thing I would change is to use the term command instead of phase and mention the role of --optimized for both 1 and 2.

**Comment by shawkins** [comment]
~priority-low
