### ISSUE TITLE
Never able to change import strategy

### ISSUE THREAD

**Issue by uwevil** [keycloak/keycloak#32355]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

I found this setting in KeycloakApplication which force the import strategy IGNORE_EXISTING, so I can't change this from startup keycloak application.

                System.setProperty(ExportImportConfig.STRATEGY, Strategy.IGNORE_EXISTING.toString());

file : https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L199

and in src/main/java/org/keycloak/exportimport/dir/DirImportProviderFactory.java
```
@Override
    public ImportProvider create(KeycloakSession session) {
        Strategy strategy = Enum.valueOf(Strategy.class, System.getProperty(ExportImportConfig.STRATEGY, config.get(STRATEGY, DEFAULT_STRATEGY.toString())));
        String realmName = System.getProperty(ExportImportConfig.REALM_NAME, config.get(REALM_NAME));
        String dir = System.getProperty(ExportImportConfig.DIR, config.get(DIR));
        return new DirImportProvider(session.getKeycloakSessionFactory(), strategy)
                .withDir(dir)
                .withRealmName(realmName);
    }
```

The strategy return is always IGNORE_EXISTING even if we are set in the keycloak property.

So maybe the factory need to be fixed.

### Version

main or 24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

possible to set import strategy

### Actual behavior

cannot change import strategy when starting Keycloak

### How to Reproduce?

run keycloak with extra argument: --import-realm --override=true --features=preview --verbose -Dkeycloak.migration.strategy=OVERWRITE_EXISTING

**Comment by pedroigor** [comment]
Please, see https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup. Importing realms during start-up will not override/re-create existing realms. For that, consider using the `import` command.
