### ISSUE TITLE
Duplicate message keys in admin messages_en.properties

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#32425]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Since commit a3ffbb439dab8983239054348cd59bb5f0e0b9d7 (unfortunately without a reference to an issue), there are not the keys `joinOrganization` and `join` present twice in the file.

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Each key should be present only once.

### Actual behavior

The keys are present twice.

### How to Reproduce?

Looking at the file.

### Anything else?

Pinging @edewit as it seems you've authored the commit.

**Comment by ssilvert** [comment]
@ahus1 Why do you consider this a blocker?  Is it causing some operation issue?

**Comment by ahus1** [comment]
@ssilvert: 

* It is a syntax error in the file: It shows in red in IntelliJ, and also the web based translation tool complains that the file is invalid. It will show in similar way to anyone else who tries to translate it
* It is a regression
* It is simple to fix as it is about removing two lines

That's why I don't want to ship KC26 without a fix.
