### ISSUE TITLE
Keycloak truststore issue authenticating with mTLS

### ISSUE THREAD

**Issue by luis-miguel-almeida** [keycloak/keycloak#32446]
### Description

Greetings,

I'm trying to authenticate to a client (myclient_mTLS) with mTLS (x509) authentication and I'm getting 401 unauthorized.

I'm deploying keycloak on AWS on an EC2 instanced served by an application load balancer which has SSL passthrough enabled.

```
sudo docker run -d \
  --name keycloak-prod \
  -v /certificates:/certificates \
  -v /certificates:/opt/keycloak/conf/truststores \
  --network=host \
  -e KC_PROXY=edge \
  -e KEYCLOAK_ADMIN=pass \
  -e KEYCLOAK_ADMIN_PASSWORD=pass \
  -e PROXY_ADDRESS_FORWARDING=true \
  quay.io/keycloak/keycloak:25.0.4 \
  start \
  --features=token-exchange \
  --tls-hostname-verifier=ANY \
  --https-client-auth=request \
  --https-certificate-file=/certificates/subdomain_body.pem \
  --https-certificate-key-file=/certificates/key.pem \
  --hostname=<domain> \
  --https-port=8443 \
  --proxy-headers=xforwarded \
  --db=postgres \
  --db-url=jdbc:postgresql://<domain>:5432/postgres \
  --db-username=pass \
  --db-password=pass \
  --cache=ispn \
  --health-enabled=true
```

In this folder "/opt/keycloak/conf/truststores" I put every certificate that I use, namely root certificate, domain certificate and the certificate that I want to use to authenticate myself.

When I do this command:

```
curl -X POST "https://internal-keycloak-926077843.eu-central-1.elb.amazonaws.com/realms/master/protocol/openid-connect/token" \
    --cert /certificates/fredflinstone-crt.pem \
    --key /certificates/fredflinstone-key.pem \
    --cacert /certificates/rootCA-crt.pem \
    -d "client_id=myclient_mTLS" \
    -d "grant_type=client_credentials" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -v 
```

I'm getting always 401 unauthorized. The fredflinstone and rootCA certificates are all in the truststores that I mentioned above.

Keycloack error message:
``
2024-08-28 09:53:52,916 ERROR [org.keycloak.services] (executor-thread-4) KC-SERVICES0017: Unknown result status
2024-08-28 09:53:52,917 WARN  [org.keycloak.events] (executor-thread-4) type="CLIENT_LOGIN_ERROR", realmId="f4d40c0e-b423-4307-9f2c-e102285e4f42", realmName="master", clientId="myclient_mTLS", userId="null", ipAddress="10.33.21.157", error="invalid_client_credentials", grant_type="client_credentials"
``

My client configuration is the following:

![image](https://github.com/user-attachments/assets/4a99f262-e4da-4b72-9bc4-bc591cb8a629)

Can anyone point me to a solution?

Thank you

**Comment by siddjellali** [comment]
How do you solved this ?
