### ISSUE TITLE
KC_HOSTNAME_ADMIN is not used anymore for some HTML resources unless master frontendUrl is set

### ISSUE THREAD

**Issue by Flowwwww** [keycloak/keycloak#32458]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

env vars :
```
KC_HOSTNAME_ADMIN: https://adx6994.keycloak.my_domain.io/auth
KEYCLOAK_HTTP_RELATIVE_PATH:  /auth/
KC_HOSTNAME: https://adx6994.auth.my_domain.io/auth
```

realm_attributes:
- `frontendUrl ` is set to `https://adx6994.auth.my_domain.io/auth` for my realm but no `frontendUrl ` is set for `master ` realm.

When i try to access `https://adx6994.keycloak.my_domain.io/auth/admin/master/console/`, administration frontend tries to load resources from `https://adx6994.auth.my_domain.io/auth`
![image](https://github.com/user-attachments/assets/af70a1e2-3ee2-4688-a2c4-77553156f174)

It is blocked for security reasons on our ingress (that's why we see 404) but it should access theses resources using the `KC_HOSTNAME_ADMIN`

### Version

25.0.4

### Regression

- [x] The issue is a regression

### Expected behavior

It should access admin resources using the `KC_HOSTNAME_ADMIN` env var.

### Actual behavior

It uses `KC_HOSTNAME`.

### How to Reproduce?

Please, check configurations before ⬆

### Anything else?

If we set frontendUrl for master realm in database just like in this post : https://github.com/keycloak/keycloak/issues/14666#issuecomment-1988934505 
`INSERT INTO realm_attribute (name, realm_id, value) VALUES ('frontendUrl', (select id from realm where name = 'master'), 'https://admin-address.net/');`
Then it works but we shouldn't have to do that. 
It was working great with Keycloak 24.

**Comment by shawkins** [comment]
Relates to #32159 - the same behavior was noted there, which is the frontend url is used for some resources while accessing the admin console. 

There the user seemed fine with access to the frontend after correcting the proxy configuration. Here you are saying "It is blocked for security reasons on our ingress" - can you elaborate why the public frontend resources cannot be accessed when using the admin console?

cc @vmuzikar

**Comment by Flowwwww** [comment]
Actually resources from `https://adx6994.auth.my_domain.io/auth/resources` and `https://adx6994.auth.my_domain.io/auth/realms/[OUR_REALM]` are publicly accessible but when accessing the admin console, resources are loaded from `https://adx6994.auth.my_domain.io/auth/realms/master` that is blocked because we don't want master realm to be accessible as the documentation states here : https://www.keycloak.org/server/hostname

> Using the hostname-admin option does not prevent accessing the Administration REST API endpoints via the frontend URL specified by the hostname option. If you want to restrict access to the Administration REST API, you need to do it on the reverse proxy level. Administration Console implicitly accesses the API using the URL as specified by the hostname-admin option.

**Comment by shawkins** [comment]
> resources are loaded from https://adx6994.auth.my_domain.io/auth/realms/master that is blocked because we don't want master realm to be accessible just like /admin API as the documentation states here

The documentation is saying frontend/admin endpoints are still accessible. /realms/master is not an admin endpoint.
