### ISSUE TITLE
Unable to create custom RESTful 

### ISSUE THREAD

**Issue by nmanthena18** [keycloak/keycloak#32457]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I want to build custom RESTful API to get the users/filter users between the modified dates (from and to), I gone through the example and documention.

I have build very basic by refering this example: https://github.com/keycloak/keycloak/tree/24.0.5/examples/providers/rest and 
Documentation: https://www.keycloak.org/docs/latest/server_development/index.html#_extensions_rest

this is my source code the restful api : [api.zip](https://github.com/nmanthena18/keycloakRESTspi/blob/master/api.zip) sorry its git source code you have to extract it.

after developed  while test I am getting multiple issues
1. when we hit this url based on the READ.md file http://localhost:8080/auth/realms/master/api we are getting  this [exapmple: http://localhost:8080/auth/realms/master/hello] `{
    "error": "Unable to find matching target resource method",
    "error_description": "For more on this error consult the server log at the debug level."
}`

2. If we hit the http://localhost:8080/realms/master/api we are getting `{
    "error": "HTTP 405 Method Not Allowed",
    "error_description": "For more on this error consult the server log at the debug level."
}`

3. We want protect all endpoints with keycloak access_token

### Version

24.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

when we hit this http://localhost:8080/realms/master/api/user we should get `Custom user data`

### Actual behavior

{
    "error": "HTTP 405 Method Not Allowed",
    "error_description": "For more on this error consult the server log at the debug level."
}

### How to Reproduce?

You can download the source code given zip or you can go through the same example

**Comment by MouniAddala** [comment]
I am also facing the same issue

**Comment by nmanthena18** [comment]
We have same issue in latest version 25.0.4

**Comment by shawkins** [comment]
> when we hit this url based on the READ.md file http://localhost:8080/auth/realms/master/api we are getting this

I believe that has been logged in the past, but I cannot find the issue now. That was referencing the older wildfly /auth root path, which is not used by default in the quarkus distribution. If you encounter something like this with KC 25 or main, please open an issue.

> If we hit the http://localhost:8080/realms/master/api we are getting { "error": "HTTP 405 Method Not Allowed", "error_description": "For more on this error consult the server log at the debug level." }

See https://github.com/keycloak/keycloak/pull/27855 for KC 25 the examples were overhauled as quickstarts and the rest example in particular was removed. I believe the docs are now supposed to cover this case https://www.keycloak.org/docs/latest/server_development/#extending-the-server 

The important part from that is "Your JAX-RS resource is only recognized by the server and registered as a valid endpoint if it includes the following configuration: - adding an empty file named beans.xml under META-INF - annotating the JAX-RS class with the annotation jakarta.ws.rs.ext.Provider."

The example HelloResourceProvider is missing the Provider annotation, so the rest framework does not properly pick it up.

Please let me know if that works for you and we can come up with any additional action items to help clarify this more looking forward. Until then I'll set the priority of this to low.

~priority-low

**Comment by Hewei-ss** [comment]
Have you solved the problem? I ran into the same problem with keycloak25.0.5
