### ISSUE TITLE
Enabling authorization_details for client grant tokens until RAR is fully implemented

### ISSUE THREAD

**Issue by laurids** [keycloak/keycloak#32488]
### Description

Since Keycloak is not yet supporting [Rich Authorization Request (RAR)](https://datatracker.ietf.org/doc/html/rfc9396), we are using a custom protocol mapper in order to include `authorization_details` in issued tokens, when using a [Pushed Authorization Request (PAR)](https://datatracker.ietf.org/doc/html/rfc9126) flow. This was also recommended in [discussions/22991](https://github.com/keycloak/keycloak/discussions/22991).
This is possible because the [ParEndpoint](https://github.com/keycloak/keycloak/blob/25.0.4/services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/ParEndpoint.java) processing goes through [AuthorizationEndpoint.java#L332](https://github.com/keycloak/keycloak/blob/25.0.4/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java#L332), that stores any additional request parameters in client session notes, which can then be accessed from a custom protocol mapper.

However, we also need RAR for a client grant type token. But since the [TokenEndpoint](https://github.com/keycloak/keycloak/blob/25.0.4/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java) processing does not store the additional request parameters, we cannot use the custom protocol mapper to achieve RAR in this case.

Therefore, we are requesting that additional request parameters is stored as notes on either the user or client session when processing a client grant type request in order to enable RAR for client grant tokens via a custom protocol mapper.

### Motivation

Among others, [EU digital wallet framework (ARF)](https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md) uses [Cloud Signature Consortium (CSC) API v2](https://cloudsignatureconsortium.org/wp-content/uploads/2023/04/csc-api-v2.0.0.2.pdf), which requires the use of [RAR](https://datatracker.ietf.org/doc/html/rfc9396).

Furthermore, the Japanese government agency [Digital Agency](https://en.wikipedia.org/wiki/Digital_Agency) is standardizing based on CSC v2, meaning they are also closely following eiDAS 2 and ARF.

While it is our impression that Keycloak will eventually fully support RAR per default, this feature request would enable RAR compatibility via a custom protocol mapper in the meantime.

### Details

My implementation idea would be to add something similar to [AuthorizationEndpoint.java#L332](https://github.com/keycloak/keycloak/blob/25.0.4/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java#L332) here: [ClientCredentialsGrantType.java#L130](https://github.com/keycloak/keycloak/blob/25.0.4/services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java#L130)

It would perhaps need a similar method to [extractAdditionalReqParams](https://github.com/keycloak/keycloak/blob/25.0.4/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java#L127), in order not to store all the `formParams` but only the "additional" parameters.

**Comment by sschu** [comment]
If I am not mistaken, there is not ClientSession for Client Credentials Grant anymore. Somebody correct me if I am wrong.
