### ISSUE TITLE
Offline refresh token suppose to work for 30 days but it expire after 7-8 days.

### ISSUE THREAD

**Issue by arunshinde1** [keycloak/keycloak#32480]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Offline refresh token suppose to work for 30 days but it expire after 7-8 days.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

That Offline tokens settings set to 30 days and it should for 30 days. 

### Actual behavior

Offline token expires only after 7 days with stale_token error.

### How to Reproduce?

Create offline refresh token by passing a scope = offline_access in login url and passing session state and code in token api.

Now use this refresh token to get new access token by using token api.

Repeat second step every day to get a new access token.

![Session setting 2](https://github.com/user-attachments/assets/39bf8c25-86d9-4a08-9f08-4fc0a9b58b5a)
![Session setting](https://github.com/user-attachments/assets/73615a38-2643-409b-8f0c-4bd5ce0e51ec)

**Comment by ahus1** [comment]
I see you added a max expiry time of 7000 days, which will have an expiry time beyond year 2038. This is currently not supported in Keycloak. See #11053 for the current issue that track it. Please up-vote that issue. 

In the meantime, reduce the max session time so that is doesn't go beyond 2038. Let me know if this resolves it for you.

**Comment by ahus1** [comment]
... alternatively, disable the option "Offline Session Max Limited", as this would disable the max lifetime and rely on the idle time.
