### ISSUE TITLE
Drag & drop issue with the step order in the Authentication settings of the Admin Console

### ISSUE THREAD

**Issue by jun7343** [keycloak/keycloak#32481]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

![image](https://github.com/user-attachments/assets/385ce335-ed78-4b15-a2d3-9a8e9a71735c)

There is an issue when adding a step in the custom browser Authentication settings of the Admin Console. After duplicating the browser flow and adding a step, it is added at the bottom, but it cannot be dragged and dropped. However, the other steps at the top can be dragged and dropped without any problem.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

When a step is added, it should be possible to change the order of the steps using drag & drop

### Actual behavior

After adding a step, I attempt to drag & drop, but it doesn't move. However, I can drag & drop the other steps at the top.

### How to Reproduce?

1. Navigate to the Authentication tab in the Admin Console.
2. Duplicate the browser flow in the Authentication section.
3. Add a step to the duplicated browser flow.
4. Attempt to drag & drop the added step.

**Comment by a-bocci** [comment]
Hi everyone, this bug is marked as fixed in 25.0.7 but there is no build for 25.0.x after 06, can you please produce a build with this fix?

**Comment by jonkoops** [comment]
There will be no further releases of 25.x, you'll have to upgrade to 26.x if you want to get this fix.

**Comment by neo-escieur** [comment]
Hello, to upgrade from 24.x to 26.x without losing the user session, we need to upgrade to 25.x because it says in the migration guide:
```
To prevent losing user sessions upgrade to Keycloak 25 first and enable the persistent sessions feature as outlined in the migration guide for Keycloak 25.
```
so can you please produce version 25.0.7 ?

**Comment by ahus1** [comment]
@neo-escieur - we do no longer provide updates of 25.x as they are end-of-life. 

You can work around this by installing an existing version of and then directly upgrade to 26.x.

**Comment by neo-escieur** [comment]
@ahus1 - how to directly upgrade to 26.x. without losing the user session ?

**Comment by ahus1** [comment]
> how to directly upgrade to 26.x. without losing the user session ?

@neo-escieur - this is not supported. Note that in a direct update, you will lose regular sessions, but offline sessions will be kept.
