### ISSUE TITLE
Admin console - "Web origins" (CORS policy) setting is not shown for "Service accounts roles" Authentication flow

### ISSUE THREAD

**Issue by borczeangelovbasenetch** [keycloak/keycloak#32489]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

In the Keycloak Admin Console, the “Web origins” (CORS policy) setting is only displayed when the “Standard flow” (AuthorizationCode) authentication flow is activated. However, this setting is not available when only the “Service accounts roles" (Client Credentials Grant) flow is enabled.

![Keycloak admin console](https://github.com/user-attachments/assets/7fdd0d0a-d862-45c3-8958-590106547c63)
![CORS Error](https://github.com/user-attachments/assets/332ad35d-dc8e-4123-9e41-c8ed2b4db203)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

In the Keycloak Admin Console, the “Web origins” setting should be displayed regardless of the authentication flow enabled, including when only the “Service accounts roles” (Client Credentials Grant) flow is activated.

### Actual behavior

In the Keycloak Admin Console, the “Web origins” setting is only displayed when the “Standard flow” (Authorization Code) authentication flow is activated. This setting is not available when only the “Service accounts roles” (Client Credentials Grant) flow is enabled.

### How to Reproduce?

Log in to the Keycloak Admin Console.
Navigate to the Clients section.
Select a client that uses **only** the “Service accounts roles” (Client Credentials Grant) flow.
Check the settings for the client and look for the “Web origins” setting.

**Comment by ssilvert** [comment]
@borczeangelovbasenetch Are you sure this is what you want?  Client Credentials Grant flow is typically done for server-to-server interactions.  So CORS would not be relevant.

**Comment by ssilvert** [comment]
I'm going to close this now as I don't think it's a bug.  But we can reopen if there is a convincing use case.

**Comment by stepex** [comment]
use case is authentication from swagger UI

**Comment by reluxa** [comment]
We have exactly the same use-case as mentioned by @stepex, please reopen the issue.

**Comment by pschichtel** [comment]
@ssilvert as you say "CORS would not be relevant", because any user agent should be able to request tokens for that client, right? So why limit browsers? Though I have to agree, browser would be an unsual case

**Comment by dervagabund** [comment]
fyi - just encountered the same issue - but, you can
1. enable standardflow,
2. set the origin, and 
3. disable it again

=> keycloak will still respect the setting and swagger will work even if standard flow is disabled again
