### ISSUE TITLE
Realm role created does not appear in Users > User details > Role mapping

### ISSUE THREAD

**Issue by gfgomes** [keycloak/keycloak#32496]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

Hi, I'm new to Keycloak, I'm deploying and testing version 25.0.2, I created a test realm, created a user, created a test group, inserted the user in the group. Then I created a realm role and when I went to insert the user in the realm role in role mapping, the realm role does not appear.
![image](https://github.com/user-attachments/assets/317c091e-3bf9-471a-b345-9a1dc2669806)
![image](https://github.com/user-attachments/assets/2f673d25-a8a1-432e-8441-ec060f6e4ede)
![image](https://github.com/user-attachments/assets/eeb19869-7cfd-4ad2-8a26-285d7482ac41)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

I was hoping to create the realm role and assign it to the user in the same realm.

### Actual behavior

I created a realm role and when I went to insert the user in the realm role in role mapping, the realm role does not appear.

### How to Reproduce?

Create a realm, create a group, create a user, insert the user into the group created. Create a realm role, save it, then try inserting the realm role in role mapping on the user you created.

**Comment by gfgomes** [comment]
I'll record the solution, it's not a bug, it's just a filter issue. When you click on the 'Assing role' button in the top right corner, there is a dropdown where you can select 'Client Roles' and 'Realm Roles'. Select 'Realm Roles'.
![image](https://github.com/user-attachments/assets/835aaeaf-9442-42eb-aaf2-8ab6a653cfc2)

**Comment by shawkins** [comment]
Thanks for the follow up @gfgomes, presumably this can be closed.
