### ISSUE TITLE
Auto refresh repeat page keycloak v25 and keycloak angular v15

### ISSUE THREAD

**Issue by tuoiconan93** [keycloak/keycloak#32506]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

i use keycloak 25 , keycloak angular v15 , angular core v17
after login it keeps refreshing , i see it has error in redirect part. keycloak v24 works fine
![image](https://github.com/user-attachments/assets/359bb5cb-c5f2-4800-bbdb-5ecc4073b4da)

### Version

25

### Regression

- [X] The issue is a regression

### Expected behavior

i use keycloak 25 , keycloak angular v15 , angular core v17
after login it keeps refreshing , i see it has error in redirect part. keycloak v24 works fine

### Actual behavior

![image](https://github.com/user-attachments/assets/ec814710-d7be-4ff2-8277-ffcdd70bbab7)

### How to Reproduce?

ok

**Comment by jonkoops** [comment]
Please provide a minimal and reproducible example without any framework-specific code.

**Comment by chornota** [comment]
Have same kind of bug.
page automatically refreshes and uri increses until i have 412 error

**Comment by c0da** [comment]
I’m having the same issue. Starting from version 25, my application gets stuck in an infinite loop after logging in, and the URI begins to grow (as seen in the screenshot)... it seems like an infinite loop. Everything works fine up to Keycloak v24.

**Comment by jonkoops** [comment]
Please report a new issue if you are still experiencing problems. Make sure to test on the latest version of Keycloak (26.0.0 at this time). Ensure your report does not have any third party dependencies and includes step by step instructions on how to reproduce the issue.
