### ISSUE TITLE
Capability to change HTTPS headers to custom values

### ISSUE THREAD

**Issue by luis-miguel-almeida** [keycloak/keycloak#32529]
### Description

Currently I'm deploying keycloak on AWS behind a application load balancer. Using ALB I am not able to enable mTLS on keycloak because ALB passes the certificate with custom amazon headers, e.g. [X-Amzn-Mtls-Clientcert-Leaf](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/mutual-authentication.html). As such I'm forced to authenticate using mTLS at the ALB level which then I'm losing a feature of keycloak.

My only option is to use a reverse proxy.

### Motivation

Easy integration with cloud services

**Comment by jonkoops** [comment]
I don't think this a feature we want to add to Keycloak itself. It is not within the domain of the Keycloak server provide a way to change HTTP headers coming into it into something else, at least not in a user-configurable manner for non-standard HTTP headers. Like you mentioned, this is the role of a proxy, which is a pretty common practice.

@keycloak/cloud-native WDYT?

**Comment by luis-miguel-almeida** [comment]
> I don't think this a feature we want to add to Keycloak itself. It is not within the domain of the Keycloak server provide a way to change HTTP headers coming into it into something else, at least not in a user-configurable manner for non-standard HTTP headers. Like you mentioned, this is the role of a proxy, which is a pretty common practice.
> 
> @keycloak/cloud-native WDYT?

I agree with you, but we would like to use AWS native services, in this case AWS ALB. But I agree with you

**Comment by vmuzikar** [comment]
This seems to be related to https://github.com/keycloak/keycloak/pull/31778.
