### ISSUE TITLE
Fix CSS issues with Login V2

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#32522]
### Description

While Login V2 is functionally complete, we need to manually check all the screens and fix any CSS issues present.

### Discussion

https://docs.google.com/spreadsheets/d/1vKpTelkhU6LgLnU4rTgQ2tjh-HsRwZFiefBSrTGpxl0/edit?gid=0#gid=0

### PRs
- https://github.com/keycloak/keycloak/pull/32536
- https://github.com/keycloak/keycloak/pull/32511
- https://github.com/keycloak/keycloak/pull/32521
- https://github.com/keycloak/keycloak/pull/32661

_No response_

### Motivation

We need to complete this Epic so that Login V2 can be the default for Keycloak 26.

**Comment by ahus1** [comment]
Today I notices that the OTP entry form looks different: The styling of the input fields seems to got lost. And it seems the layout has shifted.

Old: 

![image](https://github.com/user-attachments/assets/757a2beb-173d-41b6-9a5b-8b17991d943a)

New: 

![image](https://github.com/user-attachments/assets/5a3e0b23-13da-4a11-8811-9245bb7ba55f)

**Comment by edewit** [comment]
@ahus1 looks good IMO, not sure if we want to keep the strange restart login button though

**Comment by ahus1** [comment]
The latest changes resolved the styling of the OTP field, so it might be good enough. 

IMHO the seeing the username presented without a label is strange, as well as having the icon to restart the login. I agree that restarting the login is required functionality. 

IMHO it got stranger (worse?) when I compare v1 and v2. I'd be ok to rework the UX of this form in a separate issue if the UI team thinks it is good enough for KC26.

**Comment by edewit** [comment]
@ahus1 it works and that it's now worse then v1 is a matter of opinion

**Comment by ahus1** [comment]
> a matter of opinion

Let's agree on that. I'll leave it to you and the UI team on how you want to continue.

**Comment by edewit** [comment]
restarting the login could be a button next to sign in like this:
![image](https://github.com/user-attachments/assets/0fff75cb-c500-4db7-b0dd-fc4c3bdc1929)
and the username could be a input that is readonly to indicate that this is something that the user already filled out and can't change on this step

**Comment by edewit** [comment]
maybe like this?
![image](https://github.com/user-attachments/assets/85ce419b-e786-4db6-ae39-41261096ae33)

**Comment by ssilvert** [comment]
I'm going to call this Epic completed.  To the extent that there are remaining tasks we can open issues.
