### ISSUE TITLE
realm-management client is created with an empty secret

### ISSUE THREAD

**Issue by pdacostaporto** [keycloak/keycloak#32538]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Whenever I create a new realm, the `realm-management` client is created with an empty client secret. It makes it necessary to "regenerate" the client secret for `realm-management` whenever I create a new realm.

### Version

23.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

The `realm-management` client on the new realm should have a non-empty client secret. 

### Actual behavior

The client secret for `realm-management` is empty and the client can't be used until the client secret is "regenerated".

### How to Reproduce?

Create a new realm on the Admin UI. Select the new realm on the dropdown. Go to 'Clients' page, select the `realm-management` client, then go to the 'Credentials' tab. Watch that the 'Client Secret' field is empty.
![secret](https://github.com/user-attachments/assets/47aea583-87e7-4311-80e4-7ddb1a899634)

**Comment by sschu** [comment]
Furthermore, there is normally no reason for the realm-management client to have a secret. Why would you need one?

**Comment by pdacostaporto** [comment]
The issue still remains on the latest release (version 25.0.4).

> Furthermore, there is normally no reason for the realm-management client to have a secret. Why would you need one?

My application's architecture is quite complex. Realms are dynamic, and they are created and managed programatically through the Keycloak API. This decision was taken before I came to the project, but i can see that the realm-management client is used for some operations.

This worked with earlier versions of Keycloak, and we found it broke after an update.

**Comment by sschu** [comment]
Which former version are you talking about? I tested Keycloak 16 and 19 and none of them created a client secret. I also wouldnt know why, Keycloak doesnt need a secret for this client.

**Comment by pdacostaporto** [comment]
Looks like the last version with the original behaviour is 12.0.4 (the client secret starts creating empty on 13.0.0).

**Comment by sschu** [comment]
Then I would not consider this a bug. Keycloak doesnt need a secret for this client and if you need it, you can add it.
