### ISSUE TITLE
Multiple bugs in the experimental UiTabProvider / UiTabProviderFactory

### ISSUE THREAD

**Issue by MLukman** [keycloak/keycloak#32544]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

There are 4 bugs that are related to the form fields within UiTabProvider / UiTabProviderFactory, with the steps to reproduce them are included in `How to Reproduce` info below:

BUG 1: The value of the form field of type `script` is not captured.
BUG 2: Clicking the `Save` button multipe times inside the custom tab page registers as `onCreate` events until the page is reloaded.
BUG 3: The custom tab page displays error upon reload if there is saved a script field.
BUG 4: Modifying the form fields will not capture the new values of all fields except for string type. 

### Version

25.0.4 (Docker image)

### Regression

- [ ] The issue is a regression

### Expected behavior

BUG 1: The value of the form field of type `script` should be captured.
BUG 2: Clicking the `Save` button multipe times inside the custom tab page should register as `onCreate` event for the first click only, while the subsequent clicks should register as update events.
BUG 3: The custom tab page should not display error upon reload even if there is saved a script field.
BUG 4: Modifying the form fields should capture the new values of all field types. 

### Actual behavior

BUG 1: The value of the form field of type `script` is not captured.
BUG 2: Clicking the `Save` button multipe times inside the custom tab page registers as `onCreate` events until the page is reloaded.
BUG 3: The custom tab page displays error upon reload if there is saved a script field.
BUG 4: Modifying the form fields will not capture the new values of all fields except for string type. 

### How to Reproduce?

1. Download [this TestUiTabProvider.java](https://gist.github.com/MLukman/037490697718faf0c1356d3772e92f3d) and embed it in an empty/existing Keycloak provider codebase with the correct namespace folder path. 
2. Register the full classpath inside `META-INF/services/org.keycloak.services.ui.extend.UiTabProviderFactory`. 
3. Compile the provider as a JAR and put it into Keycloak installation's providers folder and run Keycloak build command with `--features="declarative-ui"` flag.
4. Restart/Start Keycloak with the logging streamed to stdout.
5. Go to the Admin console, navigate to the `Realm settings` page (any realm) and find the custom tab `Test UI Tab`.
6. Enter any values in the form fields and click `Save`.
7. Go to the logging and notice that the "ONCREATE" is displayed along with the field values except for script field is null -- **BUG 1**
8. Return to the admin console, modify the fields and click `Save`.
9. Go to the logging and notice that event is still `ONCREATE` while it should be an update -- **BUG 2**
10. Return to the admin console and refresh the browser (F5).
11.  Notice that the `Test UI Tab` cannot load anymore with errors either `ee.create is not a function` or `k.charCodeAt is not a function` (with more probability to get the former than the latter) -- **BUG 3**
12. Now, go back to the source code for `TestUiTabProvider.java` and remove the lines that define the script field within `getConfigProperties()`. Recompile, re-add and rebuild the provider before restarting the Keycloak installation like steps 3-4 above.
13. Navigate back to the `Test UI Tab` (it should load fine now)
14. Modify the fields and click `Save`.
15. Go to the logging and notice that the event `ONUPDATE` is now correctly detected but only the string field new value is displayed while the list and text fields do not display the new value -- **BUG 4**

### Anything else?

To repeat the reproduction of BUG 1 & BUG 2, just create new realms and repeat the steps in the custom tab there.

**Comment by travispeloton** [comment]
Yep, seeing that its creating multiple instances of `UiTabProviderFactory` in the realm config.

Would there be a way for these UI tab providers to delegate to another provider component, and not persist their own config? It would be nice to have a clear separation of concerns (UI vs actual logic).

**Comment by edewit** [comment]
@MLukman that you don't see a value for the script is, because you have a typo the field is called "sript" but you print out the value of  "script"

so BUG 1 is a bug in your example code
and BUG 4 i can't reproduce:
```
ONUPDATE
String: asat -> changed
List: NORTH -> SOUTH
Text: arstarst -> also changed
Script: // test
localStorage -> // changed as well I hope
```
For the others I have created a PR

**Comment by jonkoops** [comment]
Does this issue also affect Keycloak 22 and 24?

**Comment by edewit** [comment]
@travispeloton what logic do you have in your UI tab provider?

**Comment by edewit** [comment]
@jonkoops I'm not sure it's a experimental feature

**Comment by jonkoops** [comment]
> I'm not sure it's a experimental feature

Good to know, then no backport needed for older versions.

**Comment by travispeloton** [comment]
I'll do some more testing and file a new issue if needed.

`ONCREATE` being called instead of `ONUPDATE` after first populating the UITab (realm) was easy to replicate. There was no JSON config provided for the realm, so the form was initially blank.

**Comment by edewit** [comment]
@travispeloton that is fixed with the attached PR

**Comment by carlosrodovalho** [comment]
I'm having an interface problem with this implementation. It works fine if I update the realm attribute using the administrative interface. When I use the Rest API to update the realm attribute, the new attribute is indeed saved (confirmed checking keycloak's databse), but the data on the input at the administrative interface keeps the old value.
I already tried reloading keycloak, but nothing makes the interface to load the new value from the database.
