### ISSUE TITLE
login_hint not working on username form

### ISSUE THREAD

**Issue by tahvane1** [keycloak/keycloak#32556]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I try to prepopulate username field from url and login_hint is not working. It is working together with kc_idp_hint but for some reason it doesn't get populated to keycloak forms.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

username would get populated

### Actual behavior

empty username field

### How to Reproduce?

add login_hint to login url

**Comment by graziang** [comment]
Hi @tahvane1, from my test auth request with `login_hint` parameter works as expected.
Could you please add a comment with the auth request?

**Comment by tahvane1** [comment]
So when I trigger flow with https://<host>/realms/<realm>/protocol/openid-connect/auth?client_id=<ID>&redirect_uri=<redirect_url>&response_type=code&scope=email%20openid%20profile%20&kc_idp_hint=<hint>&login_hint=<email>
it redirects to idp and prefills email on **idp** form.

However when I leave out kc_idp_hint like
https://<host>/realms/<realm>/protocol/openid-connect/auth?client_id=<ID>&redirect_uri=<redirect_url>&response_type=code&scope=email%20openid%20profile%20&login_hint=<email>

It doesn't fill email on **keycloak** form.

**Comment by graziang** [comment]
Still not able to reproduce the issue, tried on a fresh Keycloak 25.0.4.

**Comment by tahvane1** [comment]
Okay. I am using username (only) form as first step

**Comment by Serge-Evich** [comment]
> Still not able to reproduce the issue, tried on a fresh Keycloak 25.0.4.

Hi, to be able to reproduce you need to turn on organizations in your realm

**Comment by slykar-hpts** [comment]
I can reproduce this as well. I'm on `26.0.2`.

This is my auth flow. When I pass `login_hint` during OIDC flow, the username/email field **is not** populated when at least one Organisation is added.

If Organisations are enabled, but no Organisation is added, the field **is** populated.

![Image](https://github.com/user-attachments/assets/a7b9ff7a-b7f4-4353-8de2-3510468a4526)
