### ISSUE TITLE
Session Identifier Not Updated (Vulnerability issue)

### ISSUE THREAD

**Issue by Amr9190** [keycloak/keycloak#32552]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Dear Team,
Kindly be informed that we have a vulnerability issue with Session Identifier Not Updated,
and we tried to fix it but there is no clear fix for this issue, so please advise.
Issue Description:
Session Identifier Not Updated (Vulnerability issue)
Entity: authenticate (Page)
Risk: It may be possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate
user, allowing the hacker to view or alter user records, and to perform transactions as that user
Fix Recommendation:
Prevent user ability to manipulate session ID. Do not accept session IDs provided by the user's browser at login; always generate a new session
to which the user will log in if successfully authenticated.
Invalidate any existing session identifiers prior to authorizing a new user session.
For platforms such as ASP that do not generate new values for sessionid cookies, utilize a secondary cookie. In this approach, set a secondary
cookie on the user's browser to a random value and set a session variable to the same value. If the session variable and the cookie value ever
don't match, invalidate the session, and force the user to log on again. 
**_how to fix issue of auth session id not change ,before and after login_**

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

We need to fix this issue to regenerate session id after login , or any fix 

### Actual behavior

Dear Team,
Kindly be informed that we have a vulnerability issue with Session Identifier Not Updated,
and we tried to fix it but there is no clear fix for this issue, so please advise.
Issue Description:
Session Identifier Not Updated (Vulnerability issue)
Entity: authenticate (Page)
Risk: It may be possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate
user, allowing the hacker to view or alter user records, and to perform transactions as that user
Fix Recommendation:
Prevent user ability to manipulate session ID. Do not accept session IDs provided by the user's browser at login; always generate a new session
to which the user will log in if successfully authenticated.
Invalidate any existing session identifiers prior to authorizing a new user session.
For platforms such as ASP that do not generate new values for sessionid cookies, utilize a secondary cookie. In this approach, set a secondary
cookie on the user's browser to a random value and set a session variable to the same value. If the session variable and the cookie value ever
don't match, invalidate the session, and force the user to log on again. 

### How to Reproduce?

Dear Team,
Kindly be informed that we have a vulnerability issue with Session Identifier Not Updated,
and we tried to fix it but there is no clear fix for this issue, so please advise.
Issue Description:
Session Identifier Not Updated (Vulnerability issue)
Entity: authenticate (Page)
Risk: It may be possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate
user, allowing the hacker to view or alter user records, and to perform transactions as that user
Fix Recommendation:
Prevent user ability to manipulate session ID. Do not accept session IDs provided by the user's browser at login; always generate a new session
to which the user will log in if successfully authenticated.
Invalidate any existing session identifiers prior to authorizing a new user session.
For platforms such as ASP that do not generate new values for sessionid cookies, utilize a secondary cookie. In this approach, set a secondary
cookie on the user's browser to a random value and set a session variable to the same value. If the session variable and the cookie value ever
don't match, invalidate the session, and force the user to log on again.

**Comment by jonkoops** [comment]
Closing this issue as it is reported for an older version of Keycloak, as outlined in our issue template we only accept issues validated against the latest version of Keycloak. When reporting security vulnerabilities please make sure to follow [our security policy](https://www.keycloak.org/security).
