### ISSUE TITLE
Continuous loading screen instead of access denied on account info page

### ISSUE THREAD

**Issue by sirishkumar** [keycloak/keycloak#32609]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When manage-account role is removed from account client in a realm, on user log in to account console continuous loading screen is displayed.

### Version

25.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

Earlier versions of keycloak(22.0.5) display below message

<img width="497" alt="image" src="https://github.com/user-attachments/assets/1c64aec2-8140-44de-822a-dc0172f6b786">

### Actual behavior

Version 25.0.4 and 24.0.5 instead display continuous loading screen

<img width="500" alt="image" src="https://github.com/user-attachments/assets/f0c35b32-73e4-4546-8bd8-7c6956df5bf6">

### How to Reproduce?

1. Create a realm(int)
2. Remove manage-account under Roles for account client in the realm
3. Create a new user
4. Login to the realm account console(/realms/int/account/)

**Comment by sirishkumar** [comment]
@ssilvert Thank you for taking this up. Does this issue has any impact on functionality of keycloak itself or is just UI regression.

**Comment by edewit** [comment]
@sirishkumar it's "just" a problem with how the error is being handled
