### ISSUE TITLE
Kerberos - Checksum failed

### ISSUE THREAD

**Issue by Arnaud-FELTZ** [keycloak/keycloak#32612]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Hi

Struggling for days now regarding the setup of Kerberos in a Keycloak 25.x docker container.

What I’ve done so far :

 * Creating a custom image installing `krb5-workstation` in my image
 * Mounting an existing (and working) `/etc/krb5.conf` to run container (docker swarm)

However when setting every Kerberos settings to my new Keycloak, it fails flawlessly with error :

>  Debug is  true storeKey true useTicketCache false useKeyTab true doNotPrompt true ticketCache is null isInitiator false KeyTab is /var/kerberos/keycloak/keycloak.keytab_AES refreshKrb5Config is false principal is HTTP/keycloak.contoso.net@CONTOSO.NET tryFirstPass is false useFirstPass is false storePass is false clearPass is false
>  principal is HTTP/keycloak.contoso.net@CONTOSO.NET
>  Will use keytab
>  Commit Succeeded
> 
>  2024-06-11 00:00:07,379 WARN  [org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator] (executor-thread-1) SPNEGO login failed: java.security.PrivilegedActionException: GSSException: Failure unspecified at GSS-API level (Mechanism level: Checksum failed)
>          at java.base/java.security.AccessController.doPrivileged(AccessController.java:716)
>          [...]
>          at java.base/java.lang.Thread.run(Thread.java:840)
>  Caused by: GSSException: Failure unspecified at GSS-API level (Mechanism level: Checksum failed)
>          at java.security.jgss/sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:864)
>          [...]
>          at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
>          ... 25 more
>  Caused by: KrbException: Checksum failed
>          at java.security.jgss/sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType.decrypt(Aes256CtsHmacSha1EType.java:102)
>          [...]
>          at java.security.jgss/sun.security.jgss.krb5.Krb5Context.acceptSecContext(Krb5Context.java:837)
>          ... 35 more
>  Caused by: java.security.GeneralSecurityException: Checksum failed
>  [...]
>  at java.security.jgss/sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType.decrypt(Aes256CtsHmacSha1EType.java:100)
>          ... 41 more
> 
>                  [Krb5LoginModule]: Entering logout
>                  [Krb5LoginModule]: logged out Subject
>  2024-06-11 00:00:07,385 WARN  [org.keycloak.authentication.authenticators.browser.SpnegoAuthenticator] (executor-thread-1) Received kerberos token, but there is no user storage provider that handles kerberos credentials.

I’ve tested my keytab using two methods :

1/ `kinit` & `klist` which seems to work

```sh
bash-5.1$ kinit -v -k -t /var/kerberos/keycloak/keycloak.keytab_AES HTTP/keycloak.contoso.net@CONTOSO.NET
bash-5.1$ klist
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: HTTP/keycloak.contoso.net@CONTOSO.NET

Valid starting       Expires              Service principal
06/11/2024 00:14:47  06/11/2024 10:14:47  krbtgt/CONTOSO.NET@CONTOSO.NET
        renew until 06/18/2024 00:14:47
```

2/ Using a Java piece of code provided in another SO answer but adapted to take Keycloak parameters (to work in same condition):

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import javax.security.auth.Subject;

import com.sun.security.auth.module.Krb5LoginModule;

/**
 * This is simple Java program that tests ability to authenticate 
 * with Kerberos using the JDK implementation.
 * 
 * The program uses no libraries but JDK itself.
 */
public class Krb {

  private void loginImpl(final String propertiesFileName) throws Exception {
    System.out.println("NB: system property to specify the krb5 config: [java.security.krb5.conf]");
    //System.setProperty("java.security.krb5.conf", "/etc/krb5.conf");

    System.out.println(System.getProperty("java.version"));

    System.setProperty("sun.security.krb5.debug", "true");

    final Subject subject = new Subject();

    final Krb5LoginModule krb5LoginModule = new Krb5LoginModule();
    final Map<String,String> optionMap = new HashMap<String,String>();

    if (propertiesFileName == null) {
      //optionMap.put("ticketCache", null);

      optionMap.put("keyTab", "/var/kerberos/keycloak/keycloak.keytab_AES");
      optionMap.put("principal", "HTTP/keycloak.contoso.net@CONTOSO.NET"); // default realm

      optionMap.put("doNotPrompt", "true");
      optionMap.put("refreshKrb5Config", "false");
      optionMap.put("useTicketCache", "false");
      optionMap.put("renewTGT", "false");
      optionMap.put("useKeyTab", "true");
      optionMap.put("storeKey", "true");
      optionMap.put("isInitiator", "false");
      optionMap.put("tryFirstPass", "false");
      optionMap.put("useFirstPass", "false");
      optionMap.put("storePass", "false");
      optionMap.put("clearPass", "false");
    } else {
      File f = new File(propertiesFileName);
      System.out.println("======= loading property file ["+f.getAbsolutePath()+"]");
      Properties p = new Properties();
      InputStream is = new FileInputStream(f);
      try {
        p.load(is);
      } finally {
        is.close();
      }
      optionMap.putAll((Map)p);
    }
    optionMap.put("debug", "true"); // switch on debug of the Java implementation

    krb5LoginModule.initialize(subject, null, new HashMap<String,String>(), optionMap);

    boolean loginOk = krb5LoginModule.login();
    System.out.println("======= login:  " + loginOk);

    boolean commitOk = krb5LoginModule.commit();
    System.out.println("======= commit: " + commitOk);

    System.out.println("======= Subject: " + subject);
  }

  public static void main(String[] args) throws Exception {
    System.out.println("A property file with the login context can be specified as the 1st and the only paramater.");
    final Krb krb = new Krb();
    krb.loginImpl(args.length == 0 ? null : args[0]);
  }
}
```

which results in success:

> [...]
> ======= login:  true
> Commit Succeeded
> 
> ======= commit: true
> ======= Subject: Subject:
>         Principal: HTTP/keycloak.contoso.net@CONTOSO.NET
>         Private Credential: /var/kerberos/keycloak/keycloak.keytab_AES for HTTP/keycloak.contoso.net@CONTOSO.NET

Any help would be much appreciated. Don’t know why it seems to work using 1/ & 2/ but not in keycloak (checksum failed).

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

Kerberos working

### Actual behavior

Checksum failed (see explanation above)

### How to Reproduce?

See explanation above

**Comment by pedroigor** [comment]
@Arnaud-FELTZ Can you please show the output of `klist -kte`? Wondering what are the encryption types of the session keys.

Could you let me know how you created the keytab file?

**Comment by Arnaud-FELTZ** [comment]
@pedroigor : sure.

```sh
bash-5.1$ klist -k /var/kerberos/keycloak/keycloak.keytab_AES -te
Keytab name: FILE:/var/kerberos/keycloak/keycloak.keytab_AES
KVNO Timestamp           Principal
---- ------------------- ------------------------------------------------------
   0 01/01/1970 01:00:00 HTTP/keycloak.CONTOSO.NET@CONTOSO.NET (aes256-cts-hmac-sha1-96)
```

Keytab was generated by someone else, it's pretty standard as he activated all encryptions and I put the same in my config.

**Comment by martin-kanis** [comment]
@Arnaud-FELTZ Do you use Kerberos with LDAP? When I was working on https://github.com/keycloak/keycloak/pull/33632 I saw "Kerberos - Checksum failed" error when I changed `krb5PrincipalName` in LDAP and then I tried to authenticate. 
Also `kinit` from my terminal wasn't working. What helped was updating user's password in LDAP.
Not sure why that helped by maybe it forced to sync everything from LDAP into KDC.

**Comment by minadmins** [comment]
Did you manage to fix it smh?
I'm stuck with the same issue and I couldn't find any useful info

**Comment by Solnijko** [comment]
Did you manage to fix it smh?
I'm stuck with the same issue and I can't find any solutions

**Comment by Arnaud-FELTZ** [comment]
> Did you manage to fix it smh? I'm stuck with the same issue and I can't find any solutions

Fixed it by deploying it to a VM instead of using Docker and worked directly

**Comment by ZAZmaster** [comment]
> Fixed it by deploying it to a VM instead of using Docker and worked directly

Why it doesn't work in docker/k8s? I have same issue with "Checksum failed" in k8s...

**Comment by Arnaud-FELTZ** [comment]
> > Fixed it by deploying it to a VM instead of using Docker and worked directly
> 
> Why it doesn't work in docker/k8s? I have same issue with "Checksum failed" in k8s...

Never managed to make it work, switch on an onprem server install.

**Comment by Nepetrov7** [comment]
> We found that keytab file been incorrect in our case. Regenerate file fixed issue.
> 
> > > > Fixed it by deploying it to a VM instead of using Docker and worked directly
> > > 
> > > 
> > > Why it doesn't work in docker/k8s? I have same issue with "Checksum failed" in k8s...
> > 
> > 
> > Never managed to make it work, switch on an onprem server install.
> 
> We found that keytab file been incorrect in our case. Regenerate file fixed issue. Kerberos autologin work!

What was the problem with keytab file? I have the same problem, but Keytab worked on the previous version of Keycloak...

**Comment by r-buc** [comment]
if someone runs into this issue again:
I noticed ktpass can use a wrong salt, so RC4 works, but AES not.
This was the case at least when running with -setpass.

The easiest way to create a keytab including all SPNs is with msktutil (https://github.com/msktutil/msktutil).
```
$ kinit <accountname>
$ msktutil create --dont-change-password --use-service-account --account-name <accountname> --old-account-password <password>  -k keycloak.keytab
```
