### ISSUE TITLE
addExecutionFlow endpoint does not return right ID

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#32610]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

endpoint POST `/flows/{flowAlias}/executions/flow` to add a flow to an existing flow returns a header with the id of the generated flow, but this ID is not valid

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The ID of the flow to be returned in the header of the request.

### Actual behavior

I'm not sure what is happening, but the ID that is returned is not used in when all the executions of the parent are called

### How to Reproduce?

we can use the keycloak-admin-client to show this:

```js
import KeycloakAdminClient from "@keycloak/keycloak-admin-client";

const client = new KeycloakAdminClient({
    baseUrl: "http://localhost:8080",
    realmName: "master",
  });

await client.auth({
        username: "admin",
        password: "admin",
        grantType: "password",
        clientId: "admin-cli",
      });

await client.authenticationManagement.createFlow({
        alias: "test",
        providerId: "basic-flow",
        description: "",
        topLevel: true,
        builtIn: false,
      });

const { id } = await client.authenticationManagement.addFlowToFlow({
            flow: "test",
            alias: "subFlow",
            description: "",
            provider: "registration-page-form",
            type: "basic-flow",
          });

console.log("flow", id);

const executions =
        await client.authenticationManagement.getExecutions({
          flow: "test",
        });

console.log("not the same", executions.find((e) => e.displayName === "subFlow")?.id)

```

**Comment by mposolda** [comment]
@edewit I've sent the PR with just improving the documentation https://github.com/keycloak/keycloak/pull/33894 .

The thing is, that the endpoint creates 2 entities under the covers:

- Authentication flow, which is subflow of the referenced parent flow
- Authentication execution, which is added to the parent flow and which provides binding between the original parent flow and the new flow

The ID returned in the response is pointing to the new authentication flow. Not to the execution. So I think that something like this may probably work (I did not tried as I was not able to run the admin-client tests as the step `pnpm server:start` from https://github.com/keycloak/keycloak/blob/main/js/libs/keycloak-admin-client/README.md#building-and-running-the-tests fails for me):

```
...
const { id } = await client.authenticationManagement.addFlowToFlow({
            flow: "test",
            alias: "subFlow",
            description: "",
            provider: "registration-page-form",
            type: "basic-flow",
          });

console.log("new flow id", id);

      const flow = await kcAdminClient.authenticationManagement.getFlow({
        flowId: id,
      });

      expect(flow.alias).to.be.eq("subFlow");
```
