### ISSUE TITLE
InvalidDestination Error for IDP-initiated SSO with Keycloak behind a Reverse Proxy

### ISSUE THREAD

**Issue by ManishMehta** [keycloak/keycloak#32622]
👍
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

I have been playing with Keycloak behind an Nginx proxy which terminates TLS. I use Okta as my IDP and have tried both SP-initiated and IDP-initiated modes. I have read some blogs around this, but none talk about this specific setup and error - except for one person who did not provide any solution.

I see that the SP-initiated flow works fine with my setup and the [getExpectedDestination](https://github.com/keycloak/keycloak/blob/d63c0fbd138ab0a27f3bb0833ae92e3211146c5c/services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java#L815) function returns the expected Destination properly with Scheme, host, and port similar to the original URL (before TLS termination - what Okta reaches out to).

However, the for IDP-initiated flow, the same function [getExpectedDestination](https://github.com/keycloak/keycloak/blob/d63c0fbd138ab0a27f3bb0833ae92e3211146c5c/services/src/main/java/org/keycloak/broker/saml/SAMLEndpoint.java#L815) returns the Destination that is "After" the termination (http - not https).

After some tracing of code, I see that the difference between SP and IDP-initiated flows is that the clientId is `null` for SP-initiated flow and therefore the destination is computed with this line of code
```Urls.identityProviderAuthnResponse(session.getContext().getUri().getBaseUri(), providerAlias, realm.getName()).toString();```
However, for IDP-initiated flow, I have a client that I go thru and therefore the clientId is NOT `null` and the destination is computed with the following line of code
```session.getContext().getUri().getAbsolutePath().toString();```

I see that SP-initiated flow works because it is relying on the BaseUri part of the context which is correctly set to the external https URI However, getAbsolutePath() part of the evaluation for IDP-initiated flow returns the 'http' URI.

I think it is a bug in the following line
```session.getContext().getUri().getAbsolutePath().toString();```

The destination is supposed to be built similar to how it is done when `clientId == null`

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The `getExpectedDestination` function should return the URI that is before the proxy (just like it does when clientID is null).
In this case, the URI with HTTPS and port number used before the reverse proxy. 

### Actual behavior

The returned URI uses the scheme and port AFTER the reverse proxy. In my case, it uses HTTP and 80 as the port.

### How to Reproduce?

Put a TLS-terminating reverse proxy (like NGINX) in front of Keycloak and then set up an IDP-initiated SAML flow with a client defined. Then used an external IDP like Okta to connect directly. The destination URI will not match as the external IDP will put the public-facing address (example - https://auth.example.com:8443/realms/myrealm/protocol/saml/clients/myapp-saml) in the SAML assertion as the destination.
During the handling of the SAML response, the code under function `getExpectedDestination` will compute the expected destination URI as `http://auth.example.com/realms/myrealm/protocol/saml/clients/myapp-saml` if you have forwarded the host in NGINX using 
`proxy_set_header HOST            $host;`

You can see some setup steps for IDP-initiated flow in this blog: https://www.lisenet.com/2020/keycloak-with-okta-idp-initiated-sso-login/

**Comment by ManishMehta** [comment]
I saw this issue in the older branch, but the code shows me that the issue is also present in the main branch

**Comment by ManishMehta** [comment]
@jonkoops 
I have a fix that works for me. Let me know if the team would would prefer a Pull Request. If so, please let me know the process. Thanks.

**Comment by jonkoops** [comment]
Pull requests are always appreciated! You can see how to contribute in our [contribution guidelines](https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md). If you have any questions then feel free to reach out here.
