### ISSUE TITLE
RP-Initiated logout using `POST` method fails in cross-origin setup

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#32648]
As part of [the specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) we have implemented the `POST` method of RP-Initiated Logout under #12228, and support for Keycloak JS was added under #25348. However, when the RP (client) is on a different origin than the OP (OpenID Provider) this method fails. The reason for this is that the `POST` endpoint does not set the [`Access-Control-Allow-Origin` CORS header ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin)required for allowing these sorts of requests.

**Steps to reproduce**

I've [set up a little project](https://github.com/jonkoops/kjs-playground) that I use for testing Keycloak and Keycloak JS in cross-origin scenarios which I will use for convenience of reproducing this issue. Follow the steps outlined in the README and then add `logoutMethod: 'POST'` to the options provided to the `init()` call to Keycloak JS in `src/main.ts`.

**Proposed solution**

When calling the `POST` endpoint the `Access-Control-Allow-Origin` header should be added to the response to allow cross-origin requests. Only valid web origins configured for the client should be allowed at any time. There is already [existing code](https://github.com/keycloak/keycloak/blob/557d7e87b2936dc5b1102ffe5376b283af6bab5f/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LoginStatusIframeEndpoint.java#L56-L71) that could be re-used to accomplish this for the login status iframe, which need a similar check.

**Comment by stianst** [comment]
This is not valid. Regardless if GET or POST is used, it should be a redirect, and not called directly from JavaScript. Hence, CORS headers should not be set.
