### ISSUE TITLE
Remove order by guiOrder in the Identity providers admin console page

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#32669]
### Description

After the introduction of pagination for the identity providers, the admin console UI is displaying the IDPs in a confusing way, ordering them by `guiOrder`. This used to work before pagination because all IDPs were retrieved and then ordered, but with pagination the results that come from the DB ordered by alias may not correspond to the `guiOrder` order.

While it should still be possible to set the `guiOrder` using the `Manage display order` screen to control how IDPs are shown during login, the `guiOrder` in the admin console's Identity providers page is not really needed as we have now pagination and search capabilities in place.

**Comment by jonkoops** [comment]
@sguilhen does this warrant a backport perhaps?

**Comment by sguilhen** [comment]
@jonkoops yeah, it might be good to backport this to 22/24. Let me check when the pagination was introduced to see what branches were affected

**Comment by sguilhen** [comment]
Ok, I will try to send the PRs for those later today - thanks for handling 25!

**Comment by sguilhen** [comment]
@jonkoops Got the backport for 24 under https://github.com/keycloak/keycloak/pull/33081. I've checked and we don't need to backport to 22, so I'm updating the labels

**Comment by jonkoops** [comment]
Awesome, thanks for that!
