### ISSUE TITLE
Too many technical details in account UI

### ISSUE THREAD

**Issue by GioviQ** [keycloak/keycloak#32688]
### Description

![Immagine 2024-09-05 094503](https://github.com/user-attachments/assets/780f3425-fe64-4dff-a2f1-e458fde03952)

I think I could write a custome theme to show only what I want, but why in the theme above the end user should see that "Console account"?

### Motivation

To make UI more user friendly

### Details

A flag to hide the Application section would be useful

**Comment by jonkoops** [comment]
This issue does not have the quality or detail to be actionable, if you have a question please use the forums.
