### ISSUE TITLE
Unable to import master realm with --import-realm

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#32689]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Importing the master realm is impossible with --import-realm cli option. The reason of it is that we first falsely initialize master realm and then when trying to import it we skip it because it was already created by the previous initialization.

This situation should be handled by this code: https://github.com/keycloak/keycloak/blob/866101e72e8d45a52980cdab9a121c661df039e7/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L151

and master realm should not be initialized. However, this does not work for `--import-realm` only for import/export actions.

Here is the relevant log:
```
2024-09-05 12:17:43,611 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/bin/../data/import
2024-09-05 12:17:51,461 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
2024-09-05 12:18:02,211 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'master' already exists. Import skipped
2024-09-05 12:18:47,396 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'quarkus' imported
2024-09-05 12:18:48,451 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
```

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

master realm is imported

### Actual behavior

master realm is skipped

### How to Reproduce?

1. Put json with master realm to `data/import/`
[master-realm.json](https://github.com/user-attachments/files/16893491/master-realm.json)
2. Run Keycloak with 
```
./kc.sh start-dev --import-realm
```
3. Check that the master realm does not have `sslRequired: none` 

### Anything else?

This was experienced when running Keycloak in Kubernetes with HTTP (for demo purposes). The admin console is not accessible unless sslRequired is set to none.

**Comment by shawkins** [comment]
@pedroigor @vmuzikar the import command defaults to overriding, but start w/ --import-realm defaults to ignore existing realms without an option for changing that behavior. Do we recommend in this case that users issue the appropriate import command, or should start w/ --import-realm support more behaviors?

**Comment by stianst** [comment]
We would probably have to run the import of the `master` realm before bootstrapping; one trick there is that we could only do that for the `master` realm (which also has a configurable name btw), as other realms should be imported after the master realm has been bootstrapped.

**Comment by jaceblake** [comment]
For now, you can do it like this, if you are using docker-compose
`  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_CONSOLE_OUTPUT: default
      KC_LOG_CONSOLE_COLOR: "true"
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        # master realm cannot be imported using the --import-realm command; therefore, it needs to be updated using the import command beforehand.
        # See also https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup
        ./opt/keycloak/bin/kc.sh import --file=/opt/keycloak/data/import/master-realm.json --override=true --optimized
        ./opt/keycloak/bin/kc.sh start-dev --import-realm --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import`
