### ISSUE TITLE
Make it explicit which options are needed when using optimized image with the Operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#32717]
### Description

Currently, the guide does not explicitly warn the user that when using custom optimized image, some build time options are actually required to be baked in the image.

This probably concerns only health and metrics.

**Comment by Pepo48** [comment]
@vmuzikar I can take this one, since I recently was part of the discussion, in which there was a confusion about the proper configuration.

I think there is even an KB article that was written as a follow-up. I can take a look.

**Comment by vmuzikar** [comment]
@Pepo48 Thank you, it'd be great if you could look into it.

**Comment by shawkins** [comment]
Relates to #25391
