### ISSUE TITLE
Override of Client Session Max does not work

### ISSUE THREAD

**Issue by ElenaLapshyna** [keycloak/keycloak#32720]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The value set in "Client Session Max" in Clients/settings/advanced settings is ignored in terms of invalidation of client session: client session stays active until SSO Session Max

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The client session expired after the time that is set in the client session "Client Session Max" (according to the comment https://github.com/keycloak/keycloak/issues/9896#issuecomment-1695679048)

### Actual behavior

The client session stays active until "SSO Session Max" time, despite "Client Session Max" being less, than "SSO Session Max"

### How to Reproduce?

1. Set realm session settings:
<img width="633" alt="Screenshot 2024-09-06 at 2 00 49 PM" src="https://github.com/user-attachments/assets/c5ac1de8-90e5-4a93-9e1c-ef5cc502b4a7">

2. Set client session settings with less time than SSO session:
<img width="713" alt="Screenshot 2024-09-06 at 2 02 36 PM" src="https://github.com/user-attachments/assets/879c03e4-52ac-40e8-bded-99219eafa4db">

3. Open the incognito browser tab and log in to the application.
4. You can see in the response of API `/realms/{realm_name}/login-actions/authenticate` in Response Headers, Set-Cokie:
```
KEYCLOAK_SESSION="...";Version=1;Path=/realms/avenza/;Max-Age=31536000;Secure;SameSite=None 
```
Max-Age=31536000 == SSO session max time
5. Wait "Client Session Max" + view min and reload the page.
6. The user is still logged in.

**Comment by ahus1** [comment]
There are two concepts in Keycloak: A user session and a client session. 

The user session (also called the SSO = single sign on session) is something stored on the server side which corresponds with a cookie in the browser. This has in your example a long maximum session time, so this is expected.

There are then one or more client sessions connected to a user session, which capture either the OpenID Connect or SAML communication between the client and Keycloak. 

Each of the sessions can have different timeouts: If the user session times out, the user is no longer logged in. If the client session expires, the client need to restart the OpenID Connect or SAML flow. You can see that a client session expires when the client is no longer able to use the refresh token to retrieve an updated access token. 

If you reload the page, this will (assuming a single page application) usually trigger a new OIDC / SAML flow, and this re-creates the client session if it doesn't exist anymore. The user will then not see the login screen again as the user session still exists and the user is still logged in. 

Instead, you might interact with the application and you will eventually see that the refreshing of the token will no longer work, and then (depending on the application) it might redirect to Keycloak to re-initiate the OIDC/SAML flow with the same result as in the previous paragraph: The user is still logged in, and after the redirect a new client session exists. 

Let me know if this resolves it for you.

**Comment by antikalk** [comment]
We are currently facing a similar issue. We want the "normal" application users to have a rather long SSO Session Max setting, but "admin" users that are using the realm specific admin console should not have such a long session lifetime. We tried configuring this with the Client Session Settings, but this doesn't help due to the behavior that @ahus1 mentioned, that even if the admin-console client session expires the user is directly signed in again via the user session.  

Is there any way to achieve this?

**Comment by ahus1** [comment]
@antikalk - are at least two ways that could solve this IMHO. 

(1) You could set up a maximum lifetime for the admin client and then customize the login flow for the admin client:  In the custom flow, remove the cookie authentication. Then Keycloak will always ask for the password when you access the admin client. I tried that locally and it seems to work: Whenever I reload the client using a full browser reload, it now always asks me for the password.

(2) Alternatively something that can be more convenient for your users and more generic, still it would require some clicking (and see the caveat at the end): As before, you would set up a maximum lifetime for the admin client. Then use the step-up login functionality with with "level of authentication" and an associated max-age to ensure that when accessing the admin client, a user has entered their password like within the last 10 seconds before accessing the application. See https://www.keycloak.org/docs/latest/server_admin/#con-advanced-settings_server_administration_guide for the client configuration, and https://www.keycloak.org/docs/latest/server_admin/#_step-up-flow for configuring the flow. 

Caveat for option 2: Please double-check if someone could override this by faking the authentication URL, as the Admin console will AFAIK never check the LoA that's returned after the authentication flow. 

So the first option (a custom authentication flow that disallows cookies) might be just what you need. If you would have a custom client that would be able to check the LoA, the second option might be more interesting.

**Comment by antikalk** [comment]
@ahus1 first of all I would like to thank you for your response! Very much appreciated.

I tried option 1 with removing the `Cookie` step in the Authenticator flow that is used for the admin console. One drawback I could see here, is that this requires the user to authenticate on every page reload and/or opening the admin console. The lifetime of Client Session Idle or Max is not taken into account. Not sure, but could this be related to the `login-status-iframe.html` check that is performed by the admin-console to be dependent on the cookie being checked?

This might not be a bigger issue in our case, as we use an external IDP to authenticate, then basically the session on the IDP signs in the user again. Of course the redirect to the IDP seems *unnecessary* here, as long as the user is within the client session limits. But I can see this being annoying when using username/password authentication for example.

**Comment by ahus1** [comment]
@antikalk - it seems that there is more context to share what you want to achieve from a business point of view / what kind of security concerns you want to mitigate. This is beyond this bug issue. Please create a discussion for this either in GitHub discussions, the forum or the user mailing list.

**Comment by antikalk** [comment]
> @antikalk - it seems that there is more context to share what you want to achieve from a business point of view / what kind of security concerns you want to mitigate. This is beyond this bug issue. Please create a discussion for this either in GitHub discussions, the forum or the user mailing list.

Created a post here: https://keycloak.discourse.group/t/ability-to-configure-a-different-session-lifetime-for-admin-console-users/28141
