### ISSUE TITLE
Forgot Password Function Doesn't Generate Email

### ISSUE THREAD

**Issue by PurposeBuiltFamilies** [keycloak/keycloak#32722]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Forgot Password Function Doesn't Generate Email

### Version

1

### Regression

- [ ] The issue is a regression

### Expected behavior

Should generate an email to user

### Actual behavior

Nothing happens

### How to Reproduce?

Try it

### Anything else?

Needs to be fixed.

**Comment by SebastEnn** [comment]
With this amount of information provided, no one can really help you with this issue.

Which version of Keycloak are you using? ("1" is definitely wrong)
Have you added an email server in your realm?
