### ISSUE TITLE
In the account console when I update the password the referrer dissapears

### ISSUE THREAD

**Issue by cgm-maarten** [keycloak/keycloak#32736]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Using the latest account UI, I see the message "Back to security-admin-console" in the upper right corner which I can click on.

When I navigate to the change password form and change the password.

The link dissappears

### Version

25.0.4

### Regression

- [X] The issue is a regression

### Expected behavior

The referrer link should be persistent when I get to the account ui throughout the session.

### Actual behavior

The referrer link dissappears when I try and enter a new password. (I haven't checked for new otp, and webauthn, but I suspect the behavior could be similar.)

### How to Reproduce?

1. When I go to the account ui with a referrer (client-id) and a valid referrer-url. I get the link back to the application.
2. Then I click account-security/signing-in (I don't see the referrer anymore in the url, I don't know if this is the cause) but I still have the referrer link
3. Then I change the password and submit. Now the referrer link dissappears.

### Anything else?

It seems similar to issue https://github.com/keycloak/keycloak/issues/27622 but this is a level further.

**Comment by ssilvert** [comment]
I have reproduced this.

We need to make sure we send along the referer any time we initiate a required action from the account console.  (We actually call these AIAs - application initiated actions.)

**Comment by cgm-maarten** [comment]
Thank you for the quick fix! I'll be waiting for the next minor release. (Do we know when the next minor will be released? As I see the label backport/25.0. )
