### ISSUE TITLE
KeyCloak Admin Client uses non-standard `@NoCache` annotation which is an issue for Quarkus

### ISSUE THREAD

**Issue by gsmet** [keycloak/keycloak#32731]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

As reported by @famod [here](https://github.com/quarkusio/quarkus/issues/42413), the KeyCloak Admin Client started using the non-standard RESTEasy `@NoCache` application in 25+, which is a problem with Quarkus:

https://github.com/keycloak/keycloak/commit/3fffc5182ebf93225b3da40fce5d945e04155cdf#diff-cfcc9e857008e4393a63a51cada94d238d4aecd610d4742fde9965fa0f4ef754R27

In Quarkus, we can use the KeyCloak Admin Client with RESTEasy but it can also be used with Quarkus REST (which doesn't support the RESTEasy-specific `@NoCache` annotation).

In the KeyCloak Admin Client, only standard JAX-RS features should be used if we want it to work with Quarkus REST.

I'm not entirely sure how `@NoCache` behavior can be implemented on the client wtih standard JAX-RS features but I would expect it to be unnecessary if the server specifies `@NoCache`?

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

KeyCloak should only use standard JAX-RS annotations.

### Actual behavior

KeyCloak uses RESTEasy-specific annotations.

### How to Reproduce?

Running any of these Quarkus tests would lead to a warning about the missing annotation:

- io.quarkus.keycloak.admin.client.reactive.KeycloakAdminClientInjectionDevServicesTest
- io.quarkus.it.keycloak.StaticTenantConfigPolicyEnforcerTest
- io.quarkus.it.keycloak.DynamicTenantConfigPolicyEnforcerTest
- and quarkus:build in the same module as the two ITs above: quarkus-integration-test-keycloak-authorization

### Anything else?

https://github.com/quarkusio/quarkus/issues/42413

**Comment by mabartos** [comment]
@gsmet Thanks for creating this issue. 

@mposolda IMHO, this is a valid issue. The specific annotations should be used only in impls of these resource interfaces (REST API).

**Comment by gsmet** [comment]
@mabartos @stianst glad it was fixed, thanks! Ideally, that's something we would like to be backported in KeyCloak 25 given it's what we use in the LTS.
