### ISSUE TITLE
The endpoint /admin/realms/{{realm}}/groups/{{group-id}}/members potentially fetch all user in database

### ISSUE THREAD

**Issue by newwdles** [keycloak/keycloak#32761]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

The endpoint /admin/realms/{{realm}}/groups/{{group-id}}/members accept three arguments, first, max and briefRepresentation. 
When using "first" to offset the users retrieved, Keycloak fetch all the "first" number of users instead of retrieving the "max" number of user at the "first" offset.

 Looking at the code the problem seems to be in `org.keycloak.storage.UserStorageManager#getGroupMembersStream(org.keycloak.models.RealmModel, org.keycloak.models.GroupModel, java.lang.Integer, java.lang.Integer) `where the overload `org.keycloak.storage.UserStorageManager#query(org.keycloak.storage.UserStorageManager.PaginatedQuery, org.keycloak.models.RealmModel, java.lang.Integer, java.lang.Integer)` is called instead of this one `org.keycloak.storage.UserStorageManager#query(org.keycloak.storage.UserStorageManager.PaginatedQuery, org.keycloak.storage.UserStorageManager.CountQuery, org.keycloak.models.RealmModel, java.lang.Integer, java.lang.Integer)`

This result in the first argument of the query method (the paginated query used to actually retrive the users) being used to count the number of users the provider can provide.

On a large database and an offset big enough this result in an OOM.

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Calling /admin/realms/{{realm}}/groups/{{group-id}}/members with the first argument does not fetch "first" + 1 users in database but instead fetch "max" users at "first" offset

### Actual behavior

Calling /admin/realms/{{realm}}/groups/{{group-id}}/members does return the excepted result but internally fetch the all the "first" users, resulting in OOM with a large "first" offset 

### How to Reproduce?

Start keycloak with a limited amount of memory and a realm with a large number of users. Make a call to /admin/realms/{{realm}}/groups/{{group-id}}/members with the first parameter being set to the number of users in database.
If the number of user is large enough keycloak will OOM, take a very long time.
Activating hibernate SQL logging will show that keycloak retrieve  all users in database

### Anything else?

org.keycloak.storage.UserStorageManager#searchForUserStream calls the correct UserStorageManager#query, maybe getGroupMembersStream should do the same ?

**Comment by sguilhen** [comment]
I agree there's room to improve the efficiency of these methods - accepting the issue. Any contributions to fix these are very welcome!
