### ISSUE TITLE
Deprecate oid4vc Protocol and Integrate OID4VCI Functionality into OpenID Connect

### ISSUE THREAD

**Issue by francis-pouatcha** [keycloak/keycloak#32776]
### Description

This task focuses on the removal of the dedicated oid4vc protocol and the subsequent integration of its core functionalities into the OpenID Connect (OIDC) protocol. This transition aims to streamline the credential issuance process and leverage the existing OIDC infrastructure for enhanced efficiency and consistency.

### Details

* **oid4vc Removal:** The `oid4vc` protocol is successfully deprecated and removed from the system. Any references or dependencies on `oid4vc` are eliminated.
* **OIDC Integration:** The core functionalities of OID4VCI, previously handled by the `oid4vc` protocol, are seamlessly integrated into the OIDC protocol.
* **Functionality Preservation:** Ensure that all existing OID4VCI features and capabilities are preserved and continue to function correctly within the OIDC framework.
* **Backward Compatibility:** Implement necessary measures to ensure backward compatibility for clients or systems that might still be interacting with the `oid4vc` protocol during the deprecation period.
* **Documentation:** Update all relevant documentation to reflect the removal of `oid4vc` and the integration of OID4VCI into OIDC. Provide clear guidance on how to utilize the new OIDC-based approach for credential issuance.

**Comment by francis-pouatcha** [comment]
**I am taking ownership of this ticket now.** 

Ticket dependents on:
- #34762
  - #34798

**Comment by francis-pouatcha** [comment]
### Redesign Suggestion

This proposal suggests a change to how the `credential_issuer` is defined in the  `.well-known/openid-credential-issuer` endpoint. Currently, it differs slightly from the `issuer` in the `.well-known/openid-configuration` endpoint. 

To maintain consistency and elegance, I suggest using the same value for both `issuer` and `credential_issuer`, as this has no impact on the protocol endpoints.  This modification will also align the credential issuance endpoint with the existing OAuth2 protocol URL structure.

**Current Implementation**

Endpoint `<realm-url>/.well-known/openid-configuration`:

  ```
  {
      "issuer": "<realm-url>",
      "token_endpoint": "<realm-url>/protocol/openid-connect/token",
      "jwks_uri": "<realm-url>/protocol/openid-connect/certs"
  }
  ```

Endpoint `<realm-url>/.well-known/openid-credential-issuer`:

  ```
  {
      "credential_issuer": "<realm-url>/",
      "credential_endpoint": "<realm-url>/protocol/oid4vc/credential"
  }
  ```

**Suggested Modification**

Endpoint `<realm-url>/.well-known/openid-credential-issuer`:

  ```
  {
      "credential_issuer": "<realm-url>",
      "credential_endpoint": "<realm-url>/protocol/openid-connect/oid4vci/credential"
  }
  ```

By using `<oauth2-url>/oid4vci` for routing requests to the `OID4VCIssuerEndpoint`, we can clearly delineate the endpoints related to the OID4VCI sub-protocol.

Note that we are using `oid4vcI` instead of `oid4vc`, as we are dealing only with the **issuance** protocol.

This approach will allow us to:

1. Operate both the current client-based implementation of an OID4VC protocol and an upcoming scope-based implementation of an OAuth2 sub-protocol.
2. Smoothly migrate from a client-based to a scope-based implementation.

@wistefan @Captain-P-Goldfish @IngridPuppet @tnorimat WDYT?

**Comment by tnorimat** [comment]
@francis-pouatcha Hello, I agree with your re-desing suggestion. I have one minor comment:

> Note that we are using `oid4vcI` 

might be 

Note that we are using `oid4vci`

**Comment by IngridPuppet** [comment]
I definitely agree with this proposal. In line with the objective to drop the `oid4vc` protocol-based implementation, I agree that it totally makes sense to move related endpoints under a common sub-path behind OIDC.

**Comment by wistefan** [comment]
I agree with the proposal.
