### ISSUE TITLE
[OID4VCI] Migrate Verifiable Credential Definitions from Client Attributes to Realm Level Attributes

### ISSUE THREAD

**Issue by francis-pouatcha** [keycloak/keycloak#32773]
### Description

Currently, verifiable credential definitions are stored as attributes within individual client configurations. This limits their reusability and complicates management when multiple clients require the same credential types.

This issue aims to enhance flexibility and streamline administration by relocating verifiable credential definitions from client-specific attributes to the realm level. This change will enable these definitions to be shared across multiple clients within the same realm, promoting consistency and simplifying maintenance.

**Additional Considerations:**

* Evaluate the impact on existing client configurations and provide a migration path if necessary.
* Consider versioning or other mechanisms to handle potential conflicts or changes in VC definitions over time.
* Explore user interface enhancements to facilitate the creation, management, and assignment of realm-level VC definitions.

**Comment by Ogenbertrand** [comment]
**Implementation Plan**

**Objective:**  
Relocate verifiable credential (VC) definitions from client-specific attributes to the realm level, enabling shared, reusable definitions across multiple clients within the same realm. This approach simplifies administration and promotes consistency.

---

1. **Realm-Level VC Definitions**

   Define credentials at the realm level by adding attributes, for example:
   
   ```json
   {
     "attributes": {
       "vc.IdentityCredential.expiry_in_s": 31536000,
       "vc.IdentityCredential.format": "vc+sd-jwt",
       "vc.IdentityCredential.scope": "identity_credential",
       "vc.IdentityCredential.vct": "https://credentials.example.com/identity_credential",
       "vc.IdentityCredential.claims": "{\"given_name\":{\"display\":[{\"name\":\"Given Name\",\"locale\":\"en\"}]}}",
       "vc.IdentityCredential.proof_types_supported": "{\"jwt\":{\"proof_signing_alg_values_supported\":[\"ES256\"]}}"
     }
   }
   ```

2. **Client Scope Mapping**

   Define a client scope per credential, with scope names matching credential properties like `vc.[CredentialId].scope`. This scope includes protocol mappers required to map user attributes to credential claims:

   ```json
   {
     "name": "identity_credential",
     "description": "Scope for identity credential",
     "protocol": "openid-connect",
     "protocolMappers": [
       {
         "name": "given_name-mapper",
         "protocol": "openid-connect",
         "protocolMapper": "oid4vc-user-attribute-mapper",
         "config": {
           "subjectProperty": "given_name",
           "userAttribute": "firstName"
         }
       }
     ]
   }
   ```

3. **Signer Registration**

   Register a signer per credential format (optionally credential ID), ensuring the provider ID matches the format in `vc.[CredentialId].format`. Example signer configuration:

   ```json
   {
     "id": "sd-jwt-signing_IdentityCredential",
     "name": "sd-jwt-signing-service for IdentityCredential",
     "providerId": "vc+sd-jwt",
     "config": {
       "algorithmType": ["ES256"],
       "hashAlgorithm": ["sha-256"],
       "vcConfigId": ["IdentityCredential"],
       "visibleClaims": ["iat"]
     }
   }
   ```

4. **Considerations:**

   - **Migration Path**: None, as we are modifying an experimental feature.
   - **UI Enhancements**: AdminUI changes are not included in this ticket; the realm configuration will be modified using the admin API.

**Comment by tnorimat** [comment]
@Ogenbertrand Hello, it seems good to me because your proposal aligns with the discussion about OID4VCI in former OAuth SIG meetings.

As for migration path, IMO, it might be acceptable that a user manually deletes the current client attributes and etc., and newly registers proposed realm attributes and etc., but I would like to get comments from others about this point.

**Comment by VinodAnandan** [comment]
With respect to the Migration Path: I believe a manual migration approach would also be acceptable.
