### ISSUE TITLE
Keycloak CI - AuroraDB IT, Could not download Node.js error

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#32796]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Failed with next message
`maven-plugin:1.15.0:install-node-and-pnpm (default) on project keycloak-js-adapter-jar: Could not download Node.js: Could not download https://nodejs.org/dist/v20.17.0/node-v20.17.0-linux-x64.tar.gz: Premature end of Content-Length delimited message body (expected: 46,797,238; received: 4,579,328) -> [Help 1]", "[ERROR] ", "[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.", "[ERROR] Re-run Maven using the -X switch to enable full debug logging.", "[ERROR] ", "[ERROR] For more information about the errors and possible solutions, please read the following articles:", "[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException", "[ERROR] ", "[ERROR] After correcting the problems, you can resume the build with the command", "[ERROR]   mvn <args> -rf :keycloak-js-adapter-jar"]}
2024-09-11T00:38:41.3987029Z 
2024-09-11T00:38:41.3987297Z PLAY RECAP *********************************************************************
2024-09-11T00:38:41.3988037Z 3.81.133.20                : ok=6    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1 `
GHA log: https://github.com/keycloak/keycloak/actions/runs/10802611917/job/29965034630

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by ahus1** [comment]
This is happening on the EC2 instances we spin up for the Antora DB testing. The current caches only exist on the local GitHub runner. 
We might be more stable when we push the local Maven cache to the EC2 machine. The local cache would include the node binary. 
Let's first see how often this fails?!

**Comment by ahus1** [comment]
Didn't hear this one is re-appearing. Closing it.
