### ISSUE TITLE
"Internal server error" in admin console after upgrading to v25.0.2

### ISSUE THREAD

**Issue by angeloudy** [keycloak/keycloak#32791]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After upgrading from 25.0.0 to 25.0.2, I'm getting "internal server error".
<img width="622" alt="Screenshot 2024-09-11 at 2 43 15 pm" src="https://github.com/user-attachments/assets/5a17023b-c1b3-4a12-aa4f-63d945eb16b2">
<img width="1131" alt="Screenshot 2024-09-11 at 2 43 39 pm" src="https://github.com/user-attachments/assets/31e20904-ab39-453e-bbe7-b91b453bc888">

I'm running keycloakx helm chart and I have ingress and tls enabled.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

display admin console properly

### Actual behavior

Blank page with "internal server error"

### How to Reproduce?

Upgrade from 25.0.0 to 25.0.2

### Anything else?

no.

**Comment by jonkoops** [comment]
Try using the latest available patch version instead of an older one. The latest version of Keycloak at time of writing is 25.0.5.

**Comment by angeloudy** [comment]
The issue I had is cause by `jackson-*.jar` that I used. after upgrading them from 2.15 to 2.17, everything worked.
