### ISSUE TITLE
TOTP QR codes broken when realm display name contains colon character

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#32833]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When a user tries to register a TOTP code generator via QR code and the realm display name contains ":" characters, then the generated TOTP QR contains an invalid URI.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

TOTP QR Codes for realms with colon character should still work.

### Actual behavior

TOTP QR code cannot be registered in any authenticator app because the QR code contains a broken URL.

### How to Reproduce?

1) Create a realm with a display name that contains a `:` character
2) Create a user with password
3) Try to register an TOTP code generator by scanning a QR code

The QR code app (e.g. freeotp) will show an error message like "invalid code".

An example for a broken QR code is:
<img width="180" alt="image" src="https://github.com/user-attachments/assets/c32c09ae-1485-4701-a815-feb111a1863f">

The broken otpauth URI looks like: `otpauth://totp/Invalid%3ARealm:tester?secret=MZWDMVLFNJWVCVSDOMYUO6RYKNHDO3KE&digits=6&algorithm=SHA1&issuer=Invalid%3ARealm&period=30`

### Anything else?

The problem is that the realm display name is used as the label for the QR code generator URL. 
If the realm display name contains characters that are not allowed in an URL.

We should ensure that the issuer in the otpauth URL contains no invalid characters like (`:` or `/`). Suggestion replace those characters with a space (`%20`).

**Comment by thomasdarimont** [comment]
This could be backported to KC25, KC24

**Comment by ahus1** [comment]
I read your previous comment that you are volunteering to backport this one. I've added the labels, and will leave it to you to backport this PR when you have the time.
