### ISSUE TITLE
Add client side password policy checks

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#32845]
### Description

In order to make it easier to pick a password we should support checking basic password policies on the client

**Comment by waynemorphic** [comment]
Can password policies be displayed to the user if they have been added by the admin, and can they be checked as each policy is met while the user is entering the password? Something like:
- [x] Minimum Length 8
- [ ] Must contain at least 1 upper case character 

https://github.com/keycloak/keycloak/issues/34856
