### ISSUE TITLE
Admin UI defaults to master realm even without permissions to it

### ISSUE THREAD

**Issue by BreakBB** [keycloak/keycloak#32847]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When logging into the admin UI (`/admin/master/console/`) with a user that has no permissions to view the `master` realm, the user is greeted with a "Network response was not OK." message because `whoami?currentRealm=master` returns a 403 Forbidden.

When then selecting the correct realm in the drop down the UI does not reload/change, while the URL does (`/admin/master/console/#/test`) and clicking "Press here to refresh and continue" the default URL (`/admin/master/console/`) is refreshed, not the one of the just selected realm.

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the UI redirects to the first valid realm and does not fallback/stop to the default `master` realm, when the user does not have access to it.

At least I would expect, that selecting a valid realm in the drop down, refreshes the UI and actually loads the content of the requested realm (not just the navigation bar on the left).

### Actual behavior

See "Describe the bug" ☝🏻 

### How to Reproduce?

1. Create a user that has no access to the `master` realm. For example with a group like this:

```yml
groups:
  - name: user-manager
    clientRoles:
      test-realm:
        - view-users
        - query-users
        - manage-users
        - query-groups
```

2. Log in with that user on `<url>/admin/master/console/`
3. You are greeted with
![image](https://github.com/user-attachments/assets/3234440e-8590-43c4-81f1-69b3ed4b2050)
4. Selecting "test" in the realm drop down and only updates the navigation bar on the left, not the content itself.
5. Clicking "Press here to refresh and continue" redirects back to `<url>/admin/master/console/` which results in 3.

### Anything else?

When directly calling the UI for a valid realm (`/admin/master/console/#/test`), then it works as expected. So as a workaround the users need to bookmark the "correct" URL, instead of the base URL.

**Comment by ssilvert** [comment]
I have reproduced this.

We should be able to use the realm list to find the first valid realm and set it accordingly before we render the rest of the page.

**Comment by edewit** [comment]
I'll just fix it by reset-ing the error page when we do a new request so that the error only happens when you want to show the master realm. Because querying the realms which is paginated to find a realm that we can select even when the realm you logged in from is set sounds a bit hacky

**Comment by BreakBB** [comment]
> I'll just fix it by reset-ing the error page when we do a new request so that the error only happens when you want to show the master realm. Because querying the realms which is paginated to find a realm that we can select even when the realm you logged in from is set sounds a bit hacky

So users will still be greeted with "Network response was not OK. Press here to refresh and continue" and clicking it will refresh the error page and results in nothing.

So in order to move away from the error, they need to select the correct realm in the drop down, then the content will be refreshed and the error is gone?

**Comment by edewit** [comment]
Exactly, it's the best I can do for now, have to think about how to make this nicer

**Comment by BreakBB** [comment]
That workaround will absolutely help, since right now there is no way to fix the issue using the UI 👍🏻 
It's not an ideal/final solution to the underlying issue though.
