### ISSUE TITLE
Get 502 when doing multiple requests to Keycloak Admin API (v25)

### ISSUE THREAD

**Issue by mano-lis** [keycloak/keycloak#32862]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When creating multiple resources policies permissions and scopes (for data fixtures) via admin api in a prod environment, i got some 502 during this initialization process. 

### Version

25

### Regression

- [X] The issue is a regression

### Expected behavior

Get a 200 status code

### Actual behavior

get random 502

### How to Reproduce?

Automate multiple requests to the admin api to create Resources Policies Permissions, scopes etc

### Anything else?

This issue does not happen neither on v24 with the exact same datas nor in dev env in v25.
Keycloak is running on a docker container using bitnami/keycloak image and deployed on kubernetes

**Comment by jonkoops** [comment]
This needs more information to be reproducible.

**Comment by mano-lis** [comment]
The only way to be more precise is to give the detail of our datas fixtures:

We have : 
* 65 Resources
* 245 Scopes
* 120 Permissions
* 18 Users

After deployment a script is responsible to create all of these (the client from our symfony app send requests to the keycloak admin api).
During the execution of this script, we randomly encounter 502 error.
We have the exact same datas and there's no problem using v24. The only way to make it work on v25 is to force a sleep of 200ms between each request. This problem happens exclusively on prod environment (deployed on kubernetes).

  Thank you for your prompt reply. Tell me if I can give you further informations.

**Comment by jonkoops** [comment]
We cannot possibly reproduce this issue from this information, it will be impossible to mimic your production environment. What we need is a step by step reproduction from a clean Keycloak installation on the latest version. Or at the very least a proper stack trace + log of what is happening on your production environment.

**Comment by mano-lis** [comment]
I understand that there's a lack of information in this issue. It's difficult to give you a minimal reproducer as it's a complex stack. 
I'm gonna try to find a way to reproduce this bug in the simplest possible way then I will re open a more clear issue.
Thanks for your time.

**Comment by jonkoops** [comment]
Thank you, it's very much appreciated.
