### ISSUE TITLE
Infinite loading page when try to open "Security Console" without permissions instead of Forbidden page - 403 for serverinfo endpoint

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#32904]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

It is observed after KC v24 version.

When you try to open the Security Console (http://localhost:34568/auth/admin/test/console/) for example, without the required permissions, there is infinite loading screen instead of Forbidden page shown as before:
![image](https://github.com/user-attachments/assets/cded4170-6ba1-44f3-a416-55975f9b87a8)

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Having a "Forbidden" page if the permissions are not correct, similar to before (might be better as well of course):
![image](https://github.com/user-attachments/assets/a53a745f-3a8f-411e-bf95-3eedd546c28d)

### Actual behavior

Infinite loading loop and error in the network trace (403) for serverinfo
![image](https://github.com/user-attachments/assets/cded4170-6ba1-44f3-a416-55975f9b87a8)

### How to Reproduce?

1. Create a realm
2. Create a user, with no permissions (realm-management)
3. Try to open the Security Console for the newly created realm

### Anything else?

The "Security Console" and Account Console for KC 25 and onwards for different than master realms, are leading to the master realm as well:
![image](https://github.com/user-attachments/assets/556b3fb1-d67f-42f4-9cde-81c0ab6cd71d)
instead of leading to the respectful pages, as before:
![image](https://github.com/user-attachments/assets/39fb28b0-ded9-47e2-8e76-15c148a60e66)

**Comment by mpalavrov** [comment]
Hi @ssilvert,
Yes, one of the errors is fixed in the nightly build:
![image](https://github.com/user-attachments/assets/07d783f0-a138-46fa-b0f1-a65bda84c8af)

The other one is still there, so I hope it will be solved as part of https://github.com/keycloak/keycloak/issues/32847.
Best,
Milen

**Comment by ssilvert** [comment]
@mpalavrov This is a duplicate of #32609.

It should be fixed by https://github.com/keycloak/keycloak/pull/32618
