### ISSUE TITLE
Device activity client name translations

### ISSUE THREAD

**Issue by lewsmith** [keycloak/keycloak#32916]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

The client names in the Device Activity / Signed in devices appear to not be being translated correctly using a fresh install, with the account theme, as default, set as Keycloak.v3:

![image](https://github.com/user-attachments/assets/7cf54c23-8294-405f-bbee-b5a4a115fc99)

Other areas, in the account ui, that display client names appear to show okay. Applications for example:

![image](https://github.com/user-attachments/assets/e426b873-3f1f-4f95-b3b1-0bf1db1853bd)

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

To see the clients listed in the device activity correctly translated and match that of the other areas they are displayed. 

### Actual behavior

Clients listed in the device activity showing as untranslated

`${client_account-console}, ${client_security-admin-console}`

### How to Reproduce?

Just install, login as the admin, go to the admin manage account view and look under `Account Security -> Device Activity`

**Comment by ssilvert** [comment]
I have verified this bug.  Thanks for reporting, @lewsmith
