### ISSUE TITLE
Administrator username changed in master realm after configuring email address for SMTP connection test for another realm with "Email as username" enabled

### ISSUE THREAD

**Issue by riccardobellini** [keycloak/keycloak#32915]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After I create a realm and toggle on in the realm settings "Email as username", when I configure the SMTP settings and want to test the connection, I am asked to setup an email address.
![image](https://github.com/user-attachments/assets/099eb893-1849-40cf-ab82-343cd2559fde)

If I click the link to setup an email address, this is the admin user details form before setting it.
![admin-before-email-change](https://github.com/user-attachments/assets/802dd7bc-5128-41ab-b2e0-4f999ef689cb)

After setting the email address, the username of the administrator user in the master realm is also changed to the email address we set for the test.
![image](https://github.com/user-attachments/assets/9142d9eb-05b8-4d88-ad76-674374f6fe76)

and we are not able to login anymore in the administration console using the old username "admin", we have to use the test email address, instead.

It is worth noting that the master realm to which the administrator user belongs does not have the "Email as username" option enabled. So it's really a surprising and confusing behavior.

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The test email should be set only as an email address and should not overwrite the username for the administrator account

### Actual behavior

The administrator account username is also set to the email address and cannot login anymore with the previous credentials

### How to Reproduce?

Tested on Ubuntu 20.04 with a freshly downloaded standalone instance of Keycloak 25.0.5

- Start the instance `bin/kc.sh start-dev`
- Browse to the Keycloak URL
- Configure an administration account (admin) with password
- Log in as administrator
- Create a new realm
- Enable the option "Email as username" in the new realm
- Configure the SMTP settings for the realm and setup an email address to be used for the test
- Log out and try logging back in as the administrator user

**Comment by jonkoops** [comment]
You configured the realm so that the e-mail address is the user name by checking "Email as username", so I am not really sure what you are expecting here. This all seems to be working as intended. If you do not want the admin user to use an e-mail address as a username you should not enable "Email as username".

**Comment by riccardobellini** [comment]
Only the test realm is configured to have "Email as username" enabled, the
master realm has that setting disabled.
I would not expect the administrator username to change as well, given that
the administrator is not even among the users of the realm on which I
enabled that option.

Note that the link of the section that prompts to enter a user name
directly takes the user to the administrator user details page. If you then
try to click on the "Users" section in the navbar, you won't even see the
administrator user because you are working on a different realm from master.

It just seems like an incorrect behaviour, to me, to change the username
for a user in a realm based on a setting of another realm.

Il ven 13 set 2024, 17:34 Jon Koops ***@***.***> ha scritto:
