### ISSUE TITLE
docker image for version 24.0.7

### ISSUE THREAD

**Issue by ymargulis-infinipoint** [keycloak/keycloak#32932]
### Description

Hello,
Docker image quay.io/keycloak/keycloak:24.0.7 not found, can you please build it for those who not yet migrated to version 25+?
Thanks

**Comment by jonkoops** [comment]
24.0.5 was the last version in the 24.x series. The only version actively supported is the latest major, so I'd recommend you upgrade.

**Comment by ymargulis-infinipoint** [comment]
But according to release notes there are additional fixes and security fixes in 24.0.6 and 24.0.7, important things.
https://docs.redhat.com/de/documentation/red_hat_build_of_keycloak/24.0/pdf/release_notes/Red_Hat_build_of_Keycloak-24.0-Release_Notes-en-US.pdf
Tag of 24.0.7 exists, but only docker compilation doesn't.

**Comment by jonkoops** [comment]
That is the Red Hat build of Keycloak, a downstream Keycloak distribution with commercial support. We tag those versions upstream, but we do not spin new supported releases for them.
