### ISSUE TITLE
[OID4VCI] Simplify SD-JWT API usage

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#32955]
### Description

In my opinion the current SD-JWT implementation is a bit to stiff and accepts too many parameters. I would suggest to simplify the approach to make it easier usable. I got an idea of an easier implementation by the SD-JWT implementation from `authlete` and I used it here in our reference implementation:

- https://gitlab.opencode.de/governikus/eudi-wallet-pid-provider-governikus-kg/-/blob/main/eudi-wallet-pid-provider/src/main/java/de/governikus/autent/eudiwallet/keycloak/provider/credentialbuilder/SdJwtCredentialBuilderProvider.java?ref_type=heads

The corresponding signature-service implementation can be found here:

https://gitlab.opencode.de/governikus/eudi-wallet-pid-provider-governikus-kg/-/blob/main/eudi-wallet-pid-provider/src/main/java/de/governikus/autent/eudiwallet/keycloak/provider/signingservices/SdJwtSigningProvider.java?ref_type=heads

**Comment by Awambeng** [comment]
I am currently working on this
