### ISSUE TITLE
[OID4VCI] Create a CredentialBuilderProvider interface

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#32951]
### Description

For the scope-based solution of OID4VCI we will need a `CredentialBuilderProvider` that is capable of building different credential representations based on the provided format in the `CredentialRequest`.

The first implementation of the CredentialBuilder could be done with SD-JWTs like this:

```java
public class SdJwtCredentialBuilder implements CredentialBuilder 
{
    
     public CredentialBody buildCredentialBody(Map<String, Object> claims, UserModel userModel)
     {
        ...
     }
}
```

alternative approach:

```java
public class SdJwtCredentialBuilder implements CredentialBuilder 
{
    
     public CredentialBody buildCredentialBody(ClientScope clientScope, UserModel userModel)
     {
        ...
     }
}
```

The CredentialBuilder should be retrievable by its format from the `CredentialRequest` and thus the `Factory` should get the appropriate `format` assigned as `id` to retrieve it like that:

```java
keycloakSession.getProvider(CredentialBuilder.class, credentialRequest.getFormat());
```

**Comment by IngridPuppet** [comment]
I'm currently working on this ticket.
