### ISSUE TITLE
Reordering custom auth flow executions not working in admin UI or kcadm/api

### ISSUE THREAD

**Issue by furmi7** [keycloak/keycloak#32952]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

It is no longer possible to reorder executions in a custom authentication flow. No errors appear in the log or console.

Previously, the command
`$KCADM create authentication/executions/"$EXECUTION_ID"/raise-priority -r "$REALM_NAME"`
was used to move a specific execution up in the flow, and it worked as expected until upgrading to Keycloak 25.

I also attempted to reorder executions via the admin UI. While the UI reflects the new order temporarily, the backend does not persist the change. Upon reloading the page, the previous order is restored.

### Version

25.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Reordering executions via the UI or kcadm/API should persist the changes in the backend.

### Actual behavior

Reordering executions through either the admin UI or kcadm/API has no effect. The order reverts after a page reload.

### How to Reproduce?

1. Create a custom authentication flow with at least two executions (or copy the default browser flow).
2. Change the order of the executions using the admin UI or kcadm/API.
3. Reload the page and observe that the original order is restored.

**Comment by graziang** [comment]
Hi @furmi7 I'm not able to reproduce the issue. Do you have any errors or exceptions in the server log?
