### ISSUE TITLE
[OID4VCI] Add `oid4vci` scope

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak#32963]
### Description

As discussed in the breakout sessions we need to add - as it was done for OpenID Connect (`openid`) - a new identifier scope `oid4vci` that marks the current authentication-process as `OpenID 4 Verifiable Credential Issuance` process.

**Comment by francis-pouatcha** [comment]
This ticket might be obsolete. @mposolda can you please close the ticket?

**Comment by Captain-P-Goldfish** [comment]
Yes, as discussed in the meeting recently, I do agree
