### ISSUE TITLE
authz endpoints not documented on Keycloak Admin API documentation

### ISSUE THREAD

**Issue by Shiva19908** [keycloak/keycloak#32972]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Below admin Rest Endpoints are not documented in Keycloak REST API documents:
…/admin/realms/{realm}/clients/<client-uuid>/authz/resource-server/policy/role 
…/admin/realms/{realm}/clients/<client-uuid>/authz/resource-server/policy/time 

### Version

25.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Above mentioned endpoints should be found in Admin API documentation here: https://www.keycloak.org/docs-api/25.0.0/rest-api/index.html 

### Actual behavior

Above mentioned endpoints missing from Admin API documentation.

### How to Reproduce?

Check Admin API documentation to find missing endpoints: https://www.keycloak.org/docs-api/25.0.0/rest-api/index.html

**Comment by Ashleycodesseo** [comment]
@sguilhen I can help with your documentation! I'm looking to gain some experience with REST API documentation so please let me know how I can help

**Comment by sguilhen** [comment]
@Ashleycodesseo first of all, apologies for the delayed response. You can check the `PolicyTypeService` and `PolicyResourceService` endpoints - they are missing the OpenAPI annotations. For the former, it extends from `PolicyService`, whose GET method is annotated, but it is missing the `@Extension` annotation at the class level and this must be the reason it is not getting picked up. The latter is missing annotations entirely.

Once you put the OpenAPI metadata, you can build the `services` module to build the rest-api documentation and see what it looks like.

```
mvn -f services/pom.xml -DskipTests -Pjboss-release clean install
```

Then look into the `services/target/apidocs-rest/output` folder for the generated docs.

**Comment by Shiva19908** [comment]
Hi,
We see that the endpoints are now added [Admin API documentation](https://www.keycloak.org/docs-api/latest/rest-api/index.html) and [OpenAPI](https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml). However, they are missing proper tag and summary.
Kind regards,
Shiva
