### ISSUE TITLE
Role descriptions do not wrap in the UI

### ISSUE THREAD

**Issue by giacomoch** [keycloak/keycloak#32992]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

The description column in the user roles does not wrap long descriptions.

![image](https://github.com/user-attachments/assets/034c01f7-01a4-46a0-9e66-897c1d135ce2)

This also happens when assigning roles to users:
![image](https://github.com/user-attachments/assets/96d8d5ed-d7d9-4d32-a037-2a2ef37d2fe1)

### Version

22, 24, 25

### Regression

- [ ] The issue is a regression

### Expected behavior

Descriptions are wrapped into multiple lines and row expanded

### Actual behavior

Descriptions are not wrapped and text is lost / user cannot read it

### How to Reproduce?

Assign a long description to a role

**Comment by giacomoch** [comment]
The issue can also be replicated on Keycloak 24, the top comment has been updated.

**Comment by jonkoops** [comment]
Keycloak 24 is not a supported release. Please test in the latest version of Keycloak.

**Comment by giacomoch** [comment]
This issue still happens running the latest build, 25.0.5:

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/faf90afd-1f74-459e-bfbd-6ff89f3dff36">

**Comment by giacomoch** [comment]
Thank you very much for the fix @edewit!
