### ISSUE TITLE
Defect in Role Deletion: Associated Policies and Permissions Not Deleted in keycloak:25.0.2

### ISSUE THREAD

**Issue by bollven01** [keycloak/keycloak#32996]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When deleting a role in Keycloak, the associated policies and permissions are not removed. This results in orphaned policies and permissions that can cause inconsistencies and potential security issues.

Steps to Reproduce:

1. Log in to the Keycloak Admin Console.
2. Navigate to the Realm where you want to create the role.
3. Go to Roles under the left-hand menu.
4. Create a new role (e.g., test-role).
5. Navigate to Clients select one client, under client ->Authorization
6. Go to Policies and create a new policy (e.g., test-policy) that is associated with test-role.
7. Create Permissions that are linked to this policy.
8. Delete the role

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Expected Behavior:
1. The role should be deleted.
2. All associated policies and permissions should also be deleted.

### Actual behavior

Actual Behavior:
1. The role is deleted.
2. However, the associated policies and permissions remain intact.

### How to Reproduce?

Steps to Reproduce:
1. Log in to the Keycloak Admin Console.
2. Navigate to the Realm where you want to create the role.
3. Go to Roles under the left-hand menu.
4. Create a new role (e.g., test-role).
5. Navigate to Clients select one client, under client ->Authorization
6. Go to Policies and create a new policy (e.g., test-policy) that is associated with test-role.
7. Create Permissions that are linked to this policy.
8. Delete Role
 [Keycloak Issue 25.docx](https://github.com/user-attachments/files/17017181/Keycloak.Issue.25.docx)

**Comment by sguilhen** [comment]
This is expected - deleting all policies a role is used was a bottleneck with serious performance implications in deployments with large number of policies. In these scenarios the policy will remain visible until the next time it is used. During policy evaluation, the role is checked for existence, and upon detecting that the role doesn't exist Keycloak removes the policy that depends on the role.
