### ISSUE TITLE
Defect in Keycloak: Deleting a Role Does Not Delete Associated Policies and Permissions; RBAC Fails When Adding Role to Undeleted Policy

### ISSUE THREAD

**Issue by bollven01** [keycloak/keycloak#32997]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug
When deleting a role in Keycloak, the associated policies and permissions are not removed. Additionally, Role-Based Access Control (RBAC) does not function correctly when adding a new role to a policy that was previously associated with a deleted role but not itself deleted.

Related Bug : Defect in Role Deletion: Associated Policies and Permissions Not Deleted in keycloak:25.0.2 #32996

### Version

keycloak:25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

RBAC Functionality:
Adding a new role to an existing policy should work correctly without any issues.

### Actual behavior

RBAC Functionality:
When adding a new role (test-role-2) to an existing policy (test-policy) that was previously associated with a deleted role, RBAC does not function correctly.

### How to Reproduce?

Log in to the Keycloak Admin Console.
Navigate to the Realm where you want to create the role.
Go to Roles under the left-hand menu.
Create a new role.
Navigate to Clients select one client, under client ->Authorization
Go to Policies and create a new policy  that is associated with test-role.
Create Permissions that are linked to this policy.
Delete the role
Verify that while the role itself is deleted, its associated policies  and permissions remain intact.
Create another new role (e.g., test-role-2).
Attempt to add this new role (test-role-2) to an existing policy (test-policy) which was previously associated with the deleted role (test-role-1).

**Comment by sguilhen** [comment]
I don't see what exactly is not functioning in this scenario. After deleting test-role-1, I go back to the policy, see the policy is still there, but if you click on it the deleted role is not shown anymore. 

After I added a new role I went back to the policy and I  was able to assign the new role, and then I was able to evaluate the permission just fine with the new role. What exactly is broken in this case?

**Comment by pedroigor** [comment]
The behavior @sguilhen described is expected. When removing roles, they are eventually removed from policies when updating them.

The evaluation using a policy that links to an unexistent role will always result in a DENY in this case because the role does not exist.
