### ISSUE TITLE
Delete Client and role's admin event doesn't have representation while other delete entities have the representation

### ISSUE THREAD

**Issue by bmk9727** [keycloak/keycloak#33009]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When we delete client OR Delete role, representation json is NULL While other DELETE operation like delete any resources, policy, permission or scope under client have details in representation json.

### Version

25.0.5(Latest)

### Regression

- [ ] The issue is a regression

### Expected behavior

We should have representation json block to identify what was deleted just like other delete operation. E.g DELETE any Authorization entities like Delete scope or delete resource or delete policy or delete permission those event have proper representation block. 

### Actual behavior

DELETE Client and DELETE Role doesn't have representation json block.

### How to Reproduce?

1. Enable admin event config
2. Create Client and Delete Clinet
3. Check for Delete client event's representation
4. Create Role and Delete role
5. Again check for Delete role event's representation

**DELETE** CLIENT's admin event representation
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/d3356985-225e-4312-b4cb-6b568c1600b2">

**DELETE** Client's authorization scop's admin event representation:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/4c7db215-667b-435f-a695-d2b0b9d2233a">

**DELETE** role's admin event representation:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/6ea4c8d8-27ca-4966-a071-6dc47b1275dd">

**Comment by ssilvert** [comment]
The UI just displays whatever is returned.  In this case, no representation is returned to the UI.

The core team may have a reason why it's not returning a representation for clients and roles.  Or it might just be an oversight.

**Comment by bmk9727** [comment]
Thanks for the revert @ssilvert 

Got your point. Im just curious why in some cases(like DELETE operation like delete any resources, policy, permission or scope under client) it return something while for similar operation other cases(Like delete client OR Delete role) it's not returning anything so that's the main cocern that how for few resource path im getting representation and not getting for others.
Would wait for Core team's response.

Thanks again for adding core team lable.

**Comment by martin-kanis** [comment]
Looking into the code, an object's representation is omitted because when you delete a resource (I checked clients, roles, groups, users) it is not longer available when creating the delete event. 
Preparing the event before removal and publishing it afterwards doesn't work either  because of a strange marshaling error. 
Only way I was able to set representation to a removal event is to create a representation of the resource before removal. 
```
ClientRepresentation representation = ModelToRepresentation.toRepresentation(client, session);
if (new ClientManager(new RealmManager(session)).removeClient(realm, client)) {
    adminEvent.operation(OperationType.DELETE).resourcePath(session.getContext().getUri()).representation(representation).success();
}
```
However, this creates a longer representation of an object than added object event. Not sure if that is a problem.

In any case, I don't think this is a critical issue, therefore I'm setting the priority to normal.

**Comment by bmk9727** [comment]
@martin-kanis 
Thank you so much for taking look into this and sharing your observation.

I'm just surpise why in case of DELETE any authorization entities like resource, scope, policy and permission we have represenation json. It's just adding inconsistency on Admin event tab.(Attached SS-2)

Another reason why one would be intereseted to see in representation because on event we are seeing only ids there is no name in the resource_path so it would be default to understand the event.(Attached SS-1).

======================SS-1=================================================
<img width="1728" alt="Screenshot 2024-09-19 at 11 18 38 AM" src="https://github.com/user-attachments/assets/9c2798e3-4c29-4b9f-9e8c-cb80c1d1d037">




======================SS-2=================================================
<img width="1728" alt="permission delete" src="https://github.com/user-attachments/assets/e8ed9006-8600-4275-b01a-c277e20762fa">

**Comment by bmk9727** [comment]
@martin-kanis any thoughts on this?> https://github.com/keycloak/keycloak/issues/33009#issuecomment-2360044104

**Comment by martin-kanis** [comment]
As there is an interest to provide a fix https://github.com/keycloak/keycloak/discussions/42430, I reopened the issue.
