### ISSUE TITLE
Default search in Keycloak Admin returns 'No users found due to'

### ISSUE THREAD

**Issue by ElenaLapshyna** [keycloak/keycloak#33001]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have ~3 million users in our realm.
Searching for users in Keycloak Admin using the Default Search option always returns no results, with an error popup stating “No users found due to” following by a long blank space. 
![Screenshot 2024-09-16 at 4 52 23 PM](https://github.com/user-attachments/assets/fedd172d-d775-4363-81b6-a9c4a95f842a)

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Best solution: the user is found, b/c he exists in the database.
Another solution: the appropriate error message is displayed.

### Actual behavior

The not understandable error is displayed:
![image-20240729-134146](https://github.com/user-attachments/assets/fd6bac4c-b939-4d07-ab08-8a322ca81af9)

### Precondition: 
- have a big chunk of users in the database (we have more than 3 million)

### Steps to reproduce:

1. Log in to Keycloak admin
2. Go to users and confirm the search mode is Default search
3. Type in a user email that you know exists in this Keycloak realm and hit Enter.

**Comment by ssilvert** [comment]
Need the core team to take a look at this.

**Comment by martin-kanis** [comment]
@ElenaLapshyna Can you share how many Keycloak nodes do you have, and details about CPU/memory resources? It seems your cluster cannot handle the load.
Here are some recommendations regarding CPU and memory resources https://www.keycloak.org/high-availability/concepts-memory-and-cpu-sizing

**Comment by ElenaLapshyna** [comment]
@martin-kanis Thank you for your reply. It looks like you are right; it's a lack of resources issue.

**Comment by ElenaLapshyna** [comment]
lack of resources issue
