### ISSUE TITLE
Incorrect Disclosure Handling in SdJwtVP.of(String) Method

### ISSUE THREAD

**Issue by Ogenbertrand** [keycloak/keycloak#33020]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

There is parsing error in the "SdJwtVP.java"  file when the length of 'disclosureStart' equals 'disclosureEnd'. In this case, the value should be empty, and the assignment should only occur when 'End > Start'. 

https://github.com/keycloak/keycloak/blob/5fe916861df60a8791b14d84474eaa517ca97c81/core/src/main/java/org/keycloak/sdjwt/vp/SdJwtVP.java#L104-L110

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

When "disclosureStart"  equals "disclosureEnd", the value should be empty. The assignment should occur when End > Start.

### Actual behavior

An IllegalArgumentException" is thrown with the misleading error message " ("SD-JWT is malformed, expected to end with " + SdJwt.DELIMITER) ".

### How to Reproduce?

Create an SD-JWT wwithout the delimiter at the end (e.g., "issuer-signed-jwt" instead of "issuer-signed-jwt).

Attempt to parse the SD-JWT using the `SdJwtVp.of()` method.

### Anything else?

I'll send a PR to address the issue.

**Comment by ahus1** [comment]
@francis-pouatcha - This issue touches code you've been creating recently. Can you please have a look at this bug and the related PR? Thanks!

**Comment by Ogenbertrand** [comment]
This is the Link to the PR i created,

https://github.com/keycloak/keycloak/pull/33029
