### ISSUE TITLE
Remove deprecated `setOrCreateChild()` method from Admin Client

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#33021]
The method [has been deprecated](https://github.com/keycloak/keycloak/blame/39577522e0c146be31f45c07fec13fded0bf0cb7/js/libs/keycloak-admin-client/src/resources/groups.ts#L96-L110) for a while and should be removed.

**Comment by estani** [comment]
from the docs:
```
#@deprecated Use `createChildGroup` or `updateChildGroup` instead
```
