### ISSUE TITLE
Font-color is mismatching in dark mode

### ISSUE THREAD

**Issue by triveni-k** [keycloak/keycloak#33053]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

1. set ur system in dark mode.
2. naviagate to login page.
3. login page has white text in white background. 

https://github.com/user-attachments/assets/7f675c22-fa33-4859-b5f3-3691927d43ff

expected: Background should be dark.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

expected: Background should be dark.

### Actual behavior

expected: Background is white.

### How to Reproduce?

1. set ur system in dark mode.
2. naviagate to login page.
3. login page has white text in white background. 

https://github.com/user-attachments/assets/7f675c22-fa33-4859-b5f3-3691927d43ff

expected: Background should be dark.

**Comment by jonkoops** [comment]
This has been fixed for Keycloak 26 under #32484. This might warrant a partial backport, but it's a rather minor issue.
