### ISSUE TITLE
Missing labels in admin/ui in non-master realms after 25.0.2

### ISSUE THREAD

**Issue by mrleblanc101** [keycloak/keycloak#33067]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

After upgrading from `25.0.2` to `25.04` and `25.0.5`, we lost all labels in the admin/ui in every realms except the master realm.

After:
![Screenshot 2024-09-18 at 11 05 48 AM](https://github.com/user-attachments/assets/e94c8a94-e4e2-4d88-810f-1dab94f154b9)

### Version

25.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Before:
![Screenshot 2024-09-18 at 11 07 58 AM](https://github.com/user-attachments/assets/0fcf0c77-1689-4055-9994-a059b7095cd0)

### Actual behavior

In the master realm, label are still present.
But in every other realm, only the label key is shown instead of it's actual value

### How to Reproduce?

Upgrade from 25.0.2 to 25.0.4 or 25.0.5.
Create a new realm

**Comment by mrleblanc101** [comment]
As you can see, this makes the admin ui very hard to use and navigate

**Comment by mrleblanc101** [comment]
I think our theme had some useless "admin" override, I removed them and now the label are shown

**Comment by bramn** [comment]
@mrleblanc101 can you explain which override exactly you removed? 

We are experiencing the same issue, but only when we set the admin theme on a non-master realm to a custom one, while looking at the default Keycloak admin theme.

**Comment by mrleblanc101** [comment]
We had an admin folder in the theme, it was unnecessary and probably used outdated assets

**Comment by bramn** [comment]
Thank you for your reply 😊 We also have an admin folder, but that's because we are using a custom theme for non-master realms. But why would a custom admin theme on a non-master realm interfere with the default admin theme on the master realm? 🤷
