### ISSUE TITLE
Passkeys: Infinite (re-)loading loop on browsers with WebAuthn Conditional UI disabled

### ISSUE THREAD

**Issue by UBaggeler** [keycloak/keycloak#33072]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication/webauthn

### Summary
With the introduction of Webauthn Conditional UI in keycloak (see https://github.com/keycloak/keycloak/pull/24305) an infinite (re-)loading situation was introduced. For any Webauthn/Passkey API error which occurs after the page is loaded, the browser goes into a infinite loop.

### Analysis
Any error occurring when executing `initAuthenticate()` in https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/resources/js/passkeysConditionalAuth.js#L54 is propagated to `returnFailure()`.
This then sets the error to an invisible form-field, which is then POSTed to keycloak. 

```
export function returnFailure(err) {
    document.getElementById("error").value = err;
    document.getElementById("webauth").submit();
}
```

Using this pattern of POSTing back the error causes infinite loops, especially for code paths that are directly executed again after the page has successfully loaded.

### How to fix 
Use a different pattern to show errors (not POSTing back?) or do not execute code path if error is currently displayed (from previous request).

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should not send browser into infinite (re-)loading loop if certain features are not available.

### Actual behavior

Keycloak sends browser into infinite loading loop.

### How to Reproduce?

Install DuckDuckGo browser (for example on macOS or Android) or any other browser that does not yet support Passkey Conditional UI but already exposes `PublicKeyCredential.isConditionalMediationAvailable` as a function.

**Comment by ahus1** [comment]
@tnorimat / @dasniko - This issue was raised for Passkeys, and there is already a PR. Can you please have a look if this is the thing to do for Passkeys?

**Comment by dasniko** [comment]
Technically, LGTM.
But I can't review this in a functional scope, as I don't know what was planned initially with the Webauthn Conditional UI as it was implemented in the first shot and I don't know how the current authenticator _should_ behave in case of an error.
Most likely this can be answered by @tnorimat better.

**Comment by tnorimat** [comment]
Hello,
I will review the PR.

**Comment by tnorimat** [comment]
@ahus1 @dasniko Hello,
It might be better to show a screen with an error message.
However, considering the points that infinite loop should be avoided and a passkey feature is a preview feature, it seems good to me.

**Comment by ahus1** [comment]
@UBaggeler - can you please create PR with the same change against the `release/26.0` branch so we can include this fix in the next patch release? Thanks!

**Comment by jonkoops** [comment]
Backport up under #34101
