### ISSUE TITLE
Resurfacing: Issue in representation json of admin event for AUTHORIZATION_RESOURCE_SERVER while import authz-config json

### ISSUE THREAD

**Issue by bmk9727** [keycloak/keycloak#33092]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Facing Issue in representation json of admin event for AUTHORIZATION_RESOURCE_SERVER while import authz-config json.
Representation json doesn't have details for  "resources": [], "policies": [], "scopes": [] and permission while my authz-config json had few resources,scopes, policies and permission.

[test-authz-config (2).json](https://github.com/user-attachments/files/17054859/test-authz-config.2.json)

<img width="1728" alt="Screenshot 2024-09-19 at 12 17 44 PM" src="https://github.com/user-attachments/assets/8c68a17c-d34d-4b14-b3b2-2936dbc30290">
<img width="1728" alt="Screenshot 2024-09-19 at 12 18 35 PM" src="https://github.com/user-attachments/assets/f2de3ece-32ba-4dbb-8a51-4791eae17d79">

### Version

25.0.5(latest)

### Regression

- [ ] The issue is a regression

### Expected behavior

We should get the details for keys like "resources": [], "policies": [], "scopes": [] and permission while Import a JSON file containing authorization settings for resource server.
[test-authz-config (2).json](https://github.com/user-attachments/files/17054856/test-authz-config.2.json)

### Actual behavior

Not getting information for for keys like "resources": [], "policies": [], "scopes": [] and permission while Import a JSON file containing authorization settings for resource server.

### How to Reproduce?

1. Enable admin events from realm settings.
2. Create new client with enabling Authentication and Authorization.
3. Go to Authorization under newly created client and delete default resource and policy to avoid conflient in import json.
4. Go to Setting under authorization.
5. Click on import and select this file and import[test-authz-config (2).json](https://github.com/user-attachments/files/17054908/test-authz-config.2.json)
6. Go to admin event tab and check the newly added event AUTHORIZATION_RESOURCE_SERVER

**Comment by bmk9727** [comment]
Resurfacing this issue. Thanks in advance.

**Comment by sguilhen** [comment]
Looking at the code it seems intentional as all events generated in the `ResourceServerService` endpoint are based on the endpoint's `ResourceServer` converted to representation, and that representation doesn´t  include policies, scopes, resources, etc.

Now, I can see the case, at least for update and import, to use the incoming representation in the event instead. @pedroigor Do you think it makes sense to include the full rep in the event, at least for update/import?

**Comment by pedroigor** [comment]
The reason why we don't have the data there is that it won't work/scale well for clients with 100s (at the very least) of resources, scopes, policies, etc.

IMO, we should can mark it as a low priority. And I'm not sure how to solve the problem well ...
