### ISSUE TITLE
DNS in KC_DB_URL not resolved during work

### ISSUE THREAD

**Issue by ihard** [keycloak/keycloak#33096]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I use Patroni + Consul for a Postgres cluster. The database is registered in Consul with the DNS name master.db-postgres-keycloak-test.service.consul and TTL 10 seconds
When switching the role from one database node to another, the IP address in DNS changes.
Keycloak stops working with an error in the interface - "An internal server error has occurred"

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Detection of an IP address change in DNS KC_DB_URL and reestablishment of the connection to the database

### Actual behavior

Error in web interface: "An internal server error has occurred"

Logs:
```
{"timestamp":"2024-09-19T11:40:25.941664736+03:00","sequence":46899,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.agroal.pool","level":"WARN","message":"Datasource '<default>': Closing connection in incorrect state VALIDATION","threadName":"agroal-11","threadId":36,"mdc":{},"ndc":"","hostName":"keycloak-test-1","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2024-09-19T11:40:25.942190698+03:00","sequence":46900,"loggerClassName":"io.smallrye.health.HealthLogging_$logger","loggerName":"io.smallrye.health","level":"INFO","message":"SRHCK01001: Reporting health down status: {\"status\":\"DOWN\",\"checks\":[{\"name\":\"Keycloak database connections async health check\",\"status\":\"DOWN\",\"data\":{\"Failing since\":\"2024-09-12 10:59:32,445\"}}]}","threadName":"vert.x-eventloop-thread-0","threadId":46,"mdc":{},"ndc":"","hostName":"keycloak-test-1","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2024-09-19T11:40:27.851512176+03:00","sequence":46901,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.agroal.pool","level":"WARN","message":"Datasource '<default>': Connection to master.db-postgres-keycloak-test.service.consul:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.","threadName":"agroal-11","threadId":36,"mdc":{},"ndc":"","hostName":"keycloak-test-1","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2024-09-19T11:40:27.852119254+03:00","sequence":46902,"loggerClassName":"io.smallrye.health.HealthLogging_$logger","loggerName":"io.smallrye.health","level":"INFO","message":"SRHCK01001: Reporting health down status: {\"status\":\"DOWN\",\"checks\":[{\"name\":\"Keycloak database connections async health check\",\"status\":\"DOWN\",\"data\":{\"Failing since\":\"2024-09-12 10:59:32,445\"}}]}","threadName":"vert.x-eventloop-thread-0","threadId":46,"mdc":{},"ndc":"","hostName":"keycloak-test-1","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2024-09-19T11:40:27.944522424+03:00","sequence":46903,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.agroal.pool","level":"WARN","message":"Datasource '<default>': Connection to master.db-postgres-keycloak-test.service.consul:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.","threadName":"agroal-11","threadId":36,"mdc":{},"ndc":"","hostName":"keycloak-test-1","processName":"QuarkusEntryPoint","processId":1}
{"timestamp":"2024-09-19T11:40:27.944866297+03:00","sequence":46904,"loggerClassName":"io.smallrye.health.HealthLogging_$logger","loggerName":"io.smallrye.health","level":"INFO","message":"SRHCK01001: Reporting health down status: {\"status\":\"DOWN\",\"checks\":[{\"name\":\"Keycloak database connections async health check\",\"status\":\"DOWN\",\"data\":{\"Failing since\":\"2024-09-12 10:59:32,445\"}}]}","threadName":"vert.x-eventloop-thread-0","threadId":46,"mdc":{},"ndc":"","hostName":"keycloak-test-1","processName":"QuarkusEntryPoint","processId":1}
```

### How to Reproduce?

Set KC_DB_URL with dns and change resolve ip

**Comment by jonkoops** [comment]
Can you please provide some more detailed steps to reproduce? Preferably try to exclude as many external components and settings as possible and focus on starting from a clean slate Keycloak installation.

**Comment by shawkins** [comment]
If this is not something that the pg driver can handle on its own, then you will need to configure the connection pool in such a way as to force the flushing of connections when the dns change happens. This is similar to what is happening with https://github.com/keycloak/keycloak/issues/24493

If this is possible, it will likely require quarkus specific customizations that are not yet supported by keycloak.

@barreiro - have you seen this scenario before?

**Comment by ihard** [comment]
@jonkoops, without a service discovery system like consul or kubernetes dns, you can try to repeat this if you use unbound as a dns resolver, for example, with the following setting:
server:
local-zone: "local." static
local-data: "master-db-postgres-keycloak-test.local. 10 IN A 10.200.221.31"

after switching the database, change the IP setting for dns master-db-postgres-keycloak-test.local. to unbound and apply the setting

**Comment by ihard** [comment]
I found a solution without changing the quarkus configuration:
```KC_DB_URL=jdbc:postgresql://master.db-postgres-keycloak-test.service.consul:5432/keycloak?connectTimeout=1&hostRecheckSeconds=2&socketTimeout=600&targetServerType=primary```
