### ISSUE TITLE
Token Exchange response JWT missing sub field

### ISSUE THREAD

**Issue by geNAZt** [keycloak/keycloak#33090]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

Hello,

since we upgraded from 24.0.3 to 25.0.3 we saw problems in our impersonation flows. We use client to client impersonation (between service accounts) and rely on the "sub" claim being present.

When looking into a 24.0 token the "sub" claim is present as described in https://datatracker.ietf.org/doc/html/rfc8693#section-a.1.4 . This claim however is missing from 25.0 onwards.

This is a 24.0 generated token with correct claims:

```json
{
  "exp": 1726722596,
  "iat": 1726722296,
  "jti": "b15091f7-27d8-409b-a31e-dea36e08db2e",
  "iss": "https://auth.dev.pci.paymenttools.net/realms/merchants",
  "aud": [
    "auth.dev.pci.paymenttools.net",
    "account",
    "terminal.4bea6b2f-7f9e-4146-aeef-822f8951c79b;cde/cards.read"
  ],
  "sub": "c3c4b3da-c660-432d-a566-02d86691083b",
  "typ": "Bearer",
  "azp": "submission-generator",
  "session_state": "a316220a-5e21-44cb-88ee-e75af2c97807",
  "realm_access": {
    "roles": [
      "offline_access",
      "default-roles-merchants",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "access:env_dev env:dev permission:cde/cards.read",
  "sid": "a316220a-5e21-44cb-88ee-e75af2c97807"
}
```

This is the 25.0 generated token:

```json
{
  "exp": 1726652043,
  "iat": 1726651743,
  "jti": "0a9f2816-183c-4ab7-a906-a931829ca486",
  "iss": "https://auth.dev.pci.paymenttools.net/realms/merchants",
  "aud": [
    "auth.dev.pci.paymenttools.net",
    "account",
    "terminal.4bea6b2f-7f9e-4146-aeef-822f8951c79b;cde/cards.read"
  ],
  "typ": "Bearer",
  "azp": "submission-generator",
  "sid": "11cb05a4-38f5-4901-b1e6-85c9b10d3385",
  "realm_access": {
    "roles": [
      "offline_access",
      "default-roles-merchants",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "access:env_dev env:dev permission:cde/cards.read"
}
```

### Version

25.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Having a "sub" claim in the access token which was exchanged according to https://datatracker.ietf.org/doc/html/rfc8693#section-a.1.4

### Actual behavior

"sub" claim is completely missing

### How to Reproduce?

Have two clients with service account flags enabled. Allow one to impersonate other and perform a direct naked impersonation as documented https://www.keycloak.org/docs/latest/securing_apps/#direct-naked-impersonation . The resulting access_token has the missing sub claim

**Comment by thomasletsch** [comment]
We encountered the same problem. The bad thing is that Spring Security does not accept the token when this field is missing and refuses to authenticate.

**Comment by graziang** [comment]
Hi @geNAZt, this could be related to changes on the lightweight access token in Keycloak 25. Make sure the client has client scope `basic`. More details [here](https://www.keycloak.org/docs/latest/release_notes/index.html#lightweight-access-token-to-be-even-more-lightweight).

**Comment by geNAZt** [comment]
Yes i saw that but what confuses me is that the document states that this is automatically done to all clients which doesn't seem the case. The client we impersonate into are generated before updates to Keycloak 25 where performed. Is simply adding the scope basic enough? Can I control that this scope is not visible in the token afterwards?

**Comment by graziang** [comment]
The client scope is created and added to all clients when you migrate to Keycloak 25. You can control the visibility of the scope in the access token via the `Include in token scope` switch in the client scope settings.
