### ISSUE TITLE
The "Valid redirect URIs" field is not displayed when the "Standard flow" is unchecked

### ISSUE THREAD

**Issue by rmjstn** [keycloak/keycloak#33095]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Apache Guacamole delegates the authentication to Keycloak via the "Implicit Fow". So I disabled the "Standard Flow".
In the UI if "Standard Flow" is unchecked, the field "Valid redirect URIs" is not displayed.

To resolved the problem, I did it like this in the UI : 
- check the "Standard Fow" box,
- Entering the "Valid redirect URIs",
- uncheck the "Standard Fow" box

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Display the "Valid redirect URIs" field when "Standard flow" is unchecked (mandatory for the "Implicit flow")

### Actual behavior

 "Valid redirect URIs" field is not displayed when "Standard flow" is unchecked

### How to Reproduce?

Uncheck "Standard flow"

**Comment by ssilvert** [comment]
I have reproduced this.

**Comment by jonkoops** [comment]
Does this affect Keycloak 24 and 22 as well?
