### ISSUE TITLE
Redirect_uri doesn't accept parameters

### ISSUE THREAD

**Issue by luxusv** [keycloak/keycloak#33104]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The redirect_uri doesn't support parameters, having a question mark in the redirect_uri also doesn't seem to work.

We have an application that uses the `/sso/login` path for the redirect, which works fine with the initial login. However, when a session is expired and the user needs to login again, it will add parameters to the redirect_uri to get the user to the right page after authentication: `/sso/login?sp=page_to_go_to`. When this is the case, the user will get the message `Invalid parameter: redirect_uri`. I tried the following options that didn't work:

- /sso/login
- /sso/login?*

The following option does work but doesn't feel right:

- /sso/login*

### Version

24, 25, nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

For the user to be able to sign-in without using wildcards in the redirect_uri field

### Actual behavior

The user gets a notification `Invalid parameter: redirect_uri` unless a wildcard is added or the parameters are removed by hand

### How to Reproduce?

Create a client
Set the redirect_uri to a specific path
Try to login: http://localhost:8080/realms/test/protocol/openid-connect/auth?response_type=code&client_id=test-client&redirect_uri=https%3A%2F%2Ftest-app.example.com%2Fsso%2Flogin?path%3Dtesting&login=true&scope=openid

Try to login without parameters: http://localhost:8080/realms/test/protocol/openid-connect/auth?response_type=code&client_id=test-client&redirect_uri=https%3A%2F%2Ftest-app.example.com%2Fsso%2Flogin&login=true&scope=openid

**Comment by rmartinc** [comment]
The `*` in redirect uri is only for the path (for example `https://example.com/sso/*`). If you add the `*` in the parameters it's a plain asterisk, no expansion at all. The OAuth 2.0 specification recommends to use exact string matching for redirect URIs, and in oauth 2.0 exact string matching is enforced. So, in general, do not use any path `*` in production. So don't expect `*` to be used in query parameters.

**Comment by luxusv** [comment]
I don't want to use the `*`, but when I don't add it and there are parameters in the redirect_uri that's provided by the application, then it's not accepted as a valid redirect_uri when I don't add the `*`.

So, as mentioned, `/sso/login` should also work when parameters are added by the application.

**Comment by rmartinc** [comment]
Keycloak does not accept `*` in the query parameters. So you have two options: add the `*` in the path (as you have tried); change the app to not use a redirect with variable query parameters. Note that the OAuth specification do not allow any `*` so by spec you have to follow option 2.

**Comment by luxusv** [comment]
So what is the reason that parameters are not allowed to be added to the redirect_uri by the application. The case where this happens is if a user needs to re-authenticate after a time-out, the user wants to be redirected to the page where they were at, so that path is added to the redirect_uri.

**Comment by rmartinc** [comment]
In general is security thing, recommended by OAuth 2.0 and enforced by OAuth 2.1 (see https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-11#section-10). Using any wildcard `*` for redirect URIs in production is not recommended. Keycloak historically have provided a `*` wildcard for the path (not for the query string as you have detected), but IMHO it was a mistake that generated lot of CVEs and security issues. Personally I would not extend any wildcard functionality for the same reason.

**Comment by luxusv** [comment]
I agree with not extending this functionality, but I didn't expect the query part of the URI to be part of it.

**Comment by rmartinc** [comment]
Thanks @luxusv! I'm closing the issue then.
