### ISSUE TITLE
Fix broken remote tests for operator

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#33110]
These are failing on CI and have been skipped for now. See #33086

**Comment by shawkins** [comment]
Is this is related to the otel test failures / #32490 ?

If so we need to loop in the quarkus team as their fix in 3.14.2 doesn't seem to have worked.

**Comment by jonkoops** [comment]
Seems to be the case, I'll close this as a duplicate.

**Comment by jonkoops** [comment]
Duplicate of #32490
