### ISSUE TITLE
Add Keycloak to the official list of OpenTelemetry integrations

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#33139]
### Description

Keycloak 26 introduces OTEL Tracing support. After it is released, it should be possible to add Keycloak to the [official integrations list](https://opentelemetry.io/ecosystem/integrations/). The process is described [here](https://opentelemetry.io/ecosystem/registry/adding/).

**Comment by mabartos** [comment]
@vmuzikar Will you take care of this? Or should I?

**Comment by vmuzikar** [comment]
@mabartos Feel free to go ahead (given I'm still sick). :)

**Comment by mabartos** [comment]
Closed by: https://github.com/open-telemetry/opentelemetry.io/pull/5498
