### ISSUE TITLE
JSON on message for events

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#33141]
### Description

Keycloak already provides JSON as one of its output formats for logging.
However, event logging (org.keycloak.events) have very structured data on the `message` field that could be sent structured as json.
This would help a lot using the data without further parsing/processing on systems like ELK.

### Motivation

Messages formatted as json would provide searchable data without the need of parsing. Event-logging is very important for most organizations, and this would make things easier when using a central logging solution.

**Comment by shawkins** [comment]
Duplicate of #22348
