### ISSUE TITLE
Add support for X509 client certificate lookup for Envoy

### ISSUE THREAD

**Issue by tsaarni** [keycloak/keycloak#33160]
### Description

I would like to request for built-in support for X509 client certificate lookup for Envoy based proxies.

### Motivation

Envoy has seen widespread adoption, especially in the Kubernetes ecosystem, where it serves as the primary ingress proxy for projects like Istio, Contour, and others.

### Details

In my deployments of Keycloak in Kubernetes, I’m using Istio and Contour as the ingress controller. I want to enable X509 authentication for an OIDC client and configure Keycloak to authenticate the client by retrieving the X509 certificate from the XFCC header.

![image](https://github.com/user-attachments/assets/cb8c3363-2527-4dc5-baa1-8e1826480dc2)

**Comment by ahus1** [comment]
As of https://github.com/keycloak/keycloak/pull/33159#issuecomment-2406984910, there is now a community extension.

**Comment by JefeDavis** [comment]
with the addition of the RFC 9440 provider can this be revisted? I feel that envoy is common enough for implementations that it warrants being included with out-of-the-box configuration instead of requiring a community extention

**Comment by cnwaldron** [comment]
I also would like this to be revisited as Envoy is highly used and with the deprecation of `ingress-nginx` more people will be moving towards other technologies.

**Comment by shawkins** [comment]
Reopened as there are effectively two upvotes and we will shortly be adding support for traefik #46616

**Comment by shawkins** [comment]
@tsaarni would you consider contributing your implementation?

**Comment by tsaarni** [comment]
I reopened my previous PR #33159
