### ISSUE TITLE
Authorization policy voted to PERMIT even though role has no users mapped

### ISSUE THREAD

**Issue by ybizeul** [keycloak/keycloak#33173]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

User is granted access even though the OIDC client has :
- One resource based permission associated to a policy
- This policy associated to one realm role
- That role is not mapped to any user or any group

![image](https://github.com/user-attachments/assets/4979e3a7-e4fc-492b-ac35-030311e2cd73)

### Version

999.0.0-SNAPSHOT

### Regression

- [ ] The issue is a regression

### Expected behavior

The policy based on a role with no users or group mapping should deny access

### Actual behavior

Access is permitted

### How to Reproduce?

- Create a realm role "realm role 1"
- Create a new client and enable Authorization
- Create a new client policy "policy 1", add "realm role 1" role
- Add a new permission "permission 1" on Default Resource, and "policy 1"
- Click Evaluate tab, select a user, and "realm role 1"
- Click Evaluate button

Default Resource is "Permit" and drilling down shows policy 1 voted to PERMIT

**Comment by pedroigor** [comment]
@ybizeul Thanks. That is because the `roles` you set will be added to the token to simulate the user with that role.
