### ISSUE TITLE
Authorization Token not working

### ISSUE THREAD

**Issue by avanmalleghem** [keycloak/keycloak#33185]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I would like to create a basic ClientCredentials flow using keycloack with a specific scope associated with the resource server.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect a success from the request ! If I don't specify any scope, it works so it is definitely linked to the scope. 

### Actual behavior

Response : `{"error":"invalid_scope","error_description":"Invalid scopes: read"}`

### How to Reproduce?

Steps to reproduce:
1. Creation of a Client called 'resource-server' with Authorization enabled.
2. In the Authorization section (Scopes subsection), creation of a scope "read".
3. Creation of a Client called 'client' with "Service accounts roles" enabled.
4. Http request :

```
curl --request POST   --url 'http://localhost:8080/realms/myrealm/protocol/openid-connect/token'   --header 'content-type: application/x-www-form-urlencoded'   --data grant_type=client_credentials   --data client_id=client --data client_secret=xxxxxxxx   --data scope=read
```

### Anything else?

Do I need to create a client scope aswell ? It will work but it seems a bit weird to me...

**Comment by sschu** [comment]
You probably mixed up Authorization Services scopes (https://www.keycloak.org/docs/latest/authorization_services/index.html#_resource_overview) and Client Scopes (https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/roles/client-scope.html). The latter is the one you need so yes, you have to define a client scope.

**Comment by avanmalleghem** [comment]
@sschu thanks for your answer. So I have to create a client scope so that my client can request the correct scope and then I need to create an Authorization Scope so that the resource server can validate it ?

**Comment by sschu** [comment]
You only need the client scope. The authorization services scopes are a different thing.
