### ISSUE TITLE
Update event should be launch after the update is success

### ISSUE THREAD

**Issue by fikrapdso** [keycloak/keycloak#33194]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

On eventListener SPI the event triggered before the update process was successful.
On my cases, the update transaction got rolled back because of pk already exist in DB. For this case, update event not relevant anymore.

What I suggest is to move the event call on this line after the successful commit.
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/account/AccountRestService.java#L156

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

event being trigger after successful commit

### Actual behavior

event still being trigger even after update failure

### How to Reproduce?

make sure you have 2 user (username: A and username: B)
1. create customevent listener SPI (that implement log when .onEvent being called)
2. update the user A username to B (so it triger user already exist).
3. event will still being trigger

**Comment by sguilhen** [comment]
@Fikralaksana Yeah, AFAIK no one was able to put some time into it. I can re-open the issue if you are interested in working on it.
