### ISSUE TITLE
Any one Client role mapping to user/group generating two events on admin events tab.

### ISSUE THREAD

**Issue by bmk9727** [keycloak/keycloak#33195]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

With enabling admin event configuration. When we do any role mapping with client role. We are seeing two events.

1. with REALM_ROLE_MAPPING as resource_type
2. with CLIENT_ROLE_MAPPING as resource_type

Here 2nd event is perfect representation of what one would like to see as audit trail while 1st event with REALM_ROLE_MAPPING and representation json as NULL is bit confusing for the user and wrong as audit trail.
Can someone please help to remove that extra generated event?

I have recorded video and attached for more clarity.

https://github.com/user-attachments/assets/95a9617d-374a-4de9-b553-8efa5e5a96e8

### Version

25.0.6(latest)

### Regression

- [ ] The issue is a regression

### Expected behavior

admin event tab should only have one event with CLIENT_ROLE_MAPPING as resource_type.

### Actual behavior

Admin even tab shows two events. with resource_type CLIENT_ROLE_MAPPING  and REALM_ROLE_MAPPING

### How to Reproduce?

1. Set the admin event enabled configuration.
2. Assign any client role to user.
3. Check the admin event tab
4. you will see 2 new events get created on one client role assignment activity.

**Comment by sguilhen** [comment]
I was able to reproduce the issue - will set the priority as normal, so fix contributions are welcome.

**Comment by venkatesh2090** [comment]
@sguilhen I have made an attempt at fixing this #35162
