### ISSUE TITLE
[Keycloak CI] - Base IT/Forms IT - BrowserButtonsTest.appInitiatedRegistrationWithBackButton

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#33225]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

https://github.com/keycloak/keycloak/actions/runs/10932092913

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by stianst** [comment]
This is a duplicate of https://github.com/keycloak/keycloak/issues/32676
