### ISSUE TITLE
Add tests for the new kcadm `--status` option

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#33240]
### Description

Some tests should be added for the new option that was introduced in https://github.com/keycloak/keycloak/pull/32883.

**Comment by mabartos** [comment]
@keshavprashantdeshpande Are you willing to provide also some test cases for the PR you've sent? https://github.com/keycloak/keycloak/pull/32883

Thanks!

**Comment by keshavprashantdeshpande** [comment]
@mabartos Yes I can send the test cases but where should I add those. Unfortunately I could not find any existing tests in the module (maybe I missed something). If there are no existing tests, should I proceed to write something for this ?

**Comment by vmuzikar** [comment]
@keshavprashantdeshpande The kcadm tests can be found [here](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/cli/admin).

**Comment by keshavprashantdeshpande** [comment]
@vmuzikar I have added the test but the github checks are failing with some weird reason. Can you please guide what might be wrong?
