### ISSUE TITLE
IDP mapper id doesn't get imported from exported realm

### ISSUE THREAD

**Issue by SebastEnn** [keycloak/keycloak#33245]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

When using the import functionality, both via command line and admin console, keycloak doesn't use the id specified in the "identityProviderMappers"-entry but instead generates a new one.

### Version

25.0.4, 25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

The imported idp mapper has the same id as specified in the imported realm config.

### Actual behavior

The idp mapper got a new id generated, ignoring the id given.

### How to Reproduce?

- Create a new realm
- Create a new idp with random values for the required fields
- Create a new mapper and give it a random name
- Export the realm (no clients, groups or roles have to be included)
- Delete the realm or switch to another keycloak instance
- Import the realm
- Navigate to the idp mapper and compare its id with the one in the realm export

**Comment by sguilhen** [comment]
Can't reproduce the issue in main (nightly) - exporting and re-importing the realm is preserving the IDP mapper ids just fine. Tried both `kc.sh import --file myexport.json` and also via admin UI, new realm -> import from JSON. In both cases the ids were preserved.

**Comment by SebastEnn** [comment]
I tried to reproduce the bug with the newly released version 26.0.0 and the bug is gone.

It seems like someone has already fixed it before I created this issue.
