### ISSUE TITLE
Executing CustomKeycloakTask collects the statements twice

### ISSUE THREAD

**Issue by gbtec-valerierinke** [keycloak/keycloak#33242]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I added a `CustomKeycloakTask` for adding as described here https://www.keycloak.org/docs/latest/upgrading/index.html#using-older-javascript-adapter
I added the necessary InsertStatements to the `List<SqlStatement> statements`  implemented in the CustomKeycloakTask.
After running the migration I faced the problem that the protocol mappers were added twice.

My inverstigation so far:

- The overridden method `generateStatementsImpl` are called from `CustomKeycloakTask.generateStatements` method.

- The liquibase class ChangeSet.execute call `database.executeStatements(change, databaseChangeLog, sqlVisitors); `. This again calls the generateStatements from `CustomKeycloakTask` and therefore also `generateStatementsImpl`.

Hint: I check that also for existing migration form keycloak itself with the same result. But for idempotent statements like delete or update this is not an issue, only for insert statements.

### Version

25.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

Statements are added only once

### Actual behavior

Statements are added twice

### How to Reproduce?

Add a simple `CustomKeycloakTask` like this

```
import org.keycloak.connections.jpa.updater.liquibase.custom.CustomKeycloakTask;
import org.keycloak.models.utils.KeycloakModelUtils;
import org.keycloak.protocol.oidc.mappers.NonceBackwardsCompatibleMapper;

import liquibase.statement.core.InsertStatement;

public class StatementsAddedTwiceIssue extends CustomKeycloakTask {

    @Override
    protected void generateStatementsImpl() {
        InsertStatement insertStatement = new InsertStatement(null, "keycloak", "protocol_mapper");
        insertStatement.addColumnValue("id", KeycloakModelUtils.generateId());
        insertStatement.addColumnValue("name", "nonce");
        insertStatement.addColumnValue("protocol", "openid-connect");
        insertStatement.addColumnValue("protocol_mapper_name", NonceBackwardsCompatibleMapper.PROVIDER_ID);
        statements.add(insertStatement);
    }

    @Override
    protected String getTaskId() {
        return "Just a test";
    }
}
```

**Comment by pedroigor** [comment]
Keycloak itself has quite a few "custom liquibase tasks" to migrate the database. Can you elaborate more about why you need to have your own migration tasks?

**Comment by gbtec-valerierinke** [comment]
As I already wrote, I had to add a migration for existing realms to add the protocol mapper as you described in the upgrade guide (https://www.keycloak.org/docs/latest/upgrading/index.html#using-older-javascript-adapter). 
Background: We have an old frontend component that is not compatible with the latest keycloak-js version. Therefore we need to deal with an older javascript adapter and need to add the protocol mapper.

We started the mirgation from version 20.0.3. I haven't checked an intermediate version to see when this breaks.

**Comment by sguilhen** [comment]
How exactly are you running this custom task? I've tested here and every custom task we have is executed exactly once, either using an empty DB or during migration from a previous version with an established DB in place.

**Comment by gbtec-valerierinke** [comment]
Please add a breakpoint to the keycloak default migration `org.keycloak.connections.jpa.updater.liquibase.custom.JpaUpdate25_0_0_ConsentConstraints` in line 26 and  start debugging the migration. You will see that the method ` gerenateStatementsImpl` will be called twice.
 
1.
![image](https://github.com/user-attachments/assets/150af71b-e742-4b34-bc43-ece4f4970c4d)

2. 
![image](https://github.com/user-attachments/assets/04125172-1530-4c7f-ba54-22456703d428)

You can see, that the statements now contains the sql statements from the custom task `org.keycloak.connections.jpa.updater.liquibase.custom.JpaUpdate25_0_0_ConsentConstraints` twice.

**Comment by sguilhen** [comment]
@gbtec-valerierinke I see it now with Keycloak 25 - I was testing with main (now released as 26). With 25 the statements were indeed executed twice, but it no longer happens. There were some minor changes in the `CustomKeycloakTask` and a Liquibase upgrade for 26. Not sure if this was a liquibase issue, but it seems to be fixed now.

**Comment by gbtec-valerierinke** [comment]
I retest it with version 26.0.0 and I also can not reproduce it anymore. Thanks for helping!

**Comment by sguilhen** [comment]
Thanks for confirming, @gbtec-valerierinke !
