### ISSUE TITLE
Admin (or account) console does not load with Firefox 102

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#33267]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I tried on RHEL 9 with Firefox 102 to load the admin console, I saw the screen "Loading admin console" with no progress and with the javascript error as mentioned in this screenshot

![Screenshot from 2024-09-25 10-01-02](https://github.com/user-attachments/assets/4875e13d-f119-4eb3-b922-2071aba90f9c)

The same applies to the account console.

After upgrade to Firefox 128, I did not see this anymore.

I am not sure what is the minimum Firefox version, which we support. So not really sure about priority of this (if any). But since it applies to the account console, it affects the end-users, which can likely have older browser versions thought...

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin and account console loads even with older Firefox version (Firefox 102)

### Actual behavior

Admin and account console does not load with older Firefox version (Firefox 102)

### How to Reproduce?

See the description

**Comment by jonkoops** [comment]
The problem is likely that `resourceCommonUrl` used in the template does not start with the right specifier as outlined in the error message. Probably only later versions of Firefox added support for fully qualified URLs in an import map.

**Comment by jonkoops** [comment]
As for browser support, we don't have an official definition, but we have unofficially been at least supporting:

- Latest two major versions of 'evergreen' browsers (Chrome, Firefox)
- Latest two minor versions of Safari (e.g. 18.0 and 17.6)
- All active Extended Support Release (ESR) versions of Firefox

The ESR version used in this issue report is 102, [which is EOL](https://endoflife.date/firefox). So I think we can safely close this issue. That said, we should probably formalize browser support at some point.

**Comment by mposolda** [comment]
@jonkoops Thanks for the clarification. I am closing this then.
