### ISSUE TITLE
Icons for social providers broken in login screen if the provider is created with non-default alias

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#33282]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I create a social provider (for example, instagram), and use the default alias (in this case instagram), the login screens render the instagram icon just fine. However, if I create the provider with a different alias (e.g. myorg-instagram), the login screens show a somewhat broken icon.

- Example with default alias (instagram):

![Screenshot from 2024-09-25 14-56-10](https://github.com/user-attachments/assets/0e0441ba-7c0a-485e-814d-f94ea3342ec4)

- Example with changed alias (myorg-instagram):

![Screenshot from 2024-09-25 14-57-46](https://github.com/user-attachments/assets/c19f7c8a-df6d-4cdc-8a96-3b3a68711faf)

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Social provider icon should be displayed regardless of the alias used when it is created

### Actual behavior

If the social provider alias is changed from the default value during creation, the icon is not displayed correctly

### How to Reproduce?

- Create a social provider (e.g. instagram) with an alias different from the default one (e.g. my-instagram)
- Go to the account console and check the login screen: the icon is broken

**Comment by jonkoops** [comment]
This might possibly be resolved at the same time as #33054?

**Comment by jonkoops** [comment]
@edewit this seems important enough to warrant a backport, I am adding the label for it.

**Comment by ssilvert** [comment]
Backport to 26.0 not needed.
