### ISSUE TITLE
REST Library name revealed in HTTP Response of keycloak

### ISSUE THREAD

**Issue by naumanahmedkhan** [keycloak/keycloak#33299]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/fine-grained-permissions

### Describe the bug

Keycloak error response exposes name of 3rd party library (RESTEASY) being used in keycloak. For example for the endpoint "https://localhost:8444/auth/admin/master/console/userinfo" keycloak logs are 

{“error”:“RESTEASY003210: Could not find resource for full path: https://localhost:8444/auth/admin/master/console/userinfo”}

There are several endpoints affected by this issue as well. Displaying information of software used in the code at server side could allow an attacker to determine which vulnerabilities are present in the software.

### Version

22.0.5, 26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Name of the software used in the server side must not be logged.

### Actual behavior

Displaying information of software used in the code at server side could allow an attacker to determine which vulnerabilities are present in the software.

### How to Reproduce?

Access the endpoint /auth/admin/master/console/userinfo with no information present  so keycloak will log a error message with the software name.

**Comment by stianst** [comment]
Any request to a non-existing path leads to this error message

**Comment by pedroigor** [comment]
@stianst I remember we fixed this and I can not reproduce the problem anymore when sending GET or POST requests to known and unknown endpoints.

Can you please describe how you manage to reproduce the problem?

**Comment by stianst** [comment]
Yeah, you're right. I think I might have tried an old release by mistake as I can't reproduce in 26 now.
