### ISSUE TITLE
Regex authorization policies only check the first value in a multi-valued claim

### ISSUE THREAD

**Issue by PaulBujor** [keycloak/keycloak#33293]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

When using a regex policy on a multi-valued claim, only the first value will be taken in consideration for the decision.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Regex policy will look through all values in a multi-valued when making a decision.

### Actual behavior

Regex policy will make a decision based only on the first value.

### How to Reproduce?

Have the following group structure (as long as the non-admins group comes first in the claims this is reproducible):
- /abc
- /zzz/admins

Add the same user to both groups.

Have client that maps the group memberships to the token, with claim name `groups`.

Create a regex authorization policy with the following pattern: `.*(/admins)` on the `groups` claim. Also create what is required to evaluate (scope, resource, permissions). Evaluating the policy for the user in both groups should come back negative.

### Anything else?

To me it looks like the issue is in the [RegexPolicyProvider](https://github.com/keycloak/keycloak/blob/main/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/regex/RegexPolicyProvider.java), which only takes the first value of a claim in `resolveSimpleValue`. I found an old discussion where this was mentioned: https://keycloak.discourse.group/t/regex-policy-based-on-multivalued-attribute/25153

**Comment by pedroigor** [comment]
You're right, only a single value is expected by that policy. If you are able to contribute with a fix, please let me know.

**Comment by PaulBujor** [comment]
I'd love to give it a try, but can't guarantee it will be done in a timely manner. 

I can start sometime these days and post a message here if I give up, if that's okay?
