### ISSUE TITLE
After restarting external Infinispan, SSO with persisted online user sessions is not possible

### ISSUE THREAD

**Issue by y-tabata** [keycloak/keycloak#33290]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

This issue is related to this enhancement https://github.com/keycloak/keycloak/issues/27976. @ahus1
We briefly checked the operation of Persisting online sessions with Infinispan in-memory cache and Infinispan remote store.
Only (2) of [2] was contrary to our expectations.
I wonder whether this should be a bug report or an enhancement request.
Do we need a mechanism for online sessions similar to the lazy loading of offline sessions?

Keycloak version: 25.0.4
Infinispan version: 15.07

[1] In-memory cache Infinispan
(1) Restart Keycloak
  1. User login
  2. Restart Keycloak
  3. Login with the same user
        -> Session information was restored and logged in with SSO.

[2] Remote store Infinispan
(1) Restart Keycloak
  1. User login
        -> Session information is also cached on the Infinispan Server.
  2. Restart Keycloak
  3. Login with the same user
        -> Session information was restored and logged in with SSO.
           The session information stored on the Infinispan Server remains unchanged.
           However, it is unclear whether the session information was restored from the DB and used, or obtained from the Infinispan Server.

(2) Restart the Infinispan Server
  1. User login
        -> Session information is also cached on the Infinispan Server.
  2. Restart the Infinispan Server
        -> The Infinispan Server cache is empty. It looks like session information remains in Keycloak.
  3. Login with the same user
        -> **SSO does not work, and the login screen appears again.**
           After logging in, user session information is stored in both Keycloak and the Infinispan Server.

(3) Restart both Keycloak and Infinispan
  1. User login
       -> Session information is also cached on the Infinispan Server.
  2. Restart both Keycloak and Infinispan (the order of stopping and restarting does not seem to matter)
        -> The Infinispan Server cache is empty.
  3. Login with the same user
        -> Session information is restored, and I logged in with SSO.
           Session information is also cached on the Infinispan Server.
           This means that session information has been restored from the DB.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

[2] Remote store Infinispan
(2) Restart the Infinispan Server
  1. User login
        -> Session information is also cached on the Infinispan Server.
  2. Restart the Infinispan Server
        -> The Infinispan Server cache is empty. It looks like session information remains in Keycloak.
  3. Login with the same user
        -> **Session information was restored and logged in with SSO.**
           After logging in, user session information is stored in both Keycloak and the Infinispan Server.

### Actual behavior

[2] Remote store Infinispan
(2) Restart the Infinispan Server
  1. User login
        -> Session information is also cached on the Infinispan Server.
  2. Restart the Infinispan Server
        -> The Infinispan Server cache is empty. It looks like session information remains in Keycloak.
  3. Login with the same user
        -> **SSO does not work, and the login screen appears again.**
           After logging in, user session information is stored in both Keycloak and the Infinispan Server.

### How to Reproduce?

See "Describe the bug".

**Comment by pruivo** [comment]
@y-tabata So far, I'm unable to reproduce it. I log in to KC, stop and start the Infinispan server, refresh the page, and still log in. It is not asking for credentials. Am I missing something?

**Comment by ahus1** [comment]
@y-tabata - can you please provide a CLI on how to start Keycloak and Infinispan? Can you show an example with Docker Compose, or are you using Kubernetes to deploy things?

**Comment by tnorimat** [comment]
@ahus1 @pruivo Hello, I re-tried the scenario under the following environment and found that the problem did not occur, thank you.

Keycloak version: 26.0.1
Infinispan version: 15.010.Final
