### ISSUE TITLE
Create release 24.0.8

### ISSUE THREAD

**Issue by kbakdev** [keycloak/keycloak#33329]
### Description

We noticed that there is already version 24.0.8, tagged in the Git repository, but there is no release for that version.

https://github.com/keycloak/keycloak/releases/tag/24.0.8

Our build process relies on GitHub releases and assets to run all CI/CD processes for Keycloak.

We need that version to patch CVE, and we need to have a release of that version, so our current scripts can actually deploy that version.

**Comment by ahus1** [comment]
The Keycloak project doesn't offer binary releases for other releases than the latest major release. If you are are using the Community version of Keycloak, you're supposed to upgrade to the latest version of Keycloak which is Keycloak 25. 

There are commercial offerings that provide patched Keycloak versions for older releases.
