### ISSUE TITLE
Keycloak 26.0.0 readiness

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#33322]
### Description

Review if 26.0.0 is ready to be released

Reviews
- [x] Bug status
- [x] CVE status / @stianst 
- [x] CI status
- [x] [Issues](https://github.com/orgs/keycloak/projects/35/views/1) / @stianst 
- [x] Release notes polish

Team approvals
- [x] Core Clients  / @mposolda 
- [x] Core IAM / @pedroigor 
- [x] Cloud Native / @vmuzikar 
- [x] Release / @stianst 
- [x] SRE / @ahus1 
- [x] Testing / @miquelsi 
- [x] UI / @ssilvert 

Blockers
- [x] Multi-site review/completion / @stianst

**Comment by abstractj** [comment]
@stianst with 26 released, should we close it? And maybe close the milestone?
