### ISSUE TITLE
Performance drop in cpuUsageForLoginsTest since 19.09.2024

### ISSUE THREAD

**Issue by andyuk1986** [keycloak/keycloak#33331]
### Describe the bug

A performance decrease is spotted in `cpuUsageForLoginsTest` run since 19.09.2024. 

From the attached screenshot of KCB daily runs statistics  in Horreum, you can see that the value of `userLoginsPerSecPer1vCpuPerPod` has decreased from average 110 to 82.

![horreum_perf_decrease_spot](https://github.com/user-attachments/assets/debe3039-b7ac-48a9-8420-7e095840bdfb)

The same you can see on Horreum change detection graph for that metric:

![image](https://github.com/user-attachments/assets/d21ec99f-a447-4a87-9a70-3712d7944c94)

I have checked the KCB commits, and the only change that was merged on 18.09 was Healthcheck related changes to github workflow, but there was nothing from my point of view that could harm the performance this way. 

### Version

nightly run

**Comment by ahus1** [comment]
Moving this to the Keycloak project to track this for the upcoming KC26 milestone.
