### ISSUE TITLE
"somethingWentWrong" when opening Keycloak URL in unsecure context

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#33330]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When starting Keycloak with 

```
bin/kc.sh start-dev
```

from nightly and use the URL `http://0.0.0.0:8080/` I get the error message

![image](https://github.com/user-attachments/assets/601ad5e9-525d-43bc-9e70-2f343ea88e21)

It works when using the URL `http://localhost:8080/`

### Version

nightly

### Regression

- [X] The issue is a regression

### Expected behavior

Login screen should appear

### Actual behavior

Error message appears

### How to Reproduce?

* Download Keycloak nightly
* Start `bin/kc.sh start-dev`
* Setup admin user via `http://localhost:8080/`
* Open `http://0.0.0.0:8080/` as an example for an unsecure context 

### Anything else?

IMHO this is a blocker for the KC26 release / @keycloak/ui, @stianst 

Happens both on Firefox  and Chrome (128.0.6613.137). 

![image](https://github.com/user-attachments/assets/130170f6-b03d-4050-9350-9e59cccb9058)

**Comment by jonkoops** [comment]
I'll take a look at this one.

**Comment by mabartos** [comment]
JFYI - I can confirm the PR https://github.com/keycloak/keycloak/pull/33480 properly resolved the issue.

**Comment by jonkoops** [comment]
Thanks for verifying that @mabartos

**Comment by Cloud2Software** [comment]
Using Keycloak 26.0.4 and 26.0.5 running on Docker Desktop on Windows 10 Pro if the KC_HOSTNAME is set to anything other than localhost when started using either:

`command: start-dev`

or 
 
`entrypoint: /opt/keycloak/bin/kc.sh start --proxy-headers=forwarded --proxy-trusted-addresses=192.168.0.0/24,127.0.0.0/8,142.112.223.120 `

the reported someWentWrong error is thrown and the login dialog is not presented when attempting to load the initial page.

@jonkoops any suggestions? Should a new ticket be opened?

**Comment by domdorn** [comment]
In case it helps someone: 

I'm fronting keycloak with the docker image "nginx-proxy". 

I had to add to change the entrypoint to:

```
    entrypoint: /opt/keycloak/bin/kc.sh start  --verbose --proxy-headers xforwarded --proxy-trusted-addresses=172.19.0.0/24,127.0.0.0/8
```

(where 172.19.0.0/24 is the network your nginx-proxy and your keycloak share). 

Previously I had `--proxy-headers forwarded` and changing it to `xforwarded` fixed the problem for me.

**Comment by ktk** [comment]
Same problem on my setup with a FreeBSD jail with Keycloak & Apache as reverse proxy. Had to add `proxy-headers=xforwarded` to the config to get it to work.

**Comment by sahil-sharma** [comment]
Facing the same issue. Despite adding all the Envs (as below)

![Image](https://github.com/user-attachments/assets/a85a8976-11ac-455c-895c-ab9049cbf03d)

**Comment by Rodrigosolari** [comment]
> Facing the same issue. Despite adding all the Envs (as below)
> 
> ![Image](https://github.com/user-attachments/assets/a85a8976-11ac-455c-895c-ab9049cbf03d)

yo lo solucione, pero no entiendo muy bien tu imagen...  podrias detallar que estas usando?

**Comment by sahil-sharma** [comment]
@Rodrigosolari I am trying to install keycloak in my K8s cluster. Keycloak service is exposed via Nginx Ingress. When I try to access Keycloak end-point I get above error.
I have added all the headers and set the config that might be needed or as defined in the documentation. Still it does not work. If you have any inputs on this then please share as how did you solve it. Maybe it would help me.
Above image shows the ENV being set in keycloak container during runtime. Hope it helps.

**Comment by thanhtai9606** [comment]
it should like this, it will working for me
```
extraEnvVars:
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: KC_PROXY_HEADERS
    value: "xforwarded" 
  - name: KC_PROXY
    value: "edge"
  - name: KC_HOSTNAME
    value: "domain.com"
```

**Comment by wangyanlingfamily** [comment]
> 它应该像这样，它会为我工作
> 
> ```
> extraEnvVars:
>   - name: KEYCLOAK_PRODUCTION
>     value: "true"
>   - name: KC_PROXY_HEADERS
>     value: "xforwarded" 
>   - name: KC_PROXY
>     value: "edge"
>   - name: KC_HOSTNAME
>     value: "domain.com"
> ```
thanks, it's very helpful
