### ISSUE TITLE
Email visible for user when no permissions set in User Profile

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#33341]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Given the email attribute configuration in User Profile with all Permissions unchecked:
![image](https://github.com/user-attachments/assets/2cfb277f-59f3-458c-88a7-cc7b0ac03d9c)

Then the attribute shows up at the User profile as editable field:
![image](https://github.com/user-attachments/assets/610f8a4f-1ce5-48ea-9a17-2c1e7da940d9)

At the account console it is also visible:
![image](https://github.com/user-attachments/assets/2acdcea5-435c-471e-932d-eb9660dc0e9a)

### Version

24.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Email not visible for both, user (in profile form of login theme) and admin (in admin console).

### Actual behavior

Email displayed but configuration says it should not be viewable.

### How to Reproduce?

1. All Permissions unchecked at user attribute email.
2. Set one attribute as required so that user profile shows up

**Comment by pedroigor** [comment]
This is by design where the e-mail field is always visible. Similar to the `username` attribute. The reason is that both `username` and `email` are used during authentication and they are also managed by the `email as username` and `edit username` settings in the realm settings.

The only setting that should work to change the `email` attribute behavior is `required`.

Can you please elaborate the use case and why you want to not show the e-mail field for both users and admins?

**Comment by jbman** [comment]
The email field is hidden as expected, as long as least on of the Admin permissions is checked. 
Hiding the email is needed in case of IdP integration, and at some of our installations the admin permissions where also removed at the user profile configuration. This ends up with the email being shown to the user in the Verify Profile action, which is very unexcpected.

Checking at least on Permission for the Admin is a workaround to fix it in the configuration.
We have no use case where the Admin should have no read/write access to email, but the user shouldn't have access.

**Comment by jbman** [comment]
I just checked in Version 26.0.0. The email field is never displayed, even if configured as required fro users and editable for users.

This is again a different behaviour than in the versions before and may be an issue for other use cases. The issue described here seems to apply to 24 and is not relevant any more at newer versions.

**Comment by pedroigor** [comment]
@jbman Do you have `update-email` feature enabled?

**Comment by jbman** [comment]
Ah, UPDATE_EMAIL is not enabled on 24 where the issue occurs, but was enabled when I tested at 26 (because there I had all preview features enabled).

**Comment by pedroigor** [comment]
That explain why the email is never shown.

**Comment by jbman** [comment]
Could reproduce the issue in nightly. Email field is shown unexpectedly if view edit Permissions for user and admin are all unchecked.

To reproduce it:
* Start Keycloak without any preview features (e.g. no "update-email" feature). 
* Remove all Permission checkmarks from the email attribute.
* Create a user and login with the user.

Result

![image](https://github.com/user-attachments/assets/5d88ccb5-5c4d-4c11-b2dc-a7cc27449b04)

This issue hasn't high priority as an admin can set the email viewable and editable for admins to fix it. But it is still unexpected behaviour: the user can view and edit the email while the profile says this it isn't allowed. Emails can be managed by the user while they are originally mapped from an IdP und must not be changed.
