### ISSUE TITLE
Wrong translation issues in greek translation

### ISSUE THREAD

**Issue by nsotirakos** [keycloak/keycloak#33352]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

translations

### Describe the bug

We use Keycloak on our site and recently we found two spelling mistakes when in translation from english to greek language. 
![image-20240918-091513](https://github.com/user-attachments/assets/17099f9a-3063-4afb-b722-7d9b8eb035f7)
![image-20240918-091445](https://github.com/user-attachments/assets/115ba5bb-07c4-487e-9489-c52cc66054b4)

### Version

22.05

### Regression

- [ ] The issue is a regression

### Expected behavior

1. ![image-20240918-091513](https://github.com/user-attachments/assets/4450cb08-6411-4021-a54b-6dea3f13094b)
It should be translated as "επιπλέον"

2. 
![image-20240918-091445](https://github.com/user-attachments/assets/5ca477ff-8651-4488-ad85-c732cc6bd085)
It should be translated as "τον", because the word "κωδικός" is male noun. Word "το" is used for neutral singular gender.

### Actual behavior

1. It is translated "επιπλέων"

2. It is translated "το"

### How to Reproduce?

Just click to change between language

**Comment by ahus1** [comment]
Thank you for reporting this. Please consider contributing a pull request for the following file with an updated translation: https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/login/messages/messages_el.properties
