### ISSUE TITLE
ID token from refresh_token flow does not contain nonce even when using Nonce backwards compatible mapper

### ISSUE THREAD

**Issue by tomaskralik** [keycloak/keycloak#33355]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Recently, we have migrated from Keycloak 20.0.5 to version 25.0.4 which broke an integration with a client that expects the `nonce` claim to be present in all ID tokens. However, after migrating to the new version, `nonce` is not being added to the ID token obtained using the `refresh_token` flow.

According to release notes, this is by design - https://www.keycloak.org/docs/25.0.0/upgrading/#nonce-claim-is-only-added-to-the-id-token.

The notes mention that for backwards compatibility purposes a mapper `Nonce backwards compatible` can be used to revert to old behaviour. This indeed causes the `nonce` claim to be included in access and refresh tokens, however, it is still not included in an ID token when using the `refresh_token` flow and therefore not achieving the actual old behaviour.

I successfully managed to reproduce this behaviour in the latest version 25.0.6 as well.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

When utilizing `refresh_token` flow for a client with `Nonce backwards compatible` mapper, the ID token should include `nonce` claim

### Actual behavior

ID token obtained using `refresh_token` flow does not contain `nonce` claim even when the client uses `Nonce backwards compatible` mapper

### How to Reproduce?

- Assign the `Nonce backwards compatible` mapper to a client's dedicated scope or some other scope the client uses
- Obtain token using `authorization_code` flow (even though this flow type probably does not matter) with `nonce` parameter specified when calling authorization endpoint
- Use refresh token to get new tokens using `refresh_token` flow
- Access and refresh tokens contain the original `nonce`, ID token does not

**Comment by rmartinc** [comment]
Hi @tomaskralik!

I have tested this with the admin console itself and it's working as expected for me. Note that there is a specific [test](https://github.com/keycloak/keycloak/blob/25.0.6/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/oidc/NonceBackwardsCompatibleMapperTest.java#L69) that checks the mapper adds the nonce after the refresh. Just one note, when you add the mapper to the client you need to login again in that client, if the refresh is done with a initial refresh token that doesn't have the mapper it won't work.

**Comment by tomaskralik** [comment]
Hi @rmartinc,

thank you for taking you time and looking into my issue. Your reply made me look further into it because you are right that this scenario is covered by unit tests.

I managed to find that the problem with missing `nonce` claim occurs only when an offline session is created (when `offline_session` scope is requested. When using an `Offline` token during the `refresh_token` flow, the ID token is generated without the `nonce` claim.

For reproducibility, I added a new test case which is currently failing, because the `nonce` claim is not present in the ID token.

https://github.com/keycloak/keycloak/pull/33395

**Comment by rmartinc** [comment]
Yep, thanks for the reproducer. This was triggered by this change https://github.com/keycloak/keycloak/commit/89263f52552499d730e474b87a19ec2cccf66ec5, so by this issue https://github.com/keycloak/keycloak/issues/28463. It was soon after the addition of the nonce mapper, so the mapper realy never worked with offline sessions. I'll try to send a commit in the following days.
