### ISSUE TITLE
Permission cannot be evaluated when only role and client are provided

### ISSUE THREAD

**Issue by manway331** [keycloak/keycloak#33404]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

In Clients --> Details --> Authorization --> Evaluate, User is not a required field when Roles is provided. However, keycloak admin ui return the following error.
"Could not evaluate due to: For more on this error consult the server log at the debug level."

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should be able to evaluate permission when only role is provided because user is an optional field. 

### Actual behavior

Keycloak throw error when only role and client are provided.

### How to Reproduce?

1. Go to Clients --> Details --> Authorization --> Evaluate
2. Provide client, role, resource and role
3. Click Evaluate

**Comment by pedroigor** [comment]
The `Users` field is mandatory to run evaluations.

**Comment by manway331** [comment]
Hi,

I am getting confused if Keycloak support role only evaluation because there was an issue to remove the Users field as required field  
https://github.com/keycloak/keycloak/issues/17846

**Comment by edewit** [comment]
So I had to find out what was going on with this as we can't go back and forth on it. I've downloaded keycloak 18 and seen that on that old UI it is the case that user field wasn't mandatory when you filled out roles, but the same error as described in this issue occurred. So I'm going to revert the change that was made in #17846 as it introduced an issue that was present in the old UI not a feature.
