### ISSUE TITLE
Link to existing account form: IDP Alias displayed instead of IDP Display Name

### ISSUE THREAD

**Issue by fjf2002** [keycloak/keycloak#33408]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I am using an additional identity provider (another keycloak instance) and I am logging in.
Keycloak detects that the EMail address is already known and shows a dialog to link the other keycloak instance's user account to the current one.

The dialog says: "Authenticate to link your account with {0}"

The placeholder {0} gets resolved to what I suppose is the IDP's Alias name, NOT as I would expect the IDP's Display Name (!)

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect the IDP's Display Name (!)

### Actual behavior

The placeholder {0} gets resolved to what I suppose is the IDP's Alias name.

### How to Reproduce?

- As admin: Configure a second keycloak as IDP in the first keycloak.
- Login into the first one using an account from the second.
- As admin: In the 1st keycloak, unlink the user account from the second keycloak.
- Attempt a second time the login into the first one using an account from the second.
- Keycloak will report, the account already exists.
- Choose the second button, "Link to existing account" or so.
- Now notice the message above the username input field.

### Anything else?

cf. https://github.com/keycloak/keycloak/blob/c682536dae36e1aa35d90cf2cf24aa81864b46cd/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L282

cf. https://github.com/keycloak/keycloak/blob/a35edeb48803dd356f0e947a276f22544176afe4/services/src/main/java/org/keycloak/authentication/authenticators/broker/IdpUsernamePasswordForm.java#L96

**Comment by rmartinc** [comment]
Hi @fjf2002! You are right but this is very minor issue, if you really need it please send a PR as you have identified the affected lines. It would be just getting the identity provider and assigning the display name if available (if not pass the alias as it is now).

```java
IdentityProviderModel idpModel = context.getSession().identityProviders().getByAlias(serializedCtx.getIdentityProviderId());
// then just use idpModel.getDisplayName() or the alias
```

I don't think we need a test for this as it's just using the disply name.

**Comment by NobelNerdBenne** [comment]
@fjf2002  Hey, if you would assign it to me i will do it.

**Comment by jonkoops** [comment]
Assigned you @NobelNerdBenne :+1:

**Comment by fjf2002** [comment]
@jonkoops Thank You very much for taking over. I was on holiday last week, but to be honest, I also don't have any experience with the keycloak codebase.
