### ISSUE TITLE
User specific organisation entries shouldn't be placed in the realm cache

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#33412]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When caching the membership in an org or (cacheKeyByMember) memberships of a user (cacheKeyMembership), those cache entries are user specific. Still they are placed in the realm cache.

### Version

main

### Regression

- [x] The issue is a regression

### Expected behavior

User specific information should be cached in the user cache

### Actual behavior

User specific information is cached in the realm cache

### How to Reproduce?

See InfinispanOrganizationProvider

### Anything else?

Admins would be surprised when the entries in the realm cache would be evicted due to user information being cached there.

**Comment by ahus1** [comment]
I've been looking at the code and I assume it is currently using the wrong cache / @keycloak/core-iam  

The PR #33354 should still be merged, and this would be a follow-up discussion. 

cc: @pruivo, @mhajas

**Comment by mhajas** [comment]
Thanks for creating the issue @ahus1. +1 to this. Also, since it seems we have some data cached per user, we should consider storing it directly inside user entity, not a separate entry.

**Comment by ahus1** [comment]
Thanks Michal. It is not obvious to me how to solve this despite my comment in the issue description. I am open to all ideas. I am also not sure if this might be out of scope for KC26 initial release.

**Comment by pruivo** [comment]
> Thanks for creating the issue @ahus1. +1 to this. Also, since it seems we have some data cached per user, we should consider storing it directly inside user entity, not a separate entry.

@mhajas The organization feature has its provider, `OrganizationProvider`. IMO, it would be simpler to store in a different cache. 

If you stored in the `CachedUser`, what would you do if `CachedUser` does not exist (for example, it was evicted)? 
a) Would you do another database query to populate the fields of `CachedUser`?
b) Create an empty `CachedUser` just with the organization IDs? Then you have to change the code all over the place to see if the `CachedUser` is populated. 

Thoughts?

**Comment by mhajas** [comment]
When searching for all organizations for a user we already have a user. I am talking specifically about caching this method: https://github.com/keycloak/keycloak/blob/36d973c05f74f49eac4c3620387584873e10ee85/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java#L218

We are already doing something similar with group membership: 
https://github.com/keycloak/keycloak/blob/36d973c05f74f49eac4c3620387584873e10ee85/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedUser.java#L74

**Comment by ahus1** [comment]
> IMO, it would be simpler to store in a different cache.

IMHO there are technical arguments to do this, still it would add complexity to the users which then need to configure yet another cache. 

With the rule of thumb "the more users you have logging in a period of time, the larger the users cache should be", admins should be ok. Otherwise we would give them advice like "the users cache should be x% the size of the organisations cache" if we put a lot of user related data in there. 

So that's why I'd prefer to stick with the caches we have. It is already complicated enough. And I realize (again) that we don't provide good heuristics on how to size those caches.

**Comment by pruivo** [comment]
> When searching for all organizations for a user we already have a user. I am talking specifically about caching this method:
> 
> https://github.com/keycloak/keycloak/blob/36d973c05f74f49eac4c3620387584873e10ee85/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java#L218
> 
> We are already doing something similar with group membership:
> 
> https://github.com/keycloak/keycloak/blob/36d973c05f74f49eac4c3620387584873e10ee85/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/entities/CachedUser.java#L74

`UserModel` is not the same as `CachedUser` and `UserModel` has methods to interact with groups. Are you suggesting the same? If so, `Stream<OrganizationModel> getByMember(UserModel member)` has no use :)

**Comment by pruivo** [comment]
> > IMO, it would be simpler to store in a different cache.
> 
> IMHO there are technical arguments to do this, still it would add complexity to the users which then need to configure yet another cache.
> 
> With the rule of thumb "the more users you have logging in a period of time, the larger the users cache should be", admins should be ok. Otherwise we would give them advice like "the users cache should be x% the size of the organisations cache" if we put a lot of user related data in there.
> 
> So that's why I'd prefer to stick with the caches we have. It is already complicated enough. And I realize (again) that we don't provide good heuristics on how to size those caches.

I'm thinking about a private cache, like `*Revision` caches. Those are not configurable. With the CLI options about the max-count, I'm curious about what other options users configure in the local caches.
