### ISSUE TITLE
Organization data is cached for each user even if realm never enabled organizations

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#33424]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

This is a follow-up issue on discussion here: https://github.com/keycloak/keycloak/pull/33403#discussion_r1781216978

Current version of organization caching is caching list of organization ids for users to remember what organization the user is member of.

The problem with this is, that we are querying all organizations for user with each user querying (both single result and list) because it is part of this method: https://github.com/keycloak/keycloak/blob/main/model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L119

Note, we are doing this on all codepaths querying users regardless of any other settings, only way to get rid of this is disable organization feature.

This results in the following:
1. realms cache contains one entry per user to remember all organizations for the user, there is a related issue to this: #33412
2. Even if we move the entries to user cache as suggested in #33412 we would essentially halve the user cache, because each user will have 2 entries instead of one (CachedUser data and CachedOrganizationIds).
3. For realms that do not use organizations (and never did) this will result in the `realms` cache with a lot of entries `(realm_id, empty_list)`. Note this will be true for every realm and every deployment migrated to Keycloak 26. I suspect for realms with a lot of users this will mean the `realms` cache is basically useless for realms/clients/groups/roles etc. because these entities will be pushed out by many `CachedOrganizationIds` entries.

To me 3. is important especially since this impacts everyone upgrading to Keycloak 26.

 

### Version

main

### Regression

- [x] The issue is a regression

### Expected behavior

If realm does not use organizations (and no organizations exist) do not query and cache anything related to organizations.

### Actual behavior

We are storing things related to orgs regardless of settings

### How to Reproduce?

Login to any realm and observe this key: https://github.com/keycloak/keycloak/blob/412f1f85a927f1f234e8562d9033d3786b79db29/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/organization/InfinispanOrganizationProvider.java#L346 is cached

### Anything else?

The authentication flow containing some organization conditional checks is unrelated to this issue as this is happening all the time users are queried not only when the organization related steps are done as part of authentication.

To workaround this issue it is possible to disable organization feature. However, this is not suitable for mixed deployments where some realms user orgs and some not.

**Comment by pedroigor** [comment]
Different than groups, organization membership is managed within the Organization SPI. That is the reason why we don't have it into cached user entries.

Can we skip caching when there is no organization in a realm? In addition to checking if the feature is enabled to the realm.

Other than that, we need to keep those empty_list cache entries to avoid unnecessary round-trips when resolving organizations for users.
