### ISSUE TITLE
404 in admin console when unlinking managed user from organizations

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#33435]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When some user is linked to the organization as "managed" member (so for example he was added to the realm by authentication to the identity provider, which is linked with the particular organization), then there is 404 displayed when trying to unlink such user from the organization.

AFAIK unlinking the user from the organization should remove the user and that is done under the covers. But it seems that admin console tries to redirect back to such user, which don't work as user does not exists anymore.

### Version

nightly (from 2024-10-01)

### Regression

- [ ] The issue is a regression

### Expected behavior

User is unlinked and deleted (that is done), but then some sensible page is displayed to the administrator. Probably the generic "Users" page.

### Actual behavior

There is 404 error in the admin console

### How to Reproduce?

- Follow the steps similar to the organization blog https://www.keycloak.org/2024/06/announcement-keycloak-organizations.html . Some details:
-- Setup realm `orgdemo` and add organization `orga` with the domain `orga.com` to it.
-- Setup realm `orga` with the client and with user with email `jdoe@orga.com`
-- Setup identity provider in the realm `orgdemo` and link this IDP with the `orga` organization
-- Trying to login as user in the `orgdemo` with username like `jdoe@orga.com` . This will redirect user to the login page of `orga` realm. After login as `jdoe`, the user is redirected back to the `orgdemo` realm. At this point, user `jdoe@orga.com` is registered in the realm `orgdemo` as managed member of the organization `orga` .

- Now go to the admin console and go to the realm `orgdemo` and user `jdoe` and tab `Organizations` and click to "remove"  to remove the user from the organization

![Screenshot from 2024-10-01 13-44-03](https://github.com/user-attachments/assets/dfa463b9-2638-4d71-89fd-38ca3eb06a6b)

- Now the user is unlinked and removed, but there is 404

![Screenshot from 2024-10-01 13-44-46](https://github.com/user-attachments/assets/ef834e9c-92b0-4d13-9128-c852098d45c0)

### Anything else?

When removing the unmanaged user from the organization (For example the user, which was manually linked to the organization by administrator), the unlinking from organization works as expected.

**Comment by pedroigor** [comment]
The UI is refreshing the page but managed users are removed hence the 404. When unlinking managed members we need to redirect the admin to the user list page.
