### ISSUE TITLE
.well-known/openid-configuration lacks CORs protection

### ISSUE THREAD

**Issue by oreillymj** [keycloak/keycloak#33434]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The API endpoint /realms/<realm>/.well-known/openid-configuration return the request.uri in the CORs Access-Control-Allow-Origin Header. So for an install running on https://keycloak.example.com an XHR request from evil.keycloak.example.com will result in a response header of 
Access-Control-Allow-Origin: evil.keycloak.example.com

There doesn't appear to be any way of configuring CORs to prevent cross origin requests to this endpoint.

### Version

25.06

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect the browser to block this CORs XHR request after the fetch pre-flight returns the  Access-Control-Allow-Origin header with https://keycloak. example.com set.

### Actual behavior

The browser request is not blocked and the server response with a JSON payload.

### How to Reproduce?

Below is a base64 encoded HTML file that sends a XHR request to a base URL//realms/master/.well-known/openid-configuration (change variable to suit test environment) Using the chrome web tools, you can see the XHR request and the JSON response/ headers etc.

PCFkb2N0eXBlaHRtbD48aHRtbCBsYW5nPWVuPjxtZXRhIGNoYXJzZXQ9VVRGLTg+PG1ldGEgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLGluaXRpYWwtc2NhbGU9MSJuYW1lPXZpZXdwb3J0Pjx0aXRsZT5LZXljbG9hayAtIFdlbGwgS25vd24gRmV0Y2ggVGVzdDwvdGl0bGU+PHN0eWxlPmh0bWx7Zm9udC1zaXplOjIwcHg7Zm9udC1mYW1pbHk6LWFwcGxlLXN5c3RlbSxCbGlua01hY1N5c3RlbUZvbnQsJ1NlZ29lIFVJJyxSb2JvdG8sT3h5Z2VuLFVidW50dSxDYW50YXJlbGwsJ09wZW4gU2FucycsJ0hlbHZldGljYSBOZXVlJyxzYW5zLXNlcmlmO2ZvbnQtd2VpZ2h0OjMwMH1wcmV7bWF4LXdpZHRoOjgwdnd9PC9zdHlsZT48aGVhZGVyPjxoMT5LZXljbG9hayAtIFdlbGwgS25vd24gRmV0Y2ggVGVzdDwvaDE+PC9oZWFkZXI+PG1haW4+PHA+PHRleHRhcmVhIGNvbHM9NTAgaWQ9dHh0VG9rZW4gbmFtZT10eHRUb2tlbiByb3dzPTQgdmFsdWU9IiI+PC90ZXh0YXJlYT48YnI+PGxhYmVsIGZvcj10b2tlbj5QYXN0ZSB5b3VyIEF1dGggdG9rZW4gaGVyZTwvbGFiZWw+PGJyPjxwPjxidXR0b24gaWQ9YnRuQWRkPkdldCBPcGVuSUQgY29uZmlndXJhdGlvbjwvYnV0dG9uPjwvbWFpbj48c2NyaXB0PmNvbnN0IGJhc2VVUkwgPSAnaHR0cHM6Ly9rZXljbG9hay5leGFtcGxlLmNvbSc7IAogICAgY29uc3QgdG9rZW4gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndHh0VG9rZW4nKTsKCgogICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsICgpID0+IHsKCgogICAgICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYnRuQWRkJykuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCBmQWRkKTsKICAgIH0pOwoKICAgIGZ1bmN0aW9uIGZBZGQoZXZ0KSB7CiAgICAgIC8vc2VuZCBhIHJlcXVlc3QgdG8gYW4gQVBJCiAgICAgIGxldCB1cmwgPSBgJHtiYXNlVVJMfS9yZWFsbXMvbWFzdGVyLy53ZWxsLWtub3duL29wZW5pZC1jb25maWd1cmF0aW9uYDsKICAgICAgbGV0IGNtb2RlID0gJ2NvcnMnOwogICAgICBsZXQgYXV0aF90b2tlbiA9IHRva2VuLnZhbHVlLnRyaW0oKTsKICAgICAgY29uc29sZS5sb2coInVybD0iICsgdXJsKQogICAgICBjb25zb2xlLmxvZygiYXV0aCB0b2tlbj0iICsgYXV0aF90b2tlbikKICAgICAgbGV0IHJlcSA9IG5ldyBSZXF1ZXN0KHVybCwgewogICAgICAgIG1vZGU6IGNtb2RlLCAKICAgICAgICBjcmVkZW50aWFsczogJ2luY2x1ZGUnLCAKICAgICAgfSk7CiAgICAgIGlmIChhdXRoX3Rva2VuIT0iIil7CiAgICAgICAgcmVxLmhlYWRlcnMuYXBwZW5kKCdBdXRob3JpemF0aW9uJywgJ0JlYXJlciAnICsgYXV0aF90b2tlbikKICAgICAgfQogICAgICBmZXRjaChyZXEpCiAgICAgICAgLnRoZW4oKHJlc3ApID0+IHsKICAgICAgICAgIHJlc3AuaGVhZGVycy5mb3JFYWNoKCh2YWwsIGtleSkgPT4gewogICAgICAgICAgICBjb25zb2xlLmxvZyhrZXksIHZhbCk7CiAgICAgICAgICB9KTsKICAgICAgICAgIGlmIChyZXNwLnR5cGUhPSJvcGFxdWUiKXsKICAgICAgICAgICAgcmV0dXJuIHJlc3AuanNvbigpOwogICAgICAgICAgfQogICAgICAgICAgcmV0dXJuIHJlc3AuYm9keTsgLy8gWW91IHdvbnQgZ2V0IGFjY2VzcyB0byBhbnl0aGluZyByZXR1cm4gZnJvbSB0aGUgc2VydmVyIHdpdGggQ09SUyBkaXNhYmxlZC4KICAgICAgICAgIC8vcmV0dXJuIHJlc3AuanNvbigpOwogICAgICAgIH0pCiAgICAgICAgLnRoZW4oKGRhdGEpID0+IHsKICAgICAgICAgIGxldCBvdXRwdXRwID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpOwogICAgICAgICAgaWYgKGRhdGEhPW51bGwpewogICAgICAgICAgICBjb25zb2xlLmxvZygiZGF0YTogIiArIGRhdGEuaXNzdWVyKTsKICAgICAgICAgIH0KICAgICAgICB9KQogICAgICAgIC5jYXRjaCgoZXJyKSA9PiB7CiAgICAgICAgICBjb25zb2xlLndhcm4oZXJyKTsKICAgICAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKS50ZXh0Q29udGVudCA9IGVyci5tZXNzYWdlOwogICAgICAgIH0pOwogICAgfTwvc2NyaXB0Pg==

**Comment by mposolda** [comment]
I am changing this to an Enhancement with low priority. I don't consider it as a bug. The specification https://openid.net/specs/openid-connect-discovery-1_0.html just mentions that endpoint must allow CORS headers, but there are not any described ways to describe what origins should be allowed to invoke the well-known endpoint.

IMO if we want to support this, we will need some way of configuration of allowed origins per realm or per whole Keycloak server (as currently we have only allowed origins per client and the well-known endpoint is independent of any client application).

**Comment by jonkoops** [comment]
> Below is a base64 encoded HTML file

Why is this encoded?

**Comment by oreillymj** [comment]
> > Below is a base64 encoded HTML file
> 
> Why is this encoded?

I encoded it because I assumed that github would not allow me to post html/javascript. Feel free to use it as simple test or ignore it and use a locally devised test.

btw - I've pulled the code and searched for the code which provides the response to the ./well-known endpoint request.
I've found OIDCWellKnownProvider implements WellKnownProvider but cannot figure out how that is converted into a JSON HTML response with header fields. Any pointers on how that happens would be appreciated.

**Comment by jonkoops** [comment]
GitHub does allow you to [put code in posts](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), it doesn't execute it or anything so it's not a security issue. Could you please update your code to be readable?

**Comment by michaeloreillyintel** [comment]
Since I can no longer edit my initial issue, here is the code to reproduce.
If you run this from locahost and change the BaseURL to a Keycloak domain, you should see the CORs header accepting your origin domain


```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Keycloak - Well Known Fetch Test</title>
  <style>
    html {
      font-size: 20px;
      font-family: Roboto, 'Open Sans', 'Helvetica Neue', sans-serif;
      font-weight: 300;
    }

    pre {
      max-width: 80vw;
    }
  </style>
</head>

<body>
  <header>
    <h1>Keycloak - Well Known Fetch Test</h1>
  </header>
  <main>
    <p>
      <textarea rows="4" cols="50"  id="txtToken" name="txtToken" value="" ></textarea><br>
      <label for="token">Paste your Auth token here</label><br>
    </p>

    <p><button id="btnAdd">Get OpenID configuration</button></p>
    <p id="output"></p>
  </main>
  <script>
    const baseURL = 'https://keycloak.example.com'; // cross-site CORS
    const token = document.getElementById('txtToken');
    document.addEventListener('DOMContentLoaded', () => {
      document.getElementById('btnAdd').addEventListener('click', fAdd);
    });

    function fAdd(evt) {
      let url = `${baseURL}/realms/master/.well-known/openid-configuration`;
      let cmode = 'cors';

      let auth_token = token.value.trim();
    
      console.log("url=" + url)
      console.log("auth token=" + auth_token)
      
      let req = new Request(url, {
        mode: cmode, //just a safe-guard indicating our intentions of what to allow
        credentials: 'include', //when will the cookies and authorization header be sent
      });
      if (auth_token!=""){
        req.headers.append('Authorization', 'Bearer ' + auth_token)
      }
      fetch(req)
        .then((resp) => {
          resp.headers.forEach((val, key) => {
            console.log(key, val);
          });
          //let cookie = resp.headers.get('set-cookie');
          //console.log('set-cookie header value', cookie);
          if (resp.type!="opaque"){
            return resp.json();
          }
          return resp.body; // You wont get access to anything return from the server with CORS disabled.
          //return resp.json();
        })
        .then((data) => {
          let outputp = document.getElementById('output');
          if (data!=null){
            console.log("data: " + data.issuer);
          }
          console.log("cookies: " + document.cookie);
          formattedcookies = document.cookie.trim().replace(' ', '</p><p>');
          //console.log("format: " + formattedcookies);
          formatHTML = '<p id="open">' + formattedcookies + '</p id="close">';
          //console.log("html: " + formatHTML);
          outputp.innerHTML = formatHTML;
        })
        .catch((err) => {
          console.warn(err);
          document.getElementById('output').textContent = err.message;
        });
    }

  </script>
</body>

</html>
```

**Comment by stianst** [comment]
Why would it need any cors protection? It's a read only thing.

Additionally what would you protect it with? SPA clients use it, but it's not known what client is calling it, so you don't know what origins should be permitted.

I think this should be closed as it's a non-issue.

**Comment by HerrDerb** [comment]
I just hit the same issue. I cannot get the well known endpoints in my web application. Means I need to configure all endpoints myself instead of the letting them be discovered.

**Comment by jonkoops** [comment]
Agreed, closing.
