### ISSUE TITLE
Enhance user search to support partial email matching

### ISSUE THREAD

**Issue by Lexachoc** [keycloak/keycloak#33446]
### Description

![image](https://github.com/user-attachments/assets/1eb7724e-1d46-41b4-8376-6d1a6d07e58e)

You can see from the screenshot that when I search for `corning`, no results.

### Motivation

Users from the same company, university or institute often have the same e-mail domain. It would be nice to filter them using just the domain text. Otherwise there is only one way to find them: `Ctrl+F` and go through all pages.

Example: Users of a company with the domain `XXX@corning.com`. When typing `corn` or `corning` or `@corning` or  `corning.com` or `@corning.com` in the search field should find all users with email domain of `corning`.

Currently no results are currently displayed unless the full e-mail address is entered!

**Comment by vramik** [comment]
To achieve the desired behavior it's required to put the search keywork into asterisks, like `*corn*` as desribed in the documentation https://www.keycloak.org/docs/latest/server_admin/index.html#proc-searching-user_server_administration_guide 

Alternatively it's possible to use attribute search by clicking on `Default search` dropbox.

**Comment by Lexachoc** [comment]
@vramik Thank you for the hint! I did not realize it was there! I thought searching would be more intuitive.
