### ISSUE TITLE
The "Client Secret" field does not expand to display the entire secret value

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#33467]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When entering a long client secret, the input field does not resize to show the full value. As a result, only a portion of the secret is visible, making it difficult to verify or copy the complete value. This issue impacts usability and could lead to errors when managing client secrets.

![Screenshot 2024-10-02 at 13 07 58](https://github.com/user-attachments/assets/e6d4e7f3-a134-4760-a85c-d34554f0070f)

### Version

25.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

The "Client Secret" field should automatically resize or provide a scrolling option to allow viewing of the entire secret value.

### Actual behavior

The field remains fixed in size, displaying only a truncated portion of the client secret.

### How to Reproduce?

1. Navigate to the page where the client secret is displayed.
2. Enter or generate a long client secret.
3. Observe that the field does not expand, and the full value is not visible.

**Comment by ssilvert** [comment]
@enastevska If you click on the client secret you can scroll left and right using the arrow keys.  

Is that sufficient?

**Comment by enastevska** [comment]
Our clients are already using that but they are not satisfied with it. They don't feel confident when they don't see the whole secret and need to copy it. In version 24 the whole content of the field was visible

**Comment by ssilvert** [comment]
OK.  But I can't promise we will be able to get to this soon.  A PR will be welcome.
