### ISSUE TITLE
Keycloak Reader and Writer External Database

### ISSUE THREAD

**Issue by sabinayakc** [keycloak/keycloak#33485]
### Description

We would like to connect keycloak to a reader and writer endpoints for the external database. 
We currently are using AWS Aurora cluster with one reader and one writer endpoints. 

How do we configure keycloak to use the reader and writer endpoints?

### Motivation

We saw that that all queries were going to the writer endpoints of AWS Aurora.  And the reader instance had no connection. Thus, this defeats the purpose having the reader and writer endpoints. 

### Details

If there was a way to update Database configuration such as,
`DB_READER_ENDPOINT` or `DB_REPLICA_HOST` that would be great but don't know the implementation details to achieve this configuration.

**Comment by codespearhead** [comment]
Please close this issue [1] in favor of this discussion [2], which has just been answered.

It'd help if you could mark the comment in it as the accepted answer [2] for that discussion, so it no longer appears as unanswered in the GitHub discussions tab.

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
[2] https://github.com/keycloak/keycloak/discussions/33486
[3] https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#marking-a-comment-as-an-answer
