### ISSUE TITLE
Use `crypto.randomUUID()` to generate UUIDs for Keycloak JS

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#33515]
See https://github.com/keycloak/keycloak/pull/33480#issuecomment-2391036044

**Comment by fjrial** [comment]
Dear developers, just quick comment/note

Are you aware that by using the Crypto API, now while integrating the authentication from within an angular app using latest keycloak-js library adapter, it's required to have everything running under https ?

Crypto API is only available while running over https, so while initializing the Keycloak object, the following error is thrown
<code>Error: Web Crypto API is not available
</code>
