### ISSUE TITLE
"Uncaught server error : org.keycloak.authentication.AuthenticationFlowException: authenticator: direct grant flow

### ISSUE THREAD

**Issue by alokrbl** [keycloak/keycloak#33523]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

![image](https://github.com/user-attachments/assets/32914ea9-9f05-4d41-ba3e-9688d14f981e)

I am overriding direct grant flow as above using admin REST api. This works fine till Kecloak 24 but deploying Keycloak 25 gives error -  Uncaught server error : org.keycloak.authentication.AuthenticationFlowException

### Version

Keycloak 25.x.x

### Regression

- [ ] The issue is a regression

### Expected behavior

We should not get any authentication error

### Actual behavior

get error during authentication - Uncaught server error : org.keycloak.authentication.AuthenticationFlowException

### How to Reproduce?

Override direct grant flow as mentioned above. basic user authentication gives error.

I am trying to run keycloak 25.0.6 with mysql:8.0.33. with the same setup Keycloak 23 & 24 works fine.

I run keycloak with below arguements 
 "${APP_BIN}/kc.sh" --verbose start  --metrics-enabled=true --hostname-strict=false --http-relative-path=/auth --http-enabled=false --spi-x509cert-lookup-provider=apache --spi-x509cert-lookup-apache-ssl-client-cert=SSL_CLIENT_CERT --https-client-auth=request --features="docker,admin-fine-grained-authz,scripts"  --cache-config-file=/opt/app/lib/keycloak/conf/cache-ispn.xml

### Anything else?

Complete logs 

{"v":"1.1.1","timestamp":"2024-10-03T12:02:24.415Z","level":"ERROR","category":"SERVICE","application":{"instanceId":"id-provider-549959c5cd-7kdgf","name":"KeyCloak Identity Provider","version":"25.0.6","process":21,"processName":"QuarkusEntryPoint","thread":96,"threadName":"executor-thread-16","component":"org.keycloak.services.error.KeycloakErrorHandler"},"details":{"type":"INTERNAL","description":"Uncaught server error","details":{"sequence":10278,"logger-class-name":"org.jboss.logging.Logger","mdc":{},"ndc":""},"exception":{"refId":1,"exceptionType":"org.keycloak.authentication.AuthenticationFlowException","message":null,"frames":[{"class":"org.keycloak.authentication.AuthenticationProcessor","method":"authenticateOnly","line":1079},{"class":"org.keycloak.protocol.oidc.grants.ResourceOwnerPasswordCredentialsGrantType","method":"process","line":111},{"class":"org.keycloak.protocol.oidc.endpoints.TokenEndpoint","method":"processGrantRequest","line":140},{"class":"org.keycloak.protocol.oidc.endpoints.TokenEndpoint$quarkusrestinvoker$processGrantRequest_6408e15340992839b66447750c221d9aaa837bd7","method":"invoke"},{"class":"org.jboss.resteasy.reactive.server.handlers.InvocationHandler","method":"handle","line":29},{"class":"io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext","method":"invokeHandler","line":141},{"class":"org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext","method":"run","line":147},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":582},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2513},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1538},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":1583}]}},"context":{}}

**Comment by alokrbl** [comment]
Any help or comment please?

One more additional info. with KC25 this is consistently occurring while adding config to execution using POST api in fresh database- POST /admin/realms/{realm}/authentication/executions/{executionId}/config

my config is - '{"alias": "cert-based-auth", "config": {"x509-cert-auth.mapper-selection": "Username or Email", "x509-cert-auth.mapping-source-selection": "Subject'\''s Common Name", "x509-cert-auth.mapper-selection.user-attribute-name": "usercertificate", "x509-cert-auth.regular-expression": "(.*?)(?:$)", "x509-cert-auth.crl-relative-path": "crl.pem", "x509-cert-auth.confirmation-page-disallowed": true } }'

If i do not give any config this works on default.  Do we have something changed in KC25 ( may be some datatype in mysql db)
 
highly appreciate the response

**Comment by rmartinc** [comment]
Hi! Can you please add trace level and attach the logs?

`--log-level INFO,org.keycloak.authentication.authenticators:TRACE,org.keycloak.services.x509:TRACE`
