### ISSUE TITLE
Keycloak In Docker: ERROR: Strict hostname resolution configured but no hostname setting provided

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#33539]
### Discussed in https://github.com/keycloak/keycloak/discussions/20437

<div type='discussions-op-text'>

<sup>Originally posted by **archmangler** May 18, 2023</sup>
I'm following this keycloak documentation on how to get the KC optimised image running on docker:

https://www.keycloak.org/server/containers

I get the following cryptic error when trying to run the "optimized" keycloak docker image:

```
(base) welcome@Traianos-MacBook-Pro keycloak-docker % docker run --name mykeycloak -p 8443:8443 \
        -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=P@ssw0rd \
        quay.io/keycloak/keycloak:latest \
        start --optimized
ERROR: Unexpected error when starting the server in (production) mode
ERROR: Failed to start quarkus
ERROR: Strict hostname resolution configured but no hostname setting provided
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

It's not clear from the documentation how to resolve this error:

```
ERROR: Strict hostname resolution configured but no hostname setting provided
```

Any idea how to resolve this?
</div>

**Comment by jonkoops** [comment]
Considering the 26.0.0 release is going out now, I think we should land this as a bug fix for 26.0.1. WDYT @shawkins?
