### ISSUE TITLE
Unable to submit forms in Safari

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#33557]
When building Keycloak from source and navigating to `http://localhost:8080` every form submission ends in an error. For example, when creating the initial admin user in the welcome page, or when submitting the form to sign-in on the login. This was tested on the recently released Safari 18.0, I am not sure if this problem occurs in earlier versions.

## Steps to reproduce
- Download the Keycloak 26 release (https://www.keycloak.org/downloads)
- Extract the archive and run Keycloak with `./bin/kc.sh start-dev`.
- Navigate to http://localhost:8080 and fill in the admin user form on the welcome page
- Submit the form and observe a server error on the page (see below)

<img width="917" alt="Screenshot 2024-10-04 at 12 12 10" src="https://github.com/user-attachments/assets/126300e8-163f-40b4-9d93-1d7c77ffb94d">

**Comment by jonkoops** [comment]
Even when creating the admin user in a different browser it is also not possible to log in with this user on Safari. When attempting to log into the admin console the following error pops up:
<img width="921" alt="Screenshot 2024-10-04 at 12 13 31" src="https://github.com/user-attachments/assets/654e45d2-dc94-4812-a064-04ed508dc5ca">

**Comment by jonkoops** [comment]
Little update on this, we have determined the issue is only present during local development. The cause of the issue is that Safari does not support setting the [`Secure`](https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies#secure) directive on cookies on a local origin (e.g. `localhost` or `.localhost`), even if it is a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). This is problematic, as we need to set `Secure` on cookies that are `SameSite=None`, otherwise they will simply not be set in the majority of browsers.

As a resolution we'll likely be downgrading the `SameSite=None` cookies to `SameSite=Lax`, which will work, but have some [negligible downsides](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#lax). We already do this type of 'same-site downgrading' when [running in an insecure context](https://github.com/keycloak/keycloak/blob/14f14152dee691d61274fa73638fc67971243be9/services/src/main/java/org/keycloak/cookie/DefaultCookieProvider.java#L53-L55).

Considering this issue impacts development on Safari only we will keep the priority, but we'll not be rushing out a fix. Whenever we decide to do a patch this issue should be fixed alongside.

**Comment by dhohner** [comment]
A quick workaround for ppl affected by this, who need to use safari for local testing would be to set up an alias in their /etc/hosts file that is compliant with the official cookie spec.

Working Example:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
127.0.0.1       dev.local
255.255.255.255	broadcasthost
::1             localhost
```

When using dev.local:8080 I was able to create the admin user using Safari 18.0.1

**Comment by jonkoops** [comment]
@dhohner I assume that you are running Keycloak over a local HTTPS connection in this case?

**Comment by dhohner** [comment]
I started Keycloak 26 in local development mode (`./bin/kc.sh start-dev`) without https.

**Comment by dhohner** [comment]
Will try to reproduce this on a secure domain. I ran into the same problem on a different project on earlier Versions of Safari. Need to check out what we did to fix it then.

**Comment by jonkoops** [comment]
No worries, it doesn't change the outcome of the fix. We'll have to detect the user agent of Safari and assume that anything that is not on HTTPS is not secure by default. Real shame, because all other browsers implement this consistently.
