### ISSUE TITLE
Add proto-schema-compatibility-maven-plugin check against release/26.0 branch to main

### ISSUE THREAD

**Issue by ryanemerson** [keycloak/keycloak#33565]
### Description

Add proto-schema-compatibility-maven-plugin check against release/26.0 branch to main to ensure that development on the `main` branch does not break compatibility with existing 26.0.x releases.

**Comment by ahus1** [comment]
@ryanemerson - adding the `backport/26.0` label here as I understand from the title that you want to have this also in the release branch.

**Comment by ryanemerson** [comment]
@ahus1 There shouldn't be a need for this to be in the release/26.0 branch as we're checking against the proto.lock file that exists in that module, so no need for a remote check as well as the local one.

**Comment by ahus1** [comment]
OK, thanks. Removing the backport label then.

**Comment by y-tabata** [comment]
@ryanemerson @ahus1 
Just for your information, we have confirmed that this change causes the build to fail in an environment under a proxy.
If we commented out the following, the build passed.
https://github.com/keycloak/keycloak/blob/main/model/infinispan/pom.xml#L113-L115

The build error is the following:
```
[ERROR] Failed to execute goal org.infinispan.protostream:proto-schema-compatibility-maven-plugin:5.0.12.Final:proto-schema-compatibility-check (default) on project keycloak-model-infinispan: An error occurred while running protolock: Connection timed out -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.infinispan.protostream:proto-schema-compatibility-maven-plugin:5.0.12.Final:proto-schema-compatibility-check (default) on project keycloak-model-infinispan: An error occurred while running protolock
```

**Comment by ryanemerson** [comment]
The failure is because the maven plugin is trying to retrieve a remote file from GitHub in order to check protobuf compatibility with a prior version. You can skip this check by adding the `-DskipProtoLock=true` property when building Keycloak.
