### ISSUE TITLE
Timeout Issue with Keycloak Admin Client Behind a Proxy

### ISSUE THREAD

**Issue by chriskoutr** [keycloak/keycloak#33579]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

We have a Keycloak instance deployed in a separate VM wich is connected with a spring boot application.
There is a reverse proxy and a firewall between them and the requests should pass through them.
Although, there is no issue on deployment or login, when we use keycloak-admin-client methods, we receive a timeout exception (after 2 minutes).
We have identified that the issue occurs inside invoke method of ApacheHttpClient43Engine
Specifically the request that faces the timeout is /realms/{realm}/protocol/openid-connect/token when we user user.toRepresentation() method.

Keycloak version: 24.0.5
keycloak-admin-client version: 24.0.5

The exact same applications in a different environment, without proxy, works as expected.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Receive token and user object from Keycloak.

### Actual behavior

Receive a timeout error after 2 minutes.

### How to Reproduce?

Deploy Spring Boot application that uses Keycloak as Iam service behind a proxy.

**Comment by shawkins** [comment]
The proxy timeout is probably masking another issue on the server. Can you increase the proxy timeout to see how long the request actually takes and if you hit any exception on the server side - such as a database connection pool timeout.

**Comment by chriskoutr** [comment]
We finally managed to resolve it.
This was not a server side issue, but a `keycloak-admin-client` library issue, related with resteasyClient.

We had to set the URLConnectionEngine, as http engine of the client, and set the proxy properties on it.


```
URLConnectionEngine engine = new URLConnectionEngine();
			engine.setProxyHost(proxyHost);
			engine.setProxyPort(proxyPort);
			engine.setProxyScheme("http");

Client client = (ResteasyClientBuilder) ClientBuilder.newBuilder())
				.httpEngine(engine).build();

KeycloakBuilder.builder().serverUrl(keycloakServerUrl)
			        ...
                                .resteasyClient(customizedResteasyClient())
				.build();
```

After setting the above, the application was working as expected and it was able to fetch users' data, using `keycloak-admin-client` methods.
