### ISSUE TITLE
X-Forwarded-Proto is not effective

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#33581]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Using `ngrok` in front of Keycloak it sends the `X-Forwarded-Proto`, but Keycloak does not take that in effect on the URLs.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

URLs should use `https` when `X-Forwarded-Proto=https` is sent

### Actual behavior

URLs use `http` when `X-Forwarded-Proto=https` is sent

### How to Reproduce?

Start Keycloak locally with `kc.sh start-dev --proxy-headers forwarded --hostname-debug true`

Run ngrok with `ngrok http 8080`

Open `https://<NGROK URL/realms/master/hostname-debug`. The output should show something like:

![image](https://github.com/user-attachments/assets/8c8e6832-f1ba-433c-9e9c-6f51ec3cab55)

From this you can see that frontend, backend, and admin URLs, use the hostname from `X-Forwarded-Host`, but ignores `X-Forwarded-Ports`.

**Comment by vmuzikar** [comment]
This seems to be caused by a misconfiguration. `X-Forwarded-*` headers are sent but Keycloak is configured to accept the `Forwarded` header via `--proxy-headers forwarded`.

~action/invalid

**Comment by stianst** [comment]
Maybe I did something wrong here as I should have used `--proxy-headers xforwarded`. However, question then is why is it using `X-Forwarded-Host` header?

**Comment by vmuzikar** [comment]
> However, question then is why is it using `X-Forwarded-Host` header?

Why do you thing the `X-Forwarded-Host` header is used? Looks to me the same hostname is used both in `Host` and `X-Forwarded-Host` headers, no?

**Comment by shawkins** [comment]
@stianst it's acutally using the Host header - that's enabled implicitly for either value of proxy-header.
