### ISSUE TITLE
Support an option to disable TLS/SSL

### ISSUE THREAD

**Issue by martino87r** [keycloak/keycloak#33594]
### Description

I'm stuck in a loop where the latest version of Keycloak (26) enforces SSL/TLS certificate presence at startup without any documented way to disable it.

### Discussion

https://github.com/keycloak/keycloak/discussions/33588

### Motivation

I'm behind an SSL/TLS terminating loadbalancer which manages certificates for every application behind it, I don't want to manage certificates for keycloak

### Details

Please add an option in the configuration file as logic dictates:
```
   http-enabled=true
-> https-enabled=false
```

**Comment by shawkins** [comment]
https-enabled=false is not needed. If you have not provided key material and http-enabled is true, then only http will be exposed.

**Comment by martino87r** [comment]
Please before closing an issue make sure what you're stating is true:

config:
```
db-url=jdbc:postgresql://localhost/keycloak

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP
http-host=127.0.0.1
http-port=3005
proxy-address-forwarding=true
proxy-headers=xforwarded
# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
hostname=localhost
```
Output:
```
sh-5.2$ ./bin/kc.sh start
Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
```

**Comment by martino87r** [comment]
My apologies somewhere along the path I lost track of http-enabled.
It seems to work as expected
