### ISSUE TITLE
Add a reference to http-enabled in TLS/SSL setup

### ISSUE THREAD

**Issue by martino87r** [keycloak/keycloak#33605]
### Description

By assumption I omitted the `http-enabled` config key only to be greeted by the following message during startup:
```
Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
```

It would be more helpful to inform the user that if they want HTTP only mode to be enabled they would have to do the following:

- Define option `http-enabled`
- Omit the keystore/cert path definitions
- Or implement something like `https-enabled` for the explicit crowd :)

### Discussion

https://github.com/keycloak/keycloak/discussions/33588

### Motivation

Following the official documentation led me to this error message

### Details

[Relevant docs](https://www.keycloak.org/server/enabletls)

**Comment by shawkins** [comment]
@martino87r see https://github.com/keycloak/keycloak/pull/33795 for a proposed resolution. http-enabled is mentioned from the enabletls, hostname, and reverse proxy docs.

**Comment by martino87r** [comment]
@shawkins I'd say the PR is perfect, it will definitely prevent some poor souls in the future from going bald like me :)
