### ISSUE TITLE
Fix v2 login layout

### ISSUE THREAD

**Issue by Theta-Dev** [keycloak/keycloak#33607]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I have just updated my Keycloak instance and noticed that the login page now has a new theme. The new theme has 2 issues though:

1. The title is now placed in one line with the language selector and wraps multiple times depending on language and screen size. This makes the title hard to read
2. The top margin of the login page was more than doubled, which makes the page look kind of awkward (you have to move your mouse way down to interact with the login form, this may also be exaggerated by the multi-line title)

# Login v1
![grafik](https://github.com/user-attachments/assets/cb0d2a21-ca7e-4966-bc2e-7428bb409e96)

# Login v2
![grafik](https://github.com/user-attachments/assets/8d9ef0b8-3cad-47b7-94d2-9da0ae7e66a8)

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

- Have a clearly readable title
- Have a login in form that is aligned at the top or center of the page

### Actual behavior

- The new login UI has too much top margin
- The title bar and the language selector clash with eachother, the title wraps multiple times depending on language and screen size

### How to Reproduce?

- Open the login screen with the keycloak.v2 theme enabled in Realm settings > Themes

**Comment by jonkoops** [comment]
ping @keycloak/ui

**Comment by edewit** [comment]
This is actually how it was designed by PF

**Comment by edewit** [comment]
@Theta-Dev your language dropdown is extremely wide what language is that does that? On mine it looks like this:
![image](https://github.com/user-attachments/assets/07e4652a-4c69-49b6-afeb-98afba7777fd)

**Comment by edewit** [comment]
it does the same on the PF example page:
![image](https://github.com/user-attachments/assets/5135e563-1ba9-406a-9a59-8f2cdb7b30e1)

**Comment by Theta-Dev** [comment]
I guess the longest language name was "Brazilian Portuguese".

After I removed all languages except English and German, the layout looks like you showed above.
