### ISSUE TITLE
Scheduled workflows fail to start

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#33625]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Due to lack of permissions, scheduled workflows are not started

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

The scheduled workflows should run

### Actual behavior

They don with a "403" error.

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/11206384063/job/31147062437

### Anything else?

This seems to be caused by #33534

**Comment by stianst** [comment]
Breaking changes reverted here: https://github.com/keycloak/keycloak/commit/058538ca08d68d84c717a7c2b4bca9fcf49c9922
