### ISSUE TITLE
Error when opening user admin page

### ISSUE THREAD

**Issue by oboudet-beetween** [keycloak/keycloak#33633]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When opening the users admin page in a realm with user federation, an error is displayed : 

![image](https://github.com/user-attachments/assets/a54109b3-745a-43b0-98c4-8580dd45a856)

A 400 status code is returned on `/admin/realms/master/ui-ext/brute-force-user?briefRepresentation=true&first=0&max=11&q=&exact=false` 

![image](https://github.com/user-attachments/assets/e03f8b02-e8dd-4cca-85e3-f3e315323773)

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

No error should be displayed

### Actual behavior

A "cannot parse JSON" is displayed

### How to Reproduce?

- run keycloak 26.0.0
- configure a user storage SPI
- display the user admin page

**Comment by jonkoops** [comment]
Sound to me like a bug in whatever SPI you are using for the storage. Either way, this is not a UI issue as the error is returned from the server.

**Comment by oboudet-beetween** [comment]
Ok, you are right, it is a user storage SPI which is causing this error. `searchForUserStream` was called with a `nul` `UserModel.SEARCH` param and causing a NPE.
