### ISSUE TITLE
Login theme using new ui components

### ISSUE THREAD

**Issue by alex-enchi** [keycloak/keycloak#33634]
### Description

Hi all,

I was really excited to learn about https://www.keycloak.org/2024/09/keycloak-customizable-ui

But after reading through docs and source code, I could not find anything related to Login theme

Am I right that there is not support for Login themes using new components? At the moment I am a bit lost.

As far as I can tell `npm create keycloak-theme@latest my-theme` supports only account ui

Best

**Comment by jonkoops** [comment]
Hi, if you have questions please use the mailing list or forums. The issue tracker is meant for issues only. To answer your question, no the login does not use these new components, as it is not React based. The login uses traditional FreeMarker templates for customization. See the ['Themes' section](https://www.keycloak.org/docs/latest/server_development/index.html#_themes) of the server development guide.
