### ISSUE TITLE
Non-optimized start command gives erroneous warnings for runtime spi options

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#33638]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

A non-optimized start command gives erroneous warnings for runtime spi options:

2024-10-07 16:52:42,791 WARN [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following run time options were found, but will be ignored during build time: kc.spi-realm-restapi-extension-mytest-identity-provider-vault-password ...

### Version

26.0

### Regression

- [X] The issue is a regression

### Expected behavior

No warnings should be emitted.

### Actual behavior

A warning about runtime spi options being ignored.

### How to Reproduce?

Run a non-optimized start command that includes a runtime spi option, or a value that maps to one such as --hostname-strict=false.

**Comment by vmuzikar** [comment]
@shawkins Given this is a regression, added the backport label.

**Comment by mduchrow** [comment]
This is probably related to #33902

**Comment by shawkins** [comment]
This is not directly related to https://github.com/keycloak/keycloak/issues/33902 - it is related to the changes I have with #33760 - there is a mismatch between the logic persisting values and what the initial check considers a config change.
