### ISSUE TITLE
RTL not working on keycloak.v2 login template

### ISSUE THREAD

**Issue by senyahnoj** [keycloak/keycloak#33642]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When you use the "base" login theme, it correctly adds a dir="rtl" attribute to the page HTML tag which renders the page Right-to-left in locales like Arabic.

![Screenshot from 2024-10-07 14-20-13](https://github.com/user-attachments/assets/2e911793-1803-493e-a198-064ddb8b9c26)

On the new "keycloak.v2", this HTML attribute is not set in the template. 

Consequently, the page does not render Right-To-Left as it should do.

![Screenshot from 2024-10-07 14-18-29](https://github.com/user-attachments/assets/1419ca16-ea23-4e55-b259-8865de4d2354)

(When I use the web development console in my browser and manually add the missing dir="rtl" attribute to the opening <html> tag it has the desired effect: reverses the page direction. Therefore I think it's just the missing attribute which is causing the problem).

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect, if the locale represents a RTL (Right-To-Left) language, the page will be displayed accordingly in the new keycloak.v2 login theme.

### Actual behavior

Page is not being displayed RTL on the "keycloak.v2" login page. It is being correctly displayed when we switch the realm to use the "base" template for login theme.

### How to Reproduce?

In Keycloak 26.0.0 use the "keycloak.v2" login theme. Internationalization must be enabled and you must include Arabic (ar) as a supported locale.

Go to the login page and switch the locale to Arabic in the drop-down chooser.

**Comment by rmartinc** [comment]
Hi @senyahnoj!

Yes, you are right, you just need to add the missing attribute in the `themes/src/main/resources/theme/keycloak.v2/login/template.ftl`. Can you please test and send a little PR like the following?

```diff
--- a/themes/src/main/resources/theme/keycloak.v2/login/template.ftl
+++ b/themes/src/main/resources/theme/keycloak.v2/login/template.ftl
@@ -22,7 +22,7 @@
 
 <#macro registrationLayout bodyClass="" displayInfo=false displayMessage=true displayRequiredFields=false>
 <!DOCTYPE html>
-<html class="${properties.kcHtmlClass!}"<#if realm.internationalizationEnabled> lang="${locale.currentLanguageTag}"</#if>>
+<html class="${properties.kcHtmlClass!}"<#if realm.internationalizationEnabled> lang="${locale.currentLanguageTag}" dir="${(locale.rtl)?then('rtl','ltr')}"</#if>>
 
 <head>
     <meta charset="utf-8">
```

If you cannot d it, 'll try to add it in the following days...

**Comment by ahus1** [comment]
@senyahnoj - there is another issue that is marked "help wanted" which notes that in the old theme the inputs had some hardcoded `dir="ltr"` in some places which wasn't migrated to the Login v2 theme  - see #32844.
It would be great if you could have a look at that one as well.
