### ISSUE TITLE
 keycloak-js register broken: createRegisterUrl not awaited

### ISSUE THREAD

**Issue by anst270125** [keycloak/keycloak#33645]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

Registering using keycloak-js is broken because of incorrect redirectUri after updating to v26.  The docs [clearly indicate](https://www.keycloak.org/docs/latest/upgrading/index.html#methods-for-login-are-now-async) to await `createRegisterUrl` function but keycloak-js doesn't. 

Definition: https://github.com/keycloak/keycloak/blob/0a1f28c5fca6fedb0f640c81285fa03c754fbff2/js/libs/keycloak-js/lib/keycloak.js#L510
Usage:
https://github.com/keycloak/keycloak/blob/0a1f28c5fca6fedb0f640c81285fa03c754fbff2/js/libs/keycloak-js/lib/keycloak.js#L1333

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Register should work

### Actual behavior

Register doesn't work

### How to Reproduce?

Register

**Comment by jonkoops** [comment]
Thanks for reporting this @anst270125. I will create a fix for this asap.
