### ISSUE TITLE
Customizable footer (Keycloak 26) not displaying in keycloak.v2 login theme

### ISSUE THREAD

**Issue by senyahnoj** [keycloak/keycloak#33640]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

In the release announcement for Keycloak 26 https://www.keycloak.org/2024/10/keycloak-2600-released it states

> h2. Customizable Footer in login Themes
>
> The template.ftl file in the base/login and the keycloak.v2/login theme now allows to customize the footer of the login box. This can be used to show common links or include custom scripts at the end of the page.
> 
> The new footer.ftl template provides a content macro that is rendered at the bottom of the "login box".

Following the documentation, I have created a new extension theme based on keycloak.v2 with the following theme.properties file.

```
parent=keycloak.v2
import=common/keycloak
styles=css/styles.css
```

I have also created the footer.tpl from the example given in the server docs at https://www.keycloak.org/docs/26.0.0/server_development/#_theme_custom_footer and put it in the same folder as the theme.properties file.

```
<#macro content>
<#-- footer at the end of the login box -->
<div>
    <ul id="kc-login-footer-links">
        <li><a href="#home">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
    </ul>
<div>
</#macro>
```

The contents of the footer are not displaying on the login screens as expected.

It appears to work on the base theme though. I can get this to work by changing parent=base in the theme.properties like this.

```
parent=base
import=common/keycloak
styles=css/styles.css
```

So I'm concluding that this must be a bug in the keycloak.v2 theme. I'd be grateful if someone could investigate.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

My expectation is that the customized footer template should display when extending both the "base" and "keycloak.v2" themes.

### Actual behavior

The customized footer template only displays when extending the "base" theme, NOT on the "keycloak.v2" themes.

### How to Reproduce?

Create your own theme with the following theme.properties

```
parent=keycloak.v2
import=common/keycloak
styles=css/styles.css
```

**Comment by rmartinc** [comment]
@ssilvert I think the footer is just included in the base login template ([here](https://github.com/keycloak/keycloak/blob/26.0.0/themes/src/main/resources/theme/base/login/template.ftl#L168)) but not in the keycloak.v3 theme ([here](https://github.com/keycloak/keycloak/blob/26.0.0/themes/src/main/resources/theme/keycloak.v2/login/template.ftl)). Is this done on purpose? Or just an oversight?

**Comment by ssilvert** [comment]
@rmartinc Probably an oversight.  I'm guessing that whoever added this to login v1 forgot to add it to v2.

**Comment by senyahnoj** [comment]
Look like the footer _was_ added to the keycloak.v2 login template in https://github.com/keycloak/keycloak/commit/dbd4079f923565ecd06dca5dac6f6cb8fa8462d2 but subsequently removed in https://github.com/keycloak/keycloak/commit/e410a83c3ca449ab672705b9407b05765b3cbffb

Thanks @edewit for your PR
