### ISSUE TITLE
"Acquisition timeout while waiting for new connection" when loadtesting at 20 logins a second

### ISSUE THREAD

**Issue by paul-civitas** [keycloak/keycloak#33656]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When load testing with 20 users per second, there's a timeout that leads to a cascade of failures resulting in a "prod down" scenario.

Loadtesting command:
`./kcb.sh "--server-url=https://keycloak-loadtest.us-preprod.private.civitaslearning.com" "--scenario=keycloak.scenario.authentication.AuthorizationCode" "--users-per-realm=99" "--measurement=120" "--users-per-sec=20"`

Pods are 4GB RAM 2 CPU each, 3 pods.

Database is Postgres 16.3, db.m7g.xlarge instance on AWS (4 cpu 16GB of RAM0.

This is a regression of https://github.com/keycloak/keycloak/issues/17161 many people (at least 10 judging from the number of thumbs up) in the thread are also saying they're having the same issue, however the issue was closed as completed and not revisited.

The initial error is:

```
{"timestamp":"2024-10-07T17:16:20.985483352Z","sequence":13722,"loggerClassName":"org.jboss.logging.DelegatingBasicLogger","loggerName":"org.hibernate.engine.jdbc.spi.SqlExceptionHelper","level":"ERROR","message":"Acquisition timeout while waiting for new connection","threadName":"executor-thread-145","threadId":1222,"mdc":{},"ndc":"","hostName":"keycloak-1","processName":"QuarkusEntryPoint","processId":1}
```

Following that there's errors such as:
```"ISPN000324: Cache 'authenticationSessions' is in 'STOPPING' state and this is an invocation not belonging to an on-going transaction, so it does not accept new invocations. Either restart it or recreate the cache container.","frames":[{"class":"org.infinispan.interceptors.impl.InvocationContextInterceptor"```
As the dominos start to fall.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

With sufficient resources keycloak is able to handle a modest production workload.

### Actual behavior

All nodes eventually crash.

### How to Reproduce?

`./kcb.sh "--server-url=https://keycloak-loadtest.us-preprod.private.civitaslearning.com" "--scenario=keycloak.scenario.authentication.AuthorizationCode" "--users-per-realm=99" "--measurement=120" "--users-per-sec=20"`

Using a postgres database.

### Anything else?

I understand if you want to close this due to this being reproduced on keycloak 24, but due to the number of people reporting this regression I felt compelled to open this issue.

**Comment by paul-civitas** [comment]
I've learned from the CNCF slack that there's well known serious performance issues on keycloak 24.

**Comment by paul-civitas** [comment]
Apparently there's an article even about the serious performance issues with keycloak 24: https://www.cloud-iam.com/post/keycloak-v24-release-performance-issues

**Comment by paul-civitas** [comment]
Confirmed that upgrading to keycloak 25 resolves this issue.

**Comment by samyvenkat** [comment]
Upgraded to 25 and still encountering this issue.

**Comment by jonkoops** [comment]
If you are still experiencing problems on the latest version of Keycloak (26) then please file a new issue.
