### ISSUE TITLE
IdP prefetch results in "Page has expired" in Chrome

### ISSUE THREAD

**Issue by june07** [keycloak/keycloak#33665]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

![image](https://github.com/user-attachments/assets/816c19f6-30ba-4423-a5d7-159c30e27387)
Simply clicking any of these will fail, but opening in a new tab will work.

When using any identity provider (tried GitHub, Microsoft, GitLab, and Google) Chrome prefetches the broker login URL which results in two requests being sent and the second resulting in "Page has expired".

![image](https://github.com/user-attachments/assets/7cb537ed-c03f-446a-b712-040503bbf55e)

Opening the IdP link in a new tab however avoids the prefetch and the request properly gets forwarded via the 303 reply from KC.

Opening in a new tab works fine:
![image](https://github.com/user-attachments/assets/5a08e983-4b05-406d-a10f-97fd522f6afe)

Not sure if this is a bug but I also don't understand how this isn't affecting lots more people?! It was hard to track down and find any information on it and/or figure out what was going wrong.

This was all I could find:
https://stackoverflow.com/questions/55692452/how-to-avoid-chrome-prefetch-request-at-oauth-flow

The problem doesn't happen in Firefox because no prefetching attempts occur.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Clicking IdP links should redirect without showing "Page has expired"

### Actual behavior

Clicking IdP links shows "Page has expired" instead of forwarding to identity provider

### How to Reproduce?

Just try to login by using an IdP signin link.

**Comment by hiennq99** [comment]
i got also

**Comment by june07** [comment]
Seems this is likely the culprit for our issues!  Turning this off resolved the prefetch problem.  And it seems to have been rolled out recently: https://community.cloudflare.com/t/speculation-rules-api-rollout-to-free-plans/708111/21

In my opinion, it's bad when an upstream provider just toggles a feature which breaks stuff instead of making it an opt-in thing!

![image](https://github.com/user-attachments/assets/107dcbd2-5d71-480d-9ad2-07d04e000bc4)

**Comment by june07** [comment]
@hiennq99 might help you as well...

**Comment by laopaoer-wallet** [comment]
i got also

**Comment by laopaoer-wallet** [comment]
> Seems this is likely the culprit for our issues! Turning this off resolved the prefetch problem. And it seems to have been rolled out recently: https://community.cloudflare.com/t/speculation-rules-api-rollout-to-free-plans/708111/21
> 
> In my opinion, it's bad when an upstream provider just toggles a feature which breaks stuff instead of making it an opt-in thing!
> 
> ![image](https://private-user-images.githubusercontent.com/11353590/374717200-107dcbd2-5d71-480d-9ad2-07d04e000bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDkzMjgsIm5iZiI6MTcyODQ0OTAyOCwicGF0aCI6Ii8xMTM1MzU5MC8zNzQ3MTcyMDAtMTA3ZGNiZDItNWQ3MS00ODBkLTlhZDItMDdkMDRlMDAwYmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA0NDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTAwMGRlOTU2Yzc0ODkxMDE0NTczY2Q1ZTUzMGIxOTIzOTRlYWNiNThjMDE2Y2NkYWQ2M2NjZWIzZmY3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c1bgf1BPoojyRSYLK6FD6QpqY29eUZcTXdFHi5a43SQ)

Thanks,its work!
