### ISSUE TITLE
Userprofile Textarea is not working still shows a textbox 

### ISSUE THREAD

**Issue by parthbulusu** [keycloak/keycloak#33662]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

RealmSettings>UserProfile>CreateAttribute
Select Annotation 'InputType: TextArea' Also addeds cols and rows
The attribute under user is expected to show a textarea, still showing text box

### Version

25

### Regression

- [X] The issue is a regression

### Expected behavior

Show textarea should also work with rows and colums

### Actual behavior

Shows textbox(default)

### How to Reproduce?

RealmSettings>UserProfile>CreateAttribute
Select Annotation 'InputType: TextArea' Also addeds cols and rows
The attribute under user is expected to show a textarea, still showing text box

**Comment by ssilvert** [comment]
Please try with Keycloak 26.

**Comment by ssilvert** [comment]
@parthbulusu I have verified that in Keycloak 26, a Text Area is rendered in admin console, account console, and user registration.

I'm closing this one.

**Comment by parthbulusu** [comment]
Stan,
I have downloaded keycloak 26, and I can reproduce the same.  Please let me
know if I'm missing something.
I still see it as textbox (Htpm <input type text>) for a text area
(Expecting Html <textarea>)

[image: image.png]

[image: image.png]

**Comment by ssilvert** [comment]
@parthbulusu Your images are not getting attached properly?

**Comment by parthbulusu** [comment]
Attached Images again
<img width="718" alt="textarea-issue-1" src="https://github.com/user-attachments/assets/51f4cc42-751a-495f-a996-7d27f81baf92">
<img width="943" alt="text-area-issue-2" src="https://github.com/user-attachments/assets/91cf9618-9c64-4b8d-94cc-56ee51c16748">

**Comment by ssilvert** [comment]
I re-created your problem.  Looks like you have "Multivalued" set to "On" in the general settings.  That will override your `textarea` annotation.
