### ISSUE TITLE
Cannot configure `spi-email-template-provider`

### ISSUE THREAD

**Issue by koplas** [keycloak/keycloak#33683]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Keycloak won't start with the `--optimized` flag if spi-email-template-provider is specified. This worked without a warning in Keycloak 25.0.6.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak starts without issues.

### Actual behavior

Keycloak won't start.

### How to Reproduce?

Add to keycloak.conf the following line:
```
spi-email-template-provider=freemarker
```

Run `bin/kc.sh build` and then `bin/kc.sh start --optimized`. The following error is now printed:
```
ERROR: The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.spi-email-template-provider
```

### Anything else?

This seems to be introduced with https://github.com/keycloak/keycloak/commit/10fae5de7ac91093516ec27083495e25053b11dc and https://github.com/keycloak/keycloak/commit/d5d6390b1c3a4ebf938870475a5769f7a2f1a557. Note that in Keycloak 25.0.6 no warning is printed.

Update: Other `spi-` options are also affected. For example, setting `spi-user-cache-infinispan-enabled=false` results in the following error message:
```
ERROR: The following build-time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.spi-user-cache-infinispan-enabled
```

**Comment by shawkins** [comment]
> Keycloak won't start with the --optimized flag if spi-email-template-provider is specified. 

This is correct / expected behavior because spi-email-template-provider is a build time property and will not work with --optimized. See #27298

> This worked without a warning in Keycloak 25.0.6.

It would have worked in the sense that there was no warning / error, but it would not have influenced the spi behavior.

> Update: Other spi- options are also affected. For example, setting spi-user-cache-infinispan-enabled=false results in the following error message:

That is the same case.
