### ISSUE TITLE
Lots of flaky tests caused by chromedriver bug 

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak#33707]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Lots of recent flaky tests have been caused by a bug in chrome driver with WebElement.click(). The fix for this is in UIUtils.clickLink(). However, this has only been modified for the flaky tests that have been detected. We should switch all other uses of WebElement.click() with UIUtils.clickLink() to avoid future issues.

### Version

HEAD

### Regression

- [ ] The issue is a regression

### Expected behavior

No flaky tests caused by chrome driver WebElement.click()

### Actual behavior

Occasional flaky test failures

### How to Reproduce?

Run the tests frequently.

**Comment by abstractj** [comment]
@douglaspalmer do we have any idea about how many? If yes, could you please add to this issue the links?

**Comment by mposolda** [comment]
Closing as we will fix the issues on case by case basis. As the bulk update of all the links causes lots of other failures and hence doesn't work very well...
