### ISSUE TITLE
model/infinispan/proto.lock file in git working set

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#33711]
### Description

After a build of keycloak model/infinispan/proto.lock will show as a new file in git. 

@ryanemerson can this be added to ignored or moved to target?

**Comment by ryanemerson** [comment]
@shawkins This file shouldn't appear. I believe it's a bug with the ProtoStream plugin and the way it checks the remote file.

**Comment by ryanemerson** [comment]
The underlying issue is https://issues.redhat.com/browse/IPROTO-395. I'll create a PR to fix as soon as we have a new ProtoStream release
