### ISSUE TITLE
Create a new base login theme

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#33717]
### Description

With login v2, we are still extending the old keycloak theme (which extends the base theme).

We really should break away from this architecture as the old keycloak and base themes provide little value.  Furthermore, keeping things the way they are now could make it harder to remove login v1.

**Comment by jonkoops** [comment]
I think the idea was to remove the base theme altogether no?

**Comment by ssilvert** [comment]
For now, just talking about extending `base` instead of `keycloak`

**Comment by jonkoops** [comment]
Yes, that seems a good first step.
