### ISSUE TITLE
Not possible to configure custom client authenticator in Admin UI

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#33729]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Custom client authenticators support providing a list of provider config properties, that should make it configurable in the Admin UI. However, the Admin UI does not display any configuration options for the authenticator:

![image](https://github.com/user-attachments/assets/a76572c7-7049-4485-976f-ee16253dd770)

The example authenticator is defining a number of config options that should be visible:

```
@Override
public List<ProviderConfigProperty> getConfigPropertiesPerClient() {
    return List.of(
            new ProviderConfigProperty("sub", "Subject", "Subject", ProviderConfigProperty.STRING_TYPE, null),
            new ProviderConfigProperty("aud", "Audience", "Audience", ProviderConfigProperty.STRING_TYPE, null),
            new ProviderConfigProperty("jwks", "JWKs", "JWKs", ProviderConfigProperty.STRING_TYPE, null));
}
```

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

A form is displayed allowing configuring any provider config properties defined by the authenticator.

### Actual behavior

No form is displayed.

### How to Reproduce?

Deploy a custom provider:
```
git clone https://github.com/stianst/playground
cd playground/kc-ext/spiffe-authenticator
mvn install
cp target/spiffe-authenticator.jar <KC_HOME>/providers>
```

In admin console create a client that requires authentication, and select `spiffe-jwt-svid` as the client authenticator under the credentials tab.

### Anything else?

I'm fairly certain this was supported in the old Admin UI, and is something that is missing in the new Admin UI.

Although I've done my best in implementing the custom authenticator, there may be something wrong with it, or there may be an issue on the server side.

One thing to note is the interface states `isConfigurablePerClient` should be `true`:

https://github.com/keycloak/keycloak/blob/a276b3bb3db3d1af497e1c08db13859904b3cc0a/server-spi-private/src/main/java/org/keycloak/authentication/ClientAuthenticatorFactory.java#L48-L54

However, there is no `isConfigurablePerClient` method defined in `ClientAuthenticatorFactory`.

**Comment by ssilvert** [comment]
@mposolda Just let us know when the changes are done on the server side and we will implement the UI part.

**Comment by stianst** [comment]
@ssilvert Just tested the provider on KC 20 with the old admin console, and it works just fine there:
![image](https://github.com/user-attachments/assets/54f39637-09f9-4709-b21c-48a2cbf2254b)

So, think this is an UI issue only.

**Comment by sblommers** [comment]
26.1.0 was released today so I immediately started testing, the custom client fields are now visible and editable but I do get an error when saving it:

**_Client could not be updated: Invalid json representation for ClientRepresentation. Unrecognized field "config" at line 1 column 3612._**

**Comment by sblommers** [comment]
[keycloak-client-iprange.zip](https://github.com/user-attachments/files/18437431/keycloak-client-iprange.zip)
I added a simple maven project to test it.
