### ISSUE TITLE
Create regular Windows installer

### ISSUE THREAD

**Issue by eloydegen** [keycloak/keycloak#33737]
### Description

If I want to use Keycloak on Windows I have to run the `bin/kc.bat` file to start it up. Some security software that wants to enumerate all installed software on a host checks the items within `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`

But Keycloak does not add an entry to this list and is therefor harder to detect, because it would require scanning the entire filesystem to determine if Keycloak is somewhere.

Could a Windows installer be created to fix this?

**Comment by stianst** [comment]
Delivering a Windows installer is not something we will do
