### ISSUE TITLE
Organizations section is shown in account console if organizations is not enabled for a realm.

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#33735]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Organizations section is visible if Organizations support is disabled for a realm.

See: 
![image](https://github.com/user-attachments/assets/2d355d10-a653-4a78-9065-4b18ee911326)

![image](https://github.com/user-attachments/assets/5fe8907f-55eb-4356-a63e-e7471f056f3c)

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Organizations section should only be shown if organizations are enabled for a realm.

### Actual behavior

Organizations section is visible if Organizations support is disabled for a realm.

### How to Reproduce?

1) Disable organizations for a realm
2) Access the account console for the realm

### Anything else?

This also affects Keycloak 25.x

**Comment by ahus1** [comment]
@thomasdarimont - please go ahead and do a backport for KC26. 

I read that you plan to do a backport for KC25, not sure if that is really something you want to do?

**Comment by thomasdarimont** [comment]
Thanks for taking a look. I'll create a PR for release/26.0.

KC25 is also affected by this and it's probably the same fix.

**Comment by thomasdarimont** [comment]
Added PR for backport to KC26

**Comment by ahus1** [comment]
Thank you for the backport PR. We don't plan any further community releases for KC25. If you still want to provide a backport, please do.
