### ISSUE TITLE
Client Policy throws "Invalid Redirect Uri" if Standard Flow is disabled

### ISSUE THREAD

**Issue by rene6502** [keycloak/keycloak#33734]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

In our project, we need to prevent OIDC clients from using an "open redirect." To achieve this, we implemented a Client Policy. Specifically, we use the secure-redirect-uris-enforcer with "Allow open redirect" set to "Off," and apply this policy across all clients.\
However, we are now facing an issue where clients without any defined redirect-uri are no longer deployable, as deployments fail with the error: "Invalid Redirect Uri: invalid uri."\
The problem arises with clients that have the "Standard Flow" disabled because they use only the Client Credentials flow. In such cases, no redirect-uri is required, and even the Admin UI does not display the redirect-uri field.\
The current implementation in SecureRedirectUrisEnforcerExecutor.java does not account for whether the "Standard Flow" is enabled or disabled.\
Relevant [source code line](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/clientpolicy/executor/SecureRedirectUrisEnforcerExecutor.java#L179)

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

SecureRedirectUrisEnforcerExecutor should ignore redirect-uris if Standard Flow is disabled.

### Actual behavior

SecureRedirectUrisEnforcerExecutor throws "Invalid Redirect Uri" if Standard Flow is disabled and no redirect-uri is present.

### How to Reproduce?

Use this script:
```bash
#!/bin/bash

./kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin

./kcadm.sh create realms -s realm=test -s enabled=true

./kcadm.sh update client-policies/profiles -r test -f - << EOF
{
  "profiles" : [ {
    "name" : "secure-redirect",
    "description" : "",
    "executors" : [ {
      "executor" : "secure-redirect-uris-enforcer",
      "configuration" : {
        "allow-http-scheme": true,
        "allow-ipv4-loopback-address": true,
        "allow-ipv6-loopback-address": false,
        "allow-open-redirect": false,
        "allow-private-use-uri-scheme": false,
        "allow-wildcard-context-path": true,
        "oauth-2-1-compliant": false
      }
    } ]
  } ]
}
EOF

./kcadm.sh update client-policies/policies -r test -f - << EOF
{
  "policies" : [ {
    "name" : "secure-redirect",
    "description" : "",
    "enabled" : true,
    "conditions" : [ {
      "condition" : "any-client",
      "configuration" : {
        "is-negative-logic" : false
      }
    } ],
    "profiles" : [ "secure-redirect" ]
  } ]
}
EOF

# the following request fails with "Invalid Redirect Uri: invalid uri [invalid_request]"
# by adding the following property it will succeed:
# "redirectUris": ["http://localhost/*"]
 ./kcadm.sh create clients -r test -f - << EOF
{
  "clientId": "test",
  "enabled": true,
  "protocol": "openid-connect",
  "clientAuthenticatorType": "client-secret",
  "secret": "changeme",
  "publicClient": false,
  "standardFlowEnabled": false,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": false,
  "serviceAccountsEnabled": true,
  "fullScopeAllowed": true
}
EOF
```

**Comment by zam6ak** [comment]
Using Keycloak 26.0.5 and this is still preventing use of policies that use built in profiles such as `oauth-2-1-for-confidential-client`
