### ISSUE TITLE
Linked organization column for identity providers says `Organization` instead of name

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#33742]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have an organization named `myorg`, which is linked to an identity provider. In the identity providers list this is displayed like this:

![image](https://github.com/user-attachments/assets/707ca9f4-9c6f-46dc-9394-62ea711dfbd6)

This should show the name of the organization, and it makes little sense to display `Organization` in the `Linked organization` column.

Additionally, there is no indication of an identity provider being linked when displaying the provider itself, and this is only visible in the list.
 

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Linked organization column displays the organization by name

### Actual behavior

Linked organization column displays the organization with the label `Organization`

### How to Reproduce?

Create an org, an idp, and link the two together. Then list idps.

**Comment by ssilvert** [comment]
@pedroigor @stianst Right now, the UI does not have information on the name of the organization from this screen.  We only have the ID.  I think we discussed this and decided that it would be too costly to provide the name to the UI?

**Comment by pedroigor** [comment]
DOn't remember ... But if we want to include the name of the organization we can do it by querying the org by ID.

**Comment by ssilvert** [comment]
> Don't remember ... But if we want to include the name of the organization we can do it by querying the org by ID.

@pedroigor 

So right now, we call something like:
http://localhost:8180/admin/realms/master/identity-provider/instances?first=0&max=101&realmOnly=false

And it returns an array of identity providers:
```
[
    {
        "alias": "keycloak-oidc",
        "displayName": "",
        "internalId": "c5bb1991-c2a3-4a5e-b2a3-f4fc1c4b2335",
        "providerId": "keycloak-oidc",
        "enabled": true,
        "updateProfileFirstLoginMode": "on",
        "trustEmail": false,
        "storeToken": false,
        "addReadTokenRoleOnCreate": false,
        "authenticateByDefault": false,
        "linkOnly": false,
        "hideOnLogin": true,
        "organizationId": "79d0ee04-e50e-48d6-b0f4-12552918f30a",
        "config": {
            "validateSignature": "false",
            "pkceEnabled": "false",
            "tokenUrl": "https://foo.bat",
            "clientId": "admin",
            "authorizationUrl": "https://foo.bar",
            "clientAuthMethod": "client_secret_post",
            "syncMode": "LEGACY",
            "clientSecret": "**********",
            "kc.org.domain": "foo.com",
            "kc.org.broker.redirect.mode.email-matches": "false"
        }
    }
]
```

Can you just add the organization name to each IDP?

**Comment by pedroigor** [comment]
Yes, we can. I was more thinking about not adding a `config` entry or a field but leveraging an existing endpoint from the Organization API. With the cost of a separate call for each item on the returned list.

It should be simpler to just add the name there but not sure if it will be too UI specific?

**Comment by ssilvert** [comment]
@pedroigor I'm assigning this to core.  You guys can decide what you want to do.  If you decide to move ahead just kick it back to us when you are ready for the UI part.

**Comment by pedroigor** [comment]
@ssilvert We have a second round of discussions about how to sort this one out and we agree about separate calls to obtain the name of the organization.

Even though we'll add this separate call, querying organizations by id should perform quite well in both the database and once the cache is hot. The main goal here is to avoid, at least for now, introducing fields to the broker representation that we don't really need but eventually adding them if we see the separate calls impacting the Admin API/console response time.

**Comment by ssilvert** [comment]
> @ssilvert We had a second round of discussions about how to sort this one out and we agreed about separate calls to obtain the name of the organization.

> Another point is that we have open discussions about sharing brokers across organizations. Introducing the organization name to the broker representation will be even worse in this case ...

In that case, I'm just going to close this one.  If sharing brokers is a possibility then using a name in the column won't make any sense at all.
