### ISSUE TITLE
Can't find Patternfly.min.css on 26.0.0

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#33740]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I have copied a theme from 25.0.4 to 26.0.0, and it seems it is broken. 
I see on the console that some resources are not reachable.

This is an error (404) I get with the default (keycloak.v2) theme: 

<img width="470" alt="Screenshot 2024-10-09 at 13 35 15" src="https://github.com/user-attachments/assets/6616efb8-b7ec-4a81-8f0e-23fc5b4be98f">

And this with my custom theme, also 404:

[
<img width="515" alt="Screenshot 2024-10-09 at 13 35 46" src="https://github.com/user-attachments/assets/656bff44-2fa4-4213-8a1a-5cc4e810f6f8">
](url)

Maybe it has something to do with the new proxy settings, but could it be something else?

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Themes should work as before

### Actual behavior

Custom theme gets quite broken.

### How to Reproduce?

Copy a custom theme from 25.0.4 to 26.0.0. 
See it can't reach some resources.

**Comment by oculos** [comment]
There are the default imports on my custom theme: 

```
parent=base
import=common/keycloak
stylesCommon=node_modules/@patternfly/patternfly/patternfly.min.css node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/pficon/pficon.css
```

**Comment by oculos** [comment]
Nevermind - it seems that the Common paths were updated:

```
stylesCommon=vendor/patternfly-v4/patternfly.min.css vendor/patternfly-v3/css/patternfly.min.css vendor/patternfly-v3/css/patternfly-additions.min.css lib/pficon/pficon.css
```

Is the new one. So I guess this can be closed, but I'll leave it open in case someone else has the same problem.

**Comment by jonkoops** [comment]
Thanks for the report @oculos. Since you managed to fix the problem I will go ahead and close the issue. I hope to improve resource management in the future in such a way that this will be less likely to clash, but it's on the backburner for now.

**Comment by oculos** [comment]
Shouldn’t this be mentioned on the migration guide?On 9 Oct 2024, at 17:19, Jon Koops ***@***.***> wrote:﻿
Thanks for the report @oculos. Since you managed to fix the problem I will go ahead and close the issue. I hope to improve resource management in the future in such a way that this will be less likely to clash, but it's on the backburner for now.

**Comment by jonkoops** [comment]
It is mentioned in [the upgrading guide](https://www.keycloak.org/docs/latest/upgrading/index.html#paths-for-common-theme-resources-have-changed) is not not? If there is something in particular missing there we can add it, would you be willing to create a PR for it?

**Comment by oculos** [comment]
It is, my fail.
