### ISSUE TITLE
Error during migration from 25.0.4 to 26.0.0

### ISSUE THREAD

**Issue by mflorczak** [keycloak/keycloak#33744]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

During update to 26.0.0 from 25.0.4 Kubernetes pod is unhealthy.
This is error from application 

	`2024-10-09 12:35:23,561 ERROR [org.infinispan.CLUSTER] (jgroups-8,keycloak-676dcb6b4b-zx9dq-58734) ISPN000474: Error processing request 6219@keycloak-6789765fcf-kw8wd-22255: java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper$ExternalizerImpl	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:114)	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:72)	at java.base/java.lang.Class.forName0(Native Method)	at java.base/java.lang.Class.forName(Class.java:534)	at java.base/java.lang.Class.forName(Class.java:513)	at org.infinispan.marshall.exts.ClassExternalizer.readObject(ClassExternalizer.java:37)	at org.infinispan.marshall.exts.ClassExternalizer.readObject(ClassExternalizer.java:12)`

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Migration will succeed 

### Actual behavior

Application crashed

### How to Reproduce?

Run migraton from 25.0.4 to 26.0.0

**Comment by ryanemerson** [comment]
As @shawkins states, rolling upgrades across versions are not yet supported. The issue here is that Keycloak 26 migrated it's internal Infinispan cluster to use Protostream marshalling, which is not compatible with Externalizer based approach used prior to KC 26. The class cannot be found as it no longer exists.

**Comment by mflorczak** [comment]
I created headless keycloak with own pod but got following error 
`Caused by: java.io.IOException: Unsupported protocol version 152	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)	at org.infinispan.marshall.exts.ThrowableExternalizer.newThrowableInstance(ThrowableExternalizer.java:286)	at org.infinispan.marshall.exts.ThrowableExternalizer.readGenericThrowable(ThrowableExternalizer.java:264)	at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:239)	at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:44)	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)`

**Comment by mflorczak** [comment]
I did this headless service with separate keycloak but it doesn't work, here is error log
`2024-10-11 17:15:54,278 DEBUG [java.lang.Runtime] (SIGTERM handler) Runtime.exit() called with status: 143: java.lang.Throwable: Runtime.exit(143)	at java.base/java.lang.Shutdown.logRuntimeExit(Shutdown.java:179)	at java.base/java.lang.Shutdown.exit(Shutdown.java:160)	at java.base/java.lang.Terminator$1.handle(Terminator.java:51)	at java.base/jdk.internal.misc.Signal$1.run(Signal.java:218)	at java.base/java.lang.Thread.run(Thread.java:1583)2024-10-11 17:16:14,528 ERROR [org.infinispan.CLUSTER] (jgroups-11,headless-keycloak-5c7c666984-j24mk-54933) ISPN000474: Error processing request 1283@keycloak-6789765fcf-6g6pf-46542: java.lang.ClassNotFoundException: org.keycloak.cluster.infinispan.LockEntry$ExternalizerImpl	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:114)	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:72)	at java.base/java.lang.Class.forName0(Native Method)	at java.base/java.lang.Class.forName(Class.java:534)	at java.base/java.lang.Class.forName(Class.java:513)`

**Comment by mflorczak** [comment]
I did this headless service but I got this error 
`Caused by: java.io.IOException: Unsupported protocol version 152	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)	at org.infinispan.marshall.exts.ThrowableExternalizer.newThrowableInstance(ThrowableExternalizer.java:286)	at org.infinispan.marshall.exts.ThrowableExternalizer.readGenericThrowable(ThrowableExternalizer.java:264)	at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:239)	at org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:44)	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)	at org.infinispan.remoting.responses.ExceptionResponse$Externalizer.readObject(ExceptionResponse.java:49)	at org.infinispan.remoting.responses.ExceptionResponse$Externalizer.readObject(ExceptionResponse.java:41)	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1548)`

**Comment by AbhishekKandoi314e** [comment]
We are also facing the same issue which is described by @mflorczak when upgrading to 26.0.0. We are running a single node of keycloak server through operator. Were you able to resolve this issue @mflorczak? Any help regarding this would be appreciated. I would provide the error message but for now we have reverted back to 25.0.6 with the old database backup

Current Version:- 25.0.6
Upgrading to:- 26.0.0

**Comment by mflorczak** [comment]
I solved it by stopped all pods, so production was not available for some time :(, any other tries didn't work

**Comment by ahus1** [comment]
@AbhishekKandoi314e - thank you for sharing the logs. I assume "keycloak-1-error.log" is the first pod that started. 

First no members are discovered:

```
2024-10-22 06:54:14,693 INFO  [org.jgroups.protocols.pbcast.GMS] (ForkJoinPool.commonPool-worker-1) keycloak-0-39494: no members discovered after 2001 ms: creating cluster as coordinator
```

Then suddenly a group of 4 other nodes join the cluster. 

```
2024-10-22 06:55:27,218 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-0-39494) ISPN000093: Received new, MERGED cluster view for channel ISPN: MergeView::[keycloak-0-4836|79] (3) [keycloak-0-4836, keycloak-0-21004, keycloak-0-39494], 2 subgroups: [keycloak-0-4836|78] (2) [keycloak-0-4836, keycloak-0-21004], [keycloak-0-39494|0] (1) [keycloak-0-39494]
2024-10-22 06:55:27,219 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-0-39494) ISPN100000: Node keycloak-0-4836 joined the cluster
2024-10-22 06:55:27,220 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-0-39494) ISPN100000: Node keycloak-0-21004 joined the cluster
2024-10-22 06:55:27,220 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-0-39494) ISPN100000: Node keycloak-0-4836 joined the cluster
2024-10-22 06:55:27,220 INFO  [org.infinispan.CLUSTER] (jgroups-6,keycloak-0-39494) ISPN100000: Node keycloak-0-21004 joined the cluster
```

Did you deploy this using the Keycloak Operator, or did you you a custom deployment? 

As there are multiple "keycloak-0-..." nodes, it seems to me that there are multiple deployments that interact with each other in a strange way. How many Keycloak deployment are you running in your cluster? 

Please share your full Keycloak configuration and the Keycloak custom resource.

**Comment by AbhishekKandoi314e** [comment]
@ahus1 I am deploying through Keycloak Operator provided in the documents with a nodeSelector only. I am only using a single keycloak instance in my cluster. 

I apologise for the confusion with the naming of the files but "keycloak-26-error.log" this is the first pod that started when I upgraded from `25.0.6` to `26.0.0`. Then I tried updating to `26.0.1` from `26.0.0` that is when "keycloak-1-error.log" is generated.

Here is the keycloak CR that I am using:-
`
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  additionalOptions:
    - name: http-host
      value: 0.0.0.0
    - name: http-relative-path
      value: /auth
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
  db:
    database: keycloak
    host: <dbhost>
    passwordSecret:
      key: password
      name: keycloak-db-secret
    poolInitialSize: 1
    poolMaxSize: 3
    poolMinSize: 2
    port: 5432
    schema: public
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  features:
    enabled:
      - authorization,docker,impersonation,scripts,token-exchange,preview,admin-fine-grained-authz,dynamic-scopes
  hostname:
    backchannelDynamic: false
    strict: false
  http:
    httpEnabled: true
  ingress:
    enabled: false
  instances: 1
  proxy:
    headers: xforwarded
  unsupported:
    podTemplate:
      spec:
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: deployment
                      operator: In
                      values:
                        - themes-pvc
                topologyKey: kubernetes.io/hostname
        containers:
          - volumeMounts:
              - mountPath: /opt/keycloak/providers/
                name: keycloak-themes
        nodeSelector:
          app: 314e
        volumes:
          - name: keycloak-themes
            persistentVolumeClaim:
              claimName: keycloak-themes-path-pvc
`

I am also using the `keycloak-themes` deployment to load themes from our minio besides keycloak server. I am also using a virtualservice for accessing keycloak. This is the vs:-

`
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  gateways:
    - istio-system/istiogateway
  hosts:
    - auth.domain.tech
    - auth.domain2.tech
    - auth.domain3.app
    - auth-int.domain4.app
  http:
    - match:
      - uri:
          exact: /
      name: keycloak-redirect
      redirect:
        uri: /auth
    - match:
        - uri:
            prefix: /
      name: keycloak-discovery
      route:
        - destination:
            host: keycloak-service.keycloak.svc.cluster.local
            port:
              number: 8080
          weight: 100
metadata:
  name: keycloak-vs
  namespace: keycloak
`

I have also tried removing the `/auth` redirect after the upgrade.

Thanks, Let me know if any other details are required

**Comment by AbhishekKandoi314e** [comment]
@ryanemerson Yes, I do have an another CR in a different namespace which I created for debugging this issue with the same configuration as provided above which I created recently.

But I had faced this issue during upgrade before as well, at that time I didn't had any other CR in my cluster

**Comment by ryanemerson** [comment]
> Yes, I do have an another CR in a different namespace which I created for debugging this issue with the same configuration as provided above which I created recently.

As @ahus1 points out, the logs indicate that (at least) two Keycloak clusters are joining each other with multiple nodes being added as part of the MergeView.

> But I had faced this issue during upgrade before as well, at that time I didn't had any other CR in my cluster

Do you have the logs for this upgrade attempt?

**Comment by AbhishekKandoi314e** [comment]
@ryanemerson Unfortunately I do not have the logs for the previous upgrade attempt but I encountered the same errors that are provided in the both error log files. I can point out a few errors that were present at that attempt as well:-
`java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper$ExternalizerImpl `
`java.lang.ClassNotFoundException: org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity$ExternalizerImpl`
`java.io.IOException: Unsupported protocol version 152`

**Comment by ahus1** [comment]
@AbhishekKandoi314e - can you please explain how you upgrade your installation with the Operator step-by-step, so we can reproduce your upgrade procedure?

Maybe the Operator spins up two different Keycloak instances.

**Comment by AbhishekKandoi314e** [comment]
@ahus1 I have a single replica of keycloak server and keycloak operator running on version 25.0.6. Here are the steps I take to upgrade

- I upgrade the CRDs to the required version on which I want to upgrade which is `26.0.0`
- After that I apply the latest operator deployment from the [https://www.keycloak.org/operator/installation](https://www.keycloak.org/operator/installation) with a nodeselector specific for my environment
- Then operator detects the change in version and spins up a new keycloak server(if needed I also apply the keycloak CR after upgrading the operator to new version)
- The server starts up but after some time it starts throwing the errors that I mentioned before

**Comment by pruivo** [comment]
@AbhishekKandoi314e did you shut down your cluster before performing the upgrade? 
@ahus1 Shouldn't the operator perform a cluster shutdown when upgrading different major versions? It looks like it is doing a rolling upgrade somehow.

**Comment by ahus1** [comment]
@pruivo - yes, the Operator should do it. Still it might be a special case because it is only a single instance started here. Can someone try to reproduce it with the information we have?

**Comment by ahus1** [comment]
I verified that the upgrade works when using the KC Operator when upgrading from `25.0.6` to `26.0.0` when running a single instance as in the example above. The one instance is stopped first before the new one is started. 

Please verify that no other Keycloak services are running and are discovered by the service `keycloak-discovery` which Keycloak uses to discover other pods, and also that no other Keycloak instances running in the cluster might discover your Keycloak instance. On Kubernetes, you would also want to configure Network policies to enforce that only the correct pods are allowed to each other. See also https://www.keycloak.org/server/caching#_securing_cache_communication on how to use TLS certificates to keep traffic within the group of nodes that belong to each other. 

![image](https://github.com/user-attachments/assets/a51d5d02-eae7-49a9-813c-50bd57232053)

![image](https://github.com/user-attachments/assets/0048bb7d-da99-43cc-9526-68870b198845)
