### ISSUE TITLE
Long running user registration when ldap user federation is configured

### ISSUE THREAD

**Issue by czqrny** [keycloak/keycloak#33763]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have a Keycloak server with ~2200 registered users in realm. The realm is configured to use external LDAP (openldap version 2.4.57) as user federation (write mode). Database is postgresql in version 16.4.

My problem appears when new users register using registration form on login page, the registering process takes a long time ~2min.

Last three days I spend on investigating configuration of my environment, debugging, updating and tweaking configuration options, but nothing helps so this issue is my last hope :)

As I understand, when user clicks register button, following happens under the hood:

1. LDAP is queried for all users one by one by ldap identifier (that is fast)
2. LDAP is queried for all users in batches (that is also fast)
3. Keycloak database  is queried for all users one by one (that takes a long time)

some logs messages  from services:

postgresql debug logs, many logs like for each user:
```
...
2024-10-09 23:30:56.372 UTC [33] DETAIL:  parameters: $1 = 'test', $2 = 'test'
2024-10-09 23:30:56.455 UTC [33] LOG:  execute S_2384/C_2616: select ue1_0.ID,ue1_0.CREATED_TIMESTAMP,ue1_0.EMAIL,ue1_0.EMAIL_CONSTRAINT,ue1_0.EMAIL_VERIFIED,ue1_0.ENABLED,ue1_0.FEDERATION_LINK,ue1_0.FIRST_NAME,ue1_0.LAST_NAME,ue1_0.NOT_BEFORE,ue1_0.REALM_ID,ue1_0.SERVICE_ACCOUNT_CLIENT_LINK,ue1_0.USERNAME from USER_ENTITY ue1_0 where ue1_0.USERNAME=$1 and ue1_0.REALM_ID=$2
```

ldap many logs for each user and one batch for all:
```
...
6707121b conn=5888 op=2214 SRCH base="dc=dev,dc=ldap,dc=test,dc=pl" scope=1 deref=3 filter="(entryUUID=77615d24-ddfc-103e-87e4-efa4281d91cb)"
6707121b conn=5888 op=2214 SRCH attr=entryUUID mail cn objectclass
6707121b conn=5888 op=2214 SEARCH RESULT tag=101 err=0 nentries=1 text=
6707121b conn=5888 op=2215 SRCH base="dc=dev,dc=ldap,dc=test,dc=pl" scope=1 deref=3 filter="(entryUUID=e463808e-bc35-103e-87df-efa4281d91cb)"
6707121b conn=5888 op=2215 SRCH attr=entryUUID mail cn objectclass
6707121b conn=5888 op=2215 SEARCH RESULT tag=101 err=0 nentries=1 text=
6707121b conn=5888 op=2216 SRCH base="dc=dev,dc=ldap,dc=test,dc=pl" scope=1 deref=3 filter="(&(objectClass=inetOrgPerson)(objectClass=organizationalPerson))"
6707121b conn=5888 op=2216 SRCH attr=entryUUID mail cn objectclass
6707121b conn=5888 op=2216 SEARCH RESULT tag=101 err=0 nentries=2172 text=
```

keycloak debug logs, many logs for each user:
```
...
2024-10-09 23:30:56,454 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-3) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.credentials#2dc0cc94-9031-46b0-9200-8e6c7b512e68]
2024-10-09 23:30:56,454 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-3) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.federatedIdentities#2dc0cc94-9031-46b0-9200-8e6c7b512e68]
2024-10-09 23:30:56,454 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-3) Skipping uninitialized bytecode-lazy collection: [org.keycloak.models.jpa.entities.UserEntity.requiredActions#2dc0cc94-9031-46b0-9200-8e6c7b512e68]
2024-10-09 23:30:56,454 DEBUG [org.hibernate.engine.internal.Collections] (executor-thread-3) Collection found: [org.keycloak.models.jpa.entities.UserEntity.attributes#3b4d8104-d804-4e42-9762-6dbb1d80cf7b], was: [org.keycloak.models.jpa.entities.UserEntity.attributes#3b4d8104-d804-4e42-9762-6dbb1d80cf7b] (initialized)
...
```

I do not understand why registering new user needs quering for other users (twice for ldap and at least once on database)

Why it just not creates a user? Does not constraints on ldap and database  prevent from duplicates users?

What is more strange trigerring full synchronization on LDAP provider is much faster (~5-7 seconds) , why the same mechnism is not happening on this action?

When I disabled ldap provider in Keycloak, the registration works fast (~1-2 seconds).

Does anyone had the same issue?

### Version

26.0.0, 25.0.5, 24.0.2, 24.0.8

### Regression

- [ ] The issue is a regression

### Expected behavior

Registration should be fast, server should only checks ldap and database if user can be created but not quering all users one by one.

### Actual behavior

Users are quering many times in ldap and database, registration takes a long time.

### How to Reproduce?

1. Start Keycloak service, can be in docker one
1. Start ldap
1. Configure new realm and ldap user federation in it
1. Create many identical users > 2000, REST API endpoint `POST /auth/admin/realms/<realm>/users` can be used
1. Try to register user by registration form (on web browser login page).

### Anything else?

I check a lot of possible configurations on my environments like:

1. Rising virtual machine size - it is not a resource limits problem
2. Rising JVM heap size
3. Allowing more postgresql connections (KC_DB_POOL_* variables) and on postgresql also (400 connections)
4. LDAP connection pooling  to 0 
5. switching on/off XA transactions (variable KC_TRANSACTION_XA_ENABLED)
6. Cache settings on ldap federation (eviction daily and many others)

but nothing helped, it seems that problem is that keycloak quering database for each user one by so it will only get slower as new users register

**Comment by czqrny** [comment]
I'm really ashamed but it turned out that this behavior is caused by my custom plugin which I added to registration flow.

Now I understand why such plugins are discouraged in the logs during server startup

**Comment by fernandonogueira** [comment]
> I'm really ashamed but it turned out that this behavior is caused by my custom plugin which I added to registration flow.
> 
> Now I understand why such plugins are discouraged in the logs during server startup

Hey, @czqrny ! 👋🏼 

Which plugin were you using?
