### ISSUE TITLE
Typescript Cannot find module keycloak-js or its corresponding type declarations.

### ISSUE THREAD

**Issue by ramseyfeng** [keycloak/keycloak#33778]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

TS2307: Cannot find module keycloak-js or its corresponding type declarations.
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/ece70755-8842-4627-b2c6-474a5860545a">

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak could be easily imported smoothly.

### Actual behavior

TS2307: Cannot find module keycloak-js or its corresponding type declarations.

### How to Reproduce?

Create a typescript project and try to import the Keycloak.

### Anything else?

If adding types in the package.json of keycloak-js, the error will not be displayed.
<img width="570" alt="image" src="https://github.com/user-attachments/assets/8ceb96a1-52b2-44b1-9e3e-fb7bfb07c744">

**Comment by Mario-Eis** [comment]
IMHO the solution is in the screenshot, actually. "moduleResolution": "bundler" in tsconfig.json did the trick for me.

**Comment by ramseyfeng** [comment]
@jonkoops, thank you for the information. Could you please confirm if we need to use TypeScript version 5.x or higher?
It seems typescript 4.x does not support bundler.

**Comment by jonkoops** [comment]
Yes, this was part of the [TypeScript 5.0 release](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#--moduleresolution-bundler).

**Comment by joe-noumena** [comment]
Can `"types": "./lib/keycloak.d.ts"` also be added to the **package.json**  to allow still using  `"moduleResolution": "Node",`


Using **bundler** and upgrading to typescript 5 can have significant impact on active projects lots of libs have issues with bundler.

Cheers,
Joe

**Comment by jonkoops** [comment]
We're not planning on adding the `types` field back to the root of the package, the recommendation is still to upgrade your TypeScript version and to change `moduleResolution` to `Bundler` or `Node16` (or higher). I am going to lock the discussion on this issue as this is considered resolved.
