### ISSUE TITLE
[UI]: Possibility to disable automatic dark mode (automatic color-scheme detection)

### ISSUE THREAD

**Issue by Mario-Eis** [keycloak/keycloak#33794]
### Description

The title says it all. This request is for a possibility to deactivate the automatic detection of the color-scheme.

### Motivation

A lot of customers have a very strict CI and are not allowed to support a dark mode. Unfortunately there is no way to deactivate the detection script and the colors are way off  for a lot of users.

**Comment by jonkoops** [comment]
The ability to disable dark mode for themes was already implemented under #32495 and will be part of 26.1.0.
