### ISSUE TITLE
FOUC in Firefox on login UI

### ISSUE THREAD

**Issue by Mario-Eis** [keycloak/keycloak#33793]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

There is a flash of unstyled content on the login page. Even the password suggestion Popup placement is off. Because the autofocus sets the focus to the unstyled username input. And the position is not updated when the actual css kicks in.
Firefox also gives a warning: Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.

I could not find out why exactly that happens. But, beside other things, it seems to be related to the module type of the scripts. <script type="module"... That somehow seems to affect the loading order of things.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

There should be no flashes when loading the login page.

### Actual behavior

FOUC in Firefox on login UI

### How to Reproduce?

Just load the login page in Firefox.

**Comment by ssilvert** [comment]
I have verified this.  You can easily see it if you use the inspector and throttle down the connection.

**Comment by jonkoops** [comment]
Any script with `type="module"` will be executed after the page has become ready unless it comes with a `blocking` attribute.
