### ISSUE TITLE
In SAML clients, client roles are not namespaced, and there is no mapper to filter them

### ISSUE THREAD

**Issue by martinmeneval** [keycloak/keycloak#33824]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

When a user that has client roles from any client connects to a SAML client, their assertion contains a list of all realm roles and all client roles with no differentiation.
This means that a user that has a client role "admin" in the client "example", will have that role show up in their SAML assertion, but with no mention it comes from "example".
This is also not configurable: unlike OIDC client where there are mappers to choose whether all client roles from all clients are included or only specific ones, in SAML clients it's all or nothing.

The reason I raised this as a bug and not an improvement / feature request is that it can lead to accidentally granting access to sensitive clients, with no explicit way to know.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

There is a mapper, or some configuration that allows limiting which roles are included in a SAML assertion.
If my user has no client roles from that client, no roles appear in the assertion when connecting to it.

### Actual behavior

When my user "test" has the client role "admin" from the client "example", and they connect to the SAML client "sp1", their assertion contains the role from the client "example":
```xml
<saml:Attribute Name="Role"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                >
    <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:type="xs:string"
                          >admin</saml:AttributeValue> <- no client_id visible
</saml:Attribute>
```

As a comparison, using OIDC, I can choose whether to map all client roles to the user's token, and even if they are mapped, I can tell the role comes from a different client:
```json
"resource_access": {
    "example": { <- client_id visible
      "roles": [
        "admin"
      ]
    }
  }
```

### How to Reproduce?

Spin up the following minimal `docker-compose.yml`, where we use two Keycloak: one as SAML IDP, one as SAML SP:
```yaml
services:
  keycloak-idp:
    image: quay.io/keycloak/keycloak:nightly
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
  keycloak-sp:
    image: quay.io/keycloak/keycloak:nightly
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
```
Use these config files to properly configure both instances.
[realm-export-idp.json](https://github.com/user-attachments/files/17342942/realm-export-idp.json)
[realm-export-sp.json](https://github.com/user-attachments/files/17342943/realm-export-sp.json)

Otherwise, in the IDP: 
- Create an empty OIDC client with id `example`. Create a client role `admin` inside it
- Create a SAML client with id `http://localhost:8081/realms/master`. Set valid redirect_uris to `*`, Master SAML processing URL to `http://localhost:8081/realms/master/protocol/saml`, and disable "Client signature required".
- Create a user `test` with password `test`. Remove all its roles and grant it the `admin` role from the `example` client.

In the SP:
- Set up a SAML Identity Provider with the SAML Identity Descriptor `http://localhost:8080/realms/master/protocol/saml/descriptor`
- Uncheck "Validate signatures"
- Log out, then log back in with the Identity Provider and the `test` account. 
- Observe, in a tool that can read SAML assertions (for example: the SAML Tracer extension) that the assertion contains the role `admin`, with no mention that it's for a different client.

### Anything else?

Thanks for reading! I can add clarifications / screenshots on request.

**Comment by rmartinc** [comment]
Hi @martinmeneval!

Yes, this has been this way since the beginning and for that reason there is another mapper type for saml `Role Name Mapper` to change names. That mapper can be used to change any role name for another one. For example if you select the a client role you can rename it to `client.role-name` for example. You have to do with one role that has the same name than another one.

Note that you can also restrict the role list mapper to a scope instead of using full scope (for example just restricting the scope to the same client). This way the role list will be restricted to the scope assigned to the mapper and roles from another client will not be added.

Apart from that nothing more can be done.

**Comment by rmartinc** [comment]
Thanks @martinmeneval! Yes, there is room for improvement for sure, but probably we need to add a new mapper or add something in the current one to allow adding a template for role names. As I commented the behavior was like this since the beginning. I'm closing the issue then.
