### ISSUE TITLE
Can't update unmanaged attribute on extension

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#33878]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have configured unmanaged attributes so that I could programmatically save data on an attribute. I have read-only LDAP connection, so it was important to me to have these unmanaged attributes.

However, when attempting to save data to this attribute via code in java on an extension, I get the following error: 

```
org.keycloak.models.ModelException: Not possible to write 'attribute(lastLoginTime)' when updating user 'francis'
```

So while the attribute can be written manually on the gui, it doesn't seem to be writable from code. This is my code:

```
user.setSingleAttribute(LastLoginFactory.attributeName, Integer.toString(Time.currentTime()));
```

Since the definition of unmanaged attributes is that they are treated as first class attributes ("By setting `Enabled`, unmanaged attributes are fully recognized by the server and accessible through all contexts, useful if you are starting migrating an existing realm to the declarative user profile and you don't have yet all user attributes defined in the user profile configuration. By setting `Only administrators can write`, unmanaged attributes can be managed only through the administration console and API, useful if you have already defined any custom attribute that can be managed by users but you are unsure about adding other attributes that should only be managed by administrators.), I'd expect to be able to write to them via code.

Or do I get it wrong?

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Being able to write to unmanaged attributes via code.

### Actual behavior

As the storage is read-only (or writable but without the attribute mapper), so the attribute isn't writeable via code.

### How to Reproduce?

Write a simple extension to write to that attribute via code.
It fails.

**Comment by pedroigor** [comment]
Hi @oculos, does it work if you enable import on the LDAP provider?

**Comment by oculos** [comment]
Yes, that works. I guess I didn't think this was necessary when ldap was set to "writable"

**Comment by pedroigor** [comment]
Thanks. We had a similar issue before and it does not make sense to allow setting attributes if `import` is disabled.
