### ISSUE TITLE
Auth not possible for auth session where user was enabled in the meantime

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#33883]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Whenever you authenticate using OTP/recovery code authenticator and user was enabled in the meantime or brute force lock lifted then the authentication is rejected. The auth session has the "SESSION_INVALID" note which is not cleared anywhere. 
This was detected in `testPostBrokerLoginFlowWithOTP_bruteForceEnabled` test. I'll provide a PR. Feel free to close if you think it is not possible/hard to achieve in the real world. 

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

auth passes if auth session is valid and user is enabled

### Actual behavior

auth fails if auth session is valid and user is enabled after brute force lock was lifted/ user was enabled again.

### How to Reproduce?

Run test testPostBrokerLoginFlowWithOTP_bruteForceEnabled, ` loginTotpPage.login(totp.generateTOTP(totpSecret));` at the end of the test is not successful.

**Comment by jonkoops** [comment]
@martin-kanis can you assign this issue a priority as well?
