### ISSUE TITLE
Unable to differentiate between group of same name coming from 2 different ldap servers

### ISSUE THREAD

**Issue by demonappolyon** [keycloak/keycloak#33908]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I have 2 different ldap servers  having group with same name and want to assign different roles to these groups but keycloak store only single group at it end on syncing groups to keycloak after adding in filters.
Do we have a mechanism under which we can assign different role to these groups and identify which group belongs to which ldap server.

### Version

keycloak 23.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Ideally we must be able to identify which group belongs to which ldap server and separate role could be assigned to these.

### Actual behavior

As of now keycloak maintain single group 

### How to Reproduce?

Add 2 different ldap server create a group in these ldap server with same i.e. group1 in ldap group mapping add the serach path and provide group name in filter and sync the group for both the ldap server.
Under groups tag you will see single group instead of 2 different groups.

**Comment by demonappolyon** [comment]
Tested on keycloak 24 version as well

**Comment by jonkoops** [comment]
The latest release is 26.0.0 at time of writing. Unfortunately, only the latest stable version of Keycloak is supported. Please test against the latest version and we will triage your request.

**Comment by pedroigor** [comment]
This is a valid issue, I think. @sguilhen Isn't it related to some of the issues we already have for the LDAP group mapper? Perhaps a duplicate?

**Comment by sguilhen** [comment]
Not exactly the same, but tightly related to https://github.com/keycloak/keycloak/issues/19652

**Comment by sguilhen** [comment]
One important note: If you have two servers and each one has different groups, ideally their group mappers should NOT share the same group path - i.e. they should not import groups in the same group hierarchy as that mixes up contents from both servers and it is expected that Keycloak will not duplicate a group in the same path.

**Comment by sguilhen** [comment]
I'm closing this one as having groups with same name from different LDAP providers in the same path is not supported. You can have groups with the same name in different paths (much like a directory structure), so if you have two providers with the same group name you must differentiate between them using different group paths in each group mapper.
