### ISSUE TITLE
Not persisted config settings prevent server start

### ISSUE THREAD

**Issue by mduchrow** [keycloak/keycloak#33902]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Starting a newly built Keycloak 26.0.0 with ``kc start --optimized`` shows the following error and starting fails.

> ERROR: The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.spi-user-cache-default-enabled

When running ``kc build`` with have the following config setting in *keycloak.conf*:
``spi-user-cache-default-enabled=false``

Obviously the config parameter ``spi-user-cache-default-enabled`` is not added to the */generated-bytecode.jar/META-INF/keycloak-persisted.properties*, but at startup the ``org.keycloak.quarkus.runtime.cli.Picocli.checkSpiOptions(IncludeOptions, List<String>, List<String>)`` method checks current settings (including those from *keycloak.conf*) against the entries of this file. The ``currentValueStr=false`` does not match ``currentValue=null`` from the persisted properties, hence the error.

In Keyckoak 25.0.6 this problem did not exist! There was no ``checkSpiOptions()`` in the **Picocli** class.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

All properties set at build-time must be recognized correctly at startup-time.

### Actual behavior

Starting Keycloak with --optimized fails when ``spi-user-cache-default-enabled=false`` has been set at build-time.

### How to Reproduce?

1. Put ``spi-user-cache-default-enabled=false`` into /conf/keycloak.conf
2. Run kc build
3. Run kc start --optimized

### Anything else?

This is not just related to property ``spi-user-cache-default-enabled``. This error will also occur with properties matching one of these patterns:
- kc.spi*-provider
- kc.spi*-provider-default
- kc.spi*-enabled

**Comment by shawkins** [comment]
Marking as priority important. The aspect that seems like a regression is that we're emitting an exception, whereas previously there would have been a warning. However we were not persisting the spi related build-time options, so any later checks of the spi configuration were not accurate. I'll look at separating a fix from #33760 because that one has gotten too large.

**Comment by devvick** [comment]
I just tried to build a new Docker image from quay.io/keycloak/keycloak:latest
and ran into this error on start:
```
ERROR: The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.features
```
Dockerfile (feeding only prebuilt keystore to it in COPY command):
```dockerfile
FROM quay.io/keycloak/keycloak:latest AS builder
ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_DB=postgres
WORKDIR /opt/keycloak
COPY root/opt/keycloak/conf/server.keystore /opt/keycloak/conf/
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/
ENV KC_DB_URL=jdbc:postgresql://************/keycloak \
    KC_DB_USERNAME=keycloak \
    KC_DB_PASSWORD=*************** \
    KC_HOSTNAME_STRICT=false \
    KC_PROXY=edge
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
Run command:
```bash
docker run --rm --name keycloak \
    -e "KEYCLOAK_ADMIN=**************" \
    -e "KEYCLOAK_ADMIN_PASSWORD=****************" \
    -e "KC_FEATURES=token-exchange,authorization,web-authn" \
    -e "KC_PROXY=edge" \
    -e "KC_HOSTNAME_STRICT=false" \
    -e "KEYCLOAK_EXTRA_ARGS_PREPENDED=--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true" \
     keycloak start --optimized
```
Can confirm no such error on 25.0.6 version using the same build and run commands.

**Comment by shawkins** [comment]
@devvick that is not related to this issue, and is the correct error message - features are a build time option, and cannot be modified when running a start --optimized command.

**Comment by vmuzikar** [comment]
This is actually a pretty bad regression, increasing the priority of this.

~priority/regression

**Comment by shawkins** [comment]
> This is actually a pretty bad regression, increasing the priority of this.

What works:

build ... with build time spi options specified
start --optimized ... -- without build time spi options specified 

So there is a workaround, but this means user specifying build-time spi options in the keycloak.conf or environment variables will get an error.

This issue highlights that auto-builds never really worked correctly with build-time spi options - we simply always rebuilt.

**Comment by vmuzikar** [comment]
> So there is a workaround, but this means user specifying build-time spi options in the keycloak.conf or environment variables will get an error.

Yes, hence it is a r[egression priority](https://github.com/keycloak/keycloak/blob/main/docs/bug-triage-prioritize.svg) (I consider it documented). :)

**Comment by danelec-hpm** [comment]
I am trying to update to 26.3.2 (from 23.0.4) and I get this error. I found out that I had
`ENV KC_FEATURES=token-exchange`
In the Dockerfile but I need to add it as:
`--features="token-exchange"`
To the kc.sh build command in the Dockerfile and remove the ENV.
