### ISSUE TITLE
Users can not map multiple organizations to client scope 

### ISSUE THREAD

**Issue by 4FunAndProfit** [keycloak/keycloak#33938]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

If user belongs to one organization, map organization to client scope: OK in session user or jwt

if user belongs to multiple organizations: no organizations in return ???

Will it not be better to have something like : 
- current organization : { org_id , alias }
- organizations { list of {org_id, alias} }        ?

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Scope should include organizations scope if multiple organizations

### Actual behavior

see above

### How to Reproduce?

see above

**Comment by pedroigor** [comment]
@4FunAndProfit Can you please check https://www.keycloak.org/docs/latest/server_admin/#mapping-organization-claims_server_administration_guide?

You need to pass `scope=organization:*`. See that doc for more details about the different formats supported by the `organization` scope. We changed that from 25 to 26.

**Comment by 4FunAndProfit** [comment]
@pedroigor Thanks a lot for your answer,  i have read the doc now and effectively that help, but

In the doc for organization it is written : 
```
"Maps to a single organization if the user is a member of a single organization. Otherwise, if a member of multiple organizations, 
**the user will be prompted to select an organization when authenticating to the realm.**"
```
 
That is the workflow I want in my case, but when my member authenticates, no prompt to select an organization is shown

is that normal?

**Comment by 4FunAndProfit** [comment]
Sorry did not pass the scope effectively 

Work well

Sorry for the inconvenience

**Comment by Lord-KalEl** [comment]
This is a different issue:
In my case, it's NOT about the authentification, it's after the authentification. It is about the access token. (is this really the same? No …)

Please open https://github.com/keycloak/keycloak/issues/34535 again.

Greetings,
Kal

**Comment by buff** [comment]
I agree... this is not an authentication issue. Please can somebody clarify.
Is a user able to belong to more than one organization. If so, what should the expectation be of the token that gets created. My assumption is that I will receive an array of organizations that the user belongs to.
I am however receiving none at all. 
If I remove a user from one of the organizations then I see the remaining one.
Please open [](https://github.com/keycloak/keycloak/issues/34535) again.
