### ISSUE TITLE
Background SQL statements show without a connected trace

### ISSUE THREAD

**Issue by Akzz123** [keycloak/keycloak#33932]
### Description

We've configured Keycloak to work with OpenTelemetry (OTEL) following the official documentation (https://www.keycloak.org/server/tracing). While we're able to see traces in Jaeger, we're experiencing an issue with span grouping.

### Details

Problem:
Instead of generating a single trace with multiple spans, Jaeger is creating separate traces for each span. This prevents us from leveraging the benefits of distributed tracing

**Comment by ahus1** [comment]
This is more of a bug report than a request for enhancement, so I updated it to be a bug. 

At the same time from the description it is missing important details what spans you see. Screenshots and/or JSON files of traces would be helpful, together with more details on whether the services that call Keycloak already send tracing headers.

~missing-info

**Comment by Akzz123** [comment]
Enabling Tracing in Keycloak

We've configured the following environment variables in our Keycloak StatefulSet to enable tracing:

- KC_TRACING_ENABLED: true
- KC_TRACING_COMPRESSION: gzip
- KC_TRACING_ENDPOINT: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
- KC_TRACING_JDBC_ENABLED: true

Observation

Traces are available (see attached screenshot), but only one span per trace is displayed. However, when changing Keycloak settings or configurations, multiple spans under a single trace are visible.

![Screenshot 2024-10-19 125209](https://github.com/user-attachments/assets/096ff0b9-96eb-40bf-843b-c40e67f4ba32)


Use Case and Requirement

Our use case involves calling Keycloak for authentication purposes from different applications. We want to include Keycloak-related spans in the main application trace group.

Issue

The Keycloak documentation lacks information on how to explicitly configure the header key that passes the trace ID. Specifically, we need to know:

- What header key should be used to pass the trace ID to Keycloak?
- How to configure Keycloak to propagate the trace ID to its spans?

Request

Please provide guidance on configuring Keycloak to propagate trace IDs and include related spans in the main application trace group.

**Comment by ahus1** [comment]
Thank you for adding these details. What you see here as one-span per trace are background threads that are not connected to an incoming HTTP request. 

* The removal of revoked tokens is a batch job that runs every some minutes to delete revoked tokens that are now expired. We might add a proper span to this so it is clear it is triggered from a background task.
* The deletion of CLIENT_INITIAL_ACCESS is similar
* The handling of OFFLINE_CLIENT_SESSION and OFFLINE_USER_SESSION is again a background task which bundles session updates from multiple requests . The current implementation doesn't connect it to the frontend traces. A future version of Keycloak might do this. 

Keycloak currently uses the standard OpenTelementry setup of Quarkus. [This states](https://quarkus.io/guides/opentelemetry-tracing#propagators): 

> By default, the OpenTelemetry extension enables the [W3C Trace Context](https://www.w3.org/TR/trace-context/) and the [W3C Baggage](https://www.w3.org/TR/baggage/) propagators

There is already issue https://github.com/keycloak/keycloak/issues/33624 asking for other propagators, which me might add in a future release. See you also my comment there that it might already be possible to configure this manually. 

I'm marking this issue as a possible enhancement for a future release.

**Comment by ahus1** [comment]
This #35430 being completed for KC 26.1, most of the background SQLs should now be wrapped. Still for batches we might need one more PR.
