### ISSUE TITLE
keycloak.v2 registration: Password policy validation error "errorList is null"

### ISSUE THREAD

**Issue by SebastEnn** [keycloak/keycloak#33987]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

When any password policy has been set in the Admin Console, the validation of it in the new register.ftl of the keycloak.v2 theme is bugged.
The first time the password has been entered (not compliant with the password policy), the appropriate error messages get added unterneath the input field.
If the password now get's edited and is still not compliant, the same error messages stay under the input field and the browser console logs the following error: "errorList is null".

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The error messages should be updated. The now fixed rules should no longer be shown.

### Actual behavior

The error messages didn't update, they are still the same from the first attempt.

### How to Reproduce?

- Use any realm with registration enabled
- Go to Authentication -> Policies -> Password policy and enable some policies, like minimum length, uppercase chars, lowercase chars, etc. and click on Save
- Go to the registration page of the realm
- Type something in the password field, a single letter for example, and click somewhere else to remove the focus of the field
  - Notice the error message under the password field
- Edit the entered password, for example with an compliant password

The error messages are still visible and haven't
When now opening the console of the browser, an error should be shown ("errorList is null")

**Comment by ssilvert** [comment]
I'm not seeing the error in the console, but I do see the bug where the error message never goes away.  

It does not stop the user from registering,
