### ISSUE TITLE
Handle removal of online session for the directGrant and clientCredentials

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#34000]
See https://github.com/keycloak/keycloak/issues/32650 for the details.

**Comment by jonkoops** [comment]
@rmartinc @mposolda should this be backported as well?

**Comment by rmartinc** [comment]
I think that no, this is not a direct bug, more an improvement. The online session is not created because it's not needed. We can backport it if someone thinks that it is interesting.
