### ISSUE TITLE
Session Identifier Not Updated in keycloak 

### ISSUE THREAD

**Issue by Amr9190** [keycloak/keycloak#34014]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Dear Team,
Kindly be informed that we are facing a vulnerability for session identifier not updated as below,
so please advise knowing that we upgraded our keycloak to latest version (**Keycloak - Version 25.0.6**).

Issue Description:
Session Identifier Not Updated (Vulnerability issue)
Entity: authenticate (Page)
Risk: It may be possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate
user, allowing the hacker to view or alter user records, and to perform transactions as that user
Fix Recommendation:
Prevent user ability to manipulate session ID. Do not accept session IDs provided by the user's browser at login; always generate a new session
to which the user will log in if successfully authenticated.
Invalidate any existing session identifiers prior to authorizing a new user session.
For platforms such as ASP that do not generate new values for sessionid cookies, utilize a secondary cookie. In this approach, set a secondary
cookie on the user's browser to a random value and set a session variable to the same value. If the session variable and the cookie value ever
don't match, invalidate the session, and force the user to log on again.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

to change the session id and all cookies values after login

### Actual behavior

the cookies values are same before and after login

### How to Reproduce?

open keycloak and capture the sessions cookies, then login and capture the new sessions cookies and it should be changed

**Comment by Amr9190** [comment]
Hello Team,
Keycloak has been upgraded to the latest Version 26.0.0,
but still session identifier not update vulnerability exists.
so please check and advise

**Comment by graziang** [comment]
Hi @Amr9190, I’m unable to reproduce the issue. Could you please provide more detailed steps to reproduce it on the latest version of Keycloak?

**Comment by Amr9190** [comment]
Hello Team,
The issue that we get a vulnerability issue that the auth session ID not updated ( not changed) before and after login to keycloak,
so please check the attached screen shots.

how to reproduce the issue: 
1 - Open dev too
2- access the keycloak URL
3 - capture the cookies before the login
4- login to keycloak
5- capture the cookies after the login
you can notify that all cookies for the auth session id and kc restart are same, before and after the login and this caused a vulnerability issue.

so please check and advise hot to fix it and make sure that all cookies values will be changed after we loged in to keycloak

thanks in advance
[Keycloak issue.zip](https://github.com/user-attachments/files/17618793/Keycloak.issue.zip)

**Comment by graziang** [comment]
Hi @Amr9190, the AUTH_SESSION_ID cookie is not removed after login to allow any other open tabs on the login page to complete the authentication. However, even if the auth session cookie is still valid after login, it is not possible to log in with the same auth session using a different user, as this is blocked by the server.

**Comment by Amr9190** [comment]
Hello,
There is any way to make the AUTH_session_ID value to be change after login?
thanks

**Comment by graziang** [comment]
The AUTH_SESSION_ID changes if you log out

> Hello, There is any way to make the AUTH_session_ID value to be change after login? thanks
