### ISSUE TITLE
[Admin UI] Broken autocomplete input on the "Create resource-based permission" form

### ISSUE THREAD

**Issue by rh-** [keycloak/keycloak#34017]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

# Background

The clients with the enabled fine-grained authorization have the **Authority** tab, where the **resources** and the accompanying **policies** and **permissions** can be defined.

The admin can create a resource-based permission for the given resource in the table simply by clicking the "Create permission" next to the resource of interest.

![image](https://github.com/user-attachments/assets/2c99fa4a-2182-499d-b483-56657a8fb641)

After clicking on the **Create permission** button, the user is redirected to the **Create resource-based permission** form with the pre-filled data, based on the selected resource.

e.g.

![image](https://github.com/user-attachments/assets/b2dfccb3-0d46-47c8-8d7b-2fdfcc6ee873)

# Problem

When trying to create a resource-based permission for a resource that doesn't fall into the first 10 resources, the form is rendered unusable.

e.g. When I select the **eleventh** resource from the list with intention to **Create permission**, the autocomplete input within the **Create resource-based permission** form doesn't render a resource selection.

![image](https://github.com/user-attachments/assets/787f04fe-5d92-4f44-8fde-6b44c1adc285)

![image](https://github.com/user-attachments/assets/60ce462d-fd4c-4137-b377-36b9bfca9261)

The same happens for the rest of the resources, besides the first 10 (based on the default sorting).

# Why this happens

When the **Create resource-based permission** page is loaded, a request for the available **resources** to populate the autocomplete input is executed:

```
<KC_HOSTNAME_ADMIN>/admin/realms/<realm>/clients/<client-id>/authz/resource-server/resource?first=0&max=10&permission=false
```

Note the `max=10` param. The response contains only the first 10 resources (according to some internal default sort order). The **11th** resource is not returned in the response, thus, the autocomplete input can't populate the input.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The **Resource** autocomplete input field is correctly pre-filled with the selected resource.

### Actual behavior

The **Resource** autocomplete input is empty.

### How to Reproduce?

1. Start up Keycloak
2. Navigate to **Clients**, select **Import client**
3. Upload the demo client with the **Authorization** enabled and 10+ resources available, e.g. : https://gist.github.com/rh-/e0ddf9d94f48efc2812c5c7612036264
4. Navigate to the newly imported client **demo-resource-permission-selection** -> **Authorization** -> **Resources**
5. Click **Create permission** next to the **/resource-10**

### Anything else?

Other autocomplete input forms might be affected as well.

**Comment by ssilvert** [comment]
I have recreated this problem.

**Comment by edewit** [comment]
It's not un-usable it does still work, it only doesn't show the name of the resource as selected the value is still there.
