### ISSUE TITLE
Update KEYCLOAK_SESSION cookie to not have sessionId in plain-text

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#34026]
### Description

Could we improve the `KEYCLOAK_SESSION` cookie to not contain sessionId in plain-text? This can be considered as possible hardening. Could be nice especially due the fact that `KEYCLOAK_SESSION` cookie is not httpOnly.

Can we possibly hash the sessionId (or maybe whole cookie value) with something like SHA-256 instead of using plain-text value? It looks that this won't require any changes in keycloak.js adapter itself, so it can be backwards compatible for people using older versions of keycloak.js. The keycloak.js can still send the sessionId in the message, which would be consumed by `login-status-iframe.html`. But the iframe itself can then hash the value of the received sessionId and compare it with the hashed value from the cookie.

There are few more places in Keycloak, which may require some changes as they compare the cookie session with the existing session (`LogoutEndpoint,`, `AuthenticationManager.redirectAfterSuccessfulFlow`) , but looks all of them can be updated to compare with the hash instead.

There is also one consideration that `KEYCLOAK_SESSION` cookie now contains the format like `realmId/userId/sessionId` . The "realm" and "user" parts should not be needed for anything, so can be just omitted, so we have the new format of the cookie something like `sha256(sessionId)` (This was already discussed in the past and we might have other open issue for this).

NOTE: This change could be a concern for backwards compatibility for the cluster-like deployments, which would use the new servers (with this change) combined with the old servers (without this change). That is due the format of the cookie would be incompatible. So if we want to support zero-downtime upgrade for cluster deployments, then this change probably should not go to the micro-release, but only to the minor releases.

**Comment by jonkoops** [comment]
We could also port the code to parse the cookie to support both the new and old format and backport it first, then older deployments could still handle cluster deployments by going from the last patch to the next minor.

**Comment by ahus1** [comment]
I would also like to understand if this would affect only authentication sessions, or also also already logged in users with their user session. If this change would log-out all currently logged in users, we should try to avoid it.

**Comment by jonkoops** [comment]
We can add a migration for the cookie to `DefaultCookieProvider` so that all old-style cookies are automatically converted to the new format.

**Comment by stianst** [comment]
This is broader than just the value in the cookie. If I remember correctly the session_state itself should be unique per-client and not a global thing. Not really sure how you'd do that to be honest, as it seems you'd need one cookie per-client, and also some way of mapping the session_state from one client to the underlying session.

**Comment by jonkoops** [comment]
We do [know the client i](https://github.com/keycloak/keycloak/blob/049121f41e16ede587ef84d247078e24e16943d5/services/src/main/resources/org/keycloak/protocol/oidc/endpoints/login-status-iframe.html#L23)d inside of the session status iframe, so if the cookie is pre/suffixed we can construct the name of the cookie from there.
