### ISSUE TITLE
Multivalued User Profile with options does not show

### ISSUE THREAD

**Issue by PhilippKolmann** [keycloak/keycloak#34033]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

I have added a user profile with multivalued enabled and want to offer options to the user for choosing.

The options show up fine, when multivalued is disabled. As soon as I enable multivalue again, the input field in add user is a standard textbox but fails if I enter a wrong option.

I have put together a test realm config: [test-realm.json](https://github.com/user-attachments/files/17409785/test-realm.json)
There the 'user_location' field should present the option selector.

### Version

26.0.0 and tested with nightly  sha256:425f5c107f55bb627154d6bb358933cdc813159694530c5a12390fdb42688c5b

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that the multivalued input also has the same drop down / checkbox behavior as single value

### Actual behavior

as soon as multivalue is enabled, the standard textbox is shown

### How to Reproduce?

create a user profile setting with multivalued enabled and options to choose from (see test-realm.json)

### Anything else?

Thanks for the great product!

**Comment by martin-kanis** [comment]
I can confirm the select component does not work with multivalued attributes. This looks like an UI issue.

**Comment by ssilvert** [comment]
This is really an enhancement request as the UI doesn't support multi-valued input for input types other than a regular text field.

I'll put this on our list to consider, but a community PR would be welcome.

**Comment by ssilvert** [comment]
If you choose `Multivalued` in the General Settings then you can't specify a different `inputType` in the annotations.  I don't think we have any logic to allow multivalued input for anything other than the default `inputType`.

**Comment by ssilvert** [comment]
> @ssilvert
> 
> > I'll put this on our list to consider, but a community PR would be welcome.
> 
> I had some spare time and looked into the matter. As far as I have tested this, my patch fixes this issue for me. Please check if this can be included.

I had some extra time myself and looked a little closer.  I understand your problem better now.  I see that this is an ordinary bug that really doesn't have anything to do with the `Multivalued` attribute.  It's just not saving when `inputType` is `multiselect` or `multiselect-checkboxes`.

**Comment by edewit** [comment]
@PhilippKolmann you need to add the length validator and edit how many values is the minimum and how many is the maximum, default is min: 0 max: 1
![image](https://github.com/user-attachments/assets/c9c8a8ae-51f2-4252-9b9e-58a4113fe8ba)

**Comment by ssilvert** [comment]
@PhilippKolmann I tried out your test-realm.json and I got it to work.  Just unselect the `Multivalued` option, and do this:

![image](https://github.com/user-attachments/assets/15e8f574-5cb4-4227-8c4a-31b9f160e2ac)

I spoke with @edewit about this and here is what we think is the proper solution:

1. Make it clear that the `Multivalued` toggle will always present multiple text inputs and should not be used with any `inputType` attribute.
2. If `inputType` is `multiselect` or `multiselect checkboxes` assume that the number of allowed selections is equal to the total selections.  That way, you are not required to set a `length` validator.

WDYT?

**Comment by PhilippKolmann** [comment]
@ssilvert I am not really sure if this so intuitive, that you have to turn OFF multivalued (which would mean to me the attribute is single valued) and override this with the inputType set to multiselect.

If this is the way you think is the right one, it's fine for me as well.

**Comment by PhilippKolmann** [comment]
@edewit why have you closed the issue? Should this work already out of the box?

I have just tested it with the current docker KC:nightly image:

![image](https://github.com/user-attachments/assets/acbc114a-dfff-4286-b3ed-49aa80bacb50)

As soon as I select more then one location, I receive an error, that there must only be one attribute selected!

![image](https://github.com/user-attachments/assets/7029a73f-80a6-4591-a4bf-bf3c16e7b52e)

**Comment by ssilvert** [comment]
> @edewit why have you closed the issue? Should this work already out of the box?
> 

@PhilippKolmann He closed it because he fixed it in another PR.  Please try the nightly build.
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by ssilvert** [comment]
@PhilippKolmann You are using the `length` validator.  To validate the number of values, use the `multivalued` validator instead.

I agree that this is very confusing.  I'm going to close your PR and open an new issue for us to make this more intuitive.

**Comment by edewit** [comment]
@PhilippKolmann you added the length validator instead of the multi valued validator see my screenshot

**Comment by PhilippKolmann** [comment]
Thanks @ssilvert and @edewit  for your help solving my issue. I got it even working on 25.0.6 :-)
