### ISSUE TITLE
KC 26 Organisation Invite Link Expiry Notice

### ISSUE THREAD

**Issue by danielslyman** [keycloak/keycloak#34046]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

The invitation E-Mail sent via the new Organizations feature seems to display the minutes value in milliseconds. 

### Version

26.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The invitation E-Mail sent via the new Organizations feature SHOULD display the minutes value in minutes. 

### Actual behavior

The invitation E-Mail sent via the new Organizations feature displays the minutes value in milliseconds. 

### How to Reproduce?

Send organization invitation Email and read email.

**Comment by pedroigor** [comment]
Thanks. We are fixing it here https://github.com/keycloak/keycloak/issues/34049.

**Comment by danielslyman** [comment]
Thanks!
