### ISSUE TITLE
LDAP Pagination not working for role membership in GET_ROLES_FROM_USER_MEMBEROF_ATTRIBUTE strategy

### ISSUE THREAD

**Issue by TheOignon** [keycloak/keycloak#34042]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

When loading the role membership from a user, all the roles that the user is memberOf and matching a potential LDAP filter should be loaded. The LDAP protocol having a theorical MaxPageSize, the RFC 2696 added the mechanism of pagination. Pagination seems to exist in some part of the codebase but not everywhere and specifically not here. As such, when we try to load of the group membership of an AD user, with the current strategy we are capped at 1000.

### Version

v26 / main

### Regression

- [ ] The issue is a regression

### Expected behavior

The token or userinfo endpoint should reflect the entire LDAP group membership and should not be limited to MaxPageSize on Active Directory.

### Actual behavior

The token / userinfo endpoint contain a maximum of 1000 entries since MaxPageSize is at 1000.

### How to Reproduce?

Use the federation module with Active Directory, create a mapper that will filter (or not) a user that contains more than 1000 groups membership. Make sure to be in GET_ROLES_FROM_USER_MEMBEROF_ATTRIBUTE strategy. Emulate a query that should reflect the userinfo endpoint and you will notice a maximum of 1000 groups.

### Anything else?

Caching or not does not change the behavior here. Some operations from Keycloak seems to support pagination.

**Comment by sguilhen** [comment]
I see what you mean, @TheOignon ! I'm accepting the issue and if you feel like sending a PR (saw that you've already worked on a commit) we'll be happy to review/accept it!

**Comment by sguilhen** [comment]
Please disregard the bot's comment - I've removed the auto-expire label given that we might have a PR for it soon.

**Comment by Woudan** [comment]
@TheOignon Thanks for the PR. Did a build with the changes and they solve the issues we are also running into!

**Comment by TheOignon** [comment]
@sguilhen the PR is available here atm : https://github.com/keycloak/keycloak/pull/34043
Though ATM the fix was to simply inject in place the code from LDAPUtils that implement pagination as the initial method requires an ldapProvider and the bit of code I changed only exposes the ldapConfig. 

3 solutions comes in mind : 
1) Duplication of code is okay
2) the loadAllLDAPObjects is only called at 3 places at the moment so I could just change the initial parameters and change the 3 calls to pass the ldapConfig
3) I make a method overloading that rewrite loadAllLDAPObjects 

Any comment on the right solution to implement ? Sorry for the direct ping, first PR and unsure on how to proceed.

**Comment by sguilhen** [comment]
@TheOignon Thanks for submitting the PR. I think what you did in the PR is fine (overloading the method) as that leads to the least amount of changes.
