### ISSUE TITLE
Onclick focus issue in the Username field of Clients / <client> / Client Scopes / Evaluate

### ISSUE THREAD

**Issue by martinmeneval** [keycloak/keycloak#34054]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When using the Evaluate subtab of Client Scopes, in a client's settings, in the admin UI, and clicking the Users input, the focus goes to the dropdown instead of the search bar. This means it needs a second click to be able to start typing a username.
While this may be desirable for very small deployments, as soon as you have >20 users, it's not great.

See the following video example:

https://github.com/user-attachments/assets/72071ddb-44b5-42e2-b6d3-fefed10c6dca

It used to be fine in 23.0.x, so this may be related to the new-ish PatternFly version.[](url)

### Version

nightly for this test, 25.0.6 in prod, and 23.0.5 in other instances

### Regression

- [X] The issue is a regression

### Expected behavior

When I click onto the Users field, I can start typing a username.

### Actual behavior

The focus goes to the dropdown list of users. If I have more users than fit in one page of results, I need to click a second time in the field to be able to start typing.

### How to Reproduce?

- Spin up a blank Keycloak instance
- Go to the admin UI, Clients, `account`, Client Scopes, Evaluate
- Try typing something like your admin user's username
- See that it doesn't type, and you need to click it again

**Comment by edewit** [comment]
Right the first click opens the dropdown and the second click focuses the input. I don't think that that is wrong
