### ISSUE TITLE
Realm role assignment modal shows incorrect checkbox values when switching pages

### ISSUE THREAD

**Issue by martinmeneval** [keycloak/keycloak#34053]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When you're assigning realm roles from the admin UI, and you select one (for example, the 2nd role in the list), the checkbox gets checked. If you go to the next page, the checkbox next to the 2nd role on that page will also be checked. However, that role will not be assigned, it's just a visual issue.
Client roles are fine.

Here's a video showcasing this, with more context in below paragraphs

https://github.com/user-attachments/assets/a395a889-ca88-4e40-a36d-bb06430b8a12

### Version

nightly from a week or so ago for this test, 25.0.6 in prod.

### Regression

- [X] The issue is a regression

### Expected behavior

Like the first part of the video, with client roles. If I select a role in the list, the checkbox becomes checked. If I go to the next page, no checkboxes are checked unless I specifically selected these roles.

### Actual behavior

In the second part of the video, when I try it with realm roles, we see that I select "admin", the 2nd role from the first page. When I go to page 2, the 2nd role in the list (here, "i"), will also show as checked.

### How to Reproduce?

- Spin up a blank Keycloak instance
- Create a test user, strip him of any roles
- Create enough realm roles to have ~20 total
- Go select a role assign to your test user. For ease of reproduction, ensure you show 10 per page. Do not confirm yet.
- Instead, go to the next page and see a checkbox showing up as checked incorrectly.

### Anything else?

This used to be fine in 23.0.x, I suspect it's something related to the PatternFly update but I didn't look too deeply into it :)

**Comment by ssilvert** [comment]
I have reproduced this.  Also attaching a json you can use with partial import to instantly create 150 roles.

[realm-role-many.json](https://github.com/user-attachments/files/17421229/realm-role-many.json)

**Comment by edewit** [comment]
this is also mentioned in https://github.com/keycloak/keycloak/issues/30976 and fixed by https://github.com/keycloak/keycloak/pull/33337

**Comment by omasseau** [comment]
In which version was this fixed ? I cannot find the info.
