### ISSUE TITLE
The Realm Selection Dropdown Breaks After 50 Realms In Database

### ISSUE THREAD

**Issue by JahlersSoundThinking** [keycloak/keycloak#34072]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

As an master user I logged in and created a new basic realm with no special JSON customization. After creating the realm I navigated away from that realm to find it missing from the dropdown and is not searchable until I clear my cache again. This happens every time I click on the realm and navigate away from it.

### Version

26.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

My newly created realm stays in the dropdown at all times and remains searchable

### Actual behavior

I create a new realm with just the name and no special JSON and it becomes the selected realm, then I navigate away from that realm and when I go to search it, it is gone.

### How to Reproduce?

Log in as a master user and create a new realm with no special JSON. Then after having that realm as the selected realm, navigate to a new realm and then search the dropdown for the realm that was just created, it will be missing.

**Comment by JahlersSoundThinking** [comment]
I will also add that this was run on my local server in dev mode

**Comment by ssilvert** [comment]
@JahlersSoundThinking I'm not seeing this problem.  In fact, the most recently used realms should show at the top of the list when switching realms.

What do you mean by, "with no special JSON"?  I assume you are just creating the realm from the admin console UI?
Do you have a lot of realms?
Is there anything else you can tell me to reproduce your problem?

**Comment by JahlersSoundThinking** [comment]
Yeah so I am just creating the realm from the admin console UI and not filling in the resource file box. We have 58 realms right now. The newly created realms are not showing up as "recent" either. All I've done is click on create realm, set the realm name and hit create, then I navigate to a new realm and the realm I just created is no where to be found. We have some custom code that listens to realm being created but nothing to interfere with the dropdown filtering process. I am wondering if it might be a dev mode only issue since the realms come back after clearing the cache? It works fine in 25.0.6

**Comment by JahlersSoundThinking** [comment]
We start our keycloak server like this 

bin\kc start-dev --log="console,file" --spi-connections-http-client-default-socket-timeout-millis=600000 -Dquarkus.transaction-manager.default-transaction-timeout=7200 --http-port=8081

**Comment by JahlersSoundThinking** [comment]
I can also add that I just tested it with a brand new keycloak 26.0.1 server with none of our custom providers and none of our custom themes, only connected to our database that we used in 25.0.6 and this issue is there. I also removed the themes from the problem realms to make sure it wasn't an issue with the themes not being found in the realm settings for those realms

**Comment by JahlersSoundThinking** [comment]
Started a brand new server from scratch and it looks like the pagination breaks somewhere after 50 realms are made

**Comment by ssilvert** [comment]
> Started a brand new server from scratch and it looks like the pagination breaks somewhere after 50 realms are made

I don't think I tried 50 realms.  That might make a difference.

**Comment by ssilvert** [comment]
@JahlersSoundThinking I created 60 realms and everything worked fine.   I created a new realm and then opened an old realm.  The new realm still shows up at the top of the list.

**Comment by ssilvert** [comment]
BTW, here is a json that creates 100 realms.  But I had to do it 20 at a time because it kept throwing errors.

To import: `kc.[sh|bat] import --file realms-100.json`

[realms-100.json](https://github.com/user-attachments/files/17481266/realms-100.json)

**Comment by JahlersSoundThinking** [comment]
@ssilvert which database were you using? I'm using a postgres version 12

**Comment by senyahnoj** [comment]
This looks similar to https://github.com/keycloak/keycloak/issues/33616 

We are also experiencing problems with the realms drop-down with lots of realms. I've been trying to get steps to reproduce but the problem is intermittent: sometimes the search box and next/previous buttons work and other times they don't work.

**Comment by ssilvert** [comment]
@senyahnoj @JahlersSoundThinking I'm just using the default H2 database.  But I can't imagine why it would be any different with Postgres.

We need a reliable way to reproduce this.

**Comment by JahlersSoundThinking** [comment]
Yeah I'm not sure what is going on, I just tested a clean 26.0.2 download using the h2 database and it broke after 11 realms, I created each realm by hand, I just gave them the name test1, test2....

I am running the server locally on windows 10 pro on version 22H2, with this start.bat file

set JAVA_HOME=C:\workspaces\tools\jdk-17.0.2
bin\kc.bat start-dev --http-port=8081

**Comment by ssilvert** [comment]
@JahlersSoundThinking I see it now.  I created exactly 11 new realms on a clean install.  I have to do these precise steps to see the bug:

After creating 11, realms:
1. Create another realm
2. Immediately switch to another realm
3. Do something in that realm, like click on `Users` section.
4. Realm from step 1 is gone

**Comment by idc77** [comment]
Same here, 
I don't know how many, but many realms.
I can't even search the realm name.
There are 3 pages of realm names, and then it ends.

I also don't like that new pagination in the realm list.
Even 1000 realms won't make a big impact on memory footprint and lag.
It's worse for usability as it was before.

This is still present in 26.0.5

**Comment by iliuta** [comment]
I already created an issue like that and I've been told I was dreaming.

I confirm this is not solved in 26.0.8.

I don't have 50 realms but somewhere between 10 and 20. The realm search does not work for all realms. For some it works, which seems odd. When I clear the cookies, it works for a while until it no longer works.

Not to mention that once I switch to another realm, It is impossible to list again all realms, due some "Forbidden" xhr error (already mentioned several times in several issues).

**Comment by iliuta** [comment]
However, it seems there is improvement: the API call performed by the UI correctly retrieves the results when searching for realms but none are displayed in the interface.

**Comment by iliuta** [comment]
Issue still present in the latest 26.1.0.

**Comment by Serpan07** [comment]
Hi ,

It is still planned to solve this issue?
Here is a procedure (not need 20 realms, 4 is enough) : 

- Create some realms that start with "my-realm-xxx" at least 4
- Search with "my-realm"
- Click on one of the realm
- Search again with "my-realm"
- Click on another realm
- Search again with "my-realm" -> all the realm are not displayed
- Check in your localStorage (the key 'recentRealms'), you will see a list with "master" and 3 realms selected previously.

**Comment by laurentva** [comment]
> Issue still present in the latest 26.1.0.

Hello, we're also encountering this in 26.0.7 with ~20 realms, and came here checking the release notes of 26.1.0. But now it seems that it's not fixed?
