### ISSUE TITLE
 "MIME type ('') is not a supported stylesheet MIME type" error after upgrading to Keycloak 26 in AWS ECS Fargate with multiple containers

### ISSUE THREAD

**Issue by shkmass11** [keycloak/keycloak#34078]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

**Environment:**
- **Keycloak Version:** 26
- **Deployment:** AWS ECS Fargate with 2 containers
- **Proxy Mode:** `KC_PROXY_HEADERS=xforwarded` and KC_HTTP_ENABLED=true
- **Cache Stack:** `KC_CACHE_STACK=ec2`
- **Issue Type:** Admin UI load failures and failed requests with multiple containers

**Description:**

After upgrading from Keycloak 23 to Keycloak 26 in my AWS ECS Fargate environment, I am encountering issues when running multiple containers. The Keycloak setup works fine when only a single container is running. However, when scaling to two containers, the following error appears when accessing the Admin UI:

```
MIME type ('') is not a supported stylesheet mime type. This happens for both css and js types. Once I get 404 for the requests and the next type it is 200. 
```
The failed requests doesnt have the Content-Type response headers

- Along with the Admin UI load issue, other requests also fail such as login to realm.
- Downgrading back to Keycloak 23 resolves the issue, and everything works fine even with two containers.
- The problem seems to be isolated to running multiple containers with Keycloak 26.

**Steps to Reproduce:**
1. Deploy Keycloak 26 on AWS ECS Fargate with the `KC_PROXY_HEADERS=xforwarded` and` KC_HTTP_ENABLED=true` setting.
2. Scale the ECS service to run 2 containers.
3. Access the Admin UI or send other requests to Keycloak.
4. Observe that with 2 containers, the Admin UI fails to load, and requests fail.

**Actual Behavior:**
- With 2 containers running, the Admin UI fails to load with the error:
  ```
  MIME type ('') is not a supported stylesheet mime type
  ```

- The issue does not occur when running a single container, only when scaling to two containers.
  

Please advise if there is any configuration change or additional debugging steps that could help resolve this issue.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Keycloak Admin UI and all other requests should work consistently without MIME type issues or failures when running multiple containers.

### Actual behavior

- With 2 containers running, the Admin UI fails to load with the error:
  ```
  Refused to apply style from /auth/resources/yw1z0/admin/keycloak.v2/assets/main-cvkxqs02.css because its mime type ('') is not a supported stylesheet mime type, and strict mime checking is enabled keycloak
  ```

- The issue does not occur when running a single container, only when scaling to two containers.

### How to Reproduce?

1. Deploy Keycloak 26 on AWS ECS Fargate with the `KC_PROXY_HEADERS=xforwarded` and` KC_HTTP_ENABLED=true` setting.
2. Scale the ECS service to run 2 containers.
3. Access the Admin UI or send other requests to Keycloak.
4. Observe that with 2 containers, the Admin UI fails to load, and requests fail.

### Anything else?

- No other changes were made to the configuration or environment apart from the Keycloak version upgrade along with the KC_PROXY_HEADERS and KC_HTTP_ENABLED
- This issue does not occur in Keycloak 23.
- Other env variables
 KC_CACHE=ispn, KC_HOSTNAME_STRICT=false,KC_HOSTNAME=https://myapp.com/auth,KC_HOSTNAME_ADMIN=https://myapp.com/auth,KC_HTTPS_PORT=443

**Comment by codespearhead** [comment]
1. The `KC_HTTP_ENABLED=true` setting is enabled by default in development mode, but disabled by default in production. This is because you should only enable it if your reverse proxy handles edge termination [1]. Even in that case, enabling it increases your attack surface because your Keycloak server will be accessible via HTTP within the internal network, exposing it to potential internal threats [2]. Since Keycloak is one of, if not the most, critical security components in your infrastructure, it's wise to use HTTPS even if the reverse proxy handles TLS edge termination, just to be safe.
2. You should get rid of `KC_HTTPS_PORT=443` and use the `KC_HTTP_PORT=8080`, unless you're following the best practice of only reaching Keycloak via HTTPS even if your reverse proxy handles TLS edge termination.
3. It doesn't make sense to set `KC_HOSTNAME_ADMIN` if its value is the same as `KC_HOSTNAME`. [3]
4.Either set `KC_HOSTNAME` or `KC_HOSTNAME_STRICT=false`. It doesn't make sense to set both. [4]

Confirm if the issue is still reproducible in the latest stable version of Keycloak, which currently is Keycloak `26.0.1`.

***

[1] https://github.com/keycloak/keycloak/blob/47a7d9c12eac55980b083d7dc2da16643ef3dd32/docs/guides/server/hostname.adoc?plain=1#L41-L43
[2] https://github.com/keycloak/keycloak/blob/47a7d9c12eac55980b083d7dc2da16643ef3dd32/docs/guides/server/enabletls.adoc?plain=1#L12
[3] https://github.com/keycloak/keycloak/blob/47a7d9c12eac55980b083d7dc2da16643ef3dd32/quarkus/config-api/src/main/java/org/keycloak/config/HostnameV2Options.java#L12
[4] https://github.com/keycloak/keycloak/blob/47a7d9c12eac55980b083d7dc2da16643ef3dd32/quarkus/config-api/src/main/java/org/keycloak/config/HostnameV2Options.java#L23

**Comment by shkmass11** [comment]
@codespearhead 

https://www.keycloak.org/docs/26.0.0/upgrading/#deprecated-proxy-option
Got your point for KC_HOSTNAME and  KC_HOSTNAME_STRICT. 
Also I'm following reaching Keycloak via HTTPS so KC_HTTPS_PORT=443 is also fine.
And even with KC_HTTP_ENABLED=true everything works fine with single container but not with 2 containers

**Comment by codespearhead** [comment]
Try changing `KC_PROXY_HEADERS=xforwarded` to `KC_PROXY_HEADERS=forwarded` [1][2].

***

[1] https://www.keycloak.org/server/reverseproxy (Section: Configure the reverse proxy headers)
[2] https://github.com/keycloak/keycloak/blob/12e427cd85c17c62018bc082960582f2e028f6c3/docs/guides/server/reverseproxy.adoc?plain=1#L41

**Comment by codespearhead** [comment]
@shkmass11 Did the above solution work? If not, can you share your solution?

**Comment by shkmass11** [comment]
@codespearhead No, the above solution didn't work.

What worked for me was,
Step 1: Using kc.sh build
Step 2: Using kc.sh start  --optimized

**Comment by isaacjensen** [comment]
I am experiencing this exact issue. I have only KC_HOSTNAME set.

**Comment by shawkins** [comment]
@isaacjensen can you clarify if your situation is the same - have you scaled to 2 or more instances and are using the ec2 cache stack?

I would suspect the issue is with the cache configuration. Specifying ec2 seems to require some additional setup and has been deprecated moving forward https://github.com/keycloak/keycloak/issues/34253

Can you try jdbc-ping instead?

**Comment by isaacjensen** [comment]
> @isaacjensen can you clarify if your situation is the same - have you scaled to 2 or more instances and are using the ec2 cache stack?
> 
> I would suspect the issue is with the cache configuration. Specifying ec2 seems to require some additional setup and has been deprecated moving forward #34253 More than likely the instances are not able to find each other, so cache state is not being shared.
> 
> Can you try jdbc-ping instead?

            - name: KC_CACHE_STACK
              value: "jdbc-ping"

On boot i get: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000540: No such JGroups stack 'jdbc-ping'

KC 26.0.0

**Comment by shawkins** [comment]
> On boot i get: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000540: No such JGroups stack 'jdbc-ping'

Ah, jdbc_ping isn't available until 26.1. 

@ryanemerson @pruivo what would you suggest for the cache stack on KC 26.0 in this situation?

**Comment by isaacjensen** [comment]
> > On boot i get: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000540: No such JGroups stack 'jdbc-ping'
> 
> Ah, jdbc_ping isn't available until 26.1.
> 
> @ryanemerson @pruivo what would you suggest for the cache stack on KC 26.0 in this situation?

Im going to remove my KC_CACHE and KC_CACHE_STACK env vars and just use whatever is default and try this out. To answer your questions above, my KC setup is as follows:
- Keycloak 23.0.7 
- HAproxy LB
- Should be in TLS termination mode, so KC_PROXY=edge. I have the KC_HOSTNAME env var set, KC_PROXY_HEADERS=xforwarded with the kc.sh start command doing   "--http-enabled=true"
  and "--http-port=8080"

**Comment by pruivo** [comment]
@shawkins @isaacjensen are you having clustering issues? The message `MIME type ('') is not a supported stylesheet mime type` does not seem related to JGroups or network issues. 
In any case, can you share the Keycloak logs from both containers?

**Comment by isaacjensen** [comment]
> @shawkins @isaacjensen are you having clustering issues? The message `MIME type ('') is not a supported stylesheet mime type` does not seem related to JGroups or network issues. In any case, can you share the Keycloak logs from both containers?

No errors in pods. I am running in EKS and autoscaled to 3 pods, all 1/1 Running. Deployed with helm. I hit admin console, i get redirected to https://my-keycloak.com/auth/admin/master/console/ with:

-Refused to apply style from 'https://my-keycloak.com/auth/resources/lw7fc/admin/keycloak.v2/assets/main-CvkXqs02.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

-Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by shawkins** [comment]
@pruivo suspecting the issue is with the cache config was because things seemed to work with only a single instance. Also isn't there additional setup needed for discovery to work with ec2?

**Comment by isaacjensen** [comment]
> > > On boot i get: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000540: No such JGroups stack 'jdbc-ping'
> > 
> > 
> > Ah, jdbc_ping isn't available until 26.1.
> > @ryanemerson @pruivo what would you suggest for the cache stack on KC 26.0 in this situation?
> 
> Im going to remove my KC_CACHE and KC_CACHE_STACK env vars and just use whatever is default and try this out. To answer your questions above, my KC setup is as follows:
> 
> * Keycloak 23.0.7 trying to upgrade to 26.0.0
> * HAproxy LB
> * Should be in TLS termination mode, so KC_PROXY=edge. I have the KC_HOSTNAME env var set to https://my-keycloak.com/auth, KC_PROXY_HEADERS=xforwarded with the kc.sh start command doing   "--http-enabled=true"
>   and "--http-port=8080"

Did not work. Same errors

**Comment by isaacjensen** [comment]
> ISPN000094

Yes sir. I see it in each of the 3 pods. Each one has the line. This is from uam-keycloakx-0.

2024-11-12 20:36:27,020 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000094: Received new cluster view for channel ISPN: [uam-keycloakx-0-27439|0] (1) [uam-keycloakx-0-27439]

2024-11-12 20:36:27,089 INFO  [org.infinispan.CLUSTER] (ForkJoinPool.commonPool-worker-1) ISPN000079: Channel `ISPN` local address is `uam-keycloakx-0-27439`, physical addresses are `[192.168.185.28:59471]`

2024-11-12 20:36:27,716 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: uam-keycloakx-0-27439, Site name: null

**Comment by pruivo** [comment]
```
ISPN000094: Received new cluster view for channel ISPN: [uam-keycloakx-0-27439|0] (1) [uam-keycloakx-0-27439]
                                                                                       ^^^
```
Does the list only contain a single member? Which stack did you use with keycloak v23?

**Comment by isaacjensen** [comment]
> ```
> ISPN000094: Received new cluster view for channel ISPN: [uam-keycloakx-0-27439|0] (1) [uam-keycloakx-0-27439]
>                                                                                        ^^^
> ```
> 
> Does the list only contain a single member? Which stack did you use with keycloak v23?

Single member yea, i used 'ispn' in KC 23 and worked great. ENV vars looked like this:
            - name: KC_CACHE
              value: "ispn"
            - name: KC_CACHE_STACK
              value: "kubernetes"

**Comment by pruivo** [comment]
Great, `kubernetes` stack is available in v26. This stack requires the property `-Djgroups.dns.query` which should be set in `JAVA_OPTS` or `JAVA_OPTS_APPEND`. KC 26 can be configured in the same way as KC 23.

**Comment by isaacjensen** [comment]
> Great, `kubernetes` stack is available in v26. This stack requires the property `-Djgroups.dns.query` which should be set in `JAVA_OPTS` or `JAVA_OPTS_APPEND`. KC 26 can be configured in the same way as KC 23.

Yeah, so this is what i was using from the get go when i originally saw this error. I will try again.
JAVA_OPTS_APPEND looks like this: 
extraEnvVars: |
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "common.names.fullname" . }}-headless
and is rendered as:
    - name: JAVA_OPTS_APPEND
      value: -Djgroups.dns.query=uam-keycloakx-headless


Does this look correct? On https://www.keycloak.org/server/caching under 'Available transport stacks', i see this:

Stack name | Transport protocol | Discovery
-- | -- | --
kubernetes | TCP | DNS_PING (requires `-Djgroups.dns.query=<headless-service-FQDN>` to be added to JAVA_OPTS or JAVA_OPTS_APPEND environment variable).

**Comment by isaacjensen** [comment]
> > Great, `kubernetes` stack is available in v26. This stack requires the property `-Djgroups.dns.query` which should be set in `JAVA_OPTS` or `JAVA_OPTS_APPEND`. KC 26 can be configured in the same way as KC 23.
> 
> Yeah, so this is what i was using from the get go when i originally saw this error. I will try again. JAVA_OPTS_APPEND looks like this: extraEnvVars: |
> 
> * name: JAVA_OPTS_APPEND
>   value: >-
>   -Djgroups.dns.query={{ include "common.names.fullname" . }}-headless
>   and is rendered as:
>   
>   * name: JAVA_OPTS_APPEND
>     value: -Djgroups.dns.query=uam-keycloakx-headless
> 
> Does this look correct? On https://www.keycloak.org/server/caching under 'Available transport stacks', i see this:
> 
> Stack name	Transport protocol	Discovery
> kubernetes	TCP	DNS_PING (requires `-Djgroups.dns.query=<headless-service-FQDN>` to be added to JAVA_OPTS or JAVA_OPTS_APPEND environment variable).
Ah, this is what was wrong with my setup. `-Djgroups.dns.query={{ include "common.names.fullname" . }}-headless` is INCORRECT. Not sure where i found that substitution, but use the value from configmap-env-vars.yaml: {{ printf "-Djgroups.dns.query=%s-headless.%s.svc.%s" (include "common.names.fullname" .) (include "common.names.namespace" .) .Values.clusterDomain | quote }}. All pods Running and admin console is accessible. Thank you @pruivo @shawkins

**Comment by pruivo** [comment]
@isaacjensen Glad it worked! 
@shawkins thanks for ping me. Do you think this can be closed?

**Comment by shawkins** [comment]
> @shawkins thanks for ping me. Do you think this can be closed?

Is there anything that could make jgroups.dns.query more foolproof? @isaacjensen in this instance did your original jgroups.dns.query actually resolve? If not, where there any logs related to that in the server?

**Comment by pruivo** [comment]
The helm chart can automate this and set the correct DNS query to resolve. Is the helm chart from the Keycloak team or the community? 

In KC v26.1, `jdbc-ping` will do all the hard work.

**Comment by shawkins** [comment]
> Is the helm chart from the Keycloak team or the community?

The broader community. We don't provide a helm chart from the main keycloak repos.

**Comment by shawkins** [comment]
@pruivo sounds like we're good to close. There's nothing more we will do on our side to make users more aware of misconfiguring the kubernetes stack.
