### ISSUE TITLE
java.util.ConcurrentModificationException when process user sessions update

### ISSUE THREAD

**Issue by IUADE0TB** [keycloak/keycloak#34093]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

When restart existing session and process user sessions update with JpaChangesPerformer and persistent sessions feature enabled:

java.util.ConcurrentModificationException
keycloak      |                         at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:988)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.JpaChangesPerformer$6$1.clear(JpaChangesPerformer.java:547)
keycloak      |                         at org.keycloak.models.sessions.infinispan.UserSessionAdapter$6.runUpdate(UserSessionAdapter.java:377)
keycloak      |                         at org.keycloak.models.sessions.infinispan.UserSessionAdapter$6.runUpdate(UserSessionAdapter.java:365)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.JpaChangesPerformer.lambda$processUserSessionUpdate$6(JpaChangesPerformer.java:689)
keycloak      |                         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.JpaChangesPerformer.processUserSessionUpdate(JpaChangesPerformer.java:688)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.JpaChangesPerformer.lambda$registerChange$0(JpaChangesPerformer.java:72)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.PersistentUpdate.perform(PersistentUpdate.java:40)
keycloak      |                         at org.keycloak.models.utils.KeycloakModelUtils.lambda$runJobInTransaction$1(KeycloakModelUtils.java:263)
keycloak      |                         at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransactionWithResult(KeycloakModelUtils.java:392)
keycloak      |                         at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:262)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.lambda$process$2(PersistentSessionsWorker.java:98)
keycloak      |                         at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
keycloak      |                         at org.keycloak.models.sessions.infinispan.changes.PersistentSessionsWorker$BatchWorker.lambda$process$3(PersistentSessionsWorker.java:96)
keycloak      |                         ... 4 more

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

clear() method of UserSessionEntity in JpaChangesPerformer.processUserSessionUpdate method should be excecuted without exception

### Actual behavior

exception is occured

### How to Reproduce?

Restart existing session with userSession.restartSession(..) method and persistent sessions feature enabled

**Comment by martin-kanis** [comment]
@IUADE0TB Thanks for reporting this. Can you please share what operation did you perform when the error occurred? Or it happened in the background? It could help with reproducing.

**Comment by IUADE0TB** [comment]
It happens in the background thread.
We have a custom OIDC authentication flow with cookie authentication disabled and custom authenticator that restart existing session like that:

UserSessionModel userSession = keycloakSession.sessions().getUserSession(realm, authenticationSession.getParentSession().getId());
        UserModel sessionUser = Optional.ofNullable(userSession).map(UserSessionModel::getUser).orElse(null);
        if (userSession != null && sessionUser != null) {
            userSession.restartSession(realm, authenticationSession.getAuthenticatedUser(), 
   authenticationSession.getAuthenticatedUser().getUsername(), context.getConnection().getRemoteAddr(),
                    authenticationSession.getProtocol(), false, null, null);
        }

Steps to reproduce:
1.  Configure custom auth flow with cookie auth disabled;
2. Create custom authenticator that restart session, if session exists;
3. Log in with user1 and new session will be created;
4. Try to login with user1 or other user in different browser tab, but with the same cookie;
5. Login failed with java.util.ConcurrentModificationException in the background thread and with a lot of retries.

The exception occurs in JpaChangesPerformer class, line 547 of UserSessionEntity overrided method clear():
                          @Override
                            public void clear() {
                                userSessionModel.getNotes().forEach((k, v) -> userSessionModel.removeNote(k));
                            }
Looks like userSessionModel.removeNote(k) remove map entry during iterating by userSessionModel.getNotes()

**Comment by martin-kanis** [comment]
@IUADE0TB thanks for additional info. I was able to reproduce it.

**Comment by ahus1** [comment]
Backport created: #34314
