### ISSUE TITLE
 Cannot reorder custom auth flow executions in admin-ui

### ISSUE THREAD

**Issue by mrik974** [keycloak/keycloak#34098]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I work on my authentication flows, the UI frequently freezes when I try to reorder the actions. While it works when I move an action to the bottom, it fails when I try to move them up.

I tried to reproduce the bug with the browser flow, but I couldn't. However, when I duplicate a longer browser login flow, here's what happens :
![CleanShot 2024-10-18 at 15 22 01](https://github.com/user-attachments/assets/7c94b79a-99a4-47a7-8168-efe271761df3)

The error is the same as issue #31040 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'level')
    at Mc.getChange (execution-model.ts:127:60)
    at onDrop (FlowDetails.tsx:429:50)
    at ee (Draggable.js:101:35)
    at HTMLDocument.I (Draggable.js:235:33)
```

### Version

26.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

it should be possible to reorder auth flow executions.

### Actual behavior

Cannot reorder authenticator executions in custom auth flows from bottom to top.

### How to Reproduce?

Run the release 26.0.1
Duplicate a flow with lots of actions and conditions.
Try to reorder auth flow executions from bottom to top. 

### Anything else?

When reordering from top to bottom, it works. 
When trying with a copy of browser workflow, it works as well.

**Comment by ssilvert** [comment]
@mrik974 

What I found was that when you try to drag past the top of the screen, it doesn't auto-scroll.  So you have to drop it near the top, scroll up manually, then drag again.

Is that the issue you are seeing?

**Comment by mrik974** [comment]
@ssilvert I don't think that's the issue. Here's another GIF of what I'm experiencing. It happens even when I don't have to scroll. 
![CleanShot 2024-10-22 at 09 58 33](https://github.com/user-attachments/assets/9a30fa87-a5aa-4444-ab29-60e527bacf41)

**Comment by beezerk23** [comment]
I also face that issues since 25.0.4 (don't know if it happens before). In the web console i got this error:
```
execution-model.ts:127 Uncaught TypeError: Cannot read properties of undefined (reading 'level')
    at Mc.getChange (execution-model.ts:127:60)
    at onDrop (FlowDetails.tsx:429:50)
    at ee (Draggable.js:101:35)
    at HTMLDocument.I (Draggable.js:235:33)
```

Maybe this helps?

**Comment by ssilvert** [comment]
OK, I reproduced it this time.

Steps I used are:
1. Duplicate `first broker login`
2. Grab the last step and try to drag it near the top.
3. The step you picked goes back to the bottom.

**Comment by mrik974** [comment]
I checked it, and it works fine now, thanks !

**Comment by derotune** [comment]
Hey @ssilvert , while its working for new created flows, it does not work for my existing ones. I created a browser flow using terraform but for some reason this flow keeps breaking when realigning even if i recreate it. 

Moving actions up leads to the same error i talked about before:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'level')
    at Mc.getChange (execution-model.ts:127:60)
    at onDrop (FlowDetails.tsx:429:50)
    at ee (Draggable.js:101:35)
    at HTMLDocument.I (Draggable.js:235:33)
```

**Comment by ssilvert** [comment]
Backport to 26.0 not needed.
