### ISSUE TITLE
Username Form should support autocomplete

### ISSUE THREAD

**Issue by xsrf** [keycloak/keycloak#34091]
### Description

The Username Form in the base theme prevents autocomplete, e.g. by some password managers, by setting `autocomplete="off"` at https://github.com/keycloak/keycloak/blob/7bdd10d77d5027270aa282732839db7d25686118/themes/src/main/resources/theme/base/login/login-username.ftl#L20
I can't come up with a reason for this.

### Motivation

I want my browser to suggest my username for the login form and not having to type it manually every time.

### Details

Set `autocomplete="username"` instead.

Can reproduce the issue with Chromes (v129, Windows) built in password manager. It suggests username and password on the "Username Password Form" but not on the "Username Form". If I change the autocomplete to `username` via content overrides in chromes dev-tools in the browser, I also get the suggestion on "Username Form".

**Comment by jonkoops** [comment]
This seems like a good enhancement, I would welcome a PR.

**Comment by ahus1** [comment]
@jonkoops - I see you marked this for backporting to KC26. If this is still the plan, would you pick up this task?

**Comment by jonkoops** [comment]
Done, see #35543
