### ISSUE TITLE
Cannot start Keycloak 26.0.1 in a docker container

### ISSUE THREAD

**Issue by redarccoder** [keycloak/keycloak#34126]
### Description

Hello everyone, I'm trying to setup a container with docker compose using the latest image (At the time of writing) but I have been unable to solve the issue.

The Error displayed on my container console is as follows:
[_services_keycloak_1_logs(7).txt](https://github.com/user-attachments/files/17452588/_services_keycloak_1_logs.7.txt)

I have tried to disable telemetry in the container with:
ENV KC_OTEL=false
ENV KC_METRICS_ENABLED=false

Still the same error as in the attached in the log file

I have verified the container has access to my dbserver container (from an Ubuntu image with nmap and net-utils) and externally I have tested that the DB user has access to the DB.

At this point I'm lost at what I have to do:

## Container config
keycloak:
  image: keycloak_local:latest
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro
  networks:
    - internaldb
    - publicproxy
  environment:
    # DB Setup
    KC_DB: mysql
    KC_DB_URL_HOST: dbserver
    KC_DB_URL_PORT: 3306
    KC_DB_URL_DATABASE: Keycloak
    KC_DB_USERNAME: ****
    KC_DB_PASSWORD: ****
    # User
    KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    KC_BOOTSTRAP_ADMIN_USERNAME: admin

## Docker File
FROM keycloak/keycloak:latest AS builder
ENV KC_DB=mysql
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_OTEL=false
ENV KC_METRICS_ENABLED=false

ENV KC_PROXY_HEADERS=xforwarded
ENV KC_HOSTNAME=keycloak.softwarelaguna.com
ENV KC_HTTP_ENABLED=true

ENV KC_DB=mysql

COPY ./bin/krdp.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--verbose"]

**Comment by shawkins** [comment]
@mabartos do the otel errors look familiar? Was this already addressed by the recent change to fully turn off otel?

**Comment by redarccoder** [comment]
Well... for anyone who cared about this (not that much people I guess) this has been solved with upgrading keycloak to 26.0.2... I changed nothing and the container started without a problem. What was it? dunno.... will I investigate this issue? Never.

Anyone, thank you @shawkins for taking a look at the issue, I owe you a coffee

**Comment by redarccoder** [comment]
Clicked on comment instead on close

**Comment by mabartos** [comment]
@redarccoder Thanks for creating this issue.

I haven't seen any error like this before. 

@redarccoder There is no such handling for `KC_OTEL` env var. Only the `KC_TRACING_ENABLED` env var should turn on/off (off by default) the OpenTelemetry Tracing. 

@redarccoder Could you please verify for us, that you are able to start Keycloak 26.0.2 with the `KC_TRACING_ENABLED=true`? To assure we don't have any hidden bigger problem here.

Thank you!
