### ISSUE TITLE
Standardize error messages from client and server in login theme (keycloak.v2)

### ISSUE THREAD

**Issue by SebastEnn** [keycloak/keycloak#34137]
### Description

While working on #34030 I noticed a difference between client error messages and server (aka. regular) error messages.

`field.ftl`
````freemarker
  <div id="input-error-client-${name}"></div>
  <#if error?has_content>
    <div class="${properties.kcFormHelperTextClass}" aria-live="polite">
      <div class="${properties.kcInputHelperTextClass}">
        <div class="${properties.kcInputHelperTextItemClass} ${properties.kcError}" id="input-error-${name}">
          <span class="${properties.kcInputErrorMessageClass}">
              ${error}
          </span>
        </div>
      </div>
    </div>
  </#if>
````

This results in this structure:
![grafik](https://github.com/user-attachments/assets/83aa99b2-883e-42b9-aa55-d6307d82452f)

I would like to standardize this code to have a unified way of how error messages are added to the form.

### Details

There are different ways to handle this.
(All these ways are based on the idea of having only one div tree for both client and server error messages)

- Add the _error div tree_ right after the _input div tree_
  - Should the first div of this div tree have an id?
  - Should the last div of this div tree have an id?
- Have a static div with an id after the _input div tree_ and add the _error div tree_ inside it
  - This is my favourite approach, since it's easy to check if there's an _error div tree_ inside

**Comment by jonkoops** [comment]
I think we should have as little `id` attributes as possible to avoid possible duplication. So my vote would be the latter approach.

**Comment by SebastEnn** [comment]
> I think we should have as little `id` attributes as possible to avoid possible duplication. So my vote would be the latter approach.

Okay, I'll create a PR for this and look forward to your feedback.
