### ISSUE TITLE
Upgrading from Keycloak 22.0.1 to 26 breaks content-type

### ISSUE THREAD

**Issue by slandelle** [keycloak/keycloak#34143]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Hi,

In Keycloak 22.0.1, APIs respond with a `content-type: application/json` header, which is correct.
After upgrading to 26, APIs now respond with a `content-type: application/json;charset=UTF-8` header, which is incorrect.
This broke our API client.

<img width="760" alt="Capture d’écran 2024-10-21 à 13 34 23" src="https://github.com/user-attachments/assets/fd984f03-9cb3-4261-903c-deb211f725d5">

2 issues here:
* a breaking change that's not documented. It don't know when the change happened somewhere between 22.0.1 to 26.
* setting a `charset` attribute is not correct, see [IANA](https://www.iana.org/assignments/media-types/application/json). The rationale is that JSON can only be UTF-8, UTF-16 ou UTF-32 so parsers can and are expected to infer the charset from the first bytes. I reckon that recipients shouldn't break when this unexpected attribute is present, but things happen, in particular when it wasn't there in the first place.

Regards

### Version

26

### Regression

- [X] The issue is a regression

### Expected behavior

Responses' content-type should be `application/json` as it was in 22.0.1.

### Actual behavior

Responses' content-type is not `application/json;charset=UTF-8`.

### How to Reproduce?

Check any API response in the web console when navigating in the admin console.
Custom APIs implemented in extensions suffer from the same change too.
I guess the change is in the JAX-RS implementation.

### Anything else?

Please let me know if here is the right place or if I should report it against Keycloak's underlying web framework (Vert.x?).

**Comment by slandelle** [comment]
@jonkoops I beg to differ.

The spec says the attribute should not be there and that if present a recipient should ignore it. It's not a valid implementation-specific enhancement nor is UTF-8 a default value.

> this is not a bug, but an enhancement

It's a bug in the sense it's a undocumented breaking change.
It's not an enhancement because it would only be one for recipients that don't abides to the specification. Why favor them at the cost of breaking recipients that abide strictly?

Anyway, that's not a major issue for us and we've quickly made our client ignore it.

> Feel free to submit a PR to rectify this, but I believe this is likely coming from a library and not our own code.

That's also my guess, hence my last question "should report it against Keycloak's underlying web framework (Vert.x?)". Could you please give me a pointer to the library used as JAX-RS implementation in Keycloak?

**Comment by jonkoops** [comment]
> The spec says the attribute should not be there and that if present a recipient should ignore it. It's not a valid implementation-specific enhancement nor is UTF-8 a default value.

If the specification says "no effect on compliant recipients" that means that it allowed and simply should be ignored. Hence the specification implicitly allows this to be present. If you have any evidence this is not the case please quote the exact part of the specification that would make this non-compliant, because I can't find any. 

> It's a bug in the sense it's a undocumented breaking change.

If the specification allows it, it is not a breaking change.

> It's not an enhancement because it would only be one for recipients that don't abides to the specification. Why favor them at the cost of breaking recipients that abide strictly?

I don't understand your point here. If a client does not implement the specification properly that is a bug in the client, not the API.

> Could you please give me a pointer to the library used as JAX-RS implementation in Keycloak?

Good question, I'll ask around but I believe this is likely Vert.x.

**Comment by rmartinc** [comment]
I think this was triggered by the change to resteasy-reactive in keycloak 23. I have tested in 22.0.5 and the charset was not there and in 23.0.0 it appears. So it is added by resteasy-reactive by quarkus. Besides I see that tests on quarkus checks the charset is added for application/json media type ([here](https://github.com/quarkusio/quarkus/blob/3.15.1/independent-projects/resteasy-reactive/server/vertx/src/test/java/org/jboss/resteasy/reactive/server/vertx/test/mediatype/CharsetTest.java#L56) for example).

@slandelle You can ask in quarkus about this issue. It started to happen in 23.0.0 when keycloak was moved to resteasy-reactive from classic. We are just annotating the endpoints with application_json media type exactly as before.
