### ISSUE TITLE
Group select dialog: Subgroups not displayed initially due to pagination

### ISSUE THREAD

**Issue by antikalk** [keycloak/keycloak#34149]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When using the group select dialog, subgroups for groups that appear on page 2 or higher are not display initially:

Page1:
![image](https://github.com/user-attachments/assets/eb9f455c-cb43-4b52-9420-d246cbfc7d5d)

Page2:
![image](https://github.com/user-attachments/assets/073cd4b9-bbfc-4b14-b066-bd2e4a8cbe7a)

On click on group `m`:
![image](https://github.com/user-attachments/assets/c42991db-6ab8-4488-972a-bdf3172caa9b)

Notice the pagination still starting at 11 in the query for the subgroup:
`GET /auth/admin/realms/b/groups/:id/children?first=10&max=10`

You now have to use the pagination to get to the first page and select the Childgroup:
![image](https://github.com/user-attachments/assets/9265120d-c70b-44c1-b2ca-1aabae9b383e)

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Subgroups being displayed immediately starting from position 0

### Actual behavior

You have to paginate back to see the subgroups

### How to Reproduce?

- Create more than 10 groups
- Add a subgroup to a group that is on position 11 or higher
- Go to create user
- Press `Join Group`
- Go to page two
- Open the subgroups of the group you created the subgroup for
- See that the subgroup is not shown unless you navigate to page 1

**Comment by ssilvert** [comment]
Thanks for reporting @antikalk.  I have reproduced this.
