### ISSUE TITLE
Inconsistent data between user list and user form

### ISSUE THREAD

**Issue by gilvansfilho** [keycloak/keycloak#34167]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When `email as username` are enabled user list shows at `username` column:

- `username` of the user created before the option be turned on
- `email` of the user created after the option be turned on

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/9c3ec64a-ab45-4f51-8534-28b90aea2978">

But user form has a different behaviour, it always show the `email` at `username` field.

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/164bf0fd-06ac-4cb6-b3cd-17f08421f210">

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/2589775d-bb03-47dd-ba7f-a09b2d0b22ca">

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Info about user should be consistent in different views

### Actual behavior

Info about user have differences in user list and user form

### How to Reproduce?

1. create a `test` realm
2. create a user (foo / foo@acme.com)
3. change realm settings (turn on `Email as username`)
4. create other user (bar / bar@acme.com)
5. compare infos of users on user list and user form 

### Anything else?

Exported realm to reproduce
[test.json](https://github.com/user-attachments/files/17467892/test.json)

**Comment by gilvansfilho** [comment]
Reproducer users:
- Admin (password: admin)
- foo (password: 123)
- bar@acme.com (password: 123)

**Comment by ssilvert** [comment]
I don't think this is something we want to fix.  It's a subtle difference, but when you change the option for email to be used as the user name, it doesn't actually change the old users internally.  Having it show up this way in the list lets you know what the original user name was (and sort of still is).  Having it always use the email for user name in the form just lets our form behave the same way for all users.

I see your argument, but I'd prefer to leave this one alone.
