### ISSUE TITLE
Sub Realm does not load admin interface anymore

### ISSUE THREAD

**Issue by wzrdtales** [keycloak/keycloak#34191]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When you create a realm in keycloak and assign a user admin privileges on this realm, you normally can go to the account console and from there it will link you to the admin panel. This works if you do everything on the master realm, however, if you act on a sub realm, it will fail to load a list of realms.

Keycloak is making weird requests such as 

```
XHRGET
https://keycloak..de/auth/resources/realms/admin/en
[HTTP/2 404  30ms]

XHRGET
https://keycloak..de/auth/admin/realms/realms
[HTTP/2 404  34ms]

XHRGET
https://keycloak..de/auth/admin/realms/realms/ui-ext/realms/names?
[HTTP/2 404  35ms]

XHRGET
https://keycloak..de/auth/resources/realms/admin/de
[HTTP/2 404  47ms]

```

Normally, it would call `https://keycloak..de/auth/admin/realms/realmname`, but instead does call the URL from above.

### Version

25.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

To work as before, that admin users can be created on a non master realm to manage users inside that realm

### Actual behavior

No admin panel is usable at all

### How to Reproduce?

Install keycloak, create a new realm, create a user in that realm, assign all the roles available or suitable admin roles, login to the user on that realm, go to account console and then from there to admin console

**Comment by wzrdtales** [comment]
Seems that the link in the account panel is simply broken.



Instead of generating the link

```
https://keycloak.de/auth/admin/realmname/console/#/realmname
```

it generates 

```
https://keycloak.de/auth/admin/realmname/console/#/realms
```

**Comment by edewit** [comment]
@wzrdtales sorry, but where is this link in the account console? On which page?

**Comment by wzrdtales** [comment]
Here

![image](https://github.com/user-attachments/assets/f424ccd7-682a-4166-9484-808283b47cd6)

"Return to admin-console"
