### ISSUE TITLE
Service accounts visible under user search in Admin console

### ISSUE THREAD

**Issue by shankaryadavy9** [keycloak/keycloak#34233]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In Keycloak version 26.0.1, the introduction of the `exact` parameter in the `/admin/realms/master/ui-ext/brute-force-user` endpoint has resulted in unintended filtering behavior for service accounts. When the `exact` parameter is not specified, it defaults to false, which inadvertently affects the search results for users, particularly service accounts.

### Version

26.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Service accounts should not be visible under user search in Admin console.

### Actual behavior

Service accounts  visible under user search in Admin console.

### How to Reproduce?

Just create client with service accounts enabled and see the users!.

### Anything else?

Below is the change in admin ui  that caused the issue .

<img width="698" alt="image" src="https://github.com/user-attachments/assets/468bd8ce-209a-4275-ae13-318516fc0384">

I feel instead of  making change in frontend , we can improve backend see the below snip.
`/admin-ui-ext/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java`

<img width="628" alt="image" src="https://github.com/user-attachments/assets/cd67ffd6-300e-476b-9963-5e0c735d8b3d">

Because of `exact` flag in request the `else if`(Line:133) part is getting executed and the we are setting service-account flag by default to true!  

Can we change that to false ?

**Comment by pedroigor** [comment]
@shankaryadavy9 Thanks for the proposed fix.

I thought we were supposed to show SAs when querying for users. @ssilvert This seems related to discussions we had around not mixing user and service accounts.

I'm not sure what is the intended behavior but more likely allow searching for service accounts as it stands today when searching by attribute?

**Comment by MinnDevelopment** [comment]
I'm worried that when showing service accounts in this list, that an admin might incorrectly disable or delete one of them, and recovering from this is quite difficult. This can happen quite easily, too, since the delete prompt doesn't specify which user you are about to delete:

![grafik](https://github.com/user-attachments/assets/2ec26c8b-5b48-497b-a3d7-93ff7e38f8ef)

You only need to miss one user by one row and might accidentally break an entire client. Maybe deleting these users should also be prevented anyway? Since they seem to just be recreated with default roles later (losing whatever you had configured).

**Comment by shankaryadavy9** [comment]
> I'm not sure what is the intended behavior but more likely allow searching for service accounts as it stands today when searching by attribute?

Should  we raise a separate bug to implement this with proper discussion ?

But this issue was raised for introducing a breaking change (in user experience!)

**Comment by pedroigor** [comment]
@shankaryadavy9 Which version you are migrating from?

**Comment by shankaryadavy9** [comment]
@pedroigor  in context to this issue, I simply  ran 25.0.6 on local i see no SA users in console but if I run 26 its visible. 
Regarding my migration , you remember  :)  #31240  this got merged only in 26.0.0   So i am migrating from 23.0.7 to 26.
