### ISSUE TITLE
Token revocation prevents backchannel logout

### ISSUE THREAD

**Issue by age-77** [keycloak/keycloak#34234]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Calling the oidc revocation_endpoint with a refresh token results in the execution of the "revokeClient" method in the TokenRevocation endpoint. Among other things, revokeClient removes the user session.
When the end_session_endpoint is called in the next step, the user session cannot be found in the LogoutEndpoint and "doBrowserLogout" method. This results in "AuthenticationManager.backchannelLogout" not being executed.

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Backchannel logout should be called even if the token was previously revoked.

### Actual behavior

Backchannel logout is not called if the revoke endpoint was previously called with the refresh_token

### How to Reproduce?

1. Configure OIDC identity provider
2. Login user
3. Call revocation_endpoint with refresh_token
4. Call end_session_endpoint

Configured identity provider logout url is not called

**Comment by pedroigor** [comment]
Thanks. I'm not sure what is wrong because the session was revoked after calling the revocation endpoint? It is expected to not run logout at the `end_session_endpoint` if the session is no longer valid.
