### ISSUE TITLE
Docs: Dead link

### ISSUE THREAD

**Issue by dave-meyer** [keycloak/keycloak#34257]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

In the [Keycloak Server Developer Guide](https://www.keycloak.org/docs/26.0.1/server_development/#using-the-pages) there is a link to a Keycloak Quickstart example for React Apps. This link points to a quickstart example that no longer exists: https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-admin-console-node

![grafik](https://github.com/user-attachments/assets/f2a75547-7c1d-4d64-9259-ca45639f5d16)

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

There should be working link to an example React Application in your 'keycloak-quickstarts' repo that can be used to extend either the 'admin' or 'account' pages of Keycloak.

### Actual behavior

The links leads to a GitHub directory that no longer exists.

### How to Reproduce?

Go to https://www.keycloak.org/docs/26.0.1/server_development/#using-the-pages and click on the "https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-admin-console-node" link.

**Comment by dave-meyer** [comment]
I have already made a proposal for a solution in this PR: https://github.com/keycloak/keycloak/pull/34239

**Comment by stianst** [comment]
No need to backport this to 26.0
