### ISSUE TITLE
organizations - identity-first and duplicate emails

### ISSUE THREAD

**Issue by yha-sparklane** [keycloak/keycloak#34266]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

**Context**
* I have multiple users with the same email (the realm is configured to allow duplicate emails)
* One of them has username = email
* Identity-first flow is activated (via Organization)
* The organization is linked to an IDP with automatic redirection based on email domain

**What is expected?**
When authenticating with the email I expect the flow to automatically redirect to the IDP authentication process

**What is happening?**
Keycloak should use username to identify the user but according to the stack below it seems it uses the email : 
```Failed authentication: org.keycloak.models.ModelDuplicateException: Multiple users with email```

### Version

26

### Regression

- [ ] The issue is a regression

### Expected behavior

When authenticating with the email I expect the flow to automatically redirect to the IDP authentication process

### Actual behavior

Keycloak should use username to identify the user but according to the stack below it seems it uses the email : 
```Failed authentication: org.keycloak.models.ModelDuplicateException: Multiple users with email```

### How to Reproduce?

Activate Organization and IDP with automatic redirection on a realm with duplicate emails, one of them has username=email. Then try to log in with the email address (which is the username).

**Comment by pedroigor** [comment]
I think we can change the authenticator to better handle duplicate emails and fallback to searching the user by the username when there are multiple users with the same email.

However, once you authenticate to the IdP you might end-up with a separate account if the username from the IdP does not match any user. How would you deal with this situation in your use case?

**Comment by yha-sparklane** [comment]
Hello,
The context is very simple. Create a realm with duplicate email allowed. Create 2 users : 
One with username = email, for example :
* username: user@domain.fr
* email: user@domain.fr
And an other user with a different username but same email : 
* username: user-test
* email: user@domain.fr

Activate Organization and create one with based on this domain. Identity-first login should be automatically activated.

Then try to connect with the first user : user@domain.fr
Keycloak will rise an error "duplicate email" because it is trying to get the user based on his email.

**Comment by pedroigor** [comment]
> If the username from the IdP doesn't match any user we should simply show the user/password classic login page.

I mean, once the user is authenticated by the IdP and redirected back to your realm (first broker login flow) if no username exists with the same `username` a new account will be created in your realm.

Or in your case the user will be asked to link accounts because the username will match the value from the IdP?

**Comment by yha-sparklane** [comment]
> I mean, once the user is authenticated by the IdP and redirected back to your realm (first broker login flow) if no username exists with the same username a new account will be created in your realm.

We don't allow user creation from IdP because user creation implies many things on our platform. It is orchestrated from outside Keycloak and we automatically link the user to the right organization and the good provider according to the email domain. Currently, if there are no users corresponding to the username typed in the first screen the good old login page is presented. Keycloak look for the user in Keycloak before redirecting to the IdP. At this time, Keycloak fail at identifiyng the user because it try to get it from email.

Maybe duplicate emails and allowing user creation by IdP should not be allowed at the same time but it is not our usecase.

**Comment by pedroigor** [comment]
I see. I'm not sure if I'm following your use case and what you expect.

The reason is that the identity-first login resolves the organization based on the username. However, for that the user must be a member of an organization and a `managed` member.

You mentioned that you manage users outside Keycloak where you automatically link the user to the organization and the "good" provider (the broker?). In this case, it should work if you have the user joining the organization as a managed member.

**Comment by yha-sparklane** [comment]
The user is added to the organization and linked to the IdP. But the problem is here in the code : 
`UserModel user = Optional.ofNullable(users.getUserByEmail(realm, username)).orElseGet(() -> users.getUserByUsername(realm, username));`

https://github.com/keycloak/keycloak/blob/cf2e2b692b8649f4158d943e413be8be30ce322e/services/src/main/java/org/keycloak/organization/authentication/authenticators/browser/OrganizationAuthenticator.java#L237

The organization authenticator try first to resolve user by its email then it try to resolve it by username. But the method `getUserByEmail` rises an exception when emails are duplicated.

**Comment by pedroigor** [comment]
@yha-sparklane I se your point now. Thanks for clarifying, I think we can fallback to the username and failing (e.g.: exception) to resolve via email.

**Comment by yha-sparklane** [comment]
Ok... There is a bug but no plan to fix it ?

**Comment by yha-sparklane** [comment]
Hi, I cannot believe this is not a concern... The identity-first flow ask the user for a **username**, so the normal behaviour should be to search the user by username **before** searching it by email. Why did you flag this issue as action/invalid ?

**Comment by WMartel** [comment]
FYI, I stumbled upon this issue while researching the exact same problem. I don't understand why this was closed, people seemed to be in agreement with the solution, and did not find another similar issue on GitHub, so I opened a new one here: https://github.com/keycloak/keycloak/issues/38852.

**Comment by pedroigor** [comment]
Sorry, something went wrong and closed the issue. I'm working on https://github.com/keycloak/keycloak/issues/38852.

**Comment by pedroigor** [comment]
Can you try it out https://github.com/keycloak/keycloak/pull/38876?

**Comment by WMartel** [comment]
Wonderful news, thanks for the prompt response. I will run some tests later today with that PR.
