### ISSUE TITLE
Flaky Test: BrowserFlowTest.testAlternativeNonInteractiveExecutorInSubflow()

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak#34273]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

Another Chrome click() flaky test. Click() fails silently resulting in test failure.

### Version

HEAD

### Regression

- [ ] The issue is a regression

### Expected behavior

Test should pass

### Actual behavior

Test fails

### How to Reproduce?

Run BrowserFlowTest.testAlternativeNonInteractiveExecutorInSubflow() repeatedly until it fails.

**Comment by ahus1** [comment]
@douglaspalmer - please consider backporting this so that the KC26 release branch stabilizes as well.
