### ISSUE TITLE
PEM files distributed as part of SAML adapter configs are missing -----BEGIN and -----END blocks

### ISSUE THREAD

**Issue by thegushi** [keycloak/keycloak#34276]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

When you use the SAML apapter config downloads to download a client config, you are given a certificate and private key that are "bare", just a base64 blob starting with MII...but most clients that recognize pem files (including mod_auth_mellon) do not recognize these without their "container" lines.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

pem files that are valid according to https://www.rfc-editor.org/rfc/rfc7468

### Actual behavior

Bare pem files such as the following, with no -----BEGIN CERTIFICATE----/-----END CERTIFICATE  and -----BEGIN PRIVATE KEY----/-----END PRIVATE KEY----- blocks.  Tools such as mod_auth_mellon seem to reject these.  Keycloak's own docs for mod_auth_mellon seem to say that these are usable when downloaded from keycloak.

```
MIICuTCCAaECBgGSu5MBETANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBVodHRwczovL2Nsb2FrLmlzYy5vcmcwHhcNMjQxMDIzMjI0ODQ2WhcNMzQxMDIzMjI1MDI2WjAgMR4wHAYDVQQDDBVodHRwczovL2Nsb2FrLmlzYy5vcmcwggEiM....etc....contents not important just missing headers
```

### How to Reproduce?

Follow directions here: https://www.keycloak.org/securing-apps/mod-auth-mellon to download the adapter configs, and try to use them.

### Anything else?

On FreeBSD 14.1 AMD64 with apache24-2.4.62 and with ap24-mod_auth_mellon-0.19.1.

**Comment by thegushi** [comment]
As a note, without these header lines, tools such as `openssl x509` will refuse to read these files:

```
# openssl x509 -in client-cert.pem -noout -text
Could not read certificate from client-cert.pem
Unable to load certificate
#
```

**Comment by thegushi** [comment]
Still happening against 26.0.0, and this is an obvious and easy thing to test.

Do the mod_auth_mellon pem files have the word BEGIN in them?  No?  Issue still exists.

**Comment by thegushi** [comment]
If this does get fixed, it also would be useful if the pem files were also wrapped at 64 characters per the standard.

**Comment by JanDolling** [comment]
We opened a [Pull Request ](https://github.com/keycloak/keycloak/pull/34924) to address this issue.
