### ISSUE TITLE
Importing master realm with users fails with "KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exist"

### ISSUE THREAD

**Issue by maxhov** [keycloak/keycloak#34286]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

#32914 adds the ability to import the master realm. However, it fails later in the process when creating the temporary admin, since the import of the master realm already included the admin.

I think it concerns the following code:

https://github.com/keycloak/keycloak/blob/e6c9f4a1f7e02c5ab4dc22d4e1aee2364ca87321/services/src/main/java/org/keycloak/services/resources/KeycloakApplication.java#L150-L160

Shouldn't the `createTemporaryAdmin(session);` be moved into the condition after line 155?

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak starts when the master realm is imported with a temporary admin.

### Actual behavior

The startup fails with the following errors:

```
INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/bin/../data/import
INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: OVERWRITE_EXISTING
INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'master' imported
INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Imported users from /opt/keycloak/bin/../data/import/master-users-0.json
INFO  [org.hibernate.orm.jdbc.batch] (main) HHH100503: On release of batch it still contained JDBC statements
ERROR [org.hibernate.orm.jdbc.batch] (main) HHH100501: Exception executing batch [java.sql.BatchUpdateException: Batch entry 0 insert into USER_ENTITY (CREATED_TIMESTAMP,EMAIL,EMAIL_CONSTRAINT,EMAIL_VERIFIED,ENABLED,FEDERATION_LINK,FIRST_NAME,LAST_NAME,NOT_BEFORE,REALM_ID,SERVICE_ACCOUNT_CLIENT_LINK,USERNAME,ID) values (('1729761507278'::int8),(NULL),('70b6db17-0088-42c9-bfbf-099f2bc24c76'),('FALSE'::boolean),('FALSE'::boolean),(NULL),(NULL),(NULL),('0'::int4),('c996f14f-effb-43c5-b06e-ecb658304de7'),(NULL),('admin'),('ed934580-2ee0-457f-aee2-cbb912e79f58')) was aborted: ERROR: duplicate key value violates unique constraint "uk_ru8tt6t700s9v50bu18ws5ha6"
  Detail: Key (realm_id, username)=(c996f14f-effb-43c5-b06e-ecb658304de7, admin) already exists.  Call getNextException to see other errors in the batch.], SQL: insert into USER_ENTITY (CREATED_TIMESTAMP,EMAIL,EMAIL_CONSTRAINT,EMAIL_VERIFIED,ENABLED,FEDERATION_LINK,FIRST_NAME,LAST_NAME,NOT_BEFORE,REALM_ID,SERVICE_ACCOUNT_CLIENT_LINK,USERNAME,ID) values (?,?,?,?,?,?,?,?,?,?,?,?,?)
WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 23505
ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) Batch entry 0 insert into USER_ENTITY (CREATED_TIMESTAMP,EMAIL,EMAIL_CONSTRAINT,EMAIL_VERIFIED,ENABLED,FEDERATION_LINK,FIRST_NAME,LAST_NAME,NOT_BEFORE,REALM_ID,SERVICE_ACCOUNT_CLIENT_LINK,USERNAME,ID) values (('1729761507278'::int8),(NULL),('70b6db17-0088-42c9-bfbf-099f2bc24c76'),('FALSE'::boolean),('FALSE'::boolean),(NULL),(NULL),(NULL),('0'::int4),('c996f14f-effb-43c5-b06e-ecb658304de7'),(NULL),('admin'),('ed934580-2ee0-457f-aee2-cbb912e79f58')) was aborted: ERROR: duplicate key value violates unique constraint "uk_ru8tt6t700s9v50bu18ws5ha6"
  Detail: Key (realm_id, username)=(c996f14f-effb-43c5-b06e-ecb658304de7, admin) already exists.  Call getNextException to see other errors in the batch.
ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (main) ERROR: duplicate key value violates unique constraint "uk_ru8tt6t700s9v50bu18ws5ha6"
  Detail: Key (realm_id, username)=(c996f14f-effb-43c5-b06e-ecb658304de7, admin) already exists.
ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
```

### How to Reproduce?

Export the master realm with users and import it.

### Anything else?

I am happy to submit a PR with some pointers to how this should be fixed properly.

**Comment by shawkins** [comment]
> However, it fails later in the process when creating the temporary admin, since the import of the master realm already included the admin.

This is currently the expected behavior. The expectation is that you would use a different username for your bootstrap admin, or exclude that user from the export.

**Comment by maxhov** [comment]
Ok, I can see. However, isn't it strange that a temporary admin is created while an admin has already been imported? It seems to make the newly created temporary admin unnecessary?

**Comment by shawkins** [comment]
> However, isn't it strange that a temporary admin is created while an admin has already been imported?  It seems to make the newly created temporary admin unnecessary?

The bootstrap admin logic, whether running here or via the cli, doesn't know what the existing user is, it just tries to create a new one.

**Comment by maxhov** [comment]
I see now, the bootstrap admin feature is new to me and I wasn't aware it is an optional feature. I believe the behaviour (via KEYCLOAK_ADMIN / KEYCLOAK_ADMIN_PASSWORD) used to be mandatory? I think that is where my confusion comes from. 

I would indeed opt for the current approach, failing if the admin user cannot be created due to an existing user.

**Comment by shawkins** [comment]
> used to be mandatory?

The properties were never required. But effectively they were required for most production installs, otherwise you'd have to go to the admin console to add the intial admin user.

> I would indeed opt for the current approach, failing if the admin user cannot be created due to an existing user. Thank you for the discussion!

No problem, thank you for the doc pr.
