### ISSUE TITLE
Keycloak fails to update username after email change, causing subsequent profile updates to fail.

### ISSUE THREAD

**Issue by ketan-holidu** [keycloak/keycloak#34297]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Keycloak does not update the username when the email is updated, hence all subsequent profile updates fail (409 conflict) due to the username and email being out of sync.

Realm settings
- Unmanaged attributes: Enabled
- Update email: Supported
- Email as username: ON
- Edit username: ON

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The username should be updated to reflect the updated email

### Actual behavior

The email is updated, but the username remains the same, leading to a mismatch. This causes subsequent profile updates or actions to fail.

### How to Reproduce?

1. Enable the following settings in the realm configuration:
- Unmanaged attributes: Enabled
- Update email: Supported
- Email as username: ON (Realm Settings → Login → Email settings)
- Edit username: ON (Realm Settings → Login → User info settings)
2. Create a user
3. Update their email by following this [link](http://localhost:8000/realms/guest/protocol/openid-connect/auth?client_id=kc-web-client&response_type=none&scope=openid&kc_action=UPDATE_EMAIL&redirect_uri=https://localhost:8000): 
4. Confirm the change via the email verification process:
- The email is updated successfully.
- The username remains unchanged, leading to a mismatch between email and username.
5. Make any further profile changes for the user (change language).
- This will fail (409 confict) due to the email and username not being in sync.

**Comment by pedroigor** [comment]
@ketan-holidu I'm not able to reproduce the issue. I also see you are using email verification but the steps you provided do not make any reference to enabling `Verify email` at the realm.

Tried to reproduce using the direct link to the `UPDATE_EMAIL` required action, as you provided. As well as clicking on the `Update Email` link when managing the user profile via the account console.
