### ISSUE TITLE
Brute force detection not working for docker auth

### ISSUE THREAD

**Issue by krombel** [keycloak/keycloak#34302]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

cuncurrent login requests are done when using `docker compose pull` to fetch multiple images im parallel.
As of 25.0.3 with a more strict brute force implementation this does not work anymore. Details below.

### Version

26.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

```
root@server # docker compose pull
[+] Pulling 6/6
 ✔ service-1 Pulled                                                       0.6s 
 ✔ service-2 Pulled                                                       0.7s 
 ✔ service-3 Pulled                                                       0.3s 
 ✔ service-4 Pulled                                                       0.8s 
 ✔ service-5 Pulled                                                       0.4s 
 ✔ service-6 Pulled                                                       0.8s 
```

### Actual behavior

```
root@server # docker compose pull                                                                          
[+] Pulling 6/6                                                                                                                      
 ✘ service-1 Error context canceled                                        0.2s 
 ✘ service-2 Error context canceled                                        0.2s 
 ✘ service-3 Error context canceled                                        0.2s 
 ✘ service-4 Error Head "https://registry.example.com/v2/org/image...      0.2s 
 ✘ service-5 Error context canceled                                        0.2s 
 ✘ service-6 Error context canceled                                        0.2s
Error response from daemon: Head "https://registry.example.com/v2/org/image/manifests/latest": unauthorized: Invalid username or password.
```

### How to Reproduce?

setup Keycloak with docker registry
create a docker compose file (just to make sure multiple images are pulled in parallel from the same registry)
run `docker compose pull` to fetch multiple images concurrently from the same repo (auth managed by keycloak)

keycloak logs state the following:
```
2024-10-24 11:41:29,870 WARN  [org.keycloak.events] (executor-thread-11) type="LOGIN_ERROR", realmId="$UUID", realmName="org", clientId="docker-org-registry", userId="$UUID", ipAddress="$IP", error="user_temporarily_disabled", auth_method="docker-v2", code_id="887b669e-782d-41f4-bb96-2f0a8c19029c", username="docker-user01"
```

### Anything else?

This seems to be related to [the change of brute force settings in 25.0.3](https://www.keycloak.org/docs/latest/upgrading/index.html#concurrent-login-requests-are-blocked-by-default-when-brute-force-is-enabled).
There are 2 temporary workarounds:
- Adding `--spi-brute-force-protector-default-brute-force-detector-allow-concurrent-requests=true` as mentioned in the migration guide 
- `COMPOSE_PARALLEL_LIMIT=1 docker compose pull` to limit the number of concurrent pulls

IMHO adding an exception to rate limiting for the docker provider would be the more appropriate solution.

**Comment by douglaspalmer** [comment]
This isn't a bug. The behaviour was changed on purpose to prevent race attacks. Adding the flag to allow concurrent requests isn't a temporary workaround.
