### ISSUE TITLE
Update the Keycloak CPU and Memory sizing guide to reflect the new ec2 workder nodes

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#34315]
### Description

We have updated the EC2 runner type as part of the https://github.com/keycloak/keycloak-benchmark/issues/1002 and we have to update the below guide location to reflect on the latest info.

https://github.com/keycloak/keycloak/blob/316e00bb98fd33bac0af5fdbaf7caac4481bee82/docs/guides/high-availability/concepts-memory-and-cpu-sizing.adoc?plain=1#L130

### Motivation

We also want to backport this to KC26 docs.

**Comment by ahus1** [comment]
@kami619 - this is now ready for backporting. Thanks!
