### ISSUE TITLE
Support for the Croatian language

### ISSUE THREAD

**Issue by Petar-CV** [keycloak/keycloak#34351]
### Description

After couple of projects in which I had to make parts of the Keycloak theme available in Croatian language, I've decided to open an issue about adding full support for the Croatian language.

I'm looking for native Croatian speakers who can verify translations mentioned in the pull request. Any help is greatly appreciated 🙂

**Comment by ilijaleko** [comment]
I’ve reviewed the translations, and they look accurate and appropriate to me.
