### ISSUE TITLE
26.0.2 `keycloak-admin-client` jar not yet released

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#34368]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

`26.0.2` jar not yet released to maven central, despite `26.0.2` release of keycloak

### Version

26.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

This should be automated along with the release of keycloak

### Actual behavior

No tag or release.

### How to Reproduce?

See https://github.com/keycloak/keycloak-client/tags

### Anything else?

Cross-posting from https://github.com/keycloak/keycloak-client/issues/98 in case this is the right place to file the issue

**Comment by MartaGolabek** [comment]
I am also waiting for this release.

**Comment by foliengriller** [comment]
This is imho intended: See https://www.keycloak.org/2024/10/keycloak-2600-released#_client_libraries_updates

**Comment by xgp** [comment]
So... The code lives in the main

**Comment by jonkoops** [comment]
As mentioned this is working as intended, the adapters are now versioned independently of the Keycloak server. The adapters will adhere to semantic versioning, and will remain backwards compatible with Keycloak versions unless a major version bump of the adapters is done.

**Comment by xgp** [comment]
Thanks for the explanation. Watching to see how this goes.
