### ISSUE TITLE
Error shown misleads users who do not have access to realm.

### ISSUE THREAD

**Issue by rindishkrishna** [keycloak/keycloak#34379]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When a user in master realm which does not have access to master realm but has access to other realms then the error shown is misleading.

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

If a user does not have access to the master realm then either we should redirect it to a realm that it has access or show it a better message so that the user onboarding becomes very easy.

### Actual behavior

When we login using a user which has access to another realm but has not access to master realm then we see the following screen.
<img width="1728" alt="Screenshot 2024-10-28 at 11 50 23 AM" src="https://github.com/user-attachments/assets/6d39905f-1710-43b5-be16-ba0d55ec9cc1">
here the message shown is 
Network response was not OK. Please refresh and continue.

<img width="1728" alt="Screenshot 2024-10-28 at 11 50 53 AM" src="https://github.com/user-attachments/assets/85c603fa-be9c-4fe6-b2f2-311a11361b9e">

As you can see in this screenshot the error returned to whoami call from backed specifically states that user does not have access to the realm.
So, the message shown here is useless as even after refresh the users will see the same message.

### How to Reproduce?

1. Create a new realm called 'test'.
2. Create new user 'user1' in master realm.
3. Create a password for user1.
4. Give it **roles specific to test realm** only. Example - create-client, manage-users etc.
5. Login using this users creds.

@amiteshtoharya4

**Comment by kaustubh-rh** [comment]
Hi @jonkoops , can I raise a PR for the same ?

**Comment by jonkoops** [comment]
I think this might be fixed in 26, is it still reproducible in the latest version of Keycloak?
