### ISSUE TITLE
Remove remaining table USERNAME_LOGIN_FAILURE from the jpa UserSessionProvider times

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak#34380]
### Description

In issue #32582 there was a cleanup of the tables used for the jpa UserSessionProvider that was deleted very long ago (1.5.0). But there is still one table that remains: USERNAME_LOGIN_FAILURE.

This table can also be deleted as it's not used. So it would be good if we add it for removal in the next mayor release.

**Comment by ahus1** [comment]
@rmartinc - thank you for bringing it up. The SRE team did this change when we borrowed the user sessions code from the core IAM team to make it for for cross-site. 

AFAIK the brute force and therefore login failures are owned by the core-clients team. We if you don't plan to put the login failures into the database, you can remove the table eventually. As it is an internal API, you would be able to remove it IMHO in a minor release. 

I could see reasons why to save login failures to the database if you don't want to lose them on Keycloak upgrades, but that's not on our team to decide.

**Comment by rmartinc** [comment]
Thanks @ahus1! Okis, I thought this table removal was for the sre team as the other tables. The login failures are now managed via infinispan and, although using the database would simplify increment concurrency a lot, it has been this way since version 1.5. So I think we can safely remove the table for now. I would just dd it for 26.1 payload.

**Comment by ahus1** [comment]
@rmartinc - thank you for the explanation, +1 for removing the table then.
