### ISSUE TITLE
Incorrect Content-Type Expectation for POST /admin/realms/{realm}/organizations/{id}/members in Keycloak API

### ISSUE THREAD

**Issue by JonasDev17** [keycloak/keycloak#34401]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When sending a request to the POST /admin/realms/{realm}/organizations/{id}/members endpoint, Keycloak expects the content type to be application/json. However, it only accepts a plain text string (e.g., `95f019a8-977f-b7d5-f781-c1b2a3ef288c`) rather than JSON-encoded data (`"95f019a8-977f-b7d5-f781-c1b2a3ef288c"`). This lead to the following issue with an auto-generated rest api client: https://github.com/fschick/Keycloak.RestApiClient/issues/11 where to client would convert the input into a json string with double quotes but the Keycloak api expects a plain string without double quotes.

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Either the api should change the [definition](https://www.keycloak.org/docs-api/latest/rest-api/openapi.json) to match the expected content type from application/json to text/plain or it accepts a JSON-encoded string.

### Actual behavior

Currently the definition is set to application/json.

### How to Reproduce?

I think https://github.com/fschick/Keycloak.RestApiClient/issues/11 shows pretty accurately what the issue is.

**Comment by JonasDev17** [comment]
I am not familiar with the keycloak code base but maybe just doing this might be enough:

![image](https://github.com/user-attachments/assets/89db87fb-e549-4e79-8b07-0706df264ed9)

**Comment by JonasDev17** [comment]
https://github.com/keycloak/keycloak/blob/bf3162ff380cd4c1ecd214c4ff317cb88d89c31a/integration/admin-client/src/main/java/org/keycloak/admin/client/resource/OrganizationMembersResource.java#L38

**Comment by martin-kanis** [comment]
I would just add, there is also `org.keycloak.organization.admin.resource.OrganizationIdentityProvidersResource#addIdentityProvider` that expects a JSON but consumes only `id`.

**Comment by JonasDev17** [comment]
> I would just add, there is also `org.keycloak.organization.admin.resource.OrganizationIdentityProvidersResource#addIdentityProvider` that expects a JSON but consumes only `id`.

Oh, you're right. Added it to my PR

**Comment by JonasDev17** [comment]
Seems like there are more: https://github.com/keycloak/keycloak/issues/34512
