### ISSUE TITLE
Make Hibernate Dialect configurable

### ISSUE THREAD

**Issue by dominiktopp** [keycloak/keycloak#34445]
### Description

When implementing a custom user storage provider with a seperate datasource, we have to set hibernate.dialect in persitence.xml to a hardcoded value. Persistence.xml in Keycloak based on Quarkus is not able to use placeholders to reference e.g. environment variables.

### Discussion

https://github.com/keycloak/keycloak/discussions/21876

### Motivation

Many people have problems with adding a custom datasource to Keycloak (Comments of https://github.com/keycloak/keycloak-quickstarts/issues/299).
We found a hacky workaround for our project (https://github.com/keycloak/keycloak/discussions/21876), but it stopped working after a change to our entities. The unused persistence unit user-a-mssql prevents Keycloak from starting although it is only created and never used.

### Details

I looked at Keycloaks own [default-persistence.xml](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/resources/default-persistence.xml). At first sight all it does should also be possible using [quarkus.hibernate-orm.*](https://quarkus.io/guides/hibernate-orm) props in quarkus.properties.
And in quarkus.properties we can use environment variables, e.g. 
`quarkus.datasource.users-a.password=${QUARKUS_DATASOURCE__USER_A__PASSWORD}`
If we can use quarkus.hibernate-orm.*-properties we will be able to use dynamic Hibernate dialect. But since Keycloak uses a persistence.xml [we cannot](https://www.keycloak.org/docs/latest/upgrading/index.html#quarkus-hibernate-orm-properties-no-longer-working).

**Comment by shawkins** [comment]
Should be covered by #29116 and #19427
