### ISSUE TITLE
Selected Labels Not Displayed for Multiselect Attributes in User Profile

### ISSUE THREAD

**Issue by isaac-mercieca** [keycloak/keycloak#34456]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When using a multiselect attribute with labels configured in the user profile, the labels are correctly rendered in the dropdown options. However, after selecting an option, the component displays the raw values instead of the configured labels for each selected item.

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

- The multiselect component should display the configured labels for both dropdown options and each selected item.
- This would ensure a consistent and readable display for users, with labels shown as configured throughout the selection process.

### Actual behavior

When using a multiselect attribute with configured labels:
- The dropdown options display the correct labels as expected.
- However, once an option is selected, the component shows the raw values (not the labels) for each selected item, making it confusing for users who expect to see the labels for clarity.

### How to Reproduce?

1. Configure a user profile attribute of type multiselect with multiple values, each having an associated label.
2. Navigate to the user profile form where this multiselect attribute is displayed.
3. Open the multiselect dropdown to see the list of options. Note that each option displays the correct label.
4. Select one or more options from the dropdown.
5. Observe that after selection, the chosen options display the raw values instead of the configured labels.

**Comment by martin-kanis** [comment]
Closed by https://github.com/keycloak/keycloak/pull/34457
