### ISSUE TITLE
[26.0.2] Migration from 25.0.1 Identity Provider Errors

### ISSUE THREAD

**Issue by MarkTallentire** [keycloak/keycloak#34450]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

After Upgrading to 26.0.2 from 25.0.1 unable to access Identity Provider Page on admin console and users advise IDP disappears from login screen. 

Error recieved is "unknown error" and logs show that the SQL Statement is not expecting HIDE_ON_LOGIN to be null.

### Version

26.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

For Identity Providers to migrate correctly to the new version with no changes necessary 

OR

For the breaking changes to be detailed in the migration guide with how to resolve

I have been able to resolve this with a workaround of setting HIDE_ON_LOGIN to 0 in the database

Unsure if this is something to do with our particular setup or if its common across users

**Comment by rmartinc** [comment]
@MarkTallentire I did a quick test and using mariadb and upgrading from 25.0.1 to 26.0.2 and I see the HIDE_ON_LOGIN is 0 for a sample OIDC idp.

```sql
select INTERNAL_ID,PROVIDER_ALIAS,HIDE_ON_LOGIN from IDENTITY_PROVIDER;
+--------------------------------------+----------------+---------------+
| INTERNAL_ID                          | PROVIDER_ALIAS | HIDE_ON_LOGIN |
+--------------------------------------+----------------+---------------+
| c46ae8d6-4e4a-4888-9fac-b1f0849cca23 | oidc           |             0 |
+--------------------------------------+----------------+---------------+
```

What database are you using? Maybe it's related to the database type?

**Comment by MarkTallentire** [comment]
We’re using MSSQL.  We have 57 Realms and only about 5 of them were set to
null with the rest being 0
