### ISSUE TITLE
ABAC RBAC UBAC are NOT working on Keycloak Level (Policy Enforcer)

### ISSUE THREAD

**Issue by danielslyman** [keycloak/keycloak#34484]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

Attribute-based access control (ABAC)

Role-based access control (RBAC)

User-based access control (UBAC)

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

According to documentation: 
https://www.keycloak.org/docs/latest/authorization_services/index.html

I should be able to define ABAC RBAC or UBAC allowing users access to certain clients. When setting these up, I am successful in evaluating these policies through the KC GUI. 

I was expecting that when the policy result would result in a DENY, the user would not be able to login to the client resource. I expected Keycloak to throw a 401 unauthorized error or similar. 

I expected this:

ENFORCING
(default mode) Requests are denied by default even when no policy is associated with a given resource.
https://www.keycloak.org/securing-apps/policy-enforcer

### Actual behavior

An example is Proxmox, only user group Admin should be able to access the resource. However, any realm user is able to successfully login to Proxmox, albeit without any permissions. Proxmox on an application/client level currently does not allow cheking for roles or groups, meaning any realm user would be able to successfully login.

### How to Reproduce?

Simply install v26.0.0, create client and user, set up restrictive policies and see them not enforced.

### Anything else?

Am I missing something or is this simply not intended out-of-the-box by Keycloak? I was hoping to have a centralized solution for managing access to several self-hosted applications and only setup up role and group mapping on an application level when needed.

**Comment by pedroigor** [comment]
You should expect Keycloak acting as a centralized authorization services but the enforcement is actually done by the policy enforcer.

The `keycloak-policy` (as per the link you shared) Java library will give you the components to enable policy enforcement to your application with built-in support for Jakarta EE. Do you have some code that shows how you are using the library?

**Comment by danielslyman** [comment]
> You should expect Keycloak acting as a centralized authorization services but the enforcement is actually done by the policy enforcer.
> 
> The `keycloak-policy` (as per the link you shared) Java library will give you the components to enable policy enforcement to your application with built-in support for Jakarta EE. Do you have some code that shows how you are using the library?

Thanks for answering! I believe I may have misunderstood something on a more foundational level:

I believed, that I could basically offload authentication of my several self-hosted open-source apps to keycloak to have a centralized platform to manage my family and friends. It seems that this is not the in the scope of Keycloak out of the box, or rather not in the scope of any IdP. 

Essentially I wanted to disallow logging in regularly on for example Nextcloud or Proxmox, and have granular control over who would be able to login to them via Keycloak. However, it seems that Keycloak would not prevent this, but I would need to define user roles and groups on the apps themselves, correct?

**Comment by pedroigor** [comment]
> I believed, that I could basically offload authentication of my several self-hosted open-source apps to keycloak to have a centralized platform to manage my family and friends. It seems that this is not the in the scope of Keycloak out of the box, or rather not in the scope of any IdP.

This is what Keycloak is mainly about so that you can manage your users and how they authenticate to your applications. Your applications only need to be updated to act as OIDC (or SAML) clients to authenticate your users.

It seems that what you are looking for (I think) is not supported OOTB. The reason is that there is no mechanism on the server-side to restrict which roles or groups are allowed to access a client. This is something that clients should enforce by themselves once they have access to any token issued by the server.

The `keycloak-policy-enforcer` library is about enabling a Policy Enforcement Point (PEP) to your Java application so that you can query the server for access decisions. See https://www.keycloak.org/docs/26.0.5/authorization_services/.
