### ISSUE TITLE
Standardization of API for Adding Users to an Organization

### ISSUE THREAD

**Issue by ZFCodingStudio** [keycloak/keycloak#34529]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Description
I would like to address an inconsistency in the API for adding users to an organization. Currently, the Keycloak backend accepts JSON data, but the body sent is in `--data-raw` string format. This causes difficulties when interacting with the API using libraries such as Axios.

### Problem
When using Axios to interact with the Keycloak API, Axios automatically converts the data into a string format. This results in the data being transformed into a string like `"id"`, making it challenging to interact with the API.

### Example
Here's an example of the current implementation using `curl`:
```bash
curl "https://example.com/admin/realms/example/organizations/organization-id/members" \
  -H "accept: application/json, text/plain, */*"\
  -H "authorization: Bearer <TOKEN>" \
  -H "content-type: application/json" \
  --data-raw "user-id"
```

When attempting to use Axios:

1. **Using an object**:
   ```javascript
   axios.post('https://example.com/admin/realms/example/organizations/organization-id/members', {
     userId: 'user-id'
   }, {
     headers: {
       'Authorization': `Bearer <TOKEN>`,
       'Content-Type': 'application/json'
     }
   })
   // Keycloak does not accept this format
   ```

2. **Using a string**:
   ```javascript
   axios.post('https://example.com/admin/realms/example/organizations/organization-id/members', 'user-id', {
     headers: {
       'Authorization': `Bearer <TOKEN>`,
       'Content-Type': 'application/json'
     }
   })
   // Axios sends the body as: "\"user-id\""
   // Response: "User not exist"
   ```

### Request
Please consider standardizing the API to accept JSON data directly, without requiring the `--data-raw` format. This will improve compatibility with modern HTTP clients like Axios and simplify interactions with the API.

Thank you for considering this request.

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

```
axios.post('https://example.com/admin/realms/example/organizations/organization-id/members', {
  userId: 'user-id'
}, {
  headers: {
    'Authorization': `Bearer <TOKEN>`,
    'Content-Type': 'application/json'
  }
})
```

### Actual behavior

```
axios.post('https://example.com/admin/realms/example/organizations/organization-id/members', 'user-id', {
  headers: {
    'Authorization': `Bearer <TOKEN>`,
    'Content-Type': 'application/json'
  }
})
// Axios sends the body as: "\"user-id\""
// Response: "User not exist"
```

### How to Reproduce?

1. Use `curl` to send a request:
   ```bash
   curl "https://example.com/admin/realms/example/organizations/organization-id/members" \
     -H "accept: application/json, text/plain, */*" \
     -H "authorization: Bearer <TOKEN>" \
     -H "content-type: application/json" \
     --data-raw "user-id"
   ```
   This request successfully adds the user to the organization.

2. Use Axios to send a request with an object:
   ```javascript
   axios.post('https://example.com/admin/realms/example/organizations/organization-id/members', {
     userId: 'user-id'
   }, {
     headers: {
       'Authorization': `Bearer <TOKEN>`,
       'Content-Type': 'application/json'
     }
   })
   // Keycloak does not accept this format
   ```

3. Use Axios to send a request with a string:
   ```javascript
   axios.post('https://example.com/admin/realms/example/organizations/organization-id/members', 'user-id', {
     headers: {
       'Authorization': `Bearer <TOKEN>`,
       'Content-Type': 'application/json'
     }
   })
   // Axios sends the body as: "\"user-id\""
   // Response: "User not exist"
   ```

Following these steps will reproduce the issue.

**Comment by JonasDev17** [comment]
Related to this: https://github.com/keycloak/keycloak/issues/34401

**Comment by sguilhen** [comment]
@pedroigor This seems to have been covered by #34401, no?
