### ISSUE TITLE
Keycloak cookies are not sent via Iframe

### ISSUE THREAD

**Issue by deanmaster** [keycloak/keycloak#34533]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I'm using oidc-client-ts library for doing OIDC login with Keycloak. It's not keycloak javascript but this library is very popular for SPA with OIDC. I hope this is not the problem for this bug.

I attached 1 image when doing silent renew in Chrome. As you can see all cookies which requires for checking if user is logged in and do renew are sent via IFrame.

[
<img width="1910" alt="Screenshot 2024-10-31 at 08 29 35" src="https://github.com/user-attachments/assets/8fc384e3-0ca8-4ad9-a657-00ea2ef50e5e">
](url)

On another hand, the same request from firefox which only allow to send AUTH_SESSION_ID include a warning that it will be rejected in the future. By not sending these cookies the silent renew process is falied as you can see the 2nd request has error=login_required. The result of this problem is the user will be kicked out and require login again. Normally you set token for 5 mins and user get kicked out after that.
<img width="1900" alt="Screenshot 2024-10-31 at 08 28 58" src="https://github.com/user-attachments/assets/cb9af12c-6ad7-4e95-85e6-eb77b156c53f">

i'm using 

### Version

26.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The cookies of Keycloak should be sent normally in Firefox

### Actual behavior

many cookies from Keycloak can't be sent via IFrame

### How to Reproduce?

Just run with same application, setting Keycloak token expire time to 1 mins. Observe:
* in Chrome the silent renew process runs  infinity 
* in Firefox you will see login form of your application immediately

### Anything else?

I'm aware of this issue for long time but now it's getting more serious because the users which are using firefox and we can't always make Keycloak has same domain with application because 1 Keycloak can be used by multiple projects and each project has their own domain.

**Comment by deanmaster** [comment]
hi @stianst ,

I read your reply on issues https://github.com/keycloak/keycloak/issues/24335 I understand it honestly. Either we have partitioned cookie and IFrame would work (silent _renew) and SSO would not work due to cookie is not "shared" in different domain.

We keep non-partitioned cookie and SSO will work in all application (same realm) but then user need to login every few mins due to short token life time and silent renew (using IFrame) does not work.

I'm wondering how Google IDP would work I think they are using OIDC as well do you have any experience with this? 
How SSO would work because I know Firefox and Safari forces Partitioned Cookie so there is no renew token process using IFrame in those browsers ? it's only work with Chrome ? 

This is really difficult situation.

**Comment by mposolda** [comment]
@deanmaster TBH, I don't consider this as Keycloak bug. There is no indication in any specification that Keycloak cookies must be able to be sent via iframes. If I am wrong here, please re-open but then please point me to some OIDC/OAuth specification with the requirements for cookies. Otherwise please open an enhancement for this instead of the bug.

I don't know what exactly you mean by "silent renew", but normally, the OAuth/OIDC applications can renew the tokens by sending token refresh requests as described in the OAuth/OIDC specifications (for example here https://datatracker.ietf.org/doc/html/rfc6749#page-47 ). That is also what Keycloak adapters are doing (including the javascript adapter, which is used by admin console or account console).
