### ISSUE TITLE
Make cache-remote-host available when feature multi-site or cache-embedded-remote-store is enabled

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#34536]
### Description

Make the option `cache-remote-host` available and required when the `multi-site` feature is enabled. Also, it must be available when the feature `cache-embedded-remote-store` is enabled, but it is not required since users can configure the remote store directly in the Infinispan XML configuration file.

Validate that if `cache-remote-username` or `cache-remote-password` is set, then both must be set. 

### Details

Idea from https://github.com/keycloak/keycloak/issues/34482#issuecomment-2447772718

**Comment by mhajas** [comment]
It should be also enabled for `CLUSTERLESS` feature.
