### ISSUE TITLE
Keycloak 26.0.4 - Client Adapter for Javascript as ZIP not found

### ISSUE THREAD

**Issue by vrindanayak** [keycloak/keycloak#34545]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

On https://www.keycloak.org/downloads.html page, for current available / released version 26.0.4, the link for Client Adapters - Javascript - ZIP is broken and results in Not Found

https://github.com/keycloak/keycloak/releases/download/26.0.4/keycloak-oidc-js-adapter-26.0.4.zip

![image](https://github.com/user-attachments/assets/1dc62b9d-7373-4c30-b2f4-85a186ddc66e)

### Version

26.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Client Adapter for Javascript as ZIP is downloadable

### Actual behavior

https://github.com/keycloak/keycloak/releases/download/26.0.4/keycloak-oidc-js-adapter-26.0.4.zip results in `Not Found`

![image](https://github.com/user-attachments/assets/68ccffa6-d60d-4f61-9b50-1fdcf5492916)

### How to Reproduce?

- Go to https://www.keycloak.org/downloads.html
- Click on `ZIP` link for `Client Adapters` - `JavaScript`

**Comment by codespearhead** [comment]
Could you please close this issue [1] in favor of [2]?

Make sure to upvote [2] by adding a 👍 to the description to help it gain visibility.

***

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
[2] https://github.com/keycloak/keycloak-web/issues/512

**Comment by codespearhead** [comment]
Could you please close this issue [1] in favor of [2]?

Make sure to upvote [2] and [3] by adding a 👍 to their description to help them gain visibility.

***

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
[2] https://github.com/keycloak/keycloak-web/issues/512
[3] https://github.com/keycloak/keycloak-web/pull/513

**Comment by vrindanayak** [comment]
Ok
