### ISSUE TITLE
Make it easy to secure JGroups transport

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#34546]
### Description

It should easy to secure the jgroups communication transport.

### Motivation

The current JGroups communication is unauthenticated and unencrypted by default. However in many security sensitive environments, it is a hard requirement to use encrypted and authenticated transports.

### Details

We could leverage jgroups support for SSL_KEY_EXCHANGE and ASYM_ENCRYPT here.

```xml
<SSL_KEY_EXCHANGE keystore_name="/path/to/keystore.p12" keystore_password="..." port="7128" stack.combine="INSERT_AFTER" stack.position="VERIFY_SUSPECT2"/>
<ASYM_ENCRYPT asym_keylength="2048" asym_algorithm="RSA" change_key_on_coord_leave = "false" change_key_on_leave = "false" use_external_key_exchange = "true" stack.combine="INSERT_BEFORE" stack.position="pbcast.NAKACK2"/>
```

This issue is a followup to #34102

**Comment by ahus1** [comment]
Thank you for bringing this up. 

How does this setup compare from a user's perspective to the one in https://www.keycloak.org/server/caching#_securing_cache_communication which is available in the latest versions of Keycloak? Note that this is designed to be used with TCP only (but we move to TCP anyway as we want to make things more consistent across different environments). 

cc: @pruivo

**Comment by pruivo** [comment]
@thomasdarimont Any reason to prefer `SSL_KEY_EXCHANGE` + `(A)SYM_ENCRYPT` instead of using TLS?

**Comment by thomasdarimont** [comment]
That was mentioned by @belaban once as a mechanism that supports credential rotation:
https://github.com/belaban/JGroups/discussions/700#discussioncomment-5152133

**Comment by pruivo** [comment]
@thomasdarimont I don't have a background in security, so probably this is a stupid question... Doesn't reloading the TLS certificates achieve the same level of security? 

@ahus1 I have no objection to adding this to Keycloak, although we need a new set of CLI options.

**Comment by belaban** [comment]
@thomasdarimont JGroups actually does support of reloading of keys/certificates in {{TLS}}/{{TCP}}. Currently, this is done via a file watcher, which reloads keys when the key/truststore has changed. A way to do this via a (probe/CLI) command could easily be added.
The same could be done for {{SYM_ENCRYPT}}: you could change keys in the keystores across the cluster, then trigger a reload via CLI or probe.sh, or programmatically.

**Comment by sschu** [comment]
Assuming JDBC_PING is used for discovery, wouldn't it be nice to allow automatic encryption by just generating keys and sharing them via the database?

**Comment by belaban** [comment]
Absolutely. At the end of the day, every node needs a shared key; but how you actually install such a key is open. You could pull (e.g. read from DB, file system, keystore etc) or push (inject, send) it.
The other mechanism required for this is a trigger which tells the nodes that a new key is ready to be installed.

**Comment by ahus1** [comment]
There is now a proposal on how to implement this. As all non-TCP communication mechanisms will be deprecated with KC 26.1, we'll proceed with a solution for TCP only. Please follow #35577 which captures the ideas we're about to implement.

Closing this one as a duplicate.
