### ISSUE TITLE
[FGAP] [UI] Display "Permissions" section in the left side panel of admin console

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#34566]

**Comment by thomasdarimont** [comment]
Wouldn't it be better to have an "Authorization" Item in the nav with Permissions as a "Tab"?

**Comment by vramik** [comment]
> Wouldn't it be better to have an "Authorization" nav Item in the nav with Permissions as a "Tab"? I think this would be more in line with the existing "Authentication" Nav item.

Perhaps, there are some changes to the FGPA UI planned, so it'll most likely differ a bit from what is there for Authorization. Once we know more how it might look like, I will share additional details.
