### ISSUE TITLE
Keycloak sub calim missing in keycloak 26.0.X

### ISSUE THREAD

**Issue by guitcastro** [keycloak/keycloak#34591]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I am aware of the [changes related to sub claim in keycloak 25.0.0](https://www.keycloak.org/docs/latest/release_notes/#lightweight-access-token-to-be-even-more-lightweight). Which does not affect me, however after upgrading to keycloak 26.0.X (I tried all versions) the sub is missing. 

I double checked and the Sub mapper is registered, and even passing the "basic" claim explicit did not worked. 

### Version

26.0.0

### Regression

- [x] The issue is a regression

### Expected behavior

The sub claim should be in the JWT

### Actual behavior

The sub claim is missing from the jwt

### How to Reproduce?

1. Start keycloak:
`docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.0.5 start-dev`
2. Fetch user access_token
```
curl --location 'http:l//ocalhost:8080/realms/master/protocol/openid-connect/token/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'password=admin' \
--data-urlencode 'client_id=admin-cli' \
--data-urlencode 'username=admin' \
--data-urlencode 'grant_type=password'
```
3. See that the token sub is missing from the jwt using jwt.io or any other method.

**Comment by rmartinc** [comment]
@guitcastro The admin-cli are now using lightweight access tokens (see release notes for [26.0.0](https://www.keycloak.org/docs/latest/release_notes/index.html#lightweight-access-tokens-for-admin-rest-api)). Sub is not included in lightweight access tokens. You can disable ligtweight if needed in the admin-cli or add a sub mapper in the dedicated coped that is added in the lightweight access token.

**Comment by guitcastro** [comment]
@rmartinc  Thanks, this was the case.
