### ISSUE TITLE
Remove duplicate lines in userprofile freemarker template

### ISSUE THREAD

**Issue by bsa01** [keycloak/keycloak#34614]
### Description

There are some copy/paste duplicate lines in freemarker template.

**Comment by mposolda** [comment]
@ssilvert @ahus1 Adding team-ui and team-sre to this issue as related PR was reviewed,  merged and marked for backport by you and core-client was not involved at all in the original PR

**Comment by ahus1** [comment]
IMHO `team-sre` is not involved here, so I'm removing it. 

I just happend to merge the PR after the UI team approved it, and also moved it to the right column on the board after it was tagged by @ssilvert.

**Comment by ssilvert** [comment]
I don't think this really needs a backport to 26.0.  Not sure why I added that.
