### ISSUE TITLE
Server Fails to Start Due to '--proxy-headers xforwarded' Whitespace Error Despite Documentation Syntax

### ISSUE THREAD

**Issue by Alfagun74** [keycloak/keycloak#34641]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core (how should i know, please make this field not required, im a damn user)

### Describe the bug

Server fails starting because:

```
Option: '--proxy-headers xforwarded' is not expected to contain whitespace, please remove any unnecessary quoting/escaping" but this is how the docs show to use the option.
```

### Version

26.0.5

### Regression

- [X] The issue is a regression. (Parsing worked in 26.0.1)

### Expected behavior

It should accept '--proxy-headers xforwarded'. 

### Actual behavior

Throws error:
```
Option: '--proxy-headers xforwarded' is not expected to contain whitespace, please remove any unnecessary quoting/escaping" but this is how the docs show to use the option.
```

### How to Reproduce?

Working:
```
FROM quay.io/keycloak/keycloak:26.0.1
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers xforwarded", "--http-enabled true"]
```

Not working:
```
FROM quay.io/keycloak/keycloak:26.0.5
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers xforwarded", "--http-enabled true"]
```

**Comment by Alfagun74** [comment]
i got it working using this code:

```
FROM quay.io/keycloak/keycloak:26.0.5
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers=xforwarded", "--http-enabled=true"]
```

Note the equals sign. But docs still show with spaces on several pages.

**Comment by shawkins** [comment]
You should double check the 26.0.1 behavior as this did not work there - but it did on much older versions that used an exec in the kc.sh script. You must supply the arguments separately for them to be space delimited: 

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers", "xforwarded", "--http-enabled", "true"]

This is called out in the docs here https://www.keycloak.org/docs/latest/upgrading/#kc-sh-and-shell-metacharacters

**Comment by Dirtyone95** [comment]
Complaints about game vault.got videos

**Comment by Dirtyone95** [comment]
Got videos of reels changing winning lines on many platforms
