### ISSUE TITLE
Keys tab showing disabled and inactive keys as active

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#34675]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Support customer reports that "when a key provider is created with the "Active" option "off", the key still appear in the Active keys list of the Admin console (Admin Console -> "Realms settings" menu -> "Keys" tab -> "Keys list" sub-tab).

The key status based filtering is disabled for first item of the FILTER_OPTIONS menu, which is "active". It seems this is the cause of this issue."

-----------------------------------

I have verified the bug on 26.0.4

### Version

26.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Don't show inactive and disabled keys when filter is set to `Active keys`

### Actual behavior

inactive and disabled keys shown

### How to Reproduce?

Add a disabled and/or inactive key provider on the `Add providers` subtab.
Go back to `Keys list` and see the new key listed with `Active keys` set.

**Comment by charley04310** [comment]
Hey, can you assign it to me ?
