### ISSUE TITLE
`ClientConnection.getRemoteAddr` can return a hostname when behind a reverse proxy

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#34671]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When a reverse proxy sets the `Forwarded` header, the `for` part (identifying the original remote client) might not always contain an IP address but [something else](https://datatracker.ietf.org/doc/html/rfc7239#section-6) that can be parsed as a hostname. The [`ClientConnection.getRemoteAddr`](https://github.com/keycloak/keycloak/blob/8853a942f9653ec567341045a9063deaa6c227d5/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusClientConnection.java#L33-L35) despite its name return a hostname (or IP if it's not a hostname). This is not correct as it does not match what the name suggest: an address.

There's already a [`ClientConnection.getRemoteHost`](https://github.com/keycloak/keycloak/blob/8853a942f9653ec567341045a9063deaa6c227d5/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/integration/resteasy/QuarkusClientConnection.java#L38-L40) method that has a better name for this purpose.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

`ClientConnection.getRemoteAddr` returns IP address, or `null` if IP address is not available.

### Actual behavior

`ClientConnection.getRemoteAddr` returns IP address, or whatever is provided in `Forwarded: for=` header.

### How to Reproduce?

Send a request to Keycloak with `Forwarded: for="_gazonk"` header and call `ClientConnection.getRemoteAddr`.

**Comment by mmoreiradj** [comment]
Hey @vmuzikar, I'd like to work on this, could you assign this to me ?

**Comment by vmuzikar** [comment]
@mmoreiradj Thank you for considering a collaboration but we're already working on this. :)

**Comment by stianst** [comment]
Fixed in https://github.com/keycloak/keycloak/commit/6a10c0e345299027a96b543875351a7a88459f88
