### ISSUE TITLE
[Admin UI] [Create resource-based permission] Resource input is disabled

### ISSUE THREAD

**Issue by rh-** [keycloak/keycloak#34678]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

# Background

The clients with the enabled fine-grained authorization have the **Authority** tab, where the **resources** and the accompanying **policies** and **permissions** can be defined.

The admin can create a resource-based permission for the given resource in the table simply by clicking the "Create permission" next to the resource of interest.

![377258023-2c99fa4a-2182-499d-b483-56657a8fb641](https://github.com/user-attachments/assets/aa98e1c3-592b-428e-a383-988db6173df8)

After clicking on the **Create permission** button, the user is redirected to the **Create resource-based permission** form with the pre-filled data, based on the selected resource.

e.g.

![377258325-b2dfccb3-0d46-47c8-8d7b-2fdfcc6ee873](https://github.com/user-attachments/assets/abe4700e-569c-4a48-874b-2da5dddbf26f)

# Problem

The **Resource** input is disabled. It's not possible to choose a different resource or add an another one.

However, when the permission is being created via the **Authorization** -> **Permissions** -> **Create permission** -> **Create resource-based permission**, the **Resource** input is editable and selecting multiple resources is possible.

![image](https://github.com/user-attachments/assets/d61fb0b4-7fc8-43d2-9f5d-a2323ec7b304)

![image](https://github.com/user-attachments/assets/5375e9d4-fa12-4d56-9167-f0f54523201b)

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

The **Resource** input is not disabled in any of the described scenarios. The admin user can change resource, add more resources via the dropdown input freely.

### Actual behavior

The **Resource** input is disabled. The admin user can't change resource, nor can't the admin add more resource(s).

### How to Reproduce?

1. Start up **Keycloak**
2. Navigate to **Clients**, select **Import client**
3. Upload the demo client with the **Authorization** enabled, e.g. : https://gist.github.com/rh-/e0ddf9d94f48efc2812c5c7612036264
4. Navigate to the newly imported client **demo-resource-permission-selection** -> **Authorization** -> **Resources**
5. Click **Create permission** next to a resource

### Anything else?

This worked as expected in **25.0.6**.
The problem first appeared in **26.0.0** and it remains through the **26.0.5**.

**Comment by edewit** [comment]
The input is disabled because you chose to create a permission for that particular resource.

**Comment by rh-** [comment]
In contrast to previous Keycloak versions it now doesn't allow to add more resources within the input. Only the pre-selected resource is available.

The new approach is rather limiting and makes the same form work differently, based on where the admin accessed it from, which is confusing.
