### ISSUE TITLE
Check same domain in login-status-iframe

### ISSUE THREAD

**Issue by EikeRTL** [keycloak/keycloak#34736]
### Description

The `login-status-iframe.html` always checks if the browser supports 3p cookies. By default a browser like safari does not support this und therefore the `checkAccess` function returns `false` and the iframe sends an `error`. 

In my opinion the check makes perfectly sense **but** only if the application "main domain" (where the iframe is embedded) differs from the keycloak "main domain" .
E.g:
Application domain: app.foo.de
Keycloak domain: auth.bar.de

If the "main domain" is the same we do not need the 3pCheck because the cookie can always be read or am i wrong?
E.g:
Application domain: app.foo.de
Keycloak domain: auth.foo.de

### Motivation

The login-status-iframe can be used in browsers like safari if the application and provider domain are the same 

### Details

Enhance the login-status-iframe like
```
...
async function checkState(clientId, origin, sessionState) {
        if (!isSameMainDomain()) {
            // Check if the browser has granted us access to 3rd-party storage (such as cookies).
            const hasAccess = await hasStorageAccess();

            // If we don't have access, signal an error.
            // As we cannot read cookies, we cannot verify the session state.
            if (!hasAccess) {
              return "error";
            }
        }
        ...
}

function isSameMainDomain() {
    try {
        const iframeHostname = new URL(document.location.href).hostname
        const parentHostname = new URL(document.referrer).hostname

        const iframeHostnameParts = iframeHostname.split('.');
        const parentHostnameParts = parentHostname.split('.');

        return iframeHostnameParts.slice(-2).join('.') === parentHostnameParts.slice(-2).join('.');
    } catch (error) {
        return false;
    }
  }
```

**Comment by jonkoops** [comment]
The 3rd party cookie check should also pass if access to the same origin is allowed, which is considered the eTLD+1 (in your example (`foo.de`). If it does not pass this should be considered a bug. However, we cannot safely assume that just because the eTLD+1 of a client domain and the domain of the auth server are the same access is granted, because this is entirely up to the browser settings.

I am not quite sure how we would go about detecting support for these cookies in Safari without also breaking other browsers aside from fragile user agent testing.

**Comment by EikeRTL** [comment]
Thanks for you clarification. I see that my assumption was false and that there are scenarios where the cookie access is not possible even in a "same-site context" because of browser restrictions.
Sadly in my test setup safari does throw an error on storage.requestStorageAccess() even if the user was already on the authentication provider page to perform a login (and was redirect back to the application). 
Like you said, that is none of your business and maybe safari act in strange ways

I am closing this issue
