### ISSUE TITLE
Unable to bring an existing brcypt hashed password to keycloak

### ISSUE THREAD

**Issue by vabburi** [keycloak/keycloak#34752]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-js

### Describe the bug

When migrating to keycloak from existing system, we want the user to be agnostic of this change and would prefer to keep existing passwords. i came across this blog that seems to cover how to do this and i was able to run the script succesfully without any errors and checked keycloak admin page and it showed the password was updated. However, user could not login to keycloak using their existing password.
https://dev.to/carnewal/import-existing-users-with-bcrypt-hashed-passwords-in-keycloak-17oo

i compared the hash values using brcypt.compare() method with what exists in CREDENTIAL table and they are a match. However, the user could not login with their existing password.

this was in js:     "@keycloak/keycloak-admin-client": "^26.0.0",

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

the user should be able to login with their existing passwords.

### Actual behavior

the user is unable to login with their existing passwords.

### How to Reproduce?

- generate a hashed password outside of keycloak using bcrypt library. 
- call KcAdminClient.users.update() method to update the user's credential to use the new hashed password generated in above step. 
`await kcAdminClient.users.update(
          { id: <user_id> },
          {
            credentials: [
              {
                type: 'password',
                value: hashedPassword,
                temporary: false,
                hashIterations: costFactor,
                algorithm: 'bcrypt',
              },
            ],
          }
        );`

- the above command will complete succesfully without any errors.
- try logging in with that user and it wont.

### Anything else?

the way we fixed it is to manually update the CREDENTIAL table with actual hashed password. This alone was not enough as the password seems to have been cached somewhere as when I login the first time, it would still fail and succesfully login the second time. This went away after we restarted keycloak.

**Comment by rmartinc** [comment]
I have done a very quick test and I could create the password using this file:

```
{
  "id": "5718f6d9-7e7f-4e62-87d4-fc9179187cd7",
  "credentials" : [ {
    "id" : "89ba3724-7e60-419c-bd41-eca6202d4fcb",
    "type" : "password",
    "userLabel" : "My password",
    "createdDate" : 1731333330276,
    "credentialData" : "{\"hashIterations\":-1,\"algorithm\":\"bcrypt\",\"additionalParameters\":{}}",
    "secretData" : "{\"value\":\"$2a$10$LFFoUNaZwW.R.Wnap5f4reLoGULRWOcVfkdMNcY1r0CWxGZlwghWG\",\"salt\":\"\",\"additionalParameters\":{}}"
  } ]
}
```

I have just inspected in the database after a password change using that library and I just copied the data in the json. Doing an update with that file:

```
./kcadm.sh update users/5718f6d9-7e7f-4e62-87d4-fc9179187cd7 -r <realm> -f file.json
```

I could login with the user with no issues.  In order to create the initial password I did this simple java file:

```java
public static void main(String... args) throws Exception {
        System.err.println(BCrypt.with(BCrypt.Version.VERSION_2A).hashToString(10, args[0].toCharArray()));
}
```

And please, keycloak-bcrypt is another library that we do not provide. So you can also ask to that library because they will know much more about the data required in the credential table than us.
