### ISSUE TITLE
Getting a warning to remove temporary admin user

### ISSUE THREAD

**Issue by atul-epam** [keycloak/keycloak#34768]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Are we only bootstrapping temp admin user and we have completely removed the concept of bootstrapping permanent admin user? Because I am not using KC_BOOTSTRAP_ADMIN_USERNAME and KC_BOOTSTRAP_ADMIN_PASSWORD variables to bootstrap my admin user but still I see warning "You are logged in as a temporary admin user. To harden security, create a permanent admin account and delete the temporary one."

I want to Bootstrap a permanent admin user, is there any way to do it without getting warning in Admin console page?
Are the following parameters completely removed KC_ADMIN_USER and KC_ADMIN_PASSWORD?

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

There should be no warning for admin user.

### Actual behavior

I see warning "You are logged in as a temporary admin user. To harden security, create a permanent admin account and delete the temporary one."

### How to Reproduce?

Bootstrap admin user using docker-compose with KC_ADMIN_USER and KC_ADMIN_PASSWORD

**Comment by sschu** [comment]
This is exactly how it is designed and documented, see https://github.com/keycloak/keycloak/issues/9829 and https://www.keycloak.org/server/bootstrap-admin-recovery. So this is not a bug.
