### ISSUE TITLE
Invalid flag for addDefaultRequiredActions

### ISSUE THREAD

**Issue by kanwhoa** [keycloak/keycloak#34769]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

In UserCacheSession.java:807 it calls the delegate with:
UserModel user = getDelegate().addUser(realm, id, username, addDefaultRoles, addDefaultRoles);

Should this be:
UserModel user = getDelegate().addUser(realm, id, username, addDefaultRoles, addDefaultRequiredActions);

to match the method signature?

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

The delegate should be called with the boolean flag to create the required actions.

### Actual behavior

The delegate should is called with the boolean flag to create the default roles.

### How to Reproduce?

N/A: source code review

### Anything else?

https://github.com/keycloak/keycloak/blob/d3c50822441845cb7aeeef8cc444f09686fc6d35/model/infinispan/src/main/java/org/keycloak/models/cache/infinispan/UserCacheSession.java#L807

**Comment by rmartinc** [comment]
Thanks @kanwhoa! Yes, you are right, this is an error. Can you please send a PR to change the line? We don't need a test, as you mention this method is probably not used much, it is always used the short form `addUser` from the interface.

**Comment by kanwhoa** [comment]
sure, will do shortly.
