### ISSUE TITLE
Allow to link an Organization Identity Provider to multiple domains

### ISSUE THREAD

**Issue by oboudet-beetween** [keycloak/keycloak#34773]
### Description

I have an organization with multiple domains.
![image](https://github.com/user-attachments/assets/7817d089-1716-4757-b88d-881693830fed)

I would like to allow to use Google to login into this organization.
So I created a Google Identity Provider, and linked it to my organization, but I can select only one domain : 

![image](https://github.com/user-attachments/assets/92a48016-7e37-4d64-8c48-7b5d19f13180)

I would like to have a select box where I can  select multiple domain (perhaps with an option "all") to allow to redirect users to google with all emails domain matching the list.

**Comment by wschomburg** [comment]
Looks like the same request https://github.com/keycloak/keycloak/issues/33804

**Comment by pedroigor** [comment]
Closing in favor of https://github.com/keycloak/keycloak/issues/33804.
