### ISSUE TITLE
commonjs fallbacks for keycloack-admin-client

### ISSUE THREAD

**Issue by tillweishaupt** [keycloak/keycloak#34779]
### Description

The keycloak-admin-client library appears to only be offered as an (outdated) ESM without commonjs fallbacks. It would be preferable to at least have commonjs fallbacks.

### Discussion

https://github.com/keycloak/keycloak-nodejs-admin-client/issues/519

### Motivation

We have to unit-test some functionality of our project, which includes mocking the keycloak-admin-client dependency using jest. Unfortunately, this does not stop the actual import (transitively in other places) which requires jest to process the library. In that process, jest fails to transform the keycloak-admin-client library from esm to commonjs, which our project is using. This leads to errors of jest encountering a Syntax Error regarding an "import statement outside a module". None of the fixes described in the linked discussion help or are feasible for us.

**Comment by jonkoops** [comment]
As mentioned in the original thread we have no intention of adding legacy module formats such as CommonJS to our JavaScript libraries. Now that Node.js [allows `require()`ing](https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require) there are no reasons to ship CommonJS at runtime.

The fact that Jest does not yet have a stable API to mock standardized modules is unfortunate, but it is possible to run your tests in standard (ESM) mode and use the new [experimental mocking API](https://jestjs.io/docs/ecmascript-modules#module-mocking-in-esm). Alternatively, you can use a testing tool that does have first class support such as [Vitest](https://vitest.dev/) (which I would highly recommend over Jest for any front-end project).

**Comment by tillmeerkamp** [comment]
> you can use a testing tool that does have first class support such as [Vitest](https://vitest.dev/)

That solved our problem with ease, thank you for your recommendation!
