### ISSUE TITLE
OTEL: Quarkiverse exporter for GCP not working

### ISSUE THREAD

**Issue by samodadela** [keycloak/keycloak#34799]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

I want to enable OTEL tracing to GCP using [quarkus-opentelemetry-exporter](https://docs.quarkiverse.io/quarkus-opentelemetry-exporter/dev/quarkus-opentelemetry-exporter-gcp.html).

I tried (on baremetal) to put the jar in the `providers` folder, run `kc.sh build`. The provider seems to be added from `kc.sh show-config` output but there is not a single line of log from the exporter. The properties passed via `JAVA_OPTS` work in our app (see reproducer below).

As an alternative please add the quarkiverse exporter to the distribution, if possible.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The exporter should start and send data to GCP.

### Actual behavior

Exporter is not activated.

### How to Reproduce?

- mkdir kctest
- cd kctest
- unzip keycloak.zip
- put script in kctest directory
- run the script - check logs and check GCP tracing console

The reproducer is this shell script. 
`skc.sh`:
```shell
#!/bin/bash

DIR=./keycloak-26.0.5

export KC_HEALTH_ENABLED=true
export KC_DB=dev-file

export KC_BOOTSTRAP_ADMIN_USERNAME=admin
export KC_BOOTSTRAP_ADMIN_PASSWORD=admin

# https://www.keycloak.org/server/all-config
export KC_FEATURES=opentelemetry
export KC_TRACING_ENABLED=true
export KC_TRACING_JDBC_ENABLED=true
export KC_TRACING_SERVICE_NAME=xyz

rm -rf "${DIR}/data"
mkdir -p "${DIR}/data/import"

# https://docs.quarkiverse.io/quarkus-opentelemetry-exporter/dev/quarkus-opentelemetry-exporter-gcp.html
(
cd "${DIR}/providers"
rm -f *.jar
V="3.8.3.1"
wget "https://repo1.maven.org/maven2/io/quarkiverse/opentelemetry/exporter/quarkus-opentelemetry-exporter-gcp/${V}/quarkus-opentelemetry-exporter-gcp-${V}.jar"
)

JAVA_OPTS=""
JAVA_OPTS="${JAVA_OPTS} -Dquarkus.otel.exporter.otlp.enabled=false"
JAVA_OPTS="${JAVA_OPTS} -Dquarkus.opentelemetry.tracer.exporter.otlp.enabled=false"
JAVA_OPTS="${JAVA_OPTS} -Dquarkus.opentelemetry.tracer.exporter.gcp.enabled=true"
JAVA_OPTS="${JAVA_OPTS} -Dquarkus.otel.semconv-stability.opt-in=http"
JAVA_OPTS="${JAVA_OPTS} -Dquarkus.otel.security-events.enabled=true"
JAVA_OPTS="${JAVA_OPTS} -Dquarkus.otel.logs.enabled=true"
export JAVA_OPTS
echo "JAVA_OPTS=${JAVA_OPTS}"

cd "${DIR}"
echo "BUILD:"
bash ./bin/kc.sh build --verbose
echo

echo "CONFIG:"
bash ./bin/kc.sh show-config
echo 

echo "START:"
#bash ./bin/kc.sh start-dev --verbose --import-realm --log-level=io.opentelemetry:fine,io.quarkus:fine,io.quarkiverse:fine,org.keycloak:debug
#bash ./bin/kc.sh start-dev --verbose --import-realm --log-level=org.keycloak:debug
bash ./bin/kc.sh start-dev --verbose --import-realm --log-level=io.opentelemetry:fine

exit $?
```

To test you probably need a service account and use `GOOGLE_APPLICATION_CREDENTIALS`, however I did not get that far - the exporter doesn't seem to be active.

### Anything else?

Links are in the description and shell script.

**Comment by shawkins** [comment]
Unfortunately extensions cannot be added via the provider directory. This currently takes creating a customized build of Keycloak with the extension dependency included in the server pom.

> As an alternative please add the quarkiverse exporter to the distribution, if possible.

cc @mabartos @ahus1

**Comment by samodadela** [comment]
@shawkins I see, thanks. Maybe add this info to the documentation.

**Comment by ahus1** [comment]
@samodadela - while Keycloak doesn't support GCP as described above, I assume you would use the "OpenTelemetry Collector Contrib" distribution which AFAIK includes a GCP exporter?

**Comment by samodadela** [comment]
@ahus1 Yes, that will be the workaround if Keycloak won't support the quarkiverse GCP exporter. However the setup is more involved since it requires a sidecar container which incurs additional costs in terms of k8s resources and maintenance.

We use OTEL in out application on some of our environments (prod, stage), development environments do not send telemetry. We enabled it in configuration.

The preferred way would be to use it as a provider (which was said is not supported) or out-of-the box (by enabling the quarkiverse GCP exported in configuration). If adding the exporter is not an option, an alternative could be to provide builds that have Quarkus telemetry including all the available exporters?

I will probably try building Keycloak with the exporter before going the sidecar route.

**Comment by mabartos** [comment]
@samodadela Hi, as stated, it's not possible to add Quarkus/Quarkiverse extension via the /providers dir. I've started a small project[1] with a simplified process around using Quarkus extensions in Keycloak. Note it's not officially supported by Keycloak and in the initial phase of development. But the principle is quite basic and there are no many places that might break. Additionally, the repo misses some comprehensive examples, but for your use case, it should work.

It is more compatible with official Quarkus extensions, so for your use case, the setup will not be so convenient. 

1. Clone https://github.com/mabartos/keycloak-quarkus-extensions
2. Navigate to `/runtime` module in the extension
3. Add this to `runtime/pom.xml`:
```
<dependency>
    <groupId>io.quarkiverse.opentelemetry.exporter</groupId>
    <artifactId>quarkus-opentelemetry-exporter-gcp</artifactId>
    <version>3.15.1.0</version>
</dependency>
```
4. Edit the `application.properties` in the root directory with your necessary Quarkus properties
5. Run `./kc-extensions build`
6. Run `./kc-extensions start-dev` (start extended Keycloak with your extensions, where you can verify the behavior)
7. In the root repo directory, you should see your final distribution `keycloak-extended-26.0.5.zip`

It fetches the Keycloak 26.0.5 distribution and add your extension. If the extension contains also dependency with `-deployment` artifactId, please add the dependency to the `deployment/pom.xml`.

I haven't tried it, but it should work like that. Let me know if that works for you.

[1] https://github.com/mabartos/keycloak-quarkus-extensions

**Comment by samodadela** [comment]
@mabartos 
Added this to runtime/pom.xml:
```
        <dependency>
            <groupId>io.quarkiverse.opentelemetry.exporter</groupId>
            <artifactId>quarkus-opentelemetry-exporter-gcp</artifactId>
            <version>3.8.3.1</version>
        </dependency>
```

Run:
```
./kc-extension.sh build
```
Using keycloak version from pom.xml: 26.0.5
Using quarkus version from pom.xml: 3.15.1
Executing build with '--keycloak-version': 26.0.5, '--quarkus-version': 3.15.1, and '--distPath': N/A
Additional properties: 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Keycloak Quarkus Extensions Parent                                 [pom]
[INFO] Keycloak Quarkus Extensions Runtime                                [jar]
[INFO] Keycloak Quarkus Extensions Deployment                             [jar]
[INFO] Keycloak Quarkus Extensions Final Resolver                         [jar]
[INFO] 
...
INFO] --- compiler:3.13.0:compile (default-compile) @ keycloak-quarkus-extensions-runtime ---
[INFO] No sources to compile
[INFO] 
[INFO] --- quarkus-extension:3.15.1:extension-descriptor (default) @ keycloak-quarkus-extensions-runtime ---
[ERROR] Quarkus Extension Dependency Verification Error
[ERROR] Deployment artifact org.keycloak:keycloak-quarkus-extensions-deployment::jar:1.0-SNAPSHOT was found to be missing dependencies on the Quarkus extension artifacts marked with '-' below:
[ERROR] +     org.keycloak:keycloak-quarkus-extensions-runtime::jar
[ERROR] +     org.keycloak:keycloak-quarkus-server-deployment::jar
[ERROR] +         io.quarkus:quarkus-vertx-http-deployment::jar
[ERROR] +             io.quarkus:quarkus-tls-registry-deployment::jar
[ERROR] +             io.quarkus:quarkus-mutiny-deployment::jar
[ERROR] +                 io.quarkus:quarkus-smallrye-context-propagation-deployment::jar
[ERROR] +         io.quarkus:quarkus-vertx-deployment::jar
[ERROR] +             io.quarkus:quarkus-netty-deployment::jar
[ERROR] +             io.quarkus:quarkus-virtual-threads-deployment::jar
[ERROR] +         io.quarkus:quarkus-reactive-routes-deployment::jar
[ERROR] +             io.quarkus:quarkus-jackson-deployment::jar
[ERROR] +         io.quarkus:quarkus-rest-deployment::jar
[ERROR] +             io.quarkus:quarkus-rest-common-deployment::jar
[ERROR] +             io.quarkus:quarkus-jsonp-deployment::jar
[ERROR] +         io.quarkus:quarkus-rest-jackson-deployment::jar
[ERROR] +             io.quarkus:quarkus-rest-jackson-common-deployment::jar
[ERROR] +         io.quarkus:quarkus-hibernate-orm-deployment::jar
[ERROR] +             io.quarkus:quarkus-narayana-jta-deployment::jar
[ERROR] +             io.quarkus:quarkus-caffeine-deployment::jar
[ERROR] +         io.quarkus:quarkus-agroal-deployment::jar
[ERROR] +             io.quarkus:quarkus-datasource-deployment::jar
[ERROR] +         io.quarkus:quarkus-jdbc-h2-deployment::jar
[ERROR] +         io.quarkus:quarkus-jdbc-postgresql-deployment::jar
[ERROR] +         io.quarkus:quarkus-jdbc-mariadb-deployment::jar
[ERROR] +         io.quarkus:quarkus-jdbc-mysql-deployment::jar
[ERROR] +         io.quarkus:quarkus-jdbc-mssql-deployment::jar
[ERROR] +         io.quarkus:quarkus-jdbc-oracle-deployment::jar
[ERROR] +         io.quarkus:quarkus-core-deployment::jar
[ERROR] +         io.quarkus:quarkus-smallrye-health-deployment::jar
[ERROR] +         io.quarkus:quarkus-micrometer-deployment::jar
[ERROR] +         io.quarkus:quarkus-micrometer-registry-prometheus-deployment::jar
[ERROR] +         io.quarkus:quarkus-logging-json-deployment::jar
[ERROR] +         io.quarkus:quarkus-opentelemetry-deployment::jar
[ERROR] +     io.quarkus:quarkus-logging-gelf-deployment::jar
[ERROR] +     io.quarkiverse.langchain4j:quarkus-langchain4j-openai-deployment::jar
[ERROR] +         io.quarkiverse.langchain4j:quarkus-langchain4j-openai-common-deployment::jar
[ERROR] +             io.quarkus:quarkus-rest-client-jackson-deployment::jar
[ERROR] +                 io.quarkus:quarkus-rest-client-deployment::jar
[ERROR] +                     io.quarkus:quarkus-rest-client-jaxrs-deployment::jar
[ERROR] +                     io.quarkus:quarkus-smallrye-stork-deployment::jar
[ERROR] +                     io.quarkus:quarkus-rest-client-config-deployment::jar
[ERROR] +             io.quarkus:quarkus-qute-deployment::jar
[ERROR] +             io.quarkiverse.langchain4j:quarkus-langchain4j-core-deployment::jar
[ERROR] -     io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-gcp-deployment::jar
[ERROR] +         io.quarkus:quarkus-arc-deployment::jar
[ERROR] +         io.quarkus:quarkus-grpc-common-deployment::jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Keycloak Quarkus Extensions Parent 1.0-SNAPSHOT:
[INFO] 
[INFO] Keycloak Quarkus Extensions Parent ................. SUCCESS [  0.220 s]
[INFO] Keycloak Quarkus Extensions Runtime ................ FAILURE [  2.762 s]
[INFO] Keycloak Quarkus Extensions Deployment ............. SKIPPED
[INFO] Keycloak Quarkus Extensions Final Resolver ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.126 s
[INFO] Finished at: 2024-11-12T14:19:08+01:00
[INFO] ------------------------------------------------------------------------
```

@ahus1 So is there some plan to support this extension in anyway? Or is building our own the only option?

**Comment by ahus1** [comment]
@samodadela - the focus now is to apply tracing in more places in Keycloak where it is useful like outgoing HTTP calls and LDAP calls.

As it is a Quarkiverse extension, I think it is unlikely as we would include it by default, as we currently only include core Quarkus parts. Maybe there will be a way in the future to add extensions in a simpler way. 

@mabartos might have a different opinion on this.

**Comment by mabartos** [comment]
@samodadela You need to add the `io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-gcp-deployment` dependency (note the `-deployment` suffix) to the `deployment/pom.xml` and run the `kc-extensions.sh build` again. Then, it should work.

We do not add any Quarkiverse extension(if not really necessary) to the Keycloak distribution as @ahus1 mentioned. Yes, the extension management for Keycloak is on our roadmap and we'd like to improve it. 

At this moment, only the community extension for extending your Keycloak distribution is the 'keycloak-quarkus-extensions' which will rebuild/extend your distribution with an ease. Still in a development phase.

**Comment by samodadela** [comment]
@mabartos Thanks. 

Added the deployment dependency to `deployment/pom.xml`, built Keycloak and started it using the script above. It works, traces can now be seen in the GCP Trace console.

I have a few more questions:
- At first I was expecting the extension or Quarkus to produce some logs, but none are seen. Do I need to configure logging some other way? I started Keycloak like this:
```
bash ./bin/kc.sh start-dev --verbose --import-realm --log-level=io.opentelemetry:fine,io.quarkiverse:fine,io.quarkus:fine
```
- Can you please point me to the instruction on how to make the Keycloak docker image using this zip?

**Comment by samodadela** [comment]
@mabartos Also if you could shortly explain... how does the extender work - it doesn't build from source, right?

For my use case, consider something like `--add-runtime io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-gcp:3.8.3.1` and `--add-deployment io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-gcp-deployment:3.8.3.1`.

I think it's a great tool - will be keeping an eye on the project.

**Comment by mabartos** [comment]
@samodadela Logging settings look good - please verify if there are really some logs emited.

Yes, the user experience about adding Quarkiverse extensions will be improved. 

I'll post more instructions next week around docker images.

The principle is quite basic as it mimics the Keycloak Quarkus-based distribution creation done in the Keycloak main. It just extend the approach, so every change in the distribution creation process will be automatically reflected in the extension for the specific version. 

It means only the new extensions are added to the process and the final /lib directory with all necessary JARs is created. So the principle is to replace /lib dir in Keycloak distribution with the new rebuilt /lib directory.

**Comment by mabartos** [comment]
@samodadela You should be able to use the extension like this now:
```
./kc-extension.sh add io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-gcp:3.8.3.1
```

Closing now as we can't include the Quarkiverse extension into the Keycloak distribution for now.

**Comment by mabartos** [comment]
@samodadela The approach should be described here: https://github.com/mabartos/keycloak-quarkus-extensions/blob/main/examples/otel-gcp-exporter.md

Please verify if it works.

**Comment by samodadela** [comment]
@mabartos Sorry for the slow pace... Tried it today using the instruction you provided. 

The build fails:
```
# ./kc-extension.sh build
Using keycloak version from pom.xml: 999.0.0-SNAPSHOT
Using quarkus version from pom.xml: 3.15.2
Executing build with '--keycloak-version': 999.0.0-SNAPSHOT, and '--quarkus-version': 3.15.2
Additional properties:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Keycloak Quarkus Extensions Parent                                 [pom]
[INFO] Keycloak Quarkus Extensions Runtime                                [jar]
[INFO] Keycloak Quarkus Extensions Deployment                             [jar]
[INFO] Keycloak Quarkus Extensions Final Resolver                         [jar]
[INFO]
[INFO] --------------< org.keycloak:keycloak-quarkus-extensions >--------------
[INFO] Building Keycloak Quarkus Extensions Parent 1.0-SNAPSHOT           [1/4]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ keycloak-quarkus-extensions ---
[INFO]
[INFO] --- install:3.1.2:install (default-install) @ keycloak-quarkus-extensions ---
[INFO] Installing /home/samod/src/github/keycloak-quarkus-extensions/pom.xml to /home/samod/.m2/repository/org/keycloak/keycloak-quarkus-extensions/1.0-SNAPSHOT/keycloak-quarkus-extensions-1.0-SNAPSHOT.pom
[INFO]
[INFO] ----------< org.keycloak:keycloak-quarkus-extensions-runtime >----------
[INFO] Building Keycloak Quarkus Extensions Runtime 1.0-SNAPSHOT          [2/4]
[INFO]   from runtime/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.keycloak:keycloak-quarkus-server:jar:999.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Keycloak Quarkus Extensions Parent 1.0-SNAPSHOT:
[INFO]
[INFO] Keycloak Quarkus Extensions Parent ................. SUCCESS [  0.208 s]
[INFO] Keycloak Quarkus Extensions Runtime ................ FAILURE [  1.226 s]
[INFO] Keycloak Quarkus Extensions Deployment ............. SKIPPED
[INFO] Keycloak Quarkus Extensions Final Resolver ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.589 s
[INFO] Finished at: 2025-01-29T13:31:59+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project keycloak-quarkus-extensions-runtime: Could not resolve dependencies for project org.keycloak:keycloak-quarkus-extensions-runtime:jar:1.0-SNAPSHOT
[ERROR] dependency: org.keycloak:keycloak-quarkus-server:jar:999.0.0-SNAPSHOT (compile)
[ERROR]     Could not find artifact org.keycloak:keycloak-quarkus-server:jar:999.0.0-SNAPSHOT
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :keycloak-quarkus-extensions-runtime
```

**Comment by mabartos** [comment]
@samodadela Ahh, sorry, it should be fixed now.
