### ISSUE TITLE
Log handler specific log levels support only lower-case levels

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#34817]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Log handler specific log levels support only lower-case levels (`info` for example), while the global level supports upper case (INFO or info).

This is a bit confusing as the syntax differs between the two, and also the [documented log levels](https://www.keycloak.org/server/logging#_log_levels) are all in upper case.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

Both `--log-syslog-level=INFO` and `--log-syslog-level=info` should work just like for `--log-level`.

### Actual behavior

The following error message is displayed:
```
Invalid value for option '--log-syslog-level': INFO. Expected values are: off, fatal, error, warn, info, debug, trace, all
```

### How to Reproduce?

`kc.sh start-dev --log-syslog-level=INFO`

**Comment by kaustubh-rh** [comment]
Hi @stianst , can i fix this bug ?

**Comment by stianst** [comment]
@kaustubh-rh sure thing, feel free to send a PR
