### ISSUE TITLE
AdminUI: Alphabetically sort "Event saved type" in the events listing

### ISSUE THREAD

**Issue by boomer41** [keycloak/keycloak#34811]
### Description

Currently when using the Events section in the AdminUI, you can filter for "Event saved type".
However, that list is not even close to being alphabetically sorted, and finding the type you are interested in is a pain.
Thus, I request that that list is being sorted alphabetically (after translation of course) to make it way easier for admins to look for the event they want.

Currently running KC 26.0.5.

### Motivation

It currently is hard to find the event the admin wants to filter for in a completely non-sorted list:

![image](https://github.com/user-attachments/assets/aa16dff6-bd08-4b75-8880-0d114f20d999)

**Comment by ssilvert** [comment]
I'm changing this one to a bug because it's pretty bad for usability and it will be easy to fix.

We should at least make the list alphabetical.  Bonus points if it is searchable.
