### ISSUE TITLE
SSO with Keycloak and Azure IDP, user getting Account exists popup screen when login into keycloak (when user already created into Keycloak DB). 

### ISSUE THREAD

**Issue by Dipti3010** [keycloak/keycloak#34831]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

SSO with Keycloak and Azure IDP, user getting Account exists popup screen when login into keycloak (when user already created into Keycloak DB). 

![Uploading Keycloak.png…]()

Affected users' reports vary weekly. Sometimes 1 or 2 other weeks can be 5 or 6.Issue is an intermittent.

Found following log errors in keycloak logs.
**type=IDENTITY_PROVIDER_FIRST_LOGIN_ERROR, error=invalid_user_credentials,**

### Version

26

### Regression

- [ ] The issue is a regression

### Expected behavior

Users needs to login successfully.

### Actual behavior

SSO with Keycloak and Azure IDP, user getting Account exists popup screen when login into keycloak (when user already created into Keycloak DB). 

### How to Reproduce?

Intermittently,  existing users will get an error when attempting to login w/ SSO with  “Account already exists” Solution realm login
error 
 
Keycloak displays a  “Account already exists” and proposes 2 buttons to the user:
 
“Review profile”
“Add to existing account”
 
We then need to go into Key cloak on AADS and delete the user and have them log back in and then they are fine moving forward

**Comment by foliengriller** [comment]
This is imho intended behavior. You can adjust it in the "First Broker Login Flow".

**Comment by Dipti3010** [comment]
I have observed this issue in 2-3 versions of keycloak. Keycloak 26 also have this issue.


![Keycloak](https://github.com/user-attachments/assets/4a72b63f-012f-4f4f-90a6-8cbf340cb519)


Getting above screen when user facing the issue.

**Comment by Dipti3010** [comment]
@foliengriller  Can you please explain how to adjust it in the "First Broker Login Flow"

**Comment by Dipti3010** [comment]
Hi team,

 I have configured the following Flow in Keycloak, Please let me know if it is okay or need to do correction.

![Auth_flow](https://github.com/user-attachments/assets/4d1845f8-5b3c-4a12-b29e-35e6a7baf532)

**Comment by DREGALLA** [comment]
> I have observed this issue in 2-3 versions of keycloak. Keycloak 26 also have this issue.
<img width="321" alt="Keycloak_Error" src="https://github.com/user-attachments/assets/91171d44-c168-4aac-982c-d216527052e4">


> Getting above screen when user facing the issue.

**Comment by Dipti3010** [comment]
Additionally, I found following error logs in keycloak logs.
2024-10-22 08:00:05,796 WARN  [org.keycloak.events] (executor-thread-2271) type=**IDENTITY_PROVIDER_FIRST_LOGIN_ERROR**, realmId=,error=invalid_user_credentials, 

2024-10-23 08:19:42,770 WARN  [org.keycloak.events] (executor-thread-2523) type=**REFRESH_TOKEN_ERROR,**

Please suggest , Which setting need to check on Keycloak ?

**Comment by jonkoops** [comment]
Are you sure you are on the latest version of Keycloak? The UI you have in the screenshot is from before Keycloak 18.

**Comment by Dipti3010** [comment]
@foliengriller Could this problem be caused by many users on Azure using the same email address? Can we set "Verify Existing Account By Email" as Disabled on "First Broker Login"
<img width="544" alt="Auth_flow_email" src="https://github.com/user-attachments/assets/8ba3322b-6204-4089-b4d9-b37b05d3212d">

**Comment by pedroigor** [comment]
> Could this problem be caused by many users on Azure using the same email address?

I think so too because the user will then be prompted to either review the profile (and authenticate with the existing account) or link the account.

> Can we set "Verify Existing Account By Email" as Disabled on "First Broker Login"

I'm not quite sure what will cause disabling this authentication execution but you won't be able to have users with duplicate e-mails if `Duplicate emails` (Realm Settings)  setting is not enabled.

**Comment by Dipti3010** [comment]
Please check additional configuration of keycloak.
<img width="803" alt="Map_01" src="https://github.com/user-attachments/assets/ab2cbf3a-01b8-46e8-a9db-ea1fea12d55a">
<img width="707" alt="Duplicate_email" src="https://github.com/user-attachments/assets/7bd68f85-b08e-4277-b3f9-fb6dfa825db5">

**Steps to  reproduce the issue:**
1. Users are stored in LDAP & I am using Azure IDP. On my application I have configured the IDP.
2. When I am trying to login client, Intermittently, existing users will get an error when attempting to login w/ SSO with “Account already exists” Solution realm login error.
3. Keycloak displays a “Account already exists” and proposes 2 buttons to the user:
**“Review profile”
“Add to existing account”**
<img width="321" alt="Keycloak_Error" src="https://github.com/user-attachments/assets/c530f8e4-02fa-4b76-ae75-c3d492eb3040">

4. After manually removing impacted users from keycloak GUI, Login will work.
5. I have already shared mapper & first broker login flow which I am using.
Facing similar issue as below:
https://keycloak.discourse.group/t/third-identity-provider-idp-how-to-avoid-the-account-already-exists-form/17747
https://stackoverflow.com/questions/56013500/keycloak-account-already-exists-dialog-displayed-intermittently-when-i-attemp

**Comment by Dipti3010** [comment]
> > Can we set "Verify Existing Account By Email" as Disabled on "First Broker Login"
> 
> I'm not quite sure what will cause disabling this authentication execution but you won't be able to have users with duplicate e-mails if `Duplicate emails` (Realm Settings) setting is not enabled.

@pedroigor Can I enabled "Duplicate emails" setting , currently it's disabled on my system.

**Comment by pedroigor** [comment]
Not sure if  `dupicate emails` makes sense for your use case. Most of the time, it don't make much sense to enable it. The use cases around it are still a bit blurry for me.

Another possible cause is that something is going wrong when the user is authenticating for the very first time and federated/created in the local database. However, since the user did not complete the first-broker login flow, the account is already in the database and will fail to create the user again when resuming the first-broker login flow.

**Comment by rijo-armada** [comment]
Any updates on this issue. I am getting the same intermittently for some users and when i delete the user and start a fresh login it works.

**Comment by kyale** [comment]
I'm facing this issue as well whenever the realm is deleted and reimported. It somehow does not affect all users, just some of them. This is what is being logged when this happens
```
[org.keycloak.events] (executor-thread-1501) type="IDENTITY_PROVIDER_FIRST_LOGIN_ERROR", realmId="***", realmName="***", clientId="***", userId="***", ipAddress="127.0.0.1", error="invalid_user_credentials", identity_provider="***", auth_method="openid-connect", redirect_uri="***", identity_provider_identity="***", code_id="***", username="***"
```
