### ISSUE TITLE
Display Password Policies on the Registration Page

### ISSUE THREAD

**Issue by waynemorphic** [keycloak/keycloak#34856]
### Description

I have a custom Keycloak theme running on V26 and would like to display useful FieldMessages to users on my UI before they input their passwords when registering on my platform. I've attached an example of what I would like to achieve in this image.  I am thinking of starting with a function that returns a `boolean` for checking if a `PasswordPolicy` has been created such as `Minimum Password Length` etc. Ideally, the policies should be validated as the user enters their password while concurrently checking the buttons for the associated password policy. How do I go about it?

### Motivation

UI Improvements

### Details

<img width="905" alt="Screenshot 2024-11-07 at 3 30 46 PM" src="https://github.com/user-attachments/assets/2028869d-cf22-4c90-9177-0de26aec61b7">

**Comment by edewit** [comment]
this has been fixed with https://github.com/keycloak/keycloak/pull/32846
