### ISSUE TITLE
Deprecated CLI options and new options are not stable in their sorting

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34858]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Keycloak uses a set of the deprecated options and their alternatives, which leads to differently sorted output in the docs.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

All options should be stable in their sorting. Possibly sorted alphabetically automatically.

### Actual behavior

The sorting switches between

```
STRICT and WILDCARD have been deprecated, use DEFAULT instead.
*Deprecated values: `+WILDCARD+`, `+STRICT+`*
```

and 

```
STRICT and WILDCARD have been deprecated, use DEFAULT instead.
*Deprecated values: `+STRICT+`, `+WILDCARD+`*
```

in the nightly build of Nov 9. 

### How to Reproduce?

See downstream docs build for RHBK26

### Anything else?

The `options.adoc` template or possibly one of the beans where the data is retrieved from needs fixing.

**Comment by ahus1** [comment]
Thank your for the fix, @shawkins! Looking at the change, it changes some APIs. Therefore I it might not be a good candidate for a KC26 backport. Let me know if you think otherwise.

**Comment by shawkins** [comment]
> Let me know if you think otherwise.

There shouldn't be an issue with backporting.

**Comment by ahus1** [comment]
> There shouldn't be an issue with backporting.

Thank you for the feedback. I've marked it for backporting to KC26. Please create a backport when you have the time (no urgency here).
