### ISSUE TITLE
On logout from admin console, a serverinfo call with 401 response in the logs

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34864]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When logging out of the admin console, there is one request to the serverinfo endpoint with no access token. This results in a 401 response code. 

This will create unnecessary noise in the system as it indicates an unauthorized access to a production monitoring system.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

No 401 when logging out

### Actual behavior

A 401 with a `Bearer undefined` 

![image](https://github.com/user-attachments/assets/ee2bb26d-7754-4473-a0fb-5aa6dd49ca21)

### How to Reproduce?

* Start Keycloak
* Login as admin on http://localhost:8080/
* Open the developer console and clear the network tab
* Logout -> 401 request appears

Tested with Chrome 130 on Fedora

**Comment by ssilvert** [comment]
I have verified this.

**Comment by iamkaustubhb** [comment]
Hi @ssilvert @ahus1 , can I raise a PR for the same ?

**Comment by kaustubh-rh** [comment]
Hi @ssilvert @ahus1 , can I raise a PR for the same ?

**Comment by ahus1** [comment]
@kaustubh-rh - I'm just the reporter of the issue, I wouldn't be a reviewer as it is UI related and I'm no pro on React things. Maybe @ssilvert has an opinion here. If he doesn't reply, go ahead with a PR :-)

**Comment by ssilvert** [comment]
@kaustubh-rh Yes, a PR would be great.

**Comment by edewit** [comment]
the way we find out now that the user is not logged in is by doing a request, how else would we know that the user is no longer logged in?
