### ISSUE TITLE
Clients invalidated on each client credential grant

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34875]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After the change in #34664 a client is invalidated on each call as `client.getClientScopes(true).containsKey(serviceAccountScope.getId())` is always false as the `id` is a UUID and the keys are the scope names.

https://github.com/keycloak/keycloak/blob/226daa41c72a7c2f0831dcaec6890eeed67afb30/services/src/main/java/org/keycloak/protocol/oidc/grants/ClientCredentialsGrantType.java#L86

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

If a default scope is already set, don't call enable service account

### Actual behavior

KC runs enable service account, thereby invalidating the Keycloak cache

### How to Reproduce?

Debugging

**Comment by ahus1** [comment]
@rmartinc - can you please have a look at this issue as you've been involved in the PR that triggered it? 

I would suggest to change `serviceAccountScope.getId()` to `ServiceAccountConstants.SERVICE_ACCOUNT_SCOPE` to make the code work. Still I'm not 100% sure if this is the correct change. Looking at the code, enabling the service account will never set the default scope, so for some clients that don't have this set as a default scope this would then always be called which might not be what was intended here. 

Happy to hear your thoughts. 

As this is invalidating clients all the time for client credential grants, this breaks our nightly performance tests. While it is not urgent for KC26.0, we would like to see a fix rather sooner than later so we get performance results again. We are currently testing the performance on ARM, and this one is now blocking us. 

Thanks!

**Comment by mhajas** [comment]
Here are some flamegraphs showing the difference in Client credential grant perf test with and without the suspected commit.

With commit, current main:
![image](https://github.com/user-attachments/assets/091f4017-902a-4df5-9ba8-dcc33b29f5a3)

With the commit reverted:
![image (1)](https://github.com/user-attachments/assets/c3e3f917-b6b7-4e02-a908-37b052933e2b)
