### ISSUE TITLE
Incomplete registration form when edit email is disabled and email is set as username

### ISSUE THREAD

**Issue by Alex0jk** [keycloak/keycloak#34876]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When registration is active or there is an org invite, if I have set email as username to true: 
<img width="327" alt="image" src="https://github.com/user-attachments/assets/2cc6a615-96df-438f-ba4f-d837a7095cf8">

And I also have set that users are not able to edit their emails:
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/568274fa-9dcc-4cc5-8481-7bf151deb5c0">

Then the registration screen is incomplete and users are not able to register:
<img width="835" alt="image" src="https://github.com/user-attachments/assets/c9a3109d-cd3a-41cc-862d-95d97c2cd36f">

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect that user registration is not tied to the setting I set for users in the realm allowing them to register without issues even if their username is the email and the email is not editable once registered.

Also, for invitation to an organization I would expect that if an email is already set, then the rule that they cannot edit it is enforced.

### Actual behavior

Setting email as username and removing the ability to edit the email breaks the registration process (both when registration is enabled and on org invite)

### How to Reproduce?

Activate registration or send an org invite to a non existent user.

Activate email as username:
<img width="327" alt="image" src="https://github.com/user-attachments/assets/2cc6a615-96df-438f-ba4f-d837a7095cf8">

Remove the ability to edit emails for users:
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/568274fa-9dcc-4cc5-8481-7bf151deb5c0">

Go to the registration screen and see that it is incomplete.

### Anything else?

A similar issue was reported and closed a few version ago, when the user profile was not a fully supported feature:
https://github.com/keycloak/keycloak/issues/17439

**Comment by rmartinc** [comment]
@Alex0jk But if you enable edit for the email attribute in the profile what happens?

Doing some quick tests if I set email editable for users, I can register the user and then the email is not editable in the account console (because `edit username` is off in the realm settings).

Obviously your suggestion still stands for other attributes (any other attribute that just wanted to be added by users at registration and then set it as no editable). But I think that it's simply not working in that way. That would be an enhancement in my opinion.

**Comment by Alex0jk** [comment]
@rmartinc If I enable edit for the email, then registration will work as I expect. And yes, the email becomes non editable after registration. Thing is, that currently there would still be some odd behaviors in different registration flows. 

For example, during registration when a org invite is set, the user will be able to edit their email and there is not way for me to set it so emails are not editable for a user during that process, as setting the email as not editable make registration not possible and setting it as editable just gives users full edit control there.

I think that it makes sense that this falls in the enhancement category, and maybe there are multiple enhancement that could be proposed. I reported this as a bug, as I find the current behavior a bit weird and it is odd that there is a way for an admin to completely break the registration flow without a warning.

**Comment by martin-kanis** [comment]
@Alex0jk So the original issue you are trying to solve is, that when you send a organization invitation for a given email, the registration form should have the email pre-filled and not editable? 
I checked the current behavior and the email is pre-filled and editable, but when you try to change it and send the form, the user will get an error saying the email does not match the invitation email. So it kind of works even though the UX is not great. 

Then the second problem is that when you don't allow editing emails, email is not shown in the registration form and it would be nicer to have it there (again, not great UX)?

**Comment by Alex0jk** [comment]
@martin-kanis Yes. Thanks for verifying that changing the email will make it so users can't register, I think that makes the problem less of an issue.

As for the second problem, it is a bit more of an UX issue because if email edition is disabled, then also the password creation form is not available either, creating a situation where new users cant register.
