### ISSUE TITLE
Allow a DPoP Proof by considering a clock skew for smooth interoperability

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#34894]
### Description

By follwing [the latest FAPI 2.0 security profiles draft](https://openid.bitbucket.io/fapi/fapi-2_0-security-profile.html#name-general-requirements), 

An authorization server should allow the following request object: 
- whose "iat" and "nbf" claim is within 0 to 10 seconds ahead in the future.

An authorization server should reject the follwoing request object:
- whose "iat" and "nbf" claim is over 60 seconds ahead in the future.

Whether a DPoP Proof whose "iat" and "nbf" claim is within 11 to 60 seconds ahead in the future is accepted or not is up to the authorization server.

Considering a clock skew, there are two cases about it:

-    case 1: a client's clock is ahead Keycloak's clock
-    case 2: a client's clock is behind Keycloak's clock

 To remedy case 1, the valid time slot is as follows:

-    current keycloak clock => "iat" - clock skew
-    current keycloak clock => "nbf" - clock skew

 To remedy case 2, the valid time slot is as follows:

-    current keycloak clock <= "exp" + clock skew

     or

-    current keycloak clock <= "iat" + life time + clock skew

Therefore, the valid time slot is as follows:

-    "iat" - clock skew <= keycloak's clock <= "exp" + clock skew

      or

-    "iat" - clock skew <= keycloak's clock <= iat" + life time + clock skew

Considering that these claim values are in seconds, the valid time slot uses <=, >=, instead of <, >.
Acceptable clock skew is +-15 seconds. There is no clear basis for the value.

**Comment by ahus1** [comment]
+1 for having the clock skew, the FAPI settings make sense here for the clock skew like in other places. 

One comment about the example provided above: This describes a clock skew between the client and Keycloak. This would cause problems if the client would have created the token. IMHO it is usually IdPs that create the tokens, and their clocks can have a skew. It might even be that different instances of the same Keycloak cluster have a clock skew between them, and then would reject a token. 

Therefore, IMHO allowing for a clock skew is important in all places where we verify tokens.

**Comment by tnorimat** [comment]
@ahus1 Thank you for the comment, and I agree with it. It is better to verify any kind of token created outside Keycloak.
AFAIK, there are such tokens as follows :

1. Created by an OAuth 2.0 client / OIDC RP

- JWT Client Assertion for Client Authentication (very short lifetime)
- Request Object / JAR (JWT-Secured Authorization Request) (very short lifetime)
- DPoP Proof (very short lifetime)

2. Created by IdPs by Identity Brokering:

- Access Token (short lifetime)
- ID Token (?)
- Refresh Token (long lifetime)

Maybe there are other such tokens (Token Exchange : external token, etc).

**Comment by ahus1** [comment]
@tnorimat - thank you for pointing out to me that clients sometimes create tokens as well. I stand corrected, and I'm sorry for missing that.
