### ISSUE TITLE
Upgrade 24 to 25 fails because db jpa changes drop nonexisting indexes.

### ISSUE THREAD

**Issue by rvanderboom** [keycloak/keycloak#34899]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

When upgrading from keycloak 24 to keycloak 25 the migration fails because the jpa upgrade script has DROP INDEX instructions from columns who do not exist on PRODUCTION environment only.
THis because keycloak doesn't create indexes if nr of records above a limit. Therefore OTA succeeded.

Its not the first time our upgrade failed and we had to generate sql scripts via other upgrade method...

It whould be handy to check if indexes exist in the jpa instructions, to avoid migration failure.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Migration doesn't fail if indexes that are dropped in jpa do NOT exist.

### Actual behavior

Failure on drop instructions:

ERROR: Can't DROP 'IDX_OFFLINE_USS_CREATEDON'; check that column/key exists [Failed SQL: (1091) DROP INDEX IDX_OFFLINE_USS_CREATEDON ON keycloak_prod.OFFLINE_USER_SESSION]

the following columns do only exist on our ota environment and NOT on production, since production has records above the limit that keycloak creates indexes:

   <dropIndex tableName="OFFLINE_USER_SESSION" indexName="IDX_OFFLINE_USS_CREATEDON" />
        <dropIndex tableName="OFFLINE_USER_SESSION" indexName="IDX_OFFLINE_USS_PRELOAD" />
        <dropIndex tableName="OFFLINE_USER_SESSION" indexName="IDX_OFFLINE_USS_BY_USERSESS" />
        <dropIndex tableName="OFFLINE_CLIENT_SESSION" indexName="IDX_OFFLINE_CSS_PRELOAD" />
        
        
        

### How to Reproduce?

remove above indexes and upgrade from keycloak 24 to 25..

(othere upgrade versions had this issue before, so therefore report it now).

**Comment by rvanderboom** [comment]
Additional remark:

Please don't answer: "you should have created index manual".
SIince keycloak decides not to create them in previous version, we don't created them manual since it does not add anything for us performance wise. In contrast some tables are so big (20 miljioen or more), that not always an index is helpen if features are not used and doesn't hit an index anyway...

Its a small effort to check if an index exists or not, since letting migration fail and causing issues op production (last time we had bigger problems since it hit a big table, and where offline for 2 hours since it was breaking half way).

**Comment by rvanderboom** [comment]
Another remark:
You write somewhere when > 300.000 we do not create index.
If its about the release, we tested and not the creation but the drop iindex with lot of records can hang up everything.
we tried to drop an index on a table with 20 miljoen records , it takes ages... The creation in a second...

**Comment by vramik** [comment]
Thanks @rvanderboom for creating the issue. I agree we should check the index exist before its deletion. 

> Another remark: You write somewhere when > 300.000 we do not create index. If its about the release, we tested and not the creation but the drop iindex with lot of records can hang up everything. we tried to drop an index on a table with 20 miljoen records , it takes ages... The creation in a second...
> 
> To my opinion an option would be not to drop in the release at all , and mention in the upgrade guide "drop these indexen manually as we think they are not needed"..

Could you please create separate issue for aforementioned if you think it makes sense. It won't be handled withing this one. Thanks a lot.

**Comment by rvanderboom** [comment]
see https://github.com/keycloak/keycloak/discussions/34950
