### ISSUE TITLE
Inline contents from the migration guide to the server development guide

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#34903]
### Description

When reviewing the server development guide, it still points to the migration guide which handles is based on Keycloak 20. It feel a bit strange to refer to that guide still. Instead, the important bits should be inlined here.

In addition, we don't have this guide (and a different guide) in downstream. 

As a temporary measure, in #34877 those links were either excluded in the downstream docs, or replaced with a link to the downstream migration guide.

### Motivation

Make this simpler to read and simpler to maintain. 

### Details

In the reworked version, no `ifeval` should be remaining in the `javaee.adoc` for upstream and downstream, and any relevant content should be inlined.

**Comment by ahus1** [comment]
@vmuzikar - this came up when reviewing the docs for KC 26.0. I wonder if your team can have a look at this for KC 26.2 and refactor the docs. Thanks!

cc;: @andymunro

**Comment by vmuzikar** [comment]
Please see my comment here: https://github.com/keycloak/keycloak/issues/34881#issuecomment-2472890456.

**Comment by ahus1** [comment]
Ok, closing a a duplicate. Sorry for the noise.
