### ISSUE TITLE
[Keycloak JavaScript CI] - Account UI E2E - my-resources.spec.ts

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#34910]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

Failed in `release/26.0` branch, but might affect `main` as well.

```
Error:   1) [chromium] › my-resources.spec.ts:55:3 › My resources page › One is shared with alice ─────────
    Error: expect(received).toEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 1

    - Array [
    -   "one",
    - ]
    + Array []

      59 |     await page.getByTestId("sharedWithMe").click();
      60 |     const rowData = await page.getByTestId("row[0].name").allTextContents();
    > 61 |     expect(rowData).toEqual(["one"]);
         |                     ^
      62 |   });
      63 | });
      64 |

        at /home/runner/work/keycloak/keycloak/js/apps/account-ui/test/my-resources.spec.ts:61:21
```

https://github.com/keycloak/keycloak/actions/runs/11794126380/job/32851346018

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by edewit** [comment]
stabilisation worked, closing
