### ISSUE TITLE
Two "admin" realm roles in the master realm with differently associated realm permissions

### ISSUE THREAD

**Issue by MaikLoewe** [keycloak/keycloak#34929]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In our Keycloak instance, there are two "admin" realm roles in the master realm, which also have different GUIDs in the system. We added the GUID in the description to analyze the bug.
![grafik](https://github.com/user-attachments/assets/d9f5f90e-1c49-4b69-b690-f7304fc06199)

Both admin roles were associated with different roles from the existing realms. The two roles were divided the existing 15 realms into 5 to 10 parts. The bug was noticed because not all realms appeared in the realm dropdown, not even on the following pages.

We made a backup of the database and tried to combine all roles into one admin role and delete the second. We were able to combine all roles of the REALMs into one admin role. However, it was not possible to assign this realm role to the administrative user, as it simply did not appear. Not even as a local administrator.

The second admin role in the liste with 10 realms associated:
![grafik](https://github.com/user-attachments/assets/f8a53e20-e1bc-4727-9d1e-6f78372efca9)
The first  admin role in the liste with all 15 realms associated:
![grafik](https://github.com/user-attachments/assets/62358190-b732-4aa3-918e-d164aa6736f3)

The internal administrator with one of the role associated:
![grafik](https://github.com/user-attachments/assets/4753e21c-6f77-4e63-b1c1-de34928cb670)
The attempt to get the second admin role added to that user:
![grafik](https://github.com/user-attachments/assets/66eb99ae-e91f-443c-ac16-bcff9cc4e12e)

Even a completely new user (admin) only sees the incomplete admin realm role and the one that can be seen cannot be added.
![grafik](https://github.com/user-attachments/assets/61042104-01ed-4616-920f-59c7059ae9d8)

Unfortunately, it is also not possible to use the visible admin realm role, because not all realm roles can be associated with it.
![grafik](https://github.com/user-attachments/assets/c2f862cd-82e7-4c46-92ce-87c979da2de9)

Thanks for your help and excuse if I open the issue in the wrong place.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

We only want to see one realm admin role or at least can delete one.

### Actual behavior

We see two real admin roles that cannot be merged, see bug description.

### How to Reproduce?

Sorry, we don't know how we got the second roll in.

**Comment by MaikLoewe** [comment]
What I forgot to mention: the bug has probably been around for more than a year, but it's only with the new UI that it has really come to our attention. Furthermore, the installation is already several years old and has been updated from version 16 to the current version again and again. The installation is Docker based.
Sorry

**Comment by ssilvert** [comment]
@MaikLoewe I suspect that maybe the extra admin role snuck in a long time ago from a bad realm import.  But that's only a wild guess.

Nevertheless, there is no way we could pursue a fix for this without a way to reproduce the problem.

**Comment by MaikLoewe** [comment]
Hello @ssilvert, 

I am very grateful to receive a reply so quickly, thanks to the great community!

Unfortunately, this is understandably very vague, and without being able to reproduce the problem, it is almost impossible to determine the cause. Especially if there are some version updates in between.
Nevertheless, your hint helped, because we found out that it only affects realms that a certain administrative user created.

We will analyze the case a bit more, but ultimately we will set up a new instance and transfer the realms. The configurations are often very straightforward and we expect few problems.

If it doesn't bother you, I would leave the ticket open and, if necessary, document our findings for the affected account.

Regards Maik

**Comment by ssilvert** [comment]
@MaikLoewe That's fine.  I can change the status to "Missing Info".  Then when you supply new info it will go back to triage and I will see it again.
