### ISSUE TITLE
next-auth fails with keycloak idp but not other idp

### ISSUE THREAD

**Issue by idc77** [keycloak/keycloak#34938]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

https://github.com/nextauthjs/next-auth/discussions/12222
When using next-auth v5 with a confidential client, at least next-auth complains that `"response" is not a conform Token Endpoint response`
Sadly I don't know how to debug this from the nextjs side, so I can't tell what the "non-conform token endpoint response" looks like.
However using Zitadel as an IDP, there are no issues, so it must be either something Keycloak changed from 25.0.5 to 26.0.5, or something in the next-auth keycloak adapter.
It is likely a regression, because I tried next-auth about a year ago with Svelte and Keycloak and had no issues. But there are many unknowns to tell.

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

After logging in the next.js app using next-auth v5 with the keycloak provider,
there should not be an error page saying what it does.

### Actual behavior

An error page is shown

### How to Reproduce?

- install keycloak
- create a realm
- add a confidential client to the realm
- create a user
- create a next.js app
- add next-auth@beta aka v5
- create a login button as documented in next-auth for keycloak
- log in

### Anything else?

I upgraded kc from 25.0.5 to 26.0.5 recently, which also broke other, prod, sites

**Comment by panva** [comment]
OPs client software gets a 301 from the token endpoint instead of the expected 200

**Comment by idc77** [comment]
It was https://github.com/keycloak/keycloak/discussions/34803
Since 26.0.5 or just 26, it's not documented when this change happened, or in the upgrade docs that it's required to set those values:

keycloak.conf
```
proxy-headers=xforwarded
proxy-trusted-addresses=127.0.0.0/8
```

nginx conf file
```
        location / {
                proxy_pass http://127.0.0.1:4001;
                proxy_set_header Host               $host;
                proxy_set_header X-Real-IP          $remote_addr;
                proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto  $scheme;
                proxy_buffer_size 64k;
                proxy_buffers 8 64k;
                proxy_busy_buffers_size 64k;
        }
```

**Comment by jonkoops** [comment]
Thanks for getting to the bottom of that @idc77. I'll double check if we can improve the documentation around this.
