### ISSUE TITLE
Docs: upgrading/topics/changes/changes-25_0_2.adoc

### ISSUE THREAD

**Issue by renekloth** [keycloak/keycloak#34946]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The docs say, that in release 25.0.2 a new index is added for table USER_CONSENT_CLIENT_SCOPE. So I assume, that jpa-changelog-25.0.2.xml file exists, where the index will be created. But there is no such file!

File: upgrading/topics/changes/changes-25_0_2.adoc

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Update the docs: no index will be created

### Actual behavior

The docs says an index will be created

### How to Reproduce?

Looking at the [jpa-changelog-master.xml](https://github.com/keycloak/keycloak/blob/26.0.5/model/jpa/src/main/resources/META-INF/jpa-changelog-master.xml#L86), there is no changelog file between releases 25.0.0 and 26.0.0.

**Comment by rmartinc** [comment]
@renekloth This change was needed to be backported to previous versions and, for that reason, it was added to the file [jpa-changelog-18.0.15.xml](https://github.com/keycloak/keycloak/blob/26.0.7/model/jpa/src/main/resources/META-INF/jpa-changelog-18.0.15.xml) (check commit ce195b81f82e21c97616431cd6fb0e3b05b4e729 and issue https://github.com/keycloak/keycloak/issues/30992). But it was added in version 25.0.2, that file does not exists in previous versions. I'm closing this issue.
