### ISSUE TITLE
Unable to scroll/swipe through the main menu on macOS

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#34968]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Currently it's not possible to scroll up or down/use swipe gesture over the menu on the left:
<img width="453" alt="image" src="https://github.com/user-attachments/assets/ce0ec35d-5a40-40ed-a930-2b7118492773">
This effectively means that some of the lower menu items may not be reachable on a smaller screens (unless you zoom out).

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

To be able to use scrolling/swipe gesture.

### Actual behavior

Scrolling/swiping is not possible.

### How to Reproduce?

Reproduced on MacOS, using Safari and Edge browser:
* open Admin Console
* make the browser window smaller if necessary
* try to scroll/swipe over the menu

**Comment by ssilvert** [comment]
@Pepo48 I tried this with the Edge browser.  I was able to use my scroller on the mouse to move the browser window up and down to see all of the lefthand menu items.  But I'm on Windows.

**Comment by Pepo48** [comment]
@ssilvert I can confirm that on Windows it works as expected. It's platform specific. @vmuzikar also reproduced the bug on his MacOS machine.
