### ISSUE TITLE
Keycloak using HOSTNAME URL instead of ADMIN URL for /resources

### ISSUE THREAD

**Issue by scibol** [keycloak/keycloak#34964]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

![Keycloak_Error](https://github.com/user-attachments/assets/b0067ca3-b277-42d8-8589-a401e897ae49)
I have setup
```
KC_HOSTNAME_URL: https://dev-auth-.../auth
KC_HOSTNAME_ADMIN_URL: https://dev-auth-admin-.../auth
```
When accessing the master (and every realm), it is trying to fetch the `/auth/resources/master/admin/en` from `KC_HOSTNAME_URL `and it receives 404. The resources are available on `KC_HOSTNAME_ADMIN_URL`. Note that all other resources are loaded properly, except the one on` /REALM_NAME/`. so it's not because of `/auth`.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

`/auth/resource/master/admin/en `is available on `KC_HOSTNAME_ADMIN_URL`

### Actual behavior

`/auth/resource/master/admin/en` is available on `KC_HOSTNAME_URL`

### How to Reproduce?

With Keycloak v.24.0.3, start with the following parameters
```
KC_HOSTNAME_URL: https://dev-auth-.../auth
KC_HOSTNAME_ADMIN_URL: https://dev-auth-admin-.../auth
```

**Comment by shawkins** [comment]
This is functioning as expected - only /admin resources are accessible via the admin url. 

See also #32458 and #32159

**Comment by scibol** [comment]
Hi @shawkins, thanks for the heads-up. But I do not understand then, how to make it work? The CSS does not load if I login using the admin url. How to make the admin UI display properly? I mean I could set `HOSTNAME_URL = HOSTNAME_ADMIN_URL` but that defats the purpose.

**Comment by shawkins** [comment]
> But I do not understand then, how to make it work? The CSS does not load if I login using the admin url. How to make the admin UI display properly?

Why does the CSS not load? Are you not allowing access via a proxy?

**Comment by scibol** [comment]
> > But I do not understand then, how to make it work? The CSS does not load if I login using the admin url. How to make the admin UI display properly?
> 
> Why does the CSS not load? Are you not allowing access via a proxy?

I am deploying on Openshift so I guess it is behind the Openshift ingress but nothing special.
Sorry it is not strictly CSS but the general resources found under `/resources/master/admin/en`. It is trying to access this path with the HostnameUrl (404) and not the adminUrl. The resource is accessible behind the adminUrl. The result is this funky UI shown in the screenshot before

**Comment by shawkins** [comment]
Do you not have ingress for https://dev-auth-.../auth?

**Comment by shawkins** [comment]
I'm not quite sure I follow what is going on here. 

You wouldn't expect a 404 from Keyclaok just by changing the host - that seems like an issue that has been introduced by the proxy / ingress.

**Comment by bouchardmathieu-qc** [comment]
> This is functioning as expected - only /admin resources are accessible via the admin url.
> 
> See also [#32458](https://github.com/keycloak/keycloak/issues/32458) and [#32159](https://github.com/keycloak/keycloak/issues/32159)

No it's not. The documentation says that using the --hostname-admin option allows to use the admin console with that URL. But the reality is that we need both the admin URL and the frontend URL of the master realm to use the admin console with the admin hostname.

The documentation doesn't say anywhere that you need to also update the frontendUrl attribute of the master realm to be able to log in to the admin console only with the hostname-admin URL. We had to search for hours to understand how it is now configured and looking at the number of bugs submitted for that issue, I think we are not alone with that problem.

**Comment by shawkins** [comment]
> No it's not. The documentation says that using the --hostname-admin option allows to use the admin console with that URL. But the reality is that we need both the admin URL and the frontend URL of the master realm to use the admin console with the admin hostname.

That is not correct nor expected.

Please move any additional comments to an open issue or discussion.
