### ISSUE TITLE
admin user creation issue

### ISSUE THREAD

**Issue by iambstha** [keycloak/keycloak#35011]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

welcome/ui

### Describe the bug

changing default database to postgres causing issue while providing admin username and password

![image](https://github.com/user-attachments/assets/38976eed-93fd-4d1d-b386-cf58ecd1106e)

### Version

26.0.5

### Regression

- [x] The issue is a regression

### Expected behavior

Admin user should have been created

### Actual behavior

Admin user seems to be not found

### How to Reproduce?

reproduce the issue using this compose file

version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpassword
      KC_DB_URL: "jdbc:postgresql://db:5432/keycloak_db"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./keycloak_data:/opt/keycloak/data

  db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bishal -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5

**Comment by ogronome** [comment]
I can add, that setting through environment is also broken (tried both 26.0.0 and 26.0.5


bash file contents
```
echo $KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD

kc.sh bootstrap-admin user --username adm --password:env KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD

```

bash file output
```
+ echo BlaBlaPass
BlaBlaPass
+ /home/ess/keycloak/bin/kc.sh bootstrap-admin user --username adm --password:env KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD
Environment variable KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD not found

```

**Comment by ogronome** [comment]
try (I'm not dev)

KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: admin
KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: admin

**Comment by sschu** [comment]
@iambstha I cannot reproduce the problem. I used your compose file fixed the wrong user in the health check (should be `dbuser`, not `bishal`) and I can directly login using username `admin` and password `admin`.

**Comment by iambstha** [comment]
Thanks for the help. It worked with

    environment:
      KC_DB: postgres
      KC_DB_USERNAME: bishal
      KC_DB_PASSWORD: shrestha
      KC_DB_URL: "jdbc:postgresql://db:5432/keycloak_db"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev','--verbose']
    ports:
      - 8081:8080
      - 8443:8443
      - 8787:8787
      
     but i didn't get why the issue was in the first place.
