### ISSUE TITLE
organization claim missing when user joines multiple organization

### ISSUE THREAD

**Issue by jw-cpnet** [keycloak/keycloak#35025]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

organization claim is missing from the token if the user has joined into multiple organizations.

![image](https://github.com/user-attachments/assets/ef05ea5d-6299-47a2-b192-63ba8d0e346d)

here is the decoded access token if the user joined only one organization:

![image](https://github.com/user-attachments/assets/6cd35da5-99b8-4920-9da6-61410d33d708)

```json
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "lzq31iERmzWFXthdapZ2MJugqfko5ONqOt3Wl7fcPIc"
}.{
  "exp": 1731892242,
  "iat": 1731891942,
  "auth_time": 1731891942,
  "jti": "1385596d-2b19-489e-9e41-fee59aaaeb0b",
  "iss": "http://localhost:8080/realms/fastapi",
  "sub": "8cd79aa4-78fe-46ce-97a9-e9bfdc0e49be",
  "typ": "Bearer",
  "azp": "api-swaggerui",
  "sid": "ce136fe5-d5aa-4434-bf12-e1edb48df81d",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:8000"
  ],
  "realm_access": {
    "roles": [
      "tenant_user"
    ]
  },
  "scope": "openid email profile organization",
  "email_verified": true,
  "organization": {
    "company_a": {
      "id": "00535f3c-4e6a-4ac1-8809-6ad2a3da478d"
    }
  },
  "name": "Test User",
  "groups": [
    "/Factory A"
  ],
  "preferred_username": "testuser",
  "given_name": "Test",
  "family_name": "User",
  "email": "testuser@example.com"
}.[Signature]

```

if the user has joined multiple organizations:

![image](https://github.com/user-attachments/assets/012e85b9-c8b2-4a9b-be2f-f580c6c652e4)

```json


{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "lzq31iERmzWFXthdapZ2MJugqfko5ONqOt3Wl7fcPIc"
}.{
  "exp": 1731891891,
  "iat": 1731891591,
  "auth_time": 1731891591,
  "jti": "6336fd1e-8c9e-432d-ab54-fda367dd4421",
  "iss": "http://localhost:8080/realms/fastapi",
  "sub": "8cd79aa4-78fe-46ce-97a9-e9bfdc0e49be",
  "typ": "Bearer",
  "azp": "api-swaggerui",
  "sid": "a493ae09-def9-467e-af1a-62c8f5d89c3a",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:8000"
  ],
  "realm_access": {
    "roles": [
      "tenant_user"
    ]
  },
  "scope": "openid email profile organization",
  "email_verified": true,
  "name": "Test User",
  "groups": [
    "/Factory A"
  ],
  "preferred_username": "testuser",
  "given_name": "Test",
  "family_name": "User",
  "email": "testuser@example.com"
}.[Signature]
```

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

when user was assigned to multiple organizations, the organization claim should be something like

```json
...
  "organization": {
    "company_a": {
      "id": "00535f3c-4e6a-4ac1-8809-6ad2a3da478d"
    },
    "company_b": {
      "id": "1233432-fdfas-xadf-1234-xxxxxxxxxxxxxx"
    }
  },
  ...
  ```
 

### Actual behavior

organization claim missing from the token

### How to Reproduce?

![image](https://github.com/user-attachments/assets/55e47c31-d487-4a02-b299-a4b5eb848c1f)
with this set up and assign 2 organizations to the same user.

**Comment by martin-kanis** [comment]
@jw-cpnet Please see https://github.com/keycloak/keycloak/issues/33556 I think is the same issue.
