### ISSUE TITLE
InfinispanConnectionProviderFactory major differences in the configuration of the cache manager

### ISSUE THREAD

**Issue by simse07** [keycloak/keycloak#35038]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

Hello,

while trying to solve https://github.com/keycloak/keycloak/issues/34971 I took a look at the [DefaultInfinispanConnectionProviderFactory](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java). It provides a fallback initialization for the CacheManager, if no managed cache manager is available.

By comparing the setup of the [remote](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java#L241) and [embedded](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/connections/infinispan/DefaultInfinispanConnectionProviderFactory.java#L275) cache managers, I noticed that it is not compatible to the implementation of the corresponding methods in the CacheManagerFactory:
- [startEmbeddedCacheManager](https://github.com/keycloak/keycloak/blob/release/26.0/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java#L280)
- [startRemoteCacheManager](https://github.com/keycloak/keycloak/blob/release/26.0/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/storage/infinispan/CacheManagerFactory.java#L142)

I would expect that the same configuration is applied.
Additionally, metrics and persistent user session are not fully supported. The caches for user/offline user/client/offline client sessions are not updated to reflect the changed configuration of memory and number of owners.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

Cache configuration of the fallback cache matches the configuration of the CacheManager Factory.

### Actual behavior

Cache configuration of the fallback cache does not match the configuration of the CacheManager Factory.

### How to Reproduce?

Comparing the lines of code as mentioned in the description.

**Comment by pruivo** [comment]
Both `initEmbedded` and `initRemote` are used for unit and functional tests, where the Quarkus runtime is unavailable. It is normal not to be 100% a match since features such as metrics or security are not relevant for function testing.

**Comment by ahus1** [comment]
@pruivo - can this issue be closed or are there any further actions needed?

**Comment by pruivo** [comment]
@ahus1 closing it as it brings no value.
