### ISSUE TITLE
Flaky test: org.keycloak.testsuite.model.session.AuthenticationSessionTest#testConcurrentAuthenticationSessionsCreation

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#35087]
This test failed 18% of the time in 100 runs with retries disabled

## org.keycloak.testsuite.model.session.AuthenticationSessionTest#testConcurrentAuthenticationSessionsCreation
[Keycloak CI - Store Model Tests](https://github.com/keycloak/keycloak/actions/runs/11908938899/job/33185571110) / [Pull Request #35057](https://github.com/keycloak/keycloak/pull/35057)

```
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
...
```

**Comment by ahus1** [comment]
@pruivo - can you please have a look at this failing test? Thanks!

**Comment by stianst** [comment]
From a previous run on 22 November this failed 18 out of 100 times, but from a run today it didn't fail at all.
