### ISSUE TITLE
[LoginUI] Set HTML lang attribute to "en" when internationalization disabled

### ISSUE THREAD

**Issue by andreas-blaettlinger** [keycloak/keycloak#35103]
### Description

There are some issues with the current handling of the `lang` attribute in the html tag within the `template.ftl`:

`<html class="${properties.kcHtmlClass!}"<#if realm.internationalizationEnabled> lang="${locale.currentLanguageTag}"</#if>>`

The `lang` attribute is set only when internationalization is enabled, and it is omitted entirely when internationalization is disabled. This behavior could cause problems for screen readers, which rely on the lang attribute for accurate output.

### Discussion

https://github.com/keycloak/keycloak/discussions/35050

**Comment by piyush7833** [comment]
can this be assigned to me? thanks. @andreas-blaettlinger

**Comment by andreas-blaettlinger** [comment]
I am already in development, but you're welcome to review it when it's finished @piyush7833.
