### ISSUE TITLE
Not getting correct exception/response message for Set/update password with a password that fails to comply with password policy

### ISSUE THREAD

**Issue by atul-epam** [keycloak/keycloak#35178]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

I am trying to hit following API in my Spring boot project to reset the password of a user:
			
**keycloak.realm(realmId).users().get(userId).resetPassword(credentialRepresentation);**

**Class**: org.keycloak.admin.client.resource.UserResource
**Method**: resetPassword(CredentialRepresentation credentialRepresentation);

I can see following error in keycloak logs but in spring boot code, I am getting "400 bad request" exception without any reason specified for it, which is incorrect behavior. There is no way to know, what exact error was there and what was the reason behind it. 

[org.keycloak.services.resources.admin.UsersResource] (executor-thread-6) Password policy not met for user username1: org.keycloak.policy.PasswordPolicyNotMetException: invalidPasswordMinUpperCaseCharsMessage
keycloak-1       |      at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:789)
keycloak-1       |      at org.keycloak.services.resources.admin.UsersResource.createUser(UsersResource.java:157)
keycloak-1       |      at org.keycloak.services.resources.admin.UsersResource$quarkusrestinvoker$createUser_49ad02a153eab6ba1571548b97a4fecbdc7a7465.invoke(Unknown Source)
keycloak-1       |      at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-1       |      at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-1       |      at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-1       |      at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
keycloak-1       |      at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
keycloak-1       |      at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
keycloak-1       |      at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
keycloak-1       |      at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
keycloak-1       |      at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
keycloak-1       |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-1       |      at java.base/java.lang.Thread.run(Thread.java:1583)
keycloak-1       | Caused by: org.keycloak.models.ModelException: invalidPasswordMinUpperCaseCharsMessage
keycloak-1       |      at org.keycloak.credential.PasswordCredentialProvider.createCredential(PasswordCredentialProvider.java:62)
keycloak-1       |      at org.keycloak.credential.PasswordCredentialProvider.updateCredential(PasswordCredentialProvider.java:158)
keycloak-1       |      at org.keycloak.credential.UserCredentialManager.lambda$updateCredential$2(UserCredentialManager.java:98)
keycloak-1       |      at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
keycloak-1       |      at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak-1       |      at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
keycloak-1       |      at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
keycloak-1       |      at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1808)
keycloak-1       |      at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
keycloak-1       |      at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
keycloak-1       |      at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
keycloak-1       |      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
keycloak-1       |      at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
keycloak-1       |      at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
keycloak-1       |      at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-1       |      at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
keycloak-1       |      at org.keycloak.credential.UserCredentialManager.updateCredential(UserCredentialManager.java:98)
keycloak-1       |      at org.keycloak.models.utils.RepresentationToModel.createCredentials(RepresentationToModel.java:787)
keycloak-1       |      ... 13 more

On using following REST API, response body contains correct reason of failure:
**http://localhost:8080/admin/realms/{{RealmId}}/users/{{userId}}/reset-password**

![image](https://github.com/user-attachments/assets/80ba4341-7efe-4717-aecc-c85195e0be1a)

Similar issue is there when I am trying to set password for a user while creating it:
user.setCredentials(List.of(credentialRepresentation)));
response = keycloak.realm(realmId).users().create(user);

In this case, there was no exception thrown and getting response object with 400 response code without specifying reason of failure but in Keycloak logs same error is there that I mentioned earlier.  

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

We should get response something like below for java api call, similar to what we get for REST api call:

{
    "error": "invalidPasswordMinSpecialCharsMessage",
    "error_description": "Invalid password: must contain at least 1 special characters."
}

### Actual behavior

There is response "Bad Request".

### How to Reproduce?

Mentioned in description.

**Comment by atul-epam** [comment]
Any update on this please?

**Comment by rmartinc** [comment]
@atul-epam You can d something like the following:

```java
    try {
        client.realm("lala").users().get("6c71d9ab-a56b-463e-bab2-2e381927f998").resetPassword(rep);
    } catch (BadRequestException e) {
        OAuth2ErrorRepresentation error = e.getResponse().readEntity(OAuth2ErrorRepresentation.class);
        System.out.println(error.getError() + " " + error.getErrorDescription());
    }
```


Does it not work for you?

**Comment by atul-epam** [comment]
It is working with Provided solution. Thanks.
