### ISSUE TITLE
Ldap, email mapper problem on active Directory

### ISSUE THREAD

**Issue by QuentinAxyus** [keycloak/keycloak#35194]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

All the email domain of user in keycloak db of a realm that use an ldap provider, got the same "domain name of ldap server" from the Windows Active Directory and not the value that is in the value "mail" from LDAP. 

For exemple, if on a Active directory server named "addomain.com" i got a user witch mail value is "user@otherdomain.com", in keycloak i will have: "user@addomain.com" so it does not use directly the mail value of the Active Directory server, or modify it after. 

All was working perfectly in all the previous version i was using.
The lattest where it was working was 24.0.X (could not remember precisly the version)

### Version

26.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

If the mapper use the ldap mail value, it should get all the mail value. 
for exemple this:
![Capture d'écran 2024-11-21 145433](https://github.com/user-attachments/assets/efc51e67-cfd4-4baa-9323-47d9c5933cf9)

So in the previous exemple i should have "user@otherdomain.com" the value in "Mail" from Active Directory.

### Actual behavior

it got the domain name of ldap server and not the value of "mail" that come from Active Directory.

But if i enable "Always Read Value From LDAP" on the mapper, then it become correct again. 

### How to Reproduce?

Use An active directory server whitch domain name is "addomain.com".
In this domain, create user, and configure mail for exemple "user@testdomain.com"

Connect an Active Directory server to keycloak via: 
"LDAP" ==> Vendor: "Active Directory"

Map, the value mail to email to keycloak:
![Capture d'écran 2024-11-21 145433](https://github.com/user-attachments/assets/046428d2-998a-42fc-b980-734cda1f88a0)

Do not enable "Always Read Value From LDAP" on the email mapper

In keycloak, all the user will have "@ADDomain.com",

**Comment by pedroigor** [comment]
If the a mapped attribute (eg: email) is already available from the local database, it will resolve to the value in the local database. By enabling `Always Read Value From LDAP` you will force reading from LDAP.

I would say this is the expected behavior.

**Comment by QuentinAxyus** [comment]
> If the a mapped attribute (eg: email) is already available from the local database, it will resolve to the value in the local database. By enabling `Always Read Value From LDAP` you will force reading from LDAP.
> 
> I would say this is the expected behavior.

Hello, i am not enouth clear perhaps. 
So will try to explain more, and make a simple exemple.

So BEFORE the update (version 24.X.X), ALL the email in keycloak database was similar to the AD database. All got the correct "domain" there.
So BEFORE everything was right.

AFTER the update to 26.0.5, ALL the email adresse domain switch for the AD server domain name. 
The only solution to get the correct value was to enable the option "Always Read Value From LDAP". 
(but even with that option, i could not correct to keycloak with email adresse from ldap, i should use the email adress with the wrong domain name to connect )



Here is a simple case to see the pb.
I disable the option "Always Read Value From LDAP". 

I create this user in the AD with email **test.adgit@testgit.fr**
![image](https://github.com/user-attachments/assets/6f242e36-27f0-4145-93ba-dacb527e753f)

I sync the user from the ldap connector:
![image](https://github.com/user-attachments/assets/5d587e55-4a50-4201-bd41-041771a23e44)
![image](https://github.com/user-attachments/assets/bcc25b7b-93e5-499c-8de8-6140254d2196)

And my user is here but, the email domain is wrong (of course i do nothing between the two things):
![image](https://github.com/user-attachments/assets/fd090d9d-4bf6-4d56-81aa-b19d5763dcfe)

If i enable again the option "Always Read Value From LDAP", it goes back to be ok:
![image](https://github.com/user-attachments/assets/4f89fc73-efcf-4b8a-bc17-a63a6e70b48c)
But as i said before, even with that option enable, i could not connect with the email adresse "test.adgit@testgit.fr" i should use the test.adgit@a...........com to connect... 



And as i said, it was not the case before, all were working correctly. 

THank's

**Comment by pedroigor** [comment]
I see. In my environment, I have a Samba AD and there I have users with an email domain other than the AD domain. For instance, `ldapuser@foo.org`.

If I create a new LDAP provider in the realm and `Sync all users`, the emails are imported and shown using the expected domain, not the AD domain. The `email` mapper is also set to disabled `"Always Read Value From LDAP`.

I think these are the same steps you previously described?

**Comment by QuentinAxyus** [comment]
Hello.

Yes it's the same configuration. 
Perhaps the problem is only when connected to an ActiveDirectory Server? 

Even if i enable  "Always Read Value From LDAP", i could not loggin with the correct email even if in keycloak i see the correct email, the only email that works is the one with the "Ad Domain".

**Comment by pedroigor** [comment]
I'm also testing using AD. Not sure what is the difference.

**Comment by QuentinAxyus** [comment]
So ok, i took a look, the previous version that was ok was 24.0.5.
I update to 25.0.6 (the latest) and it change nothing. 

I restart le AD server (check all microsoft update was there) and keycloak, nothing change. 

I will try to make a new installation of keycloak to see if i see the same result but i do not found any idea/solution from what could explain such result.

**Comment by pedroigor** [comment]
Thanks. I want to reproduce this locally because I cannot find any place where emails are replaced with the AD domain.

As I mentioned, I'm using Samba AD and this image https://github.com/diegogslomp/samba-ad-dc. If you can try the same with this image, perhaps we can assume the problem is when using a real AD server and simplify this investigation.

**Comment by QuentinAxyus** [comment]
So, i install a fresh version of 26.0.6 and add the same server in ldap.
For security i set it to read mode note write (only difference) i add the same mapper and test.
All seems to be good. 

I have seen that in fact i do not have all the users from ldap, it seems that something is locking during the process. 
I have done the same configuration in the ldap settings (except read mode).  
So seems to be related to something during the upgrade process but do not know what. 

Is there any risk to:
1) disable ldap connector
2) Remove imported
3) then enable it again and sync all again

?

**Comment by QuentinAxyus** [comment]
Hello, so i try:
1) disable ldap connector
2) Remove imported from the ldap connector (the goal is to have no user in keycloak database for this realm)
==> no more ldap account all was 
3) then enable it again and sync all again to get it back

==> All the account immediately come back with the AD Domain and not the email correct domain. 
No more error in sync, all the user are here. 

I don t understand what could bring such result.

**Comment by QuentinAxyus** [comment]
Hello, 
So i found the reason... 

And it was totally my fault... 
I have got 2 connector that modify the email value from ldap. 
One was from the mail value in ldap (so the good), other was from userPrincipalName from ldap.

So why was it working before? I don t know... But it's totally normal that it does not work.
Perhaps before, the order that keycloak apply the mapper was in over order so the correct mapper was the latest and i got the good value. 


I don t know if it could be a good idea to add a warning if two mapper map the same value?

**Comment by sguilhen** [comment]
Yeah, the way the mappers run guarantee no specific order, that could explain the behavior.

I think the idea to make validation more robust if then one mapper is defined for the same user attribute is a valid one. Would you mind raising an enhancement request for this?

**Comment by QuentinAxyus** [comment]
In fact it's seems that there is a consistent order that have changed, because when i rollback the server to 24.0.5, it always work again, and was working since there. 
So i think something had change somewhere that change the order.

But as i said, it's not a correct usage, and i have made en error, so except if the change of order could be problematic for something else, i think we could close this issue.
