### ISSUE TITLE
Changes in Keycloak CR, wiped out the whole database.

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#35204]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Trying to control the version in our keycloak, we added the image field in the CR. That caused the operator to wipe out ALL production data from the corresponding keycloak.

### Version

v26

### Regression

- [ ] The issue is a regression

### Expected behavior

Update the existing keycloak without wiping out the data.

### Actual behavior

ALL production data are gone. A brand new keycloak was deployed instead.

### How to Reproduce?

Create a keycloak, then add an image to the CR and see what happens.

**Comment by shawkins** [comment]
The operator does not directly deal with the database. Also the migration process is not destructive, you would see errors rather than a loss of data. More than likely you have a misconfiguration in your new cr, such as effectively using a different database that makes it appear the data is missing. Can you provide a confirmation that it's your existing database that was altered and / or logs showing a destructive process?

**Comment by droslean** [comment]
> The operator does not directly deal with the database. Also the migration process is not destructive, you would see errors rather than a loss of data. More than likely you have a misconfiguration in your new cr, such as effectively using a different database that makes it appear the data is missing. Can you provide a confirmation that it's your existing database that was altered and / or logs showing a destructive process?

Based on what you said, now I am 100% convinced that this is a BUG.

The data are being wiped out if we add an image with a different version than the current one. Keycloak updates the same instance but it wipes the data completely from the database. This can be replicated as well.

**Comment by jonkoops** [comment]
@droslean does this also happen with the latest patch release? It seems you are specifying an outdated version of Keycloak, so this might have already been fixed if it was a bug.

**Comment by droslean** [comment]
@jonkoops I just replicated it using the latest version. The wiping is happening when there is an older version already deployed and we update the CR to enforce an image with a newer version.

Also, is there any other way to enforce the keycloak version?

**Comment by shawkins** [comment]
> Based on what you said, now I am 100% convinced that this is a BUG.

This is not a behavior that has been observed - with or without the operator.

Please provide your complete cr and any logs that show the wiping of the database. Also are you doing anything unusual that might be triggering the destruction of your database via owner references for example?

> Also, is there any other way to enforce the keycloak version?

No, just via the image, but you don't have to specify that via the unsupported pod template. There is a proper field for that  - spec.image

**Comment by shawkins** [comment]
@droslean this is not reproducible for me. In fact using the 26.0.x operator and attempt to use the podTemplate to set the image updates the keycloak status to include:

```
message: |-
        warning: The name of the keycloak container cannot be modified
        warning: The image of the keycloak container cannot be modified using podTemplate
```

And nothing is done to the running keycloak.

**Comment by droslean** [comment]
@shawkins I am not sure why this issue was closed. The issue is real. 

Steps to reproduce:

- Deploy operator v22
- Create a Keycloak resource.
- Update the Keycloak resource to add:
```yaml
  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            image: quay.io/keycloak/keycloak:26.0.0
```


All data is now wiped out.

**Comment by shawkins** [comment]
> I am not sure why this issue was closed.

The v22 version of the operator is no longer supported by the community. Your first step would be to upgrade the operator - preferably from one major version to the next - this will also update the keycloak image.

Also attempting to override the image vi the podTemplate was never intended to be allowed - and is explicitly disallowed on newer versions of the operator.
