### ISSUE TITLE
Authenticated user password is visible in form data On inspect when login with any user

### ISSUE THREAD

**Issue by RuchiSingh18** [keycloak/keycloak#35220]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

![image](https://github.com/user-attachments/assets/68847b92-521d-42cb-83ed-5077c4de8d35)

### Version

22,24,26

### Regression

- [ ] The issue is a regression

### Expected behavior

Password should not visible in any form on browser inspect

### Actual behavior

![image](https://github.com/user-attachments/assets/5f2ebb3b-a47d-408d-9269-c513b305d920)

### How to Reproduce?

Create a user do federation or directly create user in keycloak . Go to client login to an application. and inspect in browser and click the authenticate one url inside payload formdata password is visible

### Anything else?

no

**Comment by douglaspalmer** [comment]
When you enable the Network developer tool in Chrome you tell chrome to record the data sent to the server and the data receiver from the server. The password you are seeing is the data Chrome sent for the login. I don't think there is anything that Keycloak can do to prevent this. If you don't use the dev tools then your browser won't record your form data.
