### ISSUE TITLE
Partial export resulting in a 500 error/being very slow

### ISSUE THREAD

**Issue by michaljelonek** [keycloak/keycloak#35233]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Hello! I'm sorry if this was already reported, but I wasn't able to find anything related!

Partial export when the realm has a lot of clients results in Transaction Reaper killing the transaction giving a 500 error. 

Transaction being killed can be avoided if the transaction timeout is modified - https://quarkus.io/guides/transaction#configuring-the-transaction-timeout. However, while this fixes the transaction being killed, the export itself is still taking a very long time - over 20 minutes - which is not very good either.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Partial export is relatively quick and not resulting in an error.

### Actual behavior

Partial export results in a 500 error, due to transaction being killed by Transaction Reaper. It's also very slow.

### How to Reproduce?

- have a lot of clients (we have just over 3700)
- partially export the realm, including clients, using the Admin UI or the API

### Anything else?

We use the partial export functionality for tools like keycloak-config-cli, which can manage Keycloak configuration.

**Comment by michaljelonek** [comment]
Unfortunately, after upgrading to 26.0.6, I'm experiencing the same issues.

**Comment by jonkoops** [comment]
Thanks for the confirmation. We'll try and get this triaged.

**Comment by vramik** [comment]
Thank you @michaljelonek for the report. I'm afraid this is known limitation[1] of partial export functionality. It would have to be changed completely how the partial export works. We do not have the capacity to start this initiative. Any improvements in this area are welcomed. Feel free to start [discussion](https://github.com/keycloak/keycloak/discussions).  

[1] https://www.keycloak.org/server/importExport
