### ISSUE TITLE
audience in OIDC access tokens show 'account' instead of proper client_id

### ISSUE THREAD

**Issue by Zysberg** [keycloak/keycloak#35262]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I have a public client `ui-client`, with Standard flow and direct access grants enabled.
I'm using OpenID-Connect as my protocol.
When I generate an access token via the `<keycloak_URL>/realms/test/token` endpoint, I get back an access_token such that
`access_token.payload.aud == acccount` when it should be `access_token.payload.aud == ui-client`

This is a security issue because having a generic audience within JWTs are considered untrustworthy.
In order to verify the tokens against JWKs, it's _**strongly**_ recommended to verify JWKS/JWT and to reject the JWT if issuers or audiences differ.

### Version

quay.io/keycloak/keycloak:latest

### Regression

- [ ] The issue is a regression

### Expected behavior

access_token payload audience (key:`aud`) should be your client_id.

### Actual behavior

access_token payload audience (key:`aud`) is 'account'

### How to Reproduce?

My docker-compose.yml file
```docker-compose.yml
services:  
  iam-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: AUTH_DB_USER
      POSTGRES_PASSWORD: AUTH_PASSWORD
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    build:
      context: .
      dockerfile: auth.Dockerfile
    depends_on:
      - iam-db
    ports:
      - 8081:8080
      - 8082:8443
```

My auth.Dockerfile
```Dockerfile
FROM quay.io/keycloak/keycloak:latest AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN rm -f conf/server.keystore
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/ # local https development
COPY ./localhost.crt ./localhost.key /opt/keycloak/
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://iam-db:5432/keycloak
ENV KC_DB_USERNAME=AUTH_DB_USER
ENV KC_DB_PASSWORD=AUTH_PASSWORD
ENV KC_BOOTSTRAP_ADMIN_USERNAME="sadmin"
ENV KC_BOOTSTRAP_ADMIN_PASSWORD="testestest"
ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/localhost.key
ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/localhost.crt
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--verbose"]
```
visit https://localhost:8082 and sign in with the bootstrap admin and password.
Create a realm - name: `loremipsum`
 Click 'Clients' on the left, then 'Create Client'
 - type: OpenID Connect
 - Client ID: `dolorsitamet`
 - Client Authentication OFF (public access)
 - Standard Flow and Direct Access Grants both ON
 - login settings: 
    + Home URL: https://localhost:5173
    + Valid Redirect URIs: ['https://localhost:5173/*']
    + valid post logout redirect URIs: ['https://localhost:5173/logout'}
    +Web origins: ['+']
- Realm Settings > Login > User Registration: ON

Spin up your client (my case, it's a react UI, using [OIDC-react](https://github.com/bjerkio/oidc-react))

Get redirected to log in with username/password or create account
console.log the access token and check on the JWT.io debugger to see aud = 'account'

**Comment by graziang** [comment]
@Zysberg, the audience `account` is added because the user by default has roles that allow access to the account console, and the `audience resolve` mapper in the `roles` client scope adds the audience to the token. You can configure default roles in **Realm Settings -> User Registration**, or you can disable `Full Scope Allowed` by setting it to **OFF** in the **Dedicated scope** of the client. More details can be found in the documentation:

- [Default Roles - Keycloak Documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#_default_roles)  
- [Full Scope Allowed - Keycloak Documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#_role_scope_mappings)

**Comment by rmartinc** [comment]
@Zysberg As @graziang commented the issuedFor or `azp` claim should be your client-id the `aud` claim is normally an array of other clients that accept tokens issued as a bearer only app (apps that only accepts tokens and do not initiate a login). By default keycloak adds in the `aud` all the apps that contain a role for this user in the scope (account for example) via the `audience-resolve` mapper in the `roles` client scope. You can modify this behavior via mappers/client scopes. Check also the [audience chapter](https://www.keycloak.org/docs/latest/server_admin/#audience-support) in the server admin documentation. So this is working as expected.

**Comment by Zysberg** [comment]
appreciate the feedback @rmartinc @graziang 

Most likely the case, I'm having a hard time understanding and it'll take some time for me to understand the specific doc section you sent me. Will provide a response with better questioning.
