### ISSUE TITLE
Your login attempt timed out

### ISSUE THREAD

**Issue by Mizar01** [keycloak/keycloak#35276]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When I do some otp configuration or reset password, my actual password is requested before proceeding.
But after re-inserting the password I get the error:
"Your login attempt timed out.  Login will start from the beginning."

This is confusing users, they did nothing fancy, and they have to start over.

What can be done?

### Version

26.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

After re-typing the password (because too much idle time has passed) I should be brought right to the option I chose (otp configuration or password reset).

### Actual behavior

After re-typing the password (because too much idle time has passed) I get the error "Your login attempt timed out.  Login will start from the beginning."

### How to Reproduce?

Login into keycloak account and go into "Signing in" page.
Let pass 5 minutes and try to configure OTP or password.
you are then forced to digit the password before proceeding ("Pleae re-authenticate")
After submitting the password I get an error:
"Your login attempt timed out.  Login will start from the beginning."

**Comment by rmartinc** [comment]
@Mizar01 I canot reproduce in a plain 26.0.6 version. I wait the 5 minutes or more, the re-authentication is shown, I put the password and then the OTP confiigration is shown and I can configure the token. Can you please test in a fresh installation of keycloak? Do you have any other missing step in your configuration to reproduce the issue?

**Comment by Mizar01** [comment]
Sorry, I have to reopen this. 

I thoroughly proceeded to exclude many settings we did in months, and I've finally been able to reproduce this.

The steps to add to reproduce the bug is:
 - Add a session count limiter to the browser flow (duplicated from the original).

So, I can rewrite the entire steps:

Go to the admin console as administrator.
Click on Authentication settings
Duplicate the browser flow and activate the duplicated version
Add a session count limiter to the duplicated browser flow  (as last step at the same level of "Username And Password form")
Set "Maximum concurrent sessions for each user within this realm" to 1
Set "Behavior when user session limit is exceeded" to "Terminate oldest session"
Set the step as "required"
Login into keycloak account and go into "Signing in" page.
Let pass 5 minutes and try to configure OTP or password.
you are then forced to digit the password before proceeding ("Pleae re-authenticate")
After submitting the password I get an error:
"Your login attempt timed out. Login will start from the beginning."

Notice that maybe the first time you do that is not happening, if you already had more that one session with the test user. But from a clean one single session, the problem occurs every time.

**Comment by rmartinc** [comment]
@Mizar01 OK, now I can reproduce it. But it's working exactly as expected :smile:. The problem here is that the session count limit is executed also for the re-authentication and it fails because the other session is there. So the limit is reached, the initial session is terminated and it generates all the mess. As a workaround you have to increase the sessions to 2.

Probably the fix would be not executing this step if there is a KC_ACTION involved, not checking session numbers in that case. Or at least provide a config option to the authenticator to allow that. I'm taking this and I'll try to provide a fix.

**Comment by borelsaffo** [comment]
Your login attempt timed out. Login will start from the beginning.
got the same issue still many days now

**Comment by ahus1** [comment]
> got the same issue still many days now

Please create a new bug issue and provide the additional information asked for in the template. This issue is closed, and you won't receive answers here without those details.
