### ISSUE TITLE
The operator uses the `nightly` image for all keycloaks. There no supported way to control the version

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#35287]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

I am using `quay.io/keycloak/keycloak-operator:26.0.0`. When I create a Keycloak using the CR, the operator creates a keycloak as it should but it uses the `nightly` image tag which is experimental. 

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I would at least expect the operator to use the same version to spawn the keycloaks

### Actual behavior

Instead it uses the nightly image,

### How to Reproduce?

Just spawn the operator and create a new Keycloak CR.

**Comment by shawkins** [comment]
@droslean I was not able to reproduce this. A fresh install of the kc 26.0.6 operator not via olm creates keycloaks with the 26.0.6 image. Same with 26.0.0. If you look in the operator yaml you should see RELATED_IMAGE_KEYCLOAK controlling the keycloak version.

OLM bundles look good as well.

How did you install the operator? Can you provide the yaml for the operator deployment as well as the generated keycloak statefulset?

**Comment by droslean** [comment]
> @droslean I was not able to reproduce this. A fresh install of the kc 26.0.6 operator not via olm creates keycloaks with the 26.0.6 image. Same with 26.0.0. If you look in the operator yaml you should see RELATED_IMAGE_KEYCLOAK controlling the keycloak version.
> 
> OLM bundles look good as well.
> 
> How did you install the operator? Can you provide the yaml for the operator deployment as well as the generated keycloak statefulset?

Hello @shawkins . You are testing the wrong version. I had this problem on `26.0.0`. Please check the description of this issue for more details. 

I upgraded to `26.0.6` and it now uses the correct image to deploy the keycloak.

**Comment by shawkins** [comment]
> You are testing the wrong version. I had this problem on 26.0.0. Please check the description of this issue for more details.

@droslean I tried with both. In any event since this seems to be working for you now, I'll mark it as resolved.
