### ISSUE TITLE
Upgrade 26.0.5 -> 26.0.6 completely breaks admin events in the admin UI

### ISSUE THREAD

**Issue by boomer41** [keycloak/keycloak#35288]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When upgrading from KC 26.0.5 to 26.0.6 with a PostgreSQL database,
the new 'details_json' column was introduced.
However, when we have some admin events already in there, the column stays NULL.

When already having admin events pre upgrade, the UI completely breaks when opening the event view,
and the REST call to `/admin/realms/master/admin-events?first=0&max=51` returns an error 404 with the message `{"error":"unknown_error","error_description":"Cannot parse the JSON"}`.

Manually executing `UPDATE admin_event_entity SET details_json='{}' WHERE details_json IS NULL;` against the database fixes the view, but the admin events are almost all empty.

### Version

26.0.6

### Regression

- [x] The issue is a regression

### Expected behavior

A **bugfix** version upgrade should not break the database.

### Actual behavior

A **bugfix** version upgrade broke the database.

### How to Reproduce?

1. Install KC 26.0.5 with PostgreSQL as the database.
2. Enable admin events
3. Generate some admin events (REALM UPDATE and CLIENT CREATE) in our testsystem)
4. Upgrade to KC 26.0.6
5. Try to access the event view, the UI only shows a red error message.

**Comment by stecullum** [comment]
As a temporary workaround.. 

[ clearing admin events ] in realm settings brings back but you lose them all!!

<img width="571" alt="image" src="https://github.com/user-attachments/assets/7293bedb-faed-409a-ac19-372e82a15548">

**Comment by boomer41** [comment]
> As a temporary workaround.. 

The correct workaround should have been to simply downgrade back to 26.0.5, as a Bugfix update should be backwards compatible. But as a Schema change was introduced in a bugfix update, this doesn't work....

**Comment by pedroigor** [comment]
Yeah, not good ... Even though updating the schema it was not supposed to break the upgrade/compatibility. I'm sending a fix.

**Comment by artragis** [comment]
Hello,
Thank you for this ticket. Would just want to tell that the bug was not just impacting the admin-ui but also the rest api.

**Comment by ahus1** [comment]
@artragis - thank you for sharing this, and sorry that this broke the REST API for you. By now, Keycloak Keycloak 26.0.7 is out, which should resolve this.

**Comment by artragis** [comment]
Hello,
I can confirm keycloak 26.0.7 solves the issue. Thank you for your work.
