### ISSUE TITLE
Essential claim with microsoft social login

### ISSUE THREAD

**Issue by malins** [keycloak/keycloak#35293]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

Hello,

I'm trying to use "essential claim" feature with Microsoft Social Login, but it simply doesn't work.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

If "verify essential claims" is on, "Essential claim" is set to "upn" and "Essential claim value" is set to ".+@somedomain.com$", then only users with a upc claim ending in @somedomain.com should be allowd.

### Actual behavior

At the moment every user is allowed to login, the check is not working at all.,

### How to Reproduce?

See expected bevhaviour.

**Comment by pedroigor** [comment]
This capability is available to any OIDC-compliant broker and should also work for the Microsoft broker. I would suggest you to look at the ID token returned by the IdP and check how the claim is defined there.

The same steps you described work for me but using a different claim. For instance, `ver` claim returned in the ID token from `https://login.microsoftonline.com/common/oauth2/v2.0/token`.
