### ISSUE TITLE
Updated tested PostgreSQL version to 17

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#35331]
### Description

Updated tested PostgreSQL version to 17

**Comment by ahus1** [comment]
AWS currently doesn't support PostgreSQL 17. The default for new Aurora PostgreSQL instances is still 16.1 although 16.4 is available as well. Therefore voting to keep Aurora PostgreSQL at 16.1 

![image](https://github.com/user-attachments/assets/06240367-3990-45ee-bb85-fe7f80c11d03)
