### ISSUE TITLE
[Keycloak CI] - Quarkus UT (windows-latest) - Keycloak Quarkus Server Deployment

### ISSUE THREAD

**Issue by ikhomyn** [keycloak/keycloak#35405]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

> Error:  Errors: 
> Error:    KeycloakMetricsConfigurationTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> Error:    KeycloakNegativeHealthCheckTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> Error:    KeycloakPathConfigurationTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> Error:    KeycloakReadyHealthCheckTest � Runtime java.lang.RuntimeException: Failed to start quarkus
> [INFO] 
> Error:  Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
> 

`Caused by: java.lang.IllegalStateException: fv-az653-80-49239: failed to find an available port in ports [57800, 57801, 57802, 57803]`

https://github.com/keycloak/keycloak/actions/runs/12049067476/job/33595264630

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by shawkins** [comment]
@Pepo48 this looks similar to #34844 - we mused there about simply making all by the clustering tests use local cache instead.

**Comment by Pepo48** [comment]
@shawkins thanks for the pointer. I couldn't reproduce it locally though. Would you annotate all of the mentioned above with `@WithEnvVars({"KC_CACHE", "local"})` or should we just go with *ConfigurationTest first and give it couple runs in CI?

**Comment by shawkins** [comment]
> @shawkins thanks for the pointer. I couldn't reproduce it locally though. Would you annotate all of the mentioned above with `@WithEnvVars({"KC_CACHE", "local"})` or should we just go with *ConfigurationTest first and give it couple runs in CI?

I'd just start with annotating all of them.
