### ISSUE TITLE
Keycloak forgetting OIDC ui_locales parameter set during logout, after logout

### ISSUE THREAD

**Issue by bmbigbang** [keycloak/keycloak#35432]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Similar issue to https://github.com/keycloak/keycloak/issues/10981
We have keycloak version 26.0.6 setup and use a DotNet Core (v8) server to authenticate with it. Here is an example request where we include the `ui_locales` in the ProtocolMessage that is sent to trigger the logout (I have removed some of the cookie/token details for brevity):
```
:authority: localhost:8092
:method: GET
:path: /omsauth/realms/oms/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A8092%2Fdlr%2Fsignout-callback-oidc&id_token_hint=...&ui_locales=ar&state=CfDJ8PcZl6VFKbpGnWxEeN8d3KYSt7BCxvXt-vlWOUw7bL2rNZ3WueFWRYsk2txKdmZobA37iN1JlhlLHVtBLTvlIr07M395WD5B84WGrp_2k4hN6gvCXKeiCQWsPcnoK5sKrJTk7_b1GHOlqS6soRQzIuOeJl3GZUlSwM888vY38viu&x-client-SKU=ID_NET8_0&x-client-ver=7.1.2.0
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-encoding: gzip, deflate, br, zstd
accept-language: en
cache-control: no-cache
cookie: AUTH_SESSION_ID=...; KEYCLOAK_LOCALE=en; KEYCLOAK_SESSION=...; KC_RESTART=......; KEYCLOAK_IDENTITY=...
pragma: no-cache
priority: u=0, i
referer: https://localhost:8092/dlr/LanguageChange
sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
```

note the KEYCLOAKE_LOCALE is set to `en` because that's what the user chooses to login with. Once logged in, within the application the user changes their language, which doesn't change this KEYCLOAK_LOCALE value, but changes another session variable we use in our app to track locale changes. On logout then we include the `ui_locales=ar` and I expected that, that would cause the KEYCLOAK_LOCALE to update accordingly via keycloak when logging out. Is this a bug or a intended behaviour?

This parameter is defined as per the OIDC specification's RP-Initiated Logout:
https://openid.net/specs/openid-connect-rpinitiated-1_0.html

There is some mention of it in the docs also:
https://www.keycloak.org/docs-api/22.0.5/javadocs/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.html
Although perhaps it operates only for the logout confirmation page?

The consequence of this is that when the same user is redirected to the login page, after logging out successfully, they still see the english version of the page so it is as though keycloak has forgotten the ui_locales used, and the KEYCLOAK_LOCALE stored for this client is now out of sync with the consumer app.

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

KEYCLOAK_LOCALE or the locale for the client to update when ui_locales is provided during OIDC logout

### Actual behavior

KEYCLOAK_LOCALE stays the same after logout with a different ui_locales is sent

### How to Reproduce?

Setup keycloak with at least two Localisations set and Internationalisation enabled. Setup a simple OIDC application to use keycloak as the authentication. Sign in with one of the languages selected. Now trigger a logout using an id token and with a different language by requesting:
`...realms/oms/protocol/openid-connect/logout?post_logout_redirect_uri=...&id_token_hint=...&ui_locales=ar`
Logout confirm page is not displayed in this situation so you will likely be redirected to the main login page on keycloak which should be in english again.

**Comment by rmartinc** [comment]
Sorry but your description is a bit convoluted, so maybe I'm missing something. The idea is the `ui_locales` is just a way to specify the desired locale to be shown at login/logout. So in the logout the `ui_locales` updates  the client selected locale [here](https://github.com/keycloak/keycloak/blob/26.0.7/services/src/main/java/org/keycloak/protocol/oidc/endpoints/LogoutEndpoint.java#L237). But then it's the DefaultLocaleSelectorProvider the one that selects the locale for the user with it's own precedence [here](https://github.com/keycloak/keycloak/blob/26.0.7/services/src/main/java/org/keycloak/locale/DefaultLocaleSelectorProvider.java#L71) and it's documented in the [server admin](https://www.keycloak.org/docs/26.0.7/server_admin/#_user_locale_selection). First it's the user locale (if selected in the profile) and later the client locale. So if the user has selected a locale previously and it's saved in its profile it takes precedence over the `ui_locales` passed over the logout. And he ui_locales never sets the locale of the user in the profile (only the locale combo-box does that). The locale provider can be overridden as documented in the [dev guide](https://www.keycloak.org/docs/latest/server_development/#_locale_selector).

**Comment by bmbigbang** [comment]
>First it's the user locale (if selected in the profile) and later the client locale. So if the user has selected a locale previously and it's saved in its profile it takes precedence over the ui_locales passed over the logout.

Thanks for your clarification. So this is working as per the OIDC spec is it? 
Does the client locale take precedence over the `ui_locales` url parameter too?

**Comment by rmartinc** [comment]
> Thanks for your clarification. So this is working as per the OIDC spec is it?

The spec just mentions that the `ui_locales` is the parameter for End-User's preferred languages for the user interface. It does not enforce to use them in a specific way (it says that the minimum level of support required for these parameters is simply to have their use not result in errors). Keycloak simply uses them but not as the first option.

 > Does the client locale take precedence over the ui_locales url parameter too?

The client locale is the `ui_locales` parameter, check the [sever admin](https://www.keycloak.org/docs/26.0.7/server_admin/#_user_locale_selection) for the order.
