### ISSUE TITLE
Realm is missing from the UI

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#35460]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I have around 20 realms in my `26.0.6` Keycloak. Unfortunatelly I am not able to list few of them using the UI because they are missing. The only way to access them is to change the URL manually to point to the desired realm.

### Version

26.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

I would except my realm to exist in the UI

### Actual behavior

It doesn't

### How to Reproduce?

Deploy the 26.0.6 keycloak. Create more than 20 realms and check the UI. Few of them are missing.

**Comment by jonkoops** [comment]
This is likely the same issue as #35296

**Comment by ssilvert** [comment]
@droslean Can you try this on the nightly build?
https://www.keycloak.org/nightly/
