### ISSUE TITLE
Can't import keycloak-js in a react typescript app

### ISSUE THREAD

**Issue by branflake2267** [keycloak/keycloak#35466]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

I can't use `import Keycloak from "keycloak-js";` without errors in my react typescript app. Works in 25.0.6.
 
![Screenshot 2024-11-29 at 9 31 36 AM](https://github.com/user-attachments/assets/0022770a-3c0b-4220-9c09-345af4bfe8d0)

### Version

26.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

Import Keycloak from "keycloak-js" with out problems. 

### Actual behavior

Build and compiler errors. 

### How to Reproduce?

1. Run `npx create-react-app my-app --template typescript`
2. Create a file for source `./src/keycloak.ts`
3. Add to `keycloak.ts`
```
import Keycloak from 'keycloak-js'; // Note this won't work in the latest version

const keycloak = new Keycloak({
    url: "http://keycloak-server",
    realm: "my-realm",
    clientId: "my-app"
});
```

**Comment by branflake2267** [comment]
Adding `"main": "./lib/keycloak.js"` in `package.json` appears to resolve the issue. 
![Screenshot 2024-11-29 at 10 06 27 AM](https://github.com/user-attachments/assets/54a9911a-bd0c-4209-a801-1512b7ebbd8d)

**Comment by branflake2267** [comment]
Install npm 10.9.1 to fix this issue. One way to install npm 10.9.1. `npm install -g npm@latest`

**Comment by jonkoops** [comment]
Duplicate of #34827
