### ISSUE TITLE
`QuarkusPropertiesDistTest` fails on Windows

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#35496]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

The `QuarkusPropertiesDistTest` is testing some areas that can easily break on Windows, there's even a [specific test for Windows](https://github.com/keycloak/keycloak/blob/4a13875fb25cfb0cc85aab546daedd273ca48a32/quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/QuarkusPropertiesDistTest.java#L176-L185). However, the tests [seem to fail on Windows](https://github.com/vmuzikar/keycloak/actions/runs/12117249404/job/33779714328). We don't even run it in GHA.

We should:
* Fix the test on Windows.
* Add the `@Tag(DistributionTest.WIN)` tag to the test class so it's ran in GHA.

### Version

main

### Regression

- [ ] The issue is a regression

### Expected behavior

`QuarkusPropertiesDistTest` works on Windows

### Actual behavior

`QuarkusPropertiesDistTest` doesn't work on Windows

### How to Reproduce?

Run `QuarkusPropertiesDistTest` on Windows

**Comment by vmuzikar** [comment]
@Pepo48 Could you please look into this when you get a chance?

**Comment by Pepo48** [comment]
@vmuzikar just the update, once https://github.com/keycloak/keycloak/pull/34462 gets merged, it will fix one of the tests. For the remaining two I will prepare their Windows counterparts.
