### ISSUE TITLE
Not waiting for admin console and automatically redirected.

### ISSUE THREAD

**Issue by Sivaramayya** [keycloak/keycloak#35525]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I have one existing instance of keycloak V23 in physical machine and  configured with Oracle DB.
We have build new instance of keycloak V26 in openshift and trying to use the same DB. 

When I am accessing the url, It is not asking or waiting for username and password for login into admin console.
It is directly saying the below message in the browser.

We are sorry...
Invalid username or password.
« Back to Application

### Version

V26

### Regression

- [ ] The issue is a regression

### Expected behavior

It is have wait for taking the username and password

### Actual behavior

When I am accessing the url, It is not asking or waiting for username and password for login into admin console.
It is directly saying the below message in the browser.

We are sorry...
Invalid username or password.
« Back to Application

### How to Reproduce?

I have one existing instance of keycloak V23 in physical machine and  configured with Oracle DB.
We have build new instance of keycloak V26 in openshift and trying to use the same DB.

**Comment by mposolda** [comment]
@Sivaramayya This is unsupported setup. It is not supported to have same DB running against 2 versions of Keycloak server of different versions.

What is supported is the workflow like this:
- Have Keycloak V23 running against your DB
- Stop Keycloak V23
- Run Keycloak V26 against same DB. This will migrate DB to the newest version.
- Now DB is migrated to KEycloak V26 and it is not possible to run the same DB against KEycloak V23 anymore (there might be DB schema changes etc, so not possible anymore to access DB migrated to 26 with Keycloak 23)

The setup you're using is completely unpredictable behaviour and that is the cause of the error.

It is also not supported to have 2 keycloak servers of same version running against same DB, but not on cluster. In other words, when you have KEycloak V26 on openshift and Keycloak V26 somewhere else running against same DB, there would be issues as well. Having multiple Keycloak servers running against same DB can work just when servers are in cluster or cross-dc .

See the docs for more details.

**Comment by Sivaramayya** [comment]
Thank you for the reply
