### ISSUE TITLE
Requesting two offline_access sessions with different scopes doesn't work

### ISSUE THREAD

**Issue by Jamstah** [keycloak/keycloak#35521]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

If I request two offline session with different scopes, the scopes in the access_tokens obtained from the refresh_tokens no longer match up.

For example:
- Request scopes `openid offline_access`
  - Use code to get refresh token A, refresh token scopes include `openid` and `offline_access`
- Request scopes `openid offline_access address`:
  - Use code to get refresh token B, refresh token scopes include `openid`, `offline_access`, `address`
- Use refresh token A to get an access_token:
  - access token scopes include `openid` and `offline access`
- Use refresh token B to get an access_token:
  - access token scopes include `openid` and  `offline_access`, no `address`

### Version

quay.io/keycloak/keycloak:latest (26.0.6)

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect using refresh token A to get an access token without the `address` scope, and when using refresh token B to get an access token with the `address` scope.

### Actual behavior

I get the same scopes from each token, without `address`, which seems to just match the first minted token.

### How to Reproduce?

As described

### Anything else?

My guess is that this is related to maintaining only one session per type (potentially one online and one offline session). Do we need to have one session per set of scopes? Alternatively, could we use the scopes in the refresh token to inform the scopes of the access token, and store the superset in the one session?

As background, I'm looking at how to use offline sessions to allow users to create API keys in my app. The app would store the refresh token against an API key, and use it to get an access token when api calls are made. By using different scopes, it can provide the ability to limit the permissions per API key.

**Comment by sschu** [comment]
@mposolda Weren't there some changes recently that went into the direction of allowing the described scenario?

**Comment by Jamstah** [comment]
Thanks for the verification, it was PEBCAK, apologies for the invalid issue.

In my tests, I had the `scope` parameter set up in my API client to `openid offline_access` when using the refresh tokens, so it was correctly descoping the access_token down from the refresh_token because I told it to.

I think I missed it because it was successfully removing the offline_access scope if I hadn't requested when I got the code, and was adding the default scopes for the client, so the scopes in the tokens looked like they were fully specified and changing based on the token.
