### ISSUE TITLE
Realm name cannot be changed

### ISSUE THREAD

**Issue by k-tamura** [keycloak/keycloak#35547]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Realm name cannot be changed since version 26.0.0.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Realm name is changed.

### Actual behavior

403 error occurs:

Realm could not be updated: HTTP 403 Forbidden
![Screenshot from 2024-12-03 18-06-30](https://github.com/user-attachments/assets/1a4a78bc-9e60-490b-b2a7-529bef0b9c55)

### How to Reproduce?

1. Setup Keycloak 26.0.0
2. Login as admin
3. Createa a realm
4. Change the realm name
-> 403 error occurs.

### Anything else?

I will investigate further, but I suspect the following commit may be the cause (regression):

https://github.com/keycloak/keycloak/commit/a14548a7a27685b35e3dd974a06dcf078aec3970#diff-44a8ec3ef78940b6ba9b73f2a66f5bbb3df47a9eeb5c8b4f642b4bab4cd4f76f

**Comment by k-tamura** [comment]
This issue is still not fixed in 26.0.7.

**Comment by ssilvert** [comment]
It is up to the core teams to decide if we allow realm renames going forward.  It's not a UI issue.

FYI: @pedroigor @mposolda
