### ISSUE TITLE
Keycloak 26: KC_HOSTNAME should not be mandatory if KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true and frontend urls are defined for realms

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#35558]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I really don't understand why `KC_HOSTNAME ` should be mandatory if `KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true`.

How can one define a single hostname, if realms have different frontend urls ?
Should a 'fake' hostname be provided for `KC_HOSTNAME` ?

The documentation says : 

> If hostname-backchannel-dynamic is set to true, hostname must be set to a URL (not just hostname). Otherwise **Keycloak would not know what is the correct frontend URL** (incl. port etc.) when being access via the dynamically resolved bachchannel.

But Keycloak can know the correct frontend URL if it is defined in the realm settings. Right ?!
Having to define a mandatory hostname if completely pointless in this case and counterintuitive.

Shouldn't this be checked at runtime (with a message like : 'Your realm does not have a frontend url defined, therefore you should define a default one through the 'hostname' parameter) if trying to ask for the urls (by calling the `.well-known/openid-configuration` endpoint) of a realm that has not frontend url, instead of checking it at server startup ?

Note : Maybe the parameter `hostname` should be renamed to something like `default-hostname`, because the documentation does not make it very clear that it will be overriden by the frontend url of the realms.

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

'hostname' parameter should not be mandatory if realms have frontend urls

### Actual behavior

'hostname' parameter is mandatory and pointeless if realms have frontend urls

### How to Reproduce?

- Set hostname-backchannel-dynamic=true
- Have a frontend url defined for each realm
- Do not define a 'hostname' -> Keycloak complains at startup that a hostname if not defined.

**Comment by shawkins** [comment]
> I really don't understand why KC_HOSTNAME  should be mandatory if KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true.

We have several paths that are not rooted at a realm which require using the hostname - this includes /lb-check, /resources, /welcome-content, etc. 

> Should a 'fake' hostname be provided for KC_HOSTNAME ?

I think you at least still need to have /resources accessible via a valid url, so a fake one won't work.

**Comment by shawkins** [comment]
Removed the regression setting. I think this can be closed, but will wait for additional feedback from @omasseau
