### ISSUE TITLE
Webinterface not accessable via HTTP

### ISSUE THREAD

**Issue by christianmerges** [keycloak/keycloak#35614]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When I follow the guide here: https://www.keycloak.org/getting-started/getting-started-docker

And start the container as suggested: docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.0.7 start-dev

When i then try to open the webinterface on http://hostname:8080 I get the error: 

We are sorry...
HTTPS required

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

I should be able to login via HTTP and setup HTTPS later via traefik reverse proxy.

### Actual behavior

I cannot login via HTTP

### How to Reproduce?

Follow the guide on: https://www.keycloak.org/getting-started/getting-started-docker

**Comment by shawkins** [comment]
Could not reproduce. Are you sure that you specificed start-dev, not start?

**Comment by christianmerges** [comment]
My docker compose file:
`services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /mnt/docker/remotework/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.http.middlewares.keycloak.forwardauth.address: http://keycloak:8080/realms/master/protocol/openid-connect/token
      traefik.http.middlewares.keycloak.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.keycloak.forwardauth.authResponseHeaders: Authorization
      traefik.enable: true


  whoami1:
    image: traefik/whoami
    container_name: whoami1
    labels:
      traefik.enable: true
      traefik.http.routers.whoami1.rule: Host(`whoami1.example.com`)
      traefik.http.routers.whoami1.entrypoints: websecure
      traefik.http.routers.whoami1.tls: true
      traefik.http.routers.whoami1.tls.certresolver: letsencrypt
      traefik.http.routers.whoami1.middlewares: keycloak
      traefik.http.services.whoami1.loadbalancer.server.port: 80
 
  whoami2:
    image: traefik/whoami
    container_name: whoami2
    labels:
      traefik.enable: true
      traefik.http.routers.whoami2.rule: Host(`whoami2.example.com`)
      traefik.http.routers.whoami2.entrypoints: websecure
      traefik.http.routers.whoami2.tls: true
      traefik.http.routers.whoami2.tls.certresolver: letsencrypt
      traefik.http.routers.whoami2.middlewares: keycloak
      traefik.http.services.whoami2.loadbalancer.server.port: 80


  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      KC_DB: dev-file
      #KC_HOSTNAME: auth.example.com
      KC_LOG: console
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      PROXY_ADDRESS_FORWARDING: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    command:
      - start-dev
    labels:
      traefik.enable: true
      traefik.http.routers.keycloak.rule: Host(`auth.example.com`)
      traefik.http.services.keycloak.loadbalancer.server.port: 8080
      traefik.http.routers.keycloak.entrypoints: websecure
      traefik.http.routers.keycloak.tls: true
      traefik.http.routers.keycloak.tls.certresolver: letsencrypt
    volumes:
      - /mnt/docker/remotework/keycloak/data:/opt/keycloak/data
    tmpfs:
      - /opt/keycloak/data/tmp:mode=777,size=8G #,uid=1000,gid=1000
    ports:
      - 8088:8080`
      
When I try to open https://auth.example.com/admin/master/console/ in Google Chrome it shows "Loading the Administration Console" after around 10 seconds: "somethingWentWrong".
      
When I try to open http://dockerhost:8088 it redirects to "http://dockerhost:8088/admin/master/console/" and then it redirects to: "http://dockerhost:8088/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Fnode4%3A8088%2Fadmin%2Fmaster%2Fconsole%2F&state=d4e086d7-6272-471a-a677-7805e74aeae6&response_mode=query&response_type=code&scope=openid&nonce=59431f2a-b864-417f-898e-5e3d3ace42dd&prompt=none&code_challenge=xvN1rhMHkW_660HVsNiJVMafU3tvwm4kvdhDUg3Xdew&code_challenge_method=S256" and showing the following error: We are sorry...
HTTPS required"

**Comment by shawkins** [comment]
Just a few clarifications:

> KC_PROXY: edge
> KC_HOSTNAME_STRICT_HTTPS: false
> PROXY_ADDRESS_FORWARDING: true
 
These KC_ properties are no longer used by Keycloak. PROXY_ADDRESS_FORWARDING is not used by the keycloak image.

> KC_DB: dev-file
> KC_HOSTNAME_STRICT: false
> KC_HTTP_ENABLED: true

These are implied by start-dev. There's nothing wrong with making them explicit - just want to give an idea of what start-dev is simplifying for you.

You should try to start the server, without docker-compose, to confirm that it works as expected. That should clarify that something is amiss above keycloak. 

If traefik is acting as a proxy, to do something like switching the port above keycloak (from 8080 to 8088) would require setting the hostname url to include the port - but for cors checking may also require setting the proxy-headers.

**Comment by christianmerges** [comment]
Thank you for your insights. Traefik is a reverse proxy. When I access the local http port, it is bypassing traefik. 

How to start the server without docker compose?
How can I check, if the proxy headers are forwarded correctly from traefik to keycloak? This is mainly a requirement for production via https, because atm I cannot even connect directly via http to the keycloak container.

**Comment by shawkins** [comment]
> How to start the server without docker compose?

Just as you showed initially with just docker, or even from the distribution zip.

> How can I check, if the proxy headers are forwarded correctly from traefik to keycloak?

hostname-debug https://www.keycloak.org/server/hostname will show you the headers that the server is receiving. You can also just check the trafik docs. Once you know what headers are being set, then use proxy-headers=forwarded or xforwarded.

**Comment by christianmerges** [comment]
the environment variable PROXY_ADDRESS_FORWARDING is read by traefik and makes it adding the x-forwarded heade to the forwarded request to keycloak.

The hosname debug is actually really interesting, because it shows that keycloak is trying to access the backend with the external hostname but the protocoll http instead of https.



```
<html>
<body>
<!--StartFragment-->
URL | Value
-- | --
Request | https://auth.example.com/realms/master/hostname-debug
Frontend | http://auth.example.com/ [FAILED]
Backend | http://auth.example.com/ [FAILED]
Admin | http://auth.example.com/ [FAILED]

Server mode | dev [start-dev]
Realm | master
Hostname SPI implementation | V2

hostname-backchannel-dynamic | false
hostname-strict | false
http-enabled | true
http-relative-path | /
http-port | 8080
https-port | 8443

Host | auth.example.com
X-Forwarded-For | <mypublicip>
X-Forwarded-Host | auth.example.com
X-Forwarded-Port | 443
X-Forwarded-Proto | https

<!--EndFragment-->
</body>
</html>
```

**Comment by shawkins** [comment]
> The hosname debug is actually really interesting, because it shows that keycloak is trying to access the backend with the external hostname but the protocoll http instead of https.

With hostname-strict=false and no hostname set, it's gleaning the host from the host header.

Now try with proxy-headers=xforwared - that will convey that the intended protocol is https, not the default of http. It's the default because you are accessing via an edge / terminating proxy over the http port.

**Comment by christianmerges** [comment]
how do you want me to set "proxy-headers=xforwared"? as environment variable or as command?

**Comment by shawkins** [comment]
Just as you would any other keycloak configuration value, so as an environment variable it is KC_PROXY_HEADERS

**Comment by christianmerges** [comment]
After setting the environment variable to `KC_PROXY_HEADERS: xforwarded` I was able to reach the console on https://auth.example.com and I could login with the bootstrap credentials.
