### ISSUE TITLE
Updating identity provider alias fails with timeout error if there are too many users

### ISSUE THREAD

**Issue by test4423** [keycloak/keycloak#35647]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

In IdentityProviderResource.updateIdpFromRep method, stream with all users is passed to updateUsersAfterProviderAliasChange method. Because of this, if there are too many users, timeout error is thrown and the alias can not be changed.
https://github.com/keycloak/keycloak/blob/0f1bdc4e975c4810102d6ad125b3ed2369c90f0b/services/src/main/java/org/keycloak/services/resources/admin/IdentityProviderResource.java#L209C49-L209C177

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Alias is changed, success message shown

### Actual behavior

Page freezes for a while, error message shown, alias not changed

### How to Reproduce?

Pre-condition: 2M users in realm
1. Open identity provider, change alias and click save

**Comment by vramik** [comment]
@test4423 thank you for reporting the issue. 

I think this behavior is more or less expected. As there is a need to update 2M+ entries in the DB.

On the other hand I wonder how did the isssue was encountered as for me the alias field is not editable, but read-only. Could you please provide steps how did you achieve alias change? 

~missing-info
