### ISSUE TITLE
Unable to create realm

### ISSUE THREAD

**Issue by larsassink** [keycloak/keycloak#35694]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I am unable to create a new realm in Keycloak 26.0.6

### Version

26.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect to create a new realm according to the documentation. 

### Actual behavior

Unable to create a new realm, the button is missing. Also no other admin accounts on the instance except mine.

### How to Reproduce?

Hosted on a proxmox LXC using this template: https://community-scripts.github.io/ProxmoxVE/scripts?id=keycloak

**Comment by sschu** [comment]
You need to provide steps to reproduce your issue using a supported installation way i.e. using the Keycloak distribution or the docker image. In both ways, creating a realm works for me. If there is something wrong in the way your linked script sets up Keycloak, we cannot fix that script. So please provide steps for us to reproduce your issue locally.
