### ISSUE TITLE
token exchange response expires_in inconsistent behavior

### ISSUE THREAD

**Issue by codeart1st** [keycloak/keycloak#35704]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

https://github.com/keycloak/keycloak/blob/d3b759b56ff564abed24b82dbe40ccbd5ff91076/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L195

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-token-exchange-16#section-2.2.1

The Token Exchange Response for OIDC Identity Provider sometimes includes the lifetime duration in seconds and sometimes an unix timestamp. Don't know why.

**Request:**

```
curl --location 'https://dev.localhost.data-experts.net/auth/realms/profil/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'requested_issuer=OIDC_IDP' \
--data-urlencode 'subject_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJycjBjN0xGOS1UR2g4V19pZHBUMWFfNl8tOXI0QWd2MTVNalNnMThJaEZnIn0.eyJl....' \
--data-urlencode 'client_id=fancy-client-name' \
--data-urlencode 'client_secret=0cc14ebd-ee05-4af6-88ca-78794adf978f' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
--data-urlencode 'requested_token_type=urn:ietf:params:oauth:token-type:access_token'
```

**Response:**

```
{
  "access_token": "N4IIorDl5p4AeQURzciu-hFez7zs-9snp~+y+K9L",
  "expires_in": 1733494922,
  "refresh_expires_in": 0,
  "not-before-policy": 0,
  "issued_token_type": "urn:ietf:params:oauth:token-type:access_token",
  "account-link-url": "https://foobar.net/auth/realms/profil/broker/OIDC_IDP/link?nonce=b1cf6bf4-beb3-4751-94fc-13135b3fc9a5&hash=jcn9LWknCd7oxwtWIXc-LNj4ctd3Z9lkUVKyyKHvBPQ&client_id=fancy-client-name"
}
```

or sometimes

```
{
  "access_token": "N4IIorDl5p4AeQURzciu-hFez7zs-9snp~+y+K9L",
  "expires_in": 1199,
  "refresh_expires_in": 0,
  "not-before-policy": 0,
  "issued_token_type": "urn:ietf:params:oauth:token-type:access_token",
  "account-link-url": "https://foobar.net/auth/realms/profil/broker/OIDC_IDP/link?nonce=b1cf6bf4-beb3-4751-94fc-13135b3fc9a5&hash=jcn9LWknCd7oxwtWIXc-LNj4ctd3Z9lkUVKyyKHvBPQ&client_id=fancy-client-name"
}
```

Or is maybe our Identity Provider the root cause?

### Version

25.0.6

### Expected behavior

expires_in should always return the validity lifetime in seconds.

### Actual behavior

expires_in is often an unix timestamp.

### How to Reproduce?

```
curl --location 'https://dev.localhost.data-experts.net/auth/realms/profil/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'requested_issuer=OIDC_IDP' \
--data-urlencode 'subject_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJycjBjN0xGOS1UR2g4V19pZHBUMWFfNl8tOXI0QWd2MTVNalNnMThJaEZnIn0.eyJl....' \
--data-urlencode 'client_id=fancy-client-name' \
--data-urlencode 'client_secret=0cc14ebd-ee05-4af6-88ca-78794adf978f' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:token-exchange' \
--data-urlencode 'requested_token_type=urn:ietf:params:oauth:token-type:access_token'
```

**Comment by rmartinc** [comment]
@codeart1st I suppose the external idp is another OIDC adapter, right?

In that case, looking to the code, what keycloak is doing is getting the responses in the session if it is still valid, and just refreshes it if it is expired (it's different if you store the token, but similar). Check the code [here](https://github.com/keycloak/keycloak/blob/26.0.7/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L287). So the expected behavior is that you receive initially more or less the same time returned by the idp, then it starts decreasing until 0, and then it is refreshed and you get again the initial time. Can you check if you see this behavior?

**Comment by rmartinc** [comment]
Ah! No I've seen what you mention. The problem is in the `exchangeSessionToken` the [expiration is set to the expiration note](https://github.com/keycloak/keycloak/blob/26.0.7/services/src/main/java/org/keycloak/broker/oidc/OIDCIdentityProvider.java#L289) (which is in time in seconds or unix time). We have to subtract current time. I'm taking the issue but if someone what to send a PR with modification of a test it would be welcomed. I'll try to work on this when I have some time.

**Comment by codeart1st** [comment]
Okay.

Today I searched for the Response from IDP to Keycloak with WireMock as a proxy in between.

```
2024-12-11T10:21:30.618548100Z Matched response definition:
2024-12-11T10:21:30.618553748Z {
2024-12-11T10:21:30.618559034Z   "status" : 200,
2024-12-11T10:21:30.618564583Z   "jsonBody" : {
2024-12-11T10:21:30.618570372Z     "token_type" : "Bearer",
2024-12-11T10:21:30.618576615Z     "access_token" : "pkeptdzhrmzvnedabj0fmd7omsmjyi9xmf8buirx",
2024-12-11T10:21:30.618582585Z     "expires_in" : 86400,
2024-12-11T10:21:30.618588034Z     "expires_at" : "1733998890",
2024-12-11T10:21:30.618593835Z     "refresh_token" : "ylcxyptzjoccog6uaoxzislj5qrznemk9jyukhjx",
2024-12-11T10:21:30.618599968Z     "id_token" : "eyJhbGciOiJub25lIn0=.ey[...]"
2024-12-11T10:21:30.618607644Z   },
2024-12-11T10:21:30.618613062Z   "headers" : {
2024-12-11T10:21:30.618618890Z     "Content-Type" : "application/json; charset=utf-8"
2024-12-11T10:21:30.618624742Z   },
2024-12-11T10:21:30.618630382Z   "transformers" : [ "response-template" ]
2024-12-11T10:21:30.618735084Z }
```

Becoming

```
{
  "access_token": "pkeptdzhrmzvnedabj0fmd7omsmjyi9xmf8buirx",
  "expires_in": 1733998890,
  "refresh_expires_in": 0,
  "not-before-policy": 0,
  "issued_token_type": "urn:ietf:params:oauth:token-type:access_token",
  "account-link-url": "https://foobar.net/auth/realms/profil/broker/OIDC_IDP/link?nonce=a69e83f3-ea1e-42aa-8355-ecde80353229&hash=5eX4akh4sJQl6cC3VHpwWYgjc41-ovJMgr6uYZ2mNfQ&client_id=inet-zid"
}
```
