### ISSUE TITLE
PUT Method Not Updating Groups via Keycloak REST API

### ISSUE THREAD

**Issue by flaviodotcom** [keycloak/keycloak#35744]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Hello everyone,

I've encountered an issue with the Keycloak REST API when working with user groups. While the POST method successfully creates groups, the PUT method does not update the groups as expected.

According to the official documentation for the REST API, the entire UserRepresentation object should be passed in the request body when using the PUT method to update a user. However, it appears that the group information in the UserRepresentation is not being considered or applied during the update process.

![image](https://github.com/user-attachments/assets/f7161674-f0b3-4fb3-83a2-99e3138e91a3)

https://www.keycloak.org/docs-api/latest/rest-api/index.html

This seems to be a potential issue in the UserResource class, which may not be handling the group updates correctly. Could you confirm if this is a bug or the expected behavior? If it's a bug, I’d be happy to assist with additional details or testing to help resolve it.

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

The PUT method for the Keycloak REST API should update the UserRepresentation object, including changes to the user's group membership, as per the documentation. After sending a PUT request with a modified UserRepresentation that includes updated group information, the changes should be reflected in the user's group assignments.

### Actual behavior

When using the PUT method to update a user via the REST API, the changes to the user's groups in the UserRepresentation are not applied. Other fields in the UserRepresentation are updated correctly, but group membership remains unchanged.

### How to Reproduce?

Use the Keycloak REST API to create a user.
Assign a group to this user using the POST method.
Send a PUT request to update the user, modifying the group membership in the UserRepresentation provided in the request body.
Observe that the user's group membership does not reflect the changes.

**Comment by pedroigor** [comment]
We do not support managing groups when updating a user. For that, you need to use a separate endpoint `/users/{user-id}/groups/{groupId}`. The same for other operations such as removing the user from a group. When returning user representations we also do not return the groups where the user is a member of.

The inconsistency is actually on the `POST` method because both `PUT` and `GET` do not process groups.

Thanks for the feedback but we are not changing this behavior.
