### ISSUE TITLE
Not possible to reorder authentication flow

### ISSUE THREAD

**Issue by talbert83** [keycloak/keycloak#35765]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Dragging around executions in an existing authentication flow in admin UI does not yield the expected result.

### Version

26.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

Dragging an execution step up or down in the authentication flow moves it to that place in the list.

### Actual behavior

Most of the time the move is simply ignored, sometimes it moves the step to a different location, but I couldn't yet get it to move my sub-flow to where I wanted it to be.

### How to Reproduce?

I do the following:
* Log in in to admin CLI
* Go to my realm
* Open my custom authentication flow
* Try to drag the last execution step (a sub-flow) three places above in the list (on the top level)

### Anything else?

I also tried using the admin CLI, calling the same API endpoint as the UI: `POST /admin/realms/<my-realm>/authentication/executions/<execution-id>/raise-priority`. It returns 204, but has no effect.

I actually need to perform a change in my production setup and have no way to do it after upgrading to KC 26. This used to work in KC 24.

**Comment by talbert83** [comment]
I don't think it's a duplicate of #34098, I don't get any errors in the browser console, the backend call is made, returns 204 and I get a green message saying that the action was successful. But nothing is changed.
It's probably related to my custom flow and custom authenticators, because I couldn't reproduce it on a standard flow. I need to dig deeper to understand what is different in my case.

**Comment by andersjdba** [comment]
> I don't think it's a duplicate of [#34098](https://github.com/keycloak/keycloak/issues/34098), I don't get any errors in the browser console, the backend call is made, returns 204 and I get a green message saying that the action was successful. But nothing is changed. It's probably related to my custom flow and custom authenticators, because I couldn't reproduce it on a standard flow. I need to dig deeper to understand what is different in my case.

@talbert83 - Did you ever uncover anything around your custom flows with this one ? We're experiencing the exact thing you describe. We create custom flows via external means using the admin API. This worked fine at 24.0.5 but trying this in 26.0.8 we end up with our flows in an unexpected order despite specifying the index and level like we always have. When going to the gui, we're unable to move these executions in a subflow around despite a green update telling us the "flow was successfully updated" and the 204 status code. We can however move executions at the same level 0 around in the gui without any drama.

**Comment by talbert83** [comment]
> seems the AuthenticationExecutionInfoRepresentation now has "priority" albeit its marked as optional. When i dont send it with priority its defaulting to '0' for everything. I added that to my flows with the appropriate priority for each executor and its working again and i can move the executors in the subflow.
@andersjdba, thanks for your input, missing priority was exactly the reason for our mix-up, too!
