### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by rocksec0** [keycloak/keycloak#35772]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug
 
I have found a major critical issue please contact me immediately.

Thanks.

### Version

Latest

### Regression

- [ ] The issue is a regression

### Expected behavior

NA

### Actual behavior

NA

### How to Reproduce?

NA

### Anything else?

NA

**Comment by jonkoops** [comment]
Please use the communication channels as outlined on our [community page](https://www.keycloak.org/community).
