### ISSUE TITLE
 JS adapter - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" #35777 

### ISSUE THREAD

**Issue by khesayed** [keycloak/keycloak#35778]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

Building microfrontend architecture using module federation fails due to 
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports"`
![Screenshot 2024-12-10 at 10 03 10 PM](https://github.com/user-attachments/assets/9e25f15e-a953-4612-a8b2-0f6efa47193e)

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Build passes

### Actual behavior

Build fails

### How to Reproduce?

Building module federation apps

**Comment by jonkoops** [comment]
Closing for reasons mentioned under https://github.com/keycloak/keycloak/pull/35779#issuecomment-2535468228
