### ISSUE TITLE
Keycloak incorrect usage of UserPolicy and cache.

### ISSUE THREAD

**Issue by deadchapaev** [keycloak/keycloak#35796]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

We have an LDAP provider, and any request to issue an RPT token leads to a call to the LDAP server.

Cache tuning does not resolve this issue.

I observed some problems in the Keycloak code.

In the class **UserPolicyProviderFactory**, the method **toRepresentation** deserializes a **UserPolicy** that always stores only a **Set** of **UUIDs**.

During this process, the method calls **getUser** with the **UUID** parameter (**userId**), which is correct:

```
representation.setUsers((Set<String>) JsonSerialization.readValue(users, Set.class).stream()
                        .filter(id -> getUser((String) id, authorization) != null)
                        .collect(Collectors.toSet()));
```

However, inside **getUser**, I noticed an issue. The method first attempts to search for a user using **userProvider.getUserByUsername**, passing an incorrect parameter, **userId**:

```
UserModel user = userProvider.getUserByUsername(realm, userId);

if (user == null) {
    user = userProvider.getUserById(realm, userId);
}
```

This behavior causes the following problems:

The call to **userProvider.getUserByUsername** always ignores the cache and queries the LDAP server.
The reason: No user provider can return a user by **username = :userId** since **userId is a UUID**. Consequently, the **user is not stored in the cache**.
The subsequent call to **userProvider.getUserById** works correctly and caches the user. However, the cache entry is tied to the **getUserById key, not getUserByUsername**.
On subsequent client requests, this process repeats:
The cache is bypassed for **getUserByUsername**, resulting in repeated LDAP lookups.

Proposed Fix

I suggest modifying the getUser method in the UserPolicyProviderFactory to **remove** the unnecessary **userProvider.getUserByUsername** call. Since the **userId** is already a **UUID**, directly calling **getUserById** would avoid redundant LDAP queries and ensure proper caching behavior.

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak goes to ldap only at first client request, then put user model to cache with correct cache key..

### Actual behavior

The call to **userProvider.getUserByUsername** always ignores the cache and queries the LDAP server.
The reason: No user provider can return a user by **username = :userId** since **userId is a UUID**. Consequently, the **user is not stored in the cache**.
The subsequent call to **userProvider.getUserById** works correctly and caches the user. However, the cache entry is tied to the **getUserById key, not getUserByUsername**.
On subsequent client requests, this process repeats:
The cache is bypassed for **getUserByUsername**, resulting in repeated LDAP lookups.

### How to Reproduce?

Configure any ldap provider, enable debug log, issue rpt token.
See logs.

**Comment by sguilhen** [comment]
Looks like the `getUser` method is also called when updating policies (IIRC you can pass usernames when updating, Keycloak will search the user and store the Id instead of the username).

It should be sufficient to invert the searches - first try by id, then fallback to username. When reading the policies this will prevent the unnecessary call to `getUserByUsername`.

**Comment by sguilhen** [comment]
I'm assigning this as important because the cache misses has a performance impact (even more when an external user federation is involved, like LDAP).

**Comment by shinyobject88** [comment]
Question on this issue. We are seeing Service Accounts that are granted access to resources via another clients authorization settings and client policy. We see that we are logging LDAP queries with the UUID of the clients for those service accounts. Would this address that issue as well? The Authorization policies are a mix of group and client polices that are required. In addition, we have to set NO_CACHE as we are getting refreshed Group AD data with the CACHE turned on. Currently running on 24.0.4 but looking to update if this resolves the issue.
