### ISSUE TITLE
Session count limiter doesnt work for cookie auth step

### ISSUE THREAD

**Issue by madziszyn** [keycloak/keycloak#35865]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have 3 webapps (vue with keycloak.js adapter):

- "dashboard" => keycloak_client_1
- "phone" => keycloak_client_2
- "tablet"  => keycloak_client_2

Note that "phone" and "tablet" share same keycloak client.

We want to allow users to use "dashboard" and "phone" or "dashboard" and "tablet" at the same time. But not "phone" and "tablet". We tried to configure this using modified Browser flow and User session count limiter step with option "Maximum concurrent sessions for each user per keycloak client." set to 1 and realm limit set to 0. We are using option "Terminates oldest session" for session limiter.

It works great when User Password Form step is executed but failes when Session limiter is applied after Cookie step; it deletes existing session. We tried many different configurations (also slightly modified version described here: https://www.keycloak.org/docs/latest/server_admin/#_user_session_limits).
Also, when session limiter precedes Cookie step it appears to do nothing.

Actual config for now:
![keycloak_auth](https://github.com/user-attachments/assets/df7ae599-6b41-455f-8b74-565186e5f020)

When session limiter (cookie sub-flow; with limit 1) is applied after Cookie step:

- user opens "dashboard" URL 
- there is no cookie and sessions so user is redirected to keycloak's login form
- after successful login user is redirected to app and everything is normal (one session in keycloak)
- user refreshes browser (f5) and hit cookie subflow (which executes with success) but session limiter deletes only session that exists (no sessions afterwards) and after redirect to app, token request failes and user has to log in again

For now we changed max limit to 2 (only in cookie sub-flow), only to try if session limiter deletes "one more session than it should". But such configuration allows:

- user opens "dashboard" on PC1 (login form)
- user opens "phone" on PC2 (login form)
- now there are 2 sessions which is correct (one with client keycloak_client_1 and other with client keycloak_client_2)
- then user opens new tab in browser on PC1 and enters "phone" (using existing session/cookie)
- then user opens new tab in browser on PC2 and enters "dashboard"
- this results in 2 sessions with 2 keycloak clients each (which is correct for given "test" configuration)
- weird thing is this that now when users refreshes app (f5) lets say on PC1 it results in session deletion for PC2. Also order doesnt matter here. Same thing applies in other direction: user refreshes any of the apps on PC2 then session for PC1 is deleted

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Session limiter doesnt delete any sessions when total number of sessions dont exceed configured limit.

### Actual behavior

User session count limiter deletes session only when actual number of sessions exceeds configured limit.

### How to Reproduce?

You need two keycloak clients with browser flow and session limiters. 
Test cases are described in description sesction.

**Comment by madziszyn** [comment]
Tried to reproduce in 26.0.7 but it seems to be fixed in latest version. Thank you. I couldn't find any information that auth flows had some changes since 24.0.1

**Comment by jonkoops** [comment]
Thanks for checking up on that, I will consider this issue resolved then :+1:
