### ISSUE TITLE
MapComponent UI Not Displaying Saved Values in Keycloak React Admin UI

### ISSUE THREAD

**Issue by A-Ibm** [keycloak/keycloak#35874]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I have been experimenting how to [extend the Admin Console](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-admin-console-spi), specifically adding tabs (as I must upgrade Keycloak to a newer version with the new React-based Admin UI). 

When using `ProviderConfigProperty.MAP_TYPE` to add a map-based component to the Admin UI, the UI does not correctly display the saved values. While the backend saves and returns the correct values, the map appears empty after reloading the page. This leads to overwriting existing values as you start from a fresh empty map.

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

- The map component should correctly display the saved values when the page is reloaded.
- The UI should remain consistent with the data returned by the backend.

### Actual behavior

- After saving values in the map component and reloading the page, the map is displayed as empty.
- Although the backend correctly saves and returns the values (verified via the network tab), the UI does not display them.
- Re-saving the empty map overwrites the previously saved values, causing data loss (as you start from an empty map).

### How to Reproduce?

1. Open the [extend the Admin Console project](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-admin-console-spi).

2. Replace `ProviderConfigProperty.STRING_TYPE` with `ProviderConfigProperty.MAP_TYPE` in [ThemeUiTab.java at line 71](https://github.com/keycloak/keycloak-quickstarts/blob/main/extension/extend-admin-console-spi/src/main/java/org/keycloak/admin/ui/ThemeUiTab.java#L71).

3. Run the project as explained in the [README.md](https://github.com/keycloak/keycloak-quickstarts/tree/main/extension/extend-admin-console-spi#readme).

4. Open `Realm Settings` and navigate to the `Attributes` tab.

5. Add some values to the map component.

6. Save the values.

7. Reload the page and observe that the map appears empty.

8. Check the network tab to confirm that the backend correctly returns the saved values (in the `GET admin/realms/master/components?type=org.keycloak.services.ui.extend.UiTabProvider` call).

### Anything else?

I found that the issue lies in the `getValues(fieldName)` function in the [MapComponent](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/components/dynamic/MapComponent.tsx), which always returns an empty result. This happens because the function is executed too early, before the backend response is received, causing the map to display as empty.

To resolve this issue, I modified the parent element, the [PageHandler](https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/page/PageHandler.tsx), to ensure it waits for the backend response before rendering the specific component. Below is the relevant snippet from my solution:

``` typescript
// Added state to track loading status
const [isLoading, setIsLoading] = useState(true);

// Ensure data is fetched before rendering
useFetch(
  async () =>
    await Promise.all([
      id ? adminClient.components.findOne({ id }) : Promise.resolve(),
      providerType === TAB_PROVIDER
        ? adminClient.components.find({ type: TAB_PROVIDER })
        : Promise.resolve(),
    ]),
  ([data, tabs]) => {
    const tab = (tabs || []).find((t) => t.providerId === providerId);
    form.reset(data || tab || {});
    if (tab) setId(tab.id);

    // Set loading to false once the data is fetched
    setIsLoading(false);
  },
  [],
);

// Render spinner while loading
if (isLoading) {
  return <KeycloakSpinner />;
}
```

This approach ensures that the backend response is fully loaded before rendering the component, preventing the `getValues()` function from returning an empty list. While this solution works, I would appreciate feedback on whether this is the best practice or if there are better ways to handle such scenarios.

**Comment by edewit** [comment]
right, I fixed it almost the same, but without introducing this extra loading state

**Comment by A-Ibm** [comment]
Hello again @edewit @agagancarczyk, 

I believe this issue should be reopened, as the fix does not fully address the problem.

It works fine initially. However, it fails when no values (of child components) are set for the custom tab. 

Specifically, when the tab is opened for the first time and no values are set, tab does not contain any data. As a result:

- `tab` is `undefined`.
- As `tab` is `undefined`, the `setId(tab.id)` line is never executed.
- The loading logic depends on `id` being set, so the condition for fetching data is never satisfied, and the spinner spins indefinitely.

``` typescript
useFetch(
  async () =>
    await Promise.all([
      id ? adminClient.components.findOne({ id }) : Promise.resolve(),
      providerType === TAB_PROVIDER
        ? adminClient.components.find({ type: TAB_PROVIDER })
        : Promise.resolve(),
    ]),
  ([data, tabs]) => {
    const tab = (tabs || []).find((t) => t.providerId === providerId);
    form.reset(data || tab || {});
    if (tab) setId(tab.id); // here tab is undefined if it is opened for the first time
  },
  [],
);

// spins indefinitely
if (isLoading) {
  return <KeycloakSpinner />;
}
```

The problem is that once the spinner enters this infinite loading state, it will continue spinning every time you open the page, not just the first time. This effectively prevents the custom component from ever being displayed, as the loading state never resolves.

Additionally, since `PageHandler` is the parent of all custom components, the issue impacts all of them.

I’ve opened a PR to fix the loading logic [here](https://github.com/keycloak/keycloak/pull/35979).

Let me know if you need further details.
