### ISSUE TITLE
Typo in username pt_BR translation in account console

### ISSUE THREAD

**Issue by lluccia** [keycloak/keycloak#35876]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Translation of username in account console ui is mispelled.

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

username should be "Nome de usuário"

### Actual behavior

username is "Nome de usúario"

### How to Reproduce?

Open the account console using pt_BR translation.

### Anything else?

https://github.com/keycloak/keycloak/blob/f12fe052a6005c117931e071cb3e3427b36d4666/themes/src/main/resources-community/theme/base/account/messages/messages_pt_BR.properties#L48

https://github.com/keycloak/keycloak/blob/f12fe052a6005c117931e071cb3e3427b36d4666/js/apps/account-ui/maven-resources-community/theme/keycloak.v3/account/messages/messages_pt_BR.properties#L94

**Comment by ssilvert** [comment]
@lluccia Will you be sending a pull request?

If this is your first, see https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md

**Comment by lluccia** [comment]
Hello @ssilvert!

Yes, it is my first contribution. Thanks for the contributing guidelines.

I already submitted a pull request <https://github.com/keycloak/keycloak/pull/35877>.
