### ISSUE TITLE
globalStatsInterval not working with QuarkusJpaConnectionProviderFactory

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak#35931]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

The QuarkusJpaConnectionProviderFactory doesn't allow to easily see jpa statistics the way DefaultJpaConnectionProviderFactory (which I thing is not used anymore).
There should be an easy way to view these logs, to debug performance issues.

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

To be able to view JPA stats easily.

### Actual behavior

You need to add extra code to view these stats.

### How to Reproduce?

Try to start the code with globalStatsInterval > 0 no logs will be displayed.

**Comment by shawkins** [comment]
This is something that was specific to the old distribution, so we probably can't treat it as a regression and just come up with what most closely matches what you are looking for. Can you describe what information you want and how you are using it?

There are stats available for quarkus datasources via metrics with the [quarkus.datasource.jdbc.enable-metrics](https://quarkus.io/guides/all-config#quarkus-agroal_quarkus-datasource-jdbc-enable-metrics) option. However I don't think we're currently setting that when metrics are enabled on keycloak, so you'd have to do that via the quarkus.properties. cc @mabartos 

@yrodiere is there an existing logging config to dump metrics periodically?

**Comment by yelhouti** [comment]
@shawkins thank you for your reply, I was indeed able to print session results using -Dquarkus.hibernate-orm.statistics=true in the build step. Although numbers are sometime broken (multiple days, for session I just run).
I will clause this and focus on the main issue: https://github.com/keycloak/keycloak/issues/35932

**Comment by yrodiere** [comment]
> There are stats available for quarkus datasources via metrics with the [quarkus.datasource.jdbc.enable-metrics](https://quarkus.io/guides/all-config#quarkus-agroal_quarkus-datasource-jdbc-enable-metrics) option. However

Are we talking about JDBC statistics or Hibernate statistics here?

> @yrodiere is there an existing logging config to dump metrics periodically?

None that I know of. But if you set [quarkus.hibernate-orm.statistics](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus-hibernate-orm-statistics) to `true`, you can access statistics through `org.hibernate.SessionFactory#getStatistics` and you even have a handy method to log them: `org.hibernate.stat.Statistics#logSummary`.

There is also an _actual_ metrics integrations with Micrometer, which you can enable with [quarkus.hibernate-orm.metrics.enabled](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus-hibernate-orm-metrics-enabled) as soon as you have the relevant extensions in your app, and I would be surprised if Micrometer didn't have a way to logs metrics regularly. But then you need Micrometer for this.

**Comment by yelhouti** [comment]
@yrodiere thank you for the details explanation.

**Comment by dalbani** [comment]
@yelhouti 
> I was indeed able to print session results using `-Dquarkus.hibernate-orm.statistics=true` in the build step.

I'm curious how you managed to build Keycloak which such a feature, as in my case it complained that:
```
8.225 ERROR: A legacy persistence.xml file is present in the classpath, but Hibernate ORM is also configured through the Quarkus config file.
8.225 Legacy persistence.xml files and Quarkus configuration cannot be used at the same time.
8.225 To ignore persistence.xml files, set the configuration property 'quarkus.hibernate-orm.persistence-xml.ignore' to 'true'.
8.225 To use persistence.xml files, remove all 'quarkus.hibernate-orm.*' properties from the Quarkus config file.
```

For the record, I'm building it like this:
```
./bin/kc.sh -Dquarkus.hibernate-orm.statistics=true build --db=postgres --health-enabled=true --metrics-enabled=true
```
