### ISSUE TITLE
 200 success response as if we use GET instead of POST  for Logout api when we use admin api for logout user with refresh token 

### ISSUE THREAD

**Issue by santhoshkotala123** [keycloak/keycloak#35975]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authorization-services

### Describe the bug

 200 success response as if we use GET instead of POST  for Logout API
  when we use admin API for logout user with refresh token with other HTTP methods like put we are getting 405 Error 
  but when we use GET for 'http://localhost:8080/realms/voltacabs/protocol/openid-connect/logout we need to get 405 
  But we are getting 200 OK 
![Screenshot 2024-12-17 155845](https://github.com/user-attachments/assets/81bf1083-ab7b-4e0f-9a25-6b0bc617d7a5)
![Screenshot 2024-12-17 155905](https://github.com/user-attachments/assets/fb219f52-1c4d-4966-87dd-558416a4a53f)

  
  curl --location --request PUT 'http://localhost:8080/realms/voltacabs/protocol/openid-connect/logout' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: AUTH_SESSION_ID=33b......2e4f' \
--data-urlencode 'client_id=postman' \
--data-urlencode 'client_secret=0xg......bBHtJbO' \
--data-urlencode 'refresh_token=ey......Q'

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

we need to get 405 error for logout API when we use a part from POST method 
for other methods we are getting correct reponce METHODS-PUT ,PATCH DELETE
{
    "error": "HTTP 405 Method Not Allowed"
}
When we use GET Http Method we are getting 200 ok response as we should not get 

### Actual behavior

When we use GET Http Method we are getting 200 ok response as we should not get 

### How to Reproduce?

we need to get 405 error for logout API when we use a part from POST method 
for other methods we are getting correct reponce METHODS-PUT ,PATCH DELETE
{
    "error": "HTTP 405 Method Not Allowed"
}
When we use GET Http Method we are getting 200 ok response as we should not get

**Comment by pedroigor** [comment]
@keycloak/core-clients team can confirm that, but the logout endpoint only supports `POST` and `GET`. The behavior is expected and the description is a bit misleading:

```
we need to get 405 error for logout API when we use a part from POST method
for other methods we are getting correct reponce METHODS-PUT ,PATCH DELETE
{
"error": "HTTP 405 Method Not Allowed"
}
When we use GET Http Method we are getting 200 ok response as we should not get
```

**Comment by rmartinc** [comment]
Hi @santhoshkotala123!

The logout endpoint supports GET and POST as it's defined in the spec [openid-connect rp-initiated logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout) :

> OpenID Providers MUST support the use of the HTTP GET and POST methods defined in RFC 7231 at the Logout Endpoint. RPs MAY use the HTTP GET or POST methods to send the logout request to the OP. If using the HTTP GET method, the request parameters are serialized using URI Query String Serialization. If using the HTTP POST method, the request parameters are serialized using Form Serialization.

So this is working as expected. Closing the issue.
