### ISSUE TITLE
keycloak-admin-client wasn't released to maven repositories since version 26.0.3

### ISSUE THREAD

**Issue by bratwurzt** [keycloak/keycloak#36128]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

While upgrading dependencies to latest at the time (26.0.7) I've noticed keycloak-admin-client is missing from maven repositories  since version 26.0.3:
https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client
https://central.sonatype.com/artifact/org.keycloak/keycloak-admin-client

But releases on github do contain tgz:
https://github.com/keycloak/keycloak/releases/download/26.0.7/keycloak-admin-client-26.0.7.tgz

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client/26.0.7 to exist

### Actual behavior

https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client/26.0.7 does not exist

### How to Reproduce?

open https://mvnrepository.com/artifact/org.keycloak/keycloak-admin-client/26.0.7 in browser

**Comment by jonkoops** [comment]
This is working as expected, as outlined in the [announcement blog post](https://www.keycloak.org/2024/10/keycloak-2600-released) the clients are now versioned separately from the main project.

**Comment by SomeDeveloper13** [comment]
If you're going to remove them from the release cycle, shouldn't you bring back the BOM?
