### ISSUE TITLE
RP-Initiated logout using POST method fails in cross-origin setup (issue not resolved on 26.0.7)

### ISSUE THREAD

**Issue by atul-epam** [keycloak/keycloak#36149]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

The issue mentioned in https://github.com/keycloak/keycloak/issues/32648 is still failing in keycloak version 26.0.7.

_**Access to XMLHttpRequest at 'https://hostname:ip/realms/myrealm/protocol/openid-connect/logout' from origin 'https://hostname:ip' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**_

It is clearly mention at https://www.keycloak.org/2024/12/keycloak-2607-released that the issue has been addressed in 26.0.7

![image](https://github.com/user-attachments/assets/48b9ad73-4b54-44fd-ac8d-9a4df7dfc685)

### Version

26.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Issue should be fixed for 26.0.7 as mentioned in release notes.

### Actual behavior

Issue persist in 26.0.7

### How to Reproduce?

Steps are mentioned here https://github.com/keycloak/keycloak/issues/32648

**Comment by jonkoops** [comment]
Pretty sure you haven't upgraded your Keycloak JS version which is causing this issue, as the fix for #34694 is not for the main Keycloak server. Make sure you upgrade all your dependencies.

**Comment by atul-epam** [comment]
I added following dependency in my pom.xml https://mvnrepository.com/artifact/org.keycloak/keycloak-js-adapter/26.0.7 but it is still not working. I am getting same error.

**Comment by jonkoops** [comment]
How exactly are you loading the files from this artifact?

**Comment by atul-epam** [comment]
@jonkoops  I am just adding keycloak-js dependency in my project and not doing any additional step. Please let me know for additional things to perform.

**Comment by jonkoops** [comment]
I don't see how that would work. Keycloak JS needs to be loaded into a HTML page of some kind, in this case the page where you are seeing this error. Also, the default behavior is to use the GET request variant, so it must be an explicit opt-in to use the POST variant. You can see how this works in the [guide for the JavaScript adapter](https://www.keycloak.org/securing-apps/javascript-adapter).

**Comment by atul-epam** [comment]
Hi @jonkoops sorry for the confusion. We are using https://hostname:ip/realms/myrealm/protocol/openid-connect/logout REST API as mentioned in issue description and not using Keycloak JS. Currently we are on 26.0.5

**Comment by jonkoops** [comment]
In that case I would recommend you align your implementation and use a form to submit a POST request, it is supposed to be a navigation anyways.

**Comment by atul-epam** [comment]
Hi @jonkoops I am not sure how a form will help in getting rid of CORS error.

**Comment by jonkoops** [comment]
A form submission is except from CORS, although cookies might still be blocked.

**Comment by atul-epam** [comment]
Hi @jonkoops 

We are using angular as front end and calling POST API with multipart/formdata for Logout and still getting the CORS error (we are passing the clientId and refreshtoken)

**Comment by jonkoops** [comment]
Yes, that is because the library is still does an actual POST request and not a redirect to this endpoint. I am still not convinced we should be adding CORS headers here. See the discussion on #32648. If there is an advisory from the specification we might reconsider this. I'd recommend you file a bug with the author of the library you are using to do OAuth, feel free to link back here.

**Comment by atul-epam** [comment]
Hi @jonkoops thanks for the suggestion but I am not sure which Library are you talking about?

**Comment by jonkoops** [comment]
> We are using angular as front end and calling POST API with multipart/formdata for Logout and still getting the CORS error (we are passing the clientId and refreshtoken)

I assume you are using an OAuth library? If you are doing this manually then don't do that using the Fetch API and follow my recommendation to use a hidden form to submit to this endpoint. This is what Keycloak JS does as well.
