### ISSUE TITLE
OIDC / SAML Logout

### ISSUE THREAD

**Issue by c8agomez** [keycloak/keycloak#36167]
### Description

I have configured OIDC & SAML client for gitlab. It logs me in perfectly but when I logout in gitlab, it closes the client session but not the user session in keycloak remains open.

Thanks

**Comment by jonkoops** [comment]
Please use the proper template when reporting an issue, this is not a task. If you have a user support question please use the appropriate channels [in the community](https://www.keycloak.org/community).
