### ISSUE TITLE
Logout from account console with wrong post_logout_redirect_uri

### ISSUE THREAD

**Issue by wiedsche** [keycloak/keycloak#36166]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Since Keycloak 26 (26.0.0.7) the `post_logout_redirect_uri` parameter of the logout url is wrong. The url is set as target of the "logout" button in the account console in the top right.

The parameter value starts with "http://" and not with "https://". That's the reason for getting an error message on logout "invalid Redirect Uri".

All other urls and flows in the keycloak installation seem correct. No issues there with erroneous http-calls. 

It's the same behavior in the account-v1 theme and our custom keycloakify theme.

With Keycloak 24 it was working.

### Version

26.0.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The `post_logout_redirect_uri` parameter of the logout url should start with `https` 

### Actual behavior

The `post_logout_redirect_uri` parameter of the logout url should start with `http` 

### How to Reproduce?

1. Open account console: https://keycloak/realms/testrealm/account/
2. Login with credentials
3. Logout by clicking "logout" button in the top right corner.

**Comment by jonkoops** [comment]
This honestly sounds like a configuration issue causing Keycloak to assume that you are running on HTTP. Are you sure you have [configured the hostname ](https://www.keycloak.org/server/hostname)of the Keycloak server correctly?

**Comment by wiedsche** [comment]
> configured the hostname

the hostname is configured properly as complete url (hostname_v2, as required since keycloak 25). example: https://mykeycloakinstance


The keycloak instance runs behind an AWS alb, that provides x-forwarded-* headers. 


As mentioned above, there are no other issues in any other places in keycloak. For example oidc endpoint urls are looking fine.

**Comment by jonkoops** [comment]
Can you provide a reproducible case that works locally?

**Comment by wiedsche** [comment]
While setting up a local setup for reproduction I found out, that the issue is not the default keycloak account theme (keycloak.v3). There was an additional "account-v1" theme in the keycloakify jar, which I erroneously mapped as the default keycloak theme.

The reason, why I thought the keycloakify theme is the "official keycloak theme" is, that that was working and "keycloak.v3" didn't show any account console at all. It showed up, that https://github.com/keycloak/keycloak/issues/34780 was the reason for not being functional. With fiddling out, that the web origin must be set to "*", and then the account console works as expected, I can tell now, that also the logout url is working correctly.

Anyway, with hints in #34780 regarding the setting `KC_PROXY_HEADERS=xforwarded` also solved my keycloakify issue.
With setting this configuration parameter, the logout url is determined with the correct protocol information.

**Comment by jonkoops** [comment]
Good to hear, thanks for following up on it :+1:
