### ISSUE TITLE
Enable CDI for custom providers

### ISSUE THREAD

**Issue by alwibrm** [keycloak/keycloak#8725]
### Description

It would be a huge progress to be able to use dependency injection (CDI) in custom developed Keycloak components. Otherwise you have to build up object graphs by hand, which can become very cumbersome in complexer customizations.

A few years ago somebody else requested that enhancement in KEYCLOAK-3672. Unfortunately the request was rejected back in the days. Hopefully this one gets a bit more attention in 2021.

See https://issues.redhat.com/browse/KEYCLOAK-13359

**Comment by stianst** [comment]
We aim to have a review in the future with regard to writing extensions/customising Keycloak. However, not leveraging CDI was a very conscious decision and has made it possible for us to have Keycloak running on a range of different platforms (WildFly, Tomcat, Spring, and now Quarkus). The more loosely coupling to the underlying platform allows us to both re-tool as well as hide more of the version upgrades of the underlying platform. Hence, introducing CDI would not be a decision we would take lightly.

I would be interested in more details though on what is lacking here, as we do have our own "micro-kernel" with SPIs and providers. I appreciate that there is some capabilities missing here, but we do use this same mechanism to build Keycloak itself, and I believe it gives us better control and can also provide a better developer experience than using CDI.

**Comment by alwibrm** [comment]
Thanks for pointing out the reasons, @stianst.

Since we added numerous Required Actions and Authenticators which come with their own Services, Entities and Repositories we have to build up a rather extensive object graph. Implementing and using all the custom classes as providers + factory + reference in META-INF/service didn't work for us and would result in a considerable amount of boilerplate code.

Another use case was to add Kafka Consumer capabilities with SmallRye. From my understanding you need a bean with `@ApplicationScope` for the reactive messaging API, [see example](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.4/kafka/kafka.html).

Do you discourage one from enabling the Weld subsystem in Keycloaks underlying Wildfly? If yes, what be your recommendation? Thanks in advance.
