### ISSUE TITLE
Unable to set exact priority of flow execution via REST API

### ISSUE THREAD

**Issue by jkroepke** [keycloak/keycloak#8726]
### Description

Hi,

the REST API PUT /flows/{flowAlias}/executions ignores the priority property from the http body.

As alternative the REST API

POST /executions/{executionId}/raise-priority
POST /executions/{executionId}/lower-priority
exists, but it's not easy to ensure a defined state, e.g. if you want to raise from priority 4 to priority 1, you you call the raise-priority API three times. It could be more complex, if you want to add a new execution and put it on the 3rd position.

Same for POST /flows/{flowAlias}/executions/execution

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-14615

### Motivation

A REST endpoint where I can define the exact priority of a auth flow/execution.

The current implement only allows to shift execution below or above others execution.

In general, It's easy to destroy and re-create the whole flow. It match a desired state.

**Comment by jonkoops** [comment]
I've assigned this to you @keshavprashantdeshpande

**Comment by jonkoops** [comment]
Ah, so you believe that one of these PRs has actually fixed this issue? Seems like they are indeed related to this problem. Very well, then I will close this one out. Thanks for the research!
