### ISSUE TITLE
KeycloakAuthenticatorValve (Tomcat) does not implement createRequestAuthenticator()

### ISSUE THREAD

**Issue by ammannmi** [keycloak/keycloak#8727]
### Describe the bug

Because of the missing override of createRequestAuthenticator(), the valve uses the CatalinaRequestAuthenticator instead of the TomcatRequestAuthenticator. The CatalinaRequestAuthenticator has no prevention against the session fixation attack. This security issue should be fixed as soon as possible.
see https://github.com/keycloak/keycloak/blob/dd69bb5d33d0ee825fcfc2f1a0502709a60fdacf/adapters/oidc/tomcat/tomcat/src/main/java/org/keycloak/adapters/tomcat/KeycloakAuthenticatorValve.java

### Version

9.0.3 - 15.0.2

### Expected behavior

Change of the session id after a successful login

### Actual behavior

Session id remains after login.

### How to Reproduce?

Check the session id before/after a login

**Comment by ammannmi** [comment]
As proposal I created a pull request:
Issue #8727: Update KeycloakAuthenticatorValve.java #8728
I tested it successfully on our instances

**Comment by abstractj** [comment]
@ammannmi could you please drop an e-mail to keycloak-security@googlegroups.com please? I could not find any way to contact you privately and I have a few questions.

**Comment by ammannmi** [comment]
Any progress? Did you received my mail?

**Comment by Paramvir-JIndal** [comment]
@abstractj, I am able to test this patch and it seems working fine for me.
