### ISSUE TITLE
Push authentication

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#8740]
### Description

It would be great if Keycoak could support push authentication / push 2FA. This would simplify 2FA and open a new passwordless authentication method.

**Comment by stianst** [comment]
It is unlikely that we will ever add push authentication directly as this is a very complicated feature to provide as it requires a proprietary protocol, ability to send push events to different device types, as well as SDKs or apps for Android, iOS, and Windows?

There's also WebAuthN that delivers similar experiences as push authentication, but using a standard protocol.

**Comment by stianst** [comment]
I'm going to close this for now. If you need push based authentication there is a wade range of options for exactly that, which can be relatively easily be integrated into Keycloak.
