### ISSUE TITLE
Http claim provider to support url path parameters

### ISSUE THREAD

**Issue by Panayioc** [keycloak/keycloak#8743]
### Description

Copied from https://issues.redhat.com/browse/KEYCLOAK-10119

When setting up http Claims providers within policy enforcement, we want to be able to resolve the path parameters of the uri.

So for a concrete example, someone tries to modify shopping cart contents by calling to API on PUT /rest/v1/carts/{cartId}
We want to be able to get the cart status from another system and add it to claims to make a policy decision according to cart status and calling user roles.

"claim-information-point": {
"http": {
"claims": { "cart_status": "/status" },
"url": "https://blf-server:8443/site/api/v1/cart/{cartId}
",
"method": "GET"
}
}
The issue here is that we have to send cartId as part of the request, but it’s not present in body or the headers of the original request, only as part of the original request URI.
At a glance I don’t see a way in 7.3 RequestPlaceHolderResolver to do something like {request.uri.5}
to get just that part of the request URI and use it in claim/parameter of request.

### Motivation

The issue here is that we have to send cartId as part of the request, but it’s not present in body or the headers of the original request, only as part of the original request URI.

**Comment by pedroigor** [comment]
@Panayioc Are you able to contribute with the necessary changes?

**Comment by pedroigor** [comment]
@Panayioc Sorry, we don't have time to work on that now. Please, feel free to re-open if you think you can help us with a contribution.

**Comment by Panayioc** [comment]
ok, we will try to create a pull request.
