### ISSUE TITLE
View group membership ( account console)

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#8748]
### Description

In the user account console, an extra menu will exist for user groups in order to be able to view the groups he/she is a member of. View groups ui could be similar to the group tab in the new admin console. Role  'view-groups' , which allows controlling which users can view groups, will be added to the account client.

Transferred issue from Jira: https://issues.redhat.com/browse/KEYCLOAK-17668
Keycloak-dev discussion: https://groups.google.com/g/keycloak-dev/c/4ZXObLaBc7I
PR: https://github.com/keycloak/keycloak/pull/7933 

Although I have done minor changes requested, PR is not accepted yet.

### Motivation

Users can not see group information from the account console. Users should at least be able to view the groups that they are a member of. This is essential for knowing their attributes and roles based on group membership.

### Details

![groups](https://user-images.githubusercontent.com/55974447/140930531-928e2c9e-6f1b-4f5f-9fdb-20c7e812deaa.PNG)
Screenshot from ui

**Comment by cgeorgilakis** [comment]
Could you finish review in PR?

Last @thomasdarimont comment was: 

> Minor formatting nitpick - otherwise this LGTM.

Generally, how I can link a PR with a github issue?

**Comment by xianli123** [comment]
Hi @cgeorgilakis , this is Kun, from UXD team and I am working on the new design of Keycloak. 

With regard to this feature, does it only allow users to check the group they belong to, not edit the group? Thanks.

**Comment by xianli123** [comment]
Thanks @cgeorgilakis I see. I will update the UI based on your explanation and suggestion.

**Comment by xianli123** [comment]
Hi @cgeorgilakis, I updated the design of the Groups, here is the link: https://marvelapp.com/prototype/ige09a4/screen/88721445. Please check it and feel free to leave your comments if you have some suggestions.

**Comment by cgeorgilakis** [comment]
@xianli123 It looks good

**Comment by xianli123** [comment]
@cgeorgilakis Thanks. I will share the design with UI developer team. If they don't have any comments, we can add this new feature in the new UI.

**Comment by ssilvert** [comment]
@cgeorgilakis To be clear, we are not asking you to update anything.  We are rebuilding account console in keycloak/keycloak-ui repo.  So we will use the new design when we do that.
