### ISSUE TITLE
Require user to agree to 'terms and conditions' during registration

### ISSUE THREAD

**Issue by reda-alaoui** [keycloak/keycloak#8750]
### Description

When a new user registers, personal data is already collected, stored and processed before the necessary consent is obtained from the user. This violates European data protection regulations and disqualifies the use of Keycloak within the scope of European law. I am astonished that so less requests on this subject have arrived. The only report I found was KEYCLOAK-8447.

Is there any workaround for this?

### Discussion

See https://issues.redhat.com/browse/KEYCLOAK-15244

**Comment by agemuend** [comment]
We are very interested in this, is it still being worked on?

**Comment by thomasdarimont** [comment]
I need this quite often in customer projects, up until now I implemented this with a custom Registration FormAction and register.ftl template:
- [CustomRegistrationUserCreation](https://github.com/thomasdarimont/keycloak-project-example/blob/main/keycloak/extensions/src/main/java/com/github/thomasdarimont/keycloak/custom/registration/formaction/CustomRegistrationUserCreation.java#L40)
- [register.ftl](https://github.com/thomasdarimont/keycloak-project-example/blob/main/keycloak/themes/custom/login/register.ftl#L127)
