### ISSUE TITLE
Login with IDP available on user account (not domain) 

### ISSUE THREAD

**Issue by kadhemmejri** [keycloak/keycloak#8766]
### Description

Hello,

Please I need your help

Is there any possibility to configure an authentication flow like this :

The first login page asks for username/email and when the user click next he gets to choose with which identity provider he wants to connect from the list of identity providers available on the user account (Identity provider link)

Scenario :

Imagine the user has 2 IDP configured on his profile (the domain can have more IDP configured)

![image](https://user-images.githubusercontent.com/70603515/141088112-6a22241a-ad1a-43cc-abe3-4addce170e72.png)

When the user open the login page, he introduce the login/email and click next to arrive on an interface with "choose an identity provider" with a list of identity providers added to the user account

![image](https://user-images.githubusercontent.com/70603515/141087837-8bc40811-013f-4419-ba5f-8a4649a7c563.png)

Could you tell me if this can be configured with any version of Keycloak ? or should we make specific developpement

Thank you so much for your prompt reply

### Discussion

https://github.com/keycloak/keycloak/discussions/8747

**Comment by stianst** [comment]
This is a question, not an epic, and you've already opened a question around this topic.
