### ISSUE TITLE
Add Brute Force Detection Lockout Event

### ISSUE THREAD

**Issue by paulbares** [keycloak/keycloak#8769]
### Description

Trigger an event when the brute force protection detects that the maximum allowed number of login failures is reached for a specific user.

### Motivation

We would like to notify users (via e-mail) whenever their account gets locked up due to excessive failed logins.

Our favoured approach consists of implementing an SPI which listens to a USER_LOCKED event. The event is triggered when the brute force protection detects that the maximum allowed number of login failures is reached for a specific user.

### Details

Original Jira ticket [KEYCLOAK-15985](https://issues.redhat.com/browse/KEYCLOAK-15985)

**Comment by paulbares** [comment]
PR open a week ago linked to this issue.

**Comment by paulbares** [comment]
Any update regarding this issue and the associated PR ?

**Comment by poklakni** [comment]
USER_UNLOCKED would be nice as well
