### ISSUE TITLE
Refreshing a token for temporary disabled users

### ISSUE THREAD

**Issue by nhirsl** [keycloak/keycloak#8770]
### Describe the bug

Token is successfully refreshed for temporary blocked users.
This way, a new access token is received which can be used for accessing the protected API

### Version

15.0.2

### Expected behavior

Refresh token should not return new access token and should throw an error

### Actual behavior

Refreshing token succeeds with new pair of access and refresh tokens.

### How to Reproduce?

1. Setup BFD and configure the users are temporary blocked
2. Use direct grant to login and obtain access and refresh token. Note them down for further usage.
2. Make sure the access token can be successfully used on protected API 
3. Temporary lock user
4. Try to use access token obtained in step one on protected API. Make sure appropriate authorization error is returned
5. Use refresh token on /auth/realms/{realm}/protocol/openid-connect/token to get new access token. This step returns new access token instead of throwing an error.
6. Use newly obtained access token to access protected API.

**Comment by nhirsl** [comment]
It looks like TokenManager#validateToken is missing a BFD check.
The code:
```
String bruteForceError = AuthenticatorUtils.getDisabledByBruteForceEventError(session.getProvider(BruteForceProtector.class), session, realm, user);
if (bruteForceError != null) {
     logger.debugf("Refresh token attempt for user disabled by BFD with error: %s", bruteForceError);
     throw new OAuthErrorException(OAuthErrorException.INVALID_GRANT, "User disabled", "User disabled by BFD");
 }
```
before
```
if (!user.isEnabled()) {
     throw new OAuthErrorException(OAuthErrorException.INVALID_GRANT, "User disabled", "User disabled");
}
```
is preventing to refresh token and returning 400 Bad Request:
```
{
    "error": "invalid_grant",
    "error_description": "User disabled"
}
```

What kind of error description should be returned here?
Is there a need to distinguish between temporary locked by BFD and permanently locked by BFD?

**Comment by nhirsl** [comment]
Hello @mposolda ,
Did you have a chance to take a closer look at the issue?

Can you please advise whether it is OK to return info about status of the user in error description ("User disabled") and whether there's need to distinguish temporary and permanently locked users.

**Comment by nhirsl** [comment]
Hello @mposolda ,
Did you have a chance to take a closer look at the issue? Can we somehow prioritize it?
This can be also considered as a security issue as there's a way for a temporary blocked users to unblock themselves.
PR is updated.
Thanks!

**Comment by nhirsl** [comment]
Hello @stianst @mposolda,
Is there a way for someone to take a look at this issue?
It is a bug we're hitting in production right now and it would be really helpful to prioritize it.
So far, I haven't found a way or workaround to resolve it in client's code. If there is, can you please advise how to do it?

If the PR is not correct, please advise, and I'll update it.
Thanks.

**Comment by nhirsl** [comment]
Hello @mposolda , thanks for the feedback.
The Brute Force Detector concept obviously has some pros and cons. Two main actions: temporary lockout and permanent lockout use the concept of User, thus lockout is always performed on User, not Client or any other concept, afaik.

The documentation (https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/threat/brute-force.adoc) is also clear on this:
"Permanent lockout disables a user account until an administrator re-enables it. Temporary lockout disables a user account for a specific period of time."
As an administrator of the Keycloak I understand this as equivalent states of the User where one is permanent and the other is time limited. No other differences should exist. So, if disabled user cannot refresh tokens, I would expect that temporary disabled user cannot do that either. This is also the understanding of our clients.

So, no matter how many Client sessions are active(valid), the User is locked and it should not be able to do anything until it becomes unlocked. This behavior is consistent with access tokens - they are not usable for locked users no matter if they are permanently or temporary locked (step 5 in steps to reproduce). However, it is inconsistent with refresh tokens.

> In the typical attack, the user is "temporarily disabled" by brute force protector when attacker tries big amount of failed login attempts. This means that attacker will be prevented from further login attempts and he won't be able to guess password by brute force.
> 
> But on the other hand, if there is already some existing valid session of this user, this session was likely valid _before_ the brute-force attack and hence it is the session of valid user, who knows the password. Hence I don't see the reason why this valid session should be prevented from refreshing tokens.

The valid session is already prevented in using already issued access tokens which is OK.
How I understand your position on this is that maybe we (keycloak) should introduce new lockout type - temporary lockout of new sessions - where the user should be able to use already issued access and refresh tokens, but cannot temporary perform new logins?

> If we accept this, it means that anyone is able to do DoS attack to Keycloak to switch users to be "temporarily disabled" and effectively prevent their existing sessions from refresh. Not sure if this not rather "security by obscurity" ?

This is the more the problem with brute force detector than to the type of the lockout. User's access tokens are already unusable. 
Is there anything else we can do to really temporary disable users?

> @nhirsl Do you have some concrete use-case in mind or the reason why "temporarily disabled" users should be prevented from token refresh? AFAIK Brute-Force protector has switch like "Permanent Lockout", which will permanently disable users and then they won't be able refresh tokens (as you expected). Isn't it the option for you to use this switch for your use-case?

Use case we're having is this:
1. Users can use web Client (public, standard flow) to login to portal and perform "actions". For some of these actions, explicit "key authorization" (according to EN 419241-[1|2]) is needed with the crypto material from the user's phone.
2. Users must have mobile application which keeps crypto material for "key authorization" and can login (public, direct grant X.509) to Keycloak
3. Optionally, users can login to other web Clients (public, standard flow) which are integrated for the usage of "actions"

Now, if the BFD detects an attack it locks the user out (temporary) and that's OK. Not a single access token cannot be used anymore. However, we discovered that refresh token bypasses this behavior and the user can continue to use the sessions and unlock the user.

The permanent lockout is vulnerable to DoS attack and as such not very useful in our use case as it requires administrator to unlock the user.
Temporary lockout is, thus, just right, with fixed refresh :)

**Comment by stianst** [comment]
Brute force protection is there to protect against any attempts of guessing a password for an account. When a user is temporarily disabled it should not be able to authenticate again, but existing sessions should still function as normal.

I could see making it possible to invalidate existing sessions when a user account is temporarily disabled, but that should be a configurable thing, and should invalidate sessions rather than checking the BFD on refresh tokens like what is done here, as that will be an additional relatively expensive operation when refreshing tokens.

**Comment by pedroigor** [comment]
The BFD behavior is expected. The original request might be done as an RFE to make it possible to configure whether sessions should be invalidated when the user is temporarily disabled, therefore blocking refresh token requests.

The behavior though can always be supported by a custom BFD provider.
