### ISSUE TITLE
Pre-loaded sessions live forever in cache

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#8776]
### Describe the bug

When offline sessions are preloaded from the database to the cache, entries have no timeout and potentially live forever.

### Version

15.0.2

### Expected behavior

When sessions are preloaded, cache timeout is set based on their expiration.

### Actual behavior

When sessions are preloaded, cache timeout is **NOT** set.

### How to Reproduce?

1. Run a Keycloak server with remote Infinispan (probably the same with embedded) and Postgres db
2. Create some offline sessions 
3. Kill Keycloak and Infinispan servers 
4. Run Infinispan and Keycloak
5. On startup Keycloak preloads offline sessions from DB to the Infinispan cache, however, the sessions seem to have no timeout and therefore live in cache forever. They are correctly removed from the database by [ClearExpiredUserSessions](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/scheduled/ClearExpiredUserSessions.java) scheduled task.

### Anything else?

Originally reported as: https://issues.redhat.com/browse/KEYCLOAK-19417
This was probably introduced in this PR: https://github.com/keycloak/keycloak/pull/7736

**Comment by aberhallo** [comment]
Thanks @mhajas for opening this issue. Regarding your questions from the initial issue KEYCLOAK-19417: 

Q: _"Is it possible that the difference in sessions in cache and database is caused by a keycloak server restart?"_ 
A: As soon as we do a restart there is no gap between the caches anymore for some minutes/hours (depends on the traffic). But after a while the caches start to differ. Hard to say if a restart causes this issue, but shouldn't the gap directly appear after the startup in this case? 

Q: _Do you think you are experiencing the same thing in your environment?_
A:  At least very similar ;-))

Maybe it helps for the root cause analysis that it happend with the update to Keycloak version 13.0.1 (from 12, with <=12 we didn't have this problem).

**Comment by mhajas** [comment]
> A: As soon as we do a restart there is no gap between the caches anymore for some minutes/hours (depends on the traffic). But after a while the caches start to differ. Hard to say if a restart causes this issue, but shouldn't the gap directly appear after the startup in this case?

Sounds the same. The number is the same in the beginning because Keycloak copies all sessions from the database to the cache. However, after some time scheduled task starts to remove expired sessions from the database, but not from the cache.

Also, the difference in the count of sessions between DB and cache should stop increasing after some time (I believe it should be `Offline Session Max` timeout that defaults to 60 days).

> (your comment from KEYCLOAK-19417) As a consequence we expect that in case of a restart the offlines tokens which are only in cache are "lost".

If this issue is really your case, you don't need to worry about losing the sessions when the cache is restarted because you just lose expired sessions that are pretty much useless. Nevertheless, we need to fix this.

> Maybe it helps for the root cause analysis that it happend with the update to Keycloak version 13.0.1 (from 12, with <=12 we didn't have this problem).

This corresponds to suspected Jira that introduced it: https://issues.redhat.com/browse/KEYCLOAK-16755

**Comment by mhajas** [comment]
I did some investigation and the problem is caused [here](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L838). 

Unfortunately, there is no simple solution.  We could replace `putAll` with `put` for each session, however, this could take much longer time as there may be a lot of sessions preloaded. 

It is not possible to use `putAll` and set lifespan for each entry. It is possible to set one lifespan timeout for all of them, so we can set timeout to max expiration time from all sessions, however, this would require to loop through all sessions. Also, in case there are some really long sessions (for example 2 years) all the others will stay in the cache for 2 years even if some of them expired already.

Do you have any other ideas on how to solve this?

**Comment by sre4ever** [comment]
What about using putAll to get all sessions in cache as fast as possible, then making a much slower 2nd pass in the background to set the TTL on individual entries? Otherwise it looks like a case for a feature request in Infinispan.

**Comment by ahus1** [comment]
@mhajas - what about creating exponentially increasing buckets by remaining lifespan instead of one big collection, and then adding the the sessions bucket by bucket. If you start at one second expiration, you'd need 25 buckets for expiration times of up to one year. You could safe some buckets if you would start at 32 seconds.

WDYT?

**Comment by mhajas** [comment]
@ahus1 Sure this would work. However, we should take into account also #9410 PR that is currently sent to the main. I looked at it and it relaxes the issue a little but not fully. It imports the session into the cache only when it is requested. 

Unfortunately, we do not set the lifespan correctly even in this case. It ends up [here](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProvider.java#L310) and uses the same method as with bulk import so it uses `putAll`. 

But we could take advantage of the fact that in the future most of the sessions will be imported one by one, hence we can import it with the correct lifespan.

@martin-kanis Do you have any other input to this?

**Comment by ahus1** [comment]
@mhajas - yes, getting that PR in first would make things a bit simpler. If there is only one session, it could be inserted with the exact remaining time; if there are multiple sessions, they could use the bucket approach. Please let me know if you want to to help out.

**Comment by martin-kanis** [comment]
When preloading is off and offline session(s) are fetched from a DB it actually inserts sessions to the cache one by one see `session.sessions().importUserSessions(Collections.singleton(persistentUserSession), offline)` and notice the singleton part. For this case we can check size of `persistentUserSessions` collection inside `importUserSessions` and if it's 1 we can use put instead of putAll. This might fix it at least for lazy loading variant which will be default soon.

**Comment by ahus1** [comment]
@martin-kanis - +1 for that approach to use put with the exact timespan for single entries. Using buckets could then be a future iteration, let's keep PRs small.

**Comment by giacomoa** [comment]
> When preloading is off and offline session(s) are fetched from a DB it actually inserts sessions to the cache one by one see `session.sessions().importUserSessions(Collections.singleton(persistentUserSession), offline)` and notice the singleton part. For this case we can check size of `persistentUserSessions` collection inside `importUserSessions` and if it's 1 we can use put instead of putAll. This might fix it at least for lazy loading variant which will be default soon.

I agree with this solution; just want to focus the fact that also maxIdle (and not only lifespan) need to be handled in this approach; maxIdle should be calculated from realm's "Offline Session Idle" and lifespan from realm's "Offline Session Max" (if enabled).

Finally, as work-around, while waiting for the fix, we are thinking about setting maxIdle and lifespan in both offlines cache configuration in standalone(-ha).xml defaulting to the keycloak realm settings applied ("Offline Session Idle" and "Offline Session Max").

**Comment by mhajas** [comment]
@martin-kanis Thanks for the confirmation. I like this solution.

On the other hand, I am not sure about the addition of session preloading in buckets. I am not sure it is worth the effort at the moment. I would probably vote to split this issue into two, first for the check for the `singleton` and using `put` instead of `putAll` and the second for the introduction of preloading sessions using buckets with the higher priority on the first one.

@giacomoa Thank you for the addition, you are right. 

Yes, this can be used as a temporary work-around, however, it is not the best long-term solution as there can potentially be a lot of expired sessions in the cache if idle/max values are too high and the changes in realm settings are not propagated there.

**Comment by zhandospdf** [comment]
I was looking into `RemoteCacheSessionsLoader` and it seems to have same issue ?
It also uses `putAll`:
https://github.com/keycloak/keycloak/blob/0ce5dfc09ce1d942de1ffba43c05386df4a296dd/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheSessionsLoader.java#L144

Should I create a new issue for this ?
