### ISSUE TITLE
Classloader theme resources don't get reloaded on deploy

### ISSUE THREAD

**Issue by raulruizbarea** [keycloak/keycloak#8780]
### Describe the bug

More information https://issues.redhat.com/browse/KEYCLOAK-17767
Discussion: https://keycloak.discourse.group/t/old-theme-resources-are-loaded-even-after-restart-due-to-theme-caching/8413

### Version

13

### Actual behavior

When theme caching is enabmed, after deploying a new theme through classloader, the old resource files are still being fetched by browsers, even on hard refresh. When fetching the resource with curl, the new version is returned.

DefaultThemeManagerFactory::themeCache gets cleared on each deploy, but the old files from GzipResourceEncodingProviderFactory::cacheDir get loaded, since this directory isn’t re-initialized until a full server reboot.

Curl doesn’t pass the Accept-Encoding header, but the browser does (by default). When this header’s value contains “gzip”, the GzipResourceEncodingProvider will be used, which doesn’t reload the gzip directory on deploy. If this header isn’t present, like in curl, ClassLoaderTheme::getResourceAsStream is called which returns the new file.

**Comment by waldemarennsaed** [comment]
This issue still exists and is pretty annoying, no hot development possible. Old theme files are still being loaded until I restart keycloak.

**Comment by stianst** [comment]
A workaround to this is to disable the gzip compression, at least during development. The proper fix here is really to have some way of versioning custom theme resources, which can adapt to modified themes, so there's no issues with caching/gzip/etc.

**Comment by waldemarennsaed** [comment]
@stianst what are the steps to disable gzip on keycloak? Or is it just the solution concept for this issue?

**Comment by stianst** [comment]
> @stianst what are the steps to disable gzip on keycloak? Or is it just the solution concept for this issue?

Looking at the code now if cacheThemes is false then gzip should be disabled as well. You can also explicitly disable it by disabling the gzip provider for resource-encoding SPI.

**Comment by waldemarennsaed** [comment]
But that's the whole point of this issue: Disabling `cacheThemes` doesn't work:

```xml
<theme>
    <staticMaxAge>-1</staticMaxAge>
    <cacheThemes>false</cacheThemes>
    <cacheTemplates>false</cacheTemplates>
    ...
</theme>
```

(copied from the [docs](https://www.keycloak.org/docs/latest/server_development/#creating-a-theme))

It still caches the theme-files until I restart the keycloak container/instance.

**Comment by stianst** [comment]
> > Looking at the code now if cacheThemes is false then gzip should be disabled as well.
> 
> But that's the whole point of this issue: Disabling `cacheThemes` doesn't work:
> 
> ```
> <theme>
>     <staticMaxAge>-1</staticMaxAge>
>     <cacheThemes>false</cacheThemes>
>     <cacheTemplates>false</cacheTemplates>
>     ...
> </theme>
> ```
> 
> (copied from the [docs](https://www.keycloak.org/docs/latest/server_development/#creating-a-theme))
> 
> It still caches the theme-files until I restart the keycloak container/instance.

That's rather strange:

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/ThemeResource.java#L65

https://github.com/keycloak/keycloak/blob/7bef5343928777b467a41816fde377bc59e62584/services/src/main/java/org/keycloak/theme/DefaultThemeManagerFactory.java#L37-L39

If cache is disabled it shouldn't do gzip at all.

**Comment by raulruizbarea** [comment]
A way to "fastly" develop and test a theme can be using rm -r /opt/jboss/keycloak/standalone/tmp/kc-gzip-cache 

A big **BUT**: Be careful because you will be losing changes that you performed in the client, users, ...

**Comment by waldemarennsaed** [comment]
> If cache is disabled it shouldn't do gzip at all.

@stianst  Okay, maybe there was a misunderstanding. Disabling cache, does not help me with "hot development" in terms of changing theme files to being directly visible on page-reload in the keycloak UI (e.g. login page). I still have to restart my keycloak service.

If caching themes is really bound to gzip, then I would say _disabling caching does not disable gzip_ -  a wild guess of mine.

> A big BUT: Be careful because you will be losing changes that you performed in the client, users, ...

What do you mean by that @raulruizbarea ?

**Comment by waldemarennsaed** [comment]
> If you add an email to a User and then you apply the rm of the "kc-gzip-cache" + reload keycloak, that email would be empty again.

Okay I See. I will test your solution and if it works, I might be able to write a little script that always deletes the folder when it notices changes in specific files - may in combination with git, that could be a nice development-workaround.

**Comment by ad9999** [comment]
Is there any update on this issue ? I have tried different approaches like updating standalone.xml, removing tmp directory and restarted but no luck

**Comment by ad9999** [comment]
Something weird I am noticing is that the changes into template file (i.e. *.ftl) are visible immediatly on page refresh but the CSS changes are the only one driving me crazy

**Comment by bmenant** [comment]
Ran into a similar issue as I was following the step-by-step guide under [server_development/#creating-a-theme](https://www.keycloak.org/docs/latest/server_development/index.html#creating-a-theme).

Contrary to what says the documentation, using a containerized development environment (as described [above](https://github.com/keycloak/keycloak/issues/8780#issuecomment-982704171); I use a very similar setup with podman), it seems we also need to restart the service after a change in a `theme.properties` file.

> To see the effect of changing the parent theme, set parent=keycloak in theme.properties and refresh the login page.

I refreshed the login page a couple of times, flushed all the caches and all... but the login page was still looking like the plain base theme. The documentation was so assertive it took me a while to figure it out. I checked the files were properly updated in the container... I checked I didn’t make a typo in `parent=keycloak`... until I finally restarted the container and realize it miraculously wasn’t a mistake of mine.

@waldemarennsaed did you find a way to dynamically refresh assets cache, finally?

**Comment by waldemarennsaed** [comment]
@bmenant not yet - except for my suggestion of a little script we could use for now. I will try to write a simple one this week and will keep you updated.

**Comment by bmenant** [comment]
@waldemarennsaed Ok. I basically set up file watchers in my IDE. It helps.

- When any file is changed in my local custom theme directory, excluding `*.properties`, then run `podman exec keycloak rm -rf /opt/jboss/keycloak/standalone/tmp/kc-gzip-cache/tyvrz/account/my-custom-theme`
- When any `*.properties` file is changed in my local custom theme directory, then run `podman restart keycloak` (using a distinct container for the database, makes restart a little bit faster/safer)

However, it definitively looks like something is wrong in this workflow. Maybe some specific configuration is added to container image builds? Like a default environment variable or configuration file that would override the deactivation of the cache in the `standalone.xml` file?

**Comment by bmenant** [comment]
Ok, I think I’ve found out why!

Apparently, by default, the image [entrypoint](https://github.com/keycloak/keycloak-containers/blob/main/server/tools/docker-entrypoint.sh#L102) loads the HA profile. 

I should have RTMF, since they mention it [over here](https://github.com/keycloak/keycloak-containers/tree/main/server#running-custom-scripts-on-startup): 

> It's also worth to mention, that by default, keycloak uses standalone-ha.xml configuration (unless other server configuration is specified).

BTW, this very line should stand out more... It’s in a section called “Custom scripts” with a big “Warning: Custom scripts have no guarantees.” At a glance, I instantly skipped the section, and missed the HA profile by default thing.

So, to make it sure, I turned off my IDE file watchers things and edited the `standalone-ha.xml` to apply the same settings:

```xml
            <theme>
                <staticMaxAge>-1</staticMaxAge>
                <cacheThemes>false</cacheThemes>
                <cacheTemplates>false</cacheTemplates>
                ...
            </theme>
```

Since then, it doesn’t take a container restart any more! The changes I made in css or properties files where reflected in my browser _instantly_, and `/opt/jboss/keycloak/standalone/tmp/kc-gzip-cache` remains (almost) empty. 

Turned out it was that simple. :smiley: 

Now, just let’s find out how to **not** load the HA profile...

**Comment by waldemarennsaed** [comment]
> Ok, I think I’ve found out why!
> 
> Apparently, by default, the image [entrypoint](https://github.com/keycloak/keycloak-containers/blob/main/server/tools/docker-entrypoint.sh#L102) loads the HA profile.
> 
> I should have RTMF, since they mention it [over here](https://github.com/keycloak/keycloak-containers/tree/main/server#running-custom-scripts-on-startup):
> 
> > It's also worth to mention, that by default, keycloak uses standalone-ha.xml configuration (unless other server configuration is specified).
> 
> BTW, this very line should stand out more... It’s in a section called “Custom scripts” with a big “Warning: Custom scripts have no guarantees.” At a glance, I instantly skipped the section, and missed the HA profile by default thing.
> 
> So, to make it sure, I turned off my IDE file watchers things and edited the `standalone-ha.xml` to apply the same settings:
> 
> ```
>             <theme>
>                 <staticMaxAge>-1</staticMaxAge>
>                 <cacheThemes>false</cacheThemes>
>                 <cacheTemplates>false</cacheTemplates>
>                 ...
>             </theme>
> ```
> 
> Since then, it doesn’t take a container restart any more! The changes I made in css or properties files where reflected in my browser _instantly_, and `/opt/jboss/keycloak/standalone/tmp/kc-gzip-cache` remains (almost) empty.
> 
> (For myself: just add the arg `-c standalone.xml` to the podman/docker run command to **not** use HA profile).

Works like a charm!!! I wonder if this might be composed with something like ViteJS & Vue for a perfect DX 🤓

**Comment by waldemarennsaed** [comment]
FYI:

**docker-compose.yml**
```docker-compose.yaml
version: '3'
services:
  keycloak:
    image: jboss/keycloak:11.0.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8085:8080
    volumes:
      - ./my-theme/:/opt/jboss/keycloak/themes/my-theme
      - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
    networks:
        - dnet
 
networks:
  dnet:
```

**standalone.xml**
```xml
<theme>
                <staticMaxAge>-1</staticMaxAge>
                <cacheThemes>false</cacheThemes>
                <cacheTemplates>false</cacheTemplates>
                ...
            </theme>

```

Using `CMD+R` for reloading to see the changes.

**Comment by pedroigor** [comment]
The way themes are deployed to the server changed significantly. The server no longer supports hot deployment of any kind of provider.

See https://www.keycloak.org/server/configuration-provider.
