### ISSUE TITLE
GroupRepresentation object returned when creating a Group using the API

### ISSUE THREAD

**Issue by coelias** [keycloak/keycloak#8781]
### Description

When creating a new group using the API, the content of the HTTP response is currenty empty. There is no clue of the id of the object created, a new request is needed to retrieve information about the group.

### Motivation

This feature will avoid multiple requests when a group is created. Plus if there are many groups in the system, fetching them can be very slow.

**Comment by stianst** [comment]
The id is included in the HTTP Location header. I know this is not ideal, but it is the way our APIs was designed. Closing this as we won't change this behaviour in the current version of the API, but will for sure improve on this in an updated version of the Admin API when we get around to doing that.
