### ISSUE TITLE
When trigger the TokenVerifier the exp and iat inside the token returned by Keycloak is too closed to each other

### ISSUE THREAD

**Issue by sonnb** [keycloak/keycloak#8789]
### Describe the bug

While the PolicyEnforcer is being triggered (Via RestClient),  AdapterTokenVerifier is trying to verify the token, it uses the token in the header as subjectToken and send those data to Keycloak to get for the AuthorizationResponse. But for some reason, the exp and iat of the token returned by the method

```
public AuthorizationResponse authorize(final AuthorizationRequest request) throws AuthorizationDeniedException {
```

is very closed to each other. In some case, exp is equals to iat. Therefore when TokenVerifier trying to verify that token, the token is already expired and we get "Token is not active" and the client gets 403 response.

### Version

15.0.2

### Expected behavior

The Token verify should not fail because the token sent by the client is still 60s from the expiration time. Currently we do a ugly check to avoid the 403 issue:

```
// Extend lifetime if it is going to be expired soon
if (tokenVerifier.getToken().getExp() - tokenVerifier.getToken().getIat() <= 30) {
    tokenVerifier.getToken().exp(tokenVerifier.getToken().getExp() + 30);
}
```

### Actual behavior

TokenVerify said that token is expired/inactive so the request cannot be completed

### How to Reproduce?

Quarkus 2.3.0.Final

Access Token Lifespan: 1 minute
Client Session Idle: 1 minute
Client Session Max: 1 minute

Do a loop which sent lot of REST requests from `service A` to `service B`. Use `ClientRequestFilter` to generate token using OidcClients, make sure token is refreshed before it expires with `refresh-token-time-skew` settings. After 1 minute, the PolicyEnforcer check on `Service B` will randomly failed.

### Anything else?

Is there any reason for the following code returns a very short exp time?

```
 return method
              .authentication()
              .uma(request)
              .response()
              .json(AuthorizationResponse.class)
              .execute();
```

Is there any settings on Keycloak which can extend that?

**Comment by pedroigor** [comment]
@sonnb The expiration time should be based on the access token lifespan set to your realm or client. I'm not sure why that might be happening.

Do you have a reproducer?

**Comment by sonnb** [comment]
@pedroigor I am working on an example and will post here soon.

**Comment by pedroigor** [comment]
@sonnb Thanks. It is kind of weird that expiration is set like that. I need to debug ...

**Comment by sonnb** [comment]
@pedroigor I afraid that the problem I had here related to the AuthenticationFilter I wrote. In that filter I use both user token (whether it is available) and the manual token (when user token is not available), and by some reasons, it will use the user token which was expired in the case the manual token is expected to be sent. I think this is not the bug of Keycloak itself.
