### ISSUE TITLE
Parameter 'matchingUri' only applies to resources owned by client, not by users

### ISSUE THREAD

**Issue by MarkusRohlof** [keycloak/keycloak#8792]
### Describe the bug

When I use `GET authz/protection/resource_set` with `matchingUri=true`, then pattern matching will only be applied correctly to resources that are owned by the requesting client (that is, my resource server).

When I try to find resources owned by a user, that same logic will not work.

I suspect this line to be the culprit, where the resource server ID is used as a Filter: https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/authorization/admin/ResourceSetService.java#L421 

### Version

15.0.2

### Expected behavior

A resource with the URI `/api/company/*` and any user of the realm as owner should be returned by the following request:

```
curl --request GET \
  --url 'http://localhost:8081/auth/realms/my-realm/authz/protection/resource_set?uri=/api/company/123&matchingUri=true' \
  --header 'Authorization: Bearer {bearer}'
```

### Actual behavior

The resource only gets returned when the owner is the client. 

### How to Reproduce?

Create a user-owned resource like so:

```
curl --request POST \
  --url http://localhost:8081/auth/realms/my-realm/authz/protection/resource_set \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer {token}' \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "Company owned by user",
	"owner": "any-existing-user",
	"uris": [
		"/api/company/*"
	]
}'
```

Execute the GET request shown above. No resource will be returned.

**Comment by pedroigor** [comment]
@MarkusRohlof This is by design so that we search the whole database for resources. It is a costly operation.

Perhaps we can add a new parameter to indicate the intention and also include resources owned by users, as a fallback mechanism.

Are you willing to contribute with the changes?

**Comment by pedroigor** [comment]
Please, let us know if you want to help us with this one.
