### ISSUE TITLE
"Backchannel Logout URL" and "Admin URL"/k_logout don't both work

### ISSUE THREAD

**Issue by pmorch** [keycloak/keycloak#8798]
### Describe the bug

Originally [[KEYCLOAK-16677] "Backchannel Logout URL" and "Admin URL"/k_logout don't both work - Red Hat Issue Tracker](https://issues.redhat.com/browse/KEYCLOAK-16677):

* Create a client with an "Admin URL" setting
* Login+Logout and see that $adminURL/k_logout is POSTed to
* Now create a "Backchannel Logout URL" also, leaving "Admin URL" as-is
* Login+Logout and see that oly $backchannelLogoutURL is POSTed to
    * I expected both to be called
    * Or that the GUI prevents me from entering both
* Removing "Backchannel Logout URL"  again does not help, now none of them ar called, even though the configuration looks exactly like the first step. This is perhaps related to KEYCLOAK-16676
* It was not possible for me to get $adminURL/k_logout working again, other than deleting the client and recreating it.

And sure, this may not be high priority, since $adminURL/k_logout presumably is on the deprecation path. There is no indication of that in the GUI, though....

### Version

12.0.1

**Comment by pedroigor** [comment]
Logout support has changed significantly since then. The issue no longer can be reproduced using the latest versions.
