### ISSUE TITLE
Convert map entities to interfaces

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#8809]
### Description

https://issues.redhat.com/browse/KEYCLOAK-18731
Currently, Map*Entity classes are concrete classes. To be generally usable, these should be interfaces. This task is to convert them all to the interfaces

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17408

### Issues

- #8807
- #8808
- #8979
- #8973
- #9657
- #9736
- #9737
- #9738
- #9739
- #9740

**Comment by vramik** [comment]
- https://github.com/keycloak/keycloak/issues/9657
