### ISSUE TITLE
Official Support for Microsoft mobile authenticator app

### ISSUE THREAD

**Issue by johgoe** [keycloak/keycloak#8820]
### Description

I just test mobile authenticator app from Microsoft with TOTP and keycloak and it seems working fine, without any changes.

The link to the product is
https://www.microsoft.com/en-us/security/mobile-authenticator-app

As google authentificator is already part of the official documentation, I guess it's helpful to add another product to documentation, so everybody can choose, which company has more trust for the TOTP application.

**Comment by danvy** [comment]
Hi @johgoe , I created a PR for that https://github.com/keycloak/keycloak/pull/13537

**Comment by johgoe** [comment]
Fixed by https://github.com/keycloak/keycloak/pull/15272
