### ISSUE TITLE
Multi-arch container image for Quarkus distribution (amd64 + arm64)

### ISSUE THREAD

**Issue by Theoderich** [keycloak/keycloak#8825]
### Description

(copied from JIRA issue)
The current Keycloak docker image doesn't contain an arm64 build in the manifest but the base image used is built for arm64.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17359

### Motivation

This is becoming more important now we have the Apple M1 chipset and also given that cloud providers are also providing ARM based hosting options, would be great if you can start pushing an arm64 build so users like me don't need to build it themselves.

**Comment by jangaraj** [comment]
Discussion: https://github.com/keycloak/keycloak/discussions/8846

**Comment by stianst** [comment]
We will provide arm64 images for the new Quarkus distribution. However, we're right in the middle of planning a bigger change to our release process, so not sure exactly when we can deliver it, but will try to get it done asap.

**Comment by jaap3** [comment]
In case anyone else was wondering where these new images can be found (they are not on docker hub).

They are here:

https://quay.io/repository/keycloak/keycloak?tab=tags

**Comment by iyobo** [comment]
So how do we reference this in docker? 

https://quay.io/repository/keycloak/keycloak?tag=xxx ??
