### ISSUE TITLE
`ui_locales` query parameter is ignored when `kc_idp_hint` is set

### ISSUE THREAD

**Issue by vilmosnagy** [keycloak/keycloak#8827]
### Describe the bug

When trying to set the locale for KeyCloak and hint which IDP to use, KeyCloak ignores the `ui_locales` hint.

### Version

15.0.2

### Expected behavior

KeyCloak should respect the `ui_locales` hint when the user gets redirected from the IdentityProvider's site.

For example when this is the first time the user logs in, and they need to verify their e-mail address.

### Actual behavior

When the `kc_idp_hint` parameter is set KeyCloak disrespects the `ui_locales` parameter.

### How to Reproduce?

 - Start a local KeyCloak instance. Configure at least 2 locale-s in your instance (I've used English and Hungarian)
 - Configure any Identity Provider (I used google). Set the realm's settings to require email verification
 - Open the https://www.keycloak.org/app/, and enter the credentials. Click the _Save_ btn.
 - put a breakpoint in `keycloak.js` at the 502th line.
 - Append the `kc_idp_hint=google&ui_locales=hu` to the variable `url`. (Or any Locale which is not your system's locale)
 - Continue the execution
 - Continue with the login process
 - the _verify your e-mail address_ will be shown to you in your system's locale.

**Comment by vilmosnagy** [comment]
I'm willing to submit a PR, if you could help me a bit.

My plan is to:
 - save the value of the `ui_locales` queryparameter to _somewhere_ in the `IdentityProviderAuthenticator::redirect` method
 - change the `DefaultLocaleSelectorProvider::getUserLocale`
   - somewhere after the `getClientSelectedLocale` method call we should check for the previously saved locale preference
   - and return that if that's not null

What I'm not sure about is where to save this value in the `IdentityProviderAuthenticator`. Is the `clientNotes` a good place for this? Or? It seems to me that the `authenticationSession` will be a different instance before we redirect the user to the IDP and after -> so the `authNotes` are lost.

**Comment by mposolda** [comment]
This is low priority and Keycloak team likely won't have time to actively look at this. So the PR would be welcome.

I see that uiLocales is already set to clientNotes in the authentication session. So it is the question why it is not seen after redirect from IDP authentication back to Keycloak. After redirect from IDP back to Keycloak, it will be ideal if same authenticationSession is used, which was used for redirect from Keycloak to IDP at the beginning of the authentication.

Another possibility is, that same authenticaitonSession is used, but the page for `verify email address` ignores the ui_locales set in the authentication session. It will be good to investigate this. Hopefully you can figure it and provide the PR. Good luck!

**Comment by mposolda** [comment]
There is Keycloak JIRA https://issues.redhat.com/browse/KEYCLOAK-19128 which is related to this (Maybe it is exactly same bug as this one, but not 100% sure).

**Comment by vilmosnagy** [comment]
@mposolda as far as I understand after some hours of debugging, KeyCloak clears all the `authSessionNotes` with the following call at `IdentityBrokerService:586` ([source code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/IdentityBrokerService.java#L586)):

```java
            // Redirect to firstBrokerLogin after successful login and ensure that previous authentication state removed
            AuthenticationProcessor.resetFlow(authenticationSession, LoginActionsService.FIRST_BROKER_LOGIN_PATH);
``` 

And the `AuthenticationProcessor::resetFlow` method clears everything from the `AuthenticationSession`:

```java
    public static void resetFlow(AuthenticationSessionModel authSession, String flowPath) {
        logger.debug("RESET FLOW");
        authSession.getParentSession().setTimestamp(Time.currentTime());
        authSession.setAuthenticatedUser(null);
        authSession.clearExecutionStatus();
        authSession.clearUserSessionNotes();
        authSession.clearAuthNotes();

        authSession.setAction(CommonClientSessionModel.Action.AUTHENTICATE.name());

        authSession.setAuthNote(CURRENT_FLOW_PATH, flowPath);
    }
```

According to my tests if we would save the value of the `LocaleSelectorProvider.CLIENT_REQUEST_LOCALE` authNote _before_ the `clearAuthNotes` call, and re-set it again _after_ the `clearAuthNotes` call, the locale selection would work fine.

Do you have any better idea than this? If so where should I look?

Thanks,
Vilmos

**Comment by stianst** [comment]
I don't think this issue is even valid. Why are you setting kc_idp_hint? That is not supposed to be set by applications, and should only be used internally within KC to switch the locale when the user explicitly does so, which should take precedence over ui_locales.

**Comment by vilmosnagy** [comment]
@stianst 

> I don't think this issue is even valid. Why are you setting kc_idp_hint? That is not supposed to be set by applications,

It's in the [documentation](https://www.keycloak.org/docs/latest/securing_apps/index.html) that I can set it, see: 

> * `kc_idp_hint` - Used to tell Keycloak to skip showing login page and automatically redirect to specified identity provider instead. More info in the Identity Provider documentation._

I'm not sure about `ui_locales`, but it's in the KeyCloak docs [1], and in the [OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) as well.

The use-case in our situation for the `kc_idp_hint` parameter is the following: one of our native clients wants to show the Google/Facebook/etc. buttons in the native screen, and they would like to start the login process on the Google screen instantly.

[1]:
> Sets the 'ui_locales' query param in compliance with section 3.1.2.1 of the OIDC 1.0 specification.

**Comment by stianst** [comment]
You're correct. I misread and was thinking about kc_locale, the kc_idp_hint is a different thing of course. This seems to be a valid bug, so ignore my previous comment.

**Comment by vilmosnagy** [comment]
Is it possible, that the `referrer` & `referrer_uri` query parameters are lost if I do an IDP linking on the account manager UI, because of the same issue?

**Comment by vilmosnagy** [comment]
@mposolda would you merge a PR, if I'd do the changes described here:
https://github.com/keycloak/keycloak/issues/8827#issuecomment-975252759

**Comment by vilmosnagy** [comment]
@mposolda @stianst I've created the PR :wink:

**Comment by kanguran** [comment]
What is needed to merge this PR to next Release ?  We have the same issue in place.

**Comment by mposolda** [comment]
@kanguran @vilmosnagy I've replied on the PR. Sorry for the late review.

**Comment by kanguran** [comment]
Could you include this PR to 19.0.2 so we could go Live quicker ?

**Comment by mposolda** [comment]
@kanguran those patch releases are dedicated usually to more critical fixes/regressions, which this bugfix is not. If you want this quicker, you can possibly consider latest Keycloak nightly release?

**Comment by kanguran** [comment]
Hello

@douglaspalmer  I have found 1 more issue related to Locales in V20.

authSession.getAuthenticatedUser() .... gives null in LocaleUtil.java in case of first-broker-loggin on Keycloak V20.0.1 and 20.0.2
it used to work well on 19th version once we got Vilmos Nagy fix merged.

user model is null and UI locale is dropped to Default locale (EN).


```
Map<String, String> extractedAuthNotes = extractAuthNotesFromSession(authenticationSession);
// Redirect to firstBrokerLogin after successful login and ensure that previous authentication state removed
AuthenticationProcessor.resetFlow(authenticationSession, LoginActionsService.FIRST_BROKER_LOGIN_PATH);
extractedAuthNotes.forEach(authenticationSession::setAuthNote);

// I made hotfix in IdentityBrokerService.authenticated() for that Error by calling LocaleUtil.processLocaleParam
LocaleUtil.processLocaleParam(session, realmModel, authenticationSession);
```

@vilmosnagy Have you tried to update your Keycloak to V20? Any issues with that ?

Next, I will try to repeat this issue by running plain Keycloak locally and provide Keycloak Test scenarios to repeat Locale Errors.
