### ISSUE TITLE
Quarkus version

### ISSUE THREAD

**Issue by nury-garryyev** [keycloak/keycloak#8841]
### Description

I am working on a custom SPI related to JPA. I ran into a problem while deploying this SPI in Keycloak.X due to the Quarkus version. Older version of Quarkus does not support mapping-file in persistence.xml and orm.xml. I saw that you have updated the Quarkus version in Keycloak version 16. Could you please update it in the current Keycloak version 15.0.2 as well?

**Comment by stianst** [comment]
Updated Quarkus version will only be available in Keycloak 16, as we won't do any further releases of 15.0
