### ISSUE TITLE
Client mapper doesn't override existed claim

### ISSUE THREAD

**Issue by VerdonTrigance** [keycloak/keycloak#8842]
### Describe the bug

Previously I was using keycloak 12. Everything works fine.

I have User custom attribute with name 'email2' and also default property 'email'.
![image](https://user-images.githubusercontent.com/12109173/142162085-7feba053-559a-4527-a7da-482e93a3b8cd.png)

The real user's email is stores in that custom attribute. 
I created a custom mapper in my specific client and map 'email2' attribute to 'email' claim:
![image](https://user-images.githubusercontent.com/12109173/142161880-2d6dcb50-de3f-4dd2-bbea-2754fdaa5cea.png)

In email claim was my custom attribute and it was what I needed:
![image](https://user-images.githubusercontent.com/12109173/142163292-c26070a4-26af-4667-a9f5-ad00bdf46eef.png)

But in version 14 I faced with the problem.
Same thing not working. I have same custom user attribute, same custom mapper that maps 'email2' to 'email' claim, and same user. But now email claim in token contains default email user's property:
![image](https://user-images.githubusercontent.com/12109173/142163497-afab2f43-b4a5-4e37-a91b-40496e1ed9bc.png)

There are no other mappers that may change this claims. Mappers' order is also same.

### Version

14.0.0

### Expected behavior

As described previously in version 12:

claim in token contains 'email' value mapped from 'email2' user custom attribute.

### Actual behavior

Claim in token contains value mapped from default email mapper (default user's email property).

### How to Reproduce?

Create custom user attribute 'email2'
Create client mapper that maps 'email2' attribute to 'email' claim.
Run evaluate to see token.

**Comment by pedroigor** [comment]
The issue no longer can be reproduced using the latest versions.
