### ISSUE TITLE
[keycloak 15.0.2] Offline session couldn't load on admin page

### ISSUE THREAD

**Issue by hvhung** [keycloak/keycloak#8845]
### Describe the bug

Error when search offline session in admin page when it has data.

Keycloak upgrading from 4.6.0 to 15.0.2
Database: Postgres
The total offline session items around 13k

### Version

15.0.2

### Expected behavior

Can load offline session without error

### Actual behavior

1. Using admin page: Failed several time, waiting around 30 seconds then we could search again (the time is not specific)
2. Using API: failed 2 times with different errors

### How to Reproduce?

1.  The 1st approach: using admin UI:
- Login to keycloak admin as admin user.
- Change to a realm that has client exist
- Choose specific client that has offline sessions
- Search offline session

2.  The 2nd approach: using API: /auth/admin/realms/{{realm-name}}/clients/{{client-uuid}}/offline-sessions?first=0&max=5
- Login as admin
- Use API to search offline sessions with the client has offline sessions

### Anything else?

I did try to call API to search 1 by 1, there is no error; but the error occurred when i search more than 2.
When you could search without error, need to restart keycloak to reproduce.

Here is the error log
[keycloak_15.0.2_offline_sessions.txt](https://github.com/keycloak/keycloak/files/7553601/keycloak_15.0.2_offline_sessions.txt)

**Comment by pedroigor** [comment]
Offline session support has changed significantly since then. The issue no longer can be reproduced using the latest versions.
