### ISSUE TITLE
[keycloak 15.0.2] [Adapter] - [Spring.Boot 2.6] - Application don't start because of Circular Reference due to dependency injection

### ISSUE THREAD

**Issue by svanacker** [keycloak/keycloak#8857]
### Describe the bug

When using Keycloak 15.0.2 with Spring.Boot 2.6 (released 19 November 2021), the application failed to start with the following description:
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  webMvcKeycloakSecurityConfigurerAdapter (field private org.keycloak.adapters.KeycloakConfigResolver org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter.keycloakConfigResolver)
└──<-──┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

By using the workaround (spring.main.allow-circular-references to true), the application start successfully

### Version

15.0.2

### Expected behavior

The application must start even if we do not set spring.main.allow-circular-references to true

### Actual behavior

Crash of the application

### How to Reproduce?

Use Keycloak security adapter 15.0.2 with Spring.Boot 2.6.0 (with spring.main.allow-circular-references no set or set to false)

**Comment by anthonyraymond** [comment]
## Why?
It most likely happens because you are defining a `KeycloakConfigResolver` in a subclass of 
 `KeycloakWebSecurityConfigurerAdapter`

something like this:
```java
@KeycloakConfiguration
@EnableGlobalMethodSecurity(
    securedEnabled = true,
    jsr250Enabled = true,
    prePostEnabled = true
)
public static class MyWebSecurityConfigurerAdapter extends KeycloakWebSecurityConfigurerAdapter {
    @Autowired
    public MyWebSecurityConfigurerAdapter() {
    }

    @Bean
    public KeycloakConfigResolver KeycloakConfigResolver() {
        return new KeycloakSpringBootConfigResolver();
    }

    // https://www.keycloak.org/docs/latest/securing_apps/#avoid-double-bean-registration
    @Bean
    public FilterRegistrationBean<KeycloakAuthenticationProcessingFilter> keycloakAuthenticationProcessingFilterRegistrationBean(final KeycloakAuthenticationProcessingFilter filter) {
        final FilterRegistrationBean<KeycloakAuthenticationProcessingFilter> registrationBean = new FilterRegistrationBean<>(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @Bean
    public FilterRegistrationBean<KeycloakPreAuthActionsFilter> keycloakPreAuthActionsFilterRegistrationBean(final KeycloakPreAuthActionsFilter filter) {
        final FilterRegistrationBean<KeycloakPreAuthActionsFilter> registrationBean = new FilterRegistrationBean<>(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @Bean
    public FilterRegistrationBean<KeycloakAuthenticatedActionsFilter> keycloakAuthenticatedActionsFilterBean(final KeycloakAuthenticatedActionsFilter filter) {
        final FilterRegistrationBean<KeycloakAuthenticatedActionsFilter> registrationBean = new FilterRegistrationBean<>(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }

    @Bean
    public FilterRegistrationBean<KeycloakSecurityContextRequestFilter> keycloakSecurityContextRequestFilterBean(final KeycloakSecurityContextRequestFilter filter) {
        final FilterRegistrationBean<KeycloakSecurityContextRequestFilter> registrationBean = new FilterRegistrationBean<>(filter);
        registrationBean.setEnabled(false);
        return registrationBean;
    }
}
```

## Quick Fix

Getting the bean declaration out of the `MyWebSecurityConfigurerAdapter` class solve the issue
```java
@Bean
public KeycloakConfigResolver KeycloakConfigResolver() {
    return new KeycloakSpringBootConfigResolver();
}
```

## Why
`KeycloakWebSecurityConfigurerAdapter` has an injected field of type `KeycloakConfigResolver`, and if you define the bean in a subclass of `KeycloakWebSecurityConfigurerAdapter` it creates a circular dependency

**Comment by ianwallen** [comment]
The reason we use the KeycloakConfigResolver bean is so that our configuration comes from the properties files instead of the keycloak.json file.  So removing the following

```java
@Bean
public KeycloakConfigResolver KeycloakConfigResolver() {
    return new KeycloakSpringBootConfigResolver();
}
```

generated the following error.

`Unable to locate Keycloak configuration file: keycloak.json`

**Comment by anthonyraymond** [comment]
I use it as well i didn't meant to remove it.
I mean that you have to move the bean declaration somewhere else, not in the `MyWebSecurityConfigurerAdapter`

**Comment by fo0** [comment]
@ianwallen 

just create a configuration class like: 

``` java
@Configuration
public class KeycloakResolverConfig {
  @Bean
  public KeycloakConfigResolver myKeycloakConfigResolver() {
      return new KeycloakSpringBootConfigResolver();
  }
}
```

if you still need to interact with the class you can access it via `@Autowired KeycloakConfigResolver resolver`

I think this is what @anthonyraymond mentioned and I understood :)

**Comment by mspasiano** [comment]
I have the same problem with spring boot 2.6.6 and keycloak 17.0.1, but even moving the bean declaration to another file the problem persists, and I was forced to insert
spring:
     main:
         allow-circular-references: true
As you can see here https://github.com/consiglionazionaledellericerche/cool-jconon/blob/538d5d0cee134c995835664ba3ddd82bd7e50fb9/cool-jconon-keycloak/src/main/resources/config/application-keycloak.yaml#L24
