### ISSUE TITLE
Incomplete translation for German locale

### ISSUE THREAD

**Issue by msts1906** [keycloak/keycloak#8860]
### Describe the bug

There is a missing translation for the German locale. The message "Invalid email address." is shown in English although everything else is displayed correctly in German.

### Version

15.0.0, 17.0.0

### Expected behavior

The error message is shown in German. Something similar to "Geben Sie bitte eine valide E-Mail ein."

### Actual behavior

The error message displays: "Invalid email address."

### How to Reproduce?

Activate Internationalization. Choose "de" as default. Try to register a new user. Provide a not valid email address.

**Comment by abstractj** [comment]
Issue confirmed on Keycloak 17.0.0.

**Comment by StitzL** [comment]
Looking at the differences between `/themes/src/main/resources/theme/base/login/messages/messages_en.properties` and `themes/src/main/resources-community/theme/base/login/messages/messages_de.properties`, I can see that quite a lot of translations are still missing, especially the ones from 0913a22c30aab4cb4bf7eb2eb1efa3eefd0df353 starting with `error-`. And I can see that a similar block of i18n properties has been added in `.../resources/theme/base/admin/...`, `.../resources/theme/base/account/...`, and `.../resources/theme/keycloak.v2/account/...` as well.

Now, as a German I want to go systematically about this. I assume that actually, all translations from `/themes/src/main/resources` are necessary and thus would be required to be translated below `themes/src/main/resources-community` in a matching file for the de-locale. So would it be helpful if I just created a map of missing properties and translated them all?

**Comment by yingzili-de** [comment]
I'm experiencing similar issue for not completed translation in Chinese.

Setting: Realm-> Theme -> Login Theme -> Supported Locals: zn-CN selected

My login page looks like 
![image](https://user-images.githubusercontent.com/47558211/173520056-5a750fe8-049b-446b-9320-cef77e5458ca.png)

The highligted labels have not been translated.  Or you have an idea, what would be the reason for this?

**Comment by davidjbng** [comment]
The issue does not necessarily look like an incomplete translation as stated in the issue title. It seems the email validator just does not use the translation.

We have set up our own theme and enabled user profile which contains an email field. Even if I specify a custom translation key for the email validator, it always displays the english message _Invalid email address._

**Comment by jonkoops** [comment]
I see, then we should indeed be using the localized text instead. Feel free to submit a PR to fix this.
