### ISSUE TITLE
User attribute on login-verify-email.ftl

### ISSUE THREAD

**Issue by iingawal** [keycloak/keycloak#8873]
### Description

We would like to show to which email address the email was send on the login-verify-email.ftl page. Example: "You will receive an email from us on

{0}
containing a link which...."

But the login-verify-email.ftl template has no "user" attribute available to get the email address from.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-3090

**Comment by KindHryhoriiShats** [comment]
Any update on this?

**Comment by iingawal** [comment]
Any update on this ?

**Comment by borudena** [comment]
CU is expecting an update on this issue.

**Comment by InterStelli** [comment]
+1 for this -- are there any alternatives?
