### ISSUE TITLE
KeycloakMetricsHandler does not respect a custom context-root

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#8877]
### Description

Currently the `KeycloakMetricsHandler` is bound with a strict path binding to `/metrics`. 
This works fine with the default context-path of `/` however, when a different context-path is configured the `/metrics` endpoint doesn't work anymore and only returns an error message.

If we enable metrics via `-Dkc.metrics.enabled=true` and configure a custom context-path via `-Dquarkus.http.root-path=/auth`, we see the following error response returned if the `/auth/metrics` endpoint is accessed:
```
The expected context root of metrics is /metrics, but a request with a different path was routed to MetricsRequestHandler
```

The problem is that the `org.keycloak.quarkus.runtime.services.health.KeycloakMetricsHandler` is configured with a fixed `/metrics` path which is used to check an incoming request.

### Motivation

To remain compatible with older Keycloak deployments, we want to use the custom context-path `/auth`. At the same time we also want metrics to be available out of the box.

### Details

A small fix is to make `KeycloakMetricsHandler` aware of the configured context path:
```
package org.keycloak.quarkus.runtime.services.health;

import io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler;
import org.keycloak.quarkus.runtime.configuration.Configuration;

import static org.keycloak.quarkus.runtime.configuration.MicroProfileConfigProvider.NS_QUARKUS_PREFIX;

public class KeycloakMetricsHandler extends SmallRyeMetricsHandler {

    public static final String DEFAULT_METRICS_ENDPOINT = "/metrics";

    public KeycloakMetricsHandler() {
        String contextPathPrefix = Configuration.getOptionalValue(NS_QUARKUS_PREFIX.concat("http.root-path")).orElse("");
        String metricsPath = (contextPathPrefix + DEFAULT_METRICS_ENDPOINT).replaceAll("//","/");
        setMetricsPath(metricsPath);
    }
}

```

**Comment by DGuhr** [comment]
Nice catch! Would be great if you could provide a PR for this. When the draft pr from @pedroigor with the testframework makes it, we should also create a test for it :) 

Also, be aware that there's now `http.relative-path` in the config which wraps the quarkus property iirc. (On phone right now, will check tomorrow)

**Comment by thomasdarimont** [comment]
Thanks! I already created a PR for this here https://github.com/keycloak/keycloak/pull/8878.
I'll adapt the PR to use the `http.relative-path` with the `NS_KEYCLOAK_PREFIX`. However, the term "relative-path" is IMHO 
a missleading replacement for `quarkus.http.root-path`. What's the rationale behind the different name? Terms like "root-path", "context-root" or "context-path" are quite used by many other web frameworks, but I find `relative-path` quite confusing.
