### ISSUE TITLE
Allow Developers/Admins to configure SameSite cookie attributes

### ISSUE THREAD

**Issue by kmoorejr9** [keycloak/keycloak#8915]
### Description

[This isssue](https://issues.redhat.com/browse/KEYCLOAK-12700) on the legacy issue tracker highlights the changes made to the SameSite cookies in order to support newer versions of Chrome. 

We have a request from our Security team to enforce lax or strict options - which are currently unavailable and uncontrollable (as far as I am aware) by a developer/administrator.

**Comment by chenjher** [comment]
Our security team also have same request, is this planned to fix and when this is planned to be fixed? Thanks.

**Comment by cbontemps** [comment]
It would be nice to let administrators disable all of the "_LEGACY" cookies. From my understanding these cookies voluntarly does not have a same site parameter.

**Comment by KacperBak** [comment]
Same here. A penetration test revealed this lack of adjustment options

**Comment by jonkoops** [comment]
I personally think that making this configurable is moot, it should be secure by default, and only have an opt-out with a flag if absolutely necessary.

**Comment by jonkoops** [comment]
I am closing this issue, not because it is irrelevant but I feel like #19886 sufficiently overlaps with this use case as well.

Duplicate of #19886
