### ISSUE TITLE
Build fails on systems with large group IDs

### ISSUE THREAD

**Issue by sre4ever** [keycloak/keycloak#8926]
### Describe the bug

Hello,

The build currently fails on systems where the main group ID of the current user is over 2097151. This often happens on systems using Samba or sssd for Active Directory integration.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (assemble) on project keycloak-server-dist: Execution assemble of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single failed: group id '**redacted (9 digits)**' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
```

The fix is trivial: PR #8927

### Version

16.0.0-SNAPSHOT

### Anything else?

Previously: [KEYCLOAK-4563](https://issues.redhat.com/browse/KEYCLOAK-4563) #3936
Regression introduced here: https://github.com/keycloak/keycloak/commit/1c8087baafc3c4e3cb4bca82c2804adaf664c270#diff-5a5ad27dcb26d0ea46e886bb1781b66b37aa627aa38bf3fb9ed65f186abf4266

**Comment by Pepo48** [comment]
Some members of Keycloak QE were able to reproduce this issue on RHEL CSBs. 
In the past a related issue was reported by MacOS users connected to active directory[1].

Possible workaround is to use is to set `tarLongFileMode` property in in server-dist pom.xml to `posix`[2]:
`<tarLongFileMode>posix</tarLongFileMode>`

[1] https://github.com/keycloak/keycloak/pull/3936
[2] https://github.com/keycloak/keycloak/blob/main/distribution/server-dist/pom.xml#L268

**Comment by sre4ever** [comment]
Thanks @Pepo48 for the research, now I think this can be considered a regression as the change to `posix` was already made in 2017 and did not cause issues requiring a rollback to `gnu` format.

**Comment by rhigdon** [comment]
I have also experienced this behavior.  Nice catch!
