### ISSUE TITLE
PAR fails to authenticate for public client

### ISSUE THREAD

**Issue by Robbilie** [keycloak/keycloak#8939]
### Describe the bug

When trying to make a pushed authorization request with a public client an authentication error is returned.

curl -vvv "https://xxx/auth/realms/main/protocol/openid-connect/ext/par/request" -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=browser-test" -d "response_type=code" -d "redirect_uri=https%3A%2F%2Flocalhost" -d "state=12345" -d "nonce=12345" -d "scope=openid"

{"error":"invalid_request","error_description":"Authentication failed."}

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/AbstractParEndpoint.java#L77

For a confidential client the authorization header is added and the endpoint returns a request_uri successfully.

### Version

15.0.2

### Expected behavior

A response with the request_uri is returned for a public client.

### Actual behavior

An error response is returned when no authorization header is provided.

### How to Reproduce?

1. create a new client
2. configure to be public
3. configure a return url
4. make a request to the PAR endpoint with all known parameters like client_id, response_type, redirect_uri, state, nonce, scope

### Anything else?

Error handling for the PAR logic seems to be sub-par since it seems like all the nice exceptions are just hidden behind the "authentication failed" one :)

**Comment by tnorimat** [comment]
@mposolda should an authorization server allow a public client to send PAR? I read the [RFC](https://datatracker.ietf.org/doc/html/rfc9126). It seems that the RFC does not prohibit sending PAR by a public client explicitly. It might be better to read other RFCs or Internet Draft describing best practices about security. WDYT?

**Comment by mposolda** [comment]
@tnorimat It seems to me that we should support PAR for the public clients. I think it is always a little bit safer to use PAR instead of the "classic" flow with parameters directly sent in the URL of the authorization request (just due the fact that there is a bit smaller chance to be disclosed in the browser history etc). And the impersonation scenario you mentioned is possible also with the "classic" flow in theory.

If someone wants to enforce confidential clients together with PAR, he can do it with the client policies though?

When quickly googling, I figured that for example here it is possible to use PAR with public clients https://connect2id.com/blog/pushed-authorisation-request-in-oauth-sdk . Aka:
```
It also works for public clients without credentials.
```

**Comment by tnorimat** [comment]
@mposolda I agree with your idea of using client policies to not allow PAR by a public client.

**Comment by rtheys** [comment]
Hi,

I'm also trying to used PAR for a public client and stumbled upon this issue as it isn't working (20.0.1).

Looking at https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/AbstractParEndpoint.java#L73 it seems there's an explicit check to see if the client is a public client. If so, the code throws a "client not allowed" exception. This exception is then caught by the exception handler and changed to return 'Authentication failed' instead.

The function I'm referring to is this one:
```
    protected void authorizeClient() {
        try {
            AuthorizeClientUtil.ClientAuthResult clientAuth = AuthorizeClientUtil.authorizeClient(session, event, cors);
            client = clientAuth.getClient();

            this.event.client(client);

            cors.allowedOrigins(session, client);

            if (client == null || client.isPublicClient()) {
                throw throwErrorResponseException(OAuthErrorException.INVALID_REQUEST, "Client not allowed.", Response.Status.FORBIDDEN);
            }
        } catch (Exception e) {
            throw throwErrorResponseException(OAuthErrorException.INVALID_REQUEST, "Authentication failed.", Response.Status.UNAUTHORIZED);
        }
    }
```

Is it sufficient to simply drop the ```|| client.isPublicClient()``` check in the if statement, or will this introduce other (security) issues?

If we explicitly deny PAR for public clients, should we not update the UI so you can not require the use of PAR for this client? Having PAR enabled for public clients would obviously be the preferred solution here.

Regards,
Rik

**Comment by rtheys** [comment]
Hi,

I'm looking into this in more detail.

The support for this was introduced with commit 2803685cd73c703e970f61d9a5e20a1c0d6d4b85. In this initial commit, the check for ```|| client.isPublicClient()``` was already present. Unfortunately I could not find any reference why the check was implemented.

Looking at https://issues.redhat.com/browse/KEYCLOAK-18353, it references https://datatracker.ietf.org/doc/html/draft-ietf-oauth-par-08 as the relevant RFC. In the document history of that RFC I see for revision -01:

```
Clarification regarding client authentication and that public clients are allowed
```

The examples also show requests that use code_challenge (PKCE) without a client_secret, so I'm quite convinced that it should be supported.

When I compare `services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java` (which I believe processes requests to the authorization endpoint) and `services/src/main/java/org/keycloak/protocol/oidc/par/endpoints/ParEndpoint.java`, both seem to have a similar way to validate the request.

In AuthorizationEndpoint.java, the _process_ function does:

```
        AuthorizationEndpointChecker checker = new AuthorizationEndpointChecker()
                .event(event)
                .client(client)
                .realm(realm)
                .request(request)
                .session(session)
                .params(params);

...
                
        try {
            checker.checkParRequired();
            checker.checkInvalidRequestMessage();
            checker.checkOIDCRequest();
            checker.checkValidScope();
            checker.checkOIDCParams();
            checker.checkPKCEParams();
        } catch (AuthorizationEndpointChecker.AuthorizationCheckException ex) {
            return redirectErrorToClient(parsedResponseMode, ex.getError(), ex.getErrorDescription());
        }
```

In ParEndpoint.java the _request_ function seems to have similar checks:

```
            AuthorizationEndpointChecker checker = new AuthorizationEndpointChecker()
                .event(event)
                .client(client)
                .realm(realm)
                .request(authorizationRequest)
                .session(session);
                
...
                
        try {
            checker.checkInvalidRequestMessage();
            checker.checkOIDCRequest();
            checker.checkOIDCParams();
            checker.checkPKCEParams();
        } catch (AuthorizationEndpointChecker.AuthorizationCheckException ex) {
            ex.throwAsCorsErrorResponseException(cors);
        }
```

Both use an AuthorizationEndpointChecker and call the checkPKCEParams function.

So at first sight, I believe it may be sufficient to simply remove the ```|| client.isPublicClient()``` in the if statement?

I will try to test this locally to see if this is sufficient to make it work. Even if it does, I'm not sure this will not introduce a (security) bug.

Regards,
Rik
