### ISSUE TITLE
Basic authentication for confidential access type not woking

### ISSUE THREAD

**Issue by Pyr0technicien** [keycloak/keycloak#8945]
Hello everyone,

I installed the latest version of keycloak next to our previous installation that is currently working with a few of our customer.
We are implementing SSO on keycloak via our azure AD IDP.

Our waf is acting as an accessgateway and redirecting not authenticated request to our keycloak, and then back to our back end with the access token.

This implementation works fine on our old version of keycloak however we are encoutering some issue with the new version.
The process works fine if our waf set the cliend_ID and client_secret in the body of the post request to keycloak but this is not really secure, basic authentication isn't working here. (Putting the encoded id and secret in the header).

Keycloak return an error saying Invalid_client_credential, seems like it doesn't recongnize the basic Authentification and doesn't look for credential in the header of the request .

Any Idea what's wrong here ? Direct access grant toggle is enabled, so I'm not sure what other setting should be checked.

Cheers

### Version

15.0.2

**Comment by pedroigor** [comment]
We had the following issues that might help with this one: 

#11908 
#[14179](https://github.com/keycloak/keycloak/pull/14179)

Basically, support for special characters and use standard header format.

Other than, client secret using basic authentication is a critical capability that is working fine.
