### ISSUE TITLE
Expose password policy in login forms to FreeMarker templates

### ISSUE THREAD

**Issue by schereradi** [keycloak/keycloak#8949]
### Description

Currently, when a user wants to register (or update his password), the user does not know which password policies are configured. When the user inputs an invalid password, the validator will stop after the first failed policy and show that one message. 

**Proposal:** There should be a possibility to get the Realm specific password policies in the Login templates so that theme developers could use them to create a password tooltip.

This is a follow-up of this topic: https://github.com/keycloak/keycloak/issues/8771.

### Motivation

For users it can be a frustrating experience to guess all the password policy rules which they have to consider.

**Comment by Olivier-SP** [comment]
Hi, any idea when this feature could be merged ?
Thanks !

**Comment by xelita** [comment]
Hi team. 

We would like to use this feature when merged. When do you plan to merge it?

Thanks

**Comment by Mattinn** [comment]
+1 This feature would be a good addition, please consider adding it to your roadmap

**Comment by carlosyague** [comment]
Please, this feature could be very useful to enhance the user experience during the process of UPDATE_PASSWORD of users. I think internationalization wouldn't be a problem. A description attribute should be added to the list of password policies:

![image](https://user-images.githubusercontent.com/1017882/175932881-1baffcd1-3c53-4024-a059-b0a48c888820.png)

**Comment by SakuraAxy** [comment]
+1 Yes!  I also think this feature can greatly improve the user experience!

**Comment by schereradi** [comment]
@ssilvert 
> One objection is that you can just add static text yourself to expose the password policy. 

Adding static text is not a solution if you are serving more than one realm (with different password policies) with your theme.

> [...] you need some logic that renders it into a clean, human-understandable format. Then you also have the problem of localization.

That's not really a problem. When implementing a theme, you have to deal with these issues anyway.

As you said, all the PR does is expose the password policy to the template in order to give a possibility to create a password tooltip according to the realm-specific configuration.

**Comment by ssilvert** [comment]
@schereradi You can use realm localization overrides to customize the text for each realm.  So static text works for most use cases.

I believe your PR would return something like, `["forceExpiredPasswordChange(365)", "specialChars(3)", "notUsername(undefined)", "length(8)"]`

Then you have to parse that on the client side and figure out how to convert to human-readable format.  

A proper solution would specify some sort of localizable template on the server side.  Then we wouldn't have a situation where everyone has to implement their own solution.

**Comment by schereradi** [comment]
@ssilvert Thanks for your feedback. You've convinced me that static text would be a solution, too. Although it is a little bit sub-optimal that you will need to keep both Keycloak realm settings and static text synchronized.

> A proper solution would specify some sort of localizable template on the server side. 

Yes, agreed! I would work on such a solution if there is a chance for this feature to be merged. But I thought it was decided not to implement it. That's why this PR gives just the possibility for everyone to implement their own password tooltip.

**Comment by ssilvert** [comment]
@schereradi If you are willing to do the work, I think we can get it done.  I think everyone agrees that this is a long overdue feature.

Provide a more detailed proposal here in this issue.  I will make sure that the right people see it so we can get an approval before you put in the hours of work.

**Comment by ssilvert** [comment]
I'd love to see this happen, but I'm going to close this for now.  If someone wants to step up and propose a good solution with a PR, we can reopen.
