### ISSUE TITLE
NullPointerException when editing a sub flow without a description

### ISSUE THREAD

**Issue by brahim-raddahi** [keycloak/keycloak#8958]
### Describe the bug

Using Oracle as the database backend on Keycloak 12.0.4:
Create a sub flow without a description
Edit it
An NPE is thrown

This is where the NPE is thrown:
https://github.com/keycloak/keycloak/blob/12.0.4/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L653

A similar bug was already fixed earlier
See here:
https://issues.redhat.com/browse/KEYCLOAK-15545
Fixed here:
https://github.com/keycloak/keycloak/blob/12.0.4/services/src/main/java/org/keycloak/services/resources/admin/AuthenticationManagementResource.java#L288

Suggested fix for this one:
```
        //check if the description changed
        if (checkFlow.getDescription() != null && !checkFlow.getDescription().equals(rep.getDescription())) {
            checkFlow.setDescription(rep.getDescription());
        } else if (checkFlow.getDescription() == null && flow.getDescription() != null) {
            checkFlow.setDescription(rep.getDescription());
        }
```

### Version

12.0.4

### Expected behavior

The flow is edited without errors

### Actual behavior

An error is shown and you can see in the server log that an NPE is thrown

### How to Reproduce?

Set up Keycloak using Oracle as the database backend
Create a flow
Add a sub flow without a description
Edit that sub flow -> this will result in an error

### Anything else?

It looks like this only happens if using Oracle as the database backend for Keycloak
Tried the same thing (12.0.4), but with MariaDB: did not seem to happen, probably because it is an empty string instead of a null there

**Comment by abstractj** [comment]
The issue is no longer valid on latest releases of Keycloak. Please try 20.0.2 release.
