### ISSUE TITLE
redirect_uri with # has wrong redirect 

### ISSUE THREAD

**Issue by Roriz** [keycloak/keycloak#8959]
### Describe the bug

When request endpoint `/auth/realms/realm-name/protocol/openid-connect/auth` with # on url, the redirect merge querystring and hash params.
Nowadays is common SPA applications use # on URL to make hash-based routing

### Impact
The only safe way to use [keycloak-js](https://www.npmjs.com/package/keycloak-js) is to initialize before any router behavior.
- It impossible to use bundle size on keycloak stuff
- create an instance of keycloak in pages that are not necessarily needed.

### Version

15.0.2

### Expected behavior

Redirect with query string, and hash independently

```
curl 'https://keycloak-url/auth/realms/realm-name/protocol/openid-connect/auth?client_id=clientId&redirect_uri=https%3A%2F%2Fapplication-url%2F%23%2Finternal%2Furl&state=secret-state&response_mode=fragment&response_type=code&scope=openid&nonce=secret-nonce&prompt=none' -H 'cookie: cookies' -i

HTTP/2 302 
date: Mon, 29 Nov 2021 19:47:43 GMT
content-length: 0
location: https://application-url/#/internal/url?state=secret-state&session_state=secret-session&code=secret-code
```

### Actual behavior

Redirect with query string, and hash merged independently

```shell
> curl 'https://keycloak-url/auth/realms/realm-name/protocol/openid-connect/auth?client_id=clientId&redirect_uri=https%3A%2F%2Fapplication-url%2F%23%2Finternal%2Furl&state=secret-state&response_mode=fragment&response_type=code&scope=openid&nonce=secret-nonce&prompt=none' -H 'cookie: cookies' -i

HTTP/2 302 
date: Mon, 29 Nov 2021 19:47:43 GMT
content-length: 0
location: https://application-url/#/internal/url&state=secret-state&session_state=secret-session&code=secret-code
```

### How to Reproduce?

Request `auth/realms/realm-name/protocol/openid-connect/auth` with valid params, example with mocked params:
```
curl 'https://keycloak-url/auth/realms/realm-name/protocol/openid-connect/auth?client_id=clientId&redirect_uri=https%3A%2F%2Fapplication-url%2F%23%2Finternal%2Furl&state=secret-state&response_mode=fragment&response_type=code&scope=openid&nonce=secret-nonce&prompt=none' -H 'cookie: cookies' -i
```

### Anything else?

More about hash router: https://krasimirtsonev.com/blog/article/deep-dive-into-client-side-routing-navigo-pushstate-hash

**Comment by straurob** [comment]
I'm also running into the behavior which @Roriz described. Is there any workaround?

**Comment by Heromyth** [comment]
We are using Keycloak 16.1.0. Suffering from this bug.

**Comment by alirizaaribas-ibg** [comment]
How to mask or by-pass this error?
![image](https://user-images.githubusercontent.com/55430656/164174493-b710be21-f4ad-4d8a-94d6-a68cb6739689.png)

**Comment by alirizaaribas-ibg** [comment]
The problem solved when adding client new address into keycloak admin clients page. Anyone can refer to [link](https://github.com/bcgsc/pori/issues/49).

**Comment by Heromyth** [comment]
> The problem solved when adding client new address into keycloak admin clients page. Anyone can refer to [link](https://github.com/bcgsc/pori/issues/49).

It's just that your problem is solved. It also works with the `Valid Redirect URI` field set to `*`.

This bug is still there.  It's a different bug.

**Comment by jkristia** [comment]
I have run into the same issue, using # strategy and the returned url + queryparam is invalid. This is causing my app to go to the default page rather than the selected page.

Any update on this ?

**Comment by NoudH** [comment]
This issue has indeed to do with Vue Router conflicting with Keycloak (see keycloak keycloak/keycloak#14742).
Based on [this comment](https://github.com/keycloak/keycloak/issues/14742#issuecomment-1663069438) we used to following solution:

**router/index.ts**
```TypeScript
const initializeRouter = () => {
  const router = createRouter({
     // Options
  })

  router.beforeEach(() => {...})
  
  router.afterEach(() => {...})

  return router
}

export default initializeRouter 
```

**main.ts**
```TypeScript
import initializeRouter from '@/router'

const app = createApp(App)

// Other app.use statements
app.use(...)

app.use(VueKeyCloak, {
  config: {
   // config
  },
  init: {
    // init options
  },
  onReady: () => {
    app.use(initializeRouter())
    app.mount('#app')
  },
})

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $keycloak: VueKeycloakInstance
  }
}

export default app
```

**Comment by LeoQuote** [comment]
Using keycloak 23.0.4 and this problem persists, but not relevant when using keycloak 11.0.*

**Comment by LeoQuote** [comment]
This case can be reproduced with keycloak nightly build.

```
HTTP/1.1 302 Found
Cache-Control: no-store, must-revalidate, max-age=0
Set-Cookie: KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/; HttpOnly
Set-Cookie: KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/; HttpOnly
Set-Cookie: KC_AUTH_STATE=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/
Set-Cookie: KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxMGQ4MjcyOC0xZTNkLTQ4NmYtYmE2MS1lMDU3NjNjMGM4MDAifQ.eyJleHAiOjE3MDU1MjAzNjYsImlhdCI6MTcwNTQ4NDM2NiwianRpIjoiMTNkNTBkMzgtYjNiNi00MGY0LTgxMzItNGFiZTZkOTNkYWRiIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrMjoxMDM4MC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNTVmMzRjNjgtYzI4NC00OWU5LTg0ZjEtMGE5ZTJjYjMzZjZjIiwidHlwIjoiU2VyaWFsaXplZC1JRCIsInNlc3Npb25fc3RhdGUiOiI5YTEzYTZjNy1lNGY1LTQzYjUtYmZjYy00ODMwN2FjYzgyMjEiLCJzaWQiOiI5YTEzYTZjNy1lNGY1LTQzYjUtYmZjYy00ODMwN2FjYzgyMjEiLCJzdGF0ZV9jaGVja2VyIjoiSVNFdXZBekFsRlRhQ3NGSENGR19VXzFsQ19NZ3BrVlVXTnFPSTdGeGtTOCJ9.ocYtxhD6mdunRZ4NUI1PzIjvoM6ZYgQ6T8VOEtZX1FE; Version=1; Path=/realms/master/; SameSite=None; Secure; HttpOnly
Set-Cookie: KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxMGQ4MjcyOC0xZTNkLTQ4NmYtYmE2MS1lMDU3NjNjMGM4MDAifQ.eyJleHAiOjE3MDU1MjAzNjYsImlhdCI6MTcwNTQ4NDM2NiwianRpIjoiMTNkNTBkMzgtYjNiNi00MGY0LTgxMzItNGFiZTZkOTNkYWRiIiwiaXNzIjoiaHR0cDovL2tleWNsb2FrMjoxMDM4MC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNTVmMzRjNjgtYzI4NC00OWU5LTg0ZjEtMGE5ZTJjYjMzZjZjIiwidHlwIjoiU2VyaWFsaXplZC1JRCIsInNlc3Npb25fc3RhdGUiOiI5YTEzYTZjNy1lNGY1LTQzYjUtYmZjYy00ODMwN2FjYzgyMjEiLCJzaWQiOiI5YTEzYTZjNy1lNGY1LTQzYjUtYmZjYy00ODMwN2FjYzgyMjEiLCJzdGF0ZV9jaGVja2VyIjoiSVNFdXZBekFsRlRhQ3NGSENGR19VXzFsQ19NZ3BrVlVXTnFPSTdGeGtTOCJ9.ocYtxhD6mdunRZ4NUI1PzIjvoM6ZYgQ6T8VOEtZX1FE; Version=1; Path=/realms/master/; HttpOnly
Set-Cookie: KEYCLOAK_SESSION=master/55f34c68-c284-49e9-84f1-0a9e2cb33f6c/9a13a6c7-e4f5-43b5-bfcc-48307acc8221; Version=1; Expires=Wed, 17-Jan-2024 19:39:26 GMT; Max-Age=36000; Path=/realms/master/; SameSite=None; Secure
Set-Cookie: KEYCLOAK_SESSION_LEGACY=master/55f34c68-c284-49e9-84f1-0a9e2cb33f6c/9a13a6c7-e4f5-43b5-bfcc-48307acc8221; Version=1; Expires=Wed, 17-Jan-2024 19:39:26 GMT; Max-Age=36000; Path=/realms/master/
Set-Cookie: KEYCLOAK_REMEMBER_ME=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/master/; HttpOnly
Content-Security-Policy: frame-src 'self'; frame-ancestors 'self'; object-src 'none';
Location: http://keycloak2:10380/admin/master/console/#/master/clients&state=3355356f-e3aa-4750-8a8a-d7d065da49f0&session_state=9a13a6c7-e4f5-43b5-bfcc-48307acc8221&iss=http%3A%2F%2Fkeycloak2%3A10380%2Frealms%2Fmaster&code=5b7bb693-f576-4799-aa98-89cf45f67f33.9a13a6c7-e4f5-43b5-bfcc-48307acc8221.e4f86516-0efc-4ecb-8be3-70e4dc084be4
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
content-length: 0
```

you can see the location header is `Location: http://keycloak2:10380/admin/master/console/#/master/clients&state=3355356f-e3aa-4750-8a8a-d7d065da49f0&session_state=9a13a6c7-e4f5-43b5-bfcc-48307acc8221&iss=http%3A%2F%2Fkeycloak2%3A10380%2Frealms%2Fmaster&code=5b7bb693-f576-4799-aa98-89cf45f67f33.9a13a6c7-e4f5-43b5-bfcc-48307acc8221.e4f86516-0efc-4ecb-8be3-70e4dc084be4`

while the original request is 
```
http://keycloak2:10380/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Fkeycloak2%3A10380%2Fadmin%2Fmaster%2Fconsole%2F%23%2Fmaster%2Fclients&state=3355356f-e3aa-4750-8a8a-d7d065da49f0&response_mode=fragment&response_type=code&scope=openid&nonce=0832f9cf-6439-4c74-890d-f7843fe1f059&code_challenge=5lAHt8WT7f6UcOkswy4nis8h8k_k_AqTF97uszs0E6s&code_challenge_method=S256
```

clearly there's something wrong with keyloak, getting a wrong redirect uri, containing `&state=` and following wrong arguments

**Comment by LeoQuote** [comment]
@jonkoops @ssilvert IMHO this is not an issue related to `js` code, but a complete **wrong redirect by keycloak core** or OIDC provider, or even URL parse error by web framework, is that possible to make the priority higher?

I'm eager to solve this problem while I cannot even run the test myself, could you help me with that so I can try to solve it myself? https://github.com/keycloak/keycloak/discussions/26357

**Comment by jonkoops** [comment]
Thanks for the detailed steps to reproduce this in the latest version @LeoQuote. I will re-label this to core so that the team can take a look at this. cc @keycloak/core

**Comment by LeoQuote** [comment]
Guys, good news: this not a keycloak bug, please see https://github.com/keycloak/keycloak/issues/26405#issuecomment-1907880982 for detailed information and **solution**

**Comment by rmartinc** [comment]
Because of @LeoQuote comment I'm closing this. Please file a new issue if needed.
