### ISSUE TITLE
It is possible to generate offline tokens with negative expire_in

### ISSUE THREAD

**Issue by LEDfan** [keycloak/keycloak#8965]
### Describe the bug

Hi,

First of all, I'm not sure whether this is the expected behavior, a bug or just a missing explanation in the documentation. Feel free to handle this report as you wish.

### Version

15.0.0

### Expected behavior

(see how to reproduce first)

1. login into keycloak and keep your session open for at least 10 minutes
2. follow the device code flow, e.g. using:

```bash
curl --request POST \
  --url 'https://keycloak.com/auth/realms/dev/protocol/openid-connect/auth/device' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'client_id=device-code' \
  --data 'scope=openid offline_access' | jq .
  
curl --request POST \
  --url 'https://keycloak.com/auth/realms/dev/protocol/openid-connect/token' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=urn:ietf:params:oauth:grant-type:device_code \
  --data device_code=<copy from previous request> \
  --data 'client_id=device-code' | jq .
```

It's important that you activate the device code flow using the existing session.
The expected behavior is that the last request returns an access token and refresh token with a positive lifetime.

### Actual behavior

The actual behavior is that the last request returns an access token and refresh token with a negative lifetime. IMO this should never happen, but because of the mis-configuration this can happen.
<details>
<img src="https://user-images.githubusercontent.com/2996275/144049511-5fd5e669-ad97-4360-bb25-4c85a93531f2.png">
</details>

### How to Reproduce?

1. setup a Keycloak server
2. create a public OpenID Client
3. enable device code for that client
4. setup the timings of the realm as follows:
 - SSO Session Idle: 30 min
 - SSO Session Max: 10 hours
 - Offline Session Idle 5 minutes
 - Offline Session Max Limited: true
 - Offline Session Max: 10 minutes
<details>
<img src="https://user-images.githubusercontent.com/2996275/144048889-8095d20f-ffe3-4a52-90bd-5ec29132387e.png">
</details>
5. click save

The key here is that the `Offline Session Max` is lower than the `SSO Session Max` setting, this causes the described problem. 

### Anything else?

Because the existing session of the user is longer than the allowed value in `Offline Session Max`, keycloak generates a token with a negative lifetime. I think that this is the relevant code: https://github.com/keycloak/keycloak/blob/9be4c289d86328e74876920cca42dda95693f11a/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L1055

This bug is easily reproducible with the device code flow, because an existing session is re-used to generate the offline access token. However, I guess there are probably ways to trigger the bug using the Authorization Code flow as well.

IMO Keycloak should give an error in the `Tokens` setting page and/or document that `Offline Session Max` must be higher than `SSO Session Max`. Besides, it could be a good idea to add a check somewhere that no tokens are issued with a negative lifetime.

Thanks!

**Comment by pedroigor** [comment]
@LEDfan I tried to reproduce using both code and device flows. I did not spot anything that might be causing the behavior you are reporting.

I might be missing the steps to reproduce using device flow, but what I did was to basically:

* Make sure those session lifetime settings are set
* User-login using a device code
* Force the server time to 10 minute or more
* Obtain the tokens after the user is authenticated using the device code
