### ISSUE TITLE
Base Email template for same appearance

### ISSUE THREAD

**Issue by razi-ahmad** [keycloak/keycloak#8999]
### Description

Having one basic email theme and all the rest extending it will give more flexibility and reduce code duplication

Currently, If we have to add header and footer in the template then we have to update all email templates. So, for this solution, there can be one base template like login have. So, in this case no need to change all templates instead of changing only base template according to requirements( mostly, in the footer to show logos, alignment of text in the centre or something else )

### Discussion

https://github.com/keycloak/keycloak/discussions/8687

**Comment by dasniko** [comment]
I can help here and provide a basic html skeleton as base template.
Are there any specific requirements?

I would keep it as simple as possible to not change/break existing usages.

**Comment by jairsjunior** [comment]
Hello, any news in regards to this issue/PR? I can help with something if is needed.
