### ISSUE TITLE
Documentation Error: User Storage SPI: CredentialInputValidator

### ISSUE THREAD

**Issue by InfoSec812** [keycloak/keycloak#9003]
### Describe the bug

The current code example in the documentation for section on CredentialInputValidator is using deprecated examples.

https://www.keycloak.org/docs/latest/server_development/#credentialinputvalidator-implementation

The example shows using `CredentialModel.PASSWORD` constant which is deprecated. The correct option should be `PasswordCredentialModel.TYPE`.

### Version

15.0.2

### Expected behavior

Change the example to use the correct new constants.

**Comment by rmartinc** [comment]
@InfoSec812 I think it's already changed in [current documentation](https://www.keycloak.org/docs/20.0.3/server_development/#credentialinputvalidator-implementation) via this [commit](https://www.keycloak.org/docs/latest/server_development/#credentialinputvalidator-implementation). Closing this one as already done.

**Comment by InfoSec812** [comment]
Thanks @rmartinc !
