### ISSUE TITLE
Access Token claims not imported using OpenID Connect v1.0 Identity Provider Attribute Importer Mappers

### ISSUE THREAD

**Issue by rm3l** [keycloak/keycloak#9004]
### Describe the bug

Hi there !

We have configured an external OIDC Identity Provider (type: `OpenID Connect v1.0`), and are trying to map claims present in the IDP Access Token to Keycloak User Attributes, using an Attribute Importer Mapper.

But Keycloak seems unable to find the claims in the Access Token, with the following DEBUG messages reported:

```
DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-6) Going to process JsonNode path role-coh-irn71429 on data null
DEBUG [org.keycloak.broker.oidc.mappers.AbstractJsonUserAttributeMapper] (default task-6) Going to process JsonNode path iat on data null
```

### Version

10.0.1, but also reproducible with 15.0.2

### Expected behavior

The tooltip message on the Mapper type states:

```
Import declared claim if it exists in ID, access token or the claim set 
returned by the user profile endpoint into the specified user property or attribute.
```

Using the documentation provided [here](https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens), I managed to retrieve the external IDP Token, and can confirm it contains the expected claim. 
So I would actually expect Keycloak to resolve the claims present in the Access Token.

### Actual behavior

The user created in Keycloak at first login does not contain the attribute expected.

### How to Reproduce?

- Configure Keycloak by adding an Identity Provider of type `OpenID Connect v1.0` : https://www.keycloak.org/docs/latest/server_admin/#_identity_broker_oidc
- Configure the external IDP to include a claim in the Access Token only
- In Keycloak, add an Attribute Importer mapper in the identity provider configured. This Attribute Importer should map the claim present in the Access Token
- Try to login using this new Identity Broker. Authentication should pass, but in Keycloak, the user attributes will not contain the mapped claim.

By the way, to make things clearer, I added two test cases in the [following branch in my fork](https://github.com/rm3l/keycloak/tree/claims_not_imported_using_oidc_idp_attribute_mappers_test). 

You can run these tests with the command below:
```shell
mvn -f testsuite/integration-arquillian/pom.xml clean install \
  -Dtest=KcOidcAccessTokenOnlyClaimsUserAttributeMapperTest,OidcAccessTokenOnlyClaimsUserAttributeMapperTest
```

`KcOidcAccessTokenOnlyClaimsUserAttributeMapperTest`, which passes, registers a `keycloak-oidc` Identity Provider.
But as reported here, `OidcAccessTokenOnlyClaimsUserAttributeMapperTest` does not pass because it registers an `oidc` IDP.

### Anything else?

Few months ago, I opened a discussion [here](https://github.com/keycloak/keycloak/discussions/8462) about that issue,but got no response so far. After some discussions, I am finally about to contribute a PR for this issue.

While the reproduction steps are a bit different, @galzetta reported a similar issue (#8961) with similar debug logs. I could not add a test case for this other issue, so I am not sure the linked PR will fix that issue.

**Comment by kevariste225** [comment]
same issue for me

**Comment by Toilal** [comment]
Salut issue on Quarkus 17.0.0

**Comment by rm3l** [comment]
> Salut issue on Quarkus 17.0.0

Hey @Toilal , talking about Keycloak 17, I guess, right? ;)

**Comment by Toilal** [comment]
Yes 👍

**Comment by rmartinc** [comment]
@rm3l I commented in your PR, the access token is opaque by spec, we cannot assume it is a JWT by default. Do you guys know if there are a lot of OIDC providers using a JWT for the access token? Can you list some?

**Comment by karolbryzgiel** [comment]
Hello, 
same issue on Keycloak 20.0.3 :( 

I have integrated Keycloak with Azure AD and when claims is present in id_token it is work fine, but when this claims is present in access_token claims, keycloak can't map this properties.

Do you know any workaround for this?

@rmartinc Azure AD using JWT tokens for access token.

**Comment by rmartinc** [comment]
@karolbryzgiel As commented for now this is the expected behavior. The access token by spec is an opaque token, so the `OIDCIdentityProvider` cannot assume it will be. One solution could be adding a toggle config option to ensure that the access token from the provider is JWT too (false by default) and include it for the parsing when that option is set. But for that the PR should be modified.
