### ISSUE TITLE
Documentation for Quarkus distribution

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#9034]
- #10000 
- #10001

**Comment by pedroigor** [comment]
@DGuhr @stianst Here is what I have in mind as the very first guides we should be looking at:

1. **Configuring Keycloak**

* Main configuration aspects of the server (e.g.: build/runtime configuration, how to check if a configuration is related to build or runtime)
* Why building a server image is important for optimal startup and how to do it
* Briefly explain the format of configuration options: CLI, ENV, properties
* Configuration file: keycloak.properties
* Property replacement

2. **Configuration Profiles**

* Explain about configuration profiles and how to use
* Briefly explain about the built-in profiles: dev and prod

3. **Configuring a SPI**

* Explain how to configure providers

4. **Deploying custom providers**

* Explain how to deploy custom providers

5. **Extending Keycloak Themes**

* Explain how to extend default themes

6. **Configuring Keycloak for Optimal Runtime**

* More detailed guide about how to optimize Keycloak to run faster and with lower memory footprint
* Examples how to extend docker image
* Examples how to do it in bare metal

7. **Configuring a Database**

* Explain how to configure a database

8. **Enabling TLS**

* Explain how to enable TLS

9. **Configuring Clustering**

* Explain the main concepts around clustering (e.g.: config file, cache modes, cache stacks)
* Clustering on Kubernetes

10. **Exposing Keycloak Endpoints**

* Explain how to configure Keycloak hostname provider

11. **Enabling/Disabling Features**

* Explain how to enable/disable features

12. **Configuring a Vault**

* How to use mounted secrets
* How to use Hashicorp

Perhaps some of the items above could be split into different guides.

**Comment by bs-matil** [comment]
Is the order artificial? If not I would like to kindly ask to put the dev experience tasks (14.) earlier so the community could easier start to contribute. Also its handy in case of SPI development to know how those can be tested in that context

**Comment by andreaTP** [comment]
Should we add a section like "Migration from Wildfly distribution"?
Mentioning e.g. bulk import/export, configuration changes etc.

**Comment by pedroigor** [comment]
> Is the order artificial? If not I would like to kindly ask to put the dev experience tasks (14.) earlier so the community could easier start to contribute. Also its handy in case of SPI development to know how those can be tested in that context

Yeah, it is artificial. We should try to deliver all of them at once.

**Comment by pedroigor** [comment]
@andreaTP We have this https://github.com/keycloak/keycloak/issues/9035.

**Comment by DGuhr** [comment]
See https://github.com/keycloak/keycloak/pull/9432 for a first draft PR for Point 1 of your list

**Comment by olivierboudet** [comment]
Hello,

For the clustering part, besides you wrote : `Explain the main concepts around clustering (e.g.: config file, cache modes, cache stacks)`, I would like to emphasis on the infinispan remote store configuration.
