### ISSUE TITLE
CVE Review

### ISSUE THREAD

**Issue by viktorgt** [keycloak/keycloak#9040]
### Description

Right now we are using Keycloak 15.0.2. [Harbor](https://goharbor.io/) does the security scan for us and it reports 11 vulnerabilities for Keycloak dependencies. 
The Quay Security Scanner for the official keycloak image does not report any vulnerabilities, I assume because of white listening. Is there any review/documentation available that describes how/whether Keycloak is affected by a CVE?

**Comment by Hildebrand-Ritense** [comment]
I share this interest. The change logs don't mention the log4shell CVE while the official docker image (https://hub.docker.com/r/jboss/keycloak) has the affected version in its file system (path: `/opt/jboss/keycloak/modules/system/layers/base/org/apache/logging/log4j/api/main/log4j-api-2.14.0.jar`, at least in version 15.1.0).

I'm not sure if this is included as part of keycloak core or that is is a side effect of the container build pipeline. In that case I'd be happy to re-open this issue at the `keycloak-containers` repo.

**Comment by DevOps-Infra-Ritense** [comment]
Apologies, I've missed [this post](https://github.com/keycloak/keycloak/discussions/9078) as I was looking through issue reports rather than read the discussions. For others stumbling across this; only log4j api is included, and not the affected log4j 2 core.

**Comment by abstractj** [comment]
Hi @viktorgt, thanks reporting this issue. Could you please share the report with keycloak-security mailing list? We plan to talk with the Quay team to understand why the scanner is not catching some issues, having more details would be helpful to improve the service.

**Comment by IlyaHoloday** [comment]
Hi @Hildebrand-Ritense, i would also like to see the results obtained.

**Comment by viktorgt** [comment]
Hi @abstractj, I emailed the relevant information to the keycloak-security mailing list.

**Comment by abstractj** [comment]
@viktorgt now we provide into the announcements' section how the most relevant CVEs affect or not Keycloak (https://github.com/keycloak/keycloak/discussions/categories/announcements). 

For false positives reported by code scanners, please check: https://github.com/keycloak/keycloak/issues?q=is%3Aissue+sort%3Aupdated-desc+%22%28False+Positive%29%22+is%3Aclosed+label%3Astatus%2Frejected+

For now, I'm closing this issue, but please reopen if you disagree or have more questions.
