### ISSUE TITLE
Keycloak import in TypeScript without allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by istvandesign** [keycloak/keycloak#9045]
### Describe the bug

When using 
```
import * as Keycloak from 'keycloak-js';

const keycloak = Keycloak({
```

I receive
`  Type '{ default: (config?: string | KeycloakConfig | undefined) => KeycloakInstance; }' has no call signatures.`

### Version

15.0.2

### Expected behavior

One should be able to import Keycloak and use it with TypeScript without turning on allowSyntheticDefaultImports.

### Actual behavior

TS2349: This expression is not callable.
  Type '{ default: (config?: string | KeycloakConfig | undefined) => KeycloakInstance; }' has no call signatures.

### How to Reproduce?

Import keycloak with import * as Keycloak from 'keycloak-js';

### Anything else?

Suggested solution: Export like any other library in 2021 by exporting all functions individually as modules and with a default export.

**Comment by jonkoops** [comment]
I'll try to resolve this as part of my efforts to ship ES modules in the adapter (preliminary work in #9351). The type definitions are currently not in a great state as we are using namespaces (read why that's bad [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm)). Most likely this will be a breaking change to the types to better reflect what is actually in the package.

**Comment by jonkoops** [comment]
I'll try to resolve this as part of my efforts to ship ES modules in the adapter (preliminary work in #9351). The type definitions are currently not in a great state as we are using namespaces (read why that's bad [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm) and [here](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#needless-namespacing)). Most likely this will be a breaking change to the types to better reflect what is actually in the package.
