### ISSUE TITLE
URL is inconsistent between jboss/keycloak and quay.io/keycloak/keycloak-x (/auth)

### ISSUE THREAD

**Issue by istvandesign** [keycloak/keycloak#9067]
### Describe the bug

Hello,
I noticed that I have an inconsistency between the  jboss/keycloak and keycloak-x docker images, the  jboss/keycloak image has /auth in the URL and the keycloak-x image doesn't have /auth.

This is annoying because the URL has to change between different test environments in my case.

### Version

15.0.2

### Expected behavior

All current keycloak distributions should come with the same defaults.

### Actual behavior

 jboss/keycloak and quay.io/keycloak/keycloak-x have undocumented differences

### How to Reproduce?

Run  jboss/keycloak and quay.io/keycloak/keycloak-x with docker and observe the path. (without importing any configuration)

**Comment by istvandesign** [comment]
Actually it is documented, my bad
![image](https://user-images.githubusercontent.com/39516661/145563639-1bc6b83f-103d-49d9-8b37-4247997aed73.png)

Still makes me angry because I have to swap URLs depending on environments, because I have to keep using other keycloak servers.

**Comment by DGuhr** [comment]
@istvandesign Thanks for reaching out. We are aware of this, and in the latest Keycloak.X version which will be shipped in the near future and includes a lot of changes there is the possibility to set the context root path, e.g. via `--http-relative-path=auth`.

If it's an option for you, I suggest to use and try out the latest main and build the distribution (mvn clean install -DskipTests -Pdistribution in the kc root dir, after that the zip for keycloak.x is located in <root>/distribution/server-x-dist/target as zip or .tar.gz ).
