### ISSUE TITLE
How can I fix Keycloak circular dependency in adapter for Spring Boot 2.6.X?

### ISSUE THREAD

**Issue by rajibhalder** [keycloak/keycloak#9079]
### Describe the bug

Spring Boot 2.6.x seems to have introduced some change causing the previously-working integration with Keycloak to have a circular reference, preventing application start; it works and starts fine with the current 2.5.x release.

Explicitly, by changing nothing except the tag value from 2.5.7 to 2.6.1 in spring-boot-starter-parent, the errors/message detailed below occur.

The expected behavior, of course, is that the application starts just fine and is secured with Keycloak just as before.

The actual message is:
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
┌──->──┐
|  keycloakSecurityConfig (field private org.keycloak.adapters.KeycloakConfigResolver org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter.keycloakConfigResolver)
└──<-──┘
Action:
Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

### Version

<dependency> 			<groupId>org.keycloak</groupId> 			<artifactId>keycloak-spring-boot-starter</artifactId> 			<version>15.0.2</version> 		</dependency>

### Expected behavior

The expected behavior, of course, is that the application starts just fine and is secured with Keycloak just as before.

**Comment by little-pinecone** [comment]
This might be related to the #8857 where moving `KeycloakConfigResolver` bean declaration out of a subclass of `KeycloakWebSecurityConfigurerAdapter` was a recommended quick fix.

The working example is the [spring-boot-swagger-ui-keycloak](https://github.com/little-pinecone/spring-boot-swagger-ui-keycloak) project – I was able to replicate the circular dependency issue in this project by declaring `KeycloakConfigResolver` inside my subclass of `KeycloakWebSecurityConfigurerAdapter`.

**Comment by little-pinecone** [comment]
The issue is probably caused by the [Circular References Prohibited by Default](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#circular-references-prohibited-by-default) change in Spring Boot.

If you really can't move the `KeycloakConfigResolver` bean declaration to a separate config class, set the `spring.main.allow-circular-references` property to `true`. This will restore the behaviour from v2.5+.

**Comment by rajibhalder** [comment]
Yes, i resolved it by moving **KeycloakConfigResolver** to a separate config class. So we can close this thread.
