### ISSUE TITLE
Client Policies : Negative logic by a policy

### ISSUE THREAD

**Issue by tnorimat** [keycloak/keycloak#9100]
### Description

To client policies' policy, add a feature "Negative Logic" that client policies' condition has already supported, "Yes" to "No" and "No" to "Yes", "Abstain" remains unchanged.

### Motivation

When we want to apply the following criteria to a request for applying profiles, the current client policies' condition and policy cannot realize this criteria.
`NOT(A AND B) = NOT(A) OR NOT (B)`

By introducing "Negative Logic" to a policy the same as existing conditions supported, the policy with negative logic being true can realize the criteria just above. 

### Details

- Add the boolean valued field `isNegativeLogic` to `ClientPolicyRepresentation` and `ClientPolicy`.
- Its default value is false.
- When the lack of this field's value, it is treated as false. (backward compartibility : this enhancement does not affect keycloak users using client policies)
- `DefaultClientPolicyManager.isSatisfied` check's this field's value of  `ClientPolicy` and revert the result if it is true.

**Comment by mposolda** [comment]
@tnorimat I am not sure about the "Negative logic" field. It seems to be better to me to introduce something like the "Decision Strategy", which is used in the authorization services. The value "unanimous" is equivalent of the logical condition "or", which means that only one condition needs to pass. The value "affirmative" is equivalent of the logical condition "and", which means that all the conditions must pass (with the exception of those, which are ignored). WDYT?

**Comment by tnorimat** [comment]
@mposolda Yes, your idea "Decision Strategy" is preferable. I would like to consider it afterwards. I close this issue and corresponding PR.
