### ISSUE TITLE
KeyCloak "User Federation"  Page not loading as expected

### ISSUE THREAD

**Issue by ZA-NVG** [keycloak/keycloak#9103]
### Describe the bug

Tried installing Keycloak service on Air-Gapped Kubernetes Cluster.

Accessing Keycloak works as expected, but the issue comes when clicking on User Federation Tab and could not add any Authentication service to Keycloak due to this error.

Kubectl logs and Kubectl describe does not shows anything related to error

Error As shown:

![KC](https://user-images.githubusercontent.com/90952517/145785247-8f919d03-13da-4591-a85e-6436f87ddcac.png)

### Version

15.0.2

### Expected behavior

should not have any formatting issues on 'User Federation' Page as shown:

![image](https://user-images.githubusercontent.com/90952517/145785988-f869ef33-1794-43dc-811c-6f9252d8aea7.png)

### Actual behavior

As describe above

### How to Reproduce?

1) Load Image to offline docker repo
2) Configure helm chart to pull from offline docker repo
3) helm install

* Do Note I cannot reproduce it on another system

**Comment by ssilvert** [comment]
@ZA-NVG Can you try this on the latest version, 16.1.0?

**Comment by poopnimator** [comment]
issue have been fixed. Resolved this issue by upgrading browser to latest version
