### ISSUE TITLE
Remove deprecated kcinit

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#9106]
### Description

There is still some leftovers from the abandoned kcinit prototype project that should be removed.

**Comment by tomrutsaert** [comment]
@stianst The /delegated endpoint was removed within the context of this issue, But can it be that [KeycloakInstalled.java line 740](https://github.com/keycloak/keycloak/blob/22a16ee899706de77fa21940c6b66fbddb88af0c/adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java#L740) still points to this endpoint?
Or am I missing something?

**Comment by thradec** [comment]
Hi @stianst, we have hit the issue described by @tomrutsaert ^, our desktop application uses `KeycloakInstalled` and users are redirected to "page not found" error after the login.
Is it a bug or we should use something different? (we would like to upgrade to version 18)
