### ISSUE TITLE
UserResource#sendVerifyEmail uses executeActions.ftl instead of email-verification.ftl

### ISSUE THREAD

**Issue by MarkusRohlof** [keycloak/keycloak#9112]
### Describe the bug

When trying to send a mail-address verification email via [UserResource#sendVerifyEmail](https://github.com/keycloak/keycloak/blob/b1eeb0626e5f462e293579f008a93b7468914b9b/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L859), the method triggers the usage of the wrong `executeActions.ftl` template instead of the correct `email-verification.ftl`.

This is a problem because executeActions.ftl makes the user click multiple times to verify their mail address, which is unexpected and leads to users not understanding why their mail addresses are not verified even though they clicked the link in their after-registration mail. 

### Version

15.0.2

### Expected behavior

`UserResource#sendVerifyEmail` calls `EmailTemplateProvider#sendVerifyEmail`, which sends out the correct `email-verification.tfl` template as the method name suggests and the user expects.

### Actual behavior

`UserResource#sendVerifyEmail` wrongly calls `EmailTemplateProvider#sendExecuteActions`, which sends out the unexpected `executeActions.ftl` template.

### How to Reproduce?

```java
 val realmResource = keycloak.realm("my-realm")
 val userResource = realmResource.users()
 userResource.get(<user-id>).sendVerifyEmail()
```

**Comment by cloudSchulze** [comment]
I have the same issue. Some news on this topic?

**Comment by maciejbak85** [comment]
yeah.. would be great to have, really its very important missing option

**Comment by letschers** [comment]
Even if the developers says that it is not a bug (which is debatable in my opinion), I guess the point about this old problem is the loose end of having a behavior that can be only done in one way, which is from GUI. In a matter of fact that's just a design decision but makes me (and a lot of fellow developers) very uncomfortable not having the choice to do things via API.

Okay, I read some old threads and the main dev arguing that in the end it is a trigger of an action, and I completely agree with it - But is not the same from the GUI? Where in the first login the keycloak admin-cli will trigger the action of verification of email? 

Sorry bringing this topic the thousand time in your life @stianst, but can you explain how do you see difference between an admin trigger from API or for GUI?

**Comment by Gwemox** [comment]
Please implement this issue

**Comment by maciejbak85** [comment]
> Please implement this issue

would be great if this would be done, anyone knows when can we expect this ?
thanks!

**Comment by wolfman42** [comment]
Ran into this problem today. This is needed so that new user registration can be implemented via API calls and so it will use different email template from the "reset password" or "reset OTP" use case.

**Comment by engek1** [comment]
This use case is vital to us as well. 

1. User Registration via API call. (User registered via custom Webapplication himself.)
2. Trigger send-verify-email via API call.
3. Email is sent immediately to the registered user, containing a link to verify the account and signs in. (same like when user registered himself via keycloak form.

I would really appreciate this feature.

**Comment by dorukguner** [comment]
Hello, I'd be happy to work on this as a first contribution but would appreciate some guidance.

Clearly we don't want to change the existing behaviour to preserve backwards compatibility, would something like adding an optional query param to the endpoint, and overloading sendExecuteActions to take an argument that dictates which ftl to use work?

**Comment by victor-borges** [comment]
> Hello, I'd be happy to work on this as a first contribution but would appreciate some guidance.
> 
> Clearly we don't want to change the existing behaviour to preserve backwards compatibility, would something like adding an optional query param to the endpoint, and overloading sendExecuteActions to take an argument that dictates which ftl to use work?

To be honest, Keycloak is not really THAT fond of backwards compatibility, there are constant breaking changes when the major version changes (as expected from major version changes).

The thing is that `send-verify-email` currently is just a subset of `execute-actions-email` and confuses a lot of newcomers using the API, then they search about it and end up in this issue eventually, I guess that's the case for a lot of people here including me.

I, for one, think that the `send-verify-email` should use the same verification template as the GUI, as it's also in the name of the endpoint, to remove that source of confusion and make the API a bit more intuitive.

**Comment by tinycoding5** [comment]
Is there any resolution for this issue?
I am facing to same issue. when I send the email via keycloak API, I get the same email (executeActions email template), I can't get the reset password mail or email verification mail.

**Comment by twobiers** [comment]
FYI: This has been adressed in 24.0.0. See: https://www.keycloak.org/docs/latest/upgrading/index.html#the-admin-send-verify-email-api-now-uses-the-same-email-verification-template.
Thanks to @lexcao.
