### ISSUE TITLE
multiple rows of a single user in CREDENTIAL table

### ISSUE THREAD

**Issue by hokuda** [keycloak/keycloak#9123]
### Describe the bug

This is a copy of https://issues.redhat.com/browse/KEYCLOAK-16438
You can create multiple rows of a single user in CREDENTIAL table.
You can login unless you do not reset password.
However, after resetting password, you can not login with the new password because of the issue.
If password history is enabled, there would be multiple rows of a single user with type==password-history. It seems OK. But, in this case, there are multiple rows of a single user with type==password. It is obviously wrong.

When you update password in the console or using the reset-password rest api, the api does:

1. insert a new row of a new password
2. delete an old row of a old password

When the rest api is invoked twice at the same time, under race condition, it does:

1-1. insert a new row of a new password (A) (1 row is added)
1-2. insert a new row of a new password (B) (1 row is added)
2-1. delete an old row of a old password (1 row is deleted)
2-2. delete an old row of a old password (no row is deleted, because an old row was deleted in 2-1)

As a result, 2 rows of a password (A) and a password (B) are created.

When you reset password, the api does:

1. insert a new row of a new password (C) (1 row is added)
2. delete an old row of a old password (A) (1 row is deleted)

Then, the CREDENTIAL table has 2 rows of B and C.
When authenticating a user, RH-SSO does "select * from CREDENTIAL".
At least, H2 and MariaDB return rows in the order of B->C. (If they return C->B, authentication is done successfully with the new password (C), because the first one (C) is used)
The order depends on implementation of RDBMS. I found H2 rarely returns C->B though, however, having 2 rows of type==password is wrong.

### Version

RH-SSO-7.3.8, RH-SSO-7.4.3

### How to Reproduce?

1. provide a clean installation of RH-SSO
2. start RH-SSO, then create the "admin" user with the password "password"
3. run the create-reset-fail.sh script
(please note that you need to run the script a few times to see the failure, because it depends on the race condition in this step)
4. running "select * from CREDENTIAL" against the DB, you will see multiple rows for the testuser1.

create-reset-fail.sh:
~~~
#!/bin/bash

REALM_NAME='testrealm1'
USER_NAME='testuser1'

TOKEN=`curl --request POST http://localhost:8080/auth/realms/master/protocol/openid-connect/token --header "Accept: application/json" --header "Content-Type: application/x-www-form-urlencoded" --data "grant_type=password&username=admin&password=password&client_id=admin-cli" | jq -r .access_token`

echo "admin's token: $TOKEN"

# delete realm
curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X DELETE "http://localhost:8080/auth/admin/realms/$REALM_NAME"

# create realm

REALM_REP="{\"enabled\":true,\"realm\":\"$REALM_NAME\"}"
curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X POST -d $REALM_REP "http://localhost:8080/auth/admin/realms"

# create user
USER_REP="{\"username\":\"$USER_NAME\", \"enabled\":true}"
curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X POST -d "$USER_REP" "http://localhost:8080/auth/admin/realms/$REALM_NAME/users"

# set password
USER_ID=`curl -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X GET "http://localhost:8080/auth/admin/realms/$REALM_NAME/users" | jq -r .[].id | tail -1`
PASSWORD="password"
CRED_REP="{\"type\":\"password\",\"value\":\"$PASSWORD\",\"temporary\":false}"

curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X PUT -d $CRED_REP "http://localhost:8080/auth/admin/realms/$REALM_NAME/users/$USER_ID/reset-password" &
curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X PUT -d $CRED_REP "http://localhost:8080/auth/admin/realms/$REALM_NAME/users/$USER_ID/reset-password" &
curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X PUT -d $CRED_REP "http://localhost:8080/auth/admin/realms/$REALM_NAME/users/$USER_ID/reset-password" &
curl -v -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X PUT -d $CRED_REP "http://localhost:8080/auth/admin/realms/$REALM_NAME/users/$USER_ID/reset-password"


# test testuser
echo "==== TEST USER ==== (password is valid, if you see access token)"
curl --request POST http://localhost:8080/auth/realms/$REALM_NAME/protocol/openid-connect/token --header "Accept: application/json" --header "Content-Type: application/x-www-form-urlencoded" --data "grant_type=password&username=$USER_NAME&password=$PASSWORD&client_id=admin-cli" | jq -C .


# reset password

echo "==== RESET PASSWORD ===="
PASSWORD="new_password"
CRED_REP="{\"type\":\"password\",\"value\":\"$PASSWORD\",\"temporary\":false}"
curl -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json" -X PUT -d $CRED_REP "http://localhost:8080/auth/admin/realms/$REALM_NAME/users/$USER_ID/reset-password"


# re-test testuser
echo "==== RE-TEST USER ==== (it will fail with the new password)"
curl --request POST http://localhost:8080/auth/realms/$REALM_NAME/protocol/openid-connect/token --header "Accept: application/json" --header "Content-Type: application/x-www-form-urlencoded" --data "grant_type=password&username=$USER_NAME&password=$PASSWORD&client_id=admin-cli" | jq -C .
~~~

### Anything else?

Related to #11995

**Comment by ashish270890** [comment]
@stianst can you please prioritize this issue it's been pending from long time ? is there any ETA for fix ?

**Comment by sschu** [comment]
I can imagine that this happens with READ_COMMITTED isolation level. I am just not sure how relevant the problem is. In what scenario are there concurrent updates of user passwords for the same user?

**Comment by mposolda** [comment]
Thanks for the report. I am adding label "Help wanted" as Keycloak team won't have time to look at this in the near future. It would need to be community contribution to improve this. See "Contributors" section under https://www.keycloak.org/community for more details.

Some more details:
- There is similar/same issue #11955
- Issue is not great, however it happens just when concurrent updates of credentials of same user happens, which can be the case just when admin manually updates credentials by REST API. This is a bit corner case scenario and not something, which normal users would do.
- The issue is likely applicable just to the old store. It will probably automatically disappear once we migrate to new store (somewhere in 2023).

**Comment by ashish270890** [comment]
@mposolda any update on this ?

**Comment by jonkoops** [comment]
@ashish270890 please stop spamming members and threads, it simply adds to our already massive workload. As @mposolda already mentioned before the Keycloak team won't have time to look at this in the near future. Feel free to resolve this issue and open a pull request as [outlined here](https://www.keycloak.org/community).
