### ISSUE TITLE
Keycloak 16.0.0/15.1.0 not on maven central

### ISSUE THREAD

**Issue by jkroepke** [keycloak/keycloak#9127]
### Describe the bug

Keycloak 15.1.0 is not available on maven central

https://mvnrepository.com/artifact/org.keycloak/keycloak-core

### Version

15.1.0

### Expected behavior

Keycloak jars should be on maven central like all other versions before.

### Actual behavior

```
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/keycloak/keycloak-parent/15.1.0/keycloak-parent-15.1.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.keycloak:keycloak-parent:pom:15.1.0 in central (https://repo.maven.apache.org/maven2) @ line 113, column 25
[ERROR] 'dependencies.dependency.version' for org.keycloak:keycloak-admin-client:jar is missing. @ line 162, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project de.adorsys.keycloak:keycloak-config-cli:4.4.1-SNAPSHOT (/Users/jan/IdeaProjects/keycloak-config-cli/pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.keycloak:keycloak-parent:pom:15.1.0 in central (https://repo.maven.apache.org/maven2) @ line 113, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.keycloak:keycloak-admin-client:jar is missing. @ line 162, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by jkroepke** [comment]
The GH Action fails for the tag, too

https://github.com/keycloak/keycloak/runs/4484462804?check_suite_focus=true

**Comment by stianst** [comment]
Hi, we're aware of this issue and there's some issues with repository.jboss.org syncing to Sonatype. Those teams are working on resolving it as quickly as they can, but I'm afraid there's nothing we can do than wait. As a temporary workaround you can enable the JBoss releases repository in your builds.

**Comment by stianst** [comment]
> The GH Action fails for the tag, too
> 
> https://github.com/keycloak/keycloak/runs/4484462804?check_suite_focus=true

That's failing for the same reason as the GH action can't download the keycloak-admin-ui from Maven central.

**Comment by stianst** [comment]
Still nothing, and we're still waiting for Sonatype to sort this out on their end.

**Comment by jkroepke** [comment]
Hi @stianst 

is there a MVNCENTRAL issue (https://issues.sonatype.org/projects/MVNCENTRAL) that we can observe?

**Comment by stianst** [comment]
> Hi @stianst 
> 
> is there a MVNCENTRAL issue (https://issues.sonatype.org/projects/MVNCENTRAL) that we can observe? 

Not a public one I'm afraid. I don't even have access to the issue.

Will report back here when I get more information, and if anyone else spots the 15.1.0 release on Maven central before me would be great with a comment here.

To give a bit more context there's an rsync job that syncs artifacts from repository.jboss.org that has broken down on the Sonatype side. One issue is that when this is recovered after several days of downtime it has a stupid amount of data to sync, which takes a long time and is hard to verify.

We will very likely drop repository.jboss.org in the future.

**Comment by jkroepke** [comment]
Looks like its fixed now

* https://repo1.maven.org/maven2/org/keycloak/keycloak-core/15.1.1/
* https://repo1.maven.org/maven2/org/keycloak/keycloak-core/16.0.0/

> We will very likely drop repository.jboss.org in the future.
Great news!
