### ISSUE TITLE
Enable new admin console to Dist.X

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#9128]
### Describe the bug

It is not possible to enable the new admin console when using Dist.X.

The reason is that we no longer have the themes exploded within the dist but loaded from the classpath.

See https://github.com/keycloak/keycloak/discussions/9119.

### Version

15.1.0

### Expected behavior

Be able to enable the new admin console.

### Actual behavior

Not possible to enable the new admin console.

### How to Reproduce?

Start the server using:

```
kc.sh start-dev --features-admin2 enabled
```

And try to select the new admin console at the `Themes` tab.

**Comment by pedroigor** [comment]
Original issue https://github.com/keycloak/keycloak/issues/9120.

**Comment by pedroigor** [comment]
@chrisx8 Should be fixed, if you are not able to build the project and try it out I can share a docker image.

**Comment by vanrar68** [comment]
> @chrisx8 Should be fixed, if you are not able to build the project and try it out I can share a docker image.

Doesn't seem to work with Keycloak.X 16.1.0
Feature is enabled at startup with --features-admin2 enabled

Following log message appears:
WARN  [org.key.com.Profile] (build-12) Experimental feature enabled: admin2

The only themes showing up for admin console are 'base' and 'keycloak'
Keycloak.X runs in dev mode (start-dev) so theme caching is disabled

**Comment by pedroigor** [comment]
@vanrar68 Did you select the theme by going to `Realm Settings` -> `Themes` and choosing the `keycloak.v2` theme from the `Admin Console Theme` setting?

**Comment by vanrar68** [comment]
> @vanrar68 Did you select the theme by going to `Realm Settings` -> `Themes` and choosing the `keycloak.v2` theme from the `Admin Console Theme` setting?

Yes. Worked well with Keycloak distribution but not with Keycloak.X.
keycloak.v2 theme doesn't show up in the admin console dropdown on the Themes tab of the realm settings
I'll run a new Keycloak.X Docker instance from scratch tomorrow and will let you know

**Comment by vanrar68** [comment]
Same result with a brain new docker instance. Here's what I do:
```
docker build --build-arg KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/16.1.0/keycloak.x-preview-16.1.0.tar.gz -t kc-x-test .
docker run --name keycloak-x -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=changeme kc-x-test start-dev
```
Inside the container:
```
./kc.sh build --features-admin2 enabled
./kc.sh show-config
Current Profile: none
Runtime Configuration:
        kc.config.args =  show-config (KcSysPropConfigSource)
        kc.db =  h2-file (PersistedConfigSource)
        kc.db.password =  ******* (PersistedConfigSource)
        kc.db.username =  sa (PersistedConfigSource)
        kc.features.admin2 =  enabled (PersistedConfigSource)
        kc.home.dir =  /opt/jboss/keycloak/bin/../ (KcSysPropConfigSource)
        kc.http.enabled =  false (PersistedConfigSource)
        kc.metrics.enabled =  false (PersistedConfigSource)
        kc.show.config =  none (KcSysPropConfigSource)
        kc.version =  16.1.0 (KcSysPropConfigSource)
```

**Comment by pedroigor** [comment]
@vanrar68 It works for me when running:

```
docker run --name keycloak-x -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=changeme kc-x-test start-dev --features-admin2 enabled
```

Note that I'm passing the `--features-admin2` as a argument to the container.

I think the problem you are facing is that `build` when the container is already running, will have no effect because you need to restart the server.

Easier is to pass any option you want to the container, similar to when using the distribution.

This is one of the main improvements we had if compared with the Wildfly image. Now you have pretty much the same experience when using the distribution and running containers.
