### ISSUE TITLE
Configuration of custom JDBC driver is broken (leads to Azure SQL cannot be used as database)

### ISSUE THREAD

**Issue by ioemat** [keycloak/keycloak#9133]
Configuration of custom JDBC driver is broken (leads to Azure SQL cannot be used as database)

In previous versions of keycloak.x it was possible to configure the JDBC driver by settings the environment variable _KC_DB_DRIVER_ .
This is e.g. required to run keycloak.x in Azure using Azure SQL (see also [disussion on dev mailing list](https://groups.google.com/g/keycloak-dev/c/ZGuX0CFWqwo/m/uEHToZDSBwAJ)).

With keycloak.x 15.1.0 this does no longer work - the database driver is now set based on the db settings to a hard coded driver class. 
In case of mssql this uses a driver that uses XA transactions which are not supported by Azure SQL.
When trying to set the jdbc driver via configuration, keycloak uses the H2 database driver always.

I added a unit test to show the behaviour to [ConfigurationTest.java](https://github.com/bosch-io/keycloak/blob/bug/keycloak.x-setting-jdbc-driver/quarkus/runtime/src/test/java/org/keycloak/provider/quarkus/ConfigurationTest.java#L257).

Has this been changed intentionally or is this a bug?

_Originally posted by @ioemat in https://github.com/keycloak/keycloak/discussions/8654#discussioncomment-1799232_

**Comment by pedroigor** [comment]
@ioemat Not intended but we also did not yet stress the use case for databases other than those we support.

Looks like we have here a good opportunity to make the necessary changes to make this fully supported and covered.

**Comment by pedroigor** [comment]
@ioemat I've created https://github.com/keycloak/keycloak/pull/9199. Kept the same tests only changed the implementation a bit.

Please, let me know if that PR solves the problem for you.

**Comment by DGuhr** [comment]
@ioemat fyi, this behaviour will change in the next version / has changed now in latest main, see PR #10378 . you'll only need to run `kc.sh build --db=mssql --transaction-xa-enabled=false`, no System Properties involved anymore.
