### ISSUE TITLE
Disable pre-loading offline sessions by default

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#9135]
We don't want pre-loading offline sessions from the database.

**Comment by stianst** [comment]
This has been changed at least for the WildFly dist:
https://github.com/keycloak/keycloak/pull/9414

Review, what is the default in Quarkus dist now

**Comment by pedroigor** [comment]
@stianst PR re-opened and rebased. Will also check how changes impact Dist.X.

**Comment by pedroigor** [comment]
Looks like it is OK and now we don't need to do anything else to make it disabled.
