### ISSUE TITLE
Blank page after deleting realm (master > client)

### ISSUE THREAD

**Issue by abelncm** [keycloak/keycloak#9143]
### Describe the bug

Keycloak 11.0.3

I went to master realm then on menu clients i removed "Marketplace CCV" client (which is the realm i created), and now I keycloak webpage is blank after login.

On kcadm cli when i do get realms i get "null [unknown-error]".

My keycloak is still on h2 database so i can't access that database and look into the data.

Can someone help me get my access back?

### Version

11.0.3

### Expected behavior

Normal client (realm i created) delete operation in master realm

### Actual behavior

Blank page after removing a client (realm i created) from master realm

### How to Reproduce?

Create a new realm, go to master realm, in the clients remove your created realm. Keycloak page goes blank!

### Anything else?

Urgent fix!

**Comment by abstractj** [comment]
@abelncm please try the latest release (16.1.0), and let us know if the issue persists.

**Comment by mposolda** [comment]
Closing as the latest version was not tried and this might be already outdated.

Please re-open if it is applicable for the latest Keycloak 20.0.2 release.
