### ISSUE TITLE
Remove Hashicorp Support

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#9144]
Quarkus Vault is no longer among the core extensions from Quarkus repository. Now it is a quarkiverse extension.

We need to check how this move affects long term support and productization.

This removal is somewhat related to the extension story.

**Comment by pedroigor** [comment]
Let us keep for now as a community feature. The fact it is in Quarkiverse does not interfere with long term support.

**Comment by pedroigor** [comment]
As discussed, we are not dropping Hashicorp support.

**Comment by vmuzikar** [comment]
Reopening this as discussed recently.

CC @pedroigor @stianst @Pepo48

**Comment by pedroigor** [comment]
@vmuzikar Discussion https://github.com/keycloak/keycloak/discussions/16446.

**Comment by pedroigor** [comment]
@mabartos Documentation here https://github.com/keycloak/keycloak-documentation/pull/1746.
