### ISSUE TITLE
Cross DC tests failures

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#9157]
### Describe the bug

There are the following CrossDC tests failing:
```
[ERROR] Failures: 
[ERROR]   BruteForceCrossDCTest.testBruteForceConcurrentUpdate:213->lambda$testBruteForceConcurrentUpdate$2:220 
Expected: a value greater than <11>
     but: <4> was less than <11>
[ERROR]   BruteForceCrossDCTest.testBruteForceWithRealmOperations:146->assertStatistics:227->lambda$assertStatistics$3:238 expected:<10> but was:<2>
[ERROR]   BruteForceCrossDCTest.testBruteForceWithUserOperations:110->assertStatistics:227->lambda$assertStatistics$3:238 expected:<10> but was:<2>
[ERROR]   SessionsPreloadCrossDCTest.loginFailuresPreloadTest:165->lambda$loginFailuresPreloadTest$0:173 expected:<10> but was:<2>
```

the failures seem to be caused by the change introduced in [KEYCLOAK-19773](https://issues.redhat.com/browse/KEYCLOAK-19773) / #8802 that stopped increasing failure count for blocked users. 

This needs to be fixed by changing the `Quick Login Check Milli Seconds` option to lower value in failed tests so that users are not blocked after the second login attempt.

### Version

15.1.0

**Comment by pedroigor** [comment]
@mhajas That one was bugging me and could not find the cause. Thanks for that! Is there a PR?

**Comment by mhajas** [comment]
@pedroigor I just sent it: https://github.com/keycloak/keycloak/pull/9160. I was waiting for GHA in my branch to pass.
