### ISSUE TITLE
drop KEYCLOAK.REALM column in legacy schema

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#9164]
### Describe the bug

There is still `REALM` column which was removed from `RoleEntity` in this [commit](https://github.com/keycloak/keycloak/commit/185075d37305463c4e8e82673bb5f2799e094346#diff-b8c40559721894bb6d1c59b1df39894b1f773f903582bf68e5163c0563195127L86-L89). 

This issue is about removing the column from the schema.

### Version

15.1.0

**Comment by ahus1** [comment]
As work is focusing on the JPA Map storage, there will be no non-essential work on the JPA legacy store as agreed in the storage team.
