### ISSUE TITLE
Operator.X Prototype

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9169]
The prototype is aimed at exploring and trying things out around the operator. There are no guarantees that anything introduced in the prototype will make it into a released operator.
Included tasks:
- [x] #9170 
- [x] #9171
- [x] #9172 
- [x] #9173
- [x] #9174
- [x] #9547
- [x] #9552
- [x] #9732
- [x] #9729
- [x] #9730
- [x] #9780

**Comment by andreaTP** [comment]
@vmuzikar this should be completed now, should we close?

**Comment by vmuzikar** [comment]
@andreaTP Yes! 🥳
