### ISSUE TITLE
Realm CRD

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9172]
The aim of this task is to experiment around Realm CRD. This includes:
- [ ] Generate the CRD from RealmRepresentation
- [ ] Implement the CRD reconciliation using the REST API stop gap solution: #9173

**Comment by andreaTP** [comment]
Related issues in fabric8 `kubernetes-client`:

 - https://github.com/fabric8io/kubernetes-client/issues/3686
 - https://github.com/fabric8io/kubernetes-client/issues/3683
 - https://github.com/fabric8io/kubernetes-client/issues/3681
 - https://github.com/fabric8io/kubernetes-client/issues/3679
 - https://github.com/fabric8io/kubernetes-client/issues/3651

**Comment by andreaTP** [comment]
All of the, so far, discovered bugs have a proposed fix now, we should be good to give this another try with `kubernetes-client` 5.12 🤞

**Comment by andreaTP** [comment]
Implementation details:

- the user will provide one or many CRs containing the RealmRepresentation and referencing (using a label?) one Keycloak deployment/main CR in the same namespace
- the operator will read the CR and dump the content into a secret in JSON format
- the operator will create a k8s `Job` with a single pod running Keycloak with the same configuration(e.g. DB connection) as the Keycloak deployment but running the Dist.X command `./kc.sh import`
- when the job finish successfully the operator perform a rolling restart of the Keycloak deployment

**Comment by andreaTP** [comment]
Related:
 - https://github.com/fabric8io/kubernetes-client/issues/3716

**Comment by andreaTP** [comment]
This is the work in progress diff:

https://github.com/andreaTP/keycloak/pull/2/files#diff-ff8fd7e53e57122ef4eb52b2cbcf149cf56486b47a05580cc17a459878e0739dR166

I can open an "official" PR as soon as 5.12 of `kubernetes-client` gets published (end of this week probably) for:
> Generate the CRD from RealmRepresentation

The reconciliation controller and the other changes need the Deployment to be better defined and to have proper testing in place.
