### ISSUE TITLE
REST API changes for Realm CRD stop gap solution

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9173]
The motivation for this is that the operator needs a stop gap solution for managing Realms (and all its sub-resources) until the Store.X and static file-based configuration is ready. The aim of this task is to update the Admin REST API for the operator to be as easy as possible to manage Realms using REST API.
- [ ] Make sure creating and updating a Realm and all its sub-resources (Clients, Roles, IdPs, ...) is possible using a single REST API call without the need for the operator to fetch anything from Keycloak.
- [ ] If necessary, add a new Admin REST API endpoint(s) as a new version `v2` (using [similar versioning system as Account REST API](https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/common/src/main/java/org/keycloak/common/enums/AccountRestApiVersion.java)).

**Comment by andreaTP** [comment]
we agreed to use the bulk import as a stop-gap solution

**Comment by vmuzikar** [comment]
Closing this as we don't need any REST API changes.
