### ISSUE TITLE
Testsuite baseline

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9174]
The aim of this task is to explore possibilities for testing the operator.
- E2E tests using a live cluster (minikube in GH Actions).
- Ideally should rely on some "framework" provided by the JOSDK.
- The testsuite needs to support the operator running both locally and as an image in a live cluster.
- To consider this done, we need a basic Keycloak deployment tested.

**Comment by stianst** [comment]
@vmuzikar please do provide some more context/details around issues ;)

**Comment by vmuzikar** [comment]
@stianst Working on it right now. ;) Actually, for all Operator.X issues.

**Comment by stianst** [comment]
@vmuzikar lol, github notifications is my new instant messaging :)
