### ISSUE TITLE
Keycloak email subject customization issue

### ISSUE THREAD

**Issue by platof** [keycloak/keycloak#9192]
### Describe the bug

Hi

We are using Keycloak in one of our products and we want to customise the verification and password reset email content and subjects.

But we recognize that both of the emails use the same template executeActions.ftl and there is only 1 field for subject line of that email: executeActionsSubject. I saw emailVerificationSubject and passwordResetSubject but these were not used.

What can I do to use different subject lines for keycloak verification email and password reset email?

I saw a solution online where it will be needed to create a freemarker template but it seems rather complicated. [https://github.com/keycloak/keycloak/pull/7665](https://github.com/keycloak/keycloak/pull/7665)

I hope for easier way to do it.... any help will be much appreciated.

I'm using a dockerized version of keycloak from this [https://github.com/keycloak/keycloak-containers/blob/main/docker-compose-examples/keycloak-mysql.yml](https://github.com/keycloak/keycloak-containers/blob/main/docker-compose-examples/keycloak-mysql.yml)

### Version

latest version of keycloak

**Comment by stianst** [comment]
This is not a bug, please open a feature request
