### ISSUE TITLE
Client authentication fails when using signed JWT, if the JWA signing algorithm is not RS256

### ISSUE THREAD

**Issue by arthurchan35** [keycloak/keycloak#9194]
### Describe the bug

https://github.com/keycloak/keycloak/blob/15.1.0/core/src/main/java/org/keycloak/crypto/AsymmetricSignatureVerifierContext.java#L45
When AsymmetricSignatureVerifierContext verify() a signature, it uses a signature algorithm from KeyWrapper key, rather than configured signature algorithm from Client-->Credential, which would be fine if KeyWrapper key has a correct algorithm set during generation, but

KeyWrapper key:

1. if we use Keys --> generate new keys and certificate, the certificate is generated with default RS256
2. if we generate a keystore file with some other RSA algorithm, for example RSA512, by ourself and import the file in Keys tab, the parsed certificate indeed is with RS512, but the generated Keywrapper key object is still generated into  RS256, because it is hardcoded in:
https://github.com/keycloak/keycloak/blob/15.1.0/services/src/main/java/org/keycloak/keys/loader/ClientPublicKeyLoader.java#L109

So either certificate(public key) importing mechanism generates a Keywrapper key object with algorithm RS256, making it fail to pass client authentication if we want to use a different RSA signature algorithm.

### Version

15.10

### Expected behavior

Client authentication succeed

### Actual behavior

client authentication failed:
`2:24:36,427 ERROR [org.keycloak.services] (default task-9) KC-SERVICES0025: Error when validating client assertion: java.lang.RuntimeException: Signature on JWT token failed validation at org.keycloak.authentication.authenticators.client.JWTClientAuthenticator.authenticateClient(JWTClientAuthenticator.java:168)`

### How to Reproduce?

1. Configure a confidential client on Keycloak
2. In credential tab, choose Signed JWT for client authenticator, and use RS512 as signature algorithm
3. In keys tab, generate new keys and certificate
4. Configure an OAuth client app accordingly, and use the private key and choose RS512 as client authentication's signature algorithm
5. Initiate a OAuth flow

**Comment by rmartinc** [comment]
@mposolda I have been checking this and @arthurchan35 is completely right. I'm working on this one if you don't mind. I'll try to send a PR the next week.

**Comment by rmartinc** [comment]
I have just sent a PR with the fix. @arthurchan35 for the moment you can to specify the certificate using jwks in the client (url or direct string with the json). There you can set the "alg" to "RS512" or the value you like, it's read OK in that format.
