### ISSUE TITLE
Keycloak docker doesn't start because WildFly initial state transfer timed out for cache

### ISSUE THREAD

**Issue by noprysk-ua** [keycloak/keycloak#9195]
### Describe the bug

I'm using `jboss/keycloak:15.1.0` docker image for integration testing in the Gitlab CI. Single Keycloak service for a job with many jobs as a part of a single pipeline. Sometimes it fails to start (in less than 1/4 of cases). The issue was observable for `jboss/keycloak:15.0.2` as well.

The only startup arguments that I set are `KEYCLOAK_USER`, `KEYCLOAK_PASSWORD`, `KEYCLOAK_LOGLEVEL`, and `DB_VENDOR`. Which is equivalent to `docker run -e KEYCLOAK_USER=admin@email.com -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_LOGLEVEL=DEBUG -e DB_VENDOR=h2 jboss/keycloak:15.0.2`.

The first error in the chain is

> 11:03:41,856 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 64) MSC000001: Failed to start service org.wildfly.clustering.infinispan.cache.keycloak.work: org.jboss.msc.service.StartException in service org.wildfly.clustering.infinispan.cache.keycloak.work: org.infinispan.commons.CacheException: Initial state transfer timed out for cache work on runner-ajvcf6kf-project-136-concurrent-54h6r4

Here are complete logs [keycloak.txt](https://github.com/keycloak/keycloak/files/7728366/keycloak.txt).

### Version

15.1.0

### Expected behavior

Correct startup.

### Actual behavior

Keycloak doesn't start correctly, and dependent services fail to communicate with it.

### How to Reproduce?

`docker run -e KEYCLOAK_USER=admin@email.com -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_LOGLEVEL=DEBUG -e DB_VENDOR=h2 jboss/keycloak:15.0.2` for many times.

### Anything else?

It may stably reproduce as a part of a Gitlab CI. The issue may be caused by infrastructure issues (e.g., limited resources).

[Here](https://stackoverflow.com/questions/70380930/keycloak-docker-doesnt-start-because-wildfly-initial-state-transfer-timed-out-f) is the related StackOverflow question.

**Comment by abstractj** [comment]
Closing it due to the lack of response. Please reopen if the issue persists.
