### ISSUE TITLE
Can't update KEYCLOAK_ADMIN_USER / unclear error message

### ISSUE THREAD

**Issue by bjolivot** [keycloak/keycloak#9202]
### Describe the bug

I start new KC.X with an error on KEYCLOAK_ADMIN_USER=administ**ar**tor 
After update with correct username  KEYCLOAK_ADMIN_USER=administ**ra**tor
I get this message 

_DATETIME_ ERROR [org.key.services] (main) KC-SERVICES0010: Failed to add user 'administrator' to realm 'master': user with username exists

### Version

docker version keycloak.x:15.1.0

### Expected behavior

Maybe a more descriptive error message like
First admin user already created...skipping this one.

Or
a possibility to add a new admin with another username

### How to Reproduce?

Just make an error on the username

**Comment by stianst** [comment]
The correct environment variables are:
KEYCLOAK_ADMIN
KEYCLOAK_ADMIN_PASSWORD
