### ISSUE TITLE
Keycloak 14 - Redirecting to blank page - Impersonate User in Admin Console

### ISSUE THREAD

**Issue by jmong143** [keycloak/keycloak#9205]
### Describe the bug

Hi All,

I'm trying to use the impersonate user feature in Keycloak 14.0.0.
I tried to go in Admin Console > Users > select any user > Impersonate

Upon clicking on Impersonate button I'm always redirecting to a blank page with this URL: {{URL}}/auth/realms/{{clientRealm}}/account

Trying to investigate this one still have no luck, hope anyone in this group can help me. Thank you so much in advance!! 

### Version

14.0.0

### Expected behavior

- Once "impersonate" user clicked the button in the admin console it should redirect to view frontend side set in keycloak

### Actual behavior

- I'm getting blank page every time impersonate button clicked

### How to Reproduce?

Login in Admin Console > Go to Users > select any user > Impersonate

See screenshot: https://08445954829887367678.googlegroups.com/attach/80bc46d64cd7c/Keycloak%20Users%20Impersonate.png?part=0.1&view=1&vt=ANaJVrH19JxtXxFnJBlgiKU6mestUEYtGRfDjZ0TATZjQxbeZpoCGjj0h34QFqzUE3oDqzDguNgNOBiIPtI7nYaooPEjTr217MpVF2ZwDC37NJD3xmu5fO0

Upon clicking on Impersonate button I'm always redirecting to a blank page with this URL: **{{URL}}/auth/realms/{{clientRealm}}/account**

See screenshot:
https://08445954829887367678.googlegroups.com/attach/80bc46d64cd7c/Impersonate%20Blank%20Page.png?part=0.2&view=1&vt=ANaJVrHsA-ORIjcwi5M5iX-74KH-ZgFmSE8_kL22igDyfpMhwGgDvjqUYitRJFM0xUFg53qlbwRQZISpS9upnsrjo7i6Wl5rO3Ph9IO5ivu5D-5XZ2n4BkY

**Comment by mabartos** [comment]
@jmong143 Thanks for creating this issue. Unfortunately, I wasn't able to reproduce the bug. Could you please try it with the latest upstream main branch? I'm closing this now, but if you face the same issue even with the latest version of KC, feel free and reopen this issue with additional information.
