### ISSUE TITLE
Changing the name of a realm causes a 404 when accessing the admin console for the realm

### ISSUE THREAD

**Issue by blevine** [keycloak/keycloak#9228]
### Describe the bug

In the admin console for an existing realm "foo".  Change the name from "foo" to "bar" and Save.
Logout
Log back in to the admin console for bar (https://server/auth/admin/bar/console
UI shows the realm setting UI for a split second and then returns a 404 on https://server/auth/admin/realms/foo/localization/en)

Note the "foo" in the path which should be "bar"

### Version

12.0.4

### Expected behavior

There should not be a 404

**Comment by ssilvert** [comment]
@blevine This is working fine for me.  When you change the name of the realm, it changes the URL to contain "bar".  Then I can log out and log back in without a problem.  I am running on the very latest code in main, so maybe this is already fixed?

**Comment by blevine** [comment]
I haven't had time to test this on main, but if it's fixed, it's fixed. So feel free to close.
