### ISSUE TITLE
Username not changing from the admin console in imported realm

### ISSUE THREAD

**Issue by AndreySuworow** [keycloak/keycloak#9230]
### Describe the bug

When I edit user, created in imported realm, it saves everything except username (while for example in master realm everything works as it should). Also in the account console username changes are saved successfully.

In realm settings “Edit username” param is switched on. Tried to turn it off, save and turn it on again - didn’t help.

### Version

15.1.0

**Comment by stianst** [comment]
When you say "I edit user" can you clarify? Also, please provide steps to reproduce

**Comment by rmartinc** [comment]
As @stianst commented, can you please provide the reproducer steps?

I have done the following:

* Export a test realm with two users.

./kc.sh export --file /tmp/test.export --realm test --users same_file

* Start and delete the realm.
* Stop again an import the realm file.

./kc.sh import --file /tmp//test.export --override false

* Start again and check the console. The username cannot be edited as the option "Edit username" was disabled in the realm. But after going to "Realm Settings" -> "login" -> Enable "Edit username". I have successfully edited a user changing the username from "ricky" to "ricky2". I have even checked that I can login with that user.

**Comment by rmartinc** [comment]
Closing this for now. Feel free to reopen if needed.
