### ISSUE TITLE
Outdated version properties in keycloak-parent pom.xml

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#9257]
### Describe the bug

In `keycloak-parent` `pom.xml` are still some old/outdated version properties, e.g. 
`<resteasy.version>3.15.1.Final</resteasy.version>` - where as the Keycloak 16.0.0 server runs more recent versions of dependencies, e.g. the RestEasy version is on `4.7.2.Final`.

This leads to errors and ClassNotFoundExceptions during runtime when using dependency versions from the parent pom during compile time.

### Version

16.0.0

### Expected behavior

All version properties in `keycloak-parent:pom.xml` reflect the actual versions of the dependencies in the running server.

### Actual behavior

The `keycloak-parent:pom.xml` has still some old/outdated dependency version properties.

### How to Reproduce?

Look into the parent `pom.xml`, e.g. https://github.com/keycloak/keycloak/blob/6c12c188542aeacc6d40aff9160e83b6a12f5b97/pom.xml#L96

**Comment by stianst** [comment]
ClassNotFoundExceptions for what/where? Please provide some more information.

Also, please see https://github.com/keycloak/keycloak/issues/9258. The dependency versions defined here are used in many different places, and simply upgrading them can result in issues as well.

**Comment by dasniko** [comment]
When using the parent pom as dependency management when developing Keycloak extensions like this:
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-parent</artifactId>
      <version>${keycloak.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

One does not have to deal with dedicated dependency versions which are used in the Keycloak server, when using transitive dependencies like `jboss-logging` or `resteasy-...`. Changing the Keycloak version always changed the transitive dependencies used in the runtime.

Now, RestEasy is still on `3.15.x` in `pom.xml`, but runtime is already on `4.7.x`. So, while the code compiles without errors, it may crash at runtime, as dependencies and package structure in RestEasy changed. Thus, ClassNotFoundException. Not directly in KC code, but in custom extensions.

Simply using a dedicated RestEasy version is not as easy is some cases, when you have deps to reasteasy in your extension code and at the same time a dependency to the kc-admin-client. The one needs Resteasy 4.7.x (extension) and the other 3.15.x (admin client). The admin client doesn't work, obviously, with Resteasy 4.7.

I understand that's it's difficult to maintain different/diverging versions while supporting two different runtimes. Until KC15 everything worked pretty fine and I think many developers are used to this  approach.

**Comment by DGuhr** [comment]
@stianst I think [here](https://github.com/aerogear/keycloak-metrics-spi/issues/124) you see a specific example. I looked a bit what may be wrong. Observations:
1) works with old kc (obviously)
2) works with kc.x (added it to our internal services) which uses Resteasy 4.7.3
3) does not work with kc16 

Question: Is there some intermediate layer which may break the overall compatibility and causes Class/MethodNotFoundExceptions and would it be reasonable to fix this, if it exists?

**Comment by stianst** [comment]
keycloak-parent isn't a BOM and obviously shouldn't be used as such. We do have the SPI BOM for this purpose, now this issue isn't valid, but made me realise that the SPI BOM is not valid either, so we can fix this there at least for now.

**Comment by dasniko** [comment]
Unfortunately, this is bad developer experience. With every version upgrade, developers have to investigate time-consuming all necessary dependency and library updates within the underlying server. Redundant work for a lot of people.

This would be ok, if it would be very easy to use Keycloak in various runtimes. But actually it's only usable with the provided Wildfly, and in future with Quarkus runtime - which is great and I really appreciate this. But today I would expect that the product gives me all the necessary dependencies which are available, not just saying "hey, it's the runtime, it's not our product". Actually, the runtime is part of the product. Just saying.

**Comment by stianst** [comment]
> Unfortunately, this is bad developer experience. With every version upgrade, developers have to investigate time-consuming all necessary dependency and library updates within the underlying server. Redundant work for a lot of people.
> 
> This would be ok, if it would be very easy to use Keycloak in various runtimes. But actually it's only usable with the provided Wildfly, and in future with Quarkus runtime - which is great and I really appreciate this. But today I would expect that the product gives me all the necessary dependencies which are available, not just saying "hey, it's the runtime, it's not our product". Actually, the runtime is part of the product. Just saying.

I'm not following what you are saying here. The Keycloak parent was never intended to be used as a BOM for writing extensions, so don't expect it to work for that purpose. We have a BOM that is specifically intended for this purpose:

https://search.maven.org/artifact/org.keycloak.bom/keycloak-spi-bom/16.1.0/pom

I appreciate that it isn't correct right now, and is also missing private SPIs, etc. What I'm suggesting is that we update this and have a proper BOM with all the dependencies needed to write extensions. That allows us to use the correct dependencies.

How would that not fit what you're actually after?

**Comment by dasniko** [comment]
> I'm not following what you are saying here. 

I know, we have different opinions on that. When I have to deal separately with a product and the runtime, to which the product is bound, I call it _bad experience_. Similar to the fact, that today a Keycloak customer (developer, operations, etc.) has to have too much knowledge for using Infinispan to run Keycloak properly in production. While this is another story in detail, it's also the thing _product only vs. complete runtime_.

Apart from that I'd really appreciate to have one bom, parent, whatever, what I can use with all the necessary dependencies a developer needs to implement proper extensions. The question remains, what are _all necessary dependencies_ so that the vast majority of developers are satisfied? We can discuss this in the issue for updating the spi-bom.

Looking forward to get a working bom in future!

**Comment by stianst** [comment]
> > I'm not following what you are saying here.
> 
> I know, we have different opinions on that. When I have to deal separately with a product and the runtime, to which the product is bound, I call it _bad experience_. Similar to the fact, that today a Keycloak customer (developer, operations, etc.) has to have too much knowledge for using Infinispan to run Keycloak properly in production. While this is another story in detail, it's also the thing _product only vs. complete runtime_.

Have you looked at the Quarkus preview distribution? This is one of the key issues that it is trying to resolve, by explicitly configuring Keycloak, not the runtime, and as much as we can hide/mask the fact that it is using Quarkus under the covers. 

When installing or configuring Keycloak you should have the experience of configuring Keycloak, and not some underlying runtime. For extensions it is a bit more difficult of course, while for simple extensions they can be written more or less agnostic to the underlying runtime, for more advanced extensions that becomes a lot harder.

> 
> Apart from that I'd really appreciate to have one bom, parent, whatever, what I can use with all the necessary dependencies a developer needs to implement proper extensions. The question remains, what are _all necessary dependencies_ so that the vast majority of developers are satisfied? We can discuss this in the issue for updating the spi-bom.
> 
> Looking forward to get a working bom in future!

Created a follow-up here:
https://github.com/keycloak/keycloak/issues/9277
