### ISSUE TITLE
Update Infinispan index after removal of indexed entity

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#9271]
### Describe the bug

When executing a Ickle query to fetch a stream of entries from a cache, it is possible that some items of the stream are concurrently removed. By the time the item is processed, it is changed to `null`. 
Therefore `null` entries needs to be filtered out to prevent NPE later on. 
```
 CloseableIterator<E> iterator = query.iterator();
        return closing(StreamSupport.stream(Spliterators.spliteratorUnknownSize(iterator, 0), false))
                .onClose(iterator::close)
                .filter(Objects::nonNull)
                .map(this.delegateProducer);
```

This behavior is experienced only when entities are indexed. We should investigate whether the Infinispan index can be updated sooner.

### Version

16

**Comment by ahus1** [comment]
Hi @martin-kanis - I updated the labels of this issue so that it is no longer in triage status. Please let me know if the labels should be tuned differently.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
