### ISSUE TITLE
Use PolicyEnforcer within OSGI doesn't work

### ISSUE THREAD

**Issue by ChristianLutz** [keycloak/keycloak#9287]
### Describe the bug

AbstractPolicyEnforcer will fail to load ClaimInformationPointProviderFactory within an OSGI environment.
The reason is the service loader is unable to find ClaimInformationPointProviderFactory.

### Version

15.0.2

### How to Reproduce?

Use the keycloak-adapter in an OSGI env. And use a keycloak.json with the attribute `"policy-enforcer": {}` set. This forces the adapter to use ClaimInformationPointProviderFactory. If you call now a secured endpoint, this will fail.

**Comment by pedroigor** [comment]
@ChristianLutz Are you using Fuse? I'm afraid we don't have any support for it.

**Comment by ChristianLutz** [comment]
Hello @pedroigor 
thank your for your fast reply.

We use karaf (so yes to your question) with cxf and jetty. I know it is not an official supported configuration, that is the reason why we have created our own admin-client https://github.com/ChristianLutz/keycloak-cxf-admin-client

But this issue isn't related to cxf-admin-client it is about the possibility to secure our REST service within an OSGI env. And for this we followed this official keycloak description [Securing a Servlet Deployed as an OSGI Service](https://www.keycloak.org/docs/latest/securing_apps/index.html#_fuse_adapter_servlet_whiteboard)
So this issue isn't distinct to karaf/fuse it is a problem of all OSGI application with [SPY Fly](https://aries.apache.org/documentation/modules/spi-fly.html) as service loader.

**Comment by pedroigor** [comment]
@ChristianLutz Thanks. I'm not sure if we are going to have time to work on a fix. But if you think the changes are simple I'm open to reviewing a PR.

I'm only concerned about testing. TBH, I would need to spend some time looking at how to write a test for this (even though I know we have some fuse-related tests).

**Comment by ChristianLutz** [comment]
@pedroigor I have already provided a PR to fix this. See above. What this PR is missing is a fuse test.

**Comment by pedroigor** [comment]
@ChristianLutz Thanks. Now the PR is linked with this issue.
