### ISSUE TITLE
Support LDAPS with non-public certificates

### ISSUE THREAD

**Issue by sll552** [keycloak/keycloak#9301]
### Description

We are hitting the same issue when trying to connect keycloak to our AD. The Issue was already described in Jira please see the link below.

https://issues.redhat.com/browse/KEYCLOAK-16207

### Motivation

AD normally use non-public certificates wich are not verifiable with the standard java keystore. 

### Details

Maybe add the option to use an init-container which would maybe help with future (non-related) issues as well.

**Comment by sll552** [comment]
I just realised that this issue might be better suited for https://github.com/keycloak/keycloak-operator 

I have created it here because the last comment in jira linked to this repo. I hope thats not a problem. 
This issue is only relevant when deploying keycloak with the keycloak-operator in OpenShift/Kubernetes.

**Comment by shawkins** [comment]
See the support added for both the server and operator under #23742
