### ISSUE TITLE
Remove Java 8 support on server side

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#9310]
### Description

As we are switching the default distribution to Quarkus we should also drop support for Java 8 as Quarkus does not support it.

At a minimum this would require:

* Updating POMs to allow Java 11 APIs for server-side only modules
* Update server installation guide
* Add a note to migration guide and release notes

**Comment by hmlnarik** [comment]
Big +1 from me. Compilation of Keycloak distribution with JDK 11 already causes binary incompatibility with JDK 8 which throws exceptions, see #9885 or #10127.

**Comment by trixpan** [comment]
+1 to @hmlnarik comment. The drop in java 8 support as part of 15.1.1 release was a big surprise and I don't recall seeing this being broadcasted to the community/
