### ISSUE TITLE
Keycloak X - KC_DB_USERNAME environment variable doesn't override PersistedConfigSource

### ISSUE THREAD

**Issue by eamelink** [keycloak/keycloak#9314]
### Describe the bug

After using `kc.sh build`, I can no longer set the `db.username` property through the `KC_DB_USERNAME` environment variable; the value from the `PersistedConfigSource` appears to take priority.

### Version

Keycloak-x 16.1.0

### Expected behavior

I would expect the environment variable to take precedence. 

### Actual behavior

The setting from the `PersistedConfigSource` remains.

### How to Reproduce?

Create a configured Keycloak docker image using the following Dockerfile:

```Dockerfile
FROM quay.io/keycloak/keycloak-x:16.1.0
WORKDIR /opt/keycloak
RUN ./bin/kc.sh build --db=postgres
```

And build with `docker build . -t test`

Then, run with `docker run --env KC_HOSTNAME=foo --env KC_DB_USERNAME=bar test show-config`, and observe the output:

```
Current Profile: none
Runtime Configuration:
	kc.config.args =  show-config (KcSysPropConfigSource)
	kc.db =  postgres (PersistedConfigSource)
	kc.db.password =  ******* (PersistedConfigSource)
	kc.db.username =  sa (PersistedConfigSource)
	kc.home.dir =  /opt/keycloak/bin/../ (KcSysPropConfigSource)
	kc.hostname =  foo (EnvConfigSource)
	kc.http.enabled =  false (PersistedConfigSource)
	kc.metrics.enabled =  false (PersistedConfigSource)
	kc.show.config =  none (KcSysPropConfigSource)
	kc.version =  16.1.0 (KcSysPropConfigSource)
```

Note that the `kc.hostname` setting did take the value from the environment, but the `kc.db.username` did not.

Also note that a system property *does* succesfully override the setting: `docker run test show-config -Dkc.db.username=bar` works as expected.

**Comment by eamelink** [comment]
I could be entirely mistaken, but I suspect it has something to do with the mapping from Keycloak config keys to Quarkus config keys: https://github.com/keycloak/keycloak/blob/96b2669a00dc1396138f863bbc11aa0b0aa3f0b6/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/KcEnvConfigSource.java#L33-L38

**Comment by Leletir** [comment]
Hi, I have exactly the same problem on Keycloak 16.1.0.

For the moment my workaround is: 
`kc.sh --profile=prod start -db-username=${KC_DB_USERNAME} --db-password=${KC_DB_PASSWORD}`

**Comment by stianst** [comment]
FIxed in main already
