### ISSUE TITLE
User profile configuration API is incorrectly typed

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#9318]
### Describe the bug

The [user profile configuration endpoint](https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_getconfiguration) response is incorrectly typed as `string` (see below). This should be a complex object type that represents the actual API response.

![Example from the API docs with incorrect tyoe](https://user-images.githubusercontent.com/695720/147141556-edaf663d-2bcb-4b41-8668-5816b4f9420b.png)
 

### Version

16.1.0

### Expected behavior

The API response is correctly typed (as well as the API docs), the correct type should be [`UPConfig`](https://github.com/keycloak/keycloak/blob/9dff21d0a72efb39fa2de5d2b63ec63da6b75291/services/src/main/java/org/keycloak/userprofile/config/UPConfig.java#L29).

### Actual behavior

The API response is of type `string`.

**Comment by rmartinc** [comment]
@jonkoops With this [commit](https://github.com/rmartinc/keycloak/commit/322a222a78b1ebd420c9f48ab26ba53cd410866f), the json for the GET/PUT method is:

```json
    "/admin/realms/{realm}/users/profile" : {
      "get" : {
        "tags" : [ "Users" ],
        "description" : "Get the configuration for the user profile",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UPConfig"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "Users" ],
        "description" : "Set the configuration for the user profile",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UPConfig"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UPConfig"
                }
              }
            }
          }
        }
      },
      "parameters" : [ {
        "name" : "realm",
        "in" : "path",
        "description" : "realm name (not id!)",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      } ]
    },
```

Is that OK for you?

**Comment by jonkoops** [comment]
Yes, that looks much better @rmartinc!
