### ISSUE TITLE
Wrong mapping for the db.schema property

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#9328]
### Describe the bug

The `db.schema` property definition is wrong and mapping to an invalid property in Quarkus.

We should change it to map to:

* `quarkus.hibernate-orm.database.default-schema`
* `spi.connectionsJpa.quarkus.schema`

We should probably have a default value for it too: `keycloak`.

### Version

16.1.0

### Expected behavior

Properly set the database schema.

### Actual behavior

Schema can only be set by overriding the JDBC url.

**Comment by DGuhr** [comment]
@pedroigor we can close this, right? looking at https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/DatabasePropertyMappers.java#L80-L81 it now points to the right value.
