### ISSUE TITLE
Keycloak.X (Documentation - ReadMe) - Need To use specify http-host with kc.sh start-dev command 

### ISSUE THREAD

**Issue by orivat** [keycloak/keycloak#9329]
### Describe the bug

Readme specifies:

~~~
To run on Linux/Unix:

    $ bin/kc.sh

To run on Windows:

    $ bin\kc.bat

After the server boots, open http://localhost:8080 in your web browser. The welcome page will indicate that the server is running.

~~~

When keycloak.x is started for the first time using command kc.sh start-dev,  It is not possible to connect to connect to UI at address http://localhost:8080

we obtain the following log trace:

~~~
kc.sh start-dev

...
...

Listening on: http://0.0.0.0:8080

~~~

Only way to connect to admin console at port 8080 has been start keycloak.x with option:

bin/kc.sh start-dev --http-host localhost

### Version

16.1.0

### Expected behavior

Update Readme to indicate how to start keycloak.x using option  --http-host localhost

**Comment by DGuhr** [comment]
@orivat I can't reproduce the behaviour you mention using 16.1.0, see https://youtu.be/1bBNaJIkjoE - most likely it is a local networking setup problem. 0.0.0.0 normally will be just fine when you use localhost:8080. For more information about this, see e.g. https://en.wikipedia.org/wiki/0.0.0.0 or https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0
