### ISSUE TITLE
Access Token is not active when retrieved via token exchange

### ISSUE THREAD

**Issue by ashleyww93** [keycloak/keycloak#9337]
### Describe the bug

Token Exchange does not seem to work correctly when you are exchanging for a new subject.

An access token is returned, but then when you introspect it, it is not active. This causes libraries like nest-keycloak-connect to be unusable with the new tokens as you get correctly get unauthorized exceptions.

I have double-checked that the host is the same as the issuer and the introspecter, and I have been running tests via Postman with no luck.

Below is a screenshot of how I am exchanging via postman:
![image](https://user-images.githubusercontent.com/3884418/147261518-420a9c84-6a36-496e-931e-dc8e9b37ac4c.png)

### Version

15.0.1

### Expected behavior

The Access Token and Id Token should be able to access applications just as if the user had manually logged in.

### Actual behavior

When the access token is introspected, it falsely reports that the token is not active.

`{"active":false}`

### How to Reproduce?

Generate an access token for your admin user.
Use that token to exchange the token for another user token.
Try and use the new token with token/introspect

See that it doesn't work.

**Comment by ashleyww93** [comment]
Hi @pedroigor. 

Thanks for the update.

However, we moved away from keycloak to firebase months ago, as keycloak did not support the core functionality we needed and there seemed to be a very small active community to help debug issues.

**Comment by ashleyww93** [comment]
I should also point we didn’t want to exchange on the client, we wanted to exchange on our own backend and then pass this token back to the front end for authentication. 

Needing to act as a tenant is quite a common use case, is not insecure if you setup your api and access levels correctly.

**Comment by pedroigor** [comment]
Thanks, @ashleyww93. I hope we can do better next time.

Created https://github.com/keycloak/keycloak/pull/13796.
