### ISSUE TITLE
Impossible to override acr claim value in ID token

### ISSUE THREAD

**Issue by fidgi** [keycloak/keycloak#9344]
### Describe the bug

Since [PR KEYCLOAK-14309](https://github.com/keycloak/keycloak/pull/8680), it is not possible anymore to override the acr claim in the ID Token.
This breaks our custom implementation that extends the very limited support of the acr claim that exists today in Keycloak and this prevents us from being able to move to KC 15.1.1 .

### Version

14.0.0

### Expected behavior

We'd like to be able to customize acr claim value in ID token.

### Actual behavior

Log :
WARN  [org.keycloak.protocol.oidc.mappers.OIDCAttributeMapperHelper] (default task-2) Claim 'acr' is non-modifiable in IDToken. Ignoring the assignment for mapper 'my_acr'.

### How to Reproduce?

Define a custom protocol mapper for the acr claim : 
			{
				"name": "my_acr",
				"protocol": "openid-connect",
				"protocolMapper": "oidc-usersessionmodel-note-mapper",
				"consentRequired": false,
				"config": {
					"user.session.note": "AUTH_LEVEL",
					"id.token.claim": "true",
					"access.token.claim": "true",
					"claim.name": "acr",
					"jsonType.label": "String"
				}
			}

**Comment by fidgi** [comment]
Just to add that this issue is critical for us since it prevents us from being able to upgrade to a version that fix the security issue.

**Comment by fidgi** [comment]
@rmartinc @stianst  it would be great to have an assignable/overwrittable acr claim in the next release (17.0.0)

**Comment by rmartinc** [comment]
@stianst WDYT? Do I prepare the PR?

**Comment by fidgi** [comment]
Hi , I wouldn't want to sound like I'm insisting but this point is really a blocker for us. It prevents us to move to a keycloak version > 14.0.0

**Comment by rmartinc** [comment]
@stianst @mposolda In PR https://github.com/keycloak/keycloak/pull/8680 the attributes that were set by the server at code level (not in mappers) are non modifiable except aud, sub and azp. So the non modifiable ones are: jti, typ, iat, exp, iss, scope, nonce, acr, auth_time and session_state. In general if you want to add "acr" or any other to be modifiable list just let me know. I will prepare a PR.

**Comment by etchepar** [comment]
As said by @fidgi , this PR prevents some people to upgrade from KC 14.
In my case, we do not use the KC default flow to implement a custom flow with some custom steps including a custom stepup mechanism (and for the moment the stepup appeared in KC 17 does not fulfill our very specific requirements).

Thus, allowing the acr to be updated via mapper (after the initoken call) in the accessToken will allow to continue to work on the KC codebase with custom authenticator and acr mapper. 

Is there a reason to prevent users to do so ?

Regards,

Gilles ETCHEPAREBORDE

**Comment by g10f** [comment]
We are also using acr in a brokered scenario and changing the value in a token mapper.
Would be nice if it possible again to overwrite the default values from keycloak.

**Comment by mposolda** [comment]
@fidgi @rmartinc @etchepar @g10f There is bigger refactoring to improve step-up authentication experience in the Keycloak. I've added this bug to be considered in the epic.

One more thing: Latest released Keycloak 17 already has some support for step-up authentication. See latest docuemtnation for more details. And "acr" claim is currently used based on the levels achieved during authentication from the authentication flow. Maybe you can try to update to see if latest Keycloak already helps you to achieve your use-cases better.

**Comment by mposolda** [comment]
This will be addressed by #10315 and #10161

**Comment by etchepar** [comment]
> @fidgi @rmartinc @etchepar @g10f There is bigger refactoring to improve step-up authentication experience in the Keycloak. I've added this bug to be considered in the epic.
> 
> One more thing: Latest released Keycloak 17 already has some support for step-up authentication. See latest docuemtnation for more details. And "acr" claim is currently used based on the levels achieved during authentication from the authentication flow. Maybe you can try to update to see if latest Keycloak already helps you to achieve your use-cases better.

Thank you very much for adding the bug.
Meanwhile, we are looking in KC 17 and try to adapt our flows and authenticators to its stepup  mechanism and dedicated notes.

**Comment by mposolda** [comment]
This is fixed during the work on https://github.com/keycloak/keycloak/issues/10161 and should be available in Keycloak 18
