### ISSUE TITLE
Bad Request readOnlyUsernameMessage

### ISSUE THREAD

**Issue by ravitejapagala** [keycloak/keycloak#9358]
### Describe the bug

When i am trying to configure the SMTP getting the following Error
I searched in google and i found these ways to resolve this issue.
**Go to Manage Account(http://<host>/auth/admin/master/console/) -> Personal Info -> Update firstName/lastName/emailAddress -> Save and try to add smtp configuration again.**
PFA for the Reference
![image](https://user-images.githubusercontent.com/84474944/147682688-bf3c903c-88c1-4d81-9baa-bf3d9578733e.png)
![Screenshot from 2021-12-29 21-48-53](https://user-images.githubusercontent.com/84474944/147682977-9d2d651b-8627-4f67-a45c-5d7f2a71ee6e.png)

### Version

14.0.0

**Comment by ssilvert** [comment]
@ravitejapagala Can you be more specific about what is wrong and the steps to reproduce?  What are the ways to resolve the issue that you found using Google?  Any links?

**Comment by ssilvert** [comment]
@ravitejapagala ^^ ??

**Comment by ssilvert** [comment]
@ravitejapagala I'm closing this for now.  We can reopen later if needed.
