### ISSUE TITLE
REST call to groups role-mappings returns the same content on each page

### ISSUE THREAD

**Issue by IAMJDA** [keycloak/keycloak#9359]
### Describe the bug

I try to fetch the role mapping of a group to a realm. I use the standard paging with ?first=0&max=100

The software I use, loops endlessly because one mapping for a group is returned on each page

### Version

16.1.0

### Expected behavior

The mapping should be returned only once and the next pages must be empty.

### Actual behavior

`PS C:\Users\salesadm> $response_p1.Content | ConvertFrom-Json

id          : 80a7208f-e490-497b-9fe3-f6b992410a21
name        : offline_access
description : ${role_offline-access}
composite   : False
clientRole  : False
containerId : master

PS C:\Users\salesadm> $response_p2.Content | ConvertFrom-Json

id          : 80a7208f-e490-497b-9fe3-f6b992410a21
name        : offline_access
description : ${role_offline-access}
composite   : False
clientRole  : False
containerId : master

PS C:\Users\salesadm> $response_p3.Content | ConvertFrom-Json

id          : 80a7208f-e490-497b-9fe3-f6b992410a21
name        : offline_access
description : ${role_offline-access}
composite   : False
clientRole  : False
containerId : master
`

### How to Reproduce?

`$url = "http://172.20.28.169:8080/auth/admin/realms/master/groups/1b10152e-20ed-4107-903a-828b23e39739/role-mappings/realm"
$token = "ABC"

$headers = @{
    Authorization="Bearer $token"
}

$response_p1 = Invoke-WebRequest -Uri "${url}?first=0&max=100" -Headers $headers
$response_p2 = Invoke-WebRequest -Uri "${url}?first=100&max=100" -Headers $headers
$response_p3 = Invoke-WebRequest -Uri "${url}?first=200&max=100" -Headers $headers`

**Comment by rmartinc** [comment]
This [endpoint](https://github.com/keycloak/keycloak/blob/20.0.3/services/src/main/java/org/keycloak/services/resources/admin/RoleMapperResource.java#L156-L164) does not manage the typical paging attributes (check also the [API](https://www.keycloak.org/docs-api/20.0.3/rest-api/index.html)), it returns all the mappings all the time. If someone wants to help on this would be much appreciated.
