### ISSUE TITLE
Client secret length should be adjusted based on select signature algorithm

### ISSUE THREAD

**Issue by mayur9991** [keycloak/keycloak#9376]
### Describe the bug

Client secret length should be changed based on Mac Algorithm if secret-jwt is used as Client Authenticator.

![image](https://user-images.githubusercontent.com/7783488/147913805-4b9e5f45-80f2-449f-994e-3cedb3818a54.png)

Currently, Keycloak generates client secret with 32 characters which is only good for HS256 (32 x 8 = 256). 

However if user wants to use HS384 or HS512, secret length should be changed based on selected signature algorithm as client secret is used to sign the JWT.

For HS384, secret length should be 48 (384 / 8 = 48). And For HS512, secret length should be 64 (512 / 8 = 64).

### Version

16.1.0

### Expected behavior

Secret length should be changed based on selected signature algorithm.

### Actual behavior

Secret length is always 32 characters which can only work with HS256 signature algorithm.

### How to Reproduce?

- Select `Signed Jwt with Client Secret` as client authenticator for OIDC client
- Select HS512 as signature algorithm
- Regenerate the secret and we can see it is only 32 characters long

```java
//Reference: org.keycloak.models.utils.KeycloakModelUtils#generateSecret
public static String generateSecret(ClientModel client) {
        String secret = SecretGenerator.getInstance().randomString();
        client.setSecret(secret);
        return secret;
}
```

**Comment by mposolda** [comment]
@marcelomrwin Assigning to you to doublecheck and eventually fix as it is a bit related to the client secrets, which you were recently working on. No hurry with fixing this issue (We can postpone for few months if there is more priority work).

TBH I am not sure if this is really valid assumption that client secret length should be based on the underlying algorithm in case of the authetnication with "Signed Jwt with Client Secret". Leaving to you to doublecheck and eventually fix this.
