### ISSUE TITLE
Failed to execute atob on window

### ISSUE THREAD

**Issue by derweise** [keycloak/keycloak#9377]
### Describe the bug

Uncaught DOMException: failed to execute 'atob' on 'window': The string to be decoded is not correctly encoded.

I get this error at keycloak.js:1071

This is here:

```
        function decodeToken(str) {
            str = str.split('.')[1];p

            str = str.replace('/-/g', '+');
            str = str.replace('/_/g', '/');
            switch (str.length % 4) {
                case 0:
                    break;
                case 2:
                    str += '==';
                    break;
                case 3:
                    str += '=';
                    break;
                default:
                    throw 'Invalid token';
            }

            str = decodeURIComponent(escape(atob(str))); // <----------

            str = JSON.parse(str);
            return str;
        }
```

### Version

"keycloak-js": "^11.0.0",

**Comment by jonkoops** [comment]
@derweise We do not actively support version 11 of Keycloak (or `keycloak-js` for that matter), could you use the latest versions of both and confirm the issue is still present? Also please provide more information about the browser you are using as that will help us reproduce the issue.

**Comment by derweise** [comment]
I think this is because the 'memberOf' attribute in keycloak contains non ASCII characters such as (ß,ä,ö,ü) for which atob fails.

**Comment by jonkoops** [comment]
Re-opening this issue so that we don't lose track of it.

**Comment by jonkoops** [comment]
I am not able to reproduce this issue any longer, and the code for decoding the token has since been changed, so I will assume this issue is fixed. If someone is still able to reproduce this please file a new issue with steps to reproduce it.

**Comment by tkyriakopoulos** [comment]
For me it was non ASCII characters at some user attributes such as firstname and lastname. I change the value of this fields to ASCII Latin characters and the atob error was gone.

**Comment by jonkoops** [comment]
@tkyriakopoulos is this still happening on the latest version of Keycloak and Keycloak JS?

**Comment by tkyriakopoulos** [comment]
@jonkoops i haven't try it to be honest.
