### ISSUE TITLE
Hardening of manage-realm role

### ISSUE THREAD

**Issue by UXabre** [keycloak/keycloak#9387]
### Describe the bug

Currently, one is able to partially import and export a json in realm when having the manage-realm role.
However, importing of the JSON file allows one to set and overwrite existing clients (even if there are no other roles assigned to that user, e.g. manage-clients).
This could lead to somebody completely altering a client, like changing the secret or worse, in case of this role on the master realm, is able to promote themselves to admin by configuring a hardcoded realm role.

At the very least it does not work consistently with exporting which seems to prevent exporting a client. Also, the API does not allow to create clients with only "manage-realm" role assigned.

### Version

16.1.0

### Expected behavior

Partially importing should only allow importing clients (and client roles) if manage-clients is assigned.
Same applies for importing groups, if the user does not have the rights to manage-users it should not be possible to create them as well.

To further elaborate, on this function: https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L1104-L1109

We could do a check to see if "clients" field is available in the realmrepresentation. If so, we can check if the we have the manage authorization for clients as well. If we check the UI, we see that this is effectively dropped from the JSON passed to the API call. We could do the same for other facets of the imported JSON as well.

It would be quite similar to the export function IMHO:
https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L1121-L1141

### Actual behavior

Via partial import one is able to create and adjust clients, client roles and groups at will.

### How to Reproduce?

- Create a user with only the manage-realm assigned for a specific realm.
- Partially Import a JSON which contains client information. (or create a client, do an export, delete the client and import the json file)
- Observe that it simply works!

### Anything else?

I've first contacted the security team but it is not deemed a high risk and rather an inconsistency that can (hopefully easily) be resolved by fixing the above.

**Comment by stianst** [comment]
The manage-realm role really should be considered as a super-user as it grants ability to do pretty much anything. So I don't really see this as an issue, or something that can be solved without fine-grained admin permissions.

**Comment by UXabre** [comment]
Forgive me if I'm completely wrong here but the matter of the fact is, that it does _not_ give these super-user abilities; if I only have manage-realm then I can only change the name, theme, mail settings,  etc of the realm. I cannot manage users, clients, federation, etc. It is not a composite role (which would make sense if this was a composite role) or does it in code seem to imply that all can be done as a manage-realm user. The "realm-admin" role, however, seems more what you are describing and gives me super-user rights (as it comprises all roles).

If the code seems to back this up actually (I just took a random example for the clients):
https://github.com/UXabre/keycloak/blob/1aef1817192edc26cbd913f2f7f13aa87a5e4703/services/src/main/java/org/keycloak/services/resources/admin/permissions/ClientPermissions.java#L253

Also, visually manage-realm seem to be related to "realm settings" as well and I cannot manage clients (and thus I don't have superpowers here as well). Even the API for managing clients does not work.
![afbeelding](https://user-images.githubusercontent.com/15357734/151358078-cf1679c3-19a7-49e8-aacd-3dcb263e4bd9.png)

The only time I am able to create clients, is by importing my realm and this seems to be inconsistent considering all of the above. My proposed PR actually only implements and reflects what seems to be the way that it is meant to be (or at least been implemented by others to be so far): it does not allow you to import clients if you can't manage clients.

Again, forgive me if my thinking here is completely wrong; I just try to go with what I can deduce from code, API, UI and documentation.

**Comment by UXabre** [comment]
Hi, many moons have gone by since the initial debut of this issue. Has somebody else found some time to review this and my rebuttal? Thanks :-)

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

**Comment by UXabre** [comment]
Hi @mposolda , actually, I've created a PR to address this issue :-)
https://github.com/keycloak/keycloak/pull/9404

I'll see to resolve the conflicts

**Comment by UXabre** [comment]
Meanwhile the conflicts seem to have been resolved, I'm working on making a PR for the renewed admin UI as well, this PR was targeting the legacy admin
