### ISSUE TITLE
Global lock interface

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#9388]
### Description

Provide interface or a set of interfaces that enable support for global locks in Keycloak such that:
- each map storage implementation can provide its own implementation of these interfaces
- legacy store implementation also exists
- it is possible to use the locks from services transparently without knowing which implementation (legacy, map-infinispan, map-jpa, ...) actually provides the lock implementation

original issue: https://issues.redhat.com/browse/KEYCLOAK-19896

~The locking needs to be handled by the provider factory on the area level, i.e. here for client tables. There should be no separate locking mechanism necessary, all the locking has to be done in here, and the locked area should not prevent locking and updating other area, e.g. realms or users.~

https://github.com/keycloak/keycloak/pull/8615#discussion_r764310768

**Comment by hmlnarik** [comment]
Changing scope to map storage as this is not JPA-specific (rather the opposite)

**Comment by ahus1** [comment]
In issue #10149 there was the scenario when Keycloak didn't have permissions to create tables in the schema. While the "manual" migration mode has been intended for this, this still needs the DATABASECHANGELOGLOCK to be present first before Keycloak can create a SQL script. For that same reason the script created doesn't contain the code to create DATABASECHANGELOGLOCK. 

When investigating this issue, a solution for this issue should aim to support a scenario as described above as well. In manual/verify mode, it might not be necessary to leverage the DATABASECHANGELOGLOCK functionality as they both never update the database anyway, and will either pass or create a SQL file that is later executed manually. 

Even a different Keycloak instance in update mode will not trick a verify/update Keycloak instance into a situation where it corrupts the database. A SQL script for migrating the database manually doesn't apply locking in the way it is created today. At the same time, it would be a quite uncommon scenario to run different Keycloak instances with different migration settings simultaneously. Only multiple Keycloak instances in update mode would need to lock the database before they validate and start the migration.
