### ISSUE TITLE
Problem displaying settings in Authentication Flow Overrides->Browser Flow after deletion user flow

### ISSUE THREAD

**Issue by BlackKerio** [keycloak/keycloak#9394]
### Describe the bug

After deleting the user flow (Authentication - Flows), it is not displayed in the Authentication Flow Overrides->Browser Flow settings in the client that uses it, which is good. (there are two blank lines in the selection menu). But unfortunately it will remain saved. 
When further editing the client settings and the next save an error is reported, "Error! An unexpected server error has occurred". 
It is necessary to select the last empty row in the list in the Browser Flow settings and then save. 

### Version

15.1.1

### How to Reproduce?

create a user float to assign to a client and then delete it.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.
