### ISSUE TITLE
Dist.X cannot connect to external Postgres if the password ends with an = sign

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#9397]
### Describe the bug

Keycloak-X fails to start if it is configured to connect to a database with a password terminating with an `=` sign.

### Version

16.1.0

### Expected behavior

You can connect to the database

### Actual behavior

Access to the database is forbidden and Keycloak fails to start.

### How to Reproduce?

Try to connect to an external postgres database with a command like:

```bash
/opt/keycloak/bin/kc.sh start-dev --db=postgres --db-url=jdbc:postgresql://<your-url>:5432/<db-name> --db-username=<your-user> --db-password='<your-password>=' --http-enabled=true
```

Modifying the password to match `<your-password>` in the database, changing accordingly the command line parameter and restarting Keycloak workaround the issue.

### Anything else?

cc. @DGuhr @pedroigor @vmuzikar

**Comment by pedroigor** [comment]
I guess this also applies to any other CLI option?
