### ISSUE TITLE
SSO Identity Provider user creation is not case insensitive on Username.

### ISSUE THREAD

**Issue by SomeDeveloper13** [keycloak/keycloak#9405]
### Describe the bug

When using an SSO saml IDP, if the case of the source saml username changes, and login by email is turned on, then login fails due to a unique constraint validation.

### Version

15.0.2

### Expected behavior

When logging in on step 4, I expect to log in with the same permissions I've had in the past.

### Actual behavior

Failure to log in due to unique index violation.

### How to Reproduce?

1. Create IDP using saml with upn mapped to username and email mapped to email address.
2. Create an SSO user with Claim of upn like JDoe@test.com and email like john.doe@test.com. (Capitalized letters in the upn & upn mapped to keycloak username)
2. Create user by logging in through the IDP as JDoe@test.com (PIV authentication for example)
3. Add a filter to the source SSO provider to lowercase the upn. (username returns as jdoe@test.com)
4. Attempt to login with same user through idp.
    Now you get an "Unexpected error..." message on the login page, and in the Keycloak logs, a unique index validation error is thrown.
    ![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/46978095/148392736-fcb6405f-7687-4f7b-a671-9a738c43f9cb.png)

### Anything else?

Cause:

- Keycloak is trying to create a new user, but the email is already in use, which causes the above error.

Proposed Resolution:
- Add an option to keycloak keycloak saml IDP's to be case agnostic with the username just as it is when logging in with basic auth.
- Or update the DB operations to be case agnostic. (May not work for everyone since I've seen cases where sites use case sensitive username... for some reason.)

**Comment by bizkaipc** [comment]
II have the same problem in the latest version.

If the user identifies himself with his username in lowercase letters, for example e05670, he can log in correctly, but if he identifies himself in uppercase letters E05670, it does not detect it as an existing user and tries to create it, giving a duplicate user error.

regards

**Comment by pedroigor** [comment]
Case-sensitive usernames have been the subject of different discussions and requests from the community. This is not only specific for brokering but also other federation providers such as LDAP.

@bizkaipc They all ended up with the same conclusion where lowercase is there by design.

@SomeDeveloper13 Also, the version you are reporting is too old and we have improvements in brokering since then. If you are facing the same error.
