### ISSUE TITLE
KeycloakPrincipal and KeycloakSecurityContext break ObjectInputStream serialization by modifying the stream's filterPattern

### ISSUE THREAD

**Issue by Dretch** [keycloak/keycloak#9408]
### Describe the bug

`org.keycloak.KeycloakPrincipal::readObject` has some code that modifies the filter on the `ObjectInputStream`:
```java
    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        DelegatingSerializationFilter.builder()
                .addAllowedClass(KeycloakPrincipal.class)
                .addAllowedClass(KeycloakSecurityContext.class)
                .addAllowedPattern("org.keycloak.adapters.RefreshableKeycloakSecurityContext")
                .setFilter(in);

        in.defaultReadObject();
    }
```

This is not a safe thing to do, in general, because the `ObjectInputStream` may contain objects after the `KeycloakPrincipal` that are unrelated to Keycloak, and the deserialization of these objects will now fail with an error like:

```
Caused by: java.io.InvalidClassException: filter status: REJECTED
	at java.base/java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1343) ~[na:na]
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1975) ~[na:na]
```

This problem commonly occurs when sessions are persisted using Java serialization - e.g. via Tomcat, Spring, Redis, etc -- because a single `ObjectInputStream` will contain unrelated objects from different sessions (and different attributes in the same session).

### Version

12.0.4

### Expected behavior

I suggest that Keycloak should not be modifying the `ObjectInputStream` in this manner.

Perhaps Keycloak should provide a filterPattern value that would enumerate all the classes expected under `KeycloakPrincipal` and/or `KeycloakSecurityContext`, but it should not attempt to install this pattern as the filter when reading these objects from an `ObjectInputStream`: the creator of the `ObjectInputStream` should be responsible for setting up the pattern (or not).

Keycloak is not in a position so know what classes will appear in the stream, so Keycloak not setting the filter should not be considered a security problem (as it seems was originally assumed).

### Anything else?

As far as I can see the issue originated with this commit: https://github.com/keycloak/keycloak/pull/7053
Some additional changes, with the same underlying problem, were made with: https://github.com/keycloak/keycloak/pull/7138

## Workaround

At least some of the time, the problem can be avoided by setting a system property (`-Djdk.serialSetFilterAfterRead=true` on the command line). This prevents Keycloak installing the problematic filter. It does result in some warnings in the logs, though.

## Possible Changes

If you decide you agree with what is stated above, I would be happy to look into sending a PR to remove the code that installs the filter.

Thanks!

**Comment by jsorah** [comment]
Moving this to the backlog as adapters are deprecated and there is not as much focus on them at the moment, PRs are certainly welcome to fix this issue.

**Comment by lrozenblyum** [comment]
We face multiple warnings like this in HA environment with Tomcat session replication
```
DelegatingSerializationFilter - Could not set ObjectFilter: null
```

After debugging I've discovered that they're caused by this ticket.
Are these warnings ignorable?

Is the workaround to avoid them (`-Djdk.serialSetFilterAfterRead=true`) safe enough?

**Comment by lrozenblyum** [comment]
@Dretch I'd like to add some remark.

It seems that `-Djdk.serialSetFilterAfterRead=true` doesn't prevent the filter to be set up. On the contrary - it's being set up and doesn't throw the exception `filter can not be set after an object has been read` from `java.io.ObjectInputStream.setObjectInputFilter(ObjectInputFilter)`, thus the warnings like `DelegatingSerializationFilter - Could not set ObjectFilter: null` disappear

**Comment by lrozenblyum** [comment]
So my thoughts are that it's safer NOT to set up `-Djdk.serialSetFilterAfterRead=true`.

Without this setting there are good chances that the Keycloak's filter won't be set up thus it won't jeopardize deserialization of potentially unrelated object in the Input stream
