### ISSUE TITLE
Origin host is not parsed correctly when the authUrl doesn't contain or ends with a / 

### ISSUE THREAD

**Issue by tolsam** [keycloak/keycloak#9417]
### Describe the bug

The following code fails to parse correct the host part of the authUrl if the authUrl doesn't contain or ends with a `/`
`loginIframe.iframeOrigin = authUrl.substring(0, authUrl.indexOf('/', 8));`
This is the case in one production environment which uses a reverse proxy in front of Keycloak.

### Version

16.0.1

### Expected behavior

No need to add a `/` in the end (or it must be documented well).

### Actual behavior

Without the `/` in the authUrl it doesn't work at all.

### How to Reproduce?

Use an URL as authUrl that doesn't contain or end with a `/`
e.g. http://auth.mydomain.com

**Comment by tolsam** [comment]
> I presume when you say "Use an URL as authUrl" in the Keycloak javascript adapter?

Sorry I used the code variable name, that might lead to confusion. I mean the URL you use in the keycloak-js adapter configuration
```
const keycloak = new Keycloak({
    url: 'http://keycloak-server${kc_base_path}',
```
And the line in the source code that causes the problem is in 
[keycloak.js](https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/keycloak.js) line 1223.

**Comment by jonkoops** [comment]
Re-opening this issue so that we don't lose track of it.

**Comment by jonkoops** [comment]
I cannot reproduce this issue. Providing a URL without a trailing slash works just fine. I am going to assume this issue was fixed. If anyone has reproduction steps that work in the latest version let me know and I will re-open the issue.
