### ISSUE TITLE
Broken search of Groups/subgroups in Admin UI

### ISSUE THREAD

**Issue by aznamier** [keycloak/keycloak#9435]
### Describe the bug

With groups/subgroups configuration, the group searching by name is rendering incorrect results.
Its impossible to select wanted group so it prevents from editing or adding the user to such group.

### Version

16.1.0

### Expected behavior

I should be able to search for a given group eg: "Manager" 
and then I should be able to select it so it can be edited or user can be added to such group.

That was working in <= v15.0.2

### Actual behavior

Search is rendering incorrect results, for example: 

With this hierarchy of groups with subgroups:
<img width="328" alt="Screen Shot 2022-01-07 at 15 32 49" src="https://user-images.githubusercontent.com/4445230/148566912-ba788a0b-7d33-4c1c-9565-6da961a08181.png">

Searching for: Manager
Renders the list of top level groups, not the group I want to find.
<img width="357" alt="Screen Shot 2022-01-07 at 15 33 54" src="https://user-images.githubusercontent.com/4445230/148567275-65dd11f9-b96c-43b4-b640-18c2d4f15fe6.png">

This issue also happens on the User/Groups management, making it impossible to add user to a Manager group:
<img width="703" alt="Screen Shot 2022-01-07 at 15 58 25" src="https://user-images.githubusercontent.com/4445230/148570479-9501b337-001a-4a1a-b9bc-ca97d0d96f73.png">

### How to Reproduce?

Create a structure of groups and subgroups, and then search for the subgroup.

**Comment by jbpin** [comment]
it's actually a bug in the API itself not only the frontend. 

Searching for a group will only return its subgroup that have subgroup but not direct subgroup...

**Comment by JuliusMu** [comment]
We are trying to update our Keycloak to Version 16.1.1 and we are having the same issue with the API. If you call the GET groups endpoint you only get the subgroups which have a subgroup itself. Is there another way to get all subgroups? It is completely breaking our own implementation.

**Comment by crose-adesso** [comment]
Hey, we are also trying to upgrade our Keycloak and the Unit Tests are Failing in that particular case. Sending a request to the Keycloak server returns a response with empty subgroups. Please fix this issue because it is crucial for our project...

Quick look from IntelliJ Debugger:
![grafik](https://user-images.githubusercontent.com/101329095/157648189-f7fe4823-a035-46b7-961a-b67bbe57542e.png)

**Comment by JuliusMu** [comment]
I looked closer into this issue and found the pull request which changed the behaviour of the realm/groups Endpoint. [PullRequest](https://github.com/keycloak/keycloak/pull/8134)
I think its current behaviour is intended. It just returns the groups and subgroups witch contain the search String and not all subgroups anymore. We are now looking into another solution on our end, like request all groups and filtering them ourself or adding the search String to all of our subgroups. If anyone has a better solution I would appreciate that.

**Comment by jbpin** [comment]
@JuliusMu thank for pointing out the pull request. Unfortunately, it will no help fixing front end nor the search. I'm not sure if the PR must be revert or improved with flag or whatever. 
Can someone from the management team can answer this ticket with intention please ?
We can find solution on our end but people working on the UI are stuck if I understand correctly.

**Comment by rmartinc** [comment]
Hi everybody and sorry for the late response.

As it's already commented the search for groups was modified intentionally in https://github.com/keycloak/keycloak/pull/8134. Now the search returns only the groups that really fulfill the query condition. IMHO it makes sense (at least more sense than the previous behavior) and, for the moment, we are not going to change this again.

Regarding the console limitations, the new console is in place and its behavior is completely different. I'm not happy with it so I have filed a new UI issue https://github.com/keycloak/keycloak-ui/issues/4526. The UI team will review it. But my point here is that the current issue is out of date with the new console as user/group assignment is different.

I'm going to close this and the PR for the moment. Check the group/user behavior in the new console and comment anything in the new issue.

Regards!
