### ISSUE TITLE
Investigate init image for Dist.X deployed with the operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9437]
The operator currently uses an init image for WF dist which is not correct. To resolve this issue, either remove the init image from the Keycloak deployment, or use one corresponding to the Quarkus dist.

**Comment by vmuzikar** [comment]
@pedroigor @DGuhr From your PoV, do we need an init image?

**Comment by andreaTP** [comment]
Investigated:

 - The current Keycloak init container is actually a "feature" of the current operator
 - The feature will download automatic popular extensions to a specific directory
 - With Keycloak.X we need to provide those `jars` to the `build` command in the `providers` folder
 
We are going to explore a seamless integration for the Quarkus Augmentation and we will integrate something on those lines there.

**Comment by vmuzikar** [comment]
Investigation is done. We will introduce init image if needed for downloading the extensions.
