### ISSUE TITLE
Initialisation of SamlAuthenticationPreprocessors from the SamlSessionUtils.getSamlAuthenticationPreprocessorIterator are not initialised using the factory 

### ISSUE THREAD

**Issue by bjconlan** [keycloak/keycloak#9441]
### Describe the bug

If a custom `SamlAuthenticationPreprocessor` is introduced which uses the `KeycloakSession` then it will throw a null pointer exception when its created/used via the `SAMLIdentityProvider`.

This is due to the fact that the `SamlAuthenticationPreprocessor`(s) are resolved using the [SamlSessionUtils.getSamlAuthenticationPreprocessorIterator method](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/saml/SamlSessionUtils.java#L71) which creates the object using the default constructor and not the `ProviderFactory.create` method.

### Version

15.0.1

### Expected behavior

The SamlAuthenticationPreprocessors should be created/populated with a referenceable  instance of the `KeycloakSession` session which is used when creating and instance via the `ProviderFactory.create` method.

### Actual behavior

If an implementation of the `SamlAuthenticationPreprocessor` attempts to use the `KeycloakSession` instance when build via the `SamlSessionutils.getSamlAuthenticationProviderIterator` then when the preprocessor attempts to access the `KeycloakSession` it will cause a `NullPointerException`

### How to Reproduce?

Implement a SamlAuthenticationPreprocessor ie:
```
public TestSamlAuthenticationPreprocessor extends SamlAuthenticationPreprocessor {
  private KeycloakSession session;
  
  @Override
  public SamlAuthenticationPreprocessor create(KeycloakSession session) {
    this.session = session;
    return this;
  }

  @Override
  public String getId() {
    return "npe-throwing-session-preprocessor";
  }

  @Override
  public AuthnRequestType beforeSendingLoginRequest(AuthnRequestType authnRequest, 
  AuthenticationSessionModel clientSession) {
    System.out.println(this.session.getContext()); // do anything with the session will cause an NPE
    return authnRequest;
  }
}
```

And add the TestSamlAuthenticationPreprocessor into the `org.keycloak.protocol.saml.preprocessor.SamlAuthenticationPreprocessor` service metdata.

Perform a SAML login.

### Anything else?
I imagine the desired change would look like (but not sure what the test will look like hence no PR)
```
    public static Iterator<SamlAuthenticationPreprocessor> getSamlAuthenticationPreprocessorIterator(KeycloakSession session) {
        return session.getKeycloakSessionFactory().getProviderFactoriesStream(SamlAuthenticationPreprocessor.class)
                .filter(Objects::nonNull)
                .map(providerFactory -> (SamlAuthenticationPreprocessor)providerFactory.create(session))
                .iterator();
    }
```

**Comment by simse07** [comment]
Hi @bjconlan,
do you have a working example on how to register a custom SamlAuthenticationPreprocessor?
I implemented the interface and added the META-INF.services but it is not hooked up.

**Comment by bjconlan** [comment]
> Hi @bjconlan, do you have a working example on how to register a custom SamlAuthenticationPreprocessor? I implemented the interface and added the META-INF.services but it is not hooked up.

Unfortunately no. I don't recall anything different from the normal provider registration process in keycloak which is as you described (ie registering the implementation with the appropriate provider descriptor service file). I currently don't have access to reference source code that triggered the creation of this ticket also cant provide much help regarding this either (if there were any gotchas).

**Comment by simse07** [comment]
@bjconlan thank you for your reply. I made it working after some time.
I missed adding my class reference in the `org.keycloak.protocol.saml.preprocessor.SamlAuthenticationPreprocessor`service metadata file.

I am wondering if we can make the preprocessor IDP specific. If I have 2 SAML IDPs, both will use the preprocessor, but this is most of the time not intended. But this is not in scope of this ticket.

**Comment by bernhof** [comment]
as far as I can tell, Keycloak never calls `create`. It does, however, call `postInit`, which gives you a session factory that you can use later to create a KeycloakSession. May be important for you to also bind it to the current realm (`session.getContext().setRealm(authSession.getRealm())`).
