### ISSUE TITLE
No restrictions on username

### ISSUE THREAD

**Issue by Ryonez** [keycloak/keycloak#9443]
### Describe the bug

New user creation allows any usernames like abc, 123,. There is no way to configure username policy. Need to be able to restrict fake/meaningless usernames.

Should be able to configure minimum characters at least.

Copied from https://issues.redhat.com/browse/KEYCLOAK-14173

Ended up having a user use a space, which has lead to issues on other services.

### Version

	16.1.0

### Expected behavior

To be able to set the kinda of usernames allowed.

### Actual behavior

No validation, a user can enter any name.

### How to Reproduce?

Make an account, go have with it and do things you wouldn't expect in a username.

### Anything else?

https://issues.redhat.com/browse/KEYCLOAK-14173
Apparently related to this to: https://issues.redhat.com/browse/KEYCLOAK-2355

**Comment by mvk37** [comment]
Validation policy should have a way to restrict characters which allowed in the name. Now I can enter name like this:

`<script>alert("xss")</script>@#$%^&*()_+!<>?[]{}|\`

Which looks very suspicious from XSS attack point of view. 

Validation policy should be not only for username but for all fields which user can enter.

**Comment by swaggboi** [comment]
Hello, we're experiencing this issue as well. We keep having user accounts created with a leading whitespace character so we'd like to just disallow whitespaces in the usernames at all.

**Comment by kroketio** [comment]
There is more weird stuff possible, like entering UTF-8 chars that look like normal latin chars, at which point it can become a security issue (e.g impersonating admins).

More control over usernames would be nice, for example the ability to set it via a regex rule.

**Comment by mvk37** [comment]
Similar problem is for realm HTML display name. It is not as critical as for user name as only admin users can access admin GUI. But it still should be addressed.

**Comment by sschu** [comment]
This can be realized by using the declarative user profile feature (currently in preview) and specifying appropriate validation rules for fields like username.

**Comment by ketchup201** [comment]
> This can be realized by using the declarative user profile feature (currently in preview) and specifying appropriate validation rules for fields like username.

This is only somewhat useful. Can you please provide instructions for where to find the feature, or provide a link to documentation for said feature?

**Comment by sschu** [comment]
Sure: https://www.keycloak.org/docs/latest/server_admin/#user-profile

**Comment by ketchup201** [comment]
Thank you so much! I just found it as you were posting it. This looks new as of v24 and is now released. Saved me a lot of headache. Much appreciated @sschu

**Comment by sschu** [comment]
With the new user profile being a supported feature, I think it is fine to close this issue now. Feel free to reopen it or add a new issue if you think anything is missing @Ryonez.
