### ISSUE TITLE
Error "invalid redirect_uri" occurred while backslash in redirect uri parameter

### ISSUE THREAD

**Issue by turlarion** [keycloak/keycloak#9450]
### Describe the bug

Entered backslash in encoded redirect_uri parameter and met a "invalid redirect_uri" error. 
Tried to reach endpoint "/auth/realms/{realm}/protocol/openid-connect/auth". 
As I found out, error occurred in class org.keycloak.protocol.oidc.utils.RedirectUtils in method verifyRedirectUri on line 88.

Link i tried to use looks like this line:

```
https://sso-test.domain.com/auth/realms/test/protocol/openid-connect/auth?access_type=online&client_id=test_client&redirect_uri=https%3A%2F%2Fsso-test-login.company.com%2Foauth%2Fcallback%3Faccountname%3DADTEST%5Cusername1&response_type=code&scope=openid+openid+email+profile&state=fcbfa5cf-2ead-4ae6-8d49-c89bbc0deaf6&response_type=code&scope=openid+openid+email+profile&state=fcbfa5cf-2ead-4ae6-8d49-c89bbc0deaf6
```

[Error happens here](https://github.com/keycloak/keycloak/blob/11.0.3/services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java#L88)

### Version

11.0.3

### Expected behavior

Correct auth flow

### Actual behavior

Invalid redirect_uri

### How to Reproduce?

[Error happens here](https://github.com/keycloak/keycloak/blob/11.0.3/services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java#L88)

**Comment by rmartinc** [comment]
Hi @turlarion!

The backslash is something you have to encode in the original URL, it's not allowed. So the `redirect_uri` parameter should be originally: 

`https://sso-test-login.company.com/oauth/callback?accountname=ADTEST%5Cusername1`

Which once encoded again to go to the `redirect_uti` parameter should be:

`https%3A%2F%2Fsso-test-login.company.com%2Foauth%2Fcallback%3Faccountname%3DADTEST%255cusername1`

If you check your URL the backslash is just encoded one time. When the keycloak server tries to construct the URI it throws an exception as backslash is a non allowed char. Please, in the client you are using, be sure you are encoding the original parameter value.

**Comment by rmartinc** [comment]
Closing this. Feel free to reopen if needed.
