### ISSUE TITLE
Upgrade Liquibase to 4.6.2

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#9476]
### Description

The Liquibase version used currently by Keycloak is 3.5.5, which is quite old and doesn't support CockroachDB. With the new storage implementation for Keycloak.X we need to support CockroachDB along with Postgres, so we need to start looking into upgrading Liquibase.

Besides supporting CockroachDB, several improvements were made in Liquibase 4, such as registration of extensions using the `ServiceLoader`, bug fixes, etc. Upgrading allows us to simplify the factories that register our custom extensions.

**Acceptance criteria**

1- There are reports that newer versions of Liquibase calculate the changelogs checksums a bit differently, which would cause issues for users migrating from previous Keycloak versions. Any upgrade work must ensure that all migration tests pass in multiple operating systems. At the very least, there must be a clear migration path for users that end up hitting invalid checksum issues. For example, it might acceptable to require users to run Liquibase's [clearCheckSums](https://docs.liquibase.com/commands/clearchecksums.html) command if that allows for a clean migration to a Keycloak version using Liquibase 4.6.2.

2- The new Liquibase might impact the performance of the Quarkus distribution. This distribution contains performance enhancements for Liquibase 3.5.5, so it might be necessary to carefully evaluate how the new Liquibase behaves and what enhancements can be made to deal with it's architecture, that is significantly different than that of Liquibase 3.5.5.

### Motivation

Main motivation is to use a Liquibase version that supports CockroachDB. It also allows for easier registration of custom extensions and incorporates many bug fixes.

**Comment by sguilhen** [comment]
### **Important findings about this task**

- **Classloading**

Liquibase now relies on Java's `ServiceLoader` using the thread context's classloader by default to load extensions, including all the implementations it provides (for example, all `Database` implementation, all `SqlGenerator`s, etc). This leads to issues on WildFly as the context classloader is the module classloader of the Keycloak deployment. As a result, Liquibase can't initialize its own extensions as the module classloader doesn't have access to the liquibase classes. 

This means we need to initialize Liquibase's `Scope` object in a block that sets the context classloader to that of the `model-jpa module`. So we need to call `Scope.getCurrentScope()` in the `DefaultLiquibaseConnectionProvider` initialization temporarily setting the thread context classloader. Then once, initialized, we can create a child `Scope` with the correct resource accessor and classloader and register this child scope as the default scope to be used for any future Liquibase operations.

- **Checksums**

All checkums computed by Liquibase have a format _version:checksum_value_, where version is the version of the checksum algorithm used by Liquibase (it encompasses the changeset normalization and the actual hashing algo). For example, a checksum produced by Liquibase 3.5.5 looks like this _**7:80b5db88a5dda36ece5f235be8757615**_

Liquibase 4.6.2 uses a checksum algorithm version **8**, which makes all the checksums previously computed by Liquibase for earlier versions of Keycloak incompatible with the new Liquibase version. There are a couple of different paths to handle this:
   **a)** Use the `<validCheckSum>` element in every changset we currently have, listing the previously computed version 7 checksum as a valid checksum. When Liquibase validates the changesets it takes this element into consideration and if the checksum currently stored in the `databasechangelog` table matches the value specified in the `<validCheckSum>` element, it accepts the changeset as valid.
   **b)** Use Liquibase's `clearCheckSums` command, that essentially sets all md5sum values in the `databasechangelog` table to `NULL`. When a new changeset is introduced, Liquibase automatically updates all checksums that are `NULL` in the database, re-computing the checksum values using the current algorithm.
   
Option **a)** is preferred as it allows for easier migration without the need to run any external command or enforcing users to set all values in the `databasechangelog` table to `NULL`. Also, in the case of a rollback to a previous version, option **a)** will work seamlessly, whereas option **b)** would require users to re-run the `clearCheckSums` command again to be reset all checksums to `NULL`.

**Comment by hmlnarik** [comment]
Documentation PR: keycloak/keycloak-documentation#1404
