### ISSUE TITLE
Login Failure with Infinispan Remote Cache

### ISSUE THREAD

**Issue by lukecalderon** [keycloak/keycloak#9487]
### Describe the bug

I've got Keycloak pointing at an Infinispan 13.0 remote cache, both hosted in Kubernetes as separate pods.

When trying to login to the admin console, the front-end errors and will not let me login, stating:
`Unexpected error when handling authentication request to identity provider`

I've verified the login attempt is taking place by supplying the incorrect password, and it does seem to be working.

In the log when I'm met with this failure, I get the following error thrown:
`[org.keycloak.services] (default task-9) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper (org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader 'org.keycloak.keycloak-model-infinispan@16.0.0' @10ec5133)`

I've tested this with KeyCloak 16.1, 16.0 and 15.1, and have the same issue in all of them. I have completely removed any authentication to the Infinispan caches and checked anonymous authentication is working. Based off the error, I do not believe the request is actually leaving Keycloak as I cannot see any entries in the cache in Infinispan.

I've been configuring as per the KeyCloak server configuration guide here: https://www.keycloak.org/docs/latest/server_installation/#assembly-setting-up-crossdc

### Version

16.0.0

### Expected behavior

Login to the admin console should be successful, and I should see a loginSession in the Infinispan cache

### Actual behavior

`[org.keycloak.services] (default task-9) KC-SERVICES0013: Failed authentication: java.lang.ClassCastException: class org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity cannot be cast to class org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper (org.keycloak.models.sessions.infinispan.entities.RootAuthenticationSessionEntity and org.keycloak.models.sessions.infinispan.changes.SessionEntityWrapper are in unnamed module of loader 'org.keycloak.keycloak-model-infinispan@16.0.0' @10ec5133)`

### Anything else?

See attached standalone-ha.xml file from one of the deployments that are affected
[kc-standalone.txt](https://github.com/keycloak/keycloak/files/7842383/kc-standalone.txt)

.

**Comment by avanlangup** [comment]
How did you solve it eventually ?
