### ISSUE TITLE
Built-in clients can no longer be deleted

### ISSUE THREAD

**Issue by nblock** [keycloak/keycloak#9496]
### Describe the bug

In Keycloak 15.0.2 it was possible to delete built-in clients of a realm (`account`, `account-console`, `broker`, …). Trying the same with Keycloak 15.1.0 or 15.1.1 yields an exception.

### Version

15.1.1

### Expected behavior

Just as in Keycloak 15.0.2, it should be possible to delete built-in clients.

### Actual behavior

When trying to delete a built-in client, the browser's account console has the following exception:

```
Possibly unhandled rejection: {"data":{"error":"invalid_request","error_description":"Could not delete client"},"status":400,"config":{"method":"DELETE",…
```

### How to Reproduce?

- Start Keycloak 15.1.0 or 15.1.1
- Login as admin
- Create a new realm `test`
- Switch to realm `test` and navigate to `Clients`
- Hit the `Delete` button

**Comment by stianst** [comment]
This is expected behaviour as you should not be deleting internal clients.
