### ISSUE TITLE
Expression resolution doesn't work for SPI "enabled" setting due to unneccesary Boolean.valueOf() call

### ISSUE THREAD

**Issue by mwalser** [keycloak/keycloak#9499]
### Describe the bug

I'm currently attempting to write a custom SPI. My plan was to use an environment variable to control whether that SPI is enabled. For this I added the following to a startup script:

```
/subsystem=keycloak-server/spi=external-event-publisher/provider=kafka/:add( \
    properties={ \
        foo => "${env.EVENTS_PUBLISHER_KAFKA_FOO}", \
        bar => "${env.EVENTS_PUBLISHER_KAFKA_BAR}" \
    }, \
    enabled = "${env.EVENTS_PUBLISHER_KAFKA_ENABLED}" \
)
```

However, while the properties for `foo` and `bar` are correctly resolved, `enabled` always stays at `false`.

After some debugging, I found out that Keycloak passes the value of `enabled` to `Boolean.valueOf()` **before** the expression is resolved:
https://github.com/keycloak/keycloak/blob/ab9413b48c742fefc3cbfa3422ea077354921135/wildfly/server-subsystem/src/main/java/org/keycloak/subsystem/server/extension/KeycloakSubsystemParser.java#L145

When using a debugger to remove the `Boolean.valueOf()` call everything works fine and the expression is resolved correctly. I strongly suspect that `Boolean.valueOf()` is not needed in this place.

### Version

16.1.0

### Expected behavior

Expressions can be used to control whether an SPI is enabled

### Actual behavior

Every value other than "true" causes the SPI to be disabled

### How to Reproduce?

* Create a custom SPI
* Set the value for `enabled` to `${env.CUSTOM_SPI_ENABLED}`
* Set the environment variable `CUSTOM_SPI_ENABLED` to `true`
* Start keycloak
* Observe the SPI not being enabled

### Anything else?

I would be willing to contribute a fix for this if this is deemed to be a bug

**Comment by stianst** [comment]
This is not a bug as not all fields supports environment variables. For a better approach update your provider to implement:

https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/provider/EnvironmentDependentProviderFactory.java#L44

Then check the value of the environment variable directly from there.

**Comment by mwalser** [comment]
Thanks for the answer @stianst. It was [this comment by James R. Perkins](https://stackoverflow.com/questions/61382945/cli-scripting-enable-provider-using-environment-properties#comment108647803_61382945) in Stackoverflow that even lead me down this path
