### ISSUE TITLE
Upgrade WebAuthn4j dependency version

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#9506]
### Description

The current version of `WebAuthn4j` dependency is `0.12.0.RELEASE`. It'd be good to upgrade it.

**Comment by ynojima** [comment]
I'd like to contribute this case (I'm author of webauthn4j).

**Comment by mabartos** [comment]
@ynojima That's great! Thanks! Have you already had a chance to look at it?

**Comment by ynojima** [comment]
I haven't started. I will release webauthn4j 0.19.0.RELEASE on Feb. 1st, and I will use it.
I also want to wait #9502 if possible.

**Comment by mabartos** [comment]
@ynojima Ok, great. With the GH actions, it'd be more challenging than I thought, so don't rely on that a lot. We can then execute pipeline tests.

**Comment by ynojima** [comment]
@mabartos Sorry for long delay, I finally submitted a pull-request for this issue: https://github.com/keycloak/keycloak/pull/11927
Could you prepare Red Hat build webauthn4j 0.19.3.RELEASE?
