### ISSUE TITLE
Rename "Resident key" to "Discoverable Credential"

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#9508]
### Description

The latest spec has renamed the concept of "Resident Key" or "Resident Credential" to "Discoverable Credential". Both UI and documentation contain deprecated names and needs to be updated to refer to the up-to-date nomenclature.

See: https://issues.redhat.com/browse/KEYCLOAK-16796

**Comment by tnorimat** [comment]
@mabartos Hello, if you would not work on the issue, could I take over it? This issue is also related to [passkeys](https://github.com/keycloak/keycloak/issues/23656).
