### ISSUE TITLE
User deletion and recreating in local database when timeout in LDAP

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#9520]
It is observed that few Keycloak LDAP users are getting deleted and recreated automatically even when there is no change in LDAP side. Upon investigation, it is observed that the user deletion is caused by a Keycloak bug in org.keycloak.storage.ldap.idm.store.ldap.LDAPOperationManager.getFilterById(String id).
This method is used to build a string which will be used to query the LDAP server based on an attribute ID. The method contains special handling if it is the 'objectGUID' attribute which is being filtered; in this case the method first makes an LDAP call (which Keycloak calls "GUIDResolve") to enable it to perform special objectGUID formatting. If this call succeeds, then the proper filter is returned and ultimately the correct object is retrieved from LDAP. The bug is if the GUIDResolve call fails, causing a NamingException to be thrown. Here is the relevant code:
try {
                Attributes attributes = execute(new LdapOperation<Attributes>() {

                    @Override
                    public Attributes execute(LdapContext context) throws NamingException {
                        return context.getAttributes(strObjectGUID);
                    }

                    @Override
                    public String toString() {
                        return new StringBuilder("LdapOperation: GUIDResolve\n")
                                .append(" strObjectGUID: ").append(strObjectGUID)
                                .toString();
                    }

                });

                byte[] objectGUID = (byte[]) attributes.get(LDAPConstants.OBJECT_GUID).get();

                filter = "(&(objectClass=*)(" + getUuidAttributeName() + LDAPConstants.EQUAL + LDAPUtil.convertObjectGUIDToByteString(objectGUID) + "))";
            } catch (NamingException ne) {
                filter = null;
            }

As can be seen above, the NamingException is caught and ignored; the method them falls through to its default handling (for non-objectGUI attributes) which returns an incorrect filter. Keycloak then queries LDAP using the incorrect filter and receives back an empty result. Based on this it thinks the user does not exist in LDAP and so deletes it from the local DB.

So a user may be deleted if, for example, a communications timeout to the LDAP server occurs during the GUIDResolve call.

Here is an example from the  logs of a correctly formatted filter:

 filter: (&(objectClass=*)(objectGUID=60d1ef00-ecfe-47de-8f5b-d9d0c91a690c))
and here is the equivalent filter which has been properly encoded:

 filter: (&(objectClass=*)(objectGUID=\00\ef\d1\60\fe\ec\de\47\8f\5b\d9\d0\c9\1a\69\0c))
From the logs, we can see that the incorrect filter is used before each user deletion.

This will need to be fixed in the Keycloak source code.

### Version

11.0

### Expected behavior

An exception should be rethrown instead of searching with a bad filter again and deleting the user.

### How to Reproduce?

Enable 2FA and try to create a timeout from LDAP for user search by id.

**Comment by hpwahyao** [comment]
> 

Hi sir, do you find any solution on this? I encounter the exact issue as yours. Thanks

**Comment by stianst** [comment]
Looks like this is related to:
https://github.com/keycloak/keycloak/issues/12257

**Comment by hpwahyao** [comment]
Hi all,
Just an intermittent updates.

M quite sure the issue is related with LDAP user sync.

We disabled the LDAP auto sync since last week. It was a peaceful week.
While we manually sync the LDAP just now. We lost a user entry again in
production environment.


We try to download the keycloak source code to see if can find some clue or
not. It’s very much appreciate if could share the package name of LDAP
sync. It will save our time a lot.

Thanks in advance

**Comment by darpanj1993** [comment]
Hello,

Is there any progress/known-solution OR workaround on this issue?

Thanks.

**Comment by hpwahyao** [comment]
Hi all,
Just to update here, we added more debugging statements in the source code
which I downloaded in May 2022 and compile the build and deployed. Now
observing the issue, hope to get more info on where throwing the error.

We did not apply the suggestions on changing the search filter.

On a side note, We realise the relevant LDAP code is moved to the legacy
folder in the latest GitHub repository.

Thanks

**Comment by pravsjv** [comment]
Tested the same with keycloak 16 and this issue is fixed as LDAP works fine.

**Comment by hpwahyao** [comment]
Hi, u said it’s fixed.

What’s the root cause? how did you fix it?

**Comment by pravsjv** [comment]
@hpwahyao The code has been refactored in keycloak 16 in this area where they are appending a custom filter along with ObejectGUid which is working fine in queries response to LDAP with active Directory.

**Comment by hpwahyao** [comment]
Noted. Will upgrade keycloak to the latest version in this case.

Thanks
