### ISSUE TITLE
Dist.X: Show-Config does not show always the right applied configuration

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#9525]
### Describe the bug

Under some circumstances, show-config does not show the currently applied configuration in "runtime configuration", but configuration from another profile instead.

### Version

<=16.1.0

### Expected behavior

After running kc.sh start-dev, the value of `kc.db` when running the show-config command should be h2-file, as dev uses h2-file. 

### Actual behavior

value `kc.db` is still set to postgres. same goes for the other values previously set for the prod profile. but not for all. See attached picture for an example
<img width="879" alt="Screenshot 2022-01-11 at 18 10 57" src="https://user-images.githubusercontent.com/89905860/148989291-a4494efa-f43a-45f8-8338-481afbb68b3d.png">
 

### How to Reproduce?

1. add e.g. 
```
%prod.db=postgres
%prod.db.username=mydbuser
%prod.db.password=mydbpassword
%prod.db.url=jdbc:postgresql://localhost/kc_db
```
to keycloak.properties

2. run `kc.sh build`

3. run `kc.sh start-dev` 

4. run `kc.sh show-config`

**Comment by pedroigor** [comment]
@DGuhr I can not reproduce the problem. Probably due to the last changes we did such as removal of configuration profiles.

Could you please, check if that is true?

**Comment by DGuhr** [comment]
@pedroigor sadly, issue is still there. See attached screenshot.
![Screenshot 2022-02-03 at 10 50 58](https://user-images.githubusercontent.com/89905860/152320032-1a4c8597-c874-4821-8433-16d0efe94147.png)

**Comment by pedroigor** [comment]
I noticed that you are appending the `%prod` profile to options. Does it also happen if the profile is ommited?
