### ISSUE TITLE
Recovery authentication codes

### ISSUE THREAD

**Issue by rh-iatanaso** [keycloak/keycloak#9540]
### Description

Feature request to add support for recovery authentication codes .
Recovery ( backup ) authentication codes can be used to authenticate in case the user does not have available his phone or otp device. Quite few public services have implemented similar feature. User can print them and store them and then use them at later point.
Please find more details in the discussion linked to this issue.
We also have submitted PR that can be found at https://github.com/keycloak/keycloak/pull/8730.

### Discussion

https://github.com/keycloak/keycloak/discussions/8518

**Comment by heddn** [comment]
Eagerly watching the development of this feature. What version of KC is this slated to release? a point release of 6.x or is this more like a 7.x feature? And what is the timeline for said potential release?
