### ISSUE TITLE
Rename or import a realm is incomplete 

### ISSUE THREAD

**Issue by dierberg** [keycloak/keycloak#9541]
### Describe the bug

Renaming a realm does not change "Valid Redirect URIs" and "Base URL" of client "account-console". The same problem occurs at import of a realm with new name. 

### Version

15.0.2

### Expected behavior

URIs and URL contains new realm part.

### Actual behavior

URIs and URL contains old string.

### How to Reproduce?

Rename a Realm and check account-console settings

**Comment by stianst** [comment]
What is the values of the account console before the rename? They should be using variables for the URLs that are dynamically resolved at runtime.

**Comment by dierberg** [comment]
Old realm name was "SDG" renamed to "HKA":
![grafik](https://user-images.githubusercontent.com/3403768/151338435-f2166759-9f21-479a-b20e-e35d23cff3d9.png)

**Comment by yelhouti** [comment]
I can confirm that this issue happens with client account-console but not account.
I stumbled upon this while working on a realm re-import an already imported realm under a different name (where I would like to rename everything, change returnURIs, ids...) 
It a shame that this is not provided OOTB by keycloak...

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.

This looks that it may be easy to fix, so can be good for someone, who want to learn Keycloak and add some contribution to it. It is probably just doing the same for the `account-console` like done for some other clients (EG. `security-admin-console`).
