### ISSUE TITLE
Multiple warnings caused by typed varargs in TokenVerifier

### ISSUE THREAD

**Issue by dteleguin** [keycloak/keycloak#9555]
### Description

The [org.keycloak.TokenVerifier::withChecks()](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/TokenVerifier.java#L295) method declaration causes the following warnings:
* a possible heap pollution warning at declaration site;
* 16 more unchecked generic array creation warnings at call sites in `keycloak-services`.

As we neither cast `checks` to `Object[]` nor rely on it being an instance of `Predicate[]`, it is safe to suppress the warning. (Check out this for more info on the warnings: [1](https://stackoverflow.com/questions/12462079/possible-heap-pollution-via-varargs-parameter) [2](https://stackoverflow.com/questions/11185774/java-1-7-varargs-function-reported-as-unchecked-warning) [3](https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.12.2))

Additionally, there are a few warnings related to unchecked constructor calls.

**Comment by pedroigor** [comment]
@dteleguin I'm glad you are still around.

Out of curiosity, does heap pollution has any impact on the runtime in terms of memory footprint? I can see it could potentially interfere in compiler optimizations though.

**Comment by dteleguin** [comment]
Glad to see you too @pedroigor :)

Couldn't find any info on memory effects of heap pollution; but I can imagine if we have a parametrized collection, and its backing structure contains only elements of one type, then it would be allocated in a way more optimal than if it contained heterogeneous elements (due to heap pollution). Anyway, looks like the code in TokenVerifier is safe and doesn't allow this, so we should be unaffected by heap pollution (and its consequences), shouldn't we?

**Comment by pedroigor** [comment]
Thanks. I think so.

We have other places to change too, I think. But it is beyond what you are working right now.
