### ISSUE TITLE
JavaScript providers - JAR with long file names causes PSQLException

### ISSUE THREAD

**Issue by mkreis** [keycloak/keycloak#9571]
### Describe the bug

When creating a JAR file with JavaScript providers, the .js file name can be chosen arbitrary.
Then using a long file name (in my case "authenticator-session2attrib.js"), there is an exception when adding this provider to an authentication flow:

`org.postgresql.util.PSQLException: ERROR: value too long for type character varying(36)`

### Version

16.1.0

### Expected behavior

There should be no issues with long file names when importing JavaScript providers from a JAR file.
Adding such a provider to a flow should not result in any error.

### Actual behavior

Providers from the JAR are imported/deployed, but adding them to an authentication flow causes an exception.

`org.postgresql.util.PSQLException: ERROR: value too long for type character varying(36)`

### How to Reproduce?

1. Create  a JAR file with the following contents:

META-INF/keycloak-scripts.json
```
{
  "authenticators": [
    {
      "name": "Store reference in session",
      "fileName": "authenticator-ref2session.js",
      "description": "Store reference query param in session"
    },
    {
      "name": "Set reference as attribute",
      "fileName": "authenticator-session2attrib.js",
      "description": "Store reference from session as custom attribute"
    }
  ],
  "policies": [],
  "mappers": []
}
```

authenticator-ref2session.js
```
function authenticate(context) {
    context.success();
}
```
authenticator-session2attrib.js
```
function authenticate(context) {
    context.success();
}
```

2. Copy this file into folder keycloak/standalone/deployments
3. Add JVM Option `-Dkeycloak.profile.feature.scripts=enabled`
4. Restart the server
5. Make a copy of authentication flow "registration"
6. Add Execution "Set reference as attribute" to the new flow
--> The error described above will occur

**Comment by TXLuong** [comment]
Hi @mkreis , I wonder whether the name of json file matters (which in this case, you named it keycloak-scripts.json), you've experienced with it so can you share it me ?
Moreover, this is case you created 2 authenticator, did this mean creating 2 providers?
Thank you! I hope you will reply me.

**Comment by mkreis** [comment]
Hi @TXLuong, yes the correct filename `keycloak-scripts.json` is important. The JavaScript files can have any name, it just needs to match the content of the .json file.
Have a look here: https://www.keycloak.org/docs/latest/server_development/index.html (search for keycloak-scripts.json to find the right section).

Yes, I created two providers. You might need only one.

**Comment by TXLuong** [comment]
@mkreis , thank you so much.
I will try this
