### ISSUE TITLE
When removing client, remove service account even if disabled

### ISSUE THREAD

**Issue by guusdk** [keycloak/keycloak#9577]
### Describe the bug

While working on #9563 I noticed this snippet in `org.keycloak.models.cache.infinispan.RealmCacheSession#removeClient`

```java
if (client.isServiceAccountsEnabled()) {
    UserModel serviceAccount = session.users().getServiceAccount(client);

    if (serviceAccount != null) {
        session.users().removeUser(realm, serviceAccount);
    }
}
```

Shouldn't the service account be removed even if the client has the feature disabled? 

### Version

Head of main

### Expected behavior

Always remove a service account associated to a client, even if the client has disabled the feature.

### Actual behavior

Untested, I've only been looking at code:

A service account associated to a client is removed only when the service account feature enabled.

**Comment by mposolda** [comment]
I am adding this with the label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Will be hopefully fixed with the PR from the Keycloak community.
