### ISSUE TITLE
migrate-standalone.cli broken since 16.0 release

### ISSUE THREAD

**Issue by pschichtel** [keycloak/keycloak#9586]
### Describe the bug

The migration script, that the upgrade guide tells me to run after upgrading, fails to execute. This happens both on upgraded and fresh instances after for versions 16 and newer.

The problematic sections of the script:

* lines 253-257:
  ```
  if (outcome == failed) of /core-service=management/security-realm=ApplicationRealm/server-identity=ssl:read-resource
      echo Adding keystore to ApplicationRealm...
      /core-service=management/security-realm=ApplicationRealm/server-identity=ssl:add(keystore-path=application.keystore,keystore-relative-to=jboss.server.config.dir,keystore-password=password,alias=server,key-password=password,generate-self-signed-certificate-host=localhost)
      echo
  end-if
  ```
* lines 462-466
  ```
  if (outcome == success) of /subsystem=elytron/http-authentication-factory=application-http-authentication/:read-resource
      echo Removing application-http-authentication from elytron subsystem
      /subsystem=elytron/http-authentication-factory=application-http-authentication:remove
      echo
  end-if
  ```

Removing these sections before running the script resolves the issue, e.g.:

```bash
sed -i '253,257d;462,466d' "$JBOSS_HOME/bin/migrate-standalone.cli"
```

### Version

16 and newer

### Expected behavior

Since the script is unchanged from keycloak 15's version, the expected output would be identical to keycloak 15's output:

```
bash-4.4$ "$JBOSS_HOME/bin/jboss-cli.sh" --file="$JBOSS_HOME/bin/migrate-standalone.cli"

*** WARNING ***

** If the following embed-server command fails, manual intervention is needed.
** In such case, remove any <extension> and <subsystem> declarations referring
** to the removed smallrye modules from the standalone.xml file and rerun this script.
** For details, see Migration Changes section in the Upgrading guide.
** We apologize for this inconvenience.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
*** Begin Migration ***

Adding eviction strategy to keycloak users cache container...
{"outcome" => "success"}
{"outcome" => "success"}

Updating authorization cache container..
{"outcome" => "success"}
{"outcome" => "success"}

Adding spi=userFederatedStorage...
{"outcome" => "success"}

Updating eviction and expiration in local-cache=keys...
{"outcome" => "success"}
{"outcome" => "success"}
{"outcome" => "success"}

Adding eviction strategy to keycloak realms cache...
{"outcome" => "success"}
{"outcome" => "success"}

Removing declaration for userFederatedStorage SPI
{"outcome" => "success"}

Updating eviction in local-cache=authorization...
{"outcome" => "success"}

Adding channel-creation-options READ_TIMEOUT to ejb3 remote
{"outcome" => "success"}

Removing eviction from hibernate entity cache and replacing with object-memory
{"outcome" => "success"}
{"outcome" => "success"}

Removing eviction from hibernate local-query cache and replacing with object-memory
{"outcome" => "success"}
{"outcome" => "success"}

Removing eviction from keycloak realms cache and replacing with object-memory
{"outcome" => "success"}
{"outcome" => "success"}

Removing eviction from keycloak users cache and replacing with object-memory
{"outcome" => "success"}
{"outcome" => "success"}

Removing eviction from keycloak authorization cache and replacing with object-memory
{"outcome" => "success"}
{"outcome" => "success"}

Removing eviction from keycloak keys cache and replacing with object-memory
{"outcome" => "success"}
{"outcome" => "success"}

Changing JNDI reference in connectionsInfinispan SPI
{"outcome" => "success"}
{"outcome" => "success"}

Removing READ_TIMEOUT option from remote service from ejb3 subsystem
{"outcome" => "success"}

{"outcome" => "success"}
Removed config for unused fixed hostname provider
Adding base metrics subsystem prefix to Keycloak...
{"outcome" => "success"}

Setting value of to default-datasource attribute in JPA subsystem to 'undefined'
{"outcome" => "success"}

*** End Migration ***
```

### Actual behavior

```
bash-4.4$ "$JBOSS_HOME/bin/jboss-cli.sh" --file="$JBOSS_HOME/bin/migrate-standalone.cli"

*** WARNING ***

** If the following embed-server command fails, manual intervention is needed.
** In such case, remove any <extension> and <subsystem> declarations referring
** to the removed smallrye modules from the standalone.xml file and rerun this script.
** For details, see Migration Changes section in the Upgrading guide.
** We apologize for this inconvenience.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-18.0.0.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
*** Begin Migration ***

Adding eviction strategy to keycloak users cache container...
{"outcome" => "success"}
{"outcome" => "success"}

Updating authorization cache container..
{"outcome" => "success"}
{"outcome" => "success"}

Adding spi=userFederatedStorage...
{"outcome" => "success"}

Updating eviction and expiration in local-cache=keys...
{"outcome" => "success"}
{"outcome" => "success"}
{"outcome" => "success"}

Adding eviction strategy to keycloak realms cache...
{"outcome" => "success"}
{"outcome" => "success"}

Removing declaration for userFederatedStorage SPI
{"outcome" => "success"}

Updating eviction in local-cache=authorization...
{"outcome" => "success"}

Adding keystore to ApplicationRealm...
Failed to get the list of the operation properties: "WFLYCTL0030: No resource definition is registered for address [
    ("core-service" => "management"),
    ("security-realm" => "ApplicationRealm"),
    ("server-identity" => "ssl")
]"
```

### How to Reproduce?

1. start a new blank keycloak instance, e.g.:
    `docker run --rm -it --name kc16 jboss/keycloak:16.0.0`
2. run the script, e.g.:
    ```bash
    docker exec -it kc16 bash
    "$JBOSS_HOME/bin/jboss-cli.sh" --file="$JBOSS_HOME/bin/migrate-standalone.cli"
    ```

### Anything else?

My assumption is that this broke with the WildFly / Elytron upgrade, which (according to Keycloak 16's blog post) changed a lot about the configuration.

**Comment by GerryDominic** [comment]
I'm seeing similar problems running on baremetal.

bin/jboss-cli.sh --file=bin/migrate-standalone-ha.cli

*** WARNING ***

** If the following embed-server command fails, manual intervention is needed.
** In such case, remove any <extension> and <subsystem> declarations referring
** to the removed smallrye modules from the standalone-ha.xml file and rerun this script.
** For details, see Migration Changes section in the Upgrading guide.
** We apologize for this inconvenience.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/keycloak/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-18.0.0.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
*** Begin Migration ***


Adding spi=userFederatedStorage...
{"outcome" => "success"}

Updating eviction and expiration in local-cache=keys...
{"outcome" => "success"}
{"outcome" => "success"}
{"outcome" => "success"}

Updating eviction in local-cache=users
{"outcome" => "success"}
{"outcome" => "success"}

Adding eviction strategy to keycloak realms cache...
{"outcome" => "success"}
{"outcome" => "success"}

Removing declaration for userFederatedStorage SPI
{"outcome" => "success"}

Adding keystore to ApplicationRealm...
Failed to get the list of the operation properties: "WFLYCTL0030: No resource definition is registered for address [
    ("core-service" => "management"),
    ("security-realm" => "ApplicationRealm"),
    ("server-identity" => "ssl")
]"

**Comment by stianst** [comment]
With the WildFly 25 upgrade we where not able to provide a migration script due to the amount of changes. See https://www.keycloak.org/docs/latest/upgrading/#migrating-to-16-0-0

The upgrade guide has been updated with a note stating that the migration scripts are not always possible, see:
https://www.keycloak.org/docs/latest/upgrading/#_install_new_version

It's not an ideal situation for sure, but it was simply necessary to be able to upgrade to WildFly 25.

**Comment by pschichtel** [comment]
@stianst I don't think this script can *ever* work again. It should be fixed or discarded.

**Comment by tgurr** [comment]
> With the WildFly 25 upgrade we where not able to provide a migration script due to the amount of changes. See https://www.keycloak.org/docs/latest/upgrading/#migrating-to-16-0-0
> 
> The upgrade guide has been updated with a note stating that the migration scripts are not always possible, see: https://www.keycloak.org/docs/latest/upgrading/#_install_new_version
> 
> It's not an ideal situation for sure, but it was simply necessary to be able to upgrade to WildFly 25.

I have a question regarding this, since in the links you've posted `Upgrading Keycloak Server` - `Running the Standalone Mode Upgrade Script` is mentioned even for version 16.1.1. Previously I *always* ran the script when upgrading keycloak as stated/suggested in the documentation.

It should also be clarified on when exactly one has to actually run the script and when it is not neccessary. Is it required only when upgrading from really old versions? Right now the section is very confusing especially in regards to this bug that it is broken.

I'm with @pschichtel here, it should be either fixed or at least removed from the documentation. Does that mean since this bug has been closed that it is and also won't be neccessary anymore to run the script in future upgrades and be sure not run into any issues?

**Comment by pschichtel** [comment]
@stianst I'm also wondering: For people using the container-based deployments and practically zero changes to the configuration file (standalone.xml), is this script relevant at all? Because to me it seems like all it does is migrate the jboss/wildfly configuration. If that is true it might be worth mentioning it in the upgrade guide.

**Comment by Mushoz** [comment]
@stianst The documentation is really unclear on this. I am upgrading from 13, and am wondering how I should upgrade. The documentation leaves much to be desired. The upgrade section DOES mention running the script, but as people have pointed out here, it fails. So from that, I gather I should NOT run it. However, I am upgrading from version 13. Should I first upgrade to the latest pre-16 version (using the script), and then upgrade to 16 (not using the script)? Or can I go straight from 13 to 16 (not running the script).

I fully agree that the script should be removed and/or the documentation updated, because at the moment it is really unclear, and it doesn't seem like I am the only one.

**Comment by mazbeh** [comment]
Hello every body,
i am trying to update keycloak from 12 to 17. According to docs of keycloak i could not do it! It seems that i have also the same problems as you. 
Could you please give me some tipps how updating to keycloak 17 could be?
Thanks alot !!!

**Comment by pschichtel** [comment]
@mazbeh the release blog post say it all: find out what changes you did to the wildfly configuration and manually apply equivalent changes to the vanilla configuration of version 17. The migrate-standalone.cli script will not work. If you intent to switch to the quarkus distribution, then configuration will look completely different anyway. I just switched to the quarkus distribution and configuration is a lot simpler.

**Comment by mazbeh** [comment]
oh, thanks alot for  replaying !!!
i have too many realms ann clients and ... that are already configured in keycloak(12). I dont know , how should i take them also to the new version -_-

**Comment by mazbeh** [comment]
@pschichtel Thank you so much for your response !
The only changes that i have done before ( to the wildfly configuration in the standalone.xml) file, was the ssl settings. According to the keycloak docs i can set my certificate with the use of ,, --https-certificate-file ,, and ,, --https-certificate-key-file ,, in keycloak version 17 . In the the running version that i have (12 ), i have not configured any db and keycloak uses it default db (H2). My question is, if i start keycloak with ,,sudo sh kc.sh,, , will the h2 db be from the last version automatically updated and i can  have all of my realms and clients in the new version ?

Sorry, i am a little bit new to this topic ;)

**Comment by stianst** [comment]
> @pschichtel Thank you so much for your response !
> The only changes that i have done before ( to the wildfly configuration in the standalone.xml) file, was the ssl settings. According to the keycloak docs i can set my certificate with the use of ,, --https-certificate-file ,, and ,, --https-certificate-key-file ,, in keycloak version 17 . In the the running version that i have (12 ), i have not configured any db and keycloak uses it default db (H2). My question is, if i start keycloak with ,,sudo sh kc.sh,, , will the h2 db be from the last version automatically updated and i can  have all of my realms and clients in the new version ?
> 
> Sorry, i am a little bit new to this topic ;)
Switch from WildFly to Quarkus dist in 17 doesn't change anything on the dB level. H2 will be upgraded. However, we strongly advice against using H2 in production.

**Comment by mazbeh** [comment]
@stianst i will try it and let you know if it works.
and thanks alot for the info !
