### ISSUE TITLE
In the User Federation, use MSSQL to report the error of SSL.

### ISSUE THREAD

**Issue by anjoy8** [keycloak/keycloak#9591]
### Describe the bug

**1、I started a service with docker and made a persistence scheme with MySql.**

```
docker run  -dt  --name keycloak-db  -p 801:8080 \
-e DB_VENDOR=mysql -e DB_USER=root   \
-e DB_PASSWORD=root -e DB_ADDR=xxxxxxxxxx -e DB_PORT=3096 \
-e DB_DATABASE=Keycloak -e KEYCLOAK_USER=keycloak -e KEYCLOAK_PASSWORD=keycloak \
jboss/keycloak-my

```

**2、Then, in the User Federation, use a SqlServer as a third-party data source.**
![image](https://user-images.githubusercontent.com/28941816/149731256-abdbb69c-0b27-4f4c-9005-500e2a5d013c.png)

**3、The service can start normally, but when I asked all users, I reported an error.**
Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: : com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Certificates do not conform to algorithm constraints". ClientConnectionId:36efacc2-c7a3-46eb-9c5c-dc3dc3573275
![image](https://user-images.githubusercontent.com/28941816/149731418-52d604ea-ed6c-4138-a448-27fbb86a90a0.png)

### Version

FROM jboss/keycloak:latest

**Comment by hmlnarik** [comment]
Thanks for reporting this issue.
This could be an enhancement request for adding a test connection button in the configuration UI. 
However, after reviewing this issue we believe it does not have sufficient priority to be resolved. If you think otherwise, feel free to reopen this issue and supplying a PR with implementation.
