### ISSUE TITLE
Missing DB constraints for JPA Map Storage for Clients

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#9610]
### Description

The existing code code as part of the Map storage can attempt a best-effort to present inconsistencies, but this can't rely on constraints or unique keys on the storage provider, as different storage providers have different abilities.

The current JPA Map Storage implementation doesn't have database constraints for clients, which could lead to inconsistent data (for example two clients with the same name within a realm). 

### Motivation

Different map providers need to come up with solutions that suit their storage back ends to prevent or repair inconsistencies.

For the JPA Map Storage implementation the implementation matching the technology available would be unique keys and constraints. 

As a best-effort attempt the MapClientProvider should trigger a search by clientId to see if the clientId is already taken.

### Details

Constraints to be added: 
* in table client: clientId + realmId unique - implemented as unique index
* in table client_attribute: fk_client + name unique - implemented as deferrable constraint to prevent issues with ordering of inserts/deletes with hibernate. Index for fk_client already exists, should be sufficient as number of attributes is expected to be low

MapClientProvider#addClient will receive a search-by-realm-and-clientId to do a best-effort prevention of duplicate clientIds in the realm.

**Comment by vramik** [comment]
Thank you very much @ahus1. 

I have just one comment regarding `client_attribute` table, client could have multi-valued attribute. It'd end up stored as multiple rows in the table with the same values in `fk_client` and `name`. I believe all three values from columns `fk_client`, `name` and `value` needs to checked for uniqueness. Please see https://github.com/keycloak/keycloak/blob/main/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/client/entity/JpaClientAttributeEntity.java#L99-L101 

One note: `value` column is `text` datatype so its length could be large. I'm not sure how it could affect it precisely.

**Comment by ahus1** [comment]
Thanks @vramik - I wasn't aware of multi-valued attributes. 

I had a look at the [ClientAttributeEntity](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/entities/ClientAttributeEntity.java), and found that it doesn't name a constraint on the Java level. For the equal() comparison, I see that it compares clientId and name, but not the value, what is then different from the JpaClientAttributeEntity. I am not sure what effect that would cause. 

For the constraints to work they should be added to the liquibase scripts, for documentation purposes I could add them to the JPA Entity as well as it has been done before, see [ClientEntity](https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/entities/ClientEntity.java).

Argument in favor: have the documentation in the code, argument against: it can get out of sync.

Any opinion on that?

**Comment by vramik** [comment]
There has been done a decision to make all attribute-containing map storage entities multi-valued, please see: https://issues.redhat.com/browse/KEYCLOAK-15572. 

You're right about  legacy `ClientAttributeEntity`, it supports only single-value attributes.

note: logical layer still uses single-value attributes for clients (and for some other objects as well), but map storage is ready to make the switch. I hope it makes sense. 

Regarding `@UniqueConstraint`, IMHO it might have sense to add it, even when there is a risk of getting out of sync.

**Comment by ahus1** [comment]
Thanks for sharing this decision/intent. I now looked at the MapClientAdapter and see that getAttributes() will return the first entry from a list. Looking closer at JpaClientEntity I see that IMHO the attributes are not ordered. 

I'll put a note on my list to ask to understand why (1) multivalued attribute values are ordered (List) and (2) if throwing an exception when there is more than one attribute value instead of returning the first or a random entry would be a more conservative approach. :roll_eyes: 

Back to the original question: Looking at the interface, the multi-valued attributes are ordered, thereby from a Java Interface point of view they are non-unique. Another reason to not add a constraint to the database for JPA here. 

@hmlnarik / @vramik - I'd he happy to have a short opinion on "multivalued attributes values are ordered vs. unordered" and "when retrieving a multivalue attribute always return the first value vs. throw an exception if more than one entry exists". One possible short answer is of course "start a GH discussion on this" :smile: - thanks!

**Comment by vramik** [comment]
Thank you @ahus1.

Regarding throwing an Exception when there is more than one attribute: I think it shouldn't happen (unless inserted concurrently), because the logical layer use only single attribute and once we'd need to make it multi-valued this behavior will change. So I think we shouldn't introduce the exception. 

Regarding the ordering: according to https://www.postgresql.org/docs/current/queries-limit.html it should be added `ORDER BY` when using `LIMIT`. What about adding `@OrderBy` annotation:

```
    @OneToMany(mappedBy = "client", cascade = CascadeType.PERSIST, orphanRemoval = true)
    @OrderBy("name")
    private final Set<JpaClientAttributeEntity> attributes = new HashSet<>();
```

And also we could check that when `queryParameters.getLimit()` is not null then also `queryParameters.getOrderBy()` is set, wdyt?

**Comment by ahus1** [comment]
Thanks for replying to this @vramik. I still ways this could fail, so I'll start two discussion on these topics.

For the core topic of this issue there's now a PR available, it would be great if you could review this as a first step to getting it merged.

**Comment by ahus1** [comment]
I started two discussions: https://github.com/keycloak/keycloak/discussions/9636 and https://github.com/keycloak/keycloak/discussions/9638

@vramik - I would be thankful if you could have a look at them when time permits. I haven't moved over your previous comment, I would leave it to you what you want to move over.
