### ISSUE TITLE
IMPERSONATOR_USERNAME not preserved in chain of impersonation

### ISSUE THREAD

**Issue by rissingh1281** [keycloak/keycloak#9627]
### Describe the bug

When impersonating users in chain. For example:

~~~
User I --- Impersonate --> User A  --- Impersonate --> User B 
~~~

  - IMPERSONATOR_USERNAME and IMPERSONATOR_ID "User Session Note" token mapper is enabled
  -  Impersonation is performed using impersonate button of Keycloak admin console
  -  Once User I is impersonated to User A, the user is redirected to account page of User A
  -  User A comes back to Keycloak admin console and since the user has impersonation role, user impersonates to User B.
  -  It redirects to User B account page
  -  The access token captured does not has the entry for User I in impersonator field of token[1].
   

[1]

{
"sub": "user B ID",
"preferred_username": "user B username",
"impersonator": {
"id": "user A ID",
"username": "user A username"
}
} 

**Impersonation should not be possible for impersonated user**

### Version

15.0.2

### Expected behavior

Impersonation should not be possible for impersonated user

### Actual behavior

Currently impersonation of impersonated user is possible. And first impersonated user is not captured in access token

### How to Reproduce?

~~~
User I --- Impersonate --> User A  --- Impersonate --> User B 
~~~

  - IMPERSONATOR_USERNAME and IMPERSONATOR_ID "User Session Note" token mapper is enabled
  -  Impersonation is performed using impersonate button of Keycloak admin console
  -  Once User I is impersonated to User A, the user is redirected to account page of User A
  -  User A comes back to Keycloak admin console and since the user has impersonation role, user impersonates to User B.
  -  It redirects to User B account page
  -  The access token captured does not has the entry for User I in impersonator field of token[1].

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by pedroigor** [comment]
Might have be fixed by https://github.com/keycloak/keycloak/pull/5096.
