### ISSUE TITLE
Hot Rod map storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9680]
### Description

Implementation of map storage in Hot Rod

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17633

### Issues

- #9670
- #9671
- #9672
- #9673
- #9674
- #9675
- #9676
- #9677
- #9678

**Comment by mhajas** [comment]
Should we add the following to this epic: 
- #9240
- #9113

I know these are enhancements but it is a kind of a must-have to make the Hot Rod store usable.

**Comment by hmlnarik** [comment]
Base for Hot Rod storage has been implemented in Keycloak 19.
