### ISSUE TITLE
JPA map storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9681]
### Description

Implementation of JPA map storage.

Needs to support PostgreSQL initially, ideally also CockroachDB.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17632

### Issues

- #9660
- #9661
- #9662
- #9663
- #9664
- #9665
- #9666
- #9667
- #9668
- #9669

**Comment by ahus1** [comment]
For a discussion how to run JPA Map Storage locally to give it a try, see https://github.com/keycloak/keycloak/discussions/9596

**Comment by hmlnarik** [comment]
Base for Hot Rod storage has been implemented in Keycloak 19.
