### ISSUE TITLE
Add `id_token_signed_response_alg` when realm default algorithm is not `RS256`

### ISSUE THREAD

**Issue by grossws** [keycloak/keycloak#9695]
### Describe the bug

Currently Registration API `GET` request return `id_token_signed_response_alg` only when some algorithm is set for client in `Fine Grain OpenID Connect Configuration` or via `POST`/`PUT` on Registration API endpoint.

If realm administrator set default algorithm for realm it isn't represented in registration API response, so client expects `RS256` as defined in [OpenID Connect Core 1.0 #3.1.3.7](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) when validating ID token.

### Version

16.1.0

### Expected behavior

When effective ID token signature algorithm is not `RS256` expose effective value via Registration API in `id_token_signed_response_alg` parameter (e.g. to allow client auto-configuration).

### Actual behavior

`id_token_signed_response_alg` is absent if realm default signature algorithm is set and client use realm-default.

### How to Reproduce?

```bash
# in one terminal:
podman run --name -it --rm -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:16.1.0

# in another terminal
podman exec -it kc /bin/bash -l
export PATH=$PATH:/opt/jboss/keycloak/bin

kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin

kcadm.sh create realms -s realm=demo -s enabled=true -s defaultSignatureAlgorithm=ES256

kcadm.sh create users -r demo -s id=da688519-eefe-497a-967a-03c563e097fa -s username=demoadm -s enabled=true
kcadm.sh set-password -r demo --username demoadm --new-password demoadm
kcadm.sh add-roles -r demo --uusername demoadm --cclientid realm-management --rolename realm-admin

kcreg.sh config credentials --server http://localhost:8080/auth --realm demo --user demoadm --password demoadm
kcreg.sh create -s clientId=test-client -s publicClient=false -s standardFlowEnabled=false -s directAccessGrantsEnabled=true
kcreg.sh get test-client -e oidc
```

It returns something like:
```json
{
  "redirect_uris" : [ ],
  "token_endpoint_auth_method" : "client_secret_basic",
  "grant_types" : [ "password", "refresh_token" ],
  "response_types" : [ ],
  "client_id" : "test-client",
  "scope" : "address phone offline_access microprofile-jwt",
  "subject_type" : "public",
  "request_uris" : [ ],
  "tls_client_certificate_bound_access_tokens" : false,
  "client_secret_expires_at" : 0,
  "registration_client_uri" : "http://localhost:8080/auth/realms/demo/clients-registrations/openid-connect/test-client",
  "registration_access_token" : "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1MTFjYzQwNi0zODIyLTQ2YzMtYjZiZC05NzVkMTJmOGRjZDUifQ.eyJleHAiOjAsImlhdCI6MTY0MjcwMzAyNCwianRpIjoiNjJhMWM3MzMtY2JjZC00OTcyLWE3ZWMtZDg3NTU3NjA2ZGVkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2RlbW8iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvZGVtbyIsInR5cCI6IlJlZ2lzdHJhdGlvbkFjY2Vzc1Rva2VuIiwicmVnaXN0cmF0aW9uX2F1dGgiOiJhdXRoZW50aWNhdGVkIn0.ISeQ4f3l-SqHyW8AMYI3XLiQI1h8N6LvQExpKKDyVDE",
  "backchannel_logout_session_required" : false,
  "require_pushed_authorization_requests" : false
}
```

Login to http://localhost:8080/auth/admin/demo/console as `demoadm` and check that `id_token` use `ES256`.

### Anything else?

[OpenID Connect Core 1.0 #3.1.3.7](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) states:

> The `alg` value SHOULD be the default of `RS256` or the algorithm sent by the Client in the `id_token_signed_response_alg` parameter during Registration.

**Comment by rmartinc** [comment]
@grossws Yep, you are right. But this is not a very important issue so if someone in the community can help here it would be much much appreciated.

**Comment by missedone** [comment]
i have the similar issue, and would like to have the property `id_token_signed_response_alg` of an oidc client
