### ISSUE TITLE
Issue migrating DB if the realm name and realm ID don't match

### ISSUE THREAD

**Issue by sdkn74** [keycloak/keycloak#9701]
### Describe the bug

While trying to upgrade from 12.0.4 to 15.1.1 we received an error which we saw the important line `(realm)=(unigroup) is not present in table "realm"`
We checked the admin portal and saw that we had a realm with that name, then went to check the database and saw the name was `unigroup` but the id was `Unigroup`. We determined that when the realm was initially created it was named with an uppercase "U". When trying to find out what was going on we generated the DB migration scripts to see what they were going to do and we saw that the SQL scripts that were generated were pulling in the realm name and trying to use that as the realm ID. We updated the realm name to match the realm ID through the admin portal but I think the generated scripts would use the realm ID instead of the realm name (updates have never been an issue from 4.0 until now). I think I tracked it down to the `JpaUpdate13_0_0_MigrateDefaultRoles.java` file but I'm not 100% on what needs updating as it looks like it's right but the prepared SQL shows something different. 

### Version

12.0.4

### Expected behavior

Database migration scripts to run without issue

An example of the working SQL statement after updating the realm name to `Unigroup`
`INSERT INTO public.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('b80f2325-eb0c-40f5-81bc-81017972b12b', 'Unigroup', FALSE, '${role_default-roles-unigroup}', 'default-roles-unigroup', 'Unigroup', 'Unigroup');`

### Actual behavior

Database migration scripts fail due with `(realm)=(REALM_NAME) is not present in table "realm"`
[Keycloak_Error_Message.log](https://github.com/keycloak/keycloak/files/7908739/Keycloak_Error_Message.log)

An example of one of the failing SQL statements
`INSERT INTO public.keycloak_role (ID, CLIENT_REALM_CONSTRAINT, CLIENT_ROLE, DESCRIPTION, NAME, REALM_ID, REALM) VALUES ('c9d4e964-cdb6-4fe0-9a8a-737bb4e264d5', 'unigroup', FALSE, '${role_default-roles-unigroup}', 'default-roles-unigroup', 'unigroup', 'unigroup');`

### How to Reproduce?

Have an entry in the realm table with non-matching realm.ID and realm.NAME on version 12.0.4 and try to upgrade to version 15.1.1

**Comment by mwaldstein** [comment]
We had the same issue - performing intermediate upgrades to 13.0.1 then 14.0.0 prior to 15.x works as expected.

**Comment by mwaldstein** [comment]
On further investigation, we've found that we can upgrade from 12.0.4 to 15.0.1 without any issues, then upgrade to 15.1.1

**Comment by ahus1** [comment]
I haven't received a response yet, therefore I close this assuming it is fixed. Please let me know if you want this issue to be re-opened.
