### ISSUE TITLE
Set KC_FEATURES_<feature>=enabled at build, unset and start afterwards does not activate the feature in some cases.

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#9702]
### Describe the bug

Case 1: token_exchange feature
When applying `export KC_FEATURES_TOKEN_EXCHANGE=enabled` as env variable to the build command, console output shows it gets picked up. But unsetting the env variable and running e.g. `./kc.sh start --http-enabled=true --hostname-strict=false --hostname-strict-https=false` afterwards, the console/gui doesn't show it as enabled anymore.

Case 2: docker feature
no message at all in build/run if it's enabled or not, when setting using `KC_FEATURES_DOCKER=enabled`. Also not shown at all in the list in the admin ui.

Case 3: scripts feature
here it works as wanted, irritatingly.

Video of all cases:
https://www.youtube.com/watch?v=o1MKsF00H8M

### Version

latest

### Expected behavior

1) Enabled/disabled features get built in correctly, so running start also shows which feature is enabled and enables it correctly.

### Actual behavior

see description

### How to Reproduce?

see description, or use e.g.:
```
FROM quay.io/keycloak/keycloak-x:latest as builder

#does get picked up at start
ENV KC_METRICS_ENABLED=true
#does not get picked up at start
ENV KC_FEATURES_TOKEN_EXCHANGE=enabled
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak-x:latest
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak
# for demo purposes only, make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=change_me
ENV KC_HOSTNAME=localhost:8443
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```
+ `docker build . -t my_kc` 
+ `docker run --rm -it -p 8443:8443 my_kc`
### Anything else?

When running `kc.sh build --features-token_exchange=enabled` the build doesn't show this feature gets enabled, but running start afterwards shows it gets enabled. Also seems to be somewhat inconsistent.

**Comment by pedroigor** [comment]
@DGuhr Looks like this is related to the change we did to the option format. Can you check it is fixed by https://github.com/keycloak/keycloak/pull/9641 ?
