### ISSUE TITLE
Keycloak Performance Testsuite issues

### ISSUE THREAD

**Issue by waltari2001** [keycloak/keycloak#9724]
### Describe the bug

When running 

cd testsuite/performance
mvn clean install

I get 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (configure-infinispan) on project performance-keycloak-infinispan-server: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /root/keycloak/testsuite/performance/infinispan/infinispan.xml:37: Execute failed: java.io.IOException: Cannot run program "./ispn-cli.sh" (in directory "/root/keycloak/testsuite/performance/infinispan/target/infinispan-server-10.1.8.Final/bin"): error=2, No such file or directory

### Version

16.1.0

**Comment by pedroigor** [comment]
@waltari2001 Could you please consider using https://github.com/keycloak/keycloak-benchmark?

Does it works for you?
