### ISSUE TITLE
Admin Rest API doesn't generate secret upon creating new Client Representation with serviceAccountEnabled.

### ISSUE THREAD

**Issue by Joshhw** [keycloak/keycloak#9728]
### Describe the bug

I've recently updated our Keycloak server from 11.0.2 to 15.0.1 and now our admin rest api endpoints for creating new clients no longer generates a secret by default. We normally use the keycloak admin client in our codebase. These are the two methods we call:

```
      ClientRepresentation cr = keycloakService.newClientRepresentation(clientId, clientType, isServiceAccount)
      Response response = keycloakService.getRealmResource().clients().create(cr)
```
We create a new clientRepresentation with these values:

```
    new ClientRepresentation(
      clientId: clientId,
      serviceAccountsEnabled: true,
      authorizationServicesEnabled: false,
      attributes: attributes
    )
```

In our prior builds the secret would normally be generated for us and present in the UI. I've noticed since that the secret doesn't appear until I either switch the Client Authenticator methods or regenerate the secret. 

### Version

15.0.1

### Expected behavior

upon creating a ClientRepresentation object with the keycloak admin rest client a secret should be generated for the created client automatically.

### Actual behavior

the secret is empty until regenerated or switching between client authenticator types.

### How to Reproduce?

use the methods above.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by rmartinc** [comment]
I'm closing this issue. If you find any problem please re-open it or file a new issue. Regards!
