### ISSUE TITLE
Tree storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9742]
### Description

Tree storage is an abstraction layer on various storage implementations that provides a unified view on the underlying storages that provide persistence or caching. The aim is to hide details of caching / federation / persistence setup from the code reading and writing objects from different areas like users, groups etc.

It has to be able to form a tree from given an implementations of the [map storage SPI](https://github.com/keycloak/keycloak/blob/main/model/map/src/main/java/org/keycloak/models/map/storage/MapStorageSpi.java) and provide wiring to allow for caching, invalidation, reads and writes.

In the following example, the caching layer is realized via Infinispan, storage is joining LDAP and REST interface to SCIM, with additional attributes stored in JPA store. Each of the Infinispan, LDAP, SCIM and JPA federation would have separate implementation of `MapStorage` interface.

![Map storage - stacking](https://user-images.githubusercontent.com/5391360/150319819-1aa0048e-a00c-4d46-b585-ec6fcd249a4c.png)

In essence, this task is about creating boilerplate code that allows wiring various storages to form a storage capable of leveraging various storage technologies (database, LDAP, Infinispan, ...) for storage and caching objects. This task is not about implementing the storages themselves.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-17408

**Comment by alexBigBoss** [comment]
Hi, there is an example to implement map storage spi?

I can not find enough information about how to do federate users using this implementation.

Thanks!

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
