### ISSUE TITLE
Token not active after exchange with Authorization Code grant

### ISSUE THREAD

**Issue by raystorm-place** [keycloak/keycloak#9747]
### Describe the bug

The authorization code grant seems to be broken, because the token is not active after exchange.
The issue is critical and can be reproduced like described in:
https://stackoverflow.com/questions/70464290/keycloak-access-token-is-not-active-when-retrieved-via-token-exchange

### Version

16.1.0

### How to Reproduce?

https://stackoverflow.com/questions/70464290/keycloak-access-token-is-not-active-when-retrieved-via-token-exchange

### Anything else?

I've tested this only in 16.1.0

**Comment by mposolda** [comment]
@raystorm-place Thanks for reporting this. I am adding label "Help wanted" as Keycloak team probably won't have time to look at this in the near future. Anyone is welcome to contribute the PR with fixing this (after it is investigated and confirmed that this is valid issue).

**Comment by Erfankam** [comment]
This problem is still exist. We are using version 22.0.3 and Direct access grants flow (Resource Owner Password Credentials Grant) for our application. After exchanging token, we would like to introspect obtained token in order to check if token is revoked. But we got "active:false". 
Any help or useful hint?

**Comment by Erfankam** [comment]
> This problem is still exist. We are using version 22.0.3 and Direct access grants flow (Resource Owner Password Credentials Grant) for our application. After exchanging token, we would like to introspect obtained token in order to check if token is revoked. But we got "active:false". Any help or useful hint?

@mposolda Could I tackle this issue and work on it? Of course I do not have any idea about its priority and backlog precedence. 
Thanks.

**Comment by jonkoops** [comment]
@Erfankam if you have a good idea of how to approach a fix for this issue feel free to open up a PR. We always welcome community contributions. I'll assign this issue to you.

**Comment by Erfankam** [comment]
I m trying to build the newest version of code base and reproduce bug in development mode.

**Comment by Erfankam** [comment]
> Due to the amount of issues reported by the community we are not able to prioritise resolving this issue at the moment.
> 
> If you are affected by this issue, upvote it by adding a 👍 to the description. We would also welcome a contribution to fix the issue.

I had some try on this issue. I keep working on it.

**Comment by Erfankam** [comment]
@jonkoops I ran some tests by calling web services to reproduce the bug in **internal to internal token**.
After I obtain token and exchange it by token endpoint, there was no problem in validity of new exchanged token.
I continue test application by more test to ensure there is no problem.

**Comment by Erfankam** [comment]
I test _user impersonation by token exchange_ mechanism and found that **there is a problem in validating exchanged impersonated token while revoking it**. I will do some more test to ensure the bug still exist.
By the way, I am using snapshot version under development environment.
