### ISSUE TITLE
view-realm permission required to edit username

### ISSUE THREAD

**Issue by herrmannkathrin** [keycloak/keycloak#9754]
### Describe the bug

Hi there,

I have the requirement in my project to create a role for a keycloak "helper admin" who is only able to manage users and groups in one specific realm subordinate to the master realm. However, if you want a user to be able edit a user's username via the admin console in a realm, he has to have the view-realm permission in the client roles for the realm that he is supposed to manage. If I only give him the permissions manage-users, query-groups, query-users, view-users, he is able to manage users and groups as desired, but the field Username appears as read-only, even though the option "Edit username" is switched on for the given realm.

I do not want to give the user the permission view-realm, however, as he would then be able to see the realm settings and partially also gets the impression, that he will be able to change realm settings (even though he hits an error page when trying to do so).

Thanks in advance for looking into this!

Best Regards
Kathrin

### Version

16.1.0

### Expected behavior

The permission manage-users enables an admin user to edit a user's user name via the admin console if "Edit username" is switched on for the selected realm.

### Actual behavior

A user with the client role manage-users is able to  edit a user's user name via the admin console if "Edit username" is switched on for the selected realm.

### How to Reproduce?

1) Switch "Edit username" on in a realm subordinate (let's call it "Realm A") to the master realm.
2) Create new user "User A" in master realm.
3) Go to role mappings for that user.
4) Select "Realm A" in the dropdown "Client Roles".
5) Assign the roles manage-users, query-groups, query-users, view-users to "User A".
6) Login as "User A" and try to edit the username for any user in "Realm A".
7) Field username appears as readonly and cannot be edited by "User A".

**Comment by minoltan** [comment]
I am also having this issue till now

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by ssilvert** [comment]
@minoltan @herrmannkathrin I believe this is fixed now.  You can give it a try in the nightly build:
https://github.com/keycloak/keycloak/releases/tag/nightly

I'm going to close this but if you find that the nightly build still has this issue we can reopen.
