### ISSUE TITLE
view-realm permission required to have prefilled "Default Admin-Initiated Action Lifespan" in "Expires In" field under "Reset Actions"

### ISSUE THREAD

**Issue by herrmannkathrin** [keycloak/keycloak#9755]
### Describe the bug

Hi there,

I have the requirement in my project to create a role for a keycloak "helper admin" who is only able to manage users and groups in one specific realm subordinate to the master realm. 

However, if you want a user to be able to send Reset Actions mails to users with the "Default Admin-Initiated Action Lifespan" in "Expires In" field prefilled under "Reset Actions", he has to have the view-realm permission in the client roles for the realm that he is supposed to manage. If I only give him the permissions manage-users, query-groups, query-users, view-users, the field "Expires In" is empty and has to be filled in manually (even though a Default Admin-Initiated Action Lifespan is configured for the realm).

I do not want to give the user the permission view-realm, however, as he would then be able to see the realm settings and partially also gets the impression, that he will be able to change realm settings (even though he hits an error page when trying to do so).

Thanks in advance for looking into this!

Best Regards
Kathrin

### Version

16.1.0

### Expected behavior

Field "Expires In" under "Reset Actions" is prefilled with "Default Admin-Initiated Action Lifespan" configured for a realm if the user logged into the admin console has the permission manage-users.

### Actual behavior

Field "Expires In" under "Reset Actions" is empty even if configured for a realm if the user logged into the admin console has the permission manage-users. If the user has the permission view-realm, the field "Expires In" is filled with the "Default Admin-Initiated Action Lifespan" configured for the realm.

### How to Reproduce?

1) Create user "User A" for a realm under the master realm who has the roles manage-users, query-groups, query-users, view-users assigned under the client roles for that realm.
2) Log in as "User A".
3) Select a user from the realm and go to "Credentials" tab.
4) Field "Expires in" is empty even though a "Default Admin-Initiated Action Lifespan" is configured for the realm.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by jens-hammel** [comment]
In 22.0.4 the "Default Admin-Initiated Action Lifespan" in realm-Settings -> Tokens is completely ignored in the Credential Reset Widget. I can see only a request to required-actions but that only contains an array of actions and there is no default time information.
I guess that in that response the value should be included.
