### ISSUE TITLE
lifespan property in PathCacheConfig is missing @JsonProperty annotation

### ISSUE THREAD

**Issue by mhajas** [keycloak/keycloak#9756]
### Describe the bug

Reported in: https://issues.redhat.com/browse/KEYCLOAK-19520

[PolicyEnforcerConfig.PathCacheConfig](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/adapters/config/PolicyEnforcerConfig.java#L332) is missing `@JsonProperty` annotation that results in the following error when it is set for example, in Spring security yaml config file:

```
Property: keycloak.policy-enforcer-config.path-cache.lifespan
 Value: 10000
 Origin: class path resource [application.yml] - 71:17
 Reason: The elements [keycloak.policy-enforcer-config.path-cache.lifespan] were left unbound.
```

### Version

16.1.0

### How to Reproduce?

Use following yaml configuration:
```
policy-enforcer-config:
 enforcement-mode: ENFORCING
 path-cache:
   lifespan: 30000
``

### Anything else?

_No response_

**Comment by StitzL** [comment]
First-timer here - I'd really have loved to submit a test for this PR, but to be honest, I am a bit overwhelmed by the project's structure. If you should think it necessary, please let me know where such a test would fit, I'll rework the PR.

**Comment by hansvanbeneden** [comment]
I had the same error message with Keycloak 21.
Turns out `path-cache` should be `path-cache-config` if you use yml config.
