### ISSUE TITLE
Problem run/debug Keycloak from Intellij

### ISSUE THREAD

**Issue by cgeorgilakis** [keycloak/keycloak#9760]
### Describe the bug

I am in current main ( commit f80d336276fb73603415aedda56b6da4580deb00).

When I run/debug Keycloak from Intellij, login page can not be opened.
The following javascript error is thrown ( showing also in the attached screenshot):
jquery.min.js:2 jQuery.Deferred exception: Keycloak is not defined ReferenceError: Keycloak is not defined
    at HTMLDocument.<anonymous> (http://localhost:8081/auth/resources/30t6k/admin/keycloak/js/app.js:14:24)
    at e (http://localhost:8081/auth/resources/30t6k/common/keycloak/node_modules/jquery/dist/jquery.min.js:2:30005)
    at t (http://localhost:8081/auth/resources/30t6k/common/keycloak/node_modules/jquery/dist/jquery.min.js:2:30307) undefined

 When Keycloak starts with command ' mvn -f testsuite/utils/pom.xml exec:java -Pkeycloak-server ', everything is ok.

### Version

main branch

### How to Reproduce?

Run KeycloakServer in main branch from Intellij.

**Comment by cgeorgilakis** [comment]
![Keycloak_ui_problem](https://user-images.githubusercontent.com/55974447/150808927-68ed7745-6018-44c3-9583-543ab34a8e7c.PNG)

**Comment by ahus1** [comment]
I'm also running Keycloak from IntelliJ, and it works for me (on the main branch, currently af9d840ec1ef424ce333fc0b67968322a02a7c2d). 

Did you run `mvn clean install -DskipTests=true` first to ensure everything is build correctly first in a situation like this. 

Do you start the class `org.keycloak.testsuite.KeycloakServer` from your IDE? Did you pass environment variables?

For my IntelliJ setup, I needed to enable annotation processing to avoid running "clean install" often. I also run the Maven goal `process-resources -pl common`  before running key KeycloakServer class, as I haven't figured out how to do the maven resource filtering directly in IntelliJ. 

Please let me know if this helps or if it is still a problem.

**Comment by cgeorgilakis** [comment]
@ahus1 Thanks for your info. Keycloak work well from IntelliJ after doing what you describe.
I haven't enable annotation processing  and I have not execute Maven goal process-resources -pl common.

**Comment by skinkie** [comment]
Might help others:
![image](https://github.com/keycloak/keycloak/assets/502394/5ec32f77-ea1e-4512-ac53-7129bc50672d)

**Comment by sachithraswg** [comment]
Really appreciate if someone can explain how to configure IDELauncher with following properties. 

--db=mysql
--db-password=<Password>
--db-url=jdbc:mysql://server:3306/keycloak
--db-username=<username>

I parse them as program arguments in Run/Debug configurations window. But it doesn't work as expected.

**Comment by ahus1** [comment]
@sachithraswg 

You would put the full CLI arguments in CLI arguments fields. Make sure to start with `start-dev` or even `--verbose start-dev` before adding the CLI options as you would on the regular Keycloak CLI. 

![image](https://github.com/user-attachments/assets/d7eb567f-2af1-4723-80a8-5c061456eb5a)
