### ISSUE TITLE
bearer-only clients changes will delete all linked authorization policies , permissions etc ..

### ISSUE THREAD

**Issue by oussamamzoughi** [keycloak/keycloak#9765]
### Describe the bug

This is my first reported issue on Github so go easy on me please ..

I tried to set a description field for a bearer only client (realm-management). 

if you click on save the authorization tab is gone and all the policies and permissions inside are deleted. 

**Note:** I know that changing clients to confidential will solve this but i dont want to change realm-management to confidential, i just want to label it (Setting a Description Field).  

This is realm-management permissions inside authorization tab. (1)

![1](https://user-images.githubusercontent.com/96692589/150938224-16dd1e18-5b51-4b38-9c07-7a2ac4687fc6.PNG)

This is the Description Field that needs to be setup. (2)

![2](https://user-images.githubusercontent.com/96692589/150938241-c86bc9af-09de-49f3-8118-eb808d5bcb1b.PNG)

This is the Authorization tab is gone with all the data inside of it like (permissions & policies etc ..) after saving. (3)

![3](https://user-images.githubusercontent.com/96692589/150938315-05ce6987-cf0c-4d4a-8734-0ac8423574ef.PNG)

### Version

15.0.1

### Expected behavior

Updating realm-management doesnt end up deleting all the authorizations data.

### Actual behavior

Updating realm-management or any bearer-only client results in deleting all the authorization data.

### How to Reproduce?

1- Enable permissions in groups for e.g. (this will create some permissions inside the realm-management authorization tab)

2- Change the description Field of the realm-management client

3- Save 

4- the authorization tab is gone & groups have their permissions disabled

**Comment by stianst** [comment]
This is expected behaviour as disabling authorization services for a client should also clean up any resources around it.

**Comment by oussamamzoughi** [comment]
@stianst i am not disabling the authorization, i am just writing something in the description field and saving .

**Comment by oussamamzoughi** [comment]
> This is expected behaviour as disabling authorization services for a client should also clean up any resources around it.

writing something in the description field shouldn't end up deleting all the authorization data .

**Comment by stianst** [comment]
Sorry, I miss-read it and have re-opened the issue as what you are describing certainly shouldn't happen

**Comment by oussamamzoughi** [comment]
Is it a valid solution until a fix, to change the access type of the realm-management client to "confidential" and set "authorization enabled" to true?

**Comment by arne-heil** [comment]
@stianst 
We are experiencing the same issue on KC18, is there a general timeline for fixing this bug or is there a workaround without changing the access type?

**Comment by mposolda** [comment]
Set to Backlog for now as doesn't look critical for Keycloak 22. We can possibly triage this later...

**Comment by pedroigor** [comment]
The new admin console works differently and changing the `realm-management` client is not possible anymore.

Closing as out-dated.
