### ISSUE TITLE
Use prod profile in Quarkus dist

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9782]
The operator currently deploys Keycloak using dev profile. We should use prod profile by default and make sure auto-build is disabled.

Prerequisite:
* #9605

**Comment by andreaTP** [comment]
I was planning to integrate this with the "seamless augmentation" issue, but good to track it separately.

**Comment by vmuzikar** [comment]
* Enable auto-builds with prod profile by default, unless a custom KC image is provided by the user.
* Add a `dev-profile` field under `unsupported` that'd be set to `false` by default.
