### ISSUE TITLE
Keycloak Should be FIPS Compliant

### ISSUE THREAD

**Issue by WKupper** [keycloak/keycloak#9783]
### Description

This is a recreation of https://issues.redhat.com/browse/KEYCLOAK-14633

Keycloak should be configured as FIPS 140-2 compliant.
Need to enable such configuration (by code changes or any other means), and then add the required configuration steps to documentation. 
 
Keycloak is using BouncyCastle library, which has a fips version (bcfips).
How can Keycloak can be configured to use it as a provider?
Probably there are other steps to be taken for having KC become FIPS compliant. For example, configure WildFly and maybe the JVM itself.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-14633

### Motivation

Keycloak is currently unusable on government based systems of "Moderate" or higher security level (both civilian and DoD).

SHA1 is not a secure algorithm

**Comment by stianst** [comment]
I'm closing this in favour of #9967
