### ISSUE TITLE
Proxy mappings for outgoing http requests must be a STRING

### ISSUE THREAD

**Issue by masseybradley** [keycloak/keycloak#9797]
### Describe the bug

The https://www.keycloak.org/docs/latest/server_installation/#_proxymappings for `1.16.x` apparently must be passed as a string, the example configuration command is invalid, results in the error:
```
[standalone@localhost:9990 /] /subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value=[".*\\.(google|googleapis)\\.com;http://www-proxy.acme.com:8080",".*\\.acme\\.com;NO_PROXY",".*;http://fallback:8080"])
{
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0097: Wrong type for 'properties'. Expected [STRING] but was LIST",
    "rolled-back" => true
}
```
... not certain if it's possible to set multiple configurations (have not tested).

### Version

1.16.0

### Expected behavior

Functional as per the documentation.

### Actual behavior

Documentation errata / possible lack of functionality.

### How to Reproduce?

Attempt to configure the proxy-mappings as per the documented example.

**Comment by piotrekfilip** [comment]
Based on [this thread](https://groups.google.com/g/keycloak-dev/c/F9y20cVEtMY), the following format should work with Keycloak 16: 
```
/subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value="[\".*\\.(google|googleapis)\\.com;http://www-proxy.acme.com:8080\",\".*\\.acme\\.com;NO_PROXY\",\".*;http://fallback:8080\"]")
```

**Comment by stianst** [comment]
The WildFly based distribution of Keycloak has been deprecated since Keycloak 17 (February 2022), and will no longer be available in Keycloak 20, which is due to be released soon.

For this reason we're closing this issue as it is related to the WildFly based distribution. Please migrate to the new Quarkus distribution as soon as possible.
