### ISSUE TITLE
Improve user search query

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9803]
### Description

See https://issues.redhat.com/browse/KEYCLOAK-18727

### Discussion

https://groups.google.com/g/keycloak-dev/c/jn5Yy9Y4Lw4/m/BEptzC0bAAAJ

**Comment by rombow** [comment]
This change is not documented in "Keycloak Admin REST API"... (e.g. https://www.keycloak.org/docs-api/18.0/rest-api/index.html#_users_resource)
