### ISSUE TITLE
FIPS 140-2 enforcement

### ISSUE THREAD

**Issue by jeffschulman** [keycloak/keycloak#9806]
### Description

DoD AAA Security Requirements Guide requires FIPS 140-2 mode enforcement.

Transition to FIPS 140-3 is underway; existing 140-2 certified modules are still authorized.

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-14633

### Motivation

All USG systems must use FIPS-compliant cryptographic modules per policy: https://csrc.nist.gov/publications/detail/fips/140/2/final.

All DOD Authentication, Authorization, and Accounting Services must comply with DISA AAA STIG: 
https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_AAA_Services_V1R2_SRG.zip

### Details

Group Title: SRG-APP-000171-AAA-000510

Rule Title: AAA Services must be configured to encrypt locally stored credentials using a FIPS-validated cryptographic module.

Discussion: Passwords need to be protected at all times, and encryption is the standard method for protecting passwords. If passwords are not encrypted, they can be plainly read (i.e., clear text) and easily compromised.

AAA Services must enforce cryptographic representations of passwords when storing passwords in databases, configuration files, and log files. Passwords must be protected at all times; using a strong one-way hashing encryption algorithm with a salt is the standard method for providing a means to validate a password without having to store the actual password.

Performance and time required to access are factors that must be considered, and the one-way hash is the most feasible means of securing the password and providing an acceptable measure of password security. If passwords are stored in clear text, they can be plainly read and easily compromised.

Check Text: Where passwords are used, verify AAA Services are configured to encrypt locally stored credentials using a FIPS-validated cryptographic module. AAA Services may leverage the capability of an operating system or purpose-built module for this purpose. 

Confirm that databases, configuration files, and log files have encrypted representations for all passwords, and that no password strings are readable/discernable. Potential locations include the local file system where configurations and events are stored, or in a related database table.

Review AAA Services configuration for use of the MD5 algorithm to create password hashes.

If AAA Services are not configured to encrypt locally stored credentials using a FIPS-validated cryptographic module, this is a finding.

If AAA Services are configured to use MD5 to create password hashes, this is a finding.

Note: FIPS-validated cryptographic modules are listed on the NIST Cryptographic Module Validation Program's (CMVP) validation list.

Fix Text: Configure AAA Services to encrypt locally stored credentials using a FIPS-validated cryptographic module.

Configure all associated databases, configuration files, and audit files to use only encrypted representations for all passwords and so that no password strings are readable/discernable.

---------

DoD AAA SRG

Group Title: SRG-APP-000172-AAA-000520

Rule Title: AAA Services must be configured to encrypt transmitted credentials using a FIPS-validated cryptographic module.

Discussion: Passwords need to be protected at all times and encryption is the standard method for protecting passwords. If passwords are not encrypted, they can be plainly read (i.e., clear text) and easily compromised.

AAA Services can accomplish this by making direct function calls to encryption modules or by leveraging operating system encryption capabilities.

Check Text: Where passwords are used, verify AAA Services are configured to encrypt transmitted credentials using a FIPS-validated cryptographic module. AAA Services may leverage the capability of an operating system or purpose-built module for this purpose.

If AAA Services are not configured to encrypt transmitted credentials using a FIPS-validated cryptographic module, this is a finding.

Note: FIPS-validated cryptographic modules are listed on the NIST Cryptographic Module Validation Program's (CMVP) validation list.

Fix Text: Configure AAA Services to encrypt transmitted credentials using a FIPS-validated cryptographic module.

**Comment by WKupper** [comment]
Posting in support of this. Posted https://github.com/keycloak/keycloak/issues/9783 one day before this ticket, so we must be running along the same track right now. 

If Keycloak is ever going to be utilized by government it needs FIPS compliance. And really, SHA1 is garbage anyway so why stick with it?

**Comment by stianst** [comment]
I'm closing this in favour of #9967
