### ISSUE TITLE
Building Keycloak 15.1.1 source code on Java 8

### ISSUE THREAD

**Issue by shubhamarora97** [keycloak/keycloak#9822]
### Describe the bug

Hi,

I had cloned the Keycloak source code 15.1.1 from keycloak github page using the below mentioned steps: 

https://github.com/keycloak/keycloak/blob/main/docs/building.md

I was trying to build the keycloak project using mvn clean install.
Firstly, when I started building the full keycloak project, I was getting the error

""[ERROR] bad class file: C:\bin\java\apache-maven\repository\org\keycloak\keycloak-quarkus-server\15.1.1\keycloak-quarkus-server-15.1.1.jar(org/keycloak/quarkus/runtime/configuration/mappers/ConfigCategory.class)"
"class file has wrong version 55.0, should be 52.0"

After this, I moved to quarkus project and changed the pom.xml  file to point it to Java8.
I have changed it in pom files for various Quarkus project to build in Java 8.

On building the source code, I am getting compilation errors now.

[INFO] Keycloak Quarkus Parent ............................ SUCCESS [ 3.786 s]
[INFO] Keycloak Quarkus Server Extension .................. FAILURE [ 8.798 s]
[INFO] Keycloak Quarkus Server Deployment ................. SKIPPED
[INFO] Keycloak Quarkus Server App ........................ SKIPPED
[INFO] Keycloak Quarkus Test Parent ....................... SKIPPED
[INFO] Keycloak Quarkus Server Integration tests .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.205 s
[INFO] Finished at: 2022-01-27T14:19:10+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project keycloak-quarkus-server: Compilation failure: Compilation failure:
[ERROR] /C:/Keycloak/keycloak/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java:[78,28] <identifier> expected
[ERROR] /C:/Keycloak/keycloak/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java:[78,29] ')' expected
[ERROR] /C:/Keycloak/keycloak/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/PersistedConfigSource.java:[78,31] '{' expected

In documentation for 15.1.1, it is mentioned that Java 8 is supported. https://www.keycloak.org/docs/15.1/server_installation/index.html

I was checking the quarkus link and it is mentioned that it is supported from Java 11 onwards but in the official keycloak docs it is mentioned as  it is supported for JAVA 8 JRE or JAVA 11 JRE. 
https://github.com/keycloak/keycloak/tree/15.1.1/quarkus 

Could you please suggest how we can proceed here?

### Version

15.1.1

### Expected behavior

Keycloak 15.1.1 source code should be able to build succesfully with Java 8

### Actual behavior

Compilation errors in quarkus project is seen during building keycloak 15.1.1 source code with Java 8

### How to Reproduce?

Clone the Keycloak source code 15.1.1 from keycloak github page using the below mentioned steps: 

https://github.com/keycloak/keycloak/blob/main/docs/building.md

I was trying to build the keycloak project using mvn clean install.
Firstly, when I started building the full keycloak project, I was getting the error

""[ERROR] bad class file: C:\bin\java\apache-maven\repository\org\keycloak\keycloak-quarkus-server\15.1.1\keycloak-quarkus-server-15.1.1.jar(org/keycloak/quarkus/runtime/configuration/mappers/ConfigCategory.class)"
"class file has wrong version 55.0, should be 52.0"

After this, I moved to quarkus project and changed the pom.xml  file to point it to Java8.
I have changed it in  pom files for various Quarkus project to build in Java 8

On building the source code, I am getting compilation errors as mentioned above

**Comment by darius-m** [comment]
I am not sure how building Keycloak works, but I think they mentioned that they only support Java 11 and onwards for the Quarkus project, which is used for Keycloak.X, and not the original Keycloak (which is based on WildFly). There may be a confusion caused by the two (diverging) implementations.

The Keycloak.X project is currently in currently in preview, as mentioned [here](https://www.keycloak.org/downloads).

**Comment by stianst** [comment]
We require Java 11+ to build Keycloak
