### ISSUE TITLE
DB Connection Leak when loading user credentials

### ISSUE THREAD

**Issue by Spindl** [keycloak/keycloak#9823]
### Describe the bug

When querying the user-sessions for all clients of a realm while the roles of a user in the same realm are changed, it seems that a DB connection leak occurs.
This leads to the statement for the user of a user session failing because either the result set or the statement for the user credentials is already closed.
As a result, the user cannot login any more (presumably because the cache for the credentials is affected as well). 
After some time (~ 60s, presumably when the cache expires) the login works again as before.

### Version

15.0.2

### Expected behavior

Loading the user-sessions of a client while changing the roles of a user does work without any problems and does not break the login for said user.

### Actual behavior

When the problem occurs, the user cannot login any more for about a minute even though the correct credentials are provided.

### How to Reproduce?

Here is what exactly we are doing and how the problem can be provoked:

### Setup:
We are using the `keycloak-admin-client` (also Version 15.0.2) to communicate with the keycloak server.
The keycloak server is running as a docker container, using the H2 database without pre-existing data or any customizations done to it.
In the two cases an admin user has been created (either `nts` or `keycloakUser`), when the server is started.
Furthermore, a realm called `GeminiIT` and a user called `gemini` has been created via the admin client.

--- 

### How to reproduce:
In our case, there are two different, unrelated processes which together seem to cause the problem.

#### Loading the user sessions
We periodically query the user-sessions for all clients in a given realm by calling the respective endpoint via the keycloak-admin-client. This calls triggers the error, but only when the other process is executed.
`keycloak.realm("GeminiIT").clients().get("<clientId>").getUserSessions(0, Integer.MAX_VALUE))`

#### Altering the roles of a user
During testing, we add a new role called `testRole` to the `gemini` user, and later remove it again, also via the admin client:

1) We load the realm `keycloakClient.realm("GeminiIT")`
2) We query the user `realm.users().search("gemini")`
3) We try to find the new role `realmResource.roles().get("testRole").toRepresentation()`
4) Since it does not exist we create it `realmResource.roles().create(testRole)`
5) We reload it to get the full information `realmResource.roles().get("testRole").toRepresentation()`
6) We check which roles the user already has `userResource.roles().realmLevel().listAll()`
7) And assign the new role `userResource.roles().realmLevel().add(testRole)`

Then the test is executed with a new token for the altered user. Finally, during cleanup:

8) We load the realm again `keycloakClient.realm("GeminiIT")`
9) We query the user again `realm.users().search("gemini")`
10) We remove the role assignment from the user `userResource.roles().realmLevel().remove(testRole);`
11) We delete the role again `realmResource.roles().deleteRole("testRole")`

---

It seems that when the role is unassigned or deleted, and the user-sessions are queried at the same time, the error occurs. Usually the sessions are only queried once a minute, but for increasing the likelihood of the error we increased the frequency to once every 3s.
Then, the error could be reproduced on every try.

### Anything else?

We first encountered the issue during normal, automated test runs of our application without any special setup. It did not occur on every run, but maybe once or twice every 10 runs or something like that. Here are two full logs from the keycloak server when the problem occured:
* [keycloak_IT_error_1.log](https://github.com/keycloak/keycloak/files/7949594/keycloak_IT_error_1.log)
* [keycloak_IT_error_2.log](https://github.com/keycloak/keycloak/files/7949593/keycloak_IT_error_2.log)

The logs also show that the login for the affected user fails for about 60s afterwards, but then starts to work again.

When we investigated more closely we set up the environment locally, increased the frequency of the user-session loading and were able to consistently provoke the error. Here is a log from such a run:

* [keycloak_local_reproducer.log](https://github.com/keycloak/keycloak/files/7949608/keycloak_local_reproducer.log)

The logs contains two cases of the error, because we missed to provoke the failing login in time during the first run.

If you need any additional information I am glad to help 😅

**Comment by Spindl** [comment]
Ad reproducers.

I just tried to reproduce the problem on a redhat-sso 7.5 server and I fear I was successful :|
I used the standalone server without any alterations: `rh-sso-7.5.0-server-dist`

Here is the log (without DEBUG logging though 😅):
* [redhat_sso.log](https://github.com/keycloak/keycloak/files/7949967/redhat_sso.log)

**Comment by Spindl** [comment]
I managed to whip up a reproducer, and when testing it I found out that the bug seemingly already has been fixed with version 15.1.0 (though I'm not sure with which change exactly).

If you want to try it yourself you can find the reproducer here: https://github.com/Spindl/keycloak-9823-reproducer

I could not reproduce the bug in 16.1.1 and 17.0.1 either, so I'm going to close it with this comment.

**Comment by aamiryaqub-10p** [comment]
Is this issue resolved @stianst and if in version? In our application we're facing similar type issue

**Comment by Spindl** [comment]
As far as I could find out with my reproducer it is occurs up to keycloak version `15.0.2`, so it is fixed with keycloak `15.1.0`. 

I was also unable to reproduce the behavior in `16.1.1` and `17.0.1` either, even though I could provoke it consistently in version `15.0.2`.

**Comment by aamiryaqub-10p** [comment]
Thanks @Spindl for your response. Can you also suggest when upgrading to version 16 you ran to any issues also have you upgraded keycloak adapter and admin client version? And also if you let me know how long it take for yu to upgrade to version 16.

**Comment by solaris-ventus** [comment]
> I managed to whip up a reproducer, and when testing it I found out that the bug seemingly already has been fixed with version 15.1.0 (though I'm not sure with which change exactly).
> 
> If you want to try it yourself you can find the reproducer here: https://github.com/Spindl/keycloak-9823-reproducer
> 
> I could not reproduce the bug in 16.1.1 and 17.0.1 either, so I'm going to close it with this comment.

Thanks a lot! You can’t imagine how you saved my time and nerves.
