### ISSUE TITLE
Initial admin user bootstrapping via the operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9843]
* The operator will create an initial admin user.
* The `KC_ADMIN` and `KC_ADMIN_PASSWORD` env vars will be used for that.
* The credentials will be stored in a Secret.
   * If the Secret doesn't exist, the operator creates it and generates a random password.
   * If the Secret already exists (was created by the user), the operator will use the credentials from it.
* The Secret name needs to explicitly show that it is only initial bootstrap admin user, e.g. `InitilAdminCreds`.
* Any changes to the Secret won't be reflected in KC after first boot. The Secret can be deleted by user if needed.

**Comment by andreaTP** [comment]
`KC_ADMIN` and `KC_ADMIN_PASSWORD`

**Comment by vmuzikar** [comment]
One thing to watch for is what happens when the Secret is deleted.

**Comment by vmuzikar** [comment]
Related discussion: https://github.com/keycloak/keycloak/discussions/8549
