### ISSUE TITLE
Invalid signature on token received through docker-v2 protocol 

### ISSUE THREAD

**Issue by bhushanthakur93** [keycloak/keycloak#9845]
### Describe the bug

The token received after authenticating through docker-v2 protocol within RH-SSO 7.5.0 has invalid signature per jwt.io

### Version

Keycloak 15.0.1 / RH-SSO 7.5.0

### Expected behavior

There should not be invalid signature error. 

### Actual behavior

The token received has invalid signature.

### How to Reproduce?

- Run RH-SSO with docker feature flag enabled.

    `standalone.sh -Dkeycloak.profile.feature.docker=enabled `

- Create a client for e.g `docker-registry` in master realm that supports `docker-v2` protocol.

- Add a user within master realm and assign username and password.

- Query docker protocol through and obtain access token.

    `curl -u ${username}:${password} 'http://localhost:8080/auth/realms/master/protocol/docker-v2/auth?service=${client_id} `

Here is a test token obtained after authentication. Pasting this token into jwt.io invalid signature. I'm not sure if the format is invalid given the actual signature verification requires public key.

`eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJISEtUOkNJUUk6NTdIUTpWRkFJOjRUWDI6UURYTjpUQ1Y3OlVRS046VFBBTTpOQ0xVOlhFVE06Q0IyWCJ9.eyJleHAiOjE2NDMxMzczMTcsIm5iZiI6MTY0MzEzNzI1NywiaWF0IjoxNjQzMTM3MjU3LCJqdGkiOiIzYTAwYTRhZS1jNzc2LTQ4NzYtYmI0OC1kYjI0MWE0YzMwN2UiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoiZG9ja2VyLXJlZ2lzdHJ5Iiwic3ViIjoidGVzdC11c2VyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZG9ja2VyLXJlZ2lzdHJ5IiwiYWNjZXNzIjpbXX0.NyJhwRQqaMzP8fOFId-GjFvcR5xy6-QUF54HgLsPM9471ttUjHJFJFcBk00JUk8k_-vO6kn7dHHiO9997ZU11eyHvSZbR0ZJkxo8ZnInWv_9jau2utbb0WnukwflGb5dG91XymKZGGBRlRAHIlBdo8HTmgidR8sVqKeELe53qCjkTcoaf7Gz4oCoAUyudInQ2bfHzHCmDnxKhYe2OlMN15x655ofiB7K_Cg5OqsunjOuY64G3AYzbk0h66Cp75d__Z5hSluxh9XY7X5GBF3OpN5miAJWrZihZVlLKkzQcuikEGMEJA5fkZ43wDqFIqjDvoV9senrgbKmobXMcVumMQ`

**Comment by bhushanthakur93** [comment]
I did not realize this is in fact due to multiple signing keys available within the realm and client not knowing which key to verify against due to kid transformation. I've opened a discussion for this https://github.com/keycloak/keycloak/discussions/9902

**Comment by alechenninger** [comment]
It looks like jwt.io tries to make a call to the .well-known endpoint, presumably to look up the jwks endpoint to do the verification.  You would have to copy the pub key into the field for that token case since localhost was used.

So I think the description here is misleading. The issue is really just that the kid on the docker access JWT and certs endpoint don't match, and they should match as the key IDs (kids) should be the same value (the same can be seen in the example JWK on the docker reference).

I'd suggest Keycloak offers up a docker-specific certs endpoint, i.e. in addition to `../protocol/openid-connect/certs` there is also `../protocol/docker-v2/certs` which uses kids in the compatible format.

**Comment by alechenninger** [comment]
@mposolda ^ what do you think?

**Comment by mposolda** [comment]
@alechenninger Yes,it seems that the "kid" in the JWT is different than any KID returned from the `../protocol/openid-connect/certs` endpoint. And this is causing issues. So looks the possibility to fix this is to:
1) Make sure that docker protocol returns the JWT with proper `kid` (I am not 100% sure why it needs to return `kid`, which is different than any KID of the Keycloak keys)
2) Make sure that docker protocol endpoint has it's own `certs` endpoint with compatible kids as you suggested

TBH the possibility (1) might be better as having different KID for OIDC and docker protocol is a bit strange and for example admin console shows currently KID of the key in the OIDC format (EG. when you look at the tab `Keys` of some realm in the admin console). So docker-based KID won't be shown anywhere. 

However I don't know if (1) is possible and/or if there is any restriction for docker protocol that it needs to use KIDs in different format than OIDC? Then we would need to use (2) as you suggested

**Comment by alechenninger** [comment]
@mposolda I don't think 1 is an option, the docker protocol requires the kid be in that specific format. So I think we need to go with 2.

**Comment by stianst** [comment]
Does Docker even call the JWKs endpoint? Or, does it assume you manually configure the certs?

**Comment by alechenninger** [comment]
As far as actually integrating a registry from the OSS docker registry, it looks like you configure a cert bundle separately: https://docs.docker.com/registry/configuration/#token (no mention of kids or JWKS as far as I can see)

**Comment by stianst** [comment]
That was what I thought as well. We do actually have some integration tests for this stuff:

https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/docker/DockerClientTest.java

It's basically just configuring the cert here:

https://github.com/keycloak/keycloak/blob/5494848f3f65143efc3bbf6eae430866b3444347/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/docker/DockerClientTest.java#L111

**Comment by stianst** [comment]
I don't think there's a valid bug here, and it seems the Docker registry protocol is actually working as expected.

**Comment by stianst** [comment]
If Docker registry doesn't support a JWKS endpoint then what purpose does a JWKS compatible endpoint serve?

**Comment by alechenninger** [comment]
There are other registry implementations. To be fair I'm not sure if it's just RH's custom proxy which uses a JWKS or if there are other OSS implementations that do (e.g. quay). On the other hand, it seems like it would be a good feature to use, and the standard does give an JWK as an example FWIW.

We would have to decide if we want a custom realm resource for this if it's not supported upstream. Giving folks cert bundles is just going to be more work.

**Comment by stianst** [comment]
Honestly, I would rather see the whole Docker protocol go away, as it is not a standard way to interact with an IdP. Docker/Quay whatever should align with the proper specs, and not some botched together thing by Docker folks.

**Comment by mposolda** [comment]
@alechenninger @bhushanthakur93 I am triaging this with label "Help wanted" as I don't consider it as a priority. However if you guys are still interested in this, we can restore the discussion and hopefully you can contribute fixing this. WDYT?
