### ISSUE TITLE
Users entries can be partially created in OpenLDAP when a validation error occurs

### ISSUE THREAD

**Issue by jledoux-sonergia** [keycloak/keycloak#9860]
### Describe the bug

When using Keycloak with OpenLDAP as user federation in writable edit mode, and email as uid, if you set up a constraint on a required LDAP custom attribute and map it wityh Keycloak without a default value set, then if you try to create a user through API REST "create user" endpoint with an expected value for this field, KC response is:

Header: 400 bad request
Body: {"errorMessage": "Could not create user"}

KC log message:

```sh
WARN  [org.keycloak.services.resources.admin.UsersResource] (default task-1) Could not create user: org.keycloak.models.ModelException: Error creating subcontext [uid=john.doe@example.com,ou=users,dc=example,dc=com]
```

Which is not the expected behavior. So I did a lot of testing, and came with another approach:

1. add a default value (such as "inital-empty-value") to the attribute's regex constraint 
2. set this value as default in user federation mapping

This works fine in a success scenario, except that it does not fit my use case, because settting a default value in the mapper will erase any previous value.

But it gets more ugly when you try to create a user through an error scenario, for instance by providing an unexpected value for this custom attribute. KC REST API response is still:

Header: 400 bad request
Body: {"errorMessage": "Could not create user"}

KC log message is still:

```sh
WARN  [org.keycloak.services.resources.admin.UsersResource] (default task-1) Could not create user: org.keycloak.models.ModelException: Error creating subcontext [uid=john.doe@example.com,ou=users,dc=example,dc=com]
```

Except that user is in fact partially created in OpenLDAP, mandatory attributes are filled with a space (I guess to avoid mandatory constraint exception), and only uid and password have correct values. So, even if you fix your mistake issue on client side, users who encountered this error will not be able to register anymore, and will get an error message "email already in use", until you clean up manually all these wrong LDAP entries.

### Version

16.1.0

### Expected behavior

KC must not initialize OpenLDAP entries required attributes with a space, this workaround makes it impossible to configure attributes constraints on LDAP mandatory attributes in order to provide decent data integrity.
(Well I guess it's not that simple, since KC developpers probably choose to implement this workaround for a good reason)

### Actual behavior

In the described scenarios, either you can't use constraint at all on OpenLDAP attributes which will break user creation workflow, or you might get partially created users entries in OpenLDAP, locking the uid value (which can be an email).

### How to Reproduce?

Set up a Keycloak v16.1.0 (or lower) realm with OpenLDAP 2.6.0 (or lower) as user federation in writable edit mode and sync registration activated. 
Set up a custom OpenLDAP schema with a custom mandatory attribute that accept only a list of values using constraint overlay (with a regex for instance), so that any other value inserted will trigger an LDAP validation error such as "add/modify breaks constraint on myCustomAttribute".

```ldif
# Overlay for constraint
dn: cn=module,cn=config
changetype: add
cn: module
objectClass: olcModuleList
olcModuleLoad: constraint

dn: olcOverlay={0}constraint,olcDatabase={2}mdb,cn=config
changetype: add
objectClass: olcConfig
objectClass: olcOverlayConfig
objectClass: olcConstraintConfig
olcOverlay: {0}constraint
olcConstraintAttribute: myCustomAttribute regex (value1|value2)
```

First scenario:

1. create a user federation mapper for this custom attribute, indicates it's mandatory
2. create a user with REST API endpoint with an attribute EXPECTED value
3. you'll get:

Header: 400 bad request
Body: {"errorMessage": "Could not create user"}

Meaning you can't create any user with this constraint in place.

Second scenario (error case):

1. create a user federation mapper for this custom attribute, indicates it's mandatory, but also define a valid default value
2. create a user with REST API endpoint with an attribute UNEXPECTED value
3. you'll get:

Header: 400 bad request
Body: {"errorMessage": "Could not create user"}

Except that KC has initialized user entry with a space in mandatory fields (see below Apache Directory Studio screenshot). 

![Screenshot from 2022-01-28 11-45-44](https://user-images.githubusercontent.com/84727313/151533994-cded857f-5a81-4483-ad83-2c9e5cbfe687.png)

### Anything else?

One way to partially resolve this issue, at least for the ugly part, might be to have a state property on user creation workflow, which can be used to rollback in case of an exception on LDAP side when user has just been initialized.

Otherwise If mandatory attributes could be sent at once during user creation with their correct values instead of an empty space, that would leave the posibility to use OpenLDAP constraint overlay on mandatory fields.

Related to https://issues.redhat.com/browse/KEYCLOAK-4433

**Comment by vramik** [comment]
Thank you @jledoux-sonergia for the report. Could you please re-check it with latest release? If I recall correctly there might be done some changes recently regarding it. Thank you

**Comment by jledoux-sonergia** [comment]
Hey @vramik, thanks for noticing me, unfortunatly I didn't have the time to upgrade KC to the latest version, I have v16.1.1, and I haven't plan to do it in a near future since I'm working on other projects that takes all my time. But as soon as I upgrade I'll try again to activate regex constraints on mandatory fields and let you know.

**Comment by vramik** [comment]
Thanks @jledoux-sonergia, I'm closing it for now then, feel free to reopen it.
