### ISSUE TITLE
Remove old account console

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#9864]
### Description

New old FreeMarker based account console has been deprecated for a while and should be removed.

Before removing the old account console, we need to remove usage of the old account console within the testsuite. The tests should be updated to not depend on the account console at all, and should leverage the testing app for login, and the Account or Admin REST APIs for updating user accounts.

Breakdown of work needed to remove the old account console usage from the testsuite:

- [x] #15196
- [x] #15198
- [x] #15199
- [x] #15200
- [x] #15201
- [x] #15202
- [x] #15203
- [x] #20730
- [x] #19668

**Comment by stianst** [comment]
This is being postponed to Keycloak 20 due a fair bit of tests that rely on the old account console. Most should not rely on the account console at all, but rather just use it as a way to test "login" works. These will need to be rewritten to use the basic testing application that is used by for example the LoginTest.

**Comment by stianst** [comment]
The old account console was scheduled to be removed in Keycloak 19, but has been delayed due to the amount of tests depending on it. We should prioritize getting rid of it for Keycloak 21, as until it is fully removed it is still supported, although in a deprecated fashion.

**Comment by stianst** [comment]
The simplest way to update the tests may be to create an account API client library that we can use to replace the use of account UI.

**Comment by lhanusov** [comment]
@wojnarfilip @miquelsi @Aboullos This abstract class will be removed as well (within last fixed issue): https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/pages/AbstractAccountPage.java

**Comment by lhanusov** [comment]
@stianst please, can you add this GH issue to the task list -> it's the replacement for the Jira: https://github.com/keycloak/keycloak/issues/19668

**Comment by jonkoops** [comment]
I've added the new issue to the list 👍
