### ISSUE TITLE
Remove Infinispan workarounds introduced to prevent deadlocks

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#9871]
### Describe the bug

In PR #9840 we introduced a workaround with synchronization around a problematic Infinispan API in order to fix #9648 

This issue is handled upstream in https://issues.redhat.com/browse/ISPN-13664 and a fix should be available as part of 12.1.12.Final. 

<strike>This should be fixed before 17.0.0 is released. If the fix is not available in time, the workaround needs to be revisited for a performance evaluation.</strike>

### Version

17.0.0-SNAPSHOT

### Expected behavior

No workaround that impacts performance should exist

### Actual behavior

Workaround is in the code.

### Anything else?

Instead of a synchronized() block a read-write-lock could be implemented.

**Comment by hmlnarik** [comment]
> This should be fixed before 17.0.0 is released. If the fix is not available in time, the workaround needs to be revisited for a performance evaluation.

We can keep this for version 17. WF 26.0.1 contains Infinispan 12.1.7 which will not have this bug fixed. Perhaps we would be able to get this fixed in some future version of Keycloak.

**Comment by martin-kanis** [comment]
This can be done after https://github.com/keycloak/keycloak/issues/12306 is resolved.

**Comment by ahus1** [comment]
The upstream issue https://issues.redhat.com/browse/ISPN-13664 has been resolved, the same symptoms still appear when shutting down multiple instances at the same time probably due to https://issues.redhat.com/browse/ISPN-13666 which might only be solved in 14.x or later.

**Comment by ahus1** [comment]
Update: upstream issue  https://issues.redhat.com/browse/ISPN-13666 is now planned for 15.x

**Comment by ahus1** [comment]
The issue has been fixed in 14.0.13.Final which is now available in main. This now verifies the fix, and removes the workarounds.
