### ISSUE TITLE
Unable to fetch /metrics via http when https is enabled

### ISSUE THREAD

**Issue by Leletir** [keycloak/keycloak#9873]
## Context

I have activated the metrics, and I have also deactivated plain http via:

```
prod.http.enabled=false
prod.metrics.enabled=true 
```

## Problem 

But now I'm unable to fetch the metrics via http, only via https:

```
curl http://${KEYCLOAK_URL}/q/metrics => fail
curl https://${KEYCLOAK_URL}/q/metrics => success
```

Unfortunately I need Prometheus tpo fetch those mtrics via plain http.

I don't know if it's a bug a feature request.

Have a good day.

### Version

16.1.1

### Expected behavior

Fetching the metrics should work via http and not only via https.

**Comment by DGuhr** [comment]
Hey, thanks for reporting.

Not sure if we should do sth about it, though, as it exactly behaves as it should. When http is disabled, it's all or nothing. cc @pedroigor wdyt?

**Comment by stianst** [comment]
This is expected behaviour. If http is disabled http is disabled ;)
