### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by tjay31** [keycloak/keycloak#9878]
### Describe the bug

Sometimes when redirecting an authenticated user to the 'change password' page, it instead displays the sign in page (doesn't know that the user is authenticated):
```
keycloak.login({
    action: "UPDATE_PASSWORD",
})
```
After I sign in, then I see the change password page. But every time I call the block above after that, it makes the user sign in. It's like it doesn't know that the user is authenticated or keycloak is not pulling the correct refresh token? If I completely logout in my application, then log back in, it works again.

### Version

Version 11

### Expected behavior

While logged in when I call the "UPDATE_PASSWORD" action, I should get the change password page.

### Actual behavior

I actually get the sign in page. After logging in, then I get the change password page. Even after I change my password after logging in, then going back to my application, if I call the update password action again it shows me the sign in page again.

### How to Reproduce?

Log in to my application and wait about half hour, then try call update_password action.

**Comment by stianst** [comment]
It is expected behaviour to require the user to re-authenticate before updating the password.
