### ISSUE TITLE
Documentation  | RHSSO 7.5 "WRITABLE" Edit mode in Server Administrator guide

### ISSUE THREAD

**Issue by borudena** [keycloak/keycloak#9890]
### Describe the bug

Hi team,

As per RHSSO 7.5 Server Administrator guide we can see the "WRITABLE" edit mode say's "You cannot change "  [1] where I guess it should be "You can change" as the WRITABLE mode allows to change the username, email, first name, last name, and other mapped attributes and passwords and synchronize them automatically with the LDAP store. In RHSSO 7.4 documentation the "WRITABLE" mode seems to be correctly mentioned.

Please verify if it need to be updated.

**7.5 Server Administrator guide** 
[1] https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.5/html/server_administration_guide/user-storage-federation#edit_mode

**7.4 Server Administrator guide** 
https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/server_administration_guide/user-storage-federation#edit_mode

### Version

7.5

### Expected behavior

WRITABLE mode should be like 
**You can change** the username, email, first name, last name, and other mapped attributes and passwords and synchronize them automatically with the LDAP store.

**Comment by stianst** [comment]
Hi, this is not the correct place to report issues against RH-SSO. If there are some issues in the Keycloak community documentation please open another issue against that and point to where the issue is in the community documentation.
