### ISSUE TITLE
Update Portuguese (Brazil) translations

### ISSUE THREAD

**Issue by alisonbruno97** [keycloak/keycloak#9892]
### Describe the bug

Mistranslation of the word "recomece"

### Version

16.1.1

### Expected behavior

Correct spelling of the word "recomece"

### Actual behavior

The right translation for Brazilian Portuguese
Reference: https://www.dicio.com.br/recomece/

### How to Reproduce?

Exceed the time on the login screen, where the token becomes invalid, at this time the message "Você demorou muito para entrar. Por favor, recomeçe o processo de login." is displayed

**Comment by jairsjunior** [comment]
Expected behavior is the right translation for Brazilian Portuguese. 
"recomece" -> 
Reference: https://www.dicio.com.br/recomece/
