### ISSUE TITLE
Auth execution "Condition - User Attribute" missing

### ISSUE THREAD

**Issue by MetroMarv** [keycloak/keycloak#9895]
### Describe the bug

The docs on [Available conditions](https://www.keycloak.org/docs/latest/server_admin/index.html#available-conditions) mention a condition "Condition - User Attribute", but I cannot find it in the UI.

### Version

16.1.1, 15.1.1

### Expected behavior

When creating a authentication execution, I can select "Condition - User Attribute" as a provider and can configure it accordingly.

### Actual behavior

Currently I can only select 3 conditional providers:

- Conditional - User Role
- Conditional - User Configured
- Conditional OTP Form

![image](https://user-images.githubusercontent.com/9006725/151788704-fb50ca9f-1c44-49d4-94e8-cbff647e1acf.png)

### Anything else?

The [respective package in the source code](https://github.com/keycloak/keycloak/tree/main/services/src/main/java/org/keycloak/authentication/authenticators/conditional) doesn't contain a `ConditionalUserAttribute` class. But there is one class `ConditionalUserAttributeValue` inside the [testsuits package](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/servers/auth-server/services/testsuite-providers/src/main/java/org/keycloak/testsuite/authentication/ConditionalUserAttributeValue.java).

Did the `ConditionalUserAttributeValue` just end up in the wrong package?

There is also a [Discourse thread](https://keycloak.discourse.group/t/condition-user-attribute/7705) on this topic.

**Comment by MetroMarv** [comment]
Thanks a lot @mposolda!

According to the milestones, this change will be included in the new version 17.1.0 and 18.0.0 correct?

**Comment by mabartos** [comment]
@MetroMarv Yes
