### ISSUE TITLE
Make sure operator tests work with pre-built operator image

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9898]
* The operator is built independently of tests.
* The tests will accept the image coordinates for the operator image.
* The tests will run in remote mode with the provided image.

**Comment by vmuzikar** [comment]
It is probably possible to do it already, we just need to doublecheck.

**Comment by vmuzikar** [comment]
In case it is already possible, document it in README.

**Comment by DGuhr** [comment]
@vmuzikar just to make sure: you are not proposing here to do anything in CI, this should just validate for e.g. running tests locally if it works using a remote image, right? 

so e.g. running: 
```
mvn clean verify \
              -Dquarkus.container-image.build=false \
              -Dquarkus.container-image.image=quay.io/keycloak/keycloak-operator:nightly \
              -Dquarkus.kubernetes.deployment-target=kubernetes \
              -Dtest.operator.deployment=remote \

```

should download the nightly, deploy to k8s / minikube and tests should work with it?

Asking bc. i think the mechanism in the CI is totally fine and likely more performant than what you propose (just building the container image from pre-built Keycloak spares roundtrips to download stuff).

**Comment by vmuzikar** [comment]
Yes, exactly. No changes in GHA required. This is mainly for our internal QE pipelines.
