### ISSUE TITLE
Keycloak 16.1.0 - NOT able to Impersonate via REST API

### ISSUE THREAD

**Issue by naveenamruth** [keycloak/keycloak#9907]
### Describe the bug

Upgraded to Keycloak from 3.4.0 to 16.0 - Impersonation NOT working - Though KEYCLOAK_IDENTITY and KEYCLOAK_SESSION Cookie are created.

I need to provide the impersonate functionality outside of Keycloak Admin Console, the very similar to Impersonate button. What I am doing is calling Keycloak REST API for
obtaining the access_token, (auth/realms/master/protocol/openid-connect/token)
which is then parsed into another call to impersonate user admin/realms/{realm}/users/{id}/impersonation .
The second call is returning the redirect link with boolean and in the headers, there are, besides others, KEYCLOAK_SESSION and KEYCLOAK_IDENTITY cookies.

From here on post redirect to Login Page - The Keycloak Impersonation session is NOT creating instead it is just seating in Login Page

This endpoint is creating all required Usersession (UserSessionModel) and creating an LoginCookie createLoginCookie(AuthenticationManager) 
After redirection, the Keycloak couldn't able to create an impersonated login session.

Please help me with this. let me know if you need more details.

**Here is the Request (done via Angular)**
`const url = environment.BASE_URL + 'realms/master/custom/realms/REALM_NAME/users/' + userName + '/impersonation';
      const headers = new Headers();
      headers.append('Authorization', 'Bearer ' + user.adminToken);
      headers.append('Access-Control-Allow-Origin', '*')
      const options = new RequestOptions({ method: RequestMethod.Post, headers: headers });
      options.withCredentials = true;
      return this._http
        .post(url, JSON.stringify(representativeDetails), options)
        .map((response: Response) => response.json())
        .catch(this.handleErrorObservable);`

    

**Here is the Response sent from our Java application**
`return Response.ok(result)
	.header(HttpHeaders.CONTENT_TYPE, org.keycloak.utils.MediaType.APPLICATION_JSON)
	.header("Access-Control-Allow-Origin", origin)
	.header("Access-Control-Allow-Methods", CollectionUtil.join(new HashSet(Arrays.asList("GET", "PUT", "POST", "DELETE"))))
	.header("Access-Control-Allow-Headers", "Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization, Access-Control-Allow-Origin")
	.header("Access-Control-Max-Age", 1234)
	.header("Access-Control-Allow-Credentials", true)
	.header("Access-Control-Expose-Headers", "*")
	.build();`
    

Below I copied from my browser where we can see all the **Request** and **Response** Headers

**Response Headers**

`access-control-allow-credentials: true
access-control-allow-headers: Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization, Access-Control-Allow-Origin
access-control-allow-methods: DELETE, POST, GET, PUT
access-control-allow-origin: https://DOMAINNAME.COM
access-control-expose-headers: *
access-control-max-age: 1234
cache-control: NO-CACHE
content-length: 108
content-type: application/json
date: Fri, 28 Jan 2022 20:31:19 GMT
p3p: CP="This is not a P3P policy!"
pragma: NO-CACHE
referrer-policy: no-referrer
set-cookie: KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiIsInXXXXXXX--------tm_sC4lnc; Version=1; Path=/; SameSite=None; Secure; HttpOnly
set-cookie: KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInXXXXXXX--------tm_sC4lnc; Version=1; Path=/; Secure; HttpOnly
set-cookie: KEYCLOAK_SESSION=REALM_NAME/065ec370-e803-4351-9a06; Version=1; Expires=Mon, 07-Feb-2022 20:31:19 GMT; Max-Age=864000; Path=/; SameSite=None; Secure
set-cookie: KEYCLOAK_SESSION_LEGACY=REALM_NAME/065ec370-e803-4351-9a06; Version=1; Expires=Mon, 07-Feb-2022 20:31:19 GMT; Max-Age=864000; Path=/; Secure
set-cookie: AUTH_SESSION_ID=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/; Secure; HttpOnly
set-cookie: KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/; Secure; HttpOnly
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block`

**Request Headers**

`:authority: SSO_BASE_URL.COM
:method: POST
:path: /auth/realms/master/custom/realms/REALM_NAME/users/USER_ID/impersonation
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,hi;q=0.8,en-IN;q=0.7
access-control-allow-origin: *
authorization: Bearer TOKEN_TOKEN_TOKEN
cache-control: no-cache
content-length: 36
content-type: application/json
cookie: AUTH_SESSION_ID=d1d12d09-3; 
AUTH_SESSION_ID_LEGACY=d1d12d09-3; 
KEYCLOAK_SESSION=master/eda99620-92e2-4; 
KEYCLOAK_SESSION_LEGACY=master/eda99620-92e2-4; 
KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiI------------; KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiI------------;
LanguageDisplayDirection=ltr; 
SplashScreen=false; 
cookiebanner=false; 
origin: https://DOMAINNAME.COM
pragma: no-cache
referer: https://DOMAINNAME.COM/
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

Here is the code base I am using
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java

### Version

16.1.0

### Expected behavior

obtaining the access_token, (auth/realms/master/protocol/openid-connect/token) which is then parsed into another call to impersonate user admin/realms/{realm}/users/{id}/impersonation . The second call is returning the redirect link with boolean and in the headers, there are, besides others, KEYCLOAK_SESSION and KEYCLOAK_IDENTITY cookies.

Upon redirecting to Login Page the Impersonation session should initiate instead it is just seating in Login Page

### Actual behavior

Its just seating in Login Page - doing NOTHING

### How to Reproduce?

Extend the org.keycloak.services.resource.RealmResourceProviderFactory 
and using the impersonate method to create a userSession and Login Cookie
same like
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java
and
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java

**Comment by cilf** [comment]
FYI `preview token exchange` was not working for our case because we really needed the keycloak session to change - we have multiple services using keycloak as SSO provider.

I can confirm impersonation from outside the keycloak admin console works in keycloak v22.0.0

**Comment by nesro** [comment]
Hi @cilf 
you wrote:
> I can confirm impersonation from outside the keycloak admin console works in keycloak v22.0.0
I need to impersonate the user with REST API, I'm trying the /impersonate endpoint from https://www.keycloak.org/docs-api/latest/rest-api/index.html and I'm getting 403 error. My admin account has the role role_impersonation set.
Can you please elaborate how did you make it work?

**Comment by cilf** [comment]
@nesro hi,
I am calling URL

```
POST http://abcd/auth/admin/realms/xyz/users/d789f3c2-2ae3-4fed-a27f-a6efea029c2b/impersonation
```

with body 
```
{"realm":"xyz","user":"d789f3c2-2ae3-4fed-a27f-a6efea029c2b"}
```

authed by the `Authorization: Bearer eyJhbGciOiJSU...` which has like

```
{
  "resource_access": {
    "realm-management": {
      "roles": [
        "impersonation",
        "manage-users",
        "view-users",
        "manage-clients",
        "query-groups",
        "query-users"
      ]
    },
    ...
}
```
- but probably only having `"impersonation"` role could be enough

You could check keycloak with debug log level set to see what it complains about when trying to impersonate.

**Comment by nesro** [comment]
Hi @cilf thanks, I was able to make it work with the `/impersonation` endpoint in the end. But this endpoint did return me a cookie, which is not what what I wanted.

To solve my problem, I used the token exchange feature and it works like a charm. There is the target user access token in the response. I am able to impersonate another user API calls using this access token.

```
const response = await axios.post(
        `${keycloakBaseUrl}/realms/${realm}/protocol/openid-connect/token`,
        new URLSearchParams({
            grant_type: 'urn:ietf:params:oauth:grant-type:token-exchange',
            client_id,
            client_secret,
            subject_token: adminAccessToken,
            requested_subject: user.id,
            scope: 'openid profile email',
            requested_token_type: 'urn:ietf:params:oauth:token-type:access_token',
        }),
        {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
        },
    );
```

**Comment by cdecinkoKnight** [comment]
You were able to make API calls but you were still unable to set the cookies? That's where I'm stuck, trying to set Keycloak cookies from my application that gets the impersonation token. Different domains.

**Comment by nesro** [comment]
> You were able to make API calls 

I'm logging in with a service account:
```
const kcAdminClient = new KeycloakAdminClient({
        baseUrl: keycloakBaseUrl,
        realmName: realm,
    });
    await kcAdminClient.auth({
        grantType: 'client_credentials',
        clientId,
        clientSecret,
    });
    const adminAccessToken = kcAdminClient.accessToken;
```

Now can I call any API endpoints.
