### ISSUE TITLE
Integration with oicd adpater EAP - KEYCLOACK does not work properly when resources are auth free

### ISSUE THREAD

**Issue by elguardian** [keycloak/keycloak#9918]
### Describe the bug

At present web resource collection seems not be handle correctly when they merge cause a forbidden access to anonymous resources

### Version

16.1.1

### Expected behavior

GET http://localhost:8080/helloworld/HelloWorld 

you can see the page

### Actual behavior

GET http://localhost:8080/helloworld/HelloWorld 

you get 403

### How to Reproduce?

vanilla installation wildfly
https://download.jboss.org/wildfly/23.0.1.Final/wildfly-23.0.1.Final.zip

vanilla installation keyloack
https://github.com/keycloak/keycloak/releases/download/16.1.1/keycloak-16.1.1.zip

start keycloack  ./bin/standalone.sh -Djboss.socket.binding.port-offset=100
configure keycloack
- add realm demo
-- add client (openid)
add role admin (set its password)
create user "user" and add admin to its role mapping

follow this over wildfly vanilla installation
https://www.keycloak.org/docs/latest/securing_apps/#_jboss_adapter
https://github.com/keycloak/keycloak/releases/download/16.1.1/keycloak-oidc-wildfly-adapter-16.1.1.zip

./bin/standalone.sh 
./bin/jboss-cli.sh --file=bin/adapter-elytron-install.cli

follow https://www.keycloak.org/docs/latest/securing_apps/index.html#_jboss_adapter
 > Securing WARs via Adapter Subsystem

copy paste installation keycloak into wildlfy
keycloack oidc jboss subsystem xml

<secure-deployment name="WAR MODULE NAME.war">
    <realm>demo</realm>
    <auth-server-url>http://localhost:8180/auth/</auth-server-url>
    <public-client>true</public-client>
    <ssl-required>EXTERNAL</ssl-required>
    <resource>helloworld</resource>
</secure-deployment>

deploy helloworld app

access https://localhost:8443/helloworld/HelloWorld

GET http://localhost:8080/helloworld/HelloWorld 

> outcome 403 forbidden when it should be anonymous access ok.

### Anything else?

files for creating the webapp

https://gist.github.com/elguardian/8972f12bfc18087be804879ce1676ef9

**Comment by sguilhen** [comment]
I was able to reproduce the Forbidden error even **without** keycloak adapters involved. I just downloaded vanilla WildFly 23 using your link, didn't install any keycloak adapters, simply deployed the war from this quickstart https://github.com/keycloak/keycloak-quickstarts/blob/latest/app-profile-jee-vanilla (changed the `web.xml` to include the `<deny-uncovered-http-methods/>`) and tried to access it. WildFly promptly gave me a 403 without even displaying the Basic Auth Dialog Box (this particular quickstart uses BASIC by default).

If I install the keycloak adapters I also get the 403 and the app doesn't even redirect to Keycloak for authentication. I suspect Elytron is denying access beforethe adapters are even involved in the process, which prevents the redirection for authentication.
