### ISSUE TITLE
Bug when updating user attributes with duplicated values

### ISSUE THREAD

**Issue by fperot74** [keycloak/keycloak#9920]
### Describe the bug

Hi,

We are trying to update an user attribute :
* my-attribute = [ “A”, “B” ]
with the new value :
* my-attribute = [ “B”, “B” ]

In DefaultUserProfile.java#L116, Keycloak is checking if values are updated like this :
```
    if (currentValue.size() != updatedValue.size() || !currentValue.containsAll(updatedValue)) {
        …
    }
```
As size are the same, it checks if currentValue contains all values from updatedValue… As updatedValue contains twice the same value which is also contained once in currentValue, Keycloak considers that my-attribute value has not been updated.

currentValue and updatedValue are lists created just before the if statement using streams… if those streams are sorted and containsAll replaced by equals, it should fix the issue. (a little bit less performant but I suppose we would not be sorting thousands of values)

### Version

14.0 to 16.1.1

### Expected behavior

When updating a user with an attribute with values [ A, B ] becoming [ B, B ], the user should be updated in Keycloak

### Actual behavior

When updating a user with an attribute with values [ A, B ] becoming [ B, B ], the update is not effective and values remain [ A, B ]

### How to Reproduce?

Go to admin console, choose a user, select "Attributes" tab and add this attribute : `myAttribute = A##B`, then save
Choose another tab then come back to "Attributes" tab. Value is still A##B or B##A.
Edit attribute and change value to B##B, then save. You get a confirm message and new value B##B is displayed.
If you choose another tab then come back, you can notice that the value has not been updated and remains A##B

**Comment by fperot74** [comment]
Watching at the code, it seems we should use `CollectionUtil.collectionEquals(...)` from keycloak-common and rewrite this method which suffers the same issue.
I already detected an issue 2 years ago in MultivaluedHashMap which was partially solved but can be improved (would not make a difference between [ A, A, B ] and [ A, B, B ]). MultivaluedHashMap could use `CollectionUtil.collectionEquals(...)` too.

**Comment by ahus1** [comment]
PR arrived: #9940
