### ISSUE TITLE
Add read-only LDAP implementation for roles

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9928]
Read-only implementation of LDAP map storage.

**Comment by ahus1** [comment]
Current state of work is here: https://github.com/ahus1/keycloak/tree/9928-map-ldap-roles

**Comment by ahus1** [comment]
@hmlnarik - I wonder if the LDAP implementation needs the same lazy loading like JpaClientDelegateProvider supports, that is: only read some fields at the beginning, and then add all fields/attributes once needed. Please let me know what you think.

**Comment by ahus1** [comment]
@hmlnarik - decided to not to have a delegate for now. Reused the existing LDAP logic as much as possible, especially LDAPConfig, Condition and LDAPIdentityStore. Pushed the changes to the branch listed above. 

I suggest to look at it together when time permits for an intermediate feedback.

**Comment by ahus1** [comment]
Pushed a first version of multi-realm and client roles support.

While support for reading attributes is missing, will now investigate how to add write support. This will allow me to gather more questions for upcoming discussions around LDAP.

**Comment by ahus1** [comment]
There will be no separate PR for read-only roles. Therefore closing this issue. Please follow issue #9929 to find out how development for role support continues.
