### ISSUE TITLE
Read-write LDAP implementation for roles

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9929]

**Comment by ahus1** [comment]
@hmlnarik - I wonder if LDAP should support composite roles, or if this is something that would be added by the tree store. If it should be supported by LDAP, I'd need some advice how this could be modeled in LDAP.

**Comment by hmlnarik** [comment]
@ahus1 If roles are modeled as LDAP groups, group membership would be natural way to tracking composition. This is indeed not generic enough for generic storage composition where a separate attribute with the role ID would need to be maintained both at the role parent and role child (parent-child as in the composition graph).

**Comment by ahus1** [comment]
@hmlnarik - I found that I could implement composite roles using just the "member" attribute.

**Comment by ahus1** [comment]
@hmlnarik - I found that I could implement composite roles using just the "member" attribute at least for those cases where the composite roles are part of the same LDAP. Could composite roles outside of the same LDAP be handled in the tree store?

**Comment by ahus1** [comment]
There is now a documentation on how to run the current state of development. It also includes the branch: https://github.com/keycloak/keycloak/discussions/10254
// cc: @hmlnarik
