### ISSUE TITLE
Credential validation for user storage

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#9932]
### Description

Design and develop a mechanism for credential validation on physical layer.

In the current store, credential validation is done in implementations of [`CredentialInputValidator`](https://github.com/keycloak/keycloak/blob/main/server-spi/src/main/java/org/keycloak/credential/CredentialInputValidator.java) interface in the logical layer. This has to be modified to support credential manipulation / validation on physical layer.

**Comment by hmlnarik** [comment]
Idea: The validation, rather than on store provider level, could be done on single user level. That means that individual entities would be able to leverage credential validation mechanism available by that particular technology.

**Comment by ahus1** [comment]
I'd be happy to discuss what would be necessary here as it is one of the next things necessary for the LDAP implementation. 

I haven't worked with these APIs before, still I wonder if 
* an LdapMapUserCredentialEntity could contain "just" the DN plus plus some LDAP meta information, that is then copied to the CredentialModel; secretData would be empty 
* an LdapCredentialInputValidator that would use these to validate a CredentialInput of PasswordUserCredentialModel to run it agains the LDAP server

Please let me know what you think.

**Comment by ahus1** [comment]
Started a discussion for this: #10833

**Comment by hmlnarik** [comment]
Implemented in 19.0.0 (#11933) as [UserModel.credentialManager()](https://github.com/keycloak/keycloak/blob/19.0.0/server-spi/src/main/java/org/keycloak/models/UserModel.java#L301-L304)
