### ISSUE TITLE
Admin CLI - Unable to manage other realms as admin

### ISSUE THREAD

**Issue by mickelsonmichael** [keycloak/keycloak#9948]
### Describe the bug

It appears that the `admin` account built-in to Keycloak doesn't have permissions to access other realms besides the `master` realm. I would expect that the admin account should be able to manage all realms as it can in the web GUI. Is this a bug or is this intended?

```powershell
> $server
http://host.docker.internal:8888/auth
> kcadm config credentials --server $server --user admin --password admin --realm master
Logging into http://host.docker.internal:8888/auth as user admin of realm master
> kcadm get clients --realm saas --fields id,clientId,redirectUris -x
null [HTTP 401 Unauthorized]
org.keycloak.client.admin.cli.util.HttpResponseException: null [HTTP 401 Unauthorized]
        at org.keycloak.client.admin.cli.util.HeadersBodyStatus.checkSuccess(HeadersBodyStatus.java:61)
        at org.keycloak.client.admin.cli.util.HttpUtil.checkSuccess(HttpUtil.java:353)
        at org.keycloak.client.admin.cli.commands.AbstractRequestCmd.process(AbstractRequestCmd.java:363)
        at org.keycloak.client.admin.cli.commands.AbstractRequestCmd.execute(AbstractRequestCmd.java:126)
        at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:63)
        at org.jboss.aesh.console.command.container.DefaultCommandContainer.executeCommand(DefaultCommandContainer.java:48)
        at org.keycloak.client.admin.cli.aesh.AeshConsoleCallbackImpl.execute(AeshConsoleCallbackImpl.java:54)
        at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: {"error":"HTTP 401 Unauthorized"}
        ... 11 more
```

I can eventually work around it, I think, by creating a new user, giving them admin privileges, and then using the new account to manage the client, but this feels like a hacky workaround.

If I attempt to login to the particular realm specifically, I get an `invalid_grant` rejection.

```powershell
> kcadm config credentials --server $server --user admin --password admin --realm saas
Logging into http://host.docker.internal:8888/auth as user admin of realm saas
Invalid user credentials [invalid_grant]
```

### Version

16.1.1

### Expected behavior

The `admin` user should be able to manage all resources within the keycloak server regardless of whether or not it is using the web GUI or the Admin CLI.

### Actual behavior

The `admin` user gets a `401 Unauthorized` when it attempts to manage other realms.

### Anything else?

Edit: Per the response below, if you use `-r` instead of `--realm`, the command succeeds, so it would appear to be a bug in the long-form version of the option

**Comment by tkautenburger** [comment]
Just had the same bug. the `--realm otherRealm` argument does not work performing operations in another realm, if you use the `-r otherRealm`short version instead, it works perfectly

**Comment by mickelsonmichael** [comment]
> Just had the same bug. the `--realm otherRealm` argument does not work performing operations in another realm, if you use the `-r otherRealm`short version instead, it works perfectly

I can confirm that this fixed the issue still using v16.1.1. Thanks a lot @tkautenburger, much appreciated for the workaround!

**Comment by filipetavares** [comment]
Can confirm that it still happens in v19.0.0, but it seems that `-r` is bugged as well if you use it with `--no-config`:
```
> ./bin/kcadm.sh get users -r master --no-config --server=http://localhost:8080 --user admin --password admin
Illegal state - no current realm in config data
```
But with `--realm` it works:
```
> ./bin/kcadm.sh get users --realm master --no-config --server=http://localhost:8080 --user admin --password admin
Logging into http://localhost:8080 as user admin of realm master
[ {
  "id" : "d6ed1b62-1e26-4a19-a201-f0d38743f2a7",
  "createdTimestamp" : 1658249251800,
  "username" : "admin",
   ...
} ]
```

**Comment by Pepo48** [comment]
I can reproduce this issue. I'll take a look at it.

**Comment by Pepo48** [comment]
Since there are no more replies I’m going to close this one for now, but you can always reopen it later if you have more questions or feedback.

Thanks everybody for the cooperation.

**Comment by ldicarlo** [comment]
Hey @Pepo48. FYI I feel like this issue still exists.
I am using keycloak 26.3 and:
`/opt/keycloak/bin/kcadm.sh get clients --realm <not master>` does not work ( `401 error`)
while 
`/opt/keycloak/bin/kcadm.sh get clients -r <not master>` works perfectly fine.

**Comment by shawkins** [comment]
@ldicarlo -r is a short-cut for target-realm, not realm.
