### ISSUE TITLE
Keycloak.X: MSSQL db connection string construction issue

### ISSUE THREAD

**Issue by epuronta** [keycloak/keycloak#9957]
### Describe the bug

Checking out Keycloak.x 16.1.1 with openjdk 11.0.14 on Debian 10.

I was trying to connect to MSSQL database with the following configuration in `keycloak.properties`:

```
db=mssql
db.username=user
db.password=pw
db.url=jdbc:sqlserver://mydbserver;databaseName=MyDb;
```

Executing `show-config` displays that when the actual `kc.db.url` is constructed, `jdbc:mssql` is used instead of the configured `jdbc:sqlserver`.

```
./bin/kc.sh show-config
Current Profile: none
Runtime Configuration:
        kc.db =  mssql (PersistedConfigSource)
        kc.db.password =  ******* (PersistedConfigSource)
        kc.db.url =  jbcd:mssql://mydbserver/MyDb(PersistedConfigSource)
        kc.db.username =  user(PersistedConfigSource)
        kc.version =  16.1.1 (KcSysPropConfigSource)
```

This in turn causes problems with MSSQL JDBC driver, which seems to very much expect the `jdbc:sqlserver` part.

```
./bin/kc.sh start-dev

WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: com.microsoft.sqlserver.jdbc.SQLServerException: The connection string contains a badly formed name or value.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
        at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnectionInternal(SQLServerDataSource.java:1050)
        at com.microsoft.sqlserver.jdbc.SQLServerPooledConnection.createNewConnection(SQLServerPooledConnection.java:81)
        at com.microsoft.sqlserver.jdbc.SQLServerPooledConnection.<init>(SQLServerPooledConnection.java:56)
        at com.microsoft.sqlserver.jdbc.SQLServerXAConnection.<init>(SQLServerXAConnection.java:36)
        at com.microsoft.sqlserver.jdbc.SQLServerXADataSource.getXAConnection(SQLServerXADataSource.java:60)
        at com.microsoft.sqlserver.jdbc.SQLServerXADataSource.getXAConnection(SQLServerXADataSource.java:92)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:509)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Finally, I figured out that if I start the server supplying the `--db-url`  as a runtime parameter, the `sqlserver` seems to not get overwritten despite the `mssql` driver obviously being used, and connection proceeds as expected (tries to connect to the correct server).

```
./bin/kc.sh start-dev --db-url jdbc:sqlserver://mydbserver
```

With this config, the connection now fails due to invalid credentials (trying to log in as `sa` user). Adding credentials as runtime parameters as well, the connection proceeds further. This time, it fails to create a lock table on `master` database (default, as I am now not supplying the database name).

```
./bin/kc.sh start-dev --db-url jdbc:sqlserver://mydbserver --db-username user --db-password pw
ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.DatabaseException: CREATE TABLE permission denied in database 'master'. [Failed SQL: CREATE TABLE [guest].[DATABASECHANGELOGLOCK] ([ID] [int] NOT NULL, [LOCKED] [bit] NOT NULL, [LOCKGRANTED] [datetime2](3), [LOCKEDBY] [nvarchar](255), CONSTRAINT [PK_DATABASECHANGELOGLOCK] PRIMARY KEY ([ID]))]
```

I am now stuck, as neither of the two possibilities for supplying the correct database name seem to work.

The `--db-url-database` seems to get ignored:

```
./bin/kc.sh start-dev --db-url jdbc:sqlserver://mydbserver --db-username user --db-password pw --db-url-database MyDb

ERROR [org.key.qua.run.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.DatabaseException: CREATE TABLE permission denied in database 'master'. [Failed SQL: CREATE TABLE [guest].[DATABASECHANGELOGLOCK] ([ID] [int] NOT NULL, [LOCKED] [bit] NOT NULL, [LOCKGRANTED] [datetime2](3), [LOCKEDBY] [nvarchar](255), CONSTRAINT [PK_DATABASECHANGELOGLOCK] PRIMARY KEY ([ID]))]
```

And using `databaseName` in the actual URL drops the username parameter, reverting to log in as `sa` again.

```
./bin/kc.sh start-dev --db-url jdbc:sqlserver://mydbserver;databaseName=MyDb; --db-username user --db-password pw

WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'
```

Finally, supplying everything that should be necessary in the `--db-url` still makes it attempt to log in as `sa`.

```
./bin/kc.sh start-dev --db-url jdbc:sqlserver://mydbserver;databaseName=MyDb;username=user;password=pw;

WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'.
```

I am at a loss and unable to proceed.

**Comment by epuronta** [comment]
Also related minor issue. I could not figure out how to print the actual runtime configuration (similar to `kc.sh show-config`) when using `start-dev`. That would have made this a lot easier to diagnose.

**Comment by DGuhr** [comment]
Hey @epuronta, thanks for reporting! :) 

Your issue might be related to #9519, we'll look into it. 

Also, for the minor issue, see #9525 - I'll re-test this now with the latest main, as @pedroigor could not reproduce that anymore, so should be fixed.

**Comment by pedroigor** [comment]
@epuronta I'm not sure from where `jdbc:mssql` is coming from because the URL we use is `jdbc:sqlserver`.

When you set the `db-url`, any other option prefixed with `db-url` are not going to take any effect. That is why you can not set the database using `db-url-database`.

W.r.t. to the CLI, you should escape the `db-url` value as follows. Otherwise, it will understand that you are ending the command.

```
--db-url "\"jdbc:sqlserver://localhost;databaseName=keycloak3;username=user;password=pw""
```

For last, when you are passing credentials within the `db-url` the credentials are going to be ignored and the values from `db-username` and `db-password` are going to be used. And here I think we have an unexpected behavior because if you only provide the `db-url` with all credentials but no `db-username` and `db-password`, the default values from these options are going to be used. That is why you still see the database complaining about the user `sa` as it is the default value for `db-username`.

For now, you can consider removing credentials from the `db-url` and use the `db-username` and `db-password` instead. I'm going to create an issue to improve this behavior and allow using the `db-url` as the source for credentials.

**Comment by epuronta** [comment]
I seem to be at fault somehow, even though I cannot understand how I got it wrong so thoroughly. Perhaps I've misunderstood the relationship between the runtime profiles, `build` command and `start-dev` command. How I assumed I should be doing this:
- Apply configuration changes to keycloak.properties
- Run `kc.sh show-config` to see what I've configured and about to go "live" with
  - This seems to be where I was wrong
- Run `kc.sh start-dev` which auto-builds the config and starts the server

Instead, it seems I should have always done `build` before `show-config`.

And it seems that somehow start-dev auto-building did not happen. I assume it's supposed to always auto-builds, because trying to hand it the auto-build flag outputs a duplicate flag error.

```
./bin/kc.sh start-dev --auto-build
option '--auto-build' should be specified only once
```

Anyway, after putting the exact same config I listed in the starting post, doing a `build` and then `start-dev`, the database connection seems to work as expected.

Now I'm getting exceptions when XA control connections (whatever they are) are being created, but that's probably not related to this topic. :)

**Comment by epuronta** [comment]
To sum up, maybe there's something to improve in the configuration mechanism, but clearly, this was mostly me making human mistakes.

**Comment by pedroigor** [comment]
@epuronta Not really. Your mistake is a signal that we are failing to make it trivial to use :)

**Comment by epuronta** [comment]
@pedroigor indeed, I'm happy to be your test subject. :) Carry on the good work!
