### ISSUE TITLE
Support OpenJDK 17

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#9971]
### Description

Add support for building and running Keycloak with OpenJDK 17

### Related issues

- #8889 
- #9945
- #9899

**Comment by DGuhr** [comment]
Also related: #9993

**Comment by ruckc** [comment]
Of note, needed to upgrade hibernate to 5.6 to get past JPA errors with class version 61 in `Keycloak Model Map JPA`

```
Failed to execute goal org.hibernate.orm.tooling:hibernate-enhance-maven-plugin:5.3.20.Final:enhance (default) on project keycloak-model-map-jpa: Unable to enhance class: JpaClientDelegateProvider.class: Failed to enhance class org.keycloak.models.map.storage.jpa.client.delegate.JpaClientDelegateProvider: Unsupported class file major version 61
```

**Comment by tsaarni** [comment]
I had two more compilation problems when trying build with JDK17 which I attempt to address with PRs #13619 and #13621.
